### ISSUE TITLE
cpp_infer - args.cpp 中 gpu_mem 的参数说明与实际不符

### ISSUE THREAD

**Issue by hiroi-sora** [PaddlePaddle/PaddleOCR#10007]
一个不影响运行的小错误。

[PaddleOCR/deploy/cpp_infer/src/args.cpp 第21行](https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/deploy/cpp_infer/src/args.cpp#L21) ：
```
DEFINE_int32(gpu_mem, 4000, "GPU id when infering with GPU.");
```

gpu_mem 的实际意义是`申请的GPU内存`，而代码中的说明 `GPU id when infering with GPU.` 与之不符。

**Comment by hiroi-sora** [comment]
另外，33行limit_type的说明建议改为：
`"limit_type of input image, the value is selected in ['max','min']."`

第39行det_db_score_mode的说明建议改为：
`Whether use polygon score, the value is selected in ['slow','fast'].`

第48行rec_batch_num的说明建议改为：
`rec batchsize`

[cpp_infer中文文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme_ch.md) 中`表格识别模型相关`部分的排版有些错误。另外文档中对参数的解释也不是很全（需要配合[inference_args.md](https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/doc/doc_ch/inference_args.md)），希望以后能补充。

**Comment by andyjpaddle** [comment]
感谢反馈，我们后续会更新

**Comment by hiroi-sora** [comment]
然而 release/2.7 里一个都没有改😂
