### ISSUE TITLE
en_PP-OCRv3_rec 预训练模型上训练自己数据集， train acc一直在0.8附近不再上升， eval acc为1

### ISSUE THREAD

**Issue by JudyTanHH** [PaddlePaddle/PaddleOCR#10001]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： ubuntu 5.14.0-1059-oem
- 版本号/Version：Paddle：paddlepaddle-gpu (2.4.2.post116 )  PaddleOCR： PaddleOCR-release-2.6 问题相关组件/Related components：识别模型训练
- 运行指令/Command Code：
 python -m paddle.distributed.launch --gpus '0,1'  tools/train.py -c  en_PP-OCRv3_rec_judy_0518_6W.txt
- 完整报错/Complete Error Message：
配置文件：
[en_PP-OCRv3_rec_judy_0518_6W.txt](https://github.com/PaddlePaddle/PaddleOCR/files/11527892/en_PP-OCRv3_rec_judy_0518_6W.txt)

后来再尝试过增大学习率，增大epoch_num，但效果都不是太好，train acc提升还是很慢， 一直都是eval acc 大于train acc。
1) lr: 0.00025  epoch_num: 250, train acc 在0.78左右徘徊 
（best metric, acc: 0.9976722853934737, is_float16: False, norm_edit_dis: 0.9988968833771118, fps: 1159.9753409509458, best_epoch: 145）
2) lr: 0.0004 epoch_num: 300, train_acc 在0.81左右徘徊 
( best metric, acc: 0.9997582586625638, is_float16: False, norm_edit_dis: 0.999990924555799, fps: 1160.236232851422, best_epoch: 296)
3) lr:0.0006  epoch_num：500
（正在训练中... ）
![1](https://github.com/PaddlePaddle/PaddleOCR/assets/130292354/fab98ed0-184c-401a-b675-06e5af7f5f9b)
![2](https://github.com/PaddlePaddle/PaddleOCR/assets/130292354/79a1eec8-e4bc-48f9-9bc6-e8308100cb3b)
![3](https://github.com/PaddlePaddle/PaddleOCR/assets/130292354/cb2f3878-7b81-48f5-8ff0-0c9a8123502a)

1.eval acc 一直大于train acc是个正常的现象吗？ 
2.train acc在0.8 左右徘徊是否是合理的呢？ 有没有说法在哪个范围内说明模型比较好呢？ 
3.如果希望进一步提升train acc，可以做哪些尝试呢？

**Comment by WYH150123** [comment]
eval acc 大于 train acc的原因是config中Aug（- RecAug:）是打开的，也就是训练的样本比评估的样本难，这是正常现象

**Comment by GanWang** [comment]
遇到相似的情况，你的后续呢？train acc是否提升了？测试效果是否OK？

**Comment by JudyTanHH** [comment]
> 遇到相似的情况，你的后续呢？train acc是否提升了？测试效果是否OK？

查了些资料都是如上面所说RecAug是打开的，所以acc没法进一步提升，暂时忽略了该现象，目前rec模型还凑合
