### ISSUE TITLE
Add language to PPOCRLabel Gui

### ISSUE THREAD

**Issue by Kassy607** [PaddlePaddle/PaddleOCR#10008]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

How can I add arabic language to the PPOCRLabel Gui?

**Comment by andyjpaddle** [comment]
you can change this [line](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel/PPOCRLabel.py#L97) following this [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/whl_en.md#3-use-custom-model),  then rebuild and install this package following this [doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel#123-build-and-install-the-whl-package-locally)

**Comment by Kassy607** [comment]
Thanks @andyjpaddle ! In the code directly its working fine for me but i wanted to add it here: 
![grafik](https://github.com/PaddlePaddle/PaddleOCR/assets/118922869/c5c12551-2f52-4fc5-a20d-1ec0bbced706)

**Comment by Kassy607** [comment]
I already tried that i added: 
lg_idx = {'Chinese & English': 'ch', 'English': 'en', 'French': 'french', 'German': 'german',
                  'Korean': 'korean', 'Japanese': 'japan', 'Arabic': 'ar'}
 self.comboBox.addItems(['Chinese & English', 'English', 'French', 'German', 'Korean', 'Japanese', 'Arabic'])

and then installed PPOCR new with: pip install PPOCRLabel (Do I need to uninstall it first?) 

Thanks for your help! @andyjpaddle

**Comment by andyjpaddle** [comment]
> then rebuild and install this package following this [doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel#123-build-and-install-the-whl-package-locally)

reinstall by this way

**Comment by andyjpaddle** [comment]
> lg_idx = {'Chinese & English': 'ch', 'English': 'en', 'French': 'french', 'German': 'german',
> 'Korean': 'korean', 'Japanese': 'japan', 'Arabic': 'ar'}

the actual model name following this [line](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py#L121), that means `'Arabic': 'arabic'`

**Comment by Kassy607** [comment]
Thanks @andyjpaddle  now I can see the option Arabic in the combo box. But I get this error (I copied also the warning, maybe it helps): 
[2023/05/23 10:48:47] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Arabic
[2023/05/23 10:51:59] ppocr ERROR: lang arabic is not support, we only support dict_keys(['en', 'ch']) for layout models

**Comment by Kassy607** [comment]
okay I got it! I changed something in paddleocr.py 
You create there the dict MODEL_URLS and I changed added arabic here ( i just copied it from 'ch'): 
'layout': {
                'en': {
                    'url':
                        'https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_infer.tar',
                    'dict_path':
                        'ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt'
                },
                'ch': {
                    'url':
                        'https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar',
                    'dict_path':
                        'ppocr/utils/dict/layout_dict/layout_cdla_dict.txt'
                },
                'arabic': {
                    'url':
                        'https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar',
                    'dict_path':
                        'ppocr/utils/dict/layout_dict/layout_cdla_dict.txt'
                }

It works, but maybe its not like it used to be ....

**Comment by andyjpaddle** [comment]
pls show me the visualized error message

**Comment by Sayaka91** [comment]
@Kassy607 @andyjpaddle Any information about this error? I got a similar error when changing `lang` to `japan`

`[2023/05/24 09:47:17] ppocr ERROR: lang japan is not support, we only support dict_keys(['en', 'ch']) for layout models`

**Comment by andyjpaddle** [comment]
> This was the error: [2023/05/23 10:51:59] ppocr ERROR: lang arabic is not support, we only support dict_keys(['en', 'ch']) for layout models

according to this error, that's because the Structure model only support ['ch', 'en'], so if you only use the OCR model, you can add a fake model to table and layout params in [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py#L276-L299) and then reinstall paddleocr by this way
```
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl
```

**Comment by KhanhHH** [comment]
any news on this?

**Comment by Sayaka91** [comment]
I just use this tool for detection, recognition and kie. 
So I just replace the `lang` value in PPOCRLabel.py by my language, and it works

**Comment by abdelmageed95** [comment]
I modify PPOCRLabel.py and paddleocr.py and add Arabic to the GUI for auto-recognition  --> go to this fork
https://github.com/abdelmageed95/PaddleOCR/tree/release/2.7

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/83831812/f4b5e0e8-3342-4c6e-8137-8e9424f58da9)

auto-recognition

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/83831812/fbc9a80d-91ae-4bef-8dbe-1066da7b348b)

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/83831812/dca987e4-6bc0-4380-8205-0e5392c1d2a5)
