### ISSUE TITLE
数字 0 与 大写字母 O 经常识别错误，有没有建议可以改善呢？

### ISSUE THREAD

**Issue by JudyTanHH** [PaddlePaddle/PaddleOCR#10003]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：
版本号/Version：Paddle：paddlepaddle-gpu (2.4.2.post116 ) PaddleOCR： PaddleOCR-release-2.6 问题相关组件/Related components：识别模型训练
运行指令/Command Code：
完整报错/Complete Error Message：

目前在做护照相关的ocr识别，其中护照资料页底部的mrz区域为44字符的长文本。 
如图：
![5](https://github.com/PaddlePaddle/PaddleOCR/assets/130292354/294a4432-c128-4232-bf9e-8212886d5fe0)

使用官方提供的det/rec en_pp-OcrV3 模型时，0 与 O识别错的概率还蛮大，考虑自己训模型，目前0 与O识别错的概率有所降低，但还是存在错误。参与训练的数据集是自己造的，一定程度上有注意0 与O的分布， 可以怎么进一步改善呢？ 有没有什么建议呢？
下图中标红的都是错误的将大写字母 O 识别成了数据0

![4](https://github.com/PaddlePaddle/PaddleOCR/assets/130292354/11ae1f22-f0e3-46b8-87e5-e36a44a3032d)

**Comment by super-tian** [comment]
调整img_shape应该可以有一定提升

**Comment by JudyTanHH** [comment]
> 护照mrz区域格式应该是固定的,比如第多少位只能是字母,多少位只能是数字,通过代码给纠错就好了

固定区域能调整的通过代码纠错了，有些位置是不同国家的填充码，每个国家的规则似乎不同，有些国家是数字有些国家是字母。

**Comment by JudyTanHH** [comment]
> 护照mrz区域格式应该是固定的,比如第多少位只能是字母,多少位只能是数字,通过代码给纠错就好了
固定区域能调整的通过代码纠错了，有些位置是不同国家的填充码，每个国家的规则似乎不同，有些国家是数字有些国家是字母。

**Comment by JudyTanHH** [comment]
> 调整img_shape应该可以有一定提升
调整img_shape后确实有一定程度上的提升， 其他的错误只能通过代码来纠错了
