### ISSUE TITLE
paddleLaber 表格识别，det框都有点偏下，导致excel中的数据两行会合并成一行

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#10010]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/49ebeecd-f903-42f7-9003-039ea2757f07)

**Comment by rexzhengzhihong** [comment]
后处理要要怎么加自己的调整？有例子吗

**Comment by andyjpaddle** [comment]
自己根据坐标调整就行，比如说坐标整体上移几个像素

**Comment by rexzhengzhihong** [comment]
> 自己根据坐标调整就行，比如说坐标整体上移几个像素

是这个会引起excel识别到一行去吗?比如这种 #10028

**Comment by rexzhengzhihong** [comment]
格式一样的图片。有的图片会，有的图片又可以正常
