### ISSUE TITLE
UPC-A底下的文字無法完整識別

### ISSUE THREAD

**Issue by hs9021401** [PaddlePaddle/PaddleOCR#10012]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleOCR 2.5.0.3
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

有一個UPC-A格式的一維條碼，條碼底下有文字
使用默認的識別rec模型與檢測det模型，但是無法正確的識別 (識別結果為 23601ll05707)
有甚麼方法可以改善識別結果嗎? 謝謝
![ocr](https://github.com/PaddlePaddle/PaddleOCR/assets/6288488/091fa032-830e-4f3e-a5db-5aa74d21b663)

**Comment by andyjpaddle** [comment]
可以收集一批数据进行finetune

**Comment by hs9021401** [comment]
> 
您是指要自行重新訓練det & ret模型嗎?
感謝回應

**Comment by andyjpaddle** [comment]
是的
