### ISSUE TITLE
android_demo中的paddleLiteLib_v2_10损坏

### ISSUE THREAD

**Issue by vlln** [PaddlePaddle/PaddleOCR#10016]
- 系统环境/System Environment：
windos10
android studio 4.1
- 版本号/Version：
release 2.6
- 完整报错/Complete Error Message：
gradle中的paddle_lite_libs文件可能损坏
 'src' : 'https://paddleocr.bj.bcebos.com/libs/paddle_lite_libs_v2_10.tar.gz'
压缩包中只有arm64的libs
![屏幕截图 2023-05-23 215631](https://github.com/PaddlePaddle/PaddleOCR/assets/43031803/eab554e3-358f-4727-b2e7-ea983b4923ee)

**Comment by andyjpaddle** [comment]
可以到paddlelite的repo下面问下

**Comment by vlln** [comment]
从[paddlelite](https://www.paddlepaddle.org.cn/lite/develop/quick_start/release_lib.html#opencl)找到对应的:
<html>
<body>


armv7 | clang | c++_shared | ON | ON | v2.12
-- | -- | -- | -- | -- | --




<html>
<body>


armv8 | clang | c++_shared | ON | ON | v2.12
-- | -- | -- | -- | -- | --

解决了.
并且opencv库好像也丢东西了, 从官网下载4.2.0替换后解决.
