### ISSUE TITLE
PGNet: End-to-end model super low precision

### ISSUE THREAD

**Issue by Whittaker0323** [PaddlePaddle/PaddleOCR#10013]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Hi all, I was trying to get a pretrained model of the end-to-end model by training on SynthText. I used about 80,000 pics and the precision_e2e is only 3.7%. What can I do to increase the precision?

**Comment by andyjpaddle** [comment]
PGNet is trained on Totaltext, pls refer to this [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_e2e_pgnet_en.md#4-model-trainingevaluation-and-inference)

**Comment by andyjpaddle** [comment]
I'm confused for the pretrained model you mentioned, PGNet can directly trained on Totaltext dataset.

**Comment by Whittaker0323** [comment]
> I'm confused for the pretrained model you mentioned, PGNet can directly trained on Totaltext dataset.

Sorry for the confusion.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/91847349/fd91ab21-ab44-4f31-80cb-158557b7a178)
My question is , what dataset did you use in step 1?

**Comment by andyjpaddle** [comment]
step 1 is using synthtext to get pretrained model, you can used it directly.
