### ISSUE TITLE
训练数据集没有可用图像

### ISSUE THREAD

**Issue by zljr** [PaddlePaddle/PaddleOCR#10015]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 10代i7 navida 1660ti
- 版本号/Version：Paddle：2.2  PaddleOCR：2.5.0 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model='./pretrain_models/ch_PP-OCRv3_rec_train/best_accuracy'
- 完整报错/Complete Error Message：2023/05/23 21:26:06] ppocr ERROR: No Images in train dataset, please ensure
        1. The images num in the train label_file_list should be larger than or equal with batch size.
        2. The annotation file and path in the configuration file are provided normally.

**Comment by zljr** [comment]
nvidia1660ti,

**Comment by andyjpaddle** [comment]
检查下数据路径是否写对了

**Comment by guoxiaoyue111111** [comment]
您好，请问您的问题解决了吗？
