### ISSUE TITLE
这个二维码扫了，没看到手写中文识别的模型在哪下载

### ISSUE THREAD

**Issue by 892745513** [PaddlePaddle/PaddleOCR#10022]
这个二维码扫了，问卷填了，没看到手写中文识别的模型在哪下载，也没看到有什么交流群，骗人嘛这不是，怼着代码下来训练还出错

**Comment by livingbody** [comment]
能提供位置不？不是很清楚是哪个。。。

**Comment by livingbody** [comment]
提供了数据以及训练方法，需要自己跑一下代码即可训练得到模型。

OCR手写文字识别 - 飞桨AI Studio
https://aistudio.baidu.com/aistudio/projectdetail/4330587

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by BillEliot** [comment]
> 提供了数据以及训练方法，需要自己跑一下代码即可训练得到模型。
> 
> OCR手写文字识别 - 飞桨AI Studio https://aistudio.baidu.com/aistudio/projectdetail/4330587

你也不看看自己训练要多长时间。。。
