### ISSUE TITLE
没有找到paddle_fluid.dll对应的paddle_fluid.lib，只有libpaddle_fluid.lib静态库

### ISSUE THREAD

**Issue by yanchao12122** [PaddlePaddle/PaddleOCR#1002]
fluid_inference_1.8.4版本cpu_avx_mkl，只有libpaddle_fluid.lib静态库，没有找到paddle_fluid.dll对应的paddle_fluid.lib

**Comment by littletomatodonkey** [comment]
linux上lib文件都是libxxx.lib的文件形式，这个没问题

**Comment by yanchao12122** [comment]
> linux上lib文件都是libxxx.lib的文件形式，这个没问题

windows下的也是libxxx.lib

**Comment by littletomatodonkey** [comment]
是编译的时候会报错吗还是？

**Comment by yanchao12122** [comment]
> 是编译的时候会报错吗还是？

此处下载的1.8.3版本(windows）cpu_avx_mkl      fluid_inference.zip，里面包含libpaddle_fluid.lib静态库，没有paddle_fluid.lib库
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html
