### ISSUE TITLE
PaddleOCRLabel是否可以设置自己的的模型，该如何设置自己的OCR模型呢

### ISSUE THREAD

**Issue by ff-0028** [PaddlePaddle/PaddleOCR#10027]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by livingbody** [comment]
参考：
PaddleOCR/PPOCRLabel/README_ch.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md

![360截图20230709005147973](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/cf0c2b2b-1a2d-4ba6-b6f1-43e8a5245ee0)

**Comment by ff-0028** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月9日(周日) 凌晨0:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PaddleOCRLabel是否可以设置自己的的模型，该如何设置自己的OCR模型呢 (Issue #10027)




 
参考：
 PaddleOCR/PPOCRLabel/README_ch.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
