### ISSUE TITLE
表格识别，用官网提供的模型会有识别成一行的情况。然后我就自己训练表格识别。但是自己训练的也会出现下面这种挤到一行的情况。是为什么呢？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#10028]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- ubunut 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
det 和table_model 模型是自己训练的。样本大概50张。样本数据是通过paddlelable根据教程标注识别的。
```

python3 predict_system_test.py \
--det_model_dir=/home/DiskA/zncsPython/picture_ocr/table/model/det/inference/det_db_dml_inference/Student \
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer \
--table_model_dir=/home/DiskA/zncsPython/picture_ocr/table/model/output/SLANet_finetune_inference \
--layout_model_dir=/home/DiskA/zncsPython/table_det/model/interence/picodet_lcnet_x1_0_layout_table  \
--image_dir=/home/DiskA/zncsPython/picture_ocr/table/test/table_det_ocr/ \
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
--output=/home/DiskA/zncsPython/picture_ocr/table/test/table_det_ocr/det_self_ocr_self_self \
--vis_font_path=../doc/fonts/simfang.ttf \
--table=true 
```
- 完整报错/Complete Error Message：
![gzxjsdgssskjsb_v1-05](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/c418e368-d69b-4a95-b409-5457b76c86aa)

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/1ef049c4-f426-458c-a053-65c892c8c9d4)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/b59b1675-50de-4819-aad2-58d8aba286b2)

**Comment by rexzhengzhihong** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/9d2717f2-a521-4040-a960-e652319a6f5c)

**Comment by rexzhengzhihong** [comment]
为什么，能回答下吗

**Comment by rexzhengzhihong** [comment]
@WenmuZhou

**Comment by andyjpaddle** [comment]
这个可能是由于坐标偏移问题，另外训练数据50张有点少了，可以再多加一些finetune一下

**Comment by rexzhengzhihong** [comment]
坐标偏移是因为什么？

**Comment by rexzhengzhihong** [comment]
一种格式的表格的训练数据要多少张才能达到效果？

**Comment by rexzhengzhihong** [comment]
这问题有解决？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
