### ISSUE TITLE
文字识别文档 字典说明

### ISSUE THREAD

**Issue by nengwp** [PaddlePaddle/PaddleOCR#10033]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

inally, a dictionary ({word_dict_name}.txt) needs to be provided so that when the model is trained, all the characters that appear can be mapped to the dictionary index.

Therefore, the dictionary needs to contain all the characters that you want to be recognized correctly. {word_dict_name}.txt needs to be written in the following format and saved in the utf-8 encoding format:

> l
> d
> a
> d
> r
> n

In word_dict.txt, there is a single word in each line, which maps characters and numeric indexes together, e.g "and" will be mapped to [2 5 1]

为什么是251 而不是 253？ 是不是写错了？

**Comment by nengwp** [comment]
meiyou hui fu

**Comment by UserWangZz** [comment]
Why are there two d  in your dictionary?
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
