### ISSUE TITLE
识别模型的验证阶段卡死

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1003]
您好，在进行识别模型阶段验证时，会出现卡死。如下：
![image](https://user-images.githubusercontent.com/43515926/97140364-6829c300-1797-11eb-8ce7-8540824c8990.png)
这个是什么原因导致的呢？

**Comment by littletomatodonkey** [comment]
可以尝试把reader.yaml的num workers减小至1，同时把配置文件里面的eval batch size减小试一下

**Comment by zcswdt** [comment]
> num



> 可以尝试把reader.yaml的num workers减小至1，同时把配置文件里面的eval batch size减小试一下

您好，我给num-workers改成1，并且把eval_tatch_step改成了500，在次运行验证代码，仍然卡主不动。
![image](https://user-images.githubusercontent.com/43515926/97162562-586fa600-17ba-11eb-8d1f-5d95a11bfd6d.png)

**Comment by tink2123** [comment]
通用模型太大了，可以调小eval时的batch_size试下：https://github.com/PaddlePaddle/PaddleOCR/blob/c77427630c687314b6875908d53d088c229fd4cb/configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml#L11
把这里修改为1

**Comment by zcswdt** [comment]
> 通用模型太大了，可以调小eval时的batch_size试下：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/c77427630c687314b6875908d53d088c229fd4cb/configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml#L11
> 
> 
> 把这里修改为1
请问一下，如果训练数据500万，验证数据集多少万比较好，验证的test_batch_size设置多少比较合适呢？

**Comment by zcswdt** [comment]
> 通用模型太大了，可以调小eval时的batch_size试下：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/c77427630c687314b6875908d53d088c229fd4cb/configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml#L11
> 
> 
> 把这里修改为1

验证是30万张图像，但是单独执行验证的时候test_batch_size_per_card: 128 会卡主不动。改成1之后能正常验证，速度很慢，改成16也能验证，改成32以上就会卡主不动，请问这是什么原因呢？
![image](https://user-images.githubusercontent.com/43515926/97258131-bb148080-1852-11eb-9b0b-3b7f0f42eed3.png)

**Comment by littletomatodonkey** [comment]
eval batch size太大的话，对显存/内存的要求比较高，程序容易hang住

**Comment by zcswdt** [comment]
> eval batch size太大的话，对显存/内存的要求比较高，程序容易hang住

谢谢回复，感觉不合理啊。我训练的时候，batch_size设置成128，能正常训练，而且我的使用双卡15G显存。当eval batch size设置为16的时候，只有一块卡在被使用。
![image](https://user-images.githubusercontent.com/43515926/97258701-f5325200-1853-11eb-8e36-161a2b0fbd41.png)

**Comment by littletomatodonkey** [comment]
eval的总数据条数需要大于eval batch size，同时eval的时候是单卡eval

**Comment by zcswdt** [comment]
> 条数需要大于

数据量30万，总数是要大于eval batch size的，eval batch size设置成16能正常验证，打印Log，设置成32以上就会卡主不动，打印不出log。

**Comment by littletomatodonkey** [comment]
那就是hang住的问题了，减小eval bs吧，先16吧

**Comment by zcswdt** [comment]
> 那就是hang住的问题了，减小eval bs吧，先16吧

好的，谢谢了。小数据量，比如3万进行验证，eval batch size能设置成128，能正常验证，打印log。
