### ISSUE TITLE
调用编译的C++版本cpp_infer，将PaddleOCR\deploy\cpp_infer\tools\config.txt中的use_angle_cls设置成1后预测结果为什么会不对？

### ISSUE THREAD

**Issue by Fzz123** [PaddlePaddle/PaddleOCR#1004]
**use_angle_cls为0时的运行结果：**
D:\projects\PaddleOCR\deploy\cpp_infer\out\build\x64-Release>.\ocr_system.exe D:\projects\PaddleOCR\deploy\cpp_infer\tools\config.txt D:\projects\PaddleOCR\doc\imgs\7.jpg
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn
use_angle_cls : 0
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1       没有吃饱只有一个        score: 0.988414
2       烦恼    score: 0.665785
3       吃饱了就有      score: 0.990093
4       烦恼！  score: 0.672449
5       无数个  score: 0.990055

**use_angle_cls为1时的运行结果：**
D:\projects\PaddleOCR\deploy\cpp_infer\out\build\x64-Release>.\ocr_system.exe D:\projects\PaddleOCR\deploy\cpp_infer\tools\config.txt D:\projects\PaddleOCR\doc\imgs\7.jpg
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn
use_angle_cls : 1
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1       安吃电月全      score: 0.329617
2       烦网    score: 0.681232
3       吃询了就育      score: 0.651605
4       2       score: 0.139528
5       无数    score: 0.443694

**Comment by littletomatodonkey** [comment]
这个可能是分类器对于这个图片中的某些框的方向分类有问题，建议使用1.1版本的移动端模型，从repo首页上就可以下载

**Comment by Fzz123** [comment]
> 这个可能是分类器对于这个图片中的某些框的方向分类有问题，建议使用1.1版本的移动端模型，从repo首页上就可以下载

你好，我之前用的模型是9.14号的，更新到了最新的模型后，结果还是有问题

D:\projects\PaddleOCR\deploy\cpp_infer\out\build\x64-Release>.\ocr_system.exe D:\projects\PaddleOCR\deploy\cpp_infer\tools\config.txt D:\projects\PaddleOCR\doc\imgs\7.jpg
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn
use_angle_cls : 1
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1       22电月全        score: 0.366755
2       烟网    score: 0.325635
3       2电了新育       score: 0.512957
4       2       score: 0.229326
5       无虹T   score: 0.40319

**Comment by Fzz123** [comment]
测试图片使用的是PaddleOCR里面自带的，python版本的测试代码中use_angle_cls设置为true的识别结果是准确的

**Comment by WenmuZhou** [comment]
cpp_infer代码是最新的吗

**Comment by Fzz123** [comment]
> cpp_infer代码是最新的吗

代码是刚刚去gitee下的，应该是最新的

**Comment by WenmuZhou** [comment]
gitee落后于github，用github上的把

**Comment by Fzz123** [comment]
> gitee落后于github，用github上的把

你好，我刚刚

> gitee落后于github，用github上的把

你好，我又下了github上的代码重新编译后结果还是错的

**Comment by Fzz123** [comment]
> gitee落后于github，用github上的把

你好，我又下了github上的代码重新编译后结果还是错的

**Comment by littletomatodonkey** [comment]
你好，可以提供下原始图像吗，我这边测试下

**Comment by Fzz123** [comment]
> 你好，可以提供下原始图像吗，我这边测试下

原始图像就是PaddleOCR中的实例测试图片  PaddleOCR\doc\imgs\7.jpg
![7](https://user-images.githubusercontent.com/30487169/97243668-cc00ca00-1831-11eb-9ab6-64faee10b348.jpg)

**Comment by Fzz123** [comment]
> 你好，可以提供下原始图像吗，我这边测试下

不只是这张图片， cpp_infer\tools\config.txt中的use_angle_cls设置成1时其他测试图片的预测结果也都有问题

**Comment by littletomatodonkey** [comment]
你好，我这边复现了这个问题，你可以先把mkldnn关闭测试下，这样是正常的，这个问题我们排查下，感谢反馈~

**Comment by Fzz123** [comment]
> 你好，我这边复现了这个问题，你可以先把mkldnn关闭测试下，这样是正常的，这个问题我们排查下，感谢反馈~

好的，期待修复~

**Comment by littletomatodonkey** [comment]
你好，这个问题在最新的Paddle预测库中已经修复，编译最新Paddle生成预测库的方法是可行的，我们近期也会放出Paddle2.0-rc版本的预测库，下面是我基于最新的Paddle代码编译得到的预测库进行预测，输出的log信息，预测结果是没问题的，再次感谢反馈！

```
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v1.1_cls_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/ch_ppocr_mobile_v1.1_det_infer/
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/ch_ppocr_mobile_v1.1_rec_infer/
use_angle_cls : 1
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1027 04:23:07.576328 48896 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1	没有吃饱只有一个	score: 0.993398
2	烦恼	score: 0.759834
3	吃饱了就有	score: 0.992803
4	烦脑！	score: 0.762208
5	无数个	score: 0.993687
花费了0.720197秒
```

**Comment by littletomatodonkey** [comment]
你好，windows下，可以试下这个CPU预测库，最新编译的

[paddle_inference_install_dir.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5443092/paddle_inference_install_dir.zip)

**Comment by Fzz123** [comment]
> 你好，windows下，可以试下这个CPU预测库，最新编译的
> 
> [paddle_inference_install_dir.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5443092/paddle_inference_install_dir.zip)

你好，现在还有个问题，无论use_angle_cls是否为1，同一张图片，正着放文字能够识别，旋转180°后C++编译版的识别效果会差很多。而在python版本中，se_angle_cls设置为1图片旋转180°后是可以识别出来的，设置为0则识别效果差。我使用的图片是doc\imgs\8.jpg，将其旋转了180°。paddle预编译库也换成了上面发的那版。

=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn
use_angle_cls : 1
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1027 14:34:29.344590 17264 analysis_config.cc:194] Please compile with MKLDNN first to use MKLDNN
E1027 14:34:29.345567 17264 analysis_config.cc:205] Please compile with MKLDNN first to set MKLDNN Thread Id
W1027 14:34:29.346712 17264 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
E1027 14:34:29.573954 17264 analysis_config.cc:194] Please compile with MKLDNN first to use MKLDNN
E1027 14:34:29.757498 17264 analysis_config.cc:194] Please compile with MKLDNN first to use MKLDNN
E1027 14:34:29.758460 17264 analysis_config.cc:205] Please compile with MKLDNN first to set MKLDNN Thread Id
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1       日619107        score: 0.83775
2       有      score: 0.231185
3       然面    score: 0.193931
4       要真    score: 0.220766
5       不留走二最题长日0月主   score: 0.58735
6       910ZX影北区关身工       score: 0.536833
7       原興    score: 0.211971

**Comment by WenmuZhou** [comment]
你好，这个问题可能是由于分类的shape设置的不对，已经在这里修复https://github.com/PaddlePaddle/PaddleOCR/pull/1021，这是我这边跑的结果
![image](https://user-images.githubusercontent.com/12406017/97275125-81eb0900-1870-11eb-987b-b00d1f1d6699.png)

**Comment by littletomatodonkey** [comment]
你好，这里修复了下，可以参考下
#1021

**Comment by TigerKylin** [comment]
> 你好，windows下，可以试下这个CPU预测库，最新编译的
> 
> [paddle_inference_install_dir.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5443092/paddle_inference_install_dir.zip)

用这个库编译出的exe文件和dll库（大概2M左右）都比以前的库编译出来的文件（大概40几兆）小很多，而且DLL文件在C#中调用时报错：     无法加载 DLL“ocr_system.dll”: 找不到指定的模块。
