### ISSUE TITLE
pycharm 高版本的cuda cudnn调试闪退依然存在

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10058]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu18 cuda 11.6 cudnn 8.8.0
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle-gpu               0.0.0.post116 ,paddleocr develop 拉取最新

- 运行指令/Command Code：单卡调试train 配置没问题
- 完整报错/Complete Error Message：
pycharm 单步调试，中途pycharm stop调试，导致整个系统程序退出，重新进入ubantu系统登陆状态，这个问题一直有，难道你们没遇见？

**Comment by cqray1990** [comment]
> 可能是pycharm的问题吧

pycharm调试别的代码没问题，就是调试paddleocr，paddlenlp都没问题

**Comment by frozenbeanxxx** [comment]
试试这个
https://blog.csdn.net/bcfd_yundou/article/details/122089367?spm=1001.2014.3001.5502
