### ISSUE TITLE
请问paddleOCR支持昇腾atlas300I推理卡吗？

### ISSUE THREAD

**Issue by HysUnknown** [PaddlePaddle/PaddleOCR#10057]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：UOSV20 -1050e server
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.4.2
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问paddleOCR支持昇腾atlas300I推理卡吗？
我部署后运行速度较慢，是否支持呢？

**Comment by andyjpaddle** [comment]
参考文档 https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/npu_ascend_cn.html

如果能运行成功那应该就是支持的
