### ISSUE TITLE
paddleOCR.ocr 與 predict_system 的檢測結果不一致

### ISSUE THREAD

**Issue by d246810g2000** [PaddlePaddle/PaddleOCR#10054]
paddleOCR.ocr 呼叫 __call__ 函數的結果與 predict_system 的檢測結果不一致，我有檢查前處理和後處理的參數都一致，想請問還有什麼原因會導致這個狀況發生？

ocr 的輸出結果為：
[[[1079. 1208.]
  [1362. 1196.]
  [1365. 1268.]
  [1082. 1281.]]

 [[ 271. 1204.]
  [ 933. 1204.]
  [ 933. 1241.]
  [ 271. 1241.]]

 [[1206. 1123.]
  [1377. 1109.]
  [1384. 1197.]
  [1213. 1212.]]

 [[ 212. 1126.]
  [ 524. 1126.]
  [ 524. 1163.]
  [ 212. 1163.]]

 [[1502. 1120.]
  [1828. 1083.]
  [1833. 1128.]
  [1507. 1164.]]

 [[ 256. 1048.]
  [ 976. 1048.]
  [ 976. 1082.]
  [ 256. 1082.]]

 [[1077. 1041.]
  [1362. 1009.]
  [1372. 1100.]
  [1087. 1132.]]

 [[ 979.  484.]
  [1557.  478.]
  [1558.  543.]
  [ 980.  549.]]

 [[ 411.  476.]
  [ 941.  481.]
  [ 940.  552.]
  [ 411.  546.]]

 [[ 173.  476.]
  [ 351.  476.]
  [ 351.  523.]
  [ 173.  523.]]

 [[ 173.  403.]
  [ 344.  403.]
  [ 344.  458.]
  [ 173.  458.]]

 [[ 422.  377.]
  [1310.  399.]
  [1308.  479.]
  [ 420.  457.]]

 [[ 184.  299.]
  [ 584.  307.]
  [ 583.  362.]
  [ 183.  353.]]]

predict_system 的輸出結果為：
[[[ 326. 1202.]
  [ 933. 1202.]
  [ 933. 1238.]
  [ 326. 1238.]]

 [[1214. 1129.]
  [1377. 1129.]
  [1377. 1204.]
  [1214. 1204.]]

 [[ 207. 1116.]
  [ 530. 1119.]
  [ 529. 1163.]
  [ 207. 1160.]]

 [[1504. 1120.]
  [1828. 1083.]
  [1833. 1128.]
  [1509. 1164.]]

 [[ 253. 1043.]
  [ 979. 1046.]
  [ 979. 1082.]
  [ 253. 1079.]]

 [[1080. 1043.]
  [1360. 1012.]
  [1369. 1093.]
  [1089. 1124.]]

 [[ 979.  481.]
  [1560.  481.]
  [1560.  544.]
  [ 979.  544.]]

 [[ 409.  468.]
  [ 946.  476.]
  [ 945.  549.]
  [ 408.  541.]]

 [[ 173.  471.]
  [ 354.  471.]
  [ 354.  525.]
  [ 173.  525.]]

 [[ 176.  403.]
  [ 349.  403.]
  [ 349.  460.]
  [ 176.  460.]]

 [[ 420.  379.]
  [1308.  396.]
  [1306.  476.]
  [ 418.  460.]]

 [[ 187.  299.]
  [ 587.  307.]
  [ 586.  362.]
  [ 186.  353.]]]

**Comment by d246810g2000** [comment]
找到原因了，原來是讀入影像時會將他變成 rgb ...

**Comment by WilliamQf-AI** [comment]
> 找到原因了，原來是讀入影像時會將他變成 rgb ...

你好，请问怎样解决的？

**Comment by d246810g2000** [comment]
> 

訓練的時候預設是使用 BGR，
但是在預測的時候有將 BGR 轉換成 RGB，
這行註銷掉就可以了。
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/predict_kie_token_ser.py#L146
