### ISSUE TITLE
垂类场景模型下载,已填写问卷,但进群二维码已过期

### ISSUE THREAD

**Issue by peipeilalala** [PaddlePaddle/PaddleOCR#10065]
我想进入官网交流群,根据提示,填写了问卷,但是进群二维码已过期,请问如何进群~?谢谢

**Comment by tink2123** [comment]
可以先扫描下面的二维码进群：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/31891223/4429f865-b229-4343-9038-c4472527ae2d)
