### ISSUE TITLE
移动端部署4线程比1线程慢

### ISSUE THREAD

**Issue by ljdang** [PaddlePaddle/PaddleOCR#1006]
在骁龙865和855上部署时，4线程比1线程慢，而且耗时不稳定。
测试Demo: https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo
模型： V1.1
版本信息： Paddle-Lite和opt均为最新develop分支编译

**Comment by AIpioneer** [comment]
![image](https://user-images.githubusercontent.com/50724968/97173008-d9cf3480-17ca-11eb-9227-48cf9689bab9.png)
https://paddle-lite.readthedocs.io/zh/latest/api_reference/cxx_api_doc.html
请绑定核试试是否还有问题

**Comment by ljdang** [comment]
@AIpioneer 测试过绑核，还是有问题

**Comment by AIpioneer** [comment]
好的，我们将会再查一下

**Comment by 772865705** [comment]
大佬，能不能教我一下如何把demo里面的V1.0的模型换成V1.1的超轻量级模型，我怎么换都会崩溃

**Comment by ljdang** [comment]
@772865705 要把Paddle-Lite的库换一下，可以看下deploy/lite端侧部署的描述

**Comment by j-river** [comment]
@ljdang 请问你的这个问题解决了吗？我也遇到类似的问题。
