### ISSUE TITLE
       标注表格的html应该怎么标注呢，直接标出html？这样会容易出错呢?ppocrlabel  预标注修改？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10063]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
PPOCRLabel支持表格标注的，可以直接标注，会生成对应的Html标签
