### ISSUE TITLE
开源的训练模型（手写识别），识别手写数字成功率为0 ，是只能识别中文吗？

### ISSUE THREAD

**Issue by julyyy123** [PaddlePaddle/PaddleOCR#10061]
之前我们拿到了训练模型（手写识别），我们转换后识别手写数字成功率为0 是只能识别中文吗，还是可能我们操作上有问题

**Comment by andyjpaddle** [comment]
开源的手写模型是在中文数据集上训练的，如果是全部是手写数字的话，可以收集一批数据finetune一下

**Comment by julyyy123** [comment]
> 开源的手写模型是在中文数据集上训练的，如果是全部是手写数字的话，可以收集一批数据finetune一下

那有别的模型可以识别手写数字的吗

**Comment by andyjpaddle** [comment]
暂时没有

**Comment by super-tian** [comment]
自建一个数据集训练一下就行，手写数字训练很容易，不需要大量的数据都能有很好的效果，并且如果你是有特定的需求的情况下，还是要用自己的真是数据训练，不然上线效果很差
