### ISSUE TITLE
TAL Table Recognition Competition Dataset 数据下载不了

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10060]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by cqray1990** [comment]
> 啥数据？

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/dataset/table_datasets_en.md

**Comment by andyjpaddle** [comment]
数据是第三方竞赛提供的，下载不了也没办法了
