### ISSUE TITLE
PPOCR_V3 长文本识别问题

### ISSUE THREAD

**Issue by bianliuyang** [PaddlePaddle/PaddleOCR#10064]
[我的训练数据是狭长文本图片，图片上的字符可能有30-40个：
![img_1](https://github.com/PaddlePaddle/PaddleOCR/assets/62277627/c3bd650b-0da9-404c-ae16-2d7100b0e353)

但是使用predict_rec.py时，我发现好像会把输入图片压缩为3,48,320大小，这会造成压缩后的图片字符挤在一起
是不是需要在哪里更改？训练的时候config配置文件是不是也要更改?
请大神帮忙解惑，万分感谢

**Comment by super-tian** [comment]
训练文件有两个地方要改，predict_rec传参就行

**Comment by bianliuyang** [comment]
> 训练文件有两个地方要改，predict_rec传参就行

是 改image_shape吗？

**Comment by super-tian** [comment]
对的，我看了一下，v3有3个shape，记得在预测的时候，也要修改成一样的

**Comment by super-tian** [comment]
max_lenth也同步修改 @bianliuyang

**Comment by liuhuan-gl** [comment]
请问没修改不会报错，但是修改后就报错是什么原因呢
