### ISSUE TITLE
手动标注无法保存rec_gt.txt文件

### ISSUE THREAD

**Issue by qiuyunbest** [PaddlePaddle/PaddleOCR#10070]
最新版2.6 release paddle下启动和使用pip安装的PPOCRLabel均有这个问题，只有自动标注后才能保存，否则rec_gt.txt和crop_img文件夹都是空的，终端无任何报错

**Comment by huangye123** [comment]
遇到同样问题，rec_gt.txt和crop_img文件夹都是空的

**Comment by qiuyunbest** [comment]
> 
回滚运行不起来

**Comment by qiuyunbest** [comment]
> 

此问题我已经解决。我发现手动标注无法导出，但是自动标注可以导出。于是我查看了Label.txt文件的数据有何不同，最终发现原来自动标注的difficult为false，而手动标注为true，将其改为false再次导出即可。
后面我又搜索了下Label.txt里面difficult的含义，原来在Linux下的PPOCRLabel是有一个复选框的，选择true的时候不会导出识别数据，而windows下是没有这个复选框的，应该是个BUG。

**Comment by qiuyunbest** [comment]
> 

此问题我已经解决。我发现手动标注无法导出，但是自动标注可以导出。于是我查看了Label.txt文件的数据有何不同，最终发现原来自动标注的difficult为false，而手动标注为true，将其改为false再次导出即可。
后面我又搜索了下Label.txt里面difficult的含义，原来在Linux下的PPOCRLabel是有一个复选框的，选择true的时候不会导出识别数据，而windows下是没有这个复选框的，应该是个BUG。

**Comment by tianjin92** [comment]
2.4版本有个可选择的框，2.6没有咋修复
