### ISSUE TITLE
Installation issue of paddlepaddle-gpu in CUDA Version:12.0

### ISSUE THREAD

**Issue by sharmaruchikht** [PaddlePaddle/PaddleOCR#10078]
I have "NVIDIA-SMI 525.60.13 || Driver Version: 525.60.13 || CUDA Version: 12.0" -> Ubuntu system

When I installed the GPU version of paddleocr in my system using `python -m pip install paddlepaddle-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple` ([link](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md#1-installation)), an error occurred: `ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory`

I know this error occurred because of a mismatch of the CUDA version.

Please provide an installation command for GPU paddlepaddle which would be suitable for CUDA Version: 12.0/Ubuntu or any other way to solve this problem?

**Comment by Sayaka91** [comment]
@sharmaruchikht 
Did you fix this error? Can you explain what happens?

**Comment by sharmaruchikht** [comment]
> @sharmaruchikht Did you fix this error? Can you explain what happens? I got the similar error

Yeah, it seems that the PaddleOCR-GPU package is currently only available for CUDA version 11.7 and below. You can refer to the documentation provided at this link: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

Right now, I have only one solution is to downgrade the cuda version from 12 to 11. In cuda-12, it doesn't support detecting part that's why it is not giving results, while when I run the same thing on the 11.4 cuda version, it is giving results.

Please update here if you find any other solution.

**Comment by sharmaruchikht** [comment]
> @sharmaruchikht Did you fix this error? Can you explain what happens? I got the similar error
 
Yeah, it seems that the PaddleOCR-GPU package is currently only available for CUDA version 11.7 and below. You can refer to the documentation provided at this link: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

Right now, I have only one solution is to downgrade the cuda version from 12 to 11. 

Cuda-12 won't support the paddleocr-gpu of different cuda version. Either it will show the error of "libcudart.so.10.2" if you will install 10 cuda version paddleocr in your 12 version cuda system and if you will install 11 version paddleocr in your 12 version of cuda system,  it won't support detecting part and will not give any results.. which is called cuda version mismatch.

Please update here if you find any other solution.

**Comment by FunnyWii** [comment]
Currently, it seems that paddle support cuda12.0 via pip installation, see https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html

**Comment by FunnyWii** [comment]
> I have NVIDIA GeForce MX330 which is not capable of CUDA, can I still run paddle on gpu?

I think you cant.

**Comment by namaws** [comment]
> > @sharmaruchikht Did you fix this error? Can you explain what happens? I got the similar error
> 
> Yeah, it seems that the PaddleOCR-GPU package is currently only available for CUDA version 11.7 and below. You can refer to the documentation provided at this link: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> 
> Right now, I have only one solution is to downgrade the cuda version from 12 to 11.
> 
> Cuda-12 won't support the paddleocr-gpu of different cuda version. Either it will show the error of "libcudart.so.10.2" if you will install 10 cuda version paddleocr in your 12 version cuda system and if you will install 11 version paddleocr in your 12 version of cuda system, it won't support detecting part and will not give any results.. which is called cuda version mismatch.
> 
> Please update here if you find any other solution.

Hello, I wanted to build a virtual environment to use paddleOCR, however, from my anaconda virtual environment, I didn't find compatible cuda and cudnn (using ``` conda search cuda``` and ```conda search cudnn``` ) , what should I do? 

![istockphoto-948829224-612x612](https://github.com/PaddlePaddle/PaddleOCR/assets/62085936/1080cbc1-5b26-447d-bbe9-b80cc5f813d3)

I wanted to use cuda 11.2 and cudnn 8.2.1, but from my environment, it showed cudnn 8.2.1 is build by cuda 11.3?
