### ISSUE TITLE
移动端部署耗时不稳定

### ISSUE THREAD

**Issue by ljdang** [PaddlePaddle/PaddleOCR#1007]
在联发科MT6799芯片上部署，大概率出现cpu offline:
I/Paddle-Lite: [I 10/26 16:30: 6.768 ...ocr/Paddle-Lite/lite/core/device_info.cc:442 check_cpu_online] CPU id:9 is offine
W/Paddle-Lite: [W 10/26 16:30: 6.769 ...ocr/Paddle-Lite/lite/core/device_info.cc:1156 SetRunMode] Some cores are offline, switch to NO BIND MODE

同时，耗时很不稳定，同一张图的不同推理耗时如下：
Inference Timecost: 2317
Inference Timecost: 4004

测试Demo: https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo
模型： V1.1
版本信息： Paddle-Lite和opt均为最新develop分支编译
线程数： 2
CPU模式： LITE_POWER_NO_BIND或LITE_POWER_HIGH

**Comment by AIpioneer** [comment]
![image](https://user-images.githubusercontent.com/50724968/97173008-d9cf3480-17ca-11eb-9227-48cf9689bab9.png)
https://paddle-lite.readthedocs.io/zh/latest/api_reference/cxx_api_doc.html
请绑定核试试是否还有问题

**Comment by ljdang** [comment]
@AIpioneer LITE_POWER_NO_BIND或LITE_POWER_HIGH这两种模式测试过，都有问题

**Comment by AIpioneer** [comment]
好的，我们会再查一下

**Comment by yongqiangma** [comment]
这个你是在mac下编译的吗？

**Comment by ljdang** [comment]
@yongqiangma Ubuntu下编译的

**Comment by ljdang** [comment]
@AIpioneer 再次验证发现，以MainActivity的选图加载方式，运行是正常的，以MiniActivity的方式就不正常，但是调用方式也没啥不同呀，麻烦帮忙查一下。

**Comment by yongqiangma** [comment]
> @AIpioneer 再次验证发现，以MainActivity的选图加载方式，运行是正常的，以MiniActivity的方式就不正常，但是调用方式也没啥不同呀，麻烦帮忙查一下。

加QQ群看下吧，  696965088

**Comment by ljdang** [comment]
@yongqiangma 群已满加不了，另外一个群没有相关信息，要是有解决方法，麻烦告知一下，谢谢。

**Comment by MissPenguin** [comment]
近期代码更新较多，可以拉取最新代码试试，如果仍有问题，欢迎重新提issue。
