### ISSUE TITLE
如果图像中不包含文字或者文字图像质量比较差，识别速度非常慢，如何解决这个问题？

### ISSUE THREAD

**Issue by opentld** [PaddlePaddle/PaddleOCR#10082]
利用yolo进行检测，然后利用paddle ocr进行识别，当检测到的文字图像质量很差，或者是图像不包含文字时，识别速度非常非常慢。
速度慢的问题似乎出在ocr的detect这个环节。该怎么解决？
比如对下面的图，检测和识别就非常非常慢，无法忍受 :(
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/21096515/608e8d93-abaa-48d3-a3ea-39e0b9ffd635)

**Comment by UserWangZz** [comment]
可以尝试文本超分
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
