### ISSUE TITLE
inf det检测模型。有的行没检测到。有的框，开始后结束的框位置不太准，怎么解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10085]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

inf det检测模型。有的行没检测到。有的框，开始后结束的框位置不太准，怎么解决？

用ch_ppocr_server_v2.0_det_train训练模型推理，报错AssertionError: when model typs is det, backbone only support ['MobileNetV3', 'ResNet', 'ResNet_SAST']

**Comment by ITccyhub** [comment]
assert module_name in support_dict, Exception(
AssertionError: when model typs is det, backbone only support ['MobileNetV3', 'ResNet', 'ResNet_vd', 'ResNet_SAST', 'PPLCNet', 'PPLCNetV3', 'PPHGNet_small']
