### ISSUE TITLE
模型下载问题

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#1008]
doc/doc_ch/models_list.md
2. 英文识别模型
en_ppocr_mobile_v1.1_rec 训练模型，下载https://paddleocr.bj.bcebos.com/20-09-22/mobile/en/en_ppocr_mobile_v1.1_rec_train.tar
解压只有一个文件best_accuracy.pdparams，缺了两个文件.pdmodel和.pdopt

**Comment by WenmuZhou** [comment]
我们更新一下

**Comment by LDOUBLEV** [comment]
.pdmodel和.pdopt 存放的分别是模型结构和优化器相关参数，可以不需要

**Comment by simplew2011** [comment]
> .pdmodel和.pdopt 存放的分别是模型结构和优化器相关参数，可以不需要

加载这个预训练时报错了

**Comment by tink2123** [comment]
> 加载这个预训练时报错了

使用 -o Global.pretrain_weights 去加载预训练模型

**Comment by simplew2011** [comment]
> 我们更新一下

hi，是否有更新？

**Comment by littletomatodonkey** [comment]
> > 我们更新一下
> 
> hi，是否有更新？

你好，如 @tink2123 所述，可以使用 `-o Global.pretrain_weights` 去加载预训练模型
