### ISSUE TITLE
复现手写ocr，acc一直为0

### ISSUE THREAD

**Issue by meizhao09** [PaddlePaddle/PaddleOCR#10083]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：AI Studio
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
- 完整报错/Complete Error Message：
-
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/37306255/70e1f0be-71c9-40ed-87af-b2340331ed95)

按照项目里的训练，acc一直为0是否正常

**Comment by meizhao09** [comment]
有训练好的模型吗，文档中提到说交流群有训练好的模型，但是二维码识别的结果是公众号，没找到下载路径

**Comment by super-tian** [comment]
哪个不是手写中文的吧，是普通文字的，我可以发一个我训练的，但是精度不高，acc才60多，主要泛化能力有点差

**Comment by zhangqiqi1228** [comment]
> 哪个不是手写中文的吧，是普通文字的，我可以发一个我训练的，但是精度不高，acc才60多，主要泛化能力有点差

請問可以分享一下您訓練的中文手寫模型麽

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
