### ISSUE TITLE
请问目前是否支持白名单黑名单

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1009]
即识别文字时，设定可能出现的字符范围，或者不可能出现的字符范围，以增加识别成功率，排除异常形近字符的误识别？比如0和O，大小写的Oo,I 和1等情况的误识别。

**Comment by singlebear** [comment]
像tesseract就支持白名单的功能，可以限定检测字符的范围。请问PaddleOCR目前支持这个功能么？或者未来会不会支持？

**Comment by LDOUBLEV** [comment]
不支持，这些可以根据你的情况加上一些识别后处理代码；或者基于我们的模型在你的场景数据上重新训练。
