### ISSUE TITLE
使用picodet_lcnet_x1_0_fgd_layout_cdla进行版面分析，结果不完整

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/PaddleOCR#10097]
如图所示，标记的结果缺头少尾
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40328063/a22a3613-084f-49cc-9faa-1a956513b2ed)

**Comment by WilliamQf-AI** [comment]
@tink2123

**Comment by liuhuan-gl** [comment]
会不会和配置文件里面的resize有关系

**Comment by codeman008** [comment]
你这是直接跑的cdla的预训练模型还是自己训练的‘

**Comment by Andy197527** [comment]
> 你这是直接跑的cdla的预训练模型还是自己训练的‘

要是自己训练的你知道怎么换上去嘛？
