### ISSUE TITLE
运行PPOCRLabel报错

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleOCR#10100]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：GNU/Linux
- 版本号/Version：Paddle：2.4.1.post117   PaddleOCR：2.6.1.3  问题相关组件/Related components： pyqt5 ： 5.12.1 
- 运行指令/Command Code：通过whl 运行 PPOCRLabel --lang ch    或者 通过Python脚本运行 python PPOCRLabel.py --lang  ch
- 完整报错/Complete Error Message：
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1686015166 (unix time) try "date -d @1686015166" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002264) received by PID 8804 (TID 0x7faaeaa48740) from PID 8804 ***]

已放弃

**Comment by Sayaka91** [comment]
@LANSEYOUYUMOWANG 
You can reinstall the newest version of PyQt. It works with me

**Comment by Sayaka91** [comment]
You can try install opencv-python-headless==4.5.3.56. My friend tried it
and the ppocrlabel tool works well

Vào Th 3, 6 thg 6, 2023 vào lúc 09:12 yuhao ***@***.***> đã
viết:

**Comment by zzh928253398** [comment]
my python is 3.9.7
and my module version is 
opencv-python 4.5.2.52
opencv-contrib-python-headless 4.5.2.52
PyQt5 5.14.2
PPOCRLabel 2.1.2
.you can try
