### ISSUE TITLE
C#使用FastDeploy推理PaddleOCR的ch_PP-OCRv3模型不出结果

### ISSUE THREAD

**Issue by yourtiger** [PaddlePaddle/PaddleOCR#10108]
1.基于VS2022下载并编译了FastDeploy
使用如下命名进行编译：
cmake .. -G "Visual Studio 17 2022" -A x64 ^
         -DENABLE_ORT_BACKEND=ON ^
         -DENABLE_PADDLE_BACKEND=ON ^
         -DENABLE_OPENVINO_BACKEND=ON ^
         -DENABLE_VISION=ON ^
         -DENABLE_TEXT=ON ^
         -DWITH_CAPI=ON ^
         -DWITH_CSHARPAPI=ON ^
         -DCMAKE_INSTALL_PREFIX="D:\temp\PaddleOCR\compiled_fastdeploy"
修改了https://github.com/PaddlePaddle/FastDeploy/tree/develop/csharp/fastdeploy/runtime_option.cs文件
把‎int64_t改为‎int64
2.基于VS2022下载并编译了PaddleOCR
只有警告，没有错误
3.运行推理命令如下：
infer_demo.exe ch_PP-OCRv3_det_infer ch_ppocr_mobile_v2.0_cls_infer ch_PP-OCRv3_rec_infer ppocr_keys_v1.txt 12.jpg 0
结果如下：
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0606 16:18:35.183938 30660 analysis_config.cc:971] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(286)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(286)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(286)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
但是没有输出推理结果

**Comment by yourtiger** [comment]
还没解决

**Comment by chccc1994** [comment]
1.同样遇到这个问题，Fastdeploy部署预测没有输出结果。
2. 采用.Net Framework 4.7.2框架，遇到参数超限：`“System.ArgumentOutOfRangeException”类型的未经处理的异常在 mscorlib.dll 中发生在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。 (异常来自 HRESULT: 0x80070459)`

使用代码：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/cpu-gpu/csharp/infer.cs

**Comment by duhuan35** [comment]
怎么解决

**Comment by Aspen0309** [comment]
请问怎么解决

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
