### ISSUE TITLE
what dataset was used to train pp-ocrv3 for Arabic language?

### ISSUE THREAD

**Issue by Shidhani** [PaddlePaddle/PaddleOCR#10107]
I want to fine tune the Arabic OCR model, but I need to know what dataset it was already trained on.

**Comment by livingbody** [comment]
Please give me five if this is useful:

Downloads - ICDAR 2019 Robust Reading Challenge on Multi-lingual scene text detection and recognition - Robust Reading Competition
https://rrc.cvc.uab.es/?ch=15&com=downloads

**Comment by livingbody** [comment]
![360截图20230709004110238](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/aab6899d-7710-49ee-b0de-41ddfca52ec6)

**Comment by Shidhani** [comment]
Great! Thank you

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
