### ISSUE TITLE
The result after exporting was not correct

### ISSUE THREAD

**Issue by leviethung2103** [PaddlePaddle/PaddleOCR#10105]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04
- 版本号/Version: Paddle:v3  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Hello,

After training the text detection model with this configure:  ch_PP-OCRv3_det_student.yml,

I've tried the checkpoint, the detection results is correct. 

However, after exporting the model, i got no detection result. Is thery

**Use the this command to export the model**
python3 tools/export_model.py -c ./configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student_lao_vn.yml -o Global.pretrained_model=output/ch_PP-OCR_V3_det/best_accuracy  Global.save_inference_dir=./inference/ch_PP-OCR_V3_det/

**Export Model**
python3 tools/export_model.py -c configs/rec/PP-OCRv3/vi_lao_PP-OCRv3_rec.yml -o Global.pretrained_model=output/v3_en_mobile/best_accuracy  Global.save_inference_dir=./inference/en_PP-OCRv3_rec/

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
