### ISSUE TITLE
paddle支持推理模型转训练模型吗？

### ISSUE THREAD

**Issue by LUXUS1** [PaddlePaddle/PaddleOCR#10103]
paddle支持推理模型转训练模型吗？

**Comment by livingbody** [comment]
不支持推理模型转训练模型。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
