### ISSUE TITLE
使用paddleocrv3微调自己的检测模型部分文字框无法检测

### ISSUE THREAD

**Issue by TTMRonald** [PaddlePaddle/PaddleOCR#10109]
训练自己的标注的驾驶证检测数据，每个驾驶证只标注4个文字框，位于上部的2个文字框训练正常，位于下部的2个文字框始终无法检测到，导致训练过程召回率最高只能达到50%
验证了标注数据是正常的
请教下有人遇到类似问题该怎么解决？

配置文件：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/det/det_mv3_db.yml（只替换了数据）

**Comment by BeyondYourself** [comment]
是不是训练轮数太少了或者标注的训练集有点少的缘故
