### ISSUE TITLE
为什么SVTR的预测中只输出小写英文字母

### ISSUE THREAD

**Issue by youde2000** [PaddlePaddle/PaddleOCR#10106]
`/Users/2mythvector/miniconda3/envs/ppocr_rosetta/bin/python tools/infer_rec.py -c \
./ppocr/models/svtr/rec_svtr_large_none_ctc_ch_train/rec_svtr_large_10local_11global_stn_ch.yml \
-o Global.infer_img='/Users/2mythvector/img' \
Global.pretrained_model=./ppocr/models/svtr/rec_svtr_large_none_ctc_ch_train/best_accuracy
`
当我运行后出现的结果全都为小写，即使原图片中的字母是大写的
<img width="1218" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/54662806/8402f7ca-f546-4047-87e5-059659ffa397">

<img width="1433" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/54662806/450a57d2-cf69-485f-9412-7361bb4ed523">

**Comment by super-tian** [comment]
我记得看到过一个描述是，在训练中会统一变成小写

**Comment by youde2000** [comment]
有什么办法可以同时识别大写字母和小写字母么？

**Comment by youde2000** [comment]
其实我感觉是在输出结果的某个地方，把所有的字母都输出为小写了，因为svtr还是认识大写字母的

**Comment by youde2000** [comment]
指定了

/Users/2mythvector/miniconda3/envs/ppocr_rosetta/bin/python tools/infer_rec.py -c \
./ppocr/models/svtr/rec_svtr_large_none_ctc_ch_train/rec_svtr_large_10local_11global_stn_ch.yml \
-o Global.infer_img='/Users/2mythvector/e51' \
Global.pretrained_model=./ppocr/models/svtr/rec_svtr_large_none_ctc_ch_train/best_accuracy \
Global.character_dict_path=./ppocr/utils/ppocr_keys_v1.txt

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
