### ISSUE TITLE
ONNX inference

### ISSUE THREAD

**Issue by tantayo** [PaddlePaddle/PaddleOCR#10115]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04, python 3.7, CUDA 10.2
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/model.onnx --rec_model_dir=./inference/rec_onnx/model.onnx --cls_model_dir=./inference/cls_onnx/model.onnx --image_dir=doc/imgs_en/img_12.jpg --rec_char_dict_path=ppocr/utils/en_dict.txt
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 140, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/santiago/projects/paddle_ocr/PaddleOCR/tools/infer/predict_det.py", line 146, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by Gmgge** [comment]
已在python3.8，paddleocr2.6，onnxruntime1.9.0、onnxruntime1.15.1复现该问题；
经过初步排查，当前onnx模型支持动态shape推理，因此通过input_tensor获取到的shape为['None', 3, '?', '?']，不再需要单独进行resize的预处理。

需要做出以下修改操作：
1.PaddleOCR/tools/infer/predict_det.py中114行，删除该if self.use_onnx:分支（144行到151行） 
2.PaddleOCR/tools/infer/predict_rec.py中174行，删除该if self.use_onnx:分支 （174行到177行）

删除这两步试图获取onnx模型的固定shape即可正常运行

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by hoangph3** [comment]
You should use `paddle2onnx==0.9.0`. It's working!
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/54660554/cc13efcd-129e-4bc2-9bad-f02c6bc89e42)
