### ISSUE TITLE
表格识别训练，需要训练文本检测吗？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#10110]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
表格识别训练，需要训练文本检测吗？
- 完整报错/Complete Error Message：

**Comment by livingbody** [comment]
我理解你的问题，是这样的，都需要训练的，表格识别只是结构识别，剩下还有很多工作要做。
## 参看
PaddleOCR/ppstructure/table/README_ch.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/table/README_ch.md
![360截图20230709003222096](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/ec547865-bd9b-4b96-a1c4-17da7fa0d73d)

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
