### ISSUE TITLE
表格识别数据标注。使用paddlelabel标注，一个空中有换行的情况。怎么标识

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#10116]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
![1686130044845](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/0d1e1d0d-eab9-47fc-991e-360f7dcf192b)

- 完整报错/Complete Error Message：
1. 像这种情况是不是要全部框起来。然后在右侧的识别结果把错误的识别结果改对。比如把 “辉捷”改成“实存数量”。？？
2.训练的时候要去训练表格的 文本检测和文本识别

**Comment by rexzhengzhihong** [comment]
@WenmuZhou

**Comment by BeyondYourself** [comment]
换行的不能在一个Box里

**Comment by rexzhengzhihong** [comment]
> 换行的不能在一个Box里

那多个box 。表格的box数量就不了。出来 tr  td错了，这怎么处理？

**Comment by rexzhengzhihong** [comment]
感觉表格的识别问题没有解决，issues一直关闭
