### ISSUE TITLE
Can not find [batch_norm_47.w_1] in model file

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#1011]
下载了server端训练模型的参数，使用了命令：python3 tools/infer_det.py -c configs/det/det_mv3_db_v1.1.yml -o TestReader.infer_img="./doc/imgs_en/" Global.checkpoints="./inference/ch_ppocr_server_v1.1_det_infer/params"
测试检测模型
报错：AssertionError: Can not find [batch_norm_47.w_1] in model file [./output/det_db/best_accuracy.pdparams]

**Comment by LDOUBLEV** [comment]
你使用的配置文件是轻量模型的配置文件，backbone是MobileNet V3 ： det_mv3_db_v1.1.yml ； 但是你加载的模型文件是server的模型文件，可以用det_r18_vd_db_v1.1.yml 这个配置文件试一下
