### ISSUE TITLE
name 'batch' is not defined

### ISSUE THREAD

**Issue by fistyee** [PaddlePaddle/PaddleOCR#1012]
![image](https://user-images.githubusercontent.com/8428329/97185914-a0eb8b80-17db-11eb-851a-447f04102d03.png)
这是paddle安装版本问题吗

**Comment by littletomatodonkey** [comment]
看着像是Paddle安装问题，可以试下重装Paddle2.0.0b0版本

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
