### ISSUE TITLE
训练模型转推理模型后精度下降

### ISSUE THREAD

**Issue by Wangyh555** [PaddlePaddle/PaddleOCR#10124]
发现经常存在训练模型转推理模型后精度下降的问题，按照文档中的方式检查了一下训练与推理的预处理和后处理过程，在确认一致之后仍然存在上述问题，是否是在模型转换的时候出现了问题呢

**Comment by fuzheng1209** [comment]
你好，请问你下降的精度很多吗？
我也是碰到了同样的问题，我是通过训练了一堆标点符号样本，训练模型评估时是正常识别，但是转换推理模型后一个都无法识别。
