### ISSUE TITLE
运行PPOCRLabel报错  qt.qpa.xcb: could not connect to display :0.0

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleOCR#10137]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：GNU/Linux
- 版本号/Version：2.4.1.post117 PaddleOCR：2.6.1.3  问题相关组件/Related components：
- 运行指令/Command Code：通过whl 运行 PPOCRLabel --lang ch 或者 通过Python脚本运行 python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/yhao/anaconda3/envs/paddleOcr/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1686530388 (unix time) try "date -d @1686530388" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800001350) received by PID 4944 (TID 0x7ffa88ceb740) from PID 4944 ***]

已放弃

**Comment by azimjonn** [comment]
SAme error is happening on me. Haven't you found the solution yet?

**Comment by UserWangZz** [comment]
这个错误通常发生在尝试在没有图形环境的服务器（例如只有命令行界面的Linux服务器）上运行基于Qt的应用程序时。Qt使用XCB（X11的C语言库）来与X服务器通信，但如果没有X服务器或者X服务器配置不正确，就会出现这个错误。
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
