### ISSUE TITLE
在原模型基础上进行了网络修改，加载预训练模型后跑出的结果没有更改前的好，有什么办法改进？

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#10138]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：ch_det_res18_db_v2.0.yml
- 运行指令/Command Code：train.py
- 完整报错/Complete Error Message：

我以官方ch_ppocr_server_v2.0_det通用模型的预训练模型为基础，进行模型微调训练。但是在训练前我加入了网络部分的改进，具体来说是部分可变形卷积替换了普通卷积，官方提出的RSEFPN代替了原DBFPN。加载原预训练模型训练后，训练效果只能接近最原始网络训练出的结果，但是不会比原网络效果好。

我想问，这种训练修改操作是不是存在问题？并且有没有办法能够改进？我查阅资料发现好像有部分参数载入的操作，将修改后的参数重新训练，没有修改的参数按照预训练导入，会不会有效果？

希望能得到改进意见，感激不尽！！

**Comment by phb-shiyige-fw** [comment]
@huangjun12 希望能得到您的回复，谢谢

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
