### ISSUE TITLE
能不能增加一下java调用grpc 服务端ocr的实例

### ISSUE THREAD

**Issue by polarisunny** [PaddlePaddle/PaddleOCR#10135]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
能不能增加一下java调用grpc 服务端ocr的实例
- 系统环境/System Environment：ubuntu 22.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 -m paddle_serving_server.serve --model ppocr_det_v3_serving ppocr_rec_v3_serving --op GeneralDetectionOp GeneralInferOp --port 8181 &>log.txt &
- 完整报错/Complete Error Message：

**Comment by faquir-sun** [comment]
这个有计划增加吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
