### ISSUE TITLE
有没有办法输出单元格上下左右的坐标？

### ISSUE THREAD

**Issue by ayang** [PaddlePaddle/PaddleOCR#10134]
表格识别输出的单元格cell_bbox是单元格内文字的框，而不是整个单元格的框。请问有没有办法得到整个单元格的bbox坐标？

因为识别pdf时有时文字是错的，但如果有单元格坐标，就可以通过直接用pymupdf得到文字框内文字了，这样比较准确。

**Comment by magicleo** [comment]
同问能得到单个文字的坐标吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
