### ISSUE TITLE
DB模型莫名训练中止！

### ISSUE THREAD

**Issue by Ming-Zhou0201** [PaddlePaddle/PaddleOCR#1013]
DB模型，训练图片2000张，验证集70+，观察内存变化一直涨，然后GPU显存还在，但是利用率变为0，return paddle.reader.multiprocess_reader(readers, False, queue_size=320)，  num_workers: 4，
这些也都调整了，还是不行，后来把训练图片改到600张左右就没有问题。怎么解决这个问题呢？

**Comment by littletomatodonkey** [comment]
试下num_workers改为1，queue_size再减小一些试下呢？应该还是资源不足导致hang住的问题

**Comment by Ming-Zhou0201** [comment]
> 试下num_workers改为1，queue_size再减小一些试下呢？应该还是资源不足导致hang住的问题

queue_size 继续减小，没问题了，应该是资源问题！谢谢哈
