### ISSUE TITLE
如何将PP-Structure返回的版面分析结果中的文本块按照阅读顺序重组

### ISSUE THREAD

**Issue by lycfight** [PaddlePaddle/PaddleOCR#10146]
![20230612-193739](https://github.com/PaddlePaddle/PaddleOCR/assets/25731261/d25f74ab-f473-4762-9855-8ccfb41ffe21)
如图所示，版面分析的结果似乎是随机排列的，如何将文本块和标题块按照阅读顺序重建呢？

**Comment by thsno02** [comment]
如果你的识别结果 promising 的话，可以直接通过 sort 解决吧。对于两栏的图片，先按照 y 进行升序排列，再按照 x 进行升序排列就可以了。

**Comment by lycfight** [comment]
但是有些潜在的策略，例如上图的6、5、3、2块，当中间被其他对象例如图、表隔开的时候，并不是优先按y排列，再按x排列

**Comment by thsno02** [comment]
> 但是有些潜在的策略，例如上图的6、5、3、2块，当中间被其他对象例如图、表隔开的时候，并不是优先按y排列，再按x排列

加策略就好了嘛，我感觉两栏这个应该能通过规则解决。因为 bounding box 之间没有 overlap。你可以考虑使用 x_mean 进行简单分类呗，判断左边、中间、右边，然后再继续。

**Comment by lycfight** [comment]
> > 但是有些潜在的策略，例如上图的6、5、3、2块，当中间被其他对象例如图、表隔开的时候，并不是优先按y排列，再按x排列
> 
> 加策略就好了嘛，我感觉两栏这个应该能通过规则解决。因为 bounding box 之间没有 overlap。你可以考虑使用 x_mean 进行简单分类呗，判断左边、中间、右边，然后再继续。

因为我想要做的是一个较为通用的方案，规则的泛化性不太够，而相关的reading order的研究也比较少

**Comment by thsno02** [comment]
打标签训分类模型？

**Comment by lycfight** [comment]
我感觉像微软的layoutreader的思路可以作一些修改，layoutreader的粒度比较小，是word-level排序的。现在给出版面分析目标检测框的工作其实比较多了，但是bbox基本都是乱序的，如果将各个块按照region-level排序就好了

**Comment by SopmmmodII** [comment]
我是直接拿微软那个Augmented XY Cut方法来用了

**Comment by dc6273632** [comment]
> 我是直接拿微软那个Augmented XY Cut方法来用了

怎么用的？求教

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by zakahan** [comment]
刚刚试了一下，可以以box的左上角为基准坐标，找到整个版面横坐标的中线，先不管分栏。
1）左上角在中线以左的，加入到l_list，在中线以右的，加入到r_list。然后根据纵坐标对两个list单独排序，再合并。基本上能解决单栏和双栏两种问题，三栏之类的很不常见也没必要考虑了。

**Comment by Devcode518** [comment]
> 刚刚试了一下，可以以box的左上角为基准坐标，找到整个版面横坐标的中线，先不管分栏。 1）左上角在中线以左的，加入到l_list，在中线以右的，加入到r_list。然后根据纵坐标对两个list单独排序，再合并。基本上能解决单栏和双栏两种问题，三栏之类的很不常见也没必要考虑了。

你好，请问3.7号更新的版本说是“优化复杂版面阅读顺序”，你有试试嘛？我想找它这个源码，找半天都没看到

**Comment by zakahan** [comment]
> > 刚刚试了一下，可以以box的左上角为基准坐标，找到整个版面横坐标的中线，先不管分栏。 1）左上角在中线以左的，加入到l_list，在中线以右的，加入到r_list。然后根据纵坐标对两个list单独排序，再合并。基本上能解决单栏和双栏两种问题，三栏之类的很不常见也没必要考虑了。
> 
> 你好，请问3.7号更新的版本说是“优化复杂版面阅读顺序”，你有试试嘛？我想找它这个源码，找半天都没看到

抱歉我并没有试过，我已经不再做这方面的工作了。

**Comment by Devcode518** [comment]
> > > 刚刚试了一下，可以以box的左上角为基准坐标，找到整个版面横坐标的中线，先不管分栏。 1）左上角在中线以左的，加入到l_list，在中线以右的，加入到r_list。然后根据纵坐标对两个list单独排序，再合并。基本上能解决单栏和双栏两种问题，三栏之类的很不常见也没必要考虑了。
> > 
> > 
> > 你好，请问3.7号更新的版本说是“优化复杂版面阅读顺序”，你有试试嘛？我想找它这个源码，找半天都没看到
> 
> 抱歉我并没有试过，我已经不再做这方面的工作了。

好的好的，感谢回复，打扰啦！
