### ISSUE TITLE
Occitan corpus: more words

### ISSUE THREAD

**Issue by Mejans** [PaddlePaddle/PaddleOCR#1014]
Hello,
I succeeded in gathering all the Hunspell dictionary for Occitan, all the different and possible form these words can have (plurals, regular and not, feminines etc).
But I cannot send the file via GitHub web interface.
So here is a link to a Firefox Send instance. It's a 26Mb text file.
https://drop.chapril.org/download/ae975b7c2ed4b1e5/#4MnQJwz71PgEtPv-nSuv4A

**Comment by tink2123** [comment]
Thanks for your contribution again～

**Comment by Mejans** [comment]
You're welcome :D

**Comment by Mejans** [comment]
@tink2123 you had time to fetch the file?

**Comment by tink2123** [comment]
Hello, I tried to download data many times, but it always failed. Can you provide other download methods?

**Comment by Mejans** [comment]
Here some links:
https://drop.chapril.org/download/60f30b8308c872b3/#DASJ3ljBo28oo_9Gcoktqg
https://framadrop.org/lufi/r/QrtWeXmpqh#QNXUgNttkekDx/UWLxPr83pJHdIqhhX4HUO7UdJK3Fw=
https://www.sendspace.com/file/fnicf6

Let me know if you can't get it

**Comment by tink2123** [comment]
> https://framadrop.org/lufi/r/QrtWeXmpqh#QNXUgNttkekDx/UWLxPr83pJHdIqhhX4HUO7UdJK3Fw=

This link is valid,  got it~

**Comment by Mejans** [comment]
@tink2123 I managed to put a 7zip file here:
https://github.com/Mejans/data-occitan
Supposed to be permanently available, if anyone is reading this closed issue :P
