### ISSUE TITLE
训练模型和测试模型的检测结果差距较大

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#1015]
使用ch_ppocr_server_v1.1_det_infer和ch_ppocr_server_v1.1_det_train对同一批图片进行测试，为什么检测的结果差这么多？所以说训练模型和测试模型不是在同一批数据集上训练的吗？

**Comment by ulanbator** [comment]
![左侧测试模型结果右侧训练模型结果](https://user-images.githubusercontent.com/26237152/97250773-9a8ffa80-1841-11eb-9789-a91cb5a26224.png)

**Comment by ulanbator** [comment]
![Uploading 微信图片_20201027113507.png…]()

**Comment by ulanbator** [comment]
![Uploading 微信图片_20201027113507.png…]()

**Comment by littletomatodonkey** [comment]
你好，可以提供下原始图片吗？我们测试下，同时提供下你那边使用训练模型和推理模型的预测脚本吧

**Comment by ulanbator** [comment]
这是测试图片：

![测试图片](https://user-images.githubusercontent.com/26237152/97258649-d0d67580-1853-11eb-8024-15e6d7153806.jpg)

推理模型的测试脚本（用的是server的推理模型）： python3 tools/infer/predict_system.py --image_dir="./doc/plp/" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True

预训练模型的测试脚本（用的是server的预训练模型）： python3 tools/infer_det.py -c ./configs/det/det_r18_vd_db_v1.1.yml -o TestReader.infer_img="./doc/plp/" Global.checkpoints="./output/det_db/best_accuracy"

**Comment by littletomatodonkey** [comment]
你好，我这边复现了这个问题，使用inference model预测结果正常，
![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)

使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~

**Comment by LDOUBLEV** [comment]
训练模型改一下后处理参数，在det_r18_vd_db_v1.1.yml里最后
![image](https://user-images.githubusercontent.com/26592129/97260743-66740400-1858-11eb-83b4-32a8a2954257.png)

**Comment by BeyondYourself** [comment]
看上面的好像目前横排文本和竖排文本在检测的时候容易混淆了，目前是不是没有什么办法区分来。

> 你好，我这边复现了这个问题，使用inference model预测结果正常，
> ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> 
> 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~

**Comment by ulanbator** [comment]
> 看上面的好像目前横排文本和竖排文本在检测的时候容易混淆了，目前是不是没有什么办法区分来。
> 
> > 你好，我这边复现了这个问题，使用inference model预测结果正常，
> > ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> > 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~

语义监督

**Comment by BeyondYourself** [comment]
对于文本在不同的box,这个可以语义监督吗？？
> > 看上面的好像目前横排文本和竖排文本在检测的时候容易混淆了，目前是不是没有什么办法区分来。
> > > 你好，我这边复现了这个问题，使用inference model预测结果正常，
> > > ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> > > 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~
> 
> 语义监督

**Comment by ulanbator** [comment]
AE Textspotter了解一下

**Comment by ulanbator** [comment]
> 对于文本在不同的box,这个可以语义监督吗？？
> 
> > > 看上面的好像目前横排文本和竖排文本在检测的时候容易混淆了，目前是不是没有什么办法区分来。
> > > > 你好，我这边复现了这个问题，使用inference model预测结果正常，
> > > > ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> > > > 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~
> > 
> > 
> > 语义监督
AE Textspotter了解一下

**Comment by ulanbator** [comment]
> 对于文本在不同的box,这个可以语义监督吗？？
> 
> > > 看上面的好像目前横排文本和竖排文本在检测的时候容易混淆了，目前是不是没有什么办法区分来。
> > > > 你好，我这边复现了这个问题，使用inference model预测结果正常，
> > > > ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> > > > 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~
> > 
> > 
> > 语义监督



> 你好，我这边复现了这个问题，使用inference model预测结果正常，
> ![image](https://user-images.githubusercontent.com/14270174/97258916-85709700-1854-11eb-9721-89e2f0c310b1.png)
> 
> 使用infer_det.py的预测结果不正常， 稍等我们排查下，感谢反馈~

你用的server端的infrence模型测试的吗？为什么同一张图片测试的结果要比我测试的要好呢？

**Comment by littletomatodonkey** [comment]
是的，我用的是最新的代码和模型，你可以更新一下
