### ISSUE TITLE
PPOCRLabel 标注一般不超过多少个字

### ISSUE THREAD

**Issue by hanyong-max** [PaddlePaddle/PaddleOCR#10159]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
长度无限制，正常训练阶段长度大于25的会过滤掉
