### ISSUE TITLE
paddleOCR参数意义

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#10157]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请问paddle ocr里很多参数在官方文档里并没有给出具体含义和调整方法，如何查询。
例如：ch_det_mv3_db_v2.0.yml中，Train：下面      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
            这几个参数就没有解释。

rec中也有些参数并没有官方说明，请问 哪里可以获取？

**Comment by andyjpaddle** [comment]
这是一些数据增广涉及的参数，比如翻转、仿射变换、缩放等，具体可以看下源码实现
