### ISSUE TITLE
from .core_avx import * ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by czblse** [PaddlePaddle/PaddleOCR#1016]
操作步骤：
1、安装paddlepaddle、paddleocr
2、执行paddleocr官方demo报错
3、直接运行python命令行，进入python环境之后，import paddle 也同样报错
4、更换paddlepaddle为1.8.5同样报错
5、更换paddlepaddle为1.7.1没有报错

环境：
1、paddlepaddle版本：2.0.0b0/1.8.5均会报错，1.7.1不会报错
2、paddleOCR版本：1.0.0
3、python版本：3.6.6
4、glibc版本：ldd (GNU libc) 2.18
5、系统：centos7

具体报错内容：
(cpu) [yfzx@ali-ai-xunlian-dev paddleOCR]$ python
Python 3.6.6 (default, Feb 20 2020, 10:12:58) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/fluid/core.py:189: UserWarning: Load /lib64/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/__init__.py", line 34, in <module>
    from .fluid import monkey_patch_variable
  File "/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/fluid/core.py", line 271, in <module>
    raise e
  File "/data/yfzx/virtualenv/cpu/lib/python3.6/site-packages/paddle/fluid/core.py", line 241, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS
>>>

**Comment by littletomatodonkey** [comment]
你好，可以试着把glibc升级到2.2.3及以上吗？

**Comment by dyning** [comment]
> 你好，可以试着把glibc升级到2.2.3及以上吗？

2.23吧

**Comment by czblse** [comment]
> 你好，可以试着把glibc升级到2.2.3及以上吗？

你好，glibc我不敢乱升级，怕出问题影响其他服务使用，请问有其他解决办法吗？

**Comment by littletomatodonkey** [comment]
你好，可以试下在docker中进行开发，新版paddle对glibc版本是有一些要求

**Comment by czblse** [comment]
> 你好，可以试下在docker中进行开发，新版paddle对glibc版本是有一些要求

我打算在现有服务中加入paddleOCR，现有服务不是在docker的，用了新版的paddlepaddle，只能把glibc升级到2.23对吧？

**Comment by littletomatodonkey** [comment]
> > 你好，可以试下在docker中进行开发，新版paddle对glibc版本是有一些要求
> 
> 我打算在现有服务中加入paddleOCR，现有服务不是在docker的，用了新版的paddlepaddle，只能把glibc升级到2.23对吧？

嗯嗯 我也查了网上的一些解决方案，比较好的方法是这样的~

**Comment by czblse** [comment]
> > > 你好，可以试下在docker中进行开发，新版paddle对glibc版本是有一些要求
> > 
> > 
> > 我打算在现有服务中加入paddleOCR，现有服务不是在docker的，用了新版的paddlepaddle，只能把glibc升级到2.23对吧？
> 
> 嗯嗯 我也查了网上的一些解决方案，比较好的方法是这样的~

好的，感谢，我这边再权衡一下

**Comment by ChChwang** [comment]
有什么解决办法吗？
