### ISSUE TITLE
Bad inference results

### ISSUE THREAD

**Issue by divastar** [PaddlePaddle/PaddleOCR#10163]
Hi. I just downloaded the latest version
and run the following
wget https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar
tar xf en_PP-OCRv3_rec_infer.tar
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/word_1.png" --rec_model_dir="./en_PP-OCRv3_rec_infer/" --rec_char_dict_path="ppocr/utils/en_dict.txt"

But I am not getting any good results:
![word_1](https://github.com/PaddlePaddle/PaddleOCR/assets/50579056/a50c2df0-02d0-4c1f-b7c4-47d8f207a5e6)    gives
[2023/06/14 12:58:45] ppocr INFO: Predicts of C:\OCR\PaddleOCR\doc\my_input\word_1.png:('qvpuA', 0.998160719871521)
Thank you

**Comment by Rishav-hub** [comment]
@divastar what was the solution for this, how was the result improved?
