### ISSUE TITLE
运行PaddleOcr服务化报错

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleOCR#10160]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：GNU/Linux
- 版本号/Version：2.4.1.post117 PaddleOCR：2.6.1.3  问题相关组件/Related components：运行PaddleOcr服务化报错
- 运行指令/Command Code：python3 web_service.py --config=config.yml &>log.txt &
- 完整报错/Complete Error Message：
args config: {'rpc_port': 18091, 'http_port': 9998, 'worker_num': 10, 'build_dag_each_worker': False, 'dag': {'is_thread_op': False, 'retry': 10, 'use_profile': True, 'tracer': {'interval_s': 10}}, 'op': {'det': {'concurrency': 8, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': './ppocr_det_v3_serving', 'devices': '0', 'ir_optim': True}}, 'rec': {'concurrency': 4, 'timeout': -1, 'retry': 1, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': './ppocr_rec_v3_serving', 'devices': '0', 'ir_optim': True}}}}
Traceback (most recent call last):
  File "web_service.py", line 167, in <module>
    uci_service.prepare_pipeline_config(yml_dict=FLAGS.conf_dict)
TypeError: prepare_pipeline_config() got an unexpected keyword argument 'yml_dict'

**Comment by andyjpaddle** [comment]
更新下paddleserver的版本试试

**Comment by youde2000** [comment]
在web_service.py里的
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/54662806/99378222-c5dd-4bd3-86c1-3b0ab2ca2ed9)
要yml_file
