### ISSUE TITLE
TensorRT有动态信息文件时初始化特别慢，但是重新生成动态信息文件时的初始化特别快

### ISSUE THREAD

**Issue by JeremyGe07** [PaddlePaddle/PaddleOCR#10165]
1. 请问关于TensorRT，推理时开启use_tensorrt=True后，虽然模型输入图片到输出结果的时间有10%左右速度提升，但是程序前面TensorRT初始化过程特别慢（大概1分钟；关闭use_tensorrt的话只用5-10秒）。如果想在服务器端部署执行推理的话，有没有什么好的方法优化这个过程？还是只能放弃使用TensorRT。
2. 开启use_tensorrt=True时，对一个文件夹下的多张图片进行推理，TensorRT生成动态信息文件（例如det_trt_dynamic_shape.txt）并且初始化的过程很快，（也就是文件夹下没有动态信息文件，需要重新生成动态信息文件时）。但是当我模型文件夹下已经有动态信息文件后，TensorRT初始化过程特别慢，1-2分钟左右，是怎么回事呢

**Comment by JeremyGe07** [comment]
@andyjpaddle @LDOUBLEV  @WenmuZhou 大佬帮忙看下谢谢

**Comment by zyboyoung** [comment]
同问，初始化太慢了

**Comment by dkw-wkd** [comment]
为啥tensorrt一会加速，一会推理速度反而慢了10呗

**Comment by XJPeng12** [comment]
同问

**Comment by ermengz** [comment]
同问，怎么经常rebuild engine 文件？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
