### ISSUE TITLE
表格训练，这种效果怎样得到？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10172]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

想要得到如下这种坐标效果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/c454ca9b-9a1f-46d5-8fcd-93e1b99dc5f2)

paddle得到的效果如下
py -3 tools/infer_table.py -c L:\paddle\models\ch_ppstructure_mobile_v2.0_SLANet_train\SLANet_ch.yml -o Global.pretrained_model=L:\paddle\models\ch_ppstructure_mobile_v2.0_SLANet_train\best_accuracy  Global.infer_img=F:\0Table03\4.png

第一次运行会自动下载 https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x1_0_ssld_pretrained.pdparams

![4](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/07b2d4f5-9423-4bdb-80fb-eb7dfcb2e066)

**Comment by archwolf118** [comment]
先把表格截取下来，再识别

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
