### ISSUE TITLE
证件识别只训练ser不用re数据格式是如何定义的

### ISSUE THREAD

**Issue by zhibin-hong** [PaddlePaddle/PaddleOCR#10177]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
数据标签：123/48王超.jpg	[{"transcription": "姓名", "points": [[70, 56], [164, 56], [164, 106], [70, 106]], "difficult": false, "key_cls": "name_key"}, {"transcription": "性别", "points": [[71, 140], [164, 140], [164, 182], [71, 182]], "difficult": false, "key_cls": "gender_key"}, {"transcription": "出生", "points": [[71, 215], [168, 215], [168, 260], [71, 260]], "difficult": false, "key_cls": "birth_key"}, {"transcription": "住址", "points": [[68, 302], [157, 302], [157, 338], [68, 338]], "difficult": false, "key_cls": "address_key"}, {"transcription": "云南省昆明市", "points": [[185, 305], [584, 305], [584, 344], [185, 344]], "difficult": false, "key_cls": "address_value"}, {"transcription": "马村", "points": [[187, 353], [499, 353], [499, 393], [187, 393]], "difficult": false, "key_cls": "address_value"}, {"transcription": "公民身份号码", "points": [[73, 496], [291, 496], [291, 533], [73, 533]], "difficult": false, "key_cls": "idnumber_key"}, {"transcription": "6579", "points": [[337, 498], [853, 498], [853, 537], [337, 537]], "difficult": false, "key_cls": "idnumber_value"}, {"transcription": "name_value", "points": [[184, 53], [310, 53], [310, 103], [184, 103]], "difficult": false, "key_cls": "name_value"}, {"transcription": "gender_value", "points": [[183, 134], [241, 134], [241, 181], [183, 181]], "difficult": false, "key_cls": "gender_value"}, {"transcription": "民族", "points": [[289, 142], [374, 142], [374, 184], [289, 184]], "difficult": false, "key_cls": "Nation_key"}, {"transcription": "汉", "points": [[382, 144], [424, 144], [424, 190], [382, 190]], "difficult": false, "key_cls": "Nation_value"}, {"transcription": "1999年14月", "points": [[182, 210], [508, 210], [508, 264], [182, 264]], "difficult": false, "key_cls": "birth_value"}]，这种格式可以直接训练吗

**Comment by livingbody** [comment]
训练ser，数据集格式不变。
参看：PaddleOCR/doc/doc_ch/dataset/kie_datasets.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/kie_datasets.md

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
