### ISSUE TITLE
OCRv3 npu推理报错the following arguments are required: --recipe, --mode

### ISSUE THREAD

**Issue by haley8776** [PaddlePaddle/PaddleOCR#10176]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：rk3588
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- python infer.py  --det_model ./rknn/ch_PP-OCRv3_det_infer/det_rk3588_unquantized.rknn --rec_model ./rknn/ch_PP-OCRv3_rec_infer/rec_rk3588_unquantized.rknn  --rec_label_file ppocr/utils/ppocr_keys_v1.txt --image 1.png --device npu
- 完整报错/Complete Error Message：
- 并没看到这个参数说明，不知道如何使用
-usage: infer.py [-h] --recipe RECIPE --mode MODE [--queue_dir QUEUE_DIR] [--base BASE] [--docker_args DOCKER_ARGS]
                [--predictor PREDICTOR]
infer.py: error: the following arguments are required: --recipe, --mode

**Comment by charlesMrH** [comment]
尝试根据https://github.com/PaddlePaddle/FastDeploy， 重新安装fastdeploy库
