### ISSUE TITLE
如何保存识别模型进行数据增强后的图片数据？

### ISSUE THREAD

**Issue by HappyJiaJun** [PaddlePaddle/PaddleOCR#10188]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by livingbody** [comment]
没明白你的意识，是下面哪种？
- 1.如何保存模型？
- 2.如何保存数据增强后的图片？

你看看是哪个意思？

**Comment by HappyJiaJun** [comment]
我的本意是保存2，目前已经解决，在定义transform后增加代码即可保存每轮训练的图片



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月30日 17:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 如何保存识别模型进行数据增强后的图片数据？ (Issue #10188) |

没明白你的意识，是下面哪种？

1.如何保存模型？
2.如何保存数据增强后的图片？

你看看是哪个意思？

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by LeslieWongCV** [comment]
@hellohahaw 

我也遇到了不能保存模型增强的结果， save_to_img但是保存的是原图＋修正后，请问你是怎样可以保存修正后的图片，谢谢

**Comment by hellohahaw** [comment]
时间太久了，我记得需要略微修改一下源代码，不难的



---- 回复的原邮件 ----
| 发件人 | Lester ***@***.***> |
| 日期 | 2025年07月29日 13:58 |
| 收件人 | ***@***.***> |
| 抄送至 | hello ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 如何保存识别模型进行数据增强后的图片数据？ (Issue #10188) |
LeslieWongCV left a comment (PaddlePaddle/PaddleOCR#10188)

@hellohahaw

我也遇到了不能保存模型增强的结果， save_to_img但是保存的是原图＋修正后，请问你是怎样可以保存修正后的图片，谢谢
