### ISSUE TITLE
Training paddleocr ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Rudragoud** [PaddlePaddle/PaddleOCR#10186]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Google colab
- 版本号/Version：Paddle：2.4.2.  PaddleOCR：2.4.2  问题相关组件/Related components：
- 运行指令/Command Code：!python3 /content/drive/MyDrive/PaddleOCR-release-2.6/tools/train.py -c /content/drive/MyDrive/PaddleOCR-release-2.6/training_paddleocr/my_config.yml -o Global.pretrained_model=/content/drive/MyDrive/PaddleOCR-release-2.6/New folder/best_accuracy

- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/train.py", line 206, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/program.py", line 623, in preprocess
    FLAGS = ArgsParser().parse_args()
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/program.py", line 61, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/program.py", line 70, in _parse_opt
    k, v = s.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Sayaka91** [comment]
@Rudragoud 
It seems because the parameter `-o` (`opts` value )realized as a string, `s` is a single character ('`G`') instead of the total value ('`Global.pretrained_model=pretrain_models/japan_PP-OCRv3_rec_train/best_accuracy.pdparams`')
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49243283/42ab32c2-89bc-4623-ae87-7619ea76b428)

**Comment by Rudragoud** [comment]
Thanks for the solution.

**Comment by Rudragoud** [comment]
I0627 04:33:32.528741  3901 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.

Where I need to modify above code

**Comment by ajith9902** [comment]
I am too facing issue while train new models.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/138596021/5e763134-f1fb-4772-ad08-6ee0a1a60d4b)

**Comment by AbdulDD** [comment]
I am also getting same error in training PGNet. Can you please! guide me further on it for PGNet training?

**Comment by ajith9902** [comment]
Hi @AbdulDD, check this #10295

**Comment by AbdulDD** [comment]
Hi @ajith9902 thank you for your response.
I have implemented the method in #10295 but for me it didn't worked. can you please! share what else can done to solve it.

**Comment by ajith9902** [comment]
> I am too facing same issue while train new models. ![image](https://user-images.githubusercontent.com/138596021/250916980-5e763134-f1fb-4772-ad08-6ee0a1a60d4b.png)

@AbdulDD  I encountered this issue only while training new model from paddle framework, so if you are having the same issue, try paddle docker images for version 2.4.2.

if you are getting different error message or issue, share the exact error details

**Comment by AbdulDD** [comment]
I am having the above mentioned issue.
Further I have created a open thread issue #10348

**Comment by AbdulDD** [comment]
@ajith9902 I am having this issue the one that is mentioned above #10348
