### ISSUE TITLE
表格检测+表格识别端到端识别  和先检测。再用检测出来的图片去表格识别，效果有差异？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#10189]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- ubunut 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0

- 运行指令/Command Code：
- 完整报错/Complete Error Message：
发现端到端预测的时候，其中的roi_img 和 roi_img写到文件之后   单独识别的时候，img = cv2.imread(image_file)去读取的时候不一样
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/a17e0540-129c-46b4-8ae1-c1a4950642e5)

**Comment by rexzhengzhihong** [comment]
做一个 cv2.imwrite 然后  cv2.imread(img_path)就没问题，要怎么改？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/cb5f4e4e-b758-443a-a51d-6348bd65c5bd)

**Comment by gl94** [comment]
.copy()就没问题了 这个涉及到三维图片存储的问题

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
