### ISSUE TITLE
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by loading2022** [PaddlePaddle/PaddleOCR#10199]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：cuda 11.6 
- 版本号/Version：
paddlenlp               2.5.2
paddleocr               2.6.1.3
paddlepaddle            2.4.2
paddlepaddle-gpu        2.4.2.post116
问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o OPT=Value
- 完整报错/Complete Error Message：W0619 03:05:28.154407 19728 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 11.6
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

網路上的方式有嘗試過，但還是報錯

**Comment by loading2022** [comment]
已解决

**Comment by YikunHan42** [comment]
> 已解决

请问怎么解决的呢

**Comment by loading2022** [comment]
可以參考這個 [issue](https://github.com/PaddlePaddle/Paddle/issues/54767)

**Comment by YikunHan42** [comment]
> 可以參考這個 [issue](https://github.com/PaddlePaddle/Paddle/issues/54767)

感谢
