### ISSUE TITLE
sentence accuracy在百度飞桨中是不是就是字符识别全对的样本/全部样本？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#10196]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by UserWangZz** [comment]
是的

该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
