### ISSUE TITLE
Continuous download of ch_PP-OCRv3_det_infer.tar

### ISSUE THREAD

**Issue by pepperav** [PaddlePaddle/PaddleOCR#10197]
ehi 👋,
I'm going to create a service by an AWS Lambda as Docker Image. 

Even though I've putted `rec_model_dir`, `det_model_dir` and `cls_model_dir` to a local path with models already there,
every run it still download _ch_PP-OCRv3_det_infer.tar_

**Code:**
`

              import sys
              from paddleocr import PaddleOCR,draw_ocr
              
              def handler(event, context):
                  ocr = PaddleOCR(ocr = PaddleOCR(det=False, det_model_dir='/tmp/whl/det/en/en_PP-OCRv3_det_infer/', rec_model_dir='/tmp/whl/rec/en/en_PP-OCRv3_det_infer/', cls_model_dir='/tmp/whl/cls/en/en_PP-OCRv3_det_infer/', use_angle_cls=False, use_gpu=False, lang='en'))
              
                  return 'Hello from AWS Lambda using Python' + sys.version + '!'

`

**Log:**
`download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to /home/sbx_user1051/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.tar`

How can I avoid that?
Thank you

**Comment by Sayaka91** [comment]
@pepperav 
I got the similar problem. It seems cause of paddleocr version. You can try down version to 2.6.1.2

**Comment by pepperav** [comment]
Thank you @Sayaka91 , I will try.

Actually with this folders tree:
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/11539474/f7baae71-da2f-4fd7-b534-249bc5262426)

and this code line:
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/11539474/5cc070cb-8220-48b5-a98f-d3df0c320e68)

it works without any other download.

**Comment by BisarAhmed** [comment]
any solution for this error it cause the failing for  the docker compose up command start downloading before the download end it give this error 
`FileNotFoundError: [Errno 2] No such file or directory: '/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer/Multilingual_PP-OCRv3_det_infer.tar'`

**Comment by pepperav** [comment]
I see multilingual on the log printed by you. In my case I forced to be only english `lang='en'`.

I guess this is the reason why it try to download other stuff.

**Comment by BisarAhmed** [comment]
i passed use_onnx as true it stopped  downloading but failed at reading .tar files. i am still debugging  

`    use_onnx=True,
        det_model_dir="whl/det/en/en_PP-OCRv3_rec_infer.tar",
        rec_model_dir="whl/rec/en/en_PP-OCRv3_rec_infer.tar",
        cls_model_dir="whl/cls/en/ch_ppocr_mobile_v2.0_cls_infer.tar"`
        
        
        
        ` INVALID_PROTOBUF : Load model from whl/cls/en/ch_ppocr_mobile_v2.0_cls_infer failed:Protobuf parsing failed.`

**Comment by pepperav** [comment]
I don't know what `use_onnx` does but you should specify folders with tar files already extracted!

eg:
**wrong**: det_model_dir="whl/det/en/en_PP-OCRv3_rec_infer.tar"
**valid**: det_model_dir="whl/det/en/en_PP-OCRv3_rec_infer/"

**Comment by khansajeel** [comment]
@BisarAhmed you should not put in tar files there, use extracted directories. it should work

**Comment by BisarAhmed** [comment]
@khansajeel @pepperav thanks it solved the download issue

**Comment by madhavi1102** [comment]
@Sayaka91  without following the mentioned structure by you for downloading det, rec, pls models, it is working fine with specifying any local path used for referring these extracted models.

**Comment by oscarjose9423** [comment]
@pepperav Hey I am doing this right now, would you mind sharing your Dockerfile? the solution and folder structure did not work for me. Additionally I am getting an error:

able to unmarshal input: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte 

when testing the container locally

**Comment by pepperav** [comment]
> @pepperav Hey I am doing this right now, would you mind sharing your Dockerfile? the solution and folder structure did not work for me. Additionally I am getting an error:
> 
> able to unmarshal input: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
> 
> when testing the container locally

Sure!

```
FROM public.ecr.aws/lambda/python:latest-x86_64

COPY requirements.txt ./

RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
RUN yum check-update; if [ $? -eq 100 ]; then exit 0; else exit $?; fi
RUN yum install -y libgomp mesa-libGL

COPY app.py ${LAMBDA_TASK_ROOT}
COPY whl ${LAMBDA_TASK_ROOT}/whl

CMD [ "app.handler" ]
```

This is the `requirements.txt` file:
```
paddleocr
paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Note**: `LAMBDA_TASK_ROOT` – The path to your Lambda function code.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
