### ISSUE TITLE
表格识别结果，怎么分辨是否已经正确识别？可视化看不出来

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10191]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

表格识别结果，怎么分辨是否已经正确识别？可视化看不出来
![bz](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/3ad2104c-2518-483e-909e-f2fed5b7f92f)

期望的效果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/77388b17-9601-468a-a103-fefcd06c135d)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
