### ISSUE TITLE
Different results between test and inference of the same model

### ISSUE THREAD

**Issue by bahar3474** [PaddlePaddle/PaddleOCR#10194]
Hi. I'm trying to fine-tune the English detection model following [this](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/detection_en.md) document. After re-training the model for about 100 epoches on custom dataset, I test the model with following command.
```bash
python3 tools/infer_det.py -c /path/to/ch_PP-OCRv3_det_cml.yml -o Global.infer_img=/path/to/images/dir Global.pretrained_model=/path/to/latest.pdparams Global.use_gpu=True
```
and I got this result:

![text_detection_v01_0](https://github.com/PaddlePaddle/PaddleOCR/assets/48449058/f0b8b78f-1954-4bd7-9212-d112e18152c7)

Then I export the model with tools/export_model.py script and check the results of each of three exported models, Teacher, Student and Student2 with following command.
```bash
python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir=/path/to/exported/model/dir --image_dir=/path/to/images/dir --use_gpu=True
```
For all of the three exported models, I got such a more accurate result. You can see an example below:

![det_res_text_detection_v01_0](https://github.com/PaddlePaddle/PaddleOCR/assets/48449058/fd73b4d8-76bf-4fb5-a9f7-198bdfb83066)
Why are the results of the non-exported version of the model so different from the results of the exported version of the same model? Same thing happend when I test and inference [the pretrained English text detection model](https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_distill_train.tar).

- System Environment：Windows 11 Enterprise
- Version: paddlepaddle_gpu-2.4.1

**Comment by masoudMZB** [comment]
same problem here
any progress since then? @bahar3474

**Comment by bahar3474** [comment]
> same problem here any progress since then? @bahar3474

I noticed that the shape of the input images after preprocessing is very different. I checked the operations that are run on the images and found that the "DetResizeForTest" configs have different values before and after the model is exported. I don't know why this happened, but to fix it, you should add the following options to your config file:
```
Eval:
  dataset:
    transforms:
    - DetResizeForTest:
        limit_side_len: 960
        limit_type: max
```

**Comment by shiyutang** [comment]
The problem is that DetResizeForTest's default params are `[limit_side_len: 736, limit_type: min](https://github.com/PaddlePaddle/PaddleOCR/blob/fac03876f39bc67acc8eef6d7facb9a2206eeecd/ppocr/data/imaug/operators.py#L221)`, which will resize the short size to 736 and rescale the image proportionally. During training, the image size is set to [960, 960]. However, the width/height ratio of the image you show is around  1:5, and the width will be reshaped to 3680, which is too big for the net to correctly infer.
