### ISSUE TITLE
请问怎么实现白纸黑字，怎么实现文字前景和背景的分离？

### ISSUE THREAD

**Issue by bemjimm** [PaddlePaddle/PaddleOCR#10198]
有没有办法将单独的文字前景一个一个字符单独抠出来？

**Comment by xu-peng-7** [comment]
有的，检测标签你打到 char级别，但是只能根据像素扣，所以背景不能有干扰。

**Comment by kbaicai** [comment]
请问怎么实现？背景可以自适应阈值去掉，但是不知道怎么将单独的字体扣出来。。

**Comment by xu-peng-7** [comment]
两个方案吧 你现在的标签是 词级别的box 或者说 句子级别的box，你的标注要 打到 字 级别。模型识别出来就是单独的文字了。还有就是抠出来之后，根据在水平方向和垂直方向的像素投影。然后裁切，但是第二种方法不是特别准。

**Comment by kbaicai** [comment]
就是还是得收集数据训练是吗？





------------------ 原始邮件 ------------------
发件人: Dec20B ***@***.***&gt;
发送时间: 2023年6月20日 09:38
收件人: kbaicai ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 请问怎么实现白纸黑字，怎么实现文字前景和背景的分离？ (Issue #10198)





 
两个方案吧 你现在的标签是 词级别的box 或者说 句子级别的box，你的标注要 打到 字 级别。模型识别出来就是单独的文字了。还有就是抠出来之后，根据在水平方向和垂直方向的像素投影。然后裁切，但是第二种方法不是特别准。
