### ISSUE TITLE
ocr轻量级模型部署移动端

### ISSUE THREAD

**Issue by zqnnn** [PaddlePaddle/PaddleOCR#102]
请问有没有考虑过移动端部署呢？具体是什么流程呢？

**Comment by LDOUBLEV** [comment]
> 请问有没有考虑过移动端部署呢？具体是什么流程呢？

已经在考虑移动端部署了，预计6月中下旬会发布PaddleOCR的移动端部署方案。具体方式是使用paddle lite部署PaddleOCR小模型

**Comment by breezechen** [comment]
Mark. 持续关注，期待`paddle lite`部署方式

**Comment by LDOUBLEV** [comment]
> Mark. 持续关注，期待`paddle lite`部署方式

预计六月底release lite部署方案
