### ISSUE TITLE
请问文档文本检测中使用自己的数据微调时loss经久不降是什么原因呢？

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#10207]
请教大佬们：
1. 为什么我使用自己的数据做文档文本检测的时候，loss经久不降？
信息：
3. 使用的配置文件是：det_r50_vd_db.yml
4. 使用预训练模型为resnet_r50
5. 自己标注的是一些教材页面，用paddleLabel进行标注。数据如下
![01_upscale](https://github.com/PaddlePaddle/PaddleOCR/assets/56385078/9dfc453f-b912-4510-8e43-90c267853a56)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
