### ISSUE TITLE
win10 英文版中的几个问题

### ISSUE THREAD

**Issue by hktalent** [PaddlePaddle/PaddleOCR#10206]
1、需要手工提前安装VC_redist.x64.exe （2015）
2、英文版本win10系统的，即便我手工安装了
微软雅黑.ttf
微软vista黑体.ttf
Songti.ttc

依然无法ocr 出中文

**Comment by hktalent** [comment]
<img width="313" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/18223385/fb8c7a27-bc91-4baa-a89c-812661f4bc69">

**Comment by hktalent** [comment]
补充说明：相同的代码，在英文版本的macos上识别中文没有问题

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
