### ISSUE TITLE
ppstructure表格分析结果不正确

### ISSUE THREAD

**Issue by xuchaoguo1983** [PaddlePaddle/PaddleOCR#10208]
- 系统环境/System Environment：MacOS
- 版本号/Version：Paddle：2.4.2  PaddleOCR： 2.6.1.3
- 运行指令/Command Code：

import cv2
from paddleocr import PPStructure

table_engine = PPStructure(recovery=True, layout=True)

save_folder = './output'
img_path = './input/table.jpg'
img = cv2.imread(img_path)
result = table_engine(img)
print("result:", result)

- 完整报错/Complete Error Message：
将输出的html转换成表格显示格式不对，有哪位大神知道该如何解决么？
![source.jpg](https://github-production-user-asset-6210df.s3.amazonaws.com/13973531/246803598-cc95106a-b6d4-4183-9a90-4d7676645c4b.jpg)

**Comment by livingbody** [comment]
图呢？哪儿错了？复杂表格会有点出入。验证了。
![360截图20230630235309965](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/b86d38a8-b49f-4aec-b5cb-d30b48320fc4)

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
