### ISSUE TITLE
论文中的曲线图有办法识别吗？找了一圈没相关的技术

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleOCR#10201]
如下：
![1](https://github.com/PaddlePaddle/PaddleOCR/assets/88191580/4d36dc0a-63e5-4fea-8593-c396804e0346)

想识别出最大值，最小值，初始化值，结束值等信息，最终想实现一个点击曲线上的某个点，能实现显示x和y值的功能

**Comment by ToddBear** [comment]
该问题具体功能的实现与OCR关系好像不大

能否先用OCR工具识别出坐标轴上标识的数值和坐标，再通过插值的方式获取网格中某个点相应的(x, y)值？
