### ISSUE TITLE
Issue in doing OCR on a simple image.

### ISSUE THREAD

**Issue by ArivCR7** [PaddlePaddle/PaddleOCR#10202]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04 x86, Nvidia GPU 3070Ti CUDA 11.2 CUDNN 8.3
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：latest version - Detector model - en_PP-OCRv3_det(https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar) Recognition Model - en_PP-OCRv3_rec(https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar) Key file - en_dict.txt

Hello Team,

PaddleOCR works out of the box on the printed texts on labels and receipts. But I have an issue in doing OCR on this simple image. Can you please let me know what could be the issue with this image? 

![white_on_blkbg](https://github.com/PaddlePaddle/PaddleOCR/assets/28477568/d8d0dee1-8bdc-428d-a392-86e12d15e6d5)

This is the result I got:

text: NERPI6IZLIL -------------- scores: 0.4638494551181793
inference time in ms: 92.56663499763818

**Comment by livingbody** [comment]
**you need to fineture you det model.**

检测的问题，det boxes: [[152,174],[376,163],[378,207],[154,218]]rec text: NERPI6IZLIL rec score:0.463844 cls label: 0 cls score: 0.947102。把两行检测成一行了。所以识别错误了。需要重新训练检测模型。

**Comment by livingbody** [comment]
![Uploading visualized_result.jpg…]()
![ac4cbb6b3b6d48b7d91d343ec13b473](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/c02f6163-87ff-45c2-a656-edc7560a7f6e)

**Comment by shiyutang** [comment]
The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by ArivCR7** [comment]
Hi @shiyutang , Should the detector model alone be finetuned or the recognition model as well?

**Comment by shiyutang** [comment]
The problem is with the detector model.
