### ISSUE TITLE
图片文本方向预处理

### ISSUE THREAD

**Issue by Carson-688** [PaddlePaddle/PaddleOCR#10205]
![20230619154001](https://github.com/PaddlePaddle/PaddleOCR/assets/39986384/d575613a-c844-4ff4-a4b6-92062c21383c)
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问能够对图片进行预处理吗，图片可能是90度，这样在识别前纠正

**Comment by livingbody** [comment]
有方向识别的。

**Comment by shiyutang** [comment]
@livingbody 需要进一步提供方向识别设置～

**Comment by livingbody** [comment]
参考方向识别文档，从训练到预测全流程都有：

PaddleOCR/doc/doc_ch/angle_class.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/angle_class.md

![360截图20230703170754037](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/48199867-e835-4078-928e-0862437694ef)

**Comment by livingbody** [comment]
识别角度后，可以用opencv等rotate进行矫正。

**Comment by Carson-688** [comment]
> 识别角度后，可以用opencv等rotate进行矫正。
图片识别出来只有0度和180度，如果是90度或者270度，识别出来还是0度和180度，这种情况下我怎么知道要旋转多少度

**Comment by livingbody** [comment]
> > 识别角度后，可以用opencv等rotate进行矫正。
> > 图片识别出来只有0度和180度，如果是90度或者270度，识别出来还是0度和180度，这种情况下我怎么知道要旋转多少度

文本方向分类器主要用于图片非0度的场景下，在这种场景下需要对图片里检测到的文本行进行一个转正的操作。在PaddleOCR系统内， 文字检测之后得到的文本行图片经过仿射变换之后送入识别模型，此时只需要对文字进行一个0和180度的角度分类，因此PaddleOCR内置的 文本方向分类器只支持了0和180度的分类。如果想支持更多角度，可以自己修改算法进行支持。

**Comment by shiyutang** [comment]
根据文档中的例子，你的示例图片属于180度

**Comment by EasyIsAllYouNeed** [comment]
这个问题是文档方向识别问题，还不是文本方向识别；
文档方向识别参考 [(https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
