### ISSUE TITLE
How to Distributed Inference

### ISSUE THREAD

**Issue by onejlee** [PaddlePaddle/PaddleOCR#10212]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04, docker
- 版本号/Version：Paddle：2.3.1  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
`python -m paddle.distributed.launch --gpus '0,1' tools/infer/predict_det.py --image_dir="/wjlee/5350023-1999-0001-0020.jpg" --det_model_dir="/wjlee/models/Multilingual_PP-OCRv3_det_infer/"`
- 完整报错/Complete Error Message：
`
[2023/06/20 00:49:38] ppocr INFO: The predict time of /wjlee/5350023-1999-0001-0020.jpg: 1.4904873371124268
[2023/06/20 00:49:38] ppocr INFO: The visualized image saved in ./inference_results/det_res_5350023-1999-0001-0020.jpg
INFO 2023-06-20 00:49:44,401 launch_utils.py:343] terminate all the procs
INFO 2023-06-20 00:49:44,401 launch_utils.py:343] terminate all the procs
ERROR 2023-06-20 00:49:44,402 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
ERROR 2023-06-20 00:49:44,402 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2023-06-20 00:49:48,406 launch_utils.py:343] terminate all the procs
INFO 2023-06-20 00:49:48,406 launch_utils.py:343] terminate all the procs
INFO 2023-06-20 00:49:48,406 launch.py:402] Local processes completed.
INFO 2023-06-20 00:49:48,406 launch.py:402] Local processes completed.
`

Hi I want to make OCR inference process using multi GPU. (python)
I've tried 2 ways 
1. add `paddle.distributed.launch`  in inference command.
2. In inference script code, wrapping the model with `paddle.DataParallel`
-> error : AttributeError: 'paddle.fluid.core_avx.PaddleInferPredictor' object has no attribute 'full_name

but both way occurs an error.

How can I make distributed inference process?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
