### ISSUE TITLE
paddleOCR 支持 32位的python 环境安装吗

### ISSUE THREAD

**Issue by wenxuezhang** [PaddlePaddle/PaddleOCR#10215]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by 302658980** [comment]
同问，现在支持了嘛，今天也遇到了这个问题。

**Comment by wenxuezhang** [comment]
阅读了各个版本的对python的pip的支持要求，发现paddle不支持32位



张文学  pi  国际事业部 
Mobile:+86-18210275525
E-mail: ***@***.***
PERCENT.CN - Decision Intelligence
北京市海淀区建材城中路27号金隅智造工场S5栋西侧 100096

 
 
发件人： 302658980
发送时间： 2023-07-27 11:12
收件人： PaddlePaddle/PaddleOCR
抄送： wenxuezhang; Author
主题： Re: [PaddlePaddle/PaddleOCR] paddleOCR 支持 32位的python 环境安装吗 (Issue #10215)
同问，现在支持了嘛，今天也遇到了这个问题。
