### ISSUE TITLE
Compile the inference source code (Windows) inference_lib_dist

### ISSUE THREAD

**Issue by Kassy607** [PaddlePaddle/PaddleOCR#10229]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

I followed to steps mentioned in the repo for compiling the inference source code (i changed it a bit to get it running on windows). 

Its possible to run this command without errors: 
cmake .. -DWITH_CONTRIB=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_INFERENCE_API_TEST=OFF -DON_INFER=ON -DWITH_PYTHON=ON

Afterwards i have the build folder with the following things inside: 
![grafik](https://github.com/PaddlePaddle/PaddleOCR/assets/118922869/dd1a50ec-32e6-46fa-811b-6324214f7598)

in the paddle_inference_install_dir is just a version.txt-file containing this: 
Paddle version: 0.0.0
GIT COMMIT ID: 1b8a1a982845ffef44679f79da363a8e7f3b20ba
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
WITH_IPU: OFF
CXX compiler version: 19.36.32535.0

How can I get the rest? CMakeCache.txt, paddle folder and third_party

**Comment by shiyutang** [comment]
This seems to me is a paddle inference compile issue. I think you should find help in the paddle inference repo. Please point out if I am wrong and provide the script you run.
