### ISSUE TITLE
fastdeploy部署服务后怎么修改配置参数呢

### ISSUE THREAD

**Issue by zhouyiminga** [PaddlePaddle/PaddleOCR#10227]
系统环境/System Environment：docker
版本号/Version： fastdeploy:1.0.4-cpu-only-21.10

我需要配置最大只识别两行文字，看文档是有max_candidates这么个配置参数是符合我要求的。fastdeploy那块问了两次都没人解答，跑来这边也问一下··
我能通过下面的命令使用工具获取只有两个文本框的图片
python3 infer_det.py -c ch_PP-OCRv3_det_student.yml -o Global.infer_img="12.jpg" Global.pretrained_model="student" Global.use_gpu=False PostProcess.max_candidates=2
![12](https://github.com/PaddlePaddle/FastDeploy/assets/41407267/c141d159-6328-4aa6-8764-e4263b8eddbb)

但是这个配置我怎么在FastDeploy服务里配置呢？我想在java上面调用，所以只能调用服务。我看着服务里的文件也没有长得像yml的东西啊
![QQ图片20230622034214](https://github.com/PaddlePaddle/FastDeploy/assets/41407267/a2b6f297-5a24-4661-b60e-d770e7009f3f)

**Comment by teymur-git** [comment]
@zhouyiminga 直接对服务响应结果做修改，
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/60127735/dbe07b0f-8ec5-4611-96e3-745e3763fa19)

**Comment by teymur-git** [comment]
或者对fastdeploy服务模型仓库的det_postprocess内的model.py文件响应结果做限制

**Comment by zhouyiminga** [comment]
> 或者对fastdeploy服务模型仓库的det_postprocess内的model.py文件响应结果做限制

这两种方案都是处理识别结果不够治本啊。我图片来源不稳定，我担心一些图片需要识别太久所以想设一个识别上限，就算有10行文字也只识别两行啥的。不过这个model.py我之前也翻到过，不知道能不能在这里设置参数呢，我之前搞了下没生效。
det_preprocess里的model.py
![QQ图片20230628165147](https://github.com/PaddlePaddle/PaddleOCR/assets/41407267/7a408f1d-9fa0-4c55-a555-3b3002c66bec)
det_postprocess里的model.py
![QQ截图20230628171002](https://github.com/PaddlePaddle/PaddleOCR/assets/41407267/7b43cb4c-cddf-4e34-be72-fe8824d4829e)

**Comment by shiyutang** [comment]
@teymur-git 我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
