### ISSUE TITLE
Error training ch_PP-OCRv4_rec_ampO2_ultra.yml -> win10

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#10225]
[2023/06/21 18:36:11] ppocr INFO: valid dataloader has 123 iters
Traceback (most recent call last):
  File "D:\PaddleOCR-dygraph\tools\train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "D:\PaddleOCR-dygraph\tools\train.py", line 182, in main
    model, optimizer = paddle.amp.decorate(
TypeError: decorate() got an unexpected keyword argument 'dtype'

**Comment by livingbody** [comment]
# 你用aistudio环境来试试，linux的比较稳定，感觉你这个是安装错误的问题。

**Comment by shiyutang** [comment]
This issue may be related to the paddle version, currently, paddle.amp.decorate have the type params in paddle 2.4 and above: https://www.paddlepaddle.org.cn/documentation/docs/zh/2.5rc1/api/paddle/amp/decorate_cn.html

**Comment by centurions** [comment]
Thx I'll check that

**Comment by Jverson** [comment]
I have also encountered this problem, and my solution is to reduce the version of paddle-bfloat from 0.1.7 to 0.1.5

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
