### ISSUE TITLE
您好，有没有按单字识别率算准确率的文字识别算法？

### ISSUE THREAD

**Issue by zeng-cy** [PaddlePaddle/PaddleOCR#10228]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by shiyutang** [comment]
这个修改metric即可，即metric为每个字符识别正确的比例。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
