### ISSUE TITLE
Problem at running the kie readMe

### ISSUE THREAD

**Issue by andreaIskanderBelkhir** [PaddlePaddle/PaddleOCR#10226]
Using the comand to predict used on the read me for the  pretrained model i'm getting this  error:

 `RuntimeError: Can't load weights for 'ser_vi_layoutxlm_xfund_pretrained'.
Please make sure that 'ser_vi_layoutxlm_xfund_pretrained' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).`

even if i download the .tar (after unzipping it give a generic file type  )

**Comment by livingbody** [comment]
Check that the path is correct and the model is correct

**Comment by shiyutang** [comment]
ser_vi_layoutxlm_xfund_pretrained.pdparams should be in the path you execute this script.

**Comment by andreaIskanderBelkhir** [comment]
i understand that but the file i downloaded is not a folder but as a generic file type

**Comment by andreaIskanderBelkhir** [comment]
ok thats strange, i redownloaded with your link and this is what its inside the .tar
![immagine](https://github.com/PaddlePaddle/PaddleOCR/assets/50459917/ad7ab71a-796e-4063-9e68-0f17ecf1b955)

**Comment by shiyutang** [comment]
maybe you can try downloading and unzipping in linux/mac system.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
