### ISSUE TITLE
ocr斜45角的名片 完全不识别？不支持纠偏？内部没做一个透视修正？

### ISSUE THREAD

**Issue by gowy222** [PaddlePaddle/PaddleOCR#10233]
直接浏览器首测 劝退? ..  .直接上图
![156](https://github.com/PaddlePaddle/PaddleOCR/assets/52201479/d792f8b4-2d97-44fc-8e74-85722cb19ec5)

**Comment by shiyutang** [comment]
可以给出预处理相关的代码

> 我这边做了预处理之后

**Comment by Gmgge** [comment]
@shiyutang 因为涉及内部项目问题，暂时无法提供旋转纠代码。如果提问者有进一步的想法，可以提供更具体的思路，例如想要尝试文本检测的多角度增强训练，或者希望做旋转纠正预处理。

1.在针对文本检测的多角度增强训练方向，可以尝试修改训练的配置文件即可获得相对稳定的效果；
2.旋转纠正需要确定使用者所应用的图像场景，往往是传统图像处理方法，难以在通用的场景保持精度

如果需要通用场景的多角度文本检测能力，建议是重新训练模型

**Comment by shiyutang** [comment]
好的～

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
