### ISSUE TITLE
ValueError: not find model.pdmodel or inference.pdmodel in inference/en_PP-OCRv3_det_infer

### ISSUE THREAD

**Issue by som21302** [PaddlePaddle/PaddleOCR#10238]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：google colab
- 版本号/Version：Paddle：  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：%cd PaddleOCR/ppstructure
!python3 /content/PaddleOCR/ppstructure/table/predict_table.py --det_model_dir=inference/en_PP-OCRv3_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=/content/Capture8.PNG --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ./output/table
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 230, in <module>
    main(args)
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 153, in main
    table_sys = TableSystem(args)
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 67, in __init__
    self.text_detector = predict_det.TextDetector(copy.deepcopy(
  File "/content/PaddleOCR/tools/infer/predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/content/PaddleOCR/tools/infer/utility.py", line 197, in create_predictor
    raise ValueError(
ValueError: not find model.pdmodel or inference.pdmodel in inference/en_PP-OCRv3_det_infer

**Comment by shiyutang** [comment]
这个是动转静路径问题。

**Comment by livingbody** [comment]
报错信息讲 “--det_model_dir=inference/en_PP-OCRv3_det_infer ”配置的目录  **inference/en_PP-OCRv3_det_infer** 下没有model.pdmodel 或 inference.pdmodel 模型名称，建议检查相对路径，或者直接改为绝对路径。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by SaiVimenthan** [comment]
ValueError: not find model.pdmodel or inference.pdmodel in C:\Users\saivi\Internship ML(OCR)\PaddleOCR\ppstructure\inference\ch_ppocr_mobile_v2.0_det_infer.tar
I'm still facing this error I have been trying for this past 1 week lol
