### ISSUE TITLE
eval 跑不动，也没报错

### ISSUE THREAD

**Issue by loading2022** [PaddlePaddle/PaddleOCR#10235]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：cuda 11.6
- 版本号/Version：
Paddle：2.4.2
PaddleOCR：2.6.1.3
问题相关组件/Related components：
- 运行指令/Command Code：python tools/eval.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o OPT=Value
- 完整报错/Complete Error Message：没有报错，但是 eval 跑不动
<img width="959" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/db7c0732-839a-4160-a9d4-409969f64f5a">

**Comment by livingbody** [comment]
您上传的图片打不开看不见。
建议你在aistudio上复现并分享项目给我。
我得微信：livingbody

**Comment by loading2022** [comment]
已解决
