### ISSUE TITLE
Query: Default  location of downloaded model files

### ISSUE THREAD

**Issue by mineshmathew** [PaddlePaddle/PaddleOCR#10234]
I am following the code snippet given [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md) to run OCR on an image. I wanted to know where the downloaded model will be saved to. My home directory is quite small in size. So if models are getting downloaded to home I would like to change the default location. How do I do it?

**Comment by livingbody** [comment]
what's your os type?

**Comment by livingbody** [comment]
- You can modify file PaddleOCR/paddleocr.py  at line 492 to solve this problem.

```
        # download model if using paddle infer
        if not params.use_onnx:
            maybe_download(params.det_model_dir, det_url)
            maybe_download(params.rec_model_dir, rec_url)
            maybe_download(params.cls_model_dir, cls_url)

```

**Comment by shiyutang** [comment]
The above has solved the problem, please reopen this issue if there is following up question. And you are welcomed to participate in our activity:https://github.com/PaddlePaddle/PaddleOCR/issues/10223
