### ISSUE TITLE
Install from source?

### ISSUE THREAD

**Issue by Hegelim** [PaddlePaddle/PaddleOCR#10231]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu 20.04

How to install from source? There doesn't seem to be any information in the documentation. Or, is there a way to install it in development mode?

**Comment by livingbody** [comment]
下载源码，然后这样安装
```
pip install -r requirements.txt
pip install -e ./
```

**Comment by shiyutang** [comment]
The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:https://github.com/PaddlePaddle/PaddleOCR/issues/10223
