### ISSUE TITLE
保存识别结果的时候，弹窗提示 "Check the image first",什么原因呢

### ISSUE THREAD

**Issue by zengyangzang** [PaddlePaddle/PaddleOCR#10237]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by shiyutang** [comment]
使用问题，可以找到Check the image first出现的代码位置，找到代码逻辑，根据提示应该和image质量相关。

**Comment by livingbody** [comment]
请提供更详细的信息，这个看不出来。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
