### ISSUE TITLE
paddleOCR编译成dll动态库，LoadLibrary加载失败 

### ISSUE THREAD

**Issue by h4444433333** [PaddlePaddle/PaddleOCR#10242]
环境：win10 vs2019 cmake3.14 standard 11 使用的cpu_avx_mkl 的inference
使用paddleocr的代码生成了dll 但是加载的时候失败，显示加载成功，然后立即卸载了。具体定位代码，发现注释掉ocr_det.cpp和ocr_rec.cpp还有orc_cls.cpp中的paddle_infer::Config config这行，加载dll就不失败了，

错误信息：
程 0x7590 已退出，返回值为 0 (0x0)。

“CMakeProject2.exe”(Win32): 已加载“C:\Users\1\source\repos\CMakeProject2\CMakeProject2\ppocr.dll”。模块已生成，不包含符号。

“CMakeProject2.exe”(Win32): 已卸载“C:\Users\1\source\repos\CMakeProject2\CMakeProject2\ppocr.dll”

0x0000000000000000 处(位于 CMakeProject2.exe 中)引发的异常: 0xC0000005: 执行位置 0x0000000000000000 时发生访问冲突。****

补充一下，这个paddle_infer::Config config的定义代码是using Config =paddle::AnalysisConfig

**Comment by h4444433333** [comment]
已解决

**Comment by smileformylove** [comment]
请问一下是怎么解决的
