### ISSUE TITLE
No module named 'tools.infer' 

### ISSUE THREAD

**Issue by zzdts** [PaddlePaddle/PaddleOCR#1024]

**Comment by grasswolfs** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md

**Comment by littletomatodonkey** [comment]
你是按照哪个教程走，遇到了这个问题呢？好歹说下报错的步骤啊

**Comment by zzdts** [comment]
ubuntu20.04  
conda 4.9.0  python3.7.7  
按照 [https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/installation_en.md](url) 这个教程，但是没有使用步骤1中的docker环境。  

这个错误很奇怪， 看了你们在这上面的讨论应该是解决了这个问题的，下载的源码中也有对应的commit id但是用了release分支和dev分支都还是一样。 
明明tools包就和引用的文件一个目录，为什么就不能导入？

**Comment by littletomatodonkey** [comment]
你是运行了哪个命令报了上面的错误？

**Comment by zzdts** [comment]
直接clone 包后 运行github上的sample时出现的。
现在发现直接使用python xx.py  运行程序没有问题，使用pdb xx.py   又出现这个问题:
`-> import studiowork
(Pdb)
ModuleNotFoundError: No module named 'tools.infer'
`

**Comment by ATM006** [comment]
请问这个问题还有最新进展么！待续。。。

**Comment by helindemeng** [comment]
自己写的代码中，存在名称为tools的包，导致paddleocr调用其本身的tools方法时，路径查询到我们自己写的tools了，所以把我们自己写的tools报名改一下即可。

**Comment by milkliker** [comment]
@littletomatodonkey 
这个问题主要还是paddle代码的tools没有绝对引用带来的问题。
建议把paddle代码里
`import tools...`
都改为
`import paddleocr.tools...`
避免与开发者自己的tools冲突

**Comment by lvguangtao** [comment]
@milkliker 我应该去哪个脚本里修改呢

**Comment by sallenhandong** [comment]
> 自己写的代码中，存在名称为tools的包，导致paddleocr调用其本身的tools方法时，路径查询到我们自己写的tools了，所以把我们自己写的tools包名改一下即可。

yes,it works

**Comment by jimmyflycv** [comment]
> 

tried but still the error exists.

**Comment by stevenong99** [comment]
For those who don't understand Chinese, the above conversation essentially says that this problem is caused by conflicting package names, namely the tools package. I managed to solve this problem by changing the paddleocr.py file like so:

Original:
![image](https://user-images.githubusercontent.com/49690818/164584646-ff28a0cf-dab6-4906-97fb-7b852cb764ba.png)
Changed:
![image](https://user-images.githubusercontent.com/49690818/164585191-2e7c931a-5537-4fe3-bc28-f5d25fa1f6d7.png)

The reason I faced this issue is due to having another package called tools installed inside my pip site-packages (this tools package comes from installing another package called detectron2). So in order to fix the issue, I had to change those 3 lines such that they refer to the correct tools package.

Additional information:
I've managed to get this package running in a machine with the specs:
OS Version: Ubuntu 16.04
CUDA Version : 10.2
cuDNN Version: 7.6.5.32
Python Version: 3.6.12

**Comment by kargaranamir** [comment]
It's a bug! Why hasn't anyone fixed it yet? You will also find the solution [here](https://github.com/PaddlePaddle/PaddleOCR/issues/1024#issuecomment-1105946934)!

**Comment by SakhnevichKirill** [comment]
I fixed the error, I had the "tools" package installed. As soon as I deleted it, everything worked.

```
python -m pip uninstall tools
```

**Comment by kargaranamir** [comment]
> I fixed the error, I had the "tools" package installed. As soon as I deleted it, everything worked.
> 
> ```
> python -m pip uninstall tools
> ```

It's not a fix :))

**Comment by giriannamalai** [comment]
Faced issue, due to the **tools** name is common.

While searching site package, figured 'tools', a separate package installed.
`>>> import tools
>>> print(tools.__file__)
`
Go to the location, temporarily rename the folder to something else, then exit the REPL.
Now it is importing successfully.



Always create separate env for installing packages to avoid conflicts.

**Comment by kargaranamir** [comment]
> Faced issue, due to the **tools** name is common.
> ...

It's not a fix :))

It's just this quote that fixes it:
https://github.com/PaddlePaddle/PaddleOCR/issues/1024#issuecomment-1105946934

**Comment by logan-markewich** [comment]
6 months later and still not fixed :(

**Comment by therahulparmar** [comment]
This issue needs to be resolved asap!

**Comment by xuri422** [comment]
> 2 years later and still not fixed :(

This is a very very serious bug? Why not resovled in 2023?

**Comment by shiyutang** [comment]
Can you guys try if this solved your issue? 
https://github.com/PaddlePaddle/PaddleOCR/pull/10502

@xuri422 @therahulparmar @logan-markewich

**Comment by fun-huan** [comment]
> @littletomatodonkey 这个问题主要还是paddle代码的tools没有绝对引用带来的问题。 建议把paddle代码里 `import tools...` 都改为 `import paddleocr.tools...` 避免与开发者自己的tools冲突

的确是这个原因导致的  ，thanks

**Comment by CheungZeeCn** [comment]
change sys.path.append => sys.path.insert...  It works.

sigh for the side effect:
after you import paddleocr， there will be lot of new path in your sys.path...

**Comment by aditya11ad** [comment]
> For those who don't understand Chinese, the above conversation essentially says that this problem is caused by conflicting package names, namely the tools package. I managed to solve this problem by changing the paddleocr.py file like so:
> 
> Original: ![image](https://user-images.githubusercontent.com/49690818/164584646-ff28a0cf-dab6-4906-97fb-7b852cb764ba.png) Changed: ![image](https://user-images.githubusercontent.com/49690818/164585191-2e7c931a-5537-4fe3-bc28-f5d25fa1f6d7.png)
> 
> The reason I faced this issue is due to having another package called tools installed inside my pip site-packages (this tools package comes from installing another package called detectron2). So in order to fix the issue, I had to change those 3 lines such that they refer to the correct tools package.
> 
> Additional information: I've managed to get this package running in a machine with the specs: OS Version: Ubuntu 16.04 CUDA Version : 10.2 cuDNN Version: 7.6.5.32 Python Version: 3.6.12



After installing detectron2 , I also got the same error.
So I making the above changes in **paddleocr.py**, 
then running below code :
`>>> from paddleocr import PaddleOCR`
Now I am getting this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 33, in <module>
    tools = importlib.import_module('.', 'paddleocr.tools')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'paddleocr.tools'; 'paddleocr' is not a package

```

**Comment by SLuyazhou** [comment]
besides, advice to check your python sys path which usualy can be set by the .pth file. Here are the steps to check:
1. type "which python", got your python path. eg. /Users/{username}/miniconda3/envs/{env name}/bin/python 
2. type "cd  /Users/{username}/miniconda3/envs/{env name}/lib/python{Version}/site-packages, and type "ls |grep .pth",you may get some filename.then  use code or vim,check these files to make sure that there is nothing conflict to tools.

I have soleved the problem through delete "GPT-SoVITS" path in users.pth
