### ISSUE TITLE
模型微调进行训练，报错：if 'bbox' in cells[bbox_idx] and len(cells[bbox_idx]['tokens']) > 0: IndexError: list index out of range

### ISSUE THREAD

**Issue by mk25499** [PaddlePaddle/PaddleOCR#10243]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/109774772/d6c1ba75-b858-496a-a38f-3fc1408f4e0c)

**Comment by shiyutang** [comment]
看上去bbox_idx越界导致索引出错，请问你是运行的什么命令呢？

**Comment by livingbody** [comment]
具体情况需要检查数据集，可以多点的。以前用过。

**Comment by mk25499** [comment]
> 看上去bbox_idx越界导致索引出错，请问你是运行的什么命令呢？
python3 tools/train.py -c configs/table/SLANet_ch.yml 是对表格识别模型进行微调，我想先少点数据集测试训练能否成功，结果报索引的问题

**Comment by mk25499** [comment]
> 看上去bbox_idx越界导致索引出错，请问你是运行的什么命令呢？

python3 tools/train.py -c configs/table/SLANet_ch.yml 是对表格识别模型进行微调，我想先少点数据集测试训练能否成功，结果报索引的问题

**Comment by rabbit123348** [comment]
你好，请问你这个问题解决了吗？我现在也遇到这个问题了，不知道怎么解决

**Comment by dc6273632** [comment]
同问，我也遇到了这个问题

**Comment by XiaokangLei** [comment]
我也遇到这个问题了

**Comment by Bishow-99** [comment]
Does anyone solve this error, even, I am facing the same issue

**Comment by UserWangZz** [comment]
可能是box type设置不对
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
