### ISSUE TITLE
关于多卡推理

### ISSUE THREAD

**Issue by minboo** [PaddlePaddle/PaddleOCR#10248]
是这样的，我的服务器上有四张T4卡，但是使用paddleocr推理时只用了0号卡，其余几张卡都是空闲状态，环境变量设置了`export CUDA_VISIBLE_DEVICES=0,1,2,3`，请问要怎样才能利用所用GPU？麻烦大佬解答一下。

**Comment by livingbody** [comment]
推力一般用不到。不过可以试试多卡训练的方式。比如：

```
python3 -m paddle.distributed.launch --ips="xx.xx.xx.xx,xx.xx.xx.xx" --gpus '0,1,2,3' tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained
```

[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/detection.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/detection.md)

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by God-song** [comment]
linux怎么查看显卡是那个程序和用户在使用呢
