### ISSUE TITLE
没有训练过程，没写出像是写出训练到 epoch 多少这样，eval 也确实没有数字，推测可能没训练到

### ISSUE THREAD

**Issue by loading2022** [PaddlePaddle/PaddleOCR#10255]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：cuda11.6
- 版本号/Version：Paddle： 2.4.2 PaddleOCR：2.6.3.1 
 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/rec/rec_mv3_none_bilstm_ctc.yml
- 完整报错/Complete Error Message：
没有训练过程，没写出像是写出训练到 epoch 多少这样，eval 也确实没有数字，推测可能没训练到?
<img width="945" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/0d970edd-9880-4154-adf8-54b4629dc94c">

**Comment by livingbody** [comment]
这个可以在训练文件中改，或者配置中改输出。直接改源文件即可。

**Comment by loading2022** [comment]
@livingbody 请问有具体的改法，或是有什么资料可以参考吗

**Comment by loading2022** [comment]
已解决
