### ISSUE TITLE
training a new model

### ISSUE THREAD

**Issue by ganapati3** [PaddlePaddle/PaddleOCR#10252]
i already trained a model for detection and recognition but its output time is more so i need to train a lightweight model for det and rec english version can you please tell me how to do it? i already seen about that models but there is no pretrained models in light weight version

**Comment by shiyutang** [comment]
which det and rec model do you train? Did you tried the PP-OCRv3 model?

**Comment by ganapati3** [comment]
> which det and rec model do you train? Did you tried the PP-OCRv3 model?

i want to train these two model en_PP-OCRv3_rec_slim,en_PP-OCRv3_det_slim
