### ISSUE TITLE
通过源码 pip install . 安装 包失败

### ISSUE THREAD

**Issue by sjy3** [PaddlePaddle/PaddleOCR#10258]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

由于pip 当前提供的最新版本为：paddleocr-2.6.1.3,
在运行时会导致：ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
看到[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 已经解决了该问题：https://github.com/PaddlePaddle/PaddleOCR/pull/10052/commits/32fe3c9b07f125b0c2e47d6a47776d128ee6847b
但是 pip包没有更新，于是打算通过源码安装 padleocr,导致失败。

- 系统环境/System Environment：MAC
- 版本号/Version：Paddle：  PaddleOCR： v2.6.0 release/2.6分支
- 问题相关组件/Related components：
- 运行指令/Command Code：pip install .
- 完整报错/Complete Error Message：
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/shijinyu7/PycharmProjects/PaddleOCR
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: -11
  ╰─> [0 lines of output]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by shiyutang** [comment]
你好，我在本地尝试
```pip install -e .```会报错
```ModuleNotFoundError: No module named 'Polygon'```
需要进入到目录，安装：
```
pip3 install -r requirements.txt
```

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by sjy3** [comment]
@shiyutang 非常感谢，上述方案解决了我的问题。
