### ISSUE TITLE
PaddleOCR not use GPU although all checks pass

### ISSUE THREAD

**Issue by Sayaka91** [PaddlePaddle/PaddleOCR#10266]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：EC2 Linux
- 版本号/Version：PaddlePaddle-GPU: 2.4.2.cu117：  PaddleOCR：2.6.1.3 问题相关组件/Related components：Torch 1.13.1.cu117
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
PaddleOCR not use GPU
I checked `paddle.utils.run_check()` and `paddle.fluid.install_check.run_check()`,
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49243283/a1069b3f-b70c-4dd6-b4ae-0d3ef4ba7180)
I checked `torch.cuda.is_available()` return `True`. All model using torch used GPU but just paddleOCR did'nt use although I added the parameter` use_gpu = True`

**Comment by GreatV** [comment]
Could you provide the script or code you used to run paddleocr so we could reproduce it?

**Comment by livingbody** [comment]
give me a picture.

**Comment by Sayaka91** [comment]
@GreatV @livingbody 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49243283/a3df3611-13bb-4639-a79c-046db65d900a)
I checked use_gpu = True, but the inference time on GPU isn't faster on CPU (~0.6s)

**Comment by GreatV** [comment]
Hi @Sayaka91, `use_gpu=True` has better performance for batch prediction.

**Comment by Sayaka91** [comment]
@GreatV If torch.cuda.is_available = True, GPU is turn on, so the inference time should be faster than processing on CPU, but I didn't got it

**Comment by UserWangZz** [comment]
> @GreatV If torch.cuda.is_available = True, GPU is turn on, so the inference time should be faster than processing on CPU, but I didn't got it

You need to use more pictures to test because the system will take time to warm up.
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
