### ISSUE TITLE
请教：OCR推理前，如何指定GPU？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleOCR#1026]
请教：OCR推理前，如何指定GPU？

**Comment by littletomatodonkey** [comment]
可以使用下面的方式指定gpu id
`export CUDA_VISIBLE_DEVICES=0`

**Comment by 670133189** [comment]
> 可以使用下面的方式指定gpu id
> `export CUDA_VISIBLE_DEVICES=0`

明白。另外如何在python代码里面指定？

**Comment by WenmuZhou** [comment]
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "2"
