### ISSUE TITLE
关键信息抽取：训练re 发票数据，报错如下

### ISSUE THREAD

**Issue by mppsk0** [PaddlePaddle/PaddleOCR#10272]
![12](https://github.com/PaddlePaddle/PaddleOCR/assets/13795045/59ff072c-1443-4557-ba4f-10d03e15f80a)
![13](https://github.com/PaddlePaddle/PaddleOCR/assets/13795045/3375a097-e5ad-4846-96a5-a6ff3e856a0e)
估计是标注格式中的错误，但不知如何修改

**Comment by livingbody** [comment]
我认真看了你的数据集，是格式问题，具体如下：
```
" 图像文件名                    json.dumps编码的图像标注信息"
ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]
```

参考文档： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/ocr_datasets.md

**Comment by shiyutang** [comment]
需要进一步说明是哪里有格式错误，怎么修改。

**Comment by livingbody** [comment]
你好，你的数据格式不对，需要一个图片一行记录。图片名称，标注信息等的
" 图像文件名                    json.dumps编码的图像标注信息"
ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]

而你的数据格式里有linking，id，label，other等等，需要进行转换，如果需要可以提出帮你一起看。

**Comment by shiyutang** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md#12-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86
KIE的数据集可以检查下下面的内容：
注意： 文本文件中默认请将图片路径和图片标签用 \t 分割，如用其他方式分割将造成训练报错。

**Comment by livingbody** [comment]
你好，请给出训练脚本，我看看是哪一步出的问题，我没遇到这个，复现不出来。

**Comment by shiyutang** [comment]
可以给出修改的数据txt，我们复现一下

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
