### ISSUE TITLE
PPOCRLabel 表格标注

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10274]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu 18
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PPOCRlabel  对于跨行 文本标注 bbox 的坐标怎么是分开的标注的，不是应该整个标注作为cell的坐标？

单项金额虽不重大但单独计提 和 坏账准备的其他应收款 本身就属于一个cell，而是用文本检测的坐标的作为cell，为什么不去合并，这不合并应该有问题啊

, {"tokens": ["单", "项", "金", "额", "虽", "不", "重", "大", "但", "单", "独", "计", "提"], "bbox": [[10, 157], [167, 157], [167, 172], [10, 172]]}, {"tokens": ["坏", "账", "准", "备", "的", "其", "他", "应", "收", "款"], "bbox": [[9, 172], [130, 172], [130, 188], [9, 188]]}

“”“”<html><body><table><tbody><tr><td rowspan=\"4\"></td><td colspan=\"5\"></td></tr><tr><td colspan=\"2\"></td><td colspan=\"2\"></td><td></td></tr><tr><td></td><td></td><td></td><td></td><td>期初余额</td></tr><tr><td>种类</td><td>账面余额</td><td>坏账准备</td><td>账面价值</td><td>金额</td></tr><tr><td>比例（%）</td><td>金额</td><td>计提比例（%）</td><td>账龄分析法组合</td><td>6,665,779,301,76</td><td>100.00</td></tr><tr><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291,30</td><td>关联单位组合</td><td>组合小计</td><td>6.665,779,301.76</td></tr><tr><td>100.00</td><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291.30</td><td>单项金额虽不重大但单独计提</td><td>坏账准备的其他应收款</td></tr><tr><td>合计</td><td>6,665,779,301.76</td><td>100.00</td><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291.30</td></tr></tbody></table></body></html>“”“”
![5004](https://github.com/PaddlePaddle/PaddleOCR/assets/32585434/921e0f6f-117e-41eb-949d-35f5f1703802)

如果不自动标注，完全手动标注，需要怎么标注呢，标注哪些内容？

**Comment by gl94** [comment]
html标注在excel里面改，是从excel导出的，界面上是标注的单元格检测分支的

**Comment by gl94** [comment]
你如果要自己标注，也可以试试从excel导出

**Comment by gl94** [comment]
或者你懂html的语法，也可以自己写，类似这样：
`html = """
<html>
  <body>
    <table border="1">
      <tr>
        <td>aa</td>
        <td>bb</td>
        <td>cc</td>
        <td>dd</td>
        <td>ee</td>
        <td>ff</td>
      </tr>
    </table>
  </body>
</html>
"""`
保存成.html可以可视化查看

**Comment by gl94** [comment]
"""
<html>
  <body>
    <table border="1">
      <tbody>
        <tr>
          <td rowspan="2">类别</td>
          <td colspan="3">期末余额</td>
          <td colspan="3">期初余额</td>
        </tr>
        <tr>
          <td>账面余额</td>
          <td>坏账准备</td>
          <td>账面价值</td>
          <td>账面余额</td>
          <td>坏账准备</td>
          <td>账面价值</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
"""
类似这样

**Comment by gl94** [comment]
- _**<html>
-   <body>
-     <table border="1">
-       <tbody>
-         <tr>
-           <td rowspan="2">类别</td>
-           <td colspan="3">期末余额</td>
-           <td colspan="3">期初余额</td>
-         </tr>
-         <tr>
-           <td>账面余额</td>
-           <td>坏账准备</td>
-           <td>账面价值</td>
-           <td>账面余额</td>
-           <td>坏账准备</td>
-           <td>账面价值</td>
-         </tr>
-       </tbody>
-     </table>
-   </body>
- </html>**_

**Comment by gl94** [comment]
![图片](https://github.com/PaddlePaddle/PaddleOCR/assets/26252750/ec0496e6-cc28-42eb-8070-1df68784325a)

**Comment by gl94** [comment]
我最好奇的是怎么标注“”<th><\th>“”<th><\th>
