### ISSUE TITLE
How do I train on top of the default model with negative case for a single character?

### ISSUE THREAD

**Issue by 04dac8af8e5b57b7** [PaddlePaddle/PaddleOCR#10276]
Hello folks! 

I'm running an experiment of PaddleOCR on car plates and it works quite well. However there's a common case where the default model (PP-OCRv3) wrongly recognize the letter E like below: 

<img src="https://github.com/PaddlePaddle/PaddleOCR/assets/27521007/20970eda-29b9-4108-bf1b-a7bc6779eac7" width="200" />

... returns `ECGM39K`

<img src="https://github.com/PaddlePaddle/PaddleOCR/assets/27521007/494738c6-d664-46d3-a956-bccaa5a2b4e3" width="200" />

... returns `EDXP02S`

What would be the best way for me to train (on top of the default model) that those small vertical dots are not an "E" letter?

**Comment by shiyutang** [comment]
It is related to the detection box.

**Comment by livingbody** [comment]
- 1. Label detection  box
- 2.train your own detection model.

**Comment by shiyutang** [comment]
It seems that your detection box is slightly wrong, it is best to exclude the left-most part. And you may hand labeled some more accurate detection boxes and fine-tune the detection model.

**Comment by 04dac8af8e5b57b7** [comment]
Thank you for looking at the issue and the suggestion! I will try to train my own detection model. Cheers.
