### ISSUE TITLE
C++ inference for PGnet

### ISSUE THREAD

**Issue by Daisy5296** [PaddlePaddle/PaddleOCR#10280]
Hi is there any plan to develop C++ deployment code for the PGnet? It would be very nice to have an e2e algorithm that can be deployed directly.

**Comment by shiyutang** [comment]
Thank you for your attention, we may add it as a task in our activity: https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
