### ISSUE TITLE
检测算法的性能能不能进行优化

### ISSUE THREAD

**Issue by ocrhei** [PaddlePaddle/PaddleOCR#10281]
比如FCENet复现的结果是85.2，跟论文中差了0.3个点，如何跟论文中的结果保持一致呢。

**Comment by shiyutang** [comment]
可以参考论文复现指南看哪里没有对齐：https://github.com/PaddlePaddle/models/blob/release%2F2.4/docs/lwfx/ArticleReproduction_CV.md。
或者调整学习策略，使用更多的迭代轮数。
