### ISSUE TITLE
RCTW17下载链接不可用

### ISSUE THREAD

**Issue by GarrettLee** [PaddlePaddle/PaddleOCR#1028]
https://github.com/PaddlePaddle/PaddleOCR/blob/e463dc98dd14100d3b6fe7c7bc2344fa168ec2bb/doc/doc_ch/datasets.md

这个文档地下的RCTW17数据集不能访问了

**Comment by MissPenguin** [comment]
确实打不开了，这个是rctw的官网，可以搜一下有没有别的下载资源，或者过段时间再试试，可能官方就修复了。

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
