### ISSUE TITLE
Illegal instruction Error on Docker Image

### ISSUE THREAD

**Issue by fxhuhn** [PaddlePaddle/PaddleOCR#10286]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Docker on Synology NAS (paddlepaddle/paddle:2.5.0)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： import paddle  
- 完整报错/Complete Error Message：Illegal instruction (core dumped) 

I'm trying to run paddleocr on my Synology, but i still running into an error. 
Does paddle don't work in a Docker environment on a SYNOLOGY NAS?

**Comment by GreatV** [comment]
To run paddle in Synology NAS, you may need to [build paddle from scratch](https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/linux-compile_en.html).

**Comment by fxhuhn** [comment]
Phew, ok that's a little more time consuming in that case. Thanks, you saved my weekend!

**Comment by shiyutang** [comment]
You are welcomed to participate in our activity：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
