### ISSUE TITLE
微调卡证检测模型，最后得到的模型检测不完整

### ISSUE THREAD

**Issue by PassionateBro** [PaddlePaddle/PaddleOCR#10282]
想请问一下，我再使用ppv3微调检测模型，针对只检测我需要的字段，其他区域都能够表现良好，但在驾驶证和行驶证的日期区域字段中，总会出现区域检测一半的情况，如图
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/57137355/9410ab49-354a-4e9a-b4ca-99fc51b08852)

这个是需要补充类似场景的训练数据吗？

**Comment by PassionateBro** [comment]
关于字符重叠的问题我已经解决了，还想请教一下，如果图片画面中行驶证的两页都出现了，我只想检测第一页的内容，第二页不想检测出内容造成我后续处理的干扰，请问有啥处理方式吗？ 我在训练数据中已经穿插一部分这种场景的数据，但仍然会有检测到我关注的字段以外的内容

**Comment by PassionateBro** [comment]
> 可能是字符重叠导致，建议可以增加模型对这一类的关注度，并且增加这类数据扩充。

关于字符重叠的问题我已经解决了，还想请教一下，如果图片画面中行驶证的两页都出现了，我只想检测第一页的内容，第二页不想检测出内容造成我后续处理的干扰，请问有啥处理方式吗？ 我在训练数据中已经穿插一部分这种场景的数据，但仍然会有检测到我关注的字段以外的内容

**Comment by shiyutang** [comment]
能不能训练一个方式对第一页的进行标注，并训练一个分割模型，对第一页检测的结果进行屏蔽？

**Comment by shiyutang** [comment]
是的，检测模型任务就是处理所有文本的检测。

**Comment by CasonTsai** [comment]
@PassionateBro 请问大佬，微调驾驶证，只需要标注想要检测的字段就行么，像register date这些可以不用标注么
