### ISSUE TITLE
测试推理模型出错

### ISSUE THREAD

**Issue by poormanfwh** [PaddlePaddle/PaddleOCR#1029]
OS： Ubuntu 18.04
HW:2CPU 8GB
当运行如下命令时出错。

ubuntu@ip-10-53-0-220:~/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False

错误如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1603850348 (unix time) try "date -d @1603850348" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2702 (TID 0x7faec2237740) from PID 0 ***]

Segmentation fault (core dumped)

麻烦尽快看一下什么问题。谢谢。

**Comment by poormanfwh** [comment]
我试过轻量级模型，也是同样的错误，同时我看相关问题的case查询这个也是支持CPU的。
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
W1028 02:41:08.590791  3716 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W1028 02:41:08.591814  3716 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

**Comment by poormanfwh** [comment]
我换成了4CPU 16GB。之后出这个错。
ubuntu@ip-10-53-0-220:~/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False
Intel MKL function load error: cpu specific dynamic library is not loaded.

是不是必须得用GPU才能运行模型？

**Comment by LDOUBLEV** [comment]
提供下你的paddle版本，
你的paddle是否安装成功了? 运行下面代码试一下
```
import paddle.fluid
paddle.fluid.install_check.run_check()
```

**Comment by poormanfwh** [comment]
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
W1028 05:56:23.732740  1893 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W1028 05:56:23.733858  1893 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

**Comment by poormanfwh** [comment]
以下为最新的错误：
ubuntu@ip-10-53-0-220:~/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1603864651 (unix time) try "date -d @1603864651" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1915 (TID 0x7f542f748740) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by poormanfwh** [comment]
我安装了paddlepaddle的1.8.5的版本后，就只报错Segmentation fault (core dumped)
ubuntu@ip-10-53-0-220:~/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False

Segmentation fault (core dumped)

**Comment by BillyLearn** [comment]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1603957066 (unix time) try "date -d @1603957066" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 24388 (TID 0x7f4339a3f740) from PID 8 ***]

只使用python 运行paddleOCR 是没问题的。
c++ 调用python 的 easyOCR 也是没有问题的。
c++ 调用python的 paddleOCR 就有上面的问题？

**Comment by poormanfwh** [comment]
我不太明白你的意思。我是直接按照文档操作的。通过python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/" --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False


我同时测过Paddle的docker image ,里面是可以输出结果。
但我希望直接在现有ubuntu环境中使用，麻烦看一下怎么解决。

**Comment by poormanfwh** [comment]
我是直接在ubuntu 18.04的环境下直接运行的。

**Comment by qiuming-93** [comment]
我也遇到了类似的问题，我是直接用pip命令安装的paddleocr的库，版本是1.1.1，paddlepaddle和paddlepaddle-gpu版本都是1.8.5，在win下（无GPU）可正常使用CPU进行推理，在centos下使用GPU可以正常推理，使用CPU就报错Intel MKL function load error: cpu specific dynamic library is not loaded.然后程序就直接崩溃了。
fluid.install_check.run_check()显示paddle环境正常

**Comment by qiuming-93** [comment]
@poormanfwh 试试conda install nomkl，我装上这个就好了

**Comment by DaguDuiyuan** [comment]
ubuntu18.04
paddlepaddle-gpu 2.0.0rc0
W1214 16:24:39.048400 28292 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.2
W1214 16:24:39.049770 28292 device_context.cc:346] device: 0, cuDNN Version: 8.0.

我使用gpu跑也是报一样的错误

**Comment by DaguDuiyuan** [comment]
cudnn降级到7.6.5就不报错了- -

**Comment by DKZHANG1982** [comment]
> @poormanfwh 试试conda install nomkl，我装上这个就好了

谢谢！你解决了我的问题，同样的问题发生在CENTOS 7.3/PYTHON3.7.1/ANACONDA环境/PaddleOCR1,0,0/PaddlePaddle1.8.5在使用hubserving进行部署时（运行hub serving未发生错误），收到post后进行预测的瞬间报错：Intel MKL function load error: cpu specific dynamic library is not loaded.

**Comment by chapmancpp** [comment]
有解决方案吗？？paddle=2.0.1，paddleOCR=2.0.1
predict_system.py 使用cpu的时候报 Intel MKL function load error: cpu specific dynamic library is not loaded.

**Comment by Z-yq** [comment]
对于python3.7.x的版本测试  python 3.7.4 以下版本测试会报错，而 python 3.7.9 测试OK

**Comment by chros425** [comment]
请问这个问题，最新的版本有修复吗，我们经常碰到，挺高频，Python3.6.4，ntel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz，用的paddle2.0-rc1版，机器上有GPU nvidia V100，但是用的是CPU的多进程来处理多页文档的

**Comment by sunchengrong** [comment]
也遇到了这个问题

**Comment by toraji1** [comment]
遇到了一样的问题

**Comment by chenzhaoqiJM** [comment]
好像是因为由于GPU个数造成的问题，官方大多数模型是在8卡GPU上训练的
我把配置文件中 EvalReader:下的
  batch_size设置为1就好了（除以八）

**Comment by mengxiang** [comment]
> 好像是因为由于GPU个数造成的问题，官方大多数模型是在8卡GPU上训练的
> 我把配置文件中 EvalReader:下的
> batch_size设置为1就好了（除以八）

你是在哪个文件中修改的？

**Comment by MissPenguin** [comment]
> > 好像是因为由于GPU个数造成的问题，官方大多数模型是在8卡GPU上训练的
> > 我把配置文件中 EvalReader:下的
> > batch_size设置为1就好了（除以八）
> 
> 你是在哪个文件中修改的？

batch_size在yml文件中

**Comment by QQ39272490** [comment]
你们的问题解决了吗？我是jetson nano推理时间久了也有这问题
![infer](https://user-images.githubusercontent.com/2766645/127622491-93382668-99e4-4daa-8b18-6806b5540e21.jpg)

**Comment by PhilCuriosity** [comment]
> 你们的问题解决了吗？我是jetson nano推理时间久了也有这问题
> ![infer](https://user-images.githubusercontent.com/2766645/127622491-93382668-99e4-4daa-8b18-6806b5540e21.jpg)

我在jetson上模型初始化时，也遇到了这个问题。在Win10下paddle2.1.1 训练也有这个问题

**Comment by gl94** [comment]
> @poormanfwh 试试conda install nomkl，我装上这个就好了

大佬 nb！
