### ISSUE TITLE
表格识别模型微调后，新模型进行表格识别时报错：IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by mk25499** [PaddlePaddle/PaddleOCR#10297]
我在表格识别模型基础上进行了微调，然后拿来进行表格识别报错！

**Comment by shiyutang** [comment]
你好，给出指令和具体报错栈信息我们看看呢？

**Comment by mk25499** [comment]
> 你好，给出指令和具体报错栈信息我们看看呢？

**Comment by mk25499** [comment]
> 你好，给出指令和具体报错栈信息我们看看呢？

指令是：paddleocr --image_dir=pages_test/1.png --type=structure --layout=false --table_model_dir=inference/SLANet_ch_test/
报错：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/109774772/781ab76d-8adf-4bad-b678-6ce8806f0bec)

**Comment by steptian** [comment]
似乎是因为没有正确导出模型参数吧

**Comment by ATP-BME** [comment]
我也遇到了相同的问题
& D:/apps/miniconda3/envs/GNN/python.exe predict_system.py --image_dir='F:/LM/知识注入/rescale/42.药理学 第九版 杨宝峰 2018年（重制快搜版）_部分2.pdf' --det_model_dir=inference/ch_PP-OCRv4_det_infer --rec_model_dir=inference/ch_PP-OCRv4_rec_infer --rec_char_dict_path="../ppocr/utils/ppocr_keys_v1.txt" --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_cdla_infer --layout_dict_path="../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt" --vis_font_path=../doc/fonts/simfang.ttf --recovery=True --output=../output/
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/251b6f81-3ffc-43aa-99f7-984d037f734b)

**Comment by rudra0713** [comment]
Hi, has this issue been resolved? 
I am trying the following command:
`
python3 table/predict_table.py  --image_dir=/scratch/rrs99/PaddleOCR/ppstructure/page_4.jpg \
                                --det_limit_side_len=736 \
                                --rec_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_rec_infer \
                                --table_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_structure_infer \
                                --det_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_det_infer \
                                --rec_char_dict_path=/scratch/rrs99/PaddleOCR/ppocr/utils/dict/table_dict.txt \
                                --table_char_dict_path=/scratch/rrs99/PaddleOCR/ppocr/utils/dict/table_structure_dict.txt \
                                --det_limit_type=min \
                                --output=/scratch/rrs99/PaddleOCR/ppstructure/output/table
`
The error I am getting:
`
Traceback (most recent call last):
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 241, in <module>
    main(args)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 189, in main
    pred_res, _ = table_sys(img)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 109, in __call__
    pred_html = self.match(structure_res, dt_boxes, rec_res)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/matcher.py", line 65, in __call__
    dt_boxes, rec_res = self._filter_ocr_result(pred_bboxes, dt_boxes, rec_res)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/matcher.py", line 194, in _filter_ocr_result
    y1 = pred_bboxes[:, 1::2].min()
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
