### ISSUE TITLE
How to serve two same category model using paddleHub.

### ISSUE THREAD

**Issue by Shadow-Alex** [PaddlePaddle/PaddleOCR#10296]
Hi, I'm trying to serve the CDLA(Chinese) layout analysis model and the English one at the same time using paddleHub, is it possible?
I'm able to get them up and running separately. Can I serve two same category models using paddleHub? If not, whats the right way out?

right now I'm trying to install them separately and start them using a `config.json` like this :
```json
{
    "modules_info": {
        "structure_layout": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": true
            },
            "predict_args": {
            }
        },
        "structure_layout_cdla": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": true
            },
            "predict_args": {
            }
        }
    },
    "port": 8871,
    "use_multiprocess": false,
    "workers": 2
}
```

**Comment by Shadow-Alex** [comment]
Well it seems to work from the command line out, I see two kinds of post are returned in code 200, but I'm actually getting one model result.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/46802674/1b98556c-17d7-457d-b290-21bdb447dba4)

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
