### ISSUE TITLE
PaddleLabel可以自定义自己的模型进行半自动标注吗

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#10301]

**Comment by luoyq6** [comment]
@tink2123

**Comment by Gmgge** [comment]
可以的，目前来说有两种方法可以实现该操作
1.不修改代码，替换默认路径下的模型文件 默认路径为根路径在("~/.paddleocr/whl/") 可以替换该路径下相应任务的模型文件，例如windows上该目录为 C:\\Users\\{你的用户名}\\.paddleocr\\whl
2.修改代码，在paddleocr.py中，类class PaddleOCR(predict_system.TextSystem)定义中，设定对于目录文件，例如设置params.det_model_dir=r"you_model_path"

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
