### ISSUE TITLE
是否可以将英文的表格和中文的表格数据合一起训练，字典就用中文的？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10304]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

@tink2123 @bingooo @ZeyuChen

**Comment by raoyutian** [comment]
可以的。表格识别，首先是识别表格，然后再根据切割的小单元格图片进行文字识别。
前后关联性不是很大。

**Comment by livingbody** [comment]
没问题
- 中文字符本身就傲寒了英文字符
-  表格结构跟字符中英文没关系

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
