### ISSUE TITLE
这种必须手工标注才行吧？没有模拟生成方法把

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10305]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

这种必须手工标注才行吧？没有模拟生成方法把
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/2a22be87-839f-4b65-b31c-25076dc88eb2)

**Comment by livingbody** [comment]
你是要搞检测模型还是识别模型？
不是很清楚你的需求。

**Comment by nissansz** [comment]
通用识别，全字符集

**Comment by livingbody** [comment]
## 可以看看PaddleOCR自带的工具

Style-Text数据合成工具是基于百度和华科合作研发的文本编辑算法《Editing Text in the Wild》https://arxiv.org/abs/1908.03047

不同于常用的基于GAN的数据合成工具，Style-Text主要框架包括：1.文本前景风格迁移模块 2.背景抽取模块 3.融合模块。经过这样三步，就可以迅速实现图像文本风格迁移。下图是一些该数据合成工具效果图。

PaddleOCR/StyleText/README_ch.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/StyleText/README_ch.md

**Comment by nissansz** [comment]
这个怎么改造成支持 日文等其他语种的字体

**Comment by shiyutang** [comment]
直接输入对应文字即可：
<img width="654" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/34859558/5af414a6-ece6-4e53-bed4-cb29b87535cb">

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by nissansz** [comment]
> 直接输入对应文字即可： <img alt="image" width="654" src="https://user-images.githubusercontent.com/34859558/252197615-5af414a6-ece6-4e53-bed4-cb29b87535cb.png">

日文不支持，没法生成，文档有提到，只支持3个语种，之前试过

**Comment by shiyutang** [comment]
看了下代码，需要 1. 提供日语字体的tff文件用于给定字符string生成文字（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/StyleText/fonts）；2. 训练TextGenerator用于给定在日文场景下的图像风格转换。（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/StyleText/arch/style_text_rec.py）

**Comment by nissansz** [comment]
日语字体tff文件， windows系统有。
训练TextGenerator，不知道怎么弄

**Comment by shiyutang** [comment]
训练代码没有给出，推断是使用GAN进行风格迁移，需要结合论文实现一下：https://arxiv.org/pdf/1908.03047.pdf

**Comment by nissansz** [comment]
完全不会。没有办法通用所有文字迁移吗

**Comment by shiyutang** [comment]
可以看看Textrender是否支持多语种：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8C%85%E8%A3%85%E7%94%9F%E4%BA%A7%E6%97%A5%E6%9C%9F%E8%AF%86%E5%88%AB.md#5-%E5%9F%BA%E4%BA%8E%E5%90%88%E6%88%90%E6%95%B0%E6%8D%AEfinetune

**Comment by shiyutang** [comment]
或者可以直接增加tff文件，看看现有风格迁移网络能不能适应日文。

**Comment by nissansz** [comment]
不能用的，以前试过，字符都不对了
