### ISSUE TITLE
识别区域重复？

### ISSUE THREAD

**Issue by P-PPPP** [PaddlePaddle/PaddleOCR#10306]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Windows 10 64bit 
- 版本号/Version：Paddle：2.4  PaddleOCR：2.0.1 问题相关组件/Related components：识别区域重复
- 运行指令/Command Code：`PaddleOCR(use_angle_cls=True, lang="ch").ocr(img_path, cls=True)`
- 完整报错/Complete Error Message：
出错的结果如下两行：
```
[[[1770.0, 770.0], [2380.0, 770.0], [2380.0, 875.0], [1770.0, 875.0]], ('序列号：2', 0.8737444877624512)]
[[[2343.0, 775.0], [3086.0, 775.0], [3086.0, 865.0], [2343.0, 865.0]], ('210990730262',0.9099360108375549)]
```
如结果所见，第一行识别结果区域在 `1770,770 - 2380,875` 之间，与此同时第二行识别位置在 `2343,775 - 3086,865` 之间，造成了在[2380,2343]这个范围内出现了字符重复，在识别结果上表现为第一行识别多了个2
我使用的模型是默认的中文模型

**Comment by shiyutang** [comment]
可以设置识别框的大小，减少膨胀，解答问题的开发者可以给出具体示例操作。

**Comment by P-PPPP** [comment]
感谢提示，我自己找到了修改方法，也为后面的兄弟必坑
只要设置`det_db_unclip_ratio`小一点就好，默认1.5
`ocr = PaddleOCR(use_angle_cls=True, lang="ch",det_db_unclip_ratio=1)`

**Comment by shiyutang** [comment]
很厉害👍 我们开启了issue解答活动欢迎参加 #10223
