### ISSUE TITLE
not find model file path ./inference/ch_ppocr_mobile_rec_infer//model

### ISSUE THREAD

**Issue by JackonLiu** [PaddlePaddle/PaddleOCR#1030]
执行此命令时
python tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_ppocr_mobile_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile
_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_cls_infer/" --use_angle_cls=True --use_space_char=True  --use_gpu=False
出现这个bug
2020-10-28 10:08:59,071-INFO: not find model file path ./inference/ch_ppocr_mobile_rec_infer//model
但是我下载的这个包里面并没有model和params

**Comment by BeyondYourself** [comment]
模型需要自己手动下载放置在相应的目录下

**Comment by JackonLiu** [comment]
需要重新把解压后的文件改成rar，后重新解压，然后就会出现model和params

**Comment by JimReno** [comment]
感谢老哥的提示，需要重新解压，非常感谢！
