### ISSUE TITLE
resnet34 默认学习率    learning_rate: 0.0005 训练到一定准确度后没法继续改善，能修改lr继续提高准确率吗？修改多少比较好？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10316]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

resnet34 默认学习率    learning_rate: 0.0005
训练到一定准确度后没法继续改善，能修改lr继续提高准确率吗？修改多少比较好？

**Comment by livingbody** [comment]
learning_rate就没必要再打主意了，算法的能力是有限的，可以用更大的数据集来尝试，数据多多益善。

**Comment by nissansz** [comment]
除了resnet34，还有哪些resnet可以支持crnn?要怎么修改yml配置

**Comment by idontkonwher** [comment]
麻烦问下，多卡batchsize增大之后learnning rate 是否应该等比例提高？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
