### ISSUE TITLE
PPOCRlabel KIE模式标注问题

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#10310]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu22
- 版本号/Version：Paddle：2.5  PaddleOCR：2.6 问题相关组件/Related components：PPOCRlable
- 运行指令/Command Code：PPOCRLabel --kie True
问题：
1、PPOCRlabel KIE模式下标注生成的标签如下
1/1_1.png	[{"transcription": "TEMPORARY", "points": [[209, 205], [807, 205], [807, 279], [209, 279]], "difficult": false, "key_cls": "发文机关标志"}
没有 ’lable‘标签，而是‘key_cls’标签，格式和官方要求的KIE训练数据不同

2、训练KIE模型，训练数据是否需要对所有文本进行打标， 是否可以只对需要提取的信息文本进行打标？
3、对于图片中多行信息，是否可以用一个矩形框进行标注？

**Comment by qiuyunbest** [comment]
我也想知道这个问题

**Comment by UserWangZz** [comment]
https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md
参考文档进行标注，感觉是标注过程有问题
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
