### ISSUE TITLE
训练SLAnet_ch

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10317]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：uabantu 18 cuda 11.6
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddle 2.4 paddocr 2.6
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

按照官方教程：整理数据格式，：
{
   'filename': PMC5755158_010_01.png,							# 图像名
   'split': ’train‘, 									# 图像属于训练集还是验证集
   'imgid': 0,								 		# 图像的index
   'html': {
     'structure': {'tokens': ['<thead>', '<tr>', '<td>', ...]}, 			# 表格的HTML字符串
     'cells': [
       {
         'tokens': ['P', 'a', 'd', 'd', 'l', 'e', 'P', 'a', 'd', 'd', 'l', 'e'], 	# 表格中的单个文本
         'bbox': [x0, y0, x1, y1]  							# 表格中的单个文本的坐标
       }
     ]
   }
}

怎么还需要8个点？，英文的4个点，中文为啥8个呢

/PaddleOCR/ppocr/data/imaug/label_ops.py", line 729, in __call__
    bboxes[i] = bbox
ValueError: could not broadcast input array from shape (4,) into shape (8,)

**Comment by lltzahdz** [comment]
您好，这个问题您如何解决的
