### ISSUE TITLE
linux cpp_infer

### ISSUE THREAD

**Issue by SxyNoPeace** [PaddlePaddle/PaddleOCR#1032]
paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/build.make:62: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/dynamic_loader.cc.o' failed
make[2]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/dynamic_loader.cc.o] Error 1
CMakeFiles/Makefile2:3004: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/all' failed
make[1]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by LDOUBLEV** [comment]
这里看不出来，看一下最开始编译报错的地方？
提供下你的paddle版本，Cmake版本

**Comment by SxyNoPeace** [comment]
> 这里看不出来，看一下最开始编译报错的地方？
> 提供下你的paddle版本，Cmake版本

The problem with entering make - j is as follows：

stamp/extern_cryptopp-install-*.log
[  2%] Completed 'extern_cryptopp'
[  2%] Built target extern_cryptopp
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_protobuf'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_mkldnn'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/gflags/gflags.git' into submodule path 'doc' failed
CMake Error at /home/chen/experiment/Project/Paddle/build/third_party/gflags/tmp/extern_gflags-gitclone.cmake:49 (message):
  Failed to update submodules in:
  '/home/chen/experiment/Project/Paddle/build/third_party/gflags/src/extern_gflags'


CMakeFiles/extern_gflags.dir/build.make:90: recipe for target 'third_party/gflags/src/extern_gflags-stamp/extern_gflags-download' failed
make[2]: *** [third_party/gflags/src/extern_gflags-stamp/extern_gflags-download] Error 1
CMakeFiles/Makefile2:365: recipe for target 'CMakeFiles/extern_gflags.dir/all' failed
make[1]: *** [CMakeFiles/extern_gflags.dir/all] Error 2
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_cub'...


Is it the network delay？
Cmake version is 3.15.0
paddle version is v1.8.

**Comment by LDOUBLEV** [comment]
Is there no internet connection when compiling?

```
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_protobuf'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_mkldnn'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/gflags/gflags.git' into submodule path 'doc' failed
```

**Comment by SxyNoPeace** [comment]
> 编译时没有互联网连接吗？
> 
> ```
> error: RPC failed; curl 18 transfer closed with outstanding read data remaining
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> Cloning into 'extern_protobuf'...
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> Cloning into 'extern_mkldnn'...
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> fatal: clone of 'https://github.com/gflags/gflags.git' into submodule path 'doc' failed
> ```

the computer was networked，is it because VPN is not used ??

**Comment by LDOUBLEV** [comment]
The reason why compiling error is the bad network connection when pulling packages needed by compiling. 
You should check your network or use another machine.

**Comment by SxyNoPeace** [comment]
> The reason why compiling error is the bad network connection when pulling packages needed by compiling.
> You should check your network or use another machine.

thanks，Error in windos as follows:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“E:\fluid_inference_install_dir\fluid_inference_install_dir\paddle\lib\libpaddle_fluid.dll

What is the reason？
vs2015 +cmake3.15.0

**Comment by LDOUBLEV** [comment]
It is recommended to use VS2019 to compile  cpp_infer demo on windows operating system machines.

**Comment by LDOUBLEV** [comment]
reference to issue https://github.com/PaddlePaddle/PaddleOCR/issues/1023
