### ISSUE TITLE
我想获得检测和识别的features，该如何做？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleOCR#10320]
最近研究视频重复检测，目前尝试了每秒提取一张图片，图片再提取特征，通过特征相似度判断，效果不是很好。打算加上其他信息。
因为我们是教育行业，每张图片中的文本我认为也是比较重要的特征，所以想拿到检测和识别模型的features。该如何操作？

**Comment by shiyutang** [comment]
获得检测和识别的features可以使用ppocrv3的模型预测获得特征。

**Comment by zouhan6806504** [comment]
> 获得检测和识别的features可以使用ppocrv3的模型预测获得特征。

有示例代码吗？

**Comment by shiyutang** [comment]
使用这个推理即可：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md
