### ISSUE TITLE
ImportError: libcudart.so.10.2

### ISSUE THREAD

**Issue by Rudragoud** [PaddlePaddle/PaddleOCR#10324]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle2.4.2：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：  debug: false
                                                  use_gpu: gpu
in .yml file
- 完整报错/Complete Error Message：
-     from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by livingbody** [comment]
read: https://github.com/PaddlePaddle/PaddleOCR/issues/9049
```
conda install cudatoolkit=10.2
export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib
```

**Comment by shiyutang** [comment]
> ~/miniconda3/envs/env_paddle/lib

The path may be subject to change based on your conda env.

**Comment by shiyutang** [comment]
The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
