### ISSUE TITLE
版面分析模型，title的宽度容易短，高度都是正常的，请问一下怎么优化啊

### ISSUE THREAD

**Issue by yywangfei** [PaddlePaddle/PaddleOCR#10326]
如提，自己训练的版面分析模型，宽度长长偏短

**Comment by livingbody** [comment]
详细描述下吧。

**Comment by ttw0** [comment]
<img width="978" alt="Snipaste_2023-12-29_15-36-11" src="https://github.com/PaddlePaddle/PaddleOCR/assets/56748855/92b90204-340b-47ec-ad22-652dab44dc6a">
+1，一些长title就会短

**Comment by zhuxiaobin** [comment]
同样的问题，6000张图片训练，出来的模型在实际使用，有的时候检测框宽度不够长会丢失两边

**Comment by Thanhthanhthanhthanh1711** [comment]
> <img alt="Snipaste_2023-12-29_15-36-11" width="978" src="https://private-user-images.githubusercontent.com/56748855/293326287-92b90204-340b-47ec-ad22-652dab44dc6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTkyMjgsIm5iZiI6MTcxNTc1ODkyOCwicGF0aCI6Ii81Njc0ODg1NS8yOTMzMjYyODctOTJiOTAyMDQtMzQwYi00N2VjLWFkMjItNjUyZGFiNDRkYzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA3NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGJhMzIxMTVmMmZhYjYxZjdiM2RkMDNiZDk4NmQ5NmJmNTIxZDUwYmU5YWFiMjZjM2I1NDNkZTU3NzY3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W37GA8kw2-MgVCRvEZFFYlJf8Z7MUwWHUscVEff9RWU"> +1，一些长title就会短

hi bro, 
you can show me what parameters to adjust to be able to combine paragraphs that are close together into one document?

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
