### ISSUE TITLE
PaddleOCR v4模型使用Mkldnn在非AVX512 CPU上变得非常慢

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/PaddleOCR#10337]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10
- Paddle：  2.5.0/2.4.2
- PaddleOCR： ppocr-v4 识别模型

AVX512 CPU上速度正常，速度大约是1.3s
在其它CPU上奇慢无比，速度大约是60秒~100秒
（虚拟机CPU都是4核）

![LFOV6P1M3% Z@$(DB5TM7HB](https://github.com/PaddlePaddle/PaddleOCR/assets/1317141/57c3b929-a1c5-48d9-88b8-8f5f9ee11b06)

使用Openblas或者Onnx速度都正常，使用ppocr-v3识别模型也正常。

**Comment by raoyutian** [comment]
预测库的Mkldnn.dll问题。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by sdcb** [comment]
不对，上面只解决了2.5推理库准确率下降的问题，未解决ppocr-v4性能慢的问题，它们是两个问题
