### ISSUE TITLE
Error in fine tuning PGNet step 2.

### ISSUE THREAD

**Issue by AbdulDD** [PaddlePaddle/PaddleOCR#10336]
While training for PGNet step 2. I am encountering the following error:
Traceback (most recent call last):
  File "/content/PaddleOCR/PaddleOCR/tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/content/PaddleOCR/PaddleOCR/tools/program.py", line 666, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/parallel.py", line 774, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'. Did you mean: 'device_id'?

Can anyone guide me through this?

Note: I am using google colab.

**Comment by AbdulDD** [comment]
I have installed Paddlepaddle GPU and the issue is resolved for me.

**Comment by youde2000** [comment]
Have you already resolved it

**Comment by AbdulDD** [comment]
Yes once you install paddlepaddleGPU it will be resolved. it seems that the
library is updated and _device_id is changed to device_id.  so you just
have to update library if already installed
