### ISSUE TITLE
Does Paddleocr supports Multi Threading ? 

### ISSUE THREAD

**Issue by amitabesit** [PaddlePaddle/PaddleOCR#10332]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：x86_64 , Macbook Pro (Intel)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddlePaddle - 2.4.2 , paddleocr -2.6.1.3
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Does Paddleocr supports Multi Threading ? 
I am having 20,000 small images to perform OCR and each image takes around approx. 300 ms (milli seconds) ~ 100 mins
so I tried to use futures.ThreadPoolExecutor(12) with 12 worker threads to 100 mins/12 

but ocr.ocr(file_path, cls=True) still processing one by one.
does ocr.ocr() using kind of sync / locking mechanism ?

example code : 
```
os.chdir(folderPath)
result = sorted(filter(os.path.isfile, os.listdir('.')), key=os.path.getmtime)

def worker(i):
    print(i)
    time.sleep(1)
    return i, time.time()


def perform_ocr(file_path):
    print(file_path)
    start_time = time.perf_counter()
    ocr_result = ocr.ocr(file_path, cls=True)
    print("Time taken", (time.perf_counter() - start_time))


e = futures.ThreadPoolExecutor(12)

# Not working as multi Threaded
e.map(perform_ocr, result)

# Working as multi Threaded
# e.map(worker, result)

```

Please suggest, how to achieve multi Threading or should I try with Multi Processing if  multi Threading is not supported by PaddleOCR

**Comment by onecatcn** [comment]
please refer to examples here: https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/multi_thread/README_CN.md

**Comment by MayankFawkes** [comment]
a code would be appreciated, i am still having same problem

**Comment by MayankFawkes** [comment]
@amitabesit i found the solution in this case please use ``ProcessPoolExecutor`` and not the ``ThreadPoolExecutor``

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
