### ISSUE TITLE
想问一下，这些垂类模型是在哪里下载吖

### ISSUE THREAD

**Issue by frank60229** [PaddlePaddle/PaddleOCR#10335]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.3
- 运行指令/Command Code：python tools/infer_rec.py -c configs/rec/rec_svtrnet_ch.yml -o Global.pretrained_model=./svtr_ch_high_accuracy/best_accuracy Global.infer_img=./doc/imgs_words/ch/word_1.jpg Global.use_gpu=True

- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/99239158/8143743d-d144-4545-b475-8a6425555789)

- 就是很奇怪 这些垂类的模型在哪里下载
-
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/99239158/4e92279d-9f7e-4282-b4f1-75e9f527eaba)
扫码之后就没有任何的提示了，就很奇怪 很多垂类的模型都不知道在哪里下载

**Comment by magicleo** [comment]
同问，请问楼主找到了吗？

**Comment by WilliamQf-AI** [comment]
链接: https://pan.baidu.com/s/1UimNclwfoXuNev9UbuPlNQ?pwd=5bq1 提取码: 5bq1 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by HouYueJie** [comment]
@WilliamQf-AI 链接失效了，能在提供一个链接么？十分感谢！！

**Comment by HouYueJie** [comment]
@WilliamQf-AI 链接失效了，能再提供一个链接么？十分感谢！！

**Comment by BTBU2018** [comment]
@WilliamQf-AI 你好，链接失效了，能够重新分享一下嘛！！！感谢！！！

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
