### ISSUE TITLE
识别模型，换字典进行重新训练

### ISSUE THREAD

**Issue by smalllyingspinach** [PaddlePaddle/PaddleOCR#10330]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

想问下如果想要更换字典，是否可以在原来的预训练模型上通过调整最后一层的规模来实现（或者说有什么别的办法吗？）

**Comment by 0-Maxwei-0** [comment]
您好，解决了吗

**Comment by smalllyingspinach** [comment]
> 如果你用一个新的字典（规模和原来的预训练不一样）训练的话，他会自动初始化一个新的头在后面
