### ISSUE TITLE
PPOCRLabel标注错误BUG

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10331]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu 20
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr  2.6
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![5004](https://github.com/PaddlePaddle/PaddleOCR/assets/32585434/8d1f24e4-4fce-4f3a-a8e6-94f51048aa82)

@tink2123 @ZeyuChen @bingooo @sdcb 

1.是直接识别出html 保存html文件，再浏览器渲染出来的，渲染出来的的和保存的xls结果不一样，渲染图和保存的xlsx结果不一样呢,不同之处 再单项金额虽不重大但单独计提
[5004.xlsx](https://github.com/PaddlePaddle/PaddleOCR/files/11994177/5004.xlsx)

补齐空白单元格之后， 种类 这个单元格怎没有了呢？ 种类单元格跨行标注错误
下面这个是自己添加空白单元之后的
2.标注结果：
 <html><body><table><tbody><tr><td rowspan=\"4\">期初余额</td><td colspan=\"5\">账面余额</td></tr><tr><td colspan=\"2\">坏账准备</td><td colspan=\"2\">账面价值</td><td>金额</td></tr><tr><td>比例（%）</td><td>金额</td><td>计提比例（%）</td><td>#####</td><td>账龄分析法组合</td></tr><tr><td>6,665,779,301,76</td><td>100.00</td><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291,30</td></tr><tr><td>关联单位组合</td><td>待识别</td><td>待识别</td><td>待识别</td><td>待识别</td><td>待识别</td></tr><tr><td>组合小计</td><td>6.665,779,301.76</td><td>100.00</td><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291.30</td></tr><tr><td>单项金额虽不重大但单独计提</td><td>待识别</td><td>待识别</td><td>待识别</td><td>待识别</td><td>待识别</td></tr><tr><td>合计</td><td>6,665,779,301.76</td><td>100.00</td><td>153,565,010.46</td><td>2.30</td><td>6,512,214,291.30</td></tr></tbody></table></body></html>

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
