### ISSUE TITLE
Pyinstaller - no module named "ppocr"

### ISSUE THREAD

**Issue by olqi** [PaddlePaddle/PaddleOCR#10340]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 10
- 版本号/Versin: Paddle：2.5.0  PaddleOCR：2.6.1.3 问题相关组件/Related components：vscode, python 3.9.2

Hey, when building an exe with Pyinstaller from a python file that uses PaddleOCR I get a "No module named 'ppocr' error" (attached a screenshot). How do I fix it?

The code I'm using is just the most barebones one to find out how to create an exe file with PaddleOCR:

`import paddleocr

ocr = paddleocr.PaddleOCR()

path = input('input path: ')

result = ocr.ocr(path)

print(result)`

Thank you! 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/139183372/9941d368-54a6-4d58-9c22-359179d0c03b)

**Comment by Edmond-Lee-Zse-Wong** [comment]
I got another but similar error when I use "from paddleocr import PaddleOCR",  my error is "FileNotFoundError"
![Uploading 屏幕截图 2023-12-23 220522.png…]()

**Comment by Edmond-Lee-Zse-Wong** [comment]
I got another but similar error when I use "from paddleocr import PaddleOCR", my error is "FileNotFoundError"
![屏幕截图 2023-12-23 220522](https://github.com/PaddlePaddle/PaddleOCR/assets/56387202/61d7011c-c19d-4cb0-a1af-3a3dea5948b7)

**Comment by kerneltravel** [comment]
@Edmond-Lee-Zse-Wong  according to [this method](https://github.com/PaddlePaddle/PaddleOCR/pull/10502), you'd try to append parameter `--collect-all  paddleocr` when package with module paddleocr by pyinstaller .

**Comment by Heryk13** [comment]
Here i made a tutorial for making a exe with pyinstaller

https://github.com/PaddlePaddle/PaddleOCR/discussions/11490#discussion-6072471

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
