### ISSUE TITLE
PaddleOCR v4模型使用Mkldnn在非AVX512 CPU上变得非常慢

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/PaddleOCR#10346]
注：这个问题是https://github.com/PaddlePaddle/PaddleOCR/issues/10337 的重开，它未得到解决或解答，且被关闭了，这个问题和PaddleInference 2.5准确率下降的问题是不同的问题。

- 系统环境/System Environment：Windows 10
- Paddle：  2.5.0/2.4.2 with mkldnn
- PaddleOCR： ppocr-v4 识别模型

AVX512 CPU上速度正常，速度大约是1.3s
在其它CPU上奇慢无比，速度大约是60秒~100秒
（虚拟机CPU都是4核）

![LFOV6P1M3% Z@$(DB5TM7HB](https://github.com/PaddlePaddle/PaddleOCR/assets/1317141/57c3b929-a1c5-48d9-88b8-8f5f9ee11b06)

使用Openblas或者Onnx速度都正常，使用ppocr-v3识别模型也正常。

**Comment by magicleo** [comment]
已经有V4模型了？请问模型地址在哪？

**Comment by yaomichael** [comment]
请问部署的时候，Flags_use_mkldnn 是保持为0（缺省值）吗？

**Comment by sdcb** [comment]
use_mkldnn=1

**Comment by yaomichael** [comment]
能试试=0的情况吗？

**Comment by sdcb** [comment]
> 另外问个问题，use_mkldnn=1，但是pcrv3的话，速度也是正常的（1-2s）？ 换句话说PCRv4和v3的差别就能导致这个性能降级？

对的，在我另一台电脑上，基于v4模型，使用openblas性能很快（8秒），使用onnx性能很快（2秒），使用mkldnn性能很慢（33秒），使用gpu性能也很快（0.1秒）
同时如果使用v3模型和mkldnn，性能也很快（0.3秒）

**Comment by sdcb** [comment]
换言之，这个问题和ppocr-v4、mkldnn、AVX512F同时相关。

**Comment by apple2333cream** [comment]
ppocr-v4识别模型能下载了吗，请问有下载地址吗？

**Comment by sdcb** [comment]
@apple2333cream 未公开发布。

**Comment by sdcb** [comment]
no, this issue was not fixed, please check.

**Comment by jcyrss** [comment]
我遇到了一样的问题， 在Python解释器（3.10），PaddlePaddle（2.5.2）, PaddleOCR（2.7.0.3） 版本一样的情况下，同样的一张图， 都使用ch_PP-OCRv4 ，enable_mkldnn=True

在我的一个AMD 7840U（支持 AVX-512） 笔记本上识别速度是 0.2秒， 
而在另一个AMD 5600U（支持 AVX-512） 笔记本上识别速度是 13秒， 如果改为 ch_PP-OCRv3， 则为0.3秒左右

enable_mkldnn=False差别不大，都是2-3秒左右。

现在为了支持用户的各种环境，我只能退回使用ch_PP-OCRv3

**Comment by LLee233** [comment]
@sdcb Hi, 请问你在进行推理的时候是否都是用的官方推理库？我们这边check了一下，发现官方的推理库都是用带avx512的机器生成的。在这种情况下，如果在非avx512机器上用官方推理库，可能就会导致这种情况，类似[#11597](https://github.com/PaddlePaddle/PaddleOCR/issues/11597)。针对这个issue我们已经提了[PR](https://github.com/PaddlePaddle/Paddle/pull/64132/)，等merge之后应该就能解决了。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
