### ISSUE TITLE
多线程推理内存溢出，不断增加,最终程序OOM

### ISSUE THREAD

**Issue by tfka** [PaddlePaddle/PaddleOCR#10342]
### ### 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle： 2.4.2.post112  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

代码正常运行，但是内存占用率不断增高，最终OOM，降低线程数也没用。

```
executor_ocr = concurrent.futures.ThreadPoolExecutor(25)
ocr = PaddleOCR(rec_model_dir="ch_PP-OCRv3_rec_infer",det_model_dir="ch_PP-OCRv3_det_infer",cls_model_dir = "ch_ppocr_mobile_v2.0_cls_infer",lang="ch",use_angle_cls=False,show_log=False,use_gpu=True,use_mp=True)
def deal_one(image):
    result = ocr.ocr(image, cls=False)
    return result
futures = [executor_ocr.submit(deal_one, img) for img in images]
    done, not_done = concurrent.futures.wait(futures,timeout=args.ocr_timeout)
    # 处理已完成的任务结果
    for future in done:
        try:
            result = future.result()  # 获取已完成的任务结果
            ocr_results.append(result)
        except Exception as e:
            print(f"Error occurred: {e}")
```

**Comment by raoyutian** [comment]
增加参数  enable_mkldnn=False

**Comment by raoyutian** [comment]
内存持续增加是因mklnn引起。可以关闭mkl加速，达到内存优化，但速度降低。
增加参数  enable_mkldnn=False

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by bxjxxyy** [comment]
> 内存持续增加是因mklnn引起。可以关闭mkl加速，达到内存优化，但速度降低。 增加参数 enable_mkldnn=False
不启用mkldnn的话识别速度太慢了，现在有没有可以解决启用mkldnn的情况下内存持续增加的办法了？
