### ISSUE TITLE
是否有适配繁中简中英文的多语言模型

### ISSUE THREAD

**Issue by eric781ctf** [PaddlePaddle/PaddleOCR#10341]
我手上有一包图像资料有简体繁体和英文，但我没办法先判断他们是哪种字体。

我尝试过的模型有 `ch` 和 `chinese_cht` 虽然这两个模型都可以辨识出简体和繁体，但准确率差蛮多的。

有没有一种模型我可以让我辨识出这三种字体准确度也没太差的？

**Comment by shiyutang** [comment]
可以自行基于方向识别器，训练一个多语种分类器，并对不同的语种分别检测识别。

**Comment by gal0is** [comment]
请问能否在现有中英文模型的基础上，加入繁体字典，然后微调？


> 可以自行基于方向识别器，训练一个多语种分类器，并对不同的语种分别检测识别：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/angle_class.md

**Comment by leviethung2103** [comment]
In my case, the performance of chinese_cht model is terrible in comparison with ch model. Has anyone also encounter this problem ?

**Comment by lipeng1109** [comment]
我也有多语言分类的需求，现在没有模型能对不同的语言进行分类的吗？自己训练多语言分类，涉及到整图进行分类还是字符条分类，都有多种语言混合的情况，该怎么处理数据呢

**Comment by eric781ctf** [comment]
> 请问能否在现有中英文模型的基础上，加入繁体字典，然后微调？
> 
> > 可以自行基于方向识别器，训练一个多语种分类器，并对不同的语种分别检测识别：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/angle_class.md

我个人猜测可能性不太高，毕竟如果只是加上繁体字典进行简繁转换的话，在辨识的过程中就可能会因为繁简的形状特征不同而被辨识成不同的字了

**Comment by eric781ctf** [comment]
> In my case, the performance of chinese_cht model is terrible in comparison with ch model. Has anyone also encounter this problem ?

I got the same problem, and in my situation, i wish to recognition multi-language in one model, of course its terrible lol.
The author has suggest me to train a new classifier based on the angle_classifier.
I've been busy with other projects recently, so I've put this matter on hold.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
