### ISSUE TITLE
Error in training PGNet.

### ISSUE THREAD

**Issue by AbdulDD** [PaddlePaddle/PaddleOCR#10348]
Traceback (most recent call last):
  File "/content/PaddleOCR/tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/content/PaddleOCR/tools/program.py", line 623, in preprocess
    FLAGS = ArgsParser().parse_args()
  File "/content/PaddleOCR/tools/program.py", line 61, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/content/PaddleOCR/tools/program.py", line 70, in _parse_opt
    k, v = s.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

I can't figure out what is wrong? can anyone please guide me on this.

**Comment by livingbody** [comment]
Please check the data set

**Comment by AbdulDD** [comment]
Dataset is fine. I have take total_text data from this official repository.
One more thing I have already tried the downgrade of paddle GPU from 2.5 to 2.4.2 that also didn't worked.

**Comment by aafkari74** [comment]
> Dataset is fine. I have take total_text data from this official repository. One more thing I have already tried the downgrade of paddle GPU from 2.5 to 2.4.2 that also didn't worked.

@AbdulDD @livingbody 
hello sir,

i am new to this architecture and i had a question about using this model to train on a Farsi custom dataset.
is this possible or this model only works on total text dataset?

thanks.

**Comment by AbdulDD** [comment]
@aafkari74 , Hi there! if you are encountering same issue as above "ValueError: not enough values to unpack (expected 2, got 1)" then make chnages directly in config file (.ymal file). it will work, I have done so and even got good results on my custom dataset.

**Comment by aafkari74** [comment]
Hello my friend.

I really appreciate your help.

Good luck in your future works.

**Comment by AbdulDD** [comment]
Thank you.

**Comment by Maryam-Mostafa** [comment]
Hi @AbdulDD, 
I'm encountering same issue as above "ValueError: not enough values to unpack (expected 2, got 1)" what changes in yaml file should be specifically changed to solve this issue?

**Comment by AbdulDD** [comment]
@Maryam-Mostafa, Ma'am lets say you  have prepared the dataset as mentioned in documentation then according to repository you need to run following command:

"python3 tools/train.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=./pretrain_models/train_step1/best_accuracy Global.load_static_weights=False"

In above command (I hope you know but just for explanation) "-c" is used to specify config file and "-o" is used to override the current values in config file.

Me along my team observed that "-o" command gets you to the above "value pack error" therefore we directly changed the config file. open config file (add training and validation paths for both images and jsons, add pretrained model path) and any other parameter you want to change then pass config file as following:

!python3 tools/train.py -c "\content\drive\yourconfigfile.yml"

I know this is not a proper solution, it is just way around to solve problem.

we finetuned model on our custom dataset and achieved 84% accuracy.

I hope this solution will help you.
Best of luck
