### ISSUE TITLE
Is visualdl graphs dynamic not available ? 动态网络结构怎么才能看见啊，ppocr用得了伐？

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#10347]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/115529885/8854e50d-60b2-4aa0-82aa-57a940fecb39)

**Comment by livingbody** [comment]
由于升级等情况，visualdl安全原因BML里可以用，老版aistudio环境不能用。
# 建议
下载文件，本地可视化。

**Comment by ToddBear** [comment]
可以参考 https://visualdl.readthedocs.io/zh/latest/README_CN.html 本地安装和使用VisualDL

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by OpenOneV** [comment]
前面图文没表达明白。我不知道还有在线版本的visualdl。我是在本地运行的visualdl命令如下：
activate paddle_env
visualdl --logdir "C:\Users\...\PaddleOCR\output\Multilingual_PP-OCRv3_det_slim_distill_train...\teacher_only\vdl" --port 80 --host 0.0.0.0
在运行PaddleOCR训练命令（train.py）的时候用来看当前训练的曲线的，但是除了vdl中的train、eval的log曲线，其他的功能除静态图可以用.pdmodel导入看以外，都不能用。
所以主要是问本地在训练OCR模型的时候怎么用上这个visualdl的动态网络结构、样本数据-图象、超参可视化等功能？
训练语句为：
cd %ppocr_path%
python tools/train.py -c %config_path% -o Global.use_visualdl=True
具体需要如何配置配置文件内容以使用这些功能？

**Comment by OpenOneV** [comment]
@ToddBear @livingbody @OpenOneV
