### ISSUE TITLE
在rt要求较高的情况下应该如何inference最合适

### ISSUE THREAD

**Issue by tfka** [PaddlePaddle/PaddleOCR#10359]
请问有方案能够批量预测吗？
比如QPS100，输入的是图像的ndarray，当前使用如下方式在A10串行预测，单图大概在50ms左右，是否有更合适的能够batch inference的方案？比如能够达到8张图 70ms～100ms这样，更充分的利用GPU。
```
ocr = PaddleOCR(rec_model_dir="ch_PP-OCRv3_rec_infer",det_model_dir="ch_PP-OCRv3_det_infer",cls_model_dir ="ch_ppocr_mobile_v2.0_cls_infer",lang="ch",use_angle_cls=False,show_log=False,use_gpu=True,use_mp=True)
def deal_one(image):
    result = ocr.ocr(image_ndarray, cls=False)
    return result
```

**Comment by onecatcn** [comment]
可以尝试fastdeploy serving的方案：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving/fastdeploy_serving

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
