### ISSUE TITLE
有没有一个比较好的指导，直接能够了解config中的各个可用的参数以及其意义、效果？

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#10356]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

```
Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
```
比如这里的A.B.scale 什么意思？
搜遍文档也搜不到（可能没看完）

**Comment by livingbody** [comment]
# 请参考：
PaddleOCR/doc/doc_ch/config.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/config.md

**Comment by ToddBear** [comment]
> # 请参考：
> PaddleOCR/doc/doc_ch/config.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/config.md

文档中的参数似乎不全（比如没有问题中提到的scale），建议提pr更新一下文档

**Comment by OpenOneV** [comment]
> > # 请参考：
> > PaddleOCR/doc/doc_ch/config.md at release/2.6 · PaddlePaddle/PaddleOCR · GitHub https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/config.md
> 
> 文档中的参数似乎不全（比如没有问题中提到的scale），建议解答问题的开发者可以提pr更新一下文档
@ToddBear 

个人感觉那个文档足够了，可以导航到py代码，就能看到具体的参数用途了。如果不习惯看代码的用户大概也不会关注这些配置细节。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
