### ISSUE TITLE
训练和评估的效果都很不错，但是预测效果很差

### ISSUE THREAD

**Issue by loading2022** [PaddlePaddle/PaddleOCR#10355]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：
Paddle：2.4.2  
PaddleOCR： 2.6.1.3
问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/infer/predict_system.py --image_dir=./test_new/LE/ --det_model_dir=./output/det/infer --rec_model_dir=./output/v3_en_mobile/infer --rec_image_shape=3,32,320 --use_space_char=False --max_text_length=7 --rec_char_dict_path=ppocr/utils/en_dict.txt --use_gpu=True
- 完整报错/Complete Error Message：
没有报错能够正常运行，训练和评估的效果都很不错，但是预测效果很差
以下是 det 和 rec 两个模型训练评估完的结果:
det 结果
<img width="932" alt="螢幕擷取畫面 2023-07-09 173822" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/4432ea27-c4e0-41d4-a9a6-8980bccaf2f4">

rec 结果
<img width="939" alt="螢幕擷取畫面 2023-07-11 171521" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/9f6f8ffa-f9ca-4b46-96f4-74b2c23d897d">

有参考过这篇[文章]( https://blog.csdn.net/ahhhhhh520/article/details/114118189)，但是准确率提升不大，也有将 test 标注过后丢进 eval 里面，效果也有到 90% 左右，但是放进 infer 中就只剩下 38% 了

**Comment by loading2022** [comment]
补充配置文件在这个档案里，使用 predict_system.py 极为不准，分别使用 infer_det.py 和 infer_rec.py 的准确度好很多，以下附上两张使用图，有检测到的是使用 infer_det.py
[config.zip](https://github.com/PaddlePaddle/PaddleOCR/files/12029131/config.zip)
<img width="428" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/5c94c8bd-f8ba-40b6-b7ff-f4221386420b">
<img width="218" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/119124535/b460a44d-87dc-48b8-942c-9918bfb5a607">

**Comment by Yang66267** [comment]
相同的问题, 你解决了吗?

**Comment by loading2022** [comment]
> 相同的问题, 你解决了吗?

还没欸，看了一些文章，有人说是预处理不一致的问题，但也还没找到

**Comment by Yang66267** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yang66267** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by UserWangZz** [comment]
转inference模型后精度下降，可能是inference推理脚本中的参数和训练时不一致导致的，可以检查一下。
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by Yang66267** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
