### ISSUE TITLE
在使用蒸馏模型的时候，预训练了其中的teacher模型，但是neck用的不一样，结果无法导入预训练模型

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#10366]
但是如果用和蒸馏模型一致的teacher.neck=LKPAN，最终导出的模型，就不能用来导入PPOCRLabel批量预测，就不好直观看效果...等等我想想看，如果把eval数据集做好一点似乎也可。em哈哈那我再看看。

怎么办？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
