### ISSUE TITLE
Issue with structuring output and using ppocrlabel functionalities

### ISSUE THREAD

**Issue by Rimabdejelil** [PaddlePaddle/PaddleOCR#10360]
I am encountering an issue while trying to structure the output of PaddleOCR according to my specific requirements. Additionally, I am looking to utilize the functionalities provided by ppocrlabel to address this problem.

**Comment by ToddBear** [comment]
Can you provide more details about the issue?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
