### ISSUE TITLE
paddleOCR识别结果丢失了文档的最后一行

### ISSUE THREAD

**Issue by magicleo** [PaddlePaddle/PaddleOCR#10367]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- Linux 4.15.0-202-generic 213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddle-bfloat                 0.1.7
- paddleclas                    2.5.1
- paddleocr                     2.6.1.0
- paddlepaddle-gpu              2.5.0

- 运行指令/Command Code：
- python predict_system.py  --det_model_dir=/mnt/storage/PaddleOCR/ppstructure/inference/ch_PP-OCRv3_det_infer   --rec_model_dir=/mnt/storage/PaddleOCR/ppstructure/inference/ch_PP-OCRv3_rec_infer  --rec_char_dict_path=/mnt/storage/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt  --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer  --table_char_dict_path=/mnt/storage/PaddleOCR/ppocr/utils/dict/table_structure_dict_ch.txt  --layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_cdla_infer  --layout_dict_path=/mnt/storage/PaddleOCR/ppocr/utils/dict/layout_dict/layout_cdla_dict.txt  --vis_font_path=/mnt/storage/PaddleOCR/doc/fonts/simfang.ttf   --image_dir=aa.pdf --output=ppp

- 完整报错/Complete Error Message：
丢失了文档最后一行
<img width="1245" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/3990950/1e1dc6bd-4416-4dbb-a702-71330eec8023">

**Comment by livingbody** [comment]
aistudio新建项目试试？不然不大好复现。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
