### ISSUE TITLE
PaddleOCR推断时显存未释放 

### ISSUE THREAD

**Issue by daigang896** [PaddlePaddle/PaddleOCR#10376]
ubuntu18.04.6或ubuntu20.04.6上均测试了：
环境：python3.8、cuda11.6、cudnn-linux-x86_64-8.4.0.27_cuda11.6、
paddlepaddle_gpu-2.4.1.post116-cp38-cp38-linux_x86_64；
代码：PaddleOCR-release-2.6

主要代码：
from paddleocr import PaddleOCR
ocr = PaddleOCR(lang="ch")
for img_path in img_paths:
        result = ocr.ocr(img_path)

执行完后PaddleOCR推断时显存未释放 ，不知道怎么办，是否有人遇到相同的问题，是如何解决的？

**Comment by livingbody** [comment]
empty_cache-API文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/cuda/empty_cache_cn.html#empty-cache

文档举例代码如下：

```
import paddle

# required: gpu
paddle.set_device("gpu")
tensor = paddle.randn([512, 512, 512], "float")
del tensor
paddle.device.cuda.empty_cache()
```

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
