### ISSUE TITLE
模块计算机类型“x64”与目标计算机类型“x86”冲突

### ISSUE THREAD

**Issue by hello-lx** [PaddlePaddle/PaddleOCR#10378]
在编译ppocr的时候出现了以下的问题，曾按照网上的方式修改编译器为x64的，但是未曾解决掉这个问题：

- 系统环境/System Environment：Windows10,  vs2017 community
- 版本号/Version：Paddle：- PaddleOCR：   release/2.2
- 完整报错/Complete Error Message：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1112	模块计算机类型“x64”与目标计算机类型“x86”冲突	ppocr	E:\XSpace\OCR\PaddleOCR\deploy\cpp_infer\build\x64\Release\args.obj	1

**Comment by GreatV** [comment]
解决方案平台改为x64应该就可以了

**Comment by hello-lx** [comment]
> 解决方案平台改为x64应该就可以了

已经试过了，还是会报相同的错

**Comment by hello-lx** [comment]
> 解决方案平台改为x64应该就可以了

是修改vs2017的解决方案为x64吗？已经试过了，还是会有相同的错误，如果是修改代码的话，麻烦告知一声该如何修改

**Comment by GreatV** [comment]
点一下重新生成

**Comment by hello-lx** [comment]
> 点一下重新生成

点击的就是重新生成

**Comment by GreatV** [comment]
那应该没有问题，麻烦你把整个窗口截图一下，我看看。

**Comment by GreatV** [comment]
是不是有某个子项目没有设置，可以挨个检查一下。

**Comment by hello-lx** [comment]
![error2](https://github.com/PaddlePaddle/PaddleOCR/assets/33655486/a2339940-91eb-4284-becf-d6f8d4009401)
检查过了，都是x64的

**Comment by GreatV** [comment]
那检查一下cmake步骤，是不是设置的x64

**Comment by GreatV** [comment]
得把以前的build删除掉
