### ISSUE TITLE
paddleOCR的TableMaster推理模型不支持Paddle2ONNX 吗？如果不支持，什么时候能够支持呢？谢谢

### ISSUE THREAD

**Issue by allen20200111** [PaddlePaddle/PaddleOCR#10371]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 
- 版本号/Version：paddlepaddle-gpu：  2.5.0.post120   PaddleOCR：2.6   paddle2onnx:  1.0.6
- 运行指令/Command Code：paddle2onnx  --model_dir ppstructure/inference/master_table/ --model_filename inference.pdmodel --params_filename inference.pdiparams --opset_version 11 --save_file ppstructure/inference/master_table/master_table.onnx

- 完整报错/Complete Error Message：
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,tril_triu,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
