### ISSUE TITLE
ppocrlabel能否进行区域标注

### ISSUE THREAD

**Issue by superme3322** [PaddlePaddle/PaddleOCR#10389]
比如一张火车票，我只想要获取发车时间，在自动标注时能否将发车时间画个框，只对框内的发车时间进行自动标注。

**Comment by livingbody** [comment]
不能！

**Comment by ToddBear** [comment]
PPOCRLabel内置的自动标注工具针对的是一般文本，无法自动检测特定的文本框

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
