### ISSUE TITLE
[error] ocr图片解析加载报错

### ISSUE THREAD

**Issue by cffycls** [PaddlePaddle/PaddleOCR#10382]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

ocr图片解析加载报错。

- 系统环境/System Environment：
```
win11
python310
```
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- main.py
```python
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False, show_log=False)

result = ocr.ocr(img_path, cls=True)  # line 35
```
- 完整报错/Complete Error Message：
```shell
File "D: work\PaddleOCR\main. py”, 1ine 35, in read root
result = ocr.ocr(file path,cls=True)
File "C: \Users\Administrator\AppData\Llocal\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py”, line44,in ocr
img = check_img(img)
File "C: \Users\Administrator\AppData\Llocal\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py”, line38,in check_img
img = img_decode(img_str)
File "C: \Users\Administrator\AppData\Llocal\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py”,line22,in img_decode
return cv2.imdecode(np_arr, cv2.IMREAD COLOR)
cv2. error: OpenC(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave. cp:816: error: (-215:Asertion failed) !buf.empty() in function  cv::imdecode.

cv2. error: OpenC(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave. cp:816: error: (-215:Asertion failed) !buf.empty() in function  cv::imdecode_
```

**Comment by GreatV** [comment]
你的图片是空的

**Comment by cffycls** [comment]
你指的是图片地址无效，还是图片内容




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 中午1:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] [error] ocr图片解析加载报错 (Issue #10382)





 
你的图片是空的

**Comment by GreatV** [comment]
> 你指的是图片地址无效，还是图片内容

检查一下图片路径对不对，用绝对路径试试看。

**Comment by cffycls** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 中午1:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] [error] ocr图片解析加载报错 (Issue #10382)





  
你指的是图片地址无效，还是图片内容
  
检查一下图片路径对不对，用绝对路径试试看。
