### ISSUE TITLE
模型识别精度真的很低，有没有高精度一点的模型。

### ISSUE THREAD

**Issue by adminChina** [PaddlePaddle/PaddleOCR#10383]
中文识别精度真的很低啊，虽然框框都画出来了，但是能把溯和湖混淆。

- 版本号/Version："@paddle-js-models/ocr": "4.0.0"

**Comment by jingsongliujing** [comment]
你好，我这个是基于ppocr转的模型，重构了一遍推理，精度比直接安装的ppocrv3高：https://github.com/jingsongliujing/OnnxOCR

**Comment by WilliamQf-AI** [comment]
> 你好，我这个是基于ppocr转的模型，重构了一遍推理，精度比直接安装的ppocrv3高：https://github.com/jingsongliujing/OnnxOCR

你这个模型可以转换为飞桨的吗？现在的项目都是用飞桨推理的

**Comment by jingsongliujing** [comment]
不用转啊，可以平滑替代paddleocr



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月13日(周四) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 模型识别精度真的很低，有没有高精度一点的模型。 (Issue #10383)




  
你好，我这个是基于ppocr转的模型，重构了一遍推理，精度比直接安装的ppocrv3高：https://github.com/jingsongliujing/OnnxOCR
  
你这个模型可以转换为飞桨的吗？现在的项目都是用飞桨推理的

**Comment by WilliamQf-AI** [comment]
> 不用转啊，可以平滑替代paddleocr
> [...](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2023年7月13日(周四) 下午4:50 收件人： ***@***.***>; 抄送： ***@***.******@***.***>; 主题： Re： [PaddlePaddle/PaddleOCR] 模型识别精度真的很低，有没有高精度一点的模型。（问题 #10383） 你好，我这个是基于ppocr转的模型，重构了一遍推理，精度比直接安装的ppocrv3高：https://github.com/jingsongliujing/OnnxOCR 你这个模型可以转换为飞桨的吗？现在的项目都是用飞桨推理的 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您发表了评论。消息 ID： ***@***.***>

只用你这个模型啊

**Comment by GreatV** [comment]
> 精度比直接安装的ppocrv3高

你这为什么精度会比ppocrv3高，不是从原版导出的嘛，有什么优化吗？

**Comment by jingsongliujing** [comment]
我用的是crnn那个模型导出的，肯定比v3效果要好点



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年7月14日(周五) 上午10:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 模型识别精度真的很低，有没有高精度一点的模型。 (Issue #10383)




  
精度比直接安装的ppocrv3高
  
你这为什么精度会比ppocrv3高，不是从原版导出的嘛，有什么优化吗？
