### ISSUE TITLE
 这种效果怎么生成？styletext无效

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10385]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/abfcae0e-5494-44a3-878c-1ac60ca7f855)

**Comment by livingbody** [comment]
图看不见

**Comment by nissansz** [comment]
“https://user-images.githubusercontent.com/41010669/253277763-abfcae0e-5494-44a3-878c-1ac60ca7f855.png”

看得到啊

**Comment by z5229889frankwht** [comment]
可以尝试多搞点椒盐噪声

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
