### ISSUE TITLE
套件一致性计划

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/PaddleOCR#10380]
## 背景

经过需求征集https://github.com/PaddlePaddle/PaddleOCR/issues/10334 和每周技术研讨会 https://github.com/PaddlePaddle/PaddleOCR/issues/10223 讨论，我们发起套件一致性计划，通过提升套件一致性提升开发者在各大CV套件之间的知识迁移，和环境一致的效果，提升开发体验。

### 任务一（已完成）：
PaddleOCR与PaddleDetection与Pillow新版本10.x不兼容。目前PaddleOCR采用的临时解决方案是在依赖列表中限制只能使用旧版本Pillow（参见 https://github.com/PaddlePaddle/PaddleOCR/pull/10344 ），而PaddleDetection未采取任何措施（按照文档安装后，使用deploy/python/visualize.py等部分功能时会直接报错）。出于套件可持续建设的考虑，希望能够适配最新版本的Pillow。

任务一 解决步骤：
1. 解决PaddleOCR与PaddleDetection与Pillow新版本10.x不兼容的问题，即对于PaddleOCR和PaddleDetection，修改过时的接口名称或参数（例如FreeTypeFont.getsize），替换为等效的API调用；对于PaddleOCR，去除requirements.txt中Pillow版本的限制。实现替换Pillow为新版本10.x，运行所有代码不报错。
2. 分别提交代码到PaddleOCR和PaddleDetection。

PS：本任务视作两个任务，分别是解决PPOCR的依赖问题、解决PPDetection的依赖问题。

**Comment by livingbody** [comment]
直接PR吗？
就是替换下的问题。

**Comment by shiyutang** [comment]
PPOCR的替换已经通过：https://github.com/PaddlePaddle/PaddleOCR/pull/10405

**Comment by livingbody** [comment]
替换Pillow为最新版 https://github.com/PaddlePaddle/PaddleDetection/pull/8446
