### ISSUE TITLE
基于文本识别的微调数据集问题

### ISSUE THREAD

**Issue by izhaolinger** [PaddlePaddle/PaddleOCR#10384]
目前我用于识别身份证的过程中发现，在识别时，稍微生僻一些的字便会识别错误，为此我想将这些生僻字数据进行微调处理。

我参考了模型微调部分的文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md

其中有提到：“不更换字典的情况下，建议至少准备5000张的文本识别数据集用于模型微调；如果更换了字典（不建议），需要的数量更多。”

请问我是否可以只将遇到的问题生僻字，通过人工标注+程序生成的方式，按照文档的方式进行微调呢？还是说我需要在这些基础上再加入一些正常识别的数据呢？大概的数据量是什么样呢？是否真的大于5000张即可？

**Comment by liuhuan-gl** [comment]
同问

**Comment by liuhuan-gl** [comment]
这里的代码可以吗？https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/PP-OCRv3_det_train.md

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
