### ISSUE TITLE
训练中只显示eval进度条, 没有显示训练进度和指标情况

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#10393]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu22
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6  问题相关组件/Related components：tools/train.py
- 运行指令/Command Code： `python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
`
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/4a0265a5-e108-466a-bf61-78a7d6067463)

**Comment by livingbody** [comment]
看来batch size 要小鱼eval的数据流，我也学会了。

**Comment by livingbody** [comment]
看来batch size 要小鱼eval的数据流，我也学会了。

**Comment by shiyutang** [comment]
可以检查你的训练bs是否大于trainloader的长度，如果大于则不到一就进入eval。

**Comment by ericosmic** [comment]
> 可以检查你的训练bs是否大于trainloader的长度，如果大于则不到一就进入eval。
trainloader的长度在哪里设置呢？  配置文件里没有这个参数

**Comment by shiyutang** [comment]
trainloader的长度=数据集长度/训练bs，可以进入程序调试看到。

**Comment by ericosmic** [comment]
> trainloader的长度=数据集长度/训练bs，可以进入程序调试看到。

并没有，我的训练集330张, bs是8, 我把代码中logger改成print 就能显示训练指标，但是显示的也很奇怪，
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/1c7fdff5-5082-441f-b71b-50a695c0c762)
准确度和recall都没有增加

**Comment by shiyutang** [comment]
需要确认加载了预训练模型，否则数据量太小；同时可以多观察几个epoch，后面精度会提升

**Comment by ericosmic** [comment]
> 需要确认加载了预训练模型，否则数据量太小；同时可以多观察几个epoch，后面精度会提升

我用参数预训练模型试过，但是报错，配置文件没有pretrain_model这一项：
`python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints: paths/to/pretrain-model
`
提示模型没有pdopt, 无法加载optimizer .   训练KIE好像是可以自动下载预训练模型。 不需要指定预训练模型路径

**Comment by livingbody** [comment]
##  paths/to/pretrain-model  这个需要替换成你自己的。

> > 需要确认加载了预训练模型，否则数据量太小；同时可以多观察几个epoch，后面精度会提升
> 
> 我用参数预训练模型试过，但是报错，配置文件没有pretrain_model这一项： `python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints: paths/to/pretrain-model ` 提示模型没有pdopt, 无法加载optimizer . 训练KIE好像是可以自动下载预训练模型。 不需要指定预训练模型路径

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
