### ISSUE TITLE
如何训练的文档文字检测模型？

### ISSUE THREAD

**Issue by quix12345** [PaddlePaddle/PaddleOCR#10395]
请问paddleocr v3是如何训练的文字检测模型，我看大部分公开数据集都是场景文字检测相关的，没有文档文字检测的

不知道是否能够透露paddleocr v3是如何训练的文字检测模型，使用了哪些数据集？是否有自有的文字检测数据集呢

感谢！

**Comment by UserWangZz** [comment]
文档类识别可以在推出的检测模型上使用自己的数据微调。v3的训练数据暂时不对外开放
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
