### ISSUE TITLE
ch_ppocr_server_v2.0通用模型效果远差于PP-OCRv3模型

### ISSUE THREAD

**Issue by Aloaml** [PaddlePaddle/PaddleOCR#10399]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu 18.04.4 LTS

- 运行指令/Command Code：我把det和rec的server推理模型下载到本地，使用的是命令行操作,  paddleocr --image_dir=’1.pdf‘ --type=structure --table=false --ocr=true --det_db_score_mode=slow --det_model_dir='ch_ppocr_server_v2.0_det_infer' --rec_model_dir='ch_ppocr_server_v2.0_rec_infer' --use_dilation=True --output=’output/‘
- 
- [2023/07/14 12:29:49] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir='1.pdf', page_num=0, det_algorithm='DB', **det_model_dir='ch_ppocr_server_v2.0_det_infer'**, det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=True, det_db_score_mode='slow', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', **rec_model_dir='ch_ppocr_server_v2.0_rec_infer'**, rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, **rec_char_dict_path='/mnt/data0/home/zhoutianming/anaconda3/lib/python3.10/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt'**, use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=False, cls_model_dir=None, cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='output', table_max_len=488, table_algorithm='TableAttn', table_model_dir='/mnt/data0/home/zhoutianming/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer', merge_no_span_structure=True, table_char_dict_path='/mnt/data0/home/zhoutianming/anaconda3/lib/python3.10/site-packages/paddleocr/ppocr/utils/dict/table_structure_dict_ch.txt', layout_model_dir='/mnt/data0/home/zhoutianming/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_dict_path='/mnt/data0/home/zhoutianming/anaconda3/lib/python3.10/site-packages/paddleocr/ppocr/utils/dict/layout_dict/layout_cdla_dict.txt', layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=False, ocr=True, recovery=False, use_pdf2docx_api=False, lang='ch', det=True, rec=True, type='structure', ocr_version='PP-OCRv3', structure_version='PP-StructureV2')

识别内容是一本书的pdf扫描版本，对比如下（不知道为啥上不了图）
默认OCRv3模型：通常飞机零构件设计有以下几个主要步骤：1.研究零构件的具体要求零构件在整个绪构中的地位和功用，零构件所受
server通用模型：通飞机茶构件心养生理步装1研变零件的真体要求，零查件在整个结构中的地位和功用零查件所受的载荷性质m交变携

默认OCRv3模型：零构件工艺性可从儿方面考虑：1.工艺设备的可能性对工广和国内现有工艺水平和设备规格及加工可能性
server通用模型：禁构件工艺理奇从元方面考虑。1：宁艺设备的可能性，对工产和国内筑有工艺水平和设备规格及加工可能性

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
