### ISSUE TITLE
有个问题，crnn训练时，如果一个图片训练结果不正确，是不会写到模型的吧？只有正确结果才会更新到模型里？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10408]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

有个问题，crnn训练时，如果一个图片训练结果不正确，是不会写到模型的吧？只有正确结果才会更新到模型里？

**Comment by UserWangZz** [comment]
训练结果不正确，产生的训练loss就会变大，对模型的调整就会变多
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
