### ISSUE TITLE
训练识别模型时，中文字体好像许多直接支持日文，韩文， 这种很多都类似，不知道怎么挑选？不会全部扔进去吧？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10402]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/8bacacff-c4d7-46e9-bcc2-013a4e6d90bb)

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
