### ISSUE TITLE
styletext合成图片的问题

### ISSUE THREAD

**Issue by lqian** [PaddlePaddle/PaddleOCR#10407]
图片上有比较多的黑点，期望合成的文字也是黑色，背景仍然是黄色。
利用styletext合成后，出现了背景上的文字没有被清除干净，合成的文字是偏白色的。

请问是不是合同的素材不符合要求，或者需要设定styletext特定的参数，来达到预期的效果？

![fake_bg](https://github.com/PaddlePaddle/PaddleOCR/assets/2938324/3dd237b4-55bc-4015-8e59-efa1619defd1)
![fake_text](https://github.com/PaddlePaddle/PaddleOCR/assets/2938324/0c53d110-a753-4b00-9712-f0615088e0a6)
![fake_fusion](https://github.com/PaddlePaddle/PaddleOCR/assets/2938324/db27999a-9ce5-4fc2-b656-54583736c86e)

**Comment by UserWangZz** [comment]
感觉可以使用高斯模糊来处理一下背景图片达到目的。
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
