### ISSUE TITLE
paddleOCR能够识别这种双层车牌吗？

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#10401]
![1689481830843](https://github.com/PaddlePaddle/PaddleOCR/assets/74600923/e69180e9-569d-4857-b9ae-6832bdd00dd7)

如题，最近在做车牌识别任务，这种双层的车牌我试过了paddleOCR给的推理模型，发现并不能正确识别，不知识别算法能够处理这种双行文字识别吗？在训练数据中加入这种是否可以识别呢？

**Comment by BeyondYourself** [comment]
先看看检测对不对

**Comment by Lebron-Harden** [comment]
> 先看看检测对不对

检测是可以把整个车牌检测出来的，然后就是双层文本送进识别模块，识别不出来

**Comment by BeyondYourself** [comment]
双层车牌检测框应该是两个吧，如果检测没有问题，需要调整一下识别参数先看看效果

**Comment by livingbody** [comment]
> > 先看看检测对不对
> 
> 检测是可以把整个车牌检测出来的，然后就是双层文本送进识别模块，识别不出来

检测要的是把每行都检测出来，不时整个车牌。

**Comment by hellohahaw** [comment]
> ![1689481830843](https://private-user-images.githubusercontent.com/74600923/253785264-e69180e9-569d-4857-b9ae-6832bdd00dd7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTYwODMsIm5iZiI6MTcxMzQxNTc4MywicGF0aCI6Ii83NDYwMDkyMy8yNTM3ODUyNjQtZTY5MTgwZTktNTY5ZC00ODU3LWI5YWUtNjgzMmJkZDAwZGQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmE4OWQ2NmU0Mzc3NWQ1NmM2ZjYxZjc4ZGZmMGVjNGY5ZjgxYzZhNzU3MjlhNmYzZjg3NGY4YmY3ZDgxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDp84sbxw4yb-bJGtWl6-qwsaY7CuEs_LBClnR8_yFY)
> 
> 如题，最近在做车牌识别任务，这种双层的车牌我试过了paddleOCR给的推理模型，发现并不能正确识别，不知识别算法能够处理这种双行文字识别吗？在训练数据中加入这种是否可以识别呢？

请问您解决这个问题了吗？识别模型怎么修改才能支持双行车牌的识别呢？

**Comment by Lebron-Harden** [comment]
> > ![1689481830843](https://private-user-images.githubusercontent.com/74600923/253785264-e69180e9-569d-4857-b9ae-6832bdd00dd7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTYwODMsIm5iZiI6MTcxMzQxNTc4MywicGF0aCI6Ii83NDYwMDkyMy8yNTM3ODUyNjQtZTY5MTgwZTktNTY5ZC00ODU3LWI5YWUtNjgzMmJkZDAwZGQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmE4OWQ2NmU0Mzc3NWQ1NmM2ZjYxZjc4ZGZmMGVjNGY5ZjgxYzZhNzU3MjlhNmYzZjg3NGY4YmY3ZDgxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDp84sbxw4yb-bJGtWl6-qwsaY7CuEs_LBClnR8_yFY)
> > 如题，最近在做车牌识别任务，这种双层的车牌我试过了paddleOCR给的推理模型，发现并不能正确识别，不知识别算法能够处理这种双行文字识别吗？在训练数据中加入这种是否可以识别呢？
> 
> 请问您解决这个问题了吗？识别模型怎么修改才能支持双行车牌的识别呢？

就是检测模型得检测两个文本框，一上一下，再用识别模型逐行识别。识别模型一口气识别出两行的结果是不行的

**Comment by hellohahaw** [comment]
啊好吧，因为我看了一篇论文，说这种识别方法不依赖于从左到右的序列，看来是扯淡的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月19日 09:45 |
| 收件人 | ***@***.***> |
| 抄送至 | hello ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] paddleOCR能够识别这种双层车牌吗？ (Issue #10401) |


如题，最近在做车牌识别任务，这种双层的车牌我试过了paddleOCR给的推理模型，发现并不能正确识别，不知识别算法能够处理这种双行文字识别吗？在训练数据中加入这种是否可以识别呢？

请问您解决这个问题了吗？识别模型怎么修改才能支持双行车牌的识别呢？

就是检测模型得检测两个文本框，一上一下，再用识别模型逐行识别。识别模型一口气识别出两行的结果是不行的

**Comment by hellohahaw** [comment]
> > > ![1689481830843](https://private-user-images.githubusercontent.com/74600923/253785264-e69180e9-569d-4857-b9ae-6832bdd00dd7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTYwODMsIm5iZiI6MTcxMzQxNTc4MywicGF0aCI6Ii83NDYwMDkyMy8yNTM3ODUyNjQtZTY5MTgwZTktNTY5ZC00ODU3LWI5YWUtNjgzMmJkZDAwZGQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmE4OWQ2NmU0Mzc3NWQ1NmM2ZjYxZjc4ZGZmMGVjNGY5ZjgxYzZhNzU3MjlhNmYzZjg3NGY4YmY3ZDgxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDp84sbxw4yb-bJGtWl6-qwsaY7CuEs_LBClnR8_yFY)
> > > 如题，最近在做车牌识别任务，这种双层的车牌我试过了paddleOCR给的推理模型，发现并不能正确识别，不知识别算法能够处理这种双行文字识别吗？在训练数据中加入这种是否可以识别呢？
> > 
> > 
> > 请问您解决这个问题了吗？识别模型怎么修改才能支持双行车牌的识别呢？
> 
> 就是检测模型得检测两个文本框，一上一下，再用识别模型逐行识别。识别模型一口气识别出两行的结果是不行的

您好，我把单双行车牌都送到模型进行训练，发现是可以直接识别双行车牌的

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
