### ISSUE TITLE
KIE suggestion: implement a sliding window

### ISSUE THREAD

**Issue by lamaeldo** [PaddlePaddle/PaddleOCR#10404]
Hello, I have a suggestion to make on your implementation of the KIE (both for SER and RE tasks) algorithms: as the max token length is of 512 (because of BERT), and there are numerous cases in which people would like to train and infer on document over 512 tokens long, you could implement a [sliding window strategy](https://github.com/microsoft/unilm/issues/935#issuecomment-1345396729) whereby the input image (for training or inference) is sliced into chunks < 512 tokens (with some overlap between the chunks), before being fed to the network. For inference, once the chunks have been fed to the network, they are then merged again to provide the user with the results on the full image. I haven't seen any implementation of this in PaddleOCR, but PaddleSeg seems to have this [feature](https://github.com/PaddlePaddle/PaddleSeg/blob/6e696897f850b1ad5dc5a93a77e3dacf14e438ff/docs/apis/core.md?plain=1#L41).
I really think it could go a long way towards increasing the number of use cases for KIE with Paddle OCR.
Otheriwse, do youy know of any other way to process documents >512 tokens?

**Comment by ToddBear** [comment]
Thanks for your suggestion !

We have added this suggestion in our activity #10334 

Welcome to participate in our activity ！
