### ISSUE TITLE
怎样竖向识别文本

### ISSUE THREAD

**Issue by Fly-betterme** [PaddlePaddle/PaddleOCR#10414]
![image] (https://github.com/PaddlePaddle/PaddleOCR/assets/46836430/199215b2-86e8-40f1-a9bf-e829533410c1)

paddleocr有什么参数设置可以识别上图文字吗，按照标记的方式，竖向识别

**Comment by ToddBear** [comment]
可以试试版面分析相关的模型

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
