### ISSUE TITLE
有没有直接导出PDF文件为TXT文件？

### ISSUE THREAD

**Issue by cristianohello** [PaddlePaddle/PaddleOCR#10419]

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
