### ISSUE TITLE
训练SER 模型 precison和recall一直为0

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#10411]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
我使用新的关键字字典（39个关键词）和自制的数据集（330张训练数据），但训练过程中模型的准确度和召回率一直为0 。 
- 系统环境/System Environment：ubuntu18
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：tools/train.py
- 运行指令/Command Code：`python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml`
- 我的配置文件: 
- 
[ser_vi_layoutxlm_xfund_zh.txt](https://github.com/PaddlePaddle/PaddleOCR/files/12066742/ser_vi_layoutxlm_xfund_zh.txt)

- 完整报错/Complete Error Message：

- 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/ea9d93c2-7cad-4261-82e3-130f63c2c30a)

**Comment by ericosmic** [comment]
visualdl 中显示的结果如下， train没有记录precision和recall， eval中这两个数值一直是0
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/d4403b04-3f87-4fe2-b7a7-0d748f8918cf)

**Comment by BeyondYourself** [comment]
这个正常的，因为你设置的评估间隔太短了
`  eval_batch_step: [ 0, 4 ]`
把这个调大一些，调整为800试试看

**Comment by lxw316830** [comment]
解决了嘛这个问题

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
