### ISSUE TITLE
在linux下完成了cpp_infer模块的编译，做识别是只输出分值

### ISSUE THREAD

**Issue by gswgit** [PaddlePaddle/PaddleOCR#10415]
我在linux下完成了cpp_infer的编译，并且生成了ppocr这个可执行文件，我用自己训练的模型(验证码识别模型)验证，结果只输出分值，没有看到结果。以下是我的命令行参数：
ppocr --rec_model_dir=/root/work/model/inference --image_dir=/root/work/1234.jpg --rec=true --det=false --cls=false --rec_char_dict_path=/root/work/en_dict.txt --rec_batch_num=1

以下是运行后最后几行的输出：
I0717 08:19:51.983285   245 memory_optimize_pass.cc:216] Cluster name : batch_norm_5.tmp_4  size: 6144
I0717 08:19:51.983291   245 memory_optimize_pass.cc:216] Cluster name : conv2d_40.tmp_0  size: 6144
I0717 08:19:51.983297   245 memory_optimize_pass.cc:216] Cluster name : fill_constant_13.tmp_0  size: 4
I0717 08:19:51.983304   245 memory_optimize_pass.cc:216] Cluster name : conv2d_42.tmp_0  size: 6144
--- Running analysis [ir_graph_to_program_pass]
I0717 08:19:51.998948   245 analysis_predictor.cc:1007] ======= optimize end =======
I0717 08:19:51.999935   245 naive_executor.cc:102] ---  skip [feed], feed -> x
I0717 08:19:52.000926   245 naive_executor.cc:102] ---  skip [softmax_2.tmp_0], fetch -> fetch
predict img: /root/work/1234.jpg
 rec score: 0.989388 

缺少关键的验证码识别结果

**Comment by gswgit** [comment]
我只能说还有点不完善，通过修改Utility::print_result函数实现了结果打印

**Comment by gswgit** [comment]
以上只是自己调试的，可根据个人需求进行更改。整整花了我两天时间找原因。我修改的只是针对rec的，希望开发者能收录并进行修改

**Comment by livingbody** [comment]
最好是代码调用。

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
