### ISSUE TITLE
What type of OCR is better for US plate recognition?

### ISSUE THREAD

**Issue by bit-scientist** [PaddlePaddle/PaddleOCR#10413]
I am relatively new to the filed of OCR. I have been reading the book [Dive into OCR](https://paddleocr.bj.bcebos.com/ebook/Dive_into_OCR.pdf) provided here. It turns out the recogntion consists of two stages: text detection and text recognition. Well, there's also end-to-end approachs like PGNet, but they're not as good as 2-stage algorithms.
I happen to work on US plate recogntion where plates vary so much in terms of font, color and shape. 

See some samples below:
---
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26497571/c2ed4915-db44-464d-9153-2cb165d59f26)
---
**_I should note that these plates are available on the Web and am not sure if they are used nowadays._**
The texts mostly appear horizontally, but some have vertical text as well. I have'nt seen any curved texts so far.
What I am concerned about is what algorithms (text detector & text recognizer) work best on these types of plates.
With all the available algorithms for OCR (both detection & recognition) here, I am quite puzzled which one to choose for my case. I hope you could direct me to a narrower path so that I don't spend too much time on what might not work at the end. Thanks.

**Comment by ToddBear** [comment]
Here is a model that has been trained for Chinese license plate recognition, and you can refer to his design for US license plate recognition model. 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E8%BD%BB%E9%87%8F%E7%BA%A7%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB.md

**Comment by bit-scientist** [comment]
Thanks a ton @ToddBear. It looks like PP-OCRv3 worked quite well on CCPD. The part I'm struggling to understand: is PP-OCRv3 itself detection (and recogntion) model? Is PP-OCRv3 detailed in this [paper](https://arxiv.org/pdf/2206.03001.pdf)? Thanks again.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
