### ISSUE TITLE
如果要基于一个新的数据集训练SER模型，配置参数需要作怎样的调整

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#10436]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle： 2.3.2  PaddleOCR：2.6 问题相关组件/Related components：tools/train.py
- 运行指令/Command Code：
```
python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
        -o Architecture.Backbone.pretrained=./pretrained-model/ser/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
```

- 完整报错/Complete Error Message：因为需要从自己的文档中抽取关键信息，所以制作了自己的数据集，字典也和原来的字典完全不同， 使用官方提供的预训练模型ser_vi_layoutxlm_xfund_pretrained和配置参数ser_vi_layoutxlm_xfund_zh.yml进行训练， hmean一直为0，而且loss=nanxxx.  所以要基于一个新数据集和字典进行训练，需要对训练参数作怎样调整才能有好的训练效果呢？

**Comment by shiyutang** [comment]
要基于一个新的数据集训练SER模型并获得好的训练效果，您可以考虑以下调整训练参数的方法：

1. 数据准备：确保新的数据集与字典（类别映射文件）匹配，并且数据目录正确配置。
2. 类别数调整：根据新的数据集的类别数量，修改配置文件中的类别数。
3.  修改训练配置：根据新的数据集特点，可能需要对训练配置进行一些调整。例如，调整学习率、优化器、训练轮数等。
4.  预训练模型选择：选择合适的预训练模型作为初始化参数。根据新数据集的语言特征或领域特点，选择合适的预训练模型。
5. 检查输出：在训练过程中，检查输出日志以确定是否有错误或异常信息。如果出现loss为nan的情况，可能是由于数据集有问题，需要检查数据集的标注或数据格式。
6. 调整超参数：根据实际情况，可能需要对模型的超参数进行调整。例如，调整学习率、批大小、正则化参数等。
7. 迭代训练：如果初始训练效果不理想，可以尝试使用更大的训练集、调整其他参数或使用其他策略进行迭代训练。

总之，训练一个好的SER模型需要根据具体的数据集和任务进行调整和优化，以上是一些常见的调整方法，你可以根据实际情况进行尝试。

对于您提到的hmean为0且loss为nan的情况，可能是由于数据集问题或配置参数不合适导致的。建议您根据上述调整方法，针对您的新数据集和字典进行相应的参数调整，例如修改类别数、调整训练配置、选择合适的预训练模型等。此外，还可以检查数据集的标注或数据格式是否正确，并尝试调整模型的超参数，如学习率、批大小、正则化参数等。如果问题仍然存在，您可能需要进一步调整数据集和参数，或者使用其他策略进行迭代训练，以优化模型效果。
