### ISSUE TITLE
ppstructure在识别结果之后有没有办法裁切这个图片的不同模块出来,求大佬指教

### ISSUE THREAD

**Issue by 1042312930** [PaddlePaddle/PaddleOCR#10435]
ppstructure在识别结果之后有没有办法裁切这个图片的不同模块出来,求大佬指教

**Comment by WilliamQf-AI** [comment]
0.0，这不是已有的功能吗

**Comment by 1042312930** [comment]
> 0.0，这不是已有的功能吗

大佬是哪个方法能不能写一下,谢谢

**Comment by WilliamQf-AI** [comment]
> > 0.0，这不是已有的功能吗
> 
> 大佬是哪个方法能不能写一下,谢谢

你把那个demo好好看下，都在里面啊

**Comment by 1042312930** [comment]
解决了
