### ISSUE TITLE
paddleocr并行调用修改为串行调用

### ISSUE THREAD

**Issue by tgao** [PaddlePaddle/PaddleOCR#10434]
- 系统环境/System Environment：Atlas800 + OpenEuler +paddle2.2

由于硬件原因，需要将三个模型并行调用，修改为串行调用。使用模型为ch_ppocr_v2.0

1。我们onnxruntime分别调用三个模型后，输出结果是一个数组，我们不知道如何解析？
   尤其是det模型输出的结果的后处理；跟rec模型的预处理，咱们有较为清晰的示例吗？

**Comment by livingbody** [comment]
## 1.须知
ONNX Runtime (支持Paddle/ONNX两种格式模型， 支持CPU/GPU）

## 2.基于fastdeploy的ocr部署
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr

## 3.onnx或飞桨模型切换
FastDeploy/docs/cn/faq/how_to_change_backend.md at develop · PaddlePaddle/FastDeploy
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/how_to_change_backend.md

**希望以上信息对你有用！**

**Comment by tgao** [comment]
我们绕过了数组的解析，后处理维持使用paddle的cpu了。只把推理部分使用华为Npu
