### ISSUE TITLE
paddleocr无法使用

### ISSUE THREAD

**Issue by zerodq2019** [PaddlePaddle/PaddleOCR#10432]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/51385967/4d98ad57-78f5-4287-b424-58180ab74a04)
无论使用任何参数都会报错，请求帮助

**Comment by shiyutang** [comment]
numpy 版本不对，建议可以直接查找问题：https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool

**Comment by zerodq2019** [comment]
> numpy 版本不对，建议可以直接查找问题：https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool

谢谢。
我更换了一台电脑后成功使用了。
但是，请问如何将输出内容到txt或者excel中？我看--output参数没作用

**Comment by 1042312930** [comment]
> > numpy 版本不对，建议可以直接查找问题：https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool
> 
> 谢谢。 我更换了一台电脑后成功使用了。 但是，请问如何将输出内容到txt或者excel中？我看--output参数没作用

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/70195780/413c73b1-3ca2-4c7e-abae-a557d5a281bf)
