### ISSUE TITLE
PaddleOCR安卓项目相关问题

### ISSUE THREAD

**Issue by chunxia0202** [PaddlePaddle/PaddleOCR#10448]
您好，我在重现https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/android项目时，出现以下问题：
1.android\app\src\main\java\com\baidu\paddle\fastdeploy\app\examples\ocr\OcrMainActivity.java文件中需要导入这几个类：
    1.1 import com.baidu.paddle.fastdeploy.pipeline.PPOCRv3;
    1.2 import com.baidu.paddle.fastdeploy.vision.OCRResult;
    1.3 import com.baidu.paddle.fastdeploy.vision.Visualize;
    1.4 import com.baidu.paddle.fastdeploy.vision.ocr.Classifier;
    1.5 import com.baidu.paddle.fastdeploy.vision.ocr.DBDetector;
    1.6 import com.baidu.paddle.fastdeploy.RuntimeOption;
    1.7 import com.baidu.paddle.fastdeploy.vision.ocr.Recognizer;
但是github中的版本没有这几个文件，期待回复，感谢！

**Comment by GreatV** [comment]
你得先安装fastdeploy，参考 [在 Android 中使用 FastDeploy Java SDK](https://github.com/PaddlePaddle/FastDeploy/tree/develop/java/android)。

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

The above question has answered the question, welcome to reopen the question if there are any following issues. And we are now holding a contribution to Paddleseg and Paddle OCR activity, you are welcome to join:[#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
