### ISSUE TITLE
请问用PaddleOCR的ocr()函数识别时，如何保持原始pdf内容格式呢？

### ISSUE THREAD

**Issue by Hins** [PaddlePaddle/PaddleOCR#10440]
比如原始pdf文件有100页，ocr之后希望还有100页，同时每页内容尽量保持原始页的结构

**Comment by WilliamQf-AI** [comment]
我也在做这方面的事，但是效果我一言难尽，忍不住伤心，衡量不出爱与不爱之间的距离...

**Comment by Hins** [comment]
在保存文件时，用python-doc强制加分页符，能部分实现，但是每页内容相较原始pdf会错乱
