### ISSUE TITLE
如何修改paddle android demo 下默认的DBNet检测模型thresh参数跟box_thresh参数? 这是可以修改的吗? 我没有找到它们的位置

### ISSUE THREAD

**Issue by Micla-SHL** [PaddlePaddle/PaddleOCR#10445]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Micla-SHL** [comment]
android demo 默认的参数不是我想要的，我想修改他

**Comment by ToddBear** [comment]
参考 https://github.com/PaddlePaddle/PaddleOCR/blob/8967e633929cd38e03f72fa1658f49adc4330178/deploy/android_demo/README.md 

修改DBNet中threshold的方法为在 设置（Setting） → 输出设置 （Output Setting）中修改 Score Threshold

**Comment by Micla-SHL** [comment]
你好，你给的这参数应该是对应的box_thresh,它还是不能达成我想要的效果，我需要修改默认的thresh的值
________________________________
发件人: ToddBear ***@***.***>
发送时间: 2023年7月21日 10:01
收件人: PaddlePaddle/PaddleOCR ***@***.***>
抄送: Micla-SHL ***@***.***>; Author ***@***.***>
主题: Re: [PaddlePaddle/PaddleOCR] 如何修改paddle android demo 下默认的DBNet检测模型thresh参数跟box_thresh参数? 这是可以修改的吗? 我没有找到它们的位置 (Issue #10445)


参考 https://github.com/PaddlePaddle/PaddleOCR/blob/8967e633929cd38e03f72fa1658f49adc4330178/deploy/android_demo/README.md

修改DBNet中threshold的方法为在 设置（Setting） → 输出设置 （Output Setting）中修改 Score Threshold

―
