### ISSUE TITLE
Issue importing the packages from of PaddleOCR, draw_ocr

### ISSUE THREAD

**Issue by AGRocky** [PaddlePaddle/PaddleOCR#10443]
Hi folks, Great day to Y'all. Please try helping me out with this.
I'd try running paddleocr in google colab but getting issue importing the packages from of PaddleOCR, draw_ocr. Below is the error message.
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by joel1895** [comment]
I am also facing the same issue. It was working fine till yesterday, since today I am facing this error.

**Comment by AGRocky** [comment]
Exactly pls let me know if you find out anything.
Thank you

**Comment by joel1895** [comment]
I installed paddleocr gpu and it's working and much faster.

!pip install paddleocr
!python -m pip install paddlepaddle-gpu==2.5.0.post118 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by AGRocky** [comment]
Did it work?

**Comment by joel1895** [comment]
Worked for me

**Comment by GreatV** [comment]
Hi @AGRocky, You may try downgrading the paddle version to 2.4.2.

**Comment by AGRocky** [comment]
Hi @GreatV still it doesn't work!

**Comment by GreatV** [comment]
Hi @AGRocky, please refer: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by ChetnaLongani** [comment]
I had same error, its solved for me. Thank you so much.

**Comment by vicenteguedes** [comment]
> Hi @AGRocky, You may try downgrading the paddle version to 2.4.2.

Downgrading to 2.4.2 worked for me. Thank you!

**Comment by promaprogga** [comment]
[Errno 2] No such file or directory: 'PaddleOCR/ppstructure'
/content/PaddleOCR/ppstructure/inference
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 29, in <module>
    import tools.infer.predict_rec as predict_rec
  File "/content/PaddleOCR/tools/infer/predict_rec.py", line 28, in <module>
    import paddle
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file

i amgetting this error, let me give the line number codes
 File "/content/PaddleOCR/tools/infer/predict_rec.py", line 28, in <module>
import tools.infer.predict_rec as predict_rec
import tools.infer.predict_det as predict_det
import tools.infer.utility as utility
from tools.infer.predict_system import sorted_boxes
from ppocr.utils.utility import get_image_file_list, check_and_read
from ppocr.utils.logging import get_logger
from ppstructure.table.matcher import TableMatch
from ppstructure.table.table_master_match import TableMasterMatcher
from ppstructure.utility import parse_args
import ppstructure.table.predict_structure as predict_strture
 cant import those
 File "/content/PaddleOCR/tools/infer/predict_rec.py", line 28, in <module>
    import paddle
import tools.infer.utility as utility
from ppocr.postprocess import build_post_process
from ppocr.utils.logging import get_logger
from ppocr.utils.utility import get_image_file_list, check_and_read
like these. please help me to solve, i am trying in colab

**Comment by GreatV** [comment]
Hi @promaprogga, please refer: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by promaprogga** [comment]
but they have mentioned for ubuntu and i am using windows

**Comment by GreatV** [comment]
hi @promaprogga, You could try installing **libssl** on colab. Since your colab environment is UBUNTU.

**Comment by promaprogga** [comment]
Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.91.83|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-09-25 05:47:57 ERROR 404: Not Found.

dpkg: error: cannot access archive 'libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb': No such file or directory

**Comment by promaprogga** [comment]
Still getting same error, let me give you the code
!git clone https://github.com/PaddlePaddle/PaddleOCR.git
!pip install paddleocr --upgrade
!pip install paddlepaddle
%cd PaddleOCR/ppstructure

# download model
!mkdir inference
%cd inference
# Download the detection model of the ultra-lightweight table English OCR model and unzip it
!wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_det_infer.tar && tar xf en_ppocr_mobile_v2.0_table_det_infer.tar
# Download the recognition model of the ultra-lightweight table English OCR model and unzip it
!wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_rec_infer.tar && tar xf en_ppocr_mobile_v2.0_table_rec_infer.tar
# Download the ultra-lightweight English table inch model and unzip it
!wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_structure_infer.tar && tar xf en_ppocr_mobile_v2.0_table_structure_infer.tar

##New OCR Model
#!wget https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar && tar xf en_PP-OCRv3_det_infer.tar

!sudo apt-get install libssl1.1

!source /path/to/your/virtualenv/bin/activate
!pip install paddleocr
# run
%cd PaddleOCR/ppstructure
!python /content/PaddleOCR/ppstructure/table/predict_table.py --det_model_dir=inference/en_PP-OCRv3_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=/content/drive/MyDrive/SSCL/Code/Table/image --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ./content/drive/MyDrive/SSCL/Code/Table/output_paddle

**Comment by GreatV** [comment]
hi @promaprogga, This issue has been fixed in the paddle develop branch.

- https://github.com/PaddlePaddle/Paddle/pull/56555

You may now install the develop version to avoid this problem.

```
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html
```

**Comment by promaprogga** [comment]
Still error @GreatV 
[Errno 2] No such file or directory: 'PaddleOCR/ppstructure'
/content/PaddleOCR/ppstructure/inference/PaddleOCR/ppstructure
Traceback (most recent call last):
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 230, in <module>
    main(args)
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 153, in main
    table_sys = TableSystem(args)
  File "/content/PaddleOCR/ppstructure/table/predict_table.py", line 67, in __init__
    self.text_detector = predict_det.TextDetector(copy.deepcopy(
  File "/content/PaddleOCR/tools/infer/predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/content/PaddleOCR/tools/infer/utility.py", line 199, in create_predictor
    raise ValueError(
ValueError: not find model.pdmodel or inference.pdmodel in inference/en_PP-OCRv3_det_infer

**Comment by GreatV** [comment]
@promaprogga, This is another error, please check if the model file is placed correctly.

**Comment by promaprogga** [comment]
Everything is in correct place

**Comment by GreatV** [comment]
<img width="648" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/790b768f-0894-4c88-b8a0-32f60d729d3e">

Your `cd` command was not executed correctly.

**Comment by promaprogga** [comment]
# run
%cd /content/PaddleOCR/ppstructure
!python /content/PaddleOCR/ppstructure/table/predict_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=/content/drive/MyDrive/SSCL/Code/Table/image --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --output=/content/drive/MyDrive/SSCL/Code/Table/output_paddle
   it works but in csv there is no text

**Comment by risemeup1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/57147 This PR will sovle this problem，it will be megred tommorrow

**Comment by risemeup1** [comment]
@promaprogga @ChetnaLongani @AGRocky @joel1895

**Comment by maifeeulasad** [comment]
You *don't* face this issue on `Ubuntu < 22.04 LTS`

And on `Ubuntu 22.04 LTS`, there is a solution:
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb
```
ref: https://stackoverflow.com/a/73603200/10305444
