### ISSUE TITLE
PP-LCNetV3有相关论文吗

### ISSUE THREAD

**Issue by tengxniu** [PaddlePaddle/PaddleOCR#10446]
我在paddleclass里面只发现了PP-LCNetV2，请问PP-LCNetV3哪里可以查阅相关资料

**Comment by GreatV** [comment]
现在应该只有 PP-LCNetV2 吧，没有 PP-LCNetV3。

**Comment by tengxniu** [comment]
v4版本里面采用了PP-LCNetV3作为骨干网络

**Comment by GreatV** [comment]
v4还没release，等它release再来看看吧。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
