### ISSUE TITLE
FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by zjlw** [PaddlePaddle/PaddleOCR#10454]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：opensuse15.1 cpu 32g内存
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle2.3.2 
- 运行指令/Command Code：正常运行predict_det.py
- 完整报错/Complete Error Message：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   phi::KernelImpl<void (*)(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*), &(void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*))>::Compute(phi::KernelContext*)
6   void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*)
7   paddle::operators::math::Im2ColFunctor<(paddle::operators::math::ColFormat)0, phi::CPUContext, float>::operator()(phi::CPUContext const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, paddle::experimental::DataLayout)
8   void paddle::operators::math::im2col_common<float>(phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, paddle::experimental::DataLayout)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1689912245 (unix time) try "date -d @1689912245" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fbaf9bd8980) received by PID 9505 (TID 0x7fc1a5375700) from PID 18446744073604532608 ***]

描述：
我注释掉了predict_det.py第44行，因为预测效果更好。
# 'limit_side_len': args.det_limit_side_len,
在一些长宽比大的图片上会报上面那个错，
然后我debug测试，把ppocr/data/imaug/operators.py第222行的self.limit_side_len = 736 改为self.limit_side_len = 368，就不会报错，但是预测效果下降了，
有办法在self.limit_side_len = 736的时候不报错吗？

**Comment by livingbody** [comment]
## 请尝试 paddlepaddle2.4
## limit_side_len会resize图片大小，当然越大越好了

**Comment by zjlw** [comment]
这个应该不是paddlepaddle版本问题，我同事试过2.4版本的，问题在图片长宽比例较大时，resize会把长边拉得非常长，图片就特别的大，所以在跑cpu的时候，就会报错。但是限制limit_side_len的长度又会降低效果，
