### ISSUE TITLE
cannot import name 'RNNCell' from 'paddle.fluid.layers'

### ISSUE THREAD

**Issue by X17exe** [PaddlePaddle/PaddleOCR#10453]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10

- 版本号/Version：Paddle：2.5.0  PaddleOCR：2.6.1.3  PaddleHub: 2.3.1 问题相关组件/Related components：看起来似乎PaddleHub调用PaddlePaddle出错

- 运行指令/Command Code：
from paddle.fluid.layers import RNNCell, LSTMCell, rnn, BeamSearchDecoder, dynamic_decode

- 完整报错/Complete Error Message： 
File "D:\Anaconda\envs\ppenv\lib\site-packages\paddlehub\compat\task\text_generation_task.py", line 22, in <module>
    from paddle.fluid.layers import RNNCell, LSTMCell, rnn, BeamSearchDecoder, dynamic_decode
ImportError: cannot import name 'RNNCell' from 'paddle.fluid.layers' (D:\Anaconda\envs\ppenv\lib\site-packages\paddle\fluid\layers\__init__.py)

**Comment by coleflowers** [comment]
有同样问题～
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS 13.4.1 

- 版本号/Version：Paddle：2.5.0  

- 运行指令/Command Code：
```
hub install chinese_ocr_db_crnn_server==1.2.0 
```
这个也会报错
```
hub --version
```

完整报错/Complete Error Message：
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/__init__.py", line 54, in <module>
    from paddlehub.compat.task.text_generation_task import TextGenerationTask
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/compat/task/text_generation_task.py", line 22, in <module>
    from paddle.fluid.layers import RNNCell, LSTMCell, rnn, BeamSearchDecoder, dynamic_decode
ImportError: cannot import name 'RNNCell' from 'paddle.fluid.layers' (/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/layers/__init__.py)

**Comment by livingbody** [comment]
## 注意：
- 该API是适配PaddlePaddle 1.8版本的，2.X已经没有该版本了，PaddleHub该模块滞后，不建议使用。

**Comment by livingbody** [comment]
![360截图20230722213707754](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/ab493638-faa9-47fb-9b02-15e7d92324fe)

**Comment by coleflowers** [comment]
> ## 注意：
> * 该API是适配PaddlePaddle 1.8版本的，2.X已经没有该版本了，PaddleHub该模块滞后，不建议使用。

正在根据这篇文档的指引搭建环境：https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/get_start/mac_quickstart.md
环境没搭成功，还没开始写代码。

**Comment by lycfight** [comment]
> ## 注意：
> * 该API是适配PaddlePaddle 1.8版本的，2.X已经没有该版本了，PaddleHub该模块滞后，不建议使用。

那是不建议用PaddleHub吗？我想自定义一个版面分析+OCR的pieline，推理服务部署用什么？

**Comment by lycfight** [comment]
> ## 注意：
> * 该API是适配PaddlePaddle 1.8版本的，2.X已经没有该版本了，PaddleHub该模块滞后，不建议使用。

那是不建议用PaddleHub吗？我想自定义一个版面分析+OCR的pieline，推理服务部署用什么

**Comment by Neloy262** [comment]
I faced the same problem with paddlepaddle version 2.5.0. I changed to version 2.4.2 and now it works.

**Comment by XksA-me** [comment]
目前测试下来，最新兼容版本是：paddlehub 2.3.1、paddlepaddle-gpu 2.4.2

我使用的环境是矩池云 CUDA 11.7 环境，预装：Ubuntu20.04, Python 3.9, CUDA 11.7, cuDNN 8, NVCC, VNC等。

![](https://files.mdnice.com/user/2046/a5eb4fc5-d360-4373-aec3-a285234771f2.png)

启动机器后，打开 Jupyterlab，新建一个 Terminal，依次输入下面指令安装环境：
```bash
# 安装 gpu 版本 paddlepaddle
python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
# 安装最新版本 paddlehub
pip install paddlehub -i https://mirror.baidu.com/pypi/simple
# 升级依赖包
pip install typing-extensions --upgrade
```
然后新建一个`notebook`，就可以正常使用了。
```python
import paddle
print(paddle.utils.run_check())

import paddlehub as hub

lac = hub.Module(name="lac")
test_text = ["今天是个好天气。"]

results = lac.cut(text=test_text, use_gpu=False, batch_size=1, return_tag=True)
print(results)
#{'word': ['今天', '是', '个', '好天气', '。'], 'tag': ['TIME', 'v', 'q', 'n', 'w']}
```

![](https://files.mdnice.com/user/2046/deaaa592-0306-48f0-83f4-38923f12e5c6.png)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by zhanglong2100** [comment]
paddleHub使用可以参考这篇文章，里面有解决这个问题的方法https://www.cnblogs.com/barros/p/18061216#%E5%9F%BA%E7%A1%80%E7%8E%AF%E5%A2%83
