### ISSUE TITLE
更换主干网络注意力模块后报错

### ISSUE THREAD

**Issue by H-eaven-1** [PaddlePaddle/PaddleOCR#10458]
使用的是MobileNet_V3网络，想尝试一下ECA模块的效果。更换原始SE模块后，训练以及训练过程中的自动评估都没问题。但导出推理模型后再进行预测出现以下报错：
InvalidArgumentError: The expanded size (-1) for non-existing dimensions must be positive for expand_as_v2 op.
      [Hint: Expected target_shape[i] > 0, but received target_shape[i]:-1 <= 0:0.] (at ../paddle/phi/kernels/impl/expand_as_kernel_impl.h:49)
      [operator < expand_as_v2 > error]

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
