### ISSUE TITLE
【论文复现】轻量语义分割网络PIDNet

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/PaddleOCR#10450]
## 背景

经过需求征集https://github.com/PaddlePaddle/PaddleOCR/issues/10334 和每周技术研讨会 https://github.com/PaddlePaddle/PaddleOCR/issues/10223 讨论，我们确定了【论文复现】轻量语义分割网络PIDNet 任务。

## 解决步骤
1. 数据和模型、代码均已经开源。
2. 根据开源代码进行网络结构、评估指标转换。代码链接：https://github.com/XuJiacong/PIDNet
3. 结合[论文复现指南](https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/article-implementation/ArticleReproduction_CV.md)，进行前反向对齐等操作，达到论文Table.6中的指标。
4. 参考[PR提交规范](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/style_cn.md)提交代码PR到[ppseg](https://github.com/PaddlePaddle/PaddleSeg/tree/develop)中。

**Comment by daoqiugsy** [comment]
认领
