### ISSUE TITLE
有的单个字符，比如  -， 识别出来可能是nan，这种怎么识别比较好

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10459]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 
- 版本号/Version：Paddle：  PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

有的单个字符，比如  -， 识别出来可能是nan，这种怎么识别比较好

**Comment by ToddBear** [comment]
可以提供一下具体的输入图片以及对应的识别结果吗？

**Comment by nissansz** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/20d3f43d-3aed-4449-a9ee-2408d6e49d01)
识别结果就是空，没结果。

**Comment by ToddBear** [comment]
我尝试了一下，发现一行文本中只有单个 '_', '-', '/', '.' 的字符就容易出现识别不出的情况，猜测原因是默认的SVRT_LCNet识别方法在特征提取时会进行上下文信息的融合，导致文字区域的特征被空白区域的特征"污染"，进而使其被识别为空白区域。

当我尝试将空白区域的范围缩小，该字符就能正确识别出来了

可以先进行文字的检测，只保留图片文字区域，再进行识别

**Comment by nissansz** [comment]
缩小范围可以识别正确，但是acc显示只有0.2，不知道这个准确率还能不能改善，有没有影响

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by failable** [comment]
单个数字也无法识别。

<img width="150" alt="image" src="https://github.com/user-attachments/assets/b5ba3168-5fb2-4957-a22b-616b0597d74b">
