### ISSUE TITLE
请问可以将模型转为.pth文件吗？

### ISSUE THREAD

**Issue by HGGshiwo** [PaddlePaddle/PaddleOCR#10462]
我看了下源码，发现在paddle/inference/__init__.py里面导入的create_predictor再往下就找不到了
```
from paddle.fluid.core import (
    create_predictor,
    get_version,
    _get_phi_kernel_name,
    get_trt_compile_version,
    get_trt_runtime_version,
    get_num_bytes_of_data_type,
    PredictorPool,
)
```

好像是用到了paddlea的运行库，想问下可以把paddlev3模型转为pt文件吗？感谢回复！

**Comment by shiyutang** [comment]
你好，我不太确定你的问题是什么意思，就我的理解pth文件应该是torch的模型文件，如果需要转换可以将权重进行转换后重新加载成torch模型。另外你提到的paddlev3和paddlea我都不知道是什么
