### ISSUE TITLE
paddlepaddle对Nvidia 3090显卡支持问题

### ISSUE THREAD

**Issue by octaviawfx** [PaddlePaddle/PaddleOCR#1046]
一个服务器上，同时安装了Nvidia 2070 super显卡和Nvidia 3090显卡，安装paddle paddle之后，在2070s显卡上可正常使用，如下图所示：

paddle.fluid.install_check.run_check()
Running Verify Paddle Program ...
W1028 18:11:05.836931 11559 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W1028 18:11:05.839093 11559 device_context.cc:245] device: 0, cuDNN Version: 7.5.
W1028 18:11:05.839110 11559 device_context.cc:271] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Your Paddle works well on SINGLE GPU or CPU.
I1028 18:11:07.455816 11559 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I1028 18:11:07.456137 11559 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I1028 18:11:07.456391 11559 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1028 18:11:07.456578 11559 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Your Paddle works well on MUTIPLE GPU or CPU.
Your Paddle is installed successfully! Let's start deep Learning with Paddle now

但是在3090显卡上验证的时候，却一直卡住，不出结果，如下：

Running Verify Paddle Program ...
W1028 18:04:00.730057 10037 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.1, Runtime API Version: 10.0
W1028 18:04:00.732218 10037 device_context.cc:245] device: 0, cuDNN Version: 7.5.
W1028 18:04:00.732234 10037 device_context.cc:271] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

**Comment by LDOUBLEV** [comment]
把这个issue转到[PaddlePaddle](https://github.com/PaddlePaddle/Paddle/issues) repo下吧，

**Comment by LDOUBLEV** [comment]
刚咨询了下，暂时不支持新架构

**Comment by octaviawfx** [comment]
> 刚咨询了下，暂时不支持新架构
> 
> 可以在paddlepaddle repo下提个issue咨询更详细的信息

好的，多谢

**Comment by octaviawfx** [comment]
With CUDA11.1 cudnn8 and paddlepaddle-gpu==2.0.0rc1.post110, the inference time per img(MY TESTSET) is :
0.32831 seconds in nvidia 3090; 
0.20 seconds  in nvidia 2070s;
0.11153 seconds  in nvidia 2080ti.

PS:I can not say I'm absolutely sure I did everything right
