### ISSUE TITLE
在同样模型下，PaddleOCR的识别效果比PPStructure的要好，不会出现漏识别，不知道是什么原因导致的

### ISSUE THREAD

**Issue by wxzwxz131** [PaddlePaddle/PaddleOCR#10468]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WilliamQf-AI** [comment]
可以动态设置SetMaxSideLen，值为图片最大边长，同时SetDetDBUnclipRatio使用默认值1.5效果最好，SetUseDilation可以开启。

**Comment by wxzwxz131** [comment]
> 可以动态设置SetMaxSideLen，值为图片最大边长，同时SetDetDBUnclipRatio使用默认值1.5效果最好，SetUseDilation可以开启。

这些都有试过，就是发现PaddleOCR比使用PPStructure要识别准确，不会出现漏0的问题，不知道是哪边设置是不同的，设置均采用默认设置的情况下

**Comment by shiyutang** [comment]
请问能否提供图片和更多执行命令呢？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
