### ISSUE TITLE
paddleocr GPU识别乱码 CPU识别正常

### ISSUE THREAD

**Issue by 666echo** [PaddlePaddle/PaddleOCR#10464]
显卡驱动 11.7
CUDA 11.7 
cudnn 8.5.0.96
paddlepaddle-gpu 2.5.0.post117 
paddleocr  2.6.1.3

加载使用gpu就会出现乱码，繁体等，而且目标很多 使用cpu就不会出现 这个如何解决呢 
然后安装paddlepaddle-gpu 2.4.2.post117 他就可以使用gpu 推理，但是他无法使用paddlenlp训练 2.4没有get_rng_state这个函数
我想使用最新版的 我应该如何解决这个问题

**Comment by thinking24k** [comment]
一样的环境，我也出现了这样的乱码。

**Comment by a943512** [comment]
我也碰到了这种情况，不知道该如何解决

**Comment by Flywolfs** [comment]
我也是，显卡4060，cuda10.2，cudnn7.6，出现GPU推理推不正确，乱码和繁体，CPU推理就正常。另外我用2080ti显卡在cuda10.2和cudnn7.6上就推理正常，结果正常，和CPU结果一样，很奇怪，希望官方给个解决方案

**Comment by Flywolfs** [comment]
> 我也是，显卡4060，cuda10.2，cudnn7.6，出现GPU推理推不正确，乱码和繁体，CPU推理就正常。另外我用2080ti显卡在cuda10.2和cudnn7.6上就推理正常，结果正常，和CPU结果一样，很奇怪，希望官方给个解决方案

已经解决，将CUDA升级到11.2就行了，4060 compute capability 8.5, 10.2的cuda不支持

**Comment by alanxinn** [comment]
我也是乱码 显卡1060 cuda12.0 cudnn8.8，gpu推理乱码，cpu推理正常

**Comment by Durian-leader** [comment]
> 我也是乱码 显卡1060 cuda12.0 cudnn8.8，gpu推理乱码，cpu推理正常，再试多几个版本
> hh
>  win10 专业版 22H2 paddlepaddle-gpu==2.3.2 cuda==10.1 cudnn==7.6.5 paddleocr==2.6.0 成功推理，不出现乱码

那不是就不能用最新的模型了

**Comment by alanxinn** [comment]
> > 我也是乱码 显卡1060 cuda12.0 cudnn8.8，gpu推理乱码，cpu推理正常，再试多几个版本
> > hh
> > win10 专业版 22H2 paddlepaddle-gpu==2.3.2 cuda==10.1 cudnn==7.6.5 paddleocr==2.6.0 成功推理，不出现乱码
> 
> 那不是就不能用最新的模型了

我可以用v4啊 不影响吧

**Comment by Durian-leader** [comment]
> > > 我也是乱码 显卡1060 cuda12.0 cudnn8.8，gpu推理乱码，cpu推理正常，再试多几个版本
> 
> > > hh
> 
> > > win10 专业版 22H2 paddlepaddle-gpu==2.3.2 cuda==10.1 cudnn==7.6.5 paddleocr==2.6.0 成功推理，不出现乱码
> 
> > 
> 
> > 那不是就不能用最新的模型了
> 
> 
> 
> 我可以用v4啊 不影响吧

哦哦哦，那就好。我又看了那个paddleocr说明文档，里面写了推荐非安培架构的gpu用10.2的，我的tesla p4 就是非安培架构，用10.2可以跑

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
