### ISSUE TITLE
按照官方教程启动paddle serving 的ocr多模型串联部署代码 预测是发生错误。

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/PaddleOCR#1047]
2020-10-28 21:34:45,182-ERROR: Exception on /ocr/prediction [POST]
Traceback (most recent call last):
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 180, in run
    return self.get_prediction(request)
  File "/ml/home/yanguangqing/.local/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 144, in get_prediction
    request.json["fetch"])
  File "ocr_rpc_server.py", line 94, in preprocess
    feed, fetch, self.tmp_args = self.text_system.preprocess(im)
  File "ocr_rpc_server.py", line 55, in preprocess
    outputs = [fetch_map[x] for x in fetch]
  File "ocr_rpc_server.py", line 55, in <listcomp>
    outputs = [fetch_map[x] for x in fetch]
TypeError: 'NoneType' object is not subscriptable
2020-10-28 21:34:45,182-INFO: 127.0.0.1 - - [28/Oct/2020 21:34:45] "POST /ocr/prediction HTTP/1.1" 500 -
环境均按照官网配置

**Comment by natureLanguageQing** [comment]
(paddleGPU) [yanguangqing@localhost pdserving]$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by natureLanguageQing** [comment]
conda list
# packages in environment at /ml/home/yanguangqing/.conda/envs/paddleGPU:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
appdirs                   1.4.4                     <pip>
astor                     0.8.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
attrs                     20.2.0                    <pip>
Babel                     2.8.0                     <pip>
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
brotlipy                  0.7.0           py36h7b6447c_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2020.7.22                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cairo                     1.14.12              h8948797_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.6.20                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.14.0           py36h2e261b9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cfgv                      3.2.0                     <pip>
chardet                   3.0.4                 py36_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
click                     7.1.2                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
clickclick                1.2.2                     <pip>
cma                       3.0.3                     <pip>
colorlog                  4.2.1                     <pip>
connexion                 2.7.0                     <pip>
cryptography              3.1              py36h1ba5d50_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               10.0.130                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudnn                     7.6.5                cuda10.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dbus                      1.13.16              hb2f20db_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
decorator                 4.4.2                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
distlib                   0.3.1                     <pip>
expat                     2.2.9                he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ffmpeg                    4.0                  hcdf2ecd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
filelock                  3.0.12                    <pip>
flake8                    3.8.3                     <pip>
Flask                     1.1.2                     <pip>
Flask-Babel               2.0.0                     <pip>
Flask-Cors                3.0.9                     <pip>
fontconfig                2.13.0               h9420a91_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freeglut                  3.0.0                hf484d3e_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freetype                  2.10.2               h5ab3b9f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
fribidi                   1.0.10               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.4.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.3.3                     <pip>
glib                      2.63.1               h5a9c865_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
graphite2                 1.3.14               h23475e2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
graphviz                  0.14.1                    <pip>
graphviz                  2.40.1               h21bd128_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
grpcio                    1.32.0                    <pip>
grpcio-tools              1.32.0                    <pip>
gst-plugins-base          1.14.0               hbbd80ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gstreamer                 1.14.0               hb453b48_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gunicorn                  20.0.4                    <pip>
harfbuzz                  1.8.8                hffaf4a1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hdf5                      1.10.2               hba1933b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
icu                       58.2                 he6710b0_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
identify                  1.5.2                     <pip>
idna                      2.10                       py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
imageio                   2.9.0                     <pip>
imgaug                    0.4.0                     <pip>
importlib-metadata        1.7.0                     <pip>
importlib-resources       3.0.0                     <pip>
inflection                0.5.1                     <pip>
intel-openmp              2020.2                      254    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
itsdangerous              1.1.0                     <pip>
jasper                    2.0.14               h07fcdf6_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Jinja2                    2.11.2                    <pip>
joblib                    0.16.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jpeg                      9b                   h024ee3a_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jsonschema                3.2.0                     <pip>
kiwisolver                1.2.0            py36hfd86e86_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lcms2                     2.11                 h396b838_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.33.1               h53a641e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20191231         h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libglu                    9.0.0                hf484d3e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libopencv                 3.4.2                hb342d67_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libopus                   1.3.1                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.12.4               hd408876_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.1.0                h2733197_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuuid                   1.0.3                h1bed415_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libvpx                    1.7.0                h439df22_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libxcb                    1.14                 h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libxml2                   2.9.10               he19cac6_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lmdb                      1.0.0                     <pip>
lz4-c                     1.9.2                he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
MarkupSafe                1.1.1                     <pip>
matplotlib                3.3.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib-base           3.3.1            py36h817c723_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mccabe                    0.6.1                     <pip>
mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py36he904b0f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.1.0            py36h23d657b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py36h0573a6f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ncurses                   6.2                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  2.5                       <pip>
nltk                      3.5                        py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nodeenv                   1.5.0                     <pip>
numpy                     1.19.1           py36hbc911f0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.19.1           py36hfa32c7d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.46                       py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openapi-spec-validator    0.2.9                     <pip>
opencv                    3.4.2            py36h6fd60c2_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-python             4.2.0.32                  <pip>
openssl                   1.1.1g               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
paddle-serving-app        0.1.2                     <pip>
paddle-serving-client     0.3.2                     <pip>
paddle-serving-server     0.3.1                     <pip>
paddle-serving-server-gpu 0.3.2.post10              <pip>
paddlehub                 1.8.2                     <pip>
paddleocr                 0.0.3.1                   <pip>
paddlepaddle              1.8.4                     <pip>
paddlepaddle-gpu          1.8.4           py36_gpu_cuda10.0_many_linux    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle
paddlepaddle-gpu          1.8.5.post107             <pip>
pandas                    1.1.2                     <pip>
pango                     1.42.4               h049681c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pathlib                   1.0.1                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pcre                      8.44                 he6710b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    7.2.0            py36hb39fc2d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       20.2.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pixman                    0.40.0               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pre-commit                2.7.1                     <pip>
protobuf                  3.12.4           py36he6710b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py-cpuinfo                5.0.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py-opencv                 3.4.2            py36hb342d67_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyclipper                 1.2.0                     <pip>
pycodestyle               2.6.0                     <pip>
pycparser                 2.20                       py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyflakes                  2.2.0                     <pip>
pyopenssl                 19.1.0                     py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 2.4.7                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyqt                      5.9.2            py36h05f1152_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyrsistent                0.17.3                    <pip>
pysocks                   1.7.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.6.10               hcf32534_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytz                      2020.1                    <pip>
PyWavelets                1.1.1                     <pip>
pyyaml                    5.3.1            py36h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
qt                        5.9.7                h5867ecd_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  8.0                  h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
regex                     2020.7.14        py36h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.24.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scikit-image              0.17.2                    <pip>
scipy                     1.5.2            py36h0b6359f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.3.1                     <pip>
sentencepiece             0.1.92                    <pip>
setuptools                49.6.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Shapely                   1.7.1                     <pip>
sip                       4.19.8           py36hf484d3e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.33.0               h62c20be_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
swagger-ui-bundle         0.0.8                     <pip>
tifffile                  2020.9.3                  <pip>
tk                        8.6.10               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
toml                      0.10.1                    <pip>
tornado                   6.0.4            py36h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.48.2                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.25.10                    py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
virtualenv                20.0.31                   <pip>
visualdl                  2.0.3                     <pip>
Werkzeug                  1.0.1                     <pip>
wheel                     0.35.1                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yaml                      0.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yapf                      0.26.0                    <pip>
zipp                      3.1.0                     <pip>
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.4.5                h9ceee32_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by MissPenguin** [comment]
今天paddle serving部署会更新一版，可以等晚点更新完毕后再尝试
