### ISSUE TITLE
运行PPOCRLabel时报错

### ISSUE THREAD

**Issue by X17exe** [PaddlePaddle/PaddleOCR#10474]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Windows 10
- 版本号/Version：Paddle：2.5.0  PaddleOCR：2.6.1.3
问题相关组件/Related components： PPOCRLabel
- 运行指令/Command Code： PPOCRLabel --lang ch --kie True
- 完整报错/Complete Error Message：
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by HappyBruce1** [comment]
删除掉一个libiomp5md.dll文件

**Comment by X17exe** [comment]
> 删除掉一个libiomp5md.dll文件

这个文件在哪个目录呢？

**Comment by UserWangZz** [comment]
如果是conda环境在conda env中查找对应环境下是否有重复的dll文件
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
