### ISSUE TITLE
这种图片好像容易识别错误，需要获得该字体，再加入数据集针对训练通用模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10472]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

这种图片好像容易识别错误，需要获得该字体，再加入数据集针对训练通用模型？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/ff3544bb-8b79-4f6f-809b-310723227541)

**Comment by shiyutang** [comment]
是的，对于这种容易识别错误的图片，可以通过获得相应的字体并将其加入数据集来训练通用模型。这样可以提高模型对特定字体的识别准确性

**Comment by nissansz** [comment]
要怎么找到各种字体？

**Comment by nissansz** [comment]
这里面好像字体很少。

另外有个问题，带点数字要怎么准备数据？目前小数点容易丢失

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/889717cc-808b-4bd7-8e86-28a875f8491c)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
