### ISSUE TITLE
古籍文字能直接用Unicode吗？

### ISSUE THREAD

**Issue by hooyia123** [PaddlePaddle/PaddleOCR#10478]
问题：
手头有一大批电子古籍，上面的文字需要识别，但是PPOCR只能识别一般的简体且横排，对于竖排不是很友好。基本情况：
1，要识别的电子古籍上的汉语文字是竖排的
2，常用汉字字典只有8.4k个，不能满足需要，而汉语古籍中的常用汉字有2万+（大概有10万字），由于有一部分不常见的汉字没有相应汉字显示，都显示为□。于是，我想能不能直接用\u23ed之类的Unicode？
3，手上有1000页可用于PPOCR训练的古籍数据集——文字检测练数据格式满足PPOCR文字检测数据格式要求、文字识别数据格式也满足PPOCR文字识别数据格式要求。为便于Unicode识别，我把（1）文字检测数据集里的汉字都转成\u23ed之类的Unicode了、（2）文字识别数据集里的汉字都转成\u23ed之类的Unicode了、（3）修改了数据字典，将默认的PaddleOCR/ppocr/utils/dict/chinese_cht_dict.txt自行扩充到了22000字，且数据字典也用一排一个类似\u23ed的Unicode

操作处理：
1，按照GitHub上PPOCR的步骤，部署了PPOCR的环境，且用小批量数据进行文字检测（从https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_distill_train.tar下载检测的预训练模型）、文字识别训练（https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_train.tar）的全流程都走通了。开始大规模训练。

2，关于竖排汉字检测训练
配置好configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml，epoch设定为100次，运行
python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Optimizer.base_lr=0.0001
一切都正常。
但是precision一直在0.5左右徘徊：ppocr INFO: best metric, hmean: 0.3497888250363498, is_float16: False, precision: 0.5123732251521298, recall: 0.26553137811415956, fps: 3.167201742626068, best_epoch: 37, start_epoch: 28

3，关于竖排汉字识别训练
查看了之前关于竖排汉字识别问题的讨论与指导，解答是：能识别竖排，需要将切好的竖排逆时针旋转90度，我这边也按照要求进行了逆时针旋转。配置好configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml，运行
python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
运行正常，且acc=0.9999

4, 调用已经训练过的模型进行推理测试，检测是横竖交错，文字识别没有数据结果，见图。不清楚原因。
![Uploading image_821.jpg…]()

![image_823](https://github.com/PaddlePaddle/PaddleOCR/assets/140177014/248cf422-9145-4b25-a7f2-920940d6dc39)

请问：
（1）将汉字转成Unicode，并用Unicode字典进行文字检测、文字识别，可行吗？
（2）为什么检测是横竖交错，文字识别没有数据结果？问题处在哪儿呢？
（3）用PPOCR成功进行古籍竖排文字识别且效果好的项目，有成功的案例吗？能否指导一二，我的微信hooyia123，敬请各位大神赐教

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
