### ISSUE TITLE
请问文本检测、表格识别的时候，是否可以通过某个参数使得检测框为矩形框

### ISSUE THREAD

**Issue by wxzwxz131** [PaddlePaddle/PaddleOCR#10471]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by ToddBear** [comment]
文本检测中的"det_box_type"设置为quad时即可返回矩形检测框，设置为"poly"则返回多边形检测框。

**Comment by wxzwxz131** [comment]
> 

收到 谢谢
