### ISSUE TITLE
PPStructure Layout Restoration 的一些问题

### ISSUE THREAD

**Issue by skwskwskwskw** [PaddlePaddle/PaddleOCR#10479]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows x64
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：ppstructure
- 运行指令/Command Code：paddleocr --image_dir=file.pdf --type=structure --recovery=true --use_pdf2docx_api=true
- 完整报错/Complete Error Message：

一些页面没有完整输出； 边缘的部分不见了； 
Microsoft word 看不到完整的 docx file， 可是WPS office 可以；

**Comment by similang** [comment]
看到有人表示，可以逐页排查，具体怎么做？

**Comment by mllife** [comment]
@similang , if you can supply the model with individual page images, add padding to them around all borders, the detection will work better. I think the issue happens as the model tries to crop the input page to fit the input layer, so adding padding can help.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
