### ISSUE TITLE
ocr = PaddleOCR() 如何使用自定義數據訓練後的模型

### ISSUE THREAD

**Issue by TonTonTWMAN** [PaddlePaddle/PaddleOCR#10487]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：HuggingFace Space
- 版本号/Version：
  - Paddle：  2.4.2 
  - PaddleOCR： 2.6
- 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

https://pypi.org/project/paddleocr/#:~:text=.99999964%5D-,3%20Use%20custom%20model,-When%20the%20built
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#22-python%E8%84%9A%E6%9C%AC%E4%BD%BF%E7%94%A8
参考了如上连结，想用 python 直接调用自定义数据的训练模型，但是看log最后都会变为使用官方预训练模型 (会出现如 det=True, rec=True, type=ocr 等等，并另外本地端执行自定义数据训练和官方预训练模型确认是官方预训练模型結果)；请问是否有相关文件说明或已知方法可以做修正，谢谢。

ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}', rec_char_dict_path='{your_rec_char_dict_path}', cls_model_dir='{your_cls_model_dir}', use_angle_cls=True)
result = ocr.ocr(img, cls=True, det=False, rec=False)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
