### ISSUE TITLE
CAN输出结果都是\\cdots

### ISSUE THREAD

**Issue by with-him777** [PaddlePaddle/PaddleOCR#10485]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
命令行输入PaddleOCR % python3 tools/infer/predict_rec.py --image_dir="/Users/liuhuan/formula/PaddleOCR/doc/datasets/crohme_demo/1.png" --rec_algorithm="CAN" --rec_batch_num=1 --rec_model_dir="./inference/rec_d28_can/" --rec_char_dict_path="./ppocr/utils/dict/latex_symbol_dict.txt"
黑底白字识别出来都是一堆\\cdots
 尝试加入--rec_image_inverse=False ，白底黑字 结果仍一样

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
