### ISSUE TITLE
在编译paddle的时候对于3rdparty能跳过那些系统有的，能用brew安装的，并且把系统有的直接链接过来吗？

### ISSUE THREAD

**Issue by quhanj** [PaddlePaddle/PaddleOCR#10488]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macos 11.6.5
- 版本号/Version：Paddle：2.4  PaddleOCR： 
- 问题相关组件/Related components：
- 运行指令/Command Code：./build/ppocr --rec_model_dir=inference/rec_rcnn --use_angle_cls=false --det=false --rec=true --cls=false --image_dir=../../doc/imgs_words/ch/word_1.jpg
- 完整报错/Complete Error Message：ERROR: flag 'help' was defined more than once (in files '/???/Paddle2.4/build/third_party/gflags/src/extern_gflags/src/gflags_reporting.cc' and '/tmp/gflags-20230101-4369-12s2aaz/gflags-2.2.2/src/gflags_reporting.cc').

使用c++的paddle_inference。paddle是编译的，opencv是通过brew安装的。paddleocr编译是正常的，能编译出ppocr来。但是运行之就出现这个错误。感觉是paddle跟opencv两个包使用了不同的gflags所造成的，我想在编译paddle的时候对于3rdparty，能跳过那些系统有的，能用brew安装的，并且把系统有的直接链接过来吗？

**Comment by quhanj** [comment]
已经解决。自问自答。希望可以帮助遇到相同需求的人。
替换掉cmake/external/gflags.cmake

基本内容包括：
set(HOMEBREW_CELLAR "/opt/homebrew/Cellar")
set(GFLAGS_INCLUDE_DIR "${HOMEBREW_CELLAR}/gflags/2.2.2/include")
set(GFLAGS_LIBRARIES "${HOMEBREW_CELLAR}/gflags/2.2.2/lib/libgflags.dylib")
add_library(gflags SHARED IMPORTED GLOBAL)
set_property(TARGET gflags PROPERTY IMPORTED_LOCATION ${GFLAGS_LIBRARIES})
add_dependencies(gflags extern_gflags)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
