### ISSUE TITLE
Error importing paddleocr

### ISSUE THREAD

**Issue by ChetnaLongani** [PaddlePaddle/PaddleOCR#10484]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Colab
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
![Screenshot (99)](https://github.com/PaddlePaddle/PaddleOCR/assets/140593324/1ff8a74e-c2f1-495a-8118-b9411f545948)

**Comment by ToddBear** [comment]
可以参考 #10443 中的做法
