### ISSUE TITLE
请问：在文字识别时候，容易出现漏0的情况（如下图所示），可以通过设置参数或什么办法解决吗

### ISSUE THREAD

**Issue by wxzwxz131** [PaddlePaddle/PaddleOCR#10480]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![1690350665330](https://github.com/PaddlePaddle/PaddleOCR/assets/37330408/bd46c9be-ade0-4830-913b-338f3cc3fcc8)
只有 30000被识别成3000，其他识别均正确

**Comment by raoyutian** [comment]
建议使用英文数字V3模型。
测试可以全部正常识别

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
