### ISSUE TITLE
请问检测有更快的模型吗

### ISSUE THREAD

**Issue by liujun5-tal** [PaddlePaddle/PaddleOCR#10494]
## 背景
现在Android的检测大概需要300多ms，有更快的模型吗，大概在50ms左右这种

**Comment by mllife** [comment]
@liujun5-tal , which model are you talking about, give more details on your issue.

**Comment by liujun5-tal** [comment]
> @liujun5-tal , which model are you talking about, give more details on your issue.

我的手机是Android，用的 Android_demo 这个apk 跑的，现在DB检测模型需要300-400ms，想问下有没有更轻量级的，准确率可以不高，就行希望能到100ms
