### ISSUE TITLE
How to optimize output file logging in fine tuning the model?

### ISSUE THREAD

**Issue by asif-ca** [PaddlePaddle/PaddleOCR#10491]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：latest Paddle：latest  PaddleOCR：2.5  问题相关组件/Related components：CUDA
- 运行指令/Command Code：`python tools/train.py -c configs/det/ch_PP-OCRv3_rec_distillation.yml`
- 完整报错/Complete Error Message：

I am[ fine tuning ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/finetune_en.md)the model using this command `python tools/train.py -c configs/det/ch_PP-OCRv3_rec_distillation.yml`

Model is saving too many files to output folder specified in `ch_PP-OCRv3_rec_distillation.yml` is it normal to save many files on each epoch/iteration (because our live server is running out of space due to this almost 30GB of files already saved by model) 

1. **_Is there any param that i can set to prevent this or delete files that are not required in future i.e resuming the fine-tuning ?_**
2.  **_Is it ok to remove files manually as we also need to resume fine-tuning on different languages in iterations using the same fine-tunned model_**

**Comment by asif-ca** [comment]
@tink2123 Any workout, please?

**Comment by asif-ca** [comment]
@WenmuZhou @dyning @LDOUBLEV @tink2123 @MissPenguin @Evezerest @littletomatodonkey @andyjpaddle @weisy11 @D-DanielYang @Topdu @sdcb @ZeyuChen @bingooo please help??

**Comment by UserWangZz** [comment]
save_epoch_step: 10
this setting every 10 epoch to save a training model.
