### ISSUE TITLE
文本检测训练完进行单张图片预测时发现漏检内容

### ISSUE THREAD

**Issue by gg336699** [PaddlePaddle/PaddleOCR#10499]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10/centos7
- 版本号/Version：Paddle：2.4.2   PaddleOCR：2.6.1.3  问题相关组件/Related components：PPOCRV3-DET
- 运行指令/Command Code：python tools/infer_det.py -c ./configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.infer_img="./train_data/det/train/00001.jpg"
- 完整报错/Complete Error Message：无报错，只是漏检内容

数据集由铁路集装箱号以及平板车号组成，如下图所示，上半部分为集装箱信息，下半部分为平板车号：

![ea0e32f1868b53d1e9bfacd264306a7](https://github.com/PaddlePaddle/PaddleOCR/assets/57903500/4ea79296-bd9f-4b8e-8645-1af7e916b035)

当我使用完整数据集训练之后，各项指标如下：
- hmean: 0.8266978922716627
- is_float16: False, precision: 0.7673913043478261
- recall: 0.8959390862944162,

但是当我进行单张图片推理测试时却发现，平板车信息并未预测出来，调整了thresh、box_thresh以及unclip_ratio超参数都没有正确输出，只是会输出集装箱信息，如下图：

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/57903500/680d34e8-285f-4643-8234-c6e954ec7fcf)

当我尝试将数据集更改为只包含平板车信息并训练后，检测一切正常，可以正常输出平板车信息的检测结果，如下图：

![17827cd413e0bfa19fea431346b4b06](https://github.com/PaddlePaddle/PaddleOCR/assets/57903500/1a773af5-b6b5-4193-aa5b-b2f32014941a)

请问有人遇到过这样的问题嘛，这是由什么原因导致的，希望可以由有一个解决方案，不胜感激！

**Comment by liuhuan-gl** [comment]
我也是这个问题

**Comment by gg336699** [comment]
> 我也是这个问题

我的问题暂时性的解决了，其实就是单张测试的时候不会显示，但是如果直接转成模型去推理的话，就会有结果，不知道是啥原因，希望ocr工作组可以注意到!

**Comment by xu-peng-7** [comment]
> > 我也是这个问题
> 
> 我的问题暂时性的解决了，其实就是单张测试的时候不会显示，但是如果直接转成模型去推理的话，就会有结果，不知道是啥原因，希望ocr工作组可以注意到!

您可以具体描述一下吗？我对这个问题有点感兴趣，单张测试是哪个命令，转成模型是指转成inference模型还是onnx模型？再推理的话指的是哪个命令。感谢

**Comment by xuxiansheng2018** [comment]
相似问题，希望有解答

**Comment by gg336699** [comment]
> 相似问题，希望有解答

如上，应该是paddle的bug，希望工作组可以闲暇时间关注一下。

**Comment by xuxiansheng2018** [comment]
您好，我具体描述一下我的问题：我的测试集有8500张图片，使用自己训练的det去单独只做检测的话，只有200张图片没有检测到框，可能是这些图片自身比较难识别。但是使用det和rec的联合指令的时候predict_system.py 指定了自己训练的det和自己训练的rec，以及官方的cls，却出现1700张图片检测结果为空，这种是det和rec之间的关联出现了问题吗？不知道问题出在哪里，希望您能给我个可行的建议。（自己训练的det验证acc=0.9&nbsp; &nbsp;rec的acc=0.8）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月2日(星期三) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 文本检测训练完进行单张图片预测时发现漏检内容 (Issue #10499)





  
相似问题，希望有解答
  
如上，应该是paddle的bug，希望工作组可以闲暇时间关注一下。

**Comment by xu-peng-7** [comment]
> 

最好给一个可以复现的场景，比如你的数据集，单独检测使用的是什么命令，predict_system.py 使用了什么命令。根据目前情况来看，很可能是参数设置的问题，你有检查过实际运行时两个检测模型的参数吗？

**Comment by xuxiansheng2018** [comment]
> 
![DE4995F2846D91871269ADC28749E0AC](https://github.com/PaddlePaddle/PaddleOCR/assets/55676370/3d564763-d22f-440e-bb79-5fa653c5fc7e)
我是在自己的数据集上进行实验的，
只测试检测阶段，python3 tools/infer_det.py \
-c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml   \
-o Global.pretrained_model=./output/rec_ppocr_v3_distillation/best_accuracy  \
Global.infer_img=./data/new_det_data/test_det/crop_img/
8500张测试图片，仅有220张未检测到框。
接着我使用CUDA_VISIBLE_DEVICES=0 \
python3 /data/yy/PaddleOCR/tools/infer/predict_system.py \
--image_dir="./data/new_det_data/test_det/crop_img/" \
--det_model_dir="./inference/ch_PP-OCRv3_det_infer/"  \
--rec_model_dir="./inference/rec_ppocr_v3_distillation/Teacher/" \
--cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"\
--use_angle_cls=True \
--use_gpu=True  \
--draw_img_save_dir="./inference_results/inference_results_101/"
还是在自己的数据集上进行测试，输出结果发现1700张图片的识别结果都是空，也就是识别不到字，如上图所示。至于你说的参数设置我应该没有特殊设置（初次接触并不是很了解），我是按照官网的教程在自己的数据集上面测试的，测试集图片就是我发的图片那种类型。

**Comment by GreatV** [comment]
hi @gg336699，出问题的原图能提供一下吗？

**Comment by UserWangZz** [comment]
> 当我尝试将数据集更改为只包含平板车信息并训练后，检测一切正常，可以正常输出平板车信息的检测结果

关于这个问题，可能的原因是predict_system中的参数配置与infer时使用的config中参数不一致导致的检测效果下降，可以尝试排查一下

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
