### ISSUE TITLE
源图片必须要放大才能获取不错的效果

### ISSUE THREAD

**Issue by yimtcode** [PaddlePaddle/PaddleOCR#10492]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS 13.4
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.0 问题相关组件/Related components：

使用`det_mv3_db.yml`配置训练，已经注释掉`DetResizeForTest `下内容

```yaml
# ...
      - DetResizeForTest:
          # image_shape: [ 736, 1280 ]
# ...
```

在导出模型使用`python tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model="./output/db_mv3/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"`都能获得不错的效果。
但在使用PaddleOCR对象加载模型，OCR识别时效果很差基本啥也识别不出来。按比例放大宽到640效果会好一点，放大到768效果会更好。

```python
PaddleOCR(
 # ...
det_model_dir='export_model_path'
)
```

直接使用官方模型是不需要调整原图片的大小的，应该怎么处理？

**Comment by UserWangZz** [comment]
可以看看PaddleOCR类中的配置和训练推理时是否一致
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
