### ISSUE TITLE
请问我使用python在电脑跑检测屏幕截图居然要30s，怎么样加快速度呢？

### ISSUE THREAD

**Issue by zxhxh0128** [PaddlePaddle/PaddleOCR#10501]
请问我使用python在电脑识别屏幕截图居然要30秒左右，怎么样提高效率速度呢？
ocr = PaddleOCR(use_angle_cls=cls, lang=lang) 
result = ocr.ocr(img_path, cls=cls)

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.6.1.3 问题相关组件/Related components：PaddleOCR.orc
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Sayaka91** [comment]
@zxhxh0128 if your using this model on cpu, you can use `enable_mkldnn` to decrease inference time

**Comment by raoyutian** [comment]
如果你是在windows平台，建议使用https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/PaddleOCRDemo/python，
该方式采用C++处理，python 调用dll的方式，速度很快。

**Comment by junwei-liu** [comment]
> 如果你是在windows平台，建议使用[https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/PaddleOCRDemo/python，](https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/PaddleOCRDemo/python%EF%BC%8C) 该方式采用C++处理，python 调用dll的方式，速度很快。

请问如果考虑是在ubuntu上运行，只有CPU的情况下，是否有加速的方法？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by raoyutian** [comment]
> > 如果你是在windows平台，建议使用[https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/PaddleOCRDemo/python，](https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/PaddleOCRDemo/python%EF%BC%8C) 该方式采用C++处理，python 调用dll的方式，速度很快。
> 
> 请问如果考虑是在ubuntu上运行，只有CPU的情况下，是否有加速的方法？

现在已经支持很多linux版本了。
