### ISSUE TITLE
Group relevant information into one block

### ISSUE THREAD

**Issue by paulgromy** [PaddlePaddle/PaddleOCR#10500]
I figured out how to get text from a PDF file using this library. But I would like to improve my functionality.
The fact is that the recognized text is not presented in a structured way, and I would like to receive text at the output that can be grouped into blocks.

Perhaps I explained not quite clearly, here you can find more details at this link https://stackoverflow.com/questions/76787641/get-data-in-the-form-of-blocks-when-recognizing-a-file

I would be happy if you tell me how to implement this idea

**Comment by ToddBear** [comment]
I can generally understand what you mean. But the link you shared seems to be dead, can you re-share it?

**Comment by shiyutang** [comment]
Hi there, did you try ppstructure?

**Comment by ToddBear** [comment]
From what I understand, are you trying to group the results of ocr in the appropriate blocks like below ? 

Where the image is divided into different areas such as text, table, and figure. 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43341135/d1f4c90b-c226-43c4-9f7c-98ad641e9843)

And each text area contains multiple lines of text.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43341135/acd3da55-77e5-4bea-96fc-35c5b9806e1a)

You may try the layout recovery module function in [ppstructure](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure), which can restores the input image to a word or pdf file with the same layout as the original image.

**Comment by paulgromy** [comment]
@ToddBearThank you for paying attention to my question. Check the link again
