### ISSUE TITLE
Text recognition: Bad results with number data and number-character-mixed data

### ISSUE THREAD

**Issue by Sayaka91** [PaddlePaddle/PaddleOCR#10507]
I tried on with paddleOCR recognition model with japanese language.
I realized the result with only character data is enough good to use. But when I add some number data or number-character-mixed data, the result is bad.
Is this a problem with model or just with japanese trained model?

**Comment by UserWangZz** [comment]
Maybe the number data is not enough?
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
