### ISSUE TITLE
djl + ppocr 进行文字识别准确度低

### ISSUE THREAD

**Issue by 12341234-yangboran** [PaddlePaddle/PaddleOCR#10504]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/74187378/f588ae4c-7a13-476e-9c53-9ed36bbfc372)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/74187378/c5a7f3d6-c561-4f35-acbd-c9644a0cccf9)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/74187378/153ddb2c-942d-4996-ae9b-a8a51017221c)

**Comment by 12341234-yangboran** [comment]
模型是从飞桨官网下载的
https://aistudio.baidu.com/aistudio/modelsdetail?modelId=17
字典在github下载的
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/ppocr_keys_v1.txt

**Comment by 12341234-yangboran** [comment]
文字检测功能是好用的，但识别效果很差

**Comment by 12341234-yangboran** [comment]
文字检测可以，文字识别效果很差

**Comment by Sayaka91** [comment]
@12341234-yangboran 
Is your result bad only with number data or character-number-mixed data? I got the similar problem

**Comment by 12341234-yangboran** [comment]
> @12341234-yangboran Is your result bad only with number data or character-number-mixed data? I got the similar problem

I used this model on my ticket to get Chinese, English and numbers.

**Comment by 12341234-yangboran** [comment]
I know this rec_model need a dict. I get it. But the result is always bad.

**Comment by 12341234-yangboran** [comment]
> @12341234-yangboran Is your result bad only with number data or character-number-mixed data? I got the similar problem

I know this rec model need a dict. I get it. But the result is always bad.

**Comment by Sayaka91** [comment]
@12341234-yangboran 
I used Japanese pretrained rec model. With input contains only characters, this model works well. But if input contains only numbers or both numbers and characters, i got the result bad. So I don't know that causes the model structure or trained dataset

**Comment by 12341234-yangboran** [comment]
> @12341234-yangboran I used Japanese pretrained rec model. With input contains only characters, this model works well. But if input contains only numbers or both numbers and characters, i got the result bad. So I don't know that causes the model structure or trained dataset
`package com.ai.djl;

import ai.djl.Model;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.util.NDImageUtils;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDList;
import ai.djl.ndarray.index.NDIndex;
import ai.djl.ndarray.types.DataType;
import ai.djl.ndarray.types.Shape;
import ai.djl.translate.Batchifier;
import ai.djl.translate.Translator;
import ai.djl.translate.TranslatorContext;
import ai.djl.util.Utils;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class PpWordRecognitionTranslator implements Translator<Image, String> {
    private List<String> table;
    private final boolean use_space_char;

    public PpWordRecognitionTranslator(Map<String, ?> arguments) {
        use_space_char =
                arguments.containsKey("use_space_char")
                        ? Boolean.parseBoolean(arguments.get("use_space_char").toString())
                        : true;
    }

    @Override
    public void prepare(TranslatorContext ctx) throws IOException {
        Model model = ctx.getModel();
        try (InputStream is = model.getArtifact("ppocr_keys_v1.txt").openStream()) {
            table = Utils.readLines(is, true);
            table.add(0, "blank");
            if(use_space_char)
                table.add(" ");
            else
                table.add("");
        }
    }

    @Override
    public String processOutput(TranslatorContext ctx, NDList list) {
        StringBuilder sb = new StringBuilder();
        NDArray tokens = list.singletonOrThrow();

        long[] indices = tokens.get(0).argMax(1).toLongArray();
        boolean[] selection = new boolean[indices.length];
        Arrays.fill(selection, true);
        for (int i = 1; i < indices.length; i++) {
            if (indices[i] == indices[i - 1]) {
                selection[i] = false;
            }
        }

        int lastIdx = 0;
        for (int i = 0; i < indices.length; i++) {
            if (selection[i] == true && indices[i] > 0 && !(i > 0 && indices[i] == lastIdx)) {
                sb.append(table.get((int) indices[i]));
            }
        }
        return sb.toString();
    }

    @Override
    public NDList processInput(TranslatorContext ctx, Image input) {
        NDArray img = input.toNDArray(ctx.getNDManager(), Image.Flag.COLOR);
        int imgC = 3;
        int imgH = 48;
        int imgW = 320;

        float max_wh_ratio = (float) imgW / (float) imgH;

        int h = input.getHeight();
        int w = input.getWidth();
        float wh_ratio = (float) w / (float) h;

        max_wh_ratio = Math.max(max_wh_ratio,wh_ratio);
        imgW = (int)(imgH * max_wh_ratio);

        int resized_w;
        if (Math.ceil(imgH * wh_ratio) > imgW) {
            resized_w = imgW;
        } else {
            resized_w = (int) (Math.ceil(imgH * wh_ratio));
        }
        NDArray resized_image = NDImageUtils.resize(img, resized_w, imgH);
        resized_image = resized_image.transpose(2, 0, 1).toType(DataType.FLOAT32,false);
        resized_image.divi(255f).subi(0.5f).divi(0.5f);
        NDArray padding_im = ctx.getNDManager().zeros(new Shape(imgC, imgH, imgW), DataType.FLOAT32);
        padding_im.set(new NDIndex(":,:,0:" + resized_w), resized_image);

        padding_im = padding_im.flip(0);
        padding_im = padding_im.expandDims(0);
        return new NDList(padding_im);
    }

    @Override
    public Batchifier getBatchifier() {
        return null;
    }
}
`

You could use this PpWordRecognitionTranslator for rec_model`s Translator.

**Comment by 12341234-yangboran** [comment]
> @12341234-yangboran I used Japanese pretrained rec model. With input contains only characters, this model works well. But if input contains only numbers or both numbers and characters, i got the result bad. So I don't know that causes the model structure or trained dataset

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/74187378/2faf8e5f-1e47-4838-9e23-b1790444f385)
like this
