### ISSUE TITLE
crnn resnet34 lr配置是 0.0005，训练过程中能修改吗？可以修改到多少，改善准确率？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10503]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

crnn resnet34 lr配置是 0.0005，训练过程中能修改吗？可以修改到多少，改善准确率？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
