### ISSUE TITLE
python3: can't open file '/content/PaddleOCR/pretrained_model/tools/infer_kie_token_ser.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by paulgromy** [PaddlePaddle/PaddleOCR#10518]
In colab.research.google.com, I execute the script for configuring Key Information Extraction (KIE) exactly with the documentation (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README.md#key-information-extraction-kie).

git clone https://github.com/PaddlePaddle/PaddleOCR.git
cd PaddleOCR
pip install -r requirements.txt
pip install -r ppstructure/kie/requirements.txt
pip install paddleocr -U

mkdir train_data
cd train_data
wget https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar && tar -xf XFUND.tar
cd ..

mkdir pretrained_model
cd pretrained_model
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/ser_vi_layoutxlm_xfund_pretrained.tar && tar -xf ser_vi_layoutxlm_xfund_pretrained.tar
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/re_vi_layoutxlm_xfund_pretrained.tar && tar -xf re_vi_layoutxlm_xfund_pretrained.tar

And when I run any of the scripts (which are presented in the documentation. Here I will give one as an example)

python3 tools/infer_kie_token_ser.py \
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg

I get an error: 
python3: can't open file '/content/PaddleOCR/pretrained_model/tools/infer_kie_token_ser.py': [Errno 2] No such file or directory

What am I doing wrong if I follow all the steps according to the documentation?

**Comment by eliot-ye** [comment]
Maybe you need do `cd ..`
