### ISSUE TITLE
识别表格中的合金组分（英文字母和数字的组合）时正确率低。应该怎么办？

### ISSUE THREAD

**Issue by KylinGuo** [PaddlePaddle/PaddleOCR#10520]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 22.04 LST
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.6.1.3 问题相关组件/Related components：PaddleOCR
- 运行指令/Command Code：paddleocr --image_dir /path/to/img/tbl-E3.5.png --use_gpu false --lang=en
- 完整报错/Complete Error Message：下标都没有正确识别。

原始图片
<img width="843" alt="tbl-E3 5" src="https://github.com/PaddlePaddle/PaddleOCR/assets/32160749/f6c40046-07da-4c9d-aa3f-1c58911b2542">

识别结果：
<img width="730" alt="2023-08-01_131424" src="https://github.com/PaddlePaddle/PaddleOCR/assets/32160749/0c0cc81c-c051-4fb9-bcda-6c87e9737afb">

**Comment by ToddBear** [comment]
建议可以针对这类数据制作一份数据集微调一下相关的模型
