### ISSUE TITLE
Can't install the requirement PyMuPDF for Python 3.11 on Windows (other versions and OS are fine)

### ISSUE THREAD

**Issue by eftalgezer** [PaddlePaddle/PaddleOCR#10529]
- 系统环境/System Environment：Python 3.11 on Windows-latest
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 and 2.7.0.0 问题相关组件/Related components：PyMuPDF

Logs for 2.7.0.0 <https://github.com/eftalgezer/PlotScan/actions/runs/5729532184/job/15526435952>.

Logs for 2.6.1.3 <https://github.com/eftalgezer/PlotScan/actions/runs/5729856355/job/15527429132>.

**Comment by eftalgezer** [comment]
I have done it by:

 1. Downgrade the machine to Windows 2019 to use Visual Studio 2019. `        os: ["ubuntu-latest", "macos-latest", "windows-2019"]`. If you are trying to install it on your local machine this is not necessary
 2. Set up Visual Studio 2019 on Windows
```
    - name: Set up Visual Studio 2019 for Windows
      if: matrix.os == 'windows-2019'
      uses: microsoft/setup-msbuild@v1.1
```
 3. Install PyMuPDF by building the source code

```
    - name: Install PyMuPDF on Windows
      if: matrix.os == 'windows-2019'
      run: |
            [bool] $vsSetupExists = $null -ne (Get-Command Get-VSSetupInstance -ErrorAction SilentlyContinue)
            if (!$vsSetupExists)
            {
              Write-Verbose "Installing the VSSetup module..."
              Install-Module VSSetup -Scope CurrentUser -Force
            }
            [string] $visualStudioInstallationPath = (Get-VSSetupInstance | Select-VSSetupInstance -Latest -Require Microsoft.Component.MSBuild).InstallationPath
            $env:PYMUPDF_SETUP_DEVENV = (Get-ChildItem $visualStudioInstallationPath -Recurse -Filter "DevEnv.exe" | Select-Object -First 1).FullName
            curl -OL https://github.com/pymupdf/PyMuPDF/archive/refs/tags/1.20.2.zip
            tar -xf 1.20.2.zip
            cd PyMuPDF-1.20.2
            python setup.py install
            cd ..
            rm -f 1.20.2.zip
            rd -r -fo PyMuPDF-1.20.2
```

 The run code above `git clone ..` is to find the location of
    devenv.com (devenv.exe). If you are trying to install on your local machine and know the path you can simply set `$env:PYMUPDF_SETUP_DEVENV = path/to/devenv.exe`. PyMuPDF 1.20.2 is the requirement of PaddleOCR.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
