### ISSUE TITLE
Latest version 2.7.0.0 does not work as expected

### ISSUE THREAD

**Issue by eftalgezer** [PaddlePaddle/PaddleOCR#10526]
- 系统环境/System Environment： Ubuntu-latest (3.7 to 3.11), macOS-latest (3.7 to 3.11), Windows-latest (3.7 to 3.10)
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.7.0.0

The input image is <https://github.com/eftalgezer/PlotScan/raw/master/figures/trimmed.png>.

My code is:

```
from paddleocr import PaddleOCR



points = []
for lang in [
    "latin",
    "arabic",
    "cyrillic",
    "devanagari",
    "ch",
]:
    ocr = PaddleOCR(use_angle_cls=True, lang=lang)
    img_path = "figures/trimmed.png"
    result = ocr.ocr(img_path, cls=True)
    for r in result:
        for line in r:
            if line[1][0].isnumeric():
                points.append([line[0], None, float(line[1][0])])
```

The previous version 2.6.1.3 gives the output for points:

`[[[[18.0, 305.0], [28.0, 305.0], [28.0, 316.0], [18.0, 316.0]], None, 0.0], [[[132.0, 303.0], [153.0, 303.0], [153.0, 319.0], [132.0, 319.0]], None, 20.0], [[[251.0, 303.0], [273.0, 303.0], [273.0, 319.0], [251.0, 319.0]], None, 40.0], [[[370.0, 303.0], [391.0, 303.0], [391.0, 319.0], [370.0, 319.0]], None, 60.0], [[[489.0, 305.0], [508.0, 305.0], [508.0, 318.0], [489.0, 318.0]], None, 80.0], [[[491.0, 304.0], [507.0, 304.0], [507.0, 316.0], [491.0, 316.0]], None, 0.0], [[[8.0, 50.0], [17.0, 50.0], [17.0, 63.0], [8.0, 63.0]], None, 3.0], [[[9.0, 130.0], [18.0, 130.0], [18.0, 142.0], [9.0, 142.0]], None, 2.0], [[[18.0, 304.0], [27.0, 304.0], [27.0, 317.0], [18.0, 317.0]], None, 0.0], [[[132.0, 302.0], [153.0, 302.0], [153.0, 319.0], [132.0, 319.0]], None, 20.0], [[[251.0, 302.0], [272.0, 302.0], [272.0, 319.0], [251.0, 319.0]], None, 40.0], [[[370.0, 302.0], [391.0, 302.0], [391.0, 319.0], [370.0, 319.0]], None, 60.0], [[[489.0, 304.0], [508.0, 304.0], [508.0, 317.0], [489.0, 317.0]], None, 80.0]]`

But, the current version 2.7.0.0 gives the output:

`[[[[18.0, 305.0], [28.0, 305.0], [28.0, 316.0], [18.0, 316.0]], None, 0.0], [[[132.0, 303.0], [153.0, 303.0], [153.0, 319.0], [132.0, 319.0]], None, 20.0], [[[251.0, 303.0], [273.0, 303.0], [273.0, 319.0], [251.0, 319.0]], None, 40.0], [[[370.0, 303.0], [391.0, 303.0], [391.0, 319.0], [370.0, 319.0]], None, 60.0], [[[489.0, 305.0], [508.0, 305.0], [508.0, 318.0], [489.0, 318.0]], None, 80.0], [[[372.0, 304.0], [388.0, 304.0], [388.0, 316.0], [372.0, 316.0]], None, 0.0], [[[491.0, 304.0], [507.0, 304.0], [507.0, 316.0], [491.0, 316.0]], None, 0.0], [[[18.0, 306.0], [27.0, 306.0], [27.0, 315.0], [18.0, 315.0]], None, 0.0], [[[132.0, 301.0], [153.0, 301.0], [153.0, 318.0], [132.0, 318.0]], None, 20.0], [[[252.0, 301.0], [272.0, 301.0], [272.0, 319.0], [252.0, 319.0]], None, 40.0], [[[370.0, 301.0], [391.0, 301.0], [391.0, 319.0], [370.0, 319.0]], None, 60.0], [[[489.0, 302.0], [508.0, 302.0], [508.0, 319.0], [489.0, 319.0]], None, 80.0]]`

As you can see, it is missing the points on the Y-axis of the image.

**Comment by eftalgezer** [comment]
@ToddBear Which explanations are needed?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
