### ISSUE TITLE
ocr识别，内存泄漏

### ISSUE THREAD

**Issue by sunjinguo** [PaddlePaddle/PaddleOCR#10521]
OCR识别，cpu 内存从7G到慢慢上涨，直至程序被kill
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.6.1  
- 运行指令/Command Code：python *.py &
- 完整报错/Complete Error Message：程序被 kill
- 疑问：程序内存开始稳定在7G 左右，是本身做OCR就是很耗费内存或显存吗？什么情况下会爆内存？后期内存缓慢上涨的原因大概是什么问题？

**Comment by situozhang** [comment]
同样问题，连续推理存在内存泄漏

**Comment by tink2123** [comment]
请问可以提供推理环境吗？操作系统是什么，循环预测一张图是否可以复现问题？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
