### ISSUE TITLE
如何将模型结果输出成json，另外有什么标签工具？

### ISSUE THREAD

**Issue by poormanfwh** [PaddlePaddle/PaddleOCR#1052]
如何将模型结果输出成json，另外有什么标签工具？

另外，我测试了手机电子发票，有些区域识别不出来，那我该怎么去训练？或者说你们的模型多久更新一次最新的训练？

**Comment by MissPenguin** [comment]
在预测脚本里将返回结果修改成你要的json格式就行。

发票支持的不够好的话，可以自己标一批数据finetune，具体训练流程可以参考教程中的“模型训练/评估”章节。

**Comment by poormanfwh** [comment]
具体怎么修改成json结果啊。

**Comment by poormanfwh** [comment]
我测试过别的有关OCR的模型会同时输出Json和标好框的输出文件。希望PaddleOCR能增加这个功能。或者有什么快捷方法可以实现吗？

**Comment by WenmuZhou** [comment]
> 我测试过别的有关OCR的模型会同时输出Json和标好框的输出文件。希望PaddleOCR能增加这个功能。或者有什么快捷方法可以实现吗？

哪个模型有这个功能啊

**Comment by poormanfwh** [comment]
https://github.com/nwcd-samples/NWCD-INdustry-customized-ocr-solution.
另外问下怎么输出 成json文件啊。
