### ISSUE TITLE
使用ppyoloe作为版面恢复的版面分析模型报错The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.

### ISSUE THREAD

**Issue by luooluo** [PaddlePaddle/PaddleOCR#10539]
- 运行指令/Command Code：

python3 predict_system.py     
--image_dir=./docs/table/pic_images/    
 --det_model_dir=inference/cn_PP-OCRv3_det_infer     
--rec_model_dir=inference/cn_PP-OCRv3_rec_infer     
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt     
--table_model_dir=inference/cn_ppstructure_mobile_v2.0_SLANet_infer     
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt    
--layout_model_dir=inference/ppyoloe_plus_crn_l_80e_coco     
--layout_dict_path=../ppocr/utils/dict/layout_dict/layout_ours_dict.txt     
--vis_font_path=../doc/fonts/simfang.ttf     
--recovery=True     
--output=../output/  

- 完整报错/Complete Error Message：

[2023/08/02 16:19:10] ppocr INFO: [0/11] ./docs/table/pic_images/00004.jpg
Traceback (most recent call last):
  File "predict_system.py", line 315, in <module>
    main(args)
  File "predict_system.py", line 254, in main
    res, time_dict = structure_sys(img, img_idx=index)
  File "predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "/mnt/share/PaddleOCR-release-2.6/ppstructure/layout/predict_layout.py", line 89, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2411)
  [operator < conv2d_fusion > error]

版面分析模型使用自己训练的ppyoloe代替picodet，运行命令显示input没有初始化张量

**Comment by jonesky** [comment]
报同样的错误，如何解决呢？

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
