### ISSUE TITLE
PPStructure有段落识别的功能吗

### ISSUE THREAD

**Issue by jesung1993** [PaddlePaddle/PaddleOCR#10538]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by ToddBear** [comment]
ppstructure中有板面分析功能，板面分析的结构近似于段落。

可以参考 [ppstructure] (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/README_ch.md)
