### ISSUE TITLE
DB++问题

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleOCR#10530]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
训练DB++出现src_h,src_w,ratio_h,ratio_w = shape_list[batch_index]现实batch_index的shape是[1,640,640]出现返回的值数量太多，用配置文件det_r50_db++_icdar出现loss_class(preds,batch)出现AssertionError错误
训练det_r50_pse_vd配置文件batch_size为1的时候出现超出现存out of memory但GPU大小是24G

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
