### ISSUE TITLE
paddleocr命令是否可以指定输出保存

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#10533]
安装后，提供的paddleocr命令，在ocr识别的时候，无法保存结果而总是输出到日志

是否可以提供一个参数指定

目前还需要手动去写代码来解决，而无法开箱即用。

**Comment by raoyutian** [comment]
下面是python代码，可以参考
`from datetime import datetime
import io
import os
import paddleocr
import numpy as np
from PIL import Image
def main():
    ppocr=paddleocr.PaddleOCR(ocr_version='PP-OCRv3',use_cls=False,use_det=True,use_gpu=False,enable_mkldnn=True,max_side_len=960,cpu_math_library_num_threads=24);
    imagepath=os.path.abspath('.')+"\\image\\"
    imagefiles=os.listdir(imagepath)
    total=[]
    for image in imagefiles:
       imagefile=imagepath+image
        
       temp= Image.open(imagefile)
       img=np.array(temp)[:,:,:3]
       t1= datetime.utcnow()
       info=ppocr.ocr(img)
       t2=datetime.utcnow()
       c=t2-t1
       total.append(c)
       print("time:",c);
       result=""
       for textblocks in info:
            result= result+textblocks[1][0]
       print(result)
    print("平均时间:",   np.mean(total));
if __name__=="__main__":
    main()
    input() 
`

**Comment by ToddBear** [comment]
提问者应该是想要新增一个args，使得可以在命令行处控制OCR结果的存储

上述代码好像不能回答这个问题，希望您能够提供新的解决方案 : )

**Comment by WilliamQf-AI** [comment]
已提交pr

**Comment by ToddBear** [comment]
@cole-dda 请问 @WilliamQf-AI 实现的功能是你想要的吗？
