### ISSUE TITLE
many test images is empty，Why？and what should I improve on next

### ISSUE THREAD

**Issue by xuxiansheng2018** [PaddlePaddle/PaddleOCR#10535]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

运行命令  使用自己训练的det加自己训练的rec加官方的cls
CUDA_VISIBLE_DEVICES=1 \
python3 tools/infer/predit_system.py \
--image_dir="./data/new_det_data/test_det/crop_img/" \
--det_model_dir="./inference/det_inference_v3_student/"  \
--rec_model_dir="./inference/rec_ppocr_v3_distillation/Teacher/" \
--cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"\
--use_angle_cls=True \
--use_gpu=True  \
--draw_img_save_dir="./inference_results/inference_results_001/"

我在测试集上测试了8500张图片，但是有1700张最后的显示结果都是空白，但是很多·图片肉眼还是可以识别出来的，
在验证集上我的det训练结果应该还是不错的
[2023/08/02 16:25:51] ppocr INFO: precision:0.908694192682108
[2023/08/02 16:25:51] ppocr INFO: recall:0.897844112769486
[2023/08/02 16:25:51] ppocr INFO: hmean:0.9032365699032366
[2023/08/02 16:25:51] ppocr INFO: fps:26.48458613411826

rec验证集上达到best metric, acc: 0.80

但是最后结合起来出现很多漏检，识别结果为空，问题在哪呢？希望得到回复

**Comment by xuxiansheng2018** [comment]
![017aebd794a1eb43c40d373a3e48562](https://github.com/PaddlePaddle/PaddleOCR/assets/55676370/677cc4d7-8ca2-45ba-bce5-238dfa26c7d5)
![c63886400fb58552d047216929ef916](https://github.com/PaddlePaddle/PaddleOCR/assets/55676370/c8406009-227d-458f-9291-a0a98e31ea7c)

**Comment by xuxiansheng2018** [comment]
有的又可以成功检测出来
![99832af7b4163f2527309681664c861](https://github.com/PaddlePaddle/PaddleOCR/assets/55676370/ad34e27a-dbb6-4f23-baeb-c2a84fb24668)

**Comment by UserWangZz** [comment]
确保predit_system脚本中使用的参数与训练时config文件中一致。
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
