### ISSUE TITLE
fintune检测模型的数据集可以不打文字标注吗

### ISSUE THREAD

**Issue by aki378** [PaddlePaddle/PaddleOCR#10532]
您好，我看到官方给出用于微调检测模型的数据标签示例带有识别结果
ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]

想问下transciption是否是必要的
如果全部ranscription都为"未识别"，会影响训练结果吗
例如：ch4_test_images/img_61.jpg    [{"transcription": "未识别", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]

如果可以不带transciption的话，标注工作会简单很多

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/95953739/072ad6fe-7e88-4ce7-8cbf-088abc0053c0)

**Comment by aki378** [comment]
应用场景为街景招牌检测，设备原因导致部分文字内容较为模糊，但希望模型学习到将整个招牌当作一个检测框的能力

**Comment by ToddBear** [comment]
应该是可以的，检测模型不会用到文字的内容作为监督信号

**Comment by aki378** [comment]
> 应该是可以的，检测模型不会用到文字的内容作为监督信号

感谢，经过测试，模型输出是transcription: ""，说明确实不需要用到
