### ISSUE TITLE
GPU识别结果为空，CPU识别结果正常

### ISSUE THREAD

**Issue by TJJ120635** [PaddlePaddle/PaddleOCR#10549]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

在 Windows 和 Linux 端均进行尝试，无法得到GPU识别结果。

**系统环境/System Environment**：
- Windows 10 家庭中文版 22H2：
1060MaxQ + CUDA 12.2

- Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-76-generic x86_64) :
Tesla P40 + CUDA 11.7

**版本号/Version：**
Python：3.8, anaconda
Paddle：paddlepaddle-gpu==2.5.1.post117
PaddleOCR： 2.7.0.0/2.6.1.3 都尝试过
问题相关组件/Related components：PPStructure

**运行指令/Command Code：**
从 Github 拉取最新 PaddleOCR 仓库
使用 `paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure`
GPU运行无结果
加上 --use_gpu=False 之后正常出结果

**完整报错/Complete Error Message：**
Windows：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43161566/f7936875-ca65-445c-975e-2cc41cc9129f)

Ubuntu：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43161566/e8523e0e-fc99-46f3-baf1-0fc476c0b72c)

**Comment by Flywolfs** [comment]
我也是这样，在4060GPU跑就没结果，2080ti上跑有结果，CPU有结果，都是同样的表格图片，很奇怪，找不到解决方案，希望官方给解答一下

**Comment by Flywolfs** [comment]
> 我也是这样，在4060GPU跑就没结果，2080ti上跑有结果，CPU有结果，都是同样的表格图片，很奇怪，找不到解决方案，希望官方给解答一下

已经解决，将CUDA升级到11.2就行了，4060 compute capability 8.5, 10.2的cuda不支持

**Comment by TJJ120635** [comment]
我用的是 CUDA 11.6，但是没有结果

**Comment by jackieZhouQQ** [comment]
我也一样，cuda各个版本都试了，显卡1070，wsl2里面就正常，win下面就无结果

**Comment by iceunlim** [comment]
我也遇到了同样的问题  cuda12.0 cudnn8.9  paddlepaddle 2.5.1 paddleocr2.7
我把2.7降到2.6是可以得到结果的

**Comment by TJJ120635** [comment]
在最新的 issue #10958 已解决，将 paddlepaddle-gpu 从 2.5.1 降级到 2.4.2 即可完成

`python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`
