### ISSUE TITLE
ppoCR-v4啥时候更新

### ISSUE THREAD

**Issue by fxwfzsxyq** [PaddlePaddle/PaddleOCR#10547]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by raoyutian** [comment]
已经于2023年8月7日发布。
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/README_ch.md
![1691554266903](https://github.com/PaddlePaddle/PaddleOCR/assets/72854228/f55dd6ea-b02d-4980-a603-a2bb47b3703a)
