### ISSUE TITLE
Add support for ODT document format to predict_system.py for Layout Recovery.

### ISSUE THREAD

**Issue by Blue-PCB** [PaddlePaddle/PaddleOCR#10545]
## Background

PaddleOCR is an amazing tool and I'm particularly interested in the Layout Recovery feature as not many layout/OCR tools support this feature, especially FOSS. 

[Layout Recovery Readme](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure/recovery)

However, it only outputs DOCX files using the [pdf2docx](https://github.com/dothinking/pdf2docx) tool. It would be great to support open document format - [ODT](https://en.wikipedia.org/wiki/OpenDocument_technical_specification).

## Solution Steps
Add support for other PDF converters, such as:

Python based pdf2odt by Turulomio
[https://github.com/turulomio/pdf2odt](https://github.com/turulomio/pdf2odt)
[https://pypi.org/project/pdf2odt/](https://pypi.org/project/pdf2odt/)

Shell based pdf2odt by gutschke
[https://github.com/gutschke/pdf2odt](https://github.com/gutschke/pdf2odt)

However, I'm not sure if this will work for the task of layout recover for "image format PDFs".

#######

##背景

PaddleOCR 是一个了不起的工具，我对它的布局恢复功能特别感兴趣，因为支持这一功能的布局/OCR 工具并不多，尤其是自由和开放源码软件。

[Layout Recovery Readme](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure/recovery)

不过，它只能使用 [pdf2docx](https://github.com/dothinking/pdf2docx) 工具输出 DOCX 文件。如果能支持开放文档格式 - [ODT](https://en.wikipedia.org/wiki/OpenDocument_technical_specification)就更好了。

## 解决方案步骤
添加对其他 PDF 转换器的支持，例如

Turulomio 基于 Python 的 pdf2odt
[https://github.com/turulomio/pdf2odt](https://github.com/turulomio/pdf2odt)
[https://pypi.org/project/pdf2odt/](https://pypi.org/project/pdf2odt/)

基于 Shell 的 pdf2odt，作者 gutschke
[https://github.com/gutschke/pdf2odt](https://github.com/gutschke/pdf2odt)

不过，我不确定这是否适用于 "图像格式 PDF "的版式恢复任务。

通过www.DeepL.com/Translator（免费版）翻译

**Comment by shiyutang** [comment]
Thank you for your suggestion. it will not work, as the image format needs to go through the OCR process and recovered to docx. We would appreciate if you will be interested in submitting a PR for this feature. 

The source code is here: https://github.com/PaddlePaddle/PaddleOCR/blob/df54a7b4223c64a8480380f618fe95de3b8cf73b/paddleocr.py#L701

**Comment by Blue-PCB** [comment]
Hi @shiyutang 

To clarify, it is possible to add support for creating ODT by updating paddleorcr.py starting at line 701?

**Comment by shiyutang** [comment]
Yes，L701 is where ppstructure convert pdf to docx
