### ISSUE TITLE
训练停止了，但没有任何的错误信息，GPU一直被占用

### ISSUE THREAD

**Issue by izhaolinger** [PaddlePaddle/PaddleOCR#10546]
我在对检测模型微调时，在训练到37个epoch时，似乎不再继续了，但没有任何错误的信息。查看GPU使用情况，发现其中一块GPU的使用率一直是100%。

之前也曾训练过很多次，但没发现过这样的情况。

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/29848522/e339840d-8be4-47a6-9fb4-db1e2123916a)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/29848522/8347bf4a-f4b4-416a-9d02-df495a481f37)

**Comment by UserWangZz** [comment]
可能卡在验证阶段了？手动kill掉任务resume启动一下就好
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
