### ISSUE TITLE
Error when installing `paddleocr`

### ISSUE THREAD

**Issue by minhvu120201dn** [PaddlePaddle/PaddleOCR#10550]
Hello, =

I run `pip install paddleocr>=2.6.0.3` on google colab, and the following error has occurred:
`
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
ERROR: Could not build wheels for faiss-cpu, which is required to install pyproject.toml-based projects
`

Does anyone have any idea how to solve this problem? Thank you in advance.

**Comment by oscarjose9423** [comment]
Having same issue

**Comment by fast-books** [comment]
I am getting the same error in windows and also on wsl. Tried everything i cud

It seems to be something with swig?  
      error: command '/usr/bin/swig' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
  Running setup.py clean for faiss-cpu
Failed to build faiss-cpu
ERROR: Could not build wheels for faiss-cpu, which is required to install pyproject.toml-based projects

**Comment by HuyTT1611** [comment]
Change python version in colab to 3.9

**Comment by HuyTT1611** [comment]
Change python version to 3.9

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by TanishqSharma2022** [comment]
> Change python version to 3.9

Thanks dude. It worked

**Comment by TanishqSharma2022** [comment]
> Hello, =
> 
> I run `pip install paddleocr>=2.6.0.3` on google colab, and the following error has occurred: ` error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for faiss-cpu ERROR: Could not build wheels for faiss-cpu, which is required to install pyproject.toml-based projects `
> 
> Does anyone have any idea how to solve this problem? Thank you in advance.

I made a conda virtual environment with python 3.9 and it installed without any errors.
