### ISSUE TITLE
mobile和server模型的推理耗时问题

### ISSUE THREAD

**Issue by YukSing12** [PaddlePaddle/PaddleOCR#1055]
硬件信息：
CPU：4
RAM：32GB
GPU：v100
显存：16GB
磁盘：100GB

分别使用**官方提供**的中英文超轻量OCR模型（8.1M，ch_ppocr_mobile_v1.1_xxx_infer）和中英文通用OCR模型（155.1M，ch_ppocr_server_v1.1_xxx_infer）测试450张1536*2048的图片的平均推理耗时，测得**mobile模型**的平均推理耗时为**152ms**，**server模型**的平均推理耗时为**154ms**，请问两个模型的推理耗时为什么没有大的区别呢？

**Comment by LDOUBLEV** [comment]
你的测试数据可以给我们一些看看吗

**Comment by YukSing12** [comment]
> 你的测试数据可以给我们一些看看吗

![BXAIa2019082513211701](https://user-images.githubusercontent.com/39983134/97584039-8d862d80-1a32-11eb-9257-be40a70cbcca.jpg)
![BXAIa2019082513251901](https://user-images.githubusercontent.com/39983134/97584152-aee71980-1a32-11eb-94ba-5b8c5922057f.jpg)
![BXAIa2019082513282801](https://user-images.githubusercontent.com/39983134/97584199-bc9c9f00-1a32-11eb-9823-0ee39451385a.jpg)
![BXAIa2019082513310901](https://user-images.githubusercontent.com/39983134/97584229-c58d7080-1a32-11eb-8edb-6f3f011ed7b5.jpg)
![BXAIa2019082513362301](https://user-images.githubusercontent.com/39983134/97584265-cfaf6f00-1a32-11eb-9770-7b5161f3b326.jpg)

**Comment by littletomatodonkey** [comment]
你好，这是因为在gpu预测情况下，相当部分耗时都在预处理和后处理那块了，你可以看下预测时的GPU利用率，应该是很低的。你可以在cpu下去测试下速度，mobile端的模型还是有比较大优势的

server+cpu
![image](https://user-images.githubusercontent.com/14270174/97605739-f927c500-1a49-11eb-8989-85f9074a654d.png)

mobile+cpu

![image](https://user-images.githubusercontent.com/14270174/97606751-1c06a900-1a4b-11eb-91ee-6ca2c21b3426.png)

**Comment by YukSing12** [comment]
> 你好，这是因为在gpu预测情况下，相当部分耗时都在预处理和后处理那块了，你可以看下预测时的GPU利用率，应该是很低的。你可以在cpu下去测试下速度，mobile端的模型还是有比较大优势的
> 
> server+cpu
> ![image](https://user-images.githubusercontent.com/14270174/97605739-f927c500-1a49-11eb-8989-85f9074a654d.png)
> 
> mobile+cpu
> 
> ![image](https://user-images.githubusercontent.com/14270174/97606751-1c06a900-1a4b-11eb-91ee-6ca2c21b3426.png)

非常感谢你的分析，预测时的GPU利用率确实是很低，那请问有什么优化的思路吗？

**Comment by littletomatodonkey** [comment]
1. 可以尝试将数据预处理放到GPU上
2. 可以开启多个进程进行预测，现在最新代码已经支持了：

https://github.com/PaddlePaddle/PaddleOCR/blob/aea8c08ac856c16e5a5ee5da82dc26991ec52381/tools/infer/utility.py#L103

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
