### ISSUE TITLE
PaddleOCR批处理 批量推理

### ISSUE THREAD

**Issue by Sariel2** [PaddlePaddle/PaddleOCR#10555]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu22  cuda 12
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.7 问题相关组件/Related components：

如何实现批量预测呢，现在只能单张图进行预测
`ocr.ocr(img)`
若按照文档进行批处理，则只能判断是否包含文字，无法识别出所有文字
`ocr.ocr(img_cvread_list, det=False)`
不加det=False会报错

**Comment by Sariel2** [comment]
脑袋晕晕的_(¦3」∠)_

**Comment by Fly2flies** [comment]
实现了吗？

**Comment by Sariel2** [comment]
并没有

**Comment by UserWangZz** [comment]
检测阶段只支持单张图片推理

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by dongdk** [comment]
有小伙伴解决这个问题了吗？不批处理的话，处理数百万张图片会很慢

**Comment by UserWangZz** [comment]
> 有小伙伴解决这个问题了吗？不批处理的话，处理数百万张图片会很慢

你好，detection阶段不会对输入图像进行padding，因此每次只能处理一张图
