### ISSUE TITLE
增加解析结果录入到数据库中

### ISSUE THREAD

**Issue by CrushLSG** [PaddlePaddle/PaddleOCR#10554]
根据图片解析的内容，将内容入到数据库中，或者提供API接口，将解析的结果支持接口返回

**Comment by ToddBear** [comment]
通过代码调用的OCR推理支持返回检测/识别结果的，与数据库存储相关的逻辑可能需要自行编写

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
