### ISSUE TITLE
ImportError: generic_type: type "_gpuDeviceProperties" is already registered!

### ISSUE THREAD

**Issue by XxLater** [PaddlePaddle/PaddleOCR#10558]
我同时在使用yolov8-gpu 和paddleocr-gpu 出现此错误 ， 单独使用不会出现 ，看起来像是个gpu占用的问题 ， 有类似的解决方案吗？

**Comment by cucyuan** [comment]
您好，我也遇到了同样的问题，请问您解决了吗

**Comment by Embosen** [comment]
我也遇到了这个问题，只要前后导入torch和paddle就会报这种错误，单独import都不会有问题。还没找到解决方法。可能时paddle版本太高，我的时2.5.0.可能需要降低到2.4.但是我不到万不得已不想去更换版本，因为得编译安装。时间太长了

**Comment by MathewsJosh** [comment]
I solved this problem by reinstalling ultralytics and downgrading paddlepaddle version.

My env now:
-   paddlepaddle                     2.4.2
-   paddlepaddle-gpu             2.4.2
-   ultralytics                            8.0.220
-   torch                                   2.0.0+cu118
-   torchaudio                          2.0.1+cu118
-   torchvision                          0.15.1+cu118

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
