### ISSUE TITLE
Fastdeploy服务化部署的参数修改方式

### ISSUE THREAD

**Issue by ToddBear** [PaddlePaddle/PaddleOCR#10562]
FastDeploy服务化部署可以通过修改配置的文件的方式对PaddleOCR的部分参数进行修改，辛苦飞桨开发者 @EasyIsAllYouNeed 在这个Issue下简单描述一下修改的方法 : )

**Comment by EasyIsAllYouNeed** [comment]
见文件 [https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/models/det_postprocess/1/model.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/models/det_postprocess/1/model.py)
`class TritonPythonModel:
    """Your Python model must use the same class name. Every Python model
    that is created must have "TritonPythonModel" as the class name.
    """

    def initialize(self, args):
        """`initialize` is called only once when the model is being loaded.
        Implementing `initialize` function is optional. This function allows
        the model to intialize any state associated with this model.
        Parameters
        ----------
        args : dict
          Both keys and values are strings. The dictionary keys and values are:
          * model_config: A JSON string containing the model configuration
          * model_instance_kind: A string containing model instance kind
          * model_instance_device_id: A string containing model instance device ID
          * model_repository: Model repository path
          * model_version: Model version
          * model_name: Model name
        """
        # You must parse model_config. JSON string is not parsed here
        self.model_config = json.loads(args['model_config'])
        print("model_config:", self.model_config)

        self.input_names = []
        for input_config in self.model_config["input"]:
            self.input_names.append(input_config["name"])
        print("postprocess input names:", self.input_names)

        self.output_names = []
        self.output_dtype = []
        for output_config in self.model_config["output"]:
            self.output_names.append(output_config["name"])
            dtype = pb_utils.triton_string_to_numpy(output_config["data_type"])
            self.output_dtype.append(dtype)
        print("postprocess output names:", self.output_names)
        self.postprocessor = fd.vision.ocr.DBDetectorPostprocessor()
        self.cls_preprocessor = fd.vision.ocr.ClassifierPreprocessor()
        self.rec_preprocessor = fd.vision.ocr.RecognizerPreprocessor()
        self.cls_threshold = 0.9`

        **self.postprocessor = fd.vision.ocr.DBDetectorPostprocessor()
        self.cls_preprocessor = fd.vision.ocr.ClassifierPreprocessor()
        self.rec_preprocessor = fd.vision.ocr.RecognizerPreprocessor()**

通过postprocessor ，cls_preprocessor ，rec_preprocessor 来修改参数

**Comment by zhouyiminga** [comment]
你好啊，我想限制识别的文本框数量，尝试过在这个地方配置这个max_candidates参数，但是不生效。是我对这个参数理解有误，还是目前这个地方只支持部分的参数配置啊。
![QQ截图20230915144715](https://github.com/PaddlePaddle/PaddleOCR/assets/41407267/9675dc49-c2aa-4649-b539-124af1f51ab9)
![QQ图片20230915150615](https://github.com/PaddlePaddle/PaddleOCR/assets/41407267/b3b7e075-da54-46f0-bca3-8323830e5852)
因为我能通过下面的命令使用工具获取只有两个文本框的图片，我以为可以通过这个参数能做到最多只返回两个结果的效果，不知道我理解有没有问题
python3 infer_det.py -c ch_PP-OCRv3_det_student.yml -o Global.infer_img="12.jpg" Global.pretrained_model="student" Global.use_gpu=False PostProcess.max_candidates=2
![12](https://github.com/PaddlePaddle/PaddleOCR/assets/41407267/39ec273c-5e49-4a38-9389-244e7f6e0078)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
