### ISSUE TITLE
关于识别模型按照官方文档配置学习率却报错的问题

### ISSUE THREAD

**Issue by mi4da** [PaddlePaddle/PaddleOCR#10565]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04 LTS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： python tools/train.py -c configs/rec/PP-OCRv3/rec_custom_finetune.yml
-  rec_custom_finetune.yml 只修改了 lr部分，其余与ch_PP-OCRv3_rec_distillation.yml一致
- 完整报错/Complete Error Message：

[2023/08/07 14:10:21] ppocr INFO: Initialize indexs of datasets:['./raw_data/finetune_data/train_data/rec/rec_gt_train.txt']
[2023/08/07 14:10:21] ppocr INFO: Initialize indexs of datasets:['./raw_data/finetune_data/train_data/rec/rec_gt_test.txt']
W0807 14:10:21.900272 256258 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.8
W0807 14:10:21.900646 256258 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 134, in main
    optimizer, lr_scheduler = build_optimizer(
  File "/home/zhenfei/testment/PaddleOCR/ppocr/optimizer/__init__.py", line 37, in build_optimizer
    lr = build_lr_scheduler(config.pop('lr'), epochs, step_each_epoch)
  File "/home/zhenfei/testment/PaddleOCR/ppocr/optimizer/__init__.py", line 29, in build_lr_scheduler
    lr = getattr(learning_rate, lr_name)(**lr_config)()
  File "/home/zhenfei/testment/PaddleOCR/ppocr/optimizer/learning_rate.py", line 175, in __call__
    learning_rate = lr.PiecewiseDecay(
  File "/home/haihen/anaconda3/envs/ppocr/lib/python3.8/site-packages/paddle/optimizer/lr.py", line 396, in __init__
    raise ValueError(
ValueError: The values have one more element than boundaries, but received len(values) [2] < len(boundaries) + 1 [3].

一下是我根据
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md
3.3节部分配置的
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [700, 800]
    values : [0.001, 0.0001]
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0

**Comment by mi4da** [comment]
原文中表示
”piecewise学习率策略，需设置2个值“
请问现在是取消了吗还是?

**Comment by mi4da** [comment]
每日一顶

**Comment by Hegelim** [comment]
basically it is said in the error log already
```
ValueError: The values have one more element than boundaries, but received len(values) [2] < len(boundaries) + 1 [3].
```
what it means is you need 3 values if you have a boundary of length 2, so if you have `decay_epochs : [700, 800]`, then you would need to set your learning rate to something like `[0.001, 0.0005, 0.0001]`. Then for epochs before 700, your learning rate is 0.001, for epochs between 700 and 800, your learning rate 

Note, if you use any modern IDE, you can first go to ppocr/optimizer/learning_rate.py L175, then go inside to `lr.PiecewiseDecay`, what it does is crystal clear.

**Comment by jchain** [comment]
I tried. It worked. Thanks. @Hegelim

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
