### ISSUE TITLE
PDF场景OCR效果提升

### ISSUE THREAD

**Issue by Lllllp93** [PaddlePaddle/PaddleOCR#10568]
### 场景描述：
我想要通过PaddleOCR识别工程设计**pdf**图中的相关信息，类似下面这种设计图但文字更多（纯英文），文字信息包括各部分数字尺寸及对应的文字信息，对recall的要求比较高。另外输入的pdf单页尺寸很大，转为图片后15000*5000像素

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/39562096/03e81170-9728-4aca-9c73-6937d1b01052)

### 当前效果：
我组合尝试了不同的det以及rec模型，目前效果最好的组合是en_PP-OCRv3_det_infer & ch_PP-OCRv3_rec_infer，总结了以下问题：
- 部分内容识别精度不高，一些制图中的符号或者箭头被错误的识别为字符串或者导致字符串被错误识别，而需要识别出来的基础的算数符号识别（如+-)精度不高
- 我的文档是全英文的，但英文rec模型不能识别符号能力更差，不如对应的中英文模型，感觉字符串误判更少，可能是中文字典更全
- 当我使用原图（15000*5000）输入det模型时，检测结果性能不如长宽各resize一半的检测效果

### 我的问题
不知道针对我的场景以及遇到的问题，各位有什么改进建议？是否相似的案例可以参考。非常感谢

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
