### ISSUE TITLE
关于识别竖排文字的问题

### ISSUE THREAD

**Issue by mi4da** [PaddlePaddle/PaddleOCR#10566]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubunutu 20.04
- 版本号/Version：Paddle：2.4.2  PaddleOCR： 问题相关组件/Related components：识别模型-ppocrV3
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问对于这种文字
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/55870943/ddbac3f7-a4f9-4888-85b2-51a17316c32a)
发现在微调的时候。模型出现了欠拟合，请问是label是否应该像正常一样：
img_10_0.jpg	论语通译
img_102_0.jpg	管理者的必修课
还是说应该一行一个，按照行识别模型的逻辑来呢？
img_10_0.jpg	论\n语\n通\n译
**还是说，将图像翻转180度或者0度呢？**

**Comment by mi4da** [comment]
顶一下

**Comment by UserWangZz** [comment]
可以尝试逆时针旋转图片放平后训练，label格式就是图片中的内容

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
