### ISSUE TITLE
好未来表格识别数据集找不到下载链接

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/PaddleOCR#10569]
这个页面给出的好未来表格识别训练数据集无法找到下载地址，可以提供吗？https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/table_datasets.md#2-WTW%E4%B8%AD%E6%96%87%E5%9C%BA%E6%99%AF%E8%A1%A8%E6%A0%BC%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by WilliamQf-AI** [comment]
@shiyutang

**Comment by nissansz** [comment]
找到了吗？可以百度网盘分享吗？

**Comment by dreamlychina** [comment]
> 找到了吗？可以百度网盘分享吗？

有找到？？大佬

**Comment by dreamlychina** [comment]
> > 找到了吗？可以百度网盘分享吗？
> 
> 有找到？？大佬

他们说在百度飞桨上面有，但是也没有找到

**Comment by nissansz** [comment]
不用找了，他们还在改善rowspan之类结构训练，目前复杂表格效果都不太好。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
