### ISSUE TITLE
运行predict_structure.py脚本时，在pycharm运行窗口里没有输出也没有报错，只有光标在闪

### ISSUE THREAD

**Issue by juzibei** [PaddlePaddle/PaddleOCR#10563]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
D:\anaconda3\envs\paddle-py3.9\python.exe G:\PaddleOCR-release-2.6\PaddleOCR-release-2.6\ppstructure\table\predict_structure.py --table_model_dir=E:\PaddleOCR-release-2.6\PaddleOCR-release-2.6\official_model\ch_ppstructure_mobile_v2.0_SLANet_infer --table_char_dict_path=E:\PaddleOCR-release-2.6\PaddleOCR-release-2.6\ppocr\utils\dict\table_structure_dict_ch.txt "--image_dir=E:\PaddleOCR-release-2.6\PaddleOCR-release-2.6\train_date\table_3_test\\" --output=../output/table

**Comment by UserWangZz** [comment]
是否使用的GPU推理呢？显存有没有明显增加？
尝试debug一下看看在哪里卡住了

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
