### ISSUE TITLE
PPOCRLabel绘制矩形框频繁闪退

### ISSUE THREAD

**Issue by zhwsh** [PaddlePaddle/PaddleOCR#10578]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：mac os 12.6.2
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.7.0.0  问题相关组件/Related components：PPOCRLabel 2.0.0  & 2.3.1
- 运行指令/Command Code：PPOCRLabel --lang ch --kie True
- -python 3.8.17  
-  opencv-contrib-python          4.6.0.66 
- opencv-contrib-python-headless 4.6.0.66
- opencv-python                  4.6.0.66
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "/Users/xxx/.anaconda3/lib/python3.11/site-packages/PPOCRLabel/libs/canvas.py", line 596, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'float'
  drawRect(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'float'

**Comment by Gmgge** [comment]
如果可以的话，能简述一下重现条件嘛？

**Comment by zhwsh** [comment]
启动界面命令：PPOCRLabel --lang ch --kie True
<img width="1776" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/3831169/fd15c655-6d6e-459c-8284-214c5b11df2b">

选择矩形标注，点击鼠标左键触发报错。

**Comment by Gmgge** [comment]
根据追溯，你可以查看[相关](https://bugs.launchpad.net/rapid/+bug/1946407)说明，简单来说是python类型自动转换出现问题，你可以尝试以下方案以解决该问题。
1.升级PyQt5版本 pip install --upgrade  PyQt5
2.如果升级后仍不能解决，修改代码进行主动类型转换，最简单的方案是修改/Users/xxx/.anaconda3/lib/python3.11/site-packages/PPOCRLabel/libs/canvas.py 文件中line 596 为p.drawRect(int(leftTop.x()), int(leftTop.y()), int(rectWidth), int(rectHeight))

**Comment by kwanxian** [comment]
报错信息:
```
PPOCRLabel\libs\canvas.py", line 599, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'float'
  drawRect(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'float'
```

自行更改：
```
# p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
x, y, w, h = [int(i) for i in (leftTop.x(), leftTop.y(), rectWidth, rectHeight)]
p.drawRect(x, y, w, h)
```

**Comment by yidasanqian** [comment]
碰到同样问题，python版本3.10.13

**Comment by mir134** [comment]
碰到同样问题，python版本3.10

**Comment by zrp2023** [comment]
same problem

**Comment by UserWangZz** [comment]
参考 https://github.com/PaddlePaddle/PaddleOCR/pull/11236
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by noiiiu** [comment]
> 根据追溯，你可以查看[相关](https://bugs.launchpad.net/rapid/+bug/1946407)说明，简单来说是数据类型自动转换出现问题，你可以尝试以下方案以解决该问题。 1.升级PyQt5版本 pip install --upgrade PyQt5 PyQt5-Qt5 PyQt5-sip(如果升级出现报错 请卸载重装) 2.如果升级后仍不能解决，修改代码进行主动类型转换，最简单的方案是修改/Users/xxx/.anaconda3/lib/python3.11/site-packages/PPOCRLabel/libs/canvas.py 文件中line 596 为p.drawRect(int(leftTop.x()), int(leftTop.y()), int(rectWidth), int(rectHeight))

实际操作了一下  升级PyQt5之后还是会报错  方法2这个可以解决问题  改动的地方不止line 596，我的版本(PPOCRLabel=                2.1.0)下line 615、615、596都进行了修改 修改完成后问题解决 非常感谢！！！
