### ISSUE TITLE
华为鲲鹏npu编译PaddleOCR C++

### ISSUE THREAD

**Issue by ruijie123** [PaddlePaddle/PaddleOCR#10571]
这个位置怎么修改呢
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/48897529/e6b4f693-7a44-426b-9da3-af5d996940b6)

**Comment by ruijie123** [comment]
OPENCV_DIR=your_opencv_dir
LIB_DIR=your_paddle_inference_dir
CUDA_LIB_DIR=your_cuda_lib_dir
CUDNN_LIB_DIR=/your_cudnn_lib_dir

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
