### ISSUE TITLE
Could not find a version that satisfies the requirement Pillow>=10.0.0

### ISSUE THREAD

**Issue by NeonBubbles** [PaddlePaddle/PaddleOCR#10575]
- 系统环境/System Environment：ubuntu22 
- 版本号/Version：2.5.1  
- PaddleOCR：2.0.1和2.6.0  
- 运行指令/Command Code： 
```
docker pull paddlepaddle/paddle:2.5.1
docker run --name paddle_docker -it -v $PWD:/paddle paddlepaddle/paddle:2.5.1 /bin/bash
pip install "paddleocr>=2.0.1" 或者 pip install "paddleocr>=2.6.0"
```

- 完整报错/Complete Error Message：
```
λ 04872db20940 /home       pip install "paddleocr>=2.0.1"
Collecting paddleocr>=2.0.1
  Downloading paddleocr-2.7.0.0-py3-none-any.whl (74.1 MB)
     |████████████████████████████████| 74.1 MB 33.8 MB/s 
Collecting premailer
  Downloading premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Collecting attrdict
  Downloading attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from paddleocr>=2.0.1) (1.21.6)
ERROR: Could not find a version that satisfies the requirement Pillow>=10.0.0 (from paddleocr>=2.0.1) (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 3.0.0, 3.1.0rc1, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 7.0.0, 7.1.0, 7.1.1, 7.1.2, 7.2.0, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.1.2, 8.2.0, 8.3.0, 8.3.1, 8.3.2, 8.4.0, 9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0)
ERROR: No matching distribution found for Pillow>=10.0.0 (from paddleocr>=2.0.1)
```

**Comment by NeonBubbles** [comment]
ERROR: Could not find a version that satisfies the requirement Pillow>=10.0.0 (from paddleocr>=2.6.0) (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 3.0.0, 3.1.0rc1, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 7.0.0, 7.1.0, 7.1.1, 7.1.2, 7.2.0, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.1.2, 8.2.0, 8.3.0, 8.3.1, 8.3.2, 8.4.0, 9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0)
ERROR: No matching distribution found for Pillow>=10.0.0 (from paddleocr>=2.6.0)

**Comment by NeonBubbles** [comment]
docker在容器内更新pip后就安装成功了

**Comment by zhangzonglin** [comment]
请问python是哪个版本啊？

**Comment by hujhcv** [comment]
更新pip还是不行。用docker安装的是python3.7，python3.7支持的Pillow最高版本就是9.5.0，没办法安装10.0.0 以上的Pillow版本。

**Comment by Linranran** [comment]
mark

**Comment by nashlibby** [comment]
mark

**Comment by Edmond-Lee-Zse-Wong** [comment]
> 更新pip还是不行。用docker安装的是python3.7，python3.7支持的Pillow最高版本就是9.5.0，没办法安装10.0.0 以上的Pillow版本。

对，我也是3.7，这个问题貌似无解，只能装个3.10再新建虚拟环境来用了

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
