### ISSUE TITLE
PPOCRLable频繁闪退

### ISSUE THREAD

**Issue by X17exe** [PaddlePaddle/PaddleOCR#10576]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10
- 版本号/Version：Paddle：2.5.0  PaddleOCR：2.6.1.3 问题相关组件/Related components：PPOCRLable
- 运行指令/Command Code：PPOCRLabel --lang ch --kie True
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "D:\Anaconda\envs\paddle_env\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'

**Comment by kwanxian** [comment]
定位到1425行，更改：
```
# bar.setValue(bar.value() + bar.singleStep() * units)
val = bar.value() + bar.singleStep() * units
if isinstance(val, float): val = int(val)
 bar.setValue(val)
```

**Comment by UserWangZz** [comment]
可以提个pr修复一下吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
