### ISSUE TITLE
关于ppocr 识别模型问题

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#1057]
![image](https://user-images.githubusercontent.com/12640462/97550268-687ec400-1a0c-11eb-9c9d-2f9ea330f42a.png)
下载识别的推理模型后解压为下图：
![image](https://user-images.githubusercontent.com/12640462/97550368-9106be00-1a0c-11eb-9544-e60dd890d090.png)
这是不是需要先进行模型转换，直接用来识别报：
![image](https://user-images.githubusercontent.com/12640462/97550455-a8de4200-1a0c-11eb-9f87-5fee3502b3fd.png)

**Comment by WenmuZhou** [comment]
再解压一下看看，我在mac下解压是正常的

**Comment by littletomatodonkey** [comment]
还是不行的话 用这个吧
[ch_ppocr_mobile_v1.1_rec_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5459558/ch_ppocr_mobile_v1.1_rec_infer.zip)

**Comment by BeyondYourself** [comment]
@littletomatodonkey 感觉连接里的识别预测包可能打包有点问题，在windows下解压当前是这个流程：
tar文件--->文件--->文件夹-->对应的param和model文件
但是实际的流程应该是：
tar文件--->文件夹--->文件夹-->对应的param和model文件
或者
tar文件--->文件夹-->对应的param和model文件
这样的流程应该比较恰当吧，因为这是对比之前的其他模型的一个差异
建议打包tar文件重新更新一下
