### ISSUE TITLE
WTW中文场景表格数据集怎样转换？

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/PaddleOCR#10570]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40328063/ffc23195-d804-496f-a098-58aa6d8c6fc7)
如上图，这里说需要转换，请问具体怎么操作？

**Comment by WilliamQf-AI** [comment]
@shiyutang

**Comment by nissansz** [comment]
有转换好的数据了吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
