### ISSUE TITLE
关于DB++检测模型的问题

### ISSUE THREAD

**Issue by X17exe** [PaddlePaddle/PaddleOCR#10586]
ICDAR2015版本和TD_TR版本有什么区别？网络上找不到TD_TR数据集的有关信息。

**Comment by data-ant** [comment]
请问PaddleOCR提供了DB++的实现吗？谢谢

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!
