### ISSUE TITLE
PaddleOCR not working in GPU  

### ISSUE THREAD

**Issue by SherwinSamuel23** [PaddlePaddle/PaddleOCR#10589]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10 
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：                                                                                                                                                      
 from paddleocr import PaddleOCR,draw_ocr
print("Hello")
ocr = PaddleOCR(use_angle_cls=True, lang='en',use_gpu=True) 
img_path = r'C:\Users\admin\Desktop\ADE_OCR\Image\page_2.jpg'
result = ocr.ocr(img_path, cls=True)
print("Hello2")
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

- 完整报错/Complete Error Message：Model is getting downloaded but print statement is not working after                       
 result = ocr.ocr(img_path, cls=True)                                                                                                                                                       Same code when i tried to execute  by changing use_gpu=False using CPU its working fine ....                                                         Version:                                                                                                                                                                                                   CUDA-11.0.2                                                                                                                                                                                          CUDNN-8.9.3                                                                                                                                                                                           Paddlepaddle-gpu-2.5.1                                                                                                                                                                       Paddleocr-2.6.1.3                                                                                                                                                                                  GPU: Nvidia RTX 3060                                                                                                                                                                             Suggest any solution for this
![Paddle-gpu](https://github.com/PaddlePaddle/PaddleOCR/assets/82770810/fe59da96-b2cd-4433-bf17-5bf99d044fb2)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
