### ISSUE TITLE
pdf转docx报错 err msg: list index out of range

### ISSUE THREAD

**Issue by 1906522096** [PaddlePaddle/PaddleOCR#10580]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle2.5.1：  PaddleOCR：2.7.0.0  问题相关组件/Related components： python:  python 3.8.17
- 运行指令/Command Code：paddleocr --image_dir=test.pdf --type=structure --recovery=true
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/39320217/f79883dc-c95e-41f9-b16e-4391f82145ff)
具体操作：
conda create -n PP -c conda-forge python=3.8
conda activate PP
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install "paddleocr>=2.6" -i https://mirror.baidu.com/pypi/simple
Invoke-WebRequest -Uri "https://ghproxy.com/https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/release/2.6/ppstructure/recovery/requirements.txt" -OutFile "requirements.txt"
pip install -r requirements.txt -i https://mirror.baidu.com/pypi/simple
pip install "PyMuPDF==1.19.0" -i https://mirror.baidu.com/pypi/simple

pdf转word的命令：
paddleocr --image_dir=test.pdf --type=structure --recovery=true

报错的pdf:

[test.pdf](https://github.com/PaddlePaddle/PaddleOCR/files/12297968/test.pdf)

**Comment by andyjpaddle** [comment]
bug已修复，https://github.com/PaddlePaddle/PaddleOCR/pull/10584/files 可安装最新版whl包进行测试，或者更新最新代码后本地编译安装
