### ISSUE TITLE
训练自己标注训练集导出的yml是coco的类而不是自己的

### ISSUE THREAD

**Issue by HHHEDA** [PaddlePaddle/PaddleOCR#10597]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
训练自己训练集，导出的yml是coco的类而不是自己的

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
