### ISSUE TITLE
Can we merge multiple models to single model?

### ISSUE THREAD

**Issue by asif-ca** [PaddlePaddle/PaddleOCR#10590]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windos
- 版本号/Version：Paddle： 2 PaddleOCR： 2.5 问题相关组件/Related components：
- 运行指令/Command Code：No
- 完整报错/Complete Error Message： No

**Can we merge multiple models of different languages like `hindi , Arabic, Chinese, english , Russian` into a single model so that no matter what the language of the text is in the image, the model should detect the text?**

**Comment by aumungray** [comment]
any update on this?

**Comment by UserWangZz** [comment]
In order to achieve this goal, you need to prepare a multilingual data set and a dictionary containing these languages, and then try to use PaddleOCR training
