### ISSUE TITLE
2.7.0版本运行不稳定

### ISSUE THREAD

**Issue by hua345** [PaddlePaddle/PaddleOCR#10594]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04 python3.8
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.7.0 问题相关组件/Related components：
- 运行指令/Command Code：PaddleOCR(use_angle_cls=True, use_gpu=False, gpu_mem=500,
                enable_mkldnn=True, show_log=True)
- 完整报错/Complete Error Message：

单进程进行图片推理，并都修改set_mkldnn_cache_capacity参数为1
sed -i 's/set_mkldnn_cache_capacity(10)/set_mkldnn_cache_capacity(1)/' /usr/local/lib/python3.8/dist-packages/paddleocr/tools/infer/utility.py

内存波动不稳定，经常被k8s杀死进程
ocr成功率 96% — ✓ 3325 / ✗ 120
http_req_failed................: 14.49% ✓ 584      ✗ 3446
http_reqs......................: 4030   2.4112/s
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/3890847/22eeb738-513b-4587-9c71-a2747c8cbd03)

- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.6.0.1
ocr成功率 96% — ✓ 3888 / ✗ 141
http_reqs......................: 4030   2.53018/s
http_req_failed................: 0.00%  ✓ 0        ✗ 4030

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/3890847/07488134-3531-4e02-b81b-d09d829af880)

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
