### ISSUE TITLE
在自己的vs项目中调用自己封装的paddleocr.dll出现paddle_inference.dll) (实验.exe 中)处有未经处理的异常: 将一个无效参数传递给了将无效参数视为严重错误的函数。

### ISSUE THREAD

**Issue by joctob** [PaddlePaddle/PaddleOCR#10591]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10   vs2019
- 版本号/Version：opencv 4.6 Paddle：paddle_inference  cpu_avx_mkl  PaddleOCR：PaddleOCR-release-2.6问题相关组件/Related components：应用的c++接口
- 运行指令/Command Code：在运行调试中出错使用的回调函数调用自己写的接口，vs的中断出现在调用结果的赋值
- 完整报错/Complete Error Message：0x00007FFEFD582634 (paddle_inference.dll) (实验.exe 中)处有未经处理的异常: 将一个无效参数传递给了将无效参数视为严重错误的函数。
附：args文件也检查过

**Comment by joctob** [comment]
加载过程中出现Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
