### ISSUE TITLE
2.7默认方式无法安装

### ISSUE THREAD

**Issue by luan78zaoha** [PaddlePaddle/PaddleOCR#10601]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version Paddle：251  PaddleOCR：270  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

pip install paddleocr
python要求最高是3.7
但是Pillow》=10.0.0 需要 python3.8以上 

ERROR: Ignored the following versions that require a different python version: 10.0.0 Requires-Python >=3.8

**Comment by ToddBear** [comment]
python == 3.8 也可以安装 paddleocr 的

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
