### ISSUE TITLE
有个问题问一下，模型微调时， 只单独增加需要微调的图片，不加入其他不需要调的图片  这样有没有什么问题

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10609]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

有个问题问一下，模型微调时，
只单独增加需要微调的图片，不加入其他不需要调的图片

这样有没有什么问题

**Comment by ToddBear** [comment]
可以参考PPOCR的微调文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/finetune.md

如果是检测任务，建议收集至少500个样本用于微调；

如果是识别任务，建议收集至少5000个样本用于微调

**Comment by nissansz** [comment]
要不要将之前的几百万数据加进去训练

**Comment by Longleaves** [comment]
同问，请问解决了吗

**Comment by ToddBear** [comment]
微调的话应该是不用把先前的数据加进去训练的

**Comment by Longleaves** [comment]
> 微调的话应该是不用把先前的数据加进去训练的

我放了几百张图片，训练以后发现新模型在我的数据集之外的图片识别效果比官网模型效果要差诶

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
