### ISSUE TITLE
ocr可以识别钢戳吗

### ISSUE THREAD

**Issue by hao123aa22** [PaddlePaddle/PaddleOCR#10600]
ocr可以识别钢戳吗

**Comment by ToddBear** [comment]
可以尝试一下现有的印章识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md

**Comment by UserWangZz** [comment]
需要保证钢戳文本的清晰程度，然后尝试微调识别模型看看

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
