### ISSUE TITLE
v3 (2.6) 和 v4 (2.7) 的识别指标似乎不一致

### ISSUE THREAD

**Issue by wangz315** [PaddlePaddle/PaddleOCR#10604]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/PP-OCRv3_introduction.md
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/PP-OCRv4_introduction.md

v3中lcnet达到了79.40%的准确率，而v4的base却变成了71.50%，耗时也有增加
请问这里是数据集做过了改变吗？

关于lcnetv3有没有相关文档可以具体分享一下呢？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
