### ISSUE TITLE
关于PP-OCRv4推理速度问题

### ISSUE THREAD

**Issue by minboo** [PaddlePaddle/PaddleOCR#10606]
**在CPU环境中使用PP-OCRv4模型对同一张图片进行推理，无论是det还是rec的推理耗时比v3模型的耗时高达数十倍之多，请问这是正常现象吗，还是和paddleocr版本不匹配，有没有大佬解答一下。**

- 系统环境/System Environment：windows  CPU
- 版本号/Version：PaddlePaddle：2.4.2  PaddleOCR：2.6.1.3 

运行代码：
```
default_engine = PaddleOCR(use_angle_cls=True, lang="ch",
                           cls_model_dir="/workspace/OCR/models/ch_ppocr_mobile_v2.0_cls_infer",
                           det_model_dir="/workspace/OCR/models/detv4_teacher_inference", 
                           rec_model_dir="/workspace/OCR/models/ch_PP-OCRv4_rec_server_infer"
                           )

image_path = "E:\\64.jpg"
responses = default_engine.ocr(image_path)
```
v4推理耗时
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/69302396/b5830154-2907-4149-ac94-436c50f589f5)
v3推理耗时
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/69302396/c7b99e61-8b51-41ba-a444-3e768e846a1a)

使用的是ch_PP-OCRv4_server模型，server和超轻量的识别效果有很大的区别吗

**Comment by jinditongzi** [comment]
我使用超轻量模型识别速度还行，但是用高精度模型在CPU环境下识别一张PNG图片得6-8分钟，而且高精度server的推理模型有漏行，反而轻量级模型没有漏行，但是会错一些字。

**Comment by jinditongzi** [comment]
[2023/08/10 17:25:23] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='./wjl/demoOCRCalls/paddleOCRv4HighModel/clsModel', cls_thresh=0.9, cpu_threads=10,
crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.2, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, de
t_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='./wjl/demoOCRCalls/paddleOCRv4HighModel/detModel', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_n
ms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_
dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_id=0, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, ir_optim=T
rue, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no
_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv4', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SV
TR_LCNet', rec_batch_num=6, rec_char_dict_path='F:\\py_repository\\PaddleNLP-develop\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='./wjl/de
moOCRCalls/paddleOCRv4HighModel/recModel', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_ba
tch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, typ
e='ocr', use_angle_cls=True, use_dilation=False, use_gpu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu
=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2023/08/10 17:25:35] ppocr DEBUG: dt_boxes num : 27, elapse : 10.534534692764282
[2023/08/10 17:25:35] ppocr DEBUG: cls num  : 27, elapse : 0.23600077629089355
[2023/08/10 17:31:46] ppocr DEBUG: rec_res num  : 27, elapse : 370.60985040664673

**Comment by minboo** [comment]
> 我使用超轻量模型识别速度还行，但是用高精度模型在CPU环境下识别一张PNG图片得6-8分钟，而且高精度server的推理模型有漏行，反而轻量级模型没有漏行，但是会错一些字。

v4的高精度还是会有漏行吗，我用v3也是会漏行，想试试v4效果怎么样，不过使用超轻量速度是比高精度快，可能是原始高精度模型比较大？

**Comment by jinditongzi** [comment]
我用v4超轻量模型不漏行，但是会有一些不该错的字没识别出来，比如“天”识别成大，“几”识别成“儿”。导致我不得不把det_db_unclip_ratio调成1.85（默认1.5），但是v4的server高精度版不会有着种问题，但是会漏行，我只能把det_db_unclip_ratio调小（调到0.8）的时候没漏行了，但是很多字都错了。

**Comment by jinditongzi** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/46389166/be7bd899-0843-453a-92b3-f045c52dd537)
主要漏这一句

**Comment by jinditongzi** [comment]
这个是刚才用v4轻量级（默认参数1.5）很多不该错的字没识别出来
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/46389166/e40ec5b1-dc93-485b-b912-13708840ab76)

**Comment by minboo** [comment]
> 



> 我用v4超轻量模型不漏行，但是会有一些不该错的字没识别出来，比如“天”识别成大，“几”识别成“儿”。导致我不得不把det_db_unclip_ratio调成1.85（默认1.5），但是v4的server高精度版不会有着种问题，但是会漏行，我只能把det_db_unclip_ratio调小（调到0.8）的时候没漏行了，但是很多字都错了。

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/69302396/c5ef85da-c20a-4333-97bb-d7bd17ddd18e)
现在用的是超轻量，漏的行还和v3不是同一行，不知道怎么处理这个问题，det_db_unclip_ratio也调过，调这个参数也不通用，即使这一份不漏了另一份还是会漏，漏行的问题一直存在

**Comment by etwk** [comment]
Try `--enable_mkldnn=True` to speed up in CPU environment.

Try any of these 3 below for the line lost issue:

- increase from default: `--det_limit_side_len=1500`
- `--det_db_score_mode=slow`
- `--det_db_box_thresh=0.3`

**Comment by digitalghost** [comment]
请问下各位 V4.0 的高精度模型，具体的下载地址是哪里啊，我找了好久也没找到啊，是不是不开放下载了

**Comment by minboo** [comment]
> 请问下各位 V4.0 的高精度模型，具体的下载地址是哪里啊，我找了好久也没找到啊，是不是不开放下载了

换到2.7分支看看 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
