### ISSUE TITLE
我编译了deploy/cpp_infer，运行时好像也没有出错，但是一直没有运行完，不知道怎么回事

### ISSUE THREAD

**Issue by quhanj** [PaddlePaddle/PaddleOCR#10618]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MacOS 13.5
- 版本号/Version：Paddle：2.4  PaddleOCR：2.7 问题相关组件/Related components：cpp_infer+PP-OCRv4
- 运行指令/Command Code：./build/ppocr --det_model_dir=inference/det_db --rec_model_dir=inference/rec_rcnn --cls_model_dir=inference/cls --image_dir=../../doc/imgs/12.jpg --use_angle_cls=true --det=true --rec=true --cls=true
- 完整报错/Complete Error Message：好像没有报错，但是输出以下内容后，什么都没有发生，也一直没有退出。
- In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320',if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
total images num: 1
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0811 22:01:28.906054 3986399360 fuse_pass_base.cc:59] ---  detected 2 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
I0811 22:01:28.924147 3986399360 fuse_pass_base.cc:59] ---  detected 1 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [constant_folding_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0811 22:01:28.932852 3986399360 memory_optimize_pass.cc:219] Cluster name : x  size: 12
I0811 22:01:28.932857 3986399360 memory_optimize_pass.cc:219] Cluster name : conv2d_469.tmp_1  size: 48
I0811 22:01:28.932860 3986399360 memory_optimize_pass.cc:219] Cluster name : conv2d_484.tmp_1  size: 384
I0811 22:01:28.932863 3986399360 memory_optimize_pass.cc:219] Cluster name : tmp_105  size: 384
I0811 22:01:28.932865 3986399360 memory_optimize_pass.cc:219] Cluster name : tmp_83  size: 1536
I0811 22:01:28.932868 3986399360 memory_optimize_pass.cc:219] Cluster name : tmp_107  size: 384
I0811 22:01:28.932869 3986399360 memory_optimize_pass.cc:219] Cluster name : tmp_73  size: 768
I0811 22:01:28.932871 3986399360 memory_optimize_pass.cc:219] Cluster name : elementwise_mul_1  size: 1536
I0811 22:01:28.932874 3986399360 memory_optimize_pass.cc:219] Cluster name : hardswish_76.tmp_0  size: 1536
--- Running analysis [ir_graph_to_program_pass]
I0811 22:01:28.945598 3986399360 analysis_predictor.cc:1318] ======= optimize end =======
I0811 22:01:28.945678 3986399360 naive_executor.cc:110] ---  skip [feed], feed -> x
I0811 22:01:28.946363 3986399360 naive_executor.cc:110] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
In PP-OCRv3, default rec_img_h is 48,if you use other model, you should set the param rec_img_h=32
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [constant_folding_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
--- Running analysis [ir_graph_to_program_pass]

**Comment by WilliamQf-AI** [comment]
点了控制台，阻塞了

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
