### ISSUE TITLE
识别模型训练好，测试有时候识别为空，有时候能识别出结果。

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1061]
您好，我将模型训练出来，有时候运行命令行，什么都打印不出来，有时候能打印出结果，请帮忙看一下哈。  

![image](https://user-images.githubusercontent.com/43515926/97652168-bc36ef00-1a98-11eb-9f9c-56d387cad8ac.png)

**Comment by LDOUBLEV** [comment]
有些玄学，预测代码里只有[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/0586d56d2b839cbb2bbeeceb2680f8b44ceee6c3/tools/infer_rec.py#L128)有continue，你可以在continue之前加一行 logger.info("valid_ind is F blank list")，重新运行下，识别为空的时候是不是从这里跳过了

**Comment by littletomatodonkey** [comment]
感觉是终端的输出重定向有问题，你重启和这个docker容器试下呢？

**Comment by zcswdt** [comment]
> logger.info("valid_ind is F blank list")
您好，我加了这个log打印，有时候还是会出现预测不了结果，有时候就能。
![image](https://user-images.githubusercontent.com/43515926/97653795-927fc700-1a9c-11eb-93ff-91fa840a9233.png)

**Comment by zcswdt** [comment]
> 感觉是终端的输出重定向有问题，你重启和这个docker容器试下呢？

目前模型还在训练，我可能暂时没有办法重启docker，不过后期可以试试。

**Comment by FLming** [comment]
若是python3.6以下版本，可能和 #982 相关。

**Comment by zcswdt** [comment]
> 若是python3.6以下版本，可能和 #982 相关。

我目前还是没解决，这个问题仍然存在，不过镜像什么的都是按照说明文档里面的快速启动安装的，我看到了一下#982，我这个是预测偶尔会进行预测，偶尔会预测为空和您那个关系不是很大吧？。

**Comment by zcswdt** [comment]
> 有些玄学，预测代码里只有[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/0586d56d2b839cbb2bbeeceb2680f8b44ceee6c3/tools/infer_rec.py#L128)有continue，你可以在continue之前加一行 logger.info("valid_ind is F blank list")，重新运行下，识别为空的时候是不是从这里跳过了

这个问题仍然没有解决，这个原因可以帮忙定位一下吗？

**Comment by zcswdt** [comment]
> 感觉是终端的输出重定向有问题，你重启和这个docker容器试下呢？

重启了docker容器也是一样，不知道是什么原因造成的。

**Comment by FLming** [comment]
> > 若是python3.6以下版本，可能和 #982 相关。
> 
> 我目前还是没解决，这个问题仍然存在，不过镜像什么的都是按照说明文档里面的快速启动安装的，我看到了一下#982，我这个是预测偶尔会进行预测，偶尔会预测为空和您那个关系不是很大吧？。

预测时构建模型的代码时一样的，同时也会影响到预测。

**Comment by zcswdt** [comment]
> 时构建模型的代码

那请问我这种情况如何解决呢？

**Comment by FLming** [comment]
> > 时构建模型的代码
> 
> 那请问我这种情况如何解决呢？

先确认是不是这个问题造成的（比如通过debug看一下是不是和表述的现象相同，python3.6以下，相关代码如果还是用的dict那么这个问题是肯定会发生的）。如果是，把代码更新到最新的就行了。

**Comment by zcswdt** [comment]
> 比如通过debug看一下是不是和表述的现象相

现象是相同的，识别模型有时候预测是空，所以我更新代码就行了吗？

**Comment by LLL0802** [comment]
> 您好，我将模型训练出来，有时候运行命令行，什么都打印不出来，有时候能打印出结果，请帮忙看一下哈。
> 
> ![image](https://user-images.githubusercontent.com/43515926/97652168-bc36ef00-1a98-11eb-9f9c-56d387cad8ac.png)

您好，请问你的训练步骤是什么样的呢，能具体说一下嘛，我也打算训练
