### ISSUE TITLE
Ser prediction goes wrong after exporting to inference model

### ISSUE THREAD

**Issue by danteblink** [PaddlePaddle/PaddleOCR#10619]
After training the ser model the predictions are correct using the trained model and the infer_kie_token_ser.py script. When I export the model using the export script and use the predict_token_ser.py script, the predictions are wrong. 

I checked the config files as suggested in the documentation but I can´t find anything wrong. Any suggestions?

**Comment by gooGofZ** [comment]
Face the same issue, do you have any update?

**Comment by danteblink** [comment]
@gooGofZ Nope. What I did was use the trained model without exporting it. There should be a problem with the export script. When I have time I will try to debug it.

**Comment by ghazalli** [comment]
> @gooGofZ Nope. What I did was use the trained model without exporting it. There should be a problem with the export script. When I have time I will try to debug it. Facing the same issues, have you found anything?

**Comment by ghazalli** [comment]
> @ghazalli I managed to overcome the errors. The problem was when using the infer_kie_token_script instead of the exported model. Ensure you select the right model dir and ser dictionary dir (class list). Also, check the other options; my command options look like this:
> 
> ```
>         --use_gpu=True
>         --kie_algorithm=LayoutXLM
>         --ser_model_dir= path_to_your_exported_model
>         --ser_dict_path= your_path/class_list.txt
>         --rec_algorithm=SVTR,
>         --ocr_order_method=tb-yx
>         --use_visual_backbone=False
>         --vis_font_path=PaddleOCR/doc/fonts/simfang.ttf
> ```

I'm sorry, i don't quite get it. So you manage to solve it by using the infer_kie_token_ser.py but for ser_model_dir you use the inference model (result from export model)?

**Comment by gooGofZ** [comment]
> > @gooGofZ Nope. What I did was use the trained model without exporting it. There should be a problem with the export script. When I have time I will try to debug it.
> 
> 
> Facing the same issues, have you found anything?

I've moved to PaddleNLP instead.

**Comment by danteblink** [comment]
> > @ghazalli I managed to overcome the errors. The problem was when using the infer_kie_token_script instead of the exported model. Ensure you select the right model dir and ser dictionary dir (class list). Also, check the other options; my command options look like this:
> > ```
> >         --use_gpu=True
> >         --kie_algorithm=LayoutXLM
> >         --ser_model_dir= path_to_your_exported_model
> >         --ser_dict_path= your_path/class_list.txt
> >         --rec_algorithm=SVTR,
> >         --ocr_order_method=tb-yx
> >         --use_visual_backbone=False
> >         --vis_font_path=PaddleOCR/doc/fonts/simfang.ttf
> > ```
> 
> I'm sorry, i don't quite get it. So you manage to solve it by using the infer_kie_token_ser.py but for ser_model_dir you use the inference model (result from export model)? Because infer_kie_token_ser.py only accept these arguments.
> 
> ![image](https://private-user-images.githubusercontent.com/52516822/281657058-11e76872-69ca-447a-a0be-ecfe3eddc1c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDcwODEsIm5iZiI6MTcwMzIwNjc4MSwicGF0aCI6Ii81MjUxNjgyMi8yODE2NTcwNTgtMTFlNzY4NzItNjljYS00NDdhLWEwYmUtZWNmZTNlZGRjMWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAwNTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZGZjZDU2ODQ2N2U4MzQ5OGQ3MTM5NDc2N2Q5NTFhNjBlODhjNWFkNjY0ZTRiYzU1OWU1NjhjNDRmMDE3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VNWBR84vvE8dgD9s3mHFHUJOWfyRatPUOmzl7pLtjZ8)

Sorry for the delay; it has been a tough month. No, You are right; these arguments are for the predict_kie_token script. You need to use this script when inferring with the exported model.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启

**Comment by gooGofZ** [comment]
> > @gooGofZ Nope. What I did was use the trained model without exporting it. There should be a problem with the export script. When I have time I will try to debug it.
> 
> Facing the same issues, have you found anything?

You need to check the yaml file for training and export are the same pixel/dimension or not?
