### ISSUE TITLE
FastDeploy 鲲鹏ascend c++部署 make-j报错

### ISSUE THREAD

**Issue by ruijie123** [PaddlePaddle/PaddleOCR#10615]
- 【FastDeploy版本】：![image](https://github.com/PaddlePaddle/FastDeploy/assets/48897529/37eb04c6-6884-46d6-801d-f023dcee0b79)
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： 鲲鹏920，
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/48897529/a1acbf23-5952-4153-898b-9df7ca6d4d81)
- 【编译语言】： C++ 
报错：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/48897529/5450de83-2fe4-454c-8509-9fafa019a026)
[ 50%] Building CXX object CMakeFiles/infer_demo.dir/infer.cc.o
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc: In function 'void AscendInfer(const string&, const string&, const string&, const string&, const string&, const fastdeploy::RuntimeOption&)':
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:37:29: error: declaration of 'fastdeploy::RuntimeOption option' shadows a parameter
   fastdeploy::RuntimeOption option;
                             ^~~~~~
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc: In function 'int main(int, char**)':
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:106:25: error: too few arguments to function 'void AscendInfer(const string&, const string&, const string&, const string&, const string&, const fastdeploy::RuntimeOption&)'
               test_image);
                         ^
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:22:6: note: declared here
 void AscendInfer(const std::string &det_model_dir,
      ^~~~~~~~~~~
CMakeFiles/infer_demo.dir/build.make:65: recipe for target 'CMakeFiles/infer_demo.dir/infer.cc.o' failed
make[2]: *** [CMakeFiles/infer_demo.dir/infer.cc.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/infer_demo.dir/all' failed
make[1]: *** [CMakeFiles/infer_demo.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shengzhe8688** [comment]
fastdeploy::RuntimeOption option; 这句话改成：
fastdeploy::RuntimeOption opt1;相关的变量都改成opt1即可。

**Comment by shengzhe8688** [comment]
把函数入参option 删掉就好了

**Comment by shengzhe8688** [comment]
如果cann版本和官方环境不一致貌似需要自己重新编译paddle-lite的动态库的。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
