### ISSUE TITLE
不能够使用tensorrt

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#10623]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
   paddlepaddle-gpu==2.5.1.post102
  paddleocr==2.7.0
- 运行指令/Command Code：
   paddleocr --image_dir 1.png --use_gpu true --use_tensorrt true --type ocr

- 完整报错/Complete Error Message：
<img width="1110" alt="screenshot_6013" src="https://github.com/PaddlePaddle/PaddleOCR/assets/1077830/3702fcb5-bd69-4a7d-9bbe-8daf09ad7782">

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
