### ISSUE TITLE
软件BUG？ 还是硬件有问题 ？ System进程和系统中断进程在占用CPU。

### ISSUE THREAD

**Issue by hzucc** [PaddlePaddle/PaddleOCR#10622]
使用GPU，在调用一个最简单的paddleocr图文识别之后，长时间放置它，比如空闲等待20秒或以上，然后会有两个进程“System”和“系统中断”进程在持续占用CPU（即使ocr进程已经关闭），除非关电脑重启它们才不占用，我的垃圾办公笔记本性能不高很容易看得出来每个占用10%-20%CPU左右。
期间没有运行其它进程。

- 系统环境/win10：
- 版本号/Version：Paddle：  paddlepaddle-gpu==2.3.2.post102，PaddleOCR：2.7.0.2 
- 运行指令/Command Code：

`import time
import cv2
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_gpu=True)
img = cv2.imread('t3.png')
res = ocr.ocr(img)
time.sleep(20)`

- 完整报错/Complete Error Message：没有报错，ocr识别结果是正确的

-其他描述：CUDA10.2，cuDNN7.6.5，显卡NVIDIA GeForce MX110

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂时将issue关闭，如果问题仍然存在，可尝试重新开启
