### ISSUE TITLE
PPOCRLabel标注问题

### ISSUE THREAD

**Issue by Hespter** [PaddlePaddle/PaddleOCR#10639]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.3.2  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

目前发现自动标注后，手动检查时添加一些未识别到的的文本框并点击确认后，在生成“导出识别结果”的rec_gt.txt和crop_img中有些手动添加的框没有出现，这是为什么？另外发现一个规律，一般未出现的文本框在Label.txt中对应的属性"difficult": true，其它自动识别的框默认都是"difficult": false，请问这是个Bug吗？

**Comment by SWHL** [comment]
PPOCRLable已经搬家了，后续请去https://github.com/PFCCLab/PPOCRLabel 这里提问把
