### ISSUE TITLE
关于文本角度分类模型

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1063]
请问文本角度分类模型准确率能达多少？训练时间需要多久？ 我的训练过程中训练集的准确率能很快达到1.0，但是验证集中的很低！
![Uploading image.png…]()

**Comment by WenmuZhou** [comment]
您好，图片不可用

**Comment by WenmuZhou** [comment]
文本分类器这边，训练准确率99+，训练时间大概一天左右

**Comment by SealQ** [comment]
> 文本分类器这边，训练准确率99+，训练时间大概一天左右

![J3L{6LJ3{`K9H1RV8U3@ 13](https://user-images.githubusercontent.com/56471409/97674671-e1dbec80-1ac8-11eb-8844-208262006583.png)

您好，图片已经上传，我的数据集是简单的白底黑字，是否需要修改resize中的padingg为np.ones(),此外，您的学习率等细节可以提供下么？我做的是四分类，但感觉泛化性不怎么高

**Comment by WenmuZhou** [comment]
你测试一张训练图片看看，你这可能是过拟合了

**Comment by SealQ** [comment]
> 你测试一张训练图片看看，你这可能是过拟合了

训练的图片准确率蛮高的，考虑过过拟合的现象，但是想着虽然图片简单，但是进行了数据增强，应该过拟合情况不是很大；
![{E0UN%2Z)M(U@ Q%O5F_U 6](https://user-images.githubusercontent.com/56471409/97675436-49466c00-1aca-11eb-898d-d978cb7952cf.png)
由于分类模型训练经验不足，所以感觉开始训练的时候的acc感觉有些许异常，希望您能指导

**Comment by WenmuZhou** [comment]
日志里的acc看着没问题

**Comment by SealQ** [comment]
> 日志里的acc看着没问题

我可以做些什么来改善我的模型么?比如修改超参等

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/optimizer.py#L81 这个调大试一下
另外你也可以用钱买准确率没到0的模型试试，检查一下eval数据和train的数据有什么异同

**Comment by SealQ** [comment]
好的 谢谢您

**Comment by SealQ** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/optimizer.py#L81 这个调大试一下
> 另外你也可以用前面准确率没到0的模型试试，检查一下eval数据和train的数据有什么异同

请教您一下，您的学习率细节方便透露么？

**Comment by WenmuZhou** [comment]
学习率就是repo里配置文件里的

**Comment by SealQ** [comment]
@WenmuZhou 您好，在您的建议下，修改了l2_decay，但在很少的iters后，训练集可以很快达到了97%+， 但是验证集依然在70%，有很明显的过拟合的现象，这难道是数据的问题？ 因为我的是白底黑字，所以在resize的时候用的是白色像素补充
