### ISSUE TITLE
C++预测demo config.SetModel 官网预测库 link错误问题

### ISSUE THREAD

**Issue by AnBaolei1984** [PaddlePaddle/PaddleOCR#1064]
C++预测demo复现和验证完成。发现一个问题：

 Paddle预测库官网的库有问题。config.SetModel(model_dir + "/model", model_dir + "/params");这个函数会link不到，应该是编预测库的时候有问题。后来通过编译paddle源码的方式解决。问题对应的文档1.2.2部分。

解决这个问题后，基本可以按着文档顺利复现过程。

**Comment by LDOUBLEV** [comment]
感谢反馈，我们看下问题

**Comment by Gmgge** [comment]
我在pp的社区看到有人回答是：
应该是编译器的问题。你下载的预测库是用gcc4.8编译的，所以你得使用gcc4.8来编译。建议你将gcc和g++都降级为4.8。可使用下面的命令实现降级...
不过你已经解决了编译的问题，emm 我的重新编译paddle源码的过程并不流畅，想请教下自己编译的时候有什么需要特殊注意的吗？

**Comment by AnBaolei1984** [comment]
> 我在pp的社区看到有人回答是：
> 应该是编译器的问题。你下载的预测库是用gcc4.8编译的，所以你得使用gcc4.8来编译。建议你将gcc和g++都降级为4.8。可使用下面的命令实现降级...
> 不过你已经解决了编译的问题，emm 我的重新编译paddle源码的过程并不流畅，想请教下自己编译的时候有什么需要特殊注意的吗？

我的编译器gcc是5.4.0。整体编译paddle源码还算顺利，就是可能会遇到提示超过文件系统数目的问题，通过设置 ulimit -n 63356解决。

**Comment by Gmgge** [comment]
好的，多谢呢 @.@
