### ISSUE TITLE
camel case fix not included in 2.7 release

### ISSUE THREAD

**Issue by itasli** [PaddlePaddle/PaddleOCR#10650]
Seems like you forgot to include #10181 in 2.7 release https://github.com/orgs/PaddlePaddle/projects/12

- System Environment：Ubuntu
- Version：Paddle：2.5.1  PaddleOCR： 2.7
- Related components：fitz
- Command Code：
- Complete Error Message：'Document' object has no attribute 'pageCount'

**Comment by shiyutang** [comment]
@itasli please cherry-pick your PR to dygraph and realse2.7: https://github.com/PaddlePaddle/PaddleOCR/pull/10181

**Comment by itasli** [comment]
> @itasli please cherry-pick your PR to dygraph and realse2.7: #10181

done #10707 #10708
