### ISSUE TITLE
训练ser任务报错

### ISSUE THREAD

**Issue by situjunhao** [PaddlePaddle/PaddleOCR#10652]
# SER单卡训练
python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml

报错：
TypeError: __init__() got an unexpected keyword argument 'num_classes'

**Comment by situjunhao** [comment]
环境是ubuntu

**Comment by situjunhao** [comment]
我把配置文件的num_classes注释了的话，又会报错：yaml.composer.ComposerError: found undefined alias 'num_classes'
  in "configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml", line 40, column 16

**Comment by tranngominhtri** [comment]
I also meet the same problem. If I leave "checkpoints:" empty, this would be occur!

**Comment by zcgg2zhmm** [comment]
1. class_list.txt:
<img width="267" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/29967092/74fdfc1d-478c-4256-a420-d9e699bc7286">


2. yml文件：
<img width="440" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/29967092/da8f7034-293d-463d-94f3-abc5729357f7">


3. 有一种说法，叫做 num_classes = 2n-1。也就是说，class_list.txt里面有3行，所以num_classes = 2 * 3 - 1 = 5

**Comment by situjunhao** [comment]
谢谢解答，我用的是开源的XFUND数据集的标签好像就是2*4-1=7，好像不是标签数目的报错

**Comment by tranngominhtri** [comment]
> 谢谢解答，我用的是开源的XFUND数据集的标签好像就是2*4-1=7，好像不是标签数目的报错
Seem the error occur in LayoutXLMForTokenClassification class, which is take 2 arguments but, in this code, 3 arguments are given.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/113980642/78d5f00e-1d74-4931-a9df-fe6bb54feb95)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/113980642/ff7c8ca7-d83b-426b-b21b-0c5ea424e51f)

**Comment by tranngominhtri** [comment]
I uninstalled paddlenlp==2.6.2 and install 2.5.2 and it work well, hope that this thing can helpful with you!

**Comment by DouLiu95** [comment]
paddlenlp更新到2.6.0后出现的报错，ser和re出现了不同的问题，downgrade到2.5.2可以解决。

**Comment by xxentropy** [comment]
> paddlenlp更新到2.6.0后出现的报错，ser和re出现了不同的问题，downgrade到2.5.2可以解决。

请问你的paddlepaddle-gpu版本是多少，是在aistudio平台上跑的吗

**Comment by UserWangZz** [comment]
感谢讨论❤️
