### ISSUE TITLE
C++ 开启mkldnn经常异常

### ISSUE THREAD

**Issue by zhzhh201314** [PaddlePaddle/PaddleOCR#1065]
use_mkldnn设置成1时，偶尔能跑成功，经常报下面异常，异常都是出现在ZeroCopyRun()的时候，paddle编译版本2.0.0beta0.rec0都试过,1.8.5报的其他错误

C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Input Variable(Input) of (conv2d) Operator used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] (at D:\2.0.0-rc0\paddle\paddle\fluid\framework\operator.cc:1462)

**Comment by LDOUBLEV** [comment]
你的输入不对吧，提示报错是某个卷积层的输入不对

**Comment by singlebear** [comment]
> 你的输入不对吧，提示报错是某个卷积层的输入不对

Error: The Input Variable(Input) of conv2d Op used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] (at D:\2.0.0-beta0\paddle\paddle\fluid\framework\operator.cc:1385)
**我也遇到了同样的问题，c++版本。而且是同一个图片，开启mkldnn后，大概率报错崩溃，极少数时能识别成功。

VS的报错要么访问异常内存，要么是paddle的异常。
断电都在void DBDetector::Run 的    this->predictor_->ZeroCopyRun();**

0x00007FFE40B8F12E (paddle_fluid.dll)处(位于 2D.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。

0x00007FFEBB383B29 处(位于 2D.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000AB990F78F8 处。

**Comment by lvnengbin** [comment]
@zhzhh201314 
我也遇到了同样的问题，你解决了吗？

**Comment by jadehh** [comment]
遇到了同样的问题，

**Comment by qq61786631** [comment]
(InvalidArgument) The Input Variable(Input) of (conv2d) Operator used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] (at D:\2.0.0rc1\paddle\paddle\fluid\framework\operator.cc:1479)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
