### ISSUE TITLE
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by JackonLiu** [PaddlePaddle/PaddleOCR#1066]
(pipenv) D:\OCRServer\enviroment>python rec.py
Traceback (most recent call last):
  File "rec.py", line 15, in <module>
    from paddle.fluid.core_avx import AnalysisConfig, create_paddle_predictor
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

运行环境
Windows XP
python3.7.8
虚拟环境已安装paddlepaddle-1.7.2，相关依赖也都打包在虚拟环境中
已安装 VC_redist.x64

paddlepaddle版本过高的问题还是？

**Comment by LDOUBLEV** [comment]
paddle过低，安装1.8.5的paddle试试

**Comment by caobingsheng** [comment]
你xp能运行python3.7?
