### ISSUE TITLE
hubserving的multi_process问题

### ISSUE THREAD

**Issue by zhongluwang** [PaddlePaddle/PaddleOCR#1067]
配置文件设置了"use_multiprocess": true，但是服务只启动了6个线程，cpu利用率是600%，服务器有32核cpu，怎么全部使用？有没有办法设置最多使用的核数？

**Comment by ShenYuhan** [comment]
您可以使用 workers: 32。来启动32个线程

**Comment by zhongluwang** [comment]
> 您可以使用 workers: 32。来启动32个线程

@ShenYuhan 找到原因了，是这里[utility.py](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py)的129行，config.set_cpu_math_library_num_threads(6)
