### ISSUE TITLE
安装 scikit-image 错误

### ISSUE THREAD

**Issue by xu756** [PaddlePaddle/PaddleOCR#10671]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
- 运行指令/Command Code：pip install scikit-image 
- 完整报错/Complete Error Message：
`
aistudio@jupyter-2065331-6654914:~/PaddleOCR$ python3 tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_PP-OCRv3_det_infer/"
Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR/tools/infer/predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "/home/aistudio/PaddleOCR/ppocr/data/__init__.py", line 23, in <module>
    import skimage
ModuleNotFoundError: No module named 'skimage'

aistudio@jupyter-2065331-6654914:~/PaddleOCR$ pip install scikit-image
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement scikit-image (from versions: none)
ERROR: No matching distribution found for scikit-image

aistudio@jupyter-2065331-6654914:~/PaddleOCR$ pip install scikit-image -i https://pypi.mirrors.ustc.edu.cn/simple
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement scikit-image (from versions: none)
ERROR: No matching distribution found for scikit-image
`
<img width="1034" alt="iShot_2023-08-17_23 58 59" src="https://github.com/PaddlePaddle/PaddleOCR/assets/84982391/1fdcc8e2-a461-48c9-9335-51050afc326f">

**Comment by xu756** [comment]
已经好了，不过刚才几个小时，换什么环境都不行，建议检查一下aistudio

**Comment by whisky-12** [comment]
我也遇到了 然后去包管理里边 安装了最新的PaddleOCR工具包解决了
