### ISSUE TITLE
PPOCR2.7 C++ WIN10部署CPU推理速度慢

### ISSUE THREAD

**Issue by CCJGD** [PaddlePaddle/PaddleOCR#10676]
- 系统环境/System Environment： win10 i7 5500U
- 版本号/Version：PaddleOCR-2.7 paddle_inference-2.5.1

-mkldnn=false，600*400尺寸图片CPU推理时间 2.2s左右；
-mkldnn=true，推理时间40+s。

请问下什么原因？

还有什么办法可以提升低配机器cpu推理速度么？

**Comment by dengmingD** [comment]
用openvino c++，但须6代以上酷睿处理器，官方也是这么用的
