### ISSUE TITLE
PPLCNetNew找不到對應模型

### ISSUE THREAD

**Issue by cjwang0318** [PaddlePaddle/PaddleOCR#10685]
- 系统环境/System Environment：Ubuntu
- 版本号/Version：Paddle v2.5：  PaddleOCR： 问题相关组件/Related components： ppocr/modeling/necks/db_fpn.py
- 运行指令/Command Code：python tools/train.py -c ./ch_PP-OCRv4_det_cml.yml
- 
使用ch_PP-OCRv4_det訓連模型進行fintune時，將 ch_PP-OCRv4_det_cml.yml 中的  Backbone name: PPLCNetNew 找不到對應模型，如果改成**PPLCNetNewV3則會報錯 for i in range(len(in_channels)):TypeError: object of type 'int' has no len()**
可以麻煩請教一下原因嗎？謝謝。

- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/ppocr/modeling/architectures/__init__.py", line 34, in build_model
    arch = getattr(mod, name)(config)
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/ppocr/modeling/architectures/base_model.py", line 67, in __init__
    self.neck = build_neck(config['Neck'])
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/ppocr/modeling/necks/__init__.py", line 42, in build_neck
    module_class = eval(module_name)(**config)
  File "/home/cjwang/cjwang/PaddleOCR-release-2.7/ppocr/modeling/necks/db_fpn.py", line 240, in __init__
    for i in range(len(in_channels)):
TypeError: object of type 'int' has no len()

-

**Comment by SWHL** [comment]
I meet the same problem.

**Comment by gl94** [comment]
不是“PPLCNetNewV3”而是“PPLCNetV3”

**Comment by Taichipeace** [comment]
> 不是“PPLCNetNewV3”而是“PPLCNetV3”

PPLCNetV3 我改成了这个，但是也是一样的报错。

**Comment by kadimakipp** [comment]
Backbone:
        name: PPLCNetNew
        scale: 0.75
        det: true
        pretrained: false

**Comment by enemy1205** [comment]
添加det: true后，
训练会遇到另外报错
```
Traceback (most recent call last):
  File "/mnt/home/sp/projects/PaddleOCR/tools/train.py", line 228, in <module>
    main(config, device, logger, vdl_writer)
  File "/mnt/home/sp/projects/PaddleOCR/tools/train.py", line 199, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/mnt/home/sp/projects/PaddleOCR/tools/program.py", line 334, in train
    post_result = post_process_class(preds, batch[1])
  File "/mnt/home/sp/projects/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 275, in __call__
    results[k] = self.post_process(predicts[k], shape_list=shape_list)
  File "/mnt/home/sp/projects/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 229, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)
I1013 19:03:27.982057 679392 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
```

调试进入
`ppocr/postprocess/db_postprocess.py`文件中229lines
```
        for batch_index in range(pred.shape[0]):
            src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
            if self.dilation_kernel is not None:
                mask = cv2.dilate(
                    np.array(segmentation[batch_index]).astype(np.uint8),
                    self.dilation_kernel)
```
发现shappe_list是一个 batch_size * 640(height) *640(width) 的数组，
显然下标访问后取值无法返回src_h, src_w, ratio_h, ratio_w

**Comment by kadimakipp** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/5710

**Comment by ITccyhub** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "D:\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\architectures\__init__.py", line 34, in build_model
    arch = getattr(mod, name)(config)
  File "D:\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\architectures\distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "D:\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\architectures\base_model.py", line 67, in __init__
    self.neck = build_neck(config['Neck'])
  File "D:\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\necks\__init__.py", line 42, in build_neck
    module_class = eval(module_name)(**config)
  File "D:\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\necks\db_fpn.py", line 240, in __init__
    for i in range(len(in_channels)):
TypeError: object of type 'int' has no len()

**Comment by ITccyhub** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/77144099/336d8b9d-06f3-42de-bef2-c795692a2a20)
 an'zh按照这个改了还是报错

**Comment by ITccyhub** [comment]
加上 det: true 直接 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/77144099/83645f11-0347-4ff4-9290-cb33d476e3f7)

**Comment by sylarwcy** [comment]
> 把PPLCNetNew改成PPLCNetV3，在添加一行det: true ![image](https://user-images.githubusercontent.com/33504478/274790065-847401fb-b6b3-4d9d-a763-d11ec34cdb2d.png)

这个是正解

**Comment by sylarwcy** [comment]
![1115](https://github.com/PaddlePaddle/PaddleOCR/assets/20201759/8274fa0d-c4c4-4154-860c-322bd6f0ecdc)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/20201759/9a1e99af-d93e-4da1-a5b9-a7a6cf3c5546)

只有设定了det: true，才能走输出序列这个条件分支。后面RSEFPN解析in_channels时，按序列来解，才不会报错。

**Comment by KongXCai** [comment]
> 添加det: true后， 训练会遇到另外报错
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/home/sp/projects/PaddleOCR/tools/train.py", line 228, in <module>
>     main(config, device, logger, vdl_writer)
>   File "/mnt/home/sp/projects/PaddleOCR/tools/train.py", line 199, in main
>     program.train(config, train_dataloader, valid_dataloader, device, model,
>   File "/mnt/home/sp/projects/PaddleOCR/tools/program.py", line 334, in train
>     post_result = post_process_class(preds, batch[1])
>   File "/mnt/home/sp/projects/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 275, in __call__
>     results[k] = self.post_process(predicts[k], shape_list=shape_list)
>   File "/mnt/home/sp/projects/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 229, in __call__
>     src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
> ValueError: too many values to unpack (expected 4)
> I1013 19:03:27.982057 679392 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
> ```
> 
> 调试进入 `ppocr/postprocess/db_postprocess.py`文件中229lines
> 
> ```
>         for batch_index in range(pred.shape[0]):
>             src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
>             if self.dilation_kernel is not None:
>                 mask = cv2.dilate(
>                     np.array(segmentation[batch_index]).astype(np.uint8),
>                     self.dilation_kernel)
> ```
> 
> 发现shappe_list是一个 batch_size * 640(height) *640(width) 的数组， 显然下标访问后取值无法返回src_h, src_w, ratio_h, ratio_w

我也遇到了跟你一样的问题，请问你解决了吗？

**Comment by Sundragon1993** [comment]
@KongXCai just set:   cal_metric_during_train: false

**Comment by Double97828** [comment]
> 把PPLCNetNew改成PPLCNetV3，在添加一行det: true ![image](https://private-user-images.githubusercontent.com/33504478/274790065-847401fb-b6b3-4d9d-a763-d11ec34cdb2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc5MTEsIm5iZiI6MTcwOTE5NzYxMSwicGF0aCI6Ii8zMzUwNDQ3OC8yNzQ3OTAwNjUtODQ3NDAxZmItYjZiMy00ZDlkLWE3NjMtZDExZWMzNGNkYjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5MDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMjk4YjIxNThjMDk3N2FjNjAxMjIxMWVhOTA1YzU3MDAzNGYyODE3MjVkYjBjMWM0NDkzYzE2M2Q2YmRkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jigU3891VAlaPjUoHuLXFHNUQHFDcsRcL81T8M1UaN8)

这个student1和student2都要做修改么，我两个都修改了以后，有非常多层的参数无法加载不到模型中

**Comment by koala-cat** [comment]
> > 把PPLCNetNew改成PPLCNetV3，在添加一行det: true ![image](https://private-user-images.githubusercontent.com/33504478/274790065-847401fb-b6b3-4d9d-a763-d11ec34cdb2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc5MTEsIm5iZiI6MTcwOTE5NzYxMSwicGF0aCI6Ii8zMzUwNDQ3OC8yNzQ3OTAwNjUtODQ3NDAxZmItYjZiMy00ZDlkLWE3NjMtZDExZWMzNGNkYjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5MDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMjk4YjIxNThjMDk3N2FjNjAxMjIxMWVhOTA1YzU3MDAzNGYyODE3MjVkYjBjMWM0NDkzYzE2M2Q2YmRkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jigU3891VAlaPjUoHuLXFHNUQHFDcsRcL81T8M1UaN8)
> 
> 这个student1和student2都要做修改么，我两个都修改了以后，有非常多层的参数无法加载不到模型中

解决了么？我也是PPLCNetNew改成PPLCNetV3之后，student1和student2都加了 det: true，也试过单独加 student1，结果还是报错 
![1712718092497](https://github.com/PaddlePaddle/PaddleOCR/assets/20234514/af824057-0e0c-4945-a746-9f0fb6d1015e)

**Comment by 564142183** [comment]
配置加上还是报错，大佬解决了吗？
预训练模型：ch_PP-OCRv4_det_train
`Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 20
  # 输出训练模型路径
  save_model_dir: ./output/ch_PP-OCRv4
  save_epoch_step: 50
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  checkpoints: null
  # 预训练模型路径
  pretrained_model: ch_PP-OCRv4_det_train/best_accuracy
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true
Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        # 将PPLCNetNew改为PPLCNetV3
        name: PPLCNetV3
        # 添加det: True
        det: True
        scale: 0.75
        pretrained: false
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: true
      Head:
        name: DBHead
        k: 50
    Student2:
      pretrained: null
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: PPLCNetV3
        scale: 0.75
        pretrained: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: true
      Head:
        name: DBHead
        k: 50
    Teacher:
      pretrained: https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_cml_teacher_pretrained/teacher.pdparams
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: ResNet_vd
        in_channels: 3
        layers: 50
      Neck:
        name: LKPAN
        out_channels: 256
      Head:
        name: DBHead
        kernel_list:
        - 7
        - 2
        - 2
        k: 50
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - - Student
        - Teacher
      - - Student2
        - Teacher
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - Student
      - Student2
      maps_name: thrink_maps
      weight: 1.0
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list:
      - Student
      - Student2
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  c:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: DistillationDBPostProcess
  model_name:
  - Student
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: Student
Train:
  dataset:
    name: SimpleDataSet
    # 数据集路径
    data_dir: train_data
    # 数据集标签路径
    label_file_list:
      - train_data/det/train.txt
    ratio_list: [1.0]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
        total_epoch: 500
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
        total_epoch: 500
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 16
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: train_data
    label_file_list:
      - train_data/det/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
`
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/27718340/c06720b3-ece7-4c57-89a2-49af337791e7)

**Comment by mattheliu** [comment]
@564142183 你可以试一下 set: cal_metric_during_train: false

**Comment by 564142183** [comment]
@mattheliu 感谢大佬回复，把cal_metric_during_train改成false后训练还是报错

```shell
[2024-05-11 09:12:21,664] [ WARNING] dataloader_iter.py:707 - DataLoader 1 workers exit unexpectedly, pids: 5673
Traceback (most recent call last):
  File "/PaddleOCR/tools/train.py", line 255, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "/PaddleOCR/tools/train.py", line 208, in main
    program.train(
  File "/PaddleOCR/tools/program.py", line 304, in train
    for idx, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.10/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 826, in __next__
    self._reader.read_next_list()[0]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at ../paddle/fluid/operators/reader/blocking_queue.h:171)
```

**Comment by 564142183** [comment]
问题已解决，附项目地址：https://aistudio.baidu.com/projectdetail/7900653?sUid=3018256&shared=1&ts=1716019542135
