### ISSUE TITLE
paddleocr 训练卡死

### ISSUE THREAD

**Issue by SHOUshou0426** [PaddlePaddle/PaddleOCR#10683]
您好，paddleocr 算法工程师们，在aisudio 上测试paddleocr 使用100张jpg 使用ocr v3 模型，配置是v100 16GB 使用单卡训练 开始出现卡死，我尝试修改batch 为1。num_work 1 则还是出现卡死，尝试使用gpu 训练 也是出现卡死情况，使用gpu 查看 gpu 占用1k 显存，内存无反应，cpu 查看 占用2k，

**Comment by SHOUshou0426** [comment]
<img width="517" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/106730086/9f69e276-c217-43ec-993e-5047258ca58e">

**Comment by SHOUshou0426** [comment]
<img width="404" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/106730086/287936a9-c1f3-4d8c-a2c2-8b09a3fda161">
<img width="368" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/106730086/7d1aac92-8856-42c1-8d6c-d6403bec51ed">
<img width="1119" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/106730086/2ee6d42e-551b-42e0-9855-2d46d1870011">

**Comment by SHOUshou0426** [comment]
希望您可以给答复，感谢

**Comment by GM5GM5** [comment]
你没有使用gpu啊，你的gpu是false，应该是true。

**Comment by GM5GM5** [comment]
> 

gpu没有使用，use_gpu应该是true

**Comment by SHOUshou0426** [comment]
> > 
> 
> gpu没有使用，use_gpu应该是true

我之前尝试gpu 也是这样，所以才使用cpu ，目前我已经找到问题，是上传数据解压后数据损坏， 导致预处理一直找不到图片，同时也感谢您的回答
