### ISSUE TITLE
self.predictor.run([im])

### ISSUE THREAD

**Issue by beiweixiaoxu** [PaddlePaddle/PaddleOCR#1069]
不是报错问题，是想学习一下paddle内部。
就比如上面是文字检测推理时候的代码，我在哪里才能看到我输入的im，通过resnet-50得到特征图，然后再经过处理得到分割图...这些流程呢？我想多学习学习....

**Comment by beiweixiaoxu** [comment]
就比如说 预处理部分 图片的长和宽为什么要处理成32的倍数，这个代码里虽然说了"resize image to a size multiple of 32 which is required by the network"，但我还是想具体看看为什么...满足我的好奇心把。

**Comment by littletomatodonkey** [comment]
以resnet-vd结构为例，im经过网络是在这里进行的，会经过5次2倍降采样，所以建议输入可以被32整除，方便处理

https://github.com/PaddlePaddle/PaddleOCR/blob/4c95450a854ee5f15e9bc82f9a86c77a8cb0d75b/ppocr/modeling/backbones/rec_resnet_vd.py#L39
