### ISSUE TITLE
训练 icdar2015文本识别模型

### ISSUE THREAD

**Issue by SxyNoPeace** [PaddlePaddle/PaddleOCR#1070]
会出现以下信息：
2020-10-31 22:33:23,501-INFO: Warning in ppocr/data/rec/img_tools.py: Wrong data type.Excepted string with length between 1 and 25, but got '0'. Label is '...
2020-10-31 22:33:24,091-INFO: Warning in ppocr/data/rec/img_tools.py: Wrong data type.Excepted string with length between 1 and 25, but got '0'. Label is '...
'0'. Label is '...
 does not exist!:26,086-INFO: ./train_data/ic15_data/
 does not exist!:27,630-INFO: ./train_data/ic15_data/

请问是什么原因，确认标签是使用\t分隔开

 rec_icdar15_train.yml 设置character_dict_path: ./ppocr/utils/dict/ic15_dict.txt

训练指令
python3 tools/train.py -c configs/rec/rec_icdar15_train.yml -o Global.epoch_num=500 2>&1 | tee train_rec.log

**Comment by littletomatodonkey** [comment]
可以检查下train list是否正确

**Comment by ChChwang** [comment]
我也碰到了同样的问题，另外如果训练中文数据，acc=0，是什么原因呢？

**Comment by ChChwang** [comment]
> 可以检查下train list是否正确

应该不是这个原因，另外训练中文，acc=0，是什么原因呢。字典是中文6000+

**Comment by SxyNoPeace** [comment]
> > 可以检查下train list是否正确
> 
> 应该不是这个原因，另外训练中文，acc=0，是什么原因呢。字典是中文6000+

确实是与train.txt有关，更换自定义数据集后没有出现问题。训练中文acc=0，我没遇到这情况，抱歉

**Comment by cuiyong127** [comment]
> 会出现以下信息：
> 2020-10-31 22:33:23,501-INFO: Warning in ppocr/data/rec/img_tools.py: Wrong data type.Excepted string with length between 1 and 25, but got '0'. Label is '...
> 2020-10-31 22:33:24,091-INFO: Warning in ppocr/data/rec/img_tools.py: Wrong data type.Excepted string with length between 1 and 25, but got '0'. Label is '...
> '0'. Label is '...
> does not exist!:26,086-INFO: ./train_data/ic15_data/
> does not exist!:27,630-INFO: ./train_data/ic15_data/
> 
> 请问是什么原因，确认标签是使用\t分隔开
> 
> rec_icdar15_train.yml 设置character_dict_path: ./ppocr/utils/dict/ic15_dict.txt
> 
> 训练指令
> python3 tools/train.py -c configs/rec/rec_icdar15_train.yml -o Global.epoch_num=500 2>&1 | tee train_rec.log

下载的训练集标签rec_gt_train.txt中有标注是“...” 删除这个就可以了
