### ISSUE TITLE
文本方向分类模型训练相关问题

### ISSUE THREAD

**Issue by strWuYaoJu** [PaddlePaddle/PaddleOCR#1071]
1.环境：
        CPU   4
        RAM  32GB
        GPU   v100
        显存   16GB
        磁盘  100GB
2.数据集
       （1）把数据集分为train、test文件夹存放在./train_data/cls/目录下，标注好cls_gt_train.txt、cls_gt_test.txt文件并放在./train_data/cls/目录下；
       （2）修改./configs/cls/cls_reader.yml文件 中训练、测试对应的img_set_dir和 label_file_path的值
                 TrainReader:
                                    img_set_dir: ./train_data/cls
                                    label_file_path: ./train_data/cls/cls_gt_train.txt
                 EvalReader:
                                    img_set_dir: ./train_data/cls
                                    label_file_path: ./train_data/cls/cls_gt_test.txt

3.训练
      执行python tools/train.py -c configs/cls/cls_mv3.yml -o Global.pretrain_weights=./pretrain_models/ch_ppocr_mobile_v1.1_cls_train/best_accuracy

报错：
     ----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by WenmuZhou** [comment]
你这是数据部分报错了，看看图片路径有没有问题吧，label.txt里记载的路径加上imagedir才应该是完整的图片路径

**Comment by strWuYaoJu** [comment]
> 你这是数据部分报错了，看看图片路径有没有问题吧，label.txt里记载的路径加上imagedir才应该是完整的图片路径

**Comment by strWuYaoJu** [comment]
> > 你这是数据部分报错了，看看图片路径有没有问题吧，label.txt里记录的路径加上imagedir才应该是完整的图片路径
你好，我的图片路径如下：
训练的：
          train_data/cls/train/img_0000.bmp	0
          train_data/cls/train/img_0001.bmp	0
          train_data/cls/train/img_0002.bmp	0
          ........

测试的：
           train_data/cls/test/img_0650.bmp	0
           train_data/cls/test/img_0651.bmp	0
           train_data/cls/test/img_0652.bmp	0
           .......

**Comment by strWuYaoJu** [comment]
cls_gt_test.txt如下：
train_data/cls/test/img_0650.bmp	0
train_data/cls/test/img_0651.bmp	0
train_data/cls/test/img_0652.bmp	0
train_data/cls/test/img_0653.bmp	0
train_data/cls/test/img_0654.bmp	0
train_data/cls/test/img_0655.bmp	0
train_data/cls/test/img_0656.bmp	0
train_data/cls/test/img_0657.bmp	0
train_data/cls/test/img_0658.bmp	180
train_data/cls/test/img_0659.bmp	180
train_data/cls/test/img_0660.bmp	180
..............................................

cls_gt_train.txt如下：
train_data/cls/train/img_0000.bmp	0
train_data/cls/train/img_0001.bmp	0
train_data/cls/train/img_0002.bmp	0
train_data/cls/train/img_0003.bmp	0
train_data/cls/train/img_0004.bmp	0
train_data/cls/train/img_0005.bmp	0
train_data/cls/train/img_0006.bmp	0
train_data/cls/train/img_0007.bmp	0
train_data/cls/train/img_0008.bmp	0
train_data/cls/train/img_0009.bmp	0
...................

真不知道哪里错，训练文字检测的路径和文字方向路径不一样？？？？？，不能统一吗？？？？

**Comment by strWuYaoJu** [comment]
@WenmuZhou
cls_gt_test.txt如下：
train_data/cls/test/img_0650.bmp 0
train_data/cls/test/img_0651.bmp 0
train_data/cls/test/img_0652.bmp 0
train_data/cls/test/img_0653.bmp 0
train_data/cls/test/img_0654.bmp 0
train_data/cls/test/img_0655.bmp 0
train_data/cls/test/img_0656.bmp 0
train_data/cls/test/img_0657.bmp 0
train_data/cls/test/img_0658.bmp 180
train_data/cls/test/img_0659.bmp 180
train_data/cls/test/img_0660.bmp 180
..............................................

cls_gt_train.txt如下：
train_data/cls/train/img_0000.bmp 0
train_data/cls/train/img_0001.bmp 0
train_data/cls/train/img_0002.bmp 0
train_data/cls/train/img_0003.bmp 0
train_data/cls/train/img_0004.bmp 0
train_data/cls/train/img_0005.bmp 0
train_data/cls/train/img_0006.bmp 0
train_data/cls/train/img_0007.bmp 0
train_data/cls/train/img_0008.bmp 0
train_data/cls/train/img_0009.bmp 0
...................

真不知道哪里错，训练文字检测的路径和文字方向路径不一样？？？？？，不统一吗？？？？

**Comment by WenmuZhou** [comment]
代码里已经指出是data reader的错误，那么应该通过如下步骤去排查
1. 排查图片路径是否错误
2. 排查图片路径和分隔符之间是不是\t
3. 排查代码错误

**Comment by SealQ** [comment]
@strWuYaoJu 您的这个文本方向分类最终的效果如何？

**Comment by strWuYaoJu** [comment]
@SealQ 我这里原因还没找到，解决后，才可以验证

**Comment by SealQ** [comment]
@strWuYaoJu  方便交换联系方式共同学习么？

**Comment by strWuYaoJu** [comment]
@WenmuZhou 现在执行训练还是不行，报如下问题：
AttributeError: 'int' object has no attribute 'split'
Exception in thread Thread-1:
Traceback (most recent call last):

**Comment by strWuYaoJu** [comment]
@SealQ 给微信号，我加你

**Comment by SealQ** [comment]
@15172875608

**Comment by WenmuZhou** [comment]
> @WenmuZhou 现在执行训练还是不行，报如下问题：
> AttributeError: 'int' object has no attribute 'split'
> Exception in thread Thread-1:
> Traceback (most recent call last):

感觉是标注文件的问题

**Comment by 1156150793** [comment]
> 执行python工具/train.py -c configs / cls / cls_mv3.yml -o Global.pretrain_weights =./ pretrain_models / ch_ppocr_mobile_v1.1_cls_train / best_accuracy
中./pretrain_models/ch_ppocr_mobile_v1.1_cls_train/best_accuracy这个文件在哪呢

**Comment by littletomatodonkey** [comment]
https://paddleocr.bj.bcebos.com/20-09-22/cls/ch_ppocr_mobile_v1.1_cls_train.tar

官网首页有下载链接

![image](https://user-images.githubusercontent.com/14270174/98235133-5f599e00-1f9c-11eb-896c-45d3a16fe3bb.png)

**Comment by lycowner** [comment]
你好，我和你一样的问题，请问你是怎样解决的呢？谢谢

**Comment by strWuYaoJu** [comment]
@lycowner 我之前是标注文件label里面写得不对，直接写文件名+角度，就好了

**Comment by shuihsaiu** [comment]
请问楼主最后是怎么解决的，跟你出现一样的错误。

**Comment by strWuYaoJu** [comment]
谢谢你的来信！
