### ISSUE TITLE
能部署在arm架构ubunt上吗

### ISSUE THREAD

**Issue by LoeWHJ** [PaddlePaddle/PaddleOCR#1074]
能部署在这种开发板上吗

**Comment by littletomatodonkey** [comment]
可以基于Paddle-Lite进行部署，Paddle-Lite是支持arm linux的

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
