### ISSUE TITLE
训练卡死

### ISSUE THREAD

**Issue by yuliangxiao** [PaddlePaddle/PaddleOCR#1075]
训练的过程中卡死，不是验证的时候，经常训练一两天之后卡死，我应该怎么查找原因？gpu利用率为0，但是显存什么的还占用，内存是不占用的。

**Comment by littletomatodonkey** [comment]
可以减小queue size，参考这个链接：

https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q335%E8%AF%BB%E6%95%B0%E6%8D%AE%E8%BF%9B%E7%A8%8B%E6%95%B0%E8%AE%BE%E7%BD%AE48%E6%97%B6%E8%AE%AD%E7%BB%83%E4%B8%80%E4%BC%9A%E8%BF%9B%E7%A8%8B%E6%8E%A5%E8%BF%9Edefunct%E5%90%8Egpu%E5%88%A9%E7%94%A8%E7%8E%87%E4%B8%80%E7%9B%B4%E4%B8%BA0%E5%8D%A1%E6%AD%BB

**Comment by yuliangxiao** [comment]
我尝试过这个修改了，改程320了，还是卡死，我需要改程更小吗？内存32，gtx1080ti，谢谢。

**Comment by littletomatodonkey** [comment]
嗯嗯，可以试下再改小点，把reader的num_worker再设置的小一些，train batch size也可以弄小些，默认256，你可以设置为128或者64

**Comment by yuliangxiao** [comment]
谢谢，我试一下。

**Comment by yuliangxiao** [comment]
我尝试过更改queue size了，虽然会延长训练时间但是还是最后会卡死，我 内存32的，比如原来训练1天就占满了卡死了，更改参数之后现在可以训练2天了，但是最终还是会卡死，这个问题没有别的解决方案了吗？谢谢。

**Comment by yuliangxiao** [comment]
还有就是训练一天的时候最大内存占用为22g，但是到第二天最大就占到30多g了。

**Comment by littletomatodonkey** [comment]
bs这块需要稍微调小一些，在不hang住的情况下，内存使用是有上限的
