### ISSUE TITLE
Is it possible to train ppocr_v4 on a 6GB GPU? I am running out of memory

### ISSUE THREAD

**Issue by BMukhtar** [PaddlePaddle/PaddleOCR#10783]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows, 6GB GPU RTX 3060, RAM 32GB, core-I712700H
- 版本号/Version：2.7 release Paddle：2.4.2.post117  PaddleOCR：4 问题相关组件/Related components：

Question:
Is it possible to train ppocr_v4 on a 6GB GPU? I am running out of memory

**Comment by crjxixixi** [comment]
ValueError: (InvalidArgument) The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [128, 240, 256].
[Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at ../paddle/phi/infermeta/binary.cc:475)
请问你在训练的时候有遇到这个问题吗？请问你是怎么解决的？

**Comment by hungtrieu07** [comment]
> Please provide the following information to quickly locate the problem
> 
> * System Environment: Windows, 6GB GPU RTX 3060, RAM 32GB, core-I712700H
> * Version:2.7 release Paddle:2.4.2.post117 PaddleOCR:4 Related components:
> 
> Question: Is it possible to train ppocr_v4 on a 6GB GPU? I am running out of memory

maybe downsize the batchsize help your problem, i'm using colab pro with T4 GPU, after change batchsize to 64, I can train my model and GPU memory about ~10/15GB

**Comment by BMukhtar** [comment]
downsizing didn't help firstly, but after I downsized first_bs too it worked in en_PP-OCRv4_rec.yml config

Thanks!

Also tried on colab free, but it trains very slowly with T4

**Comment by BMukhtar** [comment]
> 

nah, better to ask in another issue

**Comment by BMukhtar** [comment]
downsizing batch_size_per_card and first_bs solves the problem
