### ISSUE TITLE
训练文字检测模型，在验证阶段报错

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#1078]
将ccpd数据集的车牌区域作为文字检测数据集（100K），MobileNetV3_large_x0_5_pretrained作为预训练模型，训练报错。
每次出现在验证阶段。
日志和配置如下：
[train_det.log](https://github.com/PaddlePaddle/PaddleOCR/files/5473056/train_det.log)

试着修改以下三个地方，问题依旧。
return paddle.reader.multiprocess_reader(readers, False, queue_size=200)
test_batch_size_per_card: 1
num_workers: 1

环境：
Ubuntu16.04
GPU 2080 11G
Cuda 10.0
cuDNN 7.6

Paddlepaddle-gpu 2.0.0b0
PaddleOCR v1.1

**Comment by simplew2011** [comment]
ubuntu16.04
CPU 2080 11G
cuda 10.0
cuDNN 7.6

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/97850849-895a5880-1d2f-11eb-8834-0bf567e32b53.png)

你有改其他地方吗，数据处理哪些，报错提示这里，elementwise_add的两个输入shape不匹配，可以根据报错信息调试下

**Comment by simplew2011** [comment]
> ![image](https://user-images.githubusercontent.com/26592129/97850849-895a5880-1d2f-11eb-8834-0bf567e32b53.png)
> 
> 你有改其他地方吗，报错提示[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/2b16323080bbf503828b96f1ef531dc1074a1272/ppocr/modeling/heads/det_db_head.py#L160)，elementwise_add的两个输入shape不匹配，可以根据报错信息调试下

只修改过两个配置表，和reader_main.py中的：
return paddle.reader.multiprocess_reader(readers, False, queue_size=200)
其他没修过

**Comment by simplew2011** [comment]
订正：
修改了_reader.yml文件的test_image_shape,。因为ccpd数据集的图像尺寸是720*1160,。
原来：
EvalReader:
  test_image_shape: [736, 1280]
修改后：
EvalReader:
  test_image_shape: [720, 1160]

图像尺寸无法32整除导致的报错么，可否在代码上判断，自动padding.

**Comment by MissPenguin** [comment]
> 订正：
> 修改了_reader.yml文件的test_image_shape,。因为ccpd数据集的图像尺寸是720*1160。
> 原来：
> EvalReader:
> test_image_shape: [736, 1280]
> 修改后：
> EvalReader:
> test_image_shape: [720, 1160]
> 
> 图像尺寸无法32整除导致的报错么，可否在代码上判断，自动padding.

对的，需要是32的倍数。有需要的话可以自己试着改下代码。
