### ISSUE TITLE
默认不支持输入灰度图？

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1079]
void DBDetector::Run(const cv::Mat &img,
                     std::vector<std::vector<std::vector<int>>> &boxes) {
  float ratio_h{};
  float ratio_w{};

  cv::Mat srcimg;
  cv::Mat resize_img;
  img.copyTo(srcimg);
  this->resize_op_.Run(img, resize_img, this->max_side_len_, ratio_h, ratio_w);

  this->normalize_op_.Run(&resize_img, this->mean_, this->scale_,
                          this->is_scale_);

  std::vector<float> input(1 * 3 * resize_img.rows * resize_img.cols, 0.0f);
  this->permute_op_.Run(&resize_img, input.data());

**里的this->normalize_op_.Run(&resize_img, this->mean_, this->scale_, this->is_scale_);函数中，直接默认图片是3通道进行计算**
void Normalize::Run(cv::Mat *im, const std::vector<float> &mean,
                    const std::vector<float> &scale, const bool is_scale) {
  double e = 1.0;
  if (is_scale) {
    e /= 255.0;
  }
  (*im).convertTo(*im, CV_32FC3, e);
  for (int h = 0; h < im->rows; h++) {
    for (int w = 0; w < im->cols; w++) {
      im->at<cv::Vec3f>(h, w)[0] =
          (im->at<cv::Vec3f>(h, w)[0] - mean[0]) * scale[0];
      im->at<cv::Vec3f>(h, w)[1] =
          (im->at<cv::Vec3f>(h, w)[1] - mean[1]) * scale[1];
      im->at<cv::Vec3f>(h, w)[2] =
          (im->at<cv::Vec3f>(h, w)[2] - mean[2]) * scale[2];
    }
  }
}

**就会导致输入图像为单通道图像时直接崩了。paddleOCR是必须输入图像是3通道的么？如果我修改相关部分的代码使其灰度图能正常转换为单通道数据，最终通用模型能否正常识别？**

**Comment by littletomatodonkey** [comment]
提供的模型的图像输入是三通道的，因此这里设置了输入三通道，如果你的模型输入是单通道图像训练得到的，可以把这里修改下

**Comment by littletomatodonkey** [comment]
如果想测试灰度图像，可以先转化为三通道图像，再送入网络中
