### ISSUE TITLE
请问，【3自定义模型】样例中的四个path是不是必须的

### ISSUE THREAD

**Issue by ZGuangW** [PaddlePaddle/PaddleOCR#10792]
请问，【3自定义模型】样例中的四个path是不是必须的
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/whl.md#3-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B
还有，{your_rec_char_dict_path}这个路径指的是什么路径？模型下载的好像只有det，rec，cls，所以这个{your_rec_char_dict_path}指的是什么？

**Comment by LumenYan** [comment]
是必须的，四个路径分别指的是检测模型的存放位置、识别模型存放位置、数据字典的存放位置和方向分类器的存放位置，这个{your_rec_char_dict_path}指的是你自己的设备上相应的文件存放位置
