### ISSUE TITLE
__init__() got an unexpected keyword argument 'threshold'

### ISSUE THREAD

**Issue by qihangf** [PaddlePaddle/PaddleOCR#10801]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.7.0.2 问题相关组件/Related components：
- 运行指令/Command Code：# 加载模型
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)
- 完整报错/Complete Error Message
Traceback (most recent call last):
  File "test1.py", line 7, in <module>
    model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
TypeError: __init__() got an unexpected keyword argument 'threshold'

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by weiwei1392** [comment]
How do you fix this problem？
