### ISSUE TITLE
使用CPU编译fastdeploy编译exe后应用程序无法正常启动(0xc0000142)

### ISSUE THREAD

**Issue by Akumio** [PaddlePaddle/PaddleOCR#10800]
使用opencv460编译CPU版本的fastdeploy库后程序无法正常启动

**Comment by tangzhezhi** [comment]
这种情况一般是 依赖lib 没有加载， 就是那个 bat脚本要先执行，把依赖dll都搞出来，然后和你的exe放一起。

**Comment by Akumio** [comment]
> 这种情况一般是 依赖lib 没有加载， 就是那个 bat脚本要先执行，把依赖dll都搞出来，然后和你的exe放一起。

用官方opencv3416编出来的库放在同等目录下可以正常推理，根据官方fastdeploy编译指定opencv460库时将同样的dll放在一起就会报错，编译库的方法与官方一致只是opecnv库版本不同，运行exe则会报错。

**Comment by Akumio** [comment]
![84a31144dc77e2fd6aa243ba0cc50fa](https://github.com/PaddlePaddle/PaddleOCR/assets/37945925/d9f07e5f-4d94-4064-ad31-da6d1922e8c9)
同样的fastdeploy编译流程试了几次还是同样的问题，请问下是否与paddle_inferrnce库有关
