### ISSUE TITLE
RAM Issue During Inference

### ISSUE THREAD

**Issue by Taghreed7878** [PaddlePaddle/PaddleOCR#10808]
Hello,

I'm facing a big issue with RAM usage. I implemented an OCR service based on paddleocr, the service is deployed, while the application is running, a request is sent and the system responds, and so on for a few times, then at some point the server RAM is filled and the only thing that frees it is to interrupt the application execution and run it again. I don't understand why the RAM is still filled after the system response, and I don't know how to handle it. 

The same thing happens when a batch of images is sent, they are handled with multiprocessing, but the same issue happens.

**Comment by praxis-abhishek** [comment]
Hey bro did you find the solution? i am also facing same issue
