### ISSUE TITLE
请问下C++推理端定义PPOCR变量时需要如何指定路径呢

### ISSUE THREAD

**Issue by Akumio** [PaddlePaddle/PaddleOCR#10818]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file /inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1500)

**Comment by qq61786631** [comment]
请问如何解决的，同样的问题

**Comment by Akumio** [comment]
> 
在arg.h中指定文件路径
