### ISSUE TITLE
使用PPOCRLabel在导出识别标签"difficult": true的情况下，不会导出识别结果

### ISSUE THREAD

**Issue by JackLee1** [PaddlePaddle/PaddleOCR#10830]
在使用ppocr 2.7中的PPOCRLabel对图片识别进行标注时，生成的标注文件Label.txt中有些"difficult": true， 有些"difficult": false。在界面File->Export Recognition Result时，对于"difficult": true的标签的结果不出导出。

通过查看PPOCRLabel.py文件的源代码，发现2663行：
                    for i, label in enumerate(self.PPlabel[idx]):
                        if label['difficult']:
                            continue
                        img_crop = get_rotate_crop_image(img, np.array(label['points'], np.float32))
                        img_name = os.path.splitext(os.path.basename(idx))[0] + '_crop_' + str(i) + '.jpg'
                        cv2.imwrite(crop_img_dir + img_name, img_crop)
                        f.write('crop_img/' + img_name + '\t')
                        f.write(label['transcription'] + '\n')
不知道设计过程中，为什么识别标签"difficult": true的结果不导出？

**Comment by lvjianjin** [comment]
因为困难的就说明很多质量很差的，甚至都看不清的垃圾数据，这部分就被舍弃，不参加模型训练。
