### ISSUE TITLE
pdserving部署PaddleOCR v4模型失败，v3模型正常运行

### ISSUE THREAD

**Issue by jinxiqinghuan** [PaddlePaddle/PaddleOCR#10841]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：2.7.0 Paddle：  PaddleOCR： 问题相关组件/Related components：pdserving
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

部署v4模型的pdserving时，当进行推理时，回出现以下错误。而使用v3模型正常，无法定位问题所在。
```
PROFILE pid:231955      prepack_0#@DAGExecutor_0:1694053071818188 prepack_0#@DAGExecutor_1:1694053071819021 postpack_0#@DAGExecutor_0:1694053073971385 postpack_0#@DAGExecutor_1:1694053073971522 call_0#DAG-0_0:1694053071818126 call_0#DAG-0_1:1694053073971539 

PROFILE pid:231955      prepack_1#@DAGExecutor_0:1694053084056944 prepack_1#@DAGExecutor_1:1694053084057393 postpack_1#@DAGExecutor_0:1694053084226369 postpack_1#@DAGExecutor_1:1694053084226451 call_1#DAG-1_0:1694053084056906 call_1#DAG-1_1:1694053084226468 
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no): yes

**Comment by jinxiqinghuan** [comment]
问题已解决！

**Comment by jinxiqinghuan** [comment]
无效问题

**Comment by wyeye** [comment]
请问如何解决的
