### ISSUE TITLE
TypeError: the 'package' argument is required to perform a relative import for '.module'

### ISSUE THREAD

**Issue by 1290726334** [PaddlePaddle/PaddleOCR#1085]
![image](https://user-images.githubusercontent.com/16836773/97870024-51faa480-1d4d-11eb-8888-0e74a4cedb91.png)
![image](https://user-images.githubusercontent.com/16836773/97870042-57f08580-1d4d-11eb-9bf9-f81a1a7bca32.png)
![image](https://user-images.githubusercontent.com/16836773/97870063-5fb02a00-1d4d-11eb-9b35-2934f4139751.png)

**Comment by MissPenguin** [comment]
用的python38吗，换3.5～3.7试试？

**Comment by YY007H** [comment]
我也遇到了，不知道是什么原因
