### ISSUE TITLE
iOSDemo中的net_ocr1->Run()特别卡，怎么优化？

### ISSUE THREAD

**Issue by GreatTreeZX** [PaddlePaddle/PaddleOCR#1086]

**Comment by heXiangpeng** [comment]
你的是什么版本？可以运行，我这里运行都出错

**Comment by GreatTreeZX** [comment]
> 你的是什么版本？可以运行，我这里运行都出错

你那个错应该是.nb路径引用不对，移除重新引用下

**Comment by heXiangpeng** [comment]
> > 你的是什么版本？可以运行，我这里运行都出错
> 
> 你那个错应该是.nb路径引用不对，移除重新引用下

你的是直接运行deploy的版本？

**Comment by GreatTreeZX** [comment]
> 你的是什么版本？可以运行，我这里运行都出错

你那个错应该是.nb路径引用不对，移除重新引用下

> > > 你的是什么版本？可以运行，我这里运行都出错
> > 
> > 
> > 你那个错应该是.nb路径引用不对，移除重新引用下
> 
> 你的是直接运行deploy的版本？

是

**Comment by heXiangpeng** [comment]
> > 你的是什么版本？可以运行，我这里运行都出错
> 
> 你那个错应该是.nb路径引用不对，移除重新引用下
> 
> > > > 你的是什么版本？可以运行，我这里运行都出错
> > > 
> > > 
> > > 你那个错应该是.nb路径引用不对，移除重新引用下
> > 
> > 
> > 你的是直接运行deploy的版本？
> 
> 是

这个版本有点老了

**Comment by GreatTreeZX** [comment]
> > > 你的是什么版本？可以运行，我这里运行都出错
> > 
> > 
> > 你那个错应该是.nb路径引用不对，移除重新引用下
> > > > > 你的是什么版本？可以运行，我这里运行都出错
> > > > 
> > > > 
> > > > 你那个错应该是.nb路径引用不对，移除重新引用下
> > > 
> > > 
> > > 你的是直接运行deploy的版本？
> > 
> > 
> > 是
> 
> 这个版本有点老了

你运行的什么版本，从哪里下载的？

**Comment by heXiangpeng** [comment]
预测库和模型在demo里面有点老了，需要自己手动更新预测库和模型，但是运行会出错

**Comment by GreatTreeZX** [comment]
> 预测库和模型在demo里面有点老了，需要自己手动更新预测库和模型，但是运行会出错

兄弟，这个解决了吗？

**Comment by littletomatodonkey** [comment]
你好，要不使用最新的预测库看下呢？run函数其实就是主要的预测过程

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
