### ISSUE TITLE
PP-OCRv4 在C++环境下，启用mkldnn加速后，识别结果全部错误

### ISSUE THREAD

**Issue by qq61786631** [PaddlePaddle/PaddleOCR#10885]
- 系统环境：win11
- 版本号/Paddle2.3.2   PaddleOCR：2.7
- 运行环境：C++
 
如题，对于超轻量PP-OCRv4模型，未开启enable_mkldnn指令时，结果正确；但在开启enable_mkldnn后，识别时间变长，且检测和识别的结果均错误。

对于高精度模型PP-OCRv4模型，是否开启enable_mkldnn对运算时间无影响，识别结果均正确，但是计算时间是轻量版本的40倍，明显异常。

而对于PP-OCRv3版本，则没有以上问题，请大师们帮看看啥原因啊

**Comment by qq61786631** [comment]
python环境下，启用cpu模式，未开启enable_mkldnn的话，检测结果都是OK的；开启enable_mkldnn，绝大部分结果正确是正确的，但是计算时间也慢的很多。

**Comment by qq61786631** [comment]
有同样碰到这种情况的吗，之前问题还有回复，现在咋啥都没了。。。

**Comment by hiroi-sora** [comment]
同样问题+1。release2.6和2.7的c++推理代码应该是完全没有改动过的。补充一下我的测试结果，用2.6的c++推理代码测试，前端是 [Umi-OCR_v2](https://github.com/hiroi-sora/Umi-OCR_v2) ：

### V4 无mkl，结果正常，速度偏慢。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/95b5eb92-86fb-4e12-ae70-363c72359020)

### V4 + mkldnn，结果异常，速度极慢。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/b0d602f5-8c27-4f25-8160-c45fcf93f9ba)
检测结果也是完全错误（红框）：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/b711ae02-1167-4004-ae77-f252118cdb83)

### V4-server + mkldnn，结果正常，速度快。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/bfa7bba1-c5bf-435b-bc17-6c0982f1c5a4)

### V4-server 无mkl，结果正常，速度慢。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/f657f414-9a67-461c-87e6-421428e7ecf1)

对比：

### V3 无mkl，结果正常，速度偏慢。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/9a5b0302-1164-4338-9b35-cb393208d707)

### V3 + mkldnn，结果正常，速度非常快。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/56373419/2a4c8b49-6c5c-4586-82bd-122f29f8ac1f)

**Comment by qq61786631** [comment]
非常感谢，现在更换了Fastdeploy后，一切正常了。特此关贴。 @hiroi-sora

**Comment by chendanikor** [comment]
@steven-spec 不要用mkldnn，用OpenVINO，速度更快

**Comment by steven-spec** [comment]
> OpenVINO

好的谢谢！

**Comment by mrg79433283** [comment]
> @steven-spec 不要用mkldnn，用OpenVINO，速度更快

请教一下，你用fastdeploy在window server 2012上试过吗，或者有没有遇到过“fastdeploy_main: 找不到指定的模块”的问题呢

**Comment by caicaicai** [comment]
我发现用了OpenVINO之后，有的地方识别精度有下降。。比如他会帮4识别成1

**Comment by SeeYouAgainZm** [comment]
C++ 环境下，如何调用mkl对ocr加速呢
