### ISSUE TITLE
训练文字检测模型，测试效果差

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#1088]
使用ccpd训练车牌检测（100k），db模型训练，loss至0.3。
使用
python tools/infer_det.py -c configs/det/det_mv3_db_v1.1_plate.yml -o Global.checkpoints=./output/det_db/best_accuracy
预测结果效果很差，看issue
#214 
#647 
提示是尺寸缩放问题，我把db_process.py中self.resize_type = 1重设为self.resize_type = 0，效果尚可。
问题：为什么训练好的模型，直接进行测试效果差，改代码效果可以。这种训练和推理尺寸不一致的问题，在crnn识别模型里也存在（#1044），是否可以优化掉。

![image](https://user-images.githubusercontent.com/66729924/97963511-401f0d00-1df2-11eb-95ba-d891e7bf0501.png)

**Comment by MissPenguin** [comment]
配置用的icdar2015的reader，里面的参数都是针对icdar2015这个集合的，是为了大家方便对齐我们的icdar2015上的指标，所以换了别的数据后shape不适用，需要调整。也可以用tools/infer/predict_*中的脚本进行预测，这里不存在shape问题。
