### ISSUE TITLE
进行PPocrv4训练时，报提示det中不支持yml文件中的backbone，PPLCNetNew

### ISSUE THREAD

**Issue by keyfall** [PaddlePaddle/PaddleOCR#10886]
### 使用train.py进行PPocrv4训练时，报提示det中不支持yml文件中的backbone，PPLCNetNew：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/21198605/9db863be-404d-4192-9962-e12f863ce4f1)

运行命令：`python tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml`

**Comment by SWHL** [comment]
与 #11796 重复了
