### ISSUE TITLE
cpp_inter使用自训练的文本识别模型崩溃

### ISSUE THREAD

**Issue by yinqinggong** [PaddlePaddle/PaddleOCR#10889]
- 系统环境/System Environment：
win10, vs2019
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddlepaddle-gpu==2.5.1 cudatoolkit=10.2
paddleocr==2.7.0.2目前最新
- 运行指令/Command Code：
.\build\Release\ppocr.exe system --det_model_dir=.\build\Release\ch_PP-OCRv3_det_infer --rec_model_dir=.\build\Release\ch_PP-OCRv3_rec_infer --image_dir=D:\6.jpg
- 完整报错/Complete Error Message：
调试ppocr发现崩溃在PaddleOCR-release-2.7\deploy\cpp_infer\src\ocr_rec.cpp文件第76行` this->predictor_->Run();`
0x00007FFA75B1C023 (paddle_inference.dll) (ppocr.exe 中)处有未经处理的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。
 - 训练和导出模型：
```
 python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv3_rec_train/best_accuracy
python tools/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./output/rec_ppocr_v3_distillation/best_accuracy  Global.save_inference_dir=./output/rec_db_inference/
```
尝试了PaddleOCR2.7和2.6版本，训练出来的中文检测模型ch_PP-OCRv3_det_infer是可以的，中文识别模型ch_PP-OCRv3_rec_infer就出现崩溃，英文en_PP-OCRv3_rec_infer训练出来也是崩溃，是不是算法更新后cpp_inter模块没有更新？还是我流程哪里有问题？
训练使用的ch_PP-OCRv3_rec_distillation.yml基本就是修改数据集路径和batch_size，num_workers: 0，其他跟保持官方一致

**Comment by yinqinggong** [comment]
找到原因了，是paddlepaddle-gpu==2.5.1跟下载的win10版paddle_inference2.3.2.zip不匹配导致，感谢ppocr团队的辛苦付出

**Comment by hanliangwei** [comment]
你好，请问可以分享一下最终可以用的版本对应关系吗，我也是遇到了转换后在cpp_inference中直接crash，甚至从官网下载的训练模型，直接转为推理模型，在cpp_infer中也是crash，但是在python 中推理是没问题的

**Comment by yinqinggong** [comment]
> 你好，请问可以分享一下最终可以用的版本对应关系吗，我也是遇到了转换后在cpp_inference中直接crash，甚至从官网下载的训练模型，直接转为推理模型，在cpp_infer中也是crash，但是在python 中推理是没问题的
我使用的是Windows下的C++预测库，官方网站直接下载的2.3.2版本，PaddleOCR-release-2.7版本
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/9996124/16221675-b0c1-46f2-a720-58bb48639acc)

**Comment by hanliangwei** [comment]
请问下你转换后的模型中inference.pdmodel是多大呢，我使用与训练模型转换推理模型后只有一百多k，但是官方下载的推理模型却是有一兆左右

**Comment by yinqinggong** [comment]
> 请问下你转换后的模型中inference.pdmodel是多大呢，我使用与训练模型转换推理模型后只有一百多k，但是官方下载的推理模型却是有一兆左右

那你应该是哪里出错了，我转换的识别模型pdmodel有1436KB

**Comment by hanliangwei** [comment]
那就比较奇怪了，我就是

**Comment by hanliangwei** [comment]
那真是太奇怪了，我就是用的
python tools/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./ckpt/best_accuracy  Global.save_inference_dir=./inference_model
其中best_accuracy是官网下载的预训练模型，在几台电脑上都不行，甚至还在ubuntu上试了也不行
能否帮个忙用你的电脑执行一下**pip list > D:\pack.txt**  将这个文件以及你电脑里的paddle ocr的python工程发给我一下呢，感激不尽！！折腾好多天了，自己训练的模型转换有问题，官方的训练模型转换后也有问题 我的邮箱是835126606@qq.com 再次感谢！！

**Comment by yinqinggong** [comment]
> 那真是太奇怪了，我就是用的 python tools/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./ckpt/best_accuracy Global.save_inference_dir=./inference_model 其中best_accuracy是官网下载的预训练模型，在几台电脑上都不行，甚至还在ubuntu上试了也不行 能否帮个忙用你的电脑执行一下**pip list > D:\pack.txt** 将这个文件以及你电脑里的paddle ocr的python工程发给我一下呢，感激不尽！！折腾好多天了，自己训练的模型转换有问题，官方的训练模型转换后也有问题 我的邮箱是[835126606@qq.com](mailto:835126606@qq.com) 再次感谢！！

已发邮箱

**Comment by hanliangwei** [comment]
多谢多谢，我试试

**Comment by hanliangwei** [comment]
根据你的python包中，我发现你的paddlepaddle==2.3.2， 我电脑里是2.6.0，重新安装了你的版本后神奇的好了，万分感谢

**Comment by jianjuan** [comment]
> > 那真是太奇怪了，我就是用的 python tools/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./ckpt/best_accuracy Global.save_inference_dir=./inference_model 其中best_accuracy是官网下载的预训练模型，在几台电脑上都不行，甚至还在ubuntu上试了也不行 能否帮个忙用你的电脑执行一下**pip list > D:\pack.txt** 将这个文件以及你电脑里的paddle ocr的python工程发给我一下呢，感激不尽！！折腾好多天了，自己训练的模型转换有问题，官方的训练模型转换后也有问题 我的邮箱是[835126606@qq.com](mailto:835126606@qq.com) 再次感谢！！
> 
> 已发邮箱

同问，我这边预训练微调的模型转换后只有100多k，官网的预训练模型导出也是一样，可以把具体环境配置发我一份吗？非常感谢！邮箱：963063994@qq.com

**Comment by yinqinggong** [comment]
> > > 那真是太奇怪了，我就是用的 python tools/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./ckpt/best_accuracy Global.save_inference_dir=./inference_model 其中best_accuracy是官网下载的预训练模型，在几台电脑上都不行，甚至还在ubuntu上试了也不行 能否帮个忙用你的电脑执行一下**pip list > D:\pack.txt** 将这个文件以及你电脑里的paddle ocr的python工程发给我一下呢，感激不尽！！折腾好多天了，自己训练的模型转换有问题，官方的训练模型转换后也有问题 我的邮箱是[835126606@qq.com](mailto:835126606@qq.com) 再次感谢！！
> > 
> > 
> > 已发邮箱
> 
> 同问，我这边预训练微调的模型转换后只有100多k，官网的预训练模型导出也是一样，可以把具体环境配置发我一份吗？非常感谢！邮箱：[963063994@qq.com](mailto:963063994@qq.com)

pack.txt已发邮箱
