### ISSUE TITLE
PaddleOCR 官方中英文识别模型无法识别英文中的空格

### ISSUE THREAD

**Issue by jinxiqinghuan** [PaddlePaddle/PaddleOCR#10901]
识别数据是文档性质；
使用官方提供的模型；
在英文中，对于空格的识别效果特别差。

**Comment by zche** [comment]
我也遇到同样的问题，用了use_dilation = True 会稍微好一点，但效果还是差很多

**Comment by jinxiqinghuan** [comment]
@zche 只能微调了，官方提供的属于通用性质的。我微调后，感觉有不错的改善。

**Comment by zche** [comment]
@jinxiqinghuan 检测模型 和  识别模型 都需要微调吗

**Comment by jinxiqinghuan** [comment]
@zche 这个看你的需求了

**Comment by nissansz** [comment]
多语种模型，汉字识别好，英文识别会有错，怎样改善？

**Comment by loxeed1990** [comment]
> @zche 只能微调了，官方提供的属于通用性质的。我微调后，感觉有不错的改善。

请问如何微调？有文档教程吗

**Comment by nissansz** [comment]
> @zche 只能微调了，官方提供的属于通用性质的。我微调后，感觉有不错的改善。

微调hard case, lr设为多少？

**Comment by Andy197527** [comment]
> 识别数据是文档性质； 使用官方提供的模型； 在英文中，对于空格的识别效果特别差。

我也碰到这个问题了，请问你解决了吗？

**Comment by mlick** [comment]
有人解决了么？
