### ISSUE TITLE
段错误(吐核)，调用PaddleOCR，命令行直接蹦出来段错误

### ISSUE THREAD

**Issue by wowowoll** [PaddlePaddle/PaddleOCR#1090]
调用paddleocr的时候出现：段错误（吐核）
![image](https://user-images.githubusercontent.com/49295186/97968234-58def100-1df9-11eb-8863-2c7ae1e01ca3.png)
使用
![image](https://user-images.githubusercontent.com/49295186/97968293-6b592a80-1df9-11eb-82a1-25eb7425e6a7.png)
然后运行ocr
![image](https://user-images.githubusercontent.com/49295186/97968329-7744ec80-1df9-11eb-8c35-31d94bcc319a.png)
生产core.473
使用gdb core.473
![image](https://user-images.githubusercontent.com/49295186/97968371-84fa7200-1df9-11eb-8196-156bb50beb23.png)
现在问题怎么解决？

**Comment by wowowoll** [comment]
使用conda创建新环境，重新安装paddle和paddleocr，重新安装cuDNN解决了这个问题。

**Comment by littletomatodonkey** [comment]
好的~
