### ISSUE TITLE
能否提供，控制方向参数

### ISSUE THREAD

**Issue by Kessity** [PaddlePaddle/PaddleOCR#1091]
横向文字识别为竖向，竖向文字识别为横向，能否提供方向控制参数
![image](https://user-images.githubusercontent.com/15826574/97977548-54213980-1e07-11eb-947b-86e71a713611.png)
![image](https://user-images.githubusercontent.com/15826574/97977502-453a8700-1e07-11eb-8ea6-6ffbd14bf8ae.png)

**Comment by MissPenguin** [comment]
你的这个case不是参数能解决的，两行字的行间距太小，列间距反而更大，是容易识别成竖排文本。如果这种case很多的话，建议构造一批训练样本进行finetune。
