### ISSUE TITLE
训练文字检测过程中自己卡住

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#1093]
当前最新版本，训练车牌检测，使用det_mv3_db_v1.1.yml和det_db_icdar15_reader.yml配置表训练时，在非验证阶段卡住不动了。

return paddle.reader.multiprocess_reader(readers, False, queue_size=200)
test_batch_size_per_card: 1
num_workers: 1
![image](https://user-images.githubusercontent.com/66729924/97972823-12d95b80-1e00-11eb-8510-a43ed2db8fb9.png)

**Comment by MissPenguin** [comment]
稳定复现吗，估计和机器和环境有关系，我们跑了更多数据的，加大batch 和num_workers 没遇到这个问题

**Comment by littletomatodonkey** [comment]
1. 可以减小queue size，参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q335%E8%AF%BB%E6%95%B0%E6%8D%AE%E8%BF%9B%E7%A8%8B%E6%95%B0%E8%AE%BE%E7%BD%AE48%E6%97%B6%E8%AE%AD%E7%BB%83%E4%B8%80%E4%BC%9A%E8%BF%9B%E7%A8%8B%E6%8E%A5%E8%BF%9Edefunct%E5%90%8Egpu%E5%88%A9%E7%94%A8%E7%8E%87%E4%B8%80%E7%9B%B4%E4%B8%BA0%E5%8D%A1%E6%AD%BB
2. 可能程序只是累了，想休息一会 23333
