### ISSUE TITLE
【BUG】ppstructer quickstart: running bugs with official quickstart python sdk with document-analysis, table recognition functions

### ISSUE THREAD

**Issue by PancakeAwesome** [PaddlePaddle/PaddleOCR#10946]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
When I was using the python code in the ppstructer documentation to quickly experience the function of image orientation classification + layout analysis + table recognition, and there was an error. I didn't change the logic of the code, and I just typed it according to the official code.
- 系统环境/System Environment：centos7
- 版本号/Version：Paddle：paddlegpu 2.4.2&dev 0.0.0  PaddleOCR：release2.7 问题相关组件/Related components：
- 运行指令/Command Code：follow the official document of ppstructer document analysis: 
`table_engine = PPStructure(show_log=True, image_orientation=True)
img = cv2.imread(img_path)
result = table_engine(img)
`
- 完整报错/Complete Error Message：
`Traceback (most recent call last):
  File "/opt/conda/envs/jcai/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 837, in main
    result = engine(img, img_idx=index)
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_rec.py", line 616, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [4, 96, 3, 90] and the shape of Y = [4, 96, 4, 90]. Received [3] in X is not equal to [4] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]`
我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):
yes
请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by PancakeAwesome** [comment]
@GreatV

**Comment by PancakeAwesome** [comment]
> @GreatV
Thank you for coming and answering my questions.

**Comment by PancakeAwesome** [comment]
can anybody help me?

**Comment by GreatV** [comment]
Hi @PancakeAwesome , could you provide the image used for testing, I'll try to reproduce it.

**Comment by xu-peng-7** [comment]
According to the error message, the problem occurs during the text recognition stage, where the height of the image input to the recognition model is different from the expected input (Operands could not be broadcast together with the shape of X = [4, 96, 3, 90] and the shape of Y = [4, 96, 4, 90]). This error may be caused by the height of the input image not being a multiple of 16, resulting in similar errors during the concatenation of maps due to rounding errors in the downsampling and upsampling processes. We suggest you check your input img.

**Comment by PancakeAwesome** [comment]
> Hi @PancakeAwesome , could you provide the image used for testing, I'll try to reproduce it.



> According to the error message, the problem occurs during the text recognition stage, where the height of the image input to the recognition model is different from the expected input (Operands could not be broadcast together with the shape of X = [4, 96, 3, 90] and the shape of Y = [4, 96, 4, 90]). This error may be caused by the height of the input image not being a multiple of 16, resulting in similar errors during the concatenation of maps due to rounding errors in the downsampling and upsampling processes. We suggest you check your input img.

hi contributors, i used image in official github codes. follow as below:

img_path = 'ppstructure/docs/table/1.png'

```
# 2.2.1 图像方向分类+版面分析+表格识别
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True, image_orientation=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/1.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = 'doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppstructure/docs/quickstart.md#221-%E5%9B%BE%E5%83%8F%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90%E8%A1%A8%E6%A0%BC%E8%AF%86%E5%88%AB

**Comment by PancakeAwesome** [comment]
> Hi @PancakeAwesome , could you provide the image used for testing, I'll try to reproduce it.

look forward your reply, sincerely

**Comment by PancakeAwesome** [comment]
> According to the error message, the problem occurs during the text recognition stage, where the height of the image input to the recognition model is different from the expected input (Operands could not be broadcast together with the shape of X = [4, 96, 3, 90] and the shape of Y = [4, 96, 4, 90]). This error may be caused by the height of the input image not being a multiple of 16, resulting in similar errors during the concatenation of maps due to rounding errors in the downsampling and upsampling processes. We suggest you check your input img.

look forward your reply, sincerely

**Comment by xu-peng-7** [comment]
Can you first run the **2.2.2 版面分析+表格识别** code, and check if the same error occurs?

**Comment by PancakeAwesome** [comment]
> Can you first run the **2.2.2 版面分析+表格识别** code, and check if the same error occurs?
```
# 2.2.1 图像方向分类+版面分析+表格识别
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True, image_orientation=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/1.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = 'doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```
i just run this code above. can u reproduce it?

**Comment by PancakeAwesome** [comment]
> Can you first run the **2.2.2 版面分析+表格识别** code, and check if the same error occurs?

sure.After runnning this code above, i also with errors:
```
Traceback (most recent call last):
  File "demo.py", line 57, in <module>
    result = table_engine(img)
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/opt/conda/envs/jcai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_rec.py", line 616, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [6, 96, 3, 74] and the shape of Y = [6, 96, 4, 74]. Received [3] in X is not equal to [4] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_add > error]
```

**Comment by xu-peng-7** [comment]
you should switch your paddleOCR version as 2.6 ， first use `pip unintall paddleocr`  and use `pip install paddleocr>=2.6.0.3`

**Comment by GreatV** [comment]
Hi @PancakeAwesome, I ran the code you provided and it works successfully and no error message is generated. You might need to update to the latest version and check the runtime environment.

**Comment by PancakeAwesome** [comment]
> Hi @PancakeAwesome, I ran the code you provided and it works successfully and no error message is generated. You might need to update to the latest version and check the runtime environment.

my paddleocr env: paddleocr 2.7.0.3
it is right now latest online

**Comment by PancakeAwesome** [comment]
> you should switch your paddleOCR version as 2.6 ， first use `pip unintall paddleocr` and use `pip install paddleocr>=2.6.0.3`
> 
> I suggest you create a new environment and reinstall paddleocr. I couldn't reproduce this error under PaddleOCR: release 2.7.0.3, and my code successfully produced the output.

https://github.com/PaddlePaddle/PaddleOCR/issues/10946#issuecomment-1727393650
