### ISSUE TITLE
关于step_each_epoch（每个批次迭代次数）的计算问题

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleOCR#1094]
在两次相同数据集、相同算法的中文识别模型的训练过程中（仅batchsize等参数不同），出现了step_each_epoch表现结果不同的问题。
![配置参数 ](https://user-images.githubusercontent.com/49974432/98061600-31366a00-1e87-11eb-9920-6af48c8614d9.png)
黄底 为 日志输出的数值。
首先，paddleOCR文档中给出的计算方式为：step_each_epoch=total_image_num / (batch_size_per_card * card_size)
           训练集图片总数皆为5986235张
1.第一次使用多卡CPU进行训练，CPU_NUM=6，train_batch_size_per_card: 16，num_workers=6， 按照公式计算的 step_each_epoch 应为 62356次， 每62356次迭代进入下一个epoch，但后台日志文件显示，每10392次迭代 就进入了下一个epoch，
![log1](https://user-images.githubusercontent.com/49974432/98061102-18798480-1e86-11eb-94bb-bc1eab5323e6.png)，这应该是是 total_image_num / (batch_size_per_card * card_size*num_workers)的结果。
2.第二次使用单卡GPU进行训练，GPU_num=1，train_batch_size_per_card: 128，num_workers=8
，step_each_epoch 如果按照total_image_num / (batch_size_per_card * card_size*num_workers)来计算的话，应为5845次迭代，而后进入下个epoch，可目前的日志文件显示，到了40000批次，还是在epoch 0，
![log2](https://user-images.githubusercontent.com/49974432/98061440-d8ff6800-1e86-11eb-916e-eb84c8d48f07.png)
这明显又是total_image_num / (batch_size_per_card * card_size)即不除num_workers的计算方式。
综上，想问下
step_each_epoch的计算方式到底是哪种？又或者我的训练 哪里出现了问题？（我确定 参数是正确的的，已经查看了很多次。）

**Comment by LDOUBLEV** [comment]
准确的说：
step_each_epoch=total_image_num / (batch_size_per_card * card_size * card_nums)

num_workers只是进程数量，影响数据加载速度，不影响计算step_each_epoch
