### ISSUE TITLE
安卓移动端，可能有内存泄露的问题

### ISSUE THREAD

**Issue by milkliker** [PaddlePaddle/PaddleOCR#1095]
如果短时间内（比如在一个循环中）处理多张图片，会直接报内存错误然后退出。
但如果对每张图片的处理，都release之后，再init初始化，就不会有问题（但那样会非常的慢，因为每次多了初始化的时间）。

**Comment by MissPenguin** [comment]
用的哪个版本的paddle，2.0.0b0应该已经解决了内存泄漏问题

**Comment by milkliker** [comment]
> 用的哪个版本的paddle，2.0.0b0应该已经解决了内存泄漏问题

感谢MissPenguin回复！应该是1.1。
2.0有rc了吗？没看到分支或标签。

**Comment by littletomatodonkey** [comment]
Paddle分支在这里：https://github.com/PaddlePaddle/Paddle/tree/release/2.0-rc
```
pip install paddlepaddle-gpu==2.0.0rc
```

**Comment by milkliker** [comment]
> Paddle分支在这里：https://github.com/PaddlePaddle/Paddle/tree/release/2.0-rc
> 
> ```
> pip install paddlepaddle-gpu==2.0.0rc
> ```

收到，感谢！
