### ISSUE TITLE
在线测试paddleOCR只是识别数字，效果很差。是我使用不当吗

### ISSUE THREAD

**Issue by QQ10Year** [PaddlePaddle/PaddleOCR#1097]
在线测试paddleOCR识别数字，效果很差。是我使用不当吗？

**Comment by MissPenguin** [comment]
用的什么图，贴出来看看？不同场景可能需要调下参数或者finetune的

**Comment by QQ10Year** [comment]
![shuzi1](https://user-images.githubusercontent.com/12623632/98192774-9d33d380-1f56-11eb-879b-94fa86ab42c6.png)

**Comment by QQ10Year** [comment]
![shuzi1](https://user-images.githubusercontent.com/12623632/98192822-be94bf80-1f56-11eb-9086-2204dd7b8160.png)

**Comment by QQ10Year** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 中午1:56
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"QQ10年"<384793299@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 在线测试paddleOCR只是识别数字，效果很差。是我使用不当吗 (#1097)





 
用的什么图，贴出来看看？不同场景可能需要调下参数或者finetune的

**Comment by littletomatodonkey** [comment]
你好，目前单字场景的检测，paddleocr还支持得不是很好，可能需要你使用自己的单字数据集进行模型微调

**Comment by mikeshi80** [comment]
如果都是这样的单字或者双字的话，目前比较可行的方案是只使用FasterRCNN这样的目标识别模型，识别出来，然后切割下来进行识别。因为文字区域识别，它本质上要符合特征的区域的长度达到一定量后才会认为是字符串的。

当然，还有一个变通的方式，我之前试过，是将图片横向拉长2~3倍，再训练模型，这样基本就是把单个字符认为是多个字符，从而识别出来，当然，这对于1, l，i等本身很短的字符还是无可奈何的，但是对其他字符效果就很好。

**Comment by zxingkong** [comment]
> 如果都是这样的单字或者双字的话，目前比较可行的方案是只使用FasterRCNN这样的目标识别模型，识别出来，然后切割下来进行识别。因为文字区域识别，它本质上要符合特征的区域的长度达到一定量后才会认为是字符串的。
> 
> 当然，还有一个变通的方式，我之前试过，是将图片横向拉长2~3倍，再训练模型，这样基本就是把单个字符认为是多个字符，从而识别出来，当然，这对于1, l，i等本身很短的字符还是无可奈何的，但是对其他字符效果就很好。

唉，这就很难受了。。。

**Comment by mikeshi80** [comment]
> > 如果都是这样的单字或者双字的话，目前比较可行的方案是只使用FasterRCNN这样的目标识别模型，识别出来，然后切割下来进行识别。因为文字区域识别，它本质上要符合特征的区域的长度达到一定量后才会认为是字符串的。
> > 当然，还有一个变通的方式，我之前试过，是将图片横向拉长2~3倍，再训练模型，这样基本就是把单个字符认为是多个字符，从而识别出来，当然，这对于1, l，i等本身很短的字符还是无可奈何的，但是对其他字符效果就很好。
> 
> 唉，这就很难受了。。。

单字识别，还有一套CRAFT算法，但是PaddleOCR一直没有官方的实现。

**Comment by littletomatodonkey** [comment]
嗯嗯，目前还没有复现，我们评估下是否需要放在复现名单中哈

**Comment by mikeshi80** [comment]
如果加上这个就太棒了，太棒了

**Comment by one-matrix** [comment]
1.负数的识别。如：-0.13 解析为10.13  
2.数字零的识别。如：0.13 解析为 o.13或.13
3.部分数值未识别到。

**Comment by mikeshi80** [comment]
> 1.负数的识别。如：-0.13 解析为10.13
> 2.数字零的识别。如：0.13 解析为 o.13或.13
> 3.部分数值未识别到。

我对于这样的解决，是看是否一开始可以区分要识别的区域，如果此区域只有数字，或者其他很垂直的领域（比如年月日，或者城市名称），那么我会采用专门的模型去识别，比如只识别数字的或者只识别日期的，这样可以明显增加准确率。
