### ISSUE TITLE
cpu推理结果正常，更改成gpu推理则出现乱码

### ISSUE THREAD

**Issue by ZhangLe-fighting** [PaddlePaddle/PaddleOCR#10995]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7.6
- 版本号/Version：Paddle：2.5.1.post112  PaddleOCR：2.7.0.3  问题相关组件/Related components：ppocrV4_server
- 运行指令/Command Code：
- paddle_ocr = PaddleOCR(use_angle_cls=True, use_gpu=True, use_space_char=True, lang="ch",
                       det_model_dir='paddleocr_model/ch_PP-OCRv4_det_server_infer/',
                       rec_model_dir='paddleocr_model/ch_PP-OCRv4_rec_server_infer/',
                       cls_model_dir='paddleocr_model/ch_ppocr_mobile_v2.0_cls_slim_infer/'
                       )
其中use_gpu=False时，运行正常；use_gpu=True时出现乱码且结果很多
- 完整报错/Complete Error Message：
[[[[80.0, 937.0], [133.0, 937.0], [133.0, 985.0], [80.0, 985.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[321.0, 928.0], [349.0, 952.0], [330.0, 975.0], [301.0, 951.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[628.0, 932.0], [658.0, 953.0], [644.0, 972.0], [614.0, 950.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[1760.0, 929.0], [1792.0, 929.0], [1792.0, 971.0], [1760.0, 971.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[312.0, 940.0], [315.0, 985.0], [336.0, 964.0], [315.0, 985.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[408.0, 942.0], [408.0, 969.0], [421.0, 956.0], [408.0, 969.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[901.0, 940.0], [947.0, 940.0], [947.0, 971.0], [901.0, 971.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[1271.0, 946.0], [1259.0, 958.0], [1285.0, 961.0], [1273.0, 973.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[1277.0, 942.0], [1325.0, 942.0], [1325.0, 990.0], [1277.0, 990.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[1462.0, 943.0], [1482.0, 957.0], [1474.0, 970.0], [1453.0, 956.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[1504.0, 940.0], [1504.0, 966.0], [1517.0, 953.0], [1504.0, 966.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[13.0, 953.0], [40.0, 953.0], [40.0, 974.0], [13.0, 974.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)], [[[325.0, 953.0], [349.0, 953.0], [349.0, 974.0], [325.0, 974.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)], [[[427.0, 958.0], [444.0, 941.0], [457.0, 954.0], [440.0, 971.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[533.0, 958.0], [515.0, 977.0], [547.0, 971.0], [515.0, 977.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[667.0, 950.0], [712.0, 950.0], [712.0, 982.0], [667.0, 982.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[839.0, 953.0], [864.0, 971.0], [849.0, 991.0], [824.0, 973.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[997.0, 950.0], [1000.0, 979.0], [1013.0, 966.0], [984.0, 964.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[1413.0, 950.0], [1443.0, 950.0], [1443.0, 969.0], [1413.0, 969.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[1688.0, 953.0], [1675.0, 966.0], [1707.0, 971.0], [1693.0, 985.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)], [[[1761.0, 956.0], [1800.0, 968.0], [1793.0, 989.0], [1755.0, 978.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[1797.0, 951.0], [1827.0, 934.0], [1840.0, 958.0], [1811.0, 974.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[2119.0, 960.0], [2144.0, 954.0], [2151.0, 986.0], [2126.0, 991.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[2461.0, 966.0], [2485.0, 966.0], [2485.0, 990.0], [2461.0, 990.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[328.0, 982.0], [360.0, 982.0], [360.0, 1003.0], [328.0, 1003.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)], [[[1837.0, 987.0], [1840.0, 1030.0], [1860.0, 1010.0], [1840.0, 1030.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)], [[[112.0, 998.0], [136.0, 998.0], [136.0, 1014.0], [112.0, 1014.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[373.0, 998.0], [400.0, 998.0], [400.0, 1019.0], [373.0, 1019.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[1328.0, 1002.0], [1378.0, 990.0], [1386.0, 1022.0], [1336.0, 1034.0]], ('围丫é头爸围é围监爸围爸头围荔é触睿股μ惑什睿围围', 0.8125305771827698)], [[[952.0, 1014.0], [965.0, 1014.0], [965.0, 1027.0], [952.0, 1027.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[1365.0, 1009.0], [1365.0, 1035.0], [1379.0, 1022.0], [1365.0, 1035.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[1397.0, 1014.0], [1413.0, 1014.0], [1413.0, 1027.0], [1397.0, 1027.0]], ('爸系围头μ断围μμ凤系惑荔头纫μ這爸粤围头汪', 0.8146589398384094)], [[[1821.0, 1014.0], [1848.0, 1014.0], [1848.0, 1035.0], [1821.0, 1035.0]], ('围系围头μ围這系头迪丫头丫拍粤电睿围围é系惑', 0.8301279544830322)], [[[613.0, 1032.0], [632.0, 1032.0], [632.0, 1051.0], [613.0, 1051.0]], ('睿裹惑系粤头μ睿招围围粤qμ拍μμ爸é围址é熊', 0.7508943676948547)], [[[1395.0, 1024.0], [1416.0, 1024.0], [1416.0, 1051.0], [1395.0, 1051.0]], ('围μ头μ围围μ爸系é汪纫粤é电围丫头系头庆μ', 0.9001711010932922)], [[[1800.0, 1043.0], [1813.0, 1043.0], [1813.0, 1059.0], [1800.0, 1059.0]], ('围电汪μ裹告μ头睿μ拍裹粤头μ围裹围围é汪惑围裱断睿這', 0.8372356295585632)]]
没报错但是结果明显不对~

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):
yes
请尽量不要包含图片在问题中/Please try to not include the image in the issue.
ok

**Comment by JZSHQ** [comment]
CUDA版本从12.1降至11.0，问题解决

**Comment by GreatV** [comment]
这个应该和显卡以及驱动版本、cuda版本有关系，都要匹配上。太老、太新的显卡paddle框架也不太支持。
