### ISSUE TITLE
[Hackathon No.65] 版面恢复功能（恢复为docx或者excel）的c++版的一些问题

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/PaddleOCR#10999]
# 1 赛题要求

## 1.1 任务背景

用于手机端的本地化办公文档扫描。

## 1.2 详细描述

版面分析和OCR后，使用minidocx创建docx文档，libxlsxwriter生成excel。
提交PR到PPOCR。
提交内容：

按照PR提交规范，提交支持c++生成文档的代码，并展示部署效果。

# 2 疑惑点

* 提交到仓库的哪个位置
* 预训练模型的位置在哪里

**Comment by Zheng-Bicheng** [comment]
@Ligoml

**Comment by shiyutang** [comment]
1. 代码提交到：https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/lite
2. 预训练模型在下面链接中：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/docs/inference.md#1-%E7%89%88%E9%9D%A2%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96
