### ISSUE TITLE
可以使用paddle-lite在linux上部署吗

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#1099]

**Comment by littletomatodonkey** [comment]
参考Paddle-Lite的文档，应该是支持的，不过建议linux上的话直接使用python inference或者cpp inference吧

**Comment by AIpioneer** [comment]
这要看你的硬件是什么架构的，如果是x86,我们建议使用paddle infenrence部署，如果是armlinux,建议使用paddle-lite部署。
