### ISSUE TITLE
空格识别问题

### ISSUE THREAD

**Issue by kouxichao** [PaddlePaddle/PaddleOCR#1100]
您好，我有一些疑问，希望可以得到解答。

在文档ocr中，英文文本是以什么为最小结构去识别的？1.带有空格的文本行整体识别；2.单词识别，不包含空格。3.或者是其他的方法（段落）？。

我看现有的基于ctc的模型都是识别单词的，好像对于文本行不太行，是因为没有加入空格训练吗？如果只是基于单词识别，对识别结果组合，对于文档等具有大量文本的场景中因为速度原因势必没办法得到应用。现有的文档ocr商用软件中是怎么实现的？

提供文本行识别的目前了解到的只有这个项目，如果进行文档中的ocr该采用什么方案，有没有较好的项目可以参考？

感谢！

**Comment by LDOUBLEV** [comment]
现在repo中的英文模型支持文本行识别不行，如果是空格数据不符合你的预期，可以加入带空格的数据去finetune训练
