### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by fuhengwu2021** [PaddlePaddle/PaddleOCR#11007]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.7
- 运行指令/Command Code：paddleocr --image_dir 2023-09-26-11-04-19.png --use_angle_cls false --use_gpu true --rec false --det_algorithm="DB"
- 完整报错/Complete Error Message：

```
Traceback (most recent call last):
  File "/home/fuhwu/miniconda3/envs/docai/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/fuhwu/miniconda3/envs/docai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 805, in main
    for line in res:
TypeError: 'NoneType' object is not iterable

```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by likenamehaojie** [comment]
我有相同的问题
![Uploading image.png…]()

**Comment by zhuimengren-a11u** [comment]
请问有人解决了吗

**Comment by Lakindu1999** [comment]
Try to change use_gpu status to False.

`ocr = PaddleOCR(use_angle_cls=True, use_gpu=False)`

**Comment by SWHL** [comment]
main分支代码，该问题已经解决。
