### ISSUE TITLE
use_gpu = True on Windows system

### ISSUE THREAD

**Issue by gautamHCSCV** [PaddlePaddle/PaddleOCR#11019]
I am using the following inference code on my system with python 3.8. 

import paddleocr
from paddleocr import PaddleOCR

ocr = PaddleOCR(lang="en", rec_model_type='en', rec_algorithm = 'CRNN', ocr_version = 'PP-OCRv3',
                use_gpu = True, det_db_thresh=0.4, show_log = False, use_angle_cls = True)

result = ocr.ocr('img.jpg')

The code runs well on CPU (use_gpu = False), but it gives error when trying to use GPU (use_gpu = True). Please help me resolve the issue. Note that I have an active 4GB GPU on my system.

Error: 
result = ocr.ocr('img.jpg')
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\paddleocr.py", line 661, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddle\inference\wrapper.py", line 46, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:301)

**Comment by sagarjgb** [comment]
@gautamHCSCV are you using paddlepaddle-gpu library? 
To support GPU use paddlepaddle-gpu library instead of paddlepaddle library.

**PIP Installation**
`pip install paddlepaddle-gpu`

**Comment by gautamHCSCV** [comment]
The previous issue is solved but running the GPU mode of paddle ocr in threading mode (for parallellization) creates the following error. Please help me resolve the same.

esult = ocr.ocr(img)
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\paddleocr.py", line 661, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 99, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(
  File "C:\Users\GAUTAM\anaconda3\envs\myenv\lib\site-packages\paddleocr\tools\infer\predict_cls.py", line 112, in __call__
    prob_out = self.output_tensors[0].copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at ..\paddle\phi\core\dense_tensor_impl.cc:44)

**Comment by wkk689wkk689** [comment]
+1

**Comment by ysy1418899560** [comment]
+1

**Comment by PhamMinhTien05102001** [comment]
+1

**Comment by ShubhamZoop** [comment]
Any fix for this memory issue?

**Comment by Shubham654** [comment]
Any fix for this memory issue?

**Comment by yuanzhiwei** [comment]
same issue +1

**Comment by sanket-valani** [comment]
Fix to at least get things running https://github.com/PaddlePaddle/Paddle/issues/56193#issuecomment-2395379877
