### ISSUE TITLE
SVTR ch high accuracy ”窦”识别成“实”

### ISSUE THREAD

**Issue by C00pe2** [PaddlePaddle/PaddleOCR#11011]
使用ch_ppocr_mobile_v1.1_rec_infer是正常的，但使用svtr_ch_high_accuracy的识别结果会把的“窦”识别成“实”，在ppocr_key_v1.txt中都含有“窦”这个词，怎么解决，是要微调吗

**Comment by tohsakask** [comment]
你好，请问有这个模型码？
