### ISSUE TITLE
参数det=True, rec=False, cls=False运行会导致出错

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleOCR#11039]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.7.3 问题相关组件/Related components：def ocr
- 运行指令/Command Code：ocr(img_path, det=True, rec=False, cls=False)
- 完整报错/Complete Error Message：
2.7.3版本只使用det会导致报错
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```python
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR()  # need to run only once to download and load model into memory
img_path = './data/id0.jpg'
result = ocr.ocr(img_path, det=True, rec=False, cls=False)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

# 显示结果
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
im_show = draw_ocr(image, result, txts=None, scores=None, font_path='/path/to/PaddleOCR/doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```

**Comment by timlliu** [comment]
在 [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/paddleocr.py#L681](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/paddleocr.py#L681)

你可以把:

if not dt_boxes:

換成:

if len(dt_boxes) == 0:

就會解決了。

**Comment by SWHL** [comment]
仓库main分支代码已经解决。issue先行关闭。
