### ISSUE TITLE
Predicting KIE with my ocr 

### ISSUE THREAD

**Issue by andreaIskanderBelkhir** [PaddlePaddle/PaddleOCR#11038]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem:
I'm trying to infer  a kie model using my own ocr result.json using the information on the docs ( putting global.infer_mode=False and global.infer_img=myResult.json).
But i cant find the format of the JSON to use and i get errors on splitting the data for  the label.

**Comment by minhduc01168** [comment]
@andreaIskanderBelkhir Have you written predict code with your OCR model yet? What is the input format of model ser KIE? Can you tell me? Thank you very much
