### ISSUE TITLE
paddleocr gpu PDF识别程序报错+乱码

### ISSUE THREAD

**Issue by RedNoseJJN** [PaddlePaddle/PaddleOCR#11042]
CUDA 12.0 + paddlepaddle-gpu2.5.1post120, 其他依赖在pipfile中保持‘*’最新版本，在use_gpu=True的时候不能正常识别文字，出现大量乱码，并且出现以下报错：

> /usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 572390 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/subprocess.py:767: ResourceWarning: unclosed file <_io.TextIOWrapper name=11 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 572394 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 572400 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback

请问我该怎么解决这个问题

**Comment by RedNoseJJN** [comment]
btw，在CPU上运行没有任何问题

**Comment by liuzhenyulive** [comment]
+1, I have same issue with tesla P4 and cuda 12

**Comment by RedNoseJJN** [comment]
> +1, I have same issue with tesla P4 and cuda 12

exactly the same, still have no idea ab how to fix it

**Comment by RedNoseJJN** [comment]
anyone can see this?

**Comment by RedNoseJJN** [comment]
solved. downgrading cuda to 10.2 with cudnn 7.6.5 can make it.
I 'll close this issue, thanks.
