### ISSUE TITLE
Segmentation fault on Mac M1

### ISSUE THREAD

**Issue by dotieuthien** [PaddlePaddle/PaddleOCR#11067]
./build/ppocr --det_model_dir=inference/det_db \
    --image_dir=../../doc/imgs/12.jpg \
    --det=true \
    --rec=false \
    --cls=false
total images num: 1
--- Running analysis [ir_graph_build_pass]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1011 22:57:05.892509 3986859264 executor.cc:187] Old Executor is Running.
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1011 22:57:06.074900 3986859264 fuse_pass_base.cc:59] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
I1011 22:57:06.103499 3986859264 fuse_pass_base.cc:59] ---  detected 1 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [constant_folding_pass]
--- Running analysis [save_optimized_model_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1011 22:57:06.110913 3986859264 memory_optimize_pass.cc:118] The persistable params in main graph are : 2.23764MB
I1011 22:57:06.114418 3986859264 memory_optimize_pass.cc:246] Cluster name : elementwise_add_3  size: 96
I1011 22:57:06.114427 3986859264 memory_optimize_pass.cc:246] Cluster name : elementwise_add_1  size: 64
I1011 22:57:06.114429 3986859264 memory_optimize_pass.cc:246] Cluster name : hardsigmoid_3.tmp_0  size: 384
I1011 22:57:06.114431 3986859264 memory_optimize_pass.cc:246] Cluster name : conv2d_261.tmp_1  size: 384
I1011 22:57:06.114434 3986859264 memory_optimize_pass.cc:246] Cluster name : x  size: 12
I1011 22:57:06.114435 3986859264 memory_optimize_pass.cc:246] Cluster name : tmp_3  size: 384
I1011 22:57:06.114436 3986859264 memory_optimize_pass.cc:246] Cluster name : batch_norm_44.tmp_0  size: 1920
I1011 22:57:06.114439 3986859264 memory_optimize_pass.cc:246] Cluster name : batch_norm_44.tmp_3  size: 1920
I1011 22:57:06.114440 3986859264 memory_optimize_pass.cc:246] Cluster name : depthwise_conv2d_14.tmp_0  size: 1920
I1011 22:57:06.114442 3986859264 memory_optimize_pass.cc:246] Cluster name : batch_norm_44.tmp_1  size: 1920
--- Running analysis [ir_graph_to_program_pass]
I1011 22:57:06.186138 3986859264 analysis_predictor.cc:1708] ======= optimize end =======
I1011 22:57:06.186484 3986859264 naive_executor.cc:171] ---  skip [feed], feed -> x
I1011 22:57:06.189332 3986859264 naive_executor.cc:171] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
zsh: segmentation fault  ./build/ppocr --det_model_dir=inference/det_db  --det=true --rec=false

**Comment by windosx** [comment]
@dotieuthien Hello, I also encountered this issue, how did you solve it?

**Comment by madhavi1102** [comment]
I am also encountering this issue on Mac M!=1, how to solve it?

**Comment by dotieuthien** [comment]
@windosx @madhavi1102 On Mac M1, I replaced Paddle engine by OnnxRuntime, the code is [here](https://github.com/dotieuthien/paddleocr.cpp)
