### ISSUE TITLE
SRN：encoder_word_pos, gsrm_word_pos, gsrm_slf_attn_bias1, gsrm_slf_attn_bias2是怎么计算得到的？

### ISSUE THREAD

**Issue by liaomingg** [PaddlePaddle/PaddleOCR#1108]
请问，SRN模型，训练数据中的encoder_word_pos, gsrm_word_pos, gsrm_slf_attn_bias1, gsrm_slf_attn_bias2应该如何计算？

**Comment by tink2123** [comment]
输入数据的生成位置在：https://github.com/PaddlePaddle/PaddleOCR/blob/f21c41c3b53283bc16aa5edc59603aa153ada161/ppocr/data/rec/img_tools.py#L429-L459
