### ISSUE TITLE
Loading custom paddle ocr model into the pip library instance 

### ISSUE THREAD

**Issue by falloutboy111** [PaddlePaddle/PaddleOCR#11083]
Hi

I have fine tuned my own model and was hoping to deploy it but its not making correct predictions.

I exported the model using the tools/export_model.py 

ran this on a directory 

ython3 tools/infer/predict_rec.py --use_gpu=True --rec_model_dir="....../inferDir" --rec_char_dict_path='...../PaddleOCR/ppocr/utils/en_dict.txt' --image_dir='/new_image_test' 

the results were correct and what I was looking for same goes for the infer_rec.py function 

now on the exact same image if i use this rec model on the pip constructor it returns None or completely wrong results 

ocr = PaddleOCR(use_angle_cls=True, use_gpu=True, rec_model_dir="...../inferDir", rec_char_dict_path='...../PaddleOCR/ppocr/utils/en_dict.txt')

result = ocr.ocr("........./new_image_test/new_test_031d50cf-c9d1-49a1-80a7-656092f044af.png", cls=True)
print(result)

Am i doing anything incorrectly? Is it a version issue because i did a pull on the repo and everything is up to date same with the paddle pip library? Thanks

**Comment by falloutboy111** [comment]
Name: paddleocr
Version: 2.7.0.3

this is my version

**Comment by falloutboy111** [comment]
found the soultion turns out it was the detection algorithm that was broken 

result = ocr.ocr(binary, cls=True, det=False)

**Comment by SWHL** [comment]
The main branch of the repo has resolved this bug.
