### ISSUE TITLE
有计划升级PyMuPDF以便支持python3.11吗？

### ISSUE THREAD

**Issue by kiss2016** [PaddlePaddle/PaddleOCR#11119]
requirements.txt中依赖版本PyMuPDF<1.21.0，但是1.21.1及以后都已支持python3.11，请问什么时候升级PyMuPDF以便支持python3.11

- 系统环境/System Environment：win10 x64
- 版本号/Version：Paddle：paddleocr 2.7.0.3  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by SWHL** [comment]
main分支代码已经解决，issue先关闭了。
