### ISSUE TITLE
中英文通用模型没有识别罗马数字吗，这个还蛮常见的

### ISSUE THREAD

**Issue by xazeng** [PaddlePaddle/PaddleOCR#1112]
还是要感谢下飞浆团队，这个开源不管是在性能还是识别率上都是十分优秀的。
第一次接触这个，运行起来了还是很激动的，用来跑测试的图上刚好有个罗马数字1，发现识别成了大写i。
因此特意截了罗马数字测试了下，发现确实不能识别。这个应该蛮经常遇到的，是否可以考虑下加入到中英文通用模型中去呢？

**Comment by MissPenguin** [comment]
这个确实比较常见，后续模型迭代可以考虑加入，不过排期不定，需要的话可以先自己加数据训一下试试哈

**Comment by LLL0802** [comment]
> 还是要感谢下飞浆团队，这个开源不管是在性能还是识别率上都是十分优秀的。
> 第一次接触这个，运行起来了还是很激动的，用来跑测试的图上刚好有个罗马数字1，发现识别成了大写i。
> 因此特意截了罗马数字测试了下，发现确实不能识别。这个应该蛮经常遇到的，是否可以考虑下加入到中英文通用模型中去呢？

请问您自己训练了吗

**Comment by xazeng** [comment]
> > 还是要感谢下飞浆团队，这个开源不管是在性能还是识别率上都是十分优秀的。
> > 第一次接触这个，运行起来了还是很激动的，用来跑测试的图上刚好有个罗马数字1，发现识别成了大写i。
> > 因此特意截了罗马数字测试了下，发现确实不能识别。这个应该蛮经常遇到的，是否可以考虑下加入到中英文通用模型中去呢？
> 
> 请问您自己训练了吗

没有特意去训练
