### ISSUE TITLE
python3 setup.py install 安装 2.7.1 版本报错 NameError: name 'predict_system' is not defined

### ISSUE THREAD

**Issue by ThinkWD** [PaddlePaddle/PaddleOCR#11136]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux ubuntu
- 版本号/Version：2.7.1     Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：`python3 setup.py install`
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from paddleocr import VERSION
  File "/home/lx_dir/paddle/paddleocr/paddleocr.py", line 575, in <module>
    class PaddleOCR(predict_system.TextSystem):
NameError: name 'predict_system' is not defined
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):
yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by linjson** [comment]
54行,这样改from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem

**Comment by ThinkWD** [comment]
> 54行,这样改from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem 575行,这样改class PaddleOCR(TextSystem):

谢谢, 可以正常安装了

**Comment by mriamnobody** [comment]
> Line 54, change from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem to line 575, change class PaddleOCR(TextSystem) like this:

It works for me too. Thanks a lot @linjson

**Comment by durongzheng** [comment]
Works for me too. Thanks. @linjson
