### ISSUE TITLE
补充Satrn识别模型文档

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleOCR#11131]
# 补充Satrn识别模型文档
### 任务背景
- 新增的Satrn识别模型缺少说明文档，适合开源贡献经历较少的同学了解提交PR过程并熟悉OCR文档
### 完成步骤
1. 参考PR中内容[https://github.com/PaddlePaddle/PaddleOCR/pull/8433](https://github.com/PaddlePaddle/PaddleOCR/pull/8433)，在
[https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_overview.md#12](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_overview.md#12)总表里添加satrn精度和模型链接。
2. 单独写一个中文+英文的单模型介绍，参考：[https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_rec_crnn.md](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_rec_crnn.md)、[https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/algorithm_rec_crnn_en.md](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/algorithm_rec_crnn_en.md)。

### 提交内容：
1. 提交三个文档修改内容到PaddleOCR。

**Comment by shiyutang** [comment]
close due to https://github.com/PaddlePaddle/PaddleOCR/pull/11397#pullrequestreview-1797105336
