### ISSUE TITLE
Finetuning v4 - model only recognize single word in image but this contains more

### ISSUE THREAD

**Issue by xellDart** [PaddlePaddle/PaddleOCR#11137]
Hello, I have a problem. I'm running the configuration on my dataset using the en_PP-OCRv4_rec.yml file, but when I try to perform inference, it only recognizes one word when the test image contains more. I haven't modified the configuration file, and when I run 'python tools/infer_rec.py -c configs/rec/PP-OCRv4/en_PP-OCRv4_rec.yml' using the official v4 model, it recognizes more words. However, with the model I trained, it only recognizes one word. What could be the issue?

**Comment by data-ant** [comment]
I meet the same problem. And the training of v4_rec is quite strange, the acc is 0, and the norm_edit_distance is also very small.

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!

**Comment by data-ant** [comment]
May I ask you how do you solve this problem? Thks

**Comment by bhavyajoshi-mahindra** [comment]
> May I ask you how do you solve this problem? Thks

I am also looking for the solution for this. 
My finetuned model works great in case of single word images but does not work where there are multiple words in a image.

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!
