### ISSUE TITLE
发布的模型的具体性能是多少

### ISSUE THREAD

**Issue by LinJM** [PaddlePaddle/PaddleOCR#1114]
这个页面（https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md）
中发布的模型的具体性能指标是多少？

**Comment by MissPenguin** [comment]
参考benchmark：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/benchmark.md
