### ISSUE TITLE
精调小模型后，效果可以，但是还没开源的小infer模型效果好

### ISSUE THREAD

**Issue by hudielv** [PaddlePaddle/PaddleOCR#1115]
现在在做一个ocr识别pdf文档的任务，通过paddle的预训练识别模型，精调后（数据量大概300多万，用textrender生成的，生成的文字最大长度为25，其中有10万个乱序的数据），精调后的效果还可以，但是明显还没paddle开源的小模型infer模型效果好，请问下是不是可能以下的原因：
1、数据量不够的关系，数据量多少才行？
2、有乱序文字序列样本的原因？
3、发现实际样本中，一行最长的文字个数是40，而我生成的最长是25，是不是有可能这个原因？
还可能是其它原因么？
有什么方法可以保证微调后的模型效果？最起码不比开源的inference模型差呢？

**Comment by littletomatodonkey** [comment]
1. 请确保参考这个配置文件：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yml
2. 你的数据量有300W，但是目前所有长度超过25的文本在训练时都会被丢弃，所以得看下到底有多少数据是被用于训练了，如果少的话（或者长文本太多），需要把25调大一些，同时建议把输入shape调大一些，(32x320->32x480等)

**Comment by LDOUBLEV** [comment]
1. finetune只有生成数据不行，预训练模型已经在很多合成数据上训练了；
2. 数据量越多越好，最好是有标注的真实数据做fine-tune

**Comment by hudielv** [comment]
预训练为小模型，配置文件使用的是rec_chinese_lite_train_v1.1.yml，是没问题的
那我调下长度25看看，输入的shape也调下
batch_size现在为256，设置为512，大一些，效果会有提升么？

**Comment by littletomatodonkey** [comment]
256是比较合适的，微调的时候可以把学习率减小一些，减小2-5倍左右，512的话，学习旅需要是256时的学习旅的2倍
