### ISSUE TITLE
PPOCRLabel 安装问题求助

### ISSUE THREAD

**Issue by lisret** [PaddlePaddle/PaddleOCR#11166]
按照官网流程安装，尝试运行PPOCRLabel时出错，命令 python3 PPOCRLabel.py --lang ch
大家谁遇到这个错误，求指一条明路

出错信息：
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2851, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2839, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2829, in get_main_app
    win = MainWindow(lang=args.lang,
  File "PPOCRLabel.py", line 109, in __init__
    self.table_ocr = PPStructure(use_pdserving=False,
  File "G:\anaconda3\envs\PaddleOCR1\lib\site-packages\paddleocr\paddleocr.py", line 755, in __init__
    super().__init__(params)
  File "E:\li\common\PaddleOCR\PaddleOCR\PPOCRLabel\..\ppstructure\predict_system.py", line 82, in __init__
    self.return_word_box = args.return_word_box
AttributeError: 'Namespace' object has no attribute 'return_word_box'

**Comment by Shadow-Pirates** [comment]
我也是这样

**Comment by Gmgge** [comment]
请查看当前环境pip list中是否存在paddleocr，如果存在卸载或者手动从源码安装最新版本。

该问题由于发行版本的paddleocr和最新源码的版本存在一定的延迟，导致代码不匹配。

**Comment by DingHsun** [comment]
@Gmgge 我也遇到相同的問題，請問您相對應的版本是下載哪個？
以下是我的版本資訊，
paddleocr = 2.7.0.3
paddlepaddle = 2.5.1
PPOCRLabel = 2.1.3
是否需要把paddleocr降版？
感謝您~

**Comment by lisret** [comment]
> 请查看当前环境pip list中是否存在paddleocr，如果存在卸载或者手动从源码安装最新版本。
> 
> 该问题由于发行版本的paddleocr和最新源码的版本存在一定的延迟，导致代码不匹配。

感谢大佬，由于我的paddleocr版本过于新，与github拉取的项目代码不匹配，我这边paddleocr降到了2.6版本,能够正常运行

**Comment by lisret** [comment]
> 请查看当前环境pip list中是否存在paddleocr，如果存在卸载或者手动从源码安装最新版本。
> 
> 该问题由于发行版本的paddleocr和最新源码的版本存在一定的延迟，导致代码不匹配。

感谢大佬，由于我的paddleocr版本太新了，与github拉取的项目代码不匹配，我赶paddleocr降到了2.6版本，能够正常运行了

**Comment by DingHsun** [comment]
@lisret 感謝您，我把paddleocr降為2.6版本也能使用了！
