### ISSUE TITLE
ubuntu 16.04 总是出现异常

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#1117]
操作系统：ubuntu16.04
paddlepaddle==2.0.0rc0
PaddleOCR

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1604597144 (unix time) try "date -d @1604597144" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e900000706) received by PID 1800 (TID 0x7f8657465740) from PID 1798 ***]

**Comment by littletomatodonkey** [comment]
试下2.0b0呢？

**Comment by cole-dda** [comment]
2.0b0同样出现

**Comment by littletomatodonkey** [comment]
要不在docker里弄呢？这个不太好排查😂😂

**Comment by james5551** [comment]
> 2.0b0同样出现我也出现了这种问题，请问您解决了吗

**Comment by todhm** [comment]
Any solution to this problem?
