### ISSUE TITLE
C++和python环境下识别同一张图片的时间相差很多？？？

### ISSUE THREAD

**Issue by TigerKylin** [PaddlePaddle/PaddleOCR#1118]
都在windows环境下，都没有用GPU，分别用c++和python识别同一张图片，时间差了一半。

在python下：
        starttime = time.time()
        dt_boxes, rec_res = text_sys(img)
        elapse = time.time() - starttime
        print("Predict time of %s: %.3fs" % (image_file, elapse))
        执行结果是：Predict time of ./1.jpg: 0.606s

在C++下：
        auto start = std::chrono::system_clock::now();
        det->Run(srcimg, boxes); 
        std::vector<std::string> resultsocre;
        std::vector<std::vector<std::string>> result = rec->Run(boxes, srcimg, cls);
        auto end = std::chrono::system_clock::now();、
        std::cout << "cost = "
            << double(duration.count()) *
            std::chrono::microseconds::period::num /
            std::chrono::microseconds::period::den
            << "s" << std::endl;
       执行结果是：cost = 1.32728s

两个对比时间差了一半还多。

**Comment by tink2123** [comment]
在测试时间时，检测预测500次，然后去掉前10次的时间取平均值，会更准确一点。算上启动时间的话，不可比。

**Comment by ybxbupt** [comment]
> 都在windows环境下，都没有用GPU，分别用c++和python识别同一张图片，时间差了一半。
> 
> 在python下：
> starttime = time.time()
> dt_boxes, rec_res = text_sys(img)
> elapse = time.time() - starttime
> print("Predict time of %s: %.3fs" % (image_file, elapse))
> 执行结果是：Predict time of ./1.jpg: 0.606s
> 
> 在C++下：
> auto start = std::chrono::system_clock::now();
> det->Run(srcimg, boxes);
> std::vectorstd::string resultsocre;
> std::vector<std::vectorstd::string> result = rec->Run(boxes, srcimg, cls);
> auto end = std::chrono::system_clock::now();、
> std::cout << "cost = "
> << double(duration.count()) *
> std::chrono::microseconds::period::num /
> std::chrono::microseconds::period::den
> << "s" << std::endl;
> 执行结果是：cost = 1.32728s
> 
> 两个对比时间差了一半还多。

你windows下能运行的工程能否在gitee上分享一下，我的总是崩溃
