### ISSUE TITLE
DB训练过程中内存占用过大导致卡死

### ISSUE THREAD

**Issue by Wangweilai1** [PaddlePaddle/PaddleOCR#112]
发现了一个问题，我的机器是64G内存，使用DB mbv3 训练文本行定位模型， 在训练ICDAR2015 数据集没有问题，但是内存跳动很严重从9g-20g之间跳动；在训练自己的数据大约有1w多张样本，会存在内存占满的现象，导致卡死。但是当我把数据删除到只剩1000张左右时，则可以正常训练。但内存占用跳动仍然很严重。所以感觉可能这是一个bug？或者说如果我想训练10w张样本的数据，该用多大的内存空间才足够？

**Comment by tink2123** [comment]
请问您自己的数据shape是多少呢？初步建议您减小reader的进程数，定位下是否由于多进程reader读入数据过多导致的。减小配置文件中的num_workers，试下能否解决问题：
https://github.com/PaddlePaddle/PaddleOCR/blob/78d905113bbfe5ffeae80989e271a7235b69f66f/configs/det/det_db_icdar15_reader.yml#L4
我们也会测试排查，后续有结论会在尽快这里反馈。

**Comment by Wangweilai1** [comment]
图像大小是566*800*3，但是训练的时候仍然使用paddleocr的默认值640*640*3，将num_workers设置为1，仍然存在该问题。分析感觉不应该是num_workers的问题，因为同样的数据集1000张的时候num_workers也是8就没问题。

**Comment by tink2123** [comment]
问题暂时不好定位，目前代码中如果数据不能被batch_size整除，会把最后一个batch完全返回，或许您这边可以尝试把不足一个batch的数据丢弃，看是否还会卡住呢？
注释掉这两行代码即可：
https://github.com/PaddlePaddle/PaddleOCR/blob/ddefd24db02fe798afe5756a82a93d03ac518d46/ppocr/data/det/dataset_traversal.py#L64-L65

**Comment by Wangweilai1** [comment]
试了一下，仍然不行，依旧内存占满。

**Comment by tink2123** [comment]
麻烦提供一下机器环境，我们这边复现一下问题。
   1）PaddlePaddle版本：
   2）GPU：GPU型号，CUDA版本号，CUDNN版本号
   3）系统：
   4）docker镜像：
   5）Python版本号:

**Comment by Wangweilai1** [comment]
系统：Ubuntu 16.04.1 LTS 
GPU: Tesla K40c
CUDA: 10.1
CUDNN:v7.6.5
paddlepaddle-gpu: 1.7.2.post107
python: 3.7.4

没有用docker镜像，是直接安装的。
我试了使用gpu训练以及使用cpu训练都会存在该问题。
![1591261651(1)](https://user-images.githubusercontent.com/15275988/83737792-136d9a80-a686-11ea-91cf-7b4791201446.jpg)

**Comment by Wangweilai1** [comment]
发现了一个现像不知道对你们解决问题有没有帮助，1.这批数据是文档数据集，所以文本行很多，平均一张图像80行左右。2.我将数据量从1w多张减小到5000张左右，也是可以训练的，但是训练初期内存消耗从10G左右一直增长到50多G，然后会下降到10G左右，某个时刻又会缓慢上升到50G，训练过程中反复在10G-50G的内存之间徘徊。总体感觉应该是读取数据的那块有些问题，导致部分数据没释放，num_workers调低也一样。在训练ICDAR2015数据集也是会存在内存消耗不稳定的问题，只不过数据量太少所以波动范围小。

**Comment by tink2123** [comment]
图片中检测框过多可能显存占用可能会很大，您这边可以提供一份数据吗？能复现问题的数据量就好。

**Comment by bleakie** [comment]
我也出现类似的错误，在训练ccpd的车牌检测数据时，数据达到1w就会特别占内存，在数据很多时，训练这一块的数据利用还存在改进的空间

**Comment by LDOUBLEV** [comment]
> 我也出现类似的错误，在训练ccpd的车牌检测数据时，数据达到1w就会特别占内存，在数据很多时，训练这一块的数据利用还存在改进的空间

收到反馈，后续我们定位下问题

**Comment by wolfryu** [comment]
我也遇到同样问题，自己生成的图片2w张（640x640），gpu训练，但是cpu和内存被狂占用。显存也16g全满，然后卡死。icdar2015数据集就没事。
icdar2015训练的时候cpu经常100%，内存在2-12G之间来回。

**Comment by txyugood** [comment]
我也遇到这个问题，感觉是多进程造成的。暂时的解决方法写在#218了。

**Comment by lllulll** [comment]
找到问题了！设置预测过程的图片大小！！！
