### ISSUE TITLE
如何固化tensorRT engine,我不想每次启动进程重新转换engine

### ISSUE THREAD

**Issue by wangxu372848892** [PaddlePaddle/PaddleOCR#11204]
我用[(https://hub.docker.com/r/paddlepaddle/paddle/tags/)]中的paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6 容器中成功编译了2.5版本的Inference库（gpu+trt），并拉取paddleocr直接编译了C++版本的demo.我在arg.cpp下没找到可以固化cache trt engine的参数，按下面命令运行时每次都会重新转换engine,有时候会好几分钟，非常浪费时间

- 系统环境/System Environment：百度官方提供的ubuntu20.04 docker-gpu：2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6
- 版本号/Version：Paddle：inference推理库版本2.5  、  PaddleOCR版本： release/2.7
- 运行指令/Command Code：

       
          _./build/ppocr --det_model_dir=/paddle/PaddleOCR/deploy/cpp_infer/models/det \
              --rec_model_dir=/paddle/PaddleOCR/deploy/cpp_infer/models/rec \
              --cls_model_dir=/paddle/PaddleOCR/deploy/cpp_infer/models/cls \
              --image_dir=/paddle/PaddleOCR/deploy/cpp_infer/imgs/test1.png \
              --use_angle_cls=true \
              --use_gpu=true \
              --det=true \
              --rec=true \
              --cls=true \
              --use_tensorrt=true \
              --precision=fp16_

**Comment by wangxu372848892** [comment]
哦 木有人回答

**Comment by ermengz** [comment]
from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import Predictor
python api同样出现这个问题....
