### ISSUE TITLE
请问可以发布windows平台的 推理库2.0.0.b0版本么？

### ISSUE THREAD

**Issue by JasonZhangS** [PaddlePaddle/PaddleOCR#1121]

**Comment by littletomatodonkey** [comment]
你好可以从以下链接下载哈

* CPU: https://paddle-wheel.bj.bcebos.com/2.0.0-beta0/win-infer/mkl/cpu/fluid_inference_install_dir.zip
* GPU: https://paddle-wheel.bj.bcebos.com/2.0.0-beta0/win-infer/mkl/post107/fluid_inference_install_dir.zip
