### ISSUE TITLE
PaddleOCR加载训练好的推理模型和用python3 tools/infer/predict_system.py串联模型后的推理效果不一致

### ISSUE THREAD

**Issue by Double97828** [PaddlePaddle/PaddleOCR#11224]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

我在使用ocr = PaddleOCR(use_angle_cls=False,det_model_dir=DET_MODEL_PATH,rec_model_dir=REC_MODEL_PATH)加载文本识别和检测的推理模型后，效果和我用python3 tools/infer/predict_system.py --image_dir="./doc/" --det_model_dir="./inference/ch_PP-OCR_V3_det_new/"  --rec_model_dir="./inference/ch_PP-OCR_V3_rec/Teacher"出来的效果完全不一致，感觉我自己训练的推理模型在paddleocr.PaddleOCR加载后和直接用指令的完全不是一个效果

**Comment by BTBU2018** [comment]
同问！

**Comment by Double97828** [comment]
我找到的原因是
PaddleOCR(）这里有一个参数叫det_limit_type，这个原因，你们可以修改一下值看看
