### ISSUE TITLE
训练检测，best_accuracy保存模型的逻辑问题

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#1122]
问题：当设置训练轮数epoch_num很小时（比如5），最后结束可能没有best_accuracy模型被保存，因为只在eval_batch_step满足条件时触发。
这样的逻辑是否有问题，是不是应该当epoch_num全跑完时，不满足eval_batch_step条件时，也判断保存一次best_accuracy模型。
epoch_num: 5
eval_batch_step: [1000, 5000]

**Comment by hudielv** [comment]
逻辑没问题，tensorflow也是这样，保存最好的，就是在验证集中最好的，验证集没有跑，哪来的best_accurary
你把eval_batch_step设小点不就行了

**Comment by littletomatodonkey** [comment]
这块如果所有step都判断的话，eval的成本太高了
