### ISSUE TITLE
PaddleOCR 和 百度大脑 OCR的比较

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddleOCR#1124]
刚刚比较了 同是 百度 的两款服务，感觉还是 百度大脑的更好一些。不过 PaddleOCR 我用的是 精简模型。不知道大模型会不会好一些

------------------------------------------------------------------------

![test_ant_easy](https://user-images.githubusercontent.com/5635322/98433270-6bb42880-207a-11eb-957a-f3d0cbf9b07e.jpg)

![test_ant_easy_api](https://user-images.githubusercontent.com/5635322/98433268-67880b00-207a-11eb-94e5-69fbc928642f.jpg)
![test_ant_easy_paddle](https://user-images.githubusercontent.com/5635322/98433269-6a82fb80-207a-11eb-9de3-02f981b27e15.jpg)

------------------------------------------------------------------------

![test_ant_hard](https://user-images.githubusercontent.com/5635322/98433274-6c4cbf00-207a-11eb-92ad-424665f5ea1c.jpg)

![test_ant_hard_api](https://user-images.githubusercontent.com/5635322/98433272-6bb42880-207a-11eb-802f-bf2b902b5dde.jpg)
![test_ant_hard_paddle](https://user-images.githubusercontent.com/5635322/98433273-6c4cbf00-207a-11eb-8669-fa3376eb6e42.jpg)

**Comment by littletomatodonkey** [comment]
大模型会好一些，小模型能力稍微差了一些

**Comment by daming-lu** [comment]
@littletomatodonkey 
今天试了大模型，感觉还不如小模型😆 
请看效果：


ant 1 big:
![test_ant_1_paddle_big](https://user-images.githubusercontent.com/5635322/98452708-a5cb0c00-2106-11eb-8c87-a8fb7e2b0c16.jpg)

ang 1 small:
![test_ant_1_paddle_small](https://user-images.githubusercontent.com/5635322/98452711-a6fc3900-2106-11eb-9d0f-d59fc34ae718.jpg)

ant 2 big:
![test_ant_2_paddle_big](https://user-images.githubusercontent.com/5635322/98452713-a82d6600-2106-11eb-8292-fed8eac0d068.jpg)

ant 2 small
![test_ant_2_paddle_small](https://user-images.githubusercontent.com/5635322/98452715-a95e9300-2106-11eb-8303-77d30b471fd4.jpg)

**Comment by tink2123** [comment]
从 ant2 图上看，还是大网络效果会好一些，目前在文字叠加文字这种场景上，我们的模型效果还是不够好。会记录下这个问题，后续做优化～ 感谢提供用例。
