### ISSUE TITLE
ubuntu1804 C++版本cpp_infer编译测试出错

### ISSUE THREAD

**Issue by asinwon** [PaddlePaddle/PaddleOCR#1126]
系统环境： ubuntu1804 
预测库：https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-cpu-avx-mkl/fluid_inference.tgz
PaddleOCR：https://github.com/PaddlePaddle/PaddleOCR.git
opencv ：https://github.com/opencv/opencv/archive/3.4.7.tar.gz
gcc/g++：4.8.5

执行命令：./build/ocr_system ./tools/config.txt ../../doc/imgs/12.jpg
错误信息如下：
**root@PC202009041829:/mnt/d/WorkSpace/C_CPP/PPocr/CCP# ./build/ocr_system ./tools/config.txt ../../doc/imgs/12.jpg
=======Paddle OCR inference config======
char_list_file : ./ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn
use_angle_cls : 0
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 0
=======End of Paddle OCR inference config======
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::LoadProgramDesc()
5   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
6   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
/model (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:763)**

**Comment by ybxbupt** [comment]
windows下出现同样错误崩溃

**Comment by castor-xu** [comment]
反正就是各种编译不通过。非得逼我用Python吗？伤不起啊

**Comment by littletomatodonkey** [comment]
你试着自己编译生成下预测库呢？
