### ISSUE TITLE
PPStructure 这个版面分析没有分析完全，请指教

### ISSUE THREAD

**Issue by zhangquanwei962** [PaddlePaddle/PaddleOCR#11302]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
![result](https://github.com/PaddlePaddle/PaddleOCR/assets/61458769/3ea85209-8a46-46b1-8b33-e753a529dba0)

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res, draw_ocr

table_engine = PPStructure(show_log=True, det_db_unclip_ratio=2.5,
 det_limit_side_len=2000, recovery=True, ocr=True)

save_folder = './output'
img_path = '/home/zhangqw/example/data/AMMER.png'
image=cv2.imread(img_path, cv2.IMREAD_COLOR) #timg.jpeg

#获得三个通道
Bch,Gch,Rch=cv2.split(image)

#保存三通道图片
cv2.imwrite('blue_channel.jpg',Bch)
cv2.imwrite('green_channel.jpg',Gch)
cv2.imwrite('red_channel.jpg',Rch)
img = cv2.imread('/home/zhangqw/example/red_channel.jpg')
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

# for line in result:
#     line.pop('img')
#     print(line)
# print(result[1]['res']['html'])
from PIL import Image

font_path = '/home/zhangqw/example/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by yuriamao** [comment]
det_limit_side_len=2000 有错误，最大det_limit_side_len=960，可以issue里看看

**Comment by yuriamao** [comment]
提问：det_db_unclip_ratio=2.5,的设置？如何设置这个最佳

**Comment by zhangquanwei962** [comment]
> 提问：det_db_unclip_ratio=2.5,的设置？如何设置这个最佳

这个是自己手动设置的，和上面那个det_limit_side_len一样，我看issue里面说这个det_limit_side_len可以手动改的 默认是960 好像大点理论上识别的好点，det_db_unclip_ratio默认设置为2.0 检测框太小有时候就会把 ","识别成点，我自己手动加大了点
