### ISSUE TITLE
PPStructure得到了版面分析的结果后，对各个块的图进行OCR，有一个放大的预处理，导致像素失真，而OCR对缩放像素失真的鲁棒性很差。

### ISSUE THREAD

**Issue by harvinyou** [PaddlePaddle/PaddleOCR#11328]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by rexzhengzhihong** [comment]
您好。我也碰到这个问题。您后来怎么处理的

**Comment by RussellLuo** [comment]
@harvinyou @rexzhengzhihong 这里有个修复 PR：#11916，可以试一试。
