### ISSUE TITLE
识别两位数字效果不好

### ISSUE THREAD

**Issue by alex152738** [PaddlePaddle/PaddleOCR#1132]
通用中英文模型：对于识别2和3开头的两位数字可以识别出来，但是1开头的数字不能够识别出来，请问有什么好的解决办法吗？

**Comment by tink2123** [comment]
您好～ 可以给一张示例图看下嘛

**Comment by alex152738** [comment]
> 您好～ 可以给一张示例图看下嘛

![19](https://user-images.githubusercontent.com/47980839/98497940-78a26900-2280-11eb-89fe-13588a037506.jpg)
![16](https://user-images.githubusercontent.com/47980839/98497953-8526c180-2280-11eb-8cf0-ab88c75cb7cd.jpg)
![image](https://user-images.githubusercontent.com/47980839/98498097-e0f14a80-2280-11eb-8476-24729eaa7c49.png)

**Comment by xmy0916** [comment]
@alex152738 现有的模型好像还没加这种LCD样式的数据集，所以这些数字识别效果可能比较差

**Comment by alex152738** [comment]
> @alex152738 现有的模型好像还没加这种LCD样式的数据集，所以这些数字识别效果可能比较差

好吧，谢谢。

**Comment by alex152738** [comment]
> 您好～ 可以给一张示例图看下嘛

您好，请问训练检测模型，数据集较少的情况下，观察loss降到多少或者其它指数模型可以达到较好的效果。epoch为400时候loss为0.6，500epoch为0.4，并有振荡。

**Comment by tink2123** [comment]
> 您好，请问训练检测模型，数据集较少的情况下，观察loss降到多少或者其它指数模型可以达到较好的效果。epoch为400时候loss为0.6，500epoch为0.4，并有振荡。

建议通过hmean指标来衡量模型效果，DB在我们的中文数据集上，最终可以到62左右

**Comment by alex152738** [comment]
> > 您好，请问训练检测模型，数据集较少的情况下，观察loss降到多少或者其它指数模型可以达到较好的效果。epoch为400时候loss为0.6，500epoch为0.4，并有振荡。
> 
> 建议通过hmean指标来衡量模型效果，DB在我们的中文数据集上，最终可以到62左右

请问eval后prec和recall和hmean都为1.0是什么原因？

**Comment by littletomatodonkey** [comment]
可以看一下可视化效果，如果都正确的话，那么1.是正常的

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
