### ISSUE TITLE
FatalError Segmentation fault

### ISSUE THREAD

**Issue by kjlcl** [PaddlePaddle/PaddleOCR#11330]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu22, python3.10 
- 版本号/Version：Paddle：paddlepaddle              2.5.2 CPU version  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- python tools/infer/predict_system.py --image_dir=/mnt/f/ocr2/ --det_model_dir=./models/ch_PP-OCRv4_det_server_infer --det_limit_type=max --det_db_unclip_ratio=1.5 --rec_model_dir=./models/ch_PP-OCRv4_rec_server_infer --rec_image_shape="3, 48, 480" --draw_img_save_dir=./det_rec_infer/ --use_space_char=False --use_angle_cls=False --det_limit_side_len=2464 --use_gpu=False
- 完整报错/Complete Error Message：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   phi::KernelImpl<void (*)(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*), &(void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*))>::Compute(phi::KernelContext*)
6   void phi::ConvKernelImpl<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, phi::DenseTensor*)
7   phi::funcs::Im2ColFunctor<(phi::funcs::ColFormat)0, phi::CPUContext, float>::operator()(phi::CPUContext const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, phi::DataLayout)

环境检查结果：
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I1202 00:12:52.197489  1049 interpretercore.cc:237] New Executor is Running.
I1202 00:12:52.219213  1049 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1701446748 (unix time) try "date -d @1701446748" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f8c138ab580) received by PID 1010 (TID 0x7f9156f9a740) from PID 327857536 ***]

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by kjlcl** [comment]
相同环境，相同代码，更换模型为ch_PP-OCRv4_det_infer 和 ch_PP-OCRv4_rec_infer 可以正常运行

**Comment by UserWangZz** [comment]
#11530
