### ISSUE TITLE
模型微调以解决特殊字符识别问题

### ISSUE THREAD

**Issue by anonymous530** [PaddlePaddle/PaddleOCR#11338]
识别图片场景：游戏战绩截图，截图中包含用户昵称，昵称可能包含特殊字符。

基于 ppOCRv4的基础上对模型微调，目前想尝试将要识别的特殊字符集合加入到字典中，加入到字典中之后，应该是需要修改模型最后的输出维度吧，也就是全连接层的维度，这块是不用修改是吗？我这边看代码直接等于字符集合的长度了？

**Comment by tink2123** [comment]
只修改字典就好，FC纬度会根据字典变化

**Comment by anonymous530** [comment]
> 只修改字典就好，FC纬度会根据字典变化

@tink2123 好的，谢谢。
