### ISSUE TITLE
 数字 0 与 大写字母 O 经常识别错误

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#11334]
![001_12](https://github.com/PaddlePaddle/PaddleOCR/assets/72127773/a62216f9-4968-47b8-aabb-f62af929ad68)
 数字 0 与 大写字母 O 经常识别错误

rec_v3,rec_v4,rec_server_v4,svtr都识别错误

**Comment by thsno02** [comment]
如果你的字体固定的话，fine-tuning 会改善。
