### ISSUE TITLE
 2

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleOCR#11340]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by mpj1234** [comment]
自己不行不要怪别人，人家上次代码时候肯定做了测试，你用的库和人家要求都完全一致吗

**Comment by yyccR** [comment]
这个截图确实看不出问题

**Comment by xiaotailang** [comment]
你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？

**Comment by rui1998** [comment]
> 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？

我确实不想用 我用torch，客户傻逼非要用

**Comment by rui1998** [comment]
> 自己不行不要怪别人，人家上传代码时候肯定做了测试，你用的库和人家要求都完全一致吗

你要不看看我得截图 我哪里没配对？嗯？告诉我？哪个版本不是按要求弄得。上次跑一个人体分割模型还非得把paddlenlp也装上 纯粹恶心人吗不是？

**Comment by rui1998** [comment]
> 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？

我还真不觉得百度做的东西有多好，你说的这些什么从基础教程到工业部署整个流程，完全打通，确实如此 实际效率呢 你测过吗？我测过很拉跨，完全达不到部署得要求。我只能说步子迈的太大了 想把生态打通，可结果呢 你周围多少人用paddle 啊？

**Comment by rui1998** [comment]
> 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？
我评价厨师饭做的难吃我还得自己会做饭是吧

**Comment by chenzhiron** [comment]
> > 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？
> 
> 我确实不想用 我用torch，客户傻逼非要用

那为啥不跟客户对线，欺负个不会说话的代码。关于报错，不会查吗，发的图也看出来哪里的错误

**Comment by rui1998** [comment]
> > > 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？
> > 
> > 
> > 我确实不想用 我用torch，客户傻逼非要用
> 
> 那为啥不跟客户对线，欺负个不会说话的代码。关于报错，不会查吗，发的图也看出来哪里的错误

说实话 之前这个ocr代码我也跑通过，每次都配一堆百度得环境最后给你来个报错 我自认为debug能力很强，但是我不想把时间花费在这些环境上面，懒得查 大家得时间是很值钱的

**Comment by chenzhiron** [comment]
那不就跟客户说用不了，，，又不想折腾环境，又不想得罪客户，然后就来骂库，6

**Comment by rui1998** [comment]
> 那不就跟客户说用不了，，，又不想折腾环境，又不想得罪客户，然后就来骂库，6

这库我还真没听我身边做算法 的说好用过，让我浪费时间装的不爽我就骂 怎么了？你再叫连你一起骂

**Comment by mpj1234** [comment]
你是真可怜，不敢和甲方说明情况，又不自己重写代码，非要用人家，用了嫌弃不好

**Comment by rui1998** [comment]
> 你是真可怜，不敢和甲方说明情况，又不自己重写代码，非要用人家，用了嫌弃不好

所以呢 我觉得这库不好用 喷一下 怎么了 你要是闲着 ，可以去厕所吃屎

**Comment by rui1998** [comment]
> 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？

出来对线傻逼玩意儿，不是喜欢对线吗？

**Comment by rui1998** [comment]
> 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？

你爹我还真没用paddle 你爹我torch onnx  tensorrt 一套流程 比这 b玩意儿舒服多了 不知道你在叫个什么钩吧

**Comment by mpj1234** [comment]
> > 你完全可以不用paddle，可以学linus，觉得其它操作系统不好用，自己写一个linux，你觉得paddle不好用，也可以自己写一个新的。百度花大力气，在国内推广ai相关的技术，从基础教程到工业部署整个流程，完全打通。模型代码完全开源免费，给你使用。你不感激就算了，你自己看你这个说的是什么话？你有什么问题，就不能针对问题做说明吗？你一上来就这样说话，有多少人愿意帮你呢？
> 
> 你爹我还真没用paddle 你爹我torch onnx tensorrt 一套流程 比这 b玩意儿舒服多了 不知道你在叫个什么钩吧

大神，大佬，带我，但是请注意下素质
