### ISSUE TITLE
Android（移动端）部署OCR模型，模型相关的超参数没有设置接口吗？

### ISSUE THREAD

**Issue by honghanh2008** [PaddlePaddle/PaddleOCR#11359]
![1111](https://github.com/PaddlePaddle/PaddleOCR/assets/31463683/4149a995-66cd-4bc0-b3c5-16a779878f94)

例如上面图片里面的超参数。
parser.det_limit_side_len = 960
parser.det_limit_type = 'max'
parser.det_box_type = 'quad'
parser.det_db_thresh = 0.3  # 0.3
parser.det_db_box_thresh = 0.6  # 0.6
parser.det_db_unclip_ratio = 2.2  # 默认 1.5，检测出的文本扩大

上述参数python部署可以设置的，移动端无法设置。

**Comment by honghanh2008** [comment]
@tink2123 你好，可以回复一下吗？

**Comment by jenyav94** [comment]
If you use the demo version of the app, there is no interface for adjusting parameters as they are hardcoded. You can find these parameters in the C++ code.
