### ISSUE TITLE
ppocr ERROR: rec_algorithm must in ['CRNN', 'SVTR_LCNet']

### ISSUE THREAD

**Issue by moyu026** [PaddlePaddle/PaddleOCR#11358]
ocr = PaddleOCR(rec_model_dir=r'train_model\r45_visionlan\train_process\5\infer', rec_algorithm='VisionLAN', rec_char_dict_path=r'ppocr\utils\number.txt')

我想用这种方法加载自己训练的识别模型'VisionLAN'模型，但是提示只能用'CRNN'和'SVTR_LCNet'这两种方法，那应该怎么修改呢？

**Comment by honghanh2008** [comment]
你看看  SUPPORT_REC_MODEL = ['CRNN', 'SVTR_LCNet']   这个参数设置，如果只有上面两种方法，你模型算法不属于 SUPPORT_REC_MODEL，会导致保持，因为有下面这行判断代码：

        if params.det_algorithm not in SUPPORT_DET_MODEL:
            logger.error('det_algorithm must in {}'.format(SUPPORT_DET_MODEL))
            sys.exit(0)
        if params.rec_algorithm not in SUPPORT_REC_MODEL:
            logger.error('rec_algorithm must in {}'.format(SUPPORT_REC_MODEL))
            sys.exit(0)
