### ISSUE TITLE
why PaddleOCR fails on arabic integers recognition even if train on brilliant dataset

### ISSUE THREAD

**Issue by IbrarBabar009** [PaddlePaddle/PaddleOCR#11372]
@hritikakolkar @WenmuZhou @dyning @LDOUBLEV @tink2123 @MissPenguin @Topdu @Evezerest @littletomatodonkey@andyjpaddle @weisy11 @D-DanielYang @Topdu @sdcb @ZeyuChen @data-ant @bingoooplease help?????

I am using PaddleOCR for Arabic dataset recognition, and I have achieved an accuracy of 97.76%. However, I am encountering issues with error rates, specifically on Arabic dates like the example provided below:

<img width="293" alt="Screenshot 2023-12-13 at 12 03 51 PM" src="https://github.com/PaddlePaddle/PaddleOCR/assets/146720417/b15df761-ea5a-4588-9bdb-7a39f4397a58">

When I input such images into my trained PaddleOCR recognition model, it occasionally misses 2, 3, or 4 words or adds extra integers. Despite attempting to train PaddleOCR separately on dates with a labeled dataset of approximately 60,000 images, each with exact and correct ground truth, the accuracy does not seem to improve.

I am seeking assistance to understand why PaddleOCR is struggling with Arabic numbers and if there is any way to enhance its performance. Additionally, I am open to exploring alternative methods to address this issue. Can anyone provide insights or suggestions on improving the accuracy of PaddleOCR for recognizing Arabic numbers in date formats?"

**Comment by NaumanHSA** [comment]
Hi @IbrarBabar009,

I want to train a custom Arabic text recognition model but I cannot find the dataset. The current model works pretty well for me, but the size is 8MBs. I want to train a quantized light weight model as I'm gonna use it in Android application. Can you please guide me about the dataset, and the training process, as you have already done the training? Thanks in Advance.

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!
