### ISSUE TITLE
执行train.py报错

### ISSUE THREAD

**Issue by 20zhDong** [PaddlePaddle/PaddleOCR#1137]
AssertionError: We only support 'data()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode.           训练步骤都是按照readme来的，几番检查不知道问题出在哪里，该如何解决
![微信截图_20201109152757](https://user-images.githubusercontent.com/73943824/98511747-2d984e00-22a0-11eb-9f4a-5405039a2881.png)

**Comment by WenmuZhou** [comment]
你装的rc版本paddle吧， 在[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/train.py#L19)加上 import paddle;paddle.enable_static()

**Comment by 20zhDong** [comment]
> 你装的rc版本paddle吧， 在[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/train.py#L19)加上 import paddle;paddle.enable_static()

我是在AI studio上面运行的，加上去之后问题解决了，非常感谢！
