### ISSUE TITLE
在线的OCR识别好像不支持有噪点的识别？

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#114]
在线的OCR识别好像不支持有噪点的识别
![image](https://user-images.githubusercontent.com/12640462/83370517-413ab100-a3f2-11ea-9123-f7b04fa032ed.png)

另外对于图像大小稍微偏小的没有识别结果：
![image](https://user-images.githubusercontent.com/12640462/83370973-86abae00-a3f3-11ea-91b6-0e3d1fadf0c2.png)
当前对于图像的识别，要求的图像最小是什么范围，另外后续会对上面两点进行优化吗

**Comment by tink2123** [comment]
在线OCR识别针对的是，检测“大图”中的文本并识别。由于您测试的图片高度小于64，导致没有检测到框因此无法正常识别。如果只想识别上述crop出的图片结果，可以直接使用识别预测：
`python3 tools/infer/predict_rec.py --image_dir="{your img}" --rec_model_dir="{path/of/inference}"`
过小文字或噪声都是可以支持的。

**Comment by BeyondYourself** [comment]
好的，谢谢，明白了
