### ISSUE TITLE
SAST预训练模型进行训练

### ISSUE THREAD

**Issue by strWuYaoJu** [PaddlePaddle/PaddleOCR#1142]
使用SAST预训练模型进行训练自己的数据：
1.环境
        CPU 4
        RAM 32GB
        GPU v100
        显存 16GB
        磁盘 100GB
2.数据准备
      （1）把训练数据（xxx_test_img、xxx_train_img）和label放在./train_data/det/目录下
      （2）下载SAST的模型，加压到./pretrain_models/下
      （3）修改det_r50_vd_sast_icdar15.yml文件：
                 Global:
                           algorithm: SAST
                            use_gpu: true
                            epoch_num: 2000
                           log_smooth_window: 20
                           print_batch_step: 2
                            save_model_dir: ./output/det_sast/
                             save_epoch_step: 200
                            eval_batch_step: 5000
                             train_batch_size_per_card: 8
                            test_batch_size_per_card: 1
                              image_shape: [3, 640, 640]
                             reader_yml: ./configs/det/det_sast_icdar15_reader.yml
                             pretrain_weights: ./pretrain_models/sast_r50_vd_icdar2015/
                             save_res_path: ./output/det_sast/predicts_sast.txt
                            checkpoints: 
                            save_inference_dir:
     
             （4）修改det_sast_icdar15_reader.yml文件：
                TrainReader:
                                  reader_function: ppocr.data.det.dataset_traversal,TrainReader
                                  process_function: ppocr.data.det.sast_process,SASTProcessTrain
                                  num_workers: 8
                                  img_set_dir: ./train_data/det/
                                  label_file_path: ./train_data/det/train_label.txt
                                  data_ratio_list: [0.1, 0.45, 0.3, 0.15]
                                  min_crop_side_ratio: 0.3
                                    min_crop_size: 24
                                   min_text_size: 4
                                   max_text_size: 512

              EvalReader:
                                  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
                                 process_function: ppocr.data.det.sast_process,SASTProcessTest
                                 img_set_dir: ./train_data/det/
                                 label_file_path: ./train_data/det/test_label.txt
                                  max_side_len: 1536
  
               TestReader:
                                reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
                                process_function: ppocr.data.det.sast_process,SASTProcessTest
                                 infer_img: ./train_data/det/test_img/img_0644.bmp
                                 max_side_len: 1536

           （5）执行训练
python3 tools/train.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.pretrain_weights=./pretrain_models/sast_r50_vd_icdar2015/best_accuracy

报错：
----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 1, 160, 160] and the shape of Y = [-1, 1, 128, 128]. Received [160] in X is not equal to [128] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_mul > error]

**Comment by MissPenguin** [comment]
image_shape从512改成640后shape对不上了

**Comment by strWuYaoJu** [comment]
@MissPenguin 不能修改图片尺寸吗？？？？

**Comment by littletomatodonkey** [comment]
image_shape这个参数也要修改为`[3,512,512]`

![image](https://user-images.githubusercontent.com/14270174/98630554-609d1900-2356-11eb-9eba-994af67cf699.png)

**Comment by littletomatodonkey** [comment]
> @MissPenguin 不能修改图片尺寸吗？？？？
image_shape和train reader里的max_text_size需要同步修改

**Comment by longshifeng** [comment]
@strWuYaoJu 
你好，请问你用的是baidu ai studio么？
在这个平台上训练还需要自行安装cudnn么？

**Comment by strWuYaoJu** [comment]
不用，环境自带



---原始邮件---
发件人: "longshifeng"<notifications@github.com&gt;
发送时间: 2020年12月19日(周六) 上午10:46
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"juju"<1769800244@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] SAST预训练模型进行训练 (#1142)




 
@strWuYaoJu
 你好，请问你用的是baidu ai studio么？
 在这个平台上训练还需要自行安装cudnn么？
