### ISSUE TITLE
jetson-nano：Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by LittleSheepy** [PaddlePaddle/PaddleOCR#1143]
paddle:paddle2.0beta
jetsonnano sd卡挂载到、home/nvidia/sd上，在sd上编译，本来能运行成功，重启后报错Segmentation fault (core dumped)，重新编译，依然报错。
编译paddleOCR：
nvidia@nvidia-desktop:~/sd/PaddleOCR/deploy/cpp_infer$ sh tools/build.sh 
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/nvidia/tools/opencv-3.4.7/opencv3 (found version "3.4.7") 
cmake cxx flags -g -o3  -std=c++11
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.19)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:197 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "ocr_system" links to some libraries for which the linker
  must search:

    glog, gflags, protobuf, z, xxhash, -ldl -lrt -lgomp -lz -lm -lpthread, dl
    m, pthread, rt

  and other libraries with known full path:

    /home/nvidia/sd/paddle_inference_2.0.0-beta0_cuda10_cudnnv7.5_trt5_jetson_sm53_62_72/third_party/install/openblas/lib/libopenblas.a
    /home/nvidia/tools/opencv-3.4.7/opencv3/lib64/libopencv_calib3d.a
    /home/nvidia/tools/opencv-3.4.7/opencv3/share/OpenCV/3rdparty/lib64/liblibprotobuf.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_TENSORRT

-- Build files have been written to: /home/nvidia/sd/PaddleOCR/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[100%] Linking CXX executable ocr_system
[100%] Built target ocr_system

**运行时报错：
nvidia@nvidia-desktop:~/sd/PaddleOCR/deploy/cpp_infer$ ./build/ocr_system ./tools/config.txt ../../doc/imgs/12.jpg
Segmentation fault (core dumped)**

**Comment by LittleSheepy** [comment]
我重现了  我的paddle2.0推理库在卡里解压的。先挂在后，解压，编译就能用。重新挂在后就不能用了。

**Comment by LittleSheepy** [comment]
paddle2.0beta 预测库 要解压到nano板子上，避免这个问题。
但不知到为啥不能解压到sd卡上？期待大佬回答。

**Comment by littletomatodonkey** [comment]
是不是挂载之后，路径或者环境变量发生了改变

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
