### ISSUE TITLE
您好，能不能更新下iOS的demo，看着deploy目录的lite下看是，不是这个问题，就是其他问题，十分感谢

### ISSUE THREAD

**Issue by heXiangpeng** [PaddlePaddle/PaddleOCR#1144]
比如 预测库2.7，iOS14.1下

`self	ViewController *	0x102023200	0x0000000102023200
model1_path	__NSCFString *	"/private/var/containers/Bundle/Application/2647FEFE-4636-4B8B-9F9C-5C7444D0F1FF/paddle-lite-ocr.app/ch_ppocr_mobile_v1.1_det_prune_opt.nb"	0x0000000281ac9400
model2_path	__NSCFString *	"/private/var/containers/Bundle/Application/2647FEFE-4636-4B8B-9F9C-5C7444D0F1FF/paddle-lite-ocr.app/ch_ppocr_mobile_v1.1_rec_quant_opt.nb"	0x0000000281ac8140
model1_path_str	std::string	"/private/var/containers/Bundle/Application/2647FEFE-4636-4B8B-9F9C-5C7444D0F1FF/paddle-lite-ocr.app/ch_ppocr_mobile_v1.1_det_prune_opt.nb"	
model2_path_str	std::string	"/private/var/containers/Bundle/Application/2647FEFE-4636-4B8B-9F9C-5C7444D0F1FF/paddle-lite-ocr.app/ch_ppocr_mobile_v1.1_rec_quant_opt.nb"	
config	paddle::lite_api::MobileConfig	
paddle::lite_api::ConfigBase	paddle::lite_api::ConfigBase	
model_from_memory_	bool	false
lite_model_file_	std::string	"/private/var/containers/Bundle/Application/2647FEFE-4636-4B8B-9F9C-5C7444D0F1FF/paddle-lite-ocr.app/ch_ppocr_mobile_v1.1_det_prune_opt.nb"	
model_buffer_	std::string	""	
param_buffer_	std::string	""	
::net_ocr1	std::shared_ptr<paddle::lite_api::PaddlePredictor>	nullptr	
__ptr_	std::shared_ptr<paddle::lite_api::PaddlePredictor>::element_type *	NULL	0x0000000000000000`

**Comment by xiadeye** [comment]
你好，我在14.1下编译运行都是没问题的。可以提供一下复现的步骤吗？

**Comment by heXiangpeng** [comment]
> 你好，我在14.1下编译运行都是没问题的。可以提供一下复现的步骤吗？

从官方提供的iOS demo中，替换掉预测库和模型库，出现如上错误。

**Comment by heXiangpeng** [comment]
通过如下2.7版本，出现了错误，操作方式，替换掉iOS demo的预测库和模型
`./lite/tools/build_ios.sh  --arch=armv8  --with_cv=ON --with_extra=ON
`

`./opt --model_file=./ch_ppocr_mobile_v1.1_rec_quant_infer/model  --param_file=./ch_ppocr_mobile_v1.1_rec_quant_infer/params  --optimize_out=./ch_ppocr_mobile_v1.1_rec_quant_opt --valid_targets=arm
`


`[F 11/10 19:18: 8. 54 .../Paddle-Lite/lite/core/program.cc:187 RuntimeProgram] Check failed: op: no Op found for feed
[F 11/10 19:18: 8. 54 .../Paddle-Lite/lite/core/program.cc:187 RuntimeProgram] Check failed: op: no Op found for feed`

**Comment by xiadeye** [comment]
目前demo只测试过paddlelite 2.6和二阶段模型，我这边测试一下新模型，再更新下

**Comment by heXiangpeng** [comment]
> 目前demo只测试过paddlelite 2.6和二阶段模型，我这边测试一下新模型，再更新下

好的，十分感谢

**Comment by qizhen816** [comment]
@heXiangpeng IOS新的模型可以跑了吗？我看他们git上四个月没更新了……

**Comment by heXiangpeng** [comment]
@qizhen816 不能，总是有问题

**Comment by qizhen816** [comment]
@heXiangpeng 太久没维护了，我打算直接回1.1之前的版本用了

**Comment by heXiangpeng** [comment]
@qizhen816 那个正确率不高啊

**Comment by littletomatodonkey** [comment]
抱歉，动态图的ios demo尚未更新，如果希望使用ios的话，目前只能用1.1的模型哈

**Comment by fenglongteng** [comment]
为何安卓有动态图的demo，ios就没有呢，ios被忽略了？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
