### ISSUE TITLE
PPOCRLabel失败

### ISSUE THREAD

**Issue by WeiLong-Zh** [PaddlePaddle/PaddleOCR#11442]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：
- 完整报错/Complete Error Message：无法识别表格结构，文本信息也无法识别

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):no

请尽量不要包含图片在问题中/Please try to not include the image in the issue.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/44223423/078466fa-1743-48fd-9cc8-3fea115be5dd)

**Comment by SWHL** [comment]
因PPOCRLabel已经搬家了，后续有问题请移步[PPOCRLabel](https://github.com/PFCCLab/PPOCRLabel)提问哈！
此issue先行关闭了。
