### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by haximap** [PaddlePaddle/PaddleOCR#1145]
请教一下，下面两种模型部署，有什么不同吗？
![image](https://user-images.githubusercontent.com/74235583/98650164-7b31bb00-2373-11eb-993e-222fd2f6dc73.png)

**Comment by MissPenguin** [comment]
可以参考这条FAQ：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q3415-hubservingpdserving%E8%BF%99%E4%B8%A4%E7%A7%8D%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88

**Comment by haximap** [comment]
> 可以参考这条FAQ：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q3415-hubservingpdserving%E8%BF%99%E4%B8%A4%E7%A7%8D%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88

谢谢回复，理解了
