### ISSUE TITLE
英文空格分词效果不是很好

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleOCR#1147]

**Comment by MissPenguin** [comment]
用的哪个模型，给几个case看看？

**Comment by yuemengrui** [comment]
@MissPenguin 用的是通用中英文105M那个识别模型
![image](https://user-images.githubusercontent.com/24349763/98915107-6e909c80-2504-11eb-9ce5-5329a18f0e0f.png)
识别结果：Call optionishRuss2000
![image](https://user-images.githubusercontent.com/24349763/98915222-96800000-2504-11eb-96d3-7b523d44bdc7.png)
识别结果：Buy toopen
![image](https://user-images.githubusercontent.com/24349763/98915316-b6afbf00-2504-11eb-8d2b-6fbefe1c4924.png)
识别结果：PutoptionSel Sct Industrial

**Comment by ZhangRong-Mz** [comment]
目前我使用场景下英文的空格识别也是很差

**Comment by MissPenguin** [comment]
英文模型最近优化升级了，空格的问题也优化了，可以再试试哈：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/models_list_en.md#english-recognition-model
