### ISSUE TITLE
单字图片如何合成文本行图片

### ISSUE THREAD

**Issue by TOMORINAONAO** [PaddlePaddle/PaddleOCR#11485]
我手上有单字的手写图片数据，一个字有50张左右的图片，如何将这些单字数据合成为文本行拿来训练识别模型？
是直接用python将图片拼接到一起吗？
还是有能合成的工具，官方的数据合成工具我看是用字体文件和语料来生成的，不适合我这个。

**Comment by tink2123** [comment]
目前没有工具，可以尝试使用opencv直接拼接？
