### ISSUE TITLE
本地部署之后怎么封装好供调用呢？

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1149]

**Comment by xialei2821212670** [comment]
如果你是想封装成api的话，可以看下deploy\hubservering下面，就有检测识别的代码

**Comment by xialei2821212670** [comment]
我是对其进行了简单的封装，flask+niginx

**Comment by BeyondYourself** [comment]
这个用paddle Serving部署就OK了http  和rpc的调用

**Comment by lybcodes** [comment]
> 我是对其进行了简单的封装，flask+niginx



> 如果你是想封装成api的话，可以看下deploy\hubservering下面，就有检测识别的代码


> 如果你是想封装成api的话，可以看下deploy\hubservering下面，就有检测识别的代码

**Comment by lybcodes** [comment]
> 我是对其进行了简单的封装，flask+niginx

hubservering里是通过http远程调用的方式，我想在本地比如说能不能打成一个包来供其他程序去调用

**Comment by littletomatodonkey** [comment]
你好，应该是可以的，有其他小伙伴，把ocr做成了exe的，可以在issue里搜一下

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
