### ISSUE TITLE
PP-OCRv4在线体验地址失效，提示该应用已下线

### ISSUE THREAD

**Issue by sdvina** [PaddlePaddle/PaddleOCR#11491]
README.md 中的 PP-OCRv4 在线体验地址：https://aistudio.baidu.com/application/detail/7658  失效，提示该该应用已下线。
如果不再提供PP-OCRv4 的在线体验，请及时更新README.md。
![微信图片_20240115112525](https://github.com/PaddlePaddle/PaddleOCR/assets/10064158/791e6a0d-4b50-4ddb-bf6d-88573ef6a1ab)
![微信图片_20240115112535](https://github.com/PaddlePaddle/PaddleOCR/assets/10064158/d69054a2-b3f1-4ddb-b3b1-c95a5dfeb982)

**Comment by Aquapisces** [comment]
感觉PaddleOcr已经废了没人管了，一起拿多个issue压根没人问，连内存泄漏都没人管，也不知道当初怎么能上线的

**Comment by tink2123** [comment]
在线体验可以使用的，可以再点击尝试一下。 3天前可能应用临时调试下线了，不是文档有误，感谢使用。

**Comment by KyleWang-Hunter** [comment]
> 连内存泄漏都没人管，也不知道当初怎么能上线的

就是上线让我们来测试bug的☺
