### ISSUE TITLE
请问文字识别的置信度是如何计算的？

### ISSUE THREAD

**Issue by mrlihellohorld** [PaddlePaddle/PaddleOCR#11497]
感谢开源如此优秀的项目！我关注文字识别的置信度是如何计算的，我看了crnn中的CTC会计算每个字符的置信度，但是paddle会对一句话输出一个置信度，每句话的置信度是对每个文字置信度进行平均的吗  我没有找到对应的代码请问文字识别的置信度是如何计算的？

**Comment by QQQTAO** [comment]
> 感谢开源如此优秀的项目！我关注文字识别的置信度是如何计算的，我看了crnn中的CTC会计算每个字符的置信度，但是paddle会对一句话输出一个置信度，每句话的置信度是对每个文字置信度进行平均的吗 我没有找到对应的代码请问文字识别的置信度是如何计算的？

在ppocr/postprocess/rec_postprocess.py这个文件中有ctc后处理的代码

**Comment by mrlihellohorld** [comment]
谢谢

**Comment by mrlihellohorld** [comment]
好的
