### ISSUE TITLE
用自己的数据训练的模型检测不出目标

### ISSUE THREAD

**Issue by chenyangMl** [PaddlePaddle/PaddleOCR#115]
您好：
用了自己的数据训练db模型，没有出现像icdar纳样的loss信息，但保存了模型。用保存的模型检测不出任何目标。

自己排除了数据组织的问题，按照icdar格式组织的数据。想请问还可以从那方面定位问题？
2020-06-01 03:35:15,330-INFO: Already save model in ./output/det_db2//iter_epoch_50
2020-06-01 03:35:43,853-INFO: Already save model in ./output/det_db2//iter_epoch_100
2020-06-01 03:36:14,578-INFO: Already save model in ./output/det_db2//iter_epoch_150
2020-06-01 03:36:47,190-INFO: Already save model in ./output/det_db2//iter_epoch_200

**Comment by tink2123** [comment]
如果没有打印出loss信息，说明没有正常训练。请问您都做了哪些修改呢？是否修改了数据存储文件夹名称，方便贴一下您的自定义label吗。

**Comment by chenyangMl** [comment]
> 如果没有打印出loss信息，说明没有正常训练。请问您都做了哪些修改呢？是否修改了数据存储文件夹名称，方便贴一下您的自定义label吗。

数据配置目录按照对应关系修改了，应该没有问题。
自定义的label如下这样，太长截取了片段。
test/img_0.jpg	[{"transcription": "text", "points": [[86, 1510], [269, 1510], [269, 1526], [86, 1526]]}, {"transcription": "text", "points": [[84, 1527], [325, 1527], [325, 1546], [84, 1546]]}, {"transcription": "text", "points": [[600, 1521], [1102, 1521], [1102, 1534], [600, 1534]]}, {"transcription": "text", "points": [[321, 784], [548, 784], [548, 802], [321, 802]]}, {"transcription": "text", "points": [[86, 1492], [459, 1492], [459, 1508], [86, 1508]]}, {"transcription": "text", "points": [[598, 1430], [1104, 1430], [1104, 1442], [598, 1442]]}, {"transcription": "text", "points": [[202, 901], [279, 901], [279, 917], [202, 917]]}, {"transcription": "text", "points": [[85, 1474], [493, 1474], [493, 1490], [85, 1490]]}, {"transcription": "text", "points": [[512, 1368], [549, 1368], [549, 1383], [512, 1383]]}, {"transcription": "text", "points": [[455, 1216], [486, 1216], [486, 1229], [455, 1229]]}

**Comment by tink2123** [comment]
图片路径与标签之间需要用一个`tab` 键分隔，首先请确认下您的label里用的空格划分，还是`\t`。 如果无法判断问题可以修改下列代码，查看报错信息：
https://github.com/PaddlePaddle/PaddleOCR/blob/e804d51be1fe577fb8cdbd115401d47bac6d4cea/ppocr/data/det/db_process.py#L102-L103

修改为：
```
        if imgvalue is None:
            logger.info("{} does not exist!".format(img_path))
            return None
```

>如果未能正常训练，怎么没有报错那，感觉好奇怪

代码报错信息不够完善，我们会尽快修复，感谢反馈

**Comment by chenyangMl** [comment]
> 图片路径与标签之间需要用一个`tab` 键分隔，首先请确认下您的label里用的空格划分，还是`\t`。 如果无法判断问题可以修改下列代码，查看报错信息：
> https://github.com/PaddlePaddle/PaddleOCR/blob/e804d51be1fe577fb8cdbd115401d47bac6d4cea/ppocr/data/det/db_process.py#L102-L103
> 
> 修改为：
> 
> ```
>         if imgvalue is None:
>             logger.info("{} does not exist!".format(img_path))
>             return None
> ```
> 
> > 如果未能正常训练，怎么没有报错那，感觉好奇怪
> 
> 代码报错信息不够完善，我们会尽快修复，感谢反馈

多谢，有了这个报错提示，定位出问题了。图片目录配置的时候少了一个“/”。晕死，建议优化下，
剩下的一切正常，可以正常训练了。

**Comment by tink2123** [comment]
好的～不客气，多谢建议
