### ISSUE TITLE
识别模型acc高，但实际测试正确率低

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1151]
您好，我使用rec_chinese_common_train_v1.1.yml，以及百度的ch_ppocr_server_v1.1_rec_pre预训练模型进行训练，约400w训练数据（内有中英文，字典是我自己的），大概一个epoch，准确率90%，但转换为infer形式时准确率极低。对其进行eval，出现错误：图片的reader形式为lmdb，也有数据，但显示数目为0：
![1](https://user-images.githubusercontent.com/51456283/98754181-19b82d80-2401-11eb-8efa-78c46759967b.PNG)
使用转换的infer形式，也识别不正确，会将英文识别为中文
配置文件如下：
![2](https://user-images.githubusercontent.com/51456283/98755172-0312d600-2403-11eb-8f32-229906af37a9.PNG)
![3](https://user-images.githubusercontent.com/51456283/98755232-2473c200-2403-11eb-8932-27d2604dccbb.PNG)

**Comment by littletomatodonkey** [comment]
你可以先看下直接使用ch_ppocr_server_v1.1_rec_pre能否直接预测和导出，没问题的话再用自己的模型把

**Comment by tyy2tyy** [comment]
奇怪，我将读取方式的名字为rec_benchmark_reader.yml，即使我在rec_chinese_common_train_v1.1.yml内更改了文件，也是出错，但将读取文件的reader名改成rec_chinese_reader.yml就可以运行了
