### ISSUE TITLE
Converting labels and train model: errors

### ISSUE THREAD

**Issue by Nico10Hahn17** [PaddlePaddle/PaddleOCR#11513]
System Infos:
Ubuntu 22.04.3 LTS
paddleocr Version: 2.7.0.3
Python 3.8.18

1) When I try to convert labels like this explanations:

cmd: python gen_label.py --mode="rec" --input_path="{path/of/origin/label}" --output_label="rec_gt_label.txt"

![Bildschirmfoto vom 2024-01-18 09-25-05](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/de88ad85-4653-42d9-92e9-f2b31f05b1ec)

i get this error:
![Bildschirmfoto vom 2024-01-18 09-26-11](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/283ccffd-e9f7-4ba2-b5d9-6fa0022c4824)

2) I saved the pretrained model in the folder pretrained_models/en_PP-OCRv3_rec_train. I have in this folder the files best_accurancy.pdopt, best_accuracy.pdparams, best_accuracy.states, train.log

when i want to start training:
python3 tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=en_PP-OCRv3_rec_train/best_accuracy

I receive:
AssertionError: The en_PP-OCRv3_rec_train/best_accuracy.pdparams does not exists!

but it exist:
![Bildschirmfoto vom 2024-01-18 09-44-31](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/978ba271-9e24-49ee-8361-52fdb288f42e)

3) When I train an model (hard code the path to the pretrained model in save_load.py):

cmd: python3 tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=en_PP-OCRv3_rec_train/best_accuracy

error: [2024/01/18 09:52:17] ppocr ERROR: When parsing line word_7.png,  "fusionopolis"
, error happened with msg: Traceback (most recent call last):
  File "/home/krones2/Downloads/PaddleOCR/ppocr/data/simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

My gt.txt:
![Bildschirmfoto vom 2024-01-18 09-53-38](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/7dc71446-4699-4ce7-a3fc-9a93b488e2cd)

![Bildschirmfoto vom 2024-01-18 09-54-15](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/c408102e-6a53-4e3b-b45b-1c3e76ea1292)

Thanks !

**Comment by Nico10Hahn17** [comment]
Thank you very much, now it's working !

I have another question about the training. Currently I have a small datatset so recognize numbers [0-9]. I use a pretrained model:
en_PP-OCRv3_rec_train/best_accuracy.pdparams
input image shape: 1300x900x3
the hyperparameters i did not change from

When I load the pretrained parameters i receive a warning:
![Bildschirmfoto vom 2024-01-19 07-11-30](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/cef65ccf-cf21-42c3-8125-921ce14eabad)

I want to finetune the model.

During the training the loss gets down but the accurancy stays all the time 0.0:
![Bildschirmfoto vom 2024-01-19 07-01-45](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/822aa91f-55ae-4193-9d5a-dcd79f047899)

![Bildschirmfoto vom 2024-01-19 07-01-17](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/6cf8c449-853c-4a58-85d0-8e735116912c)

When I use the code from the QuickStart section i get quite good results already with 80 percent correct recognition of the numbers:

![Bildschirmfoto vom 2024-01-19 07-03-32](https://github.com/PaddlePaddle/PaddleOCR/assets/108824385/0e1e1686-059f-4ad9-bfe3-643356c546ff)

How can I use this model from the python code in your QuickStart section and finetune this model ?
Why I have a missmatch with the loaded parameters ?

**Comment by tink2123** [comment]
Have you modified the dictionary? The FC dimension of the last layer of the model corresponds to the dictionary. Modifying the dictionary will result in the parameters of the last layer not being loaded. 
If you want to fully use the pre-trained parameters, please keep the dictionary file unchanged. But generally speaking, modifying the dictionary is a correct operation. It is normal for the accuracy to be 0 at the beginning. You only need to maintain it for longer training rounds to get good accuracy.
