### ISSUE TITLE
能否控制只识别横向，不识别纵向

### ISSUE THREAD

**Issue by EvilCalf** [PaddlePaddle/PaddleOCR#1152]

**Comment by littletomatodonkey** [comment]
这块目前横排文本和竖排文本都是统一识别的，如果需要的话，可以自己训一个横向纵向的分类器，或者检测数据微调，数据标注中不包纵向文本框即可。

**Comment by BeyondYourself** [comment]
> 这块目前横排文本和竖排文本都是统一识别的，如果需要的话，可以自己训一个横向纵向的分类器，或者检测数据微调，数据标注中不包纵向文本框即可。

这个目前好像在切割那块改一下代码就可以了，直接送去识别，得到的结果一般是空，把那个旋转90度的注释了好像就不会去识别竖排文本了
![image](https://user-images.githubusercontent.com/12640462/99015972-118ef800-2591-11eb-9beb-27551a2646a6.png)
