### ISSUE TITLE
paddleocr使用多进程并发请求解析，会报以下错误

### ISSUE THREAD

**Issue by chros425** [PaddlePaddle/PaddleOCR#1156]
请教大佬们，使用多并发进程调用 paddleocr的接口报以下错误（接口使用tornado自己封装的restful服务）
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1605094768 (unix time) try "date -d @1605094768" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f0c19e00000) received by PID 32645 (TID 0x7f0e0f488740) from PID 434110464 ***]

版本信息如下：
paddlepaddle                       2.0.0b0
Python   3.6.4
使用的是CPU，没有用GPU

**Comment by tink2123** [comment]
可能是paddle版本不稳定导致的，尝试安装 paddlepaddle==2.0.0rc0 看看吧

**Comment by hudielv** [comment]
paddlepaddle==2.0.0rc0 也报这个错误，是不是进程开的太多，占cpu太满了，导致这个错误？
反正我这也是同样的问题：使用多并发进程调用 paddleocr的接口报以下错误（在tornada服务中）
![image](https://user-images.githubusercontent.com/48787551/100532714-bdde0900-3236-11eb-92d9-4cd13ed3869b.png)
请及时回复解决，感谢

**Comment by WenmuZhou** [comment]
我感觉是进程数太多了，设为cpu核数看一下吧
