### ISSUE TITLE
目前官网由 PadleOCR V4版本的 用户数据训练 教程码？

### ISSUE THREAD

**Issue by countryhotel** [PaddlePaddle/PaddleOCR#11571]
目前官网由 PadleOCR V4版本的 用户数据训练 教程码？ ch_PP-OCRv4_det 或者 ch_PP-OCRv4_server_det 的都行

**Comment by tink2123** [comment]
训练流程都是类似的，选择不同配置文件即可。可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/detection.md

**Comment by countryhotel** [comment]
收到，我再去试试。目前，ch_PP-OCRv4_det 与 ch_PP-OCRv4_server_det 都是可以正常训练迁移的吗？
________________________________
发件人: xiaoting ***@***.***>
发送时间: 2024年2月5日 11:14
收件人: PaddlePaddle/PaddleOCR ***@***.***>
抄送: countryhotel ***@***.***>; Author ***@***.***>
主题: Re: [PaddlePaddle/PaddleOCR] 目前官网由 PadleOCR V4版本的 用户数据训练 教程码？ (Issue #11571)


训练流程都是类似的，选择不同配置文件即可。可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/detection.md

―

**Comment by tink2123** [comment]
嗯嗯 是的

**Comment by tink2123** [comment]
也可以尝试去PaddleX上完成一站式训练，准备好训练数据即可无代码完成训练、评估、推理部署流程：
PP-OCRv4-server-det: https://aistudio.baidu.com/projectdetail/paddlex/6792800
PP-OCRv4-mobile-det: https://aistudio.baidu.com/projectdetail/paddlex/6792883

**Comment by countryhotel** [comment]
也可以尝试去PaddleX上完成一站式训练，准备好训练数据即可无代码完成训练、评估、推理部署流程：
PP-OCRv4-server-det: https://aistudio.baidu.com/projectdetail/paddlex/6792800
PP-OCRv4-mobile-det: https://aistudio.baidu.com/projectdetail/paddlex/6792883

这个有对应的 PP-OCRv4-server-rec 说明吗？ 以及 det与rec的集成部署？
