### ISSUE TITLE
服务器端C++预测 windows平台 vs 2019 安装问题

### ISSUE THREAD

**Issue by countryhotel** [PaddlePaddle/PaddleOCR#11577]
目前在参考官方文档 学习 Visual Studio 2019 Community CMake 编译指南 

其中“环境准备”要求如下：

1.1 安装必须环境
● Visual Studio 2019
● CUDA 10.2，cudnn 7+ （仅在使用GPU版本的预测库时需要）
● CMake 3.22+
请确保系统已经安装好上述基本软件，我们使用的是 VS2019 的社区版。

我在安装Visual Studio 2019过程中出现下图的选择界面，应该选取哪一个才能适配？

![2019选取](https://github.com/PaddlePaddle/PaddleOCR/assets/154119759/fac67c2f-d54e-4029-8cc2-5241726fd46a)

**Comment by TingquanGao** [comment]
使用C++的桌面开发

**Comment by countryhotel** [comment]
谢谢，后面是选了这个就可以了
