### ISSUE TITLE
PaddleOCR C++ 部署 可执行程序 输出问题

### ISSUE THREAD

**Issue by countryhotel** [PaddlePaddle/PaddleOCR#11580]
按照官网《windows_vs2019_build.md》，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/cpp_infer/docs/windows_vs2019_build.md

所属流程成功生成了ppocr.exe程序，在cmd内运行后发现会输出很多打印信息，如下图所示：
![C++部署打印log信息](https://github.com/PaddlePaddle/PaddleOCR/assets/154119759/79285a36-73c7-4aaf-b713-2420bdefd7e0)

但实际上我们真正关心的是检测结果，如下图红框所示，
![实际有效结果](https://github.com/PaddlePaddle/PaddleOCR/assets/154119759/99367a98-8a69-4498-84f5-aad61c6130ba)

现在的问题是：
1 能否通过修改或参数设置，关闭运行过程中的打印信息
2 能否通过修改或参数设置，将检测结果输出到txt文件内，或类似效果

**Comment by countryhotel** [comment]
有大佬可以给予指导回复吗？

**Comment by clSpider** [comment]
> 有大佬可以给予指导回复吗？

from paddleocr.ppocr.utils.logging import get_logger
get_logger().setLevel(logging.WARNING)
试试
