### ISSUE TITLE
Bug : PaddleOCR tag v2.7.1 has a minor indentation issue

### ISSUE THREAD

**Issue by comchobo** [PaddlePaddle/PaddleOCR#11599]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 22.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleOCR/ppstructure/utility.py
- 运行指令/Command Code：pip install git+https://github.com/PaddlePaddle/PaddleOCR.git@v2.7.1
- 完整报错/Complete Error Message：

```
File "/tmp/pip-req-build-uk4qh3hr/ppstructure/utility.py", line 230
          g            avg_char_width = (bbox_x_end - bbox_x_start) / len(rec_str)
      IndentationError: expected an indented block after 'else' statement on line 229
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no): yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

In v2.7.1/ppstructure/utility.py, I could find a typo in following code line 230
`g            avg_char_width = (bbox_x_end - bbox_x_start) / len(rec_str)`

**Comment by mriamnobody** [comment]
Im too facing the similar issue. Im on Python v3.7.9, Windows 11.

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from paddleocr import VERSION
  File "C:\Users\rosha\Downloads\Compressed\PaddleOCR-2.7.1\paddleocr.py", line 53, in <module>
    from ppstructure.utility import init_args, draw_structure_result
  File "C:\Users\rosha\Downloads\Compressed\PaddleOCR-2.7.1\ppstructure\utility.py", line 230
    g            avg_char_width = (bbox_x_end - bbox_x_start) / len(rec_str)
    ^
IndentationError: expected an indented block
```

**Comment by tttleon** [comment]
same problem too, i used 2.7.0 version that fixed the problem @mriamnobody 
`pip install "paddleocr==2.7.0" ,`
