### ISSUE TITLE
在CTCLoss这个类中的reduce_sum中是否会出现nan

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#116]
之前在计算CTCLoss的时候，在sum_cost = fluid.layers.reduce_sum(cost)，计算结果有的时候经常出现nan，对于这种情况有什么处理办法吗

**Comment by dyning** [comment]
不知道你那边学习率是如何设置的？学习率设置过大，容易出nan

**Comment by BeyondYourself** [comment]
那CTCLoss这个类是否需要有相关的nan的判断，之前测试学习率从0.1--0.001都出现了nan，后来也没找到程序问题

**Comment by dyning** [comment]
如果出现nan的话，继续训练也是有问题的，还是需要调整参数。
