### ISSUE TITLE
Teacher model for ch_PP-OCRv4_rec_distill.yml is not available to train/Finetune model

### ISSUE THREAD

**Issue by saikrishna431** [PaddlePaddle/PaddleOCR#11601]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

The Student model is available for ch_PP-OCRv4_rec is available from the link 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7.1/doc/doc_ch/models_list.md

But the teacher model for the same is not available. Tried using the ch_PP-OCRv4_server_rec model as the teacher model but the model architecture itself is not similar to the teacher model used in the distilled model - ch_PP-OCRv4_rec_distill.yml. 

Can you please provide the link for the teacher model for finetuning purposes.

**Comment by tink2123** [comment]
Our experiments found that when the ch_PP-OCRv4_server_rec is used for distillation, the improvement in the accuracy of the student model is limited. 
Therefore the server_rec is not used as the teacher model. Sorry, the large model for distillation is temporarily unavailable.

**Comment by renmada** [comment]
> Our experiments found that when the ch_PP-OCRv4_server_rec is used for distillation, the improvement in the accuracy of the student model is limited. Therefore the server_rec is not used as the teacher model. Sorry, the large model for distillation is temporarily unavailable.

有开源teacher的计划吗
