### ISSUE TITLE
使用tools/eval.py出错的问题

### ISSUE THREAD

**Issue by YukSing12** [PaddlePaddle/PaddleOCR#1161]
自己训练了一个检测模型，使用tools/eval.py对分辨率为1536x2048的验证集A进行验证时一切正常，但对分辨率为2448x2048的验证集B进行验证时出现错误，错误信息如下：

> W1112 14:33:46.996348  4224 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 11.0, Runtime API Version: 9.0
> W1112 14:33:47.001650  4224 device_context.cc:260] device: 0, cuDNN Version: 7.6.
> 2020-11-12 14:33:49,064-INFO: Finish initing model from ./output/det_db_enlarge_tsbd/iter_epoch_200
> 2020-11-12 14:33:49,400-INFO: test tackling num:1
> Traceback (most recent call last):
>   File "tools/eval.py", line 97, in <module>
>     main()
>   File "tools/eval.py", line 69, in main
>     metrics = eval_det_run(exe, config, eval_info_dict, "eval")
>   File "/home/aistudio/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 136, in eval_det_run
>     cal_det_res(exe, config, eval_info_dict)
>   File "/home/aistudio/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 72, in cal_det_res
>     fetch_list=eval_info_dict['fetch_varname_list'])
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
>     six.reraise(*sys.exc_info())
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
>     raise value
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
>     return_merged=return_merged)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
>     use_program_cache=use_program_cache)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
>     fetch_var_name)
> paddle.fluid.core_avx.EnforceNotMet: 
> 
> --------------------------------------------
> C++ Call Stacks (More useful to developers):
> --------------------------------------------
> 0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
> 1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
> 2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
> 3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
> 4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> 5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> 6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> 7   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
> 8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> 9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)
> 
> ------------------------------------------
> Python Call Stacks (More useful to users):
> ------------------------------------------
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
>     attrs=kwargs.get("attrs", None))
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
>     return self.main_program.current_block().append_op(*args, **kwargs)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12237, in _elementwise_op
>     'use_mkldnn': use_mkldnn})
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12416, in elementwise_add
>     return _elementwise_op(LayerHelper('elementwise_add', **locals()))
>   File "/home/aistudio/PaddleOCR/ppocr/modeling/heads/det_db_head.py", line 162, in __call__
>     input=in5, scale=2), y=in4)  # 1/16
>   File "/home/aistudio/PaddleOCR/ppocr/modeling/architectures/det_model.py", line 141, in __call__
>     predicts = self.head(conv_feas, mode)
>   File "/home/aistudio/PaddleOCR/tools/program.py", line 172, in build
>     dataloader, outputs = model(mode=mode)
>   File "tools/eval.py", line 54, in main
>     config, eval_program, startup_prog, mode='test')
>   File "tools/eval.py", line 97, in <module>
>     main()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 154, 128] and the shape of Y = [1, 96, 153, 128]. Received [154] in X is not equal to [153] in Y at i:2.
>   [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
>   [operator < elementwise_add > error]

153应该是2448/16得到的，但154就不知道为什么了，希望能帮忙看看。

**Comment by LDOUBLEV** [comment]
可否发一个图像，我们测试下

**Comment by YukSing12** [comment]
![01440](https://user-images.githubusercontent.com/39983134/99023425-92ed8700-259f-11eb-89da-3133482f0cce.JPG)

**Comment by LDOUBLEV** [comment]
我单独预测这个图像的没问题，你是不是在eval的时候，设置的batch_size大于1，看一下你的配置文件中，Global.test_batch_size_per_card设置为1 ，再eval看下

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/99032517-a9eaa400-25b4-11eb-9f99-ade4d0d063a7.png)

**Comment by YukSing12** [comment]
> 我单独预测这个图像的没问题，你是不是在eval的时候，设置的batch_size大于1，看一下你的配置文件中，Global.test_batch_size_per_card设置为1 ，再eval看下

Global.test_batch_size_per_card已经设为1了。
同样的模型、数据集和配置，我在reader.yml里面把test_image_shape改为[2432，2048]又不会报错

**Comment by YukSing12** [comment]
> 我单独预测这个图像的没问题，你是不是在eval的时候，设置的batch_size大于1，看一下你的配置文件中，Global.test_batch_size_per_card设置为1 ，再eval看下

可以给你的reader配置给我看看吗？我现在将模型换成官方的ch_ppocr_mobile_v1.1_det_train，eval 2448x2048的图也是出错，应该不是模型问题。

**Comment by LDOUBLEV** [comment]
你用的是最新的代码吗，最新的代码，reader的yml文件里已经删掉了 test_image_shape ，我的配置文件就是现在repo中的配置文件/configs/det/det_mv3_db_v1.1.yml

**Comment by YukSing12** [comment]
> 你用的是最新的代码吗，最新的代码，reader的yml文件里已经删掉了 test_image_shape ，我的配置文件就是现在repo中的配置文件/configs/det/det_mv3_db_v1.1.yml

更新代码后运行成功了。非常感谢。
