### ISSUE TITLE
ppocr ERROR: det_algorithm must in ['DB']

### ISSUE THREAD

**Issue by NidhoggBo** [PaddlePaddle/PaddleOCR#11619]
尝试将文本检测‘DB’模块换为‘PSE’模块时报这个错误

**Comment by a31413510** [comment]
请问你是使用的哪个模型呢

**Comment by NidhoggBo** [comment]
> 请问你是使用的哪个模型呢

现在是‘DB’模型，想换成‘PSE’，别的都是默认的没有改动

**Comment by a31413510** [comment]
目前paddleocr的whl包只支持了DB的后处理，不支持更换其他算法。

**Comment by a31413510** [comment]
如果想要实现自定义的改动，可参考下面文档，尝试直接使用源码推理：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/algorithm_det_psenet.md#4

**Comment by NidhoggBo** [comment]
> 如果想要实现自定义的改动，可参考下面文档，尝试直接使用源码推理：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/algorithm_det_psenet.md#4

好的 感谢

**Comment by a31413510** [comment]
好的，当前issue我先关闭了，后续有问题可以reopen补充
