### ISSUE TITLE
Have any way to divide PPOCRLabel into 2 independent functions were detetion and recognition

### ISSUE THREAD

**Issue by PxCPeter** [PaddlePaddle/PaddleOCR#11616]
Hi team, I try to use PPOCRLabel as tool to detection and recognition handwritten English paper but the result is really not good at both detection and recognition.
1. I have try to change model language at "Choose model language" to English but it have same output with  default model ( it sitll line-wise level not word-wise level)
2. I think that PPOCRLabel only use detection function will help improve output. 
        self.ocr = PaddleOCR(use_pdserving=False,
                             use_angle_cls=True,
                             det=True,
                             cls=True,
                             rec=False,
                             use_gpu=gpu,
                             lang=lang,
                             show_log=False)
I have added rec = False but output is same.
Thank you in advance.

**Comment by changdazhou** [comment]
You can try changing to the English detection model, but you need to choose the corresponding model to export the inference model and modify the parameter value of det_model_dir:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/algorithm_det_db.md

**Comment by PxCPeter** [comment]
@changdazhou  thanks for your answer but I don't really know what to change in my code. Please talk in more detail or can you give me a specific sample.
Thank you in advance.

**Comment by changdazhou** [comment]
firstly,you should refrence this command to get inference model :

**Comment by changdazhou** [comment]
First, you need to refer to this command to export the inference model
`python3 tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./det_r50_vd_db_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_db`

**Comment by changdazhou** [comment]
first, you need to refer to this command to export the inference model
`python3 tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./det_r50_vd_db_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_db`
then，add det_model_dir=your/inference/path in self.ocr = PaddleOCR(...)

**Comment by changdazhou** [comment]
for PPOCRLabel.py, detetion and recognition can't be simply split into two independent parts. if necessary, it seems that you can only modify the corresponding code to achieve it.
