### ISSUE TITLE
ppstructure输出的版面图比原始的图片多出来一些无关的东西

### ISSUE THREAD

**Issue by charliedream1** [PaddlePaddle/PaddleOCR#11617]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04.5 LTS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.7
- 运行指令/Command Code：代码如下
- 完整报错/Complete Error Message：无

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

```python
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/1.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = 'doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```

问题：执行quickstart中的样例脚本，如上。得到的版面分析图片会多出右侧的一页，出现完全无关的东西

原始输入图片
![1](https://github.com/PaddlePaddle/PaddleOCR/assets/15007828/bec69b36-895c-412e-87f2-2624de405d85)

得到的输出图片
![result](https://github.com/PaddlePaddle/PaddleOCR/assets/15007828/68837ee7-488d-4250-8330-4e2e40d3536e)

**Comment by changdazhou** [comment]
右侧是检测模型的可视化输出效果哈，如果不需要可以只输出draw_layout:https://github.com/PaddlePaddle/PaddleOCR/blob/0525f6bb01bfed401f767894619f6a25ee750892/ppstructure/utility.py#L131C5-L131C16

**Comment by charliedream1** [comment]
是注释170和171的ocr那一段吗？

**Comment by charliedream1** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 下午2:20
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] ppstructure输出的版面图比原始的图片多出来一些无关的东西 (Issue #11617)




 
对的，应该还直接返回img_layout就可以哈
