### ISSUE TITLE
arm部署使用官方源码推理，v3在pd推理时效果优于v4，但nb推理检测不到，或者检测不全

### ISSUE THREAD

**Issue by Zomcxj** [PaddlePaddle/PaddleOCR#11623]
PaddleOCR2.7.1
ch_PP-OCRv3_det_student.yml
ch_PP-OCRv4_det_student.yml
size 960
检测非机动车车牌：官方模型v3 v4都能检测   根据自己数据集训练的v3 v4模型   v3的det推理模型效果比v4的det推理模型效果好，检测框更贴合文字    但是转换到nb模型后，v3基本检测不出结果 v4大部分检测与pd模型相同，少部分检测有错误

pd_det_infer_v3_my
![w8_v3my_pd](https://github.com/PaddlePaddle/PaddleOCR/assets/74281348/3cd03cdb-09b0-41eb-b2bf-f293d4185462)

**Comment by Zomcxj** [comment]
pd_det_infer_v4_my
![w8_v4my_pd](https://github.com/PaddlePaddle/PaddleOCR/assets/74281348/cc8d2a43-2aaa-4491-a9f3-f24ce5ddf112)
nb_det_infer_v3_my
![w8_v3my_nb](https://github.com/PaddlePaddle/PaddleOCR/assets/74281348/a97343f1-6409-4b8a-86d7-835355544188)
nb_det_infer_v4_my
![w8_v4my_nb](https://github.com/PaddlePaddle/PaddleOCR/assets/74281348/b501cc10-40b3-46f8-b9f8-7ac9b464c680)

**Comment by tink2123** [comment]
是自己量化了模型吗？需要先评估下量化模型的效果是否满足需求

**Comment by Zomcxj** [comment]
解决了  pd推理时 v3图片预处理type:min 736有效果   v4图片预处理type:max 960    arm源码为max960 修改了arm源码预处理 
 但是训练时yml文件都没有指定这块不是很懂

**Comment by tink2123** [comment]
> 解决了 pd推理时 v3图片预处理type:min 736有效果 v4图片预处理type:max 960 arm源码为max960 修改了arm源码预处理 但是训练时yml文件都没有指定这块不是很懂

赞，这个参数只在推理中，训练是定长的输入。
