### ISSUE TITLE
hubserving无法使用paddle.jit.load()加载模型

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#11637]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubunut22
- 版本号/Version：Paddle：2.4.2  PaddleOCR： 问题相关组件/Related components：hubserving
- 运行指令/Command Code：我们自己用paddle训练了一个字体识别模型并且使用paddle.jit.save转换为静态模型， 在ppstructure模块中加载这个模型，使用paddleocr.py文件调用运行时可以正常运行，但是在hubserving服务中报错，无法使用报错`AssertionError: We only support 'load()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.`. 按照提示加入paddle.disable_static(), 服务化正常启动，但是请求服务时无法得到结果，排查后发现还是在新模型加载时报错`AttributeError: 'numpy.ndarray' object has no attribute 'name'`
- 完整报错/Complete Error Message：

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/e9f6dd69-9bda-4aa5-a9cd-f3dcb3dbf689)

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/abd456a4-5e0d-4618-9ee6-ff1cefc9c623)

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):
yes
请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by TingquanGao** [comment]
建议使用paddleserving

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
