### ISSUE TITLE
识别训练 crnn+ctc 测试集准确率提升不了

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#1163]
CRNN+ctc训练字符，开始时候还能正常训练，后面训练了两三天，训练集的准确率只有在学习率为0.000000的时候稍微有些提升，其他的学习率没有变化。
测试集不变后，准确率训练了20多个epoch，训练集准确率在90左右，测试集一直在70出头，是因为学习率太高吗还是别的原因，识别的图片挺简单的，还请大佬们指教以下训练时候需要注意什么?
![Dingtalk_20201112195129](https://user-images.githubusercontent.com/29195016/98936828-7cecb180-2520-11eb-9396-1c2a7a26a98e.jpg)

`
配置文件
Global:
  algorithm: CRNN
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_CRNN_25
  save_epoch_step: 10
  eval_batch_step: 500
  train_batch_size_per_card: 128
  test_batch_size_per_card: 128
  image_shape: [3, 32, 320]
  max_text_length: 25
  # 100
  character_type: ch
  character_dict_path: /home/aistudio/data/data10879/label_list.txt
  loss_type: ctc
  distort: true
  use_space_char: false
  reader_yml: ./configs/rec/rec_chinese_reader.yml
  pretrain_weights: ./pretrain_models/ch_ppocr_server_v1.1_rec_train/best_accuracy
  checkpoints: ./output/rec_CRNN_25/best_accuracy
  save_inference_dir:
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_resnet_vd,ResNet
  layers: 34

Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  fc_decay: 0.00004
  SeqRNN:
    hidden_size: 256
    
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  l2_decay: 0.00004
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay_warmup
    step_each_epoch: 126
    total_epoch: 500
    warmup_minibatch: 1000
`

**Comment by littletomatodonkey** [comment]
训练集90，测试集70多的话，看着是过拟合了，
1. 加入更多的增广方式或者调大prob的概率：https://github.com/PaddlePaddle/PaddleOCR/blob/a501603d54ff5513fc4fc760319472e59da25424/ppocr/data/rec/img_tools.py#L307
2. 调大系统的l2 dcay值：https://github.com/PaddlePaddle/PaddleOCR/blob/a501603d54ff5513fc4fc760319472e59da25424/configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yml#L47

**Comment by yjmm10** [comment]
> 训练集90，测试集70多的话，看着是过拟合了，
> 
> 1. 加入更多的增广方式或者调大prob的概率：https://github.com/PaddlePaddle/PaddleOCR/blob/a501603d54ff5513fc4fc760319472e59da25424/ppocr/data/rec/img_tools.py#L307
> 2. 调大系统的l2 dcay值：https://github.com/PaddlePaddle/PaddleOCR/blob/a501603d54ff5513fc4fc760319472e59da25424/configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yml#L47

谢谢大佬，我再试试效果
