### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by mahaling** [PaddlePaddle/PaddleOCR#11634]
Your code is licensed under Apache 2.0 which offers the most liberal license letting people use your software for even commercial purposes. But you have PyMuPDF as one of your requirements. This software comes under AGPL-3.0 which means your software also has to be released under AGPL. Can someone clarify if this is a right understanding?.

**Comment by jzhang533** [comment]
related: #8873

**Comment by jzhang533** [comment]
cc: @michaelowenliu @mahongweichina

**Comment by jzhang533** [comment]
I am not an OSS legal expert, but I do think we'd better follow instructions on this page : [APACHE LICENSE V2.0 AND GPL COMPATIBILITY](https://www.apache.org/licenses/GPL-compatibility.html). which means, we should make PyMuPDF optional in PaddleOCR project.

If anyone in the community wants to help, please create a PR and assign @jzhang533 and @tink2123 as reviewers.

**Comment by keskival** [comment]
Related: https://snyk.io/advisor/python/paddleocr
Snyks shows several severe license risks from dependencies.
