### ISSUE TITLE
检测任务负样本格式问题

### ISSUE THREAD

**Issue by Wang-Yu-Qing** [PaddlePaddle/PaddleOCR#11635]
在这里读到了文本检测任务的数据格式，有个疑问，如果图片为负样本，即没有任何文字，第二个字段应该是怎样的？https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/dataset/ocr_datasets.md#1-%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B

**Comment by Sunting78** [comment]
您好，文本检测不考虑负样本 没有框的话可以不做任何标注

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
