### ISSUE TITLE
Detection model accuracy drop after exporting

### ISSUE THREAD

**Issue by kwang19113** [PaddlePaddle/PaddleOCR#11644]
So after training i test my model with 10 images

export model:
python tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model="./output/db_mv3/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"

predict images (only got 2/10):
python tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_db_inference/" --image_dir="./doc/imgs/" --use_gpu=True

but if i use (i got 9/10 images right.):
python tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./doc/imgs/" Global.pretrained_model="./output/db_mv3/best_accuracy"

**Comment by Nada-ibrahim** [comment]
@kwang19113 
I have the same problem. Did you find a solution ?

**Comment by kwang19113** [comment]
> @kwang19113 I have the same problem. Did you find a solution ?

Hi it was due to the preprocessing code in predict_det for the image size. I don't remember specifically which part but you can check in there

**Comment by Nada-ibrahim** [comment]
Thanks a lot. I checked and found that the image size was really the issue. Adding `--det_limit_type=min` to the `predict_det` command solved the problem.
