### ISSUE TITLE
is can work or not ;(

### ISSUE THREAD

**Issue by LLotme** [PaddlePaddle/PaddleOCR#11655]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by a31413510** [comment]
嗨，请问你的问题是什么呢
