### ISSUE TITLE
char_list.append(self.character[int(text_index[idx])]); ;IndexError: list index out of range

### ISSUE THREAD

**Issue by SolEePark** [PaddlePaddle/PaddleOCR#1165]
I changed \PaddleOCR\tools\infer\utility.py...

    parser.add_argument("--rec_model_dir", type=str, default = "./PaddleOCR/inference/en_ppocr_mobile_v1.1_rec_infer")
    parser.add_argument("--rec_image_shape", type=str, default="3, 32, 100")
    parser.add_argument("--rec_char_type", type=str, default='en')
    parser.add_argument("--rec_char_dict_path", type=str, default="./PaddleOCR/ppocr/utils/dict/ic15_dict1.txt")

but error occured
  File "app_2.0.py", line 103, in Card_OCR
    final_card_number = final_number(filename,'_raw.jpg')
  File "app_2.0.py", line 121, in final_number
    ans = main(utility.parse_args(),'output/'+filename+state)
  File "app_2.0.py", line 604, in main
    dt_boxes, rec_res = text_sys(img,filename)
  File "app_2.0.py", line 559, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "\PaddleOCR\tools\infer\predict_rec.py", line 252, in __call__
    preds_text = self.char_ops.decode(rec_idx_tmp)
  File "\PaddleOCR\ppocr\utils\character.py", line 122, in decode
    char_list.append(self.character[int(text_index[idx])])
IndexError: list index out of range

**Comment by LDOUBLEV** [comment]
Maybe your charactor file 'ic15_dict1.txt' is not matched with our model.  you can try '/PaddleOCR/ppocr/utils/ic15_dict.txt'.
