### ISSUE TITLE
> Hello! I had similar issue after applying custom model for paddleocr. The error raised from custom_ocr=custom_ocr = PaddleOCR( ... )

### ISSUE THREAD

**Issue by mtahaayhan** [PaddlePaddle/PaddleOCR#11661]
> Hello! I had similar issue after applying custom model for paddleocr. The error raised from custom_ocr=custom_ocr = PaddleOCR( ... )
> 
> The following was entire error message and the code after that.
> 
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
> 1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> 2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
> 5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
> 6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
> 7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
> 8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
> 9   paddle::framework::ir::SelfAttentionFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
> 10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Illegal instruction` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1708043256 (unix time) try "date -d @1708043256" if you are using GNU date ***]
>   [SignalInfo: *** SIGILL (@0x7f56e0a1e86a) received by PID 468056 (TID 0x7f56e8434200) from PID 18446744073183291498 ***]
> 
> Illegal instruction (core dumped)
> ```
> 
> The code to run
> 
> ```
> from paddleocr import PaddleOCR,draw_ocr
> from PIL import Image
> import cv2 
> import matplotlib.pyplot as plt
> 
> #Loading the detector and ocr with the previously trained weights
> 
> #### the error raised from PaddleOCR function. #####
> custom_ocr = PaddleOCR(use_angle_cls=True,
>                 lang="en",
>                 rec_model_dir='.output/en_PP-OCRv3_rec_inference',
>                 det_model_dir='./output/det_db_inference', 
>                 rec_char_dict_path='./ppocr/utils/en_dict.txt',
>                 use_gpu=False,
>                 show_log=False)
> 
> # ocr = PaddleOCR(use_angle_cls=True, lang="en")
> img_path = "./img1006.jpg"
> 
> img = cv2.imread(img_path)
> plt.imshow(img)
> # plt.show()
> 
> 
> result = custom_ocr.ocr(img)
> # result = ocr.ocr(img)
> result = result[0]    
> 
> # draw result
> image = Image.open(img_path).convert('RGB')
> boxes = [line[0] for line in result]
> txts = [line[1][0] for line in result]
> scores = [line[1][1] for line in result]
> im_show = draw_ocr(image, boxes, txts, scores, font_path='./doc/fonts/simfang.ttf')
> im_show = Image.fromarray(im_show)
> im_show.save('result.jpg')
> 
> im_show
> ```

Is there any update for this problem?

_Originally posted by @mtahaayhan in https://github.com/PaddlePaddle/PaddleOCR/issues/8871#issuecomment-1973268194_

**Comment by changdazhou** [comment]
It is recommended that you try using GPU

**Comment by sunilswain** [comment]
Did you solve this issue?

**Comment by mtahaayhan** [comment]
> Did you solve this issue?

Yes, can u try with these versions:

paddleocr==2.7.0.3
paddlepaddle==2.5.1

**Comment by mtahaayhan** [comment]
For those of you experiencing issues with the compatibility of PaddleOCR and PaddlePaddle, I've found a solution that works well. After some testing, it appears that using the following versions together resolves the issues:

PaddleOCR version: 2.7.0.3
PaddlePaddle version: 2.5.1
Make sure to align your environment to these versions to avoid any potential compatibility issues.

**Comment by sunilswain** [comment]
> > Did you solve this issue?
> 
> Yes, can u try with these versions:
> 
> paddleocr==2.7.0.3 paddlepaddle==2.5.1

Thanks, Got solved!
