### ISSUE TITLE
训练ppocr_v1.1时python defunct

### ISSUE THREAD

**Issue by yisampi** [PaddlePaddle/PaddleOCR#1166]
![image](https://user-images.githubusercontent.com/22785527/99017947-e684b400-2550-11eb-97d0-2f85cf955eda.png)

**Comment by LDOUBLEV** [comment]
像是进程被kill了或者不正常退出，python本身也有残留进程的问题

**Comment by yisampi** [comment]
连续两天都是这样的情况 进程在 但是训练不进行了 也没有训练日志输出

**Comment by LDOUBLEV** [comment]
清理掉这些进程，重新启动训练，把num_workers设置小一点

**Comment by BeyondYourself** [comment]
重启过频繁大概率会有僵尸进程出现，建议每次重启查看是否有僵尸进程
