### ISSUE TITLE
KIE: KeyError: 0

### ISSUE THREAD

**Issue by Chenfeixia** [PaddlePaddle/PaddleOCR#11663]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 版本号/Version：Paddle：2.7.1 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：tools/infer_kie_token_ser.py -c train_data/ser_vi_layoutxlm_udml.yml -o Architecture.Models.Student.Backbone.checkpoints=./train_data/output/ser_idcard_model/best_accuracy Global.infer_img=train_data/val/xxx.jpg
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "L:\PaddleOCR-2.7.1\tools\infer_kie_token_ser.py", line 151, in <module>
    result = result[0]
KeyError: 0

使用自定义训练的KIE模型运行推理时出现此错误。
出现错误时result 的值为： {'Student': [[{'transcription': '用发票', 'bbox': [2243, 455, 2605, 596], 'points': [[2243.0, 471.0], [2600.0, 455.0], [2605.0, 579.0], [2248.0, 596.0]], 'pred_id': 1, 'pred': 'QUESTION'}, {'transcription': 'No 122638724400154130', 'bbox': [2835, 469, 3933, 617], 'points': [[2835.0, 506.0], [3929.0, 469.0], [3933.0, 579.0], [2839.0, 617.0]], 'pred_id': 0, 'pred': 'O'}, {'transcription': '东增', 'bbox': [1655, 508, 1895, 613], 'points': [[1655.0, 520.0], [1891.0, 508.0], [1895.0, 601.0], [1660.0, 613.0]], 'pred_id': 1, 'pred': 'QUESTION'......
![屏幕截图 2024-03-03 130056](https://github.com/PaddlePaddle/PaddleOCR/assets/114477851/52ba8642-e7b6-4096-a719-6aa7093a123a)

**Comment by L-Q-K** [comment]
Hey did you fix this ? I am facing the same issue. Thank you

**Comment by leonardung** [comment]
In tools/infer_kie_toker_ser.py line 158, I added this:
result, _ = ser_engine(data)
if isinstance(result, dict):
    result = result["Teacher"]
result = result[0]
