### ISSUE TITLE
在paddleocr 命令设置--use_gpu=true 但是运行起来没有生效 

### ISSUE THREAD

**Issue by xxWeiDG** [PaddlePaddle/PaddleOCR#11679]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/140797957/1b79c00c-8caa-469c-99ea-d9cf8d15621f)
问题信息如上图显示，我在命令中已经设置--use_gpu=true，但是运行起来--use_gpu=false ,nvidia-smi命令显示显卡正常

**Comment by XiaokangLei** [comment]
没有装gpu版的paddlepaddle吧，pip show paddlepaddle-gpu看看有没有

**Comment by xxWeiDG** [comment]
> pip show paddlepaddle-gpu

有
`
Name: paddlepaddle-gpu
Version: 2.6.0.post117
Summary: Parallel Distributed Deep Learning
Home-page: https://www.paddlepaddle.org.cn/
Author:
Author-email: Paddle-better@baidu.com
License: Apache Software License
Location: /usr/local/lib/python3.10/dist-packages
Requires: astor, decorator, httpx, numpy, opt-einsum, Pillow, protobuf
Required-by:
`

**Comment by xxWeiDG** [comment]
> import paddle paddle.utils.run_check()

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/140797957/6bb1adcd-7579-4e78-aa12-c8647b80aec4)
只显示CPU
