### ISSUE TITLE
PP-OCRv4模型 python推理开启 enable_mkldnn=True，速度很慢

### ISSUE THREAD

**Issue by lan11** [PaddlePaddle/PaddleOCR#11670]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu20
- 版本号/Version：Paddle：2.6  PaddleOCR：2.7 
- det模型：[ch_PP-OCRv4_det_infer.tar](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar)
- rec模型：[ch_PP-OCRv4_rec_infer.tar](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar)
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by tink2123** [comment]
PP-OCRv4 在cpu上推荐使用openvino加速

**Comment by lan11** [comment]
好的，谢谢

**Comment by gongdj** [comment]
openvinov要如何搞？
