### ISSUE TITLE
扫描版PDF版面恢复效果很差

### ISSUE THREAD

**Issue by ATP-BME** [PaddlePaddle/PaddleOCR#11687]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 
- 运行指令/Command Code：
- D:/apps/miniconda3/envs/GNN/python.exe predict_system.py --image_dir="E:/project/LM/知识注入/pdf/test/niujin1.pdf" --det_model_dir=inference/ch_PP-OCRv4_det_infer --rec_model_dir=inference/ch_PP-OCRv4_rec_infer --rec_char_dict_path="../ppocr/utils/ppocr_keys_v1.txt" --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_cdla_infer --layout_dict_path="../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt" --vis_font_path=../doc/fonts/simfang.ttf --recovery=True --output=../output/ --table=False --det_limit_type='max' --det_limit_side_len=3200
- 
- 恢复结果
- 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/b955bafc-e6e4-4908-86a3-ab7d64e436b3)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/7c313eff-89f1-46a7-b4d2-cbd6daee8ced)

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by tink2123** [comment]
感谢关注，版面恢复的效果我们会进一步升级。
