### ISSUE TITLE
想问一下，这些垂类模型是在哪里下载吖？

### ISSUE THREAD

**Issue by tohsakask** [PaddlePaddle/PaddleOCR#11695]
这里现实关注公众号获取，但是里面什么都没有。

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/68817764/75de19d2-4359-48b1-a644-4b8101697124)

**Comment by a31413510** [comment]
## 模型下载

如需下载上述场景中已经训练好的垂类模型，可以加入PaddleX官方交流频道获取20G OCR学习大礼包（内含《动手学OCR》电子书、课程回放视频、前沿论文等重磅资料）

- PaddleX官方交流频道：https://aistudio.baidu.com/community/channel/610
