### ISSUE TITLE
使用文字检测的模型测试自己的图片后，检测出来的矩形框的信息是存在哪里呢？

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1170]

**Comment by LDOUBLEV** [comment]
如果是使用tools/infer_det.py预测的，文本框信息保存在https://github.com/PaddlePaddle/PaddleOCR/blob/59b3a1ebbbce850ec527d04004ec1be7248ec7a0/configs/det/det_mv3_db.yml#L17
