### ISSUE TITLE
 module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by ccyx1997** [PaddlePaddle/PaddleOCR#11707]
- 系统环境/System Environment：win 10 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components："~~/anaconda\envs\textshot\lib\site-packages\skimage\morphology\_skeletonize.py
-
- 运行指令/Command Code：import paddleocr
- 完整报错/Complete Error Message：AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify a
ny behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**这个问题已经解决**
numpy版本尝试了1.24.4和1.24.3，都会报这个错，但是安装1.23.2版本就能正常运行了

**Comment by tink2123** [comment]
请问可以提供更具体的报错信息吗？是在代码的哪一行呢

**Comment by jzhang533** [comment]
用`pip install scikit-image --upgrade`命令，升级一下 scikit-image 看看。
