### ISSUE TITLE
服务端预测问题

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#1171]
使用paddle进行x86预测时候，同样大小的图片，前几次预测正常，后面就直接不能推理了，错误如图。看样子卷积出问题了，不过那个channel的维度是85，paddle的检测模型中会出现channel=85吗

**Comment by lgcy** [comment]
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/26407517/99066104-66f3f500-25e3-11eb-92c8-4abe66a7a526.png">

**Comment by LDOUBLEV** [comment]
是本来可以预测，多次预测就报错了吗？

**Comment by lgcy** [comment]
> 是本来可以预测，多次预测就报错了吗？

是的

**Comment by littletomatodonkey** [comment]
1. 预测的命令和运行的环境可以说明一下吗？（PAddle版本，python还是cpp，mkldnn等等）
2. 可以看下是否只有这张图会报错，单独预测这张图试下
