### ISSUE TITLE
安装 paddleocr，推荐使用2.6版本报错

### ISSUE THREAD

**Issue by meihuajunzhu** [PaddlePaddle/PaddleOCR#11713]
(D:\Cache\Anaconda\CondaEnvs\Paddle) C:\Users\35063>pip3 install "paddleocr>=2.6.0.3"
Collecting paddleocr>=2.6.0.3
  Using cached paddleocr-2.7.0.3-py3-none-any.whl.metadata (26 kB)
Collecting shapely (from paddleocr>=2.6.0.3)
  Using cached shapely-2.0.3-cp311-cp311-win_amd64.whl.metadata (7.2 kB)
Collecting scikit-image (from paddleocr>=2.6.0.3)
  Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting imgaug (from paddleocr>=2.6.0.3)
  Using cached imgaug-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting pyclipper (from paddleocr>=2.6.0.3)
  Using cached pyclipper-1.3.0.post5-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Collecting lmdb (from paddleocr>=2.6.0.3)
  Using cached lmdb-1.4.1-cp311-cp311-win_amd64.whl.metadata (1.2 kB)
Collecting tqdm (from paddleocr>=2.6.0.3)
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Collecting numpy (from paddleocr>=2.6.0.3)
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting visualdl (from paddleocr>=2.6.0.3)
  Using cached visualdl-2.5.3-py3-none-any.whl.metadata (25 kB)
Collecting rapidfuzz (from paddleocr>=2.6.0.3)
  Using cached rapidfuzz-3.6.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting opencv-python<=4.6.0.66 (from paddleocr>=2.6.0.3)
  Using cached opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl.metadata (18 kB)
Collecting opencv-contrib-python<=4.6.0.66 (from paddleocr>=2.6.0.3)
  Using cached opencv_contrib_python-4.6.0.66-cp36-abi3-win_amd64.whl.metadata (18 kB)
Collecting cython (from paddleocr>=2.6.0.3)
  Using cached Cython-3.0.9-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting lxml (from paddleocr>=2.6.0.3)
  Using cached lxml-5.1.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting premailer (from paddleocr>=2.6.0.3)
  Using cached premailer-3.10.0-py2.py3-none-any.whl.metadata (15 kB)
Collecting openpyxl (from paddleocr>=2.6.0.3)
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting attrdict (from paddleocr>=2.6.0.3)
  Using cached attrdict-2.0.1-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting PyMuPDF<1.21.0 (from paddleocr>=2.6.0.3)
  Using cached PyMuPDF-1.20.2.tar.gz (90.4 MB)
  Preparing metadata (setup.py) ... done
Collecting Pillow>=10.0.0 (from paddleocr>=2.6.0.3)
  Using cached pillow-10.2.0-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting pyyaml (from paddleocr>=2.6.0.3)
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting python-docx (from paddleocr>=2.6.0.3)
  Using cached python_docx-1.1.0-py3-none-any.whl.metadata (2.0 kB)
Collecting beautifulsoup4 (from paddleocr>=2.6.0.3)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.24.0 (from paddleocr>=2.6.0.3)
  Using cached fonttools-4.49.0-cp311-cp311-win_amd64.whl.metadata (162 kB)
Collecting fire>=0.3.0 (from paddleocr>=2.6.0.3)
  Using cached fire-0.6.0-py2.py3-none-any.whl
Collecting pdf2docx (from paddleocr>=2.6.0.3)
  Using cached pdf2docx-0.5.8-py3-none-any.whl.metadata (3.2 kB)
Collecting six (from fire>=0.3.0->paddleocr>=2.6.0.3)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting termcolor (from fire>=0.3.0->paddleocr>=2.6.0.3)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->paddleocr>=2.6.0.3)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting scipy (from imgaug->paddleocr>=2.6.0.3)
  Using cached scipy-1.12.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting matplotlib (from imgaug->paddleocr>=2.6.0.3)
  Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
Collecting imageio (from imgaug->paddleocr>=2.6.0.3)
  Using cached imageio-2.34.0-py3-none-any.whl.metadata (4.9 kB)
Collecting networkx>=2.8 (from scikit-image->paddleocr>=2.6.0.3)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->paddleocr>=2.6.0.3)
  Using cached tifffile-2024.2.12-py3-none-any.whl.metadata (31 kB)
Collecting packaging>=21 (from scikit-image->paddleocr>=2.6.0.3)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting lazy_loader>=0.3 (from scikit-image->paddleocr>=2.6.0.3)
  Using cached lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting et-xmlfile (from openpyxl->paddleocr>=2.6.0.3)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opencv-python-headless>=4.5 (from pdf2docx->paddleocr>=2.6.0.3)
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting typing-extensions (from python-docx->paddleocr>=2.6.0.3)
  Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
Collecting cssselect (from premailer->paddleocr>=2.6.0.3)
  Using cached cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting cssutils (from premailer->paddleocr>=2.6.0.3)
  Using cached cssutils-2.9.0-py3-none-any.whl.metadata (9.1 kB)
Collecting requests (from premailer->paddleocr>=2.6.0.3)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting cachetools (from premailer->paddleocr>=2.6.0.3)
  Using cached cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting colorama (from tqdm->paddleocr>=2.6.0.3)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting bce-python-sdk (from visualdl->paddleocr>=2.6.0.3)
  Using cached bce_python_sdk-0.9.5-py3-none-any.whl.metadata (318 bytes)
Collecting flask>=1.1.1 (from visualdl->paddleocr>=2.6.0.3)
  Using cached flask-3.0.2-py3-none-any.whl.metadata (3.6 kB)
Collecting Flask-Babel>=3.0.0 (from visualdl->paddleocr>=2.6.0.3)
  Using cached flask_babel-4.0.0-py3-none-any.whl.metadata (1.9 kB)
Collecting protobuf>=3.20.0 (from visualdl->paddleocr>=2.6.0.3)
  Using cached protobuf-4.25.3-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Collecting pandas (from visualdl->paddleocr>=2.6.0.3)
  Using cached pandas-2.2.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting rarfile (from visualdl->paddleocr>=2.6.0.3)
  Using cached rarfile-4.1-py3-none-any.whl.metadata (4.4 kB)
Collecting psutil (from visualdl->paddleocr>=2.6.0.3)
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting Werkzeug>=3.0.0 (from flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached werkzeug-3.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting Jinja2>=3.1.2 (from flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting itsdangerous>=2.1.2 (from flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached itsdangerous-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Collecting click>=8.1.3 (from flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached blinker-1.7.0-py3-none-any.whl.metadata (1.9 kB)
Collecting Babel>=2.12 (from Flask-Babel>=3.0.0->visualdl->paddleocr>=2.6.0.3)
  Using cached Babel-2.14.0-py3-none-any.whl.metadata (1.6 kB)
Collecting pytz>=2022.7 (from Flask-Babel>=3.0.0->visualdl->paddleocr>=2.6.0.3)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting pycryptodome>=3.8.0 (from bce-python-sdk->visualdl->paddleocr>=2.6.0.3)
  Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting future>=0.6.0 (from bce-python-sdk->visualdl->paddleocr>=2.6.0.3)
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting contourpy>=1.0.1 (from matplotlib->imgaug->paddleocr>=2.6.0.3)
  Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib->imgaug->paddleocr>=2.6.0.3)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->imgaug->paddleocr>=2.6.0.3)
  Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->imgaug->paddleocr>=2.6.0.3)
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib->imgaug->paddleocr>=2.6.0.3)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata>=2022.7 (from pandas->visualdl->paddleocr>=2.6.0.3)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset-normalizer<4,>=2 (from requests->premailer->paddleocr>=2.6.0.3)
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->premailer->paddleocr>=2.6.0.3)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->premailer->paddleocr>=2.6.0.3)
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->premailer->paddleocr>=2.6.0.3)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->flask>=1.1.1->visualdl->paddleocr>=2.6.0.3)
  Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Using cached paddleocr-2.7.0.3-py3-none-any.whl (465 kB)
Using cached fonttools-4.49.0-cp311-cp311-win_amd64.whl (2.2 MB)
Using cached opencv_contrib_python-4.6.0.66-cp36-abi3-win_amd64.whl (42.5 MB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Using cached opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
Using cached pillow-10.2.0-cp311-cp311-win_amd64.whl (2.6 MB)
Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached Cython-3.0.9-cp311-cp311-win_amd64.whl (2.8 MB)
Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl (24.5 MB)
Using cached lmdb-1.4.1-cp311-cp311-win_amd64.whl (100 kB)
Using cached lxml-5.1.0-cp311-cp311-win_amd64.whl (3.9 MB)
Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Using cached pdf2docx-0.5.8-py3-none-any.whl (132 kB)
Using cached python_docx-1.1.0-py3-none-any.whl (239 kB)
Using cached premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Using cached pyclipper-1.3.0.post5-cp311-cp311-win_amd64.whl (108 kB)
Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Using cached rapidfuzz-3.6.2-cp311-cp311-win_amd64.whl (1.6 MB)
Using cached shapely-2.0.3-cp311-cp311-win_amd64.whl (1.4 MB)
Using cached tqdm-4.66.2-py3-none-any.whl (78 kB)
Using cached visualdl-2.5.3-py3-none-any.whl (6.3 MB)
Using cached flask-3.0.2-py3-none-any.whl (101 kB)
Using cached flask_babel-4.0.0-py3-none-any.whl (9.6 kB)
Using cached imageio-2.34.0-py3-none-any.whl (313 kB)
Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Using cached protobuf-4.25.3-cp310-abi3-win_amd64.whl (413 kB)
Using cached scipy-1.12.0-cp311-cp311-win_amd64.whl (46.2 MB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached tifffile-2024.2.12-py3-none-any.whl (224 kB)
Using cached bce_python_sdk-0.9.5-py3-none-any.whl (329 kB)
Using cached cachetools-5.3.3-py3-none-any.whl (9.3 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Using cached cssutils-2.9.0-py3-none-any.whl (398 kB)
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl (7.6 MB)
Using cached pandas-2.2.1-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
Using cached rarfile-4.1-py3-none-any.whl (28 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Using cached Babel-2.14.0-py3-none-any.whl (11.0 MB)
Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl (187 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached future-1.0.0-py3-none-any.whl (491 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl (56 kB)
Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl (1.8 MB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Using cached werkzeug-3.0.1-py3-none-any.whl (226 kB)
Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl (17 kB)
Building wheels for collected packages: PyMuPDF
  Building wheel for PyMuPDF (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      PyMuPDF/setup.py: sys.argv: ['C:\\Users\\35063\\AppData\\Local\\Temp\\pip-install-zbrkm6v5\\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\\setup.py', 'bdist_wheel', '-d', 'C:\\Users\\35063\\AppData\\Local\\Temp\\pip-wheel-et9j5_nk']
      PyMuPDF/setup.py: os.getcwd(): C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc
      PyMuPDF/setup.py: __file__: C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\setup.py
      PyMuPDF/setup.py: $PYTHON_ARCH: None
      PyMuPDF/setup.py: os.environ (58):
      PyMuPDF/setup.py:     ALLUSERSPROFILE: C:\ProgramData
      PyMuPDF/setup.py:     APPDATA: C:\Users\35063\AppData\Roaming
      PyMuPDF/setup.py:     COMMONPROGRAMFILES: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMW6432: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMPUTERNAME: FUSHENGWUYIN
      PyMuPDF/setup.py:     COMSPEC: C:\Windows\system32\cmd.exe
      PyMuPDF/setup.py:     CONDA_DEFAULT_ENV: D:\Cache\Anaconda\CondaEnvs\Paddle
      PyMuPDF/setup.py:     CONDA_EXE: D:\program\anaconda3\Scripts\conda.exe
      PyMuPDF/setup.py:     CONDA_EXES: "D:\program\anaconda3\condabin\..\Scripts\conda.exe"
      PyMuPDF/setup.py:     CONDA_PREFIX: D:\Cache\Anaconda\CondaEnvs\Paddle
      PyMuPDF/setup.py:     CONDA_PREFIX_1: D:\program\anaconda3
      PyMuPDF/setup.py:     CONDA_PROMPT_MODIFIER: (D:\Cache\Anaconda\CondaEnvs\Paddle)
      PyMuPDF/setup.py:     CONDA_PYTHON_EXE: D:\program\anaconda3\python.exe
      PyMuPDF/setup.py:     CONDA_SHLVL: 2
      PyMuPDF/setup.py:     DRIVERDATA: C:\Windows\System32\Drivers\DriverData
      PyMuPDF/setup.py:     ES_JAVA_HOME: D:\services\datebase\elasticsearch-8.12.2\jdk
      PyMuPDF/setup.py:     FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
      PyMuPDF/setup.py:     FPS_BROWSER_USER_PROFILE_STRING: Default
      PyMuPDF/setup.py:     HOMEDRIVE: C:
      PyMuPDF/setup.py:     HOMEPATH: \Users\35063
      PyMuPDF/setup.py:     JAVA_HOME: D:\services\datebase\elasticsearch-8.12.2\jdk
      PyMuPDF/setup.py:     LOCALAPPDATA: C:\Users\35063\AppData\Local
      PyMuPDF/setup.py:     LOGONSERVER: \\FUSHENGWUYIN
      PyMuPDF/setup.py:     MAVEN_HOME: D:\services\Maven\maven39
      PyMuPDF/setup.py:     NODE_PATH: NODE_PATH    D:\services\NodeJs\node20\info\node_global\node_modules
      PyMuPDF/setup.py:     NUMBER_OF_PROCESSORS: 8
      PyMuPDF/setup.py:     OLLAMA_MODELS: D:\Cache\Ollama\models
      PyMuPDF/setup.py:     ONEDRIVE: C:\Users\35063\OneDrive
      PyMuPDF/setup.py:     OS: Windows_NT
      PyMuPDF/setup.py:     PATH: D:\Cache\Anaconda\CondaEnvs\Paddle;D:\Cache\Anaconda\CondaEnvs\Paddle\Library\mingw-w64\bin;D:\Cache\Anaconda\CondaEnvs\Paddle\Library\usr\bin;D:\Cache\Anaconda\CondaEnvs\Paddle\Library\bin;D:\Cache\Anaconda\CondaEnvs\Paddle\Scripts;D:\Cache\Anaconda\CondaEnvs\Paddle\bin;D:\program\anaconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;D:\program\anaconda3;D:\program\anaconda3\Scripts;D:\program\anaconda3\Library\bin;D:\program\anaconda3\Library\usr\bin;D:\program\anaconda3\Library\mingw-w64\bin;D:\services\datebase\elasticsearch-8.12.2\jdk\bin;D:\services\Maven\maven39\bin;D:\services\NodeJs\node20;D:\services\Git\cmd;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\dotnet;D:\services\poppler-24.02.0\Library\bin;D:\services\tesOCR;D:\services\cmake-3.29.0-rc3-windows-x86_64\bin;C:\Users\35063\AppData\Local\Microsoft\WindowsApps;C:\Users\35063\AppData\Local\Programs\Ollama;D:\program\Microsoft VS Code\bin;D:\services\NodeJs\node20\info\node_global;C:\Users\35063\.dotnet\tools;D:\services\poppler-24.02.0\Library\bin;.
      PyMuPDF/setup.py:     PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
      PyMuPDF/setup.py:     PIP_BUILD_TRACKER: C:\Users\35063\AppData\Local\Temp\pip-build-tracker-c6beq7qz
      PyMuPDF/setup.py:     PROCESSOR_ARCHITECTURE: AMD64
      PyMuPDF/setup.py:     PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
      PyMuPDF/setup.py:     PROCESSOR_LEVEL: 6
      PyMuPDF/setup.py:     PROCESSOR_REVISION: 8e0a
      PyMuPDF/setup.py:     PROGRAMDATA: C:\ProgramData
      PyMuPDF/setup.py:     PROGRAMFILES: C:\Program Files
      PyMuPDF/setup.py:     PROGRAMFILES(X86): C:\Program Files (x86)
      PyMuPDF/setup.py:     PROGRAMW6432: C:\Program Files
      PyMuPDF/setup.py:     PROMPT: (D:\Cache\Anaconda\CondaEnvs\Paddle) $P$G
      PyMuPDF/setup.py:     PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
      PyMuPDF/setup.py:     PUBLIC: C:\Users\Public
      PyMuPDF/setup.py:     SESSIONNAME: Console
      PyMuPDF/setup.py:     SSL_CERT_FILE: D:\program\anaconda3\Library\ssl\cacert.pem
      PyMuPDF/setup.py:     SYSTEMDRIVE: C:
      PyMuPDF/setup.py:     SYSTEMROOT: C:\Windows
      PyMuPDF/setup.py:     TEMP: C:\Users\35063\AppData\Local\Temp
      PyMuPDF/setup.py:     TESSDATA_PREFIX: D:\services\tesOCR\tessdata
      PyMuPDF/setup.py:     TMP: C:\Users\35063\AppData\Local\Temp
      PyMuPDF/setup.py:     USERDOMAIN: FUSHENGWUYIN
      PyMuPDF/setup.py:     USERDOMAIN_ROAMINGPROFILE: FUSHENGWUYIN
      PyMuPDF/setup.py:     USERNAME: 35063
      PyMuPDF/setup.py:     USERPROFILE: C:\Users\35063
      PyMuPDF/setup.py:     WINDIR: C:\Windows
      PyMuPDF/setup.py:     ZES_ENABLE_SYSMAN: 1
      PyMuPDF/setup.py:     __CONDA_OPENSLL_CERT_FILE_SET: "1"
      PyMuPDF/setup.py: mupdf_tgz already exists: C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\mupdf.tgz
      PyMuPDF/setup.py: Extracting C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\mupdf.tgz
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\setup.py", line 487, in <module>
          mupdf_local = get_mupdf()
                        ^^^^^^^^^^^
        File "C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\setup.py", line 450, in get_mupdf
          return tar_extract( mupdf_tgz, exists='return')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\35063\AppData\Local\Temp\pip-install-zbrkm6v5\pymupdf_7cd78ff68dbb4657bf79e39c157b27fc\setup.py", line 183, in tar_extract
          t.extractall()
        File "D:\Cache\Anaconda\CondaEnvs\Paddle\Lib\tarfile.py", line 2265, in extractall
          self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
        File "D:\Cache\Anaconda\CondaEnvs\Paddle\Lib\tarfile.py", line 2332, in _extract_one
          self._handle_fatal_error(e)
        File "D:\Cache\Anaconda\CondaEnvs\Paddle\Lib\tarfile.py", line 2328, in _extract_one
          self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
        File "D:\Cache\Anaconda\CondaEnvs\Paddle\Lib\tarfile.py", line 2411, in _extract_member
          self.makefile(tarinfo, targetpath)
        File "D:\Cache\Anaconda\CondaEnvs\Paddle\Lib\tarfile.py", line 2457, in makefile
          with bltn_open(targetpath, "wb") as target:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '.\\mupdf-1.20.3-source\\thirdparty\\harfbuzz\\test\\shaping\\texts\\in-house\\shaper-indic\\script-devanagari\\utrrs\\codepoint\\IndicFontFeatureCodepoint-AdditionalConsonants.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyMuPDF
  Running setup.py clean for PyMuPDF
Failed to build PyMuPDF
ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects

(D:\Cache\Anaconda\CondaEnvs\Paddle) C:\Users\35063>

**Comment by jzhang533** [comment]
这是安装 PyMuPDF 的错误。
因为 PyMuPDF 没有你的环境下对应的预编译的安装包，所以在你机器上，需要从源码编译 PyMuPDF，这个阶段出现了错误。
有两个办法可以解决：

- 本地配置好环境，解决 PyMuPDF 的编译问题。
或者：
- 用`pip install --no-deps paddleocr`，仅安装paddleocr，不安装其依赖；然后用`pip check`检查还有哪些依赖包没安装，安装上除了 PyMuPDF 外的所有的依赖包。这种方式下，paddleocr 的绝大部分功能是可用的。

BTW：最新的 paddleocr 已经将 PyMuPDF 变更为了可选安装。

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
