### ISSUE TITLE
请问paddleocr里卖弄rec模型输出的置信度能不能把每个字符的置信度分别输出来？目前是整体的

### ISSUE THREAD

**Issue by ctgushiwei** [PaddlePaddle/PaddleOCR#11717]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by zhaojun060708** [comment]
#9381

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
