### ISSUE TITLE
python推理ch_PP-OCRv4_server_rec显存突然升高导致out of memory，调小batchsize问题依然存在

### ISSUE THREAD

**Issue by hideinhat** [PaddlePaddle/PaddleOCR#11712]
使用gunicorn多进程python推理ch_PP-OCRv4_server_rec识别模型时，显存会突然升高2倍多导致显存溢出。
之后调小推理batchsize，问题依然存在。
之前部署的是paddle2.6下的ch_ppocr_server_v2.0_rec并没有发生显存溢出的情况。
请问有好的解决办法吗？

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04
- 版本号/Version：Paddle：paddlepaddle-gpu        2.2.1.post112  
- PaddleOCR：2.7.1 
- 完整报错/Complete Error Message：
Out of memory error on GPU 0. Cannot allocate 3.743348GB memory on GPU 0, 23.677490GB memory has been allocated and available memory is only 22.562500MB.
请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by TingquanGao** [comment]
有报错信息么？可以贴一下。另外，Paddle版本建议更新到2.5.2、2.6.0及以上

**Comment by hideinhat** [comment]
> 有报错信息么？可以贴一下。另外，Paddle版本建议更新到2.5.2、2.6.0及以上
报错信息如下：
```
Traceback (most recent call last):
  File "/data/workspace/ocr/ocr.py", line 150, in ocr
    rec_list, elapse = textRecognizer(img_list)
  File "/data/workspace/CgOCR/cg_ocr/tools/infer/predict_rec.py", line 616, in __call__
    self.predictor.run()
RuntimeError: ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 3.743348GB memory on GPU 0, 23.677490GB memory has been allocated and available memory is only 22.562500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
```
目前每块GPU挂1个进程，暂没有出现报错。（之前每个GPU挂2个进程）。后续会更新下Paddle版本。

**Comment by TingquanGao** [comment]
好的，那么该问题先close了，如有其他问题，可reopen或新开issue。

**Comment by nissansz** [comment]
> > 有报错信息么？可以贴一下。另外，Paddle版本建议更新到2.5.2、2.6.0及以上
> > 报错信息如下：
> 
> ```
> Traceback (most recent call last):
>   File "/data/workspace/ocr/ocr.py", line 150, in ocr
>     rec_list, elapse = textRecognizer(img_list)
>   File "/data/workspace/CgOCR/cg_ocr/tools/infer/predict_rec.py", line 616, in __call__
>     self.predictor.run()
> RuntimeError: ResourceExhaustedError:
> 
> Out of memory error on GPU 0. Cannot allocate 3.743348GB memory on GPU 0, 23.677490GB memory has been allocated and available memory is only 22.562500MB.
> 
> Please check whether there is any other process using GPU 0.
> 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> 2. If no, please decrease the batch size of your model.
> 
>  (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
> ```
> 
> 目前每块GPU挂1个进程，暂没有出现报错。（之前每个GPU挂2个进程）。后续会更新下Paddle版本。

怎么看gpu挂了几个进程？
要安装哪个版本的paddlepaddle?
