### ISSUE TITLE
Create new function in PPOCRLabel.py : click to create bounding box 

### ISSUE THREAD

**Issue by PxCPeter** [PaddlePaddle/PaddleOCR#11729]
Hi team, I am trying to create a new function when using PPOCRLabel.py
When I click on the img it will create a box has specific size. I found in the canvas.py line 252 has method mousePressEvent. The comment lines mean that I try to create box with coordinate of box_click varriabel. I want a bounding box was created when click in img BUT DON'T IN  `if self.current:`   I meet 3 problem:
1. when is the exactly if `self.drawing()` was active ? I was tried and seen that it will active when use "Create RectBox" or "Create PolygonBox".
2. Can I use box_click varriabel as fourpoint ? they request 4 points coordinate, too 
3. This function should put in ` elif not self.outOfPixmap(pos):` or `else: group_mode = int(ev.modifiers()) == Qt.ControlModifier`. When in `if self.drawing():` I don't know how to  access `elif not self.outOfPixmap(pos):`

`def mousePressEvent(self, ev):

    pos = self.transformPos(ev.pos())
    if ev.button() == Qt.LeftButton:
        if self.drawing():
            # self.handleDrawing(pos) # OLD
            if self.current:
                if self.fourpoint: # ADD IF
                    # Add point to existing shape.
                    # print('Adding points in mousePressEvent is ', self.line[1])
                    self.current.addPoint(self.line[1])
                    self.line[0] = self.current[-1]
                    if self.current.isClosed():
                        # print('1111')
                        self.finalise()
                elif self.drawSquare:
                    assert len(self.current.points) == 1
                    self.current.points = self.line.points
                    # print(self.current.points)
                    # print('square')                        
                    self.finalise()
            elif not self.outOfPixmap(pos):
                # Create new shape.
                self.current = Shape()
                self.current.addPoint(pos)
                self.line.points = [pos, pos]
                self.setHiding()
                self.drawingPolygon.emit(True)
                self.update()
                # threshold = 96 ### find in statistic.ipynb
                # h, w = self.pixmap.size().height(), self.pixmap.size().width()
                # box_click = [[0,int(pos.y()) - threshold],
                #             [self.pixmap.size().width(),int(pos.y()) - threshold],
                #             [self.pixmap.size().width(),int(pos.y()) + threshold],
                #             [0,int(pos.y()) + threshold]]
                # for p in box_click:
                #     self.current.addPoint(p)
                #     print(self.current)
        else:
            group_mode = int(ev.modifiers()) == Qt.ControlModifier
            self.selectShapePoint(pos, multiple_selection_mode=group_mode)
            self.prevPoint = pos
            self.pan_initial_pos = pos
            # print('1234')
            # print(int(pos.y()))
            # print(self.pixmap.size().height())
            # print(box_click)
    elif ev.button() == Qt.RightButton and self.editing():
        group_mode = int(ev.modifiers()) == Qt.ControlModifier
        self.selectShapePoint(pos, multiple_selection_mode=group_mode)
        self.prevPoint = pos
        # print('test') 
    self.update()`

**Comment by SWHL** [comment]
Since PPOCRLabel has moved, please go to [PPOCRLabel](https://github.com/PFCCLab/PPOCRLabel) to ask questions if you have any questions!
This issue has been closed first.
