### ISSUE TITLE
表格转换出错

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#11724]
系统环境/System Environment：ubantu 20
- 版本号/Version：Paddle：  PaddleOCR： 2.4

当单元是同时跨行和跨列时转换会有问题，比如当单元格是 <td colspan=\"5 rowspan=4\">

            excel = xlrd.open_workbook(csv_path)
            sheet0 = excel.sheet_by_index(0)  # only sheet 0
            merged_cells = sheet0.merged_cells
            html_list = [['td'] * sheet0.ncols for i in range(sheet0.nrows)]
            for merged in merged_cells:
                html_list = expand_list(merged, html_list)

            token_list = convert_token(html_list)
通过以下函数转之后，都拆开了，convert_token 没有正确处理colspan和rowspan同时存在的情况

                     def convert_token(html_list):
                            token_list = ["<tbody>"]
                            # final html list:
                            for row in html_list:
                                token_list.append("<tr>")
                                for col in row:
                                    if col == None:
                                        continue
                                    elif col == 'td':
                                        token_list.extend(["<td>", "</td>"])
                                    else:
                                        token_list.append("<td")
                                        if 'colspan' in col:
                                            _, n = col.split('colspan=')
                                            token_list.append(" colspan=\"{}\"".format(n[0]))
                                        if 'rowspan' in col:
                                            _, n = col.split('rowspan=')
                                            token_list.append(" rowspan=\"{}\"".format(n[0]))
                                        token_list.extend([">", "</td>"])
                                token_list.append("</tr>")
                            token_list.append("</tbody>")
                        
                            return token_list

**Comment by TingquanGao** [comment]
目前表格识别模型对跨行、跨列识别精度较低，我们也在努力优化

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
