### ISSUE TITLE
PP-OCRv4“离线版”和“在线体验版”识别效果不一致，会丢行

### ISSUE THREAD

**Issue by charliedream1** [PaddlePaddle/PaddleOCR#11720]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.0
- 版本号/Version：Paddle： 2.7 PaddleOCR： 问题相关组件/Related components：det
- 运行指令/Command Code：
  ```python
      from paddleocr import PaddleOCR, draw_ocr
    
    # Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
    # 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
    ocr = PaddleOCR(use_angle_cls=True, lang="ch", page_num=2)  # need to run only once to download and load model into memory
    img_path = './xxx.pdf'
    result = ocr.ocr(img_path, cls=True)
    for idx in range(len(result)):
        res = result[idx]
        for line in res:
            print(line)
  ```
- 完整报错/Complete Error Message：
  
![pdf-0 png ocr](https://github.com/PaddlePaddle/PaddleOCR/assets/15007828/024ef671-8abd-4891-a111-740e236765e1)

  OCR输出文本结果会丢失如下图片的第一行，但是在线体验版本没有这个问题。

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by JeremyGe07** [comment]
use_angle_cls=False试试。

**Comment by charliedream1** [comment]
试了下可以了，换server版发现也可以，或者放在a4纸中也可以。


另外，问下，模型对输入图片的尺寸和分辨率有什么要求？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月14日(周四) 下午5:29
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PP-OCRv4“离线版”和“在线体验版”识别效果不一致，会丢行 (Issue #11720)




 
use_angle_cls=False试试。

**Comment by charliedream1** [comment]
为什么方向识别模型会导致出错丢行？

**Comment by TingquanGao** [comment]
use_angle_cls=True的话，会使用文本行方向分类模型，主要用于解决存在文字倒置的场景，一般情况无需使用。

PP-OCRv4对输入图像的尺寸和分辨率没有特定要求，通常人眼可识别的情况即可。

**Comment by charliedream1** [comment]
谢谢



---原始邮件---
发件人: "Tingquan ***@***.***&gt;
发送时间: 2024年3月21日(周四) 下午2:18
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PP-OCRv4“离线版”和“在线体验版”识别效果不一致，会丢行 (Issue #11720)




 
use_angle_cls=True的话，会使用文本行方向分类模型，主要用于解决存在文字倒置的场景，一般情况无需使用。
 
PP-OCRv4对输入图像的尺寸和分辨率没有特定要求，通常人眼可识别的情况即可。

**Comment by TingquanGao** [comment]
那么就先close了，如有其他问题，可reopen或新开issue。
