### ISSUE TITLE
增值税专用发票识别，识别的图片中有一些干扰因素。比如桌面、下一张增值税边缘。准确率就很低

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#11739]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
 ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
增值税专用发票识别，识别的图片中有一些干扰因素。比如桌面、下一张增值税发票的边缘等，有这些因素识别的准确率就大大降低，如果只截取发票真正的区域去识别，准确率就高。该如何处理呢？版面分析？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/9adc23bf-524f-4479-8638-e3004455f78e)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/854db773-adf4-4584-937a-ce7639a01563)

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by cuicheng01** [comment]
这个问题比较奇怪，方便把图片和预测命令发出来我们定位下吗？

**Comment by rexzhengzhihong** [comment]
> 这个问题比较奇怪，方便把图片和预测命令发出来我们定位下吗？
预测命令。det模型和ser模型是我自己训练的
```
python3 predict_kie_token_ser.py                     
--kie_algorithm=LayoutXLM                     
--ser_model_dir=/home/DiskA/zncsPython/picture_ocr/zzsfp_v1/model/ser/inference/ser_vi_layoutxlm_inference                     
--image_dir=/home/DiskA/zncsPython/picture_ocr/allbill_v1/test/增值税专用发票v2                     
--ser_dict_path=/home/DiskA/zncsPython/picture_ocr/zzsfp_v1/train_data/class_list.txt                     
--vis_font_path=../doc/fonts/simfang.ttf                     
--ocr_order_method="tb-yx"                    
 --output=/home/DiskA/zncsPython/picture_ocr/allbill_v1/test/增值税专用发票v2/result/                     
--det_limit_side_len=736                     
--det_limit_type="min"                     
--rec_model_dir=/home/DiskA/zncsPython/picture_ocr/zzsfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer                    
 --det_model_dir=/home/DiskA/zncsPython/picture_ocr/zzsfp_v1/model/det/inference/det_db_dml_inference/Student 

```

两个图片是在同一个文件夹，同一个命令
![zzszyfp_v2-02](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/76705d8e-c2f4-464c-931c-71cb069bb596)
![02](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/0eb34247-b8b9-4a96-b315-a07ccbd4b861)

**Comment by rexzhengzhihong** [comment]
图2是我从图1中截出来的票据部分。识别效果就还可以

**Comment by cuicheng01** [comment]
收到，我们看看

**Comment by rexzhengzhihong** [comment]
> 收到，我们看看

感谢。搞了好几天了没搞定。需要什么资料我配合你们

**Comment by rexzhengzhihong** [comment]
@cuicheng01 有查到什么原因吗

**Comment by rexzhengzhihong** [comment]
可能是因为图片较大，所以我在预测参数中修改将
```
det_limit_side_len=736.0,
det_limit_type='min',
```
改成
```
det_limit_side_len=960.0,
det_limit_type='max',
```
就行。但是又出现一个问题。如果传入的图片像素比较小。只有693*365。预测也就不准了。这种怎么处理？
           
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/9adcc2d0-0d50-42fd-b254-5d00c38d6eaa)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/a8892439-fd63-4189-b200-c7e440359f8b)
![zzszyfp_7](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/392e9178-952d-4406-8835-114670d07e75)

**Comment by UserWangZz** [comment]
输入图像的大小会很大程度上影响检测模型的性能，从而影响后续任务的精度。所以需要从中进行取舍
