### ISSUE TITLE
ppyolov2_r50vd_dcn_365e_tableBank_word模型相关疑问

### ISSUE THREAD

**Issue by woodenwatcher** [PaddlePaddle/PaddleOCR#11738]
我这边的需求是想把该模型用TVM进行编译，但是报不支持conditional_block和select_input算子，请问有办法规避这两个控制流类似的算子吗？该模型有没有不依赖控制流算子的版本呢？从 https://github.com/PaddlePaddle/Paddle/issues/33202 这个issue上看ppyolov2模型是可以不保存控制流算子的。

**Comment by tink2123** [comment]
能否尝试 https://github.com/PaddlePaddle/Paddle/issues/33202 中的方法，使用release/2.1分支导出呢？

**Comment by woodenwatcher** [comment]
但这个模型是在PaddleOCR中提供下载的，在PaddleDetection中找不到这个模型啊

**Comment by tink2123** [comment]
抱歉，确认了一下，这个模型的训练权重已经不存在了，不能支持重新导出的操作。如有需要可以使用 PaddleDetection 重新训练，训练数据可在官网获取：https://doc-analysis.github.io/tablebank-page/index.html
