### ISSUE TITLE
关于ocr检测结果不准确的问题

### ISSUE THREAD

**Issue by Felix0525** [PaddlePaddle/PaddleOCR#11735]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.7，V4版本
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.
<img width="331" alt="屏幕截图 2024-03-14 110728" src="https://github.com/PaddlePaddle/PaddleOCR/assets/19362045/907395d8-f420-4bf4-8268-c437c08f5f14">

如上图，使用以下参数，漏了不少检测文字，求助如何更改参数才能识别。
det_model_dir='/data/models/OcrModel/ch_PP-OCRv4_det_server_infer',
                           rec_model_dir='/data/models/OcrModel/ch_PP-OCRv4_rec_server_infer',
                           use_angle_cls=False,
                           det_db_score_mode='slow',
                           det_db_unclip_ratio=2.0,
                           det_db_thresh=0.1,
                           det_db_box_thresh=0.1,
                           det_limit_side_len=1500

**Comment by tink2123** [comment]
请问上面是完整的预测图片吗？ 如果是的话输入图过窄会影响检测模型的效果，可以尝试对周围边做padding。 如果不是的话可以提供原图我们测试看看。
