### ISSUE TITLE
Could CPPD pretrained model use AMP ?

### ISSUE THREAD

**Issue by reeered** [PaddlePaddle/PaddleOCR#11734]
I try using amp in CPPD config to train with only 16G GPU memory. However, I got an error below:
W0313 20:56:07.117985  1579 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed.
W0313 20:56:07.118566  1579 multiply_fwd_func.cc:64] got different data type, run type protmotion automatically, this may cause data type been changed.

I just add several lines in config file:
Global:
  use_amp=True
  scale_loss=1024.0
  use_dynamic_loss_scaling=True
  Global.amp_level=O2
@Topdu

**Comment by Topdu** [comment]
Modify the corresponding section of `rec_cppd_head.py` as follows:

```python
        pos_node_feats = self.edge_decoder(pos_node_query, char_vis_feats,
                                           char_vis_feats)  # B, 26, dim
        edge_feats = self.edge_fc(pos_node_feats)  # B, 26, 37
        return [node_feats, edge_feats] # node_feats, edge_feats
```

Modify `CPPDLabelDecode` in the `rec_postprocess.py` as follows:

`if isinstance(preds, tuple):` to `if isinstance(preds, list):`

**Comment by reeered** [comment]
> Modify the corresponding section of `rec_cppd_head.py` as follows:
> 
> ```python
>         pos_node_feats = self.edge_decoder(pos_node_query, char_vis_feats,
>                                            char_vis_feats)  # B, 26, dim
>         edge_feats = self.edge_fc(pos_node_feats)  # B, 26, 37
>         return [node_feats, edge_feats] # node_feats, edge_feats
> ```
> 
> Modify `CPPDLabelDecode` in the `rec_postprocess.py` as follows:
> 
> `if isinstance(preds, tuple):` to `if isinstance(preds, list):`

Thanks for your help!!!
