### ISSUE TITLE
cmakelist.txt 214 line,error: external-cmake/auto-log.cmake:13 (FetchContent_MakeAvailable).how to resolve this

### ISSUE THREAD

**Issue by luluailinlin** [PaddlePaddle/PaddleOCR#11737]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by cuicheng01** [comment]
same question，closed
