### ISSUE TITLE
使用paddlepaddle-gpu 2.6.0.post116训练paddleocrv2.7.1识别模型, paddle_lite_opt转换为nb模型报错 No attributes called beta found for swish

### ISSUE THREAD

**Issue by equalman** [PaddlePaddle/PaddleOCR#11732]
版本、环境信息：
1）paddlepaddle-gpu 版本:2.6.0.post116
paddlelite 版本 当前develop分支8795a4d3d v2.13rc v2.10
paddleocr版本 v2.7.1
2）Host 环境：x86_64 Ubuntu 20.04
3）运行设备环境：x86_64 Ubuntu 20.04转换为nb模型 rk3568运行
复现信息：
1、python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml 训练模型
[ch_PP-OCRv3_rec_distillation.zip](https://github.com/PaddlePaddle/Paddle/files/14585310/ch_PP-OCRv3_rec_distillation.zip)
python tools/export_model.py -c "inference_model/ch_PP-OCRv3_rec_distillation/ch_PP-OCRv3_rec_distillation.yml" -o Global.pretrained_model="inference_model/ch_PP-OCRv3_rec_distillation/best_accuracy.pdparams" Global.save_inference_dir="inference_model/ch_PP-OCRv3_rec_distillation/new" Global.checkpoints=""
2、python 3.8.10 安装paddlelite v2.10 或者v2.13rc 或者编译paddlelite源码生成whl安装
3、paddle_lite_opt --model_file=inference.pdmodel --param_file=inference.pdiparams --optimize_out=./inference_vdevelop --valid_targets=arm --optimize_out_type=naive_buffer
问题描述：
paddelite develop分支如下结果
Loading topology data from inference.pdmodel
Loading params data from inference.pdiparams

Model is successfully loaded!
[F 3/13 17: 2:13.321 ...e-Lite/lite/core/model/general/op_desc.h:118 GetAttr] Check failed: it != attrs().end(): No attributes called beta found for swish
[F 3/13 17: 2:13.321 ...e-Lite/lite/core/model/general/op_desc.h:118 GetAttr] Check failed: it != attrs().end(): No attributes called beta found for swish
Traceback (most recent call last):
File "/usr/local/bin/paddle_lite_opt", line 142, in
main()
File "/usr/local/bin/paddle_lite_opt", line 139, in main
a.run()
RuntimeError: Paddle-Lite C++ Exception:
[F 3/13 17: 2:13.321 ...e-Lite/lite/core/model/general/op_desc.h:118 GetAttr] Check failed: it != attrs().end(): No attributes called beta found for swish
其他paddlelite版本也是类似错误
下载官方模型https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar 转换nb模型没问题,
根据报错信息 swish激活函数在官方模型中有beta属性, 但是自己训练的模型中没有这个属性, 如下使用netron软件查看的结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/10279015/db614deb-42fe-4d0a-bd08-9613b0b95a24)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/10279015/b725d88d-af50-48df-8b65-50c4954e6cc8)
现在问题是为何自己训练模型中swish激活函数没有beta属性, 怎么才能给它加上, 是否历史的paddlepaddle版本swish激活函数有beta属性?

**Comment by equalman** [comment]
应该是自训练模型中由paddle.nn.Swish模块生成的模型节点没有beta属性, 这个是与paddlepaddle版本有关吧? 或者某种配置影响了这个beta属性?

**Comment by equalman** [comment]
@changdazhou  你好  这个问题怎么处理?

**Comment by changdazhou** [comment]
建议更换2.5.0版本的PaddlePaddle尝试下呢

**Comment by equalman** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by equalman** [comment]
> 建议更换2.5.0版本的PaddlePaddle尝试下呢

好的,  这个我看别人也遇到过类似的

**Comment by renshujiajia** [comment]
> > 建议更换2.5.0版本的PaddlePaddle尝试下呢
> 
> 好的, 这个我看别人也遇到过类似的

哥，解决了没，这里建议的更换2.5.0有效果不

**Comment by changdazhou** [comment]
paddle-lite对OCR部分模型会有一些不适配哈，我们正在计划支持

**Comment by equalman** [comment]
> paddle-lite对OCR部分模型会有一些不适配哈，我们正在计划支持

你好, 现在这个是个什么进度?

**Comment by changdazhou** [comment]
这个进度我们不太清楚，建议到paddle-lite下开个issue哈

**Comment by equalman** [comment]
> > > 建议更换2.5.0版本的PaddlePaddle尝试下呢
> > 
> > 
> > 好的, 这个我看别人也遇到过类似的
> 
> 哥，解决了没，这里建议的更换2.5.0有效果不

有效果的, paddlepaddle-gpu 2.5.0 2.5.2都能转换为nb模型
