### ISSUE TITLE
1.报GPU内存不足但查看占用有足够的 2.只能单GPU运行

### ISSUE THREAD

**Issue by guodastanson** [PaddlePaddle/PaddleOCR#11746]
**1.使用langchain-chat自带的rapidOCRPdfLoader解析PDF，引入paddle-gpu进行处理。在GPU 内存占用6G/24G的时候，它就经常告诉我内存不足，比如说需要分配7G但是只剩1G。**
 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26060938/ced6206d-95b7-46cc-a9fa-68c521584343)
（如图所示）
  **2.安装了nccl之后测试paddle.utils.run_check()，通过交互模式输入代码，显示两个GPU正常，但是通过脚本模式执行同样的代码会报错**
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26060938/6e840437-75ed-49c3-a5bb-dc1dbeba8ae0)
(上图为交互模式)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26060938/4aee0672-9b3e-403e-ba9e-53b2dbf5771a)
(上图为脚本模式)

**Comment by changdazhou** [comment]
建议尝试使用官方docker尝试一下哈，感觉是环境问题哈

**Comment by UserWangZz** [comment]
第一个报错是要分配6G显存，但是23.5G已经分配可用显存只有135mb
