### ISSUE TITLE
ppocrv3中有没有KL div loss？

### ISSUE THREAD

**Issue by tammy-na** [PaddlePaddle/PaddleOCR#11744]
[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7)/[doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/doc)/[doc_ch](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/doc/doc_ch)
/PP-OCRv3_introduction.md这个文件中对于PPOCRV3的改进检测优化CML训练框架图与PPOCRV4一样，且ppocrv4里提到的改进CML：添加Student和Teacher网络输出的KL div loss，那么ppocrv3中有没有KL div loss呢？PP-OCRv3_introduction.md文件中的图是否引用错误？

**Comment by changdazhou** [comment]
v3里有的哈，只是v4的描述不太准确，是在两个额外的分支计算了KL div loss
