### ISSUE TITLE
进行KIE中的SER训练时，遇到报错TypeError: __init__() got an unexpected keyword argument 'num_classes'

### ISSUE THREAD

**Issue by SwordyLee** [PaddlePaddle/PaddleOCR#11748]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
开始训练ser模型时报错，求佬帮忙看看
- 系统环境/System Environment：Ubuntu 18.04.6
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddlepaddle-gpu 2.6.0 
- paddlenlp 2.7.2
- 运行指令/Command Code：
-  python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 完整报错/Complete Error Message：
[2024-03-15 14:29:18,116] [    INFO] - Already cached /home/lzx/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2024-03-15 14:29:18,116] [    INFO] - Loading weights file model_state.pdparams from cache at /home/lzx/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2024-03-15 14:29:19,532] [    INFO] - Loaded weights file from disk, setting weights to model.
W0315 14:29:19.539008  7370 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 6.1, Driver API Version: 12.4, Runtime API Version: 11.8
W0315 14:29:19.539882  7370 gpu_resources.cc:164] device: 3, cuDNN Version: 8.9.
[2024-03-15 14:29:21,415] [ WARNING] - Some weights of the model checkpoint at vi-layoutxlm-base-uncased were not used when initializing LayoutXLMModel: ['visual.pixel_mean', 'visual.pixel_std', 'visual_proj.bias', 'visual_proj.weight']
- This IS expected if you are initializing LayoutXLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LayoutXLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2024-03-15 14:29:21,415] [    INFO] - All the weights of LayoutXLMModel were initialized from the model checkpoint at vi-layoutxlm-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LayoutXLMModel for predictions without further training.
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/home/lzx/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "/home/lzx/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 55, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/lzx/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 80, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/lzx/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 149, in __init__
    super(LayoutXLMForSer, self).__init__(
  File "/home/lzx/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 65, in __init__
    self.model = model_class(
  File "/home/lzx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 255, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by Irving11330** [comment]
兄弟我按照官方文档给的网址下载的ser_vi_layoutxlm_xfund_pretrained和re_vi_layoutxlm_xfund_pretrained解压后皆无法使用，你是怎么使用的？
![企业微信截图_17108992341482](https://github.com/PaddlePaddle/PaddleOCR/assets/63030153/d85c4758-c837-46a2-82bc-97f0eabfe609)

**Comment by SwordyLee** [comment]
有按照文档转为inference model吗

**Comment by Irving11330** [comment]
> 有按照文档转为inference model吗

哥们按照的是什么文档？我是在这里下载的
![企业微信截图_17109045997433](https://github.com/PaddlePaddle/PaddleOCR/assets/63030153/3d436330-9a00-442b-be73-96735220ccce)
解压完发现根本打不开

**Comment by Irving11330** [comment]
> 有按照文档转为inference model吗

哥们是按照什么文档？我是在这里下载的
![企业微信截图_17109045997433](https://github.com/PaddlePaddle/PaddleOCR/assets/63030153/400ce8cc-f001-4ba3-bd68-f46eb77c1efd)
解压完就如上图打不开

**Comment by SwordyLee** [comment]
参考下这个https://github.com/PaddlePaddle/PaddleOCR/issues/11748#issuecomment-2008603598

**Comment by Irving11330** [comment]
> 参考下这个[#11748 (comment)](https://github.com/PaddlePaddle/PaddleOCR/issues/11748#issuecomment-2008603598)

哥们你发的不就是这个issue吗？

**Comment by SwordyLee** [comment]
> > 参考下这个[#11748 (comment)](https://github.com/PaddlePaddle/PaddleOCR/issues/11748#issuecomment-2008603598)
> 
> 哥们你发的不就是这个issue吗？

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/algorithm_kie_layoutxlm.md
发错了

**Comment by huanghao128** [comment]
PaddleOCR和PaddleNLP版本不匹配的问题。PaddleNLP中paddlenlp/transformers/layoutxlm/modeling.py下LayoutXLMForTokenClassification初始化方法有变化。
PaddleNLP 2.5.2实现：
![Snipaste_2024-04-18_10-14-32](https://github.com/PaddlePaddle/PaddleOCR/assets/14681278/c80af47e-8d5a-4aa4-9845-d455fe598609)
PaddleNLP 2.6.0+实现：
![Snipaste_2024-04-18_10-10-19](https://github.com/PaddlePaddle/PaddleOCR/assets/14681278/fb03bea6-5a00-4db9-9e95-b71bbf0ca99a)
目前可行的版本匹配方案：
1、PaddleOCR<=2.7.0  + PaddleNLP==2.5.2
2、PaddleOCR>=2.7.1 + PaddleNLP>=2.6.0

**Comment by UserWangZz** [comment]
感谢讨论❤️

**Comment by qdhonker** [comment]
我把版本改成2、PaddleOCR>=2.7.1 + PaddleNLP>=2.6.0也还是报这个错

**Comment by Unlicensed-driver-ljx** [comment]
> 我把版本改成2、PaddleOCR>=2.7.1 + PaddleNLP>=2.6.0也还是报这个错

解决了吗

**Comment by huanghao128** [comment]
> 我把版本改成2、PaddleOCR>=2.7.1 + PaddleNLP>=2.6.0也还是报这个错

PaddleNLP>=2.6.0后，LayoutXLMForTokenClassification初始化参数对不上了，需要改ppocr/modeling/backbones/vqa_layoutlm.py中NLPBaseModel类的模型初始化（第69行），试了下能跑起来，结果待验证。
修改前：
```python
            ...
            if type == "ser":
                self.model = model_class.from_pretrained(
                    pretrained_model_name, num_classes=kwargs["num_classes"], dropout=0
                )
            ...
```
修改后：
```python
            ...
            if type == "ser":
                base_model = base_model_class.from_pretrained(pretrained_model_name)
                config = base_model.config
                config["num_labels"] = kwargs["num_classes"]
                self.model = model_class(config)
          ...
```

**Comment by GreatV** [comment]
@huanghao128 如果方便的话，你可以提一个PR修复这个问题。

**Comment by metoogo** [comment]
> 兄弟我按照官方文档给的网址下载的ser_vi_layoutxlm_xfund_pretrained和re_vi_layoutxlm_xfund_pretrained解压后皆无法使用，你是怎么使用的？ ![企业微信截图_17108992341482](https://private-user-images.githubusercontent.com/63030153/314357159-d85c4758-c837-46a2-82bc-97f0eabfe609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjQwNDMsIm5iZiI6MTcyOTkyMzc0MywicGF0aCI6Ii82MzAzMDE1My8zMTQzNTcxNTktZDg1YzQ3NTgtYzgzNy00NmEyLTgyYmMtOTdmMGVhYmZlNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA2MjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YTA4MDVhYzJlOTMwYjE4YjEwNGNkOGM0NWI0OTc3YzMxM2FiNDkxZmI2OTExM2E0Y2U4N2M4Y2JkZGQxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30_xAJaS6th9RsYJmMYHf_AZruZFha3YzeJ-X-IYx3o)

兄弟，你后面怎么解决的？我发现这几个模型改个后缀还能再解压一次，里面是模型文件了，但是缺了一个.pdopt，还是用不了

**Comment by GreatV** [comment]
@metoogo  请参考 https://paddlepaddle.github.io/PaddleOCR/latest/ppstructure/model_train/train_kie.html#41 paddle < 2.6 paddlenlp < 2.6
