### ISSUE TITLE
恢复版面时，输出的docx效果与原始图片中的文本排版不一致

### ISSUE THREAD

**Issue by kackbob** [PaddlePaddle/PaddleOCR#11741]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10+python3.10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle-gpu       2.6.0.post117
- 运行指令/Command Code：python paddleocr.py --image_dir image_1.jpg --type structure --recovery true --lang ch --layout_dict_path .\ppocr\utils\dict\layout_dict\layout_cdla_dict.txt
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by kackbob** [comment]
图片链接
![image_1](https://github.com/PaddlePaddle/PaddleOCR/assets/140471547/3a9653fa-d375-4f2f-ac7c-850da9e98be6)

输出docx文件链接
[image_1_ocr.docx](https://github.com/PaddlePaddle/PaddleOCR/files/14600870/image_1_ocr.docx)

**Comment by cuicheng01** [comment]
这个应该是符合预期的，具体使用的话，这块还需要基于开源版本调试

**Comment by ATP-BME** [comment]
请问具体应该怎样调试呢

**Comment by UserWangZz** [comment]
可能需要根据你的需求来修改代码
