### ISSUE TITLE
Compling cpp  libpaddle_inference.so on Ubuntu 20 failed

### ISSUE THREAD

**Issue by richardgohth** [PaddlePaddle/PaddleOCR#11749]
Have been trying to compile libpaddle_inference.so on Ubuntu 20 without success.
Used 
 cmake  ..     -DWITH_CONTRIB=OFF     -DWITH_MKL=ON     -DWITH_MKLDNN=ON      -DWITH_TESTING=OFF     -DCMAKE_BUILD_TYPE=Release     -DWITH_INFERENCE_API_TEST=OFF     -DON_INFER=ON     -DWITH_PYTHON=ON -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.4/bin/nvcc -DWITH_GPU=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12.4 

Error is
Command-line error: invalid or no value specified with --nv_arch flag

1 catastrophic error detected in this compilation.
Compilation terminated.
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.Release.cmake:280 (message):
  Error generating file
  /paddleocr/Paddle/build/third_party/warprnnt/src/extern_warprnnt-build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o
======================

Have tried to compile with Cuda 11.7 and 12.1 both also failed at some cuda compilation.
Am using gcc8.
cuddn version 8.9

Able to compile withou -DWITH_GPU=ON
but gpu is not used during run.

Able to compile and run on Ubuntu 18.
But need to upgrade to Ubuntu 20 due to new gpu RTX4060 being not compatible with Ubuntu 18.
Will Ubuntu 18 be compatible with RTX30360, if so will acquire RTX3060.

Am using gcc8.

Appreciate any advice on how to compile libpaddle_inference.so with gpu support on Ubunut 20
Or anyone has a libpaddle_inference.so compiled on ubuntu 20?

Thank you

**Comment by changdazhou** [comment]
you can try remove Paddle/third_party/* and remove Paddle/.git/modules/third_party/*

**Comment by richardgohth** [comment]
Thanks.
Trying.. but it seems , cmake and make will download again using git clone?
=====
Check submodules of paddle, and run 'git submodule update --init --recursive'
Cloning into '/paddleocr/Paddle/third_party/absl'...
Cloning into '/paddleocr/Paddle/third_party/brpc'...
Cloning into '/paddleocr/Paddle/third_party/cub'...

======

**Comment by richardgohth** [comment]
Thanks.
Same error.

Command-line error: invalid or no value specified with --nv_arch flag

1 catastrophic error detected in this compilation.
Compilation terminated.
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.Release.cmake:280 (message):
  Error generating file
  /paddleocr/Paddle/build/third_party/warprnnt/src/extern_warprnnt-build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o

**Comment by richardgohth** [comment]
Can compile wartprnnt , warp-transducer, using CUDA 10.2 , following the readme.md file.
When using CUDA 10.2 to compile paddle, got this error message
nvcc fatal   : Unsupported gpu architecture 'compute_80'
How can I limit the gpu architectures supported when generating the make files?

**Comment by richardgohth** [comment]
Now got new error during make
===
   from /paddleocr/Paddle/paddle/phi/kernels/funcs/eigen/eigen_function.h:22,
                 from /paddleocr/Paddle/paddle/phi/kernels/funcs/eigen/broadcast.cc:17:
/paddleocr/Paddle/third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBroadcasting.h: In static member function ??static void phi::funcs::EigenBroadcast<Eigen::DefaultDevice, T, Rank>::Eval(const Eigen::DefaultDevice&, phi::funcs::EigenBroadcast<Eigen::DefaultDevice, T, Rank>::OutType32BitIndex, phi::funcs::EigenBroadcast<Eigen::DefaultDevice, T, Rank>::InType32BitIndex, const Array&) [with T = bool; int Rank = 5]??:
/paddleocr/Paddle/third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBroadcasting.h:680:27: error: ??it[0].Eigen::TensorEvaluator<const Eigen::TensorBroadcastingOp<const Eigen::DSizes<long int, 5>, const Eigen::TensorMap<Eigen::Tensor<const bool, 5, 1, int>, 16, Eigen::MakePointer> >, Eigen::DefaultDevice>::BlockBroadcastingIteratorState::count?? may be used uninitialized in this function [-Werror=maybe-uninitialized]
         if (++it[j].count < it[j].size) {
             ~~~~~~~~~~~~~~^~~~~~~~~~~~
/paddleocr/Paddle/third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBroadcasting.h:650:52: note: ??it[0].Eigen::TensorEvaluator<const Eigen::TensorBroadcastingOp<const Eigen::DSizes<long int, 5>, const Eigen::TensorMap<Eigen::Tensor<const bool, 5, 1, int>, 16, Eigen::MakePointer> >, Eigen::DefaultDevice>::BlockBroadcastingIteratorState::count?? was declared here
     array<BlockBroadcastingIteratorState, NumDims> it;
                                                    ^~

=======

**Comment by richardgohth** [comment]
now is this error, seems cannot compile  warprnnt on ubuntu 20
====
[ 50%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Command-line error: invalid or no value specified with --nv_arch flag

1 catastrophic error detected in this compilation.
Compilation terminated.
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.Release.cmake:280 (message):
  Error generating file
  /stratton/Paddle/build/third_party/warprnnt/src/extern_warprnnt-build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o

**Comment by richardgohth** [comment]
hi,
now trying to use the pre-compiled  libpaddle_inference.
found that my cpp code is version 2.7 but downloaded libpaddle_inference is probably 2.3
hence cannot compile
where can I download cpp_infer code version 2.3  or
libpaddle_inference.so compatible with cpp_infer code 2.7?

typical compile errors
/usr/bin/ld: /paddleocr/newdownload/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:110: undefined reference to `paddle::AnalysisConfig::EnableUseGpu(unsigned long, int, paddle::AnalysisConfig::Precision)'

appreciate any advise

**Comment by richardgohth** [comment]
Finally running by downloading using pip paddleocr==2.6
Thank you very much

**Comment by richardgohth** [comment]
found that it is not using the gpu :(

**Comment by richardgohth** [comment]
found this message
==
Please use PaddlePaddle with GPU version

**Comment by changdazhou** [comment]
sorry, you need to raise this issue under the warehouse of Paddle

**Comment by richardgohth** [comment]
found its not due to paddlepaddle, the warning is wrong
its because can only compile libpaddle_inference.so without gpu support
with gpu support cannot compile :(
so should be under paddleocr
thanks

**Comment by changdazhou** [comment]
ok, this issue has been recorded
