### ISSUE TITLE
关于PaddleOCR场景应用覆盖通用等模型

### ISSUE THREAD

**Issue by yuhai5237** [PaddlePaddle/PaddleOCR#11758]
请问PaddleOCR场景应用覆盖通用的模型应该怎么获取，关注了公众号，没看到群和问卷

**Comment by tink2123** [comment]
如需下载场景中已经训练好的垂类模型，可以加入PaddleX官方交流频道获取20G OCR学习大礼包（内含《动手学OCR》电子书、课程回放视频、前沿论文等重磅资料）

PaddleX官方交流频道：https://aistudio.baidu.com/community/channel/610
