### ISSUE TITLE
paddleocr执行版面恢复功能失败

### ISSUE THREAD

**Issue by Fissionalist** [PaddlePaddle/PaddleOCR#11754]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win
- 版本号/Version：Paddle：  PaddleOCR：2.6.1.3 
  - 问题相关组件/Related components：paddleocr/ppstructure
- 运行指令/Command Code：`paddleocr --image_dir=text.pdf --type=structure --recovery=true`
- 问题描述：在载入指定 PDF 文件（文件内容几乎全是表格）进行 docx 恢复时，转换至最后一页时发生如下报错：
```shell
ppocr ERROR: error in layout recovery image:text, err msg: list index out of range
```

**Comment by changdazhou** [comment]
能提供更多的报错log吗

**Comment by changdazhou** [comment]
有测试过其他文件吗，如果只在这个文件上有问题，能否提供一下文件我们这边测试下呢

**Comment by Fissionalist** [comment]
> 有测试过其他文件吗，如果只在这个文件上有问题，能否提供一下文件我们这边测试下呢

测试了几个其他的文件，还真没什么问题。
原始文件：[Census_table.pdf](https://github.com/PaddlePaddle/PaddleOCR/files/14661534/Census_table.pdf)


https://github.com/PaddlePaddle/PaddleOCR/blob/69832ab5326c6db614af6fb74b530aeae1c9b80e/paddleocr.py#L859

**Comment by changdazhou** [comment]
建议将pdf的最后一页删除掉试试，感觉问题出现在了最后一页
