### ISSUE TITLE
复杂排版文字识别如何标注？

### ISSUE THREAD

**Issue by echochoc** [PaddlePaddle/PaddleOCR#11759]
![IMG_ppmoney_20220924_124811_6213_f6_33_1120 5000_3406 0000_863 0000_438 0000_0 000000_329 4103_193 1026_421 0000_168 0000_0 000000](https://github.com/PaddlePaddle/PaddleOCR/assets/18675077/011ce74c-7766-426b-aa2a-2d17d011576e)
图片中是一个价签的价格字段，请问标注的时候是标为"25.90"还是"25.90元/瓶"？如果是前者，我如何可以识别出单位呢？额外增加一个检测框分开识别吗？

**Comment by echochoc** [comment]
> 目前仅支持单行文本识别， 多行复杂排版需要标注多个检测框。请问您的场景中都是这类图片吗？如果样式固定可以写一个统一的处理逻辑，例如把每张图片分离成价格和单位两个部分，分别经过OCR识别，最终将结果拼在一起。

感谢回复。实际场景不一定，价签的版式多种多样。

**Comment by echochoc** [comment]
@tink2123 我看PPOCRv4里使用了SVTR结构，把图片做了patch-wise image tokenization，是不是可以一定程度上解决这个问题呢？
还有有的时候价格可能是这种形式的：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/18675077/6b757227-a76a-4a8b-a5aa-8a2170c142f3)
我希望预测出370.00，是否可以直接标记为"370.00"呢？

**Comment by tink2123** [comment]
@echochoc 一定程度可以缓解，但不能保证完全解决，因为模型结构设计的时候没有特意处理多行文本的问题。上图可以标注为370.00。

**Comment by Arrogant-Q** [comment]
这种识别真的很麻烦哈哈哈哈哈

**Comment by UserWangZz** [comment]
感谢讨论❤️
