### ISSUE TITLE
在pycharm中运行全部项目，皆正常运行，无报错。  把项目中包含paddleocr库的脚本注释掉，打包运行项目其余部分，生成的exe文件运行正常。  加入paddleocr打包后，运行程序报错：  NotFoundError: [Errno 2] No such file or directory:  'C:\\Users\\12092\\AppData\\Local\\Temp\\_MEI344202\\paddleocr\\tools/__init__.py'

### ISSUE THREAD

**Issue by ydsjeff2020** [PaddlePaddle/PaddleOCR#11750]
在pycharm中运行全部项目，皆正常运行，无报错。

把项目中包含paddleocr库的脚本注释掉，打包运行项目其余部分，生成的exe文件运行正常。

加入paddleocr打包后，运行程序报错：

NotFoundError: [Errno 2] No such file or directory:
 'C:\\Users\\12092\\AppData\\Local\\Temp\\_MEI344202\\paddleocr\\tools/__init__.py'

**Comment by changdazhou** [comment]
注意路径中的最后一个斜杠哈，应该是路径表达出了问题，检查一下你的打包逻辑哈

**Comment by ydsjeff2020** [comment]
解决方法：
在.spec中的datas中添加，后再打包，我的已解决
datas=[('C:\\Users\\Administrator\\.virtualenvs\\MEBx_Test-b9tfmB5g\\Lib\\site-packages\\paddleocr\\tools', 'paddleocr' )],

**Comment by ZNBmm** [comment]
解决了吗，我也出现这个问题了

**Comment by changdazhou** [comment]
> 解决方法： 在.spec中的datas中添加，后再打包，我的已解决 datas=[('C:\Users\Administrator\.virtualenvs\MEBx_Test-b9tfmB5g\Lib\site-packages\paddleocr\tools', 'paddleocr' )],

参考他的方法试过了吗
