### ISSUE TITLE
使用ppstructure里的表格识别功能出错

### ISSUE THREAD

**Issue by mingxingpu** [PaddlePaddle/PaddleOCR#11766]
我想尝试表格识别并还原成excel的功能，并在PaddleOCR/ppstructure目录下，运行了如下命令：
python3 table/predict_table.py --det_model_dir=inference/ch_ppocr_server_v2.0_det_infer 
--rec_model_dir=inference/ch_ppocr_server_v2.0_rec_infer 
--table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer 
--image_dir=../../images/table_images/table4.png 
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt 
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt 
--det_limit_side_len=488 --det_limit_type=min --output ../output/table

但是在../output/table/目录下得到的excel是空的，在分析的过程中发现predict_table.py的182行得到的pred_html为：
<html><body><table><thead><tr> colspan="5" colspan="4" colspan="2"</tr> colspan="5" colspan="3" colspan="2"</tr> colspan="5" colspan="3" colspan="2"</tr></thead><tr>IPTCours) 3830 2821m 3907 2880</td></tr></td></tr></td></tr></td></tr></thead><tbody></tbody><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><tr></td></tr></td></tr></td></tr></td></tr></td></tr></thead><td</table></body></html>
这与原始表格结构差别很大，并且貌似就是一个空的html表格。  我想知道问题出在哪里呢？
表格图片如下：
<img width="521" alt="table4" src="https://github.com/PaddlePaddle/PaddleOCR/assets/59463530/24f70955-b5a0-4f73-8718-365e3ae08012">

**Comment by mingxingpu** [comment]
我想知道是因为表格结构识别的模型不正确吗？有没有提供效果更好的表格结构识别模型呢？我在几个文档里都没有找到。

**Comment by TingquanGao** [comment]
目前表格识别模型对于跨行跨列的识别效果较差，我们正在优化中，感谢关注。

**Comment by TingquanGao** [comment]
该issue已关闭，如仍有疑问可reopen或新提issue~
