### ISSUE TITLE
数据集的量级和训练时长的问题

### ISSUE THREAD

**Issue by Alanhzl** [PaddlePaddle/PaddleOCR#11768]
目前使用的是1050Ti 4G的显卡，windows系统装docker desktop，训练V2识别模型，数据集1w时大概需要训练15小时。

后续预计会重新配电脑用于训练模型，装Ubuntu，CPU是i7-13700F，显卡在4080和4090之间犹豫

因此我想请问一下：
如果字典有6K字符，根据训练需要每个字符至少出现在200张图这个要求，一张图20字符的话，要有6w以上的图片才能满足需求。加上为了避免过拟合还需要加其他数据集，最终数据集应该会上到10w-20w的大小。（后续字典可能会新增更多字符）

在上面这个量级和条件下，训练V2模型，epoch_num设置500轮，4080和4090大概都需要多少时间呢？

**Comment by TingquanGao** [comment]
抱歉，我们没有在4080、4090上测试过该模型的训练速度。
