### ISSUE TITLE
预测结果中的文字不在字典中

### ISSUE THREAD

**Issue by hpdqddsy** [PaddlePaddle/PaddleOCR#11767]
我尝试在训练文本识别模型时使用自定义字典，但在用训练得到的模型进行预测时，预测结果中的文字均不在字典中。这似乎是一个不应出现的现象。请问问题可能出在哪里？我该如何解决？谢谢。

---

- Windows 10，Python 3.8.18，paddlepaddle-gpu 2.5.0rc1.post118；
- 使用的是 release/2.7 版本的代码；
- 配置文件参考的是 `./configs/rec/multi_language/rec_multi_language_lite_train.yml` ，网络结构没有修改；
- 在一个样本数1000左右的数据集上初步尝试训练了一个模型，`best metric, acc: 0.7187`；
- 在使用 `./tools/infer/predict_rec.py` 进行预测时，将 `--rec_image_shape` 设置为与配置文件中 `image_shape` 相同（均为`3, 32, 45`）,而后遇到了如上问题。

**Comment by GreatV** [comment]
预测的时候也要指定自定义字典位置吧
