### ISSUE TITLE
几个小问题，还请指教，谢谢！

### ISSUE THREAD

**Issue by kidling-g** [PaddlePaddle/PaddleOCR#1176]
1. 训练识别模型时，如果对于宽高比大于10的样本直接舍弃，那么在此基础上训练得到的最终模型如何处理此类样本？我看之前的回答说不影响对图像的预测，为什么不影响呢？

2. 使用通用预训练识别模型（ch_ppocr_server_v1.1_rec_pre）直接对自己合成的10000张图片进行评估，为何初始精度只有0.13左右，似乎有些低了，是不是和我使用的合成数据有关。

3. 训练配置文件（rec_chinese_reader.yml）中的`num_workers: 8`这个是不是指的是使用8个线程读取数据，而跟具体的训练过程无关？

感谢回答！

**Comment by LDOUBLEV** [comment]
1. 目前代码中设置的是label字符超过25个的图像不参与训练，25可以自行调整；预测时图像会resize到【3，32，320】这样去识别，而且中文识别模型是基于CTC的，多少字符都可以识别，如果你的场景长文本很多，可以考虑扩大图像resize的宽度；

2. 我们的模型是在大批量合成数据和真实数据上训练的；你只在合成数据上finetune会影响原模型性能；

3. num_workers只影响数据读取，设置多卡训练可以用export CUDA_VISIBLE_DEVICES="0,1,2,3"这样

**Comment by kidling-g** [comment]
@LDOUBLEV 对于识别而言，是不是训练和预测都会对图像resize？

**Comment by kidling-g** [comment]
> * 目前代码中设置的是label字符超过25个的图像不参与训练，25可以自行调整；预测时图像会resize到【3，32，320】这样去识别，而且中文识别模型是基于CTC的，多少字符都可以识别，如果你的场景长文本很多，可以考虑扩大图像resize的宽度；
> * 我们的模型是在大批量合成数据和真实数据上训练的；你只在合成数据上finetune会影响原模型性能；
> * num_workers只影响数据读取，设置多卡训练可以用export CUDA_VISIBLE_DEVICES="0,1,2,3"这样

关于第二个问题，我的意思是在finetune之前直接使用预训练模型对自己合成的数据集进行评估，精度很低，这个原因是什么呢？

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV 对于识别而言，是不是训练和预测都会对图像resize？

会resize，可以看下repo中的代码

finetune之前用我们的模型在你们合成数据上评估，精度很低可能是数据分布差异较大，可以发一些样例数据看看？

**Comment by kidling-g** [comment]
![截屏2020-11-19 14 44 25](https://user-images.githubusercontent.com/62318458/99630984-ca63a400-2a75-11eb-9d7e-239f58fa97a3.png)
![截屏2020-11-19 14 44 33](https://user-images.githubusercontent.com/62318458/99630991-cdf72b00-2a75-11eb-8029-fdd8d8b693e5.png)
![截屏2020-11-19 14 44 41](https://user-images.githubusercontent.com/62318458/99630995-ce8fc180-2a75-11eb-9c0d-86c711c8680b.png)
@LDOUBLEV 大致是这类数据集，您看看

**Comment by ddz-mark** [comment]
> 1. 目前代码中设置的是label字符超过25个的图像不参与训练，25可以自行调整；预测时图像会resize到【3，32，320】这样去识别，而且中文识别模型是基于CTC的，多少字符都可以识别，如果你的场景长文本很多，可以考虑扩大图像resize的宽度；
> 2. 我们的模型是在大批量合成数据和真实数据上训练的；你只在合成数据上finetune会影响原模型性能；
> 3. num_workers只影响数据读取，设置多卡训练可以用export CUDA_VISIBLE_DEVICES="0,1,2,3"这样

预测时也会固定尺寸到【3，32，320】？我这边通过 log 发现 infer_rec.py 函数输出是的高度固定为 32，但是长度不固定。

**Comment by littletomatodonkey** [comment]
ctc的时候，不会固定宽度的，attention的时候，是会固定的

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
