### ISSUE TITLE
paddle.exp计算结果错误

### ISSUE THREAD

**Issue by adherent-ls** [PaddlePaddle/PaddleOCR#11769]
- ubuntu20.04：
- paddlepaddle-gpu==2.5.2.post120

> import paddle
> import numpy as np
> paddle.exp(paddle.Tensor(np.array([0.2])))

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/96528773/441b789a-98fd-41a0-a400-bbf26403c8fb)

**Comment by GreatV** [comment]
Pascal GPU arch is not compatible with Paddle.

**Comment by GreatV** [comment]
GPU 太旧了，paddle不兼容。你可以换个gpu或者使用arch 61重新编译一下paddle

**Comment by TingquanGao** [comment]
你的CUDA版本是12.0吗？

**Comment by TingquanGao** [comment]
该issue已关闭，如仍有疑问可reopen或新提issue~

**Comment by adherent-ls** [comment]
> Pascal GPU arch is not compatible with Paddle.
