### ISSUE TITLE
libpng error: idat: bad parameters to zlib paddleocr

### ISSUE THREAD

**Issue by hoangsc7** [PaddlePaddle/PaddleOCR#11776]

**Comment by hoangsc7** [comment]
![Uploading Screenshot from 2024-03-20 16-57-43.png…]()

**Comment by Sunting78** [comment]
您好 我们是支持png格式的，是否是图像编码有问题呢？可以发出几张图给我进行下复现。

**Comment by hoangsc7** [comment]
> 您好 我们是支持png格式的，是否是图像编码有问题呢？可以发出几张图给我进行下复现。

Thanks.I found the error due to installing the wrong library. I reinstalled opencv 4.5.2.52 and it worked
