### ISSUE TITLE
hubserving使用一段时间后宕机，hub服务在，post能通，无报错信息。

### ISSUE THREAD

**Issue by wangshijia523** [PaddlePaddle/PaddleOCR#11778]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.6  PaddleOCR： 2.6.1.1  问题相关组件/Related components：
- 运行指令/Command Code：hub serving start -c deploy/hubserving/ocr_system/config.json
- 完整报错/Complete Error Message：
无报错信息。(https://github.com/PaddlePaddle/PaddleOCR/issues/3148)
和这个问题有点像，但是刚开始使用时是正常的，大概一个星期以后出现异常。hub的服务进程还在，post能通，只是没有返回值了。
正常时完整信息：ppocr DEBUG: dt_boxes num : 22, elapse : 0.03708672523498535
[2024/03/20 18:27:04] ppocr DEBUG: cls num  : 22, elapse : 0.01366424560546875
[2024/03/20 18:27:04] ppocr DEBUG: rec_res num  : 22, elapse : 0.06538057327270508
[2024-03-20 18:27:04,935] [    INFO] _internal.py:224 - 127.0.0.1 - - [20/Mar/2024 18:27:04] "POST /predict/ocr_system HTTP/1.1" 200 -
异常时信：[2024-03-20 18:27:04,935] [    INFO] _internal.py:224 - 127.0.0.1 - - [20/Mar/2024 18:27:04] "POST /predict/ocr_system HTTP/1.1" 200 -
异常时就不在有ppocr DEBUG: rec_res num  的输出

**Comment by Sunting78** [comment]
您好 hubserving暂不维护, 建议使用fastdeploy的triton服务化部署，或者paddleserving吧
