### ISSUE TITLE
求助，为什么PaddleOCRv2在Android里面识别不了整行文字啊

### ISSUE THREAD

**Issue by LiuTingqq149132** [PaddlePaddle/PaddleOCR#11775]
- 系统环境/System Environment：Android
- 版本号/Version：Paddle：  PaddleOCRv2

我用的是paddleocr 的Android demo，可识别出来的一行文字只有一部分是正常的，后面全是乱码
就比如我检测的文字是：还可以，有些故事节奏啰嗦，但人物都挺立体。
但是识别结果就是：还可以，有些故事节奏啰嗦，但人#五 赠2#
这个要怎么处理啊？

**Comment by LiuTingqq149132** [comment]
![qq_pic_merged_1710915812114](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/6ba1545d-84d1-4494-babb-e7813ceed391)
![qq_pic_merged_1710915843361](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/5bd22bfd-20de-4db7-b2e0-cbe4693163e5)

**Comment by Alanhzl** [comment]
你是不是点了多次运行模型？运行一次会在图片框选文字，运行第二次时是会在上一次框选后的图再去检测一次文字位置，是有可能导致识别错误的。

**Comment by LiuTingqq149132** [comment]
我只点了一次运行模型。如果多次点击的话，这个识别框会重叠，识别范围会变小，这个我知道的。

**Comment by Alanhzl** [comment]
识别的原图发一下，我试试看

**Comment by LiuTingqq149132** [comment]
![Screenshot_2024-01-04-01-22-11-602_com jjwxc read](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/f097bd69-a4f0-45cd-b4f9-ec48541be824)

**Comment by LiuTingqq149132** [comment]
![Screenshot_2024-03-20-12-35-48-534_com baidu padd](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/1f22f098-df6c-4a24-b020-e6d48d76e1db)
![Screenshot_2024-03-20-12-35-41-607_com baidu padd](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/61d77dd5-8bf8-4c79-af9a-42fbe2fd41e4)
这个是我识别的结果

**Comment by Alanhzl** [comment]
![微信图片_20240320152921](https://github.com/PaddlePaddle/PaddleOCR/assets/39329022/90fb98b3-c52b-416f-8302-95470c9c4e53)
跑Demo整行是完整识别的，是换了模型吗？

**Comment by LiuTingqq149132** [comment]
没有啊，就是这个模型啊
![Screenshot_2024-03-20-15-47-18-860_com baidu padd](https://github.com/PaddlePaddle/PaddleOCR/assets/91737651/3ab7a498-cc25-4d8d-9eee-ed72f5ce0b5f)

**Comment by Alanhzl** [comment]
好的，我复现出来了，初始Demo确实是有问题的，估计是Demo用的模型是比较早的版本，有些字没训练好之类的。
我一开始没复现是因为我是换了PaddleLite v2.12，模型是下了v2模型，重新用PaddleLite编译的opt转换的nb模型，抱歉刚刚没留意我的Demo是换了文件的。
那你换一下预测库和模型应该就好了

**Comment by LiuTingqq149132** [comment]
哦哦，我去试试

**Comment by LiuTingqq149132** [comment]
我能问一下怎么换预测库和模型啊？只要我换一个它就直接报错了，总是出现各种问题，想问问大佬有没有什么步骤什么的啊

**Comment by LiuTingqq149132** [comment]
我能问一下究竟是怎么换的预测库和模型的啊？我按照别人写的步骤进行更换就直接报错了，报错是这个。之后不管我时候这么换模型都是这个报错。求大佬帮忙。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 求助，为什么PaddleOCRv2在Android里面识别不了整行文字啊 (Issue #11775)





 
好的，我复现出来了，初始Demo确实是有问题的，估计是Demo用的模型是比较早的版本，有些字没训练好之类的。
 我一开始没复现是因为我是换了PaddleLite v2.12，模型是下了v2模型，重新用PaddleLite编译的opt转换的nb模型，抱歉刚刚没留意我的Demo是换了文件的。
 那你换一下预测库和模型应该就好了

**Comment by Alanhzl** [comment]
> 我能问一下怎么换预测库和模型啊？只要我换一个它就直接报错了，总是出现各种问题，想问问大佬有没有什么步骤什么的啊

预测库的版本和模型好像是要一致的，所以我都是自己编译lite库和opt转换工具，然后用opt转换模型。

PaddleLite库编译可以参考这个[https://paddlepaddle.github.io/Paddle-Lite/v2.2.0/source_compile/](url)
opt工具的话，拉取PaddleLite代码后，执行./lite/tools/build.sh build_optimize_tool就会编译了，这个耗时挺长的
换库和模型就是把图片里面的这些头文件，库，模型换掉就行
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/39329022/14772298-96c9-42cf-b839-577ccdbd5440)

**Comment by Alanhzl** [comment]
> https://paddlepaddle.github.io/Paddle-Lite/v2.2.0/source_compile/

编译模式用full publish，链接直接点好像是异常的，复制到浏览器打开吧。

不自己编译的话，也可以找官方编译好的库，应该也能用

**Comment by Alanhzl** [comment]
[inference_lite_lib.android.armv8.zip](https://github.com/PaddlePaddle/PaddleOCR/files/14691935/inference_lite_lib.android.armv8.zip)
[ch_PP-OCRv2.zip](https://github.com/PaddlePaddle/PaddleOCR/files/14691937/ch_PP-OCRv2.zip)

这是我编译的v2.12PaddleLite库和对应转换后的nb模型，你可以替换后试一试

**Comment by y649950268** [comment]
@Alanhzl 
![7c3f09fc326fec04aad616a554c323b](https://github.com/user-attachments/assets/1fa509f6-fb3a-4be4-92ae-bbae33e49dd7)

你好 从2.10升级到2.12 是不是只用替换对应的.h 和 .so文件？ 我尝试了2.12 后最新的好多版本  也转换了对应版本的nb模型  但是android初始化的时候始终crash ,而2.10版本又有整行识别不全的问题，能不能提供一下整个demo项目啊，谢谢
