### ISSUE TITLE
双卡训练识别模型，出现某张卡被强制中断错误  code -9 log ./debug/workerlog.0

### ISSUE THREAD

**Issue by jtcjump** [PaddlePaddle/PaddleOCR#11773]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

LAUNCH INFO 2024-03-10 00:35:50,211 Pod failed
LAUNCH ERROR 2024-03-10 00:35:50,216 Container failed !!!

- 系统环境/System Environment：ubuntu20.04,cuda11.6
- 版本号/Version：Paddle：2.6  PaddleOCR：2.7.1  问题相关组件/Related components：
- 运行指令/Command Code：训练识别模型，python -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1'  tools/train.py -c configs/a_rec_self/ch_PP_OCRv4_rec_pplcnetv3_01.yml
- 完整报错/Complete Error Message：
LAUNCH INFO 2024-03-10 00:35:50,211 Pod failed
LAUNCH ERROR 2024-03-10 00:35:50,216 Container failed !!!
Container rank 0 status failed cmd ['/home/ /.conda/envs/paddle26/bin/python', '-u', 'tools/train.py', '-c', 'configs/a_rec_self/ch_PP_OCRv4_rec_pplcnetv3_01.yml''] code -9 log ./debug/workerlog.0
env {'SHELL': '/bin/bash', 'CONDA_EXE': '/opt/miniconda3/bin/conda', '_CE_M': '', 'LANGUAGE': 'zh_CN:zh', 'FLAGS_call_stack_level': '2', 'PWD': '/home/ /code/ocr/paddleocr271', 'LOGNAME': ' ', 'XDG_SESSION_TYPE': 'tty', 'CONDA_PREFIX': '/home/ /.conda/envs/paddle26', 'MOTD_SHOWN': 'pam', 'HOME': '/home/ ', 'LANG': 'zh_CN.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CONDA_PROMPT_MODIFIER': '(paddle26) ', 'SSH_CONNECTION': '192.168.31.181 54550 192.168.31.226 22', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm', '_CE_CONDA': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': ' ', 'CONDA_SHLVL': '3', 'DISPLAY': 'localhost:11.0', 'SHLVL': '0', 'XDG_SESSION_ID': '6', 'CONDA_PYTHON_EXE': '/opt/miniconda3/bin/python', 'LD_LIBRARY_PATH': '/home/ /.conda/envs/paddle26/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda-11.6/lib64:', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SSH_CLIENT': '192.168.31.181 54550 22', 'CONDA_DEFAULT_ENV': 'paddle26', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PATH': '/usr/local/cuda-11.6/bin:/home/ /.conda/envs/paddle26/bin:/opt/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'SSH_TTY': '/dev/pts/1', 'CONDA_PREFIX_1': '/opt/miniconda3', 'CONDA_PREFIX_2': '/home/ /.conda/envs/paddle25', 'OLDPWD': '/home/ ', '_': '/usr/bin/nohup', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/home/ /.conda/envs/paddle26/lib/python3.10/site-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/home/ /.conda/envs/paddle26/lib/python3.10/site-packages/cv2/qt/fonts', 'POD_NAME': 'hhznnr', 'PADDLE_MASTER': '127.0.1.1:59769', 'PADDLE_GLOBAL_SIZE': '2', 'PADDLE_LOCAL_SIZE': '2', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:59770', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_RANK_IN_NODE': '0', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:59770,127.0.1.1:59771', 'FLAGS_selected_gpus': '0', 'PADDLE_LOG_DIR': '/home/ /code/ocr/paddleocr271/debug'}
LAUNCH INFO 2024-03-10 00:35:50,216 ------------------------- ERROR LOG DETAIL -------------------------
LAUNCH INFO 2024-03-10 00:35:54,702 Exit code -9

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by jtcjump** [comment]
百度的小哥哥帮忙分析下原因吧

**Comment by Sunting78** [comment]
您好 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#nvidia-paddle-nccl-error解决
