### ISSUE TITLE
欲进行kie训练，vi_layoutxlm模型中ser和re的预训练模型下载解压后皆无法使用

### ISSUE THREAD

**Issue by Irving11330** [PaddlePaddle/PaddleOCR#11770]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

 系统环境/System Environment：64位操作系统， 基于 x64 的处理器
 版本号/Version：Paddle：2.6.0  PaddleOCR：2.6.1.3 问题相关组件/Related components：ppstructure
 运行指令/Command Code：mkdir pretrained_model
cd pretrained_model
# 下载并解压SER预训练模型
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/ser_vi_layoutxlm_xfund_pretrained.tar && tar -xf ser_vi_layoutxlm_xfund_pretrained.tar

# 下载并解压RE预训练模型
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/re_vi_layoutxlm_xfund_pretrained.tar && tar -xf re_vi_layoutxlm_xfund_pretrained.tar
 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by Irving11330** [comment]
![企业微信截图_17108983725836](https://github.com/PaddlePaddle/PaddleOCR/assets/63030153/b7e9ae19-93fb-47e4-8426-f96d4a5644fc)

**Comment by Irving11330** [comment]
re_vi_layoutxlm_xfund_infer就是正常的
![企业微信截图_17108984964418](https://github.com/PaddlePaddle/PaddleOCR/assets/63030153/f81522ed-475f-4287-a562-72865828ba36)

**Comment by Sunting78** [comment]
> ![企业微信截图_17108983725836](https://private-user-images.githubusercontent.com/63030153/314354479-b7e9ae19-93fb-47e4-8426-f96d4a5644fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDkyMzAsIm5iZiI6MTcxMTAwODkzMCwicGF0aCI6Ii82MzAzMDE1My8zMTQzNTQ0NzktYjdlOWFlMTktOTNmYi00N2U0LTg0MjYtZjk2ZDRhNTY0NGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4MTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTFhNmU2ZjI5NTVmNWJmNGE2N2QzNDM2NzJkYjZmODI0OTU1NzZmZjA3ODdjMDk2NzEyODkzNzg3YTE1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_8Os2REj2mX_WqGI368jpIWEthKYhmz9PdVC4aDIGU)

您好 可以把这三个文件再解压一下，尝试下。

**Comment by wh403948123** [comment]
好像是paddleocr升级之后的fluid组件移除。全部都不能使用了。哎。。版本啊。
