### ISSUE TITLE
单独执行检测时如何获取结果的数量？

### ISSUE THREAD

**Issue by imoko233** [PaddlePaddle/PaddleOCR#11779]
- 系统环境/System Environment：Windows 11, Python 3.8.18
- 版本号/Version：Paddle：2.6.0  PaddleOCR：2.7.0.3 问题相关组件/Related components：

`result = ocr.ocr(resized_img, rec=False)`
`print(f"num of result {len(result)}")`

使用len(result)输出的结果是1。

**Comment by cuicheng01** [comment]
可以贴一下result的结果吗

**Comment by imoko233** [comment]
> 可以贴一下result的结果吗

[[[[721.0, 151.0], [751.0, 151.0], [751.0, 171.0], [721.0, 171.0]], [[247.0, 151.0], [278.0, 151.0], [278.0, 171.0], [247.0, 171.0]], [[1576.0, 147.0], [1715.0, 145.0], [1715.0, 175.0], [1576.0, 177.0]], [[1374.0, 145.0], [1516.0, 147.0], [1515.0, 176.0], [1374.0, 174.0]], [[850.0, 147.0], [956.0, 147.0], [956.0, 174.0], [850.0, 174.0]], [[500.0, 146.0], [704.0, 148.0], [703.0, 175.0], [500.0, 173.0]], [[1016.0, 145.0], [1159.0, 145.0], [1159.0, 175.0], [1016.0, 175.0]], [[267.0, 147.0], [429.0, 145.0], [430.0, 172.0], [267.0, 174.0]], [[76.0, 145.0], [186.0, 145.0], [186.0, 175.0], [76.0, 175.0]], [[1217.0, 143.0], [1316.0, 143.0], [1316.0, 174.0], [1217.0, 174.0]], [[1777.0, 47.0], [1830.0, 47.0], [1830.0, 72.0], [1777.0, 72.0]], [[1521.0, 45.0], [1586.0, 45.0], [1586.0, 72.0], [1521.0, 72.0]], [[1403.0, 45.0], [1480.0, 45.0], [1480.0, 72.0], [1403.0, 72.0]], [[1250.0, 46.0], [1298.0, 46.0], [1298.0, 70.0], [1250.0, 70.0]], [[1073.0, 45.0], [1206.0, 43.0], [1207.0, 69.0], [1073.0, 72.0]], [[68.0, 43.0], [532.0, 43.0], [532.0, 72.0], [68.0, 72.0]], [[56.0, 47.0], [78.0, 47.0], [78.0, 65.0], [56.0, 65.0]], [[560.0, 40.0], [633.0, 43.0], [632.0, 71.0], [559.0, 68.0]], [[1649.0, 37.0], [1740.0, 42.0], [1738.0, 81.0], [1647.0, 75.0]]]]

**Comment by cuicheng01** [comment]
这个list的结果确实是长度为1的列表，这个列表里又套了一个长度为19的列表
