### ISSUE TITLE
版面分析模型 fastdeploy服务部署报错  ppocr/__init__.py 中StructureV2LayoutPostprocessor类  Failed to process the request(s) for model 'postprocess_0', message: TypeError: run(): incompatible function arguments

### ISSUE THREAD

**Issue by lsx66** [PaddlePaddle/PaddleOCR#11777]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

Invoked with: <fastdeploy.libs.fastdeploy_main.vision.ocr.StructureV2LayoutPostprocessor object at 0x7fd1dd2269b0>, [[array([[[ 3.0430562 ,  2.9620893 , -0.92005384, ..., -1.1082802 ,
         -1.694324  , -1.3905903 ],
        [-0.8745545 ,  3.1247966 ,  3.0257077 , ..., -1.0160857 ,
         -1.3037924 , -0.8528714 ],
        [-1.1111182 , -1.1563158 ,  3.6807263 , ..., -0.8917918 ,
         -1.5667745 , -1.2615712 ],
        ...,
        [ 2.574394  ,  2.0140955 , -0.02018397, ..., -1.5280299 ,
         -1.9861596 , -1.8610322 ],
        [ 0.99233127,  1.3739115 ,  0.8655137 , ..., -1.4873394 ,
         -1.9895219 , -1.8228513 ],
        [ 0.2792613 ,  0.42100033,  1.0559945 , ..., -1.313761  ,
         -1.8969777 , -1.7097901 ]]], dtype=float32)]], [array([640, 404, 608, 800], dtype=object)]

At:
  /usr/local/lib/python3.8/dist-packages/fastdeploy/vision/ocr/ppocr/__init__.py(778): run
  /ocr_serving/vision/ocr/PP-OCR/serving/fastdeploy_serving/models-layout/postprocess/1/model.py(105): execute

**Comment by Sunting78** [comment]
您好，麻烦发下具体报错日志截图。

**Comment by lsx66** [comment]
您好,
![Uploading 屏幕截图 2024-03-21 182730.png…]()
麻烦看看

**Comment by lsx66** [comment]
您好,麻烦看看
![Uploading 屏幕截图 2024-03-21 182730.png…]()

**Comment by lsx66** [comment]
![Uploading 屏幕截图 2024-03-21 182730.png…]()

**Comment by lsx66** [comment]
您好,麻烦看看
![Uploading 屏幕截图 2024-03-21 182540.png…]()

**Comment by UserWangZz** [comment]
您好，提供的截图无法打开查看
