### ISSUE TITLE
文字识别模型训练 在image_shape更改后模型预测失败

### ISSUE THREAD

**Issue by 18205097282** [PaddlePaddle/PaddleOCR#11789]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 GPU训练paddleOCR模型
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.7
- 运行指令/Command Code：
        #image_shape: [3, 32, 320]
          image_shape: [3, 48, 480]
- 完整报错/Complete Error Message：
   在image_shape: [3, 32, 320]时 训练出的模型一切工作正常，在image_shape: [3, 48, 480]后，C++项目读取模型预测失败

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by zhangyubo0722** [comment]
在推理时图片的长宽建议设置为32的倍数
