### ISSUE TITLE
某些分辨率下图片检测结果为空

### ISSUE THREAD

**Issue by imoko233** [PaddlePaddle/PaddleOCR#11781]
- 系统环境/System Environment：Windows 11, Python 3.8.18
- 版本号/Version：Paddle：2.6.0  PaddleOCR：2.7.0.3

原图像分辨率是1617 * 936，因为图片里比较小的字会检测不出来，于是尝试在检测前对图片进行放大处理，例如放大到1920 * 1111，随后进行检测就没有任何结果，试了下其他分辨率如1900 * 1099、2000 * 1157都有结果。

`ocr = PaddleOCR(det_limit_side_len=2000)`
`img_path = './img/123.png'`

`image = cv2.imread(img_path)`
`hei, wid = image.shape[:2]`

`new_wid = 2000`
`ratio = new_wid / wid`
`new_hei = int(hei * ratio)`
`resized_img = cv2.resize(image, (new_wid, new_hei))`

`result = ocr.ocr(resized_img, rec=False)`
`print(result)`

**Comment by cuicheng01** [comment]
您好，请问您的疑问是什么呢？

**Comment by imoko233** [comment]
> 您好，请问您的疑问是什么呢？

就是同一张图片某些分辨率下检测时返回的结果是空，不清楚是什么原因。然后就是将图片放大后再进行检测还是会存在小文字漏检的情况，有什么更好的方法优化吗？

**Comment by cuicheng01** [comment]
这块在不同的分辨率下的结果确实是有可能不一样甚至出现空的情况，优化的方式有很多，建议在训练的时候见足够多尺寸的样本
