### ISSUE TITLE
Paddle Serving部署报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1178]
在安装好环境，启动独立的标准版检测服务，报错。
![image](https://user-images.githubusercontent.com/43515926/99223847-3ea50a00-2820-11eb-982c-13bc2db4b2a0.png)

**Comment by zcswdt** [comment]
> 这也就是启动成功了呀，你发个请求试试
您好，我发送个请求，然后报这个错。请帮忙看看，多谢
![image](https://user-images.githubusercontent.com/43515926/99339641-7912b380-28c1-11eb-8de7-1974e214c874.png)

**Comment by MissPenguin** [comment]
看样子是结果json解析的时候出得问题，你用doc/imgs下的图片试试能正常解析不，或者把解析前的结果r打印出来看下是啥

**Comment by zcswdt** [comment]
> 看样子是结果json解析的时候出得问题，你用doc/imgs下的图片试试能正常解析不，或者把解析前的结果r打印出来看下是啥

解析出来是这种，
![image](https://user-images.githubusercontent.com/43515926/99480117-6c11c500-2992-11eb-906e-9609dbf51ed3.png)

**Comment by littletomatodonkey** [comment]
看着是返回值为None了，要不试下最新的代码呢？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
