### ISSUE TITLE
picodet_lcnet_x1_0_fgd_layout_table的推理模型的结果不是table类别

### ISSUE THREAD

**Issue by tianwenzhe** [PaddlePaddle/PaddleOCR#11785]
picodet_lcnet_x1_0_fgd_layout_table的推理模型（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppstructure/docs/models_list.md）中，生成的结果类型为text类别，这个只是检测表格，我理解应该只有table类别才对呀

**Comment by cuicheng01** [comment]
看下inference的yaml长啥样呢

**Comment by tianwenzhe** [comment]
infer_cfg.yml内容：
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: PicoDet
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 800
  - 608
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
- stride: 32
  type: PadStride
label_list:
- table
NMS:
  keep_top_k: 100
  name: MultiClassNMS
  nms_threshold: 0.5
  nms_top_k: 1000
  score_threshold: 0.3
fpn_stride:
- 8
- 16
- 32
- 64


版面检测的结果，标签为text




















在 2024-03-21 23:28:59，"cuicheng01" ***@***.***> 写道：

看下inference的yaml长啥样呢

**Comment by UserWangZz** [comment]
这边建议您使用COCO格式数据集重新标注一下，只留下table一个类别，并按照表格识别的文档进行训练
