### ISSUE TITLE
关于自己样本图片训练的几个问题

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1179]
1、基于提供的OCR通用模型基础上，额外增加的自己的样本图片训练时，步骤流程是怎么样的？

在教程“模型训练/评估”中是从一个新的完整训练集开始，不是在已有模型的基础上进行，所以对如何增加自己的样本有所疑惑。不会修改字典文件，只是添加部分样本，按照FAQ里是不需要整体重新训练的。但这个增加的过程是可以直接在已有模型上继续训练，还是需要下载原始的图像和标注数据集，把自己的添加进去再训练等等问题没有弄清。

2、模型包括检测模型和识别模型，当发现图片识别时的Box不准时，是检测模型和识别模型都需要重新训练么？

谢谢

**Comment by LDOUBLEV** [comment]
在你数据上fine-tune时，加载我们训练好的模型即可；

box不准是检测的问题，可重新训练检测模型

**Comment by singlebear** [comment]
> 在你数据上fine-tune时，加载我们训练好的模型即可；
> 
> box不准是检测的问题，可重新训练检测模型

谢谢。
