### ISSUE TITLE
v4使用配置文件训练时backbone中缺少PPLCNeTNew

### ISSUE THREAD

**Issue by Olg1erdzz** [PaddlePaddle/PaddleOCR#11796]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.5  PaddleOCR： 2.7
- 运行指令/Command Code：!python tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml -o Optimizer.base_lr=0.0001- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR-release-2.7/tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR-release-2.7/tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/home/aistudio/PaddleOCR-release-2.7/ppocr/modeling/architectures/__init__.py", line 34, in build_model
    arch = getattr(mod, name)(config)
  File "/home/aistudio/PaddleOCR-release-2.7/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/home/aistudio/PaddleOCR-release-2.7/ppocr/modeling/architectures/base_model.py", line 55, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/aistudio/PaddleOCR-release-2.7/ppocr/modeling/backbones/__init__.py", line 77, in build_backbone
    assert module_name in support_dict, Exception(
AssertionError: when model typs is det, backbone only support ['MobileNetV3', 'ResNet', 'ResNet_vd', 'ResNet_SAST', 'PPLCNet', 'PPLCNetV3', 'PPHGNet_small']

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by changdazhou** [comment]
这个模型的蒸馏有问题，建议使用student和teacher模型哈

**Comment by Olg1erdzz** [comment]
> 这个模型的蒸馏有问题，建议使用student和teacher模型哈

我将原本PPLCNeTNEW的配置修改为      
Backbone:
        name: PPLCNetV3
        scale: 0.75
        det: true
        pretrained: false
后续训练没有影响，但是在导出模型的时候遇到下面有关backbone信息不一致的错误
ppocr WARNING: Student.backbone.blocks2.0.dw_conv.conv_kxk.0.conv._ma_output_scale._scale not in loaded params dict_keys(['Student.backbone.conv1.conv.weight', 'Student.backbone.conv1.bn.weight', 'Student.backbone.conv1.bn.bias', 'Student.backbone.conv1.bn._mean', 'Student.backbone.conv1.bn._variance', 'Student.backbone.blocks2.0.dw_conv.identity.weight', 'Student.backbone.blocks2.0.dw_conv.identity.bias', 'Student.backbone.blocks2.0.dw_conv.identity._mean', 'Student.backbone.blocks2.0.dw_conv.identity._variance', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.0.conv.weight', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.0.bn.weight', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.0.bn.bias', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.0.bn._mean', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.0.bn._variance', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.1.conv.weight', 'Student.backbone.blocks2.0.dw_conv.conv_kxk.1.bn.weight', 'Student.backbone.blocks2.0.dw_conv.conv_
运行了很久也没有导出成功，请问与前面的操作有关联吗

**Comment by changdazhou** [comment]
有关联的，建议使用student和teacher模型哈

**Comment by Olg1erdzz** [comment]
> 有关联的，建议使用student和teacher模型哈

在使用ch_PP-OCRv4_det_cml.yml训练时Architecture.Models.Teacher.pretrained为https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_cml_teacher_pretrained/teacher.pdparams依然会报报AssertionError: when model typs is det, backbone only support ['MobileNetV3', 'ResNet', 'ResNet_vd', 'ResNet_SAST', 'PPLCNet', 'PPLCNetV3', 'PPHGNet_small']这个错误，在ppocr/modeling/backbone的文件下没有PPLCNetNEW这个网络。。。
