### ISSUE TITLE
按照QuickStart走，检测结果全错

### ISSUE THREAD

**Issue by GarrettLee** [PaddlePaddle/PaddleOCR#11798]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

按照这个quickstart走，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/quickstart.md，检测结果全是错的

**Comment by tink2123** [comment]
结果全错的输出是什么呢？ 提供一下测试图片、使用环境说明和复现代码吧。
