### ISSUE TITLE
游戏战绩截图识别

### ISSUE THREAD

**Issue by OswaldoBornemann** [PaddlePaddle/PaddleOCR#11790]
我发现PaddleOCR V4对于游戏战绩截图识别结果不是很好，特别是数字部分，有什么做法可以优化？

**Comment by zhangyubo0722** [comment]
> 我发现PaddleOCR V4对于游戏战绩截图识别结果不是很好，特别是数字部分，有什么做法可以优化？

因为训练数据集中缺少游戏截图的数据，所以对这类图片不好识别，可以准备一些游戏截图标注后在这上面微调
