### ISSUE TITLE
加载模型到指定gpu上,始终只显示在第一张卡

### ISSUE THREAD

**Issue by 2443374695** [PaddlePaddle/PaddleOCR#11799]
for gpu_id in range(num_gpus):  
    paddle.set_device(f'gpu:{gpu_id}')
    global_config = config['Global']
    model = build_model(config['Architecture'])
    load_model(config, model)
加载模型到指定gpu上,始终只显示在第一张卡，并为出现device 1,2 3等
![gpu](https://github.com/PaddlePaddle/PaddleOCR/assets/79261160/0e7d7634-7bac-431e-bfd5-302e13ae7b72)

**Comment by tink2123** [comment]
Paddle 通过环境变量选择某个gpu卡：

export CUDA_VISIBLE_DEVICES=0,1,2,3

**Comment by 2443374695** [comment]
不能将gpu_id 传参数传进去吗

**Comment by tink2123** [comment]
可以传参数进去， 选择指定的卡号就可以了，paddle.set_device("gpu:0")， 但建议通过环境变量指定。

**Comment by 2443374695** [comment]
> 可以传参数进去， 选择指定的卡号就可以了，paddle.set_device("gpu:0")， 但建议通过环境变量指定。
for gpu_id in range(num_gpus):
      paddle.set_device(f'gpu:{gpu_id}')
      global_config = config['Global']
      model = build_model(config['Architecture'])
      load_model(config, model)
   这样循环指定时，为啥只显示第一个GPU，其余卡并未显示

**Comment by UserWangZz** [comment]
可能和paddle代码有关系，建议在paddle仓库下提问，查找原因

**Comment by PineREN** [comment]
竟然不能当作模型加载的参数传进去

**Comment by UserWangZz** [comment]
> > 可以传参数进去， 选择指定的卡号就可以了，paddle.set_device("gpu:0")， 但建议通过环境变量指定。
> > for gpu_id in range(num_gpus):
> > paddle.set_device(f'gpu:{gpu_id}')
> > global_config = config['Global']
> > model = build_model(config['Architecture'])
> > load_model(config, model)
> > 这样循环指定时，为啥只显示第一个GPU，其余卡并未显示

这种情况可以看一下具体显卡的显存是否增加了，一般logger可能只会显示一个显卡

**Comment by PineREN** [comment]
> for gpu_id in range(num_gpus): paddle.set_device(f'gpu:{gpu_id}') global_config = config['Global'] model = build_model(config['Architecture']) load_model(config, model) 加载模型到指定gpu上,始终只显示在第一张卡，并为出现device 1,2 3等 ![gpu](https://private-user-images.githubusercontent.com/79261160/316315869-0e7d7634-7bac-431e-bfd5-302e13ae7b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTE2NjAsIm5iZiI6MTcxNTA1MTM2MCwicGF0aCI6Ii83OTI2MTE2MC8zMTYzMTU4NjktMGU3ZDc2MzQtN2JhYy00MzFlLWJmZDUtMzAyZTEzYWU3YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYWUzNzY1M2YzMmEwOWQ1ZTEwYWUyMTY5NmQ1YTg2MmUyMDFhYWU3OTNiNDNjNTE5NTM5MDM3NzZiODVlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1tzyX3blkiyDSPgCNMjHiU1WEkeOGevT6LiLU46Udw)

阅读相关代码，以及在PPStructure亲测有效：
ppstructure.utility.init_args有个参数gpu_id 可以指定显卡，PPStructure的参数继承了这个init_args，所以可以在加载模型的时候直接
PPStructure(show_log=False,lang = 'ch',gpu_id=device_id)

**Comment by UserWangZz** [comment]
感谢讨论❤️❤️❤️
