### ISSUE TITLE
能否混用V2检测模型和V3识别模型？

### ISSUE THREAD

**Issue by Alanhzl** [PaddlePaddle/PaddleOCR#11803]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

V2（ch_ppocr_mobile_v2.0_det）检测模型对于长句子的图片检测效果会很奇怪，框不到文字上面导致识别也出错了，且耗时比V3检测模型略长一些。
V3（ch_PP-OCRv3_det）检测模型效果不错，就是返回的文字框列表排序好像有一点点问题需要解决一下。

V2（ch_ppocr_mobile_v2.0_rec）识别模型速度较快，识别率也还不错
V3（ch_PP-OCRv3_det）识别模型速度较慢，识别效果也很好

V2总耗时约500ms，V3总耗时约1300ms

slim版本的模型我从训练模型转推理再转nb，使用起来会有异常，比如检测模型会检测到很多很多小框，速度和V3差不多，所以放弃。

后来我尝试了用V3的检测模型，加上V2的识别模型，整体速度和V2持平，但是不会出现V2检测错误导致的识别错误问题，所以我想问能否混用不同版本的模型？

**Comment by TingquanGao** [comment]
可以混用的，但由于v2和v3的检测、识别模块的预处理后处理不同，因此需要修改一下预处理、后处理相关代码。
