### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by Ling1992** [PaddlePaddle/PaddleOCR#11805]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： python:3.9-bullseye
- 版本号/Version：Paddle：2.6.0  PaddleOCR：2.7.1  问题相关组件/Related components：
- 运行指令/Command Code：
```
python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv4_det_infer/ \
                                         --model_filename inference.pdmodel          \
                                         --params_filename inference.pdiparams       \
                                         --serving_server ./ppocr_det_v4_serving/ \
                                         --serving_client ./ppocr_det_v4_client/
```
- 完整报错/Complete Error Message：
```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "/usr/local/lib/python3.9/site-packages/paddle_serving_client/convert.py", line 21, in <module>
     from .io import inference_model_to_serving
   File "/usr/local/lib/python3.9/site-packages/paddle_serving_client/io/__init__.py", line 16, in <module>
     from paddle.fluid import Executor
 ModuleNotFoundError: No module named 'paddle.fluid'
```
paddle.fluid api is removed in 2.6.0

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by TingquanGao** [comment]
由于PaddleServing未对Paddle2.6.0进行适配，有两个建议：
1. 尝试使用Paddle2.5.2 + PaddleOCR2.6分支 + PaddleServing；
2. 尝试使用FastDeploy进行服务化部署：https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/README_CN.md; https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving

**Comment by TingquanGao** [comment]
该问题已close，如有疑问，可以reopen或提issue。
