### ISSUE TITLE
PPstructure(layout=True) issue on html content 

### ISSUE THREAD

**Issue by tzktz** [PaddlePaddle/PaddleOCR#11806]
table_engine = PPStructure(layout=True)
html_table = []
save_folder = './output'
img_path = 'input2.jpg'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

when layout is True i can't extract the html content from that...but when layout is false i can extract the html content using html_content = result[0]['res']['html']...
@tink2123 @ZeyuChen help me to extract the html content when (layout=true)....

**Comment by TingquanGao** [comment]
If you confirm that the input image is table form only, please set the layout to False, otherwise, set True. So do you confirm the type of input image is table form only?

**Comment by tzktz** [comment]
below is my input image that contains table..
![input](https://github.com/PaddlePaddle/PaddleOCR/assets/99823984/7599686e-565d-4c3e-89ed-8ab2bb940531)

**Comment by TingquanGao** [comment]
this image looks like  the content in tabular form. so layout can be set to False.

**Comment by tzktz** [comment]
> this image looks like the content in tabular form. so layout can be set to False.
 
how return res value append into excel ? @TingquanGao

**Comment by TingquanGao** [comment]
You can refer to this document:
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppstructure/table/README.md#4-how-to-use
