### ISSUE TITLE
两张相似的表格图像识别结果不一样

### ISSUE THREAD

**Issue by hustzxl** [PaddlePaddle/PaddleOCR#11807]
1 两张几乎相同的两张照片，识别结果不一样，一张正确，一张错误。
![63](https://github.com/PaddlePaddle/PaddleOCR/assets/13199912/622c4b54-941d-42c1-92d8-5058cc0ebaa6)
这个是原图，大小339* 880
识别结果错误
![63 (2)](https://github.com/PaddlePaddle/PaddleOCR/assets/13199912/6be789da-8c63-4b5f-a83e-6dbd186ff763)

![63](https://github.com/PaddlePaddle/PaddleOCR/assets/13199912/1faffd06-3947-4e1d-8506-433703b7ebd9)
这个是截图截出来的，大小341* 884
识别结果正确
![63 (1)](https://github.com/PaddlePaddle/PaddleOCR/assets/13199912/1e04ce92-0a0d-43c3-ada0-9a617a837285)
2 为什么图片大小需要设置成448 
     # x 输入为 1x3x488x488
    # 经过LCNet之后，记录四部分的输出值，各自Shape如下：
    # 1 x 64 x 122 x 122
    # 1 x 128 x 61 x 61
    # 1 x 256 x 31 x 31
    # 1 x 512 x 16 x 16
改成512不香吗，但是改成512之后第一张图运行失败，表格识别结果为空。
3 运行脚本是
python ppstructure/table/predict_table.py \
    --table_max_len=488 --det_model_dir=inference/ch_PP-OCRv3_det_infer \
    --rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
    --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --rec_char_dict_path=./ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=./ppocr/utils/dict/table_structure_dict_ch.txt \
    --image_dir=63.jpg \
    --output=/root/table
4 另外应该和截图无关，每次不同的截图之后的图片结果都不一样，

**Comment by TingquanGao** [comment]
目前表格识别模效果确实不理想，我们还在努力优化。有进展将在此更新。

**Comment by TingquanGao** [comment]
目前表格识别模型要求训练和推理使用同样的输入尺寸，如果有大尺寸输入的需求，需要重新训练模型。

**Comment by TingquanGao** [comment]
该问题已close，如有疑问，可以reopen或提issue。

**Comment by nissansz** [comment]
这个图片大小，识别前paddle不会自动resize吗？
