### ISSUE TITLE
部分文件中使用 `try_import` 的方法似乎有误

### ISSUE THREAD

**Issue by neteroster** [PaddlePaddle/PaddleOCR#11808]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：/
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：/
- 运行指令/Command Code：/
- 完整报错/Complete Error Message：/

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

如题，例如

https://github.com/PaddlePaddle/PaddleOCR/blob/89e0a15ce7f195026d56189e04a880aa81b107f3/ppocr/utils/utility.py#L111

又如

https://github.com/PaddlePaddle/PaddleOCR/blob/89e0a15ce7f195026d56189e04a880aa81b107f3/ppstructure/pdf2word/pdf2word.py#L26

而 `try_import` 的源码应该在

https://github.com/PaddlePaddle/Paddle/blob/89a60d773893640b7cec91d4857d634a61b02304/python/paddle/utils/lazy_import.py#L21

根据我的理解，应该要这样写：

```python
fitz = try_import('fitz')
```

我确实也在实际使用的时候看到了错误：

```
[2024/03/26 07:26:09] ppocr INFO: **********./C017.pdf**********
Traceback (most recent call last):
  File "/usr/local/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py", line 807, in main
    img, flag_gif, flag_pdf = check_and_read(img_path)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/ppocr/utils/utility.py", line 114, in check_and_read
    with fitz.open(img_path) as pdf:
NameError: name 'fitz' is not defined
```

**Comment by TingquanGao** [comment]
感谢反馈~ 欢迎提PR修复此问题，或者我们之后来修复。

**Comment by jzhang533** [comment]
you are correct, please feel free to create a PR.
