### ISSUE TITLE
PPOCRLabel --lang ch --kie True

### ISSUE THREAD

**Issue by HongkunSun** [PaddlePaddle/PaddleOCR#11814]
你好，我在使用PPOCRLabel进行标注的时候，出现闪退的情况，错误如下：
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
我感觉报错原因是框的坐标不是整数，但是，我将bar.value()改为int(bar.value()),还是会出现这个错误。

**Comment by TingquanGao** [comment]
是必现问题吗？还是偶现的？可能需要debug一下，把相关值print出来检查一下，或许要这样改：`int(bar.value() + bar.singleStep() * units)`

**Comment by HongkunSun** [comment]
你好，int(bar.value() + bar.singleStep() * units) 可以解决闪退的问题！

**Comment by TingquanGao** [comment]
谢谢反馈！我们会尽快修复此问题。
