### ISSUE TITLE
paddle怎么训练docunet? 

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11817]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

https://github.com/teresasun/docUnet.pytorch

**Comment by Sunting78** [comment]
您好 目前暂时没有集成该算法。其他文档矫正算法，如doctr++有开发者在提PR可以参考下。https://github.com/PaddlePaddle/PaddleOCR/pull/11475

**Comment by nissansz** [comment]
谢谢。 有训练好的模型吗？怎么使用doctr++

**Comment by Sunting78** [comment]
暂时没有。使用方法可以参考该PR。由于暂未合入，开发者提交的doctr++代码是否完备以及是否完全能复现，暂时还未知。

**Comment by GreatV** [comment]
可以试试这个仓库 https://github.com/GreatV/DocTrPP

**Comment by nissansz** [comment]
win10能用吗？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Wang Xin  ***@***.***>
 

 
 发送时间: 2024-04-26 21:44:34
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] paddle怎么训练docunet?  (Issue #11817)
 





 可以试试这个仓库 https://github.com/GreatV/DocTrPP

**Comment by GreatV** [comment]
是python实现的，与操作系统无关。

**Comment by nissansz** [comment]
报这个错误，怎么解决？


python predict.py -i "F:\0Table03\3.jpg" -m L:\img2table\DocTrPP-main\best.ckpt -o F:\3result.jpg
Namespace(image='F:\\0Table03\\3.jpg', model='L:\\img2table\\DocTrPP-main\\best.ckpt', output='F:\\3result.jpg')
W0427 08:19:53.655071 50756 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.0, Runtime API Version: 10.2
W0427 08:19:53.673440 50756 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "predict.py", line 69, in <module>
    run(args)
  File "predict.py", line 25, in run
    bm = model(x)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "L:\img2table\DocTrPP-main\GeoTr.py", line 370, in forward
    fmap1 = self.__getattr__(self.encoder_block[0])(fmap)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "L:\img2table\DocTrPP-main\GeoTr.py", line 206, in forward
    pos = self.position_embedding(
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "L:\img2table\DocTrPP-main\position_encoding.py", line 55, in forward
    dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)
  File "D:\Python3.8.8\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (NotFound) There are no kernels which are registered in the elementwise_floordiv operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:341)
  [operator < elementwise_floordiv > error]

**Comment by GreatV** [comment]
是不是paddle版本不对，建议按照 https://www.paddlepaddle.org.cn/ 安装

**Comment by nissansz** [comment]
要哪个版本？requirements里没看到要paddlepaddle 版本
hdf5storage
loguru
numpy
scipy
opencv-python
matplotlib
albumentations

**Comment by GreatV** [comment]
最新版paddle就好了

**Comment by nissansz** [comment]
哦。我装的是paddlepaddle-gpu                              2.3.2
cuda10.2

**Comment by nissansz** [comment]
有没有办法转换成onnx格式使用？怎么用？

**Comment by UserWangZz** [comment]
问题非paddleocr问题，此处关闭该issue，可在具体仓库中重开issue提问
