### ISSUE TITLE
发现下载下面的中文字典“chinese_cht_dict.txt”里面缺少很多常用的汉字 

### ISSUE THREAD

**Issue by hds1999** [PaddlePaddle/PaddleOCR#11816]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem：

发现下载的中文字典“chinese_cht_dict.txt”里面缺少很多常用的汉字 

有以下汉字没有找到：

蔼碍爱肮袄奥懊坝罢摆败颁办绊帮绑谤剥饱宝报辈贝狈备惫绷笔毕毙币闭边编贬变辩辫标膘鳖别瘪濒滨宾饼并拨驳补财睬参蚕残惭惨灿苍舱仓沧厕侧册测层搀掺蝉馋缠铲产阐颤猖场尝长偿肠厂畅钞车彻尘陈衬撑称惩诚迟驰耻齿冲虫宠畴筹绸橱厨锄雏础储触处揣传疮闯创锤纯绰辞词赐聪葱囱从丛凑窜错达呆带贷担单掸胆诞弹当挡党荡档捣岛祷导盗灯邓敌涤递缔颠点垫电淀钓调谍叠钉顶锭订丢东动栋冻独读赌镀锻断缎兑队对吨顿钝夺跺堕鹅额讹恶饿儿尔饵贰发罚阀矾烦贩饭访纺飞诽废费纷坟奋愤粪枫锋风疯冯缝讽凤肤辐抚辅赋复负妇缚咐该钙盖杆赶秆冈刚钢纲岗镐搁鸽阁个给埂宫巩贡钩沟构购够顾挂关观馆惯贯广规归龟闺轨诡贵刽滚锅国过骇韩汉号鹤贺横恒轰鸿红壶护沪户哗华画话怀坏欢环还缓换唤痪焕涣黄谎挥辉毁贿秽会汇讳诲绘荤浑获货祸击机积饥迹讥鸡绩辑级挤剂济计记际继纪夹荚颊贾钾价驾歼监坚间艰奸茧检碱拣捡简俭减荐鉴践贱见键舰剑渐溅涧将浆蒋桨奖讲酱胶浇骄娇搅矫侥脚饺缴绞轿较阶节杰洁结诫届紧锦仅谨进晋尽劲荆兢茎鲸惊经颈静镜径竞净纠旧驹举据锯惧剧鹃绢觉决诀绝钧军骏开揩凯颗壳课垦恳吭抠库裤夸胯块宽矿旷况亏窥溃扩阔蜡莱来赖蓝栏拦篮兰澜揽览懒缆烂滥捞劳涝乐垒类泪厘篱离鲤礼栗丽厉励砾历沥隶俩联莲连镰怜敛脸链恋炼练粮凉两辆谅疗辽潦镣猎临邻鳞凛赁龄铃灵岭领馏刘龙聋咙笼垄拢楼娄搂篓芦卢颅庐炉卤虏鲁赂录陆驴吕铝侣屡缕虑滤绿峦乱抡轮伦仑沦论萝罗逻锣箩骡骆络妈玛码蚂马骂吗买麦卖迈脉瞒馒蛮满猫锚铆贸没门闷们锰梦谜弥觅绵缅庙灭悯闽鸣铭谬谋亩呐钠纳难挠脑恼闹馁内拟腻蔫撵酿鸟聂镊柠狞宁拧泞钮纽脓浓农疟诺欧鸥殴呕盘庞抛赔喷鹏骗飘频贫苹凭评泼颇扑铺仆谱栖脐齐骑岂启气弃牵铅迁签谦钱钳潜浅谴枪呛墙强抢锹桥乔侨翘窍窃钦亲寝轻氢倾顷请庆琼穷趋区蛆躯驱权劝瘸却鹊确让饶扰绕热韧认纫荣绒软锐闰润洒萨赛叁伞丧骚扫涩杀刹纱筛晒删闪陕赡伤赏晌烧绍赊摄设呻绅审婶肾渗声绳胜圣师狮湿诗尸时蚀实识驶势适释饰视试寿兽枢输书赎属术树竖数帅双谁税顺说硕烁丝饲耸颂讼诵苏诉肃虽随岁孙损笋缩琐锁态摊贪瘫滩坛谭谈袒叹汤烫涛讨腾誊题屉条贴铁厅听铜捅统头秃图涂团颓蜕脱鸵驮驼椭洼袜弯湾顽挽惋万网违围为维苇伟伪纬谓卫温闻纹稳问蜗涡窝呜乌诬无芜吴坞雾务误锡牺袭习铣戏细虾辖峡侠狭厦吓锨鲜纤贤衔闲显险现献县馅宪线厢镶乡详响项萧嚣销晓啸协挟携胁谐写泻谢锌衅兴汹锈绣虚须许叙绪续轩悬选癣学勋询寻驯训讯逊压鸦鸭哑亚讶烟盐严颜阎艳厌砚唁谚验鸯杨扬阳痒养样摇遥窑谣舀药爷页业叶医遗仪蚁艺亿忆义议谊译异绎阴银饮隐樱婴鹰应缨莹萤营荧蝇赢颖哟拥踊咏优忧邮犹诱于舆鱼渔娱屿语狱誉预鸳渊辕园员圆缘远约跃钥粤悦阅匀陨运蕴酝晕韵杂灾载攒暂赞赃脏凿枣灶责择则泽贼赠轧铡闸栅诈斋债毡盏斩崭栈战绽张涨帐账胀赵辙这贞针侦诊镇阵挣睁狰争怔郑证织职执纸挚掷帜质滞钟终种肿众轴皱昼骤猪诸烛拄嘱贮铸筑注驻专砖转赚桩庄装妆壮状锥赘坠缀谆浊资踪综总纵诅组钻凫禀谒荞荠莺叽唠嗤嘁岖猬馍悴憔缤缭缰杈桦榄檩昙牍肴胧飒铐铛锉秫鸠鹉鹦瘾癞裆笤筝箫麸跷踱躏雳鲫鳄鳍鬓

**Comment by Sunting78** [comment]
您好，请提供下您下载的url，我们确认下。

**Comment by hds1999** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppocr/utils/dict/chinese_cht_dict.txt
