### ISSUE TITLE
Inference with a pre-trained model

### ISSUE THREAD

**Issue by xamapl99** [PaddlePaddle/PaddleOCR#11813]
Hi, 

I'm trying to inference with a pre-trained model, but I get this error: ValueError: not find model.pdmodel or inference.pdmodel

How can i get the .pdmodel when I do the train?

Thank's

**Comment by TingquanGao** [comment]
Please provide the specific steps for reproducing the error.

**Comment by TingquanGao** [comment]
The issue has been closed. If have any questions, you can reopen or new issue.
