### ISSUE TITLE
请问c++中应该怎么修改，c++中好像没有rec_char_dict_path的参数

### ISSUE THREAD

**Issue by fyclver** [PaddlePaddle/PaddleOCR#11827]
试下这个命令，修改字典为英文：

```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_195.jpg" --det_model_dir="./inference/en_PP-OCRv3_det_infer/" --rec_model_dir="./inference/en_PP-OCRv3_rec_infer/" --rec_char_dict_path="ppocr/utils/en_dict.txt"
```

_Originally posted by @tink2123 in https://github.com/PaddlePaddle/PaddleOCR/issues/6760#issuecomment-1172028524_

**Comment by cuicheng01** [comment]
您可以参考这里哈：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/cpp_infer/src/args.cpp#L49

**Comment by GreatV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/6ed5562cedce18f0313d3b83271986dd6c136871/deploy/cpp_infer/include/ocr_rec.h#L48
