### ISSUE TITLE
Low per char confidence score on customized dataset when the text is clear.

### ISSUE THREAD

**Issue by OwenHuaKargo** [PaddlePaddle/PaddleOCR#11821]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：  PaddleOCR：V4 问题相关组件/Related components：recognition
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by OwenHuaKargo** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/105018891/c88de2d3-c577-454e-b97f-78bd6705e9e1)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/105018891/368a35f1-f423-4d6a-ac38-982b9602575e)

**Comment by OwenHuaKargo** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/105018891/ad785760-19d6-4261-99e8-4aaf85a3bc7c)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/105018891/a07b0b74-ca29-4683-98a1-f62e015f8e13)

**Comment by UserWangZz** [comment]
Do you mean that individual characters score lower than most other characters？

**Comment by OwenHuaKargo** [comment]
@UserWangZz Yes

**Comment by UserWangZz** [comment]
> @UserWangZz Yes

This is normal. The model will always encounter uncertainties. It may be characters that are difficult to distinguish, or it may be padding at the beginning and end of characters.

**Comment by OwenHua666** [comment]
Thank you for your replay. What do you mean by the padding? Why does the uncertainty happen for clear characters?

**Comment by UserWangZz** [comment]
Padding refers to the blank area at the beginning and end of  the character. Different padding sizes will also affect the accuracy of recognition.

Regarding the second question, I cannot guarantee whether it is correct. It may be the angle of the characters, the barcode above, etc. There are many factors that affect the model's judgment of characters.

Did you segment the characters and calculate the confidence of each character?

**Comment by OwenHua666** [comment]
Yes. I segmented to get the per character confidence.

**Comment by UserWangZz** [comment]
> ![image](https://private-user-images.githubusercontent.com/105018891/317487908-ad785760-19d6-4261-99e8-4aaf85a3bc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA1NjMsIm5iZiI6MTcxNTE1MDI2MywicGF0aCI6Ii8xMDUwMTg4OTEvMzE3NDg3OTA4LWFkNzg1NzYwLTE5ZDYtNDI2MS05OWU4LTRhYWY4NWEzYmM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNjM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjk4MTM2ZDAxM2NlNWM3YzcxOGQzZjAxM2UzNjAzMTMwZjVkMDI4N2E0YTZkZjFjNWRjMWNlNjg2NDVkZThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jzbY8aCOCdt9xiH4AcDONwlySZUUqz390TMvU93rCfs) ![image](https://private-user-images.githubusercontent.com/105018891/317488027-a07b0b74-ca29-4683-98a1-f62e015f8e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA1NjMsIm5iZiI6MTcxNTE1MDI2MywicGF0aCI6Ii8xMDUwMTg4OTEvMzE3NDg4MDI3LWEwN2IwYjc0LWNhMjktNDY4My05OGExLWY2MmUwMTVmOGUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNjM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDEyNDVhNTEwMmIwOWI5NjM0OTdiYzU5MWVjOGFiZTliMTQwZWVkMzIwMDBiMTY3N2I2NmVjZDJhNGJhNWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fI5IhuXpbycjVNsYQfio4W88oBLTRprcAkBHjQkGkWo)

So for this picture, it is very likely that the barcode above the first 8 affects the recognition of the model, because there is no barcode above the second 8

**Comment by OwenHuaKargo** [comment]
Two more follow-up questions. 1. how do we improve those clear characters with low confidence scores? 2. If we have leading padded space or trailing padded space, should I add extra spaces in the labeling step for my customized dataset? What if there is more than one space between two words in my dataset in a single text strip? Eg. "Name:         Owen". Should I have more than one space in between in the labeling?

**Comment by UserWangZz** [comment]
The confidence scores is very important in your project? What I mean is that although the confidence score is low, the model did not recognize any errors. And in situations where the image is relatively clear, recognition errors are generally rare.

**Comment by OwenHuaKargo** [comment]
Yes, they are extremely important. There are cases in which we need to filter out the low-conf chars.

**Comment by OwenHuaKargo** [comment]
Can you also give some suggestions for the multiple-spaces scenarios? Thx@

**Comment by UserWangZz** [comment]
> ![image](https://private-user-images.githubusercontent.com/105018891/317487908-ad785760-19d6-4261-99e8-4aaf85a3bc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDU1ODAsIm5iZiI6MTcxNTMwNTI4MCwicGF0aCI6Ii8xMDUwMTg4OTEvMzE3NDg3OTA4LWFkNzg1NzYwLTE5ZDYtNDI2MS05OWU4LTRhYWY4NWEzYmM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMTQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWI4MTA1MGExYzBjM2M4ZDg1MzA3M2I0ZjJhOTI0YmRjYTY4OGE2YzI5ZjZhZjEzYTE5Y2Y2OTRiNTUxYTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.apJ7eWmmipPHlLKGSKCtvO2t9OTYsXWztFQboS0BA7w) ![image](https://private-user-images.githubusercontent.com/105018891/317488027-a07b0b74-ca29-4683-98a1-f62e015f8e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDU1ODAsIm5iZiI6MTcxNTMwNTI4MCwicGF0aCI6Ii8xMDUwMTg4OTEvMzE3NDg4MDI3LWEwN2IwYjc0LWNhMjktNDY4My05OGExLWY2MmUwMTVmOGUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMTQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGU0MDA4OWIwOGI1Y2FkMTY3N2UxNGE1OTE3NzllNGM1Y2FiODEzMGY5MGNhODFlNTc0N2VlZTRmYTYyZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q_9n85ZC7iUkFvyFmti4VvPWSGLg3VC_sVIJXgzCVz8)

About this pic, for the first 8, can you segment it and deal it like the second 8, just del the bar-code which is above the num, then inference this 8, and check the confidence score. Let's check whether the barcode above the number affects the recognition of the model.

**Comment by OwenHuaKargo** [comment]
Do we have a more general fix for the above problem? The first image doesn't have a barcode.

**Comment by OwenHuaKargo** [comment]
Would you be able to help with the multiple-spaces scenario? Eg. "Owen        Hua" in a single quad polygon. How many spaces should I label for fine-tuning the recognition model?

**Comment by UserWangZz** [comment]
> Would you be able to help with the multiple-spaces scenario? Eg. "Owen Hua" in a single quad polygon. How many spaces should I label for fine-tuning the recognition model?

Sorry, I didn't understand your question? Can you explain it in more detail?

**Comment by OwenHua666** [comment]
There are more than one space in between my first and last name. How would I label it?

**Comment by UserWangZz** [comment]
you can set `use_space_char: true` make the model to predict 'space' in rec stage
