### ISSUE TITLE
新发布的2.7.2版本是否不包含2.7.1的升级内容

### ISSUE THREAD

**Issue by mandog747** [PaddlePaddle/PaddleOCR#11824]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

2.7.1 的release log里面有savefile选项，新发布的2.7.2的whl安装后无法启用

**Comment by jzhang533** [comment]
Oh, there is a release/2.7.1 branch. I didn't notice that when releasing 2.7.2 .
Branch management in this repository is not adopting best practices I've been familiar with.
Will introduce branch release/2.7.1 into release/2.7, and create a new release (version: 2.7.4).
the two branches are diverged, so may need some time.

**Comment by jzhang533** [comment]
fixed by #11831 , and a new release: https://pypi.org/project/paddleocr/2.7.4/

**Comment by mandog747** [comment]
感谢发布2.7.4，不过更新了这版whl后，出现utility.py报错，230行多了一个g

> fixed by #11831 , and a new release: https://pypi.org/project/paddleocr/2.7.4/

**Comment by jzhang533** [comment]
2.7.5 fixed this
