### ISSUE TITLE
c++英文检测和识别模型时，命令行窗口出现了乱码

### ISSUE THREAD

**Issue by fyclver** [PaddlePaddle/PaddleOCR#11823]
c++在运行英文检测和识别模型时，命令行窗口出现了乱码，是什么问题？不论是使用ASCII还是UTF-8都会出现乱码。

**Comment by cuicheng01** [comment]
您好，是在什么系统上预测的呢？采用的是PaddleOCR默认的预测代码吗？命令方便贴一下吗
