### ISSUE TITLE
运行命令行窗口时，命令行输出乱码。

### ISSUE THREAD

**Issue by fyclver** [PaddlePaddle/PaddleOCR#11825]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 c++
- 版本号/Version：Paddle：c++预测库cpu_avx_mkl 2.3.2版本 PaddleOCR2.6  PaddleOCR： 问题相关组件/Related components：英文检测和识别模型
- 运行指令/Command Code：.\build\Release\ppocr.exe system --det_model_dir=D:\learning\cpp\en_PP-OCRv3_det_slim_infer --rec_model_dir=D:\learning\cpp\en_PP-OCRv4_rec_infer --image_dir=D:\learning\cpp\PaddleOCR\doc\imgs\test2.bmp
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by cuicheng01** [comment]
您好，麻烦问下系统的编码方式是什么呢？
