### ISSUE TITLE
 expected an indented block (utility.py, line 230)

### ISSUE THREAD

**Issue by Ymars1990** [PaddlePaddle/PaddleOCR#11837]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

paddleocr 2.7.4 版本必现这个bug

**Comment by satvik-27199** [comment]
!python3 -m pip install paddlepaddle-gpu
!pip install "paddleocr>=2.0.1"
from paddleocr import PaddleOCR,draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory

Error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-6-b73ef44eaf62>"](https://localhost:8080/#), line 1, in <cell line: 1>
    from paddleocr import PaddleOCR,draw_ocr

  File "/usr/local/lib/python3.10/dist-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *

  File "/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py", line 53, in <module>
    from ppstructure.utility import init_args, draw_structure_result

  File "/usr/local/lib/python3.10/dist-packages/paddleocr/ppstructure/utility.py", line 230
    g            avg_char_width = (bbox_x_end - bbox_x_start) / len(rec_str)
                                                                            ^
IndentationError: expected an indented block after 'else' statement on line 229

**Comment by Ymars1990** [comment]
> !python3 -m pip install paddlepaddle-gpu !pip install "paddleocr>=2.0.1" from paddleocr import PaddleOCR,draw_ocr
> 
> ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
> 
> Error: Traceback (most recent call last):
> 
> File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code exec(code_obj, self.user_global_ns, self.user_ns)
> 
> File [""](https://localhost:8080/#), line 1, in <cell line: 1> from paddleocr import PaddleOCR,draw_ocr
> 
> File "/usr/local/lib/python3.10/dist-packages/paddleocr/**init**.py", line 14, in from .paddleocr import *
> 
> File "/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py", line 53, in from ppstructure.utility import init_args, odraw_structure_result
> 
> File "/usr/local/lib/python3.10/dist-packages/paddleocr/ppstructure/utility.py", line 230 g avg_char_width = (bbox_x_end - bbox_x_start) / len(rec_str) ^ IndentationError: expected an indented block after 'else' statement on line 229

only V 2.7.4 happpens it,you can install 2.7.3,it works

**Comment by jzhang533** [comment]
my bad, has been fixed by #11836, and version v2.7.4 is yanked on pypi.

**Comment by Ymars1990** [comment]
> my bad, has been fixed by #11836, and version v2.7.4 is yanked on pypi.

rollback veriosn works, hope new version to publish
