### ISSUE TITLE
基于PP-OCRv3的手写文字识别权重文件

### ISSUE THREAD

**Issue by HongkunSun** [PaddlePaddle/PaddleOCR#11830]
你好，基于PP-OCRv3的手写文字识别训练好的模型权重文件 可以提供一下吗？

**Comment by tink2123** [comment]
如需获取已训练模型，请加入PaddleX官方交流频道，获取20G OCR学习大礼包（内含《动手学OCR》电子书、课程回放视频、前沿论文等重磅资料）

PaddleX官方交流频道：https://aistudio.baidu.com/community/channel/610

**Comment by HongkunSun** [comment]
你好，我加入了频道，也在<模型需求反馈>中进行了询问，过去几天了已经，没有得到回复，希望你能帮我解决一下该模型需求。
