### ISSUE TITLE
我想单独检测英文单词，请问应该怎样做？

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1183]
您好，我想训练只检测英文单词的检测框，一个单词一个框，请问应该怎么样进行训练？之前对文本检测中mv3模型进行finetune，但是loss值减少，准确度却一直为0，训练结束，随意预测一张图片，检测的内容五花八门，就是没有正确的。请问检测框应该怎样不检测出长而是单独检测单个单词？谢谢！
![捕获1](https://user-images.githubusercontent.com/51456283/99343659-4967a980-28c9-11eb-9cd5-a5d0b360d0f5.PNG)

**Comment by LDOUBLEV** [comment]
训练数据需要是单词级别的标注，而不是句子级别的标注

之前应该是没训练好，可以检查下原因，用训练好的模型测试训练数据是否能准确检测到

**Comment by tyy2tyy** [comment]
我之前是这样标注的，请问可以吗？
![捕获](https://user-images.githubusercontent.com/51456283/99355896-1383ee80-28e4-11eb-9218-09427f4e1774.PNG)

**Comment by MissPenguin** [comment]
> 我之前是这样标注的，请问可以吗？
> ![捕获](https://user-images.githubusercontent.com/51456283/99355896-1383ee80-28e4-11eb-9218-09427f4e1774.PNG)

可以的
