### ISSUE TITLE
我想测试0-45度, 45-90,95-135,135-180, 180-225, 215-270, 315-360之间不同旋转角度的文字角度方向，然后文字矫正图像，怎么判断？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11848]
我想测试0-45度, 45-90,95-135,135-180, 180-225, 215-270, 315-360之间不同旋转角度的文字角度方向，然后文字矫正图像，怎么判断？

**Comment by changdazhou** [comment]
参考文本方向识别训练支持多方向分类的文本方向分类器哈https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md

**Comment by GreatV** [comment]
> PaddleOCR系统内， 文字检测之后得到的文本行图片经过仿射变换之后送入识别模型，此时只需要对文字进行一个0和180度的角度分类，因此PaddleOCR内置的 文本方向分类器只支持了0和180度的分类。

**Comment by nissansz** [comment]
这个0-180度，只是对每个文本行进行分类？有没有整页文档的角度判定方法？

**Comment by GreatV** [comment]
@nissansz 可以参考这里 [Awesome Document Image Rectification](https://github.com/fh2019ustc/Awesome-Document-Image-Rectification)

**Comment by nissansz** [comment]
谢谢。这个demo有本地python代码吗？https://felixhertlein.de/docrefine/home

**Comment by GreatV** [comment]
@nissansz 可以参考 [Inv3D - Models](https://github.com/FelixHertlein/inv3d-model)，目前比较好的是doctr++，也可以看下。

**Comment by nissansz** [comment]
谢谢。有没有现成的转换好的onnx可以用的？

**Comment by GreatV** [comment]
@nissansz  好像得自己导一下

**Comment by nissansz** [comment]
只会用paddle自带的导出工具，不会其它onnx导出

**Comment by GreatV** [comment]
@nissansz 可以去那个仓库的issue区问一问

**Comment by nissansz** [comment]
好的，谢谢

**Comment by nissansz** [comment]
https://github.com/fh2019ustc/DocTr 这里好像有预训练模型和代码，不会转onnx，不知道怎么用onnx
