### ISSUE TITLE
Issue regrading importing PaddleOCR

### ISSUE THREAD

**Issue by priyanshudutta04** [PaddlePaddle/PaddleOCR#11846]
-System Environment：Google Collab

-Version PaddleOCR：2.7.5

- Command Code：from paddleocr import PaddleOCR

- Complete Error Message：

6 from google.colab import files
      7 
----> 8 from paddleocr import PaddleOCR
      9 
     10 ocr = PaddleOCR(use_angle_cls=True,lang='en')

1 frames
[/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py](https://localhost:8080/#) in <module>
    573 
    574 
--> 575 class PaddleOCR(predict_system.TextSystem):
    576     def __init__(self, **kwargs):
    577         """

NameError: name 'predict_system' is not defined

**Comment by AliBasarann** [comment]
I resolved the issue and opened a pr #11847

**Comment by ping40** [comment]
I get the same issue too.

**Comment by UserWangZz** [comment]
perdict_system在tools/infer中，可以尝试重新倒入一下
