### ISSUE TITLE
rec 多语种模型，怎样才能达到纯英文模型的准确率？或者有没有办法在检测文本行时按语种检测，分开语种识别？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11852]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

rec 多语种模型，怎样才能达到纯英文模型的准确率？或者有没有办法在检测文本行时按语种检测，分开语种识别？

**Comment by UserWangZz** [comment]
这个需要您根据需求自己实现了，这边建议可以增加一个分类器，将语种进行一个分类然后分开识别

**Comment by nissansz** [comment]
1万条验证









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: WangZ  ***@***.***>
 

 
 发送时间: 2024-04-28 12:13:38
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] rec 多语种模型，怎样才能达到纯英文模型的准确率？或者有没有办法在检测文本行时按语种检测，分开语种识别？ (Issue #11852)
 





 这个需要您根据需求自己实现了，这边建议可以增加一个分类器，将语种进行一个分类然后分开识别
