### ISSUE TITLE
KIE信息抽取max_seq_len大于512时信息缺失的问题有优化么，是否可以增大max_seq_len？

### ISSUE THREAD

**Issue by shuihsaiu** [PaddlePaddle/PaddleOCR#11855]
max_seq_len大于512时信息缺失，尝试1024失败
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/70890342/d0164452-88f5-4e40-a2ae-4f1340bb00bb)

**Comment by kalelgwapo** [comment]
Hi, I also have the same question. Hoping to get some answer. Specifically is there a way to increase max_seq_len for KIE?

**Comment by UserWangZz** [comment]
这个可能与模型结构有关系吧

**Comment by tran601** [comment]
请问有解决办法了吗，最近也是被这个问题困扰

**Comment by tran601** [comment]
> 请问有解决办法了吗，最近也是被这个问题困扰

我在vqa_layoutlm.py文件中找到了调用的模型，这些模型是在paddlenlp.transformers中，在里面我找到了LayoutXLMPretrainedModel这个类，kie任务默认用了这里面的配置
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/06acc9e2-72b2-4aee-a0f5-c3d8f945f7f2)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/eb736084-5878-4262-adfd-3af13b3e8d2a)

**Comment by UserWangZz** [comment]
KIE模型使用的是paddlenlp的方法，可以去paddlenlp仓库提问，如何修改模型结构
