### ISSUE TITLE
Text recognition model fine-tuning

### ISSUE THREAD

**Issue by BuiPhamSonHa** [PaddlePaddle/PaddleOCR#11851]
I tried following the instructions in link : https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_en/finetune_en.md  to train fine-tuning recognition on my dataset .  But when I test it with the inference model , It's only good with the characters I've trained, but with the characters I haven't trained, it misreads a lot . I'm very happy to receive comments from everyone , thanks.

**Comment by lamld203844** [comment]
@BuiPhamSonHa b cung dang finetune paddleOCR recognition model phải ko? B có gặp lỗi này giống mình ko? Giúp mình với 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/78334320/cb351bbc-214f-4e47-bcd6-4603f5b3e187)

**Comment by lamld203844** [comment]
Mình cũng đang làm project về information extraction. Với characters mình dùng transformerOCR pretrained từ vietOCR thấy khá ổn bạn á. Bạn có thể tham khảo

**Comment by BuiPhamSonHa** [comment]
@lamld203844 hi bạn , mình chưa gặp lỗi như vậy bao giờ , nhưng mình đọc có vẻ như ParallelEnv đang ko có thuộc tính _device_id kia , bạn thử xem lại class  ParallelEnv hay thử sửa _device_id thành device_id như gợi ý xem được khong nhé

**Comment by lamld203844** [comment]
thanks b nha. Lỗi của mình là chạy bằng GPU mà install paddlepaddle thay vì paddlepaddle-gpu

**Comment by Vamshi-Kumar-tech** [comment]
change your paddlpaadle-gpu version, which ever is compatable in your system

**Comment by khanhjt** [comment]
> Mình cũng đang làm project về information extraction. Với characters mình dùng transformerOCR pretrained từ vietOCR thấy khá ổn bạn á. Bạn có thể tham khảo (I am also doing a project about information extraction. For characters, I used transformerOCR pretrained from vietOCR and found it quite good. You can consult)

hi bạn, b có thể share phần notebook **dùng transformerOCR pretrained từ vietOCR** mình tham khảo với được không?
