### ISSUE TITLE
ser关键信息抽取模型。使用PPOCRLable标注。如果内容有多行的情况怎么标注呢？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#11853]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
ser关键信息抽取。如果是一格的内容多行的怎么标注呢？不如下面的图片。
备注的内容可能有一行 或者多行。关键词key_cls要怎么取呢？标注只能标注一行的。
1.关键词都叫备注，那么关键信息中就有多个备注。但是没有顺序。无法拼接在一起
2.叫备注1，备注2，备注4。。。。 后期在自己拼接起来吗？有点不智能
3.还是有什么其他解决方案吗？？？？

![2](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/5e4fab91-5ef6-4c78-be4b-c85f8759790a)

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by lxw316830** [comment]
17610296011加我，我也在做这个，讨论一下

**Comment by newlxj** [comment]
> 17610296011加我，我也在做这个，讨论一下

同样类似问题

**Comment by UserWangZz** [comment]
我是多行文本，每行一个标注，但是表格结构与表格保持一致
