### ISSUE TITLE
What version of `opencv-python-headless` should I use?

### ISSUE THREAD

**Issue by annahung31** [PaddlePaddle/PaddleOCR#11858]
When installing paddleocr=2.7.5 and run ` paddleocr --help`,  I'll face the error as following:

```
  File "/usr/local/lib/python3.8/dist-packages/cv2/typing/__init__.py", line 168, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```

If I then install `opencv-python-headless<4.3`, the error will go away, but I'll face another error:

```
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'opencv-python-headless>=4.5' distribution was not found and is required by pdf2docx
```

What should I do?

**Comment by yaowt05** [comment]
You can uninstall opencv-python, opencv-python-headless and opencv-contrib-python that come with paddleocr，and install only the latest version of opencv-contrib-python (4.9)，and do not use paddleocr==2.7.4 and 2.7.5 with bug, just use paddleocr==2.7.3

**Comment by annahung31** [comment]
Thanks for the advice! 
I ended up using paddleocr==2.7.2 with opencv-fixer and it works too.

My setting:
```
pip install "paddlepaddle-gpu==2.5.0"
pip install paddleocr==2.7.2
pip install opencv-fixer==0.2.5
python -c "from opencv_fixer import AutoFix; AutoFix()"
```
