### ISSUE TITLE
图像Layout检测，一行文字丢失前面部分

### ISSUE THREAD

**Issue by xuwinrar** [PaddlePaddle/PaddleOCR#11869]
版本识别结果如图（粗红框部分文字前半部分丢失）：

![1712114916588](https://github.com/PaddlePaddle/PaddleOCR/assets/12391108/ed8a6093-7b0a-40f1-9a35-ad27da9183a9)

原图如下：
![1712115073155](https://github.com/PaddlePaddle/PaddleOCR/assets/12391108/b446f62b-b088-4ee3-bb64-fc49e9465011)

使用版本：
paddleocr                2.7.0.3
paddlepaddle             2.5.1

模型配置：
使用默认值
PP-StructureV2
            'layout': {
                'en': {
                    'url':
                    'https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_infer.tar',
                    'dict_path':
                    'ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt'
                },
                'ch': {
                    'url':
                    'https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar',
                    'dict_path':
                    'ppocr/utils/dict/layout_dict/layout_cdla_dict.txt'
                }
            }

参数设置：
table_engine = PPStructure(recovery=True, show_log=True, image_orientation=False, ocr_version='PP-OCRv4',
                           det_db_thresh=0.1, det_db_box_thresh=0.4, det_db_unclip_ratio=2, det_db_score_mode='slow', det_limit_side_len=3330, use_dilation=True, use_mkldnn=True)

试过调整参数但都无效。请问这个问题如何解决？谢谢！

**Comment by xuwinrar** [comment]
@Sunting78 , need your help, please respond thanks!

**Comment by RussellLuo** [comment]
@xuwinrar 这里有个修复PR：#11916，可以测试下。
