### ISSUE TITLE
有没有将paddle模型转换成bin加速的方法？能不能加速？或者使用C语言加速？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11861]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

有没有将paddle模型转换成bin加速的方法？能不能加速？或者使用C语言加速？

**Comment by GreatV** [comment]
可以转成其他后端推理，像onnx、trt、openvino之类的

**Comment by nissansz** [comment]
我看 tr ocr用的是bin 格式，非常快。
我现在在用onnx，感觉不够快。onnx是不是可以用python调用其它C或C++程序版的onnx推理代码来加速？怎么写？

另外这个onnx识别单行文本时，发现db检测结果，四周白边padding对结果准确性有影响，
目前想到的是用0-10像素进行投票选出最准结果，有没有其它好方法？

有时准确率显示0.99以上都不一定是准确结果，有可能0.7左右的反而是正确的(少数情况)

**Comment by GreatV** [comment]
onnx 可以直接用c++写推理代码

**Comment by nissansz** [comment]
检测模型参数调整，关键是不同图，不同参数结果不一样，要自己用代码多识别几个图，选出最好的结果。

不会C++代码，有没有现成的C++代码，可以用python来执行C++从而用其加速onnx推理

**Comment by GreatV** [comment]
参考这里修改一下就可以了 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/deploy/cpp_infer

**Comment by nissansz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/cpp_infer/docs/windows_vs2019_build.md

一大堆环境要配置，这个C++比python推理能快多少？

**Comment by UserWangZz** [comment]
这个我们也没有测试过，您可以尝试看看
