### ISSUE TITLE
想让文字预测的概率显示在图片上

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleOCR#1186]
大佬，您好！
我想在predict_system.py预测结果中显示文字预测的概率值。请问应该在哪儿改

**Comment by littletomatodonkey** [comment]
可以修改下这个函数的可视化过程

https://github.com/PaddlePaddle/PaddleOCR/blob/4cf85329cdd24eb206afec6c1193f36fc0134fe4/tools/infer/predict_system.py#L163

**Comment by terrancraft** [comment]
谢谢大佬!

**Comment by terrancraft** [comment]
> 可以修改下这个函数的可视化过程
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/4cf85329cdd24eb206afec6c1193f36fc0134fe4/tools/infer/predict_system.py#L163

不好意思，再多问一个问题~
crnn网络最后score的输出结果在哪儿找？
