### ISSUE TITLE
有个有趣的现象，英文单词中的大写i，自己训练的模型都识别成了小写，这种是怎么回事？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11862]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/6fb7efa8-29cb-468a-9eb8-a264a0abfbb9)

**Comment by TingquanGao** [comment]
使用的私有数据集？数据集标注是否正确呢？

**Comment by nissansz** [comment]
随机生成的数据。
另外哪里有好的各个语种的词库，可以用来生成训练数据吗？

**Comment by TingquanGao** [comment]
抱歉，多语种词库的话，我们也没有这方面的信息。

**Comment by nissansz** [comment]
形似的字符，加大比例可以改善准确率？这个形似字符比例一般要加到多少？

**Comment by TingquanGao** [comment]
这个只能根据经验不断尝试，建议先分析一下当前的比例。

**Comment by nissansz** [comment]
如果用字典里的单字符随机组成句子，而不用书籍之类的句子，对训练结果有什么影响吗？

**Comment by TingquanGao** [comment]
会有一点影响。使用常见的句子，可以更好利用上下文信息来做预测，如果是单字符的话，上下文信息是无意义的。
