### ISSUE TITLE
关于不同方向上文本识别的一些疑问

### ISSUE THREAD

**Issue by dagongji10** [PaddlePaddle/PaddleOCR#1187]
![image](https://user-images.githubusercontent.com/15357846/99389304-cd458400-2911-11eb-8409-0b03d05e767a.png)
如上图所示，我使用PaddleOCR官方提供测测试页面测试了四种不同的情况，产生了一些疑问：
1. 文本方向分类器能够识别的文本方向，是类似于第 1/4 句这样“从左往右书写最后旋转一定角度”的情况，还是类似于第 2 句这样“从上往下书写”的情况？或者说这两种方向都能识别？那么方向分类的结果是什么？任意角度还是只有水平和竖直两种分类？
2. 对于第 2 句这样的情况，是如何识别的？是重新训练一个CRNN的模型吗？接收的输入是（280， 32， 3）？
3. 对于第 3 句这样的情况，为什么能检测到文本，但是识别结果没有显示？是通过阈值过滤掉了？

**Comment by littletomatodonkey** [comment]
1. 这种都可以识别的，属于横排文本，检测过程就会矫正，然后再使用方向分类器判断0度还是180度。
2. 这种是竖排文本，检测完之后，会转正，识别器可以直接识别
3. 这个是因为检测框的包络面积太大了，识别过程中包含了太多无意义的特征，识别效果肯定很差

**Comment by dagongji10** [comment]
@littletomatodonkey 对于第二种情况的竖排文本，检测完成后如何实现转正呢？检测框的高度远大于宽度，但CRNN的输入不是要求输入高度是32吗？如果直接将竖排旋转为水平，那每一个字就是倒着的，识别器也能识别倒着的字体吗？

**Comment by MissPenguin** [comment]
> @littletomatodonkey 对于第二种情况的竖排文本，检测完成后如何实现转正呢？检测框的高度远大于宽度，但CRNN的输入不是要求输入高度是32吗？如果直接将竖排旋转为水平，那每一个字就是倒着的，识别器也能识别倒着的字体吗？

是的，输入高度是32，竖排文本转平后，文字是躺着的，这种文字我们加入了训练，所以能识别。

**Comment by hymanzhu1983** [comment]
对于第三句的文字识别，有什么好的方法解决？我们实际使用中很多这种图片

**Comment by littletomatodonkey** [comment]
这个是检测的包络框有问题，需要使用精度更高的检测模型

**Comment by dagongji10** [comment]
> > @littletomatodonkey 对于第二种情况的竖排文本，检测完成后如何实现转正呢？检测框的高度远大于宽度，但CRNN的输入不是要求输入高度是32吗？如果直接将竖排旋转为水平，那每一个字就是倒着的，识别器也能识别倒着的字体吗？
> 
> 是的，输入高度是32，竖排文本转平后，文字是躺着的，这种文字我们加入了训练，所以能识别。

一般水平文本的识别就需要百万级别的数据量，如果再加入“躺着”的文字，那训练数据是不是应该在原本正常水平文本识别的基础量级上翻倍？比如原来是200w，现在就需要400w？

**Comment by littletomatodonkey** [comment]
不需要的加入一些数据即可(10%左右)，

**Comment by dagongji10** [comment]
> 不需要的，加入一些数据即可(10%左右)，

好的，谢谢，我去试一下

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
