### ISSUE TITLE
Paddleocr model can not extract urdu text 

### ISSUE THREAD

**Issue by haroon423** [PaddlePaddle/PaddleOCR#11873]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by cuicheng01** [comment]
Hello, urdu text recognition is not supported yet. You need to prepare relevant data and annotations for retraining.

**Comment by haroon423** [comment]
how can do data annotation for retraining can you guide me

**Comment by cuicheng01** [comment]
you can use ppocr label tools, [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/PPOCRLabel/README.md) is README.
