### ISSUE TITLE
chinese and english 的字典在哪里下载？

### ISSUE THREAD

**Issue by yumianhuli2** [PaddlePaddle/PaddleOCR#11872]
Hello！chinese and english 的字典在哪里下载哈？
我在https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/ppocr/utils/dict这里只找到繁体中文字典。。

**Comment by cuicheng01** [comment]
您好，
中文的可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/6ed5562cedce18f0313d3b83271986dd6c136871/ppocr/utils/ppocr_keys_v1.txt
英文的可以参考：
https://github.com/PaddlePaddle/PaddleOCR/blob/6ed5562cedce18f0313d3b83271986dd6c136871/ppocr/utils/en_dict.txt

**Comment by yumianhuli2** [comment]
> 您好， 中文的可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/6ed5562cedce18f0313d3b83271986dd6c136871/ppocr/utils/ppocr_keys_v1.txt 英文的可以参考： https://github.com/PaddlePaddle/PaddleOCR/blob/6ed5562cedce18f0313d3b83271986dd6c136871/ppocr/utils/en_dict.txt

好的，感谢！
