### ISSUE TITLE
如何关闭ppocr.exe大量的日志输出

### ISSUE THREAD

**Issue by liangruxing** [PaddlePaddle/PaddleOCR#11880]
运行没有报错，就是输出了大量的日志，查了半天不知道在哪里关闭。请问有没有参数可以关闭这些日志。

e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0406 07:01:56.015069 35104 fuse_pass_base.cc:57] ---  detected 2 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0406 07:01:56.289335 35104 fuse_pass_base.cc:57] ---  detected 29 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0406 07:01:56.297314 35104 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_35  size: 384
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_93  size: 1536
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_73  size: 768
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_99  size: 1536
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : elementwise_mul_0  size: 768
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_101  size: 1536
I0406 07:01:56.313270 35104 memory_optimize_pass.cc:216] Cluster name : tmp_21  size: 192
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0406 07:01:56.341197 35104 analysis_predictor.cc:1035] ======= optimize end =======
I0406 07:01:56.341197 35104 naive_executor.cc:102] ---  skip [feed], feed -> x
I0406 07:01:56.344188 35104 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
In PP-OCRv3, default rec_img_h is 48,if you use other model, you should set the param rec_img_h=32
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0406 07:01:56.393057 35104 fuse_pass_base.cc:57] ---  detected 6 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
I0406 07:01:56.480749 35104 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
I0406 07:01:56.481746 35104 fuse_pass_base.cc:57] ---  detected 4 subgraphs
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0406 07:01:56.578488 35104 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
I0406 07:01:56.597437 35104 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0406 07:01:56.652290 35104 fuse_pass_base.cc:57] ---  detected 22 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0406 07:01:56.676226 35104 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : hardswish_45.tmp_0  size: 11520
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : linear_170.tmp_1  size: 26500
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : x  size: 576
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : tmp_84  size: 11520
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : shape_3.tmp_0_slice_1  size: 4
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : transpose_44.tmp_0_slice_2  size: 480
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : shape_5.tmp_0_slice_1  size: 4
I0406 07:01:56.695175 35104 memory_optimize_pass.cc:216] Cluster name : tmp_150  size: 480
I0406 07:01:56.696173 35104 memory_optimize_pass.cc:216] Cluster name : transpose_47.tmp_0_slice_2  size: 480
I0406 07:01:56.696173 35104 memory_optimize_pass.cc:216] Cluster name : fill_constant_17.tmp_0  size: 4
I0406 07:01:56.696173 35104 memory_optimize_pass.cc:216] Cluster name : fill_constant_19.tmp_0  size: 4
I0406 07:01:56.696173 35104 memory_optimize_pass.cc:216] Cluster name : reshape2_27.tmp_1  size: 0
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0406 07:01:56.726094 35104 analysis_predictor.cc:1035] ======= optimize end =======
I0406 07:01:56.726094 35104 naive_executor.cc:102] ---  skip [feed], feed -> x
I0406 07:01:56.728088 35104 naive_executor.cc:102] ---  skip [softmax_11.tmp_0], fetch -> fetch
W0406 07:01:56.729085 35104 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.6
W0406 07:01:56.733074 35104 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.

**Comment by changdazhou** [comment]
export GLOG_v=0试一下呢
