### ISSUE TITLE
求助：ppstructure和ocr是否支持batch推理？请给个样例

### ISSUE THREAD

**Issue by charliedream1** [PaddlePaddle/PaddleOCR#11884]
## 背景

经过需求征集https://github.com/PaddlePaddle/PaddleOCR/issues/10334 和每周技术研讨会 https://github.com/PaddlePaddle/PaddleOCR/issues/10223 讨论，我们确定了XXXX任务。

## 解决步骤
1. 根据开源代码进行网络结构、评估指标转换。代码链接：XXXX
2. 结合[论文复现指南](https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/article-implementation/ArticleReproduction_CV.md)，进行前反向对齐等操作，达到论文Table.1中的指标。
3. 参考[PR提交规范](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/code_and_doc.md)提交代码PR到ppocr中。

**Comment by gengyanlei** [comment]
@charliedream1 
这里有你想要的问题
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/FAQ.md

**Comment by charliedream1** [comment]
我看到了。

Q: 为什么PaddleOCR检测预测是只支持一张图片测试？即test_batch_size_per_card=1
A：测试的时候，对图像等比例缩放，最长边960，不同图像等比例缩放后长宽不一致，无法组成batch，所以设置为test_batch_size为1。

那我提前统一把图片处理成同样的大小，然后batch推理。有样例代码吗？还是需要自己做比较多的改动？

**Comment by charliedream1** [comment]
好的



---原始邮件---
发件人: "Tingquan ***@***.***&gt;
发送时间: 2024年4月11日(周四) 下午4:18
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 求助：ppstructure和ocr是否支持batch推理？请给个样例 (Issue #11884)




 
没有参考代码，我们也不推荐这样使用，对预测效果影响较大。
