### ISSUE TITLE
请问车牌识别是否有添加车牌种类的识别，若无应该如何添加呢

### ISSUE THREAD

**Issue by weiming12345** [PaddlePaddle/PaddleOCR#11889]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by GreatV** [comment]
加一个分类器就好了

**Comment by weiming12345** [comment]
请问一下怎么加分类器呢，我只在官网上看到了方向分类器

**Comment by GreatV** [comment]
@weiming12345 参考[paddleclas](https://github.com/PaddlePaddle/PaddleClas)或者其他分类模型选择一个分类模型，训练一个车牌分类网络，然后再现在代码上加一个分类器的代码。
