### ISSUE TITLE
有没有中文简体和繁体，日文，韩文，英文的字库，词库，可以用来生成字符均衡分配的句子？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11883]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

有没有中文简体和繁体，日文，韩文，英文的字库，词库，可以用来生成字符均衡分配的句子？

**Comment by TingquanGao** [comment]
不好意思，我们也没有。建议从网上找一下。
