### ISSUE TITLE
以下倒的印章识别，是否需要矫正后去识别

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#11886]
在用二阶段和一阶段识别印章，发现测试的和训练的印章都正的，导致倒的印章有问题，以下图片是否需要转正呢，还是要另外训练方向角度的检测？

![198929585-84e0dfad-7b06-4a7f-937b-d2f38e582f9f](https://github.com/PaddlePaddle/PaddleOCR/assets/32585434/07c528fe-2fd3-4c79-93fd-2da186ef1bd2)
![Uploading 198929585-84e0dfad-7b06-4a7f-937b-d2f38e582f9f.jpg…]()
@jzhang533 @kerneltravel @sdcb @ZeyuChen

**Comment by TingquanGao** [comment]
推荐转正

**Comment by zhanghengjiayou** [comment]
> 推荐转正

有啥推荐的算法吗

**Comment by Sencc** [comment]
可以使用极坐标转换成矩形图再去识别

**Comment by UserWangZz** [comment]
> 可以使用极坐标转换成矩形图再去识别

你好，有相关方法参考链接吗，感谢

**Comment by Sencc** [comment]
> > 可以使用极坐标转换成矩形图再去识别
> 
> 你好，有相关方法参考链接吗，感谢

大概思路就是以中心为圆点，字体的高度看成一个圆环算出内圆半径和外圆半径，然后利用极坐标把平面坐标进行转换展开，就会得到一个只包含字体的矩形图像

**Comment by UserWangZz** [comment]
> > > 可以使用极坐标转换成矩形图再去识别
> > 
> > 
> > 你好，有相关方法参考链接吗，感谢
> 
> 大概思路就是以中心为圆点，字体的高度看成一个圆环算出内圆半径和外圆半径，然后利用极坐标把平面坐标进行转换展开，就会得到一个只包含字体的矩形图像

感谢分享
