### ISSUE TITLE
形变的扫描版PDF识别经常漏行

### ISSUE THREAD

**Issue by ATP-BME** [PaddlePaddle/PaddleOCR#11895]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：ppocr
- 运行指令/Command Code：
- ocr = PaddleOCR(use_angle_cls=True, lang="ch", page_num=0,use_gpu = True, det_db_thresh=0.3,det_db_box_thresh=0.3,det_limit_side_len=2048,total_process_num=4)  # need to run only once to download and load model into memory

- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/a3ee5b8c-d6ad-431c-9b7b-07acdca4e11a)
如图，可能扫描版PDF行有弯曲，检测经常漏行
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/50ddfe5d-1329-4aa9-a2d4-e5504008cbe9)

**Comment by GreatV** [comment]
可以先用图片矫正模型处理一下 参考[Awesome Document Image Rectification](https://github.com/fh2019ustc/Awesome-Document-Image-Rectification)

**Comment by TingquanGao** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
