### ISSUE TITLE
Inference for KIE model trained on wildreceipt dataset

### ISSUE THREAD

**Issue by AlexPascu001** [PaddlePaddle/PaddleOCR#11893]
In [this link](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_en/algorithm_kie_sdmgr_en.md#4-inference-and-deployment) there is no model available for inference, saying it is "coming soon". Can it be uploaded?

**Comment by tink2123** [comment]
Thanks for your attention, sorry that there is no update yet
