### ISSUE TITLE
能否提供ppyolov2_r50vd_dcn_365e_tableBank_word的trained model或者直接提供不带控制流算子的inference model

### ISSUE THREAD

**Issue by woodenwatcher** [PaddlePaddle/PaddleOCR#11891]
目前只提供inference model下载，但inference model里有conditional_block、select_input控制流类型算子无法支持导出成其他格式的模型，因此需要提供trained model重新导出成inference model（https://github.com/PaddlePaddle/Paddle/issues/33202， 通过PaddleDetection的2.1及其以上版本可避免导出控制流类型的算子）

**Comment by tink2123** [comment]
这个模型暂时不维护了，如果需要可以自己使用开源数据训练～
