### ISSUE TITLE
本项目与百度开放的ocr api 有什么差别？

### ISSUE THREAD

**Issue by elainec728** [PaddlePaddle/PaddleOCR#1189]
不知道在功能和效果上是否有差别？

**Comment by MissPenguin** [comment]
本项目目前主要聚焦通用ocr，如果有垂类需求，可以用PaddleOCR+垂类数据自己训练；如果缺少带标注的数据，或者不想投入研发成本，建议直接调用开放的API更方便，开放的API覆盖了目前比较常见的一些垂类。
