### ISSUE TITLE
Table structure not recognized

### ISSUE THREAD

**Issue by vlavorini** [PaddlePaddle/PaddleOCR#11892]
Hello,

   I am testing this tool on a table, which is a screenshot from an actual PDF (so the alignment is "perfect").
   
   I am following the tutorial in [sec. 4.1, here](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/ppstructure/table) , both with the V3 and the V4 model weights. The issue is that the structure is not correctly recognized (see picture below)
![pad_1](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/c2e84d79-ada6-4f88-ac4b-1e196879e808)

More, if I try with the tutorial in [sec 2.2.1, here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_en/quickstart_en.md), the text direction is correctly understood:

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/c0ab992e-d391-43bf-a0b7-78eac138089c)

Can you please suggest me how to proceed in order to get the correct text orientation?

Thank you!

**Comment by tink2123** [comment]
If your scene is purely in English, it is recommended to change the table recognition model to [SLANet_en](https://paddleocr.bj.bcebos.com/ppstructure/models/slanet/en_ppstructure_mobile_v2.0_SLANet_infer.tar) or [TableMaster](https://paddleocr.bj.bcebos.com/ppstructure/models/tablemaster/table_structure_tablemaster_infer.tar)，their prediction of the coordinate box will be a little more accurate.

```
## slanet_en
# wget https://paddleocr.bj.bcebos.com/ppstructure/models/slanet/en_ppstructure_mobile_v2.0_SLANet_infer.tar
## tablemaster
# wget https://paddleocr.bj.bcebos.com/ppstructure/models/tablemaster/table_structure_tablemaster_infer.ta
python3.7 table/predict_table.py \
    --det_model_dir=inference/ch_PP-OCRv3_det_infer \
    --rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
    --table_model_dir={en/table/model} \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --image_dir=docs/table/table.jpg \
    --output=../output/table
```

**Comment by vlavorini** [comment]
I tried with the en_ models but the result actually worsen:

    python table/predict_table.py     \
    --det_model_dir=inference/en/en_PP-OCRv3_det_infer     \
    --rec_model_dir=inference/en/en_PP-OCRv4_rec_infer    \
    --table_model_dir=inference/en/en_ppstructure_mobile_v2.0_SLANet_infer    \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt     
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt     \
    --image_dir=test_table.png     
    --output=../output/table

![test_table](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/361cbaac-ba4d-4e4e-b3b9-ce65d3ef6166)

I also tried the combinations:

* ch_PP-OCRv4_det_infer  , ch_PP-OCRv4_rec_infer ,  en_ppstructure_mobile_v2.0_SLANet_infer

* ch_PP-OCRv4_det_infer  , en_PP-OCRv4_rec_infer ,  en_ppstructure_mobile_v2.0_SLANet_infer

* en_PP-OCRv3_det_infer  , ch_PP-OCRv4_rec_infer ,  en_ppstructure_mobile_v2.0_SLANet_infer

and I get the same result of the picture above (only one red rectangle). So the error seems to come from the en_ppstructure_mobile_v2.0_SLANet_infer.

Then I tried with 

* en_PP-OCRv3_det_infer  , en_PP-OCRv4_rec_infer , en_ppocr_mobile_v2.0_table_structure_infer

and the result is still a single red rectangle, but different form the previous one (and chinese characters wrongly recognized)


Instead, TableMaster (table_structure_tablemaster_infer.tar) gives an error:

    InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 256, 122, 122], X's size = 3810304, 'shape' is [-1, 256, 120, 120], known capacity of 'shape' is -3686400

Any other suggestion?

**Comment by tink2123** [comment]
```--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt  ``` 
needs change to  
```--table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \```

**Comment by tink2123** [comment]
> Instead, TableMaster (table_structure_tablemaster_infer.tar) gives an error:

Try to use this command, add two parameters `table_algorithm` and `table_max_len`:
```
python table/predict_table.py     \
--det_model_dir=inference/en/en_PP-OCRv3_det_infer     \
--rec_model_dir=inference/en/en_PP-OCRv4_rec_infer    \
--table_model_dir=inference/en/en_ppstructure_mobile_v2.0_SLANet_infer    \
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt     
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt     \
--image_dir=test_table.png    \
--output=../output/table \
--table_algorithm=TableMaster \
--table_max_len=480
```

https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_en/algorithm_table_master_en.md#41-python-inference

**Comment by vlavorini** [comment]
Here the attempts:
 ## 1 - all '_en' with the two options
```
python table/predict_table.py    \
 --det_model_dir=inference/en/en_PP-OCRv3_det_infer     \
--rec_model_dir=inference/en/en_PP-OCRv4_rec_infer     \
 --table_model_dir=inference/en/table_structure_tablemaster_infer/    \
 --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt     \
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt     \
--image_dir=test_table.png    \
 --output=../output/table \
--table_algorithm=TableMaster \
--table_max_len=480
```
Note that `table_structure_dict.txt` is teh name for the `_en` version for this file. But this returns an error: 

      File "/home/vincenzo/devel/tables/PaddleOCR/ppocr/postprocess/table_postprocess.py", line 85, in decode
    text = self.character[char_idx]
    IndexError: list index out of range


## 2 - all `_en`, with the TableMaster structure file
changing `--table_char_dict_path` to `=../ppocr/utils/dict/table_master_structure_dict.txt` make it to run, but the numbers are shown as ideograms
```
python table/predict_table.py\
     --det_model_dir=inference/en/en_PP-OCRv3_det_infer\
     --rec_model_dir=inference/en/en_PP-OCRv4_rec_infer \
     --table_model_dir=inference/en/table_structure_tablemaster_infer/\
     --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_master_structure_dict.txt \
    --image_dir=test_table.png\
     --output=../output/table \
    --table_algorithm=TableMaster\
    --table_max_len=480

```
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/34d31e3f-0def-4e21-82ac-d94609388c23)

## all `_ch` ?
If the `_en` versions gives ideograms, mayme `_ch` versions gives Latin characters and Arab numbers?

```
python table/predict_table.py\
     --det_model_dir=inference/ch/ch_PP-OCRv4_det_infer\
     --rec_model_dir=inference/ch/ch_PP-OCRv4_rec_infer\
      --table_model_dir=inference/en/table_structure_tablemaster_infer/\
     --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt\
     --table_char_dict_path=../ppocr/utils/dict/table_master_structure_dict.txt\
     --image_dir=test_table.png \
    --output=../output/table\
   --table_algorithm=TableMaster \
  --table_max_len=480
```

That's weird, but it works:
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/cfe8a1a5-ff97-4536-b188-b4d9488a6d17)

I am happy with such solution, but maybe a comment more is needed here.

Thank you @tink2123 !
