### ISSUE TITLE
PP-OCRv4识别模型量化训练错误，配置文件为：ch_PP-OCRv4_rec.yml

### ISSUE THREAD

**Issue by VioletEmpty** [PaddlePaddle/PaddleOCR#11897]
配置文件中使用的损失函数如下图所示：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/103800615/7ce8ed3e-300e-4073-a7f4-7f58f6287ca1)
但是在量化模型的python文件中需要使用SARLOSS，我尝试将配置文件中的NRTRLoss替换为SARLoss，虽然能够进行训练，但是导致模型加载不正确且模型不收敛acc为0，这个问题该怎么解决呢？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/103800615/acac1a9d-f45e-43d3-b43b-7a71fdad36c8)

**Comment by TingquanGao** [comment]
参考一下这个文档呢，ppocrv4和v3的量化是一样的。

https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7/deploy/slim/quantization

**Comment by TingquanGao** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
