### ISSUE TITLE
crnn多语种模型训练时，发现英文和数字错误率比中文等高很多，怎样改善？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11894]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

crnn多语种模型训练时，发现英文和数字错误率比中文等高很多，怎样改善？

**Comment by UserWangZz** [comment]
英文和中文分布均衡吗，数据集中大部分都是中文吗？

**Comment by nissansz** [comment]
用了英语新闻随机截取训练后，好像也没那么差了。
就是偶尔会有漏字符，多字符（出现两个同样的字符），错字辅之类的问题

**Comment by UserWangZz** [comment]
好的
