### ISSUE TITLE
mac系统使用cpu，对1920x1080的屏幕截图，ocr耗时12s，【付费】请大神帮忙优化到2秒内

### ISSUE THREAD

**Issue by jackzh00** [PaddlePaddle/PaddleOCR#11898]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
    - mac min . 
    - 3 GHz 6-Core Intel Core i5
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
   - paddle ocr 2.7.3
- 运行指令/Command Code：
```python

from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(
    use_angle_cls=False,
    lang="en",
    # use_onnx=True,
    ocr_version="PP-OCRv2",
    use_mp=True,
    # enable_mkldnn=True,
    total_process_num=2,
    # use_pdserving=True,
    
    use_mkldnn=True,
    use_gpu=False,
    # table=False,
    use_tensorrt=True,
    show_log=True
)  


def findBoxByTextFromImg(text, img_path):
    result = ocr.ocr(img_path, det=True,rec=True,cls=False)
    print("result", result)
```
现象：
- 目前CPU使用率很低。感觉和没程序再跑一样

**Comment by myhostone1990** [comment]
openvino试一下

**Comment by myhostone1990** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：
>   
>   * mac min .
>   * 3 GHz 6-Core Intel Core i5
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
>   
>   * paddle ocr 2.7.3
> * 运行指令/Command Code：
> 
> ```python
> from paddleocr import PaddleOCR, draw_ocr
> 
> ocr = PaddleOCR(
>     use_angle_cls=False,
>     lang="en",
>     # use_onnx=True,
>     ocr_version="PP-OCRv2",
>     use_mp=True,
>     # enable_mkldnn=True,
>     total_process_num=2,
>     # use_pdserving=True,
>     
>     use_mkldnn=True,
>     use_gpu=False,
>     # table=False,
>     use_tensorrt=True,
>     show_log=True
> )  
> 
> 
> def findBoxByTextFromImg(text, img_path):
>     result = ocr.ocr(img_path, det=True,rec=True,cls=False)
>     print("result", result)
> ```
> 
> 现象：
> 
> * 目前CPU使用率很低。感觉和没程序再跑一样






openvino试一下

**Comment by jackzh00** [comment]
我试了，但是无论是下载预编译的还是自己编译都失败了。#11905

**Comment by myhostone1990** [comment]
> 我试了，但是无论是下载预编译的还是自己编译都失败了。#11905

可以一起优化下，可回我邮件

**Comment by TingquanGao** [comment]
可以参考使用fastdeploy推理试试呢：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR
