### ISSUE TITLE
data filter 如何用到simple_dataset过滤动态生成的0.95以上和0.15以下的图片

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11903]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

data filter 如何用到simple_dataset过滤动态生成的0.95以上和0.15以下的图片

**Comment by nissansz** [comment]
好像很模糊的准确率都没有0.15以下，0.95以上的好像比较多，过滤好像速度不是很慢，就是不知道过滤掉两头后准确率能改善多少

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/f8c3029c-a1b9-4d2d-b7a4-86f1fb5310bb)

**Comment by TingquanGao** [comment]
对精度的影响只能实际测试一下。0.15和0.95也是我们的经验值，可以尝试修改试试。

**Comment by nissansz** [comment]
我尝试用paddleocr在训练前对每一张图片进行识别，结果cuda报错了，可能爆显存了。
怎样避免爆显存？应该怎样边识别边训练?

**Comment by TingquanGao** [comment]
如何判断是爆显存了呢？麻烦提供一下报错信息和运行命令，以及简单描述一下复现流程。

**Comment by nissansz** [comment]
就是没读取一张图，就用paddleocr进行识别，然后就报错了

**Comment by TingquanGao** [comment]
贴一下运行的命令，我们在本地机器试下

**Comment by nissansz** [comment]
没有命令，改了simple_加载py文件
读取图片时，调用paddleocr.py识别单行文字

**Comment by tink2123** [comment]
建议把筛选score的过程放在离线完成
