### ISSUE TITLE
这个代码可以解决爆显存吗？要加在哪些文件里？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11907]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

import paddle
 
# required: gpu
paddle.set_device("gpu")
#tensor = paddle.randn([512, 512, 512], "float")
#del tensor
paddle.device.cuda.empty_cache()

**Comment by TingquanGao** [comment]
是遇到报错了么？运行的什么命令呢？

**Comment by nissansz** [comment]
> 是遇到报错了么？运行的什么命令呢？

就是在生成完一张图片时，我就用paddleocr.py识别图片的结果，报错如下，不知道有没有可以避免这种错误的识别方法


  File "C:\F\pycharm2020.2\PaddleOCR-2.7.5\paddleocr.py", line 712, in ocr
    rec_res, elapse = self.text_recognizer(img)
  File "C:\F\pycharm2020.2\PaddleOCR-2.7.5\tools\infer\predict_rec.py", line 669, in __call__
    self.input_tensor.copy_from_cpu(norm_img_batch)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\inference\wrapper.py", line 36, in tensor_copy_from_cpu
    self.copy_from_cpu_bind(data)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251)

**Comment by TingquanGao** [comment]
试一下这个呢？

```python
import paddle
paddle.utils.install_check.run_check()
```

**Comment by nissansz** [comment]
checkgpu.py
Running verify PaddlePaddle program ... 
W0416 11:22:26.553992  9688 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0416 11:22:26.973874  9688 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

Process finished with exit code 0

**Comment by TingquanGao** [comment]
paddle版本、cuda、cudnn版本是多少呢？

**Comment by nissansz** [comment]
paddleocr2.7.5, 
cuda 10

**Comment by TingquanGao** [comment]
paddlepaddle-gpu版本是多少？新版的paddle已经不支持cuda10了

**Comment by nissansz** [comment]
2.3.2

**Comment by nissansz** [comment]
cuda10.2好像还可以训练

**Comment by TingquanGao** [comment]
paddle2.3.2是支持cuda10.2的，但是2.3.2是很老的版本了，目前最新已经是2.6.1了。我查了一下，最新的支持10.2的paddle是这个，可以重新安装一下试试：https://paddle-wheel.bj.bcebos.com/2.5.2/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-avx/paddlepaddle_gpu-2.5.2.post102-cp38-cp38-linux_x86_64.whl

**Comment by nissansz** [comment]
我是win10

**Comment by TingquanGao** [comment]
https://paddle-wheel.bj.bcebos.com/2.5.2/windows/windows-gpu-cuda10.2-cudnn7.6.5-mkl-avx-vs2017/paddlepaddle_gpu-2.5.2.post102-cp38-cp38-win_amd64.whl

**Comment by nissansz** [comment]
谢谢。这个对于准确率有改善吗？

另外就是，用了这个版本可以一边加载图片识别，一边训练吗？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Tingquan Gao  ***@***.***>
 

 
 发送时间: 2024-04-16 15:34:41
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] 这个代码可以解决爆显存吗？要加在哪些文件里？ (Issue #11907)
 





 https://paddle-wheel.bj.bcebos.com/2.5.2/windows/windows-gpu-cuda10.2-cudnn7.6.5-mkl-avx-vs2017/paddlepaddle_gpu-2.5.2.post102-cp38-cp38-win_amd64.whl

**Comment by TingquanGao** [comment]
对准确率没有影响；得先解决报错的问题才行。

**Comment by nissansz** [comment]
如果想在训练时加载图片前识别，该用哪种方式识别？

识别完释放显存 不占显存









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Tingquan Gao  ***@***.***>
 

 
 发送时间: 2024-04-16 15:43:36
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] 这个代码可以解决爆显存吗？要加在哪些文件里？ (Issue #11907)
 





 对准确率没有影响；得先解决报错的问题才行。

**Comment by TingquanGao** [comment]
现在就是怀疑是因为paddle版本导致的显存未正常释放，所以想换一下paddle版本试试。

**Comment by nissansz** [comment]
我先安装试试。

resnet34 和 svtr准确率哪个高？好像svtr训练速度特别慢

**Comment by nissansz** [comment]
装了 2.5.2，直接报错了，。

  File "C:\F\pycharm2020.2\PaddleOCR-2.7.5\ppocr\data\simple_dataset.py", line 36, in <module>
    from .textline2png_pillow_CharacterCheck3shadow24 import text2png_supGenerator
  File "C:\F\pycharm2020.2\PaddleOCR-2.7.5\ppocr\data\textline2png_pillow_CharacterCheck3shadow24.py", line 20, in <module>
    from straug.blur import GaussianBlur, DefocusBlur, MotionBlur, GlassBlur, ZoomBlur
  File "C:\Program Files\Python38\lib\site-packages\straug\blur.py", line 21, in <module>
    import torchvision.transforms as transforms
  File "C:\Program Files\Python38\lib\site-packages\torchvision\__init__.py", line 4, in <module>
    from .extension import _HAS_OPS
  File "C:\Program Files\Python38\lib\site-packages\torchvision\extension.py", line 6, in <module>
    import torch
  File "C:\Program Files\Python38\lib\site-packages\torch\__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: generic_type: type "_CudaDeviceProperties" is already registered!

**Comment by nissansz** [comment]
过了一段时间，就报错了

**Comment by tink2123** [comment]
几个方案可以尝试：
0. 先升级到最新的develop
1. 试试换显存分配器：export FLAGS_allocator_strategy=naive_best_fit&&export FLAGS_fraction_of_gpu_memory_to_use=0.92，这个打开后会一开始占用大量显存，后续不会auto growth
2. 如果1 不奏效， 再试试export FLAGS_allocator_strategy=auto_growth&&export FLAGS_eager_delete_tensor_gb=2 （显存小于2G时触发GC）

**Comment by nissansz** [comment]
这个 export在哪里加？windows也有效？

**Comment by tink2123** [comment]
export 是设置环境变量的命令，windows用set
