### ISSUE TITLE
字符1经常漏检

### ISSUE THREAD

**Issue by robertoding** [PaddlePaddle/PaddleOCR#11900]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：Paddle 2.6.1, PaddleOCR 2.7
- 运行指令/Command Code：paddleocr --image_dir=1.jpg --use_gpu=false --lang=ch
- 完整报错/Complete Error Message：

使用默认模型（DB）的情况下，字符“1”经常漏检，比如“1 of 2"只识别出"of 2"。在不重新训练的前提下，如何提高字符“1”的识别率。更换其他模型？调整某个参数？考虑到其他文本识别效果很好，为了1重新训练一边不值得。

**Comment by TingquanGao** [comment]
可以考虑修改后处理，调低一点1的检测阈值。

**Comment by TingquanGao** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
