### ISSUE TITLE
能够识别出文字但是一直报错runtimeerror

### ISSUE THREAD

**Issue by SHYBEENOMULA** [PaddlePaddle/PaddleOCR#11904]
这是报错的内容
RuntimeError: (NotFound) Cannot open file C:\Users\lth/.paddleocr/whl\det\ch\ch_PP-OCRv4_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2578)
![屏幕截图_20240409_190511](https://github.com/PaddlePaddle/PaddleOCR/assets/152295183/17703bd2-ce69-4ac5-ad34-fd24d703a8f5)

**Comment by GreatV** [comment]
检测一下`C:\Users\lth/.paddleocr/whl\det\ch\ch_PP-OCRv4_det_infer/inference.pdmode`这个路径

**Comment by SHYBEENOMULA** [comment]
你好，我检查了一下，发现路径没问题，跟着提示能找到这个pdmode文件，我也试过在官网上重下那个文件但这并没能解决问题，环境是win11+python3.8的pycharm

**Comment by TingquanGao** [comment]
可以简单描述一下复现流程吗？我们试试。

**Comment by WhoWhoooo** [comment]
> 可以简单描述一下复现流程吗？我们试试。

我觉得是这个路径里有中文的问题,很多issue报这个错
RuntimeError: (NotFound) Cannot open file C:\Users\lth/.paddleocr/whl\det\ch\ch_PP-OCRv4_det_infer/inference.pdmodel, please confirm whether the file is normal.
都是中文路径,希望后续可以改善

**Comment by tink2123** [comment]
应该是linux和windows的路径中，斜杠 和 反斜杠 使用的问题，我们会考虑优化下代码兼容该问题。
