### ISSUE TITLE
更改标注信息格式

### ISSUE THREAD

**Issue by plotnine1219** [PaddlePaddle/PaddleOCR#11908]
想对自定义数据集按照我们的标注格式重新标注，我需要对模型中哪些代码进行修改（没找到读取标注信息的代码）

**Comment by Sunting78** [comment]
您好，具体是什么任务呢？可以参考以下数据读取代码。https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/data/simple_dataset.py
