### ISSUE TITLE
fastdeploy编译问题：1.用预编译的提示RuntimeOption不存在。2.自己编译，编译成功了安装失败。提示不支持当前平台

### ISSUE THREAD

**Issue by jackzh00** [PaddlePaddle/PaddleOCR#11905]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
     -  mac osx 14，intel  x86 64bit
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
    1. 自己编译的fastdeploy:
    - ➜  dist git:(develop) pip install fastdeploy_python-0.0.0-cp39-cp39-macosx_12_0_x86_64.whl
```
ERROR: fastdeploy_python-0.0.0-cp39-cp39-macosx_12_0_x86_64.whl is not a supported wheel on this platform.
```
  意思是说不支持我现在的osx 14 系统吗？只支持osx12的？

 2.使用预编译的fastdepoly的报错信息：
➜  python git:(main) ✗ python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device cpu --backend paddle
```sh
fd <module 'fastdeploy' (namespace)>
Traceback (most recent call last):
  File "/Users/che3vinci/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 185, in <module>
    det_option, cls_option, rec_option = build_option(args)
  File "/Users/che3vinci/PaddleOCR/deploy/fastdeploy/cpu-gpu/python/infer.py", line 75, in build_option
    det_option = fd.RuntimeOption()
AttributeError: module 'fastdeploy' has no attribute 'RuntimeOption'
```
预编译的fastdeploy是从如下地址下在的。因为我是用的cpu
```sh
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
```

**Comment by GreatV** [comment]
是arm芯片吗

**Comment by GreatV** [comment]
<img width="886" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/b484838f-eb6d-4c25-a14a-b8e0c6f97630">
arm 只支持onnxruntime

**Comment by jackzh00** [comment]
> 是arm芯片吗

是intel x86 64

**Comment by GreatV** [comment]
你给 fastdeploy 提个issue吧

**Comment by TingquanGao** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
