### ISSUE TITLE
关于相同模型在python和c++不同结果的疑问

### ISSUE THREAD

**Issue by gmayday1997** [PaddlePaddle/PaddleOCR#1190]
首先感谢paddle的开源项目。目前使用PaddleOCR训练了一些车牌样本，在python环境下达到了很高的精度，然后使用predict_system.py也能准确检测，然而同样模型在c++推理下却出现了错误的结果。但若使用paddle团队给出的ch_pporc_mobile_rec_infer等模型，其结果不论在python环境还是在c++环境下，几乎是一致的。这样的结果让我非常困惑。

目前我的电脑安装的是cuda11, cudnn是7.5. paddlepaddle版本是1.8.5, 
c++ inference 库使用的是 https://paddle-inference-lib.bj.bcebos.com/1.8.4-gpu-cuda10-cudnn7-avx-mkl/fluid_inference.tgz

还请大家能够指点一二，不胜感激。

**Comment by LDOUBLEV** [comment]
是否有更改预测的超参数，错误是指检测错误还是识别错误 ？
