### ISSUE TITLE
文本识别模型eval.py得到的acc指标很高(99%),但是使用predict_rec.py推理得到的指标很低(77%)

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleOCR#11912]
你好，我基于PP-OCRv3识别模型微调训练，使用eval.py评估，得到acc=99%，我把预测结果都保存下来、分析，结果确实都正确，符合99%的指标。

但是我使用predict_rec.py推理的时候，基于同一批数据，得到的acc就低很多，看预测结果也较差，比如有很多空格，下划线的误识别、漏识别。

请问这是因为什么呢？

**Comment by ICEVIL** [comment]
你看配置文件eval的时候，其图像是采用RecResizeImg方式统一到[3, 48, 320]这个尺寸，predict_rec.py中应该是图像的长度是动态的其目的是对长文本支持的比较好，但是确实也会导致eval与infer的结果存在差异。

**Comment by gsx1378** [comment]
> 你看配置文件eval的时候，其图像是采用RecResizeImg方式统一到[3, 48, 320]这个尺寸，predict_rec.py中应该是图像的长度是动态的其目的是对长文本支持的比较好，但是确实也会导致eval与infer的结果存在差异。

是的，确实是这个问题引起的指标变化。因为我的训练集、评估集的图像尺寸都是随机的，训练时候固定尺寸，所以eval时候固定尺寸指标会特别高。

实际使用中，送识别的图像宽度是随机变化的，可能存在特别长的图像，这样直接缩放至固定尺寸不太易用，请问：
1. 训练时候，模型尺寸可以是动态的吗？
2. 假设训练尺寸是固定，是不是应该修改训练数据尺寸，大致围绕在48x320的范围内？还是说训练数据的宽度是固定的320

**Comment by ICEVIL** [comment]
目前，训练过程中其图像的宽度只能是固定的，可以修改这个320（宽度），具体你统计一下你的训练集的图像的宽度的分布，比如你的训练集长文本多一些（同时统计图像的宽度以及对应图像的字符数量），那么可以把320修改为480，如果大部分是短文本，那么可以将320缩短一些比如256。但是你现在是基于PP-OCRv3识别模型微调训练，那么你应该是改不了这个宽度的，只能重新训练。那么既然都需要重新训练了，不然训练PP-OCRv4，精度会高一些
