### ISSUE TITLE
试了这个openvino，报了错，不知道怎么解决 https://github.com/zhuo-yoyowz/openvino_notebooks/tree/main/notebooks/405-paddle-ocr-webcam

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11910]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

[openvino_notebooks/notebooks/405-paddle-ocr-webcam at main · zhuo-yoyowz/openvino_notebooks (github.com)](https://appmail.mail.10086.cn/m6/html/redirect.html?url=https%3A%2F%2Fgithub.com%2Fzhuo-yoyowz%2Fopenvino_notebooks%2Ftree%2Fmain%2Fnotebooks%2F405-paddle-ocr-webcam)

Exception from src\inference\src\cpp\infer_request.cpp:112:
Exception from src\inference\src\cpp\infer_request.cpp:66:
Exception from src\plugins\intel_cpu\src\infer_request.cpp:390:
Can't set the input tensor with name: x, because the model input (shape=[?,3,?,?]) and the tensor (shape=(3.48.110)) are incompatible

**Comment by Sunting78** [comment]
推荐用FD 您使用的repo不是我们官方维护的哈

**Comment by Liyulingyue** [comment]
Can't set the input tensor with name: x, because the model input (shape=[?,3,?,?]) and the tensor (shape=(3.48.110)) are incompatible
应该是你的输入结构和模型推理结构不一致导致的。

**Comment by UserWangZz** [comment]
> Can't set the input tensor with name: x, because the model input (shape=[?,3,?,?]) and the tensor (shape=(3.48.110)) are incompatible 应该是你的输入结构和模型推理结构不一致导致的。
感谢讨论

**Comment by nissansz** [comment]
onnx推理有什么办法加速吗？速度好像是paddle gpu inference的1/3
