### ISSUE TITLE
关于显存占用问题

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleOCR#1191]
![image](https://user-images.githubusercontent.com/24349763/99493915-0f6ed400-29ab-11eb-81d1-41c6cc378123.png)
我使用了paddleOCR作为服务提供，如图，同样的代码有两个环境，但GPU显存占用不一样，一开始是一样的，都是1789M,过了一天，下面的显存占用了3123M，服务还是正常的，只是为什么显存会多占用呢？

**Comment by wowowoll** [comment]
用8G显卡跑了几天现在已经专用了7900多M了

**Comment by yuemengrui** [comment]
@wowowoll 为啥会额外占显存呢？我用tensorflow和pytorch都不会额外占用显存，模型固化下来了，它就是那么多显存，跑几年都是固定的显存占用．为啥这个paddleOCR会不停的额外占用显存？

**Comment by MissPenguin** [comment]
您好，Paddle的预测机制下，如果请求的图片比较大或比较复杂，显存会相应增长，最终显存会稳定在最大图所需显存大小，不会无限制增长，如果你用同一张图循环访问，可以看到显存是不会变化的。

**Comment by liweigu** [comment]
我使用时，虽然同一张图循环访问时显存不会变化，但显存也不会下降，如果换几张图片提交给hub，显存就不够用了。

**Comment by mingo-doer** [comment]
> 您好，Paddle的预测机制下，如果请求的图片比较大或比较复杂，显存会相应增长，最终显存会稳定在最大图所需显存大小，不会无限制增长，如果你用同一张图循环访问，可以看到显存是不会变化的。

您好，请问基于这样的机制，图片尺寸过大时，显存会一直上涨，有什么好的办法去限制吗
