### ISSUE TITLE
rec v4 模型，如果是字典里没有的字符，会直接没有显示结果，也没有占位符之类。怎样修改代码，将没有的字符改成返回成■？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11926]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec v4 模型，如果是字典里没有的字符，会直接没有显示结果，也没有占位符之类。怎样修改代码，将没有的字符改成返回成■？

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/d91b3d74-3d43-4381-9f01-1d654a6712ea)
v4 中文返回的是
我从来没觉得美是个累赘
邪魔 美の。

正确返回结果应该是
我从来没觉得美咲是个累赘
私は 邪魔だなんて 思ったことないから! 美咲のこと。

如果字典没有字符，想返回如下效果，每个■代表个一个识别有问题的字符。
我从来没觉得美■是个累赘
■■■■■■邪魔 美の■■■■。

**Comment by jingmingtao** [comment]
请问您这个能够解决吗

**Comment by jingmingtao** [comment]
你好，我也遇到这样的功能需求，请问有什么好的建议吗

**Comment by tink2123** [comment]
目前算法不支持这个功能哈，可以自己修改一下后处理，判断当前字符score小于某个数值（例如0.1），则返回指定■

**Comment by nissansz** [comment]
后处理是哪个py文件？哪一行改？

**Comment by tink2123** [comment]
可以看下 decode 的逻辑：
https://github.com/PaddlePaddle/PaddleOCR/blob/00f0d42d9bf61d7fe5b70bc6bd87d809724d5abc/ppocr/postprocess/rec_postprocess.py#L206
