### ISSUE TITLE
检测模型文本框的边缘扩大缩小对识别准确率有影响，有时大一点准，有时小一点准，这种一般怎样判断应该用哪个？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11922]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

检测模型文本框的边缘扩大缩小对识别准确率有影响，有时大一点准，有时小一点准，这种一般怎样判断应该用哪个？

**Comment by zhangyubo0722** [comment]
这个没有统计性结论，一般来讲检测框越准确，识别准确率越高

**Comment by changdazhou** [comment]
不好意思，这个是不能自动适配的哈，如果有强需求，只能自行修改代码进行适配哈

**Comment by changdazhou** [comment]
如何有强需求的话，目前来看是只能这样的，我们目前没有计划对这里进行自动调整的适配计划哈

**Comment by nissansz** [comment]
如果要调整上面这些参数 必须重新启动新的OCR引擎？

还是可以直接用原先启动的引擎，识别时传入参数即可？怎么传参数进去？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: changdazhou  ***@***.***>
 

 
 发送时间: 2024-04-12 20:02:26
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] 检测模型文本框的边缘扩大缩小对识别准确率有影响，有时大一点准，有时小一点准，这种一般怎样判断应该用哪个？ (Issue #11922)
 





 如何有强需求的话，目前来看是只能这样的，我们目前没有计划对这里进行自动调整的适配计划哈

**Comment by changdazhou** [comment]
这个应该是可以启动后实时传入的，不过需要你自行适配哈，我们目前的代码应该是必须重启OCR引擎才行

**Comment by nissansz** [comment]
现在我用的是rapidocr调用paddleocr，好像可以实时传入参数

**Comment by changdazhou** [comment]
可以尝试一下
