### ISSUE TITLE
rec v4中英文模型准确率明显高于v4日文，韩文，繁体中文，什么时候有更高准确率的v4日文，韩文，繁体中文模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11929]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec v4中英文模型准确率明显高于v4日文，韩文，繁体中文，什么时候有更高准确率的v4日文，韩文，繁体中文模型？

**Comment by tink2123** [comment]
这取决于训练数据的质量，小语种我们使用的都是开源+合成数据，如果您有更高的精度要求可以使用真实数据finetune一下哈

**Comment by nissansz** [comment]
中文模型是加了真实数据？多少？

**Comment by tink2123** [comment]
中英文模型总共使用500w训练数据

**Comment by nissansz** [comment]
是什么样的数据？

**Comment by nissansz** [comment]
每行是纯英文，或纯中文？

**Comment by tink2123** [comment]
纯英文、纯中文、中文+英文，这些情况都有的
