### ISSUE TITLE
打包后提示识别错误could not create a primitive

### ISSUE THREAD

**Issue by pierre110** [PaddlePaddle/PaddleOCR#11925]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- win10 64
- 版本号/Version：
- Paddle：  2.6.1
- PaddleOCR： 2.7.5
- 问题相关组件/Related components：
- tools\infer\predict_det.py   self.predictor.run() 无法启动
- 运行指令/Command Code：

ocr = PaddleOCR(use_angle_cls=False, use_gpu=False, show_log=False)
text = ocr.ocr(file_path, cls=True) 

- 完整报错/Complete Error Message：
`Traceback (most recent call last):
  File "main.py", line 96, in <module>
  File "app.py", line 36, in App
  File "module\img_to_pdf.py", line 23, in ConvertToPdf
  File "module\img_to_pdf.py", line 128, in __model_2
  File "module\img_to_pdf.py", line 228, in InvoiceOcr
  File "paddleocr.py", line 682, in ocr
  File "tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "tools\infer\predict_det.py", line 254, in __call__
    self.predictor.run()
RuntimeError: could not create a primitive`

打包后在cmd窗口运行能执行识别成功，但是大概过了一会就提示错误无法进行下去

**Comment by changdazhou** [comment]
是指打包成wheel包之后识别报错吗

**Comment by pierre110** [comment]
> 是指打包成wheel包之后识别报错吗

是的，我也按照 #44 关闭mkldnn加速，也没有效果.
系统环境： 64bit、AMD64
spec 如下：
`# -*- mode: python ; coding: utf-8 -*-
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

block_cipher = None
a = Analysis(['main.py'],
     pathex=['E:\\PyEnviroment\\Lib\\site-packages\\paddleocr', 'E:\\PyEnviroment\\Lib\\site-packages\\paddle\\libs'],
     binaries=[('E:\\PyEnviroment\\Lib\\site-packages\\paddle\\libs', '.')],
     datas=[],
     hiddenimports=['framework_pb2','scipy.special.cython_special','skimage','skimage.feature._orb_descriptor_positions','skimage.filters.edges', 'skimage.data._fetchers'],
     hookspath=['.'],
     runtime_hooks=[],
     excludes=['matplotlib'],
     win_no_prefer_redirects=False,
     win_private_assemblies=False,
     cipher=block_cipher,
     noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
     cipher=block_cipher)
exe = EXE(pyz,
     a.scripts,
     [],
     exclude_binaries=True,
     name='main',
     debug=False,
     bootloader_ignore_signals=False,
     strip=False,
     upx=True,
     console=True)
coll = COLLECT(exe,
     a.binaries,
     a.zipfiles,
     a.datas,
     strip=False,
     upx=True,
     upx_exclude=[],
     name='mam_it')`

**Comment by pierre110** [comment]
> 是指打包成wheel包之后识别报错吗

issues不小心close，麻烦重新打开，谢谢

**Comment by changdazhou** [comment]
可不可以源码python setup.py install 安装使用呢

**Comment by python-bookworm** [comment]
遇到同样的问题，CPU推理

**Comment by cxiaowen** [comment]
解决了没，怎么解决的？
