### ISSUE TITLE
自己训练的检测模型怎么投入paddleocr中使用？

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/PaddleOCR#1192]
paddleocr自己训练的目标检测模型 怎么投入使用呐？ 训练的输出是**.pdmodel，**.pdparams;原本paddleocr的模型文件 是 model和params。谢谢
![image](https://user-images.githubusercontent.com/29444693/99498015-bce4e600-29b1-11eb-917a-904e892752e2.png)

**Comment by MissPenguin** [comment]
需要将训练模型转换成推理模型，具体操作参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md#%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B%E8%BD%ACinference%E6%A8%A1%E5%9E%8B
