### ISSUE TITLE
rec模型，如果只想评估模型的准确率更新到模型，不进行训练，怎么调用？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11938]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec模型，如果只想评估模型的准确率更新到模型，不进行训练，怎么调用？

**Comment by TingquanGao** [comment]
不好意思，没理解你说的问题。

**Comment by UserWangZz** [comment]
可以参考tools/program.py文件中 第476行代码尝试更新
```
if cur_metric[main_indicator] >= best_model_dict[main_indicator]:
      best_model_dict.update(cur_metric)
      best_model_dict["best_epoch"] = epoch
      save_model(
          model,
          optimizer,
          save_model_dir,
          logger,
          config,
          is_best=True,
          prefix="best_accuracy",
          best_model_dict=best_model_dict,
          epoch=epoch,
          global_step=global_step,
      )
```

**Comment by nissansz** [comment]
不是保存，是怎么评估每张图准确率

**Comment by UserWangZz** [comment]
> 比如一个模型，原先训练时用了100张图。可能推理时得分不太准 现在想对所有字符评估一次，改善得分，将得分更新到原模型中去

将得分更新到原模型，我理解的就是在这里进行eval的更新啊

**Comment by nissansz** [comment]
好的，谢谢

**Comment by nissansz** [comment]
好的，谢谢
