### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by zhanghengjiayou** [PaddlePaddle/PaddleOCR#11931]
训练ppocrv3没有问题，训练ppocrv4出现报错
0 paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)
网上说是bs太大，我改成1还是同样的错，cuda11.2，cudnn8.2

**Comment by zhanghengjiayou** [comment]
报这个错误

**Comment by tink2123** [comment]
请问有更详细的报错信息嘛？

**Comment by zhanghengjiayou** [comment]
> 请问有更详细的报错信息嘛？

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1713235979 (unix time) try "date -d @1713235979" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800003343) received by PID 13123 (TID 0x7f5bf5a4c100) from PID 13123 ***]

Aborted (core dumped)

**Comment by zhanghengjiayou** [comment]
Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocr_v4
  save_epoch_step: 50
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: /home/ubuntu/PaddleOCR-release-2.6/model/Rec/ch_PP-OCRv4_rec_server_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: /home/ubuntu/PaddleOCR-release-2.6/train/image/
    ext_op_transform_idx: 1
    label_file_list:
    - /home/ubuntu/PaddleOCR-release-2.6/train/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[320, 32], [320, 48], [320, 64]]
    first_bs: &bs 192
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: 1
    drop_last: true
    num_workers: 0
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/ubuntu/PaddleOCR-release-2.6/train/image/
    label_file_list:
    - /home/ubuntu/PaddleOCR-release-2.6/train/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 0

**Comment by zhanghengjiayou** [comment]
> 请问有更详细的报错信息嘛？

谢谢帮忙看一下，ppocrv4 server版需要多大内存的GPU啊

**Comment by zhanghengjiayou** [comment]
换了大显存的显卡可以了
