### ISSUE TITLE
可以在FPGA 百度大脑上部署PaddleOCR吗？

### ISSUE THREAD

**Issue by wowowoll** [PaddlePaddle/PaddleOCR#1193]
![image](https://user-images.githubusercontent.com/49295186/99498065-d6862d80-29b1-11eb-8d20-c11bf59b0e45.png)

**Comment by MissPenguin** [comment]
您好，lite支持FPGA部署，但是OCR所需要的OP可能不全，你可以先试下～

**Comment by LDOUBLEV** [comment]
FPGA没测试过；
目前测试过的芯片有RK系列，jeston系列，基于arm架构的手机芯片都可以；

**Comment by wanghaisheng** [comment]
>目前测试过的芯片有RK系列，jeston系列，基于arm架构的手机芯片都可以；
RK jeston的测试数据能放一下嘛
测了那些型号 benchmark怎么样

**Comment by Spikexxf** [comment]
这个有人试过吗，专门买了一块板子
