### ISSUE TITLE
动态图训练rec v4是要准备什么样的图片？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11937]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

动态图训练rec v4是要准备什么样的图片？

**Comment by tink2123** [comment]
可以参考数据准备教程：https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/dataset/ocr_datasets.md

**Comment by nissansz** [comment]
都是单张jpg或png，
gif那种动态图是没法训练的吧？

**Comment by tink2123** [comment]
gif 暂时没支持，可以转成静态图

**Comment by nissansz** [comment]
动态训练，指的是图片高度可以不同？

**Comment by UserWangZz** [comment]
预处理阶段会padding或resize到相同高度的
