### ISSUE TITLE
The height of image increases

### ISSUE THREAD

**Issue by okusamaOwO** [PaddlePaddle/PaddleOCR#11936]
I printed the image shape in the Det_eval and got 3*1408*993, which means the height of image is 1408
However indeed, the image size is originally 1403*993, and if i read the image with cv2, i get the same result.

Can anyone tell me why the shape of image change ?

**Comment by UserWangZz** [comment]
Do you mean that the image shape has changed from 1403 * 993 to 3 * 1403 * 993?

**Comment by okusamaOwO** [comment]
no, the dimension unchanged. I meant that the image height had increased from 1403 to 1408.

**Comment by UserWangZz** [comment]
You can track whether the image has been highly changed since it was first read in, and then gradually analyze in which stage the image shape has changed.
