### ISSUE TITLE
Cannot recognize special character

### ISSUE THREAD

**Issue by Hieung28** [PaddlePaddle/PaddleOCR#1194]
Hi all,
I've find out that PADDLE OCR algorithm is not able to recognize some special characters (such as comma, semicolon or dot) when the language is english. Is there any possible way that I can fix this problem?

**Comment by MissPenguin** [comment]
It may be caused by the lack of such data in the training data. You can try to add more data, especially data containing commas,  semicolon and dot, to fine tune the model.

**Comment by Lahari-77** [comment]
I m using the trained model.Is  there any parameter that can be set to make sure colon are also extracted
