### ISSUE TITLE
PaddleOCR中开源的繁体中文识别模型chinese_cht_mobile_v2.0_rec_infer乱码（或者是字典错乱）问题

### ISSUE THREAD

**Issue by ThatMyAurora** [PaddlePaddle/PaddleOCR#11949]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows11/Linux
- 版本号/Version：Paddle：  PaddleOCR：release2.7
- 运行指令/Command Code：tools/infer  /predict_rec.py
使用chinese_cht_mobile_v2.0_rec_infer开源模型，以及对应字典chinese_cht_dict.txt进行繁体中文识别，输出结果全是乱码，我个人觉得应该是字典顺序错乱。以繁体中文的《滕王阁序》为例：

正确的原文：
豫章故郡，洪都新府。星分翼軫，地接衡廬。襟三江而帶五湖，控蠻荊而引甌越。物華天寶，龍光射牛鬥之墟；人傑地靈，徐孺下陳蕃之榻。雄州霧列，俊採星馳。臺隍枕夷夏之交，賓主盡東南之美。都督閻公之雅望，棨戟遙臨；宇文新州之懿範，襜帷暫駐。十旬休假，勝友如雲；千里逢迎，高朋滿座。騰蛟起鳳，孟學士之詞宗；紫電青霜，王將軍之武庫。家君作宰，路出名區；童子何知，躬逢勝餞。
時維九月，序屬三秋。潦水盡而寒潭清，煙光凝而暮山紫。儼驂騑於上路，訪風景於崇阿；臨帝子之長洲，得天人之舊館。層巒聳翠，上出重霄；飛閣流丹，下臨無地。鶴汀鳧渚，窮島嶼之縈迴；桂殿蘭宮，即岡巒之體勢。
披繡闥，俯雕甍，山原曠其盈視，川澤紆其駭矚。閭閻撲地，鐘鳴鼎食之家；舸艦彌津，青雀黃龍之舳。雲銷雨霽，彩徹區明。落霞與孤鶩齊飛，秋水共長天一色。漁舟唱晚，響窮彭蠡之濱；雁陣驚寒，聲斷衡陽之浦。
遙襟甫暢，逸興遄飛。爽籟發而清風生，纖歌凝而白雲遏。睢園綠竹，氣凌彭澤之樽；鄴水朱華，光照臨川之筆。四美具，二難並。窮睇眄於中天，極娛遊於暇日。天高地迥，覺宇宙之無窮；興盡悲來，識盈虛之有數。望長安於日下，目吳會於雲間。地勢極而南溟深，天柱高而北辰遠。關山難越，誰悲失路之人？萍水相逢，盡是他鄉之客。懷帝閽而不見，奉宣室以何年？
嗟乎！時運不齊，命途多舛。馮唐易老，李廣難封。屈賈誼於長沙，非無聖主；竄梁鴻於海曲，豈乏明時？所賴君子見機，達人知命。老當益壯，寧移白首之心？窮且益堅，不墜青雲之志。酌貪泉而覺爽，處涸轍以猶歡。北海雖賒，扶搖可接；東隅已逝，桑榆非晚。孟嘗高潔，空餘報國之情；阮籍猖狂，豈效窮途之哭！
勃，三尺微命，一介書生。無路請纓，等終軍之弱冠；有懷投筆，慕宗愨之長風。舍簪笏於百齡，奉晨昏於萬里。非謝家之寶樹，接孟氏之芳鄰。他日趨庭，叨陪鯉對；今茲捧袂，喜託龍門。楊意不逢，撫凌雲而自惜；鍾期既遇，奏流水以何慚？
嗚乎！勝地不常，盛筵難再；蘭亭已矣，梓澤丘墟。臨別贈言，幸承恩於偉餞；登高作賦，是所望於羣公。敢竭鄙懷，恭疏短引；一言均賦，四韻俱成。請灑潘江，各傾陸海云爾：
滕王高閣臨江渚，佩玉鳴鸞罷歌舞。
畫棟朝飛南浦雲，珠簾暮卷西山雨。
閒雲潭影日悠悠，物換星移幾度秋。
閣中帝子今何在？檻外長江空自流。

我识别的文字结果：
秘實歌承：I承只時·買入電影°I我衝曬·症二工而稱工I·R纖戰而司概武
啊垂天實、I孔職平鬥叉T、陝I電：各種下匯業五電：I叫雲°後母員概·工匯
I秉頁二又“買工儘重南了美·承承屬公了I王“敗戰驚艦手三文只叫乙戰稱、驚雕暫
I·T角瓜便“假又I工之工氏承T“圍I間及·L戰I鳳：孟數工叉司之壘壘電冒電
工將電叉武噴·家君代字：夥出名雁：（子們4：獸承膠驚
呼雜孔月”RI二隻·管爪孟而I質電：I飛概而承I壘·睡壓購改工電“計風景
欣受師、點電了叉R洲、算天人了T會·I邏承叉：出電電、飛團武於“下輛無I
糯了寬叉：電員順五愛T”I氏肅員：I州症五I點
天稱I、TI實“L原I氏通T、T平紅千戰T·禹屬形I佔I曬出食之多、所艦
職承：實承電電工師·工經所電：夥徽通門·愛電興T承T飛：I爪王及天一孔·M丹
順晚：獸電影慧了濱、雁價驚實”實獻沖膜了通
承種電標、T興T飛·X（發而電風出、纖歌.而工遙·I圍總代°氣變叉承又
電：乳入天平：T照艦1叉氧·A業員：工戰五·電鬥所入田天、T氏通放氏員·天員
IT：覽字電之無霸、興慧悲及、識盈惠之有數·更系文改員下、月足實放雲間·I執
IM兩運承：黑I員TT天氏·LTI連：部王王配叉人°年入I邏：孟置I鐵叉名
Q電蘭而不員”承員系以G年
唯工！R實不T命為名減-屬I以之“子電戰式-I員部成天叉“T無工工、電
愛鵬叉TI：黑叉門時？氏（員了冒戀、E人所武·王員孟I”實移鬥買五八？電F孟
叉：不壓員壘工王·電為系而I叉、隱T戰以飛歌·T濟點話：氏意可E”重稱員出
桑樹T晚·王買員電：ZM只國工價：I範資孔：黑文電途工照
乳：二尺俄A“一分工出，無殿講顯“無級電叉號二看便民賢“無守戰又系風
各徽戰放員歌：承員風放電更“J講家叉實樹·我孟氏叉平織·I員纜度”町徑無興
冬然秋只、工子竈I·標意不篷：無愛員而員價、種輯氏T：冬職服以G購
鳳平！腰出不常：感邀戰再：爾豆乳系、性承已艦·點日順業：王承風放實驚史承
高/T：是I王叉承入·R稱識便：王只電引：一員叉T：T實俱氏·戰I無工、又(
陸祥工爾
睡工亮閣艦工貿“佩工順賽電歌戰
電櫃戰飛西通工手承竈賽黑氏川市
間雲質影日彼悠、物授軍移繁度秋
閣田電子公G承“概間系式座員職

请问有人遇到类似的问题吗？

**Comment by ThatMyAurora** [comment]
问题解决了！
繁体中文有两个版本的模型，分别是chinese_cht_mobile_v2.0_rec_infer（V2版，下载地址https://bj.bcebos.com/ai-studio-online/ef65f0b339e1426da22c59fed2fd03e23c49009a71d7480e90aa8bb2c665f464?authorization=bce-auth-v1%2F5cfe9a5e1454405eb2a975c43eace6ec%2F2022-09-04T15%3A26%3A50Z%2F-1%2F%2F629b09aa9f3740160be06766e1bb54d73d8cb04b34df0119f62c04d647a4bcc9&responseContentDisposition=attachment%3B%20filename%3Dchinese_cht_mobile_v2.0_rec_train.tar）和chinese_cht_PP-OCRv3_rec_infer（V3版，下载地址https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/chinese_cht_PP-OCRv3_rec_infer.tar），v2版和v3版的字典映射关系应该是不同的，最新版PaddleOCR文档里下载的好像是v2的模型，但给的是v3的字典。v3版的字典下载路径在这里：
https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/dict/chinese_cht_dict.txt
版本和字典对应好了就能够正常识别了

**Comment by UserWangZz** [comment]
感谢提供解决方案！

**Comment by UserWangZz** [comment]
可以提供一下具体的文档地址，方便我们进行修改，感谢

**Comment by ThatMyAurora** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md 中多语言识别模型列表里面中文繁体识别一栏的推理模型，点击后下载的是chinese_cht_mobile_v2.0_rec_infer.tar，即v2版本。和字典匹配的模型版本应该是  https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/chinese_cht_PP-OCRv3_rec_infer.tar

**Comment by UserWangZz** [comment]
感谢您提供的信息，我们会推进改进

**Comment by royalucifer** [comment]
請問有V2的字典嗎

**Comment by royalucifer** [comment]
請問是否有v2的字典？去哪載謝謝

**Comment by ThatMyAurora** [comment]
&nbsp;v2的字典在项目的路径应该是PaddleOCR/ppocr/utils/dict/chinese_cht_dict.txt
当然，我自己没有完全试过v2的模型和字典，目前来看v3的比较稳定










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月24日(星期五) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] PaddleOCR中开源的繁体中文识别模型chinese_cht_mobile_v2.0_rec_infer乱码（或者是字典错乱）问题 (Issue #11949)





 
請問是否有v2的字典？去哪載謝謝
