### ISSUE TITLE
检测模型预测时，gpu不可用

### ISSUE THREAD

**Issue by xsbrsg** [PaddlePaddle/PaddleOCR#11945]
- 系统环境/System Environment：Ubuntu 20.04.6 LTS
- 版本号/Version：paddlepaddle-gpu    2.6.1.post112  
- 镜像：registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda11.2-cudnn8.2-trt8.0
- 运行指令/Command Code：
   python tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./doc/imgs_en/img_10.jpg" Global.pretrained_model="./output/db_mv3/best_accuracy"
- 完整报错/Complete Error Message：
  grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.10/dist-packages/paddle/base/framework.py:688: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
E0416 11:45:15.529166  7591 place.cc:333] Cannot use GPU because there is no GPU detected on your machine
报错检测不到GPU，但同一个镜像中，训练模型时GPU正常使用。

尝试 paddle.device.is_compiled_with_cuda()  输出True
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/61486634/692d031b-88dc-45c8-8de8-e01232c4cc56)

尝试 paddle.utils.run_check()，输出结果如下：
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
[2024-04-16 11:15:35,214] [ WARNING] install_check.py:60 - You are using GPU version PaddlePaddle, but there is no GPU detected on your machine. Maybe CUDA devices is not set properly.
 Original Error is 
I0416 11:15:35.223839  7355 program_interpreter.cc:212] New Executor is Running.
I0416 11:15:35.321169  7355 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> 

请问可能是哪里的问题？

**Comment by Liyulingyue** [comment]
可以看看这个回复：https://github.com/PaddlePaddle/Paddle/issues/63552#issuecomment-2058559298

**Comment by xsbrsg** [comment]
> 可以看看这个回复：[PaddlePaddle/Paddle#63552 (comment)](https://github.com/PaddlePaddle/Paddle/issues/63552#issuecomment-2058559298) 【你安装的paddle对应的cuda是11.2版本的

显卡是nvidia A5000，cuda11.2应该是可以的。镜像用的是官方提供的cuda11.2-paddle2.6.1的镜像，我刚尝试了一下把容器重启，其他什么都没变，就正常可以检测到GPU了。不太明白是为什么
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/61486634/504083f3-3e06-4a02-8862-095a963460cf)
