### ISSUE TITLE
package PPORCLabel into EXE file

### ISSUE THREAD

**Issue by Zhang-Tianxu** [PaddlePaddle/PaddleOCR#11940]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：**Windows 11**
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
        * PaddlePaddle:2.6.1
        * PaddleOCR 2.7.5
- 运行指令/Command Code：No
- 完整报错/Complete Error Message：

[abelImg](https://github.com/HumanSignal/labelImg?tab=readme-ov-file#windows)  provide method to package into EXE file, Can PPOCRLabel be packaged into an EXE file? If so, how to package it?

I tried hard to package it using PyInstaller, still can't work properly

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/19359257/153832fc-7488-4cba-b7ad-ab82093cab04)

**Comment by Zhang-Tianxu** [comment]
I solved this problem in an inelegant way.

I copied all dependencies, such as paddle, paddleocr, etc., into `_internal` directory after excute following cmd:
```
pyinstaller --hidden-import=pyqt5 --hidden-import=lxml  PPOCRLabel.py -p ./libs -p ./ -w
```

Then you may encounter the problem in the picture, copy directory `resources` under PPOCRLabel into `_internal` can solve the problem.

Although I solved this problem, 

**I  STILL LOOK FORWARD TO AN ELEGANT SOLUTION FROM THE OFFICIAL**

**Comment by UserWangZz** [comment]
这边会找相关同学跟进一下，感谢您的建议

**Comment by UserWangZz** [comment]
We will contact relevant people to follow up. Thank you for your suggestion.

**Comment by TingquanGao** [comment]
Thx. We don't support to package to EXE file now. If you have a good solution, welcome new PR for PaddleOCR.

**Comment by ad5014858** [comment]
@Zhang-Tianxu hi，I used the same method as you to solve the problem, but a few more issues came up, did you show up and solve it or didn't show up? 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/55981213/111621a8-1276-4182-92f9-17864b8e8718)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/55981213/fe9a13fa-e912-476a-bf73-e441709ba65a)

**Comment by SWHL** [comment]
PPOCRLabel project has moved [PFCCLab/PPOCRLabel](https://github.com/PFCCLab/PPOCRLabel). For follow-up questions, please move to this repo to ask!

**Comment by Zhang-Tianxu** [comment]
> @Zhang-Tianxu hi，I used the same method as you to solve the problem, but a few more issues came up, did you show up and solve it or didn't show up?
> ![image](https://private-user-images.githubusercontent.com/55981213/329975620-111621a8-1276-4182-92f9-17864b8e8718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzAxNDMsIm5iZiI6MTcyMTQyOTg0MywicGF0aCI6Ii81NTk4MTIxMy8zMjk5NzU2MjAtMTExNjIxYTgtMTI3Ni00MTgyLTkyZjktMTc4NjRiOGU4NzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIyNTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjE2MzQyMTMzOGFhZGQ1NzNiZThlYzdiNzcyNTFhYmY5YWE5NzU4ZGJmZjU5NTU5M2NlNGEwOGZmNGRmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WPouaOfalpPTv54qBlIsHnY4YtI8jz_kDO_L0afeKTU)
> ![image](https://private-user-images.githubusercontent.com/55981213/329977563-fe9a13fa-e912-476a-bf73-e441709ba65a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzAxNDMsIm5iZiI6MTcyMTQyOTg0MywicGF0aCI6Ii81NTk4MTIxMy8zMjk5Nzc1NjMtZmU5YTEzZmEtZTkxMi00NzZhLWJmNzMtZTQ0MTcwOWJhNjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIyNTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZWNhYWNmMjI4ZWU0YWE1YWQwN2U1ZmM0N2QxNzhlMDI5YWMwMDllNmI3NDYwNDFjNDVkM2ZhOTg0MjAwZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ceOfhXDeCtFn9sWQBQPmE6cPGRzBpTs49A4YAElXK18)

@ad5014858 
Don't use `--windowed`/`-w`, use `-c`:

following cmd works for me:

`pyinstaller --hidden-import=pyqt5 --hidden-import=lxml main.py -n labelSoftware -p ./libs -p ./`
