### ISSUE TITLE
PPOCRLabel 标注时 识别内容修改输入不了中文

### ISSUE THREAD

**Issue by Gpy23** [PaddlePaddle/PaddleOCR#11942]
## 背景
PPOCRLabel 标注时 识别内容修改输入不了中文
<img width="591" alt="1713250193724" src="https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/3ac56009-a0cf-41f7-b254-b3ad4bb1d9d2">
红框中尝试输入中文，但是不管怎么切换输入法打出来的都是字母

**Comment by Gpy23** [comment]
是部署在服务器，远程连服务器操作的情况下，在服务器本地标注时切换输入法可以正常输入中文

**Comment by Gmgge** [comment]
你把本地机器的输入法切换成英文，服务器的输入法改成中文试试呢？

**Comment by UserWangZz** [comment]
试一下选中标注框，然后ctrl+E来修改

**Comment by SWHL** [comment]
因PPOCRLabel已经搬家了，后续有问题请移步[PPOCRLabel](https://github.com/PFCCLab/PPOCRLabel)提问哈！
此issue先行关闭了。
