### ISSUE TITLE
基于python引擎推理，速度过慢

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1195]
您好，我在T4卡上，进行python引擎串联推理，使用repo中的图片，平均一张图片在2s以上，开了gpu，开了MKLDNN，请问这个是什么原因呢？
![image](https://user-images.githubusercontent.com/43515926/99503924-c5411f00-29b9-11eb-8df8-9f39c23e2c1d.png)
![image](https://user-images.githubusercontent.com/43515926/99503964-d5f19500-29b9-11eb-832d-c31909e691c0.png)
单独执行识别推理，一张文字图片要1s钟。
![image](https://user-images.githubusercontent.com/43515926/99505924-6c26ba80-29bc-11eb-8b0f-04936297266c.png)

**Comment by MissPenguin** [comment]
使用gpu进行预测时，第一张图需要显存资源初始化，耗时较多，完成模型加载后，之后的预测时间会明显缩短。可以多跑一些图，把每张图的耗时打出来看下耗时变化。

**Comment by zcswdt** [comment]
> 使用gpu进行预测时，第一张图需要显存资源初始化，耗时较多，完成模型加载后，之后的预测时间会明显缩短。可以多跑一些图，把每张图的耗时打出来看下耗时变化。

不是这个初始化资源的问题，在utility.py文件关闭GPU，257张图片需要32s。然而开了GPU进行预测，257张图片需要101s.

关闭gpu耗时如下
![image](https://user-images.githubusercontent.com/43515926/99638780-b625a400-2a81-11eb-9682-51bc9bee3fb3.png)

开启gpu耗时如下：
![image](https://user-images.githubusercontent.com/43515926/99639172-42d06200-2a82-11eb-8801-42793ccc6b81.png)

而且开启GPU的时候报了一个错啊，百度也没百度到这个是什么原因造成的。
E1119 08:12:51.983549  3260 analysis_config.cc:73] Please compile with gpu to EnableGpu()
![image](https://user-images.githubusercontent.com/43515926/99639328-70b5a680-2a82-11eb-9c1f-9a04c6a1b17c.png)

**Comment by MissPenguin** [comment]
是装的gpu版的paddle吗

**Comment by zcswdt** [comment]
> 是装的gpu版的paddle吗

对，奇怪的是装的paddle-gpu2.0版本的，pip3 lisit中显示有paddle-gpu，但是推理就是耗时。
![image](https://user-images.githubusercontent.com/43515926/99743852-7dcda680-2b11-11eb-8a4a-c51b5a51dfd4.png)

后来我Pip3 uninstall paddlepaddle-gpu，然后重新安装了paddlegpu2.0版本的。python3 -m pip install paddlepaddle-gpu==2.0.0b0 -i https://mirror.baidu.com/pypi/simple

然后在执行python引擎推理，耗时居然正常了，不理解这是什么操作。
