### ISSUE TITLE
连续推理报错。     ExternalError: CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.       [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at ..\paddle\phi\kernels\gpu\rnn_kernel.cu.cc:86)       [operator < rnn > error]

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11965]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

连续推理报错。   

cuda 10.2
cudnn:8.7 

paddlepaddle 2.5.2

ExternalError: CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.       [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at ..\paddle\phi\kernels\gpu\rnn_kernel.cu.cc:86)       [operator < rnn > error]

**Comment by UserWangZz** [comment]
可以检查一下paddle版本和cuda版本是否匹配

**Comment by nissansz** [comment]
卸载所有nvidia驱动cuda, cudnnn, 再次安装cuda 10.2 + cudnn7.6.5 + paddle 2.3.2 好像速度回来了，3秒一张
