### ISSUE TITLE
运行python PPOCRLabel.py --lang ch时，报错Namespace' object has no attribute 'return_word_box'

### ISSUE THREAD

**Issue by Gpy23** [PaddlePaddle/PaddleOCR#11968]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：代码：PaddleOCR-release-2.7.1          PaddlePaddle：2.6.1    PaddleOCR： 2.7.3     问题相关组件/Related components：PaddleLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
<img width="674" alt="1713494541052" src="https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/c4f1cea8-950e-436c-9d6b-f011e6ce24d8">

**Comment by changdazhou** [comment]
已经为您记录了哈，我们正在验证

**Comment by changdazhou** [comment]
建议使用release2.7.0分支哈，2.7.1分支存在bug

**Comment by Gpy23** [comment]
换成release2.7.0也是一模一样的报错，PaddleOCR-release-2.7.0   PaddlePaddle：2.6.1    PaddleOCR： 2.7.3  PPOCRLabel：             2.1.3   这几个匹配吗，可以正常用的起来吗？

**Comment by changdazhou** [comment]
建议尝试PaddlePaddle：2.5.2 PaddleOCR： 2.7.0 以及PaddleOCR： 2.7.0中对应的PPOCRLabel，如果还是报错，我们会联系对应方向的同学解决

**Comment by Gpy23** [comment]
按您说的试验过了，还是一样的报错
可能是paddleocr这个包的问题  2.7.0.0-2.7.0.2如下图报错
<img width="932" alt="2eaf9d3b9b56b434c312d0a9657dd73" src="https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/d44f6521-64e6-4dbb-b33d-2a2339d13b1c">
2.7.0.3-2.7.3如下图报错
<img width="660" alt="25b6aac077d7cf520c8009d9c0f85a1" src="https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/74ae945c-6689-41e9-8b32-bf9fb401a851">
2.7.0.0 以下 2.6.x.x  python PPOCRLabel.py --lang ch   可以打开  但是用的就是PP-OCRv3，我想用2.7的PP-OCRv4

**Comment by UserWangZz** [comment]
pip install PPOCRLabel  # 安装

# 选择标签模式来启动
PPOCRLabel --lang ch  # 启动【普通模式】，用于打【检测+识别】场景的标签
可以尝试一下使用pip安装PPOCRLabel，使用下面方式启动PPOCRLabel

**Comment by Gpy23** [comment]
PPOCRLabel --lang ch  这种方式可以打开，谢谢

**Comment by shesung** [comment]
现在pypi上最新的whl包2.7.3里面，没有return_word_box相关代码。
