### ISSUE TITLE
竖向文字识别

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleOCR#11974]
## 背景

各位大佬,现在有没有什么orc支持中文竖向的识别.
![qq2](https://github.com/PaddlePaddle/PaddleOCR/assets/29450812/42387204-09a2-4a54-b201-1b74fd2567a1)

还有个问题,就是哪种识别算法对全图识别较好, 我可以简单训练一下.不需要检测直接识别文字

**Comment by UserWangZz** [comment]
检测的话，针对竖向文本建议是增加数据量，识别阶段的话，建议矫正为横向，直接旋转文本会导致置信度大的下降，甚至是检测不出。
