### ISSUE TITLE
How to disable DEBUG?

### ISSUE THREAD

**Issue by Roboxkin** [PaddlePaddle/PaddleOCR#11977]
Hello!
How to disable DEBUG ?

```Python
ocr = PaddleOCR(use_angle_cls=True, lang='en')
result = ocr.ocr(image, cls=True, det=False)
result1 = result[0][0][0]
print(f'Text response = "{result1}"')
```
![Screenshot_1](https://github.com/PaddlePaddle/PaddleOCR/assets/39112555/37797bad-7189-4188-abdd-94229e8b0795)

Thank you

**Comment by Roboxkin** [comment]
I found a solution to the problem, but I don't think it's correct.

C:\Users\{userName}\AppData\Local\Programs\Python\Python310\Lib\site-packages\paddleocr\ppocr\utils\logging.py

![Screenshot](https://github.com/PaddlePaddle/PaddleOCR/assets/39112555/0fa1aeed-bb3e-4389-88c2-4c56af2b5490)

Result

![Screenshot](https://github.com/PaddlePaddle/PaddleOCR/assets/39112555/9046e8ec-b5f6-4698-80b1-03d4a49d290f)

But this is not correct, no one should mess with the source code.
Is there a solution to do this differently?

**Comment by jzhang533** [comment]
an alternative way to do so without changing source code.

```python
from ppocr.utils.logging import get_logger
import logging
logger = get_logger()
logger.setLevel(logging.ERROR)
```

**Comment by Roboxkin** [comment]
> an alternative way to do so without changing source code.
> 
> ```python
> from ppocr.utils.logging import get_logger
> import logging
> logger = get_logger()
> logger.setLevel(logging.ERROR)
> ```

Thanks a lot!
Problem solved

**Comment by eccstartup** [comment]
> an alternative way to do so without changing source code.
> 
> ```python
> from ppocr.utils.logging import get_logger
> import logging
> logger = get_logger()
> logger.setLevel(logging.ERROR)
> ```

What is `ppocr`?
