### ISSUE TITLE
请问对于训练的图片进行标注时，什么样的标注方式更适合

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1197]
![Snipaste](https://user-images.githubusercontent.com/48552037/99515593-1f48e100-29c8-11eb-953c-6fec74d4cc6c.jpg)
如图的这种非常规字体，分别将每个字符都标注出来后（想训练字体单字符的识别），又把其一行作为整体标注出来（想提高检测时的整体分割正确率）。这种标注法可行吗？
一般对于OCR，不同的标注框划分方式会对训练造成什么影响？

**Comment by MissPenguin** [comment]
一般情况下，希望检测到单字符就按单字符标，希望检测整行就按整行标，这种混标的方式可能不太合适，但没有具体实践过哈。

**Comment by singlebear** [comment]
> 一般情况下，希望检测到单字符就按单字符标，希望检测整行就按整行标，这种混标的方式可能不太合适，但没有具体实践过哈。
目前用混编的数据训练发现不会弹出loss信息，检查了两个配置文件也没什么问题。但是发现奇怪的是输出的predicts_db文件的格式和icdar的数据不一致。predicts_db是icdar的，predicts_db（复件）是自己的。pp.txt是标签文件，是标签文件格式有问题么？但是检查了下没发现问题，\t分割文件路径和信息也注意到了。
[predicts_db（复件）.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5565036/predicts_db.txt)
[predicts_db.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5565037/predicts_db.txt)
[pp.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5565038/pp.txt)

**Comment by singlebear** [comment]
试着删除整体框后还是没有Loss输出只自己保存节点文件，应该不是混编的原因。

**Comment by singlebear** [comment]
知道为什么不运行了，是因为样本量太少，才百来个，处理下每个复制5个后数据量上去就开始显示loss等信息
