### ISSUE TITLE
微调ppocrv4的rec_server模型，关于数据增强的问题

### ISSUE THREAD

**Issue by zhanghengjiayou** [PaddlePaddle/PaddleOCR#11980]
应用场景下实际图像制作了5000张数据集，训练过后没有预训练模型准确率高，低5个百分点，看图像存在多识别、漏识别、噪声干扰遮挡，我应该如何制作数据集去改善这个问题啊，需要多少数据量呢，希望老师们多多指导

**Comment by UserWangZz** [comment]
一般识别阶段需要比较大的数据量，可以加强一下模型识别结果不准确的case的数据

**Comment by zhanghengjiayou** [comment]
> 一般识别阶段需要比较大的数据量，可以加强一下模型识别结果不准确的case的数据

谢谢指导

**Comment by UserWangZz** [comment]
没事的
