### ISSUE TITLE
paddleOCR运行印章比对模型报错

### ISSUE THREAD

**Issue by qingjingjue** [PaddlePaddle/PaddleOCR#11986]
采用paddleOCR运行印章比对模型时报错

- 系统环境/System Environment：win64
- 版本号/Version：
    Paddle：2.5.1  
    PaddleOCR：2.7.3 
    问题相关组件/Related components：tool/infer_e2e.py
- 运行指令/Command Code：python tools/infer_e2e.py  -c configs/pgnet_r50_vd_seal/config.yml  -o Global.pretrained_model=./pgnet_r50_vd_seal/best_accuracy  Global.infer_img=../data_test/raw/image2.png
- 完整报错/Complete Error Message：
  
![测试](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/c697c850-b4ea-4301-9209-ec91bcfe1f91)

**Comment by qingjingjue** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/8daccfe0-70f2-4751-be5f-1daecbd8f333)
加了这个就可以输出了，但是不知道会不会影响其他的应用

**Comment by qingjingjue** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/735745ba-575e-4a4b-a127-8aa41ac1005b)
danshizheg
但是这个识别效果有问题，是不是不能直接改为32位，希望解答一下

**Comment by qingjingjue** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/da3326b7-7351-4d67-a989-2813a9dee05e)
同时会提示模型参数无法无法匹配

**Comment by qingjingjue** [comment]
> 可以提供一下config文件的信息吗

Global:
  use_gpu: false
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/pgnet_r50_vd_seal_run/
  save_epoch_step: 300
  eval_batch_step:
  - 0
  - 400
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/train_step1/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  valid_set: totaltext
  save_res_path: ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: EN
  max_text_length: 50
  max_text_nums: 10
  tcl_len: 64
  load_static_weights: false
Architecture:
  model_type: e2e
  algorithm: PGNet
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
  Neck:
    name: PGFPN
  Head:
    name: PGHead
Loss:
  name: PGLoss
  tcl_bs: 32
  max_text_length: 50
  max_text_nums: 10
  pad_num: 6623
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 50
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: PGPostProcess
  score_thresh: 0.5
  mode: fast
Metric:
  name: E2EMetric
  mode: A
  gt_mat_dir: ./train_data/total_text/gt
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  main_indicator: f_score_e2e
Train:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/
    label_file_list:
    - ./train_data/label_2_rotate_transform_final.txt
    - ./train_data/label_3_rotate_transform_final.txt
    ratio_list:
    - 1.0
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTrain: null
    - PGProcessTrain:
        batch_size: 5
        min_crop_size: 24
        min_text_size: 4
        max_text_size: 512
    - KeepKeys:
        keep_keys:
        - images
        - tcl_maps
        - tcl_label_maps
        - border_maps
        - direction_maps
        - training_masks
        - label_list
        - pos_list
        - pos_mask
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 5
    num_workers: 16
Eval:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/
    label_file_list:
    - ./train_data/label_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTest:
        character_dict_path: ppocr/utils/ppocr_keys_v1.txt
    - DetResizeForTest:
        image_shape:
        - 512
        - 512
        padding: true
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - texts
        - ignore_tags
        - img_id
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null

**Comment by qingjingjue** [comment]
好的，详见附件



***@***.***
 
发件人： WangZ
发送时间： 2024-04-24 10:02
收件人： PaddlePaddle/PaddleOCR
抄送： CMS; Manual
主题： Re: [PaddlePaddle/PaddleOCR] paddleOCR运行印章比对模型报错 (Issue #11986)
可以提供一下config文件的信息吗

**Comment by qingjingjue** [comment]
> 可以提供一下config文件的信息吗

有哪些地方需要调整吗

**Comment by UserWangZz** [comment]
目前看来，有点像head网络初始化有问题，因为我看字典使用的是ppocr_keys_v1.txt，它里面共有6623个字符，你可以往这方面考虑一下

**Comment by qingjingjue** [comment]
> 目前看来，有点像head网络初始化有问题，因为我看字典使用的是ppocr_keys_v1.txt，它里面共有6623个字符，你可以往这方面考虑一下
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/d8e74ee5-c2e3-41d3-adf6-cf0b3870d1bc)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/3b22ff25-f036-4916-8b35-183b5cf9fe40)

**Comment by qingjingjue** [comment]
> 可以直接用训练权重里提供的config.yml 文件试下

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/fb0c4ac2-e7c5-4208-8f0d-541c5a7f9dff)
是这个吗

**Comment by tink2123** [comment]
这个：
<img width="885" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/31891223/84488816-acae-4d24-806e-62f9f881c003">

**Comment by qingjingjue** [comment]
> 这个： <img alt="image" width="885" src="https://private-user-images.githubusercontent.com/31891223/325103593-84488816-acae-4d24-806e-62f9f881c003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDAyOTgsIm5iZiI6MTcxMzkzOTk5OCwicGF0aCI6Ii8zMTg5MTIyMy8zMjUxMDM1OTMtODQ0ODg4MTYtYWNhZS00ZDI0LTgwNmUtNjJmOWY4ODFjMDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGQ0MDg2OGMzNTQxMmIyMjRjNzFhOTY5NzBiOGY3OWIwYzhlNzYzNDdiMzY2NjQyNzljOTRmYWE0YTdhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B9JA73Kl8MTOc0LWUjtVjBOnG4bEC9xC5qqyYKfd6E">

刚刚用的就是这个，上面提供的config信息即是这个文件
![584E77BC](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/c31de028-c422-4157-929d-a74bc5a187ca)

**Comment by qingjingjue** [comment]
> 这个： <img alt="image" width="885" src="https://private-user-images.githubusercontent.com/31891223/325103593-84488816-acae-4d24-806e-62f9f881c003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDAyOTgsIm5iZiI6MTcxMzkzOTk5OCwicGF0aCI6Ii8zMTg5MTIyMy8zMjUxMDM1OTMtODQ0ODg4MTYtYWNhZS00ZDI0LTgwNmUtNjJmOWY4ODFjMDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGQ0MDg2OGMzNTQxMmIyMjRjNzFhOTY5NzBiOGY3OWIwYzhlNzYzNDdiMzY2NjQyNzljOTRmYWE0YTdhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B9JA73Kl8MTOc0LWUjtVjBOnG4bEC9xC5qqyYKfd6E">

或者你们那有最新的吗，可以私发我一下，我换上去试试

**Comment by qingjingjue** [comment]
> 这个： <img alt="image" width="885" src="https://private-user-images.githubusercontent.com/31891223/325103593-84488816-acae-4d24-806e-62f9f881c003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDgwMTUsIm5iZiI6MTcxMzk0NzcxNSwicGF0aCI6Ii8zMTg5MTIyMy8zMjUxMDM1OTMtODQ0ODg4MTYtYWNhZS00ZDI0LTgwNmUtNjJmOWY4ODFjMDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDY5NDljNjc5NmY4MzY4YmE2NTZmYzc3NzI3ZWM5MDBiYjRjNWM1ZDc1ZjI2ZGJlODAxMjIxZmMxZGUwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LIn-fxRz7YvECC9krBpD58ZT_Gruh99er-FNalVG0LI">

也可以看看目前这个文件和你们现在最新文件的差异

**Comment by qingjingjue** [comment]
> 可以直接用训练权重里提供的config.yml 文件试下

后续怎么处理呢

**Comment by UserWangZz** [comment]
这边会记录一下，尝试复现问题

**Comment by qingjingjue** [comment]
> 这边会记录一下，尝试复现问题

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/ef00a9bc-00c0-40c7-88f2-5a0d661fdcbc)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73062036/56cca382-6214-45b7-a48e-82a9c542986d)
图中是两份config在推理环节可能比较重要的差异，可以看一下
如果有进展的话可以跟我说一下，需要远程控制的话，我这边可以协助复现，因为这个跟我们后续的一个排期计划比较相关，有劳了，感谢！

**Comment by tink2123** [comment]
训练和推理使用了不同的配置吗？ 看到字典不同应该是导致参数无法加载最主要的问题。 如果使用了ic15_dict.txt 训练，请同样使用这个ic15_dict.txt推理。
另外：训练和推理的配置文件应保持一致

**Comment by qingjingjue** [comment]
> 训练和推理使用了不同的配置吗？ 看到字典不同应该是导致参数无法加载最主要的问题。 如果使用了ic15_dict.txt 训练，请同样使用这个ic15_dict.txt推理。 另外：训练和推理的配置文件应保持一致

我没有进行训练，图中左侧的是打码拉下来后e2e的默认配置文件，图中右侧才是印章模型配套的config，目前这个config中的训练和推理用的txt是一致的。目前是打算直接使用模型和配套的config，现象是使用下载下来的模型和配置文件会有报错。

**Comment by UserWangZz** [comment]
> > 目前看来，有点像head网络初始化有问题，因为我看字典使用的是ppocr_keys_v1.txt，它里面共有6623个字符，你可以往这方面考虑一下
> > ![image](https://private-user-images.githubusercontent.com/73062036/325072448-d8e74ee5-c2e3-41d3-adf6-cf0b3870d1bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDIyMzcsIm5iZiI6MTcxNDA0MTkzNywicGF0aCI6Ii83MzA2MjAzNi8zMjUwNzI0NDgtZDhlNzRlZTUtYzJlMy00MWQzLWFkZjYtY2YwYjM4NzBkMWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwNDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MmUxNTk0ZDQyNmJmNDI0NTAwMGViZWQ3NGRhMWFkMjcyOTljYzg4MWNmMzE5ZmU0YmMzYTQxMzI2MDE3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kuqAywJnHP-7F1Y708mVdAOD3NSXA1Ks2vRffEvLfYk)
> > ![image](https://private-user-images.githubusercontent.com/73062036/325072480-3b22ff25-f036-4916-8b35-183b5cf9fe40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDIyMzcsIm5iZiI6MTcxNDA0MTkzNywicGF0aCI6Ii83MzA2MjAzNi8zMjUwNzI0ODAtM2IyMmZmMjUtZjAzNi00OTE2LThiMzUtMTgzYjVjZjlmZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwNDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOWUyZTJhMGZiZDUxMGFlMDMwZmNkMmI4M2JjNGM2ZjlmMjJhNjIxNWQ2ZDFjMGU5MDIyMjYxMzE3NTZiZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mb4OA0X6nAJPFJv6P59y-cdbrtFTzIteLv58fW_oop4)

可以提供一下这个模型和config的下载地址，我这边尝试复现一下

**Comment by qingjingjue** [comment]
怎么发过去呢，要不加一下微信



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 晚上6:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR运行印章比对模型报错 (Issue #11986)




   
目前看来，有点像head网络初始化有问题，因为我看字典使用的是ppocr_keys_v1.txt，它里面共有6623个字符，你可以往这方面考虑一下
 
 
   
可以提供一下这个模型和config的下载地址，我这边尝试复现一下

**Comment by UserWangZz** [comment]
> 怎么发过去呢，要不加一下微信
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 晚上6:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR运行印章比对模型报错 (Issue #11986) 目前看来，有点像head网络初始化有问题，因为我看字典使用的是ppocr_keys_v1.txt，它里面共有6623个字符，你可以往这方面考虑一下 可以提供一下这个模型和config的下载地址，我这边尝试复现一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

贴个链接就好

**Comment by tink2123** [comment]
已线下沟通，此处close

**Comment by sadays22** [comment]
后来这个参数问题解决了吗

**Comment by sadays22** [comment]
> 已线下沟通，此处close

可以发一下怎么解决的吗
