### ISSUE TITLE
 Getting 'tensor_desc' is not supported by the create_py_reader_0 type variable.

### ISSUE THREAD

**Issue by BiggerBinBin** [PaddlePaddle/PaddleOCR#1198]
系统：win10，16G内存，I5-8400
GPU：GTX2060，
PaddleOcr 2.0rc版本
自己训练的文本检测和文本识别模型。在使用文本检测和文本识别串联时，出现错误：
使用命令：
E:\PaddleOCR>python tools/infer/predict_system.py --image_dir="E:/PaddleOCR/train_data/iron_test/" --det_model_dir="E:/PaddleOCR/good_modeling/iron_dec_modeling" --rec_model_dir="E:/PaddleOCR/good_modeling/iron_rec_modeling" --use_angle_cls=false

报错：
E1118 23:04:14.144709  2932 analysis_config.cc:72] Please compile with gpu to EnableGpu()
W1118 23:04:14.144709  2932 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 181, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 134, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "E:\PaddleOCR\tools\infer\predict_det.py", line 80, in __init__
    utility.create_predictor(args, mode="det")
  File "E:\PaddleOCR\tools\infer\utility.py", line 144, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
UnavailableError: Getting 'tensor_desc' is not supported by the create_py_reader_0 type variable. (at D:\2.0.0-rc0\paddle\paddle\fluid\framework\var_desc.cc:213)

**Comment by Yaoxingtian** [comment]
你好，请问你解决了吗？ 我也遇到这个问题，自己训练的文本识别模型。用的预训练模型是mobilev3的。但是我用官方提供的模型（mobilev1训练出来的）是可以用的，在predict_system.py中。刚开始用paddle还不太了解

**Comment by BiggerBinBin** [comment]
我出错的原因是，我没有转模型官网文档有写的：首先将DB文本检测训练过程中保存的模型，转换成inference model。以基于Resnet50_vd骨干网络，在ICDAR2015英文数据集训练的模型为例（模型下载地址)，可以使用如下命令进行转换：# -c后面设置训练算法的yml配置文件 # Global.checkpoints参数设置待转换的训练模型地址，不用添加文件后缀.pdmodel，.pdopt或.pdparams。 # Global.save_inference_dir参数设置转换的模型将保存的地址。 python3 tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.checkpoints="./models/det_r50_vd_db/best_accuracy" Global.save_inference_dir="./inference/det_db"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 上午10:07
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"我为谁活着"<1091313282@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR]  Getting 'tensor_desc' is not supported by the create_py_reader_0 type variable. (#1198)





 
你好，请问你解决了吗？ 我也遇到这个问题，自己训练的文本识别模型。用的预训练模型是mobilev3的。但是我用官方提供的模型（mobilev1训练出来的）是可以用的，在predict_system.py中。刚开始用paddle还不太了解

**Comment by littletomatodonkey** [comment]
你好，2种预测方式
1. 基于训练好的pretrained model(pdparams, pdopt后缀)，使用tools/infer_rec.py, infer_cls.py, infer_det.py进行预测，
2. 将上述模型使用`tools/export_model.py`进行导出(inference.pdiparams, inference.pdmodel)，使用tools/infer/predict_xxx.py进行预测

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
