### ISSUE TITLE
关于表格识别模型

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleOCR#11987]
1、数据集的问题
由于标注原图片的成本太高，我采用了wps把图片解析成表格（wps识别的效果较好），然后在专程html格式，生成网页在生成标注的图片。这种方式是否可行，对表格识别的结果有多大影响？如果必须用原图标注，有什么高效率的标注方式吗？
2、如果识别的表格复杂，比如内嵌多行多列的表格，识别效果不好。识别的单元格都重叠在一起。这种情况在训练的时候应该怎么优化？
3、表格格式识别错的情况，生成的表格不是正确的表格标签，比如识别出来的某一行，会缺少几个单元格。这种情况应该怎么优化？

**Comment by crackso** [comment]
其实这个问题我也和你一样，确实标注的成本太高了；于是我想了很多办法；
1，wps这个想法还是很不错的。相当于用别人的优点帮你生成一些；其实国内还有一家公司做表格还原很厉害，还有线条坐标，不过由于某些原因，人家关闭了，还加密了代码；
2，说说我目前的做法吧，开始是标注，发现效率太慢，修改和优化了ppocrlabel，主要是单元格循序调整，还有文字标注，非常费时。一个表格少说有400个多个格子，手都标费了；
3，生成差不多的样例表格，拿这个去混合样本训练，不过这样的话，精度肯定不会和原表一样的；
这样会有一些提升，但肯定没有原表标注好，优点也显而易见，就是快，看取舍，如果样本够，时间够，那标注是最优解；
个人经历，参考下；

**Comment by TingquanGao** [comment]
目前表格识别模型对于复杂一点表格识别效果较差，我们也在努力优化中，之后会放出下个版本。

**Comment by nissansz** [comment]
有新表格模型了吗？https://paddlepaddle.github.io/PaddleOCR/algorithm/table_recognition/algorithm_table_slanet.html

这个模型没法运行，怎么转换成onnx运行？
