### ISSUE TITLE
V4识别蒸馏模型预训练权重以及训练出现KeyError: 'valid_ratio'

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/PaddleOCR#11988]
V4识别蒸馏模型预训练权重以及训练出现KeyError: 'valid_ratio'，你们有做过验证吗，V4问题一大堆，预训练权重和yaml对不起来的ch_PP-OCRv4_rec_distill.yml 它的训练权重在哪

**Comment by UserWangZz** [comment]
抱歉，我找相关同学确定一下问题

**Comment by TingquanGao** [comment]
可以提供一下训练命令吗？我们这边复现一下。

**Comment by marsbzp** [comment]
ch_PP-OCRv4_rec_distill.yml 用这yaml训就复现啊，这issue之前也有人提过你们一直不修复的吗

**Comment by marsbzp** [comment]
预训练权重能给个匹配的吗

**Comment by tink2123** [comment]
v4 有一些遗留的问题，不推荐使用蒸馏的配置。bug在排期修复中，建议使用 https://github.com/PaddlePaddle/PaddleOCR/blob/main/configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml 来训练

**Comment by jaycecd** [comment]
> v4 有一些遗留的问题，不推荐使用蒸馏的配置。bug在排期修复中，建议使用 https://github.com/PaddlePaddle/PaddleOCR/blob/main/configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml 来训练

请问这个yml对应的预训练权重在哪里？目前手册上面给出的权重仅有蒸馏中student的：
![image](https://github.com/user-attachments/assets/56c46932-a1f4-4dc7-9089-850a01e7d80a)
对应的权重模型：
![image](https://github.com/user-attachments/assets/3fc14e7e-b3ec-4e6a-9fae-c917447c67e6)

**Comment by zhugexinxin** [comment]
我也一样的错误，找不到预训练模型，只有student，报错也是KeyError: 'valid_ratio'
