### ISSUE TITLE
自己训练的rec模型，为什么onnx推理结果比inference结果要更准

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#11983]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

自己训练的rec模型，为什么onnx推理结果比inference结果要更准，所有参数都相同，只是模型格式不同

paddle推理对比原文结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/6eaa9cd2-7f90-4daa-9feb-5d84150cceff)

onnx推理对比原文结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/b90505d7-cf07-450a-9e42-b9a9ff7fc5bb)

**Comment by tink2123** [comment]
正常来说不会的，请问推理代码使用的是同一份嘛？

**Comment by nissansz** [comment]
是的。都是用的rapidocr








--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: xiaoting  ***@***.***>
 

 
 发送时间: 2024-04-23 15:52:59
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] 自己训练的rec模型，为什么onnx推理结果比inference结果要更准 (Issue #11983)
 





 正常来说不会的，请问推理代码使用的是同一份嘛？

**Comment by tink2123** [comment]
不确定rapidocr中是否有额外操作，可以去他们仓库咨询下哈
