### ISSUE TITLE
同一个模型 python推理和ppocr label的识别结果不同

### ISSUE THREAD

**Issue by freeman745** [PaddlePaddle/PaddleOCR#11981]
使用v4模型推理，数字中的,大概率会被识别为.
比如3,000.00 会被识别为3.000.00
但是用ppocr label的自动标注就没有这种问题

**Comment by UserWangZz** [comment]
可以查看一下使用v4时检测模型的参数设置，不同的检测范围，也会影响识别结果

**Comment by freeman745** [comment]
刚试了下，直接python推理和ppocr label是一致的
pdserving的python版本不一致

**Comment by UserWangZz** [comment]
好的，感谢讨论

**Comment by freeman745** [comment]
感谢回复！
