### ISSUE TITLE
使用量化后的模型进行推理报错Delete Weight Dequant Linear Op Pass is not supported for per-channel quantization

### ISSUE THREAD

**Issue by Capricorn-18** [PaddlePaddle/PaddleOCR#11990]
根据官方的文档对训练好的模型进行量化之后得到的pdparams文件可以在infer_det.py和infer_rec.py运行，但是使用slim的export_model.py将量化的模型转成pdiparams文件之后，运行predict_det.py和predict_rec.py文件就报上面的问题了，想问一下这是为什么呢？

**Comment by TingquanGao** [comment]
pdiparams文件是静态图推理模型文件。具体是什么报错，可以贴一下报错信息吗？以及使用的命令是啥？

**Comment by Sunting78** [comment]
您好，超过一周未回复的问题将关闭，如未解决可以open或者重新提issue。

**Comment by nyh3174680732** [comment]
%cd ~
!python predict.py /home/aistudio/work/data/val/test.txt result.json

/home/aistudio
Model Arch: DETR
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
Traceback (most recent call last):
  File "/home/aistudio/predict.py", line 221, in <module>
    main(infer_txt, result_path, det_model_path, threshold)
  File "/home/aistudio/predict.py", line 204, in main
    detector = Detector(pred_config, det_model_path)
  File "/home/aistudio/predict.py", line 126, in __init__
    self.predictor, self.config = load_predictor(model_dir)
  File "/home/aistudio/predict.py", line 78, in load_predictor
    predictor = create_predictor(config)
NotImplementedError: (Unimplemented) Delete Weight Dequant Linear Op Pass is not supported for per-channel quantization (at ../paddle/fluid/framework/ir/delete_weight_dequant_linear_op_pass.cc:130)

**Comment by nyh3174680732** [comment]
通用错误求解答 将模型自动压缩之后使用predict.py预测报这个错误
