### ISSUE TITLE
请问PP-OCRv3和PP-OCRv4检测模型是用了哪些数据集训练的？

### ISSUE THREAD

**Issue by JIANG3330** [PaddlePaddle/PaddleOCR#11992]
请问PP-OCRv3和PP-OCRv4检测模型是用了哪些数据集训练的？hmean指标是在哪个数据集上评估的？
我在介绍文档中找不到相关的信息：https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/PP-OCRv4_introduction.md

**Comment by Sunting78** [comment]
您好，数据部分我们使用了公开数据以及收集的数据，进行了多次数据筛选。评测是主要由中文数据组成的场景比较全面的数据集。暂未公开。
