### ISSUE TITLE
annotation tool

### ISSUE THREAD

**Issue by baireddy0417** [PaddlePaddle/PaddleOCR#1199]
which is the preferable annotation tool for getting required format

**Comment by MissPenguin** [comment]
PaddleOCR has recommended several annotation tools: https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/data_annotation_en.md, but it may be necessary to convert to PaddleOCR required format manually.

**Comment by grasswolfs** [comment]
Maybe, PPOCRLabel is the preferable annotation tool for u now.
Thanks for your questions and this issue is closed, If u have more questions, u can reopen it or open a new issue freely.
