### ISSUE TITLE
繁体模型有更新计划么

### ISSUE THREAD

**Issue by TOMORINAONAO** [PaddlePaddle/PaddleOCR#11991]
1.目前测试v3的繁体模型效果是比较差的，看到多语言模型里日文和韩文都有v4版的，繁体模型什么时候有新的？
2.我测试时是网上复制一些新闻内容或公文，然后转成繁体字，在word里改变了几种字体测试。发现不同字体的识别效果都不太一样，标点符号漏的也很多，识别的准确率也不是很高，大概是70多的准确率。

**Comment by Sunting78** [comment]
您好，如果有高的精度要求可以使用真实数据finetune一下

**Comment by TOMORINAONAO** [comment]
> 请问一下finetine的话多少数据比较好

看场景了，我是简体+繁体+英文，同时包括横排文字和竖排文字，也就是6种情况的数据，一共用了一千多万张图片，在我自己的1w2字典下训练的效果还挺好。
paddleocr官方回答说过要保证字典种每个字符出现200次以上，可以参考一下。

**Comment by flow3rdown** [comment]
> > 请问一下finetine的话多少数据比较好
> 
> 看场景了，我是简体+繁体+英文，同时包括横排文字和竖排文字，也就是6种情况的数据，一共用了一千多万张图片，在我自己的1w2字典下训练的效果还挺好。 paddleocr官方回答说过要保证字典种每个字符出现200次以上，可以参考一下。

请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？

**Comment by TOMORINAONAO** [comment]
> 请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？
轻量版v4的识别模型，数据是网上的开源数据+我自己场景下的合成数据

**Comment by TOMORINAONAO** [comment]
> 
> 请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？

v4的轻量模型，数据是网上的开源数据+我自己场景下的合成数据，合成数据占大部分

**Comment by flow3rdown** [comment]
> > 请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？
> 
> v4的轻量模型，数据是网上的开源数据+我自己场景下的合成数据，合成数据占大部分

还想问下您有没有增大词表呢，我发现v4的词表里面很多繁体字是没有的

**Comment by TOMORINAONAO** [comment]
> > > 请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？
> > 
> > 
> > v4的轻量模型，数据是网上的开源数据+我自己场景下的合成数据，合成数据占大部分
> 
> 还想问下您有没有增大词表呢，我发现v4的词表里面很多繁体字是没有的

字典改了的，paddle默认字典6600字，我结合我的场景扩充到了12000字

**Comment by flow3rdown** [comment]
> > > > 请问您是基于哪个ocr模型finetune的呀，数据是生成的吗？
> > > 
> > > 
> > > v4的轻量模型，数据是网上的开源数据+我自己场景下的合成数据，合成数据占大部分
> > 
> > 
> > 还想问下您有没有增大词表呢，我发现v4的词表里面很多繁体字是没有的
> 
> 字典改了的，paddle默认字典6600字，我结合我的场景扩充到了12000字

感谢您的回答。方便加您一个联系方式吗，想跟你请教一下关于OCR训练的问题

**Comment by hecheng64** [comment]
这个怎么微调 可以列个详细步骤 @TOMORINAONAO @flow3rdown

**Comment by flow3rdown** [comment]
我这边的微调主要包括以下几步：
1. 收集开源数据+合成数据，扩充字典；
2. 继承模型原始head权重，并根据扩充的字典生成新的参数；
3. 冻结部分模型参数开始训练

**Comment by hecheng64** [comment]
@flow3rdown chinese_cht_PP-OCRv3_rec.yml  自己训练或者新增繁体字，需要往chinese_cht_dict.txt添加新增繁体字，是否有顺序要求？你是基于哪个微信微调吗？我 现在基于chinese_cht_PP-OCRv3_rec_train.tar 不知道可行吗

**Comment by skyler9901** [comment]
@hecheng64 请问你后来解决你上面的问题了嘛，我现在微调的时候发现效果一般，故来请教如下问题：
1. 新增字典后，顺序有要求吗？
2. 你在新增字典后，改检测头了吗？还是改了哪部分呀？

**Comment by flow3rdown** [comment]
@hecheng64 @skyler9901  很抱歉，之前没有看到问题没能及时回复。分享一下之前微调时我这边的操作：
1. 使用的模型的是 `ch_pp_ocr_v4_rec`，词表从6623扩充至8623，新增的字体直接加到了词表的最后面，没有考虑顺序；
2. 词表扩充后，CTC和GTC的head的维度会发生变化，这里直接继承原始的head权重，之后对新增的词表进行权重初始化（可参考language model扩充embedding的操作）
3. 微调时冻结了模型的主体部分，只微调少数参数

**Comment by ckmstydy** [comment]
> > 请问一下finetine的话多少数据比较好
> 
> 看场景了，我是简体+繁体+英文，同时包括横排文字和竖排文字，也就是6种情况的数据，一共用了一千多万张图片，在我自己的1w2字典下训练的效果还挺好。 paddleocr官方回答说过要保证字典种每个字符出现200次以上，可以参考一下。

您好，请问竖排文字训练的过程中直接把图片喂给模型的吗？还是将图片做了旋转？
