### ISSUE TITLE
NameError: name 'predict_system' is not defined

### ISSUE THREAD

**Issue by sugarandgugu** [PaddlePaddle/PaddleOCR#11997]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
MacBook M1  cpu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddlepaddle:2.6.1 paddleocr: 2.7.5
- 运行指令/Command Code：
- paddleocr --image_dir=/Downloads/1.jpg --type=structure --image_orientation=true
- 完整报错/Complete Error Message：
<img width="822" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/95059219/eeffb2fd-f4f2-4abc-9bc2-d35e56bacaa5">

**Comment by sugarandgugu** [comment]
去源码里面进行修改在54行没有导入predict_system导致，可以将第54行改为如下部分，然后再报错的第576行将改成class PaddleOCR(TextSystem)即可。
`from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem`
ref: https://blog.csdn.net/wang602125218/article/details/137175714

**Comment by UserWangZz** [comment]
感谢讨论，使用文档分析功能，也可以使用这个脚本ppstructure/predict_system.py哦

**Comment by xiaocode337317439** [comment]
> 去源码里面进行修改在54行没有导入predict_system导致，可以将第54行改为如下部分，然后再报错的第576行将改成class PaddleOCR(TextSystem)即可。 `from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem` ref: https://blog.csdn.net/wang602125218/article/details/137175714

在docker build如何去修改？
