### ISSUE TITLE
Can not import paddle core   libstdc++.so.6: version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by Gpy23** [PaddlePaddle/PaddleOCR#11998]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu22.04   cuda：12.0   cudnn：8.9.7
- 版本号/Version：Paddle：paddlepaddle-gpu   2.6.1.post120  PaddleOCR：paddleocr 2.7.3 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer_det.py -c configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_hgnet.yml -o Global.checkpoints=./output/rec_ppocr_v4_hgnet/best_model Global.infer_img=./test/20240423174434.jpg

- 完整报错/Complete Error Message：
- 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/63e8b99d-5a30-407a-82e1-13a281ea8e20)

训练都已顺利完成，没有任何报错，在推理时就出现以上报错
加入环境变量已经尝试过
<img width="689" alt="1714016228412" src="https://github.com/PaddlePaddle/PaddleOCR/assets/73943977/ba5eb373-e374-43be-8fd3-c9f22ca74f55">

**Comment by Gpy23** [comment]
strings /anaconda3/envs/ocr/lib/libstdc++.so.6 | grep GLIBCX
查看了一下确实没有GLIBCXX_3.4.30，如何添加

**Comment by Gpy23** [comment]
此问题解决了，删除掉/anaconda3/envs/ocr/lib/libstdc++.so.6 的 libstdc++.so.6，将系统里其他包含GLIBCXX_3.4.30创建软连接给到它
 `ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /anaconda3/envs/ocr/lib/libstdc++.so.6`

**Comment by djdll** [comment]
@Gpy23 这并不是最优的方法，原因是破坏了系统默认的环境（虽然这里修改了软连接并不会有问题），最好的方法是conda虚拟环境安装gcc，conda install -c conda-forge gcc=12.1.0

**Comment by hungtrieu07** [comment]
> [@Gpy23](https://github.com/Gpy23)This is not the best method because it destroys the system default environment (although there is no problem with modifying the soft link here). The best method is to install gcc in the conda virtual environment, conda install -c conda-forge gcc=12.1.0

I have error ```Illegal instruction (core dumped)``` after use your command.

My PC specs:
CPU: i3 10100
RAM: 16GB
OS: Ubuntu 22.04.5 LTS

I also using Miniconda, create another environment with Python 3.10 and install Paddle with this command: ```conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=12.3 -c paddle -c nvidia```. Now I'm gonna use Paddle version 2.6 to see what happen.

**Comment by djdll** [comment]
@hungtrieu07 In theory, you won't get this error, but I recommend you try 2.6 instead

**Comment by hungtrieu07** [comment]
@djdll After install 2.6, I can export model without error. Thank you 😄
