### ISSUE TITLE
你好，请问DB和CRNN之间通过什么进行连接？

### ISSUE THREAD

**Issue by dy1998** [PaddlePaddle/PaddleOCR#120]
RT，请问是直接TPS变换后输入CRNN吗？

**Comment by tink2123** [comment]
将DB计算出检测框在原图上crop出来，做了仿射、旋转等变换，然后输入到CRNN。具体可以参考：
https://github.com/PaddlePaddle/PaddleOCR/blob/78d905113bbfe5ffeae80989e271a7235b69f66f/tools/infer/predict_system.py#L31

**Comment by dy1998** [comment]
> 将DB计算出检测框在原图上crop出来，做了仿射、旋转等变换，然后输入到CRNN。具体可以参考：
> https://github.com/PaddlePaddle/PaddleOCR/blob/78d905113bbfe5ffeae80989e271a7235b69f66f/tools/infer/predict_system.py#L31

感谢回复，我在代码里看到宽高比大于1.5时采取旋转操作，但是这样的话裁剪出来的图片和正常的裁剪图片相比，所有字都是逆时针转了90度的，请问这样的样本输入到识别分支会不会使性能下降

**Comment by LDOUBLEV** [comment]
PaddleOCR的识别算法支持竖排文字识别。宽高比大于1.5，认为检测到的文字是竖排文字，竖排文字在识别时先转正了再去识别，训练识别网络时会生成一些竖排文字样本参与训练，所以旋转90度不会影响识别性能。

**Comment by dy1998** [comment]
> PaddleOCR的识别算法支持竖排文字识别。宽高比大于1.5，认为检测到的文字是竖排文字，竖排文字在识别时先转正了再去识别，训练识别网络时会生成一些竖排文字样本参与训练，所以旋转90度不会影响识别性能。

了解，感谢回复

**Comment by SixGodGG** [comment]
但是其实方向性对检测识别影响还挺大的，正向的效果还是最好

**Comment by tink2123** [comment]
> 但是其实方向性对检测识别影响还挺大的，正向的效果还是最好

是的，所以将检测结果输入到识别网络之前对横排文字做了转正，用于提升识别效果。
为了满足一个模型同时识别竖排和横排文字，训练时将竖排转90度加入到横排样本中一起训练。因此预测时也需要将竖排样本旋转90度。

**Comment by Hupengyu** [comment]
> 但是其实方向性对检测识别影响还挺大的，正向的效果还是最好

是的，非常大，不加方向检测根本没法看
