### ISSUE TITLE
predict_system源码bug，在docker build中如何修改

### ISSUE THREAD

**Issue by xiaocode337317439** [PaddlePaddle/PaddleOCR#12008]
去源码里面进行修改在54行没有导入predict_system导致，可以将第54行改为如下部分，然后再报错的第576行将改成class PaddleOCR(TextSystem)即可。
`from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel,TextSystem`
ref: https://blog.csdn.net/wang602125218/article/details/137175714

_Originally posted by @sugarandgugu in https://github.com/PaddlePaddle/PaddleOCR/issues/11997#issuecomment-2076268813_

**Comment by changdazhou** [comment]
可以在dockerfile当中增加sed命令实现代码替换哈
