### ISSUE TITLE
finetune SER model 任務中的 max_seq_len

### ISSUE THREAD

**Issue by bhhsieh** [PaddlePaddle/PaddleOCR#12002]
請問 finetune SER model 任務中的 max_seq_len 預設是 512
https://github.com/PaddlePaddle/PaddleOCR/blob/main/configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml

我們數據集的 token 長度會超過 512，想調整這個值為 1024
但調整後遇到以下 error
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/138775305/6c78a6d1-5b70-44aa-8adb-0d718778e2e1)
想請教如何解決，謝謝

**Comment by cuicheng01** [comment]
代码里涉及到expand算子的地方需要跟着改动下

**Comment by bhhsieh** [comment]
請問具體要修改什麼地方?
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/138775305/40a75e34-481b-45df-bc61-a9811b9aba04)
我最後找到這個function，但沒找到 error 顯示 value (514) 之處，
再麻煩說明一下，感謝！

**Comment by tran601** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/ad5a59d1-1274-4cf0-9151-5251e7c76fd5)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/062149a1-02a4-4905-bf2f-b00e0fef6efe)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/f68f6f8f-763c-4839-885b-f3eec55bdb6e)

我是分批送进去

**Comment by cuicheng01** [comment]
paddle的版本建议升级下呢？

**Comment by ariefwijaya** [comment]
@bhhsieh Did you solved the problem? 
@tran601 How about training model, should we modify the training code to support batches as well?

**Comment by ariefwijaya** [comment]
@tran601 I've tried you code, but that produce an error: 
```
ValueError: (InvalidArgument) The 1th element of 'shape' for expand_v2 op must be greater than 0, but the value given is 0.
  [Hint: Expected expand_shape[i] > 0, but received expand_shape[i]:0 <= 0:0.] (at /Users/paddle/xly/workspace/3a60970a-8ff4-461a-878a-a5fbdbe8e3e9/Paddle/paddle/phi/infermeta/unary.cc:1215)
  ```

**Comment by ariefwijaya** [comment]
to concat batch : `preds = paddle.concat([p1[0],p2[0]],axis=1)`
