### ISSUE TITLE
关于如何微调PP-OCRV4的检测模型

### ISSUE THREAD

**Issue by TheHonestBob** [PaddlePaddle/PaddleOCR#12009]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
微调时，使用的预训练模型和配置文件是什么
我测试了ch_PP-OCRv4_det_train和ch_PP-OCRv4下的cml和student配置文件，都未能成功训练

**Comment by zhangyubo0722** [comment]
具体训练命令和报错信息是什么呢

**Comment by zhangyubo0722** [comment]
python tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml -o Global.pretrained_model=xxx

**Comment by TheHonestBob** [comment]
> python tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml -o Global.pretrained_model=xxx

我刚才又重新看了一下，是我的问题，我之前按照这个命令训练完成后，预测时指定det_dir指定到rec_dir上去了，我关闭这个issues，非常感谢
