### ISSUE TITLE
长宽比超过20的图像字符检测问题

### ISSUE THREAD

**Issue by Sencc** [PaddlePaddle/PaddleOCR#12007]
请问各位大佬，我现在有一些长宽比超过20的图像，例如6400*280，这种图像在做det的时候应该如何设置训练参数呢，感觉检测的效果很差

**Comment by changdazhou** [comment]
训练时可以修改resize的尺寸：https://github.com/PaddlePaddle/PaddleOCR/blob/main/configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml#L96

**Comment by UserWangZz** [comment]
这种比例图像可以尝试切图然后进行det
