### ISSUE TITLE
setup.py 文件里的一个小错误

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/PaddleOCR#1200]
setup.py 文件里面：
with open('requirments.txt', encoding="utf-8-sig") as f:
    requirements = f.readlines()
    requirements.append('tqdm')
这里的requirments少了一e，应该是requirements；要不然安装报错无法找到requirements.txt文件

**Comment by LDOUBLEV** [comment]
感谢反馈，fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/1203
