### ISSUE TITLE
怎样debug 单步调试

### ISSUE THREAD

**Issue by Gpy23** [PaddlePaddle/PaddleOCR#12017]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by UserWangZz** [comment]
这个需要根据你的开发环境，来确定

**Comment by Gpy23** [comment]
windows、vscode、不使用GPU，源码入口在哪儿，这个吗paddleocr.py 
python paddleocr.py --image_dir=XXXXX --type=ocr  这样启动还是  -c config 这种，应该使用哪一个配置文件

**Comment by UserWangZz** [comment]
可以参考这个文档快速开始，体验PaddleOCR
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/quickstart.md
检测阶段参考文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/detection.md
识别阶段参考文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/recognition.md
如果需要debug，建议参考vscode搭建python debug环境，在对应脚本中打断点即可。

**Comment by zhanghengjiayou** [comment]
下载下源码来就可以单步调试，如果你是pip install paddleocr，无法debug进入源码
