### ISSUE TITLE
Batch processing using paddleocr

### ISSUE THREAD

**Issue by saanvib13** [PaddlePaddle/PaddleOCR#12012]
I am using the PaddleOCR library to detect and extract tables from images. Firstly, I am running the layout detection on an image, if the layout detector detects a table in the image, then I am sending the image to the PaddleOCR. However, it does not natively support batch processing due to which the execution time is scaling linearly with the number of images being processed. The library processes one image at a time. Is there any way to process multiple images simultaneously at the gpu using paddleOCR so that the execution time does not scale linearly with the the number of images? Or are there any open source alternatives to PaddleOCR to accomplish the task?

I am trying to detect tables in images and extract them in a csv file and I want to implement batch processing so that the gpu utilization is efficient and execution time is minimized

**Comment by changdazhou** [comment]
We do not support it, we will evaluate your needs and consider whether to accomplish this task

**Comment by khanfarhan10** [comment]
@changdazhou @andyjiang1116 @Hegelim mentioned on this [issue](https://github.com/PaddlePaddle/PaddleOCR/issues/9957#issuecomment-1548913017) that we do have support for the same on PaddleOCR, can you please clarify on the same?

P. S. - Amazing library guys!
