### ISSUE TITLE
表格标注

### ISSUE THREAD

**Issue by everyday-gao** [PaddlePaddle/PaddleOCR#12019]
表格标注，如何合并单元格？

**Comment by UserWangZz** [comment]
在ppocrlabel打开的excel中将表格结构与图片表格设为一致。
具体步骤参考文档
https://github.com/PaddlePaddle/PaddleOCR/blob/main/PPOCRLabel/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA
