### ISSUE TITLE
预训练的模型用visualDL打不开

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleOCR#1201]
您好，
想用visualDL模型打开预训练的ch_ppocr_mobile_v1.1_det_infer模型，
结果发现模型打不开，请问是什么原因？ 需要做什么格式转换吗？

**Comment by MissPenguin** [comment]
具体报啥错

**Comment by terrancraft** [comment]
> 具体报啥错

打开浏览器后显示 "Error Opening file. Cannot open file params".

**Comment by terrancraft** [comment]
此外，我尝试了其他预训练过的pytorch模型可以打开。

**Comment by PeterPanZH** [comment]
请问您的模型文件名是什么？

**Comment by PeterPanZH** [comment]
不需要params文件，只要model就可以，文件名需要是__model__或者*.pdmodel才能识别是paddle的模型。

<img width="1440" alt="Xnip2020-11-19_18-55-18" src="https://user-images.githubusercontent.com/3366499/99657193-ceed8400-2a98-11eb-9150-c2e12c71a2f4.png">

**Comment by terrancraft** [comment]
> 不需要params文件，只要model就可以，文件名需要是__model__或者*.pdmodel才能识别是paddle的模型。
> 
> <img alt="Xnip2020-11-19_18-55-18" width="1440" src="https://user-images.githubusercontent.com/3366499/99657193-ceed8400-2a98-11eb-9150-c2e12c71a2f4.png">

你好，这种无法打开吗，需要做什么格式转换吗？

**Comment by LDOUBLEV** [comment]
model重命名为__model__ 试试？
