### ISSUE TITLE
关于fastdeploy文档不齐全问题的反馈

### ISSUE THREAD

**Issue by Nankee-Lee** [PaddlePaddle/PaddleOCR#12010]
您好，请问fastdeploy中的rockchip这一块是否少了rknn模型和图片？，只有infer.py，照着文档走不通哇。

期待您的回复，我的邮箱是505582357@qq.com。

**Comment by changdazhou** [comment]
请问是使用最近的零代码产线生成的部署包吗，模型在model目录下了哈

**Comment by Nankee-Lee** [comment]
您好，我使用的是PaddleOCR下的fastdploy，在对照文档部署时没有找到rknn模型和图片，请问是我找错地方了吗？期待您的答复！十分感谢！！！










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月26日(星期五) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 关于fastdeploy文档不齐全问题的反馈 (Issue #12010)





 
请问是使用最近的零代码产线生成的部署包吗，模型在model目录下了哈

**Comment by changdazhou** [comment]
辛苦贴一下文档链接，我们检查一下哈
