### ISSUE TITLE
Is there a way to just recognize  the particular words I care about, in order to improve the performance, I hope the recognition duration less than 10 ms for mobile

### ISSUE THREAD

**Issue by yulf** [PaddlePaddle/PaddleOCR#12029]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by UserWangZz** [comment]
Based on CTC decoding, this requirement cannot be achieved
