### ISSUE TITLE
空格识别问题

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1202]
您好，我希望能识别英文空格，于是制作了一些标注数据，使用rec_r34_vd_none_bilstm_ctc.yml进行训练，生成数据格式内容如下：
![捕获](https://user-images.githubusercontent.com/51456283/99629819-a606c800-2a73-11eb-9dfd-de1520163d6a.JPG)
这是image，json格式的，我之后训练是使用lmdb，字典中加入空格，训练可以正常进行。但生成的识别模型还是不能识别空格，请问是什么原因呢？

**Comment by MissPenguin** [comment]
批量看了吗，确认下是空格的识别率低还是完全无法识别？

**Comment by tyy2tyy** [comment]
完全无法识别空格，但训练时日志打印的这个：Thu Nov 19 15:16:49 2020, epoch: 0, iter: 111910, lr: 0.0009999998146668077, 'loss': 15.266683, 'acc': 0.980469，评估自己的验证集准确率也很高，但却识别不了空格，而我自己的验证集里也是有空格的，所以不知道到底是什么原因？

**Comment by MissPenguin** [comment]
你用验证集（acc=0.98这个）的图像单独跑一下结果看看空格是不是真的识别到了？
另外，自己的测试集上，是只有空格无法识别吗，文字能正常识别吗？如果都识别不好，那可能过拟合了

**Comment by tyy2tyy** [comment]
验证集用来跑模型，识别的效果不错，空格也能识别。测试集不仅空格无法识别，文字也不能正常识别。我也觉得可能是过拟合，但我的数据量是一百万了，这也容易过拟合吗？如果这样，那我是再继续增大类似训练集样本的数据量吗？

**Comment by zcswdt** [comment]
> 来跑模型，识别的效果不错，空格也能识

你这个加入了加载了预训练模型了吗？还是从来开始训练的？

**Comment by BeyondYourself** [comment]
加入预训练模型fintune就行了吧

**Comment by tyy2tyy** [comment]
从头开始训练
