### ISSUE TITLE
我不知道图片中的语言，希望ocr检测出文本和对应语种的概率，有这个模型吗？

### ISSUE THREAD

**Issue by AnitaSherry** [PaddlePaddle/PaddleOCR#12021]
我有看到Multilingual_PP-OCRv3_det_infer模型，但是使用时也必须要指定语言才行

**Comment by tink2123** [comment]
可以通过训练一个语种分类器，作为OCR的前置操作

**Comment by AnitaSherry** [comment]
能给个提示吗，在huggingface没搜到这样的模型

**Comment by TachibanaYoshino** [comment]
> 能给个提示吗，在huggingface没搜到这样的模型

Hi, I believe[ this work](https://blog.csdn.net/YY007H/article/details/124494650) can help you, I have changed the DB code in paddleocr2.7 according to the [tutorial](https://blog.csdn.net/YY007H/article/details/124491217) given in the blog post, now it can classify text while detecting it. For example, the detected text can be classified into different languages, and the text, formulas, images, and tables in the picture can be detected and classified.

**Comment by UserWangZz** [comment]
感谢讨论❤️
