### ISSUE TITLE
前后处理的cpu部分能否利用多核并行加速？

### ISSUE THREAD

**Issue by charliedream1** [PaddlePaddle/PaddleOCR#12023]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

前后处理的cpu部分能否利用多核并行加速？怎么配置？

**Comment by UserWangZz** [comment]
目前没有支持并行方式，可以自己修改代码尝试
