### ISSUE TITLE
 PPStructure: unable to recognize a fairly easy structure

### ISSUE THREAD

**Issue by vlavorini** [PaddlePaddle/PaddleOCR#12036]
I am trying to parse [this PDF](https://ec.europa.eu/eurostat/documents/2995521/11081093/3-10072020-AP-EN.pdf/d2f799bf-4412-05cc-a357-7b49b93615f1) using PaddleOCR 2.7.3.

I tried converting the pages as images, and then run PPStructure on them. I tried with the following options:

    engine = PPStructure(show_log=True, image_orientation=True)

    engine = PPStructure(show_log=True, image_orientation=True, lan='en')

    engine = PPStructure((show_log=True, image_orientation=True, lan='en',  layout_model_dir=./picodet_lcnet_x1_0_fgd_layout_infer',  layout_dict_path='./layout_publaynet_dict.txt',)

but the results in the second page of the document are not satisfactory:
![page_1](https://github.com/PaddlePaddle/PaddleOCR/assets/8724860/88863ae1-4ddc-44de-96dd-ae296ad93c43)

I also tried with the model `ppyolov2_r50vd_dcn_365e_publaynet`:

    engine = PPStructure(show_log=True, image_orientation=True, lan='en',
                          layout_model_dir='./ppyolov2_r50vd_dcn_365e_publaynet', 
                           layout_dict_path=./layout_publaynet_dict.txt',

but the program stops at an error: `InvalidArgumentError: The size of Op(Conv) inputs should not be 0.`

Any suggestion on how to correctly parse this pdf?

Thank you!

**Comment by TingquanGao** [comment]
What is the PaddlePaddle version used?

**Comment by vlavorini** [comment]
PaddlePaddle == 2.6.1
PaddleOCR == 2.7.3

**Comment by TingquanGao** [comment]
The dataset to train PPStructure models lack of such data. So the models need to be finetuned.
