### ISSUE TITLE
det模型，det_unclip_ratio = 2.8, 3.0， 4.0 得到的识别结果出现不同的漏字

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#12030]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

det模型，det_unclip_ratio = 2.8, 3.0， 4.0 得到的识别结果出现不同的漏字

2.8 结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/f6928c14-7c1a-404e-a20f-800f09626cf5)

3.0结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/700da5bd-a814-41e1-ba29-5dad41d548af)

4.0结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/0c861c1f-a6ea-42b1-9cf0-2098874d51e8)

**Comment by UserWangZz** [comment]
det_unclip_ratio参数会扩大检测框范围，rec模型会由于crop出的图像不同产生不同的输出，您需要根据自己的场景选择合适的参数

**Comment by nissansz** [comment]
还是要通过识别训练时改善
