### ISSUE TITLE
OpenCV version dependency

### ISSUE THREAD

**Issue by julian24bas** [PaddlePaddle/PaddleOCR#12034]
I have a dependency conflict installing PaddleOCR as it requires opencv-python<=4.6.0.66 and opencv-contrib-python<=4.6.0.66. However this OpenCV version is already 2 years old (Jun 7, 2022). The other package I try to install requires opencv-python = "^4.7.0.72".

Can you remove/update this version requirement? 
Appreciate any help :)

**Comment by UserWangZz** [comment]
You can try this version of opencv Python="^ 4.7.0.72" to see if it works properly on PaddleOCR
