### ISSUE TITLE
rec 模型微调时，如果只用易错字加强训练，不加入其它普通字符，有没有什么影响？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#12040]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec 模型微调时，如果只用易错字加强训练，不加入其它普通字符，有没有什么影响？

**Comment by UserWangZz** [comment]
会有影响的，模型容易将其他相近字符判断为只添加的易错字
