### ISSUE TITLE
"_CudaDeviceProperties" is already registered! when using paddleocr together with torch

### ISSUE THREAD

**Issue by KomodoCrypto** [PaddlePaddle/PaddleOCR#12046]
There are a couple of issues with this workaround. However, no solution found.
I am using paddlepaddle-gpu with cuda 12.2 and, when importing torch into the same environment, the error "_CudaDeviceProperties" is already registered! occurs. How to solve it?

Paddle version: 2.6.1
Paddle With CUDA: True

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: N/A
Libc version: N/A
Python version: 3.11.4

CUDA version: 12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
cuDNN version: N/A
Nvidia driver version: 551.23
Nvidia driver List:
GPU 0: NVIDIA GeForce RTX 4050 Laptop GPU

I also tried to downgrade to Cuda 12.0 and CUDNN 8.8 and the issue persists. It seems that can't coexist with Pytorch or Ultralytics package.

Additionally, this error is reported: (PreconditionNotMet) The third-party dynamic library (cublas64_118.dll;cublas64_11.dll) that Paddle depends on is not configured correctly. (error code is 126).

I had no issues with cpu version but with gpu seems there is no valid way to just install and run cuda version.

**Comment by zhangyubo0722** [comment]
Just to confirm, what is the CUDA version supported by PaddlePaddle?

**Comment by KomodoCrypto** [comment]
Hello, version of paddlepaddle gpu is 2.6.1 and based on documentation, it should support Cuda 12.0.
I manage to solve one of the errors (library mismatch one) installing also Cuda 11.8. However, torch and paddleocr can't coesxist, throwing the exception "_CudaDeviceProperties" is already registered!

**Comment by zhangyubo0722** [comment]
Trying to switch the versions of PaddlePaddle and PyTorch, to PaddlePaddle==2.4.2 and PyTorch==1.10.1, it is recommended to install PaddlePaddle first, followed by PyTorch. Ensure that PaddlePaddle is working properly before testing different versions of PyTorch.
