### ISSUE TITLE
trans_xfund_data.py没有找到，可否提供？

### ISSUE THREAD

**Issue by Yhc-777** [PaddlePaddle/PaddleOCR#12049]
在多模态表单识别中，trans_xfund_data.py这个函数没有找到，可否提供？谢谢！

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/applications/%E5%A4%9A%E6%A8%A1%E6%80%81%E8%A1%A8%E5%8D%95%E8%AF%86%E5%88%AB.md

**Comment by zhangyubo0722** [comment]
在aistudio项目里，
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/94225063/7ab23077-9f62-4ff4-8614-c3501dd0e5e8)
点进去后点击运行一下

**Comment by zhangyubo0722** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/94225063/4a9b9a92-aef0-451b-9161-e2533bdb94dd)

**Comment by Yhc-777** [comment]
@zhangyubo0722 好的好的！谢谢！！！费心啦！
