### ISSUE TITLE
文本方向检测

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1204]
针对镜像文本（例如6和9 ， M和W）这种文本，0度和另外一个字符的180度及其相似，这个有什么好的方法可以得到正确的检测结果么？

**Comment by WenmuZhou** [comment]
你的场景是单个字符的识别吗，如果不是的话，这种单个字符影响不大，其他字符的发现会帮助模型判断，666，999这种就不好说了

**Comment by SealQ** [comment]
> 你的场景是单个字符的识别吗，如果不是的话，这种单个字符影响不大，其他字符的发现会帮助模型判断，666，999这种就不好说了

在识别的文本中包括一部分这样的单字符，这种如果想改善其效果的话，有什么改进的方法建议么？

**Comment by littletomatodonkey** [comment]
这种目前可能没有太好的解决办法，可能只能增加检测和方向分类起的训练样本了
