### ISSUE TITLE
文本检测效果跟代码调用方法的不同有很大区别？

### ISSUE THREAD

**Issue by LightRoastKenyaPeaberry** [PaddlePaddle/PaddleOCR#12053]
我按照课程笔记上的两种推测方式，进行了对古籍页面的文本检测。
- 直接调用paddleocr
```
from paddleocr import PaddleOCR
import numpy as np
import cv2
import matplotlib.pyplot as plt
# 在notebook中使用matplotlib.pyplot绘图时，需要添加该命令进行显示
%matplotlib inline

# 2. 声明PaddleOCR类
ocr = PaddleOCR()  
img_path = '/home/zxy/战国策三十三卷_667.png' 
# 3. 执行预测
result = ocr.ocr(img_path,rec=False)
print(f"The predicted text box of {img_path} are follows.")
print(result)

# boxes = [] 
# for re in result[0]:
#     boxes.append(re[0])

image = cv2.imread(img_path)

for box in result[0]:
    box = np.reshape(np.array(box), [-1, 1, 2]).astype(np.int64)
    image = cv2.polylines(np.array(image), [box], True, (255, 0, 0), 10)

# 画出读取的图片
plt.figure(figsize=(10, 10))
plt.imshow(image)
```
效果如图：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/122678455/86465588-5c52-4c8f-856a-0afcb71f3dde)

- 使用官方发表的训练权重`ch_PP-OCRv4_det_train`，命令执行完会显示一长段的警告显示权重没载上。
```
python tools/infer_det.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml -o Global.checkpoints=/home/zxy/PaddleOCR/pretrain_models/ch_PP-OCRv4_det_train/best_accuracy  Global.infer_img=/home/zxy/战国策三十三卷_667.png
```
效果如图：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/122678455/4eeb2b72-b3f8-48b3-8af8-4fea7b900751)

**可以看出来第一种方法比第二种方法效果要好很多，我想知道为什么，以及后面我要训练一个针对古籍的文本检测网络，该怎么把我的训练的起点放在方法1的效果上？**

**Comment by UserWangZz** [comment]
报错可能是config文件和权重文件不对应导致的，可以尝试一下PPOCRv4文件下的其他config文件。方法一只支持推理，不支持训练。

**Comment by LightRoastKenyaPeaberry** [comment]
> 报错可能是config文件和权重文件不对应导致的，可以尝试一下PPOCRv4文件下的其他config文件。方法一只支持推理，不支持训练。

的确🤣， 我找到了你们给的[模型列表](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/models_list.md#1.3)，慢慢微调吧～

**Comment by UserWangZz** [comment]
感谢讨论❤️❤️
