### ISSUE TITLE
NameError: name 'fitz' is not defined

### ISSUE THREAD

**Issue by MengjiangBro** [PaddlePaddle/PaddleOCR#12058]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- windows11 22631.3527
- 版本号/Version：
- Paddle： 2.6.1 
- PaddleOCR：2.7.2 
- 问题相关组件/Related components：
- paddleocr\ppocr\utils\utility.py
- 运行指令/Command Code：
- ocr = PaddleOCR(use_angle_cls=True, lang="en", use_tensorrt=False, use_gpu=True)
- result = ocr.ocr(pdf_path, cls=True) # pdf_path是一个pdf文件需要进行OCR
- 
- 完整报错/Complete Error Message：
  File "e:\code\file.py", line 193, in run_paddle_ocr_on_pdf
    result = ocr.ocr(pdf_path, cls=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Anaconda\envs\q\Lib\site-packages\paddleocr\paddleocr.py", line 647, in ocr
    img = check_img(img)
          ^^^^^^^^^^^^^^
  File "D:\soft\Anaconda\envs\q\Lib\site-packages\paddleocr\paddleocr.py", line 527, in check_img
    img, flag_gif, flag_pdf = check_and_read(image_file)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Anaconda\envs\q\Lib\site-packages\paddleocr\ppocr\utils\utility.py", line 114, in check_and_read
    with fitz.open(img_path) as pdf:
         ^^^^
NameError: name 'fitz' is not defined
经分析,paddleocr\ppocr\utils\utility.py导入了以下库, 
import logging
import os
import imghdr
import cv2
import random
import numpy as np
import paddle
import importlib.util
import sys
import subprocess
没有导入
fitz
一定是手抖了,2333

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/95e3103f88f48529ee751c143975df558252721a/ppocr/utils/utility.py#L123
在这里尝试导入了，可以检查一下python环境中是否安装了fitz

**Comment by UserWangZz** [comment]
> * ocr = PaddleOCR(use_angle_cls=True, lang="en", use_tensorrt=False, use_gpu=True)
> * result = ocr.ocr(pdf_path, cls=True) # pdf_path是一个pdf文件需要进行OCR

切换到分支release/2.7 尝试复现未发现异常，可以切换到分支2.7
复现环境python 3.9.16 paddlepaddle2.6.1 paddleocr 2.7.5

**Comment by cbwchuck** [comment]
尝试下`pip install PyMuPDF`
