### ISSUE TITLE
Did not recongnize last number

### ISSUE THREAD

**Issue by stccorp** [PaddlePaddle/PaddleOCR#12050]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
I uploaded an image with the following number 777-88-8877
After running result = ocr.ocr(img_path, cls=True)
I get 
[[[[7.0, 2.0], [93.0, 2.0], [93.0, 14.0], [7.0, 14.0]], ('777-88-887', 0.9906673431396484)]]

Why it didnt recognize the last number 7??

- 系统环境/System Environment：Google Colbas
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：

img_path = 'output_image.png'
img = cv2.imread(img_path,cv2.IMREAD_UNCHANGED)
cv2_imshow(img)
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

This is the file
![output_image](https://github.com/PaddlePaddle/PaddleOCR/assets/8180135/7110ed14-76c9-457f-8c1a-4e47871ca915)

- 完整报错/Complete Error Message：

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/recognition.md#32-%E6%B5%8B%E8%AF%95%E8%AF%86%E5%88%AB%E6%95%88%E6%9E%9C
you can try by this document
