### ISSUE TITLE
1.自创字符可以检测识别？2.文本检测阶段，可以完全贴合字符区域画出文本框吗，并且字符全部在文本框里，不会出现多框或者少框的现象。

### ISSUE THREAD

**Issue by MMYY-yy** [PaddlePaddle/PaddleOCR#12056]
## 背景

第一个问题应用场景：将特殊创作的字符进行检测识别
第二个问题应用场景：需要针对图片里的特殊字符区域进行截取下来并单独保存。

## 解决步骤
第一个问题：如果paddleocr支持自创字符的检测识别
1.使用pplabel进行标注时，标签应该怎么设置比较好（中文描述，英文描述，其他描述）
2.应该使用哪一个模型，使得检测识别效果较好

第二个问题：
文本检测阶段，可以完全贴合字符区域画出文本框吗，并且字符全部在文本框里，不会出现多框或者少框的现象。

**Comment by UserWangZz** [comment]
特殊字符可以直接标注训练检测模型，但是识别阶段需要确保存在对应的字典文件。
第二个问题，这个只能说通过训练能够尽可能确保输出这样的文本框，但是无法完全满足要求。
