### ISSUE TITLE
NameError: name 'predict_system' is not defined

### ISSUE THREAD

**Issue by forrestr91** [PaddlePaddle/PaddleOCR#12057]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04.6 LTS
- 版本号/Version：Paddle：  2.6.1 PaddleOCR：2.7.5  问题相关组件/Related components：
- 运行指令/Command Code：
- import os
import cv2
from paddleocr import PPStructure,save_structure_res

table_engine = PPStructure(table=False, ocr=False, show_log=True)

save_folder = './output'
img_path = '1.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)
- 完整报错/Complete Error Message：
     13 # limitations under the License.
---> 14 from .paddleocr import *
     16 __version__ = paddleocr.VERSION
     17 __all__ = [
     18     'PaddleOCR', 'PPStructure', 'draw_ocr', 'draw_structure_result',
     19     'save_structure_res', 'download_with_progressbar', 'sorted_layout_boxes',
     20     'convert_info_docx', 'to_excel'
     21 ]

File ~/.local/lib/python3.10/site-packages/paddleocr/paddleocr.py:575
...
    579         args:
    580             **kwargs: other params show in paddleocr --help
    581         """

NameError: name 'predict_system' is not defined

**Comment by UserWangZz** [comment]
检查一下ppocr的安装是否正确

**Comment by UserWangZz** [comment]
你好，可以提供一下完整的报错信息吗？这个目前看不太出来问题出在什么地方

**Comment by forrestr91** [comment]
> 你好，可以提供一下完整的报错信息吗？这个目前看不太出来问题出在什么地方

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/13085583/d1f3b354-1b3a-4caf-8867-9a79495ecb68)

**Comment by UserWangZz** [comment]
predict_system在tools/infer/下，可以尝试手动导入一下看看

**Comment by forrestr91** [comment]
> predict_system在tools/infer/下，可以尝试手动导入一下看看

换成2.7.0.0版本，可以了。

**Comment by UserWangZz** [comment]
我们记录一下，排查一下问题

**Comment by Tpinion** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/27395365/a9e46bf2-da4b-4d31-941d-f8287f3d9bd0)

**Comment by zhuwenfei-wintech** [comment]
> 我们记录一下，排查一下问题

从2.7.1开始paddleocr.py里面就缺了这句话from tools.infer import predict_system

**Comment by zwfcrazy** [comment]
> 我们记录一下，排查一下问题

从2.7.1开始paddleocr.py里面就缺了这句话from tools.infer import predict_system

**Comment by UserWangZz** [comment]
好的，感谢发现问题
