### ISSUE TITLE
EastRandomCropData的size如何配置为1080P

### ISSUE THREAD

**Issue by yaojun10086** [PaddlePaddle/PaddleOCR#12055]
EastRandomCropData的size如何配置为1080P（1920*1080），修改完yml后执行检测训练报错ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [8, 96, 135, 240] and the shape of Y = [8, 96, 136, 240]. Received [135] in X is not equal to [136] in Y at i:2.
错误异常提示在\tools\program.py", line 307, in train
    preds = model(images)

**Comment by UserWangZz** [comment]
你好，这是因为模型对图片下采样出现的问题，1920*1080的图像下采样8倍会变成 240*135的特征图，但是与另一个数据shape不一致导致的报错，需要您排查一下Y张量和X张量
