### ISSUE TITLE
想咨询一下，下个版本的表格识别模型在哪些方面做了优化，是否在复杂的表格识别的准确率上有提升

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleOCR#12061]
希望有大佬帮忙回答一下。如果有，下个版本什么时候可以体验到

**Comment by UserWangZz** [comment]
目前ppocr暂时还没有表格结构的优化，后续会持续进行模型的优化的。想体验最新的通用OCR大模型和文档解析大模型可以关注PaddleX

**Comment by TingquanGao** [comment]
针对合并单元格等复杂表格的识别进行了优化。

**Comment by liuzhipengchd** [comment]
> 针对合并单元格等复杂表格的识别进行了优化。

大佬，如果单元格中的文字 有很多竖着的文字，这种情况的识别效果有提升么。（目前模型，对于如果有竖着的文字，识别容易串行）

**Comment by UserWangZz** [comment]
这种场景可以考虑微调一下文本检测模型看看效果

**Comment by liuzhipengchd** [comment]
> 这种场景可以考虑微调一下文本检测模型看看效果

大佬，还有2个问题，1、就是可以识别字体的大小，包括颜色这些熟悉吗。2、如果表格识别中，有一个单元格错了，那么整个表格的格式就不能正常在html中展示，这种情况有没有解决办法（可以修复错误单元格，让其正常展示）

**Comment by UserWangZz** [comment]
> > 这种场景可以考虑微调一下文本检测模型看看效果
> 
> 大佬，还有2个问题，1、就是可以识别字体的大小，包括颜色这些熟悉吗。2、如果表格识别中，有一个单元格错了，那么整个表格的格式就不能正常在html中展示，这种情况有没有解决办法（可以修复错误单元格，让其正常展示）

第一个问题，我理解的话字体的大小是否可以通过检测模型box的长宽来过滤，颜色的话简单训练一个分类器是不是就可以了？
第二个问题，目前html解码是根据模型输出做的，因此很难在后处理阶段来对错误进行修复。

**Comment by UserWangZz** [comment]
> @UserWangZz 大佬，我想咨询一下，通用表格模型，能够支持稍微有点褶皱和倾斜的表格，应该使用哪个模型比较好呢

目前仓库提供的模型都没有在这个场景中进行训练过，所以可能表现不会很好

**Comment by nissansz** [comment]
> chatgpt4真的很可以，支持褶皱表格识别

有链接吗？
