### ISSUE TITLE
直接识别不使用检测模型

### ISSUE THREAD

**Issue by ymy1005** [PaddlePaddle/PaddleOCR#12066]
我的场景是，很多的单元格图片，识别里面的文字，可以设置det=False直接使用识别模型识别文字吗？？
如果想微调文本识别模型，数据集如何标注？？使用ppocrlabel标注后生成的crop_img是裁剪过的，可以不用这个目录里的直接用原图片吗？

**Comment by UserWangZz** [comment]
可以不det直接识别，但是需要确保每张图片都是单一的单元格，否则识别结果会下降很严重，这也是为什么需要有一个detection模型的原因。

**Comment by ymy1005** [comment]
> 可以不det直接识别，但是需要确保每张图片都是单一的单元格，否则识别结果会下降很严重，这也是为什么需要有一个detection模型的原因。

不det直接识别只能识别到一个块的内容，比如两行文字就只能识别到一行；单元格较大，里面只有一个字符，空白面积过大时，基本识别不到。微调识别模型的话，用ppocrlabel数据标注必须有框，识别对应的是裁剪过的图片，识别模型微调时用裁剪过的图片还是原图片？

**Comment by TingquanGao** [comment]
那这个场景还是建议使用det模型。

**Comment by ymy1005** [comment]
> 那这个场景还是建议使用det模型。

原检测模型画文本框时有长宽比限制，单字符框不出来，在1000+的数据集上微调了检测模型，效果比原模型差一丢丢，还是检测不到单字符。请问这种情况有解决方法吗啊

**Comment by UserWangZz** [comment]
是要做字符级检测吗？

**Comment by ymy1005** [comment]
> 是要做字符级检测吗？

因为只有一个字符时检测不到，所以想微调一个模型，专门识别单个字符的情况，但是微调的检测模型没效果，微调后还是框不出来单个字符的情况。请问有解决方法吗

**Comment by UserWangZz** [comment]
目前模型基本上都是word level和line level，针对字符级的检测，可能需要使用大量数据重新训练

**Comment by ymy1005** [comment]
> 目前模型基本上都是word level和line level，针对字符级的检测，可能需要使用大量数据重新训练

整张图片只有一个字符，检测模型没有输出文本框，导致识别不到。这种情况，有方法解决吗？如果微调，需要多大数据量呢？

**Comment by UserWangZz** [comment]
检测模型的作用就是为识别模型缩小关注的区域，针对你所提到的场景，目前可以尝试的是生成一部分单字符的数据，可以参考文档
https://github.com/PaddlePaddle/PaddleOCR/blob/main/StyleText/README_ch.md

**Comment by UserWangZz** [comment]
> 遇到了相同的问题：单行文本中，单个字符无法被检测到。贴个图 <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/7589001/352942713-138d96d4-8df5-4edc-9ba4-b5ec91f6c48f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzY4NTYsIm5iZiI6MTcyMjIzNjU1NiwicGF0aCI6Ii83NTg5MDAxLzM1Mjk0MjcxMy0xMzhkOTZkNC04ZGY1LTRlZGMtOWJhNC1iNWVjOTFmNmM0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcwMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFkYjIwNmNjZjNmZjFmYWY4NTkwYTgxNjFhZGUwYWUzMTgzZDQ0YjBiNjJhNzU1MmU5ZmE0NzljY2YxNTUyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bwzgzkrsR7nfPSUvqIFBmh7xJvh3tkzGJY2zMzplTnI"> 上图的“一、” 一直无法被检测，即使把图片框扩大

这种图片就不需要检测了，直接识别看看效果
