### ISSUE TITLE
slimfacenet训练的模型，在linux系统下使用c++程序测试算法的性能时加载模型错误：WARNING: Logging before InitGoogleLogging() is written to STDERR I1119 16:59:19.406464 18977 cxx_api.cc:251] Load model from file. F1119 16:59:19.419380 18977 program.cc:192] Check failed: op no Op found for feed *** Check failure stack trace: *** 已放弃 (核心已转储)

### ISSUE THREAD

**Issue by zhudibo-unwulian** [PaddlePaddle/PaddleOCR#1206]
大佬，我在linux系统下使用c++测试slimfacenet训练的模型时，模型加载报如下的错误：
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1119 16:59:19.406464 18977 cxx_api.cc:251] Load model from file.
F1119 16:59:19.419380 18977 program.cc:192] Check failed: op no Op found for feed
*** Check failure stack trace: ***
已放弃 (核心已转储)
加载模型的代码如下：
        config.set_model_dir(modelDir);
        config.set_valid_places({Place{TARGET(kX86), PRECISION(kFloat)},
                           Place{TARGET(kHost), PRECISION(kFloat)}});
        predictor =CreatePaddlePredictor<CxxConfig>(config);
slimfacenet模型转为.nb格式也不行。slimfacenet使用的推理api为libpaddle_api_full_bundled.a

**Comment by wanghaoshuang** [comment]
请参考下这个issue: https://github.com/PaddlePaddle/Paddle-Lite/issues/2785

**Comment by zhudibo-unwulian** [comment]
大佬，我这个是在linux系统下使用c++测试slimfacenet训练的模型，不是编译库在嵌入式上面跑，slimfacenet使用的推理api为libpaddle_api_full_bundled.a，我在头文件中加载了：
#include "paddle_use_kernels.h"  // NOLINT
#include "paddle_use_ops.h"      // NOLINT头文件
编译时提示如下错误：
/home/un/Paddle-Lite/build.lite.x86/inference_lite_lib/cxx/lib/libpaddle_api_full_bundled.a(cast_compute.cc.o)：在函数‘void paddle::lite::fluid::VisitDataType<paddle::lite::kernels::x86::CastOpFunctor<(paddle::lite_api::TargetType)2, float> >(paddle::framework::proto::VarType_Type, paddle::lite::kernels::x86::CastOpFunctor<(paddle::lite_api::TargetType)2, float>) [clone .part.197]’中：
cast_compute.cc:(.text+0xc3)：对‘paddle::lite::fluid::DataTypeToString[abi:cxx11](paddle::framework::proto::VarType_Type)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/demo.dir/build.make:146: recipe for target 'demo' failed
make[2]: *** [demo] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/demo.dir/all' failed
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
恳请大佬指点

**Comment by littletomatodonkey** [comment]
看着是c++标准库引用有问题，这块不使用paddle的话，能正常编译c++项目吗？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
