### ISSUE TITLE
max_text_length 作用

### ISSUE THREAD

**Issue by weirman** [PaddlePaddle/PaddleOCR#12065]
在推理时候的文档中写到 
|  max_text_length | int | 25 | 识别结果最大长度，在`SRN`中有效 |
但是，在 ch_PP-OCRv3_rec.yaml 中使用了MultiHead也用到了这个参数，所以在训练的时候具体应该怎么设置？

如果我训练数据都在 50 以内，max_text_length 应该设置为 50，但是在推理的时候有大于 50 个字符的图片，是否会收到这个值的影响？

从代码上来看，好像并不作用于ch_PP-OCRv3_rec.yaml模型，但是会作用于大于max_text_length长度的数据集会被删除掉么？

**Comment by TingquanGao** [comment]
该参数只对训练有影响，推理时会自适应长文本。
