### ISSUE TITLE
在类中初始化卡顿

### ISSUE THREAD

**Issue by omaiyiwa** [PaddlePaddle/PaddleOCR#12064]
我有一个类似这样的类
`        self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)

        self.configparser = configparser.ConfigParser()
        self.configparser.read(config_ini)

        self.intersect_value = float(self.configparser['check_config']['intersect_value'])
        self.amps_value = ast.literal_eval(self.configparser['check_config']['amps_value'])

        self.device_choose = (self.configparser['device_detect']['device'])
        self.conf = float(self.configparser['device_detect']['conf_check'])
        self.classes = self.str_to_bool(self.configparser['device_detect']['classes_check'])
        self.max_det = int(self.configparser['device_detect']['max_det_check'])

    def detect(self):
        try:
            while not self.stopped:
                # time.sleep(time_sleep)
                a = time.time()
                frame = self.camera_index  # 单张图片
                if frame is None:
                    continue
                seg_id = self.deal_detection(frame)
                self.results_list.append(seg_id)

                if len(self.results_list) == self.dim_count_total:
                    work_class = self.data_total(self.results_list)
                    for ok_id in work_class:
                        self.status_weld[ok_id] = 1
                    yield self.status_weld.copy()
                    self.status_weld = [0 for _ in self.status_weld]
                    self.results_list = []
                b = time.time()
                print((b - a) * 1000)`
   当我启用 self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)我打印的时间是这样的
   `2990.854501724243
8.969783782958984
1088.2785320281982
39.86644744873047
[0, 0, 0, 0, 0]
38.87009620666504
44.03972625732422
17.93837547302246
39.86692428588867
45.84646224975586
[0, 0, 0, 0, 0]
35.880088806152344
40.8635139465332
41.44716262817383
63.78674507141113
13.953685760498047
[0, 0, 0, 0, 0]
69.76628303527832
20.93029022216797
61.79308891296387
81.39896392822266
61.79332733154297
[0, 0, 0, 0, 0]
22.92346954345703
38.87057304382324
38.507938385009766
39.86668586730957
42.85693168640137
[0, 0, 0, 0, 0]
39.86692428588867
28.903484344482422
56.411027908325195
26.909351348876953
37.87374496459961
[0, 0, 0, 0, 0]
35.87985038757324
48.83718490600586
33.88643264770508
45.84693908691406
49.833059310913086
[0, 0, 0, 0, 0]
20.93029022216797
34.88302230834961
47.840118408203125
46.874046325683594
35.329341888427734
[0, 0, 0, 0, 0]
1851.0749340057373`
从时间看会偶尔卡一下，这对我而言是致命的，而当我注释掉那一行就没有这个问题，甚至没有进行推理那一步，cpu和内存和显存占比很少，我不清楚是什么原因

**Comment by TingquanGao** [comment]
没太理解，是注释掉哪一行代码呢？

**Comment by omaiyiwa** [comment]
> 没太理解，是注释掉哪一行代码呢？

注释这一行  self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)

**Comment by UserWangZz** [comment]
self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)
这行代码是初始化PaddleOCR类，请问你自己的类是在for循环中每次都会执行一次初始化吗？这样有可能会导致卡顿，因为PaddleOCR类会去加载模型和框架，这会增加内存和显存

**Comment by omaiyiwa** [comment]
> self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False) 这行代码是初始化PaddleOCR类，请问你自己的类是在for循环中每次都会执行一次初始化吗？这样有可能会导致卡顿，因为PaddleOCR类会去加载模型和框架，这会增加内存和显存

不在for循环我只在类的_init_中定义，循环里是self.ocr.ocr(frame, cls=False)，但是都没有走这一步

**Comment by UserWangZz** [comment]
> 我只在类的_init_中定义，循环里是self.ocr.ocr(

我的意思是你的这个类是不是在一个循环里重复的初始化了

**Comment by omaiyiwa** [comment]
> > 我只在类的_init_中定义，循环里是self.ocr.ocr(
> 
> 我的意思是你的这个类是不是在一个循环里重复的初始化了

没有

**Comment by TingquanGao** [comment]
但如果注释掉`self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)`这一行代码，后续怎么做ocr识别呢？

**Comment by omaiyiwa** [comment]
> 但如果注释掉`self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)`这一行代码，后续怎么做ocr识别呢？

即使开了这段代码我也没用到识别，没有走到self.ocr.ocr(frame, cls=False)这一步

**Comment by UserWangZz** [comment]
可以解释一下这个输出的时间吗

**Comment by omaiyiwa** [comment]
> 可以解释一下这个输出的时间吗

主要是这一行的时间seg_id = self.deal_detection(frame)，现在我将里面改为直接return 0，下面的内容的收集五次返回结果，然后打印时间

**Comment by TingquanGao** [comment]
看起来和`self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)`这一行代码没有关系。当然也有可能是因为实例化PaddleOCR时，底层框架需要分配资源，导致了主进程受影响。可以将实例化PaddleOCR的代码新开一个进程来处理试试。

**Comment by omaiyiwa** [comment]
> 看起来和`self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False)`这一行代码没有关系。当然也有可能是因为实例化PaddleOCR时，底层框架需要分配资源，导致了主进程受影响。可以将实例化PaddleOCR的代码新开一个进程来处理试试。

我发现把use_gpu改为false就可以了，最后占的是显存，cpu没加
