### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 51057913** [PaddlePaddle/PaddleOCR#12069]
我使用的图片是
![table](https://github.com/PaddlePaddle/PaddleOCR/assets/65072443/3ff28c31-df24-4dd5-9f5c-6173b919d22f)
使用代码
table_engine = PPStructure(show_log=True,lang='en',recovery=True)
得到空表格，去掉recovery参数报错
 InvalidArgumentError: When step > 0, end should be greater than start, but received end = 0, start = 501.
      [Hint: Expected end >= start, but received end:0 < start:501.] (at ../paddle/phi/kernels/funcs/slice_utils.h:78)
      [operator < set_value > error]
使用中文图片和中文模型，layout设置为True,读不出来表格，更提不出文字。
result = table_engine(img) 返回为空
layout设置为False,根据源代码，ocr自动为false,自动全版面设置为表格，也提不出文字。

layout_model_dir换成中文推理模型picodet_lcnet_x1_0_fgd_layout_cdla_infer,也识别不出来表格和文字。
请问大佬们有什么解决方案？

**Comment by GreatV** [comment]
试试这里 https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppstructure/docs/quickstart.md#22-python%E8%84%9A%E6%9C%AC%E4%BD%BF%E7%94%A8

**Comment by 51057913** [comment]
> 试试这里 https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppstructure/docs/quickstart.md#22-python%E8%84%9A%E6%9C%AC%E4%BD%BF%E7%94%A8

谢谢，最终初步找出来是paddle的安装问题，以为run_check就够了，结果导入paddle打出来的tensor都是0。

**Comment by UserWangZz** [comment]
感谢讨论❤️❤️❤️

**Comment by 51057913** [comment]
> 具体是什么安装问题？我卡半天了

我最后直接装的docker镜像可以运行

**Comment by 51057913** [comment]
> 具体是什么安装问题？我卡半天了

飞桨安装的时候可以test一下，看给它不是0的tensor是否打印的是0，如果是就是没装好。
