### ISSUE TITLE
Suggestion for preprocessing of Image.

### ISSUE THREAD

**Issue by erictan23** [PaddlePaddle/PaddleOCR#12089]
Hello! Thank you for sharing PaddlePaddleOCR, I am trying to read a text from a CCTV surveillance video footage. However, I encounter some characters that are black and background is black, resulting in a poor performance of the OCR model.  The Image format is in PNG.

![invert_test](https://github.com/PaddlePaddle/PaddleOCR/assets/74151994/cdf2b5db-6e2b-4b50-be97-60182a42291d)

The results by the model are: 02+60023-We1-1249:05

I have tried some pre-processing methods such as changing of grayscale and median blurring and the results slightly improve. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
median = cv2.medianBlur(gray, 7)

![processed_image](https://github.com/PaddlePaddle/PaddleOCR/assets/74151994/05f0e36a-dca6-4673-8ca2-7b69900ab40c)

The results by the model are: 09-20023Wed-1249:05

are there any suggestions to improve on the results?

**Comment by GreatV** [comment]
In my experience you need to fine-tune the model by collecting some data for the corresponding scenarios. A generic model may not be sufficient.

**Comment by zhangyubo0722** [comment]
Yes, you need to collect some data to retrain the model.
