### ISSUE TITLE
使用pyinstaller打包PaddleOCR报错

### ISSUE THREAD

**Issue by hhhhhhhhaaha** [PaddlePaddle/PaddleOCR#12087]
使用最新版 paddlepaddle 2.5.2 在使用pyinstaller打包后，但运行时报如下错误：

Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 142, in __init__
  File "tools/infer/utility.py", line 293, in create_predictor
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libmklml_intel.so) that Paddle depends on is not configured correctly. (error code is libmklml_intel.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:301)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1715260193 (unix time) try "date -d @1715260193" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fd26100ccf0) received by PID 20795 (TID 0x7fd297ac7700) from PID 1627442416 ***]

Segmentation fault (core dumped)
希望得到答复，多谢！

**Comment by UserWangZz** [comment]
#https://github.com/PaddlePaddle/PaddleOCR/discussions/11490
PaddleOCR官方暂不提供打包服务，如有需要，可以参考这个链接进行操作
