### ISSUE TITLE
PPOCRLabel 报错

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleOCR#12091]
默认 python PPOCRLabel.py 没有问题, 可以正常标注 和识别.
使用 python PPOCRLabel.py --lang  ch 报错.
`--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::SelfAttentionFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)
`
是哪里有问题,模型我看调用的是V4的

**Comment by GreatV** [comment]
我这测试了没啥问题呀
<img width="1728" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/a047737c-d2aa-4023-b9a1-9815ca3ed567">
麻烦提供一下运行环境，和标注的图片。

**Comment by UserWangZz** [comment]
可以尝试使用pip 安装ppocrlabel的whl包进行启动，详细步骤参见文档：
https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md#12-%E5%AE%89%E8%A3%85%E4%B8%8E%E8%BF%90%E8%A1%8Cppocrlabel

**Comment by AN-ZE** [comment]
@GreatV 我的环境是这样的. 默认en没有问题, 使用ch就报错了, 程序没有启动,  环境: ubuntu20.4,  python3.10
`anyio                  4.3.0      
astor                  0.8.1      
attrdict               2.0.1      
Babel                  2.15.0     
bce-python-sdk         0.9.7      
blinker                1.8.2      
cachetools             5.3.3      
certifi                2024.2.2   
charset-normalizer     3.3.2      
click                  8.1.7      
coloredlogs            15.0.1     
contourpy              1.2.1      
cssselect              1.2.0      
cssutils               2.10.2     
cycler                 0.12.1     
Cython                 3.0.10     
decorator              5.1.1      
et-xmlfile             1.1.0      
exceptiongroup         1.2.1      
falcon                 3.1.3      
fastdeploy             3.0.14     
flask                  3.0.3      
flask-babel            4.0.0      
flatbuffers            24.3.25    
fonttools              4.51.0     
future                 1.0.0      
gevent                 24.2.1     
greenlet               3.0.3      
gunicorn               22.0.0     
h11                    0.14.0     
httpcore               1.0.5      
httpx                  0.27.0     
humanfriendly          10.0       
idna                   3.7        
imageio                2.34.1     
imgaug                 0.4.0      
itsdangerous           2.2.0      
jinja2                 3.1.4      
kiwisolver             1.4.5      
lazy-loader            0.4        
liteindex              0.0.2.dev63
lmdb                   1.4.1      
lxml                   5.2.1      
markdown-it-py         3.0.0      
MarkupSafe             2.1.5      
matplotlib             3.8.4      
mdurl                  0.1.2      
mpmath                 1.3.0      
networkx               3.3        
numpy                  1.26.4     
onnx                   1.16.0     
onnx-simplifier        0.4.36     
onnxruntime            1.17.3     
opencv-contrib-python  4.6.0.66   
opencv-python          4.9.0.80   
opencv-python-headless 4.9.0.80   
openpyxl               3.1.2      
opt-einsum             3.3.0      
packaging              24.0       
paddle2onnx            1.2.1      
paddlepaddle           2.6.1      
pandas                 2.2.2      
pillow                 10.3.0     
pip                    20.0.2     
premailer              3.10.0     
protobuf               5.26.1     
psutil                 5.9.8      
pybind11               2.12.0     
pyclipper              1.3.0.post5
pycryptodome           3.20.0     
pygments               2.18.0     
pyparsing              3.1.2      
PyQt5                  5.15.10    
PyQt5-Qt5              5.15.2     
PyQt5-sip              12.13.0    
python-dateutil        2.9.0.post0
pytz                   2024.1     
PyYAML                 6.0.1      
rapidfuzz              3.9.0      
rarfile                4.2        
requests               2.31.0     
rich                   13.7.1     
scikit-image           0.23.2     
scipy                  1.13.0     
setuptools             69.5.1     
shapely                2.0.4      
sip                    6.8.3      
six                    1.16.0     
sniffio                1.3.1      
sympy                  1.12       
tifffile               2024.5.10  
tomli                  2.0.1      
tqdm                   4.66.4     
trash-cli              0.24.4.17  
typing-extensions      4.11.0     
tzdata                 2024.1     
urllib3                2.2.1      
visualdl               2.5.3      
werkzeug               3.0.3      
wheel                  0.43.0     
xlrd                   2.0.1      
zope.event             5.0        
zope.interface         6.3        
zstandard              0.22.0  `

**Comment by GreatV** [comment]
@AN-ZE paddlepaddle换成2.5试试看

**Comment by AN-ZE** [comment]
@GreatV 可以了. 可以启动了

**Comment by GreatV** [comment]
这可能是由于 paddlepaddle 2.6 在 non avx512 有问题导致的
- https://github.com/PaddlePaddle/PaddleOCR/issues/11597
develop分支已修复 
 - https://github.com/PaddlePaddle/Paddle/pull/64132/
