### ISSUE TITLE
训练蒙古文，预训练模型应该怎样选择啊

### ISSUE THREAD

**Issue by liuchong540** [PaddlePaddle/PaddleOCR#12097]

**Comment by zhangyubo0722** [comment]
直接使用官方预训练模型即可

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/main/paddleocr.py

**Comment by liuchong540** [comment]
> 直接使用官方预训练模型即可

官方没有蒙古文的预训练模型吧，有多语言的ym配置文件和俄文，日语这些的预训练模型，可以用俄文的预训练模型，然后修改字典，给它标注好的数据直接训练吗

**Comment by UserWangZz** [comment]
是的，可以尝试重新训练一下。
