### ISSUE TITLE
ch_PP-OCRv4_rec_infer识别乱码

### ISSUE THREAD

**Issue by cloudfool** [PaddlePaddle/PaddleOCR#12093]
我用tools/infer/predict_rec.py调用ch_PP-OCRv4_rec_infer模型识别下面两张图时发现识别结果分别是“冏下點”和“冏干文”，请问这是什么原因？谢谢
![img_crop_冏下點](https://github.com/PaddlePaddle/PaddleOCR/assets/22359737/e48f8918-a856-4ec6-9aa2-279152ca7156)
![img_crop_冏干文](https://github.com/PaddlePaddle/PaddleOCR/assets/22359737/ea83245d-0356-4558-95a0-dcdba024ca31)

**Comment by UserWangZz** [comment]
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words_en/word_336.png" --rec_model_dir="./your inference model" --rec_image_shape="3, 48, 320" --rec_char_dict_path="your text dict path"
检查一下是不是模型和字典不匹配

**Comment by cloudfool** [comment]
> python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words_en/word_336.png" --rec_model_dir="./your inference model" --rec_image_shape="3, 48, 320" --rec_char_dict_path="your text dict path" 检查一下是不是模型和字典不匹配

我觉得应该没问题，跑其他图片都是可以的； 你要不帮我测试一下这两张 看看是不是和我的识别结果相同？

**Comment by UserWangZz** [comment]
我复现一下

**Comment by UserWangZz** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/47658498/cbdc08cc-3149-461b-82d8-68a695041ea1)
我这边复现第一张图也出现你所说的问题，怀疑是文字两边的空白太大，我单独截出文字部分识别是正常的
