### ISSUE TITLE
用预训练模型ResNet50_vd_ssld训练时，GPU好像不起作用

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/PaddleOCR#1209]
![微信图片_20201120094734](https://user-images.githubusercontent.com/29444693/99747417-70b2b680-2b15-11eb-9650-83db06ee2825.png)

用预训练模型ResNet50_vd_ssld训练时，显存也有占用1039Mb，GPU利用率却一直是0，感觉是在CPU多线程计算
![image](https://user-images.githubusercontent.com/29444693/99745500-b8850e00-2b14-11eb-842f-9be8d67a779d.png)

怎么才能把GPU用起来？
谢谢

**Comment by WenmuZhou** [comment]
use_gpu是true吗，这个一直是0吗

**Comment by Ficery1** [comment]
@WenmuZhou 恩。一直是0。use_gpu设置的true。

**Comment by WenmuZhou** [comment]
num_workers设大点看看

**Comment by Ficery1** [comment]
> num_workers设大点看看

谢啦。找到原因了。

**Comment by WenmuZhou** [comment]
什么原因，说说看，也许能帮到后面的人

**Comment by Ficery1** [comment]
@WenmuZhou 可能是数据量小的问题，看不出来使用
