### ISSUE TITLE
导出模型 缺少inference.pdiparams

### ISSUE THREAD

**Issue by shuaidaipeng** [PaddlePaddle/PaddleOCR#12098]
用的是主干代码，采用微调模型 后预测是没啥问题的导出模型就只有两个文件。

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/45552232/9b2de799-2c2a-4f71-af8e-52f4d75631b8)

**Comment by zhangyubo0722** [comment]
麻烦提供下复现命令吧

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by LiuJiPeng20** [comment]
我也碰到了相同的问题，请问你现在解决了吗
