### ISSUE TITLE
paddleocr训练自己数据，文本检测不出结果！

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleOCR#12103]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

1.环境：
win10、gpu、cuda11.2、cudnn8.2、paddocr2.7
2.数据：
按照ppocrlabel进行标注，并且显示没有问题；
3.训练：
采用configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml，并修改Backbone:        name: PPLCNetV3        det: true，cal_metric_during_train: false，
然后训练最后1个epoch，loss为0，eval acc为0（是因为设置了cal_metric_during_train: false的原因么？要不报错）
4.模型导出
python tools/export_model.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml -o Global.pretrained_model="./output/ch_PP-OCRv4/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"
导出的是3个文件夹 student、student2、teacher，这3个我都试了，文本检测为空。

导出时出现：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/22360785/7549feb9-43c3-481d-b69f-c9b06ad787c8)

请问这个是配置文件出现问题了么？

**Comment by UserWangZz** [comment]
https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_train.tar
configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml
尝试这个

**Comment by gengyanlei** [comment]
@UserWangZz 谢谢啦

**Comment by gengyanlei** [comment]
@UserWangZz  谢谢
我一开始看这个链接也是对应的ch_PP-OCRv4_det_cml.yml呢，它也对应student.yml呢
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/22360785/713b677f-9ff9-4484-8da8-db2881ee933b)

**Comment by UserWangZz** [comment]
问题解决了吗？

**Comment by gengyanlei** [comment]
@UserWangZz 
正在训练中，loss啥的都正常了。待测试

**Comment by UserWangZz** [comment]
你好，请问还有问题吗
