### ISSUE TITLE
PaddlePaddle catches a failure signal, it may not work properly

### ISSUE THREAD

**Issue by ksnxr** [PaddlePaddle/PaddleOCR#1210]
使用自己的数据集训练文字检测模型报错，无法进行训练。
PaddlePaddle版本为1.8.5

W1120 09:43:20.043994 207564800 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1120 09:43:20.044198 207564800 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1120 09:43:20.044301 207564800 init.cc:231] The detail failure signal is:

W1120 09:43:20.044389 207564800 init.cc:234] *** Aborted at 1605836600 (unix time) try "date -d @1605836600" if you are using GNU date ***
W1120 09:43:20.045176 207564800 init.cc:234] PC: @                0x0 (unknown)
W1120 09:43:20.045521 207564800 init.cc:234] *** SIGSEGV (@0x110) received by PID 14665 (TID 0x70000c5f3000) stack trace: ***
W1120 09:43:20.045671 207564800 init.cc:234]     @     0x7fff708665fd _sigtramp
W1120 09:43:20.045800 207564800 init.cc:234]     @     0x7fff70624b2b dispatch_apply_f
W1120 09:43:20.046893 207564800 init.cc:234]     @        0x11bb3b2f2 cv::parallel_for_()
W1120 09:43:20.047261 207564800 init.cc:234]     @        0x11bf43911 cv::hal::warpAffine()
W1120 09:43:20.047538 207564800 init.cc:234]     @        0x11bf44556 cv::warpAffine()
W1120 09:43:20.047777 207564800 init.cc:234]     @        0x11b7a7c9c pyopencv_cv_warpAffine()
W1120 09:43:20.048107 207564800 init.cc:234]     @        0x10cebe832 _PyMethodDef_RawFastCallKeywords
W1120 09:43:20.048276 207564800 init.cc:234]     @        0x10cffc1e2 call_function
W1120 09:43:20.048429 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.048832 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.049029 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.049448 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.049636 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.049798 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.049963 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.050110 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.050256 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.050401 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.050542 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.050698 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.050855 207564800 init.cc:234]     @        0x10cff8ee8 _PyEval_EvalFrameDefault
W1120 09:43:20.050998 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.051137 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.051280 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.051618 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.051777 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.052009 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.052486 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.052664 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.052816 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.052956 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.053107 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.203541 207564800 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1120 09:43:20.203789 207564800 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1120 09:43:20.203902 207564800 init.cc:231] The detail failure signal is:

W1120 09:43:20.203996 207564800 init.cc:234] *** Aborted at 1605836600 (unix time) try "date -d @1605836600" if you are using GNU date ***
W1120 09:43:20.204331 207564800 init.cc:234] PC: @                0x0 (unknown)
W1120 09:43:20.204522 207564800 init.cc:234] *** SIGSEGV (@0x110) received by PID 14672 (TID 0x70000c5f3000) stack trace: ***
W1120 09:43:20.204661 207564800 init.cc:234]     @     0x7fff708665fd _sigtramp
W1120 09:43:20.204797 207564800 init.cc:234]     @     0x7fff70624b2b dispatch_apply_f
W1120 09:43:20.205734 207564800 init.cc:234]     @        0x11bb3b2f2 cv::parallel_for_()
W1120 09:43:20.206126 207564800 init.cc:234]     @        0x11bf43911 cv::hal::warpAffine()
W1120 09:43:20.206432 207564800 init.cc:234]     @        0x11bf44556 cv::warpAffine()
W1120 09:43:20.206697 207564800 init.cc:234]     @        0x11b7a7c9c pyopencv_cv_warpAffine()
W1120 09:43:20.207058 207564800 init.cc:234]     @        0x10cebe832 _PyMethodDef_RawFastCallKeywords
W1120 09:43:20.207242 207564800 init.cc:234]     @        0x10cffc1e2 call_function
W1120 09:43:20.207401 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.207610 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.207763 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.208132 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.208323 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.208489 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.208647 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.208806 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.208964 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.209175 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.209326 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.209482 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.209640 207564800 init.cc:234]     @        0x10cff8ee8 _PyEval_EvalFrameDefault
W1120 09:43:20.209794 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.209946 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.210103 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.210258 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.210471 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.210620 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.210801 207564800 init.cc:234]     @        0x10cffc167 call_function
W1120 09:43:20.210958 207564800 init.cc:234]     @        0x10cff9f79 _PyEval_EvalFrameDefault
W1120 09:43:20.211117 207564800 init.cc:234]     @        0x10cfed86e _PyEval_EvalCodeWithName
W1120 09:43:20.211267 207564800 init.cc:234]     @        0x10cebe563 _PyFunction_FastCallKeywords
W1120 09:43:20.211421 207564800 init.cc:234]     @        0x10cffc167 call_function

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/Paddle/issues/28491  帮你找到了这个，看看能不能解决

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
