### ISSUE TITLE
LINUX  服务器使用OCR 报错 ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xjune123** [PaddlePaddle/PaddleOCR#12102]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： LINUX 9.3 (Blue Onyx)
- 版本号/Version：Paddle： paddleocr-2.7.3  python3.8  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：    result = ocr.ocr(img_path, cls=True)

- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "ocr_single.py", line 2, in <module>
    from paddleocr import PaddleOCR
  File "/data/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/data/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 25, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by xjune123** [comment]
需要手工安装一下该依赖，
sudo yum install mesa-libGL -y

**Comment by Qurite** [comment]
安装完libGL 后执行报错，如图<img width="2002" height="1266" alt="Image" src="https://github.com/user-attachments/assets/69aa1bbb-b1d8-48d5-8da2-19c8d9606cd7" />
