### ISSUE TITLE
pdf中原文放到txt中会比普通字符矮一些的非正常字符是什么字符？怎么转换成正常字符？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#12112]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/b342bdc2-829d-4126-9adb-027f67ba437f)

**Comment by nissansz** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/624233c6-6b1b-47db-a448-e74be1779f9d)
用微软雅黑字体才可以看出区别

**Comment by UserWangZz** [comment]
这个应该是编码问题吧，我也不太清楚
