### ISSUE TITLE
batch 推理文本检测

### ISSUE THREAD

**Issue by wufan-tb** [PaddlePaddle/PaddleOCR#12119]
请问PaddleOCR可以batch推理文本检测+识别么，我看到目前的ocr接口在输入list且进行检测的时候会报error，不知道是否有其他的接口支持batch的方式同时做检测+识别呢：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/34300920/fc250dd3-8b5b-40b1-89ab-4894963621dd)

**Comment by UserWangZz** [comment]
paddleocr在推理中，deteciton的batchsize必须为1

**Comment by UserWangZz** [comment]
所以当输入图像为list是，只能做识别任务

**Comment by wufan-tb** [comment]
那有其他接口支持batch推理检测么

**Comment by Sunting78** [comment]
deteciton的batchsize必须为1  暂无其他接口
