### ISSUE TITLE
paddle 开启GPU以后 速度比 use-gpu=false更慢

### ISSUE THREAD

**Issue by meilovegui** [PaddlePaddle/PaddleOCR#12116]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11  CUDA:12.1 python：3.8.9、paddleocr：2.7.3
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- `程序执行时间：5.861234664916992秒
Running verify PaddlePaddle program ...
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`
`

`# 记录开始时间
start_time = time.time()
orc = PaddleOCR(lang='ch',use_angle_cls=True,use_gpu=True)
result = orc.ocr('images/sfz/03-1.png')
print(result)
end_time = time.time()
execution_time = end_time - start_time
print(f"程序执行时间：{execution_time}秒")`

**Comment by meilovegui** [comment]
`# 记录开始时间
start_time = time.time()
orc = PaddleOCR(lang='ch',use_angle_cls=True,use_gpu=True)
result = orc.ocr('images/sfz/03-1.png')
print(result)
end_time = time.time()
execution_time = end_time - start_time
print(f"程序执行时间：{execution_time}秒")`

**Comment by GreatV** [comment]
测一张图没法说明问题

**Comment by UserWangZz** [comment]
因为将数据移动到显存内会消耗一定时间，建议批量测试后计算一下平均时间
