### ISSUE TITLE
使用GPU时检测不到文字但CPU可以

### ISSUE THREAD

**Issue by sdflkjssl** [PaddlePaddle/PaddleOCR#12115]
用的官方默认模型，使用GPU时检测不到文字但CPU可以（无论官方样例图片还是自己图片都是这样）。

- 系统环境/System Environment：Windows 10
- 版本号/Version：PaddlePaddle-GPU：2.5.2  PaddleOCR：2.7.0.2

CPU下（`paddleocr --image_dir .\pages\01.jpg --use_gpu false`）输出：
```
[2024/05/14 08:17:25] ppocr DEBUG: dt_boxes num : 80, elapse : 1.6079998016357422
[2024/05/14 08:18:30] ppocr DEBUG: rec_res num  : 80, elapse : 65.6988878250122
......
```

GPU下（`paddleocr --image_dir .\pages\01.jpg`）输出：
```
[2024/05/14 08:16:53] ppocr DEBUG: dt_boxes num : 0, elapse : 4.8608012199401855
[2024/05/14 08:16:53] ppocr DEBUG: rec_res num  : 0, elapse : 0.0
```

**Comment by GreatV** [comment]
用的是什么显卡呀？

**Comment by GreatV** [comment]
@sdflkjssl paddle框架太旧的显卡不支持，你得自己重新编译一下paddle。

**Comment by GreatV** [comment]
> 但为啥它不报错呀，是不是bug？

这个你得在 https://github.com/PaddlePaddle/paddle 仓库反馈

**Comment by suoixnazx** [comment]
请问您能告诉我dt_boxes num这三个数据是什么意思吗

**Comment by UserWangZz** [comment]
> 请问您能告诉我dt_boxes num这三个数据是什么意思吗

dt_boxes num 是检测模型检测到的box数目，elapse是所用时间

**Comment by suoixnazx** [comment]
非常感谢您的解答，这解开了我心中的疑惑



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月16日 10:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 使用GPU时检测不到文字但CPU可以 (Issue #12115) |

请问您能告诉我dt_boxes num这三个数据是什么意思吗

dt_boxes num 是检测模型检测到的box数目，elapse是所用时间

**Comment by UserWangZz** [comment]
不客气

> 非常感谢您的解答，这解开了我心中的疑惑
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年05月16日 10:07 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [PaddlePaddle/PaddleOCR] 使用GPU时检测不到文字但CPU可以 (Issue #12115) | 请问您能告诉我dt_boxes num这三个数据是什么意思吗 dt_boxes num 是检测模型检测到的box数目，elapse是所用时间 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
