### ISSUE TITLE
字符间距大跟空格很像，造成空白区域被误识别成错误字符，如何解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#12111]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.7.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
字符间距大跟空格很像，造成空白区域被误识别成错误字符，如何解决？如何判断字符间距是否大，从而通过压扁图片，缩小间距改善结果？
原图
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/9e6e8751-009c-4e2b-b8fb-597b54edf48e)
识别结果有时会出现多余错误字符
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/f7f6ab84-76d8-4a8b-bdca-31672b7bffcd)

**Comment by UserWangZz** [comment]
这个场景目前没有很好的解决方案，可以尝试压缩图像解决，或者针对该场景训练特定的识别模型

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
