### ISSUE TITLE
使用合成数据集进行训练，数据集标注全数字训练，识别出汉字

### ISSUE THREAD

**Issue by kejiusi94** [PaddlePaddle/PaddleOCR#12125]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.2, Runtime API Version: 11.2 device: 0, cuDNN Version: 8.9.
- 版本号/Version：Paddle：  PaddleOCR：PaddleOCR-release-2.7 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer/predict_system.py --image_dir="D:\yolov8\runs\detect\predict\crops\digital\hsv821.jpg" --det_model_dir="D:\PaddleOC
R-release-2.7\inference_model\ch_PP-OCRv4_det_server_infer" --rec_model_dir="D:\PaddleOCR-release-2.7\inference_model\rec"
- 完整报错/Complete Error Message：诚廖'溜题廖伺, 0.836
- 
[train.txt](https://github.com/PaddlePaddle/PaddleOCR/files/15328769/train.txt)

![hsv821](https://github.com/PaddlePaddle/PaddleOCR/assets/169960940/b3b1173b-7a86-483f-8c32-3ef5819706f2)

![hsv821](https://github.com/PaddlePaddle/PaddleOCR/assets/169960940/4398b4c1-2454-4631-bc27-0c255d169c52)

**Comment by kejiusi94** [comment]
![Uploading hsv821.jpg…]()

**Comment by UserWangZz** [comment]
使用训练模型和infer_rec脚本推理一下试试，可能是转inference模型时字典不匹配

**Comment by kejiusi94** [comment]
> 使用训练模型和infer_rec脚本推理一下试试，可能是转inference模型时字典不匹配

那转inference模型字典不匹配的问题该如何解决

**Comment by UserWangZz** [comment]
查看对应config文件，predict_system使用的是静态图模型文件，确保它推理时使用的字典文件和你训练时使用的字典文件一致

**Comment by kejiusi94** [comment]
> 查看对应config文件，predict_system使用的是静态图模型文件，确保它推理时使用的字典文件和你训练时使用的字典文件一致

谢谢，问题解决了，只要在预测命令行后加上训练时使用的字典地址就行了

**Comment by UserWangZz** [comment]
不客气哦❤️❤️
