### ISSUE TITLE
Saving the result of ocr model into a csv

### ISSUE THREAD

**Issue by saanvib13** [PaddlePaddle/PaddleOCR#12129]
![brhc10047269ex99-1_slide29](https://github.com/PaddlePaddle/PaddleOCR/assets/109897011/0963394f-0a16-493e-afe8-cfa849569402)
![brhc10047269ex99-1_slide30](https://github.com/PaddlePaddle/PaddleOCR/assets/109897011/2571a498-6466-4511-adca-cf284f4e9187)
![brhc10047269ex99-1_slide03](https://github.com/PaddlePaddle/PaddleOCR/assets/109897011/de54aa2f-ae10-44a0-8d26-58fbea40872c)
I am extracting the tables from these images into a csv file using paddleocr. The ocr model detects the table and the text inside it correctly, but when i reconstruct the text into a csv file, some values get altered and others get omitted. How to reconstruct the table and save it to a csv from the text detected ?

Pls share your views.

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppstructure/table/README.md
you can reference this document.

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/12130
