### ISSUE TITLE
Vertical text detection

### ISSUE THREAD

**Issue by baireddy417** [PaddlePaddle/PaddleOCR#1213]
I was trying to do vertical english text detection where the text contains individual letters aligned vertically one by one but the model is not working can you help me out
example
A
B
5
2
D
in this format

**Comment by LDOUBLEV** [comment]
The predicted results of the inference model ‘ch_ppocr_mobile_v1.1_det_infer’ as below:
![image](https://user-images.githubusercontent.com/26592129/99768330-876e0300-2b3f-11eb-8da1-2117d766d6f0.png)

The prerequisite for detecting vertical text is that there is vertical text in the training data.

**Comment by baireddy417** [comment]
Without training is it possible to detect vertical text and recognise it

**Comment by littletomatodonkey** [comment]
The vertical text should exists in the train set, or it will be very hard for the model.

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by aisensiy** [comment]
![image](https://user-images.githubusercontent.com/661860/178802468-c89b44f7-67fc-4ae1-9e5c-bedc935441ca.png)


I have similar problem that vertical text seems not well recognized.

But the horizontal one works well.

![image](https://user-images.githubusercontent.com/661860/178802904-9680ac89-68be-45fd-b83f-d0675a420cb7.png)
