### ISSUE TITLE
How to Merge text boxes on adjacent lines ?

### ISSUE THREAD

**Issue by Thanhthanhthanhthanh1711** [PaddlePaddle/PaddleOCR#12134]
I want to combine these 2 boxes into one box, how about?
![441105500_743539397964838_6124271347156258321_n](https://github.com/PaddlePaddle/PaddleOCR/assets/115617100/ce4a9d9b-7123-4075-ade8-4a2ca9a61bba)

**Comment by UserWangZz** [comment]
The current detection models all detect text lines. If there is such a need, you need to fuse the two boxes in the post-processing stage.
