### ISSUE TITLE
TritonModelException: inference request batch-size must be <= 128 for 'cls_pp'

### ISSUE THREAD

**Issue by sheiy** [PaddlePaddle/PaddleOCR#12135]
- 系统环境/System Environment：
- 版本号/Version：Paddle：  
- PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
```
FROM registry.baidubce.com/paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.4-trt8.5-21.10
COPY ./models-gpu.tar /ocr_serving/
WORKDIR /ocr_serving
RUN tar -xf models-gpu.tar
RUN rm models-gpu.tar
EXPOSE 8000
CMD ["fastdeployserver","--model-repository=/ocr_serving/models"]

```
- 完整报错/Complete Error Message：
<img width="880" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/12210038/7f9814ad-8c6a-415d-bc22-49632bf3aa55">
<img width="1579" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/12210038/df7a015a-75c1-4fc1-94fd-a80128f408d2">

**Comment by sheiy** [comment]
麻烦问下 需要怎么处理啊 直接修改配置吗？

**Comment by zhangyubo0722** [comment]
OCR套件并不支持Triton部署，请问你是在哪里看到的命令或文档呢

**Comment by sheiy** [comment]
@zhangyubo0722 https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving/fastdeploy_serving
那能否给我一个适合部署成api接口的文档呢

**Comment by eshine996** [comment]
@sheiy 请教一下，请问怎么解决的这个问题？

**Comment by eshine996** [comment]
@sheiy 我应该知道为啥有这个问题。因为det的时候，图片上超过128个bbox，再cls做批处理的时候，batch size就超过了设置的最大值。
