### ISSUE TITLE
saving tables detected in an image to csv

### ISSUE THREAD

**Issue by saanvib13** [PaddlePaddle/PaddleOCR#12130]
![image00051](https://github.com/PaddlePaddle/PaddleOCR/assets/109897011/c19fe44e-04de-47b4-ad83-0194741e2275)
[table_1_image00051.jpg.csv](https://github.com/PaddlePaddle/PaddleOCR/files/15335174/table_1_image00051.jpg.csv)
I have uploaded an image and its resultant extracted table in a csv. But the values in the csv are inconsistent. Symbols are missing, some values are repeated. How to improve this output. What steps can be taken?
How to preprocess the image or reconstruct the table to improve the output stored in the csv file?

**Comment by UserWangZz** [comment]
This issue is repeat. This issue will be closed and referenced to the duplicate issue.
