### ISSUE TITLE
PaddleOCR throwing fscanf failed

### ISSUE THREAD

**Issue by subhankardori** [PaddlePaddle/PaddleOCR#12138]
`W0517 10:10:58.219796   252 default_variables.cpp:95] Fail to fscanf: Success [0]`

By any chance, does it have some relevance with Core Dumped , asking because when I was using the latest version of paddlepaddle-gpu, I was constantly hitting this error inside the docker:

```
root@f76833e33ee6:/code/build/data# python3 paddle_and_annotate.py 
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   inflateReset2

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1715786295 (unix time) try "date -d @1715786295" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 207 (TID 0x71e2902e2b80) from PID 0 ***]

Segmentation fault (core dumped)
root@f76833e33ee6:/code/build/data# 
```

so the mysterious part is that when I was running a simple code for paddleocr, it was running hassle-free, but when I was testing and end-to-end operation (in whcih that snippet of paddleocr code was a part), `W0517 10:10:58.219796   252 default_variables.cpp:95] Fail to fscanf: Success [0]` this is the warning log I am getting. Anything concerning about this log?

**Comment by SWHL** [comment]
First, it is recommended to verify that the PaddlePaddle framework is successfully installed.
```python
import paddle

paddle.utils.run_check()
# PaddlePaddle is installed successfully!
```
Then, please provide the smallest reproducible demo.

**Comment by MonolithFoundation** [comment]
I got same isse.
Please, don't make users always reproducable.

<img width="826" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/168061642/6545bae1-fb67-4fc2-8850-be7b4279f5fb">


Than l am here rerproducable.

**Comment by SWHL** [comment]
Please provide the most basic operating environment so that we can reproduce this error locally and make the necessary modifications?

OS:
PaddleOCR:
Python:
Code:
```Python

```

If you only provide error information without providing context, we cannot solve it here! Because we don't know in what environment this error was reported.

**Comment by MonolithFoundation** [comment]
I have uninstalled paddlepaddleocr.

**Comment by subhankardori** [comment]
@SWHL 
W0605 10:33:27.962114    83 default_variables.cpp:95] Fail to fscanf: Success [0]
this is just a cpp warning, give me a fix to force suppress this, causing a lot of hindrance while reading logs on production
searched everywhere on the net and ChatGPT, didnt find any

**Comment by SWHL** [comment]
@subhankardori you are right, I mistakenly thought it was an error log

**Comment by subhankardori** [comment]
```
OS: Ubuntu 22.04.1 LTS 
PaddleOCR version: 2.7.3
Python version: Python 3.10.12
Paddle version: 2.5.2, had to downgrade the version of paddlepaddle-gpu, since the latest wasnt working inside container
Code: can't be disclosed
```
But one key here is that, this is only occuring inside docker container, not when I am doing a ppocr inference on the local machine

**Comment by SWHL** [comment]
That's weird, and this is beyond my ability range.
Wait and see if other friends have encountered this problem before

**Comment by subhankardori** [comment]
here are some things I tried to suppress it, but didnt work, may act as pointer
```
import os
import sys

# Redirect stderr to /dev/null
sys.stderr = open(os.devnull, 'w')

# Your code here
```

OR
```
import warnings
warnings.filterwarnings("ignore", message="Fail to fscanf.*")
```
didnt work to suppress this C++ warning

**Comment by MonolithFoundation** [comment]
Just uninstall paddleocr, it's really bad to use.

**Comment by SWHL** [comment]
@MonolithFoundation We are trying to make it more easier to use. 
If you don't like it, just don't use it and don't let it affect your mood.

**Comment by subhankardori** [comment]
@MonolithFoundation chill man, patience is the key, we will collaboratively sort it out

**Comment by SWHL** [comment]
@subhankardori
I suspect it's an issue with the PaddlePaddle framework, so I raised an issue in the Paddle repository. We can wait and see how they respond. The link is https://github.com/PaddlePaddle/Paddle/issues/64969
