### ISSUE TITLE
v2.7.0.3以后部分图片识别有问题

### ISSUE THREAD

**Issue by jaminegod** [PaddlePaddle/PaddleOCR#12147]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle：2.6.1-gpu  PaddleOCR：2.7.0.3以后  问题相关组件/Related components：paddleocr
- 运行指令/Command Code：paddleocr  --use_gpu=True --det=True --rec=True --ocr_version=PP-OCRv3  --image_dir=/home/aistudio/data/
- 完整报错/Complete Error Message：无错误，但部分图片识别不对
![20240521093904](https://github.com/PaddlePaddle/PaddleOCR/assets/13401533/b380f709-e090-472c-86f4-e011757c050d)
但v2.7.0.2及之前版本可以识别，如下：
![20240521094149](https://github.com/PaddlePaddle/PaddleOCR/assets/13401533/cfa44696-26db-4bac-b78c-0b734ef19599)

**Comment by GreatV** [comment]
麻烦提供一下测试图片

**Comment by jaminegod** [comment]
这个图片，麻烦测试后请清除，不要外传



***@***.***
 
发件人： Wang Xin
发送时间： 2024-05-21 13:05
收件人： PaddlePaddle/PaddleOCR
抄送： jaminegod; Author
主题： Re: [PaddlePaddle/PaddleOCR] v2.7.0.3以后部分图片识别有问题 (Issue #12147)
麻烦提供一下测试图片

**Comment by GreatV** [comment]
@jaminegod 无法看到图片

**Comment by jaminegod** [comment]
确实是带了附件的，如下。

大概原因是图像的方向数据与图像的真实方向没对上，paddleocr在后面版本的处理上跟之前版本不一致，当然不排除跟引入的第三方组件也有些关系。
我再发一次图片。



***@***.***
 
发件人： Wang Xin
发送时间： 2024-05-21 13:17
收件人： PaddlePaddle/PaddleOCR
抄送： jaminegod; Mention
主题： Re: [PaddlePaddle/PaddleOCR] v2.7.0.3以后部分图片识别有问题 (Issue #12147)
@jaminegod 无法看到图片

**Comment by jaminegod** [comment]
大概原因是图像的方向数据与图像的真实方向没对上，paddleocr在后面版本的处理上跟之前版本不一致，当然不排除跟引入的第三方组件也有些关系。
涉客户隐私信息，不方便外发，参考说明就行。如要真实图片测试，加V15112421071

**Comment by GreatV** [comment]
@jaminegod  需要指定 `--use_angle_cls=True`

**Comment by UserWangZz** [comment]
使用PIL读取图片有可能会造成图片方向问题
可以参考这个
https://blog.csdn.net/sxrkm6s4csx/article/details/117525646
from PIL import Image, ImageOps

 img = Image.open(img_path)
 img = ImageOps.exif_transpose(img)

**Comment by TingquanGao** [comment]
该问题已解决，issue关闭，如仍有问题可以reopen或新提issue~
