### ISSUE TITLE
训练SAST报错

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1214]
训练自己的数据的时候，下面是我的配置文件，执行命令会报错。
![IXG$P7MZO1@2IBPFH60Z~ZJ](https://user-images.githubusercontent.com/56471409/99778323-82fd1680-2b4e-11eb-9e76-e15ab11ec5ee.png)
![4FPPX%CQW9E)H~~N0064K@Y](https://user-images.githubusercontent.com/56471409/99778334-85f80700-2b4e-11eb-8cc5-12661227d5b2.png)
![GT~)(UUJ7UJARLJ%W0XVM1Q](https://user-images.githubusercontent.com/56471409/99778384-960fe680-2b4e-11eb-8c54-a913b964a7f3.png)
关于min_crop_size,min_text_size,max_text_size以及max_side_len 四个参数，理解不是很明白

**Comment by WenmuZhou** [comment]
720换成736看看

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/99925921-d5bb1600-2d7a-11eb-9186-d6f98d10a2fa.png)
这里不能被32整除，所以经过几次下采样后会产生1个像素的误差，导致你这个报错。

**Comment by SealQ** [comment]
> ![image](https://user-images.githubusercontent.com/25809855/99925921-d5bb1600-2d7a-11eb-9186-d6f98d10a2fa.png)
> 这里不能被32整除，所以经过几次下采样后会产生1个像素的误差，导致你这个报错。

这里的图片的大小必须要使用32的倍数么？

**Comment by SealQ** [comment]
> ![image](https://user-images.githubusercontent.com/25809855/99925921-d5bb1600-2d7a-11eb-9186-d6f98d10a2fa.png)
> 这里不能被32整除，所以经过几次下采样后会产生1个像素的误差，导致你这个报错。

![image](https://user-images.githubusercontent.com/56471409/100299096-c54ea980-2fcd-11eb-877b-f6f709d5ef0b.png)
这里的image_shape修正为[3, 1280, 1280]后出现了新的报错
