### ISSUE TITLE
想更改table_structure_dict_ch.txt的映射数量，除了这个txt文件夹，还需要对哪些文件进行修改

### ISSUE THREAD

**Issue by plotnine1219** [PaddlePaddle/PaddleOCR#12144]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
直接修改这个就可以

**Comment by plotnine1219** [comment]
> 直接修改这个就可以

表格结构预测结果非常差，就连eos这种终止符都预测不出来，是因为没有检测头输出类别数量的训练权重吗

**Comment by tink2123** [comment]
这个文件对应预测头的维度，修改后需要重新训练的。否则权重无法正确加载，只能输出随机结果

**Comment by plotnine1219** [comment]
> 这个文件对应预测头的维度，修改后需要重新训练的。否则权重无法正确加载，只能输出随机结果

还有一个小问题，我的数据集都是空表格就是表格里都没字符，对于这种情况，使用tablemaster效果会不会比slanet效果好

**Comment by tink2123** [comment]
tablemaster的模型参数量会更大一些，如果对精度要求高于速度要求可以使用Tablemaster
