### ISSUE TITLE
请问,在VC++下，怎么获取识别出来的文字坐标~！

### ISSUE THREAD

**Issue by flymoon1981** [PaddlePaddle/PaddleOCR#1215]
请问,在VC++下，怎么获取识别出来的文字坐标~！

**Comment by WenmuZhou** [comment]
直接把https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/src/main.cpp#L86  这个boxes返回就行

**Comment by flymoon1981** [comment]
是在rec.Run(boxes, srcimg, cls);后返回boxes对吗？谢谢

**Comment by WenmuZhou** [comment]
在函数结尾返回就行

**Comment by flymoon1981** [comment]
好的..已经成功了，，谢谢
