### ISSUE TITLE
英文字符问题

### ISSUE THREAD

**Issue by tintinxue1** [PaddlePaddle/PaddleOCR#1216]
试了8M的版和155M版，因为字符好像大部分都有问题，比如dollar sign, 小数点什么的，请问这是什么原因？（我也试了en rec model，效果一样)

**Comment by MissPenguin** [comment]
可以先确认下字典中是否包含这些字符，如果已经包含了，应该是因为包含这类字符的训练数据较少，导致效果较差，可以补充一些这类数据进行finetune试试。

**Comment by yangtianyu92** [comment]
对小数点   .     和     -       这两个字符识别的效果非常的差劲。之前没发现，现在发现了要上生产真是要死了。
