### ISSUE TITLE
基于预训练模型finetune时，输入网络的尺寸的问题

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1217]
由于样本图片尺寸大，按默认配置的image_shape 3,32,320过小，调整尺寸放大时报错After flatten the input tensor X and Y to 2-D dimensions matrix X1 and Y1,the matrix x1`s width must be equal with matrix Y1`s height。 新设置的尺寸3,160,1600也是32的倍数，不基于V1.1预训练模型就可以改变尺寸，用了预训练模型就报错。这是为什么？不能修改image_shape?

**Comment by WenmuZhou** [comment]
因为预训练模型里有fc和lstm 这两个对尺寸敏感

**Comment by strWuYaoJu** [comment]
@WenmuZhou 我也遇到类似问题，改如何解决？？？？
