### ISSUE TITLE
建议对parser.add_argument( )添加参数描述字段

### ISSUE THREAD

**Issue by GritCoder** [PaddlePaddle/PaddleOCR#1220]
建议对诸如这样的参数添加--help字段 描述说明，这样看起来可读性会更高一些，尽管咱们有些参数命名是‘’见名知义”的
    parser.add_argument("--enable_mkldnn", type=str2bool, default=False)
    parser.add_argument("--use_zero_copy_run", type=str2bool, default=False)
    parser.add_argument("--use_pdserving", type=str2bool, default=False)

**Comment by littletomatodonkey** [comment]
好的，感谢你的反馈~我们近期添加下

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
