### ISSUE TITLE
C++版本预测库头文件不包含抛出异常类型的头文件

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1227]
由于缺少含异常类型的头文件，导致无法捕获如paddle::platform::EnforceNotMet这类的异常，使得程序会崩卡住。使用通用捕获    catch (...) 又会和其他不在catch分支的异常无法区分。建议后续加入异常类型的头文件。去Paddle主库能找到包含这个类型的头文件，但是又会需要一串的其他头文件，从主库提取就很麻烦。

**Comment by littletomatodonkey** [comment]
建议使用paddle inference最新release的库

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
