### ISSUE TITLE
paddleocr c++编译问题

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/PaddleOCR#1229]
[sudo] password for rex: 
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.cpp.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.cpp.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.cpp.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.cpp.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.cpp.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.cpp.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.cpp.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.cpp.o
[100%] Linking CXX executable ocr_system
/usr/bin/ld: warning: libiomp5.so, needed by /home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libdnnl.so.1, needed by /home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so, not found (try using -rpath or -rpath-link)
CMakeFiles/ocr_system.dir/src/ocr_cls.cpp.o: In function `PaddleOCR::Classifier::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/rex/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:86: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.cpp.o: In function `PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/rex/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:21: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.cpp.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/rex/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:124: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_set_scales'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_dilated_convolution_backward_data_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_query'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_loop_end_nowait@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_engine_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_loop_static_next@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_matmul_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_engine_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_post_ops_append_sum'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_post_ops_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_parallel_start@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_desc_init_by_strides'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_parallel_end@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_concat_primitive_desc_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_lrn_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_desc_reshape'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_set_output_scales'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_execute'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_binary_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_loop_ull_static_next@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_get_memory_desc'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_loop_ull_static_start@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_softmax_backward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_barrier@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_inner_product_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `omp_get_num_threads@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `GOMP_loop_static_start@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_stream_wait'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_set_data_handle_v2'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_eltwise_backward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_post_ops_append_eltwise'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_post_ops_append_sum_v2'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_layer_normalization_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_post_ops_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_dilated_convolution_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_query_md'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_sum_primitive_desc_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_dilated_convolution_backward_weights_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_iterator_fetch'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `omp_set_num_threads@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_gru_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_dilated_deconvolution_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_desc_get_size'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_pooling_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_reorder_primitive_desc_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_stream_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_lrn_backward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_set_rnn_data_qparams'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_desc_equal'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `omp_get_max_threads@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `omp_get_thread_num@VERSION'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_desc_init_by_tag'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_batch_normalization_backward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_iterator_destroy'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_set_rnn_weights_qparams'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_softmax_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_get_data_handle'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_stream_create_v2'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_memory_get_engine'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_batch_normalization_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_pooling_backward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_eltwise_forward_desc_init'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_desc_iterator_create'
/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so: undefined reference to `dnnl_primitive_attr_set_post_ops'
collect2: error: ld returned 1 exit status
CMakeFiles/ocr_system.dir/build.make:262: recipe for target 'ocr_system' failed
make[2]: *** [ocr_system] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
在最后一步：make -j后报错如上所述，下载的是paddle_inference官方预测库，2.0.0-rc0版本,环境是ubuntu18,cuda10.0,cudnn7.6.5,cmake3.18,libiomp5.solibdnnl.so.1在预测库中都存在，麻烦解答一下，谢谢。

**Comment by LDOUBLEV** [comment]
这个路径是对的吗：/home/rex/paddle_inference/paddle_inference_install_dir/paddle/lib/libpaddle_fluid.so

**Comment by ABlueLight** [comment]
```
/home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:38: undefined reference to `paddle_infer::Predictor::GetInputNames[abi:cxx11]()'
/usr/bin/ld: /home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:39: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:46: undefined reference to `paddle_infer::Predictor::GetOutputNames[abi:cxx11]()'
/usr/bin/ld: /home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:47: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/ocr_system.dir/src/ocr_cls.o: in function `PaddleOCR::Classifier::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:74: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/ocr_system.dir/src/ocr_det.o: in function `PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:22: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/ocr_system.dir/src/ocr_det.o: in function `PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&)':
/home/sky/yisuoOCR/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:74: undefined reference to `paddle_infer::Predictor::GetInputNames[abi:cxx11]()
``
同样的问题

**Comment by ABlueLight** [comment]
@python-bookworm  他们的paddle推理库预编译的是gcc 4.8版本的，不知道是不是gcc版本差异过大，导致的符号问题。我重新在自己的系统上重新编译了paddle推理库后，就正常了，你可以试试。
