### ISSUE TITLE
空格识别问题

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1230]
您好，我想使用自己的数据训练识别模型，识别英文空格，为什么识别出来的空格是“-”符号呢，我标注空格使用的是空格。

**Comment by WenmuZhou** [comment]
字典里面有空格这个字符吗

**Comment by tyy2tyy** [comment]
有的

**Comment by WenmuZhou** [comment]
use_space_char要设置为true才行的，另外空格字符代码会自动加到字典里的，不用手动添加到字典

**Comment by tyy2tyy** [comment]
额，我重新训练了模型，但发现对于空格识别太差了，而且将原来空格的地方替换成了“-"和“.”，并且识别的效果也不佳

**Comment by littletomatodonkey** [comment]
你好，一方面，标注数据我们标了空格，另一方面，也合成了大量的带空格数据，保证空格效果

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
