### ISSUE TITLE
文本方向训练报错

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1231]
![1606187368(1)](https://user-images.githubusercontent.com/56471409/100042075-a58c7980-2e45-11eb-9753-f2c4b7806cba.jpg)
数据增强的过程中报以上错误

**Comment by SealQ** [comment]
![1606192388(1)](https://user-images.githubusercontent.com/56471409/100049029-4cc2de00-2e51-11eb-8d09-3bd96aba992c.jpg)
ch出现新的Warning

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/rec/img_tools.py#L200-L202  把这三行都改为false即可
