### ISSUE TITLE
iosdemo 出现错误 Unknown type name 'float32x4_t'

### ISSUE THREAD

**Issue by xinxiwang** [PaddlePaddle/PaddleOCR#1232]
void neon_mean_scale(const float *din, float *dout, int size, std::vector<float> mean, std::vector<float> scale) {
    float32x4_t vmean0 = vdupq_n_f32(mean[0]);
    float32x4_t vmean1 = vdupq_n_f32(mean[1]);
    float32x4_t vmean2 = vdupq_n_f32(mean[2]);
    float32x4_t vscale0 = vdupq_n_f32(1.f / scale[0]);
    float32x4_t vscale1 = vdupq_n_f32(1.f / scale[1]);
    float32x4_t vscale2 = vdupq_n_f32(1.f / scale[2]);

**Comment by xinxiwang** [comment]
![Uploading image.png…]()

**Comment by xinxiwang** [comment]
![image](https://user-images.githubusercontent.com/33017656/100046821-f99a5c80-2e4b-11eb-98e1-1f155a3ed577.png)

**Comment by EricJi001** [comment]
遇到同样问题，怎么解决的？  谢谢

**Comment by xiao9616** [comment]
@xinxiwang 你好请问你怎么解决这个问题的，这好像是arm的加速

**Comment by ufogxl** [comment]
只能真机运行

**Comment by geekplusaa** [comment]
/home/geekplusa/ai/projects/github/paddle/PaddleOCR/deploy/android_demo_deploy/app/src/main/cpp/preprocess.cpp:48:3: error: unknown type name 'float32x4_t'

**Comment by WilliamQf-AI** [comment]
请问怎样解决的，我这边也遇到
