### ISSUE TITLE
ch_rec_r34_vd_crnn_enhance_infer模型推理速度问题

### ISSUE THREAD

**Issue by Maxhyl** [PaddlePaddle/PaddleOCR#1233]
您好，我使用的是CPU，在windows环境下，文字多的图片需要30多s如第一张图，小一点的需要10s如第二张图，我是同时推理了3张图片的，请问需要怎么优化
![table4](https://user-images.githubusercontent.com/49184062/100056941-7552d400-2e61-11eb-8083-e7f5c523a225.jpg)
![table5](https://user-images.githubusercontent.com/49184062/100056970-84d21d00-2e61-11eb-8e50-b9048c0210b2.jpg)

**Comment by Maxhyl** [comment]
![image](https://user-images.githubusercontent.com/49184062/100057548-a384e380-2e62-11eb-9ea7-c92462cce5b0.png)

**Comment by LDOUBLEV** [comment]
看上去检测运行速度还是蛮快的，主要在识别上；
你用的是python端预测是吧，用的predict_system.py，可以在预测的时候开启mkldnn，https://github.com/PaddlePaddle/PaddleOCR/blob/ae6403d55b4063e0dc45a86a1e58526e7433828a/tools/infer/utility.py#L85

也可以调整一下rec_batch_num的大小

**Comment by LDOUBLEV** [comment]
你用的是哪个模型，或者试一试mobile的模型呢，mobile的模型比较小

**Comment by Maxhyl** [comment]
> 你用的是哪个模型，或者试一试mobile的模型呢，mobile的模型比较小
感谢您的回复，rec_batch_num已经设置得很小了， 把mkldnn改为True之后速度确实快了，但是还是需要十多s，使用的就是标题中的那个infer模型

**Comment by Maxhyl** [comment]
> 你用的是哪个模型，或者试一试mobile的模型呢，mobile的模型比较小
使用的模型是这个：chinese_db_crnn_server | 通用中文OCR模型

**Comment by kouhou** [comment]
<img width="1440" alt="截屏2020-11-25 11 31 26" src="https://user-images.githubusercontent.com/4274831/100181738-f075c200-2f15-11eb-9f45-6250b0c71024.png">

我这个开启--enable_mkldnn=True 报错，paddle2.0的版本没支持mkldnn=OFF。
我是Mac os 通过pip安装的，怎么安装支持mkldnn的版本。

**Comment by LDOUBLEV** [comment]
> > 你用的是哪个模型，或者试一试mobile的模型呢，mobile的模型比较小
> > 使用的模型是这个：chinese_db_crnn_server | 通用中文OCR模型

server的识别模型在CPU上计算速度很慢，可以用下面这个轻量识别模型，虽然模型小了很多，但是精度并没有降低太多
![image](https://user-images.githubusercontent.com/26592129/100188581-74837600-2f25-11eb-8685-6cb5568b841d.png)

rec_batch_num不是设置越小越好，估计稍微大一点速度可能会快一些；

**Comment by LDOUBLEV** [comment]
> <img alt="截屏2020-11-25 11 31 26" width="1440" src="https://user-images.githubusercontent.com/4274831/100181738-f075c200-2f15-11eb-9f45-6250b0c71024.png">
> 
> 我这个开启--enable_mkldnn=True 报错，paddle2.0的版本没支持mkldnn=OFF。
> 我是Mac os 通过pip安装的，怎么安装支持mkldnn的版本。

MAC上是另一套CPU，不支持开启MKLDNN

**Comment by Maxhyl** [comment]
> > > 你用的是哪个模型，或者试一试mobile的模型呢，mobile的模型比较小
> > > 使用的模型是这个：chinese_db_crnn_server | 通用中文OCR模型
> 
> server的识别模型在CPU上计算速度很慢，可以用下面这个轻量识别模型，虽然模型小了很多，但是精度并没有降低太多
> ![image](https://user-images.githubusercontent.com/26592129/100188581-74837600-2f25-11eb-8685-6cb5568b841d.png)
> 
> rec_batch_num不是设置越小越好，估计稍微大一点速度可能会快一些；

好的，谢谢

**Comment by peterpanhjh** [comment]
GPU会比CPU一般快多少呢

**Comment by skyfaker** [comment]
> GPU会比CPU一般快多少呢

以我的笔记本i7 7700HQ和GTX1060为例，
根据图片的不同，CPU时间在1s-2s，GPU在70ms-200ms。
基本上一张图GPU会比CPU快12倍左右。
