### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by koujunxia** [PaddlePaddle/PaddleOCR#1238]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1606208562 (unix time) try "date -d @1606208562" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 6946 (TID 0x7fb0f7fef700) from PID 0 ***]

**Comment by LDOUBLEV** [comment]
运行哪段代码或者是执行哪条指令出现的这个错误呢？提供下报错环境

**Comment by hudielv** [comment]
使用多进程时运行ocr预测那个api时，进程数很多时，就会报错上述错误
![image](https://user-images.githubusercontent.com/48787551/100532426-3db7a380-3236-11eb-9f4a-4d5adcb7fe16.png)

**Comment by james5551** [comment]
你好，我也是这种错误，请问Centos8系统现在支持吗？

**Comment by ka2007** [comment]
你好，同样的错误

**Comment by Jitesh4389** [comment]
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 
OMP: Info #250: KMP_AFFINITY: pid 3890037 tid 3890227 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 3890037 tid 3890493 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 3890037 tid 3890494 thread 2 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 3890037 tid 3890495 thread 3 bound to OS proc set 3


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1607943285 (unix time) try "date -d @1607943285" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3890037 (TID 0x7f75129cf700) from PID 0 ***]

**Comment by Jitesh4389** [comment]
1222 05:35:41.893994 1400487 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 
OMP: Info #250: KMP_AFFINITY: pid 1400328 tid 1400487 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 1400328 tid 1400752 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 1400328 tid 1400754 thread 3 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 1400328 tid 1400753 thread 2 bound to OS proc set 2
*************************************************************************************************************************************************
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1608615342 (unix time) try "date -d @1608615342" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1400328 (TID 0x7f038c21b700) from PID 0 ***]

**Comment by SanchiMittal** [comment]
Hello. Any updates on this? I am facing the same issue.

**Comment by hudielv** [comment]
还没解决，只是在控制利用cpu利率时，才会避免这种错误，但是不排除之后可能还会引发这种错误

**Comment by SanchiMittal** [comment]
Just updating that I am not getting this error anymore by using the docker image given in [quick installation](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/installation_en.md) and latest version of paddle(2.0c1) by directly cloning it.

This docker image, by default uses python 3.5, just remember to set it to python 3.7 by running this inside the dockeer container bash shell:

``` update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python3.7 2 ```

**Comment by Jitesh4389** [comment]
Hi
Sanchi right update this version of python 3.5 to 3.7

**Comment by hudielv** [comment]
> 你好，我也是这种错误，请问Centos8系统现在支持吗？

是的

**Comment by hhhhhhogan** [comment]
你好，请问这个怎么解决呢？ 我也遇到这个问题

**Comment by blackeyecircles** [comment]
同样问题，ubuntu 16.04, python3.7, paddle 2.1.0, paddleocr 2.0.6

**Comment by hudielv** [comment]
用paddle最新稳定版本应该就不会出现这个问题了
你什么时候出现这个问题？可以复现么？可以描述下什么情况会出现这个问题

**Comment by blackeyecircles** [comment]
环境是ubuntu16.04, 使用的conda安装python3.7
pip install paddleocr>=2.0.1    # 实际安装的 paddleocr 2.0.6
pip install paddlepaddle-gpu   # 实际安装的 paddle 2.1.0

执行的这段代码
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang="ch")

提示报错：
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/lq/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/lq/.paddleocr/2.1/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/lq/.paddleocr/2.1/det/ch', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/home/lq/.paddleocr/2.1/rec/ch', use_angle_cls=True, use_dilation=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar to /home/lq/.paddleocr/2.1/rec/ch/ch_ppocr_mobile_v2.0_rec_infer.tar
100%|███████████████████████████████████████████████████████████████| 3.90M/3.90M [00:01<00:00, 2.85MiB/s]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621589534 (unix time) try "date -d @1621589534" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 8079 (TID 0x7f9822a13700) from PID 0 ***]

段错误

**Comment by blackeyecircles** [comment]
> 用paddle最新稳定版本应该就不会出现这个问题了
> 你什么时候出现这个问题？可以复现么？可以描述下什么情况会出现这个问题

环境是ubuntu16.04, 使用的conda安装python3.7
pip install paddleocr>=2.0.1 # 实际安装的 paddleocr 2.0.6
pip install paddlepaddle-gpu # 实际安装的 paddle 2.1.0

执行的这段代码
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang="ch")

提示报错：
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/lq/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/lq/.paddleocr/2.1/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/lq/.paddleocr/2.1/det/ch', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/home/lq/.paddleocr/2.1/rec/ch', use_angle_cls=True, use_dilation=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar to /home/lq/.paddleocr/2.1/rec/ch/ch_ppocr_mobile_v2.0_rec_infer.tar
100%|███████████████████████████████████████████████████████████████| 3.90M/3.90M [00:01<00:00, 2.85MiB/s]
C++ Traceback (most recent call last):
0 paddle::framework::SignalHandle(char const*, int)
1 paddle::platform::GetCurrentTraceBackStringabi:cxx11

Error Message Summary:
FatalError: Segmentation fault is detected by the operating system.
[TimeInfo: *** Aborted at 1621589534 (unix time) try "date -d @1621589534" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 8079 (TID 0x7f9822a13700) from PID 0 ***]

段错误

**Comment by littletomatodonkey** [comment]
1. python运行`paddle.utils.run_check()`，查看是否安装正确
2. 将`use_gpu`参数修改为false，看下是否还会报错

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by yayaQAQ** [comment]
我也遇到了这个问题，但是我没有使用paddleOCR，我的项目里面和paddle相关的应该是lac，甚至定位不到哪里出错了。

**Comment by Evezerest** [comment]
应该是paddle框架问题，可以尝试安装最新版的paddle。如果还是有问题可以去paddle repo的issue下提问

> 我也遇到了这个问题，但是我没有使用paddleOCR，我的项目里面和paddle相关的应该是lac，甚至定位不到哪里出错了。
