### ISSUE TITLE
在使用PaddleServeing时 出错 

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PaddleOCR#1239]
在本地使用这个命令 python -m pip install -U https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.0.0-cp35-none-any.whl https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.0-py3-none-any.whl   会有如下报错
![QQ截图20201124230635](https://user-images.githubusercontent.com/61350752/100112069-ca1a3d00-2ea9-11eb-9e11-4d5146d4e14f.png)

**Comment by minhoooo1** [comment]
![AA](https://user-images.githubusercontent.com/61350752/100113165-ff735a80-2eaa-11eb-8138-5637018a22ae.png) 在按照APP的whl文件时才会报错

**Comment by WenmuZhou** [comment]
这是shapely安装错误哈，看这里https://github.com/PaddlePaddle/PaddleOCR/issues/986

**Comment by minhoooo1** [comment]
装好了呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhoujun"<notifications@github.com&gt;; 
发送时间: 2020年11月25日(星期三) 中午12:35
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;; 
抄送: "Derrick。"<1121851272@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 在使用PaddleServeing时 出错  (#1239)





 
这是shapely安装错误哈，看这里#986

**Comment by minhoooo1** [comment]
> 这是shapely安装错误哈，看这里#986
重新下载1.7.1版本的shapely的whl文件再安装并未解决问题，而且在执行这段命令pip install paddle_serving_app-0.0.0-py3-none-any.whl时报错是因为下载1.6.1的shapely而报错。尝试直接下载shapely1.6.1遭遇与上段命令同样报错

**Comment by littletomatodonkey** [comment]
看下`import shapely`能否正确导入吧，

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by minhoooo1** [comment]
收到！抱歉忘记关闭了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 上午9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 在使用PaddleServeing时 出错  (#1239)





 
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
 该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
