### ISSUE TITLE
预测异常

### ISSUE THREAD

**Issue by xazeng** [PaddlePaddle/PaddleOCR#1240]
环境：cuda10, rtx2060super, win10 64x，paddle2.0rc

预测程序多数时候正常
有的时候卡在 predictor->ZeroCopyRun() 里面
有的时候出下图问题
![image](https://user-images.githubusercontent.com/3202516/100124618-d35dd680-2eb6-11eb-830a-20c07670e70e.png)

有大神可以请教下吗？

**Comment by LDOUBLEV** [comment]
预测时，出现报错的这个图，一定会出现这个报错吗，还是说这个报错是随机的

**Comment by xazeng** [comment]
目前只看到这个报错

**Comment by xazeng** [comment]
> 预测时，出现报错的这个图，一定会出现这个报错吗，还是说这个报错是随机的

只要出错，目前只出现这个报错。

**Comment by xazeng** [comment]
> 预测时，出现报错的这个图，一定会出现这个报错吗，还是说这个报错是随机的

出现卡在 ZeroCopyRun 时的显卡截图，cuda突然占满掉
![image](https://user-images.githubusercontent.com/3202516/100258243-cbb73400-2f81-11eb-8c26-febe15336e79.png)

**Comment by LDOUBLEV** [comment]
你的PaddleOCR代码不是最新的吧，最新的没有用zero_copy_run：
https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/tools/infer/predict_rec.py#L234
https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/tools/infer/utility.py#L86

**Comment by xazeng** [comment]
> 你的PaddleOCR代码不是最新的吧，最新的没有用zero_copy_run：
> https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/tools/infer/predict_rec.py#L234
> 
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/tools/infer/utility.py#L86

c++的代码，加了batch，目前测试只有 1050ti 还算正常，2060s 和 1660s 基本都跟上面的情况一样。事实上，infer 的库在 win10 环境是编译不过的，不然我还可以自己试着查一查。
cuda10.0 vs2015，环境跟官网一致，出下面这个错误
![G%~7 IK~Y)9ND_KP5Z5F0YJ](https://user-images.githubusercontent.com/3202516/100401807-884dea00-3095-11eb-86ed-a920a8442c7b.png)

**Comment by littletomatodonkey** [comment]
你好，要不试下最新的预测库呢？windows上在2.1这块又做了一些优化

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
