### ISSUE TITLE
每次迭代时都会出现的错误

### ISSUE THREAD

**Issue by FibonacciZ** [PaddlePaddle/PaddleOCR#1241]
![BD8F66B3FDA1236889425378D2CA3A2E](https://user-images.githubusercontent.com/27908488/100169187-cf08dc00-2efd-11eb-8879-7cf4cd24aaf0.jpg)

The number of the whole data (912) is smaller than the batch_size * devices_num * num_workers (1024)
每次迭代60+epoch就会出现这个错误，请问该如何避免。

**Comment by LDOUBLEV** [comment]
尝试把batch_size 调小一点，num_workers小一点

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
