### ISSUE TITLE
使用哪个下载链接作为文本检测的预训练模型

### ISSUE THREAD

**Issue by astro-zihao** [PaddlePaddle/PaddleOCR#1243]
你好，我想使用百度提供的已经在中文数据集上预训练好的文本检测模型训练自己的文本检测数据集。

目前找到三个地方有预训练模型的下载链接，但不知道使用哪一个？

1. 模型训练/评估-文本检测中出现的https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md

> https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar

2. 算法介绍-文本检测中出现的https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/algorithm_overview.md

> https://paddleocr.bj.bcebos.com/det_r50_vd_db.tar

3.OCR模型列表（V1.1，9月22日更新）中出现的

> https://paddleocr.bj.bcebos.com/20-09-22/server/det/ch_ppocr_server_v1.1_det_train.tar

**Comment by kouhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md

感觉应该用总最新的

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
