### ISSUE TITLE
ch_PP-OCRv4_rec_svtr_large.yml训练导出的模型，使用predict_rec.py预测宽度比较大的图片时出现(InvalidArgument) Broadcast dimension mismatch

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleOCR#12440]
使用ch_PP-OCRv4_rec_svtr_large.yml训练的OCR识别模型，训练正常，
使用python tools/eval.py -c configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_svtr_large.yml也是正常的，
用python tools/export_model.py -c configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_svtr_large.yml 也是能成功导出模型的
用export_model.py导出的模型，使用python tools/infer/predict_rec.py预测宽度不太长的单行图片也是能正常预测的，
但是predict_rec.py预测宽度比较大的图片时出现：(InvalidArgument) Broadcast dimension mismatch错误
即使是训练、验证用的宽度比较大的图片也是出现这个错误，这个怎么解决？
训练配置：image_shape: [3, 48, 320]， max_text_length: &max_text_length 50

`[2024/05/25 14:48:36] ppocr INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 728, in main
    rec_res, _ = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 675, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 2148, 192] and the shape of Y = [1, 960, 192]. Received [2148] in X is not equal to [960] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_add > error]

[2024/05/25 14:48:36] ppocr INFO: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 2148, 192] and the shape of Y = [1, 960, 192]. Received [2148] in X is not equal to [960] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_add > error]`

**Comment by LMR2018** [comment]
![0](https://github.com/PaddlePaddle/PaddleOCR/assets/37955893/9e4daa93-a55c-4fa2-811c-0d840faeca78)
![Dingtalk_20240525170529](https://github.com/PaddlePaddle/PaddleOCR/assets/37955893/a28ff6b3-2bca-4d56-a9f7-a7d80c0aa824)

**Comment by GreatV** [comment]
直接resize 成 [3, 48, 320] 可以infer吗

**Comment by LMR2018** [comment]
> 直接resize 成 [3, 48, 320] 可以infer吗

一开始就进行直接resize成（320， 48），不行，后面官方又做了别的处理了，最后图片不是（320，48，3）
![Dingtalk_20240525174942](https://github.com/PaddlePaddle/PaddleOCR/assets/37955893/76828020-afcd-4b73-8a2d-bd2e573ba504)

![Dingtalk_20240525175020](https://github.com/PaddlePaddle/PaddleOCR/assets/37955893/48cdbb94-b370-4497-9e01-e1d6d732acb1)

**Comment by LMR2018** [comment]
还发现一个问题，上面280*32、904*118的原始图片出错，但是用过585*87，579*102，583*271，359*190的却能正常，所以在猜想不是宽度太长的问题，用ch_PP-OCRv4_rec.yml配置训练的模型就没有这个问题

**Comment by nissansz** [comment]
> ch_PP-OCRv4_rec.yml

ch_PP-OCRv4_rec.yml 这个配置我怎么训练不了，batch size = 1都爆显存。
ch_PP-OCRv4_rec.yml 这个配置没问题，可以训练

**Comment by GreatV** [comment]
感觉得检查一下 `ch_PP-OCRv4_rec_svtr_large.yml` 里的参数跟 `tools/infer/predict_rec.py` 里的是不是一致的。

**Comment by nissansz** [comment]
paddleocr 2.8 有改善这些吗？有没有更新配置文件？

**Comment by GreatV** [comment]
@nissansz 你看一下readme 就知道了。

**Comment by nissansz** [comment]
SVTRv2(Rec Sever) | configs/rec/SVTRv2/rec_svtrv2_ch.yml | A榜 68.81% (使用PP-OCRv4检测模型)

看到一个这个新配置
