### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#1245]
paddlehub==1.8.3
paddlepaddle==1.8.5
Shapely==1.7.1
pyclipper==1.2.0
numpy==1.19.1
![0](https://user-images.githubusercontent.com/14155359/100200305-5889cf80-2f39-11eb-98e2-f6799d867898.png)

**Comment by MissPenguin** [comment]
发一下具体操作流程吧，另外，直接运行module.py能正常识别吗

**Comment by bikerr** [comment]
> 发一下具体操作流程吧，另外，直接运行module.py能正常识别吗

直接运行module.py 是可以运行的，第一次安装的时候也可以，之后不知道什么情况突然不行了， 目前 hub serving start -m chinese_ocr_db_crnn 也是会报同样的错误，不知道是否是因为本地安装的包冲突或者是版本问题？

**Comment by bikerr** [comment]
所有依赖更新了一遍已经可以使用
