### ISSUE TITLE
识别模型训练速度慢

### ISSUE THREAD

**Issue by 20zhDong** [PaddlePaddle/PaddleOCR#1247]
>
![微信图片_20201125170347](https://user-images.githubusercontent.com/73943824/100205655-5d9e4d00-2f40-11eb-9653-6e3569b7f518.jpg)
![微信图片_20201125170351](https://user-images.githubusercontent.com/73943824/100205665-6131d400-2f40-11eb-85f7-a5b88c9b505a.jpg)

检测模型训练速度正常但识别模型训练速度慢且无法收敛，请问下可能的问题是出在哪里，该如何解决？

**Comment by LDOUBLEV** [comment]
识别模型loss本身就很大，看你的loss是收敛的，只不过每个迭代耗费的时间不正常，是不是你的CPU被占用着，导致数据读取很慢

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
