### ISSUE TITLE
need model for indian language i.e Hindi

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#1250]
frist of all thank you for this lib  ....team i am looking for the indian model for OCR study will you provided or can you tell me step for tarning model

**Comment by LDOUBLEV** [comment]
There is a [guideline](https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/README.md#guideline-for-new-language-requests) for other language requests.

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。

**Comment by MANISH007700** [comment]
Hello,
After installing and importing paddlepaddle-gpu and paddleocr==2.0.6
When I tried the quickstart method of creating an object using
ocr = PaddleOCR(lang="hi")
Error is : _ param lang must in dict_keys(['ch', 'en', 'french', 'german', 'korean', 'japan']), but got hi_

My Task is in Hindi, so is there any workaround for this.
I used "en", it worked but ans were not proper.
I need to use "hindi"

Any Help will be appreciated
Thanks PaddleTeam and Contributors

**Comment by omumarvaishya005** [comment]
Hello  Team ,
i have been using paddle for arabic lang. 
its quite good to see the multilingual features do we paddle-ocr system for hindi as well?
Any kind of help will be appreciated.
Thanks.
