### ISSUE TITLE
How to recognize the digital numbers in the rectangle box with paddleocr?

### ISSUE THREAD

**Issue by githubthunder** [PaddlePaddle/PaddleOCR#12518]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/12447

<div type='discussions-op-text'>

<sup>Originally posted by **githubthunder** May 25, 2024</sup>
PaddleOCR fails to recognize the digital numbers in the rectangle box. can anyone help to solve that?
<img width="551" alt="sample" src="https://github.com/PaddlePaddle/PaddleOCR/assets/30004341/01a58d72-74d9-439d-836b-2bb494f375fb">
</div>

**Comment by GreatV** [comment]
- lang=ch

![result](https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/2db2963f-b7cd-49bf-a131-f834694e22b4)

- lang=en

![result](https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/9e81b4d7-4368-4d98-b2f9-b53f4ef5e449)
