### ISSUE TITLE
paddle 与multiprocessing.Process多进程一起使用出现没有错误，不输出结果，有人知道怎么解决吗

### ISSUE THREAD

**Issue by jingenyan** [PaddlePaddle/PaddleOCR#1253]
谢谢谢谢

**Comment by LDOUBLEV** [comment]
不使用multiprocessing.Process 有问题吗？
你是要在哪个地方用多进程，预测的时候？

**Comment by jingenyan** [comment]
@LDOUBLEV不使用没有问题，如果放进程池pool里面就没有结果，说明在内部哪个地方错误了

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV不使用没有问题，如果放进程池pool里面就没有结果，说明在内部哪个地方错误了

你是多进程训练还是预测，训练已经用了多进程了

**Comment by jingenyan** [comment]
@LDOUBLEV 预测，在ocr检测的哪里是不是也使用了多进程，我测试在进入文本框预测的时候开始没有结果输出了

**Comment by LDOUBLEV** [comment]
预测没有设置多进程，只有cpu预测这里设置了线程数量：https://github.com/PaddlePaddle/PaddleOCR/blob/8477aa8ec30b4d713b64f49c27433f194b22a90b/tools/infer/utility.py#L129

你不使用多进程运行，看下后台有几个进程在占用

**Comment by stefan-567** [comment]
> 谢谢谢谢

有发现c盘temp爆仓吗？或者任务管理器中会启动很多进程
