### ISSUE TITLE
SAST训练报错

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1255]
![)F4B2`4~{XYX9{0NW4KMW46](https://user-images.githubusercontent.com/56471409/100301967-47da6780-2fd4-11eb-854d-27dd982ade0f.png)
![1Q{L1ZZ59BC 8(TSHBK9`G7](https://user-images.githubusercontent.com/56471409/100301972-4c068500-2fd4-11eb-953c-67ca098f6361.png)
![0(_QCH (55`( MA3$Z~VJ 5](https://user-images.githubusercontent.com/56471409/100301978-4dd04880-2fd4-11eb-8a36-646d8a2d8b55.png)
修改文本大小为[3, 1280, 1280]后  满足shape为32的整数倍 符合下采样操作后依然存在错误信息

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/100316935-694c4b00-2ff6-11eb-9a52-a9b4f6d5fdb1.png)
这里改了吗，只改reader里的shape会对不上，要一起改

**Comment by SealQ** [comment]
> ![image](https://user-images.githubusercontent.com/25809855/100316935-694c4b00-2ff6-11eb-9a52-a9b4f6d5fdb1.png)
> 这里改了吗，只改reader里的shape会对不上，要一起改
![)F4B2`4~{XYX9{0NW4KMW46](https://user-images.githubusercontent.com/56471409/100317328-1e7f0300-2ff7-11eb-9bb0-001966badb86.png)
修改了  但是依然会报错；

**Comment by SealQ** [comment]
![image](https://user-images.githubusercontent.com/56471409/100317609-9cdba500-2ff7-11eb-812f-df084660e8c6.png)
最后尝试修改了这里，不会报错了，但是出现了新的问题；
![image](https://user-images.githubusercontent.com/56471409/100317680-b8df4680-2ff7-11eb-801b-8a810be7fc33.png)
执行train命令后 train_batch_id一直为0
![image](https://user-images.githubusercontent.com/56471409/100317818-e926e500-2ff7-11eb-8dcb-87e6a62146ee.png)
这一步骤似乎出现异常

**Comment by MissPenguin** [comment]
我这边像你这么改后能跑起来了，没有报错，但是不建议这么改哈，512这个size是random crop后的尺寸，并不小了，调到1280太大了，并不合适，而且训练慢，另外，代码里可能有的地方参数按照512适配的，改成1280可能有隐藏风险。

**Comment by SealQ** [comment]
> 我这边像你这么改后能跑起来了，没有报错，但是不建议这么改哈，512这个size是random crop后的尺寸，并不小了，调到1280太大了，并不合适，而且训练慢，另外，代码里可能有的地方参数按照512适配的，改成1280可能有隐藏风险。

好的 感谢您，我尝试修正图片尺寸看是否可以跑通

**Comment by SealQ** [comment]
@MissPenguin 请问，SRN可以同时支持中英文混合训练么？ ，character_type应如何设置?

**Comment by tink2123** [comment]
@SealQ  可以混合训练，character_type设成ch，字典中同时包含中文和英文即可。
