### ISSUE TITLE
这里对character_str的判断是没有意义的

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#1257]
https://github.com/PaddlePaddle/PaddleOCR/blob/ce6bea9f365a91db3ddd73aef6a6dbf06646cd68/ppocr/utils/character.py#L38

这里是对框架进行了自我限制，没有实际意义。因为需要的模型地址`rec_model_dir`，和需要的`character_dict_path`，都可以通过参数设定，这里凭白无故设置了语种的种类，就限制了用户自己创建更多模型的路径了。

比如我要训练一个专门识别中国各个城市的模型，本想设置`character_type`为`cn_cities`，结果就失效了。虽然可以通过其他方式绕过，但代码可读性会下降。

建议把里面的代码移到下面的`else` 中，这里的`self.character_str = None`真是没有太多实际意义

**Comment by tink2123** [comment]
如果希望使用自定义字典的话，`character_type` 设为 `ch` 就可以，这个参数只控制字典语种。
`self.character_str = None` 确实可以优化一下，感谢反馈～

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
