### ISSUE TITLE
Github上的版本与Pypi发布的版本不一致

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#1258]
github上的release 1.1中，setup.py里写的版本是1.0.0，而现在Pypi里还有一个版本是1.0.1的，却是10月30日，合并了一个PR后改了，并发布到Pypi里的，但是github里却没有这次发布的Release信息，这个版本管理确实很混乱，让用户感觉不知所措

**Comment by LDOUBLEV** [comment]
pypi的版本号会领先于正式版

**Comment by mikeshi80** [comment]
github上的release明明是1.1了呀，但是pypi上还是1.0.1，而你们的release1.1的分支里，setup.py里的版本号是1.0.0，和你所说的好像也不一致

**Comment by WenmuZhou** [comment]
谢谢反馈，这种版本号的问题我们以后后注意的，谢谢指出我们工作的不足
