### ISSUE TITLE
单个文字漏捡

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#126]
测试了一下，有的单个文字会漏检，这个该怎么解决呢？是增加数据量还是用其他方法呢？

**Comment by LDOUBLEV** [comment]
请问你用的是哪一个模型？方便发一下测试图片吗？

**Comment by MissPenguin** [comment]
如果使用predict_system测试的，可以先把可视化阈值drop_score改小，确认是检测漏掉了还是识别置信度低于阈值被过滤掉了：https://github.com/PaddlePaddle/PaddleOCR/blob/2e127eac3a908a6968fdaf83e37cc80e6eb0170d/tools/infer/predict_system.py#L134

**Comment by wangning7149** [comment]
谢谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MissPenguin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午10:21
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王宁"<714970851@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 单个文字漏捡 (#126)





 
如果使用predict_system测试的，可以先把可视化阈值drop_score改小，确认是检测漏掉了还是识别置信度低于阈值被过滤掉了：https://github.com/PaddlePaddle/PaddleOCR/blob/2e127eac3a908a6968fdaf83e37cc80e6eb0170d/tools/infer/predict_system.py#L134

**Comment by wangning7149** [comment]
解决了，阈值问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Double_V"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午10:20
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王宁"<714970851@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 单个文字漏捡 (#126)





 
请问你用的是哪一个模型？方便发一下测试图片吗？

**Comment by wangning7149** [comment]
我又试了一下检测的模型，运行predict_det.py&nbsp; 模型为Resnet50_vd + db，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Double_V"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午10:20
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王宁"<714970851@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 单个文字漏捡 (#126)





 
请问你用的是哪一个模型？方便发一下测试图片吗？
