### ISSUE TITLE
识别模型中的推理模型是由哪个模型转换得到的？

### ISSUE THREAD

**Issue by kidling-g** [PaddlePaddle/PaddleOCR#1261]
![截屏2020-11-26 21 36 19](https://user-images.githubusercontent.com/62318458/100357344-84877c80-302f-11eb-8d80-4be60622d471.png)
请问在上图中的“推理模型”是由“预训练模型”转化得到的还是通过“训练模型”转化得到的？

**Comment by littletomatodonkey** [comment]
基于`训练模型`转化得到的

**Comment by frotms** [comment]
@littletomatodonkey 
我测试了ch_ppocr_server_v2.0_rec的“推理模型”和“预训练模型转化的推理模型”推理结果不一致(ch_ppocr_server_v2.0_det是一样的)。
ch_ppocr_server_v2.0_rec的“推理模型”和“预训练模型”的参数好像不一样？第一层的卷积后的结果就开始不一样了。
