### ISSUE TITLE
 Deprecated. Please use CreatePredictor instead.

### ISSUE THREAD

**Issue by kidling-g** [PaddlePaddle/PaddleOCR#1262]
环境：paddlepaddle-2.0.0rc0、macOS、python 3.8.2
使用CPU进行预测，模型使用的是通用模型，预测时出现图中的警告，请问这是什么情况
![截屏2020-11-26 22 25 25](https://user-images.githubusercontent.com/62318458/100362456-67a27780-3036-11eb-9675-d647322ee88b.png)

**Comment by littletomatodonkey** [comment]
这个目前可以不用管，该接口之后会做升级，我们也会做适配

**Comment by Deusxxxx** [comment]
我运行历程，报错之后就直接停止运行了，什么结果也没有输出
