### ISSUE TITLE
No module named 'paddle'

### ISSUE THREAD

**Issue by dinfer** [PaddlePaddle/PaddleOCR#1265]
```bash
docker run -d --name paddleocr ubuntu sleep infinity
docker exec -it paddleocr bash

# following commands is executed in docker
mkdir app && cd app
apt update && apt upgrade && apt install python3 python3-pip python3-venv libgl1 libglib2.0-0
python3 -m venv .
. bin/activate
pip install -U pip
pip install paddleocr
# copy codes form `https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md#1-use-by-code` to t.py
python t.py
# reports No module named 'requests', so install requests, and I do not know which version is correct.
pip install requests
python t.py
```

outputs

```
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "/app/lib/python3.8/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/app/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/app/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 21, in <module>
    import tools.infer.utility as utility
  File "/app/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "/app/lib/python3.8/site-packages/paddleocr/ppocr/utils/utility.py", line 19, in <module>
    from paddle import fluid
ModuleNotFoundError: No module named 'paddle'
```

same problem on python 3.7 and python3.8

same issue and no solution is provided.
#804

**Comment by littletomatodonkey** [comment]
paddle should be installed in py3.8 environment

**Comment by dinfer** [comment]
I have the same problem on 3.7 and 3.8. Both version are tested.
According installation document `https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/installation_en.md`, paddleocr works fine.

So, the module `paddle` should be installed manually?

**Comment by LDOUBLEV** [comment]
> I have the same problem on 3.7 and 3.8. Both versions are tested.
> 
> According installation document `https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/installation_en.md`, paddleocr works fine.
> 
> So, the module `paddle` should be installed manually?

yep, there is no 'paddle' in docker.

**Comment by dinfer** [comment]
please update document, It's confusing.
[whl_en](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md#install-package)

**Comment by WenmuZhou** [comment]
> Please update the document, It's confusing. or ad paddle module as a dependency of the paddleocr package.
> [whl_en](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md#install-package)

I will update docs

**Comment by WenmuZhou** [comment]
> > Please update the document, It's confusing. or ad paddle module as a dependency of the paddleocr package.
> > [whl_en](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md#install-package)
> 
> I will update docs
 fixed in 
https://github.com/PaddlePaddle/PaddleOCR/pull/1289

**Comment by dinfer** [comment]
Thanks, I'm closing this issue

**Comment by wmh02240** [comment]
pip install paddlepaddle

**Comment by sjtugzx** [comment]
Honestly, it is great the this repo updated frequently, howere, some essential docuemtns alswasy describes the old version which is reallly confusing. And I currently encounter the same problem. PLEASE update the documents!

**Comment by zouxiaoshi** [comment]
> > > Please update the document, It's confusing. or ad paddle module as a dependency of the paddleocr package.
> > > [whl_en](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md#install-package)
> > 
> > 
> > I will update docs
> > docs are updated in
> > #1289

plz update the [whl_cn](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/whl.md) as well.

**Comment by mikaelhg** [comment]
```
apt -qqy install xorg python3-pip
pip3 install paddlepaddle paddleocr
```

**Comment by arzakmiftakhul** [comment]
> ```
> apt -qqy install xorg python3-pip
> pip3 install paddlepaddle paddleocr
> ```

Works perfectly, thanks

**Comment by parandhamuduchakali** [comment]
its working fine 
!pip install paddlepaddle paddleocr, in windows

**Comment by Vania-Guima** [comment]
I have the same issue. My python version is 3.8.16. I already install the requeriments packages, paddlepaddle and paddleocr, but the error keeps popping up.

**Comment by Vania-Guima** [comment]
If I use the command line: python3 tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_PP-OCRv3_det_infer/" I get the error, but if I use: python tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_PP-OCRv3_det_infer/" everything works fine.
