### ISSUE TITLE
[F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():  [F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end(): 

### ISSUE THREAD

**Issue by abner2015** [PaddlePaddle/PaddleOCR#1266]
编译之后，复制到手机 ，adb 连接手机，在手机设备中执行命令：
**./ocr_db_crnn ch_ppocr_mobile_v1.1_det_prune_opt.nb  ch_ppocr_mobile_v1.1_rec_quant_opt.nb  ch_ppocr_mobile_cls_quant_opt.nb  ./11.jpg  ppocr_keys_v1.txt**

以下错误：
[I  5/ 1  6:44:50.457 ...oid/Paddle-Lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors name: HARDWARE	: QUALCOMM TECHNOLOGIES, INC SDA845
_SDM845_SDM845_
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1066 Setup] ARM multiprocessors number: 8
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 0, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 1, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 2, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 3, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 4, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 5, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 6, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 7, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1074 Setup] L1 DataCache size is: 
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1078 Setup] L2 Cache size is: 
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1082 Setup] L3 Cache size is: 
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
[I  5/ 1  6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1086 Setup] Total memory: 7848012KB
[W  5/ 1  6:44:50.459 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[W  5/ 1  6:44:50.474 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[W  5/ 1  6:44:50.488 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end(): 
[F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end(): 

Segmentation fault 

手机内存设备内存：
Filesystem       Size  Used Avail Use% Mounted on
/dev/root        2.8G  1.2G  1.6G  44% /
tmpfs            3.7G  692K  3.7G   1% /dev
/dev/block/sde16 976M  598M  378M  62% /vendor
tmpfs            3.7G     0  3.7G   0% /mnt
/dev/block/sde4  120M   43M   77M  36% /firmware
/dev/block/sde9   27M   20M  7.9M  72% /dsp
/dev/block/sda2   27M  1.3M   26M   6% /persist
/dev/block/sde5   64M  608K   63M   1% /bt_firmware
/dev/block/sda8   47G  866M   46G   2% /data
/data/media       47G  866M   46G   2% /mnt/runtime/default/emulated

请问如何解决

**Comment by abner2015** [comment]
还出现了这个问题

[F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end(): 
[F  5/ 1  6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end(): 

Segmentation fault

**Comment by LDOUBLEV** [comment]
用的是否是paddlelite 2.7 或者develop 分支编译的预测库？

**Comment by abner2015** [comment]
用的v2.7
git checkout release/v2.7
说明文档来自：
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme_en.md

**Comment by goldenduo** [comment]
一样的错误~  我是用paddleocr自带的android的demo，替换了模型跟paddlelite2.7

**Comment by gejianhui1** [comment]
> 编译之后，复制到手机 ，adb 连接手机，在手机设备中执行命令：
> **./ocr_db_crnn ch_ppocr_mobile_v1.1_det_prune_opt.nb ch_ppocr_mobile_v1.1_rec_quant_opt.nb ch_ppocr_mobile_cls_quant_opt.nb ./11.jpg ppocr_keys_v1.txt**
> 
> 以下错误：
> [I 5/ 1 6:44:50.457 ...oid/Paddle-Lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors name: HARDWARE : QUALCOMM TECHNOLOGIES, INC SDA845
> _SDM845_SDM845_
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1066 Setup] ARM multiprocessors number: 8
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 0, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 1, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 2, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 3, max freq: 1766, min freq: 1766, cluster ID: 1, CPU ARCH: A55
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 4, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 5, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 6, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 7, max freq: 2803, min freq: 2803, cluster ID: 0, CPU ARCH: A75
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1074 Setup] L1 DataCache size is:
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 64 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1078 Setup] L2 Cache size is:
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 128 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 256 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1082 Setup] L3 Cache size is:
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 2048 KB
> [I 5/ 1 6:44:50.458 ...oid/Paddle-Lite/lite/core/device_info.cc:1086 Setup] Total memory: 7848012KB
> [W 5/ 1 6:44:50.459 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
> version of opt:b92e8c4
> version of current Paddle-Lite:bd402b3
> [W 5/ 1 6:44:50.474 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
> version of opt:b92e8c4
> version of current Paddle-Lite:bd402b3
> [W 5/ 1 6:44:50.488 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
> version of opt:b92e8c4
> version of current Paddle-Lite:bd402b3
> [F 5/ 1 6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():
> [F 5/ 1 6:44:50.493 ...android/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():
> 
> Segmentation fault
> 
> 手机内存设备内存：
> Filesystem Size Used Avail Use% Mounted on
> /dev/root 2.8G 1.2G 1.6G 44% /
> tmpfs 3.7G 692K 3.7G 1% /dev
> /dev/block/sde16 976M 598M 378M 62% /vendor
> tmpfs 3.7G 0 3.7G 0% /mnt
> /dev/block/sde4 120M 43M 77M 36% /firmware
> /dev/block/sde9 27M 20M 7.9M 72% /dsp
> /dev/block/sda2 27M 1.3M 26M 6% /persist
> /dev/block/sde5 64M 608K 63M 1% /bt_firmware
> /dev/block/sda8 47G 866M 46G 2% /data
> /data/media 47G 866M 46G 2% /mnt/runtime/default/emulated
> 
> 请问如何解决

**Comment by abner2015** [comment]
问题没有解决，关了，暂时不用了
