### ISSUE TITLE
Android PP-OCRv3

### ISSUE THREAD

**Issue by Alexng2024** [PaddlePaddle/PaddleOCR#12662]
#### 问题描述 / Problem Description
我用 paddle-lite 转了 3 个 .nb 档  想转用 pp-OCRv3  load model 可以  但一执行辨识时就会死机  想请问是否未能支援   我想在 Android 上跑

#### 运行环境 / Runtime Environment
- OS:
- Paddle:
- PaddleOCR:

**Comment by xiaoshanlin000** [comment]
下载和paddle lite 库一致的opt工具, 然后使用opt工具优化推理模型, 生成.nb文件.    这是我用的参数  --optimize_out_type=naive_buffer   --valid_targets=arm -quant_type=QUANT_INT8

**Comment by Alexng2024** [comment]
import paddlelite.lite as lite

a=lite.Opt()
a.set_model_dir("D:\\ALEX_LLM\\OCR_LLM\\ch_ppocr_mobile_v2.0_cls_infer\\")

# conmbined 形式，具体模型和参数名称，请根据实际修改
a.set_model_file("D:\\inference.pdmodel")
a.set_param_file("D:\\inference.pdiparams")


a.set_valid_places("arm")
a.set_model_type("naive_buffer")

a.set_optimize_out("ch_PP-OCRv3_cls_out")
#a.set_valid_places("x86")

a.run()

我这样用 python 产生的  可 load model  就是辨识时  死app
