### ISSUE TITLE
jetson nano 编译paddleOCR时报错：No rule to make target '/usr/lib/aarch64-linux-gnu/libgtk-3.so'

### ISSUE THREAD

**Issue by LittleSheepy** [PaddlePaddle/PaddleOCR#1268]
![微信图片_20201127134436](https://user-images.githubusercontent.com/38182200/100415351-e8a15380-30b6-11eb-8fac-81a70daea74c.png)
![微信图片_20201127134511](https://user-images.githubusercontent.com/38182200/100415355-e9d28080-30b6-11eb-9356-39fca9a40d42.png)
-- Build files have been written to: /home/lcl/codes/PaddleOCR-develop/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
make[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libgtk-3.so', needed by 'ocr_system'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

编译的时候缺少libgtk-3.so，我看了下有libgtk-3.so.0这个软连接

**Comment by LDOUBLEV** [comment]
将libgtk-3.so.0 替换为libgtk-3.so  就没问题了

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
