### ISSUE TITLE
SRN训练中Loss值

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1269]
![image](https://user-images.githubusercontent.com/56471409/100426198-7424df80-30cb-11eb-8f8b-f73e2b799f8e.png)
loss值突然骤降，然后acc骤升，这个会是什么问题？

**Comment by LDOUBLEV** [comment]
这个不是问题吧，可能刚好学到了东西

**Comment by SealQ** [comment]
@LDOUBLEV SRN网络训练中是否使用了在线数据增强的操作？

**Comment by littletomatodonkey** [comment]
你好，标准的srn中，没有使用在线数据增强，所有的预处理可以在这里查看

https://github.com/PaddlePaddle/PaddleOCR/blob/aea8c08ac856c16e5a5ee5da82dc26991ec52381/configs/rec/rec_r50_fpn_srn.yml#L63

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
