### ISSUE TITLE
关于SRN推理模型问题

### ISSUE THREAD

**Issue by strWuYaoJu** [PaddlePaddle/PaddleOCR#1271]
使用SRN训练自己的数据得到对应的预训练模型，使用预训练模型进行测试，得到的结果都是正确的，但是经过导出得到的推理模型，进行测试就报错。
rec_r50fpn_vd_none_srn.yml文件内容：
  algorithm: SRN
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: output/rec_srn
  save_epoch_step: 200
  eval_batch_step: 2000
  train_batch_size_per_card: 8
  test_batch_size_per_card: 1
  image_shape: [1, 64, 224]
  max_text_length: 25
  character_type: ch
  character_dict_path: ./ppocr/utils/word_dict.txt
  loss_type: srn
  num_heads: 8
  average_window: 0.15
  max_average_window: 15625
  min_average_window: 10000
  use_space_char: false
  ................

执行：
python3 tools/export_model.py -c configs/rec/rec_r50fpn_vd_none_srn.yml -o Global.checkpoints=./output/rec_srn/best_accuracy Global.save_inference_dir=./inference/rec_srn_inference
得到推理模型；

执行：
python tools/infer/predict_rec.py  --rec_model_dir="./inference/rec_srn_inference/" --use_space_char=False --use_gpu=True --image_dir="./train_data/rec/test/"
报错：
----------------------
Error Message Summary:
----------------------
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:140)

2020-11-28 01:07:13,689-INFO: ERROR!!!! 
Please read the FAQ: https://github.com/PaddlePaddle/PaddleOCR#faq 
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'

接着把图片大小，字符类型参数加上，执行：
python tools/infer/predict_rec.py  --rec_model_dir="./inference/rec_srn_inference/" --use_space_char=False --use_gpu=True --image_dir="./train_data/rec/test/" --rec_image_shape="1,64,224" --rec_char_type="ch"
还是报错：
2020-11-28 01:11:34,682-INFO: ERROR!!!! 
Please read the FAQ: https://github.com/PaddlePaddle/PaddleOCR#faq 
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'

**Comment by LDOUBLEV** [comment]
报错信息有提示，Please set --rec_image_shape='3,32,100' and --rec_char_type='en'

试试
python tools/infer/predict_rec.py --rec_model_dir="./inference/rec_srn_inference/" --use_space_char=False --use_gpu=True --image_dir="./train_data/rec/test/"  --rec_image_shape='3,32,100' and --rec_char_type='en'

**Comment by strWuYaoJu** [comment]
@LDOUBLEV 还是报：
----------------------
Error Message Summary:
----------------------
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:140)

2020-11-30 13:05:18,612-INFO: ERROR!!!! 
Please read the FAQ: https://github.com/PaddlePaddle/PaddleOCR#faq 
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'

**Comment by tink2123** [comment]
看报错 `Error: Tensor not initialized yet when Tensor::type() is called.` 请问您是否修改了代码呢？

**Comment by strWuYaoJu** [comment]
@tink2123 没有改哦！这个指令必须加上--rec_image_shape=“x,x,x,” --rec_char_type="ch"  --rec_algorithm="SRN"才能执行，即：
python3 tools/infer/predict_rec.py --image_dir="./train_data/rec/test/img_0692.bmp" \
                                   --rec_model_dir="./inference/rec_srn_inference/" \
                                   --rec_image_shape="1, 64, 224" \
                                   --rec_char_type="ch" \
                                   --rec_algorithm="SRN"

但是执行的结果都是不对的，结果如下：
Predicts of ./train_data/rec/test/img_0692.bmp:['娇题-其0陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂陂', 0.99996775]
Total predict time for 1 images:2.010
跟预训练模型的结果完全不对

**Comment by strWuYaoJu** [comment]
@tink2123 找到问题了，我用的是自定义字典，所以还得加上一个--rec_char_dict_path参数指定字典，就好了
