### ISSUE TITLE
训练后的检测模型有一半的图片检测不到文字

### ISSUE THREAD

**Issue by astro-zihao** [PaddlePaddle/PaddleOCR#1273]
您好。我标注了1000张图片用于训练检测模型，图片的宽高比w:h约等于8, 是细长型的图片。没有改配置文件，直接训练模型。训练了500个epoch后，在100张图片上测试，发现只有约50%的图片有检测框，剩余的都没有检测到。如果将postprocess.box_thresh=0.0, 也只有70%的可以检测到，请问这是什么原因，需要更改哪些参数？

**Comment by LDOUBLEV** [comment]
训练时，会把图像reshape到640，640，可以修改配置文件参数的训练数据shape为适合你数据的形式：https://github.com/PaddlePaddle/PaddleOCR/blob/401506396ecb42bad502b4f55fa4339a02afdc3a/configs/det/det_mv3_db_v1.1.yml#L13

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
