### ISSUE TITLE
paddle2onnx现已不支持--input_shape_dict="{'x':[-1,3,x,x}"参数使用

### ISSUE THREAD

**Issue by Mrxuba** [PaddlePaddle/PaddleOCR#12743]
#### 问题描述 / Problem Description

paddle2onnx现已不支持--input_shape_dict="{'x':[-1,3,x,x}"参数使用；

#### 可能的原因

```cmd
2024-06-05 17:05:41 [WARNING]   [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle 
```

旧版本提示如上，使用**PaddleUtils**需要**paddlepaddle<=2.5.0**

新版本paddlepaddle没有fluid module了：
```cmd
ModuleNotFoundError: No module named 'paddle.fluid' 
```

#### 可能解决方案 / Possible solutions

使用了如下脚本命令来修改onnx shape
onnx shape测试可以进行正常修改

```shell
#!/bin/bash

python /home/x09934/code/PaddleOCR/PaddleUtils/paddle/paddle_infer_shape.py --model_dir /home/x09934/code/PaddleOCR/inference/en_PP-OCRv4_rec_infer/ \
                             --model_filename inference.pdmodel \
                             --params_filename inference.pdiparams \
                             --save_dir /home/x09934/code/PaddleOCR/inference/en_PP-OCRv4_rec_infer \
                             --input_shape_dict="{'x':[1,3,32,320]}"

paddle2onnx --model_dir /home/x09934/code/PaddleOCR/inference/en_PP-OCRv4_rec_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file /home/x09934/code/PaddleOCR/inference/en_PP-OCRv4_rec_infer/model.onnx \
--opset_version 10 \
--enable_onnx_checker True
# --input_shape_dict="{'x':[-1,3,-1,-1]}" \
```

**Comment by GreatV** [comment]
@Mrxuba 你好，你是否愿意提一个PR来修改对应文档的相关描述。

**Comment by Mrxuba** [comment]
感谢您的回复，我将会在明日的工作时间提供


Votre&nbsp;petit&nbsp;ami
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月5日(星期三) 晚上8:05
***@***.***&gt;;
抄送:&nbsp;"Votre petit ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] paddle2onnx现已不支持--input_shape_dict="{'x':[-1,3,x,x}"参数使用 (Issue #12743)





 
@Mrxuba 你好，你是否愿意提一个PR来修改对应文档的相关描述。

**Comment by Mrxuba** [comment]
@GreatV 您好，我已经提交了一个PR，并修改了对应文档的相关描述

**Comment by SWHL** [comment]
已经在PR #12749 中解决
