### ISSUE TITLE
运行PaddleOCR示例代码报错 TypeError: TextSystem.call() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by confuse05** [PaddlePaddle/PaddleOCR#12756]
#### 问题描述 / Problem Description
依据PaddleOCR 快速开始测试，使用pip install安装了paddleocr                 2.7.5 

执行python脚本使用的第一个例子，对图片进行ocr，执行到result = ocr.ocr(img_path, cls=True)时会报错
  File "/opt/anaconda3/envs/car-knowledge/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 729, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextSystem.__call__() takes from 2 to 3 positional arguments but 4 were given

#### 运行环境 / Runtime Environment
- OS:macOs
- Paddle:2.6.1 
- PaddleOCR:2.7.5

#### 复现代码 / Reproduction Code
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

#### 完整报错 / Complete Error Message
执行时报错如下：
Traceback (most recent call last):
    result = ocr.ocr(img_path, cls=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/car-knowledge/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 729, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextSystem.__call__() takes from 2 to 3 positional arguments but 4 were given

**Comment by GreatV** [comment]
试试2.7.3
或者最新版 `pip install git+https://github.com/PaddlePaddle/PaddleOCR.git`

**Comment by GreatV** [comment]
2.7.5被yanked

**Comment by SWHL** [comment]
issue先关闭了，后续有问题再开
