### ISSUE TITLE
训练数据的长宽比过大怎么修改shape

### ISSUE THREAD

**Issue by astro-zihao** [PaddlePaddle/PaddleOCR#1275]
请问怎么根据自己的数据集中的图片大小修改size，怎么reshape，文档里并没有看到，需要修改哪些参数？

**Comment by WenmuZhou** [comment]
识别 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml#L12

检测  https://github.com/PaddlePaddle/PaddleOCR/blob/develop/configs/det/det_mv3_db.yml#L13

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
