### ISSUE TITLE
文字检测时怎么做翻转、模糊等数据增强呢？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#1276]
大佬，在文字识别部分看到了可以做数据增强操作，请问在做文字检测时支持做数据增强吗?

**Comment by WenmuZhou** [comment]
可以啊，现在db已经做了旋转，模糊你加到这里就行https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py#L145

**Comment by Lie-huo** [comment]
> 可以啊，现在db已经做了旋转，模糊你加到这里就行https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py#L145

翻转好像没有实现吧，我训练出来的检测模型，对于正面的图片检测效果很好，但是对于完全倒立的图片效果很差，请问这样的怎么解决呢？

**Comment by WenmuZhou** [comment]
我们目前没有加这方面的增强， 需要自己加一下

**Comment by Lie-huo** [comment]
> 我们目前的旋转角度不大，-10到10之间，你这样需要改一下
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/401506396ecb42bad502b4f55fa4339a02afdc3a/ppocr/data/det/data_augment.py#L22
> 
> ，把这里的-10,10改大
可以改成-180，180吗，还是只能在-90，90之间？

**Comment by WenmuZhou** [comment]
可以-180到180
