### ISSUE TITLE
关于通用识别模型使用的训练集问题

### ISSUE THREAD

**Issue by kidling-g** [PaddlePaddle/PaddleOCR#1277]
![截屏2020-11-29 16 34 06](https://user-images.githubusercontent.com/62318458/100537133-cd724780-3260-11eb-9309-f00d26089cfa.png)
1. 请问在上图通用识别模型中，`预训练模型`使用的“全量真实数据与合成数据”分别具体是多少张，是什么样的数据集？

2. `训练模型`又是在多少（或何种）真实数据上基于预训练模型finetune的呢？

感谢回复

**Comment by LDOUBLEV** [comment]
有关模型的训练细节和数据集说明，在pp-ocr的论文中有说明，可供参考：https://arxiv.org/abs/2009.09941
