### ISSUE TITLE
Support to load model in a local directory

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/PaddleOCR#12775]
To avoid re-downloading these files each time a new container is created, is it possible to pre-download the files and store them in a local directory? This way, when a new container is started, it can copy the files from the local directory instead of downloading them again.

_Originally posted by @Ocean-Moist in https://github.com/PaddlePaddle/PaddleOCR/discussions/12774#discussioncomment-9695633_

**Comment by khanfarhan10** [comment]
Any update on this? Is this even possible @SWHL
