### ISSUE TITLE
infer_rec预测推理出现输入维度不匹配问题

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/PaddleOCR#1282]
使用python3.5,
paddlepaddle版本 2.0.0rc0

错误信息如下:
`InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 32, 130].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]`

解决办法:
修改PaddleOCR/ppocr/modeling/architectures/rec_model.py文件162行后面添加"image_shape.insert(0, -1)"
后面是具体路径create_feed函数中self.tps != None下面image_shape = deepcopy(self.image_shape)后面,添加image_shape.insert(0, -1)

**Comment by WenmuZhou** [comment]
方便提个pr吗

**Comment by L-lei** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午5:53
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"。"<1456853914@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] infer_rec预测推理出现输入维度不匹配问题 (#1282)





 
方便提个pr吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




您好,这个我建议还是让这个项目现在的开发维护者修改,原因如下:

1.我没有参与这个项目的设计,可能我的修改会造成二次错误问题,只是我使用的那个代码能正常运行

2.我没有所有的测试方法,不能够保证其它的算法模型使用不会受影响




看了我原因,如果您觉得还是可以由我修改,那我就尽量测试让其它的算法模型使用也不会受影响
