### ISSUE TITLE
predict_xx.py文件使用pyinstaller打包后，子进程一直增加，c盘temp文件夹爆仓

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleOCR#1283]
运行peidict_det.exe之后，
1. 控制台没有任何反应，
![image](https://user-images.githubusercontent.com/68883664/100686540-80ee4f80-33b9-11eb-96d3-1819826d83f7.png)
2. 任务管理器进程一直增加
![image](https://user-images.githubusercontent.com/68883664/100686689-d0348000-33b9-11eb-91aa-f91cd002b0dc.png)
3. C盘temp隐藏文件夹爆仓

**Comment by MissPenguin** [comment]
直接按照这个教程操作吧：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer

**Comment by stefan-567** [comment]
> 直接按照这个教程操作吧：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer

非常感谢您的回复，不过我想使用python环境下的接口，是否有其他的解决方法？

**Comment by littleWayne** [comment]
> > 直接按照这个教程操作吧：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer
> 
> 非常感谢您的回复，不过我想使用python环境下的接口，是否有其他的解决方法？

解决了吗哥们，什么问题，我pyinstaller打包也是进程不断增加

**Comment by YaoFANGUK** [comment]
同样的问题，打包失败

**Comment by littleWayne** [comment]
> 同样的问题，打包失败

在paddle/dataset/image.py中导入cv2时它为了解决什么bug写的很复杂用了多进程，改成直接导入cv2就好了
