### ISSUE TITLE
SRN中文识别问题

### ISSUE THREAD

**Issue by huilinghap** [PaddlePaddle/PaddleOCR#1284]
使用数据在SRN和CTC分别进行中文训练，CTC效果可达到65，而SRN只达到54，有什么好的建议？
看您之前提到的分阶段进行训练（先训练pvam模块，再训练gsrm ），是否有参考的文档及代码？谢谢~

**Comment by tink2123** [comment]
使用中文训练SRN的时候，image_shape 是否有对应修改呢？ 数据大概是什么类型的？ 
分阶段训练，就是在计算loss的时候不要fuse，先使用pvam_out 计算loss，训练完pvam之后再训练gsrm。

**Comment by huilinghap** [comment]
image_shape修改为[64, 320]，也尝试修改为[32, 320]效果不好，数据字符串长度大约在30+，SRN对这种长字符串效果是否明显？
对于pvam训练，使用pvam_outfeature->fc->topk->cross_entropy->loss 是否理解的正确？期待您的回复！谢谢~

**Comment by tink2123** [comment]
> 使用pvam_outfeature->fc->topk->cross_entropy->loss 是否理解的正确

是的，就是这样。 SRN在长文本上更具优势，论文中有给出在中文长文本上的测试数据：
![image](https://user-images.githubusercontent.com/31891223/101315373-66264a00-3895-11eb-8e44-7307e867f945.png)
