### ISSUE TITLE
移动端部署问题-直接下载的模型无法使用，提示opt

### ISSUE THREAD

**Issue by sxl1007** [PaddlePaddle/PaddleOCR#1285]
![image](https://user-images.githubusercontent.com/42663550/100587715-e72c9100-332b-11eb-8ae4-1b03d8af6a5b.png)
报错的时候给出的警告是opt工具和paddlelite版本不一致，但是我的paddlelite版本是2.7
![image](https://user-images.githubusercontent.com/42663550/100587753-f3185300-332b-11eb-8d5f-d628ec9e1734.png)

**Comment by sxl1007** [comment]
上面的图太小，看不清报错信息，报错信息如下：

[W 11/30 16:32:50.336 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[W 11/30 16:32:50.372 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[W 11/30 16:32:50.419 ...e-Lite/lite/model_parser/model_parser.cc:954 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:bd402b3
[F 11/30 16:32:50.428 ...e/admin/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():
[F 11/30 16:32:50.428 ...e/admin/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():

Segmentation fault

**Comment by 772865705** [comment]
大哥，顺便问下你的2.7版本的paddlelite哪里来的，能给我一份吗 demo里面的版本是2.6.1 我不知道怎么换成2.7

**Comment by studiouspan** [comment]
我遇到跟你一样的问题，兄嘚你解决了吗？我在官方群里问也没人回答。

**Comment by studiouspan** [comment]
+q 390402327  我们讨论下

**Comment by DaveBoy** [comment]
+1

**Comment by studiouspan** [comment]
> +1
树莓派部署paddle lite 使用paddle OCR，我已搞定。

**Comment by studiouspan** [comment]
> 我遇到跟你一样的问题，兄嘚你解决了吗？我在官方群里问也没人回答。

我解决了

**Comment by DaveBoy** [comment]
我也搞定了，[我2.7 编译的debug包](https://github.com/PaddlePaddle/PaddleOCR/issues/1655)

主要原因是因为lite编译预测库的版本和转换nb文件的opt来源版本不一致，得自己编译一次opt再用自己编译的opt转换生成nb

**Comment by studiouspan** [comment]
> 我也搞定了，[我2.7 编译的debug包](https://github.com/PaddlePaddle/PaddleOCR/issues/1655)
> 
> 主要原因是因为lite编译预测库的版本和转换nb文件的opt来源版本不一致，得自己编译一次opt再用自己编译的opt转换生成nb

我是在树莓派上部署的，原因却不是版本来源不一致的问题，报版本warning可以不用管，我这边问题是因为官方给的推理demo的代码有问题。

**Comment by zhoutao138** [comment]
> > +1
> > 树莓派部署paddle lite 使用paddle OCR，我已搞定。

你好，可以请教一下怎么部署吗

**Comment by studiouspan** [comment]
我已收到您的邮件，谢谢，祝一切顺利！
