### ISSUE TITLE
移动端部署问题-使用opt转换模型无法识别

### ISSUE THREAD

**Issue by sxl1007** [PaddlePaddle/PaddleOCR#1286]
![image](https://user-images.githubusercontent.com/42663550/100591099-412f5580-3330-11eb-9564-a0400f85795f.png)
报错：
[F 11/30 17: 9:36.710 .../admin/Paddle-Lite/lite/api/light_api.cc:60 Build] Unknown model type
[F 11/30 17: 9:36.710 .../admin/Paddle-Lite/lite/api/light_api.cc:60 Build] Unknown model type

[F 11/30 17: 9:36.710 .../admin/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size:
[F 11/30 17: 9:36.710 .../admin/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size:

[F 11/30 17: 9:36.710 ...e/admin/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!
[F 11/30 17: 9:36.710 ...e/admin/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!

[F 11/30 17: 9:36.710 ...e/admin/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,18446744073709551615] but got 0
[F 11/30 17: 9:36.710 ...e/admin/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,18446744073709551615] but got 0

[F 11/30 17: 9:36.710 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()
[F 11/30 17: 9:36.710 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()

Segmentation fault

**Comment by LDOUBLEV** [comment]
运行指令上加上分类模型地址

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
