### ISSUE TITLE
请问下，弯曲文本有试过opencv的TPS进行弯曲校正吗？对于效果和性能有没有评估过呢？

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#1288]
请问下，弯曲文本有试过opencv的TPS进行弯曲校正吗？对于效果和性能有没有评估过呢？

**Comment by WenmuZhou** [comment]
opencv的tps需要标出对应的点，这个点比较难弄，现在网络中的tps模块实现了自动学点，自动校正，不需要使用传统cv的tps

**Comment by cjt222** [comment]
TPS模型的效果如何呢，鲁棒性如何，这种模型的训练数据如何准备呢？

**Comment by WenmuZhou** [comment]
能够提升识别模型1%+,数据不需要准备，使用的是无标签学习，梯度来自于识别的loss

**Comment by cjt222** [comment]
TPS的接受输入是否是固定的？是否可支持变长数据？

**Comment by cjt222** [comment]
性能以及鲁棒性如何呢？

**Comment by WenmuZhou** [comment]
输入这块，我这边没有测试不同宽度的输入，您可以测试一下。性能方面会降低一点速度，鲁棒性还行
