### ISSUE TITLE
CUDA10.2运行train.py报错 TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by Maia97** [PaddlePaddle/PaddleOCR#1292]
CUDA10.2运行train.py报错
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)

CUDA 10.2
cuDNN 7.6
paddlepaddle 1.8.5.post107

export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64/ 依旧报错

**Comment by littletomatodonkey** [comment]
建议使用2.0.0rc进行训练

**Comment by unisoc281** [comment]
请教下，这个问题是如何解决的呢，我也遇到同样的问题。

**Comment by Mrfuhang** [comment]
解决了嘛

**Comment by Mrfuhang** [comment]
pip install paddlepaddle  我这边安装然后就没有报这个错了
