### ISSUE TITLE
文本检测训练报错 ModuleNotFoundError: No module named 'utility'

### ISSUE THREAD

**Issue by Maia97** [PaddlePaddle/PaddleOCR#1293]
`env OMP_NUM_THREADS=4 python train.py --use_gpu False --parallel=False`

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    from utility import check_gpu
ModuleNotFoundError: No module named 'utility'

pip安装utility 1.0，添加了搜索路径还是报错
`sys.path.append('/home/yg2483/anaconda3/envs/python37/lib/python3.7/site-packages/')`

**Comment by littletomatodonkey** [comment]
你这个代码看着和官网的不同，直接实试下官网的代码吧
