### ISSUE TITLE
能否提供较大图像尺寸的识别预训练模型？

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1295]
目前的预训练模型图像尺寸为3*32*320。在预训练模型的基础上基于真实数据训练时，由于真实数据缩放至高32后特征特别模糊，训练效果很差。自己根据说明去下载训练集重做预训练模型，又由于合成数据可能不好使得效果完全比不上提供的1.1版识别模型。所以以后能否同时放出尺寸较大的识别预训练模型？如高96或者以上的

**Comment by MissPenguin** [comment]
这个我们会考虑，但目前还无法保证哈，急需的话还是建议自己训练一下
