### ISSUE TITLE
Paddle中文识别场景数据集下载链接失效，能修复一下吗

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#1296]
![image](https://user-images.githubusercontent.com/17508662/100689646-cc0b6100-33bf-11eb-94bd-e4154f6c5c52.png)

**Comment by MissPenguin** [comment]
这边尝试是可以正常下载的，你再刷新多试几次？可能网络问题。

**Comment by cjt222** [comment]
试过了，是浏览器的问题，chrome下不下来，edge可以
