### ISSUE TITLE
No such file or folder at location

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#1301]
No such file or folder ./doc/predict.txt  "./doc/test_v2" in doc folder

**Comment by MissPenguin** [comment]
Why need file "./doc/predict.txt" or "./doc/test_v2"? What's your command?

**Comment by grasswolfs** [comment]
Hi, this issue is temporarily closed since we haven't received your reply for a long time. If there are more questions, you can reopen it or open a new issue to continue asking. Thank you for using PaddleOCR in your project.
