### ISSUE TITLE
服务化部署后识别不出内容

### ISSUE THREAD

**Issue by Macielyoung** [PaddlePaddle/PaddleOCR#1302]
参考官方服务化部署教程，使用ocr_rec mobile和server两个infernece model，服务化部署都成功了，但是提供图片去测试时很多识别不出正确的文本，感觉识别效果很差，想问问有没有其他人遇到这个问题。我采用的模型是：ch_ppocr_server_v1.1_rec和ch_ppocr_mobile_v1.1_rec。

**Comment by MissPenguin** [comment]
使用的paddle serving还是hub serving进行部署的呢，用的什么图片进行的测试，识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗

**Comment by Macielyoung** [comment]
使用的是hub serving部署的，整体流程就是按照https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/hubserving/readme_en.md流程来操作的。测试方法也是用的tools/test_hubserving.py这个脚本来做的，自己提供的图片，上面带一些文字，但是提供了几张都没有识别出对应的文字，只有用了一张百度的logo可以识别出来😂😂。

**Comment by Macielyoung** [comment]
> 使用的paddle serving还是hub serving进行部署的呢，用的什么图片进行的测试，识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗

使用的是hub serving部署的，整体流程就是按照https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/hubserving/readme_en.md 流程来操作的。测试方法也是用的tools/test_hubserving.py这个脚本来做的，自己提供的图片，上面带一些文字，但是提供了几张都没有识别出对应的文字，只有用了一张百度的logo可以识别出来😂😂。

**Comment by MissPenguin** [comment]
识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗？另外，可以用doc/imgs中的示例图试试，如果结果能和示例结果对上，那就是在你的测试图片场景下效果不好，需要优化模型

**Comment by Macielyoung** [comment]
好的，我试试吧。感谢

**Comment by ExcaliburEX** [comment]
> 识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗？另外，可以用doc/imgs中的示例图试试，如果结果能和示例结果对上，那就是在你的测试图片场景下效果不好，需要优化模型

我也尝试了下，出现了相同的情况，部署后识别不出来，一堆文字识别成一个数字。用`tools/infer/predict_system.py`就可以完全识别出来，不是数据的问题，怀疑部署的服务运行的算法跟本地运行时不一样？

**Comment by ExcaliburEX** [comment]
> 识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗？另外，可以用doc/imgs中的示例图试试，如果结果能和示例结果对上，那就是在你的测试图片场景下效果不好，需要优化模型

请问有什么办法嘛，搞了两天了，头疼。无论是用`2.0.0rc1`的代码还是`1.1`的代码都是一样的结果，各种`rec`模型也都试过了，都是识别不出来，但是用`paddlepaddleocr`包或者直接`tools/infer/predict_system.py`都能识别。是不是我的`./inference/ch_ppocr_mobile_v1.1_rec_infer/`放错位置了，我是放在了直接clone过来的`PaddleOCR`以及目录下。

**Comment by Macielyoung** [comment]
> > 识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗？另外，可以用doc/imgs中的示例图试试，如果结果能和示例结果对上，那就是在你的测试图片场景下效果不好，需要优化模型
> 
> 请问有什么办法嘛，搞了两天了，头疼。无论是用`2.0.0rc1`的代码还是`1.1`的代码都是一样的结果，各种`rec`模型也都试过了，都是识别不出来，但是用`paddlepaddleocr`包或者直接`tools/infer/predict_system.py`都能识别。是不是我的`./inference/ch_ppocr_mobile_v1.1_rec_infer/`放错位置了，我是放在了直接clone过来的`PaddleOCR`以及目录下。

我怀疑可能是使用的模型出错了，可以考虑一下paddlepaddleocr包调用的模型文件来部署，看一下包里面的源代码。

**Comment by ExcaliburEX** [comment]
> > > 识别效果和直接用tools/infer/predict_system.py进行预测的效果能对上吗？另外，可以用doc/imgs中的示例图试试，如果结果能和示例结果对上，那就是在你的测试图片场景下效果不好，需要优化模型
> > 
> > 
> > 请问有什么办法嘛，搞了两天了，头疼。无论是用`2.0.0rc1`的代码还是`1.1`的代码都是一样的结果，各种`rec`模型也都试过了，都是识别不出来，但是用`paddlepaddleocr`包或者直接`tools/infer/predict_system.py`都能识别。是不是我的`./inference/ch_ppocr_mobile_v1.1_rec_infer/`放错位置了，我是放在了直接clone过来的`PaddleOCR`以及目录下。
> 
> 我怀疑可能是使用的模型出错了，可以考虑一下paddlepaddleocr包调用的模型文件来部署，看一下包里面的源代码。

关键是不会啊，包里的源代码如何与hubserving集成呢，貌似逻辑是不一样的。感觉只能通过最笨的方法就是，通过python用代码与服务器进行SSH连接，然后发送指令运行paddlepaddleocr程序识别，然后将识别结果download下来，假装那边开了一个服务的样子、
