### ISSUE TITLE
cpu环境下onnxruntime推理报错

### ISSUE THREAD

**Issue by Ghorc** [PaddlePaddle/PaddleOCR#13048]
#### 问题描述 / Problem Description
onnxruntime-gpu1.15版本，在cpu环境下报错

#### 运行环境 / Runtime Environment
- onnxruntime-gpu: 1.15.0
#### 复现代码 / Reproduction Code
tools/infer/utility.py 204行缺少providers：
        else:
            sess = ort.InferenceSession(model_file_path)
        return sess, sess.get_inputs()[0], None, None

#### 完整报错 / Complete Error Message
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by GreatV** [comment]
@Ghorc 你好，你是否愿意提交一个pr来修复这个问题（在main分支）。
