### ISSUE TITLE
The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly.(error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by unyxs281** [PaddlePaddle/PaddleOCR#1304]
运行train.py 第74行exe.run(startup_program)时，出现这个错误，请教下该怎么解决呢?

**Comment by unisoc281** [comment]
![image](https://user-images.githubusercontent.com/74952328/100869365-ecc6da00-34d7-11eb-847d-e0049ea4a683.png)

**Comment by unisoc281** [comment]
这个问题解决了
先输入命令export LD_LIBRARY_PATH=/home/.../anaconda3/envs/pytorch/lib:$LD_LIBRARY_PATH
再输入命令echo $LD_LIBRARY_PATH
然后关掉Pycharm，在同一个terminal中重新启动Pycharm

**Comment by pickwu** [comment]
已解决。参考链接：https://blog.csdn.net/weixin_41255438/article/details/124144722

**Comment by 1nyourlife** [comment]
遇到了相同的问题，但没能通过以上方法解决
环境里肯定是有cudnn的，路径也改过了
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/95243930/74a6b46b-d464-46c2-b309-a4b2d392b88f)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/95243930/36e2b3a8-9cef-4084-b69e-b00b93ef7403)
