### ISSUE TITLE
make qt5py3 in PPOCRLabel

### ISSUE THREAD

**Issue by zeze1111** [PaddlePaddle/PaddleOCR#1305]
在PPOCRLabel中没有makefile，运行make qt5py3报错
`make: *** No rule to make target 'qt5py3'.  Stop.
`

**Comment by Evezerest** [comment]
Makefile had been re-uploaded. `Make qt5py3` is used for resource recompilation, which had been written in PPOCRLabel.py, so it's feasible when you directly run `python PPOCRLabel.py`. However when the resource file changed, `make qt5py3` is also necessary.

**Comment by longshifeng** [comment]
When `python PPOCRLabel.py`  gets:
```
File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```
my env version:
```
python 3.6.1
paddleocr                          1.1.1
paddlepaddle                       2.0.0b0
numpy                              1.19.2
```

what's the matter?

**Comment by Evezerest** [comment]
Are there any other error messages? It seems to be caused by NumPy, maybe you need to check whether it is compatible with Shapely
