### ISSUE TITLE
请问跟去年的craft比在文字检出方面有优势吗？

### ISSUE THREAD

**Issue by wolfryu** [PaddlePaddle/PaddleOCR#131]

**Comment by MissPenguin** [comment]
craft我们没有具体实现，但从两篇论文给出的指标来看，两种算法在icdar2015和CTW1500上的效果接近，DB在Total-Text、MLT- 2017、MSRA-TD500上的效果略有领先，另外DB在效率（fps）方面比craft会更有优势。

**Comment by wolfryu** [comment]
多谢！只要总体比craft好就足够了。
