### ISSUE TITLE
SAST训练

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1310]
![image](https://user-images.githubusercontent.com/56471409/100956502-867f9d00-3553-11eb-9f75-1a7b4b9f3f7f.png)
训练SAST时候，训练到iter=22424的时候，报错；才开始以为是数据的问题，然后重新查看了数据，训练后依然在这个迭代出现一样的错误

**Comment by tink2123** [comment]
看报错是进程数满了，可以减小num_worker的数量试一下
