### ISSUE TITLE
LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(api.obj)

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/PaddleOCR#1311]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(api.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(zero_copy_tensor.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(analysis_config.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(analysis_predictor.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(errors.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(ddim.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(place.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(device_context.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(tensor.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(data_type.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(var_type_traits.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(scope.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(memcpy.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(gpu_info.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(paddle_pass_builder.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(mkldnn_quantizer_config.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(framework.pb.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(var_desc.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(op_desc.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(block_desc.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(program_desc.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(naive_executor.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(op_compatible_info.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(analyzer.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(reset_tensor_array.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(executor.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(init.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(profiler.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(feed_fetch_method.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(version.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(graph_to_program_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(graph_viz_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(lock_free_optimize_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(fc_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(attention_lstm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(fc_lstm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(embedding_fc_lstm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(fc_gru_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(seq_concat_fc_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(multi_batch_merge_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_bn_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(seqconv_eltadd_relu_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(seqpool_concat_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(seqpool_cvm_concat_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(repeated_fc_relu_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(squared_mat_sub_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(is_test_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_elementwise_add_act_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_elementwise_add2_act_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_elementwise_add_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_affine_channel_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(transpose_flatten_concat_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(identity_scale_op_clean_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(sync_batch_norm_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(runtime_context_cache_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(quant_conv2d_dequant_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(shuffle_channel_detect_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(delete_quant_dequant_op_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(simplify_with_basic_ops_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(fc_elementwise_layernorm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(skip_layernorm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(multihead_matmul_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cudnn_placement_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(embedding_eltwise_layernorm_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(mkldnn_placement_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(mkldnn_inplace_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(depthwise_conv_mkldnn_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_bias_mkldnn_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_activation_mkldnn_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_concat_relu_mkldnn_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(conv_elementwise_add_mkldnn_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(scale_matmul_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(fc_mkldnn_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cpu_quantize_placement_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cpu_quantize_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cpu_quantize_squash_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(matmul_transpose_reshape_fuse_pass.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cpu_helper.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(mkldnn_quantizer.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cuda_error.pb.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(dynamic_loader.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cudnn.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(allocator.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(malloc.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(stream_callback_manager.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cuda_stream.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(cublas.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(threadpool.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(flags.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(attribute.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(op_call_stack.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(op_info.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(shape_inference.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(operator.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(op_registry.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(variable_helper.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(passes.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(pretty_log.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(garbage_collector.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(executor_gc_helper.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(trainer_desc.pb.obj)	1	
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中)	ocr_system	D:\PythonProject\PaddleOCR-develop\deploy\cpp_infer\build\libpaddle_fluid.lib(trainer.obj)	1	

问题描述：编译环境win10,cuda9.0+cudnn7.3.1,cmake3.18,vs2017,paddle预测库paddle==1.8.4地址：https://paddle-wheel.bj.bcebos.com/1.8.4/win-infer/mkl/post97/fluid_inference_install_dir.zip；只截取报错中的一部分，麻烦大佬看一下。

**Comment by oldfeecn** [comment]
dll文件放程序运行目录下
![image](https://user-images.githubusercontent.com/43258124/133654917-966028e4-7d5f-40b3-bc06-900c8ac933d7.png)

**Comment by jakclisky** [comment]
因为包含了gfalgs的静态链接库，想办法把相关去掉或者找一个gfalgs的动态链接库即可
