### ISSUE TITLE
引用PaddleOCR模块后会导致logging的默认logger中添加一项haddler

### ISSUE THREAD

**Issue by ireson96** [PaddlePaddle/PaddleOCR#13122]
#### 问题描述 / Problem Description
在引用PaddleOCR模块后会导致logging的默认logger中添加一项haddler，具体现象如下图所示：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/17294469/17d1d683-47fe-463b-9a4d-62b7bd5fee51)

#### 运行环境 / Runtime Environment
- OS: win11
- Paddle: 2.6.1
- PaddleOCR: 2.7.3

#### 复现代码 / Reproduction Code

`from paddleocr import PaddleOCR`

#### 完整报错 / Complete Error Message
会导致其他模块在打印日志的时候控制台多打印预期外的一条日志例如下图：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/17294469/76a102d3-b20e-4fea-b8ef-7faf106edd4a)

#### 可能解决方案 / Possible solutions
倒是可以通过在初始化logger的时候手动清空一遍默认的haddler来解决这个问题，但考虑到并不是所有情况下logger的初始化都在引用PaddleOCR之后，还是建议将PaddleOCR初始化时添加的haddler添加到对应模块名下

**Comment by GreatV** [comment]
你可以提一个PR来修复这个问题吗？

**Comment by ireson96** [comment]
可以 不过跟踪了下是paddle库的命名问题，我不是很确定是不是特意设计成这样的
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/17294469/d29ba238-ca99-4749-a973-34a5a772a54b)

**Comment by ireson96** [comment]
paddle/distributed/utils/log_utils.py

**Comment by GreatV** [comment]
paddleocr 里也有一个 get_logger https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/logging.py ，是不是可以改成 paddleocr里的 get_logger

**Comment by ireson96** [comment]
> paddleocr 里也有一个 get_logger https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/logging.py ，是不是可以改成 paddleocr里的 get_logger

这样的改动会比较大吧 毕竟两个get_logger的参数都并不太相同
