### ISSUE TITLE
pyinstaller打包后不能运行，不打包只跑py程序正常，报错是RuntimeError: MKL_Free_Buffers not found.

### ISSUE THREAD

**Issue by omaiyiwa** [PaddlePaddle/PaddleOCR#13121]
#### 问题描述 / Problem Description
pyinstaller打包后不能运行，不打包只跑py程序正常
我这样加载程序        self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False, use_gpu=False)
这样预测          out = self.ocr.ocr(frame, cls=False, det=False)
这时候是正常识别的能返回值
然后我用pyinstaller打包(之前其它电脑打包过)解决了一些之前遇到的问题，然后遇到了一个新问题
- FileNotFoundError: [Errno 2] No such file or directory: '***\\_internal\\tools/__init__.py'
我将paddleocr\tools复制到_internal下解决(尚不确定是否正确)
然后遇到了
 - The third-party dynamic library (mklml.dll) that Paddle depends on is not configured
我下载了[mklml_win_2018.0.3.20180406.zip](https://github.com/intel/mkl-dnn/releases/download/v0.14/mklml_win_2018.0.3.20180406.zip)，并解压添加为环境变量解决了(尚不确定是否正确)
然后继续运行新问题
 -   File "tools\infer\predict_rec.py", line 616, in __call__
    self.predictor.run()
RuntimeError: MKL_Free_Buffers not found.

该错误并没有找到好的解决方案

#### 运行环境 / Runtime Environment
- OS:  windows10 专业版  cuda 11.8 cudnn应该是8.6.0.163 
- Paddle:  paddlepaddle-gpu             2.4.2.post117
- PaddleOCR:  paddleocr                    2.7.3

**Comment by omaiyiwa** [comment]
> #### 问题描述 / Problem Description
> pyinstaller打包后不能运行，不打包只跑py程序正常 我这样加载程序 self.ocr = PaddleOCR(use_angle_cls=False, lang="ch", show_log=False, use_gpu=False) 这样预测 out = self.ocr.ocr(frame, cls=False, det=False) 这时候是正常识别的能返回值 然后我用pyinstaller打包(之前其它电脑打包过)解决了一些之前遇到的问题，然后遇到了一个新问题
> 
> * FileNotFoundError: [Errno 2] No such file or directory: '***\_internal\tools/**init**.py'
>   我将paddleocr\tools复制到_internal下解决(尚不确定是否正确)
>   然后遇到了
> * The third-party dynamic library (mklml.dll) that Paddle depends on is not configured
>   我下载了[mklml_win_2018.0.3.20180406.zip](https://github.com/intel/mkl-dnn/releases/download/v0.14/mklml_win_2018.0.3.20180406.zip)，并解压添加为环境变量解决了(尚不确定是否正确)
>   然后继续运行新问题
> * File "tools\infer\predict_rec.py", line 616, in **call**
>   self.predictor.run()
>   RuntimeError: MKL_Free_Buffers not found.
> 
> 该错误并没有找到好的解决方案
> 
> #### 运行环境 / Runtime Environment
> * OS:  windows10 专业版  cuda 11.8 cudnn应该是8.6.0.163
> * Paddle:  paddlepaddle-gpu             2.4.2.post117
> * PaddleOCR:  paddleocr                    2.7.3
> 
> #### 复现代码 / Reproduction Code
> #### 完整报错 / Complete Error Message
> #### 可能解决方案 / Possible solutions
> #### 附件 / Appendix

python 3.9

**Comment by omaiyiwa** [comment]
python3.9

**Comment by Gmgge** [comment]
The third-party dynamic library (mklml.dll) that Paddle depends on is not configured 这一步操作使用 --collect-all paddle来解决，由于mklml.dll为paddle的依赖，该依赖可能跟随paddle的版本升级而改变，使用paddle自带的会减少不兼容的问题出现。

其他缺少的库可以参考PPOCRlabel的[打包指令](https://github.com/PFCCLab/PPOCRLabel?tab=readme-ov-file#124-pyinstaller-build)，该库也是依赖paddleocr的，经过测试在系统：windows10，CPU:x86_64（amd、Intel） 设备中正常打包运行。

期待你的测试反馈。

**Comment by omaiyiwa** [comment]
> The third-party dynamic library (mklml.dll) that Paddle depends on is not configured 这一步操作使用 --collect-all paddle来解决，由于mklml.dll为paddle的依赖，该依赖可能跟随paddle的版本升级而改变，使用paddle自带的会减少不兼容的问题出现。
> 
> 其他缺少的库可以参考PPOCRlabel的[打包指令](https://github.com/PFCCLab/PPOCRLabel?tab=readme-ov-file#124-pyinstaller-build)，该库也是依赖paddleocr的，经过测试在系统：windows10，CPU:x86_64（amd、Intel） 设备中正常打包运行。
> 
> 期待你的测试反馈。

感谢，我加入了  --collect-all paddleocr --collect-all pyclipper --collect-all imghdr --collect-all skimage --collect-all imgaug --collect-all scipy.io --collect-all lmdb --collect-all paddle  成功解决了我的问题
