### ISSUE TITLE
The Korean language model fails to recognize '.' because it is missing.

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/PaddleOCR#13147]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13144

<div type='discussions-op-text'>

<sup>Originally posted by **junhwan-lim** June 21, 2024</sup>
The Korean language model fails to recognize '.' because it is missing.</div>

**Comment by uyeongjae** [comment]
`,` `(`  `)` also missed

**Comment by UserWangZz** [comment]
你好，可以提一个pr补充一下字典中缺失的字符，如果有对模型的需要，可以在星河社区上对现有模型进行一个微调，提供给我们吗？

**Comment by uyeongjae** [comment]
I think that modifying only the dictionary like this [PR](https://github.com/PaddlePaddle/PaddleOCR/pull/13142) will affect the existing model. How do you recommend learning to recognize small numbers of missing characters?
