### ISSUE TITLE
paddleocr 2.7.3 GPU和CPU推理结果不一致

### ISSUE THREAD

**Issue by VictorHe-1** [PaddlePaddle/PaddleOCR#13140]
#### 问题描述 / Problem Description
GPU和CPU对同一张图片识别结果不同

#### 运行环境 / Runtime Environment
- OS: Linux x86_64
- Paddle: paddlepaddle-gpu    2.6.1.post120
- PaddleOCR: paddleocr  2.7.3

#### 复现代码 / Reproduction Code
用的图片是：https://aistudio-fe-online.cdn.bcebos.com/pipeline/imgs/general_ocr_008.png
```python
import cv2
from paddleocr import PaddleOCR

ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False)

img_path = "general_ocr_008.png"
frame = cv2.imread(img_path)
result = ocr.ocr(frame, cls=False)
print(result)

ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False, use_gpu=False)
result2 = ocr.ocr(frame, cls=False)
print(result2)
# result2 和result结果不同
```

#### 完整报错 / Complete Error Message
GPU识别结果为[None]，CPU为[[[[[444.0, 176.0], [1166.0, 176.0], [1166.0, 222.0], [444.0, 222.0]], ('ACKNOWLEDGEMENTS', 0.9849705100059509)], [[[401.0, 346.0], [1204.0, 346.0], [1204.0, 386.0], [401.0, 386.0]], ('We would like to thank all the designers and', 0.9955495595932007)], [[[399.0, 396.0], [1206.0, 395.0], [1206.0, 436.0], [399.0, 438.0]], ('contributors who have been involved in the', 0.9838518500328064)], [[[399.0, 446.0], [1207.0, 445.0], [1208.0, 486.0], [399.0, 488.0]], ('production of this book; their contributions', 0.9981548190116882)], [[[401.0, 496.0], [1209.0, 496.0], [1209.0, 536.0], [401.0, 536.0]], ('have been indispensable to its creation. We', 0.9993702173233032)], [[[399.0, 548.0], [1209.0, 548.0], [1209.0, 588.0], [399.0, 588.0]], ('would also like to express our gratitude to all', 0.9976420998573303)], [[[401.0, 598.0], [1208.0, 598.0], [1208.0, 638.0], [401.0, 638.0]], ('the producers for their invaluable opinions', 0.9868574738502502)], [[[397.0, 648.0], [1209.0, 646.0], [1209.0, 686.0], [397.0, 688.0]], ('and assistance throughout this project. And to', 0.9915577173233032)], [[[397.0, 698.0], [1213.0, 696.0], [1213.0, 738.0], [397.0, 739.0]], ('the many others whose names are not credited', 0.9984794855117798)], [[[399.0, 750.0], [1211.0, 750.0], [1211.0, 789.0], [399.0, 789.0]], ('but have made specific input in this book, we', 0.9834606647491455)], [[[397.0, 802.0], [1090.0, 800.0], [1090.0, 841.0], [397.0, 843.0]], ('thank you for your continuous support.', 0.9983049631118774)]]]

**Comment by GreatV** [comment]
换个gpu试试

**Comment by jingsongliujing** [comment]
```
import cv2
from paddleocr import PaddleOCR
import paddle
# 使用第一块GPU
paddle.set_device('gpu:0')

img_path = "general_ocr_008.png"
frame = cv2.imread(img_path)

ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False, use_gpu=True)
result2 = ocr.ocr(frame, cls=False)
print(result2)
# result2 和result结果不同
```
假如是多卡，建议paddle.set_device('gpu:0')设置一下用哪张卡

**Comment by VictorHe-1** [comment]
> ```
> import cv2
> from paddleocr import PaddleOCR
> import paddle
> # 使用第一块GPU
> paddle.set_device('gpu:0')
> 
> img_path = "general_ocr_008.png"
> frame = cv2.imread(img_path)
> 
> ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False, use_gpu=True)
> result2 = ocr.ocr(frame, cls=False)
> print(result2)
> # result2 和result结果不同
> ```
> 
> 假如是多卡，建议paddle.set_device('gpu:0')设置一下用哪张卡
刚刚尝试了一下，还是一样，8张卡返回的结果都是None。这个检测识别结果会和cuda版本有关系吗？我的cuda版本是12.2，paddlepaddle我看官方文档是只写了12.0的。

**Comment by VictorHe-1** [comment]
> ```
> import cv2
> from paddleocr import PaddleOCR
> import paddle
> # 使用第一块GPU
> paddle.set_device('gpu:0')
> 
> img_path = "general_ocr_008.png"
> frame = cv2.imread(img_path)
> 
> ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False, use_gpu=True)
> result2 = ocr.ocr(frame, cls=False)
> print(result2)
> # result2 和result结果不同
> ```
> 
> 假如是多卡，建议paddle.set_device('gpu:0')设置一下用哪张卡

刚刚尝试了一下，还是一样，8张卡返回的结果都是None。这个检测识别结果会和cuda版本有关系吗？我的cuda版本是12.2，paddlepaddle我看官方文档是只写了支持cuda 12.0的。 @jingsongliujing @GreatV

**Comment by jingsongliujing** [comment]
按道理来说，cuda都是向下兼容的，看看是不是装了两个版本的paddle，假如是装了paddlepaddle和paddlepaddle-gpu，就把cpu的那个卸载，再试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月20日(周四) 晚上7:37
0收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] paddleocr 2.7.3 GPU和CPU推理结果不一致 (Issue #13140)




  import cv2 from paddleocr import PaddleOCR import paddle # 使用第一块GPU paddle.set_device('gpu:0') img_path = "general_ocr_008.png" frame = cv2.imread(img_path) ocr = PaddleOCR(use_angle_cls=True, lang='ch', show_log=False, use_gpu=True) result2 = ocr.ocr(frame, cls=False) print(result2) # result2 和result结果不同  
假如是多卡，建议paddle.set_device('gpu:0')设置一下用哪张卡
  
刚刚尝试了一下，还是一样，8张卡返回的结果都是None。这个检测识别结果会和cuda版本有关系吗？我的cuda版本是12.2，paddlepaddle我看官方文档是只写了支持cuda 12.0的。 @jingsongliujing @GreatV

**Comment by GreatV** [comment]
旧的显卡paddle不支持

**Comment by VictorHe-1** [comment]
> 旧的显卡paddle不支持

我的显卡是H800，然后paddlepaddle没有装CPU版本的，只存在GPU版本的paddlepaddle，重新试了下cuda 11.8，依然还是识别为none。重新看了下paddle那边的issue，貌似是因为paddlepaddle暂时不支持H系列显卡。

**Comment by GreatV** [comment]
可以尝试自己编译一个paddle框架
