### ISSUE TITLE
GPU推理时显存一直上涨，不释放，显存满了后，再推理就没有结果了

### ISSUE THREAD

**Issue by dencentding** [PaddlePaddle/PaddleOCR#13145]
#### 运行环境 / Runtime Environment

- OS:   ubuntu      python  3.10    cuda 12.1
- Paddle: paddlepaddle-gpu 2.6
- PaddleOCR: 2.7.3

#### 复现代码 / Reproduction Code
from paddleocr.ppstructure.kie.predict_kie_token_ser import SerPredictor

用 SerPredictor进行的推理

**Comment by GreatV** [comment]
更新一下 paddle develop 版本再看看 https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

**Comment by dencentding** [comment]
> 更新一下 paddledevelop 版本再看看https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

同样的paddledevelop，推理代码一样，我们测试环境推理GPU显存，就会释放，但是正式环境就是不释放，唯一的区别就是，测试环境cuda 为12.1，正式环境cuda为11.8

**Comment by GreatV** [comment]
@dencentding 可能是 onednn 的bug 
- https://github.com/PaddlePaddle/PaddleOCR/issues/11639#issuecomment-2177926739

**Comment by Chris-Mraz** [comment]
> > 更新一下 paddledevelop 版本再看看https://www.paddlepaddle.org.cn/install/quick?docurl=undefined
> 
> 同样的paddledevelop，推理代码一样，我们测试环境推理GPU显存，就会释放，但是正式环境就是不释放，唯一的区别就是，测试环境cuda 为12.1，正式环境cuda为11.8

您好，请问GPU显存一直增加不释放这个问题你解决了吗，因为我这边正式环境是cuda11.7的，没办法使用12.1或者11.8的

**Comment by Chris-Mraz** [comment]
> 更新一下 paddle develop 版本再看看 https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

您好，请问还有其他办法吗，因为我这边正式环境是cuda11.7的，没办法使用cuda12.1或者11.8的开发版本

**Comment by GreatV** [comment]
@Chris-Mraz 这个是onednn的bug，只能通过升级解决

**Comment by LLee233** [comment]
> @Chris-Mraz 这个是onednn的bug，只能通过升级解决

@GreatV oneDNN on Paddle is only targeting for CPU, I think this issue should not be related to oneDNN...

**Comment by Chris-Mraz** [comment]
目前测试了paddleocr 2.7.3貌似解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月16日(周二) 中午11:05
收件人: ***@***.***&gt;;
抄送: "Yang ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] GPU推理时显存一直上涨，不释放，显存满了后，再推理就没有结果了 (Issue #13145)




  
@Chris-Mraz 这个是onednn的bug，只能通过升级解决
  
@GreatV oneDNN on Paddle is only targeting for CPU, I think this issue should not be related to oneDNN...

**Comment by GreatV** [comment]
@LLee233 I'm sorry for my mistake. Since the onednn update, paddle 3.0 beta update, there are much less of these isssues.

**Comment by ThiruRJST** [comment]
@Chris-Mraz Can you please help me with what you did to solve this issue, I'm using 
PaddleOCR - 2.8.1
PaddlePaddle-GPU - 2.6.1
CUDA - 11.8


It is not solved in my system

**Comment by Chris-Mraz** [comment]
I tried the version&nbsp;paddleocr 2.7.3 and it seems to be solved.
paddlepaddle-gpu==2.5.2.post117
cuda 11.7


花生牛奶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] GPU推理时显存一直上涨，不释放，显存满了后，再推理就没有结果了 (Issue #13145)





 
@Chris-Mraz Can you please help me with what you did to solve this issue, I'm using
 PaddleOCR - 2.8.1
 PaddlePaddle-GPU - 2.6.1
 CUDA - 11.8
 
It is not solved in my system
