### ISSUE TITLE
Package lock numpy

### ISSUE THREAD

**Issue by yuuz233** [PaddlePaddle/PaddleOCR#13152]
#### 运行环境 / Runtime Environment
- OS: MacOS
- Paddle: 2.6.1
- PaddleOCR: 2.7.3

#### 复现代码 / Reproduction Code
2.2.1 演示代码
`from paddleocr import PaddleOCR, draw_ocr

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

# 显示结果
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')`

#### 完整报错 / Complete Error Message
Various

#### 可能解决方案 / Possible solutions

1. Numpy 2.0+OpenCV latest, Paddle不支持，这个是如果手动override opencv
2. Numpy 2.0+OpenCV 4.6.x, OpenCV该版本不支持Numpy2.0，这个是default behaviour
3. Numpy 1.x+OpenCV 4.6.x, Paddle可以使用。

解决方案：lock numpy to <2.0.0

Same as #13136 但是OpenCV 4.6也不支持numpy 2.0，所以可能是permanently lock to `<2.0.0`了

**Comment by GreatV** [comment]
我们后面会支持numpy>=2.0，现在主要问题是imgaug库不知道numpy 2.0，所以要先解决这个问题。如果你感兴趣的话，可以提一个pr来解决这个问题。
