### ISSUE TITLE
“paddlepaddle”、“paddleocr”安装会改变系统对opencv的安装方式？

### ISSUE THREAD

**Issue by laogonggong847** [PaddlePaddle/PaddleOCR#13156]
#### 问题描述 / Problem Description

运行“pip install paddlepaddle paddleocr”后，使用anaconda不论是在现有环境还是创建新环境时，使用pip install opencv都会选择通过编译的方法安装这是为什么？ paddlepaddle paddleocr会修改我的某些系统配置么？ 如果会我应该怎么修改？

我的图片展示的是opencv-contrib-python，但是opencv-python同样是这样
<img width="565" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/81297486/35ec1bcb-3683-41d6-a592-450f94e3a089">

这个情况是我安装 “paddlepaddle paddleocr”时才第一次出现的，后续不管我新建环境还是在现有环境安装opencv都存在这个问题。我认为这是paddlepaddle paddleocr安装时修改了某些系统配置才导致出现的。这样导致我在新环境中pip install opencv和opencv-contrib-python都特别慢。我应该如何修改？

#### 运行环境 / Runtime Environment
- OS:  MacOS
- Paddle: 2.5.0
- PaddleOCR: 2.7.3
- 一开始是最新的，但是我的Mac系统是11.6，所以我降低到这个版本了，实际安装的时候是安装最新的时候导致的这个问题，提供的版本是我降低后的版本

**Comment by GreatV** [comment]
因为numpy 升级到了2.0，导致opencv需要重新编译。

**Comment by GreatV** [comment]
Fixes #13105

**Comment by laogonggong847** [comment]
您好 @GreatV：
是的我查看了清华镜像确实没有我对应的版本，当存在对应版本时确实不会再进行任何的编译。
但是有一点我很纳闷，为什么我的Mac在安装paddle和paddleOCR之后当安装opencv会进行检查？现在不仅paddle所在的环境存在这个问题，而是我创建所有新环境，在安装没有对应python编译的版本都会出现这个情况，但是这个现象就是在我pip安装paddle和paddleOCR之后出现的，因此我有理由怀疑是安装他们时修改了我的某些配置？
打个比方：
我用windows创建python3.10的环境，当我pip最新时，安装最新版本的opencv
![53d72b2f53730e8f2ff1374acccb136b](https://github.com/PaddlePaddle/PaddleOCR/assets/81297486/63f280f8-b4fb-4864-8167-3e88fb1bc395)
请注意：
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/6c/fab8113424af5049f85717e8e527ca3773299a3c6b02506e66436e19874f/opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
虽然我是3.10的python但是下载的却是cp37，并且不尽兴任何编译，这和我之前的mac环境是一致的。
但是同样的我有mac创建一个最新的python3.10的环境，并且同样运行时，它会给我编译，因为清华镜像中并没有3.10版本编译的最新opencv-python。
因此我想请问一下您，我应该paddle和paddleOCR是否会修改我pip时的某些检查？如果是的话我应该如何回退这些修改？

**Comment by GreatV** [comment]
只是碰巧 opencv-python前几天更新的版本

**Comment by laogonggong847** [comment]
是的，opencv-python却是刚更新不久，所以我测试Mac时 
我实际是pip install opencv-python==制定某个旧版本。
打个比方4.6.0
<img width="930" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/81297486/13166fff-b314-4f18-96ff-f9b6e40726b4">

4.6.0 Mac没有cp38编译的版本，所以他会自己编译，而我之前mac环境中使用安装pip 4.7.0 4.8.0均不会编译
但是我pip安装cp38编译的opencv他又能正确下载对应的whl
而现在我pip安装这些没有cp38编译的版本，都会出现重新编译。而之前并不会，这不仅仅是对opencv4.10，而是之前正确安装使用的opencv 4.7 4.8都出现了
一开始我并不认为我pip安装paddle和paddleocr会改变我mac上pip的策略，因此我最初以为是pip本身策略的更新，后来我通过降低pip版本再次测试，以前没问题的情况现在又要重新编译，然后我在windows上创建同样的python3.10环境确保pip同样的情况下就是上图的情况虽然py3.10的环境但是却是cp37的版本并且不会重新编译。因此让我十分纳闷
十分感谢您的回复，再次感谢
