### ISSUE TITLE
OpenCV版本能不能升到最新版本，而且依赖上不要写死，现在很多库都是最新的，结果共用的时候产生了依赖冲突了

### ISSUE THREAD

**Issue by charlesluo2014** [PaddlePaddle/PaddleOCR#13157]
#### 问题描述 / Problem Description
使用别的开源库的时候产生了依赖冲突

#### 运行环境 / Runtime Environment
- OS: MacOS
- Paddle:  最新版本
- PaddleOCR: 最新版本

#### 复现代码 / Reproduction Code
paddleocr 依赖版本是<=4.6.0.66，其它的开源库使用的是opencv-python~=4.10.0.82，

#### 完整报错 / Complete Error Message

paddleocr 依赖版本是<=4.6.0.66，其它的开源库使用的是opencv-python~=4.10.0.82，opencv因为是比较常用到的库，很多场景都会用到，假如冲突的话就用不了paddleocr
#### 可能解决方案 / Possible solutions

升级依赖配置

**Comment by GreatV** [comment]
有道理，你可以提一个pr来修复它，其实最好不用指定版本号
