### ISSUE TITLE
SAST  algorithm issue..

### ISSUE THREAD

**Issue by tzktok** [PaddlePaddle/PaddleOCR#13161]
#### 问题描述 / Problem Description
```
from paddleocr import PaddleOCR,draw_ocr
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=False, lang='en', det_algorithm="SAST") # need to run only once to download and load model into memory
img_path = 'test3.jpg'
result = ocr.ocr(img_path, cls=True,det=True,inv=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)
```
error i got..
```
[2024/06/22 16:49:54] ppocr ERROR: det_algorithm must in ['DB']
```

#### 运行环境 / Runtime Environment
- OS:Ubuntu
- Paddle:paddlepaddle-2.6.1
- PaddleOCR: paddleocr 2.7.3

how to use the SAST detection algorithm... @tink2123

**Comment by GreatV** [comment]
Please refer to: https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_en/algorithm_det_sast_en.md

**Comment by tzktok** [comment]
> Please refer to: https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_en/algorithm_det_sast_en.md

tried but same error..

**Comment by GreatV** [comment]
it work for me.

![det_res_img_10](https://github.com/PaddlePaddle/PaddleOCR/assets/17264618/2a602ff7-4d54-4ecb-a777-7a2f2e5eed40)

**Comment by tzktok** [comment]
> it work for me.
> 
> ![det_res_img_10](https://private-user-images.githubusercontent.com/17264618/341971873-2a602ff7-4d54-4ecb-a777-7a2f2e5eed40.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDQzOTksIm5iZiI6MTcxOTIwNDA5OSwicGF0aCI6Ii8xNzI2NDYxOC8zNDE5NzE4NzMtMmE2MDJmZjctNGQ1NC00ZWNiLWE3NzctN2EyZjJlNWVlZDQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA0NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTZmZmJiNTUyMmM1ZTZlZWYxYzM0NzQzYzhhZjU4NTIyYzRhYTliMWQwNDhiMjlkMTRlNzE3YTE2M2MzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vzMfxXXyFAYxVdTAHXAAGDQHJk4uUAr1Snoivuh1Bjc)

```
tamil@DESKTOP-FLC1RG0:~/PaddleOCR$ python3 tools/export_model.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.pretrained_model=./det_r50_vd_sast_icdar15_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_ic15
Traceback (most recent call last):
  File "/home/tamil/PaddleOCR/tools/export_model.py", line 295, in <module>
    main()
  File "/home/tamil/PaddleOCR/tools/export_model.py", line 254, in main
    load_model(config, model, model_type=config["Architecture"]["model_type"])
  File "/home/tamil/PaddleOCR/ppocr/utils/save_load.py", line 150, in load_model
    is_float16 = load_pretrained_params(model, pretrained_model)
  File "/home/tamil/PaddleOCR/ppocr/utils/save_load.py", line 162, in load_pretrained_params
    assert os.path.exists(
AssertionError: The ./det_r50_vd_sast_icdar15_v2.0_train/best_accuracy.pdparams does not exists!
tamil@DESKTOP-FLC1RG0:~/PaddleOCR$
```
@GreatV i got this error ..while run this

**Comment by GreatV** [comment]
Please refer to: https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_en/algorithm_det_sast_en.md, You'll have to read the documents more than once.

**Comment by tzktok** [comment]
ok i got it..but detection failed for below image..
```
tamil@DESKTOP-FLC1RG0:~/PaddleOCR$ python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/test3.jpg" --det_model_dir="./inference/det_sast_ic15/"
E0624 10:51:51.041435 76965 analysis_config.cc:125] Please use PaddlePaddle with GPU version.
[2024/06/24 10:52:03] ppocr INFO: test3.jpg     []

[2024/06/24 10:52:03] ppocr INFO: 0 The predict time of ./doc/imgs_en/test3.jpg: 12.069519281387329
[2024/06/24 10:52:03] ppocr INFO: The visualized image saved in ./inference_results/det_res_test3.jpg  @GreatV 
```
![test3](https://github.com/PaddlePaddle/PaddleOCR/assets/169971463/21f7c517-2827-49fc-9f1a-060afc5076a6)

**Comment by GreatV** [comment]
For your own scenario, the detection model needs to be retrained.

**Comment by tzktok** [comment]
> For your own scenario, the detection model needs to be retrained.

i have the dataset format like below..
```
" Image file name             Image annotation information encoded by json.dumps"
ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]
```
how to train this in pre trained weight model...in my dataset i have only 6 images nd their labels.. @GreatV

**Comment by GreatV** [comment]
Please refer to https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_en/detection_en.md. It is essential to increase your data size.
