### ISSUE TITLE
表格标注数据验证问题

### ISSUE THREAD

**Issue by 77bw** [PaddlePaddle/PaddleOCR#13176]
#### 问题描述 / Problem Description
如何验证表格标注后的数据准确性，我用原本训练前的数据转换去做的，但是我有一些excel都没有做，他却显示是正确的
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/94338396/7bb312b3-6950-4e49-9a73-fe176fc0db83)

#### 可能解决方案 / Possible solutions
我目前检验数据标注是通过训练前的数据转换报ndexError: list index out of range 判断的，在加上读取excel的box和标注的bos是否相同。是否有其他更加健壮的方法嘛

**Comment by 77bw** [comment]
outs = transform(data, self.ops)
还有这个转换为空是否有问题呢？

**Comment by UserWangZz** [comment]
我之前使用PPOCRLabel标注过一批小批量的复杂表格，我的做法是随机选择几个复杂的表格标注结果，将标注中的HTML结果可视化出来判断，虽然无法全覆盖检测，但是针对复杂表格的标注没有问题，那么简单结构的表格出错的概率将会变得很低。
