### ISSUE TITLE
标注软件导出exe

### ISSUE THREAD

**Issue by BiggerBinBin** [PaddlePaddle/PaddleOCR#1318]
官方出的标注软件包含了标注一键导出模型所需要的文件，并且还能切割图片。甚是好用。但是提供的打包成exe文件的脚本不符合在windows上的使用习惯。希望官方能直接生成一个可执行文件，供广大使用者下载直接使用，从而在没有python环境下也能使用

**Comment by longshifeng** [comment]
PPOCRLabel 为啥编译不过。。。
能帮忙看下嘛？

```
(py36) G:\PaddleOCR\PPOCRLabel>python PPOCRLabel.py
Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "..\tools\infer\predict_system.py", line 26, in <module>
    import tools.infer.predict_det as predict_det
  File "..\tools\infer\predict_det.py", line 35, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "..\ppocr\data\det\db_process.py", line 23, in <module>
    from .data_augment import AugmentData
  File "..\ppocr\data\det\data_augment.py", line 13, in <module>
    import imgaug
  File "D:\anaconda\envs\py36\lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "D:\anaconda\envs\py36\lib\site-packages\imgaug\imgaug.py", line 22, in <module>
    import skimage.draw
  File "D:\anaconda\envs\py36\lib\site-packages\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```

```
python 3.6.1 
paddleocr                          1.1.1
paddlepaddle                       2.0.0b0
```

**Comment by WenmuZhou** [comment]
> PPOCRLabel 为啥编译不过。。。
> 能帮忙看下嘛？
> 
> ```
> (py36) G:\PaddleOCR\PPOCRLabel>python PPOCRLabel.py
> Traceback (most recent call last):
>   File "PPOCRLabel.py", line 34, in <module>
>     from paddleocr import PaddleOCR
>   File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
>     from .paddleocr import PaddleOCR
>   File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
>     from tools.infer import predict_system
>   File "..\tools\infer\predict_system.py", line 26, in <module>
>     import tools.infer.predict_det as predict_det
>   File "..\tools\infer\predict_det.py", line 35, in <module>
>     from ppocr.data.det.db_process import DBProcessTest
>   File "..\ppocr\data\det\db_process.py", line 23, in <module>
>     from .data_augment import AugmentData
>   File "..\ppocr\data\det\data_augment.py", line 13, in <module>
>     import imgaug
>   File "D:\anaconda\envs\py36\lib\site-packages\imgaug\__init__.py", line 7, in <module>
>     from imgaug.imgaug import *  # pylint: disable=redefined-builtin
>   File "D:\anaconda\envs\py36\lib\site-packages\imgaug\imgaug.py", line 22, in <module>
>     import skimage.draw
>   File "D:\anaconda\envs\py36\lib\site-packages\skimage\__init__.py", line 158, in <module>
>     from .util.dtype import *
>   File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
>     from .arraycrop import crop
>   File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
>     from numpy.lib.arraypad import _validate_lengths
> ImportError: cannot import name '_validate_lengths'
> ```
> 
> ```
> python 3.6.1 
> paddleocr                          1.1.1
> paddlepaddle                       2.0.0b0
> ```

百度一下也许更好 https://blog.csdn.net/weixin_42267309/article/details/91490953

**Comment by longshifeng** [comment]
> > PPOCRLabel 为啥编译不过。。。
> > 能帮忙看下嘛？
> > ```
> > (py36) G:\PaddleOCR\PPOCRLabel>python PPOCRLabel.py
> > Traceback (most recent call last):
> >   File "PPOCRLabel.py", line 34, in <module>
> >     from paddleocr import PaddleOCR
> >   File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
> >     from .paddleocr import PaddleOCR
> >   File "D:\anaconda\envs\py36\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
> >     from tools.infer import predict_system
> >   File "..\tools\infer\predict_system.py", line 26, in <module>
> >     import tools.infer.predict_det as predict_det
> >   File "..\tools\infer\predict_det.py", line 35, in <module>
> >     from ppocr.data.det.db_process import DBProcessTest
> >   File "..\ppocr\data\det\db_process.py", line 23, in <module>
> >     from .data_augment import AugmentData
> >   File "..\ppocr\data\det\data_augment.py", line 13, in <module>
> >     import imgaug
> >   File "D:\anaconda\envs\py36\lib\site-packages\imgaug\__init__.py", line 7, in <module>
> >     from imgaug.imgaug import *  # pylint: disable=redefined-builtin
> >   File "D:\anaconda\envs\py36\lib\site-packages\imgaug\imgaug.py", line 22, in <module>
> >     import skimage.draw
> >   File "D:\anaconda\envs\py36\lib\site-packages\skimage\__init__.py", line 158, in <module>
> >     from .util.dtype import *
> >   File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
> >     from .arraycrop import crop
> >   File "D:\anaconda\envs\py36\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
> >     from numpy.lib.arraypad import _validate_lengths
> > ImportError: cannot import name '_validate_lengths'
> > ```
> > 
> > 
> > ```
> > python 3.6.1 
> > paddleocr                          1.1.1
> > paddlepaddle                       2.0.0b0
> > ```
> 
> 百度一下也许更好 https://blog.csdn.net/weixin_42267309/article/details/91490953

谢谢！这个问题当时已经解决了。
实际原因是关于Numpy、shapely的版本问题（win10）
下面顺便给出最终兼容的版本作参考
numpy                              1.16.0
scikit-image                       0.17.2
Shapely                            1.7.1 （https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely）

**Comment by lzh109** [comment]
> 官方出的标注软件包含了标注一键导出模型所需要的文件，并且还能切割图片。甚是好用。但是提供的打包成exe文件的脚本不符合在windows上的使用习惯。希望官方能直接生成一个可执行文件，供广大使用者下载直接使用，从而在没有python环境下也能使用

想问下您windows下怎么将标注软件打包成exe，我用pyinstaller打包一直报错
