### ISSUE TITLE
我使用onnxruntime对齐官方的推理，推理速度比使用paddlepaddle框架推理快很多（速度快5，6倍）

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/PaddleOCR#13191]
#### 问题描述 / Problem Description

我使用onnxruntime对齐官方的推理，推理速度比使用paddlepaddle框架推理快很多（速度快5，6倍），是框架有问题吗
#### 运行环境 / Runtime Environment
- windows/linux:
-onnxruntime

#### 复现代码 / Reproduction Code
代码：https://github.com/jingsongliujing/OnnxOCR.git

**Comment by GreatV** [comment]
是比 paddle inference 快吗

**Comment by jingsongliujing** [comment]
> 是比 paddle inference 快吗

是的，要快很多

**Comment by jingsongliujing** [comment]
特别是v4版本

**Comment by jingsongliujing** [comment]
其他几个模型不明显，就v4 mobile 比较明显

**Comment by GreatV** [comment]
用 `onnx=True` 来跑呢

**Comment by jingsongliujing** [comment]
没试过，但是官方框架它本身会加载很多配置，估计推理速度也会比自己拆出来慢一些

**Comment by jingsongliujing** [comment]
我目前只做了检测，分类，识别三个模型的串联
