### ISSUE TITLE
Missing Files after building paddle library for C++ inference

### ISSUE THREAD

**Issue by rahulmangalampalli** [PaddlePaddle/PaddleOCR#1322]
## Steps followed:

* Firstly I'll give my system specification on which I reproduced below mentioned steps:

1. CPU : Intel i7 quad core processor
2. OS: Ubuntu 16.04 docker
3. RAM: 8GB

### Step 1: Installing OpenCV

* I followed same steps as given over [here](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/readme_en.md#11-compile-opencv) to install opencv version 3.4, but after executing ```make -j``` step my system freezes around 12% while building it.

* Freezing issue happened several times hence I switched to opencv 3.2 and installed it using the commands as shown below:

```bash
sudo apt install libopencv-calib3d3.2 libopencv-core3.2 libopencv-features2d3.2  libopencv-flann3.2 libopencv-highgui3.2 libopencv-imgcodecs3.2 libopencv-imgproc3.2 libopencv-ml3.2 libopencv-objdetect3.2 libopencv-photo3.2 libopencv-shape3.2 libopencv-stitching3.2 libopencv-superres3.2 libopencv-video3.2 libopencv-videoio3.2 libopencv-videostab3.2 libopencv-viz3.2 libopencv3.2-jni libopencv3.2-java libopencv-contrib3.2 

$ sudo apt install libopencv-calib3d-dev libopencv-core-dev libopencv-features2d-dev  libopencv-flann-dev libopencv-highgui-dev libopencv-imgcodecs-dev libopencv-imgproc-dev libopencv-ml-dev libopencv-objdetect-dev libopencv-photo-dev libopencv-shape-dev libopencv-stitching-dev libopencv-superres-dev libopencv-video-dev libopencv-videoio-dev libopencv-videostab-dev libopencv-viz-dev libopencv-contrib-dev libopencv-dev
$ sudo apt-get install libopenblas-dev
```
### Step 2: Building Paddle Library:

*  As given in these [steps](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/readme_en.md#121-compile-from-the-source-code), I followed exact same process with  **-DWITH_PYTHON=OFF** , and executed ```make -j``` coomand. Even this command freezed mys system.

* Hence followed the commands as shown below which I found at the [official paddle website](https://www.paddlepaddle.org.cn/documentation/docs/en/advanced_guide/inference_deployment/inference/build_and_install_lib_en.html) : 

```bash
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
mkdir build
cd build
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
 make
 make inference_lib_dist
```

* The above mentioned commands ran without any issue and freezing problems. But here the problem is the structure of the build folder is not as expected. 

* **Expected:**

```bash
build
|--fluid_inference_install_dir
```

* **I got:**

```bash
build
|--paddle_c_inference_install_dir 
|--paddle_inference_install_dir
```

* At this [step](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/readme_en.md#21-export-the-inference-model) it is required to export trained models on to Paddle directory in inference folder.

* After bringing them it uses a python script called tools/export_model.py, but there is no such file existing in repo's tools
folder.

* It mentions of **sh tools/build.sh** and **sh tools/run.sh** even those files are missing.

* Can anyone please mention proper way of building paddle library properly on the mentioned environment specs at start.

**Comment by littletomatodonkey** [comment]
You can rename `paddle_inference_install_dir` to `paddle_inference_install_dir ` , or change the directory in the cmakelist, since the develop paddle changed the output dir.
