### ISSUE TITLE
如何输出PaddleOCR的DB检测网络每一层网络的名字？

### ISSUE THREAD

**Issue by unyxs281** [PaddlePaddle/PaddleOCR#1323]

**Comment by YukSing12** [comment]
我也遇过这个问题，
paddlepaddle2.0 可以使用paddle.summary()
paddlepaddle2.0 以下可以使用paddle.fluid.contrib.model_stat.summary()，不过这个不能输出名字，得自己改一下源码。

**Comment by xiaotongtong9293** [comment]
您好,请问是将  paddle.summary()  这句话直接写在哪个位置么?   没有太懂,可否详细的说一下呢?  十分感谢!
