### ISSUE TITLE
在mac上使用PPOCRLabel.py进行标注图像，点击自动标注会闪退

### ISSUE THREAD

**Issue by wowowoll** [PaddlePaddle/PaddleOCR#1324]
![image](https://user-images.githubusercontent.com/49295186/101160840-a950a500-366a-11eb-9594-2df167b417ed.png)
PPOCRLabel.py:1096: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1898: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:2090: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/samuel/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='/Users/samuel/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/samuel/.paddleocr/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
dt_boxes num : 1, elapse : 0.013941287994384766
cls num  : 1, elapse : 0.011889934539794922
rec_res num  : 1, elapse : 0.04531407356262207
file name in openNext is  /Users/samuel/Downloads/ch4_test_images/img_1.jpg
dirPath in importDirImages is /Users/samuel/Downloads/ch4_test_images
unicodeFilePath is /Users/samuel/Downloads/ch4_test_images/img_1.jpg
initPos PyQt5.QtCore.QPointF(937.7169811320756, 254.0188679245283)
待识别
Cancel creation.
file name in openNext is  /Users/samuel/Downloads/ch4_test_images/img_2.jpg
unicodeFilePath is /Users/samuel/Downloads/ch4_test_images/img_2.jpg
Using model from  paddle
Bus error: 10
(base) lichaodeMacBook-Pro:PPOCRLabel samuel$ python PPOCRLabel.py 
PPOCRLabel.py:1096: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1898: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:2090: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/samuel/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='/Users/samuel/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/samuel/.paddleocr/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
dt_boxes num : 1, elapse : 0.014941930770874023
cls num  : 1, elapse : 0.014447927474975586
rec_res num  : 1, elapse : 0.04808187484741211
file name in openNext is  /Users/samuel/Downloads/ch4_test_images/img_1.jpg
dirPath in importDirImages is /Users/samuel/Downloads/ch4_test_images
Using model from  paddle
Bus error: 10

**Comment by kouhou** [comment]
me too

**Comment by zjuPeco** [comment]
同样是Bus error: 10

**Comment by Evezerest** [comment]
Add a new line of code `self.setStackSize(1024*1024)` in https://github.com/PaddlePaddle/PaddleOCR/blob/develop/PPOCRLabel/libs/autoDialog.py#L27. Special thanks to @ninetailskim

**Comment by wowowoll** [comment]
更新之后解决了
