### ISSUE TITLE
I can help with Turkish language.

### ISSUE THREAD

**Issue by omeeragtoprak** [PaddlePaddle/PaddleOCR#13265]
I can help with Turkish language.

_Originally posted by @fcakyon in https://github.com/PaddlePaddle/PaddleOCR/issues/1048#issuecomment-750784603_
yardımcı olabilir misiniz?

**Comment by SWHL** [comment]
Please provide the dict of Turkish language in the Discussions #12734

**Comment by fcakyon** [comment]
@omeeragtoprak @SWHL I added Turkish dict in 2021 but got no response from the Paddle team: https://github.com/PaddlePaddle/PaddleOCR/pull/1856/files

**Comment by SWHL** [comment]
@fcakyon PaddleOCR has been maintained by several groups of people. Previously, it was maintained by Baidu's official staff, and this time it was replaced by our community staff. We really don't have the energy to expand it. We will try our best to solve the previous legacy issues.
