### ISSUE TITLE
Paddle OCR c++ 编译问题

### ISSUE THREAD

**Issue by Yuzuki-N** [PaddlePaddle/PaddleOCR#1326]
在执行 `sh tools/build.sh`时出错
```
CMakeFiles/ocr_system.dir/src/ocr_cls.cpp.o: In function `PaddleOCR::Classifier::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:86: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.cpp.o: In function `PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:21: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.cpp.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:124: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ocr_system.dir/build.make:358: recipe for target 'ocr_system' failed
make[2]: *** [ocr_system] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by LDOUBLEV** [comment]
你用的哪个版本的预测库，像是找不到 AnalysisConfig

**Comment by Yuzuki-N** [comment]
ubuntu14.04_cpu_avx_mkl 1.84版本，我试过其他版本，也都不行

**Comment by littletomatodonkey** [comment]
要不试下2.0.0rc的预测库呢?

**Comment by Lisiyuan555** [comment]
请问最后如何解决的呢

**Comment by yxpandjay** [comment]
同样的问题，请问如何解决
系统ubuntu 18.04 5 LTS

**Comment by HongChow** [comment]
> 在执行 `sh tools/build.sh`时出错
> 
> ```
> CMakeFiles/ocr_system.dir/src/ocr_cls.cpp.o: In function `PaddleOCR::Classifier::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> /home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:86: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> CMakeFiles/ocr_system.dir/src/ocr_det.cpp.o: In function `PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> /home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:21: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> CMakeFiles/ocr_system.dir/src/ocr_rec.cpp.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> /home/hznu/ocr/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:124: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/ocr_system.dir/build.make:358: recipe for target 'ocr_system' failed
> make[2]: *** [ocr_system] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
> make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
解决了没？

**Comment by zxk1995** [comment]
请问解决了吗？

**Comment by Lixin-Liu** [comment]
> 同问，如何解决的呢？同样的问题

您好，请问您的问题解决了吗？
