### ISSUE TITLE
自定义字典进行训练，输出结果顺序不对

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#1327]
自定义的字典如下，进行测试的图片内容是041001900204，但是模型的输出结果却是(0)(()5((-(0，这是什么原因呢
![image](https://user-images.githubusercontent.com/13652569/101244324-c5267a80-3740-11eb-991a-3e2e93e7d8bc.png)

**Comment by Lie-huo** [comment]
字典内容如下
(
)
-
.
0
1
2
3
4
5
6
7
8
9

**Comment by LDOUBLEV** [comment]
没有训练好吧

**Comment by LLL0802** [comment]
请问自定义字典训练步骤是什么呢，能否告知一下
