### ISSUE TITLE
Change the "English" tab path in Pypi

### ISSUE THREAD

**Issue by ConnectingDNA-Depositary** [PaddlePaddle/PaddleOCR#13282]
This is just to draw your attention that the path to the "English" tab under project description in PyPi is broken.
[https://pypi.org/project/paddleocr/README_en.md/](url)

![Screenshot from 2024-07-07 14-50-28](https://github.com/PaddlePaddle/PaddleOCR/assets/166585916/39fd133d-dd2e-408e-a692-f70004994fec)

The content is available on GitHub, so you only need to use the right path. Please fix it. Thanks!

**Comment by GreatV** [comment]
thank you @ConnectingDNA-Depositary, we will update all broken link.
