### ISSUE TITLE
怎么设置只识别数字？

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1328]

**Comment by LDOUBLEV** [comment]
不能设置，可以加后处理，如果识别到的字符不是数字，通过后处理过滤掉

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
