### ISSUE TITLE
Why the QPS is not like the github demo showing？

### ISSUE THREAD

**Issue by 813BoZai** [PaddlePaddle/PaddleOCR#13293]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13292

<div type='discussions-op-text'>

<sup>Originally posted by **813BoZai** July  8, 2024</sup>
the link: https://github.com/PaddlePaddle/PaddleOCR/blob/main/deploy/pdserving/README_CN.md about Serving PaddleOCR，showing the index of QPS is 22s but when I am work for the this the QPS not got the level.Can you provide your config.yaml or other file to help me to arrive the level？</div>

**Comment by 813BoZai** [comment]
and other question is about how to control the size of image？to set the 'image_shape: [960,960] or 'resize_long: 5120' or 
'limit_side_len: 5120' in config.yaml?

**Comment by GreatV** [comment]
hi @813BoZai, pdserving is no longer maintained, you may need to choose another method for deployment.
