### ISSUE TITLE
请问会引入PSENET的检测方法吗？

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#133]
请问会引入PSENET的检测方法吗？

**Comment by MissPenguin** [comment]
暂时没有计划哈，下一步将要开源的检测算法是自研算法SAST。从论文结果上看，psenet和DB、SAST相比，效果和效率方面均无明显优势，所以暂不计划实现。

**Comment by SixGodGG** [comment]
> 暂时没有计划哈，下一步将要开源的检测算法是自研算法SAST。从论文结果上看，psenet和DB、SAST相比，效果和效率方面均无明显优势，所以暂不计划实现。

好的，明白了。但是psenet好像针对扭曲排列的字符检测上有优势。SAST什么时候推出？算法时间上和DB相比会更快吗？另外可否推出一个只有数字的和一个只有数字+字母的超轻量模型

**Comment by MissPenguin** [comment]
> > 暂时没有计划哈，下一步将要开源的检测算法是自研算法SAST。从论文结果上看，psenet和DB、SAST相比，效果和效率方面均无明显优势，所以暂不计划实现。
> 
> 好的，明白了。但是psenet好像针对扭曲排列的字符检测上有优势。SAST什么时候推出？算法时间上和DB相比会更快吗？另外可否推出一个只有数字的和一个只有数字+字母的超轻量模型

sast在研发中了，预计7月开源，速度应该和DB相当，具体等实现完了会进行量化对比。
只识别数字或数字+字母的模型，暂时无法提供，我们使用的训练工具已全部开源，可以按照教程组织数据自定义训练哈～
