### ISSUE TITLE
训练时出现Cudnn error,CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by littlesevenxiaoqi** [PaddlePaddle/PaddleOCR#1330]
运行文本识别训练的python3 tools/train.py -c configs/rec/rec_icdar15_train.yml 2>&1 | tee train_rec.log步骤时，出现错误：
External error: Cudnn error, CUDNN_STATUS_BAD_PARAM (at /paddle/paddle/fluid/operators/batch_norm_op.cu:319)
   [operator<batch_norm>error]
求大佬解答。。

**Comment by LDOUBLEV** [comment]
更换paddle到2.0rc 版本试试，

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
