### ISSUE TITLE
PaddleOCR执行文本检测时，错误退出

### ISSUE THREAD

**Issue by confuse05** [PaddlePaddle/PaddleOCR#13318]
#### 问题描述 / Problem Description
在对下面图片执行paddleocr检测时，程序会错误退出，无报错信息，仅打印了一行数字 (585, 0, 3) 32 576
![cropped_4](https://github.com/PaddlePaddle/PaddleOCR/assets/37286426/f1e95b0d-b885-45d7-b743-3da055bff035)

#### 运行环境 / Runtime Environment
- OS:  Macos 14.4 / Centos-8
- Paddle:  2.6.1(macos)/2.5.2(centos)
- PaddleOCR:  2.8.0

#### 复现代码 / Reproduction Code
 paddleocr --image_dir temncnwn/structure_images/cropped_4.png 

#### 完整报错 / Complete Error Message

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/37286426/0c4b7518-0596-4a61-b105-c19e3967364c)

**Comment by GreatV** [comment]
已复现，这个是bug。

**Comment by GreatV** [comment]
已在 #13319 修复

**Comment by confuse05** [comment]
还有个问题，在类似这种页面ocr识别时，会出现坐标顺序不固定，导致拼接时语序混乱的情况，有什么好办法判断语序吗，比如图中这句会返回如下结果
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/37286426/04837613-0958-43a6-9fde-71a87813b877)
可以看到连续的三段文字被切到了不同的位置
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/37286426/e3642423-95f7-4faf-be61-b1680633a105)

**Comment by confuse05** [comment]
> 已在 #13319 修复

按照这个改动测试了一下，还有些问题
具体流程是在最新的main分支上按照这个commit进行了对应的修改，然后pip uninstall原有的paddleocr版本，并重新在Paddlecor路径下使用pip install .安装

再使用paddleocr --image_dir 测试开头的图片，在macos上运行没问题，但在centos-8的容器中运行时，报错
<img width="1085" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/37286426/5e09a958-e4c8-4844-a2e5-7baf23e08288">

运行环境与开始时用的相同
OS: Macos 14.4 / Centos-8
Paddle: 2.6.1(macos)/2.5.2(centos)
PaddleOCR: 2.8.0

**Comment by GreatV** [comment]
试试安装paddle 3.0 beta
