### ISSUE TITLE
PPStructure(table=True) Notebook kernel Dead

### ISSUE THREAD

**Issue by jinming-neuroleap** [PaddlePaddle/PaddleOCR#13315]
#### 问题描述 / Problem Description
改为table=False正常运行，table=True就一直kernel dead重启

#### 运行环境 / Runtime Environment
- OS: Ubuntu 24.04
- Paddle: 2.6.1
- PaddleOCR: 2.7.3

**Comment by GreatV** [comment]
升级一下paddle框架版本，安装3.0
