### ISSUE TITLE
Recognition returns extra characters

### ISSUE THREAD

**Issue by richardgohth** [PaddlePaddle/PaddleOCR#13312]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13284

<div type='discussions-op-text'>

<sup>Originally posted by **richardgohth** July  8, 2024</sup>
I am training paddleocr on synthetic characters.
However always get extra characters during recognition
For example
1234 is read as 123400

Anyone encountered? How to resolve?
Appreciate assistance please</div>

**Comment by GreatV** [comment]
Please provide more information including runtime environment, paddleocr version, paddle version, training configuration used, dataset, etc.

**Comment by richardgohth** [comment]
mismatch rec_image_size  , sorry
case closed
