### ISSUE TITLE
SRN训练日志

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#1332]
SRN的训练日志方便提供下么？

**Comment by tink2123** [comment]
抱歉，暂时没有训练日志，后续会提供。

**Comment by SealQ** [comment]
@tink2123 请问SRN达到readme中的准确率用了什么配置训练了多久？

**Comment by tink2123** [comment]
配置和github中给出的一致，4卡v100训练了大概2周
