### ISSUE TITLE
ppocr v4的字符检测模块在C++使用CPU推理的时候结果异常问题

### ISSUE THREAD

**Issue by dtiny** [PaddlePaddle/PaddleOCR#13332]
#### 问题描述 / Problem Description
ppocr v4的字符检测模型在使用CPU推理的时候有目标检测框结果输出，但是输出框的位置、大小和数量全是错误，没有一个跟实际的字符行沾边的；在同样的检测设置参数情况下，如果改成GPU推理，结果就是正确的；如果换成v3版本的检测模型，CPU和GPU推理结果都是正确的，唯独v4的CPU检测是错误的。

#### 运行环境 / Runtime Environment
- OS: ubuntu18.04
- Paddle: paddle_inference.tgz 2.5 GPU | 是 | MKL | 8.2 | CUDA11.2/cuDNN8.2/TensorRT8.0
- PaddleOCR: PaddleOCR release/2.7/deploy/cpp_infer/中的c++推理代码

#### 复现代码 / Reproduction Code
检测的参数设置如下：
use_gpu 0
use_tensorrt 0
use_fp16 1
gpu_mem 4000
cpu_math_library_num_threads 10
use_mkldnn 1
limit_side_len 736
limit_type min
det_db_thresh 0.3
det_db_box_thresh 0.55
det_db_unclip_ratio 2.0
use_polygon_score 1
det_db_score_mode fast
use_dilation 0
det_precision fp16

#### 完整报错 / Complete Error Message
正常运行，没有异常报错发现，检测模块有推理目标框输出，但是输出框的位置、大小和数量全是错误，没有一个跟实际的字符行沾边的。

#### 可能解决方案 / Possible solutions
应该是推理库的问题，在C++调用推理库在执行CPU推理的时候输出结果有问题（仅仅是ppocr v4的检测有问题），导致了错误的推理结果，（paddle_inference.tgz 2.5 GPU | 是 | MKL | 8.2 | CUDA11.2/cuDNN8.2/TensorRT8.0）

**Comment by GreatV** [comment]
估计是mkldnn的问题

**Comment by dtiny** [comment]
这个问题该如何解决呢，有没有解决的办法，帮助指导一下，谢谢。

**Comment by GreatV** [comment]
换一个推理后端（如 onnx、openvino）吧，paddle 3.0 应该解决了这个问题，目前paddle inference 3.0还来发版。
