### ISSUE TITLE
新的表格识别算法-SLANet-LCNetV2，推理模型结果没法复现

### ISSUE THREAD

**Issue by zhujun5164** [PaddlePaddle/PaddleOCR#13334]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13333

<div type='discussions-op-text'>

<sup>Originally posted by **zhujun5164** July 10, 2024</sup>
我测试了下运行模型的测试代码，但是从输出结果来看和展示的存在明显区别。

python table/predict_structure.py --table_model_dir=../checkpoint/table/ --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt --image_dir=docs/table/table.jpg --output=../output/table_slanet_lcnetv2 --use_gpu=False --benchmark=True --enable_mkldnn=True --table_max_len=512

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49580602/c05a9637-cd85-41db-848e-0d0891628386)
![table](https://github.com/PaddlePaddle/PaddleOCR/assets/49580602/1b5809f1-26d9-4103-853c-65cbc042f9c2)
</div>

**Comment by GreatV** [comment]
@invictuszhao 大佬看下

**Comment by yblir** [comment]
遇到了同样的问题，把提供的训练模型转成infer模型后再次推理，问题依然存在。

**Comment by ddingwang12** [comment]
根本没法看，估计是出问题了，期待解决

**Comment by Topdu** [comment]
推理命令的字典参数修改为： --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt

**Comment by dragronstranding** [comment]
请问用的官方的模型是在https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_table_slanet.md这个链接中的现在的推理模型吗？为什么我现在的推理模型，用和你一样的指令运行会报错，显示模型不兼容

**Comment by dragronstranding** [comment]
> 请问用的官方的模型是在[https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_table_slanet.md这个链接中的下载的推理模型吗？为什么我现在的推理模型，用和你一样的指令运行会报错，显示模型不兼容](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_table_slanet.md%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E4%B8%AD%E7%9A%84%E7%8E%B0%E5%9C%A8%E7%9A%84%E6%8E%A8%E7%90%86%E6%A8%A1%E5%9E%8B%E5%90%97%EF%BC%9F%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%8E%B0%E5%9C%A8%E7%9A%84%E6%8E%A8%E7%90%86%E6%A8%A1%E5%9E%8B%EF%BC%8C%E7%94%A8%E5%92%8C%E4%BD%A0%E4%B8%80%E6%A0%B7%E7%9A%84%E6%8C%87%E4%BB%A4%E8%BF%90%E8%A1%8C%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%8C%E6%98%BE%E7%A4%BA%E6%A8%A1%E5%9E%8B%E4%B8%8D%E5%85%BC%E5%AE%B9)
