### ISSUE TITLE
SRN 训练时 acc 为 0

### ISSUE THREAD

**Issue by sjtugzx** [PaddlePaddle/PaddleOCR#1334]
我在使用SRN训练的时候 loss 可以不断下降，但是acc为0 请问这是正常现象吗？
![image](https://user-images.githubusercontent.com/20066885/101301613-534f4d80-3874-11eb-889f-b825578c512d.png)

**Comment by sjtugzx** [comment]
使用testset做validation
![image](https://user-images.githubusercontent.com/20066885/101301676-85f94600-3874-11eb-8c1b-bd6ac3d7c757.png)

**Comment by sjtugzx** [comment]
我看了别的帖子有讲是数据集太小了，不过我的数据集用的coco-text大约8w张图片应该还可以啊

**Comment by MissPenguin** [comment]
loss在正常下降的话，可以多等一段时间，刚开始acc=0是正常的。
