### ISSUE TITLE
训练中文识别CPPD方法时，在CPPDLabelEncode中encodech()方法内报错

### ISSUE THREAD

**Issue by JunXiaoWen** [PaddlePaddle/PaddleOCR#13350]
#### 问题描述 / Problem Description
none_char_index = sample(character_index, 37 - len(list(text_node_dict.keys())))
为什么会设置37呢，37是英文字母表的大小？？
#### 运行环境 / Runtime Environment
- OS: win11
- Paddle: 2.4
- PaddleOCR: 2.7

#### 完整报错 / Complete Error Message
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:592 != labels_dims[i]:1152.] (at ..\paddle\phi\infermeta\binary.cc:940)

**Comment by Topdu** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/11080
