### ISSUE TITLE
最新发布表格识别模型报错

### ISSUE THREAD

**Issue by dragronstranding** [PaddlePaddle/PaddleOCR#13359]
#### 问题描述 / Problem Description
下载最新发布的表格识别模型进行推理，然后按照文档来运行会报错

#### 运行环境 / Runtime Environment
- OS:
- Paddle:  2.3.2.post112
- PaddleOCR: 2.7.0.2

#### 复现代码 / Reproduction Code
python table/predict_table.py --det_model_dir=../weights/ch_PP-OCRv3_det_infer --rec_model_dir=../weights/ch_PP-OCRv3_rec_infer  --table_model_dir=../weights/ch_ppstructure_openatom_SLANetv2_infer --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt --image_dir=docs/table/page_1.png --output=../output/table

#### 完整报错 / Complete Error Message
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
Traceback (most recent call last):
  File "table/predict_table.py", line 230, in <module>
    main(args)
  File "table/predict_table.py", line 153, in main
    table_sys = TableSystem(args)
  File "table/predict_table.py", line 73, in __init__
    self.table_structurer = predict_strture.TableStructurer(args)
  File "/80013922/PaddleOCR-release-2.7/ppstructure/table/predict_structure.py", line 91, in __init__
    utility.create_predictor(args, 'table', logger)
  File "/80013922/PaddleOCR-release-2.7/tools/infer/utility.py", line 280, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

#### 可能解决方案 / Possible solutions
表格模型不适配

**Comment by GreatV** [comment]
先更新一下paddle版本和paddleocr版本吧

**Comment by Topdu** [comment]
试试这个issue里面的解决方法：https://github.com/PaddlePaddle/PaddleOCR/issues/13334

**Comment by dragronstranding** [comment]
你用的paddle和paddleocr的版本是多少，能提供下吗？

**Comment by Topdu** [comment]
paddle2.5.2 paddleocr2.8.0

**Comment by 12dc32d** [comment]
> 先更新一下paddle版本和paddleocr版本吧

封装打包后，应用程序运行时一直显示tools包的问题怎么解决？

**Comment by zqWu** [comment]
遇到同样的问题。
模型是直接下载的，整个过程按照文档进行。
请问有什么解决办法吗？

1. 过程参考：https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_table_slanet.md
2. PaddlePaddle 版本: VERSION_NUMBE中 2.8.1
3. 镜像: registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7
4. 权重文件是下载的，见[1]

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/5cf2ec90-f86c-4eea-90e9-50c9d9acc763">

**Comment by GreatV** [comment]
@zqWu paddle版本升级一下再试试

**Comment by zqWu** [comment]
更换镜像解决了。 registry.baidubce.com/paddlepaddle/paddle:3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6
这里 paddlepaddle-gpu==3.0.0b0

**Comment by dragronstranding** [comment]
所以应该是paddlepaddle版本的问题是吗？

**Comment by 12dc32d** [comment]
> 所以应该是paddlepaddle版本的问题是吗？

问题解决了，paddleocr里有太多动态链接库和外部文件，封装的时候最好先建立一个spec文件，然后在sepc文件中datas和hidden里添加路径和名称。
另外在封装打包成应用程序后，用户的环境需要是完整版win10，不然有些共享文件无法使用环境里的导致OCR初始化失败。
