### ISSUE TITLE
Paddleocr models keep downloading every time container starts

### ISSUE THREAD

**Issue by DipanshuJuneja** [PaddlePaddle/PaddleOCR#13385]
I have saved the models in a local folder and have copied them to the Docker image because I don't want the models to download every time a new container starts, which is currently happening. Please see the folder structure, Paddle OCR initialization and dockerfile below. How can I avoid doing this? Note that when I run the app locally, it reads the models from this directory only and does not download at app startup however when deployed using container this appears to keep redownloading
![image](https://github.com/user-attachments/assets/31fe6b80-d507-4138-8642-04c0ab4433e5)

Dockerfile
```
FROM python:3.10

ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN apt-get update && apt-get install -y libgl1 poppler-utils && pip install --no-cache-dir -r requirements.txt 

CMD ["uvicorn", myapproot.main:app", "--host", "0.0.0.0"]
```

Initialization code
```
from paddleocr import PaddleOCR

ocr = PaddleOCR(use_angle_cls=True, lang='en', enable_mkldnn=True, recovery=True,
                det_model_dir=r'myapproot\ocr_models\det', 
                rec_model_dir=r'myapproot\ocr_models\rec')
```

**Comment by GreatV** [comment]
Maybe you need to set the absolute path

**Comment by DipanshuJuneja** [comment]
@GreatV This was helpful, thanks. Got resolved.
