### ISSUE TITLE
存在内存泄露

### ISSUE THREAD

**Issue by XueKX** [PaddlePaddle/PaddleOCR#13381]
#### 问题描述 / Problem Description
存在内存泄露

#### 运行环境 / Runtime Environment
- OS: Ubuntu 22.4
- Paddle:2.6.1
- PaddleOCR:2.8.0

#### 复现代码 / Reproduction Code
from paddleocr import PaddleOCR
from loguru import logger
import requests

ocr_model = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True)

def do_ocr(img_path):
    """
    OCR识别
    :param img_path: 图片路径
    :return: 识别结果
    """
    ocr_result = []
    text_list = []
    result = ocr_model.ocr(img_path, cls=True)

li = [
    "http://XXXX/20240601101336899353.jpg",
    "http://XXXX/20240530214340344285.jpg",
     ...
]

for i in li:
    resp = requests.get(i)
    file_name = i.split("/")[-1]
    with open(f"./ocr_img/{file_name}", "wb") as f:
        f.write(resp.content)
    ret = do_ocr(f"./ocr_img/{file_name}")
    print(ret)

#### 完整报错 / Complete Error Message
多次调用do_ocr函数识别多个不同图片，内存持续上涨，不释放

#### 附件 / Appendix
![image](https://github.com/user-attachments/assets/ae4aa862-4259-4358-875a-12f982567ac9)

**Comment by GreatV** [comment]
更新一下paddle到3.0 beta，和 paddleocr

**Comment by XueKX** [comment]
> 更新一下paddle到3.0 beta，和 paddleocr
烦请告知一下完整的具体的命令，谢谢

**Comment by mattheliu** [comment]
> > 更新一下paddle到3.0 beta，和 paddleocr
> > 烦请告知一下完整的具体的命令，谢谢

@XueKX 你好，可以查看教程：https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

**Comment by XueKX** [comment]
> > > 更新一下paddle到3.0 beta，和 paddleocr
> > > 烦请告知一下完整的具体的命令，谢谢
> 
> @XueKX 你好，可以查看教程：https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

当前版本如下：
paddleocr                     2.8.0
paddlepaddle-gpu              3.0.0b1

导入：
from paddleocr import PaddleOCR 
报错：
  File "/opt/anaconda3/envs/auto_audit/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 22, in <module>
    from paddle.utils import try_import
ModuleNotFoundError: No module named 'paddle.utils'

**Comment by mattheliu** [comment]
@XueKX ，请检查你是否安装成功

**Comment by XueKX** [comment]
> @XueKX ，请检查你是否安装成功

![image](https://github.com/user-attachments/assets/ddc334f0-2b38-47f6-a5d4-a2b506edbc46)

**Comment by GreatV** [comment]
无法复现你的问题，建议在新的虚拟环境中重新安装。

**Comment by fenixlam** [comment]
pip install paddlepaddle
而不是
pip install paddle
後者會裝上一個沒有 utils 的 paddle
