### ISSUE TITLE
Can I fork this and make an English translated version?

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/PaddleOCR#134]

**Comment by tink2123** [comment]
Of course you can ！We also welcome you to contribute translations and submit a new pull request. (^_^)a

**Comment by grasswolfs** [comment]
> _No description provided._

Hi, thanks for your attention.
Excuse me, would you please submit the English translated version (include the Readme_en.md) as a new pull request to this repo, i.e., PaddleOCR? I believe many other developers could benefit from it as well.
We indeed look forward to your contributions, and this may in turn add an explicit great thanks for you in the Readme docs. 
Best regards.

**Comment by xxxpsyduck** [comment]
@grasswolfs I'm working on it. I don't have knowledge of Chinese so I mostly rely on Google translate and it will take time to correct words.

**Comment by grasswolfs** [comment]
> @grasswolfs I'm working on it. I don't have knowledge of Chinese so I mostly rely on Google translate and it will take time to correct words.
@xxxpsyduck We really feel very sorry for the absence of English version. T.T
Maybe we could work together to revise the docs after you finish the first version. Aha : )
Thanks for your contribution very much.

**Comment by xxxpsyduck** [comment]
@tink2123 @grasswolfs Hello. Can you check my fork and give feedback? Or may I have your email for better communication?

**Comment by tink2123** [comment]
Sorry for the late reply. We will read your Repo and reply as soon as possible. Thanks for your contribution. My emial is y_tink@163.com

**Comment by tink2123** [comment]
@xxxpsyduck Hi~ Can you click this button to pull request for us? We will review and comment on it. Thanks a lot.
<img width="1112" alt="图片" src="https://user-images.githubusercontent.com/31891223/84109098-767b7a80-aa54-11ea-8bef-90d255003dd7.png">
<img width="1089" alt="图片" src="https://user-images.githubusercontent.com/31891223/84109249-cfe3a980-aa54-11ea-9eeb-3cdce9d67d4a.png">

**Comment by xxxpsyduck** [comment]
@tink2123 I made a pull request. Looking forward to your feedback :)

**Comment by tink2123** [comment]
@xxxpsyduck  Many thanks for contributing the English documentation. 
<img width="832" alt="图片" src="https://user-images.githubusercontent.com/31891223/84385983-1850c200-ac23-11ea-9547-8517d37e56b8.png">
