### ISSUE TITLE
开启mkldnn加速后，出现报错RuntimeError: could not execute a primitive

### ISSUE THREAD

**Issue by uniqlo1** [PaddlePaddle/PaddleOCR#13407]
程序开始实例化paddleocr类，开启mkldnn加速
![image](https://github.com/user-attachments/assets/58a88767-d9a8-492c-9dbf-f837dc3010e4)
后循环执行对pdf文件的文字识别。
出现的问题是正常执行一个pdf文件的识别，报错一个，再正常执行一个，交替出现。
报错内容如下
![image](https://github.com/user-attachments/assets/df959a28-3ec9-40ac-9da3-fe2d2446dfac)
关闭mkldnn加速后没有此问题。修改为每次对pdf文件进行识别之前重新实例化paddleocr类，也无此问题。但这样解决会导致时间大幅增加。
更换最新的paddleocr2.8.0版本无法解决。
请问这个问题的出现是什么因素导致的，以及解决的思路。或有无除了mkldnn之外其他的cpu加速方式？

**Comment by jzhang533** [comment]
@LLee233 @zhanglirong1999 
Do you have any ideas on this issue? looks like it's oneDNN related, since "could not execute a primitive" are reported from oneDNN

**Comment by LLee233** [comment]
Could you please provide code for reproduction? And which version of Paddle were you using? We will start investigating it. Thanks.

**Comment by uniqlo1** [comment]
> Could you please provide code for reproduction? And which version of Paddle were you using? We will start investigating it. Thanks.

版本如下
![image](https://github.com/user-attachments/assets/653d7b04-440e-46a1-8e6d-b580f2ac6d17)
cpu信息如下
![image](https://github.com/user-attachments/assets/4d4ba4f3-4622-4b21-9fa0-0887a6036320)
系统
![image](https://github.com/user-attachments/assets/eaa889f4-f8ae-4a5e-8f3a-aae8eb80b08d)
抱歉代码在局域网研发环境中无法完全展示。
代码的主要部分：类的定义
```python
class OCRProcessor(paddleocr.PaddleOCR):
    def __init__(self, use_gpu):
        num_cores = int(mp.cpu_count())
        use_num_cores = int(num_cores / 2)
        super().__init__(use_angle_cls=False, use_gpu=False,enable_mkldnn = True,cpu_threads = use_num_cores,use_mp=True,total_process_num = use_num_cores,
                         det_model_dir=os.path.join(ocrprocessor_file_dir, "OCRModel/ch_PP-OCRv3_det_infer"),
                         rec_model_dir=os.path.join(ocrprocessor_file_dir, "OCRModel/ch_PP-OCRv3_rec_infer"),
                         cls_model_dir=os.path.join(ocrprocessor_file_dir,
                                                    "OCRModel/ch_ppocr_mobile_v2.0_cls_slim_infer"))
        # 根据OrigDocInfo中的类型判断出的使用的当前模板的序号
        # self.entityId = Settings.template["templateId"]
        #: :obj:paddleocr.paddleocr.PPStructure:使用PPstructure辅助文字识别
        self.table_engine = PPStructure(layout=False, show_log=False, use_gpu=False,enable_mkldnn = True,cpu_threads = use_num_cores,use_mp=True,total_process_num = use_num_cores,
                                        det_model_dir=os.path.join(ocrprocessor_file_dir,
                                                                   "OCRModel/ch_PP-OCRv3_det_infer"),
                                        rec_model_dir=os.path.join(ocrprocessor_file_dir,
                                                                   "OCRModel/ch_PP-OCRv3_rec_infer"),
                                        table_model_dir=os.path.join(ocrprocessor_file_dir,
                                                                     "OCRModel/ch_ppstructure_mobile_v2.0_SLANet_infer"),
                                        layout_model_dir=os.path.join(ocrprocessor_file_dir,
                                                                      "OCRModel/picodet_lcnet_x1_0_fgd_layout_cdla_infer")
                                        )


```
类的实例化（全局仅实例化一次）：
```python
ocr_processor = OCRProcessor(False)
```


循环执行ocr_processor对象中的类方法：
```python
for i in range(len(self.doc_img_list)):
    try:
        logger.info("当前处理页码：{0}，总处理页数：{1}，设置处理页数值：{2}".format(i + 1, len(self.doc_img_list), int(Settings.filter["processPageNum"])))
        self.doc_img = self.doc_img_list[i]
        self.bboxes_list = None
        self.bboxes_list, _ = self.text_detector(self.doc_img)

```
报错即出现在 self.bboxes_list, _ = self.text_detector(self.doc_img)这一行

**Comment by LLee233** [comment]
![image](https://github.com/user-attachments/assets/c2e5ba30-e590-4786-b170-c0865ca1dd0c)

@uniqlo1 Hi, I see you are using PaddlePaddle-GPU v2.3.2. Have you tried newer version like 3.0-beta or dev building with CPU? If not, could you please use the link below to do faster installation and try your case again?
https://www.paddlepaddle.org.cn/install/quick?docurl=undefined

Since the code you gave was just partial, it may take some time for us to reproduce it.

**Comment by uniqlo1** [comment]
> ![image](https://private-user-images.githubusercontent.com/115513981/349741497-c2e5ba30-e590-4786-b170-c0865ca1dd0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzA2MjksIm5iZiI6MTcyMTM3MDMyOSwicGF0aCI6Ii8xMTU1MTM5ODEvMzQ5NzQxNDk3LWMyZTViYTMwLWU1OTAtNDc4Ni1iMTcwLWMwODY1Y2ExZGQwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNjI1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTAwNzE2Y2VkNzg5YmY4MzEwMjI2NTRhMzYwZmNjMjQxYjg4N2FmMGNhNzM2YWYzOTQ5MjhmZGJmMjQ3MWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yNQeHYQF7NSZnnrpbugfG_WV2ZRCf-zQ9TqJhFCQqlI)
> 
> @uniqlo1 Hi, I see you are using PaddlePaddle-GPU v2.3.2. Have you tried newer version like 3.0-beta or dev building with CPU? If not, could you please use the link below to do quick installation and try your case again? Cause after 3.0-beta, we upgraded onednn to newer version. And we wonder if this issue still exists. https://www.paddlepaddle.org.cn/install/quick?docurl=undefined
> 
> Since the code you gave was just partial, it may take some time for us to reproduce it. So it may be more convenient from your side. Thanks.

非常感谢您的帮助，但因为我的代码是在一个局域网中的研发环境，现在要导入更换新的paddlepaddle包版本需要一些复杂流程。请问您是否能提供一些关于这个报错本身的解决思路呢？例如这个报错出现的原因可能是哪一方面问题造成的呢？在paddlepaddle3.0-beta版本的修改中是否是针对这方面的问题进行了改善呢？希望您能提供一些辅助我检查问题的方法或思路。再次感谢。

**Comment by LLee233** [comment]
@uniqlo1 Hi, we doubt it might be related to conflicts in multi-threading process, and we will start investigating it soon. Before fixing, you may refer to [here](https://github.com/PaddlePaddle/PaddleOCR/issues/8607#issuecomment-1347918923), reinitiating it when encountering issue instead of doing it in every inference, which should have be less impacted. Thanks.

**Comment by raoyutian** [comment]
这种问题一般是onednn的版本问题。
建议PaddleOCR2.7以上版本，Paddle2.6.1以上版本。
如果离线部署，建议使用[PaddleOCRSharp](https://gitee.com/raoyutian/PaddleOCRSharp),有C++,C# ,Python,go等语言可以调用，离线部署方便。

**Comment by DAAworld** [comment]
> 程序开始实例化paddleocr类，开启mkldnn加速 ![image](https://private-user-images.githubusercontent.com/153340967/349335333-58a88767-d9a8-492c-9dbf-f837dc3010e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzkyODIsIm5iZiI6MTczNTE3ODk4MiwicGF0aCI6Ii8xNTMzNDA5NjcvMzQ5MzM1MzMzLTU4YTg4NzY3LWQ5YTgtNDkyYy05ZGJmLWY4MzdkYzMwMTBlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMjA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDFlNTg5YmU1YmViZGQ5OWI3NjM1NDkzZTRlZDVhMmNkYWEyNGM1NDJhYjcxNjhjMjg0M2EwNmEyMGFlMGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jR_6HHWuMMJyBbj09nT-nEBmdT4vZ5Lt2TZnmmZBWko) 后循环执行对pdf文件的文字识别。 出现的问题是正常执行一个pdf文件的识别，报错一个，再正常执行一个，交替出现。 报错内容如下 ![image](https://private-user-images.githubusercontent.com/153340967/349335093-df959a28-3ec9-40ac-9da3-fe2d2446dfac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzkyODIsIm5iZiI6MTczNTE3ODk4MiwicGF0aCI6Ii8xNTMzNDA5NjcvMzQ5MzM1MDkzLWRmOTU5YTI4LTNlYzktNDBhYy05ZGEzLWZlMmQyNDQ2ZGZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMjA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTdhZmZlOTQxMGU2N2Q5YTI2ZjFkMjEzMDgzN2VkYmRlMmY0MDIzYjcxMjE3ZTg1NzE4ZTFiMDRiNDIyYzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aqQg-3OG_a0_YddcyudJX7XkeSQyHejz1Et4hkabH3M) 关闭mkldnn加速后没有此问题。修改为每次对pdf文件进行识别之前重新实例化paddleocr类，也无此问题。但这样解决会导致时间大幅增加。 更换最新的paddleocr2.8.0版本无法解决。 请问这个问题的出现是什么因素导致的，以及解决的思路。或有无除了mkldnn之外其他的cpu加速方式？

确实是的，交替出现。刚遇到

**Comment by zhanglirong1999** [comment]
@DAAworld ,Hi, 我尝试写了一个脚本复现，并未发现报错，脚本如下，是否能够帮忙查看与你的使用是否有区别，另外想请问一下使用的cpu型号，我在 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz ，Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz 等机型测试均通过，不知道是不是cpu型号过老引起的

```python
import os
import multiprocessing as mp
import paddleocr
from paddleocr import PPStructure
import logging
import cv2

logger = logging.getLogger(__name__)

class OCRProcessor(paddleocr.PaddleOCR):
    def __init__(self, use_gpu):
        num_cores = int(mp.cpu_count())
        use_num_cores = int(num_cores / 2)
        super().__init__(use_angle_cls=False, use_gpu=False, enable_mkldnn=True, cpu_threads=use_num_cores, use_mp=True, total_process_num=use_num_cores,
                         det_model_dir="/data/PaddlePaddle/pp_models/ch_PP-OCRv3_det_infer",
                         rec_model_dir="/data/PaddlePaddle/pp_models/ch_PP-OCRv3_rec_infer")

if __name__ == "__main__":
    img_folder_path = '/root/models/PaddleOCR/doc/imgs/'
    
    doc_img_list = [os.path.join(img_folder_path, f) for f in os.listdir(img_folder_path) if f.endswith(('png', 'jpg', 'jpeg', 'bmp'))]
    
    ocr_processor = OCRProcessor(False)
    
    for i, img_path in enumerate(doc_img_list):
        try:
            print('Image id', i)
            img = cv2.imread(img_path)
            ocr_processor.doc_img = img
            ocr_processor.bboxes_list, _ = ocr_processor.text_detector(ocr_processor.doc_img)
        except Exception as e:
            logger.error("errors %s happens %s", img_path, str(e))

```

测试过的paddleocr版本:
paddleocr                2.7.0.2
paddleocr                2.9.1

**Comment by DAAworld** [comment]
> @DAAworld ,Hi, 我尝试写了一个脚本复现，并未发现报错，脚本如下，是否能够帮忙查看与你的使用是否有区别，另外想请问一下使用的cpu型号，我在 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz ，Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz 等机型测试均通过，不知道是不是cpu型号过老引起的
> 
> ```python
> import os
> import multiprocessing as mp
> import paddleocr
> from paddleocr import PPStructure
> import logging
> import cv2
> 
> logger = logging.getLogger(__name__)
> 
> class OCRProcessor(paddleocr.PaddleOCR):
>     def __init__(self, use_gpu):
>         num_cores = int(mp.cpu_count())
>         use_num_cores = int(num_cores / 2)
>         super().__init__(use_angle_cls=False, use_gpu=False, enable_mkldnn=True, cpu_threads=use_num_cores, use_mp=True, total_process_num=use_num_cores,
>                          det_model_dir="/data/PaddlePaddle/pp_models/ch_PP-OCRv3_det_infer",
>                          rec_model_dir="/data/PaddlePaddle/pp_models/ch_PP-OCRv3_rec_infer")
> 
> if __name__ == "__main__":
>     img_folder_path = '/root/models/PaddleOCR/doc/imgs/'
>     
>     doc_img_list = [os.path.join(img_folder_path, f) for f in os.listdir(img_folder_path) if f.endswith(('png', 'jpg', 'jpeg', 'bmp'))]
>     
>     ocr_processor = OCRProcessor(False)
>     
>     for i, img_path in enumerate(doc_img_list):
>         try:
>             print('Image id', i)
>             img = cv2.imread(img_path)
>             ocr_processor.doc_img = img
>             ocr_processor.bboxes_list, _ = ocr_processor.text_detector(ocr_processor.doc_img)
>         except Exception as e:
>             logger.error("errors %s happens %s", img_path, str(e))
> ```
> 
> 测试过的paddleocr版本:
> 
> ```
> paddleocr                2.7.0.2
> paddleocr                2.9.1
> ```

改成使用--pre paddlepaddle-gpu版本，解决了这个问题。
