### ISSUE TITLE
是不是默认用所有的显卡进行训练的？

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#1340]

**Comment by LDOUBLEV** [comment]
可以通过export CUDA_VISIBLE_DEVICES="0,1,2,3"这样指定

**Comment by Zhangts98** [comment]
> 可以通过export CUDA_VISIBLE_DEVICES="0,1,2,3"这样指定

您好， 我使用源码在服务器上训练中文文本检测模型时，并没有指定 CUDA_VISIBLE_DEVICES，但我的每张gpu也都被占用了将近100%的资源， 我的 train_batch_size_per_card 设置为 64.
我查看官方api文档时，发现 with_data_parallel() 如果不指定places参数，则程序会自动获取当前可用设备的ID，而程序中也并没有指定, 请问是因为这个原因么？

**Comment by LDOUBLEV** [comment]
启动命令的时候可以设置使用哪些GPU训练，

python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1,2,3,4,5,6,7'

gpus是卡号
