### ISSUE TITLE
paddleocr:export onnx and inference error 

### ISSUE THREAD

**Issue by choococo** [PaddlePaddle/PaddleOCR#13410]
#### 问题描述 / Problem Description

paddleocr cls_model:use paddle2onnx export onnx model， running Error: onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running GlobalAveragePool node. Name:'p2o.GlobalAveragePool.18' Status Message: C:\a_work\1\s\onnxruntime\core/providers/cpu/nn/pool_attributes.h:105 onnxruntime::PoolAttributes::SetOutputSize input_shape.Size() > 0 || input_shape[0] == 0 was false. Invalid input shape. Only N can be zero. Got:{1,200,0,25}
#### 运行环境 / Runtime Environment
- OS: windows11
- Paddle: 2.6.1
- PaddleOCR: v3  v4

**Comment by GreatV** [comment]
please follow https://github.com/PaddlePaddle/Paddle2ONNX/issues/1330
