### ISSUE TITLE
求助！！！超级密集的文本行怎么检测，就是文本行之间近乎没有行距的这种类型

### ISSUE THREAD

**Issue by MvZpt** [PaddlePaddle/PaddleOCR#13427]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13426

<div type='discussions-op-text'>

<sup>Originally posted by **MvZpt** July 18, 2024</sup>
这种图片中近乎没有行距的文本怎么检测
![45](https://github.com/user-attachments/assets/25474c21-78ca-44d4-bdd3-0e68b4b0df80)
这是我提升亮度对比度之后的检测效果
![56_a](https://github.com/user-attachments/assets/1b4d891e-0523-43d5-982b-3e6db751f9b5)
</div>

**Comment by GreatV** [comment]
建议在自己的场景下，重新训练一下检测模型。

**Comment by MvZpt** [comment]
这就是在自己场景下训练的模型的预测结果，下图是大部分图的预测效果
![41](https://github.com/user-attachments/assets/a7537f99-a10b-4b0b-8e0d-caed04935720)
只要是文本行之间有行距的都能检测出来，这张图是所有测试集中表现最差的一张

**Comment by GreatV** [comment]
增加点数据量再试试
