### ISSUE TITLE
一张很简单的文字图片，使用命令行直接识别没问题，但是在代码中识别识别结果为空，不知道是哪里使用方式错了

### ISSUE THREAD

**Issue by weartist** [PaddlePaddle/PaddleOCR#13445]
#### 问题描述 / Problem Description
因为识别一整张图片多处文字准确率不高，我把一张大的图片文字区域提取成小一些的图片来分别识别，但很奇怪的是有一些图片识别之后直接返回None，但是通过命令行运行识别出的结果是没问题的

#### 运行环境 / Runtime Environment
- OS: Ubuntu
- Paddle: 2.6
- PaddleOCR: 2.6

#### 复现代码 / Reproduction Code

返回为None的情况代码如下：
```
ocr = PaddleOCR(use_angle_cls=True, lang="en")
results = ocr.ocr("test/test.png", cls=True)
print(results)
```

![image](https://github.com/user-attachments/assets/072945b0-2841-4823-b673-b92e27eab848)

直接在命令行识别，正确识别的命令如下：
![image](https://github.com/user-attachments/assets/dc52253b-a507-4f64-a503-42460bae7719)

#### 附件 / Appendix

原始图片：
![test](https://github.com/user-attachments/assets/df9b93f4-892d-4c3c-bf98-44011dd9b8e9)

**Comment by GreatV** [comment]
cli 里默认 ` use_angle_cls=False` 

```python
ocr = PaddleOCR(use_angle_cls=False, lang="en")
results = ocr.ocr("test/test.png", cls=False)
print(results)
```
这样修改，应该能获得和命令行一样的结果。

![result](https://github.com/user-attachments/assets/72ebcef4-b84f-4bf6-9f27-b11c28c560c5)

**Comment by weartist** [comment]
> cli 里默认 ` use_angle_cls=False`
> 
> ```python
> ocr = PaddleOCR(use_angle_cls=False, lang="en")
> results = ocr.ocr("test/test.png", cls=False)
> print(results)
> ```
> 
> 这样修改，应该能获得和命令行一样的结果。
> 
> ![result](https://private-user-images.githubusercontent.com/17264618/350744837-72ebcef4-b84f-4bf6-9f27-b11c28c560c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTE2NzgsIm5iZiI6MTcyMTYxMTM3OCwicGF0aCI6Ii8xNzI2NDYxOC8zNTA3NDQ4MzctNzJlYmNlZjQtYjg0Zi00YmY2LTlmMjctYjExYzI4YzU2MGM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAxMjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmM2NzRhMDUwODUwOWYxYTc3YzdmYTNhZDc2NDU5MWQwN2E0MjA4ZjVjYTY1NGJhYTgwYTY5MWY1ODczMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M6MfzkaPgsc4uRVgeLQJARTMlnlJgkFu8kNuFhQ7fF8)

可以了，十分感谢！
