### ISSUE TITLE
“乞丐”无法正确识别

### ISSUE THREAD

**Issue by Scott0902** [PaddlePaddle/PaddleOCR#13465]
#### 问题描述 / Problem Description
我使用paddleOCR识别某视频硬字幕时，视频中的“乞丐”两个字总是失败错误，变成：乞巧、乞正、乞写、乞与、乞平……
使用CPU和GPU识别的结果都是错的。
检测模型：ch_PP-OCRv4_det_infer
识别模型：ch_PP-OCRv4_rec_infer

是不是模型里没有收录“丐”字？

#### 运行环境 / Runtime Environment
- OS: Windows 11
- Paddle: 2.6.1
- PaddleOCR: 2.8.0
- PaddleOCR-gpu: 3.0.0b1

#### 复现条件
命令行运行
```
paddleocr --image_dir=xxxx.png --lang="ch" --use_gpu=True
```

#### 附件 / Appendix
![00_00_32_600__00_00_33_920](https://github.com/user-attachments/assets/6f4623bd-6cfa-4b87-b0eb-8c8a35175810)
![00_00_41_480__00_00_42_240](https://github.com/user-attachments/assets/6c7c1aea-6f96-4776-812a-d01469232040)

**Comment by jingsongliujing** [comment]
![image](https://github.com/user-attachments/assets/f2dcb5d4-8a50-47c6-af10-07b82f7dbc0b)
![image](https://github.com/user-attachments/assets/35c88674-29da-46be-b443-7040fd0888e8)
字典里是有这两个字的：https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/ppocr_keys_v1.txt，可能由于基础训练数据关于这连个字的数据较少，导致模型对这两个字误识别，需要相应的数据来进行微调和训练提高模型精度
