### ISSUE TITLE
表格识别，LSANet , 我训练自己的数据推理得到的框全局促在表格上半部分，哪里出问题了吗？val的指标都在0.8多了

### ISSUE THREAD

**Issue by deeplearningers** [PaddlePaddle/PaddleOCR#13469]
#### 运行环境 / Runtime Environment
- OS:
- Paddle:
- PaddleOCR:

**Comment by deeplearningers** [comment]
![360截图20240724083231](https://github.com/user-attachments/assets/323a79ae-1277-4654-8fa2-f740eb4055bf)

**Comment by GreatV** [comment]
运行环境是什么样的，用的配置文件是什么，推理的脚本是什么样的

**Comment by deeplearningers** [comment]
> 运行环境是什么样的，用的配置文件是什么，推理的脚本是什么样的

在windows下，python3.7 , paddle2.5.2, paddleocr2.6, 用的release2.8的代码，PPlabel标注数据用的release2.0。
期间遇到out of range问题，解决是按照如下链接修改了代码 https://github.com/PaddlePaddle/PaddleOCR/issues/11771

**Comment by deeplearningers** [comment]
> 运行环境是什么样的，用的配置文件是什么，推理的脚本是什么样的

我的问题没有解决啊，我以上表达的是改动过代码。问题还是如上图
