### ISSUE TITLE
DB检测网络的模型输入是3×640×640，但是对于一张尺寸为1152×2048的图片，测试时，经过前处理后图像尺寸仍是1152×2048.为什么经过前处理的图像尺寸和网络的输入尺寸不一致？

### ISSUE THREAD

**Issue by unyxs281** [PaddlePaddle/PaddleOCR#1346]

**Comment by unisoc281** [comment]
配置文件..reader.yml中test_image_shape是否必须要长宽都是32的倍数？det_mv3_db.yml中Global：image_shape=3*640*640。这个尺寸是网络模型的输入尺寸，但是为什么测试图片或训练图片不会缩放到这个尺寸，而是错放到长宽是32的倍数？

**Comment by WenmuZhou** [comment]
英文训练的时候是crop出来的640*640，这样可以保证每个batch内是一样的。预测的时候保留图片的长宽比，且不能crop

**Comment by MagicCodess** [comment]
同问

**Comment by MissPenguin** [comment]
1. 不是直接把输入图片resize到640*640，而是在random crop的时候crop出一个640*640的图像。
2. test_image_shape 要求是32的倍数是因为网络中有一些多次下采样然后elementwise add的操作，如果不是32的倍数，会因为下采样除不断产生1个像素的diff，导致elementwise add时报错。
