### ISSUE TITLE
表格识别，SLANet , 我训练自己的数据推理得到的框全局促在表格上半部分，哪里出问题了吗？val的指标都在0.8多了

### ISSUE THREAD

**Issue by deeplearningers** [PaddlePaddle/PaddleOCR#13471]
#### 问题描述 / Problem Description
在windows下，python3.7 , paddle2.5.2, paddleocr2.6, 用的release2.8的代码，PPlabel标注数据用的release2.0。
期间遇到out of range问题，按照如下链接修改过代码 https://github.com/PaddlePaddle/PaddleOCR/issues/11771
不知有没影响？

#### 运行环境 / Runtime Environment
- OS: windows
- Paddle: 2.5.2
- PaddleOCR: 2.6

**Comment by deeplearningers** [comment]
@GreatV

**Comment by deeplearningers** [comment]
推理脚本：python tools\train.py -c ../configs/table/SLANet_ch.yml

**Comment by crackso** [comment]
SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。

**Comment by crackso** [comment]
兄台，标题有错误LSANet ，是SLANet。
SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。

**Comment by crackso** [comment]
兄台，标题有错误LSANet ，是SLANet。
SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。

**Comment by deeplearningers** [comment]
> 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。

[table_structure_dict_ch.txt](https://github.com/user-attachments/files/16369764/table_structure_dict_ch.txt)
这是txt文件

**Comment by deeplearningers** [comment]
> 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。

[SLANet_ch.zip](https://github.com/user-attachments/files/16369767/SLANet_ch.zip)
这是yml文件

**Comment by deeplearningers** [comment]
> > 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。
> 
> [SLANet_ch.zip](https://github.com/user-attachments/files/16369767/SLANet_ch.zip) 这是yml文件

**Comment by crackso** [comment]
> > 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。
> 
> [table_structure_dict_ch.txt](https://github.com/user-attachments/files/16369764/table_structure_dict_ch.txt) 这是txt文件

这个文件是代码提供的，没修过过吧。看起来没问题。

**Comment by crackso** [comment]
> > > 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。
> > 
> > 
> > [SLANet_ch.zip](https://github.com/user-attachments/files/16369767/SLANet_ch.zip) 这是yml文件

训练文件好像也没问题

**Comment by crackso** [comment]
目前再排查下标注数据，自己这边有使用标注还原校验过吗？

**Comment by deeplearningers** [comment]
> 目前再排查下标注数据，自己这边有使用标注还原校验过吗？

老师，我这还原后跟标注是一样的，如附件，我打包了一张还原图，一张原图和标注文件gt.txt, 你能给看下问题出在哪里吗？这个bug我实在没找到啥原因了。
[Uploading test.zip…]()

**Comment by deeplearningers** [comment]
> > > 兄台，标题有错误LSANet ，是SLANet。 SLANet_ch.yml配置麻烦发下看看。还有table_structure_dict_ch.txt。
> > 
> > 
> > [table_structure_dict_ch.txt](https://github.com/user-attachments/files/16369764/table_structure_dict_ch.txt) 这是txt文件
> 
> 这个文件是代码提供的，没修过过吧。看起来没问题。

没修改过呢

**Comment by deeplearningers** [comment]
> > 目前再排查下标注数据，自己这边有使用标注还原校验过吗？
> 
> 老师，我这还原后跟标注是一样的，如附件，我打包了一张还原图，一张原图和标注文件gt.txt, 你能给看下问题出在哪里吗？这个bug我实在没找到啥原因了。 Uploading test.zip…

跟训练数据量有关系吗？我生成数据2000张单独训练，能稍微好点，但是也不准。
我用真实数据100多张，然后训练到过拟合，再用100多张中的其中一张预测，出现的局促在上半部分的情况。

**Comment by crackso** [comment]
> > 目前再排查下标注数据，自己这边有使用标注还原校验过吗？
> 
> 老师，我这还原后跟标注是一样的，如附件，我打包了一张还原图，一张原图和标注文件gt.txt, 你能给看下问题出在哪里吗？这个bug我实在没找到啥原因了。 Uploading test.zip…

文件没有传好呢。

**Comment by crackso** [comment]
#13489 这个是同个问题不，我们移步至那边讨论。

**Comment by deeplearningers** [comment]
> > > 目前再排查下标注数据，自己这边有使用标注还原校验过吗？
> > 
> > 
> > 老师，我这还原后跟标注是一样的，如附件，我打包了一张还原图，一张原图和标注文件gt.txt, 你能给看下问题出在哪里吗？这个bug我实在没找到啥原因了。 Uploading test.zip…
> 
> 文件没有传好呢。

[Uploading test.zip…]()

**Comment by deeplearningers** [comment]
> > > 目前再排查下标注数据，自己这边有使用标注还原校验过吗？
> > 
> > 
> > 老师，我这还原后跟标注是一样的，如附件，我打包了一张还原图，一张原图和标注文件gt.txt, 你能给看下问题出在哪里吗？这个bug我实在没找到啥原因了。 Uploading test.zip…
> 
> 文件没有传好呢。

[test.zip](https://github.com/user-attachments/files/16371708/test.zip)

**Comment by deeplearningers** [comment]
> #13489 这个是同个问题不，我们移步至那边讨论。

文件已经上传，是同一个项目问题。

**Comment by SWHL** [comment]
去 [Discussion](https://github.com/PaddlePaddle/PaddleOCR/discussions/13489)中 讨论吧，这里先关闭了。
