### ISSUE TITLE
训练r50_det模型卡住

### ISSUE THREAD

**Issue by james5551** [PaddlePaddle/PaddleOCR#1349]
训练r50_det模型，eval完后就卡住，内存占用为0，进程没有死掉，尝试修改队列数，进程数，batch大小，仍然有这种问题，请问怎么回事？

**Comment by LDOUBLEV** [comment]
训练的是哪个模型？ 每次都是eval完卡住吗？

**Comment by james5551** [comment]
您好，训练的r50_dbnet模型，每次eval完就会卡住

**Comment by LDOUBLEV** [comment]
更新代码到最新试下吧，最近修改了一些逻辑
