### ISSUE TITLE
如何只识别数字

### ISSUE THREAD

**Issue by l976308589** [PaddlePaddle/PaddleOCR#135]
我的业务场景是识别时间，使用了hub。
但是数字1经常被识别为英文l
数字5经常被识别为英文s
能否限定为只识别数字？

**Comment by MissPenguin** [comment]
如果您使用的超轻量模型，可以换通用大模型试试，但只需要识别时间的话，最好使用自己的数据重新训练一下，效果应该会好很多。

**Comment by LDOUBLEV** [comment]
> 我的业务场景是识别时间，使用了hub。
> 但是数字1经常被识别为英文l
> 数字5经常被识别为英文s
> 能否限定为只识别数字？

如果只是英文和数字的混淆，可以改一下字典文件试试，将英文的s改为5，英文的l改为1

**Comment by l976308589** [comment]
谢谢

**Comment by Matiz7** [comment]
问一下 字典文件是哪个
我的需求也是只识别数字，而且数字串是固定长度。这个如果能用正则表达式配置就最好了，想必速度会有提高

**Comment by tink2123** [comment]
英文字典：
https://github.com/PaddlePaddle/PaddleOCR/blob/ae2589b4d90825ce1a36cdbdd175570eae87f709/ppocr/utils/character.py#L29

**Comment by Matiz7** [comment]
多谢。
ocr = hub.Module(name="chinese_ocr_db_crnn")
我在本机运行后 C:\Users\abc\.paddlehub\modules这里下载生成了两个模型文件目录 chinese_ocr_db_crnn 和 chinese_text_detection_db
我想部署到服务器的话 这俩模型文件在代码里怎么指定路径 ？  不用每次开始都去重新下载

**Comment by MissPenguin** [comment]
> 多谢。
> ocr = hub.Module(name="chinese_ocr_db_crnn")
> 我在本机运行后 C:\Users\abc\.paddlehub\modules这里下载生成了两个模型文件目录 chinese_ocr_db_crnn 和 chinese_text_detection_db
> 我想部署到服务器的话 这俩模型文件在代码里怎么指定路径 ？ 不用每次开始都去重新下载

不需要管下载下来的模型，也不用再配模型路径，ocr = hub.Module(name="chinese_ocr_db_crnn")获取了模型之后，就可以直接用命令启动服务了：hub serving start -m chinese_ocr_db_crnn_mobile -p 8866，详情参考：https://github.com/PaddlePaddle/PaddleHub/tree/e2f81130d38f1f8ac1818a9f121384e6a1e9ec92/hub_module/modules/image/text_recognition/chinese_ocr_db_crnn_mobile#%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2

**Comment by MissPenguin** [comment]
不需要管下载下来的模型，也不用再配模型路径，ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")获取了模型之后，就可以直接用命令启动服务了：hub serving start -m chinese_ocr_db_crnn_mobile -p 8866，详情参考：https://github.com/PaddlePaddle/PaddleHub/tree/e2f81130d38f1f8ac1818a9f121384e6a1e9ec92/hub_module/modules/image/text_recognition/chinese_ocr_db_crnn_mobile#%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2

**Comment by gitcnbubble** [comment]
> > 我的业务场景是识别时间，使用了hub。
> > 但是数字1经常被识别为英文l
> > 数字5经常被识别为英文s
> > 能否限定为只识别数字？
> 
> 如果只是英文和数字的混淆，可以改一下字典文件试试，将英文的s改为5，英文的l改为1

修改字典后需要重新训练吗？还是可以直接使用？
可不可以在使用时临时指定当前识别任务使用的字典？
