### ISSUE TITLE
单机多卡训练需要配置哪些参数？有无demo

### ISSUE THREAD

**Issue by Ming-Zhou0201** [PaddlePaddle/PaddleOCR#1351]
export CUDA_VISIBLE_DEVICES=0,1
目前仅修改了这块

**Comment by LDOUBLEV** [comment]
就是通过export CUDA_VISIBLE_DEVICES=0,1控制使用那些GPU

**Comment by Ming-Zhou0201** [comment]
> 就是通过export CUDA_VISIBLE_DEVICES=0,1控制使用那些GPU
通过以下命令开始训练，日志报错如下
python3.7 tools/train.py -c configs/det/det_r50_vd_db.yml
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main()
  File "tools/train.py", line 103, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "/paddle-test/PycharmProjects/PaddleOCR_152/tools/program.py", line 299, in train_eval_det_run
    return_numpy=False)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1101, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1099, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1225, in _run_impl
    program._compile(scope, self.place)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 445, in _compile
    places=self._places)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 398, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ParallelExecutor::ParallelExecutor(std::vector<paddle::platform::Place, std::allocator<paddle::platform::Place> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, paddle::framework::Scope*, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, paddle::framework::details::ExecutionStrategy const&, paddle::framework::details::BuildStrategy const&, paddle::framework::ir::Graph*)
1   paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<paddle::platform::Place, std::allocator<paddle::platform::Place> > const&, ncclUniqueId*, unsigned long, unsigned long)
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
3   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Nccl error, unhandled system error  (at /paddle/paddle/fluid/platform/nccl_helper.h:118)

**Comment by Ming-Zhou0201** [comment]
单卡训练没有问题

**Comment by LDOUBLEV** [comment]
机器上没有安装[NCCL](https://developer.nvidia.com/nccl)吧：
```
wget https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb

dpkg -i nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb

sudo apt-get install -y libnccl2=2.3.7-1+cuda9.0 libnccl-dev=2.3.7-1+cuda9.0
```

**Comment by Ming-Zhou0201** [comment]
我试试 谢谢大佬
