### ISSUE TITLE
关于大量文本识别的内存占用过多的问题

### ISSUE THREAD

**Issue by chywwq** [PaddlePaddle/PaddleOCR#1352]
**环境**：Mac ，Paddle 2.0.0-rc0
**执行脚本**：`python3 tools/infer/predict_system.py --image_dir="./doc/imgs/$1" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True`
预测样本1：<img width="100" alt="wx" src="https://user-images.githubusercontent.com/1980853/101470191-a7dfef00-3980-11eb-8d5a-e9ff4cd8f821.png">
预测样本2：<img width="100" alt="ch" src="https://user-images.githubusercontent.com/1980853/101470181-a282a480-3980-11eb-9950-553b2b11f170.png">
样本1 是样本2的一部分。

**预测结果**
| 样本 | 行数 | 占用内存 |
| ---- | ---- | ---- |
| 样本1 | 18 | 4.22G |
| 样本2 | 44 | 3.2G |

**有两个问题**：
1、样本预测占用内存过多；
2、小样本占用内存比大样本占用内存多；

**Comment by chywwq** [comment]
请问下，计划在什么版本解决啊

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/38801c7f5e4fe1a99e49cd88169d8976f4b9feb4/tools/infer/utility.py#L242目前内存问题已经改善了一些，尝试在代码中加入此行代码：
