### ISSUE TITLE
使用PPOCRLabel标注表格，点击表格识别按钮无法生成表格文件

### ISSUE THREAD

**Issue by freezehe** [PaddlePaddle/PaddleOCR#13548]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

使用PPOCRLabel标注表格，点击表格识别按钮无法生成表格文件，cmd提示这个报错。
![image](https://github.com/user-attachments/assets/ea494435-662f-49a5-9ca7-997411453787)

### Environment

windows 10环境

(paddle_env0730) C:\WINDOWS\system32>pip freeze list
anyio==4.4.0
astor==0.8.1
beautifulsoup4==4.12.3
certifi==2024.7.4
charset-normalizer==3.3.2
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
Cython==3.0.10
decorator==5.1.1
exceptiongroup==1.2.2
fire==0.6.0
fonttools==4.53.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
imageio==2.34.2
imgaug==0.4.0
kiwisolver==1.4.5
lazy_loader==0.4
lmdb==1.5.1
lxml==5.2.2
matplotlib==3.9.1
networkx==3.3
numpy==1.26.4
opencv-contrib-python==4.10.0.84
opencv-python==4.10.0.84
opt-einsum==3.3.0
packaging==24.1
paddleocr==2.8.1
paddlepaddle==2.6.1
pillow==10.4.0
PPOCRLabel==2.1.3
protobuf==3.20.2
pyclipper==1.3.0.post5
pyparsing==3.1.2
PyQt5==5.15.11
PyQt5-Qt5==5.15.2
PyQt5_sip==12.15.0
python-dateutil==2.9.0.post0
python-docx==1.1.2
pywin32==306
PyYAML==6.0.1
rapidfuzz==3.9.5
requests==2.32.3
scikit-image==0.24.0
scipy==1.14.0
shapely==2.0.5
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
termcolor==2.4.0
tifffile==2024.7.24
tqdm==4.66.4
typing_extensions==4.12.2
urllib3==2.2.2
xlrd==1.2.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
please refer to: https://github.com/PFCCLab/PPOCRLabel/issues/39
