### ISSUE TITLE
RuntimeError: (PreconditionNotMet) PDNode's name should be unique

### ISSUE THREAD

**Issue by xhzh11** [PaddlePaddle/PaddleOCR#13555]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

python 3.8.0
paddleocr==2.6.1.0
paddlepaddle==2.6.1

ocr_engine = PaddleOCR(det_model_dir=det_model_dir,
                               lang='ch')
出现下面的问题应该怎么解决
                               
RuntimeError: (PreconditionNotMet) PDNode's name should be unique, get duplicate [layer_norm_fuse/layer_norm/]
  [Hint: Expected node_map_.count(name) == 0UL, but received node_map_.count(name): != 0UL:.] (at /paddle/paddle/fluid/framework/ir/graph_pattern_detector.cc:                               

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
please update your paddle version
to 3.0 beta.

**Comment by xhzh11** [comment]
> please update your paddle version to 3.0 beta.

Is it because the paddlepaddle version is too low？

**Comment by GreatV** [comment]
换一台电脑试试

**Comment by xhzh11** [comment]
> 换一台电脑试试

应该是环境的问题是吧

**Comment by GreatV** [comment]
@xhzh11 是的，应该是环境问题。

**Comment by xhzh11** [comment]
> @xhzh11 是的，应该是环境问题。

好的，感谢，我试一下
