### ISSUE TITLE
PPStructure引用不到报错

### ISSUE THREAD

**Issue by nimengxiao** [PaddlePaddle/PaddleOCR#13566]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

    from paddleocr import PPStructure,save_structure_res
ImportError: cannot import name 'PPStructure' from partially initialized module 'paddleocr' (most likely due to a circular import) 

### Environment

win10
python=3.8  
paddleocr=2.6.1.3

### Minimal Reproducible Example

import os
import cv2
from paddleocr import PPStructure,save_structure_res

table_engine = PPStructure(layout=False, show_log=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/table.jpg'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

### Additional

代码直接用的官网示例代码，引用的时候就报错。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SWHL** [comment]
欢迎提PR哈

**Comment by Gmgge** [comment]
@nimengxiao 经测试无法复现 测试环境为 win10，Python 3.8.19，paddleocr=2.6.1.3，请确认你的启动目录下是否存在paddleocr.py文件 导致引用出错？
