### ISSUE TITLE
文本检测模型是否不识别“杵”字

### ISSUE THREAD

**Issue by tiandao011** [PaddlePaddle/PaddleOCR#13560]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

我实验了几个文本检测模型，都无法识别“杵”字。其他字都能正常识别

### Environment

windows

### Minimal Reproducible Example

文本识别模型如下
rec_model_dir = 'ch_PP-OCRv4_rec_infer'
rec_model_dir = 'ch_PP-OCRv4_rec_server_infer'     
rec_model_dir = 'ch_PP-openatom_rec_svtrv2_ch_infer'

### Additional

no

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
可能需要微调一下

**Comment by SWHL** [comment]
@tiandao011 看到你勾选了愿意提交PR来修复该问题，期待你的PR哈

**Comment by UserWangZz** [comment]
检测模型不识别“杵”字？是检不到吗？

**Comment by raoyutian** [comment]
字典里有的文字，稍微微调训练下即可
