### ISSUE TITLE
ModuleNotFoundError: No module named 'ppocr'

### ISSUE THREAD

**Issue by oggyfaker** [PaddlePaddle/PaddleOCR#1358]
Hi , i got this error when i skip step 1 in installation by build docker and run this command : 
      python tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.checkpoints="./models/det_r50_vd_db/best_accuracy" Global.save_inference_dir="./inference/det_db"

How to convert model by this command without using Docker installation . I checked the training process , and it work normally , but Inference is error . Please help !

**Comment by LDOUBLEV** [comment]
1. Please update PaddleOCR code to the latest. 
2. Try the following command:
```
export PYTHONPAYH=.  &&  python tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.checkpoints="./models/det_r50_vd_db/best_accuracy" Global.save_inference_dir="./inference/det_db"
```

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
