### ISSUE TITLE
If your model has tps module:  TPS does not support variable shape.

### ISSUE THREAD

**Issue by shaoshenchen** [PaddlePaddle/PaddleOCR#1359]
AI Studio高级版，运行代码如图：
![image](https://user-images.githubusercontent.com/45918719/101559933-25e1db80-39fd-11eb-97b0-05b432844d7f.png)

**Comment by WenmuZhou** [comment]
拉取最新代码试一下

**Comment by shaoshenchen** [comment]
`git clone https://hug.fastgit.org/PaddlePaddle/PaddleOCR`  获取到的代码是最新的吗

**Comment by WenmuZhou** [comment]
不是，从github下载

**Comment by Maia97** [comment]
> 拉取最新代码试一下

最新代码加paddlepaddle2.0.0还是报错，请问还有什么解决办法吗

**Comment by shaoshenchen** [comment]
我今天尝试了一下最新代码，也还是上面的错误。
### 下面是文件的配置信息：
![image](https://user-images.githubusercontent.com/45918719/102153519-5bca0880-3eb2-11eb-9dd1-2a2c7f88ee10.png)
![image](https://user-images.githubusercontent.com/45918719/102153536-6389ad00-3eb2-11eb-8806-389360898453.png)
### 错误信息：
![Uploading image.png…]()

**Comment by LDOUBLEV** [comment]
目前问题已解决，更新代码到最新，如果有新的问题，可以开新的issue
