### ISSUE TITLE
是否可以公开一个只有数字的，一个只有数字+字母的超轻量模型。

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#136]
是否可以公开一个只有数字的，一个只有数字+字母的超轻量模型。

**Comment by MissPenguin** [comment]
只识别数字或数字+字母的模型，暂时无法提供，我们使用的训练工具已全部开源，可以按照教程组织数据自定义训练哈～

**Comment by SixGodGG** [comment]
> 只识别数字或数字+字母的模型，暂时无法提供，我们使用的训练工具已全部开源，可以按照教程组织数据自定义训练哈～

好
