### ISSUE TITLE
在paddleOCR的文档中，训练模型和推理模型有什么区别？

### ISSUE THREAD

**Issue by reBiocoder** [PaddlePaddle/PaddleOCR#13622]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

在paddleOCR的文档中，训练模型和推理模型有什么区别？以layoutXLM为例：推理模型是指：基于训练模型，再加xfund数据训练得到的模型，可以用于推理；训练模型是指：在微软layoutxlm-base的基础上，加xfund数据训练得到的预训练模型吗？
![image](https://github.com/user-attachments/assets/8824b41a-4a7f-41ea-8244-cd2fe47eb3fc)
不太理解这两个模型有什么区别？ 训练模型是可以替换微软layoutxlm-base的**预训练模型**？ 感谢解答，谢谢

### Environment

GPU：V-100

### Minimal Reproducible Example

在paddleOCR的文档中，训练模型和推理模型有什么区别？以layoutXLM为例：推理模型是指：基于训练模型，再加xfund数据训练得到的模型，可以用于推理；训练模型是指：在微软layoutxlm-base的基础上，加xfund数据训练得到的预训练模型吗？

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
训练模型是动态图模型，推理模型是静态图模型。

**Comment by reBiocoder** [comment]
> 训练模型是动态图模型，推理模型是静态图模型。

非常感谢！ 请问使用的预训练模型，还是微软的layoutxlm-base吗？
