### ISSUE TITLE
SVTR_HGNet not supported in SUPPORT_REC_MODEL(tag:2.8.1)

### ISSUE THREAD

**Issue by jnulzl** [PaddlePaddle/PaddleOCR#13652]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

我用tag 2.8.1版本测试SVTRv2识别算法，发现SVTRv2用的算法类型是[SVTR_HGNet ](https://github.com/PaddlePaddle/PaddleOCR/blob/v2.8.1/configs/rec/SVTRv2/rec_svtrv2_ch.yml#L40)，但是[SUPPORT_REC_MODEL ](https://github.com/PaddlePaddle/PaddleOCR/blob/v2.8.1/paddleocr.py#L82)中没有

### Environment

```
OS Ubuntu 18.04.6 LTS
CUDA 11.7

Python 3.8.0
paddleocr  2.8.1
paddlepaddle-gpu 2.6.1
```

### Minimal Reproducible Example

```python
import os
import sys
from paddleocr import PaddleOCR

rec_model_dir = "./openatom_rec_svtrv2_ch_infer" # https://paddleocr.bj.bcebos.com/openatom/openatom_rec_svtrv2_ch_infer.tar
rec_algorithm = "SVTR_HGNet" # https://github.com/PaddlePaddle/PaddleOCR/blob/v2.8.1/configs/rec/SVTRv2/rec_svtrv2_ch.yml#L40
ocr = PaddleOCR(use_angle_cls=True, lang="ch", rec_algorithm=rec_algorithm, rec_model_dir=rec_model_dir)
img_path = "IMG_PATH"
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
参考 https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_rec_svtrv2.md#4-%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2
