### ISSUE TITLE
PP-Structure文档分析 bbox排序 有bug存在

### ISSUE THREAD

**Issue by amzfc** [PaddlePaddle/PaddleOCR#13655]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

函数位置 ： paddleocr.ppstructure.recovery.recovery_to_doc.sorted_layout_boxes
#############################################################
        elif _boxes[i]["bbox"][0] > w / 4 and _boxes[i]["bbox"][2] > w / 2:
            _boxes[i]["layout"] = "double"
            res_right.append(_boxes[i])
            i += 1
#############################################################
问题描述：
    
    上传文档为单栏时，但是一行长标题被判别为双栏，从而被加到了res_right列表中。
     最后在合并的时候，先合并 res_left, 再合并res_right, 就会导致顺序错误。
     

### Environment

win 10  ，cpu

### Minimal Reproducible Example

def sorted_layout_boxes(res, w):
    """
    Sort text boxes in order from top to bottom, left to right
    args:
        res(list):ppstructure results
    return:
        sorted results(list)
    """
    num_boxes = len(res)
    if num_boxes == 1:
        res[0]["layout"] = "single"
        return res

    sorted_boxes = sorted(res, key=lambda x: (x["bbox"][1], x["bbox"][0]))

    _boxes = list(sorted_boxes)

    
    new_res = []
    res_left = []
    res_right = []
    i = 0

    while True:
        if i >= num_boxes:
            break
        if i == num_boxes - 1:
            if (
                _boxes[i]["bbox"][1] > _boxes[i - 1]["bbox"][3]
                and _boxes[i]["bbox"][0] < w / 2
                and _boxes[i]["bbox"][2] > w / 2
            ):
                new_res += res_left
                new_res += res_right
                _boxes[i]["layout"] = "single"
                new_res.append(_boxes[i])
            else:
                if _boxes[i]["bbox"][2] > w / 2:
                    _boxes[i]["layout"] = "double"
                    res_right.append(_boxes[i])
                    new_res += res_left
                    new_res += res_right
                elif _boxes[i]["bbox"][0] < w / 2:
                    _boxes[i]["layout"] = "double"
                    res_left.append(_boxes[i])
                    new_res += res_left
                    new_res += res_right
            res_left = []
            res_right = []
            break
        elif _boxes[i]["bbox"][0] < w / 4 and _boxes[i]["bbox"][2] < 3 * w / 4:
            _boxes[i]["layout"] = "double"
            res_left.append(_boxes[i])
            i += 1
        elif _boxes[i]["bbox"][0] > w / 4 and _boxes[i]["bbox"][2] > w / 2:
            _boxes[i]["layout"] = "double"
            res_right.append(_boxes[i])
            i += 1
        else:
            new_res += res_left
            new_res += res_right
            _boxes[i]["layout"] = "single"
            new_res.append(_boxes[i])
            res_left = []
            res_right = []
            i += 1
    if res_left:
        new_res += res_left
    if res_right:
        new_res += res_right

    return new_res

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
你好，可以提供几张图片给我们测试一下吗？

**Comment by amzfc** [comment]
经测试发现，应该是OCR识别结果 bbox问题,
[Uploading test.pdf…]()

错误识别结果：(左X识别过大）
{'type': 'title', 'bbox': [181, 242, 331, 271], 'res': [{'text': '第一条目的', '
{'type': 'title', 'bbox': [327, 95, 723, 128], 'res': [{'text': '未来集团有限公司师徒制管理规范（试行）
############################################################
def pdf_2_imgs(pdf_path:str):
    '''

    :param pdf_path: pdf文件路径
    :return:  list  ndarry集合
    '''
    fitz = try_import("fitz")
    imgs = []
    with fitz.open(pdf_path) as pdf:
        for pg in range(0, pdf.page_count):
            page = pdf[pg]
            mat = fitz.Matrix(2, 2)
            pm = page.get_pixmap(matrix=mat, alpha=False)

            # if width or height > 2000 pixels, don't enlarge the image
            if pm.width > 2000 or pm.height > 2000:
                pm = page.get_pixmap(matrix=fitz.Matrix(1, 1), alpha=False)

            img = Image.frombytes("RGB", [pm.width, pm.height], pm.samples)
            img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
            imgs.append(img)
    return imgs

if __name__ == '__main__':
  table_engine = PPStructure(....)
  imgs = pdf_2_imgs(img_path)
     for img in imgs:
         result = table_engine(img)
         h, w, _ = img.shape
         res = sorted_layout_boxes(result, w)
         for line in res:
           line.pop('img')
           print(line)

**Comment by GreatV** [comment]
@amzfc 老哥你这文档没有上传成功。

**Comment by amzfc** [comment]
[test.pdf](https://github.com/user-attachments/files/16620068/test.pdf)

**Comment by GreatV** [comment]
没有复现出来。

```python
import os
import cv2
from paddleocr import PPStructure,save_structure_res
from paddleocr import sorted_layout_boxes, convert_info_docx
from paddle.utils import try_import
from PIL import Image
import numpy as np

# 中文测试图
table_engine = PPStructure(recovery=True)
# 英文测试图
# table_engine = PPStructure(recovery=True, lang='en')

img_path = 'test.pdf'

fitz = try_import("fitz")

imgs = []
with fitz.open(img_path) as pdf:
    for pg in range(0, pdf.page_count):
        page = pdf[pg]
        mat = fitz.Matrix(2, 2)
        pm = page.get_pixmap(matrix=mat, alpha=False)

        # if width or height > 2000 pixels, don't enlarge the image
        if pm.width > 2000 or pm.height > 2000:
            pm = page.get_pixmap(matrix=fitz.Matrix(1, 1), alpha=False)

        img = Image.frombytes("RGB", [pm.width, pm.height], pm.samples)
        img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
        imgs.append(img)

save_folder = './output'
img_path = './test.pdf'
img = imgs[0]
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

h, w, _ = img.shape
res = sorted_layout_boxes(result, w)
convert_info_docx(img, res, save_folder, os.path.basename(img_path).split('.')[0])

```
[test_ocr.docx](https://github.com/user-attachments/files/16631817/test_ocr.docx)
