### ISSUE TITLE
使用det模型检测文本奇怪退出

### ISSUE THREAD

**Issue by zhanghengjiayou** [PaddlePaddle/PaddleOCR#13658]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

使用det模型检测文本，执行到input_tensor.copy_from_cpu(img)没有报错，直接退出
系统 Windows 
显存 2G
模型 ch_PP-OCRv2_det_infer
paddle-gpu 2.4.2
paddleocr 2.6.1

### Environment

系统 Windows 
显存 2G
模型 ch_PP-OCRv2_det_infer
paddle-gpu 2.4.2
paddleocr 2.6.1

### Minimal Reproducible Example

            img, shape_list = data
            if img is None:
                return None, 0
            img = np.expand_dims(img, axis=0)
            shape_list = np.expand_dims(shape_list, axis=0)
            img = img.copy()
            self.input_tensor.copy_from_cpu(img)

### Additional

无

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Gmgge** [comment]
你是否方便升级到最新的paddleocr以进行测试？
