### ISSUE TITLE
在用windows环境进行编译时

### ISSUE THREAD

**Issue by ZCCFighting** [PaddlePaddle/PaddleOCR#1366]
参考上述博客https://blog.csdn.net/qq_37735796/article/details/108015905
最后进行全部生成报错
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 _calloc_dbg	D:\zcc\OCR\PaddleOCR\deploy\cpp_infer	D:\zcc\OCR\PaddleOCR\deploy\libcpmtd.lib(xlocale.obj)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 _CrtIsValidHeapPointer，该符号在函数 "private: bool __cdecl Concurrency::details::SubAllocator::InitAndCheckBlockOnAlloc(union Concurrency::details::AllocationEntry *,unsigned __int64)" (?InitAndCheckBlockOnAlloc@SubAllocator@details@Concurrency@@AEAA_NPEATAllocationEntry@23@_K@Z) 中被引用	D:\zcc\OCR\PaddleOCR\deploy\cpp_infer	D:\zcc\OCR\PaddleOCR\deploy\libconcrtd.lib(SubAllocator.obj)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(clipper.obj 中)	D:\zcc\OCR\PaddleOCR\deploy\cpp_infer	D:\zcc\OCR\PaddleOCR\deploy\libpaddle_fluid.lib(api.obj)	1	
等错误 有没有大佬遇到过，帮忙看下，多谢

**Comment by littletomatodonkey** [comment]
编译的时候编译选项使用RelWithDebuginfo看下呢？

**Comment by ZCCFighting** [comment]
> 编译的时候编译选项使用RelWithDebuginfo看下呢？

好的多谢，我试试看

**Comment by liyandongpy** [comment]
同样遇到这个问题。
