### ISSUE TITLE
nvidia tesla p100 显卡乱码

### ISSUE THREAD

**Issue by zuanzuanshao** [PaddlePaddle/PaddleOCR#13689]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

使用mineru里面的gpu加速，里面用的paddleocr模块，识别都乱码。cuda和驱动都跑过两遍，查询显卡后发现比较旧，为2016发布的显卡，如果想识别效果正常的话，需要怎么做呢

### 🏃‍♂️ Environment (运行环境)

```
ubuntu 24.04
python 3.10.14
paddlaocr 2.7.3
paddlepaddle-gpu 3.0.0b1
nvidia tesla p100
cuda 12.2
Driver Version: 535.183.0
```
<img width="928" alt="image" src="https://github.com/user-attachments/assets/916ea376-d7e2-499e-9454-f9478c47684e">

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

magic-pdf -p 5G保证ADAS、自动驾驶系统安全可靠地运行.pdf -m ocr
和mineru作者沟通说让我来paddleocr反馈一下。
使用的cuda加速，ocr模式。
[5G保证ADAS、自动驾驶系统安全可靠地运行.pdf](https://github.com/user-attachments/files/16648843/5G.ADAS.pdf)

**Comment by GreatV** [comment]
建议使用较新的gpu，paddle框架对于旧的gpu会有兼容性问题。

**Comment by zuanzuanshao** [comment]
好的，感谢解答。
