### ISSUE TITLE
安卓demo中，v4识别和v2v3对英文数字文本识别结果有明细差异

### ISSUE THREAD

**Issue by TrioTea** [PaddlePaddle/PaddleOCR#13719]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

保持文本检测模型不变，调整文本识别模型
在英文和数字混合文本上，例如“A21D5BB562432798”
v2和v3基本可以正确识别，但V4的识别结果往往只有“A21D5”，也就是文本的前几位

在中文识别上，V4模型的表现没有问题

模型使用https://paddlepaddle.github.io/PaddleOCR/ppocr/model_list.html
ch_PP-OCRv4_rec ch_PP-OCRv3_rec ch_PP-OCRv2_rec

不知道问题出现在哪里，也定位过文本检测的结果，分割是没有问题的

### 🏃‍♂️ Environment (运行环境)

安卓14环境
使用PaddleLite1.4版本

**Comment by GreatV** [comment]
在本地用python是正常的吗

**Comment by TeaWu** [comment]
> 在本地用python是正常的吗

Python运行后识别结果是正确的
