### ISSUE TITLE
表格标注生成的gt.txt文件里面的gt属性值html页面表格样式不匹配的bug

### ISSUE THREAD

**Issue by freezehe** [PaddlePaddle/PaddleOCR#13752]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

各位老师好，我在标注表格的时候发现一个问题麻烦帮忙解答一下。我标注的是一个简单的表格，在学习完了表格标注培训视频，参考着标注，顺序也调整正确，生成的gt.txt里面的gt的属性值，我复制粘贴到一个txt文本转为html页面查看的时候，发现表格没有对应上样式。我贴一下我上述涉及到的图片和标注文件gt.txt
[gt.txt](https://github.com/user-attachments/files/16746528/gt.txt)
![image](https://github.com/user-attachments/assets/1538ae82-0d63-4657-a3c2-e3684ef01cec)
![image](https://github.com/user-attachments/assets/00f0fb20-4d27-4e1d-8db9-78097153b914)
我想问一下，这个是不是一个bug？因为gt的属性值对应的是html页面，没有跟表格样式对应上。

### 🏃‍♂️ Environment (运行环境)

windows
PPOCRLabel 标注

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

{"filename": "2.jpg", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td", " rowspan=\"8\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["实", "际", "压", "力", "值", "（", "b", "a", "r", ")"], "bbox": [[61, 12], [219, 12], [219, 32], [61, 32]]}, {"tokens": ["被", "校", "仪", "器", "示", "值", "（", "b", "a", "r", "）"], "bbox": [[323, 12], [501, 12], [501, 32], [323, 32]]}, {"tokens": ["测", "量", "不", "确", "定", "度", "（", "k", "=", "2", ")"], "bbox": [[591, 12], [775, 12], [775, 32], [591, 32]]}, {"tokens": ["-", "1", ".", "0", "0", "0"], "bbox": [[116, 39], [173, 39], [173, 61], [116, 61]]}, {"tokens": ["-", "0", ".", "9", "9", "1"], "bbox": [[388, 38], [443, 38], [443, 59], [388, 59]]}, {"tokens": ["U", "r", "e", "l", "=", "0", ".", "0", "7", "%"], "bbox": [[640, 122], [736, 122], [736, 147], [640, 147]]}, {"tokens": ["0", ".", "0", "0", "0"], "bbox": [[119, 67], [170, 67], [170, 89], [119, 89]]}, {"tokens": ["0", ".", "0", "1", "1"], "bbox": [[390, 67], [440, 67], [440, 88], [390, 88]]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [[120, 95], [170, 95], [170, 117], [120, 117]]}, {"tokens": ["1", ".", "0", "1", "0"], "bbox": [[392, 95], [442, 95], [442, 117], [392, 117]]}, {"tokens": ["2", ".", "0", "0", "0"], "bbox": [[119, 121], [171, 121], [171, 147], [119, 147]]}, {"tokens": ["2", ".", "0", "1", "1"], "bbox": [[391, 123], [440, 123], [440, 145], [391, 145]]}, {"tokens": ["3", ".", "0", "0", "0"], "bbox": [[119, 151], [170, 151], [170, 173], [119, 173]]}, {"tokens": ["3", ".", "0", "1", "2"], "bbox": [[390, 151], [441, 151], [441, 173], [390, 173]]}, {"tokens": ["4", ".", "0", "0", "0"], "bbox": [[119, 177], [170, 177], [170, 200], [119, 200]]}, {"tokens": ["4", ".", "0", "1", "2"], "bbox": [[391, 179], [441, 179], [441, 201], [391, 201]]}, {"tokens": ["5", ".", "0", "0", "0"], "bbox": [[120, 206], [170, 206], [170, 228], [120, 228]]}, {"tokens": ["5", ".", "0", "1", "2"], "bbox": [[391, 206], [441, 206], [441, 228], [391, 228]]}]}, "gt": "<html><body><table><tbody><tr><td></td><td></td><td>实际压力值（bar)</td></tr><tr><td>被校仪器示值（bar）</td><td>测量不确定度（k=2)</td><td rowspan=\"8\">-1.000</td></tr><tr><td>-0.991</td><td>Urel=0.07%</td></tr><tr><td>0.000</td><td>0.011</td></tr><tr><td>1.000</td><td>1.010</td></tr><tr><td>2.000</td><td>2.011</td></tr><tr><td>3.000</td><td>3.012</td></tr><tr><td>4.000</td><td>4.012</td></tr><tr><td>5.000</td><td>5.012</td></tr></tbody></table></body></html>"}

**Comment by GreatV** [comment]
PPOCRLabel 相关的问题建议反馈到 https://github.com/PFCCLab/PPOCRLabel
