### ISSUE TITLE
编译CMakeLists时报错

### ISSUE THREAD

**Issue by CoderMaurice** [PaddlePaddle/PaddleOCR#1375]
![image](https://user-images.githubusercontent.com/22311615/101717256-e6d58800-3ad9-11eb-8840-138017d73619.png)

拿到自己的项目里编译时报错
谷歌了一下，说要在这里加-fuse-ld=lld
set(CMAKE_SHARED_LINKER_FLAGS
        "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--gc-sections -Wl,-z,nocopyreloc")
尝试了一下依然无法成功
对编译指令不是很了解
请教下要怎么改

**Comment by LDOUBLEV** [comment]
更新代码到最新即可

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
