### ISSUE TITLE
方向分类器问题

### ISSUE THREAD

**Issue by huzheng1111** [PaddlePaddle/PaddleOCR#1376]
将训练好的方向分类器集成到ocr模型，即使已经设置了方向分类器不校正图片角度，也会导致文字识别模型识别不到任何文字，但是设置不使用方向分类器就可以识别到文字。已经将模型在使用方向分类器和不使用方向分类器传给文字识别模型的图片设置为一致，但是使用了方向分类器的同一个图片就完全识别不到文字

**Comment by WenmuZhou** [comment]
设置不矫正是用的whl包吗

**Comment by huzheng1111** [comment]
> 设置不矫正是用的whl包吗

不是，是在predict_rec文件里注释掉了旋转图片的代码，用的predict_system来识别文字的

**Comment by WenmuZhou** [comment]
把小图片保存下来，单独跑分类，看看分类前后图片有没有diff

**Comment by huzheng1111** [comment]
> 把小图片保存下来，单独跑分类，看看分类前后图片有没有diff
我有把det模型输出的图片和cls输出的图片保存下来，他们完全一样

**Comment by WenmuZhou** [comment]
> > 把小图片保存下来，单独跑分类，看看分类前后图片有没有diff
> > 我有把det模型输出的图片和cls输出的图片保存下来，他们完全一样
然后，det输出的图片拿去识别没问题，cls的图片拿去识别不出来吗？这不应该啊

**Comment by huzheng1111** [comment]
> 把小图片保存下来，单独跑分类，看看分类前后图片有没有diff
> 我有把det模型输出的图片和cls输出的图片保存下来，他们完全一样
> 然后，det输出的图片拿去识别没问题，cls的图片拿去识别不出来吗？这不应该啊
det输出的图片和cls输出的图片单独使用predict_rec都可以识别出来，但是只要最后图片有通过方向分类器，即使完全不使用cls输出的图片，把det输出的图片使用copy.deepcopy()深拷贝给识别模型，识别模型也识别不出来

**Comment by huzheng1111** [comment]
predict_system做文字识别的时候，设置use_zero_copy_run为true,同时使用方向分类器就会导致文字全部识别不出来，同时batch_size设置为4，但是识别模型返回的decoded_output shape为[1,1]，设置use_zero_copy_run为false,同时使用方向分类器就能够识别出文字
