### ISSUE TITLE
PP-OCRv4模型无法识别提取“琤”字

### ISSUE THREAD

**Issue by githubwyj** [PaddlePaddle/PaddleOCR#13767]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

我这边在做ocr识别过程中，用的PP-OCRv4模型，发现“琤”这个字无法提取，后面我用官方的demo试了，也一样，如图：
![image](https://github.com/user-attachments/assets/b9ce05a5-08c0-4910-9156-011583ccc170)

### 🏃‍♂️ Environment (运行环境)

无

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

https://aistudio.baidu.com/community/app/91660/webUI

![微信截图_20240828180049](https://github.com/user-attachments/assets/092450ba-6745-4027-9b54-8221e90e0001)

**Comment by Topdu** [comment]
字典列表中没有这个字，可以查看支持的字符：https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/ppocr_keys_v1.txt
