### ISSUE TITLE
同样的参数和模型C++推理预测的结果与python版本预测效果差太多

### ISSUE THREAD

**Issue by BiggerBinBin** [PaddlePaddle/PaddleOCR#1378]
在paddle rc2.0框架下训练的同样的模型。在python有90%以上的准确率，在c++全是1，a，p。全是错误的。放到paddleLabel标注软件上自动标注，跟在c++的预测一样，全是1,a,p识别错误。是跟什么有关系吗？与版本有关系还是？

**Comment by LDOUBLEV** [comment]
和训练的模型有关系，检查下你的字典是不是对的，C++目前只支持DB + CRNN的组合
