### ISSUE TITLE
Unreasonable term in PaddlePaddle Contributor License Agreement

### ISSUE THREAD

**Issue by umarbutler** [PaddlePaddle/PaddleOCR#13781]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

The final term of the [PaddlePaddle Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleOCR) states:
9. PaddlePaddle reserves the right to update or change this Agreement at any time, by posting the most current version of the Agreement on PaddlePaddle, with a new Effective Date shown on Dec. 9th, 2019. All such changes in the Agreement are effective from the Effective Date. **Your continued use of PaddlePaddle after we post any such changes signifies your agreement to those changes.** If you do not agree to the then-current Agreement, you must immediately discontinue using PaddlePaddle. [Emphasis added]

This would seem to imply that, under the terms of the license agreement, it would be possible for PaddlePaddle to update the Contributor License Agreement to no longer grant itself a non-exclusive license but instead convert that into an exclusive license (ie, contributors would become unable to use the code they contribute themselves) or otherwise modify the license in such a way that would be regarded as unreasonable to most, and that change would then effectively become binding upon anyone who continues to make use of PaddlePaddle, unless they 'immediately discontinue' usage at the time that the agreement is updated.

Are there any plans to modify the agreement to exclude that term? I do not assume that it is intentionally unreasonable, I only wish to point out that it has the potential for exposing contributors to an unacceptable level of legal risk. I personally would not be comfortable with signing the agreement until that term is removed.

### 🏃‍♂️ Environment (运行环境)

N/A

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

N/A

**Comment by jzhang533** [comment]
@umarbutler Thanks for pointing out this. To be honest, I've never thoroughly read the full CLA document. I will learn about the history and considerations behind the CLA document from those I believe responsible.

**Comment by jzhang533** [comment]
@umarbutler I am still in the journey of explaining/convincing various people to update CLA. It may take more time, will get back to you once consensus is made.

**Comment by jzhang533** [comment]
@umarbutler the team has updated the CLA, here is the revision: https://gist.github.com/XiaoguangHu01/75018ad8e11af13df97070dd18ae6808/revisions, thanks again.

**Comment by umarbutler** [comment]
Hey @jzhang533, thanks for making that change, I think the revised terms are far more reasonable :)
