### ISSUE TITLE
fine tune精调 broadcast dimension mismatch

### ISSUE THREAD

**Issue by longshifeng** [PaddlePaddle/PaddleOCR#1379]
已经确保使用了最新的代码，
基于DB mv3 v1.1训练 
预训练模型MobileNetV3_large_x0_5_pretrained/

> paddlepaddle 2.0.0rc0
> paddleocr 1.1.1
> img shape 3,720,1056

数据集形式：
![3` 4~ATIK17OIHFKT9OP)D4](https://user-images.githubusercontent.com/32770755/101742746-865c4000-3b05-11eb-9a89-340e1b3291ac.png)

det_mv3_db_v1.1.yml如下：
![image](https://user-images.githubusercontent.com/32770755/101741154-af300580-3b04-11eb-911c-aa0df2989f38.png)

det_db_icdar15_reader.yml如下：
![image](https://user-images.githubusercontent.com/32770755/101741246-cec72e00-3b04-11eb-84d1-2da810ccc5d3.png)
 
运行命令：
`python tools/train.py -c configs/det/det_mv3_db_v1.1.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/ 2>&1 | tee train_det.log`

错误提示：
![image](https://user-images.githubusercontent.com/32770755/101741371-eef6ed00-3b04-11eb-97a1-854fdb855f6a.png)

其他配置文件未更改。。

**Comment by LDOUBLEV** [comment]
image_shape [3, 720, 1056]，设置为32倍数试试，比如[3, 704, 1056]

**Comment by longshifeng** [comment]
> image_shape [3, 720, 1056]，设置为32倍数试试，比如[3, 704, 1056]

实在抱歉，一直以为720是32的倍数，所以就调整了高。。感谢不厌其烦。
