### ISSUE TITLE
请问如何返回识别图像中单独字符的位置吗

### ISSUE THREAD

**Issue by fdh0** [PaddlePaddle/PaddleOCR#138]
![Img](https://i.imgur.com/01iLdXo.png)
例如上面图像，我想得到每个字符的位置，怎么处理呢

**Comment by SixGodGG** [comment]
估计不行，等官方回复

**Comment by dyning** [comment]
因为CRNN是行识别，不是基于字符识别，所以无法获得每个字符的位置。需要每个字符的位置的目的是？

**Comment by fdh0** [comment]
> 因为CRNN是行识别，不是基于字符识别，所以无法获得每个字符的位置。需要每个字符的位置的目的是？

谢谢回答，我们是传统的机器视觉，对于某些粘连字符，或者宽度不均匀的字符，传统的处理不是很好。但就目前而言，传统方法具有CPU的<10ms识别，以及添加学习的功能，所以，我们想利用深度学习，优化我们的传统学习。

**Comment by fdh0** [comment]
还有人回答吗

**Comment by LDOUBLEV** [comment]
> 还有人回答吗

抱歉，旧的issue里可能回复不及时。
目前基于深度学习文本数据都是按 行 标注，识别也是以 行 为单位，除非你的标注数据是字符级的，可以检测识别单个字符的位置和具体文本。

或者按照检测到的框和识别到的文本的字符数量，去估计每个字符的位置，但是对宽度不均匀的字符不太友好

**Comment by qq61786631** [comment]
这个需求tesseract可能比较合适，但是误报概率高
