### ISSUE TITLE
应用程序无法正常启动,显示错误代码0xc0000142

### ISSUE THREAD

**Issue by yimuchunshu** [PaddlePaddle/PaddleOCR#13808]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![isue](https://github.com/user-attachments/assets/b7cd2dc5-c106-4863-955b-6391be5d51f7)
本机上可以运行，拷贝到其他机器上，出现这个问题，如何解决

### 🏃‍♂️ Environment (运行环境)

win11

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

按着官方编译好之后复制到其他机器 上出现问题

**Comment by GreatV** [comment]
写得太抽象了，无法复现。

**Comment by yimuchunshu** [comment]
![image](https://github.com/user-attachments/assets/5dc92ffc-dbe0-4867-95f5-2acdd83b9fe1)
就是把编译好的程序拷贝到其他机器上，无法运行，出现上面错误

**Comment by XiaoDongGuoGuo** [comment]
可能少了运行时依赖库
