### ISSUE TITLE
Windows cpp_infer 生成dll时的依赖问题

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#1381]
Windows cpp_infer 生成dll工程
1. 可以通过直接exe工程转dll工程吗？
2.如果自己创建dll工程，怎么将所需要的头文件、库快速的应用到项目中而不是一条一条复制过去
还请各位大佬指教一下

**Comment by TingquanGao** [comment]
可以参考一下这个：
https://zhuanlan.zhihu.com/p/145446681
