### ISSUE TITLE
CPU版本编译生成exe后运行出现应用程序无法正常运行（0xc0000142）

### ISSUE THREAD

**Issue by yimuchunshu** [PaddlePaddle/PaddleOCR#13814]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

PaddleOCR-release-2.6
paddle_inference_cpu_avx_mkl
opencv4.8.0
VS2019
WIN11

### 🏃‍♂️ Environment (运行环境)

PaddleOCR-release-2.6
paddle_inference_cpu_avx_mkl
opencv4.8.0
VS2019
WIN11

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

![image](https://github.com/user-attachments/assets/3eebc98c-71a6-4460-a11b-915aca042208)

**Comment by GreatV** [comment]
检查一下是不是缺少什么运行时
