### ISSUE TITLE
编译cpp_infer生成的ppocr项目只能支持release(因为推理库里的lib全是release的) 能提供debug版本支持吗

### ISSUE THREAD

**Issue by burning-star-x** [PaddlePaddle/PaddleOCR#13822]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

编译cpp_infer生成的ppocr项目只能支持release 使用debug模式的话 推理库里面glog等几个第三方的静态lib是release版的,不能支持debug模式运行ppocr 能不能提供对debug模式的支持

### 🏃‍♂️ Environment (运行环境)

win10 vs2022

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

![2024-09-05_02-39-29](https://github.com/user-attachments/assets/135968fa-d73b-4ce4-9a32-ce00653f43ad)

**Comment by GreatV** [comment]
可以尝试自己编译一份，使用paddle框架主仓库中的代码就可以。
