### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by savio1999** [PaddlePaddle/PaddleOCR#13828]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

, error happened with msg: Traceback (most recent call last):
File "/app/PaddleOCR/ppocr/data/simple_dataset.py", line 162, in getitem
outs = transform(data, self.ops)
File "/app/PaddleOCR/ppocr/data/imaug/init.py", line 71, in transform
data = op(data)
File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 59, in call
self.draw_border_map(text_polys[i], canvas, mask=mask)
File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 83, in draw_border_map
padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range

### 🏃‍♂️ Environment (运行环境)

ubuntu,t4 16gb

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

detector training

**Comment by GreatV** [comment]
please try our main branch

**Comment by savio1999** [comment]
tried on the main branch same issue

**Comment by GreatV** [comment]
please post more details, such as config file，dataset
