### ISSUE TITLE
按照官方文档识别pdf报错

### ISSUE THREAD

**Issue by memedacn** [PaddlePaddle/PaddleOCR#13832]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

图片可以，pdf不行。报错如下：
![微信图片_20240906140410](https://github.com/user-attachments/assets/de2ef720-dfdf-4bcf-8cc4-4fe221b390e6)

### 🏃‍♂️ Environment (运行环境)

deepin,ubuntu都试过了，一样的问题

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

paddleocr --image_dir ./xxx.pdf --use_angle_cls true --use_gpu false --page_num 2

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
