### ISSUE TITLE
验证集loss

### ISSUE THREAD

**Issue by lvyulv** [PaddlePaddle/PaddleOCR#1384]
请问paddleOCR的验证集是否为 train_data/test ？验证集的loss（类似于val_loss）是不打印到log的吗？训练过程中train的loss基本不变，acc值上升是什么原因呢？

**Comment by tink2123** [comment]
> 请问paddleOCR的验证集是否为 train_data/test

是的

> 验证集的loss（类似于val_loss）是不打印到log的吗？

验证集不会打印loss，只会计算acc。

>训练过程中train的loss基本不变，acc值上升是什么原因呢？

应该不会的，loss可能是在波动，或者下降较慢，可以多观察几个epoch，看下整体趋势

**Comment by lvyulv** [comment]
> 
> 
> > 请问paddleOCR的验证集是否为 train_data/test
> 
> 是的
> 
> > 验证集的loss（类似于val_loss）是不打印到log的吗？
> 
> 验证集不会打印loss，只会计算acc。
> 
> > 训练过程中train的loss基本不变，acc值上升是什么原因呢？
> 
> 应该不会的，loss可能是在波动，或者下降较慢，可以多观察几个epoch，看下整体趋势

好的谢谢！
我的训练数据是5w张图，验证数据是2w，目前训练acc达到了0.96，测试test_acc达到了0.94，loss停留在80左右。请问这个loss值是合理的吗？还是要降到1左右才合理？

**Comment by LDOUBLEV** [comment]
80 左右的loss是合理的，acc符合预期即可
