### ISSUE TITLE
自己训练的paddleocr模型转成onnx后利用cpu推理速度下降很多，求解决方案

### ISSUE THREAD

**Issue by GGGame1** [PaddlePaddle/PaddleOCR#13856]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

在官网模型基础上进行训练，随着训练数据量的堆叠，导出的onnx模型在cpu上推理速度越来越慢,通过调整GraphOptimizationLevel可以适当加速，但是依旧较慢
使用官网模型导出成onnx在cpu上推理速度如下：
![image](https://github.com/user-attachments/assets/8fe85cb1-4476-4d70-9388-71572ed0c5fa)
使用训练后的模型导出成onnx在cpu上推理速度如下(GraphOptimizationLevel默认为ORT_ENABLE_ALL)：
![image](https://github.com/user-attachments/assets/89df95ab-0b8f-48a4-aa76-0fd1a12611f5)
使用训练后的模型导出成onnx在cpu上推理速度如下(GraphOptimizationLevel改为ORT_ENABLE_EXTENDED或者ORT_ENABLE_BASE)：
![image](https://github.com/user-attachments/assets/2a473c9f-b3e6-4b98-8b40-63f0196e2604)

已经尝试过通过更改opset_version10，11等各种版本依旧没有效果

且通过netron查看模型结构，模型结构也一致

### 🏃‍♂️ Environment (运行环境)

Ubuntu20.04.6 LTS 
PP-OCRv4
PaddleOCR-2.7.0

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

训练命令为：python3 tools/train.py -c configs/rec/PP-OCRv4/en_PP-OCRv4_rec.yml

模型导出命令为：python tools/export_model.py -c /train_dataset/05_ocr_rec_dataset/01_bp_ocr_zf_dataset_V3/trian_PP-OCRv4_rec_ocr_kd.yml -o Global.pretrained_model=/train_dataset/05_ocr_rec_dataset/01_bp_ocr_zf_dataset_V3/model_output/rec_ppocr_v4/best_accuracy  Global.save_inference_dir=/train_dataset/05_ocr_rec_dataset/01_bp_ocr_zf_dataset_V3/model_output/inference

转成onnx命令为：paddle2onnx --model_dir /train_dataset/05_ocr_rec_dataset/01_bp_ocr_zf_dataset_V3/model_output/inference --model_filename inference.pdmodel --params_filename inference.pdiparams --opset_version 10 --save_file /train_dataset/05_ocr_rec_dataset/01_bp_ocr_zf_dataset_V3/model_output/inference/ocr_opset_10.onnx

**Comment by jingsongliujing** [comment]
建议可以把训练出来的模型试试用paddlesilm量化一下：https://github.com/PaddlePaddle/PaddleSlim

**Comment by zhangclAI** [comment]
你还，我也出现这种问题，训练模型的数据量越大，得到的ONNX模型的推理速度越慢，请问你知道怎么解决吗

**Comment by zhangclAI** [comment]
你好，我也出现这种问题，训练模型的数据量越大，得到的ONNX模型的推理速度越慢，请问你知道怎么解决吗
