### ISSUE TITLE
SRN prediction error

### ISSUE THREAD

**Issue by manzhura** [PaddlePaddle/PaddleOCR#13859]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

I get the error: 

Traceback (most recent call last):
  File "C:\Users\projects\test_paddle\PaddleOCR\test.py", line 23, in <module>
    result = ocr.ocr(gray_img,
  File "C:\Users\projects\test_paddle\PaddleOCR\paddleocr.py", line 776, in ocr
    rec_res, elapse = self.text_recognizer(img)
  File "C:\Users\projects\test_paddle\PaddleOCR\tools\infer\predict_rec.py", line 793, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is -1, input's shape is [].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at ..\paddle/phi/kernels/cpu/conv_util.h:137)
  [operator < fused_conv2d_add_act > error]

however the output below (after recent changes) works correctly:
python tools/infer/predict_rec.py --image_dir=".....jpg"  --rec_model_dir="output/rec/srn/inference"  --rec_char_dict_path="ppocr/utils/en_dict.txt"    --rec_image_shape="1,64,256" --rec_algorithm="SRN" --use_space_char=False

### 🏃‍♂️ Environment (运行环境)

windows10,  Python 3.10, paddleocr from  git clone main today

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

ocr = PaddleOCR(rec_model_dir="output/rec/_srn_new/inference/",
use_tensorrt=False,
det=False,
use_gpu=True,
lang='en',
rec_image_shape="1, 64, 256",
use_angle_cls=True,
rec_char_dict_path='ppocr/utils/en_dict.txt',
).

**Comment by GreatV** [comment]
```python
ocr = PaddleOCR(rec_model_dir="output/rec/_srn_new/inference/",
use_tensorrt=False,
det=False,
use_gpu=True,
lang='en',
rec_image_shape="1, 64, 256",
use_angle_cls=True,
rec_char_dict_path='ppocr/utils/en_dict.txt',
rec_algorithm="SRN"
).
```

**Comment by GreatV** [comment]
Specify the `rec_algorithm`.

**Comment by manzhura** [comment]
thanks for the quick reply, but in response I get:

[2024/09/12 14:06:19] ppocr ERROR: rec_algorithm must in ['CRNN', 'SVTR_LCNet']

**Comment by GreatV** [comment]
The `paddleocr` API only supports the pppocr family algorithm, code modifications are needed.

**Comment by manzhura** [comment]
If it's not too much trouble, give me an idea of ​​how to do this

**Comment by GreatV** [comment]
For specific details, please refer to tools/infer/predict_rec.py. Right now, you can't use these algorithms (SRN etc.) through the PaddleOCR PyPI package.

**Comment by GreatV** [comment]
it is hard to say, please refer to: https://paddlepaddle.github.io/PaddleOCR/en/ppocr/infer_deploy/index.html
