### ISSUE TITLE
android_demo只能使用CPU推理吗？

### ISSUE THREAD

**Issue by Jverson** [PaddlePaddle/PaddleOCR#1386]
各位大神，我将android_demo导入Android Studio
把PaddleLite替换成了release/v2.7版本（build.lite.android.armv8.gcc）
把下载的模型使用opt（--valid_targets=arm）优化成3.5M
编译后安装到我的Android终端（高通骁龙660）上运行，识别起来好慢。
我想了一下，可能是使用CPU推理的缘故，于是使用高通提供的命令查看gpu_busy_percentage
只在刚开始页面刷新的时候会有10%~%15的使用率，后面都1%或者0%，应该确实没有用到GPU。

于是我更换PaddleLite为release/v2.7的支持opencl版本（build.lite.android.armv8.clang.opencl）
模型也重新优化了一下，valid_targets加上了opencl（--valid_targets=arm opencl）
重新编译安装跑起来，已经支持opencl了，按理说应该是会使用GPU推理了，结果速度还是一样。
查看gpu_busy_percentage，也跟前面几乎一样，貌似仍然没有使用GPU推理。

想问一下，这个android_demo是不是只能用CPU推理，有没有办法实现GPU推理？

**Comment by 772865705** [comment]
大神，我也想问一下你这个androiddemo怎么使用V1.1的超轻量级版本模型，我吧paddliLite换哪个都没用…… 
你也是做android的吗，方便留联系方式吗

**Comment by Jverson** [comment]
> 大神，我也想问一下你这个androiddemo怎么使用V1.1的超轻量级版本模型，我吧paddliLite换哪个都没用……
> 你也是做android的吗，方便留联系方式吗

有具体报错的信息吗？

**Comment by DaveBoy** [comment]
后面有使用gpu的方法吗
