### ISSUE TITLE
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by Abhivadan** [PaddlePaddle/PaddleOCR#13877]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![image](https://github.com/user-attachments/assets/65967b94-24de-446d-ab93-15fdf1c9edc2)
I am facing this issue even while I am using paddle paddle gpu version 2.4.1. Also my cuda driver version is 12.6 .  It seema paddle-paddle gpu for cuda 12.6 is not present till now. Has anyone been facing this isssue or able to solve it??

### 🏃‍♂️ Environment (运行环境)

'''os linux, paddleocr -2.8.1 ,paddlepaddle-gpu -2.4.1, Cuda -12.6'''

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

 python -c "import paddle; print(paddle.device.cuda.device_count())"

**Comment by jingsongliujing** [comment]
You can try installing PaddlePaddle 3.0
```
python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/
```

**Comment by Abhivadan** [comment]
not working . Instead a new error is coming: 


>>> from paddleocr import PaddleOCR
Error: Can not import paddle core while this file exists: /datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/__init__.py", line 33, in <module>
    from .base import core  # noqa: F401
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/core.py", line 384, in <module>
    raise e
  File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/libpaddle.so).

**Comment by Cupcc** [comment]
> not working . Instead a new error is coming:
> 
> > > > from paddleocr import PaddleOCR
> > > > Error: Can not import paddle core while this file exists: /datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/libpaddle.so
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddleocr/**init**.py", line 14, in 
> > > > from .paddleocr import *
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 21, in 
> > > > import paddle
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/**init**.py", line 33, in 
> > > > from .base import core  # noqa: F401
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/**init**.py", line 38, in 
> > > > from . import (  # noqa: F401
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/backward.py", line 25, in 
> > > > from . import core, framework, log_helper, unique_name
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/core.py", line 384, in 
> > > > raise e
> > > > File "/datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/core.py", line 267, in 
> > > > from . import libpaddle
> > > > ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /datavol2/conda_env/ocr_llm/lib/python3.9/site-packages/paddle/base/libpaddle.so).

reference this
https://github.com/PaddlePaddle/PaddleOCR/issues/11998#issuecomment-2076564554
