### ISSUE TITLE
paddleocr  在C++下  cpu环境   ppocr_v4模型使用mkl加速   识别结果全错误

### ISSUE THREAD

**Issue by SeeYouAgainZm** [PaddlePaddle/PaddleOCR#13885]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

paddleocr  在C++下  cpu环境   ppocr_v4模型使用mkl加速   识别结果全错误， 其他模型没有这个情况

### 🏃‍♂️ Environment (运行环境)

win11
cpu

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

paddleocr  在C++下  cpu环境   ppocr_v4模型使用mkl加速   识别结果全错误， 其他模型没有这个情况

**Comment by jingsongliujing** [comment]
#10885 可以看看这个issue的解决办法
