### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.   [TimeInfo: *** Aborted at 1726731168 (unix time) try "date -d @1726731168" if you are using GNU date ***]   [SignalInfo: *** SIGABRT (@0x3e80001640f) received by PID 91151 (TID 0x7f4185942740) from PID 91151 ***]

### ISSUE THREAD

**Issue by sunyclj** [PaddlePaddle/PaddleOCR#13889]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

详细报错日志：
[2024/09/19 07:32:45] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/09/19 07:32:46] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/09/19 07:32:47] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/09/19 07:32:47] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun(bool)
1   paddle::framework::NaiveExecutor::RunInterpreterCore(std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
2   paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
3   paddle::framework::ProgramInterpreter::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
4   paddle::framework::ProgramInterpreter::Build(std::vector<std::string, std::allocator<std::string > > const&, std::vector<paddle::framework::OpFuncNode, std::allocator<paddle::framework::OpFuncNode> >*, bool)
5   paddle::framework::interpreter::BuildOpFuncList(phi::Place const&, paddle::framework::BlockDesc const&, std::set<std::string, std::less<std::string >, std::allocator<std::string > > const&, std::vector<paddle::framework::OpFuncNode, std::allocator<paddle::framework::OpFuncNode> >*, paddle::framework::VariableScope*, paddle::framework::interpreter::ExecutionConfig const&, std::vector<std::function<void (paddle::framework::OperatorBase*, paddle::framework::Scope*)>, std::allocator<std::function<void (paddle::framework::OperatorBase*, paddle::framework::Scope*)> > > const&, std::vector<std::function<void (paddle::framework::OperatorBase*, paddle::framework::Scope*)>, std::allocator<std::function<void (paddle::framework::OperatorBase*, paddle::framework::Scope*)> > > const&, bool, bool)
6   void phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&, bool, int, float, phi::DenseTensor*, std::vector<phi::DenseTensor*, std::allocator<phi::DenseTensor*> >), &(void phi::fusion::FusedConv2dAddActKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&, bool, int, float, phi::DenseTensor*, std::vector<phi::DenseTensor*, std::allocator<phi::DenseTensor*> >))>::KernelCallHelper<paddle::optional<phi::DenseTensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&, bool, int, float, phi::DenseTensor*, std::vector<phi::DenseTensor*, std::allocator<phi::DenseTensor*> >, phi::TypeTag<int> >::Compute<1, 3, 0, 0, phi::GPUContext const, phi::DenseTensor const, phi::DenseTensor const, phi::DenseTensor const>(phi::KernelContext*, phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&)
7   void phi::fusion::FusedConv2dAddActKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&, bool, int, float, phi::DenseTensor*, std::vector<phi::DenseTensor*, std::allocator<phi::DenseTensor*> >)
8   phi::fusion::(anonymous namespace)::CudnnConvDescManager::GetCudnnCacheInfo(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DataType, int, cudnnDataType_t, cudnnTensorFormat_t, std::function<void (cudnnConvolutionFwdAlgo_t*, unsigned long*, cudnnTensorStruct*, cudnnFilterStruct*, cudnnTensorStruct*, cudnnConvolutionStruct*)> const&, std::string const&, double)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1726731168 (unix time) try "date -d @1726731168" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80001640f) received by PID 91151 (TID 0x7f4185942740) from PID 91151 ***]

Aborted (core dumped)

### 🏃‍♂️ Environment (运行环境)

Package                  Version
------------------------ -----------
albucore                 0.0.16
albumentations           1.4.15
annotated-types          0.7.0
anyio                    4.4.0
astor                    0.8.1
beautifulsoup4           4.12.3
certifi                  2024.8.30
charset-normalizer       3.3.2
coloredlogs              15.0.1
contourpy                1.3.0
cycler                   0.12.1
Cython                   3.0.11
decorator                5.1.1
eval_type_backport       0.2.0
exceptiongroup           1.2.2
fire                     0.6.0
flatbuffers              24.3.25
fonttools                4.53.1
h11                      0.14.0
httpcore                 1.0.5
httpx                    0.27.2
humanfriendly            10.0
idna                     3.10
imageio                  2.35.1
imgaug                   0.4.0
importlib_resources      6.4.5
kiwisolver               1.4.7
lazy_loader              0.4
lmdb                     1.5.1
lxml                     5.3.0
matplotlib               3.9.2
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.4
nvidia-cublas-cu11       11.11.3.6
nvidia-cuda-cupti-cu11   11.8.87
nvidia-cuda-nvrtc-cu11   11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11        8.7.0.84
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.3.0.86
nvidia-cusolver-cu11     11.4.1.48
nvidia-cusparse-cu11     11.7.5.86
nvidia-nccl-cu11         2.19.3
nvidia-nvtx-cu11         11.8.86
onnxruntime              1.19.2
opencv-contrib-python    4.10.0.84
opencv-python            4.10.0.84
opencv-python-headless   4.10.0.84
opt-einsum               3.3.0
packaging                24.1
paddle2onnx              1.2.8
paddleocr                2.8.1
paddlepaddle             2.6.2
paddlepaddle-gpu         3.0.0b1
pillow                   10.4.0
pip                      24.2
protobuf                 5.28.1
pyclipper                1.3.0.post5
pydantic                 2.9.2
pydantic_core            2.23.4
pyparsing                3.1.4
python-dateutil          2.9.0.post0
python-docx              1.1.2
PyYAML                   6.0.2
rapidfuzz                3.9.7
requests                 2.32.3
scikit-image             0.24.0
scipy                    1.13.1
setuptools               73.0.1
shapely                  2.0.6
six                      1.16.0
sniffio                  1.3.1
soupsieve                2.6
sympy                    1.13.2
termcolor                2.4.0
tifffile                 2024.8.30
tqdm                     4.66.5
typing_extensions        4.12.2
urllib3                  2.2.3
wheel                    0.44.0
zipp                     3.20.2

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python tools/infer/predict_system.py --image_dir="./5645.jpg" --det_model_dir='./pre_model/ch_PP-OCRv4_det_infer' --cls_model_dir='./pre_model/ch_ppocr_mobile_v2.0_cls_infer' --rec_model_dir='./pre_model/ch_PP-OCRv4_rec_infer' --use_angle_cls=true
虚拟环境中cuda及cudnn版本如下：
CUDA version: 11.8
cuDNN version: 8.6.0
python版本3.9
执行import paddle
>>>paddle.utils.run_check()
可成功输出

**Comment by jingsongliujing** [comment]
假如您下载了源码，建议把pip包里的paddleocr卸载试试，pip uninstall paddleocr

**Comment by sunyclj** [comment]
> 假如您下载了源码，建议把pip包里的paddleocr卸载试试，pip uninstall paddleocr

是源码推理，卸载之后依然报一样的错误。

**Comment by jingsongliujing** [comment]
Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory动态链接库找不到的问题建议您可以看看博客的解决方案：https://blog.csdn.net/qq_45934285/article/details/134064505
