### ISSUE TITLE
表格识别时报错：IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by Wangqi12138** [PaddlePaddle/PaddleOCR#13887]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

执行-> % python table/predict_table.py \
  --det_model_dir=../models/ch_PP-OCRv3_det_infer \
  --rec_model_dir=../models/ch_PP-OCRv3_rec_infer \
  --table_model_dir=../models/ch_ppstructure_openatom_SLANetv2_infer \
  --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
  --table_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
  --image_dir=docs/table/table.jpg \ 
  --output=../output/table
  
  报错：Traceback (most recent call last):
  File "table/predict_table.py", line 241, in <module>
    main(args)
  File "table/predict_table.py", line 189, in main
    pred_res, _ = table_sys(img)
  File "table/predict_table.py", line 109, in __call__
    pred_html = self.match(structure_res, dt_boxes, rec_res)
  File "/data/ai/user/user/gaodh/wq/PaddleOCR/ppstructure/table/matcher.py", line 66, in __call__
    dt_boxes, rec_res = self._filter_ocr_result(pred_bboxes, dt_boxes, rec_res)
  File "/data/ai/user/user/gaodh/wq/PaddleOCR/ppstructure/table/matcher.py", line 197, in _filter_ocr_result
    y1 = pred_bboxes[:, 1::2].min()
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### 🏃‍♂️ Environment (运行环境)

python：3.8
paddle：2.6.2
opencv：4.10
cuda：11.7

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

  python table/predict_table.py \
  --det_model_dir=../models/ch_PP-OCRv3_det_infer \
  --rec_model_dir=../models/ch_PP-OCRv3_rec_infer \
  --table_model_dir=../models/ch_ppstructure_openatom_SLANetv2_infer \
  --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
  --table_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
  --image_dir=docs/table/table.jpg \ 
  --output=../output/table

**Comment by jingsongliujing** [comment]
可以看看这个issue的解决方法：
#8205

**Comment by jingsongliujing** [comment]
可能是自己图片的格式问题，可以先用官方的示例图片试试

**Comment by GreatV** [comment]
`--table_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt` 这个字典不对吧

**Comment by Wangqi12138** [comment]
@jingsongliujing 试了官方的图片也不行，但是已经解决了

**Comment by No360201** [comment]
> @jingsongliujing 试了官方的图片也不行，但是已经解决了

你好，请问是怎么解决的，可以分享一下吗
