### ISSUE TITLE
Deployed PaddleOCR api suddenly results in incorrect OCR text results

### ISSUE THREAD

**Issue by DipanshuJuneja** [PaddlePaddle/PaddleOCR#13884]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

I have deployed a `PaddleOCR `API via `FastAPI `on Google Cloud Run which was working correctly when making api calls until yesterday however suddenly today when I run the service, its returning gibberish output. Not sure what happened, I have not deployed any new version. When I run the app locally, it works correctly all the time. 

### 🏃‍♂️ Environment (运行环境)

paddleocr==2.7.3
paddlepaddle==2.6.1
fastapi==0.111.0

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

Below is my initializing code, note that I'm already downloading the models in my Docker image

```
from paddleocr import PaddleOCR
import os
# def ocr_model():
ocr = PaddleOCR(use_angle_cls=True, lang='en', enable_mkldnn=True, recovery=True,
                det_model_dir=os.path.abspath('fast_api_server/ocr_models/det'), 
                rec_model_dir=os.path.abspath('fast_api_server/ocr_models/rec'),
                cls_model_dir=os.path.abspath('fast_api_server/ocr_models/cls'))
```

**Comment by jingsongliujing** [comment]
Can you provide screenshots of any error messages or output logs?

**Comment by DipanshuJuneja** [comment]
Hi @jingsongliujing, I'm not seeing any error messages or anything in my output logs, it gives back a 200-status code back, only that ocr text output is not making sense suddenly since today, I'm attaching the file and text returned for your reference. Note that same file was giving back correct results till yesterday. 
[Linkedin_1.pdf](https://github.com/user-attachments/files/17054667/Linkedin_1.pdf)
<img width="184" alt="Output_OCR" src="https://github.com/user-attachments/assets/251bb0d5-0414-4526-b030-e28a2cd6cd46">

**Comment by jingsongliujing** [comment]
Oh,I need to see the difference between the normal and abnormal information to identify the issue. Based on the information currently provided, we are unable to pinpoint the exact cause of the anomaly.

**Comment by DipanshuJuneja** [comment]
I understand. Can you let me know what I can share to debug this? Since there is nothing in the logs. If it helps, I tried changing the version of FastAPI and it gave correct OCR text results for a while but now I'm seeing the issue again. My current versions used are: 
```
fastapi==0.111.0
fastapi-cli==0.0.4
uvicorn==0.30.1
```
I'm thinking does it have something to do with Google Cloud Run configurations?

**Comment by jingsongliujing** [comment]
If you are using the CPU version, it is recommended to convert to the ONNX model and use ONNX Runtime for inference: 
```
https://paddlepaddle.github.io/PaddleOCR/en/ppocr/infer_deploy/paddle2onnx.html#paddle-model-download
```

```
 https://github.com/jingsongliujing/OnnxOCR
```
 If you are using GPU for inference, it is suggested to upgrade PaddlePaddle to version 3.0:  
```
python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
```
