### ISSUE TITLE
在32核CPU运行过慢，一张图片需要30秒

### ISSUE THREAD

**Issue by hongminduzuimei** [PaddlePaddle/PaddleOCR#13892]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

在32核CPU服务器中处理一条数据的时间为30秒

### 🏃‍♂️ Environment (运行环境)

32核CPU，"paddlepaddle==2.3.0，"paddleocr==2.8.1"

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

ocr = PaddleOCR(use_angle_cls=True, lang="ch")

**Comment by jingsongliujing** [comment]
cpu上建议用onnxocr快一些：https://github.com/jingsongliujing/OnnxOCR
