### ISSUE TITLE
运行到 During the training process after the 0th iteration an evaluation is run every 1 iterations 就没往下执行了

### ISSUE THREAD

**Issue by zengweigit** [PaddlePaddle/PaddleOCR#13894]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

运行到 During the training process, after the 0th iteration, an evaluation is run every 1 iterations 就没往下执行了，能帮我看下吗？
![image](https://github.com/user-attachments/assets/1230f97c-0f70-46b7-a55e-9768583bee34)
![image](https://github.com/user-attachments/assets/3db5abe2-bbc5-4e26-855e-e25894a1cf67)

### 🏃‍♂️ Environment (运行环境)

Python3.8
Ubuntu24.04
PaddleOCR-release-2.7
![image](https://github.com/user-attachments/assets/a4141bf0-3d98-4002-a168-1b0010747bb9)

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

执行命令
python3 -m paddle.distributed.launch --gpus '0,1' tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv3_det_distill_train/best_accuracy

**Comment by zengweigit** [comment]
@jingsongliujing 麻烦帮我看下

**Comment by GreatV** [comment]
先用单个gpu训练试试看，会报错吗

**Comment by zengweigit** [comment]
> 先用单个gpu训练试试看，会报错吗
单个GPU，单独使用CPU都试过了
也是到这步就不往下运行了

**Comment by zengweigit** [comment]
> 先用单个gpu训练试试看，会报错吗

单个GPU，单独使用CPU都试过了
也是到这步就不往下运行了

**Comment by zengweigit** [comment]
![image](https://github.com/user-attachments/assets/ee3edcde-ef33-4535-a4c6-18bc461e2ebf)
数据集是下载的 ctw1500，best_accuracy 也是从官网下载的，到底哪里出问题了呀，崩溃

**Comment by zengweigit** [comment]
单GPU训练还是这样，到底啥问题啊，心态爆炸
![image](https://github.com/user-attachments/assets/0e109428-485d-4169-8726-68ee55111769)

**Comment by GreatV** [comment]
检查一下paddle框架是否安装正确，试试3.0beta版本

**Comment by zengweigit** [comment]
> 检查一下paddle框架是否安装正确，试试3.0beta版本

现在直接 Illegal instruction (core dumped) 了
![image](https://github.com/user-attachments/assets/d79c1afb-60d8-4377-94ce-6f9aa5db9294)

**Comment by GreatV** [comment]
是根据PaddlePaddle官网的安装教程安装的paddle吗

**Comment by zengweigit** [comment]
> 是根据PaddlePaddle官网的安装教程安装的paddle吗

照着这个装的
![image](https://github.com/user-attachments/assets/e5ad9809-b0b9-42a2-97aa-0113d3c52cbe)

**Comment by zengweigit** [comment]
> 是根据PaddlePaddle官网的安装教程安装的paddle吗

我装2.6.2版本就能正常打印
![image](https://github.com/user-attachments/assets/33c62eec-ab11-4967-a959-6849eaf0caa5)

**Comment by GreatV** [comment]
paddleocr用的是什么版本呀，试试main分支的代码

**Comment by zengweigit** [comment]
我自己重新创建了个conda环境，能正常运行了，用的还是paddle2.6.2，懵，，，

![image](https://github.com/user-attachments/assets/d2f4af14-7d7c-4676-bbe7-18ee5fde82f5)
