### ISSUE TITLE
OCR lite部署时出错

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/PaddleOCR#1389]
按照lite部署教程：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md 依次操作部署OCR，结果出现报错。

起初报错内容：
CANNOT LINK EXECUTABLE "./ocr_db_crnn": library "libpaddle_light_api_shared.so" not found

使用export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)命令加入lib库后，又出现如下报错：
CANNOT LINK EXECUTABLE "./ocr_db_crnn": library "libc++_shared.so" not found

请问这该如何处理呢？

**Comment by LDOUBLEV** [comment]
报错是找你的预测库文件，
 libpaddle_light_api_shared.so 改成 libc++_shared.so 的名字就行
