### ISSUE TITLE
EAST检测出错

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#139]
#https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/inference.md#3east%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86

我使用上面的网页中的教程，尝试把超轻量检测模型中的db换成EAST。自己下载了EAST模型，按照教程使用export_model.py 转换成了inference模型。转化后的模型检测完全不对。
转换后的模型下载地址：
链接：https://pan.baidu.com/s/1TEHKfzBc0zCifpM7ARmTzQ 
提取码：cgl3

**Comment by LDOUBLEV** [comment]
方便发一下你转换的命令吗

**Comment by SixGodGG** [comment]
> 方便发一下你转换的命令吗

已经成功了，是我结果输出路径不对。

**Comment by SixGodGG** [comment]
我发现还是不太对，效果不可能这么差。
python E:/GitHub/PaddleOCR/tools/infer/predict_det.py --image_dir="E:/GitHub/PaddleOCR/doc/imgs/1.jpg" --det_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/det_mv3_east/" --det_algorithm="EAST"
@LDOUBLEV 您可以下载我的模型，用predict_det.py测试一下，检测效果很差，只检测到了“研”“究”两个字。

**Comment by SixGodGG** [comment]
应该是我export_model 不对。我再试试。
