### ISSUE TITLE
RE模型推理时遇到 ValueError: not enough values to unpack (expected 2, got 1)，请教一下怎么解决

### ISSUE THREAD

**Issue by huangJJ8** [PaddlePaddle/PaddleOCR#13902]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

KIE在完成RE模型训练，进行模型预测推理时，输入指令“python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./output/re_vi_layoutxlm_xfund_zh/best_accuracy/ \
  Global.infer_img=./train_data/XFUND/ zh_val/val.json \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=output/ \
  ser_vi_layoutxlm_xfund_zh/best_accuracy/”，遇到了 “ ValueError: not enough values to unpack (expected 2, got 1)”，请教一下怎么解决。

### 🏃‍♂️ Environment (运行环境)

cuda12.2
python 3.10
paddlepaddle-gpu==2.5.2.post120
paddlenlp              2.5.2
paddleocr              2.8.1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./output/re_vi_layoutxlm_xfund_zh/best_accuracy/ \
  Global.infer_img=./train_data/XFUND/ zh_val/val.json \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=output/ \
  ser_vi_layoutxlm_xfund_zh/best_accuracy/
![111](https://github.com/user-attachments/assets/2115a003-0a74-4c01-b651-5085e08f0cb7)

**Comment by GreatV** [comment]
命令行输入有错误，检查一下

**Comment by huangJJ8** [comment]
您好，您问命令行输入是哪里的错误呢，能具体指一下吗。我按照“python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrain_models/re_vi_layoutxlm_udml_xfund_zh/best_accuracy/ \
  Global.infer_img=./train_data/XFUND/zh_val/image/ \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=pretrain_models/ \
  ser_vi_layoutxlm_udml_xfund_zh/best_accuracy/” 官方给的这个命令行，也是报同样的错误呢

**Comment by GreatV** [comment]
你是从哪段文档里复制的，把链接发我一下。

**Comment by huangJJ8** [comment]
@GreatV https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/kie.md  您好这是文档链接，SER模型和RE模型训练都是按照这个文档来的，SER和RE模型已经训练完了，SER模型推理也没有问题，在执行RE模型推理时遇到的这个问题。帮忙看一下是什么问题。非常感谢！

**Comment by GreatV** [comment]
```bash
python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrain_models/re_vi_layoutxlm_udml_xfund_zh/best_accuracy/ \
  Global.infer_img=./train_data/XFUND/zh_val/image/ \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=pretrain_models/ser_vi_layoutxlm_udml_xfund_zh/best_accuracy/
```

**Comment by huangJJ8** [comment]
@GreatV 您好，执行您这个命令，会报“RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/pretrain_models/ser_vi_layoutxlm_udml_xfund_zh/best_accuracy//model_state.pdparams failed with code 404!”  这个错误。

**Comment by GreatV** [comment]
要换成你自己实际的模型目录

**Comment by huangJJ8** [comment]
@GreatV 您是说“Architecture.Backbone.checkpoints”这个参数的值换成之前训练好保存的模型吗？，但是这样换成自己：“python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./ output/re_vi_layoutxlm_xfund_zh/best_accuracy/ \
  Global.infer_img=./train_data/XFUND/zh_val/image/ \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=output/ \
  ser_vi_layoutxlm_xfund_zh/best_accuracy/”
之后就又变成一开始的那个错误了：“ValueError: not enough values to unpack (expected 2, got 1)”

**Comment by GreatV** [comment]
你检查一下命令行里是不是多了换行符

**Comment by GreatV** [comment]
那个文档里多了一个换行符

**Comment by huangJJ8** [comment]
@GreatV 非常感谢您的解答，问题已经解决了。
