### ISSUE TITLE
默认模型释放路径如果是中文用户名包含中文会导致无法读取模型

### ISSUE THREAD

**Issue by SK-XFY** [PaddlePaddle/PaddleOCR#13925]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![1753919a2f869c1a78e27be31d1263c1](https://github.com/user-attachments/assets/5e8b8be2-4d97-4d2c-9a63-7dae4408afd3)
修改源码 
BASE_DIR = os.path.join("D:/.paddleocr/")
可以正常读取
![image](https://github.com/user-attachments/assets/c26fd0a1-d09b-47b7-adcb-e5e03640494f)

### 🏃‍♂️ Environment (运行环境)

系 统 os：windows10
paddleocr：last
paddlepaddle-cpu：3.0.0.dev20240925

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

 ocr = PaddleOCR(use_angle_cls=True, lang="ch", ignore_space=True)

**Comment by jingsongliujing** [comment]
Windows系统使用的是GBK编码，而Python默认使用的是UTF-8编码，假如用中文路径，会导致乱码，建议还是用英文路径
