### ISSUE TITLE
关于训练集选择问题。

### ISSUE THREAD

**Issue by longshifeng** [PaddlePaddle/PaddleOCR#1396]
应用文本定位模型时，输入的图形为小图（即通过手段处理裁剪出的包含待识别部分的图片）。

那么，在进行训练MobileNetV3的时候，想通过预训练模型+微调进行训练，那么此处放入的训练集和测试集是在大图标注下比较好，还是小图比较好。

![微信截图_20201212002354](https://user-images.githubusercontent.com/32770755/101928277-58afed80-3c10-11eb-8a2b-3de11cc792b8.png)
这是小图，包含所有需要训练识别的标签位置。
————————————————————————————————————————————————————————
![微信图片_20201212002130](https://user-images.githubusercontent.com/32770755/101927948-01118200-3c10-11eb-84ad-b173c1bf6d9c.png)
这是大图，包含了更多（无用的信息？）

图像质量相同，大图和小图的尺寸不同。
那么在进行微调训练时候应该如何选择？选用 哪一种图 定位效果会更好？ 小图是否是在时间上开销更低呢？~

**Comment by MissPenguin** [comment]
用和预测时的图像尺度和质量更一致的比较好，一般训练预测一致性越好，模型效果越好
