### ISSUE TITLE
paddleocr是否支持昇腾910

### ISSUE THREAD

**Issue by boreassun** [PaddlePaddle/PaddleOCR#13981]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

请问paddleocr是否支持昇腾910，paddleocr2.6在命令帮助里，没有npu选项：
![image](https://github.com/user-attachments/assets/c3eb5cd4-9ae6-4969-9812-5abfb34ea112)

如果支持有没有相关的安装文档

### 🏃‍♂️ Environment (运行环境)

昇腾910
registry.baidubce.com/device/paddle-npu:cann701-ubuntu20-aarch64-gcc84-py39
paddlepaddle2.6.1
paddleocr2.6

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

1

**Comment by Liyulingyue** [comment]
你好，请问你的问题解决了吗？根据历史issue信息 https://github.com/PaddlePaddle/PaddleOCR/issues/9054 可以在Global字段中配置这个信息。

**Comment by boreassun** [comment]
> ~你好，请问你的问题解决了吗？根据历史issue信息 #9054 可以在Global字段中配置这个信息。~
> 
> 根据2.8.1的测试，已经在在-h中增加NPU字段

问一下910a，如果我用paddleocr2.8.1的话，paddlepaddle我需要对应用哪个版本，还有PaddleCustomDevice用哪个版本？

**Comment by Liyulingyue** [comment]
910A的话，根据 PaddleCustomDevice 仓库，你需要使用2.6的PaddlePaddle，但是ppocr的2.8.1版本应该是能兼容的

**Comment by boreassun** [comment]
我使用paddlepaddle2.6+ppocr2.8.1，运行：paddleocr --image_dir ./test.png --use_angle_cls USE_ANGLE_CLS --use_npu=True报如下错误：
![fe96334126472c153c8dc30774fa253](https://github.com/user-attachments/assets/beda9204-6002-4936-9970-cc07ea8bc8e0)
![041e179da8bc6de49d06394c49b5713](https://github.com/user-attachments/assets/ede42796-62aa-4f6b-9380-ad830c00e1f1)

**Comment by Liyulingyue** [comment]
建议不要尝试了，似乎910A的适配有点问题，建议试一下910B
