### ISSUE TITLE
numpy version issue

### ISSUE THREAD

**Issue by agzeroo** [PaddlePaddle/PaddleOCR#13991]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

Hi.
I was using numpy version 1.26.3 and there was no problem.
But when numpy version becomes 2.0 or higher, the problem occurs.
Is there any way to solve this problem as quickly as possible?
https://github.com/PaddlePaddle/PaddleOCR/pull/13937#issue-2560596355 

### 🏃‍♂️ Environment (运行环境)

paddlepaddle-gpu 2.5.2

**Comment by OmarFaig** [comment]
Downgrade NumPy: Since you mentioned that the problem does not occur with NumPy version 1.26.3, a temporary workaround would be to downgrade to that version:
pip install numpy==1.26.3

**Comment by agzeroo** [comment]
@OmarFaig 
Thanks for the reply.

But I need to make paddleocr work in an environment where numpy 2.0 or higher is installed....

**Comment by GreatV** [comment]
cannot work for numpy geater than 2.0

**Comment by agzeroo** [comment]
@GreatV 

#13937 [WIP] Is there a difference between upgrade to numpy 2.0 and remove imgaug and #13467? I'm trying it, but I still don't get the result in numpy 2.0 or higher.

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/1b6764be-26fc-427b-a3b8-ca84e818eaf5">

**Comment by GreatV** [comment]
What's the specific numpy version issue you're facing?

**Comment by agzeroo** [comment]
@GreatV 

With numpy 2.1.2, training does not occur at all (loss does not decrease) and inference with a pretrained model does not produce any results. (Running the same data with numpy 1.26.3 produces normal results.) 

Trying #13467 also produced the following error, training did not occur, and inference still did not produce any results.
![image](https://github.com/user-attachments/assets/9eee01b3-6d05-49d1-8135-855be09c0a73)

**Comment by GreatV** [comment]
That looks really weird, we'll investigate further.

**Comment by GreatV** [comment]
@agzeroo Please try our latest main branch to check if the issue is resolved.
