### ISSUE TITLE
测试内存溢出

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#1400]
目前观察是在inference和eval环节出现的
用的det_r18_vd_db_v1.1.yml，只训练检测网络
关闭eval环节（eval_batch_step: [4000000, 2000]）就不再爆内存了，主进程8-10g内存，数据读取5-8g每个进程
#971

**Comment by caopulan** [comment]
补充一下，batch是14，paddlepaddle-gpu  2.0.0rc0.post101

**Comment by littletomatodonkey** [comment]
可以试着把训练和eval的bs改小一点，

**Comment by caopulan** [comment]
> 可以试着把训练和eval的bs改小一点，

训练不会造成内存泄漏，eval的bs设置没有用，我之前用的1也会造成内存一直在增长。目前只能是只train，用checkpoint单独进行eval

**Comment by LDOUBLEV** [comment]
目前内存泄漏的问题已经解决了，另外，建议不要用cudnn 8.0.3和8.1之间的版本，建议用8.1，否则可能会出现内存泄漏
