### ISSUE TITLE
space detection failed in paddleocr

### ISSUE THREAD

**Issue by tzktok** [PaddlePaddle/PaddleOCR#14012]
### 🐛 Bug (问题描述)

see the above detection in words DATE and ACTIVITY..In there space detction was failed it merge the sentence in single bounding box coordinates.. @ZeyuChen  @wencan @GreatV 

### 🏃‍♂️ Environment (运行环境)

```
python : 3.10
cuda : 11.8
paddleocr : 2.8.1
paddlepaddle : 2.6.2
```

**Comment by tzktok** [comment]
> ### 🐛 Bug (问题描述)
> ![det_res_table1](https://private-user-images.githubusercontent.com/169971463/376910081-7a8b5b2e-e6f3-4be9-93ec-1c14d775bee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjAwNzIsIm5iZiI6MTcyOTA1OTc3MiwicGF0aCI6Ii8xNjk5NzE0NjMvMzc2OTEwMDgxLTdhOGI1YjJlLWU2ZjMtNGJlOS05M2VjLTFjMTRkNzc1YmVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwNjIyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWM5M2M5ZWNlZmJjYzkzMmM2OTRhMjg1YjA1ZjYyZTQ5ZDg1ZDFlZDExNzQ4YmM5ZTMzYjYzYzk2NzMwNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aOGiR26HnkwPKyiiSsHfbFDcR-qWTl_nl5fGipJnLQo)
> 
> see the above detection in words DATE and ACTIVITY..In there space detction was failed it merge the sentence in single bounding box coordinates.. @ZeyuChen @wencan @GreatV 
> 
> ### 🏃‍♂️ Environment (运行环境)
> ```
> python : 3.10
> cuda : 11.8
> paddleocr : 2.8.1
> paddlepaddle : 2.6.2
> ```

**Comment by Liyulingyue** [comment]
It seems that the space between DATE and ACTIVITY is too small, and model treat them as the same sentence.
The solution is to train a new model, if you wanna to distinguish them.
