### ISSUE TITLE
v4检测和识别训练时报类似The pretrai ned params backbone.fc.weight not in model

### ISSUE THREAD

**Issue by HonestyBrave** [PaddlePaddle/PaddleOCR#14011]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

您好：
     真心感谢你们的开源和维护工作，我在使用最新版本v4进行训练时发现，无论是检测还是识别，都报类似The pretrai ned params backbone.fc.weight not in model这样的Warning，请问这个Warning对训练结果有影响吗，该如何解决？
![1729046977841](https://github.com/user-attachments/assets/57e7a959-4c8c-437a-85c7-1417df8ef722)

### 🏃‍♂️ Environment (运行环境)

ubuntu 18.04
torch 1.13
python 3.8

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

我的代码用的是：  
2024-10-08 22:13      
e90079f01ed17dd8694b88532a6e2d6162560ab6

**Comment by Liyulingyue** [comment]
你的运行环境和复现代码需要补充一些信息~
1. 运行环境中需要标注PaddlePaddle/PaddleOCR的版本
2. 复现DEMO中需要补充你导致问题的代码示例~

**Comment by HonestyBrave** [comment]
@Liyulingyue 代码版本是：2024-10-08 22:13
 https://github.com/PaddlePaddle/PaddleOCR/commit/e90079f01ed17dd8694b88532a6e2d6162560ab6

然后模型用的就是当前网站上提供的，你们可以验证下吗

**Comment by Liyulingyue** [comment]
没复现这个问题，但是对训练来说应该基本没啥影响。
