### ISSUE TITLE
本地下载模型解压，layout模型会校验失败

### ISSUE THREAD

**Issue by sq1139172570** [PaddlePaddle/PaddleOCR#14010]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

下载模型到本地运行发现layout会验证失败，导致无论如何都校验不过，在network.py 的maybe_download中校验inference.pdiparams和inference.pdmodel，手动下载layout解压没有这两个模型，会导致无论如何都会自动联网下载layout模型

### 🏃‍♂️ Environment (运行环境)

OS : ubuntu22.04

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

必现问题

**Comment by GreatV** [comment]
哪个模型，提供一下可复现的demo如输入的命令或者使用的代码。

**Comment by GreatV** [comment]
你是怎么指定模型地址呀

**Comment by GreatV** [comment]
是在docker里用的吗，需要指定绝对路径。

**Comment by lovingliferwj** [comment]
同样的问题，在python里使用绝对路径，
from paddleocr import PPStructure

root_path = '/paddleocr_model/ppstruct/'
table_engine = PPStructure(det_model_dir=root_path + 'ch_PP-OCRv3_det_infer',
                           rec_model_dir=root_path + 'ch_PP-OCRv3_rec_infer',
                           table_model_dir=root_path + 'ch_ppstructure_mobile_v2.0_SLANet_infer',
                           layout_model_dir=root_path + 'picodet_lcnet_x1_0_layout_infer',
                           rec_char_dict_path=root_path + 'ppocr_keys_v1.txt',
                           table_char_dict_path=root_path + 'table_structure_dict_ch.txt')
   在layout 加载阶段报错，maybedown loadpicodet_lcnet_x1_0_fgs_layout_cdla_infer 会去网络下载，但无法联网报错

**Comment by Huanuanx** [comment]
你好，请问解决了吗？我也遇到了同样的问题
