### ISSUE TITLE
同一个推理模型，文字识别predict_rec.py和predict_system.py结果不一样

### ISSUE THREAD

**Issue by ly03240921** [PaddlePaddle/PaddleOCR#14027]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

同一个推理模型
我将某部分的图片送到predict_rec.py，文字识别结果如下：
![image](https://github.com/user-attachments/assets/e0a89f82-7ccd-46fe-a086-4cb55e157926)

当我将完整图片送到predict_system.py，进行文字检测+识别时，结果如下：
![image](https://github.com/user-attachments/assets/8c2830ab-d1a6-48e9-80a6-05a813fdbfc0)
生成的可视化图是这样的，det是将“发票代码”那块检测出来的，但发票代码数字识别是错误的，中间少了0：
![image](https://github.com/user-attachments/assets/4c69d63b-9510-438b-a6b3-32ea6105d4d2)

我把predict_system.py里经过det检测后剪切的文字图片保存下来看了
这是det检测后剪切的图片：
![zhenshi_crop_2](https://github.com/user-attachments/assets/10d5a8de-6e8b-4e0b-92f9-3d5858ee17f1)
将这张图片送到predict_rec.py，识别出来的结果就是错的了，就是上图system.py出来的错结果

下面是我经过PPOCRLabel制作数据集的切片图像，也是第一张图送到predict_rec.py里面的图像：
![dzfp_3_crop](https://github.com/user-attachments/assets/ee6e042d-ca66-4882-9316-bb92c7398f82)
这张出来的结果如图1，是正确的

这两张图看起来一样，但识别结果不同，为什么呢？

### 🏃‍♂️ Environment (运行环境)

Paddleocr2.8

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python tools/infer/predict_rec.py --image_dir=./err_imgs/dzfp_3_crop.jpg --rec_model_dir=./inference_model/chushi_rec/

python tools/infer/predict_system.py --image_dir="./err_imgs/dzfp_3.jpg" --det_model_dir="./inference_model/full-dzfp_det/" --rec_model_dir="./inference_model/chushi_rec/"

**Comment by Liyulingyue** [comment]
也许可以尝试对图片进行一些处理和测试。
比如将第二个图片的长和宽向外扩张一点，用白色像素填充；或者将第一张图的向内收缩一点，可以看看是否会导致识别结果发生变化。
