### ISSUE TITLE
PaddleOCRv4检测和识别模型利用PaddleSlim量化裁剪过程中的问题

### ISSUE THREAD

**Issue by yunnan66** [PaddlePaddle/PaddleOCR#14024]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

您好！
感谢您的开源和维护工作，我在裁剪训练v4的检测和识别模型时，报错如下:ValueError: The size of input is too big. Please consider saving it to file and ‘load_op’ to load it
运行命令：python deploy/slim/prune/sensitivity_anal.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv4_det_train/best_accuracy Global.save_model_dir=./output/prune_model/
另外，还有一个问题是通过量化裁剪的方式是否可以提升PaddleOCR模型的处理速度，具体该如何操作，期待您的回复，谢谢。

### 🏃‍♂️ Environment (运行环境)

ubuntu 18.04
python 3.9
paddlapaddle 2.6.1
paddleslim 2.6.0

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

PaddleOCR的工程是PaddleOCR-main

**Comment by Liyulingyue** [comment]
请参考PaddleSlim最新的教程，后续会对内容进行验证后补充相关说明。 https://github.com/PaddlePaddle/PaddleSlim
