### ISSUE TITLE
paddleocr标注工具点击自动标注没有反应一直是加载中，没有任何的反应

### ISSUE THREAD

**Issue by laolj** [PaddlePaddle/PaddleOCR#14023]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

系统环境/System Environment：window10,  pip3.11
版本号/Version：Paddle：release/2.7   PaddleOCR： 问题相关组件/Related components：paddleocr:2.6.1.3
运行指令/Command Code：python PPOCRLabel.py --lang ch
完整报错/Complete Error Message：
ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  D:\PaddleOCR-release-2.7\data\trun\roi_output.jpg
DirPath in importDirImages is D:/PaddleOCR-release-2.7/data/trun
Using model from  paddle
unicodeFilePath is D:\PaddleOCR-release-2.7\data\trun\roi_output.jpg

### 🏃‍♂️ Environment (运行环境)

window10,  pip3.11

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

百分百出现

**Comment by laolj** [comment]
![image](https://github.com/user-attachments/assets/efb8ccf7-5ea9-48da-a376-46b7264506bd)
我加了一个中文重新运行，把原来的缓存文件删除就可以了，好奇怪，这是为啥，能教教我吗？是因为中文兼容性？源码哪里体现出来？

**Comment by GreatV** [comment]
ppocrlabel 已经迁移出去了 https://github.com/PFCCLab/PPOCRLabel，建议在独立的仓库提问。
