### ISSUE TITLE
CRNN识别，用自己的数据集训练完后评估结果'avg_acc': 1.0, 'total_acc_num': 60, 'total_sample_num': 60，但测试的时候验证集准确率并不是100%

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1405]
评估用的命令python tools/eval.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints=./output/rec_CRNN/best_accuracy
结果：
`2020-12-14 00:56:39,207-INFO: Finish initing model from ./output/rec_CRNN/best_accuracy
2020-12-14 00:56:39,566-INFO: Eval result: {'avg_acc': 1.0, 'total_acc_num': 60, 'total_sample_num': 60}
`
测试用的命令python tools/infer_rec.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints=./output/rec_CRNN/best_accuracy Global.infer_img=doc/imgs_results_vis2/test/img_1001_crop_0.jpg

**Comment by tink2123** [comment]
方便提供下测试结果吗？ 
img_1001_crop_0.jpg 这张图片是否在您的验证集里呢？

**Comment by 666888985** [comment]
怎么评估自己的数据集有人知道吗？那个eval.py里面的评估数据是公开数据集

**Comment by JescalLin** [comment]
試試這個  tools/program.py

if idx >= len(train_dataloader):
	break
#把上面这句话修改成下面这个
if idx >= len(train_dataloader)-1:
	break

**Comment by LDOUBLEV** [comment]
> 怎么评估自己的数据集有人知道吗？那个eval.py里面的评估数据是公开数据集

修改配置文件中的数据路径为你的数据路径即可
