### ISSUE TITLE
使用官方提供的east与sast模型进行检测,结果只有一个框如下图,请问是哪里设置错误了呢(使用db模型预测倒是没有问题)

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleOCR#1406]
![det_res_a](https://user-images.githubusercontent.com/65219051/102021404-8f296c00-3dba-11eb-880c-4667ebd8d296.jpg)

![这个](https://user-images.githubusercontent.com/65219051/102021391-6903cc00-3dba-11eb-8fb0-21b58dfff10e.png)

就是从官方的这个链接下载的:https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/algorithm_overview.md

转成预测模型的命令:python tools/export_model.py -c configs/det/det_mv3_east.yml -o Global.checkpoints="./models/det_mv3_east/best_accuracy" Global.save_inference_dir="./inference/EAST/det_mv3_east"

进行预测的命令: python tools/infer/predict_det.py --image_dir="./doc/imgs_en/e.jpg" --det_model_dir="./inference/EAST/det_mv3_east/"

默认参数如下:
   # EAST parmas
    parser.add_argument("--det_east_score_thresh", type=float, default=0.3)
    parser.add_argument("--det_east_cover_thresh", type=float, default=0.1)
    parser.add_argument("--det_east_nms_thresh", type=float, default=0.2)

    # SAST parmas
    parser.add_argument("--det_sast_score_thresh", type=float, default=0.3)
    parser.add_argument("--det_sast_nms_thresh", type=float, default=0.2)
    parser.add_argument("--det_sast_polygon", type=bool, default=False)

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/102033326-1ea04080-3df6-11eb-97ba-6769d9849c1f.png)
使用DB以外的模型预测时还需要传入参数det_algorithm，如 --det_algorithm=EAST

**Comment by yizhipipixia** [comment]
> ![图片](https://user-images.githubusercontent.com/25809855/102033326-1ea04080-3df6-11eb-97ba-6769d9849c1f.png)
> 使用DB以外的模型预测时还需要设定参数det_algorithm，如--det_algorithm = EAST



> ![图片](https://user-images.githubusercontent.com/25809855/102033326-1ea04080-3df6-11eb-97ba-6769d9849c1f.png)
> 使用DB以外的模型预测时还需要设定参数det_algorithm，如--det_algorithm = EAST

非常谢谢 ok了
