### ISSUE TITLE
❗❗❗BUG: Python中指定 det=False 不生效，只有命令行可用

### ISSUE THREAD

**Issue by wwfra** [PaddlePaddle/PaddleOCR#14068]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

# det=False无效
### python环境中：
`det_model_dir='./ch_PP-OCRv4_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_id=0, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, invert=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=False, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv4', output='./output', page_num=0`

### 命令行环境中：
`det_model_dir=m=0`
其他地方都一样

### 🏃‍♂️ Environment (运行环境)

OS: Windows 10 专业版 22H2
Python: 3.8.20
Environment: Jupyter

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

`ocr_engine = PaddleOCR(show_log=True, use_gpu=True, det_limit_side_len=1440, det=False, table=False)`
`ocr_res = ocr_engine.ocr(text_region_np, cls=False)`

**Comment by wwfra** [comment]
源码什么的都没改动过，保持默认

**Comment by wwfra** [comment]
Python的paddleocr whl
Version: 2.8.1

**Comment by Liyulingyue** [comment]
这个问题是命令行的处理逻辑的问题，在python脚本中确实没有生效

**Comment by GreatV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/661cda1289827f349d3f811e5067c71e91ad8341/paddleocr.py#L955-L973 命令行里会根据传入参数重新设置一下

**Comment by wwfra** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/661cda1289827f349d3f811e5067c71e91ad8341/paddleocr.py#L955-L973
> 
> 命令行里会根据传入参数重新设置一下

那问题不是还没解决么，代码中传入参数无效，这仍然是个bug，怎么直接给结束了

**Comment by GreatV** [comment]
@wwfra 得在调用ocr.ocr时显式指定det=False

**Comment by GreatV** [comment]
欢迎提交PR修复这个问题

**Comment by wwfra** [comment]
> 这个问题是命令行的处理逻辑的问题，在python脚本中确实没有生效

是的，在python脚本中无法生效，是否是whl中的代码bug

**Comment by wwfra** [comment]
> ocr_res = ocr_engine.ocr(text_region_np, cls=False)

意思是在
ocr_res = ocr_engine.ocr(text_region_np, cls=False, det=False)
对吗

**Comment by Liyulingyue** [comment]
> > ocr_res = ocr_engine.ocr(text_region_np, cls=False)
> 
> 意思是在 ocr_res = ocr_engine.ocr(text_region_np, cls=False, det=False) 对吗

是的
