### ISSUE TITLE
Shapely installation package link broken 

### ISSUE THREAD

**Issue by Haseeeb21** [PaddlePaddle/PaddleOCR#14075]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

https://github.com/PaddlePaddle/PaddleOCR/blob/main/docs/ppocr/installation.md

![image](https://github.com/user-attachments/assets/c2db60dd-4058-4100-87eb-cb3e477bce12)

The link `here` is not working

### 🏃‍♂️ Environment (运行环境)

Windows 11

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

Fix the hyperlink

**Comment by Liyulingyue** [comment]
The English Docs is not updated, you can install with `pip` directly.

**Comment by GreatV** [comment]
Hi @Haseeeb21, you can now install `shapely` using `pip install shapely`. Just ignore the note information.
