### ISSUE TITLE
paddleocr有裁剪单词并命名为自己名字图片的代码吗,没有的话我整理下贡献一个

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleOCR#1407]
![artisan=0 99999493](https://user-images.githubusercontent.com/65219051/102036013-cc165280-3dfc-11eb-8019-5bda3a888ef4.jpg)
![atar=0 99994594](https://user-images.githubusercontent.com/65219051/102036017-cde01600-3dfc-11eb-88a2-4e0c8b671406.jpg)
大概长这样,就是根据检测模型的坐标裁剪后,又根据识别模型进行重命名

**Comment by littletomatodonkey** [comment]
可以 欢迎你的贡献，不过可能需要注意特殊字符是否对文件名造成冲突

**Comment by yizhipipixia** [comment]
好的
