### ISSUE TITLE
M3 芯片电脑在进行 OCR 识别是会一直卡住不动

### ISSUE THREAD

**Issue by hb-2017** [PaddlePaddle/PaddleOCR#14086]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

正常使用 ocr 进行文字识别的时候，会一直卡在 result = ocr.ocr(image_resized, cls=True) 这一行不动，也没有日志

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/fd4a0a80-34d9-4b14-848d-67b6a2c08afe">

### 🏃‍♂️ Environment (运行环境)

![image](https://github.com/user-attachments/assets/4bced6fc-c438-4194-8e77-ded3825bbe96)

(.venv3.9) mark@Mark dnfm-yolo-tutorial % pip list | grep paddle
paddleocr                 2.9.1
paddlepaddle              2.6.2

python 版本：3.9

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

import cv2
    from paddleocr import PaddleOCR

    # 初始化 OCR 模型
    ocr = PaddleOCR(use_angle_cls=True, lang='en', use_gpu=False)  # 使用 CPU

    # 使用 OpenCV 读取图片
    image_path = '/Users/mark/Downloads/ppocr_img/imgs_words/ch/word_1.jpg'
    image = cv2.imread(image_path)

    # 将图像从 BGR 转换为 RGB，并调整尺寸
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image_resized = cv2.resize(image_rgb, (640, 480))  # 调整为适合的尺寸

    # 进行文字识别

    result = ocr.ocr(image_resized, cls=True)

    # 输出识别结果
    for line in result:
        for word_info in line:
            text = word_info[1][0]
            confidence = word_info[1][1]
            print(f'Text: {text}, Confidence: {confidence}')

**Comment by GreatV** [comment]
python -m pip install paddlepaddle==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
