### ISSUE TITLE
CUDA11.8环境下报错Could not load library libcublasLt.so.10.

### ISSUE THREAD

**Issue by ffiioonnaa** [PaddlePaddle/PaddleOCR#14081]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

请问通过pip install --upgrade paddleocr这个方式安装的paddleocr能否支持CUDA11，目前尝试了几个版本的paddleocr，都报了错：Could not load library libcublasLt.so.10. Error: libcublasLt.so.10: cannot open shared object file: No such file or directory
环境：paddlepaddle-gpu          2.6.1
           CUDA 11.8
           paddleocr 2.9.1

### 🏃‍♂️ Environment (运行环境)

paddlepaddle-gpu          2.6.1
           CUDA 11.8
           paddleocr 2.9.1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

from paddleocr import PaddleOCR
text_detector = PaddleOCR(use_angle_cls=True, use_gpu=True) 
self.text_detector.ocr(frame, cls=True)

**Comment by ffiioonnaa** [comment]
> 先按照如下链接检查paddle框架是否安装正确 https://www.paddlepaddle.org.cn/install/quick

是正确的，运行了paddle.utils.run_check()，显示PaddlePaddle works well on 4 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by GreatV** [comment]
cudnn也要对应上

**Comment by ffiioonnaa** [comment]
> cudnn也要对应上
我的报错是找不到libcublasLt.so.10，这个是cuda自带的吧，而且比较奇怪的是，我安装的cuda11版本的paddle，为什么运行的时候要去找libcublasLt.so.10呢，我的环境里面只有libcublasLt.so.11

**Comment by GreatV** [comment]
你的paddle框架是咋安装的

**Comment by ffiioonnaa** [comment]
> 你的paddle框架是咋安装的，重建一下虚拟环境再安装一遍试试
完整安装过程，请大佬帮忙看看，cuda 11.3
1. conda create --name paddle python=3.8
2. python -m pip install paddlepaddle-gpu==2.6.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
3. pip install paddleocr
4. paddle.utils.run_check() 返回：
Running verify PaddlePaddle program ... 
I1101 10:55:17.123566 2701378 program_interpreter.cc:212] New Executor is Running.
W1101 10:55:17.123968 2701378 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.2, Runtime API Version: 11.3
W1101 10:55:17.135496 2701378 gpu_resources.cc:164] device: 0, cuDNN Version: 8.7.
I1101 10:55:20.219902 2701378 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
5. class SubtitleDetect:
    def __init__(self):
        self.text_detector = PaddleOCR(use_angle_cls=True, use_gpu=True) 
        
    def detect_subtitle(self, frame):
        result = self.text_detector.ocr(frame, cls=True)
        return result
运行到result = self.text_detector.ocr(frame, cls=True)的时候Could not load library libcublasLt.so.10. Error: libcublasLt.so.10: cannot open shared object file: No such file or directory

**Comment by GreatV** [comment]
cuda 和 cudnn安装好了吗，且环境变量中有没有

**Comment by ffiioonnaa** [comment]
> cuda 和 cudnn安装好了吗，且环境变量中有没有

安装的cuda11.3，cudnn Version: 8.7. 环境变量中也有

**Comment by GreatV** [comment]
无法复现你的问题

**Comment by UserWangZz** [comment]
尝试一下docker安装吧，可能和系统环境有关系
