### ISSUE TITLE
求大佬给个思路,怎样才能不把逗号识别成y

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleOCR#1408]
![lemony=0 984543](https://user-images.githubusercontent.com/65219051/102036461-d84edf80-3dfd-11eb-97b8-52935d1fdb94.jpg)
![meatsy=0 9998738](https://user-images.githubusercontent.com/65219051/102036474-e270de00-3dfd-11eb-8d8e-caf1abb7c5b6.jpg)
用的是官方提供的名叫rec_r34_vd_none_bilstm_ctc的识别模型,用的时候识别准确度很好,就是老爱把逗号识别成y有时也识别成x,
本人小白初次使用,不知道该怎么进行调整,希望大家给些意见, 比如内否换backbone, 调整输出图片参数大小等

**Comment by yizhipipixia** [comment]
![@_IQHG$E N20CYF_G$H527N](https://user-images.githubusercontent.com/65219051/102036828-d20d3300-3dfe-11eb-8aba-4b57c2dcdc65.png)
![45JJI900R4Q0ECEE%`E2JKE](https://user-images.githubusercontent.com/65219051/102036853-e3563f80-3dfe-11eb-84dc-a1a55934058f.png)

**Comment by tink2123** [comment]
rec_r34_vd_none_bilstm_ctc 的识别模型只支持26个英文字母+10个数字，本事不支持标点符号。可以尝试使用【ppocr 中文模型】 或 添加自己的数据进行finetune
