### ISSUE TITLE
ppocr/data/reader_main.py ，缺少test_reade方法。import 错误

### ISSUE THREAD

**Issue by coopot** [PaddlePaddle/PaddleOCR#141]
环境：studio
执行命令：
python3 tools/infer_rec.py -c configs/rec/rec_chinese_lite_train.yml -o Global.checkpoints=./output/rec_CRNN/best_accuracy TestReader.infer_img=./test_img/0422camdata_0422_1566.jpg
出现错误：
ImportError: cannot import name 'test_reader' from 'ppocr.data.reader_main' (/home/aistudio/ppocr/data/reader_main.py)
检查结果：
ppocr/data/reader_main.py 
这个文件里面确实没有test_reader这个方法

**Comment by LDOUBLEV** [comment]
试下更新代码，使用最新的PaddleOCR  develop分支的代码。
或者使用官方的AIstudio教程：https://aistudio.baidu.com/aistudio/projectdetail/467229
