### ISSUE TITLE
Wrong Input Initialzation for KIE SER Prediction with vi-LayoutXLM in ONNX / 使用ONNX模型进行SER推理时，存在错误的输入初始化

### ISSUE THREAD

**Issue by FarV-Ma** [PaddlePaddle/PaddleOCR#14107]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

When enabled `--use_onnx` arg for `predict_kie_token_ser.py` with vi-LayoutXLM ONNX model transfered by Paddle2ONNX, there would be an error being raised:
当在  `predict_kie_token_ser.py` 启用 `--use_onnx` arg以使用vi-LayoutXLM的ONNX模型进行推理时，出现以下报错：

```python
Traceback (most recent call last):
  File "kie/predict_kie_token_ser_official.py", line 185, in <module>
    main(parse_args())
  File "kie/predict_kie_token_ser_official.py", line 155, in main
    ser_res, _, elapse = ser_predictor(img)
  File "kie/predict_kie_token_ser_official.py", line 119, in __call__
    for idx in range(len(self.input_tensor)):
TypeError: object of type 'onnxruntime.capi.onnxruntime_pybind11_state.NodeArg' has no len()
```

With code reviewed, we found that it was caused by line 224 in `tools/infer/utillity.py` :
经查，报错的根源应当是 `tools/infer/utillity.py` 第224行：
```python
224        return sess, sess.get_inputs()[0], None, None
```

For vi-LayoutXLM, the number of model input should be 4, not 1, so that it should not be selected only with the "zero" one in 
 `sess.get_inputs()` .
对于vi-LayoutXLM，模型的输入数量为4，而不是1（类似det/cls/rec模型），故不应当在这里只选定 `sess.get_inputs()` 返回列表中的第一个。

At the same time, once the onnx input returning changed, code in  `predict_kie_token_ser.py` may also need to be changed.
同步地，当onnx input数量出现变化，原始推理代码也可能需要被修改。

### 🏃‍♂️ Environment (运行环境)

```bash
OS: Ubuntu 20.04.6 LTS Server
Environment(brief):
- Python=3.8.0
- paddlepaddle-gpu=2.6.0
- paddle2onnx=1.2.7
- onnx=1.13.1
- onnxruntime=1.19.0
RAM: 512GB
CPU: Intel Xeon Platinum 8336C (128) @ 3.500GHz
GPU: NVIDIA A800 80GB PCIe
CUDA: 12.2
```
**MODEL MAY NOT BE LOADED TO GPU BEFORE ERROR RAISED**

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

working_dir = `{PaddleOCR Project}/ppstructure/`

Changes in `predict_kie_token_ser.py`:
```python
41   class SerPredictor(object):
42       def __init__(self, args):
43           self.ocr_engine = PaddleOCR(
44               use_angle_cls=args.use_angle_cls,
45               det_model_dir=args.det_model_dir,
46               rec_model_dir=args.rec_model_dir,
47               cls_model_dir=args.cls_model_dir,
48 ++            use_onnx=args.use_onnx,
```

Predict command:

```bash
python3 kie/predict_kie_token_ser_official.py \
--kie_algorithm=LayoutXLM \
--use_onnx True \
--ser_model_dir=inference_onnx/ser_xfund_onnx/ser_onnx_rt1-19-0_Oct22F/model.onnx \
--image_dir=./docs/kie/input/zh_val_42.jpg \
--ser_dict_path={XFUND_DIR}/class_list_xfun.txt \
--ocr_order_method="tb-yx" \
--det_model_dir=inference_onnx/det_onnx/model.onnx \
--rec_model_dir=inference_onnx/rec_onnx/model.onnx \
--cls_model_dir=inference_onnx/cls_onnx/model.onnx
```

**Comment by Alex37882388** [comment]
I have the same problem with you. I will try to submit a PR later to fix it.

**Comment by FarV-Ma** [comment]
> I have the same problem with you. I will try to submit a PR later to fix it.

Solved. THX!
