### ISSUE TITLE
各位大神，paddleocr 怎么实现内存回收，识别一张就几个G的内存一直占着没释放

### ISSUE THREAD

**Issue by ticshen2019** [PaddlePaddle/PaddleOCR#1410]
各位大神，paddleocr 怎么实现内存回收，识别一张就几个G的内存一直占着没释放

**Comment by littletomatodonkey** [comment]
程序启动之后，需要一些基础的内存来保证预测库的运行，kill之后应该就可以释放了

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。

**Comment by suparek** [comment]
@LDOUBLEV 同问，GPU状态下识别几张后内存占完了，一直不释放。

**Comment by suparek** [comment]
![image](https://user-images.githubusercontent.com/9245996/109944180-ecc1ba80-7d10-11eb-8e4f-a96d15d9dcf8.png)

**Comment by shengzhe8688** [comment]
不知各位的问题最终怎么解决了，官方给个有效解决方案呀
