### ISSUE TITLE
ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

### ISSUE THREAD

**Issue by dsamarth08** [PaddlePaddle/PaddleOCR#14109]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
While executing 'predict_system.py'  I have set the rec_image_shape parameter as rec_image_shape='3,32,320'. But even after specifying the value for the parameter system is still not able to recognize the value

**Informations (please complete the following information):**
 - Inference engine for deployment: CPU (windows)
 - Why convert to onnx：ONNX is already implemented so to use the additional functionality
 - Paddle2ONNX Version: paddle2onnx==1.0.6
 - Email/Wechat/Phone: NA

**Screenshots**: 
<img width="710" alt="image" src="https://github.com/user-attachments/assets/64723a4a-29bd-47c6-88b4-5d244182b630">

**Additional context**: issue is not only observed for paddle2onnx but also observed for paddle.
The command which I have executed is given below:

python -m predict_system.py --use_gpu=False \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer \
--rec_model_dir=./inference/en_PP-OCRv3_rec_infer \
--det_model_dir=./inference/en_PP-OCRv3_det_infer \
--image_dir=doc/imgs_en/img_12.jpg \
--rec_char_dict_path=ppocr/utils/en_dict.txt \
--rec_image_shape='3,32,320'

(Note: I have also tried giving the shape in different but the issue  still persists. --rec_image_shape="3,32,320",  
--rec_image_shape "3,32,320", --rec_image_shape 3,32,320

**Comment by GreatV** [comment]
please refer to: https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/infer_deploy/python_infer.html#_4

**Comment by ChrisEvans2** [comment]
https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/infer_deploy/python_infer.html#_4 this website now is not found "404"
