### ISSUE TITLE
paddleocr返回每个字的坐标

### ISSUE THREAD

**Issue by feilu886** [PaddlePaddle/PaddleOCR#1412]
paddleocr可以返回每个文字的坐标框的坐标吗？

**Comment by WenmuZhou** [comment]
不能

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
