### ISSUE TITLE
识别一张不带文字的图片会报错

### ISSUE THREAD

**Issue by tjpgt** [PaddlePaddle/PaddleOCR#14130]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

  使用一张无任何文字的图片，运行paddleocr --image_dir ./4k.jpg    --use_gpu false --show_log=false，报错
```
[2024/10/31 01:35:55] ppocr INFO: for usage help, please use `paddleocr --help`
[2024/10/31 01:35:56] ppocr INFO: **********./4k.jpg**********
Traceback (most recent call last):
  File "/usr/local/bin/paddleocr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paddleocr/paddleocr.py", line 978, in main
    for line in res:
TypeError: 'NoneType' object is not iterable
```

应该是下面这段代码有问题，res 也需要判断不是None

```
 if result is not None:
                lines = []
                for res in result:
                    for line in res:
                        logger.info(line)
                        lines.append(pprint.pformat(line) + "\n")
```

### 🏃‍♂️ Environment (运行环境)

  paddlepaddle版本3.0.0b1，paddleocr应该是最新稳定版

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

我用的dockerfile:
```
FROM node:18.16.0

WORKDIR /app
COPY . .

RUN apt update && apt install -y libgl1 python3-pip
RUN pip install --break-system-packages  paddlepaddle==3.0.0b1 paddleocr
RUN paddleocr --image_dir ./1.jpg    --use_gpu false --show_log=false

CMD [ "node", "index" ]
```

**Comment by GreatV** [comment]
已修复 
- #14132
