### ISSUE TITLE
怎么输出debug级的日志？

### ISSUE THREAD

**Issue by zjlw** [PaddlePaddle/PaddleOCR#14157]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

分布式训练卡住，想通过debug日志找到是什么原因导致的

### 🏃‍♂️ Environment (运行环境)

官方镜像：registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda12.0-cudnn8.9-trt8.6-gcc12.2
paddle：2.6.1.post120
l40s显卡*4
### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

 python -m paddle.distributed.launch --log_dir=./log_0_1/ --gpus "0,1,2,3" python tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_teacher.yml

**Comment by GreatV** [comment]
export GLOG_v=100
