### ISSUE TITLE
识别模型微调速度很慢

### ISSUE THREAD

**Issue by flow3rdown** [PaddlePaddle/PaddleOCR#14162]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/158c5209-99a1-47d6-987c-677c3766bdf1">

用约80w数据+8卡去训练v4识别模型发现速度很慢，根据log观察到隔几个batch avg_reader_cost花费的时间就会增大，请问这是什么原因？

### 🏃‍♂️ Environment (运行环境)

paddleocr =2.9.1
paddlepaddle-gpu=3.0.0b1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

使用的ch_PP-OCRv4_rec.yaml进行的训练

**Comment by flow3rdown** [comment]
@jzhang533 @kerneltravel @wencan @sdcb  有人能帮忙看一下吗

**Comment by UserWangZz** [comment]
这个可能与磁盘读写有关系，尝试降低batchsize试试
