### ISSUE TITLE
paddlepaddle安装包是否支持mac M3？目前安装后import paddle报错zsh: illegal hardware instruction  python

### ISSUE THREAD

**Issue by sunyclj** [PaddlePaddle/PaddleOCR#14160]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

paddle paddle版本2.6.3 ，mac M1安装，报错zsh: illegal hardware instruction  python

### 🏃‍♂️ Environment (运行环境)

Package                Version
---------------------- -----------
albucore               0.0.13
albumentations         1.4.10
annotated-types        0.7.0
anyio                  4.6.2.post1
astor                  0.8.1
beautifulsoup4         4.12.3
certifi                2024.8.30
charset-normalizer     3.4.0
coloredlogs            15.0.1
contourpy              1.3.0
cycler                 0.12.1
Cython                 3.0.11
decorator              5.1.1
exceptiongroup         1.2.2
fire                   0.7.0
flatbuffers            24.3.25
fonttools              4.54.1
h11                    0.14.0
httpcore               1.0.6
httpx                  0.27.2
humanfriendly          10.0
idna                   3.10
imageio                2.36.0
imgaug                 0.4.0
importlib_resources    6.4.5
joblib                 1.4.2
kiwisolver             1.4.7
lazy_loader            0.4
lmdb                   1.5.1
lxml                   5.3.0
matplotlib             3.9.2
mpmath                 1.3.0
networkx               3.2.1
numpy                  1.26.4
onnxruntime            1.19.2
opencv-contrib-python  4.10.0.84
opencv-python          4.10.0.84
opencv-python-headless 4.10.0.84
opt-einsum             3.3.0
packaging              24.1
paddle2onnx            1.0.9
paddleocr              2.9.1
paddlepaddle           2.6.2
pillow                 11.0.0
pip                    24.2
protobuf               5.28.3
pyclipper              1.3.0.post6
pydantic               2.9.2
pydantic_core          2.23.4
pyparsing              3.2.0
python-dateutil        2.9.0.post0
python-docx            1.1.2
PyYAML                 6.0.2
RapidFuzz              3.10.1
requests               2.32.3
scikit-image           0.24.0
scikit-learn           1.5.2
scipy                  1.13.1
setuptools             75.1.0
shapely                2.0.6
six                    1.16.0
sniffio                1.3.1
soupsieve              2.6
sympy                  1.13.3
termcolor              2.5.0
threadpoolctl          3.5.0
tifffile               2024.8.30
tomli                  2.0.2
tqdm                   4.66.6
typing_extensions      4.12.2
urllib3                2.2.3
wheel                  0.44.0
zipp                   3.20.2

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python tools/infer/predict_system.py --image_dir="../5645_id.jpg" --det_model_dir="./PP-OCRv4/预训练权重/ch_PP-OCRv4_det_infer/" --cls_model_dir="./PP-OCRv4/预训练权重/ch_ppocr_mobile_v2.0_cls_infer" --rec_model_dir="./PP-OCRv4/预训练权重/ch_PP-OCRv4_rec_infer" --use_angle_cls=true

**Comment by sunyclj** [comment]
> ### 🔎 Search before asking
> * [x]  I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
> * [x]  I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
> * [x]  I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.
> 
> ### 🐛 Bug (问题描述)
> paddle paddle版本2.6.3 ，mac M1安装，报错zsh: illegal hardware instruction python
> 
> ### 🏃‍♂️ Environment (运行环境)
> Package Version
> 
> albucore 0.0.13 albumentations 1.4.10 annotated-types 0.7.0 anyio 4.6.2.post1 astor 0.8.1 beautifulsoup4 4.12.3 certifi 2024.8.30 charset-normalizer 3.4.0 coloredlogs 15.0.1 contourpy 1.3.0 cycler 0.12.1 Cython 3.0.11 decorator 5.1.1 exceptiongroup 1.2.2 fire 0.7.0 flatbuffers 24.3.25 fonttools 4.54.1 h11 0.14.0 httpcore 1.0.6 httpx 0.27.2 humanfriendly 10.0 idna 3.10 imageio 2.36.0 imgaug 0.4.0 importlib_resources 6.4.5 joblib 1.4.2 kiwisolver 1.4.7 lazy_loader 0.4 lmdb 1.5.1 lxml 5.3.0 matplotlib 3.9.2 mpmath 1.3.0 networkx 3.2.1 numpy 1.26.4 onnxruntime 1.19.2 opencv-contrib-python 4.10.0.84 opencv-python 4.10.0.84 opencv-python-headless 4.10.0.84 opt-einsum 3.3.0 packaging 24.1 paddle2onnx 1.0.9 paddleocr 2.9.1 paddlepaddle 2.6.2 pillow 11.0.0 pip 24.2 protobuf 5.28.3 pyclipper 1.3.0.post6 pydantic 2.9.2 pydantic_core 2.23.4 pyparsing 3.2.0 python-dateutil 2.9.0.post0 python-docx 1.1.2 PyYAML 6.0.2 RapidFuzz 3.10.1 requests 2.32.3 scikit-image 0.24.0 scikit-learn 1.5.2 scipy 1.13.1 setuptools 75.1.0 shapely 2.0.6 six 1.16.0 sniffio 1.3.1 soupsieve 2.6 sympy 1.13.3 termcolor 2.5.0 threadpoolctl 3.5.0 tifffile 2024.8.30 tomli 2.0.2 tqdm 4.66.6 typing_extensions 4.12.2 urllib3 2.2.3 wheel 0.44.0 zipp 3.20.2
> 
> ### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)
> python tools/infer/predict_system.py --image_dir="../5645_id.jpg" --det_model_dir="./PP-OCRv4/预训练权重/ch_PP-OCRv4_det_infer/" --cls_model_dir="./PP-OCRv4/预训练权重/ch_ppocr_mobile_v2.0_cls_infer" --rec_model_dir="./PP-OCRv4/预训练权重/ch_PP-OCRv4_rec_infer" --use_angle_cls=true

mac M3安装

**Comment by UserWangZz** [comment]
尝试安装paddlepaddle3.0版本
