### ISSUE TITLE
显存最低要求多少

### ISSUE THREAD

**Issue by qybing** [PaddlePaddle/PaddleOCR#1416]
中英文通用OCR模型显存最低要求多少

**Comment by tink2123** [comment]
没有最低要求，如果显存较小的话，训练时减小batch_size就可以

**Comment by qybing** [comment]
@tink2123 在识别的时候，中英文通用OCR模型显存最低要求多少？

**Comment by LDOUBLEV** [comment]
> @tink2123 在识别的时候，中英文通用OCR模型显存最低要求多少？

至少要5G，只是识别模型的话，4G够用了
