### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train_data/XFUND/class_list_xfun.txt'

### ISSUE THREAD

**Issue by sunyclj** [PaddlePaddle/PaddleOCR#14178]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

进行关键信息抽取，执行：
python3 tools/infer_kie_token_ser.py \\
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg
  报错FileNotFoundError: [Errno 2] No such file or directory: 'train_data/XFUND/class_list_xfun.txt'
这是什么文件呢？为什么推理需要用到这个文件？

### 🏃‍♂️ Environment (运行环境)

paddle

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python3 tools/infer_kie_token_ser.py \\
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg

**Comment by GreatV** [comment]
### 关于 `class_list_xfun.txt` 文件

`class_list_xfun.txt` 是一个**类别列表文件**，通常用于 **关键实体信息抽取（KIE）** 任务。在使用基于 `PaddleOCR` 的 `LayoutXLM` 模型时，这个文件用于定义所有类别或标签，用于指导模型在推理阶段识别和分类不同的文本实体。  

具体来说，这个文件包含了模型要提取的每个类（如发票、日期、金额、签名等）的标签列表。

### 为什么推理阶段需要这个文件？

推理阶段使用 `class_list_xfun.txt` 文件是因为：
1. **标签映射**：模型需要知道要提取和分类哪些标签，才能正确地输出抽取的关键信息。
2. **一致性**：推理阶段的标签设置需要与训练阶段一致，以确保模型能正确地映射类别。
