### ISSUE TITLE
多卡训练时train.py --gpus "0,1" 参数报错

### ISSUE THREAD

**Issue by rainote2020** [PaddlePaddle/PaddleOCR#14195]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

**前情提要：**
已经跑通了单gpu的识别模型完整训练过程。过程中没有遇到任何问题，结果也与预期相符。
并且使用paddle.utils.run_check()也提示两张卡都跑的挺well的。

> PaddlePaddle works well on 2 GPUs.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

因此关于其他细节部分就不多介绍了。

**具体报错命令：**

> python3 -m paddle.distributed.launch   PaddleOCR/tools/train.py --gpus "0,1" -c en_PP-OCRv3_rec.yml -o Global.pretrained_model=./en_PP-OCRv3_rec_train/best_accuracy.pdparams

其中配置文件里仅改了字典、数据集和batch_size_per_card、learning_rate。其他均没有改动。

**报错日志：**

> LAUNCH INFO 2024-11-11 17:15:28,296 ------------------------- ERROR LOG DETAIL -------------------------
> /usr/local/lib/python3.10/dist-packages/paddle/utils/cpp_extension/extension_utils.py:686: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
>   warnings.warn(warning_message)
> usage: train.py [-h] [-c CONFIG] [-o OPT [OPT ...]] [-p PROFILER_OPTIONS]
> train.py: error: unrecognized arguments: --gpus 0,1
> LAUNCH INFO 2024-11-11 17:15:28,297 Exit code 2

**补充说明：**
这是个简单直白的不能在直白的报错，但却能够荣登世界上最申必的报错之一。PS：我怎么能知道不使用--gpus要如何多卡训练呢？
总的来说，--gpus是我能找到的官方教程中所有需要多卡训练的地方出现的唯一一种参数。在漫长的搜索过后，我没有找到任何关于这个--gpus参数已经弃用或者更改的说明，令人费解，你们自己不看自己的文档吗？

### 🏃‍♂️ Environment (运行环境)

环境简介：
ubuntu22容器内：Python3.10+cuda12.2+cudnn9+nccl2.19+paddle3.0-gpu      gpu：3090*2 CPU：志强 内存：256G

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

跑train.py，带上--gpus。

**Comment by GreatV** [comment]
请参考 https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/model_train/detection.html#21

**Comment by rainote2020** [comment]
上面这位二话不说把我issue关了的朋友，你想让我参考之前能不能看完我的说明。
你发的这官方文档里，原文如下：
![image](https://github.com/user-attachments/assets/ac9eaeec-b246-411f-98e5-9ddcf815a5cf)

那我我想知道，我的操作和文档里有什么不同？

> 单机多卡训练，通过 --gpus 参数设置使用的GPU ID

我的操作也是加上--gpus '0,1'

那为什么我会报错，哪怕是我nt到把命令写错了，你起码告诉我吧。

**Comment by rainote2020** [comment]
> 请参考 https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/model_train/detection.html#21

上面这位二话不说把我issue关了的朋友，你想让我参考之前能不能看完我的说明。
你发的这官方文档里，原文如下：
image

那我我想知道，我的操作和文档里有什么不同？

单机多卡训练，通过 --gpus 参数设置使用的GPU ID

我的操作也是加上--gpus，我的命令：

python3 -m paddle.distributed.launch PaddleOCR/tools/train.py --gpus "0,1" -c en_PP-OCRv3_rec.yml -o Global.pretrained_model=./en_PP-OCRv3_rec_train/best_accuracy.pdparams

报错，这是什么意思？

usage: train.py [-h] [-c CONFIG] [-o OPT [OPT ...]] [-p PROFILER_OPTIONS]
train.py: error: unrecognized arguments: --gpus 0,1

那为什么我会报错，哪怕是我nt到把命令写错了，你起码告诉我吧。

**Comment by GreatV** [comment]
`python3 -m paddle.distributed.launch --gpus '0,1,2,3'`

**Comment by rainote2020** [comment]
> `python3 -m paddle.distributed.launch --gpus '0,1,2,3'` 这个是`paddle.distributed.launch`的参数

OK。是我自己的问题，随意理解指令了。
