### ISSUE TITLE
Missing "White space" charecter for English text

### ISSUE THREAD

**Issue by Gaploid** [PaddlePaddle/PaddleOCR#1419]
Hi,
First of all thanks for the awesome OCR engine. It seems that's the most accurate one open-sourced engine based on my benchmarking. But I have an issue with recognizing " white space". Below some results and samples.  Could somebody point me in the right direction of how to fix that? I've tried different models (mobile, server), set different languages and etc.

```
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=False, lang='en',use_space_char=True)

img_path = 'middle10836.jpeg'
result = ocr.ocr(img_path, cls=False)
for line in result:
    print(line)

```

Example 1  
![miss-middle10836](https://user-images.githubusercontent.com/6171245/102110305-45ca3280-3e35-11eb-8fc6-df4ce6de2573.jpeg)

` 
dt_boxes num : 1, elapse : 0.07665395736694336
rec_res num  : 1, elapse : 0.0367124080657959
[[[132.0, 21.0], [766.0, 25.0], [766.0, 72.0], [132.0, 69.0]], ['KNOCKEDDOWNWAVECADET', 0.9874495]]
` 

Example 2
![miss-middle8049](https://user-images.githubusercontent.com/6171245/102110629-b07b6e00-3e35-11eb-9657-8b62e6526996.jpeg)

` 
dt_boxes num : 1, elapse : 0.0825192928314209
rec_res num  : 1, elapse : 0.03647327423095703
[[[181.0, 23.0], [717.0, 28.0], [717.0, 71.0], [181.0, 67.0]], ['ELIMINATEDDELUXENUT', 0.9973969]]
` 

Example 3
![middle3508](https://user-images.githubusercontent.com/6171245/102110725-cdb03c80-3e35-11eb-9447-5047e8850e47.jpeg)
` 
dt_boxes num : 1, elapse : 0.07844829559326172
rec_res num  : 1, elapse : 0.030075550079345703
[[[221.0, 18.0], [680.0, 25.0], [680.0, 76.0], [221.0, 69.0]], ['ELIMINATEDVASHY', 0.9242743]]
` 

But sometimes it's working ok Example 4
![example4](https://user-images.githubusercontent.com/6171245/102110894-005a3500-3e36-11eb-841e-d79a1379c7e9.JPG)
` 
dt_boxes num : 1, elapse : 0.0324246883392334
rec_res num  : 1, elapse : 0.029771089553833008
[[[87.0, 17.0], [381.0, 17.0], [381.0, 46.0], [87.0, 46.0]], ['ELIMINATED DOUNKNOWNN', 0.9793866]]
`

**Comment by tink2123** [comment]
Sorry that PaddleOCR is not robust enough to recognize white spaces. The letter spacing in your picture is similar to the size of the spaces, which is more difficult for recognition. You can try to add similar data and finetune to improve model performance.

**Comment by SasiAravind** [comment]
hi @Gaploid , have u solved?. i need help on this.

**Comment by Jane-Ding** [comment]
Thank you for this great OCR engine. It can recognize text from rotated, skewed, curved photos. Compared with Tesseract OCR, I struggled to do preprocess like deskewing and failed. I also have the same problem of "white space". Sometimes it cannot recognize it.
