### ISSUE TITLE
怎样在virtualenv虚拟环境中解决这个问题Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) ？

### ISSUE THREAD

**Issue by WellTung666** [PaddlePaddle/PaddleOCR#142]
----------------------
Error Message Summary:
----------------------
Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

在本地运行的时候也遇到这样的问题，通过添加export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/后解决问题。
在虚拟环境中尝试过在activate文件中添加但是没有用，有没有人知道怎么解决这个问题的？

**Comment by LDOUBLEV** [comment]
麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题

**Comment by WellTung666** [comment]
> 麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题

cuda10.0、 cudnn7.6.5、paddlepaddle-gpu 1.7.2.post107，谢谢。

**Comment by LDOUBLEV** [comment]
> > 麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题
> 
> cuda10.0、 cudnn7.6.5、paddlepaddle-gpu 1.7.2.post107，谢谢。

正常来说export LD_LIBRARY_PATH可以解决，你的虚拟环境是什么，开了一个虚拟机吗？

**Comment by LeeYongchao** [comment]
我也是这个问题，很奇怪为何 paddle 找不到 我自己在.bashrc中定义的  LD_LIBRARY_PATH 呢？

**Comment by WellTung666** [comment]
> > > 麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题
> > 
> > 
> > cuda10.0、 cudnn7.6.5、paddlepaddle-gpu 1.7.2.post107，谢谢。
> 
> 正常来说export LD_LIBRARY_PATH可以解决，你的虚拟环境是什么，开了一个虚拟机吗？

就是virtualenv创建的一个虚拟环境，我想尝试部署到本地服务上。

**Comment by LDOUBLEV** [comment]
> > > > 麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题
> > > 
> > > 
> > > cuda10.0、 cudnn7.6.5、paddlepaddle-gpu 1.7.2.post107，谢谢。
> > 
> > 
> > 正常来说export LD_LIBRARY_PATH可以解决，你的虚拟环境是什么，开了一个虚拟机吗？
> 
> 就是virtualenv创建的一个虚拟环境，我想尝试部署到本地服务上。

是不是要在虚拟机里重新装一个nccl

**Comment by WellTung666** [comment]
> > > > > 麻烦提供下你的系统环境，cuda、cudnn以及paddle版本，方便排查问题
> > > > 
> > > > 
> > > > cuda10.0、 cudnn7.6.5、paddlepaddle-gpu 1.7.2.post107，谢谢。
> > > 
> > > 
> > > 正常来说export LD_LIBRARY_PATH可以解决，你的虚拟环境是什么，开了一个虚拟机吗？
> > 
> > 
> > 就是virtualenv创建的一个虚拟环境，我想尝试部署到本地服务上。
> 
> 是不是要在虚拟机里重新装一个nccl

就是类是anaconda的本地虚拟环境，还需要重装一个吗？

**Comment by LDOUBLEV** [comment]
如果是anaconda环境应该不用重装了，不过在类似conda环境里export应该是有效的才对，你export LD_LIBRARY_PATH之后，执行 env 指令，检查是否正确设置了LD_LIBRARY_PATH

**Comment by WellTung666** [comment]
> 如果是anaconda环境应该不用重装了，不过在类似conda环境里export应该是有效的才对，你export LD_LIBRARY_PATH之后，执行 env 指令，检查是否正确设置了LD_LIBRARY_PATH

我重装虚拟环境和本地服务器后使用CPU能正常使用，但是用GPU的时候报错：
2020-06-11 11:08:44,823-ERROR: Exception on /PaddleOCR/ocr/ [POST]
Traceback (most recent call last):
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/well/myproject/myprojectenv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./PaddleOCR/OCR.py", line 103, in paddleocr
    text_sys = TextSystem()
  File "./PaddleOCR/OCR.py", line 24, in __init__
    self.text_detector = predict_det.TextDetector()
  File "./PaddleOCR/tools/infer/predict_det.py", line 58, in __init__
    utility.create_predictor(mode="det")
  File "./PaddleOCR/tools/infer/utility.py", line 99, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_noavx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::SetDeviceId(int)
3   paddle::AnalysisConfig::fraction_of_gpu_memory_for_pool() const
4   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
5   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: cudaSetDevice failed in paddle::platform::SetDeviced, error code : 3, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: initialization error at (/paddle/paddle/fluid/platform/gpu_info.cc:245)

**Comment by LDOUBLEV** [comment]
可以参考下这个blog里的方法：https://blog.csdn.net/a3335581/article/details/99739707

**Comment by Tuyota** [comment]
> ## Error Message Summary:
> Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory )
> Please specify its path correctly using following ways:
> Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS.
> For instance, issue command: export LD_LIBRARY_PATH=...
> Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)
> 
> 在本地运行的时候也遇到这样的问题，通过添加export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/后解决问题。
> 在虚拟环境中尝试过在activate文件中添加但是没有用，有没有人知道怎么解决这个问题的？

你先用locate libcublas.so定位具体位置，不出意料应该在your_path_to_anconda3/lib/,在.bashrc中添加一下这个路径就可以了
