### ISSUE TITLE
关于数据集大小对于CRNN/SRN模型识别准确度的帮助

### ISSUE THREAD

**Issue by sjtugzx** [PaddlePaddle/PaddleOCR#1420]
你好，在我使用CRNN，模型训练英文文字识别的时候，发现best acc 基本上卡在64就很难再提升，而且训练集明显过拟合。我尝试调试模型尝试了好几天都不见起色，加regularization和distort并没有什么帮助，我不知道是不是我的数据集太小了，使用文本检测模型大概需要什么量级的数据才能调试到一个相对来说比较好的水平？

目前我的数据集使用的是coco-text的数据集，大概8w张图片，进行英文识别。
如果我需要扩充数据集的化打开要扩充到什么程度呐？几十万张？数百万张？

ps 我的期望大概要acc 达到80以上

**Comment by tink2123** [comment]
训练识别模型建议增加训练样本的丰富性，看描述应该是训练集太简单了。distort里尝试增加tia的数据增强看看:https://github.com/PaddlePaddle/PaddleOCR/blob/050a29a9fca487848c5c0ab899bdf197764ad7ff/ppocr/data/rec/img_tools.py#L200
或者多添加一些训练数据。

**Comment by littletomatodonkey** [comment]
可以试着使用mobilenet large的骨干网络，参数量更多一些
