### ISSUE TITLE
AttributeError: 'paddle.base.libpaddle.Tensor' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by agzeroo** [PaddlePaddle/PaddleOCR#14215]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

Hello. 
I encountered the following problem while Training and testing with ch_PP-OCRv3.

<img width="768" alt="image" src="https://github.com/user-attachments/assets/8168ef28-ad87-4e34-a500-91a0fa030ae4">

The above problem occurs when exporting a model for inference after classification learning is completed normally.

When I tested it with the general version (paddlepaddle-gpu 2.5.2, numpy 1.26.3), I added the following code before exporting the model and confirmed that it worked properly.
paddle.disable_static()
paddle.enable_static()
paddle.fluid.dygraph.enable_dygraph()

I know that in order to work properly, params must be entered in the form of Tensor in the load_pretrained_params(model, path) section of save_load.py as in the code below.
![image](https://github.com/user-attachments/assets/ad7c80c4-56c3-4550-8517-24972b6d7d12)

But in the upgraded version, it is displayed as paddle.base.libpaddle.Tensor instead of Tensor.
![image](https://github.com/user-attachments/assets/3222a06f-aae6-43aa-aa6c-c441ed4a30dc)

However, when running with the upgraded version (paddlepaddle-gpu 2.6.2, numpy 2.1.2), fluid was deleted in paddlepaddle-gpu 2.6.2 and could not be used, and an AttributeError occurred (AttributeError: 'paddle.base.libpaddle.Tensor' object has no attribute 'dtype')

The strange thing is that the detection model and recognition model work normally in the upgraded version (paddlepaddle-gpu 2.6.2, numpy 2.1.2). The problem only occurs in the export part of the classification model.

Is there a solution?! I wonder what the cause is...

### 🏃‍♂️ Environment (运行环境)

windows 

paddlepaddle-gpu 2.6.2, numpy 2.1.2

Package                Version
---------------------- -----------
albucore               0.0.19
albumentations         1.4.20
annotated-types        0.7.0
anyio                  4.6.2.post1
astor                  0.8.1
attrdict               2.0.1
babel                  2.16.0
bce-python-sdk         0.9.23
blinker                1.8.2
cachetools             5.5.0
certifi                2024.8.30
charset-normalizer     3.4.0
click                  8.1.7
colorama               0.4.6
contourpy              1.3.0
cssselect              1.2.0
cssutils               2.11.1
cycler                 0.12.1
Cython                 3.0.11
decorator              5.1.1
et_xmlfile             2.0.0
eval_type_backport     0.2.0
fastapi                0.115.4
Flask                  3.0.3
flask-babel            4.0.0
fonttools              4.54.1
future                 1.0.0
h11                    0.14.0
httpcore               1.0.6
httpx                  0.27.2
idna                   3.10
imageio                2.36.0
imgaug                 0.4.0
itsdangerous           2.2.0
Jinja2                 3.1.4
joblib                 1.4.2
kiwisolver             1.4.7
lazy_loader            0.4
lmdb                   1.5.1
lxml                   5.3.0
MarkupSafe             3.0.2
matplotlib             3.9.2
more-itertools         10.5.0
networkx               3.4.2
numpy                  2.1.2
opencv-python          4.10.0.84
opencv-python-headless 4.10.0.84
openpyxl               3.1.5
opt-einsum             3.3.0
packaging              24.1
paddlepaddle-gpu       2.6.2
pandas                 2.2.3
pillow                 11.0.0
pip                    24.2
premailer              3.10.0
protobuf               3.20.2
psutil                 6.1.0
pyclipper              1.3.0.post6
pycryptodome           3.21.0
pydantic               2.9.2
pydantic_core          2.23.4
PyMuPDF                1.21.1
pyparsing              3.2.0
python-dateutil        2.9.0.post0
python-multipart       0.0.16
pytz                   2024.2
PyYAML                 6.0.2
RapidFuzz              3.10.1
rarfile                4.2
requests               2.32.3
scikit-image           0.24.0
scikit-learn           1.5.2
scipy                  1.14.1
setuptools             75.1.0
shapely                2.0.6
six                    1.16.0
sniffio                1.3.1
starlette              0.41.2
stringzilla            3.10.6
threadpoolctl          3.5.0
tifffile               2024.9.20
tqdm                   4.66.6
typing_extensions      4.12.2
tzdata                 2024.2
urllib3                2.2.3
uvicorn                0.32.0
visualdl               2.5.3
Werkzeug               3.0.6
wheel                  0.44.0

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

.

**Comment by GreatV** [comment]
Can you provide a minimal reproducible demo?
