### ISSUE TITLE
ppocrlabel表格标注合并cell的时候，源码中是根据生成的excel文件进行表格单元格合并代码的创建，那岂不是永远也标注不正确？

### ISSUE THREAD

**Issue by HUPg-95** [PaddlePaddle/PaddleOCR#14212]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

ppocrlabel表格标注合并cell的时候，源码中是根据生成的excel文件进行表格单元格合并代码的创建，那岂不是永远也标注不正确？

### 🏃‍♂️ Environment (运行环境)

windows11
Name: PPOCRLabel
Version: 2.1.6

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

![image](https://github.com/user-attachments/assets/b15ae3f5-5896-4f73-a233-d02f3281b1e0)

**Comment by GreatV** [comment]
ppocrlabel相关问题请反馈到 https://github.com/PFCCLab/PPOCRLabel
