### ISSUE TITLE
模型转换后缺失 pdmodel.   用export_model导不出 pdiparams.info 和 pdmodel 只有yml  json  pdiparams

### ISSUE THREAD

**Issue by Imsorryto** [PaddlePaddle/PaddleOCR#14223]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

模型转换后缺失 pdmodel.   用export_model导不出 .inferencepdiparams.info 和 inference.pdmodel 

只有inference.yml  inference.json  inference.pdiparams

Code used to export:
python tools/export_model.py -c configs/det/ch_PP-OCRv4_det_teacher.yml -o Global.pretrained_model="output/ch_PP-OCRv4/best_model/model" Global.save_inference_dir="output/det_db_inference/"

`
W1114 08:30:52.289454 41080 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.7, Runtime API Version: 11.8
W1114 08:30:52.289454 41080 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
[2024/11/14 08:30:52] ppocr INFO: load pretrain successful from output/ch_PP-OCRv4/best_model/model
[2024/11/14 08:30:53] ppocr INFO: inference model is saved to output/det_db_inference/inference
[2024/11/14 08:30:53] ppocr INFO: Export inference config file to output/det_db_inference/inference.yml
`

Export File:

![image](https://github.com/user-attachments/assets/fdb45d3d-8a06-42c5-8d31-17af8e5cb68f)

### 🏃‍♂️ Environment (运行环境)

Window 11 Python 3.10

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python tools/export_model.py -c configs/det/ch_PP-OCRv4_det_teacher.yml -o Global.pretrained_model="output/ch_PP-OCRv4/best_model/model" Global.save_inference_dir="output/det_db_inference/"

**Comment by GreatV** [comment]
paddle 3.0 beta 2 会导出新的 json格式，如果想要pdmodel可以切换到 paddle 3.0 beta 1

**Comment by Imsorryto** [comment]
请问什​​么意思, 怎样转?
我用export_model.py

什么是paddle 3.0 beta @GreatV

**Comment by 22yune** [comment]
我将yolov11转换成paddle模型，也出现这个问题。转换出的推理模型格式是json不是protobuf，在进一步转出paddle-lite时出错。我的paddle版本是3.0。看到这个问题后，降级版本到2.6，成功生成protobuf格式。
