### ISSUE TITLE
pdf转markdown怎么没有说明？

### ISSUE THREAD

**Issue by greatliu** [PaddlePaddle/PaddleOCR#14220]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

是我没找到吗？只看到介绍说加了这个功能，但是在doc里没找到怎么用。

### 🏃‍♂️ Environment (运行环境)

最新版ppocr

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

呃

**Comment by GreatV** [comment]
https://paddlepaddle.github.io/PaddleOCR/latest/ppstructure/quick_start.html?h=markdown#217-markdown

https://paddlepaddle.github.io/PaddleOCR/latest/ppstructure/quick_start.html?h=markdown#227-markdown
