### ISSUE TITLE
win10,c++打包的动态库,开启gpu加速,无法加载动态库,似乎进入了死循环,关掉gpu加速一切正常

### ISSUE THREAD

**Issue by wuliujin** [PaddlePaddle/PaddleOCR#14222]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

win10,c++打包的动态库,开启gpu加速,无法加载动态库,似乎进入了死循环,关掉gpu加速一切正常,我应该怎么找到报错日志?以及如何排查这个问题呢?请官方大大,帮忙看看,万分感谢,

![222](https://github.com/user-attachments/assets/85f90b34-76c5-499d-a2a6-818c31cb69ca)

### 🏃‍♂️ Environment (运行环境)

Paddle version: 2.6.2
GIT COMMIT ID: 8ce0de584c570589117e403322f3d1a0de6554e5
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_IPU: OFF
CUDA version: 11.8
CUDNN version: v8.6
CXX compiler version: 19.29.30145.0
WITH_TENSORRT: ON
TensorRT version: v8.5.1.7
vs:vs2022

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

args.cpp

DEFINE_bool(use_gpu, true, "Infering with GPU or CPU.");

**Comment by GreatV** [comment]
环境变量 set GLOG_v=100

**Comment by GreatV** [comment]
使用的是什么gpu

**Comment by wuliujin** [comment]
我的显卡是1060 5GB; 最新日志显示到设置显卡0就卡住,是我的显卡不支持吗?

![2](https://github.com/user-attachments/assets/22ad3ce5-2a8f-4305-809e-4e4c48c6249d)

**Comment by wuliujin** [comment]
你好请问这个函数的实现是在哪个库呢?我能加日志调试去定位问题吗?

**Comment by GreatV** [comment]
@wuliujin 这个是paddle inference

**Comment by wuliujin** [comment]
那麻烦了,需要改paddle源码,然后打包成paddle_inference动态库,然后再调试,对吗?

**Comment by GreatV** [comment]
是的，可以尝试一下不同版本的paddle inference

**Comment by wuliujin** [comment]
解决了,定义全局变量PPOCR就会这样

**Comment by wuliujin** [comment]
感谢官方的回复
