### ISSUE TITLE
运行python tools/train.py -c pretrain_models/ch_PP-OCRv3_rec_distillation.yml报错，CUDNN_STATUS_INTERNAL_ERROR错误

### ISSUE THREAD

**Issue by laolj** [PaddlePaddle/PaddleOCR#14228]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

运行python tools/train.py -c pretrain_models/ch_PP-OCRv3_rec_distillation.yml报错，
OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.   [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at ..\paddle\phi\kernels\gpu\rnn_kernel.cu.cc:356)

### 🏃‍♂️ Environment (运行环境)

os:window10
cuda 12.0
paddlepaddle 2.7

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

正常运行都不行

**Comment by GreatV** [comment]
搜索一下历史issue，有解决方案

**Comment by laolj** [comment]
4060，我找一下

**Comment by GreatV** [comment]
4060应该没有问题，可能是cuda和cudnn版本和paddle框架要求的版本不兼容

**Comment by laolj** [comment]
我找到问题了torch版本不对，我下载了torch2.5cpu版本的，我换一个版本可以识别cudnn和cuda就可以了，现在是yaml.composer.ComposerError: found undefined alias 'max_text_length'估计是我的参数不对

**Comment by laolj** [comment]
那cuda12对应哪个paddle版本？我应该怎么对比？
