### ISSUE TITLE
部分内容没有识别出来

### ISSUE THREAD

**Issue by forgeyao** [PaddlePaddle/PaddleOCR#14275]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

图片中间的“工程记录“、右下角的防伪码没有识别出来

### 🏃‍♂️ Environment (运行环境)

```
OS: Ubuntu 22.04.1
Python：python3.10
paddleocr: 2.9.1
paddlepaddle: 3.0.0b2

参数：ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer', det_limit_side_len=2560, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.10/dist-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ch', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

测试图片 Url：https://biu-cn.dwstatic.com/file_export/web/common/20241120/3801650898/YFWVUSGEAN-photo.png

输出结果：[[[[[43.0, 175.0], [149.0, 175.0], [149.0, 236.0], [43.0, 236.0]], ('关闭', 0.939062237739563)], [[[1018.0, 179.0], [1124.0, 179.0], [1124.0, 236.0], [1018.0, 236.0]], ('完成', 0.9977211356163025)], [[[657.0, 1395.0], [880.0, 1398.0], [879.0, 1432.0], [657.0, 1429.0]], ('S3 1a1 1875', 0.5381156802177429)]]]

**Comment by GreatV** [comment]
根据您提供的信息和问题描述，以下是针对 **"部分内容没有识别出来"** 的可能原因及解决方案：

---

### 原因分析

1. **识别效果不理想的可能原因**：
   - **图片分辨率**：图像的分辨率可能较低，导致模型无法清晰检测到目标区域。
   - **检测模型参数设置不当**：如 `det_db_thresh`（检测阈值）或 `det_db_box_thresh`（检测框阈值）设置的值可能导致部分区域被忽略。
   - **识别模型对字体/内容的适配性不足**：某些字体类型或格式可能未被模型良好适配。
   - **内容的复杂性**：例如，右下角的防伪码可能字体较小或与背景对比度不够明显，导致检测或识别失败。

2. **在线 Demo 和本地运行效果差异**：
   - **模型版本或参数差异**：在线 Demo 可能使用了最新的模型优化，而本地使用的模型可能存在差异。
   - **推理逻辑不同**：在线 Demo 可能对图像进行了额外的预处理（如分辨率调整、图像增强等）。

3. **表格检测和版面分析问题**：
   - 使用的 `layout_model_dir`（版面分析模型）可能对表格或复杂文档的检测效果不够优化，尤其是在表格/图表和文本区域混杂的情况下。
   - 不同语言的检测模型（如 `lang="ch"` 或 `lang="en"`) 在表格检测的适配性上存在差异。
   - 参数 `layout_score_threshold` 和 `layout_nms_threshold` 可能需要调整以优化表格检测效果。

---

### 解决方案

#### 1. 优化检测和识别参数
   - 修改检测模型的相关阈值，尝试以下设置：
     ```python
     det_db_thresh=0.2  # 检测二值化阈值，增大检测区域
     det_db_box_thresh=0.5  # 检测框阈值，避免过早过滤
     det_db_unclip_ratio=2.0  # 扩展检测框比例，适用于字体较小的场景
     ```
   - 修改识别模型的 `drop_score` 参数（默认值为 `0.5`），尝试降低为 `0.3`，以保留更多低置信度的识别结果：
     ```python
     drop_score=0.3
     ```

#### 2. 增强图像预处理
   - **图像分辨率调整**：确保输入图片的分辨率较高，推荐将图片的长边调整到 `1024px` 或更高，避免过小的内容丢失。
   - **对比度增强**：使用图像处理工具（如 OpenCV）提升图片的对比度，使字体区域更为清晰：
     ```python
     import cv2
     image = cv2.imread('input_image.png')
     enhanced_image = cv2.convertScaleAbs(image, alpha=1.5, beta=0)  # 调高对比度
     cv2.imwrite('enhanced_image.png', enhanced_image)
     ```

#### 3. 使用最新的模型版本
   - **检查模型版本**：确保您使用的是最新的 PP-OCRv4 检测和识别模型。
     下载模型：
     ```bash
     wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar && tar -xf ch_PP-OCRv4_det_infer.tar
     wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar && tar -xf ch_PP-OCRv4_rec_infer.tar
     ```
   - 更新 PaddleOCR 版本：
     ```bash
     pip install --upgrade paddleocr
     ```

#### 4. 针对小字体内容（如防伪码）优化
   - 增大 `det_limit_side_len` 参数（默认值为 `2560`），以提高小字体区域的检测精度：
     ```python
     det_limit_side_len=4000
     ```

#### 5. 针对复杂版面优化
   - 使用适合复杂版面的检测模型（如 `picodet_lcnet_x1_0_fgd_layout_infer`）：
     ```bash
     wget https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar && tar -xf picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
     ```
   - 调整版面分析模型的阈值参数：
     ```python
     layout_score_threshold=0.3  # 检测置信度阈值
     layout_nms_threshold=0.4  # 非极大值抑制阈值
     ```

#### 6. 验证改进后的效果
   - 运行以下代码测试，并保存检测结果：
     ```python
     from paddleocr import PaddleOCR, draw_ocr
     ocr = PaddleOCR(det_model_dir='path_to_new_det_model',
                     rec_model_dir='path_to_new_rec_model',
                     det_db_thresh=0.2, det_db_box_thresh=0.5,
                     drop_score=0.3)
     img_path = 'enhanced_image.png'
     result = ocr.ocr(img_path, cls=True)
     for line in result[0]:
         print(line)
     ```

---

### 参考文档和相关问题
1. **图片识别效果优化技巧**：
   - 官方文档：[PaddleOCR 参数优化](https://paddlepaddle.github.io/PaddleOCR/)
2. **在线 Demo 与本地效果差异**：
   - 相关讨论：[Issue #1015](https://github.com/PaddlePaddle/PaddleOCR/issues/1015)
   - 解决方案中提到：调整 `det_limit_side_len` 和 `drop_score` 参数。
3. **表格检测不准确问题**：
   - 相关讨论：[Discussion #2023](https://github.com/PaddlePaddle/PaddleOCR/discussions/2023)
   - 解决方案中提到：优化版面分析模型参数和使用更高质量的模型。

---

### 总结
通过调整检测和识别模型的参数、增强图像预处理、使用最新模型版本，能够有效提升对复杂内容（如小字体、防伪码、工程记录等）的识别效果。如果仍然无法满足需求，可以考虑训练定制化模型以适配特定场景。

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*

**Comment by forgeyao** [comment]
经过测试，提升图片的对比度可以解决上面的问题。

det_db_thresh、det_db_box_thresh、det_db_unclip_ratio、drop_score 没效果。
图片最长边大于 det_limit_side_len 时，提高 det_limit_side_len  有效。超过了再提高就没效果。
