### ISSUE TITLE
使用predict_system.py 和 predict_rec.py 结果差距非常大

### ISSUE THREAD

**Issue by lvyulv** [PaddlePaddle/PaddleOCR#1429]
你好，我使用自己训练后打包的识别inference模型，使用predict_system.py 和 predict_rec.py 结果差距非常大。
字典路径已更改为自己的字典路径，识别结果阈值也更改为0.0。
请问该如何处理呢？

---
具体情况如下所示：

### 识别所用的图片1：
![识别图片1](https://raw.githubusercontent.com/lvyulv/Picture/lvyulv-test-image/image-10-1.jpg)

* 自训练rec模型，使用 predict_system.py 的命令：
```py
python D:/PaddleOCR/tools/infer/predict_system.py --det_model_dir="D:/PaddleOCR/inference/ch_ppocr_server_v1.1_det_infer"  --rec_model_dir="D:/PaddleOCR/inference/output/rec_japan/infer" --cls_model_dir="D:/PaddleOCR/inference/ch_ppocr_mobile_v1.1_cls_infer"  --image_dir="D:/ll/pic/test/image-10-1.jpg" 
```
* 处理后图片
![处理后图片1](https://raw.githubusercontent.com/lvyulv/Picture/main/image-10-1z.jpg)

* 自训练rec模型，使用 predict_rec.py 的命令：
```py
python D:/PaddleOCR/tools/infer/predict_rec.py --rec_model_dir="D:/PaddleOCR/inference/output/rec_japan/infer" --image_dir="D:/ll/pic/test/image-10-1.jpg" 
```
* 控制台打印结果
```
Predicts of D:/ll/pic/test/image-10-1.jpg:['橇妙愈擦薨扱蒡牝脚凰', 0.86219674]
Total predict time for 1 images:2.079
```
---

### 识别所用的图片2：
![识别图片2](https://raw.githubusercontent.com/lvyulv/Picture/main/image-40-1.jpg)

* 自训练rec模型，使用 predict_system 的命令：
```py
python D:/PaddleOCR/tools/infer/predict_system.py --det_model_dir="D:/PaddleOCR/inference/ch_ppocr_server_v1.1_det_infer"  --rec_model_dir="D:/PaddleOCR/inference/output/rec_japan/infer" --cls_model_dir="D:/PaddleOCR/inference/ch_ppocr_mobile_v1.1_cls_infer" --rec_image_shape="3, 32, 1600" --image_dir="D:/ll/pic/test/image-40-1.jpg"
```
* 处理后图片
![处理后图片2](https://raw.githubusercontent.com/lvyulv/Picture/lvyulv-infer-result-image/image-40-1z.jpg)

* 自训练rec模型，使用 predict_rec.py 的命令：（更改了rec_image_shape）
```py
python D:/PaddleOCR/tools/infer/predict_rec.py --rec_model_dir="D:/PaddleOCR/inference/output/rec_japan/infer" --rec_image_shape="3, 32, 1600" --image_dir="D:/ll/pic/test/image-40-1.jpg" 
```
* 控制台打印结果
```
Predicts of D:/ll/pic/test/image-40-1.jpg:['涙〉雌舞袖珪麞寓梅埋璧灣經錍績囲扈公ｄ滞窄西研吏繹会鑊銑ー菜疱圖け姶插媽瓢椎付箕', 0.86810505]
Total predict time for 1 images:1.612
```

**Comment by tink2123** [comment]
如果您的图片已经是切割好的文本行，则只使用 predict_rec.py 预测即可，不需要走检测分支

**Comment by lvyulv** [comment]
> 如果您的图片已经是切割好的文本行，则只使用 predict_rec.py 预测即可，不需要走检测分支
我训练的图片都是单行文本，但想要达到的效果是检测多行文本，所以还是需要检测这一步。
检测多行文本也试过，效果也不行。

**Comment by littletomatodonkey** [comment]
检测对于这种过长的文本效果可能一般，如果都是长文本情况，则需要对检测模型在你自己的场景中进行微调

**Comment by lvyulv** [comment]
> 
> 
> 检测对于这种过长的文本效果可能一般，如果都是长文本情况，则需要对检测模型在你自己的场景中进行微调

长文本检测只是为了测试极端情况，多行短文本检测效果也是不理想的。
且  predict_rec.py  相关命令对多行文本好像不适用。

请问微调指的是调节代码参数吗？以及可以具体指出修改哪个代码文件或那个参数吗？
还是需要对检测模型重新训练呢？
以下是对10个字的多行文本识别结果，官方给出的模型似乎效果也不太好。
* 自己训练模型
![多行10个字自训练识别结果](https://github.com/lvyulv/Picture/blob/lvyulv-infer-result-image/joint10-1%E8%87%AA%E5%B7%B1%E8%AE%AD%E7%BB%83.png)

* 官方模型（使用的是  **japan_ppocr_mobile_v1.1_rec_infer**  识别模型）
![多行10个字官方模型识别结果](https://raw.githubusercontent.com/lvyulv/Picture/lvyulv-infer-result-image/joint10-1%E5%AE%98%E6%96%B9%E8%AE%AD%E7%BB%83.png)

**Comment by tink2123** [comment]
官方模型是针对通用场景的，识别模型训练时没有加入很多生僻字，因此识别效果不佳。如果您的场景中都是此类文字，还是建议使用自己训练的模型。

看上图的案例，多行文本的在短文本的情况下，检测还是比较准确的。您再优化一下自己的识别模型即可

**Comment by lvyulv** [comment]
> 
> 
> 官方模型是针对通用场景的，识别模型训练时没有加入很多生僻字，因此识别效果不佳。如果您的场景中都是此类文字，还是建议使用自己训练的模型。
> 
> 看上图的案例，多行文本的在短文本的情况下，检测还是比较准确的。您再优化一下自己的识别模型即可

感谢回复。

我训练自己的识别模型的过程是：数据为根据真实场景所用文字合成的，使用官方预训练模型，checkpoints使用自己训练几次后得到的模型。如此训练到test_acc达到0.96。
但识别效果仍不理想，查看FAQ后看到说可用真实数据进行微调。请问微调是否指训练集使用真实数据，不指定checkpoints？
微调使用的数据需要大概在什么量级吗？上万张吗？

**Comment by Luffffffy** [comment]
你好，关于你说 “使用自己训练后打包的识别inference模型”
我想知道你训练的模型是从哪里下载的呢
谢谢！！！

**Comment by LDOUBLEV** [comment]
> 请问微调是否指训练集使用真实数据，不指定checkpoints？ 微调使用的数据需要大概在什么量级吗？上万张吗？

微调是加载PaddleOCR提供的预训练模型，在你的数据上继续训练，我们提供的模型已经收敛的比较好了，在你的数据上继续训练可以增加在你场景上的拟合能力，数据越多越好，可以自行尝试

**Comment by a01163125** [comment]
这个问题我也发现了，而且在2.6 2.9 版本中都有看见。 求大佬解答
