### ISSUE TITLE
轻量化CRNN

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#143]
请问轻量化的CRNN是怎么设计的，有代码可以参考吗

**Comment by LDOUBLEV** [comment]
我们的crnn代码是开源的，轻量化crnn识别的代码：
- backbone：ppocr.modeling.backbones.rec_mobilenet_v3, MobileNetV3
- head: ppocr.modeling.heads.rec_ctc_head,CTCPredict
训练参数配置可以参考配置文件config/rec/rec_chinese_lite_train.yml
