### ISSUE TITLE
paddle 3.0 beta 2 会导出新的 json格式，针对新的格式后续export_model这边有对应更新吗，因为我的是cuda_12.4.r12.4，辛苦回一下

### ISSUE THREAD

**Issue by githubjixin** [PaddlePaddle/PaddleOCR#14319]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

 export_model失败

### 🏃‍♂️ Environment (运行环境)

 cuda_12.4.r12.4

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

。

**Comment by GreatV** [comment]
是有什么问题吗

**Comment by GreatV** [comment]
根据你提供的信息，Paddle 3.0 beta 2 导出的新 JSON 格式可能会导致 `export_model` 过程中出现问题。由于你使用的是 CUDA 12.4 版本，这也可能影响模型导出。

以下是一些可能的解决方案和建议：

1. **确认配置文件路径和内容**：确保你在执行 `export_model.py` 时使用的配置文件路径和内容是正确的。例如，`configs/det/ch_PP-OCRv4_det_teacher.yml` 文件中应该包含所有必要的配置参数。

2. **检查 Paddle 版本兼容性**：确保你使用的 PaddlePaddle 版本与 CUDA 12.4 是兼容的。有时，某些版本的 PaddlePaddle 可能还未完全支持最新的 CUDA 版本。

3. **更新 PaddleOCR**：如果尚未更新，尝试获取 PaddleOCR 的最新版本。开发团队可能已经发布了修复程序来解决与新 JSON 格式相关的问题。

4. **查看已知问题和修复**：在 PaddleOCR 的 [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) 和 [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) 页面中查找是否有类似问题的报告和解决方案。

如果以上方法未能解决问题，建议在 PaddleOCR 的 Issue 页面提交详细的错误报告，以便开发团队能够提供进一步的支持。

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | gpt-4o*
