### ISSUE TITLE
hub serving内存无法回收，疑似内存泄漏

### ISSUE THREAD

**Issue by itscarrot** [PaddlePaddle/PaddleOCR#1437]
在我自己的项目中发现使用检测算法（中文轻量模型）有疑似内存泄漏的问题，内存一直上涨。
之后我用hub serving做了个实验。dockerfile为你们提供的(https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/docker/hubserving/cpu/Dockerfile), 其中修改paddlepaddle版本为2.0.0b0，给docker container的资源为4G，发现预测后内存无法回收一直在增加，预测十张左右的照片后便会把内存填满。

ps,我这边另外一个项目没有用到图像检测，finetune了图像识别模型，运行良好。

麻烦给予解答，谢谢。

**Comment by littletomatodonkey** [comment]
关闭mkldnn还会有这个问题吗？

**Comment by itscarrot** [comment]
我看代码默认没有开启mkldnn，在我自己的项目中mkldnn也是关闭的

**Comment by YAwei666** [comment]
关闭mkldnn，问题相同
