### ISSUE TITLE
中文OCR结果缺少‘嫖’字

### ISSUE THREAD

**Issue by myhloli** [PaddlePaddle/PaddleOCR#14370]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![image](https://github.com/user-attachments/assets/006ba987-4643-4719-ab61-3e52ebca18f7)
本地和在线测试均能复现

### 🏃‍♂️ Environment (运行环境)

本地或在线

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

![image](https://github.com/user-attachments/assets/0e8cb5d8-0367-4387-8ee4-3d2d00079880)

 https://aistudio.baidu.com/community/app/91660/webUI

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/1251

**Comment by GreatV** [comment]
有是有的

https://github.com/PaddlePaddle/PaddleOCR/blob/4cfeb4cce5d5024ea08e67ef76d4f7af02fa6f68/ppocr/utils/ppocr_keys_v1.txt#L3829

**Comment by myhloli** [comment]
emmm, 为啥ocr的时候没这个字呢

**Comment by GreatV** [comment]
有类似的issue，我刚才也试了试sever版本的模型也是检测不出来，估计是之前这个字的训练数据太少了。
- https://github.com/PaddlePaddle/PaddleOCR/issues/14065

**Comment by myhloli** [comment]
可能这个词确实数据比较少😂

**Comment by lordofmetis** [comment]
之前忘了说了，“寻衅滋事”的“衅”字基本上也识别不出，识别成“畔”都算好的了。但总的来说瑕不掩瑜，是非常好用的工具，感谢！

**Comment by cuicheng01** [comment]
您好，最近paddlex会release一个文本识别更强的模型，目前内部测试“嫖”是可以识别的，敬请期待。
