### ISSUE TITLE
OCR识别后输出乱码，字典文档已经设置为中文是正确的

### ISSUE THREAD

**Issue by myBigbug** [PaddlePaddle/PaddleOCR#14381]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

输出乱码:[2024/12/13 18:43:58] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/myOcr/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/myOcr/ch_PP-OCRv4_det_server_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_id=0, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv4', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/home/admin/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/root/myOcr/ch_PP-OCRv4_rec_server_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
('围衍é头睿围汪围招爸μ围睿头围丫é裹粤股裹系粤围围', 0.7224169969558716)
<img width="841" alt="image" src="https://github.com/user-attachments/assets/9df730b6-ce94-44ff-b330-f8e8d032b44b" />

### 🏃‍♂️ Environment (运行环境)

paddleocr                 2.7.0.0
paddlepaddle-gpu          2.5.2.post112
python 3.8.20
cuda 11.2
centOS64位系统
显卡P40 

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

from datetime import datetime
from paddleocr import PaddleOCR
import numpy as np
from PIL import Image
import sys
sys.stdout.recoding = 'utf-8'

import os
print("PYTHONIOENCODING:", os.environ.get('PYTHONIOENCODING'))
print("LANG:", os.environ.get('LANG'))
# 设置环境变量
os.environ['PYTHONIOENCODING'] = 'utf8'

ocr = PaddleOCR(rec_char_dict_path = "/home/admin/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt",det_model_dir = "/root/myOcr/ch_PP-OCRv4_det_infer",rec_model_dir="/root/myOcr/ch_PP-OCRv4_rec_infer",cls_model_dir="/root/myOcr/ch_ppocr_mobile_v2.0_cls_infer",lang='ch') # need to run only once to load model into memory
img_path = '/root/myOcr/test3.png'
img = Image.open(img_path)
# 转换为RGB模式
if img.mode != 'RGB':
    img = img.convert('RGB')
# 转换为numpy数组
img_array = np.array(img)

a = datetime.now()
result = ocr.ocr(img_array, det=False, cls=False)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(type(line))
        text = line[1][0].encode('utf-8').decode('utf-8')
        print(f"识别结果: {text}")
        print(line)
b = datetime.now()
milliseconds = b - a
milliseconds = milliseconds.total_seconds() * 1000

**Comment by GreatV** [comment]
换个显卡试试

**Comment by GreatV** [comment]
或者使用cpu

**Comment by myBigbug** [comment]
> 或者使用cpu

当时使用CPU的时候，没有检测到文字。这是什么原因呢？
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/edf08c73-9ab0-48be-9b39-8d779a796667" />

**Comment by GreatV** [comment]
能提供一张图片，我测试一下。

**Comment by myBigbug** [comment]
> 能提供一张图片，我测试一下。

这张照片，辛苦帮忙看看呢
![133c29293eac29bc](https://github.com/user-attachments/assets/bcc0d3fa-977a-4fc5-bbb2-c37cfd5c310a)

**Comment by GreatV** [comment]
```python
from paddleocr import PaddleOCR
from PIL import Image, ImageDraw, ImageFont

ocr = PaddleOCR(use_angle_cls=True, lang="ch")
img_path = "395930007-bcc0d3fa-977a-4fc5-bbb2-c37cfd5c310a.jpg"
slice = {'horizontal_stride': 300, 'vertical_stride': 500, 'merge_x_thres': 50, 'merge_y_thres': 35}
results = ocr.ocr(img_path, cls=True, slice=slice)

image = Image.open(img_path).convert("RGB")
draw = ImageDraw.Draw(image)
font = ImageFont.truetype("./doc/fonts/simfang.ttf", size=20)  # 根据需要调整大小
# 处理并绘制结果
for res in results:
    for line in res:
        box = [tuple(point) for point in line[0]]

        box = [(min(point[0] for point in box), min(point[1] for point in box)),
               (max(point[0] for point in box), max(point[1] for point in box))]
        txt = line[1][0]
        draw.rectangle(box, outline="black", width=3)
        draw.text((box[0][0], box[0][1] - 25), txt, fill="white", font=font)

image.save("result.jpg")

```

![result](https://github.com/user-attachments/assets/c1089e0f-738f-4e02-9fc1-c539a13eb971)

**Comment by myBigbug** [comment]
> 无法复现
> 
> ```python
> from paddleocr import PaddleOCR
> from PIL import Image, ImageDraw, ImageFont
> 
> ocr = PaddleOCR(use_angle_cls=True, lang="ch")
> img_path = "395930007-bcc0d3fa-977a-4fc5-bbb2-c37cfd5c310a.jpg"
> slice = {'horizontal_stride': 300, 'vertical_stride': 500, 'merge_x_thres': 50, 'merge_y_thres': 35}
> results = ocr.ocr(img_path, cls=True, slice=slice)
> 
> image = Image.open(img_path).convert("RGB")
> draw = ImageDraw.Draw(image)
> font = ImageFont.truetype("./doc/fonts/simfang.ttf", size=20)  # 根据需要调整大小
> # 处理并绘制结果
> for res in results:
>     for line in res:
>         box = [tuple(point) for point in line[0]]
> 
>         box = [(min(point[0] for point in box), min(point[1] for point in box)),
>                (max(point[0] for point in box), max(point[1] for point in box))]
>         txt = line[1][0]
>         draw.rectangle(box, outline="black", width=3)
>         draw.text((box[0][0], box[0][1] - 25), txt, fill="white", font=font)
> 
> image.save("result.jpg")
> ```
> 
> ![result](https://private-user-images.githubusercontent.com/17264618/395938448-c1089e0f-738f-4e02-9fc1-c539a13eb971.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAwMTEsIm5iZiI6MTczNDMzOTcxMSwicGF0aCI6Ii8xNzI2NDYxOC8zOTU5Mzg0NDgtYzEwODllMGYtNzM4Zi00ZTAyLTlmYzEtYzUzOWExM2ViOTcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA5MDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjRjMmM4ZjgyNTcyYjkxNGI3OTBhMmRhYmYyMzRhZTc5MTQyZmRkNDFjM2JjMGU2NDA2YTI3ZmU4MWRmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6o5TEKaqnuw05eTd9PUukiJKSmKdjJJW0U5Q-H42-I)

谢谢你，我在试试其他办法

**Comment by myBigbug** [comment]
我的p40显卡，最终使用了paddlepaddle-gpu==2.4.2 cudatoolkit=11.2 paddleocr==2.6.0 
在python代码里设置了cls=True,det=True后运行程序可以正确得到ocr识别后的结果。
