### ISSUE TITLE
识别出现错别字

### ISSUE THREAD

**Issue by ALittleDruid** [PaddlePaddle/PaddleOCR#14420]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![24482140](https://github.com/user-attachments/assets/b36b2fab-0c1f-4727-8214-7dae9422ef21)
姓名识别有错别字
正确的应该是 谯婉嵘
ch_PP-OCRv3 识别成了 焦婉碟
ch_PP-OCRv4 识别成了 谯婉蝶

### 🏃‍♂️ Environment (运行环境)

Windows 10/11 x64 C++项目
paddle_inference版本为3.0.0-beta2
https://paddle-inference-lib.bj.bcebos.com/3.0.0-beta2/cxx_c/Windows/CPU/x86-64_avx-mkl-vs2019/paddle_inference.zip

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

自带的cpp_infer或者Umi-OCR都能复现这个问题
希望能优化下

**Comment by GreatV** [comment]
需要自己微调一下识别模型

**Comment by ALittleDruid** [comment]
> 需要自己微调一下识别模型

好的，我们试试
