### ISSUE TITLE
推理报错Broadcast dimension mismatch. Operands could not be broadcast together with the shape

### ISSUE THREAD

**Issue by shatang123** [PaddlePaddle/PaddleOCR#14432]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

推理报错
![image](https://github.com/user-attachments/assets/b9a8bc3d-5151-4ea2-b302-2f3ba2123718)
```js
E:\data\conda\paddle_env\python.exe E:\code\paddle_ocr\main.py 
[2024/12/20 17:54:00] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
Traceback (most recent call last):
  File "E:\code\paddle_ocr\main.py", line 11, in <module>
    result = paddleocr.ocr(img)
  File "E:\data\conda\paddle_env\lib\site-packages\paddleocr\paddleocr.py", line 760, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
  File "E:\data\conda\paddle_env\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 144, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "E:\data\conda\paddle_env\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 793, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 3, 20] and the shape of Y = [1, 96, 4, 20]. Received [3] in X is not equal to [4] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_add > error]
```

### 🏃‍♂️ Environment (运行环境)

win11系统
环境安装命令
```js
conda create --name paddle_env python=3.8 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda activate paddle_env
pip install paddlepaddle
pip install paddleocr
pip install opencv-python
```
模型下载路径
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

```python
from paddleocr import PaddleOCR, draw_ocr
import cv2

# 模型下载地址：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md
paddleocr = PaddleOCR(lang='ch', show_log=False,use_gpu=False,
                      det_model_dir=f'E:\\code\paddle_ocr\\model\\ch_PP-OCRv4_det_infer',
                      rec_model_dir=f'E:\\code\paddle_ocr\\model\\ch_PP-OCRv4_det_infer')  # 推理模型路径

img = cv2.imread('E:\\code\\paddle_ocr\\img\\3.png')

result = paddleocr.ocr(img)
for i in range(len(result[0])):
    print(result[0][i][1][0])  # 输出识别结果

```

**Comment by shatang123** [comment]
3.png图片内容
![image](https://github.com/user-attachments/assets/70fb7808-0d73-4ce4-bff3-eb8b631701a6)

**Comment by jingsongliujing** [comment]
![image](https://github.com/user-attachments/assets/1fcced1f-c4a2-40a7-8107-37f66e1e0697)
你检测和识别模型的路径都指向检测了，det模型和rec的模型路径应该分开。

**Comment by shatang123** [comment]
> ![image](https://private-user-images.githubusercontent.com/45508593/397778974-1fcced1f-c4a2-40a7-8107-37f66e1e0697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDA2MTksIm5iZiI6MTczNDk0MDMxOSwicGF0aCI6Ii80NTUwODU5My8zOTc3Nzg5NzQtMWZjY2VkMWYtYzRhMi00MGE3LTgxMDctMzdmNjZlMWUwNjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3NTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZjYxODljY2NmZWU2Y2E1YjBhNjk5NWM3ZmU5ZjhiMzIwMDVkMmU4ZWQ3Yzc3NTM3NTkwOGI1YzI0YWYyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2hRKhqM8nb13aSkvpOWmfih3mwJXsJ78N96IzZtmjQU) 你检测和识别模型的路径都指向检测了，det模型和rec的模型路径应该分开。

了解，我去换下

**Comment by shatang123** [comment]
已解决，是我使用了错误的路径
