### ISSUE TITLE
不管用v3还是v4的模型，出现文本漏检现象

### ISSUE THREAD

**Issue by dragronstranding** [PaddlePaddle/PaddleOCR#14439]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

上图，最上面一行的APP 金东纸业那一行，文本检测不出来，不管是v3还是v4

### 🏃‍♂️ Environment (运行环境)

paddleocr=2.9.2
paddlepaddle=3.0.0b1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

# 初始化 PaddleOCR
paddleocr = PaddleOCR(lang='ch', use_angle_cls=False, show_log=True,
                      det_model_dir='../weights/ch_PP-OCRv4_det_infer',
                      rec_model_dir='../weights/ch_PP-OCRv4_rec_infer'
                      )

**Comment by dragronstranding** [comment]
> ### 🔎 询问前先搜索
> * [x] 我搜索了 PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/)，没有找到类似的 bug 报告。
> * [x] 我搜索了 PaddleOCR [问题](https://github.com/PaddlePaddle/PaddleOCR/issues)，没有找到类似的 bug 报告。
> * [x] 我搜索了 PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions)，没有找到类似的 bug 报告。
> 
> ### 🐛 Bug （问题描述）
> 上图，最上面一行的APP 金东纸业那一行，文本检测不出来，不管是v3还是v4
> 
> ### 🏃 ♂️ 环境 （运行环境）
> paddleocr=2.9.2 paddlepaddle=3.0.0b1
> 
> ### 🌰 最小可复现问题的 Demo
> # 初始化 PaddleOCR
> paddleocr = PaddleOCR（lang='ch'， use_angle_cls=False， show_log=True， det_model_dir='../weights/ch_PP-OCRv4_det_infer'， rec_model_dir='../weights/ch_PP-OCRv4_rec_infer' )

**Comment by zibo-chen** [comment]
https://github.com/zibo-chen/rust-paddle-ocr/blob/main/src/det.rs
det模型输出的检测框可能会过小,可以主动放大点,可以参考我这里的处理
