### ISSUE TITLE
文本检测漏行问题

### ISSUE THREAD

**Issue by dragronstranding** [PaddlePaddle/PaddleOCR#14440]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

![image](https://github.com/user-attachments/assets/67d0d01c-7dd2-4df3-8575-2e904db33dab)
例如上图，不管是用v3还是v4的文本检测里会漏掉最上面的“APP 金东纸业。。。”那一行

### 🏃‍♂️ Environment (运行环境)

paddleocr=2.9.2
paddlepaddle=3.0.0b1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

# 初始化 PaddleOCR
paddleocr = PaddleOCR(lang='ch', use_angle_cls=False, show_log=True,
                      det_model_dir='../weights/ch_PP-OCRv4_det_infer',
                      rec_model_dir='../weights/ch_PP-OCRv4_rec_infer'
                      )

**Comment by jingsongliujing** [comment]
看上去是字体有部分歪曲和模糊，可以通过预处理（比如二值化，图像缩放和归一化、图像增强）或者标注数据再训练的方式提高识别精度
