### ISSUE TITLE
自训练模型转为推理模型的时候出错，没有生成pdmodel这个文件

### ISSUE THREAD

**Issue by LKjoey** [PaddlePaddle/PaddleOCR#14458]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

自训练模型转为推理模型的时候出错，没有生成pdmodel这个文件，识别模型多生成了一个json文件和yml文件，检测模型就更看不懂了
![Snipaste_2024-12-27_17-37-32](https://github.com/user-attachments/assets/8c17f6bc-c204-4206-98a1-8365703cfec2)
![Snipaste_2024-12-27_17-37-20](https://github.com/user-attachments/assets/ac573ca2-75cb-49b5-9445-b4f75495702f)

### 🏃‍♂️ Environment (运行环境)

python 3.10  PaddleOCR2.9.0  cuda

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

使用export文件进行导出

**Comment by GreatV** [comment]
json 格式是新的IR格式，参考 https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/model_train/recognition.html#4

**Comment by ChenControl** [comment]
https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/model_train/recognition.html#4 
无法访问，我也是自己稍微修改了一下pgnet的模型结构，自己训练了一下，但导出的也是类似json,pdiparams和yml文件
