### ISSUE TITLE
paddleX推理产线缺少inference.yml

### ISSUE THREAD

**Issue by cmx4869** [PaddlePaddle/PaddleOCR#14457]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

我的服务器无法联公网，我尝试使用paddleX的docker+指定生产线文件+外挂模型，但是报错：
FileNotFoundError: [Errno 2] No such file or directory: '/root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_mobile_rec/inference.yml'

我尝试了如下：
1.在能连接公网的服务器上，进入PaddleX的docker执行paddlex --pipeline OCR --input paddle/docker/1.png --device gpu:0 --save_path /paddle，看到了下载完成rec\det模型的信息，然后将docker保存打包，迁移到无网服务器上，提示无法连接网络下载模型

2.更改产线配置文件，尝试了https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/inference/utils/official_models.py和https://paddlepaddle.github.io/PaddleX/latest/pipeline_usage/tutorials/ocr_pipelines/OCR.html#1-ocr上面的推理文件，但是产生了FileNotFoundError: [Errno 2] No such file or directory: '/root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_mobile_rec/inference.yml'

使用的产线配置yml如下:
Global:
  pipeline_name: OCR
  input: paddle/docker/1.png

Pipeline:
  text_det_model: /root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_mobile_det_infer
  text_rec_model: /root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_server_rec
  text_rec_batch_size: 1
  device: "gpu:0"

我确认对应路径能被访问，文件来自官网。
请求您的帮助，我更倾向于能使用外挂模型+自定义产线配置yaml来执行

### 🏃‍♂️ Environment (运行环境)

ubuntu22.04
paddleX docker

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

产线配置yaml：
Global:
  pipeline_name: OCR
  input: paddle/docker/1.png

Pipeline:
  text_det_model: /root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_mobile_det_infer
  text_rec_model: /root/PaddleX/paddlex/paddle_model_yaml/PP-OCRv4_server_rec
  text_rec_batch_size: 1
  device: "gpu:0"

执行指令：
paddlex --pipeline /root/PaddleX/paddlex/paddle_model_yaml/OCR.yaml --input paddle/docker/1.png --device gpu:0 --save_path /paddle

**Comment by jingsongliujing** [comment]
https://github.com/PaddlePaddle/PaddleX/issues/2736

**Comment by jingsongliujing** [comment]
# https://github.com/PaddlePaddle/PaddleX/issues/2736

**Comment by jingsongliujing** [comment]
https://github.com/PaddlePaddle/PaddleX/issues/2736
