### ISSUE TITLE
将文本检测模型和文本识别模型转化为推理模型时出错

### ISSUE THREAD

**Issue by zhaohongpu** [PaddlePaddle/PaddleOCR#14451]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

当我用以下命令将自己训练的模型转化为推理模型时，没有inference.pdiparams.info和inference.pdmodel两个文件
python tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml -o Global.pretrained_model=./output/ch_db_res18/latest Global.save_inference_dir=./output_det_inference/

python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./output/rec_chinese_common_v2.0/best_accuracy Global.save_inference_dir=./output_rec_inference/
![image](https://github.com/user-attachments/assets/14066b87-be7c-4f94-98d5-78166fefdd01)

### 🏃‍♂️ Environment (运行环境)

Python3.10.15 Paddleocr 2.9.1 CUDA12.2 paddlepaddle2.6.1

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

希望能帮忙解决一下

**Comment by LKjoey** [comment]
请问找到原因了吗，我用2.9.0版本的进行转换也出问题

**Comment by zhaohongpu** [comment]
> 请问找到原因了吗，我用2.9.0版本的进行转换也出问题

我把版本换成了2.9.1是可以的
