### ISSUE TITLE
建议增加版面分析，针对横版和竖版

### ISSUE THREAD

**Issue by jidechao** [PaddlePaddle/PaddleOCR#145]
目前对于一般的横制图像，识别率还是蛮高的。而对于民国时的竖版报纸图像文件识别，虽说文字还是有一定的识别率，但识别结果语句顺序乱掉了。

**Comment by LDOUBLEV** [comment]
现在识别结果显示主要是针对横排文字，按照检测框的位置从上到下从左到右排序。后面考虑加上纯竖排文字展示。不过像你提到的 “民国时的竖版报纸图像文件” 这样的图像同时有横排和竖排文字对吧？

**Comment by jidechao** [comment]
> 现在识别结果显示主要是针对横排文字，按照检测框的位置从上到下从左到右排序。后面考虑加上纯竖排文字展示。不过像你提到的 “民国时的竖版报纸图像文件” 这样的图像同时有横排和竖排文字对吧？
我说的主要是针对纯竖排文字，从右至左，从上到下。

**Comment by LDOUBLEV** [comment]
> > 现在识别结果显示主要是针对横排文字，按照检测框的位置从上到下从左到右排序。后面考虑加上纯竖排文字展示。不过像你提到的 “民国时的竖版报纸图像文件” 这样的图像同时有横排和竖排文字对吧？
> > 我说的主要是针对纯竖排文字，从右至左，从上到下。

好的，后面考虑增加纯竖排文字的显示的函数

**Comment by LDOUBLEV** [comment]
新的可视化方式可以参考：https://github.com/PaddlePaddle/PaddleOCR/pull/210
