### ISSUE TITLE
最新模型inference.pdiparams，inference.pdmodel，使用fluid_inference.zip 2.0.0.0 bate版本，cpp加载版本加载崩溃！

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#1456]
![图片](https://user-images.githubusercontent.com/40679769/102297951-33620d00-3f8b-11eb-9d1c-21fa0dc8f658.png)

**Comment by xinsuinizhuan** [comment]
![Uploading 图片.png…]()

**Comment by WenmuZhou** [comment]
需要使用2.0 rc0版本及以上的预测库哈

**Comment by xinsuinizhuan** [comment]
> 
> 
> 需要使用2.0 rc0版本及以上的预测库哈

去哪里下载2.0rc0版本的预测库？官网放出来的库最高版本还是2.0bate版本

**Comment by WenmuZhou** [comment]
我这边一般是自己编译的，你可以自己编译一下

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我这边一般是自己编译的，你可以自己编译一下

我尝试过很多次自己编译，都编译失败了。我的环境是win10,vs2019,nvida10.1.

**Comment by WenmuZhou** [comment]
这个建议使用linux会方便一点，win我这边尝试一下
