### ISSUE TITLE
2.0示例报GPU内存错误

### ISSUE THREAD

**Issue by qsrc** [PaddlePaddle/PaddleOCR#1470]
paddlepaddle版本2.0.0rc1，换回1.1版没问题。

代码：
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(use_angle_cls=True) 
img_path = r'C:\Users\Administrator\Desktop\ocr_in\test_pic_01.jpg'
result = ocr.ocr(img_path, cls=True)

报错：
Traceback (most recent call last):
  File "D:/py_src/QtRepo/ocr_test/ppocr_2.0_test.py", line 23, in <module>
    result = ocr.ocr(img_path, cls=True)
  File "C:\Python38\lib\site-packages\paddleocr\paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "C:\Python38\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 106, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "C:\Python38\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 109, in __call__
    self.predictor.run([norm_img_batch])
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 2.812744MB memory on GPU 0, available memory is only 1.000000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at D:\2.0.0rc1\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

W1216 17:03:20.600451 11148 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.

**Comment by WenmuZhou** [comment]
OOM了，看显卡是不是有其他程序在跑

**Comment by qsrc** [comment]
没有，重启了电脑。感觉正常也不至于available memory is only 1.000000MB. 只有1MB。把gpu_mem调小也没用。2080的显卡

**Comment by qsrc** [comment]
识别出错了，加了个rec=False，到检测这步是正常的

**Comment by WenmuZhou** [comment]
跑的时候观察一下显卡，看看是不是检测跑完跑识别的时候显存没了

**Comment by qsrc** [comment]
对，是直接满，用完8G，然后改小gpu_mem没用

**Comment by WenmuZhou** [comment]
我这边在linux没有复现你的问题。。。。 你试一下linux看看

**Comment by qsrc** [comment]
linux暂时没搭环境，有空试。
然后用默认模型，gpu_mem=10, cls_batch_num=1, rec_batch_num=1，跑通了。显存还是用掉了7G多。应该是有个东西初始化直接固定占掉了7G多的内存，不能给其他模型用。

**Comment by chapmancpp** [comment]
> 我这边在linux没有复现你的问题。。。。 你试一下linux看看

我用PPOCRLabel，自动标注，也遇到了GPU占满的情况。

**Comment by wowowoll** [comment]
![image](https://user-images.githubusercontent.com/49295186/102953761-02df1d80-450d-11eb-80cd-ce62053d362c.png)
我是使用paddle2.0.0rc1和paddleoce 2.0 的模型一直出现显存不够的问题，1.1版本的模型反而没有出现这个问题

**Comment by wa3926** [comment]
@WenmuZhou  我也遇到了  paddleocr  镜像cuda10.1      paddlepaddle-gpu  2.0rc1      使用 hub serving start -c deploy/hubserving/ocr_system/config.json  启动   初始化内存  1362MiB /  7611MiB    第一次访问   6650MiB /  7611MiB
第二次访问   6722MiB /  7611MiB  然后我把图片旋转 180度  就直接报错了   7428MiB /  7611MiB   内存一直也不释放

**Comment by WenmuZhou** [comment]
你的hub版本是什么

**Comment by Peng-ss** [comment]
我也遇到这个问题了，使用cpu运行预测是没有问题的，采用GPU运行预测报内存溢出了

**Comment by Peng-ss** [comment]
> 对，是直接满，用完8G，然后改小gpu_mem没用

你好，请问你有解决这个问题了吗
