### ISSUE TITLE
Style Text 问题

### ISSUE THREAD

**Issue by VJoer** [PaddlePaddle/PaddleOCR#1472]
在使用案例中的场景图像进行的批量的OCR数据合成是可以生成完整的图像，但是使用本地的图像
![1](https://user-images.githubusercontent.com/41233036/102337216-2c5bee80-3fcd-11eb-83be-514b3abdbe20.jpg)

作为场景图像进行OCR数据合成生成的图像中没有文字，并且图像中充满了很多奇怪的东西
![0](https://user-images.githubusercontent.com/41233036/102337156-151d0100-3fcd-11eb-84b2-6f1b9ccd866d.png)

我也尝试调整一些配置文件中的参数，但是效果并不理想；我想知道配置文件中所有参数代表的意思，RM中只有一些参数的解释，请问怎样才能生成标准的OCR数据

**Comment by xxllp** [comment]
我的理解是这个模型需要训练的 基于自己的数据

**Comment by VJoer** [comment]
> 我的理解是这个模型需要训练的 基于自己的

我之前的本地图像的尺寸大概是200X1000
![](https://user-images.githubusercontent.com/41233036/102337216-2c5bee80-3fcd-11eb-83be-514b3abdbe20.jpg)
刚才又重新试了一下，把本地图像的尺寸调整成20X100
![1](https://user-images.githubusercontent.com/41233036/102339111-adb48080-3fcf-11eb-90c5-ad146f5bb896.jpg)
和官方案例中生成OCR数据的背景尺寸大概一致，这样就可以得到比较好的生成数据了
![3](https://user-images.githubusercontent.com/41233036/102339221-d0469980-3fcf-11eb-8dba-96be0cd3f775.png)

应该是提取背景图片中文字的模型的问题

**Comment by weisy11** [comment]
这个模型生成的数据主要用于OCR识别模型的训练。PaddleOCR目前识别模型的输入为32*N，因此当前版本模型主要应用于高度为32的数据。尺寸相差不多的数据也可以生成，尺寸很大或很小的数据效果确实不佳。

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/1475
