### ISSUE TITLE
带角度的识别不准

### ISSUE THREAD

**Issue by qiulyu** [PaddlePaddle/PaddleOCR#1473]
请问一下大家这种应该怎么改善呢
![image](https://user-images.githubusercontent.com/45893995/102343907-1d2d6e80-3fd6-11eb-8e78-46c8bf45cbc5.png)

**Comment by MissPenguin** [comment]
大概有几个思路可以尝试下：
1. 2023,05,2020这3个数是对的，g0是把06的方向判断错了，目前方向分类器是对每个文本框分别进行判断，你的这种场景（所有文本的方向是一致的）可以考虑对整张图像的文本方向进行判断，比如你这里3个正的，1个反的，那就都当正的处理。
2. 这种背景很干净的图，是否有可能先对全图进行转正
3. 增大预测输入分辨率或调一下后处理参数，解决漏检问题
4. 标一批数据finetune下模型

**Comment by LDOUBLEV** [comment]
> 请问一下大家这种应该怎么改善呢
> ![image](https://user-images.githubusercontent.com/45893995/102343907-1d2d6e80-3fd6-11eb-8e78-46c8bf45cbc5.png)

用的是PaddleOCR提供的模型还是你finetune后的文本检测模型，文本检测没训练好，如果是用的Paddle OCR模型，建议在你的数据上finetune再试下

**Comment by qiulyu** [comment]
> 大概有几个思路可以尝试下：
> 
> 1. 2023,05,2020这3个数是对的，g0是把06的方向判断错了，目前方向分类器是对每个文本框分别进行判断，你的这种场景（所有文本的方向是一致的）可以考虑对整张图像的文本方向进行判断，比如你这里3个正的，1个反的，那就都当正的处理。
> 2. 这种背景很干净的图，是否有可能先对全图进行转正
> 3. 增大预测输入分辨率或调一下后处理参数，解决漏检问题
> 4. 标一批数据finetune下模型

非常感谢您的指教：
1、三个正的和1个反的，我们人眼看是这样，在执行完文本检测之后它怎么知道哪个是正的哪个是反的呢
2、有想过先对整个文本旋正，有个问题就是怎样确定旋转到正的那个水平去，因为有时候也会向右边倾斜很大的角度还有其他的角度等
3和4我下来试一下
感谢

**Comment by qiulyu** [comment]
> > 请问一下大家这种应该怎么改善呢
> > ![image](https://user-images.githubusercontent.com/45893995/102343907-1d2d6e80-3fd6-11eb-8e78-46c8bf45cbc5.png)
> 
> 用的是PaddleOCR提供的模型还是你finetune后的文本检测模型，文本检测没训练好，如果是用的Paddle OCR模型，建议在你的数据上finetune再试下

使用的是PaddleOCR提供的那个复杂的模型，多谢指教我再finetune一下。
