### ISSUE TITLE
NotFoundError: Operator (rnn) is not registered.

### ISSUE THREAD

**Issue by VJoer** [PaddlePaddle/PaddleOCR#1476]
运行案例中预测，出现这个问题，不知道怎么解决
(paddlepaddle-gpu) F:\JorVer\demos\PaddleOCR>python tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --
cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
W1217 09:32:34.463459  7480 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 185, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 142, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 40, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "F:\JorVer\demos\PaddleOCR\tools\infer\predict_rec.py", line 51, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "F:\JorVer\demos\PaddleOCR\tools\infer\utility.py", line 133, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator (rnn) is not registered.
  [Hint: op_info_ptr should not be null.] (at D:\2.0.0-rc0\paddle\paddle/fluid/framework/op_info.h:151)

**Comment by MissPenguin** [comment]
用的什么版本的paddle，使用2.0版模型需要安装2.0.0rc1版paddle，具体可参考安装教程：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/installation.md

**Comment by VJoer** [comment]
> 用的什么版本的paddle，使用2.0版模型需要安装2.0.0rc1版paddle，具体可参考安装教程：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/installation.md
我用conda之前安装的是2.0.0rc0的paddle，现在conda的2.0.0rc1版本的paddle还没，我用pip重新安装2.0.0rc1的paddle试试
