### ISSUE TITLE
python环境下和c++infer环境下，同个模型ocr识别效果不一致

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleOCR#1477]
使用paddleOCR工程中的predict_system.py脚本做检测+识别，效果如下：
![image](https://user-images.githubusercontent.com/68883664/102435288-4e975000-4051-11eb-823e-35c8f256479c.png)
使用c++infer 做检测+识别，效果如下：
![image](https://user-images.githubusercontent.com/68883664/102434985-ce70ea80-4050-11eb-8dd8-8df1ac256fdb.png)
，差异主要是识别，c++infer中在识别的时候，resize的大小和python一致，还有什么其他原因造成了此差异？

**Comment by stefan-567** [comment]
> 方便发一下原图吗，我测一下

图片上传失败，我qq：1063800537@qq.com，方便加我一下吗？

**Comment by MissPenguin** [comment]
发我邮箱吧：lichenxia@baidu.com
