### ISSUE TITLE
WindowsC++库作为C#托管库时存在CLR和MT的冲突，而MD方式则存在链接错误

### ISSUE THREAD

**Issue by amadeuzou** [PaddlePaddle/PaddleOCR#1478]
使用的库：https://paddle-wheel.bj.bcebos.com/1.8.3/win-infer/mkl/cpu/fluid_inference_install_dir.zip
开发环境：vs2019

问题： c#调用paddle， paddle库作为托管库的一部分，但c#调用c++托管对象的时候，必需使用CLR的方式编译，但CLR与MT选项（静态链接）不兼容，只能是CLR和MD选项（动态链接），但MD选项下会出现一系列的链接错误：错误 LNK2038 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(clipper.obj 中) ocr_system

**Comment by lensea** [comment]
请问，你解决了吗？
