### ISSUE TITLE
ImportError:cannot import name 'fluid'，如何解决呢？

### ISSUE THREAD

**Issue by tongtong9293** [PaddlePaddle/PaddleOCR#1479]
想用自己的数据集在gpu服务器下训练，cuda10.0，出现以下错误，ImportError：cannot import name 'fluid'
请问是什么原因呢？应该怎么解决呢？

![fluid](https://user-images.githubusercontent.com/48546049/102443672-3f6cce00-4062-11eb-9d5e-249a25c16111.png)

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/102444229-a3dc5d00-4063-11eb-9755-27c65896c3ee.png)
zhe这一步的验证有无问题

**Comment by tongtong9293** [comment]
> ![图片](https://user-images.githubusercontent.com/12406017/102444229-a3dc5d00-4063-11eb-9755-27c65896c3ee.png)
> zhe这一步的验证有无问题
输入后，如下图所示：
![QQ图片20201217125647](https://user-images.githubusercontent.com/48546049/102445844-6974bf00-4067-11eb-8551-3000ced824e5.jpg)

![QQ图片20201217125652](https://user-images.githubusercontent.com/48546049/102445847-6c6faf80-4067-11eb-9f12-5ccc7ee64f19.jpg)

**Comment by tongtong9293** [comment]
重新装了2.0.0rc1，现在好使了。
![1](https://user-images.githubusercontent.com/48546049/102447356-caea5d00-406a-11eb-82f9-03bc72b4eaf8.jpg)
