### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.nn'，已经安装了paddle1.8.5，但是还是一直报错

### ISSUE THREAD

**Issue by wuxiaolianggit** [PaddlePaddle/PaddleOCR#1481]
ModuleNotFoundError: No module named 'paddle.nn'，已经安装了paddle1.8.5，但是还是一直报错,怎么解决呢，大佬 @ZeyuChen @karlhorky @ufoym @jacquesqiao @ZhangXinNan

**Comment by WenmuZhou** [comment]
需要使用2.0rc1

**Comment by wuxiaolianggit** [comment]
多谢大佬，我试一下啊。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhoujun <notifications@github.com&gt;
发送时间: 2020年12月17日 18:13
收件人: PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com&gt;
抄送: wuxiaolianggit <2235361118@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleOCR] ModuleNotFoundError: No module named 'paddle.nn'，已经安装了paddle1.8.5，但是还是一直报错 (#1481)

**Comment by pengyuange** [comment]
> 需要使用2.0rc1

但是使用了2.0rc1，又用不了paddlerec，这改怎么解决？

**Comment by WenmuZhou** [comment]
paddlerec是啥

**Comment by karlhorky** [comment]
@wuxiaolianggit do you think you can stop tagging me? Sorry, I am not familiar enough with this codebase to be able to help.
