### ISSUE TITLE
分类模型输入图片尺寸

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1483]
您好，我有几个问题想请教一下：
1.请问分类模型的image_shape是怎样确定的？
2.对于示例中MobileNetV3_small_x0_35模型，尺寸为什么不是96x96呢，如果高度为48，最后做卷积运算时不会被填补空白吗？
3.我现在用的数据尺寸大概是48x100，想使用ResNet50_vd_ssld_v2进行训练，请问可以直接使用这个尺寸训练吗，需要更改为224x224吗?为什么？
谢谢。

**Comment by WenmuZhou** [comment]
1. 分类器使用的是识别模型的尺寸， 上下分类，这种尺寸更好
2. 数据会做pad的
3. 如果直接使用ResNet50_vd_ssld_v2网络的话，数据需要做resize或者pad到224x224

**Comment by tyy2tyy** [comment]
好的，谢谢您的回答
