### ISSUE TITLE
想要训练检测网络，报错如下，请问怎么解决呢？

### ISSUE THREAD

**Issue by tongtong9293** [PaddlePaddle/PaddleOCR#1485]
想用自己的数据集在gpu服务器训练检测网络，输入的命令是export CUDA_VISIBLE_DEVICES=1 && python tools/train.py -c configs/det/det_mv3_db_v1.1.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/
报错如下图所示，请问是什么问题导致的呢？应该如何处理？   谢谢~

![报错](https://user-images.githubusercontent.com/48546049/102470222-ac965880-408e-11eb-821d-1fb57bc6564c.png)

**Comment by xmy0916** [comment]
![image](https://user-images.githubusercontent.com/43675899/102568060-bca94900-411d-11eb-9e05-049152475854.png)
应该是cudnn版本不匹配的问题

**Comment by tink2123** [comment]
把cudnn版本升级到7.6以上再试一下把～

**Comment by tongtong9293** [comment]
谢谢你们~ 我用anaconda在环境下安装了cudnn7.6.4以及 cuda10.0（之前报错时用的是服务器自带的cudnn7.4版本），再次输入训练命令时，没有出现报错，但是停在图片中的样子不动了（25分钟以上），也不出现训练结果，请问这是什么原因呢？  我应该如何处理呢？感谢！！！
![image](https://user-images.githubusercontent.com/48546049/102683668-8e0a9b80-420d-11eb-9f99-9767f48e8f8e.png)

![image](https://user-images.githubusercontent.com/48546049/102683663-7e8b5280-420d-11eb-8df1-76738de55d63.png)

![image](https://user-images.githubusercontent.com/48546049/102683672-97940380-420d-11eb-81b7-e3a36e39c209.png)
![image](https://user-images.githubusercontent.com/48546049/102683680-a5498900-420d-11eb-8843-64eea6effa91.png)
![image](https://user-images.githubusercontent.com/48546049/102683686-abd80080-420d-11eb-931f-9762d38e51da.png)

**Comment by grasswolfs** [comment]
有可能是batchsize太大了，可以调小一点试试

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
