### ISSUE TITLE
关于表格数据训练的问题

### ISSUE THREAD

**Issue by Maxhyl** [PaddlePaddle/PaddleOCR#1486]
请问对表格数据进行标注的时候，是按照单元格来标注吗（就是单元格的四个点），空的单元格是否也要标注呢

**Comment by xmy0916** [comment]
空的单元格不需要标注的，标注有文字的部分（不需要按照单元格的四个点标注）即可 @Maxhyl

**Comment by Maxhyl** [comment]
> 空的单元格不需要标注的，标注有文字的部分（不需要按照单元格的四个点标注）即可@Maxhyl

就是按照文本检测那种方式来标注吗

**Comment by grasswolfs** [comment]
> > 空的单元格不需要标注的，标注有文字的部分（不需要按照单元格的四个点标注）即可@Maxhyl
> 
> 就是按照文本检测那种方式来标注吗

是的，也可以使用PPOCRLabel辅助标注，我们最近有计划开源一些表格结构化方面的代码，也许会有帮助，敬请期待

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
