### ISSUE TITLE
检测结果出现平行四边形

### ISSUE THREAD

**Issue by unisoc281** [PaddlePaddle/PaddleOCR#1487]
训练图像尺寸是3×630×640。对于一张960×720的图片，测试时把test_image_shape固定为[640,640]。为什麽检测的区域是平行四边形，而不是矩形框？测试时把图片长宽按比例缩放到640×640，后处理时再按照缩放的比例还原，为什么会出现平行四边形？

**Comment by xmy0916** [comment]
您好！方便贴几张效果图片我们看看嘛？ @unisoc281

**Comment by LDOUBLEV** [comment]
> 训练图像尺寸是3×630×640。对于一张960×720的图片，测试时把test_image_shape固定为[640,640]。为什麽检测的区域是平行四边形，而不是矩形框？测试时把图片长宽按比例缩放到640×640，后处理时再按照缩放的比例还原，为什么会出现平行四边形？

DB是基于分割的文本检测模型，检测出来的框就是不规则四边形
