### ISSUE TITLE
Tensor holds the wrong type, it holds float, but desires to be int64_t

### ISSUE THREAD

**Issue by demonxjj** [PaddlePaddle/PaddleOCR#1492]
W1217 22:53:10.765017 42380 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.
(InvalidArgument) Tensor holds the wrong type, it holds float, but desires to be int64_t
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\dev\thirdpart\Paddle\paddle/fluid/framework/tensor_impl.h:51)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

最新版的2.0 ,paddlepaddle是最新的开发版本

**Comment by xmy0916** [comment]
您好，麻烦提供下您运行报错的命令，报错完整截图~

**Comment by demonxjj** [comment]
没有使用GPU,其他的配置都是默认的,在加载模型的时候出错的,CreatePaddlePredictor(config);

**Comment by tink2123** [comment]
贴一下您完整的运行命令吧，我们先复现一下问题

**Comment by demonxjj** [comment]
我这边预测程序有修改,这边环境是window 10,paddlepaddle编译的时候昨天更新代码重新编译的,选择了不支持GPU的选项编译的,预测用的是cpp版本,应该用你们的cpp版本可以重现的.

**Comment by yy2lyx** [comment]
我也遇到这种问题，请问有解决方案么
![image](https://user-images.githubusercontent.com/35443937/102846547-32c5ec80-444b-11eb-8926-3a88d3d89ed6.png)

**Comment by yy2lyx** [comment]
> W1217 22:53:10.765017 42380 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.
> (InvalidArgument) Tensor holds the wrong type, it holds float, but desires to be int64_t
> [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\dev\thirdpart\Paddle\paddle/fluid/framework/tensor_impl.h:51)
> [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
> 
> 最新版的2.0 ,paddlepaddle是最新的开发版本

请问您解决了吗

**Comment by LDOUBLEV** [comment]
请确保使用 rc1 的预测库，或者自己用Paddle 2.0rc1分支编译预测库 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

另外，昨天dygraph分支的 cpp_infer 预测代码已经更新为最新预测库接口，可以更新代码

**Comment by LDOUBLEV** [comment]
as https://github.com/PaddlePaddle/PaddleOCR/issues/1554

**Comment by yy2lyx** [comment]
> 请确保使用 rc1 的预测库，或者自己用Paddle 2.0rc1分支编译预测库 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> 
> 另外，昨天dygraph分支的 cpp_infer 预测代码已经更新为最新预测库接口，可以更新代码

刚试了paddleocr 的dygraph分支的cpp_infer，和paddle 2.0rc1（vs2019，windows10），还是报相同的错误

**Comment by qq61786631** [comment]
2048 x 3072
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 batch norm with relu activatione[0m
(InvalidArgument) The Input Variable(Input) of (conv2d) Operator used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] (at D:\2.0.0rc1\paddle\paddle\fluid\framework\operator.cc:1479)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
同样的错误

**Comment by bikerr** [comment]
环境信息
```
PaddleOCR 2.0
PaddlePaddle 2.0.1 
window 10
python 3.7.9 
```
禁用GPU
训练方向分类器还是报同样的错误

**Comment by grasswolfs** [comment]
可以拉一下最新的分支，PaddlePaddle 2.1.1 PaddleOCR2.1, lite 2.9 再试下

**Comment by baojuanluo** [comment]
我也遇到相同的问题，我用的是这个版本的预测库https://paddle-wheel.bj.bcebos.com/2.1.0win/win-infer/mkl/cpu/paddle_inference.zip，paddleocr是2.0的

**Comment by baojuanluo** [comment]
> 
> 
> 我也遇到这种问题，请问有解决方案么
> ![image](https://user-images.githubusercontent.com/35443937/102846547-32c5ec80-444b-11eb-8926-3a88d3d89ed6.png)

请问一下问题是怎么解决的啊？

**Comment by baojuanluo** [comment]
知道为什么会出现这个问题了。paddleocr和预测库用的是V2.x，但推理模型用的是V1.x版本的。把推理模型替换为V2.x问题就解决了。
