### ISSUE TITLE
Style-text 可以中英文一起生成吗？

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#1493]
Style-text 在生成数据时，中文和英文文本一起输入，应该怎么办？

**Comment by xmy0916** [comment]
可以的，选择中文字体，但是中文字体写出来的英文和数字对比英文字体写出来的英文和数字有一点点差别~

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
