### ISSUE TITLE
https://mirror.baidu.com/pypi/simple崩了，下载失败

### ISSUE THREAD

**Issue by joshua23333** [PaddlePaddle/PaddleOCR#1495]
这两天https://mirror.baidu.com/pypi/simple，百度源崩了？下载都下载不了了

**Comment by xmy0916** [comment]
![image](https://user-images.githubusercontent.com/43675899/102567218-02fda880-411c-11eb-8895-fd64cba0097d.png)
这边测试是可以的呢，检查下网络环境或者换其他源试试吧 @joshua23333

**Comment by Prymon** [comment]
注意下python版本号，不支持的版本下载会报错

> Python2 >= 2.7.15 or Python 3(3.5.1+/3.6/3.7)，64位版本
