### ISSUE TITLE
ch_ppocr_server_v2.0_rec推理模型文件后缀不正确

### ISSUE THREAD

**Issue by yinkanchn** [PaddlePaddle/PaddleOCR#1497]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/models_list.md
ch_ppocr_server_v2.0_rec的推理模型下载的文件后缀为tar,实际为tar.gz

**Comment by LDOUBLEV** [comment]
感谢反馈，稍后更新压缩包

**Comment by LDOUBLEV** [comment]
已更新模型文件，压缩方式为 tar  cf ch_ppocr_server_v2.0_rec
