### ISSUE TITLE
模型转onnx

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#150]
我尝试将提供的模型通过paddle2onnx，转成onnx，转换失败了。是不支持转换吗

**Comment by tink2123** [comment]
是的，PaddleOCR不支持转换到onnx～

**Comment by lgcy** [comment]
> 是的，PaddleOCR不支持转换到onnx～
请问后面会考虑支持吗

**Comment by LDOUBLEV** [comment]
> > 是的，PaddleOCR不支持转换到onnx～
> > 请问后面会考虑支持吗

我们会讨论下，暂时不在排期里

**Comment by lgcy** [comment]
> > > 是的，PaddleOCR不支持转换到onnx～
> > > 请问后面会考虑支持吗
> 
> 我们会讨论下，暂时不在排期里

好的，谢谢解答~

**Comment by lxjhunan** [comment]
> > > 是的，PaddleOCR不支持转换到onnx～
> > > 请问后面会考虑支持吗
> 
> 我们会讨论下，暂时不在排期里

你好，可以给一些建议和方案怎么把当前的模型转onnx吗

**Comment by lxjhunan** [comment]
> > > 是的，PaddleOCR不支持转换到onnx～
> > > 请问后面会考虑支持吗
> 
> 我们会讨论下，暂时不在排期里

你好，可以给一些方案和建议怎么把当前DB模型转onnx吗
