### ISSUE TITLE
mkldnn

### ISSUE THREAD

**Issue by w-Bro** [PaddlePaddle/PaddleOCR#1500]
paddleocr的mkldnn有什么开启条件吗，想要开启CPU加速，但是CPU是AMD的，使用paddlehub部署运行会报错，intel平台下能正常运行。
win10+python3.7+paddlepaddle2.0.0.rc+paddhub1.8.3
![image](https://user-images.githubusercontent.com/24600584/102582599-e70afe80-413d-11eb-9981-a3e5c782bf06.png)

**Comment by tink2123** [comment]
使用的是动态图代码吗？ 动态图建议安装 paddlepaddle2.0.0.rc1

**Comment by tink2123** [comment]
mkldnn是intel芯片的加速库，amd不支持mkldnn

**Comment by w-Bro** [comment]
> mkldnn是intel芯片的加速库，amd不支持mkldnn

我修改的是deploy\hubserving\ocr_system\module.py，enable_mkldnn=False -> enable_mkldnn=True
```
def _initialize(self, use_gpu=False, enable_mkldnn=True):
```
直接运行module.py是正常识别的，只是用hubserving 部署之后接收到请求后会报错，是不是hubserving的问题呢？

**Comment by LDOUBLEV** [comment]
amd不支持mkldnn加速，在非intel CPU预测，建议enable_mkldnn=False
