### ISSUE TITLE
paddle.nn has no attribute 'Conv2D'

### ISSUE THREAD

**Issue by Gavinic** [PaddlePaddle/PaddleOCR#1502]
AttributeError: module 'paddle.nn' has no attribute 'Conv2D'

1, i follow the guide in this 'url'.
     https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/installation.md
2, i have done the step 1, ,2,3,4;
3, the paddle lib import successfully.
![image](https://user-images.githubusercontent.com/20828244/102585481-76ff7700-4143-11eb-978c-aefe81e6bd3c.png)
4, when i run the synthTxt script, the attribute error occurred.
python3 tools/synth_image.py -c configs/config.yml --style_image examples/style_images/2.jpg --text_corpus PaddleOCR --language en
![image](https://user-images.githubusercontent.com/20828244/102585683-ca71c500-4143-11eb-902c-673fe4e5084e.png)

others:
the paddle version:
python3 -m pip install paddlepaddle-gpu==2.0.0rc1 -i https://mirror.baidu.com/pypi/simple

**Comment by pekinghk** [comment]
我遇到了一样的问题

**Comment by weisy11** [comment]
麻烦确认下paddle环境：

**Comment by pekinghk** [comment]
应该是版本的问题，之前是2.0b，更新conv2d好像只在fluid.layers里

**Comment by weisy11** [comment]
> 应该是版本的问题，之前是2.0b，更新conv2d好像只在fluid.layers里

是的，paddle2.0rc1中部分api的名字进行了优化
