### ISSUE TITLE
android上运行报Check failed: op: no Op found for feed的问题。

### ISSUE THREAD

**Issue by mmjj2014** [PaddlePaddle/PaddleOCR#1504]
github 发布的2.7的库默认是不支持android 5.0。我现在重新指定 --android_api_level=21 编译，编译成功。但是在android中运行时，报错了，A/Paddle-Lite: [F 12/18 16:51:30.788 ...pencode/Paddle-Lite/lite/core/program.cc:187 RuntimeProgram] Check failed: op: no Op found for feed。我参照https://github.com/PaddlePaddle/PaddleOCR/issues/904 方式排查，编译静态库时，extra 和 cv  都打开了，头文件在android项目的cmake中都有添加了，还是报了no Op found for feed。我是否在哪里有了遗漏？

**Comment by DannyIsFunny** [comment]
你好，调用Paddle-Lite静态库时需要引用头文件
``` c++
#include "paddle_use_ops.h"
#include "paddle_use_kernels.h"
```

**Comment by mmjj2014** [comment]
> 你好，调用Paddle-Lite静态库时需要引用头文件
> 
> ```c++
> #include "paddle_use_ops.h"
> #include "paddle_use_kernels.h"
> ```

果真如此。谢谢你的回复。
