### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by Dajiang1202** [PaddlePaddle/PaddleOCR#1505]
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 25.002197MB memory on GPU 0, available memory is only 15.187500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)

显卡用的是tesla V100
cuda10.2
cudnn7.6.5
确认没有其他程序在跑

gpu占用情况

![1](https://user-images.githubusercontent.com/44104044/102599923-2266f680-4159-11eb-898e-3d865aee4a23.PNG)

**Comment by Dajiang1202** [comment]
使用gunicorn开了13个worker，好像原因是内存都集中在gpu0了，有没有办法指定GPU？

**Comment by tink2123** [comment]
export CUDA_VISIBLE_DEVICES=1
可以指定一号卡，其他同理
