### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by MapleWan** [PaddlePaddle/PaddleOCR#1507]
请问cuda11.1可以使用吗 ？

**Comment by tink2123** [comment]
暂的还不行，目前支持的cuda版本可以在paddle官网查询:https://paddlepaddle.org.cn/

**Comment by MapleWan** [comment]
> 暂时还不行，目前支持的cuda版本可以在paddle官网查询:https://paddlepaddle.org.cn/

好的  谢谢
