### ISSUE TITLE
在2.0版本中，使用ch_ppocr_server_v2.0_rec识别模型替换ch_ppocr_mobile_v2.0_rec后无法识别

### ISSUE THREAD

**Issue by batumgl** [PaddlePaddle/PaddleOCR#1510]
环境：
pycharm 2020.2.5
python 3.7.9
paddlepaddle 2.0.0rc1
paddleocr 2.0.2
(仅以CPU模式运行)

我在运行官方demo时，能够自动下载模型并自动识别得到结果
![微信截图_20201218174423](https://user-images.githubusercontent.com/24230932/102599632-b4baca80-4158-11eb-93fc-df015eda4f2c.png)
![微信截图_20201218173139](https://user-images.githubusercontent.com/24230932/102599645-b97f7e80-4158-11eb-96c2-600fc6978944.png)

我手动下载中文通用识别模型 (https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar) 并解压后，得到文件结构如下：
![微信截图_20201218174700](https://user-images.githubusercontent.com/24230932/102599855-0bc09f80-4159-11eb-87ab-9e6496ee083a.png)
我手动替换
inference.pdiparams
inference.pdiparams.info
inference.pdmodel
三个文件至 C:\Users\Administrator\.paddleocr\2.0\rec\ch 目录

当我再次运行demo时，无法输出识别结果，控制台输出内容如下：
![微信截图_20201218173238](https://user-images.githubusercontent.com/24230932/102601197-ce5d1180-415a-11eb-9225-12f331d0a10d.png)

控制台输出的Namespace如下：
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\Administrator/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\Administrator/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\Administrator/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)

**Comment by WenmuZhou** [comment]
我这边刚刚替换了一下，是好的。我下载的模型文件只有三个，你怎么有6个
![image](https://user-images.githubusercontent.com/12406017/102623470-7b488600-417d-11eb-9750-e1ef24836d49.png)

**Comment by yinkanchn** [comment]
python 3.8

**Comment by WenmuZhou** [comment]
> win10
> python 3.8
> paddlepaddle-gpu 2.0.0rc1
> paddleocr 2.0.2
> cuda 10.0
> cudnn 7.6.5
> 我下载并替换了cls、det、rec模型后遇到了类似的问题。控制台输出如下：
> 
> ```
> Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='D:\\AppData\\PaddleOCR\\2.0\\cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='D:\\AppData\\PaddleOCR\\2.0\\det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='D:\\AppData\\PaddleOCR\\2.0\\rec\\ch', use_angle_cls=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
> 
> Process finished with exit code -1073741819 (0xC0000005)
> ```
> 
> 尝试切换回自带模型仍然输出如上内容。

windows下目前GPU不能用，只能先用cpu

**Comment by yinkanchn** [comment]
> windows下目前GPU不能用，只能先用cpu

目前有计划吗

**Comment by batumgl** [comment]
> 
> 
> 我这边刚刚替换了一下，是好的。我下载的模型文件只有三个，你怎么有6个
> ![image](https://user-images.githubusercontent.com/12406017/102623470-7b488600-417d-11eb-9750-e1ef24836d49.png)

6个文件是因为在Windows系统下解压文件导致，我改为Linux环境下解压得到3个文件

**Comment by batumgl** [comment]
问题已解决，故障点可能在于物理内存满了

这两天我在测试如何能够正常运行server版本的识别模型时，在Linux虚拟机中测试时，连默认下载的mobile版本的识别模型都无法运行，推理同时物理机卡死，我意识到可能是内存满了，于是立即查看物理机内存信息，物理机内存为16G，可用内存仅为几M，果然内存被占满，于是我关闭虚拟机，释放内存，关闭所有其它软件，再次测试server版本的识别模型，一切正常，我再次打开虚拟机占用了部分内存，再次测试server版本的识别模型，又无法正常识别，于是我猜测故障点可能在于物理内存满了

**Comment by WenmuZhou** [comment]
好的

**Comment by fredhu2009** [comment]
@batumgl ，你问题解决了么？你的 python脚本和config.txt能发我一下么？我一直没运行起来
