### ISSUE TITLE
英文输出只有小写,怎么更改?

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleOCR#1511]
输出的检测结果英文全是小写的(检测的英文),怎样更改能按照图片上字母的大小写灵活更改呢?

顺着找到了character.py的第35行,        if self.character_type == "en":
            self.character_str = "0123456789abcdefghijklmnopqrstuvwxyz",发现定义的字母都是小写的,我更改成大写的即self.character_str = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"之后,输出全变成大写的了,表示想让模型老老实实按照检测到的文字大小写变化应该怎样更改呢.
![a](https://user-images.githubusercontent.com/65219051/102602033-e97c5100-415b-11eb-9e19-74142c2132c4.jpg)

**Comment by WenmuZhou** [comment]
英文模型目前训练的是大小写不敏感的，如果需要大小写敏感的话需要自己训练，character_type改为en_sensitive

**Comment by tink2123** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/multi_language/rec_en_number_lite_train.yml
参考这个配置文件，这个英文数字模型是可以区分大小写的

**Comment by LLL0802** [comment]
请问，测试检测的时候换成只有英文的字典，需要改些什么呢，会出现下标溢出的错误

**Comment by tink2123** [comment]
@LLL0802 您的命令是？检测应该是不需要指定字典的。

**Comment by yizhipipixia** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/multi_language/rec_en_number_lite_train.yml
> 参考这个配置文件，这个英文数字模型是可以区分大小写的

大佬还是不怎么懂,这个rec_en_number_lite_train.yml是训练样本的配置文件,官方提供了使用MJSynth和SynthText两个文字识别数据集训练的算法的识别训练过程中保存的模型链接:https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/algorithm_overview.md

这边所以说为了区分大小写我是应该使用rec_en_number_lite_train.yml这样的配置文件重新训练一个模型吗.

或者还是可以在转换成inference model 即:ython3 tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_ctc.yml -o Global.checkpoints="./models/rec_r34_vd_tps_bilstm_ctc/best_accuracy" Global.save_inference_dir="./inference/starnet"这个步骤更改里面的yml文件,就利用官方提供的模型,就可以输出转换成预测模型呢?

**Comment by LLL0802** [comment]
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True
把tools/infer/utility.py文件里rec_char_dict_path = ./ppocr/utils/ppocr_keys_v1.txt改成了ic15_dict.txt
哦不对，不能叫检测，应该是测试识别的时候，默认的好像是汉字那个字典，但我想用英文字符的那个字典

**Comment by tink2123** [comment]
@yizhipipixia 
>这边所以说为了区分大小写我是应该使用rec_en_number_lite_train.yml这样的配置文件重新训练一个模型吗.

PaddleOCR提供了一个区分大小写的模型，对应的配置文件是这个。可以在这里下载：https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_number_mobile_v2.0_rec_infer.tar

预测时额外指定一下字典文件：--rec_char_dict_path="ppocr/utils/dict/en_dict.txt"

**Comment by tink2123** [comment]
@LLL0802 
> 会出现下标溢出的错误

如果希望替换成英文字典，预测模型也需要修改成英文模型。使用中文模型预测index，在英文字典里解码肯定是会越界的。

**Comment by yashwant07** [comment]
@yizhipipixia 您使用哪种模型检测文本？
