### ISSUE TITLE
在linux系统上运行predict_rec.py报mkl相关的错，烦请指教，谢谢。

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleOCR#1516]
您好，我在ubuntu系统上运行predict_rec.py报如下错误

(base) zhuys@claa-ECS-1837:~/ocr_meter$ python predict_rec.py --enable_mkldnn=False --image_dir="/home/meter/ocr_meter/test_crop" --rec_model_dir="/home/meter/ocr_meter/model/ch_ppocr_server_v1.1_rec_infer" --use_angle_cls=False --use_space_char=False
Intel MKL function load error: cpu specific dynamic library is not loaded.

我的机器cpu信息如下：
(base) zhuys@claa-ECS-1837:~/ocr_meter$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      4  Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz

是我的cpu不支持mkl吗？我已经设置了“--enable_mkldnn=False”，为什么还会报关于mkl的错误呢？烦请指教，谢谢。

**Comment by tink2123** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/440#issuecomment-665460443
试一下安装固定版本的requirements能否解决问题

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
