### ISSUE TITLE
如何关闭训练日志的输出？

### ISSUE THREAD

**Issue by ExcaliburEX** [PaddlePaddle/PaddleOCR#1518]
如图：
![image.png](https://i.loli.net/2020/12/19/6NuHjSvaYXhs9db.png)

这里的两句：
```bash
dt_boxes num : 1, elapse : 0.2715637683868408
rec_res num  : 1, elapse : 0.040621042251586914
```
每训练一次就会产生一次，貌似无法设置`logging`去屏蔽掉，有什么方法嘛？感谢回复！ @ZeyuChen 😸

**Comment by littletomatodonkey** [comment]
在下面这两个地方打印的，可以注释掉，然后重新制作whl包再安装即可。

https://github.com/PaddlePaddle/PaddleOCR/blob/af75806fd1d6c0f89dd0a3c44595596076b245a8/tools/infer/predict_system.py#L89
https://github.com/PaddlePaddle/PaddleOCR/blob/af75806fd1d6c0f89dd0a3c44595596076b245a8/tools/infer/predict_system.py#L106

**Comment by ExcaliburEX** [comment]
> 在下面这两个地方打印的，可以注释掉，然后重新制作whl包再安装即可。
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/af75806fd1d6c0f89dd0a3c44595596076b245a8/tools/infer/predict_system.py#L89
> 
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/af75806fd1d6c0f89dd0a3c44595596076b245a8/tools/infer/predict_system.py#L106

尝试成功！感谢指导，谢谢！:smile:
