### ISSUE TITLE
quick start 尝试出现问题

### ISSUE THREAD

**Issue by CSU-FulChou** [PaddlePaddle/PaddleOCR#1519]
![image](https://user-images.githubusercontent.com/46887649/102679959-0ca41080-41ef-11eb-903b-03822bb27e4b.png)

您好，
我在做完 quick start 之后， PaddlerOCR 里面自带的图片能够处理的很好。 但是自己的图片，处理的时候会卡着一直不动。

![image](https://user-images.githubusercontent.com/46887649/102679926-a0291180-41ee-11eb-8b27-2839a7a1b08b.png)

经过很久的运行 会输出结果 大概需要600多s
![image](https://user-images.githubusercontent.com/46887649/102680882-9f48ad80-41f7-11eb-9feb-cb9850d05d37.png)

是不是没有正常使用到 GPU呢？

**Comment by littletomatodonkey** [comment]
你好，你安装的Paddle应该是cpu版本，如果希望使用gpu版本的话，需要先卸载paddle，pip uninstall -y paddlepaddle，然后再安装 `pip install paddlepaddle-gpu==2.0.0rc1`

**Comment by CSU-FulChou** [comment]
谢谢，您好，再尝试使用 GPU版本的Paddle 我的机器出现下面的错误
![image](https://user-images.githubusercontent.com/46887649/102683177-f9eb0500-4209-11eb-96ec-f6902f9f0b3a.png)
我使用的是 官方 给的cuda10 docker 镜像。 但是里面没有 ‘CXXABI_1.3.111' 
![image](https://user-images.githubusercontent.com/46887649/102683204-30c11b00-420a-11eb-9df7-1643693f9f57.png)

最多只有 1.3.9. 是否和我的ubuntu 的版本是 16.04 有关呢？
感谢解答

**Comment by grasswolfs** [comment]
应该和操作系统无关，可以试下最新代码，应该可以解决
