### ISSUE TITLE
configs/rec/rec_icdar15_reader.yml 细节修正

### ISSUE THREAD

**Issue by maplehan2009** [PaddlePaddle/PaddleOCR#152]
configs/rec/rec_icdar15_reader.yml中img_set_dir 应该精确到图片文件夹所在路径，默认文件中是./train_data/ic15_data，是否应该改成 ./train_data/ic15_data/train

**Comment by tink2123** [comment]
config中的 img_set_dir 指向的是数据集目录，ic15_data 下还有 train 和 test，具体使用哪个数据集在label里是有区分的。

**Comment by maplehan2009** [comment]
了解，那 configs/rec/rec_icdar15_reader.yml 里的 img_set_dir 建议修改成 ./train_data/ic15_data/train

**Comment by tink2123** [comment]
感谢建议，考虑到 train 和 eval 的 label 都放在 ic15_data 路径下，且目前label格式为：
```
test/word_1.png JOINT
train/word_1.png Genaxis Theatre
```
为了尽量减小结构改动，这里暂时不做修改
