### ISSUE TITLE
输入训练命令后 停住不动了，什么原因呢？

### ISSUE THREAD

**Issue by tongtong9293** [PaddlePaddle/PaddleOCR#1520]
用anaconda在环境下安装了cudnn7.6.4以及 cuda10.0，输入训练命令时，没有出现报错，但是停在图片中的样子不动了（25分钟以上），也不出现训练过程及结果，请问这是什么原因呢？ 我应该如何处理呢？感谢！！！
![image](https://user-images.githubusercontent.com/48546049/102683924-3ec56a80-420f-11eb-8363-812ea76e8af1.png)
![image](https://user-images.githubusercontent.com/48546049/102683925-4258f180-420f-11eb-9cee-a45af2e61b9e.png)
![image](https://user-images.githubusercontent.com/48546049/102683926-46850f00-420f-11eb-957a-2988ec7620e0.png)
![image](https://user-images.githubusercontent.com/48546049/102683928-4ab12c80-420f-11eb-9c25-7e414caaa9a4.png)
![image](https://user-images.githubusercontent.com/48546049/102683919-3836f300-420f-11eb-9b08-4274ecda68ce.png)

**Comment by tink2123** [comment]
可能是在数据读取的阶段卡住了，可以将训练bs先调小至1试试能否正常启动。另外不建议修改检测的 image shape，检测中代表的是随机crop的size，使用默认数值即可。

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
