### ISSUE TITLE
Windows环境下自己编译通过，但执行报Error: operator rnn has not been registed

### ISSUE THREAD

**Issue by mripet** [PaddlePaddle/PaddleOCR#1521]
Hint: op_info_ptr should not be null.
paddlefluid 版本为2.0.0beta.
先用的paddlefluid 版本为1.8.3 报Error: operator nearest_interp_v2 has not been registed.  Hint: op_info_ptr should not be null.
有知道原因的吗？编译都显示成功。

**Comment by MissPenguin** [comment]
需要换2.0rc1的paddle
