### ISSUE TITLE
关于ai studio部署

### ISSUE THREAD

**Issue by longshifeng** [PaddlePaddle/PaddleOCR#1522]
在使用ai studio平台 训练paddleocr-develop时

平台自带cuda 10.1 但是好像没有cudnn ,并且没有sudo权限

难不成每次开启环境都要重装cuda+cudnn??

请问这种应该怎么使用GPU训练？

**Comment by LDOUBLEV** [comment]
AI studio 启动时可以选择使用高级版，基础版默认CPU版本
![image](https://user-images.githubusercontent.com/26592129/102756786-5c2f3b80-43ab-11eb-9682-3873fbbb435b.png)
