### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#1524]
ｉ　use python3 tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.pretrain_weights=./ch_ppocr_server_v2.0_det_train/best_accuracy Global.load_static_weights=FalseGlobal.save_inference_dir=./inference/db_det  to get convert model and param

and  use "python3 tools/infer/predict_det.py --image_dir="/./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/db_det" to predict but it have no results,no boxes are detected, also i try lot of images it detect no boses

i don't known why,can you help me? thks

**Comment by tfidmmatthew** [comment]
How do you fix it?
