### ISSUE TITLE
StyleText README_ch 笔误

### ISSUE THREAD

**Issue by merlin95X** [PaddlePaddle/PaddleOCR#1527]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/StyleText/README_ch.md#快速上手
中 批量合成 运行tools/synth_dataset合成数据：
命令应该为 python3 tools/synth_dataset.py -c configs/dataset_config.yml
而不是 python XXXX

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/1538
