### ISSUE TITLE
AttributeError: module 'paddle.distributed' has no attribute 'get_rank'

### ISSUE THREAD

**Issue by SasiAravind** [PaddlePaddle/PaddleOCR#1529]
Hi, 
i was tring  to using pip install "paddleocr>=2.0.1" and i am getting  following Attribute error while running example:

paddle version:
python -m pip install paddlepaddle-gpu==2.0.0rc1.post101 -f https://paddlepaddle.org.cn/whl/stable.html
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-99cfb22fa6f5> in <module>()
----> 1 from paddleocr import PaddleOCR,draw_ocr
      2 # Paddleocr supports Chinese, English, French, German, Korean and Japanese.
      3 # You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
      4 # to switch the language model in order.
      5 ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
/content/PaddleOCR/paddleocr.py in <module>()
     26 from tqdm import tqdm
     27 
---> 28 from tools.infer import predict_system
     29 from ppocr.utils.logging import get_logger
     30 

/content/PaddleOCR/tools/infer/predict_system.py in <module>()
     25 from PIL import Image
     26 import tools.infer.utility as utility
---> 27 import tools.infer.predict_rec as predict_rec
     28 import tools.infer.predict_det as predict_det
     29 import tools.infer.predict_cls as predict_cls

/content/PaddleOCR/tools/infer/predict_rec.py in <module>()
     31 from ppocr.utils.utility import get_image_file_list, check_and_read_gif
     32 
---> 33 logger = get_logger()
     34 
     35 

/usr/local/lib/python3.6/dist-packages/paddleocr/ppocr/utils/logging.py in get_logger(name, log_file, log_level)
     59         file_handler.setFormatter(formatter)
     60         logger.addHandler(file_handler)
---> 61     if dist.get_rank() == 0:
     62         logger.setLevel(log_level)
     63     else:

AttributeError: module 'paddle.distributed' has no attribute 'get_rank'

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/102755412-53d60100-43a9-11eb-970e-21a395106bcd.png)
please check your paddle is installed correctly.

**Comment by SasiAravind** [comment]
hi @LDOUBLEV  thanks for your support .

The problem was solved once i installed correctly.

**Comment by wilkice** [comment]
By the way, if you are installing the CPU version of Paddle, use `pip install paddlepaddle==2.0.0rc1` other than `pip install paddlepaddle`.

**Comment by kalai2033** [comment]
@SasiAravind i have seen your github comment in other issue for adding Tamil language. I believe you have come across both EasyOCR and PaddleOCR. Can you give few points on EasyOCR vs PaddleOCR comparison?
