### ISSUE TITLE
    from paddle.io import Dataset, DataLoader, BatchSampler, DistributedBatchSampler ModuleNotFoundError: No module named 'paddle.io'

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#1530]
i found many wired problems,paddle 1.8.5,and i run python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/db_det/ch_ppocr_mobile_v2.0_cls_infer" it raised 
    from paddle.io import Dataset, DataLoader, BatchSampler, DistributedBatchSampler ModuleNotFoundError: No module named 'paddle.io'

paddleocr is default vesrsion dygraph

**Comment by cqray1990** [comment]
after install paddlepaddle-gpu==2.0.0rc1.post100,the errors disappear,but anther problem comes,
  File "./PaddleOCR/ppocr/postprocess/db_postprocess.py", line 140, in __call__
    pred = pred[:, 0, :, :]
IndexError: too many indices for array


i doubt the method in readme to test an model is not clear?

**Comment by cqray1990** [comment]
<class 'dict'>: {'maps': array([[0.04196427, 0.95803577]], dtype=float32)
the code in db_postprocess bug?

  pred = outs_dict['maps']
        if isinstance(pred, paddle.Tensor):
            pred = pred.numpy()
        pred = pred[:, 0, :, :]
        segmentation = pred > self.thresh

**Comment by WenmuZhou** [comment]
Your model is wrong. You used the classifier model, you should actually use the detected model
