### ISSUE TITLE
怎么把3070的性能利用起来

### ISSUE THREAD

**Issue by wowowoll** [PaddlePaddle/PaddleOCR#1533]
在3070上跑paddleocr，显卡的性能利用率不到40%，有时候只有20%多。
![image](https://user-images.githubusercontent.com/49295186/102743145-d05ce580-4391-11eb-94f8-100a49a16b43.png)
使用的是docker pull paddlepaddle/paddle:2.0.0rc1-gpu-cuda11.0-cudnn8 镜像

**Comment by LDOUBLEV** [comment]
你跑的实验是哪个模型 ，文本检测模型？ 目前还没有在-cuda11.0-cudnn8  上测试过运行速度

**Comment by wowowoll** [comment]
![image](https://user-images.githubusercontent.com/49295186/102756390-ce535080-43aa-11eb-94ff-e34ad7615044.png)
yon用的1.1版本的文本识别和检测模型

**Comment by wowowoll** [comment]
目前性能只有20帧的样子

**Comment by grasswolfs** [comment]
这是用PaddleServing的方式跑的么？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
