### ISSUE TITLE
predict_system.py和paddleocr.py预测结果不一致

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#1534]
请问tools/infer/predict_system.py和paddleocr.py的区别在哪吗？自己训练了一个模型，分别用这两种方式进行测试，对同一图片在同一机器上设置相同的参数，识别结果差别有点大，有哪位大佬可以解答一下吗？
![image](https://user-images.githubusercontent.com/13652569/102746564-7cee9580-4399-11eb-8928-f50a66d56901.png)
![image](https://user-images.githubusercontent.com/13652569/102746584-837d0d00-4399-11eb-872b-5a9fdaa0da0e.png)

**Comment by MissPenguin** [comment]
自己训练的识别模型吗，训练时修改了哪些参数呢，预测时相应的参数都有修改吗

**Comment by Lie-huo** [comment]
> 自己训练的识别模型吗，训练时修改了哪些参数呢，预测时相应的参数都有修改吗

自己训练的识别模型，就只自定义了字典，其他的参数都是默认的

**Comment by Lie-huo** [comment]
> > 自己训练的识别模型吗，训练时修改了哪些参数呢，预测时相应的参数都有修改吗
> 
> 自己训练的识别模型，就只自定义了字典，其他的参数都是默认的

使用paddleocr.py的结果基本上都是正确的，但是tools/infer/predict_system.py的错误比较多

**Comment by MissPenguin** [comment]
用最新代码试试呢，如果还有问题欢迎重新提issue，我们会继续跟进～

**Comment by Actor12** [comment]
> 请问tools/infer/predict_system.py和paddleocr.py的区别在哪吗？自己训练了一个模型，分别用这两种方式进行测试，对同一图片在同一机器上设置相同的参数，识别结果差别有点大，有哪位大佬可以解答一下吗？
> ![image](https://user-images.githubusercontent.com/13652569/102746564-7cee9580-4399-11eb-8928-f50a66d56901.png)
> ![image](https://user-images.githubusercontent.com/13652569/102746584-837d0d00-4399-11eb-872b-5a9fdaa0da0e

请问你是怎么解决的？我遇到了同样的问题
