### ISSUE TITLE
怎样为自己训练过的模型加入学习率衰减策略

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#1536]
之前训练模型的时候， 没有在Optimizer 配置项中加入decay 字段，模型训练一段时间后，精度已经上不去了，可能是学习率在训练过程中没有调整的原因造成的，所以想在之前训练好的模型里加入学习率衰减策略，但是遇到了问题。
best_accuracy.pdopt  是我之前没有加decay时训练的。
![image](https://user-images.githubusercontent.com/61573829/102752302-4ff3b000-43a4-11eb-9bab-ddcd11cd4a45.png)
之前训练时设置的Optimizer
![image](https://user-images.githubusercontent.com/61573829/102752385-74e82300-43a4-11eb-8caf-f3ea618105f0.png)

加入decay后设置的Optimizer
![image](https://user-images.githubusercontent.com/61573829/102752643-cf817f00-43a4-11eb-9cc4-256ed04a4972.png)

难道只能重新训练么？ T_T

**Comment by LDOUBLEV** [comment]
as https://github.com/PaddlePaddle/PaddleOCR/issues/1537
