### ISSUE TITLE
det_limit_side_len的作用？？

### ISSUE THREAD

**Issue by frotms** [PaddlePaddle/PaddleOCR#1539]
release/2.0-rc1-0版本，tools/infer/predict_det.py使用`det_limit_side_len=960`和`det_limit_type='max'`参数似乎起不到效果，我输入了一张(3024, 4032,3)的图，推理前shape是(3,3008,4032)

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/1544/files  在这里修了哈
