### ISSUE TITLE
paddleOCR识别少一行

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#1545]
paddleOCR识别少一行
paddlehub：2.0.0b1
paddlepaddle-gpu：2.0.0rc1
code:
ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
result = ocr.recognize_text(images=[cv2.imread( r'D:\fb56028efc3249f5b6317ea91b205413\2.png')]
                            ,box_thresh = 0.5,
                            text_thresh = 0.5
                            )
line = result[0]
datas = line['data']
for data in datas:
    print(data['text'])
图片不方便上传，微信里联系我，谢谢

**Comment by dengmingD** [comment]
![1](https://user-images.githubusercontent.com/72127773/102839847-6f3e1c00-443c-11eb-8a38-d76c2944e70d.jpg)

**Comment by LDOUBLEV** [comment]
我用 ch_ppocr_mobile_v1.1_det_infer  ch_ppocr_mobile_v1.1_rec_infer 模型识别的还行
![image](https://user-images.githubusercontent.com/26592129/102840820-a31a4100-443e-11eb-81c5-b452a8be1d32.png)

**Comment by LDOUBLEV** [comment]
是指少了第一行的下划线吗？

**Comment by dengmingD** [comment]
我的测试结果，少一行
用的模型：

ch_ppocr_mobile_v1.1_det_infer ch_ppocr_mobile_v1.1_rec_infer




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 上午10:16
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"dm"<2236483949@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] paddleOCR识别少一行 (#1545)





 
是指少了第一行的下划线吗？

**Comment by LDOUBLEV** [comment]
预测的时候把这两个参数的值改一下  --det_db_thresh=0.1 --det_db_box_thresh=0 应该是检测框置信度较低，过滤掉了。我这边测试不会漏框了

**Comment by dengmingD** [comment]
又发现漏行
参数已调成 --det_db_thresh=0.1 --det_db_box_thresh=0
漏行图片如下：

**Comment by dengmingD** [comment]
漏行图片如下：

**Comment by dengmingD** [comment]
又发现漏
参数： --det_db_thresh=0.1 --det_db_box_thresh=0
漏行图片如下：
![paddle_ocr_loss_lines](https://user-images.githubusercontent.com/72127773/103199266-70cc8000-4925-11eb-8559-ac922a7748e0.png)

**Comment by HeYilong0316** [comment]
> 

@LDOUBLEV   您好 请问这两个参数改到0.1和0.0这么低的话，目前用下来会有什么问题吗？ 我也遇到了这个问题，还不确定这两个参数改到多低合适。谢谢
