### ISSUE TITLE
PaddleHub Serving部署后识别不了文字，但是本地的paddlepaddleocr包或者直接tools/infer/predict_system.py都可以

### ISSUE THREAD

**Issue by ExcaliburEX** [PaddlePaddle/PaddleOCR#1548]
请问有什么办法嘛，搞了两天了，头疼。无论是用`2.0.0rc1`的代码还是`1.1`的代码都是一样的结果，各种`rec`模型也都试过了，都是识别不出来，但是用`paddlepaddleocr`包或者直接`tools/infer/predict_system.py`都能识别。是不是我的`./inference/ch_ppocr_mobile_v1.1_rec_infer/`放错位置了，我是放在了直接clone过来的`PaddleOCR`以及目录下。
#1302 @ZeyuChen @ZhangXinNan :cry: :smile: 感谢答复！

**Comment by MissPenguin** [comment]
“识别不了文字”是什么意思，没有结果，还是效果不好，还是报错？麻烦描述一下具体操作流程和运行结果。

**Comment by ExcaliburEX** [comment]
#

> “识别不了文字”是什么意思，没有结果，还是效果不好，还是报错？麻烦描述一下具体操作流程和运行结果。

具体流程如下：

1.  `git clone https://github.com/PaddlePaddle/PaddleOCR/ && cd PaddleOCR` # 下载项目
2.  `vim deploy/hubserving/ocr_rec/params.py` # 修改
  - ```python
    cfg.rec_model_dir = "./inference/ch_ppocr_mobile_v1.1_rec_infer/"
    ```
  为
  - ```python
    cfg.rec_model_dir = "./inference/ch_ppocr_mobile_v2.0_rec_infer/"
    ```
- 明明文档里面是默认最新的模型，但是无论是`dygraph`还是`release/1.1`分支还是默认`1.1`的模型，但是`1.1`的模型也是一样的，我试过了。
 
3.  `mkdir inference` # 创建`inference`文件夹
4.  `wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar && tar xf ch_ppocr_server_v2.0_rec_infer.tar` # 下载模型
5.  安装`paddlehub`:`pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple`
6. `cd ..` # 回到`PaddleOCR`主目录
7.  安装识别服务: `hub install deploy\hubserving\ocr_rec\`
8.  启动识别服务: `hub serving start --modules ocr_rec --port 8866` 默认模型版本`1.0.0`，但是不知道怎么改成其他版本，改成`ocr_rec==2.0.0`会报错
9. 然后本地我修改了`tools/test_hubserving.py`，因为我要训练网络图片，修改后的版本跟之前差别不大，只是图片读取方式变了,我贴一下：

原本读取图片的方式:
```python
img = open(image_file, 'rb').read()
``` 
我的版本:
```python
r = requests.get(image_file)
img = Image.open(BytesIO(r.content))
img_bytes = io.BytesIO()
img.save(img_bytes, format="JPEG")
i = img_bytes.getvalue()
img = i
```
识别的图片为：`https://i.loli.net/2020/12/21/RTCQGyu6J2jPefH.jpg`
![](https://i.loli.net/2020/12/21/RTCQGyu6J2jPefH.jpg)

结果为：
```bash
Predict time of https://i.loli.net/2020/12/21/RTCQGyu6J2jPefH.jpg: 0.290s
[{'confidence': 0.1577274352312088, 'text': '5'}]
avg time cost: 0.2902231216430664
```

然后直接调用`PaddleOCR`识别为:
```bash
[[[162.0, 448.0], [417.0, 448.0], [417.0, 520.0], [162.0, 520.0]], ['菜就是菜', 0.9765369]]
[[[98.0, 524.0], [474.0, 527.0], [474.0, 592.0], [98.0, 589.0]], ['还他妈找借口', 0.99835044]]
```

## 现在的问题是部署服务，本地连接后，识别率超低。直接运行`PaddleOCR`的包还是`tools/infer/predict_system.py`都可以完美识别。

**Comment by ExcaliburEX** [comment]
> “识别不了文字”是什么意思，没有结果，还是效果不好，还是报错？麻烦描述一下具体操作流程和运行结果。

在线等小姐姐解答~:smile: 😸

**Comment by ExcaliburEX** [comment]
> “识别不了文字”是什么意思，没有结果，还是效果不好，还是报错？麻烦描述一下具体操作流程和运行结果。

我貌似发现了问题所在，用了`ocr_system`可以识别，但是单独用`ocr_rec`就不行。
用`ocr_system`识别结果为：
```bash
Predict time of mypicture.jpg: 0.720s
[{'confidence': 0.9844685196876526, 'text': '你滚吧别挡我发财臭男人', 'text_region': [[49, 445], [515, 442], [515, 486], [49, 488]]}]
avg time cost: 0.7197504043579102
```

**Comment by xmy0916** [comment]
ocr_systems是包含了检测和识别，ocr_rec是单独识别的，你可以试试把文字部分截取出来然后使用ocr_rec识别

**Comment by Macielyoung** [comment]
> > “识别不了文字”是什么意思，没有结果，还是效果不好，还是报错？麻烦描述一下具体操作流程和运行结果。
> 
> 我貌似发现了问题所在，用了`ocr_system`可以识别，但是单独用`ocr_rec`就不行。
> 用`ocr_system`识别结果为：
> 
> ```shell
> Predict time of https://i.loli.net/2020/12/21/RTCQGyu6J2jPefH.jpg: 0.795s
> [{'confidence': 0.8854655027389526, 'text': '菜就是菜', 'text_region': [[158, 450], [416, 452], [416, 521], [158, 519]]}, {'confidence': 0.9942235350608826, 'text': '还他
> 妈找借口', 'text_region': [[99, 527], [477, 529], [477, 594], [99, 592]]}]
> avg time cost: 0.7952899932861328
> ```
> 
> @Macielyoung 您也可以看看，貌似可以解决问题。

👍👍。感谢感谢，我抽空也去尝试一下看看

**Comment by MissPenguin** [comment]
你这张图需要先检测后识别，也就是应该安装ocr_system（能正确识别的tools/infer/predict_system.py也是检测+识别，和ocr_system是对应的），而ocr_rec只是识别模块，所以结果不对

**Comment by ExcaliburEX** [comment]
> 你这张图需要先检测后识别，也就是应该安装ocr_system（能正确识别的tools/infer/predict_system.py也是检测+识别，和ocr_system是对应的），而ocr_rec只是识别模块，所以结果不对

 懂啦！不过这个`ocr_system`真的吃内存啊，阿里云就买了个4G的，基本拉满了。。
