### ISSUE TITLE
StyleText支持训练自己的模型吗，训练是端到端的吗，还是分模块训练的？

### ISSUE THREAD

**Issue by 1171800323** [PaddlePaddle/PaddleOCR#1549]
中间结果如fake_bg, fake_sk, fake_text这些图像效果很好，如果端到端训练的话有可能做到这些吗？
我做了一些实验复现Editing text in the wild这篇论文，在我的结果里fake_text图像就是一片灰，无法辨认，增加对比度以后可以稍微识别出文字，fake_sk也无法辨认为文字，而是粘连在一起，只有bg和fusion结果比较好

**Comment by littletomatodonkey** [comment]
分开训练效果会更好一些，StylText目前只开源了预测部分，后续我们会开源训练部分，敬请期待

**Comment by 1171800323** [comment]
> 
> 
> 分开训练效果会更好一些，StylText目前只开源了预测部分，后续我们会开源训练部分，敬请期待

分开训练就是指三个模块分别训练了吧，这样会比端到端训练的模型更强吗？一般不都是端到端的模型会更好一点吗，论文里面也说是端到端训练的？

**Comment by superdu12138** [comment]
> 分开训练效果会更好一些，StylText目前只开源了预测部分，后续我们会开源训练部分，敬请期待

训练代码开源了吗

**Comment by grasswolfs** [comment]
目前还没有哈，我们近期在PPOCRv2上投入比较多，style-text优先级有些靠后

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
