### ISSUE TITLE
关于Tensorrt加速

### ISSUE THREAD

**Issue by guanshuicheng** [PaddlePaddle/PaddleOCR#155]
参数可传参数部分有use_tensorrt，咨询关于Tensorrt加速是否有实现的计划

**Comment by LDOUBLEV** [comment]
后续会支持TR加速，不过目前没有排期

**Comment by sangwentao** [comment]
现在paddleocr支持use_tensorrt参数吗？

**Comment by sangwentao** [comment]
> 会支持TR加速，不过目前没有排期
现在paddleocr支持use_tensorrt参数吗？
