### ISSUE TITLE
W1222 13:22:10.633201 10788 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.

### ISSUE THREAD

**Issue by helindemeng** [PaddlePaddle/PaddleOCR#1550]
Versions: paddlepaddle-gpu==2.0.0rc1.post101

![image](https://user-images.githubusercontent.com/66064229/102852685-be467a00-4459-11eb-9888-8b48e427fa9a.png)

**Comment by helindemeng** [comment]
Run the program in Python

**Comment by littletomatodonkey** [comment]
这个是警告，目前还是可以使用的，这个在api在后续我们会更新到最新，谢谢~

**Comment by WenmuZhou** [comment]
最新代码已经更新

**Comment by Jimw338** [comment]
*Where* is "analysis_predictor.cc"?  I got this error using the "Chinese-comprehension" project, which in turn uses "LAC" ("Lexical Analysis of Chinese").  <humor> Is this a literal "ghost in the machine"?..
