### ISSUE TITLE
可以识别数学公式么

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1551]
您好，我想识别数学公式，这个可以识别么？
![image](https://user-images.githubusercontent.com/43515926/102859605-294a7d80-4467-11eb-8ca4-98ad4abba5e0.png)

**Comment by littletomatodonkey** [comment]
目前还不支持这种公式识别

**Comment by zcswdt** [comment]
> 目前还不支持这种公式识别

好的，请问有没有思路识别数学公式呢

**Comment by grasswolfs** [comment]
这个太难了，市面上应该有打印体的公式识别，这么乱的基本搞不定

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
