### ISSUE TITLE
文本检测的数据增广

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#1552]
这个套件有针对自己准备的文本检测数据集的增广功能吗？类似PaddleDetection中的一些数据增强算子，比如ResizeImage、RandomDistort等，感觉这个对训练自己的数据集尤其是数据集量不大的时候很有用。

**Comment by littletomatodonkey** [comment]
检测里面的部分增广可以参考这里，如果需要增加的话，可以试着自己先集成一下哈

https://github.com/PaddlePaddle/PaddleOCR/blob/45f647db3f567f78de1506e596c26785dddd8436/ppocr/data/imaug/iaa_augment.py#L53

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
