### ISSUE TITLE
Tensor holds the wrong type, it holds int64_t, but desires to be float

### ISSUE THREAD

**Issue by yy2lyx** [PaddlePaddle/PaddleOCR#1554]
![image](https://user-images.githubusercontent.com/35443937/102871646-9d8e1c80-4479-11eb-8f6c-12ce6845dfb1.png)
前面的检测模型可以生成了，但是到ocr的输出字符串的时候就出现这种问题，这种如何解决。
Paddle预测库版本：2.0.0-rc1
PaddleOCR 版本：2.0-rc1-0
编译C++ocr检测的例子中出现的问题

**Comment by LDOUBLEV** [comment]
你用的预测库链接可以发一下吗，我这边测试没遇到类似问题

**Comment by LDOUBLEV** [comment]
请确保使用 rc1 的预测库，或者自己用Paddle 2.0rc1分支编译预测库 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

另外，昨天dygraph分支的 cpp_infer 预测代码已经更新为最新预测库接口，可以更新代码

**Comment by yy2lyx** [comment]
> 你用的预测库链接可以发一下吗，我这边测试没遇到类似问题

我用的也是https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/windows_cpp_inference.html地址下的
![image](https://user-images.githubusercontent.com/35443937/102950876-834e5000-4506-11eb-9940-082bf02537f8.png)

**Comment by yy2lyx** [comment]
> 请确保使用 rc1 的预测库，或者自己用Paddle 2.0rc1分支编译预测库 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> 
> 另外，昨天dygraph分支的 cpp_infer 预测代码已经更新为最新预测库接口，可以更新代码

刚也更新了paddleocr的dygraph分支，但是还是报相同的错误，我不知道是不是这里的问题（由于编译过不了，报未定义标识符not，然后我这里把not改成了！，这里就编译 通过了，但是就会报上面的错误）
![image](https://user-images.githubusercontent.com/35443937/102950991-cb6d7280-4506-11eb-8709-b290814f6122.png)

**Comment by BiggerBinBin** [comment]
我也遇到同样的问题，把std::vector<float> predict_batch;改成std::vector<int64_t> predict_batch;就不会崩，但是预测全是 -nan(ind)
