### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#1555]
when img_mode ='GRAY': why not  img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)?

if self.img_mode == 'GRAY':
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        elif self.img_mode == 'RGB':

**Comment by WenmuZhou** [comment]
Because the current network input is three-channel, it does not support single-channel input

**Comment by cqray1990** [comment]
@WenmuZhou  can train gray images? if we want to train gray images, can we convert img to gray directly,that is
if self.img_mode == 'GRAY':
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

so we can train gray images, is it easy to do this,why not support ?

**Comment by cqray1990** [comment]
in some cases we don't need  3 channels to train

**Comment by WenmuZhou** [comment]
change this default value to 1

**Comment by cqray1990** [comment]
change config yaml file img shape to 1,32,320?

**Comment by cqray1990** [comment]
@WenmuZhou

**Comment by cqray1990** [comment]
@WenmuZhou change config yaml file img shape to 1,32,320 to support train gray images Reconginise

**Comment by grasswolfs** [comment]
It seems to be a good idea.
