### ISSUE TITLE
识别时可以输入时指定LoDTensor吗

### ISSUE THREAD

**Issue by strgrb** [PaddlePaddle/PaddleOCR#1556]
我现在有很多长短不同的文字图片，现在想做batch输入进去，但是padding性能可能会比较低，有没有办法解决这个问题，比如使用LoDTensor？

**Comment by LDOUBLEV** [comment]
目前已经不建议使用LoDTensor了，padding性能还行吧，经测试，batch为6 -10 之间，整体速度是比较快的
