### ISSUE TITLE
怎么输出网络结构以及每层的参数信息

### ISSUE THREAD

**Issue by CaRRotOne** [PaddlePaddle/PaddleOCR#1558]
请问paddleocr里面如何输出网络结构以及每层的参数信息，类似tensorflow中的model.summary()

**Comment by WenmuZhou** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/hapi/model_summary/summary_cn.html#summary  可以试一下这个api

**Comment by caopulan** [comment]
修改head的返回，在forward里把返回字典改为返回最后一层，然后用楼上的那个接口就可以。
