### ISSUE TITLE
有计划对繁体字做支持吗

### ISSUE THREAD

**Issue by fangkuann** [PaddlePaddle/PaddleOCR#156]
目前来看如果字幕是繁体字的话， 错误率挺高的

**Comment by LDOUBLEV** [comment]
繁体字识别错误率高主要原因是识别网络的训练数据中繁体字比较少。目前暂时没有支持繁体字的排期，你可以根据我们release的中文模型进行fine-tune，加入繁体字数据进行训练

**Comment by fangkuann** [comment]
好的，英文单词现在识别出来是粘粘在一起的，这个可以做分词处理么

**Comment by guanshuicheng** [comment]
英文单词间的空格可以单独作为一个字符加入字典训练，我之前训练过CRNN的，效果特别好。
