### ISSUE TITLE
使用multiprocessing时会报错

### ISSUE THREAD

**Issue by siriusi** [PaddlePaddle/PaddleOCR#1560]
使用multiprocessing进行多进程时会报 “can't pickle paddle.fluid.core_avx.AnalysisPredictor objects” 错误，请问如何解决？

**Comment by xmy0916** [comment]
更新最新版的paddlepaddle试试

**Comment by siriusi** [comment]
> 更新最新版的paddlepaddle试试

费尽千辛万苦使用了paddlepaddle2.0.0rc1依然报同样错误。

**Comment by hanlanyi** [comment]
你的python是什么版本的？

**Comment by siriusi** [comment]
> 你的python是什么版本的？
Python 3.6.6

**Comment by liyandongpy** [comment]
我也遇到了，好像不能进行多进程infer。
