### ISSUE TITLE
关于学习率衰减策略

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#1563]
您好，我看到识别模型最新版本的训练学习率策略改变了，请问学习率策略的变化主要是哪些呢？这样变化对训练有哪些优势呢？
之前版本的学习率策略：
![image](https://user-images.githubusercontent.com/43515926/102972655-5ca80d80-4536-11eb-88b5-7e17e34e38dd.png)
最新版本的学习率策略：
![image](https://user-images.githubusercontent.com/43515926/102972788-924cf680-4536-11eb-8d67-35f468afdbb2.png)

**Comment by xmy0916** [comment]
您好！策略没有变化，您这两张图一个做了decay 一个没做，decay之前的配置文件里也是支持的

**Comment by zcswdt** [comment]
> 您好！策略没有变化，您这两张图一个做了decay 一个没做，decay之前的配置文件里也是支持的

谢谢回复，我想问您一下，那个decay下面的参数step_each_epoch和total_epoch这两个参数代表什么意思呢？请您指教一下。

**Comment by littletomatodonkey** [comment]
`step_each_epoch `表示每个epoch中有多少个minibatch，`total_epoch `表示总共要训多少个epoch，cosine decay需要根据这个确定学习率下降的具体值

**Comment by zcswdt** [comment]
> 个epoch中有多少个minibatch

谢谢回复，我使用旧版训练的时候发现学习率是周期性变化的，这样不太容易找到最优解，因为学习率出现最小的时候是最少的。

**Comment by grasswolfs** [comment]
可以再看下哈，学习率加了warmup，但是不会反复周期变化的

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
