### ISSUE TITLE
style-text文本生成

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#1565]
将style-text生成的文本数据放入OCR模型训练后，识别准确率反而降低了约1%，查看发现很多背景没有扣干净的数据，如：
![14](https://user-images.githubusercontent.com/44627542/102981642-3ab58780-4544-11eb-9990-3f233394e99f.png)
![17](https://user-images.githubusercontent.com/44627542/102981644-3c7f4b00-4544-11eb-8935-34a0df4fb579.png)

请问后面会在这方面进行优化吗？

**Comment by xmy0916** [comment]
感谢您的使用，后续会继续优化的！

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。
