### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.config'

### ISSUE THREAD

**Issue by KelleyYin** [PaddlePaddle/PaddleOCR#1566]
Hey guys, 

When I run the command， `python3 tools/synth_image.py -c configs/config.yml --style_image examples/style_images/2.jpg --text_corpus PaddleOCR --language en
`, it has the following error .

```
Traceback (most recent call last):
  File "tools/synth_image.py", line 23, in <module>
    from utils.config import ArgsParser
ModuleNotFoundError: No module named 'utils.config'
```

What should I do ?

Thx!

**Comment by xmy0916** [comment]
you should export your PYTHONPATH.
For example:
cd PaddleOCR
export PYTHONPATH=./
@KelleyYin

**Comment by littletomatodonkey** [comment]
可以试着拉下最新代码
