### ISSUE TITLE
easy edge 跟自带的demo算法不同吗

### ISSUE THREAD

**Issue by goldenduo** [PaddlePaddle/PaddleOCR#1570]
二维码下载的EasyEdge demo 跟 自带的android demo 同一个图结果却是不同的？

**Comment by goldenduo** [comment]
分析了下，大概明白原因了。

**Comment by zouxiaoshi** [comment]
@goldenduo 大佬，求分析。感觉 easyedge demo和自己编译的demo 效果相差很大，一直不明白是什么原因。
