### ISSUE TITLE
Nano上使用cpu c++推理，识别结果和在PC端使用GPU python差异比较大

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/PaddleOCR#1571]
nano环境：jetpack4.3，cuda10.0，cudnn7.6，c++代码是develop分支，paddle推理库官网下载的已编译的Nano 2.0rc
PC端环境：cuda10.0，cudnn7.6，python3.7, paddle推理库2.0rc。
模型是的PC端训练的。
问题：分别在nano和PC端测试同一张图片，文字都可以检测出来，但是识别的结果Nano上是错误或者没有识别，PC端是正确，已经确认过Nano上的config.txt配置参数是相同的，这个问题困扰好久，希望可以帮忙解答一下，可提供模型和测试代码，图片，期待回复，非常感谢。

**Comment by littletomatodonkey** [comment]
PC端和nano端用的是同一套c++代码吗？

**Comment by python-bookworm** [comment]
> PC端和nano端用的是同一套c ++代码吗？

PC端使用的是python测试，在Nano上使用的是C++代码，今天我把推理库换成了最新的rc1，错误的结果还是一样，这种问题要怎样处理，因为测试的结果有30%的差异，所以提出这样问题，望答复，感谢。

**Comment by grasswolfs** [comment]
可以先试下官方模型和代码，从文件输入，到预处理，预测结果，后处理一层一层的对比一下差异性

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
