### ISSUE TITLE
ocr模型可以转化为openvino框架下的模型，在openvino框架下运行吗？ 

### ISSUE THREAD

**Issue by ZOUYIyi** [PaddlePaddle/PaddleOCR#1572]
如题
类似于yolov3的检测模型可以转化到openvino上，
希望paddle的ocr模型也能转化，不知是否可以，如可以，能给出参考链接吗？

**Comment by MissPenguin** [comment]
抱歉暂时不支持哈

**Comment by ZOUYIyi** [comment]
> 抱歉暂时不支持哈

好的。。。谢谢您在开源上的工作！

**Comment by Joshua-china** [comment]
检测部分可以转化成openvino框架下的模型吗？
