### ISSUE TITLE
pdserving grpc client请求问题

### ISSUE THREAD

**Issue by CaRRotOne** [PaddlePaddle/PaddleOCR#1575]
pdserving 部署方式http有client相关例子，请问grpc client有相关的例子吗？
运行python -m paddle_serving_server.serve后,用grpc请求报错:
`
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 640, the input's shape is [1, 640, 640, 3]; the filter's channels is 3, the filter's shape is [8, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:640 != filter_dims[1] * groups:3.] at (/paddle/paddle/fluid/operators/conv_op.cc:94)`

我看了下server端的配置，是需要640*640，所以resize了图片。请帮忙解答错误原因。

**Comment by MissPenguin** [comment]
是在develop分支操作的吗，serve没有要求640*640啊，client是通用的，完全按照文档什么都不改能跑通吗

**Comment by CaRRotOne** [comment]
> 是在develop分支操作的吗，serve没有要求640*640啊，client是通用的，完全按照文档什么都不改能跑通吗

是的，pdserving_client.py是http方式，是可以跑通的。GRPC是我自己写的，出现了上面的问题

**Comment by wangjiawei04** [comment]
> > 是在develop分支操作的吗，serve没有要求640*640啊，client是通用的，完全按照文档什么都不改能跑通吗
> 
> 是的，pdserving_client.py是http方式，是可以跑通的。GRPC是我自己写的，出现了上面的问题

问下 服务端是 paddle_serving_server.serve 启动的，客户端是grpc对吧，那前后处理现在是都写在客户端上面是吗。

**Comment by CaRRotOne** [comment]
> > > 是在develop分支操作的吗，serve没有要求640*640啊，client是通用的，完全按照文档什么都不改能跑通吗
> > 
> > 
> > 是的，pdserving_client.py是http方式，是可以跑通的。GRPC是我自己写的，出现了上面的问题
> 
> 问下 服务端是 paddle_serving_server.serve 启动的，客户端是grpc对吧，那前后处理现在是都写在客户端上面是吗。

是的，例子里面的det_rpc_server.py我用的是9092端口，http请求可以，然后我用paddle_serving_server.serve 启动用的是9093端口，前后处理都在客户端。
脚本如下：fetch是从client配置中获取的
```python
seq = Sequential([
    File2Image()
])
image_file = '/PaddleOCR/deploy/test/test.jpg'
img = seq(image_file)
fetch_map = client.predict(feed={"image": img}, fetch=["save_infer_model/scale_0.tmp_0"])
```

**Comment by wangjiawei04** [comment]
> > > > 是在develop分支操作的吗，serve没有要求640*640啊，client是通用的，完全按照文档什么都不改能跑通吗
> > > 
> > > 
> > > 是的，pdserving_client.py是http方式，是可以跑通的。GRPC是我自己写的，出现了上面的问题
> > 
> > 
> > 问下 服务端是 paddle_serving_server.serve 启动的，客户端是grpc对吧，那前后处理现在是都写在客户端上面是吗。
> 
> 是的，例子里面的det_rpc_server.py我用的是9092端口，http请求可以，然后我用paddle_serving_server.serve 启动用的是9093端口，前后处理都在客户端。
> 脚本如下：fetch是从client配置中获取的
> 
> ```python
> seq = Sequential([
>     File2Image()
> ])
> image_file = '/PaddleOCR/deploy/test/test.jpg'
> img = seq(image_file)
> fetch_map = client.predict(feed={"image": img}, fetch=["save_infer_model/scale_0.tmp_0"])
> ```

看起来这个前处理还不够，我看到报错是 1，640，640，3。  这个模型应该是要求 NCHW，也就是 1，3，640，640

**Comment by wangjiawei04** [comment]
也可以大概描述下需求想要以什么形式来启动OCR的serving。

**Comment by CaRRotOne** [comment]
> 也可以大概描述下需求想要以什么形式来启动OCR的serving。

关于部署，我觉得如果能像tf serving那样通过config文件来配置和更新模型，那就更好了。

**Comment by wangjiawei04** [comment]
> > 也可以大概描述下需求想要以什么形式来启动OCR的serving。
> 
> 关于部署，我觉得如果能像tf serving那样通过config文件来配置和更新模型，那就更好了。

https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/pipeline/ocr 可以看看这个呢 这个是0.4.0主推的多模型启动方式，可以参考下

**Comment by CaRRotOne** [comment]
> > > 也可以大概描述下需求想要以什么形式来启动OCR的serving。
> > 
> > 
> > 关于部署，我觉得如果能像tf serving那样通过config文件来配置和更新模型，那就更好了。
> 
> https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/pipeline/ocr 可以看看这个呢 这个是0.4.0主推的多模型启动方式，可以参考下

好的，感谢。grpc请求ocr我还是没有调通,麻烦帮看一下。
脚本如下：
```python
import base64

from paddle_serving_client import Client
from paddle_serving_app.reader import Sequential, File2Image, Resize, ResizeByFactor, DBPostProcess, FilterBoxes
from paddle_serving_app.reader import CenterCrop, RGB2BGR, Transpose, Div, Normalize
import cv2
import numpy as np
import time

def cv2_to_base64(image):
    return base64.b64encode(image).decode('utf8')


client = Client()
client.load_client_config(
    "/PaddleOCR/inference/ch_ppocr_mobile_v1.1_rec_infer/serving_client_dir/serving_client_conf.prototxt")
client.connect(["127.0.0.1:9293"])

read_image_file = File2Image()
preprocess = Sequential(
    [ResizeByFactor(640, 640), Div(255),
     Transpose((2, 0, 1))])
post_func = DBPostProcess(
    {"thresh": 0.3, "box_thresh": 0.5,
     "max_candidates": 1000, "unclip_ratio": 1.5,
     "min_size": 3})
filter_func = FilterBoxes(10, 10)

image_file = '/PaddleOCR/deploy/test/127636685277102080.jpg'
img = read_image_file(image_file)
ori_h, ori_w, _ = img.shape
img = preprocess(img)

_, new_h, new_w = img.shape
ratio_list = [float(new_h) / ori_h, float(new_w) / ori_w]
print(new_h, new_w, ori_h, ori_w)



t = time.time()
outputs = client.predict(feed={"image": img}, fetch=["save_infer_model/scale_0.tmp_0"])
print(time.time() - t)

# 后处理
dt_boxes_list = post_func(outputs["save_infer_model/scale_0.tmp_0"], [ratio_list])
dt_boxes = filter_func(dt_boxes_list[0], [ori_h, ori_w])
```
返回报错如下，看着应该是获取name值的时候，该name下是空的,是因为fetch名字没有正确？fetch我用的是client中的fetchvar name

```shell
[root@eef0f1f4ba2c test]# python3 pdserving_post1.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1228 03:51:06.093747   603 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9293"): added 1
640 640 640 640
Traceback (most recent call last):
  File "pdserving_post1.py", line 41, in <module>
    outputs = client.predict(feed={"image": img}, fetch=["save_infer_model/scale_0.tmp_0"])
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_client/__init__.py", line 350, in predict
    result_map[name].shape = shape
ValueError: cannot reshape array of size 0 into shape (1,1,640,640)
```

**Comment by grasswolfs** [comment]
拉一下最新的代码再试试吧，近期有比较多的易用性更新

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
