### ISSUE TITLE
finetune时配置设置问题

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1577]
在自己数据集微调时，pretrain_weights设置为1.1版本的预训练模型，直接开始训练。和pretrain_weights设置为对应的网络初始模型，如MobileNetV3，然后checkpoint 设置为1.1版本的预训练模型开始训练。二者在效果上有何不同？二者在持续训练到结束和中间中断后重新加载最新的checkpoint继续训练这两种情况下， 有无区别？

**Comment by tink2123** [comment]
加载checkpoint时，会把优化器相关参数加载进去，如果使用了学习率衰减策略，则会恢复到上次中断时的状态。如果只用pretrained_model 则只会加载模型参数。

中断后重新加载参数训练，训练数据会乱掉，对最终精度可能会有影响，且训练精度不易复现，有条件的话建议一步训练，比较稳定。

**Comment by singlebear** [comment]
> 加载checkpoint时，会把优化器相关参数加载进去，如果使用了学习率衰减策略，则会恢复到上次中断时的状态。如果只用pretrained_model 则只会加载模型参数。
> 
> 中断后重新加载参数训练，训练数据会乱掉，对最终精度可能会有影响，且训练精度不易复现，有条件的话建议一步训练，比较稳定。
