### ISSUE TITLE
C++在ubuntu下的资源占用问题

### ISSUE THREAD

**Issue by eyeclosed** [PaddlePaddle/PaddleOCR#1578]
请问下有没有在ubuntu下docker内部编译运行c++版本的资源占用数据
比如CPU/内存/GPU等,
我这边ubuntu16+paddle1.8.5+paddleocr2.0 的内存占用为2.4G,感觉有点偏高了

**Comment by LDOUBLEV** [comment]
感谢反馈，已复现，问题排查中

**Comment by eyeclosed** [comment]
> 感谢反馈，已复现，问题排查中

请问下,有其他版本的资源占用数据吗,
docker内运行的

**Comment by luckywuhan** [comment]
@LDOUBLEV 有进展吗

**Comment by LDOUBLEV** [comment]
已经在跟进了

**Comment by jiangsikai** [comment]
Any progress?

**Comment by jiangsikai** [comment]
@LDOUBLEV  Any progress?
