### ISSUE TITLE
在做ocr识别的时候，有内存泄漏

### ISSUE THREAD

**Issue by rillzhang** [PaddlePaddle/PaddleOCR#1581]
操作系统：centos7
机器配置：显卡3080ti，cpu i5 9代，内存 16G，固态硬盘
paddle版本：2.0.0rc1
cuda版本：11.0

图片是一张手机上随便截的图，180k的jpg图片。图片一开始就读入了，每隔300毫秒循环识别这一张图。显存稳定在6G多一点。内存不断在增加，大概20分钟以后，内存占满，程序挂掉。
还请帮忙解答一下是什么原因，是跟调用方式有关吗？

示例代码如下：
`ocr_engine: paddleocr.PaddleOCR = None
ocr_engine = paddleocr.PaddleOCR()

img = cv.imread('./out.jpg', 1)

while True:
    results = ocr_engine.ocr(img)
    texts = list(map(lambda x: x[1][0], results))
    print("result : ", texts)
    time.sleep(0.3)
`

**Comment by LDOUBLEV** [comment]
问题在rc1预测库上复现存在内存泄漏，问题已经在定位中，在Paddle release/2.0 分支上编译的预测库没有出现内存泄漏，可以先切换预测库版本，后续问题修复后，会在这里更新。

**Comment by rillzhang** [comment]
收到，谢谢

**Comment by LDOUBLEV** [comment]
测试内存泄漏只出现在识别模型上，在cudnn7上没有内存泄漏问题；
另外测试了8.0.5 8.0.4 cudnn都泄露，换成了8.0.3没有出现内存泄漏；周知

**Comment by rillzhang** [comment]
我这边用cudn8.0.3没有效果，还是泄漏

**Comment by Nagisakurumi** [comment]
![2R{_(``75P28Z(8_{698X8V](https://user-images.githubusercontent.com/18586645/103335374-b1f09b80-4aaf-11eb-860d-04ca48ab7de8.png)

**Comment by Nagisakurumi** [comment]
![2R{_(``75P28Z(8_{698X8V](https://user-images.githubusercontent.com/18586645/103335419-d482b480-4aaf-11eb-937f-80ca317a77ad.png)

**Comment by Nagisakurumi** [comment]
测试了一下 还是不行 用的cudnn8.0.3 

(ocr) [root@localhost cuda]# ls
include  lib64  NVIDIA_SLA_cuDNN_Support.txt
(ocr) [root@localhost cuda]# cd lib64/
(ocr) [root@localhost lib64]# ls
libcudnn_adv_infer.so        libcudnn_cnn_infer.so.8.0.3  libcudnn_ops_train.so.8
libcudnn_adv_infer.so.8      libcudnn_cnn_train.so        libcudnn_ops_train.so.8.0.3
libcudnn_adv_infer.so.8.0.3  libcudnn_cnn_train.so.8      libcudnn.so
libcudnn_adv_train.so        libcudnn_cnn_train.so.8.0.3  libcudnn.so.8
libcudnn_adv_train.so.8      libcudnn_ops_infer.so        libcudnn.so.8.0.3
libcudnn_adv_train.so.8.0.3  libcudnn_ops_infer.so.8      libcudnn_static.a
libcudnn_cnn_infer.so        libcudnn_ops_infer.so.8.0.3
libcudnn_cnn_infer.so.8      libcudnn_ops_train.so



nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

**Comment by jiweibo** [comment]
请使用gperftools查一下，目前cudnn8存在性能和内存泄露问题

**Comment by rillzhang** [comment]
> 问题在rc1预测库上复现存在内存泄漏，问题已经在定位中，在Paddle release/2.0 分支上编译的预测库没有出现内存泄漏，可以先切换预测库版本，后续问题修复后，会在这里更新。

想问一下最新的paddle2.0正式版本修复了内存泄漏的问题了吗？

**Comment by wxz7801** [comment]
> > 问题在rc1预测库上复现存在内存泄漏，问题已经在定位中，在Paddle release/2.0 分支上编译的预测库没有出现内存泄漏，可以先切换预测库版本，后续问题修复后，会在这里更新。
> 
> 想问一下最新的paddle2.0正式版本修复了内存泄漏的问题了吗？

cuda11.2+cudnn8.1.0,paddlepaddle2.0正式版跑生产代码,之前确认过存在内存泄漏问题，更新paddlepaddle2.0后未见内存泄漏。

**Comment by MissPenguin** [comment]
内存泄漏问题已修复，欢迎拉取最新代码尝试，如果仍有问题可以重新提issue，我们继续跟进～

**Comment by sunjinguo** [comment]
目前在使用也遇到内存持续上涨至程序被kill,paddleocr 版本2.6.1.3，paddlepaddle版本为：2.3.0  ，CPU推理，开始内存会稳定在7G，会慢慢上涨，还有个疑问，是内存至少也得8G吗？为啥占那么多
