### ISSUE TITLE
如何可视化acc,loss曲线图,模型网络结构图等? 

### ISSUE THREAD

**Issue by xiaotongtong9293** [PaddlePaddle/PaddleOCR#1585]
你好,我想看训练过程中acc,loss等曲线图以及可视化模型网络结构等,请问怎么能把log文件可视化呢?  
我看有个VisualDL ,是用这个么?  没太懂~

**Comment by WenmuZhou** [comment]
将[这](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/rec_mv3_none_bilstm_ctc.yml#L15)设置为true,训练后在终端里输入  visualdl --logdir your_path ，之后会输出可查看的网址，具体命令参考[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/03_VisualDL/visualdl.html)

**Comment by xiaotongtong9293** [comment]
> 将 [这里](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/rec_mv3_none_bilstm_ctc.yml#L15) 设置为true,训练后在终端里输入 visualdl --logdir your_path ，之后会输出可查看的网址，具体命令参考 [这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/03_VisualDL/visualdl.html)
好的谢谢,看到了,这是识别的.    那请问文本定位的训练过程有相关设置么? 能输出lr,loss等变化么? 没有看到呢...

**Comment by WenmuZhou** [comment]
文本检测的配置是一样的
