### ISSUE TITLE
 hub install deploy/hubserving/ocr_system/  启动报错

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#1589]
目前我 使用的是docker 拉取的环境  cuda10  linux   gpu环境    

paddlepaddle-gpu==2.0.0b1 

在执行  hub install deploy/hubserving/ocr_system/ 

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/usr/local/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/usr/local/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/module.py", line 146, in __init__
    self._initialize(**kwargs)
  File "deploy/hubserving/ocr_system/module.py", line 52, in _initialize
    self.text_sys = TextSystem(cfg)
  File "./tools/infer/predict_system.py", line 40, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "./tools/infer/predict_rec.py", line 51, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "./tools/infer/utility.py", line 139, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareExecutor()
4   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
5   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
6   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
7   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, paddle::framework::AttributeMap, bool)
8   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
Error: Operator rnn has not been registered
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:140)

报这个错   然后我看有人之前提了issue里面和我提了一样的问题    

我就重新安装paddlepaddle-gpu 到2.0.0c1 的版本  

结果遇到了和 issue 1106 一样的问题   
importerror  ：/usr/lib/x86_64-linux-gpu/libstdc++ version 'CXXABI_1.3.11'  not found 

上面让我升级 paddlepaddle-gpu  到 2.0.0b1   感觉死循环了    升级到哪个版本都有问题  请问到底应该升级到哪个版本

**Comment by tink2123** [comment]
2.0.0c1 是目前推荐的版本
>使用的是docker 拉取的环境 cuda10 linux gpu环境

请问是拉取的这个docker吗？
`sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash`

**Comment by wa3926** [comment]
@tink2123  我看 gitee 上是 cuda10.0-cudnn7 这个版本 请问有区别吗    之前clone gethub 太慢就按照 gitee上来了

**Comment by tink2123** [comment]
paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82  提供的是高gcc版本的docker，适配paddle2.0rc1，建议还是按照上面的命令拉取。

gitee上的内容可能更新不够及时

**Comment by wa3926** [comment]
谢谢
