### ISSUE TITLE
关于表盘数据集标注

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#159]
数据集是电表有液晶屏和机械字轮表类型，只识别其中的数字信息，如果想识别一张图片固定区域的数字，对于数据集来说需要用目标检测的方法框选对应区域，还是用语义分割的方式框选对应区域，应该如何标注比较好一些

**Comment by LDOUBLEV** [comment]
用检测的方法就可以，把整行文本用检测框标注出来

**Comment by Sunyingbin** [comment]
好的，谢谢
