### ISSUE TITLE
Can't inference, the same error when I try "python PPOCRLabel.py  --lang ch"

### ISSUE THREAD

**Issue by hjctop1** [PaddlePaddle/PaddleOCR#1591]
Pls see the error thx.

ubuntu@ubuntu-Super-Server:~/PaddleOCR$ python -c "import paddle; print(paddle.__version__)"
2.0.0-rc0
ubuntu@ubuntu-Super-Server:~/PaddleOCR$ ls
configs  doc        __init__.py  MANIFEST.in   ppocr       __pycache__   README.md         setup.py   tools
deploy   inference  LICENSE      paddleocr.py  PPOCRLabel  README_ch.md  requirements.txt  StyleText  train.sh
ubuntu@ubuntu-Super-Server:~/PaddleOCR$ python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 144, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 42, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "/home/ubuntu/PaddleOCR/tools/infer/predict_rec.py", line 51, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/home/ubuntu/PaddleOCR/tools/infer/utility.py", line 135, in create_predictor
    predictor = inference.create_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareExecutor()
4   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
5   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
6   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
7   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, paddle::framework::AttributeMap, bool)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator (rnn) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:151)

**Comment by tink2123** [comment]
> ubuntu@ubuntu-Super-Server:/PaddleOCR$ python -c "import paddle; print(paddle.version)"
> 2.0.0-rc0

Please install PaddlePaddle 2.0rc1
```
# If you have cuda9 or cuda10 installed on your machine, please run the following command to install
python3 -m pip install paddlepaddle-gpu==2.0rc1 -i https://mirror.baidu.com/pypi/simple

# If you only have cpu on your machine, please run the following command to install
python3 -m pip install paddlepaddle==2.0rc1 -i https://mirror.baidu.com/pypi/simple
```

**Comment by hjctop1** [comment]
Fixed. Thx. @tink2123
