### ISSUE TITLE
ImportError: cannot import name 'inference' from 'paddle' 

### ISSUE THREAD

**Issue by wwwanghao** [PaddlePaddle/PaddleOCR#1592]
when start PPOCRLabel with python3 PPOCRLabel.py --lang ch, meet above error,  any suggestion to solve it?
os: Mac
paddle: paddlepaddle==2.0.0b0
install it follow:https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md

**Comment by airesgit** [comment]
新安装的好像都有这个问题

**Comment by WenmuZhou** [comment]
rc1版本

**Comment by hg791603457** [comment]
楼上正解，已解决，需要使用rc1版本
