### ISSUE TITLE
(interrupted by signal 9: SIGKILL) error in detection (2.0.0rc1)

### ISSUE THREAD

**Issue by Ru-Van** [PaddlePaddle/PaddleOCR#1593]
Hi, 
after the update, the detection stopped working.
When i used ver.(PaddlePaddle==1.8.5, paddleocr==1.1.1)
`ocr = PaddleOCR(use_angle_cls=False, use_gpu=False)`
`result = ocr.ocr(img, rec=False, det=True, cls=False)` 
This script work good on cpu. 
But, when i update paddle (PaddlePaddle==2.0.0rc1, paddleocr==2.0.2), code at the top doesn't work on the same data. 
**Process finished with exit code 137 (interrupted by signal 9: SIGKILL)**
Image for the test in the attachment
![0_1](https://user-images.githubusercontent.com/27008727/103204822-3ce36180-4909-11eb-9439-c0cc941fcc0e.png)

**Comment by LDOUBLEV** [comment]
Hi, please checkout to dygraph branch of PaddleOCR if you using Paddle2.0rc1, refer to https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/whl_en.md.
```
git clone https://github.com/PaddlePaddle/PaddleOCR
git branch -a 
git checkout dygraph   # dygraph branch  
git checkout develop # static branch 
```
