### ISSUE TITLE
在无网络环境下，hub install和serving都会直接hang住

### ISSUE THREAD

**Issue by andrewleo** [PaddlePaddle/PaddleOCR#1595]

**Comment by andrewleo** [comment]
我已经在一个有网络的地方hub install并serving启动过，且能运行
然后我重启服务，重新hub serving，就直接hang住了。求问如果离线使用？

**Comment by andrewleo** [comment]
hub version也会hang住很久。。

**Comment by littletomatodonkey** [comment]
指定地址为127.0.0.1试下呢？

**Comment by andrewleo** [comment]
如何指定地址，加什么参数？

**Comment by grasswolfs** [comment]
不应该的，是可以离线使用的，有任何报错信息么？
在有网环境下启动服务成功后，断网直接启动，但不要移动任何文件目录，要不然找不到默认目录文件也无法运行

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by MacTian** [comment]
解决了没？怎么解决的

**Comment by andrewleo** [comment]
> 解决了没？怎么解决的

里面有几个海外的域名，请求一直hang住，我加了个host先临时解决了，报错也没关系
