### ISSUE TITLE
无法单机多卡训练

### ISSUE THREAD

**Issue by dengrui-64** [PaddlePaddle/PaddleOCR#1598]
问题描述

```
export CUDA_VISIBLE_DEVICES=0,1 && python3.7 tools/train.py  -c configs/det/det_r50_vd_sast_icdar15.yml
```
未运行train.py时，两张卡显存占用均为1MiB
![image](https://user-images.githubusercontent.com/53159801/103254907-3a910e00-49c2-11eb-8488-e1d89077df6c.png)

运行时，仅调用了卡1，卡2的显存一直在12MiB
![image](https://user-images.githubusercontent.com/53159801/103255046-b55a2900-49c2-11eb-9e2c-7bbc2f0cc2ee.png)

系统环境：
Ubuntu16.04 
1080ti显卡
cuda10.2
版本：官方镜像paddlepaddle/paddle:2.0.0rc0-gpu-cuda10.1-cudnn7下的python3.7

镜像内环境检查
![image](https://user-images.githubusercontent.com/53159801/103255106-010cd280-49c3-11eb-84ab-6dab4e35a192.png)

**Comment by dengrui-64** [comment]
```
export CUDA_VISIBLE_DEVICES=0,1 && python3.7 tools/train.py  -c configs/det/det_r50_vd_sast_icdar15.yml
```
训练日志，
![image](https://user-images.githubusercontent.com/53159801/103255174-44674100-49c3-11eb-8666-dc768904d219.png)

**Comment by mingo-doer** [comment]
请问，这个问题是怎么解决了呢
