### ISSUE TITLE
使用EAST+RART失败

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#160]
本地window环境下，运行python predict_system.py， det 使用的east，rec使用CRNN，成功检测并识别。
但是使用EAST+RATE失败。
下载的是：
rec_r34_vd_tps_bilstm_ctc
然后自己export出inference模型。
按照路径进行配置
![1](https://user-images.githubusercontent.com/6395366/84109841-2dc4c100-aa56-11ea-85c6-928cf57b6e75.jpg)

**Comment by SixGodGG** [comment]
![1](https://user-images.githubusercontent.com/6395366/84109801-0c63d500-aa56-11ea-9de3-62e192981a02.jpg)

**Comment by SixGodGG** [comment]
![2](https://user-images.githubusercontent.com/6395366/84109861-3b7a4680-aa56-11ea-9d01-2e4c0a9ed70e.jpg)

**Comment by SixGodGG** [comment]
改成： parser.add_argument("--rec_algorithm", type=str, default='STAR-Net')  也不对啊

**Comment by tink2123** [comment]
请提供一下完整的报错信息

**Comment by tink2123** [comment]
如果识别使用了带tps的RARE模型，请参考文档说明修改参数
<img width="950" alt="图片" src="https://user-images.githubusercontent.com/31891223/84112528-8480c980-aa5b-11ea-9d36-49b23f6fa38d.png">

**Comment by SixGodGG** [comment]
![3](https://user-images.githubusercontent.com/6395366/84113067-7a12ff80-aa5c-11ea-9042-363e3549897a.jpg)

**Comment by tink2123** [comment]
请参考文档修改预测命令，另外您的代码好像不是最新版本，可以更新下代码，报错信息会更友好

**Comment by SixGodGG** [comment]
是新程序啊  我重新clone了一份，单独rec 是对的，但是使用predict_system.py  不太对啊
![4](https://user-images.githubusercontent.com/6395366/84116500-8dc16480-aa62-11ea-8586-07adf0227996.jpg)
单独rec 成功，模型是rec_r34_vd_tps_bilstm_ctc

**Comment by tink2123** [comment]
使用predict_system.py 也要对应修改上面的几个参数 --rec_image_shape=“3,32,100” --rec_char_type="en" --rec_algorithm=“RARE”

这里的说明文档我们完善一下

**Comment by SixGodGG** [comment]
报错还是一样，运行命令如下：
python E:/GitHub/PaddleOCR/tools/infer/predict_system.py --image_dir="E:/GitHub/PaddleOCR/doc/imgs_en/img_195.jpg" --det_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference/det/"  --rec_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/rec_r34_vd_tps_bilstm_ctc/" --rec_image_shape="3, 32, 100" --rec_char_type="ch" --use_gpu="false" --rec_algorithm="RARE" 

另外无论使用--rec_algorithm="RARE"   还是 --rec_algorithm="STAR-Net"   还是--rec_algorithm="STARNet"  报错都是一样的，上面贴图了，报错。

**Comment by SixGodGG** [comment]
另外我这都是基于ctc损失的识别模型，不是attention。

**Comment by tink2123** [comment]
报错应该是tps不支持变长输入导致的，本质都是要修改默认输入值为“3,32,100” 字符类型为“en”。修改这两个参数后应该不会再报错了，如果还有问题可在这个PR下贴完整报错信息

**Comment by SixGodGG** [comment]
STAR-Net 算法居然需要这样设置： --rec_algorithm="CRNN"  为什么！？？

以下这样运行就ok了。
python E:/GitHub/PaddleOCR/tools/infer/predict_system.py --image_dir="E:/GitHub/PaddleOCR/doc/imgs_en/img_10.jpg" --det_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference/det/" --det_algorithm="EAST" --rec_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/rec_r34_vd_tps_bilstm_ctc/" --rec_image_shape="3, 32, 100" --rec_char_type="en" --use_gpu="false"

**Comment by SixGodGG** [comment]
@tink2123 能解释一下 为什么STAR-Net  算法需要使用 --rec_algorithm="CRNN"  啊？

**Comment by tink2123** [comment]
> 为什么STAR-Net 算法需要使用 --rec_algorithm="CRNN" 啊？

你设置STAR报错吗？设置CRNN不会报错是因为这两个算法都是使用ctc_loss

**Comment by SixGodGG** [comment]
> > 为什么STAR-Net 算法需要使用 --rec_algorithm="CRNN" 啊？
> 
> 你设置STAR报错吗？设置CRNN不会报错是因为这两个算法都是使用ctc_loss

对。上面说过了。
![5](https://user-images.githubusercontent.com/6395366/84130402-d0406c80-aa75-11ea-8942-686d4e688e71.jpg)


那我可以这样理解，只要是ctc的，都设置成--rec_algorithm="CRNN"  只要是 attention的，都设置成：--rec_algorithm="RARE"

**Comment by dlml** [comment]
tps 如果输入尺寸比100大，比如600，训练会不收敛，这种问题怎么解决？
