### ISSUE TITLE
ERROR:2.0.0-rc1-gpu-cuda10-cudnn7-mkl_paddlepaddle_gpu-2.0.0rc1.post100-cp36-cp36m-linux_x86_64.whl is not a supported  wheel on  this platform

### ISSUE THREAD

**Issue by wanlipeng** [PaddlePaddle/PaddleOCR#1600]
你好,问下,我个人linus平台环境python3.6.6, cuda 10.0.130, cudnn7.6.5,在官网下的pip whl安装包,就是按照这个平台下载的为啥会报错呢,StytleText在本地paddle1.8.5不能跑,有遇到同样的问题吗,求教?

**Comment by WenmuZhou** [comment]
重命名为paddlepaddle_gpu-2.0.0rc1.post100-cp36-cp36m-linux_x86_64.whl

**Comment by wanlipeng** [comment]
好的,可以啦,感谢!!
