### ISSUE TITLE
使用配置文件启动GPU服务出现Lack of necessary parameters!

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleOCR#1601]
{
    "modules_info": {
        "ocr_system": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": true
            },
            "predict_args": {
            }
        }
    },
    "port": 8868,
    "use_multiprocess": false,
    "workers": 2
}

**Comment by LDOUBLEV** [comment]
配置文件和启动命令是？

**Comment by Mashiro-JY** [comment]
> 配置文件和启动命令是？

配置文件就是按照文档的json写的
{
"modules_info": {
"ocr_system": {
"init_args": {
"version": "1.0.0",
"use_gpu": true
},
"predict_args": {
}
}
},
"port": 8868,
"use_multiprocess": false,
"workers": 2
}
启动命令是
export CUDA_VISIBLE_DEVICES=3
hub serving start -c deploy/hubserving/ocr_system/config.json

**Comment by grasswolfs** [comment]
都拉一下最新的包吧，应该就可以解决

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
