### ISSUE TITLE
Style-Text 文本读取编码异常

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1602]
![image](https://user-images.githubusercontent.com/48552037/103263949-3249ca80-49e4-11eb-8e78-b8d74d517c92.png)

**Comment by LDOUBLEV** [comment]
你的文本中是什么字符呢？中文字符还是其他语言字符？

**Comment by singlebear** [comment]
> 你的文本中是什么字符呢？中文字符还是其他语言字符？

英文，解决方法是style_samplers.py的读取文本文件的部分指定打开编码格式。
