### ISSUE TITLE
运行python3 tools/synth_image.py -c configs/config.yml --style_image examples/style_images/2.jpg --text_corpus PaddleOCR --language en 时出现错误！！！

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1603]
Traceback (most recent call last):
  File "tools/synth_image.py", line 82, in <module>
    synth_image()
  File "tools/synth_image.py", line 29, in synth_image
    image_synthesiser = ImageSynthesiser()
  File "/home/hs/PycharmProjects/PaddleOCR-dygraph/StyleText/engine/synthesisers.py", line 32, in __init__
    self.text_drawer = text_drawers.StdTextDrawer(self.config)
  File "/home/hs/PycharmProjects/PaddleOCR-dygraph/StyleText/engine/text_drawers.py", line 13, in __init__
    self.load_fonts(config["TextDrawer"]["fonts"])
  File "/home/hs/PycharmProjects/PaddleOCR-dygraph/StyleText/engine/text_drawers.py", line 19, in load_fonts
    font_height = self.get_valid_height(font_path)
  File "/home/hs/PycharmProjects/PaddleOCR-dygraph/StyleText/engine/text_drawers.py", line 25, in get_valid_height
    _, font_height = font.getsize(self.char_list)
  File "/home/hs/anaconda3/envs/OCR_Paddle/lib/python3.7/site-packages/PIL/ImageFont.py", line 414, in getsize
    size, offset = self.font.getsize(text, "L", direction, features, language)
OSError: invalid face handle

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1609224242 (unix time) try "date -d @1609224242" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 12494 (TID 0x7fca7e011740) from PID 0 ***]

段错误 (核心已转储)

**Comment by weisy11** [comment]
无法复现，能否提供更详细的信息？例如：操作系统及版本，python版本，paddle版本，Pillow版本。如果有其他可能导致bug的原因也可以提供一下，谢谢。

**Comment by weisy11** [comment]
根据https://github.com/python-pillow/Pillow/issues/3066 libraqm库可能会导致这个问题。如果您安装了libraqm，可以尝试移除这个库，或新建一个干净的虚拟环境来尝试解决。

**Comment by hsyy673150343** [comment]
ubuntu 18.04
python 3.7 
Pillow  8.0.1
paddlepaddle       2.0.0rc1
paddlepaddle-gpu   2.0.0b0
我是用自己笔记本电脑配置的环境

**Comment by LDOUBLEV** [comment]
可能是Pillow版本 和raqm库的问题，建议重新安装pillow或者libraqm

**Comment by hsyy673150343** [comment]
> 无法复现，能否提供更详细的信息？例如：操作系统及版本，python版本，paddle版本，Pillow版本。如果有其他可能导致bug的原因也可以提供一下，谢谢。

**Comment by hsyy673150343** [comment]
> 无法复现，能否提供更详细的信息？例如：操作系统及版本，python版本，paddle版本，Pillow版本。如果有其他可能导致bug的原因也可以提供一下，谢谢。

ubuntu 18.04
python 3.7
Pillow 8.0.1
paddlepaddle 2.0.0rc1
paddlepaddle-gpu 2.0.0b0
我是用自己笔记本电脑配置的环境

**Comment by hsyy673150343** [comment]
> 根据[python-pillow/Pillow#3066](https://github.com/python-pillow/Pillow/issues/3066) libraqm库可能会导致这个问题。如果您安装了libraqm，可以尝试移除这个库，或新建一个干净的虚拟环境来尝试解决。

Package            Version
------------------ -------------------
appdirs            1.4.4
astor              0.8.1
Babel              2.9.0
bce-python-sdk     0.8.53
certifi            2020.12.5
cfgv               3.2.0
chardet            4.0.0
click              7.1.2
cycler             0.10.0
decorator          4.4.2
distlib            0.3.1
filelock           3.0.12
flake8             3.8.4
Flask              1.1.2
Flask-Babel        2.0.0
future             0.18.2
gast               0.3.3
glibc              0.6.1
graphviz           0.16
identify           1.5.10
idna               2.10
imageio            2.9.0
imgaug             0.4.0
importlib-metadata 3.3.0
itsdangerous       1.1.0
Jinja2             2.11.2
joblib             1.0.0
kiwisolver         1.3.1
lmdb               1.0.0
MarkupSafe         1.1.1
matplotlib         3.2.1
mccabe             0.6.1
netifaces          0.10.9
networkx           2.5
nltk               3.5
nodeenv            1.5.0
numpy              1.19.4
objgraph           3.5.0
opencv-python      4.2.0.32
paddlepaddle       2.0.0rc1
paddlepaddle-gpu   2.0.0b0
pathlib            1.0.1
Pillow             8.0.1
pip                20.3.3
pre-commit         2.9.3
prettytable        2.0.0
protobuf           3.14.0
psutil             5.8.0
pyclipper          1.2.1
pycodestyle        2.6.0
pycryptodome       3.9.9
pyflakes           2.2.0
pyparsing          2.4.7
PyQt5              5.15.2
PyQt5-sip          12.8.1
python-dateutil    2.8.1
python-Levenshtein 0.12.0
pytz               2020.5
PyWavelets         1.1.1
PyYAML             5.3.1
rarfile            4.0
regex              2020.11.13
requests           2.25.1
scikit-image       0.18.1
scipy              1.5.4
setuptools         51.0.0.post20201207
Shapely            1.7.1
six                1.15.0
tifffile           2020.12.8
toml               0.10.2
tqdm               4.55.0
trash-cli          0.20.12.26
typing-extensions  3.7.4.3
urllib3            1.26.2
virtualenv         20.2.2
visualdl           2.0.5
wcwidth            0.2.5
Werkzeug           1.0.1
wheel              0.36.2
zipp               3.4.0

这是虚拟环境里面的包，没有安装您说的libraqm

**Comment by weisy11** [comment]
https://github.com/python-pillow/Pillow/issues/3066#issuecomment-691506185
