### ISSUE TITLE
如何操作可以不加载文本定位的预训练模型  直接从头进行训练呢?

### ISSUE THREAD

**Issue by xiaotongtong9293** [PaddlePaddle/PaddleOCR#1606]
请问,如果不用文本定位的预训练模型, 从头训练自己的数据集, db的yml文件中pretrain_weights: 的路径是空着不写嘛?      但是空着不写程序运行不起来,会报错.      应该是如何操作的呢?
谢谢!!!!!

**Comment by WenmuZhou** [comment]
空着报啥错，理论上空着就行了

**Comment by xiaotongtong9293** [comment]
> 空着报啥错，理论上空着就行了

谢谢,找到问题了!   是可以的
