### ISSUE TITLE
Win10系统，VS2019 编译的ocr_system 执行出错

### ISSUE THREAD

**Issue by farmer21cn** [PaddlePaddle/PaddleOCR#1607]
D:\PaddlePaddleOCR2019\PaddleOCR-dygraph\deploy\cpp_infer\out\build\x64-Release>ocr_system config.txt aa.jpg
Config config(argv[1]);=======Paddle OCR inference config======
char_list_file : D:/PaddlePaddleOCR/PaddleOCR-dygraph/ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : D:/PaddlePaddleOCR/PaddleOCR-dygraph/deploy/cpp_infer/output/Release/inference/ch_ppocr_mobile_v2.0_cls_infer
cls_thresh : 0.9
cpu_math_library_num_threads : 0
det_db_box_thresh : 0.3
det_db_thresh : 0.3
det_db_unclip_ratio : 0.8
det_model_dir : D:/PaddlePaddleOCR/PaddleOCR-dygraph/deploy/cpp_infer/output/Release/inference/ch_ppocr_server_v2.0_det_infer
gpu_id : 0
gpu_mem : 4000
max_side_len : 200
rec_model_dir : D:/PaddlePaddleOCR/PaddleOCR-dygraph/deploy/cpp_infer/output/Release/inference/ch_ppocr_server_v2.0_rec_infer
use_angle_cls : 0
use_gpu : 0
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
cv::Mat srcimg
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
DBDetector det
cls = new Classifier
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Operator rnn has not been registered
  [Hint: op_info_ptr should not be null.] (at D:\2.0.0-beta0\paddle\paddle/fluid/framework/op_info.h:140)

**Comment by farmer21cn** [comment]
fluid_inference_install_dir2.0.0-beta0版本、ch_ppocr_mobile_v2.0_cls_infer、ch_ppocr_server_v2.0_det_infer、ch_ppocr_server_v2.0_rec_infer、PaddleOCR-dygraph最新版本

**Comment by WenmuZhou** [comment]
预测库需要从源码编译

**Comment by farmer21cn** [comment]
> 预测库需要从源码编译

谢谢，按照你的提示，处理成功。
