### ISSUE TITLE
能否详细介绍下Style-Text配置文件内参数作用？

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1608]
想自己调参的时候问题比较大，而且希望可支持更大的图片高，32对于真实场景还是太小了。还有Style-Text如何不文字风格迁移，就像普通文本生成程序一样默认字体直接输出到分割的背景图？

**Comment by weisy11** [comment]
使用image_synth模式会输出fake_bg.jpg，即为背景图。如果想要批量提取背景，可以稍微修改一下代码，将fake_bg保存下来即可

**Comment by weisy11** [comment]
关于图片尺寸：StyleText合成的数据主要针对 OCR识别模型，而非检测、分割等模型，尺寸主要参考目前PaddleOCR中的识别模型。在训练阶段我们没有采用多尺度的数据，因此直接在配置文件中修改尺寸效果不佳。
最近也收到一些反馈，觉得这个尺寸不合适。因此我们也想了解一下，您的识别模型输入尺寸是多少？如果我们提供一个支持更大尺寸的模型，多大可以满足需求？

**Comment by singlebear** [comment]
> 关于图片尺寸：StyleText合成的数据主要针对 OCR识别模型，而非检测、分割等模型，尺寸主要参考目前PaddleOCR中的识别模型。在训练阶段我们没有采用多尺度的数据，因此直接在配置文件中修改尺寸效果不佳。
> 最近也收到一些反馈，觉得这个尺寸不合适。我们也想了解一下，您的识别模型输入尺寸是多少？如果我们提供一个支持更大尺寸的模型，多大可以满足需求？
> 关于配置文件：目前第一版的配置文件说明确实不够详细，主要也是因为一些配置目前还不能随意调整。除了尺寸外，如果还有哪些默认配置不能满足需求也请您说明，我们后续的版本会进一步优化。

        我这边主要是用在英文的数据生成。尺寸过小导致效果差的主要原因是需检测的背景与字体颜色十分相近，且字体类似于笔画带内外边缘、边缘间部分带填充条纹或点的艺术字，还是笔画较为膨胀的那种，没有匹配的字体直接生成仿真数据。实际采样图像压缩至32高后，如A8BE等带中心空白位置的字会直接胡成一团，不但字看不清，迁移的字体形状也有较大误差。对我这边的应用来说，如果高能扩大到64，字体纹路特征就能勉强清晰。但考虑到其他人的应用，特别是中文艺术字体，我觉得可能96就够完整显示出字体的特征，这点可以看看其他人的需求情况。
        配置部分。我想要调整的主要有几个部分，第一个就是字体与迁移的风格字体的相似度。比如0~1,0的话直接输入原始字体的样式，越接近1越像风格图片的字体。需要这点的主要原因是想通过人工的调整，来输出更符合人类感官上相似的字形，有时候偏移的字形过于夸张反而失真。目前试着调整Predictor下面的std和mean的值，那个字直接不是字了。第二个是想有调整影响背景图分割的阈值。原因主要是我的字与背景本身很相近，目前经常出现背景图依旧带着字的一部分的问题，这样生成的图片肯定有问题。如果能通过一个阈值控制背景提取的强度，哪怕牺牲使得背景图糊一点，只要能把原本的字体特征给滤掉都可以接受。

**Comment by weisy11** [comment]
> > 关于图片尺寸：StyleText合成的数据主要针对 OCR识别模型，而非检测、分割等模型，尺寸主要参考目前PaddleOCR中的识别模型。在训练阶段我们没有采用多尺度的数据，因此直接在配置文件中修改尺寸效果不佳。
> > 最近也收到一些反馈，觉得这个尺寸不合适。我们也想了解一下，您的识别模型输入尺寸是多少？如果我们提供一个支持更大尺寸的模型，多大可以满足需求？
> > 关于配置文件：目前第一版的配置文件说明确实不够详细，主要也是因为一些配置目前还不能随意调整。除了尺寸外，如果还有哪些默认配置不能满足需求也请您说明，我们后续的版本会进一步优化。
> 
> ```
>     我这边主要是用在英文的数据生成。尺寸过小导致效果差的主要原因是需检测的背景与字体颜色十分相近，且字体类似于笔画带内外边缘、边缘间部分带填充条纹或点的艺术字，还是笔画较为膨胀的那种，没有匹配的字体直接生成仿真数据。实际采样图像压缩至32高后，如A8BE等带中心空白位置的字会直接胡成一团，不但字看不清，迁移的字体形状也有较大误差。对我这边的应用来说，如果高能扩大到64，字体纹路特征就能勉强清晰。但考虑到其他人的应用，特别是中文艺术字体，我觉得可能96就够完整显示出字体的特征，这点可以看看其他人的需求情况。
>     配置部分。我想要调整的主要有几个部分，第一个就是字体与迁移的风格字体的相似度。比如0~1,0的话直接输入原始字体的样式，越接近1越像风格图片的字体。需要这点的主要原因是想通过人工的调整，来输出更符合人类感官上相似的字形，有时候偏移的字形过于夸张反而失真。目前试着调整Predictor下面的std和mean的值，那个字直接不是字了。第二个是想有调整影响背景图分割的阈值。原因主要是我的字与背景本身很相近，目前经常出现背景图依旧带着字的一部分的问题，这样生成的图片肯定有问题。如果能通过一个阈值控制背景提取的强度，哪怕牺牲使得背景图糊一点，只要能把原本的字体特征给滤掉都可以接受。
> ```

谢谢您的建议。兼容不同大小的图像我们会尽快做出来。可调节尺度的style和背景这个想法很好，我们会试试看效果怎么样。关于提取的背景有残留文字，目前看文字模糊，边距较小等情况都会导致这个问题的发生，是我们下版本主要改进和解决的问题。

**Comment by wanlipeng** [comment]
我这边也测试过styleText的效果,使用自己图片,存在1.抽取来背景图保留style_img上面的文字;2.新合成的图中写入文字如果长一点10个字符左右就存在字不清楚啦,其实感觉如果从单纯做数据角度考虑的话**,抽取更干净,和style_img更相似的背景图是刚需吧**,,尺寸大小可以resize,不同字体也可以自己合成写上去的,个人之见,背景图抽取如果能优化下,解决一大需求啊

**Comment by chocolate-byte** [comment]
文字风格迁移感觉希望增加开关的功能，还有字体自己更换的功能，小数点等符号目前还不能生成
