### ISSUE TITLE
同一张图片，通过页面上的功能演示，上传图片、显示识别结果，和项目里源代码预测出的结果不一样呢？页面上的功能演示效果要好很多

### ISSUE THREAD

**Issue by sundyll** [PaddlePaddle/PaddleOCR#1609]

**Comment by LDOUBLEV** [comment]
模型不一样吧，用的模型分别是？

**Comment by 4ft35t** [comment]
我也发现同样的问题，不通模型检测结果有差异，和线上不一样。

原图

![image](https://user-images.githubusercontent.com/2051049/105444077-27fbb300-5ca8-11eb-8eb9-da21ad30979e.png)
中英文超轻量OCR模型
`+861069096584443500, 0.984`
![image](https://user-images.githubusercontent.com/2051049/105444159-4a8dcc00-5ca8-11eb-805e-bb5dec23854c.png)

中英文通用OCR模型
```
+8610690, 0.998
6584443500, 0.998
```

![1611129230904](https://user-images.githubusercontent.com/2051049/105444456-d69ff380-5ca8-11eb-9602-850047f835bc.jpg)

线上结果
```
          "text": "+861069096584443500",
          "confidence": 0.9961311221122742
```
---
本以为用通用模型效果更好，实际这个场景下轻量效果更好。
用通用模型有啥参数调整能达到轻量的效果？

**Comment by WenmuZhou** [comment]
调整后处理里的thresh，调低看看
