### ISSUE TITLE
预测出错，在rec_postprocess.py中

### ISSUE THREAD

**Issue by Nestart** [PaddlePaddle/PaddleOCR#1611]
您好，首先谢谢您的开源。我在利用项目进行文本预测时，发现总是对部分数据出现索引超列表的问题，经过自己的探索，发现问题出现在rec_postprocess.py中.在decode函数里，int(text_index[batch_idx][idx])恰好超出索引范围一个值，请问这个是什么原因呢？

**Comment by Nestart** [comment]
![Screenshot from 2020-12-29 22-41-54](https://user-images.githubusercontent.com/34918269/103291626-292e1d00-4a27-11eb-9911-b8231287e034.png)

**Comment by Nestart** [comment]
您好，我通过判断，跳过逻辑让运行没有问题了，但是还是奇怪为什么不同数据会出现这个情况

**Comment by LDOUBLEV** [comment]
你使用的字典中字的数量 少于 要分类的识别字的数量

**Comment by Nestart** [comment]
> 
> 
> 你使用的字典中字的数量 少于 能识别字的数量

好的，谢谢您
