### ISSUE TITLE
Out of memory error on GPU 0 gitee上拉的paddle2.0rc1 代码

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#1612]
export CUDA_VISIBLE_DEVICES=0
 export FLAGS_allocator_strategy=auto_growth
 hub serving start -c deploy/hubserving/ocr_system/config.json   

Out of memory error on GPU 0. Cannot allocate 92.031494MB memory on GPU 0, available memory is only 23.437500MB.
我按照其他issue 里面  改默认值500 以及环境变量 并没有用  请问下 是gitee 上代码不全吗
parser.add_argument("--gpu_mem", type=int, default=8000) 
设置环境变量：export FLAGS_allocator_strategy=auto_growth 或者 export FLAGS_fraction_of_gpu_memory_to_use=0.
我

**Comment by LDOUBLEV** [comment]
是你的0号显卡没有显存了吧

**Comment by wa3926** [comment]
@LDOUBLEV  初始化  1362MiB /  7611MiB     第一次小图片推荐  6650MiB /  7611MiB    第二次同样的图片 6722MiB /  7611MiB   再换一张图片 直接就 7428MiB /  7611MiB    报错了 Out of memory error on GPU 0.     内存一直不释放

**Comment by wa3926** [comment]
@LDOUBLEV  大佬求指导一下 我不知道是不是 gitee代码不同步问题

**Comment by wa3926** [comment]
应该是图片尺寸问题  小一点尺寸就没问题  图片太大需要resize一下
