### ISSUE TITLE
python3 PPOCRLabel.py --lang ch 命令出错怎么解决

### ISSUE THREAD

**Issue by pby231** [PaddlePaddle/PaddleOCR#1613]
python3 PPOCRLabel.py --lang ch 出现错误

PPOCRLabel.py:1035: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1794: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:1825: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:2011: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/home/pby231/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/pby231/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/home/pby231/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
[2020/12/30 13:28:59] root INFO: dt_boxes num : 1, elapse : 0.012268781661987305
[2020/12/30 13:28:59] root INFO: cls num  : 1, elapse : 0.007131099700927734
Intel MKL function load error: cpu specific dynamic library is not loaded

**Comment by tink2123** [comment]
可以参考这个issue：https://github.com/PaddlePaddle/PaddleOCR/issues/440

**Comment by pby231** [comment]
> 可以参考这个issue：#440

我的笔记本是AMD，点击自动识别就出错呢，版本不能降级呢

**Comment by grasswolfs** [comment]
这个可能也和硬件相关，估计不易解决，如果有可能的话还是建议换个intel的硬件

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
