### ISSUE TITLE
Text direction and recognition rate

### ISSUE THREAD

**Issue by huigezhi** [PaddlePaddle/PaddleOCR#1614]
When the text is not horizontal (such as vertical), the recognition rate can be greatly reduced or even unrecognized

**Comment by tink2123** [comment]
We have optimized for vertical text in predict_system
https://github.com/PaddlePaddle/PaddleOCR/blob/2b16323080bbf503828b96f1ef531dc1074a1272/tools/infer/predict_system.py#L76-L77

What is your run command? Is it convenient to provide bad case?
