### ISSUE TITLE
移动端的体验Demo的源码开放吗

### ISSUE THREAD

**Issue by li123** [PaddlePaddle/PaddleOCR#1616]
移动端提供的体验Demo(基于EasyEdge和Paddle-Lite, 支持iOS和Android系统)只看到了下载APK的二维码链接，源代码现在开源吗，在哪里能找到。谢谢。

**Comment by tink2123** [comment]
EasyEdge 的代码暂时无法开源， 在repo中我们提供了 ios 和 android 两个简单的demo，可以参考：
https://github.com/PaddlePaddle/PaddleOCR/tree/release/1.1/deploy/ios_demo
https://github.com/PaddlePaddle/PaddleOCR/tree/release/1.1/deploy/android_demo

**Comment by w070115230** [comment]
如何封装自己的sdk在ios移动端？

**Comment by GreatTreeZX** [comment]
> EasyEdge 的代码暂时无法开源， 在repo中我们提供了 ios 和 android 两个简单的demo，可以参考：
> https://github.com/PaddlePaddle/PaddleOCR/tree/release/1.1/deploy/ios_demo
> https://github.com/PaddlePaddle/PaddleOCR/tree/release/1.1/deploy/android_demo

iOS的Demo，识别率很低，没用Android高
