### ISSUE TITLE
端侧部署只对OCR的检测部署 可以吗？

### ISSUE THREAD

**Issue by gejianhui1** [PaddlePaddle/PaddleOCR#1617]
我想用端侧预测那块，只对OCR的检测部分进行部署测试时间，能解决吗

**Comment by tink2123** [comment]
可以的，识别和检测是解耦的。单独执行检测的预测代码即可。

**Comment by gejianhui1** [comment]
我的意思就像图中ocr中的识别和检测是串行在一起，如何分开检查，就像图二中ssd那样，有没有单独的cc文件



| |
mrjhge
|
|
邮箱：mrjhge@163.com
|

Signature is customized by Netease Mail Master

在2020年12月30日 20:08，xiaoting 写道：

可以的，识别和检测是解耦的。单独执行检测的预测代码即可。

**Comment by gejianhui1** [comment]
比如像yolov3这样，里边有两个文件夹。我看ocr里边生产的难以分开


| |
mrjhge
|
|
邮箱：mrjhge@163.com
|

Signature is customized by Netease Mail Master

在2020年12月30日 20:08，xiaoting 写道：

可以的，识别和检测是解耦的。单独执行检测的预测代码即可。

**Comment by tink2123** [comment]
需要自己修改一下main函数，只保留检测相关就可以
https://github.com/PaddlePaddle/PaddleOCR/blob/de3e2e7cd3b8b65ee02d7a41e570fa5b511a3c1d/deploy/cpp_infer/src/main.cpp#L72
