### ISSUE TITLE
关于在服务器上识别模型训练无故中断的问题

### ISSUE THREAD

**Issue by Hiroshi230** [PaddlePaddle/PaddleOCR#1619]
服务器上win10，paddle1.84，cuda10.1，本地训练无问题，服务器虚拟win10无故中断训练，不知如何排除故障，
在缩小了batchsize，增大了学习率，调小了queue，训练进行一段时间后会自动停止，不知原因为何

**Comment by WenmuZhou** [comment]
停止过程是否有报错，训练的是静态图版本吗

**Comment by hwangyl** [comment]
最后解决了没有啊？

**Comment by chuanfuye** [comment]
> 服务器上win10，paddle1.84，cuda10.1，本地训练无问题，服务器虚拟win10无故中断训练，不知如何排除故障，
> 在缩小了batchsize，增大了学习率，调小了queue，训练进行一段时间后会自动停止，不知原因为何

请问解决了吗

**Comment by chuanfuye** [comment]
> > 服务器上win10，paddle1.84，cuda10.1，本地训练无问题，服务器虚拟win10无故中断训练，不知如何排除故障，
> > 在缩小了batchsize，增大了学习率，调小了queue，训练进行一段时间后会自动停止，不知原因为何
> 
> 请问解决了吗

最后在Ubuntu系统训练可以用，win10还是不行
