### ISSUE TITLE
加载中文路径直接报错，导致无法解析数据

### ISSUE THREAD

**Issue by 617475jordan** [PaddlePaddle/PaddleOCR#1620]
[2020/12/31 11:11:56] root ERROR: error in loading image:F:\DataSets\车牌\功能车牌图像库数据\“藏”牌-30\藏ED2029.jpg
Can not recognise file  is :   F:\DataSets\车牌\功能车牌图像库数据\“藏”牌-30\藏ED2029.jpg

**Comment by WenmuZhou** [comment]
windows下中文路径会存在问题，这个我们后续会修复

**Comment by JingyiZhang0225** [comment]
cv2.imread(image_file)函数不接受中文参数，建议改为img=cv2.imdecode(np.fromfile(image_file,dtype=np.uint8),1)

**Comment by 617475jordan** [comment]
好的，谢谢

**Comment by xinye01234** [comment]
> cv2.imread(image_file)函数不接受中文参数，建议改为img=cv2.imdecode(np.fromfile(image_file,dtype=np.uint8),1)
但是遇到png图片会出错,jpg没问题
