### ISSUE TITLE
ocr_system不返回angle

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#1621]
使用hub serving start -c deploy/hubserving/ocr_system/config.json  启动的    

我看  ocr_system 下面module.py 源码是这样写的  没发现角度返回的参数 请问下改哪里可以返回
 dt_boxes, rec_res = self.text_sys(img)
            elapse = time.time() - starttime
            logger.info("Predict time: {}".format(elapse))

            dt_num = len(dt_boxes)
            rec_res_final = []

            for dno in range(dt_num):
                text, score = rec_res[dno]
                rec_res_final.append({
                    'text': text,
                    'confidence': float(score),
                    'text_region': dt_boxes[dno].astype(np.int).tolist()
                })
            all_results.append(rec_res_final)

**Comment by WenmuZhou** [comment]
理论上是不需要返回角度的，如果需要的话，需要改这里https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/infer/predict_system.py#L103   将angle_list返回

**Comment by wa3926** [comment]
@WenmuZhou  本想想根据角度 旋转图片方向的  因为图片有90 180 270的进来   但我刚才把paddleocr    文字方向检测用几张图片试了一下 好像只有  0和180  思路好像行不通了

**Comment by wa3926** [comment]
谢谢 已经想到解决办法了

**Comment by suparek** [comment]
> 谢谢 已经想到解决办法了

你好，请问你的解决办法是什么样的？

**Comment by suparek** [comment]
> 谢谢 已经想到解决办法了

我这也是只有0和180
