### ISSUE TITLE
推理报错：not find model file path inference/ch_ppocr_mobile_v2.0_det_infer/model

### ISSUE THREAD

**Issue by noirlyrik** [PaddlePaddle/PaddleOCR#1625]
解压后的文件内容如图
![image](https://user-images.githubusercontent.com/39143373/103402720-8e4d5400-4b88-11eb-9000-606569226bae.png)

**Comment by WenmuZhou** [comment]
你下载的是动态图的模型，需要使用dygraph 分支的代码
