### ISSUE TITLE
请问: 用了预训练模型, 对east训练,test tackling num处特别慢,这是为什么呢?该如何解决

### ISSUE THREAD

**Issue by xiaotongtong9293** [PaddlePaddle/PaddleOCR#1626]
用了预训练模型, 对east训练,test tackling num处特别慢,50张图用了45分钟,如图片所示, 关掉终端又试一次,还是很慢,这是为什么呢? 

![选区_308](https://user-images.githubusercontent.com/49447219/103406810-f30fab00-4b96-11eb-9196-87ee85e7b775.png)

一些参数配置如图
![选区_307](https://user-images.githubusercontent.com/49447219/103406645-5baa5800-4b96-11eb-9d8b-ed2096422253.png)

另外,想问:用east时,图片的宽和高必须设置为一样的吗?  类似 image_shape: [3, 512, 512] ??

**Comment by grasswolfs** [comment]
速度慢，可能和硬件有关吧，是用的GPU训练的么？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
