### ISSUE TITLE
win10下安装requirements里的依赖，出现以下错误！！

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1629]
ERROR: Command errored out with exit status 1:
   command: 'E:\Users\anaconda3\envs\PaddleOCR_new\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"'; __file__='"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\HONGSO~1\AppData\Local\Temp\pip-wheel-79mpitw4'
       cwd: C:\Users\HONGSO~1\AppData\Local\Temp\pip-install-ffnujfwd\python-levenshtein_2bb6d28252394694a806c809daab4ea3\
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\Levenshtein
  copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.7\Levenshtein
  copying Levenshtein\__init__.py -> build\lib.win-amd64-3.7\Levenshtein
  running egg_info
  writing python_Levenshtein.egg-info\PKG-INFO
  writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
  writing entry points to python_Levenshtein.egg-info\entry_points.txt
  writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
  writing requirements to python_Levenshtein.egg-info\requires.txt
  writing top-level names to python_Levenshtein.egg-info\top_level.txt
  reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.7\Levenshtein
  copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.7\Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for python-Levenshtein

ERROR: Command errored out with exit status 1:
     command: 'E:\Users\anaconda3\envs\PaddleOCR_new\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"'; __file__='"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HONGSO~1\AppData\Local\Temp\pip-record-1d6lu7sq\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Users\anaconda3\envs\PaddleOCR_new\Include\python-Levenshtein'
         cwd: C:\Users\HONGSO~1\AppData\Local\Temp\pip-install-ffnujfwd\python-levenshtein_2bb6d28252394694a806c809daab4ea3\
    Complete output (27 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.7\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.7\Levenshtein
    running egg_info
    writing python_Levenshtein.egg-info\PKG-INFO
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.7\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.7\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Users\anaconda3\envs\PaddleOCR_new\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"'; __file__='"'"'C:\\Users\\HONGSO~1\\AppData\\Local\\Temp\\pip-install-ffnujfwd\\python-levenshtein_2bb6d28252394694a806c809daab4ea3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HONGSO~1\AppData\Local\Temp\pip-record-1d6lu7sq\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Users\anaconda3\envs\PaddleOCR_new\Include\python-Levenshtein' Check the logs for full command output.

**Comment by PhilCuriosity** [comment]
安装一个vc_redist.x64.exe

**Comment by hsyy673150343** [comment]
> 安装一个vc_redist.x64.exe 再试试

为什么我批量图片识别的时候，保存下来的crop图最多只有十张？

**Comment by grasswolfs** [comment]
楼上再试试，不应该的

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
