### ISSUE TITLE
树莓派4B 运行paddle-lite-demo报错

### ISSUE THREAD

**Issue by tongtong9293** [PaddlePaddle/PaddleOCR#1630]
pi@raspberrypi:~/Documents/Paddle-Lite-Demo-master/PaddleLite-armlinux-demo/image_classification_demo $ sudo ./run.sh 
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TARGET ARCH ABI: armv7hf
-- PADDLE LITE DIR: ../Paddle-Lite
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP  4.5
-- OpenMP C flags:  -fopenmp
-- OpenMP CXX flags:  -fopenmp
-- OpenMP OpenMP_CXX_LIB_NAMES:  gomp;pthread
-- OpenMP OpenMP_CXX_LIBRARIES:  /usr/lib/gcc/arm-linux-gnueabihf/8/libgomp.so;/usr/lib/arm-linux-gnueabihf/libpthread.so
CMake Error at CMakeLists.txt:42 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/Documents/Paddle-Lite-Demo-master/PaddleLite-armlinux-demo/image_classification_demo/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
./run.sh:行19: ./image_classification_demo: 没有那个文件或目录

采用的是已经编译好的
opencv_contrib_python-4.1.0.25-cp37-cp37m-linux_armv7l.whl
opencv_python-4.4.0.46-cp37-cp37m-linux_armv7l.whl
+
python3.7.3，直接在树莓派上pip install 的

已经可以在python3.7中 Import cv2

是一定要在树莓派本机自行编译opencv+opencv_contrib么？并且在本机自行尝试cmake的时候提示

cmake fatal error: OpenCL_INCLUDE_DIR-NOTFOUND/CL/cl.h

请问如何解决？？ 十分感谢！

**Comment by long-Rookie** [comment]
加一，我也遇到了这个问题

**Comment by long-Rookie** [comment]
个人已经解决，C++,对下载的opencv-3.4.1 源码编译，更新了动态链接库，然后重新按照官方的命令跑了一遍就没有这种情况了。可能是因为树莓派本身的opencv C++环境没有搭建好，找不到对应库的原因导致的。d
