### ISSUE TITLE
关于端侧部署时 demo/cxx下 确实 没有Makefile.def这个文件

### ISSUE THREAD

**Issue by longshifeng** [PaddlePaddle/PaddleOCR#1634]
![image](https://user-images.githubusercontent.com/32770755/103460836-6d395e80-4d54-11eb-9319-794cc9633bc8.png)

@LDOUBLEV  你好，
树莓派4B 编译paddle-lite release/v2.7成功 但是使用demo 推理的时候 make -j 出现上述错误。

关于 demo/cxx下 确实 没有Makefile.def这个文件 在编译成功后正常demo下是没有cxx文件夹的，在 PaddleOCR/deploy/lite/下运行prepare.sh 才会生成cxx文件，而 prepare.sh 脚本里也没有关于Makefile.def啊。所以如果应该生成Makefile.def是应该在哪一步产生的？？
```
mkdir -p  $1/demo/cxx/ocr/debug/
cp  ../../ppocr/utils/ppocr_keys_v1.txt  $1/demo/cxx/ocr/debug/
cp -r  ./*   $1/demo/cxx/ocr/
cp ./config.txt  $1/demo/cxx/ocr/debug/
cp ../../doc/imgs/11.jpg  $1/demo/cxx/ocr/debug/

echo "Prepare Done"
```

![d0a788e1a9028c4d55b86237f7f9be5](https://user-images.githubusercontent.com/32770755/103460856-aa055580-4d54-11eb-95d4-07cb896a89fb.png)

另外编译paddle-lite时 命令如下：
./lite/tools/build_linux.sh --arch=armv7hf --with_python=ON --python_version=3.7 --with_cv=ON --with_extra=ON

**Comment by superdu12138** [comment]
请问问题解决了吗

**Comment by shuoyang129** [comment]
我也遇见这个问题啦，在编译paddle-lite android 时会在demo/cxx下生成这个Makefile.def，但是在编译armlinux 时没有这个文件，导致make -j 时出错

**Comment by longshifeng** [comment]
问题已经解决，确实是 平台的问题 armlinux下不能完全按照 android的教程进行。

**Comment by shuoyang129** [comment]
> 问题已经解决，确实是 平台的问题 armlinux下不能完全按照 android的教程进行。

怎么解决的？能不能分享一下相关的东西？

**Comment by lctagnes** [comment]
请问这个问题是怎么解决的？ armlinux下应该如何生成Makefile.def？能否分享一下？谢谢

**Comment by shuoyang129** [comment]
从其他demo抄写一个CMakefileLists,把该加的包加上，就可以顺利编译。

**Comment by lichman0405** [comment]
不使用build_linux.sh脚本。而是用build.sh脚本，添加参数
`./lite/tools/build.sh \
  --arm_os=armlinux \
  --arm_abi=armv7hf \
  --arm_lang=gcc \
  --build_extra=OFF \
  full_publish`
