### ISSUE TITLE
DB大分辨率漏检

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/PaddleOCR#1636]

**Comment by ShawnXsw** [comment]
图形分辨率横纵2000+，单个字符时易漏检（infer_det阶段），此时应改善train imageshape 还是 reader的maxlen

**Comment by LDOUBLEV** [comment]
可以发一张测试图看下

**Comment by ShawnXsw** [comment]
> 可以发一张测试图看下

![image](https://user-images.githubusercontent.com/33308054/103776559-931f7580-506a-11eb-83b2-4115c9499b2c.png)

**Comment by ShawnXsw** [comment]
done by self
