### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#1641]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1609730558 (unix time) try "date -d @1609730558" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3fc0001b94a) received by PID 112970 (TID 0x7fb195e57700) from PID 112970 ***]

之前使用Paddleocr训练自己的一批文本检测数据集是没问题的，现在换了一批数据训练老是报这种错误，训练一会就终止了。请问能通过设置什么参数解决这个问题吗？

**Comment by ZhangYangHNU** [comment]
请问解决了吗？我通过外部设备摄像头进行识别的时候也出现核心已转储的错误

**Comment by weiwenlan** [comment]
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
it works for me. Try it now.

**Comment by Ner0oooooo** [comment]
我也遇到这个问题了，请问解决了吗

**Comment by grasswolfs** [comment]
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
