### ISSUE TITLE
what is format for train_list.txt , eval_list.txt

### ISSUE THREAD

**Issue by Pooksin** [PaddlePaddle/PaddleOCR#1642]
i want to training my own dataset. but i can`t find about format.

how to train with my own datasets? how to preprocessing my dataset?

**Comment by zcswdt** [comment]
> i want to training my own dataset. but i can`t find about format.
> 
> how to train with my own datasets? how to preprocessing my dataset?

这个repo里面都有介绍，你可以去看一下。

**Comment by Pooksin** [comment]
"file_name \t label" is it correct format for using simple dataset?

**Comment by Pooksin** [comment]
sorry. i found
