### ISSUE TITLE
not find model file path ./inference/ch_ppocr_server_v2.0_det_infer//model

### ISSUE THREAD

**Issue by yangshiyu89** [PaddlePaddle/PaddleOCR#1643]
按照官网 quick start 下载推断模型后，结构树如下所示:
├── ch_ppocr_mobile_v2.0_cls_infer
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
├── ch_ppocr_server_v2.0_det_infer
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
├── ch_ppocr_server_v2.0_rec_infer
    ├── inference.pdiparams
    ├── inference.pdiparams.info
    └── inference.pdmodel
运行 infer_system.py 找不到 model 文件。这是和前一版本兼容问题吗？

```python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True```

```not find model file path ./inference/ch_ppocr_server_v2.0_det_infer//model```

**Comment by EgorOs** [comment]
Although I'm not completely sure, but you could try using absolute path to the model. Also here you can find my [google colab](https://colab.research.google.com/drive/1zXYmh0OmmyGVfHEmWr_tDooLlYY7D1XG?usp=sharing) with minimal working example for paddleOCR, I hope you'll find it helpful

**Comment by ForLittleBeauty** [comment]
I find the same problem. If you can try with your own tutorial, and find what was wrong may be the best solution

**Comment by LDOUBLEV** [comment]
> 按照官网 quick start 下载推断模型后，结构树如下所示:
> ├── ch_ppocr_mobile_v2.0_cls_infer
> │ ├── inference.pdiparams
> │ ├── inference.pdiparams.info
> │ └── inference.pdmodel
> ├── ch_ppocr_server_v2.0_det_infer
> │ ├── inference.pdiparams
> │ ├── inference.pdiparams.info
> │ └── inference.pdmodel
> ├── ch_ppocr_server_v2.0_rec_infer
> ├── inference.pdiparams
> ├── inference.pdiparams.info
> └── inference.pdmodel
> 运行 infer_system.py 找不到 model 文件。这是和前一版本兼容问题吗？
> 
> `python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True`
> 
> `not find model file path ./inference/ch_ppocr_server_v2.0_det_infer//model`

你的infer_system.py是基于develop分支的吧，你下载的2.0模型是动态图模型（dygraph分支），动态图分支下的inference 模型是这种格式：
```
ch_ppocr_server_v2.0_det_infer
├── inference.pdiparams
├── inference.pdiparams.info
└── inference.pdmodel
```
develop下的模型（1.0， 1.1）模型格式是：
```
ch_ppocr_server_v1.1_det_infer
model
params
```
