### ISSUE TITLE
Are there any plans to provide larger Multilingual Recognition Model?

### ISSUE THREAD

**Issue by root-T2** [PaddlePaddle/PaddleOCR#1645]
Thank you for developing a great product that is easy to use.
I am currently using the Japanese recognition model. Checking the results, text-detection and angle prediction are doing very well, but the accuracy of recognition is not so good. punctuation "、" and "。" are often missed or recognized as different characters like"い" and "り".
Currently, only {language}_mobile_v2.0_rec is available, but could you please provide a larger model {language}_server_v2.0_rec which has better performance?

**Comment by tink2123** [comment]
Thanks for your use. 
The current Japanese model is a preliminary version, and it will continue to iterate to optimize performance. Welcome to continue to pay attention.
