### ISSUE TITLE
有带有TRT的window预测库吗？

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleOCR#1647]
有没有是带有TRT的windows预测库？麻烦发个链接，谢谢了。

**Comment by LDOUBLEV** [comment]
可以参考官网链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/windows_cpp_inference.html

**Comment by stefan-567** [comment]
> 可以参考官网链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/windows_cpp_inference.html

    我下载了该链接中cuda10.0_cudnn7_avx_mkl（2.0.0-rc1）版本的预测库，安装了TensorRT 6 cuda 10.0版本，在配置文件中use_tensorrt和use_fp16都置为1， 软件运行在this->predictor_ = CreatePaddlePredictor(config)处崩溃，异常信息：
“0x00007FFB6B9A3B29 处(位于 Use.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x0000004F3CEFD1B8 处。 出现了 ”
    如果不在配置文件中打开TensorRT运行正常，这是什么原因导致的呢？

**Comment by grasswolfs** [comment]
这部分可以试下最新PaddleOCR 2.1分支代码，看看是否可以解决

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
