### ISSUE TITLE
请问一下，在将文字检测出来之后，PaddleOCR对待识别文字区域有什么预处理操作吗？

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1651]
因为在代码里，没发现有什么明显的操作。

**Comment by tink2123** [comment]
对检测框做了角度转正和垂直转正，具体在：https://github.com/PaddlePaddle/PaddleOCR/blob/40e83f2275dfc5ab976e4a8d49014f6bcc3514fc/tools/infer/predict_system.py#L48

**Comment by Hupengyu** [comment]
> 对检测框做了角度转正和垂直转正，具体在：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/40e83f2275dfc5ab976e4a8d49014f6bcc3514fc/tools/infer/predict_system.py#L48

请问在哪里可以看到他的整体的思路？readme和官方文档里这么细的操作并没有说明，但是我确实需要清楚
