### ISSUE TITLE
Linux  duance bushu

### ISSUE THREAD

**Issue by gejianhui1** [PaddlePaddle/PaddleOCR#1652]
LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:b92e8c4
      version of current Paddle-Lite:5610ee3b

**Comment by LDOUBLEV** [comment]
bushu 的问题是你编译的lite预测库和opt模型转换工具版本不匹配，建议用paddlelite2.7分支编译预测库和opt
