### ISSUE TITLE
采用paddle lite 进行 端侧部署，出现问题，环境配置了好多次，都没问题

### ISSUE THREAD

**Issue by gejianhui1** [PaddlePaddle/PaddleOCR#1654]
LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
version of opt:b92e8c4
version of current Paddle-Lite:5610ee3b

**Comment by DaveBoy** [comment]
这个我解决了


如果你的预测库是自己编译的，那么你的nb文件也要自己编译，用同一个lite版本。不能直接用下载的nb文件，因为版本不同

**Comment by maoxiaoming86** [comment]
> 这个我解决了
> 
> 如果你的预测库是自己编译的，那么你的nb文件也要自己编译，用同一个lite版本。不能直接用下载的nb文件，因为版本不同

请问您转的是dygraph分支train出来的模型吗？这个分支有个rnn op，好像只有lite2.8版本有，但我lite2.8版本编译报“Paddle-Lite/Paddle-Lite/lite/model_parser/base/io.h:89:17: 错误：‘is_trivially_copyable’不是‘std’的成员” 这样的错
