### ISSUE TITLE
PPOCRLabel工具更换自己训练好的模型出错

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1658]
这是报错信息
 File "G:/lyb/ocr/PaddleOCR/PPOCRLabel/PPOCRLabel.py", line 2094, in <module>
    sys.exit(main())
  File "G:/lyb/ocr/PaddleOCR/PPOCRLabel/PPOCRLabel.py", line 2082, in main
    app, _win = get_main_app(sys.argv)
  File "G:/lyb/ocr/PaddleOCR/PPOCRLabel/PPOCRLabel.py", line 2074, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file,
  File "G:/lyb/ocr/PaddleOCR/PPOCRLabel/PPOCRLabel.py", line 114, in __init__
    result = self.ocr.ocr('./data/img0_crop_0.jpg', cls=True, det=True)
  File "G:\lyb\ocr\PaddleOCR\paddleocr.py", line 282, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "G:\lyb\ocr\PaddleOCR\tools\infer\predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "G:\lyb\ocr\PaddleOCR\tools\infer\predict_rec.py", line 252, in __call__
    preds_text = self.char_ops.decode(rec_idx_tmp)
  File "G:\lyb\ocr\PaddleOCR\ppocr\utils\character.py", line 122, in decode
    char_list.append(self.character[int(text_index[idx])])
IndexError: list index out of range

进程已结束,退出代码1

我在paddleocr.py中修改了参数如下 ：
    else:
        return argparse.Namespace(  use_gpu=True,
                                    ir_optim=True, 
                                    use_tensorrt=False, 
                                    gpu_mem=8000, 
                                    image_dir='',
                                    det_algorithm='DB',
                                    det_model_dir='./inference/det_db5/',
                                    det_max_side_len=960,
                                    det_db_thresh=0.3,
                                    det_db_box_thresh=0.5,
                                    det_db_unclip_ratio=2.0,
                                    det_east_score_thresh=0.8,
                                    det_east_cover_thresh=0.1,
                                    det_east_nms_thresh=0.2,
                                    rec_algorithm='Rosetta',
                                    rec_model_dir='./inference/rec_Rosetta5/',
                                    rec_image_shape="3, 32, 192",
                                    rec_char_type='ch',
                                    rec_batch_num=30,
                                    max_text_length=10,
                                    rec_char_dict_path='./ppocr/utils/dict/number_dict.txt',
                                    use_space_char=False,
                                    cls_model_dir=None,
                                    cls_image_shape="3, 48, 192",
                                    label_list=['0', '180'],
                                    cls_batch_num=30,
                                    cls_thresh=0.9,
                                    enable_mkldnn=False,
                                    use_zero_copy_run=False,
                                    use_pdserving=False,
                                    lang='ch',
                                    det=True,
                                    rec=True,
                                    use_angle_cls=True
                                    )

**Comment by WenmuZhou** [comment]
rec_char_dict_path='./ppocr/utils/dict/number_dict.txt',  这个字典要换成你训练时候用的
