### ISSUE TITLE
attention还是失败

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#166]
![1](https://user-images.githubusercontent.com/6395366/84135742-e9005080-aa7c-11ea-9424-1f53074cef44.jpg)
export_model  模型成功，但是识别rec阶段使用官网提供的图像和命令，报错如上图。

**Comment by tink2123** [comment]
识别过程没有报错，且完成了预测流程，但输出结果是['', nan]， 请问export model的命令是什么，是否生成了正确的inference_model呢

**Comment by SixGodGG** [comment]
> 识别过程没有报错，且完成了预测流程，但输出结果是['', nan]， 请问export model的命令是什么，是否生成了正确的inference_model呢

我又重新export了一次，还是同样的结果。
模型转化命令如下：
python E:/GitHub/PaddleOCR/tools/export_model.py -c E:/GitHub/PaddleOCR/configs/rec/rec_r34_vd_tps_bilstm_attn.yml -o Global.checkpoints=D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/rec_r34_vd_tps_bilstm_attn/best_accuracy Global.save_inference_dir=D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/rec_r34_vd_tps_bilstm_attn/


attention的Rec 识别命令如下：
python E:/GitHub/PaddleOCR/tools/infer/predict_system.py --image_dir="E:/GitHub/PaddleOCR/doc/imgs_en/img_195.jpg" --det_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference/det/" --det_algorithm="DB" --rec_model_dir="D:/Git/Label-LH/Run-64SJC/paddleOCR-Case/inference-other/rec_r34_vd_tps_bilstm_attn/" --rec_image_shape="3, 32, 100" --rec_char_type="en" --use_gpu="false" --rec_algorithm="RARE"

**Comment by tink2123** [comment]
命令没有问题，我这边重新尝试了一次也是可以正确识别的，或许你可以试一下我转换好的inference model，看能否识别成功？

[rec_mv3_tps_bilstm_attn.zip](https://github.com/PaddlePaddle/PaddleOCR/files/4758010/rec_mv3_tps_bilstm_attn.zip)

**Comment by SixGodGG** [comment]
rec_r34_vd_tps_bilstm_attn 我之前试的是这个模型。
换了你提供的inference模型。rec正确。
我重新下载了OCR Readme中的rec_mv3_tps_bilstm_attn   checkpoints模型，再次export出inference模型，识别结果还是不对，没法用，我对比你给我的inference模型，感觉我export这步可能出错。
![1](https://user-images.githubusercontent.com/6395366/84341529-f11fd380-abd5-11ea-84e0-25a230ca1a93.jpg)
![2](https://user-images.githubusercontent.com/6395366/84341544-fa10a500-abd5-11ea-92f9-79b3c77f64a1.jpg)

**Comment by SixGodGG** [comment]
这是我的config，其中训练，test数据集地址没有配置，
![3](https://user-images.githubusercontent.com/6395366/84342751-edda1700-abd8-11ea-8df9-338ec071da24.jpg)
![4](https://user-images.githubusercontent.com/6395366/84342754-ef0b4400-abd8-11ea-9d11-687e6dc45eda.jpg)


[rec.zip](https://github.com/PaddlePaddle/PaddleOCR/files/4762438/rec.zip)

**Comment by SixGodGG** [comment]
![5](https://user-images.githubusercontent.com/6395366/84343710-840f3c80-abdb-11ea-97eb-81ddfc8cbec7.jpg)
关键转换这一步也没什么错误提示啊。

**Comment by SixGodGG** [comment]
@tink2123

**Comment by tink2123** [comment]
配置文件没有问题，export model不需要配置数据。export model不报错说明参数文件和模型配置匹配，使用 tools/infer_rec.py 加载你的参数文件可以正确得到结果吗？

**Comment by SixGodGG** [comment]
> 配置文件没有问题，export model不需要配置数据。export model不报错说明参数文件和模型配置匹配，使用 tools/infer_rec.py 加载你的参数文件可以正确得到结果吗？
不可以

**Comment by tink2123** [comment]
那可能是因为你参数文件下载有误

**Comment by SixGodGG** [comment]
> 那可能是因为你参数文件下载有误

您如果没有自己下载过你们提供的rec_r34_vd_tps_bilstm_attn，再export出inference模型，请不要妄下评论。另外问题还没解决呢，怎么就close了

**Comment by tink2123** [comment]
@SixGodGG 给您回复之前我在本地重新下载并测试过两个模型，且两种方式都验证过没有问题，r34模型太大无法在github上传，因此发送给mv3模型供您测试。您贴出来的命令除去本地路径无法验证，其余部分是正确的，我发送给你的inference_model您可以得到正确结果。
>使用 tools/infer_rec.py 加载你的参数文件可以正确得到结果吗？
不可以

因此我说“可能”参数文件下载有误，我理解这不算“妄加评论”吧。

**Comment by LDOUBLEV** [comment]
> > 那可能是因为你参数文件下载有误
> 
> 您如果没有自己下载过你们提供的rec_r34_vd_tps_bilstm_attn，再export出inference模型，请不要妄下评论。另外问题还没解决呢，怎么就close了

attention模型转inference模型出错的问题已经解决了，所以我才关了这个issue，不是我小伙伴关的。
现在按照repo里的文档转inference模型去预测是没问题的，有问题再沟通。
