### ISSUE TITLE
同类型图片经常出现漏检

### ISSUE THREAD

**Issue by xcorrnner** [PaddlePaddle/PaddleOCR#1661]
![2](https://user-images.githubusercontent.com/30427269/103728679-a6562500-5019-11eb-90e0-62b932b08c83.png)
![4](https://user-images.githubusercontent.com/30427269/103728689-ae15c980-5019-11eb-9b9d-0abb45aae196.png)

**Comment by WenmuZhou** [comment]
也可能是识别分数太低，过滤了，单独跑检测确定下是不是检测的问题

**Comment by xcorrnner** [comment]
您说的检测是指下面
> [2021/01/06 12:29:22] root INFO: dt_boxes num : 1, elapse : 0.022029638290405273 这一行？

elapse 是有分数的，但是没有dt_box。请问这种怎么调整


已经识别
> [2021/01/06 12:29:22] root INFO: dt_boxes num : 1, elapse : 0.022029638290405273
[2021/01/06 12:29:22] root INFO: cls num  : 1, elapse : 0.01804804801940918
[2021/01/06 12:29:23] root INFO: rec_res num  : 1, elapse : 0.10828781127929688
[2021/01/06 12:29:23] root INFO: 185D, 1.000

未识别
>[2021/01/06 12:30:40] root INFO: dt_boxes num : 0, elapse : 0.02203202247619629
[2021/01/06 12:30:40] root INFO: cls num  : 0, elapse : 0
[2021/01/06 12:30:40] root INFO: rec_res num  : 0, elapse : 0

**Comment by xcorrnner** [comment]
原图
![45](https://user-images.githubusercontent.com/30427269/103757506-d3233000-504b-11eb-86a5-b1ead0b859d4.png)
模型识别产出为空
![45](https://user-images.githubusercontent.com/30427269/103757518-d74f4d80-504b-11eb-852a-6e19e477e108.png)
检测
![det_res_45](https://user-images.githubusercontent.com/30427269/103757669-0d8ccd00-504c-11eb-8378-5ab859a3d21c.png)
原图比较大，这是需要识别的区域，有什么办法可以提高检测的准确性吗？eg.更换尺寸,灰度图像

**Comment by tink2123** [comment]
可以针对场景数据，finetune一下检测模型。
