### ISSUE TITLE
编译运行android_demo失败

### ISSUE THREAD

**Issue by xiaotian-freedom** [PaddlePaddle/PaddleOCR#1662]
导入到Android studio后构建项目，报以下错误：

ld: error: found local symbol '__end__' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so

Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a Native}
  ninja: Entering directory `/Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a'
  [1/11] Building CXX object CMakeFiles/Native.dir/ocr_db_post_process.cpp.o
  [2/11] Building CXX object CMakeFiles/Native.dir/ocr_clipper.cpp.o
  [3/11] Building CXX object CMakeFiles/Native.dir/ppredictor.cpp.o
  [4/11] Building CXX object CMakeFiles/Native.dir/predictor_input.cpp.o
  [5/11] Building CXX object CMakeFiles/Native.dir/ocr_cls_process.cpp.o
  [6/11] Building CXX object CMakeFiles/Native.dir/ocr_crnn_process.cpp.o
  [7/11] Building CXX object CMakeFiles/Native.dir/native.cpp.o
  [8/11] Building CXX object CMakeFiles/Native.dir/ocr_ppredictor.cpp.o
  [9/11] Building CXX object CMakeFiles/Native.dir/predictor_output.cpp.o
  [10/11] Building CXX object CMakeFiles/Native.dir/preprocess.cpp.o
  [11/11] Linking CXX shared library /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libNative.so
  FAILED: /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libNative.so 
  : && /Users/zoneyet/Desktop/android_sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android23 --gcc-toolchain=/Users/zoneyet/Desktop/android_sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/zoneyet/Desktop/android_sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -Wno-format -ffast-math -Ofast -Os -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  -Wl,--gc-sections -Wl,-z,nocopyreloc -shared -Wl,-soname,libNative.so -o /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libNative.so CMakeFiles/Native.dir/native.cpp.o CMakeFiles/Native.dir/ocr_clipper.cpp.o CMakeFiles/Native.dir/ocr_cls_process.cpp.o CMakeFiles/Native.dir/ocr_crnn_process.cpp.o CMakeFiles/Native.dir/ocr_db_post_process.cpp.o CMakeFiles/Native.dir/ocr_ppredictor.cpp.o CMakeFiles/Native.dir/ppredictor.cpp.o CMakeFiles/Native.dir/predictor_input.cpp.o CMakeFiles/Native.dir/predictor_output.cpp.o CMakeFiles/Native.dir/preprocess.cpp.o  /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_calib3d.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_core.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_dnn.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_features2d.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_flann.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_highgui.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_imgcodecs.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_ml.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_objdetect.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_photo.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_stitching.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_video.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_videoio.a -lGLESv2 -lEGL -ljnigraphics -llog /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibprotobuf.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_imgcodecs.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibjpeg-turbo.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibwebp.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibpng.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibtiff.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/liblibjasper.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libIlmImf.a -landroid -llog -lmediandk /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libquirc.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_calib3d.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_features2d.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_flann.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/staticlibs/arm64-v8a/libopencv_core.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libtbb.a -lc -lz /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libcpufeatures.a /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libittnotify.a -ldl -lm -llog /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/arm64-v8a/libtegra_hal.a -latomic -lm && cd /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a && /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/cmake -E copy /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libc++_shared.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libc++_shared.so && cd /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a && /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/cmake -E copy /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libpaddle_light_api_shared.so && cd /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a && /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/cmake -E copy /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libhiai.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libhiai.so && cd /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a && /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/cmake -E copy /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libhiai_ir.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libhiai_ir.so && cd /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/.cxx/cmake/debug/arm64-v8a && /Users/zoneyet/Desktop/android_sdk/sdk/cmake/3.10.2.4988404/bin/cmake -E copy /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libhiai_ir_build.so /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/build/intermediates/cmake/debug/obj/arm64-v8a/libhiai_ir_build.so
  ld: error: found local symbol '__bss_end__' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '__bss_start' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '_end' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '_edata' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '__bss_start__' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '_bss_end__' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  ld: error: found local symbol '__end__' in global part of symbol table in file /Users/zoneyet/Downloads/PaddleOCR-develop/deploy/android_demo/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by lingzhiwen** [comment]
same question, wait supported.

**Comment by yuyutao** [comment]
使用ndk版本为22的话 只编译armv7的 没问题
想编译arm64 只能降低ndk版本到21
