### ISSUE TITLE
difference in run time between docker and conda 

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/PaddleOCR#1664]
docker:
- images: paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82
- paddle version: 2.0rc1 gpu
- inference time: 12 ms

conda:
- python 3.7, cuda 11, cudnn 8
- paddle version: 2.0rc1.post110 gpu
- inference time: 53ms

command: `python3 tools/infer/predict_system.py --image_dir="test.jpg" --det_model_dir="./inference/det_db/" --det_algorithm="DB" --rec_model_dir="./inference/rec_crnn" --rec_image_shape="3, 32, 100" --rec_char_type="en"
` 

device: RTX 2080ti

Same models, same test image, same other packages version from requirements.txt

**Comment by WenmuZhou** [comment]
cuda and version will affect speed

**Comment by xxxpsyduck** [comment]
@WenmuZhou Is this a bug of paddle itself? This should not be an expected behavior

**Comment by littletomatodonkey** [comment]
As wenmuzhou says, cuda and cunn version will affect speed. Cuda and cudnn version in docker are different from your conda env.
