### ISSUE TITLE
Is SRN(Towards Accurate Scene Text Recognition with Semantic Reasoning Networks) open source or not? 

### ISSUE THREAD

**Issue by Xushanbo** [PaddlePaddle/PaddleOCR#1666]
I notice some issues about SRN training process, but can't find the related algorithm, besides the doc in  [https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en](url)    says   **' SRN(paper)[5] coming soon'**.
So, it is open source or not? And how can I use it?

**Comment by WenmuZhou** [comment]
Please wait patiently, it will be released after ready

**Comment by tink2123** [comment]
Currently the dynamic version is still under debugging. If you want to use it, the static version has been released. Can refer to https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/doc/doc_en/algorithm_overview_en.md


The configuration file is ：https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/configs/rec/rec_r50fpn_vd_none_srn.yml

**Comment by Xushanbo** [comment]
> 
> 
> Currently the dynamic version is still under debugging. If you want to use it, the static version has been released. Can refer to https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/doc/doc_en/algorithm_overview_en.md
> 
> The configuration file is ：https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/configs/rec/rec_r50fpn_vd_none_srn.yml

Thanks a lot! I didn't notice that document.
