### ISSUE TITLE
hub install 报错UnboundLocalError: local variable 'version' referenced before assignment

### ISSUE THREAD

**Issue by 1253970836** [PaddlePaddle/PaddleOCR#1667]
hub install deploy/hubserving/ocr_system/安装后卸载再安装报UnboundLocalError: local variable 'version' referenced before assignment

**Comment by WenmuZhou** [comment]
第二次安装成功了吗

**Comment by grasswolfs** [comment]
可以先确定下版本，paddlepaddle 2.0rc1，paddlehub最新的也是2.0rc0了
