### ISSUE TITLE
v2.0-rc1-0训练模型和测试模型的识别结果差距较大

### ISSUE THREAD

**Issue by frotms** [PaddlePaddle/PaddleOCR#1668]
使用ch_ppocr_server_v2.0_rec_infer和ch_ppocr_server_v2.0_rec_train对同一输入进行测试，从第一层卷积层结果开始，结果就不一样了。它们的权重也不一样。所以这个infer模型不是由train模型转换得到的吗？？？

**Comment by littletomatodonkey** [comment]
ch_ppocr_server_v2.0_rec_infer是inference model，你是怎么查看权重的呢？

**Comment by frotms** [comment]
@littletomatodonkey 不好意思，我弄错了，主页上的是ch_ppocr_server_v2.0_rec_pre模型，重新找了ch_ppocr_server_v2.0_rec_train模型，验证了是一致的
