### ISSUE TITLE
端侧部署出问题

### ISSUE THREAD

**Issue by gejianhui1** [PaddlePaddle/PaddleOCR#1669]
总是显示lite版本和opt版本不一致问题，根据教程下载的这两个，如何统一他们一致。

**Comment by DaveBoy** [comment]
不能直接用下载的nb文件，下载的nb用的其他版本的opt（2.6.3好像）编译的，你的lite是2.7（假如），这就不一样了。

**Comment by DaveBoy** [comment]
要用你编译预测库的lite版本自己编译nb
