### ISSUE TITLE
求推荐个设备配置

### ISSUE THREAD

**Issue by RunSean** [PaddlePaddle/PaddleOCR#1673]
希望使用paddleOcr对工业相机拍的照片进行文字识别
工业相机500W像素
每张照片大概5M 或者 11M
大小 2048 * 2448

希望识别结果在800ms内返回，可以将paddleOcr部署成服务，图片经网络传输，也可以是C#取到照片直接调用paddleOcr的动态链接库

求GPU或者CPU最低要求

**Comment by LDOUBLEV** [comment]
工业相机的图像是可以压缩的吧，每张图像中文字多少？预测速度和图像大小也有关系的；

最低要求也吃不准，好的GPU、CPU运算速度快，GPU一般用T4预测吧，你可以先在你有的机器上测试速度，不满意的话再更新机器；
