### ISSUE TITLE
部署后，发送二进制流的post请求

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#1675]
你好，我在使用hubsevring部署后，在发送post请求时，如果使用使用二进制流而不是base64，请求参数的headers和data应该怎么写呢
r = requests.post(url=url, headers=headers, data=json.dumps(data))

**Comment by MissPenguin** [comment]
一般都是用base64编码呢，不太清楚你说的这种咋弄，可能需要自己调研下。。

**Comment by Lie-huo** [comment]
> 一般都是用base64编码呢，不太清楚你说的这种咋弄，可能需要自己调研下。。

因为我需要识别pdf，所以打算使用二进制流的方式向post发送请求；content-type必须是'application/json' 吗，可以是其他的类型吗，  另外发送post请求支持使用MultipartEncoder 来编码吗
