### ISSUE TITLE
Advise:Cuda error(30), unknown error. This indicates that an unknown internal error has occurred

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleOCR#1679]
环境：Cuda compilation tools, release 10.1, V10.1.105 ， paddle：2.0. beta
执行命令：python3 tools/export_model.py -c configs/rec/rec_r34_vd_none_bilstm_ctc.yml
报错：
Traceback (most recent call last):
  File "tools/export_model.py", line 75, in <module>
    main()
  File "tools/export_model.py", line 48, in main
    startup_prog, eval_program, place, config, _ = program.preprocess()
  File "/home/wang/work/pythonwork/paddleOCR-Dete-UBUNTU/tools/program.py", line 416, in preprocess
    place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::GetCUDADeviceCount()
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:68)

之前几次转换模型是没问题的，这次就报错了。

**Comment by MissPenguin** [comment]
难道是环境损坏，要不重新拉个docker试试

**Comment by wj920291253** [comment]
额。。。我去试试。

**Comment by wj920291253** [comment]
....重启下就可以了。。
