### ISSUE TITLE
FatalError: A serious error (Process abort signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#1680]
执行训练的时候，动不动就卡死在这一步，报个这个错也不往下走

`2021-01-07 16:11:12,320-INFO: Already save model in ./output/rec_CRNN/iter_epoch_12
2021-01-07 16:11:29,295-INFO: epoch: 15, iter: 60, lr: 0.008845, 'loss': 35.44248, 'acc': 0.917969, time: 2.869
2021-01-07 16:11:33,426-INFO: Already save model in ./output/rec_CRNN/iter_epoch_15
double free or corruption (fasttop)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Process abort signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1610007101 (unix time) try "date -d @1610007101" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80036c8ca) received by PID 3590346 (TID 0x7fb337d72700) from PID 3590346 ***]`

**Comment by littletomatodonkey** [comment]
试一下动态图代码吧，dataloader这块优化的比较多

**Comment by hudielv** [comment]
使用api预测时，也会出现这个错误，怎么回事？这个是什么导致的错误，请教下？

**Comment by Evezerest** [comment]
paddle版本是多少呢？升级到最新的试试？
