### ISSUE TITLE
使用CPU预测开启enable_mkldnn，乱码问题

### ISSUE THREAD

**Issue by peterpanhjh** [PaddlePaddle/PaddleOCR#1688]
使用CPU推理过程，开启enable_mkldnn=true后，发现hubserving 预测的返回数据是乱码，这个是什么问题，该怎么解决呢

**Comment by LDOUBLEV** [comment]
这个问题已经反馈给intel了，开启mkldnn时，如果识别的batch_size>1，结果是乱码，batch_size=1结果正常，可以设置识别的batch_size=1

**Comment by KyleWang-Hunter** [comment]
> 这个问题已经反馈给intel了，开启mkldnn时，如果识别的batch_size>1，结果是乱码，batch_size=1结果正常，可以设置识别的batch_size=1

设置batch_size=1结果还是乱码
