### ISSUE TITLE
如何添加新词到文本识别字典

### ISSUE THREAD

**Issue by XingBin111** [PaddlePaddle/PaddleOCR#1689]
如何添加新词到文本识别字典并且不影响原模型对旧词的识别, 以及增加新词之后如何load文字识别的预训练模型?

**Comment by LDOUBLEV** [comment]
新词加在对应字典中，为了保证原有模型的准确率，需要准备大量的数据训练（包括新词和旧词的）；
增加新词后加载模型用Global.pretrain_weights，不要用Global.checkpoints

**Comment by XingBin111** [comment]
假设Global.pretrain_weights识别字典有5000个词, 如果我新加100个词到字典中, 应该加到识别字典的末尾吗? 
另外最后一层的分类器类别由5000 增加为5100, 应该如何加载Global.pretrain_weights最后一层的分类器?

**Comment by tink2123** [comment]
更改分类器维度后无法加载之前的fc层参数，需要重新训练。但是加载backbone部分的pretrain依然可以加速收敛。
