### ISSUE TITLE
调用Paddleocr 之后出现 axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by Nagisakurumi** [PaddlePaddle/PaddleOCR#1694]
不知道哪里报的错  我试了 你们官方的图片 还有我自己的本地图片  无论是我传路径 还是 我先读取然后再传 np的数据进去都是这样。

一下是代码

def appendPath(path):
    current = os.getcwd()
    current = os.path.join(current, path)
    print("path : ", current)
    return current

def parse_args():
    import argparse
    
    return argparse.Namespace(
            use_gpu=False,
            ir_optim=True,
            use_tensorrt=False,
            gpu_mem=8000,
            image_dir='',
            det_algorithm='DB',
            det_model_dir=appendPath('det'),
            det_limit_side_len=960,
            det_limit_type='max',
            det_db_thresh=0.3,
            det_db_box_thresh=0.5,
            det_db_unclip_ratio=2.0,
            det_east_score_thresh=0.8,
            det_east_cover_thresh=0.1,
            det_east_nms_thresh=0.2,
            rec_algorithm='CRNN',
            rec_model_dir=appendPath('rec'),
            rec_image_shape="3, 32, 320",
            rec_char_type='ch',
            rec_batch_num=30,
            max_text_length=25,
            rec_char_dict_path=appendPath('ppocr_keys_v1.txt'),
            use_space_char=True,
            drop_score=0.5,
            cls_model_dir=None,
            cls_image_shape="3, 48, 192",
            label_list=['0', '180'],
            cls_batch_num=30,
            cls_thresh=0.9,
            enable_mkldnn=False,
            use_zero_copy_run=False,
            use_pdserving=False,
            lang='ch',
            det=True,
            rec=True,
            use_angle_cls=False)

self.ocr_engine = PaddleOCR(**(parse_args().__dict__))

img = cv.imread(appendPath("1.jpg"))
print(img.shape)
results = self.ocr_engine.ocr(img)

**Comment by WenmuZhou** [comment]
你好，我这边没有复现你这个问题，我的代码是
```python
import os
import cv2
from paddleocr import PaddleOCR
def appendPath(path):
    current = os.getcwd()
    current = os.path.join(current, path)
    print("path : ", current)
    return current

def parse_args():
    import argparse

    return argparse.Namespace(
            use_gpu=False,
            ir_optim=True,
            use_tensorrt=False,
            gpu_mem=8000,
            image_dir='',
            det_algorithm='DB',
            det_model_dir=appendPath('det'),
            det_limit_side_len=960,
            det_limit_type='max',
            det_db_thresh=0.3,
            det_db_box_thresh=0.5,
            det_db_unclip_ratio=2.0,
            det_east_score_thresh=0.8,
            det_east_cover_thresh=0.1,
            det_east_nms_thresh=0.2,
            rec_algorithm='CRNN',
            rec_model_dir=appendPath('rec'),
            rec_image_shape="3, 32, 320",
            rec_char_type='ch',
            rec_batch_num=30,
            max_text_length=25,
            rec_char_dict_path=appendPath('PaddleOCR/ppocr/utils/ppocr_keys_v1.txt'),
            use_space_char=True,
            drop_score=0.5,
            cls_model_dir=None,
            cls_image_shape="3, 48, 192",
            label_list=['0', '180'],
            cls_batch_num=30,
            cls_thresh=0.9,
            enable_mkldnn=False,
            use_zero_copy_run=False,
            use_pdserving=False,
            lang='ch',
            det=True,
            rec=True,
            use_angle_cls=False)
ocr_engine = PaddleOCR(**(parse_args().__dict__))

img = cv2.imread(appendPath('PaddleOCR/doc/imgs/1.jpg'))
print(img.shape)
results = ocr_engine.ocr(img)
print(results)
```

**Comment by littletomatodonkey** [comment]
1. 2.0rc1的whl包的话，需要使用dygraph分支的inference model
2. 之前whl包的话，需要使用develop分支的inference model
3. 上面同学也提供了代码哈，可以试一下，如果还有问题，欢迎随时reopen或者开一个issue哈
