### ISSUE TITLE
pdserving 部署

### ISSUE THREAD

**Issue by Ming-Zhou0201** [PaddlePaddle/PaddleOCR#1695]
λ 8f66b0707106 /paddle-test/PycharmProjects/PaddleOCR_152/deploy/pdserving {develop} python3.7 det_local_server.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "det_local_server.py", line 23, in <module>
    from tools.infer.predict_det import TextDetector
  File "/paddle-test/PycharmProjects/PaddleOCR_152/tools/infer/predict_det.py", line 27, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 286, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 254, in <module>
    from .core_avx import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

大佬帮忙看看！！！
paddle版本2.0.0.rc1

还有一个问题，老版本训练的模型在新版本的paddleocr 和paddlepaddle 还适用吗？

**Comment by LDOUBLEV** [comment]
这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6

**Comment by LDOUBLEV** [comment]
老版本是基于静态图的，新版本是基于动态图的，模型不通用

**Comment by Ming-Zhou0201** [comment]
> 老版本是基于静态图的，新版本是基于动态图的，模型不通用

我就指的静态图版本，develop 分支之前一直在更新，之前试过一次，两个不同版本的develop分支，eval结果还是差很多的

**Comment by LDOUBLEV** [comment]
> > 老版本是基于静态图的，新版本是基于动态图的，模型不通用
> 
> 我就指的静态图版本，develop 分支之前一直在更新，之前试过一次，两个不同版本的develop分支，eval结果还是差很多的

可以提供下两个develop版本的commit和日期吗
在PaddleOCR 目录下 git log 指令查看

**Comment by Ming-Zhou0201** [comment]
> 这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6

![image](https://user-images.githubusercontent.com/58206790/104010447-752b4f80-51e7-11eb-8278-92e5e8adcf85.png)
是有的。。。
串联服务 就一行代码启动吧？python ocr_rpc_server.py

**Comment by Ming-Zhou0201** [comment]
> > > 老版本是基于静态图的，新版本是基于动态图的，模型不通用
> > 
> > 
> > 我就指的静态图版本，develop 分支之前一直在更新，之前试过一次，两个不同版本的develop分支，eval结果还是差很多的
> 
> 可以提供下两个develop版本的commit和日期吗
> 在PaddleOCR 目录下 git log 指令查看

很早之前做的实验，记得是在提出4.2M那个会议之后和之前的版本了。

**Comment by littletomatodonkey** [comment]
要不试一下最新的develop分支代码吧

**Comment by Ming-Zhou0201** [comment]
> 要不试一下最新的develop分支代码吧

目前更新到最新代码，然后还是无法部署
images 镜像
hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev

paddle-serving-app        0.0.0       
paddle-serving-client     0.0.0       
paddle-serving-server     0.0.0       
paddle-serving-server-gpu 0.0.0.post10


按照教程
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/readme.md
部署ch_ppocr_mobile_v1.1_det_infer 
python3 det_rpc_server.py 图片.jpg


报错日志：
2021-01-15 09:52:14,267-INFO: Predict time of ../../../PaddleOCR_003/train_data/real_det/realdata/00000000.jpg: 0.010s
2021-01-15 09:52:14,267-INFO: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "pdserving_client.py", line 117, in <module>
    main(image_path)
  File "pdserving_client.py", line 96, in main
    draw_img = draw_server_result(image_file, res)
  File "pdserving_client.py", line 45, in draw_server_result
    keys = res[0].keys()
AttributeError: 'str' object has no attribute 'keys'


大佬能再看看吗

**Comment by Ming-Zhou0201** [comment]
> 这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6

这个我重新查了一下，因为我一直用的是python3.7  xxx.py 或者pip3.7  install xxx，拉取的images环境变量里都是python3.5.1，所以部署的时候找不到GPU 、cuda等等，但是平常训练是没有问题的

**Comment by wangjiawei04** [comment]
> > 这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6
> 
> 这个我重新查了一下，因为我一直用的是python3.7 xxx.py 或者pip3.7 install xxx，拉取的images环境变量里都是python3.5.1，所以部署的时候找不到GPU 、cuda等等，但是平常训练是没有问题的

https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_rpc_server.py#L98 
目前Serving在做Paddle 2.0 重构 1月底会更新这部分代码，如果现在需要跑通，可以按照上述链接
改成 `return feed, fetch, True`
最后的True意思是 feed里的tensor是否为一整个batch的图片

**Comment by Ming-Zhou0201** [comment]
> > > 这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6
> > 
> > 
> > 这个我重新查了一下，因为我一直用的是python3.7 xxx.py 或者pip3.7 install xxx，拉取的images环境变量里都是python3.5.1，所以部署的时候找不到GPU 、cuda等等，但是平常训练是没有问题的
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_rpc_server.py#L98
> 目前Serving在做Paddle 2.0 重构 1月底会更新这部分代码，如果现在需要跑通，可以按照上述链接
> 改成 `return feed, fetch, True`
> 最后的True意思是 feed里的tensor是否为一整个batch的图片

改了之后，还是有一些小问题
目前对于paddle 2.0 .0b0训练的模型，需要提高QPS，这里有什么好的建议吗？

**Comment by hymanzhu1983** [comment]
> > > 这个应该是paddle版本不对，paddle需要libstdc++.so.6，你看下/usr/lib/x86_64-linux-gnu/这个路径下是不是没有 libstdc++.so.6 这个文件，有没有libstdc++.so.6.* 的文件，有的话重命名为libstdc++.so.6
> > 
> > 
> > 这个我重新查了一下，因为我一直用的是python3.7 xxx.py 或者pip3.7 install xxx，拉取的images环境变量里都是python3.5.1，所以部署的时候找不到GPU 、cuda等等，但是平常训练是没有问题的
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_rpc_server.py#L98
> 目前Serving在做Paddle 2.0 重构 1月底会更新这部分代码，如果现在需要跑通，可以按照上述链接
> 改成 `return feed, fetch, True`
> 最后的True意思是 feed里的tensor是否为一整个batch的图片

请问serving的改动会在什么时候提交？
