### ISSUE TITLE
Data augmentation methods???

### ISSUE THREAD

**Issue by lloydnguyen96** [PaddlePaddle/PaddleOCR#1697]
You said in the data augmentation section: "The default perturbation methods are: cvtColor, blur, jitter, Gasuss noise, random crop, perspective, color reverse."
Then, what is cvtColor, perspective, color reverse in detail? Thanks

**Comment by LDOUBLEV** [comment]
There are  https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/data/imaug/rec_img_aug.py

**Comment by xxxpsyduck** [comment]
@lloydnguyen96 if your problem resolved, please close the issue
