### ISSUE TITLE
pdserving部署调用后出现 array has incorrect number of dimensions: 3; expected 4

### ISSUE THREAD

**Issue by solomance** [PaddlePaddle/PaddleOCR#1698]
$ python3 pdserving_client.py ../../doc/imgs/12.jpg

2021-01-08 22:58:45,327-INFO: Predict time of ../../doc/imgs/12.jpg: 0.064s
2021-01-08 22:58:45,327-INFO: array has incorrect number of dimensions: 3; expected 4
Traceback (most recent call last):
  File "pdserving_client.py", line 133, in <module>
    main(image_path)
  File "pdserving_client.py", line 112, in main
    draw_img = draw_server_result(image_file, res)
  File "pdserving_client.py", line 60, in draw_server_result
    keys = res[0].keys()
AttributeError: 'str' object has no attribute 'keys'

PaddleServing版本：
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_server_gpu-0.0.0.post10-py3-none-any.whl
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.0.0-cp37-none-any.whl
https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.0-py3-none-any.whl

PaddleOCR部署：
https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving

PaddleOCR版本：
分支：develop
last commit: 12442d1c4f87c8c0db6f448a47fb9158eb84251a

麻烦帮忙看看，谢谢！

**Comment by littletomatodonkey** [comment]
看着是出现请求异常了，在`keys = res[0].keys()`前面直接print(res)看下返回结果是什么呢？

**Comment by zhfkt** [comment]
我也遇到了这个问题， print(res) -> res直接就是 array has incorrect number of dimensions: 3; expected 4
