### ISSUE TITLE
ocr 文本识别之后如何拼成有意义的句子呢？

### ISSUE THREAD

**Issue by CSU-FulChou** [PaddlePaddle/PaddleOCR#1699]
您好：我有个问题想要咨询一下：
比如 图片扫描之后 box 的顺序并不是 真正的语句顺序，
例如：
![image](https://user-images.githubusercontent.com/46887649/104041802-89397600-5214-11eb-8f0a-e89859410e83.png)

如何定位到具体信息呢？ 或者将 box能够组成有意义的语句呢？

**Comment by LDOUBLEV** [comment]
现在box的排序方式是从上到下从左到右，你可以更改这个排序方式看能否实现你想要的效果，另外，观察到，你的测试图像中有明显的序号，你可以根据识别到文字的序号排序

**Comment by CSU-FulChou** [comment]
您好，
这个排序是我讲目前的ocr顺序打印出来方便看。比较明显地看到，0号和1号的位置。应该调换。
但是却不是一个仅仅先左右再上下扫描能够满足 语义。不知道在 产品应用的时候，想要固定提取某一个 左边字段 key 对应的右边字段 value 有没有一些较好的办法呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Double_V <notifications@github.com&gt;
发送时间: 2021年1月9日 14:15
收件人: PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com&gt;
抄送: CSU-FulChou <602933854@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleOCR] ocr 文本识别之后如何拼成有意义的句子呢？ (#1699)





 
现在box的排序方式是从上到下从左到右，你可以更改这个排序方式看能否实现你想要的效果，另外，观察到，你的测试图像中有明显的序号，你可以根据识别到文字的序号排序

**Comment by LDOUBLEV** [comment]
你的场景是比较垂类的，实现你想要的效果可以用规则的方法试一下，识别到指定key的字符时，也能获得当前key字符的文本框，可以根据框的位置推算value的文本框位置

**Comment by yumeliu** [comment]
> 现在box的排序方式是从上到下从左到右，你可以更改这个排序方式看能否实现你想要的效果，另外，观察到，你的测试图像中有明显的序号，你可以根据识别到文字的序号排序

请问要更改哪个文件里的哪个函数呢？感谢耐心解答!

**Comment by CSU-FulChou** [comment]
我目前采用的方案是 利用nlp即文本框内容语义之间的关系。来做一个找到对应文本。
目前这个顺序仅仅是你所说的上下，左右。找到这个顺序，很简单，你分析一下 运行的文件。有一个人去合成新图片的操作。在里面作者将每一个box都花了一遍。你加入顺序到每个box里面文字就可以了。如果还是不明白的话。
你可以再联系我



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yumeliu <notifications@github.com&gt;
发送时间: 2021年2月15日 18:12
收件人: PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com&gt;
抄送: CSU-FulChou <602933854@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleOCR] ocr 文本识别之后如何拼成有意义的句子呢？ (#1699)
