### ISSUE TITLE
Chinese scene text recognition datasets problems?

### ISSUE THREAD

**Issue by lloydnguyen96** [PaddlePaddle/PaddleOCR#1704]
I cannot download Chinese Street View Text Recognition datasets and Chinese Document Text Recognition dataset from outside of China.
I actually have a Baidu account but recently, whenever I log in, a window will pop up and require me to enter the verification code which in fact never come to my phone number in the forms of some SMS messages
Thanks

**Comment by xxxpsyduck** [comment]
You can login using a github account instead. Guess you won't have any problem with that.

**Comment by lloydnguyen96** [comment]
And how about Synthetic Chinese String Dataset??? github account doesn't work this time

**Comment by xxxpsyduck** [comment]
guess you'll have to generate one by yourself. All the tools are open-sourced. They can not upload all the datasets to external services like dropbox or google drive because of high cost

**Comment by lloydnguyen96** [comment]
I spent hours trying to create a Baidu account using an oversea phone number but nothing works

**Comment by lloydnguyen96** [comment]
One more question: in Synthetic Chinese String Dataset, file Chinese_dataset.rar only consists of images, but not labels for those images, right? Only file 'Synthetic Chinese String Dataset.rar' has labels in corresponding test.txt and train.txt file, right?

**Comment by littletomatodonkey** [comment]
Yes you can uncompress the rar file, all the files are included in the directory.
