### ISSUE TITLE
some updates repeated

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#1706]
2020.6.5 Support exporting attention model to inference_model
2020.6.5 Support separate prediction and recognition, output result score
2020.6.5 Support exporting attention model to inference_model
2020.6.5 Support separate prediction and recognition, output result score

**Comment by WenmuZhou** [comment]
where are you see these?

**Comment by Intsigstephon** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/update_en.md

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
