### ISSUE TITLE
is the means and std in the wrong order, rgb instead of bgr?

### ISSUE THREAD

**Issue by zylo117** [PaddlePaddle/PaddleOCR#1713]
Hi, I found out that all the means and stds are the same as imagenet's. But in imagenet, they are in the cfg are in RGB order while this repo train and infer in BGR order.
 https://github.com/PaddlePaddle/PaddleOCR/blob/161a47a6e263f3249ea4a0ec40c779eddea630eb/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L124-L125

I believe they can both achieve the almost same performance, just pointing out.

**Comment by LDOUBLEV** [comment]
> I believe they can both achieve the almost same performance.
Yes, it is.
