### ISSUE TITLE
Multilingual Recognition Pre-trained model for fineturning ?

### ISSUE THREAD

**Issue by HienDT27** [PaddlePaddle/PaddleOCR#1714]
Thanks you for developing a great product .
I am using the Japanese recognition model but I want to fineturning (training on my dataset )  ,
I can't found the pre-trained model ( https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/models_list_en.md )
( found pre-trained model for Chinese Recognition Model only )

Are there any plans to provide pre-trained model for multilingual recognition task ( japanese , korean ...) ?

**Comment by MissPenguin** [comment]
Multilingual recognition models have been released. Check out here: https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/models_list_en.md#multilingual-recognition-modelupdating

**Comment by HienDT27** [comment]
Thanks so much .

**Comment by bit-scientist** [comment]
Hi, @MissPenguin, I was trying to run `python tools/infer/predict_system.py` as given [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/inference_ppocr_en.md#text-detection-angle-classification-and-recognition-inference-concatenation), but couldn't find  relevant files for `--det_model_dir`, `--cls_model_dir` for Korean language. They are available for Chinese and English. Does it mean that files residing in default paths (`./ch_PP-OCRv3_det_infer/`, `./cls/ch_ppocr_mobile_v2.0_cls_slim_infer/`) also support Korean (or other languages)? I am afraid that is not the case. Could you explain about it a little. Thank you.
