### ISSUE TITLE
cannot import name 'inference' from 'paddle'

### ISSUE THREAD

**Issue by apophatique** [PaddlePaddle/PaddleOCR#1715]
Hello. I'm trying to start paddleocr.py, but i'm getting an error:
 `Traceback (most recent call last):
  File "A:/Projects/PaddleOCR/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "A:\Projects\PaddleOCR\tools\infer\predict_system.py", line 28, in <module>
    import tools.infer.utility as utility
  File "A:\Projects\PaddleOCR\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle'`

I've already installed requrements.txt. Please, explain, what is the problem? 
Thank you

**Comment by HorizonLiang** [comment]
+1

**Comment by MissPenguin** [comment]
Which version of Paddle have you installed? Paddle 2.0.0rc1 is required.

**Comment by apophatique** [comment]
> Which version of Paddle have you installed? Paddle 2.0.0rc1 is required.

![image](https://user-images.githubusercontent.com/44003762/104290306-66dd7c00-54e4-11eb-9685-902009cc03cd.png)

have I installed the right package exactly? is it https://pypi.org/project/paddle/ ??

**Comment by LDOUBLEV** [comment]
pip install paddlepaddle-gpu==2.0.0rc1

**Comment by apophatique** [comment]
> pip install paddlepaddle-gpu==2.0.0rc1
> or
> pip install paddlepaddle-gpu==2.0.0rc1 -f https://paddlepaddle.org.cn/whl/stable.html
> ![image](https://user-images.githubusercontent.com/26592129/104290657-93e65a80-54f5-11eb-8c2c-05808fc48323.png)
> 
> https://pypi.org/project/paddlepaddle/#history

I've installed paddlepaddle as you wrote, but it doesn't help - same error
I dont understand a bit, i had to install paddlepaddle-gpu, but import/error goes from paddle?  

![image](https://user-images.githubusercontent.com/44003762/104294393-4e239500-54e9-11eb-8e51-2d22e7e9b627.png)

![image](https://user-images.githubusercontent.com/44003762/104294638-a0fd4c80-54e9-11eb-8cff-351d89fc8f51.png)

**Comment by Champwin** [comment]
in paddle\__init__.py, line 24:

except ImportError:
    import sys
    sys.stderr.write('''Warning with import paddle: you **should not
     import paddle from the source directory**; please install paddlepaddle*.whl firstly.'''
                     )
so you can copy paddleocr.py to other path, and run it again.
