### ISSUE TITLE
树莓派4B使用python + paddlelite的方式运行文字识别模型时，只识别图片的前一半内容，这是什么原因呢？

### ISSUE THREAD

**Issue by NYF-BRICK** [PaddlePaddle/PaddleOCR#1720]

**Comment by LDOUBLEV** [comment]
是没张图都这样吗，你看下可视化结果，剩下的一半内容有没有检测到

**Comment by NYF-BRICK** [comment]
> 是没张图都这样吗，你看下可视化结果，剩下的一半内容有没有检测到

是每一张图片都是这样，det模型的文字区域检测是正常的，但rec模型就是只输出图片中前一半的文字。
我现在是参照c++的demo中用在predictor.run()之后predictor.get_output(0)的结果进行后续处理，他还有一个get_output(1)的结果。现在我怀疑是不是应该用get_output(1)的结果来处理。

**Comment by NYF-BRICK** [comment]
python的情况下，不能参照c++demo中的识别结果的postprocess流程走。

**Comment by siyuzhong94** [comment]
楼主是交叉编译部署到树莓派上的么，有木有交叉编译的教程

**Comment by NYF-BRICK** [comment]
有的。
