### ISSUE TITLE
找不到model

### ISSUE THREAD

**Issue by Mr-Zhange** [PaddlePaddle/PaddleOCR#1722]
PS D:\Code\PaddleOCR> D:\Code\CC\venv\Scripts\python.exe  .\tools\infer\predict_rec.py --rec_model_dir="D:\Code\CC\tools\ch_ppocr_server_v2.0_rec_infer" --image_dir="D:\Code\CC\image\20210112190106.bmp"
2021-01-13 02:15:40,965-INFO: not find model file path D:\Code\CC\tools\ch_ppocr_server_v2.0_rec_infer/model

用的是主页下载的识别模型-推理模型

检测模型所在文件夹。传参方式有两种，1. None: 自动下载内置模型到 ~/.paddleocr/det；2.自己转换好的inference模型路径，模型路径下必须包含model和params文件......

**Comment by LDOUBLEV** [comment]
你用的预测代码是develop分支的代码，使用的是静态图版本，带2.0的模型是动态图版本的模型；

develop分支的预测模型是
```
ch_ppocr_server_v1.1_rec_infer
- model
- param
```

dygraph 分支的预测模型是：
```
ch_ppocr_server_v2.0_rec_infer
- inference.pdimodel
- inference.pdiparams
- inference.pdinfo
```

可以在PaddleOCR目录下，用git branch 命令查看当前分支，如果是develop分支，建议从[这个页面](https://github.com/PaddlePaddle/PaddleOCR/tree/develop#pp-ocr-11-series-model-listupdate-on-sep-17)下载模型，如果是digraph分支，建议从[此页面](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-20-series-model-listupdate-on-dec-15)下载模型；

**Comment by ChiMuYuan** [comment]
@LDOUBLEV  
啊这...其实是develop下server的模型里面解压出来是一个没有后缀的东西，然后手动改成了.rar或.tar，再解压才是model + param。
也就是说套娃了，并且套了个无后缀的文件。
