### ISSUE TITLE
PPOCRLabel启动问题

### ISSUE THREAD

**Issue by liyi002** [PaddlePaddle/PaddleOCR#1724]
请问一下，运行 python3 PPOCRLabel.py --lang ch报错：
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1610504597 (unix time) try "date -d @1610504597" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e900002f39) received by PID 12089 (TID 0x7f7636c96740) from PID 12089 ***]

**Comment by liuzard** [comment]
同样的问题，deepin v15，重装了很多次都是报这个错，在windows下正常

**Comment by ricardomlyk** [comment]
同问，Ubuntu18.04，一模一样的报错，安装PPOCRLabel的时候完全按照readme，猜测是要另外安装QT5？

**Comment by liuzard** [comment]
> ~同问，Ubuntu18.04，一模一样的报错，安装PPOCRLabel的时候完全按照readme，猜测是要另外安装QT5？~
> 
> 刚刚谷歌报错的时候查到了一个博客，其中的报错和这个情况相同，根据博客的教程来处理亲测问题解决，具体操作：
> 1、通过在系统变量中添加`export QT_DEBUG_PLUGINS=1`打开pyqt的debug模式；
> 2、再次运行PPOCRLabel.py，可以从debug信息里发现真正的问题是`Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory) QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"`；
> 3、cd到/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/，然后`ldd libqxcb.so`查看依赖关系，发现真正缺少的是`libxcb-xinerama.so.0`；
> 4、安装缺少的库`sudo apt-get install libxcb-xinerama0`；
> 
> [原博客](https://www.jb51.net/article/193024.htm)
> 
> 在此感谢PPOCR项目的开发者们


正解，感谢！

**Comment by liuzard** [comment]
> ~同问，Ubuntu18.04，一模一样的报错，安装PPOCRLabel的时候完全按照readme，猜测是要另外安装QT5？~
> 
> 刚刚谷歌报错的时候查到了一个博客，其中的报错和这个情况相同，根据博客的教程来处理亲测问题解决，具体操作：
> 1、通过在系统变量中添加`export QT_DEBUG_PLUGINS=1`打开pyqt的debug模式；
> 2、再次运行PPOCRLabel.py，可以从debug信息里发现真正的问题是`Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory) QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"`；
> 3、cd到/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/，然后`ldd libqxcb.so`查看依赖关系，发现真正缺少的是`libxcb-xinerama.so.0`；
> 4、安装缺少的库`sudo apt-get install libxcb-xinerama0`；
> 
> [原博客](https://www.jb51.net/article/193024.htm)
> 
> 在此感谢PPOCR项目的开发者们


正解，感谢！
可能大家确的库不一样，但是通过打开debug模式找到缺的库，就可以定位问题。
我缺的是libxcb-util.so.1，通过[解决debian 10.6安装Qt后提示缺少xcb无法启动的问题](https://www.cnblogs.com/mariocanfly/p/14061631.html)解决。

**Comment by liuzard** [comment]
> ~同问，Ubuntu18.04，一模一样的报错，安装PPOCRLabel的时候完全按照readme，猜测是要另外安装QT5？~
> 
> 刚刚谷歌报错的时候查到了一个博客，其中的报错和这个情况相同，根据博客的教程来处理亲测问题解决，具体操作：
> 1、通过在系统变量中添加`export QT_DEBUG_PLUGINS=1`打开pyqt的debug模式；
> 2、再次运行PPOCRLabel.py，可以从debug信息里发现真正的问题是`Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory) QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"`；
> 3、cd到/usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/，然后`ldd libqxcb.so`查看依赖关系，发现真正缺少的是`libxcb-xinerama.so.0`；
> 4、安装缺少的库`sudo apt-get install libxcb-xinerama0`；
> 
> [原博客](https://www.jb51.net/article/193024.htm)
> 
> 在此感谢PPOCR项目的开发者们

正解，感谢！
可能大家缺的库不一样，但是通过打开debug模式找到缺的库，就可以定位问题。
我缺的是libxcb-util.so.1，通过解决debian 10.6安装Qt后提示缺少xcb无法启动的问题解决。

**Comment by lexiaoyuan** [comment]
Ubuntu 16.04。运行 `python3 PPOCRLabel.py --lang ch`，报错：
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1612507733 (unix time) try "date -d @1612507733" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x2e9) received by PID 745 (TID 0x7f6d1df23740) from PID 745 ***]

Aborted (core dumped)
```

**Comment by WenmuZhou** [comment]
qt没装，看起来

**Comment by lexiaoyuan** [comment]
> Ubuntu 16.04。运行 `python3 PPOCRLabel.py --lang ch`，报错：
> 
> ```
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::framework::SignalHandle(char const*, int)
> 1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Process abort signal` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1612507733 (unix time) try "date -d @1612507733" if you are using GNU date ***]
>   [SignalInfo: *** SIGABRT (@0x2e9) received by PID 745 (TID 0x7f6d1df23740) from PID 745 ***]
> 
> Aborted (core dumped)
> ```

按照上面的步骤，debug定位，显示如下信息（部分）：
```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1612516047 (unix time) try "date -d @1612516047" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x8a2) received by PID 2210 (TID 0x7f5d58800740) from PID 2210 ***]

Aborted (core dumped)
```
按上面的步骤，应该是缺少`libxcb-icccm`，但是这个库用`apt-get install libxcb-icccm`，显示`E: Unable to locate package libxcb-icccm`。

pyqt5重装了好几次，还是报这个错误。

**Comment by ccl-private** [comment]
linux下，pyqt5版本选5.12.1,apt安装libxcb-icccm，libxcb-util，libxcb-xinerama0，问题解决。
如果apt找不到这些包，用apt-cache search libxcb-icccm命令可以查找正确的包名。
