### ISSUE TITLE
标注数据 标注空格 问题

### ISSUE THREAD

**Issue by chenglong-do** [PaddlePaddle/PaddleOCR#1725]
Q2.2.1：支持空格的模型，标注数据的时候是不是要标注空格？中间几个空格都要标注出来么？
A：如果需要检测和识别模型，就需要在标注的时候把空格标注出来，而且在字典中增加空格对应的字符。标注过程中，如果中间几个空格标注一个就行。

看到 FAQ  里面说需要单独标注，使用的是 PPOCRLable 标注，标注空格后，里面内容不能为空格，请问下这样应该怎么处理喃？

**Comment by Evezerest** [comment]
能具体描述一下是哪一步出现问题了吗？如果在识别结果中的文字之间增加空格是可以保存的。

**Comment by chenglong-do** [comment]
> 能具体描述一下是哪一步出现问题了吗？如果在识别结果中的文字之间增加空格是可以保存的。

我看这个 FAQ 的意思是空格需要单独标注，您的意思是整段标注后中间加空格就可以了么？

**Comment by Evezerest** [comment]
是的，标注的时候在字符之间加空格就行，不需要单独把空格用检测框画出来。但PaddleOCR的空格识别只支持对英文间空格的识别。另外根据您的描述`标注空格后，里面内容不能为空格` 是指在单独绘制检测框，标记空格为识别结果的时候会出错吗？

**Comment by chenglong-do** [comment]
> 是的，标注的时候在字符之间加空格就行，不需要单独把空格用检测框画出来。但PaddleOCR的空格识别只支持对英文间空格的识别。另外根据您的描述`标注空格后，里面内容不能为空格` 是指在单独绘制检测框，标记空格为识别结果的时候会出错吗？

是的，我是看FAQ 觉得是 在单独绘制检测框，标记空格为识别结果，如果不是这样，那就没问题，谢谢！
