### ISSUE TITLE
这个项目支持onnx转换吗

### ISSUE THREAD

**Issue by chenxinhua** [PaddlePaddle/PaddleOCR#1726]
这个项目的模型支持转换为onnx吗

**Comment by littletomatodonkey** [comment]
暂时应该还没支持，后续会考虑，可以看下X2Paddle这个repo

**Comment by jiangjiajun** [comment]
> 这个项目的模型支持转换为onnx吗

你好，我们目前已经通过Paddle2ONNX来支持各模型套件的转换，PaddleOCR基于PaddlePaddle 2.0的版本（dygraph分支）已经支持导出为ONNX，欢迎关注Paddle2ONNX，了解更多项目的进展

- Paddle2ONNX项目：https://github.com/PaddlePaddle/Paddle2ONNX
- Paddle2ONNX支持转换的[模型列表](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8Focr)
