### ISSUE TITLE
SIG Task Acceptance | 兴趣小组纳新说明

### ISSUE THREAD

**Issue by Evezerest** [PaddlePaddle/PaddleOCR#1728]
PaddleOCR has accumulated more than 10K Stars and has been frequently listed on the Github Trending daily and monthly lists, thanks to the support of all the community users. With the open source of many high-quality content, the dream of serving OCR technology to all walks of life is also realized gradually. Many hands make light work. We need developers in the community who have the will, ability and time to work with us to apply OCR to all kinds of production and life in the spirit of open source, which is also the origin of the PaddleOCR Special Interest Group (PPOCR-SIG). In PPOCR-SIG, you can get face-to-face communication with PaddlePaddle's senior R & D, and also with SIG members from various fields to fully express opinions and show your good ideas. Get open source honor will also have material rewards. We hope that the open source platform could be an amplifier of your ability, look forward to your participation.

Examples of SIG collaboration content.
1、Participate in improving the labeling tool PPOCRLabel
2、Use PaddleOCR to complete solutions for various application scenarios
3、Complete the deployment of new programming language prediction independently
4、Use PaddleOCR to complete the model training of new languages
5、New algorithm model replication and integration

**How to participate: complete [the questionnaire](https://iwenjuan.baidu.com/?code=da1gu6) and the pre-task to officially join**

SIG pre-task: According to [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR), complete the entire process (or part of the process) from installation, prediction, training, and deployment, and record the problems you encounter and raise issues or requirements in the process, improvements to the code or optimization points, and effective experience can also be shared on various platforms.

Task acceptance links include any of the following, please reply under this issue:
- Issues raised during the process and their solutions. (Add [SIG] before issue title)
- Put forward valuable PR for code improvement points and be merged. (Add [SIG] before PR title)
- Document records of the whole process operation (including the main operation process, experience and ideas, the final result, etc.) and publish it on Zhihu, CSDN and other platforms.

_Note: If you have made one of the above contributions to PaddleOCR before, you can join SIG directly by replying the link below. 
If you do not have a clear optimization goal but have a strong willingness to join, you can also reply below, and the staff will assign you specific optimization points._

PaddleOCR累计Star数超过10K，频频登上Github Trending 日榜月榜，感谢各位社区用户的支持，众多优质的内容开源也是希望能将OCR技术服务于各行各业。众人拾柴火焰高，我们需要社区中有意愿有能力有时间的开发者与我们一起，以开源的精神将OCR应用于各类生产生活中，这也就是特殊兴趣小组（SIG）的由来，在这里你可以获得飞桨资深研发面对面交流，也可以与各行各业SIG成员充分碰撞思想，表达意见，show出你的好想法，获得开源荣誉的同时也会有物质层面的奖励。希望开源平台能成为你能力的放大器，期待你的加入。

SIG协作内容示例：
1、参与改进标注工具PPOCRLabel
2、利用PaddleOCR完成各个应用场景的解决方案
3、独立完成新编程语言预测部署
4、使用PaddleOCR完成新语种的模型训练
5、新算法模型复现与合入

**加入方式：[完成问卷](https://iwenjuan.baidu.com/?code=da1gu6)与前置任务即可正式加入**

前置任务说明：根据 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 文档完成从安装、预测、训练以及部署的全流程（或部分流程）操作，在此过程中记录自己遇到的问题、提出issues或需求、对代码或优化点提出改进，有效的经验也可以分享在各类内容平台。

提交形式包括以下任意一种，直接在此问题下回复完成后的链接：
- 对流程过程中提出的issues及其解决方式（在issue标题前加入[SIG]标志）
- 对代码改进点提出有价值的PR且合入（在PR标题前加入[SIG]标志）
- 全流程操作的文档记录（包括主要的操作流程、经验与想法、最终实现的效果等）并发布在知乎，CSDN等平台

_注意：如果你之前已经对PaddleOCR做出过上述贡献之一，直接在下方回复链接即可加入SIG。若你没有明确的优化目标但同时具有较强的加入意愿，也可在下方回复说明，工作人员将为你分配具体优化点。_

**Comment by abnercloud** [comment]
hello

**Comment by Wei-JL** [comment]
已添加打开当前预标注数据集的文件夹的功能
https://github.com/PaddlePaddle/PaddleOCR/pull/3275

**Comment by d2623587501** [comment]
add the shortcut key[pr url](https://github.com/PaddlePaddle/PaddleOCR/pull/3261)
