### ISSUE TITLE
弯曲文本检测怎么与tps识别模型串联

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleOCR#1729]
![image](https://user-images.githubusercontent.com/18511799/104429269-64505480-55c0-11eb-8ef0-62443ea34558.png)

wiki里写的检测框矫正逻辑的局限性不支持串联，那弯曲文本ocr是怎样的流程呢？

**Comment by tink2123** [comment]
弯曲文本建议使用端到端的算法，repo中有开源[PGNet](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/pgnet.md)。
