### ISSUE TITLE
用pathlib这个模块做了什么

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#173]
我在阿里云函数计算上使用PaddleOCR时 初始化时报一个错
{'errorMessage': "Module initialization error: 'type object 'Path' has no attribute 'home''", 'errorType': 'Exception', 'stackTrace': ["AttributeError: type object 'Path' has no attribute 'home'"]}

**Comment by LDOUBLEV** [comment]
不太明白你报错的情况，可以详细描述下吗？看报错好像是你那边环境配置的问题

{'errorMessage': "Module initialization error: 'type object 'Path' has no attribute 'home''",
