### ISSUE TITLE
develop分支的iOSDemo识别效果远不及Adnroid，问题是出在哪里？

### ISSUE THREAD

**Issue by GreatTreeZX** [PaddlePaddle/PaddleOCR#1730]
http://img5.taoche.cn/00/d4f3bcdb-022200h2yi.jpg

http://img5.taoche.cn/00/98ba8865-022200mive.jpg

http://img5.taoche.cn/00/a70a0e32-022200mipz.jpg

目的识别VIN码

扫码安装Demo又快，又流畅，又准，用GitHub源码的Demo，卡、不准

**Comment by LDOUBLEV** [comment]
可以发一下case吗

**Comment by GreatTreeZX** [comment]
> 可以发一下case吗

http://img5.taoche.cn/00/d4f3bcdb-022200h2yi.jpg

扫码安装Demo又快，又流畅，又准，用GitHub源码的Demo，卡、不准

**Comment by tink2123** [comment]
IOS demo是由外部用户贡献的，暂时不更新维护了，如有需要可以在repo里的源码基础上进行优化。
