### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by JinlongHe** [PaddlePaddle/PaddleOCR#1731]
![image](https://user-images.githubusercontent.com/27532975/104432288-d4140e80-55c3-11eb-9779-14ef40a9c10c.png)
在测试paddleocr下，输入python tools/test_hubserving.py http://127.0.0.1:8866/predict/ocr_system ./doc/imgs/
，然后出现错误（paddleocr已经安装成功）
![image](https://user-images.githubusercontent.com/27532975/104432612-28b78980-55c4-11eb-8a73-bfa1bea16371.png)

**Comment by tink2123** [comment]
文档已更新：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/pdserving/README_CN.md

可以参考这个步骤部署
