### ISSUE TITLE
[Bug Report]使用PPOCRLabel的自动标注功能时出现段错误

### ISSUE THREAD

**Issue by ricardomlyk** [PaddlePaddle/PaddleOCR#1732]
环境：
Ubuntu18.04
paddlepaddle 2.0.0rc1 (cpu)

情况说明：
PPOCRLabel可以正常打开，在手动绘制box之后单独使用识别模型也没有问题，但当选中一个文件夹然后直接ctrl+shift+A调用predication_system后，自动标注的进度条走完后UI消失的几秒之后PPOCRLabel会闪退

报错信息：
`Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/root/.paddleocr/2.0/rec/en', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
[2021/01/13 17:38:20] root INFO: dt_boxes num : 1, elapse : 0.018787145614624023
[2021/01/13 17:38:20] root INFO: cls num  : 1, elapse : 0.006593942642211914
[2021/01/13 17:38:20] root INFO: rec_res num  : 1, elapse : 0.00758671760559082

(python3:11095): dconf-WARNING **: 17:38:20.445: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:20.445: failed to commit changes to dconf: The connection is closed
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Gtk-Message: 17:38:23.706: GtkDialog mapped without a transient parent. This is discouraged.

(python3:11095): dconf-WARNING **: 17:38:23.781: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:23.815: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:24.900: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:25.769: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:27.934: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:28.759: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:29.795: failed to commit changes to dconf: The connection is closed

(python3:11095): dconf-WARNING **: 17:38:29.795: failed to commit changes to dconf: The connection is closed
file name in openNext is  /home/ricardo/Pictures/PPOCRLabel/test1/1.png
dirPath in importDirImages is /home/ricardo/Pictures/PPOCRLabel/test1
Using model from  paddle
[2021/01/13 17:38:32] root INFO: dt_boxes num : 38, elapse : 0.3279993534088135
[2021/01/13 17:38:32] root INFO: cls num  : 38, elapse : 0.19802308082580566
[2021/01/13 17:38:32] root INFO: rec_res num  : 38, elapse : 0.28386545181274414
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
[2021/01/13 17:38:32] root INFO: dt_boxes num : 21, elapse : 0.25923991203308105
[2021/01/13 17:38:33] root INFO: cls num  : 21, elapse : 0.09653735160827637
[2021/01/13 17:38:33] root INFO: rec_res num  : 21, elapse : 0.10576558113098145
unicodeFilePath is /home/ricardo/Pictures/PPOCRLabel/test1/2.jpg
[('Di', [[17.0, 108.0], [65.0, 112.0], [59.0, 190.0], [11.0, 186.0]], None, None, False)]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1610530715 (unix time) try "date -d @1610530715" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x3a) received by PID 11095 (TID 0x7f1906e5a740) from PID 58 ***]

Segmentation fault (core dumped)
`

**Comment by Evezerest** [comment]
打开文件后点击自动标注按钮会报错吗？

**Comment by ricardomlyk** [comment]
@Evezerest   点按钮不会，好像只有用快捷键ctrl+shift+A才会闪退，这么神奇的嘛？

**Comment by Evezerest** [comment]
我们这边测试了一下仿佛是有概率出现的

**Comment by ricardomlyk** [comment]
另外在折腾自动标注的时候还发现一个小问题，就是如果输入的图片高度小于32，那么使用自动标注的时候会报如下错误：
`Using model from  paddle
invalid input 'img' in NormalizeImage
Traceback (most recent call last):
  File "/home/ricardo/code/PaddleOCR/PPOCRLabel/libs/autoDialog.py", line 37, in run
    self.result_dic = self.ocr.ocr(Imgpath, cls=True, det=True)
  File "../paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "../tools/infer/predict_system.py", line 89, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "../tools/infer/predict_det.py", line 157, in __call__
    data = transform(data, self.preprocess_op)
  File "../ppocr/data/imaug/__init__.py", line 38, in transform
    data = op(data)
  File "../ppocr/data/imaug/operators.py", line 82, in __call__
    np.ndarray), "invalid input 'img' in NormalizeImage"
AssertionError: invalid input 'img' in NormalizeImage
`
一开始直接拿人工标注之后的文本图片（从原图中把检测框裁剪出来）来做自动标注就报这个错，然后就翻了一下源码，问题应该是因为在检测模型中，对原图做预处理的时候调用了[operators.py](https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/ppocr/data/imaug/operators.py#L115)里面的`DetResizeForTest`的`__call__`方法，然后调用`resize_image_type0`方法，里面的`resize_h = int(round(resize_h / 32) * 32)`会导致高度小于32的所有图片的`resize_h`变为0，然后触发后面的返回`None`。
而后面的预处理方法`NormalizeImage`没有处理这种输入，而是直接raise了一个`AssertionError: invalid input 'img' in NormalizeImage`。这样会导致因为文件夹里的某个高小于32的样本而中断整个自动标注过程，我觉得是不是应该加一些逻辑处理一下这个异常，让自动标注跳过这些不符合高/宽的样本，而不影响其他的样本的自动标注。

**Comment by Evezerest** [comment]
好的，感谢你的反馈，如果可以的话欢迎直接将修改的代码PR

**Comment by YY007H** [comment]
我测试识别图片过小的图片也会报这个错误
![Uploading img1724061495421253893.jpg…]()

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/1992  fixed in this

**Comment by WenmuZhou** [comment]
> 另外在折腾自动标注的时候还发现一个小问题，就是如果输入的图片高度小于32，那么使用自动标注的时候会报如下错误：
> `Using model from paddle invalid input 'img' in NormalizeImage Traceback (most recent call last): File "/home/ricardo/code/PaddleOCR/PPOCRLabel/libs/autoDialog.py", line 37, in run self.result_dic = self.ocr.ocr(Imgpath, cls=True, det=True) File "../paddleocr.py", line 300, in ocr dt_boxes, rec_res = self.__call__(img) File "../tools/infer/predict_system.py", line 89, in __call__ dt_boxes, elapse = self.text_detector(img) File "../tools/infer/predict_det.py", line 157, in __call__ data = transform(data, self.preprocess_op) File "../ppocr/data/imaug/__init__.py", line 38, in transform data = op(data) File "../ppocr/data/imaug/operators.py", line 82, in __call__ np.ndarray), "invalid input 'img' in NormalizeImage" AssertionError: invalid input 'img' in NormalizeImage `
> 一开始直接拿人工标注之后的文本图片（从原图中把检测框裁剪出来）来做自动标注就报这个错，然后就翻了一下源码，问题应该是因为在检测模型中，对原图做预处理的时候调用了[operators.py](https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/ppocr/data/imaug/operators.py#L115)里面的`DetResizeForTest`的`__call__`方法，然后调用`resize_image_type0`方法，里面的`resize_h = int(round(resize_h / 32) * 32)`会导致高度小于32的所有图片的`resize_h`变为0，然后触发后面的返回`None`。
> 而后面的预处理方法`NormalizeImage`没有处理这种输入，而是直接raise了一个`AssertionError: invalid input 'img' in NormalizeImage`。这样会导致因为文件夹里的某个高小于32的样本而中断整个自动标注过程，我觉得是不是应该加一些逻辑处理一下这个异常，让自动标注跳过这些不符合高/宽的样本，而不影响其他的样本的自动标注。

#1992 fixed in this
