### ISSUE TITLE
pdserving  一直部署不成功

### ISSUE THREAD

**Issue by Ming-Zhou0201** [PaddlePaddle/PaddleOCR#1733]
https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving  这个文档有更新过后的吗？pdserving client app server 不知道到底哪里不对，一直部署不成功，或者有没有docker image?
hubserving  部署没有问题

部署环境：
paddle-serving-app        0.2.0
paddle-serving-client     0.4.0
paddle-serving-server-gpu 0.4.0.post10
paddlepaddle-gpu          2.0.0rc1

**Comment by tink2123** [comment]
文档已更新：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/pdserving/README_CN.md

可以参考这个步骤部署
