### ISSUE TITLE
关于DB文本检测模型检测弯曲文本的问题

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/PaddleOCR#1739]
你好，我在使用DB文本检测模型有几个问题想确认一下：
1.目前PaddleOCR的DB模型应该是支持训练弯曲文本检测模型的吧？只要保证文本框的关键点数量一致就行了吧？
2.得到训练之后的DB模型在进行预测的时候发现无法检测，我看了一下db_postprocess.py这里面经过后处理之后返回的好像都是四边形的坐标，如果我修改一下这个后处理代码是否就能支持检测弯曲文本了呢？

**Comment by WenmuZhou** [comment]
是的，修改一下后处理就可以了

**Comment by xiulianzw** [comment]
好的，谢谢大神回复

**Comment by aleaaaa** [comment]
请问db_postprocess.py具体怎么修改的吗

**Comment by xiulianzw** [comment]
你看一下box_score_fast里面的封装方法应该就能看明白了，如果你直接改的话可能会影响文字识别的效果，你自己测试看看吧。可能后面需要加入插值方法或者透视变换等，看你弯曲文本的弯曲幅度了，幅度大(例如印章的圆弧文字)的话建议直接放弃DB吧，可以去了解一下ABCNet或者其他的算法
