### ISSUE TITLE
在eval的时候出现这个错误

### ISSUE THREAD

**Issue by bleakie** [PaddlePaddle/PaddleOCR#174]
File "PaddleOCR/ppocr/utils/character.py", line 96, in decode
    char_list.append(self.character[(text_index[idx])])
TypeError: list indices must be integers or slices, not numpy.float32
在对训练好的模型进行测试时，时而出现这个错误，而且，同一个模型多次调用，有时成功几次，有时出现error，这是什么原因呢？

**Comment by LDOUBLEV** [comment]
你的代码是最新的吗，代码库的代码是 ：char_list.append(self.character[text_index[idx]]) 你的代码里好像多了一个括号？

问题好像是你的索引超过了character的长度，可以调试检查下，比如把96行改为：
```
print("character 96 line -- character index: {}   character length: {}".format(text_index[idx]], len(self.character)))
char_list.append(self.character[text_index[idx]])
```

**Comment by bleakie** [comment]
错误原因已找到：多了()，感谢！
