### ISSUE TITLE
不明错误

### ISSUE THREAD

**Issue by arnozeng** [PaddlePaddle/PaddleOCR#1740]
训练自己准备的数据时，报了如下错误。按照训练教程操作，未发现问所在。请问有碰到类似问题的解决方式吗？
这是错误日志：
[workerlog.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5812319/workerlog.txt)
![error](https://user-images.githubusercontent.com/64408767/104545068-2f95d900-5664-11eb-9f19-3fe0e7ba91ca.jpg)

eval model:: 100%|█████████▉| 2853/2860 [01:14<00:00, 36.96it/s]
eval model:: 100%|█████████▉| 2857/2860 [01:14<00:00, 37.72it/s]INFO 2021-01-14 12:20:26,187 launch_utils.py:308] terminate all the procs
ERROR 2021-01-14 12:20:26,187 launch_utils.py:546] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-01-14 12:20:29,191 launch_utils.py:308] terminate all the procs

**Comment by LDOUBLEV** [comment]
在训练的时候打开--log_dir参数，报错的时候看下log_dir里的日志
```
python3.7 -m paddle.distributed.launch --gpus '0,1,2,3' --log_dir 'debug/'  tools/train.py -c ....
```

也可以尝试把eval的batch_size 调小一些

**Comment by arnozeng** [comment]
> 在训练的时候打开--log_dir参数，报错的时候看下log_dir里的日志
> 
> ```
> python3.7 -m paddle.distributed.launch --gpus '0,1,2,3' --log_dir 'debug/'  tools/train.py -c ....
> ```
> 
> 也可以尝试把eval的batch_size 调小一些


经测试，把batch_size调到1，也是不行。 GPU 是1080TI 11g, cpu为16G. 错误没有提示其他日志

**Comment by littletomatodonkey** [comment]
你好，减小bs的同时，把Train和Eval的num_workers都改为0吧

https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L102

**Comment by arnozeng** [comment]
问题未解决

**Comment by YY007H** [comment]
楼主解决了吗？我也有这个问题

**Comment by abnercloud** [comment]
单个GPU时，是 --gpus '0' ，而不是    --gpus '0, '
