### ISSUE TITLE
批量生成图片时StyleText如何保存style的背景图片“fake_bg”

### ISSUE THREAD

**Issue by sjtugzx** [PaddlePaddle/PaddleOCR#1742]
你好，
如题，再批量生成图片时，如何保存生成的fake_bg。

**Comment by littletomatodonkey** [comment]
你好，下面这里，这样就可以拿到fake_bg的信息

```
fake_bg = synth_result["fake_bg"]
```

https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/StyleText/engine/synthesisers.py#L68
