### ISSUE TITLE
关于dygraph分支中，识别模型训练，要使用数据增强应该如何设置？

### ISSUE THREAD

**Issue by liuzard** [PaddlePaddle/PaddleOCR#1744]
在以前的develop分支，在识别模型的训练中可以设置desort参数，在dygraph分支中应该如何设置呢？谢谢！

**Comment by littletomatodonkey** [comment]
你好，可以设置use_tia和aug_prob这两个参数，use_tia表示是否tia数据增广，aug_prob表示每个数据增广操作的概率，为0的话，表示不使用数据增广，否则按照该概率对图片进行数据增广

https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/ppocr/data/imaug/rec_img_aug.py#L38


对应配置文件可以在这里添加字段

```
- RecAug:
  - use_tia: True
  - aug_prob: 0.4
```

https://github.com/PaddlePaddle/PaddleOCR/blob/17346d854e90e95decdc8585479924d9cb03831c/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L72

**Comment by FoneMobius** [comment]
应该这样的，use_tia和aug_prob前面没有横杠
#- RecAug: null
    - RecAug:
        use_tia: True
        aug_prob: 0.4
