### ISSUE TITLE
paddleOCR对华为服务器的支持

### ISSUE THREAD

**Issue by Qggg** [PaddlePaddle/PaddleOCR#1748]
在微信群里提问没人吭声
之前看到百度和华为联手AI的报道
请问PaddleOCR是否支持在华为鲲鹏920CPU上部署？是否支持atlas300推理卡？

**Comment by LDOUBLEV** [comment]
问了下，目前paddle的预测库是支持华为鲲鹏920CPU的，但是OCR还没在这些芯片上试过

**Comment by Qggg** [comment]
OK
