### ISSUE TITLE
F:\android_demo\app\src\main\cpp\ocr_clipper.cpp:1052:5: error: cannot use 'throw' with exceptions disabled

### ISSUE THREAD

**Issue by victorlea** [PaddlePaddle/PaddleOCR#1749]
大家有没有遇到这个问题啊，就加了一个静态库。

**Comment by tink2123** [comment]
没有遇到过类似问题，可以提供一下可复现代码。这个issue先暂时关闭，如有问题可以reopen或提交新的issue讨论。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
