### ISSUE TITLE
PaddleOCR-dygraph多卡并行程序直接被杀死

### ISSUE THREAD

**Issue by chenxinhua** [PaddlePaddle/PaddleOCR#1750]
执行python3 -m paddle.distributed.launch --gpus='0,1,2,3'  tools/train.py -c configs/det/det_mv3_db.yml -o Optimizer.base_lr=0.0001，直接显示被杀死。
-----------  Configuration Arguments -----------
gpus: 0,1,2,3
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/det/det_mv3_db.yml', '-o', 'Optimizer.base_lr=0.0001']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-01-16 18:17:20,265 launch.py:314] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-01-16 18:17:20,267 launch_utils.py:472] Local start 4 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55457               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:43859,127.0.0.1:53163,127.0.0.1:44137|
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-01-16 18:17:20,267 launch_utils.py:476] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log.
已杀死

**Comment by chenxinhua** [comment]
>>> import paddle
>>> paddle.utils.run_check()
发现. NVIDIA-NCCL2 is not installed correctly on your system.
参照nivdia官网安装即可。

**Comment by YY007H** [comment]
我这都安装了，还是报这个错误

**Comment by ddz-mark** [comment]
同样出现这个问题，多卡训练时被杀死，单卡训练是可以的
