### ISSUE TITLE
请问paddleocr有能够区分大小写的英文识别模型吗?

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleOCR#1753]
目前没有在github上发现,都是识别为小写的,改了代码内的字典也没有变化, 
所以如果有的话麻烦发一下链接给我,
如果官方目前没有提供的话,麻烦提供一下训练文字识别模型的例子(手册),我自己试着进行训练,谢谢

**Comment by WenmuZhou** [comment]
这个我们这边没有训练，你可以自己训练并在这个字典里加上大写字母就行
