### ISSUE TITLE
发现小图的识别率很低，除了重新训练还有别的办法提供识别率吗？

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#1756]
这些是测试图，识别效果很差
![img_crop_出生](https://user-images.githubusercontent.com/15188456/104865927-4005c680-5978-11eb-9bf5-36dabc6360e6.png)
![img_crop_公民身份证号码](https://user-images.githubusercontent.com/15188456/104865928-4136f380-5978-11eb-8288-32ed3d54f5d3.png)
![img_crop_名族](https://user-images.githubusercontent.com/15188456/104865932-41cf8a00-5978-11eb-89b3-79ff7ea88512.png)
![img_crop_姓别](https://user-images.githubusercontent.com/15188456/104865938-4431e400-5978-11eb-9a87-6d51682eeb75.png)
![img_crop_姓名](https://user-images.githubusercontent.com/15188456/104865944-46943e00-5978-11eb-9306-0329ae8ba7cb.png)
![img_crop_住址](https://user-images.githubusercontent.com/15188456/104865951-485e0180-5978-11eb-9d14-9612fd85838d.png)

**Comment by WenmuZhou** [comment]
没有其他好办法了

**Comment by piaobuliao** [comment]
1) 字体颜色可能会影响识别，弄成灰度图试试
2) 底纹干扰，高斯模糊下试试
3）上下留白比较多可能都会导致识别不好，上下cut掉部分
