### ISSUE TITLE
 root ERROR: When parsing line icdar_c4_train_imgs/img_832.jpg , error happened with msg: name 'Polygon' is not defined

### ISSUE THREAD

**Issue by michael-malu** [PaddlePaddle/PaddleOCR#1757]
root ERROR: When parsing line icdar_c4_train_imgs/img_832.jpg [{"transcription": "###", "points": [[232, 489], [249, 471], [252, 487], [236, 504]]}, {"transcription": "###", "points": [[298, 236], [346, 234], [346, 246], [298, 247]]}, {"transcription": "###", "points": [[548, 267], [600, 264], [601, 282], [549, 285]]}, {"transcription": "###", "points": [[639, 206], [715, 206], [713, 220], [638, 220]]}, {"transcription": "###", "points": [[461, 234], [512, 230], [509, 242], [458, 247]]}, {"transcription": "###", "points": [[862, 47], [900, 21], [900, 58], [862, 85]]}, {"transcription": "MARC", "points": [[800, 92], [855, 54], [860, 88], [803, 125]]}, {"transcription": "###", "points":
[[310, 69], [330, 68], [330, 96], [310, 97]]}, {"transcription": "###", "points": [[310, 486], [351, 475], [355, 486], [314, 496]]}, {"transcription": "###", "points": [[801, 223], [847, 226], [849, 239], [804, 237]]}, {"transcription": "###", "points": [[908, 12], [924, 0], [967, 2], [913, 44]]}, {"transcription": "###", "points": [[0, 248], [25, 249], [24, 260], [0, 259]]}, {"transcription": "###", "points": [[711, 213], [761, 211], [763, 219], [713, 221]]}]
, error happened with msg: name 'Polygon' is not defined

**Comment by WenmuZhou** [comment]
提供一下可复现的脚本哈

**Comment by michael-malu** [comment]
> 提供一下可复现的脚本哈

你好 我用的是paddleocr_dygraph 分支下的train.py 去训练定位模型，数据集是icdar2015，paddle 版本是2.0.0rc1,
训练识别模型是正常运行的

**Comment by WenmuZhou** [comment]
训练数据和对应的训练配置文件打包一份上传一下

**Comment by michael-malu** [comment]
[text_localization.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5833818/text_localization.zip)
[det_mv3_db.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5833826/det_mv3_db.txt)
你好 图太大了 就没传，只上传了label

**Comment by michael-malu** [comment]
2.0.0rc1 GPU 版本程序 肯定有问题，报polygon未定义，那我把polygon 字段加到label中去，依然报，然后 我用一张图片，一个label 直接跑通了，然后再把这个图以及对应的label拷一份，重命名，组成一个两张图的数据集，结果第二个就报polygon未定义

**Comment by tink2123** [comment]
可以更新一下代码，使用release2.1分支试试。
