### ISSUE TITLE
paddleOCR训练3通道黑白图像，效果极差。

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleOCR#1759]
做车牌“检测”，如果是彩色图像，500代收敛效果良好。但是，图像换成三通道灰度图像，recall值特别低，2000代后只有0.02，训练集：1000张，测试集：50张，是什么原因呢？

**Comment by WenmuZhou** [comment]
测试的时候是否也换了三通道灰度图像

**Comment by stefan-567** [comment]
> 测试的时候是否也换了三通道灰度图像

测试图片也是三通道灰度图，检查过了，没有问题
