### ISSUE TITLE
SimpleReader 对输入img_shape[0]等于1时不支持

### ISSUE THREAD

**Issue by maplehan2009** [PaddlePaddle/PaddleOCR#176]
当参数 Global/image_shape 设为灰度图，例如 [1, 32, 320]时，SimpleReader的处理逻辑和resize_norm_img有些冲突

SimpleReader 中的 sample_iter_reader 函数里，一定会将img channels设为3，不管image_shape是如何设置的。

而 resize_norm_img 中，是有考虑image_shape[0]==1时的逻辑，即将灰度图再扩充一个维度

但是当image_shape[0]设为1时，两者串在一起使用会有矛盾，导致报错

**Comment by tink2123** [comment]
感谢反馈，会尽快修复

**Comment by dyning** [comment]
已修复。
