### ISSUE TITLE
空格问题：中英文通用模型，英文能识别空格，是因为生成了一批带空格的英文文本数据么？

### ISSUE THREAD

**Issue by wksuixin** [PaddlePaddle/PaddleOCR#1761]

**Comment by WenmuZhou** [comment]
能识别空格是因为生产了一批带空格的数据

**Comment by lgcy** [comment]
> 能识别空格是因为生产了一批带空格的数据

2.0版本的中英混合模型是支持空了吗

**Comment by DuckJ** [comment]
> 能识别空格是因为生产了一批带空格的数据

@WenmuZhou 你好，请教一下，请问生成的带空格数据是中英混合的数据还是纯英文带空格数据呀？
支持空格模型的训练是用这批带空格数据finetune的吗？还有就是finetune的时候用中文的数据了吗
