### ISSUE TITLE
PaddleOCR请问如何使用分类模型区分手写字体或者打印体。

### ISSUE THREAD

**Issue by theowl13** [PaddlePaddle/PaddleOCR#1764]
初次接触PaddleOCR有很多不懂得，望各位大佬看到后指点一二。

是这样，我遇到了需要同时识别印刷体和手写文字的情况，
     看到了QA中提到的解决方案:**共用检测模型，使用二分类模型区分手写字体或打印体，从而可以分别使用针对手写体或打印体不同的识别模型**
      这里我有一些问题：1、PaddleOCR支持用户自己在检测模型、识别模型、方向分类器之外，再加一个分类模型么？如果可以我怎样才能添加这个模型呢
      2、我怎么才能分别使用两个识别模型？可以通过配置吗，还是需要修改PaddleOcr一些工具的结构了？

**Comment by MissPenguin** [comment]
印刷手写分类模型本质和文字方向分类模型是一样的，你可以单独再增加一个分类器，或者重新训练文本方向分类器，让其具备手写印刷分类的功能，这样避免堆砌一堆模型。要额外增加模型的话，最好先熟悉文本方向分类器的训练，以及如何嵌入到整个系统，然后用类似的方式集成。

**Comment by xlihub** [comment]
请问重新训练文本方向分类器有相关的教程参考吗？在文字方向分类器中，添加其他维度的分类标签，需要怎样去准备训练数据和标记，例如同时预测产生[高铁票,0度]两种分类信息

**Comment by xlihub** [comment]
> 印刷手写分类模型本质和文字方向分类模型是一样的，你可以单独再增加一个分类器，或者重新训练文本方向分类器，让其具备手写印刷分类的功能，这样避免堆砌一堆模型。要额外增加模型的话，最好先熟悉文本方向分类器的训练，以及如何嵌入到整个系统，然后用类似的方式集成。

请问重新训练文本方向分类器有相关的教程参考吗？在文字方向分类器中，添加其他维度的分类标签，需要怎样去准备训练数据和标记，例如同时预测产生[高铁票,0度]两种分类信息

**Comment by CaesarRyan** [comment]
请问您的问题解决了吗，有什么好的方案吗？

**Comment by zbximo** [comment]
请问这个问题解决了吗？ @theowl13

**Comment by nissansz** [comment]
手写用哪个yml配置文件训练？
