### ISSUE TITLE
rec 训练一个epoch后，训练进程结束了

### ISSUE THREAD

**Issue by kruskr** [PaddlePaddle/PaddleOCR#1766]
![QQ截图20210119145005](https://user-images.githubusercontent.com/16792045/104998119-a87ea180-5a65-11eb-8a7c-0c8b1533d258.jpg)
![image](https://user-images.githubusercontent.com/16792045/104998053-913fb400-5a65-11eb-9e1e-0e55d2894d8f.png)

**Comment by kruskr** [comment]
Process finished with exit code -1073741819 (0xC0000005)

**Comment by just-automatic** [comment]
我也是

**Comment by zhaopu0710** [comment]
我也是

**Comment by just-automatic** [comment]
我怎么感觉是某个地方发生了错误, 但是并没有打印到log里去

**Comment by zhaopu0710** [comment]
我换paddle1.85了。就ok了

**Comment by littletomatodonkey** [comment]
可以把bs调小一点，或者使用dygaph分支的代码+paddle2.0.0rc1

**Comment by zhaopu0710** [comment]
> 可以把bs调小一点，或者使用dygaph分支的代码+paddle2.0.0rc1

我今天开始就用的2.0+dygaph，然后就出现了一个问题。我也试过把bs调小了，调到2也不行。

**Comment by just-automatic** [comment]
> 我换paddle1.85了。就ok了

非常棒, 安装 `gitee` 上的老版本配合 `1.8.5` 可以完美运行, 应该是开发团队新版本出现了灾难性 `bug`

**Comment by littletomatodonkey** [comment]
> > 可以把bs调小一点，或者使用dygaph分支的代码+paddle2.0.0rc1
> 
> 我今天开始就用的2.0+dygaph，然后就出现了一个问题。我也试过把bs调小了，调到2也不行。

贴一下报错信息吧，num worker调小也不行吗？

**Comment by just-automatic** [comment]
> > > 可以把bs调小一点，或者使用dygaph分支的代码+paddle2.0.0rc1
> > 
> > 
> > 我今天开始就用的2.0+dygaph，然后就出现了一个问题。我也试过把bs调小了，调到2也不行。
> 
> 贴一下报错信息吧，num worker调小也不行吗？

我昨天 `num_worker` 设置为 `4` 和 `2` 的时候也有这个问题

**Comment by zhaopu0710** [comment]
> > > 可以把bs调小一点，或者使用dygaph分支的代码+paddle2.0.0rc1
> > 
> > 
> > 我今天开始就用的2.0+dygaph，然后就出现了一个问题。我也试过把bs调小了，调到2也不行。
> 
> 贴一下报错信息吧，num worker调小也不行吗？

没有报错信息，就和上面截图一样。到第一个`epoch`的最后一个`iter`时，直接终止。`num worker` 设置`1`还是不行。
![image](https://user-images.githubusercontent.com/50993924/105161779-b824e580-5b4c-11eb-84bf-0e1ee3b879bc.png)

**Comment by kruskr** [comment]
bs调小，2.0+dygraph,换成3.6的Python居然可以了，玄了

**Comment by just-automatic** [comment]
> bs调小，2.0+dygraph,换成3.6的Python居然可以了，玄了

请问呢是python3.6.几呢, 还有你的bs设置的多少

**Comment by kruskr** [comment]
> 请问呢是python3.6.几呢, 还有你的bs设置的多少

python         3.6.12
paddlepaddle         2.0.0rc1
bs          25
试过64的bs也是可以的

**Comment by zhaopu0710** [comment]
> > 请问呢是python3.6.几呢, 还有你的bs设置的多少
> 
> python 3.6.12
> paddlepaddle 2.0.0rc1
> bs 25
> 试过64的bs也是可以的

换了还是不行0.0

**Comment by just-automatic** [comment]
> > > 请问呢是python3.6.几呢, 还有你的bs设置的多少
> > 
> > 
> > python 3.6.12
> > paddlepaddle 2.0.0rc1
> > bs 25
> > 试过64的bs也是可以的
> 
> 换了还是不行0.0

哎, 放弃吧 :(

**Comment by just-automatic** [comment]
时隔 14 天, 来重新说一下: 在 `tools/program.py` 中的 `train()` 函数中, 在 `enumerate` 循环末尾加入 
```python
if len(train_dataloader) == idx + 1:
    break
```
能够正常退出本次循环, 进入下次循环, 否则由 `enumerate` 自行结束会触发问题

具体原因并不明确, 因为创建迭代器的核心函数 `create_py_reader` 代码在 `core_avx.pyd` 中, 没有研究过这类文件, 或许开发者能够解答一下

**Comment by simplew2011** [comment]
这个问题，我在win10上训练CCPD车牌识别时复现了，在每次训练到第一轮结束后，程序自动结束Process finished with exit code -1073741819 (0xC0000005)。修改batch和num_workers无效。
相同代码在另一个pycharm conda env下是可以正常训练的。
所以对比了两个虚拟环境的依赖，逐个更新对比，发现是scipy库导致的，在1.5.3时报错，1.3.1不报错。

**Comment by annzheng** [comment]
> 这个问题，我在win10上训练CCPD车牌识别时复现了，在每次训练到第一轮结束后，程序自动结束Process finished with exit code -1073741819 (0xC0000005)。修改batch和num_workers无效。
> 相同代码在另一个pycharm conda env下是可以正常训练的。
> 所以对比了两个虚拟环境的依赖，逐个更新对比，发现是scipy库导致的，在1.5.3时报错，1.3.1不报错。

可行，感谢

**Comment by yz-yang** [comment]
> 这个问题，我在win10上训练CCPD车牌识别时复现了，在每次训练到第一轮结束后，程序自动结束Process finished with exit code -1073741819 (0xC0000005)。修改batch和num_workers无效。 相同代码在另一个pycharm conda env下是可以正常训练的。 所以对比了两个虚拟环境的依赖，逐个更新对比，发现是scipy库导致的，在1.5.3时报错，1.3.1不报错。

解决，感谢！

**Comment by dawaer** [comment]
> 这个问题，我在win10上训练CCPD车牌识别时复现了，在每次训练到第一轮结束后，程序自动结束Process finished with exit code -1073741819 (0xC0000005)。修改batch和num_workers无效。 相同代码在另一个pycharm conda env下是可以正常训练的。 所以对比了两个虚拟环境的依赖，逐个更新对比，发现是scipy库导致的，在1.5.3时报错，1.3.1不报错。

靠谱
