### ISSUE TITLE
padleocr编译出错

### ISSUE THREAD

**Issue by dreamercv** [PaddlePaddle/PaddleOCR#1769]
/root/share/PaddleOCR/deploy/cpp_infer/include/ocr_cls.h:63:28: error: template argument 1 is invalid
   std::shared_ptr<Predictor> predictor_;
                            ^
In file included from /root/share/PaddleOCR/deploy/cpp_infer/src/main.cpp:32:0:
/root/share/PaddleOCR/deploy/cpp_infer/include/ocr_rec.h:35:17: error: ‘paddle_infer’ is not a namespace-name
 using namespace paddle_infer;
                 ^
/root/share/PaddleOCR/deploy/cpp_infer/include/ocr_rec.h:35:29: error: expected namespace-name before ‘;’ token
 using namespace paddle_infer;
                             ^
/root/share/PaddleOCR/deploy/cpp_infer/include/ocr_rec.h:69:19: error: ‘Predictor’ was not declared in this scope
   std::shared_ptr<Predictor> predictor_;
                   ^
/root/share/PaddleOCR/deploy/cpp_infer/include/ocr_rec.h:69:28: error: template argument 1 is invalid
   std::shared_ptr<Predictor> predictor_;
                            ^
CMakeFiles/ocr_system.dir/build.make:101: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_cls.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_cls.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/ocr_system.dir/build.make:114: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_det.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_det.o] Error 1
CMakeFiles/ocr_system.dir/build.make:127: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_rec.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_rec.o] Error 1
CMakeFiles/ocr_system.dir/build.make:88: recipe for target 'CMakeFiles/ocr_system.dir/src/main.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/main.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
==============================
我用的paddle预测库是ubuntu14.04_cuda10.0_cudnn7_avx_mkl_gcc482 1.8.5的版本，在编译paddleocr出现了如上错误，请问该如何解决

**Comment by littletomatodonkey** [comment]
你好，这个需要使用2.0.0rc1版本的预测库

**Comment by dreamercv** [comment]
请问对paddleocr的版本有有要求嘛

**Comment by fujianhai** [comment]
你们gcc4.8.2的编译的库不提供了吗？cpp里面库的名字也不统一，fluid_inference.tgz 和 paddle_inference.tgz， @littletomatodonkey
