### ISSUE TITLE
3080 3090 显卡

### ISSUE THREAD

**Issue by gdwu1427** [PaddlePaddle/PaddleOCR#1772]
您好!
      3080 3090显卡能适配使用吗？或者有没有计划更新支持cuda11.

**Comment by tink2123** [comment]
30系列显卡需要有CUDA11.1, Paddle 暂时没有发布cuda11.1 的whl包，可以自己使用源码编译，或者等待Paddle2.0的发布。

**Comment by gdwu1427** [comment]
谢谢！

**Comment by gdwu1427** [comment]
你好，有源码编译cuda11.1的whl包的教程吗 @tink2123
