### ISSUE TITLE
运行案例报错：ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by 554518983** [PaddlePaddle/PaddleOCR#1773]
执行命令：
 python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
报错信息：
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 23, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by tink2123** [comment]
需要安装相关依赖
在PaddleOCR目录下：
pip3 install -r requirements.txt

**Comment by 554518983** [comment]
谢谢

**Comment by Notemo9** [comment]
不行
