### ISSUE TITLE
显存问题：1、OCR模型中，检测、判断、识别三个模型分别推理的时候的显存相加 比 三个模型一起使用的时候显存要小很多

### ISSUE THREAD

**Issue by wksuixin** [PaddlePaddle/PaddleOCR#1775]

**Comment by wksuixin** [comment]
显存问题：
1、OCR模型中，检测、判断、识别三个模型分别推理的时候的显存相加 比 三个模型一起使用的时候显存要小很多，是什么原因？
2、如果初始化时，是一张最大的图显存可能占用4G，再跑其它图像显存也不会增加；如果用一张小图初始化，再跑之前的大图，显存就可能超过4G；造成这个问题的原因是什么？显存分配的时候是需要多少就开多少显存？还是开的显存会比需要的显存大一些？开显存的策略是什么呀？

**Comment by tink2123** [comment]
会预先分配一些显存，如果不够用了就会继续增长。

请问显存问题现在是否影响您的使用了呢？我们会反馈给预测团队。

**Comment by wksuixin** [comment]
> 会预先分配一些显存，如果不够用了就会继续增长。
> 
> 请问显存问题现在是否影响您的使用了呢？我们会反馈给预测团队。

想问一下增长有没有增长策略？是需要多少就增长多少？还是增长的比需要的大一些？

**Comment by tink2123** [comment]
会存在增长比需要稍大的情况

**Comment by wksuixin** [comment]
> 会存在增长比需要稍大的情况

可以设置为按需要多少增长多少么？

**Comment by wksuixin** [comment]
> > 会存在增长比需要稍大的情况
> 
> 可以设置为按需要多少增长多少么？

我这边可以通过配置GPU的使用方法来控制么？

**Comment by tink2123** [comment]
可以试下这个 export FLAGS_allocator_strategy='auto_growth'
