### ISSUE TITLE
训练时有何方法提高GPU利用率

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1776]
由于显存容易爆，减小batch_size。但是GPU利用率才0.4，有什么方法不爆显存又提高GPU利用率来加快训练速度。

**Comment by tink2123** [comment]
增大num_worker的个数，多进程可以提升利用率。

**Comment by singlebear** [comment]
> 增大num_worker的个数，多进程可以提升利用率。
加大这个，速度能增加点，但还是用不满，而且又会导致爆内存。之前提过这个issues，但是没回复。
https://github.com/PaddlePaddle/PaddleOCR/issues/1665

**Comment by LDOUBLEV** [comment]
你使用develop分支的代码训练的吗，静态图的reader机制有点问题，现在动态图（dygraph）分支训练GPU利用率还挺高的，感兴趣可以尝试下

**Comment by singlebear** [comment]
> 你使用develop分支的代码训练的吗，静态图的reader机制有点问题，现在动态图（dygraph）分支训练GPU利用率还挺高的，感兴趣可以尝试下

对的，谢谢，我去试下。
