### ISSUE TITLE
编译paddle出现的问题

### ISSUE THREAD

**Issue by dreamercv** [PaddlePaddle/PaddleOCR#1779]
我在编译paddle1.8.5的时候出现`c++: internal compiler error: Killed (program cc1plus)`，据说是在编译过程中，内存溢出的问题，可是我的服务器内存如下
```
Every 1.0s: free -m                                                              Wed Jan 20 17:25:45 2021

              total        used        free      shared  buff/cache   available
Mem:         128566      127080         348         229        1137         115
Swap:             0           0           0

```
请问这该怎么解决

**Comment by LDOUBLEV** [comment]
看上去你空余的内存确实不多了，把其他占空间的进程杀掉空出来一些内存重新编译看看，或者换一个机器

**Comment by dreamercv** [comment]
100多g的内存都是我用在了编译上，感觉有点不可思议

**Comment by tink2123** [comment]
可以拉最新的代码重新编译试试，如还有问题，可以去PaddlePaddle/Paddle repo下提一个issue：https://github.com/PaddlePaddle/Paddle/issues
