### ISSUE TITLE
PPOCRLabel保存识别结果直接崩溃

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#1787]
目录下只有30张图片，点保存时报下面这个错误：
OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3143: error: (-215:Assertion failed) _src.total() > 0 in function 'cv::warpPerspective'
报错是随机的，不特定哪个图片

**Comment by YY007H** [comment]
找到问题了，这里不知道为啥操作img会变成None，建议这里加个判断
![QQ图片20210121145524](https://user-images.githubusercontent.com/15188456/105315487-5cb13100-5bfa-11eb-88fb-c8b315fbba09.png)

**Comment by Evezerest** [comment]
感谢您的反馈，您是否有修改过软件输出文件的相关内容呢？由于我们没有遇到过这个问题，您能否将场景详细描述一下，或将解决方案PR到repo中？

**Comment by WenmuZhou** [comment]
这个none可能是因为路径之类的问题，比如他win下的中文路径

**Comment by YY007H** [comment]
> 感谢您的反馈，您是否有修改过软件输出文件的相关内容呢？由于我们没有遇到过这个问题，您能否将场景详细描述一下，或将解决方案PR到repo中？

运行后，有张图片不对，然后删除图片时应用崩溃了，重启后，再生成数据集时候就报这个错了

**Comment by Evezerest** [comment]
> > 感谢您的反馈，您是否有修改过软件输出文件的相关内容呢？由于我们没有遇到过这个问题，您能否将场景详细描述一下，或将解决方案PR到repo中？
> 
> 运行后，有张图片不对，然后删除图片时应用崩溃了，重启后，再生成数据集时候就报这个错了

应该是在外部把图片删掉了吧，此时软件里还有这个图片路径，所以再此读取的时候就错了。实际上可以直接在软件里点击删除图片。后续我们修复一下。
