### ISSUE TITLE
cpu version hubserving docker 

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleOCR#1788]
In the [dockerfile](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/docker/hubserving/cpu/Dockerfile) of hubserving/cpu, the base image is from paddle-gpu

> FROM hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev

I checked the docker images of paddle form dockerhub, and it seems most images support gpu and only version below paddlepaddle/paddle:1.8.3 support cpu.

Any plans to release docker images of paddle which support cpu only ? (Those gpu versions are too large, most are beyond 4Gb)

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/1801
