### ISSUE TITLE
Online demo has better result than local installation

### ISSUE THREAD

**Issue by chuk-yong** [PaddlePaddle/PaddleOCR#1790]
paddlepaddle==2.0.0rc1
paddleocr 2.02

Hi!  I put in the same image through the online demo (https://www.paddlepaddle.org.cn/hub/scene/ocr) and running the code locally.  The online version has a better result!  

What could be the problem with the recognition?  Can I change the recognition model?  I tried setting rec_algorthm = "SRN" but it said I can only use CRNN

**Comment by LDOUBLEV** [comment]
First, the online and offline models may be inconsistent or the hyperparameters may be different. Can I ask
which model do you use for online and offline testing?

Currently we only support DB + CRNN for Chinese recognition.

**Comment by chuk-yong** [comment]
I just use the default settings.

I can change the model if I am using it for English recognition?

**Comment by chuk-yong** [comment]
I am doing a project to read hand-engraved text on metallic surfaces.  Of all the tools, Google Vision did well and PaddleOCR is quite close.  I was hoping to try out different settings to see if I can get it to perform better.

**Comment by LDOUBLEV** [comment]
> I just use the default settings.
> 
> I can change the model if I am using it for English recognition?

We provide [English detection and recognition model](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/algorithm_overview_en.md), and the [Chinese model](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-20-series-model-listupdate-on-dec-15) we provide also supports English recognition.  BTW, the server model has better recognition performance than the mobile model.
