### ISSUE TITLE
No matching distribution found for opencv-python==4.2.0.32

### ISSUE THREAD

**Issue by 4ft35t** [PaddlePaddle/PaddleOCR#1791]
Python 3.9.1
pip 20.2.2 from /usr/lib/python3.9/site-packages/pip (python 3.9)

```py
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from paddleocr) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48)
ERROR: No matching distribution found for opencv-python==4.2.0.32 (from paddleocr)
```

**Comment by 4ft35t** [comment]
Python 3.7.9 也是同样问题

**Comment by LDOUBLEV** [comment]
你本地没有安装opencv吧，安装4.2.0.32 版本的opencv-python看下

**Comment by WenmuZhou** [comment]
https://mirror.baidu.com/pypi/simple  使用百度源

**Comment by 4ft35t** [comment]
> https://mirror.baidu.com/pypi/simple 使用百度源

`python -m pip install opencv-python==4.2.0.32 -i https://mirror.baidu.com/pypi/simple`
确认有效

**Comment by OwO1** [comment]
目前百度也没有了

**Comment by dkw-wkd** [comment]
> > https://mirror.baidu.com/pypi/simple 使用百度源
> 
> `python -m pip install opencv-python==4.2.0.32 -i https://mirror.baidu.com/pypi/simple` 确认有效

过期了，链接进去是空的 有新的镜像源吗
