### ISSUE TITLE
近期会发布新版吗？

### ISSUE THREAD

**Issue by scfw** [PaddlePaddle/PaddleOCR#1792]
离线版本能达到线上demo的识别效果吗

**Comment by LDOUBLEV** [comment]
目前离线版本就是mobile系列模型，你说的线上demo识别效果指的是使用server模型？

我们也会不断迭代模型，近期没有新模型发布排期

**Comment by scfw** [comment]
mobile模型和server模型目前有什么区别呢？server模型可以离线使用吗？

**Comment by MissPenguin** [comment]
mobile模型基于mobilenetV3的骨干网络，模型更小，速度更快；server模型基于resnet，模型大很多，但效果更好。两者都可离线使用。线上demo展示的是mobile的效果。

**Comment by scfw** [comment]
感谢及时的回复，有server版的线上demo可供测试吗？

**Comment by scfw** [comment]
python版的识别效果等效于c++版吗

**Comment by tink2123** [comment]
server版模型暂时没有线上demo，python识别效果和C++是等效的
