### ISSUE TITLE
数据读取导致程序崩溃的问题

### ISSUE THREAD

**Issue by dgl547437235** [PaddlePaddle/PaddleOCR#1793]
你好，我在windows上进行识别程序训练，发现paddle.io.Dataset读取数据时在最后一次访问数据通道会发生错误，并且无法抓取异常，我的paddle版本是2.0.0rc
![image](https://user-images.githubusercontent.com/31400928/105335233-c4737600-5c12-11eb-985b-c750a990cf76.png)

**Comment by LDOUBLEV** [comment]
在windows上可以尝试把num_workers设置为0

**Comment by dgl547437235** [comment]
你好，把num_workers设置为0 ，并且drop_last设置为Tue之后依然发生如上的错误，我在另外一台windows电脑上也发生了同样的情况

**Comment by WenmuZhou** [comment]
把那个try except 去掉看看

**Comment by studiouspan** [comment]
哈喽，堵哥哥
