### ISSUE TITLE
如何对识别结果进行格式化解析（形成json的key-value pair）

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleOCR#1794]
很多图象中文本是带有结构化语义信息的，
比如说各类票据，不仅需要识别文字具体内容，还得解析出该文字属于哪个字段。

常见的一些方案，
1. 例如身份证识别，根据识别结果的位置以及特定值(比如出现省市，可以判断出其为地址)
2. 通过NLP，进行文本分类
3. 通过预先设置的模板，根据相对位置
4. 通过目标检测，可同时得到位置以及字段类别
5. and so on....

如果可以的话，希望未来能增加 这方面的讨论与描述。

**Comment by LDOUBLEV** [comment]
> 很多图象中文本是带有结构化语义信息的，
比如说各类票据，不仅需要识别文字具体内容，还得解析出该文字属于哪个字段。


目前我们只考虑通用场景，你说的太场景化了，可以自己加一些后处理实现
