### ISSUE TITLE
在原先训练的检测模型上继续训练(比如学习率为0.01),我现在想将学习率改为0.001的话，该怎么做呢？谢谢

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/PaddleOCR#1797]
!python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrain_weights=./output/db_mv3/latest1/ Optimizer.lr.learning_rate=0.001
这是我的代码，继续训练后，发现损失变大了好几倍，训练出的hmean也很低，感觉就是重新训练一样，而不是继续训练

**Comment by WenmuZhou** [comment]
加一个GLobal. load_static_weights=False

**Comment by ahsdx** [comment]
已解决，非常感谢



---原始邮件---
发件人: "zhoujun"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 晚上6:41
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "ahsdx"<2589561091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 在原先训练的检测模型上继续训练(比如学习率为0.01),我现在想将学习率改为0.001的话，该怎么做呢？谢谢 (#1797)




 
加一个GLobal. load_static_weights=False
