### ISSUE TITLE
发生异常: IndexError list index out of range。附图必现

### ISSUE THREAD

**Issue by mbxinye** [PaddlePaddle/PaddleOCR#1798]
![test](https://user-images.githubusercontent.com/10904311/105447163-a2c7cc80-5cae-11eb-97ab-dd805f5a31ee.png)

**Comment by WenmuZhou** [comment]
你好，请问是py预测还是cpp预测会出现

**Comment by mbxinye** [comment]
> 你好，请问是py预测还是cpp预测会出现

py预测，
paddleocr             2.0.2
paddlepaddle          2.0.0rc1

参数设置
PaddleOCR(enable_mkldnn=True,
                                 rec_batch_num=1,
                                 use_space_char=False,
                                 det_db_box_thresh=0.1,
                                 use_gpu=False,
                                 lang="ch")

**Comment by mbxinye** [comment]
试了静态版本没问题。静态版本paddlepaddle1.8.5  paddleocr最新 其他配置不变

**Comment by WenmuZhou** [comment]
试一下最新paddle看看

**Comment by QuantumLiu** [comment]
这个问题设置`use_space_char=False`会有概率出现

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
