### ISSUE TITLE
cuda11.0 Segmentation fault` is detected by the operating system

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#1803]
环境 python3.7.9   镜像 2.0.0rc1-gpu-cuda11.0-cudnn8
docker pull paddlepaddle/paddle:2.0.0rc1-gpu-cuda11.0-cudnn8

系统 centos7.9  显卡驱动 11.2   

>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0123 02:07:17.522380  1816 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0123 02:07:17.528874  1816 device_context.cc:330] device: 0, cuDNN Version: 8.0.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

λ localhost /paddle/PaddleOCR {release/2.0-rc1-0} nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

使用 hub serving start -c deploy/hubserving/ocr_system/config.json 启动 cpu版本没有 问题   换成gpu预测就报

FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1611367356 (unix time) try "date -d @1611367356" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1644 (TID 0x7f069b976740) from PID 0 ***]
我看其他有人反映过这个问题  我不知道是不是 Runtime API Version: 10.2 这个问题 或者驱动高的问题  求指导一下

**Comment by wa3926** [comment]
本来以为 驱动11.2的  cuda一定要安装  11.0 以上版本     cuda版本换成10.2  cudnn 7.6 换一下就好了

**Comment by xiakj** [comment]
@wa3926 我的也是cuda11.0+cudnn8.0，报这个段错误。不知道怎么解决了，我的显卡还是RTX3060

**Comment by wa3926** [comment]
@xiakj   uda版本换成10.2 cudnn 7.6 换一下就好了
