### ISSUE TITLE
文字检测 不明原因退出

### ISSUE THREAD

**Issue by Mr-Zhange** [PaddlePaddle/PaddleOCR#1804]
Windows 10     版本:CPU - 2.0.0rc1
附件是:log 与 yml
链接：https://pan.baidu.com/s/1HrH1yITNGcvb0tZsXghiLw 
提取码：5c04

**Comment by Cllan-z** [comment]
降版本 1.8.5  运行提示:paddle没有seed属性
tools/train.py 第30行
代码是 最新dygraph分支

**Comment by LDOUBLEV** [comment]
dygraph分支需要paddle版本 >=2.0.0rc1 
windows上建议num_workers设置为0
也可以设置断点调试下在哪里出问题的
