### ISSUE TITLE
not find model file path ./inference/ch_ppocr_mobile_v2.0_det_infer/model

### ISSUE THREAD

**Issue by 554518983** [PaddlePaddle/PaddleOCR#1805]
安装环境：window10
安装过程：根据快速安装教程安装，没有使用docker
PaddleOCR：git clone https://gitee.com/paddlepaddle/PaddleOCR 版本是v2.0，使用的是默认分支
运行测试实例报错：2021-01-24 13:39:13,077-INFO: not find model file path ./inference/ch_ppocr_mobile_v2.0_det_infer/model

**Comment by MissPenguin** [comment]
要先下载模型，再运行测试命令

**Comment by 554518983** [comment]
@MissPenguin 您好：
我从官网中下载模型后执行的命令，执行步骤是参考官网中给的《中文OCR模型快速使用》
![image](https://user-images.githubusercontent.com/33560754/105656740-e6644580-5efd-11eb-9cb3-5d5f96743ed2.png)
解压后的结构和官方文档中的结构是一样的，并且将解压后的模型文件放到了项目下的inference文件夹中。

**Comment by tink2123** [comment]
gitee 上的代码不是最新的，建议拉 github 上 dygraph 分支的代码

**Comment by 554518983** [comment]
@tink2123 好的，谢谢
