### ISSUE TITLE
开放出来的小语种的模型，只有识别模型，没有检测模型么？

### ISSUE THREAD

**Issue by yangbisheng2009** [PaddlePaddle/PaddleOCR#1806]
我看到小语种模型，只有识别模型，导致只能识别出来第一行文字，请问检测模型开放了么？

**Comment by MissPenguin** [comment]
小语种（包括纯英文数字）的检测模型和中文的检测模型是共用的，在训练中文检测模型时加入了多语言数据。https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/models_list_en.md#1-text-detection-model

**Comment by chengshiyao-1989** [comment]
我测试的时候发现通用的检测模型只能检测中文、英文、数字，请问其他小语种（比如韩文）的检测模型是没开放吗？

**Comment by yangbisheng2009** [comment]
对对，我看到的效果也是一样的，中英文的检测模型对小语种没效

**Comment by WenmuZhou** [comment]
小语种目前没有检测模型哈，可以自己训练一个

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
