### ISSUE TITLE
det_mobilenet_v3中model_name=="small"的BUG反馈

### ISSUE THREAD

**Issue by maplelinfy** [PaddlePaddle/PaddleOCR#1812]
在用mobilenet_v3做backbone+db做head时
当https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/configs/det/det_mv3_db_v1.1.yml#L31
model_name改为"small"后，
https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/modeling/backbones/det_mobilenet_v3.py#L105
这个条件使得返回的outs个数是3，因而在
https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/modeling/heads/det_db_head.py#L133
赋值时会报错。

根据db论文输入要求，在model_name=="small"时，可否将条件改为
if layer_cfg[5] == 2 and i > 0:

**Comment by WenmuZhou** [comment]
谢谢反馈，在这里pr了 https://github.com/PaddlePaddle/PaddleOCR/pull/1822

**Comment by maplelinfy** [comment]
> 谢谢反馈，在这里pr了 #1822

感谢修改
