### ISSUE TITLE
推理耗时2s

### ISSUE THREAD

**Issue by chuzhifeng** [PaddlePaddle/PaddleOCR#1815]
hi，我使用基于pip安装whl包快速推理，使用的是您们提供的轻量级的模型，paddlepaddle是cpu版本，单张图片推断耗时2s钟左右，请问这是正常的吗，有优化的空间吗，能否优化到1s以内呢

**Comment by chuzhifeng** [comment]
当我开启ocr = PaddleOCR(use_angle_cls=True, lang="ch", enable_mkldnn=True)中的enable_mkldnn加速后，推理速度还是2s左右，并没有加快，这是什么原因呢（ps：cpu是intel的）

**Comment by WenmuZhou** [comment]
这个可能是你装的paddle没有mkl

**Comment by chuzhifeng** [comment]
那您这边有提供安装带mkl的paddle版本的链接和教程嘛

**Comment by chuzhifeng** [comment]
我还遇到一个问题，当我使用paddleOCR做预测时，只要不kill掉进程，每预测一张图片，这个就一直会吃内存（ps:版本：paddle2.0.0rc1.使用cpu版本）

**Comment by WenmuZhou** [comment]
一直跑同一张图片会吃内存吗

**Comment by WenmuZhou** [comment]
https://paddle-wheel.bj.bcebos.com/2.0.0-rc1%2Fwin-mkl%2Fpaddlepaddle_gpu-2.0.0rc1-cp38-cp38-win_amd64.whl  试试这个paddle

**Comment by chuzhifeng** [comment]
是的，跑同一张图片也会吃内存，看了其他issue的回答，修改了2.0.0，2.0.0b0这几班版本都还会吃内存，只有kill才能释放

**Comment by chuzhifeng** [comment]
我本地是mac，服务器是linux，这个windows用不了，安装包哪个版本的可以解决这个 问题吗

**Comment by WenmuZhou** [comment]
你去链接里找一下对于的linux的安装包  这是linux的mkl的安装包https://paddle-wheel.bj.bcebos.com/2.0.0-rc1-cpu-mkl%2Fpaddlepaddle-2.0.0rc1-cp38-cp38-linux_x86_64.whl

**Comment by chuzhifeng** [comment]
好的，我试试，那这个吃内存不释放的问题有解决方案麽，10G可用内存，测了50张左右图片内存就吃完了

**Comment by WenmuZhou** [comment]
这个按理说2.0b0都预测库解决了，我问问相关同学，你那边合适的话可以提供一下复现的模型和代码，以及增长的截图

**Comment by chuzhifeng** [comment]
模型：使用的就是内置模型
代码：`import time
from flask import request, Flask, jsonify
from paddleocr import PaddleOCR
from werkzeug.contrib.fixers import ProxyFix
import logging
app = Flask(__name__)


OCR = PaddleOCR(use_angle_cls=True, lang="ch", enable_mkldnn=True)


@app.route("/paddle_ocr", methods=['POST'])
def paddle_ocr():
    start_time = time.time()
    req = request.json
    logging.info("[req] %s" % req)
    resp = {"code": 0, "msg": "success", "data": []}

    try:
        img_url = req["img_url"]
        if not img_url:
            raise ValueError("img_url is null")

        results = OCR.ocr(img_url, cls=True)
        for result in results:
            res = {
                "location": result[0],
                "text": result[1][0],
                "score": str(result[1][1])
            }
            resp["data"].append(res)
    except Exception as e:
        logging.error(e)
        resp["code"] = -1
        resp["msg"] = str(e)

    cost = int((time.time() - start_time) * 1000)
    logging.info("ocr [rsp] %s, [cost] %s ms" % (resp, cost))
    return jsonify(resp)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=7000)`

当我开启这个服务后，只要不kill掉，每次请求，内存就一直消耗，导致最终内存吃完

**Comment by chuzhifeng** [comment]
请问问题能排查出来了嘛

**Comment by WenmuZhou** [comment]
下面是我在win下面的测试，使用同一张图
开始执行预测时
![image](https://user-images.githubusercontent.com/12406017/106353708-7b64a580-6327-11eb-9e9f-baea49c33a44.png)

大约执行200次后
![image](https://user-images.githubusercontent.com/12406017/106353827-591f5780-6328-11eb-96dc-2788e971b91a.png)

内存并没有明显变化。我这边使用的paddle是2.0版本，paddleocr为2.0.2

**Comment by suparek** [comment]
> 模型：使用的就是内置模型
> 代码：`import time
> from flask import request, Flask, jsonify
> from paddleocr import PaddleOCR
> from werkzeug.contrib.fixers import ProxyFix
> import logging
> app = Flask(**name**)
> 
> OCR = PaddleOCR(use_angle_cls=True, lang="ch", enable_mkldnn=True)
> 
> @app.route("/paddle_ocr", methods=['POST'])
> def paddle_ocr():
> start_time = time.time()
> req = request.json
> logging.info("[req] %s" % req)
> resp = {"code": 0, "msg": "success", "data": []}
> 
> ```
> try:
>     img_url = req["img_url"]
>     if not img_url:
>         raise ValueError("img_url is null")
> 
>     results = OCR.ocr(img_url, cls=True)
>     for result in results:
>         res = {
>             "location": result[0],
>             "text": result[1][0],
>             "score": str(result[1][1])
>         }
>         resp["data"].append(res)
> except Exception as e:
>     logging.error(e)
>     resp["code"] = -1
>     resp["msg"] = str(e)
> 
> cost = int((time.time() - start_time) * 1000)
> logging.info("ocr [rsp] %s, [cost] %s ms" % (resp, cost))
> return jsonify(resp)
> ```
> 
> if **name** == '**main**':
> app.run(host='0.0.0.0', port=7000)`
> 
> 当我开启这个服务后，只要不kill掉，每次请求，内存就一直消耗，导致最终内存吃完

我的版本

paddleocr 2.0.2
paddlepaddle-gpu 2.0.0.post101

use_gpu = True
GPU模式下也存在这个问题，用掉的GPU memory不释放。

**Comment by soxunyi** [comment]
目前使用release/2.1分支，无内存泄漏问题。releae/2.0分支，仍然会遇到内存泄漏问题。

**Comment by WenmuZhou** [comment]
那可以使用最新代码看看

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
