### ISSUE TITLE
训练识别模型 python tools/train.py -c configs/rec/rec_mv3_tps_bilstm_attn.yml 得不到 best_accuracy 文件

### ISSUE THREAD

**Issue by eashow** [PaddlePaddle/PaddleOCR#1818]
rec_mv3_tps_bilstm_attn.yml 配置如下

Global:
  algorithm: RARE
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: output/rec_RARE
  save_epoch_step: 3
  eval_batch_step: 2000
  train_batch_size_per_card: 256
  test_batch_size_per_card: 256
  image_shape: [3, 32, 100]
  max_text_length: 25
  character_type: en
  loss_type: attention
  tps: true
  reader_yml: ./configs/rec/rec_benchmark_reader.yml
  pretrain_weights: E:\AI\CarNo\work\pretrain_models\rec_mv3_tps_bilstm_attn\best_accuracy
  checkpoints:
  save_inference_dir:
  infer_img:

python tools/train.py -c configs/rec/rec_mv3_tps_bilstm_attn.yml
训练后总是得到一些 iter_epoch_xx.pdopt，iter_epoch_xx.pdmodel，iter_epoch_xx.pdparams.... 文件

**Comment by WenmuZhou** [comment]
看看你训练过程中输出的log里，迭代次数有没有到2000

**Comment by eashow** [comment]
迭代次数 没有2000，只有70（0到69）

**Comment by eashow** [comment]
怎么配参才可以生成 best_accuracy 文件呀？

**Comment by WenmuZhou** [comment]
eval_batch_step 改为10
