### ISSUE TITLE
请问一下这里×800是为什么？以及在EAST在算loss的时候为什么dice_loss要乘以0.01

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#182]
https://github.com/PaddlePaddle/PaddleOCR/blob/a03f9e149eb30d8588356c2bd5c40576817dd3ac/ppocr/modeling/heads/det_east_head.py#L107

**Comment by zchengquan** [comment]
1.f_geo分支是用于回归文字几何边界，通过(simoid激活 - 0.5 ) * 2 * 800操作，一方面把文字的几何偏差范围预设在-800~800之间了（有点类似anchor的概念），起到更好收敛的作用。你也可以选择直接用conv/fc层直接替换（尤其是当你的数据中文字尺度变化更大的时候）。
2.dice_loss乘以0.01是来做不同loss之间的均衡作用，是个经验参值，一般根据每个loss收敛后的量级或者不同任务分支所带来的梯度影响来设定的，亦或可以通过批量调参来决定。
