### ISSUE TITLE
linux多卡训练经常性崩溃。。。

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#1823]
**运行环境：**ubuntu20.04, python 3.8,  PU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 11.0, cuDNN Version: 8.0
**崩溃报错：**报错很随机，有时候训练刚开始就报错，有时候训练快结束来个这个报错
![报错](https://user-images.githubusercontent.com/15188456/105804218-331d4e80-5fda-11eb-835a-02454ef25f07.png)
**显卡占用：**
![显卡占用](https://user-images.githubusercontent.com/15188456/105804235-416b6a80-5fda-11eb-8854-ac8ae26ee74f.png)

**Comment by WenmuZhou** [comment]
试一下最新代码和最新的paddle

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
