### ISSUE TITLE
release/2.0-rc1-0这个分支下的ic15_dict.txt字典不包含大写字母

### ISSUE THREAD

**Issue by studiouspan** [PaddlePaddle/PaddleOCR#1824]
发现release/2.0-rc1-0这个分支下的ic15_dict.txt字典不包含大写字母，请勿使用。

**Comment by tink2123** [comment]
这个字典是用做快速 finetune 英文模型的。因为英文模型训练时字典文件不包含大写字母，因为finetune时的字典也不能包含大写。
如果需要大小写的字典，请使用：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0-rc1-0/ppocr/utils/dict/en_dict.txt
