### ISSUE TITLE
android 应用闪退

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleOCR#1839]
成功编译且安装到手机上，但是打开应用时会闪退，debug下显示说是找不到模型文件，报错如下：
(第一次接触安卓，不太懂. thx)

01/27 10:04:20: Launching 'app' on OPPO OPPO A59m.
Install successfully finished in 10 s 804 ms.
$ adb shell am start -n "com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 24846 on device 'oppo-oppo_a59m-KNAIJJY9G6MB8L6D'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ActivityThread: installProvider: context.getPackageName()=com.baidu.paddle.lite.demo.ocr  

**_W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.baidu.paddle.lite.demo.ocr/files, /storage/sdcard1 has not mounted right now_**
**_W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.baidu.paddle.lite.demo.ocr/files
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter_** 
**_androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable_**  

E/Process: android_os_Process_getProcessNameByPid pid is 24846
E/Process: android_os_Process_getProcessNameByPid value is e.lite.demo.ocr
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
    Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
D/OpenGLRenderer: Dumper init 4 threads <0x7f9d189a80>
    <com.baidu.paddle.lite.demo.ocr> is running.
D/OpenGLRenderer: initialize DisplayEventReceiver 0x7f9601a630
    Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas: Validating map...
D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{17cc01e1 com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity,ident = 0}
V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{224765c5 I.E..... R.....ID 0,0-0,0}
D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{367fb7f4 com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity,ident = 1}
V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{367fb7f4 com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{224765c5 V.E..... R.....ID 0,0-0,0}  

**_W/System.err: java.io.FileNotFoundException: models/ocr_v1_for_cpu/ocr_v1_for_cpu_**  

W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:359)
        at android.content.res.AssetManager.open(AssetManager.java:333)
        at com.baidu.paddle.lite.demo.ocr.Utils.copyFileFromAssets(Utils.java:21)
        at com.baidu.paddle.lite.demo.ocr.Utils.copyDirectoryFromAssets(Utils.java:56)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:114)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
W/System.err:     at com.baidu.paddle.lite.demo.ocr.Utils.copyFileFromAssets(Utils.java:34)
        at com.baidu.paddle.lite.demo.ocr.Utils.copyDirectoryFromAssets(Utils.java:56)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:114)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/Predictor: model path/data/data/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_det_mv3_db_opt.nb ; /data/data/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_rec_mv3_crnn_opt.nb;/data/data/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/cls_opt_arm.nb
W/linker: /data/app/com.baidu.paddle.lite.demo.ocr-2/lib/arm64/libNative.so: unused DT entry: type 0x6ffffffe arg 0x2b190
W/linker: /data/app/com.baidu.paddle.lite.demo.ocr-2/lib/arm64/libNative.so: unused DT entry: type 0x6fffffff arg 0x3
    libpaddle_light_api_shared.so: unused DT entry: type 0x6ffffffe arg 0x30c10
    libpaddle_light_api_shared.so: unused DT entry: type 0x6fffffff arg 0x2
    libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2ebf8
W/linker: libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
    libhiai_ir.so: unused DT entry: type 0x6ffffffe arg 0x17808
    libhiai_ir.so: unused DT entry: type 0x6fffffff arg 0x2
    libhiai_ir_build.so: unused DT entry: type 0x6ffffffe arg 0x1b68
    libhiai_ir_build.so: unused DT entry: type 0x6fffffff arg 0x2
    libhiai.so: unused DT entry: type 0x6ffffffe arg 0x4468
    libhiai.so: unused DT entry: type 0x6fffffff arg 0x2
D/OpenGLRenderer: CanvasContext() 0x7f9601e7c0 initialize 0x7f9d23d410
D/MALI: eglInitialize:1479: [+]
E/art: dlopen("/data/app/com.baidu.paddle.lite.demo.ocr-2/lib/arm64/libNative.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.ocr, PID: 24846
    java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:18)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:127)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:16)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:127) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/GED: Failed to get GED Log Buf, err(0)
D/MALI: eglInitialize:1850: [-]
I/: elapse(include ctx switch):6232 (ms), eglInitialize
I/OpenGLRenderer: Initialized EGL, version 1.4
D/MALI: eglCreateContext:206: [MALI] eglCreateContext display 0x7f9d05c180, share context 0x0 here.
D/MALI: gles_context_new:248: Create GLES ctx 0x7f96292008 successfully
    eglCreateContext:543: [MALI] eglCreateContext end. Created context 0x7f96282d80 here.
D/OpenGLRenderer: Created EGL context (0x7f962292e0)
I/OpenGLRenderer: Get enable program binary service property (1)
    Initializing program atlas...
D/ProgramBinary/Service: BpProgramBinaryService.getFileDescriptor
    BpProgramBinaryService.getProgramMapLen
    BpProgramBinaryService.getProgramMapArray
D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryLen
I/OpenGLRenderer: Program binary detail: Binary length is 169984, program map length is 152.
    Succeeded to mmap program binaries. File descriptor is 47, and path is /dev/ashmem�.
I/OpenGLRenderer: No need to use file discriptor anymore, close fd(47).
D/OpenGLRenderer: TaskManager() 0x7f961fb8f0, cpu = 8, thread = 4
D/OpenGLRenderer: Initializing program cache from 0x7fa0e91ad0, size = 4
D/OpenGLRenderer: -- init (key = 0x0000003800000000)
D/OpenGLRenderer: -- init (key = 0x0000100800000003)
D/OpenGLRenderer: -- not init (key = 0x0000100800500043)
D/OpenGLRenderer: -- init (key = 0x0000101000000000)
    Enabling debug mode 0
D/Surface: Surface::connect(this=0x7f9d23d400,api=1)
D/mali_winsys: new_window_surface returns 0x3000
D/Surface: Surface::allocateBuffers(this=0x7f9d23d400)
D/OpenGLRenderer: CanvasContext() 0x7f9601e900 initialize 0x7f9d244410
D/Surface: Surface::connect(this=0x7f9d244400,api=1)
D/mali_winsys: new_window_surface returns 0x3000
D/Surface: Surface::allocateBuffers(this=0x7f9d244400)
D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask1 (24892)
    [TaskMgr] Running thread hwuiTask2 (24893)
D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask3 (24894)
D/OpenGLRenderer: ProgramCache save to disk, size = 4
I/Process: Sending signal. PID: 24846 SIG: 9

**Comment by zouxiaoshi** [comment]
补充：
在MACOS下编译
手机 安卓内核 5.1
minSdkVersion 20
targetSdkVersion 29

**Comment by authorfu** [comment]
models/ocr_v1_for_cpu/ocr_v1_for_cpu 这个文件是assets目录下的，代码会尝试复制到 data目录下，可以尝试看下: /storage/sdcard1/Android/data/com.baidu.paddle.lite.demo.ocr/files是否可写，或者另外找一个目录复制

**Comment by zouxiaoshi** [comment]
> models/ocr_v1_for_cpu/ocr_v1_for_cpu 这个文件是assets目录下的，代码会尝试复制到 data目录下，可以尝试看下: /storage/sdcard1/Android/data/com.baidu.paddle.lite.demo.ocr/files是否可写，或者另外找一个目录复制

您好哪里可以修改 /storage/sdcard1/Android/data 这个地址，我试了下，sdcard1是只读的，sdcard0可写，现在想尝试下把地址换成 /storage/sdcard0/Android/data/com.baidu.paddle.lite.demo.ocr/files  但我在java文件里找了好久 没找到更改地址的地方，请问该在哪里做修改。

**Comment by zouxiaoshi** [comment]
换了设备后，可以正常读取/storage/sdcard1，但又出现了新的问题：（如下为debug信息），（应用闪退）

01/30 18:08:02: Launching 'app' on HUAWEI SHT-AL09.
Install successfully finished in 12 s 363 ms.
$ adb shell am start -n "com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 362 on device 'huawei-sht_al09-PUG6R18314009013'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.ocr#10131#256
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.ocr#10131#0
I/AwareBitmapCacher: init processName:com.baidu.paddle.lite.demo.ocr pid=362 uid=10131
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@86385a4
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@5f00f0d
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: Runnable thread started.
D/IMonitor: Load library imonitor_jni
V/ActivityThread: Skipping new config:{1.0 460mcc1mnc [zh_CN_#Hans] ldltr sw533dp w533dp h829dp 480dpi lrg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1600, 2560) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.26}, config:{1.0 460mcc1mnc [zh_CN_#Hans] ldltr sw533dp w533dp h829dp 480dpi lrg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1600, 2560) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.26} for app:com.baidu.paddle.lite.demo.ocr
V/HwPolicyFactory: : success to get AllImpl object and return....
V/ActivityThread: callActivityOnCreate
W/e.lite.demo.oc: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
I/HwApsImpl: APS: new HwApsImpl created
V/HwWidgetFactory: : successes to get AllImpl object and return....
I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
I/HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@8ff3e1f,androidx.appcompat.view.ContextThemeWrapper@495156c
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@2741c58,androidx.appcompat.view.ContextThemeWrapper@495156c
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/AwareAppScheduleManager: post cache drawable res id to aware, resId = 17302082, packagename = com.baidu.paddle.lite.demo.ocr, cost time = 10183854
W/e.lite.demo.oc: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/e.lite.demo.oc: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/TextView: get Display Panel Type is : 0
W/e.lite.demo.oc: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
D/ActivityThread: add activity client record, r= ActivityRecord{d724b2b token=android.os.BinderProxy@e255810 {com.baidu.paddle.lite.demo.ocr/com.baidu.paddle.lite.demo.ocr.MainActivity}} token= android.os.BinderProxy@e255810
D/ZrHung.AppEyeUiProbe: notify runnable to start.
I/HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=true, mIsFloating=true
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@955c73d,android.view.ContextThemeWrapper@2689b32
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@381387e,android.view.ContextThemeWrapper@2689b32
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@3f45e8a,android.view.ContextThemeWrapper@2689b32
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
    loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@b49e118,android.view.ContextThemeWrapper@2689b32
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
D/OpenGLRenderer: Skia GL Pipeline
D/HwAppInnerBoostImpl: set config for com.baidu.paddle.lite.demo.ocr BOOST_FLAG=false REPORT_DURATION_CLICK=1000 REPORT_TIMES_CLICK=3 REPORT_DURATION_SLIDE=5000 REPORT_TIMES_SLIDE=16
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true
W/System.err: java.io.FileNotFoundException: models/ocr_v1_for_cpu/ocr_v1_for_cpu
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:865)
        at android.content.res.AssetManager.open(AssetManager.java:842)
W/System.err:     at com.baidu.paddle.lite.demo.ocr.Utils.copyFileFromAssets(Utils.java:21)
        at com.baidu.paddle.lite.demo.ocr.Utils.copyDirectoryFromAssets(Utils.java:56)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:114)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
        at com.baidu.paddle.lite.demo.ocr.Utils.copyFileFromAssets(Utils.java:34)
        at com.baidu.paddle.lite.demo.ocr.Utils.copyDirectoryFromAssets(Utils.java:56)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:114)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
W/System.err:     at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/Predictor: model path/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_det_mv3_db_opt.nb ; /data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_rec_mv3_crnn_opt.nb;/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/cls_opt_arm.nb
I/HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddle.lite.demo.ocr, windowType=2, mHiTouchRestricted=false
E/OCR_NDK: cpu_mode not found LITE_POWER_HIGH
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/Paddle-Lite: [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1064 Setup] ARM multiprocessors name: _SHT_HI3660_
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/Paddle-Lite: [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors number: 8
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 0, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 1, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 2, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 3, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 4, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 5, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 6, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 7, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1073 Setup] L1 DataCache size is: 
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
I/chatty: uid=10131(com.baidu.paddle.lite.demo.ocr) Predictor Worke identical 6 lines
I/Paddle-Lite: [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1077 Setup] L2 Cache size is: 
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
I/chatty: uid=10131(com.baidu.paddle.lite.demo.ocr) Predictor Worke identical 6 lines
I/Paddle-Lite: [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1081 Setup] L3 Cache size is: 
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
I/chatty: uid=10131(com.baidu.paddle.lite.demo.ocr) Predictor Worke identical 6 lines
I/Paddle-Lite: [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
    [I  1/30 18: 8:16.724 ...tmp/Paddle-Lite/lite/core/device_info.cc:1085 Setup] Total memory: 3804700KB
I/iGraphics: [0020080c] pn: com.baidu.paddle.lite.demo.ocr, p: 362
    [0030080c] no spt app: com.baidu.paddle.lite.demo.ocr
I/OpenGLRenderer: Initialized EGL, version 1.4, mEglDisplay 0x1
D/OpenGLRenderer: Swap behavior 2
A/Paddle-Lite: [F  1/30 18: 8:16.729 ...odel_parser/naive_buffer/naive_buffer.cc:62 LoadFromFile] Check failed: fp: Unable to open file: /data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_det_mv3_db_opt.nb
    
    
    --------- beginning of crash
A/libc: FORTIFY: fseeko: null FILE*
I/HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddle.lite.demo.ocr, windowType=1, mHiTouchRestricted=false
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 588 (Predictor Worke), pid 362 (e.lite.demo.ocr)
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true
I/ViewRootImpl: jank_removeInvalidNode jank list is null

**Comment by MissPenguin** [comment]
最新的android demo代码是没有问题的，可以先拉最新代码试试哈，如果仍有问题可以重新提issue，我们再继续跟进～

**Comment by zouxiaoshi** [comment]
> 最新的android demo代码是没有问题的，可以先拉最新代码试试哈，如果仍有问题可以重新提issue，我们再继续跟进～

好的。多谢哈。
