### ISSUE TITLE
角度分类器问题

### ISSUE THREAD

**Issue by Sunzhongfeng** [PaddlePaddle/PaddleOCR#1840]
![image_1](https://user-images.githubusercontent.com/37096083/105934563-68ce4000-608b-11eb-908a-82ffe9cd5c89.png)
请教一下，角度分类器，1,2 这两种情况分别是0度和180度，3,4这两种情况也是0度和180度吗？ 角度分类器训练的时候，1,3 是属于同一个类别吗？

**Comment by WenmuZhou** [comment]
训练的时候1，3是一个类别0度，2和4是一个类别180度

**Comment by Sunzhongfeng** [comment]
好的，谢谢，那3的这种情况，比如第一个“在”字，躺着的和正常的，识别训练的时候是一个类别，是吗？

**Comment by MissPenguin** [comment]
> 好的，谢谢，那3的这种情况，比如第一个“在”字，躺着的和正常的，识别训练的时候是一个类别，是吗？

对，是一个类别
