### ISSUE TITLE
检测模型使用其他尺寸输入，设置哪些参数

### ISSUE THREAD

**Issue by chenxinhua** [PaddlePaddle/PaddleOCR#1842]
检测模型在测试时，可以设置DetResizeForTest: image_shape: [736, 1280]来控制输入尺寸，如果注释image_shape，默是怎么处理的？
训练时输入图片尺寸是怎么调整的呢？

**Comment by MissPenguin** [comment]
不同的参数会调用不同的resize逻辑，具体可以看下这部分代码：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/data/imaug/operators.py#L115
