### ISSUE TITLE
训练方向分类器模型出错

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#1845]
执行python tools/train.py -c configs/cls/cls_mv3.yml
报错如下：
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 52, in main
    config, train_program, startup_program, mode='train')
  File "G:\PaddleOCR\tools\program.py", line 183, in build
    opt_loss = outputs['total_loss']
KeyError: 'total_loss'

**Comment by MissPenguin** [comment]
是dygraph分支最新代码吗

**Comment by lybcodes** [comment]
> 是dygraph分支最新代码吗

不是，是develop分支

**Comment by WenmuZhou** [comment]
拉一下最新代码看看，我这边给个确认无误的

**Comment by lybcodes** [comment]
> 拉一下最新代码看看，我这边刚刚确认无误的

还是要请教下您，我拉了最新的代码，报了这样的错误
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.5\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

然后我检查了数据集的格式，感觉没什么问题，不知道是哪里出错了
yml配置文件如下：
TrainReader:
  reader_function: ppocr.data.cls.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: ./train_data/cls
  label_file_path: ./train_data/cls/cls_train.txt
  
EvalReader:
  reader_function: ppocr.data.cls.dataset_traversal,SimpleReader
  img_set_dir: ./train_data/cls
  label_file_path: ./train_data/cls/cls_test.txt

TestReader:
  reader_function: ppocr.data.cls.dataset_traversal,SimpleReader

标签文件如下：
cls_train/img1989.jpg	0
cls_train/img1990.jpg	0
cls_train/img1991.jpg	0
cls_train/img1992.jpg	0
cls_train/img1993.jpg	0
cls_train/img1994.jpg	0
cls_train/img1995.jpg	0
cls_train/img1996.jpg	0
cls_train/img1997.jpg	0
cls_train/img1998.jpg	0
cls_train/img1999.jpg	0
cls_train/rimg100.jpg	180
cls_train/rimg101.jpg	180
cls_train/rimg102.jpg	180
cls_train/rimg103.jpg	180

**Comment by lybcodes** [comment]
解决了，是我标签文件格式不对，我的txt里每行结尾是\r\n，dataset_traversal.py里加载文件的代码是根据\n来分割的
