### ISSUE TITLE
中英文超轻量OCR模型中的识别模型解压之后与文档中的目录结构不一样

### ISSUE THREAD

**Issue by great-wind** [PaddlePaddle/PaddleOCR#1848]
按照快速使用文档的说明，下载中英文超轻量OCR模型的检测模型、方向分类模型、识别模型，按照说明，每个模型解压之后应该有3个文件，但是识别模型解压之后只有一个文件，请问怎么解决？

**Comment by MissPenguin** [comment]
是吗，你解压出来是啥，截图看下

**Comment by great-wind** [comment]
> 是吗，你解压出来是啥，截图看下

感谢回复！！！

文档里的识别模型，解压之后是下面的结构
```├── ch_ppocr_mobile_v2.0_rec_infer
    ├── inference.pdiparams
    ├── inference.pdiparams.info
    └── inference.pdmodel```
但是我解压之后，只有一个文件，如下：
<img width="612" alt="111" src="https://user-images.githubusercontent.com/43674034/106229226-18401980-6228-11eb-86f2-30a747aaf15c.png">

**Comment by zhaoyantao-murray** [comment]
> 按照快速使用文档的说明，下载中英文超轻量OCR模型的检测模型、方向分类模型、识别模型，按照说明，每个模型解压之后应该有3个文件，但是识别模型解压之后只有一个文件，请问怎么解决？

我下载的是V2.0的模型文件，使用tar -xvf ch_ppocr_server_v2.0_det_infer.tar   解压后是没问题的。
