### ISSUE TITLE
有一个问题想请问一下，困扰了好久

### ISSUE THREAD

**Issue by sifanlook** [PaddlePaddle/PaddleOCR#1851]
**文本检测**的数据集可以用PPLabel进行自动标注，然后训练，很方便
那么**文本识别**是不是需要手动把图片中的文字一行一行截取成一个新的图片，然后再标注训练？（**这样会不会太麻烦了啊**）
请大佬帮忙解答一下，万分感谢☺

**Comment by MissPenguin** [comment]
写个脚本批量处理下

**Comment by sifanlook** [comment]
这个问题已解决，PPOCRLabel可以搞定☺
