### ISSUE TITLE
c++ infer tensorrt开启时结果不一致

### ISSUE THREAD

**Issue by eyeclosed** [PaddlePaddle/PaddleOCR#1853]
paddle release/2.0 
paddleocr 为2021-01-26的动态版本
设备 jetson tx2，jetpack4.4
在config文件里分别开启和关闭tensorrt，两者预测结果相差较大,tensorrt开启后效果明显差了很多
同时，当开启tensorrt后使用rpc服务部署时，每重连一次，显存会直接增加800M左右，断开不释放。不开启tensorrt时，服务正常

附件分别为运行时配置文件，paddle编译后的版本文件，有问题的图片。图片为ccpd数据集中截取车牌部分的小图片

[version.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5884668/version.txt)
[val3.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5884669/val3.zip)
[config.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5884670/config.txt)

在另一台pc设备上docker内运行，结果和jetson上类似； 主机 ubuntu16 /rtx2080；docker cudn10.0-cudnn7-tensorrt7-ubuntu16。

**Comment by LDOUBLEV** [comment]
不是环境的问题，开启TRT时图像需要resize到固定长度，会影响预测效果，后面会尝试支持变长输入，效果就不会变差了
https://github.com/PaddlePaddle/PaddleOCR/pull/1696

**Comment by eyeclosed** [comment]
我看到代码里固定resize到640*640，我这边尝试下截图时保证长宽比为1看看效果；

另外我这边将c++代码集成到rpc服务中时，发现在开启tensorrt支持后存在显存泄漏的问题，具体表现为
当客户端完成若干（3-1000，图片大小格式一致）次ocr请求后断开连接，再次请求连接后GPU占用会直接增加800M左右；
关闭tensorrt支持则为正常。@LDOUBLEV

**Comment by WenmuZhou** [comment]
试一下最新代码看看

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
