### ISSUE TITLE
CRNN模型 多BATCH预测但是结果被合并问题。

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleOCR#1854]
比如我输入一张(1, 3, 32, 320) 的图让CRNN识别 ， 结果是[631 93 92 25 1108 26 25 24 1108 630 28 93 1108]， 很正常。
但是如果我输入两张(2, 3, 32, 320)的图让CRNN识别，结果是 [631 93 92 25 1108 26 25 24 1108 630 28 93 1108 631 93 92 25 1108 26 25 24 1108 630 28 93 1108] 
风中凌乱。

**Comment by tink2123** [comment]
你的预测命令是？
batch_size > 1的情况下，返回结果会cat到一起，后处理的时候会根据batch size去解码。

**Comment by yangtianyu92** [comment]
> 你的预测命令是？
> batch_size > 1的情况下，返回结果会cat到一起，后处理的时候会根据batch size去解码。

大神谢谢你，卡了我一天了，头皮发麻。这个后处理在哪可以看啊。

**Comment by yangtianyu92** [comment]
记录下,不定长TENSOR有个lod()方法可以返回索引，通过这个索引就可以把结果切割出来。哈哈
