### ISSUE TITLE
请问微调v1.1预训练的模型，可以直接用文字垂直排列和上下颠倒的图片吗？还是必须要水平排列的，我看v1.1模型支持垂直排列和上下翻转图片的识别的

### ISSUE THREAD

**Issue by kingwpf** [PaddlePaddle/PaddleOCR#1857]

**Comment by kingwpf** [comment]
pretrain的模型本身是依靠方向分类器实现的对上下颠倒图片的支持吗？方向分类只有0°和180°，那是不是垂直排列的字符是可以直接训练的

**Comment by tink2123** [comment]
竖排文字需要逆时针旋转90度后加入训练集与横排一起训练。

**Comment by kingwpf** [comment]
> 竖排文字需要逆时针旋转90度后加入训练集与横排一起训练。

好的，谢谢，如果文字是上下翻转的数据可以一起训练吗？

**Comment by tink2123** [comment]
可以一起训练，我们也提供了方向分类器，分类之后转正再预测也是可以的

**Comment by kingwpf** [comment]
> 可以一起训练，我们也提供了方向分类器，分类之后转正再预测也是可以的

与训练的模型是只输入了正向的和旋转90°的数据吗？
