### ISSUE TITLE
方向分类器输入图片resize问题

### ISSUE THREAD

**Issue by Sunzhongfeng** [PaddlePaddle/PaddleOCR#1859]
大神，请教一下，请问方向分类器的输入图片是怎么resize的（存在几个字符很短，还有很长的情况），预测图片和训练时的resize方式一样吗？

**Comment by WenmuZhou** [comment]
高度resize到48，宽度等比例resize，如果宽度<192, 就进行进行pad，>192就强行resize到(48,192)

**Comment by Sunzhongfeng** [comment]
好的，谢谢！预测的时候也是这样resize吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zhoujun&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月28日(星期四) 下午5:31
收件人:&nbsp;&quot;PaddlePaddle/PaddleOCR&quot;<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Sunzhongfeng&quot;<254043936@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 方向分类器输入图片resize问题 (#1859)

**Comment by Sunzhongfeng** [comment]
还有请问一下，方向分类器训练，预测时图片reszie的代码是哪部分啊，没找到

**Comment by Sunzhongfeng** [comment]
> 高度resize到48，宽度等比例resize，如果宽度<192, 就进行进行pad，>192就强行resize到(48,192)

好的，谢谢！，预测的图片resize也是一样的吗？还有请问一下，训练，预测时图片reszie的代码是对应的哪部分啊，没找到

**Comment by WenmuZhou** [comment]
训练在这里https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/data/imaug/rec_img_aug.py#L35
预测在这里https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/infer/predict_cls.py#L51
