### ISSUE TITLE
east检测模型检测出的文本框太紧凑，请问如何调整参数，使得检测出的文本框稍大一些，以便能将文本全包括进来？

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/PaddleOCR#1862]

**Comment by tink2123** [comment]
目前没有暴露参数，可以手动修改后处理的代码，放大边框:https://github.com/PaddlePaddle/PaddleOCR/blob/51d80bd6960bbf4bacc4521b1ffac656849e22ad/ppocr/postprocess/east_postprocess.py#L129

**Comment by ahsdx** [comment]
> 目前没有暴露参数，可以手动修改后处理的代码，放大边框:
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/51d80bd6960bbf4bacc4521b1ffac656849e22ad/ppocr/postprocess/east_postprocess.py#L129

好的，谢谢
