### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.jit'

### ISSUE THREAD

**Issue by GraceKafuu** [PaddlePaddle/PaddleOCR#1863]
搜也搜不到这种问题，太坑了

**Comment by LDOUBLEV** [comment]
升级paddle版本吧，paddle版本至少大于等于2.0rc1

**Comment by GraceKafuu** [comment]
卸了，不玩百度的了，还是PyTorch好

**Comment by tink2123** [comment]
paddle.jit 是Paddle2.0最新的api，如果安装了之前版本的paddle，是没有办法使用的。

按照教程推荐的版本安装的话，是不会出现这个问题的哦。

**Comment by Zhang-O** [comment]
> paddle.jit 是Paddle2.0最新的api，如果安装了之前版本的paddle，是没有办法使用的。
> 
> 按照教程推荐的版本安装的话，是不会出现这个问题的哦。

2.1.1 还是会出现 “No module named 'paddle.jit“问题
2.1.2 不会出现
