### ISSUE TITLE
关于EAST模型检测出文本框的四个点坐标顺序的问题

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/PaddleOCR#1866]
忽然发现EAST模型检测出文本框的四个点坐标并不是严格按照矩形左上、右上、右下、左下顺序排列的，它有时候会按照左下、左上、右上、右下顺序排列，这样会导致识别模型识别错误，请问有什么比较好的解决办法呢？
虽然说可以写个代码，让检测出的坐标严格按照左上、右上、右下、左下排列，但这样感觉会增加推理时间。

**Comment by WenmuZhou** [comment]
这个只能写个代码解决了，并且排序时间应该不会增加多少

**Comment by ahsdx** [comment]
好的，谢谢
