### ISSUE TITLE
style-text生成文本可以替换背景吗？

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#1870]
保留输入图片的文本风格fake_text，背景fake_bg替换为其他的图片other_bg，然后用fake_text和other_bg合成fake_fusion可以吗？

**Comment by weisy11** [comment]
不可以，这里的fake_bg并没有直接输入到fusion模块。fusion模块的输入是提取fake_bg过程中的feature_map。
如果需要换背景可以通过先把fake_text的字抠出来（可以通过颜色大致判断），再贴到需要的背景上去。

**Comment by weisy11** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/0c5c9f694d129c4b4a96aad73fd2291dc7a6f768/StyleText/arch/style_text_rec.py#L65
把这里的fake_bg改成other_bg就可以了，要注意shape一致
