### ISSUE TITLE
图片方向矫正后的识别效果变差了

### ISSUE THREAD

**Issue by Maxhyl** [PaddlePaddle/PaddleOCR#1876]
我先对图片的方向进行判定，然后用PIL模型的transpose对图片进行旋转，但是发现旋转后的识别效果变差了，没有直接对图片进行操作再识别的效果好，请问是因为旋转影响到图片质量了吗？还是别的原因

**Comment by littletomatodonkey** [comment]
图像旋转不会影响图片质量，但是会影响检测效果，

**Comment by Maxhyl** [comment]
> 图像旋转不会影响图片质量，但是会影响检测效果，

感谢回复，请问有什么方法优化吗

**Comment by WenmuZhou** [comment]
训练检测的时候加入旋转的数据增强

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
