### ISSUE TITLE
win10 GPU/CPU训练一下莫名中断

### ISSUE THREAD

**Issue by chuanfuye** [PaddlePaddle/PaddleOCR#1878]
硬件环境：win10 专业版，cuda10.2 ，cudnn7.6.5，显卡1660ti，6G
BUG如下：
启动训练命令：python tools/train.py -c configs/det/det_mv3_db.yml      -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained

错误信息：2021/01/29 17:52:52] root INFO: epoch: [1/1200], iter: 960, lr: 0.001000, loss: 3.700005, loss_shrink_maps: 2.079536, loss_threshold_maps: 0.953216, loss_binary_maps: 0.423404, reader_cost: 0.00000 s, batch_cost: 0.10197 s, samples: 10, ips: 9.80697
Segmentation fault 
总是到batch=8 × iteration120 = 960 中断
修改了配置文件的batch大小，或者num_worcker改变线程大小，或者use_shared_memory改为True，都没有效果。望解答
是否是在1660ti上面不能训练，还是修改什么参数
希望回答，非常感谢！！！！

**Comment by edisonyan** [comment]
我的2080也一样 到iter990就自动中断了

**Comment by WenmuZhou** [comment]
你的数据集一个epoch的最大iter是1000吗，这个问题我最近在win上测试，paddle2.0.0版本下是正常的

**Comment by chuanfuye** [comment]
> 你的数据集一个epoch的最大ite

你好，我在训练的的时候吧batch改为1.确实iter到990的时候会断掉，能否问一下这个参数要怎么修改谢谢。你测试的时候是用或者gpu训练呢

**Comment by edisonyan** [comment]
经过尝试
使用提供的docker环境或者降低paddle到1.8版本+dev分支代码，同样的数据集和配置没有重现一个epoch后进程中止的问题。

**Comment by chuanfuye** [comment]
经过尝试，在ubuntu服务器上2.0.0可以使用。在win10训练问题依旧存在，也可能是内存太小
