### ISSUE TITLE
Both of detection and recognition for uyghur language is not working well!

### ISSUE THREAD

**Issue by azmat21** [PaddlePaddle/PaddleOCR#1879]
Both of detection and recognition for uyghur language is not working well, example as follows (Uyghur is right to left language like arabic , and want to reshape the text while training and testing):

![1](https://user-images.githubusercontent.com/5554488/106262085-7509f700-625d-11eb-9493-506561ecf38b.png)
![4_bi](https://user-images.githubusercontent.com/5554488/106262125-818e4f80-625d-11eb-8bf8-1b2ac9c97f89.jpeg)
![book2_1](https://user-images.githubusercontent.com/5554488/106262138-86530380-625d-11eb-88b0-a0eca2fb5e7a.png)
![test_full](https://user-images.githubusercontent.com/5554488/106262153-8a7f2100-625d-11eb-8ef2-314c2153f083.png)

**Comment by tink2123** [comment]
Thanks for your suggestion, we know little about Uyghur language. The current model only uses synthetic data. If you can help provide some real data, the effect will be greatly improved.

**Comment by azmat21** [comment]
> Thanks for your suggestion, we know little about Uyghur language. The current model only uses synthetic data. If you can help provide some real data, the effect will be greatly improved.

It is  hard to get large scale real image data and I am also use  synthetic data. But most important point for Synthetic data for RTL languages (like arabic, uyghur and so on) is you need to get display text from labels. simple Pseudocode as below:

```
from bidi.algorithm import get_display

// for train
label = "مەن ناھايىتى ياخشى" // label for generating image
img = get_img(label)  // generate image
golbel_label =  get_display(label)  // (img, golbel_label) for train

//inference
label = model(img)
return_label = get_display(label) // result for return
  
```


`

**Comment by WenmuZhou** [comment]
we have support Uyghur for text recognition

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by Shewket** [comment]
Hi, this issue is already be solved or not? @tink2123
