### ISSUE TITLE
运行pridict_system文件报错:list index out of range

### ISSUE THREAD

**Issue by xiaokecui** [PaddlePaddle/PaddleOCR#188]
Traceback (most recent call last):
  File "C:/Users/EDDC/Desktop/PaddleOCR-develop - beifen/tools/infer/predict_system.py", line 115, in <module>
    dt_boxes, rec_res = text_sys(img)
  File "C:/Users/EDDC/Desktop/PaddleOCR-develop - beifen/tools/infer/predict_system.py", line 78, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "C:\Users\EDDC\Desktop\PaddleOCR-develop - beifen\tools\infer\predict_rec.py", line 94, in __call__
    preds_text = self.char_ops.decode(rec_idx_tmp)
  File "C:\Users\EDDC\Desktop\PaddleOCR-develop - beifen\ppocr\utils\character.py", line 96, in decode
    char_list.append(self.character[text_index[idx]])
IndexError: list index out of range

**Comment by tink2123** [comment]
请问识别是否使用了attention模型？请尝试在预测时添加参数 --rec_algorithm=“RARE”

**Comment by xiaokecui** [comment]
你好,我因为刚接触这些,所以并不是很清楚你说的attention模型,和--rec_algorithm=“RARE”该如何添加. 我现在用的是readme中提到的ch_det_mv3_db_infer和ch_rec_mv3_crnn_infer模型

**Comment by tink2123** [comment]
使用ch_rec_mv3_crnn_infer的话损失函数不是attention，方便发一下您预测的命令吗

**Comment by xiaokecui** [comment]
我是在pycharm中直接运行的pridict_system文件,其中在readme提供的指令: 
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
```中的rec_model_dir和det_model_dir参数我是在tool/info/utility文件中进行修改如下:
parser.add_argument("--det_model_dir", type=str,default=path+r'/inference/ch_det_mv3_db')
parser.add_argument("--rec_model_dir", type=str,default=path+r'/inference/ch_rec_mv3_crnn')
path为当前项目所在路径

**Comment by tink2123** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/d6939fa263947d2f149414935d14727c75ef1168/tools/infer/utility.py#L62-65
如果要用 path + 的方式，需要同样修改dict文件路径。或者您可以直接在pycharm的terminal里输入 `SET PATHONPATH=.`

**Comment by tink2123** [comment]
@xiaokecui 您好，请问问题解决了吗

**Comment by xiaokecui** [comment]
还没呢,我刚刚尝试了你说的dict用path+的方式和设置pyhton环境变量但还是同样的报错






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 中午11:34
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"小可☆崔"<1191345362@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运行pridict_system文件报错:list index out of range (#188)





 
@xiaokecui 您好，请问问题解决了吗

**Comment by xiaokecui** [comment]
‍你好,我通过debug发现了上面的问题,但是我不太清楚出现这种问题的原因是什么.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 中午11:34
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"小可☆崔"<1191345362@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运行pridict_system文件报错:list index out of range (#188)





 
@xiaokecui 您好，请问问题解决了吗

**Comment by tink2123** [comment]
看起来是因为你使用了中文模型进行预测，但是解码时选择了英文模式，预测时添加 --rec_char_type=‘ch’ 试一下呢？

**Comment by ZhaoyangLi-nju** [comment]
> 看起来是因为你使用了中文模型进行预测，但是解码时选择了英文模式，预测时添加 --rec_char_type=‘ch’ 试一下呢？

不能同时显示吗，在预测时，我也出现了类似的错误，我已经设置如上所述的参数，但依旧出现了类似的问题，分别在
1.File "/root/Detection/detection/tools/infer/predict_rec.py", line 121, in __call__
    end = predict_lod[rno + 1]
IndexError: list index out of range
2.File "/root/Detection/detection/tools/infer/predict_rec.py", line 121, in __call__
    end = predict_lod[rno + 1]
IndexError: list index out of range
同时，在linux下有时候会出现如下的问题，烦请您指教
Intel MKL function load error: cpu specific dynamic library is not loaded.
[2020-07-16 20:06:39 +0800] [52752] [INFO] Booting worker with pid: 52752

**Comment by ZhaoyangLi-nju** [comment]
> 看起来是因为你使用了中文模型进行预测，但是解码时选择了英文模式，预测时添加 --rec_char_type=‘ch’ 试一下呢？

问题1,2有时候会出现，有时候不会出现。

**Comment by tink2123** [comment]
> 不能同时显示吗，在预测时，我也出现了类似的错误，我已经设置如上所述的参数，但依旧出现了类似的问题
英文模型训练时预测类别数为37（26个小写字母+10数字+blank位），中文为6000+类，rec_char_type 的解码方式不同，预测index后执行decode的结果也不同，这取决于你选择的字典。如果rec_char_type=en则只支持37类，使用训练好的中文模型去预测时，字典顺序不同可能会得到>37的index，这就会越界。 所以如果你想预测中文，请设置为--rec_char_type=‘ch’

**Comment by tink2123** [comment]
>Intel MKL function load error: cpu specific dynamic library is not loaded.

请问您安装的paddle版本是？

**Comment by ZhaoyangLi-nju** [comment]
> > 不能同时显示吗，在预测时，我也出现了类似的错误，我已经设置如上所述的参数，但依旧出现了类似的问题
> 
> 英文模型训练时预测类别数为37（26个小写字母+10数字+blank位），中文为6000+类，rec_char_type 的解码方式不同，预测index后执行decode的结果也不同，这取决于你选择的字典。如果rec_char_type=en则只支持37类，使用训练好的中文模型去预测时，字典顺序不同可能会得到>37的index，这就会越界。 所以如果你想预测中文，请设置为--rec_char_type=‘ch’
我是用的是支持

> > Intel MKL function load error: cpu specific dynamic library is not loaded.
> 
> 请问您安装的paddle版本是？

1.7.2，在python环境下运行的，出现了这个错误，

**Comment by ZhaoyangLi-nju** [comment]
> > 不能同时显示吗，在预测时，我也出现了类似的错误，我已经设置如上所述的参数，但依旧出现了类似的问题
> 
> 英文模型训练时预测类别数为37（26个小写字母+10数字+blank位），中文为6000+类，rec_char_type 的解码方式不同，预测index后执行decode的结果也不同，这取决于你选择的字典。如果rec_char_type=en则只支持37类，使用训练好的中文模型去预测时，字典顺序不同可能会得到>37的index，这就会越界。 所以如果你想预测中文，请设置为--rec_char_type=‘ch’

这个情况感觉同时发起多个请求时产生的，rec_char_type='ch'是这么设置的。

**Comment by tink2123** [comment]
>1.7.2，在python环境下运行的

CPU or GPU , 机器型号是？如果是GPU请提供一下 cuda 版本 和 cuDNN 版本。

> rec_char_type='ch'是这么设置的。
设置 ‘ch’ 时也会报错吗？请问预测命令是？我们自测一下

**Comment by ZhaoyangLi-nju** [comment]
前者，是在CPU(E5-2650)下运行的，linux(Debain)，也是同时多个线程访问会产生这个问题。
后者，这种问题，只有在同时发起多个线程去访问，会产生这种问题。单个线程不会产生这种问题。

**Comment by ZhaoyangLi-nju** [comment]
> > 1.7.2，在python环境下运行的
> 
> CPU or GPU , 机器型号是？如果是GPU请提供一下 cuda 版本 和 cuDNN 版本。
> 
> > rec_char_type='ch'是这么设置的。
> > 设置 ‘ch’ 时也会报错吗？请问预测命令是？我们自测一下

感觉很像是线程之间交叉，但是python3不是自带锁吗

**Comment by ZhaoyangLi-nju** [comment]
> > 1.7.2，在python环境下运行的
> 
> CPU or GPU , 机器型号是？如果是GPU请提供一下 cuda 版本 和 cuDNN 版本。
> 
> > rec_char_type='ch'是这么设置的。
> > 设置 ‘ch’ 时也会报错吗？请问预测命令是？我们自测一下

刚试了下，intel MKL ***error，单线程下也会错，时好时坏，很奇怪

**Comment by tink2123** [comment]
建议安装一个docker，可以避免环境问题
`sudo docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash`

**Comment by dyning** [comment]
如果遇到intel MKL ***error，单线程下也会错，请参考 https://github.com/PaddlePaddle/PaddleOCR/issues/440
