### ISSUE TITLE
生成的数据，背景文字干扰太大。背景字体没有去除

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#1880]

**Comment by cxy86121** [comment]
可以在保留最后结果时 ，只保留fake_text.jpg，再用OpenCV添加背景。
批量生成时把synthesisers.py中倒数第三、四行改成
fake_bg = synth_result['fake_bg']
self.writer.save_image(fake_bg, text_input_label)
就可以了

**Comment by aishangmaxiaoming** [comment]
> 可以在保留最后结果时 ，只保留fake_text.jpg，再用OpenCV添加背景。
> 批量生成时把synthesisers.py中倒数第三、四行改成
> fake_bg = synth_result['fake_bg']
> self.writer.save_image(fake_bg, text_input_label)
> 就可以了

再用OpenCV添加背景,是指什么意思呢？

**Comment by cxy86121** [comment]
只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午3:16
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"Cxy"<861210578@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 生成的数据，背景文字干扰太大。背景字体没有去除 (#1880)





  
可以在保留最后结果时 ，只保留fake_text.jpg，再用OpenCV添加背景。
 批量生成时把synthesisers.py中倒数第三、四行改成
 fake_bg = synth_result['fake_bg']
 self.writer.save_image(fake_bg, text_input_label)
 就可以了
  
再用OpenCV添加背景,是指什么意思呢？

**Comment by aishangmaxiaoming** [comment]
好的，谢谢

**Comment by aishangmaxiaoming** [comment]
> 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> […](#)

为什么按照批量生成时把synthesisers.py中倒数第三、四行改成
fake_bg = synth_result['fake_bg']
self.writer.save_image(fake_bg, text_input_label)，生成的图像大部分没有新的文字，即还是原图的背景和文字，

**Comment by aishangmaxiaoming** [comment]
> 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> […](#)

就是咱们的算法没有区分出我的原图的背景和图片导致的，原图是自然场景的图片

**Comment by cxy86121** [comment]
> > 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> > […](#)
> 
> 为什么按照批量生成时把synthesisers.py中倒数第三、四行改成
> fake_bg = synth_result['fake_bg']
> self.writer.save_image(fake_bg, text_input_label)，生成的图像大部分没有新的文字，即还是原图的背景和文字，
是不是没有输入新的文本？dataset_config.yml 文件中CorpusGenerator部分的corpus_file处添加你的输入文本.txt文件

**Comment by cxy86121** [comment]
> > 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> > […](#)
> 
> 就是咱们的算法没有区分出我的原图的背景和文字导致的，原图是自然场景的图片

是的，模型在抠图时没有把前景部分完全去除

**Comment by aishangmaxiaoming** [comment]
> > 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> > […](#)
> 
> 为什么按照批量生成时把synthesisers.py中倒数第三、四行改成
> fake_bg = synth_result['fake_bg']
> self.writer.save_image(fake_bg, text_input_label)，生成的图像大部分没有新的文字，即还是原图的背景和文字，
> 是不是没有输入新的文本？dataset_config.yml 文件中CorpusGenerator部分的corpus_file处添加你的输入文本.txt文件

有的，有输入文本，所以应该是咱们的算法对自然场景的文字，不鲁棒？训练数据没有加入自然场景？

**Comment by cxy86121** [comment]
> > > 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> > > […](#)
> > 
> > 
> > 为什么按照批量生成时把synthesisers.py中倒数第三、四行改成
> > fake_bg = synth_result['fake_bg']
> > self.writer.save_image(fake_bg, text_input_label)，生成的图像大部分没有新的文字，即还是原图的背景和文字，
> > 是不是没有输入新的文本？dataset_config.yml 文件中CorpusGenerator部分的corpus_file处添加你的输入文本.txt文件
> 
> 有的，有输入文本，所以应该是咱们的算法对自然场景的文字，不鲁棒？训练数据没有加入自然场景？

不应该啊，我不是作者，也是使用者。生成场景文本是可以的，你再查一下文档看看。

**Comment by aishangmaxiaoming** [comment]
> > > > 只保留fake_text.jpg，然后再自己写代码把背景添加上去，fake_text.jpg的背景全部为灰色，比如说我们想让背景为红色，就找一张红色的图片，然后写代码将红色背景和fake_text.jpg融合到一起。
> > > > […](#)
> > > 
> > > 
> > > 为什么按照批量生成时把synthesisers.py中倒数第三、四行改成
> > > fake_bg = synth_result['fake_bg']
> > > self.writer.save_image(fake_bg, text_input_label)，生成的图像大部分没有新的文字，即还是原图的背景和文字，
> > > 是不是没有输入新的文本？dataset_config.yml 文件中CorpusGenerator部分的corpus_file处添加你的输入文本.txt文件
> > 
> > 
> > 有的，有输入文本，所以应该是咱们的算法对自然场景的文字，不鲁棒？训练数据没有加入自然场景？
> 
> 不应该啊，我不是作者，也是使用者。生成场景文本是可以的，你再查一下文档看看。

使用方法没问题，所以能加个微信聊聊你是怎么做的吗，对于自然场景图。我这边自然场景的就是不鲁棒，基本都不行

**Comment by WenmuZhou** [comment]
解决了吗
