### ISSUE TITLE
GPU use_gpu=true not working

### ISSUE THREAD

**Issue by chuk-yong** [PaddlePaddle/PaddleOCR#1882]
Hi!
I have a RTX 2080 Max-Q with 8Gb of RAM.

I run the program with use_gpu = False with no problem.  However, when I set use_gpu= True, it stops with the following:

Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\User/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\User/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\User/.paddleocr/2.0/rec/en', use_angle_cls=True, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
W0130 10:18:54.899268  9272 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
E0130 10:18:57.178395  9272 analysis_predictor.cc:585] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E0130 10:18:57.178395  9272 analysis_predictor.cc:588] Try to shink the value by setting AnalysisConfig::EnableGpu(...)

I tried setting gpu_mem=4000, it stops with just the following line:
W0130 10:31:38.553580 12884 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.

**Comment by WenmuZhou** [comment]
How large is your GPU memory? Set gpu_mem is smaller than your memory

**Comment by chuk-yong** [comment]
I have a RTX 2080 Max-Q with 8Gb of RAM.

When I set to  smaller value gpu_mem=4000, it stops with just the following line:
W0130 10:31:38.553580 12884 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.

**Comment by WenmuZhou** [comment]
try latest code and paddle

**Comment by omar16100** [comment]
@WenmuZhou Using latest code, still unable to use GPU. Maybe I will open another, the error message is this : 

```
Config use_gpu cannot be set as true while you are using paddlepaddle cpu version ! 
Please try: 
        1. Install paddlepaddle-gpu to run model on GPU 
        2. Set use_gpu as false in config file to run model on CPU
```

**Comment by Evezerest** [comment]
please Install paddlepaddle-gpu to run model

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by omar16100** [comment]
Hi

paddlepaddle-gpu was installed but paddlepaddle was also installed

After uninstalling paddlepaddle, it resolved my issue. Thanks.

**Comment by ganeshmohane-aisolo** [comment]
My Fix, I also faced same problem - 

first uninstall paddlepaddle which is default cpu only for gpu support u need to install paddlepaddle-gpu but pip does not gives latest version so try this docs - https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/develop/install/pip/linux-pip_en.html

you will find there gpu section u can copy paste in your docker to install or run direct to install in local and also for paddleocr set it  conditioni >= 3.0.0
