### ISSUE TITLE
方向分类器命令报错

### ISSUE THREAD

**Issue by BeeFly616** [PaddlePaddle/PaddleOCR#1883]
`AssertionError: key load_static_weights not in sub_keys: {'debug': False, 'algorithm': 'CLS', 'use_gpu': False, 'epoch_num': 100, 'log_smooth_window': 20, 'print_batch_step': 100, 'save_model_dir': 'output/cls_mv3', 'save_epoch_step': 3, 'eval_batch_step': 500, 'train_batch_size_per_card': 512, 'test_batch_size_per_card': 512, 'image_shape': [3, 48, 192], 'label_list': ['0', '180'], 'distort': True, 'reader_yml': './configs/cls/cls_reader.yml', 'pretrain_weights': None, 'checkpoints': '/root/model/paddle_ocr/pretrain/ch_ppocr_mobile_v1.1_cls_train/best_accuracy', 'save_inference_dir': None, 'infer_img': None}, please check your running command.`

**Comment by BeeFly616** [comment]
原本的命令为：  
python3 tools/infer_cls.py -c configs/cls/cls_mv3.yml -o Global.pretrained_model={path/to/weights}/best_accuracy Global.load_static_weights=false Global.infer_img=doc/imgs_words/ch/word_1.jpg

改为：  
python3  tools/infer_cls.py -c configs/cls/cls_mv3.yml -o Global.checkpoints={path/to/weights}/best_accuracy Global.infer_img=doc/imgs_words/ch/word_1.jp

**Comment by WenmuZhou** [comment]
建议按照原本的命令使用

**Comment by BeeFly616** [comment]
您说的是要重新装个库吗？我运行了v2.0的模型和v1.1的模型结果都是错误的

**Comment by WenmuZhou** [comment]
不是，你仔细理解一下我的意思

**Comment by BeeFly616** [comment]
首先，您说我用的代码是动态图的，并且建议按照原本的命令使用（原本的命令就是我用的那个代码呀，因为我是按照官方文档运行的）。按照这个推论，所以官方代码是动态图的代码。

所以，意思就是说我的模型是错误的。因为您说我的模型是静态图的。

而v2.0模型是动态图的。v1.1的模型是静态图。这个在官方文档里能找到。

所以我尝试了运行了v2.0的模型。

**Comment by WenmuZhou** [comment]
不好意思，我之前没有描述清楚
1. 你运行的命令是动态图的
2. 你的配置文件是静态图的
3. 你的模型之前的静态图的
静态图的配置，模型和代码需要使用develop分支
动态图的配置，模型和代码需要使用dygraph分支

**Comment by BeeFly616** [comment]
好的，谢谢，明白了
