### ISSUE TITLE
ocr支持对中文汉字间的空格识别么，比如因为排版等问题，2个汉字间隔了3个空格之类的

### ISSUE THREAD

**Issue by lyxx3068956** [PaddlePaddle/PaddleOCR#1885]

**Comment by WenmuZhou** [comment]
中英文模型是支持空格的，多个空格最后可能输出只有一个

**Comment by lyxx3068956** [comment]
![1-result](https://user-images.githubusercontent.com/76687209/106405556-90e5e680-6471-11eb-92a8-d2b823acee2f.png)

PaddlePaddle  2.0.0rc1
PaddleOCR   git clone https://github.com/PaddlePaddle/PaddleOCR

模型参考
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/quickstart.md
超轻量级模型
# 下载超轻量级中文OCR模型的检测模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar && tar xf ch_ppocr_mobile_v2.0_det_infer.tar
# 下载超轻量级中文OCR模型的识别模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar && tar xf ch_ppocr_mobile_v2.0_rec_infer.tar
# 下载超轻量级中文OCR模型的文本方向分类器模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar && tar xf ch_ppocr_mobile_v2.0_cls_infer.tar
CPU预测命令
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/1.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  
--rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" 
--use_angle_cls=True --use_space_char=True --use_gpu=False

![1](https://user-images.githubusercontent.com/76687209/106405554-8fb4b980-6471-11eb-8573-f25f2aedd9c8.jpg)

**Comment by lyxx3068956** [comment]
> 中英文模型是支持空格的，多个空格最后可能输出只有一个



> 中英文模型是支持空格的，多个空格最后可能输出只有一个

**Comment by tink2123** [comment]
由于通用场景中，对中文的空格识别需求不多。训练样本中主要都是英文空格，因此对中文效果不好，如果需要的话建议在自己的数据上调优。
另外请教下：像您的这个场景，为什么需要识别出中文空格呢？不会影响阅读吗

**Comment by lyxx3068956** [comment]
> 由于通用场景中，对中文的空格识别需求不多。训练样本中主要都是英文空格，因此对中文效果不好，如果需要的话建议在自己的数据上调优。
> 另外请教下：像您的这个场景，为什么需要识别出中文空格呢？不会影响阅读吗

呃，有需求，需要识别出来，然后尽量在原来的位置复原，包括大小位置啥的要尽量一模一样。如上图片只是随便找的测试示例。

**Comment by DuckJ** [comment]
@tink2123 请问下 中英混合模型支持空格的话，也是最后加的英文空格数据finetune的么，还是直接一起训练的？只想支持英文空格的话，中文之间的空格不需要标注吧

**Comment by lucasjinreal** [comment]
英文也没空格好吧，中英文混合的场景都没有空格

**Comment by GreatV** [comment]
@lucasjinreal 你在自己的场景上再训练一下就好了。
