### ISSUE TITLE
您好，想问一下EAST模型检测文本框的长度是否有限制

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/PaddleOCR#1886]
我训练了一个模型，发现一些较长的文本框未检测充分，只检测到其大概80%长度的部分

**Comment by WenmuZhou** [comment]
这是east算法本身的限制哈，网络感受野不够

**Comment by ahsdx** [comment]
好的，谢谢。那请问有什么模型推荐呢？请问百度自研的SAST算法可以解决这个问题吗？

**Comment by WenmuZhou** [comment]
sast和db在长文本上面都比east要好一些

**Comment by ahsdx** [comment]
好的，谢谢



---原始邮件---
发件人: "zhoujun"<notifications@github.com&gt;
发送时间: 2021年2月4日(周四) 晚上7:36
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "ahsdx"<2589561091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 您好，想问一下EAST模型检测文本框的长度是否有限制 (#1886)




 
sast和db在长文本上面都比east要好一些
