### ISSUE TITLE
是否能指定文本方向，固定为竖板

### ISSUE THREAD

**Issue by imageorbit** [PaddlePaddle/PaddleOCR#1887]
做一些古文的识别，都是竖板的，但大部分都给识别成横版了，有没有参数能指定为竖板识别的，后者简单的代码修改，在哪里改？

**Comment by littletomatodonkey** [comment]
你好，可以给一张图片case来看下吗？

**Comment by imageorbit** [comment]
[印刷体.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5910898/default.zip)
![txt_27 jpg](https://user-images.githubusercontent.com/72195144/106596998-bddceb00-6590-11eb-807c-3db8194717f9.png)

**Comment by WenmuZhou** [comment]
这种可以识别之后自己改一下print就行了
