### ISSUE TITLE
请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#189]

**Comment by wangning7149** [comment]
请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧

**Comment by MissPenguin** [comment]
> 请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧

对的，不要求是矩形。

**Comment by LDOUBLEV** [comment]
> 请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧

是的

**Comment by wangning7149** [comment]
> 请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧
> 
> 对的，不要求是矩形。

谢谢

**Comment by wangning7149** [comment]
> 请问，训练DB模型时，训练数据的四个点不用是矩形，任意四个点就可以吧
> 
> 是的

谢谢
