### ISSUE TITLE
训练到eval阶段卡住问题。

### ISSUE THREAD

**Issue by zhaopu0710** [PaddlePaddle/PaddleOCR#1892]
如下图所示：
![figure1](https://user-images.githubusercontent.com/50993924/106418693-e29e6900-6491-11eb-93b0-5e69afe1c2f7.png)
经过调试发现在`PaddleOCR/tools/program.py`代码中卡死：
![image](https://user-images.githubusercontent.com/50993924/106418881-3d37c500-6492-11eb-959f-3e51324655f5.png)
经过长时间的运行，发现`eval`进度进行了一部分，然后程序中断了。

运行环境：
`ubuntu20.04`
`python3.8`
 `paddlepaddle2.0.0`
  ` cuda10.1`
求大佬帮忙看看是什么问题。

**Comment by littletomatodonkey** [comment]
Eval中的num worker改为0，batch size减小一些可以吗？

**Comment by zhaopu0710** [comment]
> Eval中的num worker改为0，batch size减小一些可以吗？

莫名奇妙好了。。。我好像是把搜狗输入法卸载了就好了....

**Comment by littletomatodonkey** [comment]
好的，有啥问题的话欢迎随时反馈~

**Comment by lcdisme** [comment]
我也遇到了相同的问题，每次训练都会卡这儿
[2021/07/12 07:55:23] root INFO: epoch: [1/100], iter: 1100, lr: 0.001000, loss: 1.579126, score_loss: 0.213759, border_loss: 0.109167, tvo_loss: 0.531415, tco_loss: 0.297495, reader_cost: 0.23958 s, batch_cost: 0.62122 s, samples: 800, ips: 12.87798
eval model::   0% 1/200 [00:00<01:35,  2.08it/s]invalid poly
eval model::  89% 178/200 [27:24<00:15,  1.42it/s]
