### ISSUE TITLE
连接失效了

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#1893]
这个页面的连接
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/recognition.md#%E5%B0%8F%E8%AF%AD%E7%A7%8D

corpus
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/corpus

失效了

**Comment by TingquanGao** [comment]
您好，可以截图说明一下是页面中的哪个超链接么？我在这个页面中没看到您说的这个链接。

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，已经修复：#1905
