### ISSUE TITLE
请问怎么将shape=[32, 320, 3]的tensor转为shape=[1, 3, 32, 320]

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#1895]
我试了input_tensor = paddle.transpose(input_tensor, perm=[2, 0, 1])，结果为shape=[3，32, 320]，下一步该怎么转换呢

**Comment by AvenSun** [comment]
refer to [paddle.expand](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/manipulation/expand_cn.html#paddle.expand)

**Comment by littletomatodonkey** [comment]
如上所述

```
import paddle
a = paddle.rand([3,32,320])
b = paddle.expand(a, shape=[1] + a.shape)
```

![image](https://user-images.githubusercontent.com/14270174/106469592-71cf6f00-64da-11eb-8a0b-3fa7ffb15a41.png)

**Comment by cxy86121** [comment]
> refer to [paddle.expand](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/manipulation/expand_cn.html#paddle.expand)

谢谢！

**Comment by cxy86121** [comment]
> 如上所述
> 
> ```
> import paddle
> a = paddle.rand([3,32,320])
> b = paddle.expand(a, shape=[1] + a.shape)
> ```
> 
> ![image](https://user-images.githubusercontent.com/14270174/106469592-71cf6f00-64da-11eb-8a0b-3fa7ffb15a41.png)

谢谢！
