### ISSUE TITLE
增加东南亚的小语种

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#1896]
越南语 Vietnamese

vie

https://github.com/tesseract-ocr/langdata/tree/master/vie

老挝语 Lao

lao

https://github.com/tesseract-ocr/langdata/tree/master/lao

泰文 Thai

tha

https://github.com/tesseract-ocr/langdata/tree/master/tha

缅甸 Burmese

mya

https://github.com/tesseract-ocr/langdata/tree/master/mya

印尼 Indonesian

https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html

菲律宾

fil = Filipino (old  Tagalog)

tgl = Tagalog  (new Filipino)

**Comment by habout632** [comment]
这个 我要怎么贡献到代码库里面呢

**Comment by WenmuZhou** [comment]
可以看看最新的多语言文档

**Comment by wallon-ai** [comment]
> 这个 我要怎么贡献到代码库里面呢
你好，没找到印尼语的模型呢
