### ISSUE TITLE
NameError: name 'cur_metric' is not defined的问题解决办法

### ISSUE THREAD

**Issue by iamyoyo** [PaddlePaddle/PaddleOCR#1898]
你好，在运行程序时，出现一个错误提示
"E:\XXX\PaddleOCR\tools\program.py", line 257, in train
    ['{}: {}'.format(k, v) for k, v in cur_metric.items()]))
NameError: name 'cur_metric' is not defined
PaddleOCR/tools/program.py的第254行的变量名原为cur_metirc，需要修改为cur_metric

Hello, when running the program, there is an error prompt 
"E:\XXX\PaddleOCR\tools\ program.py ", line 257, in train
['{}: {}'.format(k, v) for k, v in cur_ metric.items ()]))
NameError: name 'cur_ metric' is not defined
PaddleOCR/tools/ program.py The variable name in line 254 of is cur_ Metirc, which needs to be changed to cur_ metric

**Comment by littletomatodonkey** [comment]
收到，感谢反馈~

**Comment by littletomatodonkey** [comment]
你好，已经修复，可以拉下最新代码
