### ISSUE TITLE
Scikit-image 与 numpy==1.16.4 不兼容

### ISSUE THREAD

**Issue by Ca2OH4** [PaddlePaddle/PaddleOCR#1899]
requirements.txt 文件中 numpy 未指定版本，默认会安装 numpy==1.16.4。
但是 numpy==1.16.4 与 scikit-image 0.18.1 不兼容，具体如下图所示：
![image](https://user-images.githubusercontent.com/42209827/106427794-ef778880-64a2-11eb-856e-40ddb66d9a59.png)

`python
ERROR: scikit-image 0.18.1 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
`
指定 numpy 版本为 1.16.5 即可。

**Comment by littletomatodonkey** [comment]
设置清华源的话，默认应该安装的1.20.0来着，或者你可以试着更新下pip
