### ISSUE TITLE
xml数据格式转icdar数据标注格式

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#190]
目前PaddleOCR 训练时使用的label是一个集合txt。且标注的格式固定，有限。
能否再增加两种常见的模式。
1.Json格式的。
2.xml的。
拿xml举例。

![1](https://user-images.githubusercontent.com/6395366/84373326-fd745280-ac0e-11ea-9f29-2fcb77edd46d.jpg)
应该在配置接口设定以哪种格式进行训练。
每张图的xml文件也不用进行合并。和图像的名称一致即可，同一个路径即可。
希望可以实现。
另：
目前的这种格式有什么好方式实现吗？或者是不是应该开放一个python代码，或者命令进行格式转化什么的。
感觉数据集制作起来很麻烦。

**Comment by LDOUBLEV** [comment]
数据集标注是比较麻烦，建议标注好后，将xml格式的标注用python代码转换成PaddleOCR的格式吧，python转换代码不会太难。

目前OCR检测的主流数据格式是我们现在使用的格式，暂时不会排期支持其他格式的数据

**Comment by LDOUBLEV** [comment]
如果是自己标注的检测数据，且格式是xml的，可以参考如下代码将其转换为icdar的格式：
```
"""
Code from LDOUBLEV: https://github.com/LDOUBLEV
Date: 2020.6.15
"""
import os
import cv2
import numpy as np
import math
import xml.dom.minidom as xmldom
from functools import reduce
import operator
from glob import glob
import json


def rect2rotateBox(box, angle):
    """
    box: [cx, cy, w, h]
    angle:
    """
    # x0 = (x - rx0) * cos(a) - (y - ry0) * sin(a) + rx0;
    # y0 = (x - rx0) * sin(a) + (y - ry0) * cos(a) + ry0

    cx, cy, w, h = box

    x0 = (max(0, cx - w/2.) - cx) * math.cos(angle) - (max(0, cy - h/2) - cy) * math.sin(angle) + cx
    y0 = (max(0, cx - w/2.) - cx) * math.sin(angle) + (max(0, cy - h/2) - cy) * math.cos(angle) + cy

    x1 = (cx + w / 2. - cx) * math.cos(angle) - (max(0, cy - h / 2) - cy) * math.sin(angle) + cx
    y1 = (cx + w / 2. - cx) * math.sin(angle) + (max(0, cy - h / 2) - cy) * math.cos(angle) + cy

    x2 = (cx + w / 2. - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
    y2 = (cx + w / 2. - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy

    x3 = (max(cx - w / 2., 0) - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
    y3 = (max(cx - w / 2., 0) - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy

    return [[x0, y0], [x1, y1], [x2, y2], [x3, y3]]


def test_rect2rotateBox():
    box = [754.7317, 1321.4268, 224.0, 65.0]
    box = rect2rotateBox(box, -3.08/180*math.pi)
    print(box)
    img_path = "~/OCR_Det-sample-sec/Image00002.jpg"
    src_im = cv2.imread(img_path)
    box = np.array(box).astype(np.int32).reshape(-1, 2)
    cv2.polylines(src_im, [box], True, color=(255, 255, 0), thickness=2)
    cv2.imwrite("./vis.jpg", src_im)


def rolabelimg2icdar(xmlpath, save_path):
    """
    :param xmlpath: str, the xml path
    :param save_path:  the saved file path
    :return:
    """

    if not os.path.exists(xmlpath):
        raise Exception("{} not exists!".format(xmlpath))
    if not os.path.exists(os.path.dirname(save_path)):
        os.makedirs(os.path.dirname(save_path))

    save_file = open(save_path, "w")

    for file in list(glob(os.path.join(xmlpath, "*.xml"))):
        fileName = os.path.basename(file).split('.')[0] + '.jpg'

        DOMTree = xmldom.parse(file)
        collection = DOMTree.documentElement
        imgSize = collection.getElementsByTagName('size')
        width = imgSize[0].getElementsByTagName('width')[0].childNodes[0].data
        height = imgSize[0].getElementsByTagName('height')[0].childNodes[0].data
        depth = imgSize[0].getElementsByTagName('depth')[0].childNodes[0].data

        imgObjects = collection.getElementsByTagName('object')

        data = []
        for imgObject in imgObjects:
            label = imgObject.getElementsByTagName('name')[0].childNodes[0].data
            imgBox = imgObject.getElementsByTagName('robndbox')[0]
            cx = imgBox.getElementsByTagName('cx')[0].childNodes[0].data
            cy = imgBox.getElementsByTagName('cy')[0].childNodes[0].data
            w = imgBox.getElementsByTagName('w')[0].childNodes[0].data
            h = imgBox.getElementsByTagName('h')[0].childNodes[0].data
            angle = imgBox.getElementsByTagName('angle')[0].childNodes[0].data

            bboxList = [float(cx), float(cy), float(w), float(h)]
            robndbox = rect2rotateBox(bboxList, -float(angle)/180.*math.pi)
            dic = {"transcription": label, "points": robndbox}
            data.append(dic)
        line = fileName + '\t' + json.dumps(data) + '\n'
        save_file.writelines(line)
    print("The new annotation has saved in {}".format(save_path))


if __name__ == '__main__':

    file_path = '~/OCR_detdata/OCR_Det-sample-sec/'

    rolabelimg2icdar(file_path, "./anno.txt")
```

**Comment by SixGodGG** [comment]
上面的还有些bug，我们继续修复。

**Comment by LDOUBLEV** [comment]
> 如果是自己标注的检测数据，且格式是xml的，可以参考如下代码将其转换为icdar的格式：
> 
> ```
> """
> Code from LDOUBLEV: https://github.com/LDOUBLEV
> Date: 2020.6.15
> """
> import os
> import cv2
> import numpy as np
> import math
> import xml.dom.minidom as xmldom
> from functools import reduce
> import operator
> from glob import glob
> import json
> 
> 
> def rect2rotateBox(box, angle):
>     """
>     box: [cx, cy, w, h]
>     angle:
>     """
>     # x0 = (x - rx0) * cos(a) - (y - ry0) * sin(a) + rx0;
>     # y0 = (x - rx0) * sin(a) + (y - ry0) * cos(a) + ry0
> 
>     cx, cy, w, h = box
> 
>     x0 = (max(0, cx - w/2.) - cx) * math.cos(angle) - (max(0, cy - h/2) - cy) * math.sin(angle) + cx
>     y0 = (max(0, cx - w/2.) - cx) * math.sin(angle) + (max(0, cy - h/2) - cy) * math.cos(angle) + cy
> 
>     x1 = (cx + w / 2. - cx) * math.cos(angle) - (max(0, cy - h / 2) - cy) * math.sin(angle) + cx
>     y1 = (cx + w / 2. - cx) * math.sin(angle) + (max(0, cy - h / 2) - cy) * math.cos(angle) + cy
> 
>     x2 = (cx + w / 2. - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
>     y2 = (cx + w / 2. - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy
> 
>     x3 = (max(cx - w / 2., 0) - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
>     y3 = (max(cx - w / 2., 0) - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy
> 
>     return [[x0, y0], [x1, y1], [x2, y2], [x3, y3]]
> 
> 
> def test_rect2rotateBox():
>     box = [754.7317, 1321.4268, 224.0, 65.0]
>     box = rect2rotateBox(box, -3.08/180*math.pi)
>     print(box)
>     img_path = "~/OCR_Det-sample-sec/Image00002.jpg"
>     src_im = cv2.imread(img_path)
>     box = np.array(box).astype(np.int32).reshape(-1, 2)
>     cv2.polylines(src_im, [box], True, color=(255, 255, 0), thickness=2)
>     cv2.imwrite("./vis.jpg", src_im)
> 
> 
> def rolabelimg2icdar(xmlpath, save_path):
>     """
>     :param xmlpath: str, the xml path
>     :param save_path:  the saved file path
>     :return:
>     """
> 
>     if not os.path.exists(xmlpath):
>         raise Exception("{} not exists!".format(xmlpath))
>     if not os.path.exists(os.path.dirname(save_path)):
>         os.makedirs(os.path.dirname(save_path))
> 
>     save_file = open(save_path, "w")
> 
>     for file in list(glob(os.path.join(xmlpath, "*.xml"))):
>         fileName = os.path.basename(file).split('.')[0] + '.jpg'
> 
>         DOMTree = xmldom.parse(file)
>         collection = DOMTree.documentElement
>         imgSize = collection.getElementsByTagName('size')
>         width = imgSize[0].getElementsByTagName('width')[0].childNodes[0].data
>         height = imgSize[0].getElementsByTagName('height')[0].childNodes[0].data
>         depth = imgSize[0].getElementsByTagName('depth')[0].childNodes[0].data
> 
>         imgObjects = collection.getElementsByTagName('object')
> 
>         data = []
>         for imgObject in imgObjects:
>             label = imgObject.getElementsByTagName('name')[0].childNodes[0].data
>             imgBox = imgObject.getElementsByTagName('robndbox')[0]
>             cx = imgBox.getElementsByTagName('cx')[0].childNodes[0].data
>             cy = imgBox.getElementsByTagName('cy')[0].childNodes[0].data
>             w = imgBox.getElementsByTagName('w')[0].childNodes[0].data
>             h = imgBox.getElementsByTagName('h')[0].childNodes[0].data
>             angle = imgBox.getElementsByTagName('angle')[0].childNodes[0].data
> 
>             bboxList = [float(cx), float(cy), float(w), float(h)]
>             robndbox = rect2rotateBox(bboxList, -float(angle)/180.*math.pi)
>             dic = {"transcription": label, "points": robndbox}
>             data.append(dic)
>         line = fileName + '\t' + json.dumps(data) + '\n'
>         save_file.writelines(line)
>     print("The new annotation has saved in {}".format(save_path))
> 
> 
> if __name__ == '__main__':
> 
>     file_path = '~/OCR_detdata/OCR_Det-sample-sec/'
> 
>     rolabelimg2icdar(file_path, "./anno.txt")
> ```

**Comment by LDOUBLEV** [comment]
> 上面的还有些bug，我们继续修复。

bug已修复；
补充：
1. 适用于检测标注格式转换
2. 用的标注工具是 ： https://github.com/cgvict/roLabelImg/projects

**Comment by wangning7149** [comment]
> 
> 
> 数据集标注是比较麻烦，建议标注好后，将xml格式的标注用python代码转换成PaddleOCR的格式吧，python转换代码不会太难。
> 
> 目前OCR检测的主流数据格式是我们现在使用的格式，暂时不会排期支持其他格式的数据
转成paddle格式，我见txt文件里面会有空格，其实有无空格对标签的读取没有影响吧

**Comment by denonzhu** [comment]
roLabelImg标注的转imdb 格式，稍微修改了一下代码，可以支持参数

`
import os
import json
from xml.etree.ElementTree import parse
import math
import argparse


# 旋转的盒子转成坐标
def rect2RotateBox(box, angle):
    """
    box: [cx, cy, w, h]
    angle:
    """
    # x0 = (x - rx0) * cos(a) - (y - ry0) * sin(a) + rx0;
    # y0 = (x - rx0) * sin(a) + (y - ry0) * cos(a) + ry0

    cx, cy, w, h = box

    x0 = (max(0, cx - w / 2.) - cx) * math.cos(angle) - (max(0, cy - h / 2) - cy) * math.sin(angle) + cx
    y0 = (max(0, cx - w / 2.) - cx) * math.sin(angle) + (max(0, cy - h / 2) - cy) * math.cos(angle) + cy

    x1 = (cx + w / 2. - cx) * math.cos(angle) - (max(0, cy - h / 2) - cy) * math.sin(angle) + cx
    y1 = (cx + w / 2. - cx) * math.sin(angle) + (max(0, cy - h / 2) - cy) * math.cos(angle) + cy

    x2 = (cx + w / 2. - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
    y2 = (cx + w / 2. - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy

    x3 = (max(cx - w / 2., 0) - cx) * math.cos(angle) - (cy + h / 2 - cy) * math.sin(angle) + cx
    y3 = (max(cx - w / 2., 0) - cx) * math.sin(angle) + (cy + h / 2 - cy) * math.cos(angle) + cy

    return [[x0, y0], [x1, y1], [x2, y2], [x3, y3]]


def rolabelimg2icdar(root_path, xml_path, output_label):
    # path = "/Users/denonzhu/Developer/AI/PaddleOCR/train_data/waybillOcr/xml"  # 文件夹目录
    xml_path = root_path + xml_path
    files = os.listdir(xml_path)  # 得到文件夹下的所有文件名称
    out_file = open(root_path + output_label, 'w')
    for file in files:  # 遍历文件夹
        if not os.path.isdir(file):  # 判断是否是文件夹，不是文件夹才打开
            doc = parse(xml_path + "/" + file)
            # Extract and output tags of interest
            label = []
            img_path = 'img/' + doc.findtext('path')
            for item in doc.iterfind('object'):
                try:
                    name = item.findtext('name')
                    robndbox = item.find('robndbox')
                    cx = robndbox.findtext('cx')
                    cy = robndbox.findtext('cy')
                    w = robndbox.findtext('w')
                    h = robndbox.findtext('h')
                    angle = robndbox.findtext('angle')
                    points_list = [float(cx), float(cy), float(w), float(h)]
                    points = rect2RotateBox(points_list, -(math.pi - float(angle)))
                    dic = {"transcription": name, "points": points}
                    label.append(dic)
                except Exception as e:
                    print('Reason:', e)
        out_file.write(img_path + '\t' + json.dumps(label, ensure_ascii=False) + '\n')


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--root_path',
        type=str,
        default=".",
        help='The root directory of images. ')
    parser.add_argument(
        '--input_path',
        type=str,
        default=".",
        help='Input_label or input path to be converted')
    parser.add_argument(
        '--output_label',
        type=str,
        default="out_label.txt",
        help='Output file name')

    args = parser.parse_args()
    rolabelimg2icdar(args.root_path, args.input_path, args.output_label)
`

使用方法：
`
python3 gen_ocr_label.py --root_path="waybillOcr/" --input_path="xml" --output_label="train_waybill_label.txt"
`

**Comment by hwangyl** [comment]
import os
import cv2
import numpy as np
import math
import xml.dom.minidom as xmldom
from glob import glob
import json


def rotatepoint(xc, yc, xp, yp, theta):
    xoff = xp-xc
    yoff = yp-yc
    cosTheta = math.cos(theta)
    sinTheta = math.sin(theta)
    pResx = cosTheta * xoff + sinTheta * yoff
    pResy = - sinTheta * xoff + cosTheta * yoff
    return xc+pResx, yc+pResy


def rect2rotatebox(box, angle):
    cx, cy, w, h = box
    p0x, p0y = rotatepoint(cx, cy, cx - w / 2, cy - h / 2, -angle)
    p1x, p1y = rotatepoint(cx, cy, cx + w / 2, cy - h / 2, -angle)
    p2x, p2y = rotatepoint(cx, cy, cx + w / 2, cy + h / 2, -angle)
    p3x, p3y = rotatepoint(cx, cy, cx - w / 2, cy + h / 2, -angle)
    points = [(p0x, p0y), (p1x, p1y), (p2x, p2y), (p3x, p3y)]
    return points


def horizon_rect2box(xmin, ymin, xmax, ymax):
    p0x, p0y = xmin, ymin
    p1x, p1y = xmax, ymin
    p2x, p2y = xmin, ymax
    p3x, p3y = xmax, ymax
    points = [(p0x, p0y), (p1x, p1y), (p2x, p2y), (p3x, p3y)]
    return points


def test_rect2rotatebox():
    box = [512.6081, 435.9595, 279.0, 145.0]
    angle = 2.671593
    box = rect2rotatebox(box, angle)
    img_path = "a.jpg"
    src_img = cv2.imread(img_path)
    box = np.array(box).astype(np.int32).reshape(-1, 2)
    cv2.polylines(src_img, [box], True, color=(0, 0, 255), thickness=2)
    cv2.imwrite("test.jpg", src_img)


def rolabelimg2icdar(xmlpath, save_path):
    if not os.path.exists(xmlpath):
        raise Exception("{} not exist".format(xmlpath))

    if not os.path.exists(os.path.dirname(save_path)):
        os.mkdir((os.path.dirname(save_path)))
    save_file = open(save_path, "w")

    for file in glob(xmlpath + "/*.xml"):
        fileName = os.path.basename(file).split('.')[0] + ".jpg"
        DOMTree = xmldom.parse(file)
        collection = DOMTree.documentElement
        imgSize = collection.getElementsByTagName('size')
        width = imgSize[0].getElementsByTagName('width')[0].childNodes[0].data
        height = imgSize[0].getElementsByTagName('height')[0].childNodes[0].data
        depth = imgSize[0].getElementsByTagName('depth')[0].childNodes[0].data

        imgObjects = collection.getElementsByTagName('object')

        data = []
        for imgObject in imgObjects:
            label = imgObject.getElementsByTagName('name')[0].childNodes[0].data
            box_type = imgObject.getElementsByTagName('type')[0].childNodes[0].data
            if box_type == 'robndbox':
                cx = imgObject.getElementsByTagName('cx')[0].childNodes[0].data
                cy = imgObject.getElementsByTagName('cy')[0].childNodes[0].data
                w = imgObject.getElementsByTagName('w')[0].childNodes[0].data
                h = imgObject.getElementsByTagName('h')[0].childNodes[0].data
                angle = imgObject.getElementsByTagName('angle')[0].childNodes[0].data
                bbox_list = [float(cx), float(cy), float(w), float(h)]
                robndbox = rect2rotatebox(bbox_list, float(angle))
                dic = {"transcription": label, "points": robndbox}
                data.append(dic)
            if box_type == 'bndbox':
                xmin = imgObject.getElementsByTagName('xmin')[0].childNodes[0].data
                ymin = imgObject.getElementsByTagName('ymin')[0].childNodes[0].data
                xmax = imgObject.getElementsByTagName('xmax')[0].childNodes[0].data
                ymax = imgObject.getElementsByTagName('ymax')[0].childNodes[0].data
                bndbox = horizon_rect2box(xmin, ymin, xmax, ymax)
                dic = {"transcription": label, "points": bndbox}
                data.append(dic)
            line = fileName + "\t" + json.dumps(data) + '\n'
            save_file.writelines(line)


if __name__ == "__main__":
    test_rect2rotatebox()
    xml_path = r"F:\work11\ocrdataset\detection\labels"
    save_path = r"F:\work11\ocrdataset\detection\results\annotation.txt"
    rolabelimg2icdar(xml_path, save_path)
