### ISSUE TITLE
身份证的后处理是要怎么做呢

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#1904]
使用PPOCR 识别出了信息 postprocessing 是要怎么做呢？
基于位置还是文本处理的呢 可不可以增加证件识别这模块 直接结构化信息 key-value

**Comment by littletomatodonkey** [comment]
目前提供的模型都是比较通用的模型，没有涉及太多的垂类后处理，这块如果需求比较急，可以先使用百度的商业ocr解决方案哈

**Comment by zouxiaoshi** [comment]
最简单的方案是文本内容，通过正则表达式筛选下就出来了。
或者，根据位置，身份证字段结构简单且固定，可通过相对位置找出来。
