### ISSUE TITLE
请问中文检测+识别模型识别不出来“篱”这个字应该怎么做

### ISSUE THREAD

**Issue by 1253970836** [PaddlePaddle/PaddleOCR#1907]
中文检测+识别模型识别不出来“篱”这个字，或者比较稠密的字也识别不准甚至直接漏掉，应该怎么继续训练或者怎么处理

**Comment by LDOUBLEV** [comment]
主要是我们的训练数据中这类字的数据比较少，建议你针对识别效果不好的字 合成一批数据，或者收集一批数据，加载我们的模型fine-tune训练

**Comment by 1253970836** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Double_V&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月4日(星期四) 上午10:34
收件人:&nbsp;&quot;PaddlePaddle/PaddleOCR&quot;<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;1253970836&quot;<1253970836@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 请问中文检测+识别模型识别不出来“篱”这个字应该怎么做 (#1907)
