### ISSUE TITLE
文字识别训练过程中有问题

### ISSUE THREAD

**Issue by WhutTjk** [PaddlePaddle/PaddleOCR#1908]
ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log
![image](https://user-images.githubusercontent.com/58941474/106543111-11731880-6540-11eb-844e-1b81ef9ce0de.png)

**Comment by LDOUBLEV** [comment]
报错是dataloader的第一个进程挂掉了，可以检查下你的数据有没有问题，tools/train.py中有test_reader()函数，可以使用这个函数调试数据读取器有没有问题
另外，`df -h`看下你机器上的/dev/shm 目录下是否还有大于8G的内存空间，如果已经被占满了，建议清理下，`rm -rf  /dev/shm/* `
