### ISSUE TITLE
运行预测代码的时候，错误是是 module "tools.infer"找不到

### ISSUE THREAD

**Issue by evelesliexx** [PaddlePaddle/PaddleOCR#191]
不知道怎么去处理这个问题，inference的模型都已经wget下载解压好了

**Comment by tink2123** [comment]
请在PaddleOCR 目录下设置环境变量，export PYTHONPATH=.

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/195
