### ISSUE TITLE
PPOCRLable.py 有安装了pyclipper，但提示找不到指定模块

### ISSUE THREAD

**Issue by tangjinhan** [PaddlePaddle/PaddleOCR#1910]
PPOCRLable.py 有安装了pyclipper，但提示找不到指定模块，有碰到过类似问题吗，谢谢!

>   File "D:\Work\Project\ocr_research\paddle\paddleOCR\PaddleOCR-develop\ppocr\data\det\make_shrink_map.py", line 11, in <module>
    import pyclipper
ImportError: DLL load failed: 找不到指定的模块。

**Comment by liu-zh** [comment]
您好，您解决了吗？

**Comment by tangjinhan** [comment]
> 您好，您解决了吗？

没有

**Comment by WenmuZhou** [comment]
感觉看起来是安装遇到了问题，重新安装试一下

**Comment by Kraken000** [comment]
有兄弟解决这个问题了吗，同问同问

**Comment by Kraken000** [comment]
> 有兄弟解决这个问题了吗，同问同问

重装pyclipper并不管用

**Comment by tangjinhan** [comment]
还没有



---原始邮件---
发件人: "Yan Jiang"<notifications@github.com&gt;
发送时间: 2021年2月24日(周三) 下午5:27
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "tangjinhan"<304526881@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PPOCRLable.py 有安装了pyclipper，但提示找不到指定模块 (#1910)




  
有兄弟解决这个问题了吗，同问同问
  
重装pyclipper并不管用

**Comment by Jverson** [comment]
我的pyclipper原来是1.2.1，我卸载并重新装了一个1.1.0，没再报这个错了。

**Comment by claire0227** [comment]
> 我的pyclipper原来是1.2.1，我卸载并重新装了一个1.1.0，没再报这个错了。

试过了，重新装1.1.0的版本可以解决
