### ISSUE TITLE
文字检测训练自己的数据集时出现了这个问题

### ISSUE THREAD

**Issue by Matthew-dhu** [PaddlePaddle/PaddleOCR#1911]
[2021/02/02 06:29:28] root INFO: load pretrained model from ['./pretrain_models/ResNet50_vd_ssld_pretrained/']
[2021/02/02 06:29:28] root INFO: train dataloader has 35199 iters, valid dataloader has 35198 iters
[2021/02/02 06:29:28] root INFO: During the training process, after the 4000th iteration, an evaluation is run every 5000 iterations
[2021/02/02 06:29:28] root INFO: Initialize indexs of datasets:['/data/dataset/paddle_dataset/detetion/train.txt']
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/data/projects/PaddleOCR/tools/program.py", line 192, in train
    for idx, batch in enumerate(train_dataloader):
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 709, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 8 workers exit unexpectedly, pids: 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088

    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by Matthew-dhu** [comment]
大佬们可以帮忙看一下吗。数据集的txt文件是这样的
train/0163-2_0-382&594_567&668-567&660_384&668_382&602_565&594-0_0_27_6_31_32_24-59-29.jpg      [{"transcription": "abc", "points": [[567, 660], [384, 668], [382, 602], [565, 594]]}]
train/0314-0_10-214&564_555&641-541&639_214&641_228&566_555&564-0_0_25_26_19_30_24-69-39.jpg    [{"transcription": "abc", "points": [[541, 639], [214, 641], [228, 566], [555, 564]]}]
train/0335-2_0-255&517_530&619-530&605_260&619_255&531_525&517-0_0_20_20_24_26_27-81-47.jpg     [{"transcription": "abc", "points": [[530, 605], [260, 619], [255, 531], [525, 517]]}]
train/0343-1_1-190&470_471&572-471&567_190&572_190&475_471&470-0_0_33_27_30_33_28-69-157.jpg    [{"transcription": "abc", "points": [[471, 567], [190, 572], [190, 475], [471, 470]]}]
train/0284-0_7-285&573_530&670-516&670_285&668_299&573_530&575-0_0_24_2_32_27_32-75-38.jpg      [{"transcription": "abc", "points": [[516, 670], [285, 668], [299, 573], [530, 575]]}]
train/0462-7_22-193&425_512&546-512&546_215&508_193&425_490&463-0_0_26_28_29_30_33-56-28.jpg    [{"transcription": "abc", "points": [[512, 546], [215, 508], [193, 425], [490, 463]]}]
train/0329-2_1-176&438_457&536-457&526_181&536_176&448_452&438-0_0_21_6_30_24_32-107-141.jpg    [{"transcription": "abc", "points": [[457, 526], [181, 536], [176, 448], [452, 438]]}]
train/0241-1_2-275&386_504&474-502&468_275&474_277&392_504&386-0_0_18_12_31_33_24-141-35.jpg    [{"transcription": "abc", "points": [[502, 468], [275, 474], [277, 392], [504, 386]]}]
train/0436-3_2-276&499_570&623-570&604_278&623_276&518_568&499-0_0_10_5_31_26_31-101-24.jpg     [{"transcription": "abc", "points": [[570, 604], [278, 623], [276, 518], [568, 499]]}]
train/0276-0_0-263&479_532&565-532&565_263&564_263&479_532&480-0_0_7_1_31_28_30-67-18.jpg       [{"transcription": "abc", "points": [[532, 565], [263, 564], [263, 479], [532, 480]]}]
train/0500-4_13-143&420_497&538-497&538_157&511_143&420_483&447-0_0_6_16_25_26_26-104-93.jpg    [{"transcription": "abc", "points": [[497, 538], [157, 511], [143, 420], [483, 447]]}]
train/0154-0_6-238&541_446&603-446&602_245&603_238&542_439&541-0_0_28_11_31_33_32-86-24.jpg     [{"transcription": "abc", "points": [[446, 602], [245, 603], [238, 542], [439, 541]]}]
train/0287-1_7-172&483_451&569-451&569_181&564_172&483_442&488-0_0_20_30_17_31_29-49-5.jpg      [{"transcription": "abc", "points": [[451, 569], [181, 564], [172, 483], [442, 488]]}]
train/0151-6_3-239&548_415&620-415&601_248&620_239&567_406&548-0_0_19_32_27_26_29-60-26.jpg     [{"transcription": "abc", "points": [[415, 601], [248, 620], [239, 567], [406, 548]]}]
train/0263-0_2-257&456_504&545-500&544_257&545_261&457_504&456-0_0_11_31_26_26_3-64-69.jpg      [{"transcription": "abc", "points": [[500, 544], [257, 545], [261, 457], [504, 456]]}]
train/0426-1_0-124&479_448&589-448&578_127&589_124&490_445&479-0_0_0_6_26_33_32-132-55.jpg      [{"transcription": "abc", "points": [[448, 578], [127, 589], [124, 490], [445, 479]]}]
train/0343-7_22-124&496_378&609-378&609_146&579_124&496_356&526-0_0_27_11_27_27_30-81-31.jpg    [{"transcription": "abc", "points": [[378, 609], [146, 579], [124, 496], [356, 526]]}]
train/0257-1_0-266&471_505&561-505&554_267&561_266&478_504&471-0_0_29_29_29_20_32-148-92.jpg    [{"transcription": "abc", "points": [[505, 554], [267, 561], [266, 478], [504, 471]]}]
train/0367-7_1-258&470_512&591-512&559_268&591_258&502_502&470-0_0_4_2_25_32_30-49-19.jpg       [{"transcription": "abc", "points": [[512, 559], [268, 591], [258, 502], [502, 470]]}]
train/0225-2_16-194&453_426&534-408&525_194&534_212&462_426&453-0_0_21_27_32_30_11-99-23.jpg    [{"transcription": "abc", "points": [[408, 525], [194, 534], [212, 462], [426, 453]]}]
train/0839-5_4-135&418_538&592-538&553_138&592_135&457_535&418-0_0_23_18_25_27_26-88-188.jpg    [{"transcription": "abc", "points": [[538, 553], [138, 592], [135, 457], [535, 418]]}]

**Comment by WenmuZhou** [comment]
是不是你的文件路径太长了，读取不到文件

**Comment by xialei2821212670** [comment]
我也遇到这个问题，我路径类似adb/image.png ，但是transcription 是中文

**Comment by WenmuZhou** [comment]
这个你们先检查一下https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/data/simple_dataset.py#L83  这一行有没有读取到图片

**Comment by Matthew-dhu** [comment]
文件名后面改了还是这样，图片我print了也读到了，应该不是这个问题，我还用了icdar数据集也一样的错误。
后面我把loader.num_workers改成了0就可以跑了，但是超过0就不能跑，不知道是为什么。

**Comment by WenmuZhou** [comment]
机器内存不够

**Comment by lamhoangtung** [comment]
I can confim I'm having the same problem. It can work with @Matthew-dhu suggestion by setting num_workers to 0. But other than 0, it will fail. Even if my machine had 50+ GB of free RAM.

**Comment by lexiaoyuan** [comment]
我也遇到了类似的问题：
```
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 708, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 8 workers exit unexpectedly, pids: 245, 246, 247, 248, 249, 250, 251, 252
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 99, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/paddle/PaddleOCR/tools/program.py", line 197, in train
    for idx, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
```
是通过配置`use_shared_memory: False`来解决的。

**Comment by xtyzhen** [comment]
会不会是bug？
https://blog.csdn.net/qq_37668436/article/details/114336142
用了百度aistudio，同样报错。无奈无法更改文件。

**Comment by WenmuZhou** [comment]
如果是docker里的话，需要shm空间够大

**Comment by wziji** [comment]
> 我也遇到了类似的问题：
> 
> ```
> ERROR:root:DataLoader reader thread raised an exception!
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
>     data = self._data_queue.get(timeout=self._timeout)
>   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 108, in get
>     raise Empty
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
>     batch = self._get_data()
>   File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 708, in _get_data
>     raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
> RuntimeError: DataLoader 8 workers exit unexpectedly, pids: 245, 246, 247, 248, 249, 250, 251, 252
> Traceback (most recent call last):
>   File "tools/train.py", line 124, in <module>
>     main(config, device, logger, vdl_writer)
>   File "tools/train.py", line 99, in main
>     program.train(config, train_dataloader, valid_dataloader, device, model,
>   File "/paddle/PaddleOCR/tools/program.py", line 197, in train
>     for idx, batch in enumerate(train_dataloader):
>   File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
>     data = self._reader.read_next_var_list()
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
> ```
> 
> 是通过配置`use_shared_memory: False`来解决的。


taken(OOV) or label(O) not in tag2id_dict ...

**Comment by LifetimeMax** [comment]
> use_shared_memory: False

请问`use_shared_memory: False`配置，是在哪个文件里头的？
