### ISSUE TITLE
eval 很慢

### ISSUE THREAD

**Issue by hw446** [PaddlePaddle/PaddleOCR#1914]
单卡多个work的情况，几十秒eval一张图
![b4aa3a904ca53f6bea1b9b62aa213bf](https://user-images.githubusercontent.com/13492498/106578319-5d42b380-657a-11eb-9f76-b718611d19c4.png)

多卡单个work的情况，也同样很慢，貌似eval不支持多卡，开了24个进程也没觉得速度有提升
python3 -m paddle.distributed.launch --gpus 0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3 tools/eval.py

**Comment by hw446** [comment]
是不是eval和infer都是不支持多gpu的？

**Comment by LDOUBLEV** [comment]
训练速度是正常的吗？

设置多个workers是通过num_wokers 设置的，-m paddle.distributed.launch --gpus 0,1  是设置使用的GPU卡
eval的配置文件改成下面这样试试：
![image](https://user-images.githubusercontent.com/26592129/106837570-b2dfa300-66d5-11eb-8ebe-d3bdcea63f75.png)

**Comment by WenmuZhou** [comment]
这种情况可能是因为你的图片里文本框太多了，计算iou耗时比较久

**Comment by YukSing12** [comment]
![image](https://user-images.githubusercontent.com/39983134/115744592-47989980-a3c5-11eb-8fcd-f973d378d6ef.png)

我在模型剪枝敏感性分析时，同样也遇到了这个问题。
设置use_shared_memory为True后，第一次eval速度比较正常，第二次eval的速度就很慢了。
我的模型是识别的模型，因此可能不是图片文本框太多的问题。

我的环境为
paddlepaddle-gpu      2.0.2.post101
paddleocr             2.0.6
python 3.7.10

**Comment by WenmuZhou** [comment]
看fps 网络运行部分没问题，看看cpu是不是占用很大吧
