### ISSUE TITLE
PaddleOCR is not compitiable with Ray Serve

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#1915]
Hi,

Ray Serve is an easy-to-use scalable model serving library built on Ray - https://docs.ray.io/en/master/serve/index.html

When I try to apply PaddleOCR on Ray Serve, the following error is reported:

**ValueError: signal only works in main thread**

It is caused by calling signal.signal in the file ppocr/data/__init__.py  line 50-51 on https://github.com/PaddlePaddle/PaddleOCR/blob/9f6b3a118862932487e4d58d98d33b1bc66d3186/ppocr/data/__init__.py#L50 
After I remove these 2 lines , the Ray serve could be started. 

Here the request is to make PaddleOCR compitiable with Ray Serve

Thank you !

**Comment by LDOUBLEV** [comment]
Thanks for your advice.  We will check the use of `signal.SIGINT`

**Comment by kai06046** [comment]
> Thanks for your advice. We will check the use of `signal.SIGINT`

@LDOUBLEV Hi, may I ask the reason of avoiding signal not working in main thread?

**Comment by esteininger** [comment]
confirming this, YES! PaddleOCR uses signal.signal() which only works in the main thread. Ray actors run in worker threads, causing the crash.
