### ISSUE TITLE
How to set configs

### ISSUE THREAD

**Issue by jey07** [PaddlePaddle/PaddleOCR#1916]
This OCR seems to be good. I could see there are many configs file in config folder
How can I make sure that a particular config file is selected for my run.

**Comment by tink2123** [comment]
You can read the model training document in the [readme](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/README.md), 
Here is a one-to-one correspondence between configuration files and algorithms.
![image](https://user-images.githubusercontent.com/31891223/106837486-8a57a900-66d5-11eb-8911-cbff70665e5d.png)

**Comment by jey07** [comment]
Thanks.I have got a better picture about configs.
Is it possible to run pretrained model on my data without training. { for text detection and recognition)

**Comment by tink2123** [comment]
Yes, in order to speed up the convergence and improve the model effect, we recommend that you use a pre-trained model on your data.
