### ISSUE TITLE
cudnn8.1.x内存泄漏

### ISSUE THREAD

**Issue by yuliangxiao** [PaddlePaddle/PaddleOCR#1924]
paddlehub里面模型可以规避一下，PaddleOCR能否规避一下？
https://github.com/PaddlePaddle/Paddle/issues/30805

**Comment by LDOUBLEV** [comment]
还是建议用cudnn7 吧，我测试cudnn>=8.04的时候识别模型会有内存泄漏问题
8.0.3没有内存泄漏问题，另外，cudnn8在GPU上预测相比cudnn7存在性能下降，预测时间远超过在cudnn7上的预测时间。

如果要一定用cudnn8的话，可以尝试在[这一行](https://github.com/PaddlePaddle/PaddleOCR/blob/84bf657299058b2095e8de9e8049b5c3a6c3f380/tools/infer/utility.py#L113)添加这两句话：
```
config.delete_pass('conv_elementwise_add_act_fuse_pass')
config.delete_pass('conv_elementwise_add2_act_fuse_pass')
```

**Comment by yuliangxiao** [comment]
谢谢，因为我用的3090。
