### ISSUE TITLE
TypeError: hardsigmoid() got an unexpected keyword argument 'slope' 的解决方法

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1925]
训练时发现问题
outputs = F.hardsigmoid(outputs, slope=0.2, offset=0.5)
TypeError: hardsigmoid() got an unexpected keyword argument 'slope'
目前已解决，记录下解决方法以便后续他人查询。
原因是老用户直接升级代码导致的，之前教程安装的是paddlepaddle==2.0.0rc1 版本。
目前发布的是2.0.0版本，函数接口有变化，更新Paddle库即可。可用命令
python3 -m pip install paddlepaddle==2.0.0 -i https://mirror.baidu.com/pypi/simple

**Comment by Jitesh4389** [comment]
same issue facing

**Comment by WenmuZhou** [comment]
最新代码已经修复了哈
