### ISSUE TITLE
Unable to establish SSL connection. 

### ISSUE THREAD

**Issue by zzn1999** [PaddlePaddle/PaddleOCR#1927]
win10下使用git执行编译 make -j出错
$ make -j
/usr/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/sh: -c: line 1: syntax error: unexpected end of file
/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/sources/cxx-stl/llvm-libc++/include -I/sources/cxx-stl/llvm-libc++abi/include -I/sources/android/support/include -I/sysroot/usr/include  -I/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions -frtti -std=c++11 -fopenmp -O3 -DNDEBUG -fPIE -o ocr_db_crnn.o -c ocr_db_crnn.cc
/usr/bin/sh: /toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++: No such file or directory
make: *** [Makefile:47: ocr_db_crnn.o] Error 127
make: *** Waiting for unfinished jobs....
Fetch clipper
fetch opencv libs
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = D:\GnuWin32/etc/wgetrc
--2021-02-03 15:13:05--  https://paddle-inference-dist.bj.bcebos.com/opencv4.1.0.tar.gz
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = D:\GnuWin32/etc/wgetrc
--2021-02-03 15:13:05--  https://paddle-inference-dist.cdn.bcebos.com/PaddleLite/Clipper/clipper.hpp
Resolving paddle-inference-dist.bj.bcebos.com... 220.181.33.44, 220.181.33.43
Connecting to paddle-inference-dist.bj.bcebos.com|220.181.33.44|:443... Resolving paddle-inference-dist.cdn.bcebos.com... 115.238.187.35, 115.238.242.35
Connecting to paddle-inference-dist.cdn.bcebos.com|115.238.187.35|:443... connected.
connected.
ERROR: cannot verify paddle-inference-dist.cdn.bcebos.com's certificate, issued by `/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA':
  Unable to locally verify the issuer's authority.
To connect to paddle-inference-dist.cdn.bcebos.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
ERROR: cannot verify paddle-inference-dist.bj.bcebos.com's certificate, issued by `/C=US/O=DigiCert Inc/CN=DigiCert Secure Site Pro CN CA G3':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `*.bcebos.com' doesn't match requested host name `paddle-inference-dist.bj.bcebos.com'.
To connect to paddle-inference-dist.bj.bcebos.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
make: *** [Makefile:62: fetch_clipper] Error 1
make: *** [Makefile:70: fetch_opencv] Error 1

**Comment by LDOUBLEV** [comment]
你把文件下载到本地再编译试下吧，看样子是访问不了paddle-inference-dist.bj.bcebos.com
```
wget -c https://paddle-inference-dist.cdn.bcebos.com/PaddleLite/Clipper/clipper.hpp  --no-check-certificate
wget -c https://paddle-inference-dist.cdn.bcebos.com/PaddleLite/Clipper/clipper.cpp --no-check-certificate
```
或者在cmakelist文件里加上  --no-check-certificate https://github.com/PaddlePaddle/PaddleOCR/blob/29c825031a490a8b72bbb5ece4846a5215b9561f/deploy/lite/Makefile#L63
