### ISSUE TITLE
cuda error (701):too many resources requested for launch

### ISSUE THREAD

**Issue by AlsoSprachZarathushtra** [PaddlePaddle/PaddleOCR#1933]
T4卡，whl引擎推理，每张卡起3个推理服务，每个服务限制显存4G。
特殊应用场景，图为固定尺寸1280*1024，约含200-300个文字框，文字密度大，排列分布不规则。
个别图片导致cuda error (701):too many resources requested for launch错误。同一图片并不总是出错，出错几率约为50%，暂未发现出现此错误的规律。报错后，送入其他图片仍可正常推理出结果。

**Comment by LDOUBLEV** [comment]
图像尺寸太大了，占用内存会比较多，建议在预测的代码里加上
```
os.environ["FLAGS_allocator_strategy"] = 'auto_growth'
```
参考：https://github.com/PaddlePaddle/PaddleOCR/blob/84bf657299058b2095e8de9e8049b5c3a6c3f380/tools/infer/predict_rec.py#L21
