### ISSUE TITLE
使用官方的推理模型进行测试，报错numpy.AxisError: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by Fenghaze** [PaddlePaddle/PaddleOCR#1934]
![QQ截图20210204102454](https://user-images.githubusercontent.com/40448037/106836044-61361900-66d3-11eb-9f45-7aaf734a7b6a.png)

**Comment by tink2123** [comment]
1.1 的模型，请使用 release/1.1 分支的代码去预测。
