### ISSUE TITLE
paddleocr报错：OMP: Error #13: Assertion failure at z_Linux_util.cpp(2338).

### ISSUE THREAD

**Issue by Rsndmmm** [PaddlePaddle/PaddleOCR#1937]
环境：Ubuntu 16.04
python 3.7
paddlepaddle 1.7.2
paddlepaddle-gpu 1.8.5.post97
paddleocr 0.0.3.1
运行paddleocr python包报错：
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2338).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.

运行代码就是官方的检测+识别demo代码

配置信息：
Namespace(det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='/root/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/root/.paddleocr/rec', use_gpu=False, use_space_char=True, use_tensorrt=False)

**Comment by LDOUBLEV** [comment]
升级paddlepaddle 吧，建议paddlepaddle-gpu==2.0.0版本
