### ISSUE TITLE
DB算法预处理, 图片随机裁剪存在漏掉部分目标框的问题

### ISSUE THREAD

**Issue by XiaoSX** [PaddlePaddle/PaddleOCR#1940]
ppocr.data.imaug.random_crop_data.py, split_regions 函数region的收集不完整, 循环结束时, 仍满足index的不连续条件, 即axis[i] != axis[i - 1] + 1, 这部分region没有收集, 结果可能导致漏掉图片最右或最下边的bbox

原图:
![Screenshot from 2021-02-04 15-51-09](https://user-images.githubusercontent.com/13111327/106861541-da983080-6700-11eb-848b-c5f6482aa349.png)

裁剪后:
![Screenshot from 2021-02-03 11-02-03](https://user-images.githubusercontent.com/13111327/106861290-868d4c00-6700-11eb-81ae-f015973e4bde.png)

代码链接
https://github.com/PaddlePaddle/PaddleOCR/blob/84bf657299058b2095e8de9e8049b5c3a6c3f380/ppocr/data/imaug/random_crop_data.py#L31

**Comment by LDOUBLEV** [comment]
感谢反馈，我们跟进下，也欢迎给我们提PR修复bug

**Comment by zhongwenkun886** [comment]
请问这是否bug？ 我看最新版也还没改。
