### ISSUE TITLE
develop版本运行报错double free or corruption (fasttop)求解答

### ISSUE THREAD

**Issue by zjy614** [PaddlePaddle/PaddleOCR#1941]
使用glibc2.27，cuda10.0+cudnn7.6.5，三块tesla v100显卡按照detection文档训练icdar2015数据集，在训练中报错，求指教，具体报错信息如下
double free or corruption (fasttop)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   ClipperLib::ClipperOffset::Execute(std::vector<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> >, std::allocator<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> > > >&, double)
1   ClipperLib::Clipper::Execute(ClipperLib::ClipType, std::vector<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> >, std::allocator<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> > > >&, ClipperLib::PolyFillType, ClipperLib::PolyFillType)
2   ClipperLib::ClipperBase::DisposeAllOutRecs()
3   ClipperLib::ClipperBase::DisposeOutRec(unsigned long)
4   ClipperLib::DisposeOutPts(ClipperLib::OutPt*&)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1612422857 (unix time) try "date -d @1612422857" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002f8c) received by PID 12172 (TID 0x7f29f2098700) from PID 12172 ***]

**Comment by tink2123** [comment]
develop 分支是不稳定的开发分支，如果想使用动态图，建议基于 dygraph 分支或者 release/2.0 ，如果是静态图建议基于 release/1.1分支。

**Comment by zjy614** [comment]
> develop 分支是不稳定的开发分支，如果想使用动态图，建议基于 dygraph 分支或者 release/2.0 ，如果是静态图建议基于 release/1.1分支。

收到，我更换试试，感谢
