### ISSUE TITLE
可以用TensorRT么？

### ISSUE THREAD

**Issue by wksuixin** [PaddlePaddle/PaddleOCR#1942]
TensorRT的环境下，PaddleOCR可以用TensorRT加速么？是否需要改代码固定输入？

**Comment by tink2123** [comment]
可以用TensorRT加速，变长支持的不够好，可以先修改成定长加速。

**Comment by wksuixin** [comment]
> 可以用TensorRT加速，变长支持的不够好，可以先修改成定长加速。

我看检测要求输入[3, 640, 640] 方向判断[3 ,32, 100]，这都得修改程序么？还是修改配置文件就可以？？

**Comment by wksuixin** [comment]
并且我这边的TensorRT是用的新的版本， 用的7.0
![111](https://user-images.githubusercontent.com/48641685/106994498-db3fce00-67b7-11eb-8038-a59d7108a5f8.png)

**Comment by tink2123** [comment]
> 并且我这边的TensorRT是用的新的版本， 用的7.0

需要修改下代码，把输入图片resize成一个固定长度，否则在预测的时候会报错。变长这块我们也正在支持，请等待一段时间。

**Comment by wksuixin** [comment]
> > 并且我这边的TensorRT是用的新的版本， 用的7.0
> 
> 需要修改下代码，把输入图片resize成一个固定长度，否则在预测的时候会报错。变长这块我们也正在支持，请等待一段时间。

好的，知道了，感谢
