### ISSUE TITLE
计算多边形面积 polygon_area

### ISSUE THREAD

**Issue by lexiqi** [PaddlePaddle/PaddleOCR#1943]
![image](https://user-images.githubusercontent.com/25817952/106880074-e42c9300-6716-11eb-9dd7-74c5b6aed1f7.png)

polygon_area()函数里的计算多边形面积为什么要这么计算？？？？

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/1973

**Comment by firstelfin** [comment]
多边形面积计算公式，维基百科有详细介绍：https://en.wikipedia.org/wiki/Shoelace_formula
