### ISSUE TITLE
PPOCRLabel 无法保存识别的 crop_image 和 rec_gt.txt

### ISSUE THREAD

**Issue by noirlyrik** [PaddlePaddle/PaddleOCR#1946]
paddlepaddle           2.0.0rc1  
20210119克隆的PaddleOCR代码
点击保存标注结果可以获取识别结果，但是点击保存识别结果，crop_image下是空的， rec_gt.txt也是空的

**Comment by Evezerest** [comment]
Please make sure that the images had been checked before saving the recognition results.

**Comment by noirlyrik** [comment]
window电脑上勾选然后导出时报错：

```
Traceback (most recent call last):
  File "PPOCRLabel.py", line 1960, in saveRecResult
    cv2.imwrite(crop_img_dir+img_name, img_crop)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
```

mac没有

**Comment by Evezerest** [comment]
> window电脑上勾选然后导出时报错：
> 
> ```
> Traceback (most recent call last):
>   File "PPOCRLabel.py", line 1960, in saveRecResult
>     cv2.imwrite(crop_img_dir+img_name, img_crop)
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
> ```
> 
> mac没有

可以更新一下代码，或者检查一下是否有中文路径
