### ISSUE TITLE
2.0det模型训练后怎么转换成推理模型

### ISSUE THREAD

**Issue by kotohono** [PaddlePaddle/PaddleOCR#1947]
文本检测，训练完的训练模型保存为pdparams和pdopt是好用的，转换成推理模型的pdiparams和pdimodel进行文本检测就不好用了。
paddle.jit.save用的inputSpecs 是[InputSpec(shape=[1,3,None,None], dtype='float32')]。
文本识别用[1,3,32,320]效果还行，文本检测输入的不是固定的，不清楚用什么

**Comment by WenmuZhou** [comment]
这个我们已经提供了一个转换脚本 tools/export_model.py

**Comment by GreenVegetables123** [comment]
> 这个我们已经提供了一个转换脚本 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/export_model.py

我用这个转换脚本，转换出来的检测推理模型效果很差，几乎检测不出来，用直接训练号的模型，不转换，反而效果很好

**Comment by WenmuZhou** [comment]
这个你看看参数对不对

**Comment by PHI6kai** [comment]
怎么解决的？？
