### ISSUE TITLE
如何复现benchmark中各模型整体识别率F-score

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#1948]
Hi,

从 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/benchmark.md 可以看到，各个模型有一个整体识别率F-score

模型名称 | 整体模型大小(M) | 检测模型大小(M) | 方向分类器模型大小(M) | 识别模型大小(M) | 整体识别F-score
-- | -- | -- | -- | -- | --
ch_ppocr_mobile_v1.1 | 8.1 | 2.6 | 0.9 | 4.6 | 0.5193
ch_ppocr_server_v1.1 | 155.1 | 47.2 | 0.9 | 107 | 0.5414
ch_ppocr_mobile_v1.0 | 8.6 | 4.1 | - | 4.5 | 0.393
ch_ppocr_server_v1.0 | 203.8 | 98.5 | - | 105.3 | 0.4436

例如 ch_ppocr_mobile_v1.1 的  整体识别F-score 是 0.51

是否有教程可以帮助用户在本地复现这个整体识别F-score ？

Thank you in advance !

**Comment by WenmuZhou** [comment]
这个识别率是在内部数据集上评测的，数据集没有开放，可能无法复现

**Comment by zhfkt** [comment]
Thank you for replying.

那是否有在公开数据集上评测的F-score ？以及这个end-to-end的F-score是用项目中的哪一个脚本跑出来的？谢谢 !

**Comment by WenmuZhou** [comment]
没有在公开数据集上评测，评测代码也没有开源
