### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#1957]
develop分支的configs/rec/rec_r34_tps_bilstm_attn.yml 的模型summary 不出来，别的模型可以。
![image](https://user-images.githubusercontent.com/61573829/107021503-28836600-67df-11eb-95ae-1ca74fcfa353.png)

**Comment by littletomatodonkey** [comment]
你好，目前attention模型还不支持summary哈，抱歉~

https://github.com/PaddlePaddle/PaddleOCR/blob/29c825031a490a8b72bbb5ece4846a5215b9561f/tools/train.py#L83
