### ISSUE TITLE
训练过程中出现double free or corruption （faststop）求解答

### ISSUE THREAD

**Issue by zjy614** [PaddlePaddle/PaddleOCR#1958]
更换了PaddleOCR1.1和Paddle1.8.5，使用python3.7,glibc2.27，cuda10.0+cudnn7.6.5，三块tesla v100显卡按照detection文档训练icdar2015数据集，在训练中报错，求指教，具体报错信息如下
2021-02-06 01:38:22,702-INFO: epoch: 731, iter: 13174, 'lr': 0.000279, 'total_loss': 1.310723, 'loss_shrink_maps': 0.690919, 'loss_threshold_maps': 0.495159, 'loss_binary_maps': 0.137346, time: 1.320
double free or corruption (fasttop)
W0206 01:38:26.893338 27807 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0206 01:38:26.893457 27807 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0206 01:38:26.893468 27807 init.cc:231] The detail failure signal is:

W0206 01:38:26.893481 27807 init.cc:234] *** Aborted at 1612546706 (unix time) try "date -d @1612546706" if you are using GNU date ***
W0206 01:38:26.899175 27807 init.cc:234] PC: @                0x0 (unknown)
W0206 01:38:26.899662 27807 init.cc:234] *** SIGABRT (@0x3e800006c9f) received by PID 27807 (TID 0x7f2fed38f700) from PID 27807; stack trace: ***
W0206 01:38:26.904228 27807 init.cc:234]     @     0x7f3035503980 (unknown)
W0206 01:38:26.906816 27807 init.cc:234]     @     0x7f303513efb7 gsignal
W0206 01:38:26.909294 27807 init.cc:234]     @     0x7f3035140921 abort
W0206 01:38:26.911856 27807 init.cc:234]     @     0x7f3035189967 (unknown)
W0206 01:38:26.914091 27807 init.cc:234]     @     0x7f30351909da (unknown)
W0206 01:38:26.915779 27807 init.cc:234]     @     0x7f30351980f4 cfree
W0206 01:38:26.916121 27807 init.cc:234]     @     0x55677c0fd2d0 lock_dealloc
W0206 01:38:26.917007 27807 init.cc:234]     @     0x7f2fd8eca517 __pyx_tp_dealloc_5numpy_6random_10_generator_Generator
W0206 01:38:26.917165 27807 init.cc:234]     @     0x55677c07eee8 dict_dealloc
W0206 01:38:26.917285 27807 init.cc:234]     @     0x55677c1144f0 subtype_dealloc
W0206 01:38:26.917433 27807 init.cc:234]     @     0x55677c07ef67 dict_dealloc
W0206 01:38:26.917551 27807 init.cc:234]     @     0x55677c1144f0 subtype_dealloc
W0206 01:38:26.917695 27807 init.cc:234]     @     0x55677c07eb92 list_dealloc
W0206 01:38:26.917814 27807 init.cc:234]     @     0x55677c11450e subtype_dealloc
W0206 01:38:26.918296 27807 init.cc:234]     @     0x55677c0859bc _PyEval_EvalCodeWithName
W0206 01:38:26.918735 27807 init.cc:234]     @     0x55677c0d6107 _PyFunction_FastCallKeywords
W0206 01:38:26.919232 27807 init.cc:234]     @     0x55677c13e4b6 _PyEval_EvalFrameDefault
W0206 01:38:26.919692 27807 init.cc:234]     @     0x55677c08685b _PyFunction_FastCallDict
W0206 01:38:26.920146 27807 init.cc:234]     @     0x55677c0a54d3 _PyObject_Call_Prepend
W0206 01:38:26.920397 27807 init.cc:234]     @     0x55677c0dce1a slot_tp_call
W0206 01:38:26.920853 27807 init.cc:234]     @     0x55677c0ddccb _PyObject_FastCallKeywords
W0206 01:38:26.921339 27807 init.cc:234]     @     0x55677c14339e _PyEval_EvalFrameDefault
W0206 01:38:26.921588 27807 init.cc:234]     @     0x55677c0ddf11 gen_send_ex
W0206 01:38:26.922071 27807 init.cc:234]     @     0x55677c13eae6 _PyEval_EvalFrameDefault
W0206 01:38:26.922320 27807 init.cc:234]     @     0x55677c0ddf11 gen_send_ex
W0206 01:38:26.922806 27807 init.cc:234]     @     0x55677c13eae6 _PyEval_EvalFrameDefault
W0206 01:38:26.923260 27807 init.cc:234]     @     0x55677c085829 _PyEval_EvalCodeWithName
W0206 01:38:26.923717 27807 init.cc:234]     @     0x55677c086925 _PyFunction_FastCallDict
W0206 01:38:26.924211 27807 init.cc:234]     @     0x55677c13feea _PyEval_EvalFrameDefault
W0206 01:38:26.924638 27807 init.cc:234]     @     0x55677c0d5e7b _PyFunction_FastCallKeywords
W0206 01:38:26.925125 27807 init.cc:234]     @     0x55677c13e740 _PyEval_EvalFrameDefault
W0206 01:38:26.925551 27807 init.cc:234]     @     0x55677c0d5e7b _PyFunction_FastCallKeywords
2021-02-06 01:38:28,439-INFO: epoch: 732, iter: 13176, 'lr': 0.000278, 'total_loss': 1.297585, 'loss_shrink_maps': 0.678198, 'loss_threshold_maps': 0.494434, 'loss_binary_maps': 0.135294, time: 3.992

**Comment by littletomatodonkey** [comment]
把batch size和numworkers都减小一点试下呢？

**Comment by zjy614** [comment]
> 把batch size和numworkers都减小一点试下呢？

解决了多谢
