### ISSUE TITLE
字典中没有的字怎么标注？

### ISSUE THREAD

**Issue by klw2020** [PaddlePaddle/PaddleOCR#1960]
![K7_O(H7UEV%SKX EWBI~XEN](https://user-images.githubusercontent.com/53896985/107110220-32f63c00-6881-11eb-8c7c-51385084d778.png)
比如说字典中没有“的”字，用空格代替还是直接忽略掉，还是？

**Comment by littletomatodonkey** [comment]
可以直接写成的，在编码的时候，会忽略掉字典中不存在的字符的
