### ISSUE TITLE
paddle cpp推理引擎加载模型报错cpu_avx_openblas 2.0预测库

### ISSUE THREAD

**Issue by laizewei** [PaddlePaddle/PaddleOCR#1961]
win10版本20h2(19042.746)
visual studio 2019 版本 16.9.0 Preview 3.0
paddle cpp推理引擎加载模型报错cpu_avx_openblas 2.0预测库
运行例子无法跑。模型是paddleocr det移动端模型
void DBDetector::LoadModel(const std::string &model_dir) {
  //   AnalysisConfig config;
  paddle_infer::Config config;
  config.SetModel(model_dir + "/inference.pdmodel",//这一句报错了这一句报错了这一句报错了这一句报错了
                  model_dir + "/inference.pdiparams");

0x00007FFBE44CD759 处(位于 ConsoleApplication1.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000F9F92FC530 处。
------------------
推理库下载地址;https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/windows_cpp_inference.html
cpu_avx_openblas
模型下载地址:
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/models_list.md
ch_ppocr_mobile_v2.0_det 推理模型

**Comment by TingquanGao** [comment]
您好！参考[说明文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/docs/windows_vs2019_build.md)，使用以下环境，我未能复现您所说的问题。

> PaddleOCR：dygraph分支
> 推理库：[paddle_inference cpu_avx_openblas](https://paddle-wheel.bj.bcebos.com/2.0.0/win-infer/open/cpu/paddle_inference_install_dir.zip)
> 模型：
>> ch_ppocr_mobile_v2.0_det
>> ch_ppocr_mobile_v2.0_rec
>> ch_ppocr_mobile_v2.0_cls

有一点需要注意的是，[此行代码](https://github.com/PaddlePaddle/PaddleOCR/blob/895d44bc3941810ca974f103fe27bd383570e241/deploy/cpp_infer/CMakeLists.txt#L136)中，`libopenblas`需要更改为`openblas`，我们会尽快修复该问题并更新代码。

**Comment by laizewei** [comment]
我不是用cmake构建的，没有指定third_party，只引用了opencv,paddle,openblas和例子几个头文件，其它依赖库头文件没有引用

**Comment by laizewei** [comment]
我的cpu是i7 7700

**Comment by TingquanGao** [comment]
目前我们仅验证过cmake编译正常。您那边使用cmake+visual studio 2019，按照我们提供的文档可以正常跑通吗？
