### ISSUE TITLE
linux OCR服务器部署，运行module.py 出现AttributeError: 'OCRSystem' object has no attribute 'text_sys'错误

### ISSUE THREAD

**Issue by YAwei666** [PaddlePaddle/PaddleOCR#1962]

**Comment by littletomatodonkey** [comment]
你好，可以参考这篇文档进行ocr服务器部署，不能直接运行mobule.py的哈

https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/hubserving/readme.md

**Comment by YAwei666** [comment]
@littletomatodonkey  ![image](https://user-images.githubusercontent.com/34396185/107134819-73f95980-6930-11eb-90c7-dffb4e4fb7a7.png)
到相应的module.py和params.py等文件中根据实际需求修改代码。
例如，如果需要替换部署服务所用模型，则需要到params.py中修改模型路径参数det_model_dir和rec_model_dir，如果需要关闭文本方向分类器，则将参数use_angle_cls置为False，当然，同时可能还需要修改其他相关参数，请根据实际情况修改调试。 强烈建议修改后先直接运行module.py调试，能正确运行预测后再启动服务测试。

**Comment by YAwei666** [comment]
Intel MKL function load error: cpu specific dynamic library is not loaded.
这个问题重新装scipy==1.1.0没有解决，现在有什么推荐的解决方案嘛，感谢

**Comment by xialei2821212670** [comment]
> @littletomatodonkey 到相应的module.py和params.py等文件中根据实际需求修改代码。 例如，如果需要替换部署服务所用模型，则需要到params.py中修改模型路径参数det_model_dir和rec_model_dir，如果需要关闭文本方向分类器，则将参数use_angle_cls放置为False，当然，同时可能还需要修改其他相关参数，请根据实际情况进行修改调试。测试。![图像](https://user-images.githubusercontent.com/34396185/107134819-73f95980-6930-11eb-90c7-dffb4e4fb7a7.png)
,你好这问题您解决了？，我也尝试了，遇到这个问题

**Comment by Yinmm** [comment]
paddlehub版本换1.8.3可解决

**Comment by wangkailun** [comment]
需要将moudle.py 中的 `def  _initialize()`这个函数名，改为初始化函数 `def __init__()`  
另外我在  `from ocr_system.params import read_params`  这行遇到报错，需要改为  `from params import read_params`

**Comment by wa3926** [comment]
我也遇到这个问题了 本地hub 1.8的确实没问题   但是服务器paddle已经升级2.0了  退不回去了   这个bug好像还没解决

**Comment by ConleyKong** [comment]
> 需要将module.py 中的 `def _initialize()`这个函数名，改为初始化函数 `def __init__()`
> 另外我在 `from ocr_system.params import read_params` 这行遇到报错，需要改为 `from params import read_params`

仅能在测试时增加__init__方法，在部署时需要注释掉，貌似hub部署时会调用真正的__init__方法

**Comment by littletomatodonkey** [comment]
你好，之前的hubserving代码有点问题，等这个pr合入之后，可以拉取dygraph分支的代码测试一下哈：#3269

**Comment by littletomatodonkey** [comment]
此外，paddlehub2.1.0也是可以的
