### ISSUE TITLE
tools/eval.py和tools/infer_rec.py结果相差太远

### ISSUE THREAD

**Issue by chenxinhua** [PaddlePaddle/PaddleOCR#1963]
对于同样的配置文件和同样的权重文件，tools/eval.py测试精度能达到96.5%，而tools/infer_rec.py结果绝大部分是错误的，大概只有17%是对的，其中很多情况是最后字符重复一个。

**Comment by littletomatodonkey** [comment]
你好，你使用的是dygraph分支的代码吗还是？这里应该已经对字符进行去重了，

https://github.com/PaddlePaddle/PaddleOCR/blob/baafb2991876ae7d4942e8fd3c4adbe31346bf05/ppocr/postprocess/rec_postprocess.py#L117

可以拉下最新的代码试一下哈

**Comment by chenxinhua** [comment]
是dygraph分支，识别模型支持不定长的文字识别吗，等比例缩放文字后，高度32，但是长度不一。

**Comment by Evezerest** [comment]
不定长是支持的，能提供一下图片么

**Comment by wstchhwp** [comment]
> 对于同样的配置文件和同样的权重文件，tools/eval.py测试精度能达到96.5%，而tools/infer_rec.py结果绝大部分是错误的，大概只有17%是对的，其中很多情况是最后字符重复一个。

你好，请问这个问题是怎么解决的呢
