### ISSUE TITLE
ch_ppocr_mobile_v2.0_rec_infer.tar在Windows下解压有问题

### ISSUE THREAD

**Issue by lexiaoyuan** [PaddlePaddle/PaddleOCR#1965]
`ch_ppocr_mobile_v2.0_rec_infer.tar`在Windows下解压有问题，另外两个解压没问题，在Ubuntu下都可以。

**Comment by littletomatodonkey** [comment]
你好，这个需要解压两次才可以哈，具体原因目前还在排查，抱歉给你的使用带来不便~
