### ISSUE TITLE
请问像这种弯曲的文本，请问如何处理？感谢！

### ISSUE THREAD

**Issue by bowentest123** [PaddlePaddle/PaddleOCR#1966]
![image](https://user-images.githubusercontent.com/53248151/107133973-b9198d80-6928-11eb-90c0-e02aceb3a2af.png)

请问大神，像这种弯曲的文本，请提供一些思路。我目前做实验如下：
1，矩形标注后，使上图中数字在一个框内，ch_ppocr_server_v2.0_rec识别效果很差。
2，数字部分分成左右两段标注，左边一框包住斜的，右边一框包住横的，经过一些样本的训练后，发现检测依然不理想。

![image](https://user-images.githubusercontent.com/53248151/107134066-a6ec1f00-6929-11eb-8925-d8eb62d34fa0.png)
1，上图经过百度AI高精度版识别后，可以正确识别，返回坐标大致如上，其明显包含了第一行“如您需要当日.....” 。然后截取
这一块并使用ch_ppocr_server_v2.0_rec进行识别，结果不理想。

想请问大神综合上面两种情况能提供些思路，是从检测部分下手还是从识别部分下手，使用ch_ppocr系列预训练模型是否不可能实现，还是说要从头训练使用STAR等模型 .....  

谢谢各位！

**Comment by WenmuZhou** [comment]
建议从检测和识别分别入手
检测： 标注的时候使用多点标注，修改网络的后处理部分，添加多边形输出
识别： 根据多边形输出mask出文字属于，然后截取矩形送入识别模型，送入的图片需要多边形内部是文字，外部是黑色或者北京，然后训练一个带tps的模型，识别模型数据里也适当加上黑色边框

**Comment by bowentest123** [comment]
> 建议从检测和识别分别入手
> 检测： 标注的时候使用多点标注，修改网络的后处理部分，添加多边形输出
> 识别： 根据多边形输出mask出文字属于，然后截取矩形送入识别模型，送入的图片需要多边形内部是文字，外部是黑色或者北京，然后训练一个带tps的模型，识别模型数据里也适当加上黑色边框

谢谢您的回复，看来必然要使用多点标注，如您所说，如果使用多点标注，是否还可以用 ch_ppocr_server_v2.0_det.yml和其对应预训练模型进行训练(因为您提供的预训练模型效果还是很不错的，不想自己从头训练 )  ？

**Comment by WenmuZhou** [comment]
可以
