### ISSUE TITLE
数据预处理中为何要将太正的四边形忽略掉呢

### ISSUE THREAD

**Issue by maplelinfy** [PaddlePaddle/PaddleOCR#1967]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/det/make_shrink_map.py#L27
如果这个多边形经前面处理后的坐标是例如：[[1, 3], [5, 3], [5, 1], [1, 1]]
那么通过https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/det/make_shrink_map.py#L34
计算这个面积后，得到的结果是0，所以就被pass掉了，还有一些计算出来是小于0的，请问这个过滤逻辑是什么呢，谢谢。

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，多边形面积计算更新了下，可以暂时先参考这个pr: https://github.com/PaddlePaddle/PaddleOCR/pull/1973

**Comment by maplelinfy** [comment]
> 你好，感谢反馈，多边形面积计算更新了下，可以暂时先参考这个pr: #1973

感谢更新
