### ISSUE TITLE
官网上提供的ch_ppocr系列模型是在哪些训练集上训练的

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#1968]
按照 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/models_list.md ， 可以看到 模型下载地址 和 相对应的训练配置文件 。例如 ch_ppocr_mobile_v2.0_det 的训练配置文件是 ch_det_mv3_db_v2.0.yml 。但是官网上并没有说明 ch_ppocr系列模型是在哪些训练集上训练的 ，以及从哪里找dataset。如果想要在本地复现 ch_ppocr系列模型 ，是否有相应的教程？谢谢！

**Comment by WenmuZhou** [comment]
ch模型外部无法复现哈，有部分私有数据集

**Comment by tink2123** [comment]
训练数据暂时无法提供，这里有一些可用的开源数据说明，可供参考：https://github.com/PaddlePaddle/PaddleOCR/blob/161a47a6e263f3249ea4a0ec40c779eddea630eb/doc/doc_ch/datasets.md
