### ISSUE TITLE
paddle推理和Tensorflow冲突的BUG反馈

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleOCR#1969]
版本是paddlepaddle2b版本。
原设定tensorflow的模型推理在4，5两张显卡上是可以正常推理的（services-streaming框架），但是在import paddle后tensorflow模型只能放在1号显卡上推理。非常的amazing啊。所以这里paddle里面改了什么环境变量吗？为何不能放在多卡上推理呢？

**Comment by yangtianyu92** [comment]
降低paddlepaddle版本到1.6.0后一切都按预先想的那样推理了，看样子确实是paddlepaddle2.0.0b的问题。。。

**Comment by littletomatodonkey** [comment]
可以实现先import paddle，再import tensorflow

**Comment by yangtianyu92** [comment]
> 可以实现先import paddle，再import tensorflow

啊这，确实可以。谢啦。还是好奇的问下到底里面改了什么东西会导致这种情况呢。

**Comment by littletomatodonkey** [comment]
这个没有具体研究过，可能是初始化的时候有冲突，具体可能得看Paddle的源码了~

**Comment by yangtianyu92** [comment]
> 这个没有具体研究过，可能是初始化的时候有冲突，具体可能得看Paddle的源码了~

我悟到了，暗示paddle必须放在tensorflow上面。
