### ISSUE TITLE
图像太小就会报错：invalid input 'img' in NormalizeImage，请问这个怎么解决呢

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#1974]

**Comment by WenmuZhou** [comment]
多小的图片会触发这个，这个代码里看是图片不是numpy矩阵引起的，

**Comment by aishangmaxiaoming** [comment]
> 多小的图片会触发这个，这个代码里看是图片不是numpy矩阵引起的，

我大概测试了一批，长或者宽一般小于17像素会报错

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/1992 fixed

**Comment by aishangmaxiaoming** [comment]
> #1992 fixed

谢谢🙏
