### ISSUE TITLE
PPOCRLabel调整识别好的矩形标注框，会自动变为正方形标注模式

### ISSUE THREAD

**Issue by noirlyrik** [PaddlePaddle/PaddleOCR#1977]
PPOCRLabel标注时调整识别好的矩形框，会自动变为正方形标注，矩形框变为正方形框。

需要先选择正方形标注，再取消勾选，才能调整矩形标注框

**Comment by Evezerest** [comment]
你好，如果勾选了编辑-正方形标注，那么拖动矩形框的点，矩形框会自动变为正方形。如果没有勾选，矩形框拖动时仍然会按照矩形框模式。在正常新建矩形框时不需要勾选正方形标注。

**Comment by noirlyrik** [comment]
> 你好，如果勾选了编辑-正方形标注，那么拖动矩形框的点，矩形框会自动变为正方形。如果没有勾选，矩形框拖动时仍然会按照矩形框模式。在正常新建矩形框时不需要勾选正方形标注。

没有勾选正方形标注，拖动矩形框自动变为正方形。勾选正方形标注再取消勾选后，才能正常拖动矩形框。

**Comment by Evezerest** [comment]
这种情况我们测试的过程中没有遇到，能提供一下你的环境吗，比如系统、代码是最新的吗

**Comment by noirlyrik** [comment]
> 这种情况我们测试的过程中没有遇到，能提供一下你的环境吗，比如系统、代码是最新的吗

系统：macOS 10.15.4 

2021年1月19日 克隆的代码，2月拉取最新代码的时候没能成功运行，所以还是使用1月19日的版本

**Comment by noirlyrik** [comment]
拉取最新代码后没有这个问题了，非常感谢！
