### ISSUE TITLE
det阶段finetune, 关于冻结某些层的问题

### ISSUE THREAD

**Issue by felixzhao01** [PaddlePaddle/PaddleOCR#1986]
请问在使用reset18或者mobilenet进行finetune时，想要冻结某些层时，设置的stop_gradient=True可以在config文件里配置吗？在config文件里有没有可以设置不同层不同学习率的选项或者冻结某些层的选项呢？谢谢

**Comment by Evezerest** [comment]
目前还不支持通过配置文件设置
