### ISSUE TITLE
假如一张图片可以很好识别，Mat 截取部分，重新去识别效果不好。

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleOCR#1987]
一张图片可以很好识别，但是用Mat截取部分，来识别，但是效果不佳。请问是什么原因？是使用不对吗？请问要如何使用？

**Comment by MissPenguin** [comment]
怎么个截取法，图片贴来看看？

**Comment by mybrew** [comment]
类似这样截取，	
Mat ms2 ( srcimg , Rect( x , y , width ,height ) ;
srcimg是原始图，后面截取了部分，要识别的文字截取进去了，这时用ms2用来运行效果不佳。

**Comment by chaoswong1981** [comment]
我现在依然有这个问题，请问您是解决了么？如何解决的呢？ @mybrew
