### ISSUE TITLE
我通过hub使用chinese_ocr_db_crnn_server模型，但是对于一个不太大的图片都会造成内存爆满

### ISSUE THREAD

**Issue by y455471846b** [PaddlePaddle/PaddleOCR#199]
我通过hub使用chinese_ocr_db_crnn_server模型，但是对于一个不太大的图片都会造成内存爆满，本机运行模块和通过服务的方法都是如此，要怎么解决呢?才1M多的图片

**Comment by Steffy-zxf** [comment]
你好！请问你的图片size多大？机器内存多大呢？
