### ISSUE TITLE
可以提供server版的演示功能吗

### ISSUE THREAD

**Issue by scfw** [PaddlePaddle/PaddleOCR#1998]

**Comment by MissPenguin** [comment]
考虑到效率问题，咱不计划提供server演示demo哈，可以按照“快速使用”教程（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/quickstart.md）跑一下server模型的效果，会直接生成可视化的结果。

**Comment by MissPenguin** [comment]
考虑到效率问题，暂不计划提供server演示demo哈，可以按照“快速使用”教程（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/quickstart.md ）跑一下server模型的效果，会直接生成可视化的结果。
