### ISSUE TITLE
弯曲完本检测，DBNET出来是一些点的集合，怎么能把文本区域抠出来然后展平？

### ISSUE THREAD

**Issue by liuheng0111** [PaddlePaddle/PaddleOCR#1999]
现在很多弯曲文本检测，PSNET、DBNET，但是检测出来之后怎么展平放到识别模型里去？

**Comment by MissPenguin** [comment]
2阶段的文本识别方法中，弯曲文本拉直的方法目前常用方法主要是TPS，另外一些端到端的方法如ABCNet也有一些新的思路，可以研究下，从实用性角度考虑PaddleOCR的完整识别系统目前不支持弯曲文本的识别
