### ISSUE TITLE
是否有 基于ch_pproc模型的 迁移训练 的教程

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#2000]
github上是否有 基于ch_pproc模型 迁移训练的教程。

我在github上面只看到全量训练icdar的教程 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/detection.md ，没有看到基于ch_pproc模型迁移训练的教程。

谢谢！

**Comment by Evezerest** [comment]
教程目前还没有，但可以在https://aistudio.baidu.com/aistudio/projectoverview/public找到相关的
