### ISSUE TITLE
如何在自定义数据集上计算End-to-End的F-score，评估算法的整体性能？

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#2001]
Hi，

我看到 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/benchmark.md 这边有如下的F-score 的metric。如 ch_ppocr_mobile_v1.1的 F-score是 0.5193。

模型名称 | 整体模型大小(M) | 检测模型大小(M) | 方向分类器模型大小(M) | 识别模型大小(M) | 整体识别F-score
-- | -- | -- | -- | -- | --
ch_ppocr_mobile_v1.1 | 8.1 | 2.6 | 0.9 | 4.6 | 0.5193
ch_ppocr_server_v1.1 | 155.1 | 47.2 | 0.9 | 107 | 0.5414

看起来F-score应该可以代表End-to-End的整体性能。

如果我想在自定义数据集（例如icdar15数据集）上，计算ch_ppocr_mobile_v1.1 的F-score是多少，改用什么工具/脚本去计算？我找到如下工具：

1. 文本检测 阶段可以通过tools/eval.py脚本得到 Precision、Recall、Hmean这三个指标
python3 tools/eval.py -c configs/det/det_mv3_db.yml  -o Global.checkpoints="{path/to/weights}/best_accuracy" PostProcess.box_thresh=0.5 PostProcess.unclip_ratio=1.5

2. 文本识别 阶段可以通过tools/eval.py脚本得到 Avg Accuracy 这个指标
python3 -m paddle.distributed.launch --gpus '0' tools/eval.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints={path/to/weights}/best_accuracy

如果想要得到整体end-to-end的F-score，评估算法的整体（检测+识别）性能，该用哪一个脚本或者工具去计算？谢谢！

**Comment by MissPenguin** [comment]
您好，端到端的评估中，我们使用的ICDAR2015官方使用的端到端评估工具，具体信息可以到官网看下：https://rrc.cvc.uab.es/?ch=2&com=tasks

**Comment by zhfkt** [comment]
> 您好，端到端的评估中，我们使用的ICDAR2015官方使用的端到端评估工具，具体信息可以到官网看下：https://rrc.cvc.uab.es/?ch=2&com=tasks

Thank you for replying.

我看到提供的页面中，只有下列Evaluation的算法介绍，但是没有现成的工具或者脚本进行下载。是否可以提供具体的ICDAR2015官方使用的端到端评估工具的下载链接？

`Evaluation
The evaluation protocol proposed by Wang 2011 [4] will be used which considers a detection as a match if it overlaps a ground truth bounding box by more than 50% (as in [5]) and the words match, ignoring the case. Detecting or missing words marked as “do not care” will not affect (positively or negatively) the results. Any detections overlapping more than 50% with “do not care” ground truth regions will be discarded from the submitted results before evaluation takes place, and evaluation will not take into account ground truth regions marked as “do not care”.`

**Comment by Evezerest** [comment]
抱歉暂时无法提供
