### ISSUE TITLE
ch_ppocr_mobile_v2.0_rec_infer.tar: missing files

### ISSUE THREAD

**Issue by Timo9Madrid7** [PaddlePaddle/PaddleOCR#2008]
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar does not contain the correct files:
    ├── inference.pdiparams
    ├── inference.pdiparams.info
    └── inference.pdmodel

**Comment by MissPenguin** [comment]
I just tried and it didn't go wrong. What files did you get after decompressing?

**Comment by Timo9Madrid7** [comment]
> I just tried and it didn't go wrong. What files did you get after decompressing?

I used Windows10 and it showed like this ↓
![image](https://user-images.githubusercontent.com/37281330/108688346-15b7a380-74f8-11eb-8804-112d59b62bca.png)

**Comment by noitq** [comment]
@Timo9Madrid7 please try with this command `tar -xzvf ch_ppocr_mobile_v2.0_rec_infer.tar `

**Comment by dawn-123** [comment]
you shoud use command in cmd tar -xzvf ch_ppocr_mobile_v2.0_rec_infer.tar.
