### ISSUE TITLE
模型预测速度比较慢

### ISSUE THREAD

**Issue by wangtao666666** [PaddlePaddle/PaddleOCR#201]
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False  预测一张图片大概2s,有没有可以加快速度的办法

**Comment by LDOUBLEV** [comment]
预测单个图像可能是初始化的问题，导致占了很多时间，你可以试试连续预测多张图像，从第二张开始速度会快很多。
```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
```

另一个加速的方法就是把识别的batch_num 减小，调整rec_batch_num参数：
```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False  --rec_batch_num=6
```

**Comment by wangtao666666** [comment]
> 预测单个图像可能是初始化的问题，导致占了很多时间，你可以试试连续预测多张图像，从第二张开始速度会快很多。
> 
> ```
> python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
> ```
> 
> 另一个加速的方法就是把识别的batch_num 减小，调整rec_batch_num参数：
> 
> ```
> python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False  --rec_batch_num=6
> ```
对连续预测多张图片也相对比较慢，400张图片大概300s

**Comment by mujinbao** [comment]
> > 预测单个图像可能是初始化的问题，导致占了很多时间，你可以试试连续预测多张图像，从第二张开始速度会快很多。
> > ```
> > python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
> > ```
> > 
> > 
> > 另一个加速的方法就是把识别的batch_num 减小，调整rec_batch_num参数：
> > ```
> > python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False  --rec_batch_num=6
> > ```
> 
> 对连续预测多张图片也相对比较慢，400张图片大概300s

@wangtao666666 我使用的rtx 2080，图像分辨率230*230，连续预测30次，最终平均运行时长在200ms，对于这个大小的图片属实有点慢了
另外有大佬知道如何在python中设置batch 1吗

**Comment by mujinbao** [comment]
使用CPU的话时间确实比较慢，我这里用的i7-8700，300*300的图像 服务端模型要300ms，移动端模型要50ms，不过GPU要快很多，经过模型预热后，RTX2080运行时间是16ms

**Comment by SixGodGG** [comment]
cpu 就是这样，GPU第一张图慢，后面很快，可以放入整个文件夹，例如：
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=True

**Comment by bigvine2** [comment]
服务器部署会快一些，大约在1s以内，本地台式机和楼主测试一样，的确比较慢，另外发现CPU结果与GPU结果差不多，这个让我很疑惑，不知道哪位老兄可以解答一下
![图片](https://user-images.githubusercontent.com/44392161/88142237-bb83f680-cc27-11ea-9ea4-a6b2d848a0ec.png) 
![图片](https://user-images.githubusercontent.com/44392161/88142257-c5a5f500-cc27-11ea-8959-04e08a7d48eb.png)
第一个是GPU结果，第二个是CPU结果，让人困惑

**Comment by idlesysman** [comment]
2秒？我这要37秒咋个破

**Comment by zhuliangliang** [comment]
> 

37 秒？我这样 180 秒咋整…

**Comment by liuyike98** [comment]
> > 
> 
> 37 秒？我这要 180 秒咋整…

180秒离谱
