### ISSUE TITLE
编译了v2.0版的c++程序，使用ocr_system.exe测试效果和官方截图差好多

### ISSUE THREAD

**Issue by scfw** [PaddlePaddle/PaddleOCR#2015]
推理库 模型均已核实为2.0版。使用tools文件夹下的config.txt，参数未修改。无法重现官方的识别效果
该如何下手排查问题？

**Comment by littletomatodonkey** [comment]
使用官方的demo图片也不行吗？可以把命令、配置和运行结果截图发来看下吗？

**Comment by scfw** [comment]
编译时对opencv的版本有要求吗？必须3.4.6吗

**Comment by scfw** [comment]
![12333](https://user-images.githubusercontent.com/49031041/108320294-937c6600-71fd-11eb-9141-58655b08fb7e.png)
麻烦你给看一下

**Comment by littletomatodonkey** [comment]
1. 这看着有少量漏检，使用python inference的结果也是这样吗？你也可以把原图上传上来，我这边测试下
2. opencv版本没有限制，建议使用稳定版本的opencv

**Comment by scfw** [comment]
图片就是官方自带的那个doc\imgs\00009282.jpg

**Comment by scfw** [comment]
python版的我还没有试过。我把这个图片上传到官方演示版，好像也达不到官方截图里的准确度

**Comment by scfw** [comment]
![00009282](https://user-images.githubusercontent.com/49031041/108321381-0803d480-71ff-11eb-8b2d-1ed2a7a99ca4.jpg)
请问这个图是由哪个demo生成的？

**Comment by littletomatodonkey** [comment]
用的是server端模型 ，首页可以下载，我这边使用server端模型试了下，没什么问题哈

![image](https://user-images.githubusercontent.com/14270174/108322173-1d2d3300-7200-11eb-9f09-94b0bd77d137.png)


![image](https://user-images.githubusercontent.com/14270174/108322125-0d155380-7200-11eb-83f7-ef951c378322.png)

**Comment by scfw** [comment]
1 我之前用的是mobile模型，问题是出在模型的选择上吗？
2 你用的是c++的demo吗？

**Comment by scfw** [comment]
![12111](https://user-images.githubusercontent.com/49031041/108322767-d3911800-7200-11eb-9a91-da8c50482484.png)
2.0的推理库，从这儿下载对吧？

**Comment by littletomatodonkey** [comment]
是的，python和cpp inference，在超参数相同的情况下，结果几乎一致，

**Comment by scfw** [comment]
c++版出的图ocr_vis.png，就是很简陋对吗？

**Comment by scfw** [comment]
感觉python版的demo比c++版的强好多

**Comment by littletomatodonkey** [comment]
是的，输出的可视化没有做的那么炫酷，python的更好实现一些，不过识别出的文本框和结果都是基本一致的

**Comment by scfw** [comment]
你发的验证图里，丢掉了”最高洗涤温度30C“，没有识别出来

**Comment by littletomatodonkey** [comment]
你好，这是因为添加了一个使用dilation的选项，检测效果在很多图片上都更好一些，所以默认为true了，你可以把这里修改为false，就不会有漏检的问题了，感谢反馈，我们也完善下代码

https://github.com/PaddlePaddle/PaddleOCR/blob/ecc408a6dbbba743b7479e1a1c454d6b388474f4/tools/infer/predict_det.py#L67
