### ISSUE TITLE
请问一下，有没有遇到过横排和竖排数据混合训练时不收敛的情况？

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#2017]
请问一下，有没有遇到过横排和竖排数据混合训练时不收敛的情况？发现一旦加大竖排数据的比例，横排效果就不好，加大横排数据的比例，竖排效果就不好

**Comment by MissPenguin** [comment]
训练检测还是识别

**Comment by cjt222** [comment]
识别模型

**Comment by littletomatodonkey** [comment]
你好，我们的模型也是基于横竖排数据混合训练得到的，应该都是可以收敛得，不过主要还是考虑到了横排的情况，如果你需要同时保证二者的识别效果都很好，建议使用server端模型进行finetune（参数量更大，效果好一些），同时增加训练的数据量，保证二者比例尽量均衡

**Comment by cjt222** [comment]
横排和竖排的比例是多少啊

**Comment by cjt222** [comment]
竖排的数据是否开放了呢？

**Comment by littletomatodonkey** [comment]
训练的时候，横排为竖排数据量的10倍左右，暂时没有开放

**Comment by cjt222** [comment]
训练时有加预训练参数吗？还是直接重头开始训？

**Comment by littletomatodonkey** [comment]
训练的时候分两个阶段，第一阶段是合成数据+真实数据一起训练，第二阶段是只用真实数据进行finetune，加载的是第一阶段的pretrain，

**Comment by cjt222** [comment]
真实数据finetune时候会覆盖不到全字表吧，这样学起来是不是会对真实数据以外的字效果不好？

**Comment by Evezerest** [comment]
这个可以自己搭建数据集覆盖
