### ISSUE TITLE
老问题了，这个到底是什么原因呢

### ISSUE THREAD

**Issue by hudielv** [PaddlePaddle/PaddleOCR#2018]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1613617811 (unix time) try "date -d @1613617811" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f56bed7c000) received by PID 31381 (TID 0x7f58b672d740) from PID 18446744072616394752 ***]

**Comment by MissPenguin** [comment]
这是什么环境下执行什么操作的报错呢

**Comment by hudielv** [comment]
已经有很多人提了这个错误，我之前提过，可以看下之前提过的

**Comment by MissPenguin** [comment]
这种一般是环境问题，需要提供一下你的环境配置才好查问题

**Comment by xxllp** [comment]
个人感觉是资源不足  cpu或者内存太小了

**Comment by damengdameng** [comment]
请问下这个解决了吗？我cuda10.0 cudnn7.6.5 安装paddle-gpu 2.0.0 在安装验证的时候报这个错误
