### ISSUE TITLE
train recognition

### ISSUE THREAD

**Issue by raminrahimi6970** [PaddlePaddle/PaddleOCR#2019]
I want to train recognition for my language
Train recognition just run on GPU?
I want to  train  recognition on cpu but get erro like this...
![image](https://user-images.githubusercontent.com/29606778/108331266-d8939e80-71e3-11eb-8d0e-be064b3aeeea.png)

we should set num_servers or num worker for cpu???

can you help me???

**Comment by littletomatodonkey** [comment]
You can directly use

```
python3 tools/train.py -c xxx.yaml
```

to train on cpu.

**Comment by raminrahimi6970** [comment]
thanks
