### ISSUE TITLE
服务器端C++预测，编译Paddle预测库出现错误，请问这个要怎么解决呢

### ISSUE THREAD

**Issue by niudali1** [PaddlePaddle/PaddleOCR#2020]
Found Paddle host system: , version: 15.11
-- Found Paddle host system's CPU: 8 cores
-- The CXX compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
**-- Looking for pthread_create in pthreads - not found**
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CXX compiler: /usr/bin/c++, version: GNU 6.3.0
-- C compiler: /usr/bin/cc, version: GNU 6.3.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
CMake Warning at CMakeLists.txt:219 (MESSAGE):
  Disable NCCL when compiling without GPU.  Force WITH_NCCL=OFF.

-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /home/gxj/Desktop/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- MKLML_VER: csrmm_mklml_lnx_2019.0.5, MKLML_URL: http://paddlepaddledeps.bj.bcebos.com/csrmm_mklml_lnx_2019.0.5.tgz
-- Found cblas and lapack in MKLML (include: /home/gxj/Desktop/Paddle/build/third_party/install/mklml/include, library: /home/gxj/Desktop/Paddle/build/third_party/install/mklml/lib/libmklml_intel.so)
-- Set /home/gxj/Desktop/Paddle/build/third_party/install/mkldnn/lib to runtime path
-- MKLDNN library: /home/gxj/Desktop/Paddle/build/third_party/install/mkldnn/lib/libdnnl.so
-- Protobuf protoc executable: /home/gxj/Desktop/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/gxj/Desktop/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/gxj/Desktop/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/gxj/Desktop/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.13", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.13", minimum required is "2.7") 
-- Found PY_pip: /home/gxj/.local/lib/python2.7/site-packages/pip  
-- Found PY_numpy: /usr/lib/python2.7/dist-packages/numpy  
-- Found PY_wheel: /usr/lib/python2.7/dist-packages/wheel  
-- Could NOT find PY_google.protobuf (missing: PY_GOOGLE.PROTOBUF) 
CMake Error at cmake/python_module.cmake:27 (message):
  **python module google.protobuf is not found**
Call Stack (most recent call first):
  cmake/external/python.cmake:71 (find_python_module)
  cmake/third_party.cmake:230 (include)
  CMakeLists.txt:263 (include)

-- Configuring incomplete, errors occurred!
See also "/home/gxj/Desktop/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/gxj/Desktop/Paddle/build/CMakeFiles/CMakeError.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
make: *** No rule to make target 'inference_lib_dist'。 停止

**Comment by LDOUBLEV** [comment]
> -- Could NOT find PY_google.protobuf (missing: PY_GOOGLE.PROTOBUF)
> python module google.protobuf is not found

看你的日志里有上述报错，好像和你的环境有关系 执行`pip install protobuf`再试下

**Comment by niudali1** [comment]
已经安装了这个了，还是同样错误，Looking for pthread_create in pthreads - not found ，感觉这个也很有问题，有知道怎么回事的吗

**Comment by LDOUBLEV** [comment]
感觉你的cmake版本也不对，你用的cmake版本是多少，我的是3.16.0 编译没问题

建议你在docker里运行，推荐使用的docker是： https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/installation.md

![image](https://user-images.githubusercontent.com/26592129/108502445-c2720500-72ed-11eb-99cd-c606c1ce72e5.png)

**Comment by niudali1** [comment]
我是cmake3.18.5,我是docker

**Comment by niudali1** [comment]
我试试docker

**Comment by niudali1** [comment]
还是依赖问题，通过这篇博客解决了  https://blog.csdn.net/liutong123987/article/details/79303548
