### ISSUE TITLE
会出现最后一个字重复的情况

### ISSUE THREAD

**Issue by xiangjiaozhizuo** [PaddlePaddle/PaddleOCR#2025]
成果文件框的字个数也是正确的，只是输出的结果会把最后一个字或数重复一下
![1](https://user-images.githubusercontent.com/50776393/108374052-7f575980-723b-11eb-86d4-764ee0904e7a.png)
![2](https://user-images.githubusercontent.com/50776393/108374097-8b431b80-723b-11eb-883f-107d5e31497a.png)
![3](https://user-images.githubusercontent.com/50776393/108374113-9007cf80-723b-11eb-8c1c-6c3d0b49ebb4.png)
![4](https://user-images.githubusercontent.com/50776393/108374132-94cc8380-723b-11eb-93a8-271267b3e803.png)

**Comment by LDOUBLEV** [comment]
你好，这个属于已知问题，解决中

**Comment by xiangjiaozhizuo** [comment]
好的，谢谢哈！请问有没有paddleocr的nuget包呢？

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 礼！
 &nbsp;
 &nbsp;
 唐炳林&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 下午2:13
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"持伞先生"<214732192@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 会出现最后一个字重复的情况 (#2025)





 
你好，这个属于已知问题，解决中

**Comment by xiangjiaozhizuo** [comment]
谢谢哈！
&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 礼！
 &nbsp;
 &nbsp;
 唐炳林&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Double_V"<notifications@github.com&gt;; 
发送时间: 2021年2月19日(星期五) 下午2:13
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;; 
抄送: "持伞先生"<214732192@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 会出现最后一个字重复的情况 (#2025)





 
你好，这个属于已知问题，解决中

**Comment by LDOUBLEV** [comment]
没有paddleocr的nuget包

**Comment by singlebear** [comment]
> 你好，这个属于已知问题，解决中

动态图版本我也遇到了这个问题，不止结尾字符，完全随机的任意位置重复N个。这个问题目前是定位BUG在推理端还是训练端，是否需要重新训练字库？

**Comment by xiangjiaozhizuo** [comment]
是推理端出现这个问题，应该不需要重新训练字库，因为推理端会生成一个图片，生成的图片上框的文字数量和个数是正确的




还有，我把封装后，传递出来的中文结果会出现只有三个字符的情况（只有一个中文需要识别），结果不完整，改天我再在DOS下直接运行程序看下效果。当然这个有可能是我封装错误，因为我水平非常菜哈，我以前是用VB的，现在为了这个识别才开始在学C++，所以这个问题有可能是我自己的错误

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 礼！
 &nbsp;
 &nbsp;
 唐炳林&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 上午9:17
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"持伞先生"<214732192@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 会出现最后一个字重复的情况 (#2025)





  
你好，这个属于已知问题，解决中
  
动态图版本我也遇到了这个问题，不止结尾字符，完全随机的任意位置重复N个。这个问题目前是定位BUG在推理端还是训练端，是否需要重新训练字库？

**Comment by singlebear** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/2072 懒得等官方更新了，检查了下代码，问题应该在这。我这改了正常了。

**Comment by ddebby** [comment]
遇到同样的问题，期待fix
![image](https://user-images.githubusercontent.com/7961354/128976572-149b27c4-729d-43f7-8d93-190d8d42f98a.png)
