### ISSUE TITLE
c++版本的推理库支持批量识别吗？支持的话该如何调用呢？

### ISSUE THREAD

**Issue by scfw** [PaddlePaddle/PaddleOCR#2028]

**Comment by LDOUBLEV** [comment]
现在的代码还不支持批量识别，你可以改一下代码，输入reshape为[batch, channels, h, w]的格式就行，目前默认的batch=1

**Comment by scfw** [comment]
2.0版的好像不返回index了，遇到换行的一段长文字，就不知道怎么拼接了
