### ISSUE TITLE
c++服务端编译问题

### ISSUE THREAD

**Issue by niudali1** [PaddlePaddle/PaddleOCR#2032]
Scanning dependencies of target ocr_system
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[100%] Linking CXX executable ocr_system
CMakeFiles/ocr_system.dir/src/ocr_cls.o：在函数‘PaddleOCR::Classifier::Run(cv::Mat&)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:38：对‘paddle_infer::Predictor::GetInputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:39：对‘paddle_infer::Predictor::GetInputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:46：对‘paddle_infer::Predictor::GetOutputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:47：对‘paddle_infer::Predictor::GetOutputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/ocr_system.dir/src/ocr_cls.o：在函数‘PaddleOCR::Classifier::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:75：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/ocr_system.dir/src/ocr_det.o：在函数‘PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:23：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/ocr_system.dir/src/ocr_det.o：在函数‘PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:74：对‘paddle_infer::Predictor::GetInputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:75：对‘paddle_infer::Predictor::GetInputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:81：对‘paddle_infer::Predictor::GetOutputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:82：对‘paddle_infer::Predictor::GetOutputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/ocr_system.dir/src/ocr_rec.o：在函数‘PaddleOCR::CRNNRecognizer::Run(std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >, cv::Mat&, PaddleOCR::Classifier*)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:46：对‘paddle_infer::Predictor::GetInputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:47：对‘paddle_infer::Predictor::GetInputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:53：对‘paddle_infer::Predictor::GetOutputNames[abi:cxx11]()’未定义的引用
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:54：对‘paddle_infer::Predictor::GetOutputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/ocr_system.dir/src/ocr_rec.o：在函数‘PaddleOCR::CRNNRecognizer::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/gxj/Desktop/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:98：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/ocr_system.dir/build.make:264: recipe for target 'ocr_system' failed
make[2]: *** [ocr_system] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by LDOUBLEV** [comment]
建议使用Paddle 2.0版本的预测库，预测库链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

**Comment by hnyztang** [comment]
> 建议使用Paddle 2.0版本的预测库，预测库链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> 
> GetInputHandle和GetOutputHandle是2.0预测库才有的属性

这个可能是什么原因导致的？ 我也遇到这个问题，换了几个版本，都报这个错！！！

**Comment by wangxiang1219** [comment]
> > 建议使用Paddle 2.0版本的预测库，预测库链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> > GetInputHandle和GetOutputHandle是2.0预测库才有的属性
> 
> 这个可能是什么原因导致的？ 我也遇到这个问题，换了几个版本，都报这个错！！！

请问这个错误解决了吗？

**Comment by wangxiang1219** [comment]
> 建议使用Paddle 2.0版本的预测库，预测库链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> 
> GetInputHandle和GetOutputHandle是2.0预测库才有的属性

换了版本还是报相同的错误
