### ISSUE TITLE
'Namespace' object has no attribute 'use_dialtion'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2034]
python cs.py
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/root/.paddleocr/2.0/rec/ch', use_angle_cls=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
Traceback (most recent call last):
  File "cs.py", line 4, in <module>
    ocr = PaddleOCR() # need to run only once to download and load model into memory
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 269, in __init__
    super().__init__(postprocess_params)
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 67, in __init__
    postprocess_params["use_dilation"] = args.use_dialtion
AttributeError: 'Namespace' object has no attribute 'use_dialtion'

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/2035 and https://github.com/PaddlePaddle/PaddleOCR/pull/2036

**Comment by zhfkt** [comment]
估计是这个修改导致的 - https://github.com/PaddlePaddle/PaddleOCR/commit/5e555a80473fbca5f033171aff073db75d4b523c#r47311263

**Comment by zhfkt** [comment]
另外PPOCRLabel 也由于这个参数use_dialtion导致无法启动 ，而且            

 postprocess_params["use_dilation"] = args.use_dialtion 中

的后面部分 dialtion 拼错了。

**Comment by LDOUBLEV** [comment]
感谢指正，在PR2037中修复了  https://github.com/PaddlePaddle/PaddleOCR/pull/2037

**Comment by monkeycc** [comment]
`from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang="ch") # need to run only once to download and load model into memory
img_path = '/root/PaddleOCR/doc/imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

from PIL import Image
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='/root/PaddleOCR/doc/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')`

-----------------------------
python cs.py
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/root/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
Traceback (most recent call last):
  File "cs.py", line 4, in <module>
    ocr = PaddleOCR(use_angle_cls=True, lang="ch") # need to run only once to download and load model into memory
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 269, in __init__
    super().__init__(postprocess_params)
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 67, in __init__
    postprocess_params["use_dilation"] = args.use_dilation
AttributeError: 'Namespace' object has no attribute 'use_dilation'

@LDOUBLEV

**Comment by monkeycc** [comment]
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True

Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 144, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/root/PaddleOCR/tools/infer/predict_det.py", line 67, in __init__
    postprocess_params["use_dilation"] = args.use_dilation
AttributeError: 'Namespace' object has no attribute 'use_dilation'

改了之后 不能正常用

**Comment by LDOUBLEV** [comment]
更新代码再试下，https://github.com/PaddlePaddle/PaddleOCR/pull/2038 这里修了

**Comment by LDOUBLEV** [comment]
更新代码再试下

**Comment by zhfkt** [comment]
PPOCRLabel依然不能用:

--------------------------

python PPOCRLabel.py --lang ch



Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\zhfkt/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\zhfkt/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\zhfkt/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2005, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 1993, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 1986, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file)
  File "PPOCRLabel.py", line 111, in __init__
    self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=False, lang=lang)
  File "C:\Users\zhfkt\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\paddleocr.py", line 269, in __init__
    super().__init__(postprocess_params)
  File "..\tools\infer\predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "..\tools\infer\predict_det.py", line 67, in __init__
    postprocess_params["use_dilation"] = args.use_dilation
AttributeError: 'Namespace' object has no attribute 'use_dilation'

**Comment by LDOUBLEV** [comment]
更新github到最新代码，今早修复了 https://github.com/PaddlePaddle/PaddleOCR/pull/2038   https://github.com/PaddlePaddle/PaddleOCR/pull/2039

**Comment by zhfkt** [comment]
我看到报错是因为我们pip装了 paddleocr 的whl的包。由于只更新了github，而whl包没更新，所以会在本地的site-packages中报错： File "C:\Users\zhfkt\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\paddleocr.py", line 269, in init
 报错。

希望也可以更新 paddleocr的pip whl包。

**Comment by LDOUBLEV** [comment]
嗯，很快就会更新
你也可以按照PR里的内容 https://github.com/PaddlePaddle/PaddleOCR/pull/2038   https://github.com/PaddlePaddle/PaddleOCR/pull/2039 修改你的本地文件
或者clone PaddleOCR后从本地再编译一个whl包
```
git clone https://github.com/PaddlePaddle/PaddleOCR
cd PaddleOCR
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x是paddleocr的版本号
```

**Comment by weijiang2009** [comment]
Thanks for the quick fix and it works for my case
