### ISSUE TITLE
PPOCRLabel编辑识别文字时误触发快捷键

### ISSUE THREAD

**Issue by park911011** [PaddlePaddle/PaddleOCR#2040]
如输入文字zhang，其中有字母a，是返回上一张图片的快捷键，于是还没输入成功就返回上一张，本张没有确认的识别结果全部丢失。

**Comment by Evezerest** [comment]
使用的是系统自带输入法吗

**Comment by park911011** [comment]
搜狗输入法Mac版

**Comment by Evezerest** [comment]
可以根据readme的近期更新里面的提示来切换一下输入法，推荐使用默认输入法，第三方输入法需要额外设置。或者使用默认输入法输入后再次切换回第三方输入法。

**Comment by park911011** [comment]
好的谢谢

**Comment by park911011** [comment]
换了默认输入法还会有这种情况。

**Comment by Evezerest** [comment]
你好，我们这边测试是没问题的。能把问题界面截个图吗，在识别结果中有输入的情况下。
