### ISSUE TITLE
mac下docker编译失败

### ISSUE THREAD

**Issue by zerogaofeng** [PaddlePaddle/PaddleOCR#2041]
按照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/deploy/cpp_infer/readme_en.md这个下面的 
rm -rf build
mkdir build
cd build

cmake  .. \
    -DWITH_CONTRIB=OFF \
    -DWITH_MKL=ON \
    -DWITH_MKLDNN=ON  \
    -DWITH_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DON_INFER=ON \
    -DWITH_PYTHON=ON
make -j
make inference_lib_dist来编译，在make的时候，出现下面错误：

76%] Building CXX object src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_reorder.cpp.o

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
src/cpu/CMakeFiles/dnnl_cpu.dir/build.make:270: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_reorder.cpp.o' failed
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_reorder.cpp.o] Error 1
CMakeFiles/Makefile2:339: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/all' failed
make[4]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed

**Comment by WenmuZhou** [comment]
这个在paddle下面提问看看

**Comment by littletomatodonkey** [comment]
可以直接下载编译好的：https://paddle-inference-lib.bj.bcebos.com/mac/2.0.0/cpu_avx_openblas/paddle_inference.tgz
