### ISSUE TITLE
CRNN转换为ONNX时候报错

### ISSUE THREAD

**Issue by SealQ** [PaddlePaddle/PaddleOCR#2042]
执行命令为: paddle2onnx --model_dir ./inference/CRNN_ORIGIN/  --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./onnx/rec_2021_2_9CRNN_ONNX/rec_CRNN.onnx --opset_version 10 --enable_onnx_checker True

报错信息 :Bad node spec: input: "Constant@2" input: "Constant@1" input: "Gather@0" output: "ScatterND@0" name: "ScatterND@0" op_type: "ScatterND"

![image](https://user-images.githubusercontent.com/56471409/108582514-d873da00-736e-11eb-9e95-8fe64b9bfac4.png)

**Comment by WenmuZhou** [comment]
paddle2onnx通过源码安装试一下

**Comment by SealQ** [comment]
> paddle2onnx通过源码安装试一下

您好，使用了源码安装之后依然存在相同的问题

**Comment by WenmuZhou** [comment]
--opset_version  这个参数改为12
