### ISSUE TITLE
PaddleOCR用C++部署出现问题

### ISSUE THREAD

**Issue by MartinDing-hub** [PaddlePaddle/PaddleOCR#2045]
我使用的系统环境是ubuntu18.04，在运行最后一步：sh tools/run.sh时，报错：.build/ocr_system:error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory（如下图所示）
![2021-02-20 12-45-27 的屏幕截图](https://user-images.githubusercontent.com/70771429/108584109-94d29d80-7379-11eb-9671-7130a0a7fecf.png)
可是，但我使用locate命令来查找libiomp5.so时，发现python环境下是存在这个库文件的（如下图所示）
![2021-02-20 12-47-39 的屏幕截图](https://user-images.githubusercontent.com/70771429/108584137-d9f6cf80-7379-11eb-9af8-d8c5d695c163.png)
所以我想知道，python环境下的libiomp5.so可以用在C++部署的PaddleOCR中吗？
如果可以，我要如何进行操作？如果不可以，我要如何获取这个库文件

我所有的操作步骤都是根据“服务器端C++预测”readme文档来一步步完成的，现在就差最后一步sh tools/run.sh出结果了（如下图所示）
![2021-02-20 12-50-53 的屏幕截图](https://user-images.githubusercontent.com/70771429/108584189-48d42880-737a-11eb-9c7e-687880c3d022.png)

**Comment by WenmuZhou** [comment]
看看这个能不能解决你的问题

**Comment by MartinDing-hub** [comment]
我将python环境下的libiomp5.so复制到/home/martin/paddle_inference/paddle/lib/目录下后（如下图所示），运行sh tools/run.sh仍然报相同的错误
![2021-02-20 15-35-34 的屏幕截图](https://user-images.githubusercontent.com/70771429/108587966-a758d100-7391-11eb-94d6-b2a127b8461c.png)
我不知道现在错误，是因为我将库文件放错了位置，还是说python的库文件和C++的库文件不能混用！

我的情况还与您奉献给我的博客有些区别，博客中都是python的环境，而我这里是C++的环境为主

**Comment by WenmuZhou** [comment]
可以试一下拷贝到/usr/lib

**Comment by MartinDing-hub** [comment]
嗯，拷贝到/usr/lib目录下，上述的问题确实解决了，谢谢！

但是，我的最终结果与文档最后的很不一样
![2021-02-20 18-13-26 的屏幕截图](https://user-images.githubusercontent.com/70771429/108592153-6bc90180-73a7-11eb-8341-0c88010a0445.png)
并没有显示文字的识别结果，而是将我要识别的图片在我运行的目录下复制了一份，这个是为什么？
