### ISSUE TITLE
Android Demo 无法编译，NDK路径已经配置好了，也不行

### ISSUE THREAD

**Issue by jiayuanfa** [PaddlePaddle/PaddleOCR#2046]
![image](https://user-images.githubusercontent.com/9419485/108585495-ca7c8400-7383-11eb-81b4-badee2725c17.png)

![image](https://user-images.githubusercontent.com/9419485/108585478-bc2e6800-7383-11eb-93c4-29c8e8dedfd9.png)

**Comment by weidenbach** [comment]
I had the same issue. Update android gradle plugin to 4.1.2 and gradle to 6.5, then it worked for me.
