### ISSUE TITLE
Ubuntu20使用docker部署paddleocr服务器端，CPU占用率太高，检测识别一张图片要30秒

### ISSUE THREAD

**Issue by adiranxym** [PaddlePaddle/PaddleOCR#2047]
paddlepaddle 2.0.0rc1
安装了ocr_system
直接使用git下来的PaddleOCR文件夹
服务器端部署
使用单线程启动，可以正常识别图片，但是很慢， 平均一张图片要30多秒，使用的paddleocr文件夹中自带的图
使用多线程启动，gunicorn都会报WORKER TIMEOUT错误
使用的是vm虚拟机， CPU，10核，64G内存
安装过程都正常， 但是识别图片非常慢， 多线程会报错，是哪里设置有问题吗

**Comment by WenmuZhou** [comment]
慢是因为cpu跑模型本来就慢

**Comment by adiranxym** [comment]
也不可能这么慢啊， 测了另一张小图，都用了快5分钟了，可能是设置得不对
