### ISSUE TITLE
在OCR领域中，对于某些英文字符（例如S），是否识别出大写字符和小写字符都可以认为是正确的字符 ？

### ISSUE THREAD

**Issue by zhfkt** [PaddlePaddle/PaddleOCR#2048]
在rec_metric.py 中

https://github.com/PaddlePaddle/PaddleOCR/blob/ff1b0a362141bdd04e1d548a4586ee27b20b5cb2/ppocr/metrics/rec_metric.py#L33

可以看到需要word完全相同才会认为是一个match。

但是对于某些英文字符（例如S），小写的s和大写的S在很多时候无法区分（不像字符a，大写A和小写a有显著的不同）。在这种情况下，对于字符s，是否识别出大写字符和小写字符都可以认为是正确的字符 ?

**Comment by WenmuZhou** [comment]
这种可以手动修改的哈

**Comment by heyhumor** [comment]
这个要参照邻近字符吧，有参照系还是很好区分的
