### ISSUE TITLE
Windows10+VS2019部署PaddleOCR的C++接口问题

### ISSUE THREAD

**Issue by MartinDing-hub** [PaddlePaddle/PaddleOCR#2049]
我的环境是Windows10、OpenCV3.4.6、VS2019进行C++的PaddleOCR部署
![image](https://user-images.githubusercontent.com/70771429/108588356-b6d91980-7393-11eb-9ccf-b3c8a659cf10.png)
上图为PaddleOCR项目所处的文件夹，其中opencv文件夹中存放的是OpenCV3.4.6的库，fluid_inference文件夹中存放的是Paddle预测库（用的是2.0.0rc-0的版本），inference文件夹中存放的是中英文通用OCR推理模型
![image](https://user-images.githubusercontent.com/70771429/108588445-2fd87100-7394-11eb-933c-9bb152d67b82.png)
所有的操作步骤全部是根据下图所示的博客一步步来完成的
![image](https://user-images.githubusercontent.com/70771429/108588494-86de4600-7394-11eb-9ac3-5495f69b4008.png)
目前我已经在D:\Paddle-C++\PaddleOCR\deploy\cpp_infer\out\build\x64-Release目录下生成了ocr_system.exe可执行文件
![无标题](https://user-images.githubusercontent.com/70771429/108588574-e5a3bf80-7394-11eb-90b9-44203de6173d.png)
并且已经对D:\Paddle-C++\PaddleOCR\deploy\cpp_infer\tools\目录下的config.txt文件进行了修改，修改结果如下图所示：
![image](https://user-images.githubusercontent.com/70771429/108588671-606cda80-7395-11eb-91ed-6deb16b5408c.png)

问题是：
在Powershell中运行程序，没有任何的反应，结果如下：
![image](https://user-images.githubusercontent.com/70771429/108588705-885c3e00-7395-11eb-9451-d5338af197c5.png)
而在windows自带的cmd中运行程序总说找不到paddle和opencv的库
![屏幕截图(6)](https://user-images.githubusercontent.com/70771429/108588775-e557f400-7395-11eb-93c9-11645d9f90f3.png)
![屏幕截图(7)](https://user-images.githubusercontent.com/70771429/108588791-fc96e180-7395-11eb-80b9-1e92cd223217.png)
![image](https://user-images.githubusercontent.com/70771429/108588827-3962d880-7396-11eb-847c-e0e26dfeaec8.png)

**Comment by WenmuZhou** [comment]
在你的paddle-c++里找到对应的dll，拷贝到ocr_system.exe所在文件夹试试

**Comment by MartinDing-hub** [comment]
可以了，谢谢！
