### ISSUE TITLE
c++编译paddle推理库时，克隆的速度太慢

### ISSUE THREAD

**Issue by niudali1** [PaddlePaddle/PaddleOCR#2054]
[  0%] Performing install step for 'extern_gflags'
-- extern_gflags install command succeeded.  See also /home/gxj/Desktop/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-install-*.log
[  0%] Completed 'extern_gflags'
[  0%] Built target extern_gflags
[  0%] copy_if_different /home/gxj/Desktop/Paddle/build/paddle/fluid/operators/jit/kernels.h
[  0%] Built target copy_kernels_command
[  0%] copy_if_different /home/gxj/Desktop/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  0%] Built target copy_paddle_inference_pass_command
[  0%] copy_if_different /home/gxj/Desktop/Paddle/build/paddle/fluid/pybind/pybind.h
[  0%] Built target copy_pybind_command
[  0%] Performing update step for 'extern_glog'
-- extern_glog update command succeeded.  See also /home/gxj/Desktop/Paddle/build/third_party/glog/src/extern_glog-stamp/extern_glog-update-*.log
[  0%] No patch step for 'extern_glog'
[  0%] Performing configure step for 'extern_glog'
-- extern_glog configure command succeeded.  See also /home/gxj/Desktop/Paddle/build/third_party/glog/src/extern_glog-stamp/extern_glog-configure-*.log
[  0%] Performing build step for 'extern_glog'
[100%] Built target glog
[  0%] Performing install step for 'extern_glog'
-- extern_glog install command succeeded.  See also /home/gxj/Desktop/Paddle/build/third_party/glog/src/extern_glog-stamp/extern_glog-install-*.log
[  0%] Completed 'extern_glog'
[  0%] Built target extern_glog
[  0%] Built target extern_zlib
[  0%] Performing download step (git clone) for 'extern_protobuf'
正克隆到 'extern_protobuf'...

##在这里老是卡主，我把自己在gitee克隆的protobuf放到extern_protobuf目录下，它老是删除重下，有没有办法让他用我下好的protobuf，或者自己选择它的克隆地址，像在.gitmodules文件里配置那样。 l

**Comment by tink2123** [comment]
build目录里没有的话 就会重新下载，克隆速度太慢的话可以尝试添加代理
