### ISSUE TITLE
TypeError: draw_ocr() got an unexpected keyword argument 'draw_txt'

### ISSUE THREAD

**Issue by NATHAN76543217** [PaddlePaddle/PaddleOCR#2057]
Hello,
It's for report a bug.

I've just downloaded paddleOCR and when I come to test hubserving with param `is_visualize = True`
I got this error: **_TypeError: draw_ocr() got an unexpected keyword argument 'draw_txt'_**

_in tools/infer/utility.py_ draw_ocr() is prototyped:

> def draw_ocr(image,
>              boxes,
>              txts=None,
>              scores=None,
>              drop_score=0.5,
>              font_path="./doc/simfang.ttf"):

So I changed:

>         draw_img = draw_ocr(
>             image, boxes, texts, scores, draw_txt=True, drop_score=0.5)
> 

with

>         draw_img = draw_ocr(
>             image, boxes, texts, scores, drop_score=0.5, font_path='doc/fonts/french.ttf')
> 

And process work perfectly.

**Comment by tink2123** [comment]
Thanks for the feedback, you are right, we will fix this bug as soon as possible.
