### ISSUE TITLE
请问为什么image_shape只能是[3, 512, 512]?

### ISSUE THREAD

**Issue by sidongfeng** [PaddlePaddle/PaddleOCR#206]
报错原因：Error: ShapeError: broadcast dimension mismatch
![image](https://user-images.githubusercontent.com/37397706/84623299-8e9a4080-af11-11ea-9c1b-473e261101e0.png)

**Comment by dyning** [comment]
这个是模型训练，还是预测？

**Comment by sidongfeng** [comment]
训练模型

**Comment by LDOUBLEV** [comment]
可否提供完整的报错信息和运行指令

**Comment by sidongfeng** [comment]
运行指令：
![1148630c613ae60303af2b333fbc2d7](https://user-images.githubusercontent.com/37397706/84736609-c91ae080-afd8-11ea-8757-b3fcc6f4328a.png)
![bb088595e6252c1c0b9487bd7dfddb0](https://user-images.githubusercontent.com/37397706/84736634-e059ce00-afd8-11ea-8f97-73775896dcba.png)

报错信息：
![image](https://user-images.githubusercontent.com/37397706/84736754-20b94c00-afd9-11ea-82de-d03c78dae7b0.png)

**Comment by LDOUBLEV** [comment]
已修复，可以更新下代码

**Comment by sidongfeng** [comment]
谢谢更新。

**Comment by BruceHan98** [comment]
你好，我在det_db预训练模型上训练自己的数据集（图片尺寸不是默认的（3，640，640））时，修改相应的配置文件的image_shape为自己数据集的图片尺寸，出现了同样的情况：Broadcast dimension mismatch.
请问需要修改哪些文件来解决？

Error Message Summary:
----------------------
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 96, 64, 10] and the shape of Y = [16, 96, 63, 10]. Received [64] in X is not equal to [63] in Y at i:2.
