### ISSUE TITLE
paddlehub中ocr无法本地调用

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleOCR#2063]
![_L`KHUXF4W4EJ7P5 B1 $(M](https://user-images.githubusercontent.com/61171287/108662118-8ff02400-7508-11eb-971f-04d6b330e69e.png)
在aistudio上可以调用 但是本地无法正常使用

**Comment by grasswolfs** [comment]
搜一下issue或者faq，shapely  安装包的问题
