### ISSUE TITLE
armv7hf lite部署，使用1.1模型只能检测无法识别。使用2.0模型，运行segmentfault

### ISSUE THREAD

**Issue by zsun14** [PaddlePaddle/PaddleOCR#2064]
环境：
paddleocr  develop版本
paddle-lite 使用2.8的release， inference_lite_lib.armlinux.armv7hf.gcc.with_extra.with_cv.tar

崩溃步骤：
1 编译paddle-ocr deploy lite  
按照readme操作
由于要运行在树莓上，所以剥离了对NDK的依赖，重新编译了opencv4.1，生成ocr_db_crnn

2 使用linux_opt 对分别对det cls rec模型优化
模型使用pp-orc 2.0的ch_ppocr_mobile_v2.0_det ch_ppocr_mobile_v2.0_rec ch_ppocr_mobile_v2.0_cls
./opt_linux \
--model_file=./ch_ppocr_mobile_v2.0_det_infer/inference.pdmodel \
--param_file=./ch_ppocr_mobile_v2.0_det_infer/inference.pdiparams \
--optimize_out_type=naive_buffer \
--optimize_out=./det --valid_targets=arm

rec和cls同上

3 执行崩溃
![image](https://user-images.githubusercontent.com/1172257/108666342-d8600f80-7511-11eb-937d-2d285e133535.png)
`(gdb) r
Starting program: /home/pi/paddle_lite_28/demo/cxx/ocr/debug/ocr_db_crnn ./det.nb  ./rec.nb  ./cls.nb    ./1.jpg  ./ppocr_keys_v1.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1097 Setup] ARM multiprocessors name: MODEL NAME      : ARMV7 PROCESSOR REV 3 (V7L)
HARDWARE  : BCM2711

[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1098 Setup] ARM multiprocessors number: 4
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1100 Setup] ARM multiprocessors ID: 0, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1100 Setup] ARM multiprocessors ID: 1, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1100 Setup] ARM multiprocessors ID: 2, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1100 Setup] ARM multiprocessors ID: 3, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1106 Setup] L1 DataCache size is:
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1108 Setup] 32 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1108 Setup] 32 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1108 Setup] 32 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1108 Setup] 32 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1110 Setup] L2 Cache size is:
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1112 Setup] 512 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1112 Setup] 512 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1112 Setup] 512 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1112 Setup] 512 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1114 Setup] L3 Cache size is:
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1116 Setup] 0 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1116 Setup] 0 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1116 Setup] 0 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1116 Setup] 0 KB
[I  2/22 13:10:14.772 ...ild/Paddle-Lite/lite/core/device_info.cc:1118 Setup] Total memory: 1729820KB
[New Thread 0xb5f693a0 (LWP 19361)]
[New Thread 0xb57683a0 (LWP 19362)]
[New Thread 0xb4bff3a0 (LWP 19363)]

Thread 1 "ocr_db_crnn" received signal SIGSEGV, Segmentation fault.
0x0006111c in std::vector<unsigned long long, std::allocator<unsigned long long> >::operator[](unsigned int) ()
(gdb) bt
#0  0x0006111c in std::vector<unsigned long long, std::allocator<unsigned long long> >::operator[](unsigned int) ()
#1  0x00059f7c in RunRecModel(std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >, cv::Mat, std::shared_ptr<paddle::lite_api::PaddlePredictor>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<float, std::allocator<float> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::shared_ptr<paddle::lite_api::PaddlePredictor>, int) ()
#2  0x0005c058 in main ()
(gdb)
`

无法识别步骤：
1 使用此前编译程序

2 下载1.1模型，使用2.8的opt进行优化

3 执行，可以定位文字区域，但无识别结果。

**Comment by LDOUBLEV** [comment]
1.1 模型，建议用paddle lite 2.7分支，在arm8上测试是可以的

2.0模型，建议用paddle lite 2.8分支，而且2.0模型的lite代码还没上传，和1.1模型的lite代码有些不一样，所以用2.0的模型会出现段错误

**Comment by xuxiaobao-3** [comment]
> 1.1 模型，建议用paddle lite 2.7分支，在arm8上测试是可以的
> 
> 2.0模型，建议用paddle lite 2.8分支，而且2.0模型的lite代码还没上传，和1.1模型的lite代码有些不一样，所以用2.0的模型会出现段错误
> 
> 有部署问题可以加这个群：
> ![image](https://user-images.githubusercontent.com/26592129/108836744-2d804c00-760c-11eb-829c-2e8af3ff90fa.png)
群二维码失效了 重发一下可以么
