### ISSUE TITLE
如何设置只检测英文和数字？

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleOCR#2066]
你好，为了只识别英文和数字，我做了如下修改：
rec_model_dir：en_ppocr_mobile_v1.1_rec_infer
rec_char_type：en
rec_char_dict_path : ic15_dict.txt
出现错误：char_list.append(self.character[int(text_index[idx])])，IndexError: list index out of range
请问怎么修改，谢谢

**Comment by tink2123** [comment]
修改这两个参数重新试下
rec_char_type：EN
rec_char_dict_path : ppocr/utils/dict/en_dict.txt

**Comment by Yang-Changhui** [comment]
> 修改这两个参数重新试下
> rec_char_type：EN
> rec_char_dict_path : ppocr/utils/dict/en_dict.txt



> 修改这两个参数重新试下
> rec_char_type：EN
> r

**Comment by Yang-Changhui** [comment]
你好，改了还是不行，那个是en不是EN，我打错了

**Comment by tink2123** [comment]
你的预测命令是？

**Comment by Yang-Changhui** [comment]
我是在pycharm直接运行的，用中文识别模型就可以，换成英文字符识别模型就报错啦

**Comment by heyhumor** [comment]
debug找下下标，看看哪里越界了

**Comment by zhangyinzhangyin** [comment]
> 你好，为了只识别英文和数字，我做了如下修改：
> rec_model_dir：en_ppocr_mobile_v1.1_rec_infer
> rec_char_type：en
> rec_char_dict_path : ic15_dict.txt
> 出现错误：char_list.append(self.character[int(text_index[idx])])，IndexError: list index out of range
> 请问怎么修改，谢谢

请问解决了吗

**Comment by Armo00** [comment]
遇到了同样的问题，似乎是字母表越界了，有一个长度为69的玩意，但是英文字母表长度只有64

**Comment by zhangyinzhangyin** [comment]
> 遇到了同样的问题，似乎是字母表越界了，有一个长度为69的玩意，但是英文字母表长度只有64

您好，能具体说一下怎么改的吗？

**Comment by yukai09020** [comment]
请问有人改好了么
