### ISSUE TITLE
用GPU训练数据量越大为何CPU内存占用越高呢

### ISSUE THREAD

**Issue by maplelinfy** [PaddlePaddle/PaddleOCR#2067]
根据 https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/rec/dataset_traversal.py#L190
读数据是根据batchsize用生成器分批读取，为何数据量越大时CPU的内存占用也越高呢？这部分数据应该是在GPU显存里的吧

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/rec/dataset_traversal.py#L190 这里的数据还在CPU上，没有在GPU上

**Comment by maplelinfy** [comment]
> 
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/rec/dataset_traversal.py#L190 这里的数据还在CPU上，没有在GPU上

可是生成器会一批一批的读取吧，这里为何会将全部数据都读进内存了呢？
