### ISSUE TITLE
请问训练图片尺寸与模型的哪些参数有关联？

### ISSUE THREAD

**Issue by wolfryu** [PaddlePaddle/PaddleOCR#207]
icdar2015的尺寸是1280x720
发现det_db_icdar15_realder.yml里面有test_image_shape这个参数。
请问还有什么地方有这种涉及到图片尺寸与模型参数关联的参数设置？
多谢！

**Comment by dyning** [comment]
请问这个设置是想应用到训练，还是预测？主要是关注图像预处理模块，参考 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py， 里面有预处理程序

**Comment by wolfryu** [comment]
多谢！
