### ISSUE TITLE
kill进程显卡不释放

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2074]
nohup 启动训练进程之后直接kill主进程显卡不会释放显存
并且nvidia-smi只能看到显存占用，底下看不到这张卡里有进程
fuser -v /dev/nvidia* 用这个能看到具体进程，kill了所有进程之后显存会释放
想问问能不能之后的版本里改进一下，谢谢~

**Comment by LDOUBLEV** [comment]
是一个好的问题，python 本身也会存在一些进程遗留的情况，我也会反馈下这个问题，感谢
