### ISSUE TITLE
ERROR:root:DataLoader reader thread raised an exception!

### ISSUE THREAD

**Issue by NATHAN76543217** [PaddlePaddle/PaddleOCR#2075]
Hello,
I'm on macbook pro mi-2012 with OSX Sierra installed. I use paddle paddle on docker container with:

## docker desktop:
- 3 cpu / 4
- 12.5GB ram / 16GB
- 1 GB swap / 4
- 80GB mem / 280GB

I've encounter an error when I run `python3.7 tools/train.py -c /data/configs/det/ch_det_res18_db_v2.0.yml`

## Output log:
> 2021/02/22 17:53:43] root INFO: train with paddle 2.0.0 and device CPUPlace
> [2021/02/22 17:53:43] root INFO: Initialize indexs of datasets:['/data/train/train_data/ic15_data/det/det_train_icdar2015_label.txt']
> [2021/02/22 17:53:43] root INFO: Initialize indexs of datasets:['/data/train/train_data/ic15_data/det/det_test_icdar2015_label.txt']
> [2021/02/22 17:53:49] root INFO: load pretrained model from ['/data/train/best/ch/best_accuracy']
> [2021/02/22 17:53:49] root INFO: train dataloader has 125 iters, valid dataloader has 500 iters
> [2021/02/22 17:53:49] root INFO: During the training process, after the 3000th iteration, an evaluation is run every 2000 iterations
> [2021/02/22 17:53:49] root INFO: Initialize indexs of datasets:['/data/train/train_data/ic15_data/det/det_train_icdar2015_label.txt']

> ERROR:root:DataLoader reader thread raised an exception!
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
>     data = self._data_queue.get(timeout=self._timeout)
>   File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 105, in get
>     raise Empty
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
>     batch = self._get_data()
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 709, in _get_data
>     "pids: {}".format(len(failed_workers), pids))
> RuntimeError: DataLoader 2 workers exit unexpectedly, pids: 60983, 60984
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 120, in <module>
>     main(config, device, logger, vdl_writer)
>   File "tools/train.py", line 97, in main
>     eval_class, pre_best_model_dict, logger, vdl_writer)
>   File "/home/PaddleOCR/tools/program.py", line 213, in train
>     avg_loss.backward()
>   File "<decorator-gen-114>", line 2, in backward
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
>     self._run_backward(framework._dygraph_tracer(), retain_graph)
>   File "/usr/local/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
>     core._throw_error_if_process_failed()
> SystemError: (Fatal) DataLoader process (pid 60985) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:165)

### Configfile.yaml :

> 
> #for chinese server version
> Global:
>   use_gpu: false
>   epoch_num: 1200
>   log_smooth_window: 20
>   print_batch_step: 2
>   save_model_dir: /data/train/models/common
>   save_epoch_step: 1200
>   \# evaluation is run every 5000 iterations after the 4000th iteration
>   eval_batch_step: [3000, 2000]
>   \# if pretrained_model is saved in static mode, load_static_weights must set to True
>   load_static_weights: True
>   cal_metric_during_train: False
>   pretrained_model: /data/train/best/ch/best_accuracy
>   checkpoints:
>   save_inference_dir:
>   use_visualdl: False
>   infer_img: doc/imgs_en/img_10.jpg
>   save_res_path: /data/det_db/predicts_db.txt
> 
> Architecture:
>   model_type: det
>   algorithm: DB
>   Transform:
>   Backbone:
>     name: ResNet
>     layers: 18
>     disable_se: True
>   Neck:
>     name: DBFPN
>     out_channels: 256
>   Head:
>     name: DBHead
>     k: 50
> 
> Loss:
>   name: DBLoss
>   balance_loss: true
>   main_loss_type: DiceLoss
>   alpha: 5
>   beta: 10
>   ohem_ratio: 3
> 
> Optimizer:
>   name: Adam
>   beta1: 0.9
>   beta2: 0.999
>   lr:
>     name: Cosine
>     learning_rate: 0.001
>     warmup_epoch: 2
>   regularizer:
>     name: 'L2'
>     factor: 0
> 
> PostProcess:
>   name: DBPostProcess
>   thresh: 0.3
>   box_thresh: 0.6
>   max_candidates: 1000
>   unclip_ratio: 1.5
> 
> Metric:
>   name: DetMetric
>   main_indicator: hmean
> 
> Train:
>   dataset:
>     name: SimpleDataSet
>     data_dir: /data/train/train_data/ic15_data/det/
>     label_file_list:
>       - /data/train/train_data/ic15_data/det/det_train_icdar2015_label.txt
>     ratio_list: [1.0]
>     transforms:
>       - DecodeImage: # load image
>           img_mode: BGR
>           channel_first: False
>       - DetLabelEncode: # Class handling label
>       - IaaAugment:
>           augmenter_args:
>             - { 'type': Fliplr, 'args': { 'p': 0.5 } }
>             - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
>             - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
>       - EastRandomCropData:
>           size: [960, 960]
>           max_tries: 50
>           keep_ratio: true
>       - MakeBorderMap:
>           shrink_ratio: 0.4
>           thresh_min: 0.3
>           thresh_max: 0.7
>       - MakeShrinkMap:
>           shrink_ratio: 0.4
>           min_text_size: 8
>       - NormalizeImage:
>           scale: 1./255.
>           mean: [0.485, 0.456, 0.406]
>           std: [0.229, 0.224, 0.225]
>           order: 'hwc'
>       - ToCHWImage:
>       - KeepKeys:
>           keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
>   loader:
>     shuffle: True
>     drop_last: False
>     batch_size_per_card: 8
>     num_workers: 4
> 
> Eval:
>   dataset:
>     name: SimpleDataSet
>     data_dir: /data/train/train_data/ic15_data/det/
>     label_file_list:
>       - /data/train/train_data/ic15_data/det/det_test_icdar2015_label.txt
>     transforms:
>       - DecodeImage: # load image
>           img_mode: BGR
>           channel_first: False
>       - DetLabelEncode: # Class handling label
>       - DetResizeForTest:
> \#           image_shape: [736, 1280]
>       - NormalizeImage:
>           scale: 1./255.
>           mean: [0.485, 0.456, 0.406]
>           std: [0.229, 0.224, 0.225]
>           order: 'hwc'
>       - ToCHWImage:
>       - KeepKeys:
>           keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
>   loader:
>     shuffle: False
>     drop_last: False
>     batch_size_per_card: 1 # must be 1
>     num_workers: 2
> 
> 

When this append I reduce `batch_size_per_card` and `num_workers` in config and it's work, but so it's very slow.
I faced this issue many times when i work with english(rec), french(rec) or chinese(det/rec) model
What can cause such trouble?
It's prevent me from trainning a model so it's a little bit problematic ^^

Thanks

**Comment by LDOUBLEV** [comment]
First of all, it is not recommended to train DB (res18_db) on CPU (MAC) because the training process is slow.
There is a[ free website ](https://aistudio.baidu.com/aistudio/index)where you can train models using V100 GPU.

**Comment by NATHAN76543217** [comment]
Thats don't stop the problem.
I've just test with `rec_chinese_lite_train_v2.0` on ic15 dataset I add `use_shared_memory` but I got the same issue.
For the web site it's hard cause I'm french so even with google translate I can't read some part.

**Comment by DuckJ** [comment]
same problem.,even set the number works =1.
I trained the CRNN model(chinese_lite) with paddle 2.0,  I have 20 million images in datasets, the batchsize is set 256, 8 q6k GPUs were used.

**Comment by SWHL** [comment]
I have met the same problem.

**Comment by yxd117** [comment]
Had the same problem when I was using the lmdb dataset to train(just for setting the training pipeline). Found it generally hard to finetune the model, got problems here and there.

**Comment by NarasimmanSaravana1994** [comment]
I set "infer_mode" - False it worked.

Thanks.
