### ISSUE TITLE
动态图和静态图的区别

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2078]
请问一下，动态图和静态图的区别是啥呢？谢谢

**Comment by maplelinfy** [comment]
> 请问一下，动态图和静态图的区别是啥呢？谢谢

可以参考下 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/dygraph/DyGraph.html

**Comment by LDOUBLEV** [comment]
区别参考： https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/FAQ.md#q3124-paddleocr-develop%E5%88%86%E6%94%AF%E5%92%8Cdygraph%E5%88%86%E6%94%AF%E7%9A%84%E5%8C%BA%E5%88%AB

**Comment by zcswdt** [comment]
> > 请问一下，动态图和静态图的区别是啥呢？谢谢
> 
> 可以参考下 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/dygraph/DyGraph.html

好的，谢谢

**Comment by zcswdt** [comment]
> 区别参考： https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/FAQ.md#q3124-paddleocr-develop%E5%88%86%E6%94%AF%E5%92%8Cdygraph%E5%88%86%E6%94%AF%E7%9A%84%E5%8C%BA%E5%88%AB

好的，多谢，嘿嘿
