### ISSUE TITLE
对于识别网站截图的文本有没有好的方案？

### ISSUE THREAD

**Issue by who0sy** [PaddlePaddle/PaddleOCR#2079]
![screenshot-1](https://user-images.githubusercontent.com/40428449/108812847-cbfbb580-75ea-11eb-8c74-3c8b456ef60a.png)

目前的需求是对很多网站进行网页文字提取（包括图片上的文字），所以就想用OCR解决，有没有类似成熟的方案或者模型参考

**Comment by LDOUBLEV** [comment]
可以现在这个[网站](https://www.paddlepaddle.org.cn/hub/scene/ocr)上测试下识别效果

可以写个网页截图的程序，获取截图后送给PaddleOCR的模型识别

**Comment by who0sy** [comment]
@LDOUBLEV 在线体验的那个我试过，只能说惨不忍睹，没有识别出几个字
这种网站类的截图能走OCR这个方向去识别提取文字吗，我这的功能就是其他服务给张网站截图，我返回给他们文本内容

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV 在线体验的那个我试过，只能说惨不忍睹，没有识别出几个字
> 这种网站类的截图能走OCR这个方向去识别提取文字吗，我这的功能就是其他服务给张网站截图，我返回给他们文本内容

当然可以，我给你看下PaddleOCR的识别效果
![image](https://user-images.githubusercontent.com/26592129/108970475-eb631300-76bc-11eb-86fc-92dd10f82c14.png)

**Comment by who0sy** [comment]
@LDOUBLEV 效果还是不太友好，我自己基于paddleocr训练的模型也不太行，干扰因素太多了

**Comment by who0sy** [comment]
@LDOUBLEV 你用的是paddle ocr官方的那个mobile推理模型？ 我用server的怎么还没你这个识别的好？
