### ISSUE TITLE
检测出倾斜框是，识别部分怎么 处理的？

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#208]
请问：如果检测出来的文本是倾斜的，识别的时候他怎么知道是左旋还是右旋？旋转错了不就成倒的了吗？

**Comment by dyning** [comment]
检测结果是四点模型，只要保证四点是顺时针排列，通过opencv的getPerspectiveTransform和warpPerspective进行转正，但是图片如果竖直方向颠倒，的确会有问题，后面会提供一个判断文字是正向还是颠倒的分类器。

**Comment by Hupengyu** [comment]
> 请问：如果检测出来的文本是倾斜的，识别的时候他怎么知道是左旋还是右旋？旋转错了不就成倒的了吗？
涉及方向paddle_ocr就拉跨了，方向检测自己做一下吧
