### ISSUE TITLE
训练模型和推理模型效果不一致

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#2080]
PaddleOCR-release-2.0
基于det_mv3_db.yml训练车牌检测模型。
使用训练完的模型直接测试，infer_det.py，效果很好。
然后使用export_model.py对best_accuracy模型进行转换为推理模型（基于训练时的配置表config.yml），得到inference模型，使用predict_det.py做预测。效果没有前者好，检测框不紧密。

![F6726907-C310-4b5d-8CEF-EFCC44B193BC](https://user-images.githubusercontent.com/66729924/108827728-ea6cab80-7600-11eb-95f4-c477cd4f060b.png)

使用官方的ch_ppocr_mobile_v2.0_det_train进行测试，以及转换后测试效果也不一致。

如下保证predict_det.py的效果和infer_det.py一致？

**Comment by LDOUBLEV** [comment]
可能是检测的后处理参数不一致的，调整下试试。训练的后处理参数是：https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L58
预测的后处理参数是：https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/tools/infer/utility.py#L46

**Comment by simplew2011** [comment]
![image](https://user-images.githubusercontent.com/66729924/108841515-d92c9a80-7612-11eb-83c1-f78d31839a68.png)

参数是一致的。
det_limit_side_len这个参数有无影响，改了640,736,960，似乎没啥变化

**Comment by simplew2011** [comment]
以前v1.1版本也有这种问题，v2.0又出现

**Comment by simplew2011** [comment]
![image](https://user-images.githubusercontent.com/66729924/108933773-b045ed00-7686-11eb-82ee-097625a3b76a.png)


左边是infer_det.py结果，右侧是predict_det.py结果，可以看到前者和目标框比较紧密，点集回归比较准。除了上诉参数，还有那些参数可能影响predict_det.py的结果呢？

**Comment by LDOUBLEV** [comment]
你的图像能否发我测试下

**Comment by simplew2011** [comment]
> 你的图像能否发我测试下

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/312cd6298a6042 或进入 cowtransfer.com 获取，在首页输入取件码：195535（24小时内有效）

**Comment by simplew2011** [comment]
> > 你的图像能否发我测试下
> 
> 您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/312cd6298a6042 或进入 cowtransfer.com 获取，在首页输入取件码：195535（24小时内有效）

内含模型和图片

**Comment by LDOUBLEV** [comment]
找到问题了，是训练模型和预测模型的预处理不一致导致的，已经提了PR修复，可以按照PR的内容修改下代码，再试下

**Comment by simplew2011** [comment]
> 找到问题了，是训练模型和预测模型的预处理不一致导致的，已经提了[PR](https://github.com/PaddlePaddle/PaddleOCR/pull/2091)修复，可以按照PR的内容修改下代码，再试下

问题确实出现在DB预处理，但按建议改
'DetResizeForTest': None的效果还是比infer_det.py差不少，此处改成'image_shape': [640, 640]的效果会接近infer_det.py，稍稍差一点点。
![image](https://user-images.githubusercontent.com/66729924/108971566-675d5b00-76bd-11eb-90d8-ab3d616c7282.png)

**Comment by simplew2011** [comment]
原图
![image](https://user-images.githubusercontent.com/66729924/108971739-94117280-76bd-11eb-900c-d3848ebef5dd.png)

**Comment by LDOUBLEV** [comment]
是预处理不一样，我看了一下你的config文件，应该是和预测的时候一些参数没对应上导致的，train model 在eval的时候
![image](https://user-images.githubusercontent.com/26592129/108997885-207e5e00-76db-11eb-9550-283db8be150c.png)
![image](https://user-images.githubusercontent.com/26592129/108997902-270cd580-76db-11eb-8bb4-70874a28e89d.png)
在tools/infer/predict_det.py预测的时候，先修改下tools/infer/predict_det.py line42 的参数如下，
![image](https://user-images.githubusercontent.com/26592129/108998128-69cead80-76db-11eb-8abf-875891227fa4.png)
然后预测的时候调整后处理参数和config文件里的超参数一致，

```
python3.7 tools/infer/predict_det.py --det_model_dir=./data/inference/    --image_dir=./car.png  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5
```
这样得到的box是完全一样的

**Comment by LDOUBLEV** [comment]
infer/predict_det.py
```
 inference predict :[[[ 97. 528.]
  [271. 559.]
  [270. 624.]
  [ 95. 593.]]]

```
![image](https://user-images.githubusercontent.com/26592129/108998334-be722880-76db-11eb-874c-368f02e3de3f.png)


trained model results
```
train model predict : [[[ 97 528]
  [271 559]
  [270 624]
  [ 95 593]]]
```
![image](https://user-images.githubusercontent.com/26592129/108998416-da75ca00-76db-11eb-9915-0c2f7c0ef751.png)

**Comment by LDOUBLEV** [comment]
非常抱歉，后面会想办法统一下超参数，避免不必要的踩坑

**Comment by simplew2011** [comment]
> 非常抱歉，后面会想办法统一下超参数，避免不必要的踩坑

感谢。

**Comment by simplew2011** [comment]
> 非常抱歉，后面会想办法统一下超参数，避免不必要的踩坑

在训练时配置表，Eval.DetResizeForTest: image_shape: [736, 1280]可否和Train数据保持一致image_shape: [640, 640]，为什么要设置为[736, 1280]？

**Comment by LDOUBLEV** [comment]
不同数据集的shape不同，建议 Eval.DetResizeForTest:  不设置参数，就是默认为None，会根据输入图像自动初始化，你可以在训练的配置文件里把image_shape: [736, 1280] 注释掉

**Comment by lexiaoyuan** [comment]
类似的问题（已解决），在这里记录一下。
基于`det_mv3_east.yml`训练的检测模型，训练完成后使用` tools/infer_det.py`测试效果很好，转推理模型后，用
```
python3 tools/infer/predict_det.py --image_dir="./doc/imgs_my_test/" --det_model_dir="inference/det_mv3_east"
```
做预测，完全没有效果。
修改为如下命令（指定了检测算法）后就有效果了：
```
python3 tools/infer/predict_det.py --image_dir="./doc/imgs_my_test/" --det_model_dir="inference/det_mv3_east" --det_algorithm="EAST"
```

**Comment by YY007H** [comment]
> 不同数据集的shape不同，建议 Eval.DetResizeForTest: 不设置参数，就是默认为None，eval的时候会按照原图大小预测，你可以在训练的配置文件里把image_shape: [736, 1280] 注释掉

大佬，你好，在release/2.1分支上，这个结果不同的问题还是存在，predict_det.py的时候不加'image_shape': [960, 960]（随意指定），结果识别不出来；随意加个尺寸[960, 960]或者 [736, 1280] ，结果就能正常出来

**Comment by Dandelion111** [comment]
> 非常抱歉，后面会想办法统一下超参数，避免不必要的踩坑

请问大佬解决这个问题了吗？我也遇到了这个情况，自己训练的DBNet模型用官方python预测代码可以检测的很好，模型到处为推理模型之后，用cpp推理却检测不到？好奇怪

**Comment by Dandelion111** [comment]
> PaddleOCR-release-2.0
> 基于det_mv3_db.yml训练车牌检测模型。
> 使用训练完的模型直接测试，infer_det.py，效果很好。
> 然后使用export_model.py对best_accuracy模型进行转换为推理模型（基于训练时的配置表config.yml），得到inference模型，使用predict_det.py做预测。效果没有前者好，检测框不紧密。
> 
> ![F6726907-C310-4b5d-8CEF-EFCC44B193BC](https://user-images.githubusercontent.com/66729924/108827728-ea6cab80-7600-11eb-95f4-c477cd4f060b.png)
> 
> 使用官方的ch_ppocr_mobile_v2.0_det_train进行测试，以及转换后测试效果也不一致。
> 
> 如下保证predict_det.py的效果和infer_det.py一致？
请问大佬解决这个问题了吗？我也遇到了这个情况，自己训练的DBNet模型用官方python预测代码可以检测的很好，模型到处为推理模型之后，用cpp推理却检测不到？好奇怪

**Comment by KrabbeJing** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png)
> 把这一行注释掉，结果就一样了...

兄弟，感恩抱拳了

**Comment by zhangyingying520** [comment]
> 找到问题了，是训练模型和预测模型的预处理不一致导致的，已经提了[PR](https://github.com/PaddlePaddle/PaddleOCR/pull/2091)修复，可以按照PR的内容修改下代码，再试下

你好，能具体说一下怎么改得了吗，我的是训练的模型转为推理后，几乎识别不出来

**Comment by zhangyingying520** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png)
> 把这一行注释掉，结果就一样了...

麻烦问一下，这是哪个文件

**Comment by zhangyingying520** [comment]
> 类似的问题（已解决），在这里记录一下。
> 基于`det_mv3_east.yml`训练的检测模型，训练完成后使用` tools/infer_det.py`测试效果很好，转推理模型后，用
> 
> ```
> python3 tools/infer/predict_det.py --image_dir="./doc/imgs_my_test/" --det_model_dir="inference/det_mv3_east"
> ```
> 
> 做预测，完全没有效果。
> 修改为如下命令（指定了检测算法）后就有效果了：
> 
> ```
> python3 tools/infer/predict_det.py --image_dir="./doc/imgs_my_test/" --det_model_dir="inference/det_mv3_east" --det_algorithm="EAST"
> ```

!python3 tools/infer/predict_det.py --det_model_dir="inference/db_mv3_infer/"   --image_dir="doc/test/TEST084.jpg"  --det_algorithm="DB"
还是不行

**Comment by zhangyingying520** [comment]
> 是预处理不一样，我看了一下你的config文件，应该是和预测的时候一些参数没对应上导致的，train model 在eval的时候
> ![image](https://user-images.githubusercontent.com/26592129/108997885-207e5e00-76db-11eb-9550-283db8be150c.png)
> ![image](https://user-images.githubusercontent.com/26592129/108997902-270cd580-76db-11eb-8bb4-70874a28e89d.png)
> 在tools/infer/predict_det.py预测的时候，先修改下tools/infer/predict_det.py line42 的参数如下，
> ![image](https://user-images.githubusercontent.com/26592129/108998128-69cead80-76db-11eb-8abf-875891227fa4.png)
> 然后预测的时候调整后处理参数和config文件里的超参数一致，
> 
> ```
> python3.7 tools/infer/predict_det.py --det_model_dir=./data/inference/    --image_dir=./car.png  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5
> ```
> 
> 这样得到的box是完全一样的

按照你说的这些设置完成之后，还是检测不到，能给帮忙看看吗

**Comment by YY007H** [comment]
> > 是预处理不一样，我看了一下你的config文件，应该是和预测的时候一些参数没对应上导致的，train model 在eval的时候
> > ![image](https://user-images.githubusercontent.com/26592129/108997885-207e5e00-76db-11eb-9550-283db8be150c.png)
> > ![image](https://user-images.githubusercontent.com/26592129/108997902-270cd580-76db-11eb-8bb4-70874a28e89d.png)
> > 在tools/infer/predict_det.py预测的时候，先修改下tools/infer/predict_det.py line42 的参数如下，
> > ![image](https://user-images.githubusercontent.com/26592129/108998128-69cead80-76db-11eb-8abf-875891227fa4.png)
> > 然后预测的时候调整后处理参数和config文件里的超参数一致，
> > ```
> > python3.7 tools/infer/predict_det.py --det_model_dir=./data/inference/    --image_dir=./car.png  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样得到的box是完全一样的
> 
> 按照你说的这些设置完成之后，还是检测不到，能给帮忙看看吗

你的代码不是最新的吧，切换成最新的代码吧

**Comment by zhangyingying520** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png)
> 把这一行注释掉，结果就一样了...

注释掉了，还是没有效果，崩溃

**Comment by YY007H** [comment]
> > ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png)
> > 把这一行注释掉，结果就一样了...
> 
> 注释掉了，还是没有效果，崩溃

检测不到，还是导出的模型检测和训练的模型检测不一样？

**Comment by zhangyingying520** [comment]
> > > 是预处理不一样，我看了一下你的config文件，应该是和预测的时候一些参数没对应上导致的，train model 在eval的时候
> > > ![image](https://user-images.githubusercontent.com/26592129/108997885-207e5e00-76db-11eb-9550-283db8be150c.png)
> > > ![image](https://user-images.githubusercontent.com/26592129/108997902-270cd580-76db-11eb-8bb4-70874a28e89d.png)
> > > 在tools/infer/predict_det.py预测的时候，先修改下tools/infer/predict_det.py line42 的参数如下，
> > > ![image](https://user-images.githubusercontent.com/26592129/108998128-69cead80-76db-11eb-8abf-875891227fa4.png)
> > > 然后预测的时候调整后处理参数和config文件里的超参数一致，
> > > ```
> > > python3.7 tools/infer/predict_det.py --det_model_dir=./data/inference/    --image_dir=./car.png  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样得到的box是完全一样的
> > 
> > 
> > 按照你说的这些设置完成之后，还是检测不到，能给帮忙看看吗
> 
> 你的代码不是最新的吧，切换成最新的代码吧

已经解决，是推理过程出了问题

**Comment by HaoyuScut** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...

就是这里！

**Comment by Double97828** [comment]
> > ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...
> 
> 就是这里！

我也是这里注释掉了就好了，什么原因呢？因为后面我想用python的那个库来加载我的推理模型，感觉出现了一样的问题，但是在这里我没有办法做注释了

**Comment by yangy996** [comment]
> > > ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...
> > 
> > 
> > 就是这里！
> 
> 我也是这里注释掉了就好了，什么原因呢？因为后面我想用python的那个库来加载我的推理模型，感觉出现了一样的问题，但是在这里我没有办法做注释了

https://blog.csdn.net/YY007H/article/details/125506785

**Comment by Double97828** [comment]
> > > > ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...
> > > 
> > > 
> > > 就是这里！
> > 
> > 
> > 我也是这里注释掉了就好了，什么原因呢？因为后面我想用python的那个库来加载我的推理模型，感觉出现了一样的问题，但是在这里我没有办法做注释了
> 
> https://blog.csdn.net/YY007H/article/details/125506785

我想原因是我用的ch_PP-OCRv3_det_student.yml 他的 DetResizeForTest: null本身就是none，所以我在预测的时候注释掉就对了？
那我在python里
ocr = PaddleOCR(lang="ch",det_model_dir=DET_MODEL_DIR, rec_model_dir=REC_MODEL_DIR,det_max_side_len=？ )这个值我应该填多少

**Comment by 1443244362** [comment]
> > ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...
> 
> 就是这里！

真正的大佬 三年后依然可以帮助到人

**Comment by GreatV** [comment]
这类问题 FAQ 已经写了: https://paddlepaddle.github.io/PaddleOCR/ppocr/model_train/detection.html#5-faq

**Comment by lduojia** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130921985-d73734f5-e621-407d-aae5-b97d2745a21b.png) 把这一行注释掉，结果就一样了...

这个排查了很久，经测有效，特别感谢
