### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.  [TimeInfo: *** Aborted at 1614049874 (unix time) try "date -d @1614049874" if you are using GNU date ***]   [SignalInfo: *** SIGABRT (@0x3e800000501) received by PID 1281 (TID 0x7f0436df8740) from PID 1281 ***]  已放弃(吐核)

### ISSUE THREAD

**Issue by sellinaxmj** [PaddlePaddle/PaddleOCR#2081]
centos7 cpu版本 
$ paddle --version
PaddlePaddle 2.0.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON

PaddleOCR]$ python3 ./tools/infer/predict_det.py --image_dir="./doc/imgs/12.jpg" --det_model_dir="./inference/det_db/"
E0223 17:18:08.118952 20326 analysis_config.cc:78] Please compile with gpu to EnableGpu()
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   void paddle::operators::math::Blas<paddle::platform::CPUDeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const
8   cblas_sgemm
9   sgemm
10  mkl_blas_sgemm
11  mkl_serv_get_num_stripes
12  omp_get_num_procs
13  paddle::framework::SignalHandle(char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1614071888 (unix time) try "date -d @1614071888" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800004f66) received by PID 20326 (TID 0x7f47b3388740) from PID 20326 ***]

PaddleOCR]$ python3 tools/infer/predict_det.py --det_algorithm="EAST" --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/"
E0223 11:11:13.839426  1281 analysis_config.cc:78] Please compile with gpu to EnableGpu()
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   void paddle::operators::math::Blas<paddle::platform::CPUDeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const
8   cblas_sgemm
9   sgemm
10  mkl_blas_sgemm
11  mkl_serv_get_num_stripes
12  omp_get_num_procs
13  paddle::framework::SignalHandle(char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1614049874 (unix time) try "date -d @1614049874" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800000501) received by PID 1281 (TID 0x7f0436df8740) from PID 1281 ***]

已放弃(吐核)

**Comment by LDOUBLEV** [comment]
你用的是自己编译的paddle ？ 
pip install 的paddle也不能用吗

**Comment by suparek** [comment]
> 你用的是自己编译的paddle ？
> pip install 的paddle也不能用吗

不能用啊，我也提了issue，没人理我。。。 #2069

**Comment by sellinaxmj** [comment]
> 你用的是自己编译的paddle ？
> pip install 的paddle也不能用吗

pip 的paddle可以用阿，但到上面tools/infer/predict_det.py 的时候就会报这个错，不知道是哪里出了问题，特来请教下各路大神，求指点

**Comment by sellinaxmj** [comment]
PaddleOCR]$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: True
bld_path: 
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: flexible
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /home/260/anaconda3/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: 
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local: 
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.8
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env}) 
envs_dirs:
  - /home/260/anaconda3/envs
  - /home/260/.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - /home/260/anaconda3/pkgs
  - /home/260/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: /home/260/anaconda3
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: None
solver_ignore_timestamps: False
ssl_verify: True
subdir: linux-64
subdirs:
  - linux-64
  - noarch
target_prefix_override: 
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []

**Comment by LDOUBLEV** [comment]
安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()

如果出现PaddlePaddle is installed successfully!，说明您已成功安装

**Comment by LDOUBLEV** [comment]
我这边的环境没法复现，建议确认下paddle 2.0.0版本是否安装成功

**Comment by sellinaxmj** [comment]
> 安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()
> 
> 如果出现PaddlePaddle is installed successfully!，说明您已成功安装

$ python3
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
WARNING:root:You are using GPU version PaddlePaddle, but there is no GPU detected on your machine. Maybe CUDA devices is not set properly.
 Original Error is Not compiled with CUDA
PaddlePaddle works well on 1 CPU.
W0224 08:13:48.404541 12479 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0224 08:13:48.411198 12479 build_strategy.cc:430] fuse_bn_add_act_pass is only supported on GPU, skipped.
W0224 08:13:48.413651 12479 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
是安装成功的。
而且用mnist 测过，>>> model.evaluate(val_dataset, verbose=0)
{'loss': [2.384186e-07], 'acc': 0.979}
>>> 
您说的这块是没有问题的哈。谢谢

**Comment by sellinaxmj** [comment]
python3 tools/infer/predict_cls.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --cls_model_dir="ch_ppocr_mobile_v2.0_cls_infer"
E0224 08:39:40.478053 13700 analysis_config.cc:78] Please compile with gpu to EnableGpu()
[2021/02/24 08:39:40] root INFO: Predicts of ./doc/imgs_words/ch/word_4.jpg:['0', 0.9999982]
[2021/02/24 08:39:40] root INFO: Total predict time for 1 images, cost: 0.011
(ocr_p) [260245@localhost PaddleOCR]$ python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_2.jpg" --rec_model_dir="ch_ppocr_mobile_v2.0_rec_infer"
E0224 08:39:54.355834 13749 analysis_config.cc:78] Please compile with gpu to EnableGpu()
[2021/02/24 08:39:54] root INFO: Predicts of ./doc/imgs_words/ch/word_2.jpg:('汉阳鹦鹉家居建材市场E区25-26号', 0.98325324)
[2021/02/24 08:39:54] root INFO: Total predict time for 1 images, cost: 0.042
用这个测也是可行的。
但python3 ./tools/infer/predict_det.py --image_dir="./doc/imgs/12.jpg" --det_model_dir="./inference/det_db/"
这类型的就会出现上面那种错误

**Comment by sellinaxmj** [comment]
python版本从3.8降到3.7就可以用了。谢谢 #2069和@LDOUBLEV 两位大兄弟

**Comment by GDL888** [comment]
我用的python3.7.3也报这个错误

**Comment by nguyenvulong** [comment]
I solved it by using `paddlepaddle-gpu==2.3.2` instead of `paddlepaddle-gpu==2.4.2`. You guys may want to give it a try.

**Comment by jiliangqian** [comment]
> 
请问你解决了吗

**Comment by tongtongwyo** [comment]
搞了两天 把python从3.8改3.7终于可以了

**Comment by tongtongwyo** [comment]
> 我用的python3.7.3也报这个错误

我用的3.7.0

**Comment by ChengsongLu** [comment]
把batch size调小试试 --> #48615
