### ISSUE TITLE
模型文件内容缺失

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#2088]
[models_list.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md)
页面下，中文识别模型，ch_ppocr_mobile_v2.0_rec的[训练模型](https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_train.tar)压缩包内文件缺失，只有best_accuracy.pdparams，缺失.pdopt等文件。

**Comment by LDOUBLEV** [comment]
模型文件没有确实，可以再解压一次，或者用tar命令解压

**Comment by simplew2011** [comment]
![image](https://user-images.githubusercontent.com/66729924/109089778-c28a5e80-774c-11eb-98cc-0296b3a69726.png)
确实缺失了，可否更新下。

**Comment by blackhitomi** [comment]
请问问题解决了吗 确实缺少文件
