### ISSUE TITLE
关于生成的LSVT的弱标注数据集

### ISSUE THREAD

**Issue by whuhangzhang** [PaddlePaddle/PaddleOCR#209]
@ZeyuChen @LDOUBLEV 您好，我看到doc中提到使用LSVT弱标注数据集生成中文识别数据，请问下您是使用什么生成代码生成的， 是text_renderer、SynthText、TextRecognitionDataGenerator其中的哪一个呢？

**Comment by dyning** [comment]
LSVT弱标注数据集是实际数据，只不过没有文本的位置信息，只有文本内容信息。

**Comment by MissPenguin** [comment]
生成的中文识别数据是基于LSVT中的全标注数据，目前还没有用到弱标注数据

**Comment by MissPenguin** [comment]
合成工具使用的text_renderer

**Comment by whuhangzhang** [comment]
@MissPenguin 是直接使用全标注的语料生成的么，还是做了一些nlp的变化呀

**Comment by MissPenguin** [comment]
lsvt只用了全标注的语料，此外还用到了rctw的语料，没有用nlp变化
