### ISSUE TITLE
请问推理时predict_systerm.py做端到端识别,如何用多卡做推理？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#2092]

**Comment by littletomatodonkey** [comment]
你好，目前提供的方法还是单卡推理，如果需要多卡推理，建议做数据切分，在不同的卡上启动不同的识别推理任务哈

**Comment by jey07** [comment]
It is a nice addition. Yes, probably u can make those changes n suggest.

**Comment by aishangmaxiaoming** [comment]
> 你好，目前提供的方法还是单卡推理，如果需要多卡推理，建议做数据切分，在不同的卡上启动不同的识别推理任务哈

单卡推理速度还是比较慢，你的意思是做多卡多个服务吗？
