### ISSUE TITLE
请问在线体验OCR使用的哪个文本检测模型？

### ISSUE THREAD

**Issue by viki9492** [PaddlePaddle/PaddleOCR#2096]
https://www.paddlepaddle.org.cn/hub/scene/ocr
请问该网址下使用的是哪个文本检测模型，使用官方提供的多个文本检测模型检测结果均与它不一致

**Comment by littletomatodonkey** [comment]
使用的是服务端检测模型，检测结果不一致是因为后处理超参不太相同，后处理超参我们更新过几次，可能没及时同步到在线体验ocr中
