### ISSUE TITLE
运行时Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Wzh1997** [PaddlePaddle/PaddleOCR#2097]
![image](https://user-images.githubusercontent.com/40290961/108985967-9c24de80-76cc-11eb-9c27-c68c7756724e.png)
安装完第三方库后，进行文档的运行命令测试，出现Illegal instruction (core dumped)的问题

**Comment by littletomatodonkey** [comment]
可以看下你安装paddle的方式哈，可能与avx有关，我在网上也找了类似的问题，可以先重装Paddle，看下是否能够解决这个问题

https://blog.csdn.net/clever_wr/article/details/89057427
https://ai.baidu.com/forum/topic/show/889944

**Comment by Wzh1997** [comment]
@littletomatodonkey 
![image](https://user-images.githubusercontent.com/40290961/109135552-27b47300-7792-11eb-812b-820d6924291e.png)
我是通过这个whl包安装的，安装的时候测试了也是安装成功，然后按文档中的流程往下走
![image](https://user-images.githubusercontent.com/40290961/109135675-4adf2280-7792-11eb-809b-34cf988b7607.png)
来到进行图片预测这里就出现了这个问题，然后再进python里面测试paddlepaddle也显示失败了。

我在在jetson nano的板子上面跑的，jetpack4.4的

![image](https://user-images.githubusercontent.com/40290961/109135984-9bef1680-7792-11eb-9230-d2514c5e687a.png)
我今天也去重新安装了图中这些whl包，但是都不成功

不知道你们有没有关于在jetson nano上成功部署的相关文档呢？

**Comment by Grungeby52** [comment]
You should set 'export OPENBLAS_CORETYPE=ARMV8' in terminal

**Comment by TonyZhang-code** [comment]
有没有人已经解决了该问题呢
