### ISSUE TITLE
how to activate conda env in dockerfile and start the server service. 

### ISSUE THREAD

**Issue by songaiguo** [PaddlePaddle/PaddleOCR#2106]
I would like to  activate conda env in dockerfile and start the server service. Could anyone tell me how to do that. 
The original commond like this 

CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]

if i have my env "my env"

how can i modify the commond.

**Comment by tink2123** [comment]
Activate your Conda environment and execute the command
