### ISSUE TITLE
提一个文本检测训练出现的bug

### ISSUE THREAD

**Issue by abner2015** [PaddlePaddle/PaddleOCR#2107]
使用教程的例子跑文件检测模型，训练的服务器是两张tesla-v100的显卡，当执行
**# 单机单卡训练 mv3_db 模型
python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/**命令的时候是
 **epoch: 4, iter: 96, 'lr': 1e-06, 'total_loss': nan, 'loss_shrink_maps': nan, 'loss_threshold_maps': nan, 'loss_binary_maps': nan, time: 4.454**从头到尾都是nan
而指定一张显卡训练的时候却可以正常训练
# 单机多卡训练，通过 --gpus 参数设置使用的GPU ID
**python3 -m paddle.distributed.launch --gpus '1' tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/**
同样的在cpu下也是正常训练。
总结一句话就是：有两张显卡训练要指定使用一张显卡才可以正常训练，否则两张都使用就是**nan**

**Comment by tink2123** [comment]
把学习率调小一点看看？ 你的batch_size 是多少呢？

**Comment by abner2015** [comment]
试过调学习率，就是跑提供的例子
