### ISSUE TITLE
StyleText风格图像只能是你们提供的那5W里面选吗？我自己场景里的效果非常不好是怎么回事？

### ISSUE THREAD

**Issue by zy86603465** [PaddlePaddle/PaddleOCR#2109]
使用你们提供的风格图像，合成的效果还可以，但使用我自己的风格图像，效果不好，是什么原因呢？
需要用我的风格图像进行训练吗？

**Comment by weisy11** [comment]
大概是什么样的风格图像呢？方便提供一些数据样例吗？

**Comment by zy86603465** [comment]
![101](https://user-images.githubusercontent.com/12467462/109249640-123b5980-7823-11eb-9280-a0bcc87443cb.jpg)
![100](https://user-images.githubusercontent.com/12467462/109249655-1b2c2b00-7823-11eb-8c17-7510153198bc.jpg)
![111](https://user-images.githubusercontent.com/12467462/109249668-20897580-7823-11eb-83fd-34ab5981921b.jpg)
使用这些风格图像，合成的效果不太好，麻烦帮忙看一下是什么原因

**Comment by yuantangliang** [comment]
估计就是这样的，我也遇到的同样的问题
