### ISSUE TITLE
想自己制作1000张数据量的测试集来测试对比paddleocr模型和其他模型的精度

### ISSUE THREAD

**Issue by eveleslie** [PaddlePaddle/PaddleOCR#211]
因为是ocr小白，所以想请问数据标注是用的labelimg一个字一个字的标吗？类似于多分类的标注？以及paddleocr的数据集格式是什么呢

**Comment by dyning** [comment]
数据标注是行粒度，也就是一行文字，对应这行文字的label，https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/recognition.md 文档里面的数据准备有数据格式的详细说明。

**Comment by rockzhan** [comment]
请问如果训练数据包含两行的文字，模型效果会不会变差呢？
像这样的：
![image](https://user-images.githubusercontent.com/19775116/84848752-55cfa800-b086-11ea-9aba-dc80c3756677.png)

**Comment by dyning** [comment]
会变差的，因为不管是CTC损失，还是Attention损失，最后都是针对单个字符进行识别的，需要将两行文字转为一行。

**Comment by rockzhan** [comment]
好的，谢谢

**Comment by ulanbator** [comment]
> 请问如果训练数据包含两行的文字，模型效果会不会变差呢？
> 像这样的：
> ![image](https://user-images.githubusercontent.com/19775116/84848752-55cfa800-b086-11ea-9aba-dc80c3756677.png)

您好，请问您是做类似的双层车牌检测吗，能交流一下吗？

**Comment by pcb9382** [comment]
车牌车牌识别开源项目可以看看这个：https://github.com/pcb9382/PlateRecognition
