### ISSUE TITLE
Improving image pre processing 

### ISSUE THREAD

**Issue by jey07** [PaddlePaddle/PaddleOCR#2111]
I am having documents as printed text( black ink on white paper).
I have seen through method where image normalization is done. Could you point me to function/methods or any suggestion on how could i improve the image pre processing part within paddle OCR ?

**Comment by maplelinfy** [comment]
> I am having documents as printed text( black ink on white paper).
> I have seen through method where image normalization is done. Could you point me to function/methods or any suggestion on how could i improve the image pre processing part within paddle OCR ?

This may be helpful to you, please refer to https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/ppocr/data/det/data_augment.py#L21
