### ISSUE TITLE
垂直场景下的训练数据

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2112]
在之前的回答中看到 ”对于识别任务，需要保证识别字典中每个字符出现在不同场景的行文本图像数目需要大于200张（举例，如果有字典中有5个字，每个字都需要出现在200张图片以上，那么最少要求的图像数量应该在200-1000张之间），这样可以保证基本的识别效果。“
有一个疑问，假如在做发票/身份证/火车票等场景下，字典中的字数可能会上千个，那么我们需要的图像数量需要几万甚至几十万么？还是在现有通用模型的基础上，只需要几百或几千张图像数据进行微调即可？还是需要再生成一批数据做训练？

**Comment by tink2123** [comment]
通用模型中的训练数据中包含了一部分的发票、身份证等场景，可以用你现有的真实数据+合成数据，去做微调。数据量大概几万张就够了。
