### ISSUE TITLE
请问如何可视化DB模型的三个map

### ISSUE THREAD

**Issue by JinMitaka** [PaddlePaddle/PaddleOCR#2113]
请问输出DB模型在自己数据上probability map、threshold map、 approximate binary map的热图

**Comment by LDOUBLEV** [comment]
可以修改这里，https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/tools/infer_det.py#L97

preds是预测结果，格式是：{'maps': paddle.concat([shrink_maps, threshold_maps, binary_maps], axis=1)}

https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/ppocr/modeling/heads/det_db_head.py#L127

**Comment by Dearzxs** [comment]
> 请问输出DB模型在自己数据上probability map、threshold map、 approximate binary map的热图

您好有具体可视化代码吗
