### ISSUE TITLE
DB的box框有最小的限制吗？box后面会支持多边形的训练吗

### ISSUE THREAD

**Issue by Young1993** [PaddlePaddle/PaddleOCR#2114]

**Comment by LDOUBLEV** [comment]
box框有最小限制,https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/ppocr/data/imaug/make_shrink_map.py#L41
后续应该会支持多边形训练，请关注

**Comment by Young1993** [comment]
> box框有最小限制,
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/fa32b9b184528d446a3aea14a750a3912491dfd5/ppocr/data/imaug/make_shrink_map.py#L41
> 
> 
> 后续应该会支持多边形训练，请关注

感谢
