### ISSUE TITLE
服务器端的预测是否支持mkl加速？

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/PaddleOCR#2116]
如题，感谢解答。

**Comment by tink2123** [comment]
支持的，可以参考文档中的相关数据：https://github.com/PaddlePaddle/PaddleOCR/blob/e6a95c3a71dddbfc41fe9786fde0ad153a29ae52/doc/doc_ch/benchmark.md#%E8%AF%84%E4%BC%B0%E6%8C%87%E6%A0%87

**Comment by HongChow** [comment]
> 支持的，可以参考文档中的相关数据：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/benchmark.md

谢谢~
