### ISSUE TITLE
工程文件莫名消失

### ISSUE THREAD

**Issue by EnzoLiang** [PaddlePaddle/PaddleOCR#2117]
我在docker环境下运行的PaddleOCR，利用hubserving部署了识别模型，然而第二天发现下载的PaddleOCR工程消失了好几个文件夹！但是服务仍可访问，有没有类似情况的呀？
![QQ截图20210225183723](https://user-images.githubusercontent.com/27463147/109141493-c217b500-7798-11eb-931e-bfa5cf10d696.png)

**Comment by tink2123** [comment]
消失的是什么呀？很神奇，没有见过。

**Comment by EnzoLiang** [comment]
> 消失的是什么呀？很神奇，没有见过。
右边是原始的，左边是docker用到的，明显少了很多文件夹
![image](https://user-images.githubusercontent.com/27463147/109238068-cfbb5200-780d-11eb-90c4-d50956dc32f6.png)
