### ISSUE TITLE
图像通道问题

### ISSUE THREAD

**Issue by chccc5** [PaddlePaddle/PaddleOCR#2118]
在实际工程应用中C++部署时，相机采集到的图像一般为四通道，PaddleOCR在检测、识别时兼容不好  。会报异常
` det.Run(srcimg, boxes);
 rec.Run(boxes, srcimg, cls);`

**Comment by littletomatodonkey** [comment]
你好，读取四通道数据`cv::imread(img_path, cv::IMREAD_COLOR);`的时候，这种方式读进来仍然是三通道图像，不影响处理，如果你对数据输入做了修改，那么可以加一个判断，四通道图像时，转为三通道即可：`cvCvtColor(&img,img3chan,CV_RGBA2RGB)`
