### ISSUE TITLE
C# 部署问题

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/PaddleOCR#2121]
请问一下Cmake后，修改main.cpp生成dll，DLL怎么能返回识别后字符串和字符串的位置？？？ 
DLL怎么返回std::vector<std::vector<std::string>>ocr_result、std::vector<std::vector<std::vector<int>>> boxes 以供C#调用。
`    std::vector<std::vector<std::vector<int>>> boxes;
    // 检测
    cv::Mat ocrImage;
    ocrImage = det.Run(srcimg, boxes);
    // 识别
    //rec.Run(boxes, srcimg, cls);
    std::vector<std::vector<std::string>>ocr_result;`

我实现的博客 https://blog.csdn.net/ch_ccc/article/details/113857304

**Comment by xialei2821212670** [comment]
你好，我也是遇到这个问题，C#无法接收C++的Vector 结构。

**Comment by chccc5** [comment]
> 你好，我也是遇到这个问题，C#无法接收C++的Vector 结构。

目前考虑用先将vector转化为数组，数组指针的方式传递；可以进行参考一下。

**Comment by xialei2821212670** [comment]
有代码说明？我现在还是没看懂，看了你的博客，看到保留了预测图

**Comment by chccc5** [comment]
> 有代码说明？我现在还是没看懂，看了你的博客，看到保留了预测图

还没完全实现，没贴这一部分代码。

**Comment by xialei2821212670** [comment]
![Uploading image.png…]()

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/109456920-ca236d80-7a94-11eb-83d2-275faffc2295.png)

**Comment by chccc5** [comment]
修改了检测的返回值；

**Comment by neo125874** [comment]
@xialei2821212670 hello, did you solve this problem?

**Comment by neo125874** [comment]
@chccc1994 hi, could you share the relative information? csdn block foreigner to join membership

**Comment by Yuyanze** [comment]
> 请问一下Cmake后，修改main.cpp生成dll，DLL怎么能返回识别后字符串和字符串的位置？？？ DLL怎么返回std::vector<std::vectorstd::string>ocr_result、std::vector<std::vector<std::vector>> boxes 以供C#调用。 ` std::vector<std::vector<std::vector<int>>> boxes; // 检测 cv::Mat ocrImage; ocrImage = det.Run(srcimg, boxes); // 识别 //rec.Run(boxes, srcimg, cls); std::vector<std::vector<std::string>>ocr_result;`
> 
> 我实现的博客 https://blog.csdn.net/ch_ccc/article/details/113857304



> 请问一下Cmake后，修改main.cpp生成dll，DLL怎么能返回识别后字符串和字符串的位置？？？ DLL怎么返回std::vector<std::vectorstd::string>ocr_result、std::vector<std::vector<std::vector>> boxes 以供C#调用。 ` std::vector<std::vector<std::vector<int>>> boxes; // 检测 cv::Mat ocrImage; ocrImage = det.Run(srcimg, boxes); // 识别 //rec.Run(boxes, srcimg, cls); std::vector<std::vector<std::string>>ocr_result;`
> 
> 我实现的博客 https://blog.csdn.net/ch_ccc/article/details/113857304

看了你的博客深受启发，不知道你遇到过大量图片预测的这个问题没有，具体如下：
基本问题是这样的：C#每次传一张图片给我，然后C#每次需要调用我这里的PaddleOCR dll，输出结果放回C#。但模型的加载每次都在我这里进行，每次图片过来之后我都需要多花费700ms加载OCR 的三个模型，之后才调用识别图片，在这种场景下如何只加载模型一次呢？大家有遇到过类似的问题吗？另外我的PaddleOCR dll只能在子线程中调用，不能在主线程中调用，如果将模型加载变量设置为全局变量的话运行第二张图片时会失败
