### ISSUE TITLE
C++ linux按照官网编译错误

### ISSUE THREAD

**Issue by chuanfuye** [PaddlePaddle/PaddleOCR#2122]
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3 (found version "3.4.7") 
cmake cxx flags -g -o3 -fopenmp -std=c++11
cp: cannot stat '/home/wt_yechuanfu/anaconda3/envs/wt_ocr/lib/python3.7/site-packages/paddle/third_party/install/mklml/lib/libmklml_intel.so': No such file or directory
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.19)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:207 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "ocr_system" links to some libraries for which the linker
  must search:

    glog, gflags, protobuf, z, xxhash, -ldl -lrt -lgomp -lz -lm -lpthread, dl
    m, pthread, rt

  and other libraries with known full path:

    /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3/lib64/libopencv_calib3d.a
    /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3/share/OpenCV/3rdparty/lib64/liblibprotobuf.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_TENSORRT

-- Build files have been written to: /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
make[2]: *** No rule to make target '/home/wt_yechuanfu/anaconda3/envs/wt_ocr/lib/python3.7/site-packages/paddle/paddle/lib/libpaddle_fluid.so', needed by 'ocr_system'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_cls.cpp:15:0:
/home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_cls.h:18:10: fatal error: paddle_api.h: No such file or directory
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
compilation terminated.
In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_det.cpp:15:0:
/home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_det.h:20:10: fatal error: paddle_api.h: No such file or directory
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
compilation terminated.
/home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/preprocess_op.cpp:18:10: fatal error: paddle_api.h: No such file or directory
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/ocr_system.dir/build.make:120: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_cls.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_cls.o] Error 1
CMakeFiles/ocr_system.dir/build.make:133: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_det.o' failed
In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_rec.cpp:15:0:
/home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_rec.h:18:10: fatal error: paddle_api.h: No such file or directory
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_det.o] Error 1
compilation terminated.
CMakeFiles/ocr_system.dir/build.make:172: recipe for target 'CMakeFiles/ocr_system.dir/src/preprocess_op.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/preprocess_op.o] Error 1
CMakeFiles/ocr_system.dir/build.make:146: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_rec.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_rec.o] Error 1
In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/main.cpp:31:0:
/home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_det.h:20:10: fatal error: paddle_api.h: No such file or directory
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/ocr_system.dir/build.make:107: recipe for target 'CMakeFiles/ocr_system.dir/src/main.o' failed
make[2]: *** [CMakeFiles/ocr_system.dir/src/main.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 
按照官方文档操作，执行到
cd cpp_infer目录下
执行sh tools/build.h，报上述错误，请问应该修改哪里呢，感谢

**Comment by HongChow** [comment]
the same as yours

**Comment by HongChow** [comment]
> -- The CXX compiler identification is GNU 7.5.0
> -- The C compiler identification is GNU 7.5.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Found OpenCV: /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3 (found version "3.4.7")
> cmake cxx flags -g -o3 -fopenmp -std=c++11
> cp: cannot stat '/home/wt_yechuanfu/anaconda3/envs/wt_ocr/lib/python3.7/site-packages/paddle/third_party/install/mklml/lib/libmklml_intel.so': No such file or directory
> CMake Warning (dev) in CMakeLists.txt:
> No cmake_minimum_required command is present. A line of code such as
> 
> ```
> cmake_minimum_required(VERSION 3.19)
> ```
> 
> should be added at the top of the file. The version specified may be lower
> if you wish to support older CMake versions for this project. For more
> information run "cmake --help-policy CMP0000".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Configuring done
> CMake Warning (dev) at CMakeLists.txt:207 (add_executable):
> Policy CMP0003 should be set before this line. Add code such as
> 
> ```
> if(COMMAND cmake_policy)
>   cmake_policy(SET CMP0003 NEW)
> endif(COMMAND cmake_policy)
> ```
> 
> as early as possible but after the most recent call to
> cmake_minimum_required or cmake_policy(VERSION). This warning appears
> because target "ocr_system" links to some libraries for which the linker
> must search:
> 
> ```
> glog, gflags, protobuf, z, xxhash, -ldl -lrt -lgomp -lz -lm -lpthread, dl
> m, pthread, rt
> ```
> 
> and other libraries with known full path:
> 
> ```
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3/lib64/libopencv_calib3d.a
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/opencv-3.4.7/opencv3/share/OpenCV/3rdparty/lib64/liblibprotobuf.a
> ```
> 
> CMake is adding directories in the second list to the linker search path in
> case they are needed to find libraries from the first list (for backwards
> compatibility with CMake 2.4). Set policy CMP0003 to OLD or NEW to enable
> or disable this behavior explicitly. Run "cmake --help-policy CMP0003" for
> more information.
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Generating done
> CMake Warning:
> Manually-specified variables were not used by the project:
> 
> ```
> USE_TENSORRT
> ```
> 
> -- Build files have been written to: /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/build
> Scanning dependencies of target ocr_system
> make[2]: *** No rule to make target '/home/wt_yechuanfu/anaconda3/envs/wt_ocr/lib/python3.7/site-packages/paddle/paddle/lib/libpaddle_fluid.so', needed by 'ocr_system'. Stop.
> make[2]: *** Waiting for unfinished jobs....
> [ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
> [ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
> [ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
> [ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
> [ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
> [ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
> [ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
> [ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
> [ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
> In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_cls.cpp:15:0:
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_cls.h:18:10: fatal error: paddle_api.h: No such file or directory
> #include "paddle_api.h"
> ^~~~~~~~~~~~~~
> compilation terminated.
> In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_det.cpp:15:0:
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_det.h:20:10: fatal error: paddle_api.h: No such file or directory
> #include "paddle_api.h"
> ^~~~~~~~~~~~~~
> compilation terminated.
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/preprocess_op.cpp:18:10: fatal error: paddle_api.h: No such file or directory
> #include "paddle_api.h"
> ^~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/ocr_system.dir/build.make:120: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_cls.o' failed
> make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_cls.o] Error 1
> CMakeFiles/ocr_system.dir/build.make:133: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_det.o' failed
> In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/ocr_rec.cpp:15:0:
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_rec.h:18:10: fatal error: paddle_api.h: No such file or directory
> #include "paddle_api.h"
> ^~~~~~~~~~~~~~
> make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_det.o] Error 1
> compilation terminated.
> CMakeFiles/ocr_system.dir/build.make:172: recipe for target 'CMakeFiles/ocr_system.dir/src/preprocess_op.o' failed
> make[2]: *** [CMakeFiles/ocr_system.dir/src/preprocess_op.o] Error 1
> CMakeFiles/ocr_system.dir/build.make:146: recipe for target 'CMakeFiles/ocr_system.dir/src/ocr_rec.o' failed
> make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_rec.o] Error 1
> In file included from /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/src/main.cpp:31:0:
> /home/wt_yechuanfu/ceshi_code/Paddle-2.0.0/deploy/cpp_infer/include/ocr_det.h:20:10: fatal error: paddle_api.h: No such file or directory
> #include "paddle_api.h"
> ^~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/ocr_system.dir/build.make:107: recipe for target 'CMakeFiles/ocr_system.dir/src/main.o' failed
> make[2]: *** [CMakeFiles/ocr_system.dir/src/main.o] Error 1
> CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
> make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
> Makefile:102: recipe for target 'all' failed
> make: *** [all] Error
> 按照官方文档操作，执行到
> cd cpp_infer目录下
> 执行sh tools/build.h，报上述错误，请问应该修改哪里呢，感谢

I know the reason : you maybe added the wrong Paddle Inference Lib path error ?
In "sh tools/build.h" change the LIB_DIR from "paddle_inference_c_install_dir"  to  "paddle_inference_install_dir"
