### ISSUE TITLE
IOS 上部署, 使用EAST算法問題

### ISSUE THREAD

**Issue by kwan96** [PaddlePaddle/PaddleOCR#2124]
测试的图像: 倾斜的文字
结果: 测试效果甚差(相对DB算法), 几乎侦测不出来, 而使用python script跑EAST算法则问题不大
备注: 不是后处理的问题, 已经有用C++实现了EAST算法(output: text_rec_quad)的后处理, 问题是score map几乎完全难以通过score threshold(0.2), 应该就是侦测不出来。

使用EAST的原因: EAST支援多边形， 后处理的转正效果要比DB要好得多。
请问是不推荐在端侧使用EAST吗？

**Comment by LDOUBLEV** [comment]
目前不推荐端侧使用EAST

**Comment by kwan96** [comment]
谢谢回复~
