### ISSUE TITLE
请问朋友们试过使用paddle2onnx转换检测和识别模型为onnx，我尝试了一下没有成功，项目训练和预测功能都是正常能运行的，转换为onnx时报错

### ISSUE THREAD

**Issue by 2017ZYS** [PaddlePaddle/PaddleOCR#213]

**Comment by 2017ZYS** [comment]
![20200616100301](https://user-images.githubusercontent.com/31603272/84723616-99f47700-afb8-11ea-9b38-95be35b30199.png)

**Comment by jiangjiajun** [comment]
你好，请问你转的是检测模型还是识别模型, 目前已支持检测，转换方式如下  
##1.安装X2Paddle 
```
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```

##2.转换模型
```
x2paddle -f paddle2onnx -m infer_ocr_model -s ./output
```
**需要注意的是，传入的infer_ocr_model即paddle模型目录，里面需要包括__model__和__params__两个文件（目前PaddleOCR下载下来的inference模型包含的是model和params两个文件，需要手动重命名）

**Comment by 2017ZYS** [comment]
感谢，目前试了下检测模型的转换，成功了，但是识别模型转换失败了，希望后期能支持识别的转换
![20200618152542](https://user-images.githubusercontent.com/31603272/84990641-049fe100-b178-11ea-8164-82a866c2328e.jpg)

**Comment by an1018** [comment]
@2017ZYS 你好，能分享下onnx模型的测试代码吗
