### ISSUE TITLE
请问一下：OCR识别完成后的结果如何结构化多行的问题？

### ISSUE THREAD

**Issue by hjb-huang** [PaddlePaddle/PaddleOCR#2130]
比如需要结构化为：{品牌：XXX，主要成分：XXXX，主要功能：XXX}

多行的问题是按场景坐标处理吗？还是需要用NLP再处理？谢谢！

![11_det](https://user-images.githubusercontent.com/63033529/109290268-5ac63780-7862-11eb-819e-b0b8eb4a1d93.jpg)

**Comment by KyrieHee** [comment]
将输出结果的每个字段拆出来,组成json就可以.
