### ISSUE TITLE
模型训练异常

### ISSUE THREAD

**Issue by liyi002** [PaddlePaddle/PaddleOCR#2131]
训练时抛这个异常：
在program.py  -- train里面  192行 for idx, batch in enumerate(train_dataloader)
(<class 'RuntimeError'>, RuntimeError('DataLoader 8 workers exit unexpectedly, pids: 5807, 5808, 5811, 5817, 5822, 5827, 5834, 5839',), <traceback object at 0x7f953346bc48>)

**Comment by ioracion** [comment]
同问，本地跑train.py做微调时没问题，但在AiStudio环境上跑就报这个错（文件夹结构、配置文件都一样），难道是python版本问题？（本地3.8，aistudio上3.7）
