### ISSUE TITLE
基于Python预测引擎推理下载解压识别模型，疑似缺少文件。

### ISSUE THREAD

**Issue by wangherr** [PaddlePaddle/PaddleOCR#2133]
“文档教程/预测部署/基于Python预测引擎推理/一、训练模型转inference模型/识别模型转inference模型”

下载超轻量中文识别模型：
`wget -P ./ch_lite/ https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_train.tar && tar xf ./ch_lite/ch_ppocr_mobile_v2.0_rec_train.tar -C ./ch_lite/`

但解压结果只有一个文件best_accuracy.pdparams，而没有pdopt和pdparams文件。

**Comment by Sest0** [comment]
解压出来的那个文件后面加个.tar的后缀，再次解压就正常了。或者用tar命令解压
