### ISSUE TITLE
使用GPU推理或者训练时自动杀死进程，事件查看器中报错

### ISSUE THREAD

**Issue by CactusSeed2020** [PaddlePaddle/PaddleOCR#2135]
使用GPU推理或者训练时自动杀死进程，无报错；使用CPU时正常，附图
![error](https://user-images.githubusercontent.com/79742127/109381739-1052c280-7917-11eb-81f1-f2014a5a5788.png)

**Comment by CactusSeed2020** [comment]
![image](https://user-images.githubusercontent.com/79742127/109385633-3c2e7200-7930-11eb-9883-0c7d1b3a09f0.png)
又发现即使使用CPU训练时，模型评估完成后进程也会被自动杀死，无报错，任务管理器显示“已挂起”

**Comment by oujunke** [comment]
我也是  训练着会莫名关闭
![Uploading Snipaste_2021-03-01_09-56-16.png…]()

**Comment by oujunke** [comment]
我也是 训练着会莫名关闭
![Snipaste_2021-03-01_09-56-16](https://user-images.githubusercontent.com/26790160/109443065-93d5f600-7a74-11eb-8adc-f148de73c7e9.png)

**Comment by oujunke** [comment]
事件查看器里面有以下错误:
错误应用程序名称: python.exe，版本: 3.7.8150.1013，时间戳: 0x5ef85af9
错误模块名称: MSVCP140.dll，版本: 14.28.29334.0，时间戳: 0x5fa9a827
异常代码: 0xc0000005
错误偏移量: 0x00000000000026ae
错误进程 ID: 0x1f68
错误应用程序启动时间: 0x01d70e3df4ce8567
错误应用程序路径: C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe
错误模块路径: C:\Windows\SYSTEM32\MSVCP140.dll
报告 ID: 38c51301-6ed3-495b-840c-2be31c7ffaa1
错误程序包全名: 
错误程序包相对应用程序 ID:
