### ISSUE TITLE
C++源码编译，运行错误

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/PaddleOCR#2136]
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 2.0
det_model_dir : ./inference/ch_ppocr_mobile_v2.0_det_infer/
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/ch_ppocr_mobile_v2.0_rec_infer/
use_angle_cls : 0
use_gpu : 0
use_mkldnn : 0
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareExecutor()
4   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
5   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
6   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
7   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, paddle::framework::AttributeMap, bool)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
Error: Operator rnn has not been registered
  [Hint: op_info_ptr should not be null.] (at /Data/PJTs/OCR/Paddle/Paddle/paddle/fluid/framework/op_info.h:140)

Aborted (core dumped)

环境： 
(1)OS: Ubuntu 18.04.5 LTS 
(2) cpu: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8 
(3)GUN: cmake version 3.10.2 gcc (GCC) 7.5.0
(4)PaddlePaddle: release/2.0-beta
(5)PaddleOCR: release/2.0 or release/2.0-rc1
期待和感谢回复

**Comment by HongChow** [comment]
还有个问题是有时候好像编不出 libpaddle_fluid.so

**Comment by littletomatodonkey** [comment]
你好
1. OCR的话，建议使用`release/2.0`分支哈
2. Paddle的话，建议使用2.0的预测库
