### ISSUE TITLE
[提问]是否可以使用Paddle.js运行本项目的模型？

### ISSUE THREAD

**Issue by dinfer** [PaddlePaddle/PaddleOCR#2141]
是否可以使用Paddle.js运行本项目的模型？有没有相关示例及资料可供参考？

**Comment by littletomatodonkey** [comment]
你好，目前还不支持，js中对于ocr中部分ocr算子还不支持

**Comment by QianLingjun** [comment]
请问，现在可以实现js ocr的预测了吗？目前我遇到了一个关键js OCR转换过程中的问题，如下：

我遇到一个问题，就是官方提供了OCR js检测的案例，但是没有识别的案例（https://github.com/PaddlePaddle/Paddle.js）。我用官方提供的模型，在Linux上是可以完成OCR全过程的，在OCR js的案例，也是可以在网页上预测的。但是，我用官方的模型，和代码，转换到js版本的model和。dat文件后，无法识别。其中model没有问题，.dat其中的二进制数字不一致。请问这种是什么问题呢？谢谢
