### ISSUE TITLE
生产环境下的模型更新

### ISSUE THREAD

**Issue by wanghaisheng** [PaddlePaddle/PaddleOCR#2143]
请问有最佳实践吗
还是说要人工操作

**Comment by littletomatodonkey** [comment]
你好
1. 人工操作的话，可以把
2. 如果希望自动更新的话，可以使用一些自动化工具，定时保存模型、导出inference model，重启服务，这块的代码，目前repo中还没有现成的代码，不过可以尝试使用`Linux Crontab`工具包
