### ISSUE TITLE
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#2144]
cudnn版本7.6.4
cuda版本10.0.130

**Comment by littletomatodonkey** [comment]
建议升级下显卡驱动

**Comment by wfdubowen** [comment]
安装CUDA10.0对应版本也可以试试：
python -m pip install paddlepaddle-gpu==2.0.0.post100 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
