### ISSUE TITLE
做身份证信息提取，数据如何标注比较好呢

### ISSUE THREAD

**Issue by maplelinfy** [PaddlePaddle/PaddleOCR#2145]
例如第一行“姓名   张三”，可以有三种标注方法：
1 “姓名张三”（一行文字统一标出来）
2. “姓名”，“张三”（空格较大的就分开标）
3. “张三”（只标需要的信息）
有经验的大佬们，请问哪种方式检测效果会最好呢

**Comment by littletomatodonkey** [comment]
建议是第二张标注方法，学习起来容易一些

**Comment by maplelinfy** [comment]
> 建议是第二张标注方法，学习起来容易一些

非常感谢~

**Comment by xialei2821212670** [comment]
你好，问下第二种效果是否高效，我还是按照行进行处理的

**Comment by Essence9999** [comment]
> 例如第一行“姓名 张三”，可以有三种标注方法： 1 “姓名张三”（一行文字统一标出来） 2. “姓名”，“张三”（空格较大的就分开标） 3. “张三”（只标需要的信息） 有经验的大佬们，请问哪种方式检测效果会最好呢

你现在的身份证识别效果咋样？

**Comment by Essence9999** [comment]
> 你好，问下第二种效果是否高效，我还是按照行进行处理的

你现在的身份证识别效果咋样？

**Comment by xialei2821212670** [comment]
> > 你好，问下一个效果是否有效，我还是按照行处理的
> 
> 你现在的身份识别效果咋样？

测试数据比较规范，效果还行
