### ISSUE TITLE
微调识别模型初始准确率是从0开始的合理吗？

### ISSUE THREAD

**Issue by kingwpf** [PaddlePaddle/PaddleOCR#2146]
pretrain_weights是ch_ppocr_server_v1.1_rec_pre，
![image](https://user-images.githubusercontent.com/10610290/109475352-922a2380-7ab0-11eb-8800-ca2fc133491d.png)

**Comment by kingwpf** [comment]
我理解的微调是这个预训练的模型应该可以识别对部分图片的，但是感觉这个微调像是从新训练了一样

**Comment by littletomatodonkey** [comment]
你好
1. 可以看下是否正常加载pretrained model了
2. 如果字典文件修改了的话，finetune的时候不会加载fc，acc是0也是正常的

**Comment by kingwpf** [comment]
> 你好
> 
> 1. 可以看下是否正常加载pretrained model了
> 2. 如果字典文件修改了的话，finetune的时候不会加载fc，acc是0也是正常的

你好，感谢你的回复！
我微调模型用的字典和“configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml”里面的字典是同一个，路径是“ppocr/utils/ppocr_keys_v1.txt”，请问预训练的v1.1模型是使用的这个字典吗？

模型加载部分我看到了“Finish initing model from xxx”，但是上面有两个Warning，ctc有两个参数没有加载进来，两个Warning分别是：（1）“WARNING: variable ctc_fc_b_attr not used”， （2）”WARNING: variable ctc_fc_w_attr not used“。 请问是这两个参数没加载进来导致的吗？
