### ISSUE TITLE
C++部署代码运行错误

### ISSUE THREAD

**Issue by syyxsxx** [PaddlePaddle/PaddleOCR#2147]
系统:linux 16.04 gcc 4.8
PaddleOCR:release/2.0 版本
Paddle预测库：从官网下载的2.0rc cpu mkldnn预编译库(manylinux_cpu_avx_mkl_gcc482)
代码可以编译成功，但运行的时候报找不到rnn op
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareExecutor()
5   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
6   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
7   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
8   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, paddle::framework::AttributeMap, bool)
9   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator (rnn) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:151)

**Comment by LDOUBLEV** [comment]
试一下2.0版本的预测库，不是2.0rc版本

**Comment by syyxsxx** [comment]
> 试一下2.0版本的预测库，不是2.0rc版本

2.0可以的，多谢
