### ISSUE TITLE
文字识别这两个模型有什么区别么

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#2148]
文字识别文档当中 给出的预训练模型是这个
https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar

我看这个模型不在模型列表当中
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md

rec_mv3_none_bilstm_ctc_v2.0_train 这个是基于中文的 还是英文训练的呢

**Comment by littletomatodonkey** [comment]
你好
1. https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar 这个是基于lmdb数据集训练的
2. https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md 这个上面的列表都是ppocr系列的模型，是我们在中英文数据集上训练的
3. 实际使用中，建议使用model list.md中的模型
