### ISSUE TITLE
英文识别模型是基于什么数据集训练得到的

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#2151]
模型列表当中， 英文识别是基于什么数据集训练得到的呢
![Screenshot from 2021-03-02 10-21-37](https://user-images.githubusercontent.com/3166070/109586994-44a9c700-7b41-11eb-8c32-45828d504d08.png)
模型列表
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md

**Comment by tink2123** [comment]
英文数字的训练数据全部来自于合成数据，包括 synth90K 和 使用部分语料合成了英文文档图片。
