### ISSUE TITLE
docker部署时端口不一致

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2154]
使用docker部署时，dockerfile里的EXPOSE是8868，但最后部署成功后要访问的端口是8866，请问这是为什么？
![image](https://user-images.githubusercontent.com/13652569/109612664-0aedb600-7b6b-11eb-8c95-c859598cc1fd.png)

**Comment by WenmuZhou** [comment]
将-dp 后面改为8868:8866试试
