### ISSUE TITLE
文字方向模型数据集相关

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#2155]
请问一下 paddleocr里面开源的文字方向模型  使用的数据集是 https://github.com/YCG09/chinese_ocr 训练的吗  如果是的  那如果检测框里面字符大于10个   模型里面会自动截取10个预测是吗             如果不是训练文字方向的数据集请问在哪里能找到

**Comment by littletomatodonkey** [comment]
数据集是合成+真实数据，真实数据就是开源的数据，你旋转180度，就得到了180度的训练图片，合成数据同理

**Comment by wa3926** [comment]
明白了 谢谢你
