### ISSUE TITLE
KeyError: 'LinearWarmup_LR'

### ISSUE THREAD

**Issue by lircstar** [PaddlePaddle/PaddleOCR#2158]
训练检测网络的时候
![image](https://user-images.githubusercontent.com/28331873/109642440-f0790400-7b8d-11eb-98e6-39fcee0e9afb.png)
![image](https://user-images.githubusercontent.com/28331873/109642485-01297a00-7b8e-11eb-9475-381b867aa855.png)
![image](https://user-images.githubusercontent.com/28331873/109642501-07b7f180-7b8e-11eb-8a8e-fbd1b23cb686.png)
在save_load.py的init_model时候，提示标题的错误，是我装的paddle的版本问题？还是yaml文件需要配置哪里呢？

**Comment by clive1158** [comment]
1、checkpoints设置的模型路径有误
2、模型有问题

**Comment by lircstar** [comment]
不是从https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.0/doc/doc_ch下载
吗？
但是我看帮助文档是用的
wget -P ./pretrain_models/ https://paddle-imagenet-models-name.bj.bcebos.com/ResNet18_vd_pretrained.tar
或者其他两个模型。

我用上面的不对吗？上面的设置checkpoints？能详细解释下吗？

**Comment by weisy11** [comment]
这里有两个不同的概念：
pretrained_model：指预训练模型，例如使用的imagenet的模型。这时会load预训练模型的参数，但并不会load学习率、优化器以及训练状态等。
checkpoints：指之前训练的中间结果，例如前一次训练到了100个epoch，想接着训练。这时会load尝试所有信息，包括模型的参数，之前的状态等。
你这里应该使用pretrained_model而不是checkpoints

**Comment by ymzx** [comment]
> 训练检测网络的时候
> ![image](https://user-images.githubusercontent.com/28331873/109642440-f0790400-7b8d-11eb-98e6-39fcee0e9afb.png)
> ![image](https://user-images.githubusercontent.com/28331873/109642485-01297a00-7b8e-11eb-9475-381b867aa855.png)
> ![image](https://user-images.githubusercontent.com/28331873/109642501-07b7f180-7b8e-11eb-8a8e-fbd1b23cb686.png)
> 在save_load.py的init_model时候，提示标题的错误，是我装的paddle的版本问题？还是yaml文件需要配置哪里呢？

同志，请问这个问题进展如何了？解决了？如何解决的？这个是paddle本身缺陷？

**Comment by smolendawid** [comment]
In my case using `pretrained_model` and not `checkpoint` helped, as mentioned above
