### ISSUE TITLE
自己训练的模型做印刷体识别，对特殊字符效果不好

### ISSUE THREAD

**Issue by llwowowowoll** [PaddlePaddle/PaddleOCR#2159]
印刷体识别时，对特殊字符效果不好（标点 空格 特殊字体）。
用PaddleOCR提供的预测模型，对特殊字符效果更佳。

我只训练了识别模型，训练集约400w，训练集中的特殊字符数量确实比较少，大部分都是文字。
模型的配置文件，选择的是 rec_chinese_common_train_v1.1.yml

**Comment by llwowowowoll** [comment]
这个有什么解决方法吗？特殊字符的训练集很难获取到啊

**Comment by zcswdt** [comment]
> 这个有什么解决方法吗？特殊字符的训练集很难获取到啊

可以生成啊，
