### ISSUE TITLE
Learning rate无法调整

### ISSUE THREAD

**Issue by sidongfeng** [PaddlePaddle/PaddleOCR#216]
加载checkpoint以后，learning rate设置无效。

运行指令（其余都未更改）：
![image](https://user-images.githubusercontent.com/37397706/84755618-6a636000-aff4-11ea-81ed-1a5789e364b7.png)

![image](https://user-images.githubusercontent.com/37397706/84755755-8f57d300-aff4-11ea-98cf-21e821fb2c39.png)

训练：
![image](https://user-images.githubusercontent.com/37397706/84755553-56b7f980-aff4-11ea-9f93-dca7d129bd88.png)

**Comment by LDOUBLEV** [comment]
按照这样调整试试：
```
pretrain_weights: ./det_r50_vd_east/best_accuracy
checkpoints: 
```

**Comment by sidongfeng** [comment]
感谢，可以用了，但想知道一下这里的checkpoints代表的是什么？

**Comment by LDOUBLEV** [comment]
> 感谢，可以用了，但想知道一下这里的checkpoints代表的是什么？
表示 加载模型参数路径，doc/doc_ch/config.md中有提到
![image](https://user-images.githubusercontent.com/26592129/84847080-d55b7800-b082-11ea-8b12-c39ea2ed0858.png)
