### ISSUE TITLE
paddleOCR里面的android_demo程序问题请教

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleOCR#2161]
paddleOCR里面的android_demo程序，里面的OCRPredictorNative.Config config 没有c++接口config诸如 
det_db_box_thresh  0.5 
det_db_unclip_ratio  1.6
之类的配置，还是说android端不需要这些配置了？
还有就是把"ch_rec_mv3_crnn_opt.nb"替换为支持空格的nb模型，好像也不行。支持空格的nb模型是通过opt从ch_rec_r34_vd_crnn_enhance转换过来的。请问如果android demo想要支持空格的识别，请问怎么处理？谢谢。

**Comment by WenmuZhou** [comment]
这两个参数都在代码里写死了，在这个文件夹内，可以手动修改https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/android_demo/app/src/main/cpp/ocr_db_post_process.cpp

**Comment by mybrew** [comment]
谢谢你的回复

> 这两个参数都在代码里写死了，在这个文件夹内，可以手动修改https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/android_demo/app/src/main/cpp/ocr_db_post_process.cpp
