### ISSUE TITLE
mv3+db文字检测,推理模型无效果

### ISSUE THREAD

**Issue by ChungTak** [PaddlePaddle/PaddleOCR#2162]
1、PaddleOCR版本： gitee最新版本 2021-02-23  
      运行操作系统 Ubuntu 20.04
      paddlepaddle 2.0
      python3.7
2、问题描述：
mv3+db 训练文字检测，使用tools/infer_det.py 效果很好.
export_model 导出模型后，使用tools/infer/predict_det.py 完全没效果，输出的是原图没任何标注。
训练和推理效果不一致问题，旧issue上有解决的办法，我按照修改也没有效果，det_db_thresh=0.3  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5参数与配置文件一致。 DetResizeForTest的image_shape 也注释掉了
3、测试步骤：
训练模型预测命令
```
python3.7 PaddleOCR/tools/infer_det.py -c det_mv3_db.yml -o Global.infer_img="./car1.jpeg" Global.pretrained_model="./output/db_mv3/best_accuracy" Global.load_static_weights=false PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5 Global.use_gpu=False
```
Image saved in ./output/det_db/det_results/car1.jpeg
输出效果正确：
![car1](https://user-images.githubusercontent.com/778353/109743693-1644ee00-7c0c-11eb-9d05-33fae4858331.jpeg)

导出模型,进行推理
```
python3.7 PaddleOCR/tools/export_model.py -c det_mv3_db.yml  -o Global.pretrained_model=./output/db_mv3/best_accuracy Global.load_static_weights=False Global.save_inference_dir=./inference/det_db/
python3.7 PaddleOCR/tools/infer/predict_det.py --image_dir="./car1.jpeg" --det_model_dir="./inference/det_db/"  --det_db_thresh=0.3  --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5 --use_gpu=False

```
Image saved in ./output/det_db/det_results/car1.jpeg
输出没有标注，识别不出来
![det_res_car1](https://user-images.githubusercontent.com/778353/109743852-52784e80-7c0c-11eb-8269-55a5c9e5913f.jpeg)

4、附件 模型文件、测试图片和训练配置
[det_mv3_db_test.tar.gz](https://github.com/PaddlePaddle/PaddleOCR/files/6073280/det_mv3_db_test.tar.gz)

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/109774254-1b6d6180-7c3b-11eb-8a0c-8969e071b31f.png)
这是我用你的模型和命令跑的

**Comment by ChungTak** [comment]
> 这是我用你的模型和命令跑的

奇怪了,为何我折腾了一天都出不来结果` ` `` ``请问你的操作系统是什么版本？  但是训练模型就可以`` ` 想不通 是那里影响

**Comment by WenmuZhou** [comment]
我的是macos ,py38

**Comment by littletomatodonkey** [comment]
你的模型是不是不正确，需要下载动态图的模型

**Comment by ChungTak** [comment]
> 你的模型是不是不正确，需要下载动态图的模型

我是新手不太懂～～～按着 官方文本检测教程,教程里只有这个mv3+db预训练模型  [MobileNetV3_large_x0_5_pretrained.tar](https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV3_large_x0_5_pretrained.tar)

请教一下，你说的mv3+db动态图的模型在那里下载？怎样判断，什么情况下需要用动态图的模型，什么情况用静态图模型。谢谢～～

**Comment by LDOUBLEV** [comment]
动态图模型下载：https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-20-series-model-listupdate-on-dec-15

**Comment by ChungTak** [comment]
换了这个训练模型可以了～～谢谢大家
