### ISSUE TITLE
有什么提高垂直文本检测效果的方法么？

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#2165]
我在做身份证文本检测 水平的文本检测效果已经很好了 但是垂直的身份正基本上检测不出来文本 有什么需要配置的地方名 可以提升检测效果 我现在有很多水平身份正的标注数据 但是垂直的没有 需要标注更多的数据名 还是说有什么数据增强办法呢

**Comment by littletomatodonkey** [comment]
这块建议还是标注更多的垂直文本训练样本，或者合成一些包含垂直文本的图片。

**Comment by mymagicpower** [comment]
把垂直的身份证旋转一下不就解决了。

**Comment by fengmy** [comment]
垂直的、各种角度的，做个模型校正一下就可以了，detection+kp
