### ISSUE TITLE
请问一下这个预训练模型在哪下载，太长时间没用我记得以前没有这个啊。

### ISSUE THREAD

**Issue by huabao97** [PaddlePaddle/PaddleOCR#2166]
![image](https://user-images.githubusercontent.com/69790778/109819126-b16eaf80-7c6e-11eb-9623-d026f5131f10.png)

ValueError: Model pretrain path ./pretrain_models/MobileNetV3_large_x0_5_pretrained/ does not exists.

**Comment by MissPenguin** [comment]
您好，预训练模型来自PaddleClas模型库，上面这个模型可以用如下命令下载：wget -P ./pretrain_models/ https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV3_large_x0_5_pretrained.tar
