### ISSUE TITLE
onnxruntime1.7.0 windows x64，不能加载ch_ppocr_mobile_v2.0_rec_pre转的onnx模型 

### ISSUE THREAD

**Issue by laizewei** [PaddlePaddle/PaddleOCR#2167]
onnxruntime1.7.0 windows x64，不能加载ch_ppocr_mobile_v2.0_rec_pre转的onnx模型 。

Load model from rec_paddle.onnx failed:This is an invalid model. Error in Node:ScatterND@1 : No Op registered for ScatterND with domain_version of 9

**Comment by laizewei** [comment]
用opt11转换可以加载了，但是推理报 
2021-03-04 11:28:19.5141933 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}
Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

**Comment by laizewei** [comment]
1.7.0onnxruntime推理报错,1.6.0onnxruntime可以推理。谁的锅

**Comment by Channingss** [comment]
> onnxruntime1.7.0 windows x64，不能加载ch_ppocr_mobile_v2.0_rec_pre转的onnx模型 。
> 
> Load model from rec_paddle.onnx failed:This is an invalid model. Error in Node:ScatterND@1 : No Op registered for ScatterND with domain_version of 9

这个问题的develop分支里面修复啦，ScatterND是onnx opset11才有的。



> 1.7.0onnxruntime推理报错,1.6.0onnxruntime可以推理。谁的锅

onnxruntime 1.7.0是最新出来的版本，我们之前一直使用1.6.0进行的测试。感谢反馈

**Comment by laizewei** [comment]
develop分支修复了？是paddleocr还是paddlepaddle分支？

**Comment by Channingss** [comment]
> develop分支修复了？是paddleocr还是paddlepaddle分支？我更新了paddle2.1.0dev0和paddleocr还是不行

paddle2onnx，解决的Node:ScatterND 注册的版本管理问题，onnxruntime 1.7.0的问题我们第一次发现，需要接下来验证和定位。

**Comment by laizewei** [comment]
我从源码安装了paddle2onnx，还是报错。希望尽快修复

**Comment by Channingss** [comment]
> 我从源码安装了paddle2onnx，还是报错。希望尽快修复

请问报错信息是什么？

**Comment by laizewei** [comment]
2021-03-04 17:03:57.2407649 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}
Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

**Comment by Channingss** [comment]
> > develop分支修复了？是paddleocr还是paddlepaddle分支？我更新了paddle2.1.0dev0和paddleocr还是不行
> 
> paddle2onnx，解决的Node:ScatterND 注册的版本管理问题，onnxruntime 1.7.0的问题我们第一次发现，需要接下来验证和定位。

请仔细看一下上面回复的信息呢。

Muqi

**Comment by laizewei** [comment]
请问修复了吗

**Comment by znsoftm** [comment]
加油：）
