### ISSUE TITLE
如何对dygraph进行重置操作

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#2169]
将tool/eval.py封装成了一个函数使用，eval_dict = eval.main(args)，然后在其后面，将tool/export_model.py封装成函数，export_model.main(args)，此时报错：
parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

似乎在eval结束后没有释放模型？
paddle中有类似于pytorch的`torch.cuda.empty_cache()`功能么，可对dygraph 进行重置操作？
如何处理可解决此问题。

**Comment by simplew2011** [comment]
找到这个
paddle.fluid.dygraph.disable_dygraph()
paddle.fluid.dygraph.enable_dygraph()

**Comment by Harrison410-web** [comment]
您好，知道怎么修改了吗？

**Comment by WenmuZhou** [comment]
torch.cuda.empty_cache() 类似的功能目前还没有

**Comment by Harrison410-web** [comment]
> torch.cuda.empty_cache() 类似的功能目前还没有

paddle.fluid.dygraph.disable_dygraph()
paddle.fluid.dygraph.enable_dygraph()
我根据这两条指令搞定了，但是不懂原因
