### ISSUE TITLE
sast检测印章等弯曲文本，yml和标注文件需要如何准备

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleOCR#2170]
使用labelme标注印章，每张图片分辨率315x315，16点标注，yml文件只修改数据集路径的情况下：
    
![image](https://user-images.githubusercontent.com/18511799/109931287-a023b280-7d03-11eb-82c3-2e000bb93337.png)

训练结果也收敛了，但是eval评估准确率为0，转infer模型评估效果也是惨不忍睹，sast训练有哪些参数和注意事项嘛？

![image](https://user-images.githubusercontent.com/18511799/109931193-7f5b5d00-7d03-11eb-94f9-e35a8376b643.png)

![image](https://user-images.githubusercontent.com/18511799/109930596-c7c64b00-7d02-11eb-80c4-5232e14a4657.png)

**Comment by LDOUBLEV** [comment]
可以在你的训练集上可视化效果是不是可以的

**Comment by jackiezzq** [comment]
> 可以在你的训练集上可视化效果是不是可以的

效果附上了（第三张图），完全没框住，反而把五角星给框住了 @LDOUBLEV

**Comment by LDOUBLEV** [comment]
你训练用的哪个配置文件呢，有没有修改了什么

**Comment by jackiezzq** [comment]
det_r50_vd_sast_totaltext.yml  只修改了训练集测试集路径

**Comment by jackiezzq** [comment]
> 你训练用的哪个配置文件呢，有没有修改了什么

det_r50_vd_sast_totaltext.yml  只修改了训练集测试集路径

**Comment by LDOUBLEV** [comment]
加载pretrain_model了吗？

**Comment by jackiezzq** [comment]
> 加载pretrain_model了吗？

这个肯定加载了啊
![image](https://user-images.githubusercontent.com/18511799/110072230-6c569480-7db8-11eb-8600-c7d87da60f5c.png)

**Comment by KampauCheung** [comment]
我也遇到了类似的问题，在LSVT数据集上训练的时候，eval评估准确率一般般，可视化后的框框非常乱

**Comment by yoggaboomin** [comment]
你好，请问问题解决了吗？
