### ISSUE TITLE
检测训练模型和预测模型如何保证结果一致

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleOCR#2172]
修改了utility.py和predict_det.py：DetResizeForTest等相关参数，对齐了训练时的DB预处理参数和预测时的参数。
但infer_det.py和predict_det.py结果总是不一致。
把测试图片和训练模型及inference模型及其配置表文件一同上传。
请求协助。
您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/7195b82ccee442

**Comment by simplew2011** [comment]
总结几个问题：
1、DetResizeForTest设置为空，在批量预测大量尺寸不一的图片时会导致显存溢出（predict_det和infer_det两种都会），但预测少量图片10几张或者文件夹内有大量图片但尺寸固定时，均可正常预测，且效果稳定；
2、DetResizeForTest设置为其他'image_shape': [736, 1280]或者'resize_long': 960时，predict_det（差）和infer_det（好）效果差异大。
1和2两个
总之问题还是出现在训练和预测时的图像预处理操作不能统一，没有更好的考虑。希望能够修复。  @LDOUBLEV

**Comment by LDOUBLEV** [comment]
除了预处理参数要一致，后处理参数也要对齐，不同的配置文件参数不一样

DetResizeForTest的不同预处理方式在[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/ac31a18b6177a2ca3e7701d2aa80a6295fbe798f/ppocr/data/imaug/operators.py#L115)，可以根据你的场景选择不同的预处理方式
