### ISSUE TITLE
paddleocr android_demo 识别 带空格英文问题请教

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleOCR#2173]
jpg图里面内容如下：
Abc  china 5.5V tEST

识别出来其中：china×5.5V×tEST，带有“×”，而不是空格显示。rec模型使用的是支持空格的nb文件
2021-03-05 08:59:00.194 3762-3781/com.baidu.paddle.lite.demo.ocr I/Predictor: [stat] Preprocess Time: 558.0 ; Inference Time: 2432.0 ;Box Size 2
2021-03-05 08:59:00.194 3762-3781/com.baidu.paddle.lite.demo.ocr I/Predictor: Abc 0.99923706; Points: (113,66) (157,66) (157,88) (113,88) 
2021-03-05 08:59:00.194 3762-3781/com.baidu.paddle.lite.demo.ocr I/Predictor: china×5.5V×tEST 0.9880313; Points: (160,66) (289,66) (289,87) (160,87)

**Comment by tink2123** [comment]
方便看下测试原图吗？

**Comment by mybrew** [comment]
![1](https://user-images.githubusercontent.com/5379117/110070331-b3428b00-7db4-11eb-9286-d0ee9c3cc885.JPG)


> 方便看下测试原图吗？

**Comment by tink2123** [comment]
直接用识别模型预测，返回的是空格，这个x感觉是您那边的显示问题。能否尝试一下其他带标点符号的图片，看下识别结果呢？

**Comment by mybrew** [comment]
> 直接用识别模型预测，返回的是空格，这个x感觉是您那边的显示问题。能否尝试一下其他带标点符号的图片，看下识别结果呢？

你好，请问你用的是哪个模型，我用的是ch_rec_mv3_crnn_enhance。

**Comment by tink2123** [comment]
我使用的是轻量级中文模型：
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

**Comment by mybrew** [comment]
> 我使用的是轻量级中文模型：
> https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

你好，我使用你提到的这个infer.tar 转为只有model和params格式的模型会失败。请问你是怎么转换的呀？
我是这样转换的。我用的是paddleocr是dygraph版本的。
python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference Global.save_inference_dir=./inference/ch_mobileV2.0_rec_crnn/
log报错提示“AssertionError: Given dir ./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference.pdp
arams not exist.” 这个tar包里面的文件后缀好像和其他的不太一样。

**Comment by tink2123** [comment]
这个infer本身就是转换好的，直接解压之后里面就是 model 和 params




发自网易邮箱大师
在2021年03月08日 13:55，mybrew 写道：

我使用的是轻量级中文模型：
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

你好，我使用你提到的这个infer.tar 转为只有model和params格式的模型会失败。请问你是怎么转换的呀？
我是这样转换的。我用的是paddleocr是dygraph版本的。
python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference Global.save_inference_dir=./inference/ch_mobileV2.0_rec_crnn/
log报错提示“AssertionError: Given dir ./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference.pdp
arams not exist.” 这个tar包里面的文件后缀好像和其他的不太一样。

**Comment by mybrew** [comment]
> 这个infer本身就是转换好的，直接解压之后里面就是 model 和 params 发自网易邮箱大师 在2021年03月08日 13:55，mybrew 写道： 我使用的是轻量级中文模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar 你好，我使用你提到的这个infer.tar 转为只有model和params格式的模型会失败。请问你是怎么转换的呀？ 我是这样转换的。我用的是paddleocr是dygraph版本的。 python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference Global.save_inference_dir=./inference/ch_mobileV2.0_rec_crnn/ log报错提示“AssertionError: Given dir ./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference.pdp arams not exist.” 这个tar包里面的文件后缀好像和其他的不太一样。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，可是这个链接文件我解压出来是inference.pdiparams，inference.pdiparams.info，inference.pdmodel 这3个文件，里面没有model 和 params呀。

**Comment by tink2123** [comment]
你使用的是静态图嘛？ 那可以直接下载1.1版本的inference model




发自网易邮箱大师
在2021年03月08日 14:03，mybrew 写道：

这个infer本身就是转换好的，直接解压之后里面就是 model 和 params 发自网易邮箱大师 在2021年03月08日 13:55，mybrew 写道： 我使用的是轻量级中文模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar 你好，我使用你提到的这个infer.tar 转为只有model和params格式的模型会失败。请问你是怎么转换的呀？ 我是这样转换的。我用的是paddleocr是dygraph版本的。 python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference Global.save_inference_dir=./inference/ch_mobileV2.0_rec_crnn/ log报错提示“AssertionError: Given dir ./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference.pdp arams not exist.” 这个tar包里面的文件后缀好像和其他的不太一样。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，可是这个链接文件我解压出来是inference.pdiparams，inference.pdiparams.info，inference.pdmodel 这3个文件，里面没有model 和 params呀。

**Comment by mybrew** [comment]
> 你使用的是静态图嘛？ 那可以直接下载1.1版本的inference model 发自网易邮箱大师 在2021年03月08日 14:03，mybrew 写道： 这个infer本身就是转换好的，直接解压之后里面就是 model 和 params 发自网易邮箱大师 在2021年03月08日 13:55，mybrew 写道： 我使用的是轻量级中文模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar 你好，我使用你提到的这个infer.tar 转为只有model和params格式的模型会失败。请问你是怎么转换的呀？ 我是这样转换的。我用的是paddleocr是dygraph版本的。 python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference Global.save_inference_dir=./inference/ch_mobileV2.0_rec_crnn/ log报错提示“AssertionError: Given dir ./ch_lite/ch_ppocr_mobile_v2.0_rec_infer/inference.pdp arams not exist.” 这个tar包里面的文件后缀好像和其他的不太一样。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，可是这个链接文件我解压出来是inference.pdiparams，inference.pdiparams.info，inference.pdmodel 这3个文件，里面没有model 和 params呀。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我用predict_system.py测试，感觉ch_ppocr_mobile_v2.0比ch_ppocr_mobile_v1.1效果更好，v1.1识别不出来的空格v2.0可以识别出来。

**Comment by YY007H** [comment]
请问你英文识别带有空格吗？

**Comment by mybrew** [comment]
> 请问你英文识别带有空格吗？

有空格，但不是100% ok

**Comment by YY007H** [comment]
> > 请问你英文识别带有空格吗？
> 
> 有空格，但不是100% ok

我用Android手机跑的是1.1的nb模型，一点空格都检测不出来，你那里可以检测出来？怎么处理的

**Comment by private1215** [comment]
你说的问题是可以在Predictor这个类中的postprocess方法里解决，你遇到的那个x只需要把 word.append("×");注释掉就可以了，我遇到的问题是识别出来的文本都多了一个\r，我直接在这个方法里replace了一下搞定
