### ISSUE TITLE
请问一下PaddleOCR可不可以进行定制化模板识别，例如只识别票据中的某一些，而且识别之后要按要求排列组织

### ISSUE THREAD

**Issue by huabao97** [PaddlePaddle/PaddleOCR#2174]

**Comment by LDOUBLEV** [comment]
目前不支持

> 例如只识别票据中的某一些

这个需要你重新训练，把想要识别的部分标注训练

> 而且识别之后要按要求排列组织 

可以获得识别的结果和检测框的位置，你可以根据检测框的位置排列文本
