### ISSUE TITLE
有没有直接基于视屏的推理工具？

### ISSUE THREAD

**Issue by jingruhou** [PaddlePaddle/PaddleOCR#2175]
有没有基于视屏的推理工具，可以直接输入视屏路径，然后直接就返回绘制好检测框+识别结果的示例呢？

**Comment by LDOUBLEV** [comment]
你可以改一下代码，对输入视频做处理，拆成一帧一帧的图像，然后送到PPOCR中识别

**Comment by chocolate-byte** [comment]
请问下ppocr识别是不是会出现每捕捉到一帧就跑一遍整个程序重新加载一次模型这个现象，有什么办法让模型一直处于加载状态吗
