### ISSUE TITLE
使用styleText 批量生成图片

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#2177]
我在image_list中增加多个图片背景，但是生成的图片只有一种图片背景，是哪里的配置不对吗？
![image](https://user-images.githubusercontent.com/28819717/110082052-ce6ac600-7dc7-11eb-8af0-14eeb5750447.png)
![image](https://user-images.githubusercontent.com/28819717/110082075-d460a700-7dc7-11eb-92ea-3164ba43d8b0.png)

**Comment by mingo-doer** [comment]
生成的背景只有0.jpg的背景图

**Comment by weisy11** [comment]
一共生成了多少张图呢？生成的时候会对style随机采样，如果生成的图片数量很少，可能会采样到同一张图片

**Comment by mingo-doer** [comment]
多谢，问题已解决了
