### ISSUE TITLE
PaddleOCR检测模型训练中,控制台打印的log中的字段都代表啥意思,能否请教一下,非Python开发人员,望理解。

### ISSUE THREAD

**Issue by NSLog-YuHaitao** [PaddlePaddle/PaddleOCR#2179]
![image](https://user-images.githubusercontent.com/18722689/110097754-607bca00-7dda-11eb-9fc8-c07198b733da.png)

**Comment by immense8342** [comment]
和python无关，是深度学习的训练过程记录

**Comment by NSLog-YuHaitao** [comment]
> 和python无关，是深度学习的训练过程记录

那每个字段代表含义是啥?
