### ISSUE TITLE
visualdl 有文件无输出

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2180]
配置文件设置True了，模型保存目录下有vdl文件，里面有log，但是用命令行无法输出。

(paddleocr) ***@*******:~/ocr/PaddleOCR$ visualdl --logdir ./output/rec_focal/vdl --host 0.0.0.0 --port 14321
VisualDL 2.1.1
Running VisualDL at http://0.0.0.0:14321/ (Press CTRL+C to quit)

**Comment by littletomatodonkey** [comment]
这个应该是访问本地ip+端口号去查看可视化效果的
![image](https://user-images.githubusercontent.com/14270174/110233969-b8ddd380-7f62-11eb-8e0c-869e72eeb0c1.png)

可以参考visualdl的官网：https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md
