### ISSUE TITLE
如何设置inference模型输入为固定大小？

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#2183]
如何设置用户训练的ppocr模型inference模型输入为固定大小？主要原因时在paddle2onnx时经常报错

**Comment by littletomatodonkey** [comment]
识别为例，在这里，将shape改为(3, 32, 320)，
https://github.com/PaddlePaddle/PaddleOCR/blob/978807038a4570dd94194873ca5ecbe284d02125/tools/export_model.py#L81
但是ocr模型目前没有在paddle2onnx上验证过，更建议使用paddle inference部署

**Comment by PhilCuriosity** [comment]
好的，谢谢

**Comment by PhilCuriosity** [comment]
> 识别为例，在这里，将shape改为(3, 32, 320)，
> https://github.com/PaddlePaddle/PaddleOCR/blob/978807038a4570dd94194873ca5ecbe284d02125/tools/export_model.py#L81
> 
> 
> 但是ocr模型目前没有在paddle2onnx上验证过，更建议使用paddle inference部署

好的，谢谢
