### ISSUE TITLE
Few clarification

### ISSUE THREAD

**Issue by jey07** [PaddlePaddle/PaddleOCR#2186]
I have noticed that using sever model and bit of image pre processing, I am able to improve the performance. I am using below 
standard command line to execute.
```
!python tools/infer/predict_system.py --image_dir="/content/gdrive/My Drive/SmartAnalytics/Dataset/Test" \
 --det_model_dir="/content/gdrive/My Drive/Paddle_OCR/inference/ch_ppocr_server_v2.0_det_infer" \
 --det_algorithm="DB" \
 --use_dilation=True \
 --rec_model_dir="/content/gdrive/My Drive/Paddle_OCR/inference/ch_ppocr_server_v2.0_rec_infer/" \
 --cls_model_dir="/content/gdrive/My Drive/Paddle_OCR/inference/ch_ppocr_mobile_v2.0_cls_infer/" \
 --use_angle_cls=False --use_space_char=True --use_gpu=True
```

I noticed that ` --rec_char_type` default value is chinese The moment I change to english by giving "en", the program throw errors as below:
```
   rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/content/gdrive/MyDrive/Paddle_OCR/paddle_payslip/tools/infer/predict_rec.py", line 241, in __call__
    rec_result = self.postprocess_op(preds)
  File "/content/gdrive/MyDrive/Paddle_OCR/paddle_payslip/ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/content/gdrive/MyDrive/Paddle_OCR/paddle_payslip/ppocr/postprocess/rec_postprocess.py", line 88, in decode
    idx])])
```
Also, I have seen that dilation can be set through argument but not erosion. How can i add erosion while using server model ? Or where should i add erosion code.?

**Comment by littletomatodonkey** [comment]
1. when you specify the dict, you have to use type `ch`
2. You can search cv2.dilate in the source code. You can also use erosion if it's better in your scene.

https://github.com/PaddlePaddle/PaddleOCR/blob/e6a95c3a71dddbfc41fe9786fde0ad153a29ae52/ppocr/postprocess/db_postprocess.py#L147

**Comment by jey07** [comment]
So you meant to say that if I set --rec_char_type as and "ch" and path to dict as english then it will work ?

Thanks for answering the other question.

**Comment by tink2123** [comment]
1. Yes, The dilation operation is in the db post-processing. If you want to use it in the pre-processing, you can refer to the post-processing to add the corresponding code.
2. --rec_char_type = 'ch'  meaning a custom dictionary. Just set --rec_char_type to ‘ch’ and the set dictionary file will be read
