### ISSUE TITLE
rec模型eval计算准确率为什么空格

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2188]
pred = pred.replace(" ", "")
target = target.replace(" ", "")

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by tink2123** [comment]
主要是为了对齐DTRB的计算规则，另外中文场景下对空格识别也不敏感。
如果有需要的话，可以把这两行注释掉。
