### ISSUE TITLE
识别模型的padding部分需要做特殊处理吗？

### ISSUE THREAD

**Issue by seuGLX** [PaddlePaddle/PaddleOCR#219]
识别模型预处理padding部分为0，但是识别模型做lstm和attention的时候并没有考虑到padding的影响，padding会影响到非padding部分，请问识别模型是如何去掉padding的影响的？

**Comment by tink2123** [comment]
不需要做特殊处理，预处理时对图像做padding，得到效果类似于：
![图片](https://user-images.githubusercontent.com/31891223/84893573-0911be80-b0d2-11ea-8e16-7d5f2240fe89.png)
经过特征提取后，padding信息不会对lstm产生过多影响

**Comment by seuGLX** [comment]
上图是特征提取图吗，是哪一层的输出？在中文场景中，当w比较大，padding比较多的时候，验证集上的acc会出现抖动情况，前后两个epoch acc相差十几个点，不知道有没有遇到过？

**Comment by tink2123** [comment]
上图是输入图片的类似效果，中文场景中ctc解码方式有抖动是合理的。我们实验时也有波动，波动程度可能和训练数据有关。训练过程中代码会保存最佳模型，最终收敛效果不会有太大影响。
