### ISSUE TITLE
【手机demo开源】

### ISSUE THREAD

**Issue by MachineVision123** [PaddlePaddle/PaddleOCR#2190]
请问手机端demo代码有开源吗？感觉手机测试的效果比PC端测的好，是因为有预处理和后处理的操作吗？

**Comment by MissPenguin** [comment]
手机端demo在develop分支（静态图分支）下，android和ios都开源了。动态图的版本正在调试中，预计4月份发布。手机测试的是1.1静态图模型，pc测试的是2.0动态图模型，两个版本的模型在我们自测数据集上的指标是差不多的，具体到case上可能有效果差异，预处理和后处理都是一样的。

**Comment by MissPenguin** [comment]
android：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo
ios：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/ios_demo

**Comment by MachineVision123** [comment]
感谢解答
