### ISSUE TITLE
模型预测的时候报错ResourceExhaustedError: Fail to alloc memory of 564023296 size, error code is 12

### ISSUE THREAD

**Issue by Fraudsterrrr** [PaddlePaddle/PaddleOCR#2199]
python tools/infer/predict_system.py --image_dir="./doc/imgs/test1.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
报错：
ResourceExhaustedError: Fail to alloc memory of 564023296 size, error code is 12.
      [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:66)
      [operator < conv2d > error]
用自带的图进行预测不会报错，用自己的图就报错了。
不使用cls 会报错
ResourceExhaustedError: Fail to alloc memory of 129472640 size, error code is 12.
      [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:66)
      [operator < elementwise_add > error]
是硬件问题吗？ 期待回复，感谢。

**Comment by yukun80** [comment]
同问

**Comment by Fraudsterrrr** [comment]
解决了，  因为如果在检测阶段内存不足需要先吧输入的图片分辨率进行调整固定尺寸，在识别阶段内存不足需要调整参数rec_image_shape，rec_batch_num 调低基本上能解决内存问题
