### ISSUE TITLE
版本对应问题

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleOCR#2201]
paddlepaddle v2.0.0-beta0对应哪个paddleocr版本？

报下面这个错误怎么解决？是不是paddleocr版本用错了

----------------------
Traceback (most recent call last):
----------------------
  File "tools/infer/predict_system.py", line 185, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 142, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 40, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "/my-project/PaddleOCR/tools/infer/predict_rec.py", line 51, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/my-project/PaddleOCR/tools/infer/utility.py", line 139, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_noavx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareExecutor()
4   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
5   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
6   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
7   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string > >, std::less<std::string >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string > > > > > const&, paddle::framework::AttributeMap, bool)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
Error: Operator rnn has not been registered
  [Hint: op_info_ptr should not be null.] (at /my-project/paddle/paddle/fluid/framework/op_info.h:140)

**Comment by WenmuZhou** [comment]
paddle建议使用2.0.0

**Comment by isLiuHao** [comment]
对应develop
