### ISSUE TITLE
推理阶段，检测模型的backbone信息存放在model和params中么？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2202]
您好，
【1】检测模型的 backbone 对应的网络结构和参数 也分别保存在model和params文件中么？在inference阶段，并没有看到加载backbone结构的代码，而是直接采用 predictor = create_paddle_predictor(config)，config中指定model和params路径，那么backbone相关信息应该已包含在model文件中了，我的理解有问题么？
【2】如果【1】的理解正确，MobileNetV3_large_x0_5_pretrained参数文件已经>10M了， 和“检测（2.6M）+方向分类器（0.9M）+ 识别（4.6M）= 8.1M”中检测2.6M不一致，是paddle自己做了优化么？
谢谢！

**Comment by WenmuZhou** [comment]
1. MobileNetV3_large_x0_5_pretrained是训练时保存的模型，而你说的model和params是训练模型转inference模型之后得到的文件
2. MobileNetV3_large_x0_5_pretrained里还包含了fc层，这个参数里比较大。

**Comment by ymzx** [comment]
> 1. MobileNetV3_large_x0_5_pretrained是训练时保存的模型，而你说的model和params是训练模型转inference模型之后得到的文件
> 2. MobileNetV3_large_x0_5_pretrained里还包含了fc层，这个参数里比较大。

谢谢，还有一事不明，训练模型转inference模型得到的model和params中也应该存贮有Backbone的结构和参数信息吗？推理时候，图片也需要经过backbone提取特征然后经过DB模块等，那model和params中主要保存了Backbone哪些信息？如何保存的？大致做了哪些优化？

**Comment by WenmuZhou** [comment]
inference模型里模型结构信息在model文件里面，params文件里是对应的参数

**Comment by ymzx** [comment]
> inference模型里模型结构信息在model文件里面，params文件里是对应的参数

这个显而易见，我其实是想确认model中是否已经包含了推断所需的backbone结构信息？params是否已经包含了 推断所需的backbone参数信息？（因为我无法从model或者param中显示看到backbone信息）。
谢谢

**Comment by WenmuZhou** [comment]
包含了
