### ISSUE TITLE
超轻量模型和通用模型大小差异

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2204]
![image](https://user-images.githubusercontent.com/29808550/110453703-64bd2580-8101-11eb-8d33-aedee6dcd03a.png)
超轻量模型和通用模型 相差44M，主要是通用模型那个部门导致的？主要是因为骨干网络差异导致的么？两者检测和推理性能量化对比在哪里可以看到？谢谢

**Comment by WenmuZhou** [comment]
主要是backbone和neck部分导致的大小差异。在https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/add_new_algorithm.md 里可以看到不同backbone下的acc指标

**Comment by ymzx** [comment]
> 主要是backbone和neck部分导致的大小差异。在https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/add_new_algorithm.md 里可以看到不同backbone下的指标

这个链接是不是给错了 并没有看到不同backbone下的指标数据

**Comment by WenmuZhou** [comment]
给错了，是这个https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/algorithm_overview.md
