### ISSUE TITLE
Could you provide the architecture diagrams?

### ISSUE THREAD

**Issue by Timo9Madrid7** [PaddlePaddle/PaddleOCR#2205]
Hi,

Did you make C4 diagrams or any relative ones relative to software architecture when you design the software? And could you make them public?

Many thanks!

**Comment by grasswolfs** [comment]
https://aistudio.baidu.com/aistudio/education/group/info/6758
![image](https://user-images.githubusercontent.com/23690325/110724036-03579c80-8250-11eb-96a3-ace742ba44e2.png)

maybe these lessions can help u. However, all of them are based on Chinese only.  T.T
