### ISSUE TITLE
hubserving 部署以后GPU显存会不断增长

### ISSUE THREAD

**Issue by shch1210** [PaddlePaddle/PaddleOCR#2206]
你好，

谢谢开源项目。效果很好。
我用hubserving部署以后，发现GPU会不断增长，好像max_lone_side=960的没起作用，我想请问下应该怎么操作，可以限制GPU的不断增长。
使用的是2.0的仓库，启动命令是：
hub serving start -m ocr_system -c /tmp/padpad/PaddleOCR/deploy/hubserving/ocr_system/config.json
我看ocr_system/params.py里有cfg.det_limit_side_len = 960，这个参数限制好像没起作用。
hub是官方的安装方式pip安装的：
pip install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple \

**Comment by WenmuZhou** [comment]
hub版本是啥

**Comment by shch1210** [comment]
> hub版本是啥

你好，hub版本就是 pip install 的paddlehub，部署在服务器里，暂时没办法看hub的版本

**Comment by shch1210** [comment]
> 你测同一张图片看看会不会还增长

同一张不会涨。换图的时候会涨。如果设置了最长边不超过960.那不是应该换了大图的话应该会resize到960再预测？
我举个例子哈，比如我用了600宽的，占了3g，我用了1280的时候，假设会缩放到960，这时候显存会占到5G。那我再用1500宽的，也会缩放到960，此时不也应该是5G吗，但实际上显存可能会占到7G这样子。

**Comment by WenmuZhou** [comment]
长边不超多960，可能短边变化了，另外可以试一下单独跑ppocr的infer，如果不会oom，只是hub部署的时候会oom的话，
看看这2个issue, https://github.com/PaddlePaddle/PaddleHub/issues/682  https://github.com/PaddlePaddle/PaddleHub/issues/1212  可以在下面跟帖。
