### ISSUE TITLE
请问有软件架构图C4之类的帮助理解设计吗？

### ISSUE THREAD

**Issue by GMYMingyu** [PaddlePaddle/PaddleOCR#2208]
您好，贵项目非常有趣，感谢您的分享。
作为学生，我将您的项目作为本学期一门课的分析对象，如果有C4图之类的软件架构设计思路能分享吗？蟹蟹。

**Comment by grasswolfs** [comment]
https://aistudio.baidu.com/aistudio/education/group/info/6758
