### ISSUE TITLE
关于竖直中文识别训练过程的细节

### ISSUE THREAD

**Issue by whuhangzhang** [PaddlePaddle/PaddleOCR#221]
@MissPenguin 你好：
1. 我想在这一repo上训练自己的数据，但是我对于竖直文本的训练数据的处理有些疑惑，请问如何处理竖直文本训练集呢？是将竖直文本直接转90度进行处理呢，如下图：
![image](https://user-images.githubusercontent.com/53819630/84869804-1b2f3500-b0b1-11ea-8cef-5a6f5158d9a9.png)

2.  对于原始LSVT的文本行标注，在训练之前是如何做预处理的呢，是否需要进行透视变化？能否提供一下变换的脚本呢？
![image](https://user-images.githubusercontent.com/53819630/84869942-3f8b1180-b0b1-11ea-812b-964420dd52e8.png)

**Comment by tink2123** [comment]
1. 是的，旋转90度即可
2. 可参考predict_system 对文本行做透视变化
https://github.com/PaddlePaddle/PaddleOCR/blob/ed4313d611b7708a7763d4612f00cb7f318a0e1f/tools/infer/predict_system.py#L41
