### ISSUE TITLE
这些东西何意?

### ISSUE THREAD

**Issue by KennyHito** [PaddlePaddle/PaddleOCR#2212]
![image](https://user-images.githubusercontent.com/18722689/110569180-1f473980-818f-11eb-88db-6a582a429983.png)

**Comment by WenmuZhou** [comment]
一种评测指标，百度一下吧

**Comment by NSLog-YuHaitao** [comment]
能否说一下前三个具体的含义吗?

**Comment by weekstudy** [comment]
调和平均数，精确率，召回率
