### ISSUE TITLE
paddle lite 2.8加载官方模型报错

### ISSUE THREAD

**Issue by shyskyboy** [PaddlePaddle/PaddleOCR#2218]
从github上下载了移动端模型
![image](https://user-images.githubusercontent.com/20738555/110599802-36e9e680-81be-11eb-91d4-48f7cc1f54c4.png)
然后使用2.8的opt转换成了Android 支持的nb格式。手机加载报错
![image](https://user-images.githubusercontent.com/20738555/110600258-b4155b80-81be-11eb-88f6-4f5b64600968.png)

**Comment by weidenbach** [comment]
Google將英語翻譯成中文：
我有相同的內容，請參閱https://github.com/PaddlePaddle/PaddleOCR/issues/2300。
現在，我的錯誤隨著當前的opt和2.0模型而改變：
```
A/Paddle-Lite: [F  4/28 21:36:41.781 /island/Paddle-Lite/lite/core/program.cc RuntimeProgram:211] Check failed: (kernels.size() > 0): 0!>0 No kernels found for subgraph
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25018 (Predictor Worke), pid 24858 (com.artranslate)
```
您找到解決方案了嗎？ 
________________________________________________________________________
English:
I had the same, see https://github.com/PaddlePaddle/PaddleOCR/issues/2300 .
Now my error changed with the current opt and 2.0 models:
```
A/Paddle-Lite: [F  4/28 21:36:41.781 /island/Paddle-Lite/lite/core/program.cc RuntimeProgram:211] Check failed: (kernels.size() > 0): 0!>0 No kernels found for subgraph
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25018 (Predictor Worke), pid 24858 (com.artranslate)
```
Did you find a solution?
