### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'seed'

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2222]
![image](https://user-images.githubusercontent.com/29808550/110656881-55220780-81fb-11eb-9fa0-aeceb7dc531f.png)
请问这是什么原因导致的？

**Comment by ymzx** [comment]
版本不兼容，升级到2.0.1就自动解决了

**Comment by yifanzhang666777** [comment]
版本已经是是2.0.1了 可以还是出现 AttributeError: module 'paddle' has no attribute 'seed'
