### ISSUE TITLE
请问Style Text工具的fonts文件如何新增其他语种支持？

### ISSUE THREAD

**Issue by fengzhibin** [PaddlePaddle/PaddleOCR#2223]
我看到PaddleOCR\StyleText\fonts文件夹下有三份字体文件，当前只支持中文，英语和韩文。可以自行新增新语种吗？或者有什么办法新增其他语种的支持？

**Comment by fengzhibin** [comment]
已在微信群内咨询得到答案，暂时只有三种语种支持，只能等待开发者训练更多的语种。

**Comment by venus-chf** [comment]
除了PaddleOCR\StyleText\fonts文件夹下有三份字体文件，自己添加的字体文件出来的图片，字体不清晰是为什么

**Comment by fengzhibin** [comment]
> 除了PaddleOCR\StyleText\fonts文件夹下有三份字体文件，自己添加的字体文件出来的图片，字体不清晰是为什么

估计字体文件是需要训练得出的
