### ISSUE TITLE
win下GPURTX2080 训练无法利用到多线程。

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#223]
训练过程中总报：
multiprocess is not fully compatible with Windows.num_workers will be 1. 

TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 2
  img_set_dir: E:/GitHub/PaddleOCR/train_data/train-Blister/
  label_file_path: E:/GitHub/PaddleOCR/train_data/train-Blister/train-Blister-Paddle.txt

这里的num_workers 从1到8 都试过了，还是报这个。目前虽然报这个，但是batch=12 可以训练

**Comment by SixGodGG** [comment]
报的是多进程与window不兼容，是不是win下面num_workers 只能自动变成1，这个num_workers 大了会加快训练速度吗

**Comment by dyning** [comment]
是的，主要是提升图像预处理的速度，提高GPU的利用率
