### ISSUE TITLE
acc一直为0，请问该怎么查起？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/PaddleOCR#2232]
![image](https://user-images.githubusercontent.com/44393339/110891702-839fff80-832d-11eb-8655-cd6d3418e4b2.png)
加载了预训练模型，训练了一些带噪点的验证码图片，acc一直为0，效果并不理想
![image](https://user-images.githubusercontent.com/44393339/110891876-ea251d80-832d-11eb-9a02-4c5083668e92.png)

**Comment by caopulan** [comment]
https://github.com/caopulan/PaddleOCR_Utils
可以参考这个，把eval的间隔调短一点来输出每次eval的结果来分析模型

**Comment by littletomatodonkey** [comment]
前期loss看着能正常收敛的话，acc为0是正常的哈，10个epoch之后可以再看下acc的情况，之前训crnn的话，也是10个epoch左右，acc才大于0
