### ISSUE TITLE
训练时无报错中断

### ISSUE THREAD

**Issue by whyzq** [PaddlePaddle/PaddleOCR#2233]
![~$(JD{KDVNEB@17V $9@B%S](https://user-images.githubusercontent.com/38233412/110908966-7f360f80-834a-11eb-8147-06224026428c.png)
在这里中断是怎么回事？

**Comment by littletomatodonkey** [comment]
你好，尝试减小batch size和num worker试下呢？同时建议使用dygraph分支的动态图代码哈
