### ISSUE TITLE
SRN长中文识别

### ISSUE THREAD

**Issue by buptlihang** [PaddlePaddle/PaddleOCR#2235]
想请问一下有试过SRN在长中文数据集上（图片宽高比丰富）训练吗？效果如何呢

**Comment by tink2123** [comment]
做过相关实验的，具体数据参考SRN论文（https://arxiv.org/abs/2003.12294） 中 table 6
![image](https://user-images.githubusercontent.com/31891223/111155137-05fb1e80-85cf-11eb-8ecc-566a641c897c.png)

**Comment by buptlihang** [comment]
(pvam.WrapEncoderForFeature.PrepareEncoder.Embedding)[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/ppocr/modeling/heads/self_attention.py#L322]的num_embeddings设置为256，而它的输入src_pos是由(encoder_word_pos)[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/tools/infer/predict_rec.py#L114]传入的，是一个[0， (imgH / 8) * (imgW / 8))的数组，这里如何保证src_pos的数值小于num_embeddings(256)呢，如果图片宽度很大是无法保证的吧？那要如何推理长度很长的图片？

**Comment by buptlihang** [comment]
[resize_norm_img_srn](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/tools/infer/predict_rec.py#L88)我看到所有图片最终都是image_shape(3,32,100)的大小，这对长中文来说不合理吧

**Comment by tink2123** [comment]
> num_embeddings设置为256，而它的输入src_pos是由encoder_word_pos传入的，是一个[0， (imgH / 8) * (imgW / 8))的数组.

num_embeddings 这里是针对默认shape写死了，它是根据 [backbone 输出的 feature map 计算得到的](https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/ppocr/modeling/heads/rec_srn_head.py#L79)。当输入图片宽度设置的很大时，这里也会相应修改。

> resize_norm_img_srn我看到所有图片最终都是image_shape(3,32,100)的大小，这对长中文来说不合理吧

srn 默认的输入shape是 [1, 64，256]，如果需要支持长文本，需要修改输入shape，增大宽度。

**Comment by buptlihang** [comment]
好的，感谢！
