### ISSUE TITLE
C++ 接口怎么获取文字方向呢

### ISSUE THREAD

**Issue by lijzeng** [PaddlePaddle/PaddleOCR#2237]
c++接口中，目前我看到识别结果包含了，置信度，文本，位置，  **那文字方向（角度）**怎么获取呢

**Comment by littletomatodonkey** [comment]
可以在这里拿到：
https://github.com/PaddlePaddle/PaddleOCR/blob/f687e092b6b414a3dcda504cd56e376248d21a45/deploy/cpp_infer/src/ocr_cls.cpp#L66

**Comment by lijzeng** [comment]
哦，多谢
