### ISSUE TITLE
当num_workers大于1的时候，多线程出问题

### ISSUE THREAD

**Issue by azmat21** [PaddlePaddle/PaddleOCR#2238]
[2021/03/13 10:54:09] root INFO: During the training process, after the 0th iteration, an evaluation is run every 1000 iterations
[2021/03/13 10:54:09] root INFO: Initialize indexs of datasets:['/home/azmat/project/krakenuig/train_data/ug/test.txt']
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 21: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 22: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 23: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 24: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 25: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 26: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 27: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 28: Can't spawn new thread: res = 11
[ERROR:0] global /io/opencv/modules/core/src/parallel_impl.cpp (234) WorkerThread 29: Can't spawn new thread: res = 11

**Comment by littletomatodonkey** [comment]
你好，先看下opencv版本是否和requirements.txt中的是否相同，同时看下当前是否为dygraph分支代码哈
