### ISSUE TITLE
关于检测文本框的坐标

### ISSUE THREAD

**Issue by yukun80** [PaddlePaddle/PaddleOCR#2239]
请问在调用predict_system.py脚本和单独的检测脚本predict_det.py时，为什么检测框的坐标不一致呢？使用的检测模型均为通用中英文模型，如何修改才能使其输出一致呢？

**Comment by littletomatodonkey** [comment]
你好，可以先看下超参是否一致，同时看下是否只是检测框顺序不一致哈
