### ISSUE TITLE
求助：训练过程中，每次EVAL后都会把程序卡死

### ISSUE THREAD

**Issue by konami86** [PaddlePaddle/PaddleOCR#224]
1、训练的ICDAR2015数据集，训练过程中，每次EVAL后都会把程序卡死，麻烦大神帮忙解决一下；
2、还有'precision': 0.05172413793103448, 'recall': 0.004333172845450169, 'hmean': 0.007996446023989339，这个指标recall是正常的吗？
![EDF5D7F2-7C50-4de8-B3E5-1E1E5992D1D4](https://user-images.githubusercontent.com/33835806/84891051-d9f94e00-b0cd-11ea-97b8-e47e7b5191d3.png)

**Comment by MissPenguin** [comment]
1、请问训练的DB还是EAST？
2、迭代轮数较少，指标低是正常的

**Comment by MissPenguin** [comment]
1、DB训练ICDAR2015卡死的现象好像没碰到过，可以加一些log，看看具体是卡在哪儿
2、迭代轮数较少，指标低是正常的
