### ISSUE TITLE
How can I submit a new dictionary?

### ISSUE THREAD

**Issue by yumeliu** [PaddlePaddle/PaddleOCR#2240]
I have generated a new dictionary for a language that is not currently supported. How can I submit it?

**Comment by littletomatodonkey** [comment]
Thanks for your contribution, you can submit it in the directory: 
```
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict
```

**Comment by yumeliu** [comment]
> Thanks for your contribution, you can submit it in the directory:
> 
> ```
> https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict
> ```

Thanks for the information, but the uploads are disabled.

**Comment by grasswolfs** [comment]
> I have generated a new dictionary for a language that is not currently supported. How can I submit it?

For more language request，u can also refer to
https://github.com/PaddlePaddle/PaddleOCR/issues/1048#issuecomment-768877849
Thanks for your contribution :)
