### ISSUE TITLE
关于断点训练的建议

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2241]
能否在ckpt里保存global iterations，避免从ckpt开始训练时，epoch数时对的但是iter数错的。
用visualdl来可视化的话想要使两段训练前后连就得用横轴时间，但是中间会出现间隔，横轴用iter的话就变成都是从1开始

**Comment by littletomatodonkey** [comment]
你好，目前只保存了epoch，iter确实没有用保存的信息，这块我们优化下，感谢反馈~
