### ISSUE TITLE
文字间隔大的也被检测成了一行，这个文字检测能够分离么？

### ISSUE THREAD

**Issue by zhangcj13** [PaddlePaddle/PaddleOCR#2242]
您好：
       采用mobile模型检测时，文字间隔大的也被检测成了一行（比如像“ 分离              A115 ”这样的排列方式），这个文字检测能够通过设置参数分离么？

**Comment by LDOUBLEV** [comment]
在中文模型的训练数据里，这种算是一行，除非间隔很大，建议你加一些数据finetune训练下

**Comment by zhangcj13** [comment]
hi @LDOUBLEV :
  github把我空格吞了，其实有好几个空格，主要识别时不是正面拍的而是有一定角度的，我发现paddleocr里提供的框是用minRotateRect来获取的，这样检测框远处字符的框高度会和近处较大字符的框一样高，这样定位是不准的会直接导致后面的文字识别错误，我再尝试下服务器版本模型试试，还有多谢你的意见
