### ISSUE TITLE
需要进行相对路径import，否则install wheel包可能无法正常使用

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#2244]
https://github.com/PaddlePaddle/PaddleOCR/blob/fd5ea74b00351aa47715575f805aefa343db1725/paddleocr.py#L28

这里直接import，会造成如果在用户自己的目录结构，或者引入了其他的Paddle包，如`PaddleClas`，也存在`tools`包，那么就会引用不到这个包的问题。解决方案是使用相对引用，如这里使用

```python
from .tools.infer import predict_system
```

建议其他地方也一并处理了，否则别人install了这个paddleocr，也可能无法正常使用。

**Comment by littletomatodonkey** [comment]
好的，感谢反馈~我们测试下这个
