### ISSUE TITLE
训练Rec模型后端到端对det_db_unclip_ratio很敏感

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2246]
只训练了rec模型，基于server版本rec，只改变了最后一层维度
用的我们自己应用场景的数据作为测试集，训练过程中best accuracy在85%
但是在测端到端的时候，用同样的测试集，我们直接用的paddleocr两个版本的检测权重作为检测模型，接上我们自己的识别模型，我发现结果会被det_db_unclip_ratio这个参数影响非常大
默认的det_db_unclip_ratio是1.6，端到端的hmean是50%左右
我训练后的模型大概在3.3-3.5的时候端到端hmean能达到最大值，在78%左右

所以这个现象正常吗，有什么可以避免的方法吗，以及如果能找到最佳的det_db_unclip_ratio需要去避免这个现象吗

初步的想法是：
①训练集lsvt crop的时候进行随机的扩张留白，合成的那部分也给一个随机的留白
②验证集加上不同留白程度的图片，得到的best_accuracy相对来讲对不同的留白情况都有较好的表现

但是后来又觉得如果我找到了我det和rec模型的最佳det_db_unclip_ratio，是不是就不需要考虑泛化

**Comment by littletomatodonkey** [comment]
是的，这个参数确实影响很大，你的这两个想法都没问题~都可以试下，不过建议优先试下第1个思路，保证所有的模型都能学到这种特征。

**Comment by nissansz** [comment]
请教一下，这个训练时随机留白，白色部分多少宽度范围比较好？5-10？
