### ISSUE TITLE
模型部署

### ISSUE THREAD

**Issue by huzheng1111** [PaddlePaddle/PaddleOCR#2247]
请问一下，paddleocr在本地可以执行，但是将模型部署到paddlehub上面，request库返回的json数据是{'msg': 'list index out of range', 'results': '', 'status': '101'}，这是什么原因啊

**Comment by littletomatodonkey** [comment]
可以在server端看下更新具体的日志信息吗？

**Comment by huzheng1111** [comment]
> 可以在server端看下更新具体的日志信息吗？
现在的错误变成这个了，我的模型是在paddle1.8上面训练得到的，目前环境是paddle2.0，paddlehub2.0。在2.0环境下执行python tools/infer/predict_system.py命令是可以给出预测结果的，但是用paddlehub2.0部署后，使用python tools/test_hubserving.py命令后就出现这个错误
![捕获](https://user-images.githubusercontent.com/49019031/111133399-72692400-85b5-11eb-8260-4bf34de4df7a.PNG)

**Comment by rainmakerMa** [comment]
@littletomatodonkey 遇到同样的问题了，请问有具体原因么
