### ISSUE TITLE
如何使用test_images测试某个模型的准确率？

### ISSUE THREAD

**Issue by Hupengyu** [PaddlePaddle/PaddleOCR#2248]
在training的过程中是可以看到acc，但是我想直接看官网提供的pre_model的acc，paddle_ocr中是否有实现的代码？如果没有，希望大佬们能提供一下简单的思路。
附：paddle_ocr中有eval，但是eval只是可视化了单张图片的效果，无法提供model的acc。

**Comment by littletomatodonkey** [comment]
你好，可以使用下面的脚本进行评估，得到准确率

`python tools/eval.py -c xxx.yaml`
