### ISSUE TITLE
国名的缩写也太随心所欲了吧

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#2249]
https://github.com/PaddlePaddle/PaddleOCR/blob/c7be8856e90c2174131586a701201ad8669b616e/configs/rec/multi_language/generate_multi_language_configs.py#L22

西班牙简称 xi，葡萄牙简称 pu，你们这是真的不考虑国际化了？

**Comment by littletomatodonkey** [comment]
感谢关注和反馈，我们完善下~
