### ISSUE TITLE
關於訓練數據集

### ISSUE THREAD

**Issue by renchenliang** [PaddlePaddle/PaddleOCR#225]
想請教一下，與訓練模型是用的文中提供的數據集訓練出來的麼？還是自己添加了其他的數據集呢？

**Comment by tink2123** [comment]
中文和英文使用的数据集可以阅读Readme中的说明：

<img width="941" alt="图片" src="https://user-images.githubusercontent.com/31891223/84996131-73cd0380-b17f-11ea-9f2f-87b5b7c73372.png">

**Comment by tink2123** [comment]
检测数据集：
<img width="941" alt="图片" src="https://user-images.githubusercontent.com/31891223/84996606-108fa100-b180-11ea-8772-47d46ba25a27.png">

**Comment by renchenliang** [comment]
> 检测数据集：
> <img alt="图片" width="662" src="https://user-images.githubusercontent.com/31891223/84996699-3026c980-b180-11ea-8b0e-791aaa5376bf.png">
您好，您發的這2張圖片無法打開是神碼原因呢？

**Comment by tink2123** [comment]
可能是网络原因吧～ 图片打不开的话，在首页Readme的 `文本检测算法` 和 `文本识别算法` 中有训练数据的说明

**Comment by Aiyoj** [comment]
> 中文和英文使用的数据集可以阅读Readme中的说明：
> 
> <img alt="图片" width="941" src="https://user-images.githubusercontent.com/31891223/84996131-73cd0380-b17f-11ea-9f2f-87b5b7c73372.png">

您好，请问从lsvt数据集中crop出30w，是怎么进行位置校准的呢

**Comment by tink2123** [comment]
@Aiyoj 可以参考 #221 中的说明

**Comment by Aiyoj** [comment]
> @Aiyoj 可以参考 #221 中的说明

@tink2123 对于四点可以采用opecv的透视变化去校准，那超过4点是如何校准的呢

**Comment by dyning** [comment]
对于大于4点的检测框，目前处理方式是忽略。弯曲文字的检测和识别需要新的处理算法。

**Comment by renchenliang** [comment]
想請教一下，使用text——render生成字符，使用了大量的不同的背景亮麼？

**Comment by renchenliang** [comment]
> 对于大于4点的检测框，目前处理方式是忽略。弯曲文字的检测和识别需要新的处理算法。

想請教一下，使用text——render生成字符，使用了大量的不同的背景亮麼？

**Comment by renchenliang** [comment]
> > 对于大于4点的检测框，目前处理方式是忽略。弯曲文字的检测和识别需要新的处理算法。
> 
> 想請教一下，使用text——render生成字符，使用了大量的不同的背景亮麼？

以及不同的中文的字體

**Comment by dyning** [comment]
嗯，基于imagenet的校验集作为背景图，还有不同中文的字体
