### ISSUE TITLE
先对图片进行检测，再进行识别的过程可以分割开来吗？

### ISSUE THREAD

**Issue by immense8342** [PaddlePaddle/PaddleOCR#2254]
您好！
现在我有一个需求是，比如传入一张图片，不知道上面是否有字（是否需要识别模型），看了FQA后知道可以先对图片进行二分类（分离出有字和没字的图片），然后再进行识别。
我发现一个问题是，这样后面是不是需要重复检测和识别啊（比如检测出有字，又需要再次调用检测模型+识别模型）
`# 预测image_dir指定的单张图像
!python3 tools/infer/predict_system.py --image_dir="./doc/imgs/japan_1.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --use_space_char=True --use_gpu=False`
这个是官方给出的使用**固化模型进行预测**的代码，如果想要剔除重复检测的部分，提高效率，可以如何修改？
谢谢各位大佬。

**Comment by caopulan** [comment]
你修改下predict_system的代码逻辑就可以啊，把里面检测到识别的过程中间if判断一下结果，无结果跳过就好

**Comment by immense8342** [comment]
> 你修改下predict_system的代码逻辑就可以啊，把里面检测到识别的过程中间if判断一下结果，无结果跳过就好
好的哈~~~我思维固化了，我想着是不是在这句话外面加个if啥的，维持封装性
没想到里面可以改一改

**Comment by immense8342** [comment]
> 你修改下predict_system的代码逻辑就可以啊，把里面检测到识别的过程中间if判断一下结果，无结果跳过就好

好的哈~~~谢谢程序猿哥哥~~我思维固化了，我想着是不是在这句话外面加个if啥的，维持封装性
没想到里面可以改一改
