### ISSUE TITLE
识别模型SRN数据集

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2258]
Towards Accurate Scene Text Recognition with Semantic Reasoning Networks 论文有用SRN模型去识别中文字符

请问能提供下SRN模型中文的训练集吗，我看config和文章，应该除了字符内容还需要每个字符的位置信息吧

**Comment by WenmuZhou** [comment]
在这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/recognition.md#%E6%95%B0%E6%8D%AE%E4%B8%8B%E8%BD%BD

**Comment by caopulan** [comment]
> 在这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/recognition.md#%E6%95%B0%E6%8D%AE%E4%B8%8B%E8%BD%BD

谢谢，SRN有一部分我没太读懂，想顺便在这里提问下
attention里的阅读顺序Ot是按照数据集标注吗
最后输出是以单个字符为单位吗

**Comment by tink2123** [comment]
数据标注和CTC是一致的，输出以行为单位
