### ISSUE TITLE
数据集标注工具

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#226]
你好，请问一下：
文字检测的标注工具应该用什么？
文字识别的标注工具应该用什么？
百度是否提供了对应的工具方法可以将标注的数据生成数据训练需要的格式

**Comment by MissPenguin** [comment]
你好，我们暂时没有开源的数据标注工具，最近个人了解到的2个标注工具你可以看一下：
labelImg，矩形标注，项目地址：https://github.com/tzutalin/labelImg

**Comment by MissPenguin** [comment]
你好，我们暂时没有开源的数据标注工具，最近个人了解到的2个标注工具你可以看一下：

- labelImg，矩形标注，项目地址：https://github.com/tzutalin/labelImg

- labelme，四点、多边形、圆形等多种标注，项目地址：https://github.com/wkentaro/labelme

**Comment by Sunyingbin** [comment]
哦哦，明白了，那如果文字检测和识别的标注工具如果没有相当的，我们如果想自己标注数据的话，就只能用labelme这样的工具标注之后，写方法转成DB模型，CRNN模型能训练的那种格式对吧，或者全程手动改了，对不

**Comment by LDOUBLEV** [comment]
> 哦哦，明白了，那如果文字检测和识别的标注工具如果没有相当的，我们如果想自己标注数据的话，就只能用labelme这样的工具标注之后，写方法转成DB模型，CRNN模型能训练的那种格式对吧，或者全程手动改了，对不

对，需要把标注的格式改成PaddleOCR需要的格式

**Comment by Sunyingbin** [comment]
了解了，谢谢

**Comment by MissPenguin** [comment]
另外，也可以借助已有模型预测一遍数据，把结果作为初步的标注结果，然后用规则或人工修正，成本比纯手动标注应该能低一些

**Comment by LDOUBLEV** [comment]
自标注检测数据样本并转 PaddleOCR 训练标注的格式： https://github.com/PaddlePaddle/PaddleOCR/issues/190
