### ISSUE TITLE
训练完的DB模型做检测时，未保存检测后的图片

### ISSUE THREAD

**Issue by qcrrrrr** [PaddlePaddle/PaddleOCR#2263]
仅显示success，但是检测后的图像未保存到output中

我的训练集只有100张图片，是不是由于训练集过小，未检测到图像 所以在预测时不保存
了。

**Comment by WenmuZhou** [comment]
是没有保存图片还是保存的图片上没有框，后者的话就是检测器没训练好

**Comment by qcrrrrr** [comment]
> 是没有保存图片还是保存的图片上没有框，后者的话就是检测器没训练好

第一个，没有保存图片。
利用训练好的dbnet进行预测的时候，有的图片可以保存且检测到，有的图片完全没有保存下来。

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/tools/infer/predict_system.py#L145 这个值没有注释掉的话，是会保存图片的

**Comment by qcrrrrr** [comment]
没有注释掉，有的图片预测显示 the detected image saved in ....但是有的图片预测完仅显示sucess 没有保存，就很奇怪。

**Comment by qcrrrrr** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/tools/infer/predict_system.py#L145 这个值没有注释掉的话，是会保存图片的

还有一个问题 想咨询您，就是在eval时 检测训练的三个指标均测试为0，这是什么原因呢？precision recall hmean 是我的训练有问题么？或者说训练集（300张图片）过小？

**Comment by WenmuZhou** [comment]
你可以infer一下eval图片看看，看看有没有框，没有的话就再加点数据
