### ISSUE TITLE
IndexError: list index out of range using en_number_mobile_v2.0_rec_infer

### ISSUE THREAD

**Issue by morris87813** [PaddlePaddle/PaddleOCR#2267]
I was running predict_system.py and I have download all the inference models needed. It was running quite well when using ch_ppocr_server_v2.0_rec_infer, but I got index error after switching to en_number_mobile_v2.0_rec_infer.
I have changed the --rec_char_type to "en", and --use_space_char is also True.

**Comment by WenmuZhou** [comment]
rec_char_type should be set to EN when en_number_mobile_v2.0_rec_infer  model is used, see this link for details https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/recognition.md#%E5%B0%8F%E8%AF%AD%E7%A7%8D
