### ISSUE TITLE
这里的函数貌似完全没用

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#2268]
https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/tools/export_model.py#L34-L39

实际上这个函数完全没有用到。加在这里会造成困扰

**Comment by WenmuZhou** [comment]
这个在命令行导出的时候会用到，参考这里命的导出模型的命令https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/inference.md

**Comment by mikeshi80** [comment]
> 这个在命令行导出的时候会用到，参考这里命的导出模型的命令https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.0/doc/doc_ch/inference.md

应该确实没用到，之后命令行里使用的，是

https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/tools/export_model.py#L31

import的ArgsParser

**Comment by WenmuZhou** [comment]
fixed in thishttps://github.com/PaddlePaddle/PaddleOCR/pull/2307
