### ISSUE TITLE
CPU 并行训练

### ISSUE THREAD

**Issue by jscene** [PaddlePaddle/PaddleOCR#2271]
服务器 32C 64G

进行Paddle OCR 文本检测训练时，发现即使服务器有32核，但实际训练的时候只使用了单核进行训练，而阅读了Paddle官方API发现有支持CPU并行训练的api，所以想请问下，怎么样改造或者配置才能让OCR训练也尽量使用多的CPU资源进行训练？
![1615964185(1)](https://user-images.githubusercontent.com/13428489/111427688-6d30e400-8731-11eb-9e12-207e41fc4c52.png)

**Comment by jccc100** [comment]
我也想知道如何开启CPU并行训练，希望解决了的同学能分享一下经验，谢谢
