### ISSUE TITLE
Is there a place to download the files ?

### ISSUE THREAD

**Issue by koayst** [PaddlePaddle/PaddleOCR#2272]
In PaddleOCR/configs/det/ there is a det_r50_vd_sast_icdar15.yml.

label_file_list: [./train_data/icdar2013/train_label_json.txt, ./train_data/icdar2015/train_label_json.txt, ./train_data/icdar17_mlt_latin/train_label_json.txt, ./train_data/coco_text_icdar_4pts/train_label_json.txt]\

Is the txt files mentioned in label_file_list available for me to download ?

**Comment by littletomatodonkey** [comment]
Thanks for you attention, you can download the datasets from [google drive](https://drive.google.com/drive/folders/1ll2-XEVyCQLpJjawLDiRlvo_i4BqHCJe)

**Comment by koayst** [comment]
Hi,

Thanks for the assistance.  Managed to download the files.

Initially I encountered some problems due to the large files (those
gigabyte files).  It is alright now after I used "Backup and Sync from
Google" and was able to download all the files.  Not sure you can access
youtube, here is the link.

https://www.youtube.com/watch?v=hBNSplAMxfI

Thanks.



Regards,
Seng Tian

**Comment by koayst** [comment]
Baidu drive has 6 files and google drive has 4 files.

Can you please upload "total_text_icdar_14pt.tar" and "icdar2015.tar" to google drive ?

Thank you so much !

**Comment by koayst** [comment]
Checked Google drive and all 6 files are uploaded.

Thanks.
