### ISSUE TITLE
识别训练，结果集下没有图片

### ISSUE THREAD

**Issue by xiaozhainank** [PaddlePaddle/PaddleOCR#2273]
![image](https://user-images.githubusercontent.com/77321239/111443874-c8b89d00-8744-11eb-942a-b718ea28d8a5.png)
仔细检查了配置路径没有问题。
以下是具体配置：
![image](https://user-images.githubusercontent.com/77321239/111447808-c5271500-8748-11eb-90e1-6fb93d5545a9.png)
![image](https://user-images.githubusercontent.com/77321239/111444057-f30a5a80-8744-11eb-90f3-2cf28b6cf695.png)
![image](https://user-images.githubusercontent.com/77321239/111444232-1e8d4500-8745-11eb-88a1-b8d3e15df679.png)
![image](https://user-images.githubusercontent.com/77321239/111444286-2a790700-8745-11eb-85a1-5694851dcba5.png)

环境：
win10+py3.7+paddle2.0.1
release2.0和dygraph都是这情况。
折腾好几天了，请大神帮忙看看是啥情况。

debug看到：
![image](https://user-images.githubusercontent.com/77321239/111457498-38358900-8753-11eb-9c0c-4f7e0e645db0.png)
data_lines是读取到数据了。

根据train.py中报错的提示
![image](https://user-images.githubusercontent.com/77321239/111457591-5ac7a200-8753-11eb-80f7-9f86619b7e3f.png)
data_loader为0，才导致这个报错
![image](https://user-images.githubusercontent.com/77321239/111457702-8185d880-8753-11eb-9714-a56827d59921.png)
但不清楚什么参数错误导致的。

**Comment by littletomatodonkey** [comment]
1. 可以看下数据的分隔符是否为`\t`
2. 可以在下面这里用print的方法debug一下，看下img_path是否符合预期

https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/ppocr/data/simple_dataset.py#L79

**Comment by xiaozhainank** [comment]
debug看了，分隔符是\t ，img_path也是符合预期的。
是否会和图片尺寸有关？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别训练，结果集下没有图片 (#2273)





  
可以看下数据的分隔符是否为\t
 
可以在下面这里用print的方法debug一下，看下img_path是否符合预期
  
https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/ppocr/data/simple_dataset.py#L79

**Comment by xiaozhainank** [comment]
![image](https://user-images.githubusercontent.com/77321239/111560978-a53a3480-87ce-11eb-83a7-6f7ec6948772.png)
debug看了，分隔符是\t。
通过train.py  debug后未进入def__getitem__()，未能进入你所说的的79行，而是进入23行__init__里面

**Comment by WenmuZhou** [comment]
图片数量大于batchsize吗
