### ISSUE TITLE
所有数据迭代完成后，程序退出

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#2274]
https://github.com/PaddlePaddle/PaddleOCR/blob/a7937102dbf1668a9eb3d5bc3a37ad3c88d65a9d/tools/program.py#L337-L356

理论上，这里执行完了，应该执行之后的代码，但是实际情况是程序无报错的退出了。debug之后的结果是，最后一次迭代完成后，再次回到循环的开头，就结束进程了。由于dataloader的代码是C/C++的，所以应当是没有正确的抛出StopIteration异常，结束循环，而是直接因为某种原因结束进程了。

本人由于使用RTX 3090显卡，目前的官方发布包还没有支持这个显卡，所以是自行编译的。

编译环境为

Win10,
CUDA 11.2
cuDNN 8.1.0
VS2017

编译的PaddlePaddle版本为 
develop分支的 0205e9f84ecb74ab0bcb3e06ba45779440da4c75 号提交。

目前我的Workaround，是在循环的最后，加入判断 `if idx == len(valid_dataloader)-1: break`，主动跳出循环。

依稀感觉是PaddlePaddle的问题，但由于问题出在PaddleOCR的训练环节，所以在此提交Issue

**Comment by littletomatodonkey** [comment]
你好，目前Paddle在windows上对于cuda11的支持还在进一步开发中，目前有2个方法可以绕过去

**Comment by mikeshi80** [comment]
感谢回复，了解了。
