### ISSUE TITLE
如何增加同时部署的不同配置的ocr_system？

### ISSUE THREAD

**Issue by 0000cctv** [PaddlePaddle/PaddleOCR#2275]
我需要针对不同场景使用不同的识别模型，使用hubserving时如何部署两个不同参数的ocr_system？或者能否在运行中指定使用的检测、识别模型？

**Comment by littletomatodonkey** [comment]
你好，可以的，需要启动不同的服务，服务配置中可以配置不同的超参以及不同的模型地址

**Comment by 0000cctv** [comment]
> 你好，可以的，需要启动不同的服务，服务配置中可以配置不同的超参以及不同的模型地址

那请问具体要怎么操作呢？比如是否需要新建一个ocr_system1的文件夹，把文件复制过来修改参数，然后hub install ocr_system1，预测用的地址就是predict/ocr_system1？

**Comment by yoeaki** [comment]
> 

您好，现在也是部署了docker版本，目前只看到predict/ocr_system接口，不知道您是否已经找到线索？ 
如何通过接口传入不同参数，使用不同预测模型。例如我想使用structure_table和vqa模型，如何配置呢？
