### ISSUE TITLE
Error when evaluating on images with different shapes

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/PaddleOCR#228]
I'm training on [MLT19](https://rrc.cvc.uab.es/?ch=15) dataset and I split out 1000 images for evaluation. The thing is that images from this dataset have diferrent shapes which results in error:
```
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main()
  File "tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "/paddle/PaddleOCR/tools/program.py", line 258, in train_eval_det_run
    metrics = eval_det_run(exe, config, eval_info_dict, "eval")
  File "/paddle/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 130, in eval_det_run
    cal_det_res(exe, config, eval_info_dict)
  File "/paddle/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 63, in cal_det_res
    img_list = np.concatenate(img_list, axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by MissPenguin** [comment]
You can alse try to change the value of parameter "train_batch_size_per_card" in config to 1.

**Comment by MissPenguin** [comment]
You can alse try to change the value of parameter "test_batch_size_per_card" in config to 1.

**Comment by xxxpsyduck** [comment]
@LDOUBLEV @MissPenguin It's not the problem. From line 55 to line 62 in `eval_det_utils.py` :
```python
            img_list = []
            ratio_list = []
            img_name_list = []
            for ino in range(img_num):
                img_list.append(data[ino][0])
                ratio_list.append(data[ino][1])
                img_name_list.append(data[ino][2])
            img_list = np.concatenate(img_list, axis=0)
```
I try to print out the shape of data[ino][0].
When using icdar15:
```
(1, 3, 672, 1280)
(1, 3, 672, 1280)
(1, 3, 672, 1280)
...
```
When using mlt19:
```
(1, 3, 1024, 1440)
(1, 3, 1760, 2400)
(1, 3, 2400, 1760)
(1, 3, 1536, 2048)
(1, 3, 1536, 2048)
(1, 3, 960, 704)
...
```
That is the problem

**Comment by MissPenguin** [comment]
Have you tried to change the value of parameter "test_batch_size_per_card" in config to 1?
I ran into the same problem and solved it by change "test_batch_size_per_card" to 1. This solution makes sense because "img_num" would be 1 and "img_list" only contained 1 image. Then it is impossible to report an error in the "concatenate" operation again.

**Comment by xxxpsyduck** [comment]
@MissPenguin It solved the problem temporarily but it doesn't make sense because we have lots of images, especially when training rec model

**Comment by MissPenguin** [comment]
This operation is only used for evaluation and test. In training, images will be scaled to the same shape.

**Comment by xxxpsyduck** [comment]
I know, but it still costly to evaluate 1 by 1

**Comment by MissPenguin** [comment]
If you want to speed up the evaluation，you can scale the images to the same shape by adding a parameter "test_image_shape" in reader yml, ref to https://github.com/PaddlePaddle/PaddleOCR/blob/develop/configs/det/det_db_icdar15_reader.yml

**Comment by xxxpsyduck** [comment]
@MissPenguin I already had that parameter but it seem that it was never used so it causes the problem

**Comment by MissPenguin** [comment]
Ah, I got it. You are training east, but it only works in DB now. Try to replace resize image function(https://github.com/PaddlePaddle/PaddleOCR/blob/1816241d10072dfbaa5da178d1c6c650b9af198f/ppocr/data/det/east_process.py#L504) with that in DB(https://github.com/PaddlePaddle/PaddleOCR/blob/dfa00e1a70a8c7c9d51c8dcd27c17c5e68fa471a/ppocr/data/det/db_process.py#L205). We'll fix this later~

**Comment by xxxpsyduck** [comment]
@MissPenguin but I'm training DB. Actually I just modied your DB reader for icdar15

**Comment by MissPenguin** [comment]
😢OK, then,,, can you debug step by step to verify it goes to "resize_image_type1" or "resize_image_type0"? "resize_image_type1" resize images to fixed shape specified by "test_image_shape", while "resize_image_type0" only adjust the side length to a multiple of 32.

**Comment by xxxpsyduck** [comment]
@MissPenguin Images go through "resize_image_type0"

**Comment by xxxpsyduck** [comment]
@MissPenguin I got it! In config it must be 'det_image_shape' not 'test_image_shape'

**Comment by MissPenguin** [comment]
Bug catched！😂 I'll fix it !
