### ISSUE TITLE
window系统无法启动标注工具,如图所示

### ISSUE THREAD

**Issue by NSLog-YuHaitao** [PaddlePaddle/PaddleOCR#2280]
![1AB97A0B-4871-42c4-9AFA-F273DA27713E](https://user-images.githubusercontent.com/18722689/111561743-ed0d8b80-87cf-11eb-8ec2-9bdf6005777f.png)

**Comment by Evezerest** [comment]
尝试运行一下预测脚本，看环境是否正常

**Comment by NSLog-YuHaitao** [comment]
怎么去预测 如何执行?
