### ISSUE TITLE
求数据生成训练代码，谢谢！

### ISSUE THREAD

**Issue by xiaowenhe** [PaddlePaddle/PaddleOCR#2281]
想结合自己的数据训练数据生成，求训练代码。

**Comment by littletomatodonkey** [comment]
你好，感谢关注，我们会在4-5月份开源训练代码，敬请期待~

**Comment by xiaowenhe** [comment]
@littletomatodonkey ，请问，Style-Text数据合成训练代码可以开源了吗？谢谢！

**Comment by xiaowenhe** [comment]
@littletomatodonkey ，请问，Style-Text数据合成训练代码可以开源了吗？谢谢！

**Comment by xiaowenhe** [comment]
@littletomatodonkey ，请问，Style-Text数据合成训练代码可以开源了吗？谢谢！

**Comment by ZaneCode6574** [comment]
同，请问多久才会开源训练代码
