### ISSUE TITLE
使用昇腾 310 Ai芯片，没有加速效果，是否要做什么配置？

### ISSUE THREAD

**Issue by huailian1216** [PaddlePaddle/PaddleOCR#2284]
购买了 2台华为云服务器，其中一台 AI加速服务器使用了  昇腾 310 Ai芯片
单张 图片 识别， 有AI 芯片的 耗时 4s，没有 AI 芯片 3.5s 左右
昇腾 310 Ai芯片 完全没 作用，是否要做什么配置？

**Comment by AIpioneer** [comment]
您好！当前的昇腾310硬件还没有适配paddle太多的算子，所以目前还不支持对ocr模型的ai加速
