### ISSUE TITLE
Bad result when inferencing image with trained Traditional Chinese model

### ISSUE THREAD

**Issue by nwlam** [PaddlePaddle/PaddleOCR#2287]
Hi, I was trying to fine-tune the Traditional Chinese model (ch_tra_mobile_v2.0_rec, trained model).  Before fine-tuning, I used the model to infer an image, the image consists of 1 unknown word and 6 known words (with reference to ppocr/utils/dict/ch_tra_dict.txt).  The model should be able to recognize the known words.  
Below is the result.  The result changed every time, but the thing in common is that the confidence level is very low. It seems that it was not able to recognize the characters precisely at all, which may be due to the config issue in my view.

![image](https://user-images.githubusercontent.com/59189296/111590649-56f25900-8801-11eb-90c9-94c84e17c880.png)

However, I tried with another Simplified Chinese model (ch_ppocr_mobile_v2.0_rec) following similar constructions, and the result came out pretty well. 
![image](https://user-images.githubusercontent.com/59189296/111591178-0deed480-8802-11eb-8dd0-b49d2be3f3b9.png)

Therefore I guess something went wrong with the .yml file, or I was using a non-consistent dictionary with the trained model.

Attached is the .yml file I used when I was inferring the image with the traditional Chinese model (I changed it to .txt just for uploading).  Any help would be appreciated.  Thanks.
[rec_ch_tra_lite_train.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6162198/rec_ch_tra_lite_train.txt)

**Comment by tink2123** [comment]
>Below is the result. The result changed every time, but the thing in common is that the confidence level is very low. It seems that it was not able to recognize the characters precisely at all, which may be due to the config issue in my view.

This seems to be the prediction result obtained by random initialization of the model. It is not successfully loaded into the trained parameters, you can try to modify this parameter:
`use_space_char: True`

**Comment by nwlam** [comment]
Thanks, the problem is solved now.  I will now close this issue.
