### ISSUE TITLE
import paddle之后提示只能使用cpu,有遇到这个问题的吗

### ISSUE THREAD

**Issue by Mafengqiang** [PaddlePaddle/PaddleOCR#2289]
![image](https://user-images.githubusercontent.com/44855506/111625367-bbc0aa00-8827-11eb-8760-f5758e77fdb3.png)
服务器的cuda版本为9.0
![image](https://user-images.githubusercontent.com/44855506/111625667-13f7ac00-8828-11eb-9629-a067f87ab42b.png)
这是服务器的配置，我安装的是cuda10.1的paddle镜像
![image](https://user-images.githubusercontent.com/44855506/111625783-38ec1f00-8828-11eb-8d16-0409ceac4a05.png)
下载的是
python3 -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple
用这条指令下载的paddle
能帮我看一下哪里出问题了吗，谢谢大家

**Comment by WenmuZhou** [comment]
主机驱动太低了不支持cuda10.1吧
