### ISSUE TITLE
images generated by style text missing gt. words

### ISSUE THREAD

**Issue by zhyj3038** [PaddlePaddle/PaddleOCR#2293]
I used  "style text" to generate chinese iamge data. but is often missing some words. for eg.
the gt is "似抽咬瑜震枣炒蹒锏緑杳沅", but image generated is 
<img width="297" alt="微信图片_20210319103437" src="https://user-images.githubusercontent.com/14101478/111723692-d2abd000-8818-11eb-8669-30ebc8945c58.png">

**Comment by littletomatodonkey** [comment]
Hi, you can show more images generated in the current dir? Such as fake_text.jpg and so on.

**Comment by zhyj3038** [comment]
<img width="63" alt="微信图片_20210323141234" src="https://user-images.githubusercontent.com/14101478/112101597-c9de3580-8b5b-11eb-9c42-00a299c14faa.png">
<img width="233" alt="微信图片_20210323141227" src="https://user-images.githubusercontent.com/14101478/112101607-cc408f80-8b5b-11eb-94c5-890c953f5486.png">
<img width="169" alt="微信图片_20210323141220" src="https://user-images.githubusercontent.com/14101478/112101622-d19dda00-8b5b-11eb-8492-6a4002f3b6a3.png">

this badcase  can easily get using "style text"
