### ISSUE TITLE
部署c++Docker镜像，是否有更小的镜像

### ISSUE THREAD

**Issue by fujianhai** [PaddlePaddle/PaddleOCR#2297]
您好，部署中采用docker镜像部署，发现镜像太大了 udo docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash， 有10G+，是否有比较简洁的镜像？

较小的推理镜像 ？

**Comment by littletomatodonkey** [comment]
你好，大部分的docker都是挺大的，因为考虑到尽可能覆盖大家的通用开发场景。

如果希望找一些比较小的镜像，你可以在下面的地址中找一个适合自己开发的镜像~

https://hub.docker.com/r/paddlepaddle/paddle/tags/?page=1&ordering=last_updated

**Comment by fujianhai** [comment]
@littletomatodonkey, 多谢，如果你们能提供几个轻量级c++部署的 dockerfile，那样就更好了。
