### ISSUE TITLE
使用SRN识别中文时的问题

### ISSUE THREAD

**Issue by CoderAnn** [PaddlePaddle/PaddleOCR#2298]
使用SRN识别中文时会产生大量的重复识别的问题，如一句话的label是：“述信息发生变更”，识别结果为：“述信息发生变变更”，请问有遇到这样的问题吗？或者基于SRN训练中文识别时是否有小trick呢？

**Comment by aishangmaxiaoming** [comment]
SRN识别中文模型是自己的数据训练的吗

**Comment by tink2123** [comment]
>使用SRN识别中文时会产生大量的重复识别的问题

重复识别的问题暂时没有遇到呢，您的训练样本的最大长度是25吗？预测和训练的图片shape是否一致呢？

> SRN识别中文模型是自己的数据训练的吗

是的，需要自己准备数据训练

**Comment by aishangmaxiaoming** [comment]
> 使用SRN识别中文时会产生大量的重复识别的问题，如一句话的label是：“述信息发生变更”，识别结果为：“述信息发生变变更”，请问有遇到这样的问题吗？或者基于SRN训练中文识别时是否有小trick呢？

请问crnn和SRN哪个在中文效果好呢

**Comment by tink2123** [comment]
>请问crnn和SRN哪个在中文效果好呢

如果训练数据量不多的话，建议使用CRNN，SRN在更大的训练数据中会有优势。
