### ISSUE TITLE
Android mobile OCR with 2.0 models not working

### ISSUE THREAD

**Issue by weidenbach** [PaddlePaddle/PaddleOCR#2300]
Hey, I'm german so sorry for not writing in chinese.
I'm trying to improve the results of PaddleOCR mobile by moving from the 1.1 to the new 2.0 models.
Based on this https://github.com/PaddlePaddle/PaddleOCR/issues/1894 issue, it is possible to use the 2.0 dynamic graph models (hopefully better performance?).

I've used the latest PaddleLite version v2.8-rc (https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.8-rc) and the latest dygraph branch models (https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/models_list_en.md) (ch_ppocr_mobile_v2.0_det, en_number_mobile_v2.0_rec ch_ppocr_mobile_v2.0_cls) to generate the .nb files with the given opt_linux file.
Now when I start the application with these models (using the test app https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo) the app crashes with the following error
`E/libc++abi: terminating with uncaught exception of type std::out_of_range: vector`  
`A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9733 (Predictor Worke), pid 9675 (e.lite.demo.ocr)`

When using the 1.1 models the detection is working well, but the recognition model en_ppocr_mobile_v1.1_rec (https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/models_list_en.md) is connecting words together. As you can see here its connecting THE INTERNATIONAL BESTSELLER to one word without spaces:
![Screenshot_20210320-173113_OCR Chinese](https://user-images.githubusercontent.com/73471359/111877184-5d6c0680-89a2-11eb-81d1-56bf73f54597.jpg)

Im wondering how I can fix this issue with the spaces with the model 2.0, and why the 2.0 model is not working.

**Comment by WenmuZhou** [comment]
We pay close attention to the development of the official version of paddlelite2.8, and the paddleocr mobile demo will be released as soon as the official version of paddlelite2.8 is released.

**Comment by mrcnserkan** [comment]
> Hey, I'm german so sorry for not writing in chinese.
> I'm trying to improve the results of PaddleOCR mobile by moving from the 1.1 to the new 2.0 models.
> Based on this #1894 issue, it is possible to use the 2.0 dynamic graph models (hopefully better performance?).
> 
> I've used the latest PaddleLite version v2.8-rc (https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.8-rc) and the latest dygraph branch models (https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/models_list_en.md) (ch_ppocr_mobile_v2.0_det, en_number_mobile_v2.0_rec ch_ppocr_mobile_v2.0_cls) to generate the .nb files with the given opt_linux file.
> Now when I start the application with these models (using the test app https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo) the app crashes with the following error
> `E/libc++abi: terminating with uncaught exception of type std::out_of_range: vector`
> `A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9733 (Predictor Worke), pid 9675 (e.lite.demo.ocr)`
> 
> When using the 1.1 models the detection is working well, but the recognition model en_ppocr_mobile_v1.1_rec (https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/models_list_en.md) is connecting words together. As you can see here its connecting THE INTERNATIONAL BESTSELLER to one word without spaces:
> ![Screenshot_20210320-173113_OCR Chinese](https://user-images.githubusercontent.com/73471359/111877184-5d6c0680-89a2-11eb-81d1-56bf73f54597.jpg)
> 
> Im wondering how I can fix this issue with the spaces with the model 2.0, and why the 2.0 model is not working.

Which label file are you using for en_ppocr_mobile_v1.1_rec? When I use en_ppocr_mobile_v1.1_rec model for recognition with en_dict.txt it gives this error
```
direct_conv_trans_weights<(paddle::lite_api::PrecisionType)2, (paddle::lite_api::PrecisionType)1>] Check failed: w_scale.size() == 1 || w_scale.size() == oc: weights scale size must = filter size or = 1
2021-03-23 10:41:26.667 20567-20653/com.demo.ocr A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 20653 (Predictor Worke), pid 20567 (com.demo.ocr)
```

**Comment by weidenbach** [comment]
@mrcnserkan I'm using the same as you, en_dict.txt.

**Comment by mrcnserkan** [comment]
Can you share your en_ppocr_mobile_v1.1_rec file with me? Actually I don't have a problem when I use ch_ppocr_mobile_v1.1_rec_opt.nb

**Comment by weidenbach** [comment]
Sure, here you go, hope it helps:
[en_ppocr_mobile_v1.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6187886/en_ppocr_mobile_v1.zip)

**Comment by mrcnserkan** [comment]
Thank you. I'll be trying.

**Comment by weidenbach** [comment]
> 
> 
> We pay close attention to the development of the official version of paddlelite2.8, and the paddleocr mobile demo will be released as soon as the official version of paddlelite2.8 is released.

I have searched through the docs and haven't found a new paddleocr mobile demo. It is not released yet right? Do you know when it will be available?

**Comment by weidenbach** [comment]
I have used the latest version of opt and the 2.0 models again to create the .nb models. Now I receive a different error regarding subgraph. Does anyone know what could be the issue? 
```
A/Paddle-Lite: [F  4/28 21:36:41.781 /island/Paddle-Lite/lite/core/program.cc RuntimeProgram:211] Check failed: (kernels.size() > 0): 0!>0 No kernels found for subgraph
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25018 (Predictor Worke), pid 24858 (com.artranslate)
```
