### ISSUE TITLE
100张 训练完的DB模型做检测时，mv骨干，训练前后检测结果完全无变化，可能是什么问题？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2305]
1. 样本过少？
2. 如果1成立，一般多少量级的图片能撬动已有平台给出的检测模型参数结果
3. 基过程是，训练采用 python tools/train.py， 然后 python tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.pretrained_model=./output/ch_db_mv3/best_accuracy Global.load_static_weights=False Global.save_inference_dir=./inference/det_db/ 生成推理模型
4. 请问问题可能出现在哪？如何debug?谢

**Comment by WenmuZhou** [comment]
可以试试检测你的训练集图片看看

**Comment by ymzx** [comment]
检测结果没问题，正常显示，就是训练前后，两个检测模型识别结果完全一样，连噪声都一模一样，没有任何变动，彷佛自己制作的训练集没起作用，模型参数完全没有收到影响。

**Comment by ymzx** [comment]
> 可以试试检测你的训练集图片看看

检测结果没问题，正常显示，就是训练前后，两个检测模型识别结果完全一样，连噪声都一模一样，没有任何变动，彷佛自己制作的训练集没起作用，模型参数完全没有收到影响。

**Comment by WenmuZhou** [comment]
你是finetune的？

**Comment by ymzx** [comment]
> 你是finetune的？

是的  我已经知道问题在哪了，谢谢您，修改为python tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.checkpoints=./output/ch_db_mv3/best_accuracy Global.load_static_weights=False Global.save_inference_dir=./inference/det_db/   即把Global.pretrained_model修改为Global.checkpoints即可，paddleocr说明文档可能需要修改下
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/inference.md#%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B%E8%BD%ACinference%E6%A8%A1%E5%9E%8B
![image](https://user-images.githubusercontent.com/29808550/111964971-288dba00-8b30-11eb-9102-95382643c723.png)

**Comment by ymzx** [comment]
Global.pretrained_model  按照paddle给出的配置文件 应该是存放骨干网络的预训练模型参数文件

**Comment by ymzx** [comment]
> Global.pretrained_model 按照paddle给出的配置文件 应该是存放骨干网络的预训练模型参数文件

![Uploading image.png…]()

**Comment by ymzx** [comment]
> Global.pretrained_model 按照paddle给出的配置文件 应该是存放骨干网络的预训练模型参数文件

![image](https://user-images.githubusercontent.com/29808550/111965539-cd0ffc00-8b30-11eb-9b99-7a4f3f71f761.png)

**Comment by WenmuZhou** [comment]
你这个配置文件看起来就是使用了一个imagenet的预训练模型，训练前后没变化，是不是你predict的模型用的是一样的

**Comment by ymzx** [comment]
> 你这个配置文件看起来就是使用了一个imagenet的预训练模型，训练前后没变化，是不是你predict的模型用的是一样的

嗯 本质上是这个原因，导致这个原因是因素就是如上所述。
