### ISSUE TITLE
串联推理出的中文乱码

### ISSUE THREAD

**Issue by sifanlook** [PaddlePaddle/PaddleOCR#2314]
训练的检测模型 识别模型单独使用都没问题，导出inference串联推理就各种问题，竟然是中文乱码
我都是纯英文图片，请问什么原因？急！！！！！！！！

**Comment by sifanlook** [comment]
![捕获2](https://user-images.githubusercontent.com/21136881/111969310-0ba7b580-8b35-11eb-97b7-859963ca80c3.JPG)
![捕获3](https://user-images.githubusercontent.com/21136881/111969316-0f3b3c80-8b35-11eb-906d-df1017e0efc2.JPG)

**Comment by sifanlook** [comment]
![Uploading 捕获1.JPG…]()

**Comment by sifanlook** [comment]
![捕获1](https://user-images.githubusercontent.com/21136881/111969385-237f3980-8b35-11eb-99dd-b07f02a61d7f.JPG)

**Comment by sifanlook** [comment]
识别预训练模型：en_ppocr_mobile_v1.1_rec_train.tar
检测预训练模型：ch_ppocr_mobile_v1.1_rec_pre.tar

**Comment by sifanlook** [comment]
[ic15_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6181044/ic15_dict.txt)

**Comment by lexiaoyuan** [comment]
串联推理时，命令加上`--rec_char_dict_path='ppocr/utils/ic15_dict.txt'`指定字典路径再试试。

**Comment by littletomatodonkey** [comment]
你用的是英文的模型，需要指定英文的字典
