### ISSUE TITLE
只finetune的识别模型，检测模型不变，串联推理的时候漏检很多

### ISSUE THREAD

**Issue by xiaomore** [PaddlePaddle/PaddleOCR#2315]
请问一下：
我自己生成了一些数据集，只训练了识别模型（在ch_ppocr_server_v2.0_rec_pre的基础上进行finetune）字典文件替换为我自己的，但是训练完之后，只用检测模型推理（ch_ppocr_server_v2.0_det_infer）没问题，但是把检测和新训练的识别模型放在一起推理，就会漏检很多文本了。具体的例子如下图，请帮忙分析一下是我哪里操作的有问题呢？感谢~~

图1. 只使用中文通用检测模型推理
![只使用中文通用检测模型推理](https://user-images.githubusercontent.com/33802586/111974851-df8f3300-8b3a-11eb-84c9-fa40c109bcb4.png)

图2. 使用中文通用检测模型和我finetune的识别模型串行推理
![使用中文通用检测模型和我finetune的识别模型串行推理](https://user-images.githubusercontent.com/33802586/111974985-06e60000-8b3b-11eb-9bd2-3a3db0c6b1c5.png)

**Comment by littletomatodonkey** [comment]
可以把这个值设置为0.0，看下是否有漏检的情况，还是说识别得分太低了

https://github.com/PaddlePaddle/PaddleOCR/blob/006751614253159aa6b3eb74fd5fd82e5dccb8ba/tools/infer/utility.py#L76

**Comment by xiaomore** [comment]
> 可以把这个值设置为0.0，看下是否有漏检的情况，还是说识别得分太低了
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/006751614253159aa6b3eb74fd5fd82e5dccb8ba/tools/infer/utility.py#L76

您好，感谢回复~
我把参数--drop_score设置成了0.0，进行检测和识别一起推理，仍有少量文本行漏检，如下图，
![image](https://user-images.githubusercontent.com/33802586/112097680-685dab80-8bdb-11eb-983a-fdaa2e43782a.png)


识别依然很差，我在训练识别模型的时候，主要做的改动有：
1. 使用PaddleOCR提供的通用中文预训练模型：pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
2. 更换了这个字典（ppocr/utils/ppocr_keys_v1.txt）成我自己的；
3. 使用的配置文件是rec_chinese_common_train_v2.0.yml，修改了image_shape: [3, 32, 280]，因为我的训练集图片是280*32的。
请帮忙分析下，漏检的情况和识别结果差的情况。

**Comment by Luffffffy** [comment]
你好，关于你说 “在ch_ppocr_server_v2.0_rec_pre的基础上进行finetune”

我想请教一下 ch_ppocr_server_v2.0_det_train 的文字检测的训练模型是不是不能finetune啊？
我试过好像只能finetune  ResNet 原始的模型版本
但是你说的这个文字识别的 预训练模型就是可以finetune
是我哪里理解错了吗，我是下载的这个两个模型，目前只尝试finetune第一个
![image](https://user-images.githubusercontent.com/49063302/123078148-44fe0300-d44d-11eb-9a3c-843e26b4b72f.png)
我猜想不成功的原因是因为“模型名称后缀名的区别，包含 _pre的可能才能finetun”
问题是，去哪里下载可以finetune的文字检测模型呢
回复感激不尽，谢谢！！！

**Comment by sifanlook** [comment]
> 你好，关于你说 “在ch_ppocr_server_v2.0_rec_pre的基础上进行finetune”
> 
> 我想请教一下 ch_ppocr_server_v2.0_det_train 的文字检测的训练模型是不是不能finetune啊？
> 我试过好像只能finetune ResNet 原始的模型版本
> 但是你说的这个文字识别的 预训练模型就是可以finetune
> 是我哪里理解错了吗，我是下载的这个两个模型，目前只尝试finetune第一个
> ![image](https://user-images.githubusercontent.com/49063302/123078148-44fe0300-d44d-11eb-9a3c-843e26b4b72f.png)
> 我猜想不成功的原因是因为“模型名称后缀名的区别，包含 _pre的可能才能finetun”
> 问题是，去哪里下载可以finetune的文字检测模型呢
> 回复感激不尽，谢谢！！！

这个问题太久远了，我都忘了当时的情况了
检测模型和识别模型都是可以finetun的，我今天就训练了一版，按照文档一步步配置就能成功训练！

**Comment by Luffffffy** [comment]
![image](https://user-images.githubusercontent.com/49063302/123083036-3b2ace80-d452-11eb-8374-d503ad7bc493.png)

再次感谢回复！！！
训练倒是可以训练，但是测试的效果非常非常差。。。
具体表现在检测不到图片上的文字框

**Comment by sifanlook** [comment]
这要看你训练集大不大，训练精度precision有没有训练的很高，高了自然就能检测到框了

**Comment by sifanlook** [comment]
> ![image](https://user-images.githubusercontent.com/49063302/123083036-3b2ace80-d452-11eb-8374-d503ad7bc493.png)
> 
> 再次感谢回复！！！
> 训练倒是可以训练，但是测试的效果非常非常差。。。
> 具体表现在检测不到图片上的文字框

还有如果训练集太少，最终训练出的模型会过拟合到你训练集那一类的图片上，造成模型对普通图片识别效果很差，这个跟你说一下避免踩坑

**Comment by Luffffffy** [comment]
> 这要看你训练集大不大，训练精度precision有没有训练的很高，高了自然就能检测到框了

感谢解答，那我再加大力度试试
具体我还有一个疑问，关于文字检测finetune模型的下载
我看过一些别人的issue，从以下截图下载的finetune模型都有
我想。。。应该都有点问题，不然为什么会提issue呢。。。

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/algorithm_overview.md
![image](https://user-images.githubusercontent.com/49063302/123084579-e2f4cc00-d453-11eb-9c87-7245784364b3.png)

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md
![image](https://user-images.githubusercontent.com/49063302/123084812-28b19480-d454-11eb-9222-110b4c5d7da9.png)

**Comment by Luffffffy** [comment]
> > ![image](https://user-images.githubusercontent.com/49063302/123083036-3b2ace80-d452-11eb-8374-d503ad7bc493.png)
> > 再次感谢回复！！！
> > 训练倒是可以训练，但是测试的效果非常非常差。。。
> > 具体表现在检测不到图片上的文字框
> 
> 还有如果训练集太少，最终训练出的模型会过拟合到你训练集那一类的图片上，造成模型对普通图片识别效果很差，这个跟你说一下避免踩坑

好的，感谢提醒，我的训练集大概有2100张同场景的图片

**Comment by shinefy** [comment]
请问解决了吗，遇到了相似的问题
