### ISSUE TITLE
安装第三方库pip3 install -r requirements.txt时报错

### ISSUE THREAD

**Issue by freedomst82** [PaddlePaddle/PaddleOCR#2316]
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting shapely
  Using cached Shapely-1.7.1-cp35-cp35m-manylinux1_x86_64.whl (1.0 MB)
ERROR: Could not find a version that satisfies the requirement scikit-image==0.17.2
ERROR: No matching distribution found for scikit-image==0.17.2

**Comment by freedomst82** [comment]
我找到别的指令可以安装了，看看能不能用

**Comment by NSLog-YuHaitao** [comment]
![image](https://user-images.githubusercontent.com/18722689/112089428-9b4c7300-8bcc-11eb-9182-d24ff14a54b1.png)
要满足这个条件

**Comment by littletomatodonkey** [comment]
建议使用python3.6/3.7，python3.5对于有些whl包的兼容性不是很好哈

**Comment by bswhb** [comment]
@freedomst82 我现在使用paddle的docker container安装，也遇到这个问题，看起来是因为里面内置了3.5的python，想问一下你这边后来是怎么安装成功的？谢谢
