### ISSUE TITLE
SRNRecResizeImg配置缺少num_heads

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2317]
```
class SRNRecResizeImg(object):
    def __init__(self, image_shape, num_heads, max_text_length, **kwargs):
```
这个地方有一个num_heads
但是配置文件缺少这个参数
- SRNRecResizeImg:
          image_shape: [1, 64, 256]

**Comment by tink2123** [comment]
在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/006751614253159aa6b3eb74fd5fd82e5dccb8ba/configs/rec/rec_r50_fpn_srn.yml#L21
