### ISSUE TITLE
v2.0.0的文本检测算法有大问题！！！v1.0.0的检测效果远远好于v2.0.0，如下图分别为新旧图检测效果！！！

### ISSUE THREAD

**Issue by Doubledongli** [PaddlePaddle/PaddleOCR#2318]
![202103201100031](https://user-images.githubusercontent.com/20540661/112106453-a6150100-8be8-11eb-858f-e504d20494ba.png)
![big2](https://user-images.githubusercontent.com/20540661/112106540-c775ed00-8be8-11eb-85a5-cc53c70af509.png)
![big1](https://user-images.githubusercontent.com/20540661/112106559-cd6bce00-8be8-11eb-88f2-5235ad2dfb88.png)

如上图，从上往下分别为原图，v2.0.0检测结果，v1.0.0检测结果，很明显，v2.0.0检测结果好多都漏掉了！

**Comment by Doubledongli** [comment]
问题发现后请联系我：double_dongli@foxmail.com

**Comment by singlebear** [comment]
![Snipaste_2021-03-23_16-29-11](https://user-images.githubusercontent.com/48552037/112116218-027e1d80-8bf5-11eb-8de6-2b70e3dd89d0.jpg)
建议多找找自己代码和设置的问题，我用的就是2.0的模型

**Comment by Doubledongli** [comment]
@singlebear 大佬，我是按照文档配置的，没发现哪里有问题，请指点

**Comment by Doubledongli** [comment]
> 懒得和你解释怎么设

求大佬指点

**Comment by Doubledongli** [comment]
问题已发现：1、未加入方向模型，2、没有直接git clone代码，而是下载的打包的源码

**Comment by latawangzi** [comment]
> 问题已发现：1、未加入方向模型，2、没有直接git clone代码，而是下载的打包的源码

git clone 和下载的差别大么？

**Comment by yuansky** [comment]
我也遇见了和楼主一样的问题。。。。谁能救救孩子啊，求求各位大佬了

**Comment by yuansky** [comment]
> ![Snipaste_2021-03-23_16-29-11](https://user-images.githubusercontent.com/48552037/112116218-027e1d80-8bf5-11eb-8de6-2b70e3dd89d0.jpg) 我用的就是2.0的模型，建议多找找自己代码和设置的问题，别一有问题就先觉得是别人有问题。你这标题直接定个性是2.0版本有问题，还一堆感叹号，看着神烦，作为路人就回你个图，也懒得和你解释怎么设置。

大哥大哥，能跟我说一下怎么做的么，跪谢了。。。
