### ISSUE TITLE
训练模型的时候，数据reader进程会死掉

### ISSUE THREAD

**Issue by aceyw** [PaddlePaddle/PaddleOCR#232]
我训练识别模型 到时候，reader进程数量是8个或者4个，但是进程会死掉。
刚才修改成了2个，后才注意到一条日志“place would be ommited when DataLoader is not iterable”。

reader死掉，导致无法训练。这个问题比较着急，请帮忙解决一下，谢谢

**Comment by LDOUBLEV** [comment]
> 我训练识别模型 到时候，reader进程数量是8个或者4个，但是进程会死掉。
> 刚才修改成了2个，后才注意到一条日志“place would be ommited when DataLoader is not iterable”。
> 
> reader死掉，导致无法训练。这个问题比较着急，请帮忙解决一下，谢谢

你是否是改了代码或者更换了数据，数据格式是否是符合icdar的数据标注格式？建议发完整的报错信息，如果有更改的地方也提出来，方便排查问题

**Comment by aceyw** [comment]
是icdar的数据格式，公开的360多万的文档文本数据，是识别模型数据。没有任何错误信息或日志，没有通知，读取数据的进程变成了exit状态。我们是发现GPU使用率降低了，才能知道进程挂了。

**Comment by aceyw** [comment]
使用的不是lmdb，是simple的读取文件的方式。

**Comment by LDOUBLEV** [comment]
> 是icdar的数据格式，公开的360多万的文档文本数据，是识别模型数据。没有任何错误信息或日志，没有通知，读取数据的进程变成了exit状态。我们是发现GPU使用率降低了，才能知道进程挂了。

发一下你的执行命令

**Comment by aceyw** [comment]
crnn-atten crnn-ctc cnn-ctc在不同的文件夹下面都尝试过训练，例如，
CUDA_VISIBLE_DEVICES=5 nohup python3 -u tools/train.py \
                            -c configs/rec/rec_mv3sm_none_bilstm_ctc__chn5989.yml \
                            -o Global.print_batch_step=1000 \
                            Global.epoch_num=2000 \
                            Global.save_epoch_step=20 \
                            Global.eval_batch_step=2000 \
                            Global.train_batch_size_per_card=256 \
                            Global.test_batch_size_per_card=128 \
                            Global.use_gpu=true \
                            > log.rec_mv3sm_none_bilstm_ctc_chn5989 &

**Comment by aceyw** [comment]
rec_mv3sm_none_bilstm_ctc__chn5989.yml 是根据rec_chinese_lite_train.yml进行的修改，修改了图片尺寸和数据路径等。

**Comment by tink2123** [comment]
请问训练使用的是哪个配置，您的机器显存是多少？

**Comment by tink2123** [comment]
是在训练开始就会挂掉，还是在训练一段时间后挂掉呢？

**Comment by aceyw** [comment]
8卡的显存，这个实例使用的是卡号5，每个卡是32G。模式使用了不超过11个G

**Comment by aceyw** [comment]
训练一段时间后挂的

**Comment by aceyw** [comment]
数据加载，有个LMDBReader，有个SimpleReader。
你们使用SimpleReader进行过完整的训练吗、出现过类似问题吗？

**Comment by tink2123** [comment]
我们中文模型是使用SimpleReader进行完整训练的，可以先将num_workers修改为1，看问题是否还会出现。
> 修改了图片尺寸
是修改到了多少呢，如果shape比较大的话，也可以减小batch_size试试

**Comment by aceyw** [comment]
我使用的是这个数据集：

4、中文文档文字识别
数据来源：https://github.com/YCG09/chinese_ocr
数据简介：
共约364万张图片，按照99:1划分成训练集和验证集。
数据利用中文语料库（新闻 + 文言文），通过字体、大小、灰度、模糊、透视、拉伸等变化随机生成
包含汉字、英文字母、数字和标点共5990个字符（字符集合：https://github.com/YCG09/chinese_ocr/blob/master/train/char_std_5990.txt ）
每个样本固定10个字符，字符随机截取自语料库中的句子
图片分辨率统一为280x32

**Comment by aceyw** [comment]
修改成了icdar2015的标签格式，字符集文件也修改了、去掉了最前面的空格

**Comment by aceyw** [comment]
你们使用过这个数据集进行训练吗？是数据太多了吗？ 我之前自己生成的40万数据，也是这种reader挂掉的问题。

**Comment by tink2123** [comment]
没有使用过这个数据集训练，中文模型训练时我们尝试过1000w的数据量，没有挂掉。可以先将进程数修改为1，我这边也会试一下训练这个公开数据集。

**Comment by aceyw** [comment]
嗯，谢谢，尽快哈
我试过train_reader的进程数为1，还是挂。
我现在使用3万的子样本在训练，再看看。
另外，我准备吧batch改成64，再启动一个训练试试。

**Comment by aceyw** [comment]
改成64的也是还不行

**Comment by tink2123** [comment]
可以提供一下环境吗？
1）PaddlePaddle版本：
2）GPU：GPU型号，CUDA版本号，CUDNN版本号
3）系统：
4）docker镜像：
5）Python版本号:

**Comment by aceyw** [comment]
paddlepaddle-gpu==1.7.2.post10.7
GPU：    Tesla V100， 驱动版本410.79， CUDA版本10.0。 8卡，每个卡是32G
Centos7.3.1611
没有docker，用不了docker
Python 3.6.6，使用的virtualenv的虚拟环境

**Comment by peif1987** [comment]
@aceyw 你解决这个问题了吗？我用自己合成的数据训练，也遇到了一样的问题，内存会一直增长，即使把num_workers改成1, 还有reader_main里的queue_size从默认的1000改成32了都不行

**Comment by littletomatodonkey** [comment]
可以试着拉下最新代码，同时升级Paddle为2.0.0rc试下哈

**Comment by Hupengyu** [comment]
> paddlepaddle-gpu==1.7.2.post10.7
> GPU： Tesla V100， 驱动版本410.79， CUDA版本10.0。 8卡，每个卡是32G
> Centos7.3.1611
> 没有docker，用不了docker
> Python 3.6.6，使用的virtualenv的虚拟环境
为什么用不了docker?
