### ISSUE TITLE
how can we sort bounding box coordinates in the order of appearance in image (from left to right and top to bottom) for invoice ocr

### ISSUE THREAD

**Issue by alenma04** [PaddlePaddle/PaddleOCR#2321]

**Comment by alenma04** [comment]
Hi,
how can we sort bounding box coordinates in the order of appearance in image (from left to right and top to bottom)  for invoice ocr

**Comment by MissPenguin** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/d3a4f788646efd4a3084f5a9807b679177fadfcd/tools/infer/predict_system.py#L96

**Comment by alenma04** [comment]
Thanks for your reply @MissPenguin .Problem is default sorted_boxes function is failing to sort line by line when we have different fonts in same image.I need to sort bounding box coordinates to individual  lines.

**Comment by jey07** [comment]
Sortingis not a major issue. Paddle ocr already gives detection boxes with text. You can come up with your own sorting logic.
