### ISSUE TITLE
How can get OCR and BBox by word as opposed to sentences ? (Currently the OCR output and bboxes are for sentences)

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [PaddlePaddle/PaddleOCR#2322]

**Comment by PrithivirajDamodaran** [comment]
`[[[393.0, 340.0], [1207.0, 342.0], [1207.0, 389.0], [393.0, 387.0]], ['We would like to thank all the designers and', 0.9357758]]`

Instead of this how can i get word by word bbox. please advice.

**Comment by MissPenguin** [comment]
In training, annotation is the annotation of the whole text line, so the prediction is also the position of the text line. If you want to obtain the position information of a single character, you can calculate the number of characters according to the predicted text, and then estimate the position of each character in the text block according to the position information of the whole text line.

**Comment by PrithivirajDamodaran** [comment]
> In training, annotation is the annotation of the whole text line, so the prediction is also the position of the text line. If you want to obtain the position information of a single character, you can calculate the number of characters according to the predicted text, and then estimate the position of each character in the text block according to the position information of the whole text line.

Thanks. You suggest retraining with word by word annotation or just calculating the bboxes for word level from sentence predictions ?

**Comment by jey07** [comment]
You can either do post processing from the output or train the model with your annotated datatset( word by word)

**Comment by PrithivirajDamodaran** [comment]
> You can either do post processing from the output  to ge word by word or train the model with your annotated datasets( word by word)

@jey07 - Can you advice how do I get word by word Bbox from a prediction by post processing it ? See sample prediction below


[[[393.0, 340.0], [1207.0, 342.0], [1207.0, 389.0], [393.0, 387.0]], ['We would like to thank all the designers and', 0.9357758]]

**Comment by Akhilesh64** [comment]
@PrithivirajDamodaran were you able to achieve this ??
