### ISSUE TITLE
动态图版本训练一个epoch自动停止

### ISSUE THREAD

**Issue by robbiewongBD** [PaddlePaddle/PaddleOCR#2324]
在win下用动态图版本训练一个epoch自动停止，在linux就正常，用台式机、笔记本、2.0.0、2.0.1、cuda10.1/cuda10.2都是如此，调试发现是dataloader在最后一个iter会自动断掉，请问可能是什么原因呢？

**Comment by jimyho-msn** [comment]
我也遇到这个问题了。踩坑几天了。
![Train_11](https://user-images.githubusercontent.com/66407841/112436202-a6480480-8d80-11eb-88cf-d1c2df3fdfa2.png)
我的训练怎么老是在这里就出来了，没有报错，也没有模型生成，不管是cpu 还是 gpu 版本
正常应该有save model 的输出
![Train_21](https://user-images.githubusercontent.com/66407841/112436635-e5765580-8d80-11eb-96db-883b607b4b42.jpg)

**Comment by robbiewongBD** [comment]
> 我也遇到这个问题了。踩坑几天了。
> ![Train_11](https://user-images.githubusercontent.com/66407841/112436202-a6480480-8d80-11eb-88cf-d1c2df3fdfa2.png)
> 我的训练怎么老是在这里就出来了，没有报错，也没有模型生成，不管是cpu 还是 gpu 版本
> 正常应该有save model 的输出
> ![Train_21](https://user-images.githubusercontent.com/66407841/112436635-e5765580-8d80-11eb-96db-883b607b4b42.jpg)

我debug发现是dataloader的最后一个iter会失败，但是在Linux下就没问题

**Comment by JescalLin** [comment]
@robbiewongBD 

試試這個 tools/program.py

if idx >= len(train_dataloader):
break
#把上面这句话修改成下面这个
if idx >= len(train_dataloader)-1:
break

**Comment by mikeshi80** [comment]
这个是一个bug，具体参见  https://github.com/PaddlePaddle/PaddleOCR/issues/2274

**Comment by mikeshi80** [comment]
> @robbiewongBD
> 
> 試試這個 tools/program.py
> 
> if idx >= len(train_dataloader):
> break
> #把上面这句话修改成下面这个
> if idx >= len(train_dataloader)-1:
> break

好巧，几乎同时回答，哈哈

**Comment by jimyho-msn** [comment]
谢谢上面几位。
怪不得没几个人遇到，我也是用 cuda11

**Comment by robbiewongBD** [comment]
好神奇真的可以，不过我的是cuda10.2，也这样解决了，之前觉得这里有问题，但是是直接注释掉，并没有用减1，直接注释并没有用。
