### ISSUE TITLE
ch_ppocr_mobile_v2.0_rec trained model 文件不全

### ISSUE THREAD

**Issue by yxd117** [PaddlePaddle/PaddleOCR#2326]
从这里下载的 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_train.tar 
解压缩完 只有best_accuracy.pdparams 没有办法 evaluate

`ch_ppocr_mobile_v2.0_rec_train/best_accuracy.pdopt not exist.`

**Comment by MissPenguin** [comment]
使用pretrained_model参数加载模型就可以的哈，-o Global.pretrained_model，不要用checkpoints，我们优化下文档

**Comment by yxd117** [comment]
多谢改成这个就可以eval了, 还有个问题 在icdar2015 dataset 上面eval performance 很差， 用了server 也是, 你们有试过吗
`[2021/03/24 20:19:33] root INFO: metric eval ***************
[2021/03/24 20:19:33] root INFO: acc:0.05247953779489649
[2021/03/24 20:19:33] root INFO: norm_edit_dis:0.22870624101825765
[2021/03/24 20:19:33] root INFO: fps:492.15801380698014`

**Comment by MissPenguin** [comment]
> 多谢改成这个就可以eval了, 还有个问题 在icdar2015 dataset 上面eval performance 很差， 用了server 也是, 你们有试过吗
> 
> ```
> [2021/03/24 20:19:33] root INFO: metric eval ***************
> [2021/03/24 20:19:33] root INFO: acc:0.05247953779489649 
> [2021/03/24 20:19:33] root INFO: norm_edit_dis:0.22870624101825765
> [2021/03/24 20:19:33] root INFO: fps:492.15801380698014
> ```

没有用icdar2015测试过，不过指标低也比较合理，icdar都是自然场景，比较难，没有针对性训练。可以用“算法介绍”中的模型验证评估是否能对齐
