### ISSUE TITLE
SRN中文识别训练

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2327]
配置文件和configs里给的一致
数据集用的LSVT（20+w）和生成数据（300W），还有一些根据应用场景生成的一部分数据，取样后三者大概是1:2:1
这三个数据集在CRNN+CTC模型能在训练集达到91%acc（不过拟合的时候大概是85）
然后用SRN进行训练，训练了差不多两天，训练集acc稳定在0~2/64，整体loss 1k左右，验证集acc 0.005上下，想询问下有可能是什么原因

**Comment by MissPenguin** [comment]
srn的配置文件是训练英文的，要训练中文的话需要改一下，可以对照crnn的中文训练的config修改
