### ISSUE TITLE
OSError: (External)  Cuda error(3), initialization error

### ISSUE THREAD

**Issue by ByronGe** [PaddlePaddle/PaddleOCR#2329]
单进程下运行没问题，多进程报了如此错误OSError: (External)  Cuda error(3), initialization error
![2021-03-24 20-41-14屏幕截图](https://user-images.githubusercontent.com/29230326/112312160-785fb300-8ce1-11eb-8f6e-fe61e5aa773d.png)

**Comment by MissPenguin** [comment]
目前多进程预测是有点问题，正在修复中了，先用单进程吧。。

**Comment by ByronGe** [comment]
好的，谢谢

**Comment by daixiangzi** [comment]
> 好的，谢谢

找到该问题的解决方式没有
