### ISSUE TITLE
Paddle Serving 服务部署 启动服务时出错

### ISSUE THREAD

**Issue by mathser123** [PaddlePaddle/PaddleOCR#2332]
我是使用windows python3.7 CPU 服务部署
Step 3.1
(base) C:\Users\3004385\PaddleOCR-develop\deploy\pdserving>python det_local_server.py
C:\Users\3004385\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\config.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
This API will be deprecated later. Please do not use it
This API will be deprecated later. Please do not use it
web service address:
http://10.136.39.63:9292/ocr/prediction
This API will be deprecated later. Please do not use it
 * Serving Flask app "paddle_serving_server.web_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Step3.2 
(base) C:\Users\3004385\PaddleOCR-develop\deploy\pdserving>python ocr_local_server.py
C:\Users\3004385\AppData\Local\Continuum\anaconda3\lib\site-packages\markupsafe\__init__.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
Traceback (most recent call last):
  File "ocr_local_server.py", line 27, in <module>
    from paddle_serving_app.local_predict import Debugger
ImportError: cannot import name 'Debugger' from 'paddle_serving_app.local_predict' (C:\Users\3004385\AppData\Local\Continuum\anaconda3\lib\site-packages\paddle_serving_app\local_predict.py)

**Comment by MissPenguin** [comment]
静态图模型的话用hub serving吧，静态图的paddle serving容易出问题，现在也不太维护了。动态图模型的话，hub serving和paddle serving都可以

**Comment by mathser123** [comment]
> 静态图模型的话用hub serving吧，静态图的paddle serving容易出问题，现在也不太维护了。动态图模型的话，hub serving和paddle serving都可以

好的，非常感谢你的建议！

**Comment by mathser123** [comment]
> 静态图模型的话用hub serving吧，静态图的paddle serving容易出问题，现在也不太维护了。动态图模型的话，hub serving和paddle serving都可以

另外请问一下hubserving 使用的时候为什么延迟会很高呢，一张有6秒延迟

**Comment by MissPenguin** [comment]
> > 静态图模型的话用hub serving吧，静态图的paddle serving容易出问题，现在也不太维护了。动态图模型的话，hub serving和paddle serving都可以
> 
> 另外请问一下hubserving 使用的时候为什么延迟会很高呢，一张有6秒延迟

mobile模型还是server模型，cpu还是gpu呢？一般第一张图延迟会比较高，和直接inference推理耗时一致

**Comment by mathser123** [comment]
> > > 静态图模型的话用hub serving吧，静态图的paddle serving容易出问题，现在也不太维护了。动态图模型的话，hub serving和paddle serving都可以
> > 
> > 
> > 另外请问一下hubserving 使用的时候为什么延迟会很高呢，一张有6秒延迟
> 
> mobile模型还是server模型，cpu还是gpu呢？一般第一张图延迟会比较高，和直接inference推理耗时一致

我是server模型 cpu ，每张图的延迟都是6秒左右

**Comment by MissPenguin** [comment]
cpu跑server模型是会比较慢，建议用mobile，或者server+gpu

**Comment by mathser123** [comment]
> cpu跑server模型是会比较慢，建议用mobile，或者server+gpu
非常感谢！
请问并发性能怎么样呢，我多个客户端的时候会有排队现象。比如一个客户端6秒一张，两个客户端同时访问，第二个客户端可能就要12秒一张

**Comment by mathser123** [comment]
> cpu跑server模型是会比较慢，建议用mobile，或者server+gpu


非常感谢！
请问并发性能怎么样呢，我多个客户端的时候会有排队现象。比如一个客户端6秒一张，两个客户端同时访问，第二个客户端可能就要12秒一张

**Comment by MissPenguin** [comment]
hub serving并发支持的不好，可以用paddle serving，支持动态图模型部署的paddle serving在dygraph分支
