### ISSUE TITLE
为什么你门测的结果和相关论文官方给的不太一样？比如EAST，DB

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/PaddleOCR#234]
好奇你们怎么把EAST提上去的？DB使用是有测不同分辨率的情况吗
![image](https://user-images.githubusercontent.com/18586273/85094053-6025a980-b220-11ea-8f90-56ba35b0d190.png)
![image](https://user-images.githubusercontent.com/18586273/85094085-759ad380-b220-11ea-919f-6611ebc209c6.png)

**Comment by MissPenguin** [comment]
EAST提升可能是因为backbone换了resnet50vd，不是标准的resnet50，另外有些细节不一样，但我们没有做详细的消融实验；
DB指标的测试尺度是736*1280，比论文指标低有2个原因：1，论文使用了dcn模块，我们还没加这个；2、论文先在vgg80w合成数据上训练，然后在icdar2015上finetune，而我们没有使用合成数据，直接用icdar2015训的

**Comment by xxllp** [comment]
都是坑 细微的差别这么大嘛
