### ISSUE TITLE
Image properties for paddle ocr

### ISSUE THREAD

**Issue by jey07** [PaddlePaddle/PaddleOCR#2340]
Does paddle ocr  has any threshold like below for image quality?

"brightness" : 119.78944967576575,
                        "blur" : 667.688303305511,
                        "contrast" : 63.9889243548327,
                        "saturation" : 40.40709306429385,
                        "noise" : 0.40759676786756344,
                        "dimension" : {
                         "height" : 728,
                         "width" : 546}

**Comment by MissPenguin** [comment]
No. PaddleOCR focus on text detection and recognition.😁
