### ISSUE TITLE
windows下shapely库安装问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2341]
您好，我看到readme中有shapely库安装的方法，我根据链接地址下载了这个文件，请问这个如何安装？
![image](https://user-images.githubusercontent.com/43515926/112457118-67bd4480-8d96-11eb-806e-23fa2798bae3.png)

**Comment by MissPenguin** [comment]
pip3 install *.whl

**Comment by zcswdt** [comment]
> pip3 install *.whl

我这样安装了还是一样的报错

**Comment by zcswdt** [comment]
> pip3 install *.whl
您好，在windows下使用cpu推理还是报如下的错误。
![image](https://user-images.githubusercontent.com/43515926/112565142-831c6400-8e17-11eb-9b7a-003c3f94c962.png)

**Comment by zcswdt** [comment]
> pip3 install *.whl

python进入解释器，输入`Import shapely`并不报错，但是输入`from shapely.geometry import Polygon`就会报错。
![image](https://user-images.githubusercontent.com/43515926/112565437-01790600-8e18-11eb-82ff-bb3f177e64e2.png)

**Comment by zcswdt** [comment]
> > pip3 install *.whl
> 
> python进入解释器，输入`Import shapely`并不报错，但是输入`from shapely.geometry import Polygon`就会报错。
> ![image](https://user-images.githubusercontent.com/43515926/112565437-01790600-8e18-11eb-82ff-bb3f177e64e2.png)



> > pip3 install *.whl
> 
> python进入解释器，输入`Import shapely`并不报错，但是输入`from shapely.geometry import Polygon`就会报错。
> 
> ![image](https://user-images.githubusercontent.com/43515926/112565437-01790600-8e18-11eb-82ff-bb3f177e64e2.png)

已经解决，卸载重新装就好了，应该是之前使用Pip安装了，然后在下载安装包来安装没有覆盖掉Pip安装的。
