### ISSUE TITLE
在angular7-10的项目里可以使用PaddleOCR吗？如果可以的话要怎么使用？如果可以的话可以贴一个使用教程link吗？

### ISSUE THREAD

**Issue by liuna471658955** [PaddlePaddle/PaddleOCR#2343]
麻烦问下我想在前端angular工程里使用PaddleOCR要怎么使用？我的angular是跑在PC浏览器里的，请问有没有跑在PC浏览器教程链接啊？谢谢

**Comment by JimReno** [comment]
刚clone代码跑了一下，代码仓库中的/depoly/hubserving文件夹下有部署检测服务的实践教程，大佬们已经用flask部署好了服务，可以直接通过post方法请求的，post的用例可以在tools/hubserving.py中找到，在“发送HTTP请求下面，就是实际的用例”。
没实践过，但感觉这样应该能行，希望能帮到你哈

**Comment by liuna471658955** [comment]
@JimReno 你好，我是想在前端项目中直接调用模型来识别文字，但是找了好久也没有找到例子，我并不想要发post请求到其他地方来获取服务，请问您上面说的这种方法可以实现吗？谢谢

**Comment by liuna471658955** [comment]
@bikerr 是的我看到有paddlejs但是他们官方没有提供相关的使用文档，并不知道要怎么用，请问您知道相关的信息吗？或者是有没有paddlejs相关人员的联系方式我想询问一下？
