### ISSUE TITLE
How to suppress those "root INFO:" logging?

### ISSUE THREAD

**Issue by mo-han** [PaddlePaddle/PaddleOCR#2348]
```
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
[2021/03/26 14:29:17] root INFO: dt_boxes num : 0, elapse : 0.960580587387085
[2021/03/26 14:29:17] root INFO: rec_res num  : 0, elapse : 0
[2021/03/26 14:29:18] root INFO: dt_boxes num : 0, elapse : 1.3157596588134766
[2021/03/26 14:29:18] root INFO: rec_res num  : 0, elapse : 0
[2021/03/26 14:29:20] root INFO: dt_boxes num : 0, elapse : 0.8542914390563965
[2021/03/26 14:29:20] root INFO: rec_res num  : 0, elapse : 0
[2021/03/26 14:29:21] root INFO: dt_boxes num : 2, elapse : 0.9476561546325684
[2021/03/26 14:29:21] root INFO: rec_res num  : 2, elapse : 0.050711870193481445
F
[2021/03/26 14:29:22] root INFO: dt_boxes num : 3, elapse : 0.9637429714202881
[2021/03/26 14:29:22] root INFO: rec_res num  : 3, elapse : 0.07630443572998047

[2021/03/26 14:29:23] root INFO: dt_boxes num : 4, elapse : 0.8289830684661865
[2021/03/26 14:29:23] root INFO: rec_res num  : 4, elapse : 0.12187695503234863
1C
[2021/03/26 14:29:25] root INFO: dt_boxes num : 5, elapse : 0.8632614612579346
[2021/03/26 14:29:25] root INFO: rec_res num  : 5, elapse : 0.1981816291809082
2
Delete
End
[2021/03/26 14:29:26] root INFO: dt_boxes num : 5, elapse : 0.814629077911377
[2021/03/26 14:29:26] root INFO: rec_res num  : 5, elapse : 0.16572332382202148
Delete
End
```

That is quite a mess in stdout, any way to make it quiet/silent?

**Comment by remyzane** [comment]
import logreset                                # pip install logging-reset
logreset.reset_logging()                 # before you logging setting

**Comment by mo-han** [comment]
> 
> 
> import logreset # pip install logging-reset
> logreset.reset_logging() # before you logging setting

Not working. I've already put these two lines at the top, which I tried last week when I saw your posted issue, failed then, and failed now again. The following message always show up:

```
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\mo-han/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
[2021/03/29 14:45:35] root INFO: dt_boxes num : 3, elapse : 0.9987108707427979
[2021/03/29 14:45:35] root INFO: rec_res num  : 3, elapse : 0.05867958068847656
[2021/03/29 14:45:37] root INFO: dt_boxes num : 3, elapse : 0.844285249710083
[2021/03/29 14:45:37] root INFO: rec_res num  : 3, elapse : 0.05870652198791504
[2021/03/29 14:45:38] root INFO: dt_boxes num : 1, elapse : 0.8029294013977051
[2021/03/29 14:45:38] root INFO: rec_res num  : 1, elapse : 0.013962984085083008
[2021/03/29 14:45:39] root INFO: dt_boxes num : 1, elapse : 0.86393141746521
[2021/03/29 14:45:39] root INFO: rec_res num  : 1, elapse : 0.028530359268188477
```

**Comment by Jtao0818** [comment]
in：paddleocr>tools>infer>predict_system.py
Line91:      # logger.info("dt_boxes loggernum : {}, elapse : {}".format(
                 #    len(dt_boxes), elapse))
Line110:    # logger.info("rec_res num  : {}, elapse : {}".format(
                 #     len(rec_res), elapse))

**Comment by stevenwalton** [comment]
I'm getting similar results. The output is extremely noisy. Using `logreset` as suggested above does nothing. It would be nice if this were incorporated into the pypy version, maybe with a logging or debug option when you call PaddleOCR (e.g. `ocr = PaddleOCR(lang=lang, debug=False)`, preferably debug would default to false).

**Comment by liut0012** [comment]
`PaddleOCR(show_log = False)` works for me

**Comment by sharmas1ddharth** [comment]
> `PaddleOCR(show_log = False)` works for me

Thank you so much @liut0012

**Comment by 1ravikumar2001** [comment]
Thank You So much @liut0012 

> `PaddleOCR(show_log = False)` works for me

**Comment by mohblnk** [comment]
> `PaddleOCR(show_log = False)` works for me

it still outputs warnings, is there is a way to completely shut it off ?

**Comment by CrashTechnologyOfficer** [comment]
After some research,
The logger's configuration can be found at:  https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppocr/utils/logging.py
so you can change it after ```PaddleOCR(use_angle_cls=False, lang=lang, show_log=False)```
You can change the logger's settings after initializing PaddleOCR with:
```
logging.getLogger('ppocr').handlers = []
```
Alternatively you can set the level:
```
logging.getLogger('ppocr').setLevel(logging.ERROR)
```

**Comment by DimIsaev** [comment]
none of the solutions work
logging lines are duplicated

**Comment by SantiiRepair** [comment]
> `PaddleOCR(show_log = False)` works for me

Thank you mate

**Comment by rumanxyz** [comment]
Adding this disabled the paddleOCR log for more :
```
import logging
logging.disable(logging.DEBUG) 
```

**Comment by DimIsaev** [comment]
> Adding this disabled the paddleOCR log for more :
> 
> ```
> import logging
> logging.disable(logging.DEBUG) 
> ```

this is not a solution to the problem
i need to disable duplicate log output from Paddle
but not disable all logging

**Comment by DimIsaev** [comment]
> > `PaddleOCR(show_log = False)` works for me
> 
> Thank you mate

this not work

**Comment by liesvarastranta** [comment]
> After some research, The logger's configuration can be found at: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppocr/utils/logging.py so you can change it after `PaddleOCR(use_angle_cls=False, lang=lang, show_log=False)` You can change the logger's settings after initializing PaddleOCR with:
> 
> ```
> logging.getLogger('ppocr').handlers = []
> ```
> 
> Alternatively you can set the level:
> 
> ```
> logging.getLogger('ppocr').setLevel(logging.ERROR)
> ```

This one works nicely. 👍

**Comment by dongdk** [comment]
how to disable the warning, like this: `ppocr WARNING: Since the angle classifier is not initialized`?

**Comment by eatgreen** [comment]
> > Adding this disabled the paddleOCR log for more :
> > ```
> > import logging
> > logging.disable(logging.DEBUG) 
> > ```
> 
> this is not a solution to the problem i need to disable duplicate log output from Paddle but not disable all logging

i have exactly the same problem, following code works for me since i do not have a root logger handler

```
root = logging.getLogger()
root.handlers.clear() #paddleocr is hijacking the root handler, remove it!
```
