### ISSUE TITLE
It takes almost twice as long to train an SRN model with multiple GPUs

### ISSUE THREAD

**Issue by iKiYo** [PaddlePaddle/PaddleOCR#2349]
Hello, I was wondering if you could help me with the following.

As is: Even though multiple GPUs are recognized both in the VM instance itself and in the docker container, it takes almost twice as long to train the SRN model, and I get the following warnings. Also, I installed CUDA 10.1 on the VM instance itself, but the error shows Runtime as 10.0, which is not the correct version.

For a batch,
1 GPU time: 1.285
2 GPUs time: 2.122

W0310 07:50:18.594549 2240 device_context.cc:320] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0310 07:50:18.599908 2240 device_context.cc:328] device: 0, cuDNN Version: 7.6.
W0310 07:50:26.800444 2240 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 310. To make the speed faster, some all_reduce ops are fused To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 256.

To be: train SRN model on multiple GPUs correctly

Environment: 
GCP VM instance: ubuntu18.04
docker image: paddlepaddle/paddle:2.0.0-gpu-cuda10.1-cudnn7
nvcc 10.1.243
(on nvidia-smi command)
cuda version: 10.1
nvidia-driver:418.181.07

PaddleOCR: release/1.1 
paddlepaddle-gpu==2.0.0b0

To reproduce: 
I started training the SRN model with my own data using the following command

export CUDA_VISIBLE_DEVICES=0,1
python3 tools/train.py -c rec_srn_train.yml 2>&1 | tee train_rec.log

External Error nccl occurred　

![Screenshot from 2021-03-10 14-32-38](https://user-images.githubusercontent.com/33816000/112631625-767d2780-8e7a-11eb-80f6-90e26fee1af2.png)

I reinstalled nccl and started training the SRN model with my own data using the same command.
I got the following warnings before the training started. 
W0310 07:50:18.594549 2240 device_context.cc:320] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0310 07:50:18.599908 2240 device_context.cc:328] device: 0, cuDNN Version: 7.6.
W0310 07:50:26.800444 2240 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 310. To make the speed faster, some all_reduce ops are fused To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 256.

**Comment by tink2123** [comment]
It seems that your nccl and cuda are not installed correctly. It is recommended to train model in docker. Can other models be trained normally?

**Comment by tink2123** [comment]
After the installation is complete, you can use python or python3 to enter the Python interpreter and then use
```
import paddle
paddle.utils.run_check()
```
If  `PaddlePaddle is installed successfully! `  appears, to verify that the installation was successful.
