### ISSUE TITLE
这张图片完全识别不出来，是什么原因呢？一开始是一个大图片，这一段完全消失，后来单独截出这块图片，发现完全无法识别

### ISSUE THREAD

**Issue by hotthink** [PaddlePaddle/PaddleOCR#2353]
<img width="507" alt="微信图片_20210327213635" src="https://user-images.githubusercontent.com/33413908/112735418-c34e2480-8f86-11eb-8f76-ce16588f7aeb.png">

**Comment by hotthink** [comment]
描述的不正确，是下面的部分完全无法识别

<img width="506" alt="微信图片_20210327213756" src="https://user-images.githubusercontent.com/33413908/112735453-0d370a80-8f87-11eb-850c-f2ed73991ce8.png">

**Comment by hotthink** [comment]
上传到官方的页面上也完全无法识别，难道不是个bug吗？

**Comment by WenmuZhou** [comment]
在推理时，你需要调整一下参数det_db_box_thresh，把这个值调低一点，建议以后碰到这种问题了，先debug一下看看具体是什么原因
