### ISSUE TITLE
检测框高度相对字体真实高度偏窄，请问训练时候该调整什么参数？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2354]
问题：如题
检测模型：ch_det_mv3_db_v2.0.yml
![捕获](https://user-images.githubusercontent.com/29808550/112776966-8a3fae00-9073-11eb-8882-74c1452d1175.JPG)
不希望在预测试调整参数去避免该问题，希望能在训练阶段直接改善该现象。

**Comment by xxxpsyduck** [comment]
In my opinion, you should modify your train data instead

**Comment by caopulan** [comment]
调整配置文件PostProcess unclip_ratio，这个数值调大。
看上去除了中间两行略矮，其他行都是紧贴文本的，这个配置是用于调整检测后处理的边缘缩放的，调大一点会使检测框基于检测结果扩大

**Comment by ymzx** [comment]
> 调整配置文件PostProcess unclip_ratio，这个数值调大。
> 看上去除了中间两行略矮，其他行都是紧贴文本的，这个配置是用于调整检测后处理的边缘缩放的，调大一点会使检测框基于检测结果扩大

谢，但这个方法治标不治本，通过修改后处理参数会出现“拆东墙补西墙”的现象

**Comment by ymzx** [comment]
> In my opinion, you should modify your train data instead
3ks! 
I have checked my train data carefully. It's almost certain that my data is OK.  such as follow:
![微信图片_20210330111417](https://user-images.githubusercontent.com/29808550/112928427-32737680-9149-11eb-81c1-58a127f32ac6.png)

**Comment by caopulan** [comment]
> > In my opinion, you should modify your train data instead
> > 3ks!
> > I have checked my train data carefully. It's almost certain that my data is OK.  such as follow:
> > ![微信图片_20210330111417](https://user-images.githubusercontent.com/29808550/112928427-32737680-9149-11eb-81c1-58a127f32ac6.png)

这个训练集图片不是正说明了你的模型训练出来的就应该是紧贴文字的框吗，既然你的模型检测所有的文本都是紧贴文本的，那在后续处理之前统一一个扩大的因子来进行缩放应该就可以得到泛化的模型

**Comment by caopulan** [comment]
或者说想要直接改善就只能去对所有的训练集提前进行缩放，但实际上这时候你也需要一个“超参数”来控制训练集的缩放

**Comment by ymzx** [comment]
> 或者说想要直接改善就只能去对所有的训练集提前进行缩放，但实际上这时候你也需要一个“超参数”来控制训练集的缩放

已验证这个思路是可行的，该问题已解决。谢

**Comment by xxxpsyduck** [comment]
@ymzx please close the issue if it is resolved. Thanks.

**Comment by GUOhm230** [comment]
> > > In my opinion, you should modify your train data instead
> > > 3ks!
> > > I have checked my train data carefully. It's almost certain that my data is OK.  such as follow:
> > > ![微信图片_20210330111417](https://user-images.githubusercontent.com/29808550/112928427-32737680-9149-11eb-81c1-58a127f32ac6.png)
> 
> 这个训练集图片不是正说明了你的模型训练出来的就应该是紧贴文字的框吗，既然你的模型检测所有的文本都是紧贴文本的，那在后续处理之前统一一个扩大的因子来进行缩放应该就可以得到泛化的模型

您好，我最近也在做文档识别的，遇到了同样的问题。正好看着有答案，十分感谢，想确认一下：
1. 您解决该问题的时候，是针对训练图片进行边框放大对嘛？您设置的放大比例是多少呢？如果靠的很近的两行会不会导致出现误识别概率增加？
再请教一下，希望可以得到解答：
1.请问您是怎么解决文本弯曲的检测问题的？
2.如何解决长文本碎片化的问题？
3.识别中的空格问题，您是怎么解决的呢？
