### ISSUE TITLE
运行2.0.0版本c++ infer报错：未加载kernelbase.pdb

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleOCR#2355]
编译c++infer，环境：vs2017+cmake3.15+opencv346/vc14，可正常生成exe，但无法运行，应该是编译阶段出错（第一行代码也未运行），是什么原因？报错信息如下：
  
![image](https://user-images.githubusercontent.com/68883664/112777470-e6570200-9074-11eb-99af-8307e8d5ec28.png)
![image](https://user-images.githubusercontent.com/68883664/112777488-ef47d380-9074-11eb-9b71-f15029af7ddd.png)

**Comment by xxxpsyduck** [comment]
If you want to use tensorrt please install it first. If not, change the config file `use_tensorrt 0`

**Comment by stefan-567** [comment]
都还没有读取配置文件，就开始报错，并且配置文件中use_tensorrt字段已经设置为0，应该不是这个问题导致的。

**Comment by stefan-567** [comment]
> If you want to use tensorrt please install it first. If not, change the config file `use_tensorrt 0`

都还没有读取配置文件，就开始报错，并且配置文件中use_tensorrt字段已经设置为0，应该不是这个问题导致的。

**Comment by stefan-567** [comment]
原因找到了，运行c++ infer工程之前，必须配置相应的TensorRT环境，写出来供大家参考

**Comment by lingl-space** [comment]
hello, I would like to ask you how to configure the tensorrt environment? Methods that directly copy the contents of the lib file to the release file will still report this error.
