### ISSUE TITLE
SRN语义训练

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2356]
中文特殊场景，假设我已经通过普通的数据集训练完SRN模型，我可以通过大量特殊场景语义合成数据仅训练语义模块吗
是修改loss文件的 
sum_cost = cost_word * 3.0 + cost_vsfd + cost_gsrm * 0.15
把cost_word权重设为0就可以吗

**Comment by tink2123** [comment]
理论上可以，可以在pvam模块的最后一层输出，设置 stop_gradient=False， 然后计算loss的时候用 sum_cost = cost_vsfd+cost_gsrm*0.15 或者适当增加 gsrm 的权重

**Comment by caopulan** [comment]
> 理论上可以，可以在pvam模块的最后一层输出，设置 stop_gradient=False， 然后计算loss的时候用 sum_cost = cost_vsfd+cost_gsrm*0.15 或者适当增加 gsrm 的权重

想问下可不可以把 resnet+fpn+pvam模块用crnn+ctc代替
