### ISSUE TITLE
新GPU服务器启动OCR模型训练时，单卡启动正常，多卡启动不执行训练，不打印训练日志

### ISSUE THREAD

**Issue by tjzx** [PaddlePaddle/PaddleOCR#2358]
你好，新GPU服务器，安装最新版飞浆平台后执行多卡模型训练：
python3 -m paddle.distributed.launch --gpus '0,1,2,3,4,5,6,7' tools/train.py -c configs/rec/ch_ppocr_v2.0/dosmono_rec_ch_lite_samll_train_v2.0.yml
没有执行训练操作，也没有输出训练日志 (有加载资源等日志)。
参考：
![ocr_multi-GPU_log](https://user-images.githubusercontent.com/10286246/112784397-32f60980-9084-11eb-9281-847b3bec6b4b.png)
![ocr_multi-GPU_nvidia-smi](https://user-images.githubusercontent.com/10286246/112784402-34273680-9084-11eb-9f42-41e66a0e3549.png)
![ocr_multi-GPU_process](https://user-images.githubusercontent.com/10286246/112784403-34bfcd00-9084-11eb-932a-f093a9503e93.png)

但单卡执行则正常：python3  tools/train.py -c configs/rec/ch_ppocr_v2.0/dosmono_rec_ch_lite_samll_train_v2.0.yml &
![ocr_1GPU_log](https://user-images.githubusercontent.com/10286246/112784007-2624e600-9083-11eb-8fb2-01c413981822.png)
![ocr_1GPU_nvidia-smi](https://user-images.githubusercontent.com/10286246/112784009-27eea980-9083-11eb-8d58-5a7af7ab3147.png)
![ocr_1GPU_process](https://user-images.githubusercontent.com/10286246/112784010-28874000-9083-11eb-8fd0-f52db899a3f9.png)
环境：多卡 A100、Centos7.8、驱动 450.102.04、CUDA 11.0、cudnn 8.0.4、nccl 2.8.4、Python 3.8、pip3 21.0.1
请问有哪些可能的问题导致此情况？

**Comment by tink2123** [comment]
尝试减小多卡训练时的 num_workers 或 batch_size，看下能否跑起来

**Comment by tjzx** [comment]
修改后还是一样的情况
![cfg](https://user-images.githubusercontent.com/10286246/112943294-e5e96480-9163-11eb-9442-6034110ce69c.png)

**Comment by tjzx** [comment]
更新软件后版本：多卡 A100、Centos7.8、驱动 460.32.03、CUDA 11.2、cudnn 8.0.4、nccl 2.8.4、Python 3.8.5、pip3 21.0.1
多卡模式启动训练时卡在program.py如图处，帮忙看看什么问题导致。
![program py](https://user-images.githubusercontent.com/10286246/112950269-ad9a5400-916c-11eb-80ff-4f14c4342cf8.png)

**Comment by steinvenic** [comment]
腾讯云Ubuntu 20.04 LTS， NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0
显存就占了几百兆，试过好几次了，都这个样
![image](https://user-images.githubusercontent.com/18524326/125456195-709ffe28-6f80-4ead-a690-6b1b6c5f5ddc.png)

**Comment by tjzx** [comment]
我情况的问题是NVIDIA显卡与AMD CPU的IOMMU不兼容的锅，重启进BIOS把IOMMU设置成Disable，或在系统中禁用IOMMU (二选一即可)。
会影响虚拟化方面，如果没使用到虚拟化就没关系。另外，据说会对性能有一点影响，没实际测试。目前是这么使用的。
你的只有一张卡，应该不是这个问题。

**Comment by zqx1609** [comment]
[2022/06/08 11:58:23] ppocr INFO:     loader : 
[2022/06/08 11:58:23] ppocr INFO:         batch_size_per_card : 14
[2022/06/08 11:58:23] ppocr INFO:         drop_last : True
[2022/06/08 11:58:23] ppocr INFO:         num_workers : 4
[2022/06/08 11:58:23] ppocr INFO:         shuffle : True
[2022/06/08 11:58:23] ppocr INFO: profiler_options : None
[2022/06/08 11:58:23] ppocr INFO: train with paddle 2.2.2 and device CUDAPlace(0)
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:39589', '127.0.0.1:60869', '127.0.0.1:47711']
I0608 11:58:26.548106 152481 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0

我也是多卡的时候卡住，你是用的dgx吗

**Comment by tjzx** [comment]
没有使用dgx。可以尝试我上面的方法
