### ISSUE TITLE
paddleOCR模型预测开启gpu后耗时平均为2s, 使用cpu耗时为0.4秒, 是配置有问题吗

### ISSUE THREAD

**Issue by tustz** [PaddlePaddle/PaddleOCR#2360]
如题, opencv为3.4.7版, cuda为9.2.0,  paddleOCR为release1.1版本, paddle预测库为1.8.5在centos7.6源码编译的, 支持gpu和cudnn, 但是没有开启tensorrt

**Comment by tustz** [comment]
模型使用的是官网给的中文超轻量v1.1版本的det和rec, 配置信息如下
=======Paddle OCR inference config======
char_list_file : ../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : /mnt/ssd1/abc/weight/cls
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : /home/zwb/paddleOCR/models/ch_ppocr_mobile_v1.1_det_infer
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : /home/zwb/paddleOCR/models/ch_ppocr_mobile_v1.1_rec_infer
use_angle_cls : 0
use_gpu : 1
use_mkldnn : 1
use_zero_copy_run : 1
visualize : 1
=======End of Paddle OCR inference config======
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
1	上海斯格威铂尔大酒店	score: 0.991312
2	打浦路15号	score: 0.995862
3	绿洲仕格维花园公寓	score: 0.997271
4	打浦路252935号	score: 0.990316
花费了2.32771秒

**Comment by tink2123** [comment]
测试速度时，需要测一组图片，去掉模型启动时间后，取平均值。预测单张图片得到的结果并不准确。
