### ISSUE TITLE
SRN需要对训练集字符长度做平衡吗

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2364]
之前用crnn+ctc模型，卷积和ctc对图片宽度都没有限制，在训练好模型后可以根据实际应用场景随意调整图片宽度和字符长度，训练集的字符长度也没有要求（比如训练集都是短文本，应用场景都是长文本也不会有太大影响）

但是输出SRN的eval结果的时候我发现长文本的识别效果非常差（训练集几乎没有较长文本），想问一下训练SRN的话，训练集是不是需要做一些文本长度的平衡，如果我应用场景会出现大量长文本，在训练的时候是不是也需要大量长文本数据

**Comment by tink2123** [comment]
是的，ctc 不需要对齐。SRN和attention的方法类似，依赖最大长度的限制，如果需要长文本的话，需要修改max_length、img_shape，并添加一些长文本数据用来训练。
