### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by Mafengqiang** [PaddlePaddle/PaddleOCR#2365]
![image](https://user-images.githubusercontent.com/44855506/112928710-af9eeb80-9149-11eb-926b-0ec848e0a01d.png)
安装docker镜像时，这两个cuda版本必须对应吗
![image](https://user-images.githubusercontent.com/44855506/112928778-cfceaa80-9149-11eb-91ff-fef4851a541c.png)

**Comment by WenmuZhou** [comment]
这两个不用，但是你的驱动版本必须支持镜像里的cuda版本

**Comment by Mafengqiang** [comment]
> 这两个不用，但是你的驱动版本必须支持镜像里的cuda版本

好的，谢谢了
