### ISSUE TITLE
PaddleOCR\ppocr\data\imaug\operators.py文件报错invalid input 'img' in NormalizeImag

### ISSUE THREAD

**Issue by ziyangwang21** [PaddlePaddle/PaddleOCR#2366]
当输入图片较小，文字与边缘贴合紧密时，operators.py的81行会报错invalid input 'img' in NormalizeImag是什么原因呢？如何解决。另外发现对数字识别不是很友好（可能针对 文字识别吧233

**Comment by Caotijing** [comment]
![Uploading 1.png…]()

**Comment by WenmuZhou** [comment]
你打印一下，进operators.py的81行的图片shape看看

**Comment by Caotijing** [comment]
显示图片是None

**Comment by Caotijing** [comment]
好像是图片清晰度不够，resize采样到50X50以上就好了。。

**Comment by WenmuZhou** [comment]
好的
