### ISSUE TITLE
Windows下使用标注工具，提示导入错误

### ISSUE THREAD

**Issue by Gs-Zhang** [PaddlePaddle/PaddleOCR#2368]
![image](https://user-images.githubusercontent.com/48624777/112951552-0e765c00-916e-11eb-8c41-b8f72ae0d213.png)
导入paddle也出错

**Comment by grasswolfs** [comment]
可以先参考安装文档解决paddle安装的问题哈
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by MyGitHub-G** [comment]
一样的问题，求解

**Comment by MyGitHub-G** [comment]
> ![image](https://user-images.githubusercontent.com/48624777/112951552-0e765c00-916e-11eb-8c41-b8f72ae0d213.png)
> 导入paddle也出错

请问解决了吗

**Comment by Gs-Zhang** [comment]
> 可以先参考安装文档解决paddle安装的问题哈
> https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

目前paddlepaddle不支持window家庭版使用pip方式安装，这个是原因。

**Comment by Gs-Zhang** [comment]
应该都可以，主要是要用conda配置环境，具体为什么要这样我也不清楚，因为之前我是这样安装成功的，所以注意到说不支持家庭版的时候，我重新按照之前的方法试了一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月31日(周三) 晚上9:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] Windows下使用标注工具，提示导入错误 (#2368)




    

 导入paddle也出错
  
请问解决了吗
  
如果你的的电脑是windows家庭版的吧，可以考虑使用anaconda创建一个虚拟环境，在虚拟环境里面安装paddlepaddle，这样可以解决paddlepaddle的安装问题。
  
所以使用conda安装paddlepaddle 而不是用pip吗
