### ISSUE TITLE
hubserving cpu 部署  ocr_det,ocr_system算法换成EAST，100%报错

### ISSUE THREAD

**Issue by shen2009fei** [PaddlePaddle/PaddleOCR#2373]
hubserving cpu 部署  ocr_det,ocr_system算法换成EAST，对应的参数也是修改过了的, 100%报错。

错误信息：list index out of range

版本是paddleocr 2.0
server：4核16g

**Comment by chenjiaoAngel** [comment]
错误信息：list index out of range 这个说明哪儿读取数据存在越界风险；可能还有地方没有修改过来
