### ISSUE TITLE
关于SAST模型使用的NMS算法的解读

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleOCR#2374]
尊敬的PaddleOCR老师，您好，
最近我正在学习飞桨自研的SAST算法，我阅读了一下SAST算法的原始论文，论文中似乎没有对使用的NMS算法作具体的描述，请问一下，SAST跟EAST用的是同一个NMS算法吗？

期待您的回复！

**Comment by MissPenguin** [comment]
实现细节可能略有不同，效果是差不多的
