### ISSUE TITLE
执行build_ios后，继续执行 make -j 报错  make: *** No rule to make target `../Makefile.def'.  Stop.

### ISSUE THREAD

**Issue by silsuer** [PaddlePaddle/PaddleOCR#2376]
模仿Android的教程执行  `./lite/tools/build_ios.sh  --arch=armv8  --with_cv=ON --with_extra=ON`

然后执行 `prepare.sh`

最后在ocr目录下执行 `make -j`

报错:

```
Makefile:4: ../Makefile.def: No such file or directory
make: *** No rule to make target `../Makefile.def'.  Stop.
```

请问是哪步有问题？能否给一个部署ios的教程？

**Comment by chenjiaoAngel** [comment]
最后在ocr目录下执行 make -j， 这个应该是产物目录下的demo 目录去做make；请问是参考的哪个教程呢？

**Comment by silsuer** [comment]
@chenjiaoAngel  `https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/lite` 这个教程

**Comment by chenjiaoAngel** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/38650344/113650927-a2db4400-96c3-11eb-80c9-376b79972e9e.png">

辛苦检查下这个目录是否有上述文件内容，如果有；那make -j是在demo/cxx/ocr/这个目录执行的吗？（这个下面有Makefile 文件，应该是可以make）

**Comment by silsuer** [comment]
@chenjiaoAngel 这些文件倒是都有，makefile文件也有，只是make的时候，报错，没有 `../Makefile.def` 这个文件，确实没有这个文件

**Comment by chenjiaoAngel** [comment]
![image](https://user-images.githubusercontent.com/38650344/113998855-0b751d00-988c-11eb-83e7-a59be6bb2e62.png)
生成产物目录例如：build.lite.android.armv7.clang/inference_lite_lib.android.armv7/d
emo/cxx/）下是有Makefile.def 这个文件的；如果没有话，是不是没有下载全或者源码编译没有跑完

**Comment by chshwei-perfxlab** [comment]
@silsuer @chenjiaoAngel 请问Makefile.def的问题解决了吗？我发现 @chenjiaoAngel 你的在android环境下是有Makefile.def，但在build_linux.sh下没有Makefile.def ?

**Comment by silsuer** [comment]
@chshwei-perfxlab 没有解决，最后还是部署在了服务端，前端只传base64
