### ISSUE TITLE
OCR项目设置CUDA_VISIBLE_DEVICES后，找不到设备呢

### ISSUE THREAD

**Issue by astronstar** [PaddlePaddle/PaddleOCR#238]
---------------------------------------------------------------------------KeyError                                  Traceback (most recent call last)~/.paddlehub/modules/chinese_ocr_db_crnn_mobile/module.py in recognize_text(self, images, paths, use_gpu, output_dir, visualization, box_thresh, text_thresh)
    177             try:
--> 178                 _places = os.environ["CUDA_VISIBLE_DEVICES"]
    179                 int(_places[0])
/opt/conda/envs/python35-paddle120-env/lib/python3.7/os.py in __getitem__(self, key)
    677             # raise KeyError with the original key value
--> 678             raise KeyError(key) from None
    679         return self.decodevalue(value)
KeyError: 'CUDA_VISIBLE_DEVICES'
During handling of the above exception, another exception occurred:
RuntimeError                              Traceback (most recent call last)<ipython-input-40-6c673fd0eb33> in <module>
     11                     visualization=False,       # 是否将识别结果保存为图片文件；
     12                     box_thresh=0.1,           # 检测文本框置信度的阈值；
---> 13                     text_thresh=0.1)          # 识别中文文本置信度的阈值；
     14 
     15 for result in results:
~/.paddlehub/modules/chinese_ocr_db_crnn_mobile/module.py in recognize_text(self, images, paths, use_gpu, output_dir, visualization, box_thresh, text_thresh)
    180             except:
    181                 raise RuntimeError(
--> 182                     "Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES via export CUDA_VISIBLE_DEVICES=cuda_device_id."
    183                 )
    184 
RuntimeError: Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES via export CUDA_VISIBLE_DEVICES=cuda_device_id.

**Comment by astronstar** [comment]
!export CUDA_VISIBLE_DEVICES=0,1

results = ocr.recognize_text(
                    images=np_images,         # 图片数据，ndarray.shape 为 [H, W, C]，BGR格式；
                    use_gpu=True,            # 是否使用 GPU；若使用GPU，请先设置CUDA_VISIBLE_DEVICES环境变量

**Comment by astronstar** [comment]
os.environ设置

**Comment by wowowoll** [comment]
命令行里 export CUDA_VISIBLE_DEVICES=0

**Comment by zyzz1974** [comment]
windows环境怎么设置呢
