### ISSUE TITLE
印章文字识别

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2383]
印章上面有环形文本还有水平文本两种。针对圆形和椭圆形两种类型的弯曲文本，有没有合适的训练模型算法推荐呢，我看你们官网上的印章文字识别效果特别好，能给解答一下吗，谢谢了

**Comment by sixyang** [comment]
同求，官网上的效果挺好的，能交流一下吗？

**Comment by lalalagogogochong** [comment]
> 同求，官网上的效果挺好的，能交流一下吗？

他们官网的应该是用的端到端的PGnet实现的，我没用过这个方法，没有相关的数据。https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/pgnet.md

**Comment by charlesyzk** [comment]
> > 同求，官网上的效果挺好的，能交流一下吗？
> 
> 他们官网的应该是用的端到端的PGnet实现的，我没用过这个方法，没有相关的数据。https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/pgnet.md

请问官网上的案例是在哪里看到的 想了解下

**Comment by charlesyzk** [comment]
> > 同求，官网上的效果挺好的，能交流一下吗？
> 
> 他们官网的应该是用的端到端的PGnet实现的，我没用过这个方法，没有相关的数据。https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/pgnet.md

请问官网上的案例是在哪里看到的  我没有找到 想看下了解下
