### ISSUE TITLE
visualdl断点训练

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/PaddleOCR#2384]
目前的断点训练会使visualdl显示不出数据
而且iter的数断点后会从0开始

我每次是把旧的vdl文件重命名，才能显示visualdl，如果直接断点续训，visualdl启动后会显示没有数据

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/2566  这里修了
