### ISSUE TITLE
移动端模型能否输出坐标？

### ISSUE THREAD

**Issue by silsuer** [PaddlePaddle/PaddleOCR#2387]
根据教程 `https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/lite`  完成了端侧部署，但是输出结果中并不包含坐标，请问如何设置才能得到坐标？或者如何把在`adb shell`里的命令，塞进Android程序里？

**Comment by WenmuZhou** [comment]
返回这个坐标即可https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/ocr_db_crnn.cc#L397
