### ISSUE TITLE
训练小语种

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleOCR#239]
首先感谢您的出色项目,有些问题需要请教:
1.网络是否可以支持训练小语种,比如日语,法语,韩语等
2.这些小语种有预训练模型可以用吗
3.ppocr_keys_v1.txt这个文件是怎么生成的呢,训练小语种的话也是需要生成对应字典文件的吧

**Comment by LDOUBLEV** [comment]
1. 支持其他数据训练，前提是有这些数据
2. 目前没有release小语种的模型
3. 这个是字典文件，如果你用小语种训练，字典里的文字就是你小语种的问题，如果是英文这种，可以不需要字典文件，字母加数字即可

**Comment by lfxx** [comment]
> 1. 支持其他数据训练，前提是有这些数据
> 2. 目前没有release小语种的模型
> 3. 这个是字典文件，如果你用小语种训练，字典里的文字就是你小语种的问题，如果是英文这种，可以不需要字典文件，字母加数字即可

感谢您的回复,使用中文预训练模型训练小语种是否有帮助呢,会不会起到反作用

**Comment by leminhyen2** [comment]
@lfxx in the end, did you use the pre-trained Chinese model to train other languages? I'm interested in training Japanese
