### ISSUE TITLE
PPOCRLabel安装问题：sudo apt-get install libxcb-icccm.so.4

### ISSUE THREAD

**Issue by VarianReeves** [PaddlePaddle/PaddleOCR#2390]

**Comment by VarianReeves** [comment]
aistudio@jupyter-625437-1751077:~/PaddleOCR/PPOCRLabel$ sudo apt-get install libxcb-icccm.so.4
[sudo] password for aistudio: 

Sorry, try again.
[sudo] password for aistudio: 
Sorry, try again.
[sudo] password for aistudio: 
sudo: 3 incorrect password attempts

无法输入password

**Comment by VarianReeves** [comment]
aistudio@jupyter-625437-1751077:~/PaddleOCR/PPOCRLabel$ python PPOCRLabel.py --lang ch
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
QFactoryLoader::QFactoryLoader() checking directory path "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/conda/envs/python35-paddle120-env/bin/platforms" ...
Cannot load library /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617411367 (unix time) try "date -d @1617411367" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000003fc) received by PID 1020 (TID 0x7f4cef384700) from PID 1020 ***]

Aborted (core dumped)

**Comment by VarianReeves** [comment]
环境：python 3.7     PaddlePaddle 2.0.1

**Comment by Evezerest** [comment]
linux输入密码的时候是不可见的，报错是qt安装问题

**Comment by VarianReeves** [comment]
> linux输入密码的时候是不可见的，报错是qt安装问题

这样的吗，谢谢，我试一下
