### ISSUE TITLE
如何提高垂类精度？

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleOCR#2391]
请问修改了字典，然后pretrain_weights指定为官方预训练模型，继续训练提高垂类数据精度吗？不能的话，具体要怎么操作

**Comment by WenmuZhou** [comment]
你的操作理论上是可以的，但是需要你自己做实验看看结论

**Comment by mikeshi80** [comment]
我一直在做这方面工作，完全可行。比如专门识别号码的，专门识别人名，地名的，精度都远超官方的通用模型。但是这里牵涉到一个训练的素材的问题，生成训练用数据时，文本和字体，以及设定的背景及间距等，都至关重要。

**Comment by isLiuHao** [comment]
> 你的操作理论上是可以的，但是需要你自己做实验看看结论

但是我试了发现是重新开始训练，引用的预训练模型相当于没有使用

**Comment by mikeshi80** [comment]
> > 你的操作理论上是可以的，但是需要你自己做实验看看结论
> 
> 但是我试了发现是重新开始训练，引用的预训练模型相当于没有使用

不会啊，收敛比重头开始快很多啊。当然，如果是小模型，确实差别不大，但是如果是几千个字的大模型，就不一样了
