### ISSUE TITLE
eval超轻量模型datareader报错

### ISSUE THREAD

**Issue by zhaoyantao-murray** [PaddlePaddle/PaddleOCR#2393]
在AIstudio上eval 超轻量OCR模型报错datareader有问题，可是在自己电脑上跑就没问题，请问开发老哥咋回事呢，麻烦解答
![报错](https://user-images.githubusercontent.com/61047836/113506120-7d402480-9575-11eb-8d6f-81f6d6e40bbc.png)

**Comment by WenmuZhou** [comment]
ai studio上需要把num_workers=0

**Comment by zhaoyantao-murray** [comment]
ok，问题解决，谢谢哈
