### ISSUE TITLE
SRN model

### ISSUE THREAD

**Issue by CuongNN218** [PaddlePaddle/PaddleOCR#2394]
I want to train SRN recognition with my own dataset. How can I create the key below?
'encoder_word_pos',
'gsrm_word_pos',
'gsrm_slf_attn_bias1',
'gsrm_slf_attn_bias2'

**Comment by tink2123** [comment]
You can refer to this code and modify the corresponding parameter shape according to the image shape and max_length you input.

https://github.com/PaddlePaddle/PaddleOCR/blob/2b16323080bbf503828b96f1ef531dc1074a1272/ppocr/data/rec/img_tools.py#L417-L438
