### ISSUE TITLE
识别模型使用训练好的推断模型预测都没有问题，但是把预训练模型转换为推断模型后预测结果为乱码

### ISSUE THREAD

**Issue by zikaixie** [PaddlePaddle/PaddleOCR#2397]
如图，为直接下载超轻量模型的推断模型预测：
![0](https://user-images.githubusercontent.com/62594309/113650231-7115ad80-96c2-11eb-8c57-4cd83510b9ae.png)

但是使用预训练模型，不管是直接eval，还是转换为推断模型再predict，或者是经过一点数据训练后再eval/转化为推断模型predict，都会预测出置信度0.03的无效文本：
![0 (1)](https://user-images.githubusercontent.com/62594309/113650357-a91cf080-96c2-11eb-9e89-3500e9ab4423.png)

请问是配置文件哪里设置错了吗？我试了ch_ppocr_mobile_v2.0_rec_pre和rec_r34_vd_tps_bilstm_ctc_v2.0_train，配置文件用的都是自带的，都出现了这样的问题

环境为windows

**Comment by tink2123** [comment]
是重新训练了吗？麻烦贴一下都是无效结果的预测命令吧～

**Comment by liaoxy169** [comment]
可以看下配置里面空格和字典错了没有

**Comment by frotms** [comment]
遇到同样问题：
用rec_mv3_tps_bilstm_ctc_v2.0_train和rec_r34_vd_tps_bilstm_ctc_v2.0_train转为inference模型，
rec_mv3_tps_bilstm_ctc_v2.0_infer推理结果正确，
rec_r34_vd_tps_bilstm_ctc_v2.0_infer推理结果错误。

**Comment by frotms** [comment]
找到问题，`configs/rec/rec_r34_vd_tps_bilstm_ctc.yml`配置有问题，`model_name和`encoder_type`改为下面配置，结果就正确了。
`Architecture:
  model_type: rec
  algorithm: STARNet
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: large
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0`

**Comment by Helloworld0214** [comment]
> 找到问题，`configs/rec/rec_r34_vd_tps_bilstm_ctc.yml`配置有问题，`model_name`和`encoder_type`改为下面配置，结果就正确了。
> Architecture:
> model_type: rec
> algorithm: STARNet
> Transform:
> name: TPS
> num_fiducial: 20
> loc_lr: 0.1
> model_name: large
> Backbone:
> name: ResNet
> layers: 34
> Neck:
> name: SequenceEncoder
> encoder_type: reshape
> hidden_size: 256
> Head:
> name: CTCHead
> fc_decay: 0


你好，训练tps的时候这个点你们设置的依据是什么。还有就是训练的时侯，标注框会有点的坐标吗？
