### ISSUE TITLE
pyinstaller 打包ocr报错

### ISSUE THREAD

**Issue by WindCanDie** [PaddlePaddle/PaddleOCR#2398]
使用pyinstaller 进行基本例子的打包，会出现no module named .... paddleocr 内部包没有正常关联起来，paddle也有同样问题

**Comment by sky-chy** [comment]
老哥，你解决了吗

**Comment by sky-chy** [comment]
我在spec文件里面引入依赖路径，打包的时候就报 使用非顶级路径的问题
![image](https://user-images.githubusercontent.com/41139710/140924150-ade92049-bd93-4167-81ed-f3251ce1fe9a.png)
