### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adolf69** [PaddlePaddle/PaddleOCR#24]
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 15, in <module>
    import utility
  File "PaddleOCR/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
ModuleNotFoundError: No module named 'ppocr'

**Comment by dyning** [comment]
# 设置PYTHONPATH环境变量
export PYTHONPATH=.

**Comment by adolf69** [comment]
export PYTHONPATH=.;
 python -m tools.infer.predict_system \
 --image_dir="doc/imgs/" \
 --det_model_dir="inference/det/"
 --rec_model_dir="inference/rec/"

**Comment by adolf69** [comment]
使用sh脚本 报ModuleNotFoundError: No module named 'utility'
test.sh: 5: test.sh: --rec_model_dir=inference/rec/: not found
的错误

**Comment by LDOUBLEV** [comment]
> 使用sh脚本 报ModuleNotFoundError: No module named 'utility'
> test.sh: 5: test.sh: --rec_model_dir=inference/rec/: not found
> 的错误

需要先下载inference模型，确保下载 识别的inference模型 在inference/rec/目录下

**Comment by adolf69** [comment]
下载了 不使用shell脚本直接命令行运行就可以

**Comment by LDOUBLEV** [comment]
> 下载了 不使用shell脚本直接命令行运行就可以

好的，我们会排查下问题

**Comment by adolf69** [comment]
顺便问一下 ，可以跑在cpu上面吗

**Comment by LDOUBLEV** [comment]
> 顺便问一下 ，可以跑在cpu上面吗

可以在CPU上运行，但是目前CPU上的结果与GPU有稍许diff，问题正在处理中

**Comment by adolf69** [comment]
好的 运行在cpu上的命令能发一下吗

**Comment by LDOUBLEV** [comment]
> 好的 运行在cpu上的命令能发一下吗

如果是跑CPU的inference，可以通过设置tools/infer/utility.py中的--use_gpu参数实现，如下：
```
export PYTHONPATH=.  && python  tools/infer/predict_rec.py --image_dir="/demo.jpg" --rec_model_dir="./inference/rec/"  --use_gpu=False
```

**Comment by adolf69** [comment]
好的 谢谢 辛苦了 我先看看效果 再看看代码

**Comment by LDOUBLEV** [comment]
> 好的 谢谢 辛苦了 我先看看效果 再看看代码


> 顺便问一下 ，可以跑在cpu上面吗

CPU与GPU运行结果有diff的bug已修复，请拉取最新代码试下
