### ISSUE TITLE
识别通用模型的合成方法

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/PaddleOCR#2401]
ppocr识别的通用模型用的500万合成数据的合成方法或方式能透露么

**Comment by MissPenguin** [comment]
使用开源数据合成工具text_renderer进行合成的：https://github.com/Sanster/text_renderer

**Comment by aaferrero** [comment]
谢谢，背景图片的素材是网上扒的么，文字颜色是随机的？
