### ISSUE TITLE
3.单张图像或者图像集合预测 提示的问题，怎么解决呢

### ISSUE THREAD

**Issue by micricket** [PaddlePaddle/PaddleOCR#2402]
λ intellif /paddle/PaddleOCR {release/2.0} python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 28, in <module>
    import tools.infer.utility as utility
  File "/paddle/PaddleOCR/tools/infer/utility.py", line 23, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle' (/usr/local/lib/python3.7/site-packages/paddle/__init__.py)

**Comment by LDOUBLEV** [comment]
更新paddle版本 >=2.0就行
