### ISSUE TITLE
文本检测中的数据增强的上下翻转怎么实现？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2403]
1、PaddleOCR给出的模型对于上下翻转的图像检测效果也很好，是因为训练数据就包含大量的上下翻转的数据吗？我用正面的训练数据训练的模型只能检测到正面图像文本，上下翻转的检测不出来。后来通过{ 'type': Affine, 'args': { 'rotate': [-10, 10] } }的角度设置为-180，180，但是效果非常差。
2、在文本检测模型DB中，数据增强是左右翻转{ 'type': Fliplr, 'args': { 'p': 0.5 } }，有没有类似的方式来做上下翻转的数据增强呢？

**Comment by WenmuZhou** [comment]
这个可以查询一下imgaug的文档

**Comment by Lie-huo** [comment]
> 这个可以查询一下imgaug的文档

嗯嗯，好的，我查一下。那么官方的检测模型可以检测上下翻转后的文本，方便告知是怎么实现的吗？

**Comment by Lie-huo** [comment]
没有人回答的吗

**Comment by WenmuZhou** [comment]
做了对于的数据扩充
