### ISSUE TITLE
轻量模型的推断中，每隔几行就会出现一行识别为乱码

### ISSUE THREAD

**Issue by zikaixie** [PaddlePaddle/PaddleOCR#2405]
![image](https://user-images.githubusercontent.com/62594309/113710560-73095c00-9716-11eb-828d-40026f37715e.png)
就像这里蓝色圈起来的这行

但是通用模型就没有这个问题
这是什么原因引起的呢？

**Comment by LDOUBLEV** [comment]
可以发一下测试图和参数配置吗？我这边测试了一批图，没出现这个问题

**Comment by zikaixie** [comment]
没有特别的参数配置，是调用
ocr = PaddleOCR(use_gpu=False, use_angle_cls=True, enable_mkldnn=True)
然后
ocr.ocr(img_path+img, cls=True)
返回的，模型就是默认自动下载的（应该是轻量模型）

测试图比如：
![8](https://user-images.githubusercontent.com/62594309/113980405-035fb200-9879-11eb-8c3b-6f7aa8af32a4.png)
这张图的测试结果：
[输出.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6276608/default.txt)
倒数第二行，是右下角那个电话号码，它输出就是很奇特的['g0saz zSe+G）ZzLzzSzzse+(）', 0.511896]]

**Comment by zikaixie** [comment]
发现问题了：方向分类器把其中的一些bbox识别为‘180’了，然后就倒置了这些bbox，倒置之后就会识别出乱码，关掉方向分类器可以解决该问题
