### ISSUE TITLE
使用目前提供的检测模型发现在每次测试同一批数据的结果都不一样？

### ISSUE THREAD

**Issue by dhhcj1** [PaddlePaddle/PaddleOCR#2406]
RT，使用提供的检测模型（DB resnet18）测试同一批数据（MTWI 随机抽取了200张）时发现每次的 Hmean 值都不太一样，上下浮动在1%左右，请问这是出现了什么情况，该如何解决呢？

目前已经确认过的事项：

1.  配置文件相同
2.  测试数据相同
3.  没有更改代码
4.  测试其他已经训练好的检测模型时也发现了同样的问题 
5. 使用的测试脚本及命令是
python3 tools/eval.py -c configs/det/det_mv3_db.yml -oGlobal.checkpoints="{path/to/weights}/best_accuracy"

**Comment by dhhcj1** [comment]
使用的测试脚本及命令是
python3 tools/eval.py -c configs/det/det_mv3_db.yml  -oGlobal.checkpoints="{path/to/weights}/best_accuracy"

**Comment by MissPenguin** [comment]
可能组网里有些随机化的地方没有设置test模式，如果导出为推理模型预测，结果就会稳定了

**Comment by dhhcj1** [comment]
> 可能组网里有些随机化的地方没有设置test模式，如果导出为推理模型预测，结果就会稳定了

一步一步跟进发现是测试图像的问题，发现有一些图（Mtwi2018 task2）在每次的测试的结果都不相同，把这些图排除掉之后结果就稳定了。 所以想问一下，咱们这个项目有对公开数据集做过预处理吗？比如说转化成统一格式（PNG -> JPG）之类的

**Comment by dhhcj1** [comment]
> 可能组网里有些随机化的地方没有设置test模式，如果导出为推理模型预测，结果就会稳定了

一步一步跟进发现是测试图像的问题，发现有一些图（Mtwi2018 task2）在每次的测试的结果都不相同，把这些图排除掉之后结果就稳定了。 所以想问一下，咱们这个项目有对公开数据集做过预处理吗？比如说转化成统一格式（PNG -> JPG）之类的

**Comment by gl94** [comment]
我测试了 确实preds的数值不一样 有随机性

**Comment by tianlianghai** [comment]
> 我测试了 确实preds的数值不一样 有随机性

是的
