### ISSUE TITLE
Windows10, 自行编译2.0.1的PaddlePaddle GPU下，无法训练SRN模型

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleOCR#2407]
由于使用3090显卡，所以飞桨为自行编译的2.0.1版本，使用CUDA11.2， cuDNN8.1.0。

在尝试进行SRN模型训练时，程序无报错直接退出，通过加log，发现是 

https://github.com/PaddlePaddle/PaddleOCR/blob/e4ce3bf69c37e012d28db77e351412c0f2e5acf0/tools/program.py#L207

处执行后直接退出，没有执行下一句。

调整过batch size，显存占用16G，离3090的24G尚有一段空间，所以应该不是爆显存导致。同时，GPU的使用率也一直为0，应该是没有进行训练。

**Comment by tink2123** [comment]
其他模型可以正常训练吗？是单卡训练的吗？在model里多打一些log，定位一下具体是在哪里退出的吧

**Comment by mikeshi80** [comment]
其他模型可以的，我之后在model里打打log追踪一下吧

**Comment by mikeshi80** [comment]
使用VSCode进行debug，最后跟踪到是执行到这里突然退出

https://github.com/PaddlePaddle/PaddleOCR/blob/ff9f8ecedf9ebf27f7eff039652acbbc5eae6fb7/ppocr/modeling/heads/rec_srn_head.py#L90-L91

`word_pos_feature`的数值是这样的：
```
shape=[32, 15, 1, 512], dtype=float32, place=CUDAPlace(0), stop_gradient=False,       [[[[-0.92625737, -0.56897......]]]]
```
`self.max_length`是25（这个应该是配置文件里的最大字符数），c是512。`paddle.reshape`函数应该是C/C++的代码，无法进一步step in了。

**Comment by Tomingz** [comment]
windows paddle-gpu2.1.2,。遇到同样的问题，srn模型无法训练，crnn都正常
