### ISSUE TITLE
ppocrlabel启动报错

### ISSUE THREAD

**Issue by MyGitHub-G** [PaddlePaddle/PaddleOCR#2412]
![捕获](https://user-images.githubusercontent.com/71758483/113855788-04d69f00-97d3-11eb-9d8d-5660015f0896.PNG)
按照步骤进行的安装操作
操作系统：windows家庭版
paddlepaddle-gpu
python3.7.2
![捕获1](https://user-images.githubusercontent.com/71758483/113856046-4f581b80-97d3-11eb-8b16-6a03ffb51173.PNG)
![捕获2](https://user-images.githubusercontent.com/71758483/113856055-5121df00-97d3-11eb-8149-aff17d8af145.PNG)

**Comment by LDOUBLEV** [comment]
shapely 库没有安装好，window机器建议下载到本地安装，可以在网上搜一下教程

**Comment by MyGitHub-G** [comment]
真的非常谢谢，终于解决了

> shapely 库没有安装好，window机器建议下载到本地安装，可以在网上搜一下教程
