### ISSUE TITLE
官方的检测模型可以检测上下翻转后的文本，方便告知是怎么实现的吗？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2414]
官方的检测模型可以检测上下翻转后的文本是因为训练数据中就有大量的翻转图片吗，还是在代码中做了数据增强？

**Comment by bikerr** [comment]
> 官方的检测模型可以检测上下翻转后的文本是因为训练数据中就有大量的翻转图片吗，还是在代码中做了数据增强？

三步骤：检测-方向分类-识别 其中方向分类器会把反向文本进行旋转再去识别。好好阅读下文档应该就能解决的问题

**Comment by MissPenguin** [comment]
对的，因为使用了方向分类器。

**Comment by Lie-huo** [comment]
> > 官方的检测模型可以检测上下翻转后的文本是因为训练数据中就有大量的翻转图片吗，还是在代码中做了数据增强？
> 
> 三步骤：检测-方向分类-识别 其中方向分类器会把反向文本进行旋转再去识别。好好阅读下文档应该就能解决的问题

您好，您可能误解了我的意思了，我说的只是检测模型，不涉及后面的方向分类器与识别。因为我用自己的数据训练的检测模型只可以检测到正面的图片，当相同的图片上下翻转后就检测不到文本了。所以想了解一下你们的检测模型是怎么做的？

**Comment by Lie-huo** [comment]
> 对的，因为使用了方向分类器。

您好，您可能误解了我的意思了，我说的只是检测模型，不涉及后面的方向分类器与识别。因为我用自己的数据训练的检测模型只可以检测到正面的图片，当相同的图片上下翻转后就检测不到文本了。所以想了解一下你们的检测模型是怎么做的？

**Comment by gathierry** [comment]
我想是因为检测模型的数据增强里有rot90，当rot90的次数为2时，就是180度旋转，和上下翻转很相似。

**Comment by Lie-huo** [comment]
> 我想是因为检测模型的数据增强里有rot90，当rot90的次数为2时，就是180度旋转，和上下翻转很相似。

这是你的猜测吗

**Comment by littletomatodonkey** [comment]
你好，检测训练的时候，包含左右翻转的数据增广

https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/iaa_augment.py#L57

**Comment by Lie-huo** [comment]
> 你好，检测训练的时候，包含左右翻转的数据增广，不包含上下翻转
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/iaa_augment.py#L57

那官方的检测模型可以检测上下翻转的图片，是训练数据里有大量的上下翻转的图片吗？

**Comment by MissPenguin** [comment]
> > 你好，检测训练的时候，包含左右翻转的数据增广，不包含上下翻转
> > https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/iaa_augment.py#L57
> 
> 那官方的检测模型可以检测上下翻转的图片，是训练数据里有大量的上下翻转的图片吗？

应该自然有一些这种数据，但是没有针对性补充。那估计是模型的泛化性还不错

**Comment by Lie-huo** [comment]
> > > 你好，检测训练的时候，包含左右翻转的数据增广，不包含上下翻转
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/iaa_augment.py#L57
> > 
> > 
> > 那官方的检测模型可以检测上下翻转的图片，是训练数据里有大量的上下翻转的图片吗？
> 
> 应该自然有一些这种数据，但是没有针对性补充。那估计是模型的泛化性还不错

那我打算在使用imgaug的上下翻转，是需要加在PaddleOCR/ppocr/data/imaug/iaa_augment.py的class IaaAugment()中吗


>

**Comment by MissPenguin** [comment]
> > > > 你好，检测训练的时候，包含左右翻转的数据增广，不包含上下翻转
> > > > https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/iaa_augment.py#L57
> > > 
> > > 
> > > 那官方的检测模型可以检测上下翻转的图片，是训练数据里有大量的上下翻转的图片吗？
> > 
> > 
> > 应该自然有一些这种数据，但是没有针对性补充。那估计是模型的泛化性还不错
> 
> 那我打算在使用imgaug的上下翻转，是需要加在PaddleOCR/ppocr/data/imaug/iaa_augment.py的class IaaAugment()中吗
> 
> >

可以的

**Comment by gathierry** [comment]
> > 我想是因为检测模型的数据增强里有rot90，当rot90的次数为2时，就是180度旋转，和上下翻转很相似。
> 
> 这是你的猜测吗

east 的预处理里面是有rot90，DB里没看到。https://github.com/PaddlePaddle/PaddleOCR/blob/a0d51569d072a25a9d11327caa989af19390e251/ppocr/data/imaug/east_process.py#L58

但是旋转180度和flipud毕竟是不完全一样，所以是的，是猜测
