### ISSUE TITLE
报错：root INFO: not find model file path ./inference/ch_ppocr_mobile_v1.1_det_infer//inference.pdmodel 

### ISSUE THREAD

**Issue by andrew2558** [PaddlePaddle/PaddleOCR#2415]
我按网上的教程一步一步来的，下载的模型结构如下：
![image](https://user-images.githubusercontent.com/25080605/113960046-6b50d100-9856-11eb-85bb-4edcbcd9277d.png)

![image](https://user-images.githubusercontent.com/25080605/113960055-7277df00-9856-11eb-978a-10bd89a47e25.png)

![image](https://user-images.githubusercontent.com/25080605/113960070-77d52980-9856-11eb-99a0-467ed1bfb279.png)

请问这是什么问题？

**Comment by MissPenguin** [comment]
你下载的是静态图模型，重新下载v2.0的动态图模型吧，动态图模型和静态图模型文件名不一样

**Comment by andrew2558** [comment]
@MissPenguin 谢谢，真的是这个原因。

**Comment by hierarchyJK** [comment]
怎么下载动态图模型
