### ISSUE TITLE
训练srn loss一直特别大。acc为0，同样的数据训练crnn正常，所以数据没问题。想问下是不是srn代码还有问题呢？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#2416]
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/67897601/113989718-50488600-9883-11eb-8729-305dbf2eddd0.png">

**Comment by MissPenguin** [comment]
loss有在下降吗，可以多迭代一段时间观察下，开始acc为0是正常的。另外配置文件除了数据路径，改了别的参数吗？

**Comment by aishangmaxiaoming** [comment]
> loss有在下降吗，可以多迭代一段时间观察下，开始acc为0是正常的。另外配置文件除了数据路径，改了别的参数吗？
除了数据路径都没改。loss 5000多是正常的吗？

**Comment by MissPenguin** [comment]
没改别的地方就再迭代看看吧，开始loss5000多是正常的，最后收敛大概降到几百

**Comment by aishangmaxiaoming** [comment]
> 没改别的地方就再迭代看看吧，开始loss5000多是正常的，最后收敛大概降到几百

好的，72个epoch是不是太少啦，我看crnn是500个

**Comment by MissPenguin** [comment]
得看数据量

**Comment by aishangmaxiaoming** [comment]
> 得看数据量

srn你们是多少数据量设定的70个epoch收敛完毕的呢？

**Comment by simplify23** [comment]
> 没改别的地方就再迭代看看吧，开始loss5000多是正常的，最后收敛大概降到几百
这里的loss是指最终loss收敛到几百吗，我跑了mobilenetv3作为backbone的，用120w的英文合成数据集，训练epoch30左右，看起来已经收敛了，但总loss在3300左右，word_loss和img_loss在600左右，这符合预期吗
