### ISSUE TITLE
请教一个关于android so 依赖的问题？

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/PaddleOCR#2417]
为什么lite版本只需要依赖libpaddle_light_api_shared.so就可以在android端执行。但是android的demo 需要
```
libpaddle_light_api_shared.so
libc++_shared.so
libhiai_ir_build.so
libhiai_ir.so
libhiai.so
```
以上五个so的依赖，请问一下其他4so是什么功能，android demo中是否可以只依赖libpaddle_light_api_shared.so

**Comment by YY007H** [comment]
其他几个好像跟华为的什么东西有关，官方也没详解这块，我现在1.1的都跑不起来
