### ISSUE TITLE
中文的文字识别很容易过拟合

### ISSUE THREAD

**Issue by ruyijidan** [PaddlePaddle/PaddleOCR#242]
训练精度都有98了，实际验证才60多，是不是在识别的训练中现在还没有数据增强呀，

**Comment by SixGodGG** [comment]
同问，识别的训练中，有数据增强部分吗？

**Comment by dyning** [comment]
目前没有数据增强，后续会添加。

**Comment by SixGodGG** [comment]
> 目前没有数据增强，后续会添加。

好的 检测的数据处理中有

**Comment by dyning** [comment]
嗯，识别中的数据增强和检测中的数据增强不太一样。

**Comment by deep-practice** [comment]
这种训练精度很高(99%左右)，测试精度很低(60%左右)的情况，该如何处理呢 @dyning  印刷字体，数据量也足够，用了mbv3的预训练模型

**Comment by Hupengyu** [comment]
> > 目前没有数据增强，后续会添加。
> 
> 好的 检测的数据处理中有

请问检测的数据增强在哪里啊？我没有看到啊。pre_process_list里的{DetResizeForTest': 'NormalizeImage': 'ToCHWImage': 'KeepKeys':}，这四个是吗？这个是什么操作啊？预处理还是数据（图像）增强？
