### ISSUE TITLE
关于印章文字ocr的问题

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/PaddleOCR#2422]
![image](https://user-images.githubusercontent.com/40067956/114121148-6c4e3500-9920-11eb-86b7-c99848015bd3.png)
我在百度开放平台上面看到了印章ocr的识别，请问有什么开源的印章文字内容ocr识别代码可以参考一下的吗？谢谢

**Comment by MissPenguin** [comment]
paddleocr目前没有开源专门的印章识别代码，下周会开源端到端弯曲文本识别算法PGNet，可以用来训练印章识别任务。欢迎关注哦

**Comment by LilyCaiZL** [comment]
哇塞，好的好的，真的开源的很是时候，请问哪里可以看到宣传的信息呢？有专门paddleocr的群吗，还是就在飞桨交流群里面会说？

**Comment by MissPenguin** [comment]
> 哇塞，好的好的，真的开源的很是时候，请问哪里可以看到宣传的信息呢？有专门paddleocr的群吗，还是就在飞桨交流群里面会说？

首页有paddleocr交流群的二维码，可以扫码入群哈，最新的更新都会发布到群里的

**Comment by kylewangt** [comment]
> 哇塞，好的好的，真的开源的很是时候，请问哪里可以看到宣传的信息呢？有专门paddleocr的群吗，还是就在飞桨交流群里面会说？

请问下，现在印章识别的效果怎么样了？
