### ISSUE TITLE
paddleocr支持tensorrt推理吗

### ISSUE THREAD

**Issue by botao1995** [PaddlePaddle/PaddleOCR#2427]
paddleocr支持tensorrt推理吗

**Comment by tink2123** [comment]
支持的～ 编译的时候把这个开关打开https://github.com/PaddlePaddle/PaddleOCR/blob/e4ce3bf69c37e012d28db77e351412c0f2e5acf0/deploy/cpp_infer/CMakeLists.txt#L6

**Comment by lfxx** [comment]
> 支持的～ 编译的时候把这个开关打开
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e4ce3bf69c37e012d28db77e351412c0f2e5acf0/deploy/cpp_infer/CMakeLists.txt#L6

请问支持变长输入的tensorrt功能什么时候可以用呢

**Comment by kealennieh** [comment]
@tink2123  python版本是否同样支持TensorRT呢？我理解，只要paddlepaddle源码编译是带上了TensorRT，应该就可以支持paddleOCR的python接口使用tensorrt？
