### ISSUE TITLE
PaddleOCR在Windows端执行训练文件时遇到的问题

### ISSUE THREAD

**Issue by William9Baker** [PaddlePaddle/PaddleOCR#2428]
直接在pycharm右键运行训练文件时，
提示如下报错信息：
AssertionError: Please specify --config=configure_file_path.
百思不得其解，求大佬指导！

**Comment by WenmuZhou** [comment]
看看文档吧

**Comment by littletomatodonkey** [comment]
你好，可以参考这篇文档

https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md

![image](https://user-images.githubusercontent.com/14270174/114182255-00e28280-9975-11eb-9930-9910ab07dea6.png)

**Comment by BothCats** [comment]
解决了吗，我也出现这个问题了，这个问题不是再说==在说config文件吗，

**Comment by purblack** [comment]
解决了吗，我也遇到了这个问题。
