### ISSUE TITLE
中断之后继续训练没有继承epoch?

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleOCR#243]
中断继续训练后,模型参数可以继续加载,但是epoch是从0开始的,正常不是应该从中断epoch继续训练吗?另外模型是不是存在显存泄露问题,随着训练时间的增加,显存占用也逐渐增加.
```
python tools/train.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml
```

**Comment by SixGodGG** [comment]
python E:/GitHub/PaddleOCR/tools/train.py -c E:/GitHub/PaddleOCR/configs/det/det_mv3_db.yml -o Global.checkpoints=E:/GitHub/PaddleOCR/output/det_db/iter_epoch_200

类似我这样

**Comment by LDOUBLEV** [comment]
> 中断继续训练后,模型参数可以继续加载,但是epoch是从0开始的,正常不是应该从中断epoch继续训练吗?另外模型是不是存在显存泄露问题,随着训练时间的增加,显存占用也逐渐增加.
> 
> ```
> python tools/train.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml
> ```


epoch不是一个参数变量，在保存模型的时候不会保存epoch这个参数。
你提到的显存增加的问题没有复现出来，请问是训练一段时间后代码就死掉了吗？

**Comment by lfxx** [comment]
> > 中断继续训练后,模型参数可以继续加载,但是epoch是从0开始的,正常不是应该从中断epoch继续训练吗?另外模型是不是存在显存泄露问题,随着训练时间的增加,显存占用也逐渐增加.
> > ```
> > python tools/train.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml
> > ```
> 
> epoch不是一个参数变量，在保存模型的时候不会保存epoch这个参数。
> 你提到的显存增加的问题没有复现出来，请问是训练一段时间后代码就死掉了吗？

这个问题我自己增加了个start_epoch参数解决了,显存增加问题我重新启动训练后就没有出现过了,有问题再反馈:)
