### ISSUE TITLE
python PPOCRLabel.py --lang ch无法启动运行

### ISSUE THREAD

**Issue by bargainRule** [PaddlePaddle/PaddleOCR#2430]
在敲入python PPOCRLabel.py --lang ch命令后，出现如图所示情况，项目无法启动。
![image](https://user-images.githubusercontent.com/60413549/114176072-47cc7a00-996d-11eb-8058-6089dc32e884.png)

**Comment by MyGitHub-G** [comment]
补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)

**Comment by Evezerest** [comment]
pyqt版本是什么呢？

> 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)

**Comment by Evezerest** [comment]
> 在敲入python PPOCRLabel.py --lang ch命令后，出现如图所示情况，项目无法启动。
> ![image](https://user-images.githubusercontent.com/60413549/114176072-47cc7a00-996d-11eb-8058-6089dc32e884.png)

模型路径不建议使用中文哈

**Comment by bargainRule** [comment]
> pyqt版本是什么呢？
> 
> > 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> > ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)

![Uploading image.png…]()

**Comment by bargainRule** [comment]
> pyqt版本是什么呢？
> 
> > 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> > ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)

**Comment by bargainRule** [comment]
> pyqt版本是什么呢？
> 
> > 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> > ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)
PyQt5               5.15.4
PyQt5-Qt5           5.15.2
PyQt5-sip           12.8.1

**Comment by Evezerest** [comment]
> > pyqt版本是什么呢？
> > > 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> > > ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)
> > > PyQt5               5.15.4
> > > PyQt5-Qt5           5.15.2
> > > PyQt5-sip           12.8.1

应该是报错的第一行 imp module相关的问题

**Comment by MyGitHub-G** [comment]
> > > pyqt版本是什么呢？
> > > > 补充一下 上面的问题是 只显示配置文件，好像是正常运行了 但是不显示ppocrlabel窗口，和正常显示运行不一样
> > > > ![QQ图片20210409203624](https://user-images.githubusercontent.com/71758483/114180818-4d2cc300-9973-11eb-8310-90e062ccd794.png)
> > > > PyQt5               5.15.4
> > > > PyQt5-Qt5           5.15.2
> > > > PyQt5-sip           12.8.1
> 
> 应该是报错的第一行 imp module相关的问题

抱歉，我的没有问题 我的能够正常弹出窗口，提问者是我的队友，我只是解释一下提问者的问题，拿我的截图做个对比
