### ISSUE TITLE
use cmake  compiler  c++ version error：LNK2019,LNK2015,LNK2001,LNK2038

### ISSUE THREAD

**Issue by botao1995** [PaddlePaddle/PaddleOCR#2433]
![image](https://user-images.githubusercontent.com/47848566/114254184-746da980-99e0-11eb-8b38-8a0c51b42507.png)

**Comment by littletomatodonkey** [comment]
编译的时候，编译选项使用RelWithDebInfo试下

**Comment by botao1995** [comment]
> 编译的时候，编译选项使用RelWithDebInfo试下

行不通
