### ISSUE TITLE
训练自定义字符集时acc为0

### ISSUE THREAD

**Issue by ananas-hebo** [PaddlePaddle/PaddleOCR#2439]
在尝试训练中文，按照文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/recognition.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86

准备了一些demo数据，英文的可以但是中文的在训练过程中acc一致为0，也无法正常infer_rec出预想的结果。
在调试代码中发现，decode不出来数据所以acc为0。
![image](https://user-images.githubusercontent.com/5362672/114263772-1958a880-9a1a-11eb-85fe-5a902063cf6c.png)

检查了配置没看出问题，训练所用的demo yml和数据，我提交了一份，希望帮忙看一下。
[demo_train.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6289502/demo_train.zip)

**Comment by littletomatodonkey** [comment]
你好，你这个更改了训练字典，所以最后的fc层在微调的时候，无法加载，需要从头学习，训练集图片数据太少。另外这种中文的预训练模型建议使用

https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_pre.tar

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md#%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

**Comment by ananas-hebo** [comment]
@littletomatodonkey 感谢回复，指点迷津。
1 更换了model
2 还原了 character_dict_path 配置
可以正常工作了
