### ISSUE TITLE
英文attn识别模型rec_mv3_tps_bilstm_attn.tar，导出成功了，推理的时候没有识别结果

### ISSUE THREAD

**Issue by aceyw** [PaddlePaddle/PaddleOCR#244]
导出命令
python3 tools/export_model.py \
    -c configs/rec/rec_mv3_tps_bilstm_attn.yml \
    -o Global.checkpoints=./rec_mv3_tps_bilstm_attn/best_accuracy \
    Global.save_inference_dir=./rec_mv3_tps_bilstm_attninfer/ \
    Global.use_gpu=False
导出时的提示信息
save success, output_name_list: ['decoded_out', 'predicts']
导出文件保存在 ./rec_mv3_tps_bilstm_attninfer 文件夹下面

识别时的推理命令
python3 tools/infer/predict_rec.py \
    --use_gpu=False \
    --rec_algorithm="RARE" \
    --rec_model_dir="./rec_mv3_tps_bilstm_attninfer/" \
    --rec_image_shape="3,32,100" \
    --rec_char_type="en" \
    --rec_char_dict_path="" \
    --image_dir="./doc/imgs_words_en/"   
没有识别到内容，提示信息
Predicts of ./doc/imgs_words_en/word_10.png:['', nan]
Predicts of ./doc/imgs_words_en/word_116.png:['', nan]
Predicts of ./doc/imgs_words_en/word_19.png:['', nan]
Predicts of ./doc/imgs_words_en/word_201.png:['', nan]
Predicts of ./doc/imgs_words_en/word_308.png:['', nan]
Predicts of ./doc/imgs_words_en/word_336.png:['', nan]
Predicts of ./doc/imgs_words_en/word_401.png:['', nan]
Predicts of ./doc/imgs_words_en/word_461.png:['', nan]
Predicts of ./doc/imgs_words_en/word_52.png:['', nan]
Predicts of ./doc/imgs_words_en/word_545.png:['', nan]
Total predict time for 10 images:0.195

我现在在学习和使用attention的识别模型，希望能够尽快掌握、对这个比较着急。请帮忙尽快解决一下，不胜感激，谢谢~

**Comment by SixGodGG** [comment]
一样的问题，官方还没有解决。

**Comment by tink2123** [comment]
@aceyw 这个问题是save_inference_model在paddle1.7.1版本上有bug，麻烦更新paddle版本至1.8.1再尝试一下

**Comment by SixGodGG** [comment]
> @aceyw 这个问题是save_inference_model在paddle1.7.1版本上有bug，麻烦更新paddle版本至1.8.1再尝试一下

1.8.1 之前好像ocr用不了，现在可以了对吧

**Comment by tink2123** [comment]
>1.8.1 之前好像ocr用不了，现在可以了对吧

是的

**Comment by aceyw** [comment]
用paddle1.8.2试了一下，可以了。谢谢，你们真棒

**Comment by tink2123** [comment]
好的，不客气的～
