### ISSUE TITLE
怎么提高单个字的识别效果

### ISSUE THREAD

**Issue by dinglei0719** [PaddlePaddle/PaddleOCR#2445]
最近在基于PaddleOCR做表格识别，切分完单元格之后对每个单元格的子图进行OCR，结果一些序号的1，2，3，...之类识别不出来，求教应该怎么优化？
原始图片：
![image](https://user-images.githubusercontent.com/6258286/114335241-eda30300-9b7e-11eb-97a1-16283d33d6f0.png)
切分后单元格的图片：
![image](https://user-images.githubusercontent.com/6258286/114335321-188d5700-9b7f-11eb-8d89-5202c37d9c4d.png)
这个“1”识别不出来

**Comment by zxingkong** [comment]
对的，个位数数字，很难识别.....感觉应该需要自己训练模型才行

**Comment by MissPenguin** [comment]
单字一般是因为检测容易漏掉，可以补充一些单字数据优化一下检测模型。
