### ISSUE TITLE
pgnet识别中文的话，是不是会很慢

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#2447]

**Comment by JetHong** [comment]
目前开源的PGNet模型，目前是只支持英文数字，对于识别中文需要自己添加数据集，改相应的配置文件。速度的话，可以转为inference模型在进行预测，效果应该是挺可观的

**Comment by lgcy** [comment]
> 目前开源的PGNet模型，目前是只支持英文数字，对于识别中文需要自己添加数据集，改相应的配置文件。速度的话，可以转为inference模型在进行预测，效果应该是挺可观的

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/ppocr/modeling/heads/e2e_pg_head.py#L181，如果中文有6000多类，这么大的一个卷积，速度不会受影响吗

**Comment by Williamwsk** [comment]
> > 目前开源的PGNet模型，目前是只支持英文数字，对于识别中文需要自己添加数据集，改相应的配置文件。速度的话，可以转为inference模型在进行预测，效果应该是挺可观的
> 
> [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/ppocr/modeling/heads/e2e_pg_head.py#L181，如果中文有6000多类，这么大的一个卷积，速度不会受影响吗](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/ppocr/modeling/heads/e2e_pg_head.py#L181%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%B8%AD%E6%96%87%E6%9C%896000%E5%A4%9A%E7%B1%BB%EF%BC%8C%E8%BF%99%E4%B9%88%E5%A4%A7%E7%9A%84%E4%B8%80%E4%B8%AA%E5%8D%B7%E7%A7%AF%EF%BC%8C%E9%80%9F%E5%BA%A6%E4%B8%8D%E4%BC%9A%E5%8F%97%E5%BD%B1%E5%93%8D%E5%90%97)

同问，我对这个也存有疑问，麻烦博主解释下
