### ISSUE TITLE
Question about deformable convolution 

### ISSUE THREAD

**Issue by gaizerik** [PaddlePaddle/PaddleOCR#2450]
Hi, thanks for sharing your great work here.

I got a question about deformable convolution.
In the original version of Deformable Binarization, author reported accuracy improvement using deformable convolution, which I cannot see in you ppocr detector backbone code.
Have you decided not to use deformable convolution because it's not worth the computational power?

**Comment by MissPenguin** [comment]
Yes, you're right. You can add it yourself if necessary~

**Comment by gaizerik** [comment]
> Yes, you're right. You can add it yourself if necessary~

Thanks!
