### ISSUE TITLE
Paddle OCR微信验证码失效

### ISSUE THREAD

**Issue by zhtyyx** [PaddlePaddle/PaddleOCR#2451]
请问可以拉我进一下群吗？Paddlepaddle总群里的管理员小伙伴告诉我可以提issue来加群

**Comment by zhtyyx** [comment]
ZHT-Hunter

**Comment by MissPenguin** [comment]
再扫一次试试呢，刚试着是好的呢。还是不行的话，可以添加MissPenguin41，备注OCR，拉你入群。
