### ISSUE TITLE
标注资料疑问

### ISSUE THREAD

**Issue by JescalLin** [PaddlePaddle/PaddleOCR#2456]
我想加一些资料去finetune 但这个LOT其实不需要侦测到
我还需要标注它吗？
另外想问一下
1.标注留白边大约要留多少？ 上面这样标可以吗？
2.像是这种dot-matrix文字，有什么可以做的优化 让辨识效果更好
谢谢

![123](https://user-images.githubusercontent.com/19463066/114358350-67e67e00-9ba5-11eb-862a-b2fa6de9c43d.png)
![456](https://user-images.githubusercontent.com/19463066/114358351-67e67e00-9ba5-11eb-9d98-aa616d29e3f4.png)

**Comment by MissPenguin** [comment]
可以不标注“LOT”；
留白宽度没有严格限制，你这样标就可以了；
点阵文字目前ppocr模型直接识别效果会差点，因为训练数据里类似数据比较少，自己标注一批finetune一下效果应该能明显提升。

**Comment by JescalLin** [comment]
@MissPenguin Thanks!
