### ISSUE TITLE
Rec 训练文档需修改

### ISSUE THREAD

**Issue by SixGodGG** [PaddlePaddle/PaddleOCR#246]
![QQ截图20200622093024](https://user-images.githubusercontent.com/6395366/85240527-14b30b80-b46b-11ea-85cb-3b8c91a7af57.jpg)

rec_icdar15_train.yml中无character_dict_path 字段，请修改文档。

**Comment by lfxx** [comment]
> ![QQ截图20200622093024](https://user-images.githubusercontent.com/6395366/85240527-14b30b80-b46b-11ea-85cb-3b8c91a7af57.jpg)
> 
> rec_icdar15_train.yml中无character_dict_path 字段，请修改文档。

这个自己在yml文件里增加就行,训练的时候会自动读取这个参数

**Comment by SixGodGG** [comment]
好的 但文档应该说明一下？
是不是这些都可以手动添加到yml文件中？
![QQ截图20200622104923](https://user-images.githubusercontent.com/6395366/85244040-2057ff80-b476-11ea-9e75-acfe9fe05cda.jpg)
