### ISSUE TITLE
怎么在训练时加入Transform --TPS。比如在CRNN配置文件里面加，配置文件如何写呢？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#2461]

**Comment by MissPenguin** [comment]
configs里有带tps的配置文件，可以参考～
![image](https://user-images.githubusercontent.com/25809855/114486164-e7289000-9c3f-11eb-9d79-39601e2d12fa.png)

**Comment by aishangmaxiaoming** [comment]
> configs里有带tps的配置文件，可以参考～
> ![image](https://user-images.githubusercontent.com/25809855/114486164-e7289000-9c3f-11eb-9d79-39601e2d12fa.png)

想问下1.选large和small什么原则。2.训练时加入tps，推理时CRNN也要改代码吗？

**Comment by MissPenguin** [comment]
1. 选large还是small就看你更看重精度还是速度
2. 带tps的推理不需要改代码，但需要指定算法名称，例如用的RARE算法则需要在推理时传入参数--rec_algorithm="RARE"。但如果你不是直接用项目提供的带tps的算法，而是自己在crnn基础上改，那推理代码可能也需要修改。

**Comment by aishangmaxiaoming** [comment]
> * 选large还是small就看你更看重精度还是速度
> * 带tps的推理不需要改代码，但需要指定算法名称，例如用的RARE算法则需要在推理时传入参数--rec_algorithm="RARE"。但如果你不是直接用项目提供的带tps的算法，而是自己在crnn基础上改，那推理代码可能也需要修改。
好的，谢谢
