### ISSUE TITLE
关于服务器端模型的backbone

### ISSUE THREAD

**Issue by yukun80** [PaddlePaddle/PaddleOCR#2466]
为什么官方的预测模型使用的是ResNet50而不是PaddleClas曲线图中更漂亮的ResNet50_vd_ssid_v2呢？
![t4 fp32 bs1 main_fps_top1](https://user-images.githubusercontent.com/60764816/114413943-fe846080-9be0-11eb-96c0-6519e738d125.png)

**Comment by MissPenguin** [comment]
ssld模型是蒸馏模型，网络结构还是resnet50
