### ISSUE TITLE
ocr.ocr  怎么样才能关闭输出

### ISSUE THREAD

**Issue by wanghaotian233** [PaddlePaddle/PaddleOCR#2467]
[2021/04/12 11:16:23] root INFO: dt_boxes num : 14, elapse : 0.02325296401977539
[2021/04/12 11:16:23] root INFO: rec_res num  : 14, elapse : 0.0431065559387207

如题，不想打印上面这些信息

**Comment by MissPenguin** [comment]
把打印log的代码注释掉即可：
https://github.com/PaddlePaddle/PaddleOCR/blob/010e94d6b638b860dfd487e4f7229b6efef6b433/tools/infer/predict_system.py#L91
https://github.com/PaddlePaddle/PaddleOCR/blob/010e94d6b638b860dfd487e4f7229b6efef6b433/tools/infer/predict_system.py#L110

**Comment by lmw0320** [comment]
今天刚测试了下，用下面的方法可以关闭这个DEBUG的输出：
from paddleocr import paddleocr
paddleocr.logging.disable(logging.DEBUG)
