### ISSUE TITLE
弯曲文本数据

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#247]
请问哪一版的icdar数据支持弯曲文本标注，我见大部分都是标注的四个点，DB代码里对于弯曲文本是怎样训练的呢？

**Comment by MissPenguin** [comment]
DB代码里针对弯曲文本的逻辑还没加进去，近期会进行补全。

**Comment by wangning7149** [comment]
> 
> 
> DB代码里针对弯曲文本的逻辑还没加进去，近期会进行补全。

期待中~~~~~~

**Comment by WenmuZhou** [comment]
@MissPenguin db针对弯曲的label制作是没问题的
