### ISSUE TITLE
总结下自己踩过的坑（关于训练模型和推理模型效果不一致问题），也方便后来者看看，也希望开发人员能看看怎么优化，或者加入FAQ

### ISSUE THREAD

**Issue by ioracion** [PaddlePaddle/PaddleOCR#2470]
#### 潜在因素1
[是训练模型和预测模型的预处理不一致导致的，按照PR的内容修改下代码再试试](https://github.com/PaddlePaddle/PaddleOCR/issues/2080#issuecomment-784848027)

#### 潜在因素1
[现在默认会对中文图片resize，可以试着注释掉这两行，看下结果会不会一致](https://github.com/PaddlePaddle/PaddleOCR/issues/214#issuecomment-645346661)

#### 潜在因素2
训练用和推理用的字典要相同！要相同！相同！同！

#### 1
infer目录下的[utility.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/infer/utility.py)和对应的yml文件参数可能没对齐

#### 2
即使上面都确认无误后，paddleocr.ocr()初始化后还是发现参数不对，这时要看看[paddleocr.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/paddleocr.py)文件中的相关参数，也要对齐下

#### 3
[好好看看转换模型的文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/inference.md)

**Comment by MissPenguin** [comment]
赞，谢谢反馈！～

确实参数对齐这里容易踩坑，训练模型用的yml中的参数一般是为了eval能对齐公开数据集上的指标，而预测模型的参数适配的通用的中文场景，所以会有些diff，另外代码多次迭代也导致了一些没对齐的问题。

给大家带来了困扰非常抱歉，有问题欢迎随时提issue，我们也记到小本本，看看怎么优化一下或者加FAQ！

**Comment by ddz-mark** [comment]
请问：自己训练的 文本识别 rec 模型，同一批测试集，inference模型与eval模型最后的准确率差距很大，为什么？

**Comment by WenmuZhou** [comment]
看看infer和eval点预处理是不是一致

**Comment by ddz-mark** [comment]
我直接使用 v2.0 版本的源码，需要改动什么参数么？

**Comment by ioracion** [comment]
> 我直接使用 v2.0 版本的源码，需要改动什么参数么？

默认有些文件的参数不是对齐的，检查下

**Comment by Dandelion111** [comment]
> ### (det)检测模型转换后效果不一致
> #### 潜在因素1
> [是训练模型和预测模型的预处理不一致导致的，按照PR的内容修改下代码再试试](https://github.com/PaddlePaddle/PaddleOCR/issues/2080#issuecomment-784848027)
> 
> ### (rec)识别模型转换后效果不一致（主要针对中英文混合场景）
> #### 潜在因素1
> [现在默认会对中文图片resize，可以试着注释掉这两行，看下结果会不会一致](https://github.com/PaddlePaddle/PaddleOCR/issues/214#issuecomment-645346661)
> 
> #### 潜在因素2
> 训练用和推理用的字典要相同！要相同！相同！同！
> 
> ### Common潜在因素
> #### 1
> infer目录下的[utility.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/infer/utility.py)和对应的yml文件参数可能没对齐
> 
> #### 2
> 即使上面都确认无误后，paddleocr.ocr()初始化后还是发现参数不对，这时要看看[paddleocr.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/paddleocr.py)文件中的相关参数，也要对齐下
> 
> #### 3
> [好好看看转换模型的文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/inference.md)

请问大佬解决这个问题了吗？我也遇到了这个情况，自己训练的DBNet模型用官方python预测代码可以检测的很好，模型到处为推理模型之后，用cpp推理却检测不到？好奇怪

**Comment by ioracion** [comment]
我是解决了（纯python），cpp就母鸡了，估计还是哪里参数没对齐...（这点真的坑
