### ISSUE TITLE
文字识别的数据增强

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#2472]
识别的数据增强只需要在配置文件中设置distort: true就可以了吧？训练完测试怎么感觉像没加扰动一样

**Comment by MissPenguin** [comment]
识别加数据增强需要在yml中加RecAug参数，不用写值，参考这里：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L71

**Comment by aishangmaxiaoming** [comment]
> 识别加数据增强需要在yml中加RecAug参数，不用写值，参考这里：
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L71

<img width="527" alt="image" src="https://user-images.githubusercontent.com/67897601/114527631-cc274180-9c7a-11eb-9fdf-1f702faba869.png">
不写值默认数据增强吗，RecAug:  冒号后面什么也不加？

**Comment by MissPenguin** [comment]
> > 识别加数据增强需要在yml中加RecAug参数，不用写值，参考这里：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L71
> 
> <img alt="image" width="527" src="https://user-images.githubusercontent.com/67897601/114527631-cc274180-9c7a-11eb-9fdf-1f702faba869.png">
> 
> 不写值默认数据增强吗，RecAug: 冒号后面什么也不加？

嗯嗯，不加参数是按照默认的增强参数生效，包括增强的概率等，也可以增加一些参数进行修改，具体可以看看RecAug部分的代码。

**Comment by gyr-kdgc** [comment]
请问distort：true是添加在Global下面吗？还是添加在Train的loader下面？

**Comment by lybcodes** [comment]
> 请问distort：true是添加在Global下面吗？还是添加在Train的loader下面？

Global下面

**Comment by lybcodes** [comment]
> 识别加数据增强需要在yml中加RecAug参数，不用写值，参考这里：
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L71

还有个问题，我看了下文档里说识别的数据增强目前是只支持Linux下训练是吗？
