### ISSUE TITLE
Xavier上PaddleOCR C++ demo无输出问题

### ISSUE THREAD

**Issue by Crystalxd** [PaddlePaddle/PaddleOCR#2473]
在Xavier上编译生成了ocr_system二进制程序，运行demo时一直没有输出，模型是官方的mobile全套模型，图片也是官方测试图片
![image](https://user-images.githubusercontent.com/34636084/114506938-0a196b00-9c65-11eb-8af9-56a91ff7d354.png)
（这是测试结果）
求解。

config.txt如下：
# model load config
use_gpu 1
gpu_id  0
gpu_mem  4000
cpu_math_library_num_threads  10
use_mkldnn 0

# det config
max_side_len  960
det_db_thresh  0.3
det_db_box_thresh  0.5
det_db_unclip_ratio  1.6
det_model_dir  ./inference/ch_ppocr_mobile_v2.0_det_infer/

# cls config
use_angle_cls 0
cls_model_dir  ./inference/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh  0.9

# rec config
rec_model_dir  ./inference/ch_ppocr_mobile_v2.0_rec_infer/
char_list_file ../../ppocr/utils/ppocr_keys_v1.txt

# show the detection results
visualize 1

# use_tensorrt
use_tensorrt 0
use_fp16   0

**Comment by WenmuZhou** [comment]
det_db_box_thresh 这个值调到0看看

**Comment by Crystalxd** [comment]
@WenmuZhou 
![image](https://user-images.githubusercontent.com/34636084/114686351-46bc9380-9d45-11eb-998b-58e287126bc0.png)
还是没有输出

**Comment by Crystalxd** [comment]
附加：paddleOCR和Paddle预测库均是release/2.0.1版本

**Comment by Crystalxd** [comment]
@WenmuZhou 还有一个奇怪的一点是：我修改了src/main.cpp里面的代码，比如价格std::cout语句打印一段字符串，重编译后运行并没有修改显示我加上去的那段字符串。除此之外，我使用错误的语法去编译依然可以编译通过，似乎没有用到src里面的main.cpp

**Comment by Crystalxd** [comment]
@WenmuZhou 
nvidia@nvidia-desktop:~/projects/PaddleOCR/deploy/cpp_infer$ ./tools/build.sh 
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable exact version "10.0") 
-- Found OpenCV: /home/nvidia/local_install (found version "3.3.1") 
cmake cxx flags -g -o3  -std=c++11
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:208 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "ocr_system" links to some libraries for which the linker
  must search:

    glog, gflags, protobuf, z, xxhash, -ldl -lrt -lgomp -lz -lm -lpthread

  and other libraries with known full path:

    /home/nvidia/projects/paddle_inference_install_dir/third_party/install/openblas/lib/libopenblas.a
    /home/nvidia/local_install/lib/libopencv_cudabgsegm.so.3.3.1

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_TENSORRT


-- Build files have been written to: /home/nvidia/projects/PaddleOCR/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[100%] Linking CXX executable ocr_system
[100%] Built target ocr_system

这是我编译阶段log

**Comment by wangye707** [comment]
@Crystalxd 你的paddle是自己编译的还是下载官方的？

**Comment by wangye707** [comment]
@Crystalxd 你编译的cmake指令发一下

**Comment by Crystalxd** [comment]
@WenmuZhou 
paddle是直接下载官方的（地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html）里面的nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)，和我的Xavier环境是一致的。

paddlOCR的编译指令就是修改了./tool/build.sh的路径直接运行的，路径都没有问题
OPENCV_DIR=your_opencv_dir
LIB_DIR=your_paddle_inference_dir
CUDA_LIB_DIR=your_cuda_lib_dir
CUDNN_LIB_DIR=your_cudnn_lib_dir

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=OFF \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \

make -j

**Comment by ycdhqzhiai** [comment]
> @WenmuZhou
> paddle是直接下载官方的（地址：[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html）里面的nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)，和我的Xavier环境是一致的。](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html%EF%BC%89%E9%87%8C%E9%9D%A2%E7%9A%84nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)%EF%BC%8C%E5%92%8C%E6%88%91%E7%9A%84Xavier%E7%8E%AF%E5%A2%83%E6%98%AF%E4%B8%80%E8%87%B4%E7%9A%84%E3%80%82)
> 
> paddlOCR的编译指令就是修改了./tool/build.sh的路径直接运行的，路径都没有问题
> OPENCV_DIR=your_opencv_dir
> LIB_DIR=your_paddle_inference_dir
> CUDA_LIB_DIR=your_cuda_lib_dir
> CUDNN_LIB_DIR=your_cudnn_lib_dir
> 
> BUILD_DIR=build
> rm -rf ${BUILD_DIR}
> mkdir ${BUILD_DIR}
> cd ${BUILD_DIR}
> cmake ..
> -DPADDLE_LIB=${LIB_DIR}
> -DWITH_MKL=ON
> -DWITH_GPU=OFF
> -DWITH_STATIC_LIB=OFF
> -DUSE_TENSORRT=OFF
> -DOPENCV_DIR=${OPENCV_DIR}
> -DCUDNN_LIB=${CUDNN_LIB_DIR}
> -DCUDA_LIB=${CUDA_LIB_DIR} \
> 
> make -j

@Crystalxd https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html。。。你这个地址挂了？？？我怎么访问就到使用教程页面了，jetson的编译doc能分享下吗

**Comment by ycdhqzhiai** [comment]
> @WenmuZhou
> paddle是直接下载官方的（地址：[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html）里面的nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)，和我的Xavier环境是一致的。](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html%EF%BC%89%E9%87%8C%E9%9D%A2%E7%9A%84nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)%EF%BC%8C%E5%92%8C%E6%88%91%E7%9A%84Xavier%E7%8E%AF%E5%A2%83%E6%98%AF%E4%B8%80%E8%87%B4%E7%9A%84%E3%80%82)
> 
> paddlOCR的编译指令就是修改了./tool/build.sh的路径直接运行的，路径都没有问题
> OPENCV_DIR=your_opencv_dir
> LIB_DIR=your_paddle_inference_dir
> CUDA_LIB_DIR=your_cuda_lib_dir
> CUDNN_LIB_DIR=your_cudnn_lib_dir
> 
> BUILD_DIR=build
> rm -rf ${BUILD_DIR}
> mkdir ${BUILD_DIR}
> cd ${BUILD_DIR}
> cmake ..
> -DPADDLE_LIB=${LIB_DIR}
> -DWITH_MKL=ON
> -DWITH_GPU=OFF
> -DWITH_STATIC_LIB=OFF
> -DUSE_TENSORRT=OFF
> -DOPENCV_DIR=${OPENCV_DIR}
> -DCUDNN_LIB=${CUDNN_LIB_DIR}
> -DCUDA_LIB=${CUDA_LIB_DIR} \
> 
> make -j
@Crystalxd  你这个地址现在是改了吗？ 我访问进去是使用文档页面，能把你编译nvidia jetson的doc分享下吗？或者分享下链接

**Comment by ycdhqzhiai** [comment]
> @WenmuZhou
> paddle是直接下载官方的（地址：[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html）里面的nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)，和我的Xavier环境是一致的。](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html%EF%BC%89%E9%87%8C%E9%9D%A2%E7%9A%84nv_jetson_cuda10_cudnn7.6_trt6_all(jetpack4.3)%EF%BC%8C%E5%92%8C%E6%88%91%E7%9A%84Xavier%E7%8E%AF%E5%A2%83%E6%98%AF%E4%B8%80%E8%87%B4%E7%9A%84%E3%80%82)
> 
> paddlOCR的编译指令就是修改了./tool/build.sh的路径直接运行的，路径都没有问题
> OPENCV_DIR=your_opencv_dir
> LIB_DIR=your_paddle_inference_dir
> CUDA_LIB_DIR=your_cuda_lib_dir
> CUDNN_LIB_DIR=your_cudnn_lib_dir
> 
> BUILD_DIR=build
> rm -rf ${BUILD_DIR}
> mkdir ${BUILD_DIR}
> cd ${BUILD_DIR}
> cmake ..
> -DPADDLE_LIB=${LIB_DIR}
> -DWITH_MKL=ON
> -DWITH_GPU=OFF
> -DWITH_STATIC_LIB=OFF
> -DUSE_TENSORRT=OFF
> -DOPENCV_DIR=${OPENCV_DIR}
> -DCUDNN_LIB=${CUDNN_LIB_DIR}
> -DCUDA_LIB=${CUDA_LIB_DIR} \
> 
> make -j


@Crystalxd 你这个地址现在是改了吗？ 我访问进去是使用文档页面，能把你编译nvidia jetson的doc分享下吗？或者分享下链接
