### ISSUE TITLE
用det_r50_vd_sast_totaltext.yml 训练的时，一直卡在eval-model

### ISSUE THREAD

**Issue by chunniunai220ml** [PaddlePaddle/PaddleOCR#2474]
用det_r50_vd_sast_totaltext.yml 训练的时，一直卡在eval-model,也不报错，就一直卡着，v100也有还有空间，训练就很正常，这可能是哪里出了问题？
config里面只修改了数据路径相关

又一次报过这个错误：
numpy.core._exceptions.MemoryError: Unable to allocate 1.83 GiB for an array with shape (21979, 11178) and data type float64.   昨天是这里报过错，后来就没报错

**Comment by WenmuZhou** [comment]
在跑预测吧，可能图片比较大，跑的很慢

**Comment by chunniunai220ml** [comment]
> 在跑预测吧，可能图片比较大，跑的很慢
跑训练，训练正常，但是到了eval就卡死了

**Comment by chunniunai220ml** [comment]
正常eavl.py也能测试，就是很慢，增加numwork也比较慢，但是db版本速度就正常

**Comment by YY007H** [comment]
我也是卡在这里，解决了吗？
