### ISSUE TITLE
PPOCRLabel标注问题

### ISSUE THREAD

**Issue by shen2009fei** [PaddlePaddle/PaddleOCR#2480]
真实图片有中英文混合，但是只需要提取 一部分的英文和数字（有很多英文和数字），请问可以用PPOCRLabel准备训练数据的时候，只需要框选自己感兴趣的那一部分英文和数字，还是所有有文字的地方，或者是框选全部的英文和数字？

**Comment by JescalLin** [comment]
@shen2009fei 我问过类似的问题 我只标我想要的区域 训练起来没问题
#2456 

![0005](https://user-images.githubusercontent.com/19463066/114676845-4f5c9c00-9d3c-11eb-8955-c8602698ef7d.jpg)

**Comment by shen2009fei** [comment]
> @shen2009fei 我问过类似的问题 我只标我想要的区域 训练起来没问题
> #2456
> 
> ![0005](https://user-images.githubusercontent.com/19463066/114676845-4f5c9c00-9d3c-11eb-8955-c8602698ef7d.jpg)

识别应该是没啥问题，但是检测呢？不知道会不会影响
