### ISSUE TITLE
中文文档文字识别

### ISSUE THREAD

**Issue by yukun80** [PaddlePaddle/PaddleOCR#2481]
为什么中文文档文字识别的数据里面txt文件后面的格式是坐标数据，而不是图片文字呢？
![image](https://user-images.githubusercontent.com/60764816/114556908-bece7f00-9c9b-11eb-9ca6-52c4939d3392.png)
![image](https://user-images.githubusercontent.com/60764816/114556938-c68e2380-9c9b-11eb-95af-5a386ef9bbd3.png)

**Comment by yukun80** [comment]
![image](https://user-images.githubusercontent.com/60764816/114557036-d9085d00-9c9b-11eb-8b3e-93b92d01e728.png)
这里的训练数据

**Comment by WenmuZhou** [comment]
这个不是坐标，是字符在字典里的索引，字典是这个
![Uploading image.png…]()
