### ISSUE TITLE
ImportError: cannot import name 'inference' from 'paddle' (/anaconda/envs/open-mmlab/lib/python3.7/site-packages/paddle/__init__.py)

### ISSUE THREAD

**Issue by Rahul2203** [PaddlePaddle/PaddleOCR#2484]
I am following the installation guideline as mentioned in the documentation. 
I am getting this error while importing 
from paddleocr import PaddleOCR,draw_ocr

**Comment by WenmuZhou** [comment]
升级paddle到2.0
