### ISSUE TITLE
个别字母识别错误有什么好的解决办法吗？

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleOCR#2486]
我的图片中要识别是一行字符，长度为4，两位英文字母+两位数字，预训练模型用的官方的中英文通用OCR模型，然后训练的时候检测用DB+识别用Rosetta，识别出来结果个别英文字母识别出错，比如N识别成R，H识别成A等等。想请教下有啥建议没有

**Comment by lybcodes** [comment]
这个是不是会跟我训练集里面英文字母出现的频次有关，有的字母出现的次数少甚至没有，而有的字母出现很多次

**Comment by mikeshi80** [comment]
还有数量有关，如果弄个几十万的样本，效果会有提升，另外，还要考虑用什么模型，比如MobileNetV3核ResNet 50就相差较大
