### ISSUE TITLE
服务部署与移动端部署中，服务端部署，什么时候ready呢？

### ISSUE THREAD

**Issue by qiaoning** [PaddlePaddle/PaddleOCR#249]
服务部署与移动端部署
预计6月中下旬会先后发布基于Serving的服务部署方案和基于Paddle Lite的移动端部署方案，欢迎持续关注。

6月底可以支持不？

**Comment by MissPenguin** [comment]
差不多，6月底，7月初的样子

**Comment by fujianhai** [comment]
@MissPenguin， 同问，基于Serving的服务部署方案可以在端午节前发布吗？

**Comment by MissPenguin** [comment]
> @MissPenguin， 同问，基于Serving的服务部署方案可以在端午节前发布吗？

端午节前应该发布不了，Serving官网有用PaddleOCR做的demo，可以试着自己搭一下～ 
检测服务：https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/ocr_detection
识别服务：https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/ocr

**Comment by grasswolfs** [comment]
> @MissPenguin， 同问，基于Serving的服务部署方案可以在端午节前发布吗？

你也可以试试这个，https://aistudio.baidu.com/aistudio/projectdetail/507159 的第五部分
最近速度还是不是特别理想，最近还会再优化一版

**Comment by fujianhai** [comment]
好的，多谢。
