### ISSUE TITLE
hubserving部署启动时报错

### ISSUE THREAD

**Issue by zhaoyantao-murray** [PaddlePaddle/PaddleOCR#2490]
在win下按照hubserving文档指导进行部署过程中报错，麻烦老哥指导！十分感谢
(paddleocr) C:\Users\www19\PycharmProjects\PaddleOCR>pip install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: paddlehub in c:\anaconda3\envs\paddleocr\lib\site-packages (2.0.4)
Requirement already satisfied: gitpython in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (3.1.14)
Requirement already satisfied: matplotlib in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (3.3.4)
Requirement already satisfied: colorama in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (0.4.4)
Requirement already satisfied: numpy in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (1.19.3)
Requirement already satisfied: rarfile in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (4.0)
Requirement already satisfied: paddlenlp>=2.0.0rc5 in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (2.0.0rc8)
Requirement already satisfied: filelock in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (3.0.12)
Requirement already satisfied: colorlog in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (4.7.2)
Requirement already satisfied: Pillow in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (8.1.0)
Requirement already satisfied: easydict in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (1.9)
Requirement already satisfied: tqdm in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (4.56.0)
Requirement already satisfied: visualdl>=2.0.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (2.1.1)
Requirement already satisfied: pyyaml in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (5.4.1)
Requirement already satisfied: packaging in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (20.9)
Requirement already satisfied: flask>=1.1.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (1.1.2)
Requirement already satisfied: opencv-python in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (4.2.0.32)
Requirement already satisfied: pyzmq in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlehub) (22.0.3)
Requirement already satisfied: Werkzeug>=0.15 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flask>=1.1.0->paddlehub) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flask>=1.1.0->paddlehub) (2.11.3)
Requirement already satisfied: click>=5.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flask>=1.1.0->paddlehub) (7.1.2)
Requirement already satisfied: itsdangerous>=0.24 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flask>=1.1.0->paddlehub) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\anaconda3\envs\paddleocr\lib\site-packages (from Jinja2>=2.10.1->flask>=1.1.0->paddlehub) (1.1.1)
Requirement already satisfied: jieba in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlenlp>=2.0.0rc5->paddlehub) (0.42.1)
Requirement already satisfied: seqeval in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlenlp>=2.0.0rc5->paddlehub) (1.2.2)
Requirement already satisfied: h5py in c:\anaconda3\envs\paddleocr\lib\site-packages (from paddlenlp>=2.0.0rc5->paddlehub) (3.2.1)
Requirement already satisfied: pre-commit in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (2.10.1)
Requirement already satisfied: flake8>=3.7.9 in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (3.8.4)
Requirement already satisfied: protobuf>=3.11.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (3.14.0)
Requirement already satisfied: shellcheck-py in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (0.7.1.1)
Requirement already satisfied: requests in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (2.25.1)
Requirement already satisfied: bce-python-sdk in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (0.8.53)
Requirement already satisfied: Flask-Babel>=1.0.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (2.0.0)
Requirement already satisfied: six>=1.14.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from visualdl>=2.0.0->paddlehub) (1.15.0)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->paddlehub)
(2.2.0)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->paddle
hub) (2.6.0)
Requirement already satisfied: importlib-metadata in c:\anaconda3\envs\paddleocr\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->paddlehub) (3.4
.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->paddlehub) (0
.6.1)
Requirement already satisfied: pytz in c:\anaconda3\envs\paddleocr\lib\site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->paddlehub) (2021.1)
Requirement already satisfied: Babel>=2.3 in c:\anaconda3\envs\paddleocr\lib\site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->paddlehub) (2.9.0)

Requirement already satisfied: future>=0.6.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from bce-python-sdk->visualdl>=2.0.0->paddlehub) (0.18.2)

Requirement already satisfied: pycryptodome>=3.8.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from bce-python-sdk->visualdl>=2.0.0->paddlehub) (3
.9.9)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from gitpython->paddlehub) (4.0.5)
Requirement already satisfied: smmap<4,>=3.0.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->paddlehub) (3.0.5)
Requirement already satisfied: cached-property in c:\anaconda3\envs\paddleocr\lib\site-packages (from h5py->paddlenlp>=2.0.0rc5->paddlehub) (1.5.2)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\anaconda3\envs\paddleocr\lib\site-packages (from importlib-metadata->flake8>=3.7.9->visual
dl>=2.0.0->paddlehub) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in c:\anaconda3\envs\paddleocr\lib\site-packages (from importlib-metadata->flake8>=3.7.9->visualdl>=2.0.0->padd
lehub) (3.4.0)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\envs\paddleocr\lib\site-packages (from matplotlib->paddlehub) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from matplotlib->paddlehub) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\anaconda3\envs\paddleocr\lib\site-packages (from matplotlib->paddlehub) (2
.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from matplotlib->paddlehub) (1.3.1)
Requirement already satisfied: cfgv>=2.0.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from pre-commit->visualdl>=2.0.0->paddlehub) (3.2.0)
Requirement already satisfied: identify>=1.0.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from pre-commit->visualdl>=2.0.0->paddlehub) (1.5.13)
Requirement already satisfied: nodeenv>=0.11.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from pre-commit->visualdl>=2.0.0->paddlehub) (1.5.0)
Requirement already satisfied: virtualenv>=20.0.8 in c:\anaconda3\envs\paddleocr\lib\site-packages (from pre-commit->visualdl>=2.0.0->paddlehub) (20.4.2
)
Requirement already satisfied: toml in c:\anaconda3\envs\paddleocr\lib\site-packages (from pre-commit->visualdl>=2.0.0->paddlehub) (0.10.2)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\anaconda3\envs\paddleocr\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl>=2.0.0-
>paddlehub) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl>=2.0.0-
>paddlehub) (0.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from requests->visualdl>=2.0.0->paddlehub) (1.26.
4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\anaconda3\envs\paddleocr\lib\site-packages (from requests->visualdl>=2.0.0->paddlehub) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\envs\paddleocr\lib\site-packages (from requests->visualdl>=2.0.0->paddlehub) (2020.12.
5)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda3\envs\paddleocr\lib\site-packages (from requests->visualdl>=2.0.0->paddlehub) (2.10)
Requirement already satisfied: scikit-learn>=0.21.3 in c:\anaconda3\envs\paddleocr\lib\site-packages (from seqeval->paddlenlp>=2.0.0rc5->paddlehub) (0.2
4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda3\envs\paddleocr\lib\site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp>=2.0
.0rc5->paddlehub) (2.1.0)
Requirement already satisfied: joblib>=0.11 in c:\anaconda3\envs\paddleocr\lib\site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp>=2.0.0rc5->p
addlehub) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in c:\anaconda3\envs\paddleocr\lib\site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp>=2.0.0rc5->
paddlehub) (1.6.0)

(paddleocr) C:\Users\www19\PycharmProjects\PaddleOCR>hub install deploy\hubserving\ocr_system\
c:\anaconda3\envs\paddleocr\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and
 will be removed in the next major release
  DeprecationWarning,
c:\anaconda3\envs\paddleocr\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and
 will be removed in the next major release
  DeprecationWarning,
[2021-04-14 10:49:31,808] [    INFO] - Successfully uninstalled ocr_system
[2021-04-14 10:49:32,379] [    INFO] - Successfully installed ocr_system-1.0.0

(paddleocr) C:\Users\www19\PycharmProjects\PaddleOCR>hub serving start -m ocr_system
c:\anaconda3\envs\paddleocr\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and
 will be removed in the next major release
  DeprecationWarning,
c:\anaconda3\envs\paddleocr\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and
 will be removed in the next major release
  DeprecationWarning,
[2021-04-14 10:50:07,105] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initializat
ion of the object
 * Serving Flask app "paddlehub.serving.app_compat" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\anaconda3\envs\paddleocr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\paddleocr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\paddleocr\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\paddlehub\commands\serving.py", line 352, in execute
    self.start_serving()
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\paddlehub\commands\serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\paddlehub\commands\serving.py", line 223, in start_single_app_with_args
    app.run(configs=self.modules_info, port=port)
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\paddlehub\serving\app_compat.py", line 209, in run
    my_app.run(host="0.0.0.0", port=port, debug=False, threaded=False)
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\werkzeug\serving.py", line 1052, in run_simple
    inner()
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\werkzeug\serving.py", line 1005, in inner
    fd=fd,
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\werkzeug\serving.py", line 863, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "c:\anaconda3\envs\paddleocr\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "c:\anaconda3\envs\paddleocr\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "c:\anaconda3\envs\paddleocr\lib\http\server.py", line 139, in server_bind
    self.server_name = socket.getfqdn(host)
  File "c:\anaconda3\envs\paddleocr\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

**Comment by WenmuZhou** [comment]
看起来是编码的问题，可能win默认编码gbk，但是报文信息的utf8的，产生了编码错误。

**Comment by zhaoyantao-murray** [comment]
> 看起来是编码的问题，可能win默认编码gbk，但是报文信息的utf8的，产生了编码错误。

在linux上可以启动，还有一个问题请教老哥，我想在一台电脑上启动hubserving服务，在另一台电脑上访问网址传入图片进行推理应该怎么操作呢？我直接用文档里面的python tools/test_hubserving.py http://127.0.0.1:8868/predict/ocr_system ./doc/imgs/

命令在另一台电脑运行，显示无法连接，麻烦指导一下，非常感谢！

**Comment by WenmuZhou** [comment]
另一台顶你telnet一下启动服务的这台电脑的8868端口看看。如果能测通的话，传图片的时候server_url换成 启动服务的机器ip地址加端口

**Comment by zhaoyantao-murray** [comment]
> 在另一台机器上telnet一下启动服务的这台电脑的8868端口看看。如果能测通的话，传图片的时候server_url换成 启动服务的机器ip地址加端口

好的好的，我搞了一天，别的端口都可以用telnet测通，就是8868不行，但是一运行hubserving，竟然可以正常跑通。。。我在安装telnet服务的是时候也碰到了问题，莫名其妙又安上了。。。不管怎么样，跑通了，我就不动了hhhh，感谢老哥！
