### ISSUE TITLE
相同模型在C++和Python推理结果不同

### ISSUE THREAD

**Issue by yuelaiyue2** [PaddlePaddle/PaddleOCR#2496]
C++推理时，文本框检测会将一维码检测出来
![image](https://user-images.githubusercontent.com/54937338/114663462-efaac480-9d2c-11eb-8972-807a2dcbe80e.png)

Python推理时不会检测一维码
![image](https://user-images.githubusercontent.com/54937338/114663622-31d40600-9d2d-11eb-9137-8bdeb1bf4dc4.png)

请问是什么原因呢？能怎样避免？

**Comment by WenmuZhou** [comment]
看看预处理参数是否一致，cpp和py模型和后处理都是一致的，还有py的处理有个https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/utility.py#L50，这个在cpp里是false

**Comment by yuelaiyue2** [comment]
> 看看预参数是否一致，cpp和py模型和后处理都是一致的，还有py的处理有个[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer /utility.py#L50，这个在cpp里是false](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/utility.py#L50%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%9C%A8cpp%E9%87%8C%E6%98%AFfalse)

我的python里面是false（C++里面的这个参数没找到设置的地方），其它的参数对照了congfig.txt和utility.py,都是相同的，还有其它地方影响detector框的参数吗？
![image](https://user-images.githubusercontent.com/54937338/114684912-fdb80f80-9d43-11eb-9a87-607ae6975589.png)
这是我的C++ 的congfig设置。Python的就改过文件路径和GPU调用的地方。

**Comment by WenmuZhou** [comment]
如果都是一样的话，就没有其他影响了

**Comment by mazhen2009** [comment]
我这也出现 python 和 c++ 不一致的情况，c++ 检测到的文字要少很多。没有改代码和参数。
附件是原始图片。
如果 ocr 这边没有差别，我怀疑 python 用到的 paddle_inference 可能和 c++ 用到的 paddle_inference.dll 有不一致的地方。
但是我都是几乎同时下载的，应该区别不大吧。

![img4](https://user-images.githubusercontent.com/5170209/115170199-a5da2980-a0f2-11eb-864f-0dfb8cd0ee4e.jpg)

**Comment by yuelaiyue2** [comment]
> 我这也出现python和c ++重叠的情况，c ++检测到的文字要少很多。没有改版和参数。
> 附件是原始图片。
> 如果ocr这边没有差异，我怀疑python用到的paddle_inference可能和c ++用到的paddle_inference.dll有重叠的地方。
> 但是我都是几乎同时下载的，应该区别不大吧。
> 
> [img4.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6332696/img4.zip)

我这边C++检测也是会少一部分，效果很差，而且C++用GPU推理速度居然比不上Python GPU推理速度，你那边测试了python和C++推理速度了吗？速度怎样？
C++没有直接的批量识别，我直接加了个循环。
![image](https://user-images.githubusercontent.com/54937338/115171160-09655680-a0f5-11eb-9518-57481b43ca56.png)

**Comment by mazhen2009** [comment]
> 我这边C++检测也是会少一部分，效果很差，而且C++用GPU推理速度居然比不上Python GPU推理速度，你那边测试了python和C++推理速度了吗？速度怎样？
> C++没有直接的批量识别，我直接加了个循环。
> ![image](https://user-images.githubusercontent.com/54937338/115171160-09655680-a0f5-11eb-9518-57481b43ca56.png)

同样那副图，我python 的
`dt_boxes num : 22, elapse : 1.7772445678710938
rec_res num  : 22, elapse : 0.09574580192565918`

c++
`Cost  2.59713s`

**Comment by yuelaiyue2** [comment]
> > 我这边C++检测也是会少一部分，效果很差，而且C++用GPU推理速度居然比不上Python GPU推理速度，你那边测试了python和C++推理速度了吗？速度怎样？
> > C++没有直接的批量识别，我直接加了个循环。
> 
> 同样那副图，我python 的
> `dt_boxes num : 22, elapse : 1.7772445678710938 rec_res num : 22, elapse : 0.09574580192565918`
> 
> c++
> `Cost 2.59713s`



> > 我这边C ++检测也是会少一部分，效果很差，而且C ++用GPU推理速度居然比不上的Python GPU推理速度，你那边测试了蟒和C ++推理速度了吗？速度怎样？
> > C ++没有直接的批量识别，我直接加了个循环。
> 
> 同样那副图，我python的
> `dt_boxes num : 22, elapse : 1.7772445678710938 rec_res num : 22, elapse : 0.09574580192565918`
> 
> C ++
> `Cost 2.59713s`

不能看一次的，因为初始化也需要时间的。你可以多复制几张相同的图到Python img下进行批量推理，C++也加个循环试试。

**Comment by Dandelion111** [comment]
> > 看看预参数是否一致，cpp和py模型和后处理都是一致的，还有py的处理有个[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer /utility.py#L50，这个在cpp里是false](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/utility.py#L50%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%9C%A8cpp%E9%87%8C%E6%98%AFfalse)
> 
> 我的python里面是false（C++里面的这个参数没找到设置的地方），其它的参数对照了congfig.txt和utility.py,都是相同的，还有其它地方影响detector框的参数吗？
> ![image](https://user-images.githubusercontent.com/54937338/114684912-fdb80f80-9d43-11eb-9a87-607ae6975589.png)
> 这是我的C++ 的congfig设置。Python的就改过文件路径和GPU调用的地方。

请问大佬解决这个问题了吗？我也遇到了这个情况，自己训练的DBNet模型用官方python预测代码可以检测的很好，用cpp推理却检测不到？好奇怪

**Comment by yjmm10** [comment]
> > > 看看预参数是否一致，cpp和py模型和后处理都是一致的，还有py的处理有个[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer /utility.py#L50，这个在cpp里是false](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/utility.py#L50%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%9C%A8cpp%E9%87%8C%E6%98%AFfalse)
> > 
> > 
> > 我的python里面是false（C++里面的这个参数没找到设置的地方），其它的参数对照了congfig.txt和utility.py,都是相同的，还有其它地方影响detector框的参数吗？
> > ![image](https://user-images.githubusercontent.com/54937338/114684912-fdb80f80-9d43-11eb-9a87-607ae6975589.png)
> > 这是我的C++ 的congfig设置。Python的就改过文件路径和GPU调用的地方。
> 
> 请问大佬解决这个问题了吗？我也遇到了这个情况，自己训练的DBNet模型用官方python预测代码可以检测的很好，用cpp推理却检测不到？好奇怪

大佬，你这个问题解决了吗，最近我也遇到同一个模型，python跟c++得到的二值化图都不一样。python正常，c++就没结果了
