### ISSUE TITLE
在进行文本检测、识别串联推理时，出现错误

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#250]
输入以下命令：
python3 tools/infer/predict_system.py --image_dir=/home/hs/OCR_Projects/PaddleOCR/train_data/tibetan/text_localization/test_image/img_9.jpg --det_model_dir="./inference/det_db/"  --rec_model_dir="./inference/rec_crnn/"
出现以下错误：
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 118, in <module>
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 81, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/hs/OCR_Projects/PaddleOCR/tools/infer/predict_rec.py", line 101, in __call__
    preds_text = self.char_ops.decode(rec_idx_tmp)
  File "tools/infer/../../ppocr/utils/character.py", line 97, in decode
    char_list.append(self.character[text_index[idx]])
IndexError: list index out of range

**Comment by tink2123** [comment]
应该是因为预测模型使用的是中文模型，解码时指定了英文的字符解码方式。请问您使用的是哪一个识别模型呢？

**Comment by hsyy673150343** [comment]
您好！我使用的识别模型是rcnn发自我的华为手机-------- 原始邮件 --------发件人： xiaoting <notifications@github.com>日期： 2020年6月22日周一 下午1:27收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleOCR] 在进行文本检测、识别串联推理时，出现错误 (#250)

应该是因为预测模型使用的是中文模型，解码时指定了英文的字符解码方式。请问您使用的是哪一个识别模型呢？

**Comment by tink2123** [comment]
是中文模型吗？请试试预测时重新指定下解码方式：
python3 tools/infer/predict_system.py --image_dir=/home/hs/OCR_Projects/PaddleOCR/train_data/tibetan/text_localization/test_image/img_9.jpg --det_model_dir="./inference/det_db/"  --rec_char_type='ch'

**Comment by hsyy673150343** [comment]
> 是中文模型吗？请试试预测时重新指定下解码方式：
> python3 tools/infer/predict_system.py --image_dir=/home/hs/OCR_Projects/PaddleOCR/train_data/tibetan/text_localization/test_image/img_9.jpg --det_model_dir="./inference/det_db/" --rec_char_type='ch'

python3 tools/infer/predict_system.py --image_dir=./doc/imgs/img_9.jpg --det_model_dir="./inference/det_db/"  --rec_model_dir="./inference/rec_crnn/" --rec_char_type='ch'
还是会出现错误：
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 118, in <module>
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 81, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/hs/OCR_Projects/PaddleOCR/tools/infer/predict_rec.py", line 102, in __call__
    preds_text = self.char_ops.decode(rec_idx_tmp)
  File "tools/infer/../../ppocr/utils/character.py", line 96, in decode
    char_list.append(self.character[text_index[idx]])
IndexError: list index out of range

**Comment by tink2123** [comment]
打印下解码时的字典个数和预测的idx看一下呢？
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/ppocr/utils/character.py#L81
在81行后：print(char_num)

https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/ppocr/utils/character.py#L96
96行前：print("text_index:{}, idx:{}".format(text_index,idx))

**Comment by hsyy673150343** [comment]
> print("text_index:{}, idx:{}".format(text_index,idx))

char_num: 6623
text_index:[82262 81698 82095     0 82262 82249 81770 81698 82262 81698 82262 81698
 82009 81698 82262 82149 81698], idx:0

**Comment by tink2123** [comment]
inference model 是从官方下载的吗？看起来预测结果有误，中文dict共有6623类，但是预测出了索引值都在8w+

**Comment by hsyy673150343** [comment]
我是自己训练的模型然后按照文档里的说明转换成的inference model！
我的中文字典也是自定义的，我在rec_icdar15_train.yml中也指定了character_dict_path
但从char_num: 6623可以看出，程序还是用的自带的ppcor_keys_v1.txt

**Comment by tink2123** [comment]
如果使用了自己的字典文件，在使用system预测时，需要修改字典路径，预测时添加： --rec_char_dict_path="{your text dict path}"
![图片](https://user-images.githubusercontent.com/31891223/85271125-f7069600-b4ac-11ea-98ff-e0c2d99b9c9c.png)

**Comment by hsyy673150343** [comment]
谢谢您的耐心解答，我还有个问题。同一张图片，为什么我单独进行检测的时候能正常检测出文字，而在进行文本检测、识别串联的时候连最基本的检测都检测不出来？

**Comment by tink2123** [comment]
您的图片是什么样子的呢，方便发一张样图给我们看下吗？ 
>连最基本的检测都检测不出来

是指没有检测结果，还是检测结果错误呢

**Comment by hsyy673150343** [comment]
没有检测结果。
img_9.jpg

**Comment by hsyy673150343** [comment]
没有检测结果～！
![img_9](https://user-images.githubusercontent.com/49397302/85273681-7cd81080-b4b0-11ea-92e0-bfa1cb53e530.jpg)

**Comment by hsyy673150343** [comment]
> 您的图片是什么样子的呢，方便发一张样图给我们看下吗？
> 
> > 连最基本的检测都检测不出来
> 
> 是指没有检测结果，还是检测结果错误呢
没有检测结果
![img_9](https://user-images.githubusercontent.com/49397302/85273911-cfb1c800-b4b0-11ea-946b-069232d0b399.jpg)

**Comment by tink2123** [comment]
可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这两个地方的阈值设置为0.0 看是否能显示出结果：
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139

**Comment by hsyy673150343** [comment]
> 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139

改了之后报错啦：
Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 137, in <module>
    image, boxes, txts, scores, draw_txt=True, drop_score=0)
  File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
    txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
  File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
    draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
    draw_text(ink)
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
    **kwargs,
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
    size, offset = self.font.getsize(text, direction, features, language)
OSError: invalid face handle
段错误 (核心已转储)

**Comment by LDOUBLEV** [comment]
> > 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139
> 
> 改了之后报错啦：
> Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
> Traceback (most recent call last):
> File "tools/infer/predict_system.py", line 137, in
> image, boxes, txts, scores, draw_txt=True, drop_score=0)
> File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
> txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
> File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
> draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
> File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
> draw_text(ink)
> File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
> **kwargs,
> File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
> size, offset = self.font.getsize(text, direction, features, language)
> OSError: invalid face handle
> 段错误 (核心已转储)

你是只测试识别模型？imgs_words/ch下的是识别数据，宽度太小。测试检测用/doc/imgs下的图像试试？？

**Comment by hsyy673150343** [comment]
我是在进行文本检测、识别串联推理的时候报的错。用的我自己的图片，图片大小为608*608 发自我的华为手机-------- 原始邮件 --------发件人： Double_V <notifications@github.com>日期： 2020年6月22日周一 晚上7:19收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleOCR] 在进行文本检测、识别串联推理时，出现错误 (#250)





可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：

https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139



改了之后报错啦：

Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s

Traceback (most recent call last):

File "tools/infer/predict_system.py", line 137, in

image, boxes, txts, scores, draw_txt=True, drop_score=0)

File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr

txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)

File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual

draw_txt.text((0, gap * count), new_txt, txt_color, font=font)

File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text

draw_text(ink)

File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text

**kwargs,

File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2

size, offset = self.font.getsize(text, direction, features, language)

OSError: invalid face handle

段错误 (核心已转储)



你是只测试识别模型？imgs_words/ch下的是识别数据，宽度太小。测试检测用/doc/imgs下的图像试试？？

**Comment by hsyy673150343** [comment]
> 我是在进行文本检测、识别串联推理的时候报的错。用的我自己的图片，图片大小为608*608 发自我的华为手机-------- 原始邮件 --------发件人： Double_V <notifications@github.com>日期： 2020年6月22日周一 晚上7:19收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Author <author@noreply.github.com>主 题： Re: [PaddlePaddle/PaddleOCR] 在进行文本检测、识别串联推理时，出现错误 (#250) 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果： https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139 改了之后报错啦： Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s Traceback (most recent call last): File "tools/infer/predict_system.py", line 137, in image, boxes, txts, scores, draw_txt=True, drop_score=0) File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score) File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual draw_txt.text((0, gap * count), new_txt, txt_color, font=font) File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text draw_text(ink) File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text **kwargs, File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2 size, offset = self.font.getsize(text, direction, features, language) OSError: invalid face handle 段错误 (核心已转储) 你是只测试识别模型？imgs_words/ch下的是识别数据，宽度太小。测试检测用/doc/imgs下的图像试试？？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

我用的测试命令如下：
python3 tools/infer/predict_system.py --image_dir=./doc/imgs_words/ch/img_9.jpg --det_model_dir="./inference/det_db/" --rec_model_dir="./inference/rec_crnn/" --rec_char_type='ch' --rec_char_dict_path="./ppocr/utils/all_tibetan_word.txt"  
--det_algorithm="DB" --rec_image_shape="3, 32, 280" --rec_char_type="ch"

测试的图片是我自己收集的数据集，图片大小为608*608

**Comment by hsyy673150343** [comment]
> > > 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139
> > 
> > 
> > 改了之后报错啦：
> > Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
> > Traceback (most recent call last):
> > File "tools/infer/predict_system.py", line 137, in
> > image, boxes, txts, scores, draw_txt=True, drop_score=0)
> > File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
> > txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
> > File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
> > draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
> > draw_text(ink)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
> > **kwargs,
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
> > size, offset = self.font.getsize(text, direction, features, language)
> > OSError: invalid face handle
> > 段错误 (核心已转储)
> 
> 你是只测试识别模型？imgs_words/ch下的是识别数据，高度太小。测试检测用/doc/imgs下的图像试试？？

     

我用的测试命令如下：
python3 tools/infer/predict_system.py --image_dir=./doc/imgs_words/ch/img_9.jpg --det_model_dir="./inference/det_db/" --rec_model_dir="./inference/rec_crnn/" --rec_char_type='ch' --rec_char_dict_path="./ppocr/utils/all_tibetan_word.txt"
--det_algorithm="DB" --rec_image_shape="3, 32, 280" --rec_char_type="ch"

测试的图片是我自己收集的数据集，图片大小为608*608

**Comment by hsyy673150343** [comment]
> > > 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139
> > 
> > 
> > 改了之后报错啦：
> > Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
> > Traceback (most recent call last):
> > File "tools/infer/predict_system.py", line 137, in
> > image, boxes, txts, scores, draw_txt=True, drop_score=0)
> > File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
> > txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
> > File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
> > draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
> > draw_text(ink)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
> > **kwargs,
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
> > size, offset = self.font.getsize(text, direction, features, language)
> > OSError: invalid face handle
> > 段错误 (核心已转储)
> 
> 你是只测试识别模型？imgs_words/ch下的是识别数据，高度太小。测试检测用/doc/imgs下的图像试试？？

测试的是检测和识别串联推理，我用的测试命令如下：
python3 tools/infer/predict_system.py --image_dir=./doc/imgs_words/ch/img_9.jpg --det_model_dir="./inference/det_db/" --rec_model_dir="./inference/rec_crnn/" --rec_char_type='ch' --rec_char_dict_path="./ppocr/utils/all_tibetan_word.txt"
--det_algorithm="DB" --rec_image_shape="3, 32, 280" --rec_char_type="ch"

测试的图片是我自己收集的数据集，图片大小为608*608

**Comment by hsyy673150343** [comment]
> > > 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139
> > 
> > 
> > 改了之后报错啦：
> > Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
> > Traceback (most recent call last):
> > File "tools/infer/predict_system.py", line 137, in
> > image, boxes, txts, scores, draw_txt=True, drop_score=0)
> > File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
> > txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
> > File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
> > draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
> > draw_text(ink)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
> > **kwargs,
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
> > size, offset = self.font.getsize(text, direction, features, language)
> > OSError: invalid face handle
> > 段错误 (核心已转储)
> 
> 你是只测试识别模型？imgs_words/ch下的是识别数据，高度太小。测试检测用/doc/imgs下的图像试试？？

测试的是检测和识别串联推理，我用的测试命令如下：
 python3 tools/infer/predict_system.py --image_dir=./doc/imgs_words/ch/img_9.jpg --det_model_dir="./inference/det_db/"  --det_algorithm="DB" --rec_model_dir="./inference/rec_crnn/" --rec_image_shape="3, 32, 280" --rec_char_type="ch" --rec_char_dict_path="./ppocr/utils/all_tibetan_word.txt"
测试的图片是我自己收集的数据集，图片大小为608*608

**Comment by hsyy673150343** [comment]
> > > 可能是因为识别得分低于0.5，置信度过低没有返回结果。可以把这个地方的阈值设置为0.0 看是否能显示出结果：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L139
> > 
> > 
> > 改了之后报错啦：
> > Predict time of ./doc/imgs_words/ch/img_9.jpg: 1.049s
> > Traceback (most recent call last):
> > File "tools/infer/predict_system.py", line 137, in
> > image, boxes, txts, scores, draw_txt=True, drop_score=0)
> > File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
> > txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
> > File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
> > draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
> > draw_text(ink)
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
> > **kwargs,
> > File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
> > size, offset = self.font.getsize(text, direction, features, language)
> > OSError: invalid face handle
> > 段错误 (核心已转储)
> 
> 你是只测试识别模型？imgs_words/ch下的是识别数据，高度太小。测试检测用/doc/imgs下的图像试试？？

测试的是检测和识别串联推理，我用的测试命令如下：
python3 tools/infer/predict_system.py --image_dir=./doc/de_rec_test_img/img_9.jpg  --det_model_dir="./inference/det_db/"  --rec_model_dir="./inference/rec_crnn/" --rec_char_type="ch" --rec_char_dict_path="./ppocr/utils/all_tibetan_word.txt"

测试的图片是我自己收集的数据集，图片大小为608*608

报错信息为：
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 139, in <module>
    image, boxes, txts, scores, draw_txt=True, drop_score=0.0)
  File "tools/infer/../../tools/infer/utility.py", line 154, in draw_ocr
    txts, scores, img_h=img.shape[0], img_w=600, threshold=drop_score)
  File "tools/infer/../../tools/infer/utility.py", line 241, in text_visual
    draw_txt.text((0, gap * count), new_txt, txt_color, font=font)
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 351, in text
    draw_text(ink)
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageDraw.py", line 316, in draw_text
    **kwargs,
  File "/home/hs/.local/lib/python3.6/site-packages/PIL/ImageFont.py", line 471, in getmask2
    size, offset = self.font.getsize(text, direction, features, language)
OSError: invalid face handle
段错误 (核心已转储)

**Comment by tink2123** [comment]
报错说明返回了检测框，在画图了。这好像是Pillow库的bug，可能因为您的字典中有特殊字符？可以参考这个issue尝试重新安装编译：https://github.com/python-pillow/Pillow/issues/3066

或者跳过draw_text函数: draw_txt=False
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/utility.py#L311

返回结果可以通过修改阈值，在终端打印出来，score>=0.0 ：
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127

**Comment by hsyy673150343** [comment]
> 报错说明返回了检测框，在画图了。这好像是Pillow库的bug，可能因为您的字典中有特殊字符？可以参考这个issue尝试重新安装编译：[python-pillow/Pillow#3066](https://github.com/python-pillow/Pillow/issues/3066)
> 
> 或者跳过draw_text函数: draw_txt=False
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/utility.py#L311
> 
> 返回结果可以通过修改阈值，在终端打印出来，score>=0.0 ：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127
我是在弄藏文识别，字典里全是藏文字符

**Comment by hsyy673150343** [comment]
> 报错说明返回了检测框，在画图了。这好像是Pillow库的bug，可能因为您的字典中有特殊字符？可以参考这个issue尝试重新安装编译：[python-pillow/Pillow#3066](https://github.com/python-pillow/Pillow/issues/3066)
> 
> 或者跳过draw_text函数: draw_txt=False
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/utility.py#L311
> 
> 返回结果可以通过修改阈值，在终端打印出来，score>=0.0 ：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127

我的字典里全是藏文字符

**Comment by hsyy673150343** [comment]
> 报错说明返回了检测框，在画图了。这好像是Pillow库的bug，可能因为您的字典中有特殊字符？可以参考这个issue尝试重新安装编译：[python-pillow/Pillow#3066](https://github.com/python-pillow/Pillow/issues/3066)
> 
> 或者跳过draw_text函数: draw_txt=False
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/utility.py#L311
> 
> 返回结果可以通过修改阈值，在终端打印出来，score>=0.0 ：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127

我的字典里全是藏文字符，跳过draw_text函数，可以在终端打印出来。但是返回了检测框，却在图上画不出来

**Comment by hsyy673150343** [comment]
> 报错说明返回了检测框，在画图了。这好像是Pillow库的bug，可能因为您的字典中有特殊字符？可以参考这个issue尝试重新安装编译：[python-pillow/Pillow#3066](https://github.com/python-pillow/Pillow/issues/3066)
> 
> 或者跳过draw_text函数: draw_txt=False
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/utility.py#L311
> 
> 返回结果可以通过修改阈值，在终端打印出来，score>=0.0 ：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_system.py#L127

谢谢您的耐心解答~！我的问题解决了。
我首先卸载了pillow----》pip uninstall pillow==7.1.2
然后将score改为0
最后使用conda重新下载了pillow----》conda install pillow==7.1.2
这个bug就没有了
