### ISSUE TITLE
2080ti，检测耗时3.2s，DB-mv3, 最大边2048，请问正常么？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2504]
多次运行（非第一次运行，排除了模型加载时间的影响）
输入图片的原始尺寸：2627*3623
预测时最大边长像素：2048
最终输入检测模型的尺寸：(2048,1484,3)
附上测试图片如下：

检测模型：
configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml
使用的GPU：2080TI 
检测耗时：
[2021/04/14 17:56:20] root INFO: dt_boxes num : 147, elapse : 3.1584384441375732
识别耗时：
[2021/04/14 17:56:20] root INFO: rec_res num  : 147, elapse : 0.35449695587158203
总共耗时4s，
请问以上测试结果符合预期么？
这里DB模块（mv3）速度与论文（res-18）检测速度给出的完全不符，请问可能是什么原因？
这个尺度、硬件环境下，检测耗时一般是多少？
谢！^_^

**Comment by WenmuZhou** [comment]
正常的，你的图片里文字很多，后处理占了比较多的时间

**Comment by xealml** [comment]
老哥，我觉得你这样做会暴露别人的个人信息

**Comment by ymzx** [comment]
谢提醒，当时考虑如果改动了或者做了屏蔽，技术复现上会有问题，已删除。

**Comment by ymzx** [comment]
> 老哥，我觉得你这样做会暴露别人的个人信息

谢提醒，当时考虑如果改动了或者做了屏蔽，技术复现上会有问题，已删除。
