### ISSUE TITLE
用STAR-net做识别网络，推理时需要修改代码吗？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#2505]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/67897601/114696197-fcd8ab00-9d4e-11eb-96c2-e14035cf6609.png">
是只把这里的CRNN改成STAR-net吗？

**Comment by WenmuZhou** [comment]
需要的，具体参考文档https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md

**Comment by aishangmaxiaoming** [comment]
> 需要的，具体参考文档https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md

看了文档，好像说STAR-net不需要修改？所以修改什么呢？

**Comment by aishangmaxiaoming** [comment]
> 需要的，具体参考文档https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md

就是训练时STARNET有TPS，但是推理时没有tps，是需要自己加吗？
