### ISSUE TITLE
No slim model about Multilingual Recognition

### ISSUE THREAD

**Issue by skydev66** [PaddlePaddle/PaddleOCR#2507]
Thanks for your great android demo project.
It works quite well about images written in Chinese, and English. However it is not recognizing other languages, like Japanese, Korean, Russian because current model is not providing the languages except English and Korean.
I've seen there are multilingual recognition models, but all of them contain inference or trained model and do not support slim model.

Could you share any other slim model files(.nb) to recognize other language texts?

**Comment by tink2123** [comment]
Sorry, we do not  have slim models in other languages currently. If you need to, you can refer to our [slim document](https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/slim/quantization) to generate .nb files by yourself.
