### ISSUE TITLE
部署推理模型，识别中文有误，与预测模型精确度相差较大

### ISSUE THREAD

**Issue by lyhlyhl** [PaddlePaddle/PaddleOCR#2512]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/predict_rec.py  中

![image](https://user-images.githubusercontent.com/49781275/114806670-b4190480-9dd7-11eb-9315-13c61b2a10c9.png)
会导致为中文时，参数--rec_image_shape失效，从而识别结果完全不对（张量大小完全不一样了）
会发现，预测模型是一个结果，转化成推理模型后完全不对

不太看明白这两行有什么作用，但是经测试注释后正常推理

**Comment by tink2123** [comment]
当预测文本过长时，这两行保证不对长文本进行过度压缩，从而导致识别错误。
如果您本身修改了image shape，注释掉这两行即可

**Comment by lyhlyhl** [comment]
> 当预测文本过长时，这两行保证不对长文本进行过度压缩，从而导致识别错误。
> 如果您本身修改了image shape，注释掉这两行即可

明白了，感谢，希望能加个FAQ之类的，之前困惑了我很多天，识别一直乱码
