### ISSUE TITLE
如何关闭logger.info()

### ISSUE THREAD

**Issue by MrLeeeee** [PaddlePaddle/PaddleOCR#2514]
ocr = PaddleOCR(lang="ch", use_gpu=False)
result = ocr.ocr(img_path)
如何设置才不打印 logger.info()的信息呢

**Comment by tink2123** [comment]
在 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/paddleocr.py 代码中注释不想打印的logger，并重新生成whl包。
