### ISSUE TITLE
模型转换问题：key load_static_weights not in sub_keys

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#2518]
根据官网上的训练模型转预测模型的指令：
# -c 后面设置训练算法的yml配置文件
# -o 配置可选参数
# Global.pretrained_model 参数设置待转换的训练模型地址，不用添加文件后缀 .pdmodel，.pdopt或.pdparams。
# Global.load_static_weights 参数需要设置为 False。
# Global.save_inference_dir参数设置转换的模型将保存的地址。

python3 tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.pretrained_model=./ch_lite/ch_ppocr_mobile_v2.0_det_train/best_accuracy Global.load_static_weights=False Global.save_inference_dir=./inference/det_db/

我用如下指令转换：
python3 ~/Downloads/PaddleOCR/tools/export_model.py -c ./configs/rec/rec_chinese_lite_train_v1.1.yml -o Global.pretrain_weights=./backup/rec_CRNN/iter_epoch_2290  Global.save_inference_dir=./inference/rec/ Global.load_static_weights=False 

但是报错了：

python3 ~/Downloads/PaddleOCR/tools/export_model.py -c ./configs/rec/rec_chinese_lite_train_v1.1.yml -o Global.pretrain_weights=./backup/rec_CRNN/iter_epoch_2290  Global.save_inference_dir=./inference/rec/ Global.load_static_weights=False 

求解答，卡了好久了，群里问没人理 T-T

**Comment by tink2123** [comment]
请问报错信息是什么？可以通过 -o Global.load_static_weights=False 或者直接修改配置文件里的值

**Comment by blackhitomi** [comment]
> 请问报错信息是什么？可以通过 -o Global.load_static_weights=False 或者直接修改配置文件里的值

谢谢，已解决。通过 -o Global.load_static_weights=False设置会报上面的错误，估计是因为配置文件中没有该参数造成的；自己手动添加后无错误。
