### ISSUE TITLE
ImportError: No module named paddle.distributed

### ISSUE THREAD

**Issue by JohnnyZhang0628** [PaddlePaddle/PaddleOCR#2519]
![image](https://user-images.githubusercontent.com/28375774/114852964-e21d3980-9e15-11eb-90df-a841a9a2ee7b.png)
运行测试的命令，直接报错了，提示缺少了一个模块。
系统：centos7，
安装：源码安装的，不是docker安装。

**Comment by tink2123** [comment]
需要安装 paddle2.0 及以上的版本

**Comment by JohnnyZhang0628** [comment]
@tink2123 我安装的就是2.0，昨天晚上怎么都不行。今天早上重启了一下，就可以了，不知道为啥？

**Comment by tink2123** [comment]
应该是2.0没有安装成功吧～

**Comment by ViokingTung** [comment]
`pip uninstall paddlepaddle-gpu paddlepaddle
python -m pip install paddlepaddle-gpu==2.1.2.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

我的也这样，卸载了重装就好了
