### ISSUE TITLE
PaddleOCR如何进行恢复训练，训练中断后接着训练？

### ISSUE THREAD

**Issue by coopot** [PaddlePaddle/PaddleOCR#252]
PaddleOCR如何进行恢复训练，训练中断后接着训练？

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/85273593-5dd97e80-b4b0-11ea-888f-415ce5cb74e9.png)

检测模型 断点训练可参考[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md) ，直接通过checkpoints加载先前保存的模型即可，识别模型同理。

**Comment by coopot** [comment]
3Q
