### ISSUE TITLE
文本识别STARnet转inference模型推理识别结果是乱码，用CRNN识别正常，是不是STARnet需要修改什么地方呢？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#2520]
文本识别STARnet转inference模型推理识别结果是乱码，用CRNN识别正常,是不是STARnet需要修改什么地方呢？
下面是原图和识别结果
<img width="956" alt="image" src="https://user-images.githubusercontent.com/67897601/114856601-e186a200-9e19-11eb-8da0-734502a6a2ea.png">
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/67897601/114856673-f5320880-9e19-11eb-9eba-e0a48aa8292d.png">

**Comment by tink2123** [comment]
看socre得分，网络被随机初始化了，请问使用训练引擎的 infer_rec.py 去预测，可以得到正确结果吗？

**Comment by aishangmaxiaoming** [comment]
> 看socre得分，网络被随机初始化了，请问使用训练引擎的 infer_rec.py 去预测，可以得到正确结果吗？

训练的log和eval正常，把模型拿出来用infer_rec.py / eval.py/ predict_rec.py 测试都异常

**Comment by Helloworld0214** [comment]
我也有一样的结果
