### ISSUE TITLE
文字识别模型推理

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2523]
在使用starnet做模型推理的时候，生成的推理信息能不能直接在图片上标注出来，现在只能返回
![image](https://user-images.githubusercontent.com/44855506/114955321-0ec16780-9e8f-11eb-9868-4206899f0132.png)
这种类型的，想直接在图片上显示出来比较直观，有没有这个功能呢

**Comment by aishangmaxiaoming** [comment]
> 在使用starnet做模型推理的时候，生成的推理信息能不能直接在图片上标注出来，现在只能返回
> ![image](https://user-images.githubusercontent.com/44855506/114955321-0ec16780-9e8f-11eb-9868-4206899f0132.png)
> 这种类型的，想直接在图片上显示出来比较直观，有没有这个功能呢

你用的是哪个配置文件训练的模型，数据是自己的吗？

**Comment by tink2123** [comment]
文本行识别时，目前只支持把结果打印出来。暂时没有在图片上显示出来的功能。
端到端预测时，可以把文本框和文本结果画出来。如有需要可以参考代码，把图画出来。https://github.com/PaddlePaddle/PaddleOCR/blob/8341d58f199a29aa8c334469c92db1982c37d588/tools/infer/utility.py#L172

**Comment by Harrison410-web** [comment]
> 文本行识别时，目前只支持把结果打印出来。暂时没有在图片上显示出来的功能。
> 端到端预测时，可以把文本框和文本结果画出来。如有需要可以参考代码，把图画出来。
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/8341d58f199a29aa8c334469c92db1982c37d588/tools/infer/utility.py#L172
您好，我用了infer_det.py，好像他的模型预测后的信息，只包含了预测框，好像没有包含预测文字

**Comment by MissPenguin** [comment]
> > 文本行识别时，目前只支持把结果打印出来。暂时没有在图片上显示出来的功能。
> > 端到端预测时，可以把文本框和文本结果画出来。如有需要可以参考代码，把图画出来。
> > https://github.com/PaddlePaddle/PaddleOCR/blob/8341d58f199a29aa8c334469c92db1982c37d588/tools/infer/utility.py#L172
> > 
> > 您好，我用了infer_det.py，好像他的模型预测后的信息，只包含了预测框，好像没有包含预测文字

infer_det就是文本检测啊，你要识别结果的话得用端到端的识别，转换成推理模型后用predict_system.py进行串联预测。

**Comment by Mafengqiang** [comment]
> 文本行识别时，目前只支持把结果打印出来。暂时没有在图片上显示出来的功能。
> 端到端预测时，可以把文本框和文本结果画出来。如有需要可以参考代码，把图画出来。
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/8341d58f199a29aa8c334469c92db1982c37d588/tools/infer/utility.py#L172

嗯嗯，好的，谢谢解答

**Comment by Harrison410-web** [comment]
我用端到端PGNET去尝试，但是很奇怪，直接就报错，“python3 tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="./doc/imgs_en/img623.jpg" --e2e_model_dir="./inference/e2e_server_pgnetA_infer/" --e2e_pgnet_polygon=True”
但是utility.py的参数输入根本就没有上面的参数“error: unrecognized arguments: --e2e_algorithm=PGNet --e2e_model_dir=./inference/e2e_server_pgnetA_infer/ --e2e_pgnet_polygon=True
”
我有点晕，看不太懂这个github上面的内容，我想识别自己数据集的4个数字，但是4个数字处在图片边缘，且存在一定的角度，希望大佬们给点意见？我该如何下手





------------------&nbsp;Original message&nbsp;------------------
From: "MissPenguin"; 
Sendtime: Monday, Apr 19, 2021 10:41 AM
To: "PaddlePaddle/PaddleOCR"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [PaddlePaddle/PaddleOCR] 文字识别模型推理 (#2523)





   
文本行识别时，目前只支持把结果打印出来。暂时没有在图片上显示出来的功能。
 端到端预测时，可以把文本框和文本结果画出来。如有需要可以参考代码，把图画出来。
 https://github.com/PaddlePaddle/PaddleOCR/blob/8341d58f199a29aa8c334469c92db1982c37d588/tools/infer/utility.py#L172
 
您好，我用了infer_det.py，好像他的模型预测后的信息，只包含了预测框，好像没有包含预测文字
   
infer_det就是文本检测啊，你要识别结果的话得用端到端的识别，转换成推理模型后用predict_system.py进行串联预测。
