### ISSUE TITLE
StyleText 有办法生成点阵文字吗？

### ISSUE THREAD

**Issue by JescalLin** [PaddlePaddle/PaddleOCR#2524]
现在用StyleText生成的图像如下
![0](https://user-images.githubusercontent.com/19463066/114955756-f4d45480-9e8f-11eb-97ce-d973499b750a.png)
![1](https://user-images.githubusercontent.com/19463066/114955757-f4d45480-9e8f-11eb-8e79-b22134c73126.png)
我的真实资料如下
![t0021_crop_0](https://user-images.githubusercontent.com/19463066/114955848-264d2000-9e90-11eb-9177-8b6d3e4b170c.jpg)
![t0019_crop_0](https://user-images.githubusercontent.com/19463066/114955855-29e0a700-9e90-11eb-865a-21bc6efd165d.jpg)
有办法让StyleText生成更像真实资料吗？
谢谢

**Comment by cxy86121-sudo** [comment]
可以直接把原图输入到模型看一下输出效果
