### ISSUE TITLE
C++编译推理出错，是哪里出了问题？

### ISSUE THREAD

**Issue by yuelaiyue2** [PaddlePaddle/PaddleOCR#2525]
cmake配置：
![image](https://user-images.githubusercontent.com/54937338/114958863-79c26c80-9e96-11eb-87f2-533013e5eb4c.png)

不论选择tensorRT或者不选择tensorRT都会显示tensorRT的 Load symbol getPluginRegistry failed.
通过cmake编译后，运行可执行文件显示：
![image](https://user-images.githubusercontent.com/54937338/114958930-99599500-9e96-11eb-9ce6-e2d4ff77557a.png)

**Comment by siqiaof** [comment]
我也遇到了同样的问题，请问您现在解决了吗？

**Comment by shyn** [comment]
Me too here.
