### ISSUE TITLE
pgnet相关问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2529]
请问端到端的pgnet相比于DB+CRNN在准确率上有优势吗？或者是pgnet最擅长的场景是什么场景呢？

**Comment by MissPenguin** [comment]
pgnet是端到端算法，检测识别一步到位，不用分开训练2个模型，也支持弯曲文本的识别，但是在中文上的效果还没有充分验证；db+crnn的验证更充分，应用相对成熟，常规非弯曲的文本都能解的不错。

**Comment by zcswdt** [comment]
> 规非弯曲的文本都能

哦哦哦，谢谢解答。
