### ISSUE TITLE
繁体中文和英文预测感觉不太准

### ISSUE THREAD

**Issue by sunweiconfidence** [PaddlePaddle/PaddleOCR#253]
您好，

试用了发现，简体中文预测很准，但是英文预测出来，句子都是黏连在一起，每个单词之间没空格分开，繁体中文一些字也不能准确预测，请问该如何设置吗？还是目前就是这样？谢谢

预测命令如下：
python tools/infer/predict_system.py --image_dir="./doc/imgs/test1.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False

**Comment by tink2123** [comment]
目前发布的模型主要针对简体中文，繁体字的训练样本较少。有需要的话，可以用自己的数据进行finetune。
英文目前不支持空格，后期会推出支持空格的版本，您也可以根据需要在现有dict中加入空格类别自己训练。

**Comment by sunweiconfidence** [comment]
好的，谢谢
