### ISSUE TITLE
请问SAST算法如何训练自己的数据集？

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#2533]
我的数据集是四边形标注，请问有没有脚本能够能成几对上下轮廓点，然后送入到SAST算法中训练，直接使用4个顶点训练的话效果很差。

**Comment by MissPenguin** [comment]
目前没有这种脚本，如果你的数据都是4点标注的非弯曲文本，可以用db试试，sast主要优势在弯曲文本，弯曲文本需要14点标注

**Comment by ulanbator** [comment]
使用了DB但是对于一些长文本有文本区域断裂的现象，所以想使用SAST的高级目标信息引导一下。
