### ISSUE TITLE
没有为paddle_inference.dll 加载符号文件。

### ISSUE THREAD

**Issue by yuelaiyue2** [PaddlePaddle/PaddleOCR#2535]
![image](https://user-images.githubusercontent.com/54937338/115100138-59191600-9f6d-11eb-98ac-537a432b3816.png)

![image](https://user-images.githubusercontent.com/54937338/115100145-68985f00-9f6d-11eb-808d-d31411619ffb.png)

请问一下出现在安装与编译 Windows 预测库 这种情况需要怎么修改？？？

**Comment by mxy493** [comment]
我也遇到了同样的问题

**Comment by yuelaiyue2** [comment]
> 我也遇到了同样的问题

我的cmake3.17.0，用paddleOCR 2.1版本编辑cmakelist成功了，预测库（2.0.2版本的）你自己根据你的cuda的安装情况选一下。我也不知道为啥就成功了，可能是cmakelist的原因。。。。

**Comment by mxy493** [comment]
> > 我也遇到了同样的问题
> 
> 我的cmake3.17.0，用paddleOCR 2.1版本编辑cmakelist成功了，预测库（2.0.2版本的）你自己根据你的cuda的安装情况选一下。我也不知道为啥就成功了，可能是cmakelist的原因。。。。

我编译Demo是成功了的，现在在写自己的代码了，有些莫名其妙的问题

**Comment by wu-yakun** [comment]
啊，这个问题搞了两天了，都没解决。求教大神！！

**Comment by wu-yakun** [comment]
我的问题已经解决。原因是我下载预测库的问题，我下载的是“cuda10.2_cudnn7.6_avx_mkl_trt7”，然而并没有安装tensorrt。我将tensorrt安装上，没有为paddle_inference.dll加载符号文件的问题就已解决。
你可能会想，我没有用tensorrt，为啥也要tensorrt呢？好问题，是因为你下载的这个“cuda10.2_cudnn7.6_avx_mkl_trt7“包含tensorrt的相关文件，所以你即使不用tensorrt，也要有tensorrt。
