### ISSUE TITLE
inference.pdiparams和inference.pdmodel两个文件如何转为params和model两个文件？

### ISSUE THREAD

**Issue by 304526881** [PaddlePaddle/PaddleOCR#2538]
PaddeOCR release2.0版本inference的是inference.pdiparams和inference.pdmodel两个文件，这两个文件可以转为PaddleOCR develop版本inference的params和model两个文件吗？

**Comment by yfc886** [comment]
在套件根目录下有个export_model.sh  可以将动态模型转换为静态模型

**Comment by MissPenguin** [comment]
请问具体是什么需求呢？2.0是动态图分支，develop是静态图分支，所以保存的推理模型格式不一样，2.0和1.1的模型效果是差不多的，如果想用静态图，直接用1.1的模型就行，不需要用2.0进行转换

**Comment by tangjinhan** [comment]
> 请问具体是什么需求呢？2.0是动态图分支，develop是静态图分支，所以保存的推理模型格式不一样，2.0和1.1的模型效果是差不多的，如果想用静态图，直接用1.1的模型就行，不需要用2.0进行转换

如果要转换，需要怎么怎么转呢，给个思路，谢谢！

**Comment by Fei-dong** [comment]
> 请问具体是什么需求呢？2.0是动态图分支，develop是静态图分支，所以保存的推理模型格式不一样，2.0和1.1的模型效果是差不多的，如果想用静态图，直接用1.1的模型就行，不需要用2.0进行转换

我训练的效果差很多，不知道什么原因。

**Comment by WenmuZhou** [comment]
好像没有这个功能
