### ISSUE TITLE
lsvt数据集没有test labels

### ISSUE THREAD

**Issue by renchenliang** [PaddlePaddle/PaddleOCR#254]
https://ai.baidu.com/broad/download?dataset=lsvt
这个test数据集的label没有开源么

**Comment by MissPenguin** [comment]
test数据集的label目前没有开源，要评估结果只能去官网提交：https://rrc.cvc.uab.es/?ch=16

**Comment by DuckJ** [comment]
竖直文字的数据集是在lsvt中获取矫正之后再旋转90度，请问你们有合成竖直文字吗

**Comment by tink2123** [comment]
@DuckJ 是的，我们使用合成工具基于lsvt语料生成了一批竖直文字。

**Comment by DuckJ** [comment]
@tink2123 方便透漏什么工具吗？还是生成时候用的是旋转后的字体啊

**Comment by tink2123** [comment]
![图片](https://user-images.githubusercontent.com/31891223/86102617-50df0f80-baee-11ea-8b37-83bf0146404e.png)
我们用到的是text_render，合成文字时选择垂直字体即可

**Comment by DuckJ** [comment]
好的，谢谢
