### ISSUE TITLE
使用了infer_det.py，但是输出的图像只有预测框，没有预测的文字

### ISSUE THREAD

**Issue by Harrison410-web** [PaddlePaddle/PaddleOCR#2544]
想问问能不能将预测文字打印出，在输出的图像也可，在predict.txt也可

**Comment by MissPenguin** [comment]
infer_det就是文本检测啊，你要识别结果的话得用端到端的识别，转换成推理模型后用predict_system.py进行串联预测。

**Comment by Harrison410-web** [comment]
好的，谢谢了，我去摸索摸索



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月19日(周一) 中午11:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 使用了infer_det.py，但是输出的图像只有预测框，没有预测的文字 (#2544)




 
infer_det就是文本检测啊，你要识别结果的话得用端到端的识别，转换成推理模型后用predict_system.py进行串联预测。

**Comment by Harrison410-web** [comment]
您好，感谢您的回复，能麻烦您讲详细一些么，我有点不是很懂，不懂内容如下：我现在是改用PGNET去训练数据集是吗？但是我用PGNET的官方文档，一直显示出错，参数输入就已经出错了： error: unrecognized arguments: --e2e_algorithm=PGNet --e2e_model_dir=./inference/e2e_server_pgnetA_infer/ --e2e_pgnet_polygon=True





------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Monday, Apr 19, 2021 11:35 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [PaddlePaddle/PaddleOCR] 使用了infer_det.py，但是输出的图像只有预测框，没有预测的文字 (#2544)





 
infer_det就是文本检测啊，你要识别结果的话得用端到端的识别，转换成推理模型后用predict_system.py进行串联预测。

**Comment by MissPenguin** [comment]
要不你先描述你下你的需求吧，没太看明白你想做什么😂

**Comment by Harrison410-web** [comment]
已经解决了，谢谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月20日(周二) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 使用了infer_det.py，但是输出的图像只有预测框，没有预测的文字 (#2544)




 
要不你先描述你下你的需求吧，没太看明白你想做什么😂

**Comment by xuxiaobao-3** [comment]
为什么我pridict_text里面图片名和后面只有个空的[]

**Comment by Harrison410-web** [comment]
一般的[]里面含有预测框的坐标，4个点，如果为空，则该图片未检测到预测框



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月21日(周五) 下午2:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 使用了infer_det.py，但是输出的图像只有预测框，没有预测的文字 (#2544)




 
为什么我pridict_text里面图片名和后面只有个空的[]

**Comment by kidcad1412** [comment]
> 已经解决了，谢谢啦
> […](#)

请问一下怎么解决的，我用ppocrv5 的CLI执行命令也是结果图片只有一个框，没有文字，但是json是全的
