### ISSUE TITLE
请问style-text 是否可以生成竖排文本？

### ISSUE THREAD

**Issue by cxy86121-sudo** [PaddlePaddle/PaddleOCR#2546]
请问style-text 是否可以生成竖排文本？

**Comment by mikeshi80** [comment]
目前感觉无法生成，如果要生成，请使用 https://github.com/oh-my-ocr/text_renderer ，里面可以加上 horizontal=false，来生成垂直文本

**Comment by MissPenguin** [comment]
style-text 暂时不支持竖排文本哈

**Comment by aisensiy** [comment]
请问这个目前有什么进展么
