### ISSUE TITLE
训练starnet出错

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleOCR#255]
训练日文
训练命令:
```
python tools/train.py -c configs/rec/rec_r34_vd_tps_bilstm_ctc_smlange.yml
```
报错如下：
```
InvalidArgumentError: The value of Attr(blank) should be in interval [0, 2183), but received 
  [Hint: Expected blank < sequence_width, but received blank:2183 >= sequence_width:2000.] at (/paddle/paddle/fluid/operators/warpctc_op.cc:58)
  [operator < warpctc > error]
```
之前用attention模型训练时，说是字符字典不能超过2000行，这次改用了ctc，貌似又是某个参数超过了范围?请哪位帮忙看一下，急等解决，非常感谢.

**Comment by lfxx** [comment]
大致明白了，ctc也有字符限制，不能超过2000行。。

**Comment by tink2123** [comment]
ctc是没有字符限制的，看起来是因为预测predict纬度和设置的类别数不一致，可以打印一下warpctc的输入shape看一下：
https://github.com/PaddlePaddle/PaddleOCR/blob/160bb06e7075430da0bc7742ffe1cf7c4f4b496b/ppocr/modeling/losses/rec_ctc_loss.py#L31

print("sequence_width:",predict.shape)

**Comment by lfxx** [comment]
> ctc是没有字符限制的，看起来是因为预测predict纬度和设置的类别数不一致，可以打印一下warpctc的输入shape看一下：
> https://github.com/PaddlePaddle/PaddleOCR/blob/160bb06e7075430da0bc7742ffe1cf7c4f4b496b/ppocr/modeling/losses/rec_ctc_loss.py#L31
> 
> print("sequence_width:",predict.shape)

结果如下：
```
sequence_width: (-1, 2184)
```
这意思是多了一个字符？

**Comment by tink2123** [comment]
同时打印一下 self.char_num，另外您的自定义字典有多少类呢？字典和label格式大概是怎样的呢？

**Comment by lfxx** [comment]
> 同时打印一下 self.char_num，另外您的自定义字典有多少类呢？字典和label格式大概是怎样的呢？

结果如下：
```
sequence_width: (-1, 2184)
char_num:2183
```
我的字典有2183行，utf-8编码，生成字典文本时用的如下代码
```
with open(os.path.join('./PaddleOCR/train_data/data_lm', 'japan_dict.txt'), 'w',
          encoding='utf-8') as f:
    for i in word:
        f.write('{}\n'.format(i))
```
感觉是在最后一行的后面加了一个空白行

**Comment by lfxx** [comment]
[japan_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817694/japan_dict.txt)
这个是我生成的字典文件

**Comment by tink2123** [comment]
字典文件没有问题～方便看一下您label的格式吗？另外您在训练时都修改了哪些参数和代码呢？

**Comment by lfxx** [comment]
[rec_benchmark_reader.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817748/rec_benchmark_reader.txt)
[rec_r34_vd_tps_bilstm_ctc_smlange.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817749/rec_r34_vd_tps_bilstm_ctc_smlange.txt)
这个是我的配置文件，代码并没有修改

**Comment by lfxx** [comment]
[gt_train.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817763/gt_train.txt)
这个是label文件

**Comment by lfxx** [comment]
[gt_test.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817765/gt_test.txt)
[gt_valid.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4817767/gt_valid.txt)

**Comment by tink2123** [comment]
您使用的数据格式是LMDB的吗？如果是普通的图片请使用chinese_reader，
reader_yml: ./configs/rec/rec_chinese_reader.yml
参考这部分说明：
<img width="903" alt="图片" src="https://user-images.githubusercontent.com/31891223/85374673-b3bd2d80-b567-11ea-9573-d75e0416a520.png">

**Comment by lfxx** [comment]
> 您使用的数据格式是LMDB的吗？如果是普通的图片请使用chinese_reader，
> reader_yml: ./configs/rec/rec_chinese_reader.yml
> 参考这部分说明：
> <img alt="图片" width="903" src="https://user-images.githubusercontent.com/31891223/85374673-b3bd2d80-b567-11ea-9573-d75e0416a520.png">

换了还是显示字符不匹配，其实我之前已经成功使用合成日文数据成功训练过一次，这次是想在真实数据上继续训练，然后出了问题，应该不是reader的问题

**Comment by tink2123** [comment]
是加载了预训练模型？可以检查下是不是用的 -o Global.pretrain_weights={path}方式加载的，如果用的是 -o Global.checkpoints={path} 可能会有问题

**Comment by lfxx** [comment]
> 是加载了预训练模型？可以检查下是不是用的 -o Global.pretrain_weights={path}方式加载的，如果用的是 -o Global.checkpoints={path} 可能会有问题

改了之后可以成功运行了，可以说一下原理吗。。

**Comment by tink2123** [comment]
checkpoints 方式，代表训练中断后加载参数，继续训练，会把之前训练的参数完全加载进来。如果网络结构有变化，参数会有对不上的问题。
pretrain_weights方式，是加载预训练模型，当参数和网络结构对不上时，会默认不加载参数。使用随机初始化的结果，因此如果你不是断点训练的话，不推荐使用checkpints方式加载。

**Comment by lfxx** [comment]
> checkpoints 方式，代表训练中断后加载参数，继续训练，会把之前训练的参数完全加载进来。如果网络结构有变化，参数会有对不上的问题。
> pretrain_weights方式，是加载预训练模型，当参数和网络结构对不上时，会默认不加载参数。使用随机初始化的结果，因此如果你不是断点训练的话，不推荐使用checkpints方式加载。

明白了,我自己在合成数据(1999类,65000张图片)上训练后,测试正确率在80%左右,然后拿这个模型训练真实数据,损失很大,和直接从头训练表现差不多,这是为什么呢,因为合成数据种类少吗?

**Comment by tink2123** [comment]
类别不同的话，之前训练好的最后一层fc权重是没有用到的。另外合成数据的分布和真实数据也不相同，可以增加一下合成数据的丰富度，或者合成+真实数据一起训练。

**Comment by lfxx** [comment]
> 类别不同的话，之前训练好的最后一层fc权重是没有用到的。另外合成数据的分布和真实数据也不相同，可以增加一下合成数据的丰富度，或者合成+真实数据一起训练。

好的，感谢大佬
