### ISSUE TITLE
pgnet的标注问题

### ISSUE THREAD

**Issue by wuxiaolianggit** [PaddlePaddle/PaddleOCR#2550]
请问大佬，pgnet数据集标注的14点标注，有什么具体要求，水平文本也要需要标注14点吗？很短的文本标注14点，会不会很难标注啊？ @ZeyuChen @karlhorky @ufoym @jacquesqiao @ZhangXinNan

**Comment by MissPenguin** [comment]
不要求一定14点，文档里有相关说明：
![image](https://user-images.githubusercontent.com/25809855/115337699-0a20ea00-a1d4-11eb-8c1c-8e1d670a7884.png)

**Comment by chujian521** [comment]
pgnet的eval数据集标注格式是什么样子的啊，按照训练格式一样的话会报错，eval model::   0%|          | 0/50002 [00:00<?, ?it/s]root ERROR: When parsing line 0, error happened with msg: invalid literal for int() with base 10: 'ask2_images/gt_2836_0'

**Comment by MissPenguin** [comment]
> pgnet的eval数据集标注格式是什么样子的啊，按照训练格式一样的话会报错，eval model:: 0%| | 0/50002 [00:00<?, ?it/s]root ERROR: When parsing line 0, error happened with msg: invalid literal for int() with base 10: 'ask2_images/gt_2836_0'

这部分已经完成了适配，参考pr：
https://github.com/PaddlePaddle/PaddleOCR/pull/2576/files
可以拉取最新代码，设置metric的mode为A。A模式主要为了方便用户训练，和训练集一样的标注文件就可以eval，B模式主要为了和Total text的测评方式对齐。
