### ISSUE TITLE
C++推理部署问题

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#2551]
采用2.0.2版本paddle训练得到的推理模型，是否无法在2.0版本的c++推理库上使用？

推理采用官方老的2.0中文通用模型效果很好，但是采用新版的en_num发现预测效果很差，自己训练的模型同样效果很差。

请问是否和版本不同相关？

**Comment by littletomatodonkey** [comment]
关系应该不大，使用en num的时候，是否更改了字典了呢？
