### ISSUE TITLE
请问ORC识别模型，训练中断后如何继续上次结果接着训练？

### ISSUE THREAD

**Issue by zsshub** [PaddlePaddle/PaddleOCR#2553]

**Comment by klw2020** [comment]
配置里面有个checkpoints
checkpoints: ./output/rec_chinese_lite_v2.0/latest

**Comment by zsshub** [comment]
是的，谢谢

**Comment by zsshub** [comment]
> 配置里面有个checkpoints
> checkpoints: ./output/rec_chinese_lite_v2.0/latest

是的，谢谢
