### ISSUE TITLE
请问能否对多个文字中的每个字单独进行检测、识别？

### ISSUE THREAD

**Issue by tonytonglt** [PaddlePaddle/PaddleOCR#2554]
请问能否将多个文字中的每个字单独进行检测、识别，生成每个字单独的bbox和文字呢？
比如我图中有“恭喜发财”四个字，我想要得到“恭”“喜”“发”“财”四个字分别的四个bbox坐标和文字、置信度，而不是“恭喜发财”连起来的一个bbox和文字、置信度，请问这样子可以做到吗？需要做哪些修改呢？谢谢！

**Comment by klw2020** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q3413%E8%83%BD%E5%90%A6%E8%BF%94%E5%9B%9E%E5%8D%95%E5%AD%97%E5%AD%97%E7%AC%A6%E7%9A%84%E4%BD%8D%E7%BD%AE

**Comment by mikeshi80** [comment]
如果想要单个文字的大致位置，更好的方法是使用CRAFT算法( https://github.com/clovaai/CRAFT-pytorch )，在飞桨的FAQ（Q1.1.1）中虽有提及这个算法，不过官方并没有实现。 具体效果参见这个

 <img src="https://github.com/clovaai/CRAFT-pytorch/blob/master/figures/craft_example.gif?raw=true">

**Comment by tonytonglt** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q3413%E8%83%BD%E5%90%A6%E8%BF%94%E5%9B%9E%E5%8D%95%E5%AD%97%E5%AD%97%E7%AC%A6%E7%9A%84%E4%BD%8D%E7%BD%AE

感谢回复！
但我看这个FAQ提到的是“根据预测的文本和字符数量，再根据文本行的位置，来估计每个字符的位置”，但在我的场景中，不同的文本行的文字大小和间距是不同的，那是不是就很难有一个统一的方法来估计每张图片单独的字符位置呢？

**Comment by tonytonglt** [comment]
> 如果想要单个文字的大致位置，更好的方法是使用CRAFT算法( https://github.com/clovaai/CRAFT-pytorch )，在飞桨的FAQ（Q1.1.1）中虽有提及这个算法，不过官方并没有实现。 具体效果参见这个
> 
> ![](https://github.com/clovaai/CRAFT-pytorch/blob/master/figures/craft_example.gif?raw=true)

感谢回复！
看了下这个github，好像这里提供的CRAFT算法的预训练模型支持的语言只有英文的，在不重新训练的情况下，是不是就没办法对中文的每个字符进行识别呢？

**Comment by mikeshi80** [comment]
不要被动图迷惑了，毕竟CRAFT算法是韩国人提出来的，所以他们训练的模型是针对英文+东亚文字的，对汉字识别非常精确。

**Comment by tonytonglt** [comment]
> 不要被动图迷惑了，毕竟CRAFT算法是韩国人提出来的，所以他们训练的模型是针对英文+东亚文字的，对汉字识别非常精确。

好的，非常感谢！我尝试一下

**Comment by Quangui-He** [comment]
> > 不要被动图迷惑了，毕竟CRAFT算法是韩国人提出来的，所以他们训练的模型是针对英文+东亚文字的，对汉字识别非常精确。
> 
> 好的，非常感谢！我尝试一下

朋友你好这个效果怎么
