### ISSUE TITLE
2.0.2 Windows 预测库无法下载

### ISSUE THREAD

**Issue by mxy493** [PaddlePaddle/PaddleOCR#2555]
[安装与编译 Windows 预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/windows_cpp_inference.html)

![image](https://user-images.githubusercontent.com/46776216/115193048-38dc8900-a11e-11eb-8e4c-00370721a387.png)

无法下载：
![image](https://user-images.githubusercontent.com/46776216/115193234-76411680-a11e-11eb-88ce-71cf538efe88.png)

**Comment by yuelaiyue2** [comment]
第二个也下不了

**Comment by littletomatodonkey** [comment]
cpu: https://paddle-wheel.bj.bcebos.com/2.0.2/win-infer/mkl/cpu/paddle_inference.zip

gpu: https://paddle-wheel.bj.bcebos.com/2.0.2/win-infer/mkl/post100/paddle_inference.zip

**Comment by littletomatodonkey** [comment]
我们也更新下官网，感谢反馈~
