### ISSUE TITLE
训练的时候出现动态库的错误

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#256]
python tools/train.py -c ./configs/det/det_r50_vd_db.yml -o Global.pretrain_weights=./pretrain_models/ResNet50_vd_ssld_pretrained

训练的时候出现以下错误
Error: Failed to find dynamic library: libnccl.so ( libnccl.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

**Comment by LDOUBLEV** [comment]
提示找不到libnccl.so，如果cuda  NCCL没问题，试试export 设置环境变量LD_LIBRARY_PATH到你的cuda/lib下

**Comment by wangning7149** [comment]
怎样查看 cuda NCLL 的问题呢？

**Comment by wangning7149** [comment]
解决了！有一样问题的朋友安装libnccl.so就可以了。
