### ISSUE TITLE
checkpoints和pretrained_model区别

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/PaddleOCR#2564]
如题，这两个具体区别在哪里，是不是都可以用这两个来finetune

**Comment by mikeshi80** [comment]
不一样的，checkpoints是继续你上一次的训练，比如你上一次迭代了1000次了，用这个checkpoints，就可以继续下去，但是pretained model每次都是从1开始。当然，这不是最大的区别，checkpoints是要求你的模型完全一致的，比如你想自己训练一个模型，字库的文字数从3000变成了3010，那么checkpoints就不能用了，它会说模型不一致的，但是pretrained model是可以的。

总之，一个是用来继续之前未完成的训练的，所有参数必须完全一致，而另一个是用来做迁移学习的，模型可以做少量修改。

**Comment by aaferrero** [comment]
pretrained model 是不是取中间的cnn层，或者是部分层，checkpoints如果参数都一致，从checkpoints继续训练下去的效果是不是和pretrained model一样，我就想知道两者都可以训练下去，都是能作finetune的，而且我发现从checkpoints中恢复训练，识别率是从0开始的这是为什么呢

**Comment by mikeshi80** [comment]
这就不清楚了，我只能怀疑你是不是把checkpoints的数据放在配置中的`pretrained_model`而不是`checkpoints`中了。

我放在`checkpoints`中，准确度是跟着之前走的
