### ISSUE TITLE
使用单机多卡训练，一直报错，使用的PGnet

### ISSUE THREAD

**Issue by Harrison410-web** [PaddlePaddle/PaddleOCR#2565]
ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] 
“python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=/home/user/cqq/PaddleOCR/pretrain_models/train_step1/best_accuracy Global.load_static_weights=False”

**Comment by Harrison410-web** [comment]
用了多卡训练后，想恢复单卡训练，一直出现这个问题
'''
File "/home/user/cqq/paddleocr2/PaddleOCR/ppocr/utils/e2e_utils/extract_batchsize.py", line 26, in org_tcl_rois
    pos_lists_split[gpu_id].append(pos_list)
IndexError: list index out of range
'''

**Comment by JetHong** [comment]
你现在是单机多卡，单机单卡？

**Comment by Harrison410-web** [comment]
我是单机多卡，尝试训练一段时间，想换回单机单卡就一直报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月20日(周二) 晚上6:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 使用单机多卡训练，一直报错，使用的PGnet (#2565)




 
你现在是单机多卡，单机单卡？

**Comment by jaychen1996-byte** [comment]
看你的配置文件的85行，你改了batch_size要跟下面的一致。
