### ISSUE TITLE
文字检测训练 每最后一个iter会无报错退出

### ISSUE THREAD

**Issue by 1431241631** [PaddlePaddle/PaddleOCR#2568]
train_dataloader_len 19
[2021/04/20 16:33:49] root INFO: epoch: [1/1200], iter: 18, lr: 0.001000, loss: 7.009249, loss_shrink_maps: 4.877296, loss_threshold_maps: 1.159563, loss_binary_maps: 0.976661, reader_cost: 0.20449 s, batch_cost: 0.33140 s, samples:
 120, ips: 36.20982

**Comment by littletomatodonkey** [comment]
1. drop last改为false看下
2. 把下面这个部分改成`if idx >= len(train_dataloader)-1`


https://github.com/PaddlePaddle/PaddleOCR/blob/63221916af26df7eae6ac406aac1c8433d1fdc2f/tools/program.py#L201

**Comment by 1431241631** [comment]
> 1. drop last改为false看下
> 2. 把下面这个部分改成`if idx >= len(train_dataloader)-1`
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/63221916af26df7eae6ac406aac1c8433d1fdc2f/tools/program.py#L201

确实是这样的，已经可以训练了

**Comment by liuyangly1** [comment]
我靠一步一步print打印锁定了train_dataloader最后一次循环有问题，但是没有想到这么简单的解决办法，只要不跑最后一次就好了。
`
for idx, batch in enumerate(train_dataloader):
    if idx >= len(train_dataloader)-1:
        break
`
