### ISSUE TITLE
PGNet测试集数据标注格式

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#2569]
请问PGNet测试集数据标注是什么样的啊？跟训练集一样的标注会报错，没法eval

**Comment by JetHong** [comment]
这个是因为要和total_text官方的评测指标对齐，官方提供的是gt_mat文件，所以eval是通过加载gt_mat文件来做的。后续我们会提供脚本将测试集的label转为mat来提供测评

**Comment by Harrison410-web** [comment]
那现在想制作自己的测试集应该怎么做呢

**Comment by JetHong** [comment]
为了方便用户测试，我们正在修改相关代码，保证与训练集相同的标签就可以测试，预期今晚可以上线，欢迎明天更新代码~

**Comment by Harrison410-web** [comment]
好像还是没有说测试集的事，如何制作自己的测试集，或者测试集跟total_txt是一样的吗

**Comment by Harrison410-web** [comment]
l另外每当评估的时候==> eval :会出现如下错误
'''
root ERROR: When parsing line 0, error happened with msg: invalid literal for int() with base 10: 'mg/1'
'''

**Comment by chujian521** [comment]
我出现的也是这个错误，上面的JetHong已经回复啦，是因为测试集标注的问题。我目前是直接把eval参数改的很大，这样就可以跳过评估这个步骤，也就不会报错。最好的方案就是等官方改好代码

**Comment by Harrison410-web** [comment]
谢谢你和JetHong的回复，我以为今天会更新代码，看了一下更新的内容，还是没看到测试集如何解决。

**Comment by JetHong** [comment]
可以看一下哈，现在代码已经更新了

**Comment by Harrison410-web** [comment]
我跳过了测试集评估，但是产生的模型去推理，总是有问题,:这个函数具体作用我还没摸清，dst_str有时为空，就会报错
def ctc_decoder_for_image(gather_info_list,
                          logits_map,
                          Lexicon_Table,
                          pts_num=6):
    """
    CTC decoder using multiple processes.
    """
    # lexicon_table ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    decoder_str = []
    decoder_xys = []
    for gather_info in gather_info_list:
        if len(gather_info) < pts_num:
            continue
        dst_str, xys_list = instance_ctc_greedy_decoder(
            gather_info, logits_map, pts_num=pts_num)

        dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])  # 出错的地方为 dst_str 是空的
        if len(dst_str_readable) < 2:
            continue
        decoder_str.append(dst_str_readable)
        decoder_xys.append(xys_list)
    return decoder_str, decoder_xys

**Comment by JetHong** [comment]
这个函数的具体作用是，通过像素点去得到字符串。建议使用一下官方的模型，看看预测和评估是否正常。然后能定位代码问题还是模型问题
