### ISSUE TITLE
模型的loss大概在什么范围就表示收敛

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#257]
我训练DB的时候total_loss一直在3左右，请问这是收敛了吗?

**Comment by MissPenguin** [comment]
应该还没收敛，最终应该是降到1左右

**Comment by wangning7149** [comment]
好的，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MissPenguin"<notifications@github.com&gt;; 
发送时间: 2020年6月23日(星期二) 下午4:19
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;; 
抄送: "王宁"<714970851@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 模型的loss大概在什么范围就表示收敛 (#257)





 
应该还没收敛，最终应该是降到1左右
