### ISSUE TITLE
阿拉伯语训练时训练数据要如何处理，现在按正常文本训练效果很差

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/PaddleOCR#2575]
python -m paddle.distributed.launch --gpus '2,3,4,5' tools/train.py -c configs/rec/multi_language/rec_arabic_lite_train.yml 
数据是自己生成的将近100w数据，按照官方文档训练的，但是loss一直在20多，acc一直是0
会不会是阿语的顺序要调整，还是怎么，是不是因为阿语是从右向左的顺序的问题，有些该连写的没连写，我图片生成的是对的，从右向左生成的，但是文字是不是也要怎么处理下？

而且我在windows打开文字是这样
![1618972109(1)](https://user-images.githubusercontent.com/47582901/115487981-56c7fc00-a28c-11eb-825f-27c9fc5ce03d.jpg)

linux是这样
![1618972162(1)](https://user-images.githubusercontent.com/47582901/115488055-78c17e80-a28c-11eb-8d54-4f3e9404c714.jpg)
这又是啥问题

**Comment by tink2123** [comment]
> 我图片生成的是对的，从右向左生成的，但是文字是不是也要怎么处理下？

文字按正常顺序准备即可。

linux 和 windows 可能是字符编码不同，看起来linux是正确的
