### ISSUE TITLE
paddlehub中文OCR模型存在BUG

### ISSUE THREAD

**Issue by DeepGeGe** [PaddlePaddle/PaddleOCR#2578]
PaddleHub中中文OCR文字识别模型chinese_ocr_db_crnn_mobile和chinese_ocr_db_crnn_server存在BUG，使得当文字识别框个数大于30时，只能识别30个结果。详细见截图，问题出在两个模型的module.py文件。
![1](https://user-images.githubusercontent.com/51083814/115520261-8f7fc980-a2bc-11eb-966d-2dfcb478d67b.png)
![2](https://user-images.githubusercontent.com/51083814/115520301-99a1c800-a2bc-11eb-82fb-5e4a8320f179.png)

**Comment by DeepGeGe** [comment]
现在OCR超轻量中英文识别在线体验版就是用了这个有BUG版本，导致多余30个文字框的都会丢失结果。

**Comment by ShenYuhan** [comment]
感谢您提供的建议，欢迎您向paddlehub的repo提供pr，帮助我们进行优化。ocr模型的代码位置在https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/modules/image/text_recognition
如果您不方便，我们会在稍后进行优化升级。

**Comment by DeepGeGe** [comment]
pr已提交。
