### ISSUE TITLE
模型训练参数starnet 

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2580]
image_shape  heigh只能是32 吗
![image](https://user-images.githubusercontent.com/44855506/115533687-8ba67400-a2c9-11eb-820b-5125862a43fc.png)

**Comment by Mafengqiang** [comment]
> image_shape heigh只能是32 吗
> ![image](https://user-images.githubusercontent.com/44855506/115533687-8ba67400-a2c9-11eb-820b-5125862a43fc.png)

我改成别的参数，一改 就报错，width可以改，但是height就不行
![image](https://user-images.githubusercontent.com/44855506/115639651-b59e7b80-a347-11eb-8100-1626669a3de1.png)

**Comment by Mafengqiang** [comment]
> > image_shape heigh只能是32 吗
> > ![image](https://user-images.githubusercontent.com/44855506/115533687-8ba67400-a2c9-11eb-820b-5125862a43fc.png)
> 
> 我改成别的参数，一改 就报错，width可以改，但是height就不行
> ![image](https://user-images.githubusercontent.com/44855506/115639651-b59e7b80-a347-11eb-8100-1626669a3de1.png)

我的数据集不是规则的长条状的，所以要把height改一下，有没有方法可以改呢

**Comment by tink2123** [comment]
image shape 可以修改，但是需要保证backbone输出的最后一层，高度为1。如果修改 image shape，也需要适当修改backbone的stride，保证最后高度被下采样到1

**Comment by Mafengqiang** [comment]
> stride

stride要在哪里修改呢，我要把image shape 改成（3,100,160）的话，stride改成多少合适呢，谢谢你了

**Comment by Mafengqiang** [comment]
> image shape 可以修改，但是需要保证backbone输出的最后一层，高度为1。如果修改 image shape，也需要适当修改backbone的stride，保证最后高度被下采样到1

stride要在哪里修改呢，我要把image shape 改成（3,100,160）的话，stride改成多少合适呢，谢谢你了

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/modeling/backbones/rec_mobilenet_v3.py 改这个文件里的网络，你这个shape得你自己调试了
