### ISSUE TITLE
识别模型的推理速度的疑问

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/PaddleOCR#2581]
` startTime = datetime.now()
  rec_res, predict_time = self.text_recognizer_context(img_list)   //引用predict_rec.py的识别类
  endTime = datetime.now()
  howLong = endTime - startTime
  elapsedTime = '%d.6%d' % (howLong.seconds, howLong.microseconds)`
伙伴们！我发现预测时间和我在函数外部打印的时间差很多，前者能在0.015秒，后者在0.619011秒，请问是什么原因呢，的确速度有些慢，有什么办法提速一波？
![image](https://user-images.githubusercontent.com/51236891/115533945-d7591d80-a2c9-11eb-8f51-58bbfc1b0c92.png)

**Comment by tink2123** [comment]
统计时间的位置不同
加速办法：GPU 开启tensorrt，CPU开启mkldnn；尝试用多进程等等

**Comment by JianJingGao** [comment]
后来发现是统计时间的方法不同，结果也不一样。Tensorrt有版本要求吗

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月22日 16:09
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleOCR] 识别模型的推理速度的疑问 (#2581)


统计时间的位置不同
加速办法：GPU 开启tensorrt，CPU开启mkldnn；尝试用多进程等等

―
