### ISSUE TITLE
请问轻量级中文ocr模型对图像有什么要求？

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleOCR#2583]
经过测试，同一张图片设置不同的DetResizeForTest的resize_long参数后，会有不同的表现效果，设置大了反而识别不出。 但是对一张图片设置好表现最佳参数后，其他图片又表现差了。
请问这里面有没有参数设置的标准，比如基于输入图像的像素，应该设置多少合适，有没有自适应的参数设置？

**Comment by tink2123** [comment]
没有自适应的参数设置，这个确实需要针对不同场景调整。默认的参数是可以适用大部分场景的，其他就需要自己调参了
