### ISSUE TITLE
可在树莓派4B上使用吗？

### ISSUE THREAD

**Issue by JescalLin** [PaddlePaddle/PaddleOCR#2585]
ARM架构下，有试着在树莓派编译安装paddlelite(2.8.0)也成功了
是否有完整的Python API的教学?

这位大佬有提供分类的教学
https://blog.csdn.net/qq_45779334/article/details/112155819
但要怎么应用到目标检测或OCR?  谢谢
刚接触 还是小白 请多包涵

**Comment by littletomatodonkey** [comment]
可以参考这个文档：

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md#2-%E5%9F%BA%E4%BA%8Ectc%E6%8D%9F%E5%A4%B1%E7%9A%84%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86
