### ISSUE TITLE
编译PaddleOCR C++预测demo 运行sh tools/build.sh 出现问题make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by upcdz** [PaddlePaddle/PaddleOCR#2586]
cmake cxx flags -g -o3  -std=c++11
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/Projects/PaddleOCR/deploy/cpp_infer
make: *** No targets specified and no makefile found.  Stop.

**Comment by littletomatodonkey** [comment]
日志信息可以提供的更全一些吗？

**Comment by upcdz** [comment]
你好，它就出现这个。













在 2021-04-22 16:13:32，"littletomatodonkey" ***@***.***> 写道：

日志信息可以提供的更全一些吗？

**Comment by upcdz** [comment]
> 日志信息可以提供的更全一些吗？

你好，就出现这些日志，没有别的啦。
