### ISSUE TITLE
阿拉伯语和维语的检测效果很差

### ISSUE THREAD

**Issue by WiliiamBryant** [PaddlePaddle/PaddleOCR#2589]
您好，很喜欢您的项目，一直关注着PaddleOCR的进展
我这边测试维语和阿拉伯语时发现识别效果很差，可视化输出后发现检测效果很差，漏检严重，如下图

![uu1](https://user-images.githubusercontent.com/51152883/115650316-8eea4000-a35b-11eb-82d1-c13e9b846449.jpg)

![uu2](https://user-images.githubusercontent.com/51152883/115650885-ae359d00-a35c-11eb-87c7-9fdce1f14ff5.jpg)

修改det_db_unclip_ratio等相关参数也没什么提升，不知道是不是检测模型效果不太好。

另外，对于中英文识别，我发现后面发布的文本检测模型都没有最开始的ch_det_r50_vd_db_infer（98M）效果好；后面发布的识别模型的空格识别效果也没有最开始的ch_rec_r34_vd_crnn_enhance_infer（105M）效果好。希望能够发布一版更优的2.0版模型

测试环境：
System CentOS7
CUDA Version 10.0.130
paddleocr 2.0.6
paddlepaddle-gpu 2.0.1

**Comment by littletomatodonkey** [comment]
这种情况建议搞点小语种的检测数据集，微调一下

**Comment by tink2123** [comment]
阿拉伯语的识别结果的可视化结果不准确，由于他们反向书写的特性，需要看下在任务台print出来的结果。

另外这两个小语种的识别效果也需要继续提升。

我们推出了对空格支持更好的英文数字模型，感兴趣的话可以尝试下：https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_number_mobile_v2.0_rec_infer.tar

**Comment by WiliiamBryant** [comment]
> 阿拉伯语的识别结果的可视化结果不准确，由于他们反向书写的特性，需要看下在任务台print出来的结果。
> 
> 另外这两个小语种的识别效果也需要继续提升。
> 
> 我们推出了对空格支持更好的英文数字模型，感兴趣的话可以尝试下：https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_number_mobile_v2.0_rec_infer.tar

你好，同样是上面两张图片，我在控制台上print出来，同样存在漏词严重的现象
![ug1](https://user-images.githubusercontent.com/51152883/115979583-5778cf00-a5b9-11eb-8e50-99b22a8f48db.jpg)
![ug2](https://user-images.githubusercontent.com/51152883/115979596-63fd2780-a5b9-11eb-963d-9c4dc18c0e7c.jpg)
或许是en检测模型并不适合阿拉伯语或维语，需要阿拉伯语或维语的图片数据进行微调？但我之前用全英文数据集训练的检测模型同样能检测中文

**Comment by WiliiamBryant** [comment]
> 这种情况建议搞点小语种的检测数据集，微调一下

你好，请问你那有没有维语文本检测数据集呢？因为要做有监督，很难搜集到带标签的小语种数据
