### ISSUE TITLE
使用uwsgi部署paddleocr模型时初始化cuda失败

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleOCR#2595]
File "./tools/infer/predict_det.py", line 223, in __call__
    self.input_tensor.copy_from_cpu(img)
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:200)

请问怎么解决？

**Comment by daixiangzi** [comment]
+1

**Comment by MagicCodess** [comment]
+1

**Comment by wzy123456wzy** [comment]
+1 我也是遇到该问题 cuda是11.4 cudnn 8.2

**Comment by Essence9999** [comment]
大佬，解决了吗？如何解决
