### ISSUE TITLE
可以在Windows环境下train吗？

### ISSUE THREAD

**Issue by Bobby-youngking** [PaddlePaddle/PaddleOCR#2596]

**Comment by zhaoyantao-murray** [comment]
当然可以，你看看文档

**Comment by Bobby-youngking** [comment]
> 当然可以，你看看文档

哪里？？我真没找到，还望指教

**Comment by zhaoyantao-murray** [comment]
> > 当然可以，你看看文档
> 
> 哪里？？我真没找到，还望指教

![image](https://user-images.githubusercontent.com/61047836/115806954-49407c80-a41a-11eb-90e9-0499eaf8dfbf.png)
在win的终端运行里面的命令就可以了，注意python3 改成python，文档里的是linux命令。

**Comment by Bobby-youngking** [comment]
非常感谢
