### ISSUE TITLE
PGNET datasets

### ISSUE THREAD

**Issue by PureHing** [PaddlePaddle/PaddleOCR#2601]
你好，按照PGNET的[readme](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/pgnet.md#%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE)说明，想请问这个链接下载的数据集并没有total_text.txt这个文件，是需要自己重新标注转为ppocr的label格式吗
另外，
1.请问是否在后续考虑裁剪pgnet？满足arm A系列芯片的部署，比如rk系列的板子。如有，请问大概什么时候
2.pgnet目前的TDO阶段好像不适用这样的场景：输入图片是上下镜像倒置的图片，不知有好的建议吗

**Comment by JetHong** [comment]
我们预计今天会提供一份total_text的训练集的网盘地址，到时候关注一下哈～
1、目前暂时还没有计划，如果有模型压缩的相关需求，可以参考PaddleSlim教程自己尝试，https://github.com/PaddlePaddle/PaddleSlim ，然后过程中如果有问题，欢迎随时向PaddleSlim提issue
2、数据集中是没有这类图片的，因为镜像倒置涉及到文字的识别方向以及图片特征这两个问题，假如你这类数据比较多的话，建议重新训练一下试试

**Comment by PureHing** [comment]
@JetHong 
> 2、数据集中是没有这类图片的，因为镜像倒置涉及到文字的识别方向以及图片特征这两个问题，假如你这类数据比较多的话，建议重新训练一下试试

如果在数据集中预处理添加上下镜像的，那么文字的word label也需要跟着镜像吗？我看论文中说TDO是按照人眼视觉的正确阅读顺序，那么镜像了方向应该反了呀

**Comment by JetHong** [comment]
是的，标注的时候，需要从左到右标注

**Comment by PureHing** [comment]
@JetHong 谢谢。那再请问一下[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/pgnet.md)说的"上下对称，左右距离一致"中，左右距离一致如何理解？

**Comment by JetHong** [comment]
会更新在pgnet的文档里面，下载链接会换掉，左右一致指的是左右两点间的距离尽量保持一致，别出现极端的情况

**Comment by PureHing** [comment]
明白了  谢谢

**Comment by PureHing** [comment]
@JetHong 你好，链接还是没有label标签

> 会更新在pgnet的文档里面，下载链接会换掉，左右一致指的是左右两点间的距离尽量保持一致，别出现极端的情况

**Comment by PureHing** [comment]
![e2e_res_img623](https://user-images.githubusercontent.com/62579216/115978272-b8e87000-a5b0-11eb-9758-e2246ae4734d.jpg)

**Comment by JetHong** [comment]
你好，这种情况对于PGNet可能不能很好的识别了，因为网络中没有方向分类器这个模块，我建议使用一下ppocr的多阶段方式，至于ppocrlabel，可以询问一下专门负责这个模块的同学～
