### ISSUE TITLE
hub serving部署的相关参数说明？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2610]
请问使用hub serving进行部署，输入时对图片的大小，输出时的相关参数如错误码有几种，分别是什么含义。有没有相关的参数说明呢？

**Comment by littletomatodonkey** [comment]
具体错误可以贴一下吗？

**Comment by Lie-huo** [comment]
> 具体错误可以贴一下吗？

是这样的，使用Hubserving后，需要写一份api的说明文档，所以想了解一下使用hub serving进行部署时相关的参数说明

**Comment by MissPenguin** [comment]
> > 具体错误可以贴一下吗？
> 
> 是这样的，使用Hubserving后，需要写一份api的说明文档，所以想了解一下使用hub serving进行部署时相关的参数说明

您好，输入图片的尺度之类的没有限制，只是相当于把模型的预测接口暴露出来而已，错误码在代码里有：
![image](https://user-images.githubusercontent.com/25809855/116021857-a25b1b00-a67b-11eb-9e4f-5d191f2aa0b1.png)
https://github.com/PaddlePaddle/PaddleHub/blob/778db1ae865b944952057018236c51b965fdf7a3/paddlehub/serving/app_compat.py#L33
