### ISSUE TITLE
predict_det.py  'Namespace' object has no attribute 'det_db_score_mode'

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#2611]
File "..\tools\infer\predict_det.py", line 65, in __init__
    postprocess_params["score_mode"] = args.det_db_score_mode
AttributeError: 'Namespace' object has no attribute 'det_db_score_mode'

**Comment by littletomatodonkey** [comment]
你好，你这个是使用命令报错的呢？

**Comment by littletomatodonkey** [comment]
如果是hubserving的话，可以参考这个PR修改下自己的params.py
https://github.com/PaddlePaddle/PaddleOCR/pull/2612

**Comment by littletomatodonkey** [comment]
该pr已经merge了，也可以直接拉下最新代码哈，感谢反馈~

**Comment by xulihang** [comment]
paddleocr.py也有这个问题

**Comment by littletomatodonkey** [comment]
> paddleocr.py也有这个问题

使用提供的whl包应该没有问题，自己编译生成whl的话，可以在下面这里后面加上`parser.add_argument("--det_db_score_mode", type=str, default="fast")`，代码明天我们更新下

https://github.com/PaddlePaddle/PaddleOCR/blob/68560891d192922291455a439e759fccbba18772/paddleocr.py#L195

**Comment by ronaldpan** [comment]
> 如果是hubserving的话，可以参考这个PR修改下自己的params.py
> #2612
不是hubserving

**Comment by MissPenguin** [comment]
> > 如果是hubserving的话，可以参考这个PR修改下自己的params.py
> > #2612
> > 不是hubserving, 是执行命令 python PPOCRLabel.py --lang ch

PPOCRLabel就是调用的paddleocr.py，刚刚代码已更新，拉最新代码再试试吧
