### ISSUE TITLE
ubuntu环境下 paddleOCR按照官方教程安装完毕，依然无法 import。

### ISSUE THREAD

**Issue by austinxln** [PaddlePaddle/PaddleOCR#2619]
参考的安装连接是这个：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/installation.md  

运行到最后一步 
![image](https://user-images.githubusercontent.com/19772008/115957087-1a69f980-a533-11eb-94e4-9bfd99ecfaea.png)

提示成功，但是尝试import paddleocr 依然提示失败。

![image](https://user-images.githubusercontent.com/19772008/115957121-3f5e6c80-a533-11eb-92e7-3544c69a60f7.png)

求大佬们支招，如何才能安装paddleocr，感谢。

**Comment by MissPenguin** [comment]
你这个调用的是paddleocr的whl包，需要进一步pip install paddleocr，具体可以看这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/whl.md

**Comment by austinxln** [comment]
> 你这个调用的是paddleocr的whl包，需要进一步pip install paddleocr，具体可以看这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/whl.md

感谢大佬，我再试试。
