### ISSUE TITLE
训练时会卡住

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/PaddleOCR#262]
![image](https://user-images.githubusercontent.com/18586273/85388832-297dc500-b579-11ea-8f8a-f2c6d18bb5c5.png)

**Comment by Ezra-Yu** [comment]
![image](https://user-images.githubusercontent.com/18586273/85392601-52ed1f80-b57e-11ea-8683-d4c71163d2c4.png)
等了半天，发现每一个iter的时间差别好大，这是什么原因，我训练的就是icdar

**Comment by LDOUBLEV** [comment]
看Loss下降还算正常，是不是机器有其他程序占用资源
