### ISSUE TITLE
检测推理的结果与C++的结果不一致

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#2620]
python tools/infer/predict_det.py --image_dir="./doc/imgs_en/1.jpg" --det_model_dir="./output/ch_db_mv3" --use_gpu=False --det_db_thresh=0.7  --det_db_box_thresh=0.2 --det_db_unclip_ratio=1.2
结果正确。

但用C++推理结果完全不对。c++的config.txt如下：
# model load config
use_gpu 0
gpu_id  0
gpu_mem  4000
cpu_math_library_num_threads  10
use_mkldnn 0

# det config
max_side_len  960
det_db_thresh  0.7
det_db_box_thresh  0.2
det_db_unclip_ratio 1.2
det_model_dir  ./output/ch_db_mv3
这是python推理的结果
![det_res_29f180900010007_1](https://user-images.githubusercontent.com/13417382/115976320-605ca700-a59f-11eb-87bb-4aba94bfacbb.jpg)
这是cpp推理的结果
![ocr_vis](https://user-images.githubusercontent.com/13417382/115976305-415e1500-a59f-11eb-9fe2-3edecc18c0b4.png)

**Comment by MissPenguin** [comment]
您好，可以发下原图吗

**Comment by austinxln** [comment]
@MissPenguin 大佬，请问可以帮忙看一下这个 issue吗?感谢。https://github.com/PaddlePaddle/PaddleOCR/issues/2619  
官方教程安装完 requirement.txt以后，感觉是不是还得有一些后续操作在教程里面没写？ 一直尝试import 一直失败

**Comment by MissPenguin** [comment]
> @MissPenguin 大佬，请问可以帮忙看一下这个 issue吗?感谢。#2619
> 官方教程安装完 requirement.txt以后，感觉是不是还得有一些后续操作在教程里面没写？ 一直尝试import 一直失败

刚刚已回复哈

**Comment by ronaldpan** [comment]
> 您好，可以发下原图吗

![omr3](https://user-images.githubusercontent.com/13417382/115978083-ca7d4800-a5af-11eb-9c8b-1ba4280ef827.jpg)
推理模型怎么上传？

**Comment by MissPenguin** [comment]
> > 您好，可以发下原图吗
> 
> ![omr3](https://user-images.githubusercontent.com/13417382/115978083-ca7d4800-a5af-11eb-9c8b-1ba4280ef827.jpg)
> 推理模型怎么上传？

是自己重新训练的模型？邮件到lichenxia@baidu.com吧

**Comment by ronaldpan** [comment]
> lichenxia@baidu.com

模型在这里：https://github.com/ronaldpan/ronaldpan.github.io/blob/master/ch_db_mv3.rar

**Comment by MissPenguin** [comment]
> > [lichenxia@baidu.com](mailto:lichenxia@baidu.com)
> 
> 模型在这里：https://github.com/ronaldpan/ronaldpan.github.io/blob/master/ch_db_mv3.rar

好的，有结论后反馈哈

**Comment by MissPenguin** [comment]
您好，问题已定位，是因为python预测和c++预测的预处理中的resize操作不一致：

- 原图shape为 **110 * 508**

- python预处理按照短边resize到736（ https://github.com/PaddlePaddle/PaddleOCR/blob/73c7c6ac86dbc153ba557b856b4cb32dfc7fd3d6/ppocr/data/imaug/operators.py#L129 ），所以输入被缩放到 **736 * 3392**

- c++预处理按长边不超过960进行resize，即长边超过960时resize到长边960（ https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/src/preprocess_op.cpp#L62 ），长边没超过960时直接按原图输入，另外会微调至32的倍数，因此最后输入是 **96 * 480**

目前c++代码中只实现了长边960这一种resize方式，可以对照python代码添加更适合您的应用场景的其他resize方式，后续我们也会优化一下代码，将python和c++对齐。

**Comment by ronaldpan** [comment]
> 您好，问题已定位，是因为python预测和c++预测的预处理中的resize操作不一致：
> 
> * 原图shape为 **110 * 508**
> * python预处理按照短边resize到736（ https://github.com/PaddlePaddle/PaddleOCR/blob/73c7c6ac86dbc153ba557b856b4cb32dfc7fd3d6/ppocr/data/imaug/operators.py#L129
>    ），所以输入被缩放到 **736 * 3392**
> * c++预处理按长边不超过960进行resize，即长边超过960时resize到长边960（ https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/src/preprocess_op.cpp#L62 ），长边没超过960时直接按原图输入，另外会微调至32的倍数，因此最后输入是 **96 * 480**
> 
> 目前c++代码中只实现了长边960这一种resize方式，可以对照python代码添加更适合您的应用场景的其他resize方式，后续我们也会优化一下代码，将python和c++对齐。

请问python中config.yml 中设置哪个参数控制采用长边960？

**Comment by MissPenguin** [comment]
> > 您好，问题已定位，是因为python预测和c++预测的预处理中的resize操作不一致：
> > 
> > * 原图shape为 **110 * 508**
> > * python预处理按照短边resize到736（ https://github.com/PaddlePaddle/PaddleOCR/blob/73c7c6ac86dbc153ba557b856b4cb32dfc7fd3d6/ppocr/data/imaug/operators.py#L129
> >   
> >   ），所以输入被缩放到 **736 * 3392**
> > * c++预处理按长边不超过960进行resize，即长边超过960时resize到长边960（ https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/src/preprocess_op.cpp#L62 ），长边没超过960时直接按原图输入，另外会微调至32的倍数，因此最后输入是 **96 * 480**
> > 
> > 目前c++代码中只实现了长边960这一种resize方式，可以对照python代码添加更适合您的应用场景的其他resize方式，后续我们也会优化一下代码，将python和c++对齐。
> 
> 请问python中config.yml 中设置哪个参数控制采用长边960？

predict_det.py预测和yml无关了，预处理resize方式这里设置的none：https://github.com/PaddlePaddle/PaddleOCR/blob/73c7c6ac86dbc153ba557b856b4cb32dfc7fd3d6/tools/infer/predict_det.py#L42 ，所以会走到我上面贴出的else分支按短边736缩放

**Comment by yuelaiyue2** [comment]
> 您好，问题已定位，是因为python预测和c ++预测的预中的resize操作替代：
> 
> * 原图形状为**110 * 508**
> * python预先按照短边resize到736（ https://github.com/PaddlePaddle/PaddleOCR/blob/73c7c6ac86dbc153ba557b856b4cb32dfc7fd3d6/ppocr/data/imaug/operators.py#L129
>    ），所以输入被缩放到**736 * 3392**
> * c ++预按长边不超过960进行resize，即长边超过960时resize到长边960（[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/src/preprocess_op。 cpp＃L62](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/src/preprocess_op.cpp#L62)），长边没超过960时直接按原图输入，另外会微调至32的倍数，因此最后输入是**96 * 480**
> 
> 目前c ++代码中只实现了长边960这一种resize方式，可以对照python代码添加更适合您的应用场景的其他resize方式，随后我们也会优化一下代码，将python和c ++对齐。

你好，我想问一下DetResizeForTest这个类的实例化的地方。我想找到kwargs的传入，但通过打印信息只看到kwargs是一个空字典。
![image](https://user-images.githubusercontent.com/54937338/116336725-a1f18a00-a80b-11eb-99b5-cb340d6443bf.png)
