### ISSUE TITLE
关于识别模型的训练准确率

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2621]
您好，我下载了你们识别模型的训练的log文件，我看到使用了大概一千六百万数据训练，最后训练了35个epoch，在验证集上测试，准确率为76.8%。有点疑惑，这个准确率会不会有点小低？
![image](https://user-images.githubusercontent.com/43515926/115978365-4fb52c80-a5b1-11eb-9901-e85f9fd5fcd5.png)

**Comment by littletomatodonkey** [comment]
提供的验证集合是非常难的，我们的训练集也是包含了大部分的合成文本，你可以看下训练集acc 90+%

**Comment by zcswdt** [comment]
> 提供的验证集合是非常难的，我们的训练集也是包含了大部分的合成文本，你可以看下训练集acc 90+%

好的，明白了，谢谢哈

**Comment by Hupengyu** [comment]
> 您好，我下载了你们识别模型的训练的log文件，我看到使用了大概一千六百万数据训练，最后训练了35个epoch，在验证集上测试，准确率为76.8%。有点疑惑，这个准确率会不会有点小低？
> ![image](https://user-images.githubusercontent.com/43515926/115978365-4fb52c80-a5b1-11eb-9901-e85f9fd5fcd5.png)

还不错吧，我的eval的acc只有0.03..
