### ISSUE TITLE
检测训练时出现  The ``path`` (./pretrain_models/MobileNetV3_large_x0_5_pretrained.pdparams) to load model not exists.

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#2623]
执行 python tools/train.py -c configs/det/ch_det_mv3_db_v2.0_ocr.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/时出现错误：
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 93, in main
    pre_best_model_dict = init_model(config, model, logger, optimizer)
  File "D:\PaddleOCR\ppocr\utils\save_load.py", line 116, in init_model
    model, logger, path=pretrained, load_static_weights=load_static)
  File "D:\PaddleOCR\ppocr\utils\save_load.py", line 74, in load_dygraph_pretrain
    param_state_dict = paddle.load(path + '.pdparams')
  File "D:\Anaconda3\envs\paddleocr\lib\site-packages\paddle\framework\io.py", line 371, in load
    model_path, config = _build_load_path_and_config(path, config)
  File "D:\Anaconda3\envs\paddleocr\lib\site-packages\paddle\framework\io.py", line 159, in _build_load_path_and_config
    raise ValueError(error_msg % path)
ValueError: The ``path`` (./pretrain_models/MobileNetV3_large_x0_5_pretrained.pdparams) to load model not exists.

在release 2.0 中这样训练是正常的，没有错误。在release 2.1中出现上述错误。

**Comment by ganleiboy** [comment]
请问该如何解决呢？

**Comment by Lanme** [comment]
怎么解决的？

**Comment by chaosjeyli** [comment]
同问如何解决的

**Comment by Lanme** [comment]
> 同问如何解决的

好像2.1版本就是pdparams，之前的版本就是一个tar文件包含很多权重文件。

**Comment by liuwake** [comment]
`wget -P/kaggle/temp/PaddleOCR/pretrain_models/ \
    https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/MobileNetV3_large_x0_5_pretrained.pdparams`.
More backbone see `PaddleClas`/[docs/zh_CN/models/ImageNet1k/README.md](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.6/docs/zh_CN/models/ImageNet1k/README.md)
