### ISSUE TITLE
paddleocr对gpu的要求

### ISSUE THREAD

**Issue by wxiaoli** [PaddlePaddle/PaddleOCR#2627]
你好，安装说明中提到要求paddleoc使用的是Paddle2.0.0，请问2.0.0对cuda和操作系统的版本要求与2.0.2一样吗，可以具体介绍一下paddleocr对gpu的要求吗？

**Comment by MissPenguin** [comment]
2.0.0和2.0.2对环境的要求是一样的

**Comment by wxiaoli** [comment]
> 2.0.0和2.0.2对环境的要求是一样的

ok, 非常感谢
