### ISSUE TITLE
paddleocr 用lite部署到windows，有一些ARM下的指令要用什么指令替换？

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#2629]
https://github.com/PaddlePaddle/PaddleOCR/blob/01d41741120348a0400fd408ffa5f29c9393aac6/deploy/lite/ocr_db_crnn.cc#L26-L67

**Comment by littletomatodonkey** [comment]
windows上建议用cpp inference部署

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/deploy/cpp_infer/readme.md
