### ISSUE TITLE
2.x版本比1.x版本慢2倍

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#2630]
同一个系统，同一个python，使用paddle2.02和paddleocr2.x  比 paddle1.8.5和paddleocr1.1.1慢2倍以上。

使用cpu

而且测试发现：
1.x 开启enable_mkldnn=True，快，关闭，慢
2.x开启enable_mkldnn=True，慢1倍，关闭，快。

为何表现不一致？

**Comment by LDOUBLEV** [comment]
检测模型？建议线程数调整到10，开启mkldnn后都有明显加速，这个问题是新使用插值OP尚未支持mkldnn，paddle2.1会支持

**Comment by liyandongpy** [comment]
检测模型，2.01 确实慢了不止一倍，还不如退回去呢。

**Comment by liyandongpy** [comment]
> 检测模型？建议线程数调整到10，开启mkldnn后都有明显加速，这个问题是新使用插值OP尚未支持mkldnn，paddle2.1会支持

哪块开启线程数？

**Comment by liyandongpy** [comment]
> 检测模型？建议线程数调整到10，开启mkldnn后都有明显加速，这个问题是新使用插值OP尚未支持mkldnn，paddle2.1会支持

哪块开启线程数？
