### ISSUE TITLE
推理耗时问题

### ISSUE THREAD

**Issue by clive1158** [PaddlePaddle/PaddleOCR#2631]
使用predict_det.py进行推理时，self.input_tensor.copy_from_cpu()耗时严重。
![image](https://user-images.githubusercontent.com/16435973/115989183-beb17600-a5ef-11eb-94b2-53d72fb125ed.png)

![image](https://user-images.githubusercontent.com/16435973/115989193-d25cdc80-a5ef-11eb-8fa1-3ff234b175f2.png)

**Comment by LDOUBLEV** [comment]
没有吧，我这边测试速度挺快的，如果第一次运行都会慢一些，后续预测速度都还可以；

**Comment by clive1158** [comment]
> 没有吧，我这边测试速度挺快的，如果第一次运行都会慢一些，后续预测速度都还可以；

GPU速度好着，CPU速度很慢

**Comment by littletomatodonkey** [comment]
跑500张图片看下情况吧，单独一张不太能看出来

**Comment by clive1158** [comment]
跑500张图片，平均耗时2秒。 设置mkldnn好像没有太大效果，是不是因为用源码跑开启不了mkldnn呢？
