### ISSUE TITLE
win10 训练中断

### ISSUE THREAD

**Issue by chccc5** [PaddlePaddle/PaddleOCR#2636]
win10 Cuda11.0 训练icdar2015 检测，减小     batch_size，num_workers还是到
**eval model** 时候中断？？？？

![image](https://user-images.githubusercontent.com/68001817/116015443-d3335400-a66b-11eb-8192-18745b5305e4.png)
![image](https://user-images.githubusercontent.com/68001817/116017716-f3b2dc80-a672-11eb-83c7-3c86f19f27ae.png)

**Comment by littletomatodonkey** [comment]
把这里改成`if idx >= len(valid_dataloader) -1: `试下


https://github.com/PaddlePaddle/PaddleOCR/blob/db37ba33103f25607bc2b0004857378e7e786ca0/tools/program.py#L339

**Comment by chccc5** [comment]
好的，已解决。
