### ISSUE TITLE
网络结构的打印

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2639]
您好，我想打印网络的模型结构，这个怎么打印呢？

**Comment by tink2123** [comment]
可以使用 paddle.summary， 具体参考:https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/hapi/model_summary/summary_cn.html

**Comment by zcswdt** [comment]
> 可以使用 paddle.summary， 具体参考:https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/hapi/model_summary/summary_cn.html

您好，我在代码里面这个地方设置了断点，程序运行到这个地方会卡住，打印不了模型的结构。
![image](https://user-images.githubusercontent.com/43515926/116494178-dd0ac080-a8d2-11eb-83a2-3a2897e55405.png)

**Comment by zcswdt** [comment]
> 可以使用 paddle.summary， 具体参考:https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/hapi/model_summary/summary_cn.html

您好，我这个问题目前还没有解决，可以帮忙看一下么？谢谢

**Comment by tink2123** [comment]
参考我的修改，在这个位置添加代码：https://github.com/PaddlePaddle/PaddleOCR/blob/90bede2bb64161be8735d09d7df5ae6fcdc3b767/tools/train.py#L76

![image](https://user-images.githubusercontent.com/31891223/116641105-a306f080-a99e-11eb-8806-e155dc117b00.png)

**Comment by tink2123** [comment]
会得到如下结果：
![image](https://user-images.githubusercontent.com/31891223/116641215-d9dd0680-a99e-11eb-8fb1-04232e6ad279.png)

**Comment by zcswdt** [comment]
> 会得到如下结果：
> 会得到如下结果：
> ![image](https://user-images.githubusercontent.com/31891223/116641215-d9dd0680-a99e-11eb-8fb1-04232e6ad279.png)


您好，我使用的是DB训练代码，mobilenetv3网络骨架，然后在实例化网络模型以后，打印不出，程序结束，下面是代码，您看一下
![image](https://user-images.githubusercontent.com/43515926/116643266-380be880-a9a3-11eb-98af-83d6dd6fff59.png)

**Comment by zcswdt** [comment]
> 参考我的修改，在这个位置添加代码：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/90bede2bb64161be8735d09d7df5ae6fcdc3b767/tools/train.py#L76
> 
> ![image](https://user-images.githubusercontent.com/31891223/116641105-a306f080-a99e-11eb-8806-e155dc117b00.png)

您使用的是张量是（1，3，32，100）是识别模型的吧？我这个使用的是检测模型，使用（1，3，240，240）打印不了结国，请问识别模型具体使用多大张量呢？

**Comment by tink2123** [comment]
在 mv3_db 模型上打印也是可以得到结果的：
![image](https://user-images.githubusercontent.com/31891223/117237246-186e3780-ae5d-11eb-87a4-bf2b42e327e8.png)

![image](https://user-images.githubusercontent.com/31891223/117237234-0e4c3900-ae5d-11eb-8739-43b2b956eae0.png)

您使用的是2.0.0的paddle吗？

**Comment by zcswdt** [comment]
> 在 mv3_db 模型上打印也是可以得到结果的：
> ![image](https://user-images.githubusercontent.com/31891223/117237246-186e3780-ae5d-11eb-87a4-bf2b42e327e8.png)
> 
> ![image](https://user-images.githubusercontent.com/31891223/117237234-0e4c3900-ae5d-11eb-8739-43b2b956eae0.png)
> 
> 您使用的是2.0.0的paddle吗？

您那边使用的是哪个代码？我是使用的predict_det.py代码，是不是您使用的是infer_det.py的原因。我这个是2.0的paddle版本。
![image](https://user-images.githubusercontent.com/43515926/117251349-1d3fe500-ae77-11eb-9daa-81c4ae356275.png)
