### ISSUE TITLE
Style-text 中文和数字一起生成时，数字变扭曲

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleOCR#2642]

**Comment by littletomatodonkey** [comment]
之前训练集中这种情况考虑的比较少，方便发几张图片以及语料吗？我们也分析下~

**Comment by wuranran** [comment]
例如：
顺丰364
![fake_fusion](https://user-images.githubusercontent.com/38750407/116215298-21367d80-a77a-11eb-8f66-a36c9f1ac9fc.jpg)
357顺丰
![fake_fusion](https://user-images.githubusercontent.com/38750407/116215414-3ca18880-a77a-11eb-9a85-66b5b9a1b679.jpg)

**Comment by wuranran** [comment]
> 之前训练集中这种情况考虑的比较少，方便发几张图片以及语料吗？我们也分析下~
例如：
顺丰364
fake_fusion
357顺丰
fake_fusion
