### ISSUE TITLE
PGNet训练中文弯曲文本

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#2643]
请问PGNet训练中文弯曲文本的话是不是不能使用提供的预训练的模型啊？

**Comment by littletomatodonkey** [comment]
可以使用，不过有些层因为维度不同可能无法加载

**Comment by chujian521** [comment]
请问我修改配置文件character_dict_path为中文字符集的时候，类型改为ch， Loss里面的pad_num具体含义是什么呢？应该如何设置
