### ISSUE TITLE
在某个类的__call__中pdb打断点，不能停住

### ISSUE THREAD

**Issue by zzt6227** [PaddlePaddle/PaddleOCR#2644]
在ppocr代码中，某个类的__call__中pdb打断点，不能停住，直接就往下执行了，num_workers设为0，依然不能停住，请各位老师帮忙解答，是代码设置了多进程吗？还是其他什么问题

**Comment by tink2123** [comment]
可以具体描述下您的问题吗？想debug什么呢？num_workers=0 就是关闭多进程。
