### ISSUE TITLE
某一次跑了一个多线程的之后，再运行示例就报错了

### ISSUE THREAD

**Issue by MollyHoo** [PaddlePaddle/PaddleOCR#2645]
/usr/local/lib/python3.8/dist-packages/paddle/utils/cpp_extension/extension_utils.py:460: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/usr/local/lib/python3.8/dist-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
[2021-04-26 15:33:36,928] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0426 15:33:37.133873  5992 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
E0426 15:34:48.012296  5992 analysis_predictor.cc:641] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E0426 15:34:48.012315  5992 analysis_predictor.cc:644] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
[2021-04-26 15:34:53,486] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1619422656 (unix time) try "date -d @1619422656" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5992 (TID 0x7fa3c1834740) from PID 0 ***]

段错误 (核心已转储)

**Comment by tink2123** [comment]
是否修改过代码呢？可以查看一下进程有没有kill干净

**Comment by Hathaway2019** [comment]
用hub stop 提示没有进程了，没有修改代码的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月26日(周一) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 某一次跑了一个多线程的之后，再运行示例就报错了 (#2645)




 
是否修改过代码呢？可以查看一下进程有没有kill干净
