### ISSUE TITLE
Upload synthetic dataset to mirror

### ISSUE THREAD

**Issue by s-krunch** [PaddlePaddle/PaddleOCR#2649]
Hi, you mention a synthetic dataset in your [docs ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/recognition_en.md#12-dataset-download) that can be downloaded from this link: https://pan.baidu.com/s/1-HSZ-ZVdqBF2HaBZ5pRAKA

Would it be possible to upload this data elsewhere as well? I can't access pan.baidu.com...

Thanks for any help with this!

**Comment by tink2123** [comment]
Thank you for your use. We will put the data on the google drive as soon as possible and let you know here after the update.

**Comment by s-krunch** [comment]
Thanks! 🙏
