### ISSUE TITLE
 ResourceExhaustedError: Fail to alloc memory of 5060694016 size.

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2656]
Windows，cpu 8G，运行python tools/infer/predict_system.py使用ch_ppocr_server_v2.0_det_infer、ch_ppocr_server_v2.0_rec_infer进行预测时报内存的错误ResourceExhaustedError: Fail to alloc memory of 5060694016 size。使用的最新的2.1的代码，config.enable_memory_optim()也是开着的。请问这是什么原因呢？

**Comment by littletomatodonkey** [comment]
你的图片是多大？

**Comment by Lie-huo** [comment]
几十或者几百k，没有过1M的图片

**Comment by WenmuZhou** [comment]
内部不够了，清一下内存再跑看看

**Comment by Lie-huo** [comment]
> 内部不够了，清一下内存再跑看看

那一般需要多大的内存呢

**Comment by WenmuZhou** [comment]
你跑的时候盯一下内存情况，看看是不是这样
