### ISSUE TITLE
Easy Edge 网站上的 iOS OCR Demo 体验安装不了

### ISSUE THREAD

**Issue by KittenYang** [PaddlePaddle/PaddleOCR#2660]
这里有 PaddleOCR iOS Demo 体验  https://ai.baidu.com/easyedge/app/openSource, 但是扫描了二维码还是无法下载到 iOS, 图标一直是灰的，是现在不提供了吗？

**Comment by dium6i** [comment]
中文识别模型下载好了提示需要更新，开发者们是不是不管iOS上的东西了？
![IMG_0820](https://user-images.githubusercontent.com/75460093/147205995-b0114a45-5a5f-4a6e-8569-b7e4ebc0f455.PNG)
