### ISSUE TITLE
C++推理如何设置rec_char_type

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#2663]
在C++推理过程中，发现使用en训练的字符，在c++推理得到的结果是乱的，感觉有点像字典重新映射了一遍，有谁知道原因吗

**Comment by yfc886** [comment]
我也遇到这个问题。 目前重新训练了 不能使用EN 要用 ch 才行

**Comment by blackhitomi** [comment]
> 我也遇到这个问题。 目前重新训练了 不能使用EN 要用 ch 才行

好的，谢谢！确实是这样，检测的时候似乎会把字典重排。
