### ISSUE TITLE
Visual studio 下无法编译，语法错误

### ISSUE THREAD

**Issue by znsoftm** [PaddlePaddle/PaddleOCR#2664]
C++推理代码

postprocess_op.cpp中，第189行：

  cv::Point rook_point[contour.size()];  // 这个语法，vc无法编译，vc不支持动态数组 ，只在gcc下支持，请改用new 操作或其它操作处理
  for (int i = 0; i < contour.size(); ++i) {
    rook_point[i] = cv::Point(int(box_x[i]) - xmin, int(box_y[i]) - ymin);
  }
  const cv::Point *ppt[1] = {rook_point};
  int npt[] = {int(contour.size())};
  cv::fillPoly(mask, ppt, npt, 1, cv::Scalar(1));

**Comment by znsoftm** [comment]
另外，cmake文件在windows下编译太困难了，加了太多不必要的flag,希望整理测试一下。

**Comment by LDOUBLEV** [comment]
你的VS code版本是？推荐用2019 ，之前在VScode2019 + windows上没遇到这个问题，而且编译建议用gcc 8.2版本

**Comment by znsoftm** [comment]
不是vscode, 是visual studio 2019 ，自带的msvc编译器，也不是gcc. 我已经pr了。 是语法问题。vc编译器不支持变长数组 。

int array[var]; 这样的是不允许 的，只支持常数，不支持变量。这是vc编译器的限制。
