### ISSUE TITLE
DB检测弯曲文字

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2667]
请问DB文字检测模型哪里设置可以检测弯曲的文本？

**Comment by WenmuZhou** [comment]
目前输出被限制为四边形文本了，弯曲文本的输出还没开放

**Comment by zcswdt** [comment]
> 目前输出被限制为四边形文本了，弯曲文本的输出还没开放

额。。。我的场景会有弯曲文字，请问这个有什么好的方法么

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/postprocess/db_postprocess.py#L91 这里的box用contour替代返回就行

**Comment by laocan** [comment]
> 
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/postprocess/db_postprocess.py#L91 这里的box用contour替代返回就行

用 contour 替代之后，给到识别前，是否需要先拉直成box？

**Comment by WenmuZhou** [comment]
能拉直最好，不能拉直就直接进去

**Comment by yxyangxu** [comment]
> 能拉直最好，不能拉直就直接进去

求问如何把polygon拉直，搜了半天没有搜到

**Comment by AlvinZheng** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/postprocess/db_postprocess.py#L91 这里的box用contour替代返回就行

contour[:, 0] = np.clip(
                np.round(box[:, 0] / width * dest_width), 0, dest_width)
请问这样吗？还是后面的box也要改为contour？

**Comment by justcodew** [comment]
同问  使用DBnet检测弯曲文字 需要修改哪些部分

**Comment by justcodew** [comment]
参考[ https://github.com/MhLiao/DB/blob/master/structure/representers/seg_detector_representer.py#L65]( https://github.com/MhLiao/DB/blob/master/structure/representers/seg_detector_representer.py#L65) 修改后处理，可以得到弯曲文本
