### ISSUE TITLE
c++推理精度问题，路过的大佬进来看看。

### ISSUE THREAD

**Issue by yfc886** [PaddlePaddle/PaddleOCR#2672]
python 下推理都正常，但是C++推理的话，只有第一行11个字符的正确。 第二行起4个字符的都不准确。 在PYTHON 下推理又全部正常。

**Comment by WenmuZhou** [comment]
给个图片看看

**Comment by yfc886** [comment]
> 给个图片看看
这是python代码跑的。识别效果很好
![2](https://user-images.githubusercontent.com/18112706/116387519-78595280-a84d-11eb-8a0f-f505db95aad8.png)

这是C++推理的结果。相同的模型。但是效果非常差
![111](https://user-images.githubusercontent.com/18112706/116387680-9d4dc580-a84d-11eb-9110-6efef6a30f94.png)

**Comment by yfc886** [comment]
大概问题出在rec_char_type=ch 上  我需要修改为rec_char_type=EN 
请问C++ 怎么设置rec_char_type 呢 ？
