### ISSUE TITLE
关于半自动标注工具

### ISSUE THREAD

**Issue by wangshihuang** [PaddlePaddle/PaddleOCR#2676]
您好，谢谢您的开源。
请问半自动标注工具，有一个矩形标注，但现实图片总是有倾斜，矩形标注不能很好的贴合，四点标注又很麻烦，不好掌控，是否能添加倾斜的矩形标注功能，根据三个点就标注好

**Comment by Evezerest** [comment]
你好，后续我们会评估一下这个功能，请问您的数据场景是什么呢
