### ISSUE TITLE
请教如何优化检测阶段时长

### ISSUE THREAD

**Issue by yinkanchn** [PaddlePaddle/PaddleOCR#2677]
os:win10
python:3.8
paddleocr:2.0.2
paddlepaddle-gpu:2.0.1  
enable_gpu:true
![image](https://user-images.githubusercontent.com/12893351/116341468-92763f00-a813-11eb-9104-b0b34fffe3bb.png)
检测+识别一张这样的图使用的时长是这样的
```
root INFO: dt_boxes num : 4, elapse : 1.117570400238037
root INFO: rec_res num  : 4, elapse : 0.05500006675720215
```
请教检测阶段这个耗时正常吗？可以优化吗？

**Comment by MissPenguin** [comment]
预测单张图会慢一点，如果批量预测，第一张图比较慢，后面就快了，因为最开始一些初始化操作比较耗时。

**Comment by yinkanchn** [comment]
> 预测单张图会慢一点，如果批量预测，第一张图比较慢，后面就快了，因为最开始一些初始化操作比较耗时。

耗时部分的操作可以单独预热吗？

**Comment by MissPenguin** [comment]
> > 预测单张图会慢一点，如果批量预测，第一张图比较慢，后面就快了，因为最开始一些初始化操作比较耗时。
> 
> 耗时部分的操作可以单独预热吗？

服务部署的话，访问一次后，后面再访问就不会初始化了，推理的话每次都需要初始化的

**Comment by yinkanchn** [comment]
> > > 预测单张图会慢一点，如果批量预测，第一张图比较慢，后面就快了，因为最开始一些初始化操作比较耗时。
> > 
> > 
> > 耗时部分的操作可以单独预热吗？
> 
> 服务部署的话，访问一次后，后面再访问就不会初始化了，推理的话每次都需要初始化的

好的。感谢
