### ISSUE TITLE
数据增强问题

### ISSUE THREAD

**Issue by chunniunai220ml** [PaddlePaddle/PaddleOCR#2679]
iaa里面添加的数据增强方式，是每张图像训练都会做增强还是随机的？比如做GaussianBlur等操作？
如何实现iaa.Sometimes(0.5,iaa.GaussianBlur(sigma=(0, 1.5))),？

还是说可以在train.py中，获取batch——imgs以后，添加
seq = iaa.Sequential([
            iaa.Sometimes(0.2,iaa.AdditiveGaussianNoise(scale=(10, 60))),
            iaa.Sometimes(0.5,iaa.GaussianBlur(sigma=(0, 1.5))),
            iaa.Sometimes(0.1,iaa.AddToHueAndSaturation((-60, 60))),
            iaa.Sometimes(0.1,iaa.ContrastNormalization((0.75, 1.5)))
        ], random_order=True)
        return seq(imgs)

这些操作？

**Comment by LDOUBLEV** [comment]
iaa增强的训练配置参考：https://github.com/PaddlePaddle/PaddleOCR/blob/0ccc1720c252beb277b9e522a1b228eb6abffb8a/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L82
{ 'type': Fliplr, 'args': { 'p': 0.5 } }    p是概率

新增数据增强，可以参考这个方法：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/add_new_algorithm.md#%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E5%A4%84%E7%90%86
