### ISSUE TITLE
2020-06-27 22:09:59  -  [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by minxinliu** [PaddlePaddle/PaddleOCR#268]
win10新安装的环境
根据文档安装paddlepaddle和paddlehub等依赖包，执行
(paddle) C:\Users\paddleadmin>hub serving start -m chinese_ocr_db_crnn_server
Warning: Windows cannot use multiprocess working mode, PaddleHub Serving will switch to single process mode
chinese_ocr_db_crnn_server == 1.0.0
 * Serving Flask app "paddlehub.serving.app_single" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-06-27 22:09:22,272-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
2020-06-27 22:09:59  -  [WinError 126] 找不到指定的模块。
2020-06-27 22:09:59,795-INFO: 127.0.0.1 - - [27/Jun/2020 22:09:59] "[37mPOST /predict/chinese_ocr_db_crnn_server HTTP/1.1[0m" 200 -

望解答，谢谢

**Comment by grasswolfs** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/507159
启动服务之前可以先试试把正常的python api跑通试试
本地预测没问题再启动服务哈

**Comment by minxinliu** [comment]
@grasswolfs 非常感谢，就是这个问题，已经解决
