### ISSUE TITLE
更多中文通用识别模型

### ISSUE THREAD

**Issue by superPangpang** [PaddlePaddle/PaddleOCR#2682]
目前仅公开了CRNN的中文通用识别模型？请问有没有公开更多算法 例如SRN的中文识别模型的打算？

**Comment by tink2123** [comment]
暂时没有这个计划

**Comment by wangshihuang** [comment]
> 暂时没有这个计划

请问有中文繁体的数据集吗，可以分享吗？

**Comment by tink2123** [comment]
@wangshihuang 我们没有使用开源的中文繁体的数据集，用的是自己合成的数据，抱歉无法提供。如果发现好的开源数据可以一起交流～
