### ISSUE TITLE
动态图模型文本检测不全

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2683]
在使用2.1的通用模型进行承兑汇票识别时，对与大写金额经常会检测不到，对于票据号码号码，经常会检测成两个框，请问这怎么解决呢，对于离得近的框怎么合并呢？
![image](https://user-images.githubusercontent.com/13652569/116495348-4e4b7300-a8d5-11eb-9ebb-e46048400837.png)

![image](https://user-images.githubusercontent.com/13652569/116495282-2e1bb400-a8d5-11eb-8fe9-94e4b10a054e.png)

**Comment by tink2123** [comment]
大写金额在训练数据中较少，有需要的话可以添加一些数据 finetune一下。离得近的框现在从模型上不好合并，可以加一些额外的规则进行合并。

**Comment by LDOUBLEV** [comment]
也可以打开--use_dilation 重新测试下

**Comment by Lie-huo** [comment]
> 也可以打开--use_dilation 重新测试下

请问这个参数的作用是什么呢

**Comment by Lie-huo** [comment]
> 也可以打开--use_dilation 重新测试下

请问这个参数的作用是什么呢，对于识别速度以及部署有什么影响吗？
