### ISSUE TITLE
使用Cmake构建的工程sIn,无法调试内部的main.cpp

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#2685]
平台Vs2017, Cuda10.1, Cudnn 7.6 , Cmake 3.16，
C++环境，windows操作系统
已经可以在命令行能够运行ocr_system.exe  config.txt,
但是想断点调试main.cpp，比如第二次运行图片时间，更改输入图像集目录，查看中间结果。
问题：
断点击不中，命令行显示no such label file: config.txt, exit the program...
不再使用命令行参数，改为int main() 后面赋临时值打断点，断点也击不中。程序退出

**Comment by ronaldpan** [comment]
只能release，不能debug

**Comment by liudongminghaha** [comment]
好吧，我再试试。

**Comment by liudongminghaha** [comment]
> 只能release，不能debug
好吧，我再试试。

**Comment by znsoftm** [comment]
不不，你可以调试。直接用visualstudio 打开cmake工程进行处理

**Comment by liudongminghaha** [comment]
> 不不，你可以调试。直接用visualstudio 打开cmake工程进行处理
> ![捕获](https://user-images.githubusercontent.com/15354249/116538077-a3a97380-a919-11eb-860b-28ff8e383c75.JPG)

还可以在Debug下调试，是需要修改什么配置吗？paddle编译了源码？

**Comment by liudongminghaha** [comment]
> 还可以在Debug下调试，是需要修改什么配置吗？paddle编译了源码？我debug出现这样的问题。

![image](https://user-images.githubusercontent.com/31954286/116539821-ed935900-a91b-11eb-985f-3d265123114d.png)

**Comment by liudongminghaha** [comment]
> 只能release，不能debug
[我找到了解决方案](https://blog.csdn.net/juluwangriyue/article/details/114441918)，另外字典，配置文件采用绝对路径。

**Comment by znsoftm** [comment]
这个是cmake写得有问题。我给你一个简化的版本，只支持vc++, 修改里面的路径为你的实际路径。
[CMakeLists.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6398443/CMakeLists.txt)
