### ISSUE TITLE
运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果

### ISSUE THREAD

**Issue by wjy3326** [PaddlePaddle/PaddleOCR#269]
运用你们提供的预训练模型
![image](https://user-images.githubusercontent.com/31943425/85936582-d320d580-b92e-11ea-8294-c741c88799e9.png)
和识别模型

![1593313505](https://user-images.githubusercontent.com/31943425/85936661-5e01d000-b92f-11ea-865c-63805fa679d2.png)

将下载的模型转换成inference模型，可是没有出来检测和识别结果，请问这个是怎么回事呢？

**Comment by wjy3326** [comment]
运用你们提供的预训练模型 EAST det_r50_vd_east ，和识别模型  rec_r34_vd_tps_bilstm_attn
将下载的模型转换成inference模型，可是没有出来检测和识别结果，请问这个是怎么回事呢？

**Comment by LDOUBLEV** [comment]
> 运用你们提供的预训练模型 EAST det_r50_vd_east ，和识别模型 rec_r34_vd_tps_bilstm_attn
> 将下载的模型转换成inference模型，可是没有出来检测和识别结果，请问这个是怎么回事呢？

提供下转换的命令，你测试的图像是英文图像吗？

**Comment by wjy3326** [comment]
嗯，我的转换命令是：python tools/export_model.py -c configs/det/det_r50_vd_east.yml -o Global.checkpoints="./models/det_r50_vd_east/best_accuracy" Global.save_inference_dir="./inference/det_r50_vd_east" -o Global.use_gpu=False


python tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml -o Global.checkpoints="./models/rec_r34_vd_tps_bilstm_attn/best_accuracy" Global.save_inference_dir="./inference/rec_r34_vd_tps_bilstm_attn" -o Global.use_gpu=False
检测的是中文的文本，请问这些模型都是训练的英文？但是连检测框都没检测出来呀，这跟语言有这么大的关系吗？


然后还想问下哈，我用的超轻量中文模型的检测模型，然后用的rec_r34_vd_tps_bilstm_attn的识别模型，主要想试一下attention模型的识别效果，但是还是出现了错误，我运行的命令是：python tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_det_mv3_db/"&nbsp; --rec_model_dir="./inference/rec_r34_vd_tps_bilstm_attn/" --rec_algorithm="RARE"
错误好像是shape不匹配，具体您看下附件的图片，请问这个我要怎么修改呢？如果想测试这个识别模型的效果，需要重新训练中文的识别模型吗？那模型代码需要做修改吗？谢谢哈！


然后还想问您，您训练中文识别模型是用的中文街景数据集还有中文文档数据集吗？两个都用了吗？谢谢哈！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Double_V"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 中午12:24
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果 (#269)





  
运用你们提供的预训练模型 EAST det_r50_vd_east ，和识别模型 rec_r34_vd_tps_bilstm_attn
 将下载的模型转换成inference模型，可是没有出来检测和识别结果，请问这个是怎么回事呢？
  
提供下转换的命令，你测试的图像是英文图像吗？

**Comment by LDOUBLEV** [comment]
我运行了一遍doc_ch/inferencg.md里的命令，检测结果正常；
![image](https://user-images.githubusercontent.com/26592129/85939193-0a4eb100-b946-11ea-8ed1-8752e843bc6b.png)

如果检测的模型是在英文数据上训练的，对中文文本检测效果不会太好，反之同理；

训练中文识别模型的数据中没有用中文文档数据集，有街景数据。

**Comment by tink2123** [comment]
>错误好像是shape不匹配，具体您看下附件的图片，请问这个我要怎么修改呢？如果想测试这个识别模型的效果，需要重新训练中文的识别模型吗？那模型代码需要做修改吗？谢谢哈！

带tps的模型请参考Readme 修改输入图片shape，具体可看这个 #248 ，想测试中文效果的话需要重新训练，参数修改与ic15类似，可以阅读：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/recognition.md

**Comment by wjy3326** [comment]
嗯嗯，谢谢，我又用英文图片测试了一下模型，运行命令：python tools/infer/predict_system.py --image_dir="./doc/imgs_en/" --det_model_dir="./inference/det_r50_vd_east/"&nbsp; --rec_model_dir="./inference/rec_r34_vd_tps_bilstm_attn/" --det_algorithm="EAST" --rec_algorithm="RARE" 就是还是没有出来结果，检测网络没有检测出检测框，但是也没有报错，我测试了一下，进入检测模型之前，图片是正常的，有数据，但是检测模型好像不太正常，结果显示就是下面这样，请问是不是我忽略了一些配置呢？为什么没有结果呢？谢谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 下午2:08
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果 (#269)





  
错误好像是shape不匹配，具体您看下附件的图片，请问这个我要怎么修改呢？如果想测试这个识别模型的效果，需要重新训练中文的识别模型吗？那模型代码需要做修改吗？谢谢哈！
  
带tps的模型请参考Readme 修改输入图片shape，具体可看这个 #248 ，想测试中文效果的话需要重新训练，参数修改与ic15类似，可以阅读：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/recognition.md

**Comment by LDOUBLEV** [comment]
没有收到你的图像结果，你先跑一下下面的命令，看是否能正确检测，检测可视化的结果在tools同目录的inference_results文件夹下，没有这个文件夹就手动创建一个
```
python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST"
```

**Comment by wjy3326** [comment]
嗯嗯，我跑了一下，修改了模型，使用了det_r50_vd_east，没有检测出文字，inference_results里的图片与原图一样，没有框出文本框呀，请问这是怎么回事呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Double_V"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 下午3:29
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果 (#269)





 
没有收到你的图像结果，你先跑一下下面的命令，看是否能正确检测，检测可视化的结果在tools同目录的inference_results文件夹下，没有这个文件夹就手动创建一个
 python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST"

**Comment by LDOUBLEV** [comment]
> 嗯嗯，我跑了一下，修改了模型，使用了det_r50_vd_east，没有检测出文字，inference_results里的图片与原图一样，没有框出文本框呀，请问这是怎么回事呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Double_V"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月28日(星期天) 下午3:29 收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;; 抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果 (#269) 没有收到你的图像结果，你先跑一下下面的命令，看是否能正确检测，检测可视化的结果在tools同目录的inference_results文件夹下，没有这个文件夹就手动创建一个 python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST" — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

那不太对，你重新生成inference模型，再试一下，按照文档里的步骤走是没问题的：
```
python3 tools/export_model.py -c configs/det/det_r50_vd_east.yml -o Global.checkpoints="./models/det_r50_vd_east/best_accuracy" Global.save_inference_dir="./inference/det_east"

python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST"
```

**Comment by Luffffffy** [comment]
> > 嗯嗯，我跑了一下，修改了模型，使用了det_r50_vd_east，没有检测出文字，inference_results里的图片与原图一样，没有框出文本框呀，请问这是怎么回事呢？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Double_V"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年6月28日(星期天) 下午3:29 收件人: "PaddlePaddle/PaddleOCR"<[PaddleOCR@noreply.github.com](mailto:PaddleOCR@noreply.github.com)>; 抄送: "王俊艳"<[1079158605@qq.com](mailto:1079158605@qq.com)>;"State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题: Re: [PaddlePaddle/PaddleOCR] 运用预训练的east模型和RARE模型进行预测，没有出来检测和识别结果 (#269) 没有收到你的图像结果，你先跑一下下面的命令，看是否能正确检测，检测可视化的结果在tools同目录的inference_results文件夹下，没有这个文件夹就手动创建一个 python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST" — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 那不太对，你重新生成inference模型，再试一下，按照文档里的步骤走是没问题的，我试了一下可以得到正常的检测结果：
> 
> ```
> python3 tools/export_model.py -c configs/det/det_r50_vd_east.yml -o Global.checkpoints="./models/det_r50_vd_east/best_accuracy" Global.save_inference_dir="./inference/det_east"
> 
> python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/" --det_algorithm="EAST"
> ```

你不能说你的没问题，然后就把这个问题给关闭了呀？
