### ISSUE TITLE
请问有中文繁体的数据集吗，或者中文简体和繁体一体的模型

### ISSUE THREAD

**Issue by wangshihuang** [PaddlePaddle/PaddleOCR#2693]

**Comment by LDOUBLEV** [comment]
目前PaddleOCR release的中文模型支持繁体识别，暂无中文繁体数据，可自行生成一些数据

**Comment by wangshihuang** [comment]
> 目前PaddleOCR release的中文模型支持繁体识别，暂无中文繁体数据，可自行生成一些数据

是中英文通用OCR模型吗，这个只能中文简体，繁体识别不正确，我想要简体和繁体都可以识别的模型

**Comment by yxliii** [comment]
楼主找到数据集了嘛
