### ISSUE TITLE
使用 AIStudio  转化的DB ONNX模型，无法转化成tensorrt

### ISSUE THREAD

**Issue by lx-rookie** [PaddlePaddle/PaddleOCR#2695]
这边使用固化的ONNX文件，进行转化tensorrt是，出现如下不支持错误，请问我该怎么修改。
In node -1 (importResize): UNSUPPORTED_NODE: Assertion failed: (mode != "nearest" || nearest_mode == "floor") && "This version of TensorRT only supports floor nearest_mode!"

就是paddle—DB中文检测模型 使用了tensorrt不支持的层。这该如何修改

**Comment by LDOUBLEV** [comment]
暂时无计划适配tensorRT 部署，目前PaddleOCR也支持TRT预测，可尝试使用
