### ISSUE TITLE
关于DB检测网络训练的图像输入尺寸问题

### ISSUE THREAD

**Issue by JaneBai** [PaddlePaddle/PaddleOCR#2696]
DB检测模型的图像输入尺寸为640*640，我在用预训练模型finetune的时候，假设我训练的样本图像尺寸都远低于640，比如都是250*200的，那么训练时这个输入尺寸是否可以改小？是否需要保持和实际图像尺寸相同的比例？（比如设置为256*192，32的倍数）？
@LDOUBLEV @littletomatodonkey

**Comment by LDOUBLEV** [comment]
> 250200的，那么训练时这个输入尺寸是否可以改小？是否需要保持和实际图像尺寸相同的比例？（比如设置为256*192，32的倍数）

可以的，保证是32的倍数就可以
