### ISSUE TITLE
带有干扰文字的印章OCR识别问题

### ISSUE THREAD

**Issue by Eric-Zhang1990** [PaddlePaddle/PaddleOCR#2698]
请问对于有干扰文字的印章如何进行OCR识别呢？ 是不是先去除干扰文字（比如日期等），将印章提取处理再进行后续处理，如果这样做，那有什么好的方法把印章提取出来呢？ （如下图，除了用颜色空间提取外，因为有灰色印章）
![tmp](https://user-images.githubusercontent.com/24602893/116653007-ed956680-a9b8-11eb-8f78-6a3b6a2e5b0e.png)

**Comment by Mafengqiang** [comment]
> 请问对于有干扰文字的印章如何进行OCR识别呢？ 是不是先去除干扰文字（比如日期等），将印章提取处理再进行后续处理，如果这样做，那有什么好的方法把印章提取出来呢？ （如下图，除了用颜色空间提取外，因为有灰色印章）
> ![tmp](https://user-images.githubusercontent.com/24602893/116653007-ed956680-a9b8-11eb-8f78-6a3b6a2e5b0e.png)
可以直接加这这种干扰背景的样本进行训练吧，你这个印章生成的脚本是自己写的吗，有开源的工程吗

**Comment by Eric-Zhang1990** [comment]
@Mafengqiang  印章是github一个开源的java项目生成的，字体模糊和灰色背景是我自己处理的，干扰日期也是自己加的。
 你说的直接加干扰背景的样本训练，是直接识别带有干扰背景的吗？比如上图，直接送给模型进行识别吗？我觉得重叠的部分太多，直接识别是不是效果不好，是不是先去除干扰再识别会好些呢？

**Comment by Eric-Zhang1990** [comment]
@dyning  @WenmuZhou  @LDOUBLEV @MissPenguin @grasswolfs @tink2123 @littletomatodonkey @JetHong @weisy11 @Evezerest @changrq @TingquanGao   各位，请问paddleocr是直接训练和识别带有干扰背景的文字吗？比如上图重叠的日期和“人力资源部”。期待回复，谢谢！

**Comment by Mafengqiang** [comment]
> @Mafengqiang 印章是github一个开源的java项目生成的，字体模糊和灰色背景是我自己处理的，干扰日期也是自己加的。
> 你说的直接加干扰背景的样本训练，是直接识别带有干扰背景的吗？比如上图，直接送给模型进行识别吗？我觉得重叠的部分太多，直接识别是不是效果不好，是不是先去除干扰再识别会好些呢？

你是用哪个模型训练啊，是检测和识别分开吗，还是直接端到端，你这个带干扰的有点假，正常应该是印章压在背景文字上，你这个是干扰文字盖住印章了

**Comment by Eric-Zhang1990** [comment]
> > @Mafengqiang 印章是github一个开源的java项目生成的，字体模糊和灰色背景是我自己处理的，干扰日期也是自己加的。
> > 你说的直接加干扰背景的样本训练，是直接识别带有干扰背景的吗？比如上图，直接送给模型进行识别吗？我觉得重叠的部分太多，直接识别是不是效果不好，是不是先去除干扰再识别会好些呢？
> 
> 你是用哪个模型训练啊，是检测和识别分开吗，还是直接端到端，你这个带干扰的有点假，正常应该是印章压在背景文字上，你这个是干扰文字盖住印章了

@Mafengqiang  这个是我生成的图片，干扰是叠加上去的，这个是用作说明的，如果就是这种较强的干扰，能有什么方法进行识别呢？ 是端到端呢？ 还是先用算法去除干扰文字，再进行后续识别呢？

**Comment by kylewangt** [comment]
> > > @Mafengqiang 印章是github一个开源的java项目生成的，字体模糊和灰色背景是我自己处理的，干扰日期也是自己加的。
> > > 你说的直接加干扰背景的样本训练，是直接识别带有干扰背景的吗？比如上图，直接送给模型进行识别吗？我觉得重叠的部分太多，直接识别是不是效果不好，是不是先去除干扰再识别会好些呢？
> > 
> > 
> > 你是用哪个模型训练啊，是检测和识别分开吗，还是直接端到端，你这个带干扰的有点假，正常应该是印章压在背景文字上，你这个是干扰文字盖住印章了
> 
> @Mafengqiang 这个是我生成的图片，干扰是叠加上去的，这个是用作说明的，如果就是这种较强的干扰，能有什么方法进行识别呢？ 是端到端呢？ 还是先用算法去除干扰文字，再进行后续识别呢？

这个训练数据量得多少呢？
