### ISSUE TITLE
jetson nano部署ocr+hub 运行GPU模式卡死

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#2699]
jetson nano部署paddleocr和paddlehub后，CPU模式运行正常，但是GPU模式运行hub后会出现卡死现象，初步确定卡死位置在：
predict_det.py中的#line98 

>  self.predictor, self.input_tensor, self.output_tensors = utility.create_predictor(
>             args, 'det', logger)  # paddle.jit.load(args.det_model_dir)

————————————————————————————————————————————————————————

求教有没有解决办法？

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/tools/infer/utility.py#L36这个参数设置小一些试试

**Comment by blackhitomi** [comment]
> [https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/tools/infer/utility.py#L36这个参数设置小一些试试](https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/tools/infer/utility.py#L36%E8%BF%99%E4%B8%AA%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE%E5%B0%8F%E4%B8%80%E4%BA%9B%E8%AF%95%E8%AF%95)

谢谢，这个参数设置试过了，8000会报错，500会卡死不动

**Comment by blackhitomi** [comment]
> [https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/tools/infer/utility.py#L36这个参数设置小一些试试](https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/tools/infer/utility.py#L36%E8%BF%99%E4%B8%AA%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE%E5%B0%8F%E4%B8%80%E4%BA%9B%E8%AF%95%E8%AF%95)

这个问题直接运行predict_system.py不会出现，只会在部署hubserving后启动serving的时候出现
