### ISSUE TITLE
训练模型和inference模型预测结果相差比较大

### ISSUE THREAD

**Issue by Simon-liusheng** [PaddlePaddle/PaddleOCR#270]
训练的识别模型crnn+mv3+ctc，数据集是一些车牌的数据集，训练的文字dict也已经配置好，转换inference模型是，config文件是训练时候的config，执行预测时候，训练的best accuracy模型，预测结果全部正确，转换inference模型后，预测结果是英文部分是正确的，但是车牌前面的省份大部分有错误。测试了windows和百度aistudio平台，结果都是有错误。

1. 训练好的模型预测代码
`python3 tools/infer_rec.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints=output/rec_CRNN/best_accuracy Global.infer_img=test_img`

2.inference模型预测代码
‘python3 tools/infer/predict_rec.py --image_dir="test_img" --rec_model_dir="inference/rec_crnn" --rec_image_shape="3, 32, 100" --rec_char_type="ch" --rec_char_dict_path="ppocr/utils/plate_dict.txt"’
3.测试图片和配置文件，结果截图如下
![inference预测](https://user-images.githubusercontent.com/53001871/85967813-e9de2f80-b9f5-11ea-92ac-bbb09fbd5a51.jpg)
![训练预测](https://user-images.githubusercontent.com/53001871/85967816-eb0f5c80-b9f5-11ea-88cb-14543b637d76.jpg)

![1](https://user-images.githubusercontent.com/53001871/85967621-7d633080-b9f5-11ea-922c-8c2a6f7c8397.jpg)
![2](https://user-images.githubusercontent.com/53001871/85967624-7e945d80-b9f5-11ea-8201-2781b153b069.jpg)
![3](https://user-images.githubusercontent.com/53001871/85967625-7f2cf400-b9f5-11ea-927b-561fc2ee4852.jpg)
![4](https://user-images.githubusercontent.com/53001871/85967626-7fc58a80-b9f5-11ea-9a7a-7cfb034a7cab.jpg)
![5](https://user-images.githubusercontent.com/53001871/85967627-805e2100-b9f5-11ea-888a-bda1277fcf3f.jpg)
![6](https://user-images.githubusercontent.com/53001871/85967628-805e2100-b9f5-11ea-8a85-b363fa59425e.jpg)
![7](https://user-images.githubusercontent.com/53001871/85967629-80f6b780-b9f5-11ea-84d6-6b1687910ab0.jpg)
![8](https://user-images.githubusercontent.com/53001871/85967631-818f4e00-b9f5-11ea-80e4-5a804f8e57a0.jpg)
![9](https://user-images.githubusercontent.com/53001871/85967632-8227e480-b9f5-11ea-98fb-42e732cc66ad.jpg)
![10](https://user-images.githubusercontent.com/53001871/85967634-82c07b00-b9f5-11ea-8116-c3080cd76504.jpg)
![11](https://user-images.githubusercontent.com/53001871/85967635-83591180-b9f5-11ea-93e0-05f75d7a798c.jpg)
![12](https://user-images.githubusercontent.com/53001871/85967637-83f1a800-b9f5-11ea-9021-9cc75dbcb4b4.jpg)
![13](https://user-images.githubusercontent.com/53001871/85967638-848a3e80-b9f5-11ea-91aa-5771b0d0d731.jpg)
![14](https://user-images.githubusercontent.com/53001871/85967639-848a3e80-b9f5-11ea-80b7-81d4435a1b8a.jpg)
![15](https://user-images.githubusercontent.com/53001871/85967640-85bb6b80-b9f5-11ea-9902-472ecddb5d66.jpg)
![16](https://user-images.githubusercontent.com/53001871/85967645-85bb6b80-b9f5-11ea-83c5-fc9c7e78c90e.jpg)
![17](https://user-images.githubusercontent.com/53001871/85967646-86540200-b9f5-11ea-9bdb-8a852b6eca89.jpg)
![18](https://user-images.githubusercontent.com/53001871/85967649-86ec9880-b9f5-11ea-88e7-6a03cf17cea5.jpg)
![19](https://user-images.githubusercontent.com/53001871/85967650-87852f00-b9f5-11ea-8cbe-a8c567a4fd4a.jpg)
![20](https://user-images.githubusercontent.com/53001871/85967653-881dc580-b9f5-11ea-9b57-41cf5ef522ad.jpg)
[plate_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/4843473/plate_dict.txt)

**Comment by Simon-liusheng** [comment]
请求大佬这个是啥原因，难道还要用转换后的模型继续训练吗？

**Comment by tink2123** [comment]
识别模型使用 predict_rec.py 时，默认在 rec_char_type= "ch" 模式下根据图片长宽比resize，你指定的shape可能没有生效，可以试着注释掉这两行，看下结果会不会一致：
https://github.com/PaddlePaddle/PaddleOCR/blob/ed4313d611b7708a7763d4612f00cb7f318a0e1f/tools/infer/predict_rec.py#L54-L55

这个issue与您的问题类似，可以参考一下 #214

**Comment by Simon-liusheng** [comment]
@tink2123 非常感谢，试了一下，问题已经解决。

**Comment by tink2123** [comment]
不客气～
