### ISSUE TITLE
windows gpu 推理崩溃

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#2700]
![图片](https://user-images.githubusercontent.com/40679769/116654321-79a88d80-a9bb-11eb-9d12-3da33064b585.png)

环境：
windows10 + vs2019 x64
cuda11.0  cuda_11.0.2_451.48_win10 TensorRT-7.2.2.3
cuda11.0_cudnn8_avx_mkl_trt7

最新版本，C++，检测推理的时候，input_t->CopyFromCpu(input.data())崩溃

**Comment by sml2h3** [comment]
我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
下载一个everything软件，然后搜索msvcp140.dll，按大小排序，把最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
> 下载一个everything软件，然后搜索msvcp140.dll，按大小排序，用最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用

您替换到的那个msvcp140.dll多大？

**Comment by sml2h3** [comment]
> > 我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
> > 下载一个everything软件，然后搜索msvcp140.dll，按大小排序，用最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用
> 
> 您替换到的那个msvcp140.dll多大？

960kb

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > 我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
> > > 下载一个everything软件，然后搜索msvcp140.dll，按大小排序，用最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用
> > 
> > 
> > 您替换到的那个msvcp140.dll多大？
> 
> 960kb

![图片](https://user-images.githubusercontent.com/40679769/117228323-65491280-ae4b-11eb-92a4-09bb438e621f.png)
我替换完后，就这样了。可否把您的这个文件，给我发一个呢，不胜感激。邮箱：lllstandout@163.com

**Comment by sml2h3** [comment]
> > > > 我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
> > > > 下载一个everything软件，然后搜索msvcp140.dll，按大小排序，用最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用
> > > 
> > > 
> > > 您替换到的那个msvcp140.dll多大？
> > 
> > 
> > 960kb
> 
> ![图片](https://user-images.githubusercontent.com/40679769/117228323-65491280-ae4b-11eb-92a4-09bb438e621f.png)
> 我替换完后，就这样了。可否把您的这个文件，给我发一个呢，不胜感激。邮箱：[lllstandout@163.com](mailto:lllstandout@163.com)

好的，晚上回去发给你

**Comment by sml2h3** [comment]
> > > > 我和你的情况一样的，找到个最靠谱的解决方法，不用改代码。
> > > > 下载一个everything软件，然后搜索msvcp140.dll，按大小排序，用最大的那个msvcp140.dll替换掉C:\Windows\System32中的msvcp140.dll再启动项目就可以了，亲测可用
> > > 
> > > 
> > > 您替换到的那个msvcp140.dll多大？
> > 
> > 
> > 960kb
> 
> ![图片](https://user-images.githubusercontent.com/40679769/117228323-65491280-ae4b-11eb-92a4-09bb438e621f.png)
> 我替换完后，就这样了。可否把您的这个文件，给我发一个呢，不胜感激。邮箱：[lllstandout@163.com](mailto:lllstandout@163.com)

链接：https://pan.baidu.com/s/1HO6BZ82MVDrbxIyDY4gFvw 
提取码：ynpd 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V5的分享

**Comment by xinsuinizhuan** [comment]
![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
崩溃，崩溃，着急。

**Comment by sml2h3** [comment]
> ![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
> 崩溃，崩溃，着急。

这个我没遇到了，我换了那个dll就好了，你可以把你电脑里面比原来system32里面那个dll大的dll文件都给替换进去试试。我指的是把别的地方的dll文件复制替换掉system32里面的dll，被替换的是system32里面的dll

**Comment by xinsuinizhuan** [comment]
> 
> 
> > ![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
> > 崩溃，崩溃，着急。
> 
> 这个我没遇到了，我换了那个dll就好了，你可以把你电脑里面比原来system32里面那个dll大的dll文件都给替换进去试试。我指的是把别的地方的dll文件复制替换掉system32里面的dll，被替换的是system32里面的dll

我替换过，替换后，就直接是0x0000007崩溃了。

**Comment by xinsuinizhuan** [comment]
> 
> 
> > ![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
> > 崩溃，崩溃，着急。
> 
> 这个我没遇到了，我换了那个dll就好了，你可以把你电脑里面比原来system32里面那个dll大的dll文件都给替换进去试试。我指的是把别的地方的dll文件复制替换掉system32里面的dll，被替换的是system32里面的dll

奇怪的是，我自己电脑现在不知道怎么回事好了，但是放到另外一台同样环境，还是不行，我替换了所有可能的这个库，依然不行。

**Comment by sml2h3** [comment]
> > > ![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
> > > 崩溃，崩溃，着急。
> > 
> > 
> > 这个我没遇到了，我换了那个dll就好了，你可以把你电脑里面比原来system32里面那个dll大的dll文件都给替换进去试试。我指的是把别的地方的dll文件复制替换掉system32里面的dll，被替换的是system32里面的dll
> 
> 奇怪的是，我自己电脑现在不知道怎么回事好了，但是放到另外一台同样环境，还是不行，我替换了所有可能的这个库，依然不行。

你是win10么？我是华硕的主板，我拷贝的我华硕的ai suit套件里面的msvcp140.dll

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > > ![1620813016(1)](https://user-images.githubusercontent.com/40679769/117955417-9b562d00-b34a-11eb-9a25-4a7d96cb6746.jpg)
> > > > 崩溃，崩溃，着急。
> > > 
> > > 
> > > 这个我没遇到了，我换了那个dll就好了，你可以把你电脑里面比原来system32里面那个dll大的dll文件都给替换进去试试。我指的是把别的地方的dll文件复制替换掉system32里面的dll，被替换的是system32里面的dll
> > 
> > 
> > 奇怪的是，我自己电脑现在不知道怎么回事好了，但是放到另外一台同样环境，还是不行，我替换了所有可能的这个库，依然不行。
> 
> 你是win10么？我是华硕的主板，我拷贝的我华硕的ai suit套件里面的msvcp140.dll

是的。win10。我觉得应该是某个地方设置的问题，它报错的意思，应该是要分配内存出错。

**Comment by luodaoyi** [comment]
我估计是你的显存不够
