### ISSUE TITLE
PaddleOCR2.1文字检测没有输出模型

### ISSUE THREAD

**Issue by 370019421** [PaddlePaddle/PaddleOCR#2701]
按文档执行python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/，没有输出模型请问是什么原因

值输出了config.yml和train.log两个文件

**Comment by LDOUBLEV** [comment]
检查下参数设置：
https://github.com/PaddlePaddle/PaddleOCR/blob/ac2e0da2dd898b6767037b9206974ee84a736bd5/configs/det/det_mv3_db.yml#L7

**Comment by 370019421** [comment]
这两个参数也都设置了[10,10]和3还是没有效果

**Comment by 370019421** [comment]
就执行到最后一张图的最后一段就完事了

**Comment by 370019421** [comment]
忘了说了是windows10环境
