### ISSUE TITLE
paddle 如何进行多进程并行推理？

### ISSUE THREAD

**Issue by liyandongpy** [PaddlePaddle/PaddleOCR#2703]
paddle [怎么进行并行推理，我多进程调用两个paddle模型进行推理，会出现底层代码报错。

- 
![微信图片_20210430230650](https://user-images.githubusercontent.com/49861986/116715003-e433ea80-aa08-11eb-83b5-c2f1997d7564.png)

**Comment by littletomatodonkey** [comment]
可以参考这里 

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md#%E4%BA%94%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E5%92%8C%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E4%B8%B2%E8%81%94%E6%8E%A8%E7%90%86

**Comment by liyandongpy** [comment]
> 可以参考这里
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md#%E4%BA%94%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E5%92%8C%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E4%B8%B2%E8%81%94%E6%8E%A8%E7%90%86

这个确实可以实现，但是怎么在服务端部署呢？有其他的解决方法吗？
