### ISSUE TITLE
README.rst'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2707]
python setup.py install

Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    with open('README.rst') as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

**Comment by littletomatodonkey** [comment]
It seems that your file is not right, cause  the line `with open(README.rst) as readme_file:` does not exist in the file `setup.py`
