### ISSUE TITLE
No module named 'sip'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2708]
python PPOCRLabel.py --lang ch

/home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/scikit_image-0.17.2-py3.7-linux-x86_64.egg/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/scikit_image-0.17.2-py3.7-linux-x86_64.egg/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Traceback (most recent call last):
  File "PPOCRLabel.py", line 38, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/PyQt5-5.15.4-py3.7-linux-x86_64.egg/PyQt5/QtCore.abi3.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PPOCRLabel.py", line 48, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by littletomatodonkey** [comment]
从这个文件里看出，应该是你的Qt so有问题，导致走了下面的分支，

https://github.com/PaddlePaddle/PaddleOCR/blob/394ad5a29953a37045eab82538ea480622466b8c/PPOCRLabel/PPOCRLabel.py#L48

可以先试下`pip install sip`看下
