### ISSUE TITLE
C++ Traceback

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2709]
python PPOCRLabel.py --lang ch

QLibraryPrivate::loadPlugin failed on "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library 

/home/hello/anaconda3/envs/PaddleOCR/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-util.so.1: 无法打开共享对象文件: 没有那个文件或目录)"

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1620044673 (unix time) try "date -d @1620044673" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000043cc) received by PID 17356 (TID 0x7f3111a90740) from PID 17356 ***]

已放弃

**Comment by xxxpsyduck** [comment]
Did you run this in docker?

**Comment by littletomatodonkey** [comment]
看着是pyqt的so导入的bug，可以先排查下PyQT是否正常

**Comment by zjl123123zjl** [comment]
请问这个问题有人解决了吗，可以提供一下解决思路吗
