### ISSUE TITLE
训练自己数据集时没有loss的log信息打印出来

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/PaddleOCR#271]
![image](https://user-images.githubusercontent.com/18586273/85975991-0edd9d00-ba0c-11ea-8e7c-cafb900bb7ef.png)

**Comment by tink2123** [comment]
这种情况应该是数据读取有误，可以更新一下代码，根据打印出的报错信息修改数据读取路径。或者参考 #115 手动添加报错信息。

**Comment by Ezra-Yu** [comment]
应该不是那个问题，没有执行到那一步
![image](https://user-images.githubusercontent.com/18586273/85978678-c7f2a600-ba11-11ea-8883-07495338b9d8.png)

**Comment by tink2123** [comment]
是因为没有读取到数据啊，所以网络没有开始计算结果。先更新一下代码试试吧～

**Comment by Ezra-Yu** [comment]
你们代码try,except异常记录下log吧，不然还要回头看代码

**Comment by LDOUBLEV** [comment]
> 你们代码try,except异常记录下log吧，不然还要回头看代码

我们后续考虑优化下reader部分的代码，增加报错信息等。目前看上去你的问题还是数据读取的问题，建议先调试下数据读取器是否能正常加载数据。

**Comment by Ezra-Yu** [comment]
有点看不懂这个报错：
![image](https://user-images.githubusercontent.com/18586273/85981509-e0b18a80-ba16-11ea-884c-3333cc012007.png)
真麻烦你们了，想先跑通代码，再慢慢了解细节

**Comment by Ezra-Yu** [comment]
然后是这样的，我是真看不懂
![image](https://user-images.githubusercontent.com/18586273/85981890-81a04580-ba17-11ea-9795-498dfcf198d8.png)

**Comment by LDOUBLEV** [comment]
你的split/train.txt 里面的数据格式是什么样的？是否符合icdar15的数据格式？

另外，你的配置文件好像有问题，你是想训练backbone为MV3_large的DB模型？训练DB模型需要用DB的后处理和预处理，看你的reader里选用的是EAST的处理函数；
![image](https://user-images.githubusercontent.com/26592129/85984091-3a1bb880-ba1b-11ea-902f-f00c3e9465bf.png)

**Comment by Ezra-Yu** [comment]
太感谢了，解决这个问题！麻烦你们了！！

**Comment by Ezra-Yu** [comment]
问题解决了，太感谢你们了！反馈真的快！
