### ISSUE TITLE
PGNet的ctcloss计算模块出错

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#2712]
![Y@DDL$CANZS$~BO6(XRAM~4](https://user-images.githubusercontent.com/33149964/116997703-b9e77300-ad0f-11eb-80ad-448f806692cd.png)
修改配置文件为中文的时候，使用中文字符集，pad_num设置为中文字符集长度6623后报错，说的是pad_num必须<37，但是中文字符集不是英文字符集10数字+26字母==36，而是更多的字符，请问应该如何解决这个错误呢？

**Comment by born-to-love** [comment]
可能是 e2e_pg_loss.py 的第 94 行和第 97 行也需要修改。
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/ppocr/losses/e2e_pg_loss.py#L94-L97

**Comment by chujian521** [comment]
但是我之前已经尝试过修改93、94和97，还是会报错，报错信息是
![image](https://user-images.githubusercontent.com/33149964/117126328-32603980-adcd-11eb-8030-78be7b4bdea3.png)

**Comment by chujian521** [comment]
我之前已经尝试过修改这个文件的93、94和97行的代码，但是会出现如下错误
![image](https://user-images.githubusercontent.com/33149964/117126488-676c8c00-adcd-11eb-9949-d93e82c44a06.png)
请问还有别的位置定义这个tensor的大小为37吗

**Comment by dijkexo** [comment]
参考 FAQ 改改试试。
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q3160-pgnet%E6%9C%89%E4%B8%AD%E6%96%87%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%90%97

**Comment by chujian521** [comment]
啊，没看到FAQ更新了，谢谢您！网络那部分忘记修改的原因
