### ISSUE TITLE
Got error: "Segmentation fault"

### ISSUE THREAD

**Issue by Mary63** [PaddlePaddle/PaddleOCR#2715]
I installed the docker container and then the paddlepaddle for my GPU machine with CUDA 10.0 on linux. 

I verified that the paddle is working by importing it into python. I used import paddle and then paddle.utils.run_check() and it is working. 

Then I got the inference directory by this: 
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/pgnet/e2e_server_pgnetA_infer.tar
 
and then followed every step and ran this:

python tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="./doc/imgs_en/img623.jpg" --e2e_model_dir="./inference/e2e_server_pgnetA_infer/" --e2e_pgnet_polygon=True

But I get this error:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1620154290 (unix time) try "date -d @1620154290" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1958 (TID 0x7f179ffe6700) from PID 0 ***]

Segmentation fault

Could you please tell me how to fix it? (I cannot read Chinese, so I could not follow other issues here related to this error)

**Comment by littletomatodonkey** [comment]
可以先用下面的命令看下paddle是否安装成功

```
import paddle
paddle.utils.run_check()
```

**Comment by Mary63** [comment]
Yes, I used the same code and checked if paddle is installed. I receive the message saying it is installed successfully.


Is there anything else that I should check? Can you please  answer in English?

**Comment by cnjack** [comment]
I got same issue in colab, may be its course by cuda version and cudnn version

**Comment by Yulv-git** [comment]
我也遇到了该问题。我的情况和解决方法如下：
1. 查看issues后发现，可能是cudnn版本的问题，然后使用以下命令查看发现我用的服务器没有安装cudn
`cat /usr/local/cuda-10.2/include/cudnn.h | grep CUDNN_MAJOR -A 2`
2. 下载安装与cuda10.2版本对应的cudnn7.6.5。安装成功后，再次运行该项目就不会出现Segmentation fault了
