### ISSUE TITLE
通用模型在自己数据集上finetune后原来已有的中英文识别效果变差

### ISSUE THREAD

**Issue by LiangYongAI** [PaddlePaddle/PaddleOCR#2717]
用百度提供的通用模型做数字的OCR识别，发现小数点识别很多情况下会漏掉，于是自己找了一些带小数点的数据finetune了一下识别模型，对小数点的识别效果好些了，但原本识别效果较好的中文和英文的识别效果却不好了，于是想问如下几个问题：
1、在自己数据集上finetune一般做多少epoch，我训练了200个epoch，并且观察到训练时打印的Log的acc(应该是在训练集上的精度 )到90%多才停止。
2、如果finetune影响了原来的识别效果，我想到把我自己制作的加强数据和原有的数据集一起训练，我在https://ai.baidu.com/broad/download?dataset=lsvt链接里找到了百度提供数据集，以这个数据集为例
![image](https://user-images.githubusercontent.com/15886620/117249601-70fcff00-ae74-11eb-94b5-a0b5898cac9a.png)
里面提供的标注文件是一个Json文件，格式也并不是PPOCRLabel生成的数据集格式，我要自己做个脚本来根据json文件里面的框再去原图上把小图抠出来再做成识别的数据集？有没有现成的脚本？百度是怎么做的？

**Comment by littletomatodonkey** [comment]
1. finetune 一般200差不多了，看数据量，有10W的话，一般200差不多了
2. 可以参考下面的函数进行裁剪

https://github.com/PaddlePaddle/PaddleOCR/blob/394ad5a29953a37045eab82538ea480622466b8c/tools/infer/predict_system.py#L49
