### ISSUE TITLE
ModuleNotFoundError: No module named 'paddlehub.common'

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2718]
运行2.1时，python deploy/hubserving/ocr_system/module.py报错No module named 'paddlehub.common'
环境：windows10，cpu，paddlehub=2.0.0，paddlepaddle=2.0.2

**Comment by littletomatodonkey** [comment]
paddlehub试下2.0.4呢？我这边import是正常的

**Comment by Lie-huo** [comment]
> paddlehub试下2.0.4呢？我这边import是正常的

先import paddlehub 再 from paddlehub.common.logger import logger 不报错，但是直接from paddlehub.common.logger import logger就报错
![image](https://user-images.githubusercontent.com/13652569/117416723-3feffd80-af4c-11eb-857b-b68042450b59.png)

![Uploading image.png…]()

**Comment by wa3926** [comment]
@Lie-huo 请问一下你是怎么解决的 我也遇到和你一个问题了  折磨一天了

**Comment by Lie-huo** [comment]
> @Lie-huo 请问一下你是怎么解决的 我也遇到和你一个问题了 折磨一天了

这个问题我也没有解决，后来是直接在linux下运行的，你的解决了吗？

**Comment by wa3926** [comment]
不行  module.py一直运行不成功   我只能hub install 部署成功之后 本地调用   耽误很多时间  勉强能用

**Comment by Lie-huo** [comment]
> 不行 module.py一直运行不成功 我只能hub install 部署成功之后 本地调用 耽误很多时间 勉强能用

额，一样的

**Comment by MissPenguin** [comment]
安装paddlehub==1.8.3试试，这个问题应该是paddlehub更新后导致不兼容了

**Comment by JiChen-gh** [comment]
可以改成from paddlehub import logger
