### ISSUE TITLE
求助！ 训练时报错

### ISSUE THREAD

**Issue by JWLe666** [PaddlePaddle/PaddleOCR#2721]
![image](https://user-images.githubusercontent.com/49588285/117272596-eb864880-ae8d-11eb-8db8-9eefb13a1561.png)
![image](https://user-images.githubusercontent.com/49588285/117272722-0f498e80-ae8e-11eb-8dae-1e06557219f1.png)

**Comment by littletomatodonkey** [comment]
yaml文件里面，如果希望为空，可以用null

`pretrained_model: null`

**Comment by JWLe666** [comment]
还是不行 是我的训练命令有问题吗 python -m paddle.distributed.launch --gpus 0  tools/train.py -c 1.yml

**Comment by JWLe666** [comment]
还是不行 是我的训练命令有问题吗 python -m paddle.distributed.launch --gpus 0  tools/train.py -c 1.yml

**Comment by JWLe666** [comment]
是Architecture 算法这里找不到 pdparams      CRNN我已经下载要放到哪里去

**Comment by JWLe666** [comment]
![image](https://user-images.githubusercontent.com/49588285/117416110-9f014280-af4b-11eb-9895-836bb13118de.png)
这样不会报错那个pdarams 但是还是不能训练
![image](https://user-images.githubusercontent.com/49588285/117416335-d66fef00-af4b-11eb-9219-8da10685dd1d.png)

**Comment by Lebron-Harden** [comment]
pretrained_model那里面什么也不写就行了
