### ISSUE TITLE
paddleOCR 在C++识别inference案例中有batchSize吗？

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#2722]
在windows， c++环境下，是否可以使用opencv一次性读入几张图片，然后一次性识别多张图片，而不是读取一张图片，识别一张图片。

**Comment by tink2123** [comment]
可以参考识别预测，修改一下C++代码：
https://github.com/PaddlePaddle/PaddleOCR/blob/394ad5a29953a37045eab82538ea480622466b8c/tools/infer/predict_rec.py#L266

**Comment by liudongminghaha** [comment]
> 可以参考识别预测，修改一下C++代码：
> https://github.com/PaddlePaddle/PaddleOCR/blob/394ad5a29953a37045eab82538ea480622466b8c/tools/infer/predict_rec.py#L266

开发者好，paddleOCR 文本检测算法 DB EAST SAST，文本识别算法 CRNN Rosetta(paper)  STAR-Net RARE SRN，包括PGNet端到端算法这些可以用C++部署吗？案例都是python的
