### ISSUE TITLE
着急请教，训练过程中断，不动了

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#2723]
ubuntu18.04 cuda10.2 2080的显卡，使用ch_det_mv3_db_v2.0.yml模型和
![图片](https://user-images.githubusercontent.com/40679769/117383358-35fdd880-af13-11eb-863e-7b0bfe391b13.png)

训练检测模型，1200次
第一次训练1200次，训练到700多的时候，停掉不往下走了
![微信图片_20210507090550](https://user-images.githubusercontent.com/40679769/117383557-a0af1400-af13-11eb-87d9-fa57e1d3c943.jpg)

第二次训练1200次，训练都930次的时候，又停掉不往下走了
![微信图片_202105070859051](https://user-images.githubusercontent.com/40679769/117383203-cd166080-af12-11eb-92ec-b300e50b5522.jpg)

请帮忙排查。

**Comment by xxxpsyduck** [comment]
I got the same error multiple times. For now, just stop and resume training from a checkpoint

**Comment by WenmuZhou** [comment]
在terminal里跑训练看看，不用pycharm启动

**Comment by YY007H** [comment]
我也是跑着跑着就不动了

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我也是跑着跑着就不动了

继续训练吧，没其他办法

**Comment by lxhmark7** [comment]
遇到同样的问题，每次都是在eval时暂停不同了
