### ISSUE TITLE
PPOCRLabel自动标注跑着跑着就自己闪退了

### ISSUE THREAD

**Issue by Aunixtoyou** [PaddlePaddle/PaddleOCR#2724]
开启GPU
显卡 RTX 2070 super
CUDA 10
开始跑着速度挺快的，然后越来越慢，最后卡一会儿就闪退了（任务管理器无资源占用）。选了大概9000多张图片。使用CPU跑一会儿也会卡，不过不会闪退

**Comment by littletomatodonkey** [comment]
隔一段时间释放下资源呢？这个之前没遇到过

**Comment by Evezerest** [comment]
Paddle版本、PaddleOCR版本以及系统环境是什么呢

**Comment by Aunixtoyou** [comment]
> Paddle版本、PaddleOCR版本以及系统环境是什么呢

paddle2onnx           0.5.1
paddlehub             2.1.0
paddlenlp             2.0.0rc20
paddlepaddle-gpu      2.0.2.post100

PaddleOCR 版本是git仓库最新

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130


处理器	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
机带 RAM	16.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入


版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎2/‎4
操作系统内部版本	19042.928
体验	Windows Feature Experience Pack 120.2212.551.0

**Comment by Aunixtoyou** [comment]
> 隔一段时间释放下资源呢？这个之前没遇到过

PaddleOCRLabel 内置似乎是开的多线程处理

**Comment by Aunixtoyou** [comment]
全部版本号

Package               Version
--------------------- -------------
appdirs               1.4.4
astor                 0.8.1
Babel                 2.9.1
bce-python-sdk        0.8.60
certifi               2020.12.5
cfgv                  3.2.0
chardet               4.0.0
click                 7.1.2
colorama              0.4.4
colorlog              5.0.1
cycler                0.10.0
decorator             4.4.2
dill                  0.3.3
distlib               0.3.1
easydict              1.9
filelock              3.0.12
flake8                3.9.1
Flask                 1.1.2
Flask-Babel           2.0.0
future                0.18.2
gast                  0.3.3
gitdb                 4.0.7
GitPython             3.1.15
h5py                  3.2.1
identify              2.2.4
idna                  2.10
imageio               2.9.0
imgaug                0.4.0
itsdangerous          1.1.0
jieba                 0.42.1
Jinja2                2.11.3
joblib                1.0.1
kiwisolver            1.3.1
lmdb                  1.2.1
MarkupSafe            1.1.1
matplotlib            3.4.1
mccabe                0.6.1
multiprocess          0.70.11.1
networkx              2.5.1
nodeenv               1.6.0
numpy                 1.19.3
opencv-contrib-python 4.2.0.32
opencv-python         4.5.1.48
packaging             20.9
paddle2onnx           0.5.1
paddlehub             2.1.0
paddlenlp             2.0.0rc20
paddlepaddle-gpu      2.0.2.post100
Pillow                8.2.0
pip                   21.1.1
pre-commit            2.12.1
protobuf              3.15.8
pyclipper             1.2.1
pycodestyle           2.7.0
pycryptodome          3.10.1
pyflakes              2.3.1
pyparsing             2.4.7
PyQt5                 5.15.4
PyQt5-Qt5             5.15.2
PyQt5-sip             12.8.1
python-dateutil       2.8.1
python-Levenshtein    0.12.2
pytz                  2021.1
PyWavelets            1.1.1
PyYAML                5.4.1
pyzmq                 22.0.3
rarfile               4.0
requests              2.25.1
scikit-image          0.17.2
scikit-learn          0.24.2
scipy                 1.6.3
seqeval               1.2.2
setuptools            56.0.0
Shapely               1.7.1
shellcheck-py         0.7.2.1
six                   1.16.0
smmap                 4.0.0
threadpoolctl         2.1.0
tifffile              2021.4.8
toml                  0.10.2
tqdm                  4.60.0
typing-extensions     3.10.0.0
urllib3               1.26.4
virtualenv            20.4.6
visualdl              2.1.1
Werkzeug              1.0.1

**Comment by Aunixtoyou** [comment]
找到错误信息了

错误应用程序名称: python.exe，版本: 3.8.10150.1013，时间戳: 0x608fe38a
错误模块名称: MSVCP140.dll，版本: 14.27.29114.0，时间戳: 0x5f972b18
异常代码: 0xc0000005
错误偏移量: 0x00000000000026de
错误进程 ID: 0x1234
错误应用程序启动时间: 0x01d7459cd8c56d88
错误应用程序路径: D:\Software\Python\Python38\python.exe
错误模块路径: C:\WINDOWS\SYSTEM32\MSVCP140.dll
报告 ID: 57c9687c-75d9-4dbf-81e5-6bb4994ce5ca
错误程序包全名: 
错误程序包相对应用程序 ID: 

程序在predict_rec.py __call__函数里的循环跑着跑着就暴毙了。目前无解...

**Comment by Evezerest** [comment]
感谢提示，问题正在定位和解决中。目前建议可以先把数据集做一个拆分，然后再自动标注。

> 找到错误信息了
> 
> 错误应用程序名称: python.exe，版本: 3.8.10150.1013，时间戳: 0x608fe38a
> 错误模块名称: MSVCP140.dll，版本: 14.27.29114.0，时间戳: 0x5f972b18
> 异常代码: 0xc0000005
> 错误偏移量: 0x00000000000026de
> 错误进程 ID: 0x1234
> 错误应用程序启动时间: 0x01d7459cd8c56d88
> 错误应用程序路径: D:\Software\Python\Python38\python.exe
> 错误模块路径: C:\WINDOWS\SYSTEM32\MSVCP140.dll
> 报告 ID: 57c9687c-75d9-4dbf-81e5-6bb4994ce5ca
> 错误程序包全名:
> 错误程序包相对应用程序 ID:
> 
> 程序在predict_rec.py __call__函数里的循环跑着跑着就暴毙了。目前无解...
