### ISSUE TITLE
PGnet数据标注

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2727]
用PGNet做进行端到端训练时，数据集标注的点的个数必须都是统一一样的吗，比如都标14个点或者都标12个点，能不能随意标点数，只要能够按顺时针从左上角开始标这样

**Comment by MissPenguin** [comment]
目前代码要求统一的点数哈

**Comment by tjpulfn** [comment]
请问怎么进行数据集标注点个数统一@ @MissPenguin

**Comment by mydhui** [comment]
@tjpulfn 我试了一下，统一的意思是每一次训练标注的点的个数要求一样。比如你可以标注数据的时候标4、6、8、10、12 点polygon (注意必须是偶数)。如果你在标注期间有的图片标了6个点有的图片标了10个点，最后需要统一后处理label，直到所有label全是10个点
