### ISSUE TITLE
loss异常可能什么原因

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/PaddleOCR#273]
lr为0.001和lr为0.01的loss如下
![image](https://user-images.githubusercontent.com/18586273/85989852-b4e8d180-ba23-11ea-946a-f321872942d3.png)
![image](https://user-images.githubusercontent.com/18586273/85989883-c205c080-ba23-11ea-8f0f-c7ab884a4ba7.png)
lt一直为0，lb为1，ls有时爆炸

可能和我数据有关系：
![image](https://user-images.githubusercontent.com/18586273/85989991-ed88ab00-ba23-11ea-9d81-75215a9da509.png)
![image](https://user-images.githubusercontent.com/18586273/85990034-fc6f5d80-ba23-11ea-98aa-16e6f0eec942.png)

**Comment by MissPenguin** [comment]
如果只是更换了数据，可以check下数据格式，注意transcription为“###”的文本框会被ignore，还可以把预处理完的shrink map、threshold map、binary map画出来看看是否正确

**Comment by Ezra-Yu** [comment]
就是这个“###”!!!
shrink map、threshold map、binary map画的脚本在哪？

**Comment by Ezra-Yu** [comment]
训练了一会儿，就会停下来，不知道为什么？可以解释一下吗
![image](https://user-images.githubusercontent.com/18586273/86079604-70ad0e00-bac3-11ea-9bb9-47e9262b85e0.png)

**Comment by dyning** [comment]
现在训练正常了吗？
