### ISSUE TITLE
导入paddle问题

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2731]
在linux上导入paddle时，显示cuda路径有问题，但是paddle.utils.run_check()正常。请问这是怎么回事？

![image](https://user-images.githubusercontent.com/13652569/117467241-148a0480-af86-11eb-976e-84d7500f116a.png)

**Comment by tink2123** [comment]
可以测试下能否正确训练，如果没有问题的话可以不用理会这个waring。

**Comment by Lie-huo** [comment]
> 可以测试下能否正确训练，如果没有问题的话可以不用理会这个waring。

感觉速度慢了，使用huserving部署官方给出的服务器版ocr模型，单张图片的时间是0.5秒左右，图片大小在500k左右，gpu使用的是16g的T4，请问平均0.5s的速度正常吗

**Comment by LDOUBLEV** [comment]
预测时间和图像大小也有关系，第一次预测模型初始化等比较耗时，连续预测多张图，每个图都很慢吗？

可以设置时间戳，看看哪个部分比较慢，是预处理后处理，还是inference部分耗时较多
