### ISSUE TITLE
PGNet模型在使用export_model.py导出预测模型后，预测时与预训练模型的结果不同

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleOCR#2732]
我的paddlepaddle版本是2.0.2，CUDA10.2，系统ubuntu18.04.
我使用自己的数据集训练了PGNet，使用预训练模型和脚本tools/infer_e2e.py时，检测效果很好。
但在转换到预测模型后，就检测不到字符了。
请问这种情况可能是什么原因呢

**Comment by MissPenguin** [comment]
训练改了哪些参数，模型转换和预测的命令都发出来看下

**Comment by gaooolianggg** [comment]
后来找到问题了。是默认的配置文件中，训练和Infer的图像通道不一样，修改后就好了。
