### ISSUE TITLE
印章文字识别

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2733]
针对印章弯曲文本识别时，只对识别部分采用哪个模型训练效果好一点啊，训练时可以加水平文本和弯曲文本一起训练吗，我用starNet训练时，在训练集识别效果比较好，用测试集测试效果不好，能给推荐一下模型吗，谢谢

**Comment by LDOUBLEV** [comment]
> 针对印章弯曲文本识别时，只对识别部分采用哪个模型训练效果好一点啊

只是识别的话，可以试试带TPS模块的识别网络，也可以试试RARE；如果需要检测的话，可以试试PGNet算法
