### ISSUE TITLE
Error: An error occurred here. There is no accurate error hint for this error yet.

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#274]
跑demo的时候，遇到以下问题
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUBLAS_STATUS_EXECUTION_FAILED] at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)

**Comment by LDOUBLEV** [comment]
请问运行的是哪个demo，方便发一下运行指令和你的环境： CPU/GPU 、 cuda 、 cudnn
