### ISSUE TITLE
release/2.1，hub serving ocr system，Predict time很长

### ISSUE THREAD

**Issue by soxunyi** [PaddlePaddle/PaddleOCR#2742]
使用GPU，同一张图片，经过多次测试，发现：在release/2.1，通过 python3 PaddleOCR/tools/test_hubserving.py http://127.0.0.1:8868/predict/ocr_system ./ocr-test-imgs/zh.png（见zh.png.zip），Predict time在400毫秒以上，
而develop分支下，使用1.1模型文件，Predict time仅130毫秒左右。请问，产生如此大差别的原因是什么？需要去配置哪些参数？

此外，develop分支下，可以识别出宽为2880px的图片上文字(见empty-result.png.zip)，而release/2.1识别结果为空，通过修改--det_max_side_len也不行。

多谢

[zh.png.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6445518/zh.png.zip)

[empty-result.png.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6445528/empty-result.png.zip)

**Comment by MissPenguin** [comment]
您好，我这边验证1.1和2.0分支用zh.png预测平均耗时都在大约100ms，无较大diff；图empty-result.png在2.1分支下用predict_rec.py可以正确识别，用predict_system.py会由于检测不完整而识别不全，1.1和2.1的模型是静态图和动态图机制下分别训练的，在我们的验证集上整体指标接近，但在个别图上有diff很正常哈。
