### ISSUE TITLE
🚨 Potential Code Injection (CWE-94)

### ISSUE THREAD

**Issue by huntr-helper** [PaddlePaddle/PaddleOCR#2744]
👋 Hello, @dyning, @LDOUBLEV, @WenmuZhou - a potential high severity Code Injection (CWE-94) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-PaddlePaddle/PaddleOCR** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by JamieSlome** [comment]
@MissPenguin - can you please confirm if this vulnerability is valid and/or has been patched, and the patch commit SHA?

Cheers! 🍰
