### ISSUE TITLE
PGNet数据集标注格式转换

### ISSUE THREAD

**Issue by KampauCheung** [PaddlePaddle/PaddleOCR#2747]
请问是否有脚本能够将目前公开的数据集（art, lsvt, rects等）转换为符合PGNet输入的14点标注？类似于SAST模型训练额外加入的经过整理格式整理的英文公开数据集icdar2013、icdar2017、COCO-Text、ArT等。

**Comment by MissPenguin** [comment]
没有现成的转换工具哈，可以按照格式要求自己写一下
