### ISSUE TITLE
SRN实现细节：gsrm_features计算成gsrm_out，用了embeding的权重相乘，这个是什么原理

### ISSUE THREAD

**Issue by simplify23** [PaddlePaddle/PaddleOCR#2748]
在看SRN_head代码时，GSRM模块中，不是很理解，使用两种transformer Unit之后，1、为什么两种Unit会直接使用相加的形式 2、这个self.mul函数具体代表什么意思，为什么要这样做呢？看了原论文，但是似乎没有提及这两个操作。非常感谢
`        self.mul = lambda x: paddle.matmul(x=x,
                                           y=self.wrap_encoder0.prepare_decoder.emb0.weight,
                                           transpose_y=True)`
上面是这个函数的定义，下面是实现部分

`     
       gsrm_feature1 = self.wrap_encoder0(enc_inputs_1)
       
        gsrm_feature2 = self.wrap_encoder1(enc_inputs_2)

        ...
        gsrm_features = gsrm_feature1 + gsrm_feature2

        gsrm_out = self.mul(gsrm_features)`

**Comment by tink2123** [comment]
1. gsrm需要感知除本身字符外的所有位置信息，这里是对当前字符的左边信息和右边信息分开来感知的，最后再合一块。所以是一个相加
2. mul 这个操作是transformer里的加权求和 attention_weights * feature

**Comment by simplify23** [comment]
> 1. gsrm需要感知除本身字符外的所有位置信息，这里是对当前字符的左边信息和右边信息分开来感知的，最后再合一块。所以是一个相加
> 2. mul 这个操作是transformer里的加权求和 attention_weights * feature

感谢您的回复。1、可以理解对左边信息感知和右边信息感知的获取上下文的做法，但是直接通过相加的方式主要是出于什么理由呢。比如‘s-t-u-d-y’单词，在预测t时，把s,u合并起来，我理解是可能在预测t的时候并没有预测成功，可能预测成了't-u-d-y'或者‘s-s-t-u-d-y’,这样在前后感知的时候能起到预测t的正面效果，不知道这样的理解是否正确。但如果是这样，直接采用相加的方式是否并不那么合理
2、attention_weights * feature这样做法是出于什么考虑设计的，我可能Transformer系列论文看的不那么仔细，没有在其他文献上看到这一方面的动机和原理
