### ISSUE TITLE
CPU能正常识别文字，但使用GPU就无法识别文字

### ISSUE THREAD

**Issue by suiyi1420** [PaddlePaddle/PaddleOCR#2749]
在Jetson NANO 4G上部署后使用CPU模式能正确识别图片中的文字，但添加了user_gpu=True参数后，识别结果与CPU的识别结果相差非常大，甚至无法识别，是不是GPU模式下还需要设置什么参数？
当前环境：
CUDA : 10.2.89
CuDNN :8.0.0.180
Jetpack 4.5.1 
【代码】
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(lang="ch",use_gpu=True)
img_path ='3.png'
result = ocr.ocr(img_path)
txts = [line[1][0] for line in result]
print(txts)

【结果】
这是使用CPU模式，use_gpu=False 情况下的识别结果，识别正确

![11111111](https://user-images.githubusercontent.com/15998309/117623456-6ad58e00-b1a6-11eb-8148-8d65c651cbd3.png)

这是使用GPU，use_gpu=True 情况下的结果，完全识别错误，并且使用官方的示例去识别doc/imgs文件夹下的图片，全都无法识别。
![222222222222](https://user-images.githubusercontent.com/15998309/117623764-c7d14400-b1a6-11eb-9e91-3961e93ca712.png)

这是什么问题？

**Comment by LDOUBLEV** [comment]
你安装的paddle是哪一个版本

**Comment by suiyi1420** [comment]
> 还没在Nano GPU上测试过

paddle 2.0.2

**Comment by LDOUBLEV** [comment]
目前你的问题已经复现，预测团队同学正在检查问题

**Comment by suiyi1420** [comment]
> 目前你的问题已经复现，预测团队同学正在检查问题

感谢！若问题处理好麻烦通告下

**Comment by suiyi1420** [comment]
> 目前你的问题已经复现，预测团队同学正在检查问题

paddle库更换到2.1后GPU识别结果正常了，感谢团队
