### ISSUE TITLE
Results differ in running inference and predict

### ISSUE THREAD

**Issue by hungnv21292** [PaddlePaddle/PaddleOCR#2755]
Hi author
Thanks you very much for your great contribution.

I trained recognition module with a custom dataset and run inference/predict in a testset. However the results of inference and predict are difference. (acc of predict ~97%, but inference ~70%)
Inference run infer_rec.py with trained model.
Predict run predict_rec.py with exported model.

I used backbone MobileNetV3 and CTC head/loss.

My environment:
- OS: Ubuntu 20.04
- source code: tag version PaddleOCR 2.1.0
- paddlepaddle-gpu: 2.0.0
Notes: I tried with other version: PaddleOCR2.0.0 and paddlepadlle-gpu 2.0.1 but get the same issue.

Please give me your suggestion if you know its cause

**Comment by WenmuZhou** [comment]
Can you post a log？
