### ISSUE TITLE
弯曲文本识别训练

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2756]
![0000000](https://user-images.githubusercontent.com/44855506/117752618-abd2ae80-b249-11eb-8ffe-138bee5355c6.jpg)
使用starnet弯曲文本识别训练时，直接把这种训练数据输入到网络可以吗，如果弯曲文本和水平文本同时训练时，
![0095456](https://user-images.githubusercontent.com/44855506/117752851-1552bd00-b24a-11eb-8ae5-e4f36cab92f4.jpg)
比如这种的，image_shape该怎么协调呢

**Comment by WenmuZhou** [comment]
imageshape用一样的就行，弯曲的会被tps校正为水平的

**Comment by Mafengqiang** [comment]
> imageshape用一样的就行，弯曲的会被tps校正为水平的

我直接输入的这种弯曲的文本，他是怎么去检测文字的位置然后去做tps校正呢，我只是用来做识别，没有具体文字的坐标点
