### ISSUE TITLE
crnn 对特定字体文字的识别

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#2760]
您好， 我是用的paddle1.1系列的训练代码(develop分支)从头训练的crnn+ctc 模型， 字典文件也是自己的，里面有将近9000的字符，包括中英文、符号。

配置文件: res_r34_vd_none_bilstm_ctc.yml

数据方面： 
        起始数据：总量 2kw+ 张合成数据（彩色）， 字体使用的是常见的那几种字体， 生成样本时就加入了图像增强。其中20w为 
                          验证集， 其余为训练集。(其实这些数据是别人给我的， 里面也包含了一些这种特定字体样本， 具体有多少我就 
                          不知道了......)
        后加数据：使用该种特定字体生成了 800w+ 张图像， 图像增强的程度较小， 其中验证集数据量不到10w
                          
工作： 在开始训练该特定字体中文识别模型时， 由于业务需要， 先使用起始数据训练出一个在它的验证集上准确率为98%的模型， 效果比较强。后来要训练识别该特定字体文字的模型， 就将起始数据和后加数据一起训练， 使用上面那个准确率为98%当作预训练模型，训练了8 epoch左右， 新模型在验证集这30w+张数据上的准确率只有不到96%， 实际测试中对该特定字体文字的识别率只有80%多。学习率衰减策略用的是分段衰减， 现在已经到了0.00005， max_text_length=25, character_type=ch, batch_size=64，4卡， loss基本就在80上下震荡， 训练过程中的acc在96%上下。

问题：
        1. 请问我之后应该如何优化， 以及有什么方法可以训练的快些么?
        2. 在训练过程中， 不同的iter 输出的acc 经常是同样的值， 这是说明这个模型已经到了瓶颈了么?
![image](https://user-images.githubusercontent.com/61573829/117774762-65427b80-b26c-11eb-8e99-da4e6ffc85b5.png)
![image](https://user-images.githubusercontent.com/61573829/117774774-670c3f00-b26c-11eb-84cd-b1121fbbb4b3.png)

**Comment by Zhangts98** [comment]
呃， 还有就是， 在训练过程中， 不同的iter 输出的acc 经常是同样的值， 这是说明这个模型已经到了瓶颈了么?

**Comment by Zhangts98** [comment]
> 后面的finetune可以直接使用你的数据集，然后训练时加数据扩充
非常感谢， 对于问题2 能解答一下嘛？

**Comment by WenmuZhou** [comment]
问题2：是的

**Comment by nissansz** [comment]
有没有中文字体集合？
