### ISSUE TITLE
paddlehub部署服务假死

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2761]
使用paddlehub部署了通用服务器版ocr服务，运行一段时间后，出现假死，请求没反应，在log日志中只有上次调用成功的记录，这次的没有任何记录，查看显存正常，内存占用3G左右，服务端口也可以ping通，就是请求没反应。paddlepaddle版本2.0.1，paddlehub版本2.0.4，cuda版本9.2，显卡T4 16G。日志文件中没有错误输出，目前无法排除问题所在。

**Comment by Lie-huo** [comment]
> 感觉是请求了太多，任务在排队

我就发送了了1个请求，然后一直没反应

**Comment by WenmuZhou** [comment]
环境贴一下，看看我这边能不能复现

**Comment by Lie-huo** [comment]
系统：centos 7.6
python：3.6
显卡：T4
显卡驱动版本：418.197.02
cuda：9.2
cudnn：7.6
paddlehub：2.0.4
paddlepaddle-gpu：2.0.1.post90
opencv-python：4.2.0.32

**Comment by lmmir** [comment]
cuda 版本升级到11.0试试，我之前用10.2，就是出现假死，调用很慢。

**Comment by Lie-huo** [comment]
> cuda 版本升级到11.0试试，我之前用10.2，就是出现假死，调用很慢。

好的，谢谢，我试一下吧
