### ISSUE TITLE
相同模型，c++与python检测结果有差异

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleOCR#2770]
已经将两者的预处理对其，统一resize到1280*736

**Comment by littletomatodonkey** [comment]
给相同的输入呢？预处理之后的结果是相同的吗？

**Comment by wuranran** [comment]
> 给相同的输入呢？预预处理后结果是相同的都是，
c++预处理后的图：
![3](https://user-images.githubusercontent.com/38750407/117942150-57106000-b33d-11eb-90b8-84cbe1781070.jpg)

python的

![2](https://user-images.githubusercontent.com/38750407/117942232-6b545d00-b33d-11eb-8282-6a446ded179e.jpg)
我测试了以下两者相同

**Comment by wuranran** [comment]
> 给相同的输入呢？预处理之后的结果是相同的吗？
python预处理
![2](https://user-images.githubusercontent.com/38750407/117944556-f6ceed80-b33f-11eb-8d2a-f29c51f5eb73.jpg)

c++预处理后的
![33](https://user-images.githubusercontent.com/38750407/117944579-fd5d6500-b33f-11eb-946e-276dff4dbe70.jpg)
经测试，预处理图像是一样的

**Comment by littletomatodonkey** [comment]
这块是因为之前的cpp和python预处理方式不太一样，已经修复了，你再试下最新代码呢？

https://github.com/PaddlePaddle/PaddleOCR/commit/64a3580f1bd3c9d0d2c70df9237f5bf7b5875614

**Comment by wuranran** [comment]
> 这块是因为之前的cpp和python预处理方式不太一样，已经修复了，你再试下最新代码呢？
> 
> [64a3580](https://github.com/PaddlePaddle/PaddleOCR/commit/64a3580f1bd3c9d0d2c70df9237f5bf7b5875614)

我按照以下方式将两者的预处理对齐了，这样对齐有什么问题吗
c++：
  cv::resize(img, resize_img, cv::Size(1280, 736));
    ratio_h = double(736) / double(h);
    ratio_w = double(1280) / double(w);
python：
pre_process_list = [{
            'DetResizeForTest': {'image_shape': [736,1280]}
        }, {
