### ISSUE TITLE
StyleText 生成图像后，标签和图像文字偶尔不对

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#2773]
感谢提供StyleText这么好的生成工具，我这边用了一下，大部分生成的图像文字和label都是对的。
但偶尔会有图像文字生成了叠字（两个字相同），而真正的label里面不是叠字。
例如：labal标签中为：0/51.png	黄玲霞。
但生成图像中的文字是：黄玲玲
大概10张里面有一张发生这种现象。
请问怎么改进？

**Comment by weisy11** [comment]
抱歉，这是一个已知缺陷。目前已经初步做了修正方案，还在验证中，最快下个月更新新模型，敬请期待

**Comment by guijuzhejiang** [comment]
@weisy11 感谢回复，期待。
