### ISSUE TITLE
不同显卡上速度测评：2070s 2080ti  3090

### ISSUE THREAD

**Issue by octaviawfx** [PaddlePaddle/PaddleOCR#2775]
1000张图片的测试集上，平均每张图片的时间：3090上：0.328s；2070s上:0.20s；2080ti上0.111s；
3090显卡24G显存，2080ti11G显存，但是2080ti的速度是3090的3倍；
Tesla T4显卡，3080显卡上的速度，大家感兴趣的话可以回复，或者邮件我octaviawfx@163.com
------------------补充如下--------------------------
3090机器的配置：CUDA11.1+CUDNN 8.2.0+paddlepaddle-gpu=2.0.0rc1.post110

**Comment by LDOUBLEV** [comment]
GPU是吧，3090上建议CUDA11 + CUDNN8.1 + Paddlepaddle-gpu=2.1

cudnn版本小于8.1 GPU上存在性能下降的问题，Nvidia的同学在8.1修复了

**Comment by octaviawfx** [comment]
> GPU是吧，3090上建议CUDA11 + CUDNN8.1 + Paddlepaddle-gpu=2.1
> 
> cudnn版本小于8.1 GPU上存在性能下降的问题，Nvidia的同学在8.1修复了

**Comment by octaviawfx** [comment]
> GPU是吧，3090上建议CUDA11 + CUDNN8.1 + Paddlepaddle-gpu=2.1
> 
> cudnn版本小于8.1 GPU上存在性能下降的问题，Nvidia的同学在8.1修复了

嗨，我把3090机器的配置也更新了一下，除了paddlepaddle-gpu版本有所不同，其它满足要求，我更换下paddlepaddle-gpu版本，再测试一下

**Comment by LDOUBLEV** [comment]
好的，有测试结论可以同步在这里

**Comment by octaviawfx** [comment]
> 好的，有测试结论可以同步在这里

wait, 根据https://github.com/PaddlePaddle/Paddle/blob/develop/README_cn.md，目前PaddlePaddle最新版本: v2.0；
请问您说的Paddlepaddle-gpu=2.1来自哪里？

**Comment by LDOUBLEV** [comment]
在2.0.2上也可以先测试看看，目前已经有了paddle2.0.2

**Comment by soxunyi** [comment]
@octaviawfx 我这边，在3090，paddle2.0.2，遇到同样性能问题。
[issues/2742](https://github.com/PaddlePaddle/PaddleOCR/issues/2742)

**Comment by LDOUBLEV** [comment]
> GPU是吧，3090上建议CUDA11 + CUDNN8.1 + Paddlepaddle-gpu=2.1
> 
> cudnn版本小于8.1 GPU上存在性能下降的问题，Nvidia的同学在8.1修复了


目前paddle2.1已经发布了，可以用paddle2.1在 3090上测试看看

**Comment by gdwu1427** [comment]
@octaviawfx 你好，paddle2.1已更新，在 3090上测试情况能否分享一下
