### ISSUE TITLE
c++ 中有实现get_rotate_crop_image（）这个函数功能吗

### ISSUE THREAD

**Issue by wuranran** [PaddlePaddle/PaddleOCR#2776]

**Comment by LDOUBLEV** [comment]
有的，在https://github.com/PaddlePaddle/PaddleOCR/blob/4cfba6f1d7a008ea7e9104e627460d8c154a21de/deploy/cpp_infer/src/ocr_rec.cpp#L131

**Comment by wuranran** [comment]
> GetRotateCropImage

好的，谢谢
还想请教以下，python与c++文字检测框位置有一点不同，但是识别时，c++版的总是识别错误

**Comment by LDOUBLEV** [comment]
这个不太对的，你的测试图像发我一下，我这边测试下

**Comment by LDOUBLEV** [comment]
检测框有一点不同也不太对，你要不更新代码再试下
