### ISSUE TITLE
win10x64下conda环境安装paddlepaddle缓慢，清华镜像源已设置

### ISSUE THREAD

**Issue by botao1995** [PaddlePaddle/PaddleOCR#2777]

**Comment by LDOUBLEV** [comment]
换成百度源试试呢
-i https://mirror.baidu.com/pypi/simple

**Comment by botao1995** [comment]
> 换成百度源试试呢
> -i https://mirror.baidu.com/pypi/simple
pip无问题，conda有问题，烦请官方维护一下，谢谢！

**Comment by LDOUBLEV** [comment]
好的，收到
