### ISSUE TITLE
label_file_list和ratio_list不匹配

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#2778]
您好，我在训练DB检测模型的时候，采用多个数据集会报错，如下我用两个数据集进行验证。说是label_file_list和ratio_list不匹配，请问采用多个数据集的时候label_file_list的格式是什么样子的呢？
![image](https://user-images.githubusercontent.com/43515926/118066134-bd928e00-b3d0-11eb-9a1c-0a7381451ca4.png)

![image](https://user-images.githubusercontent.com/43515926/118066253-f5013a80-b3d0-11eb-8926-02ab3b81b89e.png)

**Comment by LDOUBLEV** [comment]
try：
```
label_file_list:
  -  [data_list1,  data_list2]
```
