### ISSUE TITLE
文本识别中，TPS模块，为啥参数量并不大，但pdmodel很大

### ISSUE THREAD

**Issue by simplify23** [PaddlePaddle/PaddleOCR#2779]
测试了一下，TPS的small模块，参数量<1M，但这个模块会让model文件增加7.0+M以上，这个是什么原因呢？是TPS中的卷积或者全连接导致的吗？还是有什么其他原因？

**Comment by LDOUBLEV** [comment]
参数量和model文件没有大小关系，参数量影响paparams文件的大小，按照Paddle OCR里StartNet和CRNN的对比，加TPS也就相差1M左右；

startnet 模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_tps_bilstm_ctc_v2.0_train.tar
CRNN模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar

**Comment by simplify23** [comment]
> 参数量和model文件没有大小关系，参数量影响paparams文件的大小，按照Paddle OCR里StartNet和CRNN的对比，加TPS也就相差1M左右；
> 
> startnet 模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_tps_bilstm_ctc_v2.0_train.tar
> CRNN模型： https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar

理解这个意思。我们可以在训练的时候统计参数量来控制pdparams的大小，但model文件的大小和什么相关呢？TPS的small版本，参数<1M，但通过控制变量（startnet和crnn）发现，增加TPS,pdmodel的大小增加了7.0+M,目前测出来发现pdmodel的增加和TPS预测的矫正点的多少有关（如20个点->7.0+ 10个点->3.0+等等）由于比赛的要求，想问一下我该如何控制pdmodel模型的大小，这个又是一个什么样的原理呢

**Comment by simplify23** [comment]
另外这个pdmodel，可以通过一些模型压缩手段缩小吗，还是模型压缩仅能压缩参数量影响pdparams？

**Comment by LDOUBLEV** [comment]
比赛限制的模型大小是inference  model的大小，需要按照[这个方法](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md)转换成inference model (pdmodel, pdiparams)，实际上训练保存的模型都比inference model要大不少

**Comment by LDOUBLEV** [comment]
你好，修改了TPS 的代码，[PR链接](https://github.com/PaddlePaddle/PaddleOCR/pull/3069)，预计pdmodel可以缩减到1.5M
