### ISSUE TITLE
同一批图片，train 和eval 的准确度都很高，然后用导出的模型做预测，结果完全不对。

### ISSUE THREAD

**Issue by deannazhang-dot** [PaddlePaddle/PaddleOCR#2782]
用自己的数据集训练之后预测效果比较差，为了跑通自定义数据集训练，做了如下实验。
1 用opencv 随机生成1000张尺寸为1500*900的图片，上面随机生成了5行文字（数字和英文混合，随机生成图片如下）
![image](https://user-images.githubusercontent.com/76757393/118075570-dc018500-b3e2-11eb-8807-13caf9f784f8.png)

2 对1000张图片用paddleOCR 的标注工具进行半自动化标注，标注完成之后进行检测训练，为了方便，我把train数据集也设置成了eavl数据集，用DB模型做检测训练，结果显示eval上准确度达到95%以上，但是我用同一批训练的数据拿去做预测，预测结果如下，其中蓝色部分为识别到的文字区域，感觉完全不对，不知道是什么原因导致的，困惑中。

![image](https://user-images.githubusercontent.com/76757393/118075685-1cf99980-b3e3-11eb-911d-9388e1fa2a57.png)

**Comment by LDOUBLEV** [comment]
- 检查导出模型使用的yml文件是否是和训练用的yml文件是一致的
- 检查导出模型时，pretrained_model是否load到定义的网络中

**Comment by deannazhang-dot** [comment]
千算，万算，发现是自己到export 模型的时候，少加了这一句Global.load_static_weights 参数需要设置为 False。另外还发现一个问题就是我的yml文件中DetResizeForTest: image shape:[736,1280],追到源码里面看发现这句会把输入图像预处理成736*1280尺寸，但最后predict的时候，里面默认是不设置DetResizeForTest这一项的，后面把yml的配置文件里这一项也屏蔽了。目前貌似至少正常点了，太不容易了。。。。。。

**Comment by LDOUBLEV** [comment]
恭喜大佬踩坑，你说的这两个问题我等下提个PR修复了

**Comment by Dandelion111** [comment]
> 恭喜大佬踩坑，你说的这两个问题在最新代码里都修复了，去掉了Global.load_static_weights 参数， DetResizeForTest: image shape:[736,1280], 在中文检测的配置文件下也屏蔽了

请问如果的训练DBNet训练集输入是224*224，那么验证集大小应该如何设置？默认的是把短边resize到736好像不合适
