### ISSUE TITLE
有没有打算把中文繁体纳入通用模型中？目前通用模型是支持简体中文和英文。

### ISSUE THREAD

**Issue by Jane-Ding** [PaddlePaddle/PaddleOCR#2786]
对于一些香港的发票，里面会有繁体中文，英文，也有简体中文，使用现在的通用模型，无法识别繁体中文，用繁体中文模型，识别英文效果不太好。谢谢。
![image](https://user-images.githubusercontent.com/69578198/118089884-7241a500-b3fb-11eb-88d2-ce2d1a8cb48c.png)

**Comment by LDOUBLEV** [comment]
现在的中文模型也支持繁体识别，但是训练数据中繁体数据没有那么多，训练出来的效果有点差；
目前是打算把繁体中文也放在中文模型中，可否提供下你所用到的繁体文字，有遗漏的我们补充到中文字典中

**Comment by Jane-Ding** [comment]
> 现在的中文模型也支持繁体识别，但是训练数据中繁体数据没有那么多，训练出来的效果有点差；
> 目前是打算把繁体中文也放在中文模型中，可否提供下你所用到的繁体文字，有遗漏的我们补充到中文字典中

感谢回答。是的，目前中文模型也支持繁体识别，就是效果不是很好。我现在没有繁体文字的数据集，如果搜集一些数据，可以在中文模型的基础上fine tune吗？ 你们后面有打算提升繁体中文的表现吗？

**Comment by LDOUBLEV** [comment]
> 如果搜集一些数据，可以在中文模型的基础上fine tune吗？
这个是可行的

> 你们后面有打算提升繁体中文的表现吗？
打算提升的，但是也受限于数据，如果你们有可以公开的数据，可以发给我们，我们进一步迭代模型
