### ISSUE TITLE
win10x64下trt推理编译Error

### ISSUE THREAD

**Issue by botao1995** [PaddlePaddle/PaddleOCR#2787]
14>------ 已启动全部重新生成: 项目: extern_cryptopp, 配置: Release x64 ------
14>Creating directories for 'extern_cryptopp'
14>Performing download step (git clone) for 'extern_cryptopp'
14>Cloning into 'extern_cryptopp'...
5>fatal: unable to access 'https://github.com/gflags/gflags.git/': Failed to connect to github.com port 443: Timed out
5>Cloning into 'extern_gflags'...
7>fatal: unable to access 'https://github.com/progschj/ThreadPool.git/': Failed to connect to github.com port 443: Timed out
7>Cloning into 'extern_threadpool'...
13>fatal: unable to access 'https://github.com/baidu-research/warp-ctc.git/': Failed to connect to github.com port 443: Timed out
13>Cloning into 'extern_warpctc'...
5>fatal: unable to access 'https://github.com/gflags/gflags.git/': Failed to connect to github.com port 443: Timed out
5>Cloning into 'extern_gflags'...
7>fatal: unable to access 'https://github.com/progschj/ThreadPool.git/': Failed to connect to github.com port 443: Timed out
7>Cloning into 'extern_threadpool'...
13>fatal: unable to access 'https://github.com/baidu-research/warp-ctc.git/': Failed to connect to github.com port 443: Timed out
13>Cloning into 'extern_warpctc'...
6>-- extracting... [analysis]
6>-- extracting... [rename]
14>fatal: unable to access 'https://github.com/weidai11/cryptopp.git/': OpenSSL SSL_read: Connection was reset, errno 10054
14>Cloning into 'extern_cryptopp'...
5>fatal: unable to access 'https://github.com/gflags/gflags.git/': Failed to connect to github.com port 443: Timed out
5>-- Had to git clone more than once:
5>CMake Error at E:/env/Paddle/build/third_party/gflags/tmp/extern_gflags-gitclone.cmake:31 (message):
5>  Failed to clone repository: 'https://github.com/gflags/gflags.git'
5>
5>
5>          3 times.
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: “E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-mkdir.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-download.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-update.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-patch.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-configure.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-build.rule;E:\env\Paddle\build\CMakeFiles\451b97997368e34a53f360be45f665f1\extern_gflags-install.rule;E:\env\Paddle\build\CMakeFiles\bac0ee7ab161aa1cfe806e3d022a580b\extern_gflags-complete.rule;E:\env\Paddle\build\CMakeFiles\6d3fa5ee584ac912aaadb29e76ee20da\extern_gflags.rule”的自定义生成已退出，代码为 1。
5>已完成生成项目“extern_gflags.vcxproj”的操作 - 失败。
15>------ 已启动全部重新生成: 项目: extern_glog, 配置: Release x64 ------
7>fatal: unable to access 'https://github.com/progschj/ThreadPool.git/': Failed to connect to github.com port 443: Timed out
7>-- Had to git clone more than once:
7>CMake Error at E:/env/Paddle/build/third_party/threadpool/tmp/extern_threadpool-gitclone.cmake:31 (message):
7>          3 times.
7>  Failed to clone repository: 'https://github.com/progschj/ThreadPool.git'
7>
7>
7>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: “E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-mkdir.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-download.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-update.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-patch.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-configure.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-build.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-install.rule;E:\env\Paddle\build\CMakeFiles\4d2266f456ffd881b8c56528cc28c102\extern_threadpool-test.rule;E:\env\Paddle\build\CMakeFiles\bac0ee7ab161aa1cfe806e3d022a580b\extern_threadpool-complete.rule;E:\env\Paddle\build\CMakeFiles\6d3fa5ee584ac912aaadb29e76ee20da\extern_threadpool.rule”的自定义生成已退出，代码为 1。
7>已完成生成项目“extern_threadpool.vcxproj”的操作 - 失败。
16>------ 已启动全部重新生成: 项目: extern_pybind, 配置: Release x64 ------
12>fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': OpenSSL SSL_read: Connection was reset, errno 10054
12>Cloning into 'extern_protobuf'...
16>Creating directories for 'extern_pybind'
16>Performing download step (git clone) for 'extern_pybind'
16>Cloning into 'extern_pybind'...
13>fatal: unable to access 'https://github.com/baidu-research/warp-ctc.git/': Failed to connect to github.com port 443: Timed out
13>-- Had to git clone more than once:
13>          3 times.
13>CMake Error at E:/env/Paddle/build/third_party/warpctc/tmp/extern_warpctc-gitclone.cmake:31 (message):
13>  Failed to clone repository:
13>  'https://github.com/baidu-research/warp-ctc.git'

github已代理，即便不用代理 为何使用cmake生成好的项目还会继续请求github呢？

**Comment by LDOUBLEV** [comment]
换个代理试试：fatal: unable to access 'https://github.com/gflags/gflags.git/': Failed to connect to github.com port 443: Timed out

报错是超时
