### ISSUE TITLE
使用Trt推理结果，结果输出乱码

### ISSUE THREAD

**Issue by botao1995** [PaddlePaddle/PaddleOCR#2789]
![image](https://user-images.githubusercontent.com/47848566/118103096-1af80080-b40c-11eb-8acf-f1dd5bd99ca6.png)

**Comment by LDOUBLEV** [comment]
检查下是不是中文解码的问题，目前字典文件是utf-8编码，score看上去挺正常的

**Comment by botao1995** [comment]
问题已经解决
