### ISSUE TITLE
支持在原有的模型上强化么？

### ISSUE THREAD

**Issue by lmmir** [PaddlePaddle/PaddleOCR#2790]
原来的识别印刷体，如果想印刷体+手写体一起识别，是需要重新全部训练，还是只要在用预训练模型，再加入手写数据集就可以了？

**Comment by LDOUBLEV** [comment]
最好是全部重新训练，fine-tune的时候只加入手写数据，可能会影响模型的原效果。

**Comment by lmmir** [comment]
那我fine-tune 手写和印刷的1:1的加入，会影响么模型原效果么？
