### ISSUE TITLE
 'OCRDet' object has no attribute 'text_detector

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#2791]
gpu 环境  hub install deploy/hubserving/ocr_det/     运行没有问题   

想单独运行文件的时候 报错    paddlehub  安装的最新的  2.1.0
python3.7 deploy/hubserving/ocr_det/module.py  
AttributeError: 'OCRDet' object has no attribute 'text_detector'   求指导

**Comment by LDOUBLEV** [comment]
有的，你检查下你的代码，有没有这一行：
https://github.com/PaddlePaddle/PaddleOCR/blob/ce24ca77ba4ae7cab45ff42ca70473e4f68d9e74/deploy/hubserving/ocr_det/module.py#L53

**Comment by wa3926** [comment]
@LDOUBLEV  大佬  代码里面是有的  
from paddlehub.common.logger import logger
from paddlehub.module.module import moduleinfo, runnable, serving
import paddlehub as hub 还有一个奇怪的现象  
 ModuleNotFoundError: No module named 'paddlehub.common'      如果我把 import paddlehub as hub  放上面去  就不报这个错   变成报上面'OCRDet' object has no attribute 'text_detector        但是我本地windows的没问题                          
  现在出问题的是linux docker容器       paddlehub 版本 之前是2。1.0  换成 2.0.4 也不行    ocr 用hub 部署没问题 也能调用  就运行module 报错      求指导！

**Comment by wa3926** [comment]
@LDOUBLEV  大佬 paddlehub  2.0.4  paddle 2.0.2  怎么也不行

**Comment by wa3926** [comment]
@littletomatodonkey  大佬们求指导  我代码重新下载也不行  执行几个 module.py  文件都报错     
ModuleNotFoundError: No module named 'paddlehub.common' 

hub serving start -c deploy/hubserving/ocr_system/config.json  启动没问题  也能正常预测   有点不知道哪里问题了  感觉像hub问题 但是版本换过2个都不行
