### ISSUE TITLE
chinese_ocr_db_crnn_server检测不全

### ISSUE THREAD

**Issue by clayton8011** [PaddlePaddle/PaddleOCR#2792]
对于我生成的大一点的图片，excel表格图片检测的十分不好，只能识出0,其他文字都没有识别出。不知道怎么配置才能扩大选取范围。

**Comment by tink2123** [comment]
请提供一下可复现的测试图片，和测试命令。

**Comment by clayton8011** [comment]
{
    "modules_info": {
        "ocr_system": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": false
            },
            "predict_args": {
                
            }
        }
    },
    "port": 8868,
    "use_multiprocess": false,
    "workers": 2
}
启动了一个服务，通过http请求。返回数据检测不全。

**Comment by clayton8011** [comment]
图片无法公开。
