### ISSUE TITLE
启动OCR模型报错，启动不了

### ISSUE THREAD

**Issue by Ray-Small-Q** [PaddlePaddle/PaddleOCR#2793]
W0514 10:25:39.371384 3892 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1 W0514 10:25:39.375342 3892 device_context.cc:372] device: 0, cuDNN Version: 7.6. ?

--------------------------------------

C++ Traceback (most recent call last):

--------------------------------------

0 paddle::framework::SignalHandle(char const*, int)

1 paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------

Error Message Summary:

----------------------

FatalError: `Segmentation fault` is detected by the operating system.

[TimeInfo: *** Aborted at 1620959536 (unix time) try "date -d @1620959536" if you are using GNU date ***]

[SignalInfo: *** SIGSEGV (@0x8) received by PID 3892 (TID 0x7f62bfbdc700) from PID 8 ***]

**Comment by tink2123** [comment]
从提供的报错信息看不出问题，猜测是环境和paddle不匹配导致的，可以先check下paddle安装是否正确：
```
安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()
如果出现PaddlePaddle is installed successfully!，说明您已成功安装。
```
另外建议在docker中运行

**Comment by Ray-Small-Q** [comment]
> 从提供的报错信息看不到问题，猜测是环境和paddle不匹配导致的，可以先检查下paddle安装是否正确：
> 
> ```
> 安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()
> 如果出现PaddlePaddle is installed successfully!，说明您已成功安装。
> ```
> 
> 另外建议在docker中运行

确认是可以用了，但是为什么docker-compose可以正常启动但是docker stack deploy 就会报上面那个错呢

**Comment by tink2123** [comment]
可能是2个方法导致最终找到的cuda、cudnn版本不同

**Comment by Ray-Small-Q** [comment]
> 可能是2个方法导致最终找到的cuda、cudnn版本不同

用的是10.1-cudnn7-devel-centos7 镜像，版本应该不会变化

**Comment by Ray-Small-Q** [comment]
> > 可能是2个方法导致最终找到的cuda、cudnn版本不同
> 
> 用的是10.1-cudnn7-devel-centos7 镜像，版本应该不会变化



> 可能是2个方法导致最终找到的cuda、cudnn版本不同

![image](https://user-images.githubusercontent.com/49464957/118251941-c96a7700-b4da-11eb-93ca-c13b0244a6e1.png)

使用GPU内存距离正常的老是差一点

**Comment by qiyueliuhuo** [comment]
我也遇到相同的问题
```
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0521 07:19:56.558301  2420 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0521 07:19:56.570338  2420 device_context.cc:422] device: 0, cuDNN Version: 7.6.
```
