### ISSUE TITLE
关于标注粒度的问题

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#2795]
自己在做数据标注，关于标注粒度大概分下面三种：
1，以字为单位标注
2，以词为单位标注
3，以句子为单位标注
请问用哪种粒度标注比较好？

**Comment by tink2123** [comment]
看你的实际场景，crnn不推荐第一种，体现不出算法优势。
2 or 3 看你希望返回什么粒度的结果

**Comment by guijuzhejiang** [comment]
@tink2123 谢谢回复。我买了一些数据是以第一种方式标注的。自己买的数据，哭着也要用完。确实第一种方式标注又累，又用不到rnn的序列特征。不过如果从准确度的角度看，这三种标注的识别准确度是不是一样的呢？

**Comment by tink2123** [comment]
还是要看你具体的场景下，希望返回什么样的结果。识别准确率来看的话，标注越长，训练难度越大。

**Comment by guijuzhejiang** [comment]
@tink2123 收到，谢谢。
