### ISSUE TITLE
ch_ppocr_mobile_v1.1_xx识别预训练模型预测错误

### ISSUE THREAD

**Issue by PGogo** [PaddlePaddle/PaddleOCR#2796]
使用了develop分支，rec_chinese_lite_train.yml配置文件

我加载的是ch_ppocr_mobile_v1.1_xx的识别预训练模型（链接https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_pre.tar），预测出来的结果错误。
但是用ch_ppocr_mobile_v1.1_xx的推理模型（链接https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_infer.tar），预测结果正确。
而且发现用ch_ppocr_mobile_v1.1_rec_pre.tar预训练，使用了ppocr/utils/ppocr_keys_v1.txt字符集，准确率都是从0开始的，Loss开始特别大，而且我使用了自己的训练数据160万，训了10个epoch仍然只有15%的准确率，以我之前的模型的训练经验，应该一个epoch就能到40%了。
当然了，以上是两个问题，一个是预训练模型是否正常的问题，另一个是我的训练问题，主要是想问下前者。能帮忙确认下是我自己的问题还是真的是预训练模型的问题吗？我识别的图片是这张
![1620978562](https://user-images.githubusercontent.com/41355904/118242559-0ed57700-b4d0-11eb-9cf6-52893f26a5de.png)
这张图片只是个例子，其他的很常规的图片里面的文本也识别不了，我把我的验证集不训练直接拿预训练模型验证，准确率为0。麻烦请你们帮测一下，谢谢！

**Comment by littletomatodonkey** [comment]
试下这个预训练模型呢？和推理模型是对应的，pre的这个模型是我们在合成+真实数据集上训练的，train的这个模型是在真实数据上finetune的

https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_train.tar

**Comment by PGogo** [comment]
> 试下这个预训练模型呢？和推理模型是对应的，pre的这个模型是我们在合成+真实数据集上训练的，train的这个模型是在真实数据上finetune的
> 
> https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_train.tar

还是不行，预测出来的是空字符串。请问下这些预训练模型在你们那边已经确认是可以正常预测的了吗？对于上面那张或者是随便截一张白底黑字的印刷体文本，我这边都是预测不出来的。

**Comment by Christina0114** [comment]
我直接用他的与训练模型预测他自己给的韩国小馆图片，效果很差
