### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'det_db_score_mode'

### ISSUE THREAD

**Issue by yszzQ** [PaddlePaddle/PaddleOCR#2799]
AttributeError                            Traceback (most recent call last)
<ipython-input-21-16a968a6de2c> in <module>
      2 
      3 # 同样也是通过修改 lang 参数切换语种
----> 4 ocr = PaddleOCR(lang="ch") # 首次执行会自动下载模型文件
      5 img_path = r'C:/Users/Q/2.jpg'
      6 result = ocr.ocr(img_path)

C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\paddleocr.py in __init__(self, **kwargs)
    343 
    344         # init det_model and rec_model
--> 345         super().__init__(postprocess_params)
    346 
    347     def ocr(self, img, det=True, rec=True, cls=False):

~\PaddleOCR\tools\infer\predict_system.py in __init__(self, args)
     40 class TextSystem(object):
     41     def __init__(self, args):
---> 42         self.text_detector = predict_det.TextDetector(args)
     43         self.text_recognizer = predict_rec.TextRecognizer(args)
     44         self.use_angle_cls = args.use_angle_cls

~\PaddleOCR\tools\infer\predict_det.py in __init__(self, args)
     66             postprocess_params["max_candidates"] = 1000
     67             postprocess_params["unclip_ratio"] = args.det_db_unclip_ratio
---> 68             postprocess_params["use_dilation"] = args.use_dilation
     69             postprocess_params["score_mode"] = args.det_db_score_mode
     70         elif self.det_algorithm == "EAST":

AttributeError: 'Namespace' object has no attribute 'det_db_score_mode'

python3.8.5 报错

**Comment by yszzQ** [comment]
找到原因了 Namespace里少了 det_db_score_mode="fast"

**Comment by LDOUBLEV** [comment]
更新代码即可解决
