### ISSUE TITLE
got an unexpected keyword argument 'gradient_clip'

### ISSUE THREAD

**Issue by goodtogood** [PaddlePaddle/PaddleOCR#28]
`python tools/export_model.py -c configs/det/det_db_mv3.yml -o Global.checkpoints="./output/best_accuracy" Global.save_inference_dir="./inference/det/"`

paddlepaddle-gpu只能用这个版本1.7.2.post97吗？
目前是paddlepaddle-gpu   1.8.0.post107

**Comment by LDOUBLEV** [comment]
> `python tools/export_model.py -c configs/det/det_db_mv3.yml -o Global.checkpoints="./output/best_accuracy" Global.save_inference_dir="./inference/det/"`
> 
> paddlepaddle-gpu只能用这个版本1.7.2.post97吗？
> 目前是paddlepaddle-gpu 1.8.0.post107

目前尚未更新到paddle1.8版本，建议换成paddle1.7吧，1.7.0, 1.7.1, 1.7.2 都可以的

**Comment by goodtogood** [comment]
v1.7 work. thx!
