### ISSUE TITLE
PaddleOCR有专门的API文档吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleOCR#280]
尊敬的开发者，你好，我想请问一下，PaddleOCR有专门的API文档吗，我在飞桨的 API Reference中似乎没有找到`ocr.recognize_text()`的参数说明，我想知道这个函数是否支持PIL.Image作为输入？

期待你的回复！

**Comment by dyning** [comment]
目前没有专门的API文档，预测代码的逻辑比较清楚，建议直接修改读图相关的代码。https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/predict_system.py中的get_image_file_list
函数位置from ppocr.utils.utility import get_image_file_list

**Comment by songyuc** [comment]
@dyning ，好的，谢谢你的回复；
希望飞桨之后可以加入PaddleOCR的API文档；

**Comment by dyning** [comment]
谢谢您的建议，后续我们会考虑。
