### ISSUE TITLE
关于windows10下 rtx3090 c++ 部署的问题

### ISSUE THREAD

**Issue by xixidiaosoulianwa** [PaddlePaddle/PaddleOCR#2801]
请问 windows10下 rtx3090 部署， 采用CUDA、 cudnn、 paddle_inference 哪个版本比较合适

**Comment by littletomatodonkey** [comment]
cuda10.2或者11.0, cudnn 7.6.5, paddle_inference2.0.2

**Comment by lmmir** [comment]
cuda11.0+ 3060系用10.2好像有问题

**Comment by xixidiaosoulianwa** [comment]
> cuda10.2或者11.0, cudnn 7.6.5, paddle_inference2.0.2

我使用cuda11.0,cudnn 8.1.4,paddle_inference2.02，能够成功运行。但从推理速度来看似乎并没有完全发挥显卡的性能（大概跟我笔记本的1660TI速度差不多），是我CUDA和cudnn的版本不对吗？
