### ISSUE TITLE
issue max_text_length 

### ISSUE THREAD

**Issue by JITESH11989** [PaddlePaddle/PaddleOCR#2802]
I have line data  55 char max char length because of that acc reduce as per GitHub issue if I change char max length 25 to 50 it will issue with training but I have line add  55 char length can you guys tell me how to solve the issue. 
this is the link I was read: https://github.com/PaddlePaddle/PaddleOCR/issues/2540
this sample data:
train_img/0022_BindiyaKiAathmakatha_Img_300_Org_Page_0001_crop_9.jpg बीत गया । असमय के इस बुढ़ापे की देहली पर बैठी, मौत की
train_img/0022_BindiyaKiAathmakatha_Img_300_Org_Page_0001_crop_10.jpg प्रतीक्षा कर रही हूँ । पर लगाता है उसने भी सबों के साथ-साथ

**Comment by littletomatodonkey** [comment]
you can modify the `max_text_length` to 60 and enlarge the image shape(such as `3x32x640` and so on).

https://github.com/PaddlePaddle/PaddleOCR/blob/e59177f07f2ab686e51bcd3f9cf7fe34b30b5e6e/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L19

https://github.com/PaddlePaddle/PaddleOCR/blob/e59177f07f2ab686e51bcd3f9cf7fe34b30b5e6e/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L75

https://github.com/PaddlePaddle/PaddleOCR/blob/e59177f07f2ab686e51bcd3f9cf7fe34b30b5e6e/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L95
