### ISSUE TITLE
小语种识别模型在c++部署后无法识别

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleOCR#2806]
paddleocr-2.0版本在windows vs2019上生成ocr_system.exe，并按照官方模型可以识别中文，但是替换了我自己训练的小语种模型后，并修改config.字典文件，执行exe没有结果。
![image](https://user-images.githubusercontent.com/41140837/118445553-2b1c2280-b721-11eb-911e-6256dc3c8eaf.png)
打印出label.size()是对的，但是打印出argmax_idx24003 max_value0.999992。这个argmax_idx应该是无法索引到label中。由于小语种的字典一行不是一个字符，泰文是多个字符堆叠作为一个字符的。不知道是不是这个原因。该如何修改。

**Comment by tink2123** [comment]
现在label list是多少呢？使用python预测可以得到正确结果吗？

**Comment by xiangfeidecao** [comment]
我的label list是7271，我看c++中特地加了两个是7273

**Comment by xiangfeidecao** [comment]
在python中是正常的。而且我调试了一下，argmax_idx中索引也是2万多。但是却能找到正确的标签。是因为python导入字典是用char.但是c++中是一行string导入的。导致了标签数不同。

**Comment by xiangfeidecao** [comment]
我在c++中调试发现。我的字典导入时，一行作为string导入时这个字符个数很奇怪，กั่ 这个对应的line.length()是9.

**Comment by tink2123** [comment]
可能是python和c++编码格式不同，看下c++读取字典时是不是utf-8呢？

**Comment by xiangfeidecao** [comment]
c++怎么设置，读取字典那里是github上的源码，没改过。    while (getline(in, line)) {
      m_vec.push_back(line);这里也没法设置吧

**Comment by xiangfeidecao** [comment]
为什么同样的字典文件（有个别行用\t结束的），python识别时不会把\t写到结果中，但是c++会把\t也写出来
> 可能是python和c++编码格式不同，看下c++读取字典时是不是utf-8呢？

**Comment by xiangfeidecao** [comment]
终于改完了。由于小语种的特殊字符一个字按照字符数量占三个到九个字节，而且‘\t’都计算到字典中。所以读取字典得每个字符分开存到字典中。
