### ISSUE TITLE
2.0及之后版本模型的benchmark麻烦更新下？

### ISSUE THREAD

**Issue by ConleyKong** [PaddlePaddle/PaddleOCR#2807]
看到最新docs_ch中的benchmark仅仅是针对1.x版本模型的效果，感觉挺差的，2.x之后的版本模型效果应该是提升了吧？能补充下benchmark结果吗？

**Comment by littletomatodonkey** [comment]
2.0版本的模型和和1.x版本的模型在精度方面基本一致哈，最主要的改变就是我们新增了动态图，方便用户调试。后续我们会开源精度更高、速度更快的模型的，敬请期待~

**Comment by ConleyKong** [comment]
嗯嗯，我看文档里好像写了，辛苦啦~
