### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleOCR#281]
尊敬的开发者，你好，我今天在Win10系统上面测试了一下进行文字识别，出现了下面的错误：

>   File "main.py", line 46, in main
>     text_thresh=0.5)  # 识别中文文本置信度的阈值；
>   File "C:\Users\46630\.paddlehub\modules\chinese_ocr_db_crnn_mobile\module.py", line 197, in recognize_text
>     images=predicted_data, use_gpu=self.use_gpu, box_thresh=box_thresh)
>   File "C:\Users\46630\.paddlehub\modules\chinese_text_detection_db_mobile\module.py", line 168, in detect_text
>     from chinese_text_detection_db_mobile.processor import DBPreProcess, DBPostProcess, draw_boxes, get_image_ext
>   File "C:\Users\46630\.paddlehub\modules\chinese_text_detection_db_mobile\processor.py", line 9, in <module>
>     from shapely.geometry import Polygon
>   File "E:\Path\Python\Anaconda3\envs\conda-general\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
>     from .base import CAP_STYLE, JOIN_STYLE
>   File "E:\Path\Python\Anaconda3\envs\conda-general\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
>     from shapely.coords import CoordinateSequence
>   File "E:\Path\Python\Anaconda3\envs\conda-general\lib\site-packages\shapely\coords.py", line 8, in <module>
>     from shapely.geos import lgeos
>   File "E:\Path\Python\Anaconda3\envs\conda-general\lib\site-packages\shapely\geos.py", line 145, in <module>
>     _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
>   File "E:\Path\Python\Anaconda3\envs\conda-general\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] 找不到指定的模块。

请问一下，这个该怎么进行设置呢？

**Comment by tink2123** [comment]
这个问题是因为shapely库安装有误，可以参考 #212 这个issue重新安装一下

**Comment by songyuc** [comment]
@tink2123 ，好的，谢谢你的解答！

**Comment by linlion0311** [comment]
> 

感謝~ 方法有用

**Comment by linlion0311** [comment]
> 这个问题是因为shapely库安装有误，可以参考 #212 这个issue重新安装一下

感謝~ 方法有用
