### ISSUE TITLE
paddlehub部署多并发问题

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2810]
在使用paddlehub部署时，use_multiprocess设置为false代表启不使用并发方式；当为true的时候使用多并发，有两个问题：
1、workers的数值设置为几就代表有几个并发吗？在config.json中默认设置值为2，是代表有2个并发吗？
2、默认为2*cpu_count-1时，workers是需要为空吗？

**Comment by MissPenguin** [comment]
1. 是的
2. 对，没有workers就用默认值，有值就以workers为准
