### ISSUE TITLE
有哪些开源手写OCR数据集

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#2814]
请问大家有使用过哪些开源手写OCR的中文数据集，听说有个HITHCD-2018数据集，但始终没找到下载链接。有链接的小伙伴能共享一下吗？先谢过。

**Comment by MissPenguin** [comment]
PaddleOCR整理的数据集中有一个中文手写数据集，可以看下是否能用上：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/handwritten_datasets.md#%E4%B8%AD%E7%A7%91%E9%99%A2%E8%87%AA%E5%8A%A8%E5%8C%96%E7%A0%94%E7%A9%B6%E6%89%80-%E6%89%8B%E5%86%99%E4%B8%AD%E6%96%87%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by guijuzhejiang** [comment]
@MissPenguin 谢谢，这个我用了，保存格式很多。都是单个字标注的。还是对HITHCD-2018念念不忘，得不到的永遠在騷動

**Comment by kyrie111** [comment]
> @MissPenguin 谢谢，这个我用了，保存格式很多。都是单个字标注的。还是对HITHCD-2018念念不忘，得不到的永遠在騷動

您好 请问您收集到了这个数据集嘛 我最近也在进行相关研究
