### ISSUE TITLE
请问数据前处理要怎么做

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#2817]
数据前处理对预测准确率会有提高，我想加入大律法二值化，灰度均衡和居中padding的前处理，请问要在哪里加入？配置yml文件能直接加入前处理吗？

**Comment by MissPenguin** [comment]
可以参考预处理中的[归一化操作](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/ppocr/data/imaug/operators.py#L60)增加自己的想要的预处理方法，写成class，然后在yml文件中的[transform](https://github.com/PaddlePaddle/PaddleOCR/blob/cb91cf3cd1f2048e540f7dd69cf799d96b9a6534/configs/det/det_mv3_db.yml#L69)下合适的位置增加相应配置进行调用。

**Comment by guijuzhejiang** [comment]
@MissPenguin 谢谢提供思路
