### ISSUE TITLE
paddle_inference2.0.2预测库部署 paddleocr编译异常

### ISSUE THREAD

**Issue by 746891300-org** [PaddlePaddle/PaddleOCR#2818]
paddle_inference下载地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

之前使用paddle_inference2.0.0官方预测库，paddleocr正常编译使用
现在下载了paddle_inference2.0.2版预测库，paddleocr编译异常了

这两个版本CMakeLists.txt文件做了如下更新：
if(WITH_STATIC_LIB)
    if(WIN32)
        set(DEPS
                ${PADDLE_LIB}/paddle/lib/paddle_inference${CMAKE_STATIC_LIBRARY_SUFFIX})
    else()
        set(DEPS
                ${PADDLE_LIB}/paddle/lib/libpaddle_inference${CMAKE_STATIC_LIBRARY_SUFFIX})
    endif()
else()
    if(WIN32)
        set(DEPS
                ${PADDLE_LIB}/paddle/lib/paddle_inference${CMAKE_SHARED_LIBRARY_SUFFIX})
    else()
        set(DEPS
                ${PADDLE_LIB}/paddle/lib/libpaddle_inference${CMAKE_SHARED_LIBRARY_SUFFIX})
    endif()
endif(WITH_STATIC_LIB)

**异常信息截取如下：**  （各文件的.o包都可以编译出来）

[100%] Linking CXX executable ocr_engine
/usr/local/paddle/paddle_inference/paddle/lib/libpaddle_inference.a(aes_cipher.cc.o)：在函数‘paddle::framework::AESCipher::BuildCipher(bool, bool*, CryptoPP::member_ptr<CryptoPP::SymmetricCipher>*, CryptoPP::member_ptr<CryptoPP::StreamTransformationFilter>*)’中：
aes_cipher.cc:(.text+0x64e)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
aes_cipher.cc:(.text+0x685)：对‘vtable for CryptoPP::SimpleKeyingInterface’未定义的引用
aes_cipher.cc:(.text+0x6a2)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0x719)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0x772)：对‘CryptoPP::BlockOrientedCipherModeBase::ResizeBuffers()’未定义的引用
aes_cipher.cc:(.text+0x7a4)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
aes_cipher.cc:(.text+0x929)：对‘vtable for CryptoPP::SimpleKeyingInterface’未定义的引用
aes_cipher.cc:(.text+0x948)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0x9ae)：对‘CryptoPP::CBC_Decryption::ResizeBuffers()’未定义的引用
aes_cipher.cc:(.text+0x9ea)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
aes_cipher.cc:(.text+0xa63)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
aes_cipher.cc:(.text+0xab1)：对‘vtable for CryptoPP::SimpleKeyingInterface’未定义的引用
aes_cipher.cc:(.text+0xad0)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0xb29)：对‘CryptoPP::BlockOrientedCipherModeBase::ResizeBuffers()’未定义的引用
aes_cipher.cc:(.text+0xb5b)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
aes_cipher.cc:(.text+0xbc9)：对‘vtable for CryptoPP::SimpleKeyingInterface’未定义的引用
aes_cipher.cc:(.text+0xbe8)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0xc41)：对‘CryptoPP::BlockOrientedCipherModeBase::ResizeBuffers()’未定义的引用
aes_cipher.cc:(.text+0xc7d)：对‘CryptoPP::StreamTransformationFilter::StreamTransformationFilter(CryptoPP::StreamTransformation&, CryptoPP::BufferedTransformation*, CryptoPP::BlockPaddingSchemeDef::BlockPaddingScheme)’未定义的引用
/usr/local/paddle/paddle_inference/paddle/lib/libpaddle_inference.a(aes_cipher.cc.o)：在函数‘paddle::framework::AESCipher::EncryptInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
aes_cipher.cc:(.text+0xe18)：对‘CryptoPP::g_nullNameValuePairs’未定义的引用
aes_cipher.cc:(.text+0xe7b)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0xe82)：对‘vtable for CryptoPP::StringSinkTemplate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’未定义的引用
aes_cipher.cc:(.text+0xed9)：对‘CryptoPP::Algorithm::Algorithm(bool)’未定义的引用
aes_cipher.cc:(.text+0xee0)：对‘vtable for CryptoPP::Redirector’未定义的引用
aes_cipher.cc:(.text+0xf34)：对‘vtable for CryptoPP::Filter’未定义的引用
aes_cipher.cc:(.text+0x1058)：对‘CryptoPP::SimpleKeyingInterface::SetKeyWithIV(unsigned char const*, unsigned long, unsigned char const*, unsigned long)’未定义的引用

**Comment by 746891300-org** [comment]
您好，我下载的是mkl cpu版，代码是同步dygraph分支的

**Comment by LDOUBLEV** [comment]
> 您好，我下载的是mkl cpu版，代码是同步dygraph分支的

mkl cpu版本的[预测库](https://paddle-inference-lib.bj.bcebos.com/2.0.2-cpu-noavx-openblas/paddle_inference.tgz) + dygraph分支的代码验证了也没问题的；

**Comment by 746891300-org** [comment]
问题找到了，
option(WITH_STATIC_LIB "Compile demo with static/shared library, default use static."   OFF)
这个参数要设置为动态库，不能用静态库编译了

**Comment by LDOUBLEV** [comment]
在编译的时候tools/build.sh 里可以通过 -DWITH_STATIC_LIB=OFF 参数设置是否用关闭静态图
