### ISSUE TITLE
关于合成数据的问题

### ISSUE THREAD

**Issue by jeejeeli** [PaddlePaddle/PaddleOCR#282]
您好：
非常感谢您们开源OCR算法，OCR小白，对您们的文档描述“使用LSVT街景数据集根据真值将图crop出来30w数据，进行位置校准。此外基于LSVT语料生成500w合成数据训练中文模型，”有一些疑问：
1. “crop出来30w数据，进行位置校准”是怎么进行位置校准的呢
2. “LSVT语料生成500w合成数据”是怎么合成数据的，有什么参考的方法吗，或者提供500W合成数据的数据集下载地址吗？
希望得帮忙解答下，非常感谢~

**Comment by tink2123** [comment]
1. 位置校准，即对歪曲的4点框进行转正，可以参考 #221 的描述
2. 合成数据暂时无法提供下载链接，中文合成工具使用的是：[text_render](https://github.com/Sanster/text_renderer) ，合成数据语料来自于LSVT，更多关于数据集的内容可阅读：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/datasets.md

**Comment by jeejeeli** [comment]
非常感谢

**Comment by Sanster** [comment]
@tink2123 你好，想问下合成的数据有做字符的平衡么？例如比较低频的字是否有做特殊的采样处理
