### ISSUE TITLE
请问文本识别的预训练模型，还有其他的嘛？

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#2822]
![image](https://user-images.githubusercontent.com/52873355/118620049-bbc53200-b7f7-11eb-84c5-57eaece74c04.png)

**Comment by MissPenguin** [comment]
中文的有mobile版和server版：
![image](https://user-images.githubusercontent.com/25809855/118645231-3d758980-b811-11eb-93ee-f48c909989b3.png)

更多的识别模型可以看[模型下载](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md#%E4%BA%8C%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B)页面，里面还有英文和支持80种语言的多语言识别模型。

**Comment by PhilCuriosity** [comment]
> 中文的有mobile版和server版：
> ![image](https://user-images.githubusercontent.com/25809855/118645231-3d758980-b811-11eb-93ee-f48c909989b3.png)
> 
> 更多的识别模型可以看[模型下载](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md#%E4%BA%8C%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B)页面，里面还有英文和支持80种语言的多语言识别模型。

模型列表中的预训练模型是不是已经把输入输出固定死了？我需要自定义字典去训练，不知道是否可以？mobile模型和server模型模型大小中间过度太大了，有没有50M左右的模型？
![image](https://user-images.githubusercontent.com/52873355/118750149-73f2e900-b891-11eb-9443-9f64c5287dd8.png)
![image](https://user-images.githubusercontent.com/52873355/118750227-984ec580-b891-11eb-9596-330440480a78.png)
