### ISSUE TITLE
CPU下的inference效率稍微有点低啊，发票检测时一张图片平均耗时6s左右

### ISSUE THREAD

**Issue by ConleyKong** [PaddlePaddle/PaddleOCR#2825]
有什么能够提升CPU下处理效率的方式吗

**Comment by LDOUBLEV** [comment]
加速方法：
- 开启mkldnn
- 设置rec_batch_num=6 # 根据情况调整
- 如果使用paddle 2.1版本，尝试开启interpolate_mkldnn pass，[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/a499f048d0bcc370be7d463f27ec6d26ee484b62/tools/infer/utility.py#L158)增加如下代码：
```
pass_builder = config.pass_builder()
pass_builder.append_pass("interpolate_mkldnn_pass")
```



发票上文本框比较多，处理时间会比较长；

是否方便发一张你的测试图让我测试下？
