### ISSUE TITLE
请问paddleocr中断后继续训练，为什么epoch又是从0开始？

### ISSUE THREAD

**Issue by dychb** [PaddlePaddle/PaddleOCR#2827]
![AMR{%LJ__VK_MOW9JN{VC41](https://user-images.githubusercontent.com/59058681/118669300-3c9c2200-b828-11eb-9b4c-5a4870bc4797.png)
然后模型的保存又是从头开始，要是中断多次了的话，都不知道模型已经训练多少次了

**Comment by LDOUBLEV** [comment]
epoch这个参数不是一个tensor，训练的时候不会保存在模型参数里，如果在中断训练前保存了best_accuracy模型，best_accuracy.states这个文件里存放的有当前的epoch和best_acc 信息

另外，看你的totalloss比较小，是成功加载了训练好的模型，实际上是从epoch 40后接续训练的，只不过epoch=0

**Comment by dychb** [comment]
![LG~T7XY} 93D_J4ZWM6(YD2](https://user-images.githubusercontent.com/59058681/118785767-c3520d00-b8c3-11eb-894b-07419af825d1.png)
还有一个问题就是这个学习率我已经改成了0.0001了，但是下面显示的还是0.001，这只是显示的问题还是说学习率并没有改变（在配置文件里修改学习率我也试过了，也是一样）

![L)@WVVIC444S0$R(`@NWV60](https://user-images.githubusercontent.com/59058681/118786807-c3064180-b8c4-11eb-9f4f-865ee96103ad.png)

**Comment by LDOUBLEV** [comment]
明白你的问题了，这个问题是由于你用的checkpoints加载的模型，checkpoints中保存了你上次训练的学习率，所以重新设置学习率后没有起作用，有两个解决方法：
1. 使用Global.pretrained_model加载模型，默认不加载优化器相关参数
2. [这里](https://github.com/PaddlePaddle/PaddleOCR/blob/6a63ac7d7fa8cafa2b7323ba3c14249b67e3e9de/ppocr/utils/save_load.py#L93)修改加载的opt_dict里的学习率数据，opt_dict是个字典，可以把学习率读取出来，手动修改；

**Comment by dychb** [comment]
好的，谢谢解答
