### ISSUE TITLE
关于单字和多字检测识别的区别

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#2828]
关于多字的识别原理不是很清楚。
单字识别的原理很好理解，先检测出单字位置，再用字典识别出具体是哪个字。
但多字被检测出位置后，应该也是分割成单字，然后识别单字，在字典中找到匹配的单字，再用CTC对齐的吧？
请问是这样理解吗？

**Comment by guijuzhejiang** [comment]
我训练的模型是这样：
1，检测模型用的是多字标注（单字标注太麻烦），必然检测到的是多字结果
2，识别模型用的是开源单字训练的。
问题：
多字检测模型输出的多字，作为单字识别模型的输入，文字是否会被正确识别？

**Comment by LDOUBLEV** [comment]
可以先去网上找资料看看


> 问题： 多字检测模型输出的多字，作为单字识别模型的输入，文字是否会被正确识别？

这就取决于你的单字识别模型是否能支持识别多字了

**Comment by guijuzhejiang** [comment]
> 可以先去网上找资料看看
> 
> > 问题： 多字检测模型输出的多字，作为单字识别模型的输入，文字是否会被正确识别？
> 
> 这就取决于你的单字识别模型是否能支持识别多字了

单字模型顾名思义就是只用单字训练出来的识别模型，你的意思是说只用单字训练出来的模型不能识别检测出多字的情况是吗？

**Comment by guijuzhejiang** [comment]
我看项目给出的中文字典里（ppocr_keys_v1.txt）也都是单个字的，没有多字情况。也就是说识别模型最后的分类层都是按字典中的单字分类的吧。如果成立，说明检测模型给出多字作为识别模型输入后，也是分割成单字识别的吧？

**Comment by chocolate-byte** [comment]
文本检测算法里按理说有图像分割

**Comment by chocolate-byte** [comment]
文本检测算法里按理说有图像分割

**Comment by chocolate-byte** [comment]
predict_dec.py有阈值处理，cv2.findContour就是分割位置，但是阈值是在predict_db_head里面一个神经网络算出来的

**Comment by DoiiarX** [comment]
我在这里留个传送门。找单字识别的走这条。我最近查资料经常走错。留个传送门给后人。。。

https://github.com/PaddlePaddle/PaddleOCR/issues/10377
