### ISSUE TITLE
如果想用PGNET,输出角度angle的话，应该改哪部分代码

### ISSUE THREAD

**Issue by Harrison410-web** [PaddlePaddle/PaddleOCR#2832]

**Comment by LDOUBLEV** [comment]
Pgnet没有计算文本角度信息，可以尝试利用输出的检测框计算倾斜角度

**Comment by Harrison410-web** [comment]
谢谢你回复，我就是使用了检测框来计算角度，但是角度相同的情况下，文字可能存在正反的情况，就不知道怎么处理了。想问问那个方向训练器具体作用是什么，可以输出具体角度吗？

**Comment by Harrison410-web** [comment]
> Pgnet没有计算文本角度信息，可以尝试利用输出的检测框计算倾斜角度

谢谢你回复，我就是使用了检测框来计算角度，但是角度相同的情况下，文字可能存在正反的情况，就不知道怎么处理了。想问问那个方向训练器具体作用是什么，可以输出具体角度吗？

**Comment by LDOUBLEV** [comment]
文字方向分类器就是对文字方向分类的，你可以根据检测框求一个最小包围矩形框，然后把最小包围矩形框里的文本输入给文字方向分类器，进而得到一个文字角度，0 or 180

**Comment by Harrison410-web** [comment]
好的。我去试试，谢谢你了
