### ISSUE TITLE
如果是盖章类，怎么识别

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2833]
盖章类  360度方向  都有

字母 + 数字

这种要怎么训练

**Comment by LDOUBLEV** [comment]
可以尝试PGNet算法 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/pgnet.md

**Comment by monkeycc** [comment]
好的 谢谢
