### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2834]
**python3 PPOCRLabel.py --lang ch**

Found metadata in lib /home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}

QLibraryPrivate::loadPlugin failed on "/home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-util.so.1: 无法打开共享对象文件: 没有那个文件或目录)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621411128 (unix time) try "date -d @1621411128" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800003e03) received by PID 15875 (TID 0x7fd0d8cc5740) from PID 15875 ***]

已放弃

**Comment by Evezerest** [comment]
这是在linux平台下吗？

**Comment by ccl-private** [comment]
我也遇到了，linux
