### ISSUE TITLE
lstm 提取语义

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#2836]
您好， 我使用的develop分支代码， 训练crnn模型。我的数据中是含有语义信息的（但是为了提高某些字的字频，就将这些字随机排列然后生成了一批图片，约占训练集的1/60），而且数据量很大。模型在我的验证集上也到了96%的准确率， 但是在测试时， 总感觉这个lstm部分没有提取到相应的语义信息，例如“牛皮癣” 会被识别成 “牛皮癖”， 这种情况需要怎么优化？
![image](https://user-images.githubusercontent.com/61573829/118797451-2e551100-b8cf-11eb-83a6-469d9e24c32b.png)
![image](https://user-images.githubusercontent.com/61573829/118797491-390fa600-b8cf-11eb-8d30-6c69aa4ab6ca.png)

![image](https://user-images.githubusercontent.com/61573829/118797658-69574480-b8cf-11eb-91ed-4dd5b3855ffe.png)
![image](https://user-images.githubusercontent.com/61573829/118797689-707e5280-b8cf-11eb-9242-ce679138736b.png)

**Comment by tink2123** [comment]
应该是因为训练数据中 “癣” 这个字出现的次数较少，可以分析一下训练数据的词频，有针对性的增加一些生僻字数据

**Comment by Zhangts98** [comment]
> 应该是因为训练数据中 “癣” 这个字出现的次数较少，可以分析一下训练数据的词频，有针对性的增加一些生僻字数据

训练数据中每个字的字频都在5000以上，有的上万。
