### ISSUE TITLE
PGNet 怎么调整 方向分类-['0','90','180','270','320']

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2838]
官方文档
label_list | 设置方向分类器支持的角度 | ['0','180'] | 仅在方向分类器中生效
-----------------
Global:
  label_list:['0','90','180','270','320']

我在Global中增加，报错

因为我的是印章类  360度方向都会有   不固定位置   
字母+数字
比如     AA123456    XX   2021/05    BB23456

我这种 应该在哪里设置方向分类，实现360度的读取我上面的字

**Comment by tink2123** [comment]
PGNet不需要方向分类器，这是端到端的算法。方向分类器是两阶段的检测+分类使用的。
