### ISSUE TITLE
图像旋转90° 文本检测可以正常检测到具体文本位置，但是识别准确度大幅降低 是否会考虑增加相应的旋转预处理？

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#284]

**Comment by tink2123** [comment]
可以麻烦具体描述一下问题吗？方便的话请提供一下
原始图片：
旋转后图片：
旋转后的识别效果：

**Comment by bikerr** [comment]
先后测试效果，采用的官网提供的身份证图片 
![image](https://user-images.githubusercontent.com/14155359/86442784-e07bfc80-bd40-11ea-96c1-b9553e5128e5.png)
![image](https://user-images.githubusercontent.com/14155359/86442794-e4a81a00-bd40-11ea-8561-3ae7ae56bb2e.png)

**Comment by tink2123** [comment]
目前模型只支持两种方向的文字：水平和垂直。 为了降低模型大小，加快模型预测速度，PaddleOCR暂时没有加入图片的方向判断。您的这种情况，可以在图片送入模型之前转正吗？

**Comment by tink2123** [comment]
上述图片可以尝试下顺时针旋转90度，顺时针的旋转不会影响效果。

**Comment by bigvine2** [comment]
旋转的问题百度ocr接口一直都存在这个问题，接口中选择了检测方向选项，但是结果还是不如自己进行旋转后识别效果好，个人猜测是算法中对文本框的方向和文字识别同时进行了处理，所以在识别流程中忽略了对图像整体的旋转，但事实上还是旋转之后再识别效果更好（为了解决该问题我自己训练了一个检测图片文字方向的模型）

**Comment by tink2123** [comment]
使用一个模型支持多方向文字识别仍有难度，如对模型大小和运行速度要求不高，添加一个方向分类器是很好的解决方案。

**Comment by itscarrot** [comment]
可以用vgg来判断文字方向

**Comment by myfjdthink** [comment]
> 可以用vgg来判断文字方向

请问有没有现成的模型可以使用？

**Comment by itscarrot** [comment]
> > 可以用vgg来判断文字方向
> 
> 请问有没有现成的模型可以使用？

[chineseocr](https://github.com/chineseocr/chineseocr)里面有一个vgg16 可以判断文字方向

**Comment by Hupengyu** [comment]
> > > 可以用vgg来判断文字方向
> > 
> > 
> > 请问有没有现成的模型可以使用？
> 
> [chineseocr](https://github.com/chineseocr/chineseocr)里面有一个vgg16 可以判断文字方向

这个chineseocr里的可以和paddle合在一起吗？框架不一样啊，而且paddle的模型类型也和他的不一样，难道是先用chineseocr识别方向后再放入paddle的det里吗？感觉那样就会很慢啊

**Comment by tink2123** [comment]
@Hupengyu  PaddleOCR 中提供了方向分类器模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/angle_class.md

**Comment by itscarrot** [comment]
> > > > 可以用vgg来判断文字方向
> > > 
> > > 
> > > 请问有没有现成的模型可以使用？
> > 
> > 
> > [chineseocr](https://github.com/chineseocr/chineseocr)里面有一个vgg16 可以判断文字方向
> 
> 这个chineseocr里的可以和paddle合在一起吗？框架不一样啊，而且paddle的模型类型也和他的不一样，难道是先用chineseocr识别方向后再放入paddle的det里吗？感觉那样就会很慢啊

不是，需要自己处理耦合。提问的时候paddleocr没有方向分类器，现在已经有了。如果你自己有图片，可以旋转各种角度后自己训练一个分类模型，针对自己的场景效果会比较好。

**Comment by Hupengyu** [comment]
> @Hupengyu PaddleOCR 中提供了方向分类器模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/angle_class.md

当前的2.0只有[0, 180]的，90的没有，这个我要自己训练吧？是不是要改一些网络参数？

**Comment by Hupengyu** [comment]
> > > > > 可以用vgg来判断文字方向
> > > > 
> > > > 
> > > > 请问有没有现成的模型可以使用？
> > > 
> > > 
> > > [chineseocr](https://github.com/chineseocr/chineseocr)里面有一个vgg16 可以判断文字方向
> > 
> > 
> > 这个chineseocr里的可以和paddle合在一起吗？框架不一样啊，而且paddle的模型类型也和他的不一样，难道是先用chineseocr识别方向后再放入paddle的det里吗？感觉那样就会很慢啊
> 
> 不是，需要自己处理耦合。提问的时候paddleocr没有方向分类器，现在已经有了。如果你自己有图片，可以旋转各种角度后自己训练一个分类模型，针对自己的场景效果会比较好。

当前的2.0只有[0, 180]的，90的没有，这个我要自己训练吧？是不是要改一些网络参数？

**Comment by fengmy** [comment]
> > > > > > > 可以用vgg来判断文字方向
> > > > > > 
> > > > > > 
> > > > > > 请问有没有现成的模型可以使用？
> > > > > 
> > > > > 
> > > > > [chineseocr](https://github.com/chineseocr/chineseocr)里面有一个vgg16 可以判断文字方向
> > > > 
> > > > 
> > > > 这个chineseocr里的可以和paddle合在一起吗？框架不一样啊，而且paddle的模型类型也和他的不一样，难道是先用chineseocr识别方向后再放入paddle的det里吗？感觉那样就会很慢啊
> > > 
> > > 
> > > 不是，需要自己处理耦合。提问的时候paddleocr没有方向分类器，现在已经有了。如果你自己有图片，可以旋转各种角度后自己训练一个分类模型，针对自己的场景效果会比较好。
> > 
> > 
> > 当前的2.0只有[0, 180]的，90的没有，这个我要自己训练吧？是不是要改一些网络参数？
> 
> 如果需要90、270甚至更多的角度，需要自己训练，这是一个图片分类任务，你可以用paddlecls或者其他框架进行训练。另外，你是判断整张图片的角度，还是文本检测后扣取的局部文本图片的角度？如果是后者，根据我自己的经验，最终训练出来模型性能还是很好的，但是前者的话，入模的图片需要做一些预处理，比如对齐，才能取得比较好的效果。

搞个关键点检测，做透视变换矫正到水平就可以了。

**Comment by UnstoppableCurry** [comment]
paddleclas 里面有一个官方 4个角度 文本回归的项目
