### ISSUE TITLE
关于db模型，进行finetune时遇到的问题

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleOCR#2841]
在检测任务中，我的训练图片尺寸都是手机截图，想修改一下resaize尺寸，请问在配置文件中哪里修改？
![image](https://user-images.githubusercontent.com/41312357/118914239-70c52f00-b95d-11eb-9de5-daee8c9f2f78.png)
是在这里吗？

**Comment by tink2123** [comment]
是的
