### ISSUE TITLE
ModuleNotFoundError: No module named 'gast'  按照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/quickstart.md  下的以超轻量级模型为例  进行测试出现

### ISSUE THREAD

**Issue by yifanzhang666777** [PaddlePaddle/PaddleOCR#2842]
pip list 显示有 gast 0.3.3   但是运行时就是出现ModuleNotFoundError: No module named 'gast'

**Comment by xmy0916** [comment]
> pip list 显示有 gast 0.3.3   但是运行时就是出现ModuleNotFoundError: No module named 'gast'
需要确保这个包安装到了同一个python下，可以用python3 -m pip install来确保安装到了python3下，或者python的绝对路径 -m pip install xxx

**Comment by yifanzhang666777** [comment]
> python3 -m pip install
可以的
