### ISSUE TITLE
PGNet数据集任意点标注出错

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#2843]
请问训练时每张图片有多个标注的时候，标注的的点数不一样会报错：
![image](https://user-images.githubusercontent.com/33149964/118928875-65cac880-b976-11eb-840f-c61db92e05a9.png)
使用插值之后，扩充到14个点又会出点问题：
![image](https://user-images.githubusercontent.com/33149964/118928996-87c44b00-b976-11eb-875a-1f1918641843.png)
而且loss会变得挺高的，请问是什么原因呢
而且求问能不能把每个图片标注的点数改为任意点呢

**Comment by chujian521** [comment]
看了一下源代码，这个报错是因为插值导致产生某些点共线，会影响TBO模块，会影响后面的训练嘛？

**Comment by LDOUBLEV** [comment]
PaddleOCR 中的 pgnet训练需要用14点数据，扩充点时也要注意点的方向，从左到右

**Comment by tjpulfn** [comment]
请问怎么扩充点
