### ISSUE TITLE
PaddleOCR动态图移动端部署

### ISSUE THREAD

**Issue by Fei-dong** [PaddlePaddle/PaddleOCR#2844]
移动端使用paddle-lite_v2.9版本，写的比较好的字，在移动端识别错误得分很低，pc端识别正确，得分也很高，这种情况可能是什么原因导致的？有没有可能是库输出问题，lite输出部分代码没有选择得分最高的那个值？

**Comment by tink2123** [comment]
可以提供一下这个bad case吗？ lite部分输出逻辑和pc是一致的，都是会取得分最高的结果。可能是前后处理有diff导致预测结果不同。

**Comment by Fei-dong** [comment]
> 可以提供一下这个bad case吗？ lite部分输出逻辑和pc是一致的，都是会取得分最高的结果。可能是前后处理有diff导致预测结果不同。

非常感谢回复，我用自己准备的数据重新训练了模型，我再确认一下前后处理吧。
