### ISSUE TITLE
paddleocr  命令行模式 bash: paddleocr: command not found

### ISSUE THREAD

**Issue by yifanzhang666777** [PaddlePaddle/PaddleOCR#2845]
看见paddleocr 测试时候可以进行命令行模式进行   我现在直接运行会报 bash: paddleocr: command not found错  需要配置什么吗

**Comment by tink2123** [comment]
需要先安装 paddleocr， 请参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/whl.md
