### ISSUE TITLE
paddlepaddle ==2.0.1    AttributeError: module 'paddle' has no attribute 'seed 

### ISSUE THREAD

**Issue by yifanzhang666777** [PaddlePaddle/PaddleOCR#2847]
paddlepaddle 已经为2.0.1 但是还是出现AttributeError: module 'paddle' has no attribute 'seed

**Comment by tink2123** [comment]
确认升级成功了吗？
python 进入解释器：
import  paddle
paddle.__version__ 

查看下paddle版本呢
