### ISSUE TITLE
SAST弯曲文本检测模型推理速度和效果问题

### ISSUE THREAD

**Issue by siqiaof** [PaddlePaddle/PaddleOCR#2848]
我从 https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_sast_totaltext_v2.0_train.tar 下载了预训练模型。转换成了推理模型，并按如下命令推理 

python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img623.jpg" --det_model_dir="./inference/det_sast_tt/" --det_sast_polygon=True

然而单次推理耗时大概二十多分钟，且结果也很差，不知道是哪里出了问题。

![det_res_img623](https://user-images.githubusercontent.com/67352303/118961093-860a7f80-b996-11eb-8667-8e42f4ad6217.jpg)

CPU 型号：Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz   3.00 GHz
GPU 型号：Nvidia GTX 1650
Paddlepaddle 版本：2.0 GPU

**Comment by tink2123** [comment]
转换和推理是否是按这个命令来的呢：
```
python3 tools/export_model.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.pretrained_model=./det_r50_vd_sast_icdar15_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_ic15
```
```
python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_sast_ic15/"
```

**Comment by siqiaof** [comment]
> 转换和推理是否是按这个命令来的呢：
> 
> ```
> python3 tools/export_model.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.pretrained_model=./det_r50_vd_sast_icdar15_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_ic15
> ```
> 
> ```
> python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_sast_ic15/"
> ```

是按照弯曲文本检测的转换和推理
`python3 tools/export_model.py -c configs/det/det_r50_vd_sast_totaltext.yml -o Global.pretrained_model=./det_r50_vd_sast_totaltext_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_tt
`

`python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img623.jpg" --det_model_dir="./inference/det_sast_tt/" --det_sast_polygon=True
`

**Comment by tink2123** [comment]
试下拉取最新的release/2.1分支代码吧，自测没有问题，无法复现你的报错

**Comment by siqiaof** [comment]
> 试下拉取最新的release/2.1分支代码吧，自测没有问题，无法复现你的报错

谢谢您，我再尝试一下
