### ISSUE TITLE
Bus error(core dump) 

### ISSUE THREAD

**Issue by kaywangdong** [PaddlePaddle/PaddleOCR#285]
Bus error(core dump)

**Comment by littletomatodonkey** [comment]
您的系统是什么呢？建议您在docker中运行PaddleOCR，排除环境问题。

**Comment by kaywangdong** [comment]
ubuntu18.04, docker也试过了，都不行，同样的配置环境，在另一台机器上能用，但是这台机器就是不行

**Comment by littletomatodonkey** [comment]
您这台机器的磁盘空间是否已满呢？
