### ISSUE TITLE
模型保存加载问题

### ISSUE THREAD

**Issue by Harrison410-web** [PaddlePaddle/PaddleOCR#2853]
能否？例如我训练一个det模型，能否直接保存模型，加载后使用，而不是每次都需要init_model

**Comment by Harrison410-web** [comment]
另外，我出现了一个问题，问题描述如下： parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers
因为我在代码中用到了cls和det两种模型，在初始化模型的时候就会出现这个问题

**Comment by Harrison410-web** [comment]
求好心大佬帮忙解释一下，感激不尽

**Comment by WenmuZhou** [comment]
在paddle里，训练引擎的推理是不允许存在两个相同的变量的，你这种情况，建议适应inference的推理也就是predict_xxx
