### ISSUE TITLE
文字识别的CTC解码问题

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2857]
你好，文字识别模型模型的输出矩阵需要进行解码才能得到识别的文本。我看代码中实现为preds_idx = preds.argmax(axis=2)，也就是最佳路径解码法。这是一种贪心算法，是每一个时间步只将最大概率的字符作为当前时间步的预测输出，但得到的结果不一定是最好的。为什么不使用beam search这种方式进行解码呢？

**Comment by WenmuZhou** [comment]
因为这样快，acc也差别不大

**Comment by lalalagogogochong** [comment]
> 你好，文字识别模型模型的输出矩阵需要进行解码才能得到识别的文本。我看代码中实现为preds_idx = preds.argmax(axis=2)，也就是最佳路径解码法。这是一种贪心算法，是每一个时间步只将最大概率的字符作为当前时间步的预测输出，但得到的结果不一定是最好的。为什么不使用beam search这种方式进行解码呢？

如果采用beam search，最终选出多条最优路径的话，用什么策略取最优结果呢，如果是取得分最高的，也是按照概率大小来计算得分，结果和贪婪解码是一样的吧。

**Comment by ZhangChaoZhong** [comment]
> 
维比特算法可以找到最优，可以去网上找找。
Beam Search的复杂度是介于贪心算法和维比特算法之间。
贪心算法：O（1*N*T）
Beam Search：O（k*N*T）
维比特算法：O（N*N*T）
