### ISSUE TITLE
Linux系统下使用pycharm运行paddleocr时，强制停止程序Linux系统闪退。

### ISSUE THREAD

**Issue by Hkey-done** [PaddlePaddle/PaddleOCR#2858]
Linux系统下使用pycharm运行paddleocr时，强制停止程序会导致Linux系统闪退，变为注销状态。同样代码在win10系统下使用正常。忘修复，谢谢。
测试环境：
Linux系统： deepin20.2及优麒麟20.4 （win10正常）
运行程序： pycharm（ Linux最新社区版本 ）
Python版本： anaconda3 python3.7.10
paddlepaddle版本：conda Linux CPU 2.1.0
paddleocr版本： 2.0.6
CPU，GPU模式都会出现

**Comment by WenmuZhou** [comment]
这个在paddle下已经有issue了,https://github.com/PaddlePaddle/Paddle/issues/29845 建议关注这个
