### ISSUE TITLE
进程存在，训练无故停止

### ISSUE THREAD

**Issue by chunniunai220ml** [PaddlePaddle/PaddleOCR#2860]
训练east模型的进程存在，numwork=8，但是训练无故停止，trainlog也没有输出，大家有遇到过这种情况吗？

环境：
conda+Quadro RTX 600, 以前没有遇到过，最近频繁这样，代码也跟着更新至2.1版本了

**Comment by WenmuZhou** [comment]
训练其他的算法也会这样吗

**Comment by xuxiaobao-3** [comment]
我也是  进程还在 就是突然停止了

**Comment by chunniunai220ml** [comment]
> 训练其他的算法也会这样吗

别的还没有训练呢，之前2.0没有这个问题
