### ISSUE TITLE
最新版本数字明显识别错误

### ISSUE THREAD

**Issue by coderchuan** [PaddlePaddle/PaddleOCR#2861]
会将整个文本旋转180度，导致6识别为9，9识别为6，4识别为7，这样的话用confidence来判断结果是否可信就完全行不通了。能否在返回的数据中加入文本旋转的角度，这个我们就可以通过这个角度结合confidence来判断结果是否可靠 
![test](https://user-images.githubusercontent.com/44311500/119087081-17cac900-ba39-11eb-870f-ccafa094fcc7.jpg)

模型：chinese_ocr_db_crnn_server

识别结果为
```
[{'save_path': '', 'data': [{'text': '667-687', 'confidence': 0.9987493753433228, 'text_box_position': [[216, 133], [538, 133], [538, 207], [216, 207]]}]}]
```

**Comment by WenmuZhou** [comment]
有返回角度需求的话，可以自行修改 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/predict_system.py#L119 将angle_list返回

**Comment by coderchuan** [comment]
好像没有作用

**Comment by coderchuan** [comment]
> 有返回角度需求的话，可以自行修改 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/predict_system.py#L119 将angle_list返回

好像没有作用，能贴下代码吗？
