### ISSUE TITLE
用自己的数据集训练识别模型时打标签的问题

### ISSUE THREAD

**Issue by zjy614** [PaddlePaddle/PaddleOCR#2864]
训练自己的数据集时，有的标签不想加入训练集，需要在标签文件label.txt剔除该条目吗，发现仅仅在字典文件不加这些字训练出的模型会造成这些样本识别错误。

**Comment by WenmuZhou** [comment]
需要从label.txt剔除

**Comment by zjy614** [comment]
谢谢
