### ISSUE TITLE
自己数据集finetune的问题

### ISSUE THREAD

**Issue by wfdubowen** [PaddlePaddle/PaddleOCR#2866]
文本识别CRNN中，如果对原模型准确率影响不大的情况下，在某一领域finetune自己的数据集的话，自己准备的这部分数据集的量级大概是多少呢？还是在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响呢？

**Comment by WenmuZhou** [comment]
在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响

**Comment by YY007H** [comment]
> 准备通用中英文的部分数据

准备通用中英文的部分数据大概是多少呢？或者是哪个的数据集呢？

**Comment by WenmuZhou** [comment]
和finetune的数据集差不多大吧

**Comment by YY007H** [comment]
> 和finetune的数据集差不多大吧

一般finetune的数据集都不会太大，比如加个新字符也就一两千条数据，这种情况下也准备和finetune的数据集差不多大的吗？

**Comment by wfdubowen** [comment]
有没有一些通用中英文公开数据集推荐呢？

**Comment by YY007H** [comment]
> 有没有一些通用中英文公开数据集推荐呢？

上面那位大佬整理的有个公开数据集地址https://github.com/WenmuZhou/OCR_DataSet.git

**Comment by mybrew** [comment]
> 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响

你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？

**Comment by YY007H** [comment]
> > 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响
> 
> 你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？

我尝试过，是这样的，不加入通用的中英文，只训练自己的数据，训练的越久遗忘的越多，但加入通用的训练又非常慢

**Comment by pingzi5233** [comment]
> > > 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响
> > 
> > 
> > 你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？
> 
> 我尝试过，是这样的，不加入通用的中英文，只训练自己的数据，训练的越久遗忘的越多，但加入通用的训练又非常慢

那最后请问是采取了哪种训练方式呢？加入同数量的通用文本数据集还是加入全部的？

**Comment by YY007H** [comment]
> > > > 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响
> > > 
> > > 
> > > 你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？
> > 
> > 
> > 我尝试过，是这样的，不加入通用的中英文，只训练自己的数据，训练的越久遗忘的越多，但加入通用的训练又非常慢
> 
> 那最后请问是采取了哪种训练方式呢？加入同数量的通用文本数据集还是加入全部的？

我加入了百度语料库的20万条数据进行训练，不确定最少需要加入多少数据

**Comment by pingzi5233** [comment]
> > > > > 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响
> > > > 
> > > > 
> > > > 你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？
> > > 
> > > 
> > > 我尝试过，是这样的，不加入通用的中英文，只训练自己的数据，训练的越久遗忘的越多，但加入通用的训练又非常慢
> > 
> > 
> > 那最后请问是采取了哪种训练方式呢？加入同数量的通用文本数据集还是加入全部的？
> 
> 我加入了百度语料库的20万条数据进行训练，不确定最少需要加入多少数据

效果如何啊？你的特定场景的数据集大概在多少量？

**Comment by YY007H** [comment]
> > > > > > 在finetune过程中必须要准备通用中英文的部分数据，跟某一领域的一起训练才不会对原模型的通用识别精度造成影响
> > > > > 
> > > > > 
> > > > > 你好，如果准备了通用中英文的部分数据一起训练后，是不是没有加入的通用中英文字符识别效果就不好了？等于说微调训练出来的模型基本上只适用于训练过的特定数据吗？
> > > > 
> > > > 
> > > > 我尝试过，是这样的，不加入通用的中英文，只训练自己的数据，训练的越久遗忘的越多，但加入通用的训练又非常慢
> > > 
> > > 
> > > 那最后请问是采取了哪种训练方式呢？加入同数量的通用文本数据集还是加入全部的？
> > 
> > 
> > 我加入了百度语料库的20万条数据进行训练，不确定最少需要加入多少数据
> 
> 效果如何啊？你的特定场景的数据集大概在多少量？

数据量不多也就才2000多条，目前已经跑到了acc 80%

**Comment by pingzi5233** [comment]
>数据量不多也就才2000多条，目前已经跑到了acc 80%

这个准确率是在训练的时候的吗？实际测试效果怎么样？特定场景以及通用场景？
