### ISSUE TITLE
paddleOCR可以在windows可以使用C++多进程部署吗？

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#2869]
平台windows, AMD Ryzen 5 1600X Six-Core Processor ,CUDA10.1
paddleOCR在windows上有类似于python多进程部署（--use_mp=True --total_process_num=6）对应的C++版本吗？
1.在Paddle Inference的C++API中，有对应的多进程接口吗？

2.在PaddleOCR C++部署方案中，使用时opencv是非CUDA版的，是否可以使用CUDA编译版本的opencv，进一步提高字符检测和推理识别速度？

**Comment by WenmuZhou** [comment]
https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/Config/GPUConfig.html  参考这个
