### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by kaywangdong** [PaddlePaddle/PaddleOCR#287]
CUDA10.1, cudnn-10.1-linux-x64-v7.6.5.32
![微信图片_20200706104718](https://user-images.githubusercontent.com/17980830/86551034-88c6d680-bf76-11ea-9107-4084127de984.jpg)

**Comment by phlrain** [comment]
从log 来看，像是获取cudnn的一个handle的时候出错了， 你看下cudnn版本啥的么

**Comment by kaywangdong** [comment]
cudnn的版本就是7.6.5

**Comment by kaywangdong** [comment]
这个问题解决了，解决办法是将cudnn-10.1-linux-x64-v7.6.5.32换成cudnn-10.0-linux-x64-v7.6.5.32，但是没明白，因为我用的cuda版本为10.1
