### ISSUE TITLE
安装PPOCRLabel问题

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2870]
问题1 :  

python setup.py install

Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    with open('README.rst') as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
(PaddleOCR) hello@hello-PC:~/PaddleOCR/PPOCRLabel$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    with open('HISTORY.rst') as history_file:
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

----------------------
问题2  :  

python PPOCRLabel.py --lang ch

Traceback (most recent call last):
  File "PPOCRLabel.py", line 38, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/hello/anaconda3/envs/PaddleOCR/lib/python3.6/site-packages/PyQt5-5.15.4-py3.6-linux-x86_64.egg/PyQt5/QtCore.abi3.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PPOCRLabel.py", line 51, in <module>
    from PyQt4.QtGui import *
ModuleNotFoundError: No module named 'PyQt4'

-----------------

求安装PPOCRLabel的正确方式
anaconda环境     linux 系统

**Comment by wfdubowen** [comment]
PPOCRLabel不用setup.py安装，直接按照这一块进行就行https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/PPOCRLabel/README_ch.md#ubuntu-linux
