### ISSUE TITLE
PaddleOCR微信群二维码过期

### ISSUE THREAD

**Issue by prevailings** [PaddlePaddle/PaddleOCR#2874]
想进群交流，找一些资料看看，但是文档和一些视频里的微信二维码都过期了。
方便在这个问题下面提供一张最新的二维码吗? 或者将文档里的二维码更新一下也可以。
谢谢！

**Comment by wfdubowen** [comment]
同求

**Comment by zhangyistruggle** [comment]
希望更新群二维码

**Comment by fhf526** [comment]
![image](https://user-images.githubusercontent.com/84608423/119227720-eab60d80-bb41-11eb-85a2-f3636eb1ab90.png)

**Comment by prevailings** [comment]
谢谢！
