### ISSUE TITLE
attention ocr的问题？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#2876]
文字识别主要有crnn ocr和attention ocr两种方式，但是在我们的说明文档中，crnn有对应的论文，但是attention ocr没看到，指的是RARE那篇论文吗？是由RARE先提出来的吗？

**Comment by tink2123** [comment]
文字识别主要有 ctc 和 attention 两种方式， 基于ctc的算法有 CRNN 、 Rosetta、StarNet，基于attention的方法有RARE、其他的算法我们在repo里没有提供复现代码。论文的链接可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/algorithm_overview.md#%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95
