### ISSUE TITLE
关于OCR识别输出中文的问题

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/PaddleOCR#2877]
![image](https://user-images.githubusercontent.com/40067956/119255675-a2552900-bbef-11eb-9fdf-00476c969aad.png)

这个是我们公司ocr用的paddle出现了问题，有些图能够识别有些图识别就和左边一样，乱七八糟，ocr部署再windows上识别一切正常，没用图片会是左图这样，部署在centos上，就会出现左边的这个情况，但是又不是所有的图在centos上都会出现这个问题，偶尔出现左图的问题，例如右图是centos跑的就没问题。centos和win的程序一样，库包版本都是一样的，唯一区别是centos上面是用显卡跑的，win是用cpu跑的，上面的图，多次放入centos跑都是这个结果，排除像素问题，像素或大或小或和这个差不多的，识别在centos上面都没问题的

**Comment by littletomatodonkey** [comment]
cpu上，把mkldnn这个选项关掉试下呢？

**Comment by LilyCaiZL** [comment]
我可能上面阐述的有问题，是大部分用centos没问题，小部分有问题，再win上完全没问题，win是cpu，centos是gpu

**Comment by LilyCaiZL** [comment]
“识别在centos上面都没问题的”改成“大部分识别在centos上面都没问题的，小部分有左图的问题”
