### ISSUE TITLE
关于文字识别lable 长度问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#2879]
我看文档里面有要求 文字识别模型 训练要求  文字长度不要超过25   超过会自动剔除    有个疑问我用 文字检测模型  检测真实数据  每一行里面文字长度基本都超过25   但是送到识别模型   还是能识别出来    

求大佬指点一下：文字识别训练集对文字长度有要求   为什么真实场景超过25的图片  也能识别出来

**Comment by littletomatodonkey** [comment]
训练的时候，需要保证图片处于同一大小，比如说32x320，短文本padding到320，长文本crop到320，但是长文本太长，crop的话会丢失很多信息，所以在这里做了文本字符长度的限制，但是预测的时候，这块不需要统一到特定长度，所以任意长度的文本都是可以识别的

**Comment by wa3926** [comment]
感谢大佬指点
