### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Evan-wyl** [PaddlePaddle/PaddleOCR#2881]
标注数据时总是闪退，有什么解决办法？
<img width="735" alt="截屏2021-05-24 上午10 06 06" src="https://user-images.githubusercontent.com/68650142/119286938-08858e80-bc78-11eb-8cdc-3afb8967c5af.png">

**Comment by Evezerest** [comment]
标注的步骤能描述一下么？

**Comment by Evan-wyl** [comment]
遇到闪退的情况：
1. 当框选完字之后，点击重新识别，突然闪退。
2. 当框选完字之后，点击重新识别，突然闪退，然后再次进入重新标注闪退前的图片，还是闪退。
3. 框选字时，突然闪退。

标注步骤：
1. 按照教程打开PaddleOCRLabel
2. 勾选自动保存标记结果
3. 打开需要标记的文件夹
4. 开始标记
5. 对标记错误的字进行修改，对未框选的字进行选择，并且输入正确标签(或者直接重新识别，然后修改错误的字)。
6. 确认。
7. 标注下一张

**Comment by Evezerest** [comment]
嗯嗯，是按照四点还是矩形标注呢？四点标注的过程是否有误呢？
