### ISSUE TITLE
*** Error in `python3': double free or corruption (fasttop): 0x00007f2f780020e0 ***

### ISSUE THREAD

**Issue by dychb** [PaddlePaddle/PaddleOCR#2883]
![55ZVEOH4%`XI1_6R}K8Q9](https://user-images.githubusercontent.com/59058681/119302871-67a6cb80-bc97-11eb-89aa-6d305dbb41a1.png)
![(}((O}6H993~7HR207IGNJM](https://user-images.githubusercontent.com/59058681/119302900-6fff0680-bc97-11eb-9a7c-83adbb891681.png)
请问这是怎么回事啊

**Comment by littletomatodonkey** [comment]
把batch size调小一点，把num workers调成0试下呢？
