### ISSUE TITLE
关于SRN导出inference模型的问题

### ISSUE THREAD

**Issue by YukSing12** [PaddlePaddle/PaddleOCR#2884]
导出SRN的inference模型时，模型的输入尺寸是否固定为 1x64x256？
https://github.com/PaddlePaddle/PaddleOCR/blob/47d0927f4d5070eb7767a78e2228ef8d43f9bc76/tools/export_model.py#L55-L71

**Comment by tink2123** [comment]
是的，实际输入的图片shape可以任意，经过预处理的resize后，模型的数据输入shape为1，64，256

**Comment by YukSing12** [comment]
怪不得我修改了之后就出错了，非常感谢您的回复。
