### ISSUE TITLE
文档有死链

### ISSUE THREAD

**Issue by DannyIsFunny** [PaddlePaddle/PaddleOCR#2886]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/quickstart_en.md#2-inference-models
![image](https://user-images.githubusercontent.com/45189361/119307547-72189380-bc9e-11eb-80a4-3d95242f606d.png)

**Comment by littletomatodonkey** [comment]
感谢反馈，已提PR修复：#2896
