### ISSUE TITLE
请教StyleText模型如何部署到移动端

### ISSUE THREAD

**Issue by sheng020** [PaddlePaddle/PaddleOCR#2887]
请教一下，移动端想实现styleText的功能
我按照文档把模型下载下来，地址：
https://paddleocr.bj.bcebos.com/dygraph_v2.0/style_text/style_text_models.zip
里面是pdparams文件，怎么转成移动端（Android，IOS）的格式？
参考文档：
https://paddlex.readthedocs.io/zh_CN/develop/deploy/paddlelite/android.html#paddlexinference
步骤卡在 2.1 使用python脚本优化模型 这一步，
model_file 和 model_dir 在哪里？
谢谢。

**Comment by littletomatodonkey** [comment]
你好，目前styletext还不支持模型导出和转成lite部署到移动端，这个模型本身也比较大，不建议在移动端使用哈

**Comment by sheng020** [comment]
那移动端想实现类似的效果，例如google lens 文字识别和翻译之后那种显示效果，有替代的推荐方案吗？谢谢

**Comment by sheng020** [comment]
> 你好，目前styletext还不支持模型导出和转成lite部署到移动端，这个模型本身也比较大，不建议在移动端使用哈

那移动端想实现类似的效果，例如google lens 文字识别和翻译之后那种显示效果，有替代的推荐方案吗？谢谢
