### ISSUE TITLE
识别顺序错乱

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#289]
针对某些字体稍微不平整,、包含上下标 、包含表格、图片等场景的时候 识别顺序可能会错乱

**Comment by LDOUBLEV** [comment]
能发个样例图吗？

**Comment by bikerr** [comment]
1.包含表格
![image](https://user-images.githubusercontent.com/14155359/86691067-1409a000-c03b-11ea-92e2-904af7b3b611.png)
2.字体稍微不平整
![3](https://user-images.githubusercontent.com/14155359/86691425-621ea380-c03b-11ea-9d24-f0d7730bff7c.png)

**Comment by LDOUBLEV** [comment]
看来是可视化的时候boxes排序的问题，今天修复下

**Comment by LDOUBLEV** [comment]
hub中的box排序没有更新，已联系相关人员修复

**Comment by bikerr** [comment]
采用更新之后的模型 发现还是有这样的问题
