### ISSUE TITLE
英文识别定位不准，英文单词之间没有空格

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#290]
![英文识别无空格](https://user-images.githubusercontent.com/14155359/86690574-9fcefc80-c03a-11ea-8e1c-e25962cdc5b3.png)
![文字较多定位比较差](https://user-images.githubusercontent.com/14155359/86690580-a1002980-c03a-11ea-85e8-6c6c7ab2753b.png)

**Comment by tink2123** [comment]
感谢使用，支持空格的模型还未更新在Repo里，发布后会同步给您。

**Comment by grasswolfs** [comment]
![image](https://user-images.githubusercontent.com/23690325/86731996-9c4f6b80-c062-11ea-8e46-504f275bf761.png)
忍不住先发重训之后最新的模型效果看下，应该近期就会更新出来。

**Comment by tink2123** [comment]
@bikerr 支持空格的模型已发布，上图是大模型的识别效果，欢迎试用

**Comment by longxiang946** [comment]
> @bikerr 支持空格的模型已发布，上图是大模型的识别效果，欢迎试用.
> [inference 模型](https://paddleocr.bj.bcebos.com/ch_models/ch_rec_r34_vd_crnn_enhance_infer.tar)
> [预训练模型](https://paddleocr.bj.bcebos.com/ch_models/ch_rec_r34_vd_crnn_enhance.tar)

预训练模型下载不了

**Comment by Aionrichman** [comment]
请问这个有没有mobile net版本的inference模型啊

**Comment by dyning** [comment]
mobilenet的inference模型也有，请在中文OCR模型列表查找。

**Comment by DuckJ** [comment]
@dyning @tink2123 请问带空格模型finetune时候和原来的预训练模型训练时候的字典大小是不是一样的啊？即原来的预训练模型是不是字典中也有空格啊，只是训练集中没有标出来。finetune时候其实网络层的大小维度是不变的这样才可以顺利finetune，不然finetune的时候是不是数据量少了也不行

**Comment by tink2123** [comment]
是的，支持空格的预训练模型，字典中是有空格的。网络结构改变也可以finntune，但是fc层参数无法加载，相当于从头学习。数据量少的话模型比较难达到一个很好的效果。




发自网易邮箱大师
在2020年08月28日 19:02，ZJ 写道：

@dyning@tink2123 请问带空格模型finetune时候和原来的预训练模型训练时候的字典大小是不是一样的啊？即原来的预训练模型是不是字典中也有空格啊，只是训练集中没有标出来。finetune时候其实网络层的大小维度是不变的这样才可以顺利finetune，不然finetune的时候是不是数据量少了也不行

**Comment by DuckJ** [comment]
@tink2123 谢谢回复，多问一句，你们训练的这个模型finetune的数据量规模大概是多少啊？还有优化器的设置都是什么啊，我在120w数据上学习率减半finetune，loss震荡比较厉害，优化器都是adam

**Comment by DuckJ** [comment]
@tink2123 大佬，请问finetune的时候固定哪些层的参数了么，例如crnn模型。

**Comment by tink2123** [comment]
@DuckJ 优化器和中文配置文件一致，120W数据finetune应该够了，由于我们没有修改字典大小，因此没有固定参数。你可以尝试固定FC之前的参数。

**Comment by DuckJ** [comment]
@tink2123 thanks

**Comment by lucasjinreal** [comment]
中英文混合的，英文君无空格。
