### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#2901]
```
2021-05-25 11:15:18,710 - ERROR - Exception on /ocr [POST]
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\xxx\app.py", line 90, in paddle
    result = chineseOCREngine.ocr(image, cls=False)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\paddleocr.py", line 383, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 109, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 239, in __call__
    output = output_tensor.copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at D:\v2.0.1\paddle\paddle/fluid/framework/tensor.h:202)
```

**Comment by LDOUBLEV** [comment]
提供下报错环境和指令？

**Comment by blackeyecircles** [comment]
同样出现该问题，也是使用flask，现象是并发1个的时候正常，2个以上大概率会出现

**Comment by blackeyecircles** [comment]
File "/home/xxx/anaconda3/envs/xxx/lib/python3.7/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           │    │           │    │              │    │            │   └ {}
           │    │           │    │              │    │            └ <Request 'http://192.168.1.5:8911/predict_online' [POST]>
           │    │           │    │              │    └ 'predict_online'
           │    │           │    │              └ <Rule '/predict_online' (POST, OPTIONS) -> predict_online>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x7f23fd03a200>, 'predict_online': <function predict_online at 0x7f2...
           │    │           └ <Flask 'flask_img'>
           │    └ <function Flask.ensure_sync at 0x7f23fd019b90>
           └ <Flask 'flask_img'>

  File "flask_img.py", line 188, in predict_online
    rec_res = image_predict.pdocr.ocr(imgpath, is_visualize=False)
              │             │     │   └ './tmp/99952833.jpg'
              │             │     └ <function TextSystem.ocr at 0x7f23fd9b3320>
              │             └ <paddleocr_2_1_0.tools.infer.predict_system.TextSystem object at 0x7f2482c754d0>
              └ <__main__.ImagePredict object at 0x7f24dd8c1490>

  File "/home/xxx/xxx/xxx/paddleocr_2_1_0/tools/infer/predict_system.py", line 164, in ocr
    dt_boxes, rec_res = self.detect(img)
                        │    │      └ array([[[ 13,  30,  39],
                        │    │                [ 12,  29,  38],
                        │    │                [ 10,  27,  36],
                        │    │                ...,
                        │    │                [156, 185, 212],
                        │    │                [154...
                        │    └ <function TextSystem.detect at 0x7f23fd9b3200>
                        └ <paddleocr_2_1_0.tools.infer.predict_system.TextSystem object at 0x7f2482c754d0>

  File "/home/xxx/xxx/xxx-xxx/paddleocr_2_1_0/tools/infer/predict_system.py", line 93, in detect
    dt_boxes, elapse = self.text_detector(img)
                       │    │             └ array([[[ 13,  30,  39],
                       │    │                       [ 12,  29,  38],
                       │    │                       [ 10,  27,  36],
                       │    │                       ...,
                       │    │                       [156, 185, 212],
                       │    │                       [154...
                       │    └ <tools.infer.predict_det.TextDetector object at 0x7f2482bebed0>
                       └ <paddleocr_2_1_0.tools.infer.predict_system.TextSystem object at 0x7f2482c754d0>

  File "/home/xxx/xxx/xxx/paddleocr_2_1_0/tools/infer/predict_det.py", line 167, in __call__
    output = output_tensor.copy_to_cpu()
             │             └ <instancemethod copy_to_cpu at 0x7f24308a5810>
             └ <paddle.fluid.core_avx.PaddleInferTensor object at 0x7f2482c03230>

RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:202)

**Comment by blackeyecircles** [comment]
ubuntu 16.04， PaddleOCR-2.1.0, paddlepaddle-gpu==2.1.0   @LDOUBLEV  , 谢谢！

**Comment by bikerr** [comment]
> 提供下报错环境和指令？
@LDOUBLEV 
环境信息：
Windows 10
paddleocr-2.0.6
Flask==1.1.2
CPU环境

**Comment by blackeyecircles** [comment]
@bikerr 多线程的话需要把self.input_tensor, self.output_tensor分离出来，并且屏蔽掉 try_shrink_memory()即可了

**Comment by Gavinic** [comment]
> @bikerr 多线程的话需要把self.input_tensor, self.output_tensor分离出来，并且屏蔽掉 try_shrink_memory()即可了

how to do that ?

**Comment by Gavinic** [comment]
> @bikerr 多线程的话需要把self.input_tensor, self.output_tensor分离出来，并且屏蔽掉 try_shrink_memory()即可了
你好，请问具体怎么实现呢？能贴一下代码吗？

**Comment by blackeyecircles** [comment]
@Gavinic 将 predict_det.py, predict_rec.py 的init  input_tensor, output_tensor 的初始化函数从__init__ 函数移到 __call__函数，因为这2个变量是需要多线程重入的，放在__init__里面作为公用函数会被覆盖，单线程没问题，但是多线程会冲突

**Comment by Gavinic** [comment]
> @Gavinic 将 predict_det.py, predict_rec.py 的init input_tensor, output_tensor 的初始化函数从__init__ 函数移到 __call__函数，因为这2个变量是需要多线程重入的，放在__init__里面作为公用函数会被覆盖，单线程没问题，但是多线程会冲突

好的，非常感谢。

**Comment by Gavinic** [comment]
> @Gavinic 将 predict_det.py, predict_rec.py 的init input_tensor, output_tensor 的初始化函数从__init__ 函数移到 __call__函数，因为这2个变量是需要多线程重入的，放在__init__里面作为公用函数会被覆盖，单线程没问题，但是多线程会冲突
您好，我把input_tensor, output_tensor移到了_call_里边，确实可以解决报错的问题，但是多线程并发的时候一些识别结果会出问题，感觉是因为input_tensor,output_tensor指向的是graph的固定内存区域，每次多线程会修改其中的值？

**Comment by Gavinic** [comment]
> > @Gavinic 将 predict_det.py, predict_rec.py 的init input_tensor, output_tensor 的初始化函数从__init__ 函数移到 __call__函数，因为这2个变量是需要多线程重入的，放在__init__里面作为公用函数会被覆盖，单线程没问题，但是多线程会冲突
> 
> 好的，非常感谢。

TPS的考虑， predictor 的init还是放在了init函数里

**Comment by lpj0711** [comment]
> > > @Gavinic 将 predict_det.py, predict_rec.py 的init input_tensor, output_tensor 的初始化函数从__init__ 函数移到 __call__函数，因为这2个变量是需要多线程重入的，放在__init__里面作为公用函数会被覆盖，单线程没问题，但是多线程会冲突
> > 
> > 
> > 好的，非常感谢。
> 
> TPS的考虑， predictor 的init还是放在了init函数里

你好 你多线程解决了嘛 我也想问这个问题，看了下utility.create_predictor()这个代码，是加载模型的代码吧，是不是每个线程都需要加载一次模型吧

**Comment by blackeyecircles** [comment]
@lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
参考 tools/infer/predict_rec.c: __call__ 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型: 

# input tensor
input_names = self.predictor.get_input_names()
for i in range(len(input_names)):
    input_tensor = self.predictor.get_input_handle(input_names[i])

# output tensor
output_names = self.predictor.get_output_names()
output_tensors = []
for output_name in output_names:
    output_tensor = self.predictor.get_output_handle(output_name)
    output_tensors.append(output_tensor)

**Comment by blackeyecircles** [comment]
@lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:

input_names = self.predictor.get_input_names()
for i in range(len(input_names)):
input_tensor = self.predictor.get_input_handle(input_names[i])

output_names = self.predictor.get_output_names()
output_tensors = []
for output_name in output_names:
output_tensor = self.predictor.get_output_handle(output_name)
output_tensors.append(output_tensor)

**Comment by lpj0711** [comment]
> @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> 
> input_names = self.predictor.get_input_names()
> for i in range(len(input_names)):
> input_tensor = self.predictor.get_input_handle(input_names[i])
> 
> output_names = self.predictor.get_output_names()
> output_tensors = []
> for output_name in output_names:
> output_tensor = self.predictor.get_output_handle(output_name)
> output_tensors.append(output_tensor)

多谢指教！

**Comment by lpj0711** [comment]
> @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> 
> input_names = self.predictor.get_input_names()
> for i in range(len(input_names)):
> input_tensor = self.predictor.get_input_handle(input_names[i])
> 
> output_names = self.predictor.get_output_names()
> output_tensors = []
> for output_name in output_names:
> output_tensor = self.predictor.get_output_handle(output_name)
> output_tensors.append(output_tensor)

大佬 再问下你多线程批量处理图片有提速吗？ 我感觉我的速度没有提升呢

**Comment by blackeyecircles** [comment]
@lpj0711 我这里处理5000张图片，单线程147秒，batch 16耗时96秒，提升大概50%

**Comment by suparek** [comment]
> @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> 
> input_names = self.predictor.get_input_names()
> for i in range(len(input_names)):
> input_tensor = self.predictor.get_input_handle(input_names[i])
> 
> output_names = self.predictor.get_output_names()
> output_tensors = []
> for output_name in output_names:
> output_tensor = self.predictor.get_output_handle(output_name)
> output_tensors.append(output_tensor)

你好，我也使用这个修改，predict_cls.py 如果不用这个修改 也会报这个错
` 
 File "/home/yangtao/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 117, in __call__
    prob_out = self.output_tensors[0].copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
`

但是用了以后，几率性地会报另一个错

`
  File "/home/yangtao/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 123, in __call__
    cls_res[indices[beg_img_no + rno]] = [label, score]
IndexError: index 45 is out of bounds for axis 0 with size 45
`

我还屏蔽了 self.predictor.try_shrink_memory()

**Comment by suparek** [comment]
> > @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> > 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> > input_names = self.predictor.get_input_names()
> > for i in range(len(input_names)):
> > input_tensor = self.predictor.get_input_handle(input_names[i])
> > output_names = self.predictor.get_output_names()
> > output_tensors = []
> > for output_name in output_names:
> > output_tensor = self.predictor.get_output_handle(output_name)
> > output_tensors.append(output_tensor)
> 
> 你好，我也使用了这个修改，predict_cls.py 如果不用这个修改 也会报这个错
> ` File "/home/##/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 117, in __call__ prob_out = self.output_tensors[0].copy_to_cpu() RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.`
> 
> 但是用了以后，几率性地会报另一个错
> 
> `File "/home/##/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 123, in __call__ cls_res[indices[beg_img_no + rno]] = [label, score] IndexError: index 45 is out of bounds for axis 0 with size 45`
> 
> 我还屏蔽了 self.predictor.try_shrink_memory()

@blackeyecircles 向大佬求助

**Comment by suparek** [comment]
> > @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> > 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> > input_names = self.predictor.get_input_names()
> > for i in range(len(input_names)):
> > input_tensor = self.predictor.get_input_handle(input_names[i])
> > output_names = self.predictor.get_output_names()
> > output_tensors = []
> > for output_name in output_names:
> > output_tensor = self.predictor.get_output_handle(output_name)
> > output_tensors.append(output_tensor)
> 
> 你好，我也使用了这个修改，predict_cls.py 如果不用这个修改 也会报这个错
> ` File "/home/##/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 117, in __call__ prob_out = self.output_tensors[0].copy_to_cpu() RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.`
> 
> 但是用了以后，几率性地会报另一个错
> 
> `File "/home/##/miniconda3/envs/paddle_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_cls.py", line 123, in __call__ cls_res[indices[beg_img_no + rno]] = [label, score] IndexError: index 45 is out of bounds for axis 0 with size 45`
> 
> 我还屏蔽了 self.predictor.try_shrink_memory()

@LDOUBLEV IndexError这个好像以前也报过，请问是否有什么解决办法呢？

**Comment by suparek** [comment]
> @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> 
> input_names = self.predictor.get_input_names()
> for i in range(len(input_names)):
> input_tensor = self.predictor.get_input_handle(input_names[i])
> 
> output_names = self.predictor.get_output_names()
> output_tensors = []
> for output_name in output_names:
> output_tensor = self.predictor.get_output_handle(output_name)
> output_tensors.append(output_tensor)

屏蔽 self.predictor.try_shrink_memory() 后，显存得不到释放怎么办？

**Comment by suparek** [comment]
> @lpj0711 你好，我使用的service_streamer进行批量检测，多线程测试正常，
> 参考 tools/infer/predict_rec.c: call 中初始化input_tensor, output_tensors的代码如下, 没有重新加载模型:
> 
> input_names = self.predictor.get_input_names()
> for i in range(len(input_names)):
> input_tensor = self.predictor.get_input_handle(input_names[i])
> 
> output_names = self.predictor.get_output_names()
> output_tensors = []
> for output_name in output_names:
> output_tensor = self.predictor.get_output_handle(output_name)
> output_tensors.append(output_tensor)

@blackeyecircles 屏蔽 self.predictor.try_shrink_memory() 后，显存得不到释放怎么办？
