### ISSUE TITLE
在C++部署方案中，在config.txt中将use_tensorrt置为1，识别出错

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#2904]
在C++部署方案中，在config.txt中将use_tensorrt置为1，命令行窗口出现错误，置为0，则识别成功。
![微信截图_20210525145823](https://user-images.githubusercontent.com/31954286/119453200-bcb31200-bd69-11eb-82eb-a6905681814e.png)

**Comment by LDOUBLEV** [comment]
TRT 部署的明天会提一个支持dynamic shape的PR

**Comment by LDOUBLEV** [comment]
使用TRT可以按照这个[PR](https://github.com/PaddlePaddle/PaddleOCR/pull/2921)修改代码，或，等PRmerge后更新代码

**Comment by Liudyan** [comment]
> 使用TRT可以按照这个[PR](https://github.com/PaddlePaddle/PaddleOCR/pull/2921)修改代码，或，等PRmerge后更新代码
![image](https://user-images.githubusercontent.com/31954286/119628479-ba22ec00-be3f-11eb-80c3-69a32173e46e.png)
是这个节点吗？
