### ISSUE TITLE
求教：关于手写中文单字合成文本行数据集问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#2908]
在手写数据集 页面下面又一行使用建议：
数据为单字，白色背景，可以大量合成文字行进行训练。白色背景可以处理成透明状态，方便添加各种背景。对于需要语义的情况，建议从真实语料出发，抽取单字组成文字行

HWDB1.0~1.2总共有3895135个手写单字样本，分属7356类（7185个汉字和171个英文字母、数字、符号）

想请教一下：近400W 单字   应该怎么合成 文本行数据   要兼顾 lable长度不能超过25  以及 样本的均衡性   ，求大佬指点一下思路！或者参考的代码

**Comment by LDOUBLEV** [comment]
随机抽取单字图像和对应的label，组合成句子

**Comment by wa3926** [comment]
@LDOUBLEV  大佬 单字合成图像高度 不一致   每行图片生成的时候 是以最大的为准  还是说 有个统一的高度  请问一下 哪种训练效果好一点

**Comment by wa3926** [comment]
感谢大佬  目前已经合成 第一批数据

**Comment by MarginGitHub** [comment]
> 感谢大佬 目前已经合成 第一批数据

目前你训练的准确度可以达到多少哦？
