### ISSUE TITLE
C++版本和Python版本预测结果相差很大，使用官方模型和自训练模型都相差很大

### ISSUE THREAD

**Issue by lydyc** [PaddlePaddle/PaddleOCR#2910]
问题好像是C++和python在图像预处理时不一样，检测结果有差别，识别结果也有差别，C++效果普遍较差。请问怎么解决呢？使用2.0版本。

**Comment by LDOUBLEV** [comment]
我这边测试，python预测和C++预测框波动1-2个像素
C++：
![image](https://user-images.githubusercontent.com/26592129/119506200-454ca500-bda0-11eb-85d0-dee759397003.png)
python：
![image](https://user-images.githubusercontent.com/26592129/119506247-509fd080-bda0-11eb-8a74-a70e40501018.png)


你测试差别大的图是哪一个

**Comment by lydyc** [comment]
> 我这边测试，python预测和C++预测框波动1-2个像素
> C++：
> ![image](https://user-images.githubusercontent.com/26592129/119506200-454ca500-bda0-11eb-85d0-dee759397003.png)
> python：
> ![image](https://user-images.githubusercontent.com/26592129/119506247-509fd080-bda0-11eb-8a74-a70e40501018.png)
> 
> 你测试diff较大的图是哪一个

使用自训练识别模型，当时acc大概为0.996，使用predict_rec.py测试准确率挺好的，后转换为inference模型。
（1）python tools/export_model.py -c configs/rec/multi_language/rec_en_number_lite_train -o Global.pretrained_model=./pretrain_models/en_number_mobile_v2.0_rec_train/best_accuracy  Global.save_inference_dir=./inference/rec_en_number/
![image](https://user-images.githubusercontent.com/38954440/119585922-51674f80-bdfe-11eb-9da4-51c7df2eb3c2.png)

（2）转换结束后，使用predict_system.py进行测试：python tools/infer/predict_system.py --image_dir="./doc/imgs/1.bmp" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/rec_en_number/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False
![image](https://user-images.githubusercontent.com/38954440/119585981-70fe7800-bdfe-11eb-83d9-0cfb92ef4f67.png)
![image](https://user-images.githubusercontent.com/38954440/119586037-94292780-bdfe-11eb-83b4-451fd22e7a4e.png)


（3）使用C++进行测试，使用同样的模型：
配置文件：
![image](https://user-images.githubusercontent.com/38954440/119586232-d7839600-bdfe-11eb-9316-d16286f02209.png)
识别结果：
![image](https://user-images.githubusercontent.com/38954440/119586244-de120d80-bdfe-11eb-851e-f869d91f2feb.png)
检测结果：
![image](https://user-images.githubusercontent.com/38954440/119586571-8f18a800-bdff-11eb-87b3-c35415a0843b.png)

（4）原图及识别模型：

[model-image.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6543138/model-image.zip)

**Comment by lydyc** [comment]
![image](https://user-images.githubusercontent.com/38954440/119586692-cdae6280-bdff-11eb-9f03-45cde3a27222.png)

**Comment by LDOUBLEV** [comment]
你用的哪个分支的PaddleOCR代码，更新代码试试，我用的dygraph分支的代码，没加方向分类器，用你的模型测试，python和C++结果是一样的，只是score有点不一样

**Comment by LDOUBLEV** [comment]
配置文件：
![image](https://user-images.githubusercontent.com/26592129/119593769-233d3c00-be0d-11eb-85ed-5ebf3ce1feab.png)

**Comment by lydyc** [comment]
> 配置文件：
> ![image](https://user-images.githubusercontent.com/26592129/119593769-233d3c00-be0d-11eb-85ed-5ebf3ce1feab.png)

谢谢，我再试试，请问您使用的预测库是哪个版本的呢？2.0.1还是2.1.0
![image](https://user-images.githubusercontent.com/38954440/119597154-14f21e80-be13-11eb-9a18-6d4a66c4204f.png)
![image](https://user-images.githubusercontent.com/38954440/119597187-1facb380-be13-11eb-8ef7-fbfd873e227c.png)

**Comment by lydyc** [comment]
> > 配置文件：
> > ![image](https://user-images.githubusercontent.com/26592129/119593769-233d3c00-be0d-11eb-85ed-5ebf3ce1feab.png)
> 
> 谢谢，我再试试，请问您使用的预测库是哪个版本的呢？2.0.1还是2.1.0
> ![image](https://user-images.githubusercontent.com/38954440/119597154-14f21e80-be13-11eb-9a18-6d4a66c4204f.png)
> ![image](https://user-images.githubusercontent.com/38954440/119597187-1facb380-be13-11eb-8ef7-fbfd873e227c.png)

您好，我使用预测库2.1.0版本+ygraph分支，和预测库2.1.0版本+2.1release分支进行了测试，结果还是和python不一致：
（1）预测库2.1.0版本+ygraph分支：
![image](https://user-images.githubusercontent.com/38954440/119598796-30125d80-be16-11eb-891a-69d389f4dbb9.png)
![image](https://user-images.githubusercontent.com/38954440/119598758-1d982400-be16-11eb-88a6-d87b15924b95.png)

![image](https://user-images.githubusercontent.com/38954440/119598985-a616c480-be16-11eb-86c4-079d6e07a269.png)
![image](https://user-images.githubusercontent.com/38954440/119598966-9a2b0280-be16-11eb-90d9-e85f35044cbd.png)

（2）预测库2.1.0版本+2.1release分支 和 ygraph分支结果一致。
（3）配置文件：
![image](https://user-images.githubusercontent.com/38954440/119599036-c5155680-be16-11eb-9e02-7d3169f0535f.png)
（4）使用python测试，同样的模型+字典，结果和C++不同。
![image](https://user-images.githubusercontent.com/38954440/119607422-e1b98a80-be26-11eb-8a74-4b3afc2b468a.png)

**Comment by lydyc** [comment]
1、做了一下其它的测试，发现在使用tools/infer_rec.py进行预测时，使用best_accuracy，测试结果准确：
python tools/infer_rec.py -c configs/rec/multi_language/rec_en_number_lite_train.yml -o Global.pretrained_model=output/rec_en_number_lite/best_accuracy Global.load_static_weights=false Global.infer_img=doc/imgs/100.jpg Global.character_dict_path=ppocr/utils/en_dict.txt
![100](https://user-images.githubusercontent.com/38954440/119610719-3d3a4700-be2c-11eb-96c0-601d6850ea57.jpg)
![image](https://user-images.githubusercontent.com/38954440/119610807-62c75080-be2c-11eb-8aa6-5a603c4e0f92.png)
2、接着将best_accuracy转化为inference进行预测，发现必须指定rec_char_type="en"（训练的时候也是指定为“en”），若不指定则结果和C++预测结果一样（错误识别为“0E”）。
![image](https://user-images.githubusercontent.com/38954440/119612628-b470da80-be2e-11eb-9c8f-3b4ada5cb9c7.png)

**Comment by fredhu2009** [comment]
问一下两位大神：我的预测库里没有params和model两个文件，如果只用用inference.pdiparams的三个文件，C++代码是怎么写的呀？我直接用这个目录配置上去，ocr_system.exe直接异常退出。

**Comment by Dandelion111** [comment]
> 你用的哪个分支的PaddleOCR代码，更新代码试试，我用的dygraph分支的代码，没加方向分类器，用你的模型测试，python和C++结果是一样的，只是score有点不一样
> python：
> ![image](https://user-images.githubusercontent.com/26592129/119593713-07399a80-be0d-11eb-870e-eecfe187dba5.png)
> 
> C++
> ![image](https://user-images.githubusercontent.com/26592129/119593731-0e60a880-be0d-11eb-9a3a-b149c228fb58.png)

请问大哥dygraph代码在哪里
