### ISSUE TITLE
如何修改DB后处理，实现只出水平检测框呢？

### ISSUE THREAD

**Issue by yxyangxu** [PaddlePaddle/PaddleOCR#2911]
如果两行之间距离较近，各行每个文字之间较远，该怎么办呢，我想到的办法是修改DB后处理，实现只出水平检测框
还有其他建议吗

**Comment by LDOUBLEV** [comment]
如果你要检测的比较规整，可以尝试判断文本框的长宽比，如果长宽比过小，说明文本框是竖着的，可以对文本框做等分；具体依照你的case来处理，加一些规则进去；

**Comment by yxyangxu** [comment]
> 整

会有办法强制DB区域生成框的时候，都是水平框吗

**Comment by yxyangxu** [comment]
> 如果你要检测的比较规整，可以尝试判断文本框的长宽比，如果长宽比过小，说明文本框是竖着的，可以对文本框做等分；具体依照你的case来处理，加一些规则进去；

会有办法强制DB区域生成框的时候，都是水平框吗

**Comment by LDOUBLEV** [comment]
这个没法限制，目前两个办法可以试试：
1.  你在你的数据上finetune训练
2. 把db 后处理参数 unclip_ratio调小一些，这样文本框会更紧贴文字，看是否能将上下文本的框分开

**Comment by yxyangxu** [comment]
> 这个没法限制，目前两个办法可以试试：
> 
> 1. 你在你的数据上finetune训练，让模型适应你的数据
> 2. 把db 后处理参数 unclip_ratio调小一些，这样文本框会更紧贴文字，看是否能将上下文本的框分开

非常感谢
