### ISSUE TITLE
paddle版本问题

### ISSUE THREAD

**Issue by Mafengqiang** [PaddlePaddle/PaddleOCR#2915]
我的服务器的驱动版本为384.130，一开始用docker安装paddle2.0的时候提示版本太低安装不上，参考的是这个版本对应图。
![paddleocr版本对应](https://user-images.githubusercontent.com/44855506/119587730-dd2eab00-be01-11eb-8a1c-e5a283a721f0.jpg)
现在在同样的环境下下，安装的paddle版本为2.0.2:post101安装运行测试成功了，是新版本对服务器的驱动版本要求变低了吗

**Comment by MissPenguin** [comment]
run check一下看是不是真的装成功了
![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)

**Comment by Mafengqiang** [comment]
> run check一下看是不是真的装成功了
> ![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)

![image](https://user-images.githubusercontent.com/44855506/119749576-f438d000-bec9-11eb-96fa-c3706c08c572.png)
这是测试结果，提示只有一张卡运行成功了，其他的卡是不是因为占用满了的原因

**Comment by Mafengqiang** [comment]
> run check一下看是不是真的装成功了
> ![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)

![image](https://user-images.githubusercontent.com/44855506/119749790-6f01eb00-beca-11eb-95a4-c0f22a07aed4.png)
这个是paddle的安装版本，现在新版本是对服务器的驱动版本要求变低了吗

**Comment by MissPenguin** [comment]
> > run check一下看是不是真的装成功了
> > ![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)
> 
> ![image](https://user-images.githubusercontent.com/44855506/119749790-6f01eb00-beca-11eb-95a4-c0f22a07aed4.png)
> 这个是paddle的安装版本，现在新版本是对服务器的驱动版本要求变低了吗

pip list有paddle不代表成功安装，安装上面的验证步骤验证下，如果确实没问题，就直接用就行了，有问题的话就还是需要换版本。不过一般对版本的要求严格来说是“建议”版本，不代表所有不满足的一定用不了的哈

**Comment by Mafengqiang** [comment]
> > > run check一下看是不是真的装成功了
> > > ![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44855506/119749790-6f01eb00-beca-11eb-95a4-c0f22a07aed4.png)
> > 这个是paddle的安装版本，现在新版本是对服务器的驱动版本要求变低了吗
> 
> pip list有paddle不代表成功安装，安装上面的验证步骤验证下，如果确实没问题，就直接用就行了，有问题的话就还是需要换版本。不过一般对版本的要求严格来说是“建议”版本，不代表所有不满足的一定用不了的哈

嗯嗯谢谢你啦，我run check测试了，结果是安装成功了，运行结果截图在上面，主要是之前我安装2.0版本一直用不了，现在别人同样环形下安装2.0.2可以用了，就有点疑问

**Comment by Mafengqiang** [comment]
> > > run check一下看是不是真的装成功了
> > > ![image](https://user-images.githubusercontent.com/25809855/119659612-e9962080-be60-11eb-8437-c6de8f1a520b.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44855506/119749790-6f01eb00-beca-11eb-95a4-c0f22a07aed4.png)
> > 这个是paddle的安装版本，现在新版本是对服务器的驱动版本要求变低了吗
> 
> pip list有paddle不代表成功安装，安装上面的验证步骤验证下，如果确实没问题，就直接用就行了，有问题的话就还是需要换版本。不过一般对版本的要求严格来说是“建议”版本，不代表所有不满足的一定用不了的哈

嗯嗯谢谢你啦，我run check测试了，结果是安装成功了，运行结果截图在上面，主要是之前我安装2.0版本一直用不了，现在别人同样环境下安装2.0.2可以用了，就有点疑问
