### ISSUE TITLE
检测算法图像预处理时候，为什么一定需要是32的整数倍？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2918]
检测算法图像预处理时候，为什么一定需要是32的整数倍（如下代码），若不为32的倍数，在windons CPU下报错,无法运行
'''
        resize_h = int(round(resize_h / 32) * 32)
        resize_w = int(round(resize_w / 32) * 32)
'''

**Comment by MissPenguin** [comment]
可以看下这两个FAQ：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q216-%E9%A2%84%E5%A4%84%E7%90%86%E9%83%A8%E5%88%86%E5%9B%BE%E7%89%87%E7%9A%84%E9%95%BF%E5%92%8C%E5%AE%BD%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E5%A4%84%E7%90%86%E6%88%9032%E7%9A%84%E5%80%8D%E6%95%B0
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q3323%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E6%88%96%E9%A2%84%E6%B5%8B%E6%97%B6%E5%87%BA%E7%8E%B0elementwise_add%E6%8A%A5%E9%94%99
