### ISSUE TITLE
识别模型微调问题

### ISSUE THREAD

**Issue by Aiyoj** [PaddlePaddle/PaddleOCR#292]
使用mv3_crnn微调，loss很大，acc很难上去

**Comment by tink2123** [comment]
请问具体是怎么微调的？训练数据有多少呢？

**Comment by Aiyoj** [comment]
> 请问具体是怎么微调的？训练数据有多少呢？

@tink2123 配置文件采用的是rec_chinese_lite_train.yml，数据集是是从lsvt裁剪下来的10W数据，下图是训练日志
![image](https://user-images.githubusercontent.com/28584450/86859773-f77e6e00-c0f5-11ea-8f0b-7106864b8379.png)

**Comment by tink2123** [comment]
lsvt数据中有一些偏难，我们训练到收敛最终loss也接近500左右。
