### ISSUE TITLE
定义模型中的eval函数问题

### ISSUE THREAD

**Issue by Luodapang** [PaddlePaddle/PaddleOCR#2922]
发现PaddlePaddleOCR框架在生成模型或者数据集等的时候会使用到eval函数（代码如下所示），但是关于eval函数的细节不太清楚，它的功能是什么，如果我想自定义一个模型需要怎么利用这个实现。
`
module_class = eval(module_name)(**config)
`

**Comment by MissPenguin** [comment]
eval一般用于基于训练模型评估模型指标，相关配置可以在yml文件中找到：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/det/det_mv3_db.yml#L105 ，可以根据需要修改相应的预处理或后处理逻辑，包括指标计算方式也可以修改

**Comment by Luodapang** [comment]
> eval一般用于基于训练模型评估模型指标，相关配置可以在yml文件中找到：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/det/det_mv3_db.yml#L105 ，可以根据需要修改相应的预处理或后处理逻辑，包括指标计算方式也可以修改

感谢您的回答，我知道.yml文件中Eval部分是对训练模型评估模块的一些参数，但是我在自定义backbone网络的时候遇到了一个eval()函数，这个函数返回的应该是根据config定义的模型，但是函数的细节我没看到，所以我不能准确知道实例化函数的具体流程以及实例化的结果。不知道我理解的对不对。
`
module_class = eval(module_name)(**config)
return module_class
`

**Comment by MissPenguin** [comment]
抱歉前面理解错你的意思了，以为问的评估。这个eval是python内置函数，具体功能和使用方式可以百度一下，关键词“python eval”即可。

**Comment by Luodapang** [comment]
> 抱歉前面理解错你的意思了，以为问的评估。这个eval是python内置函数，具体功能和使用方式可以百度一下，关键词“python eval”即可。

嗯嗯，明白了，感谢。
