### ISSUE TITLE
python import paddleocr方式，如何开启多线程multi-proecess？

### ISSUE THREAD

**Issue by hnwlxywns** [PaddlePaddle/PaddleOCR#2924]
请教一下，python 编码方式，引入 paddleocr库，如何开启多线程，是否有相关的案例； 目前通过测试，单张图片识别要15秒左右，麻烦解答一下？

**Comment by littletomatodonkey** [comment]
1. cpu的话，可以开启mkldnn多线程预测，`enable_mkldnn `参数修改为true
2. 如果是希望使用多进程，可以将`use_mp `修改为true
3. 图片太大的话，可以把图片reisze之后再送进网络

刚才说的所有参数都在这里
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/utility.py

**Comment by hnwlxywns** [comment]
感谢回复~
