### ISSUE TITLE
想请教下，我需要印刷体和手写体的识别，按照文档需要一个分类器和两个识别模型，想问几个问题

### ISSUE THREAD

**Issue by stedylan** [PaddlePaddle/PaddleOCR#2928]
1.分类器是在什么位置加呢，能否指点一下，有无文档
2.对于手写体识别，我现在有中科大的单字数据库，我需要组合句子，还是说用单字就可以训练了？

**Comment by MissPenguin** [comment]
1. 方向分类器可以通过命令行参数控制是否使用，具体可参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/inference.md#1-%E8%B6%85%E8%BD%BB%E9%87%8F%E4%B8%AD%E6%96%87ocr%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86
2. 这个决定于你的检测是单字检测还是行级别，都是可行的，但建议都基于行级别，这样可以利用上句子的序列信息

**Comment by stedylan** [comment]
> 1. 方向分类器可以通过命令行参数控制是否使用，具体可参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/inference.md#1-%E8%B6%85%E8%BD%BB%E9%87%8F%E4%B8%AD%E6%96%87ocr%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86
> 2. 这个决定于你的检测是单字检测还是行级别，都是可行的，但建议都基于行级别，这样可以利用上句子的序列信息

非常感谢！还有一点就是，我想训练一个文字类别分类器，您说的方向分类器能运用于文字类别判定上吗

**Comment by MissPenguin** [comment]
方向分类器只是判定文字方向，你说的文字类别是指手写体印刷体分类吗，是的话，需要自己重新训练，但都是分类任务，逻辑是类似的，可以参考方向分类器改一下

**Comment by stedylan** [comment]
> 方向分类器只是判定文字方向，你说的文字类别是指手写体印刷体分类吗，是的话，需要自己重新训练，但都是分类任务，逻辑是类似的，可以参考方向分类器改一下

好的，谢谢
