### ISSUE TITLE
你好, 尊敬的程序员哥哥/姐姐，想问一下建立多语种混合识别模型的问题

### ISSUE THREAD

**Issue by immense8342** [PaddlePaddle/PaddleOCR#2929]
现在业务需要是建立一个 可以识别 **混合多语种信息 的自然场景文字识别模型**。 
（比如一张车站牌子上面有中文、日文、英文等，需要将他们分别识别出来）
问题如下：

1. 我查阅了你们以前的Q&A，说是建立“1个检测模型+1个N分类模型+N个识别模型”，**具体的垂直的多语种模型建立过程可以写得详细一些吗**？比如一般使用哪些模型组合较好？文档里面多语种只是给出了训练好的模型，但是对于自己去针对性地训练自己的模型描述得较少。是直接参考英文模型的进行训练就可以吗？
2. 多语种同在一个图片，面临着需要一个三分类模型，这个模型一般采用什么呢？是直接使用Softmax？使用回归？LeNet、AlexNet、VGG、GoogLeNet、ResNet这些？**要怎么把他们“1个检测模型+1个N分类模型+N个识别模型”弄成一起端到端啊**？纯小白，只学了点皮毛，不知道后面怎么操作了。
希望能有人帅心善/人美心善的程序员解答下！！先谢谢啦~~~

**Comment by MissPenguin** [comment]
1. 是的，识别的训练都是差不多的，换语种训练一般替换训练数据和字典就行
2. 语种分类就是一个分类任务，可以参考本项目中的[方向分类器](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/angle_class.md)进行改造，也可参考分类模型套件[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)学习一下分类一般怎么训，里面也有丰富的文档教程

**Comment by immense8342** [comment]
> 1. 是的，识别的训练都是差不多的，换语种训练一般替换训练数据和字典就行
> 2. 语种分类就是一个分类任务，可以参考本项目中的[方向分类器](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/angle_class.md)进行改造，也可参考分类模型套件[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)学习一下分类一般怎么训，里面也有丰富的文档教程

好的~~谢谢~~
我看了分类套件中的Demo，大概知道了如何使用预训练的CNN模型进行分类，现在的问题是**如何将检测模型和分类模型结合成端到端呢**？
比如：假设我们得到了

> " 图像文件名                    json.dumps编码的图像标注信息"
>ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]


我们通过PaddleOCR中检测模型得到了，这样的**预测points列表**，  之后**输入到CNN分类模型的是什么呢**？是这个point列表吗？还是图像数据？如果是图像数据，要怎么截取出来呢？哭了

**Comment by Evezerest** [comment]
识别模型输入的都是根据检测框截取好的文字图像
