### ISSUE TITLE
自然场景文字识别，背景面积很大，文字较小且不突出识别不出来的问题

### ISSUE THREAD

**Issue by immense8342** [PaddlePaddle/PaddleOCR#2930]
尝试使用PaddleOCR的**训练好**的通用模型对图片中的文字进行识别，发现因为**图片较大，背景很大，文字只占了图片很小的一部分**的时候（比如识别一个飞机的型号，飞机很大，但是型号很小；识别一张游客拍的图片上面的路标牌，由于离得很远，虽然图片文字人工看得清，但是占比过小，检测模型发现不了）
**检测模型会出现无法检测出文字**的情况。
请问这种时候该如何优化呢？或者是替换什么部分？这种问题需要怎么应对呢？

谢谢人帅心善/人美心善的程序员哥哥/姐姐~~~~~~~~~

**Comment by MissPenguin** [comment]
1. 建议使用业务场景数据进行finetune
2. 预测时可调大输入图像分辨率试试

**Comment by immense8342** [comment]
> 1. 建议使用业务场景数据进行finetune
> 2. 预测时可调大输入图像分辨率试试

谢谢~~~~

finetune
到底是重新直接加载预训练模型训练一遍？
还是要固定ResNet的某些层的参数，修改层参数，再进行训练？
还是要加载预训练模型，自己手动修改学习率等参数，多次尝试看看有没有更好的结果？

网上搜了很多，各种解释都有，不知道到底是什么。求解释。

**Comment by Evezerest** [comment]
都是，finetune的目的就是在已有的一个好的模型初始化点上，根据当前的数据情况进一步训练调整，你说的这些都是调整的具体手段
