### ISSUE TITLE
Opencv版本问题

### ISSUE THREAD

**Issue by zhaowenjun** [PaddlePaddle/PaddleOCR#2932]
你好，Opencv的版本必须是3.4.6版本吗？因为我程序用的是opecv4.5.1版本，我想部署OCR的时候也用4.5.1的版本。

**Comment by siqiaof** [comment]
我之前试过4.5.2加win10预编译的paddle inference，可以运行。

**Comment by siqiaof** [comment]
cuda版本和cudnn版本对应就行，我是cuda 10.2，cudnn 7.6.5

**Comment by zhaowenjun** [comment]
@siqiaof 非常感谢你的宝贵意见。
