### ISSUE TITLE
训练自己的文字识别模型，修改图片大小

### ISSUE THREAD

**Issue by maxh2010** [PaddlePaddle/PaddleOCR#2933]
rec_chinese_lite_train_v2.0.yml里可以根据实际图片大小 修改下面的参数吗？
rec_chinese_lite_train_v2.0.yml
      - RecResizeImg:          image_shape: [3, 32, 320]
      修改后
      - RecResizeImg:          image_shape: [3, 100, 300]

**Comment by WenmuZhou** [comment]
你改为100后，需要改网络结构了，保证cnn部分出来的特征图h为1

**Comment by maxh2010** [comment]
了解了，多谢
