### ISSUE TITLE
有关日语模型

### ISSUE THREAD

**Issue by jessica05166** [PaddlePaddle/PaddleOCR#2935]
选择日语模型的场合，金额【￥】不能识别，还有【※】,在字典【japan_dict.txt】查找了一下。没有这两个关键字。并且半角金额【￥】在中文系统中显示的是【\】。日文字典是不是漏了【\】，【￥】，【※】这三个关键字呢！

**Comment by tink2123** [comment]
看下下字典中确实没有～ 如果有需要的话可以把缺少的字符添加到字典中，基于自己的数据finetune一下。

**Comment by jessica05166** [comment]
您说的finetune，是要重新训练吗？具体怎么操作呢？我是新手，安装上工具后，只会用它识别图。别的数据再训练，还不会。

**Comment by tink2123** [comment]
finetune 指的是用自己的数据，基于我们已经训练好的权重做微调。
finetune相关的文档可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/recognition.md
