### ISSUE TITLE
预测精度问题

### ISSUE THREAD

**Issue by chenzi** [PaddlePaddle/PaddleOCR#2936]
我使用同一张图片，在官网预测和自己下载模型预测结果不一样，请问是什么问题？

**Comment by WenmuZhou** [comment]
1. 给出图片
2. 给出你下载的模型地址
3. 给出你说的官网路径
4. 给出你的预测命令

**Comment by chenzi** [comment]
1. 我的图片
![图片](https://user-images.githubusercontent.com/5486633/119801027-e3ab4880-bf0f-11eb-9ccd-60536a81ffd8.jpg)

2.模型地址：
 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar
  https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar

3.我的预测命令：
python3 tools/infer/predict_system.py --image_dir="./images/xxx.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer" --use_angle_cls=True --use_space_char=True

5.我的预测结果：
![11842273-big](https://user-images.githubusercontent.com/5486633/119804297-cb88f880-bf12-11eb-8a9b-60ce3cee6850.jpg)

6.官方的预测结果：
地址：https://www.paddlepaddle.org.cn/hub/scene/ocr
<img width="1336" alt="QQ20210527-174044@2x" src="https://user-images.githubusercontent.com/5486633/119804296-cb88f880-bf12-11eb-9649-2a2607c47899.png">

是我下载错了模型吗？ 请问官网用的什么模型？

**Comment by chenzi** [comment]
我下载的模型：
![QQ20210527-174501](https://user-images.githubusercontent.com/5486633/119804860-54079900-bf13-11eb-8f9b-8ab11814b943.png)

**Comment by WenmuZhou** [comment]
我试了一下，server的模型会这样，mobile的不会，网页上用的是mobile的

**Comment by chenzi** [comment]
这就尴尬了， 我看说明server的精度要高些，我试下mobile模型看看。

**Comment by WenmuZhou** [comment]
server的指标是高的，部分case有差异
