### ISSUE TITLE
Please compile with MKLDNN first to use MKLDNN

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#2938]
用C++部署，把use_mkldnn 设置位1后出现下面提示，速度也没有加快。

E0527 17:43:51.017755 15752 analysis_config.cc:231] Please compile with MKLDNN first to use MKLDNN
E0527 17:43:51.018748 15752 analysis_config.cc:242] Please compile with MKLDNN first to set MKLDNN Thread Id
E0527 17:43:51.368813 15752 analysis_config.cc:231] Please compile with MKLDNN first to use MKLDNN
E0527 17:43:51.368813 15752 analysis_config.cc:242] Please compile with MKLDNN first to set MKLDNN Thread Id

**Comment by LDOUBLEV** [comment]
首先使用的预测库要支持MKLDNN？使用的预测库是？
另外，只测试一张图看不出来加速，预测一张图会做模型初始化，比较占时间，建议多测试一些图看看
