### ISSUE TITLE
推理后的模型效果不行

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#294]
训练： CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/rec/rec_icdar15_train.yml

转推理：python3 tools/export_model.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints=./output/rec_CRNN/iter_epoch_60 Global.save_inference_dir=./inference/rec_crnn/（微调，60轮效果很好了）

预测：python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/" --rec_model_dir="./inference/rec_crnn"
效果不好！！！

**Comment by tink2123** [comment]
试一下：

python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/" --rec_model_dir="./inference/rec_crnn" --rec_image_shape="3, 32, 100" --rec_char_type="en"

**Comment by wangning7149** [comment]
> 
> 
> 试一下：
> 
> python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/" --rec_model_dir="./inference/rec_crnn" --rec_image_shape="3, 32, 100" --rec_char_type="enbu

**Comment by wangning7149** [comment]
> 
> 
> 试一下：
> 
> python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/" --rec_model_dir="./inference/rec_crnn" --rec_image_shape="3, 32, 100" --rec_char_type="en"

不行

**Comment by tink2123** [comment]
效果很好是指：使用 infer_rec 预测效果很好吗？
您的模型在验证集上精度有多少？
