### ISSUE TITLE
paddle ocr是否支持华为Atlas 300 型号 GPU

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2940]
paddle ocr是否支持华为Atlas 300 型号 GPU  能不能部署paddle

**Comment by WenmuZhou** [comment]
目前华为支持的是这些
![image](https://user-images.githubusercontent.com/12406017/119811129-55d45b00-bf19-11eb-8ada-c7e3d7845a1b.png)

**Comment by ymzx** [comment]
> 目前华为支持的是这些
> ![image](https://user-images.githubusercontent.com/12406017/119811129-55d45b00-bf19-11eb-8ada-c7e3d7845a1b.png)

请问如何将 paddle ocr 和华为atlas300结合，paddleocr 效果很好，但是我只有atlas300，如何能让两者结合，跑的飞快？

**Comment by WenmuZhou** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/hardware_info_cn.html 
![image](https://user-images.githubusercontent.com/12406017/119929632-74d1fc00-bfb0-11eb-8a90-50895383e686.png)
目前还不支持
