### ISSUE TITLE
C++  WIN编译部署集成显卡和N卡顺序引起的异常，请大佬看看。

### ISSUE THREAD

**Issue by yfc886** [PaddlePaddle/PaddleOCR#2944]
基于Paddleocr2.0 cpp_infer 编译的项目，CUDA 10.2   
现在遇到一个问题，当PC 存在双显卡 也就是 集成显卡和独立显卡的情况，如果独立显卡N卡在任务管理器中显示索引为0，则GPU可以正常推理。 如果N卡索引为1，载入模型会错误。 设置GPUID 为索引0和1 也不行。
![66](https://user-images.githubusercontent.com/18112706/119843838-7f51ae80-bf3a-11eb-889b-dca401244fd9.png)
集成显卡在N卡前面，就不能推理
![4444](https://user-images.githubusercontent.com/18112706/119843959-9a242300-bf3a-11eb-9795-58bff1f3754e.png)
N卡在集成显卡前面推理就正常。 已经测试5个PC了。

**Comment by yfc886** [comment]
![5555](https://user-images.githubusercontent.com/18112706/119844255-dc4d6480-bf3a-11eb-90d2-ea0ccc56ef72.png)

**Comment by littletomatodonkey** [comment]
python还是cpp？不同系列的显卡确实可能会出现这样的问题
