### ISSUE TITLE
用横排竖排都有的数据集训练pgnet时，ctc_loss无法收敛。

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#2945]
ctc_loss一直保持开始的水平，在40~60之间波动
横排检测的效果尚可，竖排很差
识别的效果横竖都很差
是需要对竖排文本做一些处理吗？训练和预测时分别需要怎么做呢？
（数据集大部分为横排，小部分为竖排）

**Comment by LDOUBLEV** [comment]
你的label是不是对的，另外可以check下训练数据生成的label ，比如文字方向是不是对的；

**Comment by LDOUBLEV** [comment]
另外要注意的是坐标点的顺序，横排的pgnet的点顺序是从左到右，竖排文字的坐标顺序可能会不太一样

**Comment by lzzzzj** [comment]
标签和点的顺序都没有问题
请问ctc_loss不收敛还有别的可能的原因吗，多次修改过一些参数都没有什么改善

**Comment by lqniunjunlper** [comment]
@lzzzzj 遇到同样的问题 如何解决？竖排的label坐标如何设置比较好？

**Comment by lzzzzj** [comment]
> @lzzzzj 遇到同样的问题 如何解决？竖排的label坐标如何设置比较好？

标点按理来说也是从左上开始顺时针即可，但是我最后效果还是比较差，你可以试一试

**Comment by BurrowsWang** [comment]
> 我用来训练印章识别，ctc_loss从一开始就是0

您用的印章数据集是哪个呢？

**Comment by shuihsaiu** [comment]
请问楼主，遇到的问题解决了么？

**Comment by lzzzzj** [comment]
> 
没有，收敛不了，最后换模型了😥
