### ISSUE TITLE
windows下编译预测库

### ISSUE THREAD

**Issue by zhaowenjun** [PaddlePaddle/PaddleOCR#2947]
我根据https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/docs/windows_vs2019_build.md  这个网站进行编译预测库，做到第3步就做不下去了。。（Step3: 使用Visual Studio 2019直接编译CMake点击： 文件->打开->CMake 选择项目代码所在路径，并打开CMakeList.txt：），我的目录下没有CMakeList.txt，只有CMakeCache.txt。但是我用vs2019 cmake文件打开CMakeCache.txt，什么也没有发生，vs2019上没有项目这一选项？       我是不是打开错了项目源码还是？？？并且我下载了PaddleOCR-release-2.1源代码，里面的目录也是和文档上对不上。。。。

**Comment by TingquanGao** [comment]
你好，是不是PaddleOCR的代码没有下载完整呢？或者是分支选择不对？应该是有CMakeList.txt文件的。
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/deploy/cpp_infer/CMakeLists.txt

**Comment by luoyuncen** [comment]
这个文档说的不清楚，建议看这个：https://blog.csdn.net/qq_38836770/article/details/109548170

**Comment by zhaowenjun** [comment]
@TingquanGao @luoyuncen 感谢两位！
