### ISSUE TITLE
配置他国语言怎么配置，没有params和model两个文件，用inference.pdiparams文件怎么调用呀

### ISSUE THREAD

**Issue by fredhu2009** [PaddlePaddle/PaddleOCR#2954]
想问一下，这三个dir文件里，需要都只有params和model两个文件，没这两个文件，用inference.pdiparams这样的文件报异常。
demo里用到的文件都是params和model。
另外，没有params和model两个文件，下面的怎么配置呢？
det_model_dir ./inference/det_db
cls_model_dir ./inference/cls
rec_model_dir 

> **_./inference/rec_crnn
![zz](https://user-images.githubusercontent.com/76801122/119937801-fe3bfb00-bfbd-11eb-8214-3903f821a8c1.png)
_**

char_list_file ./inference/ppocr_keys_v1.txt
另外，char_list_file这个文件做什么用的，如果我想配置土库曼斯坦国家的语言，怎么配置这个config

**Comment by littletomatodonkey** [comment]
需要下载release/2.1分支下面的代码哈，model和params是静态图的inference model格式文件

**Comment by tink2123** [comment]
土库曼斯坦国家的语言和俄语是一个语系吗？可以试一下这个命令看能否识别：
```
paddleocr --image_dir doc/imgs_words/japan/1.jpg   --det false --lang=ru
```

> 没有params和model两个文件，下面的怎么配置呢？

这两个文件是静态图模型保存的格式，如果要使用静态图模型，请使用release/1.1 版本的代码

**Comment by fredhu2009** [comment]
> 土库曼斯坦国家的语言和俄语是一个语系吗？可以试一下这个命令看能否识别：
> 
> ```
> paddleocr --image_dir doc/imgs_words/japan/1.jpg   --det false --lang=ru
> ```

报错呢

**Comment by tink2123** [comment]
报什么错？安装好ppocr的whl包了吗？
```
pip install "paddleocr>=2.0.6
```

**Comment by fredhu2009** [comment]
> 报什么错？安装好ppocr的whl包了吗？
> 
> ```
> pip install "paddleocr>=2.0.6
> ```

Python已停止工作

**Comment by tink2123** [comment]
没关系啊 运行这个命令去预测是不需要config的

可以参考一下文档去执行：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md

**Comment by fredhu2009** [comment]
> 没关系啊 运行这个命令去预测是不需要config的
> 
> 可以参考一下文档去执行：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md

这些资料都看过，基本上没一个能真正跑起来的。像什么yml文件配置，里面莫名其妙多出其它的文件路径，又没说这些文件是什么样的。

**Comment by tink2123** [comment]
只使用预测的话，是不需要yml文件的，上面的这个文档你尝试过吗？
你希望实现什么功能呢？使用自己的数据训练模型吗？如果希望训练的话，可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/recognition.md
