### ISSUE TITLE
pgnet的C++部署版本有计划推出吗？

### ISSUE THREAD

**Issue by luoyuncen** [PaddlePaddle/PaddleOCR#2956]

**Comment by fredhu2009** [comment]
> _No description provided._

问一下，你的文字训练里用inference.pdiparams这样的文件能调用成功么？我的一直调用不成功。能发个代码参考么？

**Comment by luoyuncen** [comment]
这个直接用官方代码不就可以吗？

**Comment by MissPenguin** [comment]
pgnet暂时没有开发C++版本的计划，欢迎提pr共建~
