### ISSUE TITLE
使用C++和python推理结果不一致，使用官方相同的模型

### ISSUE THREAD

**Issue by RedFree** [PaddlePaddle/PaddleOCR#2958]
使用C++和python推理结果不一致，模型使用官方2.0的模型
![选区_511](https://user-images.githubusercontent.com/5827427/119950859-ec625400-bfcd-11eb-80ce-a4c0d076f633.png)这是python结果。
![选区_512](https://user-images.githubusercontent.com/5827427/119950907-f84e1600-bfcd-11eb-8755-3f8580ec5cbf.png)
这是C++结果，请教下这是什么原因呢？

**Comment by Evezerest** [comment]
1.优先对一下几个阈值参数是否一致；
排查一下c++代码和python代码的预处理和后处理方式是否一致；
用python在模型输入输出各保存一下二进制文件，排除inference的差异性

2.可能是导出的inference model版本与预测库版本需要保持一致，比如在Windows下，Paddle官网提供的预测库版本是1.8，而PaddleOCR提供的inference model 版本是1.7，因此最终预测结果会有差别。可以在Paddle1.8环境下导出模型，再基于该模型进行预测。 此外也需要保证两者的预测参数配置完全一致。
