### ISSUE TITLE
关于通用模型训练时数据量及微调数据量建议

### ISSUE THREAD

**Issue by yxyangxu** [PaddlePaddle/PaddleOCR#2965]
百度Paddle OCR老师们好，想请教3个问题：

1. 看到官方视频说，

> 文字识别预训练模型基于1790万数据训练，又在200万真实数据上微调，识别准确率从65.81提升到69%。

想请教这里的1790万数据来源是什么呢？200万真实数据集是百度内部的吗？使用这200万真实数据微调，就是直接用200万数据做训练吗，想知道微调的更多细节。

2. FAQ文档中说：

> 识别的话，520W左右的数据集（真实数据26W+合成数据500W）训练，超轻量模型：4卡V100，总共训练了5天左右。通用模型：4卡V100，共训练6天。

为什么这里的数据量和问题1里视频中说的不一样呢，我可以以哪个数字为准呢？

3. 如果想要基于百度开源出的预训练模型再次微调进行训练，目的是对打印机中文字符效果更好，一般需要大约多少数据量呢，加入只有1～2万的合成数据，微调会把效果调崩吗？

再次十分感谢百度Paddle OCR老师们的开源工作！！！

**Comment by yxyangxu** [comment]
还是想问下，在各种文档中都看到了微调字样，如果想知道微调的具体操作手段（使用什么样的数据，固定哪些层）有什么指导去处吗？比如某些文档，感谢

**Comment by tink2123** [comment]
以 1 中的数据量为准， 2 中说的是ppocr的初版模型，后面我们经过了迭代优化，目前开放出的模型和官方视频中描述的一致。

微调建议最好使用真实数据，全是合成数据模型比较容易过拟合，真实数据2w这个数据量是可以的。

微调的具体方法：不需要固定层，加载官方提供的预训练模型即可。我们训练的时候采样策略是 真实数据：合成数据=1:1

**Comment by yxyangxu** [comment]
> 以 1 中的数据量为准， 2 中说的是ppocr的初版模型，后面我们经过了迭代优化，目前开放出的模型和官方视频中描述的一致。
> 
> 微调建议最好使用真实数据，全是合成数据模型比较容易过拟合，真实数据2w这个数据量是可以的。
> 
> 微调的具体方法：不需要固定层，加载官方提供的预训练模型即可。我们训练的时候采样策略是 真实数据：合成数据=1:1

感谢老师回复，还想问下老师，
（1）问题1中1790万数据来源是什么呢？是都是造的数据吗？
（2）您提到“采样策略是 真实数据：合成数据=1:1”，想知道准备数据集时，真实数据和合成数据量的比例是多少呢？
（3）就是我没理解您们的流程，您看是这样的对吗：“第一步使用1790万造的数据训练；第二步在200万真实数据集上微调，微调过程是没有固定层，并且微调时也用到了第一步1790万造的数据，只不过采样比例是真实：造的=1：1

**Comment by tink2123** [comment]
1. 1790中基本都是合成数据
2. 真实数据占比越大越好，另外也需要训练模型后在自己的场景上验证，分析badcase后有针对性的增加相应数据
3. 最早我们真实数据比较少，是按你说的这个流程训练的初版模型。后来有针对性的补充了不同场景下的真实数据，第二阶段全部使用真实数据finetune，采样比例按照我们希望的场景做了调整，例如  车牌：票据：街景 = 2:3:5

**Comment by yxyangxu** [comment]
> 1. 1790中基本都是合成数据
> 2. 真实数据占比越大越好，另外也需要训练模型后在自己的场景上验证，分析badcase后有针对性的增加相应数据
> 3. 最早我们真实数据比较少，是按你说的这个流程训练的初版模型。后来有针对性的补充了不同场景下的真实数据，第二阶段全部使用真实数据finetune，采样比例按照我们希望的场景做了调整，例如  车牌：票据：街景 = 2:3:5

想向您请教，关于模型微调遗忘的问题。
您提到“第二阶段全部使用真实数据finetune”，想请教您如果特征场景下的真实数据字符是有针对性的，比如数字占比很大，英文只有几种重复性的单词（即26个字母只有部分出现过），汉字也只有30种（字典里有6000多种）出现，在这样的场景下微调模型，不固定任何层，这样模型不会遗忘吗，就是不会遗忘之前见过的“全部字符”吗

**Comment by yxyangxu** [comment]
还是说，也要看具体的 “场景” ，如果这个场景能覆盖全部的字符（数字、英文、汉字都几乎均匀出现），就可以用来微调？
要是这个“场景”真的很偏颇，就像上面提到的“英文只有几种重复性的单词（即26个字母只有部分出现过），汉字也只有30种（字典里有6000多种）出现”，这样的场景该如何微调呢？

**Comment by Sanster** [comment]
> 还是说，也要看具体的 “场景” ，如果这个场景能覆盖全部的字符（数字、英文、汉字都几乎均匀出现），就可以用来微调？
> 要是这个“场景”真的很偏颇，就像上面提到的“英文只有几种重复性的单词（即26个字母只有部分出现过），汉字也只有30种（字典里有6000多种）出现”，这样的场景该如何微调呢？

字符集差这么多的话感觉直接微调就不合适了，可以减小字符集，加载预训练模型时，把最后一层fc里对应字符的embedding拿出来，再微调
