### ISSUE TITLE
It isn`t addpted on python3.8, 3.9, and should be install paddlepaddle before

### ISSUE THREAD

**Issue by banrieen** [PaddlePaddle/PaddleOCR#2968]
When try it in python3.8 or python3.9 ;Got the error cannot import PaddleOcr； 

then I find that It is adapter only python3.7, within python3.7 env, We must install paddlepaddle before.

Maybe it is info problem, bu it is very confused thad when become install  paddleocr whl packages.

**Comment by tink2123** [comment]
> When try it in python3.8 or python3.9 ;Got the error cannot import PaddleOcr；

Installing the version of ladder 2.1 can solve this problem

>We must install paddlepaddle before.

ppocr  must be installed paddlepaddle ahead of time. We will remind users in this document. Thanks for your feedback.
