### ISSUE TITLE
项目启动训练

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2971]
下载了最新的paddleocr项目，在windows10上环境如下：
            cuda 10.1
            paddle 2.1
            python3.7
，训练集准备好了，配置了一下rec_chinese_lite_train_v2.0.yml，启动训练log如下，想问一下程序为什么不跑呢?
![image](https://user-images.githubusercontent.com/23546166/120136129-46e4f580-c204-11eb-922a-2b3a93e7376f.png)
![image](https://user-images.githubusercontent.com/23546166/120136178-62500080-c204-11eb-87ff-5ad91c979c52.png)
![image](https://user-images.githubusercontent.com/23546166/120136216-6ed45900-c204-11eb-9134-a58befa410f1.png)

**Comment by WenmuZhou** [comment]
请问cuda，cudnn分别是什么版本，paddle的运行检测通过了吗
![image](https://user-images.githubusercontent.com/12406017/120182165-a06b1580-c240-11eb-94fd-7b1531806b9a.png)

**Comment by Sunyingbin** [comment]
> 通过

我把yml配置文件的batch_size_per_card变小了就可以跑了，但是训练速度会变慢

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
