### ISSUE TITLE
使用tensorrt检测结果变差

### ISSUE THREAD

**Issue by chwjshlwel** [PaddlePaddle/PaddleOCR#2973]
同样的图片和模型，只是将config.txt中use_tensorrt 0 变为 use_tensorrt 1，得到的检测结果不一样，请问是哪里设置不对吗？
主要是detection的结果不一样，测试图片很简单，就是一行英文加数字 ABS33CM 16A。
不使用tensorrt 时ABS33CM 16A全部detection成功
使用tensorrt时只检测到CM 16A

**Comment by WenmuZhou** [comment]
tensorrt 目前是将图片resize到特定尺度，和不使用tensorrt的逻辑不一样，这个pr提交了可变长输入的tensorrt代码，建议关注 https://github.com/PaddlePaddle/PaddleOCR/pull/2921

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
