### ISSUE TITLE
python命令行运行识别，出现停止运行，大佬们帮看看是什么问题？

### ISSUE THREAD

**Issue by fredhu2009** [PaddlePaddle/PaddleOCR#2974]
![zzzfff](https://user-images.githubusercontent.com/76801122/120144712-05a91180-c215-11eb-892f-0b6e6ed15910.png)
我用python的命令行运行识别，报异常，命令行如下：
python tools/infer/predict_system.py --image_dir="./tt.jpg" --det_model_dir="./inference/det_db/"  --rec_model_dir="./inference/det_db/" --cls_model_dir="./inference/det_db/" --use_angle_cls=True --use_space_char=False --use_gpu=False

我的 inference/det_db/下的文件都是;inference.pdiparams，inference.pdmodel和inference.pdiparams.info，语言是俄语

**Comment by tink2123** [comment]
> rec_model_dir="./inference/det_db/"

需要使用识别模型，det_db是检测模型

**Comment by fredhu2009** [comment]
我只有官网下载的这三种扩展名的文件，怎么加到识别的程序里做参数，一直报错，没法成功

**Comment by tink2123** [comment]
俄语识别模型：https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/cyrillic_ppocr_mobile_v2.0_rec_infer.tar
字典：dict_path': './ppocr/utils/dict/cyrillic_dict.txt

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
