### ISSUE TITLE
PGNet output/dictionary constraints at inference

### ISSUE THREAD

**Issue by cpene1** [PaddlePaddle/PaddleOCR#2975]
Hi!

Thanks a lot for such a powerfull library! The best out there for sure!

I have a question regarding running the PGNet inference model. Is there any way to restrict the dictionary to some predefined classes? Or at least to restrict it to only numbers? I assume this can be done by training your own network, but is there any way to do this at inference?

Thank you in advance!

**Comment by cpene1** [comment]
Update: I got it to work by altering the file ./ppocr/utils/ic15_dict.txt and left only the digits there.

It seems to work at the beginning, but running in a live video, after a few frames I get the following error:
`
Traceback (most recent call last):
  File "main.py", line 373, in <module>
    main()
  ...
  File "main.py", line 255, in [...]
    points, strs, elapse = text_detector(obj_img)
  File "[...]/PaddleOCR/tools/infer/predict_e2e.py", line 141, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "[...]/PaddleOCR/ppocr/postprocess/pg_postprocess.py", line 49, in __call__
    data = post.pg_postprocess_fast()
  File "[...]/PaddleOCR/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 57, in pg_postprocess_fast
    instance_yxs_list, seq_strs = generate_pivot_list_fast(
  File "[...]/PaddleOCR/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 386, in generate_pivot_list_fast
    decoded_str, keep_yxs_list = ctc_decoder_for_image(
  File "[...]/PaddleOCR/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 118, in ctc_decoder_for_image
    dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
  File "[...]/PaddleOCR/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 118, in <listcomp>
    dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
IndexError: list index out of range
`
My ic15_dict.txt file looks like this now:
`0
1
2
3
4
5
6
7
8
9`

Any reason this might happen? I haven't modified anything else.

Thanks a lot for your support!

**Comment by WenmuZhou** [comment]
You can filter the results during inference and only keep the numbers in the results

**Comment by cpene1** [comment]
Thanks for your reply! Yes I know that and as far as I looked through the source code, that is exactly what ppocr is doing as well, based on the dictionary that is being passed, or the default one.

But do you have any idea the error from above might happen? It might be an error in the code somewhere. I got it to work for my own use, but the Error should not happen there in my opinion.

**Comment by WenmuZhou** [comment]
The above error is because you change the length of the dictionary, but the output length of the model is still the same, there will be an array out of bounds problem

**Comment by cpene1** [comment]
Alright I understand. Thanks you!

**Comment by rsingh2083** [comment]
> Alright I understand. Thanks you!

Hi,
How did you get it working on video ? Even I want to run live OCr on video using paddleOCR but dont know where to start , couldnt find any documentation or example code for video
