### ISSUE TITLE
docker部署ocr的hubserving时出现这样的问题 ，完全按照官方教程走的

### ISSUE THREAD

**Issue by Dacyuan** [PaddlePaddle/PaddleOCR#2976]
![image](https://user-images.githubusercontent.com/33952239/120177297-dd340e00-c23a-11eb-887d-07867f1f3851.png)

**Comment by WenmuZhou** [comment]
这个link要换成你自己下载的模型地址

**Comment by Dacyuan** [comment]
哦哦哦 感谢 可以了~

**Comment by Dacyuan** [comment]
> 这个link要换成你自己下载的模型地址

https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

**Comment by Dacyuan** [comment]
> 这个link要换成你自己下载的模型地址

哦哦哦 感谢 可以了~

**Comment by themantalope** [comment]
@WenmuZhou 我怎么设置这个“link”，“file”的变量？
