### ISSUE TITLE
请问这代表docker服务化部署成功了吗（cpu）

### ISSUE THREAD

**Issue by Dacyuan** [PaddlePaddle/PaddleOCR#2978]
![image](https://user-images.githubusercontent.com/33952239/120197623-c0f09b00-c253-11eb-9fbc-48e34999b08a.png)
gan'm感觉和官方文档里说的不太一样。没有出现http://0.0.0.0:8868/predict/ocr_system

**Comment by tink2123** [comment]
看起来成功了，访问 http://172.17.0.4:8866 能看到内容吗

**Comment by Dacyuan** [comment]
> 看起来成功了，访问 http://172.17.0.4:8866 能看到内容吗
嗯嗯 成功了 但是和官方描述的的不一样。

**Comment by kylewangt** [comment]
这种方式是不是不推荐在生产环境中使用？
