### ISSUE TITLE
when use pip to inference, get wrong about Module Import Error.

### ISSUE THREAD

**Issue by claylau** [PaddlePaddle/PaddleOCR#2979]
### Permise: pip install paddlepaddle paddleocr at windows with python3.8

```python
ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-f0cc890400a6> in <module>
----> 1 from paddleocr import PaddleOCR, draw_ocr
      2 # Paddleocr目前支持中英文、英文、法语、德语、韩语、日语，可以通过修改lang参数进行切换
      3 # 参数依次为`ch`, `en`, `french`, `german`, `korean`, `japan`。
      4 ocr = PaddleOCR(use_angle_cls=True, lang="ch") # need to run only once to download and load model into memory
      5 img_path = '00056221.jpg'
D:\Anaconda\lib\site-packages\paddleocr\__init__.py in <module>
     14 
     15 __all__ = ['PaddleOCR', 'draw_ocr']
---> 16 from .paddleocr import PaddleOCR
     17 from .tools.infer.utility import draw_ocr
D:\Anaconda\lib\site-packages\paddleocr\paddleocr.py in <module>
     26 from tqdm import tqdm
     27 
---> 28 from tools.infer import predict_system
     29 from ppocr.utils.logging import get_logger
     30 
ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
```

**Comment by tink2123** [comment]
You need to run the command in the PaddleOCR/ directory.

tools.infer.predict_system is https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/predict_system.py

**Comment by claylau** [comment]
> You need to run the command in the PaddleOCR/ directory.
> 
> tools.infer.predict_system is https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/predict_system.py

I have tried `python setup.py install` or `pip install paddleocr` to install.
```python
(base) PS C:\Users\claylau\Documents\GitHub\PaddleOCR> python tools/infer/predict_system.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./inference/det_db/" --cls_model_dir="./inference/cls/" --rec_model_dir="./inference/rec_crnn/" --use_angle_cls=true --use_gpu=False
Traceback (most recent call last):
    import tools.infer.utility as utility
ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
```
when i set breakpoint in `tools/infer/predict_system.py` to print `sys.path`
```python
(base) PS C:\Users\claylau\Documents\GitHub\PaddleOCR> python tools/infer/predict_system.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./inference/det_db/" --cls_model_dir="./inference/cls/" --rec_model_dir="./inference/rec_crnn/" --use_angle_cls=true --use_gpu=False
> c:\users\claylau\documents\github\paddleocr\tools\infer\predict_system.py(24)<module>()
-> import cv2
(Pdb) print('\n'.join(sys.path))
C:\Users\claylau\Documents\GitHub\PaddleOCR\tools\infer
D:\Anaconda\python38.zip
D:\Anaconda\DLLs
D:\Anaconda\lib
D:\Anaconda
C:\Users\claylau\AppData\Roaming\Python\Python38\site-packages
D:\Anaconda\lib\site-packages
D:\Anaconda\lib\site-packages\paddleocr-2.0.6-py3.8.egg
D:\Anaconda\lib\site-packages\certifi-2021.5.30-py3.8.egg
D:\Anaconda\lib\site-packages\win32
D:\Anaconda\lib\site-packages\win32\lib
D:\Anaconda\lib\site-packages\Pythonwin
C:\Users\claylau\Documents\GitHub\PaddleOCR\tools\infer
C:\Users\claylau\Documents\GitHub\PaddleOCR
(Pdb)
```
and i run python terminal to import
```python
(base) PS C:\Users\claylau\Documents\GitHub\PaddleOCR> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tools.infer.utility as utility
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
>>> import paddleocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\claylau\Documents\GitHub\PaddleOCR\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package
>>>
```

**Comment by TingquanGao** [comment]
Hi, thx for your feedback. The bug has been fixed. You can refer to https://github.com/PaddlePaddle/PaddleOCR/pull/3447; https://github.com/PaddlePaddle/PaddleOCR/pull/3446  for details. Please try rebuilding whl package and installing.

**Comment by malfonso0** [comment]
hi.. i was trying to install paddleocr on a xavier nx

1. downloaded and installed paddlepaddle_gpu-2.1.1-cp36-cp36m-linux_aarch64.whl
2. tested paddle import and worked
3. git clone https://github.com/PaddlePaddle/PaddleOCR
4. installed all deps
5. pip setup.py install
6. installation is correct
7. python ->from paddleocr import PaddleOCR, draw_ocr
8. got the exact same message as above (ModuleNotFoundError: No module named 'tools.infer'; 'tools' is not a package)

@TingquanGao .. could you provide more details ? are those fix in master ? or still pull from another fork?

thanks in advance for any help

**Comment by malfonso0** [comment]
i have just realized that the error i got is different
  runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iiotbrooksville06/PaddleOCR/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/home/iiotbrooksville06/PaddleOCR/tools/__init__.py", line 15, in <module>
    from . import infer
  File "/home/iiotbrooksville06/PaddleOCR/tools/infer/__init__.py", line 15, in <module>
    from . import predict_cls, predict_det, predict_e2e, predict_rec, predict_system, utility
  File "/home/iiotbrooksville06/PaddleOCR/tools/infer/predict_cls.py", line 30, in <module>
    import tools.infer.utility as utility
AttributeError: module 'tools' has no attribute 'infer'
