### ISSUE TITLE
Performance Issue about DBNet 

### ISSUE THREAD

**Issue by jiangxiluning** [PaddlePaddle/PaddleOCR#2981]
plz ref to MhLiao/DB#259.

**Comment by WenmuZhou** [comment]
感谢，将在验证ok后进行修改

**Comment by jiangxiluning** [comment]
@WenmuZhou There is a bug about eval. Plz ref to  https://github.com/MhLiao/DB/pull/263 . Btw, I checked the metrics of resnet18 on icdar15, everything seems ok.

**Comment by WenmuZhou** [comment]
get

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
