### ISSUE TITLE
标签显示

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#2982]
![image](https://user-images.githubusercontent.com/44855506/120256197-32663300-c2c0-11eb-9e8a-85af695c03d7.png)
请问，这种文字标签显示是用的什么工具显示的啊

**Comment by zcswdt** [comment]
> ![image](https://user-images.githubusercontent.com/44855506/120256197-32663300-c2c0-11eb-9e8a-85af695c03d7.png)
> 请问，这种文字标签显示是用的什么工具显示的啊

你这种你就要读一下代码啊，代码里面写的明明白白的。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
