### ISSUE TITLE
训练模型已经达到一定的准确率并且不收敛了，应该如何操作？

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2985]
关闭训练，这时output下已经生成了best_accuracy.pdopt、best_accuracy.pdparams、best_accuracy.states，在重新启动后yml配置文件中，pretrained_model还是原来的预训练模型不变是吗？checkpoints应该填什么？我才可以根据上次训练到最好的参数基础上继续训练。./output/rec_chinese_lite_v2.0/best_accuracy这样对不？

**Comment by tink2123** [comment]
-o Global.checkpoints=output/rec_chinese_lite_v2.0/best_accuracy 

checkpoint 的优先级高于pretrained_model

**Comment by Sunyingbin** [comment]
> -o Global.checkpoints=output/rec_chinese_lite_v2.0/best_accuracy
> 
> checkpoint 的优先级高于pretrained_model

哦哦，但output下已经生成了best_accuracy.pdopt、best_accuracy.pdparams、best_accuracy.states这三个没有best_accuracy.pdmodel，我理解是不是参数参考checkpoint，模型参考了pretrain_model。

**Comment by tink2123** [comment]
训练过程中，模型就是代码中定义的，训练只会保存参数，不会保存网络结构。如果需要把网络结构固化保存，需要导出inference model。
.pdmodel 是使用inference预测才会用到的

**Comment by Sunyingbin** [comment]
> inference

明白了，非常感谢！！！
