### ISSUE TITLE
gpu训练利用率如何可以提高？

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2986]
你好，采用gpu进行训练，NVIDIA GeForce GTX1080Ti 显卡，gpu的内存利用率最大只有10%，如何能提升利用率呢？
![image](https://user-images.githubusercontent.com/23546166/120272861-4e79cc80-c2e0-11eb-8a21-a73ccba73efe.png)

**Comment by tink2123** [comment]
增大训练的batch_size试下，或者换大的骨干网络

**Comment by Sunyingbin** [comment]
> 增大训练的batch_size试下，或者换大的骨干网络
![image](https://user-images.githubusercontent.com/23546166/120292856-3eb9b280-c2f7-11eb-9e5e-1ab28b9a573f.png)

batch_size_per_card设置成512了，最大显示到了19%，这个参数最多可以设置多少呢？另外num_workers子进程个数最多可以设置成多少呢？

**Comment by Sunyingbin** [comment]
> 增大训练的batch_size试下，或者换大的骨干网络

是专用gpu内存利用率高了，共享gpu内存不变

**Comment by Sunyingbin** [comment]
您好，测试num_workers数目设置成0、2、4、8、16消耗的训练时间是一样的，这是为什么？

**Comment by Evezerest** [comment]
你的显卡是单卡，12G内存吧？
