### ISSUE TITLE
srn ResNetFPN训练异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleOCR#2987]
配置文件
Global:
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: /home/aistudio/output/rec_chinese_lite_v2.0
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 20]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: 
  save_inference_dir:
  use_visualdl: True
  infer_img: /home/aistudio/TestA_000001.jpg
  # for data or label process
  character_dict_path: /home/aistudio/PaddleOCR-release-2.1/ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: /home/aistudio/output/rec/predicts_chinese_lite_v2.0.txt
  num_heads: 8

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 3
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

ResNetFPN:
  layers: 18

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data/TrainImages
    label_file_list: ["/home/aistudio/data/LabelTrain_f5_1_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data/TrainImages
    label_file_list: ["/home/aistudio/data/LabelTrain_f5_1_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 0

异常信息
Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR-release-2.1/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR-release-2.1/tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR-release-2.1/tools/program.py", line 227, in train
    preds = model(images, others)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR-release-2.1/ppocr/modeling/architectures/base_model.py", line 74, in forward
    x = self.backbone(x)
  File "/home/aistudio/PaddleOCR-release-2.1/ppocr/modeling/backbones/rec_resnet_fpn.py", line 150, in __call__
    x = self.conv(x)
  File "/home/aistudio/PaddleOCR-release-2.1/ppocr/modeling/backbones/rec_resnet_fpn.py", line 212, in __call__
    x = self.conv(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 660, in forward
    use_cudnn=self._use_cudnn)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1, the input's shape is [256, 1, 64, 256]; the filter's channels is 3, the filter's shape is [64, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:96)
  [

**Comment by tink2123** [comment]
image shape 需要修改为 [1,64,256] 暂时不支持输入通道数为3
