### ISSUE TITLE
SRN中的cross-attention问题

### ISSUE THREAD

**Issue by simplify23** [PaddlePaddle/PaddleOCR#2990]
我在SRN的self-attention中看到了非常有趣的代码部分，有对cross-attention的选择代码，想问一下cross-attention比起self-attention性能如何。另外如果我想调用cross-attention的代码，需要再cache里增加部分，即增加先验的信息atten_bais,想问一下这一信息上应该加什么值，才能调用cross-attention的代码。非常感谢~
![image](https://user-images.githubusercontent.com/39580716/120289810-4592f600-c2f4-11eb-8451-bc17cc15091d.png)
![image](https://user-images.githubusercontent.com/39580716/120290001-7c690c00-c2f4-11eb-94b5-5e60e40fb226.png)

**Comment by tink2123** [comment]
抱歉回复晚了～ cross-attention 的效果我们没有实验过，主要关注的self-attention的方式。代码中提供的两种实现方式，是参考Paddle代码实现的，因此保留了croos-attention分支。
感兴趣的话您可以尝试下效果，调用方式可参考：https://github.com/PaddlePaddle/Paddle/blob/6550c203fa1f22e1a0dd7679ae935eb2d973ff6a/python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py#L305

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
