### ISSUE TITLE
试验了下单张图片的合成效果，并不好，求解释

### ISSUE THREAD

**Issue by SharonJin422** [PaddlePaddle/PaddleOCR#2991]
![image](https://user-images.githubusercontent.com/85158796/120291779-43319b80-c2f6-11eb-8cfb-e7492272fa39.png)
上图是分离的背景图，但是银行卡上的数字还是存在

合成的图片上文字重叠了

**Comment by weisy11** [comment]
这张图效果确实是不太好，我们记录一下badcase

**Comment by SharonJin422** [comment]
有新的微信进去二维码吗

**Comment by weisy11** [comment]
扫描现在首页README的二维码，可以进最新的微信群

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
