### ISSUE TITLE
有新的进群二维码吗

### ISSUE THREAD

**Issue by SharonJin422** [PaddlePaddle/PaddleOCR#2993]
想请教下源码是不是没有提供自己训练模型的入口
看到源码中有网络结构，但是新手，还不会自己写训练代码

**Comment by MissPenguin** [comment]
文档中都有教程的，照着操作就好啦：
![image](https://user-images.githubusercontent.com/25809855/120433412-c3ff9e80-c3ad-11eb-9c8c-f7d7f04e4333.png)

**Comment by SharonJin422** [comment]
不是文字识别和检测，是数据合成工具，因为我尝试了几个图片，合成效果并不好，想试一下扩充风格图片，看看效果如何
![image](https://user-images.githubusercontent.com/85158796/120434077-936c3480-c3ae-11eb-9c22-0087f2d51afc.png)

**Comment by MissPenguin** [comment]
style-text暂时没有开源训练代码哈，可以看下是怎样的图片效果不好吗，我们可以先分析下问题。

**Comment by SharonJin422** [comment]
是合成银行卡的图片，不知道为什么贴不上图片了，可以看下我提交的另一个issue #2991 （https://github.com/PaddlePaddle/PaddleOCR/issues/2991）里面有

**Comment by MissPenguin** [comment]
> #2991

收到，看到相关负责同学回复你了，这确实是个badcase，我们只能先记录，后续再优化了

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
