### ISSUE TITLE
RARE MobileNetV3训练异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleOCR#2994]
配置文件
Global:
  use_gpu: True
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /home/aistudio/output/predicts_mv3_tps_bilstm_att
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 40]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: True
  infer_img: /home/aistudio/TestA_000001.jpg
  # for data or label process
  character_dict_path: /home/aistudio/PaddleOCR-release-2.1/ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: /home/aistudio/output/rec/predicts_mv3_tps_bilstm_att.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: RARE
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: small
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn 
    hidden_size: 96
  Head:
    name: AttentionHead  
    hidden_size: 96
    

Loss:
  name: AttentionLoss

PostProcess:
  name: AttnLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data/TrainImages
    label_file_list: ["/home/aistudio/data/LabelTrain_f5_1_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data/TrainImages
    label_file_list: ["/home/aistudio/data/LabelTrain_f5_1_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 0

异常信息
2021-06-01 17:48:02,043 - WARNING - DataLoader reader thread raised an exception.
[WARNING 2021-06-01 17:48:02,043 dataloader_iter.py:345] DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR-release-2.1/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR-release-2.1/tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR-release-2.1/tools/program.py", line 213, in train
    for idx, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 346, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 65, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 90, in default_collate_fn
    tmp = np.stack(slot, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by MissPenguin** [comment]
看下贡献内存的空间（shm size）有多大，一般建议8G以上。

**Comment by bbbxixixixi** [comment]
> 看下贡献内存的空间（shm size）有多大，一般建议8G以上。

这个是aistudio环境，ipcs -m打印了如下信息
------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status  

没显示别的

**Comment by MissPenguin** [comment]
> > 看下贡献内存的空间（shm size）有多大，一般建议8G以上。
> 
> 这个是aistudio环境，ipcs -m打印了如下信息
> ------ Shared Memory Segments --------
> key shmid owner perms bytes nattch status
> 
> 没显示别的

df -lh 看下

**Comment by bbbxixixixi** [comment]
> > > 看下贡献内存的空间（shm size）有多大，一般建议8G以上。
> > 
> > 
> > 这个是aistudio环境，ipcs -m打印了如下信息
> > ------ Shared Memory Segments --------
> > key shmid owner perms bytes nattch status
> > 没显示别的
> 
> df -lh 看下

Filesystem      Size  Used Avail Use% Mounted on
overlay         493G  347G  121G  75% /
tmpfs            64M     0   64M   0% /dev
tmpfs            56G     0   56G   0% /sys/fs/cgroup
/dev/vdb        775G  174G  562G  24% /home/aistudio
/dev/vdd1       493G  347G  121G  75% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            56G   12K   56G   1% /proc/driver/nvidia
/dev/vda1        39G   17G   23G  44% /usr/bin/nvidia-smi
tmpfs            12G  178M   11G   2% /run/nvidia-persistenced/socket
udev             56G     0   56G   0% /dev/nvidia0
tmpfs            56G     0   56G   0% /proc/acpi
tmpfs            56G     0   56G   0% /proc/scsi
tmpfs            56G     0   56G   0% /sys/firmware

shm 64m，难道说aistudio不能训练这种配置吗？

**Comment by zhangyinzhangyin** [comment]
> > > > 看下贡献内存的空间（shm size）有多大，一般建议8G以上。
> > > 
> > > 
> > > 这个是aistudio环境，ipcs -m打印了如下信息
> > > ------ Shared Memory Segments --------
> > > key shmid owner perms bytes nattch status
> > > 没显示别的
> > 
> > 
> > df -lh 看下
> 
> Filesystem Size Used Avail Use% Mounted on
> overlay 493G 347G 121G 75% /
> tmpfs 64M 0 64M 0% /dev
> tmpfs 56G 0 56G 0% /sys/fs/cgroup
> /dev/vdb 775G 174G 562G 24% /home/aistudio
> /dev/vdd1 493G 347G 121G 75% /etc/hosts
> shm 64M 0 64M 0% /dev/shm
> tmpfs 56G 12K 56G 1% /proc/driver/nvidia
> /dev/vda1 39G 17G 23G 44% /usr/bin/nvidia-smi
> tmpfs 12G 178M 11G 2% /run/nvidia-persistenced/socket
> udev 56G 0 56G 0% /dev/nvidia0
> tmpfs 56G 0 56G 0% /proc/acpi
> tmpfs 56G 0 56G 0% /proc/scsi
> tmpfs 56G 0 56G 0% /sys/firmware
> 
> shm 64m，难道说aistudio不能训练这种配置吗？

请问解决了吗？

**Comment by bbbxixixixi** [comment]
> > > > > 看下贡献内存的空间（shm size）有多大，一般建议8G以上。
> > > > 
> > > > 
> > > > 这个是aistudio环境，ipcs -m打印了如下信息
> > > > ------ Shared Memory Segments --------
> > > > key shmid owner perms bytes nattch status
> > > > 没显示别的
> > > 
> > > 
> > > df -lh 看下
> > 
> > 
> > Filesystem Size Used Avail Use% Mounted on
> > overlay 493G 347G 121G 75% /
> > tmpfs 64M 0 64M 0% /dev
> > tmpfs 56G 0 56G 0% /sys/fs/cgroup
> > /dev/vdb 775G 174G 562G 24% /home/aistudio
> > /dev/vdd1 493G 347G 121G 75% /etc/hosts
> > shm 64M 0 64M 0% /dev/shm
> > tmpfs 56G 12K 56G 1% /proc/driver/nvidia
> > /dev/vda1 39G 17G 23G 44% /usr/bin/nvidia-smi
> > tmpfs 12G 178M 11G 2% /run/nvidia-persistenced/socket
> > udev 56G 0 56G 0% /dev/nvidia0
> > tmpfs 56G 0 56G 0% /proc/acpi
> > tmpfs 56G 0 56G 0% /proc/scsi
> > tmpfs 56G 0 56G 0% /sys/firmware
> > shm 64m，难道说aistudio不能训练这种配置吗？
> 
> 请问解决了吗？

几天前试过，没解决

**Comment by LDOUBLEV** [comment]
共享内存比较小时（/dev/shm 目录的内存小于4G），设置Dataloader的use_shared_memory为False
https://github.com/PaddlePaddle/PaddleOCR/blob/e10128ac4c8218beb15187ba460eabb149c7270c/configs/det/det_mv3_db.yml#L103

**Comment by thomaszheng** [comment]
@bbbxixixixi 你试试这个修改  #3455
