### ISSUE TITLE
使用推荐的ch_ppocr_server_v2.0_rec_pre预训练模型跑最新的paddleocr项目报如下错误

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2995]
用的yml配置文件是：rec_chinese_lite_train_v2.0.yml，预训练模型放在了checkpoints属性上
![image](https://user-images.githubusercontent.com/23546166/120310583-205cb280-c309-11eb-9e77-e169692cc6eb.png)
提示优化器有问题？

**Comment by tink2123** [comment]
预训练模型需要使用 -o Gloabl.pretrained_mode 的方式加载，checkpoint是断点加载

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
