### ISSUE TITLE
Cannot load cudnn shared library

### ISSUE THREAD

**Issue by arufus** [PaddlePaddle/PaddleOCR#300]
----------------------
Error Message Summary:
----------------------
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

参考installation.md流程走的，没有建docker容器，直接用conda新建了虚拟环境。
python3 -m pip install paddlepaddle-gpu==1.7.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple
cuda版本是10.2，感谢！

**Comment by littletomatodonkey** [comment]
1. 没有用docker的话，需要把cudnn lib添加到`LD_LIBRARY_PATH`中去。
2. 还是建议在docker中操作，环境统一，方便debug~
