### ISSUE TITLE
怎么用PPOCRLabel工具把全标注的3w张文字检测数据集，转化成文字识别数据集啊？

### ISSUE THREAD

**Issue by wumeizhi** [PaddlePaddle/PaddleOCR#3000]
我把文字检测的标注txt文件按照PPOCRLabel需要的Label格式转化了，用PPOCRLabel打开对应的目录发现，Label.txt里的数据是读取了，但是在识别结果那一栏，全都是没有打勾的选项，要我一个一个打勾然后点确认才能最后转成分割了的图片的文字识别数据集，但是3w张图片我一个人完全点不完啊。
然后我在代码里找了一下，把那个识别结果的默认勾选设置好，结果勾是勾上了，但是点完确认，保存识别结果的时候，并没有正确的保存分割了的图片的文字识别数据集，好像是必须要手动点一下那个复选框才能保存分割后的图片。

**Comment by chocolate-byte** [comment]
txt文本直接复制一串改不就好了，就一个文件。。会的话python直接打印前面的一串地址信息，后面的字符还要人工写

**Comment by wumeizhi** [comment]
> txt文本直接复制一串改不就好了，就一个文件。。会的话python直接打印前面的一串地址信息，后面的字符还要人工写

就是标注文件已经把字符都写好了，像这样：
icdar_c4_train_imgs/gt_8004.jpg	[{"transcription": "\u8863\u54c1\u8f69", "points": [[4, 297], [401, 277], [398, 370], [1, 384]], "difficult": "false"}, {"transcription": "\u957f", "points": [[641, 260], [757, 255], [757, 377], [654, 382]], "difficult": "false"}, {"transcription": "###", "points": [[186, 857], [203, 864], [181, 922], [165, 913]], "difficult": "false"}, {"transcription": "###", "points": [[251, 850], [275, 850], [275, 856], [251, 858]], "difficult": "false"}, {"transcription": "###", "points": [[169, 559], [198, 559], [199, 569], [168, 570]], "difficult": "false"}]
transcription就是校验过的字符不需要再手动矫正了，问题就是我用PPOCRLabel读取之后，还需要手动点那个识别结果下面的复选框按钮才能保存识别结果（就是一个分割好的图片的文件夹和识别标注文件）

**Comment by wumeizhi** [comment]
> txt文本直接复制一串改不就好了，就一个文件。。会的话python直接打印前面的一串地址信息，后面的字符还要人工写

刚刚试了把PPOCRLabel.py里的1978行注释掉：#if label['difficult']: continue ，问题就解决了。
感觉difficult这个字段的用法好奇怪，感觉代码里完全没用上。

**Comment by Evezerest** [comment]
你好，
difficult是对于一些比较难以识别的文字设计的，进而可以导出部分识别结果。
在正常的逻辑下，识别结果前的复选框是被默认勾选的，但目前这种情况属于使用外部的txt结果来用PPOCRLabel加工，因此没有读入txt中的difficult参数，这一点后续我们会优化一下。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
