### ISSUE TITLE
Word Level Coordinates

### ISSUE THREAD

**Issue by rajathjain** [PaddlePaddle/PaddleOCR#3001]
Is there a way to get word level coordinates for chinese text

**Comment by LDOUBLEV** [comment]
It is not supported that predict word-level text boxes for now.

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
