### ISSUE TITLE
C++部署说明文档出现错误？

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3004]
![image](https://user-images.githubusercontent.com/29808550/120460213-801b9200-c3cb-11eb-9d51-331062260aa9.png)
将模型导出为inference model，对应的格式不应该是如下么
inference/det_db/
    ├── inference.pdiparams         # 检测inference模型的参数文件
    ├── inference.pdiparams.info    # 检测inference模型的参数信息，可忽略
    └── inference.pdmodel           # 检测inference模型的program文件

文档链接：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/readme.md#21-%E5%B0%86%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%BAinference-model

**Comment by MissPenguin** [comment]
感谢反馈，你这个是对的，.info这个文件是因为没什么用所以没写，另外两个有书写错误，已修正。
