### ISSUE TITLE
No version of opencv-python 4.2.0.32

### ISSUE THREAD

**Issue by mhashas** [PaddlePaddle/PaddleOCR#3005]
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from paddleocr) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52)
ERROR: No matching distribution found for opencv-python==4.2.0.32

I have also tried

python -m pip install opencv-python==4.2.0.32 -i https://mirror.baidu.com/pypi/simple

**Comment by LDOUBLEV** [comment]
May be the web problem, I can download from pypi. Try this download link

https://mirror.baidu.com/pypi/packages/34/a3/403dbaef909fee9f9f6a8eaff51d44085a14e5bb1a1ff7257117d744986a/opencv_python-4.2.0.32-cp37-cp37m-manylinux1_x86_64.whl

**Comment by mhashas** [comment]
seems its because of the python version, as I was using 3.9. Are there any plans to remove this dependency in the future?
