### ISSUE TITLE
弯曲文本识别中的一点疑问

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#3007]
PGNet使用中文弯曲数据集去训练效果不是很好，但是检测的效果还不错，那我可不可以使用PGNet去检测文本，使用StarNet等带有tps模块的识别算法识别呢？由于PGNet是端到端的，只用来检测文本可行吗？后面可以串联推理嘛？

**Comment by LDOUBLEV** [comment]
PGNet用做中文识别也是可以的，但是识别字符的数量非常多可能会导致不好训练，检测是可以的，不依赖字符数量，

> 那我可不可以使用PGNet去检测文本，使用StarNet等带有tps模块的识别算法识别呢？由于PGNet是端到端的，只用来检测文本可行吗？后面可以串联推理嘛？

思路是可行的，可以使用PGNet获得检测坐标点

**Comment by chujian521** [comment]
非常感谢，那请问串联推理的时候是直接指定--det_model_dir为训练好的PGNet的模型吗？

**Comment by chujian521** [comment]
好像是不可以的，因为PGNet是端到端的，不能当det模型去用啊

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by yjmm10** [comment]
> 我最近在用pgnet训练印章识别，也是，检测的效果比较好，识别一塌糊涂

你现在检测的效果怎么样，可以交流一下吗

**Comment by kylewangt** [comment]
> 

能交流下吗，我也有同样需求

**Comment by kylewangt** [comment]
> > 我最近在用pgnet训练印章识别，也是，检测的效果比较好，识别一塌糊涂
> 
> 你现在检测的效果怎么样，可以交流一下吗

能交流下吗，我也有同样需求
