### ISSUE TITLE
CMake Error at CMakeLists.txt:47 (find_package):  Could not find a package configuration file provided by "OpenCV" 

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3009]
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:47 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.17)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
请问以上可能是什么原因？
centos系统 paddle 2.1

**Comment by LDOUBLEV** [comment]
编译的时候有没有正确指定opencv的package路径，[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/deploy/cpp_infer/tools/build.sh#L1)需要设置编译好的opencv

![image](https://user-images.githubusercontent.com/26592129/120596815-c679fb00-c476-11eb-9686-9cb922cf3b87.png)

**Comment by ymzx** [comment]
> 编译的时候有没有正确指定opencv的package路径，[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/deploy/cpp_infer/tools/build.sh#L1)需要设置编译好的opencv
> 
> ![image](https://user-images.githubusercontent.com/26592129/120596815-c679fb00-c476-11eb-9686-9cb922cf3b87.png)

有的，严格按照贵司提供的文档操作的，CMakeLists.txt中
![image](https://user-images.githubusercontent.com/29808550/120599724-70a75200-c47a-11eb-98d4-8ff1e58a6886.png)
这个路径下并没有.cmake文件

**Comment by yangy996** [comment]
> 编译的时候有没有正确指定opencv的package路径，[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/deploy/cpp_infer/tools/build.sh#L1)需要设置编译好的opencv
> 
> ![image](https://user-images.githubusercontent.com/26592129/120596815-c679fb00-c476-11eb-9686-9cb922cf3b87.png)
windows下编译也报这个错，不知道哪配置的不对
![image](https://user-images.githubusercontent.com/15188456/188791573-635db638-612e-415e-bcc8-a63f6ba95718.png)
