### ISSUE TITLE
动态图分支tensorrt跑不通

### ISSUE THREAD

**Issue by Hubert2102** [PaddlePaddle/PaddleOCR#3010]
--use_tensorrt=True
报错
 File "/export/xufulai/PaddleOCR-dygraph/tools/infer/utility.py", line 242, in create_predictor
predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:238)
请问下是什么原因呢？

**Comment by Hubert2102** [comment]
将min_subgraph_size从3调到15，报错如下？

  File "/export/xufulai/PaddleOCR-dygraph/tools/infer/predict_cls.py", line 102, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) TRT runtime input shape of x is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime inputshape = [3, 3, 48, 192], min input shape = [6, 3, 48, 10], max input shape = [6, 3, 48, 2000].
  [Hint: Expected is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape) == true, but received is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape):0 != true:1.] (at /paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:124)

**Comment by LDOUBLEV** [comment]
> ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.

用的模型中有一些参数的shape需要设置动态shape，解决步骤：
1. 屏蔽[disable_glog_info()](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/tools/infer/utility.py#L154);
2. 重新运行预测，此时报错信息会多一些，并且会提到哪个参数没有设置动态shape，设置这个参数的min max opt_shape；
3. 重新执行预测

**Comment by Hubert2102** [comment]
> > ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
> 
> 用的模型中有一些参数的shape需要设置动态shape，解决步骤：
> 
> 1. 屏蔽[disable_glog_info()](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/tools/infer/utility.py#L154);
> 2. 重新运行预测，此时报错信息会多一些，并且会提到哪个参数没有设置动态shape，设置这个参数的min max opt_shape；
> 3. 重新执行预测

我用到的是server common模型，将min_subgraph_size从3调到15，这个报错就没有了。但是会有新的问题就是上面提到的“ Expect runtime input shape to be within min/max input shape”。
后来发现是说假如，分类、识别模型的batch设置为6，初始化引擎时min_input_shape = {"x": [args.rec_batch_num, 3, 32, 10]}，
            min_input_shape = {"x": [args.rec_batch_num, 3, 32, 10]}
此时如果检测出来的文本数量是27，则27/6=4...3,也就是说最后一个batch预测输入shape是[3, 3, 48, 192]，产生上面的报错。

此时我是不是应该将最后的一个batch加一些空白样本来解决尾部不能整除batch的TRT推理？

**Comment by Hubert2102** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/tools/infer/predict_system.py#L102
在这后面加了
        padsam_num = args.rec_batch_num - (len(img_crop_list) % args.rec_batch_num)
        for i in range(padsam_num):
            tmp = np.zeros([100, 32, 3], np.uint8)
            img_crop_list.append(tmp)
做预测，预测之后截取：
rec_res = rec_res[0:len(dt_boxes)]
跑通了

**Comment by LDOUBLEV** [comment]
> 我用到的是server common模型，将min_subgraph_size从3调到15，这个报错就没有了

这是一个规避手段，可能影响加速比

**Comment by Hubert2102** [comment]
> > 我用到的是server common模型，将min_subgraph_size从3调到15，这个报错就没有了
> 
> 这是一个规避手段，可能影响加速比

确实，有这个问题。

但是min_subgraph_size从3，为什么检测模型网络维数不对的，这个能帮忙看看应该往哪个方向上改？多谢~
I0603 18:02:35.068974  6040 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 13 nodes
I0603 18:02:35.071635  6040 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E0603 18:02:35.073755  6040 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): kernel weights has count 147456 but 55296 was expected
E0603 18:02:35.073796  6040 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): count of 147456 weights in kernel, but kernel dimensions (3,3) with 96 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 96 * 3*3 * 64 / 1 = 55296
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 202, in <module>
    text_detector = TextDetector(args)
  File "tools/infer/predict_det.py", line 100, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/export/xufulai/PaddleOCR-dygraph/tools/infer/utility.py", line 242, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) The Bias's size(64) should be equal to the first dim(0) of the Input.
  [Hint: Expected Y_t->dims()[0] == dims_x.d[1], but received Y_t->dims()[0]:64 != dims_x.d[1]:0.] (at /paddle/paddle/fluid/inference/tensorrt/convert/elementwise_op.cc:100)

**Comment by Hubert2102** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/tools/infer/utility.py#L189
应该是elif

**Comment by jackiezzq** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/tools/infer/utility.py#L189
> 
> 
> 应该是elif

哈哈，我跟你踩了一样的坑，还差不多同时发现的

**Comment by Hubert2102** [comment]
> > https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/tools/infer/utility.py#L189
> > 
> > 应该是elif
> 
> 哈哈，我跟你踩了一样的坑，还差不多同时发现的

你直接跑官方提供的inference模型TRT推理能跑通么？有遇到维度不对的问题么？

**Comment by jackiezzq** [comment]
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/tools/infer/utility.py#L189
> > > 
> > > 应该是elif
> > 
> > 
> > 哈哈，我跟你踩了一样的坑，还差不多同时发现的
> 
> 你直接跑官方提供的inference模型TRT推理能跑通么？有遇到维度不对的问题么？

也是把将min_subgraph_size从3调到15将min_subgraph_size从3调到15，然后把那个if改了就正常了

**Comment by Hubert2102** [comment]
> > > > https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/tools/infer/utility.py#L189
> > > > 
> > > > 应该是elif
> > > 
> > > 
> > > 哈哈，我跟你踩了一样的坑，还差不多同时发现的
> > 
> > 
> > 你直接跑官方提供的inference模型TRT推理能跑通么？有遇到维度不对的问题么？
> 
> 也是把将min_subgraph_size从3调到15将min_subgraph_size从3调到15，然后把那个if改了就正常了

这样加速效果感觉不太明显。。。

**Comment by shihaitao118** [comment]
> rec_res = rec_res[0:len(dt_boxes)]



> --use_tensorrt=True 报错 File "/export/xufulai/PaddleOCR-dygraph/tools/infer/utility.py", line 242, in create_predictor predictor = inference.create_predictor(config) ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details. [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:238) 请问下是什么原因呢？

你好，我最近使用paddle ocr 2.5 版本tensorrt加速时，遇到了这个问题（链接： https://github.com/PaddlePaddle/PaddleOCR/issues/6663 ），能否帮忙一起看下

**Comment by shihaitao118** [comment]
> > ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
> 
> 用的模型中有一些参数的shape需要设置动态shape，解决步骤：
> 
> 1. 屏蔽[disable_glog_info()](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/tools/infer/utility.py#L154);
> 2. 重新运行预测，此时报错信息会多一些，并且会提到哪个参数没有设置动态shape，设置这个参数的min max opt_shape；
> 3. 重新执行预测

你好，我最近使用paddle ocr 2.5 版本tensorrt加速时，遇到了这个问题（链接： https://github.com/PaddlePaddle/PaddleOCR/issues/6663 ），能否帮忙一起看下
