### ISSUE TITLE
小数点识别不准

### ISSUE THREAD

**Issue by chocolate-byte** [PaddlePaddle/PaddleOCR#3012]
因为mobilenetv3轻量版对小数点识别效果不佳，在训练针对印刷体数字小数点用了脚本生成的数据集，但还是发现其中的小数点识别不太准，一个会判断为两个点，想问一下有什么方法加强吗，因为mobilnetV3的通用模型识别小数点就非常好，但是速度就不如预期。
[2021/06/03 09:28:13] root INFO: 9942..52, 0.966

另外想问一下多进程同步可以做到识别时间减半吗，想通过多进程减少识别的时间。

**Comment by LDOUBLEV** [comment]
你是CPU预测还是GPU预测？

CPU上要实现速度优化，要开启mkldnn，并设置较大的[线程数](https://github.com/PaddlePaddle/PaddleOCR/blob/84445cc4732ccfb9c8e655e11f5f2961faf4074e/tools/infer/utility.py#L143)，如果有资源，可以设置为10；

另外，可以调整识别的batchsize加速计算，不算是一个加速手段，在某些情况下，不同batch预测时间还有有差距的，你可以设置一个符合你环境的batch

GPU上可以用TRT加速

**Comment by chocolate-byte** [comment]
我用的是cpu，但是预测视频时据说python的线程锁优化似乎不高，所以在考虑是不是需要多进程同步运算

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
