### ISSUE TITLE
linux 如何确定 CUDNN_LIB_DIR的库路径

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3013]
![image](https://user-images.githubusercontent.com/29808550/120579787-ae947e00-c45a-11eb-9dd3-eb725cd54199.png)
centos 如何找到 CUDNN_LIB_DIR的库路径，能确定cudnn已安装。

**Comment by LDOUBLEV** [comment]
找你cudnn安装的路径
一般是在/usr/include 或
/usr/local/cuda/include
或
/usr/lib/x86_64-linux-gnu/
