### ISSUE TITLE
Could not find a package configuration file provided by "OpenCV" with any of the following names

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3016]
按照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/cpp_infer/readme.md 实践C++部署，总提示报错如下：
CMake Error at CMakeLists.txt:48 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake
48行如下：
find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/share/OpenCV NO_DEFAULT_PATH)
opencv4.2.0,编译完后，在库文件路径/home/ocr/opencv-4.2.0/opencv3下确实没找到OpenCVConfig.cmake或者opencv-config.cmake，为什么？opencv编译安装后，安装文件路径为/home/ocr/opencv-4.2.0/opencv3，其目录：
[root@cloud-gpu02 opencv3]# ll
total 4
drwxrwxr-x 2 ocr ocr  148 Jun  1 18:17 bin
drwxrwxr-x 3 ocr ocr   21 Jun  1 18:17 include
drwxrwxr-x 3 ocr ocr   23 Jun  1 18:17 lib
drwxrwxr-x 4 ocr ocr 4096 Jun  1 18:17 lib64
drwxrwxr-x 4 ocr ocr   37 Jun  1 18:17 share
 这些文件中确实没有cmake文件，请问这是为什么？如何处理？

**Comment by LDOUBLEV** [comment]
> find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/share/OpenCV NO_DEFAULT_PATH)

确认下/home/ocr/opencv-4.2.0/opencv3/share/OpenCV  目录下有没有.cmake文件

![image](https://user-images.githubusercontent.com/26592129/120599474-2625d580-c47a-11eb-95d5-d92c8bd0a9d7.png)

**Comment by ymzx** [comment]
> > find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/share/OpenCV NO_DEFAULT_PATH)
> 
> 确认下/home/ocr/opencv-4.2.0/opencv3/share/OpenCV 目录下有没有.cmake文件
> 
> ![image](https://user-images.githubusercontent.com/26592129/120599474-2625d580-c47a-11eb-95d5-d92c8bd0a9d7.png)

确认过，并没有，所以很困惑
![image](https://user-images.githubusercontent.com/29808550/120600539-794c5800-c47b-11eb-8fcf-3e9b96455588.png)
但是在以下路径可以找到
![image](https://user-images.githubusercontent.com/29808550/120600646-997c1700-c47b-11eb-8985-2b31f34f22b4.png)

**Comment by ymzx** [comment]
opencv编译安装路径如下
![image](https://user-images.githubusercontent.com/29808550/120601061-11e2d800-c47c-11eb-9f1f-106806316629.png)
