### ISSUE TITLE
enable_mkldnn=true,需要在本地安装mkl库吗，为何我直接可以运行

### ISSUE THREAD

**Issue by whz11** [PaddlePaddle/PaddleOCR#3017]
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
控制台输出这个是成功了吗

**Comment by LDOUBLEV** [comment]
> 控制台输出这个是成功了吗

这里看上去没问题，如果有输出，没报错就可以，目前看上去mkldnn没问题
一般不需要手动安装mkldnn

**Comment by whz11** [comment]
> > 控制台输出这个是成功了吗
> 
> 这里看上去没问题，如果有输出，没报错就可以，目前看上去mkldnn没问题
> 一般不需要手动安装mkldnn

OK，非常感谢，可以正常使用，但是时间上没有明显的下降，一张200kb的图片，识别要5s

**Comment by LDOUBLEV** [comment]
预测一张图看不出来，第一张图需要做模型初始化，多预测几张试试

**Comment by whz11** [comment]
> 预测一张图看不出来，第一张图需要做模型初始化，比较耗时，多预测几张试试

嗯嗯，非常感谢

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
