### ISSUE TITLE
centos gpu 如何设置tools/build.sh on和off？官方已给出的为cpu配置

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3019]
tools/build.sh如下：
‘’‘
OPENCV_DIR=your_opencv_dir
LIB_DIR=your_paddle_inference_dir
CUDA_LIB_DIR=your_cuda_lib_dir
CUDNN_LIB_DIR=/your_cudnn_lib_dir

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DDEMO_NAME=ocr_system \
    -DWITH_GPU=OFF \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \

make -j
’‘’
linux GPU 下，设置为：
    -DWITH_MKL=OFF \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
这样可以么？有参数说明文档么？

**Comment by LDOUBLEV** [comment]
-DWITH_GPU=ON

执行预测的时候把 [use_gpu ](https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/deploy/cpp_infer/tools/config.txt#L2)设置为1 并指定[gpu_id](https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/deploy/cpp_infer/tools/config.txt#L3)

**Comment by ymzx** [comment]
> -DWITH_GPU=ON
> 
> 执行预测的时候把 [use_gpu ](https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/deploy/cpp_infer/tools/config.txt#L2)设置为1 并指定[gpu_id](https://github.com/PaddlePaddle/PaddleOCR/blob/389e7f57281d405b6beda605bed06432cf588a55/deploy/cpp_infer/tools/config.txt#L3)

仅需要把DWITH_GPU=ON， 其它参数均不变，例如DWITH_MKL还是设置为ON？

**Comment by LDOUBLEV** [comment]
DWITH_MKL设置为ON 是指在CPU上开启MKLDNN加速，和GPU没关系
