### ISSUE TITLE
C++编译问题[CMakeFiles/ocr_system.dir/all] Error 2

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3020]
[root@cloud-gpu02 cpp_infer]# sh tools/build.sh 
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/ocr/opencv-4.2.0/opencv3 (found version "4.2.0") 
cmake cxx flags -g -o3 -fopenmp -std=c++11
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.17)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:212 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "ocr_system" links to some libraries for which the linker
  must search:

    glog, gflags, protobuf, z, xxhash, -ldl -lrt -lgomp -lz -lm -lpthread, dl
    m, pthread, rt

  and other libraries with known full path:

    /home/ocr/paddle_infer_cpp/paddle_inference/third_party/install/mklml/lib/libiomp5.so
    /home/ocr/paddle_infer_cpp/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0
    /usr/local/cuda/lib64/libcudart.so
    /home/ocr/opencv-4.2.0/opencv3/lib64/libopencv_calib3d.a
    /home/ocr/opencv-4.2.0/opencv3/lib64/opencv4/3rdparty/liblibprotobuf.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_TENSORRT

Build files have been written to: /home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/builcanning dependencies of target ocr_system
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[100%] Linking CXX executable ocr_system
CMakeFiles/ocr_system.dir/src/ocr_cls.o: In function `PaddleOCR::Classifier::Run(cv::Mat&)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_cls.cpp:38: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_cls.cpp:39: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_cls.cpp:46: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_cls.cpp:47: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_cls.o: In function `PaddleOCR::Classifier::LoadModel(std::string const&)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_cls.cpp:75: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.o: In function `PaddleOCR::DBDetector::LoadModel(std::string const&)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_det.cpp:23: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.o: In function `PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_det.cpp:74: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_det.cpp:75: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_det.cpp:81: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_det.cpp:82: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.o: In function `PaddleOCR::CRNNRecognizer::Run(std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >, cv::Mat&, PaddleOCR::Classifier*)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_rec.cpp:47: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_rec.cpp:48: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_rec.cpp:54: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_rec.cpp:55: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::string const&)':
/home/ocr/paddle_infer_cpp/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/ocr_rec.cpp:99: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::shrink_to_fit()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__future_base::_State_baseV2::_Make_ready::_M_set()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char, unsigned long) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/home/ocr/paddle_infer_cpp/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char, unsigned long) const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [ocr_system] Error 1
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
make: *** [all] Error 2
----------------------------------------
从这个提示可以看出大致是哪块出问题了么？

**Comment by ymzx** [comment]
tool/build.sh 如下：


OPENCV_DIR=/home/ocr/opencv-4.2.0/opencv3/lib64
LIB_DIR=/home/ocr/paddle_infer_cpp/paddle_inference
CUDA_LIB_DIR=/usr/local/cuda/lib64
CUDNN_LIB_DIR=/usr/local/cuda/lib64

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \

make -j
~

**Comment by LDOUBLEV** [comment]
你使用的是哪个预测库？

**Comment by ymzx** [comment]
> 你使用的是哪个预测库？
> build.sh里
> -DWITH_STATIC_LIB=OFF 是否是False的
使用如下预测库
![image](https://user-images.githubusercontent.com/29808550/120616035-75c0cd00-c48b-11eb-876c-f645c6e8267c.png)
-DWITH_STATIC_LIB=OFF 
我是用的是centos  是否和这个有关？

**Comment by LDOUBLEV** [comment]
你的机器GCC版本是多少的？

**Comment by LDOUBLEV** [comment]
如果可以的话，建议用我们的docker: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/installation.md#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85

**Comment by ymzx** [comment]
> 你的机器GCC版本是多少的？

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by ymzx** [comment]
> 如果可以的话，建议用我们的docker: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/installation.md#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85
> 
> 就不用折腾环境了

嗯 这个一定会用的，目前就是在比较不同部署方式的差异，还是希望先把这个尽量走完。

**Comment by LDOUBLEV** [comment]
> > 你的机器GCC版本是多少的？
> 
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

建议用8.2的，docker的环境里gcc是8.2的，可以在docker中验证，docker不影响你部署方式的差异

**Comment by ymzx** [comment]
> > > 你的机器GCC版本是多少的？
> > 
> > 
> > gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> 
> 建议用8.2的，docker的环境里gcc是8.2的，可以在docker中验证，docker不影响你部署方式的差异

latest-dev-cuda10.1-cudnn7-gcc82    我的cuda版本10.2  这个会有影响么？ 可选镜像清单在哪呢？谢

**Comment by ymzx** [comment]
> > 如果可以的话，建议用我们的docker: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/installation.md#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85
> > 就不用折腾环境了
> 
> 嗯 这个一定会用的，目前就是在比较不同部署方式的差异，还是希望先把这个尽量走完。

已使用该镜像，报错如下：
https://github.com/PaddlePaddle/PaddleOCR/issues/3026

**Comment by ymzx** [comment]
> 如果可以的话，建议用我们的docker: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/installation.md#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85
> 
> 就不用折腾环境了
已使用该镜像，报错如下：
https://github.com/PaddlePaddle/PaddleOCR/issues/3026

**Comment by ymzx** [comment]
采用镜像已解决
