### ISSUE TITLE
Performance on TextOCR Dataset

### ISSUE THREAD

**Issue by jkcg-learning** [PaddlePaddle/PaddleOCR#3022]
**Motivation**

Improve the benchmark performance of all algorithms based on TextOCR dataset released by Facebook AI research team

Related resources
https://textvqa.org/textocr

**Overview**
TextOCR requires models to perform text-recognition on arbitrary shaped scene-text present on natural images. TextOCR provides ~1M high quality word annotations on TextVQA images allowing application of end-to-end reasoning on downstream tasks such as visual question answering or image captioning.

**Statistics**
28,134 natural images from TextVQA
903,069 annotated scene-text words
32 words per image on average

**Comment by Evezerest** [comment]
Sorry, we don't support TextOCR for now.
