### ISSUE TITLE
windows gpu机器上部署 ppocr ，出现不明原因的闪退

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3023]
因为没有显示的异常报错描述，所以难以描述问题，说下现象，请大神分析下可能的原因？
【1】程序能正常运行，但是运行几十分钟后，往往出现停止退出
【2】gpu显存够用  没出现内存溢出
【3】每次都是在相同图片识别下退出，走完检测，送入识别时候退出；但是该图片单独识别没问题
【4】是否有win镜像使用，感觉ppocr不同平台、同平台不同计算方式环境配置满烦人的
谢

**Comment by LDOUBLEV** [comment]
win 平台和linux平台配置环境不一样是正常的，win上需要配置许多环境变量，这个不是ppocr的问题，linux上建议用我们的docker，win上目前没有镜像

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
