### ISSUE TITLE
尝试了几乎所有贵司的镜像，C++部署，报错: recipe for target 'CMakeFiles/ocr_system.dir/all' failed

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3026]
使用如下镜像：
https://hub.docker.com/layers/paddlepaddle/paddle/2.1.0-gpu-cuda10.2-cudnn7/images/sha256-d7f917c419cdbecfb3f2fc4847d2555b9dc6465a33c84ee70e2fecdc3842a29b?context=explore
![image](https://user-images.githubusercontent.com/29808550/120647115-d3194600-c4ac-11eb-9161-2c0e547cfa18.png)
paddle预测库使用如下
![image](https://user-images.githubusercontent.com/29808550/120647698-779b8800-c4ad-11eb-90d9-41c5bbd4d59e.png)

C++部署，sh tool/build.sh报错如下
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[100%] Linking CXX executable ocr_system
CMakeFiles/ocr_system.dir/src/main.o: In function `main':
/home/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/main.cpp:51: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/ocr_system.dir/src/ocr_det.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
/home/opencv-4.2.0/opencv3/include/opencv4/opencv2/core/mat.inl.hpp:548: undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/home/opencv-4.2.0/opencv3/include/opencv4/opencv2/core/mat.inl.hpp:561: undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
CMakeFiles/ocr_system.dir/src/utility.o: In function `PaddleOCR::Utility::VisualizeBboxes(cv::Mat const&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > > const&)':
/home/PaddleOCR-release-2.0-c++/deploy/cpp_infer/src/utility.cpp:55: undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ocr_system.dir/build.make:241: recipe for target 'ocr_system' failed
make[2]: *** [ocr_system] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
请问可能是什么原因？如何排查？使用其它镜像都是报这一个错

**Comment by LDOUBLEV** [comment]
不会吧，安装文档里有推荐安装的docker说明，我用了你说的镜像，C++编译预测也没问题啊；


**如果您希望在CPU环境下使用docker，使用docker而不是nvidia-docker创建docker
sudo docker run --name ppocr -v $PWD:/paddle --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash

如果使用CUDA10，请运行以下命令创建容器，设置docker容器共享内存shm-size为64G，建议设置32G以上
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash

您也可以访问[DockerHub](https://hub.docker.com/r/paddlepaddle/paddle/tags/)获取与您机器适配的镜像。
**

**Comment by LDOUBLEV** [comment]
用当前2.1分支的代码试一下？

**Comment by ymzx** [comment]
> 用当前2.1分支的代码试一下？
> 
> 这个报错是opencv的问题
> ![image](https://user-images.githubusercontent.com/26592129/120735884-ef090000-c51d-11eb-87cd-1d50b313cebb.png)
> 
> 检查你编译的opencv是不是可用的，文档里推荐的opencv用不了？
> ![image](https://user-images.githubusercontent.com/26592129/120735981-0f38bf00-c51e-11eb-9977-71b1f4bbd08c.png)

谢谢@LDOUBLEV，本人代码是基于paddleocr2.0二次开发的，加了一些新的算法（例如单字定位算法等），源代码修改的地方很多，不打算更新到2.1。但是paddle 是使用的2.1, opencv这个我再确认下。。。

**Comment by ymzx** [comment]
> 不会吧，安装文档里有推荐安装的docker说明，我用了你提到的镜像，C++编译预测也没问题啊；
> 
> **如果您希望在CPU环境下使用docker，使用docker而不是nvidia-docker创建docker
> sudo docker run --name ppocr -v $PWD:/paddle --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash
> 
> 如果使用CUDA10，请运行以下命令创建容器，设置docker容器共享内存shm-size为64G，建议设置32G以上
> sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash
> 
> 您也可以访问[DockerHub](https://hub.docker.com/r/paddlepaddle/paddle/tags/)获取与您机器适配的镜像。
> **

---
GPU，使用的nvidia-docker 创建的镜像

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/120755028-03f68b00-c540-11eb-9a02-6d15d392e886.png)

另外一个问题是GPU，选择预测库要和你的环境匹配，环境是cudnn7.6的，预测库不要选择cudnn8 的

**Comment by ymzx** [comment]
已解决
