### ISSUE TITLE
android_demo源码性能不稳定，EasyEdge的开源模型没有PaddleOCR

### ISSUE THREAD

**Issue by cat9** [PaddlePaddle/PaddleOCR#3027]
我尝试了PaddleOCR项目下deploy里面的android_demo，在同一手机同一张图片多次重复识别，android_demo里面的耗时十分不稳定，从500毫秒-25秒范围内变动。对比EasyEdge的demo，每次都能稳定在500毫秒以内，请问为什么差距这么大？
另外，我想直接使用EasyEdge的开源模型，发现体验开源模型里面有demo，实际上并没有PaddleOCR的开源模型在可用选项里面，这是EasyEdge停止了PaddleOCR的开源支持吗？

**Comment by littletomatodonkey** [comment]
1. 可能是EasyEdge中在初始化模型这块，做了warmup，导致后续的图片预测耗时比较稳定，一般第一次预测的时候都会有较大的时间波动
2. 没有，后续会继续更新的

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
