### ISSUE TITLE
SimpleDataSet的__getitem__不能调试

### ISSUE THREAD

**Issue by zzt6227** [PaddlePaddle/PaddleOCR#3029]
在训练dbnet时，打断点到ppocr/data/simple_dataset.py中的SimpleDataSet的__getitem__中，不能停住，怎么解决？

**Comment by littletomatodonkey** [comment]
num worker改为0，试下，一般建议在getitem中输出需要的信息进行调试

**Comment by zzt6227** [comment]
> num worker 改为0，试下，一般建议在getitem中输出需要的信息进行调试

试过了，代码也是直接执行过去了，不行
