### ISSUE TITLE
部分生僻（少见）字识别不准确

### ISSUE THREAD

**Issue by guchengxi1994** [PaddlePaddle/PaddleOCR#3030]
已经遇到的有  “绰” 识别成 “掉”， “姣” 识别程 “妹” ，“尕” 识别成 “孕” ，“嫣” 识别成 “媽”

**Comment by littletomatodonkey** [comment]
对于这种形近字和或者生僻字，建议单独做一些数据集去做模型微调，通用场景的话，此类字符确实较少

**Comment by nissansz** [comment]
有没有形近字列表？微调时也必须把所有文字的数据集包括在内？
