### ISSUE TITLE
paddle serving部署问题

### ISSUE THREAD

**Issue by kylewangt** [PaddlePaddle/PaddleOCR#3031]
按照官方的教程https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/pdserving/README_CN.md部署，无法成功

**Comment by littletomatodonkey** [comment]
可以参考dygraph分支下面的serving代码

**Comment by JiaXiao243** [comment]
请问是在哪一步出错了呢，报错信息是？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
