### ISSUE TITLE
gpu训练利用率太低了

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#3032]
你好，我用gpu跑训练，利用率最多能到19%，正常就是保持在10%，是不是代码中大部分都是调用的cpu来计算，少部分用上了gpu

**Comment by littletomatodonkey** [comment]
是的，数据预处理这块为了保证效果，加了很多数据增广，所以cpu所占的时间比较多，可以尝试调大，batch size(建议至少大于128)和num workers(建议为8)看下

**Comment by Sunyingbin** [comment]
> 是的，数据预处理这块为了保证效果，加了很多数据增广，所以cpu所占的时间比较多，可以尝试调大，batch size(建议至少大于128)和num workers(建议为8)看下

batch size我的电脑最多可以调整到512，但是我目前只用256来训练，num workers很奇怪，我怎么调整都没有什么效果，训练的速度也根本没有变，调成16、8、4、2、0都是一样的，这是为啥。

**Comment by kivenyangming** [comment]
可以事先对你的数据进行数据扩增，不在网络中进行，这样网络的运行的速度也提升上来了。
