### ISSUE TITLE
基于paddleocr二次开发，新增了一些算法和功能，例如单字信息等，代码相对于源码改动大，如何转化为cpp文件，用C++部署

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#3033]
如题

**Comment by littletomatodonkey** [comment]
梳理好逻辑之后，用c++实现即可，可以参考deploy/cpp_infer中的文件

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
