### ISSUE TITLE
paddleocr rec训练，把max_text_length从25改成7 会就报错，请问还需要修改那些配置？

### ISSUE THREAD

**Issue by xuwuwei** [PaddlePaddle/PaddleOCR#3035]

**Comment by littletomatodonkey** [comment]
报什么错？报错信息日志发来看看

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
