### ISSUE TITLE
模型评估时卡住

### ISSUE THREAD

**Issue by dychb** [PaddlePaddle/PaddleOCR#3036]
![P{N)$J08{K$G)M{1PO)Y{I9](https://user-images.githubusercontent.com/59058681/120924253-4917ea00-c705-11eb-83df-544cf2f6de17.png)
请问这个可能是什么原因？

**Comment by LDOUBLEV** [comment]
python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1' ....
使用distribution方式启动训练时，可以指定log_dir，看下你的log_dir中的文件有无明确的报错信息

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
