### ISSUE TITLE
use_visualdl设置为true，启动服务后，没有显示计算图相关信息。

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#3037]
use_visualdl设置为true，启动服务后，没有显示计算图相关信息。读取output/vdl文件夹下的log文件，vdl页面没有加载任何信息并提示错误。

**Comment by Sunyingbin** [comment]
![image](https://user-images.githubusercontent.com/23546166/120950511-8027e300-c779-11eb-9217-45de4a807cba.png)
win10环境上打开log文件显示乱码

**Comment by Evezerest** [comment]
可以到VDLrepo下提问
