### ISSUE TITLE
EAST MV3 Detection cal_metric_during_train Failure

### ISSUE THREAD

**Issue by mohamadmansourX** [PaddlePaddle/PaddleOCR#3039]
I'm trying to train det_mv3_east model.
When setting `cal_metric_during_train` in config to **False**, everything works successfully, but when I try to set the `cal_metric_during_train` to **True** to visualize the metrics on training data as well, I receive the below error:
```python 
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/mansour/PaddleOCR/tools/program.py", line 259, in train
    post_result = post_process_class(preds, batch[1])
  File "/home/mansour/PaddleOCR/ppocr/postprocess/east_postprocess.py", line 131, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[ino]
ValueError: not enough values to unpack (expected 4, got 1)
```

I believe the error lies in the passed parameters for the `EASTPostProcess` object since the metric is calculated successfully in the case of evaluation while failing on training data only.

After further inspection of the error, calculation of the metric(precision,hmean, recall..) is dependent on `post_process_class(preds, batch[1]) `function, and the error lies in the line where` src_h, src_w, ratio_h, ratio_w `are being set to `shape_list[ino] `( = batch[1][ino])
In the case of evaluation where it works successfully (batches are gotten from valid_dataloader-->`paddle.io.DataLoader(batch_sampler=paddle.io.BatchSampler)`) and the inputted parameters to the `post_process_class` function have the following description:
> preds (dictionary):
>>  f_score    (1, 1, 432, 328)
>> f_geo    (1, 8, 432, 328)

> batch(list of Tensors):
>>  batch[0]: Dim:    4, Shape:    (1, 3, 1728, 1312)
>> ###  **batch[1]: Dim:    2, Shape:    (1, 4)**
>> batch[2]: Dim:    4, Shape:    (1, 4, 4, 2)
>> batch[3]: Dim:    2, Shape:    (1, 4)

In the case of training data - `batch_size_per_card: 5` - where it failed (batches are gotten from train_dataloader-->`paddle.io.DataLoader(batch_sampler=paddle.io.DistributedBatchSampler)`)and the inputted parameters to the `post_process_class` function have the following description:
> preds (dictionary):
>>  f_score    (5, 1, 128, 128)
>> f_geo    (5, 8, 128, 128)

> batch(list of Tensors):
>>  batch[0]: Dim:    4, Shape:    [5, 3, 512, 512]
>>  ### **batch[1]: Dim:    2, Shape:   [5, 1, 128, 128]**
>> batch[2]: Dim:    4, Shape:   [5, 9, 128, 128]
>> batch[3]: Dim:    2, Shape:   [5, 1, 128, 128]

_________________________________________________
Update:
Config file for the training dataloader has the following

>  `keep_keys: ['image', '**_score_map_**', 'geo_map', 'training_mask']`

while for the eval:

> `keep_keys: ['image, '**_shape_**', 'polys', 'ignore_tags']`

**Comment by MissPenguin** [comment]
Thank you for using and feedback! As we noted [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/program.py#L233) , function `cal_metric_during_train` is usually needed and only supported in recognition and classification training.

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
