### ISSUE TITLE
finetune的识别模型前向速度比ppocr提供的识别infer模型速度慢很多

### ISSUE THREAD

**Issue by caidou05** [PaddlePaddle/PaddleOCR#3042]
我自己再paddleocr提供的模型finetune最后的shape是-1*-1*6625，但是同样的图片，PaddleOCR模型在cpu上前向速度比我finetune的模型快了4，5倍，这是什么原因

**Comment by littletomatodonkey** [comment]
1. 保证图片shape一样去测试，
2. 测试速度的时候，最好测试一批图片，去除前10张的预测耗时影响
3. 都导出成inference model去测试

**Comment by caidou05** [comment]
> 1. 保证图片shape一样去测试，
> 2. 测试速度的时候，最好测试一批图片，去除前10张的预测耗时影响
> 3. 都导出成inference model去测试

我是用ppocr提供的ch_ppocr_server_v2.0_rec_infer这个模型，转成onnx，这个模型本来输入是32*100，我改成32*-1，然后又用ch_ppocr_server_v2.0_rec_pre这个模型去finetune，转成inference model，输入是32*-1，也转成onnx，这两个速度差的特别大

**Comment by littletomatodonkey** [comment]
那比较奇怪，建议先用paddle inference去做一下速度测试，onnx目前这边还没统一测试过

**Comment by caidou05** [comment]
> 那比较奇怪，建议先用paddle inference去做一下速度测试，onnx目前这边还没统一测试过
请问一下，这个infer的模型是用export_model.py生成的吗
![image](https://user-images.githubusercontent.com/85534457/121286802-f0b63780-c912-11eb-9df1-16da7805004d.png)

**Comment by Evezerest** [comment]
是的
