### ISSUE TITLE
db检测模型配置checkpoints断点重载报错

### ISSUE THREAD

**Issue by j-river** [PaddlePaddle/PaddleOCR#3043]
db模型训练时，我使用之前保存的最佳模型的参数进行初始化，在yaml文件中配置了最佳模型的路径，结果加载模型报AssertionError: Can not find [batch_norm_47.b_0_velocity_0] in model file。 请问这是什么原因呢？该如何解决？

**Comment by MissPenguin** [comment]
这个报错应该是模型结构没对上，确认下加载的模型和当前网络结构是否一致。另外，`checkpoints`是断点继续训练，如果你是想用来做预训练但配置有所改动，建议用`pretrained_model`。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
