### ISSUE TITLE
train for persian

### ISSUE THREAD

**Issue by raminrahimi6970** [PaddlePaddle/PaddleOCR#3044]
Hi thanks for your repository
I use your wights for persian  but Results are not as good as English....
I have corpus  contains a 50000  unique words in my language (farsi) would you mind train paddle ocr for my language?
thanks best regards

**Comment by tink2123** [comment]
Hi  raminrahimi6970，

Thanks for your attention. You are welcome to contribute corpus. In addition, would you like to contribute some fonts for us to synthesize data? We are very willing to optimize the model effect with your help.

You can send the corpus and fonts to my email： y_tink@163.com

Best regards

**Comment by raminrahimi6970** [comment]
thanks for your reply I send corpus and fonts to your email

**Comment by tink2123** [comment]
Hi @raminrahimi6970 ,

Thank you for your contribution, but I did not see the email when I checked the mailbox. 
Can you send another copy of the data?

Best regards

**Comment by raminrahimi6970** [comment]
Hi 
I send it again...
Best regards
