### ISSUE TITLE
关于横排纵排的判断

### ISSUE THREAD

**Issue by wksuixin** [PaddlePaddle/PaddleOCR#3045]
对于文本检测后，裁剪出来的词条；除了根据h/w>1.5来判断横排纵排，进而判断是否需要逆时针旋转90°；是否有其它更准确的方法？

**Comment by MissPenguin** [comment]
目前采用的通过宽高比判定的方式比较简单粗暴，但基本足够应对一般情况。想要更准确的话，可以训个分类器。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
