### ISSUE TITLE
output_tensor.copy_to_cpu() 非常耗时

### ISSUE THREAD

**Issue by tangmiao0** [PaddlePaddle/PaddleOCR#3051]
output_tensor.copy_to_cpu() 非常耗时，是模型推理的100倍左右，请问有解决方法吗？

**Comment by LDOUBLEV** [comment]
你用的哪个版本的Paddle，运行的模型是？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
