### ISSUE TITLE
DBNet训练时，加载数据报错

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3054]
![image](https://user-images.githubusercontent.com/44855506/121179959-de94b480-c892-11eb-864d-38e748effa54.png)
提示超出范围，这个数据的标签个数比较多，大概有80个，是标签数量太多的问题吗，在哪里改这个上限啊

**Comment by Evezerest** [comment]
能提供一下完整信息吗

**Comment by lalalagogogochong** [comment]
> 能提供一下完整信息吗

![Uploading image.png…]()
