### ISSUE TITLE
请问，多行文本识别，需要怎么提高confidence？

### ISSUE THREAD

**Issue by frh16** [PaddlePaddle/PaddleOCR#3056]
使用：中英文通用OCR模型（143M）

例如要识别的图片如下：
![444](https://user-images.githubusercontent.com/51506628/121280972-bbf1b280-c909-11eb-8a4f-0dffb1205e19.png)

使用ocr_rec时，结果：
[[{'confidence': 0.6300355792045593, 'text': '。不文a'}]]

使用ocr_system时，结果：（有很多错别字）
[[{'confidence': 0.7980666756629944, 'text': '品果布望使用不支持空调的的识别模型，在预汇的时候需要主意：请持代码电新到最新版本、开添加W料：--usespacechar=False', 'text_region': [[11, 7], [927, 7], [927, 18], [11, 18]]}, {'confidence': 0.9854691028594971, 'text': '。如果不希望使用方向分类器，在预测的时候需要注意：请将代码更新到最新版本，并添加参数--use anglecls=False', 'text_region': [[9, 32], [859, 33], [859, 47], [9, 46]]}]]

如果把图片截掉一半，保留任意单行文字，使用ocr_rec时，结果就非常准确，没有错别字

所以，请问怎么设置参数，可以让多行文本识别准确？

**Comment by WenmuZhou** [comment]
把ubclip_ratio调大看看

**Comment by frh16** [comment]
> 把unclip_ratio调大看看

虽然我看不大明白，还是感谢一下
后来，我发现，增加图片padding，可以让识别准确。

比如：
![1](https://user-images.githubusercontent.com/51506628/121375403-4de1d580-c973-11eb-8f7a-61b19c7d3bde.png)
