### ISSUE TITLE
docker部署发送请求问题

### ISSUE THREAD

**Issue by ClearTorch** [PaddlePaddle/PaddleOCR#3059]
运行paddle_cor容器，打印日志如下：
 * Serving Flask app 'paddlehub.serving.app_compat' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.3:8866/ (Press CTRL+C to quit)

判断运行成功！

发送请求命令：
$ curl --data /home/cleartorch/python/OCR/PaddleOCR/doc/imgs/11.jpg **http://localhost:8868/predict/ocr_system**
错误提示        curl: (56) Recv failure: Connection reset by peer

更改地址，
$ curl --data /home/cleartorch/python/OCR/PaddleOCR/doc/imgs/11.jpg **http://172.17.0.3:8866/predict/ocr_system**
输出提示：
{"msg":"This usage is out of date, please use 'application/json' as content-type to post to /predict/ocr_system. See 'https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md' for more details.","results":"","status":"112"}

请问如何正确发送请求？

**Comment by cool3rzZ** [comment]
按照官方的方式启动试试，例如：hub serving start -c deploy/hubserving/ocr_system/config.json

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
