### ISSUE TITLE
如何设置检测字符的搜索区间

### ISSUE THREAD

**Issue by qq61786631** [PaddlePaddle/PaddleOCR#306]
rt，设置搜索区间，可以避免错误结果的干扰。找了半天没发现在哪设置。是暂时还不支持吗^_^

**Comment by dyning** [comment]
检测字符的搜索区间是指对结果过滤？

**Comment by qq61786631** [comment]
嗯，可能我的思路还停留在传统ocr上，这样确实也是可以的。thanks
