### ISSUE TITLE
是不是把最新版的paddleocr发布到pip上？

### ISSUE THREAD

**Issue by suparek** [PaddlePaddle/PaddleOCR#3064]
![image](https://user-images.githubusercontent.com/9245996/121320969-3dfcce00-c940-11eb-8f20-cdb5461da44b.png)

我看pip上的还是4月份发布的。

**Comment by tink2123** [comment]
这个就是最新的呀，模型是4月确定并发布的，目前还在迭代中，下一版优化完之后会更新pip

**Comment by suparek** [comment]
> 这个就是最新的呀，模型是4月确定并发布的，目前还在迭代中，下一版优化完之后会更新pip

原来如此
