### ISSUE TITLE
ppocr转视频识别

### ISSUE THREAD

**Issue by chocolate-byte** [PaddlePaddle/PaddleOCR#3065]
请问下ppocr识别是不是会出现cap.read每捕捉到一帧就跑一遍整个程序重新加载一次模型这个现象，有什么办法让模型一直处于加载状态并识别视频吗

**Comment by tink2123** [comment]
输入批量图片去预测，只会初始化一次模型。自己修改一下数据读取的逻辑就可以～

**Comment by chocolate-byte** [comment]
请问如果有实时视频predict的需求就不能批量输入图像了，另外tools/infer中有一个video_predict文件方便问一下有没有具体的接口文档呀

**Comment by chocolate-byte** [comment]
这种情况是需要把模型预测代码提取出来的吗，想麻烦问一下有关模型恢复的文件写在哪些文件里面

**Comment by rsingh2083** [comment]
> 这种情况是需要把模型预测代码提取出来的吗，想麻烦问一下有关模型恢复的文件写在哪些文件里面

Were you able to run real time video prediction ?
