### ISSUE TITLE
编译预测库报错

### ISSUE THREAD

**Issue by xuxiaobao-3** [PaddlePaddle/PaddleOCR#3067]
root@ocrdev-System-Product-Name:/media/ocr/disk1/Project/Paddle-Lite# ./lite/tools/build_android.sh --arch=armv8 --with_cv=ON --with_extra=ON
-- Found Paddle host system: ubuntu, version: 20.04.2
-- Found Paddle host system's CPU: 12 cores
-- Found host C compiler: /usr/bin/gcc
-- Found host CXX compiler: /usr/bin/g++
-- Lite ARM Compile android with armv8 
-- Android: Targeting API '23' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected GCC toolchain 'aarch64-linux-android-4.9'
-- The CXX compiler identification is GNU 4.9.0
-- The C compiler identification is GNU 4.9.0
-- Check for working CXX compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++
-- Check for working CXX compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
-- Check for working C compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++, version: GNU 4.9.0
-- C compiler: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc, version: GNU 4.9.0
-- AR tools: /opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Performing Test FMA_FOUND
-- Performing Test FMA_FOUND - Failed
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
-- CMAKE_BUILD_TYPE: Release
-- `lite/model_parser/flatbuffers/framework.fbs`: add generation of C++ code with '--no-includes;--gen-compare;--force-empty'
-- SRC_FBS_DIR: lite/model_parser/flatbuffers
-- `lite/model_parser/flatbuffers/param.fbs`: add generation of C++ code with '--no-includes;--gen-compare;--force-empty'
-- SRC_FBS_DIR: lite/model_parser/flatbuffers
-- Building the mobile framework
-- Performing Test out_var
-- Performing Test out_var - Success
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Found OpenMP  4.0
-- OpenMP C flags:  -fopenmp
-- OpenMP CXX flags:  -fopenmp
-- OpenMP OpenMP_CXX_LIB_NAMES:  log;gomp
-- OpenMP OpenMP_CXX_LIBRARIES:  /opt/android-ndk-r17c/platforms/android-23/arch-arm64/usr/lib/liblog.so;/opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/lib64/libgomp.a
-- Flatbuffers will be used as cpp default program description.
-- LIGHT_FRAMEWORK:	ON
-- LITE_WITH_CUDA:	OFF
-- LITE_WITH_X86:	OFF
-- LITE_WITH_ARM:	ON
-- LITE_WITH_OPENCL:	OFF
-- LITE_WITH_NPU:	OFF
-- LITE_WITH_RKNPU:	OFF
-- LITE_WITH_XPU:	OFF
-- LITE_WITH_APU:	OFF
-- LITE_WITH_XTCL:	
-- LITE_WITH_FPGA:	OFF
-- LITE_WITH_MLU:	OFF
-- LITE_WITH_HUAWEI_ASCEND_NPU:	OFF
-- LITE_WITH_BM:	OFF
-- LITE_WITH_PROFILE:	OFF
-- LITE_WITH_CV:	ON
-- generating arm dotprod code
-- Found PythonInterp: /usr/bin/python (found version "3.8.5") 
input file:  /media/ocr/disk1/Project/Paddle-Lite/lite/backends/arm/math/dotprod/__gemm_sdot_meta__.h
output file:  /media/ocr/disk1/Project/Paddle-Lite/lite/backends/arm/math/dotprod/gemm_sdot.h
-- add lite kernels
-- compile with lite host kernels
-- compile with lite ARM kernels
fatal: 没有标签准确匹配 'd5b0d529717c533fed1f4dd1bd9fb97961bae518'
-- tag: 
-- branch: release/v2.7
-- commit: d5b0d529
-- Collected 165 ops
-- Collected 0 X86 kernels
-- Collected 0 CUDA kernels
-- Collected 35 Host kernels
-- Collected 82 ARM kernels
-- Collected 0 OpenCL kernels
-- Collected 0 NPU kernels
-- Collected 0 APU kernels
-- Collected 0 XPU kernels
-- Collected 0 RKNPU kernels
-- Collected 0 FPGA kernels
-- Collected 0 BM kernels
-- Collected 0 MLU kernels
-- Collected 0 HUAWEI_ASCEND_NPU kernels
-- bundled_tgt_full_name:  /media/ocr/disk1/Project/Paddle-Lite/build.lite.android.armv8.gcc/libpaddle_api_light_bundled.a
CMake Error at /opt/cmake-3.10/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Java (missing: Java_JAVAH_EXECUTABLE) (found version
  "11.0.11")
Call Stack (most recent call first):
  /opt/cmake-3.10/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.10/share/cmake-3.10/Modules/FindJava.cmake:271 (find_package_handle_standard_args)
  lite/api/android/jni/CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/media/ocr/disk1/Project/Paddle-Lite/build.lite.android.armv8.gcc/CMakeFiles/CMakeOutput.log".
See also "/media/ocr/disk1/Project/Paddle-Lite/build.lite.android.armv8.gcc/CMakeFiles/CMakeError.log".

**Comment by LDOUBLEV** [comment]
> Could NOT find Java (missing: Java_JAVAH_EXECUTABLE) (found version

没有安装依赖吧

**Comment by xuxiaobao-3** [comment]
> > Could NOT find Java (missing: Java_JAVAH_EXECUTABLE) (found version
> 
> 没有安装依赖吧，交叉编译环境记得安装，https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_env.html#linux
> 
> ![image](https://user-images.githubusercontent.com/26592129/121365175-02c3c480-c96b-11eb-858c-627f030b6503.png)

按照这个步骤走了一遍  jdk也是按照他的语句安装的 就是出现这些

**Comment by LDOUBLEV** [comment]
是否安装成功了呢？

```
# 1. Install basic software
apt update
apt-get install -y --no-install-recommends \
  gcc g++ git make wget python unzip adb curl

# 2. Prepare Java env.
apt-get install -y default-jdk

# 3. Install cmake 3.10 or above
wget -c https://mms-res.cdn.bcebos.com/cmake-3.10.3-Linux-x86_64.tar.gz && \
    tar xzf cmake-3.10.3-Linux-x86_64.tar.gz && \
    mv cmake-3.10.3-Linux-x86_64 /opt/cmake-3.10 && \  
    ln -s /opt/cmake-3.10/bin/cmake /usr/bin/cmake && \
    ln -s /opt/cmake-3.10/bin/ccmake /usr/bin/ccmake

# 4. Download Android NDK for linux-x86_64
#     Note: Skip this step if NDK installed
#     support android-ndk-r17c-linux-x86_64 and other later version such as ndk-r18b or ndk-r20b 
#     ref: https://developer.android.com/ndk/downloads
cd /tmp && curl -O https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
cd /opt && unzip /tmp/android-ndk-r17c-linux-x86_64.zip

# 5. Add environment ${NDK_ROOT} to `~/.bashrc` 
echo "export NDK_ROOT=/opt/android-ndk-r17c" >> ~/.bashrc
source ~/.bashrc
```
执行这些就够了，可以看下你的～/.bashrc文件里有没有export NDK_ROOT=/opt/android-ndk-r17c

**Comment by xuxiaobao-3** [comment]
> 是否安装成功了呢？
> 
> ```
> # 1. Install basic software
> apt update
> apt-get install -y --no-install-recommends \
>   gcc g++ git make wget python unzip adb curl
> 
> # 2. Prepare Java env.
> apt-get install -y default-jdk
> 
> # 3. Install cmake 3.10 or above
> wget -c https://mms-res.cdn.bcebos.com/cmake-3.10.3-Linux-x86_64.tar.gz && \
>     tar xzf cmake-3.10.3-Linux-x86_64.tar.gz && \
>     mv cmake-3.10.3-Linux-x86_64 /opt/cmake-3.10 && \  
>     ln -s /opt/cmake-3.10/bin/cmake /usr/bin/cmake && \
>     ln -s /opt/cmake-3.10/bin/ccmake /usr/bin/ccmake
> 
> # 4. Download Android NDK for linux-x86_64
> #     Note: Skip this step if NDK installed
> #     support android-ndk-r17c-linux-x86_64 and other later version such as ndk-r18b or ndk-r20b 
> #     ref: https://developer.android.com/ndk/downloads
> cd /tmp && curl -O https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
> cd /opt && unzip /tmp/android-ndk-r17c-linux-x86_64.zip
> 
> # 5. Add environment ${NDK_ROOT} to `~/.bashrc` 
> echo "export NDK_ROOT=/opt/android-ndk-r17c" >> ~/.bashrc
> source ~/.bashrc
> ```
> 
> 执行这些就够了，可以看下你的～/.bashrc文件里有没有export NDK_ROOT=/opt/android-ndk-r17c
环境变量、配置好了  报错说的是缺少javah？

**Comment by xuxiaobao-3** [comment]
declare -x MAIL="/var/mail/root"
declare -x NDK_ROOT="/opt/android-ndk-r17c"
declare -x OLDPWD="/etc/apt"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x PWD="/media/ocr/disk1/Project/Paddle-Lite"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SUDO_COMMAND="/usr/bin/su"
declare -x SUDO_GID="1000"
declare -x SUDO_UID="1000"
declare -x SUDO_USER="ocr"
declare -x TERM="xterm-256color"
declare -x USER="root"
declare -x XAUTHORITY="/run/user/1000/gdm/Xauthority"
declare -x jdk="/usr/bin/java"

**Comment by LDOUBLEV** [comment]
apt-get install -y default-jdk
安装成功了？

**Comment by xuxiaobao-3** [comment]
> > 环境变量、配置好了 报错说的是缺少javah？
> 
> apt-get install -y default-jdk
> 安装成功了？
> 
> 还不行的话可以在docker中编译，避免环境问题
> 可以用镜像：paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82
> 或编译paddlelite 安装文档里提到的镜像

root@ocrdev-System-Product-Name:/home/ocr# apt-get install -y default-jdk
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
default-jdk 已经是最新版 (2:1.11-72)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 16 个软件包未被升级。
这位安装好了  还是不可以    我使用docker试下吧 谢谢大佬帮助
