### ISSUE TITLE
ch_det_mv3_db_v2.0.yml 动态模型可以正常推理转静态模型就推理失败请大佬看看

### ISSUE THREAD

**Issue by yfc886** [PaddlePaddle/PaddleOCR#3068]
使用ch_det_mv3_db_v2.0.yml   训练的db det 模型。动态图可以正常的进行推理和定位到具体文字。使用python tools\export_model.py --config=configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml   转静态图的时候没有异常出现。inference 文件夹也能生成3个文件。 但是使用这个静态文件进行推理的时候，推理不出结果来。 不知道是什么原因。

训练好的动态图：
[训练好的动态图.zip](https://github.com/PaddlePaddle/PaddleOCR/files/6622764/default.zip)

如果可以正常转换静态图可联系小弟QQ：7767324  不胜感激

**Comment by tink2123** [comment]
没有通过 -o Global.checkpoints= 指定你训练好的权重吗？

**Comment by yfc886** [comment]
> 没有通过 -o Global.checkpoints= 指定你训练好的权重吗？

请问这个怎么填写。有参考吗？

**Comment by tink2123** [comment]
python3 tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.checkpoints=./ch_lite/ch_ppocr_mobile_v2.0_det_train/best_accuracy

替换你自己训练好的权重保存路径即可

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
