### ISSUE TITLE
请教一下SRN模型对英文标点符号效果不好的问题

### ISSUE THREAD

**Issue by jerryzhang-ss** [PaddlePaddle/PaddleOCR#3071]
尊敬的paddleocr团队各位老师你们好。

我最近尝试在coco-text数据集上尝试使用SRN训练以及预测，具体流程是下载官方提供的pretrained model然后在coco-text训练集上fine-tune。从结果上看似乎对标点符号比较经常忽略，比如3:30就预测成330。 我还尝试了用rec_chinese_common_train_v2.0这个配置的pretrained model fine tune，效果似乎没有SRN的好，所以想继续在SRN的基础上做些尝试。

想请问一下各位老师，针对标点符号有什么改进的方法吗？另外想问一下是否有什么在这个数据集上提升performance的建议。十分感谢

**Comment by jerryzhang-ss** [comment]
另外还想请教一下SRN是否不能加TPS？我试着使用了您这边的TPS模块，也试着自己搭了个STN网络，结果都是loss爆炸了……

**Comment by MissPenguin** [comment]
标点的问题，建议增加相关数据到训练中。TPS原理是是可以加到SRN中的，但是需要调试，这个我们没有尝试过
