### ISSUE TITLE
cannot import name ‘draw_ocr’

### ISSUE THREAD

**Issue by shudingcai** [PaddlePaddle/PaddleOCR#3072]
pip install paddleocr (2.06)
from paddleocr import draw_ocr

使用pyinstaller 打包后 
ImportError: cannot import name 'draw_ocr' from 'paddleocr' (C:\Users\kochi\AppData\Local\Temp\_MEI166482\paddleocr.pyc)
D:\tecleadrpa-client-master\venv\Lib\site-packages\paddleocr\paddleocr.py 里面没有找到draw_ocr 函数。

**Comment by littletomatodonkey** [comment]
这个函数在这里，应该是pyinstaller的时候，没有把这个文件拷贝过去

https://github.com/PaddlePaddle/PaddleOCR/blob/7b759798887596629e83c01436d5256543805060/tools/infer/utility.py#L208

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
