### ISSUE TITLE
AssertionError: The setting of Parameter-Server must has server_num or servers

### ISSUE THREAD

**Issue by scopedog** [PaddlePaddle/PaddleOCR#3073]
Hi, I just tried train.sh in PaddleOCR and get the following error:

-----------  Configuration Arguments -----------
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: ./debug/
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/rec/rec_mv3_none_bilstm_ctc.yml']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-06-09 10:59:28,075 launch.py:352] Not found distinct arguments and not compiled with cuda or xpu. Default use ps mode
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ahoahoman/.local/lib/python3.7/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/home/ahoahoman/.local/lib/python3.7/site-packages/paddle/distributed/fleet/launch.py", line 371, in launch
    launch_ps(args, distribute_mode)
  File "/home/ahoahoman/.local/lib/python3.7/site-packages/paddle/distributed/fleet/launch.py", line 289, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "/home/ahoahoman/.local/lib/python3.7/site-packages/paddle/distributed/fleet/launch_utils.py", line 807, in __init__
    self.get_role_endpoints(args)
  File "/home/ahoahoman/.local/lib/python3.7/site-packages/paddle/distributed/fleet/launch_utils.py", line 824, in get_role_endpoints
    assert args.servers != "", "The setting of Parameter-Server must has server_num or servers."
AssertionError: The setting of Parameter-Server must has server_num or servers.

I use a CPU version of Paddle.
Is it fixable?
Thank you.

**Comment by littletomatodonkey** [comment]
It seems that you the paddlepaddle you install can just be run on cpu, you can try to use the following command to run you train program.

`python tools/train.py -c xxx.yaml`

**Comment by scopedog** [comment]
OK, but I could solve the problem by editing a few programs of Paddle.
I don't know if the change is correct though.
Thanks anyway.

**Comment by littletomatodonkey** [comment]
you are welcome, in fact you can throw your exact problem and the environment info here to let more look for more people's help.

**Comment by scopedog** [comment]
OK, I will do so if I have time.

**Comment by scopedog** [comment]
Here are the details of my environment and solution:
* Problem: Training with CPU fails with the aforementioned error.
* OS: Debian 10
* Solution: Some variables in Paddle (paddlepaddle) are not initialized and need to be initialized as follows:
$diff paddle/site-packages/paddle/distributed/fleet/launch_utils.py paddle/site-packages/paddle/distributed/fleet/launch_utils.py.org
824,830d823
<             args.server_num = 0
<             args.servers = ""
<             ports = get_ports(self.server_num, 0)
<             self.server_endpoints = ",".join(
<                     ["127.0.0.1:" + str(x) for x in ports])
< 
<             '''
834d826
<             '''
851,856d842
<             args.worker_num = 0
<             args.workers = ""
<             ports = get_ports(self.worker_num, self.server_num)
<             self.worker_endpoints = ",".join(
<                     ["127.0.0.1:" + str(x) for x in ports])
<             '''
880d865
<         '''

Basically, as args.worker_num and args.workers are None, you need to force args.worker_num = 0 and args.workers = "" and ignore between assert args.workers != "" and self.worker_endpoints = args.workers. Similarly, set args.worker_num = 0 and args.workers = "" and ignore assert args.workers != "", etc.
Also, as self.ranks doesn't seem to be correctly initialized in paddle/fluid/dataloader/batch_sampler.py, you need to add:
        if self.nranks == 0:
            self.nranks = 1
between
        else:
            self.nranks = ParallelEnv().nranks
and
        if rank is not None:
            assert isinstance(rank, int) and rank >= 0,

I know this is an ugly solution and don't know if PaddleOCR training is correctly working but mine is running anyway. Please be aware that it is a temporary solution only for PaddleOCR + training with CPU. Please restore the original if you use paddlepaddle for other purposes.

**Comment by littletomatodonkey** [comment]
> It seems that you the paddlepaddle you install can just be run on cpu, you can try to use the following command to run you train program.
> 
> `python tools/train.py -c xxx.yaml`

Actually if you run using this way, the problems you met should not occur.

**Comment by scopedog** [comment]
I also tried with
% python tools/train.py -c xxx.yaml
but still got an error at 
        self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
in paddle/fluid/dataloader/batch_sampler.py caused by self.nranks = 0.
You have to make it
        if self.nranks == 0:
            self.nranks = 1
