### ISSUE TITLE
video_predict.py可以用来预测视频吗

### ISSUE THREAD

**Issue by chocolate-byte** [PaddlePaddle/PaddleOCR#3075]
在尝试做视频识别想用队列抽取帧的时候发现ppocr/tools/infer下有一个video_predict.py文件，但是遍历文档都没有查到video_predict有相关的说明文档或者接口，所以想请问一下各位大哥们谁知道这个video_predict有相关的调用文档和使用方式吗

**Comment by littletomatodonkey** [comment]
你好，这个应该不是ppocr的文件，ppocr目前还不支持视频预测

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
