### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by Nanhaojie** [PaddlePaddle/PaddleOCR#3076]
我在用paddleserving部署时，预测不同的图片，图片都resize到960，在显存优化开启的情况下，显存会一直增加，导致显存不足，

**Comment by littletomatodonkey** [comment]
这块使用的预测库版本和serving版本是什么呢？

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
