### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.infer.utility'; 'tools.infer' is not a package

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3077]
ｉrun  python3 tools/infer/predict_system.py  in the dir of PaddleOCR it alse raise ModuleNotFoundError: No module named 'tools.infer.utility'; 'tools.infer' is not a package

**Comment by littletomatodonkey** [comment]
You can try to unset PYTHONPATH using `unset PYTHONPATH` and the run your command again.

**Comment by hukefei** [comment]
you can check whether a module named 'tools' was installer earlier by
`python
import tools
print(tools.__path__)`
if there was, remove this module

**Comment by cqray1990** [comment]
@hukefei   i create an new pythonefile with content of 
import tools
print(tools.__path__)
and run 
projects/PaddleOCR/tools  it print paddleocr tools 
thereis no wrong i didn't install any tools
