### ISSUE TITLE
how to invoke pgnet with c++ server inference 

### ISSUE THREAD

**Issue by kuaiyouxiaozi** [PaddlePaddle/PaddleOCR#3078]
how to invoke pgnet with c++ server inference

**Comment by littletomatodonkey** [comment]
Thanks for your attention, pgnet is not implemented into cpp demo as now, you can try it with the help of `deploy/cpp_infer`

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
