### ISSUE TITLE
实时视频检测

### ISSUE THREAD

**Issue by chocolate-byte** [PaddlePaddle/PaddleOCR#3081]
想做一个实时检测视频的功能，现在已经训练好了单张图像的模型，请问各位老师有什么方法可以继续往下实现吗，我对调用模型的py不是很清楚怎么修改才能变成实时。

**Comment by littletomatodonkey** [comment]
模型速度和模型大小关系也比较大，不清楚你具体要做什么，预测的话，可以用inference model进行预测，参考`tools/export_model.py`进行导出

**Comment by hice1207** [comment]
> 想做一个实时检测视频的功能，现在已经训练好了单张图像的模型，请问各位老师有什么方法可以继续往下实现吗，我对调用模型的py不是很清楚怎么修改才能变成实时。

我也想做实时的视频识别，方便留个联系方式交流一下吗

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
