### ISSUE TITLE
同样的数据训练CRNN不报错，训练RARE报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#3084]
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/67897601/121475583-2ed95700-c9f8-11eb-9d75-433e88ef79f3.png">

**Comment by littletomatodonkey** [comment]
把num worker设置为0，看下具体的报错信息是什么

**Comment by aishangmaxiaoming** [comment]
> 把num worker设置为0，看下具体的报错信息是什么
把num worker设置为0,报错 ValueError: all input arrays must have the same shape
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/67897601/122759270-553aa480-d2cc-11eb-9935-c27abbdb10ca.png">

**Comment by thomaszheng** [comment]
#3455 可以试试

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
