### ISSUE TITLE
pgnet文本识别要训练多少个epoch才有效果?

### ISSUE THREAD

**Issue by Agino-ltp** [PaddlePaddle/PaddleOCR#3085]
在使用pgnet训练自己的数据集时，损失值变化很小，20个epoch之后基本不怎么变化，一直保持在50左右，f_score也只有0.001的样子

**Comment by LDOUBLEV** [comment]
你的数据集是什么样式的，识别的是英文还是中文呢

检测的指标是否正常？

**Comment by Agino-ltp** [comment]
> 你的数据集还是方式的，识别的是英文中文呢
> 
> 检测的指标是否正常？

数据集格式是扫描的英文票据，识别的是英文。要求就是：不管是大写的文本还是小写的文本都全部识别成大写的。txt中的transcription全部都是大写的字母格式。但是训练的时候检测的指标（召回，准确率等）都可以到达96%，但是识别的指标全部都是0。训练了100多个epoch并测试图像的话大写字母识别成了大写的，但是小写字母却被识别成小写（要求是要识别成大写）

**Comment by two-bee-or-not-two-bee** [comment]
> > 你的数据集还是方式的，识别的是英文中文呢
> > 检测的指标是否正常？
> 
> 数据集格式是扫描的英文票据，识别的是英文。要求就是：不管是大写的文本还是小写的文本都全部识别成大写的。txt中的transcription全部都是大写的字母格式。但是训练的时候检测的指标（召回，准确率等）都可以到达96%，但是识别的指标全部都是0。训练了100多个epoch并测试图像的话大写字母识别成了大写的，但是小写字母却被识别成小写（要求是要识别成大写）

请问你的训练的配置文件怎么设定的呀，我想要区分大小写，但是一直不收敛，而且所有的都识别成了小写，我修改字典为en_dict.txt, 但是好像没啥用
