### ISSUE TITLE
训练RARE报错

### ISSUE THREAD

**Issue by Agino-ltp** [PaddlePaddle/PaddleOCR#3091]
训练自己的数据，其他算法都没问题，就RARE报错
![image](https://user-images.githubusercontent.com/73732417/121778235-b1187580-cbc8-11eb-8b82-8e74e939ff20.png)

**Comment by tink2123** [comment]
看起来是 pred 和 target 类别不一致的报错，可以提供一下配置文件吗？

**Comment by Agino-ltp** [comment]
> 好像是预先和目标类别的错误，可以提供一下配置文件吗？

是的，最大文本长度和类别数出了问题，后面我去看了论文和源代码，谢谢您的回复

**Comment by tink2123** [comment]
不客气～

**Comment by HouYanGG** [comment]
> 

您好，我跟你遇到同样的问题了，请问您是怎么解决的呢，我使用2.2版本的代码
