### ISSUE TITLE
微调法语文本识别模型，accuracy没有提升

### ISSUE THREAD

**Issue by alexawangzi** [PaddlePaddle/PaddleOCR#3092]
您好，目前我有大约3000条真实数据，是从超市产品的照片中利用PPOCRLabel提取的，都是法语。用这个法语数据集， 在官方提供的french_mobile_v2.0_rec_train模型上进行微调，然后用这个法语数据集的数据进行test的时候，accuracy没有提升，反而比微调之前下降了两三个百分点。 想问一下，这有可能是哪个步骤做错了？

另外看到这条问答里提到用来训练的数据应该同时有英文和中文，这对于法语模型的训练和微调应该是不适用的吧？ https://github.com/PaddlePaddle/PaddleOCR/issues/2866 

再次感谢你们的开源工作！

**Comment by littletomatodonkey** [comment]
数据太少了，3000条很容易过拟合，需要再合成一批数据，加到里面一起finetune

**Comment by alexawangzi** [comment]
> 数据太少了，3000条很容易过拟合，需要再合成一批数据，加到里面一起finetune

谢谢！
那么，多少数据量比较合适？真实数据和合成数据的比例应该是多少呢？

**Comment by Evezerest** [comment]
可以参考FAQ中的内容
