### ISSUE TITLE
训练自己的数据集报错无法找到标注文件

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3093]
[Errno 2] No such file or directory: './train_data/train_rec_gt.txt'

**Comment by littletomatodonkey** [comment]
这是评估label文件，需要有的，或者需要把训练时评估这个选项关掉(Global.eval_during_training)

**Comment by hice1207** [comment]
> 这是评估label文件，需要有的，或者需要把训练时评估这个选项关掉(Global.eval_during_training)

朋友你好，我的数据集里有这个文件，我的问题是用相对路径就会报这个问题，用绝对路径就没事，但绝对路径会带来别的bug。所以是为什么相对路径不能用的问题。
