### ISSUE TITLE
由于找不到paddle+inference.dll。

### ISSUE THREAD

**Issue by liyandongpy** [PaddlePaddle/PaddleOCR#3094]
windows 推理C++ 部署时出现错误，
![image](https://user-images.githubusercontent.com/49861986/121988145-66674b00-cdcc-11eb-9c55-04126b80f482.png)

**Comment by Ginkle** [comment]
![image](https://user-images.githubusercontent.com/58083860/122011950-3b422300-cdef-11eb-8a54-474133b43e97.png)

**Comment by liyandongpy** [comment]
@Ginkle 谢谢，问题已经解决了。您这个文档是链接麻烦给我发一下，我看最新的文档上面并没有写明。
