### ISSUE TITLE
PaddleOCR  det_mv3_db.yml 转换为推理模型之后对于同一张图片推理模型几乎检测不出来。。。

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/PaddleOCR#3095]
![20210224041949_199](https://user-images.githubusercontent.com/46549527/121993070-6c155e80-cdd5-11eb-8c28-7c6348561f9c.jpg)
![det_res_20210224041949_199](https://user-images.githubusercontent.com/46549527/121993085-70417c00-cdd5-11eb-9e3d-c50e09f24bed.jpg)

第一张为训练模型检测结果 第二张为检测模型测试结果

 转换代码：python tools/export_model.py         -c configs/det/det_mv3_db_zdl.yml         -o Global.checkpoints=./output/db_mv3/best_accuracy         Global.save_inference_dir=./inference/db_mv4/

**Comment by littletomatodonkey** [comment]
先试下ppocr提供的inference model的检测效果呢？

**Comment by QIANXUNZDL123** [comment]
用ppocr通用模型Inference检测效果也很差

**Comment by ioracion** [comment]
参考下我这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/2470)

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
