### ISSUE TITLE
识别模型的数据增强

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3097]
请问识别模型的参数RecAug这个参数如何启动呢？
![image](https://user-images.githubusercontent.com/43515926/122005274-041c4380-cde8-11eb-8208-2a5a68480e24.png)

**Comment by littletomatodonkey** [comment]
默认就是开启的状态

**Comment by littletomatodonkey** [comment]
不希望添加的话，可以把这个字段删掉

**Comment by zcswdt** [comment]
> 默认就是开启的状态

哦哦哦，这个开启的状态会有多少种数据增强呢？
