### ISSUE TITLE
eval的acc第一次训练的时候特别高，之后一直很低怎么回事？

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#3098]
![image](https://user-images.githubusercontent.com/23546166/122145665-409f7c00-ce88-11eb-8238-13c79ce802e0.png)
情况是在528个epoch开始，第529有最高的准确性，从528epoch开始已经训练到822epoch了，但是准确性如图所示，一直在0.74-0.76之间徘徊，这是不是过拟合了，遇到这种情况应该如何处理，调参还能解决这种问题吗，还是需要做一些数据增强的操作？

**Comment by LDOUBLEV** [comment]
应该是过拟合了，可以多加一些数据增强，加[正则](https://github.com/PaddlePaddle/PaddleOCR/blob/7c1379d6899d955bc353d057337bb909a494bd6a/configs/rec/rec_icdar15_train.yml#L29)，增加数据等等

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
