### ISSUE TITLE
识别时，有好多表格中的内容未识别

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#310]
![image](https://user-images.githubusercontent.com/12640462/87261251-36426880-c4e8-11ea-8ba2-023142514bf3.png)

这个是在线识别的一个效果，图中有用蓝色和绿色标注的内容未进行识别，在det阶段没有检测到，这个是因为什么呢，有的同一列有的可以识别有的不行，谢谢

**Comment by BeyondYourself** [comment]
补充一下，
![image](https://user-images.githubusercontent.com/12640462/87262858-0d24d680-c4ee-11ea-9318-27fb8bc2cc43.png)
我用了另外一张表格，其中有好几行的数字连在一起进行识别了

**Comment by LDOUBLEV** [comment]
可视化的时候设置的阈值是多少，默认是只可视化文本识别的准确度>0.5的检测识别结果。另外，我们的训练数据中表格数据不多，一列数字是当作竖排文本了。

可以把score设置为0 试试，score设置在：
https://github.com/PaddlePaddle/PaddleOCR/blob/a987ec70e8bced756a9b1084c80aa1ede0e2936a/tools/infer/predict_system.py#L149

**Comment by BeyondYourself** [comment]
收到，谢谢

**Comment by LDOUBLEV** [comment]
如果有表格标注数据，使用我们的模型fine-tune训练会好很多

**Comment by BeyondYourself** [comment]
> 如果有表格标注数据，使用我们的模型fine-tune训练会好很多

这个有没有相关链接,thx

**Comment by Maxhyl** [comment]
> 如果有表格标注数据，使用我们的模型fine-tune训练会好很多

请问表格数据标注是按文本标准还是按单元格标注呀@LDOUUBLEV

**Comment by CV-deeplearning** [comment]
> > 如果有表格标注数据，使用我们的模型fine-tune训练会好很多
> 
> 这个有没有相关链接,thx



> 如果有表格标注数据，使用我们的模型fine-tune训练会好很多

你好，怎么fine-tune?可以提供能加载的预训练模型吗？
