### ISSUE TITLE
创建Docker镜像失败

### ISSUE THREAD

**Issue by mxxlei** [PaddlePaddle/PaddleOCR#3101]
Successfully installed PyWavelets-1.1.1 imageio-2.9.0 imgaug-0.4.0 lmdb-1.2.1 networkx-2.5.1 opencv-contrib-python-4.2.0.32 pyclipper-1.2.1 python-Levenshtein-0.12.2 scikit-image-0.17.2 shapely-1.7.1 tifffile-2021.6.14
Removing intermediate container 66a1757b2765
 ---> 7aee4a82aa3a
Step 7/15 : RUN mkdir -p /PaddleOCR/inference/
 ---> Running in ba451386fbdc
Removing intermediate container ba451386fbdc
 ---> 69bb7c5b202d
Step 8/15 : ADD {link} /PaddleOCR/inference/
ADD failed: file not found in build context or excluded by .dockerignore: stat {link}: file does not exist

**Comment by LDOUBLEV** [comment]
link 是没有传入参数吧

**Comment by bswhb** [comment]
参考这个issue：https://github.com/PaddlePaddle/PaddleOCR/issues/2976

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
