### ISSUE TITLE
使用DBNet做文字检测

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3105]
![image](https://user-images.githubusercontent.com/44855506/122188478-91cc6180-cec2-11eb-960b-a3954b8ae9b6.png)
在数据框标注时必须标注点必须是顺时针的吗，可不可以是逆时针四个点，只要闭合就可以

**Comment by LDOUBLEV** [comment]
>  在数据框标注时必须标注点必须是顺时针的吗，可不可以是逆时针四个点，只要闭合就可以

应该是没问题的，不过你也可以加一个排序函数对点排序

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
