### ISSUE TITLE
文字检测时数据增强处理

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3107]
使用DBNet做文字检测的时候，数据旋转角度范围在哪里修改呢

**Comment by Mafengqiang** [comment]
> 使用DBNet做文字检测的时候，数据旋转角度范围在哪里修改呢

没有找到DBNet的数据处理脚本
![image](https://user-images.githubusercontent.com/44855506/122192772-8bd87f80-cec6-11eb-8827-f9d9dfc6dd5b.png)

**Comment by SWHL** [comment]
可以更改这里
https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L81

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
