### ISSUE TITLE
为什么paddleocr 2.0版本的检测效果不如1.0呢 

### ISSUE THREAD

**Issue by andrew-begain** [PaddlePaddle/PaddleOCR#3109]
用的是pip install 的方式

**Comment by LDOUBLEV** [comment]
1.0的模型后处理加了[膨胀](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/utility.py#L50)，也调整了后处理参数

你可以试试在动态图模型里开启膨胀操作，有人调整后处理参数试试https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/utility.py#L45

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
