### ISSUE TITLE
识别模型的resize操作

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3110]
1. 您好，请问一下，在训练识别模型的时候，如下两种pad方式有什么区别吗？
![image](https://user-images.githubusercontent.com/43515926/122197207-8b41e800-ceca-11eb-9208-9b3a6d136f91.png)
2. 在训练识别模型的时候我看代码是用rgb图像进行训练的，这样的话，文本图像的颜色会有很多种。如果使用灰度图训练识别模型这样能否提高识别模型的准确率，消除颜色的影响呢？

**Comment by LDOUBLEV** [comment]
> 您好，请问一下，在训练识别模型的时候，如下两种pad方式有什么区别吗？

两个函数实现在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/7c1379d6899d955bc353d057337bb909a494bd6a/ppocr/data/imaug/rec_img_aug.py#L86


> 在训练识别模型的时候我看代码是用rgb图像进行训练的，这样的话，文本图像的颜色会有很多种。如果使用灰度图训练识别模型这样能否提高识别模型的准确率，消除颜色的影响呢？

看场景吧，颜色影响并不大

**Comment by zcswdt** [comment]
> > 您好，请问一下，在训练识别模型的时候，如下两种pad方式有什么区别吗？
> 
> 两个函数实现在这里：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/7c1379d6899d955bc353d057337bb909a494bd6a/ppocr/data/imaug/rec_img_aug.py#L86
> 
> > 在训练识别模型的时候我看代码是用rgb图像进行训练的，这样的话，文本图像的颜色会有很多种。如果使用灰度图训练识别模型这样能否提高识别模型的准确率，消除颜色的影响呢？
> 
> 看场景吧，颜色影响并不大

1. 可以大概说一下这两个resize代码的区别么？我看了代码的，没懂。
2. 对于图片自然场景下的颜色。原始代码是使用RGB操作的，在数据增强也使用了HSV颜色空间转换，在这方面上是不是已经默认了颜色带来的影响所以才做的数据增强呢？如果使用灰度图训练，灰度图预测的话，是不是效果能提升呢？

**Comment by LDOUBLEV** [comment]
> 对于图片自然场景下的颜色。原始代码是使用RGB操作的，在数据增强也使用了HSV颜色空间转换，在这方面上是不是已经默认了颜色带来的影响所以才做的数据增强呢？如果使用灰度图训练，灰度图预测的话，是不是效果能提升呢？

通用场景估计不会有太大作用

**Comment by zcswdt** [comment]
> > 对于图片自然场景下的颜色。原始代码是使用RGB操作的，在数据增强也使用了HSV颜色空间转换，在这方面上是不是已经默认了颜色带来的影响所以才做的数据增强呢？如果使用灰度图训练，灰度图预测的话，是不是效果能提升呢？
> 
> 通用场景估计不会有太大作用

我觉得还是得做一下实验看看效果。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
