### ISSUE TITLE
该用 OCR 还是 Object Detection 来实现?

### ISSUE THREAD

**Issue by JescalLin** [PaddlePaddle/PaddleOCR#3114]
![擷取](https://user-images.githubusercontent.com/19463066/122315335-69894500-cf4c-11eb-90fe-458ca77d24b0.JPG)

想问一下 像是这种影像
8 13 标签固定是白色
3 10 标签固定是深绿色
4 9 标签固定是黑色
14 7标签固定是红色
我可以把它当成Object Detection 8类来做
还是用OCR 来做呢?
或是有更好的方法
Paddleocr 可以针对文字底色背景做训练吗? 像是图像看到 红的 只辨识 14 or 7 
谢谢各位

**Comment by tink2123** [comment]
类别比较少的话，也可以用deteciton来做。可以先分别试下两种模型在你场景上的效果，选择效果好的去进一步调优。
针对文字背景这个暂时还不行。
