### ISSUE TITLE
用自训练的中文attention模型预测时报错：root ERROR: rec_algorithm must in ['CRNN']

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleOCR#3115]
预测命令：
`python3 paddleocr.py --det_model_dir ./inference/det  --rec_model_dir ./inference/rec_att  --image_dir ./testImg --rec_char_dict_path ./train_data/dataset/news2016zh_train1_dict-8k.txt --rec_image_shape='3, 32, 100' --rec_algorithm='RARE'`

报错：
`/data/anaconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/data/anaconda3/envs/paddle2.x/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/data/anaconda3/envs/paddle2.x/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/ai/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='./inference/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='./testImg', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='RARE', rec_batch_num=6, rec_char_dict_path='./train_data/dataset/news2016zh_train1_dict-8k.txt', rec_char_type='ch', rec_image_shape='3, 32, 100', rec_model_dir='./inference/rec_att', use_angle_cls=False, use_dilation=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
[2021/06/17 10:05:00] root ERROR: rec_algorithm must in ['CRNN']`

**Comment by chenxuezhao** [comment]
train用的config文件(部分)：

> Global:
  use_gpu: True
  epoch_num: 10000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/b3_rare_r34_none_gru/
  save_epoch_step: 100
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ./train_data/dataset/news2016zh_train1_dict-8k.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.0000

Architecture:
  model_type: rec
  algorithm: RARE
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: large
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256 #96
  Head:
    name: AttentionHead  # AttentionHead
    hidden_size: 256 #
    l2_decay: 0.00001

Loss:
  name: AttentionLoss

PostProcess:
  name: AttnLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

**Comment by chenxuezhao** [comment]
预测命令改为：

> python3 paddleocr.py --det_model_dir ./inference/det --rec_model_dir ./inference/rec_att --image_dir ./testImg --rec_char_dict_path ./train_data/dataset/news2016zh_train1_dict-8k.txt --rec_image_shape='3, 32, 100' --rec_algorithm='RARE'

后，又会报下面的错误：

> [2021/06/17 10:45:36] root INFO: dt_boxes num : 20, elapse : 2.1174910068511963
Traceback (most recent call last):
  File "paddleocr.py", line 428, in <module>
    main()
  File "paddleocr.py", line 419, in main
    result = ocr_engine.ocr(img_path,
  File "paddleocr.py", line 385, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/data/work/PaddleOCR-N/PaddleOCR/tools/infer/predict_system.py", line 109, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/data/work/PaddleOCR-N/PaddleOCR/tools/infer/predict_rec.py", line 243, in __call__
    rec_result = self.postprocess_op(preds)
  File "/data/work/PaddleOCR-N/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/data/work/PaddleOCR-N/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range

**Comment by tink2123** [comment]
ppocr.py 目前只支持CRNN模型，要预测attention的话请使用：
```
python3 tools/infer/predict_system.py --det_model_dir ./inference/det --rec_model_dir ./inference/rec_att --image_dir ./testImg --rec_char_dict_path ./train_data/dataset/news2016zh_train1_dict-8k.txt --rec_image_shape='3, 32, 100' --rec_algorithm='RARE'
```

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
