### ISSUE TITLE
centos7系统中c++推理模型部署失败

### ISSUE THREAD

**Issue by weixing19** [PaddlePaddle/PaddleOCR#3119]
操作系统：x86_64 CentOS Linux release 7.9.2009 (Core)

同机器编译了opencv4.5.0和paddlepaddle
opencv4.5.0目录结构如下：
/myapps/opencv-4.5.0
                   |-build
                   |-3rdparty
                   |-apps
                   |-include .....
[nohup.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6667361/nohup.txt)
[nohup.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6667362/nohup.txt)

paddlepaddle编译后的库目录结构如下：
/myapps/fluid_inference
                   |-paddle
                   |-paddle_inference_install_dir
                   |-third_party
                   |-CMakeCache.txt
                   |-version.txt

编译PaddleOCR时报错如下：
Reaping winning child 0x8b38f0 PID 2651 
Live child 0x8b38f0 (CMakeFiles/ocr_system.dir/all) PID 2654 
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile `CMakeFiles/ocr_system.dir/build.make'...
Reading makefile `CMakeFiles/ocr_system.dir/depend.make' (search path) (no ~ expansion)...
Reading makefile `CMakeFiles/ocr_system.dir/compiler_depend.make' (search path) (no ~ expansion)...
Reading makefile `CMakeFiles/ocr_system.dir/progress.make' (search path) (no ~ expansion)...
Reading makefile `CMakeFiles/ocr_system.dir/flags.make' (search path) (no ~ expansion)...
Updating makefiles....
 Considering target file `CMakeFiles/ocr_system.dir/flags.make'.
  Looking for an implicit rule for `CMakeFiles/ocr_system.dir/flags.make'.
  No implicit rule found for `CMakeFiles/ocr_system.dir/flags.make'.
  Finished prerequisites of target file `CMakeFiles/ocr_system.dir/flags.make'.
 No need to remake target `CMakeFiles/ocr_system.dir/flags.make'.
 Considering target file `CMakeFiles/ocr_system.dir/progress.make'.
  Looking for an implicit rule for `CMakeFiles/ocr_system.dir/progress.make'.
  No implicit rule found for `CMakeFiles/ocr_system.dir/progress.make'.
  Finished prerequisites of target file `CMakeFiles/ocr_system.dir/progress.make'.
 No need to remake target `CMakeFiles/ocr_system.dir/progress.make'.
 Considering target file `CMakeFiles/ocr_system.dir/compiler_depend.make'.
  Looking for an implicit rule for `CMakeFiles/ocr_system.dir/compiler_depend.make'.
  No implicit rule found for `CMakeFiles/ocr_system.dir/compiler_depend.make'.
  Finished prerequisites of target file `CMakeFiles/ocr_system.dir/compiler_depend.make'.
 No need to remake target `CMakeFiles/ocr_system.dir/compiler_depend.make'.
 Considering target file `CMakeFiles/ocr_system.dir/depend.make'.
  Looking for an implicit rule for `CMakeFiles/ocr_system.dir/depend.make'.
  No implicit rule found for `CMakeFiles/ocr_system.dir/depend.make'.
  Finished prerequisites of target file `CMakeFiles/ocr_system.dir/depend.make'.
 No need to remake target `CMakeFiles/ocr_system.dir/depend.make'.
 Considering target file `CMakeFiles/ocr_system.dir/build.make'.
  Looking for an implicit rule for `CMakeFiles/ocr_system.dir/build.make'.
  No implicit rule found for `CMakeFiles/ocr_system.dir/build.make'.
  Finished prerequisites of target file `CMakeFiles/ocr_system.dir/build.make'.
 No need to remake target `CMakeFiles/ocr_system.dir/build.make'.
Updating goal targets....
Considering target file `CMakeFiles/ocr_system.dir/build'.
 File `CMakeFiles/ocr_system.dir/build' does not exist.
  Considering target file `ocr_system'.
   File `ocr_system' does not exist.
    Considering target file `CMakeFiles/ocr_system.dir/link.txt'.
     Looking for an implicit rule for `CMakeFiles/ocr_system.dir/link.txt'.
     No implicit rule found for `CMakeFiles/ocr_system.dir/link.txt'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/link.txt'.
    No need to remake target `CMakeFiles/ocr_system.dir/link.txt'.
    Considering target file `CMakeFiles/ocr_system.dir/src/clipper.o'.
     File `CMakeFiles/ocr_system.dir/src/clipper.o' does not exist.
      Considering target file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
       Looking for an implicit rule for `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
       No implicit rule found for `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
       Finished prerequisites of target file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      No need to remake target `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/clipper.cpp'.
       Looking for an implicit rule for `../src/clipper.cpp'.
       No implicit rule found for `../src/clipper.cpp'.
       Finished prerequisites of target file `../src/clipper.cpp'.
      No need to remake target `../src/clipper.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/clipper.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/clipper.o'.
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:75 to update target `CMakeFiles/ocr_system.dir/src/clipper.o'.
Putting child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/clipper.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/config.o'.
     File `CMakeFiles/ocr_system.dir/src/config.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/config.cpp'.
       Looking for an implicit rule for `../src/config.cpp'.
       No implicit rule found for `../src/config.cpp'.
       Finished prerequisites of target file `../src/config.cpp'.
      No need to remake target `../src/config.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/config.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/config.o'.
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:89 to update target `CMakeFiles/ocr_system.dir/src/config.o'.
Putting child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/config.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/main.o'.
     File `CMakeFiles/ocr_system.dir/src/main.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/main.cpp'.
       Looking for an implicit rule for `../src/main.cpp'.
       No implicit rule found for `../src/main.cpp'.
       Finished prerequisites of target file `../src/main.cpp'.
      No need to remake target `../src/main.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/main.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/main.o'.
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:103 to update target `CMakeFiles/ocr_system.dir/src/main.o'.
Putting child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/main.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/ocr_cls.o'.
     File `CMakeFiles/ocr_system.dir/src/ocr_cls.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/ocr_cls.cpp'.
       Looking for an implicit rule for `../src/ocr_cls.cpp'.
       No implicit rule found for `../src/ocr_cls.cpp'.
       Finished prerequisites of target file `../src/ocr_cls.cpp'.
      No need to remake target `../src/ocr_cls.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/ocr_cls.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/ocr_cls.o'.
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:117 to update target `CMakeFiles/ocr_system.dir/src/ocr_cls.o'.
Putting child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/ocr_cls.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/ocr_det.o'.
     File `CMakeFiles/ocr_system.dir/src/ocr_det.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/ocr_det.cpp'.
       Looking for an implicit rule for `../src/ocr_det.cpp'.
       No implicit rule found for `../src/ocr_det.cpp'.
       Finished prerequisites of target file `../src/ocr_det.cpp'.
      No need to remake target `../src/ocr_det.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/ocr_det.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/ocr_det.o'.
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:131 to update target `CMakeFiles/ocr_system.dir/src/ocr_det.o'.
Putting child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/ocr_det.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/ocr_rec.o'.
     File `CMakeFiles/ocr_system.dir/src/ocr_rec.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/ocr_rec.cpp'.
       Looking for an implicit rule for `../src/ocr_rec.cpp'.
       No implicit rule found for `../src/ocr_rec.cpp'.
       Finished prerequisites of target file `../src/ocr_rec.cpp'.
      No need to remake target `../src/ocr_rec.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/ocr_rec.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/ocr_rec.o'.
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Invoking recipe from CMakeFiles/ocr_system.dir/build.make:145 to update target `CMakeFiles/ocr_system.dir/src/ocr_rec.o'.
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
Putting child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 on the chain.
    Recipe of `CMakeFiles/ocr_system.dir/src/ocr_rec.o' is being run.
    Considering target file `CMakeFiles/ocr_system.dir/src/postprocess_op.o'.
     File `CMakeFiles/ocr_system.dir/src/postprocess_op.o' does not exist.
      Pruning file `CMakeFiles/ocr_system.dir/compiler_depend.ts'.
      Pruning file `CMakeFiles/ocr_system.dir/flags.make'.
      Considering target file `../src/postprocess_op.cpp'.
       Looking for an implicit rule for `../src/postprocess_op.cpp'.
       No implicit rule found for `../src/postprocess_op.cpp'.
       Finished prerequisites of target file `../src/postprocess_op.cpp'.
      No need to remake target `../src/postprocess_op.cpp'.
     Finished prerequisites of target file `CMakeFiles/ocr_system.dir/src/postprocess_op.o'.
    Must remake target `CMakeFiles/ocr_system.dir/src/postprocess_op.o'.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2656 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Reaping winning child 0x22141b0 PID 2656 
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2655 
Reaping winning child 0x2212f20 PID 2655 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2657 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping winning child 0x2218270 PID 2657 
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/clipper.d: No such file or directory
compilation terminated.
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/config.d: No such file or directory
compilation terminated.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2658 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping winning child 0x221ac20 PID 2658 
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2659 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping winning child 0x221d550 PID 2659 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2660 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping winning child 0x221fef0 PID 2660 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x22141b0 (CMakeFiles/ocr_system.dir/src/config.o) PID 2661 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping losing child 0x22141b0 PID 2661 
make[2]: *** [CMakeFiles/ocr_system.dir/src/config.o] Error 1
Removing child 0x22141b0 PID 2661 from chain.
make[2]: *** Waiting for unfinished jobs....
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x2212f20 (CMakeFiles/ocr_system.dir/src/clipper.o) PID 2662 
Reaping losing child 0x2212f20 PID 2662 
make[2]: *** [CMakeFiles/ocr_system.dir/src/clipper.o] Error 1
Removing child 0x2212f20 PID 2662 from chain.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x2218270 (CMakeFiles/ocr_system.dir/src/main.o) PID 2665 
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/main.d: No such file or directory
compilation terminated.
Reaping losing child 0x2218270 PID 2665 
make[2]: *** [CMakeFiles/ocr_system.dir/src/main.o] Error 1
Removing child 0x2218270 PID 2665 from chain.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221ac20 (CMakeFiles/ocr_system.dir/src/ocr_cls.o) PID 2666 
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/ocr_cls.d: No such file or directory
compilation terminated.
Reaping losing child 0x221ac20 PID 2666 
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_cls.o] Error 1
Removing child 0x221ac20 PID 2666 from chain.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221d550 (CMakeFiles/ocr_system.dir/src/ocr_det.o) PID 2669 
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/ocr_det.d: No such file or directory
compilation terminated.
Reaping losing child 0x221d550 PID 2669 
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_det.o] Error 1
Removing child 0x221d550 PID 2669 from chain.
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
Live child 0x221fef0 (CMakeFiles/ocr_system.dir/src/ocr_rec.o) PID 2670 
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/ocr_rec.d: No such file or directory
compilation terminated.
Reaping losing child 0x221fef0 PID 2670 
make[2]: *** [CMakeFiles/ocr_system.dir/src/ocr_rec.o] Error 1
Removing child 0x221fef0 PID 2670 from chain.
Reaping losing child 0x8b38f0 PID 2654 
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Removing child 0x8b38f0 PID 2654 from chain.
Reaping losing child 0x9ea270 PID 2650 
make: *** [all] Error 2
Removing child 0x9ea270 PID 2650 from chain.

详细内容见上面的附件：**nohup.txt**

**Comment by LDOUBLEV** [comment]
build.sh里面的参数怎么设置的？检查下有没有正确链接到预测库

没试过cmake 3.20，尝试3.16， 3.17试试，

**Comment by weixing19** [comment]
非常感谢，确实是cmake版本过高导致，更换低版本（3.17.5）后解决问题。
