### ISSUE TITLE
使用android demo，paddle-lite升级到2.8，替换自己训练的模型，偶尔识别内容异常。

### ISSUE THREAD

**Issue by MichaelLiu-TJ** [PaddlePaddle/PaddleOCR#3122]
使用android demo，paddle-lite升级到2.8，替换自己训练的模型，偶尔识别内容异常。

异常的时候情况如下：文本检测可以正确标出文本框的位置，但是文本行的文字长度为1，内容为0，score为0。

加载一次模型连续预测没问题；每次重新打开app、或者重新编译安装到手机打开之后，会有比较低的几率出现模型识别不到文字的情况，如果关了应用，清理了后台，下一次打开又正常了。

**Comment by tink2123** [comment]
收到，感谢反馈，我们测试看看。

**Comment by hzjai0624** [comment]
@tink2123  请问如何解决这种情况。

**Comment by WenmuZhou** [comment]
使用lite2.9吧

**Comment by MichaelLiu-TJ** [comment]
> 使用lite2.9吧

使用2.9还是有这种情况出现

**Comment by WenmuZhou** [comment]
你部署到手机之前，把app卸载掉，再看看

**Comment by MichaelLiu-TJ** [comment]
> 你部署到手机之前，把app卸载掉，再看看

是的，我每次都是卸载，然后用android stuio重新build安装到手机上，会有一定几率，那一次打开应用后，检测模型是正常工作的，但是识别的score是0，length为1，内容就是1个0；然后删了，再build安装，可能就正常了，全程都是不动代码的

**Comment by MichaelLiu-TJ** [comment]
模型用opt 2.9 和2.8 ，分别搭配对应版本的库，都有问题。
用opt2.6.1，lite 2.6.1，问题不见
