### ISSUE TITLE
可以对动图（test.gif）进行文本检测吗？

### ISSUE THREAD

**Issue by cqhblg** [PaddlePaddle/PaddleOCR#3123]
想对一个gif动图进行检测，能否得到圈出文字后的gif动图

**Comment by tink2123** [comment]
暂时不可以，检测允许的输入图片是静态的，有需要的话可以自己把gif按帧输入检测，再把输出结果合并起来。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
