### ISSUE TITLE
修改字典后的迁移学习无效

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#3124]
修改字典后，即使不改变字典的总长度，只是局部替换掉一个字，迁移学习还是不成功，虽然没有报错，但是acc是从0开始的。请问有什么办法，在修改字典后，也能利用迁移学习加快训练吗？

**Comment by tink2123** [comment]
修改字典之后acc为0是很正常的，acc计算时只有整行预测正确才算对。
虽然刚开始acc为0，但加载预训练模型会加快模型的收敛速度，继续训练即可。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
