### ISSUE TITLE
paddleocr 静态图版本是不是不支持visualdl功能？

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleOCR#3125]
你好，如题，请问paddleocr 静态图版本是不是不支持visualdl功能？配置文件没找到use_visualdl设定。可以自己添加吗？

**Comment by tink2123** [comment]
静态图代码里没有适配，可以自己添加相关代码，具体可参考：https://github.com/PaddlePaddle/VisualDL/blob/develop/README_CN.md#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F
