### ISSUE TITLE
为什么cpp_infer的推理接口没有方向分类器模块？

### ISSUE THREAD

**Issue by rainmakerMa** [PaddlePaddle/PaddleOCR#3128]
如题，cpp_infer demo 对文本行没有做方向的判定和转正？

**Comment by WenmuZhou** [comment]
cpp_infer对外只提供了系统整体的，可以自行修改

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
