### ISSUE TITLE
paddleocr使用自己的数据集训练文本检测模型，运行到第0个epoch快完成时退出，1073741819（0xc0000005）

### ISSUE THREAD

**Issue by micro-driver** [PaddlePaddle/PaddleOCR#3129]
![image](https://user-images.githubusercontent.com/85141858/122511244-83ed1c80-d039-11eb-9653-ad27ebf727de.png)
![image](https://user-images.githubusercontent.com/85141858/122511309-99fadd00-d039-11eb-90e6-77d74d6a559e.png)

**Comment by Jitesh4389** [comment]
are you traning on CPU or GPU

**Comment by micro-driver** [comment]
> are you traning on CPU or GPU

Cpu

**Comment by WenmuZhou** [comment]
这一行是最新代码不 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/program.py#L202

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
