### ISSUE TITLE
关于tensorRT预测

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleOCR#313]
我看utility.py文件中已经有parser.add_argument("--use_tensorrt", type=str2bool, default=False)了,是不是意味着已经支持tensorRT推理加速库了?具体用法可以说一下吗,paddlepaddle框架是否需要重新编译呢

**Comment by dyning** [comment]
我们尝试TensorRT加速不明显，目前还在验证tensorRT6 支持可变长输入的效果。
