### ISSUE TITLE
different output of inference model  and traing model

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#3130]
i was trained model on 100k image training model acc 98 give good output 

[2021/06/18 11:07:08] root INFO: load pretrained model from ['./output/rec_sankrit_lite_100_50_200/best_accuracy']
[2021/06/18 11:07:08] root INFO: infer_img: synth_words/images/sans_synth_95951.jpg
[2021/06/18 11:07:08] root INFO: result: ('योगमायाम्', 0.99999833) //Correct ouput
[2021/06/18 11:07:08] root INFO: success!

after converting traning model into inference model  and run module.py  output has differnt 
./inference/sankrit_CRNN_100_50_200/
[[{'text': 'ळक़छलूळूलग़', 'confidence': 0.9999983310699463}]] // Incorrect output

this is a input image 
![sans_synth_95951](https://user-images.githubusercontent.com/74894949/122512259-0833a580-d022-11eb-8aad-6f21ebdf52da.jpg)

**Comment by Jitesh4389** [comment]
#params for text recognizer 
    cfg.rec_algorithm = "CRNN"
    cfg.rec_model_dir = "./inference/sankrit_CRNN_100_50_200/"
    cfg.rec_image_shape = "3, 32, 320"
    cfg.rec_char_type = 'devanagari'
    cfg.rec_batch_num = 30
    cfg.max_text_length = 25
    cfg.rec_char_dict_path = "./ppocr/utils/dict/devanagari_dict.txt"
    cfg.use_space_char = True
    cfg.use_pdserving = False
    cfg.use_tensorrt = False
    return cfg

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/2362  参考这个

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
