### ISSUE TITLE
Accuracy in training and accuracy in prediction do not match.

### ISSUE THREAD

**Issue by ikiyo-mlb** [PaddlePaddle/PaddleOCR#3131]
I would appreciate your help.

paddleOCR 2.1
Google Colab
SRN model (rec model only)　

The accuracy of my SRN model for the training and test data displayed during training is about 1.0 and 0.98 respectively. After exporting this model, I got the predicted strings and confidence probabilities from the tuple "rec_res" in the script /tools/infer/predict_rec.py. When I compared the predictions with the correct labels in the gt file, I found that the accuracy of the model on both the training and test data was only about 0.90.

I also compared the predictions made by infer_rec.py before exporting the model, and the predictions made by the model for some of the data that failed to be recognized by predict_rec.py, the resulting strings were the same as those displayed by predict_rec.py.

Here are some of the data that failed to recognize characters taken from the tuple of rec_res, and the data where the correct label and prediction do not match perfectly. 
<img width="919" alt="スクリーンショット 2021-06-18 16 23 35" src="https://user-images.githubusercontent.com/84305876/122526868-b9076800-d055-11eb-84c3-8cea2f13da62.png">

**Comment by Jitesh4389** [comment]
same Qestion i have

https://github.com/PaddlePaddle/PaddleOCR/issues/3130

**Comment by WenmuZhou** [comment]
参考这个 https://github.com/PaddlePaddle/PaddleOCR/issues/2362

**Comment by ikiyo-mlb** [comment]
The page you refer to seems to be a little different from my question. The model I am using is an SRN model, and my question is not about bridging the gap between infer_rec and predict_rec. In my case, the prediction of infer_rec and predict_rec correspond.

It seems that the process of resize for SRN model (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/predict_rec.py#:~:text=def-,resize_norm_img_srn,-(self%2C%20img%2C%20image_shape) is done in predict_rec, but is this function different from the resize process that is called from tool/train.py just before training?

Could you tell me the part of the resize code that SRN model calls before training? I would like to copy the resize process to predict_rec.py.

**Comment by WenmuZhou** [comment]
srn training stage resize:  https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/data/imaug/rec_img_aug.py#L135

You can see if the output of predict and infer is the same if the input of the same numpy matrix is the same

**Comment by Jitesh4389** [comment]
What about CRNN is it resize of image matters with predict and infer ?why infer give good output and predict Not

**Comment by Evezerest** [comment]
CRNN do the same resize
