### ISSUE TITLE
Paddle 2.0.0，`Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by xxAna** [PaddlePaddle/PaddleOCR#3133]
fluid.install_check.run_check()测试paddlepaddle的时候，反馈Your Paddle Fluid works well on SINGLE GPU or CPU.但是单卡运行无法调用GPU。然后多卡情况则显示FatalError: `Segmentation fault` is detected by the operating system.请问这是什么原因呢。我看到有贴子说的2.1的问题，然后回退到2.0.0还是不行

**Comment by WenmuZhou** [comment]
多卡的话需要nccl的，paddle.utils.run_check() 这个命令显示ok的话，单卡就是好的，你报什么错误，单卡的时候
