### ISSUE TITLE
docker环境下，基于total_text训练PGNet Dataloader报错

### ISSUE THREAD

**Issue by bityigoss** [PaddlePaddle/PaddleOCR#3135]
镜像使用的是paddle部署gpu镜像
训练命令为
python3.7 -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=./pretrain_models/train_step1/best_accuracy Global.load_static_weights=False

由于train.num_works默认是16情况下，执行报错(queue empty之类的错误)，查issue说改成num_works=0可以运行，但是改成num_works=0之后，仍然报错如下错误：
![image](https://user-images.githubusercontent.com/6988886/122543951-e3115800-d05e-11eb-86d3-af3fc5e69af1.png)

**Comment by WenmuZhou** [comment]
use_shared_memory改为false看看
