### ISSUE TITLE
将自己训练的inference模型使用paddlelite的opt转换为lite模型时，显示不支持算子

### ISSUE THREAD

**Issue by micro-driver** [PaddlePaddle/PaddleOCR#3136]
![image](https://user-images.githubusercontent.com/85141858/122633245-18bf4b00-d10a-11eb-8cd9-b134c178d612.png)
![image](https://user-images.githubusercontent.com/85141858/122633248-21178600-d10a-11eb-954b-549aabc679b7.png)

**Comment by LDOUBLEV** [comment]
你在x86上运行不需要用paddlelite，用paddle就行，如果是arm上预测，推荐用paddlelite
