### ISSUE TITLE
 请问关于android 中java的部署Demo，大概什么时候可以发布？

### ISSUE THREAD

**Issue by martinou** [PaddlePaddle/PaddleOCR#314]
请问关于android 中java的部署Demo，大概什么时候可以发布？

**Comment by dyning** [comment]
目前已经提供端侧部署的代码，https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md，可以尝试集成到android中。此外，也可以先看看下面两个PR：
https://github.com/PaddlePaddle/Paddle-Lite-Demo/pull/80
https://github.com/PaddlePaddle/Paddle-Lite-Demo/pull/81

**Comment by martinou** [comment]
编译过程中出现clipper.hpp找不到

**Comment by LDOUBLEV** [comment]
> 编译过程中出现clipper.hpp找不到

make  -j

**Comment by LDOUBLEV** [comment]
> > 编译过程中出现clipper.hpp找不到
> 
> make -j

**Comment by authorfu** [comment]
目前android版本demo已经发布，https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/android_demo
