### ISSUE TITLE
特定图片导致显存打满且不会释放

### ISSUE THREAD

**Issue by Appla** [PaddlePaddle/PaddleOCR#3140]
### 环境信息
* Ubunut 18.04, 8C15G,  GPU 15G
* paddlepaddle-gpu-2.1.0
* paddleocr 2.0.6 [pypi]
* CUDA 10.2

### 问题描述
* 使用中遇到X轴或者Y轴如果像素为1，导致GPU内存打满，后续服务因显存不足无法使用的情况，实际哪些图片为什么会触发不可知（创建paddleocr对象时有指定GPU内存限制为3G，实际使用远超3G）
* 样例图片
    - ![2021061909302260cd48aedbc40](https://user-images.githubusercontent.com/8346196/122699050-39f37900-d27b-11eb-911a-2f674d4efb40.png)
    - ![2021061912234260cd714e69040](https://user-images.githubusercontent.com/8346196/122699324-c3a34680-d27b-11eb-957f-d8009605fe84.png)

* Windows上也有类似现象，CPU迅速飙升

**Comment by Evezerest** [comment]
什么情况下会对这种图片进行ocr呢？图片尺寸太大会导致显存爆掉的
