### ISSUE TITLE
续训：EOFError: Ran out of input

### ISSUE THREAD

**Issue by irsLu** [PaddlePaddle/PaddleOCR#3145]
在服务器上训练时，进程中断了，然后通过续训，报EOFError: Ran out of input的错误：
![image](https://user-images.githubusercontent.com/42465965/122845519-8354ce80-d336-11eb-9409-ce8f5cec1fce.png)

**Comment by irsLu** [comment]
训续指令为：python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '1,2,3,4,5,6,7'  tools/train.py -c configs/rec/ztl_config_exp/r50_tps_bilstm_ctc_124.yml -o Global.checkpoints=./output/rec/500_resnet_fpn_50_trans_4_512_640/latest

**Comment by DreamJokerMJ** [comment]
应该考虑pth文件本身出现了问题，比如我在pycharm里删除了保存的模型，然后后悔了，执行撤销，有可能这个pth文件恢复回来了，但是一看文件大小，发现是0。

当然，另一个情况就是比较多见的DataLoader里num_worker值引起的，改成0即可。
