### ISSUE TITLE
test_hubserving服务器部署时读取img失败

### ISSUE THREAD

**Issue by ykpercy** [PaddlePaddle/PaddleOCR#3148]
PaddleHub服务化部署时，我在module.py增加了每个图片识别结果按照对应路径保存为json文件的程序。
module.py的单元测试通过，可以按对应路径保存json文件。
问题：在本地启动服务部署的时候出现读取图片为空的错误，错误提示如下：
程序如下：
```
    def predict(self, images=[], paths=[]):
        """
        Get the chinese texts in the predicted images.
        Args:
            images (list(numpy.ndarray)): images data, shape of each is [H, W, C]. If images not paths
            paths (list[str]): The paths of images. If paths not images
        Returns:
            res (list): The result of chinese texts and save path of images.
        """

        if images != [] and isinstance(images, list) and paths == []:
            predicted_data = images
        elif images == [] and isinstance(paths, list) and paths != []:
            predicted_data = self.read_images(paths)
        else:
            raise TypeError("The input data is inconsistent with expectations.")

        assert predicted_data != [], "There is not any image to be predicted. Please check the input data."

        all_results = []
        for img, img_path in zip(predicted_data, paths):
            if img is None:
                logger.info("error in loading image")
                all_results.append([])
                continue
            starttime = time.time()
            dt_boxes, rec_res = self.text_sys(img)
            elapse = time.time() - starttime
            logger.info("Predict time: {}".format(elapse))

            dt_num = len(dt_boxes)
            rec_res_final = []

            for dno in range(dt_num):
                text, score = rec_res[dno]
                # rec_res_final.append({
                #     'text': text,
                #     'confidence': float(score),
                #     'text_region': dt_boxes[dno].astype(np.int).tolist()
                # })
                rec_res_final.append({
                    'text': text
                })

            # 此处将识别文字保存为JSON文件
            img_name = os.path.basename(img_path)
            save_name = img_name.split('.')[0] + '.json'
            save_path = os.path.join('./inference_text/', save_name)
            with open(save_path, 'w') as f:  # save the file
                text = json.dumps(rec_res_final, ensure_ascii=False)
                f.write(text)

            print(f'text saved!')

            all_results.append(rec_res_final)
        return all_results
```
启动服务命令：
服务端：`hub serving start -m ocr_system`
客户端：`python3 tools/test_hubserving.py http://192.168.2.19:8866/predict/ocr_system ./doc/imgs/`

错误提示：
```
import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "tools/test_hubserving.py", line 122, in <module>
    main(server_url, image_path)
  File "tools/test_hubserving.py", line 94, in main
    res = r.json()["results"][0]
IndexError: list index out of range
```
未添加这段保存程序前，服务部署可以在线打印识别文本。
增加这段程序后保错，请问这是什么问题？

**Comment by WenmuZhou** [comment]
看起来的你的服务贸易返回任何结果，可以进行print调试看看

**Comment by ykpercy** [comment]
谢谢，昨天我和同事调试半天，还是不行。
调试结果显示：服务器可以读取post上传的图像数据，只是返回数据为空。
基本定位在调用module.py内检测识别算法出现问题，而文件保存处理刚好添加在module.py内！

我今天尝试保持post请求module.py内的检测识别任务不变，将识别的文本保存程序放在test_hubserving.py。
然后单元测试可以正常保存JSON文件。
启动服务器后，也可以返回识别的文本数据，同时保存在对应路径。
这样单元测试和服务器测试都通过了。😊

**Comment by cool3rzZ** [comment]
File "tools/test_hubserving.py", line 94, in main
    res = r.json()["results"][0]
IndexError: list index out of range
我单独启动ocr_det服务时就报这个错，打印发现r.json()["results"]为None。但是启动ocr_system任务就没事

**Comment by zhangyingying520** [comment]
> 谢谢，昨天我和同事调试半天，还是不行。 调试结果显示：服务器可以读取post上传的图像数据，只是返回数据为空。 基本定位在调用module.py内检测识别算法出现问题，而文件保存处理刚好添加在module.py内！
> 
> 我今天尝试保持post请求module.py内的检测识别任务不变，将识别的文本保存程序放在test_hubserving.py。 然后单元测试可以正常保存JSON文件。 启动服务器后，也可以返回识别的文本数据，同时保存在对应路径。 这样单元测试和服务器测试都通过了。😊

麻烦问一下，你这个是测试本地的图片还是服务器上的图片

**Comment by ykpercy** [comment]
> > 谢谢，昨天我和同事调试半天，还是不行。 调试结果显示：服务器可以读取post上传的图像数据，只是返回数据为空。 基本定位在调用module.py内检测识别算法出现问题，而文件保存处理刚好添加在module.py内！
> > 我今天尝试保持post请求module.py内的检测识别任务不变，将识别的文本保存程序放在test_hubserving.py。 然后单元测试可以正常保存JSON文件。 启动服务器后，也可以返回识别的文本数据，同时保存在对应路径。 这样单元测试和服务器测试都通过了。😊
> 
> 麻烦问一下，你这个是测试本地的图片还是服务器上的图片

从IP端口上看，应该是在本地另外起的一个命令行运行服务，模拟服务端

**Comment by ykpercy** [comment]
请问你的问题解决了吗？需要帮助的话这是我的微信：heuyangkang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 上午8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] test_hubserving服务器部署时读取img失败 (#3148)





    
谢谢，昨天我和同事调试半天，还是不行。 调试结果显示：服务器可以读取post上传的图像数据，只是返回数据为空。 基本定位在调用module.py内检测识别算法出现问题，而文件保存处理刚好添加在module.py内！
 我今天尝试保持post请求module.py内的检测识别任务不变，将识别的文本保存程序放在test_hubserving.py。 然后单元测试可以正常保存JSON文件。 启动服务器后，也可以返回识别的文本数据，同时保存在对应路径。 这样单元测试和服务器测试都通过了。😊
  
麻烦问一下，你这个是测试本地的图片还是服务器上的图片
  
从IP端口上看，应该是在本地另外起的一个命令行运行服务，模拟服务端
  
可以加个联系方式咨询一下吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuxh6** [comment]
我是运行了 hub install ./deploy/hubserving/ocr_system/  之后就解决了。仅供参考
