### ISSUE TITLE
CRNN训练文字识别加载数据时报错

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3149]
![image](https://user-images.githubusercontent.com/44855506/122858628-27497480-d34d-11eb-95ac-75ca68b6962d.png)
能帮忙看一下是什么问题吗

**Comment by WenmuZhou** [comment]
看错误是一个batch内的图片大小不一致，可以在dataset里打印一下每次load出来的图片shape看看

**Comment by Mafengqiang** [comment]
> 看错误是一个batch内的图片大小不一致，可以在dataset里打印一下每次load出来的图片shape看看
老师，有个问题还想问你一下，就是如果图片的宽高比过大的话，针对长文本那种，有的图片的宽高比为2000/80这种，resize之后会丢失图片信息吧，但是数据集图片的尺度变化比较大，这种宽高比的图片相对较少，如果改大image_shape的话会影响其他数据的识别吗，有没有比较好的解决方案呢

**Comment by WenmuZhou** [comment]
这种图片很少的话直接放弃吧
