### ISSUE TITLE
arm_linux 边缘设备cpp部署

### ISSUE THREAD

**Issue by rainmakerMa** [PaddlePaddle/PaddleOCR#3151]
请问一下paddleocr开源的端侧部署项目有使用paddle lite进行推理的demo吗，
目前看到paddle_ocr官方的cpp_infer是使用paddle inference进行推理的，但是在arm边缘设备上没法编译paddle预测库，请问是否有使用paddle lite的样例，或者有更好的解决方案，谢谢。

**Comment by WenmuZhou** [comment]
有的，在这里，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/deploy/lite/readme.md

**Comment by rainmakerMa** [comment]
@WenmuZhou 我按照文档走下来，在编译的时候报错， Makefile:4: ../Makefile.def: No such file or directory  makefile是不是和教程没对应啊，makefile.def 和third-party目录不存在的呀

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/2376 参考一下这个

**Comment by chshwei-perfxlab** [comment]
@WenmuZhou 你好！#2376并没有解决makefile.def 没有的问题，请问现在是否更新解决此问题
