### ISSUE TITLE
识别模型微调经验

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/PaddleOCR#3152]
有没有大佬分享一下基于预训练模型微调的经验，想提升一下证件场景下的识别准确率，但是能拿到的真实的证件素材数量有限，
使用的合成证件素材训练的识别效果较差。想问下针对这种情况该如何训练比较合适。

**Comment by MissPenguin** [comment]
如果是有数据只是没标注，可以用PPOCRLabel标一批；
如果原始数据就很少，可以从网上爬虫一批下来标一下，另外可以加一些数据增强；
此外，公开数据集一般也能有帮助的，可以找一批加进去，即便是不同场景，但是至少是真实数据。
