### ISSUE TITLE
学习率衰减可以每隔一定迭代数，或者epoches,手动设定吗？

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#3153]
在./config/rec各种训练配置文件.yml中，学习率都设定一个固定的值 
 lr:
    learning_rate: 0.0005
或者
  lr:
    name: Cosine
    learning_rate: 0.005

是否可以通过在配置文件修改，使得比如训练总共400 epoch时,设定初始学习率Ir 0.01, 迭代到200 epoch时，学习率为0.001，迭代到300 epoch时，Ir为0.0005.这样的。该如何书写？

**Comment by WenmuZhou** [comment]
lr:
 name: Piecewise
 decay_epochs: [200,300]
 values: [0.01,0.001,0.0005]
