### ISSUE TITLE
ppocr对于单行文字的图片检测效果有问题

### ISSUE THREAD

**Issue by chros425** [PaddlePaddle/PaddleOCR#3157]
使用环境：python3.6.4，paddlepaddle-GPU==2.1.0，ppocr==2.1，cuda-10.1，检测和识别模型，都是 V2.0 server版，测试的数据如下，检测和识别结果都为空，经测试，发现是检测模型没有检测到文字，请问是哪里的问题，相关的det的参数也都调整尝试过，也不行
![5735976_hs1106](https://user-images.githubusercontent.com/25075794/122962207-c2773400-d3b7-11eb-86c1-bc753a198854.png)
![57096968_2876396349](https://user-images.githubusercontent.com/25075794/122962234-c73be800-d3b7-11eb-808e-acf34cc88627.jpg)
![57547562_3433214771](https://user-images.githubusercontent.com/25075794/122962245-c99e4200-d3b7-11eb-820a-4b958a074124.jpg)

**Comment by LDOUBLEV** [comment]
这种的就不需要用检测模型了，直接上识别模型吧
