### ISSUE TITLE
C++部署识别预测 和python 识别预测不一致

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/PaddleOCR#3158]
过程：
1. Cmake PaddleOCR生成部署DLL，C#调用DLL。 
2. PaddleOCR toos/train.py 训练检测模型、识别模型。
3. C# 调用检测模型、识别模型。
--------------------------------------------------
问题1：在做部署测试时，发现检测到的图像先经过旋转再去做识别？为什么会出现这种情况？
问题2： 识别模型训练完成后，预测图像识别率一般都是0.99996，预测数值也是对的。`但是`在部署时，识别率挺高，但是预测数值不对。
![image](https://user-images.githubusercontent.com/68001817/123029876-67bff580-d414-11eb-9697-925ceba9b159.png)

---------------------------------------------------------------
**同一张图片，同一张图片，部署检测识别和识别模型后预测结果咋不一样？？？？纳尼**

![image](https://user-images.githubusercontent.com/68001817/123057659-a5d01000-d43a-11eb-9c69-cb70e3ed06a0.png)

**Comment by LDOUBLEV** [comment]
> 问题1：在做部署测试时，发现检测到的图像先经过旋转再去做识别？为什么会出现这种情况？

检测到的框不是规则的矩形，可能有一定倾斜角度，在识别的时候会先矫正，矫正函数，[python](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/predict_system.py#L49)，[C++](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/deploy/cpp_infer/src/ocr_rec.cpp#L132)

> 问题2： 识别模型训练完成后，预测图像识别率一般都是0.99996，预测数值也是对的。但是在部署时，识别率挺高，但是预测数值不对。

参考[FAQ](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/FAQ.md#q3425-paddleocr%E6%A8%A1%E5%9E%8Bpython%E7%AB%AF%E9%A2%84%E6%B5%8B%E5%92%8Cc%E9%A2%84%E6%B5%8B%E7%BB%93%E6%9E%9C%E4%B8%8D%E4%B8%80%E8%87%B4)排查问题

**Comment by chccc5** [comment]
> > 问题1：在做部署测试时，发现检测到的图像先经过旋转再去做识别？为什么会出现这种情况？
> 
> 检测到的框不是规则的矩形，可能有一定倾斜角度，在识别的时候会先矫正，矫正函数，[python](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/predict_system.py#L49)，[C++](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/deploy/cpp_infer/src/ocr_rec.cpp#L132)
> 
> > 问题2： 识别模型训练完成后，预测图像识别率一般都是0.99996，预测数值也是对的。但是在部署时，识别率挺高，但是预测数值不对。
> 
> 参考[FAQ](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/FAQ.md#q3425-paddleocr%E6%A8%A1%E5%9E%8Bpython%E7%AB%AF%E9%A2%84%E6%B5%8B%E5%92%8Cc%E9%A2%84%E6%B5%8B%E7%BB%93%E6%9E%9C%E4%B8%8D%E4%B8%80%E8%87%B4)排查问题

和预测库版版本有关系吗？ 预测库版本用的是windows  cuda11.0_cudnn8_avx_mkl_trt7 预测库(2.1.0版本)  ，python 安装的paddlepaddle-gpu      2.1.0.post110

**Comment by chccc5** [comment]
> > 问题1：在做部署测试时，发现检测到的图像先经过旋转再去做识别？为什么会出现这种情况？
> 
> 检测到的框不是规则的矩形，可能有一定倾斜角度，在识别的时候会先矫正，矫正函数，[python](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/predict_system.py#L49)，[C++](https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/deploy/cpp_infer/src/ocr_rec.cpp#L132)
> 
> > 问题2： 识别模型训练完成后，预测图像识别率一般都是0.99996，预测数值也是对的。但是在部署时，识别率挺高，但是预测数值不对。
> 
> 参考[FAQ](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/FAQ.md#q3425-paddleocr%E6%A8%A1%E5%9E%8Bpython%E7%AB%AF%E9%A2%84%E6%B5%8B%E5%92%8Cc%E9%A2%84%E6%B5%8B%E7%BB%93%E6%9E%9C%E4%B8%8D%E4%B8%80%E8%87%B4)排查问题

换了STARNet也是同样的问题，python 推理和C++ 推理差别相当大。

**Comment by chccc5** [comment]
@LDOUBLEV ??
