### ISSUE TITLE
Tensor not initialized yet when Tensor

### ISSUE THREAD

**Issue by DaliaJaber** [PaddlePaddle/PaddleOCR#3160]
Hi, I get the below error when running multiple occurrences of paddleOCR. Do we need to initialize PaddleOCR for each text detection? Does it not support multiprocessing on Windows?

_File "/home/.conda/envs/ocr/lib/python3.6/site-packages/paddleocr/tools/infer/predict_rec.py", line 239, in __call__
    output = output_tensor.copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:202)_

**Comment by LDOUBLEV** [comment]
It is not necessary to initialize PaddleOCR detection module when using the recognizer module of PaddleOCR.

Can u provide your running command?

>  Does it not support multiprocessing on Windows?

Multi-process prediction is only tested on the linux environment.

https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/predict_system.py#L190

**Comment by DaliaJaber** [comment]
> It is not necessary to initialize PaddleOCR detection module when using the recognizer module of PaddleOCR.
> 
> Can u provide your running command?
> 
> > Does it not support multiprocessing on Windows?
> 
> Multi-process prediction is only tested on the linux environment. However, you can try it on Windows, and theoretically, it is worked on Windows as the ‘subprocess’ package is supported on Win.
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/b80396c47cfd41b705b941c8a1dfce37dd9e2bc9/tools/infer/predict_system.py#L190

**Comment by DaliaJaber** [comment]
@LDOUBLEV

**Comment by dncnbuck** [comment]
I'm also running into the issue mentioned above. When running the PaddleOCR wit threaded execution via celery workers using the same initiallized model instance I receive the error
```
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
[Hint: holder should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:202)_
```

I've tried initialising the input and output tensors for each invocation of `model.ocr(image_array)` but I still cannot remove this bug. 

Any suggestions would be most helpful
