### ISSUE TITLE
关于DB文本检测模型推理

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3168]
![image](https://user-images.githubusercontent.com/49063302/123076285-93aa9d80-d44b-11eb-920f-9f75943d8752.png)

我按照图上所示教程，下载模型并执行命令行，并未输出任何错误，但是所得到的输出是这样的

![det_res_img_10](https://user-images.githubusercontent.com/49063302/123076619-e84e1880-d44b-11eb-89ff-601f5b5f8071.jpg)

我不知道我哪里出现了问题

**Comment by LDOUBLEV** [comment]
提供信息，包括：
- 下载的模型？
- 使用的命令？

我用这个模型测试是可以的：https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_db_v2.0_train.tar

**Comment by Luffffffy** [comment]
https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_db_v2.0_train.tar

> 提供信息，包括：
> 
> * 下载的模型？
> * 使用的命令？
> 
> 我用这个模型测试是可以的：https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_db_v2.0_train.tar

按照官方提供的教程，我进行了如下操作：
1，下载预训练的模型从官方提供的网址：https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_db_v2.0_train.tar
2，将pretrained模型转换为官方定义的inference模型，从官方提供的命令行：
`python tools/export_model.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./det_r50_vd_db_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_db`
3，测试 DB文本检测模型推理，从官方提供的命令行：
`python tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_db/"`
4，得到inference_results目录下的结果图片：
![image](https://user-images.githubusercontent.com/49063302/123197466-1bd98300-d4de-11eb-8f91-68e65857bc35.png)

但是得到的结果和官方示例不一致，我很困惑我哪里出现了问题

**Comment by LDOUBLEV** [comment]
发现是dygraph分支 tools/infer/predict_det.py 保存可视化图像的代码被删掉了，参考这个PR修改下就可以了：https://github.com/PaddlePaddle/PaddleOCR/pull/3185

**Comment by LDOUBLEV** [comment]
执行命令
`python tools/infer_det.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./det_r50_vd_db_v2.0_train/best_accuracy  Global.infer_img=./doc/imgs_en/img_10.jpg `
是能得到结果的吧
