### ISSUE TITLE
Streamlit is not working with PaddleOCR , getting value error : signal only works in main thread

### ISSUE THREAD

**Issue by saitej123** [PaddlePaddle/PaddleOCR#3170]
File "c:\users\sai tej\anaconda3\lib\site-packages\paddleocr\ppocr\data\__init__.py", line 51, in <module>
    signal.signal(signal.SIGINT, term_mp)
File "c:\users\sai tej\anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

import paddleocr
from paddleocr import PaddleOCR, draw_ocr

without this import
it works fine

In jupyter notebook it works fine

want to build OCR app with Paddleocr and streamlit  if someone has tried this please do share the approach

**Comment by LDOUBLEV** [comment]
I guess the training feature is not necessary for PaddleOCR app. 
try delete  code blows:
https://github.com/PaddlePaddle/PaddleOCR/blob/b20716851f3d6edcaeab32fd37b6831759d08f8d/ppocr/data/__init__.py#L51
```
signal.signal(signal.SIGINT, term_mp)
signal.signal(signal.SIGTERM, term_mp)
```

**Comment by saitej123** [comment]
Ok, thanks

For hosting in heroku or any other platform how requirements picked from pypi , how to customize this?

**Comment by saitej123** [comment]
In Streamlit , image path cant be defined, for paddle ocr we have to give an image path instead of direct 

Anyone could share code how to use streamlit with paddleocr
