### ISSUE TITLE
CTC文本识别模型是否可以使用beam search以及语言模型辅助解码?

### ISSUE THREAD

**Issue by hellomotor** [PaddlePaddle/PaddleOCR#3171]
类似于语音识别解码，beam search以及语言模型对提高准确率应该会有帮助，期待实现!

**Comment by hellomotor** [comment]
自己尝试了一下，发现效果还可以，能够纠正一些常见的识别错误

**Comment by Nickeilf** [comment]
@hellomotor 您好，请问纠正了常见识别错误是因为加了beam seach还是用了语言模型(使用的N-Gram还是Nerual LM)？

**Comment by hellomotor** [comment]
Beam Search和N-Gram

**Comment by NNNNAI** [comment]
兄弟，你用的是那个库来实现beam search和N-Gram呀，我最近也发现ocr的识别效果很差，想要优化一下

**Comment by hellomotor** [comment]
@NNNNAI,  我用的这个
[https://github.com/parlance/ctcdecode]

**Comment by Dhao007** [comment]
@hellomotor 您好，请问咋实现的
