### ISSUE TITLE
Not able to add "hi" while making PaddleOCR Object 

### ISSUE THREAD

**Issue by MANISH007700** [PaddlePaddle/PaddleOCR#3172]
Hello, 
After installing and importing `paddlepaddle-gpu` and `paddleocr==2.6.0` 
When I tried the quickstart method of creating an object using 
`ocr = PaddleOCR(lang="hi")` 
Error is : _ param lang must in dict_keys(['ch', 'en', 'french', 'german', 'korean', 'japan']), but got hi_ 

My Task is in Hindi, so is there any workaround for this. 
I used "en", it worked but ans were not proper. 
I need to use "hindi"

Any Help will be appreciated
Thanks PaddleTeam and Contributors

**Comment by tink2123** [comment]
Hi,

Thanks for your using. The paddleocr version must be 2.0.6. Look at your error, it seems that the old version of paddleocr is installed, you can try to uninstall and reinstall.

Looking forward to your reply.

Thanks

**Comment by MANISH007700** [comment]
I am sorry. It is paddleocr == 2.0.6 
Still, I am getting the same error as  " param lang must in dict_keys(['ch', 'en', 'french', 'german', 'korean', 'japan']), but got hi " 

Don't you guys have hindi as a language for PaddleOCR ? 
Please help, and thanks for the quick response

**Comment by tink2123** [comment]
Maybe you could try to build and install paddleocr locally:

```
git clone https://github.com/PaddlePaddle/PaddleOCR.git
cd PaddleOCR
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x is the version number of paddleocr
```
