### ISSUE TITLE
PPOCRLabel有很多要改进的地方，一点都不好用

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#3173]
1.标注一个图片后，用鼠标点击下一张，上一张标注没了，而且也不提示
2.标注一部分图片后，关闭窗口重新打开什么也没了
3.Eidt Label按下快捷键一点反应也没有
4.保存还得手动Ctrl+S，自动保存就是个摆设
5.更多BUG数不清
建议每个图片单独保存一个标签，类似labelImg，如果训练的话自己弄个合并代码又不难
总之这个我用了一会标注了一会，结果白干了，真想来一句fuc*****

**Comment by Evezerest** [comment]
由于PPOCRLabel中每张图片上的标注源自机器和人工两个渠道，所以在和普通标注工具的使用上有比较大的区别，建议使用前详细阅读 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/PPOCRLabel/README_ch.md，里面有详细的关于保存、快捷键方面的解释。

版本以release2.1为准，其他分支上的代码没有更新。

反馈bug，请提供系统、环境、版本、操作步骤等信息以方便复现。不同系统或环境遇到的问题可能不同，已发布的功能经过mac和win平台测试。

PPOCRLabel作为社区共建的自动标注工具，有许多功能需要完善，希望有志之士能够投入到开源建设中。
