### ISSUE TITLE
关于识别模型的类别不平衡问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3174]
假设识别模型的字典为1-9，在1-8中的文字出现有1000次，而9只出现10次，这样的话训练出来模型会影响识别9么？或者是说我无脑增加训练的迭代次数或者是epoch，这样不就相当于变相增加了9的数目，这样能缓解这个问题么？

**Comment by tink2123** [comment]
尽量保证类别均衡，实验证明训练集中出现频次较少的字符，识别效果会很差， 增加迭代次数不能改变频率低的问题。
