### ISSUE TITLE
ocr 提供的dockerfile 和镜像中的版本问题

### ISSUE THREAD

**Issue by linxi-1214** [PaddlePaddle/PaddleOCR#3175]
1. docker file里expose 端口是8868，但实际容器里启动的是8866端口
2. gpu的部署镜像里，paddlepaddle-gpu. 版本是2.0.0，这个版本会报错“NoModuleFound, paddle.utils.cpp_extension"
升级到2.1.0  后解决，希望可以升级基础镜像里的版本

**Comment by LDOUBLEV** [comment]
感谢反馈

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/3216
端口号和hubserving里的端口号保持一致，paddle版本问题在上述PR中更新了
