### ISSUE TITLE
PaddleOCR  github上在PC端的在线体验超轻量模型和开源的模型一致吗

### ISSUE THREAD

**Issue by chenyuqiang234** [PaddlePaddle/PaddleOCR#3176]
在PC端在线体验上面，同一张图片识别效果很好，自己下载的模型，按照使用教程，测试的效果不好，什么原因，是使用的相同模型吗？
PC端在线体验：https://www.paddlepaddle.org.cn/hub/scene/ocr

**Comment by tink2123** [comment]
是一样的模型，部分后处理参数不同，可以贴一下测试效果不好的图片吗？

**Comment by chenyuqiang234** [comment]
> 是一样的模型，部分后处理参数不同，可以贴一下测试效果不好的图片吗？
 @![result](https://user-images.githubusercontent.com/53166988/123219530-94047080-d4ff-11eb-8089-484ad19b568a.jpg)
![yhk](https://user-images.githubusercontent.com/53166988/123219535-95359d80-d4ff-11eb-8eb7-3662b1cd5bd1.jpg)
![代码](https://user-images.githubusercontent.com/53166988/123219580-a2528c80-d4ff-11eb-94f8-bda9377ef75c.png)

@tink2123

**Comment by chenyuqiang234** [comment]
这是识别结果，看到FAQ中的调优，我也试过，感觉也不行，但是在线体验的识别的挺好，所以问一下。
![调优](https://user-images.githubusercontent.com/53166988/123220090-31f83b00-d500-11eb-95b2-3f6a5b8e6fed.png)

**Comment by tink2123** [comment]
可以试一下 PaddleOCR/release1.8 分支的代码，看看静态图模型效果能不能满足需求，online上的模型版本可能比较久。
