### ISSUE TITLE
预训练模型 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_pre.tar解压后没有.pdmodel文件

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleOCR#3177]
预训练模型 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_pre.tar解压后没有.pdmodel文件，只有：best_accuracy.pdopt   best_accuracy.pdparams  
  best_accuracy.states train.log  
但是! python3 tools/infer/predict_system.py --image_dir="../2张样例图片/WechatIMG192.png" \
    --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer"  \
    --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_pre"  \
    --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer" --use_angle_cls=True --use_space_char=True --use_gpu=False
需要用到.pdmodel文件

**Comment by Fly-hub** [comment]
我看错了，之前下载的是预训练模型文件，不是推理模型文件。。。

**Comment by tink2123** [comment]
是的，要下载推理模型
