### ISSUE TITLE
弯曲文字的检测与识别

### ISSUE THREAD

**Issue by wkw1542673895** [PaddlePaddle/PaddleOCR#318]
检测除了db还可以用什么，是否会开源，识别用啥模型

**Comment by MissPenguin** [comment]
DB原理上可支持弯曲文本检测，但这部分逻辑未完整训练和调试，计划晚些时候补全。此外，近期还会开源百度自研文本检测算法SAST（https://arxiv.org/abs/1908.05498），该算法也支持弯曲文本检测。

弯曲文本的识别，可以用带tps矫正模块的rare算法，但本项目尚未在弯曲数据集上验证。

**Comment by bigvine2** [comment]
期待百度开源SAST
