### ISSUE TITLE
关于文字检测的预训练模型

### ISSUE THREAD

**Issue by Lufffya** [PaddlePaddle/PaddleOCR#3180]
在我想用自己的数据集去finetune文字检测预训练模型的时候，遇到了关于如何下载预训练模型的疑问？
根据我的理解，要在自定义的数据集上finetune需要下载pretrained模型，最后在OCR Pipeline的时候，需要将finetune后的模型转换为inference模型才能进行推理。
在看过文档之后，我发现了下面几处都可以下载预训练模型（以文字检测模型为例）：

1， https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/README_ch.md#pp-ocr-20%E7%B3%BB%E5%88%97%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8%E6%9B%B4%E6%96%B0%E4%B8%AD
![image](https://user-images.githubusercontent.com/49063302/123215318-e42d0400-d4fa-11eb-9138-e45435ac3cd3.png)
模型链接：https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_train.tar

2，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md#%E4%B8%80%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B
![image](https://user-images.githubusercontent.com/49063302/123215683-556cb700-d4fb-11eb-851c-ddb23f9287cd.png)

3，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/algorithm_overview.md#1%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E7%AE%97%E6%B3%95
![image](https://user-images.githubusercontent.com/49063302/123216022-af6d7c80-d4fb-11eb-874f-046c7d6bc393.png)

4，https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md#resnet%E5%8F%8A%E5%85%B6vd%E7%B3%BB%E5%88%97
![image](https://user-images.githubusercontent.com/49063302/123216181-d62bb300-d4fb-11eb-8932-1dd117db8a73.png)

于是我混乱了！！！不知道下载哪一个，而且也只有图2才列出了对应的yml配置文件，如何才能正确的知道下载某个正确的预训练模型以及与之对应的yml配置文件呢？
回复感激不尽，谢谢大佬们！！！

**Comment by tink2123** [comment]
图一的移动端和通用模型，分别对应图二的mobile和server，关注图2就可以。
图三中的模型看配置文件的名称就可以找到对应关系：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/configs/det， 例如 det_r50_vd_east.yml 对应的就是EAST算法，backbone为resnet50_vd
图四是PaddleClas里的模型参数，相应的配置文件也在configs里可以找到: https://github.com/PaddlePaddle/PaddleClas/tree/release/2.2/ppcls/configs/ImageNet

**Comment by Luffffffy** [comment]
> 图一的移动端和通用模型，分别对应图二的mobile和server，关注图2就可以。
> 图三中的模型看配置文件的名称就可以找到对应关系：[https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/configs/det，](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/configs/det%EF%BC%8C) 例如 det_r50_vd_east.yml 对应的就是EAST算法，backbone为resnet50_vd
> 图四是PaddleClas里的模型参数，相应的配置文件也在configs里可以找到: https://github.com/PaddlePaddle/PaddleClas/tree/release/2.2/ppcls/configs/ImageNet


哦哦，明白了，谢谢解惑
还有一点想问下，
PaddleClas 里面的模型也可以适用于PaddleOCR里面的文字检测模型的finetune吗？
按我的理解是可以的，因为从官方的教程来看，也指向了这个PaddleClas这个地址
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/detection.md#%E5%BF%AB%E9%80%9F%E5%90%AF%E5%8A%A8%E8%AE%AD%E7%BB%83
![image](https://user-images.githubusercontent.com/49063302/123410189-9b9c4600-d5e1-11eb-92d9-d6a33702e0ea.png)

但是我观察了PaddleClas模型对面的配置文件，从这个路径
https://github.com/PaddlePaddle/PaddleClas/tree/release/2.2/ppcls/configs/ImageNet
发现配置文件后缀名为 .yaml ，和PaddleOCR里面的模型finetune配置文件后缀名为.yml 的有出入，所以有点疑惑
再次感谢回复！！！
