### ISSUE TITLE
能否公开英文识别模型的数据集

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#3183]
面对的场景是英文数字流水号，但是使用en_number_mobile_v2.0_rec识别时，仍然有个别错误，比如v识别成y等，u识别成A等。

1.想finetune时，将自己的数据集（5w张左右）和预训练时官方的数据集一起训练，能否提供英文识别训练的数据集吗？

2.英文识别数据集多少数据量为好，和自己的数据集一起训练，既可以保持原始的en_number_mobile_v2.0_rec的识别效果，又可以解决一些小的识别错误？

3.英文识别模型有服务级别server的吗？

**Comment by tink2123** [comment]
官方的训练数据量比较大，且大部分都是合成数据，有需要可以自行合成，暂时没有办法提供。
如果数据量少的话，finetune的时候epoch数不要太大，有针对性的添加数据解决识别错误的问题就可以，5w左右数据应该够用。
英文识别模型暂时没有server模型，可以自己训练，识别效果会有提升

**Comment by Liudyan** [comment]
英文文本检测模型是和中英文文本检测模型是一致的，英文检测模型有预训练模型吗？我采用.paddleocr里面的det/en推理模型(应该是ppOCRLabel默认下载的），
发现识别精度比中英文文本检测模型精度要高，后续crnn识别也更好.

**Comment by tink2123** [comment]
英文的检测和识别都是单独在英文场景上训练的模型，和中英文模型不同。预训练模型：https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_ppocr_mobile_V2.0_det_train.tar
