### ISSUE TITLE
使用MKL-DNN加速推理时只能跑一次（CPU）

### ISSUE THREAD

**Issue by C4a15Wh** [PaddlePaddle/PaddleOCR#3186]
我们封装了一个server并且把调用写在了接口函数内，并且服务成功地跑起来了
但当我们使用MKL-DNN加速推理（enable_mkldnn=True）的时候，只有第一次才能成功调用，后续的请求都不会成功。
服务端日志：
https://paste.ubuntu.com/p/NsrkK3zBn8/
部分代码：
![@9UCZ W$RZ%P{LUA@R%H}9O](https://user-images.githubusercontent.com/61458603/123297438-27629380-d54a-11eb-8eca-8fba269f266f.png)
问题部分：
japanOcr = PaddleOCR(use_angle_cls=True, use_gpu=False, lang="japan", enable_mkldnn=True)
【此处当去掉enable_mkldnn=True时，就可以多次请求不会报错】

**Comment by grasswolfs** [comment]
能提供一下请求报错的截图么？

**Comment by GT-ZhangAcer** [comment]
> 能提供一下请求报错的截图么？

https://paste.ubuntu.com/p/NsrkK3zBn8/
这个是服务端的日志，可以在这里看到完整的报错信息哈

**Comment by C4a15Wh** [comment]
> 能提供一下请求报错的截图么？

![image](https://user-images.githubusercontent.com/61458603/123435687-68b57a80-d600-11eb-9e92-ba69f85469df.png)

**Comment by GT-ZhangAcer** [comment]
补充我在本地复现的细节，在运行两次时同样出现该情况  

Python环境如下
>  Python3.7-3.9均不通过
> flask==2.0.1
> paddlepaddle==2.1
> paddleocr==1.1.1/2.0.6均不通过

```
from flask import Flask
from paddleocr import PaddleOCR, draw_ocr

app = Flask(__name__)

ocr_japan = PaddleOCR(use_angle_cls=True, use_gpu=False, lang="japan")
ocr_en = PaddleOCR(use_angle_cls=True, use_gpu=False, lang="en")
ocr_korean = PaddleOCR(use_angle_cls=True, use_gpu=False, lang="korean")
ocr_chinese = PaddleOCR(use_angle_cls=True, use_gpu=False, lang="ch", enable_mkldnn=True)

@app.route('/')
def hello_world():
    result = ocr_chinese.ocr("./image.jpg", cls=True)
    print(result)
    return "1"


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)

```
![图片](https://user-images.githubusercontent.com/46156734/123658471-55a2e480-d864-11eb-989f-57d6241b7bfb.png)

**Comment by LDOUBLEV** [comment]
测试发现paddle2.1版本上存在这个问题，paddle2.0版本上可以正常预测
```
python3
paddlepaddle==2.0 or paddlepaddle==2.0.1
paddleocr==2.0.6
```
