### ISSUE TITLE
Issue while parsing the data

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/PaddleOCR#3189]
ERROR: When parsing line /content/PaddleOCR/reallife_cgi_1212993569-1.tif B0000005070B
, error happened with msg: list index out of range

**Comment by MissPenguin** [comment]
Maybe the data format is not right. Check if the delimiter is '\t'.

**Comment by ZhangXinNan** [comment]
我也遇到了同样的问题，可能后边的标注非常的长。

**Comment by yong-asial** [comment]
@dang-nh194423 i'm facing the same problem. how did you solve it?
