### ISSUE TITLE
文本长度超过25，应该怎么处理

### ISSUE THREAD

**Issue by wkw1542673895** [PaddlePaddle/PaddleOCR#319]
超过25的部分识别不准了

**Comment by littletomatodonkey** [comment]
训练的时候没有考虑超过25的文本长度，如果图片长宽比太大，可以考虑将图片裁剪为两部分，分别识别，或者在训练的时候，设置更大的最长文本长度。

**Comment by wkw1542673895** [comment]
> 训练的时候没有考虑超过25的文本长度，如果图片长宽比太大，可以考虑将图片裁剪为两部分，分别识别，或者在训练的时候，设置更大的最长文本长度。

请问可以修改哪个参数

**Comment by littletomatodonkey** [comment]
以下面这个配置文件为例，可以修改`max_text_length `这个参数哈

https://github.com/PaddlePaddle/PaddleOCR/blob/4a035c05987a76344dc09279cb122d26cc213e54/configs/rec/rec_chinese_lite_train.yml#L13
