### ISSUE TITLE
两个系统相同环境相同hub和模型版本针对同一图片结果却有不同

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#3193]
[paddle]# hub version
2.1.0
同一张图片，两个环境一样都是centOS8，hub版本一样 模型都是最新的
结果不完全相同是受哪方面的影响呢
硬件一个有GPU 一个没有

**Comment by MissPenguin** [comment]
可以具体描述一下复现步骤吗，以及具体的diff情况
