### ISSUE TITLE
Load model

### ISSUE THREAD

**Issue by Adriel-Cabral** [PaddlePaddle/PaddleOCR#3198]
how can i load a trained model with my own dataset with the script ?

**Comment by MissPenguin** [comment]
Set your own model path to the parameter "pretrained_model" in the configuration file. such as : https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml#L11
