### ISSUE TITLE
训练 det_mv3_db 模型时内存泄漏oom

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleOCR#3199]
环境信息：
paddlepaddle/paddle:2.1.1-gpu-cuda11.2-cudnn8  docker镜像
gpu 3090
PaddleOCRv2.1.1 release 代码

yml配置文件：
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 16
    num_workers: 4

现象：
 
![image](https://user-images.githubusercontent.com/18511799/123437655-7ec43a80-d602-11eb-8b13-e9889dc730a0.png)
每次dataloader重新读都会增加使用内存，然后oom
试过num_workers设为0，降低bs，都没用。

**Comment by jackiezzq** [comment]
每个epoch的iters只有两三个的时候，内存泄漏的就很快，增大数据集之后内存占用就保持稳定了，不知道是啥问题

**Comment by MissPenguin** [comment]
> 每个epoch的iters只有两三个的时候，内存泄漏的就很快，增大数据集之后内存占用就保持稳定了，不知道是啥问题

该问题由dataloader引起，已在Paddle 2.1.2版本修复，可以更新Paddle版本验证下。
