### ISSUE TITLE
竖排文字的处理

### ISSUE THREAD

**Issue by heromanba** [PaddlePaddle/PaddleOCR#32]
您好，感谢您分享这么好的工作。想请教一下，因为CRNN这种只能处理水平的文字，PaddleOCR是如何处理竖排文字的呢？多谢！

**Comment by LDOUBLEV** [comment]
训练时：生成一些竖排文字样本加入训练
预测时：根据检测框的长宽比粗判断横排竖排，如果：box中 h >> w，判断为竖排，把竖排文字转成横着的去识别

**Comment by heromanba** [comment]
多谢您的回复，再请问下，这个在代码里哪个地方有体现呢？我试着找了下，没找到。。

**Comment by LDOUBLEV** [comment]
> 多谢您的回复，再请问下，这个在代码里哪个地方有体现呢？我试着找了下，没找到。。

inference时： https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/predict_system.py#L55

**Comment by heromanba** [comment]
十分感谢！

**Comment by Lebron-Harden** [comment]
> 训练时：生成一些竖排文字样本加入训练
> 预测时：根据检测框的长宽比粗判断横排竖排，如果：box中 h >> w，判断为竖排，把竖排文字转成横着的去识别

您好，请问训练时竖排文字样本时，图片需要预先旋转成横着的吗？
