### ISSUE TITLE
C++  paddleOCR tensorrt推理报错

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/PaddleOCR#3201]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [x] shape of trt subgraph is [-1,3,32,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/data-code/Paddle/paddle/fluid/inference/tensorrt/engine.h:103)

**Comment by LDOUBLEV** [comment]
设置动态shape参考dygraph分支的代码,release/2.1分支还未支持 ：https://github.com/PaddlePaddle/PaddleOCR/blob/52651b33bf9451f5c22e5feb1390d6fbd3dbf131/deploy/cpp_infer/src/ocr_rec.cpp#L116
