### ISSUE TITLE
关于Pretrained模型finetune后转inference模型，前后效果不一致问题

### ISSUE THREAD

**Issue by Lufffya** [PaddlePaddle/PaddleOCR#3204]
如图：
1
![image](https://user-images.githubusercontent.com/49063302/123592178-75fc8000-d81f-11eb-84f4-cefc02e30ab8.png)
2
![image](https://user-images.githubusercontent.com/49063302/123592186-785eda00-d81f-11eb-9d51-65f7601b684d.png)

请问一下大佬们，图1是自定义数据集finetune后评估测试的结果，图2是同样的模型转成inference格式模型测试后的结果，顶部出现了漏识而且底部出现了错误，请问这是什么原因，有相应的参数可以调整吗，感谢回复，谢谢！！！

**Comment by MissPenguin** [comment]
估计是预处理没对齐，看一下两种预测的输入resize是否一致

**Comment by Luffffffy** [comment]
> 估计是预处理没对齐，看一下两种预测的输入resize是否一致

我评估和转inference的时候用的是同一个yml，参数没有任何的不同，而且也都是同一张图片
我发现其他的issues有很多同类似的问题，但是都没有得到解决
