### ISSUE TITLE
StyleText 按照最新版本的教程生成的 4 张图,文字与标签不对应

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#3206]
label.txt 文件内容:
0/0.png	飞桨文字识别
0/1.png	Paddle
0/2.png	Paddle
0/3.png	飞桨文字识别

0/0.png 图片为“飞浆文飞浆文”
![image](https://user-images.githubusercontent.com/18033495/123606272-968df100-d7b1-11eb-9db9-72ffafed13f8.png)

**Comment by weisy11** [comment]
这个bug还挺奇怪的，感觉是拼接错误，我检查一下

**Comment by ddz-mark** [comment]
我目前是了paddlepaddle 2.0.0 和 2.1.0 的版本，然后换了台电脑重新配置环境，同样出现上述问题，完全按照教程走的。

**Comment by weisy11** [comment]
是的，这个确实是一个bug，修复PR：https://github.com/PaddlePaddle/PaddleOCR/pull/3236

**Comment by ddz-mark** [comment]
好的，谢谢
