### ISSUE TITLE
C++ 部署tensorrt如何设置SetTRTDynamicShapeInfo

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/PaddleOCR#3209]
当我根据引导手册中的方法推理时,报如下错误:
InvalidArgumentError: The input [x] shape of trt subgraph is [-1,3,32,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/data-code/Paddle/paddle/fluid/inference/tensorrt/engine.h:103)

我设置完动态尺寸后仍然报错如下错误
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v2.0_rec_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db/
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn/
use_angle_cls : 0
use_fp16 : 0
use_gpu : 1
use_mkldnn : 0
use_polygon_score : 1
use_tensorrt : 1
visualize : 1
=======End of Paddle OCR inference config======
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0628 23:48:42.680503  8416 analysis_config.cc:424] use_dlnne_:0
I0628 23:48:42.680562  8416 analysis_config.cc:424] use_dlnne_:0
I0628 23:48:42.680593  8416 analysis_config.cc:424] use_dlnne_:0
I0628 23:48:42.680631  8416 analysis_config.cc:424] use_dlnne_:0
I0628 23:48:42.680658  8416 analysis_config.cc:424] use_dlnne_:0

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /home/data-code/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:248)

请问应该如何设置

**Comment by LDOUBLEV** [comment]
参考dygraph分支的代码 ：https://github.com/PaddlePaddle/PaddleOCR/blob/52651b33bf9451f5c22e5feb1390d6fbd3dbf131/deploy/cpp_infer/src/ocr_rec.cpp#L116

**Comment by yuctian** [comment]
> 参考dygraph分支的代码 ：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/52651b33bf9451f5c22e5feb1390d6fbd3dbf131/deploy/cpp_infer/src/ocr_rec.cpp#L116

我参考这个改了还是报错,切换到dygraph分支还是有同样的问题,这是跟paddle版本有关系吗?
我的paddle是release/2.1
报错如下:
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/ppocr_keys_v1.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db/
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./inference/rec_crnn/
use_angle_cls : 0
use_fp16 : 0
use_gpu : 1
use_mkldnn : 0
use_polygon_score : 1
use_tensorrt : 1
visualize : 0
=======End of Paddle OCR inference config======
dir_name is not a valid directory !
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0629 11:16:56.056355 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:16:56.056392 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:16:56.056416 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:16:56.056514 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:16:56.538965 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:16:56.538992 13407 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
I0629 11:16:56.547528 13407 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0629 11:16:56.653584 13407 graph_pattern_detector.cc:91] ---  detected 33 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0629 11:16:56.661387 13407 graph_pattern_detector.cc:91] ---  detected 33 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0629 11:16:56.674762 13407 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 108 nodes
I0629 11:16:56.683348 13407 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
input:x
all_dynamic_shape_set:1
I0629 11:16:56.818689 13407 engine.cc:202] Run Paddle-TRT Dynamic Shape mode.
I0629 11:17:08.025976 13407 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 13 nodes
I0629 11:17:08.029527 13407 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
input:conv2d_92.tmp_0
input:nearest_interp_v2_2.tmp_0
input:nearest_interp_v2_3.tmp_0
input:nearest_interp_v2_4.tmp_0
input:nearest_interp_v2_5.tmp_0
all_dynamic_shape_set:1
I0629 11:17:08.030930 13407 engine.cc:202] Run Paddle-TRT Dynamic Shape mode.
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0629 11:17:08.438665 13407 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0629 11:17:08.443816 13407 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_0.tmp_0  size: 384
I0629 11:17:08.443825 13407 memory_optimize_pass.cc:199] Cluster name : tmp_0  size: 384
I0629 11:17:08.443828 13407 memory_optimize_pass.cc:199] Cluster name : conv2d_90.tmp_0  size: 384
--- Running analysis [ir_graph_to_program_pass]
I0629 11:17:08.473294 13407 analysis_predictor.cc:636] ======= optimize end =======
I0629 11:17:08.475258 13407 naive_executor.cc:98] ---  skip [feed], feed -> x
I0629 11:17:08.475611 13407 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I0629 11:17:08.476091 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:17:08.476102 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:17:08.476111 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:17:08.476123 13407 analysis_config.cc:424] use_dlnne_:0
I0629 11:17:08.476130 13407 analysis_config.cc:424] use_dlnne_:0
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /home/data-code/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:248)

tools/run.sh: 行 1: 13407 已放弃               (核心已转储) ./build/ocr_system ./tools/config.txt /home/erin/图片/屏幕截图.png

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/123743666-25009080-d8e0-11eb-8228-4fcfd03e46e0.png)

检测模型的dynamic  shape也改一下https://github.com/PaddlePaddle/PaddleOCR/blob/52651b33bf9451f5c22e5feb1390d6fbd3dbf131/deploy/cpp_infer/src/ocr_det.cpp#L67

**Comment by yuctian** [comment]
> ![image](https://user-images.githubusercontent.com/26592129/123743666-25009080-d8e0-11eb-8228-4fcfd03e46e0.png)
> 
> 检测模型的dynamic shape也改一下
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/52651b33bf9451f5c22e5feb1390d6fbd3dbf131/deploy/cpp_infer/src/ocr_det.cpp#L67

检测是没有问题的,我在出问题的地方打印看了看,结果是这样的
input:conv2d_92.tmp_0
input:nearest_interp_v2_2.tmp_0
input:nearest_interp_v2_3.tmp_0
input:nearest_interp_v2_4.tmp_0
input:nearest_interp_v2_5.tmp_0
all_dynamic_shape_set:1
input:x
all_dynamic_shape_set:1
input:lstm_0.tmp_0
ranks:0
all_dynamic_shape_set:0
也就是在识别的时候,dynamicShape不仅需要设置X,还需要设置lstm_0.tmp_0等参数,不清楚怎么设置

**Comment by LDOUBLEV** [comment]
> 也就是在识别的时候,dynamicShape不仅需要设置X,还需要设置lstm_0.tmp_0等参数,不清楚怎么设置

提示哪个参数没有设置动态shape，就加在min/max/opt_input_shape里，对比下检测和识别的动态shape设置，你就知道怎么加了。

比如
```
      std::map<std::string, std::vector<int>> min_input_shape = {
          {"x", {1, 3, 32, 10}}, {"lstm_0.tmp_0", {*, *}}};
      std::map<std::string, std::vector<int>> max_input_shape = {
          {"x", {1, 3, 32, 2000}}, {"lstm_0.tmp_0", {*, *}}};
      std::map<std::string, std::vector<int>> opt_input_shape = {
          {"x", {1, 3, 32, 320}}, {"lstm_0.tmp_0", {*, *}}};
```
* 换成shape的值

**Comment by yuctian** [comment]
> > 也就是在识别的时候,dynamicShape不仅需要设置X,还需要设置lstm_0.tmp_0等参数,不清楚怎么设置
> 
> 提示哪个参数没有设置动态shape，就加在min/max/opt_input_shape里，对比下检测和识别的动态shape设置，你就知道怎么加了。
> 
> 比如
> 
> ```
>       std::map<std::string, std::vector<int>> min_input_shape = {
>           {"x", {1, 3, 32, 10}}, {"lstm_0.tmp_0", {*, *}}};
>       std::map<std::string, std::vector<int>> max_input_shape = {
>           {"x", {1, 3, 32, 2000}}, {"lstm_0.tmp_0", {*, *}}};
>       std::map<std::string, std::vector<int>> opt_input_shape = {
>           {"x", {1, 3, 32, 320}}, {"lstm_0.tmp_0", {*, *}}};
> ```
> 
> * 换成shape的值
> 
> 你预测库下载的哪个版本，TRT哪个版本的

我的TRT是7.2.3

**Comment by yuctian** [comment]
> > > 也就是在识别的时候,dynamicShape不仅需要设置X,还需要设置lstm_0.tmp_0等参数,不清楚怎么设置
> > 
> > 
> > 提示哪个参数没有设置动态shape，就加在min/max/opt_input_shape里，对比下检测和识别的动态shape设置，你就知道怎么加了。
> > 比如
> > ```
> >       std::map<std::string, std::vector<int>> min_input_shape = {
> >           {"x", {1, 3, 32, 10}}, {"lstm_0.tmp_0", {*, *}}};
> >       std::map<std::string, std::vector<int>> max_input_shape = {
> >           {"x", {1, 3, 32, 2000}}, {"lstm_0.tmp_0", {*, *}}};
> >       std::map<std::string, std::vector<int>> opt_input_shape = {
> >           {"x", {1, 3, 32, 320}}, {"lstm_0.tmp_0", {*, *}}};
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 换成shape的值
> > 
> > 你预测库下载的哪个版本，TRT哪个版本的
> 
> 我的TRT是7.2.3

我试过自己加,但是加完之后permute操作报错

**Comment by LDOUBLEV** [comment]
> 我试过自己加,但是加完之后permute操作报错

报错信息贴一下？

**Comment by yuctian** [comment]
> > 我试过自己加,但是加完之后permute操作报错
> 
> 报错信息贴一下？
=======Paddle OCR inference config======
char_list_file : ../../ppocr/utils/number_dict.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v2.0_rec_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/det_db/
gpu_id : 0
gpu_mem : 100
max_side_len : 960
rec_model_dir : ./inference/rec/
use_angle_cls : 0
use_fp16 : 0
use_gpu : 1
use_mkldnn : 0
use_polygon_score : 1
use_tensorrt : 1
visualize : 1
=======End of Paddle OCR inference config======
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0701 10:55:03.762472 28371 analysis_config.cc:424] use_dlnne_:0
I0701 10:55:03.762507 28371 analysis_config.cc:424] use_dlnne_:0
I0701 10:55:03.762533 28371 analysis_config.cc:424] use_dlnne_:0
I0701 10:55:03.762629 28371 analysis_config.cc:424] use_dlnne_:0
I0701 10:55:03.762646 28371 analysis_config.cc:424] use_dlnne_:0
input:x
all_dynamic_shape_set:1
input:conv2d_92.tmp_0
input:nearest_interp_v2_2.tmp_0
input:nearest_interp_v2_3.tmp_0
input:nearest_interp_v2_4.tmp_0
input:nearest_interp_v2_5.tmp_0
all_dynamic_shape_set:1
input:x
all_dynamic_shape_set:1
input:lstm_0.tmp_0
all_dynamic_shape_set:1
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::inference::tensorrt::OpConverter::ConvertOp(paddle::framework::proto::OpDesc const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*, bool)
14  paddle::inference::tensorrt::TransposeOpConverter::operator()(paddle::framework::proto::OpDesc const&, paddle::framework::Scope const&, bool)
15  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
16  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Invalid permutation dimensions for trt transpose op converter: duplicate or out of bound.
  [Hint: Expected is_valid_permutation(dims, perm) == true, but received is_valid_permutation(dims, perm):0 != true:1.] (at /home/data-code/Paddle/paddle/fluid/inference/tensorrt/convert/transpose_op.cc:70)

tools/run.sh: 行 1: 28371 已放弃               (核心已转储) ./build/ocr_system ./tools/config.txt /home/erin/桌面/nums_/gen_pics

**Comment by JiaoPaner** [comment]
@yuctian rec.cpp问题咋解决的
