### ISSUE TITLE
使用develop分支，使用部署网页上的paddlelite2.7版本对应模型，手机侧联调时报错，是什么问题呢？谢谢

### ISSUE THREAD

**Issue by wangwh0128** [PaddlePaddle/PaddleOCR#3212]
[W  6/29 16:48: 6.652 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:124 CreateKernels] op pool2d get 1 kernels
[W  6/29 16:48: 6.652 ...ite/lite/model_parser/base/vector_view.h:84 operator std::__ndk1::vector<T>] Copying elements out of VectorView will damage performance.
[W  6/29 16:48: 6.652 ...ite/lite/model_parser/base/vector_view.h:84 operator std::__ndk1::vector<T>] Copying elements out of VectorView will damage performance.
[W  6/29 16:48: 6.652 ...ite/lite/model_parser/base/vector_view.h:84 operator std::__ndk1::vector<T>] Copying elements out of VectorView will damage performance.
[W  6/29 16:48: 6.652 ...le-Lite/Paddle-Lite/lite/core/program.cc:206 RuntimeProgram] Found the attr '__@kernel_type_attr@__': pool2d/def/4/1/1 for pool2d
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for pool2d arm/float/NCHW get 1 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for pool2d arm/float/any get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for pool2d arm/any/NCHW get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for pool2d arm/any/any get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:124 CreateKernels] op pool2d get 1 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/program.cc:206 RuntimeProgram] Found the attr '__@kernel_type_attr@__': fc/def/4/1/1 for fc
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for fc arm/float/NCHW get 1 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for fc arm/float/any get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for fc arm/any/NCHW get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for fc arm/any/any get 0 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:124 CreateKernels] op fc get 1 kernels
[W  6/29 16:48: 6.653 ...le-Lite/Paddle-Lite/lite/core/program.cc:206 RuntimeProgram] Found the attr '__@kernel_type_attr@__': arg_max/def/4/1/1 for arg_max
[W  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for arg_max arm/float/NCHW get 0 kernels
[W  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for arg_max arm/float/any get 0 kernels
[W  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for arg_max arm/any/NCHW get 5 kernels
[W  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:90 operator()] pick kernel for arg_max arm/any/any get 0 kernels
[W  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/op_lite.cc:124 CreateKernels] op arg_max get 5 kernels
[F  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():
[F  6/29 16:48: 6.654 ...le-Lite/Paddle-Lite/lite/core/program.cc:214 RuntimeProgram] Check failed: it != kernels.end():

**Comment by LDOUBLEV** [comment]
预测库版本也是PaddleLite 2.7的？
建议按照教程编译paddle lite 2.7 opt工具，重新导出模型

**Comment by wangwh0128** [comment]
PaddleLite 2.7
模型是下的公开模型，需要用opt转换吗？
