### ISSUE TITLE
docker容器中多卡训练PGNet报错ABORT!!!Out of all 4 trainers, the trainer process with rank[0] was aborted. Please check its log.

### ISSUE THREAD

**Issue by kuli-cyd** [PaddlePaddle/PaddleOCR#3219]
![5B317B0E-CE0C-4254-A2C6-267B0E35998C](https://user-images.githubusercontent.com/85658392/123895203-08bd2c00-d992-11eb-8b70-ac3b4fc3cfd1.png)

**Comment by kuli-cyd** [comment]
![Uploading 5B317B0E-CE0C-4254-A2C6-267B0E35998C.png…]()

**Comment by tink2123** [comment]
看一下workerlog.0 文件中的具体报错信息，可能是显存不足的问题，调小评估的batch_size试试

**Comment by kuli-cyd** [comment]
不是显存的问题，看监控似乎是训练过程中会出现内存泄漏，调小batch_size只能减缓这一增长
