### ISSUE TITLE
det_algorithm must in ['DB']

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3220]
![image](https://user-images.githubusercontent.com/49063302/123899167-3e194800-d999-11eb-921f-c1e82806f1bd.png)
![image](https://user-images.githubusercontent.com/49063302/123899170-3fe30b80-d999-11eb-968a-922b91d208bb.png)

请问这里是只支持DB算法吗？

**Comment by tink2123** [comment]
whl 包目前只支持DB算法，其他模型的预测建议clone整个项目，并参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/inference.md

**Comment by Luffffffy** [comment]
> whl 包目前只支持DB算法，其他模型的预测建议clone整个项目，并参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/inference.md

哦哦，这样啊，但是我发现使用其他模型的预测，并不支持python直接调用，而是只能命令行调用，并且结果是直接输出在控制台的，并不能直接获取从而进行后续的操作，是否还需要自己下修改源代码呢？

**Comment by tink2123** [comment]
是的，可以自己修改源码支持相关功能。

**Comment by Luffffffy** [comment]
希望能尽快支持别的算法，应为DB模型的效果有点差，在方向不规则的图片上表现尤为明显

**Comment by MathewsJosh** [comment]
Is it still necessary to clone the repository to add new rec and det models in the current version (2.7)?

**Comment by Laubeee** [comment]
@MathewsJosh it seems like, still getting the same error.
it is also unclear to me whether the algorithm can just be changed, or if that also requires detection model re-training.
