### ISSUE TITLE
关于检测模型的评估参数

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3223]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/detection.md#%E6%8C%87%E6%A0%87%E8%AF%84%E4%BC%B0
![image](https://user-images.githubusercontent.com/49063302/123915623-49796d00-d9b3-11eb-8fbe-b309c9965315.png)

在评估检测模型的时候，可以设置 box_thresh、unclip_ratio 两个参数
我验证过在DB算法模型上的有效性，官方提示说在EAST算法模型上无效
那如果是SAST算法模型上，是否有效，还是无用呢？有点疑惑

**Comment by tink2123** [comment]
这两个参数是DB后处理需要的，EAST和SAST都不生效
