### ISSUE TITLE
视频文字检测

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3224]
您好，视频文字检测如果逐帧检测的话会能实现但是很慢，请问有什么快的方法吗？

**Comment by tink2123** [comment]
现在的速度大概是多少呢？方便给一下测试数据吗？
cpu上可以开启mkldnn加速，GPU上可以开启Tensorrt加速

**Comment by zcswdt** [comment]
> 现在的速度大概是多少呢？方便给一下测试数据吗？
> cpu上可以开启mkldnn加速，GPU上可以开启Tensorrt加速

我没有使用加速，而是直接调用大模型对视频每帧都要检测，这样的话，时间就是（检测+识别）乘视频帧数 。例如一个6分钟的视频是13000帧，其中有文字的有300帧，则话花费的时间就是，300乘2 =600s。

**Comment by raychiu0202** [comment]
> > 现在的速度大概是多少呢？方便给一下测试数据吗？
> > cpu上可以开启mkldnn加速，GPU上可以开启Tensorrt加速
> 
> 我没有使用加速，而是直接调用大模型对视频每帧都要检测，这样的话，时间就是（检测+识别）乘视频帧数 。例如一个6分钟的视频是13000帧，其中有文字的有300帧，则话花费的时间就是，300乘2 =600s。

您这每一帧需要两秒的原因是每帧识别前需要重新加载模型吗？加个QQ讨论下 757374816

**Comment by zcswdt** [comment]
> 每一帧需要两秒的原因是每帧识别前需要重新加载模型吗？加个QQ讨论下

我之前使用的是实时检测，每一帧都要进行检测，发现非常的耗时，后来我改成了抽帧检测，每1s抽5帧检测，这个快点。30s视频抽帧检测+识别是11S。之前每帧需要2S是图片上的文字非常的多，所以识别很耗时。
