### ISSUE TITLE
sast算法检测模型pretrained模型与inference模型效果不一致

### ISSUE THREAD

**Issue by Lufffya** [PaddlePaddle/PaddleOCR#3225]
操作步骤如下：
1，sast pretrained 模型使用命令预测：
`python tools/infer_det.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.infer_img="" Global.pretrained_model="output/sast_r50_vd_ic15_train/best_accuracy" `

2，得到结果：

![image](https://user-images.githubusercontent.com/49063302/123933770-45eee180-d9c5-11eb-9259-f9552d62e996.png)

3，使用命令转换inference 模型：
`python tools/export_model.py -c configs/det/det_r50_vd_sast_icdar15_train.yml -o Global.pretrained_model=output/sast_r50_vd_ic15_train/best_accuracy  Global.save_inference_dir=inference/sast_r50_vd_ic15_train`

4，使用命令推理：
` python tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="" --det_model_dir="inference/sast_r50_vd_ic15_train"`

5，得到结果：
![image](https://user-images.githubusercontent.com/49063302/123933818-5010e000-d9c5-11eb-8870-b2f96b204f55.png)

**这个问题真的没有办法解决吗？**

ps:附上det_r50_vd_sast_icdar15.yml配置文件关键部分:
![image](https://user-images.githubusercontent.com/49063302/123936520-d3333580-d9c7-11eb-8c74-dff7e62deed9.png)

**Comment by tink2123** [comment]
对齐一下预测的后处理参数试试：
https://github.com/PaddlePaddle/PaddleOCR/blob/39161f5c9be9307d0756bbd4e6c8567f929ab671/tools/infer/utility.py#L57-L60

**Comment by Luffffffy** [comment]
> 对齐一下预测的后处理参数试试：
> https://github.com/PaddlePaddle/PaddleOCR/blob/39161f5c9be9307d0756bbd4e6c8567f929ab671/tools/infer/utility.py#L57-L60

本来就是这样的
![image](https://user-images.githubusercontent.com/49063302/123942235-87838a80-d9cd-11eb-9d67-e29f36508219.png)

**Comment by tink2123** [comment]
是的，我的意思是和你yml文件里的参数对齐

**Comment by Luffffffy** [comment]
> 是的，我的意思是和你yml文件里的参数对齐

我检查了这三个参数，和yml文件里面的参数值是一样的
其实这个问题真的很好复现，随便下载一个resnet sast的pretrained模型，预测一张图片，然后使用同样的yml文件转换为inference模型再预测相同的图片，就可以看到结果

**Comment by ioracion** [comment]
[https://github.com/PaddlePaddle/PaddleOCR/issues/2470](url)

**Comment by Luffffffy** [comment]
> [看看我的](https://github.com/PaddlePaddle/PaddleOCR/issues/2470)

我在提这个问题之前就看过你的issue，但是对我没有任何的帮助，依然存在这个问题
