### ISSUE TITLE
图片可以根据坐标分割吗

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3226]
如图：
![image](https://user-images.githubusercontent.com/49063302/123945648-f6aeae00-d9d0-11eb-951b-ff1a7a1d31ad.png)

有图片检测出来的文字框和对应的坐标若干，
能不能根据这个文字框坐标 [ 左上（x,y），右上（x,y)，右下（x,y)，左下（x,y)] 分割成每个小图片呢，
我猜想paddleOCR repo里面是有这个代码的，但是找不出来它在哪里
因为  https://github.com/PaddlePaddle/PaddleOCR/issues/3225 的缘故，我只能想到这种办法，
先用pretrained模型去检测坐标，再手动拆分，然后逐个识别。。。

**Comment by tink2123** [comment]
根据坐标crop文本框：https://github.com/PaddlePaddle/PaddleOCR/blob/39161f5c9be9307d0756bbd4e6c8567f929ab671/tools/infer/predict_system.py#L49

**Comment by Luffffffy** [comment]
> 根据坐标crop文本框：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/39161f5c9be9307d0756bbd4e6c8567f929ab671/tools/infer/predict_system.py#L49

非常有用，感谢！！！
