### ISSUE TITLE
从图片中裁减出来的待识别的文字区域的大小是否应该和训练crnn模型时的图片大小一致？

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#323]

**Comment by tink2123** [comment]
预测时会将图片缩放到训练尺度，因此对裁剪操作没有过多的限制

**Comment by hsyy673150343** [comment]
> 预测时会将图片缩放到训练尺度，因此对裁剪操作没有过多的限制

明白了，谢谢您的解答～！

**Comment by hsyy673150343** [comment]
> 预测时会将图片缩放到训练尺度，因此对裁剪操作没有过多的限制
如果用自己的数据集训练识别模型，例如街景文字识别，数据集的规模至少要达到万级甚至十万级才能取得较好的识别效果吗？
