### ISSUE TITLE
请问下 训练的时候 单卡正常多卡的就卡在加载数据上 不动了 无法下面进行训练 没有报错

### ISSUE THREAD

**Issue by 01Juw** [PaddlePaddle/PaddleOCR#3234]
请问下 训练的时候 单卡正常多卡的就卡在加载数据上 不动了 无法下面进行训练 没有报错
![image](https://user-images.githubusercontent.com/16891631/124086302-80b74f00-da83-11eb-810a-788784de73f0.png)

两个显卡显存都是占用一点后就不再增加了
![image](https://user-images.githubusercontent.com/16891631/124086382-93318880-da83-11eb-8198-5c8d35941906.png)

**Comment by SWHL** [comment]
我也遇到这个了，你可以尝试把下面的
https://github.com/PaddlePaddle/PaddleOCR/blob/aea8c08ac856c16e5a5ee5da82dc26991ec52381/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L5
改为
```python
print_batch_step: 1
```

**Comment by 01Juw** [comment]
已经可以了 RTX5000多显卡怎么都不行 重新创建实例换3090四卡可以正常训练了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 中午11:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问下 训练的时候 单卡正常多卡的就卡在加载数据上 不动了 无法下面进行训练 没有报错 (#3234)





 
我也遇到这个了，你可以尝试把下面的
 https://github.com/PaddlePaddle/PaddleOCR/blob/aea8c08ac856c16e5a5ee5da82dc26991ec52381/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L5
 改为
 print_batch_step: 1
