### ISSUE TITLE
使用python进行推理时，程序卡死报错

### ISSUE THREAD

**Issue by hch-baobei** [PaddlePaddle/PaddleOCR#3239]
I0702 10:43:11.765318  5376 analysis_config.cc:424] use_dlnne_:0
I0702 10:43:11.765318  5376 analysis_config.cc:424] use_dlnne_:0
I0702 10:43:11.765318  5376 analysis_config.cc:424] use_dlnne_:0
I0702 10:43:11.765318  5376 analysis_config.cc:424] use_dlnne_:0

Process finished with exit code -1073741819 (0xC0000005)

以上是全部的报错信息，我在dubug之后发现是在此处程序退出，位于 
tools/infer/predict_det.py  
169  
self.input_tensor.copy_from_cpu(img)

我查看issues 有人说是windows本身的问题，我尝试了linux可行，我想问一下飞桨开发组有没有办法在windows上解决这个问题？

**Comment by hch-baobei** [comment]
> I0702 10:43:11.765318 5376 analysis_config.cc:424] use_dlnne_:0
> I0702 10:43:11.765318 5376 analysis_config.cc:424] use_dlnne_:0
> I0702 10:43:11.765318 5376 analysis_config.cc:424] use_dlnne_:0
> I0702 10:43:11.765318 5376 analysis_config.cc:424] use_dlnne_:0
> 
> Process finished with exit code -1073741819 (0xC0000005)
> 
> 以上是全部的报错信息，我在dubug之后发现是在此处程序退出，位于
> tools/infer/predict_det.py
> 169
> self.input_tensor.copy_from_cpu(img)
> 
> 我查看issues 有人说是windows本身的问题，我尝试了linux可行，我想问一下飞桨开发组有没有办法在windows上解决这个问题？

说明一下我的配置文件，我采用的模型是直接官网下载的服务器端推理模型，测试图片也是使用的doc文件夹下的图片

**Comment by WenmuZhou** [comment]
请描述一下具体的运行环境，cuda版本，paddle版本，代码版本，运行命令，

**Comment by youwei2567** [comment]
试了下，windows平台关闭gpu，用cpu是可以跑起来的

**Comment by hch-baobei** [comment]
好的，了解了，谢谢你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 上午9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 使用python进行推理时，程序卡死报错 (#3239)





 
试了下，windows平台关闭gpu，用cpu是可以跑起来的
