### ISSUE TITLE
预测图片的resize

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3240]
https://github.com/PaddlePaddle/PaddleOCR/blob/aea8c08ac856c16e5a5ee5da82dc26991ec52381/ppocr/data/imaug/rec_img_aug.py#L109
您好，我看代码在训练的时候会将图片resize到3,32,320的值内（有Padding的操作），当时在预测代码的时候我看代码和训练的时候保持一致，也是3,32,320。这样的话，假设一个h,w为32单字符，后面加边也就是Padding的范围就是320-32这样子，就加了很多白边。预测不能处理输入直接为32,32的图片吗？请问这样做只是为了和训练保持一致还是有别的考虑呢？

**Comment by WenmuZhou** [comment]
直接送32*32进去效果不好

**Comment by zcswdt** [comment]
> 直接送32*32进去效果不好

请问这个是什么原因呢？如果加边进去的话不就相当于增加了干扰因素么？

**Comment by WenmuZhou** [comment]
因为训练时，对w较小的图片进行了pad，预测时进行pad可以和训练保持一致
