### ISSUE TITLE
关于图片预处理的问题

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3241]
我分别用相同的代码预测了同样但不同角度的图片
得到图下结果：
![image](https://user-images.githubusercontent.com/49063302/124218002-f4149b80-db2b-11eb-8450-ea5cbe304e2c.png)

![image](https://user-images.githubusercontent.com/49063302/124218048-055da800-db2c-11eb-8511-ad03a0d10196.png)

![image](https://user-images.githubusercontent.com/49063302/124218087-18707800-db2c-11eb-883d-4647f67ecdfd.png)

可以观察到，相同的图片，对于正面向上，和正面向右的处理都比较合理，
但是对正面向左的处理就比较离谱，观察到这个结果很疑惑
基于这个疑惑看了源代码的部分函数，发现个疑问
![image](https://user-images.githubusercontent.com/49063302/124218140-3938cd80-db2c-11eb-888f-c6a15acf7a66.png)

这里只对正面朝右的图片进行了逆时针90度的处理，
那如果是正面朝左的图片呢，识别不到的原因是否和这段代码的处理之间有些联系呢？

**Comment by WenmuZhou** [comment]
请问预测的时候开启分类器了吗 use_angle-cls=true，如果开启了的话，这个旋转是没影响的

**Comment by Luffffffy** [comment]
> 果开启了的话，这个旋转是没影响的

没有开启的，我一直不知道这个分类器的作用到底是什么，开不开启的话，是否会对我正常识别的结果造成影响？

**Comment by Luffffffy** [comment]
> 请问预测的时候开启分类器了吗 use_angle-cls=true，如果开启了的话，这个旋转是没影响的

其实这个旋转是旋转已经检测出来的文本框，但是向左的图片压根连文本框都检测不出来

**Comment by WenmuZhou** [comment]
方向分类器就是将倒置的图片转正啊，因为可能存在图片里文字倒置的情况

> > 果开启了的话，这个旋转是没影响的
> 
> 没有开启的，我一直不知道这个分类器的作用到底是什么，开不开启的话，是否会对我正常识别的结果造成影响？

**Comment by WenmuZhou** [comment]
> > 请问预测的时候开启分类器了吗 use_angle-cls=true，如果开启了的话，这个旋转是没影响的
> 
> 其实这个旋转是旋转已经检测出来的文本框，但是向左的图片压根连文本框都检测不出来

向左的是训练检测的时候没有相关数据

**Comment by Luffffffy** [comment]
> > > 请问预测的时候开启分类器了吗 use_angle-cls=true，如果开启了的话，这个旋转是没影响的
> > 
> > 
> > 其实这个旋转是旋转已经检测出来的文本框，但是向左的图片压根连文本框都检测不出来
> 
> 向左的是训练检测的时候没有相关数据

您是说向左的没有检测出来，是因为我训练集缺少向左标注样本的缘故？

**Comment by WenmuZhou** [comment]
是的
