### ISSUE TITLE
关于whl包的文档错误

### ISSUE THREAD

**Issue by Luffffffy** [PaddlePaddle/PaddleOCR#3242]
![image](https://user-images.githubusercontent.com/49063302/124230585-ca666f00-db41-11eb-82bb-02470c726092.png)

请问这个文档例子所述的输出里，那个是方向分类器的输出呢？

**Comment by Luffffffy** [comment]
还是说分类只能单独使用？
![image](https://user-images.githubusercontent.com/49063302/124231032-57112d00-db42-11eb-91f2-55c5791a7d7e.png)

**Comment by WenmuZhou** [comment]
预测过程中开启了分类器的话，分类器会在识别之前，将图片转正，是不会有输出的

**Comment by Luffffffy** [comment]
> 预测过程中开启了分类器的话，分类器会在识别之前，将图片转正，是不会有输出的

那请问这个转正的操作是出于什么原因呢，到底在使用的时候是否需要带上分类器？

**Comment by WenmuZhou** [comment]
因为存在图片为倒置的情况，所以需要转正，使用的时候是否需要取决于你的场景
