### ISSUE TITLE
Paddle OCR c++ OCR_SYSTEM 编译问题

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#3243]
环境：CentOS Linux release 7.2.1511 (Core) 
推理库：ubuntu14.04_cpu_avx_mkl_gcc82  paddle_inference.tgz  预测库(2.0.2版本) 
Paddle OCR 2.0
错误如下，请教哪里还要配置，谢谢！
-- Build files have been written to: /root/projects/PaddleOCR/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
[ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
[100%] Linking CXX executable ocr_system
CMakeFiles/ocr_system.dir/src/ocr_cls.o: In function `PaddleOCR::Classifier::Run(cv::Mat&)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:38: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:39: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:46: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:47: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_cls.o: In function `PaddleOCR::Classifier::LoadModel(std::string const&)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:75: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.o: In function `PaddleOCR::DBDetector::LoadModel(std::string const&)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:23: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_det.o: In function `PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:74: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:75: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:81: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:82: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.o: In function `PaddleOCR::CRNNRecognizer::Run(std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >, cv::Mat&, PaddleOCR::Classifier*)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:47: undefined reference to `paddle_infer::Predictor::GetInputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:48: undefined reference to `paddle_infer::Predictor::GetInputHandle(std::string const&)'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:54: undefined reference to `paddle_infer::Predictor::GetOutputNames()'
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:55: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::string const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::string const&)':
/root/projects/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:99: undefined reference to `paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::shrink_to_fit()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__future_base::_State_baseV2::_Make_ready::_M_set()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/thirdsource/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make[2]: *** [ocr_system] Error 1
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
make: *** [all] Error 2

**Comment by linkewei0580** [comment]
能不能帮我解答一下呀，谢谢！

**Comment by linkewei0580** [comment]
是不是编译OCR_SYSTEM 需要GCC 8.2?

**Comment by WenmuZhou** [comment]
是的，你这个推理库需要8.2

**Comment by linkewei0580** [comment]
你好，感谢你的回复，我换了GCC 8.3.1 还是一样。



林可伟
13701764610
 
发件人： zhoujun
发送时间： 2021-07-12 12:17
收件人： PaddlePaddle/PaddleOCR
抄送： linkewei0580; Author
主题： Re: [PaddlePaddle/PaddleOCR] Paddle OCR c++ OCR_SYSTEM 编译问题 (#3243)
是的，你这个推理库需要8.2

**Comment by WenmuZhou** [comment]
可以试一下paddle自己的镜像看看
