### ISSUE TITLE
PaddleServing部署的服务，如何返回文本框坐标呢

### ISSUE THREAD

**Issue by xuncv** [PaddlePaddle/PaddleOCR#3244]
按教程部署的PaddleServing，跑通之后测试，只返回文本识别结果，

{'err_no': 0, 'err_msg': '', 'key': ['res'], 'value': ["['Paddle.jit.saveO）', '：best accuracy.pdopt', 'inference.pdmodel', 'ch det my3', '模型训练', 'best accuracy.pdparams', '模型转换', 'opt优化模型', 'inference.pdiparams', 'db opt.nb', 'best accuracy.states']"]}

翻了一圈文档，没找到返回文本框坐标的配置。请问应该如何设置呢

**Comment by WenmuZhou** [comment]
你开启的serving是system的吗

**Comment by xuncv** [comment]
> 你开启的serving是system的吗

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/pdserving/README_CN.md
按照这个文档部署的.文档中的截图也是没有返回文本坐标的

**Comment by lvjianjin** [comment]
目前官方给的代码是没有返回坐标框的，需要自己修改代码

**Comment by macanv** [comment]
尝试蹲一个大佬改好的
