### ISSUE TITLE
Missing spaces when using "latin" recognition model

### ISSUE THREAD

**Issue by chancezeus** [PaddlePaddle/PaddleOCR#3246]
Given this image
![Screenshot_2021-07-02_16-44-04](https://user-images.githubusercontent.com/2089196/124293195-ab260c80-db56-11eb-908a-7be1e4807355.png)

When running paddleocr (using python cli command) with ```--lang en``` it works as expected and it detects all words and separates them with spaces
![image](https://user-images.githubusercontent.com/2089196/124293143-9c3f5a00-db56-11eb-8a56-a2d98bcba98d.png)

However running it on the same image with ```--lang nl``` the words are recognized, but the spaces are gone
![image](https://user-images.githubusercontent.com/2089196/124293132-9a759680-db56-11eb-8544-f23d407b043c.png)

We are planning to embed this as a full frame OCR solution to detect subtitles in multiple countries so we really need the extra accents and punctuation marks provided by the latin recognition model, but it's unusable if it isn't able to add spaces into the correct places.

Can anybody provide a solution for this? I don't mind some additional pre- or post processing, but I have no idea where to start (already tried tweaking both detection and recognition model params to no avail).

**Comment by chancezeus** [comment]
@WenmuZhou any feedback on this would be greatly appreciated

**Comment by chancezeus** [comment]
@tink2123 anything?

Otherwise could you provide a download link for the (full) dataset used to train the latin recognition network that is not hosted on Baidu (since I don't live in China, using Baidu is very impractical and I prefer not having to install some random client/app on my laptop and/or phone, just to download the dataset) so we can retrain the network and perhaps add some additional data that includes spaces and/or reannotate some of the existing data (I checked the config yml file for the latin set and space recognition is enabled there, so my assumption is that the dataset itself is simply missing actual training data that includes them (and/or it's there but simply not annotated in a way that it's useable)).

**Comment by vcmellia** [comment]
Did you solve this problem?

**Comment by JayveeHe** [comment]
any updates for this issue?
