### ISSUE TITLE
DBNET训练文本检测

### ISSUE THREAD

**Issue by Mafengqiang** [PaddlePaddle/PaddleOCR#3247]
配置文件中的这些参数设置有说明文件吗，还有就是针对不同的训练集调整哪些参数能够针对性的提高模型的训练效果呢
![image](https://user-images.githubusercontent.com/44855506/124341152-01de2580-dbed-11eb-8842-41ce0450b61e.png)

**Comment by littletomatodonkey** [comment]
1. 目前数据增广这块没有参数说明，不过所有的类，都可以在`https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/data/imaug/` 这里找到对应的具体实现，可以看下
2. 给出的数据增广一般都是比较标准的数据增广或者 比较有效的数据增广，通用型比较强。针对不同的训练集，可能需要针对性调整

**Comment by Mafengqiang** [comment]
> 1. 目前数据增广这块没有参数说明，不过所有的类，都可以在`https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/ppocr/data/imaug/` 这里找到对应的具体实现，可以看下
> 2. 给出的数据增广一般都是比较标准的数据增广或者 比较有效的数据增广，通用型比较强。针对不同的训练集，可能需要针对性调整

好的，谢谢
