### ISSUE TITLE
检测和识别怎么连接

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3248]
想用轻量化的检测模型配合RCNN识别，不知道怎么将两个阶段连接在一起。

**Comment by littletomatodonkey** [comment]
你好，你说的是CRNN识别？

**Comment by littletomatodonkey** [comment]
可以参考这里：[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_ch/inference.md#%E4%BA%94%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E5%92%8C%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E4%B8%B2%E8%81%94%E6%8E%A8%E7%90%86)

**Comment by hice1207** [comment]
> 你好，你说的是CRNN识别？

谢谢您，我没有注意到有这个说明。
