### ISSUE TITLE
关于PGNet训练中文数据集端到端准确率一直为0

### ISSUE THREAD

**Issue by kuli-cyd** [PaddlePaddle/PaddleOCR#3251]
用PGNet训练一百万中文数据集，字典长度6k+，单机6卡，batchsize设置为10，目前训练了7个epoch，总loss下降到20左右，但是端到端精确、召回和f指标仍然为0，请问这一现象正常吗？想问下咱们Paddle开源的中文模型大概训练多少个epoch才能有效果？另外目前速度大概6、7个小时一个epoch，请问这个速度正常吗？

**Comment by LDOUBLEV** [comment]
开源的中文模型用的DB算法，PGNet在中文数据上直接训练效果不一定有DB好

> 目前训练了7个epoch，总loss下降到20左右

看loss是没有收敛很好

> 目前速度大概6、7个小时一个epoch

每个epoch 100W数据，这个时间是差不多的

**Comment by s957995299** [comment]
> 看loss是没有收敛很好

您好，模型没收敛好该怎么办呢？我检测模型用db算法训练的，但是指标也都是0，应该也是没收敛好

**Comment by hooyia123** [comment]
經歷了很長時間的train和eval，親測，PGNet目前除了English，其他語種都不支持。所以，希望用PGNet訓練中文的，都不用浪費時間了。
