### ISSUE TITLE
crnn中的lstm问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3255]
您好，在crnn中如果不使用lstm，结果和使用lstm准确率相差大么，如果不使用这个结构在代码中如何修改呢？

**Comment by LDOUBLEV** [comment]
不使用LSTM 准确率会降低1-2个点左右，也看数据集场景了

不使用lstm，在训练的时候，这里设置为reshape
https://github.com/PaddlePaddle/PaddleOCR/blob/dae6e749b918bd7ab05b8080241c5807518bc765/configs/rec/rec_mv3_none_none_ctc.yml#L44
