### ISSUE TITLE
Cannot make bilingual detection 

### ISSUE THREAD

**Issue by todhm** [PaddlePaddle/PaddleOCR#3257]
I tried to detect ocr contents Korean. However if some english words are mixed in contents model gave as false result. 
Is there any parameters I can use to detect english words with korean model? 
<img width="340" alt="mixedkorean" src="https://user-images.githubusercontent.com/20569265/124430934-bd988400-ddaa-11eb-8e25-e894ee7dd34e.png">

Expected Output: 
```
[[[[136.0, 114.0], [417.0, 114.0], [417.0, 141.0], [136.0, 141.0]], ('쇼핑의즐거움이 함께하는', 0.9392483)], [[[431.0, 116.0], [562.0, 116.0], [562.0, 139.0], [432.0, 140.0]], ('[NC광주역점',~~)]]```
```
Real Output
```
[[[[136.0, 114.0], [417.0, 114.0], [417.0, 141.0], [136.0, 141.0]], ('쇼핑의즐거움이 함께하는', 0.9392483)], [[[431.0, 116.0], [562.0, 116.0], [562.0, 139.0], [432.0, 140.0]], ('[6공주역점', 0.79012376)]]```
```

```
from paddleocr import PaddleOCR
from PIL import Image

lang = 'korean'
ocr_app = PaddleOCR(lang=lang)

with Image.open('tests/data/images/mixedkorean.png') as img:
    img = img.convert("RGB")
    img = np.array(img)
    ocr.ocr(img)
```

**Comment by tink2123** [comment]
Sorry， mixed English and Korean, the model recognition effect is not good enough, there are no parameters to adjust for the time being, we will optimize the model effect in the later stage, welcome to continue to pay attention.
