### ISSUE TITLE
在英伟达nano上使用 tensorrt推理报错

### ISSUE THREAD

**Issue by xiesibo** [PaddlePaddle/PaddleOCR#3260]
paddle-gpu=2.0.0
paddleocr=2.0
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Adding input elementwise_add_1 failed in TensorRT inference network. Please recheck your input.
  [Hint: input should not be null.] (at /home/jetson/Paddle/paddle/fluid/inference/tensorrt/engine.cc:235

**Comment by LDOUBLEV** [comment]
- 尝试关闭TensorRT的动态shape，即屏蔽https://github.com/PaddlePaddle/PaddleOCR/blob/b7c8bfb4a1deea20d69e4317029850518e04e15f/tools/infer/utility.py#L226
- 设置较大的min_subgraph_size https://github.com/PaddlePaddle/PaddleOCR/blob/b7c8bfb4a1deea20d69e4317029850518e04e15f/tools/infer/utility.py#L169
