### ISSUE TITLE
chinese_ocr_db_crnn_server可以离线使用吗？

### ISSUE THREAD

**Issue by gaogaoxingxing2010** [PaddlePaddle/PaddleOCR#3263]
chinese_ocr_db_crnn_server运行报错如附件图片，目前我是离线状态下，不可上网，是否可用呢？一定需要联网吗？
![IMG_20210705_200615](https://user-images.githubusercontent.com/62227361/124531904-0bac9680-de42-11eb-8be2-0807d5b8a90b.jpg)

**Comment by tink2123** [comment]
不连网可以用的，但是需要手动把模型下载好，并指定加载模型路径

**Comment by gaogaoxingxing2010** [comment]
感谢老师回复！下载我会，我是小白一枚
。指定加载模型路径这块，您能给下具体实例代码吗？或者相关资料。感谢感谢！附全部代码如下链接：https://blog.csdn.net/weixin_44936889/article/details/114916600

**Comment by gaogaoxingxing2010** [comment]
或者改下hub.Module()参数，加入路径吗？

**Comment by gaogaoxingxing2010** [comment]
或者我把下载后的模型放到C:\Users\xxxx.paddlehub\modules目录下，原代码不改会自动加载模型呢？

**Comment by gaogaoxingxing2010** [comment]
> 不连网可以用的，但是需要手动把模型下载好，并指定加载模型路径

或者我把下载后的模型放到C:\Users\xxxx.paddlehub\modules目录下，原代码不改会自动加载模型呢？

**Comment by grasswolfs** [comment]
> > 不连网可以用的，但是需要手动把模型下载好，并指定加载模型路径
> 
> 或者我把下载后的模型放到C:\Users\xxxx.paddlehub\modules目录下，原代码不改会自动加载模型呢？

是的，源代码不改会自动到这个路径下找模型加载

**Comment by gaogaoxingxing2010** [comment]
> > > 不连网可以用的，但是需要手动把模型下载好，并指定加载模型路径
> > 
> > 或者我把下载后的模型放到C:\Users\xxxx.paddlehub\modules目录下，原代码不改会自动加载模型呢？
> 
> 是的，源代码不改会自动到这个路径下找模型加载
> 

按照您的指导，我下载好模型后尝试hub install 模型，会报错KeyError: 'version'，详见截图。这是为什么呢？
ps：我也尝试了把模型包解压后放在C:\Users\xxxx.paddlehub\modules目录，执行后也报KeyError: 'version'的错误，跟上面一模一样。
