### ISSUE TITLE
识别训练精度到了98%就不提高了

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#3266]
我用rec_en_number_lite_train.yml训练识别英文字母与数字，识别精度到了98%，测试精度到96%，就不提高了，请问是什么原因。
2021/07/06 12:23:33] root INFO: epoch: [44/200], iter: 76000, lr: 0.000888, loss: 0.044212, acc: 0.980469, norm_edit_dis: 0.980469, reader_cost: 0.35390 s, batch_cost: 0.56907 s, samples: 2560, ips: 449.85604
[2021/07/06 12:24:52] root INFO: cur metric, acc: 0.961811404986523, norm_edit_dis: 0.9740109782120395, fps: 2278.5071829951635
训练数据集有44万条，测试数据集有10万条

**Comment by tink2123** [comment]
可以把识别错误的预测结果和label打印出来对比一下，精度到96%已经很高了。

**Comment by ronaldpan** [comment]
只有到99%以上才能用于实际应用。

**Comment by tink2123** [comment]
那就具体看一下预测错误的图片样式以及预测错的结果，针对性调优。
