### ISSUE TITLE
关于文字识别中用到双向LSTM的问题

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#3278]
请问各位大佬，在训练手写文字识别模型时，用了attention和双向LSTM，发现模型的推理结果出现了文本重复的现象。
比如：
输入的文本标签是：你好
模型推理的结果是：你好你好
但并不是每个文本推理结果都会重复，大部分还是正常的。
请问这是什么原因呢，有遇到的吗？

**Comment by WenmuZhou** [comment]
这个是模型对这张图片表现不好，如果只有这一张的话，可以忽略
