### ISSUE TITLE
srn的训练代码的疑问

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleOCR#3280]
在看代码的时候有几个疑问，请解答一下，谢谢

1.  数据预处理后哟这几个字段，其中length字段是不是后续的模型没用到？      、
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'

**2.     srn_head的forward代码**
`    def forward(self, inputs, others):
        encoder_word_pos = others[0]
        gsrm_word_pos = others[1]
        gsrm_slf_attn_bias1 = others[2]
        gsrm_slf_attn_bias2 = others[3]`
(1)inputs是image进过resnet后的结果吗
(2)这里是others是怎么得到的，看了BaseModel的forward和build_dataloader的代码，没有找到
3. padding补的是end token， 计算loss的时候好像没有除掉padding？

**Comment by tink2123** [comment]
1. length 在build SRN head时会用到，默认是25:https://github.com/PaddlePaddle/PaddleOCR/blob/418490edd711925fe6a8f5afbcb416798989f428/ppocr/modeling/heads/rec_srn_head.py#L227
2. 是的，inputs 是backbone的输出，是这个关系：https://github.com/PaddlePaddle/PaddleOCR/blob/418490edd711925fe6a8f5afbcb416798989f428/ppocr/modeling/architectures/base_model.py#L80
3. others 是在数据准备的时候手动创建的：https://github.com/PaddlePaddle/PaddleOCR/blob/418490edd711925fe6a8f5afbcb416798989f428/ppocr/data/imaug/rec_img_aug.py#L162
4. 计算loss的时候不需要除掉padding，解码时遇到第一个end token就结束了
