### ISSUE TITLE
推理模型和训练模型

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3282]
推理模型和训练模型相比有什么优势呢

**Comment by WenmuZhou** [comment]
速度快，模型小，不需要组网代码，可以cpp部署

**Comment by Mythos-Rudy** [comment]
> 速度快，模型小，不需要组网代码，可以cpp部署

请问models_list.md里说的推理模型(inference model)是从训练模型(trained model)转换过来的吗
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md

**Comment by WenmuZhou** [comment]
是的
