### ISSUE TITLE
有配置文本长度的地方吗？在配置文件中只看到了max_text_length参数

### ISSUE THREAD

**Issue by steinvenic** [PaddlePaddle/PaddleOCR#3283]
现在想要识别验证码，验证码的长度都是固定的，如果在训练过程中就把长度表明了，是不是在结果上能有更好的表现呢？可是我没找到能配置的地方，希望开发能帮助解惑^_^

**Comment by WenmuZhou** [comment]
这个配置文件里没有，需要自己自定义代码来达到你的要求了
