### ISSUE TITLE
关于文字识别时使用attention训练时出现的问题

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/PaddleOCR#3284]
请问文字识别时使用attention，会出现什么意想不到的问题？
目前我得到的问题是会缺失后面的文本，比如一个文本是：宝可梦图鉴，得到的识别结果会是：宝可梦，图鉴两个字没有被识别出来，在停止符号之后。
会不会还有其他问题，请各位大佬指点！

**Comment by WenmuZhou** [comment]
mark
