### ISSUE TITLE
求助，如何把表格OCR识别结果保存到 excel

### ISSUE THREAD

**Issue by hpevo** [PaddlePaddle/PaddleOCR#3287]
按照SDK 接口调用示例，写了以下代码

""" 读取图片 """
def get_file_content(filePath):
    with open(filePath, 'rb') as fp:
        return fp.read()

def file_download(url, name):
    res = requests.get(url)
    with open(name + '.xls', 'wb') as f:
        f.write(res.content)

img_path = './test1/26.jpg'
image = get_file_content(img_path)

""" 如果有可选参数 """
options = {}
options["language_type"] = "JAP"
options["detect_direction"] = "true"
options["detect_language"] = "true"
options["probability"] = "true"

res2 = client.tableRecognitionAsync(image,options)
requestId = res2['result'][0]['request_id']
res3 = client.getTableRecognitionResult(requestId,options)

msg = res3['result']['ret_msg']
if msg == '已完成':
    url = res2['result']['result_data']
    file_download(url, img_path.split('/')[-1][:-4])
    print(img_path.split('/')[-1] + ' down')
else:
    time.sleep(1)
    print(res3)

我是小白，请帮我把代码重写一下，.tableRecognitionAsync是表格文字识别，不可以直接返回识别的结果吗，为何还要getTableRecognitionResult返回识别结果，怎么把结果写到 excle 文件里

**Comment by WenmuZhou** [comment]
请问你用的是百度云api吗，这个建议问一下那边的客服人员

**Comment by solofive** [comment]
百度表格识别接口调用，有个同步和异步我记得，可以去看下文档，异步的话，代码中的request_id我记得应该是本次请求编号，需要拿这个编号再发一次请求获取excel文件。
