### ISSUE TITLE
仅做车牌号识别，自己数据，用训练模型结果正确，转化inference后识别结果错误

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#3288]
训练模型推理：
python tools/infer_rec.py -c configs/rec/hphm.yml -o Global.pretrained_model=./output/hphm_mydict/latest Global.load_static_weights=false Global.infer_img=E:/0202pzsqb/rec/merge_3_data/test/95_bg5.jpg
![2021-07-07_17-42-32](https://user-images.githubusercontent.com/63723648/124737703-c7f18400-df4a-11eb-8d6c-7e0fcdf22a2e.jpg)
然后转化为inference：
python tools/export_model.py -c configs/rec/hphm.yml -o Global.pretrained_model=./output/hphm_mydict/best_accuracy Global.save_inference_dir=./inference/hphm_mydict/
最后用inference预测：
from paddleocr import PaddleOCR
ocr = PaddleOCR(rec_model_dir=r'./inference/hphm_mydict', rec_char_dict_path=r'./ppocr/utils/hphm.txt') 
img_path = r'E:/0202pzsqb/rec/merge_3_data/test/95_bg5.jpg'
result = ocr.ocr(img_path, det=False)
for line in result:
    print(line)
![2021-07-07_17-50-07](https://user-images.githubusercontent.com/63723648/124738911-f6239380-df4b-11eb-9a87-b6187b3612b8.jpg)
结果和用训练模型预测的不一致，且训练模型是正确的结果。
被预测的图片如下
![95_bg5](https://user-images.githubusercontent.com/63723648/124741409-3dab1f00-df4e-11eb-9e38-018070959c1c.jpg)

模型和配置文件在链接内：
链接：https://pan.baidu.com/s/1XB6rg4oQ5OJQDH3MbYanIg 
提取码：9cbx

**Comment by wjrjsdx** [comment]
windows下用了paddle2.0,2.1,2.1.1都试过了，都是这个问题

**Comment by xxx1996** [comment]
> windows下用了paddle2.0,2.1,2.1.1都试过了，都是这个问题

我也碰到过类似的问题，源码的推理结果和pip包的推理结果存在一些差别...

**Comment by MRQinhao66666** [comment]
插眼，等待解决方案

**Comment by WenmuZhou** [comment]
你试一下把训练模型和推理模型的图片处理过程保持一致看看，具体就是将这两行注释掉https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/predict_rec.py#L72-L73

**Comment by wjrjsdx** [comment]
> 你试一下把训练模型和推理模型的图片处理过程保持一致看看，具体就是将这两行注释掉https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/tools/infer/predict_rec.py#L72-L73

感谢回复，测试可以
