### ISSUE TITLE
视频流的实时检测

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3290]
paddleOCR的模型里面有没有能进行视频实时检测识别的，类似工业仪表的实时检测。

**Comment by zcswdt** [comment]
> paddleOCR的模型里面有没有能进行视频实时检测识别的，类似工业仪表的实时检测。

我也想请教视频文字采用什么方法来检测，顺便在这提一下。大佬们出来解答一下，哈哈

**Comment by WenmuZhou** [comment]
视频实时检测识别，我理解就是将视频读取成图片帧，然后送入OCR系统，视频的读取paddleocr没有实现，可以手动实现下，然后调用paddleocr的检测识别能力

**Comment by Yuyanze** [comment]
我这里有个关于视频流模型部署的问题：这边问题是C#每次传一张图片给我，然后C#每次调用PaddleOCR dll的话都要重新从我的paddleOCR C++ 程序里面加载模型，然后识别,这样会非常耗时，能不能有只加载模型一次的方法？另外我的PaddleOCR dll只能在子线程中调用，不能再主线程中调用

**Comment by HaloWang** [comment]
> 视频实时检测识别，我理解就是将视频读取成图片帧，然后送入OCR系统，视频的读取paddleocr没有实现，可以手动实现下，然后调用paddleocr的检测识别能力

当两个不同图片帧之间有很多重复的信息时, 在传输给 OCR.dll 做识别前有很多优化空间. 要是 PaddleOCR 能提供对应的优化算法就好了和 DEMO 就好了🤗
