### ISSUE TITLE
gpu加速推理

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3292]
您好，请问有什么方法可以使用在gpu上进行加速推理，如果可以，有文档教程么？

**Comment by littletomatodonkey** [comment]
目前轻量级模型的速度主要瓶颈在数据读取和预处理这块，可以尝试使用异步数据读取的方式，加快数据处理这块的速度

**Comment by zcswdt** [comment]
> 目前轻量级模型的速度主要瓶颈在数据读取和预处理这块，可以尝试使用异步数据读取的方式，加快数据处理这块的速度

额，，，轻量级还好，我想使用大模型，能否有在gpu上加速预测的方法。轻量级我目前用不到，效果不太好。

**Comment by littletomatodonkey** [comment]
这种也可以通过数据读取优化去加速，不过目前我们还没太多精力做这个，你可以先试下哈~

**Comment by rainmakerMa** [comment]
人家问的问题不是推理加速嘛，扯什么异步读取数据。。又不是训练。。
不是应该回答tensorrt加速和模型量化方面的问题嘛
