### ISSUE TITLE
FatalError: Segmentation fault is detected by the operating system

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3295]
在Jetson AGX板卡运行paddlehub 中的ocr识别模型上会出现这种问题。
- 版本、环境信息：
    1）PaddlePaddle版本： 2.0.0  PaddleHub版本：2.0.0
    2）GPU： CUDA10.2 
    3）系统环境：JetPack 4.4  

-预测信息 
    1）预测库来源：[https://paddle-inference-lib.bj.bcebos.com/2.0.2-nv-jetson-jetpack4.4-all/paddlepaddle_gpu-2.0.2-cp36-cp36m-linux_aarch64.whl]( https://paddle-inference-lib.bj.bcebos.com/2.0.2-nv-jetson-jetpack4.4-all/paddlepaddle_gpu-2.0.2-cp36-cp36m-linux_aarch64.whl) 由问题 [#32210](https://github.com/PaddlePaddle/Paddle/issues/32210)提供的预测库

```
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/even/.local/lib/python3.6/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/home/even/.local/lib/python3.6/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-02-23 09:46:24,533] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0223 09:46:24.583606  8416 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   cuDevicePrimaryCtxRetain
1   paddle::framework::SignalHandle(char const*, int)
2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1614044784 (unix time) try "date -d @1614044784" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fa95f6090) received by PID 8416 (TID 0x7fa9631010) from PID 18446744072256184464 ***]

Segmentation fault (core dumped)
```
在 `~/.bashrc`文件中加入了：`export CUDA_VISIBLE_DEVICES=0 和 export OPENBLAS_CORETYPE=ARMV8`

**Comment by littletomatodonkey** [comment]
你好，先用下下面的python代码看下paddle是否安装成功呢？

```
import paddle
paddle.utils.run_check()
```

看着是环境不太兼容导致的~

**Comment by PhilCuriosity** [comment]
感谢回复，这是打印的内容。是不是cuDNN版本不匹配造成的？

> ~$ python3 
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
----》import paddle
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
----》 paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0223 09:46:19.155405  8170 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.2, Driver API Version: 10.2, Runtime API Version: 10.2
W0223 09:46:19.215874  8170 device_context.cc:372] device: 0, cuDNN Version: 8.0.
PaddlePaddle works well on 1 GPU.
I0223 09:46:43.849323  8170 parallel_executor.cc:469] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.



> 你好，先用下下面的python代码看下paddle是否安装成功呢？
> 
> ```
> import paddle
> paddle.utils.run_check()
> ```
> 
> 看着是环境不太兼容导致的~

**Comment by PhilCuriosity** [comment]
这里我结束掉整个程序后，为什么GPU占用的内存没有释放掉？
![image](https://user-images.githubusercontent.com/52873355/125029936-f55e3f00-e0bc-11eb-8686-0d8d06343e2b.png)

**Comment by littletomatodonkey** [comment]
`top`看下占用显存的进程id呢，`kill -9` 杀掉看下呢？

**Comment by PhilCuriosity** [comment]
> `top`看下占用显存的进程id呢，`kill -9` 杀掉看下呢？

这里可能是Py36的bug，在当前terminal中使用ps 查看会有Python3的进程，在新开的terminal中`top`看不到Python3 的进程。

请问第一个问题有解决方法吗？

**Comment by PhilCuriosity** [comment]
我这边目前使用的是paddlehub的中文识别的Server模型，会是paddlehub那边的问题吗？
