### ISSUE TITLE
训练过程存在内存泄露

### ISSUE THREAD

**Issue by ZhangLichao1987** [PaddlePaddle/PaddleOCR#3297]
PaddleOCR随着训练时间增加，内存占用逐渐增大，能否解决，在PaddleOCR交流群中提过

**Comment by ZhangLichao1987** [comment]
我查过PaddleOCR代码，发现问题很可能出在Paddle框架底层，因此也测试了PaddleDetection的代码，发现存在同样的问题，因此百度能否查一查。

**Comment by ZhangLichao1987** [comment]
![image](https://user-images.githubusercontent.com/40378089/125014688-bc17d600-e0a0-11eb-9807-96659cd58ae0.png)
尝试在train.py里面加这三行代码，依然会随着训练逐渐增加内存,内存是波浪式上升的，稳定一段时间之后，就涨一点，然后又稳定一段时间，再涨一点
![image](https://user-images.githubusercontent.com/40378089/125015112-6db70700-e0a1-11eb-894a-b87cdc75f18a.png)
后面这个内存会逐渐涨到满

**Comment by ZhangLichao1987** [comment]
![image](https://user-images.githubusercontent.com/40378089/125015160-84f5f480-e0a1-11eb-8b13-72da97713af8.png)
加的三行代码如上，因此推测，这个代码只针对推理模型（推理我没有测试）

**Comment by ZhangLichao1987** [comment]
我的机器配置是：centos7

**Comment by ZhangLichao1987** [comment]
我机器的配置是：TeslaT4，32G内存，CentOS7系统

**Comment by MissPenguin** [comment]
paddle使用的哪个版本？

**Comment by ZhangLichao1987** [comment]
> paddle使用的哪个版本？
2.1.0版本
![image](https://user-images.githubusercontent.com/40378089/125017971-bb823e00-e0a6-11eb-91f6-1004cbef8ee1.png)

**Comment by ZhangLichao1987** [comment]
> paddle使用的哪个版本？

我怀疑是数据加载的问题，而这个问题，藏在paddle底层框架中，如果真是这样，那么其实挺致命的，估计一时半刻也解决不了，所以麻烦查一查吧。

**Comment by MissPenguin** [comment]
好的，我们稍后排查一下，有结论后在这里反馈。

**Comment by jackiezzq** [comment]
#3199 
同遇到这个问题

**Comment by lz2470** [comment]
#3235 同样问题，应该是底层有地方跑完一个epoch内存没释放，导致不断积累

**Comment by hhhhhhogan** [comment]
请问这个问题解决了吗

**Comment by ZhangLichao1987** [comment]
还没有，百度在查。有结果之后，百度会直接在这里回复。我相信只要是需要长时间训练模型的人都会遇到这个问题。
本来抱着挺大期望来用paddle，因为paddle准备了很多现成的东西，很好。但是这些现成的东西里面也确实不少问题，就我试验就发现不少，有些真的很可怕。

比如：我看有issues说百度模型转换前后推理结果不一致，这多吓人。（我都不敢转了，不敢在产品上冒这个风险）
还有一些我搭建项目时遇到的种种问题，有些我能用另一条路做的我就自己做了（要改很多paddle项目的代码），由于最终问题还是解决了，所以里面的问题也就忍了。

但如果是底层问题，你说我改了之后，以后还更新你们的东西不？更新完了我每次都要自己去改一遍底层？万一底层变了，我还要再查。所以希望官方赶紧修正吧。

在paddle产品的使用上，我也是已经下了不少功夫了，不想再用pytoch或TF把很多东西重做，而且我多少还是有些爱国情怀的，希望国人能做出点替代他们的好产品。所以百度加把劲吧，看看多少人遇到同样的问题，当然肯定也有你们不知道的，就是有多少人因为这些问题放弃了paddle。


> 请问这个问题解决了吗



> 好的，我们稍后排查一下，有结论后在这里反馈。



> #3235 同样问题，应该是底层有地方跑完一个epoch内存没释放，导致不断积累



> #3199
> 同遇到这个问题

**Comment by MooncellAutomaton** [comment]
之前各种卸载重装pip包版本尝试出来的（之前在18.04上试出来的方法，后面重装成20.04了也行），最后的操作大概是下面这样：


环境 Ubuntu20.04
rtx2070s
cuda11.2
cudnn8.11

步骤：
1.先安装paddlepaddle 2.1.1
2.然后再安装gpu版（2.0.2.post102），会显示已经存在paddlepaddle，无法安装。
3.卸载cpu版，再安装gpu版本
4.然后pip list会发现有两个版本，一个paddlepaddle，另一个paddlepaddle－gpu，但是不影响使用


手机码的字，可能记忆有些偏差。你可以先试试看。总之是paddle和某些包的版本匹配问题（也可能卡了个bug？）

注： cuda是11.2，但是依然下的.post102版本,或许.post112也行？暂时不敢折腾了

**Comment by MooncellAutomaton** [comment]
还有，我貌似也更新了一下requirement.txt里面的某些包版本。如果上面没用的话再告诉我。我把pip list拉出来。

主要安装cpu版本是因为貌似只有cpu版本会下载和更新一堆其他包。可能是某个包的问题。

除了paddle，其他是用aliyun的源

**Comment by PhilCuriosity** [comment]
我这边遇到过在Jetson AGX使用Paddlehub的OCR识别Server模型，存在程序退出后内存没有释放的情况[链接](https://github.com/PaddlePaddle/PaddleOCR/issues/3295#issuecomment-876933594)使用的时Paddle2.0

**Comment by wa3926** [comment]
还好吧  用最新的代码  paddle 2.0.2   linux GPU 500W 数据 多线程读取数据  我已经训练10几天了   显存一直是 17G左右  没动过

**Comment by ZhangLichao1987** [comment]
> 还好吧 用最新的代码 paddle 2.0.2 linux GPU 500W 数据 多线程读取数据 我已经训练10几天了 显存一直是 17G左右 没动过

这里说的是内存不是显存，你大概是数据比较多，epoch迭代慢，外加内存大。

**Comment by wa3926** [comment]
我这个内存确实会变 线程个数会来回变 我看不影响训练就没管过它  内存128G的   
![image](https://user-images.githubusercontent.com/53547082/125582862-9aae9257-a9ed-48cb-9e30-6d7a68408ac1.png)

**Comment by ZhangLichao1987** [comment]
> 我这个内存确实会变 线程个数会来回变 我看不影响训练就没管过它 内存128G的
> ![image](https://user-images.githubusercontent.com/53547082/125582862-9aae9257-a9ed-48cb-9e30-6d7a68408ac1.png)

你这500W数据，一个epoch我估计都得跑个几天，十几天能跑20个epoch么？我这边测试是每个epoch之后，内存占用会多一点。

**Comment by ZhangLichao1987** [comment]
![image](https://user-images.githubusercontent.com/40378089/125583589-cd26c897-4e49-43cb-98a0-b0e45d84debf.png)
这条进程，你可以关注一下，不过你一个epoch太慢了，估计很难注意到

**Comment by wa3926** [comment]
@ZhangLichao1987  
![image](https://user-images.githubusercontent.com/53547082/125583820-f6d27fce-61ba-417a-af26-90ecb49d1bd2.png)
现在还在训练呢  一轮10个小时 感觉慢 正在找原因呢
![image](https://user-images.githubusercontent.com/53547082/125584014-ca38a930-a673-4477-b6b2-1b69d76d9b08.png) 这条线程一直在变  不知道为什么

**Comment by ZhangLichao1987** [comment]
> @ZhangLichao1987
> ![image](https://user-images.githubusercontent.com/53547082/125583820-f6d27fce-61ba-417a-af26-90ecb49d1bd2.png)
> 现在还在训练呢 一轮10个小时 感觉慢 正在找原因呢
> ![image](https://user-images.githubusercontent.com/53547082/125584014-ca38a930-a673-4477-b6b2-1b69d76d9b08.png) 这条线程一直在变 不知道为什么

训练慢的原因有可能有很多，但是每过一个epoch，那个内存会多一点。平时是波浪式的，然后到下一个epoch就会变多一点点，多的不多。像你这种内存大的，可能训个几天停下看一看效果，这样基本是察觉不出来这个泄露问题的。

**Comment by wa3926** [comment]
@ZhangLichao1987 那你把内存弄大一点吧

**Comment by ZhangLichao1987** [comment]
我32G还可以，不过数据少，连续训个1天还是每啥问题，只不过我就是发现了这个问题。

**Comment by neverstoplearn** [comment]
遇到同样问题

**Comment by neverstoplearn** [comment]
#3341

**Comment by Askfk** [comment]
同样的问题，数据比较大，只有64g内存，训练的时候还得手动杀死程序从checkpoint开始来实现释放内存，

**Comment by MissPenguin** [comment]
拉取最新dygraph分支代码试试呢

**Comment by MissPenguin** [comment]
大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
1. 对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
2. 自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

**Comment by hhhhhhogan** [comment]
你好，请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？










在 2021-08-02 19:40:43，"MissPenguin" ***@***.***> 写道：

大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：

对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

**Comment by hhhhhhogan** [comment]
请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？
![image](https://user-images.githubusercontent.com/40531744/128107224-f7010072-352b-4aff-8d02-1690969916c7.png)
![image](https://user-images.githubusercontent.com/40531744/128107231-b0cde2c4-edfc-494f-8024-52365657938a.png)


图片刚刚好像没有贴上来。。。。
请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？

> 大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
> 
> 1. 对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
> 2. 自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

**Comment by ZhangLichao1987** [comment]
个人认为不一定是dataloader问题，可能是数据集标注或者格式有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月4日(周三) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 训练过程存在内存泄露 (#3297)




 
请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？
 
 
 
图片刚刚好像没有贴上来。。。。
 请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？
  
大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
  
对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py 

自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle 
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhhogan** [comment]
好的，不过我使用的icdar15的数据集，并且是训练到一定epoch时候就会报错













在 2021-08-04 09:30:03，"ZLC" ***@***.***> 写道：

个人认为不一定是dataloader问题，可能是数据集标注或者格式有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月4日(周三) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 训练过程存在内存泄露 (#3297)





请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？



图片刚刚好像没有贴上来。。。。
请问这个原因也是因为dataloader导致的内存泄漏而报的错误吗？出现了好几次，不知应该如何解决？

大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：

对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py

自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDOUBLEV** [comment]
# 训练过程中内存泄漏问题解决
1. 更新Paddle OCR的代码，OCR检测训练内存溢出问题修复https://github.com/PaddlePaddle/PaddleOCR/pull/3434；
2. 需要安装最新版本的paddle develop版本，下载链接，或者按照这个PR修改Paddle Dataloader源码：
https://github.com/PaddlePaddle/Paddle/pull/34301

**Comment by Wei-JL** [comment]
> 大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
> 
> 1. 对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
> 2. 自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

收到

**Comment by Atiuiee** [comment]
> 大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
> 
> 1. 对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
> 2. 自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle

好像更新到paddlepaddle-gpu2.2.0就没有这个问题了

**Comment by Jsooooooo** [comment]
> 大家好，经排查，训练内存泄露的问题是Paddle的dataloader导致的，目前已有pr修复这个问题，但暂时没有稳定whl包可直接替换，因此临时解决方案有2种供大家参考：
> 
> 1. 对照这个pr修改自己安装好的Paddle中的相关文件：https://github.com/PaddlePaddle/Paddle/pull/34301/files ，如果是用的docker，文件路径应该类似这样：/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
> 2. 自己拉取Paddle官网代码，编译新的Paddle whl包：https://github.com/PaddlePaddle/Paddle
