### ISSUE TITLE
推理的过程中显存会泄露

### ISSUE THREAD

**Issue by Helloworld0214** [PaddlePaddle/PaddleOCR#3299]
![微信图片_20210709154320](https://user-images.githubusercontent.com/22692122/125042491-796bf300-e0cc-11eb-8e5f-c61dff54e8e3.png)
设置显存限制为4GB，但显存不会释放，当图片数量多的时候会出现显存不够的情况。

**Comment by MissPenguin** [comment]
用的最新版的代码吗，推理内存泄漏打开这个开关可以修复：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/utility.py#L152
可以检查下你的代码

**Comment by Helloworld0214** [comment]
> 用的最新版的代码吗，推理内存泄漏打开这个开关可以修复：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/utility.py#L152
> 可以检查下你的代码

谢谢，你的代码解决了问题。

**Comment by yuxx0218** [comment]
> 用的最新版的代码吗，推理内存泄漏打开这个开关可以修复：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/utility.py#L152
> 可以检查下你的代码

根本不好使，显存依旧无法释放。

**Comment by 0x0004** [comment]
> > 用的最新版的代码吗，推理内存泄漏打开这个开关可以修复：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/utility.py#L152
> > 可以检查下你的代码
> 
> 谢谢，你的代码解决了问题。

这个怎么打开，参数形式是什么

**Comment by Helloworld0214** [comment]
您好，我已收到您的邮件，尽快给您回复。祝好
