### ISSUE TITLE
different naming format might be a little trap to the new 

### ISSUE THREAD

**Issue by AvenSun** [PaddlePaddle/PaddleOCR#33]
> det_r50_vd_east.tar      &emsp;&emsp;     det_east_r50_vd.yml
> det_mv3_east.tar       &emsp;&emsp;    det_east_mv3.yml
> det_r50_vd_db.tar     &emsp;&emsp;      det_db_r50_vd.yml
> det_mv3_db.tar       &emsp;&emsp;    det_db_mv3.yml

**Comment by goodtogood** [comment]
我就遇到这个问题了，当时看了好几遍没看出来哪错了-_-
