### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by Harrisonyong** [PaddlePaddle/PaddleOCR#3305]
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/bin/platforms" ...
loaded library "/usr/local/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1625825525 (unix time) try "date -d @1625825525" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x1d) received by PID 29 (TID 0x7f60723c8080) from PID 29 ***]

**Comment by Harrisonyong** [comment]
when I use python3 PPOCRLabel.py to start it, I meet this question as I description.  I have checked all the qt libary have been perpared. So, what's the reason caused this bug?

**Comment by Evezerest** [comment]
Do you run PPOCRLabel on Linux? What version of qt have you installed？

**Comment by Fanky186** [comment]
@Evezerest @Harrisonyong 
Hi, I have the same problem， So how do we solve this？Please help me

**Comment by mohandeepzumen** [comment]
@Evezerest my qt version is qt5, I used pip install PyQt5

**Comment by mohandeepzumen** [comment]
Just resolved it. Install opencv in the same env where you installed paddle paddle. use "pip install opencv-python==4.2.0.32".
Doing this resolved for me

**Comment by liguiyuan** [comment]
I have solved this problem, reduce the OpenCV version :
pip3 install --upgrade opencv-python==4.2.0.32
