### ISSUE TITLE
紧急求解：训练时偶现AttributeError错误

### ISSUE THREAD

**Issue by byh1990** [PaddlePaddle/PaddleOCR#3306]
硬件环境：cuda10.1 两个2080Tipaddle和2.1.1版本都试过
出现的问题：
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 85, in main
    parameters=model.parametersld_metric())
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataParallel' object has no attribute 'parametersld_metric'
INFO 2021-07-10 02:03:38,172 launch_utils.py:327] terminate all the procs
ERROR 2021-07-10 02:03:38,172 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2021-07-10 02:03:41,176 launch_utils.py:327] terminate all the procs

请问如何解决？比较着急，因为我们目前在落地中

**Comment by LDOUBLEV** [comment]
你好，可以试试parameters=model._layers.parametersld_metric())
