### ISSUE TITLE
从头训练识别网络

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3307]
您好，我想用自己的数据集，不使用预训练权重，从头训练一个识别网络，使用的配置是官方提供的rec_chinese_lite_train_v1.1.yml，PaddleOCR版本是1.1。

训练开始时，loss在下降，但是下降到一定值时，不在下降而且依然很大，acc也一直为0。感觉学习率设置存在问题。

请问这正常吗，或者说从头训练一个识别网络，大概需要多久？如果可以，能否给出从头开始训练识别网络的一个训练策略或者步骤？

**Comment by hanguangmic** [comment]
我也有同样的问题

**Comment by LDOUBLEV** [comment]
识别训练前期acc会一直为0，训练时间长一些就会有精度了，
如果你的数据很多，可以先找一个小数据子集训练看看
