### ISSUE TITLE
eval.py使用下载的预训练模型评估自有数据集的检测结果，均为0

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/PaddleOCR#3308]
在自己的数据集上使用pretrain_models（官方），load_static_weights设为False，但是precision，recall等仍为0.
看了一下代码的区别主要在init_model的方式上，最终也导致预测的preds的差别。
不知道有人遇到同样的事情么？

**Comment by LDOUBLEV** [comment]
用的哪个分支的代码，你评估的指令可以发一下

**Comment by HongChow** [comment]
> 用的哪个分支的代码，你评估的指令可以发一下
谢谢答复。
分支是最新的：release/2.1（paddle的环境是2.0，我是不是应该切到2.0去？）
指令代码：%run  tools/eval.py -c configs/det/det_mv3_db.yml  -o  Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x1_0_pretrained/  PostProcess.box_thresh=0.5 PostProcess.unclip_ratio=1.5

**Comment by HongChow** [comment]
> 用的哪个分支的代码，你评估的指令可以发一下

分支是最新的：release/2.1（paddle的环境是2.0，我是不是应该切到2.0去？）
指令代码：%run tools/eval.py -c configs/det/det_mv3_db.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x1_0_pretrained/ PostProcess.box_thresh=0.5 PostProcess.unclip_ratio=1.5

**Comment by HongChow** [comment]
> 用的哪个分支的代码，你评估的指令可以发一下

分支是最新的：release/2.1（paddle的环境是2.0，我是不是应该切到2.0去？）
指令代码：%run tools/eval.py -c configs/det/det_mv3_db.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x1_0_pretrained/ PostProcess.box_thresh=0.5 PostProcess.unclip_ratio=1.5

**Comment by LDOUBLEV** [comment]
./pretrain_models/MobileNetV3_large_x1_0_pretrained/ 

这个模型是backbone预训练模型，训练的时候加载，用于模型快速收敛，要评估精度，可以用readme中提供的训练好的模型：
![image](https://user-images.githubusercontent.com/26592129/125242439-466d6d80-e31f-11eb-806e-23239f04d8eb.png)

**Comment by HongChow** [comment]
> ./pretrain_models/MobileNetV3_large_x1_0_pretrained/
> 
> 这个模型是backbone预训练模型，训练的时候加载，用于模型快速收敛，要评估精度，可以用readme中提供的训练好的模型：
> ![image](https://user-images.githubusercontent.com/26592129/125242439-466d6d80-e31f-11eb-806e-23239f04d8eb.png)
非常感谢！
