### ISSUE TITLE
使用CPU加速时遇到的问题

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#3313]
Traceback (most recent call last):
  File "/root/PaddleOCR/tools/infer/predict_server.py", line 234, in rec_hand
    result = main(args,f)
  File "/root/PaddleOCR/tools/infer/predict_server.py", line 187, in main
    dt_boxes, rec_res = text_sys(img)
  File "/root/PaddleOCR/tools/infer/predict_server.py", line 92, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/root/PaddleOCR/tools/infer/predict_det.py", line 170, in __call__
    self.predictor.run()
RuntimeError: could not execute a primitive

可以知道这是因为什么  如何修改吗

**Comment by tink2123** [comment]
是开启mkldnn的时候遇到的报错吗？可以更新paddle版本至2.1，问题应该已经修复，参考issue：https://github.com/PaddlePaddle/Paddle/issues/29506

**Comment by super999** [comment]
遇到同楼主相同的问题.
环境一
1.  使用 visual studio 2019 , x64 , release , 版本 2.1.0 (GIT COMMIT ID: 4ccd9a0a86ad550a861c954d70e28ef15741b310) 未发现该问题,   
环境二

**Comment by Actor12** [comment]
> 遇到同楼主相同的问题. paddle_inference c++
> 环境一
> 
> 1. 使用 visual studio 2019 , x64 , release , 版本 2.1.0 (GIT COMMIT ID: 4ccd9a0a86ad550a861c954d70e28ef15741b310)
>    开启mkldnn    未发现该问题,
>    环境二
> 2. 使用 QT 开发,  Qt Creator 4.14.2 ,  Based on Qt 5.15.2 (MSVC 2019, 64 bit), 在Release环境下,  版本 2.1.1 (GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e)
>    开启mkldnn  后 有概率读取到到第二张图片, 或者之后的图片抛出异常  could not execute a primitive
>    Microsoft C++ exception: dnnl::error at memory location 0x000000F1E41FDCD0.
>    概率与图片文件OCR识别的顺序相关.
>    关闭 mkldnn    未发现报错.

同，请问你解决了吗

**Comment by sevenold** [comment]
> 是开启mkldnn的时候遇到的报错吗？可以更新paddle版本至2.1，问题应该已经修复，参考issue：[PaddlePaddle/Paddle#29506](https://github.com/PaddlePaddle/Paddle/issues/29506)

paddlepaddle            2.1.3 还是有这个问题

**Comment by super999** [comment]
> > 遇到同楼主相同的问题. paddle_inference c++
> > 环境一
> > 
> > 1. 使用 visual studio 2019 , x64 , release , 版本 2.1.0 (GIT COMMIT ID: 4ccd9a0a86ad550a861c954d70e28ef15741b310)
> >    开启mkldnn    未发现该问题,
> >    环境二
> > 2. 使用 QT 开发,  Qt Creator 4.14.2 ,  Based on Qt 5.15.2 (MSVC 2019, 64 bit), 在Release环境下,  版本 2.1.1 (GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e)
> >    开启mkldnn  后 有概率读取到到第二张图片, 或者之后的图片抛出异常  could not execute a primitive
> >    Microsoft C++ exception: dnnl::error at memory location 0x000000F1E41FDCD0.
> >    概率与图片文件OCR识别的顺序相关.
> >    关闭 mkldnn    未发现报错.
> 
> 同，请问你解决了吗

我目前的解决方案是 try catch 这个异常, 如果catch到异常 就重新new一次,  然后再ocr一次. 我当前的版本是 2.1.1

**Comment by UncleLLD** [comment]
同样还是遇到这样的问题，请求解决
![image](https://user-images.githubusercontent.com/16642335/145965417-a1e513d0-d0ba-444a-8a0c-45b2e01d588a.png)

**Comment by Jesse3692** [comment]
paddleocr 2.5.0.3也存在这个问题

**Comment by ladykillerjason** [comment]
> 
你好，解决了吗

**Comment by Lanme** [comment]
2.5也还有这个问题

**Comment by Sayaka91** [comment]
Still get this error in version 2.6.1.2

**Comment by piscesvivian** [comment]
paddlepaddle-2.6.1 依然存在这个问题，系统: windows 10,  Python 3.11

**Comment by ZZzeal** [comment]
> 我写flask只声明一次 ocr = PaddleOCR(use_angle_cls=True, lang="ch")，就会报这个错误。 然后我改成每次执行OCR 识别都NEW 一个这个对象就没问题了，相对速度会慢一点点，也能接受

同flask应用，先这样了，或者手动控制资源分配
