### ISSUE TITLE
如何提高gpu利用率，提高识别速度

### ISSUE THREAD

**Issue by mmApr** [PaddlePaddle/PaddleOCR#3315]
Paddleocr-release-2.1.0，运行paddleocr.py,将use_gpu改为True,预测一张图片，发现gpu利用率只有1%，一张10k的图片识别需要0.8秒，如何提高gpu利用率，提高识别速度？

**Comment by WenmuZhou** [comment]
可以通过设置rec_batch_num来提高识别的速度，检测因为每张图片的resize不一样，所以目前batch只能是一维，你的图片，可以限制一下图片的尺寸，还有可以循环跑测一下速度，第一张图片的速度不太准确
