### ISSUE TITLE
PaddleOCR自训练报错

### ISSUE THREAD

**Issue by Sweetwenty** [PaddlePaddle/PaddleOCR#3331]
![Uploading issue.png…]()
 使用自定义数据集训练完成后，将转换模型串联起来运行predict_system报错，请问有办法解决吗？

**Comment by MissPenguin** [comment]
你这个图片打不开，训练的哪个模型呢，这种问题一般是参数没对上导致的，麻烦具体描述一下模型的信息以及串联运行的命令。

**Comment by Sweetwenty** [comment]
![issue](https://user-images.githubusercontent.com/87378415/125664913-93256f43-deff-4b8d-a933-a02a6b475ddd.png)
角度分类模型没有训练，直接用的下载好的，检测和识别模型都训练了。串联起来首先碰到的错误：FileNotFoundError: [Errno 2] No such file or directory: './ppocr/utils/ppocr_keys_v1.txt'。由于我训练识别模型时自定义了字典，把那个字典复制过来后，会报错：IndexError: list index out of range。所以是不是角度分类模型也要用自己的数据训练一遍？
先将默认的这个字典复制过来。碰到的第二个错误就是上面的图片：
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1626284488 (unix time) try "date -d @1626284488" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7f39081077c5) received by PID 934 (TID 0x7f39181bf700) from PID 135296965 ***]

Floating point exception (core dumped)
将自训练的识别模型也替换成通用模型后，可以识别出结果。所以这一步是识别模型出问题了吗？
谢谢回复。下面是串联命令：
!python ./work/PaddleOCR/tools/infer/predict_system.py --image_dir="./work/PaddleOCR/doc/imgs/1.png" \
--det_model_dir="./work/PaddleOCR/output/det_db/best_accuracy/"  \
--rec_model_dir="./work/PaddleOCR/output/rec_CRNN/best_accuracy " \
--cls_model_dir="./work/PaddleOCR/inference/ch_ppocr_mobile_v1.1_cls_infer/" \
--use_angle_cls=True \
--use_space_char=True

**Comment by gl94** [comment]
我也出现了这个问题 是原图出了问题 比如说原图检测错误 切出来文本行只有 2*2 
你可以对原图的高度或者宽度加个判断
