### ISSUE TITLE
请问下影响 batch_cost 的因素有哪些

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#3334]
![image](https://user-images.githubusercontent.com/53547082/125579711-8eed4cf9-fa13-4800-8c93-6f97435ddf33.png)
上面是目前训练的log  
下面是参数配置
![image](https://user-images.githubusercontent.com/53547082/125579914-c5501053-182c-46e8-ab76-249f99a87588.png)

单卡V100 训练   感觉不应该这个速度的  多线程下reader_cost这个已经很小了  batch_cost 平均要2秒  求大佬指导下 有没有办法加快训练的速度！

**Comment by LDOUBLEV** [comment]
batch_cost 包括模型前向和反响梯度更新的时间，你的batch_size比较大，这个速度还算正常，
你可以看下GPU利用率和显存占用是否正常

**Comment by wa3926** [comment]
@LDOUBLEV  
![image](https://user-images.githubusercontent.com/53547082/125719043-3b771fb4-4e2e-48b5-99ac-ae6d9294c696.png)
大佬你好  GPU使用率正常的 0-99不断的变化  显存一直都是17个G  这张卡就一个在训练 其它2个是推理模型  我看关掉和开启对这训练没多大关系    已经训练10几天了 才20几轮   我看FAQ里面说 4卡500W 训练1个星期    我就简单算单卡20天  我这个我感觉要训练半年！
