### ISSUE TITLE
小语种数据集&小语种竖排文字检测

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3342]
1、请问小语种（日韩文）有没有一些街景、招牌等实用场景下的数据集呢？
2、 小语种竖排文字检测的话目前paddle支持识别吗？

**Comment by LDOUBLEV** [comment]
> 1、请问小语种（日韩文）有没有一些街景、招牌等实用场景下的数据集呢？

目前小语种模型的训练数据大多是合成数据，街景招牌数据很少

> 2、 小语种竖排文字检测的话目前paddle支持识别吗？

不支持

**Comment by LinXin04** [comment]
如果想在这个模型的基础上，fine-tuning识别街景招牌的话，需要大概多少街景样本呢？

**Comment by LDOUBLEV** [comment]
看你场景复杂度了，不过越多越好

**Comment by LinXin04** [comment]
我现在用的是japan_mobile_v2.0_rec_train这个模型（日文的我只找到这一个，还有别的吗），是否在这个模型的基础上，搞一些场景样本作微调即可？
