### ISSUE TITLE
识别模型转onnx，

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3344]
请问识别模型支持onnx转换吗？或者是支持tensorrt转换吗？

**Comment by LDOUBLEV** [comment]
目前发布的模型支持tensorrt预测，https://github.com/PaddlePaddle/PaddleOCR/blob/e10128ac4c8218beb15187ba460eabb149c7270c/tools/infer/utility.py#L34

**Comment by Dandelion111** [comment]
> 请问识别模型支持onnx转换吗？或者是支持tensorrt转换吗？

请问识别模型crnn转onnx，输入shape怎么设置的
