### ISSUE TITLE
paddleOCR使用GPU时报错，用CPU没问题

### ISSUE THREAD

**Issue by grasswolfs** [PaddlePaddle/PaddleOCR#3345]
论坛转用户issue贴：

我用的是centos7 ，cuda 11.2 + cudnn 8.2.0，显卡是Quadro P4000，paddle 版本是：paddlepaddle-gpu 2.1.1

--use-gpu=False时没问题，而使用gpu进行识别时报错：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0 paddle::framework::SignalHandle(char const*, int)
1 paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
[TimeInfo: *** Aborted at 1626252476 (unix time) try "date -d @1626252476" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 51654 (TID 0x7f38594bc700) from PID 0 ***]

 

通过打日志的形式定位到问题应该是出现在predict_det.py中，

        self.input_tensor.copy_from_cpu(img)
        self.predictor.run()  #就这行代码出错

有人能指点下怎么回事儿么？

**Comment by MooncellAutomaton** [comment]
paddlegpu版本不對:
post後面是cuda版本
python -m pip install paddlepaddle-gpu==2.1.1.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

實在不行去 https://www.paddlepaddle.org.cn/whl/mkl/stable.html 下2.0.2版本手動裝

**Comment by wolfog** [comment]
> paddlegpu版本不對: post後面是cuda版本 python -m pip install paddlepaddle-gpu==2.1.1.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
> 
> 實在不行去 https://www.paddlepaddle.org.cn/whl/mkl/stable.html 下2.0.2版本手動裝
完美解决
