### ISSUE TITLE
Recommended images

### ISSUE THREAD

**Issue by scopedog** [PaddlePaddle/PaddleOCR#3351]
Thank you for developing a great OCR program.

I have a question about images used for training. I created images from many texts and some fonts with pango-view and trained the recognition with PaddleOCR. However, it is not as accurate as ch_ppocr_mobile_v2.0_rec_infer or ch_ppocr_server_v2.0_rec_infer even in English. It is actually way worse than them.
What kind of images do you recommend, or what kind of images did you use for ch_ppocr_mobile_v2.0_rec_infer or ch_ppocr_server_v2.0_rec_infer? I'm currently re-creating images with TextRecognitionDataGenerator and pango-view with different background and foreground colors and noise, etc. Some texts are also blurred or distorted. Do you think they are OK?

Regards,

**Comment by tink2123** [comment]
Hi scopedog,

In addition to a large amount of synthetic data, ch_ppocr_mobile_v2.0 also uses real data in different scenarios. If your own data is not rich enough, you can directly load and provide good training weights to finetune, and you should get good results.

Regards

**Comment by scopedog** [comment]
Thank you for your response. I appreciate it.
