### ISSUE TITLE
ICDAR多语种数据集无法下载

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3353]
![image](https://user-images.githubusercontent.com/25193686/125882170-d12d01f6-d6a9-4078-978c-0492a0d86d24.png)

这里的数据集下载不下来，请问有没有别的数据存储路径呢？

**Comment by tink2123** [comment]
由于版权问题，只能给出官网地址，另外测试了一下，注册账号后是可以下载的。

**Comment by LinXin04** [comment]
这个数据集的话，我们的多语言OCR训练的时候有咩有使用呢？想用这个数据集来做多语言模型的fine-tuning

**Comment by tink2123** [comment]
有使用的，需要提醒下这个数据集是单词级别的标注，单独使用它做finetune的话会影响空格的识别效果。

**Comment by LinXin04** [comment]
我现在用的是japan_mobile_v2.0_rec_train这个模型。
这个数据集我把里面的图片都切割了，按照数据集里的四点坐标。然后做fine_tuning。就是下面这种格式
![image](https://user-images.githubusercontent.com/25193686/126255962-2740ed5d-6841-4d0b-94d8-a5db49632eb3.png)
![image](https://user-images.githubusercontent.com/25193686/126255991-51e45b04-181b-4ca1-b454-43c39ce8ba59.png)

fine tuning的时候，我发现，loss一直降低，但是acc一直是0怎么回事呢？
![image](https://user-images.githubusercontent.com/25193686/126256186-2c912984-9468-43f2-b05f-a26941fc1972.png)

**Comment by LinXin04** [comment]
![image](https://user-images.githubusercontent.com/25193686/126257042-b504dd52-7ff7-4d18-a5bf-90f033281d35.png)
