### ISSUE TITLE
请问文本识别的预训练模型在哪里下载啊？

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3357]
目前在训练文档只看到一个
```
# 下载MobileNetV3的预训练模型
wget -P ./pretrain_models/ https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar
```
还有其他基于paddle2.1英文识别的预训练模型吗？

**Comment by PhilCuriosity** [comment]
还有这两个
![image](https://user-images.githubusercontent.com/52873355/125914377-e54c62d9-444e-4269-8a9e-3df595ee7ef1.png)

**Comment by tink2123** [comment]
都在这个文档下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md

**Comment by PhilCuriosity** [comment]
好的，谢谢
