### ISSUE TITLE
检测训练时，训练log指标的含义是什么？尤其是后面四个指标

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleOCR#3359]
![Lark20210716181054](https://user-images.githubusercontent.com/41312357/125932279-5aa1cdf1-0fee-45e8-9810-a8d61392d8b3.png)

**Comment by tink2123** [comment]
可以看一下DB的论文，里面有loss含义的介绍：https://arxiv.org/abs/1911.08947

**Comment by bupt906** [comment]
reader_cost, batch_cost, samples, ips 这四个参数是什么意思？我在论文中没有看到相关介绍
