### ISSUE TITLE
训练过程中，如何恰当的停止训练

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#336]
有的时候，在训练模型中，可能效果不理想，会执行手动停止训练，当前我这边只能通过kill的方式结束训练，但是短时间内如果多次kill掉同一训练服务后会出现内存、CPU/GPU不够用的现象，只有重启容器才能恢复正常。关于如何正确的中止训练有什么好的方法吗

**Comment by littletomatodonkey** [comment]
可以通过下面的方式终止训练，会终止所有包含`train.py`字段的进程

`ps -axu | grep train.py | awk '{print $2}' | xargs kill -9`

**Comment by BeyondYourself** [comment]
之前一直用的是ps -ef|grep train.py   ，然后kill -9  进程ID
这样应该等同于你上面的操作吧，可能有的时候会有僵尸进程存在，有没有其他有效方式可以终止训练

**Comment by littletomatodonkey** [comment]
`fuser -v  /dev/nvidia*`
可以查看所有与显卡占用相关的进程，kill -9即可
