### ISSUE TITLE
训练遇到问题：The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. 

### ISSUE THREAD

**Issue by fxfviolet** [PaddlePaddle/PaddleOCR#3361]
我按照教程在cuda-11.2用icdar2015数据集训练，报以下错误：The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. 请问怎么解决？谢谢！

**Comment by tink2123** [comment]
nccl 安装有误，可能是没有设置好环境变量。建议在docker环境中运行代码，避免环境配置引起的问题

**Comment by fxfviolet** [comment]
非常感谢您的回复。我重新配置看看。
另外，请问一下，怎么在代码中指定GPU训练，我在终端用export CUDA_VISIBLE_DEVICES=1，不起作用。谢谢！

**Comment by fxfviolet** [comment]
非常感谢您的回复。我重新配置看看。
另外，请问一下，怎么在代码中指定GPU训练，我在终端用export CUDA_VISIBLE_DEVICES=1，不起作用。谢谢！
