### ISSUE TITLE
paddleocr: Command not found.

### ISSUE THREAD

**Issue by neonin04** [PaddlePaddle/PaddleOCR#3363]
I followed the every following step, and it worked successfully.

```
pip install paddlepaddle
pip install "paddleocr>=2.0.6" # 2.0.6 version is recommended
git clone https://github.com/PaddlePaddle/PaddleOCR.git
cd PaddleOCR
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x is the version number of paddleocr
```

However, command like these don't work.
`paddle -h`
`paddleocr --image_dir doc/imgs_en/254.jpg --lang=en`

`paddleocr: Command not found.`

How can I solve this? thanks in advance!

oh I'm also trying with the code as well, but that has another error too.. so i would like to execute it with the command.
(kindly note that please answer in English thank you)

**Comment by WenmuZhou** [comment]
you should use pip3 instead of pip
