### ISSUE TITLE
关于各个文本检测模型的训练数据 标注的问题 

### ISSUE THREAD

**Issue by tairen99** [PaddlePaddle/PaddleOCR#3366]
Hi PaddleOCR，

请问在使用DB, EAST，和 SAST 做 我自己数据文本检测的时候，对训练数据文本标注有什么要求？

比如说：因为我的训练文本 数据很大，我没有提供文本框对应的 transcription，也就是说为 "transcription": 为**常值**，或者为**空**， 如下所示

    ***_***_**/img_289.jpg	[{"transcription": "常值", "points": [[622, 327], [691, 332], [693, 356], [625, 352]]}, 
    {"transcription": "常值", "points": [[691, 335], [775, 337], [775, 361], [691, 358]]}, {"transcription": “”, "points": 
    [[679, 360], [731, 361], [731, 376], [679, 376]]}]

**请问 使用这样的训练数据 会影响 模型精度吗？ 是否一定要提供对应文本框的 transcription？**

在测试 SAST方法时，我注意到 在“configs/det” 文件夹中，有两个配置文件， 他们分别是：“det_r50_vd_sast_icdar15.yml” 和 “det_r50_vd_sast_totaltext.yml”，
其中 “det_r50_vd_sast_icdar15.yml” 对应的**训练数据的文本框是 四点 标注**？ 而 “det_r50_vd_sast_totaltext.yml” 对应的训练数据的文本框是 **十四点标注 还是 十六点标注呢**？

另为，在测试PGnet的时候，对应的 “e2e_r50_vd_pg.yml” 的**训练数据的文本框 是十四点标注 还是 十六点标注呢？** 我下载的 “total_text.tar” 中的训练数据文本框是采用的 十六点标注， 如：

    rgb/img399.jpg	[{"transcription": "Chirardelli", "points": [[120.0, 609.0], [295.6, 440.5], [471.1, 272.1], [703.4, 215.0], [942.9, 172.1], [1177.1, 206.1], [1408.3, 281.8], [1592.0, 442.0], [1423.0, 688.0], [1275.5, 546.2], [1099.9, 450.8], [904.8, 401.9], [703.7, 440.1], [512.3, 497.4], [361.8, 636.0], [211.0, 775.0]]}]

但是PaddleOCR网上 [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/pgnet_en.md](url) 提供的训练范例是 十四点标注：

    " Image file name             Image annotation information encoded by json.dumps"

    rgb/img11.jpg    [{"transcription": "ASRAMA", "points": [[214.0, 325.0], [235.0, 308.0], [259.0, 296.0], [286.0, 291.0], [313.0, 295.0], [338.0, 305.0], [362.0, 320.0], [349.0, 347.0], [330.0, 337.0], [310.0, 329.0], [290.0, 324.0], [269.0, 328.0], [249.0, 336.0], [231.0, 346.0]]}, {...}]

还麻烦你们帮忙指明！

谢谢！

**Comment by MissPenguin** [comment]
1. 训练检测模型时，transcription可以设为非“###”的任意字符（“###”表示该区域在训练时被忽略），不影响训练精度；
2. det_r50_vd_sast_icdar15.yml对应数据为4点标注，det_r50_vd_sast_totaltext.yml对应数据为14点标注；
3. PGnet的训练total text的文本框是14点标注，可以直接下载我们处理过的14点标注的total text数据集。

**Comment by tairen99** [comment]
Hi @MissPenguin，
     
谢谢您快速的答复！

 针对 问题3, 我有延伸的问题，还想请教您：

 1. 现有的 PGnet 能 针对文本框是4点标注的数据 进行训练吗？ 好像现有的配置文件是针对 文本框是14点标注的数据
 
 2. PaddleOCR中的 Total ltext 的14点标注的文本框 和 原始total text 的16 点标注的文本框，大概有什么不同以及为什么需要这些不同呢？
     
 3. 如果现有的 PGnet 不能用于 文本框是 4 点标注的训练数据，这就意味着 如果我们要训练自己的数据，我们必须将现有的 4 点文本框标注数据进行插值处理。请问这个插值处理有什么要注意的地方吗？ 是必须在文字框 上 均匀的设置 14 个采样点， 还是可以任意采样 进行插值呢？
    
 再次表示感谢！

**Comment by MissPenguin** [comment]
1. 支持4点，包括8点、10点、12点等等都是支持的，唯一要求是所有训练数据点数一致，不能混杂，因为要组batch
2. 你这个例子是test集合，预测时单张操作所以点数不一致没关系，训练集都插值成14点了
3. 支持4点，如果有需求扩充标注点数，需要自己写一下插值工具，大致思路就是文本上下边缘点数一致并且尽可能均匀分布。

**Comment by tairen99** [comment]
Hi @MissPenguin ,

    谢谢你的答复！
