### ISSUE TITLE
can not found op arguments for node conv2_b_attr

### ISSUE THREAD

**Issue by martinou** [PaddlePaddle/PaddleOCR#337]
参照端部署文档，执行opt时出错。Paddle 版本1.8.2，paddlelite 2.6.1
can not found op arguments for node conv2_b_attr。
请问什么原因。谢谢！

**Comment by LDOUBLEV** [comment]
opt工具是自己编译的吗？

**Comment by martinou** [comment]
自己编译的opt。优化的模型是官方提供。执行如下：
./opt --model_file=./ch_det_mv3_db/model --param_file=./ch_det_mv3_db/params --optimize_out_type=naive_buffer --optimize_out=./ch_det_mv3_db_opt --valid_targets=arm

**Comment by LDOUBLEV** [comment]
问题定位到了，paddle-lite 2.6.1引入了bug，我先测试其他分支，测试没问题之后同步给你

**Comment by LDOUBLEV** [comment]
> opt工具是自己编译的吗？
> opt优化的模型是inference model，如果是训练得到的模型，需要先通过tools/export.py转换为inference model

问题还在修复，为了方便你测试，先提供给你之前转换好的模型：

opt优化后的轻量中英文检测模型地址： https://paddleocr.bj.bcebos.com/deploy/lite/ch_det_mv3_db_opt.nb
opt优化后的轻量中英文识别模型地址： https://paddleocr.bj.bcebos.com/deploy/lite/ch_rec_mv3_crnn_opt.nb

**Comment by LDOUBLEV** [comment]
测试了最新的Paddle-Lite develop版本编译的opt工具可以用，文档也已更新， https://github.com/PaddlePaddle/PaddleOCR/pull/339
