### ISSUE TITLE
使用DB训练文本检测

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3375]
在使用DB训练文本检测时，hemean的值一直比较低，0.6-0.7之间，precision0.7左右，recall0.6左右，有没有优化策略能提一下这个指标呢，数据集场景比较复杂，字体大小尺度变化比较大，而且有许多艺术字这种

**Comment by MissPenguin** [comment]
数据集难度较大，所以指标上不去，这个指标是正常的，需要进行数据和算法调优

**Comment by lalalagogogochong** [comment]
> 数据集难度较大，所以指标上不去，这个指标是正常的，需要进行数据和算法调优

您好，数据和算法调优的话，有没有什么建议呢，可以从哪些方面着手呢，谢谢了

**Comment by MissPenguin** [comment]
数据多样性比较强的话，想要模型拟合的比较好，需要比较多的数据。轻量模型参数量少，能力有限，可以换resnet等更大的模型。可以看下ppocr技术报告：https://arxiv.org/abs/2009.09941 ，里面有一些调优方法可以参考。

**Comment by lalalagogogochong** [comment]
> 数据多样性比较强的话，想要模型拟合的比较好，需要比较多的数据。轻量模型参数量少，能力有限，可以换resnet等更大的模型。可以看下ppocr技术报告：https://arxiv.org/abs/2009.09941 ，里面有一些调优方法可以参考。

好的，十分感谢
