### ISSUE TITLE
文本检测训练的问题

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#3377]
如果我想检测不同的语言，如何在label中设置多个class，如中文为class0，英文为class1，韩文为class2？文本检测支持这样的操作吗

**Comment by MissPenguin** [comment]
现有检测模型基础上不太好操作，可以直接训一个分类模型，可以参考方向分类器的训练方式，或者直接看[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)。如果想直接改造检测模型，参考通用目标检测的网络结构搭建方式，参考[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)。

**Comment by rpaeng** [comment]
这个问题你解决了吗?
