### ISSUE TITLE
paddleocr如何只识别数字不识别中文

### ISSUE THREAD

**Issue by mmApr** [PaddlePaddle/PaddleOCR#3378]
比如识别某张图片，那张图片有一行：今天是2021年7月19日，如何只识别2021719这几个数字，不识别“今天是年月日”这几个中文字

**Comment by LDOUBLEV** [comment]
加个规则判断不就行了，识别出来的字不属于数字的话，就剔除掉

**Comment by mmApr** [comment]
具体怎么加规则呢

**Comment by LDOUBLEV** [comment]
python判断下字符是不是在【0-9】这些字符中不就可以了

**Comment by Gmgge** [comment]
使用正则匹配过滤一下结果。
