### ISSUE TITLE
How to output results in a txt file or JSON

### ISSUE THREAD

**Issue by 97morningstar** [PaddlePaddle/PaddleOCR#3380]
I am using the CPU version and I wish to get JSON or text files output with the results from each image. How can I do that from the command line?

Current command used: 

python3 tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="../images/valid/pii-likely-english" --e2e_model_dir="./inference/e2e_server_pgnetA_infer/" --e2e_pgnet_polygon=True --use_gpu=False

Thank you

**Comment by LDOUBLEV** [comment]
It does not support save outputs to files.
But U can easily implement this function by adding code to tools/infer/predict_e2e.py to save the ‘points’ and ‘strs’.

https://github.com/PaddlePaddle/PaddleOCR/blob/e10128ac4c8218beb15187ba460eabb149c7270c/tools/infer/predict_e2e.py#L147
