### ISSUE TITLE
按文档步骤操作，python tools/infer/predict_system.py --image_dir= "./doc/imgs/11.jpg " --det_model_dir= " ./inference/ch_ppocr_mobile_v2.0_det_infer/ "   --rec_model_dir= " ./inference/ch_ppocr_mobile_v2.0_rec_infer/ " --cls_model_dir= " ./inference/ch_ppocr_mobile_v2.0_cls_infer/ " --use_angle_cls=True --use_space_char=True遇到错误 unrecognized arguments: ./doc/imgs/11.jpg   ./inference/ch_ppocr_mobile_v2.0_det_infer/   ./inference/ch_ppocr_mobile_v2.0_rec_infer/   ./inference/ch_ppocr_mobile_v2.0_cls_infer/

### ISSUE THREAD

**Issue by xiaoyong001** [PaddlePaddle/PaddleOCR#3382]

**Comment by xiaoyong001** [comment]
遇到错误 unrecognized arguments: ./doc/imgs/11.jpg ./inference/ch_ppocr_mobile_v2.0_det_infer/ ./inference/ch_ppocr_mobile_v2.0_rec_infer/ ./inference/ch_ppocr_mobile_v2.0_cls_infer该怎么解决

**Comment by LDOUBLEV** [comment]
等号后面多加了空格吧？

**Comment by xiaoyong001** [comment]
好嘞，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月21日(周三) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 按文档步骤操作，python tools/infer/predict_system.py --image_dir= "./doc/imgs/11.jpg " --det_model_dir= " ./inference/ch_ppocr_mobile_v2.0_det_infer/ "   --rec_model_dir= " ./inference/ch_ppocr_mobile_v2.0_rec_infer/ " --cls_model_dir= " ./inference/ch_ppocr_mobile_v2.0_cls_infer/ " --use_angle_cls=True --use_space_char=True遇到错误 unrecognized arguments: ./doc/imgs/11.jpg   ./inference/ch_ppocr_mobile_v2.0_det_infer/   ./inference/ch_ppocr_mobile_v2.0_rec_infer/   ./inference/ch_ppocr_mobile_v2.0_cls_infer/ (#3382)




 
等号后面多加了空格
