### ISSUE TITLE
改变预训练模型后，找不到文件目录(文件目录存在)

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3386]
![TF%F8TW{8 M3KUZDPL2 D2](https://user-images.githubusercontent.com/65577659/126420541-7194350b-5ea3-444c-9a00-5acc980cbd97.png)
![S31LJ{434DTQ Z38 408D75](https://user-images.githubusercontent.com/65577659/126420622-4a5449f7-fd83-4ea6-b106-a2a79d46fcf5.png)
![PAWBE%@80LVHGI74SD(527O](https://user-images.githubusercontent.com/65577659/126420646-771a1d0f-dabf-4b6c-b298-78d4e6e6ce70.png)

只跟换了./configs/rec/rec_mv3_tps_bilstm_ctc.yml和预训练模型,代码就会报错跑不通
将错误判断跳过后,又会有新的错误,原先./configs/rec/rec_icdar15_train.yml和对应预训练模型可以跑通,但对0~90度弯曲文本来说准确率很低.

**Comment by lin-0015** [comment]
已根据train.log日志文件调整过yml配置

**Comment by tink2123** [comment]
自定义数据集请使用 SimpleDataSet 数据读取方式，参考 ./configs/rec/rec_icdar15_train.yml 的数据配置

**Comment by lin-0015** [comment]
> 自定义数据集请使用 SimpleDataSet 数据读取方式，参考 ./configs/rec/rec_icdar15_train.yml 的数据配置

非常感谢您!
