### ISSUE TITLE
小语种fine-tuning时acc一直是0

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3391]
我现在用的是japan_mobile_v2.0_rec_train这个模型。
这个数据集我把里面的图片都切割了，按照数据集里的四点坐标。然后做fine_tuning。就是下面这种格式
![image](https://user-images.githubusercontent.com/25193686/126446213-a686f45a-67ed-4177-9bf4-4a1e00cdc088.png)
![image](https://user-images.githubusercontent.com/25193686/126446230-50a4614b-ff81-4049-9019-7b556fa60255.png)

![image](https://user-images.githubusercontent.com/25193686/126446364-0daa7a00-44e8-496b-9422-58bda524ce25.png)
![image](https://user-images.githubusercontent.com/25193686/126446382-0b425b46-04bb-4ccc-b8c9-19cae2504825.png)
![image](https://user-images.githubusercontent.com/25193686/126446407-b250c1d8-3b51-42c5-a946-4d6989f9aa82.png)

fine tuning的时候，我发现，loss在降低之后不再变化，但是acc一直是0怎么回事呢？
![image](https://user-images.githubusercontent.com/25193686/126446259-5995d53b-cf58-4c4b-bd56-b8121b3a8561.png)

**Comment by tink2123** [comment]
是否修改了字典呢？如果修改了，那么开始是acc为0是正常的，因为最后一层fc参数没有加载，迭代一段时间acc就会上涨了。

**Comment by LinXin04** [comment]
没有修改字典，用的就是源代码里面的。
![image](https://user-images.githubusercontent.com/25193686/126580225-fd5d5cc9-fef9-4f3b-82c4-f9f730af5a67.png)

迭代到50几步都是0，而且loss从十几步的时候也基本不变了。
![image](https://user-images.githubusercontent.com/25193686/126579999-0e02e49d-679c-4934-a2d4-911774f4df42.png)

是我数据集有问题吗？

**Comment by ioracion** [comment]
loss有下降就好，多等等看

**Comment by LinXin04** [comment]
只在1-5epoch下降了，后面就一直在波动，不再下降。acc一直为0

**Comment by ioracion** [comment]
确实有点怪异。。那图片里的字在字典里都有不？

**Comment by LinXin04** [comment]
用的就是源码提供的dict，按道理说应该是比较全的了。。。没有另外补充

**Comment by LinXin04** [comment]
还是说这个训练的时候必须是字力度的？

**Comment by ioracion** [comment]
不要“按道理”，要确定，万一没覆盖全呢。
不用字粒度的。
yml文件的参数列出来看看呢。

**Comment by LinXin04** [comment]
Global:
  use_gpu: False
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_japan_lite
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  character_dict_path: ppocr/utils/dict/japan_dict.txt
  character_type: japan
  max_text_length: 25
  infer_mode: False
  use_space_char: False


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list: ["./train_data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list: ["./train_data/rec/rec_gt_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 8

**Comment by ioracion** [comment]
参数看起来中规中矩，没啥问题。。可能图片太小了分辨率太低？
还有就是你的data_dir路径这样设置能跑起来？我这样设置是不行（刚试了下
还有你要不换到aistudio上面跑吧(薅GPU)，你这CPU看着跑的实在慢...

**Comment by LinXin04** [comment]
用GPU跑有一个问题：
cuda: 10.1
cuDNN Version: 7.6

安装
pip install paddle==1.0.2 -i https://mirror.baidu.com/pypi/simple
python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

代码运行失败：
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)

**Comment by ioracion** [comment]
报错很明显了- - CUDNN_STATUS_NOT_INITIALIZED，装的版本不对？

**Comment by LinXin04** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
--
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

我装的
pip install paddle==1.0.2 -i https://mirror.baidu.com/pypi/simple
python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

其他版本都是过了，还是报错。

机器上跑其他的GPU任务是没有问题的。

**Comment by ioracion** [comment]
还是建议你先用aistudio上的gpu跑，环境都给你配好了，命令行一敲直接就能跑，先把模型搞出来，训练好了再捣鼓本地环境（我也还没弄本地的

**Comment by LinXin04** [comment]
我就是在AIstudio上跑的GPU，所以cuda环境肯定没问题。
W0722 17:38:59.804157 746 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.1, Runtime API Version: 10.1
device: 0, cuDNN Version: 7.6.

就是报错：

OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)
[operator < gaussian_random > error]
main process return code: 1
not found core file

**Comment by ioracion** [comment]
既然是用aistudio的话，那就没必要折腾paddle和paddlepaddle-gpu版本了吧- -
我这默认的库是这样的（就手动装了个paddleocr
Package                Version        

absl-py                0.8.1          
aspy.yaml              1.3.0          
astor                  0.8.1          
astroid                2.4.1          
attrs                  19.2.0         
audioread              2.1.8          
autopep8               1.5.3          
Babel                  2.8.0          
backcall               0.1.0          
bce-python-sdk         0.8.53         
blackhole              1.0.1          
bleach                 3.1.0          
cachetools             4.0.0          
certifi                2019.9.11      
cffi                   1.14.0         
cfgv                   2.0.1          
chardet                3.0.4          
Click                  7.0            
cloudpickle            1.6.0          
cma                    2.7.0          
colorama               0.4.4          
colorlog               4.1.0          
cycler                 0.10.0         
Cython                 0.29           
decorator              4.4.2          
dill                   0.3.3          
easydict               1.9            
entrypoints            0.3            
et-xmlfile             1.0.1          
filelock               3.0.12         
flake8                 3.8.2          
Flask                  1.1.1          
Flask-Babel            1.0.0          
Flask-Cors             3.0.8          
forbiddenfruit         0.1.3          
funcsigs               1.0.2          
future                 0.18.0         
gast                   0.3.3          
gitdb                  4.0.5          
GitPython              3.1.14         
google-auth            1.10.0         
google-auth-oauthlib   0.4.1          
graphviz               0.13           
grpcio                 1.35.0         
gunicorn               20.0.4         
gym                    0.12.1         
h5py                   2.9.0          
identify               1.4.10         
idna                   2.8            
imageio                2.6.1          
imageio-ffmpeg         0.3.0          
imgaug                 0.4.0          
importlib-metadata     0.23           
ipykernel              5.1.0          
ipython                7.0.1          
ipython-genutils       0.2.0          
isort                  4.3.21         
itsdangerous           1.1.0          
jdcal                  1.4.1          
jedi                   0.17.0         
jieba                  0.42.1         
Jinja2                 2.10.1         
joblib                 0.14.1         
JPype1                 0.7.2          
json5                  0.9.5          
jsonschema             3.1.1          
jupyter-client         5.3.3          
jupyter-core           4.5.0          
jupyter-lsp            0.8.0          
jupyterlab             2.1.3          
jupyterlab-server      1.1.5          
kiwisolver             1.1.0          
lazy-object-proxy      1.4.3          
librosa                0.7.2          
lightgbm               3.1.1          
llvmlite               0.31.0         
lmdb                   1.2.1          
Markdown               3.1.1          
MarkupSafe             1.1.1          
matplotlib             2.2.3          
mccabe                 0.6.1          
mistune                0.8.4          
more-itertools         7.2.0          
moviepy                1.0.1          
nbconvert              5.3.1          
nbformat               4.4.0          
netifaces              0.10.9         
networkx               2.4            
nltk                   3.4.5          
nodeenv                1.3.4          
notebook               5.7.0          
numba                  0.48.0         
numpy                  1.20.3         
oauthlib               3.1.0          
objgraph               3.4.1          
opencv-python          4.2.0.32       
openpyxl               3.0.5          
packaging              20.9           
paddlehub              2.0.4          
paddlenlp              2.0.0rc7       
paddleocr              2.0.4          
paddlepaddle-gpu       2.0.2.post101  
pandas                 1.1.5          
pandocfilters          1.4.2          
parl                   1.4.1          
parso                  0.7.0          
pathlib                1.0.1          
pexpect                4.7.0          
pickleshare            0.7.5          
Pillow                 7.1.2          
pip                    19.2.3         
pluggy                 0.13.1         
pre-commit             1.21.0         
prettytable            0.7.2          
proglog                0.1.9          
prometheus-client      0.5.0          
prompt-toolkit         2.0.10         
protobuf               3.14.0         
psutil                 5.7.2          
ptyprocess             0.6.0          
py4j                   0.10.9.2       
pyarrow                2.0.0          
pyasn1                 0.4.8          
pyasn1-modules         0.2.7          
pyclipper              1.3.0          
pycodestyle            2.6.0          
pycparser              2.19           
pycryptodome           3.9.9          
pydocstyle             5.0.2          
pyflakes               2.2.0          
pyglet                 1.4.5          
Pygments               2.4.2          
pylint                 2.5.2          
pynvml                 8.0.4          
pyparsing              2.4.2          
pypmml                 0.9.11         
pyrsistent             0.15.4         
python-dateutil        2.8.0          
python-jsonrpc-server  0.3.4          
python-language-server 0.33.0         
python-Levenshtein     0.12.2         
pytz                   2019.3         
PyWavelets             1.1.1          
PyYAML                 5.1.2          
pyzmq                  18.1.1         
rarfile                3.1            
recordio               0.1.7          
requests               2.22.0         
requests-oauthlib      1.3.0          
resampy                0.2.2          
rope                   0.17.0         
rsa                    4.0            
scikit-image           0.17.2         
scikit-learn           0.24.2         
scipy                  1.6.3          
seaborn                0.10.0         
Send2Trash             1.5.0          
sentencepiece          0.1.85         
seqeval                1.2.2          
setuptools             56.2.0         
Shapely                1.7.1          
shellcheck-py          0.7.1.1        
simplegeneric          0.8.1          
six                    1.15.0         
sklearn                0.0            
smmap                  3.0.5          
snowballstemmer        2.0.0          
SoundFile              0.10.3.post1   
tabulate               0.8.3          
tb-nightly             1.15.0a20190801
tb-paddle              0.3.6          
tensorboard            2.1.0          
tensorboardX           1.8            
termcolor              1.1.0          
terminado              0.8.2          
testpath               0.4.2          
threadpoolctl          2.1.0          
tifffile               2021.7.2       
toml                   0.10.0         
tornado                5.1.1          
tqdm                   4.36.1         
traitlets              4.3.3          
typed-ast              1.4.1          
ujson                  1.35           
urllib3                1.25.6         
virtualenv             16.7.9         
visualdl               2.2.0          
wcwidth                0.1.7          
webencodings           0.5.1          
Werkzeug               0.16.0         
wheel                  0.36.2         
wrapt                  1.12.1         
xarray                 0.16.2         
xgboost                1.3.3          
xlrd                   1.2.0          
yapf                   0.26.0         
zipp                   0.6.0

**Comment by LinXin04** [comment]
必须得下载，不然会报错。

shapely
scikit-image==0.17.2
imgaug==0.4.0
pyclipper
lmdb
tqdm
numpy
visualdl
python-Levenshtein
opencv-contrib-python==4.2.0.32
opencv-python-headless

pip install paddlehub==2.0.4
pip install paddlenlp==2.0.0rc7
pip install paddleocr==2.0.4
pip install paddlepaddle-gpu==2.0.2.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

即使这几个paddle包按照你的版本，还是报错：


OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:255)
--
[operator < gaussian_random > error]
main process return code: 1
not found core file

**Comment by ioracion** [comment]
这,,,,要不重开一个项目？可能环境配置已经乱了
ps. 我的项目框架是2.0.2版本的

**Comment by LinXin04** [comment]
没有用，重启了还换了GPU镜像，都是报错
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)
