### ISSUE TITLE
单机多卡报错: ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.

### ISSUE THREAD

**Issue by fxfviolet** [PaddlePaddle/PaddleOCR#3394]
单机多卡运行，安装了nccl，又报以下错误，不知道怎么解决，谢谢啦！

W0721 18:25:40.236928  6826 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:36250 failed 1 times with reason: Connection refused retry after 0.5 seconds
W0721 18:25:40.737262  6826 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:36250 failed 2 times with reason: Connection refused retry after 1 seconds
INFO 2021-07-21 18:25:47,709 launch_utils.py:327] terminate all the procs
ERROR 2021-07-21 18:25:47,709 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
INFO 2021-07-21 18:25:50,714 launch_utils.py:327] terminate all the procs

**Comment by tink2123** [comment]
请查看log中的具体报错，另外请验证环境内是否正确安装ncvv，多卡通信是否无误。

安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()
如果出现PaddlePaddle is installed successfully!，说明您已成功安装。

**Comment by cqray1990** [comment]
@tink2123 我的安装成功了Running verify PaddlePaddle program ... 
W0807 20:17:26.232933 16525 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.0
W0807 20:17:26.282476 16525 device_context.cc:372] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
W0807 20:17:28.995244 16525 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0807 20:17:28.995271 16525 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0807 20:17:30.893250 16525 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

但还是出错
[2021/08/07 20:00:24] root INFO: During the training process, after the 0th iteration, an evaluation is run every 400 iterations
[2021/08/07 20:00:24] root INFO: Initialize indexs of datasets:/archive/pubtabnet/pubtabnet/PubTabNet_train.jsonl
INFO 2021-08-07 20:01:03,416 launch_utils.py:307] terminate all the procs
ERROR 2021-08-07 20:01:03,610 launch_utils.py:545] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-07 20:01:06,612 launch_utils.py:307] terminate all the procs

**Comment by jedibobo** [comment]
同问，有解决方法吗？我是python -m paddle.distributed.launch --gpus=0,1  ./test.py    

环境测试也没问题
