### ISSUE TITLE
单机的GPU训练文字识别是什么指令呢？

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3395]
AttributeError: module 'paddle' has no attribute 'batch'

**Comment by tink2123** [comment]
请确认paddle版本是否是2.1.0

**Comment by LinXin04** [comment]
Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddle==2.1.0
ERROR: No matching distribution found for paddle==2.1.0

**Comment by tink2123** [comment]
安装命令：python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

具体请参考官方安装文档 ：https://www.paddlepaddle.org.cn/

**Comment by LinXin04** [comment]
我用的是cuda10.2版本，
请问paddle和paddlepaddle-gpu的版本分别是啥呢？
pip install paddle==1.0.2 -i https://mirror.baidu.com/pypi/simple
pip install paddlepaddle-gpu==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by LinXin04** [comment]
nvcc版本

nvcc: NVIDIA (R) Cuda compiler driver
--
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
