### ISSUE TITLE
识别模型训练集问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3397]
您好，我想做生僻字识别优化。需要增加生僻字训练数据，但生僻字缺乏语料用于合成数据。现在只能随机使用生僻字合成语料，但这样的一条语料语句是没有任何逻辑没有意义的一句话，使用生僻字随机堆成的。请问这样的语料合成的数据能进行训练吗，对识别有影响吗？

**Comment by WenmuZhou** [comment]
可以训练，效果也有，但是没组合成语义的效果好

**Comment by ziyaxuanyi** [comment]
那有什么办法可以解决生僻字语料数据不足的问题吗？

**Comment by WenmuZhou** [comment]
attention对生僻字好一点

**Comment by WenmuZhou** [comment]
生僻字可以用我们新添加的CenterLoss, 具体见这个配置文件https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_enhanced_ctc_loss.yml
