### ISSUE TITLE
识别英文出错

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleOCR#3398]
图片以及命令如下：
### 图片
![buyer 1](https://user-images.githubusercontent.com/44261675/126593877-b84a96ce-ef03-4399-8482-089922b0e085.jpg)

### 命令
```python
ocr = PaddleOCR(lang="en")

img = cv2.imread(img_path)
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
res = ocr.ocr(img,det=False)
```
### 结果
```
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/yuankaizou/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/Users/yuankaizou/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/yuankaizou/.paddleocr/2.0/rec/en', use_angle_cls=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)

[('jvttlyjphsovskpunjvtwhuFsptpAlk', 0.99078065)]
```

在 lang = "ch" 时，结果是正常的，但是识别不了空格，
```
[('COMMERCIALHOLDINGCOMPANYLIMITED', 0.9987323)]
```
请问如何识别出此图中的空格。(无论lang 是 cn 还是 en 皆可，或者有什么预处理上的建议吗)
多谢。

### 版本
paddleocr             2.0.2

**Comment by ioracion** [comment]
造数据微调模型

**Comment by zouxiaoshi** [comment]
> 造数据微调模型

感觉不该是这样的效果，理论上，lang=en时，比ch， 在识别英文上要强不少才对。

**Comment by zouxiaoshi** [comment]
在 图片为 
![price](https://user-images.githubusercontent.com/44261675/126595664-015ee10a-556a-4e63-a372-7d55ea38d337.jpg)
时 直接报错
```python
~/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py in decode(self, text_index, text_prob, is_remove_duplicate)
     77                             batch_idx][idx]:
     78                         continue
---> 79                 char_list.append(self.character[int(text_index[batch_idx][
     80                     idx])])
     81                 if text_prob is not None:

IndexError: list index out of range
```

**Comment by xiangfeidecao** [comment]
> > 造数据微调模型
> 
> 感觉不该是这样的效果，理论上，lang=en时，比ch， 在识别英文上要强不少才对。

请问，为什么要转RGB？你把RGB显示看看。

**Comment by zouxiaoshi** [comment]
> > > 造数据微调模型
> > 
> > 
> > 感觉不该是这样的效果，理论上，lang=en时，比ch， 在识别英文上要强不少才对。
> 
> 请问，为什么要转RGB？你把RGB显示看看。

BGR格式也是一样的结果。

**Comment by ioracion** [comment]
> 在 图片为
> ![price](https://user-images.githubusercontent.com/44261675/126595664-015ee10a-556a-4e63-a372-7d55ea38d337.jpg)
> 时 直接报错
> 
> ```python
> ~/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py in decode(self, text_index, text_prob, is_remove_duplicate)
>      77                             batch_idx][idx]:
>      78                         continue
> ---> 79                 char_list.append(self.character[int(text_index[batch_idx][
>      80                     idx])])
>      81                 if text_prob is not None:
> 
> IndexError: list index out of range
> ```

这个错大概率是没识别出来。。（就是说模型不行

**Comment by zouxiaoshi** [comment]
> > 在 图片为
> > ![price](https://user-images.githubusercontent.com/44261675/126595664-015ee10a-556a-4e63-a372-7d55ea38d337.jpg)
> > 时 直接报错
> > ```python
> > ~/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py in decode(self, text_index, text_prob, is_remove_duplicate)
> >      77                             batch_idx][idx]:
> >      78                         continue
> > ---> 79                 char_list.append(self.character[int(text_index[batch_idx][
> >      80                     idx])])
> >      81                 if text_prob is not None:
> > 
> > IndexError: list index out of range
> > ```
> 
> 这个错大概率是没识别出来。。（就是说模型不行

感觉应该是 字典与模型不匹配，要么字典没加载对。。要么模型没加载对。。

**Comment by ioracion** [comment]
你这个CNY的可以加规则判断，COMMERCIAL这个找找英文文本分词之类的库吧

**Comment by WenmuZhou** [comment]
use_space_char=true看看

**Comment by zouxiaoshi** [comment]
> use_space_char=true看看

用了，我看了下，它默认就是use_space_char=True.

以免是模型问题，我把模型文件删了，然后又重新下载，命令如下，
从里面的内容来看，加载的字典以及下载的模型是没有问题的，不知道为什么识别效果上很怪异。
```bash
ocr = PaddleOCR(lang="en",use_space_char=True)

Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/yuankaizou/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/Users/yuankaizou/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/yuankaizou/.paddleocr/2.0/rec/en', use_angle_cls=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_number_mobile_v2.0_rec_infer.tar to /Users/yuankaizou/.paddleocr/2.0/rec/en/en_number_mobile_v2.0_rec_infer.tar
```

**Comment by zouxiaoshi** [comment]
> 你这个CNY的可以加规则判断，COMMERCIAL这个找找英文文本分词之类的库吧

好的，准备用jieba 试试。多谢。

**Comment by WenmuZhou** [comment]
很奇怪了，我找同事确认下

**Comment by tink2123** [comment]
我这边自测的预测结果：

![image](https://user-images.githubusercontent.com/31891223/127469453-4b301674-caa2-4e0b-9da4-368185b17c1f.png)


E0729 17:38:11.888267 242671040 analysis_config.cc:81] Please compile with gpu to EnableGpu()
---    Fused 0 subgraphs into layer_norm op.
[2021/07/29 17:38:12] root INFO: **********/Users/yinxiaoting/Desktop/en_space.jpg**********
[2021/07/29 17:38:12] root INFO: (0.98161834, 'CNY6,350.00')


可以尝试安装 paddleocr==2.0.6  版本，重新预测看看，注意清除之前下载过的模型

**Comment by tink2123** [comment]
> 请问如何识别出此图中的空格。(无论lang 是 cn 还是 en 皆可，或者有什么预处理上的建议吗)
多谢。

边缘过于紧致的文本框，会影响空格的预测，如果这个结果是检测得到的，建议添加膨胀扩大检测框，可以提升识别效果。

**Comment by zouxiaoshi** [comment]
> > 请问如何识别出此图中的空格。(无论lang 是 cn 还是 en 皆可，或者有什么预处理上的建议吗)
> > 多谢。
> 
> 边缘过于紧致的文本框，会影响空格的预测，如果这个结果是检测得到的，建议添加膨胀扩大检测框，可以提升识别效果。

谢谢。 
paddleocr==2.0.6 版本可正常使用。
扩大文本框区域后，空格效果有所提升，多谢。

**Comment by zouxiaoshi** [comment]
> 你这个CNY的可以加规则判断，COMMERCIAL这个找找英文文本分词之类的库吧

网上找了找，wordninja 感觉应该是效率最高，而且效果还不错的。
只不过需要手动添加词库。
