### ISSUE TITLE
PaddleOCRLabel启动错误

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3401]
![EW@9~BTXLTK%E9P~J_B`S{L](https://user-images.githubusercontent.com/65577659/126610529-571ccd58-264d-4d47-b32a-8ebef3b1b4fa.png)
![image](https://user-images.githubusercontent.com/65577659/126610553-f8ed7e96-abbd-4908-8e4f-447c955fff04.png)
本机window环境下装完paddle,想使用PaddleOCRLabel 但运行起不来

**Comment by xiangfeidecao** [comment]
可能，路径中有中文。

**Comment by lin-0015** [comment]
> 可能，路径中有中文。

是的,还与python版本问题有关系 ,已解决 谢谢你!
