### ISSUE TITLE
增加新字到字典末尾

### ISSUE THREAD

**Issue by hqx11** [PaddlePaddle/PaddleOCR#3405]
请问我想增加新的字到字典末尾，准备了包含新字的数据集，用通用文字识别模型作为预训练模型，可以吗？
是不是需要用（大量的）旧数据和新数据一起训练？还是只需要新数据的数据集呢

**Comment by ioracion** [comment]
> 用通用文字识别模型作为预训练模型，可以吗？

可。

> 是不是需要用（大量的）旧数据和新数据一起训练？

要的，不然之前学的东西会忘记，只用新数据不中。
