### ISSUE TITLE
请问我评估det_r50_vd_db.yml模型的时候出现了以下问题是为什么呢  

### ISSUE THREAD

**Issue by Jane-pyh** [PaddlePaddle/PaddleOCR#3409]
评估命令：
python3 tools/eval.py -c configs/det/det_r50_vd_db.yml -o Global.checkpoints="{path/to/weights}/best_accuracy" PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5

报错：

  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 1, column 18:
    {path/to/weights}/best_accuracy
                     ^

**Comment by ioracion** [comment]
"{path/to/weights}/best_accuracy" 里的 {path/to/weights} 要替换成你本地的路径

**Comment by Jane-pyh** [comment]
> "[路径/到/重量]/best_accuracy"[路径/到/重量]表示"路径/到/重量"

你好，这应该是哪个文件路径呢？

测试的时候改成output/det_db文件下：python3 tools/infer_det.py -c configs/det/det_r50_vd_db.yml -o Global.infer_img="./doc/imgs_en/img_10.jpg" Global.pretrained_model="./output/det_db/best_accuracy" 

报错：AssertionError: key pretrained_model not in sub_keys: {'debug': False, 'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 100, 'log_smooth_window': 20, 'print_batch_step': 20, 'save_model_dir': './output/det_db/', 'save_epoch_step': 20, 'eval_batch_step': [0, 50], 'train_batch_size_per_card': 8, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': './configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': './pretrain_models/ResNet50_vd_ssld_pretrained/', 'save_res_path': './output/det_db/predicts_db.txt', 'checkpoints': None, 'save_inference_dir': None, 'infer_img': './doc/imgs_en/img_10.jpg'}, please check your running command.

**Comment by ioracion** [comment]
是你训练模型的路径（非推理模型），你再加个这个参数试试呢 Global.load_static_weights=false

**Comment by Jane-pyh** [comment]
你好，加了这个参数，训练还是报上面这个错

**Comment by Jane-pyh** [comment]
加了这个参数测试还是报同样的错误
