### ISSUE TITLE
PGNet训练自己模型yml参数配置

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3411]
transforms 对图片和标签进行变换的方法列表对训练有什么影响
![image](https://user-images.githubusercontent.com/65577659/126739747-08d0a423-5d81-4482-b0ce-7e0163831996.png)
训练参数报错 如何修改?

**Comment by littletomatodonkey** [comment]
看着是标注格不太对，解析的时候出现了问题，按照官网的数据格式再check下呢？

**Comment by lin-0015** [comment]
> check

imgs/000.jpg	[{"transcription": "4403071515304", "points": [[130, 315], [318, 245], [329, 299], [143, 352]], "difficult": false}]
是这样的呐 我原先尝试下面的格式也不行:
imgs/000.jpg	[{"transcription":"4403071515304","points":[[132.6242774566474,310.528901734104],[321.0,244.0],[342.9088293999477,296.8771311798859],[144.53310685659514,363.4060329139899]],"difficult":false}]
使用PPOCRLabel 手动修改确认一下格式就变成上面的格式了

**Comment by littletomatodonkey** [comment]
PGNet目前还是只支持14点标注哈

**Comment by lin-0015** [comment]
> PGNet目前还是只支持14点标注哈

能不能指定下源码
修改下一下标注点的位数要求呢
