### ISSUE TITLE
有没有比较好的迁移训练方式

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleOCR#3413]
目前提供的通用识别模型识别上存在以下问题1 汉字字典涵盖范围小 2 对于卡证上数字英文识别能力较差，目前手上数据少，更改汉字字典范围用自有数据进行训练后发现模型远比原通用识别模型效果差，泛华能力差(仅数字和英文这类不需要充足样本的获得了良好的效果)，请问有没有比较好的迁移训练方式，能够在较少数据的情况下基于通用预训练模型获得较好的效果

**Comment by littletomatodonkey** [comment]
1. 如果数据比较少的话，不建议更改字典，否则fc需要重新学习，收敛成本较高
2. 目前应该已经提供了英文模型，可以试一下，数据太少的话，垂类场景的精度确实会有问题
3. 可以试一下百度提供的商业api接口看下效果

**Comment by xiangfeidecao** [comment]
楼主解决了吗？我感觉这个预训练模型和官方推理模型差别很大，模型大小和模型速度都差两倍。效果好了速度又跟不上去。
