### ISSUE TITLE
对于拥挤的字符，稍微拉伸一点，但怎么判断字拥挤情况呢

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3415]

**Comment by littletomatodonkey** [comment]
如果是比较特定的场景，可以试着用连通区域的方法去大概看下有多少个字，然后根据图像长度判断是否拥挤，但是这种场景更建议在训练的时候直接对原始图片进行长度拉伸压缩变换

**Comment by cqray1990** [comment]
拉伸变换，但是实际测试的时候有的字拥挤，有的正常，这还是要去判断什么时候该去拉伸阿
