### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3420]
加入自己的数据训练，acc到0.79，loss到1.35后，训练很久loss不在下降，acc也不提升了，请问可能是什么原因，是已经收敛了吗？

**Comment by ioracion** [comment]
如果是用轻量模型的话，换通用模型试试，我换了acc提升到90+

**Comment by ziyaxuanyi** [comment]
通用模型太大了，就是要求轻量模型

**Comment by ioracion** [comment]
难啊兄弟，官方训练的这个轻量acc指标最好也才65。。上复杂模型+搞张GPU才是王道- -

**Comment by tink2123** [comment]
丰富一下训练数据，尽量贴近真实场景，添加数据增广或者蒸馏策略试试

**Comment by ziyaxuanyi** [comment]
> 难啊兄弟，官方训练的这个轻量acc指标最好也才65。。上复杂模型+搞张GPU才是王道- -

可能要部署移动端，模型必须小

**Comment by ziyaxuanyi** [comment]
> 丰富一下训练数据，尽量贴近真实场景，添加数据增广或者蒸馏策略试试

发现长文本识别不错，但短文本识别不佳，文本长度小于6的基本识别效果很差，检查了一下数据集，发现没有文本长度小于6的样本。只要文本长度超过6效果还可以，请问这正常吗？是否需要增加文本长度小于6的样本训练？
