### ISSUE TITLE
DBNet模型检测设置的位置

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#3421]
请问在 configs/det/det_r50_vd_db.yml中这个config文件中image_shape : [736, 1280]的数值是随便设置的吗，还是根据什么理论呢？

**Comment by tink2123** [comment]
这个是icdar2015数据的shape

**Comment by HongChow** [comment]
> 这个是icdar2015数据的shape

shape都是固定的？ 如果数据集shape 不一样的需要怎么做能提高检测率？

**Comment by Dandelion111** [comment]
> > 这个是icdar2015数据的shape
> 
> shape都是固定的？ 如果数据集shape 不一样的需要怎么做能提高检测率？

请问大佬问题解决了吗？
