### ISSUE TITLE
PGNet训练模型报错

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3423]
![image](https://user-images.githubusercontent.com/65577659/126923356-adcbb4d5-2a05-434a-b7ed-f0e6f728c9d7.png)
使用官方数据官方数据
还更改yml文件中:
![image](https://user-images.githubusercontent.com/65577659/126923913-df3f0484-8940-40a6-8555-4687d7d591d0.png)

**Comment by tink2123** [comment]
PGDataSet 是一个特殊的数据读取类，不要修改成 SimpleDataSet

**Comment by lin-0015** [comment]
> PGDataSet 是一个特殊的数据读取类，不要修改成 SimpleDataSet
但是会报错，说找不到文件？
肿么办？

**Comment by lin-0015** [comment]
> PGDataSet 是一个特殊的数据读取类，不要修改成 SimpleDataSet

![image](https://user-images.githubusercontent.com/65577659/126974048-895749bf-bc34-4bb5-bf39-a2f8c8185a91.png)
这种读取方式找不到文件.......

**Comment by LDOUBLEV** [comment]
你的代码比较久了，更新下代码吧
