### ISSUE TITLE
 训练方向分类器的问题：Tensor holds the wrong type, it holds int, but desires to be int64_t.

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleOCR#3427]
在训练PPOCR的方向分类器时，出现了** Tensor holds the wrong type, it holds int, but desires to be int64_t.**错误。错误原因大概是Tensor的数据类型错误，想要的是int64，而不是int。但是，我不知道要从何处去改，那位哥哥姐姐知道，请赐教下。不胜感激！

**Comment by tink2123** [comment]
可以贴一下完整的报错信息，看下具体的报错位置，把对应的数据类型修改成 int64 即可

**Comment by wu-yakun** [comment]
感谢，我把损失函数的数据类型修改为int64就解决问题了。
