### ISSUE TITLE
Style-Text 效果好差

### ISSUE THREAD

**Issue by hqx11** [PaddlePaddle/PaddleOCR#3428]
如题，按[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/StyleText/README_ch.md)说明进行测试，抽取背景效果差，是什么原因呢？效果如下图

![1](https://user-images.githubusercontent.com/12028465/126928197-1c374fe2-2af3-448c-b546-8e141eac5bbe.png)  ![fake_bg-1](https://user-images.githubusercontent.com/12028465/126928198-cdc10e5d-c6d7-4fd7-b162-30ff0580a3e3.jpg)  ![fake_fusion-1](https://user-images.githubusercontent.com/12028465/126928200-cea90671-ac41-4830-8428-6a6cc6e598b9.jpg) ![fake_text-1](https://user-images.githubusercontent.com/12028465/126928202-a95da7fe-0efa-434c-9421-4b44bc7f60e0.jpg)

![2](https://user-images.githubusercontent.com/12028465/126928146-64a62caf-7f1b-4b64-8655-48179d5046e2.png) ![fake_bg-2](https://user-images.githubusercontent.com/12028465/126928152-45efd9ad-7ce6-4c24-a3b5-ce54794f029e.jpg) ![fake_fusion-2](https://user-images.githubusercontent.com/12028465/126928155-0cf49e14-5fdb-4520-b5a7-1580b2175ba5.jpg) ![fake_text-2](https://user-images.githubusercontent.com/12028465/126928159-b3956b91-bd8e-4b02-979f-7fb89cc5212a.jpg)

![3](https://user-images.githubusercontent.com/12028465/126928475-0c1ca026-2d46-451b-b6d6-9da5cba8594d.png) ![fake_bg-3](https://user-images.githubusercontent.com/12028465/126928476-46cd385b-c388-45c1-bc58-78a74ab25f9f.jpg) ![fake_fusion-3](https://user-images.githubusercontent.com/12028465/126928481-d562a2d0-1e6f-4c2d-9fe2-bd40e2f87186.jpg) ![fake_text-3](https://user-images.githubusercontent.com/12028465/126928484-21e7a994-f860-4db7-823d-ff55cd3a443e.jpg)

![4](https://user-images.githubusercontent.com/12028465/126928521-ce5c2a92-9016-49cb-a795-b63b95cb7130.png) ![fake_bg-4](https://user-images.githubusercontent.com/12028465/126928525-1adf0d14-f264-4ce4-8265-ac1461037481.jpg) ![fake_fusion-4](https://user-images.githubusercontent.com/12028465/126928526-c9f41be5-7700-4540-a7d1-004fa2b33cd4.jpg)  ![fake_text-4](https://user-images.githubusercontent.com/12028465/126928527-348fb4a2-5c71-488e-a1b6-1fa645be056d.jpg)

![5](https://user-images.githubusercontent.com/12028465/126928550-b9effa60-79a7-4d01-b725-ae45f82417c0.png) ![fake_bg-5](https://user-images.githubusercontent.com/12028465/126928556-f029697f-9f8d-4f41-ad5c-018b5b0a693c.jpg)  ![fake_fusion-5](https://user-images.githubusercontent.com/12028465/126928558-3d4dc143-4613-4f38-a51e-55109dc4dc77.jpg)  ![fake_text-5](https://user-images.githubusercontent.com/12028465/126928559-6ffa8f85-a799-4b77-991e-39447242e6ad.jpg)

**Comment by ioracion** [comment]
+1，改用text_renderer了

**Comment by weisy11** [comment]
嗯嗯，目前边距比较小的图片效果确实不大好，相关更新已经在计划中了。

**Comment by ddz-mark** [comment]
大佬，那你现在用的什么工具提取背景的？我也是用StyleText提取背景，发现效果太差
