### ISSUE TITLE
文字检测上如何进行少数据的训练？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleOCR#3429]
目前数据集比较少，大概只有30-40张，如何在文字检测上进行少数据的训练？如冻结前面若干层、使用目前开源的已经训练好的模型进行迁移学习？另外，目前文字检测上使用的主要的是DB算法，训练时有哪些地方需要多加注意呢？

**Comment by tink2123** [comment]
需要冻结的那部分网络的输出加下 out.stop_gradient = True 就可以了

**Comment by hhhhhhogan** [comment]
> 需要冻结的那部分网络的输出加下 out.stop_gradient = True 就可以了

具体是在哪里加呢？

**Comment by hhhhhhogan** [comment]
具体是在哪里加呢？
















在 2021-07-26 17:31:08，"xiaoting" ***@***.***> 写道：

需要冻结的那部分网络的输出加下 out.stop_gradient = True 就可以了
