### ISSUE TITLE
对于长文本如何识别？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3431]

**Comment by tink2123** [comment]
请详细描述下你的问题，长文本和短文本的识别命令是一样的。

**Comment by cqray1990** [comment]
@tink2123 就是对于长文本识别效果不怎么好，如果检测出来一行很长的大概有４０，５０个字，会漏，也会识别错

**Comment by tink2123** [comment]
方便贴一个bad case看下吗～

**Comment by cqray1990** [comment]
![imgag](https://user-images.githubusercontent.com/32585434/127839466-e9d2dd21-d99f-4ddb-bd89-7dc278acc14f.jpg)

**Comment by cqray1990** [comment]
@tink2123
