### ISSUE TITLE
paddle查看cuda 和cudnn 版本api是否存在问题哈？

### ISSUE THREAD

**Issue by zhang-deep** [PaddlePaddle/PaddleOCR#3433]
![image](https://user-images.githubusercontent.com/62748383/127001015-f665c364-2207-4e0a-88de-ec7fdcf871ea.png)
![image](https://user-images.githubusercontent.com/62748383/127001315-74814723-6a8b-44dd-b868-ae281be0d0c2.png)
利用torch查看cudnn版本 和 利用paddle查看cudnn版本 不一致，请问这是为什么？

**Comment by WenmuZhou** [comment]
torch是自带cudnn的，paddle用的系统里的
