### ISSUE TITLE
Load symbol MKL_Free_Buffers failed

### ISSUE THREAD

**Issue by zhenglihui007** [PaddlePaddle/PaddleOCR#3436]
paddleocr:2.1
paddle:cpu2.1
预测总是失败，提示Load symbol MKL_Free_Buffers failed

**Comment by WenmuZhou** [comment]
你的机器上安装有mkl了吗

**Comment by zhenglihui007** [comment]
> 你的机器上安装了mkl

安装了，也是不起作用，还是说只能用GPU版本的？我现在都是用paddle1.8版本的，想试下新版本，使用起来好多问题啊

**Comment by WenmuZhou** [comment]
先关闭mkl使用吧
