### ISSUE TITLE
关于paddleocr预分配显存

### ISSUE THREAD

**Issue by rainmakerMa** [PaddlePaddle/PaddleOCR#3437]
请问 paddleocr内部 是怎么初始化显存分配的，
config.enable_use_gpu(args.gpu_mem, 0) 这个参数有起到实质的控制作用么，
实际实验发现，这个值如果设置的超出显卡显存，只是会提示分配了过多显存，但还是会正常运行；
这个值如果设置的很小很小，似乎不产生任何影响。

**Comment by WenmuZhou** [comment]
这个只是初始化分配的gpu显存，如果如要更多的显存还是回去申请的

**Comment by rainmakerMa** [comment]
> 这个只是初始化分配的gpu显存，如果如要更多的显存还是回去申请的

推理部分的显存是否有参数设置上限限制？
如果不作限制，是否会像t早期tf那样默认把整块卡的显存占满，导致oom的错误

**Comment by WenmuZhou** [comment]
不会限制，只会申请需要的显存，不会占满整张卡的
