### ISSUE TITLE
关于文本检测方法 训练的验证结果 和 独立测试结果偏差的问题

### ISSUE THREAD

**Issue by tairen99** [PaddlePaddle/PaddleOCR#3444]
PaddleOCR好！

我采用 文本检测方法：DB， EAST， 和SAST对我的数据进行训练。在训练结束后，我采用另外一套独立的数据对这三种方法进行独立测试。它们结果如下：

在训练验证阶段，对 DB， EAST，和SAST，我得到了以下的训练验证结果：
 方法 ：     H-mean
    DB：    0.69      (训练了 361 epochs， 共计2340张图片,每张图片包含文字数目>200）
EAST：    0.86      (训练了 184 epochs，共计2340张图片,每张图片包含文字数目>200)
SAST：    0.89      (训练了 217 epochs，共计2340张图片,每张图片包含文字数目>200)

可是当我用独立的测试数据的时候，我得到了如下的结果：
 方法 ：     H-mean
    DB：    0.92  （520 张图片）
EAST：    0.89  （520 张图片）
SAST：    0.84  （520 张图片）

我不知道为什么训练的时候，SAST得到了最好的验证结果，但是 针对独立数据测试的时候，结果却不好。请问这大概是什么原因呢？ 是训练 epochs 不够多，还是训练的数据不够多呢？ 还是两者都有？

如果是 epochs 不够多，有没有一个根据图片多少，来决定多少epochs的方法，还是看训练的 log分析？

如果是图片不够的话，针对这三种不同的方法，大概需要多少图片？

先谢谢！

**Comment by littletomatodonkey** [comment]
这块可能是因为数据集有偏导致的，建议用最终需要检验的数据作为验证集

**Comment by tairen99** [comment]
Hi @littletomatodonkey,

   谢谢你的答复。好像可以这样尝试一下，不过如果检验数据很多的话，训练很费时间。
