### ISSUE TITLE
OcrResultModel中的wordIndex具体含义是什么？

### ISSUE THREAD

**Issue by private1215** [PaddlePaddle/PaddleOCR#3445]
识别图片过程中调用了Predictor中的postprocess获取的结果转成了json字符串，获取结果如下：
{"confidence":0.9617134,"label":"334","points":[{"x":30,"y":44},{"x":351,"y":44},{"x":351,"y":197},{"x":30,"y":197}],"wordIndex":[93,93,631]},"wordIndex":[93,93,631]},{"confidence":0.91871727,"label":"下午","points":[{"x":348,"y":97},{"x":423,"y":97},{"x":423,"y":137},{"x":348,"y":137}],"wordIndex":[172,1674]}

**Comment by littletomatodonkey** [comment]
应该是ctc decode出来的 时间步长信息，哪些是有真实含义的字符，可以不用关注哈

**Comment by private1215** [comment]
好的，多谢啦兄弟
