### ISSUE TITLE
paddleocr的GPU量化与tensorrt加速

### ISSUE THREAD

**Issue by 77h2l** [PaddlePaddle/PaddleOCR#3454]
请问paddleocr的模型，或者是paddle模型，后续在转tensorrt的时候是独立的么，还是已经内嵌在paddle引擎内部了？
因为注意到有参数可以配置是否使用trt和fp16模式

**Comment by littletomatodonkey** [comment]
目前来看，是嵌入在内部的，在预测的时候，只需要设置paddle的trt信息即可

**Comment by rainmakerMa** [comment]
> 目前来看，是嵌入在内部的，在预测的时候，只需要设置paddle的trt信息即可

那如果需要把paddle模型单独转tensorrt呢？怎么操作
