### ISSUE TITLE
识别模型问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3458]
请问，训练集文本的长度必须是1-25的各种长度都要有吗？我目前使用的数据集里面没有文本长度小于6的样本，最后训练出来的模型对长文本识别效果还行，但是对于文本长度小于6的识别效果特别差。这是什么原因？

**Comment by littletomatodonkey** [comment]
你好，为了确保对不同长度的文本识别效果都比较好，建议不同长度的训练数据都包含一些，因为短文本在识别的时候需要padding，所以其实如果没怎么见过短文本的话，是会稍有影响的

**Comment by mrlihellohorld** [comment]
那请问训练的时候数据集中字符长度怎么取呢，1-25都要有吗，比例怎么分配呢

**Comment by littletomatodonkey** [comment]
一般训练集包含短文本较多的话，预测长文本的话也是可以搞定的，建议包含长短都包括一些，按照实际情况来就好
