### ISSUE TITLE
关于PPOCR文本校正算法的疑问

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleOCR#3461]
PPOCR的文本检测算法是用来检测图片中的文本，若检测出的文本框是带角度的，则需要对文本框进行校正为水平状态。
疑问一：文本矫正算法在代码中的那个部分呢？

疑问二：用PPOCR检测多角度多方向的文本时，可以将检测结果以水平方式呈现吗？

**Comment by xiangfeidecao** [comment]
路过，检测输出的坐标点是最小外接矩形带角度的。好像分类之前在取img_crop时，做了仿射变换，这个图取出来就是正的水平的。看get_rotate_crop_image

**Comment by wu-yakun** [comment]
谢谢大佬，不过PPOCR的输出不带角度哦，

**Comment by wu-yakun** [comment]
大佬，是predict_system.py的输出不带角度，predict_det.py带角度。
