### ISSUE TITLE
模型finetune策略

### ISSUE THREAD

**Issue by SharonJin422** [PaddlePaddle/PaddleOCR#3464]
hello, 想请教一下如果我的数据类型比较多，合成数据包括：简单背景、复杂背景、艺术字体等，再加上真实场景的数据，
finetune的策略是
1. 串行：即现在百万级的简单背景数据上pre-train，再分别加入复杂背景、艺术字体、真实数据finetune三轮
2. 直接分两批：在所有的合成数据上pre-train，再加入真实数据finetune
3. 或者在简单背景数据上pre-train, 再把复杂背景、艺术字体、真实数据一次加入，分别按照1:1:1:1 finetune 一轮
请问理论上哪种策略会更好一点呢？

其实尝试过在简单数据上pretrain,然后先在真实数据上finetune,后来又加入复杂背景finetue两轮，发现对于真实数据验证集效果反而下降了

**Comment by MissPenguin** [comment]
如果分阶段训练，可以先全量，然后最后在真实数据上finetune；或者直接一起训练，注意真实数据的采样比例。具体的，还得看数据的实际情况，建议多跑些实验对比下结论比较可靠。
