### ISSUE TITLE
开启mkldnn时，PPOCRLabel自动预测出现乱码，漏检

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleOCR#3466]
版本信息
paddlepaddle 2.0.0 CPU版本
PaddleOCR-release-2.1
CPU i5-1035G1

根据Q1.1.10问题中修改参数enable_mkldnn 
self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=False, lang=lang,
                             enable_mkldnn=True)
未开启结果：
[('第一章', [[1803.0, 1514.0], [2533.0, 1514.0], [2533.0, 1760.0], [1803.0, 1760.0]], None, None, False), ('供应链战略规划', [[1276.0, 2007.0], [3066.0, 2007.0], [3066.0, 2222.0], [1276.0, 2222.0]], None, None, False)]
开启结果：
[('第一章', [[1803.0, 1514.0], [2533.0, 1514.0], [2533.0, 1760.0], [1803.0, 1760.0]], None, None, False)]

您好，想问下这种情况是某些设置没有配置正确的问题嘛？

**Comment by LDOUBLEV** [comment]
不是设置的问题，你更新到Paddle2.1版本试下，2.1上测试了没这个问题
或者你发一下你测试的图像

**Comment by Gmgge** [comment]
我更新了 Paddle2.1，可以正常加速使用了，可能是某个bug在新的版本被修复了，很感谢你的回复。
