### ISSUE TITLE
infer_rec结果错误

### ISSUE THREAD

**Issue by Lanme** [PaddlePaddle/PaddleOCR#3469]
我跑的一个手写模型，图片为(3,32,140)，第一条是对的“考器拜舒蚤”，但是转为export为infer之后就不行了
运行代码如下：
python3 tools/infer_rec.py -c configs/rec/rec_textline_handwritings.yml -o Global.pretrained_model=./output/rec_chinese_common_v2.0/latest Global.load_static_weights=false Global.infer_img=/mnt/jml/paddlepaddle/ppocr/handwritings/line_data/test/50000.jpg

> ...
> ...
> [2021/07/29 09:10:39] root INFO: load pretrained model from ['./output/rec_chinese_common_v2.0/best_accuracy']
> [2021/07/29 09:10:39] root INFO: infer_img: /mnt/jml/paddlepaddle/ppocr/handwritings/line_data/test/50000.jpg
> 1 512 1 35
> [2021/07/29 09:10:39] root INFO: 	 result: ('考器拜舒蚤', 0.99781495)
> [2021/07/29 09:10:39] root INFO: success!

python3 tools/export_model.py -c configs/rec/rec_textline_handwritings.yml -o Global.pretrained_model=./output/rec_chinese_common_v2.0/latest  Global.save_inference_dir=./inference/rec_chinese_common_v2.0/

> ...
> ...
> [2021/07/29 08:51:04] root INFO: inference model is saved to ./inference/rec_chinese_common_v2.0//inference

python3 tools/infer/predict_rec.py --image_dir="/mnt/jml/paddlepaddle/ppocr/handwritings/line_data/test/50000.jpg" --rec_model_dir="./inference/rec_chinese_common_v2.0/"

> ...
> ...
> [2021/07/29 09:03:00] root INFO: Predicts of /mnt/jml/paddlepaddle/ppocr/handwritings/line_data/test/50000.jpg:('关:汇与昏', 0.997746)
> [2021/07/29 09:03:00] root INFO: Total predict time for 1 images, cost: 1.439

**Comment by ioracion** [comment]
估计参数没对齐

**Comment by Lanme** [comment]
> 估计参数没对齐

这该怎么解决呀

**Comment by ioracion** [comment]
学会利用关键词搜索以往的[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/2470)
