### ISSUE TITLE
关于cpp_infer tensorrt推理

### ISSUE THREAD

**Issue by ycdhqzhiai** [PaddlePaddle/PaddleOCR#3470]
初步接触paddleocr，我看接口上有use_trt这个参数，我想问下，这个是否能在nvidia jetson 上运行。

https://github.com/PaddlePaddle/PaddleOCR/blob/25f30acb290439fb89947577c229165ab4a4afa0/deploy/cpp_infer/src/main.cpp#L61

**Comment by wangye707** [comment]
@ycdhqzhiai  TRT fp16推理仅支持jetson xavier AGX和NX。fp32所有jetson都支持。

**Comment by ycdhqzhiai** [comment]
@wangye707 非常感谢

**Comment by FangJingYunner** [comment]
帅哥，你的paddleocr是在哪个nvidia嵌入式端部署的呀？有试过nvidia xavier agx嘛？tensorrt推理速度怎么样呢？ @wangye707 @ycdhqzhiai
