### ISSUE TITLE
Eval阶段 RuntimeError: (Unavailable) Memory map failed when create shared memory.

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/PaddleOCR#3476]
eval model::  58%|█████▊    | 306/524 [01:30<02:16,  1.60it/s]
eval model::  59%|█████▊    | 307/524 [01:30<01:44,  2.08it/s]Process Process-34:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 472, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 463, in _worker_loop
    tensor_list = core._convert_to_tensor_list(batch)
RuntimeError: (Unavailable) Memory map failed when create shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:78)

Eval:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/test
    label_file_list: [./train_data/test/test_4.txt]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - E2ELabelEncodeTest:
      - E2EResizeForTest:
          max_side_len: 768
      - NormalizeImage:
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'shape', 'polys', 'texts', 'ignore_tags', 'img_id']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2

**Comment by lqniunjunlper** [comment]
--shm-size=201630439424

**Comment by LDOUBLEV** [comment]
在配置文件中Eval  loader的部分增加如下参数：
use_shared_memory:False
