### ISSUE TITLE
2.1训练出来的模型可以输出成1.1版本的预测模型吗？

### ISSUE THREAD

**Issue by kainer80** [PaddlePaddle/PaddleOCR#3477]
我们是在paddle2.1下做的训练，需要转换成以前版本的预测模型，直接在1.1的环境下转换可以吗？

**Comment by LDOUBLEV** [comment]
不行的，建议还是在Paddle2.1上导出预测模型，并且2.1的识别模型后处理逻辑和1.1的识别代码后处理逻辑有些不一样，即使转换成之前的预测模型，在1.1上也没法预测
