### ISSUE TITLE
CPU跑线程数设置

### ISSUE THREAD

**Issue by mxxlei** [PaddlePaddle/PaddleOCR#3478]
多核CPU，需要加速单个请求的响应速度，use_multiprocess无法做到，修改workers也不行，我用下面的配置，CPU只能跑10个线程执行识别，哪里修改呢？
`
{
    "modules_info": {
        "ocr_system": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": false
            },
            "predict_args": {
            }
        }
    },
    "port": 8868,
    "use_multiprocess": false,
    "workers": 48
}
`

![image](https://user-images.githubusercontent.com/9283254/127603485-6b9df7bb-658f-4543-9804-201f6f5257c3.png)

**Comment by LDOUBLEV** [comment]
你运行的是hub serving的例子？
设置CPU的线程数，可以修改这个参数；
https://github.com/PaddlePaddle/PaddleOCR/blob/25f30acb290439fb89947577c229165ab4a4afa0/tools/infer/utility.py#L101

**Comment by mxxlei** [comment]
感谢您的帮助，我设置了cpu_threads=48，运行时可以看到多核CPU都用到了，但是识别速度并没有明显的提高。还有其他的优化地方吗？ @LDOUBLEV 
![image](https://user-images.githubusercontent.com/9283254/127608574-87a93cb8-aec2-47e4-829d-35ab7dbe15e4.png)

**Comment by LDOUBLEV** [comment]
线程数量增加到一定程度后，加速增益趋于饱和
如果没有开启mkldnn的话，建议开启mkldnn，--enable_mkldnn=True
https://github.com/PaddlePaddle/PaddleOCR/blob/25f30acb290439fb89947577c229165ab4a4afa0/tools/infer/utility.py#L100
