### ISSUE TITLE
有没有成功编译PPOCRLabel成exe且正常使用的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleOCR#3479]
我想编译PPOCRLabel成exe，在windows 10上使用，编译得到的exe程序打开总会出现各种导包问题，有没有已经编译成功的，能提供一下吗？

**Comment by yeyupiaoling** [comment]
我已经有打包的了，这里提供给大家使用：https://download.csdn.net/download/qq_33200967/20719083

**Comment by MrCuiHao** [comment]
你是怎么打包的？我打包了2天都没成功，求打包详细教程，可以写一篇文章到CSDN分享出来吗？非常感谢

**Comment by liugj101** [comment]
怎么获得CSDN积分呢0.0
