### ISSUE TITLE
识别模型训练问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3480]
我发现在训练的时候，每隔5个iter，就会有一次训练耗费很长时间，准确来说是读取数据耗费很长时间，reader_cost特别大。中间的iter读数据就很快，训练速度很快。请问这正常吗？是什么原因了？

**Comment by MissPenguin** [comment]
应该是刚好一个epoch训完了，重新加载数据耗时比较多吧

**Comment by ziyaxuanyi** [comment]
> 应该是刚好一个epoch训完了，重新加载数据耗时比较多吧

并不是，我一个epoch有将近3000个iter，这是每隔5个iter就出现一次
