### ISSUE TITLE
PPOCRLabel不能启动，报OMP错误

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#3481]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
运行环境：  windows 10 64位，paddlepaddle-gpu==2.1.1 cudatoolkit=10.2

**Comment by Evezerest** [comment]
paddleocr可以正常预测吗？

**Comment by ronaldpan** [comment]
可以

**Comment by Evezerest** [comment]
应该是环境问题，可以搜索一下，参考https://www.codenong.com/cs110454017/
