### ISSUE TITLE
PGNet可以同时训练水平文字 和 垂直方向文字？

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/PaddleOCR#3484]
PGNet训练任意旋转角度的文字图片？
目前看对于水平识别较好，垂直识别很差！

**Comment by LDOUBLEV** [comment]
可以先看下是垂直文本是检测还是识别的问题；
检测部分需要考虑文字方向和坐标点处理（水平方向是文本从左到右）

**Comment by lqniunjunlper** [comment]
detection部分就比较差 recognition部分更不能看了。那对于非水平的文字，坐标如何处理？

**Comment by shuihsaiu** [comment]
请问垂直方向文字检测效果差的原因找到了么？
