### ISSUE TITLE
空格問題 - ppocr_keys_v1.txt

### ISSUE THREAD

**Issue by benechiu** [PaddlePaddle/PaddleOCR#3485]
在 configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml 內, character_dict_path: ppocr/utils/ppocr_keys_v1.txt 

字典(ppocr_keys_v1.txt) 內有6623字, 找不到空格

models 是 ch_ppocr_mobile_v2.0

python tools/infer/predict_system.py --image_dir=".\doc\imgs_en\img_12.jpg" --det_model_dir="./inference/det_db/" --rec_model_dir="./inference/rec_crnn/" --use_angle_cls=false --use_mp=True --total_process_num=6

結果可以支持空格 (字典沒有空格), 測試其他圖片, 對空格支持度不一致

如果想利用 ch_ppocr_mobile_v2.0_rec_train 作 空格 fine tune, 可否在ppocr_keys_v1.txt加上空格, 修改 configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml, 加上 pretrained_model, label_file_list?

![img_12](https://user-images.githubusercontent.com/6835856/127634025-1d440e51-9c4a-4347-9c47-69de09ae5075.jpg)

![test_2](https://user-images.githubusercontent.com/6835856/127637308-186ee20c-1ff3-42ac-b374-22330524f36c.jpg)

**Comment by ziyaxuanyi** [comment]
空格支持是直接在代码里面加的。在config文件中设置use_space_char: True，代码里面会在读取的字典里追加空格字符的，不需要在字典里添加。官方开源的ch_ppocr_mobile_v2.0_rec_train模型训练的config是打开了use_space_char: True的，是支持空格识别的
