### ISSUE TITLE
批量预测时 cudnn error  ，cuda cudnn版本都是按规范配置

### ISSUE THREAD

**Issue by zouwen198317** [PaddlePaddle/PaddleOCR#3489]
![9638500267befc041cd19704d541f87](https://user-images.githubusercontent.com/11547233/127732426-5bbb2308-3d68-4dd4-b213-e43b2db68f98.jpg)

**Comment by zouwen198317** [comment]
有时候跑了1万次，有时候跑 5000次，就出现这个，让后停了

**Comment by zouwen198317** [comment]
win10 64

**Comment by zouwen198317** [comment]
我显存是6g，不会是显存不足吧？

**Comment by Sariel2** [comment]
代码贴一下看看噻
