### ISSUE TITLE
识别模型backbone问题

### ISSUE THREAD

**Issue by Aiyoj** [PaddlePaddle/PaddleOCR#349]
rec_mobilenet_v3.py model_name="small“时代码如下：
![image](https://user-images.githubusercontent.com/28584450/87619211-43f92780-c74e-11ea-876c-87385d2201fc.png)
height缩小了16倍，首尾又分别缩小了2倍，整个过程缩小了64倍

**Comment by tink2123** [comment]
网络目前根据输入高度为32设计，在最后一层pooling之前高度缩小了32倍，因此最后一层pool后高度仍然为1。后面会考虑对高度64进行适配。

**Comment by Aiyoj** [comment]
> 网络目前根据输入高度为32设计，在最后一层pooling之前高度缩小了32倍，因此最后一层pool后高度仍然为1。后面会考虑对高度64进行适配。

@tink2123 也就是说在最后一层pool之前高度为1，pool之后高度还是1，只是对宽度缩小了一半吗

**Comment by Aiyoj** [comment]
> > 网络目前根据输入高度为32设计，在最后一层pooling之前高度缩小了32倍，因此最后一层pool后高度仍然为1。后面会考虑对高度64进行适配。
> 
> @tink2123 pytorch复现该网络时，高度为32时，经过最后一层pool后高度变成0了，所以提出该疑问

**Comment by tink2123** [comment]
> 也就是说在最后一层pool之前高度为1，pool之后高度还是1，只是对宽度缩小了一半吗

是的

与 torch 的表现不同的问题，我们调研一下

**Comment by Aiyoj** [comment]
@tink2123 mv3的large和small cfg里的stride参数（一个缩小8倍，一个缩小16倍）为啥没统一起来呢

**Comment by littletomatodonkey** [comment]
> @tink2123 mv3的large和small cfg里的stride参数（一个缩小8倍，一个缩小16倍）为啥没统一起来呢

您好，感谢您的反馈，之前没有使用mv3 large的backbone进行训练，所以没有注意到这个问题，我们会尽快修复这个问题，谢谢！ #356
