### ISSUE TITLE
请问如何用最新版本将检测和识别串联推理？

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#3491]
tools/infer/predict_system.py 可以串联推理，但是需要pdmodel和pdiparams文件，但是我训练的模型都是pdprarms文件没有什么pdmodel和pdiparams文件，请问我只有pdparams模型检测和识别的，能串联推理吗。pdmodel和pdiparams文件是不是以前静态图的权重文件，官方没有更新串联推理的模块呢？

**Comment by weekstudy** [comment]
我觉得应该可以，如果是DB检测是检测阶段，应该是把检测的输出，再输入到识别的模型里面进行识别，pdiparams文件可以用export_model.py文件转换，但是转换时需要paddle2.0.0版本

**Comment by WenmuZhou** [comment]
楼上是对的，导出一下模型就好了
