### ISSUE TITLE
PPOCRLabel检测的结果与predict_system的结果不一致

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#3492]
我在PPOCRLabel中调用了自己的模型，配置了参数，识别结果与predict_system的结果不一致。

**Comment by littletomatodonkey** [comment]
你好，可以先检查下超参数是否完全一致

**Comment by ronaldpan** [comment]
PPOCRLabel中      
`  self.ocr = PaddleOCR(
det_model_dir='H:/PaddleOCR/output/ch_db_mv3/',
det_db_thresh=0.7,
det_db_box_thresh=0.2,
det_db_unclip_ratio=1.2,
det_limit_side_len=1920,
det_limit_type=max,
rec_model_dir='H:/PaddleOCR/output/rec/36e01/',
rec_image_shape="3,32,160",
rec_char_type='ch',
max_text_length=5,
rec_char_dict_path='H:/PaddleOCR/ppocr/utils/ocr_dict_my.txt',
use_space_char=False,
cls_model_dir=None,
#cls=True, 
#det=True,
use_pdserving=False, use_angle_cls=False, use_gpu=False, lang="ch")`


predict_system的参数
`python tools/infer/predict_system.py --image_dir="./test/omr1.jpg" --det_model_dir="./output/ch_db_mv3/"  --rec_model_dir="./output/rec/36e01/" --cls_model_dir="" --use_angle_cls=False --use_space_char=False --det_db_thresh=0.7 --det_db_box_thresh=0.2 --det_db_unclip_ratio=1.2 --det_limit_side_len=1920 --det_limit_type=max --rec_image_shape=“3,32,160” --rec_char_type=“ch” --max_text_length=5 --rec_char_dict_path=“./ppocr/utils/ocr_dict_my.txt” --use_pdserving=False --use_gpu=False`

二者结果差别非常大。

**Comment by Actor12** [comment]
请问你解决了吗？我也遇到了用样的问题
