### ISSUE TITLE
检测模型训练报错

### ISSUE THREAD

**Issue by dajiew** [PaddlePaddle/PaddleOCR#3493]
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 47, in main
    dist.init_parallel_env()
  File "C:\Users\54565\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\distributed\parallel.py", line 192, in init_parallel_env
    core.NCCLParallelContext(strategy, place))
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'NCCLParallelContext'
INFO 2021-08-02 13:26:12,919 launch_utils.py:327] terminate all the procs
ERROR 2021-08-02 13:26:12,920 launch_utils.py:582] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2021-08-02 13:26:15,942 launch_utils.py:327] terminate all the procs

**Comment by littletomatodonkey** [comment]
nccl目前不支持windows平台，因此无法使用多卡，可以直接使用`python tools/train.py -c xxx`来跑单卡任务

**Comment by cqray1990** [comment]
@littletomatodonkey 我在linux训练也出现这个错误，nccl2.4.8 cuda10.0,cudnn,7.6

**Comment by littletomatodonkey** [comment]
你好，要不使用docker试下呢？看着是环境问题
