### ISSUE TITLE
单张图上多语种并存识别问题

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3494]
你好，我想问一下，当一张图片中共存多个语种（中、英、日等）时，看您的建议是做一个多语种分类，请问目前这种多语种分类技术有哪些呢？有咩有公开的开源工具呢？

**Comment by littletomatodonkey** [comment]
分类的话，目前直接使用图像分类套件PaddleClas就可以的，另外，公开数据集可以从mlt多语言数据集中去看下是否满足你的需求，也可以通过合成的方法生成一些多语言的数据集

**Comment by LinXin04** [comment]
分类的话样本应该是怎么样的呢？是单个词的图片，还是文件检测拿下来的那种几个词连在一起的呢？
