### ISSUE TITLE
PGNet+横排文字旋转之后label（坐标问题）如何设置

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/PaddleOCR#3495]
原图：
![image](https://user-images.githubusercontent.com/6329891/127819837-3560d2e6-8c2e-428a-ae52-8c468439b9c1.png)
transcription：测试一下
points：[[100,200],[300,200],[300,500],[100,500]]

顺时针旋转90度：
![image](https://user-images.githubusercontent.com/6329891/127819898-5aaa42a8-de9b-4b00-85a2-8937129bf75d.png)

180度：
![image](https://user-images.githubusercontent.com/6329891/127819992-9d96041c-e9f3-4ff2-9ea5-a9438c14e2a6.png)

270度：
![image](https://user-images.githubusercontent.com/6329891/127820006-b5c1ad5e-2958-4af2-95c0-799fb5aa8ec5.png)

**Comment by littletomatodonkey** [comment]
你好，从文字阅读顺序的左上角开始标注，顺时针标注即可哈
