### ISSUE TITLE
db_fpn.py中上采样后形状不一致，不能直接加

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3498]
经过卷积之后的in4和in5第三维的shape不成2倍关系，上采样相加报错
       in5 = self.in5_conv(c5)
        in4 = self.in4_conv(c4)
        in3 = self.in3_conv(c3)
        in2 = self.in2_conv(c2)
        print(in4.shape, in5.shape)   # [2, 256, 45, 80] [2, 256, 23, 40]
        print(in2.shape, in3.shape)  # [2, 256, 180, 320] [2, 256, 90, 160]
        out4 = in4 + F.upsample(in5, scale_factor=2, mode="nearest", align_mode=1)  # 1/16 
如何修改？

**Comment by littletomatodonkey** [comment]
你好，这块需要保证输入图像的长和宽都能够被32整除

**Comment by PhilCuriosity** [comment]
用代码检查了是32的倍数

> import os
> import cv2
> img_dir = 'print/train'
> for img_name in os.listdir(img_dir):
>     img_path = os.path.join(img_dir, img_name)
>     img = cv2.imread(img_path)
>     if img.shape[0] != 288 or img.shape[1] != 448:
>         print(img.shape[0], img.shape[1])
