### ISSUE TITLE
请问训练DBNet时有哪几个超参数需要着重调整呢？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleOCR#3499]
请问训练DBNet时有哪几个超参数需要着重调整呢？
我目前主要不知config配置文件yml中MakeBorderMap和MakeShrinkMap的参数shrink_ratio、 Head下的放大系数k、以及损失函数alpha、beta需要调整吗？以及调整的方向是如何的呢？

**Comment by LDOUBLEV** [comment]
> 我目前主要不知config配置文件yml中MakeBorderMap和MakeShrinkMap的参数shrink_ratio、 Head下的放大系数k、以及损失函数alpha、beta需要调整吗

这些参数默认即可，建议训练完后根据效果，调整后处理参数--det_db_thresh  --det_db_box_thresh  --det_db_unclip_ratio

**Comment by hhhhhhogan** [comment]
> > 我目前主要不知config配置文件yml中MakeBorderMap和MakeShrinkMap的参数shrink_ratio、 Head下的放大系数k、以及损失函数alpha、beta需要调整吗
> 
> 这些参数默认即可，建议训练完后根据效果，调整后处理参数--det_db_thresh --det_db_box_thresh --det_db_unclip_ratio

好的谢谢，就是训练的时候默认参数，然后推理的话就修改参数--det_db_thresh --det_db_box_thresh --det_db_unclip_ratio是吗？以及调整图片大小应该也可以提高准确率吧？
