### ISSUE TITLE
KeepKey创建运维指什么? 配置文件与inference模型配置文件utility不一致?

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3500]
1.yml中
转换 标签和图片的方法KeepKeys  创建数据运维指什么?
![image](https://user-images.githubusercontent.com/65577659/127825670-7cf038a8-098c-4518-82e9-bfab277a784f.png)
![image](https://user-images.githubusercontent.com/65577659/127825840-49553802-aa26-48e3-979d-fddb84f6e526.png)

为什么Train和Eval中keepkeys这差别较大呢?   

2.为什么不把配置统一一下,inference模型中又将默认配置文件写在utility中
utility中默认值:
![image](https://user-images.githubusercontent.com/65577659/127826010-e57095cb-f75b-4475-8aa7-96d0515db997.png)
文件.\ppocr\data\imaug\operators.py中默认值:
![image](https://user-images.githubusercontent.com/65577659/127826155-e1d73bc1-2314-416e-a3e3-3f707d719fe3.png)
限制的默认类型也由"min"变为了"max"

![image](https://user-images.githubusercontent.com/65577659/127826418-e52a47f0-33bb-4479-a247-04b7743a3880.png)
![image](https://user-images.githubusercontent.com/65577659/127826677-f421031f-5f21-425b-8849-33ec6dae13ca.png)
det_limit_side_len 与 det_db_unclip_ratio中的默认值,utility中 0.5,1.6;det配置文件中:0.6,1.5 是手误写错了还是别的原因????

**Comment by lin-0015** [comment]
郭若愚大佬小哥哥能否给我耐心细说说呢

**Comment by littletomatodonkey** [comment]
1. 在训练的时候，db会有3个loss，这块会有多个监督信号，keep keys就是拿到对应的输入和gt label监督信号
2. 检测在inference的时候，在这里，默认也是max：https://github.com/PaddlePaddle/PaddleOCR/blob/25f30acb290439fb89947577c229165ab4a4afa0/tools/infer/predict_det.py#L43
3. postprocess ymal文件的中的参数我们没来得及更新，感谢反馈，我们修复下~

**Comment by lin-0015** [comment]
好的谢谢郭兄~

> 1. 在训练的时候，db会有3个loss，这块会有多个监督信号，keep keys就是拿到对应的输入和gt label监督信号
> 2. 检测在inference的时候，在这里，默认也是max：https://github.com/PaddlePaddle/PaddleOCR/blob/25f30acb290439fb89947577c229165ab4a4afa0/tools/infer/predict_det.py#L43
> 3. postprocess ymal文件的中的参数我们没来得及更新，感谢反馈，我们修复下~
好的谢谢郭兄
