### ISSUE TITLE
中文OCR模型快速使用出错

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3501]
~/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
(1, 1, 512, 896)
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 203, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 158, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 90, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/phil/PaddleOCR/tools/infer/predict_det.py", line 183, in __call__
    preds['f_score'] = outputs[1]
IndexError: list index out of range

**Comment by littletomatodonkey** [comment]
你好，要不拉下最新代码看下呢？我这边测试没有问题，看着你的代码行数和最新代码对应的行数也不太一样

**Comment by PhilCuriosity** [comment]
行数的话，因为之前报错，我中间加了两行print。
