### ISSUE TITLE
style-text生成的fake_text很乱

### ISSUE THREAD

**Issue by WZMIAOMIAO** [PaddlePaddle/PaddleOCR#3502]
阅读完官方Style Text文档后，使用官方的demo正常，但测试自己的数据时生成的fake_text很乱。

style_image：
![487X_id_crop_10](https://user-images.githubusercontent.com/31005897/127847286-8472e4a1-f18b-47e4-94f9-df4286729bbc.jpg)

text_corpus： 57074270930576081X

生成的fake_text：
![fake_text](https://user-images.githubusercontent.com/31005897/127847425-bb30d5d2-e6a1-4ef6-9220-ec0fb373cd92.jpg)

使用指令：
```
python3 tools/synth_image.py -c configs/config.yml --style_image examples/style_images/style.jpg --text_corpus 57074270930576081X --language ch
```

请问这是什么问题啊？由于fake_text生成时一团糟，合成的数据就完全无法使用。

**Comment by littletomatodonkey** [comment]
你好，这个是由于之前训练的时候，没有此类身份证背景的图片，所以合成效果比较差哈

**Comment by WZMIAOMIAO** [comment]
所以，身份证的暂时用不了对吧

**Comment by littletomatodonkey** [comment]
是的，这个场景目前确实没有做适配

**Comment by WZMIAOMIAO** [comment]
好吧，谢谢
