### ISSUE TITLE
eval时报错

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3503]
评估阶段会报错，不是数据集和模型的问题，换了模型和数据集一样报错。
eval model::   0%|          | 0/12 [00:00<?, ?it/s]
eval model::   8%|▊         | 1/12 [00:00<00:03,  3.31it/s]
eval model::  17%|█▋        | 2/12 [00:00<00:02,  3.89it/s]
eval model::  25%|██▌       | 3/12 [00:00<00:02,  3.86it/s]
eval model::  33%|███▎      | 4/12 [00:01<00:02,  3.93it/s]
eval model::  42%|████▏     | 5/12 [00:01<00:01,  3.91it/s]
eval model::  50%|█████     | 6/12 [00:01<00:01,  3.93it/s]
eval model::  58%|█████▊    | 7/12 [00:01<00:01,  3.84it/s]
eval model::  67%|██████▋   | 8/12 [00:02<00:01,  3.98it/s]
eval model::  75%|███████▌  | 9/12 [00:02<00:00,  4.01it/s]
eval model::  83%|████████▎ | 10/12 [00:02<00:00,  3.91it/s][2021/08/02 18:30:53] root ERROR: When parsing line 
, error happened with msg: list index out of range

eval model::  92%|█████████▏| 11/12 [00:02<00:00,  3.91it/s]
eval model:: 100%|██████████| 12/12 [00:02<00:00,  4.74it/s]
eval model:: 100%|██████████| 12/12 [00:02<00:00,  4.09it/s]

**Comment by littletomatodonkey** [comment]
解析数据标注中的某一行有问题，数据标注格式错误，不过在评估的时候会跳过这一行，可以不用管

**Comment by hice1207** [comment]
> 解析数据标注中的某一行有问题，数据标注格式错误，不过在评估的时候会跳过这一行，可以不用管

评估的acc每次都是0.0

**Comment by littletomatodonkey** [comment]
可以试着加载官网提供的prertain model看下精度

**Comment by TD-wzw** [comment]
> > 解析数据标注中的某一行有问题，数据标注格式错误，不过在评估的时候会跳过这一行，可以不用管
> 
> 评估的acc每次都是0.0

![H_DOH4WRSK`L%YZ7X9T3M1W](https://user-images.githubusercontent.com/57340568/133364500-c58504be-b295-4824-afd7-f8d665d48e87.png)
我也是这样请问你解决了吗

**Comment by hice1207** [comment]
> > > 解析数据标注中的某一行有问题，数据标注格式错误，不过在评估的时候会跳过这一行，可以不用管
> > 
> > 
> > 评估的acc每次都是0.0
> 
> ![H_DOH4WRSK`L%YZ7X9T3M1W](https://user-images.githubusercontent.com/57340568/133364500-c58504be-b295-4824-afd7-f8d665d48e87.png)
> 我也是这样请问你解决了吗

我的问题解决了，我的是数据集的问题，你可以看看tools里那个eval文件，打个断点看看是哪一步出问题了

**Comment by TD-wzw** [comment]
好的，谢谢
