### ISSUE TITLE
使用官方给定的模型（ https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_train.tar）ch_ppocr_mobile_v2.0_det_train/best_accuracy，加载配置文件（ch_det_mv3_db_v2.0.yml)，进行推理时（infer_det.py)结果错误，无法检测出文字，请问一下大概是什么问题？

### ISSUE THREAD

**Issue by weekstudy** [PaddlePaddle/PaddleOCR#3513]
不是，模型文件是用的这个链接 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_train.tar，
不是https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar）

**Comment by weekstudy** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
配置文件与检测结果

**Comment by MissPenguin** [comment]
运行命令和报错信息发一下吧

**Comment by weekstudy** [comment]
> 运行命令和报错信息发一下吧



> 运行命令和报错信息发一下吧

没有报错信息，可以运行，只是运行的检测结果不正确，如图所示，搞不明白是为什么；
运行命令的话，因为是在ide运行的，但是配置文件用的是上面如图所示，

**Comment by weekstudy** [comment]
> 运行命令和报错信息发一下吧

没有报错信息，可以运行，只是运行的检测结果不正确，如图所示，搞不明白是为什么；
运行命令的话，因为是在ide运行的，但是配置文件用的是上面如图所示，
