### ISSUE TITLE
想将试卷上的手写文字擦除掉，有什么好的方法嘛？？

### ISSUE THREAD

**Issue by jdmking2019** [PaddlePaddle/PaddleOCR#3514]

**Comment by MissPenguin** [comment]
先检测手写文字区域，再用图像处理擦除

**Comment by jdmking2019** [comment]
您好！目前正在使用Paddle OCR训练自己的数据集。
配置文件选用的是det_r50_vd_sast_icdar15.yml
训练的时候会出现invalid poly

截图如下：


数据是利用labelimg标注的xml格式，1个类别，主要就是想检测自己数据集中手写字体的位置。不知道为什么会出现这种原因。
期待您的帮助！
在2021年11月4日 ***@***.***> 写道：

Closed #3514.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
