### ISSUE TITLE
DET和REC使用Paddle Serving部署可以单独部署吗

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/PaddleOCR#3516]
参考链接为[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/deploy/pdserving/README_CN.md#ppocr-%E6%9C%8D%E5%8A%A1%E5%8C%96%E9%83%A8%E7%BD%B2](url)

**Comment by MissPenguin** [comment]
原理上是可以的，但是需要自己开发一下，如果不想开发，可以试试hubserving：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/deploy/hubserving
