### ISSUE TITLE
表格不能检测中文

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#3529]
图片是中文的表格不能识别啊

**Comment by Lie-huo** [comment]
可不可以出一个识别中文表格的？

**Comment by MissPenguin** [comment]
目前的结构化模型实在英文公开数据集上训练的，表格内部的文字识别可以用ppocr的中文模型。可以贴一下case看看嘛

**Comment by Lie-huo** [comment]
> 目前的结构化模型实在英文公开数据集上训练的，表格内部的文字识别可以用ppocr的中文模型。可以贴一下case看看嘛

![image](https://user-images.githubusercontent.com/13652569/128148548-862e51b7-6fb1-4799-9ee9-a4be46e89411.png)

类似于这样的，其中的表格检测不出来

**Comment by MissPenguin** [comment]
哦哦，是没检测出来啊，版面分析模型的训练数据都是英文文档（像论文那种），和你的这种case确实差异比较大，所以检测效果估计不会好。另外你这个表格即使检测出来了，可能识别效果也不会太好，因为你这种格式的表格和pubtabnet中的表格差异也很大。建议最好用自己的业务数据训一把表格检测和表格识别。

**Comment by FocueAI** [comment]
> 哦哦，是没检测出来啊，版面分析模型的训练数据都是英文文档（像论文那种），和你的这种case确实差异比较大，所以检测效果估计不会好。另外你这个表格即使检测出来了，可能识别效果也不会太好，因为你这种格式的表格和pubtabnet中的表格差异也很大。建议最好用自己的业务数据训一把表格检测和表格识别。

有制作pubtabnet数据格式的开源工具吗？
