### ISSUE TITLE
some image don't have  result

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleOCR#353]
for example :PaddleOCR-develop/doc/imgs/11.jpg  
when i run the code"sh tools/run.sh",that output:
"terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.7) /home/wz/Downloads/opencv-3.4.7/modules/imgproc/src/convhull.cpp:137: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull' "

can you tell me how to change?

**Comment by LDOUBLEV** [comment]
> for example :PaddleOCR-develop/doc/imgs/11.jpg
> when i run the code"sh tools/run.sh",that output:
> "terminate called after throwing an instance of 'cv::Exception'
> what(): OpenCV(3.4.7) /home/wz/Downloads/opencv-3.4.7/modules/imgproc/src/convhull.cpp:137: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull' "
> 
> can you tell me how to change?

We are trying to solve this problem.

**Comment by littletomatodonkey** [comment]
You can also refer to #338 to fix this problem.
