### ISSUE TITLE
训练eval环节accu一直很低的问题

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3530]
![image](https://user-images.githubusercontent.com/25193686/128111049-0d7b5459-6b08-4b2e-ae71-4d71846709b8.png)

在训练集上的accu一直在增加，到了70%多，效果还很好。为什么eval的效果一直在40左右呢？

数据集是ICDAR切下来的日文小语种

**Comment by LDOUBLEV** [comment]
数据量太少了吧，可能训练过拟合了，建议多加一些数据增强和数据

**Comment by LinXin04** [comment]
训练集数据量8K, 测试集2k. 这里需要设置droplast吗？
![image](https://user-images.githubusercontent.com/25193686/128117611-2eecaea5-e74a-4d7f-9bb5-5f7fdb0a9d11.png)

**Comment by LDOUBLEV** [comment]
训练数据不算多，可以多找一些其他日文数据参与训练，
为了防止过拟合，可以多加一些数据增强
loader中的shuffle建议设置为True

**Comment by LinXin04** [comment]
数据增强的话直接在配置文件里加个distort:True字段就行了吧？
![image](https://user-images.githubusercontent.com/25193686/128301090-9a58419f-2fb9-48d5-ba42-a43dba0722f1.png)

**Comment by LDOUBLEV** [comment]
数据增强的加法，参考配置文件：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml
![image](https://user-images.githubusercontent.com/26592129/128445531-ab3f1cb9-a460-487a-b5ed-861b55dc4cdf.png)

**Comment by LinXin04** [comment]
@LDOUBLEV 
直接取消这参数就行了把，默认好像就是取消的
![image](https://user-images.githubusercontent.com/25193686/128466965-86c621c8-4914-4c45-a665-aa9e054af1cb.png)
