### ISSUE TITLE
表格识别ppstructure，更换模型出现InvalidArgumentError。

### ISSUE THREAD

**Issue by zxGH86** [PaddlePaddle/PaddleOCR#3535]
更换table_model_dir后出现InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(image) is not initialized.
[Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1565)
      [operator < conv2d > error]

**Comment by MissPenguin** [comment]
是换成什么模型报的错，table_model_dir这个模型目前应该就开源了一个，拿什么换？😂

**Comment by zxGH86** [comment]
> 是换成什么模型报的错，table_model_dir这个模型目前应该就开源了一个，拿什么换？😂

就是把对应的table_model_dir换成了LayoutParser 模型中的publaynet、tableBank_word、tableBank_latex
