### ISSUE TITLE
CTC文字识别预测文字多字，求助

### ISSUE THREAD

**Issue by SharonJin422** [PaddlePaddle/PaddleOCR#3536]
用CTC解码的时候，发现预测多字，对比试验发现和seq_len、max time step设置有关，想请问下大佬们有遇到这种情况吗，主要是不知道这种现象的理论解释是什么，特别困惑。
1. 设置max time step = 128, seq_len = 64,预测不会多字
2. 设置max time step = 128, seq_len = 14，预测多字

另外一个现象是：
3.设置max time step = 128, seq_len = 128,会报“No valid path found”， 一开始上网查到说是“input label length > max timestep”, 后来发现是学习率太大的问题，改小learning rate后，就没问题了，所以目前不确定是不是因为learning rate导致上面的现象，正在跑对比实验。

**Comment by LDOUBLEV** [comment]
你用的是PaddleOCR 里的代码 ？

**Comment by SharonJin422** [comment]
不完全是，加上了双向LSTM

**Comment by LDOUBLEV** [comment]
Paddle OCR的识别模型有双向LSTM可以直接用现成的
