### ISSUE TITLE
文本方向分类器相关

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleOCR#3538]
请问下paddle的分类器大概用了多少数据呢？我训练集和验证集共十万张左右，总是过拟合

**Comment by LDOUBLEV** [comment]
10万数据足够了，加一些数据增强，正则
也可以看下在哪些方向类别上过拟合严重，看下数据分布

**Comment by TD-wzw** [comment]
数据增强尝试过颜色变换，旋转(-2,2)，随机cropresize，随机遮挡，它在验证集表现也还不错，可能是我数据样本太单一了吧

**Comment by TD-wzw** [comment]
训练集验证集长的太像了导致它虚高

**Comment by TD-wzw** [comment]
就都是用的paddle介绍的数据集里有一个中文文本行的，一行十个字那个数据集

**Comment by neverstoplearn** [comment]
我想问一下文本角度分类器数据集是哪来的？谢谢。

**Comment by TD-wzw** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md这里的中文文档

**Comment by neverstoplearn** [comment]
> [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md这里的中文文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md%E8%BF%99%E9%87%8C%E7%9A%84%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3)

意思是需要自己对这里的数据集进行翻转来制作数据集吗？

**Comment by LDOUBLEV** [comment]
> > [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md这里的中文文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md%E8%BF%99%E9%87%8C%E7%9A%84%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3)
> 
> 意思是需要自己对这里的数据集进行翻转来制作数据集吗？

是的，旋转的时候记录下旋转的角度即可

**Comment by neverstoplearn** [comment]
好的，谢谢。

**Comment by TD-wzw** [comment]
请问下这个您大概用了多少数据集，我还想加入其他语言，英文日文这些，想搞的均衡点，请告知中文大概多少？单个角度来说

**Comment by LDOUBLEV** [comment]
如果你要加入其他数据集，建议多加一些数据；
用到的数据集 详情，可以在[这篇文章](https://arxiv.org/abs/2009.09941)中找到；

**Comment by TD-wzw** [comment]
谢谢~

**Comment by wb315** [comment]
@LDOUBLEV 你好，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/datasets_en.md这里的中文文档这个链接打不开了
