### ISSUE TITLE
AttributeError: module 'layoutparser' has no attribute 'PaddleDetectionLayoutModel

### ISSUE THREAD

**Issue by chinaguole** [PaddlePaddle/PaddleOCR#3541]
python3.8-10/windows,部署完终端运行报错:
AttributeError: module 'layoutparser' has no attribute 'PaddleDetectionLayoutModel'

**Comment by littletomatodonkey** [comment]
你好，需要按照官网教程去安装layoutparser: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/ppstructure/README_ch.md

```
pip3 install -U https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
```

**Comment by chinaguole** [comment]
谢谢！

**Comment by yanlieting** [comment]
我也有这个问题！两个环境按文档装了2次都是同一个问题！
版本：release-2.3
没有安装ppaddleocr，直接拉取github的代码执行：
python paddleocr.py *** 报这个错
是不是版本的问题？

**Comment by yanlieting** [comment]
> 你好，需要按照官网教程去安装layoutparser: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/ppstructure/README_ch.md
> 
> ```
> pip3 install -U https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
> ```

没用
