### ISSUE TITLE
训练闪退

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3542]
在pycharm训练ppstruct的时候中途停止训练，导致电脑所有程序闪退，调试的时候也闪退，是要用动态版本？

**Comment by MissPenguin** [comment]
建议按照教程中的流程来哈，在docker中操作，这样有问题比较好排查

**Comment by cqray1990** [comment]
没有用ｄｏｋｃｅｒ，这个问题以前也出现过

**Comment by cqray1990** [comment]
也不至于闪退啊，导致电脑上所有的程序都退出了，内存泄漏？
