### ISSUE TITLE
训练闪退，在pycharm训练ppstruct的时候中途停止训练，导致电脑所有程序闪退，调试的时候也闪退是什么原因？版本问题？我用的最新的版本

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3543]

**Comment by frkhit** [comment]
我在调试 PP-OCR 文字识别的时候， 也出现过类似的问题： 使用调试模式， 打断点。 在调试过程中， 直接点击 pycharm 终止调试按钮， pycharm 闪退。 如果让 pycharm 执行完所有程序， pycharm 则正常。

**Comment by cqray1990** [comment]
@frkhit 是的，以前就是这种情况，提过issue，但是没有解决，说是ｐａｄｄｌｅ分动态静态啥的，ｔｆ动态图静态都出现这个情况啊

**Comment by cqray1990** [comment]
@frkhit 请问你解决了？

**Comment by cqray1990** [comment]
@frkhit

**Comment by frkhit** [comment]
@cqray1990 没解决。 为避免 pycharm 闪退， 我在调试模式下， 调试结束后， 会让程序执行完成， 避免手工终止调试程序。
