### ISSUE TITLE
 训练闪退，在pycharm训练ppstruct的时候中途停止训练，导致电脑所有程序闪退，调试的时候也闪退是什么原因？版本问题？我用的最新的版本!!!

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3544]
麻烦大佬们来解决一下啊，老出现这个问题！！

**Comment by tink2123** [comment]
提供下你的环境吧，windows or mac ？另外能否在训练过程中观察一下内存占用情况？

**Comment by cqray1990** [comment]
@tink2123 我没有训练，是在调试训练的代码，环境cudnn7，cuda10.0,paddlepadlle版本2.0,2.1都试过
