### ISSUE TITLE
Has anyone tried live real-time recognition via mobile ?

### ISSUE THREAD

**Issue by rsingh2083** [PaddlePaddle/PaddleOCR#3545]
Can anyone please help with doing live OCR via mobile phone ?
Is it even possible to do via PaddleOCR ?

**Comment by tink2123** [comment]
You can try to use the mobile demo：
Mobile DEMO experience (based on EasyEdge and Paddle-Lite, supports iOS and Android systems): Sign in to the website to obtain the QR code for installing the App

**Comment by rsingh2083** [comment]
I downloaded and installed that mobile app, but how can I recreate that mobile app again with changes in UI ?

**Comment by rsingh2083** [comment]
> You can try to use the mobile demo：
> Mobile DEMO experience (based on EasyEdge and Paddle-Lite, supports iOS and Android systems): Sign in to the website to obtain the QR code for installing the App

Please help, I want to customize that mobile app. Want to change the UI and language etc

**Comment by rsingh2083** [comment]
Pls help
