### ISSUE TITLE
调试 PP-OCR 文字识别的时候， 也出现过类似的问题： 使用调试模式， 打断点。 在调试过程中， 直接点击 pycharm 终止调试按钮， pycharm 闪退。 如果让 pycharm 执行完所有程序， pycharm 则正常。

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3548]
这种到底是什么原因？以前也出现过

**Comment by littletomatodonkey** [comment]
这种没试过，感觉是某些代码不支持断点运行

**Comment by cqray1990** [comment]
@littletomatodonkey 大佬写代码不调试的？哈哈，厉害

**Comment by thgpddl** [comment]
楼主我也遇到了，请问你解决了吗？
目前我发现是`import tools.program as program`中导入的`from ppocr.data import build_dataloader
`造成的，当我注释`from ppocr.data import build_dataloader`后debug便不会闪退
