### ISSUE TITLE
mobilentv3 backbone 

### ISSUE THREAD

**Issue by ouyanghuiyu** [PaddlePaddle/PaddleOCR#355]
用mobilentv3 下采样16倍和32倍的时候 h < 5 了，用5*5的核，岂不是有部分参数根本没起到作用

**Comment by tink2123** [comment]
是的，现在是有这个问题，我们也考虑是否修改网络结构，后续会进行实验迭代优化模型。感谢关注～

**Comment by dyning** [comment]
再就是，后面我们会做消融实验，看看直接采用AdaptiveAvgPool方式的效果。
