### ISSUE TITLE
预测结果返回score为-nan(ind)

### ISSUE THREAD

**Issue by contoto** [PaddlePaddle/PaddleOCR#3555]
大部分字符均能预测出来，但有时个别字符预测结果返回-nan(ind)
![warp_normal_3152_2](https://user-images.githubusercontent.com/25604224/128302479-8ad140b1-32b0-49d7-b9de-4b09b6bfcaa0.png)

**Comment by tink2123** [comment]
自测时可以正确预测的：
paddleocr --image_dir=test.png

<img width="918" alt="图片" src="https://user-images.githubusercontent.com/31891223/128328673-821b39ba-8055-498d-9b1b-8ad3a393cd00.png">

**Comment by contoto** [comment]
是使用不同的库模型结果导致的吗？
程序我是编译这个下面的：~PaddleOCR\deploy\cpp_infer\src
然后配置的模型如下：
# model load config
use_gpu 0
gpu_id  0
gpu_mem  4000
cpu_math_library_num_threads  10
use_mkldnn 0

# det config
max_side_len  960
det_db_thresh  0.3
det_db_box_thresh  0.5
det_db_unclip_ratio  1.6
det_model_dir  ./inference/ch_ppocr_mobile_v2.0_det_infer/

# cls config
use_angle_cls 0
cls_model_dir  ./inference/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh  0.9

# rec config
rec_model_dir  ./inference/ch_ppocr_mobile_v2.0_rec_infer/
char_list_file ./ppocr_keys_v1.txt

# show the detection results
visualize 1

# use_tensorrt
use_tensorrt 0
use_fp16   0

**Comment by contoto** [comment]
> 
> 
> 是使用不同的库模型结果导致的吗？
> 程序我是编译这个下面的：~PaddleOCR\deploy\cpp_infer\src
> 然后配置的模型如下：
> # model load config
> 
> use_gpu 0
> gpu_id 0
> gpu_mem 4000
> cpu_math_library_num_threads 10
> use_mkldnn 0
> # det config
> 
> max_side_len 960
> det_db_thresh 0.3
> det_db_box_thresh 0.5
> det_db_unclip_ratio 1.6
> det_model_dir ./inference/ch_ppocr_mobile_v2.0_det_infer/
> # cls config
> 
> use_angle_cls 0
> cls_model_dir ./inference/ch_ppocr_mobile_v2.0_cls_infer/
> cls_thresh 0.9
> # rec config
> 
> rec_model_dir ./inference/ch_ppocr_mobile_v2.0_rec_infer/
> char_list_file ./ppocr_keys_v1.txt
> # show the detection results
> 
> visualize 1
> # use_tensorrt
> 
> use_tensorrt 0
> use_fp16 0

使用Python环境，系统默认运行结果也是对的，如下：
![default_ocr](https://user-images.githubusercontent.com/25604224/128679916-874dc122-8392-4974-acbf-7894dbc14b6b.png)

**Comment by irvingzhang0512** [comment]
zai jetson 上部署也偶尔出现 score 为 nan 的情况
