### ISSUE TITLE
关于文本识别算法SRN训练所需合成数据集上特殊字符的问题

### ISSUE THREAD

**Issue by simplify23** [PaddlePaddle/PaddleOCR#3557]
SRN算法在训练时，用的字典是dict_36,这个字典并没有特殊字符和大小写。但在训练的过程中，合成数据集MJ ST上有特殊字符和大写字母，请问SRN是怎么处理MJ+ST上的这类字符的呢，可以发一下处理这些字符的代码脚本路径吗，非常感谢~

**Comment by tink2123** [comment]
SRN默认训练时过滤掉了这些特殊字符，具体代码在：
https://github.com/PaddlePaddle/PaddleOCR/blob/14638fe05868356d1046e8adf36bfff9a36edc8e/ppocr/data/imaug/label_ops.py#L153-L158
