### ISSUE TITLE
关于预处理的几个疑惑

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/PaddleOCR#3561]
（1）训练时候的预处理包括：
<ppocr.data.imaug.operators.DecodeImage object at 0x7f3605b64c90>, <ppocr.data.imaug.label_ops.DetLabelEncode object at 0x7f3605b64690>, <ppocr.data.imaug.iaa_augment.IaaAugment object at 0x7f3605b64d50>, <ppocr.data.imaug.random_crop_data.EastRandomCropData object at 0x7f3605b64f90>, <ppocr.data.imaug.make_border_map.MakeBorderMap object at 0x7f3605b64750>, <ppocr.data.imaug.make_shrink_map.MakeShrinkMap object at 0x7f3605b68750>, <ppocr.data.imaug.operators.NormalizeImage object at 0x7f3605b68990>, <ppocr.data.imaug.operators.ToCHWImage object at 0x7f3605b68a50>, <ppocr.data.imaug.operators.KeepKeys object at 0x7f3605b68b10>]
主要的疑惑在random crop在我数据集上，很多样本在crop前后的对比如图：
crop前：
![image_before1](https://user-images.githubusercontent.com/21244547/128320994-8628f91d-28c1-4096-8078-e09c8ee40eb1.jpg)
crop后：
![image_after1](https://user-images.githubusercontent.com/21244547/128321026-d8befb12-b5e4-4ec6-803d-b535b83eb9d9.jpg)
crop前：
![image_before2](https://user-images.githubusercontent.com/21244547/128321070-44fcdc44-cad7-4b36-8926-2993bd05c50d.jpg)
corp后：
![image_after2](https://user-images.githubusercontent.com/21244547/128321090-bd919f3a-9b21-4a5a-b6d4-c785c8c95190.jpg)
这样crop之后感觉有效区域少了非常多
训练的代码为什么要做这样的crop（crop的代码逻辑我没有细读），或者是因为我的数据长宽比比较极端导致crop出来也极端？
（2）另外eval和inference（来自tools/infer/predict_det.py 代码）的预处理是：
[<ppocr.data.imaug.operators.DecodeImage object at 0x7f0a55902ed0>, <ppocr.data.imaug.label_ops.DetLabelEncode object at 0x7f0a55902dd0>, <ppocr.data.imaug.operators.DetResizeForTest object at 0x7f0a559029d0>, <ppocr.data.imaug.operators.NormalizeImage object at 0x7f0a55902890>, <ppocr.data.imaug.operators.ToCHWImage object at 0x7f0a55902cd0>, <ppocr.data.imaug.operators.KeepKeys object at 0x7f0a55902d90>]
但是DetResizeForTest 的操作是不一样的，eval直接resize到某个尺寸，inference是等比例（有最大边长度设置）并取32的倍数。
我觉得inference的更合理，但为什么eval要这样操作。
目前我最大的困惑是在自己的数据集上训练指标不理想。

**Comment by tink2123** [comment]
1. random crop 是数据增强的方式，为了增加数据的丰富度，随机切割掉边缘。你的图片上确实是因为长宽比比较极端，所以crop出来只保留了边缘。训练时可以去掉这个数据增强。
2. eval 的shape是按照ic15的数值设计的，你的数据集如果shape比较特殊，可以自己修改一下数值。
