### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'seed'

### ISSUE THREAD

**Issue by thongvhoang** [PaddlePaddle/PaddleOCR#3562]
I use version: 
paddlepaddle                      2.1.2
paddlepaddle-gpu                  1.7.2.post107

I run on GPU, ubuntu 20.04, and
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   44C    P8     9W / 151W |    447MiB /  8116MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       964      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      2016      G   /usr/lib/xorg/Xorg                210MiB |
|    0   N/A  N/A      2145      G   /usr/bin/gnome-shell               71MiB |
|    0   N/A  N/A      2478      G   ...AAAAAAAAA= --shared-files       30MiB |
|    0   N/A  N/A      2595      G   ...AAAAAAAAA= --shared-files       85MiB |
+-----------------------------------------------------------------------------+

How can fix this bug ?
![Screenshot from 2021-08-05 15-53-34](https://user-images.githubusercontent.com/42695481/128321958-c9b92a52-9677-4926-a7d8-75fa8dc1ccd5.png)

**Comment by tink2123** [comment]
Try to update paddlepaddle-gpu:

python3 -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

**Comment by thongvhoang** [comment]
> Try to update paddlepaddle-gpu:
> 
> python3 -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

I have followed your tutorial. But failed

**Comment by thongvhoang** [comment]
I have updated some my environment.

**Comment by thongvhoang** [comment]
Thank you.
I have fixed this bug by adjust cuda version 10.02 to be suitable with paddlepaddle-gpu.
