### ISSUE TITLE
可视化bug

### ISSUE THREAD

**Issue by 77h2l** [PaddlePaddle/PaddleOCR#3563]
image, boxes, texts, scores, draw_txt=True, drop_score=0.5) 

这个地方参数有一处bug，正确的参数应该是

image, boxes, texts, scores, drop_score=0.5, font_path="./doc/fonts/simfang.ttf")

**Comment by tink2123** [comment]
感谢反馈，请问这是哪个文档里的呢？我们会尽快修复它

**Comment by rainmakerMa** [comment]
> 感谢反馈，请问这是哪个文档里的呢？我们会尽快修复它

https://github.com/PaddlePaddle/PaddleOCR/issues/3563#issuecomment-893312589

这里

**Comment by rainmakerMa** [comment]
> 感谢反馈，请问这是哪个文档里的呢？我们会尽快修复它

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/tools/test_hubserving.py#L68

这里
