### ISSUE TITLE
使用中文训练pgnet损失为nan

### ISSUE THREAD

**Issue by zhishao** [PaddlePaddle/PaddleOCR#3564]
![image](https://user-images.githubusercontent.com/18610954/128324637-d94f0dca-e941-423b-b394-ca438cb38c66.png)
之前使用英文训练效果良好，英文使用四边形标注，character_dict_path: ppocr/utils/ic15_dict.txt。
但数据更换为中文数据，中文四边形标注，character_dict_path: ppocr/utils/ppocr_keys_v1.txt，训练损失出现nan，实际测试什么都检测不出。

**Comment by Rickyart** [comment]
> ![image](https://user-images.githubusercontent.com/18610954/128324637-d94f0dca-e941-423b-b394-ca438cb38c66.png) 之前使用英文训练效果良好，英文使用四边形标注，character_dict_path: ppocr/utils/ic15_dict.txt。 但数据更换为中文数据，中文四边形标注，character_dict_path: ppocr/utils/ppocr_keys_v1.txt，训练损失出现nan，实际测试什么都检测不出。

同样问题，请问楼主解决了吗
