### ISSUE TITLE
请问一下，配置文件det_mv3_db.yml中use_shared_memory参数有什么用？如果设为true表示什么意思？设为false表示什么意思？

### ISSUE THREAD

**Issue by weekstudy** [PaddlePaddle/PaddleOCR#3566]

**Comment by tink2123** [comment]
是否使用共享内存来提升子进程将数据放入进程间队列的速度，需要确认机器上有足够的共享内存空间(如Linux系统下 /dev/shm/ 目录空间大小)再设置此参数

**Comment by weekstudy** [comment]
> 是否使用共享内存来提升子进程将数据放入进程间队列的速度，需要确认机器上有足够的共享内存空间(如Linux系统下 /dev/shm/ 目录空间大小)再设置此参数

明白了，感谢！
