### ISSUE TITLE
在部署OCR的时候出现的问题。

### ISSUE THREAD

**Issue by tszhang20** [PaddlePaddle/PaddleOCR#357]
我按照这个https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md 的教程在ubuntu16.04下部署ARMv8。
apt-get install -y --no-install-recommends g++-arm-linux-gnueabi gcc-arm-linux-gnueabi g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu 的输出如下：
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-aarch64-linux-gnu is already the newest version (4:5.3.1-1ubuntu1).
g++-arm-linux-gnueabihf is already the newest version (4:5.3.1-1ubuntu1).
gcc-aarch64-linux-gnu is already the newest version (4:5.3.1-1ubuntu1).
gcc-arm-linux-gnueabihf is already the newest version (4:5.3.1-1ubuntu1).
g++-arm-linux-gnueabi is already the newest version (4:5.3.1-1ubuntu1).
gcc-arm-linux-gnueabi is already the newest version (4:5.3.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 610 not upgraded.`
make -j的输出如下：
`/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ --sysroot=/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/sources/cxx-stl/llvm-libc++/include -I/sources/cxx-stl/llvm-libc++abi/include -I/sources/android/support/include -I/sysroot/usr/include  -I/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions -frtti -std=c++11 -fopenmp -O3 -DNDEBUG -fPIE -o ocr_db_crnn.o -c ocr_db_crnn.cc
make: /toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++: Command not found
Makefile:47: recipe for target 'ocr_db_crnn.o' failed
make: *** [ocr_db_crnn.o] Error 127
make: *** Waiting for unfinished jobs....`
本人第一次接触这方面的东西，请问一下这个是什么问题，谢谢。

**Comment by LDOUBLEV** [comment]
是否安装了对应的预编译环境
![image](https://user-images.githubusercontent.com/26592129/87691610-59f20100-c7bd-11ea-8f32-58a5c9bdb5d4.png)

**Comment by tszhang20** [comment]
> 这个[链接](https://paddle-lite.readthedocs.io/zh/latest/user_guides/source_compile.html#arm-linux)的步骤走完了没，有没有报错啥的，看上去像是预编译环境没配好
> 
> ![image](https://user-images.githubusercontent.com/26592129/87691984-cbca4a80-c7bd-11ea-9f96-6fe097cd2716.png)

第一步的输出如下：
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
make is already the newest version (4.1-6).
unzip is already the newest version (6.0-20ubuntu1).
git is already the newest version (1:2.7.4-0ubuntu1.9).
python is already the newest version (2.7.12-1~16.04).
wget is already the newest version (1.17.1-1ubuntu1.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`
第二步的输出在问题里面提到了，然后CMake版本是3.12，gcc/g++是5.3.0，NDK是r17c.

**Comment by LDOUBLEV** [comment]
刚测试了linux环境下准备好lite的预编译环境，编译OCR的demo是没问题的。你在哪个目录下编译的，OCR的lite demo有没有按照下面的格式组织好，
![image](https://user-images.githubusercontent.com/26592129/87750903-467f7e00-c82f-11ea-80e0-72aa11a99775.png)

然后在/demo/cxx/ocr 下执行 make -j

**Comment by tszhang20** [comment]
> 刚测试了linux环境下准备好lite的预编译环境，编译OCR的demo是没问题的。你在哪个目录下编译的，OCR的lite demo有没有按照下面的格式组织好，
> ![image](https://user-images.githubusercontent.com/26592129/87750903-467f7e00-c82f-11ea-80e0-72aa11a99775.png)
> 
> 然后在/demo/cxx/ocr 下执行 make -j

感谢解答，上面是我NDK环境配置的问题，现在解决了。然后，现在是在最后一步的输入是：
`./ocr_db_crnn ch_det_mv3_db_opt.nb  ch_rec_mv3_crnn_opt.nb ./11.jpg  ppocr_keys_v1.txt`
现在的输出是：
`WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6ffffffe arg 0x6900
WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6ffffffe arg 0xbfe8
WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6fffffff arg 0x3
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__register_atfork" referenced by "libpaddle_light_api_shared.so"...
`
测试Android环境是5.1，CPU Cortex A72。网上普遍说是版本匹配的问题，可以说明一下吗?

**Comment by AIpioneer** [comment]
> 感谢解答，上面是我NDK环境配置的问题，现在解决了。然后，现在是在最后一步的输入是：
> `./ocr_db_crnn ch_det_mv3_db_opt.nb ch_rec_mv3_crnn_opt.nb ./11.jpg ppocr_keys_v1.txt`
> 现在的输出是：
> `WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6ffffffe arg 0x6900 WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6fffffff arg 0x2 WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6ffffffe arg 0xbfe8 WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6fffffff arg 0x3 CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__register_atfork" referenced by "libpaddle_light_api_shared.so"... `
> 测试Android环境是5.1，CPU Cortex A72。网上普遍说是版本匹配的问题，可以说明一下吗?

你好！目前看起来是安卓版本太低了。请问您使用的是什么机器啊？为什么会在用比较低的版本呢，还有没有可能升级安卓系统？

**Comment by tszhang20** [comment]
> > 感谢解答，上面是我NDK环境配置的问题，现在解决了。然后，现在是在最后一步的输入是：
> > `./ocr_db_crnn ch_det_mv3_db_opt.nb ch_rec_mv3_crnn_opt.nb ./11.jpg ppocr_keys_v1.txt`
> > 现在的输出是：
> > `WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6ffffffe arg 0x6900 WARNING: linker: ./ocr_db_crnn: unused DT entry: type 0x6fffffff arg 0x2 WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6ffffffe arg 0xbfe8 WARNING: linker: libpaddle_light_api_shared.so: unused DT entry: type 0x6fffffff arg 0x3 CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__register_atfork" referenced by "libpaddle_light_api_shared.so"... `
> > 测试Android环境是5.1，CPU Cortex A72。网上普遍说是版本匹配的问题，可以说明一下吗?
> 
> 你好！目前看起来是安卓版本太低了。请问您使用的是什么机器啊？为什么会在用比较低的版本呢，还有没有可能升级安卓系统？

是一部安卓手机，现在看来应该不能升级安卓系统。然后，这个Demo的最低版本要求是多少呢？

**Comment by AIpioneer** [comment]
您好，Paddle Lite的版本最低要求为5.1，因此您这个问题我们还需要检测一下。方便的话，可以电话或者微信加一下我I52IO5九8六五八。
