### ISSUE TITLE
paddleocr/paddleocr.py:ocr 函数存在内存泄露

### ISSUE THREAD

**Issue by wenxuezhang** [PaddlePaddle/PaddleOCR#3573]
调用__call__函数的时候，内存有溢出。
__call__函数里：text_detector 函数，text_classifier函数，text_recognizer函数有比较明显内存变化。
使用ps -aux方法，执行这些函数前后，内存有明显增加。或者通过连续识别10000个图片，内存变化明显。
环境：paddlepaddle-2.1.2，paddleocr：2.0.2

**Comment by wenxuezhang** [comment]
能给个结论不？

**Comment by WenmuZhou** [comment]
调用call函数内存增加是正常的，你看看一张图片infer1000次，内存是不是持续增长

**Comment by wenxuezhang** [comment]
我写了一个python进程，加载模型后，调用：result = ocr.ocr(input_file, cls=True) 函数100000次，内存有非常显著的增长，大约几十G的样子。




张文学  pi  认知智能实验室 
Mobile:+86-18210275525
E-mail: ***@***.***
PERCENT.CN - Decision Intelligence
北京市海淀区建材城中路27号金隅智造工场S5栋西侧 100096
 
 
发件人： zhoujun
发送时间： 2021-08-16 19:27
收件人： PaddlePaddle/PaddleOCR
抄送： wenxuezhang; Author
主题： Re: [PaddlePaddle/PaddleOCR] paddleocr/paddleocr.py:ocr 函数存在内存泄露 (#3573)
调用call函数内存增加是正常的，你看看一张图片infer1000次，内存是不是持续增长
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wenxuezhang** [comment]
我写了一个python进程，加载模型后，调用：result = ocr.ocr(input_file, cls=True) 函数100000次，内存有非常显著的增长，大约几十G的样子。

**Comment by jtl1207** [comment]
没错,那该怎么解决啊

**Comment by WenmuZhou** [comment]
你好，我这边linux下没有复现这个问题，方便提供一下你的复现代码和图片吗

**Comment by wenxuezhang** [comment]
![Uploading image.png…]()    ----上面是ps -aux后看第六个变量的结果
下面是测试代码，
[ocr_test.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7450416/ocr_test.zip)
执行的时候，运行Python app.py 然后 调用对应主机的这个服务，即post 下面链接http://*.*.*.*:10001/ocr/arm
运行10万次试试，随时沟通@WenmuZhou

**Comment by wenxuezhang** [comment]
我用最新的paddlepaddle-2.2.0，paddleOCR2.3.0.1 ，CPU算力 依然出现内存泄露现象。

**Comment by wenxuezhang** [comment]
兄弟，要不要视频一下，我把问题给你反馈一下？

**Comment by meanfei** [comment]
> 兄弟，要不要视频一下，我把问题给你反馈一下？

遇到了一样的问题，请问楼主是怎么解决的

**Comment by wenxuezhang** [comment]
没解决，无响应

**Comment by kealennieh** [comment]
貌似采用不同尺寸的图，仅仅在模型配置中设置了最大尺寸的限制，会导致显存不断增加。这是因为每次图像大小不一样，每次都会去重新申请显存么？
