### ISSUE TITLE
以serving方式启动后，识别几张图片后，web_service变为defunct

### ISSUE THREAD

**Issue by fafi09** [PaddlePaddle/PaddleOCR#3577]
INFO 2021-08-06 08:14:30,412 [pipeline_server.py:51] (log_id=0) inference request name:ocr self.name:ocr
INFO 2021-08-06 08:14:30,413 [operator.py:1411] RequestOp unpack one request. log_id:0, clientip:             name:ocr, method:prediction
INFO 2021-08-06 08:14:30,413 [dag.py:368] (data_id=2 log_id=0) Succ Generate ID 

log停在这里

**Comment by EtachGu** [comment]
i have same problem

**Comment by WenmuZhou** [comment]
方便提供一下复现的步骤不
