### ISSUE TITLE
How to use paddleOCR using opencv from source?

### ISSUE THREAD

**Issue by Amrou7** [PaddlePaddle/PaddleOCR#3578]
In the requirements, there is a specific version of opencv-contrib and opencv-python in order to use PaddleOCR. However, I'm in a case that I should use opencv-python and opencv-contrib from source ( Because I use gstreamer ). How can I run PaddleOCR with opencv-contrib and opencv-python from source?

**Comment by WenmuZhou** [comment]
you can refer to cpp demo in https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/deploy/cpp_infer/readme_en.md
