### ISSUE TITLE
进行端侧部署的的时候不知道这些文件是从哪里来的

### ISSUE THREAD

**Issue by koala9527** [PaddlePaddle/PaddleOCR#358]
|-- config.txt                  DB-CRNN超参数配置
|-- crnn_process.cc             识别模型CRNN的预处理和后处理文件
|-- crnn_process.h
|-- db_post_process.cc          检测模型DB的后处理文件
|-- db_post_process.h
|-- Makefile                    编译文件
|-- ocr_db_crnn.cc              C++预测源文件

**Comment by LDOUBLEV** [comment]
这些文件在PaddleOCR/deploy/lite/下，部署时需要放在预测库的demo中，参考deploy/lite/readme.md的第四步。
![image](https://user-images.githubusercontent.com/26592129/87690416-059a5180-c7bc-11ea-9e7c-2ec5fcdf72cf.png)

明天写个脚本自动完成文件拷贝

**Comment by koala9527** [comment]
> 这些文件在PaddleOCR/deploy/lite/下，部署时需要放在预测库的demo中，参考deploy/lite/readme.md的第四步。
> ![image](https://user-images.githubusercontent.com/26592129/87690416-059a5180-c7bc-11ea-9e7c-2ec5fcdf72cf.png)
> 
> 明天写个脚本自动完成文件拷贝

谢谢，没看仔细
