### ISSUE TITLE
训练ppstructure出错

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3582]
I0807 11:46:34.981138 24888 nccl_context.cc:189] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0807 11:46:35.307796 24888 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.0
W0807 11:46:35.342660 24888 device_context.cc:372] device: 0, cuDNN Version: 7.6.
[2021/08/07 11:46:41] root INFO: Initialize indexs of datasets:/archive/pubtabnet/pubtabnet/PubTabNet_train.jsonl
W0807 11:47:24.176131 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:47:24.176129 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:47:33.859097 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:47:33.994922 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:47:56.473485 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:47:52.712929 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:01.534920 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:09.972973 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:11.362350 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:20.217123 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:23.692962 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:30.844411 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:32.065567 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:39.060076 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:42.790083 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:39.907958 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:57.002235 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:48:48.376204 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:10.428205 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:04.723089 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:13.019785 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:17.830086 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:27.100239 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:49:32.085688 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
[2021/08/07 11:49:41] root INFO: Initialize indexs of datasets:/archive/pubtabnet/pubtabnet/PubTabNet_val.jsonl
[2021/08/07 11:49:41] root INFO: train dataloader has 125194 iters
[2021/08/07 11:49:41] root INFO: valid dataloader has 1 iters
[2021/08/07 11:49:41] root INFO: During the training process, after the 0th iteration, an evaluation is run every 400 iterations
[2021/08/07 11:49:42] root INFO: Initialize indexs of datasets:/archive/pubtabnet/pubtabnet/PubTabNet_train.jsonl
W0807 11:50:21.570055 24832 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0807 11:50:21.570053 24920 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
已杀死

**Comment by cqray1990** [comment]
@littletomatodonkey 单卡跑的没问题，双卡分布式运行train.sh的时候就出现这个问题ncll已装

**Comment by littletomatodonkey** [comment]
你好 这个使用的是官方的docker吗？
