### ISSUE TITLE
copy_from_cpu 卡死

### ISSUE THREAD

**Issue by jellywong88** [PaddlePaddle/PaddleOCR#3583]
PaddlePaddle(GPU) 2.0.0
python3.7
cuDNN 7.6.5
cuda10.2
显卡：RTX3060Ti
显卡驱动：470.57.02

跑到predict_det.py下拷贝数据时卡死
self.input_tensor.copy_from_cpu(img)

**Comment by LDOUBLEV** [comment]
你的输入数据很大吗？
测试一张小的图像是否也会卡住

**Comment by hzwangjl** [comment]
和数据大小无关 ，感觉是Paddle底层对RTX3060卡的支持问题，我换了GTX1650卡是没问题的

**Comment by hzwangjl** [comment]
是不是RTX3060需要更新下cuda和cudnn？  是否有cuda和cudnn对应的匹配版本推荐？

**Comment by NextGuido** [comment]
> PaddlePaddle(GPU) 2.0.0
> python3.7
> cuDNN 7.6.5
> cuda10.2
> 显卡：RTX3060Ti
> 显卡驱动：470.57.02
> 
> 跑到predict_det.py下拷贝数据时卡死
> self.input_tensor.copy_from_cpu(img)

3090目前也不行

**Comment by kaaier** [comment]
> PaddlePaddle(GPU) 2.0.0 python3.7 cuDNN 7.6.5 cuda10.2 显卡：RTX3060Ti 显卡驱动：470.57.02
> 
> 跑到predict_det.py下拷贝数据时卡死 self.input_tensor.copy_from_cpu(img)

您好，请问您的问题解决了吗？ 是因为环境问题吗？
