### ISSUE TITLE
使用opt工具对检测模型转换时报错  can not found op arguments for node conv2_b_attr

### ISSUE THREAD

**Issue by kasyoukin** [PaddlePaddle/PaddleOCR#359]
[root@titanpx01 api]# ./opt --model_file=./ch_det_r50_vd_db/model --param_file=./ch_det_r50_vd_db/params --optimize_out_type=naive_buffer --optimize_out=./ch_det_mv3_db_opt --valid_targets=arm
[W  7/16 22:27:51.141 /data2/Paddle-Lite/lite/api/opt.cc RunOptimize:149] Load combined-param model. Option model_dir will be ignored
[I  7/16 22:27:51.141 /data2/Paddle-Lite/lite/api/cxx_api.cc Build:251] Load model from file.
[I  7/16 22:27:51.271 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_quant_dequant_fuse_pass
[I  7/16 22:27:51.303 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_quant_dequant_fuse_pass
[I  7/16 22:27:51.303 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: weight_quantization_preprocess_pass
[I  7/16 22:27:51.304 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: weight_quantization_preprocess_pass
[I  7/16 22:27:51.304 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_conv_elementwise_fuse_pass
[I  7/16 22:27:51.319 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 4 subgraph
[I  7/16 22:27:51.319 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_conv_elementwise_fuse_pass
[I  7/16 22:27:51.319 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_conv_bn_fuse_pass
[I  7/16 22:27:51.398 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 57 subgraph
[I  7/16 22:27:51.424 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 2 subgraph
[I  7/16 22:27:51.424 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_conv_bn_fuse_pass
[I  7/16 22:27:51.424 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_conv_elementwise_fuse_pass
[I  7/16 22:27:51.441 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_conv_elementwise_fuse_pass
[I  7/16 22:27:51.441 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_conv_activation_fuse_pass
[I  7/16 22:27:51.456 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 37 subgraph
[I  7/16 22:27:51.493 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_conv_activation_fuse_pass
[I  7/16 22:27:51.493 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_var_conv_2d_activation_fuse_pass
[I  7/16 22:27:51.493 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip lite_var_conv_2d_activation_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.493 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_fc_fuse_pass
[I  7/16 22:27:51.494 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_fc_fuse_pass
[I  7/16 22:27:51.494 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_shuffle_channel_fuse_pass
[I  7/16 22:27:51.495 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_shuffle_channel_fuse_pass
[I  7/16 22:27:51.495 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_transpose_softmax_transpose_fuse_pass
[I  7/16 22:27:51.495 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_transpose_softmax_transpose_fuse_pass
[I  7/16 22:27:51.495 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_interpolate_fuse_pass
[I  7/16 22:27:51.496 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: lite_interpolate_fuse_pass
[I  7/16 22:27:51.496 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: identity_scale_eliminate_pass
[I  7/16 22:27:51.496 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: identity_scale_eliminate_pass
[I  7/16 22:27:51.496 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: elementwise_mul_constant_eliminate_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: elementwise_mul_constant_eliminate_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: lite_sequence_pool_concat_fuse_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip lite_sequence_pool_concat_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: __xpu__resnet_fuse_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip __xpu__resnet_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: __xpu__multi_encoder_fuse_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip __xpu__multi_encoder_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: __xpu__embedding_with_eltwise_add_fuse_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip __xpu__embedding_with_eltwise_add_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: __xpu__fc_fuse_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip __xpu__fc_fuse_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: identity_dropout_eliminate_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip identity_dropout_eliminate_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: quantized_op_attributes_inference_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip quantized_op_attributes_inference_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: npu_subgraph_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip npu_subgraph_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: xpu_subgraph_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip xpu_subgraph_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: bm_subgraph_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip bm_subgraph_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: apu_subgraph_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip apu_subgraph_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: rknpu_subgraph_pass
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:215]    - Skip rknpu_subgraph_pass because the target or kernel does not match.
[I  7/16 22:27:51.497 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: static_kernel_pick_pass
[I  7/16 22:27:51.508 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:219] == Finished running: static_kernel_pick_pass
[I  7/16 22:27:51.508 /data2/Paddle-Lite/lite/core/optimizer.h RunPasses:202] == Running pass: variable_place_inference_pass
[F  7/16 22:27:51.513 ...core/mir/variable_place_inference_pass.h:124 InferenceArgumentPlace] Check failed: arg_name.size() > 0: can not found op arguments for node conv2_b_attr

**Comment by LDOUBLEV** [comment]
你用的Paddle-Lite是哪个版本，用paddlelite develop分支版本编译得到的opt是可以的转换的，2.6分支的不太行。

**Comment by kasyoukin** [comment]
@LDOUBLEV 用的2.6.2，使用develop确实好使
