### ISSUE TITLE
想修改评估过程代码，这段源码在哪能找到？

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3591]
def eval(*args, **kwargs): # real signature unknown
    """
    Evaluate the given source in the context of globals and locals.
    
    The source may be a string representing a Python expression
    or a code object as returned by compile().
    The globals must be a dictionary and locals can be any mapping,
    defaulting to the current globals and locals.
    If only globals is given, locals defaults to it.
    """
    pass

**Comment by MissPenguin** [comment]
是找这个吗：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/tools/program.py#L347
