### ISSUE TITLE
ppstructure bug

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3596]
环境：cuda10.0,cudann7.6
数据：PubTabNet_2
两块2080ti

单卡训练没有问题，双卡训练的时候batchsize=1了都挂掉，出现如下错误：

 During the training process, after the 0th iteration, an evaluation is run every 400 iterations
[2021/08/08 13:34:48] root INFO: Initialize indexs of datasets:/archive/pubtabnet/pubtabnet/PubTabNet_train.jsonl
W0808 13:35:25.852634  3872 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0808 13:35:25.852632  4000 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0808 13:35:38.788174  3872 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0808 13:35:48.391178  3872 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0808 13:35:40.979748  4000 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
INFO 2021-08-08 13:35:54,597 launch_utils.py:307] terminate all the procs
ERROR 2021-08-08 13:35:54,609 launch_utils.py:545] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2021-08-08 13:35:57,611 launch_utils.py:307] terminate all the procs

用top监控的时候swap空间有时侯可使用空间为0，然后程序挂掉，/dev/shm 空间是够的把，有8G，难道还跟swap空间有关？

**Comment by cqray1990** [comment]
@MissPenguin top - 17:59:48 up 21:39,  1 user,  load average: 2.41, 2.60, 2.58
任务: 321 total,   1 running, 239 sleeping,   6 stopped,   0 zombie
%Cpu(s): 13.8 us,  2.9 sy,  0.0 ni, 81.0 id,  0.0 wa,  0.0 hi,  2.4 si,  0.0 st
KiB Mem : 16319980 total,  7590340 free,  6657368 used,  2072272 buff/cache

有时候这个Swap free突然为0，我的/dev/shm为8G
KiB Swap:  8003580 total,   235632 free,  7767948 used.  9184120 avail Mem 
                           
进�� USER      PR  NI    VIRT    RES    SHR �  %CPU %MEM     TIME+ COMMAND     
 9784 root      20   0  556824  46876   8100 S  94.0  0.3  68:40.19 sunlogincl+ 
 1089 root      20   0 1161248   2068      0 S   8.0  0.0  59:52.67 sunlogincl+ 
  983 root      20   0  454440  56980  48128 S   5.6  0.3  55:02.59 Xorg        
 3456 lgx       20   0 4453432 123808  59852 S   3.3  0.8  16:55.38 gnome-shell 
 9317 lgx       20   0  855288  22460  12820 S   2.7  0.1   7:05.59 gnome-term+ 
 4952 lgx       20   0 8545524 1.132g  10672 S   2.0  7.3  34:56.81 java        
 3778 lgx       20   0 3326776  14884  13436 S   1.7  0.1  17:29.00 sunlogincl+ 
 4044 lgx       20   0 22.933g 12986

**Comment by cqray1990** [comment]
@MissPenguin 我用双卡测试，总数据20张图，测试10张batchsize=1，他能跑，然后用全部的数据50多万张，出现以上错误，bachsize仍是等于1

**Comment by cqray1990** [comment]
@MissPenguin 这个配置文件没有distributed信息，其他的配置也没有，然后这里分布式返回false，分布式不需要为True？

 if config['Global']['distributed']:
        model = paddle.DataParallel(model)

**Comment by cqray1990** [comment]
@MissPenguin 

Running verify PaddlePaddle program ... 
W0808 18:47:30.872273 16157 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.0
W0808 18:47:30.935014 16157 device_context.cc:372] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
W0808 18:47:34.772919 16157 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0808 18:47:34.773142 16157 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0808 18:47:43.231055 16229 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0808 18:47:45.892004 16157 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0808 18:47:46.008189 16157 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

Process finished with exit code 0

这个是版本问题导致？

**Comment by cqray1990** [comment]
@MissPenguin麻烦看下这个问题？，谢谢

**Comment by guijuzhejiang** [comment]
我也遇到这个问题,我训练同时开了visualdl看loss情况,后来把visualdl关了,/dev/shm空间就释放了.不知道适不适合你的情况
