### ISSUE TITLE
check paddle 出现Cannot enable P2P access from 0 to 1错误

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#3598]
run paddle.utils.run_check()：
W0808 18:51:25.743397 28427 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.0
W0808 18:51:25.751139 28427 device_context.cc:372] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
W0808 18:51:27.531513 28427 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0808 18:51:27.531538 28427 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0808 18:51:29.348312 28427 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

run paddle.fluid.install_check.run_check():
Running Verify Fluid Program ... 
W0808 18:53:15.186529  2059 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.0
W0808 18:53:15.188891  2059 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0808 18:53:16.860621  2059 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0808 18:53:16.860644  2059 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0808 18:53:18.696321  2059 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

**Comment by MissPenguin** [comment]
paddle安装问题建议去这里提个issue哈，会有更专业的同学帮忙解答：https://github.com/PaddlePaddle/Paddle
