### ISSUE TITLE
gen_label.py格式转化脚本

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3599]
一直报错

(paddlepaddle) C:\Users\H1CE\Desktop>python gen_label.py --mode="det" --root_path="C:/Users/H1CE/Desktop/data_enhancement/"  --input_path="C:/Users/H1CE/Desktop/icdar_label" --output_label="C:\Users\H1CE\Desktop\after_enhancement"
Traceback (most recent call last):
  File "gen_label.py", line 80, in <module>
    gen_det_label(args.root_path, args.input_path, args.output_label)
  File "gen_label.py", line 30, in gen_det_label
    with open(out_label, 'w',encoding='utf-8') as out_file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\H1CE\\Desktop\\after_enhancement'

**Comment by hice1207** [comment]
> 请问这个问题怎么解决的？我遇到了一样的问题。

很抱歉哥们，已经过去快两年了，对于这个问题我已经没有什么印象了。但是当时我遇到的大部分问题的解决法是对照着paddle给的教程尝试一遍，再对着自己的数据集修改，一般是格式问题。

**Comment by 1wang11lijian1** [comment]
OK，谢谢你的回答，刚刚我想到了答案，就是路径选择文件夹的时候后面不应该有斜杠

**Comment by hice1207** [comment]
> OK，谢谢你的回答，刚刚我想到了答案，就是路径选择文件夹的时候后面不应该有斜杠

不客气，祝科研顺利
