### ISSUE TITLE
请教！如何通过PaddleOCR实现百度OCR中的iOCR定位识别功能？

### ISSUE THREAD

**Issue by DEV-XiA** [PaddlePaddle/PaddleOCR#3600]
之前一直在使用百度OCR的iOCR功能API识别固定表格中的指定位置字段，想知道是否可以通过PaddleOCR或是pp-structure来实现类似的功能？

**Comment by MissPenguin** [comment]
pp-structure暂时没有提供识别key-value关系的功能，可以尝试基于ocr结果通过关键字匹配来实现这个功能。
