### ISSUE TITLE
android-demo

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#3601]
请问最新版的android-demo是什么版本的，有没有2.0版本或者更新版本的android-demo，看评论说有2.0的但是我在2.0的版本里并没有发现android的demo，如果使用的话只能在armv8的机器上使用么。

**Comment by MissPenguin** [comment]
最新的2.2分之下是有Android demo的，路径：deploy/android_demo/，支持2.0的ppocr模型。demo的部分我们提供一个打通的版本后不会频繁维护，所以模型升级或者做其他更新后出现不兼容的地方比较正常，需要自己调适下。
