### ISSUE TITLE
在训练时怎么指定config文件？AssertionError: Please specify --config=configure_file_path.

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3605]
报了program.py文件48行的断言提示，要求指定config文件，是每一次训练都要自己指定config文件吗，使用paddle提供的预训练模型也要自己指定config文件吗，网上的教程是在第42行“--config”, 后面添加default="指定的config文件"，可以用其他方式解决吗？
报错：
AssertionError: Please specify --config=configure_file_path.

**Comment by LDOUBLEV** [comment]
参考训练教程，参数文件是必须的，指定参数文件的例子：-c configs/det/det_mv3_db.yml

**Comment by BothCats** [comment]
已解决，必须手动改指定参数文件，

**Comment by Chuck-Zeng** [comment]
请问您是怎么加载该参数文件的呢？

**Comment by 201118abc** [comment]
我也想问这个问题 怎么加载该参数文件的呢？
