### ISSUE TITLE
移动端推理耗时越来越久的问题

### ISSUE THREAD

**Issue by Danvae** [PaddlePaddle/PaddleOCR#3606]
问题描述：使用android_demo文件夹的内容，把拍照识别图片换成预览框实时检测识别后（大概一秒会传好几张图片），推理变得越来越慢，需要三四秒才能识别出来，换用了2.1分支代码以及paddlelite2.9，同样有此问题，请问有何解决办法？

**Comment by LDOUBLEV** [comment]
是推理越来越慢吗，单独测试预测部分，连续预测多张图像，时间没有变慢

**Comment by Danvae** [comment]
我有打印c++每部分耗时，具体来说是两个部分变慢了，识别模型CRNN大概比之前慢17倍，文字方向检测cls也慢了8倍左右

**Comment by LDOUBLEV** [comment]
检测模型预测没有变慢吗？

打印c++每部分耗时，是infer的时间变慢了吗？https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/deploy/android_demo/app/src/main/cpp/ocr_ppredictor.cpp#L121

**Comment by Danvae** [comment]
是的，检测模型的infer时间变化不大，主要问题在rec和cls。目前demo里面只有一个页面，如果新增一个主页面用于跳转，再次进入识别会更慢，在安卓11上体现特别明显。

**Comment by WenmuZhou** [comment]
不实时预览的情况下，连续预测会变慢吗

**Comment by Danvae** [comment]
> 
> 
> 不实时预览的情况下，连续预测会变慢吗

我这边测试并不明显

**Comment by zhangyinzhangyin** [comment]
> 我这边测试并不明显

请问解决了吗？我发现连续预测内存不断增加
