### ISSUE TITLE
如何解压预训练模型？

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3610]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_ch/models_list.md
提供了三钟类型的模式供下载，如何解压预训练模型？
希望提供两种方式：
①Windows
②Linux

**Comment by LDOUBLEV** [comment]
压缩包都是tar结尾的，可以用tar xf 解压
