### ISSUE TITLE
ppyolov2基于publaynet的预训练模型可以给出吗？

### ISSUE THREAD

**Issue by gasoline23333** [PaddlePaddle/PaddleOCR#3611]
https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_publaynet.tar
在ppstruct下只有用于inference的模型文件，请问可以将inference文件转换为可以训练的预训练模型吗，或者是否有基于publaynet的预训练模型？

**Comment by littletomatodonkey** [comment]
你好，具体的链接如下：
https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_publaynet_pretrained.pdparams
