### ISSUE TITLE
数字识别不准确有什么办法吗？

### ISSUE THREAD

**Issue by xliu79** [PaddlePaddle/PaddleOCR#3612]
表盘上的数据，负号总是丢失。导致数值不准。
如图:
![3-12](https://user-images.githubusercontent.com/31554245/128669676-27ca9d6c-9c5a-4953-a609-e5aa58028d1c.jpg)

**Comment by xliu79** [comment]
一般数字前面有负号都会丢失，识别不出来。

**Comment by frkhit** [comment]
参考这篇文章 https://www.infoq.cn/article/tj485lufvqbsd9kkkpg0

```
对于一般的文字区域检测算法，单独出现的’+’、’-’等符号通常是被视作噪声的。我们的 Yolo 文字区域检测算法也倾向于将这些符号视作噪声。这个先验知识在大部分医学报告单上是可行的。但仍然有占总数比例很小的一些类别的报告单（如尿常规、便常规等）上面会出现这些字符，而这些字符在这些类报告单上代表的却是非常关键的意义：如‘+’通常代表阳性，‘-’通常代表阴性（如图 2.3 所示）。为更好地处理这些类别的报告单，我们仍然需要一种效果更好、可以检测出这些不起眼的小字符的文字区域检测算法。
```

**Comment by xliu79** [comment]
好的我试试

**Comment by LDOUBLEV** [comment]
> 一般数字前面有负号都会丢失，识别不出来。

看上去是没有检测到负号，建议在表盘数据上finetune训练下，多加一些带负号的标注数据参与训练
