### ISSUE TITLE
Convert PGNet to IR model

### ISSUE THREAD

**Issue by cpene1** [PaddlePaddle/PaddleOCR#3613]
Hi there!

I'm working on a project that needs very fast text spotting. I want to go for the PGNet model, since I've been working with it a couple of months ago and got impressive results. However, this time I need to work with OpenVino models, so the only workaround I can think of is converting to PaddlePaddle PGNet to ONNX and then ONNX to OpenVino. Is this a straightforward approach or should I think of something else?

Furthermore, is it going to work? Because when I was looking at the [Supported PaddlePaddle* Models via ONNX Conversion](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_paddlepaddle_models_via_onnx_conversion), I can only see a limited number of models that can be converted. What does that mean?

Thank you for support! :)

**Comment by LDOUBLEV** [comment]
Hi,
firstly, you can use [paddle2onnx](https://github.com/PaddlePaddle/Paddle2ONNX) to convert paddle pgnet inference model to onnx.
And then it is easily that convert onnx model to openvino.

**Comment by cpene1** [comment]
Alright, thank you! Will give it a shot and come back if problems encountered.

**Comment by ujjawalcse** [comment]
Hi @LDOUBLEV @cpene1 ,
Did you try to get inference using the .onnx model of pgnet inference model got from paddle2onnx?
I tried but getting the below issue.

```
(1, 3, 300, 300) 
NodeArg(name='x', type='tensor(float)', shape=[None, 3, None, None])

---------------------------------------------------------------------------

RuntimeException                          Traceback (most recent call last)

<ipython-input-21-90e728a110ab> in <module>()
     17 print(ort_sess.get_inputs()[0])
     18 ort_inputs = {ort_sess.get_inputs()[0].name: x}
---> 19 ort_outs = ort_sess.run(None, ort_inputs)
     20 print(ort_outs)
     21 print("Exported model has been predict by ONNXRuntime!")

/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in run(self, output_names, input_feed, run_options)
    186             output_names = [output.name for output in self._outputs_meta]
    187         try:
--> 188             return self._sess.run(output_names, input_feed, run_options)
    189         except C.EPFail as err:
    190             if self._enable_fallback:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_30' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:497 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 19 by 20
```
where (1, 3, 300, 300)  is my input to the onnx model and [None, 3, None, None] is expected by the model. Means there  is
no issue with the input.
Could you please share any view on this issue?
Thanks.

**Comment by cpene1** [comment]
Hi,

I personally haven't tried it yet, but your error seems weird. I'll reopen the issue so we can get some support :)

Thanks for your comment!

**Comment by zhangtaoshan** [comment]
> Hi,
> 
> I personally haven't tried it yet, but your error seems weird. I'll reopen the issue so we can get some support :)
> 
> Thanks for your comment!

Hi, have you solved this problem? I have encountered the same problem, and a add operator in the middle part of the model have a broadcast problem.
