### ISSUE TITLE
识别模型转ONNX后基于mobilenetv3的lite版的为什么反而比基于resnet34的common版慢

### ISSUE THREAD

**Issue by Kwongrf** [PaddlePaddle/PaddleOCR#3615]
20张图lite版模型平均0.976s, common版模型平均0.862s，是因为MobileNetV3结构的问题吗？将检测部分的backbone从resnet换成mobilenetv3也没有明显提速，平均0.865s

没转onnx之前20张图通过predict_system分别是lite版 0.496s， common版  0.522s。

**Comment by LDOUBLEV** [comment]
和网络结构有关系；
建议直接用Paddle 去部署
