### ISSUE TITLE
如何解决fine-tuning过拟合问题？

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3616]
在小语种finetuning 的过程中，发现训练的acc可以到80%，但是eval的acc只有30%-40%

**Comment by LDOUBLEV** [comment]
加[数据增强](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_ch/recognition.md#%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA)，加[正则](https://github.com/PaddlePaddle/PaddleOCR/blob/9cb073a7296b76c7e1ca3544731d258dbc90d303/configs/rec/rec_icdar15_train.yml#L48)，加数据

**Comment by LinXin04** [comment]
数据增强和正则分别怎么加呢？

**Comment by LDOUBLEV** [comment]
> 数据增强和正则分别怎么加呢？

上一条回复你的数据中有超链接，看下文档和配置文件的介绍

**Comment by LinXin04** [comment]
嗯，都加过了。还是有过拟合问题，现在在补充数据。目前用的ICDAR上的日文数据集，不过有点不明白，我们的预训练模型不是在ICDAR上做过训练了吗？怎么用同样的数据（虽然只有6k条）做fine tuning的时候，还是过拟合呢？
