### ISSUE TITLE
shared_memory在哪里可以关掉

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3617]
AIstudio报错
![QQ图片20210809193739](https://user-images.githubusercontent.com/51903595/128700499-fa977af4-a1a7-4059-86b6-5723713243a7.png)
在2.0以上版本的共享缓存怎么关？
如果不可关，怎样解决以上问题？

**Comment by LDOUBLEV** [comment]
AI studio上的共享内存比较小，只有64M，关闭共享内存可以在配置文件中设置use_shared_memory: False

参考：https://github.com/PaddlePaddle/PaddleOCR/blob/9cb073a7296b76c7e1ca3544731d258dbc90d303/configs/det/det_mv3_db.yml#L103

**Comment by BothCats** [comment]
谢谢，已成功解决
