### ISSUE TITLE
训练几小时后出错：阻塞队列被终止，因为数据读取器引发异常

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3621]
阻塞队列被终止，因为数据读取器引发异常
Blocking queue is killed because the data reader raises an exception
![tmpE0B5](https://user-images.githubusercontent.com/51903595/128709396-81fb4687-8fcb-4557-9a26-b3d8d47dfa9c.png)
不明原因，如何解决？而且训练中loss很大

**Comment by LDOUBLEV** [comment]
先确定数据格式是否正确，可以用tools/train.py 中的test_reader函数调试；
win上训练设置num_workers为0，不使用多进程数据读取试试；
