### ISSUE TITLE
lr维持稳定在0.000999，loss较大，如何解决？

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3622]
学习率是0.001，loss稳定在 3.0 附近 优化器采用的 Adam，训练icdar2015文本检测的模型，使用的mobilnetv3的预训练模型，bitch_size设置为14，每个256，loss从开始的8 附近降到3.0附近后没有太大变化，如何解？
参考之前一篇评论，说epoch迭代太大才导致的，如何修改？
这种问题怎么解决？
![tmp9DF6](https://user-images.githubusercontent.com/51903595/128713031-c28025db-f172-49cb-9ce1-730f9857e806.png)，
是不是应该设置更小的学习率？

**Comment by LDOUBLEV** [comment]
本身训练loss就很大，看你的loss在收敛，训练时间长一点评估看效果即可
