### ISSUE TITLE
训练过程被杀死DataLoader process (pid 3063) exited is killed by signal: Killed，怎么解决呢

### ISSUE THREAD

**Issue by xiaoyong001** [PaddlePaddle/PaddleOCR#3624]
![image](https://user-images.githubusercontent.com/49474119/128796993-601ce916-e048-4461-a7a8-f4f7b61b6199.png)

>

**Comment by tink2123** [comment]
尝试调小num_worker的数量吧，或者更新到dygraph分支训练
