### ISSUE TITLE
rec训练后在infer_rec.py识别效果很好，在predict_system.py及编译的C++上识别很差

### ISSUE THREAD

**Issue by 244668226** [PaddlePaddle/PaddleOCR#3627]
有个问题查了所有的issue也没解决， 我训练了rec模型后，用这个预训练模型运行infer_rec.py效果很好，但是我转完inference后用predict_system.py和我编译好的C++这两种方法识别效果都很差（模型位置都设置正确了，用的也是默认字典，图像尺寸也是默认的）
![image](https://user-images.githubusercontent.com/59698348/128803348-9dbc08f6-62ae-4e01-b815-249af7b2d046.png)
![image](https://user-images.githubusercontent.com/59698348/128803481-ce961ad9-2325-4cc1-a178-6883d4e4e93d.png)
![image](https://user-images.githubusercontent.com/59698348/128803498-d7a18322-3349-4c2b-b83c-92034dfb685b.png)

**Comment by tink2123** [comment]
可能检测模型和您的场景不适配？如果只需要识别的话，可以用 predict_rec.py 去预测

**Comment by 244668226** [comment]
> 可能检测模型和您的场景不适配？如果只需要识别的话，可以用 predict_rec.py 去预测

1. 我的最终目的是要在已经编译好的C++上运行，但是效果很差。
2. 您说的用predict_rec.py预测，因为我看了他是被predict_system.py调用的，我predict_system.py识别差，那predict_rec.py正常也会差吧。
3. 您说的场景不匹配，数据是大概w:h = 400 : 80的白底黑字且字体占比正常的图

**Comment by tink2123** [comment]
predict_system.py 是先对输入图片进行文本检测，得到检测框后送入识别。如果检测效果很差，会影响识别的效果。按您描述单独识别效果很好，因此建议首先测一下检测模型的效果。

另外C++代码正在更新中，可以下周等代码合入后重新测试。

**Comment by 244668226** [comment]
> predict_system.py 是先对输入图片进行文本检测，得到检测框后送入识别。如果检测效果很差，会影响识别的效果。按您描述单独识别效果很好，因此建议首先测一下检测模型的效果。
> 
> 另外C++代码正在更新中，可以下周等代码合入后重新测试。

好的

**Comment by Dandelion111** [comment]
> > predict_system.py 是先对输入图片进行文本检测，得到检测框后送入识别。如果检测效果很差，会影响识别的效果。按您描述单独识别效果很好，因此建议首先测一下检测模型的效果。
> > 另外C++代码正在更新中，可以下周等代码合入后重新测试。
> 
> 好的

请问您的问题解决了吗？我遇到了类似的问题，我是文本检测模型用python预测效果好，转为推理模型就不行了
