### ISSUE TITLE
多语种识别

### ISSUE THREAD

**Issue by LinnaWang76** [PaddlePaddle/PaddleOCR#3629]
如何获取文档中支持的80种语言推理模型？该文档中只有部分语言的模型链接。谢谢

**Comment by tink2123** [comment]
小语种模型按照字母被分为多类，可以参考代码中的分类标准下载相关模型：
https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/paddleocr.py#L156-L189

或者直接通过whl包安装使用：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_ch/whl.md

**Comment by LinnaWang76** [comment]
已解决。谢谢！
