### ISSUE TITLE
CRNN的Finetune问题

### ISSUE THREAD

**Issue by holasyb** [PaddlePaddle/PaddleOCR#3633]
hi ppocr的开发者。
在FineTune的时候，是应该直接使用ppocr提供的模型在新数据上训练还是应该掺杂一部分生成的图片以避免在新数据上的过拟合呢？
比如注意到ppocr给的mbv3模型识别空格有一定不足，是应该单独放一些英文含空格的数据来训练还是加一些中文图片避免损失了中文文字识别的能力。
如果要添加，大概数量和比例是怎样的呢？

**Comment by tink2123** [comment]
可以参考FAQ：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_ch/FAQ.md#q3159-%E4%BD%BF%E7%94%A8%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E8%BF%9B%E8%A1%8C%E9%A2%84%E6%B5%8B%E5%AF%B9%E4%BA%8E%E7%89%B9%E5%AE%9A%E5%AD%97%E7%AC%A6%E8%AF%86%E5%88%AB%E8%AF%86%E5%88%AB%E6%95%88%E6%9E%9C%E8%BE%83%E5%B7%AE%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3
