### ISSUE TITLE
初始化数据集索引卡住

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3635]
![tmp1A5](https://user-images.githubusercontent.com/51903595/128957407-84269a4b-9717-47f2-939e-4b6394ddf217.png)
PaddleOCR——文本识别——初始化数据集卡住，用的ICDAR数据集，Paddle提供的label标签，
[config文件.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6965359/config.txt)
这是使用的config文件和训练标签文件，为什么会在这里卡住呢，numworks设置为0也会出问题，降低bitchsize也会出这个问题。
[rec_gt_train.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6965362/rec_gt_train.txt)

**Comment by WenmuZhou** [comment]
看日志，这边猜测是在循环读取数据卡主了，可以在simpledataset的getitem函数里调试看看

**Comment by BothCats** [comment]
问题已解决，是数据集与模型不匹配导致的，可能把检测的数据集误以为训练的数据集了。

**Comment by Lebron-Harden** [comment]
![image](https://user-images.githubusercontent.com/74600923/132088760-c2e41de6-c1d5-4561-ba11-999797fceb60.png)

您好，我也遇到同样的问题了，请问怎么解决呢？
