### ISSUE TITLE
关于paddleocr 推理引擎内置的tensorrt相关问题

### ISSUE THREAD

**Issue by rainmakerMa** [PaddlePaddle/PaddleOCR#3636]
paddleocr使用paddle-inference推理引擎进行推理，在gpu上进行推理时，其内置了tensorrt推理引擎库，遇到以下问题，请问有没有相关专业人员能解答下：
 1. 开启tensorrt确实有加速效果，但是量化无加速效果，最新版本的paddleocr代码中，utility.py里面支持通过“precision”参数设置量化精度选项，实测只支持fp16, 开启int8选项报错，并且fp16不起任何加速效果，请问paddle-inference是如何做到在不更改模型文件的情况下，起到量化的效果的（实测fp16无任何加速） 是否有专业人员能说明下
 2. 查看paddle-inference推理引擎源码， from paddle import inference 相关api在哪查看，paddle官网文档结构较乱，跳转来跳转去还是没找到对应的api文档

**Comment by LDOUBLEV** [comment]
1. 新版本的paddle对量化模型没有加速的问题，已经在修复了；
> 请问paddle-inference是如何做到在不更改模型文件的情况下，起到量化的效果的（实测fp16无任何加速） 是否有专业人员能说明下

底层OP支持fp32， fp16， int8，所以可以支持fp16预测，int8预测

2. 预测部分常用API，可以参考：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html#api
