### ISSUE TITLE
pdserving web_service.py 疑问

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleOCR#3639]
![image](https://user-images.githubusercontent.com/53547082/128980275-2acc10f5-4813-4f4e-b5f5-e7c8a4304faa.png)
大佬请教下  pdServing 部署模型里面    在det pre里面已经计算出了 im  为什么要传递一个raw_im  到  rec pre里面再算一次呢 

我是想在前面加一个图片方向分类模型 感觉这边参数好像有点问题？

**Comment by WenmuZhou** [comment]
请问你这代码是哪个脚本里的

**Comment by wa3926** [comment]
@WenmuZhou  大佬你好 是在 deploy/pdserving/web_service.py  里面的  部署模型的

**Comment by WenmuZhou** [comment]
因为识别的流程可能单独使用，为了统一性
