### ISSUE TITLE
日文预训练fine-tuning的问题

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3640]
你好，我是在下面这个预训练模型上做的fine-tuning。
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md#%E8%AF%AD%E7%A7%8D%E7%BC%A9%E5%86%99

![image](https://user-images.githubusercontent.com/25193686/128981626-d45bf7b3-8142-47d2-9648-14ee805d56c4.png)

刚才认真看了一下该模型文件中的train.log，发现他本身的文件里就是训练train的acc在90%+，eval的best metirc只有在38%，我一直以为是我fine-tuning的过程过拟合了。是我对这两个输出理解错了吗？

![image](https://user-images.githubusercontent.com/25193686/128981696-0ba4051f-dfca-43e0-9076-ab76a14dcba6.png)

**Comment by LinXin04** [comment]
@tink2123 
所以这个日文的预训练模型在验证集真实数据上的acc只有38.5%？

可是我用真实数据做finetune，ICDAR，怎么也存在这么大的gap呢？

**Comment by LinXin04** [comment]
是这样的，我先用ICDAR的数据集一共6K条，做训练和验证，但是gap很大。

后面又用我自己的真实数据集做训练&验证，gap也很大

**Comment by latawangzi** [comment]
你数据集多大？
