### ISSUE TITLE
PGNet数据读取失败

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3642]
paddle2.1.1 拉去PaddleOCR版本2.2
数据集使用官方提供的地址
![image](https://user-images.githubusercontent.com/65577659/128999763-11140c22-e363-40cb-816f-bb404a53d4e8.png)

但训练时预训练模型加载成功,数据读取异常
![image](https://user-images.githubusercontent.com/65577659/128999787-68917534-b34b-4b97-b5de-39c6c48a64da.png)

![image](https://user-images.githubusercontent.com/65577659/128999873-b3f30449-de83-49c7-98bf-ec4f3bc5033b.png)
是什么原因呢?

**Comment by WenmuZhou** [comment]
麻烦贴一下报错谢谢和运行的config log

**Comment by qqqqq127** [comment]
是什么问题呢？

**Comment by lin-0015** [comment]
> 是什么问题呢？

记得是数据集结构的问题.
