### ISSUE TITLE
PGNet parallelize for multiple photos prediction

### ISSUE THREAD

**Issue by cpene1** [PaddlePaddle/PaddleOCR#3643]
Hi and thank you for the support!

I need to process multiple photos (usually quite small cause they are basically crops) and have worked with the ppocr PGNet in the past (amazing model btw). Usually in torch it's really easy to process multiple inputs at once, parallelizing the job on the GPU. Is there a way to do this in ppocr, specifically by using PGNet? Because the inference tutorial processes input photos 1 by 1, and this is quite slow.

PS: To give a bit of context, from a real-time video of 2K resolution, I crop multiple regions of interest and feed them to the PGNet model. But this drops my FPS incredibly much from obvious reasons. So I am looking for a way to process those regions of interest as fast as I can. My idea is to feed all ROIs at once and just lose time as I would for predicting 1 photo. What do you think?

As a last note, from my initial benchmarks, most of the time lost is for GPU->CPU copy (see below lines). Do you have any ideas/advice?

https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/tools/infer/predict_e2e.py#L112-L114

Thanks again for your support! Been enjoying ppocr for quite some time now! :+1:

**Comment by LDOUBLEV** [comment]
Hi there, your can speed up the  PGNet prediction by using multiprocessing like https://github.com/PaddlePaddle/PaddleOCR/blob/864ad073ab02ceab5a23020a3972efd46f45346d/tools/infer/predict_system.py#L180.

> My idea is to feed all ROIs at once and just lose time as I would for predicting 1 photo. What do you think?

When the inputs is a cropped image, I guess that most of the time is spent on preprocessing and postprocessing. In addition, batchsize also has an impact. I found that the average prediction speed when the batch size is 6 is faster than the average prediction speed when the batch size is 10.

> As a last note, from my initial benchmarks, most of the time lost is for GPU->CPU copy (see below lines). Do you have any ideas/advice?

You may have this problem when your input is large. 

when the input image resolution is 960, copy_crom_cpu is not very time-consuming for me with paddlepaddle-gpu==2.1.2.

**Comment by cpene1** [comment]
Hi and thank you for your reply!
>I found that the average prediction speed when the batch size is 6 is faster than the average prediction speed when the batch size is 10.

Thank you for the advice, I played with the batch size number for a bit and found no significant improvements. But it's a good point to keep in mind.

Multiprocessing is a very good idea. However, I really couldn't find a significant difference in speed prediction. For example for 5000 images I get the following benchmark:
- 1 proc: 171s
- 2 proc: 143s
- 3 proc: 138s

I have to mention I only have 1 GPU, so it's a Single GPU Multiprocessing which I know from other articles that usually go into deadlocks and don't improve that much the prediction performance. Do you think this is the case here as well? Do the benchmarks make sense to you?
> when the input image resolution is 960, copy_crom_cpu is not very time-consuming for me with paddlepaddle-gpu==2.1.2.
You are right, I analyzed again my benchmarks and copy_from_cpu was problematic only in the first couple of predictions, then it went close to nothing.

**From here it becomes interesting**

However, *and this is really interesting*, copy_to_cpu (so GPU to CPU) is very problematic when using multiprocessing (at least on 1 GPU). This is probably the point when it goes into some deadlocks and some of a process' copy has to wait for another. This is my benchmark for the avg copy_to_cpu time for 100 inputs from 1 to 3 processes:

```
1 proc -> average GPU to CPU copy: 0.0014777326583862306
2 proc -> average GPU to CPU copy: 0.02126596450805664
3 proc -> average GPU to CPU copy: 0.041829557129831024
```

The rest of the operations stay completely constant, so this is the part where I lose a lot of time. I assume if I was using multiple GPUs this wouldn't happen and it makes sense (at least I hope it wouldn't happen).

But why do we copy_to_cpu after every single prediction? Couldn't we improve our performance by copying the Tensors at the very end, all together? Because I assume this should be possible, regardless of the Tensor shape. And then we do postprocessing at the very end, since we don't need the predictions straight away (or at least in this specific case).

If we do that, we could have a clean reduction of the prediction time by a factor of total_process_num (almost). And this is not only for a single GPU, but also for multiple ones I assume the same thing happens if we load more models than GPUs available (at least for some of the processes).

What do you think? Thanks again for your support! :)

**Comment by LDOUBLEV** [comment]
> Thank you for the advice, I played with the batch size number for a bit and found no significant improvements. But it's a good point to keep in mind.

This is just a trick. Don't worry if it doesn't work. 

Your analysis is very enlightening. 
The copy_to_cpu completes the copy of the prediction output from the GPU to the CPU, because the post-processing process is completed on the CPU. 
The reason why the first prediction is time-consuming is that the first run needs to be initialized, and the prediction speed will be much faster after the second run.
My guess is that process blocking caused the copy_to_cpu to take a long time when there were multiple processes.

>  Couldn't we improve our performance by copying the Tensors at the very end, all together?

It is a good point. And we haven't noticed the problem of multi-process prediction causing excessive data copying time. I will report this issue and discuss how to deal with it. This requires the cooperation of other developers.

I have a question, what is the speed bottleneck you are encountering now, that is, which part seriously affects your FPS.
In addition to the time consumed by predict, pre-processing and post-processing are also time-consuming, because this part is done on the CPU.

If you want to speed up the predictor.run(), another way is to turn on TensorRT, which is expected to speed up by 20-30%.
https://github.com/PaddlePaddle/PaddleOCR/blob/864ad073ab02ceab5a23020a3972efd46f45346d/tools/infer/utility.py#L37
(The premise is that the paddle you installed supports TRT prediction.  The version of paddlepaddle-gpu large than 2.1 is OK.)

**Comment by cpene1** [comment]
> The reason why the first prediction is time-consuming is that the first run needs to be initialized, and the prediction speed will be much faster after the second run.

Yeah I assumed so, that's why I also make some dummy predictions before (I saw you are also doing some warmup before, in your predict_system.py).

> It is a good point. And we haven't noticed the problem of multi-process prediction causing excessive data copying time. I will report this issue and discuss how to deal with it. This requires the cooperation of other developers.

It's nice to hear! I would be happy to contribute to this issue. After your internal discussion, let me know whether or not I can be of help. I really need this to work so, as I said, happy to help wherever I can.

> I have a question, what is the speed bottleneck you are encountering now, that is, which part seriously affects your FPS.

To be honest, besides from this multiprocessing issue, there's not much I can personally do in my project. It depends on the number of ROIs I have to analyze which is variable (10 to 30). The most time is spent on the prediction step itself, but there's not much we can do there. So by using multiprocessing, this would speed up my total predictions a lot. And this is how I found out of this copy_to_cpu bottleneck when using multiprocessing. But the prediction itself is the one that is the most time-consuming (again, not much to be done here I guess).

> In addition to the time consumed by predict, pre-processing and post-processing are also time-consuming, because this part is done on the CPU.

Here is my complete benchmark for 1000 input images run on 1-3 processes. As you can see, everything looks fine except to gpu_cpu. So fixing that should fix the **biggest issue**. I will think of optimizations for the pre and post processing. At a first thought, it is what it is.

|              | 1        | 2        | 3        |
|--------------|----------|----------|----------|
| avg_preproc  | 0.001495 | 0.001674 | 0.001947 |
| avg_cpu_gpu  | 0.000066 | 0.000081 | 0.000090 |
| avg_pred     | 0.027468 | 0.028132 | 0.029060 |
| avg_gpu_cpu  | 0.001896 | **0.022343** | **0.045012** |
| avg_postproc | 0.001710 | 0.001987 | 0.002116 |

For more processes the problem should be even bigger. I would try with 4+, but I have only have 6GB gpu memory (NVIDIA Quadro RTX 3000), and the PGNet model has 1.8GB already.

> If you want to speed up the predictor.run(), another way is to turn on TensorRT, which is expected to speed up by 20-30%.

That sounds very nice, thanks for the advice! However, I get the following error and I can't find an answer in English: ( I have paddlepaddle-gpu==2.1.2.post110 )

```
  File "/.../ppocr/tools/infer/predict_e2e.py", line 79, in __init__
    self.predictor, self.input_tensor, self.output_tensors = utility.create_predictor(
  File "/.../ppocr/tools/infer/utility.py", line 160, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:216)
```

**Comment by LDOUBLEV** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

You can download paddlepaddle-gpu whl which support trt prediction. 

![image](https://user-images.githubusercontent.com/26592129/129997578-69549c02-54b5-4df9-ad11-66122c118ddb.png)

**Comment by cpene1** [comment]
Yes, I have that exact one for CUDA 11.0
To make sure I installed it again using your link and I still experience the same problem.

![image](https://user-images.githubusercontent.com/59665541/130038109-1e49c41f-fe20-471e-8c45-585a9c86ba69.png)

**Comment by cpene1** [comment]
It seems that paddlepaddle-gpu2.1.2 for CUDA 11.0 does not come with TensorRT

**Comment by cpene1** [comment]
Hi! Any advice on this issue? I got it working with version paddlepaddle_gpu-0.0.0.post110-cp38-cp38-linux_x86_64, but I would prefer a stable release.

**Comment by cpene1** [comment]
Closing this for now.
Issue continued in #4108
