### ISSUE TITLE
倾斜角度文本的检测和识别

### ISSUE THREAD

**Issue by xuhui1994** [PaddlePaddle/PaddleOCR#3645]
想咨询一下作者，倾斜角度文本的检测和识别不是很理想，怎么只设置检测和识别水平和垂直的文本，忽略倾斜角度的文本

**Comment by WenmuZhou** [comment]
可以跟根据检测到的文本框角度来判断是不是倾斜框，然后进行过滤

**Comment by xuhui1994** [comment]
> 可以跟根据检测到的文本框角度来判断是不是倾斜框，然后进行过滤
刚接触paddleOCR，找了很长时间没找到这部分文本框角度代码，请问你了解这部分代码吗

**Comment by WenmuZhou** [comment]
paddleocr没有这部分代码，需要自己添加
