### ISSUE TITLE
Arabic model is not performing well

### ISSUE THREAD

**Issue by soufieneghribi** [PaddlePaddle/PaddleOCR#3649]
Can anyone give us a description about the Arabic model and the data used for training?

I have tested it over several images but it is giving very poor results.

**Comment by tink2123** [comment]
Try to update paddleocr==2.6.0.1

**Comment by MohieEldinMuhammad** [comment]
@tink2123 
Thanks for your effort, 2.6 is the least version on pip and it solves some problem but still the performance is not close from English performance.

See this example:

![image](https://user-images.githubusercontent.com/89604782/187903864-e90ab93d-4b21-4a38-8e65-704c40da9bb3.png)

although the detection is good but the output is wrong in order
```
تتمكن
ِقطع كَلُ َعَة َّي
أن
هلا
تجمع
على
كان
T .
تستطع
ولكنها
لهم
خمإرا
بها
من
تفرئى
أن
حاولى
لَها
فَقالّ
يساعدَها
أن
أبيها
كجإ
ك
ولكتنى
فقالت
فقطع
قطعة
``

**Comment by MohieEldinMuhammad** [comment]
@tink2123 @WenmuZhou @sdcb
