### ISSUE TITLE
训练数据加载出错

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3651]
训练识别模型，加载自己的训练数据，能够正常训练几个iter，没有问题。但是之后报错
DataLoader reader thread raised an exception.
all input arrays must have the same shape.

检查过，所有数据都统一到了一个尺寸。

**Comment by ziyaxuanyi** [comment]
发现bug:
在ppocr/data/imaug/label_ops.py的288到294行：
if len(text) >= self.max_text_len:
    return None
data['length'] = np.array(len(text))
text = [0] + text + [len(self.character) - 1] + [0] * (self.max_text_len
                                                       - len(text) - 2)
data['label'] = np.array(text)
return data

当text文本长度恰好是self.max_text_len-1的时候，由于要加sos和eos两个特殊符号，经过填充后text文本长度会变成self.max_text_len+1，从而导致输入数据形状不一致。
应当将if len(text) >= self.max_text_len:改为if len(text) >= self.max_text_len-1

**Comment by littletomatodonkey** [comment]
你好，这个训练的是什么模型呢？

**Comment by ziyaxuanyi** [comment]
识别模型
