### ISSUE TITLE
检测训练在测试集上非常慢，有加速的方法吗？

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#3652]
检测训练时，在测试数据集上只能设置：batch_size_per_card: 1 # must be 1
这样导致测试的速度非常慢。请问有加速的方法吗？

**Comment by littletomatodonkey** [comment]
可以去掉一些数据增广看下，不过bs没法改大的话，建议找一些显存更大的设备哈

**Comment by ronaldpan** [comment]
测试数据集没有使用数据增广。
