### ISSUE TITLE
import layoutparser 出错TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by CC-todo** [PaddlePaddle/PaddleOCR#3657]
根据这个安装pip3 install -U https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
但是import layoutparser as lp报错TypeError: expected string or bytes-like object

**Comment by littletomatodonkey** [comment]
你好，使用的python版本是多少呢？我这边测试3.6/7没啥问题

**Comment by CC-todo** [comment]
> 你好，使用的python版本是多少呢？我这边测试3.6/7没啥问题

python3.7 cuda10.1改为10.0就解决了
