### ISSUE TITLE
 FatalError: Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by liuvvss** [PaddlePaddle/PaddleOCR#3658]
版本、环境信息：
   1）PaddlePaddle版本：paddlepaddle-gpu=2.1.2
   2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
   3）GPU：显卡2080Ti cuda10.2 libcudnn.so.7.5.0
   4）系统环境：linux、Python3.7
注：您可以通过执行summary_env.py获取以上信息。
安装方式信息：
1）pip安装

![2](https://user-images.githubusercontent.com/88772225/129170613-f9b2424b-8ed0-4180-ba00-579d77eb2465.png)

输入 python tools/train.py -c configs/rec/rec_icdar15_train.yml
报错 FatalError: Blocking queue is killed because the data reader raises an exception.
[Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
[operator < read > error]

**Comment by littletomatodonkey** [comment]
你好，把配置文件中的num worker修改为0看下呢？
