### ISSUE TITLE
paddleocr --image_dir=../doc/table/1.png --type=structure 后没有输出excel文件

### ISSUE THREAD

**Issue by prudence312** [PaddlePaddle/PaddleOCR#3661]

**Comment by 934453938** [comment]
我这边也没有输出excel文件，只有.jpg和.txt两个文件

**Comment by CastleDream** [comment]
同样加一，也只有一个jpg文件和一个txt文件，而且我输出的.jpg文件和原图一模一样，同时txt文件为空

**Comment by CastleDream** [comment]
我之前由于服务器cuda版本是11.1，没法使用11.2的镜像，所以选择了 paddlepaddle/paddle:2.1.2-gpu-cuda10.2-cudnn7这个老的镜像，后来发现运行速度特别慢，GPU加载到1GB的数据大概需要半小时左右，后来发现应该是环境问题，换了paddlepaddle/paddle:2.1.2这个cpu版本的镜像就可以跑出来了，尝试更换镜像 @934453938 @prudence312
