### ISSUE TITLE
使用en_number_mobile_v2.0_rec_infer识别数字，但结果显示为中文

### ISSUE THREAD

**Issue by westwind1027** [PaddlePaddle/PaddleOCR#3664]
命令行如下：
python3 tools/infer/predict_system.py --image_dir="/paddle/images/lednum2.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/en_number_mobile_v2.0_rec_infer_org/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=False --use_space_char=False

请帮忙看下是哪里出了问题啊？预测得到的图片如下。
![image](https://user-images.githubusercontent.com/67861529/129312531-dbdb9878-4eea-46ce-8ccb-682a2259b294.png)

**Comment by mydhui** [comment]
应该是label字典用错了，有两个参数，一个是引用字典的path，一个是中英文char，调一下试试

**Comment by MissPenguin** [comment]
楼上正解，检查下字典是否正确

**Comment by westwind1027** [comment]
> 应该是label字典用错了，有两个参数，一个是引用字典的path，一个是中英文char，调一下试试

将这两个参数改为如下，并将算法改为‘SRN’（默认是CRNN好像是针对中文，SRN好像是对应en）
--rec_char_type='en' --rec_char_dict_path='./ppocr/utils/dict/en_dict.txt' --rec_algorithm='SRN'

但仍然报错：
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2102, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1, the input's shape is [6, 1, 32, 320]; the filter's channels is 3, the filter's shape is [8, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:96)

是否是("--rec_image_shape", type=str, default="3, 32, 320")这个rec_image_shape也需要修改啊？

**Comment by westwind1027** [comment]
> 应该是label字典用错了，有两个参数，一个是引用字典的path，一个是中英文char，调一下试试

找到解决方法了，应该是把rec_char_type改为'EN_symbol'，最终的命令行是：
python3 tools/infer/predict_system.py --image_dir="/paddle/images/lednum2.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/en_number_mobile_v2.0_rec_infer_org/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True --**rec_char_type='EN_symbol'**

识别结果如下：(虽然还是有点问题，将小数点'.'识别为了'}'。感觉是‘EN_symbol’对应的字典与‘en_number_mobile_v2.0_rec_infer’使用的字典还是有区别)
![image](https://user-images.githubusercontent.com/67861529/130722372-0cb1ac09-b9b6-47dd-bc48-993b736e30bc.png)
