### ISSUE TITLE
PaddleOCR想同时识别韩文和英文,语言应该怎么设置?

### ISSUE THREAD

**Issue by rpaeng** [PaddlePaddle/PaddleOCR#3667]
ocr = PaddleOCR(lang="korean")
比如一张图片上有韩文和英文,检测到的英文就不准,该怎么设置语言参数?

**Comment by MissPenguin** [comment]
目前要实现韩文和英文同时识别，只能选择韩文，因为韩文识别训练时有加入英文数据，但是因为数据量的关系整体效果可能会差一些，建议补充数据进行finetune
