### ISSUE TITLE
读取训练集标签不明原因报错，训练集与icdar2015训练集标签格式一样

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3668]
是以下问题的表达：
https://github.com/PaddlePaddle/PaddleOCR/issues/3663

问题文件目录：
PaddleOCR-2.2/ppocr/data/simple_dataset.py -- 118行 outs = transform(data, self.ops)

问题 “方法” 源码：
PaddleOCR-2.2/ppocr/data/imaug/__init__.py
def transform(data, ops=None):
    """ transform """
    if ops is None:
        ops = []
    for op in ops:
        data = op(data)
        if data is None:
            return None
    return data

请详细描述该方法是如何运作的，原理和目标，ops是什么。

**Comment by MissPenguin** [comment]
您好，如上一条issue回复，检查下生成的数据格式哈。
