### ISSUE TITLE
推理问题

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleOCR#3669]
我下载了推理模型，按照给定的命令运行
模型路径到文件名的时候不给后缀，ValueError: Model pretrain path /model/ch_ppocr_mobile_v2.0_cls_infer/inference does not exists.报这样的错误，请问可以更新下文档吗，上边刚说了Global.checkpoints指定权重，下边就用了Global.pretrained_model，并且用了它会报那样的错误

**Comment by ziyaxuanyi** [comment]
Global.checkpoints和Global.pretrained_model都是在训练模型的时候指定的，都是指定的预训练模型或者中途保存的权重模型。你下载的推理模型inference是适合推理作推理用的，由训练模型导出的，只适合做推理，不是用来训练的。不知道你想表达什么意思

**Comment by MissPenguin** [comment]
楼上正解，Global.checkpoints和Global.pretrained_model都是在训练模型的时候指定的，你下载的是推理模型，想做训练的话可以下载“预训练模型”，Global.checkpoints用于断点继续训练，一般是模型训练中断后继续训练，参数不做任何修改，其他情况用Global.pretrained_model
