### ISSUE TITLE
Best Combination of models to use on Edge Device like RPi or Jetson Nano 

### ISSUE THREAD

**Issue by ujjawalcse** [PaddlePaddle/PaddleOCR#3671]
Hey,
Thanks for the PGNet implementation.
I tested end to end with little bit modification and also tested on real-time videos. 
But It's that fast to operate in real-time with low PC configuration or only CPU devices.
Can anyone suggest the best combination of model that can be used on RaspberryPi4 or Jetson Nano?
If anyone has already tried, please share some useful link.
Thanks.

**Comment by MissPenguin** [comment]
Thanks for your attention. If you want to achieve real-time on devices with insufficient computing power such as CPU, it is recommended to use ppocr mobile series models, which have been  verified on mobile devices.

**Comment by ujjawalcse** [comment]
Thanks @MissPenguin .
