### ISSUE TITLE
官方提供的通用模型使用了哪些数据集训练？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleOCR#3672]
官方提供的通用模型使用了哪些数据集训练？
我想在这些数据集的基础上添加我的数据集。

这些数据集有提供下载吗？

![微信截图_20210816180037](https://user-images.githubusercontent.com/26297768/129546661-a21486cb-bf8e-4349-a828-f4636a28c22f.png)

**Comment by MissPenguin** [comment]
您好，识别模型的训练数据主要是公开数据集和合成数据，合成数据的工具是开源工具[text_renderer](https://github.com/Sanster/text_renderer)，合成好的数据暂时不会开源哈，可以自己搜集语料用这个工具合成。

**Comment by yeyupiaoling** [comment]
好的
