### ISSUE TITLE
GPU无法释放

### ISSUE THREAD

**Issue by yuxx0218** [PaddlePaddle/PaddleOCR#3673]
PaddleOCR-2.1分支。
显存无法释放。
inference完了之后，用time.sleep睡个几分钟，就会发现，显存在这期间根本无法释放。只有sleep结束，进程关掉，显存才会释放。
换句话说，copy_from_cpu的tensor，可能一直存在predicter的内部，只要程序不停止，predicter一直在，拷贝到gpu的tensor就一直不会释放。
而实际项目部署的时候，不可能每访问一次ocr，就重新创建一个predicter的，所以这个一个非常重大的bug。

**Comment by yuxx0218** [comment]
predictor.try_shrink_memory()
predictor.clear_intermediate_tensor()
都是不好使的。
@MissPenguin

**Comment by yuxx0218** [comment]
测试发现，cpu也有同样的问题，安卓也是。实际工程项目就完全无法使用了。有解决办法吗？如果没有，下一个版本会优化吗？

**Comment by yuxx0218** [comment]
测试发现，内存也有同样的问题，安卓内存也是。实际工程项目就完全无法使用了。有解决办法吗？如果没有，下一个版本会优化吗？

**Comment by yuxx0218** [comment]
@MissPenguin 目前有办法吗？这个后面会修复吗？

**Comment by MissPenguin** [comment]
您好，Paddle目前的机制就是这样的哈，进程结束才会释放显存，这个是框架特性，PaddleOCR这边不会在这方面做优化呢。。
