### ISSUE TITLE
Nvidia jetson nano下载官方预测库运行报错

### ISSUE THREAD

**Issue by ycdhqzhiai** [PaddlePaddle/PaddleOCR#3674]
下载预测库:https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html
<html>
<body>

Jetpack4.4: nv-jetson-cuda10.2-cudnn8-trt7(nano)
--

<br class="Apple-interchange-newline">
</body>
</html>

运行cpp_infer，设置use_gpu=1 use_tensorrt=1.报错Illegal instruction (core dumped).
求解答，困扰好久了。自己编译paddle源码，一大堆依赖下载不下来

**Comment by LDOUBLEV** [comment]
use_gpu=0 use_tensorrt=0
use_gpu=1 use_tensorrt=0
上述配置是否能运行？

你的机器上是否安装了TRT？

报错信息可以发全一点，截个图

**Comment by ycdhqzhiai** [comment]
> use_gpu=0 use_tensorrt=0
> use_gpu=1 use_tensorrt=0
> 上述配置是否能运行？
> 
> 你的机器上是否安装了TRT？
> 
> 报错信息可以发全一点，截个图或者拍个照片

测试图片为doc/imgs/12.png (1150*720)
1.use_gpu=0 use_tensorrt=0 可以运行，推理需要16s
2.use_gpu=1 use_tensorrt=0 可以运行 ，推理需要600ms

已经安装TRT，能够正常运行其他trt模型

3.use_gpu=1, use_tensorrt=1段错误，报错
![image](https://user-images.githubusercontent.com/12273405/129667063-2369d650-0507-4bb5-a930-1e98e84e9e28.png)

**Comment by wangye707** [comment]
@ycdhqzhiai  你好，从日志看你是jetpack4.6的系统吗？我看你是TensorRT8,目前官方暂未正式支持该版本，下个版本将支持。预计发版时间9月初

**Comment by ycdhqzhiai** [comment]
好的，期待下一版更新。谢谢
