### ISSUE TITLE
Supports optical character recognition for Vietnamese 

### ISSUE THREAD

**Issue by longtran84** [PaddlePaddle/PaddleOCR#3676]
Please help me on Vietnamese. Thanks in advance

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_en/multi_languages_en.md

It is support vietnamese recognition now.

**Comment by khanh41** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_en/multi_languages_en.md
> 
> It is support vietnamese recognition now.

I see in the link you sent that it supports Vietnamese, but when I tried it, it was completely wrong.

**Comment by doduythao** [comment]
Yes, big problem here is no tone marks in vi lang.
