### ISSUE TITLE
将“ch_ppocr_mobile_v2.0_rec”模型从onnx转为openvino时出现问题

### ISSUE THREAD

**Issue by HanGuangXin** [PaddlePaddle/PaddleOCR#3678]
开发者们你好！非常感谢你们在PaddleOCR中精彩的工作！
最近我在将“ch_ppocr_mobile_v2.0_rec”模型从onnx转为openvino时遇到了问题，无法导出得到正确的openvino模型。
我已经验证过从paddlepaddle推理模型到onnx的转换是完全正确的，二者具有几乎完全一致的输出结果：

inference with inference model
```python
python tools/infer/predict_rec.py --image_dir="onnx_input_demo_ppocr.jpg" --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/"
# [2021/08/13 21:53:59] root INFO: Predicts of onnx_input_demo_ppocr.jpg:('鲁UR565', 0.71912557)
```
inference with onnx
```python
python onnx_inference/predict_rec.py --image_dir="onnx_input_demo_ppocr.jpg" --rec_model_dir="inference/ch_ppocr_mobile_v2.0_rec_infer/model.onnx" --use_angle_cls=False --rec_char_dict_path ppocr/utils/ppocr_keys_v1.txt --vis_font_path inference/ch_ppocr_mobile_v2.0_rec_infer/simfang.ttf
# [2021/08/13 21:53:20] root INFO: Predicts of onnx_input_demo_ppocr.jpg:('鲁UR565', 0.7191264)
# [2021/08/13 21:53:20] root INFO: Total predict time for 1 images, cost: 0.003
```

当从onnx转换到openvino时，我得到了以下的warning（每种warning只截取了一部分）：
```bash
[ WARNING ]  Skipped <class 'extensions.front.AttributedGatherNormalizer.AttributedGatherNormalizer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.InterpolateNormalizer.InterpolateNormalizer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.Log1p.Log1p'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.Pack.Pack'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.PowerToEltwises.PowerToEltwises'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.tf.FakeQuantWithMinMaxVars.FakeQuantWithMinMaxVarsToQuantize'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.eltwise_n.EltwiseNReplacement'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.rank_decomposer.RankDecomposer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.image_scaler.ImageScaler'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.instance_normalization.InstanceNormalization'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.reciprocal.ReciprocalReplacer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.softsign_replacer.SoftSign'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.split_normalizer.SqueezeAxis'> registration because it was already registered or it was disabled. 

[ WARNING ]  Skipped <class 'mo.front.common.replacement.FrontReplacementSubgraph'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.user_data_repack.UserDataRepack'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'mo.front.tf.replacement.FrontReplacementFromConfigFileGeneral'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.ATenToEmbeddingBag.AtenToEmbeddingBag'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.AttributedClampNormalizer.AttributedClampNormalizer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.AttributedPadToPad.AttributedPadToPad'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.ChangePlaceholderTypes.ChangePlaceholderTypes'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.ExpandDimsToUnsqueeze.ExpandDimsToUnsqueeze'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.FillToBroadcast.FillToBroadcast'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.GeLUMerger_Erf.GeLUMergerErf'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.InterpolateV1ToInterpolate.InterpolateV1ToInterpolate'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.LayerNorm.LayerNorm'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.pass_separator.FrontStart'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.pass_separator.FrontFinish'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.OneHotDepthNormalizer.OneHotDepthNormalizer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.SqueezeNormalize.SqueezeNormalize'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.ThresholdedReluDecomposition.ThresholdedReluDecomposition'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.TopKNormalize.TopKNormalize'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.tf.pad_tf_to_pad.PadTFToPad'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.binary_quantize_normalization.BinaryFakeQuantizeNormalization'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.create_tensor_nodes.CreateTensorNodes'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.disable_weights_quantize_value_propagation.DisableQuantizeValuePropagation'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.div.Div'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.global_pooling_to_reduce.GlobalPoolingToReduce'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.input_cut.InputCut'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.interpolate_reshape.InterpolateWithConcat'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.output_cut.OutputCut'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.override_batch.OverrideBatch'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.scatter_normalizer.ScatterNormalizer'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.sub.Sub'> registration because it was already registered or it was disabled. 
[ WARNING ]  Skipped <class 'extensions.front.transformations_config.TransformationsConfig'> registration because it was already registered or it was disabled. 

[ WARNING ]  Converting type of Const node "Squeeze_0/Dims/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_0/Cast_124756_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_1/Cast_124674_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_2/Cast_124696_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_3/Cast_124706_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_4/Cast_124752_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Reshape_18/Cast_124668_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_5/Cast_124688_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Reshape_19/Cast_124710_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Transpose_6/Cast_124754_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_7/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_6/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_2/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_1/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_4/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_0/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_8/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_5/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "GlobalAveragePool_3/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Softmax_0/FlattenONNX_/input_shape/Gather/Cast_224732_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "Softmax_0/FlattenONNX_/first_dims/Cast_124684_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "5860_const" to "<class 'numpy.int64'>"
[ WARNING ]  Converting type of Const node "5865_const" to "<class 'numpy.int64'>"

[ WARNING ]  There are at least two output nodes with the same key used to sort the outputs. This means that IRs with different order of nodes may be generated between Model Optimizer runs. The dictionary with outputs is: {'save_infer_model/scale_0.tmp_1/sink_port_0': 'Identity_0_0', 'Constant_140/Output_0/Data_': '<UNKNOWN>', 'Constant_183/Output_0/Data_': '<UNKNOWN>', '749/Output_0/Data_': '<UNKNOWN>', '750/Output_0/Data_': '<UNKNOWN>', '751/Output_0/Data_': '<UNKNOWN>', '752/Output_0/Data_': '<UNKNOWN>', '753/Output_0/Data_': '<UNKNOWN>', '754/Output_0/Data_': '<UNKNOWN>', '755/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/input_shape/Indices/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/input_shape/Axis/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/first_dims/value/Output_0/Data_': '<UNKNOWN>', 'LSTM_0/ExtraOutput/1/sink_port_0': 'Transpose_3_0', 'LSTM_0/ExtraOutput/2/sink_port_0': 'Transpose_3_0', 'LSTM_4/ExtraOutput/1/sink_port_0': 'Reshape_18_0', 'LSTM_4/ExtraOutput/2/sink_port_0': 'Reshape_18_0', 'LSTM_4/Split/forward/ShapeOf/Indices5930': '<UNKNOWN>', 'LSTM_4/Split/forward/ShapeOf/Axis5931': '<UNKNOWN>', 'LSTM_0/Split/forward/ShapeOf/Indices5960': '<UNKNOWN>', 'LSTM_0/Split/forward/ShapeOf/Axis5961': '<UNKNOWN>', 'LSTM_4/Split/reverse/ShapeOf/Indices5990': '<UNKNOWN>', 'LSTM_4/Split/reverse/ShapeOf/Axis5991': '<UNKNOWN>', 'LSTM_0/Split/reverse/ShapeOf/Indices6020': '<UNKNOWN>', 'LSTM_0/Split/reverse/ShapeOf/Axis6021': '<UNKNOWN>', 'Slice_0/Concat7663': '<UNKNOWN>', 'Slice_0/Concat76537664': '<UNKNOWN>', 'Slice_0/Strides7665': '<UNKNOWN>', 'Slice_1/Concat7699': '<UNKNOWN>', 'Slice_1/Concat76897700': '<UNKNOWN>', 'Slice_1/Strides7701': '<UNKNOWN>', 'Slice_14/Concat7743': '<UNKNOWN>', 'Slice_14/Concat77297744': '<UNKNOWN>', 'Slice_14/Strides7745': '<UNKNOWN>', 'Slice_15/Concat7787': '<UNKNOWN>', 'Slice_15/Concat77737788': '<UNKNOWN>', 'Slice_15/Strides7789': '<UNKNOWN>', 'Slice_28/Concat7831': '<UNKNOWN>', 'Slice_28/Concat78177832': '<UNKNOWN>', 'Slice_28/Strides7833': '<UNKNOWN>', 'Slice_29/Concat7875': '<UNKNOWN>', 'Slice_29/Concat78617876': '<UNKNOWN>', 'Slice_29/Strides7877': '<UNKNOWN>', 'LSTM_4/Split/reverse/CellStateResize/Cast_124646': '<UNKNOWN>', 'LSTM_0/Split/reverse/HiddenStateResize/Cast_124666': '<UNKNOWN>', 'GlobalAveragePool_1/reduce/Cast_124682': '<UNKNOWN>', 'LSTM_0/Split/reverse/CellStateResize/Cast_124686': '<UNKNOWN>', 'GlobalAveragePool_0/reduce/Cast_124690': '<UNKNOWN>', 'LSTM_4/Split/reverse/HiddenStateResize/Cast_124692': '<UNKNOWN>', 'LSTM_0/Split/forward/HiddenStateResize/Cast_124694': '<UNKNOWN>', 'LSTM_0/Split/forward/CellStateResize/Cast_124704': '<UNKNOWN>', 'GlobalAveragePool_2/reduce/Cast_124708': '<UNKNOWN>', 'GlobalAveragePool_3/reduce/Cast_124712': '<UNKNOWN>', 'GlobalAveragePool_6/reduce/Cast_124714': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/Reshape/Cast_124716': '<UNKNOWN>', 'save_infer_model/scale_0.tmp_1/Cast_124722': '<UNKNOWN>', 'GlobalAveragePool_7/reduce/Cast_124728': '<UNKNOWN>', 'GlobalAveragePool_8/reduce/Cast_124740': '<UNKNOWN>', 'GlobalAveragePool_5/reduce/Cast_124746': '<UNKNOWN>', 'LSTM_4/Split/forward/HiddenStateResize/Cast_124748': '<UNKNOWN>', 'GlobalAveragePool_4/reduce/Cast_124750': '<UNKNOWN>', 'LSTM_4/Split/forward/CellStateResize/Cast_124758': '<UNKNOWN>', '2573525736': '<UNKNOWN>', '2573725738': '<UNKNOWN>', '2573925740': '<UNKNOWN>', '2574125742': '<UNKNOWN>', '2574325744': '<UNKNOWN>', '2574525746': '<UNKNOWN>', '2574725748': '<UNKNOWN>', '2574925750': '<UNKNOWN>', '2575125752': '<UNKNOWN>', '2575325754': '<UNKNOWN>', '2575525756': '<UNKNOWN>', '2575725758': '<UNKNOWN>', '2575925760': '<UNKNOWN>', '2576125762': '<UNKNOWN>', '2576325764': '<UNKNOWN>', '2576525766': '<UNKNOWN>', '2576725768': '<UNKNOWN>', '2576925770': '<UNKNOWN>', '2577125772': '<UNKNOWN>', '2577325774': '<UNKNOWN>', '2577525776': '<UNKNOWN>'}
```
本人使用的是最新的PaddleOCR，openvino版本为2021.3
请问您是否有解决的思路或方案？

**Comment by HanGuangXin** [comment]
目前我个人倾向于是LSTM导致的问题？

**Comment by Dandelion111** [comment]
> 开发者们你好！非常感谢你们在PaddleOCR中精彩的工作！
> 最近我在将“ch_ppocr_mobile_v2.0_rec”模型从onnx转为openvino时遇到了问题，无法导出得到正确的openvino模型。
> 我已经验证过从paddlepaddle推理模型到onnx的转换是完全正确的，二者具有几乎完全一致的输出结果：
> 
> inference with inference model
> 
> ```python
> python tools/infer/predict_rec.py --image_dir="onnx_input_demo_ppocr.jpg" --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/"
> # [2021/08/13 21:53:59] root INFO: Predicts of onnx_input_demo_ppocr.jpg:('鲁UR565', 0.71912557)
> ```
> 
> inference with onnx
> 
> ```python
> python onnx_inference/predict_rec.py --image_dir="onnx_input_demo_ppocr.jpg" --rec_model_dir="inference/ch_ppocr_mobile_v2.0_rec_infer/model.onnx" --use_angle_cls=False --rec_char_dict_path ppocr/utils/ppocr_keys_v1.txt --vis_font_path inference/ch_ppocr_mobile_v2.0_rec_infer/simfang.ttf
> # [2021/08/13 21:53:20] root INFO: Predicts of onnx_input_demo_ppocr.jpg:('鲁UR565', 0.7191264)
> # [2021/08/13 21:53:20] root INFO: Total predict time for 1 images, cost: 0.003
> ```
> 
> 当从onnx转换到openvino时，我得到了以下的warning（每种warning只截取了一部分）：
> 
> ```shell
> [ WARNING ]  Skipped <class 'extensions.front.AttributedGatherNormalizer.AttributedGatherNormalizer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.InterpolateNormalizer.InterpolateNormalizer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.Log1p.Log1p'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.Pack.Pack'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.PowerToEltwises.PowerToEltwises'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.tf.FakeQuantWithMinMaxVars.FakeQuantWithMinMaxVarsToQuantize'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.eltwise_n.EltwiseNReplacement'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.rank_decomposer.RankDecomposer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.image_scaler.ImageScaler'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.instance_normalization.InstanceNormalization'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.reciprocal.ReciprocalReplacer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.softsign_replacer.SoftSign'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.split_normalizer.SqueezeAxis'> registration because it was already registered or it was disabled. 
> 
> [ WARNING ]  Skipped <class 'mo.front.common.replacement.FrontReplacementSubgraph'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.user_data_repack.UserDataRepack'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'mo.front.tf.replacement.FrontReplacementFromConfigFileGeneral'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.ATenToEmbeddingBag.AtenToEmbeddingBag'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.AttributedClampNormalizer.AttributedClampNormalizer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.AttributedPadToPad.AttributedPadToPad'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.ChangePlaceholderTypes.ChangePlaceholderTypes'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.ExpandDimsToUnsqueeze.ExpandDimsToUnsqueeze'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.FillToBroadcast.FillToBroadcast'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.GeLUMerger_Erf.GeLUMergerErf'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.InterpolateV1ToInterpolate.InterpolateV1ToInterpolate'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.LayerNorm.LayerNorm'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.pass_separator.FrontStart'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.pass_separator.FrontFinish'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.OneHotDepthNormalizer.OneHotDepthNormalizer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.SqueezeNormalize.SqueezeNormalize'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.ThresholdedReluDecomposition.ThresholdedReluDecomposition'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.TopKNormalize.TopKNormalize'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.tf.pad_tf_to_pad.PadTFToPad'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.binary_quantize_normalization.BinaryFakeQuantizeNormalization'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.create_tensor_nodes.CreateTensorNodes'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.disable_weights_quantize_value_propagation.DisableQuantizeValuePropagation'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.div.Div'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.global_pooling_to_reduce.GlobalPoolingToReduce'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.input_cut.InputCut'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.interpolate_reshape.InterpolateWithConcat'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.output_cut.OutputCut'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.override_batch.OverrideBatch'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.scatter_normalizer.ScatterNormalizer'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.sub.Sub'> registration because it was already registered or it was disabled. 
> [ WARNING ]  Skipped <class 'extensions.front.transformations_config.TransformationsConfig'> registration because it was already registered or it was disabled. 
> 
> [ WARNING ]  Converting type of Const node "Squeeze_0/Dims/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_0/Cast_124756_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_1/Cast_124674_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_2/Cast_124696_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_3/Cast_124706_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_4/Cast_124752_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Reshape_18/Cast_124668_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_5/Cast_124688_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Reshape_19/Cast_124710_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Transpose_6/Cast_124754_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_7/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_6/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_2/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_1/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_4/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_0/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_8/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_5/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "GlobalAveragePool_3/input_rank/0d_rank_of/value/Output_0/Data__const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Softmax_0/FlattenONNX_/input_shape/Gather/Cast_224732_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "Softmax_0/FlattenONNX_/first_dims/Cast_124684_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "5860_const" to "<class 'numpy.int64'>"
> [ WARNING ]  Converting type of Const node "5865_const" to "<class 'numpy.int64'>"
> 
> [ WARNING ]  There are at least two output nodes with the same key used to sort the outputs. This means that IRs with different order of nodes may be generated between Model Optimizer runs. The dictionary with outputs is: {'save_infer_model/scale_0.tmp_1/sink_port_0': 'Identity_0_0', 'Constant_140/Output_0/Data_': '<UNKNOWN>', 'Constant_183/Output_0/Data_': '<UNKNOWN>', '749/Output_0/Data_': '<UNKNOWN>', '750/Output_0/Data_': '<UNKNOWN>', '751/Output_0/Data_': '<UNKNOWN>', '752/Output_0/Data_': '<UNKNOWN>', '753/Output_0/Data_': '<UNKNOWN>', '754/Output_0/Data_': '<UNKNOWN>', '755/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/input_shape/Indices/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/input_shape/Axis/Output_0/Data_': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/first_dims/value/Output_0/Data_': '<UNKNOWN>', 'LSTM_0/ExtraOutput/1/sink_port_0': 'Transpose_3_0', 'LSTM_0/ExtraOutput/2/sink_port_0': 'Transpose_3_0', 'LSTM_4/ExtraOutput/1/sink_port_0': 'Reshape_18_0', 'LSTM_4/ExtraOutput/2/sink_port_0': 'Reshape_18_0', 'LSTM_4/Split/forward/ShapeOf/Indices5930': '<UNKNOWN>', 'LSTM_4/Split/forward/ShapeOf/Axis5931': '<UNKNOWN>', 'LSTM_0/Split/forward/ShapeOf/Indices5960': '<UNKNOWN>', 'LSTM_0/Split/forward/ShapeOf/Axis5961': '<UNKNOWN>', 'LSTM_4/Split/reverse/ShapeOf/Indices5990': '<UNKNOWN>', 'LSTM_4/Split/reverse/ShapeOf/Axis5991': '<UNKNOWN>', 'LSTM_0/Split/reverse/ShapeOf/Indices6020': '<UNKNOWN>', 'LSTM_0/Split/reverse/ShapeOf/Axis6021': '<UNKNOWN>', 'Slice_0/Concat7663': '<UNKNOWN>', 'Slice_0/Concat76537664': '<UNKNOWN>', 'Slice_0/Strides7665': '<UNKNOWN>', 'Slice_1/Concat7699': '<UNKNOWN>', 'Slice_1/Concat76897700': '<UNKNOWN>', 'Slice_1/Strides7701': '<UNKNOWN>', 'Slice_14/Concat7743': '<UNKNOWN>', 'Slice_14/Concat77297744': '<UNKNOWN>', 'Slice_14/Strides7745': '<UNKNOWN>', 'Slice_15/Concat7787': '<UNKNOWN>', 'Slice_15/Concat77737788': '<UNKNOWN>', 'Slice_15/Strides7789': '<UNKNOWN>', 'Slice_28/Concat7831': '<UNKNOWN>', 'Slice_28/Concat78177832': '<UNKNOWN>', 'Slice_28/Strides7833': '<UNKNOWN>', 'Slice_29/Concat7875': '<UNKNOWN>', 'Slice_29/Concat78617876': '<UNKNOWN>', 'Slice_29/Strides7877': '<UNKNOWN>', 'LSTM_4/Split/reverse/CellStateResize/Cast_124646': '<UNKNOWN>', 'LSTM_0/Split/reverse/HiddenStateResize/Cast_124666': '<UNKNOWN>', 'GlobalAveragePool_1/reduce/Cast_124682': '<UNKNOWN>', 'LSTM_0/Split/reverse/CellStateResize/Cast_124686': '<UNKNOWN>', 'GlobalAveragePool_0/reduce/Cast_124690': '<UNKNOWN>', 'LSTM_4/Split/reverse/HiddenStateResize/Cast_124692': '<UNKNOWN>', 'LSTM_0/Split/forward/HiddenStateResize/Cast_124694': '<UNKNOWN>', 'LSTM_0/Split/forward/CellStateResize/Cast_124704': '<UNKNOWN>', 'GlobalAveragePool_2/reduce/Cast_124708': '<UNKNOWN>', 'GlobalAveragePool_3/reduce/Cast_124712': '<UNKNOWN>', 'GlobalAveragePool_6/reduce/Cast_124714': '<UNKNOWN>', 'Softmax_0/FlattenONNX_/Reshape/Cast_124716': '<UNKNOWN>', 'save_infer_model/scale_0.tmp_1/Cast_124722': '<UNKNOWN>', 'GlobalAveragePool_7/reduce/Cast_124728': '<UNKNOWN>', 'GlobalAveragePool_8/reduce/Cast_124740': '<UNKNOWN>', 'GlobalAveragePool_5/reduce/Cast_124746': '<UNKNOWN>', 'LSTM_4/Split/forward/HiddenStateResize/Cast_124748': '<UNKNOWN>', 'GlobalAveragePool_4/reduce/Cast_124750': '<UNKNOWN>', 'LSTM_4/Split/forward/CellStateResize/Cast_124758': '<UNKNOWN>', '2573525736': '<UNKNOWN>', '2573725738': '<UNKNOWN>', '2573925740': '<UNKNOWN>', '2574125742': '<UNKNOWN>', '2574325744': '<UNKNOWN>', '2574525746': '<UNKNOWN>', '2574725748': '<UNKNOWN>', '2574925750': '<UNKNOWN>', '2575125752': '<UNKNOWN>', '2575325754': '<UNKNOWN>', '2575525756': '<UNKNOWN>', '2575725758': '<UNKNOWN>', '2575925760': '<UNKNOWN>', '2576125762': '<UNKNOWN>', '2576325764': '<UNKNOWN>', '2576525766': '<UNKNOWN>', '2576725768': '<UNKNOWN>', '2576925770': '<UNKNOWN>', '2577125772': '<UNKNOWN>', '2577325774': '<UNKNOWN>', '2577525776': '<UNKNOWN>'}
> ```
> 
> 本人使用的是最新的PaddleOCR，openvino版本为2021.3
> 请问您是否有解决的思路或方案？

请问问题解决了吗，转openvino成功了吗
