### ISSUE TITLE
有大佬封装一个图像文字识别安卓端的sdk api吗

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#368]

**Comment by authorfu** [comment]
有针对开发者的快速方式：
https://ai.baidu.com/easyedge/app/openSource?from= 
可以扫描测试+快速方式集成，永久免费。 但是目前调用库闭源。

**Comment by riskycheng** [comment]
https://bj.bcebos.com/aipe-easyedge/open-model/1/EasyEdge-Android-Demo.zip?authorization=bce-auth-v1%2F50c8bb753dcb4e1d8646bb1ffefd3503%2F2020-08-02T17%3A05%3A49Z%2F3600%2F%2F463c9f5affc72188cd110da5ab27e8f7bb1e2a839bde0d1c515db5f0899f6317
