### ISSUE TITLE
InvalidArgumentError: The Bias's size(64) should be equal to the first dim(0) of the Input.

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3682]
你好，我的环境是Jetpack4.4，paddlepaddle-gpu 2.0.2   opencv-contrib-python 4.5.3.56 
官网的jetson 4.4 -Paddle 2.1怎么不见了,是在重新编译吗 
OCR需要opencv-contrib-python 4.4.0.46 但在Jetson上不好装,编译失败 而且我需要使用opencv-contrib-python 4.5.3.56 的wechat_qrcode_WeChatQRCode()

even@even-desktop:~/Project/PaddleOCR$ python3 tools/infer/predict_system.py --image_dir="./test_imgs/" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/"  --use_angle_cls=False --use_space_char=True --use_gpu=True --use_tensorrt=True
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
W0815 21:09:50.530268 14834 analysis_predictor.cc:677] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0815 21:09:50.530690 14834 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
I0815 21:09:50.575745 14834 analysis_predictor.cc:522] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0815 21:09:50.857421 14834 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0815 21:09:50.923368 14834 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0815 21:09:50.956389 14834 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 59 nodes
W0815 21:09:50.991263 14834 tensorrt_subgraph_pass.cc:304] The Paddle lib links the 7130 version TensorRT, make sure the runtime TensorRT you are using is no less than this version, otherwise, there might be Segfault!
I0815 21:09:51.015503 14834 tensorrt_subgraph_pass.cc:347] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0815 21:09:53.916244 14834 engine.cc:204] Run Paddle-TRT Dynamic Shape mode.
W0815 21:09:53.917384 14834 helper.h:74] DLA requests all profiles have same min, max, and opt value. All dla layers are falling back to GPU
I0815 21:10:05.791201 14834 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 13 nodes
I0815 21:10:05.797592 14834 tensorrt_subgraph_pass.cc:347] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E0815 21:10:05.802601 14834 helper.h:78] conv2d (Output: conv2d_63.tmp_0399): kernel weights has count 147456 but 55296 was expected
E0815 21:10:05.802772 14834 helper.h:78] conv2d (Output: conv2d_63.tmp_0399): count of 147456 weights in kernel, but kernel dimensions (3,3) with 96 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 96 * 3*3 * 64 / 1 = 55296
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 193, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 117, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/even/Project/PaddleOCR/tools/infer/predict_det.py", line 99, in __init__
    args, 'det', logger)
  File "/home/even/Project/PaddleOCR/tools/infer/utility.py", line 250, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::OpConverter::ConvertOp(paddle::framework::proto::OpDesc const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*, bool)
13  paddle::inference::tensorrt::ElementwiseWeightOpConverter::operator()(paddle::framework::proto::OpDesc const&, paddle::framework::Scope const&, bool)
14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
15  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Bias's size(64) should be equal to the first dim(0) of the Input.
  [Hint: Expected Y_t->dims()[0] == dims_x.d[1], but received Y_t->dims()[0]:64 != dims_x.d[1]:0.] (at /home/paddle/data/wangye19/Paddle/paddle/fluid/inference/tensorrt/convert/elementwise_op.cc:115)

**Comment by tink2123** [comment]
Jetpack 编译问题麻烦去Paddle repo提一个issue：https://github.com/PaddlePaddle/Paddle/issues

**Comment by wangye707** [comment]
现在是opencv装不上还是paddle装不上？

**Comment by PhilCuriosity** [comment]
> 现在是opencv装不上还是paddle装不上？
现在是opencv-contrib-python==4.4.0.46这个装不上，我现在用的是opencv-contrib-python>4.5.2的，paddle装的是2.0.2的


> Jetpack 编译问题麻烦去Paddle repo提一个issue：https://github.com/PaddlePaddle/Paddle/issues
好的，谢谢
