### ISSUE TITLE
配置文件的有啥区别？

### ISSUE THREAD

**Issue by weekstudy** [PaddlePaddle/PaddleOCR#3684]
在configs/det/det_mv3_db.yml中的output_channels=256与configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml中的output_channels=96，请问为什么这两个不一样？有什么区别？对训练有什么影响吗？
![image](https://user-images.githubusercontent.com/39413303/129501476-87c0476d-dc58-48dc-9318-19555ca05d46.png)

![image](https://user-images.githubusercontent.com/39413303/129501388-894b030b-6c19-4cd1-a9fe-01e42f056a14.png)

**Comment by WenmuZhou** [comment]
会更快，精度会掉一点点

**Comment by weekstudy** [comment]
> 会更快，精度会掉一点点

哦哦，懂了，感谢
