### ISSUE TITLE
How to export the model?

### ISSUE THREAD

**Issue by cv-small-snails** [PaddlePaddle/PaddleOCR#3688]
I run this command
` python tools/export_model.py -c ./output/table_mv3/config.yml`
But it raise this error
![image](https://user-images.githubusercontent.com/18139836/129513515-bdb89156-104e-475d-b95c-65ca26d8cca8.png)
How to fix this error and export the model for inference?

**Comment by yaoguangshun** [comment]
cuda version=10.2 cudnn version=7.6.5 paddle version=2.1.1

**Comment by WenmuZhou** [comment]
you can try latest code
