### ISSUE TITLE
支持获取每条文字的位置么？

### ISSUE THREAD

**Issue by Wanyor** [PaddlePaddle/PaddleOCR#369]
类似与腾讯优图，有个功能很实用，返回的结果有一个box_size，显示的是每条文字内容以及基于图片的像素的框位置。

**Comment by tink2123** [comment]
您好～ 我们支持返回每条文字位置的。
online体验里可以查看response：https://www.paddlepaddle.org.cn/hub/scene/ocr
<img width="384" alt="图片" src="https://user-images.githubusercontent.com/31891223/87764291-b817f600-c848-11ea-824d-1e66fc13c49f.png">

本地测试时也可以返回框的位置，可以在这里获取到：https://github.com/PaddlePaddle/PaddleOCR/blob/e47254fc6e17ac04c146734f3890060df3979efa/tools/infer/predict_system.py#L130

**Comment by Wanyor** [comment]
好的，谢谢您！

**Comment by tink2123** [comment]
不客气～

**Comment by feilu886** [comment]
请问可以返回每个文字的坐标吗？
