### ISSUE TITLE
crnn 模型，去掉rnn后，模型size增大是为什么？

### ISSUE THREAD

**Issue by Zhang-O** [PaddlePaddle/PaddleOCR#3690]
训练crnn模型
配置1：
Neck:
    name: SequenceEncoder 
    encoder_type: rnn
    hidden_size: 48
![image](https://user-images.githubusercontent.com/18193972/129521261-1c709583-5c7c-4d86-882b-bab61ca31001.png)

配置2：
Neck:
    name: SequenceEncoder 
    encoder_type: reshape
![image](https://user-images.githubusercontent.com/18193972/129521321-135e46a1-d278-4acb-8b9b-4960aec8f5d7.png)

去掉rnn后参数应该少了一部分，为什么 best_accuracy.pdparams 体积变大了70%？

**Comment by WenmuZhou** [comment]
你需要看导出inference模型之后的大小，那个比较准确

**Comment by Zhang-O** [comment]
inference后：
2*lstm：4.3M
![image](https://user-images.githubusercontent.com/18193972/129734608-15af2765-ea7b-4047-bfe9-0d6ee22f2a1f.png)

0*lstm: 8.5M
![image](https://user-images.githubusercontent.com/18193972/129734749-7c6dfc5b-48be-4d86-83fe-0df774487b01.png)

**Comment by Sanster** [comment]
cnn 最后一层拉平后的维度比 rnn 最后的 hidden size大得多，所以后面接的 fc 参数也更多，可以在fc前面再加一层conv或fc降维

**Comment by TangDL** [comment]
hello, I'm doing the same work, and I wander how you deal this problems? can you reply me tdlming@163.com,thanks
