### ISSUE TITLE
der支持长框检测如何修改参数？

### ISSUE THREAD

**Issue by sjtu-cz** [PaddlePaddle/PaddleOCR#3691]
我基于east训练了检测模型，但目前检测的效果对于较长的框效果不佳，请问需要怎么对应调整config？
![img4572](https://user-images.githubusercontent.com/20858982/129522523-6c3e247a-a6af-4bf7-96f4-8cb38e86ac7a.jpg)

**Comment by sjtu-cz** [comment]
请问east能做到支持这种长框的检测么？

**Comment by WenmuZhou** [comment]
长文本用db吧 east不太支持
