### ISSUE TITLE
Issue with onnx model 

### ISSUE THREAD

**Issue by ujjawalcse** [PaddlePaddle/PaddleOCR#3694]
Hi,
I used pgnet inference model and got nice results.
Then I tried to convert it to onnx model using paddle2onnx and successfully converted.
But I couldn't produce the results using that onnx model.
I'm facing the below issue:-

```
(1, 3, 300, 300) 
NodeArg(name='x', type='tensor(float)', shape=[None, 3, None, None])

---------------------------------------------------------------------------

RuntimeException                          Traceback (most recent call last)

<ipython-input-21-90e728a110ab> in <module>()
     17 print(ort_sess.get_inputs()[0])
     18 ort_inputs = {ort_sess.get_inputs()[0].name: x}
---> 19 ort_outs = ort_sess.run(None, ort_inputs)
     20 print(ort_outs)
     21 print("Exported model has been predict by ONNXRuntime!")

/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in run(self, output_names, input_feed, run_options)
    186             output_names = [output.name for output in self._outputs_meta]
    187         try:
--> 188             return self._sess.run(output_names, input_feed, run_options)
    189         except C.EPFail as err:
    190             if self._enable_fallback:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_30' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:497 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 19 by 20
```

where (1, 3, 300, 300) is my input to the onnx model and [None, 3, None, None] is expected by the model. Means there is
no issue with the input.
Could you please share any view on this issue?
Thanks.

**Comment by jiangjiajun** [comment]
@ujjawalcse It seems like there's some problem with Paddle2ONNX， could you upload your PGNet PaddlePaddle model(saved as inference model format) and converted ONNX model here?

**Comment by ujjawalcse** [comment]
@jiangjiajun ,Please download it from the below link:-
pgnet inference model : https://drive.google.com/drive/folders/1FyAOycrBCf3F2LDLVvsGaeu6CUWbgcad?usp=sharing
pgnet onnx model : https://drive.google.com/file/d/1qB7VMIQr6U08e2amAgxkcFHjVoS2wc6J/view?usp=sharing

**Comment by yeliang2258** [comment]
Hello, you can try input size as 256*256, or 512*512.

**Comment by ZhengtianXu** [comment]
> @ujjawalcse It seems like there's some problems with Paddle2ONNX， could you upload your PGNet PaddlePaddle model(saved as inference model format) and converted ONNX model here?

Have you solved this problem? I trained a angle classification models and converted it to onnx model. When I used this onnx model, it raises this error.

**Comment by yeliang2258** [comment]
> > @ujjawalcse It seems like there's some problems with Paddle2ONNX， could you upload your PGNet PaddlePaddle model(saved as inference model format) and converted ONNX model here?
> 
> Have you solved this problem? I trained a angle classification models and converted it to onnx model. When I used this onnx model, it raises this error. @jiangjiajun

You can try input size as 256 * 256, or 512 * 512.
