### ISSUE TITLE
请问如果自己单独训练识别银行卡和存折，分别需要多少数据？

### ISSUE THREAD

**Issue by zsshub** [PaddlePaddle/PaddleOCR#3695]
@MissPenguin @tink2123 @LDOUBLEV

**Comment by WenmuZhou** [comment]
看你做什么任务，检测1000，识别几十万吧

**Comment by zsshub** [comment]
> 看你做什么任务，检测1000，识别几十万吧

谢谢，以下是具体的问题需要请教一下：

1. 检测识别级联任务，如果是单独训练银行卡呢，请问各需要多少张？
2. 现在主要问题是有的银行卡号码是凹凸纹理的，通用模型识别效果很差；另外，银行卡名称是中文的，字典里也要把要用到的中文字符都包含吗，每个字符是不是也要做到样本均衡？
3. 如果是在通用模型识别下，通过对银行卡做一些图像处理以辅助提升识别效果，比较好的方法有哪些？
