### ISSUE TITLE
检测模型训练好之后，直接eval和转inference模型之后eval差距很大？

### ISSUE THREAD

**Issue by sjtu-cz** [PaddlePaddle/PaddleOCR#3698]
![image](https://user-images.githubusercontent.com/20858982/129553406-9f379f2b-414a-40ad-b296-ba13c6f303ba.png)
![image](https://user-images.githubusercontent.com/20858982/129553416-e7dea504-a9ac-49cb-a6df-f03b8ee60ba9.png)
上面的图是用infer_det.py，下面是用predict_det.py。
请问为什么会这样？

**Comment by WenmuZhou** [comment]
能不能看看你infer跑的config还有predict跑的参数

**Comment by sjtu-cz** [comment]
下图是运行的指令，附件是使用的config。 谢谢，辛苦
s







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 检测模型训练好之后，直接eval和转inference模型之后eval差距很大？ (#3698)





 
能不能看看你infer跑的config还有predict跑的参数
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sjtu-cz** [comment]
我应该找到原因了，应该是test的时候resize的问题，之前这两者之间的配置文件没对齐。辛苦了
