### ISSUE TITLE
表格识别时，无法使用gpu进行推理

### ISSUE THREAD

**Issue by xl2023** [PaddlePaddle/PaddleOCR#3699]
您好，使用ppstructure文件夹下的代码进行表格识别时，args.use_gpu设置的为True，但识别过程中使用watch -n 1 nvidia-smi监控gpu的使用情况，发现gpu一直未使用，p100显卡下400k的表格图片识别时间在5秒左右。进行代码追踪，到这predictor = inference.create_predictor(config)也没发现问题。

**Comment by WenmuZhou** [comment]
看看你的paddle能否调起gpu

**Comment by TTMRonald** [comment]
请问你解决了么？我也遇到同样的问题，使用表格结构识别模型CPU和GPU预测耗时一样，都是接近3秒，其他模型可以正常使用GPU加速
