### ISSUE TITLE
!pip install -r /home/aistudio/work/PaddleOCR/requirements.txt 在AI Studio 环境下 导入opencv-contrib-python卡死

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleOCR#3702]
参考了，你们更新之后。
!pip install -r /home/aistudio/work/PaddleOCR/requirements.txt

< "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (0.6.0)
Requirement already satisfied: more-itertools in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (7.2.0)
Building wheels for collected packages: opencv-contrib-python
Building wheel for opencv-contrib-python (PEP 517) ... |

一直卡死了，不加载了

**Comment by WenmuZhou** [comment]
可以去终端执行安装命令

**Comment by Wei-JL** [comment]
quirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (1.25.6)
Requirement already satisfied: Werkzeug>=0.15 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from flask>=1.1.1->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: itsdangerous>=0.24 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from flask>=1.1.1->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: click>=5.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from flask>=1.1.1->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from Jinja2>=2.5->Flask-Babel>=1.0.0->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->flake8>=3.7.9->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (0.6.0)
Requirement already satisfied: more-itertools in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->flake8>=3.7.9->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (7.2.0)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (PEP 517) ... |^-


终端也是卡死这里

**Comment by Wei-JL** [comment]
大约什么时候才能解决啊？

**Comment by ioracion** [comment]
pip install --upgrade pip

**Comment by Wei-JL** [comment]
> pip install --upgrade pip

我换成以前的版本了

**Comment by toulzx** [comment]
我也遇到了...
使用 @ioracion 的方法解决了，感谢❤🚀👍

**Comment by XinyiXiang** [comment]
针对非 Intel 芯片的 Mac 还需要支持 PaddlePaddle 镜像的 Python ver.(3.6/3.7), 细节见:(https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/install_cn.html#mac-m1paddle)

安装完成后prompt输入命令
```python3 -m pip install --upgrade pip```
