### ISSUE TITLE
自定义训练的table structure 使用export导出模型进行inference时报错

### ISSUE THREAD

**Issue by yaocctao** [PaddlePaddle/PaddleOCR#3703]
训练数据为PubTabNet中的examples中的20张数据
其中一条数据如下：
{"filename": "PMC4840965_004_00.png", "split": "train", "imgid": 0, "html": {"cells": [{"tokens": ["<b>", "V", "a", "r", "i", "a", "b", "l", "e", "</b>"], "bbox": [1, 4, 27, 13]}, {"tokens": ["<b>", "H", "a", "z", "a", "r", "d", " ", "r", "a", "t", "i", "o", "</b>"], "bbox": [219, 4, 260, 13]}, {"tokens": ["<b>", "9", "5", " ", "%", " ", "C", "I", "</b>"], "bbox": [336, 4, 363, 13]}, {"tokens": ["<b>", "<i>", "p", "</i>", " ", "v", "a", "l", "u", "e", "*", "</b>"], "bbox": [456, 4, 484, 13]}, {"tokens": ["A", "g", "e", " ", "(", "m", "e", "d", "i", "a", "n", ")"], "bbox": [1, 17, 46, 27]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "7", "1", "6"], "bbox": [456, 17, 475, 27]}, {"tokens": [" ", "≤", "6", "9"], "bbox": [8, 31, 23, 41]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 31, 238, 41]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", ">", "6", "9"], "bbox": [8, 45, 23, 55]}, {"tokens": ["0", ".", "8", "3", "9"], "bbox": [219, 45, 238, 55]}, {"tokens": ["0", ".", "3", "1", "0", "–", "2", ".", "2", "6", "8"], "bbox": [336, 45, 376, 55]}, {"tokens": []}, {"tokens": ["G", "e", "n", "d", "e", "r"], "bbox": [1, 59, 26, 69]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "1", "4", "2"], "bbox": [456, 59, 475, 69]}, {"tokens": [" ", "M", "a", "l", "e"], "bbox": [8, 73, 26, 83]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 73, 238, 83]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "F", "e", "m", "a", "l", "e"], "bbox": [8, 87, 34, 97]}, {"tokens": ["0", ".", "4", "2", "6"], "bbox": [219, 87, 238, 97]}, {"tokens": ["0", ".", "1", "5", "2", "–", "1", ".", "1", "9", "0"], "bbox": [336, 87, 376, 97]}, {"tokens": []}, {"tokens": ["T", "y", "p", "e", " ", "o", "f", " ", "s", "u", "r", "g", "e", "r", "y"], "bbox": [1, 101, 52, 111]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "0", "1", "0"], "bbox": [456, 101, 475, 111]}, {"tokens": [" ", "L", "o", "w", " ", "a", "n", "t", "e", "r", "i", "o", "r", " ", "r", "e", "s", "e", "c", "t", "i", "o", "n"], "bbox": [8, 115, 82, 125]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 115, 238, 125]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "A", "b", "d", "o", "m", "i", "n", "o", "p", "e", "r", "i", "n", "e", "a", "l", " ", "r", "e", "s", "e", "c", "t", "i", "o", "n"], "bbox": [8, 129, 101, 139]}, {"tokens": ["3", ".", "1", "4", "0"], "bbox": [219, 129, 238, 139]}, {"tokens": ["0", ".", "9", "1", "9", "–", "1", "0", ".", "7", "2", "5"], "bbox": [336, 129, 379, 139]}, {"tokens": []}, {"tokens": ["T", "u", "m", "o", "r", " ", "l", "o", "c", "a", "t", "i", "o", "n"], "bbox": [1, 143, 51, 153]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "7", "1", "0"], "bbox": [456, 143, 475, 153]}, {"tokens": [" ", "U", "p", "p", "e", "r", " ", "r", "e", "c", "t", "u", "m"], "bbox": [8, 157, 55, 167]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 157, 238, 167]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "M", "i", "d", "d", "l", "e", " ", "r", "e", "c", "t", "u", "m"], "bbox": [8, 171, 58, 181]}, {"tokens": ["1", ".", "2", "6", "7"], "bbox": [219, 171, 238, 181]}, {"tokens": ["0", ".", "3", "8", "1", "–", "4", ".", "2", "1", "3"], "bbox": [336, 171, 376, 181]}, {"tokens": []}, {"tokens": [" ", "L", "o", "w", " ", "r", "e", "c", "t", "u", "m"], "bbox": [8, 185, 49, 195]}, {"tokens": ["1", ".", "7", "1", "6"], "bbox": [219, 185, 238, 195]}, {"tokens": ["0", ".", "4", "1", "9", "–", "7", ".", "0", "2", "6"], "bbox": [336, 185, 376, 195]}, {"tokens": []}, {"tokens": ["G", "r", "a", "d", "e", " ", "o", "f", " ", "d", "i", "f", "f", "e", "r", "e", "n", "t", "i", "a", "t", "i", "o", "n"], "bbox": [0, 199, 77, 209]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "9", "3", "6"], "bbox": [456, 199, 475, 209]}, {"tokens": [" ", "G", "1"], "bbox": [8, 213, 19, 223]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 213, 238, 223]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "G", "2"], "bbox": [8, 227, 19, 237]}, {"tokens": ["1", ".", "9", "3", "3"], "bbox": [219, 227, 238, 237]}, {"tokens": ["0", ".", "4", "1", "6", "–", "3", ".", "4", "2", "3"], "bbox": [336, 227, 376, 237]}, {"tokens": []}, {"tokens": [" ", "G", "3"], "bbox": [8, 241, 19, 251]}, {"tokens": ["1", ".", "1", "1", "9"], "bbox": [219, 241, 238, 251]}, {"tokens": ["0", ".", "1", "3", "7", "–", "9", ".", "1", "3", "7"], "bbox": [336, 241, 376, 251]}, {"tokens": []}, {"tokens": ["H", "i", "s", "t", "o", "l", "o", "g", "i", "c", " ", "t", "y", "p", "e"], "bbox": [0, 255, 51, 265]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "2", "9", "9"], "bbox": [456, 255, 475, 265]}, {"tokens": [" ", "A", "d", "e", "n", "o", "c", "a", "r", "c", "i", "n", "o", "m", "a"], "bbox": [8, 269, 65, 279]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 269, 238, 279]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "A", "d", "e", "n", "o", "c", "a", "r", "c", "i", "n", "o", "m", "a", " ", "w", "i", "t", "h", " ", "m", "u", "c", "i", "n", "o", "u", "s", " ", "f", "e", "a", "t", "u", "r", "e", "s"], "bbox": [8, 283, 142, 293]}, {"tokens": ["0", ".", "3", "8", "1"], "bbox": [219, 283, 238, 293]}, {"tokens": ["0", ".", "0", "9", "6", "–", "1", ".", "5", "1", "4"], "bbox": [336, 283, 376, 293]}, {"tokens": []}, {"tokens": ["D", "e", "p", "t", "h", " ", "o", "f", " ", "t", "u", "m", "o", "r", " ", "i", "n", "v", "a", "s", "i", "o", "n"], "bbox": [0, 297, 82, 307]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "9", "2", "5"], "bbox": [456, 297, 475, 307]}, {"tokens": [" ", "T", "3"], "bbox": [8, 311, 18, 321]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 311, 238, 321]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", "T", "4", "a"], "bbox": [8, 325, 22, 335]}, {"tokens": ["0", ".", "9", "1", "9"], "bbox": [219, 325, 238, 335]}, {"tokens": ["0", ".", "3", "1", "6", "–", "2", ".", "6", "7", "3"], "bbox": [336, 325, 376, 335]}, {"tokens": []}, {"tokens": [" ", "T", "4", "b"], "bbox": [8, 339, 22, 349]}, {"tokens": ["0", ".", "7", "4", "5"], "bbox": [219, 339, 238, 349]}, {"tokens": ["0", ".", "1", "7", "2", "–", "3", ".", "2", "2", "3"], "bbox": [336, 339, 376, 349]}, {"tokens": []}, {"tokens": ["T", "u", "m", "o", "r", " ", "s", "i", "z", "e"], "bbox": [0, 353, 37, 363]}, {"tokens": []}, {"tokens": []}, {"tokens": ["0", ".", "3", "2", "9"], "bbox": [456, 353, 475, 363]}, {"tokens": [" ", "≤", "4", " ", "c", "m"], "bbox": [8, 367, 32, 377]}, {"tokens": ["1", ".", "0", "0", "0"], "bbox": [219, 367, 238, 377]}, {"tokens": []}, {"tokens": []}, {"tokens": [" ", ">", "4", " ", "c", "m"], "bbox": [8, 381, 31, 391]}, {"tokens": ["0", ".", "5", "9", "4"], "bbox": [219, 381, 238, 391]}, {"tokens": ["0", ".", "2", "1", "4", "–", "1", ".", "6", "5", "1"], "bbox": [336, 381, 376, 391]}, {"tokens": []}], "structure": {"tokens": ["<thead>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</thead>", "<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}}}
训练50个epoch保存
通过tools/export_model.py保存模型

报错信息如下
D:\anaconda\envs\PaddleOCR\python.exe D:/桌面/PaddleOCR/PaddleOCR-release-2.2/test.py
E0816 22:05:08.322073 19052 analysis_config.cc:81] Please compile with gpu to EnableGpu()
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='./models/paddleocr/2.2.0.1/ocr/det/ch/ch_ppocr_server_v2.0_det_infer', det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', layout_path_model='./models/paddledet/inference_model/ppyolov2_r50vd_dcn_365e_publaynet/ppyolov2_r50vd_dcn_365e_publaynet_infer', max_batch_size=10, max_text_length=25, min_subgraph_size=10, output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='D:\\桌面\\PaddleOCR\\PaddleOCR-release-2.2\\ppocr\\utils\\ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='./models/paddleocr/2.2.0.1/ocr/rec/ch/ch_ppocr_server_v2.0_rec_infer', save_log_path='./log_output/', show_log=True, table_char_dict_path='D:\\桌面\\PaddleOCR\\PaddleOCR-release-2.2\\ppocr\\utils\\dict\\table_structure_dict.txt', table_char_type='en', table_max_len=488, table_model_dir='inference_model', total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=True)
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0816 22:05:08.405956 19052 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_2.tmp_3  size: 26214400
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : conv2d_59.tmp_0  size: 26214400
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : elementwise_add_8.tmp_0  size: 26214400
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : tmp_1  size: 6553600
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_22.tmp_2  size: 819200
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_5.tmp_0  size: 6553600
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : conv2d_50.tmp_0  size: 1638400
I0816 22:05:08.425892 19052 memory_optimize_pass.cc:199] Cluster name : x  size: 4915200
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0816 22:05:08.452636 19052 analysis_predictor.cc:636] ======= optimize end =======
I0816 22:05:08.452636 19052 naive_executor.cc:98] ---  skip [feed], feed -> x
I0816 22:05:08.454632 19052 naive_executor.cc:98] ---  skip [batch_norm_2.tmp_3], fetch -> fetch
E0816 22:05:08.459581 19052 analysis_config.cc:81] Please compile with gpu to EnableGpu()
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
I0816 22:05:08.564301 19052 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0816 22:05:08.566295 19052 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0816 22:05:08.608183 19052 graph_pattern_detector.cc:91] ---  detected 39 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_3  size: 1
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_2.tmp_2  size: 819200
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : lstm_0._generated_var_0  size: 1
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : conv2d_41.tmp_0  size: 819200
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_1  size: 4096
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : x  size: 38400
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_1.tmp_3  size: 409600
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_2  size: 4096
I0816 22:05:08.765763 19052 memory_optimize_pass.cc:199] Cluster name : relu_2.tmp_0  size: 204800
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0816 22:05:08.806191 19052 analysis_predictor.cc:636] ======= optimize end =======
I0816 22:05:08.806191 19052 naive_executor.cc:98] ---  skip [feed], feed -> x
I0816 22:05:08.809182 19052 naive_executor.cc:98] ---  skip [conv2d_41.tmp_0], fetch -> fetch
E0816 22:05:08.810180 19052 analysis_config.cc:81] Please compile with gpu to EnableGpu()
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
I0816 22:05:08.890219 19052 graph_pattern_detector.cc:91] ---  detected 3 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0816 22:05:08.914156 19052 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : relu_2.tmp_0  size: 4286592
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_4.tmp_3  size: 4286592
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : x  size: 2857728
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_8.tmp_3  size: 1309792
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_6.tmp_3  size: 357216
I0816 22:05:08.930114 19052 memory_optimize_pass.cc:199] Cluster name : batch_norm_12.tmp_3  size: 153760
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0816 22:05:08.977986 19052 analysis_predictor.cc:636] ======= optimize end =======
I0816 22:05:08.977986 19052 naive_executor.cc:98] ---  skip [feed], feed -> x
I0816 22:05:08.980978 19052 naive_executor.cc:98] ---  skip [batch_norm_4.tmp_3], fetch -> fetch
I0816 22:05:08.980978 19052 naive_executor.cc:98] ---  skip [relu_2.tmp_0], fetch -> fetch
E0816 22:05:08.980978 19052 analysis_config.cc:81] Please compile with gpu to EnableGpu()
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
[2021/08/16 22:05:13] root DEBUG: dt_boxes num : 34, elapse : 0.3827669620513916
[2021/08/16 22:05:15] root DEBUG: rec_res num  : 34, elapse : 1.9893176555633545
Traceback (most recent call last):
  File "D:/桌面/PaddleOCR/PaddleOCR-release-2.2/test.py", line 17, in <module>
    result,layout_res = table_engine(img)
  File "D:\桌面\PaddleOCR\PaddleOCR-release-2.2\paddleocr.py", line 336, in __call__
    res = super().__call__(img)
  File "D:\桌面\PaddleOCR\PaddleOCR-release-2.2\ppstructure\predict_system.py", line 70, in __call__
    res = self.table_system(roi_img)
  File "D:\桌面\PaddleOCR\PaddleOCR-release-2.2\ppstructure\table\predict_table.py", line 92, in __call__
    pred_html, pred = self.rebuild_table(structure_res, dt_boxes, rec_res)
  File "D:\桌面\PaddleOCR\PaddleOCR-release-2.2\ppstructure\table\predict_table.py", line 97, in rebuild_table
    matched_index = self.match_result(dt_boxes, pred_bboxes)
  File "D:\桌面\PaddleOCR\PaddleOCR-release-2.2\ppstructure\table\predict_table.py", line 112, in match_result
    if distances.index(sorted_distances[0]) not in matched.keys():
IndexError: list index out of range

Process finished with exit code 1

**Comment by WenmuZhou** [comment]
代码是最新的不，详细需要看看这里是否一致 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/ppocr/data/imaug/label_ops.py#L388-L396

**Comment by yaocctao** [comment]
> 代码是最新的不，详细需要看看这里是否一致 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/ppocr/data/imaug/label_ops.py#L388-L396

 代码是最新的PaddleOCR-release-2.2版本，link对应的代码也都一致

**Comment by WenmuZhou** [comment]
看起来是模型明天检测到cell框，可以单独输出一些结构模型的结果看看
