### ISSUE TITLE
tensorRT动态输入问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3705]
请问怎么设置或者查看tensorRT动态输入通道数应该输入多少啊？用官方的设置的动态输入，还是会报某些维度错误，注释掉
config.disable_glob_info()，可以看到具体的报错的通道维度信息，但是应该怎样知道正确的通道数了？

**Comment by LDOUBLEV** [comment]
> 请问怎么设置或者查看tensorRT动态输入通道数应该输入多少啊？用官方的设置的动态输入，还是会报某些维度错误，注释掉
> config.disable_glob_info()，可以看到具体的报错的通道维度信息，但是应该怎样知道正确的通道数了？

把inference.pdmodel 拖到https://netron.app/ 中查看下出问题的参数，默认输入是640的；

根据你的输入计算这个参数的shape是多少即可；
