### ISSUE TITLE
辨識圖片結果為[('', nan)]

### ISSUE THREAD

**Issue by rockallorange** [PaddlePaddle/PaddleOCR#3708]
- 訓練時為自定義圖片集、字典
- paddleocr==2.0.6
- paddlepaddle-gpu == 2.1.1

使用以下指令產出預測模型(抓取latest model為1000epoch)
python3 tools/export_model.py -c ./output/rec_chinese_lite_v2.0/config.yml -o Global.pretrained_model=./output/rec_chinese_lite_v2.0/latest Global.save_inference_dir=./inference/rec_chinese/

[Code]
import cv2
import numpy as np
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/",
                rec_model_dir="./inference/rec_chinese/",
                cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/", 
                lang="ch",use_gpu=False,
                rec_char_type='ch', rec_char_dict_path='./ppocr/utils/dict/chinese_cht_dict2.txt') 
img_path = 'OCR_TEST_Sample_license/2_3license_01_cut_image_1.tif'
result = ocr.ocr(img_path, det=False)
print(result)

[output]
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='./inference/ch_ppocr_mobile_v2.0_cls_infer/', cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='./inference/ch_ppocr_server_v2.0_det_infer/', det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=10, output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='./ppocr/utils/dict/chinese_cht_dict2.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='./inference/rec_chinese/', save_log_path='./log_output/', show_log=True, table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=True)
[2021/08/17 09:59:30] root WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[('', nan)]

但若是較少epoch數的訓練model轉成預測模型(iter_epoch_30)
 python3 tools/export_model.py -c ./output/rec_chinese_lite_v2.0/config.yml -o Global.pretrained_model=./output/rec_chinese_lite_v2.0/iter_epoch_30 Global.save_inference_dir=./inference/rec_chinese/

預測結果有值，但信心分數與準確度極差
[('使', 0.0072729485)]

求解~

**Comment by littletomatodonkey** [comment]
你好，这个训练时的评估精度怎么样呢？先看下是训练问题还是模型导出问题
