### ISSUE TITLE
文本检测部分是否可以对检测到的文本框进行分类

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#3711]
文本检测部分是否可以对检测到的文本框进行分类

**Comment by littletomatodonkey** [comment]
你好，你说的分类指的是？目前应该主要还是二分类，即是否为文本区域

**Comment by Dandelion111** [comment]
我的意思是在文本检测的时候能不能既检测到文本又可以知道的类别，就像目标检测算法一样，能检测到目标还能知道目标属于哪一类

**Comment by Dandelion111** [comment]
> 你好，你说的分类指的是？目前应该主要还是二分类，即是否为文本区域

我的意思是在文本检测的时候能不能既检测到文本又可以知道的类别，就像目标检测算法一样，能检测到目标还能知道目标属于哪一类

**Comment by wu-yakun** [comment]
不可以的
