### ISSUE TITLE
文本识别训练时报错maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by fdshan** [PaddlePaddle/PaddleOCR#3713]
`root ERROR: When parsing line rec_train/ZHG031004900021.tif	[{"transcription": "茶史卷一", "points": [[1572, 35], [1632, 35], [1632, 253], [1572, 253]], "difficult": false}, {"transcription": "八十老人劉源長介祉父著", "points": [[1447, 85], [1537, 85], [1537, 638], [1447, 638]], "difficult": false}, {"transcription": "男謙吉", "points": [[1487, 685], [1554, 685], [1554, 868], [1487, 868]], "difficult": false}]
, error happened with msg: maximum recursion depth exceeded while calling a Python object`

标记是用PPOCRLabel工具做的。也查看了之前的issue，检查了格式，确定格式为图片名称 + \t + 文本 + \n，但还是报错。
请问这个该怎么改呢？ 感谢回答！

**Comment by zhangyingying520** [comment]
文本训练不是使用那种格式的标签文件吗？
图片名 文字内容
你这个是用的文字检测的那个标签文件把

**Comment by fdshan** [comment]
谢谢提醒，但是readme里有写说PPOCRLabel的输出结果可以直接用于识别模型的训练的。
目前我的数据都是多行文字，我看范例里都是单行文字，那多行文字该怎么做呀？

**Comment by zhangyingying520** [comment]
不是还有一个标签文件吗？没有坐标的那个，就算是多行文本的识别，那也是通过单行文本识别训练出来的模型，不信你看，官方提供数据集里面的图片和标签

**Comment by zhangyingying520** [comment]
这是文本识别模型训练，多行文本的识别，只要你的文本检测能够检测出多行文本，那最后他就是能实现多行文本识别的，就和官方提供的例程一样，而且你用的标签文本和官方数据集里面的都不一样

**Comment by zhangyingying520** [comment]
我用了没有坐标的那个标签文件，也出错了

**Comment by zhangyingying520** [comment]
你解决了吗

**Comment by zhangyingying520** [comment]
> 这是文本识别模型训练，多行文本的识别，只要你的文本检测能够检测出多行文本，那最后他就是能实现多行文本识别的，就和官方提供的例程一样，而且你用的标签文本和官方数据集里面的都不一样

[rec_gt.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7004101/rec_gt.txt)

**Comment by zhangyingying520** [comment]
我是用的上面这个标签文件，就可以正常训练了，我一开始没写对图片路径得时候也出现了你这个问题

**Comment by fdshan** [comment]
嗯，我已经可以正常训练啦

**Comment by DongLibin0804** [comment]
想问一下你是怎么解决的 我也是用Label导出的文件还是出错
