### ISSUE TITLE
ppstructure

### ISSUE THREAD

**Issue by tigermessi** [PaddlePaddle/PaddleOCR#3718]
ppstructure现有的模型可以识别中文表格么？还是说要自己训练模型进行替换？

**Comment by Gmgge** [comment]
我这边的数据测试发现，效果不是很理想。你可以自己测试一下你的数据，并且关掉你的另一个相同问题。

**Comment by tigermessi** [comment]
python3 predict_system.py --det_model_dir=inference/ch_ppocr_mobile_v2.0_det_infer --rec_model_dir=inference/ch_ppocr_mobile_v2.0_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=../doc/table/1.png --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --rec_char_type=ch --output=../output/table --vis_font_path=../doc/fonts/simfang.ttf 用这个语句可以识别中文表格么？我执行使一直在报错：unknown expection

**Comment by Gmgge** [comment]
请确认你的代码版本以及模型文件。我使用的whl包测试，未复现你的错误，有更详细的报错提示嘛？

**Comment by tigermessi** [comment]
当我运行
`import os
import cv2
from paddleocr import  PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True)`
时，出现了一下错误：
`C:\ProgramData\Anaconda3\python.exe C:/Users/梁高鹏/PycharmProjects/paddleOCR/ppsructure.py
C:\ProgramData\Anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\梁高鹏/.paddleocr/2.2.0.2\\ocr\\det\\ch\\ch_ppocr_mobile_v2.0_det_infer', det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=10, output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='C:\\ProgramData\\Anaconda3\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\梁高鹏/.paddleocr/2.2.0.2\\ocr\\rec\\ch\\ch_ppocr_mobile_v2.0_rec_infer', save_log_path='./log_output/', show_log=True, table_char_dict_path='C:\\ProgramData\\Anaconda3\\lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\table_structure_dict.txt', table_char_type='en', table_max_len=488, table_model_dir='C:\\Users\\梁高鹏/.paddleocr/2.2.0.2\\ocr\\table\\en_ppocr_mobile_v2.0_table_structure_infer', total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=True)
E0818 09:23:56.483762  9808 analysis_config.cc:81] Please compile with gpu to EnableGpu()
(NotFound) Cannot open file C:\Users\梁高鹏/.paddleocr/2.2.0.2\ocr\det\ch\ch_ppocr_mobile_v2.0_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:953)

Traceback (most recent call last):
  File "C:/Users/梁高鹏/PycharmProjects/paddleOCR/ppsructure.py", line 5, in <module>
    table_engine = PPStructure()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 316, in __init__
    super().__init__(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 45, in __init__
    self.text_system = TextSystem(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 99, in __init__
    args, 'det', logger)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddleocr\tools\infer\utility.py", line 250, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: Unknown exception`

**Comment by sucre111** [comment]
> 请确认你的代码版本以及模型文件。我使用的whl包测试，未复现你的错误，有更详细的报错提示嘛？

您好，使用ppstructure识别中文表格出来是乱码，您遇到了吗

**Comment by sucre111** [comment]
> 我这边的数据测试发现，效果不是很理想。你可以自己测试一下你的数据，并且关掉你的另一个相同问题。

您好，使用ppstructure识别中文表格出来是乱码，您遇到了吗

**Comment by wj920291253** [comment]
> 

我用vqa识别表单出现的也是乱码。。。你解决了吗？
rec_result [('抓定蕾莳党｀党恕捕癣获癣', 0.056176524609327316), ('璨蕉襄疹襄炝慈尨藩审癣塌往赫塌坋靴窍戾癣', 0.07258342951536179), ('竟睡细邑汶邑定長赫捕｀恕靴捕嘟靴蒂靴癣诚潘癣', 0.044424887746572495), ('鸽定痂党诚汰诚党癣诚藩癣往癣闫癣靴癣靴戾癣', 0.04831065982580185), ('竟睡细诃汶邑長赫捕｀恕靴腈癣嘟癣蒂癣诚潘癣峭', 0.05076713487505913), ('愚睡浮党蕉｀渊潘捕励恕往癣蒂获诚获癣', 0.0833430290222168)]
rec_result [('演稻昴現慈是瘸勃审诃癣藩癣往腈癣蒂癣诚癣', 0.09631882607936859), ('囗汶玫定緑徐戟舶´稻藩7藩捕靴潘往靴诚戾靴癣', 0.08099830895662308), ('熟垌玫張緑長徐昔且稻藩7靴往靴戾Ｅ靴癣', 0.08518553525209427), ('」邑噩碎１長包些帧跪敖漢長崂癣奈靴郜癖鲆艷衛窍含存靴存', 0.06990572065114975), ('演Ο演現慈Ο党峭鹗魚瘸勃暢诃癣藩党癣往腈癣腈潘癣蒂癣尨癣', 0.07136307656764984), ('箬緑箬捕１K寕K１鹗察藩恕潘往潘蒂潘获癣潘癣', 0.07049374282360077)]

**Comment by wj920291253** [comment]
@sucre111 
我用vqa识别表单出现的也是乱码。。。你解决了吗？
rec_result [('抓定蕾莳党｀党恕捕癣获癣', 0.056176524609327316), ('璨蕉襄疹襄炝慈尨藩审癣塌往赫塌坋靴窍戾癣', 0.07258342951536179), ('竟睡细邑汶邑定長赫捕｀恕靴捕嘟靴蒂靴癣诚潘癣', 0.044424887746572495), ('鸽定痂党诚汰诚党癣诚藩癣往癣闫癣靴癣靴戾癣', 0.04831065982580185), ('竟睡细诃汶邑長赫捕｀恕靴腈癣嘟癣蒂癣诚潘癣峭', 0.05076713487505913), ('愚睡浮党蕉｀渊潘捕励恕往癣蒂获诚获癣', 0.0833430290222168)]
rec_result [('演稻昴現慈是瘸勃审诃癣藩癣往腈癣蒂癣诚癣', 0.09631882607936859), ('囗汶玫定緑徐戟舶´稻藩7藩捕靴潘往靴诚戾靴癣', 0.08099830895662308), ('熟垌玫張緑長徐昔且稻藩7靴往靴戾Ｅ靴癣', 0.08518553525209427), ('」邑噩碎１長包些帧跪敖漢長崂癣奈靴郜癖鲆艷衛窍含存靴存', 0.06990572065114975), ('演Ο演現慈Ο党峭鹗魚瘸勃暢诃癣藩党癣往腈癣腈潘癣蒂癣尨癣', 0.07136307656764984), ('箬緑箬捕１K寕K１鹗察藩恕潘往潘蒂潘获癣潘癣', 0.07049374282360077)]
