### ISSUE TITLE
关于文字检测模型的比较

### ISSUE THREAD

**Issue by tairen99** [PaddlePaddle/PaddleOCR#3722]
首先谢谢你们优秀的PaddleOCR！
我想在EAST, DB, 和SAST中，选择一个最好的模型；这个比较从：文字检测精度，速度，和大型数据集的训练时间三个方面考虑。

在 [模型链接](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/algorithm_overview_en.md) 下载了三个训练好的模型后，我分析了里面的train.log。我发现三个模型使用了不同的 pretrained_model（DB 使用了ResNet50_vd_ssld_v2_pretrained，EAST使用了ResNet50_vd_pretrained，SAST使用了sast_r50_vd_synth），同时他们的训练数据也不一样；即使DB和EAST使用了同样的训练数据，但是它们的ratio_list也不一样。

请问你们有没有 比较过使用同样的pretrained_model 和 同样的训练数据集对这三种方法进行训练和比较？如果有，哪个会更好？

如果没有，我可能要自己进行对比，那么我是否能够直接将 EAST 和 SAST 的pretrained_model 替换成 ResNet50_vd_ssld_v2_pretrained？

另外请问从哪里可以下载到这个 sast_r50_vd_synth 的 pretrained_model？ 这个 sast_r50_vd_synth 是不是 SAST 在 Synthetic dataset 训练得到的？

谢谢！

**Comment by huangjianyi666** [comment]
sast_r50_vd_synth好像并未开放

**Comment by MissPenguin** [comment]
您好，关于您的这几个问题，简答解答一下：

ResNet50_vd_ssld_v2_pretrained在ImageNet上比ResNet50_vd_pretrained好一点，具体参考[PaddleClas](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/en/ImageNet_models_en.md)，但用于文本检测pretrain，并不一定前者比后者好，但差别不会太大。sast的pretrain模型sast_r50_vd_synth是在公开的合成数据集synthtext上训练得到的模型，这么做是为了和原paper对齐，这个模型暂时没有发布，有需要可以自己训练一下。

建议：单看效果，应该是sast优于db优于east，并且sast类似于db和sast的融合，速度应该是db最快，如果是要落地业务场景，建议直接试试db是否满足。

**Comment by tairen99** [comment]
@MissPenguin，

    明白了，谢谢您的答复！

**Comment by tengerye** [comment]
@MissPenguin Hi, may I ask did you use SynthText as pre-training dataset for the performance in [this](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/algorithm_overview_en.md)?

As I noticed, the performance of DB-Res50(0.86/0.78) is lower than reported 0.88/0.83.
