### ISSUE TITLE
在AI Studio中!pip install "paddleocr>=2.2"的问题

### ISSUE THREAD

**Issue by tigermessi** [PaddlePaddle/PaddleOCR#3726]
开发者您好！
我在AI Studio中!pip install "paddleocr>=2.2"，而后就停留在了Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (PEP 517) ... /，请问有什么解决办法么？
我的环境的python3.7 框架PaddlePaddle 2.0.2

**Comment by MissPenguin** [comment]
应该是正在building，需要多等待一段时间

**Comment by ioracion** [comment]
pip install --upgrade pip
