### ISSUE TITLE
竖排文字识别顺序问题

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#3727]
目前竖排文字识别 排序存在比较大的问题 看到商业化软件做的都比较好 可以自动识别 

原图如下：
![中文竖排](https://user-images.githubusercontent.com/14155359/129851869-758a21c2-7ad6-4b87-9ab1-24f91e93ae00.jpg)

识别结果
```
觉来知是梦＇不胜悲
昨夜夜半?枕上分明梦见。 半羞还半喜 语多时，依旧桃花面?频低柳叶眉
不知魂已断‘空有梦相随·      别
西                       女冠子

却天边月＇没人知· 
君时，忍泪伴低面含羞半眉   月十七＇正是去年今日。

 欲去又依依。
韦庄

```

**Comment by MissPenguin** [comment]
目前结果打印是按照检测框从上到下排序打印的，对于这种竖排文本确实不太友好，可以在代码中修改排序逻辑为更适合自己场景的。
