### ISSUE TITLE
关于模型部署以及转换的几个问题

### ISSUE THREAD

**Issue by Syencil** [PaddlePaddle/PaddleOCR#373]
1. 当我用export_model.py将模型转成infer模式之后，调用x2paddle将其转换为onnx之后，出现了batchnorm和conv维度不匹配的问题<br>
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Deserialize tensor batch_norm_48.w_0 failed.corrupted protobuf data: tensor shape size(24) does not match the data size(64) in proto
```
2. 提供的ch_det_mv3_db这种模型可以直接用infer_det.py测试吗
3. ch_det_mv3_db转成onnx之后精度损失好像非常大

**Comment by LDOUBLEV** [comment]
1. 目前PaddleOCR的模型转onnx模型可能会有些问题，如果你想要部署的话，可以考虑下我们lite部署，C++ inference， serving部署等。
2. 从主页下载的inference模型（ch_det_mv3_db_infer）用PaddleOCR/tools/infer/predict_det.py预测，预训练模型(ch_det_mv3_db)用PaddleOCR/tools/infer_det.py预测，详细使用可以参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md
