### ISSUE TITLE
模型推理，动态尺度输入trt dynamic_shape问题。

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleOCR#3730]
**环境：**centos 7
**cuda:** 10.1
**cudnn:**7.5
**设备：**T4
**tensorRT:**TensorRT-6.0.1.5
**模型：**det_r50_vd_db
**paddlepaddle-gpu**:2.1.2

**运行命令中加入：**--use_tensorrt True
**报错如下：**
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 215, in <module>
    text_detector = TextDetector(args)
  File "tools/infer/predict_det.py", line 100, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/xxxxxxxxx/xxx/xxx/paddle/PaddleOCR-release-2.1/tools/infer/utility.py", line 173, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [x] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /paddle/paddle/fluid/inference/tensorrt/engine.h:103)

**寻找报错原因，没有设置动态尺度信息：config.set_trt_dynamic_shape_info。**

**模型输入信息：**
![image](https://user-images.githubusercontent.com/36955510/129859677-849fee00-b916-4426-8657-d8f5fb755fed.png)

**添加动态尺度信息：**
![image](https://user-images.githubusercontent.com/36955510/129859840-405dd6f6-762a-46f9-9676-78a1809f3333.png)

再次运行报错如下：
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 215, in <module>
    text_detector = TextDetector(args)
  File "tools/infer/predict_det.py", line 100, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "xxxxx/paddle/PaddleOCR-release-2.1/tools/infer/utility.py", line 169, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

**如果我将推理模型固定尺度，推理没有问题，动态尺度输入会报错，各位大佬我现在应该怎么修改。**

**Comment by ziyaxuanyi** [comment]
你还有一些输入没有设置动态尺度，注释掉config.disable_glog_info()有更详细的报错，可查看具体那层没有设置，添加即可

**Comment by LiquorPerfect** [comment]
@ziyaxuanyi 
**我把 # config.disable_glog_info() 注释掉了，还是如下错误，帮忙看一下：**  其余代码没有改动
W0819 14:16:01.677834 84180 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0819 14:16:01.715567 84180 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0819 14:16:02.281651 84180 graph_pattern_detector.cc:91] ---  detected 56 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0819 14:16:02.323088 84180 graph_pattern_detector.cc:91] ---  detected 56 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0819 14:16:02.354377 84180 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 131 nodes
I0819 14:16:02.377585 84180 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0819 14:16:02.988652 84180 engine.cc:202] Run Paddle-TRT Dynamic Shape mode.
I0819 14:16:11.670855 84180 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 13 nodes
I0819 14:16:11.674070 84180 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0819 14:16:11.675817 84180 op_converter.h:211] trt input [conv2d_123.tmp_0] dynamic shape info not set, please check and retry.
I0819 14:16:11.675843 84180 op_converter.h:211] trt input [nearest_interp_v2_2.tmp_0] dynamic shape info not set, please check and retry.
I0819 14:16:11.675858 84180 op_converter.h:211] trt input [nearest_interp_v2_3.tmp_0] dynamic shape info not set, please check and retry.
I0819 14:16:11.675870 84180 op_converter.h:211] trt input [nearest_interp_v2_4.tmp_0] dynamic shape info not set, please check and retry.
I0819 14:16:11.675882 84180 op_converter.h:211] trt input [nearest_interp_v2_5.tmp_0] dynamic shape info not set, please check and retry.
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 215, in <module>
    text_detector = TextDetector(args)
  File "tools/infer/predict_det.py", line 100, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/mnt/ssd1/zhangjinlong21/paddle/PaddleOCR-release-2.1/tools/infer/utility.py", line 176, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)
