### ISSUE TITLE
句子有整句的丢失，有办法解决吗？

### ISSUE THREAD

**Issue by GuoQingSong1007** [PaddlePaddle/PaddleOCR#3731]
![image](https://user-images.githubusercontent.com/50289836/129859281-dc82d459-4c75-496d-a90a-cc5b0c59949a.png)
![image](https://user-images.githubusercontent.com/50289836/129859374-15b47041-bf0b-4a57-9eff-ecbeca2448ef.png)
如图，一张图片可能丢失几行。

**Comment by bikerr** [comment]
检测模型二值化阈值过高 `det_db_box_thresh=0.5`调低一点儿试试

**Comment by MissPenguin** [comment]
可能是后处理的问题，楼上的方法可以一试

**Comment by GuoQingSong1007** [comment]
> 检测模型二值化阈值过高 `det_db_box_thresh=0.5`调低一点儿试试

谢谢。情况好了些，但还是有丢句子。请问还有其他参数可优化吗？

**Comment by ykpercy** [comment]
det_limit_side_len这个输入图片尺寸改大一点试试
