### ISSUE TITLE
请问有提供ppyolov2_r50vd_dcn_365e_publaynet模型的下载地址吗

### ISSUE THREAD

**Issue by yaocctao** [PaddlePaddle/PaddleOCR#3732]
我想用ppyolov2_r50vd_dcn_365e_publaynet模型在我自定义的数据集下进行fine tune，但是没有找到ppyolov2_r50vd_dcn_365e_publaynet模型的下载地址，只有inference的下载地址。

**Comment by littletomatodonkey** [comment]
你好，可以从这里下载：https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_publaynet_pretrained.pdparams
