### ISSUE TITLE
PGNet训练best模型与inference的差异

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3733]
想请教一下拉取得代码release/2.2训练完的best模型与inference具有一定差异:
转完inference模型后 : 检测框的数量与检测的字符位数部分与best模型不一致
请你们可以检查一下配置文件相关参数 运行inference模型时,
ValueError: too many values to unpack (expected 3)
![image](https://user-images.githubusercontent.com/65577659/129873312-0b12d78a-664e-4d2c-b250-8c9de065b3b1.png)

utility.py文件中,259行去掉config后inference才能正常运行
请检查一下配置部分相关py代码 测试一下模型的一致性

**Comment by cpene1** [comment]
Thank you!

**Comment by LDOUBLEV** [comment]
修复pgnet 预测 的问题：
dygraph: https://github.com/PaddlePaddle/PaddleOCR/pull/3751

https://github.com/PaddlePaddle/PaddleOCR/pull/3752
