### ISSUE TITLE
TensorRT问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3734]
部署测试Inference+TensorRT没有问题，能够进行识别。但重复使用之后显存会不断增加，最终崩溃。怎么解决paddle显存释放的问题？

**Comment by LDOUBLEV** [comment]
重复使用是连续预测多张图像吗？
你的cudnn版本是多少的，如果是cudnn8.0的，建议更新到8.1
