### ISSUE TITLE
检测与识别结合问题

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#3736]
![无标题](https://user-images.githubusercontent.com/87969070/129990305-0914770c-70bd-4bd4-91c6-6a77d9dcf295.png)
我将检测模型与识别模型结合起来之后，得到的结果有中文，但是我在识别模型训练的是数字，请问这是怎么一回事？需要自己加字典吗？我尝试了加字典之后，发现识别模型无法训练。

**Comment by LDOUBLEV** [comment]
> 我将检测模型与识别模型结合起来之后，得到的结果有中文

需要更换为你训练用的字典文件

> 我尝试了加字典之后，发现识别模型无法训练。

出现什么报错？
