### ISSUE TITLE
CPU识别速度

### ISSUE THREAD

**Issue by chocolate-byte** [PaddlePaddle/PaddleOCR#3738]
想做一个实时的视频识别，大概传入像素在300x400以内，一帧会有6个以内的简单字符，想问一下有人试过window下CPU的速度最快能达50ms以内吗，是用什么模型实现的，是CRNN还是图像处理然后分割的传统方式

**Comment by LDOUBLEV** [comment]
可以先试下ppocr_mobile 模型是否符合你的需求

![image](https://user-images.githubusercontent.com/26592129/130042323-44343c67-7727-4122-85c0-f5675e88402a.png)

**Comment by chocolate-byte** [comment]
mobilnetv3已经训练过了大概批量计算的识别时间平均是0.1s，这样就算做成视频实际上可能10帧都不到，不清楚这个是不是可以去掉文本检测进行加速？可以请问下有其它更快的模型测试速度嘛，比如说repvgg-A0这种

**Comment by Sanster** [comment]
字符在图片中的比例如何？如果不是很小的话，DB训练/推理的尺寸完全可以改小，场景简单的话，mbv3 可以用 large_0.35 甚至 small

**Comment by chocolate-byte** [comment]
预计是用人工标注加上一小部分形态学确定大概位置，所以位置可以基本保证在画面中心面积占一半以上，可以请问下你们有测试过cpu最快可以做到什么程度吗，另外不是很清楚0.35这个应该在哪里调整

**Comment by Sanster** [comment]
其实你这个挺快了感觉。
mbv3 可以调整 scale 和 model_name(small/large) https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L24

**Comment by chocolate-byte** [comment]
您好我发现别人似乎有用crnn做到40ms的一个评论，请问这个速度40ms和7ms是cpu都可以实现吗，感觉没人提到过这个加速问题
https://github.com/PaddlePaddle/PaddleOCR/issues/2950



> > > 对比过 onnxruntime 和 pytorch ，ORT 的 CPU 推理速度有明显的优势，以 crnn 为例，32*128 尺寸的输入，7ms vs 40 ms，具体耗时还要看你的 backbone 规模和 cpu 主频了，加钱换个主频高点的 CPU....或者 check 下现在的 cpu 是不是支持 AVX512 的，paddle 对 AVX512 有没有优化
> > 
> > 
> > 好的，您好，您这里能提供一下示例代码嘛？因为我之前按照官方的方式去做的测试
> 
> 可以参考一下[RapidOCR](https://github.com/RapidOCR/RapidOCR)

**Comment by chocolate-byte** [comment]
或者是否可以做到去掉文本检测的模型推理从而减半时间？
