### ISSUE TITLE
pyinstaller 打包问题

### ISSUE THREAD

**Issue by cx4** [PaddlePaddle/PaddleOCR#3740]
使用pyinstaller 打包，发现很多的modules 不能够被正确识别，在以文件夹作为module name的时候文件夹中不包含__init__.py文件，导致无法被识别为module

**Comment by LDOUBLEV** [comment]
没有吧，测试正常打包和使用是没问题的，打包安装paddleocr后，可以先cd 到其他目录再调用import paddleocr ,不然在PaddleOCR 跟目录下可能会出现paddleocr重复的问题

**Comment by cx4** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/1024

**Comment by cx4** [comment]
经过多次测试，在python3.7下打包仅需修改一处 可以比较好的完成打包，其他版本可能问题比较多。

**Comment by HeinzGong** [comment]
> 经过多次测试，在python3.7下打包仅需修改一处 可以比较好的完成打包，其他版本可能问题比较多。

请问怎么修改，我现在包含paddleocr项目打包exe运行的时候一堆错误，无法正常运行

**Comment by cx4** [comment]
> > 经过多次测试，在python3.7下打包仅需修改一处 可以比较好的完成打包，其他版本可能问题比较多。
> 
> 请问怎么修改，我现在包含paddleocr项目打包exe运行的时候一堆错误，无法正常运行

看你具体报什么错了

**Comment by WENDGOUNDI** [comment]
Hi @cx4. Were you able to package paddleocr with pyinstaller? Thanks

**Comment by kerneltravel** [comment]
> Hi @cx4. Were you able to package paddleocr with pyinstaller? Thanks

you could pyiinstaller with additional parameter:  
`--collect-all  paddleocr`

**Comment by kerneltravel** [comment]
[pyinstaller 打包问题](https://github.com/PaddlePaddle/PaddleOCR/issues/3740#top)  使用pyinstaller 打包时增加参数： 
`--collect-all  paddleocr` 可避免pyinstaller 打包后exe文件运行失败的问题。

**Comment by rve** [comment]
> [pyinstaller 打包问题](https://github.com/PaddlePaddle/PaddleOCR/issues/3740#top) 使用pyinstaller 打包时增加参数： `--collect-all paddleocr` 可避免pyinstaller 打包后exe文件运行失败的问题。

It says
> 525 WARNING: collect_data_files - skipping data collection for module 'paddleocr' as it is not a package.
> 526 WARNING: collect_dynamic_libs - skipping library collection for module 'paddleocr' as it is not a package.

**Comment by kerneltravel** [comment]
> --collect-all

parameter collect-all usage from `pyinstaller --help`: 

```
--collect-all MODULENAME
                        Collect all submodules, data files, and binaries from the specified package or module. This option can be used multiple times.
```
so `--collect-all paddleocr`  will copy paddleocr's source directory to the directory of packaged executable file.
