### ISSUE TITLE
linux环境部署py37+cudn10.0.130+cudnn7.7.7，应该安装哪个paddlepaddle包？调用predict_system.py预测出现如下问题：The third-party dynamic library (libcusolver.so) that Paddle depends on is not configured correctly

### ISSUE THREAD

**Issue by zylxadz** [PaddlePaddle/PaddleOCR#3742]
1、环境
python：3.7.11
cudn：10.0.130
cudnn：7.6.5
paddlepaddle安装包：python3 -m pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple
import paddle.fluid成功。已正确添加环境变量，libcusolver.so文件存在。
2、请教：应该如何使用pip或conda安装哪一个版本的paddlepaddle呢？
3、报错信息如下：
W0818 20:07:44.675881 2449855 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 193, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 126, in main
    res = text_sys(img)
  File "tools/infer/predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/qingru/PaddleOCR/tools/infer/predict_det.py", line 192, in __call__
    self.input_tensor.copy_from_cpu(img)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcusolver.so) that Paddle depends on is not configured correctly. (error code is libcusolver.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:234)

**Comment by LDOUBLEV** [comment]
你的CUDA和CUDNN库没找到吧，可以按照提示操作，如果安装了CUDA和CUDNN，可以设置下环境变量

另外，建议更新CUDA到10.1版本以上
