### ISSUE TITLE
将PPOCR的DB文本检测模型转为ONNX之后，精度明显下降

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleOCR#3743]
问题说明：在未转ONNX之前，PPOCR的DB文本检测模型检测的相当准，但是转为ONNX之后，精度明显下降。
我转ONNX的方法是先通过export_model.py转inference model，已经验证，inference model检测也非常准，因此可以排除这个步骤的问题。
之后，我通过paddle2onnx将inference model转为onnx模型。经过验证，onnx模型的准确率非常低，精度明显下降。因此，怀疑是转onnx时的问题。
转onnx时借鉴下图方法，并且paddle2onnx版本是0.7，满足大于0.6的要求。我比较纳闷这个问题，请大佬指教！！！

![企业微信截图_16293428378073](https://user-images.githubusercontent.com/48200202/130001835-a0307855-09ca-4012-b1a0-fdce1bc8262b.png)

**Comment by LDOUBLEV** [comment]
建议在Paddle2Onnx repo下提问:https://github.com/PaddlePaddle/Paddle2ONNX/issues
