### ISSUE TITLE
训练过程中loss突然增大，acc突然降为0

### ISSUE THREAD

**Issue by Zhang-O** [PaddlePaddle/PaddleOCR#3747]
![image](https://user-images.githubusercontent.com/18193972/130041861-58313cb5-fe2f-4c98-8ea3-bc2e7cfecd22.png)

背景： rec模型训练到一半机器死机了，然后resume继续训练，训练了不到3个小时突然出现这种情况

**Comment by littletomatodonkey** [comment]
这个之前没遇到过，数据标注确定没问题的话，从头训下看下呢？

**Comment by Zhang-O** [comment]
数据没问题，训练都是resume 已有模型 继续训练的，这种问题出现了2次，重新训练应该不会出现问题

**Comment by littletomatodonkey** [comment]
好的，我们记录下，看下是否能够复现～

**Comment by Zhang-O** [comment]
**
![image](https://user-images.githubusercontent.com/18193972/131278386-ea5d5ba0-36c7-4ea0-9521-fc267a3566f0.png)
**

我进行敏感度剪枝，训练过程中又出现这个问题，前8个epoch都是正常的，不知道为什么突然出现这个问题？？？

**Comment by Zhang-O** [comment]
> 数据没问题，训练都是resume 已有模型 继续训练的，这种问题出现了2次，重新训练暂时没有遇到过这种情况

多个epoch没有出现问题，突然某个epoch出现问题，是不是说明不是数据的问题

**Comment by Zhang-O** [comment]
> **
> ![image](https://user-images.githubusercontent.com/18193972/131278386-ea5d5ba0-36c7-4ea0-9521-fc267a3566f0.png)
> **
> 
> 我进行敏感度剪枝，训练过程中又出现这个问题，前8个epoch都是正常的，不知道为什么突然出现这个问题？？？

loss 出现这种大幅度的震荡，准确率也出现大幅度的震荡，其他人没有遇到过吗

**Comment by maximli** [comment]
> > **
> > ![image](https://user-images.githubusercontent.com/18193972/131278386-ea5d5ba0-36c7-4ea0-9521-fc267a3566f0.png)
> > **
> > 我进行敏感度剪枝，训练过程中又出现这个问题，前8个epoch都是正常的，不知道为什么突然出现这个问题？？？
> 
> loss 出现这种大幅度的震荡，准确率也出现大幅度的震荡，其他人没有遇到过吗？
> 前面若干个 epoch 没有问题，从中间某个epoch开始就出现这个现象了

我遇到了类似的问题，但是我的acc没有到0，到0.4左右，不再上升了，总是在0.4左右上下波动。loss会在1.x波动，不在继续下降。

**Comment by jpy-lucky** [comment]
> > **
> > ![image](https://user-images.githubusercontent.com/18193972/131278386-ea5d5ba0-36c7-4ea0-9521-fc267a3566f0.png)
> > **
> > 我进行敏感度剪枝，训练过程中又出现这个问题，前8个epoch都是正常的，不知道为什么突然出现这个问题？？？
> 
> loss 出现这种大幅度的震荡，准确率也出现大幅度的震荡，其他人没有遇到过吗？ 前面若干个 epoch 没有问题，从中间某个epoch开始就出现这个现象了


> > **
> > ![image](https://user-images.githubusercontent.com/18193972/131278386-ea5d5ba0-36c7-4ea0-9521-fc267a3566f0.png)
> > **
> > 我进行敏感度剪枝，训练过程中又出现这个问题，前8个epoch都是正常的，不知道为什么突然出现这个问题？？？
> 
> loss 出现这种大幅度的震荡，准确率也出现大幅度的震荡，其他人没有遇到过吗？ 前面若干个 epoch 没有问题，从中间某个epoch开始就出现这个现象了

请问解决了吗？我也遇到了。昨天也遇到了，它是训练一遍数据，测试一次精度那种，那个测试精度就变为0了，没搭理它，一会就又变成95%了，今天训练又变为0了，我就终止训练了

**Comment by thsno02** [comment]
调整 learning rate，能有效解决这个问题。

**Comment by Shy280** [comment]
> 调整 学习率，能有效解决这个问题。

如何调整 或大或小？

**Comment by thsno02** [comment]
做实验呀

**Comment by scuxxs** [comment]
请问是否解决，我也遇到相同问题

**Comment by No360201** [comment]
我也遇到了相同的问题，请问可以解决吗

**Comment by Punchlinezm** [comment]
请问解决了吗
