### ISSUE TITLE
PaddleOCR在windows C++推理有吗我看了只有linux介绍

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#375]
我想把PaddleOCR做成windows上可执行程序运行，可以吗，用C#也可以，我测试过目前windows上python是可以的，但是我想要C++版本或者.net版本

**Comment by littletomatodonkey** [comment]
C++ inference在windows上的支持我们正在开发中，敬请期待~

**Comment by littleSpongebob** [comment]
> C++ inference在windows上的支持我们正在开发中，敬请期待~

期待(๑˙ー˙๑)

**Comment by littletomatodonkey** [comment]
你好，目前基于Windows10 + vs2019 PaddleOCR已经跑通，可以参考这个PR： #389

**Comment by littleSpongebob** [comment]
> 你好，目前基于Windows10 + vs2019 PaddleOCR已经跑通，可以参考这个PR： #389

你好想了解一下，打包成exe或者dll之后，大概会有多大，我看lib库由1.6个G，应该不用全部链接进去吧？

**Comment by littletomatodonkey** [comment]
exe是43M左右，然后如果您可能也得包含opencv，Paddle预测库的dll，如果使用gpu预测的话，也得再加上cuda的dll~

**Comment by littleSpongebob** [comment]
> exe是43M左右，然后如果您可能也得包含opencv，Paddle预测库的dll，如果使用gpu预测的话，也得再加上cuda的dll~

你好，我今天尝试了一下x86的编译流程，好像会出问题，会报一堆无法解析的外部符号，请问一下怎么解决(ﾟoﾟ;

**Comment by littletomatodonkey** [comment]
可以你操作的流程以及错误的日志发出来吗？感觉是lib库路径不对的原因

**Comment by littleSpongebob** [comment]
> 可以把你操作的流程以及错误的日志发出来吗？感觉是lib库路径不对的原因

你好，谢谢关注，已经解决问题了

**Comment by xinsuinizhuan** [comment]
楼主，你跑通了吗，使用C++ windows调用，我也想跑

**Comment by xinsuinizhuan** [comment]
楼主，你跑通了吗，使用C++ windows调用，然分装成dll？

**Comment by littleSpongebob** [comment]
> 楼主，你跑通了吗，使用C++ windows调用，然分装成dll？

exe编出来了，封装dll还没搞，你有相关的经验么，我也是第一次搞dll

**Comment by xinsuinizhuan** [comment]
我也是刚跑通，但是速度很慢，处理一张图形得3s左右，cpu的。你是自己编译的paddle，我自己编译一直有问题

**Comment by Yo-gurts** [comment]
> 我也是刚跑通，但是速度很慢，处理一张图形得3s左右，cpu的。你是自己编译的paddle，我自己编译一直有问题

你们是用他官方提供的cmakelist来生成的吗？就我想弄个界面那种，不会改cmakelist.....如果直接用vs 来生成就一堆错

**Comment by littleSpongebob** [comment]
> 我也是刚跑通，但是速度很慢，处理一张图形得3s左右，cpu的。你是自己编译的paddle，我自己编译一直有问题

是你的图片比较大吧，我的1s左右

**Comment by littleSpongebob** [comment]
> > 我也是刚跑通，但是速度很慢，处理一张图形得3s左右，cpu的。你是自己编译的paddle，我自己编译一直有问题
> 
> 你们是用他官方提供的cmakelist来生成的吗？就我想弄个界面那种，不会改cmakelist.....如果直接用vs 来生成就一堆错
不会吧，我因为要搞x86的所以改了cmakelist，你要是x64的应该不用的吧

**Comment by littleSpongebob** [comment]
@littletomatodonkey 你好，请问在dbnet里的UnClip实现的是那个步骤或者功能？
`cv::RotatedRect PostProcessor::UnClip(std::vector<std::vector<float>> box,
                                      const float &unclip_ratio) {
  float distance = 1.0;

  GetContourArea(box, unclip_ratio, distance);

  ClipperLib::ClipperOffset offset;
  ClipperLib::Path p;
  p << ClipperLib::IntPoint(int(box[0][0]), int(box[0][1]))
    << ClipperLib::IntPoint(int(box[1][0]), int(box[1][1]))
    << ClipperLib::IntPoint(int(box[2][0]), int(box[2][1]))
    << ClipperLib::IntPoint(int(box[3][0]), int(box[3][1]));
  offset.AddPath(p, ClipperLib::jtRound, ClipperLib::etClosedPolygon);

  ClipperLib::Paths soln;
  offset.Execute(soln, distance);
  std::vector<cv::Point2f> points;

  for (int j = 0; j < soln.size(); j++) {
    for (int i = 0; i < soln[soln.size() - 1].size(); i++) {
      points.emplace_back(soln[j][i].X, soln[j][i].Y);
    }
  }
  cv::RotatedRect res;
  if (points.size() <= 0) {
    res = cv::RotatedRect(cv::Point2f(0, 0), cv::Size2f(1, 1), 0);
  } else {
    res = cv::minAreaRect(points);
  }
  return res;
}`

**Comment by littleSpongebob** [comment]
@littletomatodonkey 
https://github.com/PaddlePaddle/PaddleOCR/blob/a0c8968c96b11982f8806bd05c6cb4ece5f6b068/deploy/cpp_infer/src/postprocess_op.cpp#L37

**Comment by PRNDA** [comment]
> > 楼主，你跑通了吗，使用C++ windows调用，然分装成dll？
> 
> exe编出来了，封装dll还没搞，你有相关的经验么，我也是第一次搞dll

可否提供一个demo项目？

**Comment by tyushua1** [comment]
> > exe是43M左右，然后如果您可能也得包含opencv，Paddle预测库的dll，如果使用gpu预测的话，也得再加上cuda的dll~
> 
> 你好，我今天尝试了一下x86的编译流程，好像会出问题，会报一堆无法解析的外部符号，请问一下怎么解决(ﾟoﾟ;

您好，请问您这个问题是怎么解决的呢?需要编译一个x86的Windows预测库（fluid_inference_install_dir）吗？还是lib的路径问题呢？

**Comment by kui606** [comment]
ocr_system.exe  D:\projects\PaddleOCR\deploy\cpp_infer\tools\config.txt E:\Python\OCR\PaddleOCR-develop\doc\imgs\10.jpg
这样的命令直接崩溃了

**Comment by SQ-Deng** [comment]
请问可以发一个调试通过的demo吗？

**Comment by SQ-Deng** [comment]
@littleSpongebob 你好，请问编译报错一堆是怎么解决的？我也遇上了这个问题

**Comment by zx2457** [comment]
同问 怎么解决的编译报错一堆无法解析的符号
