### ISSUE TITLE
Build Errors without any changes.

### ISSUE THREAD

**Issue by igneous8k** [PaddlePaddle/PaddleOCR#3754]
hi, im having trouble building the app , it logs errors on the code directly taken from repo no changes at all, ill attach the logs below:
 The imported target "libjpeg-turbo" references the file

     "/home/raghav/Downloads/PaddleOCR-release-2.2/deploy/android_demo/app/OpenCV/sdk/native/3rdparty/libs/armeabi-v7a/liblibjpeg-turbo.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/raghav/Downloads/PaddleOCR-release-2.2/deploy/android_demo/app/OpenCV/sdk/native/jni/abi-armeabi-v7a/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /home/raghav/Downloads/PaddleOCR-release-2.2/deploy/android_demo/app/OpenCV/sdk/native/jni/abi-armeabi-v7a/OpenCVConfig.cmake:139 (include)
  /home/raghav/Downloads/PaddleOCR-release-2.2/deploy/android_demo/app/OpenCV/sdk/native/jni/OpenCVConfig.cmake:44 (include)
  CMakeLists.txt:18 (find_package)

**Comment by WenmuZhou** [comment]
I just tried to download the code and run it directly. It can run successfully, and I can also see the liblibjpeg-turbo.a file in the android_demo/app/OpenCV/sdk/native/3rdparty/libs/armeabi-v7a/ directory. See if there is a problem with your network and the download was not successful 
![image](https://user-images.githubusercontent.com/12406017/130171008-65a20b09-7df5-4425-91a1-7d637dc33aa1.png)

**Comment by igneous8k** [comment]
There's no openCV directory for me when I cloned the project. What can be the issue here?

**Comment by igneous8k** [comment]
hi , i have solved the issue by getting sdk from opencv, the app is working , but it is working on photo , you will have to click and photo and then it runs the model and reads the characters, what i wanna know is how do i make it so it can run the model on camera feed live and continuously and stop reading once it finishes readying everything.

**Comment by rsingh2083** [comment]
> I just tried to download the code and run it directly. It can run successfully, and I can also see the liblibjpeg-turbo.a file in the android_demo/app/OpenCV/sdk/native/3rdparty/libs/armeabi-v7a/ directory. See if there is a problem with your network and the download was not successful
> ![image](https://user-images.githubusercontent.com/12406017/130171008-65a20b09-7df5-4425-91a1-7d637dc33aa1.png)

Now how do we make the app run on live video/Camera ?

**Comment by raghavzns** [comment]
> You can refer to other Android programs that take real-time photos

There is no documentation on how to run Paddle predictor on video stream.
