### ISSUE TITLE
关于单个小字符，数字和符号的侦测问题

### ISSUE THREAD

**Issue by tairen99** [PaddlePaddle/PaddleOCR#3755]
你好， PaddleOCR, @MissPenguin ，
谢谢你们的项目和您之前的回答和帮助！

我使用了默认的配置文件 [DB Resnet50](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/configs/det/det_r50_vd_db.yml)  对我自己的数据进行了训练。数据集包含2000张不同大小的图片，大部分为大概 2000*3000 大小的图片，其他的大小不等。经过1100 Epochs训练后，我发现整体预测效果还不错，但是对单独的标点符号，单独的数字和单独的小字符，大部分有遗漏。想请教该如何有效的设置 配置文件 “det_r50_vd_db.yml” 去提高模型对单独标点符号，数字和小字符的侦测。

通过阅读程序和以前的问题，是不是需要修改配置文件中的：

      - MakeShrinkMap:
              min_text_size: 8 ？
--------------------------------------------
这个“IaaAugment” 是用来对训练数据进行提升增加的吧？ 我看到程序里面还有“blur.py”, "contrast.py", 以及 ”color.py“等等，为什么这里选择的是 “Fliplr”， “Affine/rotate” 和 “Resize”? 进行这些操作如何保证 与标记好的 label 的坐标对应呢？

      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }

---------------------------------------------
针对我使用的大图片：

      - EastRandomCropData:
          size: [640, 640]

这个 size 需要设置更大吗？ 这个EastRandomCropData 的作用是什么呢？

--------------------------------------------

另外“MakeBorderMap” 的目的是什么呢？这些参数“shrink_ratio”，“thresh_min”和“thresh_max”会如何影响训练数据呢？

      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7

-------------------------------------------
经过测试我发现，

      - DetResizeForTest:
          image_shape: [736, 1280]

对训练时的验证和预测效果有很大的影响。通过阅读 [程序](https://github.com/PaddlePaddle/PaddleOCR/blob/ac31a18b6177a2ca3e7701d2aa80a6295fbe798f/ppocr/data/imaug/operators.py#L115)，我发现这里有大致有3种 resize的类型，针对我这种情况（想更好的侦测单个的字符，数字，标点符号），我该选择哪种呢？这个 “limit_side_len” 设置的越大，图片就会越大，是不是训练的时候，就会需要更多的显存？
如果我不设置 “- DetResizeForTest:”， 则训练就是用原始图片进行训练？这样有什么不好吗？ 训练显存会随图片大小而变化？

这个训练既烧钱，又耗时，还请您多多指点！
谢谢！

**Comment by MissPenguin** [comment]
您好，简单解答一下您的几个问题
1.  DB算法是个分割算法，在单字符和小字符的检测上有原生的缺陷，因为检测到的像素点很少，很容易当初噪点过滤掉，可以试试把min_text_size调小也许能补回一些召回
2. 数据增强选择哪些增强是和原文对应的，图像变换后也会对label做相应变换，有兴趣可以自己尝试别的增强方式
3. 训练时的输入尺寸EastRandomCropData，640就够了，这是crop后的size，不是直接resize原图，可以自己把预处理完后的数据画出来看看就清楚了
4. MakeBorderMap里的3个参数是基于原始标注生成3种输入数据的超参数，可以查看db原文，里面有详细描述
5. DetResizeForTest是测试时的输入尺寸，和训练无关

**Comment by tairen99** [comment]
@MissPenguin 您好！
谢谢您回复！

针对 第2点 数据增强的选择，弱弱的问一下 在PaddleOCR 程序的哪部分 有 “Fliplr”，“Affine/rotate” 和 “Resize“对应的 label的处理和变换？找了好一会没有找到
再次表示感谢！
