### ISSUE TITLE
styletext不能生成标点和存在漏字问题

### ISSUE THREAD

**Issue by mrlihellohorld** [PaddlePaddle/PaddleOCR#3756]
感谢飞奖团队开源如此优秀的项目，我在使用styletext生成文字识别数据集时遇到一些问题，向各位老师请教一下
1. 在ch模式下，语料文本中有标点，生成图片时候无法生成标点。
2. 在en模式下，使用5W中通用数据集，生成的数字和英文有一部分是很难肉眼识别的，因为风格图片的风格千姿百态，这种图片会影响训练识别网络吗，例如：
![图片](https://user-images.githubusercontent.com/31719207/130171303-07623227-0337-445b-a2bf-31190fe096a9.png)
3. 在ch模式下，使用个别风格迁移图片生成图片时，存在漏字的情况。例如：
风格图片：
![图片](https://user-images.githubusercontent.com/31719207/130171389-0e2def4c-0d49-46c1-9b57-a0c9c34ffcd3.png)
语料：近一个月来四川
生成图片：
![图片](https://user-images.githubusercontent.com/31719207/130171406-2ca2f598-12c2-4797-b475-7181386c053f.png)
风格图片：
![图片](https://user-images.githubusercontent.com/31719207/130171422-b3fa6650-23eb-4ee0-aada-d3cf40a8ba41.png)
语料：都阿坝等市州降大暴成
生成图片：
![图片](https://user-images.githubusercontent.com/31719207/130171447-ad033b8b-9336-42b5-97ec-775f81f1ad01.png)
4. 为了解决个别图片存在漏字的情况，我计划语料txt文本中每行就放一个字，然后一张风格图片生成10个图片，最后把10张图片拼接成一个带有10个字符的图片，用于crnn的训练。请问这种方法是否可行。
5. 为了解决漏字问题，我想的另外一种方法是在语料中还是每行放10个字，生成风格迁移后的文字，然后贴在背景图片中（背景图片根据文字长度进行crop和padding），请问这种方式是否可行，或者老师们有其他方法吗。谢谢！

**Comment by weisy11** [comment]
感谢关注，目前styletext确实存在一些问题
1.确实，目前大部分标点并不支持
2.这种数据可能需要过滤一下
3.确实目前长文本有缺字的情况
4.可以生成5个字左右的数据，缺失会少很多
5.恐怕不行，这样的话ground truth标注可能不正确

**Comment by mrlihellohorld** [comment]
你好，不是很理解您解释的第五条，请问可以详细讲一下吗。谢谢。
另外，如果我想尽量生成不缺失的10个字符的图片，有什么好的方法吗
