### ISSUE TITLE
识别与识别推理

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#3758]
识别过程中，同一张图在inference转换前后有一定差异，请问是什么原因？

**Comment by Dandelion111** [comment]
> 识别过程中，同一张图在inference转换前后有一定差异，请问是什么原因？

我也有这个问题，请问大哥解决了吗

**Comment by 18362890185** [comment]
> > 识别过程中，同一张图在inference转换前后有一定差异，请问是什么原因？
> 
> 我也有这个问题，请问大哥解决了吗

还没有那

**Comment by tink2123** [comment]
可能是数据预处理不一致导致的，希望保持一致的话可以在inference预测时，注释掉这两行代码：
https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/predict_rec.py#L89-L90

**Comment by 18362890185** [comment]
> 可能是数据预处理不一致导致的，希望保持一致的话可以在inference预测时，注释掉这两行代码：
> https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/predict_rec.py#L89-L90

好的，我试一试，谢谢

**Comment by 18362890185** [comment]
> 可能是数据预处理不一致导致的，希望保持一致的话可以在inference预测时，注释掉这两行代码：
> https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/predict_rec.py#L89-L90

![1](https://user-images.githubusercontent.com/87969070/130708384-2c9f3fea-4ab0-46f5-b2f9-4e55a8d1a3c2.png)
![2](https://user-images.githubusercontent.com/87969070/130708468-5a0ddfb7-7169-4455-bc29-36c196b55649.png)

你好，我想问一下，关于这个shape[3,32,100]，是按照什么标准进行设置的，我尝试将32换成64运行就发生错误，请问这是什么原因呢？

**Comment by 18362890185** [comment]
> 可能是数据预处理不一致导致的，希望保持一致的话可以在inference预测时，注释掉这两行代码：
> https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/predict_rec.py#L89-L90

![image](https://user-images.githubusercontent.com/87969070/131296563-9f4e1bb9-4faf-4926-a127-fd3d05c1c36d.png)


你好，关于检测得到的区域，右边有一些错误框，请问：我在串联检测模型与识别模型过程中，哪一些参数是将这些错误框自动过滤掉？谢谢啦!

**Comment by zhangyingying520** [comment]
> > 可能是数据预处理不一致导致的，希望保持一致的话可以在inference预测时，注释掉这两行代码：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/predict_rec.py#L89-L90
> 
> ![image](https://user-images.githubusercontent.com/87969070/131296563-9f4e1bb9-4faf-4926-a127-fd3d05c1c36d.png)
> 
> 你好，关于检测得到的区域，右边有一些错误框，请问：我在串联检测模型与识别模型过程中，哪一些参数是将这些错误框自动过滤掉？谢谢啦!

![image](https://user-images.githubusercontent.com/80818728/136915058-a896086d-bb11-42dd-94c3-183126b63dcc.png)
在这个文件下tools/infer/predict_det.py
