### ISSUE TITLE
希望可以出一个基于Paddle Lite 在windows端部署PaddleOCR超轻量中文检测、识别模型的demo

### ISSUE THREAD

**Issue by littleSpongebob** [PaddlePaddle/PaddleOCR#376]
希望可以将该ocr集成进桌面的客户端中

**Comment by tink2123** [comment]
抱歉～Windows暂时还不支持部署 我们会统计您的需求尽力支持，欢迎持续关注

**Comment by littleSpongebob** [comment]
> 抱歉～Windows暂时还不支持部署 我们会统计您的需求尽力支持，欢迎持续关注

大概是哪个部分的原因导致的？我看paddle_lite有教程可以编译出x86的库了。是这个库还有部分paddleocr用到的算子没有实现么

**Comment by tink2123** [comment]
是的～部分算子暂时还不支持，需求收集中，后面会逐步完善。请问您的应用场景是？

**Comment by littleSpongebob** [comment]
> 是的～部分算子暂时还不支持，需求收集中，后面会逐步完善。请问您的应用场景是？

就是一个windows桌面程序想要集成一个离线，轻量的ocr模块

**Comment by AIpioneer** [comment]
方便联系一下吗~ 了解一下您这边的详细需求。另外可以使用paddle inference来调用轻量的ocr模型的，可以考虑使用。 微信同手机I52IO5久八六武吧。

**Comment by dyning** [comment]
看下这个教程是否可用，Visual Studio 2019 Community CMake 编译指南， 
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md
