### ISSUE TITLE
infer时的图像尺寸问题

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#3764]
训练时默认图像crop到960*960，预测时如果把输入图像尺寸放大一些，例如1280*1280，识别准确率是否会提高？

**Comment by tink2123** [comment]
会提升准确率的，但是也会带来更大的耗时，可根据情况自己调整

**Comment by guijuzhejiang** [comment]
谢谢，我测试一下
