### ISSUE TITLE
detec训练自己的数据集出现不明错误

### ISSUE THREAD

**Issue by BothCats** [PaddlePaddle/PaddleOCR#3767]
![QQ图片20210821165810](https://user-images.githubusercontent.com/51903595/130316633-4e3cef1f-1c83-442e-81c4-ffae31b59433.png)
加了个print，在for data in loader():执行的时候报的错，不过也能训练，训练到loss降到1.2就不好下降了，请问什么情况下会报这种错误呢，而且每执行120次就会程序崩溃一次，有可能是评估模型的时候崩溃的，有没有什么方法或者类似的错误？？
![QQ图片20210821165810](https://user-images.githubusercontent.com/51903595/130316700-cbe637f5-5526-4382-858e-6fea251681ed.png)

**Comment by WenmuZhou** [comment]
这个错误，好像是图片格式不对的问题，可以改为Image.open读取图片，这两行换为
```python
img  = Image.open(img).convert('rgb')
img = np.array(img)[:,:,::-1]
```
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/data/imaug/operators.py#L44-L45
