### ISSUE TITLE
infer_dt.py测试结果和cpp_infe推理效果不一样

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#3768]
请问各位大佬，为什么我训练完文本检测模型，用infer_dt.py测试能得到较好的检测效果，把模型转为推理模型之后，用cpp_infe推理却检测不到文本了？

**Comment by WenmuZhou** [comment]
试试调低这个值https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/src/main.cpp#L54
