### ISSUE TITLE
英文文本识别模型不太对

### ISSUE THREAD

**Issue by janetwise** [PaddlePaddle/PaddleOCR#377]
下载了英文识别模型：rec_mv3_none_bilstm_ctc.tar. 按照说明转换模型，识别

python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/word_10.png" --rec_model_dir="./inference/rec_crnn/"

识别结果：
Predicts of ./doc/imgs_words_en//word_10.png:['0更计妇', 0.9998258]

请帮助查看这个模型文件是不是不对。谢谢！试了几个其他的rec_.tar模型，都有这个问题。

**Comment by dyning** [comment]
没有指定英文字典，--rec_image_shape="3, 32, 100" --rec_char_type="en"，请参考 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md 中的基于CTC损失的识别模型推理章节

**Comment by janetwise** [comment]
@dyning 多谢啊，现在对了，那个命令行挺长的没有看到这部分。
