### ISSUE TITLE
版本选择

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleOCR#3770]
请问只训练和识别静态图，选择哪个版本比较好？
v2.2可以训练和预测静态图吗？

**Comment by littletomatodonkey** [comment]
你好，建议用develop分支的代码，v2.2只能用来训练动态图

**Comment by isLiuHao** [comment]
> 你好，建议用develop分支的代码，v2.2只能用来训练动态图

请问develop分支可以使用最新版本的paddle吗
