### ISSUE TITLE
问题: 预训练模型下载地址错误

### ISSUE THREAD

**Issue by cloudy-sfu** [PaddlePaddle/PaddleOCR#3772]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/README_ch.md

1. 这个页面上 "方向分类模型" server 版本的模型, 下载链接错误地指向 mobile 版本的模型文件.

**Comment by WenmuZhou** [comment]
方向分类器mobile版本精度已经足够高了，因此没必要训练server版本
