### ISSUE TITLE
android_demo配置参数，图片resize和前后处理文件？

### ISSUE THREAD

**Issue by yaoruinupt** [PaddlePaddle/PaddleOCR#3775]
您好，我最近在学习此demo（PaddleOCR/deploy/android_demo/），由于找不到相关文档说明，针对细节有如下问题：
1.请问多线程参数（demo默认4线程）在哪里修改？
2.请问图片resize在哪里修改？我们场景的图片是2358*4148的大图片，且含有较为紧密的文字，如果resize太小会导致大量文字无法识别，是否有解决建议？
3.请问哪个文件的哪个函数可以返回识别结果（识别结果+置信率+位置坐标）？
谢谢！

**Comment by WenmuZhou** [comment]
1. 在这里修改，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/deploy/android_demo/app/src/main/res/values/arrays.xml#L15
2. 在这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/Utils.java#L42-L62
3. 结果都在这个[results](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/Predictor.java#L239)里，results是一个list,里面item具体的结构可以参考https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/OcrResultModel.java

**Comment by yaoruinupt** [comment]
感谢回复！
