### ISSUE TITLE
识别出来是这样的？不准哇

### ISSUE THREAD

**Issue by yuanjie-ai** [PaddlePaddle/PaddleOCR#3776]
![image](https://user-images.githubusercontent.com/20265321/130406518-87eeb7d1-a0c4-4801-85bc-615f1751c07e.png)
![image](https://user-images.githubusercontent.com/20265321/130406580-549096c8-82fd-4931-83af-2807d9925ddf.png)

**Comment by MissPenguin** [comment]
哪里不准

**Comment by Jie-Yuan** [comment]
> 哪里不准

表格文字，错位了

**Comment by Jie-Yuan** [comment]
表格错位有啥 好的处理方式？？？
