### ISSUE TITLE
请问训练DBNet的时候，训练集设为224*224,验证集大小应该怎么设置呢

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#3778]
请问训练DBNet的时候，训练集设为224*224,验证集大小应该怎么设置呢？默认的短边resize到736好像不合适

**Comment by MissPenguin** [comment]
根据你的场景选择合适的尺度就行

**Comment by Dandelion111** [comment]
> 根据你的场景选择合适的尺度就行

我的图像大概是100*300的样子，应该和我的图像大小差不多吗？

**Comment by MissPenguin** [comment]
> > 根据你的场景选择合适的尺度就行
> 
> 我的图像大概是100*300的样子，应该和我的图像大小差不多吗？

嗯，可以的，比如可以也试试224，用于训练时评估来选best model应该没什么问题，选出best model之后，可以再试试不同尺度的单独评估，来选择最佳的预测尺度
