### ISSUE TITLE
各位大佬有空整合成一个Flutter插件吗,只要英文ocr识别功能

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#378]

**Comment by grasswolfs** [comment]
目前没有官方的，之前有第三方开发者基于Paddle-Lite做过一个Flutter的教程，不过不是OCR方向的，可以参考着看看看能不能搞定。
https://zhuanlan.zhihu.com/p/114926049?from_voters_page=true
