### ISSUE TITLE
segmentation fault for ubuntu

### ISSUE THREAD

**Issue by xiaolinyezi** [PaddlePaddle/PaddleOCR#3781]
cuda 10.2 
paddlepaddle-gpu==2.1.2

C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629712940 (unix time) try "date -d @1629712940" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 63194 (TID 0x7f546f6cf240) from PID 0 ***]

段错误 (核心已转储)

**Comment by xiaolinyezi** [comment]
I have find the error root cause, thanks a lot...

**Comment by IDAwaken** [comment]
兄弟你是怎么解决的，我也遇到同样问题

**Comment by XinchengYuYi** [comment]
考虑cuda版本

**Comment by binwang672012** [comment]
> I have find the error root cause, thanks a lot...

怎么解决的？什么问题？
