### ISSUE TITLE
用网页Demo可以正确识别，但是使用预训练的中文server模型就无法检测到文本。

### ISSUE THREAD

**Issue by Nightaway** [PaddlePaddle/PaddleOCR#3782]
![2](https://user-images.githubusercontent.com/1297050/130434265-45b5ca27-e1cb-4eca-a8ac-87b98926c1be.png)

**Comment by MissPenguin** [comment]
网页demo后台是1.1静态图版mobile模型，模型不一致，在部分case上效果会有diff。可以批量数据评估下，根据指标选择合适自己场景的模型。
