### ISSUE TITLE
“车牌识别”中多语言算法的选择问题

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleOCR#3783]
我国车牌字符涉及中文、英文和数字，那么我在选择多语言算法时应当选择哪一种更好？
![image](https://user-images.githubusercontent.com/48787805/130437912-0df8538c-24f9-4e49-a57e-de077b3bac5b.png)

目前我选择的是mv3_none_bilstm_ctc，并且配置如下：
```
# 包含国内车牌字符的字典：省份简称、大写英文字母、数字
character_dict_path: /home/aistudio/work/ppocr/utils/dict/plate_dict.txt
character_type: en
```

数据集是CCPD制作的SimpleDataSet

**Comment by MissPenguin** [comment]
需要识别中文、英文和数字，选择主推的ppocr中文模型即可。你贴出来的是配置文件，对应不同语种的识别（主要是小语种），算法是一样的。

**Comment by thgpddl** [comment]
> 需要识别中文、英文和数字，选择主推的ppocr中文模型即可。你贴出来的是配置文件，对应不同语种的识别（主要是小语种），算法是一样的。

好的，谢谢你，我使用主推的轻量级PPOCR模型训练，目前精度已经接近80%，还在继续训练中。
