### ISSUE TITLE
按照官网的提示部署出错在运行python tools/test_hubserving.py http://127.0.0.1:8866/predict/ocr_system ./doc/imgs/之后

### ISSUE THREAD

**Issue by xiaoyong001** [PaddlePaddle/PaddleOCR#3789]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8866): Max retries exceeded with url: /predict/ocr_system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efeff8a1850>: Failed to establish a new connection: [Errno 111] Connection refused'))这种错误是什么yuan原因呢，该怎么解决
> 
![image](https://user-images.githubusercontent.com/49474119/130545594-b6e42974-cef7-4fa7-9626-c72fe55c417d.png)

**Comment by LDOUBLEV** [comment]
127.0.0.1 换成你的机器IP试试
