### ISSUE TITLE
识别模型推理报错

### ISSUE THREAD

**Issue by Nightaway** [PaddlePaddle/PaddleOCR#379]
python3 tools/infer_rec.py -c configs/rec/rec_chinese_lite_train.yml -o Global.checkpoints=pretrained/ch_rec_mv3_crnn/best_accuracy TestReader.infer_img=doc/imgs_words/en/word_1.jpg
Traceback (most recent call last):
  File "tools/infer_rec.py", line 140, in <module>
    main()
  File "tools/infer_rec.py", line 53, in main
    program.merge_config(FLAGS.opt)
  File "tools/../tools/program.py", line 126, in merge_config
    assert (sub_key in cur)
AssertionError

**Comment by littletomatodonkey** [comment]
如果需要预测单张图片，需要指定`Global.infer_img`，不是`TestReader.infer_img`哈
```
python3 tools/infer_rec.py \
    -c configs/rec/rec_chinese_lite_train.yml  \
    -o Global.checkpoints=pretrain_models/rec_mv3_crnn/best_accuracy  \
    Global.infer_img=doc/imgs_words/en/word_1.png
```

**Comment by Nightaway** [comment]
Fix it, Thanks.
