### ISSUE TITLE
识别模型处理中文时的问题

### ISSUE THREAD

**Issue by ioracion** [PaddlePaddle/PaddleOCR#3790]
尝鲜装了最新的版本，发现训练模型和预测模型差异很大，找了半天问题发现又是[这个问题](https://github.com/PaddlePaddle/PaddleOCR/issues/214#issuecomment-645346661)（其实是忘了自己踩过的坑，以为修复了）

因此就想问问能不能把predict_rec和infer_rec文件里的代码同步下？（指处理当rec_char_type= "ch" 的情况下）看到论坛里不少人都有这个问题了，而且是**从去年到现在**。都过去这么久了真的想吐槽吐槽

**Comment by thgpddl** [comment]
多谢楼主，已解决，就是下方的问题，现在还是没有修正
```
# if self.character_type == "ch":
#     imgW = int((32 * max_wh_ratio))
```
