### ISSUE TITLE
PGNet 评估时 索引超出范围

### ISSUE THREAD

**Issue by lllbq** [PaddlePaddle/PaddleOCR#3792]
![QQ图片20210824104629](https://user-images.githubusercontent.com/44738266/130547726-1f0db4c9-4b07-451f-bded-d2b088840d5f.png)

预设为0~9，而dst_str出现了超过9的数字

**Comment by LDOUBLEV** [comment]
训练的时候是否对应修改了字典文件，https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/configs/e2e/e2e_r50_vd_pg.yml#L18

检查下你识别输出 char 的维度是不是和你的字典字符数量一致https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/losses/e2e_pg_loss.py#L123

**Comment by lllbq** [comment]
> 训练的时候是否对应修改了字典文件，
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/configs/e2e/e2e_r50_vd_pg.yml#L18
> 
> 检查下你识别输出 char 的维度是不是和你的字典字符数量一致
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/losses/e2e_pg_loss.py#L123

char维度为 [4, 37, 128, 128]，与自定义字典的长度不同，自定义字典是十个数字，除了要修改字典和e2e_r50_vd_pg.yml以外，还需要修改哪里？

**Comment by lllbq** [comment]
> 如果字典是10个数字，可以应该是[4, 11, 128, 128]维度
请问应该在哪修改这个数值？

**Comment by lllbq** [comment]
> 如果字典是10个数字，可以应该是[4, 11, 128, 128]维度

请问应该在哪修改这个数值？
