### ISSUE TITLE
Why I have this error when using PaddleOCR to process an image from web API?

### ISSUE THREAD

**Issue by jordane95** [PaddlePaddle/PaddleOCR#3796]
I am using PIL.Image.open(io.BytesIO(image_bytes)) to get the image from web API. But the PaddleOCR yields the following error
> InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 4, the input's shape is [1, 4, 640, 960]; the filter's channels is 3, the filter's shape is [8, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.

      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:4 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)

      [operator < conv2d > error]

But it is ok when I use cv.imread(img_path) to directly read it locally from disk. Does anyone know why ???

**Comment by LDOUBLEV** [comment]
The error indicates that your input image has four channels, but the expected RGB image with three channels.

**Comment by jordane95** [comment]
> The error indicates that your input image has four channels, but the expected RGB image with three channels.

Thank you! I dropped the 4th channel and it works well.
