### ISSUE TITLE
识别模型推理

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#3797]
图像识别过程中inference转换前后，识别效果不一致。关于注释self.character_type=="ch"并没有起到作用，请问还需要修改其他参数能将其转换为一致吗？

**Comment by LDOUBLEV** [comment]
> 识别效果不一致？ 

是差多少，给个例子看看
- 如果训练更换了字典，在预测的时候也要更新为你的字典文件
- 检查预处理是否采用的是一样的预处理

**Comment by 18362890185** [comment]
![1](https://user-images.githubusercontent.com/87969070/130716610-364cb8f3-0fb2-4eb5-baf0-314090892074.png)

嗯嗯，目前已经找到原因了。现在还有一个点是关于shape的设置，我的图像是74*68的图像，我将shape中32换成64出现报错的现象，请问这个计算方式遵循什么规则，我这个尺寸应该设置多少比较合适？

**Comment by LDOUBLEV** [comment]
32 是固定的，不要贸然修改，但是长度100是可以修改的，


> 我的图像是74*68的图像，

你要识别的是单字符吗？

**Comment by 18362890185** [comment]
> 32 是固定的，不要贸然修改，但是长度100是可以修改的，
> 
> > 我的图像是74*68的图像，
> 
> 你要识别的是单字符吗？



好的，谢谢解答，也不完全是单字符 字符主要是1-32.

**Comment by 18362890185** [comment]
> 32 是固定的，不要贸然修改，但是长度100是可以修改的，
> 
> > 我的图像是74*68的图像，
> 
> 你要识别的是单字符吗？

![1](https://user-images.githubusercontent.com/87969070/130731161-de9ae125-f476-49e7-aa22-03c59d69b50f.png)
你好，请问，我用EAST检测模型时，输出的图像框都是这种左边宽 右边窄的现象，请问这跟哪一个参数有关系？
