### ISSUE TITLE
自训练的DB模型（mobile版)，什么都检测不出来（检测一张训练用的图片）

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleOCR#3800]
自训练的DB模型（mobile版)，什么都检测不出来（检测一张训练用的图片），训练过程中的eval显示如下：

- [2021/08/24 16:04:52] root INFO: cur metric, precision: 0.22115384615384615, recall: 0.49503311258278143, hmean: 0.3057259713701431, fps: 37.75302028824835
- [2021/08/24 16:04:52] root INFO: best metric, hmean: 0.8846761453396524, precision: 0.8459214501510574, recall: 0.9271523178807947, fps: 37.30944696036153, best_epoch: 1
- [2021/08/24 16:04:53] root INFO: epoch: [2/10000], iter: 15202, lr: 0.000611, loss: 0.392021, loss_shrink_maps: 0.192247, loss_threshold_maps: 0.151013, loss_binary_maps: 0.038385, reader_cost: 0.00378 s, batch_cost: 0.14088 s, samples: 16, ips: 56.78539
- [2021/08/24 16:04:53] root INFO: epoch: [2/10000], iter: 15204, lr: 0.000611, loss: 0.401438, loss_shrink_maps: 0.199626, loss_threshold_maps: 0.151013, loss_binary_maps: 0.039874, reader_cost: 0.00327 s, batch_cost: 0.17112 s, samples: 16, ips: 46.75097

paddle版本：paddlepaddle-gpu   2.1.2
paddleOCR版本：release 2.2

**Comment by LDOUBLEV** [comment]
你这才训练2epoch，评估指标hmean才30，属于很低的精度了，训练时间久一点看看

**Comment by chenxuezhao** [comment]
这只在之前已经训练过的模型基础上训练的，之前的模型已经训练了14个epoch（10万张图片）。现在训练2个epoch之后，在训练就会过拟合。

**Comment by chenxuezhao** [comment]
另外，数据标定的时候，对于一张倾斜的图片，我应该怎么标定？
![1](https://user-images.githubusercontent.com/42796059/130715860-df0ef646-e913-4bcc-9058-ef5600ba91cd.jpg)
还是
![2](https://user-images.githubusercontent.com/42796059/130715903-fe828db1-5ddf-444b-9728-adb0585ad1a3.jpg)

**Comment by LDOUBLEV** [comment]
采用图二的标定方式

你可视化分析下badcase，看上去loss很低了，但是精度差了很多；
可以在抽一部分训练集上评估看下是不是过拟合了

**Comment by chenxuezhao** [comment]
谢谢回复。
我从官网下载的预训练的DB模型，训练的时候用的下面的命令：
python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0'  tools/train.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.checkpoints=./pretrain_models/ch_ppocr_mobile_v2.0_det_train
可以吗？
pretrain_models/ch_ppocr_mobile_v2.0_det_train目录下的内容如下图所示：
![image](https://user-images.githubusercontent.com/42796059/130722843-311031d9-c6c5-43e3-9bf0-5a96abefde03.png)

**Comment by LDOUBLEV** [comment]
训练方式没问题

**Comment by chenxuezhao** [comment]
3个epoch之后，感觉已经过拟合了。
![image](https://user-images.githubusercontent.com/42796059/130763838-b17ab429-a6a9-4542-b413-0fe61c8a762d.png)
训练的模型转为inference推理模型后，用命令：
- python3 tools/infer/predict_det.py --image_dir="./test.jpg" --det_model_dir="./inference/det”
检测一张图片，结果什么都没有检测到。
直接用训练的模型，去检测图片：
- python3 tools/infer_det.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.infer_img=test.jpg  Global.checkpoints="./output/ch_db_mv3/best_accuracy"  PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5
可以检测到文本，但效果没有从官网下载的infer模型好。
自训练模型检测结果：
![20210715132742_1](https://user-images.githubusercontent.com/42796059/130764953-c22f7429-17cf-4e8b-80a0-4a2398203edc.jpg)
官网下载的infer模型检测结果：
![det_res_20210715082347_1](https://user-images.githubusercontent.com/42796059/130765135-cf82a34a-593a-40e4-904f-2d87788005b3.jpg)

**Comment by LDOUBLEV** [comment]
> 训练的模型转为inference推理模型后，用命令： python3 tools/infer/predict_det.py --image_dir="./test.jpg" --det_model_dir="./inference/det”  检测一张图片，结果什么都没有检测到。

检查下推理模型的时候权重有没有加载进去，另外，测试的时候，infer_det.py的数据预处理：https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L118
https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/data/imaug/operators.py#L128
和predict_det.py的预处理参数不一样，可以用一样的预处理试下：
https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/infer/predict_det.py#L43

**Comment by LeoRainly** [comment]
2.6也遇到了同样的问题，该怎么解决啊
