### ISSUE TITLE
模型评估

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3802]
训练中best是通过评估得出的，评估用的是测试集，我这么理解对吗，因为我最近跑的几次实验发现最后几个epoch显示的acc都已经接近100%，但最终得出的best acc才0.5，是不是每个epoch显示的acc是在自己训练集中的验证集得出的结果，best的acc是通过eval测试集得出的结果？？

**Comment by LDOUBLEV** [comment]
> 是不是每个epoch显示的acc是在自己训练集中的验证集得出的结果，best的acc是通过eval测试集得出的结果？？

是这样的

**Comment by hice1207** [comment]
> > 是不是每个epoch显示的acc是在自己训练集中的验证集得出的结果，best的acc是通过eval测试集得出的结果？？
> 
> 是这样的

 十分感谢
