### ISSUE TITLE
利用tenorrt 推演时出错

### ISSUE THREAD

**Issue by hanguangmic** [PaddlePaddle/PaddleOCR#3803]
利用tensorrt创建predicator的时候，出现如下错误
，说我的weights 参数量不匹配， 我用netron 查看生成的网络图，并没有发现这个 conv2d (Output: batch_norm_201.tmp_33248) 节点。请问一下大神们有解么？ 卡了好几天了。

####################################################################
I0824 13:38:08.504269   934 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E0824 13:38:17.569257   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.569310   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.569396   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.569401   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.569406   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.569409   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.569496   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.569502   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.569998   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.570011   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.570014   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.570020   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.570503   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.570513   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.570518   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.570523   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571022   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571031   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571036   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571039   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571528   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571538   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571543   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571548   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
I0824 13:38:17.571812   934 engine.cc:202] Run Paddle-TRT Dynamic Shape mode.
E0824 13:38:17.571889   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571897   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571900   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): kernel weights has count 23328 but 11664 was expected
E0824 13:38:17.571904   934 helper.h:84] conv2d (Output: batch_norm_201.tmp_33248): count of 23328 weights in kernel, but kernel dimensions (3,3) with 18 input channels, 72 output channels and 1 groups were specified. Expected Weights count is 18 * 3*3 * 72 / 1 = 11664
E0824 13:38:17.571913   934 helper.h:84] Layer conv2d (Output: batch_norm_201.tmp_33248) failed validation
E0824 13:38:17.571924   934 helper.h:84] Network validation failed.

**Comment by LDOUBLEV** [comment]
加大min_subgraph_size试下 https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38

**Comment by hanguangmic** [comment]
> 加大min_subgraph_size试下
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38

试过了 大佬弄成了15

**Comment by LDOUBLEV** [comment]
> > 加大min_subgraph_size试下
> > https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38
> 
> 试过了 大佬弄成了15

试试20 或者更大

你用的是哪个网络？

**Comment by hanguangmic** [comment]
> > > 加大min_subgraph_size试下
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38
> > 
> > 
> > 试过了 大佬弄成了15
> 
> 试试20 或者更大
> 
> 你用的是哪个网络？
我用的db net, backbone是hrnet

**Comment by hanguangmic** [comment]
> > > 加大min_subgraph_size试下
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38
> > 
> > 
> > 试过了 大佬弄成了15
> 
> 试试20 或者更大
> 
> 你用的是哪个网络？

刚刚试了一下  100 都不行

**Comment by hanguangmic** [comment]
> > > 加大min_subgraph_size试下
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/ebd266656b344b16e38a3299e3e77014aba337de/tools/infer/utility.py#L38
> > 
> > 
> > 试过了 大佬弄成了15
> 
> 试试20 或者更大
> 
> 你用的是哪个网络？

大佬 我用了300 成了 但是感觉tensorrt inference 和 paddle inference 区别不是很大
