### ISSUE TITLE
使用icdar2015数据集训练识别模型的时候loss很大并且准确率很低

### ISSUE THREAD

**Issue by infinite013** [PaddlePaddle/PaddleOCR#381]
![QQ图片20200719161501](https://user-images.githubusercontent.com/37789662/87870490-1c6abf00-c9db-11ea-8882-f3304cd3b047.png)

**Comment by tink2123** [comment]
使用ic15数据集训练时，建议加载预训练模型。icdar2015 数据量较小，主要作为demo跑通并熟悉代码。从头训练建议使用lmdb数据。

**Comment by infinite013** [comment]
> 使用ic15数据集训练时，建议加载预训练模型。icdar2015 数据量较小，主要作为demo跑通并熟悉代码。从头训练建议使用lmdb数据。

感谢说明
还有一点问题如下：
1、默认训练icdar数据是的batchsize_per_card为256，但是如果我以256的batchsize训练我自己的数据集(很小大概500张图片)的时候，会出现在训练过程中不显示loss以及acc的情况。如下图所示，只显示模型保存的信息，发现训练几十个epoch后模型未学到东西：
![微信图片_20200719200903](https://user-images.githubusercontent.com/37789662/87874428-4680a900-c9fc-11ea-81b0-218f84a0c804.png)




当我将batchsize改小改为8之后再进行训练，就不会出现不显示loss以及acc的情况。如下图所示，并且我训练了几百个epoch后发现对模型的训练是有效的：
![微信图片_20200719201126](https://user-images.githubusercontent.com/37789662/87874422-41bbf500-c9fc-11ea-8918-0f1576734dc4.png)

**Comment by tink2123** [comment]
> 很小大概500张图片)的时候，会出现在训练过程中不显示loss以及acc的情况

您应该是使用了多卡训练吧，bs=256 * 卡数 > 500（全部数据量）会导致一次训练时数据总量小于设置的训练数据量，读取数据时报错，因此没有进行训练。
