### ISSUE TITLE
请问一下，可以冻结某些层，比如固定backbone网络层，只训练后面的网络层吗

### ISSUE THREAD

**Issue by weekstudy** [PaddlePaddle/PaddleOCR#3811]

**Comment by tink2123** [comment]
可以的，找到想固定的那层，输出变量设置stop_gradient=True 即可，例如：

```
x = resnet(xxxx)
x.stop_gradient=True
```

**Comment by two-bee-or-not-two-bee** [comment]
> 可以的，找到想固定的那层，输出变量设置stop_gradient=True 即可，例如：
> 
> ```
> x = resnet(xxxx)
> x.stop_gradient=True
> ```
![QQ图片20210831220501](https://user-images.githubusercontent.com/75458893/131516993-deb7390c-2928-4903-aa9c-6c8a343c95ab.png)

请问我在backbone输出后面加了这句指令，但是报错，输出是list 没有stop_gradient，

报错：File "/home/aistudio/work/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
    x.stop_gradient = True
AttributeError: 'list' object has no attribute 'stop_gradient'

**Comment by weekstudy** [comment]
> > 可以的，找到想固定的那层，输出变量设置stop_gradient=True 即可，例如：
> > ```
> > x = resnet(xxxx)
> > x.stop_gradient=True
> > ```
> 
> ![QQ图片20210831220501](https://user-images.githubusercontent.com/75458893/131516993-deb7390c-2928-4903-aa9c-6c8a343c95ab.png)
> 
> 请问我在backbone输出后面加了这句指令，但是报错，输出是list 没有stop_gradient，
> 
> 报错：File "/home/aistudio/work/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
> x.stop_gradient = True
> AttributeError: 'list' object has no attribute 'stop_gradient'

他这里的x是个列表，需要遍历设置，比如
for xx in x:
     xx.stop_gradient = True
但是感觉冻结起来没有用，训练不起来

**Comment by two-bee-or-not-two-bee** [comment]
> > > 可以的，找到想固定的那层，输出变量设置stop_gradient=True 即可，例如：
> > > ```
> > > x = resnet(xxxx)
> > > x.stop_gradient=True
> > > ```
> > 
> > 
> > ![QQ图片20210831220501](https://user-images.githubusercontent.com/75458893/131516993-deb7390c-2928-4903-aa9c-6c8a343c95ab.png)
> > 请问我在backbone输出后面加了这句指令，但是报错，输出是list 没有stop_gradient，
> > 报错：File "/home/aistudio/work/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
> > x.stop_gradient = True
> > AttributeError: 'list' object has no attribute 'stop_gradient'
> 
> 他这里的x是个列表，需要遍历设置，比如
> for xx in x:
> xx.stop_gradient = True
> 但是感觉冻结起来没有用，训练不起来
   

 pgnet原始是字典是37类，然后想分大小写，字典是63类。但是一直不收敛，就想着冻结backbone，确实好像没啥区别
