### ISSUE TITLE
关于ocr中字典的编码与解码问题

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#3812]
我在调试的时候为了应对少数民族语言文字，不了解lable_ops.py与simple_dataset.py这两个里面都有编码与解码，他们有什么关系，而且程序好像都用到了，我在修改yml中dataset下的CTCLabelEncode改成BaseRecLabelEncode，直接报错---不期望有这个参数（use-gpu，debug等），假如我直接用CTCLabelEncode，说我超出数组，很奇怪的

**Comment by tink2123** [comment]
simple_dataset.py 里没有编解码的，用到编解码的地方是后处理和前处理。
请问你是怎么修改的代码？如果只是为了适配其他语种，在配置文件里修改字典路径就可以。
