### ISSUE TITLE
预测报错ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by Jack-wx** [PaddlePaddle/PaddleOCR#382]
请问又遇到过这报错么，怎么解决呢，重装这个scikit-image并没效果呢。。
`Traceback (most recent call last):
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/skimage/__init__.py", line 119, in <module>
    from ._shared import geometry
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 24, in <module>
    import tools.infer.predict_det as predict_det
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/tools/infer/predict_det.py", line 26, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/ppocr/data/det/db_process.py", line 23, in <module>
    from .data_augment import AugmentData
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/ppocr/data/det/data_augment.py", line 13, in <module>
    import imgaug
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/imgaug/__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/skimage/__init__.py", line 122, in <module>
    _raise_build_error(e)
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/skimage/__init__.py", line 102, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
`

**Comment by dyning** [comment]
是在docker里面运行吗？

**Comment by Jack-wx** [comment]
> 是在docker里面运行吗？

不是的，直接在linux里面运行的。

**Comment by Jack-wx** [comment]
> > 是在docker里面运行吗？
> 
> 不是的，直接在linux里面运行的。

而且我直接在linux里面运行python,然后import skimage.draw是不会报错的。。就有点迷啦

**Comment by LDOUBLEV** [comment]
> > > 是在docker里面运行吗？
> > 
> > 
> > 不是的，直接在linux里面运行的。
> 
> 而且我直接在linux里面运行python,然后import skimage.draw是不会报错的。。就有点迷啦

看报错是：
![image](https://user-images.githubusercontent.com/26592129/87897276-6b693080-ca7d-11ea-9e50-29a7619fe4b9.png)
检查下是不是scikit-image库装的有问题吧，建议重新装一个

**Comment by LDOUBLEV** [comment]
> > > 是在docker里面运行吗？
> > 
> > 
> > 不是的，直接在linux里面运行的。
> 
> 而且我直接在linux里面运行python,然后import skimage.draw是不会报错的。。就有点迷啦

可以确认下，linux直接运行的python和你运行代码的python是不是同一个版本？

**Comment by Jack-wx** [comment]
> > > > 是在docker里面运行吗？
> > > 
> > > 
> > > 不是的，直接在linux里面运行的。
> > 
> > 
> > 而且我直接在linux里面运行python，然后导入skimage.draw是不会报错的。。就有点迷啦
> 
> 可以确认下，linux直接运行的python和你运行代码的python是不是同一个版本？
[root@kaifa01 PaddleOCR-develop]# which python3
/usr/bin/python3
[root@kaifa01 PaddleOCR-develop]# python3 --version
Python 3.6.8
[root@kaifa01 PaddleOCR-develop]# python3 -m pip --version
pip 20.1.1 from /usr/local/python3.6.8/lib/python3.6/site-packages/pip (python 3.6)
[root@kaifa01 PaddleOCR-develop]# python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
x86_64
[root@kaifa01 PaddleOCR-develop]# python
Python 3.6.8 (default, Jul 17 2020, 17:57:44) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ... 
Your Paddle works well on SINGLE GPU or CPU.
I0720 11:44:43.123045  2748 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0720 11:44:43.124445  2748 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
I0720 11:44:43.124569  2748 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0720 11:44:43.125531  2748 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0720 11:44:43.126293  2748 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Your Paddle works well on MUTIPLE GPU or CPU.
Your Paddle is installed successfully! Let's start deep Learning with Paddle now

**Comment by Jack-wx** [comment]
> 查下是不是scikit-image库装的有问题吧，建议重新装一个

我试过，而且也安装过低版本的scikit-image去试试的，我确认这个是安装成功了的。而且我也能执行python后正常import进来。

**Comment by Jack-wx** [comment]
已解决，关闭

**Comment by double-vane** [comment]
@Jack-wx 请问，是怎么解决的？谢谢

**Comment by JiaoZiLang** [comment]
@Jack-wx 请问下是怎么解决的？我这边也复现这个问题，感觉很谜～

**Comment by Jack-wx** [comment]
你可以试试这个，我将版本改成这个就好啦。pip3 install scikit-image==0.17.1

发送自 Windows 10 版邮件应用

发件人: JiaoZiLang
发送时间: 2020年10月23日 16:34
收件人: PaddlePaddle/PaddleOCR
抄送: Jack-wx; Mention
主题: Re: [PaddlePaddle/PaddleOCR] 预测报错ImportError: dlopen: cannot load any more object with static TLS (#382)

@Jack-wx 请问下是怎么解决的？我这边也复现这个问题，感觉很谜～

**Comment by Jack-wx** [comment]
> @杰克-WX请问下是怎么解决的？我这边也复现这个问题，感觉很谜〜
你可以试试这个，我将版本改成这个就好啦。pip3 install scikit-image==0.17.1

**Comment by Jack-wx** [comment]
@JiaoZiLang @double-vane 你可以试试这个，我将版本改成这个就好啦。pip3 install scikit-image==0.17.1

**Comment by linkxzhou** [comment]
@Jack-wx 我安装了还是报错

**Comment by ChChwang** [comment]
在docker里运行，改成pip3 install scikit-image==0.17.1 也不行。怎么解决？

**Comment by linyupark** [comment]
docker 里面执行 pip3.7 install -r requirements.txt

**Comment by GiggleLy** [comment]
我也遇到了各个方法都试过了，绝望。求解答

**Comment by ketusrai** [comment]
最终解决方案：ImportError: dlopen: cannot load any more object with static TLS

使用命令: ll /usr/lib64/libc.so.6. 查看的软连接，如果是 /usr/lib64/libc.so.6 -> libc-2.18.so 那就会出现这种问题，具体看csdn里有说明，但是没理解。 你只要把软连接修改  /usr/lib64/libc.so.6 -> libc-2.17.so 上就没有问题了。

**Comment by Hurray0** [comment]
> 最终解决方案：ImportError: dlopen: cannot load any more object with static TLS
> 
> 使用命令: ll /usr/lib64/libc.so.6. 查看的软连接，如果是 /usr/lib64/libc.so.6 -> libc-2.18.so 那就会出现这种问题，具体看csdn里有说明，但是没理解。 你只要把软连接修改 /usr/lib64/libc.so.6 -> libc-2.17.so 上就没有问题了。

你这命令差点把我系统整崩溃😂
