### ISSUE TITLE
PPOCR的c++部署

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleOCR#3823]
我训练的python版本的PPOCR识别算法效果很好，将python版本训练好的识别模型转为inference模型，在进行C++推理时，发现c++下的PPOCR的识别，在一个文本框中总是漏识别。请问，可能是那里的原因？

**Comment by one-matrix** [comment]
> Scanning dependencies of target ocr_system
> make[2]: *** 没有规则可制作目标“/home/Cpp/paddle_inference/paddle/lib/libpaddle_fluid.so”，由“ocr_system” 需求。 停止。
> make[2]: *** 正在等待未完成的任务....
> [ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
> [ 20%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
> [ 30%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_cls.o
> [ 40%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
> [ 50%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
> [ 60%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
> [ 70%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
> [ 80%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
> [ 90%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
> make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> inference:
> manylinux_cpu_avx_openblas_gcc82（2.0.1）
> 
> opencv:
> 3.4.7.tar.gz
> 
> paddleocr:
> release/2.0
> 
> 求请教楼主遇到过类似的问题吗？该如何解决？无论三cpu还是gpu环境下，c++的inference部署总是不成功

一样的错误，有找到解决方法吗
