### ISSUE TITLE
关于PGNet训练相关问题

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#3828]
请教一下大佬，阅读完PGNet的说明文档。
1. 发现官方提供的total_text数据集只有图片信息，没看到有标注信息。
2. 在issues里面找PGNet相关的问题，提及到训练中文文本需要修改两个地方，配置文件跟PGNet相关代码，官方能否给个比较系统的说明。
3. 对于PGNet，需要多少个数据能够得到比较好的结果呢。

还请路过的大佬指教指教。

**Comment by superaidou123** [comment]
您好，请问自己实际场景中标注的弧形文字坐标点个数不等于14，官方有提供转换脚本吗？或者说，代码能支持任意点的训练（类似于PSEnet，弯曲文本检测时支持任意点标注）吗？

**Comment by superaidou123** [comment]
您好，请问自己实际场景中标注的弧形文字坐标点个数不等于14，官方有提供转换脚本吗？或者说，代码能支持任意点的训练（类似于PSEnet，弯曲文本检测时支持任意点标注）吗？

**Comment by guochengzhen** [comment]
您好，请问自己实际场景中标注的弧形文字坐标点个数不等于14，官方有提供转换脚本吗？或者说，代码能支持任意点的训练（类似于PSEnet，弯曲文本检测时支持任意点标注）吗？

**Comment by LDOUBLEV** [comment]
> 您好，请问自己实际场景中标注的弧形文字坐标点个数不等于14，官方有提供转换脚本吗？或者说，代码能支持任意点的训练（类似于PSEnet，弯曲文本检测时支持任意点标注）吗？

目前没有提供转换脚本，代码里支持任意点训练，前提是点数是统一的，比如统一用4点、14点等等

**Comment by guochengzhen** [comment]
这这这。还是等于要固定点训练。那请问训练过程中，不同标注的点数不同的话，对识别模块有什么影响吗？如果不影响，按道理应该能改代码去适应任意点训练吧。
PSE修改后：
![image](https://user-images.githubusercontent.com/24316588/131475053-3ee4fa86-dd06-408e-8e80-114970eb8b79.png)
PSE修改前：
![image](https://user-images.githubusercontent.com/24316588/131475094-8d544526-0185-43c0-b2aa-0ba8cf5800ce.png)
