### ISSUE TITLE
清晰度尚可，多个区域整段无法识别，请教下可能是什么原因？

### ISSUE THREAD

**Issue by NimbleDev** [PaddlePaddle/PaddleOCR#3837]
待识别图片：
![image](https://user-images.githubusercontent.com/51120096/131129925-3f1457e9-e01e-4104-96af-c2c009bd952e.png)

识别结果（红框为未识别出区域）：
![image](https://user-images.githubusercontent.com/51120096/131130086-ecd34fcd-8955-498b-ac8c-e901ee0aa1ed.png)

**Comment by littletomatodonkey** [comment]
你好，可以尝试一下server模型，我这边看着效果还不错

![image](https://user-images.githubusercontent.com/14270174/131206461-7e6fedc9-512c-428f-8a90-85892f71a217.png)
