### ISSUE TITLE
ISSUE WHILE TRAINING MODELS WITH LMDB DATASET CONFIG

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3838]
I am getting the following error while running the rec_r50_fpn_srn.yml file. Please solve the issue.

Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 52, in main
    train_dataloader = build_dataloader(config, 'Train', device, logger)
  File "/content/PaddleOCR/ppocr/data/__init__.py", line 66, in build_dataloader
    dataset = eval(module_name)(config, mode, logger, seed)
  File "/content/PaddleOCR/ppocr/data/lmdb_dataset.py", line 34, in __init__
    self.lmdb_sets = self.load_hierarchical_lmdb_dataset(data_dir)
  File "/content/PaddleOCR/ppocr/data/lmdb_dataset.py", line 52, in load_hierarchical_lmdb_dataset
    meminit=False)
lmdb.Error: /content/PaddleOCR/train_data/training/train/.ipynb_checkpoints: No such file or directory
INFO 2021-08-27 14:19:39,992 launch_utils.py:307] terminate all the procs
ERROR 2021-08-27 14:19:39,993 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-27 14:19:42,996 launch_utils.py:307] terminate all the procs

**Comment by littletomatodonkey** [comment]
hi, it seems that lmdb file you make is wrong, maybe you should remove `.ipynb_checkpoints` from the anno file, since that causes the exception.

**Comment by karndeepsingh** [comment]
@littletomatodonkey  Thankyou so much. I got it working.
 I have one more query please help me with. How I can augment the data using rec_r50_fpn_srn.yml file and also How can I can fine tune it on my Handwritten dataset? I have prepared the dataset but want to augment and finetune it. 

Please help me with this. Thanks.

**Comment by littletomatodonkey** [comment]
Hi you can use the config file to finetune your dataset. 
1. You should use your own dataset.
2. You should load the pretrained weights we provided and modify the `pretrained_model`.

https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/configs/rec/rec_r50_fpn_srn.yml#L11

**Comment by karndeepsingh** [comment]
Hi,
Sure I am using my dataset. But how should I do Data Augmentation while training ?
