### ISSUE TITLE
有没有尝试过对抗训练

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#3841]
请问有没有测试过对抗训练的效果，如果加入对抗训练在哪里加入好？

**Comment by LDOUBLEV** [comment]
为什么有这个想法，对抗训练一般用在GAN的网络里
OCR任务里有很直接的label，比如box或者文字，没必要用对抗训练

**Comment by guijuzhejiang** [comment]
对抗训练不是对抗网络GAN。对抗训练是加入对抗样本，提高模型在扰动下的稳健性。可以让模型更收敛，更鲁棒，提升准确率

**Comment by LDOUBLEV** [comment]
没试过，可以尝试下
