### ISSUE TITLE
实时 OCR 检测帮助

### ISSUE THREAD

**Issue by raghavzns** [PaddlePaddle/PaddleOCR#3842]
你好,
,

paddleOCR 是否支持这样的功能（textRecognizer）来进行实时检测？

`            cameraSource = new CameraSource.Builder(getApplicationContext(), predictor)` 

或者

`                public void receiveDetections(Detector.Detections<TextBlock> detections) `

请帮帮我
 @MissPenguin @ZeyuChen  @WenmuZhou @tink2123

**Comment by raghavzns** [comment]
请帮忙。我想在现场安卓相机上运行这个
@MissPenguin @ZeyuChen @WenmuZhou @LDOUBLEV @karlhorky

**Comment by LDOUBLEV** [comment]
代码里给的demo无法运行吗？
或者是运行遇到了什么问题？

**Comment by raghavzns** [comment]
>  或者是运行遇到了什么问题？

android 演示代码工作正常。
但我希望 OCR 在实时摄像头上工作，就像 https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/mask_detection_demo

掩码检测演示在实时摄像机上运行。我希望 OCR 也能在实时摄像机上运行。你能帮忙吗
