### ISSUE TITLE
HOW TO RESUME TRAINING FROM LAST CHECKPOINT?

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3844]
Hi,
I have been training a model on my own dataset, How I can resume the training from last checkpoint saved? And also when I train the model does it save Best weights automatically  to some path or we need to provide some argument to do it. 
Please help me on this.

Thanks..

**Comment by LDOUBLEV** [comment]
Please refer to: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_en/detection_en.md#load-trained-model-and-continue-training
You can set the path of the latest model to `Global.checkpoints`.

**Comment by karndeepsingh** [comment]
Thanks @LDOUBLEV Can also please help to identify best accurate model after training has been finished. I have trained a custom model and all the model weights got saved in output folder and it also has latest.pdparams, is this latest.pdparams is best accurate model? Or how it is saved somewhere else. As i have checked all folders but there was no bestaccuracy folder present as mentioned in tutorial. Please help me to find the best trained weights.

Thanks

**Comment by shraddha291996** [comment]
@karndeepsingh Even I have the same question. Did you find any answer for that?

**Comment by ArturoJ** [comment]
In the .yml there is the section ( save_model_dir): ./output/db_mv3/

To load the checkpoint
 
` python tools/train.py -c configs/det/det_mv3_db.yml  -o Global.checkpoints=C:/XXXXXXXXXXX/PaddleOCR/output/db_mv3/latest
`

**Comment by ArturoJ** [comment]
To load the checkpoint

> Hi, I have been training a model on my own dataset, How I can resume the training from last checkpoint saved? And also when I train the model does it save Best weights automatically to some path or we need to provide some argument to do it. Please help me on this.
> 
> Thanks..

In the .yml there is the section ( save_model_dir): ./output/db_mv3/

To load the checkpoint
 
` python tools/train.py -c configs/det/det_mv3_db.yml  -o Global.checkpoints=C:/XXXXXXXXXXX/PaddleOCR/output/db_mv3/latest
`
