### ISSUE TITLE
HOW TO LOAD PRETRAINED WEIGHTS FOR SRN MODEL?

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3846]
Hi,
I am training my handwritten dataset and I am using rec_r50fpn_vd_none_srn.yml model to train on my dataset. But I want to use already pretrained model and fine tune iton my dataset. How can mention pretrained model??  Where I can find and it?.

Please help me to finetune the model. 
Thanks

**Comment by LDOUBLEV** [comment]
pretrain: 
Global.pretrained_model={path/to/weights}/best_accuracy

**Comment by karndeepsingh** [comment]
> pretrain:
> Global.pretrained_model={path/to/weights}/best_accuracy

Thanks for your reply @LDOUBLEV, I saw this command on tutotial's page but I want pretrained model develeoped by you and want to mention it in yaml file to finetune on mydataset. Please help me in providing the link to downloade the pretrained weight and how to mention it in yaml file for custom training. 


Thanks

**Comment by nazarovsky** [comment]
@karndeepsingh 
you can try downloading pretrained backbone weights from here
https://github.com/PaddlePaddle/PaddleClas/tree/release/static
and change config accordingly (worked for me for r18_vd)
```
  load_static_weights: True
  pretrained_model: ./pretrain_models/ResNet18_vd_pretrained 

```

**Comment by Ehteshamciitwah** [comment]
> > pretrain:
> > Global.pretrained_model={path/to/weights}/best_accuracy
> 
> Thanks for your reply @LDOUBLEV, I saw this command on tutotial's page but I want pretrained model develeoped by you and want to mention it in yaml file to finetune on mydataset. Please help me in providing the link to downloade the pretrained weight and how to mention it in yaml file for custom training.
> 
> Thanks

Hello, you can get pretrained of SRN model from here,
https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/doc/doc_en/algorithm_overview_en.md#TEXTRECOGNITIONALGORITHM
