### ISSUE TITLE
pdserving的服务无法启动

### ISSUE THREAD

**Issue by Ray8716397** [PaddlePaddle/PaddleOCR#3848]
我按照这个教程做
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/deploy/pdserving/README_CN.md

运行web_service.py后，但是http或gprc的服务都无法启动

**Comment by tink2123** [comment]
无法启动是指？ 可以看一下log里的报错信息

**Comment by Ray8716397** [comment]
Traceback (most recent call last):
  File "/home/guijutech/Workspace/github/PaddleOCR/deploy/pdserving/web_service.py", line 14, in <module>
    from paddle_serving_client.convert import WebService, Op
ImportError: cannot import name 'WebService' from 'paddle_serving_client.convert' (/opt/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle_serving_client/convert.py)

**Comment by tink2123** [comment]
更新一下server吧，都更新到 0.6.1 版本
