### ISSUE TITLE
DBNet参数含义

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3849]
DBNet 的use_dilation这个参数有什么作用呢，默认为False，设置为True可以提高检测效果吗

**Comment by tink2123** [comment]
检测框是否要膨胀，膨胀的话框会更外扩，针对场景中框过于紧致的情况

**Comment by lalalagogogochong** [comment]
> 检测框是否要膨胀，膨胀的话框会更外扩，针对场景中框过于紧致的情况

好的，谢谢老师
