### ISSUE TITLE
识别问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3850]
识别模型识别pdf文档的时候，效果不错，准确率都很高，但是有很小的几率出现识别某一页，有一行识别效果特别差，得分在0.3以下，识别结果完全错误，而其他行都正常且得分都很高。检查过检测模型结果，是正常的，请问这是什么原因？

**Comment by tink2123** [comment]
可以把效果不好的case贴一下吗～

**Comment by ziyaxuanyi** [comment]
> 可以把效果不好的case贴一下吗～
解决了，方向分类器问题，我不使用方向分类器，就可以正常识别出结果了。感觉应该是方向分类器和识别模型之间衔接的代码部分有bug，例子是很正常的pdf里面某一行，很长的一长条文本，很明显是水平的，不太会是方向分类器把它误分类为竖直的，检测出的部分没问题，感觉好像是经过分类器后，截取出来的检测区域发生了变化导致送入识别模型识别出来的完全是乱七八糟的结果。应该是衔接部分代码有bug，由于工作原因不便贴出，请见谅。我用的2.1的代码，希望你们自己排查一下。

**Comment by ziyaxuanyi** [comment]
debug了一下，发现是方向分类器的问题，方向分类器把正常文本错判为180，分数为0.99，因此做了180旋转之后，再送入识别网络的。请问怎么解决这种方向分类器误判的问题？ @ @tink2123

**Comment by Gmgge** [comment]
针对你的数据集再自己训练一下方向分类器试试，如果保证你的业务应用中不会遇到文字颠倒的情况，建议取消方向分类器。
