### ISSUE TITLE
PaddleOCR/dygraph官方给的预训练模型不能用

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/PaddleOCR#3853]
PaddleOCR/dygraph官方给的预训练模型不能用,使用下面的预训练模型,提示格式不对,官方能给正确能用的预训练模型吗?
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_pre.tar

**Comment by tink2123** [comment]
可以用啊，为什么说不能用呢。贴一下具体的报错吧

**Comment by 1220985305** [comment]
> 可以用啊，为什么说不能用呢。贴一下具体的报错吧
这是我放预训练模型的路径,日志显示模型不存在
![1](https://user-images.githubusercontent.com/74039253/131437710-f88ef343-436a-46cf-ba5f-938e6743b2df.png)
![2](https://user-images.githubusercontent.com/74039253/131437718-56c9251a-dcbf-4548-8634-0beadeb715e8.png)
![3](https://user-images.githubusercontent.com/74039253/131437884-8b08fa37-52d4-4823-a7eb-5c5ea346b51f.png)

**Comment by ioracion** [comment]
模型都没正确解压出来训练个球，用tar解压，训练的命令估计也有错误，仔细看看教程文档
