### ISSUE TITLE
HOW TO SAVE THE PREDICTIONS IN TEXT FILE?

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3854]
Hi,
I have trained a custom model and when try to inference it, it shows the output on notebook but I want that predictions output to be stored in a text file for all the images present in a folder. I have been using following command to extract the prediction:

paddleocr --image_dir http://n.sinaimg.cn/ent/transform/w630h933/20171222/o111-fypvuqf1838418.jpg --use_angle_cls=true

Please help me to save the prediction output on text file.

Thanks

**Comment by tink2123** [comment]
This function is not supported in the whl package. To implement this function, you need to modify the source code by yourself. 
There is a similar implementation in the PaddleOCR code base, you can refer to here:https://github.com/PaddlePaddle/PaddleOCR/blob/1664aa989e4e52d1d64922a670163c398f2f98fe/tools/infer_rec.py#L131-L133

**Comment by karndeepsingh** [comment]
> This function is not supported in the whl package. To implement this function, you need to modify the source code by yourself.
> There is a similar implementation in the PaddleOCR code base, you can refer to here:
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/1664aa989e4e52d1d64922a670163c398f2f98fe/tools/infer_rec.py#L131-L133

**Comment by karndeepsingh** [comment]
@tink2123  Thanks for your answer. What argument I should provide while calling infer_rec.py to save the predictions?
