### ISSUE TITLE
用predict_system infer的时候使用srn预处理模型报错

### ISSUE THREAD

**Issue by TUDelftHao** [PaddlePaddle/PaddleOCR#3855]
命令`python tools/infer/predict_system.py --image_dir='/test/data/ICDAR2015/test_speed_imgs/' --det_model_dir=/test/data/pretrained_weights/PPocr/inference/det_r50_db/ --det_algorithm='DB' --rec_model_dir=/test/data/pretrained_weights/PPocr/inference/rec_r50_srn/ --use_angle_cls=false --use_gpu=True --rec_algorithm="SRN" --rec_image_shape="1, 64, 256"`
结果报错
![image](https://user-images.githubusercontent.com/46449831/131322403-e9d4ba23-1e78-477c-ad0c-dbcc3f2176a8.png)
应该是检测模型扣图的尺寸不对，但是请问应该修改哪里呢？

**Comment by tink2123** [comment]
看报错应该是字符数量没有对上，预测的时候要指定一下自定义字典的路径。

**Comment by TUDelftHao** [comment]
> 看报错应该是字符数量没有对上，预测的时候要指定一下自定义字典的路径。

我用的icdar2015数据集做推理，应该就是默认的’en’ type吧。用其他的模型和db做串联预测都没问题，这个模型的输入尺寸和其他几个识别模型不一样，感觉应该是这里有问题吧。但是README文件没有说对于SRN做联合推理需要做什么特殊处理呢？

**Comment by liuwenfu1218** [comment]
> > 看报错应该是字符数量没有对上，预测的时候要指定一下自定义字典的路径。
> 
> 我用的icdar2015数据集做推理，应该就是默认的’en’ type吧。用其他的模型和db做串联预测都没问题，这个模型的输入尺寸和其他几个识别模型不一样，感觉应该是这里有问题吧。但是README文件没有说对于SRN做联合推理需要做什么特殊处理呢？

你好，我遇到了一样的问题，请问您解决了么？
