### ISSUE TITLE
tensort 静态图出错

### ISSUE THREAD

**Issue by sususu1** [PaddlePaddle/PaddleOCR#3856]
跑的paddle OCR 2.1版本，推理时候用到tensorrt,
检测和分类阶段能跑，但是到了识别阶段会报如下错误：
Traceback (most recent call. last):

File predictsys. py", line 227, in module>

recresult (r' /home/ workSpace/Paddle0CR- release 2. l/test data )

File "predictsys. py", line 224, in recresult

return main (args)

File " predictsys.py", line 148, in main

dt_ boxes, rec_ res = text sys (img)

File "predictsys. py", line 104, in_ call

rec_ res, elapse = self. text_ recognizer(img_ crop_ list

File /home/workSpace/Paddle0CR- release -2. 1/tools/ infer/predict_ rec. py", line 235, in_ call

self. predictor. run0

ValueError: (Inval idArgument) Input shapes are inconsistent with the model. Expect [3, 32, 100] in model description, but got [3, 32, 163] in runtime. TRT 5 or lower version does not support dynamiinput shapes. Please check and modify your input shapes.

[Hint: Expected model_ input_ shape = runtime_ input_ shape = true, but received model_ input_ shape = runtime_ input_ shape:0 != true:l. ] (at /paddle/ paddle fluid operators/ tensorrt/ tensorrt_ engine_. h:76)

请问这个input 代表什么，reshape还是报各种错。

**Comment by ziyaxuanyi** [comment]
换用高版本的tensorRT,低版本的不支持动态shape。照着paddleOCR2.2版本的代码，设置tensorRT的动态输入信息。
