### ISSUE TITLE
paddleOCR识别凸显银行卡

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#3857]
有什么比较有效的解决方案？通用模型识别平面银行卡还行，但一遇到凸显银行卡，就会出现一些数字识别错误。
![image](https://user-images.githubusercontent.com/66725845/131429805-f1701d6f-a4c3-4d23-aa2f-87291af23c22.png)

**Comment by ioracion** [comment]
造/找数据自己训练

**Comment by WenmuZhou** [comment]
楼上正解，造数据可以考虑styletext

**Comment by Essence9999** [comment]
> 楼上正解，造数据可以考虑styletext

微调吗？估计需要多少数据量

**Comment by WenmuZhou** [comment]
> > 楼上正解，造数据可以考虑styletext
> 
> 微调吗还是训练？估计需要多少数据量

微调吧，大概几十万就行了
