### ISSUE TITLE
使用AI studio notebook 训练的模型 转换成inference 出现问题

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/PaddleOCR#3859]
![image](https://user-images.githubusercontent.com/50097546/131461976-22bf34ec-0c2b-4925-8935-adcb23524401.png)

我使用AI studio的notebook训练的rec模型。但是想转换成推理模型使用出现问题。

请问这是什么原因

**Comment by WenmuZhou** [comment]
具体是啥问题

**Comment by 827346462** [comment]
我就没看出问题。但是感觉是保存模型的问题
我的paddle版本是1.7.2
我想把训练好的模型用官方的方法转成inference.  然后就出现了上图所示的错误。我用我自己的pc采用下面方法是可以转换的。
![image](https://user-images.githubusercontent.com/50097546/131607402-8f60e20e-7556-4724-88a4-293151b4a4f9.png)

**Comment by WenmuZhou** [comment]
看起来是配置文件有问题，检查下
