### ISSUE TITLE
PC机上的cpu耗时

### ISSUE THREAD

**Issue by zhangming8** [PaddlePaddle/PaddleOCR#386]
有人测试过最小的检测+识别模型在PC机上的cpu耗时吗，i3或者i5或者i7处理器。

**Comment by littletomatodonkey** [comment]
您好，这个之前没有测过，我们提供了4个平台上的预测耗时情况，可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/benchmark.md

**Comment by freshgeek** [comment]
cpu 半分钟 i5 7300HQ  还是要搞gpu的
