### ISSUE TITLE
我在debug的时候，以强制结束debug，直接编译器直接闪退，或者电脑直接注销了

### ISSUE THREAD

**Issue by HouYanGG** [PaddlePaddle/PaddleOCR#3860]
debug代码paddlleocr的时候，Ubuntu18系统，pycharm专业版，一旦强制结束debug，我一台电脑直接给我注销电脑，另一台直接编译器退出。

大家有遇到这样的问题吗，怎么搞！！！

就是很难受，搞代码不能debug很痛苦

还有crnn网络的代码在哪个文件夹下呀

**Comment by ziyaxuanyi** [comment]
建议vscode走起，debug无压力，丝滑，变量随便看。网络部分代码都在ppocr/modeling/下，backone,neck,head三个部分，找对应的识别模型的就行

**Comment by WenmuZhou** [comment]
楼上优秀

**Comment by HouYanGG** [comment]
> 建议vscode走起，debug无压力，丝滑，变量随便看。网络部分代码都在ppocr/modeling/下，backone,neck,head三个部分，找对应的识别模型的就行

这就准备冲vscode，看看多丝滑

**Comment by HouYanGG** [comment]
老哥们，用的这个吗，是的话，麻烦大佬给个链接，配置深度学习环境的教程呀
![Uploading visual_code.jpg…]()
