### ISSUE TITLE
Data Augmentation Selection

### ISSUE THREAD

**Issue by fadamsyah** [PaddlePaddle/PaddleOCR#3862]
Hi! Thank you for providing this repository. It's extremely cool!

I see on [img_tools.py](https://github.com/PaddlePaddle/PaddleOCR/blob/6b44a969d319307d42c1d0c5fdc6171514258f2d/ppocr/data/rec/img_tools.py) that there are some data augmentations which can be applied when we train a model. But, is it possible for us to **choose** several augmentations only? If applicable, how do we set our configuration file then?

**Comment by Gmgge** [comment]
你可以在configs中设定，例如在[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/configs/det/det_mv3_db.yml](url)，在75行设定图像增强参数。

**Comment by WenmuZhou** [comment]
This needs to manually modify the parameters in the code, you can also change the code to the form of passing parameters by yourself

**Comment by fadamsyah** [comment]
Great. Thank you. Sorry for my late response
