### ISSUE TITLE
Jetson Nano上推理，开启tensorrt加速，报错！

### ISSUE THREAD

**Issue by Miller-em** [PaddlePaddle/PaddleOCR#3864]
我将tensorrt选项设置为True，出现以下报错：

Traceback (most recent call last):
  File "use_/camera_infer.py", line 87, in <module>
    img,t=thread1.infer(frame)
  File "use_/camera_infer.py", line 53, in infer
    rec_res, draw_img, elapse = self.predict_system.main(utility.parse_args(), frame)  #推理
  File "/home/xiaozhoua/workspace/SND_nano/infer/predict_system.py", line 145, in main
    text_sys = TextSystem(args)
  File "/home/xiaozhoua/workspace/SND_nano/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/xiaozhoua/workspace/SND_nano/infer/predict_det.py", line 95, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/home/xiaozhoua/workspace/SND_nano/infer/utility.py", line 146, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [conv2d_124.tmp_0] shape of trt subgraph is [-1,256,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/paddle/data/tc/work/e247db3b53dc4203/Paddle/paddle/fluid/inference/tensorrt/engine.h:103)

**Comment by ziyaxuanyi** [comment]
建议issues搜tensorRT关键字,基本都有解决方法

**Comment by Miller-em** [comment]
这个地方我加入了

**Comment by Miller-em** [comment]
我在使能tensorrt后面添加了这个就能够成功调用trt了。
`if args.use_tensorrt:
            config.enable_tensorrt_engine(
                precision_mode=inference.PrecisionType.Half
                if args.use_fp16 else inference.PrecisionType.Float32,
                max_batch_size=args.max_batch_size,
                min_subgraph_size=20)
            # skip the minmum trt subgraph
            if mode == "det":
                min_input_shape = {
                    "x": [1, 3, 50, 50],
                    "conv2d_92.tmp_0": [1, 96, 20, 20],
                    "conv2d_91.tmp_0": [1, 96, 10, 10],
                    "conv2d_59.tmp_0": [1, 96, 20, 20],
                    "nearest_interp_v2_1.tmp_0": [1, 96, 10, 10],
                    "nearest_interp_v2_2.tmp_0": [1, 96, 20, 20],
                    "conv2d_124.tmp_0": [1, 96, 20, 20],
                    "nearest_interp_v2_3.tmp_0": [1, 24, 20, 20],
                    "nearest_interp_v2_4.tmp_0": [1, 24, 20, 20],
                    "nearest_interp_v2_5.tmp_0": [1, 24, 20, 20],
                    "elementwise_add_7": [1, 56, 2, 2],
                    "nearest_interp_v2_0.tmp_0": [1, 96, 2, 2]
                }
                max_input_shape = {
                    "x": [1, 3, 2000, 2000],
                    "conv2d_92.tmp_0": [1, 96, 400, 400],
                    "conv2d_91.tmp_0": [1, 96, 200, 200],
                    "conv2d_59.tmp_0": [1, 96, 400, 400],
                    "nearest_interp_v2_1.tmp_0": [1, 96, 200, 200],
                    "conv2d_124.tmp_0": [1, 256, 400, 400],
                    "nearest_interp_v2_2.tmp_0": [1, 96, 400, 400],
                    "nearest_interp_v2_3.tmp_0": [1, 24, 400, 400],
                    "nearest_interp_v2_4.tmp_0": [1, 24, 400, 400],
                    "nearest_interp_v2_5.tmp_0": [1, 24, 400, 400],
                    "elementwise_add_7": [1, 56, 400, 400],
                    "nearest_interp_v2_0.tmp_0": [1, 96, 400, 400]
                }
                opt_input_shape = {
                    "x": [1, 3, 640, 640],
                    "conv2d_92.tmp_0": [1, 96, 160, 160],
                    "conv2d_91.tmp_0": [1, 96, 80, 80],
                    "conv2d_59.tmp_0": [1, 96, 160, 160],
                    "nearest_interp_v2_1.tmp_0": [1, 96, 80, 80],
                    "nearest_interp_v2_2.tmp_0": [1, 96, 160, 160],
                    "conv2d_124.tmp_0": [1, 256, 160, 160],
                    "nearest_interp_v2_3.tmp_0": [1, 24, 160, 160],
                    "nearest_interp_v2_4.tmp_0": [1, 24, 160, 160],
                    "nearest_interp_v2_5.tmp_0": [1, 24, 160, 160],
                    "elementwise_add_7": [1, 56, 40, 40],
                    "nearest_interp_v2_0.tmp_0": [1, 96, 40, 40]
                }
            elif mode == "rec":
                min_input_shape = {"x": [args.rec_batch_num, 3, 32, 10]}
                max_input_shape = {"x": [args.rec_batch_num, 3, 32, 2000]}
                opt_input_shape = {"x": [args.rec_batch_num, 3, 32, 320]}
            elif mode == "cls":
                min_input_shape = {"x": [args.rec_batch_num, 3, 48, 10]}
                max_input_shape = {"x": [args.rec_batch_num, 3, 48, 2000]}
                opt_input_shape = {"x": [args.rec_batch_num, 3, 48, 320]}
            else:
                min_input_shape = {"x": [1, 3, 10, 10]}
                max_input_shape = {"x": [1, 3, 1000, 1000]}
                opt_input_shape = {"x": [1, 3, 500, 500]}
            config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape,
                                            opt_input_shape)`
