### ISSUE TITLE
Jetson，trt推理——Run Paddle-TRT Dynamic Shape mode. 这行INFO会等待很久

### ISSUE THREAD

**Issue by Miller-em** [PaddlePaddle/PaddleOCR#3867]
我在Jetson Nano上面使用Tensorrt成功调用了tensorrt，但是在下面 **TensorRT subgraph engine is enabled**这一行要等待6，7分钟，而且每帧都会等待这么久的时间，请问这是为什么呢？

**Comment by Miller-em** [comment]
W0831 21:42:35.842456  7887 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0831 21:42:35.928975  7887 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0831 21:42:36.338377  7887 graph_pattern_detector.cc:91] ---  detected 33 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0831 21:42:36.410378  7887 graph_pattern_detector.cc:91] ---  detected 49 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0831 21:42:36.526113  7887 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 156 nodes
I0831 21:42:36.633728  7887 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0831 21:42:40.439776  7887 engine.cc:86] Run Paddle-TRT FP16 mode
I0831 21:42:40.439841  7887 engine.cc:202] Run Paddle-TRT Dynamic Shape mode.
^C^C^C^C^C--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0831 21:45:49.598016  7887 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0831 21:45:49.624040  7887 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_4.tmp_0  size: 256
I0831 21:45:49.624096  7887 memory_optimize_pass.cc:199] Cluster name : conv2d_126.tmp_0  size: 256
I0831 21:45:49.624117  7887 memory_optimize_pass.cc:199] Cluster name : tmp_8  size: 1024
I0831 21:45:49.624136  7887 memory_optimize_pass.cc:199] Cluster name : tmp_9  size: 1024
I0831 21:45:49.624155  7887 memory_optimize_pass.cc:199] Cluster name : tmp_10  size: 1024
I0831 21:45:49.624172  7887 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_2.tmp_0  size: 1024
--- Running analysis [ir_graph_to_program_pass]
I0831 21:45:49.878849  7887 analysis_predictor.cc:636] ======= optimize end =======
I0831 21:45:49.895608  7887 naive_executor.cc:98] ---  skip [feed], feed -> x
I0831 21:45:49.898479  7887 naive_executor.cc:98] ---  skip [tmp_10], fetch -> fetch
main proc 7887 exit, kill process group 7887
Killed

**Comment by Miller-em** [comment]
![QQ截图20210830125701](https://user-images.githubusercontent.com/66259560/131518508-02d214fa-6d0b-4452-990e-2b6233449610.jpg)
![QQ截图20210831221442](https://user-images.githubusercontent.com/66259560/131518642-168357d5-f779-4fe9-a144-0208fbb580d2.jpg)

**Comment by Miller-em** [comment]
![QQ截图20210831221353](https://user-images.githubusercontent.com/66259560/131518734-1a56a2b3-7109-4f4a-8632-4bc02988b64c.jpg)
![QQ截图20210831221442](https://user-images.githubusercontent.com/66259560/131518751-0932f251-dbf9-483a-b150-cd3816f038b4.jpg)

**Comment by LDOUBLEV** [comment]
能运行成功的话，可以在之前的issue：https://github.com/PaddlePaddle/PaddleOCR/issues/3864 回复下解决方法后关闭吧，帮助下后来人

> 但是在下面 TensorRT subgraph engine is enabled这一行要等待6，7分钟，而且每帧都会等待这么久的时间，请问这是为什么呢？

第一次运行需要初始化，可能会耗费很久，但是花费那么久也不正常，我找个机器复现下问题，你那边可以先把GPU mem调小一点试试：https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/infer/utility.py#L40

**Comment by Miller-em** [comment]
我目前第一次加载很久后可以运行了（mem修改后还是一样的情况），但是部分图片出现了这样的报错
![QQ截图20210901130559](https://user-images.githubusercontent.com/66259560/131615051-00730f56-a377-46cc-b6d4-c071e72b067c.jpg)
我尝试将rec_batch_size从默认的6变成1，还是有这种报错。还有个问题就是使用GPU不使用trt和使用trt的推理速度是差不多得的，没有得到提高，请问是怎么回事呢？ @LDOUBLEV

**Comment by Miller-em** [comment]
谢谢 @LDOUBLEV ，现在是能够使用trt正常推理了，但是请问第一次加载初始化 TensorRT subgraph engine is enabled这行还是很久，这次是加载成功了推理速度就正常了，但是觉得初始化还是太久了有什么方式可以优化吗，

**Comment by LDOUBLEV** [comment]
> 这次是加载成功了推理速度就正常了，但是觉得初始化还是太久了有什么方式可以优化吗

我先确认下问题吧，有更新在这个issue里回复
