### ISSUE TITLE
明明有图片，为啥会有这样报错Exception: not found any img file in “./doc/imgs/16.png”

### ISSUE THREAD

**Issue by Jack-wx** [PaddlePaddle/PaddleOCR#387]
[root@kaifa01 PaddleOCR-develop]# ls -al ./doc/imgs/
总用量 3292
drwxr-xr-x  2 root root    4096 7月  17 12:59 .
drwxr-xr-x 12 root root    4096 7月  17 12:59 ..
-rwxr-xr-x  1 root root   25710 7月  17 12:59 10.jpg
-rwxr-xr-x  1 root root   48680 7月  17 12:59 11.jpg
-rw-r--r--  1 root root  398527 7月  17 12:59 12.jpg
-rw-r--r--  1 root root 1035932 7月  17 12:59 13.png
-rw-r--r--  1 root root  202605 7月  17 12:59 15.jpg
-rw-r--r--  1 root root  231010 7月  17 12:59 16.png
-rw-r--r--  1 root root  170784 7月  17 12:59 17.png
-rw-r--r--  1 root root  312292 7月  17 12:59 1.jpg
-rw-r--r--  1 root root   48049 7月  17 12:59 22.jpg
-rw-r--r--  1 root root   45018 7月  17 12:59 2.jpg
-rw-r--r--  1 root root  238867 7月  17 12:59 3.jpg
-rwxr-xr-x  1 root root   52551 7月  17 12:59 4.jpg
-rw-r--r--  1 root root   63736 7月  17 12:59 5.jpg
-rw-r--r--  1 root root   82868 7月  17 12:59 6.jpg
-rw-r--r--  1 root root   92684 7月  17 12:59 7.jpg
-rwxr-xr-x  1 root root   28864 7月  17 12:59 8.jpg
-rw-r--r--  1 root root  251539 7月  17 12:59 9.jpg
[root@kaifa01 PaddleOCR-develop]# python tools/infer/predict_system.py --image_dir=“./doc/imgs/” --det_model_dir=“./inference/ch_det_mv3_db/“   --rec_model_dir=”./inference/ch_rec_mv3_crnn/“ --use_gpu=False
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 161, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 117, in main
    image_file_list = get_image_file_list(args.image_dir)
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/ppocr/utils/utility.py", line 62, in get_image_file_list
    raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in “./doc/imgs/”
[root@kaifa01 PaddleOCR-develop]# 
[root@kaifa01 PaddleOCR-develop]# python tools/infer/predict_system.py --image_dir=“./doc/imgs/16.png” --det_model_dir=“./inference/ch_det_mv3_db/“   --rec_model_dir=”./inference/ch_rec_mv3_crnn/“ --use_gpu=False
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 161, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 117, in main
    image_file_list = get_image_file_list(args.image_dir)
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/ppocr/utils/utility.py", line 62, in get_image_file_list
    raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in “./doc/imgs/16.png”

**Comment by littletomatodonkey** [comment]
您的引号是中文的引号，需要换成英文的引号~
```
python3 tools/infer/predict_system.py \
    --image_dir="./doc/imgs/" \
    --rec_model_dir="./inference/rec_crnn/" \
    --det_model_dir="./inference/det_db/" \
    --rec_batch_num=1 \
    --use_gpu=False
```

**Comment by Jack-wx** [comment]
解决，空格导致的

**Comment by Jack-wx** [comment]
> 解决，路径这里不能带引号。去掉引号就好啦
