### ISSUE TITLE
sast训练正常，但是在训练过程中测试模式会卡主，报错。

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#3870]
![image](https://user-images.githubusercontent.com/43515926/131598489-d2c65aaf-b328-4b8f-8d05-832541bb8656.png)
测试模型的num_works和batch_size如下：
![image](https://user-images.githubusercontent.com/43515926/131598610-6f109585-fed4-4534-b855-022dc85dbc52.png)

**Comment by littletomatodonkey** [comment]
这块建议把train的 num workers修改为0测试下

**Comment by zcswdt** [comment]
> 的 num workers修改为0测试下

这里不是在eval model中才会出现卡主么？训练过程没错啊

**Comment by ZzyChris97** [comment]
请问你最后解决了没
