### ISSUE TITLE
检测模型异常Cannot open file inference.pdmodel

### ISSUE THREAD

**Issue by fwt1226** [PaddlePaddle/PaddleOCR#3871]
配置：win10+cmake3.17+opencv3.4.1+paddleocr2.0

C:\Users\fwt\Desktop\pro\OCR\PaddleOCR\PaddleOCR-release-2.0\deploy\cpp_infer\build\Release>ocr_system.exe config.txt 1.png
=======Paddle OCR inference config======
char_list_file : ./ppocr_keys_v1.txt
cls_model_dir : ./models/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 10
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./models/ch_ppocr_server_v2.0_det_infer/
gpu_id : 0
gpu_mem : 4000
max_side_len : 960
rec_model_dir : ./models/ch_ppocr_server_v2.0_rec_infer/
use_angle_cls : 0
use_fp16 : 0
use_gpu : 0
use_mkldnn : 0
use_polygon_score : 1
use_tensorrt : 0
visualize : 0
=======End of Paddle OCR inference config======
dir_name is not a valid directory !

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file ./models/ch_ppocr_server_v2.0_det_infer//inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:969)

请问这个问题是什么原因呢？

**Comment by littletomatodonkey** [comment]
没找到文件，看log，说的是dir_name不合法

![image](https://user-images.githubusercontent.com/14270174/131772717-02dde979-635c-48ce-b0d6-ad16ece05967.png)

**Comment by fwt1226** [comment]
> 没找到文件，看log，说的是dir_name不合法
> 
> ![image](https://user-images.githubusercontent.com/14270174/131772717-02dde979-635c-48ce-b0d6-ad16ece05967.png)

解决了 谢谢
是我把模型放在了二级文件夹下
应该在一级
改了以后就成功检测识别了
就是还会有一串这个显示
dir_name is not a valid directory !
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0902 11:17:09.960017 27996 fuse_pass_base.cc:57] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
I0902 11:17:09.968988 27996 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0902 11:17:09.978958 27996 memory_optimize_pass.cc:214] Cluster name : conv2d_transpose_4.tmp_0  size: 26214400
I0902 11:17:09.978958 27996 memory_optimize_pass.cc:214] Cluster name : batch_norm_24.tmp_2  size: 26214400
I0902 11:17:09.978958 27996 memory_optimize_pass.cc:214] Cluster name : elementwise_add_4  size: 1638400
I0902 11:17:09.979926 27996 memory_optimize_pass.cc:214] Cluster name : nearest_interp_v2_2.tmp_0  size: 26214400
I0902 11:17:09.979926 27996 memory_optimize_pass.cc:214] Cluster name : conv2d_60.tmp_0  size: 102400
I0902 11:17:09.979926 27996 memory_optimize_pass.cc:214] Cluster name : relu_0.tmp_0  size: 6553600
I0902 11:17:09.980945 27996 memory_optimize_pass.cc:214] Cluster name : conv2d_38.tmp_0  size: 6553600
I0902 11:17:09.980945 27996 memory_optimize_pass.cc:214] Cluster name : x  size: 4915200
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0902 11:17:10.017823 27996 analysis_predictor.cc:644] ======= optimize end =======
I0902 11:17:10.018821 27996 naive_executor.cc:98] ---  skip [feed], feed -> x
I0902 11:17:10.020848 27996 naive_executor.cc:98] ---  skip [conv2d_transpose_4.tmp_0], fetch -> fetch
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0902 11:17:10.342576 27996 main.cpp:79] The predict img: 1.png
后面才显示识别结果
The detection visualized image saved in ./ocr_vis.png
The predicted text is :
5#      score: 0.834904
BZJ-XZ-BK-210711-315    score: 0.998909
350Q2300        score: 0.985711
Cost  2.84073s

**Comment by littletomatodonkey** [comment]
前面的表示在预测时打印出的一些优化过程，可以忽略

**Comment by JacksonFFFFF** [comment]
具体应该怎么操作 能细说吗 着急等回复 谢谢了

**Comment by littletomatodonkey** [comment]
操作什么呢？
