### ISSUE TITLE
ppstructure/table中label及图片处理存在不一致的问题

### ISSUE THREAD

**Issue by WuChannn** [PaddlePaddle/PaddleOCR#3872]
您好，根据table_mv3.yml中的设置，数据处理transform中的倒数第三步为PaddingTableImage，该操作将resize之后的图片padding到（488,488,3），但是没有对坐标进行进一步的处理，这样的话框的坐标值都是相对于resize之后的图片宽高的比例，而不是相对于padding之后的宽高。

如此，在模型训练的过程中输入的是488*488的图片，最终输出的bbox应该是相对于488*488的值，这样与label是相对于resize之后的图片宽高的比例的情况是不匹配的。麻烦解答一下疑惑，感谢
![WeChatWorkScreenshot_e724c905-b041-4c92-ae1c-1cf3205d7bb4](https://user-images.githubusercontent.com/25492462/131607160-928de8b3-33a8-4f75-854a-04f9b528c071.png)

**Comment by cpwan** [comment]
Any updates?
The model has a very low loss (0.01xx) when my data contains images with a fixed length. But the loss is big (0.5xx) and sometimes goes `nan` when my data has variable lengths.
