### ISSUE TITLE
pgnet训练中文，识别结果出现字符重复严重的问题

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#3873]
![4e51cd1bce47b001fa1fe8e3cdd6496e](https://user-images.githubusercontent.com/67897601/131607148-7203073a-52b9-4e9b-9277-b2afbc9b08ee.jpg)
pgnet训练中文，识别结果出现字符重复严重的问题如上图，铭浩家纺的识别结果，出现过多字符重复。想知道这个是什么原因？

**Comment by LDOUBLEV** [comment]
pgnet的识别是基于CTC的，应该是识别分支没有训练好的原因

**Comment by aleaaaa** [comment]
请问训练中文数据集会用到预训练模型吗
