### ISSUE TITLE
参数max_length 的意义和作用是什么?

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#3874]

**Comment by aishangmaxiaoming** [comment]
> 限制图像最大尺寸，减少计算量。

增大max_lenth训练能否解决长文本识别不好的问题，如下图
<img width="682" alt="15f84409a929b9e1f1200f16002fefba" src="https://user-images.githubusercontent.com/67897601/131772325-8542dba9-abb7-46ae-8e11-86289d57ba79.png">

**Comment by littletomatodonkey** [comment]
这个估计是去重的问题，我们排查下srn的原因

**Comment by littletomatodonkey** [comment]
提供的crnn模型目前应该没有这个问题

**Comment by aishangmaxiaoming** [comment]
> 提供的crnn模型目前应该没有这个问题

crnn没问题，但是srn和p g ne t都有这个问题。目前在srn中文精度高一些，所以想使用SRN，但是这个问题也影响了整体的性能。所以有结果，麻烦同步下，谢谢

**Comment by Gmgge** [comment]
@aishangmaxiaoming 请问下你们尝试过改大这个参数进行测试嘛？想了解下目前是什么结果，提前感谢你的回复  ^_^。
