### ISSUE TITLE
SRN识别中文，文本段长会出现字符重复等识别问题？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#3875]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/67897601/131624386-b3e75a7e-8872-47cd-bb32-21c62a5bd235.png">
SRN识别中文，文本段长会出现字符重复等问题，这是什么原因

**Comment by tink2123** [comment]
输入的shape是多少？可能因为长文本被过度压缩了。

**Comment by aishangmaxiaoming** [comment]
> 输入的shape是多少？可能因为长文本被过度压缩了。

location': [17.0, 234.0, 514.0, 232.0, 514.0, 261.0, 17.0, 262.0] 这是四点坐标 ，检测完大概28 * 280 左右，resize是按照srn默认值
