### ISSUE TITLE
paddleOCR android端部署后精度下降

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/PaddleOCR#3876]
导出模型转.nb文件后精度下降,推理同一张图片,得到识别结果不一样
![服务器](https://user-images.githubusercontent.com/74039253/131626442-b69cee19-e201-4e03-a365-2de43bed02eb.jpg)
上图为在线测试推理结果;
![端侧](https://user-images.githubusercontent.com/74039253/131626502-611731f1-7e06-4360-96cf-fde98e7be713.jpg)
这个是端侧部署结果.两个结果不一样,有没有解决方案,或者给出原因!

**Comment by littletomatodonkey** [comment]
可能是参数不一样，需要看下后处理参数是否一致

**Comment by 1220985305** [comment]
> 可能是参数不一样，需要看下后处理参数是否一致
你好，后处理参数是指什么参数呀？在哪设置呢？

**Comment by Fenghaze** [comment]
您好，您的意思是把demo中ppocr_keys_v1.txt的内容改成自己的训练字典就可以了吗

**Comment by lexiaoyuan** [comment]
> 您好，您的意思是把demo中ppocr_keys_v1.txt的内容改成自己的训练字典就可以了吗

是直接使用的ppocr_keys_v1.txt，没有该里面的内容

**Comment by Fenghaze** [comment]
> 

我现在的情况是训练的模型用的自定义字典，那我在demo上直接用ppocr_keys_v1.txt就可以了吗

**Comment by lexiaoyuan** [comment]
> > 
> 
> 我现在的情况是训练的模型用的自定义字典，那我在demo上直接用ppocr_keys_v1.txt就可以了吗

不行，训练用的字典和demo用的字典要一致。如果用自定义的字典效果不好，可以试试用ppocr_keys_v1.txt这个字典**重新训练**（预训练模型建议用这个字典对应的ch_ppocr_mobile_v2.0_rec_pre）。

**Comment by Fenghaze** [comment]
@lexiaoyuan 那训练的配置文件可以使用 configs/rec/multi_language/rec_en_number_lite_train.yml 这个吗

**Comment by lexiaoyuan** [comment]
> @lexiaoyuan 那训练的配置文件可以使用 configs/rec/multi_language/rec_en_number_lite_train.yml 这个吗

建议是配置文件和预训练模型配套（参考[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md)），训练的效果会好一点。如果自己的数据够多，用哪个预训练模型或者配置文件或者自定义的字典，问题应该不大。如果数据不多，建议用预训练模型及对应的配置文件和字典在自己的数据集上训练。

**Comment by Fenghaze** [comment]
> > @lexiaoyuan 那训练的配置文件可以使用 configs/rec/multi_language/rec_en_number_lite_train.yml 这个吗
> 
> 建议是配置文件和预训练模型配套（参考https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md），训练的效果会好一点。如果自己的数据够多，用哪个预训练模型或者配置文件或者自定义的字典，问题应该不大。如果数据不多，建议用预训练模型及对应的配置文件和字典在自己的数据集上训练。

@lexiaoyuan 你好，我按照你的解决办法重新训练了模型，但是还是遇到了一些问题，可以留个联系方式吗
