### ISSUE TITLE
Jetson xavier NX 无法使用tensortrt 加速

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleOCR#3881]
您好,我现在使用的环境如下:
Paddle-2.1.1
Jetson xavier NX Jetpack-4.5.1
PaddleOCR-2.2
```python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/"  --use_angle_cls=False --use_space_char=True --use_gpu=True  --use_tensorrt=True --gpu_mem=3000```
报以下错误, 请问该怎么解决这个问题? 谢谢!
> phil@phil-desktop:~/Project/PaddleOCR$ python3 tools/infer/predict_system.py
> WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
> /usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
> W0902 12:52:31.771718 31837 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
> I0902 12:52:31.818235 31837 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
> --- Running analysis [ir_graph_build_pass]
> --- Running analysis [ir_graph_clean_pass]
> --- Running analysis [ir_analysis_pass]
> --- Running IR pass [conv_affine_channel_fuse_pass]
> --- Running IR pass [adaptive_pool2d_convert_global_pass]
> --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
> --- Running IR pass [shuffle_channel_detect_pass]
> --- Running IR pass [quant_conv2d_dequant_fuse_pass]
> --- Running IR pass [delete_quant_dequant_op_pass]
> --- Running IR pass [delete_quant_dequant_filter_op_pass]
> --- Running IR pass [simplify_with_basic_ops_pass]
> --- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
> --- Running IR pass [multihead_matmul_fuse_pass_v2]
> --- Running IR pass [multihead_matmul_fuse_pass_v3]
> --- Running IR pass [skip_layernorm_fuse_pass]
> --- Running IR pass [conv_bn_fuse_pass]
> I0902 12:52:32.075630 31837 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
> --- Running IR pass [unsqueeze2_eltwise_fuse_pass]
> --- Running IR pass [squeeze2_matmul_fuse_pass]
> --- Running IR pass [reshape2_matmul_fuse_pass]
> --- Running IR pass [flatten2_matmul_fuse_pass]
> --- Running IR pass [map_matmul_to_mul_pass]
> --- Running IR pass [fc_fuse_pass]
> --- Running IR pass [conv_elementwise_add_fuse_pass]
> I0902 12:52:32.106022 31837 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
> --- Running IR pass [tensorrt_subgraph_pass]
> I0902 12:52:32.135335 31837 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 13 nodes
> I0902 12:52:32.143494 31837 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
> E0902 12:52:33.526691 31837 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): kernel weights has count 147456 but 55296 was expected
> E0902 12:52:33.526934 31837 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): count of 147456 weights in kernel, but kernel dimensions (3,3) with 96 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 96 * 3*3 * 64 / 1 = 55296
> Traceback (most recent call last):
>   File "tools/infer/predict_system.py", line 193, in <module>
>     main(args)
>   File "tools/infer/predict_system.py", line 117, in main
>     text_sys = TextSystem(args)
>   File "tools/infer/predict_system.py", line 45, in __init__
>     self.text_detector = predict_det.TextDetector(args)
>   File "/home/phil/Project/PaddleOCR/tools/infer/predict_det.py", line 99, in __init__
>     args, 'det', logger)
>   File "/home/phil/Project/PaddleOCR/tools/infer/utility.py", line 250, in create_predictor
>     predictor = inference.create_predictor(config)
> ValueError: 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
> 1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> 2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
> 5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
> 6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
> 7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
> 8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
> 9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
> 10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
> 11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
> 12  paddle::inference::tensorrt::OpConverter::ConvertOp(paddle::framework::proto::OpDesc const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*, bool)
> 13  paddle::inference::tensorrt::ElementwiseWeightOpConverter::operator()(paddle::framework::proto::OpDesc const&, paddle::framework::Scope const&, bool)
> 14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> 15  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> InvalidArgumentError: The Bias's size(64) should be equal to the first dim(0) of the Input.
>   [Hint: Expected Y_t->dims()[0] == dims_x.d[1], but received Y_t->dims()[0]:64 != dims_x.d[1]:0.] (at /home/paddle/data/wangye19/Paddle/paddle/fluid/inference/tensorrt/convert/elementwise_op.cc:125)

**Comment by wangye707** [comment]
你好，这个是一个动态shape的参数bug，近期会修复。

**Comment by PhilCuriosity** [comment]
我曾尝试将CRNN的onnx模型，在Jetson nx, jetpack 4.5.1 上对其做动态shape的转换老是有问题。Nvidia那边建议使用jetpack4.6的进行转换。

**Comment by AndersonWuCheng** [comment]
> 这个是一个动态shape的参数bug，近期会修复。

我在windows c++環境同樣錯誤。請問這個bug有臨時解決方案麽？

**Comment by rainmakerMa** [comment]
> 您好,我现在使用的环境如下: Paddle-2.1.1 Jetson xavier NX Jetpack-4.5.1 PaddleOCR-2.2 `python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --use_angle_cls=False --use_space_char=True --use_gpu=True --use_tensorrt=True --gpu_mem=3000` 报以下错误, 请问该怎么解决这个问题? 谢谢!
> 
> > phil@phil-desktop:~/Project/PaddleOCR$ python3 tools/infer/predict_system.py
> > WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
> > /usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> > import imp
> > W0902 12:52:31.771718 31837 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
> > I0902 12:52:31.818235 31837 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
> > --- Running analysis [ir_graph_build_pass]
> > --- Running analysis [ir_graph_clean_pass]
> > --- Running analysis [ir_analysis_pass]
> > --- Running IR pass [conv_affine_channel_fuse_pass]
> > --- Running IR pass [adaptive_pool2d_convert_global_pass]
> > --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
> > --- Running IR pass [shuffle_channel_detect_pass]
> > --- Running IR pass [quant_conv2d_dequant_fuse_pass]
> > --- Running IR pass [delete_quant_dequant_op_pass]
> > --- Running IR pass [delete_quant_dequant_filter_op_pass]
> > --- Running IR pass [simplify_with_basic_ops_pass]
> > --- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
> > --- Running IR pass [multihead_matmul_fuse_pass_v2]
> > --- Running IR pass [multihead_matmul_fuse_pass_v3]
> > --- Running IR pass [skip_layernorm_fuse_pass]
> > --- Running IR pass [conv_bn_fuse_pass]
> > I0902 12:52:32.075630 31837 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
> > --- Running IR pass [unsqueeze2_eltwise_fuse_pass]
> > --- Running IR pass [squeeze2_matmul_fuse_pass]
> > --- Running IR pass [reshape2_matmul_fuse_pass]
> > --- Running IR pass [flatten2_matmul_fuse_pass]
> > --- Running IR pass [map_matmul_to_mul_pass]
> > --- Running IR pass [fc_fuse_pass]
> > --- Running IR pass [conv_elementwise_add_fuse_pass]
> > I0902 12:52:32.106022 31837 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
> > --- Running IR pass [tensorrt_subgraph_pass]
> > I0902 12:52:32.135335 31837 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 13 nodes
> > I0902 12:52:32.143494 31837 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
> > E0902 12:52:33.526691 31837 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): kernel weights has count 147456 but 55296 was expected
> > E0902 12:52:33.526934 31837 helper.h:84] conv2d (Output: conv2d_63.tmp_0399): count of 147456 weights in kernel, but kernel dimensions (3,3) with 96 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 96 * 3*3 * 64 / 1 = 55296
> > Traceback (most recent call last):
> > File "tools/infer/predict_system.py", line 193, in 
> > main(args)
> > File "tools/infer/predict_system.py", line 117, in main
> > text_sys = TextSystem(args)
> > File "tools/infer/predict_system.py", line 45, in **init**
> > self.text_detector = predict_det.TextDetector(args)
> > File "/home/phil/Project/PaddleOCR/tools/infer/predict_det.py", line 99, in **init**
> > args, 'det', logger)
> > File "/home/phil/Project/PaddleOCR/tools/infer/utility.py", line 250, in create_predictor
> > predictor = inference.create_predictor(config)
> > ValueError:
> > 
> > ## C++ Traceback (most recent call last):
> > 0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
> > 1   std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> > 2   paddle::AnalysisPredictor::Init(std::shared_ptrpaddle::framework::Scope const&, std::shared_ptrpaddle::framework::ProgramDesc const&)
> > 3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptrpaddle::framework::ProgramDesc const&)
> > 4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
> > 5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
> > 6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
> > 7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_deletepaddle::framework::ir::Graph >)
> > 8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
> > 9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
> > 10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >_) const
> > 11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc_, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
> > 12  paddle::inference::tensorrt::OpConverter::ConvertOp(paddle::framework::proto::OpDesc const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*, bool)
> > 13  paddle::inference::tensorrt::ElementwiseWeightOpConverter::operator()(paddle::framework::proto::OpDesc const&, paddle::framework::Scope const&, bool)
> > 14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> > 15  paddle::platform::GetCurrentTraceBackStringabi:cxx11
> > 
> > ## Error Message Summary:
> > InvalidArgumentError: The Bias's size(64) should be equal to the first dim(0) of the Input.
> > [Hint: Expected Y_t->dims()[0] == dims_x.d[1], but received Y_t->dims()[0]:64 != dims_x.d[1]:0.] (at /home/paddle/data/wangye19/Paddle/paddle/fluid/inference/tensorrt/convert/elementwise_op.cc:125)

请问你的paddle的推理库，是自己在nx上编的么

**Comment by pk-cb** [comment]
Hi any luck fixing this issue?
