### ISSUE TITLE
paddleocr检测模型训练一段时间后出错（显存溢出，数据加载出错）

### ISSUE THREAD

**Issue by vron8632** [PaddlePaddle/PaddleOCR#3882]
好像是显存溢出了，又报了数据加载的问题。如下所示：
识别模型就没有问题，paddle版本是2.1

MemoryError: Unable to allocate 14.1 MiB for an array with shape (4, 960, 960) and data type float32

File "D:\ProgramData\Anaconda3\envs\paddle2.1\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 204, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by vron8632** [comment]
num_workers: 0   还是报错
硬件是，内存16G，显卡6G/11G都试过

**Comment by yfq512** [comment]
@vron8632 你解决了么？同问
