### ISSUE TITLE
加载ch_ppocr_server_v2.0_common的预训练模型后，微调训练的数据量需要多少

### ISSUE THREAD

**Issue by yearlz** [PaddlePaddle/PaddleOCR#3883]
rt，使用大概1w的样本在预训练模型上进行微调，过拟合了，在迁移的样本域的效果也没有预训练的效果好。

**Comment by MissPenguin** [comment]
是finetune的识别模型吗，识别模型一版需要的数据量会多一些，最好能到10w级别，但具体还是取决于你的字符数量和场景难度。如果问题是过拟合，可以少迭代一段时间看看？
