### ISSUE TITLE
HOW CAN WE CHANGE THE ARCHITECTURE WHILE TRAINING OCR MODEL?

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3886]
Hi, 
I have trained CRNN model using resnet34 as backbone. Is it possible to change this architecture to differentone such as Resnet 152 or Densenet or any other backbone?

Thanks

**Comment by LDOUBLEV** [comment]
Maybe this [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_en/add_new_algorithm_en.md#network) can help you about how to change backbone.

**Comment by karndeepsingh** [comment]
@LDOUBLEV Thanks for helping! I am have changed the Architecture from RESNET 34 to RESNET 152 and when I am trying to change the Image_size in YAML file from  [3,32,100] to [1,224,224] , it throws error when I run the training script. Please sugggest the changes required for changing the image size as I want image to fed as GRAY not BGR (by default in yaml file).

Please help. Thanks

**Comment by nissansz** [comment]
Is it solved? Any working yaml file?
