### ISSUE TITLE
扩充文字识别模型的字典做迁移训练，是否可以冻结已经训练的label相关参数，只训练更新扩充的字典label的参数

### ISSUE THREAD

**Issue by xmadog** [PaddlePaddle/PaddleOCR#3887]
问题如标题，多谢

**Comment by LDOUBLEV** [comment]
无法实现，字符数变化了最后一层fc的权重维度也会变化，可以尝试只训练最后一层fc

**Comment by xmadog** [comment]
> 无法实现，字符数变化了最后一层fc的权重维度也会变化，可以尝试只训练最后一层fc

目前问题是我从6k的字符集扩充到1w的字符集，准备了600w的数据，其中扩充的字符样本数控制在平均200个左右，字典中原有的字符集的样本分布没有控制，后面出现了大部分'期'被错误识别为了‘撕’，‘回’被错误识别为了'【'。这种情况除了控制样本分布，是否可以在模型层面，通过控制损失函数或者局部参数来缓解呢？

**Comment by xmadog** [comment]
或者其他的更有效、快速的方式进行微调？

**Comment by LDOUBLEV** [comment]
期、回 属于比较常见的字符，识别错了应该是还没有训练的很好？

想加强增加字符的监督训练的话，可以参考focal loss的用法；

**Comment by xmadog** [comment]
非常感谢
