### ISSUE TITLE
some trt inputs dynamic shape info not set, check the INFO log above for more details.

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleOCR#3890]
![image](https://user-images.githubusercontent.com/48200202/131958482-e2a5e3b4-4836-455a-be30-a59840523040.png)
c++部署PPOCR时，使用TensorRT加速时出现了这个问题，请教老师，该如何解决。
配置如下：
CUDA10.2
CUDNN7.6.5
TensorRT 7
c++预测库“cuda10.2_cudnn7.6_avx_mkl_trt7”

**Comment by LDOUBLEV** [comment]
需要设置这个参数的最大最小shape，
1. 把inference.pdmodel拖到[netron.app](https://netron.app/)网站里，搜索conv2d_124，这个参数的shape
2. 参考[此处shape设置](https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/infer/utility.py#L170)，设置conv2d_124.tmp_0的shape

**Comment by PhilCuriosity** [comment]
> 需要设置这个参数的最大最小shape，
> 
> 1. 把inference.pdmodel拖到[netron.app](https://netron.app/)网站里，搜索conv2d_124，这个参数的shape
> 2. 参考[此处shape设置](https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/infer/utility.py#L170)，设置conv2d_124.tmp_0的shape

您好，问题[#3881](https://github.com/PaddlePaddle/PaddleOCR/issues/3881)也是这样的解决方法吗
