### ISSUE TITLE
识别多行文本时很不准

### ISSUE THREAD

**Issue by Actor12** [PaddlePaddle/PaddleOCR#3892]
![mutlline](https://user-images.githubusercontent.com/30867078/131982250-94ee379c-8679-4f37-b1dc-8bfa7223f3e7.jpg)

对于上述这种多行的文本，用paddleOCR文件来推理，很容易出现识别结果只有一两行是对的 ，其他行都是繁体字。
![1630660976(1)](https://user-images.githubusercontent.com/30867078/131982645-beaccf2d-54c4-4d35-bd24-9c3212b83410.jpg)

但是用predict_system.py来推理，就很准
![mutlline](https://user-images.githubusercontent.com/30867078/131985514-0c87e465-369f-47b8-97b5-1970bf8b4ebd.jpg)

定位和识别模型用的都是mobile，参数也没动。

**Comment by MissPenguin** [comment]
“用paddleOCR文件”来推理的意思是？可以贴一下具体命令吗，可能是参数没有配对

**Comment by Actor12** [comment]
> “用paddleOCR文件”来推理的意思是？可以贴一下具体命令吗，可能是参数没有配对

用paddleocr.py模型推理不准，找到原因了，是因为我把参数use_gpu设为了False，设成True就准了。但是费解的是，我本地没有gpu，paddlepadlle装的也不是gpu版。
