### ISSUE TITLE
我如何使用灰度图图像进行文字识别模型的训练？

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleOCR#3895]
我使用灰色图像数据集，我修改了yml文件中Train和Eval的配置：
- img_mode:GRAY
- image_shape:[1, 32, 96]

同时我没有采用预训练模型和checkpoints，即从头开始训练一个模型，但是我开始训练时，报错如下：
![image](https://user-images.githubusercontent.com/48787805/131997433-bf1a269a-964e-4506-8d8c-600f38b6e4aa.png)
每一张图片都报如上图所示的错误，那么我应当如何正确配置去训练一个识别灰度图中文字的文字识别模型？

**Comment by ddz-mark** [comment]
灰度图训练遇到同样的问题，如果 img_mode 调整为 GRAY，则报错。直接使用 BGR 则不报错

**Comment by PengYuan0** [comment]
你好请问解决了吗
