### ISSUE TITLE
英文识别后期处理阶段 是否可以增加词法矫正模块，发现有较多单词存在拼写错误问题

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#390]
![TIM截图20200721103552](https://user-images.githubusercontent.com/14155359/88006506-5accbf00-cb3e-11ea-9629-e43ff7053da2.png)

采用在线体验地址识别，识别效果以及相关标注如图

**Comment by dyning** [comment]
矫正模块后续考虑添加。建议可以试试通用中文模型效果，或者利用合成数据针对性finetuning模型

**Comment by deep-practice** [comment]
中文也有类似的矫正需求

**Comment by dyning** [comment]
好的
