### ISSUE TITLE
能把文档写好点吗？

### ISSUE THREAD

**Issue by andrew2558** [PaddlePaddle/PaddleOCR#3901]
C++按照你们的文档根本部署不成功。能不能更新一下文档。

**Comment by coder-sun** [comment]
我也遇到了，你成功了吗

**Comment by andrew2558** [comment]
@coder-sun 在网上找编译教程，碰到问题就搜，总算编译成功了。

**Comment by WenmuZhou** [comment]
方便指出文档哪里存在不足吗

**Comment by coder-sun** [comment]
> 方便指出文档哪里存在不足吗

我说下我遇到的。
1、cmake版本要求和gcc版本升级到3.17.3和8.2.0。
2、CMakeLists.txt中需要修改opencv相关的参数，文档中没有提到，OPENCV_DIR需要set成自己的位置。find package那也要修改到build文件夹，而不是默认的share/opencv，
#find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/OpenCV NO_DEFAULT_PATH)
find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}ild NO_DEFAULT_PATH)

**Comment by coder-sun** [comment]
老哥，现在的C++推理是每次都要加载模型，每次输入的参数都是模型位置和图片地址，这样每张图片都要重新加载一次模型，请问有没有加载模型和识别图片分开的C++代码（C++小白好蓝瘦），感谢！

**Comment by chenliang2014** [comment]
nt main(int argc, char **argv) {
  if (argc < 3) {
    std::cerr << "[ERROR] usage: " << argv[0]
              << " configure_filepath image_path\n";
    exit(1);
  }

  OCRConfig config(argv[1]);

  config.PrintConfigInfo();

 

  DBDetector det(config.det_model_dir, config.use_gpu, config.gpu_id,
                 config.gpu_mem, config.cpu_math_library_num_threads,
                 config.use_mkldnn, config.max_side_len, config.det_db_thresh,
                 config.det_db_box_thresh, config.det_db_unclip_ratio,
                 config.visualize, config.use_tensorrt, config.use_fp16);

  Classifier *cls = nullptr;
  if (config.use_angle_cls == true) {
    cls = new Classifier(config.cls_model_dir, config.use_gpu, config.gpu_id,
                         config.gpu_mem, config.cpu_math_library_num_threads,
                         config.use_mkldnn, config.cls_thresh,
                         config.use_tensorrt, config.use_fp16);
  }

  CRNNRecognizer rec(config.rec_model_dir, config.use_gpu, config.gpu_id,
                     config.gpu_mem, config.cpu_math_library_num_threads,
                     config.use_mkldnn, config.char_list_file,
                     config.use_tensorrt, config.use_fp16);


  

  for (int j = 2; j < argc; j++) {
	  std::string img_path(argv[j]);
	  auto start = std::chrono::system_clock::now();
	  cv::Mat srcimg = cv::imread(img_path, cv::IMREAD_COLOR);
	  std::vector<std::vector<std::vector<int>>> boxes;
	  det.Run(srcimg, boxes);

	  rec.Run(boxes, srcimg, cls);
	  auto end = std::chrono::system_clock::now();
	  auto duration =
		  std::chrono::duration_cast<std::chrono::microseconds>(end - start);
	  std::cout << "Cost  "
		  << double(duration.count()) *
		  std::chrono::microseconds::period::num /
		  std::chrono::microseconds::period::den
		  << "s" << std::endl;
  }
  return 0;
}
