### ISSUE TITLE
关于用自己的数据集训练识别模型的问题

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#3903]
rt，现在在做一个繁体中文报纸识别的项目，需要用自己的数据训练识别的模型，有下面两个问题想问：
1.可以在paddleocr已有的模型的权重的基础上继续训练吗？我看下载权重那块也有训练模型和预训练模型的权重，不知道要用哪一个，感觉从零开始训练太慢了，训练的效果也不能保证。
2.繁体中文报纸数据大多是竖直的中文文本图片，我试过paddleocr，好像只能识别横着的图片，竖着的图片基本只能识别一个字。训练的话，图片resize的尺寸需要调整吗？原来的resize尺寸是[3, 32, 320]

**Comment by WenmuZhou** [comment]
1. 可以，建议使用训练权重，这个是在中文数据集上训练好的
2. 竖直的图片paddleocr也是可以识别的，我们在训练数据集里加了这部分数据，这部分数据建议把整张图片旋转90度进行训练

**Comment by Lebron-Harden** [comment]
> 1. 可以，建议使用训练权重，这个是在中文数据集上训练好的
> 2. 竖直的图片paddleocr也是可以识别的，我们在训练数据集里加了这部分数据，这部分数据建议把整张图片旋转90度进行训练

感谢您的回复！我最近也尝试了训练，还有两个问题想请教一下您：
1.训练竖直的图片是只能将图片旋转后才可以吗？能不能直接就用竖直的图片训练呢？这样是不是需要修改网络结构和resize的尺寸呢？
2.我在PaddleOCR给的繁体中文的训练模型的基础上进行了训练，10000张合成图片，大概训练到30个epoch的时候准确率基本就不会提升了，然后拿训练后的权重去识别，效果却还没有训练以前的好，请问是什么原因呢？

**Comment by suchunxie** [comment]
> > 1. 可以，建议使用训练权重，这个是在中文数据集上训练好的
> > 2. 竖直的图片paddleocr也是可以识别的，我们在训练数据集里加了这部分数据，这部分数据建议把整张图片旋转90度进行训练
> 
> 感谢您的回复！我最近也尝试了训练，还有两个问题想请教一下您： 1.训练竖直的图片是只能将图片旋转后才可以吗？能不能直接就用竖直的图片训练呢？这样是不是需要修改网络结构和resize的尺寸呢？ 2.我在PaddleOCR给的繁体中文的训练模型的基础上进行了训练，10000张合成图片，大概训练到30个epoch的时候准确率基本就不会提升了，然后拿训练后的权重去识别，效果却还没有训练以前的好，请问是什么原因呢？

您好， 我也在做小语种的竖排文字识别，请问您的问题解决了吗？
