### ISSUE TITLE
根据教程配置完超轻量级中文检测、识别模型进行推理，精度几乎为0。

### ISSUE THREAD

**Issue by Yejing-Lai** [PaddlePaddle/PaddleOCR#3906]
paddleocr中文教程文档：https://www.bookstack.cn/read/PaddleOCR/inference.md#1idz44
我根据教程进行第一步和第四.1步进行操作
![image](https://user-images.githubusercontent.com/55339926/132167076-5af7a788-fa3f-43c5-847b-8e8413b77844.png)
无结果输出。
另外执行超轻量中文识别模型推理命令，输出文本识别的精确度几乎为0：
![image](https://user-images.githubusercontent.com/55339926/132167200-aa95a4c8-ac97-4918-b74a-00e154531c88.png)
请问是我漏了什么步骤吗？期待您的回复！谢谢~

**Comment by littletomatodonkey** [comment]
你好，方便把运行命令发一下吗？下载的模型确定是正确嘛？

**Comment by Yejing-Lai** [comment]
> 你好，方便把运行命令发一下吗？下载的模型确定是正确嘛？

一：首先我下载了文本检测模型：
wget -P ./ch_lite/ https://paddleocr.bj.bcebos.com/ch_models/ch_det_mv3_db.tar && tar xf ./ch_lite/ch_det_mv3_db.tar -C ./ch_lite/
并转换为推理模型
python3 tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.checkpoints=./ch_lite/det_mv3_db/best_accuracy Global.save_inference_dir=./inference/det_db/
最后生成了这三个文件：
![image](https://user-images.githubusercontent.com/55339926/132282108-30301ab0-6677-489e-ba3f-ee1f10969a49.png)
运行中文检测模型推理：
python3 tools/infer/predict_det.py --image_dir="./doc/imgs/2.jpg"--det_model_dir="./inference/det_db/"
可以得到正确的文本检测结果。

二：
下载超轻量中文识别模型：
wget -P ./ch_lite/ https://paddleocr.bj.bcebos.com/ch_models/ch_rec_mv3_crnn.tar && tar xf ./ch_lite/ch_rec_mv3_crnn.tar -C ./ch_lite/
并转换为推理模型
python3 tools/export_model.py -c configs/rec/rec_chinese_lite_train.yml -o Global.checkpoints=./ch_lite/rec_mv3_crnn/best_accuracy \
Global.save_inference_dir=./inference/rec_crnn/
此时报错无rec_chinese_lite_train.yml文件，我把PaddleOCR/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml作为替换文件（我猜有可能是这里的问题，但是我找不到configs/rec/rec_chinese_lite_train.yml），最后正常转换成推理模型生成以下文件：
![image](https://user-images.githubusercontent.com/55339926/132283944-17e42dfb-5fe6-4b99-b7fb-cedbbc8e0f03.png)
运行中文识别模型推理：
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./inference/rec_crnn/"
![image](https://user-images.githubusercontent.com/55339926/132284073-5963744d-7abd-45fe-b933-f51c27ff979a.png)
得到了错误的结果。
期待您的答复~

**Comment by qiano** [comment]
我下载的是推理模型，但与楼主的情况一样，原因不明

**Comment by qiano** [comment]
原因清楚了，因类对识别模型输入了整张图，应该要输入已检测到的文字图像区域

**Comment by Yejing-Lai** [comment]
> 原因清楚了，因类对识别模型输入了整张图，应该要输入已检测到的文字图像区域

我输入的图像就是已检测到的文字图像区域，如：
![word_4](https://user-images.githubusercontent.com/55339926/132623624-c6fe3a64-4019-46fd-9809-e000cd4b8f82.jpg)
请问您下载的是首页的推理模型吗？我在首页下载的推理模型如下：
![image](https://user-images.githubusercontent.com/55339926/132623801-7faa545e-986c-4ba3-b9c1-09037c5d50e9.png)
请问进行推理的命令是什么呢？

**Comment by qiano** [comment]
> > 原因清楚了，因类对识别模型输入了整张图，应该要输入已检测到的文字图像区域
> 
> 我输入的图像就是已检测到的文字图像区域，如：
> ![word_4](https://user-images.githubusercontent.com/55339926/132623624-c6fe3a64-4019-46fd-9809-e000cd4b8f82.jpg)
> 请问您下载的是首页的推理模型吗？我在首页下载的推理模型如下：
> ![image](https://user-images.githubusercontent.com/55339926/132623801-7faa545e-986c-4ba3-b9c1-09037c5d50e9.png)
> 请问进行推理的命令是什么呢？

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/quickstart.md
