### ISSUE TITLE
关于预训练模型与自己训练模型叠加问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#3907]
能否实现官网下载模型与自己训练模型叠加？使得模型鲁棒性更好

**Comment by littletomatodonkey** [comment]
你好，可以把识别结果拿到，然后根据score判断哪个模型的得分更高一些，选择得分更高的结果看下

**Comment by 18362890185** [comment]
> 你好，可以把识别结果拿到，然后根据score判断哪个模型的得分更高一些，选择得分更高的结果看下

好的，感谢回答，无法实现叠加是吗？
