### ISSUE TITLE
Training the model for custom dataset with two language

### ISSUE THREAD

**Issue by rakshanaa** [PaddlePaddle/PaddleOCR#3908]
I have my own datasets-it is an image i need to detect all the text in an image it contain both Arabic and English text. 
What per-trained model we can use for training? 
what type of dict we need to use?
Can you give me a solution for this process.

**Comment by littletomatodonkey** [comment]
Hi, now we do not have any model which supports 2 lauguages series, maybe you can train a language classifier and then go into the specific recognition branch.

**Comment by rakshanaa** [comment]
Thank you.
-> My own datasets  i tagged with the PPOCR label with semi-automatic graphic annotation tool and it detected(both English and Arabic)  i got label.txt file for the datasets .  
-> Then i train with en_dict.txt using MobileNetV3(pre-trained_model), then it is trained, while test the image i am getting only one word detection rest all text is not detected(the detection is also wrong). I need multiple detection.
-> Any step i am doing is wrong so i am not able to get multiple detection
