### ISSUE TITLE
关于竖排文字的识别：

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#391]
您好，感谢开源这个项目。我请教一个问题。就是在中文识别过程中：1.竖排文字和横排文字，将竖排文字旋转90度混合到一起训练出一个模型。2.单独训练横排模型合竖排模型，哪种效果好呢？

**Comment by dyning** [comment]
没有详细做过消融实验，第二种效果更好，但是需要多一个识别模型和方向分类器。目前从效果看，第一种方案也OK，效果没有差距太多。

**Comment by zcswdt** [comment]
> 没有详细做过消融实验，第二种效果更好，但是需要多一个识别模型和方向分类器。目前从效果看，第一种方案也OK，效果没有差距太多。
谢谢百忙之中的回复，我之前合成400万中文数据，使用https://github.com/clovaai/deep-text-recognition-benchmark这个仓库训练了一个横排识别模型，效果很好。但是我想加竖排文字识别能力，于是我合成100万竖排文字并将竖排文字旋转90度，使用训练好的横排模型作为预训练模型，进行finetune。虽然训练出来的模型具有竖排文字的识别能力，准确率在85%，但是同时失去了横排文字的识别能力，请问出现这种情况的原因大概是什么，可以帮忙分析一下吗？

**Comment by zcswdt** [comment]
> 没有详细做过消融实验，第二种效果更好，但是需要多一个识别模型和方向分类器。目前从效果看，第一种方案也OK，效果没有差距太多。

谢谢百忙之中的回复，我之前合成400万中文数据，使用https://github.com/clovaai/deep-text-recognition-benchmark 这个仓库训练了一个横排识别模型，效果很好。但是我想加竖排文字识别能力，于是我合成100万竖排文字并将竖排文字旋转90度，使用训练好的横排模型作为预训练模型，进行finetune。虽然训练出来的模型具有竖排文字的识别能力，准确率在85%，但是同时失去了横排文字的识别能力，请问出现这种情况的原因大概是什么，可以帮忙分析一下吗？

![image](https://user-images.githubusercontent.com/43515926/88028383-2c190d80-cb6b-11ea-8658-48e29b3f43c0.png)

**Comment by cjt222** [comment]
请问下，你生成竖排文字使用的是什么工具呢？

**Comment by zcswdt** [comment]
> 请问下，你生成竖排文字使用的是什么工具呢？

可以去看一下我的git项目，横排竖排都支持，并且支持生成rgb颜色图片。https://github.com/zcswdt/Color_OCR_image_generator

**Comment by dyning** [comment]
横排竖排效果差别大的原因，如果不finetuing，重头训，是否验证过？

**Comment by zcswdt** [comment]
> 横排竖排效果差别大的原因，如果不finetuing，重头训，是否验证过？

您的意思是讲，横排和竖排文字混合到一起，重头训练，然后看看识别效果是吗？如果是这样的话，我没有验证过。如果重头训的话，横排和竖排的文字比例大概是多少呢？

**Comment by cjt222** [comment]
> > 请问下，你生成竖排文字使用的是什么工具呢？
> 
> 可以去看一下我的git项目，横排竖排都支持，并且支持生成rgb颜色图片。https://github.com/zcswdt/Color_OCR_image_generator

收到，多谢

**Comment by fanw52** [comment]
@zcswdt 感谢开源，如果后面仅仅用竖排文字做训练，横排文字识别率是正常的，灾难性遗忘！！！！

**Comment by jdhao** [comment]
> > 横排竖排效果差别大的原因，如果不finetuing，重头训，是否验证过？
> 
> 您的意思是讲，横排和竖排文字混合到一起，重头训练，然后看看识别效果是吗？如果是这样的话，我没有验证过。如果重头训的话，横排和竖排的文字比例大概是多少呢？

后面是否采用横排和竖排一起训了，效果如何。。？

**Comment by ckmstydy** [comment]
> > 没有详细做过消融实验，第二种效果更好，但是需要多一个识别模型和方向分类器。目前从效果看，第一种方案也OK，效果没有差距太多。
> 
> 谢谢百忙之中的回复，我之前合成400万中文数据，使用https://github.com/clovaai/deep-text-recognition-benchmark 这个仓库训练了一个横排识别模型，效果很好。但是我想加竖排文字识别能力，于是我合成100万竖排文字并将竖排文字旋转90度，使用训练好的横排模型作为预训练模型，进行finetune。虽然训练出来的模型具有竖排文字的识别能力，准确率在85%，但是同时失去了横排文字的识别能力，请问出现这种情况的原因大概是什么，可以帮忙分析一下吗？
> 
> ![image](https://user-images.githubusercontent.com/43515926/88028383-2c190d80-cb6b-11ea-8658-48e29b3f43c0.png)

您好，最近也想训练一个竖排文字识别的模型，请问您提到的将竖排文字旋转90度，是直接将整张图片旋转吗？不需要管单个文字的方向吗？
