### ISSUE TITLE
多线程问题

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/PaddleOCR#3914]
代码单线程跑时没问题，当多线程跑时 predictor->Run()会报错。
![005336eea027dead740d2c2eb30622c](https://user-images.githubusercontent.com/18069515/132202483-b11716f5-41dd-4691-982c-5d834178c209.png)

**Comment by littletomatodonkey** [comment]
可以说下更加具体的运行脚本以及paddle版本吗？
