### ISSUE TITLE
设置use_gpu=True时，只能调用第一个显卡，强制将yolov5的显卡调用变为第一个显卡

### ISSUE THREAD

**Issue by lingLucas** [PaddlePaddle/PaddleOCR#3917]

**Comment by littletomatodonkey** [comment]
你好，可以通过设置CUDA_VISIBILE_DEVICES环境变量来设置使用哪一个显卡哈

**Comment by lingLucas** [comment]
> 你好，可以通过设置CUDA_VISIBILE_DEVICES环境变量来设置使用哪一个显卡哈

按照你的要求，我修改CUDA_VISIBILE_DEVICES=0，1，但是还是只跑了第0个
