### ISSUE TITLE
有没有centos7 cpu下C++推理的相关docker镜像，按C++推理文档部署总是出错

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#3920]
有没有centos7 cpu下C++推理的相关docker镜像，按C++推理文档部署总是出错。
或者编译好的cpu C++版本的paddleocr

**Comment by littletomatodonkey** [comment]
@MissPenguin

**Comment by coder-sun** [comment]
> 要不贴下具体的报错信息呢？

![image](https://user-images.githubusercontent.com/25734125/132448496-1755d6d3-bdf6-4578-b380-2e00551c709a.png)

**Comment by coder-sun** [comment]
> 要不贴下具体的报错信息呢？
已经解决了。
我说下我遇到的。
1、cmake版本要求和gcc版本升级到3.17.3和8.2.0。
2、CMakeLists.txt中需要修改opencv相关的参数，文档中没有提到，OPENCV_DIR需要set成自己的位置。find package那也要修改到build文件夹，而不是默认的share/opencv， 
#find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/OpenCV NO_DEFAULT_PATH)
  find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}ild NO_DEFAULT_PATH)

**Comment by coder-sun** [comment]
现在的C++推理是每次都要加载模型，每次输入的参数都是模型位置和图片地址，请问有没有加载模型和识别图片分开的C++代码（C++小白好蓝瘦）
