### ISSUE TITLE
重头训练还是使用预训练模型好呢

### ISSUE THREAD

**Issue by lvjianjin001** [PaddlePaddle/PaddleOCR#3921]
目前我大概准备了1000万左右的识别数据，请问是重头训练还是使用预训练模型好呢？
如果是使用预训练模型继续训练有什么注意事项吗？
目前我将学习率设置为0.0001进行预训练感觉模型提升的很慢。

**Comment by littletomatodonkey** [comment]
你好，建议加载我们的预训练模型进行训练哈，收敛会快很多，另外初始学习率建议设置为0.001

**Comment by chros425** [comment]
> 你好，建议加载我们的预训练模型进行训练哈，收敛会快很多，另外初始学习率建议设置为0.001

你好，请问在扩充字典集到7000多个字符的情况下，如何利用百度官方的预训练模型呢，如果是修改最后一层的，请问是怎么修改的？
