### ISSUE TITLE
英文模型比中文模型慢

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#3926]
请问识别模型中，英文模型只有2.6M，中文模型5M，为啥英文模型没有比中文模型快呢

**Comment by MissPenguin** [comment]
这个速度是怎么对比的呢，中英文的识别都挺快的，大致感觉上不会有明显差距

**Comment by Dandelion111** [comment]
> 这个速度是怎么对比的呢，中英文的识别都挺快的，大致感觉上不会有明显差距

就是检测用中文和英文模型分别检测只有英文数字的图像，两个模型速度差不多，本来以为英文模型比较小，速度会快点呢

**Comment by MissPenguin** [comment]
端到端对比很难看出差距，因为检测时间占比较大，有需要可以用相同数据集只对比识别模型。

**Comment by Dandelion111** [comment]
> 端到端对比很难看出差距，因为检测时间占比较大，有需要可以用相同数据集只对比识别模型。

好的，谢谢啦

**Comment by Dandelion111** [comment]
> 端到端对比很难看出差距，因为检测时间占比较大，有需要可以用相同数据集只对比识别
你好，我对比了下识别模型，结果还是英文模型和中文模型时间差不多，英文字典只有几十个字符，而且模型更小，理论上应该要快一些啊，请问是不是有什么可以设置的参数去调整呢？
