### ISSUE TITLE
表格识别的训练

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#3927]
你好，请问表格识别的怎么进行训练呢？以及官方是否提供了训练代码？最后问下，不知道什么时候会开源基于中文的表格识别模型以及相关代码？

**Comment by MissPenguin** [comment]
您好，表格识别训练可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/ppstructure/table/README_ch.md#32-%E8%AE%AD%E7%BB%83

中文的表格模型在研发计划中了，不过暂时还没有具体排期，可以先尝试自己训一下～

**Comment by hhhhhhogan** [comment]
好的谢谢回复，也感谢ppocr的表格识别开源！

在 2021-09-07 10:28:54，"MissPenguin" ***@***.***> 写道：

您好，表格识别训练可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/ppstructure/table/README_ch.md#32-%E8%AE%AD%E7%BB%83

中文的表格模型在研发计划中了，不过暂时还没有具体排期，可以先尝试自己训一下～

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weinixuehao** [comment]
中文表格的训练数据有提供？或者从哪里找？
