### ISSUE TITLE
文本合成

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#3931]
请问如何使用styletext合成竖直文本？

**Comment by weisy11** [comment]
可以尝试将输入文本图像旋转90度，再进行合成。不过目前效果可能不是很理想，可以关注后续更新。

**Comment by buptlihang** [comment]
PIL种的ImageFont可以旋转字体文件中单个字符的cmap，然后就可以像生成水平文本一样生成竖直文本:

ImageFont.TransposedFont(font, orientation=Image.ROTATE_90)

可以参考[官方文档](https://www.osgeo.cn/pillow/reference/ImageFont.html#PIL.ImageFont.TransposedFont)

也可以参考我们的实现[DeepVAC/Synthesis2D](https://github.com/DeepVAC/Synthesis2D/blob/master/ocr/recognition/synthesis.py#L213)

**Comment by ziyaxuanyi** [comment]
好的，感谢
