### ISSUE TITLE
paddleOCR可以部署到rk3399Pro吗

### ISSUE THREAD

**Issue by huaxiangwangman** [PaddlePaddle/PaddleOCR#3939]

**Comment by Zhang-O** [comment]
可以

**Comment by huaxiangwangman** [comment]
参考哪一个教程呢，我看paddle Lite不支持呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR可以部署到rk3399Pro吗 (#3939)





 
可以
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zhang-O** [comment]
> 参考哪一个教程呢，我看paddle Lite不支持呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年9月8日(星期三) 下午3:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR可以部署到rk3399Pro吗 (#3939) 可以 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没有教程，就按照官方来进行，都是arm公版架构

**Comment by huaxiangwangman** [comment]
好，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR可以部署到rk3399Pro吗 (#3939)





  
参考哪一个教程呢，我看paddle Lite不支持呢
 …
 ------------------�0�2原始邮件�0�2------------------ 发件人: @.&gt;; 发送时间: 2021年9月8日(星期三) 下午3:16 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] paddleOCR可以部署到rk3399Pro吗 (#3939) 可以 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
没有教程，就按照官方来进行，都是arm公版架构
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
