### ISSUE TITLE
模型库404

### ISSUE THREAD

**Issue by MyOnlyCat** [PaddlePaddle/PaddleOCR#3942]
ch_ppocr_mobile_slim_v2.1_det 推理模型
ch_ppocr_mobile_v2.1_det 推理和训练模型
上面的到目前是404状态，无法下载

**Comment by LDOUBLEV** [comment]
你好，本次发版的模型版本号改为了PP-OCRv2，可以下载尝鲜，目前在主页README.md和doc/doc_ch/model_list.md中都提供了下载链接
![image](https://user-images.githubusercontent.com/26592129/132303937-bf1bddde-198f-4dab-8274-4859cc2f81c0.png)
![image](https://user-images.githubusercontent.com/26592129/132303983-091ec58e-0591-4acf-8c60-463630e85a55.png)

**Comment by MyOnlyCat** [comment]
> 你好，本次发版的模型版本号改为了PP-OCRv2，可以下载试鲜，现在在主页README.md和doc/doc_ch/model_list.md中都提供了下载链接
> ![图片](https://user-images.githubusercontent.com/26592129/132303937-bf1bddde-198f-4dab-8274-4859cc2f81c0.png)
> ![图片](https://user-images.githubusercontent.com/26592129/132303983-091ec58e-0591-4acf-8c60-463630e85a55.png)
