### ISSUE TITLE
EAST训练文本检测

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3944]
EAST做文本检测的时候有的长文本会只检测到中间的一部分，框的边缘会漏检一部分，这个有什么参数也可以调整一下吗，应该怎么处理呢

**Comment by MissPenguin** [comment]
您说的这个现象是EAST算法天生的缺陷哈，如果长文本较多，可以换DB会好一些

**Comment by lalalagogogochong** [comment]
> 您说的这个现象是EAST算法天生的缺陷哈，如果长文本较多，可以换DB会好一些

哦哦，好的，谢谢您了
