### ISSUE TITLE
PGNet训练优化、网络构建相关问题请教~

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#3947]
冒昧请教一下相关问题:
查看以前版本 有相关图像增强的变化代码 PaddleOCR/ppocr/data/rec/img_tools.py 
可以在配置文件中增加参数distort: true
release/2.2显示没有路径 如何增加图像增强
PGNet中dilation参数防止漏识别参数有吗?
PGNet可以调整相关的backbone吗? PGNet支持MobileNetV3系列吗?官方使用ResNet_vd的那个呢
pg损失是由检测什么和识别的ctc构成?
head中默认通道层数in_channels是多少呢?有默认image_shape参数吗?配置文件无指定.

**Comment by LDOUBLEV** [comment]
> 查看以前版本 有相关图像增强的变化代码 PaddleOCR/ppocr/data/rec/img_tools.py
可以在配置文件中增加参数distort: true

这个现在不用配置了，识别算法默认开启了扰动，文档中介绍了https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/recognition.md#21-%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA

增加新的数据处理函数，可以参考这部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E5%A4%84%E7%90%86

> PGNet中dilation参数防止漏识别参数有吗?

没有防止漏识别的参数，如果是漏识别，应该是识别分支没有训练好

> PGNet可以调整相关的backbone吗? PGNet支持MobileNetV3系列吗?官方使用ResNet_vd的那个呢

可以调整backbone，参考这个部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E7%BD%91%E7%BB%9C

> pg损失是由检测什么和识别的ctc构成?

看下论文和代码

> head中默认通道层数in_channels是多少呢?有默认image_shape参数吗?配置文件无指定.

PgNet head的inchannels等于neck网络的out_channels，可以看下这里的代码逻辑：https://github.com/PaddlePaddle/PaddleOCR/blob/25ce7ae163e01958d586ae33e5f8a98a55ae604f/ppocr/modeling/architectures/base_model.py#L66

**Comment by lin-0015** [comment]
> > 查看以前版本 有相关图像增强的变化代码 PaddleOCR/ppocr/data/rec/img_tools.py
> > 可以在配置文件中增加参数distort: true
> 
> 这个现在不用配置了，识别算法默认开启了扰动，文档中介绍了https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/recognition.md#21-%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA
> 
> 增加新的数据处理函数，可以参考这部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E5%A4%84%E7%90%86
> 
> > PGNet中dilation参数防止漏识别参数有吗?
> 
> 没有防止漏识别的参数，如果是漏识别，应该是识别分支没有训练好
> 
> > PGNet可以调整相关的backbone吗? PGNet支持MobileNetV3系列吗?官方使用ResNet_vd的那个呢
> 
> 可以调整backbone，参考这个部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E7%BD%91%E7%BB%9C
> 
> > pg损失是由检测什么和识别的ctc构成?
> 
> 看下论文和代码
> 
> > head中默认通道层数in_channels是多少呢?有默认image_shape参数吗?配置文件无指定.
> 
> PgNet head的inchannels等于neck网络的out_channels，可以看下这里的代码逻辑：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/25ce7ae163e01958d586ae33e5f8a98a55ae604f/ppocr/modeling/architectures/base_model.py#L66

谢谢你~ 感谢

**Comment by lin-0015** [comment]
> > 查看以前版本 有相关图像增强的变化代码 PaddleOCR/ppocr/data/rec/img_tools.py
> > 可以在配置文件中增加参数distort: true
> 
> 这个现在不用配置了，识别算法默认开启了扰动，文档中介绍了https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/recognition.md#21-%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA
> 
> 增加新的数据处理函数，可以参考这部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E5%A4%84%E7%90%86
> 
> > PGNet中dilation参数防止漏识别参数有吗?
> 
> 没有防止漏识别的参数，如果是漏识别，应该是识别分支没有训练好
> 
> > PGNet可以调整相关的backbone吗? PGNet支持MobileNetV3系列吗?官方使用ResNet_vd的那个呢
> 
> 可以调整backbone，参考这个部分教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/add_new_algorithm.md#%E7%BD%91%E7%BB%9C
> 
> > pg损失是由检测什么和识别的ctc构成?
> 
> 看下论文和代码
> 
> > head中默认通道层数in_channels是多少呢?有默认image_shape参数吗?配置文件无指定.
> 
> PgNet head的inchannels等于neck网络的out_channels，可以看下这里的代码逻辑：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/25ce7ae163e01958d586ae33e5f8a98a55ae604f/ppocr/modeling/architectures/base_model.py#L66

![image](https://user-images.githubusercontent.com/65577659/132346262-c1869e4f-b1dd-462b-94d6-0696ed6d8ab1.png)
看着和论文数值挺接近的,实际准备测试集,大概70%过一些,还有优化空间吗?(模型本身网络因素 亦或是训练集原料因素)

**Comment by LDOUBLEV** [comment]
优化的话，可以先可视化分析看下，找一些badcase，看下是检测的问题还是识别的问题，针对性的优化下

**Comment by lin-0015** [comment]
> 优化的话，可以先可视化分析看下，找一些badcase，看下是检测的问题还是识别的问题，针对性的优化下

谢谢建议~
