### ISSUE TITLE
文本侦测训练问题

### ISSUE THREAD

**Issue by latinfish28** [PaddlePaddle/PaddleOCR#3949]
请问我这样的结果是对的吗？
![螢幕擷取畫面 2021-09-07 162235](https://user-images.githubusercontent.com/82246665/132310766-3bed5789-e2e8-48d5-be12-d2ad982b3aa8.jpg)
不过我看别人训练后会出现的讯息是这样
![螢幕擷取畫面 2021-09-07 162536](https://user-images.githubusercontent.com/82246665/132311253-c984c561-b2f5-40d4-a2c3-33fdbe88f9ca.jpg)

**Comment by MissPenguin** [comment]
你这个看着只是初始化完，还没开始训练，如果一直这样可能是卡死了，可以check下数据格式是否正确。

**Comment by latinfish28** [comment]
我的label格式长这样
[test_label.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7121273/test_label.txt)
我识别训练的结果也是跟上面截图一样
[rec_gt_test.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7121283/rec_gt_test.txt)

**Comment by latinfish28** [comment]
yml档我只有修改档案路径而已

**Comment by MissPenguin** [comment]
你这是训检测还是识别啊，可以贴一下完整的config吗

**Comment by latinfish28** [comment]
我两种都有训，但结果都一样，我先放检测的config
[ch_det_mv3_db_v2.0.yml.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7121473/ch_det_mv3_db_v2.0.yml.txt)

**Comment by latinfish28** [comment]
还是跟这个有关系呢?
`[2021/09/08 15:22:20] root INFO: The shape of model params head.thresh.conv3.bias [1] not matched with loaded params fc.weight (1280, 1000) !`

**Comment by MissPenguin** [comment]
看不太出来具体问题，可以加一些log看看具体是在哪一步卡住
