### ISSUE TITLE
端测部署时,android demo把拍照图片处理异常模糊

### ISSUE THREAD

**Issue by zzdang** [PaddlePaddle/PaddleOCR#395]
android demo里面检测识别相册图片正常, 对于拍照图片apk处理后特别模糊, 导致检测识别异常

**Comment by littletomatodonkey** [comment]
这个是因为在实时拍照的时候，可能会有抖动、不对焦等问题，所以图片相对模糊，在拍照时，可以等界面稍微稳定一点再拍摄~
如果希望在图片输入网络之前进行去模糊，可以在这里进行修改：
https://github.com/PaddlePaddle/PaddleOCR/blob/73261c9ec6b20da52bab8ac213064a32c1fee516/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MainActivity.java#L398

**Comment by zzdang** [comment]
貌似不是因为抖动,拍出来是清晰的,运行文字检测识别后显示的图就是模糊的,不知道是哪里把图片处理模糊了

**Comment by littletomatodonkey** [comment]
要不你上传下检测识别之前和之后的图片，我们分析下？我这边ios的demo看着没啥问题
![image](https://user-images.githubusercontent.com/14270174/88132039-047c8080-cc11-11ea-9884-a882ebe76270.png)

**Comment by zzdang** [comment]
![1562302810](https://user-images.githubusercontent.com/22818954/88132727-e1eb6700-cc12-11ea-89fb-91ef77c13652.jpg)
拍的图是清晰的,不知道怎么处理就成这样了

**Comment by zzdang** [comment]
![1562302810](https://user-images.githubusercontent.com/22818954/88132815-05aead00-cc13-11ea-8049-866b99d364cc.jpg)

**Comment by littletomatodonkey** [comment]
好的，谢谢你的反馈，如果要跑demo的话，easy edge提供的app demo应该是没问题的，这个自带相机拍照模糊的问题，我们先看下哈

**Comment by LDOUBLEV** [comment]
fix  in https://github.com/PaddlePaddle/PaddleOCR/pull/397
