### ISSUE TITLE
新版本检测模型如何训练

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#3950]
请问新版本检测模型训练，只替换配置文件和预训练模型可以吗？  还有什么参数需要设置吗？

**Comment by MissPenguin** [comment]
是的，换配置就可以了哈。后面我们再优化下文档说明下～

**Comment by Dandelion111** [comment]
直接换配置好像不太行，新配置文件和之前的格式不太一样

**Comment by Dandelion111** [comment]
> 是的，换配置就可以了哈。后面我们再优化下文档说明下～

直接换配置好像不太行，新配置文件和之前的格式不太一样
NetWorks:
  Student:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: MobileNetV3
      scale: 0.5
      model_name: large
      disable_se: true
    Neck:
      name: DBFPN
      out_channels: 96
    Head:
      name: DBHead
      k: 50
  Student2:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: MobileNetV3
      scale: 0.5
      model_name: large
      disable_se: true
    Neck:
      name: DBFPN
      out_channels: 96
    Head:
      name: DBHead
      k: 50
  Teacher:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: ResNet
      layers: 18
    Neck:
      name: DBFPN
      out_channels: 256
    Head:
      name: DBHead
      k: 50

**Comment by MissPenguin** [comment]
有具体报错吗

**Comment by Dandelion111** [comment]
![F LLJ9} )M 4A9FE{ {J899](https://user-images.githubusercontent.com/48303408/132616254-37eda67e-942e-4398-a215-edeca93bca59.png)
![F0 JZ5BY4L0SIV(YS7~TVVL](https://user-images.githubusercontent.com/48303408/132616267-ca78207a-7523-48a4-b39e-8ddf94d2d615.png)
配置文件是用的预训练模型里面带的config.yml
