### ISSUE TITLE
about the Enhanced CTC Loss

### ISSUE THREAD

**Issue by Danee-wawawa** [PaddlePaddle/PaddleOCR#3953]
Hi, thank you for your work. It is very useful.
I want to know where is the implementation code of the Enhanced CTC loss?
Looking forward for your answer.

**Comment by Intsigstephon** [comment]
The code of the Enhanced CTC loss is be arranging  It will be open sourced soon

**Comment by Danee-wawawa** [comment]
OK, looking forward to it.

**Comment by Danee-wawawa** [comment]
Hi, when the code of the Enhanced CTC loss being open sourced?
