### ISSUE TITLE
PP-OCRv2 Table 2 的数值有误

### ISSUE THREAD

**Issue by Sanster** [PaddlePaddle/PaddleOCR#3955]
第二行的 hmean 结果不对，目测可能是 precision 写错了
<img width="928" alt="截屏2021-09-07 下午9 02 24" src="https://user-images.githubusercontent.com/3998421/132349927-f34930d2-1d1b-459a-adc7-b98c4f8a75f4.png">

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，我们更新下，应该是0.743

**Comment by LDOUBLEV** [comment]
感谢指正，精度已更新
<img width="683" alt="eea1b8697426f8b11d7ad5d3717f84f1" src="https://user-images.githubusercontent.com/26592129/132355372-82f4644f-1326-4132-b88d-020d1cf6111b.png">
