### ISSUE TITLE
关于 PP-OCRv2 完全不添加真实数据的性能

### ISSUE THREAD

**Issue by Sanster** [PaddlePaddle/PaddleOCR#3957]
如 Table 1 所示，检测和识别都使用了万/百万级别的真实数据，想了解下是否测试过完全使用合成数据在的性能？谢谢

![image](https://user-images.githubusercontent.com/3998421/132350453-1b66d60e-1c55-4efc-b2e4-9a12170353dc.png)

**Comment by littletomatodonkey** [comment]
最早的时候做过实验，添加真实数据可以带来15%左右的精度提升，后来再优化的时候就没有做过更加具体的消融实验了

**Comment by Sanster** [comment]
thanks
