### ISSUE TITLE
想使用官方SDK，序列号怎么申请呀。申请时还要上传模型什么的？

### ISSUE THREAD

**Issue by AaronYin0514** [PaddlePaddle/PaddleOCR#396]

**Comment by dyning** [comment]
请再明确下您的需求。

**Comment by AaronYin0514** [comment]
/**
 * 设置序列号，请在官网获得序列号之后填写在此处
 * @param serialNumber 序列号
 */
+ (void)setSerialNumber:(NSString *)serialNumber;

这个序列号怎样获取

**Comment by dyning** [comment]
这个是哪个文件中的信息？

**Comment by AaronYin0514** [comment]
官方SDK的接口里面。
https://ai.baidu.com/easyedge/app/openSource?from=paddlelite
在这下载的SDK

**Comment by chenxiaoyu3** [comment]
开源模型的sdk不需要设置序列号就可以使用

**Comment by AaronYin0514** [comment]
在Demo中可以使用，不过不知道能不能用在正式版的APP上
