### ISSUE TITLE
C++ demo read image fail (Version 2.3)

### ISSUE THREAD

**Issue by shisenxd** [PaddlePaddle/PaddleOCR#3964]
main.cpp  line : 182

cv::Mat srcimg = cv::imread(FLAGS_image_dir, cv::IMREAD_COLOR);

param should be image_path

**Comment by shisenxd** [comment]
另外预测库是用官方发布的 2.1.1 吗, demo 自带的图片, paddleocr2.3+paddle2.1.1 耗时大概1.6, paddleocr2.1.0+paddle2.1.0 耗时大概1.3. 有什么特别需要注意的地方吗,

**Comment by LDOUBLEV** [comment]
182行改为：cv::Mat srcimg = cv::imread(cv_all_img_names[i], cv::IMREAD_COLOR); 
这个问题刚修复了

> 另外预测库是用官方发布的 2.1.1 吗, demo 自带的图片, paddleocr2.3+paddle2.1.1 耗时大概1.6, paddleocr2.1.0+paddle2.1.0 耗时大概1.3. 有什么特别需要注意的地方吗,

单张图像预测的时候，要完成初始化等操作，初始化之后从第二张图开始就会变快很多，可以尝试下

**Comment by coder-sun** [comment]
> 182行改为：cv::Mat srcimg = cv::imread(cv_all_img_names[i], cv::IMREAD_COLOR);
> 这个问题刚修复了
> 
> > 另外预测库是用官方发布的 2.1.1 吗, demo 自带的图片, paddleocr2.3+paddle2.1.1 耗时大概1.6, paddleocr2.1.0+paddle2.1.0 耗时大概1.3. 有什么特别需要注意的地方吗,
> 
> 单张图像预测的时候，要完成初始化等操作，初始化之后从第二张图开始就会变快很多，可以尝试下

怎么改成先加载模型，然后一张一张的推理图片呢
