### ISSUE TITLE
关于版式分析的问题

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#3966]
使用官方的版式分析模型检测后结果如下：

![image](https://user-images.githubusercontent.com/40531744/132435507-9921cb5e-cdc1-4731-b5a9-01fa5c3447a6.png)
效果看起来并不是很好，上方Text部分检测为List了，以及Table并没有完全框住这个表格，不知道具体是什么原因？
然后应该是需要重新训练吗？
另外请教一下list代表的是什么，我理解好像只有table、text、figure、title四个类别好像就可以了？

**Comment by littletomatodonkey** [comment]
你好，数据类别定义可以在publayernet数据集中查看：https://arxiv.org/pdf/1908.07836.pdf
另外，我们训练的数据集主要是英文的哈，直接用在中文上，效果可能会稍微差一些~

**Comment by hhhhhhogan** [comment]
> 你好，数据类别定义可以在publayernet数据集中查看：https://arxiv.org/pdf/1908.07836.pdf
> 另外，我们训练的数据集主要是英文的哈，直接用在中文上，效果可能会稍微差一些~

好的，感谢回复。那我重新训练看看效果~

**Comment by buptlihang** [comment]
> 使用官方的版式分析模型检测后结果如下：
> 
> ![image](https://user-images.githubusercontent.com/40531744/132435507-9921cb5e-cdc1-4731-b5a9-01fa5c3447a6.png)
> 效果看起来并不是很好，上方Text部分检测为List了，以及Table并没有完全框住这个表格，不知道具体是什么原因？
> 然后应该是需要重新训练吗？
> 另外请教一下list代表的是什么，我理解好像只有table、text、figure、title四个类别好像就可以了？







近期我会整理公开一个中文文档的版面分析数据集，感兴趣可以关注一下: [CDLA](https://github.com/buptlihang/CDLA)

**Comment by hhhhhhogan** [comment]
好的感谢@buptlihang

**Comment by zhentaoCoding** [comment]
> > 使用官方的版式分析模型检测后结果如下：
> > ![image](https://user-images.githubusercontent.com/40531744/132435507-9921cb5e-cdc1-4731-b5a9-01fa5c3447a6.png)
> > 效果看起来并不是很好，上方Text部分检测为List了，以及Table并没有完全框住这个表格，不知道具体是什么原因？
> > 然后应该是需要重新训练吗？
> > 另外请教一下list代表的是什么，我理解好像只有table、text、figure、title四个类别好像就可以了？
> 
> 近期我会整理公开一个中文文档的版面分析数据集，感兴趣可以关注一下: [CDLA](https://github.com/buptlihang/CDLA)

使用CDLA数据训练版面分析模型，代码需要做改动吗
