### ISSUE TITLE
paddle1.7 gpu服务器训练好的模型，如何部署推理到只有cpu的服务器 

### ISSUE THREAD

**Issue by mppsk0** [PaddlePaddle/PaddleOCR#3973]

**Comment by LDOUBLEV** [comment]
配置inference config的时候disable_gpu()

https://github.com/PaddlePaddle/PaddleOCR/blob/6b44a969d319307d42c1d0c5fdc6171514258f2d/tools/infer/utility.py#L128

**Comment by mppsk0** [comment]
试过了没有用，启动模型变成core dumped
