### ISSUE TITLE
pdserver部署遇到问题

### ISSUE THREAD

**Issue by LithubCN** [PaddlePaddle/PaddleOCR#3975]
# 启动服务，运行日志保存在log.txt
python3 web_service.py &>log.txt &

执行这句话之后什么啥都没有

log.txt就只有这句话
2021/09/08 16:02:09 start proxy service

请问是什么原因

**Comment by tink2123** [comment]
查看一下 PipelineServingLogs/pipeline.log 里面有没有更多的报错信息呢？
