### ISSUE TITLE
PaddleLable相关报错

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleOCR#3977]
![IMG_0832](https://user-images.githubusercontent.com/57340568/132474248-f608829e-dc5a-4569-b33c-b55fb99fa7f5.JPG)
请问这个问题是什么原因导致的？网上查说是cudnn不匹配，但我用的是cpu版本的paddlepaddle

**Comment by TD-wzw** [comment]
然后还想问一下，这个工具代码的阈值在哪里设置，想把box检测阈值设低一点

**Comment by Evezerest** [comment]
如果上面的报错信息是cv2下的opencv，可能是opencv版本太高，可以查看文档：https://github.com/Evezerest/PPOCRLabel/blob/dygraph/README_ch.md#%E9%94%99%E8%AF%AF%E6%8F%90%E7%A4%BA

**Comment by TD-wzw** [comment]
> 如果上面的报错信息是cv2下的opencv，可能是opencv版本太高，可以查看文档：https://github.com/Evezerest/PPOCRLabel/blob/dygraph/README_ch.md#%E9%94%99%E8%AF%AF%E6%8F%90%E7%A4%BA

感谢，换成4.2的opencv以后确实可以用了
