### ISSUE TITLE
有没有API reference

### ISSUE THREAD

**Issue by Legend94rz** [PaddlePaddle/PaddleOCR#3978]
开发靠猜吗？

**Comment by LDOUBLEV** [comment]
对，我们都是闭眼开发，天亮了代码就自己写好了

不想猜的话可以在Paddle Paddle主页找到相关API文档！
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html

**Comment by MissPenguin** [comment]
可以在Paddle Paddle主页找到相关API文档！
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html

**Comment by Legend94rz** [comment]
有PaddleOCR 的API reference吗？

**Comment by ioracion** [comment]
核心的文件就几个（tools文件夹下），要改啥自己多花时间看看就懂了
