### ISSUE TITLE
请问如何对HWDB2.0数据集进行解析

### ISSUE THREAD

**Issue by yxhnjust** [PaddlePaddle/PaddleOCR#398]
如题，我希望知道如何对HWDB2.0手写数据集进行解析，并且知道更多的训练细节，比如cpu环境下的batchsize和lr

**Comment by tink2123** [comment]
1. 数据解析
将解压后的数据放在 `PaddleOCR/train_data` 目录下，提取图像并创建label，以测试集为例：
```
import struct
import os
import cv2 as cv
import numpy as np


def read_from_agrl(dgrls):
    if not os.path.exists(dgrls):
        print('DGRL not exis!')
        return

    f1 = open('./test_label.txt', 'w')

    for root, dirs, files in os.walk(dgrls):
        for dgrl in files:
            dir_name = root
            base_name = dgrl
            image_dir = dir_name + '_images'

            if not os.path.exists(image_dir):
                os.makedirs(image_dir)

            with open(os.path.join(root,dgrl), 'rb') as f:
                # 读取表头尺寸
                header_size = np.fromfile(f, dtype='uint8', count=4)
                header_size = sum([j << (i * 8) for i, j in enumerate(header_size)])
                # print(header_size)

                # 读取表头剩下内容，提取 code_length
                header = np.fromfile(f, dtype='uint8', count=header_size - 4)
                code_length = sum([j << (i * 8) for i, j in enumerate(header[-4:-2])])
                # print(code_length)

                # 读取图像尺寸信息，提取图像中行数量
                image_record = np.fromfile(f, dtype='uint8', count=12)
                height = sum([j << (i * 8) for i, j in enumerate(image_record[:4])])
                width = sum([j << (i * 8) for i, j in enumerate(image_record[4:8])])
                line_num = sum([j << (i * 8) for i, j in enumerate(image_record[8:])])
                print('图像尺寸:')
                print(height, width, line_num)

                # 读取每一行的信息
                for k in range(line_num):
                    print(k + 1)

                    # 读取该行的字符数量
                    char_num = np.fromfile(f, dtype='uint8', count=4)
                    char_num = sum([j << (i * 8) for i, j in enumerate(char_num)])
                    print('字符数量:', char_num)

                    # 读取该行的标注信息
                    label = np.fromfile(f, dtype='uint8', count=code_length * char_num)
                    label = [label[i] << (8 * (i % code_length)) for i in range(code_length * char_num)]
                    label = [sum(label[i * code_length:(i + 1) * code_length]) for i in range(char_num)]
                    label = [struct.pack('I', i).decode('gbk', 'ignore')[0] for i in label]
                    print('合并前：', label)
                    label = ''.join(label)
                    label = ''.join(label.split(b'\x00'.decode()))  # 去掉不可见字符 \x00，这一步不加的话后面保存的内容会出现看不见的问题
                    print('合并后：', label)

                    # 读取该行的位置和尺寸
                    pos_size = np.fromfile(f, dtype='uint8', count=16)
                    y = sum([j << (i * 8) for i, j in enumerate(pos_size[:4])])
                    x = sum([j << (i * 8) for i, j in enumerate(pos_size[4:8])])
                    h = sum([j << (i * 8) for i, j in enumerate(pos_size[8:12])])
                    w = sum([j << (i * 8) for i, j in enumerate(pos_size[12:])])
                    # print(x, y, w, h)

                    # 读取该行的图片
                    bitmap = np.fromfile(f, dtype='uint8', count=h * w)
                    bitmap = np.array(bitmap).reshape(h, w)

                    # 图片路径
                    pic_path = os.path.join(image_dir, base_name.replace('.dgrl', '_' + str(k) + '.jpg'))
                    # 写入label
                    f1.write(pic_path+'\t'+label+'\n')
                    bitmap_file = os.path.join(image_dir, base_name.replace('.dgrl', '_' + str(k) + '.jpg'))
                    cv.imwrite(bitmap_file, bitmap)

if __name__ == "__main__":
    read_from_agrl('HWDB2.0Test')
```

2. 修改 `PaddleOCR/configs/rec/rec_chinese_reader.yml`
```
TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 1 #cpu 设置为1
  img_set_dir: ./train_data 
  label_file_path: ./train_data/test_label.txt # 修改成自己的label文件
```

3. 加载中文预训练模型，启动训练 建议选择机器能承担的较大 batch size，128/64/32 等等， 学习率设为0.0001

**Comment by yxhnjust** [comment]
> 1. 数据解析
>    将解压后的数据放在 `PaddleOCR/train_data` 目录下，提取图像并创建label，以测试集为例：
> 
> ```
> import struct
> import os
> import cv2 as cv
> import numpy as np
> 
> 
> def read_from_agrl(dgrls):
>     if not os.path.exists(dgrls):
>         print('DGRL not exis!')
>         return
> 
>     f1 = open('./test_label.txt', 'w')
> 
>     for root, dirs, files in os.walk(dgrls):
>         for dgrl in files:
>             dir_name = root
>             base_name = dgrl
>             image_dir = dir_name + '_images'
> 
>             if not os.path.exists(image_dir):
>                 os.makedirs(image_dir)
> 
>             with open(os.path.join(root,dgrl), 'rb') as f:
>                 # 读取表头尺寸
>                 header_size = np.fromfile(f, dtype='uint8', count=4)
>                 header_size = sum([j << (i * 8) for i, j in enumerate(header_size)])
>                 # print(header_size)
> 
>                 # 读取表头剩下内容，提取 code_length
>                 header = np.fromfile(f, dtype='uint8', count=header_size - 4)
>                 code_length = sum([j << (i * 8) for i, j in enumerate(header[-4:-2])])
>                 # print(code_length)
> 
>                 # 读取图像尺寸信息，提取图像中行数量
>                 image_record = np.fromfile(f, dtype='uint8', count=12)
>                 height = sum([j << (i * 8) for i, j in enumerate(image_record[:4])])
>                 width = sum([j << (i * 8) for i, j in enumerate(image_record[4:8])])
>                 line_num = sum([j << (i * 8) for i, j in enumerate(image_record[8:])])
>                 print('图像尺寸:')
>                 print(height, width, line_num)
> 
>                 # 读取每一行的信息
>                 for k in range(line_num):
>                     print(k + 1)
> 
>                     # 读取该行的字符数量
>                     char_num = np.fromfile(f, dtype='uint8', count=4)
>                     char_num = sum([j << (i * 8) for i, j in enumerate(char_num)])
>                     print('字符数量:', char_num)
> 
>                     # 读取该行的标注信息
>                     label = np.fromfile(f, dtype='uint8', count=code_length * char_num)
>                     label = [label[i] << (8 * (i % code_length)) for i in range(code_length * char_num)]
>                     label = [sum(label[i * code_length:(i + 1) * code_length]) for i in range(char_num)]
>                     label = [struct.pack('I', i).decode('gbk', 'ignore')[0] for i in label]
>                     print('合并前：', label)
>                     label = ''.join(label)
>                     label = ''.join(label.split(b'\x00'.decode()))  # 去掉不可见字符 \x00，这一步不加的话后面保存的内容会出现看不见的问题
>                     print('合并后：', label)
> 
>                     # 读取该行的位置和尺寸
>                     pos_size = np.fromfile(f, dtype='uint8', count=16)
>                     y = sum([j << (i * 8) for i, j in enumerate(pos_size[:4])])
>                     x = sum([j << (i * 8) for i, j in enumerate(pos_size[4:8])])
>                     h = sum([j << (i * 8) for i, j in enumerate(pos_size[8:12])])
>                     w = sum([j << (i * 8) for i, j in enumerate(pos_size[12:])])
>                     # print(x, y, w, h)
> 
>                     # 读取该行的图片
>                     bitmap = np.fromfile(f, dtype='uint8', count=h * w)
>                     bitmap = np.array(bitmap).reshape(h, w)
> 
>                     # 图片路径
>                     pic_path = os.path.join(image_dir, base_name.replace('.dgrl', '_' + str(k) + '.jpg'))
>                     # 写入label
>                     f1.write(pic_path+'\t'+label+'\n')
>                     bitmap_file = os.path.join(image_dir, base_name.replace('.dgrl', '_' + str(k) + '.jpg'))
>                     cv.imwrite(bitmap_file, bitmap)
> 
> if __name__ == "__main__":
>     read_from_agrl('HWDB2.0Test')
> ```
> 
> 1. 修改 `PaddleOCR/configs/rec/rec_chinese_reader.yml`
> 
> ```
> TrainReader:
>   reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
>   num_workers: 1 #cpu 设置为1
>   img_set_dir: ./train_data 
>   label_file_path: ./train_data/test_label.txt # 修改成自己的label文件
> ```
> 
> 1. 加载中文预训练模型，启动训练 建议选择机器能承担的较大 batch size，128/64/32 等等， 学习率设为0.0001

使用了这种方法进行解析，loss依旧没有呈现下降趋势，请问数据字典和中文预训练权重以及数据字典是如何设置原则的，loss一直是5000多左右波动。

**Comment by xxllp** [comment]
@yxhnjust  你训练的是识别嘛

**Comment by yxhnjust** [comment]
> @yxhnjust 你训练的是识别嘛

是的
