### ISSUE TITLE
> > > > 这个0.5吧

### ISSUE THREAD

**Issue by HaodiFan** [PaddlePaddle/PaddleOCR#3984]
> > > > 这个0.5吧
> > > 
> > > 
> > > 使用了如下数据集构成：
> > > 百度中文场景文字识别 205663
> > > icdar2015 2015
> > > SROIE: 18000
> > > Synthetic Chinese String Dataset(360万中文数据集)： 970000
> > > *(自己合成）搜狗词汇中随机位置插入字符： 1103588
> > > **evaluation 集和训练集的比例为1.5%：97%
> > > 训练了3个epoch
> > > 训练结果：
> > > 1）训练精度远远比不上paddle官方提供的server端的rec精度
> > > 2）训练精度
> > > 随即我就去测试了一下预训练的rec模型的精度发现什么都识别不出来
> > > 问题：
> > > 对预训练模型的finetune和从头训练感觉效果上差不多？
> > > 如何才能保证原识别率的状态下finetune？
> > 
> > 
> > 你修改字典了吗？
> 
> 替换了两个生僻字，但字典的总数没变，然后针对替换后的字符进行训练的😀

_Originally posted by @ryaoyu in https://github.com/PaddlePaddle/PaddleOCR/issues/2856#issuecomment-915692640_

**Comment by tink2123** [comment]
可能是因为训练数据太多，并且太简单。可以把eval迭代的频率调高一点，并且在训练集里添加尽量高比例的真实数据。

**Comment by ryaoyu** [comment]
已收到您的来信，谢谢。
