### ISSUE TITLE
SAST模型推理

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3987]
SAST模型推理时检测框会斜着是怎么回事呢，两行文本会检测串了，会出现好多这种情况

**Comment by tink2123** [comment]
在推理的时候有没有指定 --det_algorithm="SAST"

**Comment by lalalagogogochong** [comment]
> 在推理的时候有没有指定 --det_algorithm="SAST"

这个参数设置了，上传图片不知道为啥上传不了 ，就是有一些密集一点的图片，会检测错行

**Comment by lalalagogogochong** [comment]
> > 在推理的时候有没有指定 --det_algorithm="SAST"
> 
> 这个参数设置了，上传图片不知道为啥上传不了 ，就是有一些密集一点的图片，会检测错行
类似于这张图片里的检测结果
https://user-images.githubusercontent.com/49063302/123933770-45eee180-d9c5-11eb-9259-f9552d62e996.png

**Comment by lalalagogogochong** [comment]
> > > 在推理的时候有没有指定 --det_algorithm="SAST"
> > 
> > 
> > 这个参数设置了，上传图片不知道为啥上传不了 ，就是有一些密集一点的图片，会检测错行
> > 类似于这张图片里的检测结果
> > https://user-images.githubusercontent.com/49063302/123933770-45eee180-d9c5-11eb-9259-f9552d62e996.png

@tink2123 老师，麻烦您看一下，这个是模型本身存在的问题吗，还是训练的时候参数设置有问题
