### ISSUE TITLE
PP-OCRv2 支持C++部署吗，支持转成onnx吗

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/PaddleOCR#3991]
如题

**Comment by tink2123** [comment]
支持C++部署，可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/cpp_infer
可以转成onnx，百度上有很多教程可以参考，但是不推荐。

**Comment by coder-sun** [comment]
> 支持C++部署，可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/cpp_infer
> 可以转成onnx，百度上有很多教程可以参考，但是不推荐。

C++部署编译后的每次预测都要加载一次模型，可不可以把加载模型和预测分开呢？
