### ISSUE TITLE
PaddleLable标注工具相关

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleOCR#3993]
请问如果我只想标注文本检测的标签，不想用到识别的话，需要怎么修改？

**Comment by Evezerest** [comment]
只标记文本，不改识别结果就好，直接导出标记记过就是了

**Comment by TD-wzw** [comment]
不好意思我没表达清楚
我想问的是，打开文件夹一开始自动标注，自动标注的过程中文本检测和识别都进行了，会比较慢，现在我只想标注文本检测的位置信息，不需要识别的标签，请问下这个该怎么改，是需要改代码吗？

**Comment by TD-wzw** [comment]
目前我的标注流程是：
1.打开文件夹进行自动标注
2.对自动标注过后的标签进行微调然后导出
目前的问题是：在自动标注的时候我就只想要标注检测的位置信息（四个点），不需要crnn进行识别，想提高一下自动标注的速度

**Comment by ioracion** [comment]
1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
2.把识别模型换成超轻量的，加快识别速度

**Comment by TD-wzw** [comment]
> 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> 2.把识别模型换成超轻量的，加快识别速度

就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲

**Comment by ioracion** [comment]
> > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > 2.把识别模型换成超轻量的，加快识别速度
> 
> 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲

简单，学好python，有了基础再来，不然你这样一直事倍功半

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

你如果一直这么喜欢说废话的话其实可以不用回复这个issues

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

方便的话留下联系方式我跟您私聊请教一下您？

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

除了放点没有用的屁你还能干点啥呢大兄弟，挺大个脑瓜子长你脖子上算白长了呗？

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

如果没有开关直接控制，这个东西代码我肯定会自己看，针对你放的这个没有用的屁呢大兄弟，我就想问问你个逼养的色蓝，你还缺不缺父亲了？不行我去给你当一下子吧？

**Comment by ioracion** [comment]
就这口吐芬芳的素质，算了吧您。issue开开关关、“芬芳”话语发发删删，气急败坏的样子极其好笑。这个就留给后来者看看。

![截图](https://user-images.githubusercontent.com/17641924/134642745-2dc5dd47-1d11-49a7-825f-34d56f3699e9.jpg)

**Comment by TD-wzw** [comment]
> 就这口吐芬芳的素质，算了吧您。issue开开关关、“芬芳”话语发发删删，气急败坏的样子极其好笑。这个就留给后来者看看。
> 
> ![截图](https://user-images.githubusercontent.com/17641924/134642745-2dc5dd47-1d11-49a7-825f-34d56f3699e9.jpg)

发了删本意就是只让你看到为父教育你，乖儿子要贴出来那为父也就不删了，宝贝儿子除了放没用的屁以外，应该还会放没用的屁，可以让你后边的叔父们看下

**Comment by Evezerest** [comment]
请大家和谐交流
只需要检测的话可以在 [这里](https://github.com/PaddlePaddle/PaddleOCR/blob/7cd100254354b7251e803c4be3aae142ab8eb3f7/PPOCRLabel/libs/autoDialog.py#L41) 传入rec=False 但可能会由于没有识别结果而出现其他报错，这个我们还没有测试过

**Comment by TD-wzw** [comment]
> 请大家和谐交流
> 只需要检测的话可以在 [这里](https://github.com/PaddlePaddle/PaddleOCR/blob/7cd100254354b7251e803c4be3aae142ab8eb3f7/PPOCRLabel/libs/autoDialog.py#L41) 传入rec=False 但可能会由于没有识别结果而出现其他报错，这个我们还没有测试过

谢谢大佬，已经改好了

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半
儿子你好：
看到了么？上边你那位叔叔的回答才是正常人说的话。
不会你可以说不会，不愿意告诉我那也是你的权力，你可以不搭理我或者直接说你不愿意告诉我这个，我不带说你半个不字儿，
然而你个狗篮子上来就开始教育，崩点儿没有用的屁你感觉你自己行了？
issues是用来提问的，问与答都直接一点不好？会与不会，有或没有，愿意告知或者不愿意告知，你这种乐意说教别人并且装犊子的逼玩意儿别人该咋说你呢？嗯？
我还是想再和你说一句操你妈
最后当然了，我也为自己对你的辱骂进行道歉，对不起好儿，为父确实不该这么骂你，这次是为父错了，下次再遇到你还骂。

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半
儿子你好：
看到了么？上边你那位叔叔的回答才是正常人说的话。
不会你可以说不会，不愿意告诉我那也是你的权力，你可以不搭理我或者直接说你不愿意告诉我这个，我不带说你半个不字儿，
然而你个狗篮子上来就开始教育，崩点儿没有用的屁你感觉你自己行了？
issues是用来提问的，问与答都直接一点不好？会与不会，有或没有，愿意告知或者不愿意告知，你这种乐意说教别人并且装犊子的逼玩意儿别人该咋说你呢？嗯？
我还是想再和你说一句操你妈
最后当然了，我也为自己对你的辱骂进行道歉，对不起好儿，为父确实不该这么骂你，这次是为父错了，下次再遇到你还骂。

**Comment by TD-wzw** [comment]
> > > 1.修改源码，把那识别部分屏蔽掉，或者用固定数值代替识别
> > > 2.把识别模型换成超轻量的，加快识别速度
> > 
> > 
> > 就是想问下，修改源码把识别部分屏蔽掉应该怎么该一下，对QT那些有点不太懂，代码看着有点费劲
> 
> 简单，学好python，有了基础再来，不然你这样一直事倍功半

亲爱的好儿，上一条你应该已经看到了，为父接着删了哈，别让人家管理员为难，你想贴出来就继续
