### ISSUE TITLE
请问有办法支持识别左右颠倒的文字吗

### ISSUE THREAD

**Issue by icesword95** [PaddlePaddle/PaddleOCR#3996]
了解原理后看到方向识别器只支持上下颠倒，如果有左右镜像（还包括上下颠倒+左右镜像）的情况有办法用正确的顺序训练吗？训练后测试集的正确率远低于验证集会和这有关吗？

**Comment by tink2123** [comment]
横向文本的读取顺序是从左向右，预测结果顺序与图片顺序一致。如果需要反向识别，可以单独训练方向分类器，并做手动反转。

**Comment by icesword95** [comment]
> 横向文本的读取顺序是从左向右，预测结果顺序与图片顺序一致。如果需要反向识别，可以单独训练方向分类器，并做手动反转。

那现在的方向识别器有这个功能吗？我看只有上下，那是得自己修改方向器吗

**Comment by ioracion** [comment]
好好看配置文件，本来就上下2个label，你再加左右2个label从头训练个模型就好了

**Comment by icesword95** [comment]
> 好好看配置文件，本来就上下2个label，你再加左右2个label从头训练个模型就好了

除了标签还得修改下后处理吧？出来的图片还要根据标签做旋转和翻转，请问这部分的代码是在哪里？

**Comment by ioracion** [comment]
根据你能找到的代码，比如文件的main函数，一步步往源头找。这个得慢慢来
