### ISSUE TITLE
预测时cpu模式下cpu占用高

### ISSUE THREAD

**Issue by sdnusqy-art** [PaddlePaddle/PaddleOCR#3997]
是否可以设置cpu占用核数，默认情况占用很高，如何进行？

**Comment by tink2123** [comment]
是指训练的时候还是预测的时候呢？有以下两个方式可以减小内存占用：
1. 减小 batch_size
2. 去掉多进程

**Comment by sdnusqy-art** [comment]
> 是指训练的时候还是预测的时候呢？有以下两个方式可以减小内存占用：
> 
> 1. 减小 batch_size
> 2. 去掉多进程

我是说的cpu利用率不是内存， 是在预测时的cpu利用率很高，是否可以设置cpu占用核数？
