### ISSUE TITLE
端测打包android demo时一直提示找不到OpenCV_DIR信息

### ISSUE THREAD

**Issue by tangmq** [PaddlePaddle/PaddleOCR#400]
端测打包android demo时一直提示找不到OpenCV_DIR信息，但我实际在env中是有配置的，不知道是什么原因
![481595411109_ pic](https://user-images.githubusercontent.com/5723629/88162585-16c3e200-cc44-11ea-9d40-f37f2e3365e1.jpg)
![421595410816_ pic](https://user-images.githubusercontent.com/5723629/88162602-1d525980-cc44-11ea-899c-cc7ea3a933c8.jpg)

**Comment by tink2123** [comment]
点击一下编译，然后退出项目，再进入应该就可以了～试一下

**Comment by tangmq** [comment]
找到问题了，因为第一次run的时候，因为公司网络不太好，导致下载了一个解压错误的包（只解压出一部分文件，正好没有opencv）。从github重拉一次代码，然后找网络好的环境重新拉一次就好了。
