### ISSUE TITLE
文本检测训练时，log中没有输出loss等评估信息，并且一直没有出现best_accuracy模型，请问是我yml配置的有问题吗?

### ISSUE THREAD

**Issue by wangkailun** [PaddlePaddle/PaddleOCR#4005]
log信息一直重复这两行
![image](https://user-images.githubusercontent.com/19208269/132786293-e22e4be2-adf9-4659-8cbf-a4a3044410b4.png)

yml配置信息
![image](https://user-images.githubusercontent.com/19208269/132786439-b6e2648b-ff42-4222-9347-7aaff8e635a7.png)

生成的模型列表没有best_accuracy:
![image](https://user-images.githubusercontent.com/19208269/132785776-c0d100ea-d1e2-4c1e-974e-e5a9646a0b82.png)

各位大佬帮忙看一下，我配置文件哪里写错了吗？我记得第一次用官方的数据集训练是有loss信息的。

**Comment by WenmuZhou** [comment]
你的数据量太少了，没有达到输出log和eval模型的次数

**Comment by wangkailun** [comment]
确实是这样，增加数据量之后就正常了，感谢。

**Comment by wangkailun** [comment]
> 你的数据量太少了，没有达到输出log和eval模型的次数

**Comment by wangkailun** [comment]
确实是这样，增加数据量之后就正常了，感谢。
