### ISSUE TITLE
PP-OCRv2模型推理报错

### ISSUE THREAD

**Issue by ycdhqzhiai** [PaddlePaddle/PaddleOCR#4007]
版本：
+ RaddleOCR:release/2.3
+ Paddle预测库：
```
GIT COMMIT ID: 5c7ad3bcb482dd93ea21b3b66b5a7ff964e0f239
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 11.0
CUDNN version: v8.0
CXX compiler version: 8.2.0
WITH_TENSORRT: ON
TensorRT version: v7
```
+ tensorrt:7.2.3
+ CUDA: 11.1 
运行cpp_infer报错：
![image](https://user-images.githubusercontent.com/12273405/132805499-82abb757-9974-4ee6-93fc-3b0bd5e47bcb.png)

**Comment by WenmuZhou** [comment]
试一下新的代码看看
