### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#4008]
![~R2U~6V}8CFBDDP9056F N6](https://user-images.githubusercontent.com/65577659/132808713-c70363ac-b07c-411b-99bb-ec6a7ebf072f.jpg)
请问一下这种格式的预训练模型是基于什么数据呢? 还提供吗?

**Comment by WenmuZhou** [comment]
这种是paddleclas静态图的预训练模型，目前动态图模式下不建议使用，建议使用paddleclas动态图的预训练

**Comment by lin-0015** [comment]
好滴~ 谢谢
