### ISSUE TITLE
slim 模型精度

### ISSUE THREAD

**Issue by chiaitian** [PaddlePaddle/PaddleOCR#4010]
请问slim模型都做了哪些操作，slim模型的大小在lite端下降很多，模型的精度和原始模型相差多少？

**Comment by WenmuZhou** [comment]
slim精度和inference模型差不多，少部分会更高

**Comment by chiaitian** [comment]
谢谢回复！那lite端的模型size比较小，prune和quant应该都有使用吧

**Comment by WenmuZhou** [comment]
是的
