### ISSUE TITLE
python脚本预测，如何关闭控制台的额外输出

### ISSUE THREAD

**Issue by BlueWinters** [PaddlePaddle/PaddleOCR#4012]
![image](https://user-images.githubusercontent.com/16732444/132816074-0dbbe2fb-d700-440b-984c-91e3a3702f44.png)

**Comment by WenmuZhou** [comment]
这个好像没法关闭

**Comment by BlueWinters** [comment]
是paddlepaddle本身的原因吗？

**Comment by WenmuZhou** [comment]
可以查询一下paddle官网的log相关参数看看

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/3929 参考这个pr
