### ISSUE TITLE
DB检测算法支持的数据标注

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#4013]
请问，db检测算法除了支持4点标注，支持14点标注吗？希望能通过14点标注来检测印章文字，如果有别的更好的思路，还希望大佬指教指教。
另外，PGNet训练的话，没有大量字符的数据集，训练几个epoch，效果并不是很理想。

**Comment by WenmuZhou** [comment]
17个点理论是支持的，不支持的话，需要改一下数据处理和后处理部分，不难
