### ISSUE TITLE
How to convert checkpoint table recognition to onnx

### ISSUE THREAD

**Issue by cnxdeveloper** [PaddlePaddle/PaddleOCR#4015]
dear authors
i am very excited with your table structure. but i can't convert it to ONNX. I used framework PADDLE2ONNX offical. Please help me to do this.

**Comment by WenmuZhou** [comment]
what error msg received

**Comment by cnxdeverloper** [comment]
> what error msg received

The error msg
NotImplementedError: 
There's 9 ops are not supported yet
=========== write_to_array ===========
=========== tensor_array_to_tensor ===========
=========== less_than ===========
=========== select_input ===========
=========== lod_array_length ===========
=========== conditional_block ===========
=========== one_hot_v2 ===========
=========== while ===========
=========== logical_not ===========

**Comment by WenmuZhou** [comment]
It looks like there are 9 ops that don't support converting onnx
