### ISSUE TITLE
关于PP-OCRv2版本中的文本识别技术相关问题

### ISSUE THREAD

**Issue by Danee-wawawa** [PaddlePaddle/PaddleOCR#4016]
您好，非常感谢你们的工作。关于PP-OCRv2版本中的文本识别技术我有一个问题，如下：
![image](https://user-images.githubusercontent.com/24379250/132818361-987aa44f-197e-4e9c-89b9-09d82d5410ea.png)
在文档中提到了Feature Map Resolution，能否具体解释下这个是指什么呢，还有相关代码实现部分是在哪里呢？
期待您的回答。

**Comment by littletomatodonkey** [comment]
你好，这是v1的策略，指的是减少一次降采样，让网络前向的feature map大一倍
