### ISSUE TITLE
Run paddleocr CPU on AWS cloud segmentation fault

### ISSUE THREAD

**Issue by cnxdeveloper** [PaddlePaddle/PaddleOCR#4017]
Dear author I tried run Paddle OCR on AWS cloud server. I got error Segmentation fault. I tried reinstall a lots of paddlepaddle-cpu versions. But It still not work, paddleocr ver 2.3.0.1, paddlepaddle ver 2.1.2. My output error:

--- Running analysis [ir_graph_to_program_pass]
I0910 09:50:52.969626 22710 analysis_predictor.cc:636] ======= optimize end =======
I0910 09:50:52.973817 22710 naive_executor.cc:98] ---  skip [feed], feed -> x
I0910 09:50:52.976850 22710 naive_executor.cc:98] ---  skip [batch_norm_4.tmp_3], fetch -> fetch
I0910 09:50:52.976873 22710 naive_executor.cc:98] ---  skip [conv2d_66.tmp_0], fetch -> fetch
E0910 09:50:52.977479 22710 analysis_config.cc:81] Please compile with gpu to EnableGpu()
---    Fused 0 subgraphs into layer_norm op.
(220, 1000, 3)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1631267455 (unix time) try "date -d @1631267455" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 22710 (TID 0x7f4ac1bc3740) from PID 0 ***]

Segmentation fault (core dumped)
Many thanks for any support

**Comment by WenmuZhou** [comment]
试一下cpu模式能不能跑 --use_gpu=false

**Comment by cnxdeverloper** [comment]
> 试一下cpu模式能不能跑 --use_gpu=false
I just install paddlepaddle cpu. I tried set use_gpu=false but it still not work

**Comment by Zhang-O** [comment]
> > 试一下cpu模式能不能跑 --use_gpu=false
> > I just install paddlepaddle cpu. I tried set use_gpu=false but it still not work

you do not need to install paddlepaddle-cpu.  what you should do is  just adding "--use_gpu=false" to your command line when you run predict_infer.

**Comment by cnxdeverloper** [comment]
> > > 试一下cpu模式能不能跑 --use_gpu=false
> > > I just install paddlepaddle cpu. I tried set use_gpu=false but it still not work
> 
> you do not need to install paddlepaddle-cpu. what you should do is just adding "--use_gpu=false" to your command line when you run predict_infer.

i did it. But it not working. But I use paddle docker problem is solved. I don't know why. I compared system AWS with system paddle docker. It's not diffrence.

**Comment by WenmuZhou** [comment]
maybe gcc version diffrence
