### ISSUE TITLE
C++推理开启MKL速度推理速度变慢

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#4019]
cpu环境如上图所示
![image](https://user-images.githubusercontent.com/25734125/132932854-1257d050-2ee3-410b-a497-225700874845.png)

tool/build.sh中MKL=NO

paddle_inference.tgz使用的是这个：
其余代码基本使用的都是2.3版本中默认的。
测试图片为../../doc/imgs/00015504.jpg
使用预测命令为：./build/ppocr system     --det_model_dir=inference1/ch_ppocr_mobile_v2.0_det_infer     --rec_model_dir=inference1/ch_ppocr_mobile_v2.0_rec_infer  --enable_mkldnn=1   --image_dir=../../doc/imgs/00015504.jpg

开启mkl预测时间为2.4s，不开启mkl预测时间为1.8s。

**Comment by Gmgge** [comment]
单张图像测试时间不稳定，包含模型装载时间等，建议测试100张（当然50也行）计算平均时间。

**Comment by coder-sun** [comment]
> 单张图像测试时间不稳定，包含模型装载时间等，建议测试100张（当然50也行）计算平均时间。
打印的只有检测识别时间，模型加载写在了前面，这样推理时就排除掉了模型加载的时间。main.cpp文件是这么写的（有错误请指正，需要的是模型只加载一次，后面每次调用推理函数都不用再加载）：
[main.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7150724/main.txt)

**Comment by Gmgge** [comment]
可能是一些其他的问题，抱歉。

**Comment by coder-sun** [comment]
同样机器CPU环境下，都不开mkl，python推理速度大概是2.7s，C++是1.8s，不知道你们有没有相应的测试结果啊，求一份C++对比python推理速度提升多少的结果。

**Comment by Gmgge** [comment]
@coder-sun  今天测了下RapidOCR cpp+onnex+onnexRuntime比python快两倍左右。

**Comment by coder-sun** [comment]
> @coder-sun 今天测了下RapidOCR cpp+onnex+onnexRuntime比python快两倍左右。

我也测这个了，同样的硬件环境，同一张图片的平均时间：
paddle  python 2.7s，c++ 1.8s， 2.2s（c++开启mkl）
RapidOCR cpp+onnex+onnexRuntime 0.95s（不开启openmp），0.45s（开启openmp 4个线程）

paddle c++的框架推理速度还需要优化啊，开启mkl负优化有点懵逼

**Comment by Gmgge** [comment]
我拉了最新的代码跑了paddle的c++推理，现在开启mkl是加速了的。

**Comment by coder-sun** [comment]
> 我拉了最新的代码跑了paddle的c++推理，现在开启mkl是加速了的。

可以问下测试结果大概什么样吗，cpu下提升了多少

**Comment by Gmgge** [comment]
我使用的最新推出的服务端模型，测试13张图像，开启mkl减少时间在35%左右，可能测试的不太准确。

**Comment by littletomatodonkey** [comment]
测试的时候可以去掉前面几轮迭代的时间，warmup耗时较多，一般不稳定

**Comment by bigmover** [comment]
> > @coder-sun 今天测了下RapidOCR cpp+onnex+onnexRuntime比python快两倍左右。
> 
> 我也测这个了，同样的硬件环境，同一张图片的平均时间： paddle python 2.7s，c++ 1.8s， 2.2s（c++开启mkl） RapidOCR cpp+onnex+onnexRuntime 0.95s（不开启openmp），0.45s（开启openmp 4个线程）
> 
> paddle c++的框架推理速度还需要优化啊，开启mkl负优化有点懵逼

如何开启openmp 在我的环境设置OMP_NUM_THREADS 没有效果不知道怎么回事？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26063296/a00c742f-b897-459a-889d-a133d6d8cdff)
