### ISSUE TITLE
python版本opt转换模型问题

### ISSUE THREAD

**Issue by peif1987** [PaddlePaddle/PaddleOCR#402]
使用如下命令转换官方提供的ocr_det模型：

```
paddle_lite_opt  --model_file=./ch_det_mv3_db/model \
      --param_file=./ch_det_mv3_db/param  \
      --valid_targets=x86 \
      --optimize_out_type=protobuf \
      --optimize_out=ocr_det
```
提示错误如下：

> This model is not supported, because 8 ops are not supported on 'x86'. These unsupported ops are: 'conv2d_transpose, elementwise_mul, exp, hard_sigmoid, hard_swish, nearest_interp, reciprocal, sigmoid'.

**Comment by LDOUBLEV** [comment]
> 使用如下命令转换官方提供的ocr_det模型：
> 
> ```
> paddle_lite_opt  --model_file=./ch_det_mv3_db/model \
>       --param_file=./ch_det_mv3_db/param  \
>       --valid_targets=x86 \
>       --optimize_out_type=protobuf \
>       --optimize_out=ocr_det
> ```
> 
> 提示错误如下：
> 
> > This model is not supported, because 8 ops are not supported on 'x86'. These unsupported ops are: 'conv2d_transpose, elementwise_mul, exp, hard_sigmoid, hard_swish, nearest_interp, reciprocal, sigmoid'.

目前还不支持x86上的端侧部署，只支持arm版本的，我们会尽快支持。

**Comment by AIpioneer** [comment]
> 使用如下命令转换官方提供的ocr_det模型：
> 
> ```
> paddle_lite_opt  --model_file=./ch_det_mv3_db/model \
>       --param_file=./ch_det_mv3_db/param  \
>       --valid_targets=x86 \
>       --optimize_out_type=protobuf \
>       --optimize_out=ocr_det
> ```
> 
> 提示错误如下：
> 
> > This model is not supported, because 8 ops are not supported on 'x86'. These unsupported ops are: 'conv2d_transpose, elementwise_mul, exp, hard_sigmoid, hard_swish, nearest_interp, reciprocal, sigmoid'.

您好，方便联系一下吗，你们要使用什么硬件啊  联系方式（微信/电话）：I5二IO五9八六5巴。

**Comment by peif1987** [comment]
我只是想在本地PC机上先跑一下结果验证下，一般的开发场景应该是先在本机测试通过后，再用jni封装成动态库发布给安卓开发工程师开发上层应用。
官方提供的demo只能在手机上跑的话，调试起来会觉得不够方便。
