### ISSUE TITLE
训练过程中在跑验证集的时候卡死

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4021]
![H%~8@XUY5C_NLLTD~OIW~E7](https://user-images.githubusercontent.com/48303408/132934390-83371678-0df7-4d6e-9609-39df06f81724.png)
请问训练过程中在跑验证集的时候卡死不动了是啥情况

**Comment by Essence9999** [comment]
> ![H%8@XUY5C_NLLTDOIW~E7](https://user-images.githubusercontent.com/48303408/132934390-83371678-0df7-4d6e-9609-39df06f81724.png)
> 请问训练过程中在跑验证集的时候卡死不动了是啥情况

遇到同样问题
