### ISSUE TITLE
PaddleServing 内存不释放

### ISSUE THREAD

**Issue by Mr-Zhange** [PaddlePaddle/PaddleOCR#4024]
环境：
wsl2 ubuntu 20.04
paddlepaddle-gup==2.1.2.post112
paddle-serving-server-gpu==0.6.3.post11
paddle-serving-app==0.6.3
paddle-serving-client==0.6.3

![image](https://user-images.githubusercontent.com/35223774/132988495-e7cc0b8f-8ba7-4a70-9358-2a00f73178cf.png)
内存不释放
/mnt/d/Code/Paddle/PaddleOCR/deploy/pdserving/web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0912 20:44:46.689173  1692 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.2
W0912 20:44:46.795991  1692 device_context.cc:422] device: 0, cuDNN Version: 8.2.
PROFILE	pid:1692	prep#[det|1]_0:1631450686414539 prep#[det|1]_1:1631450686582238 midp#[det|1]_0:1631450686582249 midp#[det|1]_1:1631450692799307 postp#[det|1]_0:1631450692799767 postp#[det|1]_1:1631450692978561 
W0912 20:44:53.359845  1788 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.2
W0912 20:44:53.433773  1788 device_context.cc:422] device: 0, cuDNN Version: 8.2.
W0912 20:45:15.582222  2390 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582464  2396 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582870  2386 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582280  2394 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582264  2395 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582413  2388 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582372  2389 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.582437  2391 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.585047  2393 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.586475  2387 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.586797  2397 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:45:15.587169  2392 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0912 20:47:32.748334  1788 rnn_op.cu.cc:404] If the memory space of the Input WeightList is not continuous, less efficient calculation will be called. Please call flatten_parameters() to make the input memory continuous.

**Comment by bjjwwang** [comment]
看着像是cuda和cudnn的版本没有对上的问题，问下 现在环境的cuda和cudnn的版本号是多少

**Comment by Mr-Zhange** [comment]
CUDA Version: 11.6
cuDNN Version: 8.2
