### ISSUE TITLE
关于检测模型训练

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4029]
采用同样的模型训练同一数据集，经过多次训练感觉模型拟合越来越好，请问这是什么情况？难道会在前面训练参数的基础上叠加？

**Comment by LDOUBLEV** [comment]
> 经过多次训练感觉模型拟合越来越好?

拟合越来越好是指训练精度越来越高？

你训练的时候是否加载了上一次训练的模型

**Comment by 18362890185** [comment]
> > 经过多次训练感觉模型拟合越来越好?
> 
> 拟合越来越好是指训练精度越来越高？
> 
> 你训练的时候是否加载了上一次训练的模型

拟合精度越来越高，预训练模型有加载过自己训练的模型

**Comment by 18362890185** [comment]
> > > 经过多次训练感觉模型拟合越来越好?
> > 
> > 
> > 拟合越来越好是指训练精度越来越高？
> > 你训练的时候是否加载了上一次训练的模型
> 
> 拟合精度越来越高，预训练模型有加载过自己训练的模型
但是多数加载的官网的预训练模型
