### ISSUE TITLE
提个几个小想法

### ISSUE THREAD

**Issue by WenmuZhou** [PaddlePaddle/PaddleOCR#403]
1. 日志文件希望可以保存到模型保存的文件夹内，这样在后台运行训练任务时，可以根据日志来查看训练进度。
2. 希望保存的模型参数的时候可以保存一下附带的信息，比如当前epoch，train_batch_id，当前最优模型的acc和最优模型所在epoch，目前观察下来，每次resume都是从epoch0和iter0开始的。

**Comment by BeyondYourself** [comment]
日志保存下来，最好能够引入可视化VisualDL，方便分析结果

**Comment by WenmuZhou** [comment]
> 日志保存下来，最好能够引入可视化VisualDL，方便分析结果

能引入VisualDL就更好了

**Comment by dyning** [comment]
感觉一般都是通过把log重定向到文件中，查看上述信息。

**Comment by dyning** [comment]
> > 日志保存下来，最好能够引入可视化VisualDL，方便分析结果
> 
> 能引入VisualDL就更好了

嗯，后续会考虑添加。
