### ISSUE TITLE
使用PubTabNet的数据进行表格识别，效果并不是很理想

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#4030]
你好，我使用pubtabnet的数据进行表格识别，发现效果并不好，请问是什么原因导致呢？
进行预测的代码为：
import os
import cv2
from paddleocr import PPStructure, draw_structure_result, save_structure_res

table_engine = PPStructure(det_model_dir='inference/en_ppocr_mobile_v2.0_table_det_infer/',
                           rec_model_dir='inference/en_ppocr_mobile_v2.0_table_rec_infer/',
                           table_model_dir="inference/en_ppocr_mobile_v2.0_table_structure_infer",
                           model_path="inference/ppyolov2_r50vd_dcn_365e_tableBank_latex",
                           rec_char_dict_path="E:/temp_project/PaddleOCR-release-2.2/ppocr/utils/dict/table_dict.txt",
                           show_log=True)
save_folder = 'E:/dataset/pdf_table/table_output'
img_path = 'E:/dataset/pubtabnet/test/PMC2953638_007_00.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = '../doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

[2021/09/13 15:10:24] root DEBUG: dt_boxes num : 272, elapse : 0.32413363456726074
[2021/09/13 15:10:27] root DEBUG: rec_res num  : 272, elapse : 2.5624077320098877
{'type': 'Table', 'bbox': [1, 7, 484, 578], 'res': '<html><body><table><thead><tr><td></td><td><b>Sex</b></td><td>65-69 N = 533</td><td>70-74 N = 520</td><td>75-79 N = 397</td><td>80+ N = 561</td><td>All N = 2011</td></tr></thead><tbody><tr><td>Arthritis or rheumatism</td><td>F</td><td>42.6 37.3, 47.5</td><td>37.3, 40.1</td><td>41.4, 53.4</td><td>39.8,49.5</td><td>41.5, 46.9</td></tr><tr><td>MV<sup>1 = 3</td><td>M</td><td>20.7 14.9, 26.5</td><td>19.9 14.3, 25.5</td><td>22.9 15.7, 30.1</td><td>25.6 18.9, 32.3</td><td>19.0, 25.2</td></tr><tr><td>Eyesight problems</td><td>F</td><td>38.5 33.3, 43.6</td><td>37.2 31.8, 42.5</td><td>39.6 33.7, 45.5</td><td>49.2 44.3, 54.2</td><td>41.6 38.9, 44.2</td></tr><tr><td>MV = 3</td><td>M</td><td>30.7 24.1, 37.3</td><td>31.1 24.6, 37.6</td><td>36.6 28.4, 44.9</td><td>46.4 38.9, 53.9</td><td>32.2, 39.4 35.8</td></tr><tr><td> Hearing difficulty or deafness</td><td>F</td><td>8.5 5.5, 11.4</td><td>8.7 5.6, 11.7</td><td>11.3 7.5, 15.1</td><td>19.1 15.3, 23.0</td><td>12.2 10.5, 14.0</td></tr><tr><td>MV = 3</td><td>M</td><td>8.5 4.5, 12.4</td><td>11.7 7., 16.2</td><td>11.5 6.0, 17.0</td><td>23.2 16.8, 29.6</td><td>13.6 11.0, 6.2</td></tr><tr><td>Persistent cough</td><td></td><td>8.5 5.5,11.4</td><td>10.8 7.4, 14.2</td><td>10.5 6.6, 14.2</td><td>12.2 9.0, 15.4</td><td>10.6 8.9, 12.2</td></tr><tr><td>MV = 3</td><td>M</td><td>10.6 6.2, 1.5</td><td>7.1 3.5, 10.8</td><td>9.2 4.2, 14.1</td><td>12.6 15.5, 17.6</td><td>9.9 7.6, 12.0</td></tr><tr><td>Difficulty breathing, breathlessness or asthma</td><td>F</td><td>8.7 5.8, 11.7</td><td>9.3 6.1, 12.4</td><td>9.8 6.2, 13.3</td><td>12.0 8.8, 15.2</td><td>8.4, 11.7 10.0</td></tr><tr><td>MV = 2</td><td>M</td><td>10.1 5.8 14.3</td><td>7.1 3., 10.8</td><td>6.9 2.5, 11.2</td><td>9.5 5.1, 13.9</td><td>6.4, 10.6 8.5</td></tr><tr><td> Heart trouble or angina</td><td>F</i></td><td>5.0 27, 73</td><td>5.9 3.3, 8.5</td><td>3.4 1.2, 5.6</td><td>4.8 <i>2.7, 7.0</i></td><td>4.8 3.7, 6.0</td></tr><tr><td>MV = 3</td><td>M</td><td>2.6 0.4, 4.9</td><td>4.1 1.3, 6.9</td><td>6.9 2.5, 11.2</td><td>4.2 1.1, 7.2</td><td>4.2 2.7, 5.8</td></tr><tr><td> Stomach or intestine problems</td><td>F</td><td>19.5 15.3, 23.7</td><td>22.3 17.7, 26.9</td><td>21.9 16.9, 26.9</td><td>23.0 18.8, 27.2</td><td>19.5, 23.9 21.7</td></tr><tr><td>MV = 4</td><td>M</td><td>12.7 7.9, 17.5</td><td>16.8 16 22.1</td><td>13.7 7.8, 19.6</td><td>14.9 9.3, 20.4</td><td>14.6 12.0, 17.3</td></tr><tr><td> Faints or blackouts</td><td>F</td><td>3.5 1.6, 5.4</td><td>2.8 10, 46</td><td>3.8 1.5, 6.0</td><td>5.9 3.6, 0.2</td><td>1.0, 5.2 4.1</td></tr><tr><td>MV = 5</td><td>M</td><td>2.6 0.4, 4.9</td><td>2.6 0.3, 4.9</td><td>1.5 0.0, 3.6</td><td>3.0 0.4, 5.6</td><td>2.5 1.3, 3.7</td></tr><tr><td>Paralysis, weakness or loss of one leg or arm</td><td>F</b></td><td>3.2 1.3, 5.1</td><td>3.7 1.7, 5.8</td><td>1.9 0.2, 3.5</td><td>10.1 7.1, 13.0</td><td>3.9, 6.3 5.1</td></tr><tr><td>MV = 7</td><td>M</td><td>2.7 0.4, 5.0</td><td>6.6 3.1, 10.1</td><td>5.3 1.5, 9.2</td><td>6.0 2.4, 9.5</td><td>3.5, 6.8 5.1</td></tr><tr><td>Skin disorders pressure sores, leg ulcers or burns</td><td></td><td>1.7 0.4, 3.1</td><td>0.6 0.0, 1.5</td><td>1.9 0.2, 3.5</td><td>4.3 2.3, 6.4</td><td>2.3 1.5, 3.1</td></tr><tr><td>MV = 6</td><td>M</td><td>1.1 0.0, 2.5</td><td>0.5 0.0, 1.5</td><td>0.8 0.0 2.3</td><td>3.0 0.4, 5.5</td><td>1.3 0.5, 2.2</td></tr><tr><td>More than 15 disability days in the last month</td><td>F</b></td><td>10.5 7.2, 13.7</td><td>11.8 .3, 15.3</td><td>14.7 10.4, 18.9</td><td>28.5 24.0, 33.0</td><td>16.9 14.9, 19.0</td></tr><tr><td>MV = 5</td><td>M</td><td>9.0 4.9, 13.1</td><td>13.2 8.5, 18.0</td><td>11.5 6.0, 17.0</td><td>17.2 11.5, 23.0</td><td>10.2, 15.2 12.7</td></tr></table></body></html>'}

输入的图片为：
![PMC2953638_007_00](https://user-images.githubusercontent.com/40531744/133039716-701ab512-89b5-4093-ad59-c5074b4d53d6.png)

之前遇到乱码问题，不过更换了字典集之后就好多了。但是我测试了几张图片，发现特别是第一行部分，都没有很好地重建表格的结构出来，请问是为什么呢？

**Comment by hhhhhhogan** [comment]
然后我版式分析、文本检测、文本识别也换过模型，图片也更换过训练集、评估集的，效果也不是很理想

**Comment by WenmuZhou** [comment]
看看检测的表格区域有没有检测到第一行
