### ISSUE TITLE
训练数据下载链接404

### ISSUE THREAD

**Issue by maplehan2009** [PaddlePaddle/PaddleOCR#4033]
训练数据下载链接 : https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/datasets.md

无法打开, 显示 page not found 404

**Comment by LDOUBLEV** [comment]
英文的文档后面都有en.md结尾，文档在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/datasets_en.md
请问，这个错误的链接是在哪出现的，麻烦指出，我们会第一时间修改

**Comment by maplehan2009** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/training_en.md#31-training-data

Chinese data set 的 url 链接应该写错了
