### ISSUE TITLE
copypaste数据增强

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#4036]
请问通用文本检测模型模型训练时增加copypaste了吗

**Comment by MissPenguin** [comment]
copypaste 是 PP-OCRv2模型才开始加入的，原server模型没有用到这个

**Comment by lalalagogogochong** [comment]
> copypaste 是 PP-OCRv2模型才开始加入的，原server模型没有用到这个

老师，您好，原始的server模型可以使用吗，PP-OCRv2模型使用时在配置文件中有没有相关的参数配置呢

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/4063 参考这个pr

**Comment by lalalagogogochong** [comment]
> #4063 参考这个pr

好的，谢谢老师
