### ISSUE TITLE
有没有大神更换backbone成功的

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#4038]
顶不住了，主干网络改了一个月了，还全是bug，请不要回复跟着readme里的指导更换了，完全没啥用，有没有高人指路给个成功更换的案例

**Comment by MissPenguin** [comment]
想换哪个backbone呢，可以把具体报错贴出来看下

**Comment by houyan520** [comment]
准备更换，老哥你先把bug贴出来

**Comment by hice1207** [comment]
> 准备更换，老哥你先把bug贴出来

目前更换成功了，之前是basemodel里面的outchannel读取不到，我自己重写了读取的代码。
兄弟等你换成功了给我介绍一下经验。

**Comment by xiong-yuxian** [comment]
想请问一下你更换了哪个网络，我换成vgg训练了很久acc依旧很低，loss也降得很少，想向你请教一下经验
![image](https://user-images.githubusercontent.com/58280508/190095251-587c1056-6c8a-45b0-870a-922ff3b2ca82.png)
