### ISSUE TITLE
训练异常中断

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#4042]
系统： centos7
CUDA: 10.0
cudnn: 7.6.5
cpu: 支持avx
gpu: 4个1080 ti
![企业微信截图_16315845741829](https://user-images.githubusercontent.com/61573829/133187775-2b2f5e6b-6a76-418b-a43d-b51dbf946e75.png)
![gpu](https://user-images.githubusercontent.com/61573829/133187868-c583f308-92de-439f-8264-9a9d69274e69.png)

conda 环境
python: 3.7
paddlepaddle: paddlepaddle-gpu==2.0.0
安装方式: pip install paddlepaddle-gpu==2.0.0
![企业微信截图_16315887312457](https://user-images.githubusercontent.com/61573829/133188142-988fe042-b6ff-42c6-8dac-c083a82275e9.png)

![企业微信截图_16315886824270](https://user-images.githubusercontent.com/61573829/133188076-b806efd3-043e-4dff-9767-4be3ad75c6a2.png)

4个gpu都被占满，但paddleocr代码并没有特地指定使用哪一个gpu。
训练一段时间后，出现错误：
![error](https://user-images.githubusercontent.com/61573829/133187906-488e8cbf-7c37-4670-8212-03d89bda5b9f.png)

请问这个错误是什么原因导致的？该如何解决啊？

**Comment by Zhangts98** [comment]
训练代码是develop 分支的。
训练命令： python tools/train.py -c config/rec/xxx.yml

之前训练是没有问题的，后来要编译其他东西，在机器上额外装了一个cuda10.2，更改了默认cuda, 执行了ldconfig。编译结束后，把默认的cuda修改为cuda10.0，重新执行了ldconfig,。启动训练后， 1epoch+几十个iters后就卡住。后来就删除所有cuda，重新安装paddlepaddle和cuda10.0（但没有重装驱动），训练了 2epoch+几十iters 后，就中断并报错。

**Comment by Zhangts98** [comment]
训练代码是develop 分支的。
训练命令： python tools/train.py -c config/rec/xxx.yml

之前训练是没有问题的，后来要编译其他东西，在机器上额外装了一个cuda10.2，更改了默认cuda, 执行了ldconfig。编译结束后，把默认的cuda修改为cuda10.0，重新执行了ldconfig,。启动训练后， 1epoch+几十个iters后就卡住。后来就删除所有cuda，重新安装paddlepaddle和cuda10.0（但没有重装驱动），训练了 2epoch+几十iters 后，就中断并报错。

**Comment by tink2123** [comment]
数据读取有问题，再检测一下数据路径的配置吧，可以先跑一下单卡训练，跑通后再执行多卡。

**Comment by Zhangts98** [comment]
> 数据读取有问题，再检测一下数据路径的配置吧，可以先跑一下单卡训练，跑通后再执行多卡。

看了下，路径是没有问题的。即使是不存在的图像数据或者读取为None的图像数据，也会执行continue跳过。

**Comment by tink2123** [comment]
这里的warning信息可以屏蔽一下：https://github.com/PaddlePaddle/PaddleOCR/blob/6b44a969d319307d42c1d0c5fdc6171514258f2d/ppocr/data/rec/img_tools.py#L378
看下有没有其他训练报错

**Comment by Zhangts98** [comment]
> 这里的warning信息可以屏蔽一下：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/6b44a969d319307d42c1d0c5fdc6171514258f2d/ppocr/data/rec/img_tools.py#L378-L382
> 
> 
> 看下有没有其他训练报错

重启了训练， 把上面warning信息屏蔽了。 这次没有出现错误的信息， 只不过在第一轮结束后就停止训练了（如图一）。训练开始的同时，我使用nvidia-smi -l 5 每隔五秒打印一次gpu的信息，注意到最后两次打印的时间间隔并不是五秒。并且倒数第二次输出的信息是完整的，且时间和训练停掉的时间差不多(如图二)， 最后一次打印输出了error。图三是用ps查看训练程序的状态，他们的状态都是Sl+。
请问这是gpu本身出现问题了。还是我的数据读取有问题。这两次训练出现的错误信息都不一样。。。。。
图一：
![xunlian](https://user-images.githubusercontent.com/61573829/133536296-0aeda8d4-4c8f-4731-88ad-0723c735fdaf.png)
图二：
![gpu](https://user-images.githubusercontent.com/61573829/133536311-62453560-dedb-45cb-a714-0ecf0dd9e8df.png)
图三：
![python](https://user-images.githubusercontent.com/61573829/133536321-648a6fb6-e920-43fc-9f33-e9fcf57a7e0a.png)

**Comment by Zhangts98** [comment]
![nvidia](https://user-images.githubusercontent.com/61573829/133536806-23f520cb-aed7-497f-9f97-165553322c66.png)
这是nvidia-smi -l 5 进程的状态
