### ISSUE TITLE
请问下，竖排文字是使用什么项目生成的呢？能否提供一个链接？

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#405]
请问下，竖排文字是使用什么项目生成的呢？能否提供一个链接？

**Comment by tink2123** [comment]
竖排文字与横排文字合成方式相同，只是选择了垂直字体。合成工具推荐：https://github.com/Sanster/text_renderer

**Comment by cjt222** [comment]
请问下垂直字体指的是什么呢？这个工具貌似还不能支持生成竖排文字吧

**Comment by tink2123** [comment]
垂直字体就是可以竖向书写的字体，上面的工具替换fonts可以合成竖排文字。另外也可以看下这个工具：https://github.com/zcswdt/Color_OCR_image_generator

**Comment by caopulan** [comment]
> 垂直字体就是可以竖向书写的字体，上面的工具替换fonts可以合成竖排文字。另外也可以看下这个工具：https://github.com/zcswdt/Color_OCR_image_generator

请问哪里能下载到竖向字体
