### ISSUE TITLE
Benchamrk(Benchmark)单词拼写错误

### ISSUE THREAD

**Issue by 934453938** [PaddlePaddle/PaddleOCR#4050]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/benchmark.md
![image](https://user-images.githubusercontent.com/28644889/133223445-49617187-21a0-4090-a5c9-1678f1a1b207.png)

**Comment by tink2123** [comment]
感谢反馈，已修复。
