### ISSUE TITLE
你好  style_text可以生成的数据有些会出现文字重叠的情况

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#4051]
![5](https://user-images.githubusercontent.com/57936895/133227175-1baf361f-3cbc-45fe-a3f3-4587c092e243.png)

**Comment by weisy11** [comment]
是的…可以根据文字的长度crop一下

**Comment by guijuzhejiang** [comment]
> 是的…可以根据文字的长度crop一下

怎么裁剪?有的好有的坏,标签怎么改?这个bug提了很久了,难道不是先解决bug吗?
