### ISSUE TITLE
如何取消这些日志打印输出？我在PPStructure设置show_log=False不生效

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#4053]
请问如何取消这些日志打印输出？我在PPStructure设置show_log=False不生效？

I0914 17:32:07.127447 253159 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0914 17:32:07.142017 253159 memory_optimize_pass.cc:199] Cluster name : conv2d_89.tmp_0  size: 153600
I0914 17:32:07.142048 253159 memory_optimize_pass.cc:199] Cluster name : elementwise_add_7  size: 358400
I0914 17:32:07.142060 253159 memory_optimize_pass.cc:199] Cluster name : conv2d_90.tmp_0  size: 614400
I0914 17:32:07.142078 253159 memory_optimize_pass.cc:199] Cluster name : conv2d_transpose_4.tmp_0  size: 9830400
I0914 17:32:07.142107 253159 memory_optimize_pass.cc:199] Cluster name : relu_2.tmp_0  size: 13107200
I0914 17:32:07.142122 253159 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_2.tmp_0  size: 9830400
I0914 17:32:07.142133 253159 memory_optimize_pass.cc:199] Cluster name : x  size: 4915200
I0914 17:32:07.142144 253159 memory_optimize_pass.cc:199] Cluster name : hard_swish_0.tmp_0  size: 3276800
I0914 17:32:07.142155 253159 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_4.tmp_0  size: 2457600
--- Running analysis [ir_graph_to_program_pass]

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/3929 参考这个pr吧
