### ISSUE TITLE
device参数

### ISSUE THREAD

**Issue by xiuyangshengxi** [PaddlePaddle/PaddleOCR#4054]
请问python版本的device参数如何设定，比如设定只使用cpu运行

**Comment by tink2123** [comment]
训练可以通过 -o Global.use_gpu=False ，预测时指定参数 --use_gpu=False

单卡训练选择0号卡： export CUDA_VISIBLE_DEVICES=0 

具体可以参考文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md
