### ISSUE TITLE
C++推理代码疑问

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleOCR#4058]
PaddleOCR\deploy\cpp_infer\src\main.cpp182行中循环读取文件夹下照片时，该代码读取FLAGS_image_dir为文件夹名称，更改为cv_all_img_names[i]则可正常运行，不知道这是代码错误还是？
代码版本为今日刚拉取的最新版本。

`LOG(INFO) << "The predict img: " << cv_all_img_names[i];

      cv::Mat srcimg = cv::imread(FLAGS_image_dir, cv::IMREAD_COLOR);
      if (!srcimg.data) {
        std::cerr << "[ERROR] image read failed! image path: " << cv_all_img_names[i] << endl;
        exit(1);
      }`

**Comment by WenmuZhou** [comment]
我看最新的和你给的不一样啊https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/src/main.cpp#L207-L211

**Comment by Gmgge** [comment]
@WenmuZhou 尬住了，早上拉了两边，重新拉了下，看到七天前就改掉了。
