### ISSUE TITLE
单卡GPU 多线程报错，单线程没问题（Flask）

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4060]
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at/paddle/paddle/fluid/platform/gpu_info.cc:308)

CUDA11.2, CUDNN8，驱动都没有问题

**Comment by WenmuZhou** [comment]
这个可以提供复现的最小代码吗

**Comment by Essence9999** [comment]
> 这个可以提供复现的最小代码吗，另外部署建议考虑下hubserving

![image](https://user-images.githubusercontent.com/66725845/133378143-a851ac38-22b8-406f-b50e-a38a7b3a4192.png)
