### ISSUE TITLE
Please introduce the functions of these two folders

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#4061]
![image](https://user-images.githubusercontent.com/12640462/133366174-cc33da55-60fd-44b7-8133-e4ea52e34b52.png)

I guess whether it can be merged into a same folder

**Comment by WenmuZhou** [comment]
ch_ppocr_v2.0 is the dygraph version config of https://github.com/PaddlePaddle/PaddleOCR/blob/develop/configs/det/det_mv3_db_v1.1.yml
ch_PP-OCRv2 is the latest model of PP-OCR series，it has a huge improvement in accuracy.

**Comment by BeyondYourself** [comment]
THX
