### ISSUE TITLE
量化的检测模型在转换到paddle-lite后，运行结果无意义

### ISSUE THREAD

**Issue by chiaitian** [PaddlePaddle/PaddleOCR#4062]
我使用deploy/slim/quantization/quant.py 量化训练自己的模型，转换的inference模型没有问题，但是转换的paddle-lite模型输出结果无意义。paddle-lite使用protobuf模式转换的模型Netron.app也无法打开。

请问这是哪里的问题？

**Comment by WenmuZhou** [comment]
无意义是啥意思

**Comment by chiaitian** [comment]
就是检测的文本框的位置都不对

**Comment by chiaitian** [comment]
问题解决了。查看模型结构需要把protobuf模式生成的model文件改为__model__.
之前paddle-lite模型输出有问题，是因为我转换的模型的输入是固定大小的，而实际推理时输入大小不一致导致的，转换时改为动态就行了
