### ISSUE TITLE
js OCR转换问题

### ISSUE THREAD

**Issue by QianLingjun** [PaddlePaddle/PaddleOCR#4064]
请问，现在可以实现js ocr的预测了吗？目前我遇到了一个关键js OCR转换过程中的问题，如下：

我遇到一个问题，就是官方提供了OCR js检测的案例，但是没有识别的案例（https://github.com/PaddlePaddle/Paddle.js）。我用官方提供的模型，在Linux上是可以完成OCR全过程的，在OCR js的案例，也是可以在网页上预测的。但是，我用官方的模型，和代码，转换到js版本的model和。dat文件后，无法识别。其中model没有问题，.dat其中的二进制数字不一致。请问这种是什么问题呢？谢谢

**Comment by WenmuZhou** [comment]
但是，我用官方的模型，和代码，转换到js版本的model和。dat文件后，无法识别。其中model没有问题，.dat其中的二进制数字不一致

这一步是用的我们这边发布的模型吗，转换之后检测能否正常工作呢，我看你只说了没法识别，是不是检测是正常的
