### ISSUE TITLE
版面分析模型LayoutParser model 的训练模型能放出了吗？

### ISSUE THREAD

**Issue by fly8764** [PaddlePaddle/PaddleOCR#4065]
版面分析模型LayoutParser model 在三个数据集上训练好的模型能放出训练模型吗?现在PaddleOCR/ppstructure 上给出的是预测推理模型，不能在自己的数据集上加训。

https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/ppstructure

**Comment by WenmuZhou** [comment]
在自己数据集上训练，可以直接参考PPYOLO的文档进行训练的https://github.com/PaddlePaddle/PaddleDetection/blob/release%2F2.2/configs/ppyolo/README_cn.md
