### ISSUE TITLE
过长的文本识别训练效果很差，但检测模型检测的结果就是长文本

### ISSUE THREAD

**Issue by icesword95** [PaddlePaddle/PaddleOCR#4066]
之前标注一行文字时凡是遇到空格的地方都会断开标注为两个文本框，此时识别训练效果也较好，acc能到0.90
但用这些标注数据训练检测模型时，同一行高度的文字哪怕中间有好几个空格的长度都会被识别为一个文本框，虽然框的效果不错但因为和标注的差距很大所以数值很低，担心这个会对识别也造成影响（之前都没有标注空格）因此重新做了标注。
重新标注将同一行的全部文字标为一个文本框，因此算上空格长度最长会有40+，最大长度也修改为了50。宽高比最多会有超过20的。再次训练后识别效果变得极差，acc只有60。（后来查询其他issue发现resize未改，现在改为了3,32,640在重新训练）
请问这种情况下究竟该如何标注？如果要回复原来的标注，中间有空格的检测结果的较长文本框传递给没见过空格和长文本的识别模型会有影响吗，或是有没有办法让检测模型会在空格处断开文本框？或者继续在文本极长的情况下还有什么参数可以修改帮忙提高acc吗，FAQ中有提到宽高比超过10:1的会被舍弃，这个是否有地方可以修改？

**Comment by houyan520** [comment]
我遇到类似的问题了，首先您上面说的那个resize，现在改为了3,32,640在重新训练，这个机制是640/32的比例，只要训练集有大于这个比例的图片会被抛弃，如果您的数据集长文本居多，可以适当调大这个，其次，就是增加数据集，我是扩充了数据集以后再次训练（此时数据集依旧短文本居多，3-5个字左右，我同时让数据集含有语义信息），然后其预测长文本（15字以上），发现效果提升，但是针对预测的文本图片边缘含有较多空白，预测效果极差，基本上没对的

**Comment by WenmuZhou** [comment]
你说的标志分开拿去训练检测却是合并都，这个我不太理解啊，理论上这种检测出来也应该是合并的

**Comment by icesword95** [comment]
> 你说的标志分开拿去训练检测却是合并都，这个我不太理解啊，理论上这种检测出来也应该是合并的

合并起来长度会特别长，多的时候会有40+个字符，而且中间会有很长的空格，这不会影响到识别模型的效果吗？识别模型训练时里面没有空格，而且长度不超过20。我试着拿合起来的标记去训练过，效果非常地差，改成3*320*640还是很差。
