### ISSUE TITLE
PPOCRLabel 标注最后一行无法输入中文

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/PaddleOCR#4067]
如图描述，标注后最后一个label无法输入中文
![2](https://user-images.githubusercontent.com/44053467/133416594-b67f862f-9c6d-4c77-b376-4d4db037bf13.png)

**Comment by Evezerest** [comment]
你好，问题解决了吗？无法输入中文的情况能具体描述一下吗

**Comment by ChaoII** [comment]
解决办法就是粘贴。不能打字。我不知道是不是和我电脑或者输入法有关



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月27日(周一) 晚上8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PPOCRLabel 标注最后一行无法输入中文 (#4067)




 
你好，问题解决了吗？无法输入中文的情况能具体描述一下吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by latawangzi** [comment]
可以点击右键-编辑-输入文字确认
