### ISSUE TITLE
./tools/infer/predict_system.py程序中dt_boxes, rec_res = text_sys(img) 耗时多，有没有什么优化方案？

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4069]
![image](https://user-images.githubusercontent.com/66725845/133435943-768eeef6-a8fe-47a2-b423-17fc43683768.png)

CPU环境下，dt_boxes, rec_res = text_sys(img)这步耗时0.8s
CPU环境下，ocr识别一张身份证，总耗时1.3s

**Comment by Gmgge** [comment]
这个函数是OCR三个流程的整合，是该项目的核心功能实现函数。

**Comment by WenmuZhou** [comment]
开mkldnn吧，另外第一张图耗时会比后面的多

**Comment by Essence9999** [comment]
> 开mkldnn吧，另外第一张图耗时会比后面的多

不开，mkldnn可以识别整个图片；开了，只能识别两个字。不知道问题出在哪

**Comment by Gmgge** [comment]
我升级了版本之后，就解决了这个问题。
