### ISSUE TITLE
蒸馏训练的两个小模型保存路径

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4072]
![image](https://user-images.githubusercontent.com/48303408/133541228-9d9a2916-76d0-4f59-bbd7-8c376bc62f89.png)
怎么能让两个小模型都保存下来，这个模型保存路径应该怎么设置

**Comment by littletomatodonkey** [comment]
你好，可以参考这篇文档中，对目前保存下来的模型进行解析

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/knowledge_distillation.md
