### ISSUE TITLE
PaddleOCR/ppocr/utils/ppocr_keys_v1.txt文件缺了一个仫字

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleOCR#4073]
仫佬族是个少数民族，这字在身份证识别用途上还是比较重要的。

**Comment by littletomatodonkey** [comment]
你好，是的，感谢反馈，我们考虑在下一版模型中添加该字段哈，当前还是更建议更换字典进行微调哈

**Comment by Essence9999** [comment]
> 你好，是的，感谢反馈，我们考虑在下一版模型中添加该字段哈，当前还是更建议更换字典进行微调哈

微调的话，是只选含这个字的一定量数据进行训练还是，在全部训练数据的基础上加上含这个字的数据训练？

**Comment by Essence9999** [comment]
> 你好，是的，感谢反馈，我们考虑在下一版模型中添加该字段哈，当前还是更建议更换字典进行微调哈

蕲 识别成 薪，官方默认中文字典中是有这个字的，有什么办法快速解决吗？
