### ISSUE TITLE
slim量化

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#4075]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md
ch_PP-OCRv2_rec_slim | 【最新】slim量化版超轻量模型，支持中英文、数字识别 | ch_PP-OCRv2_rec.yml | 9M | 推理模型 / 训练模型
ch_PP-OCRv2_rec | 【最新】原始超轻量模型，支持中英文、数字识别 | ch_PP-OCRv2_rec.yml | 8.5M | 推理模型 / 训练模型

这两个文字识别的版本有什么区别呢，量化版和非量化哪个效果会更好呢，我看配置文件都是同一个

**Comment by littletomatodonkey** [comment]
你好，量化和非量化精度基本一致，量化模型在lite部署时，速度更快，体积更小

**Comment by lalalagogogochong** [comment]
> 你好，量化和非量化精度基本一致，量化模型在lite部署时，速度更快，体积更小

好的谢谢老师
