### ISSUE TITLE
3399部署paddlelite+paddleocr识别异常

### ISSUE THREAD

**Issue by lovehuanhuan** [PaddlePaddle/PaddleOCR#4078]
参考了https://blog.csdn.net/Zhangzh_0329/article/details/114643639
paddle lite版本 v2.7
ppocr用的2020 9月17日更新
中英文超轻量压缩OCR模型（3.5M） | ch_ppocr_mobile_slim_v1.1_xx | 移动端
结果可以检测字体，但是都不识别
![222](https://user-images.githubusercontent.com/14980577/133564509-4dfdf877-85cd-49fb-99df-9afd38bb347a.jpg)
<img width="910" alt="a34e2f9e030cf9971a14269241400003d1f7518b608574411d56cda624a66d19RDpcRGluZ1RhbGtBcHBEYXRhXERpbmdUYWxrXDIwOTIxNzk2OV92MlxJbWFnZUZpbGVzXDE2MzE3NzUyODAzOTVfNjhGRDIxRDctMDQ4Qy00MzIyLUJDMTQtOTFGMTk3OEI1NEE5LnBuZw==" src="https://user-images.githubusercontent.com/14980577/133564521-c1736128-1e55-414c-95a8-01ce3af546d7.png">
![vis](https://user-images.githubusercontent.com/14980577/133564622-bb71a027-fcf2-4687-99c4-6d9118aaa79b.jpg)

**Comment by WenmuZhou** [comment]
换2.0试试吧

**Comment by lovehuanhuan** [comment]
解决
