### ISSUE TITLE
PPOCRLabel是否可以直接保存所有的Label到label.txt中而不需要一张一张确认 ？

### ISSUE THREAD

**Issue by MengQiDWangChao** [PaddlePaddle/PaddleOCR#4081]

**Comment by Essence9999** [comment]
可以啊

**Comment by MengQiDWangChao** [comment]
暂时未发现这个快捷键是什么
![image](https://user-images.githubusercontent.com/32353044/133607185-46f00300-52e5-403b-8b53-e7524ab0db51.png)

**Comment by zhangyingying520** [comment]
> 可以啊

你是怎么实现的

**Comment by Evezerest** [comment]
这个目前不可以，原因在于机器标注的结果和人调整的结果之间需要一个状态改变，如果直接导出模型的结果其实是不需要标注软件的。
