### ISSUE TITLE
识别微调 acc 下降问题（手机屏幕截图）

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#4083]
目前使用识别的预训练模型在4W的测试集上：acc 为83%。主要场景是手机屏幕截图

使用 text_renderer 工具合成了 200W 的图片，每个字差不多均衡选取300张图片。语料使用NLP常见数据集，字体使用常见的 10多种字体，背景为0-255随机的灰度背景，高度固定为32，长度不定。

微调之后模型在测试集上的效果变差，目前猜测是合成数据与测试数据的分布差异太大导致，请问大佬：
1. 原因是否在于合成数据的偏差？
2. 如果存在偏差，怎么量化偏差，以及怎么改进这种问题呢？

**Comment by houyan520** [comment]
老哥，你有没有出现，预测的时候出现文本图像有多余空白边缘，识别效果骤降

**Comment by littletomatodonkey** [comment]
> 老哥，你有没有出现，预测的时候出现文本图像有多余空白边缘，识别效果骤降

你的那个issue里面回复了哈

**Comment by littletomatodonkey** [comment]
> 目前使用识别的预训练模型在4W的测试集上：acc 为83%。主要场景是手机屏幕截图
> 
> 使用 text_renderer 工具合成了 200W 的图片，每个字差不多均衡选取300张图片。语料使用NLP常见数据集，字体使用常见的 10多种字体，背景为0-255随机的灰度背景，高度固定为32，长度不定。
> 
> 微调之后模型在测试集上的效果变差，目前猜测是合成数据与测试数据的分布差异太大导致，请问大佬：
> 
> 1. 原因是否在于合成数据的偏差？
> 2. 如果存在偏差，怎么量化偏差，以及怎么改进这种问题呢？

你好，数据偏差肯定是存在的，这块建议还是需要有一些真实数据，然后和合成数据动态采样训练

**Comment by Essence9999** [comment]
> > 目前使用识别的预训练模型在4W的测试集上：acc 为83%。主要场景是手机屏幕截图
> > 使用 text_renderer 工具合成了 200W 的图片，每个字差不多均衡选取300张图片。语料使用NLP常见数据集，字体使用常见的 10多种字体，背景为0-255随机的灰度背景，高度固定为32，长度不定。
> > 微调之后模型在测试集上的效果变差，目前猜测是合成数据与测试数据的分布差异太大导致，请问大佬：
> > 
> > 1. 原因是否在于合成数据的偏差？
> > 2. 如果存在偏差，怎么量化偏差，以及怎么改进这种问题呢？
> 
> 你好，数据偏差肯定是存在的，这块建议还是需要有一些真实数据，然后和合成数据动态采样训练

蕲 识别成 薪，有什么快速解决方法吗？

**Comment by Sanster** [comment]
> 目前使用识别的预训练模型在4W的测试集上：acc 为83%。主要场景是手机屏幕截图
> 
> 使用 text_renderer 工具合成了 200W 的图片，每个字差不多均衡选取300张图片。语料使用NLP常见数据集，字体使用常见的 10多种字体，背景为0-255随机的灰度背景，高度固定为32，长度不定。
> 
> 微调之后模型在测试集上的效果变差，目前猜测是合成数据与测试数据的分布差异太大导致，请问大佬：
> 
> 1. 原因是否在于合成数据的偏差？
> 2. 如果存在偏差，怎么量化偏差，以及怎么改进这种问题呢？

目测你的识别场景背景比较干净，所以选择了随机灰度背景，不过还是建议找些背景图（例如coco里找些）生成数据，提高模型范化性。另外200w数据感觉少了，可以搞个500w试试

**Comment by ddz-mark** [comment]
> 目测你的识别场景背景比较干净，所以选择了随机灰度背景，不过还是建议找些背景图（例如coco里找些）生成数据，提高模型范化性。另外200w数据感觉少了，可以搞个500w试试

目前生成的数据是灰度图，不过可以试试彩色图这种方式，数据也增加的试试。谢谢大佬解答。
