### ISSUE TITLE
预测识别的时候，有多余的空白边缘识别效果很差

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#4085]
有空白多余边缘，识别效果很差
![cff6cdada7f10fd53ee46c01f798016](https://user-images.githubusercontent.com/49891512/133597261-a9bda16d-3e02-442f-8bdd-b7869ce12f50.png)

![d8cb48ab10e2bc4a442e80e3bd5145a](https://user-images.githubusercontent.com/49891512/133597260-a17cb866-a691-4202-b8f9-c85bf22f59dc.png)
这种情况有啥好办法吗 

我初步想法是扩充数据集，扩充这种有边缘信息的，我目前的数据集没有边缘信息

**Comment by littletomatodonkey** [comment]
你好，训练的时候确实没有考虑这块的增广，你说的扩充边缘信息的增广是可行的，可以先试下

**Comment by houyan520** [comment]
> 你好，训练的时候确实没有考虑这块的增广，你说的扩充边缘信息的增广是可行的，可以先试下

谢谢您的建议，我去试一下哈，我这边github随缘登录上去，刚看到您的回复

**Comment by houyan520** [comment]
> 你好，训练的时候确实没有考虑这块的增广，你说的扩充边缘信息的增广是可行的，可以先试下

我看了官方给的例子以及模块，没有发现有扩大边缘信息方法，有一些缩放、随机裁剪等，是不是自己要实现扩大边缘信息呀
