### ISSUE TITLE
请问下，为什么使用通用模型识别通用的文本时反面出现很多文字不被检测到的情况？

### ISSUE THREAD

**Issue by 965662766** [PaddlePaddle/PaddleOCR#4086]
![image](https://user-images.githubusercontent.com/85744622/133605340-c828076e-b7c9-4081-9ba5-5fc7051f8157.png)
![image](https://user-images.githubusercontent.com/85744622/133605388-9a489e66-2192-40f3-9a18-b35980a79d11.png)
![image](https://user-images.githubusercontent.com/85744622/133605500-1fbf830a-91b1-466d-9d5b-aca073f5ae5e.png)

**Comment by littletomatodonkey** [comment]
你好，可以把检测的dilation参数修改为True，看下效果

**Comment by 965662766** [comment]
![image](https://user-images.githubusercontent.com/85744622/133612992-b5f3ea9e-3a02-470d-aeb7-b777c183af1c.png)
你好，我这个样子添加参数试了并没有效果，是参数位置写错了吗？

**Comment by 965662766** [comment]
> ![image](https://user-images.githubusercontent.com/85744622/133612992-b5f3ea9e-3a02-470d-aeb7-b777c183af1c.png)
> 你好，我这个样子添加参数试了并没有效果，是参数位置写错了吗？

**Comment by 965662766** [comment]
> ![image](https://user-images.githubusercontent.com/85744622/133612992-b5f3ea9e-3a02-470d-aeb7-b777c183af1c.png)
> 你好，我这个样子添加参数试了并没有效果，是参数位置写错了吗？参数设置成 det_dilation=True 也没效果
> 
> > 你好，可以把检测的dilation参数修改为True，看下效果
