### ISSUE TITLE
训练的数据image_shape为什么必须为4的倍数

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#409]
![image](https://user-images.githubusercontent.com/12640462/88263178-2ef73800-ccfc-11ea-88f1-d0b6d50ea8ff.png)

在det_model.py段代码里，宽或者高为4的倍数，我查阅了一下关于图像宽为4的倍数有这样的说明：[Windows规定一个扫描行所占的字节数必须是4的倍数](https://blog.csdn.net/csdn_222/article/details/80878021)，那么高是否需要为4的倍数呢？

**Comment by MissPenguin** [comment]
这个逻辑跟east相关，east从backbone拿到c2，c3，c4，c5特征后，会使用unet方式进行上采样和concat，最终feature map正好是输入尺度的1/4，如果输入尺度不是4的倍数，会造成采样过程中由于除不断四舍五入产生1个像素的差距，concat报错。

**Comment by BeyondYourself** [comment]
明白，谢谢
