### ISSUE TITLE
更改骨干网路，配置文件如何设置

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4090]
你好，我更换了小的骨干网络，在Paddlecls里面找的mv_small_0_35，在训练的时候出现了维度不匹配的情况，训练还可以进行，是不是这个原因导致的推理错误，更换小骨干网络之后，配置文件中更改了large->small，scals：0_5->0_35，请问别的还有需要改的吗？
![1_08S17@ OBI_WP)(J4X45D](https://user-images.githubusercontent.com/48303408/133707951-9174145a-bb91-4050-8859-e13f3cc6525d.png)

**Comment by MissPenguin** [comment]
您好，ocr里已经支持mv3系列骨干网络了，可以直接改配置中的large->small，scals：0_5->0_35，不用更换骨干网络py文件，如果要从paddleclas拿别的骨干网络来用，需要对形状进行适配，可以diff下ocr里的mv3骨干与clas里的mv3骨干，看下如何做的适配。

**Comment by Dandelion111** [comment]
> 您好，ocr里已经支持mv3系列骨干网络了，可以直接改配置中的large->small，scals：0_5->0_35，不用更换骨干网络py文件，如果要从paddleclas拿别的骨干网络来用，需要对形状进行适配，可以diff下ocr里的mv3骨干与clas里的mv3骨干，看下如何做的适配。

好的，感谢回复，也就是说我用Paddlecls里的mv3系列的网络和ocr里的mv3网络结构上还不一样？如果进行适配的话也得修改骨干网络py文件吧，不然这个适配是啥意思呢？ ocr里面是否有mv3_small系列的呢？望指教！

**Comment by MissPenguin** [comment]
是的，ocr里面已经适配了resnet和mv3，如果你要换别的系列的骨干需要重新适配。mv3_small已经支持了，改一下yml里的相关参数就行，例如：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/det/det_mv3_db.yml#L22

**Comment by Dandelion111** [comment]
> 是的，ocr里面已经适配了resnet和mv3，如果你要换别的系列的骨干需要重新适配。mv3_small已经支持了，改一下yml里的相关参数就行，例如：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/det/det_mv3_db.yml#L22

感谢指导
