### ISSUE TITLE
新版本训练出现shape不匹配情况

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4093]
你好，问题如下：
![image](https://user-images.githubusercontent.com/48303408/133735543-3c853dbc-0ec4-4962-8b83-93f2bf4dc434.png)
预训练模型用这个方法下载的
![image](https://user-images.githubusercontent.com/48303408/133735637-3cded437-3521-451b-b837-b33961696a2a.png)
配置文件用的这个：
![image](https://user-images.githubusercontent.com/48303408/133735740-b011c428-ee76-4f95-9344-630499241096.png)
望指教

**Comment by MissPenguin** [comment]
您好，你用的这个配置文件是调过参数的，通道从256裁剪到了96，所以有的参数无法加载，不影响训练，如果用这个原始配置就不存在这个问题：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/det/det_mv3_db.yml
