### ISSUE TITLE
SAST使用自制数据集训练问题

### ISSUE THREAD

**Issue by chujian521** [PaddlePaddle/PaddleOCR#4094]
使用自己标注的训练集训练时由于一张图片上有多个文本框，为了统一所有文本框均用14点标注，但是训练时就会产生Cross point does not exist的报错，总体损失在不断下降，但是总有个别非常大，borderloss会达到几百，请问这是什么原因呢？

**Comment by MissPenguin** [comment]
这个问题没有碰到过呢，不过看样子应该是碰到了有问题的数据，也许是转换标注有问题，可以把导致报错的数据画出来看下

**Comment by chujian521** [comment]
标注里面有四点扩充成十四点的，请问这个会导致报这个错误嘛？扩充的点可能与其他点共线，会不会因为共线导致的呢？另外不扩充的话，四点标注与十四点标注在同一图片中好像会出现更多的Cross point does not exist

**Comment by MissPenguin** [comment]
训练时所有数据的点数要一致的，不要一部分4点、一部分14点这样

**Comment by chujian521** [comment]
您好，我已经找到Cross point does not exist的原因了，应该是由于扩充点时产生了某几个点会共线的情况，导致会大量报错这种，那请问每个iter总体损失在不断下降，但是总有个别loss非常大，borderloss会达到几百，请问这是什么原因呢？

**Comment by haiderasad** [comment]
@chujian521  i am facing the same problem when training on custom built dataset, converted 4 points into 14 points , any idea how to tackle this "Cross point does not exist" ?

**Comment by chujian521** [comment]
> @chujian521 i am facing the same problem when training on custom built dataset, converted 4 points into 14 points , any idea how to tackle this "Cross point does not exist" ?

Hello, this is caused by multiple collinear points when converted 4 points into 14 points. Maybe you can add a tiny random value to the Y coordinate when you converted points. Or just ignore this warning. This is my personal opinion above.
