### ISSUE TITLE
ch模式下进行微调，微调后不支持空格识别

### ISSUE THREAD

**Issue by mrlihellohorld** [PaddlePaddle/PaddleOCR#4095]
官方模型：./models/ch_ppocr_server_v2.0_rec_infer
识别结果：./eval_test/rec/test/ssxw16600_5.png:('Huawei launchesits ownoperatingsystem HarmonyOS', 0.9782156)
加入自己的数据集（数据集包含中英文，英文中只有单个单词，没有带空格的句子）：./inference_ch_common_finetune_model_latest_epoch7
识别结果：./eval_test/rec/test/ssxw16600_5.png:('HuaweilaunchesitsownoperatingSystemHarmonyOs', 0.9699037)
/home/diable/document_li/ocr/PaddleOCR/eval_test/rec/test/ssxw16600_5.png
微调后的模型，不再能够识别空格。

**Comment by mrlihellohorld** [comment]
![ssxw16600_5](https://user-images.githubusercontent.com/31719207/133740005-b42a1e17-36c9-4df6-9fe3-0fa7bd2b5a0b.png)

**Comment by MissPenguin** [comment]
是所有case都不能识别空格了还是只是识别率降低？如果不是有bug的话，可以增加一些带空格的英文数据到训练中。

**Comment by mrlihellohorld** [comment]
你好，我在finetune的时候，英文数据是没有空格的，都是单词。另外，我在测试集中少数几张图片中测试，不能识别空格。没有做大量的测试。
另外再请教一个问题，paddle提供的模型，我在测试时候发现，英文能够识别空格，中文不能识别空格。是否是因为训练数据集中存在，gt没有空格，但是图片中有空格的带有中文字符的图片。

**Comment by MissPenguin** [comment]
> 你好，我在finetune的时候，英文数据是没有空格的，都是单词。另外，我在测试集中少数几张图片中测试，不能识别空格。没有做大量的测试。
> 另外再请教一个问题，paddle提供的模型，我在测试时候发现，英文能够识别空格，中文不能识别空格。是否是因为训练数据集中存在，gt没有空格，但是图片中有空格的带有中文字符的图片。

可能是的，中文一般没有空格。

**Comment by nissansz** [comment]
> 你好，我在finetune的时候，英文数据是没有空格的，都是单词。另外，我在测试集中少数几张图片中测试，不能识别空格。没有做大量的测试。 另外再请教一个问题，paddle提供的模型，我在测试时候发现，英文能够识别空格，中文不能识别空格。是否是因为训练数据集中存在，gt没有空格，但是图片中有空格的带有中文字符的图片。

空格有办法解决了吗？微信 nlanguage
