### ISSUE TITLE
Finetune检测模型，检测框有小部分重叠

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4096]
首先感谢官方，Finetune的效果挺好的。
![image](https://user-images.githubusercontent.com/66725845/133739843-5b15fe11-c079-4a4c-b6af-4f1c66bc92ed.png)
![image](https://user-images.githubusercontent.com/66725845/133740102-3a1a9ff1-c38c-4b8c-8252-a7d0d2b10745.png)
像这种检测框部分重叠的，能通过后期参数调整吗？哪些参数呢？谢谢

**Comment by MissPenguin** [comment]
这种是确实旁边有数字导致的重叠，不太好通过调参来优化。训练数据是分段标注的吗，标成整行的话应该不会这么容易断开

**Comment by Essence9999** [comment]
> 这种是确实旁边有数字导致的重叠，不太好通过调参来优化。训练数据是分段标注的吗，标成整行的话应该不会这么容易断开

嗯嗯 我是三四个字符标注一下，目的是为了增加识别数据集，使识别模型更好些。针对检测模型，需要重新标注再预训练吗？

**Comment by Evezerest** [comment]
可以再训一个检测模型
