### ISSUE TITLE
为什么PaddleOCR输出识别结果时很多截出来的单个字符都会旋转90度

### ISSUE THREAD

**Issue by icesword95** [PaddlePaddle/PaddleOCR#4097]
而且看起来和宽高比没很大的关系，竖矩形的框一部分会旋转一部分不会，是被识别为竖排文字了吗？这样混杂着不会影响训练结果么，还得手动调整回来？不能取消对竖排的识别吗

**Comment by MissPenguin** [comment]
可以贴几张示例图看下

**Comment by icesword95** [comment]
> 可以贴几张示例图看下

![Uploading QQ图片20210922143219.png…]()
![QQ图片20210922143326](https://user-images.githubusercontent.com/8707090/134294394-5dabd64a-456a-4276-8766-e19164552f2d.png)
![QQ图片20210922143438](https://user-images.githubusercontent.com/8707090/134294399-1a650e95-c422-42ab-9b8e-643443a77b4e.png)
都是单个字符，标注的时候只标注过竖直的

**Comment by dium6i** [comment]
在使用PPOCRLabel标注图片后切割的时候也遇到了类似的问题，并且大部分主要集中在某一个字上。我这边“总”字经常被裁切后旋转90°，“A”、“I”、“峰”、“电”、“反”等也遇到过，希望官方能修复下
![new_pic0869_crop_2](https://user-images.githubusercontent.com/75460093/143028392-f6d40719-705a-4a90-a11e-a8e91fd8c038.jpg)
