### ISSUE TITLE
新模型训练问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4098]
![2](https://user-images.githubusercontent.com/87969070/133746634-b3543c10-1a1f-417c-8f5d-df435e85f9ff.png)
训练自己的数据过程中，所涉及的值一直是0.

**Comment by littletomatodonkey** [comment]
你好，需要更新下代码哈

**Comment by 18362890185** [comment]
> 你好，需要更新下代码哈

这个更新代码是指？麻烦指明以下。谢谢啦！

**Comment by MissPenguin** [comment]
拉取最新的代码再试下

**Comment by 18362890185** [comment]
> 拉取最新的代码再试下

我是直接将2.3版本下载的包在环境下运行，目前就是这样的结果，拉取新的代码还是有点不明白？
