### ISSUE TITLE
在 docker 容器内执行 predict_system.py 报错：Error: id must less than GPU count

### ISSUE THREAD

**Issue by myfjdthink** [PaddlePaddle/PaddleOCR#410]
docker 镜像：

> hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev

python --version ：3.7

nvcc --version

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130

nvidia-smi

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 25%   47C    P5    17W / 275W |      0MiB / 11178MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
> | 26%   46C    P5    29W / 275W |      0MiB / 11177MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+

按照[这个教程](https://github.com/PaddlePaddle/PaddleOCR/blob/fbed0a021093041ea602d38cd2ce7b25db08afef/doc/doc_ch/installation.md)按照的依赖包 

执行命令
```bash
python3.7 tools/infer/predict_system.py --image_dir="./pans/3.jpg" --det_model_dir="./inference/full/ch_det_r50_vd_db/"  --rec_model_dir="./inference/space/ch_rec_r34_vd_crnn_enhance/"
```

**Comment by LDOUBLEV** [comment]
有修改代码吗

**Comment by myfjdthink** [comment]
没有修改代码 @LDOUBLEV

**Comment by nblib** [comment]
@myfjdthink 是不是没有设置环境变量     `ENV CUDA_VISIBLE_DEVICES=0`

**Comment by myfjdthink** [comment]
设置环境变量还是一样的报错 @nblib 
```bash
CUDA_VISIBLE_DEVICES=0 python3.7 tools/infer/predict_system.py
```

**Comment by LDOUBLEV** [comment]
> 设置环境变量还是一样的报错 @nblib
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python3.7 tools/infer/predict_system.py
> ```

麻烦贴一下详细的报错截图吧，或者按照下面的步骤试一下：

```
export CUDA_VISIBLE_DEVICES=1
python3 tools/infer/predict_system.py --image_dir="./pans/3.jpg" --det_model_dir="./inference/full/ch_det_r50_vd_db/"  --rec_model_dir="./inference/space/ch_rec_r34_vd_crnn_enhance/"
```

**Comment by myfjdthink** [comment]
设置 CUDA_VISIBLE_DEVICES=1 一样的报错
![image](https://user-images.githubusercontent.com/2044143/88370573-d8096580-cdc4-11ea-9ffb-e3998c4ff842.png)

**Comment by myfjdthink** [comment]
我这边大概知道原因了。
如果 Docker version >= 19.03,  可以安装最新版的 nvidia-docker ，启动的到时候不需要用 nvidia-docker 命令了，可以直接用 docker 命令。
详细内容看 nvidia-docker 文档 https://github.com/NVIDIA/nvidia-docker

所以可以直接这样：
```bash
docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
```
如果正常，会输出显卡相关的信息，这样 docker 容器内才能检测到显卡。
![image](https://user-images.githubusercontent.com/2044143/88371764-3cc5bf80-cdc7-11ea-82c9-8b93de82fcc8.png)

这里很关键的一个参数是  **--gpus** 
我出现上面的问题就是少了这个参数。

**Comment by liudatutu** [comment]
@myfjdthink 我也是同样的错误，在docker容器里面用nvidia-smi可以显示显卡信息，就是在运行predict_system.py报Error: id must less than GPU count，请问你解决了么？

**Comment by myfjdthink** [comment]
Sorry 我没碰到和你一样的问题，无法帮助你 @liudatutu
