### ISSUE TITLE
PaddleOCR转ONNX问题

### ISSUE THREAD

**Issue by RyanCCC** [PaddlePaddle/PaddleOCR#4100]
请问如何将https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar转换成ONNX模型？

之前也有issue：https://github.com/PaddlePaddle/Paddle2ONNX/issues/248提到，能否给出具体步骤？小白表示看不懂，谢谢！

**Comment by MissPenguin** [comment]
可以按照[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)官网教程进行操作，如果遇到问题在[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)提issue就行，提issue时最好提供完整的操作流程和报错信息，方便相关同学跟进。

**Comment by RyanCCC** [comment]
> 可以按照[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)官网教程进行操作，如果遇到问题在[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)提issue就行，提issue时最好提供完整的操作流程和报错信息，方便相关同学跟进。

因为repo提供的ch_ppocr_server_v2.0_rec_pre inference model在转换成onnx之后只能输入100的宽度，不支持动态输入。因此我打算操作的步骤是：
1. 将repo提供的pretrain-model转换成inference model。（目前repo的tools/export_model.py支持动态输入）
2. 将inference model转换成onnx model。

在操作步骤1的时候，我利用repo上的tools/export_model.py在执行的时候发现在我设定的文件夹下没有模型输出，我的输入命令是：

```sh
python3 tools/export_model.py -c ./configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./paddleocrmodel/ch_ppocr_server_v2.0_rec_pre/ Global.load_static_weights=True Global.save_inference_dir=./tmp/
```
![image](https://user-images.githubusercontent.com/27406337/133870637-363cddfd-670d-4186-b220-672b4e65d922.png)

**Comment by MissPenguin** [comment]
2.0模型是动态图模型，你这个导出的命令有问题，改成这样试试：
```shell
python3 tools/export_model.py -c ./configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./paddleocrmodel/ch_ppocr_server_v2.0_rec_pre/best_accuracy Global.save_inference_dir=./tmp/
```

**Comment by RyanCCC** [comment]
> 2.0模型是动态图模型，你这个导出的命令有问题，改成这样试试：
> 
> ```shell
> python3 tools/export_model.py -c ./configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./paddleocrmodel/ch_ppocr_server_v2.0_rec_pre/best_accuracy Global.save_inference_dir=./tmp/
> ```

似乎还是出现问题，执行命令后tmp文件夹为空。
![image](https://user-images.githubusercontent.com/27406337/133879016-cfe97578-24fe-4480-86c1-1765abd5d778.png)

**Comment by RyanCCC** [comment]
> 2.0模型是动态图模型，你这个导出的命令有问题，改成这样试试：
> 
> ```shell
> python3 tools/export_model.py -c ./configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./paddleocrmodel/ch_ppocr_server_v2.0_rec_pre/best_accuracy Global.save_inference_dir=./tmp/
> ```

好的，已经解决，非常感谢！

**Comment by Dandelion111** [comment]
> 请问如何将[https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar转换成ONNX模型？](https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar%E8%BD%AC%E6%8D%A2%E6%88%90ONNX%E6%A8%A1%E5%9E%8B%EF%BC%9F)
> 
> 之前也有issue：[https://github.com/PaddlePaddle/Paddle2ONNX/issues/248提到，能否给出具体步骤？小白表示看不懂，谢谢！](https://github.com/PaddlePaddle/Paddle2ONNX/issues/248%E6%8F%90%E5%88%B0%EF%BC%8C%E8%83%BD%E5%90%A6%E7%BB%99%E5%87%BA%E5%85%B7%E4%BD%93%E6%AD%A5%E9%AA%A4%EF%BC%9F%E5%B0%8F%E7%99%BD%E8%A1%A8%E7%A4%BA%E7%9C%8B%E4%B8%8D%E6%87%82%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

请问识别模型怎么转成onnx
