### ISSUE TITLE
过小的检测框，过滤如何掉或删除？

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4102]

**Comment by MissPenguin** [comment]
可以把这个过滤的参数调大点试试：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/infer/predict_det.py#L159

**Comment by Essence9999** [comment]
> 可以把这个过滤的参数调大点试试：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/infer/predict_det.py#L159

可以，谢谢大佬
