### ISSUE TITLE
Load PGNet on specific GPU

### ISSUE THREAD

**Issue by cpene1** [PaddlePaddle/PaddleOCR#4103]
Hi there!

Is there any way we can load a ppocr model (specifically PGNet model for my app) on a specific GPU? In case we have multiple GPUs.

Thanks in advance!

**Comment by MissPenguin** [comment]
maybe “export CUDA_VISIBLE_DEVICES=1” ？

**Comment by cpene1** [comment]
Ohh sorry, I meant programatically. Because I have to load other models on other GPU, so I need a programatic way of loading both models. Thanks! :)
