### ISSUE TITLE
新版本识别模型比旧版本慢

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4104]
你好，我只把识别模型更换为新版本，经过100张图像的测试，发现识别部分速度平均比旧版本慢了将近一倍，理论上不应该呀

**Comment by Gmgge** [comment]
我这边测试也是发现时间增加，使用的是python+cpu+mkl

**Comment by MissPenguin** [comment]
确实不应该，测试的时候机器上是不是有别的任务占了cpu或gpu呢
