### ISSUE TITLE
训练模型转推理模型，误差特别大

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4106]
麻烦问一下，需要修改那些地方，才能和训练模型直接测试的结果一致，我用了自己的字典，现在修改完
![image](https://user-images.githubusercontent.com/80818728/133783518-c5015139-a98e-44aa-b69a-b2dcf710decb.png)
xi效果好了一点，但是他们说的注释那行程序没找到在哪

**Comment by MissPenguin** [comment]
在 #4107 跟进，这个先关闭了
