### ISSUE TITLE
训练模型转推理模型，误差特别大

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4107]
麻烦问一下需要修改哪个配置文件，才能让自己训练的模型的效果和推理完的模型效果接近？
用了自己的字典修改完这个地方了，还需要修改哪里
![image](https://user-images.githubusercontent.com/80818728/133784366-ffff37ac-0162-4fb9-b68f-bd42fbf8b1ce.png)

**Comment by MissPenguin** [comment]
自己训练的哪个模型呢，导出推理模型的命令和执行预测的命令发一下吧，另外方便的话可以给几个训练模型和推理模型的预测结果示例看看

**Comment by zhangyingying520** [comment]
> 自己训练的哪个模型呢，导出推理模型的命令和执行预测的命令发一下吧，另外方便的话可以给几个训练模型和推理模型的预测结果示例看看
#将训练好的DB模型转换为推理模型
!python tools/export_model.py -c configs/det/det_mv3_db.yml -o  Global.save_inference_dir=./output/db_mv3_infer/
#将训练好的文字识别模型转换为推理模型
!python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o  Global.save_inference_dir=inference/rec_infer

**Comment by zhangyingying520** [comment]
> > 自己训练的哪个模型呢，导出推理模型的命令和执行预测的命令发一下吧，另外方便的话可以给几个训练模型和推理模型的预测结果示例看看
> > #将训练好的DB模型转换为推理模型
> > !python tools/export_model.py -c configs/det/det_mv3_db.yml -o  Global.save_inference_dir=./output/db_mv3_infer/
> > #将训练好的文字识别模型转换为推理模型
> > !python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o  Global.save_inference_dir=inference/rec_infer

也没说怎么改呀

**Comment by zhangyingying520** [comment]
已解决

**Comment by lzzzzj** [comment]
> 

可以请问一下是怎么解决的吗
谢谢
