### ISSUE TITLE
能否提供下PP-OCR v2.0识别模型前向推理时各层的runtime？以及channel attention（Mul op相当耗时）在CPU上是怎么优化加速的？

### ISSUE THREAD

**Issue by songkq** [PaddlePaddle/PaddleOCR#4109]

**Comment by songkq** [comment]
@WenmuZhou  @dyning @LDOUBLEV @MissPenguin

**Comment by songkq** [comment]
@LDOUBLEV请问 CPU 开启mkldnn，能快多少？消耗的内存有差别嘛？

**Comment by LDOUBLEV** [comment]
开启mkldnn内存占用不变，比不开mkldnn能快非常多，你可以找一批图测试看看
另外，可以用最新的paddle>=2.1的版本，CPU+mkldnn速度比之前的paddle要快
