### ISSUE TITLE
win10下使用python推断报错。

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#411]
win10下使用python推断报错，使用的命令和错误提示如下图所示：
![image](https://user-images.githubusercontent.com/25734125/88272130-ce232c00-cd0a-11ea-8b19-02bedea71ed8.png)

检测使用的是r50_db模型，识别使用的是r34_crnn，即下图中下载的两个模型。
![image](https://user-images.githubusercontent.com/25734125/88272236-fb6fda00-cd0a-11ea-84aa-ed98dd06321b.png)

推理方法的写法参考下图，第一个图中有命令
![image](https://user-images.githubusercontent.com/25734125/88272337-1cd0c600-cd0b-11ea-82a6-3d1b3c5f6b46.png)

**Comment by tink2123** [comment]
可能是您的机器上缺少libiomp5md.dll， 有两个解决方案：
1. 
predict_system.py 前添加
```
import os
os.environ[‘KMP_DUPLICATE_LIB_OK’]=‘True’
```
2. 百度一下这个报错信息，手动下载libiomp5md.dll，复制到C:\Windows\System 路径下

**Comment by coder-sun** [comment]
> 可能是您的机器上缺少libiomp5md.dll， 有两个解决方案：
> 1.
> predict_system.py 前添加
> 
> ```
> import os
> os.environ[‘KMP_DUPLICATE_LIB_OK’]=‘True’
> ```
> 
> 1. 百度一下这个报错信息，手动下载libiomp5md.dll，复制到C:\Windows\System 路径下

感谢，已经解决。
