### ISSUE TITLE
断点训练出现loss为nanxx的情况

### ISSUE THREAD

**Issue by kano201** [PaddlePaddle/PaddleOCR#4110]
训练SRN模型的过程中断开训练，在断点继续训练的时候会出现loss直接变为nanxx的情况

使用checkpoints和pretrained_model都会出现该问题，调整了学习率也没有改善

如果不中断，训练是正常的

**Comment by Evezerest** [comment]
你好，可以提供一下命令 配置文件 还有相关包版本么
