### ISSUE TITLE
新版本识别模型训练问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4113]
![1](https://user-images.githubusercontent.com/87969070/133873431-dfbe0089-c60f-4bdf-bac8-4c1f3c6d0a3d.png)
zhe这种情况应该如何调整？

**Comment by LDOUBLEV** [comment]
提示加载模型的参数和构造的网络参数不匹配，你运行的命令是？是否修改了配置文件

**Comment by 18362890185** [comment]
> 提示加载模型的参数和构造的网络参数不匹配，你运行的命令是？是否修改了配置文件
![1](https://user-images.githubusercontent.com/87969070/134265893-df7c781e-e810-4361-be16-c5821aaf8fa0.png)
shang'tu上图是运行的指令，配置文件中更改了加载预训练模型，其余的并没有更改。
