### ISSUE TITLE
如何清除掉控制台多余的信息?

### ISSUE THREAD

**Issue by qfwysw** [PaddlePaddle/PaddleOCR#4114]
非常感谢您优秀的代码, 但ocr控制台输出太多信息, 如何才能清除呢
![image](https://user-images.githubusercontent.com/53482524/133881053-5370af0b-6925-4d88-a593-b9ecf53e5bac.png)

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/133881480-4de2492a-79dc-4187-84ee-b3a1b66e6d2f.png)
我很困惑定义在哪里

**Comment by MissPenguin** [comment]
把这行注释打开：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/infer/utility.py#L267
