### ISSUE TITLE
预测出错

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleOCR#4116]
预测时出现下面的错误：
(PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:202)

**Comment by LDOUBLEV** [comment]
麻烦提供下预测报错的指令和使用的模型以及运行环境
在linux T4GPU测试了release的ppocr模型，预测是正常的，没有报错

**Comment by zhangkui669** [comment]
> 麻烦提供下预测报错的指令和使用的模型以及运行环境 在linux T4GPU测试了release的ppocr模型，预测是正常的，没有报错

server版本的检测分类识别、压测的时候会出现这样的错误
