### ISSUE TITLE
如何设置预先的box的大小, 有时候一句话分了几段会分段输出

### ISSUE THREAD

**Issue by qfwysw** [PaddlePaddle/PaddleOCR#4118]
![image](https://user-images.githubusercontent.com/53482524/133918622-10db25d5-290b-4811-a16f-82c9c411c526.png)

**Comment by BeyondYourself** [comment]
应该可以修改一下最大文本长度试试

**Comment by lidh15** [comment]
这和最大文本长度有关系吗，paddlocr好像无法处理换行的情形

**Comment by BeyondYourself** [comment]
换行其他的也无法处理
