### ISSUE TITLE
Can't find module deploy/hubserving/ocr_system/, please check your spelling.

### ISSUE THREAD

**Issue by freshgeek** [PaddlePaddle/PaddleOCR#412]
在下载

hub install deploy/hubserving/ocr_system/

提示

Can't find module deploy/hubserving/ocr_system/, please check your spelling.

**Comment by littletomatodonkey** [comment]
export PYTHONPATH=.
需要先export一下python path，可以参考doc里面的serving.md

**Comment by littletomatodonkey** [comment]
export PYTHONPATH=.
需要先export一下python path，可以参考doc里面的serving.md

**Comment by freshgeek** [comment]
还是无效呢,
![image](https://user-images.githubusercontent.com/20513615/88447212-40a71f80-ce63-11ea-9564-2583943fe8f7.png)
![image](https://user-images.githubusercontent.com/20513615/88447216-4866c400-ce63-11ea-8c6c-5a7f47d95797.png)
![image](https://user-images.githubusercontent.com/20513615/88447219-53b9ef80-ce63-11ea-8fd2-858b68e333b9.png)

**Comment by freshgeek** [comment]
环境是 飞桨gpu

![image](https://user-images.githubusercontent.com/20513615/88447268-f8d4c800-ce63-11ea-9e59-77ef5e2b76e5.png)


装好了cuda 10.0
![image](https://user-images.githubusercontent.com/20513615/88447283-2588df80-ce64-11ea-9853-cdb22fbc8fb5.png)

同时装了 cuDNN 7.6.5

**Comment by littletomatodonkey** [comment]
在windows下安装的时候，需要在PaddleOCR文件夹中操作，同时
需要使用hub install deploy\hubserving\ocr_system\
因为windows下文件夹分隔符是`\`，可以看下最新的serving文档~

**Comment by freshgeek** [comment]
> 在windows下安装的时候，需要在PaddleOCR文件夹中操作，同时
> 需要使用hub install deploy\hubserving\ocr_system
> 因为windows下文件夹分隔符是`\`，可以看下最新的serving文档~

还是不行的,我在 #418  中也贴出了异常信息

**Comment by littletomatodonkey** [comment]
看截图，是找不到inference model，需要先下载inference model在指定的位置，否则无法启动服务。
