### ISSUE TITLE
GPU内存不足，迭代次数减小了也不行，怎么办

### ISSUE THREAD

**Issue by xiaohua1027** [PaddlePaddle/PaddleOCR#4120]
Out of memory error on GPU 0. Cannot allocate 28.125244MB memory on GPU 0, available memory is only 25.187500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

**Comment by ziyaxuanyi** [comment]
你GPU内存多大的，适当减少batch_size，内存和迭代次数没关系

**Comment by zhangyingying520** [comment]
还有可能这个GPU在处理其他进程
