### ISSUE TITLE
小白求解。。。。

### ISSUE THREAD

**Issue by xiaohua1027** [PaddlePaddle/PaddleOCR#4121]
如果文本框检测，是不是只需要cml一个配置文件就可以了，其他的配置文件dml,distill,student是不同的方法嘛？用了cml这个方法，直接拿预训练模型去预测，结果检测不出文本框坐标呀，用rec_distillation直接识别的话，识别出来的文字是\u831c\u7018\u8bc3这样，并不是中文。。。小白求解。。

**Comment by BeyondYourself** [comment]
编码问题，对于中文将ascii改为UTF-8
