### ISSUE TITLE
No module named 'paddle' 什么问题？

### ISSUE THREAD

**Issue by a6965921** [PaddlePaddle/PaddleOCR#4122]
我运行paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true
No module named 'paddle' 什么问题？

**Comment by xiaohua1027** [comment]
没有paddlepaddle包吧，win10CPU不能直接下载这个包，可以去网上看看解决方法

**Comment by a6965921** [comment]
paddleocr

> 没有paddlepaddle包吧，win10CPU不能直接下载这个包，可以去网上看看解决方法

paddleocr不是完美兼容win10的码

**Comment by WenmuZhou** [comment]
你没有装paddlepaddle

**Comment by kuafuwang** [comment]
> 你没有装paddlepaddle
得装paddlepaddle

**Comment by lishuaiCN** [comment]
pip install paddlepaddle

**Comment by qqqqq127** [comment]
Looking for incompatible packages.
