### ISSUE TITLE
直播录播

### ISSUE THREAD

**Issue by daeing** [PaddlePaddle/PaddleOCR#4123]
蹲一个前一段时间的对paddleocrv2的直播录播~

**Comment by songkq** [comment]
@daeing https://aistudio.baidu.com/aistudio/education/lessonvideo/1718122

**Comment by daeing** [comment]
> @daeing https://aistudio.baidu.com/aistudio/education/lessonvideo/1718122

感谢老哥~

**Comment by mrlihellohorld** [comment]
大哥  打不开啊

**Comment by daeing** [comment]
> 大哥 打不开啊

点击链接是空的，左上方有一个我的课程，然后搜索paddleocr，可以看到两个，这两个里面有一个最新的课程就是v2版本的直播
