### ISSUE TITLE
在linux跑的时候SSLCertVerificationError

### ISSUE THREAD

**Issue by HanGod1** [PaddlePaddle/PaddleOCR#4129]
刚安装想测试一下是否能跑，最后一步出现了HTTPSConnectionPool(host='paddleocr.bj.bcebos.com'                                                                                                , port=443): Max retries exceeded with url: /PP-OCRv2/chinese/ch_PP-OCRv2_det_in                                                                                                fer.tar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIF                                                                                                Y_FAILED] certificate verify failed: unable to get local issuer certificate (_ss                                                                                                l.c:1131)')))。请问各位大神如何解决？

**Comment by MissPenguin** [comment]
证书错误，网上搜一下很多解决办法，可以先试试

**Comment by zzd2001** [comment]
> 刚安装想测试一下是否能跑，最后一步出现了HTTPSConnectionPool(host='paddleocr.bj.bcebos.com' , port=443): Max retries exceeded with url: /PP-OCRv2/chinese/ch_PP-OCRv2_det_in fer.tar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIF Y_FAILED] certificate verify failed: unable to get local issuer certificate (_ss l.c:1131)')))。请问各位大神如何解决？

请问楼主解决了么？我也遇到了同样的问题
