### ISSUE TITLE
蕲 识别成 薪

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4134]
使用的是2.0server通用模型，有什么好的解决方案？除了finetune
![image](https://user-images.githubusercontent.com/66725845/134304130-1ab417ac-bbea-441e-99ba-4ff65b5d559a.png)
![image](https://user-images.githubusercontent.com/66725845/134304161-9f076765-fc21-4e76-ad53-e666d32a9211.png)
查阅了默认的中文字典，是有蕲这个字的啊

**Comment by MissPenguin** [comment]
略生僻的字是比较容易识别错，一般只能finetune了

**Comment by Essence9999** [comment]
> 略生僻的字是比较容易识别错，一般只能finetune了

能不能在通用模型的基础上，只finetune识别模型，使用只含有这个字的图片，来微调，少训练几个迭代~
请问能不能到达识别出这个字的效果？

**Comment by ziyaxuanyi** [comment]
不能，只使用只含有这个字的图片finetune，会忘记识别其他字的能力

**Comment by nissansz** [comment]
> 使用的是2.0server通用模型，有什么好的解决方案？除了finetune ![image](https://user-images.githubusercontent.com/66725845/134304130-1ab417ac-bbea-441e-99ba-4ff65b5d559a.png) ![image](https://user-images.githubusercontent.com/66725845/134304161-9f076765-fc21-4e76-ad53-e666d32a9211.png) 查阅了默认的中文字典，是有蕲这个字的啊

解决了吗？怎么微调解决？
