### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by KyrieHee** [PaddlePaddle/PaddleOCR#4135]
1.  使用Dockerfile构建了镜像
2.  远程执行 python3 tools/test_hubserving.py http://localhost:8868/predict/ocr_system  ./doc/imgs/1.jpg 
报以下错
`
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2021/09/12 08:59:05] root INFO: Predict time of ./doc/imgs/1.jpg: 0.337s
Traceback (most recent call last):
  File "tools/test_hubserving.py", line 118, in <module>
    main(server_url, image_path)
  File "tools/test_hubserving.py", line 91, in main
    res = r.json()["results"][0]
IndexError: string index out of range
`

**Comment by MissPenguin** [comment]
应该是没有结果，导致解析报错。可以直接打印r.json()看看

**Comment by KyrieHee** [comment]
已经修复，多谢

**Comment by wdfnst** [comment]
> 已经修复，多谢

请问啥原因，怎么解决？

**Comment by bldu** [comment]
> 已经修复，多谢

请问如何解决的？

**Comment by zyzz1974** [comment]
怎么修复的？

**Comment by Han-Y-F** [comment]
> > 已经修复，多谢
> 
> 请问啥原因，怎么解决？

请问如何修复的？

**Comment by xuxh6** [comment]
这个问题还是普遍存在啊
