### ISSUE TITLE
ValueError: Not found GPU in current device. Please check your device or set args.use_gpu as False

### ISSUE THREAD

**Issue by huafeihuayu** [PaddlePaddle/PaddleOCR#4138]
![image](https://user-images.githubusercontent.com/54087172/134330159-e39f34e0-18e1-4979-9746-5be92c654da9.png)

PPStructure  error

**Comment by MissPenguin** [comment]
如报错所示：机器上没有GPU，需要使用CPU，加个参数 --use_gpu=Fasle
