### ISSUE TITLE
crnn paddle模型转onnx输入格式怎么设置？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4139]
![image](https://user-images.githubusercontent.com/48303408/134333737-2f23591e-17bc-4d49-abb2-e8adfda63884.png)
请问识别模型crnn  paddle模型转onnx输入格式怎么设置？

**Comment by MissPenguin** [comment]
可以参考Paddle2ONNX官网教程哈：https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/README_zh.md，里面还有专门针对PPOCR的案例

**Comment by MissPenguin** [comment]
可以参考Paddle2ONNX官网教程哈：https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/README_zh.md ，里面还有专门针对PPOCR的案例
