### ISSUE TITLE
Docker执行报No module named 'tools.infer'

### ISSUE THREAD

**Issue by TonyK-T** [PaddlePaddle/PaddleOCR#414]
我在Docker容器里面执行安装了hub,但是在 执行 hub install deploy/hubserving/ocr_system/ 还是报以下错误
    from tools.infer.utility import base64_to_cv2
ModuleNotFoundError: No module named 'tools.infer'

docker执行如下：
# Install paddlehub  
pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple

# Set environment variables  
export PYTHONPATH=.

hub install deploy/hubserving/ocr_system/

**Comment by MissPenguin** [comment]
是按照 快速开始 安装的环境吗（https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md）？能用tools/infer/predict_system.py正常预测吗？

**Comment by MissPenguin** [comment]
是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md

能用tools/infer/predict_system.py正常预测吗？

**Comment by TonyK-T** [comment]
> 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> 
> 能用tools/infer/predict_system.py正常预测吗？

已解决，环境问题导致，

**Comment by TonyK-T** [comment]
> 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> 
> 能用tools/infer/predict_system.py正常预测吗？

这个问题已解决，是环境问题导致，
另外出现了新问题：
问题-1：hub install deploy/hubserving/ocr_system/  默认安装的好像是 chinese_db_crnn_mobile轻量模型，如何指定安装通用模型？ 我是把所有的模型都解压到 interface 目录

多谢了

**Comment by TonyK-T** [comment]
> 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> 
> 能用tools/infer/predict_system.py正常预测吗？

另外-优化：docker部署 可以写成 Dockerfile 的形式吗？ 这样docker部署会方便很多

**Comment by MissPenguin** [comment]
> > 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> > 能用tools/infer/predict_system.py正常预测吗？
> 
> 这个问题已解决，是环境问题导致，
> 另外出现了新问题：
> 问题-1：hub install deploy/hubserving/ocr_system/ 默认安装的好像是 chinese_db_crnn_mobile轻量模型，如何指定安装通用模型？ 我是把所有的模型都解压到 interface 目录
> 
> 多谢了

hub install deploy/hubserving/ocr_system/ 安装的是ocr_system，不是hub内置的chinese_db_crnn_mobile。ocr_system模块内可以修改模型路径和其他参数，修改方式参考https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%AE%E6%94%B9%E6%9C%8D%E5%8A%A1%E6%A8%A1%E5%9D%97

**Comment by MissPenguin** [comment]
> > 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> > 能用tools/infer/predict_system.py正常预测吗？
> 
> 另外-优化：docker部署 可以写成 Dockerfile 的形式吗？ 这样docker部署会方便很多

这个有需要的话自己操作一下哈~

**Comment by TonyK-T** [comment]
> > > 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> > > 能用tools/infer/predict_system.py正常预测吗？
> > 
> > 
> > 这个问题已解决，是环境问题导致，
> > 另外出现了新问题：
> > 问题-1：hub install deploy/hubserving/ocr_system/ 默认安装的好像是 chinese_db_crnn_mobile轻量模型，如何指定安装通用模型？ 我是把所有的模型都解压到 interface 目录
> > 多谢了
> 
> hub install deploy/hubserving/ocr_system/ 安装的是ocr_system，不是hub内置的chinese_db_crnn_mobile。ocr_system模块内可以修改模型路径和其他参数，修改方式参考https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%AE%E6%94%B9%E6%9C%8D%E5%8A%A1%E6%A8%A1%E5%9D%97


参照url修改方式，我尝试更改 parmas.py 模型路径(只改了路径) 运行报错了，
python model.py 报：No module named paddlehub.common.logger
hub uninstall ocr_system 报： ocr_system is not installed
 hub serving start -m ocr_system 报：Can't find module ocr_system, please check your spelling 

操作步骤：
1.hub serving stop - 8866
2.修改 params.py 文件，cfg.det_model_dir=和cfg.rec_model_dir= 指向通用模型目录
3. hub uninstall ocr_system 报：模型没安装
4. hub install deploy/hubserving/ocr_system/ 报：找不到模型
5. hub serving start -m ocr_system 报 Can't find module ocr_system, please check your spelling

**Comment by TonyK-T** [comment]
> > > > 是按照 快速开始 安装的环境吗？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md
> > > > 能用tools/infer/predict_system.py正常预测吗？
> > > 
> > > 
> > > 这个问题已解决，是环境问题导致，
> > > 另外出现了新问题：
> > > 问题-1：hub install deploy/hubserving/ocr_system/ 默认安装的好像是 chinese_db_crnn_mobile轻量模型，如何指定安装通用模型？ 我是把所有的模型都解压到 interface 目录
> > > 多谢了
> > 
> > 
> > hub install deploy/hubserving/ocr_system/ 安装的是ocr_system，不是hub内置的chinese_db_crnn_mobile。ocr_system模块内可以修改模型路径和其他参数，修改方式参考https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%AE%E6%94%B9%E6%9C%8D%E5%8A%A1%E6%A8%A1%E5%9D%97
> 
> 参照url修改方式，我尝试更改 parmas.py 模型路径(只改了路径) 运行报错了，
> python model.py 报：No module named paddlehub.common.logger
> hub uninstall ocr_system 报： ocr_system is not installed
> hub serving start -m ocr_system 报：Can't find module ocr_system, please check your spelling
> 
> 操作步骤：
> 1.hub serving stop - 8866
> 2.修改 params.py 文件，cfg.det_model_dir=和cfg.rec_model_dir= 指向通用模型目录
> 3. hub uninstall ocr_system 报：模型没安装
> 4. hub install deploy/hubserving/ocr_system/ 报：找不到模型
> 5. hub serving start -m ocr_system 报 Can't find module ocr_system, please check your spelling

see img
![1595571230](https://user-images.githubusercontent.com/11296126/88365560-02edbc80-cdb9-11ea-96bd-68f271d69d6e.jpg)

**Comment by MissPenguin** [comment]
我这边验证换到通用大模型是正常的。

” python model.py 报：No module named paddlehub.common.logger “
注意执行路径和python版本，可能应该执行的是： python3 deploy/hubserving/ocr_system/module.py

" 4. hub install deploy/hubserving/ocr_system/ 报：找不到模型 "
这一步的报错信息截图看下

**Comment by MissPenguin** [comment]
可以参考这里的解决方案：https://github.com/PaddlePaddle/PaddleOCR/issues/392#issuecomment-664915158
