### ISSUE TITLE
StyleText数据合成问题

### ISSUE THREAD

**Issue by pyh13258102131** [PaddlePaddle/PaddleOCR#4140]
挑选了效果很好的背景切割图片，合成数据，发现官方提供模型不能识别的文字合成后的效果很差
比如“你因何事被羁押”，其中“羁”字使用官方提供的模型不能正确识别出来此文字，合成后“羁”字效果很差，其他字都很好，效果如下
![pan_浣犳槸鍥犱綍浜嬩簬浣曟椂琚緛鎶糭18_40_crop_2 jpg](https://user-images.githubusercontent.com/44732329/134337401-a7a6f2a1-0069-45d5-8860-65eafd2f81d4.png)

请问这是因为会调用识别模型吗，或者其他原因

**Comment by weisy11** [comment]
有2个原因：1.训练数据中，生僻字的出现不太多；2.这个字的笔画比较多，中间容易糊…后续会继续优化模型的，欢迎关注
