### ISSUE TITLE
ch_PP-OCRv2_det_infer model Conver To ONNX    result  0

### ISSUE THREAD

**Issue by Fanky186** [PaddlePaddle/PaddleOCR#4141]
I converted the V2 det model to onnx , by paddle2onnx, but reasoning with onnxRuntime kept getting 0.
and no errors were reported in this procedure of paddle2onnx.

![2021-09-22 20-44-58屏幕截图](https://user-images.githubusercontent.com/42005895/134346497-79d274fc-a36f-442c-8764-d4cc7471c250.png)

**Comment by Fanky186** [comment]
I downloaded the inference model file directly,  then paddle2onnx, get the error

**Comment by jiangjiajun** [comment]
Hi, @Fanky186 

Normally, we keep the same inputs to PaddlePaddle model and ONNX model to check if the output keeps same.

So, in this case, you can try following the steps to validate  ONNX model
- 1. dump inputs data, which is preprocessed, and dumped as pickle file or `.npy` file
- 2. use `paddle.static.load_inference_model` to load paddlepaddle model, and run result with inputs from step1
- 3. use onnxruntime to load ONNX model, and run result with inputs from step1
- 4. check the results in step2 and step3

**Comment by Fanky186** [comment]
@ jiangjiajun
Yes, I did. Paddle is right, but onnx is always 0. The only difference is the way I load the paddle model. I load paddle model use 
   config = paddle.inference.Config(model_file, params_file) , paddle.inference.create_predictor(config)

**Comment by Fanky186** [comment]
This is the transformed onnx  model structure:
![2021-09-23 11-50-21屏幕截图](https://user-images.githubusercontent.com/42005895/134452237-c5cd168c-f731-4ba2-9ac4-26f0350cdb95.png)

**Comment by jiangjiajun** [comment]
@Fanky186 Please provide your exported PaddlePaddle model, and inputs data (dumped as pickle data), I'll try to reproduce your problem

**Comment by Fanky186** [comment]
@jiangjiajun 
Hi,This is pickle data,and PaddlePaddle model
[det_model、data.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7216737/det_model.data.zip)

**Comment by Fanky186** [comment]
Hi @jiangjiajun 
This is PaddlePaddle model and input data
[model_data.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7216756/model_data.zip)

**Comment by jiangjiajun** [comment]
@Fanky186 I found that you are dump data in a text file `model_data/data.txt`, please let me know how to load this data

**Comment by Fanky186** [comment]
@jiangjiajun 
f1 = open('data.txt', 'rb')
data = pickle.load(f1)

**Comment by Fanky186** [comment]
![2021-09-23 20-39-29屏幕截图](https://user-images.githubusercontent.com/42005895/134508155-578cabe6-a871-4a6b-9937-28dfbe2e57b8.png)

**Comment by Fanky186** [comment]
![2021-09-23 20-42-09屏幕截图](https://user-images.githubusercontent.com/42005895/134508520-20825901-fadb-41e3-9351-56a3cb73887c.png)

**Comment by jiangjiajun** [comment]
I have tested convert model with
`paddle2onnx --model_dir . --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file model.onnx --opset_version 11`

and use `run_diff.py` to check the results, and the diff is totally fine.

[model_data_jason.tar.gz](https://github.com/PaddlePaddle/PaddleOCR/files/7217665/model_data_jason.tar.gz)
=

**Comment by Fanky186** [comment]
@jiangjiajun 
Thank you,I know where I went wrong

**Comment by Fanky186** [comment]
@jiangjiajun 
Hello, can this onnx model fix the input size（shape）? I want to convert to the tensorRT model, but I don't want to use dynamic input sizes.

**Comment by Fanky186** [comment]
@jiangjiajun 
I have converted it to tensorRT's model, showing the difference as shown, is this normal？
![image](https://user-images.githubusercontent.com/42005895/134606367-bd6976a6-d1a2-4e5d-ba24-873e2f01fb3a.png)

**Comment by jiangjiajun** [comment]
Since your model is a detection model, the coordinate may has a large range, I think the difference may not be suitable to check if the result is correct, use following method to check the difference.

```
absolute_diff = np.fabs(paddle_result - trt_result)
relative_diff = absolute_diff / (np.fabs(paddle_result) + 1e-06)
print(absolute_diff.max(), relative_diff.max())
```
check the `relative_diff`

**Comment by Fanky186** [comment]
@jiangjiajun 
I just tried it as you said, and the results are as follows
![image](https://user-images.githubusercontent.com/42005895/134610205-6740563b-6da2-42ba-86cb-bce616fc5fb8.png)

**Comment by Fanky186** [comment]
@jiangjiajun
I just tried it as you said, and the results are as follows
![image](https://user-images.githubusercontent.com/42005895/134612743-c6f26c8a-c8bd-45d3-a776-a58166564711.png)

**Comment by Fanky186** [comment]
@jiangjiajun
[model.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7222054/model.zip)
 
This is my tensorRT model:

**Comment by jiangjiajun** [comment]
In this case, I think the result may not be right. Since we have checked the result is correct, maybe you need ask help from TensorRT.
