### ISSUE TITLE
采用自己训练的server模型做预训练模型

### ISSUE THREAD

**Issue by melon12321** [PaddlePaddle/PaddleOCR#4145]
采用自己训练的server模型做预训练模型，teacher模型精度很高，两个student模型的精度都是0是怎么回事呢？

![1](https://upload-images.jianshu.io/upload_images/20803730-4328f5d0e8225977.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by LDOUBLEV** [comment]
看下你的student 的loss有没有持续降低，是否收敛了
