### ISSUE TITLE
使用GPU推理第一次调用CopyFromCpu时很慢

### ISSUE THREAD

**Issue by WillisXue** [PaddlePaddle/PaddleOCR#4146]
环境：
windows10 + vs2019 x64
cuda11.0 cuda_11.0.2_451.48_win10 TensorRT-7.2.2.3
cuda11.0_cudnn8_avx_mkl_trt7

模型：en_number_mobile_v2.0_rec_infer

use_tensorrt=false

使用GPU推理时第一次调用CopyFromCpu很慢，大概要1秒多钟，第二次调用时间正常

![image](https://user-images.githubusercontent.com/9125768/134448786-a6d03e72-0441-4668-8498-b729157f35e7.png)

**Comment by LDOUBLEV** [comment]
第一次会比较慢，建议真正运行前先做一次warmup，https://github.com/tink2123/PaddleOCR/blob/309a850c05387bef98530c9ab749d553239ef2e2/tools/infer/predict_system.py#L123
