### ISSUE TITLE
提高字典中一个生僻字的识别效果，如何finetune保证server原有的识别精度不会有损失？数据量应该多少呢

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4147]
提高字典中一个生僻字的识别效果，如何finetune保证server原有的识别精度不会有损失？数据量应该多少呢

**Comment by LDOUBLEV** [comment]
> 如何finetune保证server原有的识别精度不会有损失？数据量应该多少呢

请问是哪个生僻字识别效果不好，确定是某个字识别错吗，也可能是背景或者其他因素影响

finetune的 话，建议找一些中文和英文数据集，包括：lsvt上的中文数据，再加一些合成数据，这些数据能凑够20W左右，应该是够了

**Comment by Essence9999** [comment]
> > 如何finetune保证server原有的识别精度不会有损失？数据量应该多少呢
> 
> 请问是哪个生僻字识别效果不好，确定是某个字识别错吗，也可能是背景或者其他因素影响
> 
> finetune的 话，建议找一些中文和英文数据集，包括：lsvt上的中文数据，再加一些合成数据，这些数据能凑够20W左右，应该是够了

蕲
绰
浉
姣
嫣
识别错误。

20w finetune 通用识别模型够用吗？

**Comment by ziyaxuanyi** [comment]
兄弟，你是自己学习这个做的玩，还是做具体的工程落地应用。如果是自己学习做的玩的话，20w足够了。但如果是做具体的工程落地应用的话，建议根据实际应用场景来制作真实数据和合成数据，总共数据量大概要千万级别以上，才会有比较不错的效果。

**Comment by ziyaxuanyi** [comment]
> > 兄弟，你是自己学习这个做的玩，还是做具体的工程落地应用。如果是自己学习做的玩的话，20w足够了。但如果是做具体的工程落地应用的话，建议根据实际应用场景来制作真实数据和合成数据，总共数据量大概要千万级别以上，才会有比较不错的效果。
> 
> 好奇千万级别的数据怎么标注的？一张一张图片人工确定吗？

少量真实数据，大部分都是合成工具合成的
