### ISSUE TITLE
无法识别数位数字

### ISSUE THREAD

**Issue by cx4** [PaddlePaddle/PaddleOCR#4148]
![image](https://user-images.githubusercontent.com/41991295/134455600-acc59e4e-1d39-497e-9b9f-ea5160ca25ca.png)

对数位数字的识别无法正常识别。

**Comment by LDOUBLEV** [comment]
目前发布的模型用的训练数据中，数码管，电子表数据很少，所以这类场景识别效果偏差

建议在我们模型的基础上，用你们的数据finetune训练

如果您有很多这样的数据，是否方便开源出来，我们加到现有的训练数据中，可以进一步提升这种场景的识别精度

**Comment by cx4** [comment]
> 目前发布的模型用的训练数据中，数码管，电子表数据很少，所以这类场景识别效果偏差
> 
> 建议在我们模型的基础上，用你们的数据finetune训练
> 
> 如果您有很多这样的数据，是否方便开源出来，我们加到现有的训练数据中，可以进一步提升这种场景的识别精度

谢谢，我尝试训练一下吧。
