### ISSUE TITLE
无法安装服务模块

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#415]
![image](https://user-images.githubusercontent.com/29020213/88371695-1dc72d80-cdc7-11ea-981c-d97f7e3cdbfa.png)

看过serving.md的教程,卡在这一步了,python的环境变量也已经配置成功了,就是不行

**Comment by xxllp** [comment]
拼写错了

**Comment by mdddj** [comment]
> 拼写错了

文档直接复制的...

**Comment by freshgeek** [comment]
我也是这个问题,cpu 能安装成功gpu 版本不知道哪个步鄹不对,每一步都是按着文档的 配置了PYTHONPATH 也没用

**Comment by mdddj** [comment]
> 我也是这个问题,cpu 能安装成功gpu 版本不知道哪个步鄹不对,每一步都是按着文档的 配置了PYTHONPATH 也没用

我已经提交了两个iss

**Comment by mdddj** [comment]
> 我也是这个问题,cpu 能安装成功gpu 版本不知道哪个步鄹不对,每一步都是按着文档的 配置了PYTHONPATH 也没用

得到回复了,要在他们项目目录下执行命令

**Comment by littletomatodonkey** [comment]
你好，windows下的分隔符号是反斜杠，可以参考这个issue： #418 ，我提交了windows 文档部署的PR：你也可以参考下：#421
