### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by RyanCCC** [PaddlePaddle/PaddleOCR#4151]
请问训练的时候执行以下命令，报错了如下截图所示：
```sh
paddle.utils.run_check()
```
![image](https://user-images.githubusercontent.com/27406337/134468916-e9fbb7b3-fffa-4a5a-b4cb-5678c0c6196a.png)

cuda版本：
![image](https://user-images.githubusercontent.com/27406337/134468808-257ccb8e-ad76-4ebb-aa48-234636139539.png)

**Comment by LDOUBLEV** [comment]
是paddle没有安装好的问题，麻烦在这里提issue吧，https://github.com/PaddlePaddle/Paddle/issues，会有专门的人解答
