### ISSUE TITLE
Paddle OCR跨行文本问题

### ISSUE THREAD

**Issue by lidh15** [PaddlePaddle/PaddleOCR#4153]
如果文本是一个段落的话不会被识别为一个完整的文本框，而是每行一个文本框，微信就可以识别为一整段，只是微信的没开源

**Comment by lidh15** [comment]
#4118 像这种

**Comment by siwing** [comment]
可以在拿到Paddle OCR的结果后，根据文本框的坐标将跨行文本合并。

**Comment by lidh15** [comment]
希望PaddleOCR可以添加一个参数来做这个功能
