### ISSUE TITLE
The shape of model params......not matched with loaded params......

### ISSUE THREAD

**Issue by MrCuiHao** [PaddlePaddle/PaddleOCR#4156]
你好，我在训练DB文字检测的时候，提示这个错误 The shape of model params......not matched with loaded params......，如下图所示：
![image](https://user-images.githubusercontent.com/37323877/134503769-91271147-101d-454f-aa7e-a56fa3d082e4.png)
预训练模型是从你们写的那个文本检测文档里下载的，下载路径如下图所示：
![image](https://user-images.githubusercontent.com/37323877/134504522-4db585e1-0546-461b-9724-faef86f84024.png)
![image](https://user-images.githubusercontent.com/37323877/134504248-f14214ab-5e8f-45b5-8a30-cb7e5245d87f.png)

是提供的预训练模型不对吗？

**Comment by LDOUBLEV** [comment]
你好，这个是backbone的预训练模型，是一个分类模型，在OCR任务里，不需要分类网络的后几个层了，所以这几个参数加载不上

打印的日志不是报错，是一个警告，提示shape没对上，这个是正常的，请忽略，后续会优化下该部分提示信息
