### ISSUE TITLE
按官方文档基于Docker方式部署无法按QuickStart文档进行体验

### ISSUE THREAD

**Issue by gongjimin** [PaddlePaddle/PaddleOCR#4164]
初步看是```https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/environment_en.md```这个文档中提供的
```paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82```容器镜像的问题导致的。
该容器镜像内提供了python2和python3。
使用pip安装默认是基于python2，但paddleocr并不支持python2。
该容器镜像内的python3默认是3.5。paddleocr从2.0.2之后就无法在python3.5上使用pip3安装了。而piddleocr2.0.2有缺陷导致QuickStart文档中提到的“--lang en”选项在使用时会导致程序异常终止。
如果paddleocr2.0计划支持Python3.5，应该在相关依赖的版本上使用Python3.5支持的版本。

**Comment by LDOUBLEV** [comment]
倒是忽略了官方镜像的这个问题 -_-!

如果用镜像就默认用python3.7 吧，或者把默认的python3改为python3.7 

镜像里除了python3.5，还有python3.6 和python3.7 

关于这个问题，非常抱歉，稍后会改一下文档

**Comment by neozhu** [comment]
@gongjimin 你用的是docker hub官网的镜像部署的吗？
可以分享一下你的docker 运行命令吗？我也像部署一下只要能通过 web api调用就好

**Comment by LDOUBLEV** [comment]
你好，目前飞桨开发镜像中默认的python3版本是python3.5，但是这样镜像也包含python3.7，在执行python脚本的时候需要python3.7  run_py.py 才会默认使用python3.7版本；
同时，我们也更新了推荐镜像，新的镜像默认python3是python3.7版本，见文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/environment_en.md#132-docker-environment-preparation

**Comment by FrankScarlet** [comment]
[OCR Docker部署](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/docker/hubserving/README_cn.md)的Dockerfile中，使用的镜像是`registry.baidubce.com/paddlepaddle/paddle:2.0.0`。

1. 是否有registry.baidubce.com的界面，需要对这些`tag`区别的说明

我想要尝试Docker部署OCR服务，上面那个镜像我拉了很久才下好，本地电脑快卡死，才发现是个10GB+的镜像。
我看Docker Hub上`2.2.0`和`2.2.1`也有很小的版本。发现`2.0.0`的这个镜像有100个步骤，`2.2.0`的只有50步。

如果说`registry.baidubce.com`只是`hub.docker`的镜像站（用于加速），那就不需要额外的界面。希望之后能增加大致的版本的说明。我这里引用的文档1和这个issue指出的文档2，用了很不一样的镜像。过多的`tag`让人困扰

2. 是否可以用`2.2.0`的镜像来做OCR Docker部署，替换原本[Dockerfile](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/docker/hubserving/cpu/Dockerfile)

我一会儿试一试，我不确定Dockerfile加载的训练好的模型，在paddle2.0.0和paddle2.2.0 能否混用。能用更小的镜像，也方便大家体验、开发、部署啥的
