### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4166]
麻烦问一下，
![image](https://user-images.githubusercontent.com/80818728/134625038-5c189fd1-17c3-4451-9d48-14fe37ca700e.png)
zh这两个数据代表的是训练集和测试集的图片数吗

**Comment by ziyaxuanyi** [comment]
是一个迭代数epoch的迭代数，迭代数 x batch_size x 显卡数目 = 图片总数
