### ISSUE TITLE
use_multiprocess参数问题

### ISSUE THREAD

**Issue by 934453938** [PaddlePaddle/PaddleOCR#4167]
纯CPU机器
使用hub serving start -m chinese_ocr_db_crnn_server启动没有问题
使用hub serving start -m chinese_ocr_db_crnn_server --use_multiprocess --workers启动就一直报错：
File "D:\Program\anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by BeyondYourself** [comment]
命令不对吧，既然你要用到多线程，你应该指定线程数或者其他，上面的是参数后面需要你指定具体值
eg:--use_multiprocess  True  --workers  10

**Comment by 934453938** [comment]
> 命令不对吧，既然你要用到多线程，你应该指定线程数或者其他，上面的是参数后面需要你指定具体值
> eg:--use_multiprocess True --workers 10

--use_multiprocess和--workers都是有默认值的，--use_multiprocess的默认值是true,指定为True，服务启动的时候就会报错

**Comment by BeyondYourself** [comment]
你这个命令是不是有问题 ，参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/7d4147b7f7e2a3c13957aeb7519f5299527609e2/deploy/hubserving/readme.md#:~:text=%E4%BD%BF%E7%94%A8%E6%AD%A4%E6%96%B9%E5%BC%8F-,Windows%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8F%AA%E6%94%AF%E6%8C%81%E5%8D%95%E8%BF%9B%E7%A8%8B%E6%96%B9%E5%BC%8F,---workers)

**Comment by 934453938** [comment]
> 你这个命令是不是有问题 ，参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/7d4147b7f7e2a3c13957aeb7519f5299527609e2/deploy/hubserving/readme.md#:~:text=%E4%BD%BF%E7%94%A8%E6%AD%A4%E6%96%B9%E5%BC%8F-,Windows%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8F%AA%E6%94%AF%E6%8C%81%E5%8D%95%E8%BF%9B%E7%A8%8B%E6%96%B9%E5%BC%8F,---workers)

我的命令没有问题，就是参考教程来的。。。

**Comment by hanzhangyu** [comment]
我已收到你的邮件
