### ISSUE TITLE
请问ppocr训练的crnn模型可以转为openvino模型吗？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4169]
请问ppocr训练的crnn模型可以转为openvino模型吗？

**Comment by tink2123** [comment]
可以的，百度上有一些教程，可以自行搜索

**Comment by Dandelion111** [comment]
> 可以的，百度上有一些教程，可以自行搜索

你好，PaddleX的转换工具是不是只能转换PaddleX训练的模型，它转换的时候需要的配置文件是yml格式，请问除了这个还有什么工具可以转换吗
