### ISSUE TITLE
ocr_system.sln Compilation error

### ISSUE THREAD

**Issue by xhggstudy** [PaddlePaddle/PaddleOCR#4176]
![image](https://user-images.githubusercontent.com/91367058/134764520-2357885f-8fd0-4b9b-a8ec-e60c0fc818d0.png)
![image](https://user-images.githubusercontent.com/91367058/134764532-98e0c3e4-1e87-4b50-bfd5-4af61be807ac.png)
Hello, there are many errors when compiling SLN

Why is this? No error is reported during cmake, but there is no OpenCV_ Dir only opencv_ DIR
![image](https://user-images.githubusercontent.com/91367058/134764585-6ed90d0b-bd10-4d05-8928-72aec73423a7.png)

**Comment by Gmgge** [comment]
提供个简单的辅助信息：ppocr2.3，vs2019，根据官方的编译文档流程正常编译，遇到两个问题在文档的最后也有提示。
建议增加ocr版本信息以及编译器信息等更详细的信息以更有效的获得帮助。

**Comment by LDOUBLEV** [comment]
please reference to doc :https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/docs/windows_vs2019_build.md

**Comment by gl94** [comment]
> 提供个简单的辅助信息：ppocr2.3，vs2019，根据官方的编译文档流程正常编译，遇到两个问题在文档的最后也有提示。
> 建议增加ocr版本信息以及编译器信息等更详细的信息以更有效的获得帮助。

您好，按照官方的走，最后在vs里是文件夹视图，不是项目，如何添加dirent.h的路径到属性页里？
![1632740114(1)](https://user-images.githubusercontent.com/26252750/134895644-f9263379-d949-4d82-8c6a-5be4668b166c.png)
