### ISSUE TITLE
如何用openvino读取ppocr训练的模型？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4177]
如何用openvino读取ppocr训练的模型？有没有相关的资料或者demo呢？

**Comment by WenmuZhou** [comment]
可以试下onnx做个中间转换

**Comment by Dandelion111** [comment]
> 可以试下onnx做个中间转换
试过先转onnx在转openvino，但是转过之后的输出shape完全不对。不知道中间有没有什么要注意的地方

**Comment by QAiStudio** [comment]
解决了吗？有没有openvinoC++版demo可以展示一下？
