### ISSUE TITLE
关于修改特征提取网络

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#4179]
最近在做古籍识别相关的工作，发现paddleocr里的CRNN部分的MobileNet_v3的网络比较大，有11个Residual Unit。由于paddleocr是针对许多不同场景的识别情况的，所以特征提取网络需要大一点。但是我现在是在针对特定的场景做识别，感觉网络也不需要那么大，所以想做一些压缩。不知有没有什么建议？感谢ORZ

**Comment by ioracion** [comment]
你可能需要[PaddleSlim](https://github.com/PaddlePaddle/PaddleSlim)
