### ISSUE TITLE
我无法安装检测+识别串联服务模块,三天没解决

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#418]
已经配置了环境变量
![image](https://user-images.githubusercontent.com/29020213/88445940-9924ef80-ce58-11ea-97d0-8098e745477a.png)
t他提示
![image](https://user-images.githubusercontent.com/29020213/88445967-dbe6c780-ce58-11ea-817c-b7bcbe085c91.png)

**Comment by littletomatodonkey** [comment]
在windows下，命令行中需要这样设置python path
```
SET PYTHONPATH=.
```
可以参考这篇文档
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md

**Comment by mdddj** [comment]
> 在windows下，命令行中需要这样设置python path
> 
> ```
> SET PYTHONPATH=.
> ```
> 
> 可以参考这篇文档
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md

抱歉,还是不行
![image](https://user-images.githubusercontent.com/29020213/88451011-fb481980-ce85-11ea-8960-10e6af01b1f3.png)

**Comment by littletomatodonkey** [comment]
你需要在PaddleOCR的文件夹下执行这些命令~

**Comment by mdddj** [comment]
> 你需要在PaddleOCR的文件夹下执行这些命令~

谢谢,我尝试安装它,但是出现下面错误
![image](https://user-images.githubusercontent.com/29020213/88451098-b2449500-ce86-11ea-838b-8b0bf00eb678.png)

**Comment by littletomatodonkey** [comment]
你好，我在本地尝试复现下

**Comment by mdddj** [comment]
> 你好，我在本地尝试复现下

这是我的python版本信息
```
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

**Comment by mdddj** [comment]
> 你好，我在本地尝试复现下

和这个问题一样,https://github.com/PaddlePaddle/PaddleOCR/issues/392#issue-662817819

**Comment by littletomatodonkey** [comment]
嗯嗯 我在windows上跑基于python3.6复现了，稍等我排查下哈，谢谢你的反馈~

**Comment by littletomatodonkey** [comment]
你好，需要将hub install的内容变成下面这样
```
hub install deploy\hubserving\ocr_det\
```
因为windows上的路径是`\`作为分隔符的，这块我们稍后也更新下文档

**Comment by mdddj** [comment]
> 你好，需要将hub install的内容变成下面这样
> 
> ```
> hub install deploy\hubserving\ocr_det\
> ```
> 
> 因为windows上的路径是`\`作为分隔符的，这块我们稍后也更新下文档

兄弟,不行啊
![image](https://user-images.githubusercontent.com/29020213/88451683-2f720900-ce8b-11ea-925c-a30c62e78a14.png)

**Comment by littletomatodonkey** [comment]
> > 你好，需要将hub install的内容变成下面这样
> > ```
> > hub install deploy\hubserving\ocr_det\
> > ```
> > 
> > 
> > 因为windows上的路径是`\`作为分隔符的，这块我们稍后也更新下文档
> 
> 兄弟,不行啊
> ![image](https://user-images.githubusercontent.com/29020213/88451683-2f720900-ce8b-11ea-925c-a30c62e78a14.png)

每次新打开终端的时候需要先设置下python path

```
SET PYTHONPATH=.
```

**Comment by mdddj** [comment]
> > > 你好，需要将hub install的内容变成下面这样
> > > ```
> > > hub install deploy\hubserving\ocr_det\
> > > ```
> > > 
> > > 
> > > 因为windows上的路径是`\`作为分隔符的，这块我们稍后也更新下文档
> > 
> > 
> > 兄弟,不行啊
> > ![image](https://user-images.githubusercontent.com/29020213/88451683-2f720900-ce8b-11ea-925c-a30c62e78a14.png)
> 
> 每次新打开终端的时候需要先设置下python path
> 
> ```
> SET PYTHONPATH=.
> ```

小哥哥,方便加个qq413153189远程吗,帮忙安装一下,试了一下还是不行

**Comment by littletomatodonkey** [comment]
报什么错呢？缺少安装包的话，按照提示安装即可

**Comment by freshgeek** [comment]
请问如何解决的呢? 能不能贴出来?
根据文档改了之后还是报错

![image](https://user-images.githubusercontent.com/20513615/88458316-c2c53180-cebf-11ea-8e2d-cfcf415eb92e.png)

![image](https://user-images.githubusercontent.com/20513615/88458318-c789e580-cebf-11ea-857e-8d614947b55b.png)

**Comment by BeyondYourself** [comment]
统一设置成  “/”,这样就不用区分win和Linux，win可以识别/路径的

**Comment by littletomatodonkey** [comment]
> 请问如何解决的呢? 能不能贴出来?
> 根据文档改了之后还是报错
> 
> ![image](https://user-images.githubusercontent.com/20513615/88458316-c2c53180-cebf-11ea-8e2d-cfcf415eb92e.png)
> 
> ![image](https://user-images.githubusercontent.com/20513615/88458318-c789e580-cebf-11ea-857e-8d614947b55b.png)

启动服务的时候提示找不到inference model，需要先下载inference model在指定的路径

**Comment by mdddj** [comment]
> > 请问如何解决的呢? 能不能贴出来?
> > 根据文档改了之后还是报错
> > ![image](https://user-images.githubusercontent.com/20513615/88458316-c2c53180-cebf-11ea-8e2d-cfcf415eb92e.png)
> > ![image](https://user-images.githubusercontent.com/20513615/88458318-c789e580-cebf-11ea-857e-8d614947b55b.png)
> 
> 启动服务的时候提示找不到inference model，需要先下载inference model在指定的路径

抱歉,我安装过程还是遇到错误,ModuleNotFoundError: No module named 'tools.infer'

以下是报错信息
```
(venv) D:\text-d\PaddleOCR-develop>hub install deploy\hubserving\ocr_det\
Traceback (most recent call last):
  File "c:\users\eee\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\eee\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eee\AppData\Local\Programs\Python\Python37\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\commands\install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\module\manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\module\module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "c:\users\eee\appdata\local\programs\python\python37\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "c:\users\eee\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "deploy\hubserving\ocr_det\module.py", line 22, in <module>
    from tools.infer.utility import base64_to_cv2
ModuleNotFoundError: No module named 'tools.infer'

```
![image](https://user-images.githubusercontent.com/29020213/88494710-ca80f500-cfe9-11ea-9892-652d9ccfef9c.png)

**Comment by mdddj** [comment]
解决惹,感谢@littletomatodonkey

**Comment by nn3126** [comment]
怎么解决的不说一下的吗？

**Comment by mdddj** [comment]
> 怎么解决的不说一下的吗？

检查依赖环境,重新安装一遍试试

**Comment by nn3126** [comment]
我这边运行检查都是通过的。No module named 'tools.infer' 这个问题是哪个依赖环境的有问题？哪个组件什么版本的？

**Comment by TopGun666** [comment]
Run this in terminal, this issue will be solved.
```bash
export PYTHONPATH=.
```

**Comment by ibetsun** [comment]
export PYTHONPATH=. 
centos 或ubuntu中要先这个配置变量，然后再hub install

**Comment by ysy2025** [comment]
This question can be solved through this way, and you do not need to change any .py file
first SET PYTHONPATH=. when you start a new cmd in Windows
second hub install C:\Users\XXX\Anaconda3\Lib\site-packages\PaddleOCR\deploy\hubserving\ocr_system, I use the full path and the install process worked.
![hub](https://user-images.githubusercontent.com/48482673/102966620-39c42c00-452b-11eb-8c72-24e91ae8021d.png)
Hope This Help.
