### ISSUE TITLE
串联测试

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4181]
执行这段代码使用官方给的检测和识别模型可以出结果，但是识别的结果不准!python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" 
执行这段代码，用官方的检测模型，自己的识别模型! python/tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="inference/rec_infer/" 
不出结果
![image](https://user-images.githubusercontent.com/80818728/134791612-160eef27-2382-49aa-9238-cea281c5330d.png)
麻烦问一下，这种情况怎么解决

**Comment by ziyaxuanyi** [comment]
先将识别模型的drop阈值调为0,看看检测模型结果是否正常，再判断是检测模型还是识别模型问题

**Comment by zhangyingying520** [comment]
> 先将识别模型的drop阈值调为0,看看检测模型结果是否正常，再判断是检测模型还是识别模型问题

![image](https://user-images.githubusercontent.com/80818728/134798654-d2343719-7c91-4d79-8c3b-c9e8503b015d.png)
s是改这里吗

**Comment by ziyaxuanyi** [comment]
在tools/infer/utility.py的第80行
parser.add_argument("--drop_score", type=float, default=0.5)

**Comment by zhangyingying520** [comment]
> 在tools/infer/utility.py的第80行
> parser.add_argument("--drop_score", type=float, default=0.5)

发现自己推理完的检测模型和识别模型都不行
!python3 tools/infer/predict_det.py --image_dir="./doc/test/111.jpg" --det_model_dir="inference/db_mv3_infer/"
!python3 tools/infer/predict_rec.py --image_dir="doc/test/1_crop_1.jpg" --rec_model_dir="inference/rec_infer/"

**Comment by ziyaxuanyi** [comment]
检测结果里面如果没有检测到文本框的话，就说明检测模型无法应对这种情形的检测，需要加入这种情形的样本训练微调检测模型

**Comment by zhangyingying520** [comment]
> 检测结果里面如果没有检测到文本框的话，就说明检测模型无法应对这种情形的检测，需要加入这种情形的样本训练微调检测模型

但是没转换为推理模型之前是可以检测和识别得，推理后检测不出也识别不出

**Comment by zhangyingying520** [comment]
> 检测结果里面如果没有检测到文本框的话，就说明检测模型无法应对这种情形的检测，需要加入这种情形的样本训练微调检测模型

解决了，谢谢。最后的原因是转推理模型的时候出现了问题
