### ISSUE TITLE
官方提供的训练模型和预训练模型，有区别吗？都可以用来finetune吗？

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4188]
ch_ppocr_mobile_v2.0_rec_train和ch_ppocr_mobile_v2.0_rec_pre，都可以用来finetune吗？

**Comment by littletomatodonkey** [comment]
是的，都可以，如果接近垂类场景，建议ch_ppocr_mobile_v2.0_rec_train

**Comment by latawangzi** [comment]
什么是垂类场景？
