### ISSUE TITLE
win10 C++与python识别结果不一致

### ISSUE THREAD

**Issue by qq61786631** [PaddlePaddle/PaddleOCR#419]
如题，python文字定位和检测都比较正常。
![2](https://user-images.githubusercontent.com/34880475/88448085-6dac0000-ce6c-11ea-8d8a-42a3146d226e.png)

但是C++，使用ocr_system.exe识别时，出现文字定位不准确的情况，导致识别结果异常。

![360截图16720402076048](https://user-images.githubusercontent.com/34880475/88448071-553be580-ce6c-11ea-876f-21257237afc5.png)

两者都用的  超轻量级中文OCR模型 （ch_det_mv3_db）和 文字检测（ch_rec_mv3_crnn_enhance） 模型，参数均为默认参数。

但是用通用中文OCR模型两者都可以正确识别，请问C++实现和python实现为啥会出现这些分别~  还能抢救下不 \(^o^)/

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，可能是预测库和inference model的版本不一致导致的，稍等我check下

**Comment by littletomatodonkey** [comment]
你好，初步定位原因如下：官网提供的windows c++预测库版本为1.8.2，PaddleOCR提供的inference model为1.7.1版本，因此加载之后c++预测和py预测的输出diff比较大，有2个解决方法：
1. 在paddle1.8.2环境下导出检测与识别模型，使用该模型和1.8.2版本的c++预测库结合使用
2. 在windows按照预测库官网教程编译1.7.1版本的Paddle预测库，再使用PaddleOCR官网提供的inference model进行预测。
我尝试了方案1，结果diff很小，符合预期。
![image](https://user-images.githubusercontent.com/14270174/88454469-8afbc100-cea2-11ea-9e82-40d48640c07d.png)

**Comment by qq61786631** [comment]
thanks，经过测试：
第一种方案和python版本结果差别不大
第二种方案应该是不可行，测试了1.7.2的mkl和openblas ，都不行 ^_^

**Comment by littletomatodonkey** [comment]
> thanks，经过测试：
> 第一种方案和python版本结果差别不大
> 第二种方案应该是不可行，测试了1.7.2的mkl和openblas ，都不行 ^_^

好的，目前还是建议使用第一种方案吧~

**Comment by qq61786631** [comment]
ok ,谢谢
