### ISSUE TITLE
ppstructure识别不到表格结构（整张图片都是表格且像素较大）

### ISSUE THREAD

**Issue by Sweetwenty** [PaddlePaddle/PaddleOCR#4190]
最近使用表格识别时遇到两个问题：
1. 对于上千像素大小（4000*3000）的整张表格（上下两端均有横线），ppstructure识别不到表格结构，返回两张图片，res.txt内容为空；裁剪成4000*2000的图片，在上下两端添加横线后可以识别到表格结构，返回show.jpg（右端内容为空），但Excel表格内几乎为空。
2. 以上同样像素大小的图片，针对返回表格内容较差的问题，只使用tools.infer.predict_system进行识别，识别内容同样几乎为空（轻便模型、通用模型均已试验过，后者效果稍好），但使用ppstructure推出之前的版本识别效果非常好。
还有一些小的疑问：
show.jpg应该是识别到表格结构返回的图片，对于上面提到的整张图片都是表格的情况而言，show右端应该是空白的，识别结果直接输出到Excel中。但是在试验合适像素的表格图片（500*300且含有部分汉字）时也碰到过同时输出[坐标].jpg和show.jpg，并且show右端显示了识别结果，更重要的是在Excel表格中的结果和show中展示的结果不同（表格中结果较差）：这种情况是否出现了两次识别，当成text识别一次，table又识别一次并写入表格。
目前具体想通过更改表格内的内容识别这一板块，但是新版更改的地方比较多，希望得到一些简单的修改方向指导以及上述问题的回复。
正在学习过程中，问出的问题还停留在初级阶段，希望不吝解答。

**Comment by BeyondYourself** [comment]
中文表格目前还不支持

**Comment by sucre111** [comment]
> 中文表格目前还不支持

这是官方回复吗

**Comment by sucre111** [comment]
> 

老哥解决了吗，有最新进展吗

**Comment by Sweetwenty** [comment]
> > 
> 
> 老哥解决了吗，有最新进展吗

搁置了一段时间，还没有进展。

**Comment by wurentidai** [comment]
请问这个问题解决了吗？最近遇到和你相同的问题？盼回复

**Comment by Sweetwenty** [comment]
> 请问这个问题解决了吗？最近遇到和你相同的问题？盼回复

我的图片里面是中文，识别出来结构是空白，找张英文的确实可以输出结构；像素太大这个问题目前还没有解决。
