### ISSUE TITLE
ppstructure识别表格类型为figure

### ISSUE THREAD

**Issue by gannilaoer** [PaddlePaddle/PaddleOCR#4192]
想试一下识别表格为execl的功能，但是所用的表格都被判断为‘figure’。

看了下代码，在ppstructure\predict_system.py下有一个类型判断，‘figure‘和’table’两种类型走的是不同的流程。

想问一下有无办法绕过这个类型判断，直接使用‘table’的流程输出excel？

**Comment by MissPenguin** [comment]
只需要识别表格的话，直接按这里的步骤来就好：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/ppstructure/table
