### ISSUE TITLE
小语种，比如维吾尔等的检测模型，在哪里下载？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#4193]
只找到了识别模型，怎么检测？另外，小语种如何翻译为中文，有没有相关的东西？

**Comment by MissPenguin** [comment]
检测模型复用中英文的检测模型即可，该训练时加入了多语言数据，可以检测小语种；如果觉得效果无法满足需求，则需要用目标语种数据进行finetune。

小语种翻译这块目前不在PaddleOCR关注范围内。。
