### ISSUE TITLE
请问paddle自带模型训练时数据是否涵盖了目前商业化的一些场景？

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/PaddleOCR#4201]
我看到Readme文件展示的文字识别效果，对车辆名牌上的参数，以及医疗清单上的术语识别都很准确；然而readme中有关训练数据只提到一些公开的竞赛数据，这些竞赛数据多为自然场景，因此我想问的是百度自带的模型是否用到一些商业业务中的数据，比如车辆名牌，医疗清单，发票等等？依我看来，如果用那些公开的竞赛数据训练模型，除非其中包含大量医疗数据，否则对医疗清单上的术语识别率应该很有限吧？

**Comment by MissPenguin** [comment]
已发布的PP-OCRv2模型的训练数据全部来自于开源数据集和合成数据
