### ISSUE TITLE
关于论文PP-OCRv2: Bag of Tricks for Ultra Lightweight OCR System的问题

### ISSUE THREAD

**Issue by Syencil** [PaddlePaddle/PaddleOCR#4206]
1. 关于LCN网络的输出额外增加了一层FC，应该增加了计算量才对，为什么是没有任何额外的推理时间增加，intel cpu优化了吗？
2. Model Size是说的参数量还是说Paddel训练完用于部署的权重大小？
3. 介绍CML到时候mobilnetv3拼写错误

**Comment by BeyondYourself** [comment]
我也发现mobilnetV3的确有一处拼写错了

**Comment by lin-0015** [comment]
mobilnetv3模型训练效果相对于2.1变了

**Comment by LDOUBLEV** [comment]
> 关于LCN网络的输出额外增加了一层FC，应该增加了计算量才对，为什么是没有任何额外的推理时间增加，intel cpu优化了吗？

理论上计算量会增加，但是增加一层FC，就是多加了一个矩阵乘法，对计算速度的影响微乎其微，增加的速度完全可以忽略，而且2.1.2 的paddle版本在CPU上开启mkdnn，预测速度变快了不少，整体预测速度相比较旧版本的ppocr模型还是变快了


> Model Size是说的参数量还是说Paddel训练完用于部署的权重大小？

用于部署的权重大小，Model Size 是训练模型转成的inference model大小

> 介绍CML到时候mobilnetv3拼写错误

感谢反馈，笔误，请见谅
