### ISSUE TITLE
local variable 'label' reference before assignment

### ISSUE THREAD

**Issue by weilaizhe666** [PaddlePaddle/PaddleOCR#4207]
就是有没有小伙伴运行ppstructure的时候，替换版式分类模型, layout_path_model 的值改为替换的版式分类模型的路径之后，报这个错？
在predict_system.py文件的第65行：
layout_res = self.table_layout.detect(img[...,::-1])
调用安装的layoutmodel.py的detect函数392行
layout = self.gather_output(results)
然后调用
layoutmodel.py 文件里面的353行：
Rectangle（x_1,y_1,x_2,y_2）,type=lable,score=score
这个换版式分类模型的时候有没有需要注意的？直接改layout_path_model 路径的值，有没有用?还需要做其他的么？

还有这个错误原因不知道为啥

**Comment by WenmuZhou** [comment]
麻烦贴一下详细的错误信息
