### ISSUE TITLE
论文中验证集具体的来源

### ISSUE THREAD

**Issue by maplehan2009** [PaddlePaddle/PaddleOCR#4208]
我想复现 [ppocr论文](https://arxiv.org/pdf/2009.09941.pdf) 中的定位与识别模型的实验. 文中在介绍验证集来源时, 只说定位在真实数据中选取了500张图片, 识别在真实数据中选择了18.7K图片. 

但是我不清楚这些图片是具体从哪个数据集的哪些图片采样出来的?

**Comment by LDOUBLEV** [comment]
这些数据是我们收集的，评估的数据暂时不打算开源

**Comment by maplehan2009** [comment]
那评估的数据的采样有范围吗? 比如是从哪几个数据集采样得到的?
