### ISSUE TITLE
paddleocr移动端DEMO问题

### ISSUE THREAD

**Issue by linjson** [PaddlePaddle/PaddleOCR#4210]
有没paddlelite(android)是用java写的ocr,而不是用c++写的DEMO,你们官方提供是全是c++写的OCR-demo,希望有java版本的OCR-demo

**Comment by linjson** [comment]
有没ios版本的OCR-demo

**Comment by LDOUBLEV** [comment]
目前不支持java的实现，java调用C++也是可以的，新的IOS的demo目前没有开发计划，旧版本的倒是有一个,https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/ios_demo
