### ISSUE TITLE
Linux 虚拟服务器，不能获取到cpu信息，导致出现错误avx错误

### ISSUE THREAD

**Issue by 0zcz** [PaddlePaddle/PaddleOCR#4214]
服务器是通过云计算生成的服务器，cpu是虚拟的。在执行值会提示
Error: AVX is not support on your machine, but you have installed paddlepaddle with avx core, you should reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html'

**Comment by LDOUBLEV** [comment]
按照提示重新安装paddle吧
