### ISSUE TITLE
ocr参数里面的ch改成en就会崩溃

### ISSUE THREAD

**Issue by KangLifei** [PaddlePaddle/PaddleOCR#4217]
ocr参数里面的ch改成en,decode会报错

**Comment by KangLifei** [comment]
![5a40ac6bbf92a41634b4affc8ea535c](https://user-images.githubusercontent.com/44434204/135194362-c3f767c6-136f-4ed0-92fe-138142bfb087.jpg)

**Comment by BeyondYourself** [comment]
越界了
