### ISSUE TITLE
PPOCRLabel  建议 pyqt5 替换为 pyside6 

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#4221]
pyqt5 | GPL-3.0
如果项目用这个打包 做项目出售
需要购买商业版权或全部开源
不太友好

PyQt5有两种授权协议：
GPL开源协议或商用闭源协议。
前者意味着直接使用PyQt5的程序也需要基于GPL协议开源，而后者需要支付购买费用，才能闭源使用。

pyside6 是 LGPL协议
可以在发布程序时合法合理地闭源

建议pyqt5 替换为 pyside6
反正都是同一家QT公司的产品

**Comment by Evezerest** [comment]
感谢你提供的信息，我们稍后会进一步考虑。PPOCRLabel为开源共建项目，欢迎PR修改相关代码。
