### ISSUE TITLE
有关表格结构预训练模型的问题

### ISSUE THREAD

**Issue by FangLi1** [PaddlePaddle/PaddleOCR#4226]
您好，请问官网提供的en_ppocr_mobile_v2.0_table_structure的预训练模型，为何不能使用？
出现了assert error：
File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 125, in set_valueself.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ conv3_expand_weights_moment1_0 ] need tensor with shape (72, 16, 1, 1) but load set tensor with shape (64, 16, 1, 1)

使用的是表格的默认的配置，求大佬解答！！

**Comment by hungnv21292** [comment]
I faced the same issue. Can someone help me?

**Comment by FangLi1** [comment]
I trained the model by myself as pretrained model, but it need some time...

**Comment by hungnv21292** [comment]
> I trained the model by myself as pretrained model, but it need some time...

You training PubTabNet dataset from scratch and use it as pretrained model for finetune task, that right.
I think it is good idea.

Thanks for your sharing.

**Comment by CV-deeplearning** [comment]
> I trained the model by myself as pretrained model, but it need some time...

你好，你的预训练模型训练好了吗？我也在从头开始训练，可以加微信私聊吗？微信：guopei-cg

**Comment by hungnv21292** [comment]
> I trained the model by myself as pretrained model, but it need some time...

Could you share with us your pretrained model?
Thanks you.
