### ISSUE TITLE
不同光照、不同倾斜度等因素都会对识别有影响，导致识别出错

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4228]
建议：有没有可能从模型角度进行优化？毕竟实际业务场景多样，Finetune的数据，不可能考虑全面
从模型、网络结构方面有没有优化方向？

**Comment by Gmgge** [comment]
目前还没有人能设计出这种模型。。。
不同光照、角度、尺度算是图像经典难题了，pp的团队怎么会不知道。。。
如果这些难题都能使用网络结构解决（大多数方法是缓解这些问题的影响），而不是靠数据集的多样性，那得拿多少图灵奖。。。

**Comment by ioracion** [comment]
同意楼上，想法不太现实。
可以考虑加些通用的处理，像是图像灰度处理、锐化等，在喂给模型前让数据的特性尽可能一样（当然最好是能从源头处理，做好规范
