### ISSUE TITLE
PPOCRv2 paper results!

### ISSUE THREAD

**Issue by RamanHacks** [PaddlePaddle/PaddleOCR#4239]
Which model was used to get the v2 paper result? Was it the new slim model or the non-slim one?

**Comment by LDOUBLEV** [comment]
> Which model was used to get the v2 paper result? 

Here https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th

> Was it the new slim model or the non-slim one?

there are slim and non-slim mode. 
Text detection slim and non-slim model https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_en/models_list_en.md#1-text-detection-model

Text recognition model 
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_en/models_list_en.md#21-chinese-recognition-model
