### ISSUE TITLE
请问，用官方的docker镜像运行起来后如何通过http api 调用？

### ISSUE THREAD

**Issue by neozhu** [PaddlePaddle/PaddleOCR#4242]
哪里有这方面的文档说明，我找了半天没找到。

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/135788315-c4fd4ef5-e849-44e4-84d3-2da2e70123f5.png)
/bin/sh: 1: source: not found
用的docker-hub上最新的镜像，运行失败

**Comment by neozhu** [comment]
> docker run -p 8868:8868 --name paddle -it -v pwd:/paddle registry.baidubce.com/paddlepaddle/paddle /bin/bash
现在 docker 运行起来了
![image](https://user-images.githubusercontent.com/1549611/135789271-090afe9f-19b7-44bd-bee3-5a950e27fd7e.png)
但是打开浏览器 8868 没有服务

**Comment by neozhu** [comment]
请问还需要运行哪些命令才可以运行rest full api

**Comment by neozhu** [comment]
能否官方做一个一键运行的docker 镜像。

**Comment by neozhu** [comment]
经过不断的尝试，还差一点

**Comment by neozhu** [comment]
请问PaddleHub Serving的服务部署 是不是只能本地访问，就算docker上映射了端口也不行，谁能解答一下

**Comment by neozhu** [comment]
总算搞定了。

**Comment by YuhooZhu** [comment]
> 总算搞定了。

老哥, 我这边用api调用后返回的识别结果与他的py测试工具效果差很多, 同一个识别率低了很多. 你那边有类似情况吗?

**Comment by vincentbin** [comment]
请问跑起来的dockerfile能提供下吗？
