### ISSUE TITLE
How to improve recognition result?

### ISSUE THREAD

**Issue by shraddha291996** [PaddlePaddle/PaddleOCR#4247]
Currently, I am training  model e2e_r50_vd_pg with my handwritten dataset, the model is detecting well but not recognizing text very well
![Test1_img](https://user-images.githubusercontent.com/59836701/135843198-664a018b-3f05-444a-9c2c-74eed1a80877.JPG)
 
I have attached the recognized result. Its English language text and recognizing only "make" word correct 
Can you please suggest how I can improve the results?
Thanks

**Comment by dhea1323** [comment]
hello @tink2123,
Can you guide me to finetune it?
