### ISSUE TITLE
盖章的地方检测文本框效果不好，想要训练一下有盖章的这种的数据集，但没找到

### ISSUE THREAD

**Issue by xiaohua1027** [PaddlePaddle/PaddleOCR#4249]

**Comment by tink2123** [comment]
传统db算法对印章文本检测效果有限，可以试一下端到端的算法，例如[PGNet](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/pgnet.md)

**Comment by wangfangming0611** [comment]
> _No description provided._

请问您现在找到数据集了吗

**Comment by mingming0611** [comment]
> _No description provided._

请问您现在找到数据集了吗
