### ISSUE TITLE
移动端可以在无网络的情况下使用吗？

### ISSUE THREAD

**Issue by softboy99** [PaddlePaddle/PaddleOCR#425]
移动端可以在无网络的情况下使用吗？

**Comment by BeyondYourself** [comment]
可以的，不需要网络

**Comment by softboy99** [comment]
看到应该也有人反映了，识别结果的输出是乱的，如下例营业执照的照片：https://www.flikflak.com/var/storage/images/media/images/business_licence_chinese_0820192/1271528-1-chi-CN/business_licence_chinese_082019.jpg，
结果不好写代码去解析，识别再准确又有何用，识别结果如下：
1: 统一社会信用代码
2: 营业执照
3: 美
4: 913100007989084879
5: 证照编号：01000002201906140006
6: 注册资本美元50.0000万
7: 上海瑞湾钟表商业有限公司
8: 成立日期2007年04月2日
9: 有限责任会司（台港澳法大独资）
10: 业期限2007年04月2日至2037年04月1日
11: 天
12: 代表
13: 潘治欣
14: 海市黄浦区南京东路23号一层122
15: 限镜及其零部件
16: 担轴医
17: 珠宝首饰（毛销、
18: 爱迎1
19: 微福
20: 品牌相关纪
21: 斤月
22: 76
23: 世口
24: 九公用品
25: 台导体器化
26: 服相服
27: 家用电器
28: A
29: 通信设备的进
30: 厨房用具
31: 售后维修服务和商务信
32: 世相关配套服务
33: 许可证管理的
34: 洗及配额
35: 双国营贸易管理商品
36: 关规定办理电请
37: 经相关部门批准后力可开展经营活
38: 批准的项日
39: 誉记机关
40: 年06
41: H
42: 2019

**Comment by softboy99** [comment]
不知道云端识别的那种，是怎么处理识别结果的，除了需要网络和上传照片，对带宽有要求外，还是挺准确的
