### ISSUE TITLE
请问你们对票据识别应用有什么好的方案

### ISSUE THREAD

**Issue by neozhu** [PaddlePaddle/PaddleOCR#4253]
环境我已经部署成功了，http服务也可以正常使用了，就是因为购买主机性能太差有点慢，但这都不是问题。
我想问一下大家你们对实际的业务需求有什么好的想法吗，我可以借鉴一下。
比如：用户上传一堆要报销的发票图片其中有普通的餐饮发票，打车票，医院看病的电子票，动车票 ....
当然不同的发票要抓的内容也不一样，比如普通发票，抓金额和服务名称发票号码，打车票，金额和打车时间距离，等
这些数据识别的结果里都有，但要通过什么手段能快速的抓取呢。
第一步，在上传的一堆附件里先要进行分类，比如上传10张图片：里面有发票，打车票，动车票， 我要怎么先分类（这里我还不知道怎么做）
第二步，根据分类，一类一类的处理，发票 通过正则表达匹配关键找金额等内容，

你们有什么好的方案吗。

**Comment by Lie-huo** [comment]
> 环境我已经部署成功了，http服务也可以正常使用了，就是因为购买主机性能太差有点慢，但这都不是问题。 我想问一下大家你们对实际的业务需求有什么好的想法吗，我可以借鉴一下。 比如：用户上传一堆要报销的发票图片其中有普通的餐饮发票，打车票，医院看病的电子票，动车票 .... 当然不同的发票要抓的内容也不一样，比如普通发票，抓金额和服务名称发票号码，打车票，金额和打车时间距离，等 这些数据识别的结果里都有，但要通过什么手段能快速的抓取呢。 第一步，在上传的一堆附件里先要进行分类，比如上传10张图片：里面有发票，打车票，动车票， 我要怎么先分类（这里我还不知道怎么做） 第二步，根据分类，一类一类的处理，发票 通过正则表达匹配关键找金额等内容，
> 
> 你们有什么好的方案吗。

如果发票中存在混帖的情况，建议使用分割或检测的方式先进行票据切分，然后再对每种票据进行ocr识别

**Comment by ioracion** [comment]
> > 你好，我咨询一下除了正则表达匹配还有什么好的方法做键值匹配吗
> 
> 你可以看一下商汤的mmocr，里面有关键信息提取的相关方法
 感谢分享，这技术感觉不错耶

@littletomatodonkey （祈求）开发大佬们能不能开发个飞桨版的，就我自己的使用场景来说，这技术会很有用。或者能不能先发起个问卷调研看看大家有没有这个需求再做决定（please

**Comment by neozhu** [comment]
就百度而言能开源这些就很不错，因为还有云端的识别服务(识别发票，发车票等)都是收费,所以正对特定应用的，肯定不会开源出来的。

**Comment by LDOUBLEV** [comment]
> 第二步，根据分类，一类一类的处理，发票 通过正则表达匹配关键找金额等内容，

@neozhu 
目前 关键信息提取的模型 已经在开发中了， 尽量月底测试完上线吧，也可能下个月，这个是效果图
![25d56ef434a8eeaee9bc65a1de8a4f68](https://user-images.githubusercontent.com/26592129/136646461-dcc94473-d638-49ca-adc3-3c6ecd8725c7.png)

**Comment by cjt222** [comment]
@LDOUBLEV 请问下，这种关键信息提取之后，很多重复的key value，这种一般要怎么去做key value的匹配呢？
