### ISSUE TITLE
"Please do not include whitespace in the path."  Why?

### ISSUE THREAD

**Issue by smartalx** [PaddlePaddle/PaddleOCR#4254]
Whenever I run this, I get "Please do not include whitespace in the path."
The filepath for the script is C:\Users\ROG 480\Documents\primrose
I know that the filepath has spaces in it.  There's nothing I can do about that.  The SSD has a whitespace in the name.  I can't just change it.  And I can't move the script.  It has to remain here.

Can you fix PaddleOCR so it doesn't have this limitation?

**Comment by littletomatodonkey** [comment]
you can provide your whole run script for better analysis, actually this should not happen if your path is right or can be accessed using python.
