### ISSUE TITLE
Can't use ppocrv2 

### ISSUE THREAD

**Issue by rubensanchezrivero** [PaddlePaddle/PaddleOCR#4258]
Whenever i try to run the models even if a put the cls = False it returns:
"version PP-OCRv2 not support cls models, use  version PP-OCR instead"
don't know how to solve this issue.
Thanks in advance

**Comment by LDOUBLEV** [comment]
It is just a warning and set cls as False does not affect the use of version PP-OCRv2.

**Comment by rubensanchezrivero** [comment]
> It is just a warning and set cls as False does not affect the use of version PP-OCRv2.

OK, thanks, I misunderstood, I thought, that means that the version PP-OCR will be the one used
