### ISSUE TITLE
如何使用opencv读取图片然后识别而非使用命令行指定图片识别

### ISSUE THREAD

**Issue by infinite013** [PaddlePaddle/PaddleOCR#426]

**Comment by littletomatodonkey** [comment]
你好，想问下你是想实时读取图片然后处理吗还是？以python预测为例，可以在这里进行修改，每次opencv读取图片，拿到numpy数据之后，再进行模型预测

https://github.com/PaddlePaddle/PaddleOCR/blob/c1ba964326cfbc6404d43b8d43fed61ca5f00c1e/tools/infer/predict_system.py#L122

**Comment by infinite013** [comment]
是的，我是想先对图片进行预处理然后再送入ocr中进行识别

**Comment by littletomatodonkey** [comment]
嗯嗯 那按照上面的操作是可行的，不过建议预处理过程尽量和PaddleOCR保持一致，否则精度可能会稍微差一些
