### ISSUE TITLE
请问如何添加多语言模块

### ISSUE THREAD

**Issue by neozhu** [PaddlePaddle/PaddleOCR#4266]
我按文档配置成功了，但只能识别中文和英文，无法识别其它语言，我还需要运行什么命令，或修改配置,有文档吗，

**Comment by LDOUBLEV** [comment]
> 从代码看，只要传入的语言代码，会自动下载需要下语言模型对吗？

是的

可以加参数lang 指定语言，识别算法还是CRNN

**Comment by neozhu** [comment]
> > 从代码看，只要传入的语言代码，会自动下载需要下语言模型对吗？
> 
> 是的
> 
> 可以加参数lang 指定语言，识别算法还是CRNN
不同改代码hub serving predict/ocr_system 就支持传参吗
