### ISSUE TITLE
Inference trained SRN model in ONNX format from onnxruntime

### ISSUE THREAD

**Issue by susanin1970** [PaddlePaddle/PaddleOCR#4267]
Hi!  

I trained SRN model for text recognition in my own dataset and translated to the inference format    
I use `predict_rec.py` script in PaddleOCR repository for getting predictions   
```
python .\tools\infer\predict_rec.py --rec_model_dir=D:\Repositories\PaddleOCR\output\rec\srn\inference_model --rec_algorithm=SRN --rec_image_shape="1,64,256" --rec_char_type=en --image_dir=C:\Users\Reutov\Desktop\test_iso_numbers --use_gpu=True
```  
And I got predictions successfully
I also made the model inference directly from Python code:
```python
    rec_algorithm = 'SRN'
    ocr = PaddleOCR(
        rec_model_dir=r"D:\Repositories\PaddleOCR\output\rec\srn\inference_model",
        rec_char_type="en",
        rec_image_shape="1,64,256",
        use_gpu=True,
        det=False,
        cls=False,
        rec_algorithm=rec_algorithm
    )
```
And I got predictions successfully

Then I tried to convert SRN inference model to the ONNX. I used Paddle2ONNX repo for converting by following command:   

```
paddle2onnx --model_dir D:\Repositories\PaddleOCR\output\rec\srn\inference_model  --model_filename D:\Repositories\PaddleOCR\output\rec\srn\inference_model\inference.pdmodel --params_filename D:\Repositories\PaddleOCR\output\rec\srn\inference_model\inference.pdiparams --save_file C:\Users\Reutov\Desktop\SRN_iso_containers.onnx --opset_version 11 --enable_onnx_checker True  
```  

Then when I try to make inference ONNX model via onnxruntime, I get following error:  

```
Traceback (most recent call last):
  File ".\paddle_ocr_onnx_test.py", line 33, in <module>
    outputs = session.run(None, {input_name: number_image})
  File "C:\Users\Reutov\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 184, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 5 inputs. Input Feed contains 1  
```  

I checked ONNX graph of SRN model by using Netron:  
![image](https://user-images.githubusercontent.com/57865736/136567191-d6cfbdfb-eba9-43f9-94df-5bf1a4b54ce5.png)  

It can be seen that the model has 5 inputs, one of which is responsible for the input image tensor (x), and the purpose of all the others is still unknown to me  

Inference model (inference.pdimodel) has also 5 inputs:  
![image](https://user-images.githubusercontent.com/57865736/136568587-99e41a50-bd91-4db6-be5f-489db31f326e.png)

What should I do to execute the correct SRN model inference via onnxruntime?  
ONNX model link: https://drive.google.com/file/d/10dlXJwmmr4dmG8OStbZmRO6Yvc5O8dwb/view?usp=sharing  
Inference model link: https://drive.google.com/file/d/1nYDrG9zDO6Sjo7oYvN57mmmwy3jNzGL7/view?usp=sharing

Thanks in advance for answer)

**Comment by susanin1970** [comment]
Thanks for answer, I will try to use this function for generate required input for SRN model in ONNX format)

**Comment by susanin1970** [comment]
I generated required input for SRN model in ONNX format with use this functions and I got predictions  
Thank you very much for your help!)

**Comment by tsufbechor** [comment]
> Hi!
> 
> I trained SRN model for text recognition in my own dataset and translated to the inference format I use `predict_rec.py` script in PaddleOCR repository for getting predictions
> 
> ```
> python .\tools\infer\predict_rec.py --rec_model_dir=D:\Repositories\PaddleOCR\output\rec\srn\inference_model --rec_algorithm=SRN --rec_image_shape="1,64,256" --rec_char_type=en --image_dir=C:\Users\Reutov\Desktop\test_iso_numbers --use_gpu=True
> ```
> 
> And I got predictions successfully I also made the model inference directly from Python code:
> 
> ```python
>     rec_algorithm = 'SRN'
>     ocr = PaddleOCR(
>         rec_model_dir=r"D:\Repositories\PaddleOCR\output\rec\srn\inference_model",
>         rec_char_type="en",
>         rec_image_shape="1,64,256",
>         use_gpu=True,
>         det=False,
>         cls=False,
>         rec_algorithm=rec_algorithm
>     )
> ```
> 
> And I got predictions successfully
> 
> Then I tried to convert SRN inference model to the ONNX. I used Paddle2ONNX repo for converting by following command:
> 
> ```
> paddle2onnx --model_dir D:\Repositories\PaddleOCR\output\rec\srn\inference_model  --model_filename D:\Repositories\PaddleOCR\output\rec\srn\inference_model\inference.pdmodel --params_filename D:\Repositories\PaddleOCR\output\rec\srn\inference_model\inference.pdiparams --save_file C:\Users\Reutov\Desktop\SRN_iso_containers.onnx --opset_version 11 --enable_onnx_checker True  
> ```
> 
> Then when I try to make inference ONNX model via onnxruntime, I get following error:
> 
> ```
> Traceback (most recent call last):
>   File ".\paddle_ocr_onnx_test.py", line 33, in <module>
>     outputs = session.run(None, {input_name: number_image})
>   File "C:\Users\Reutov\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 184, in run
>     raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
> ValueError: Model requires 5 inputs. Input Feed contains 1  
> ```
> 
> I checked ONNX graph of SRN model by using Netron: ![image](https://user-images.githubusercontent.com/57865736/136567191-d6cfbdfb-eba9-43f9-94df-5bf1a4b54ce5.png)
> 
> It can be seen that the model has 5 inputs, one of which is responsible for the input image tensor (x), and the purpose of all the others is still unknown to me
> 
> Inference model (inference.pdimodel) has also 5 inputs: ![image](https://user-images.githubusercontent.com/57865736/136568587-99e41a50-bd91-4db6-be5f-489db31f326e.png)
> 
> What should I do to execute the correct SRN model inference via onnxruntime? ONNX model link: https://drive.google.com/file/d/10dlXJwmmr4dmG8OStbZmRO6Yvc5O8dwb/view?usp=sharing Inference model link: https://drive.google.com/file/d/1nYDrG9zDO6Sjo7oYvN57mmmwy3jNzGL7/view?usp=sharing
> 
> Thanks in advance for answer)

Hi susan, 
![image](https://github.com/user-attachments/assets/6189f0c4-1831-4cee-936f-100df4280ad1)

Have you received this error? I used config that is similar to one you used in a previous post
