### ISSUE TITLE
编译生成exe后运行出现应用程序无法正常运行（0xc0000142）

### ISSUE THREAD

**Issue by zhongweidi993** [PaddlePaddle/PaddleOCR#4269]
编译生成exe后运行出现应用程序无法正常运行（0xc0000142）
![image](https://user-images.githubusercontent.com/84389111/136641369-5e4c1281-7a25-41c6-ae87-ec6c22c0ceb6.png)

**Comment by tink2123** [comment]
请问您是怎么编译的呢？

**Comment by zhongweidi993** [comment]
按照官方文档来，vs19编译cmake文件，配置参数，编译库paddle_inference的路径可能会传不过去，把编译库的绝对路径写入cmake文件就能编译了

**Comment by pollyyan** [comment]
是报这个错么～
![image](https://user-images.githubusercontent.com/38637686/136887124-7df5ad4e-090d-4fcb-a458-dbcc3e1a1ee0.png)

**Comment by zhongweidi993** [comment]
是的，万分感谢，已经解决了。
