### ISSUE TITLE
error:json解码出错

### ISSUE THREAD

**Issue by scc103766** [PaddlePaddle/PaddleOCR#4271]
root ERROR: When parsing line ch4_training_images/00001006.jpg    [{"transcription": "MOA2020-W避雷器监测智能传感器", "points": [[249, 488], [490, 501], [489, 522], [248, 509]], "difficult": false}, {"transcription": "NLINF", "points": [[331, 526], [424, 531], [422, 555], [330, 550]], "difficult": false}, {"transcription": "宁波理工监测科技股份有限公司", "points": [[278, 557], [453, 566], [452, 582], [277, 573]], "difficult": false}, {"transcription": "仅供图片识别使用，严禁其他用途", "points": [[91, 850], [657, 850], [657, 884], [91, 884]], "difficult": false}, {"transcription": "2号", "points": [[116, 892], [270, 895], [269, 945], [115, 942]], "difficult": false}, {"transcription": "52207", "points": [[282, 894], [490, 894], [490, 954], [282, 954]], "difficult": false}, {"transcription": "20", "points": [[317, 583], [402, 583], [402, 636], [317, 636]], "difficult": false}] ch4_training_images/img_424.jpg   [{"transcription": "RamenPlay", "points": [[406, 93], [563, 78], [566, 112], [410, 127]]}, {"transcription": "###", "points": [[573, 84], [627, 77], [630, 98], [575, 104]]}]
, error happened with msg: Extra data: line 1 column 783 (char 782)

**Comment by tink2123** [comment]
请详细描述下您的报错场景，使用的什么数据，在训练什么模型时出现的。
label 使用的是PaddleOCR提供的吗？
