### ISSUE TITLE
关于 docker 部署服务的问题

### ISSUE THREAD

**Issue by Micro-sheep** [PaddlePaddle/PaddleOCR#4274]
偶然一次试用百度的 OCR 在线平台做图片文字识别服务，识别效果非常棒！但因为近期有大量的图片文字识别要求，所以来这研究怎么搭建自己的 OCR 在线服务。`Docker` 无疑是一个很好的选择。但是当安装文档的说明，使用 `Docker` 来部署时，真的很无奈，相关贡献者并没有清楚指明部署时需要的依赖，仅仅是拉取一个镜像，里面的 python 版本甚至与该项目是不符合的（ Dockerfile 里面的镜像 python 版本为 3.5，但实际上这个项目得在 python 3.7 版本项目能良好运行）。并且，要成功运行，仅仅根据 `requirements.txt` 文件来安装 python 依赖是不够的，还得装 `gcc`、`libgl1`。并且其构建的镜像非常大，我试了一下，大小超过 10G，服务也没能正常运行。

使用 Docker 的目的是简化人为干预的部署流程，但该项目里面的 Dockerfile 显然没有达到这个目的，甚至比不用 `Docker` 来部署还难做。

我已经自己写了一个保证可以运行，并且只要  `docker-compose up`  即可成功运行的脚本，如果可以，我愿意提交到该项目里面。

**Comment by tink2123** [comment]
由于Paddle官方提供的Docker要保证对所有套件和框架功能的兼容性，有些庞大了。如果你原因，非常欢迎贡献一个PR，帮助更多的用户简化部署流程。

**Comment by Micro-sheep** [comment]
> > > 由于Paddle官方提供的Docker要保证对所有套件和框架功能的兼容性，有些庞大了。如果你愿意，非常欢迎贡献一个PR，帮助更多的用户简化部署流程。
> > 
> > 
> > 好 过几天我把自己写的提交到此项目。
> 
> 你好，提交了吗，我想学习一下

现在提交了，地址在这：[PR](https://github.com/PaddlePaddle/PaddleOCR/pull/4512)
如果看着麻烦，可以到我自己 fork 的仓库里面看  [Paddleocr](https://github.com/Micro-sheep/PaddleOCR)

**Comment by pennpeng** [comment]
@Micro-sheep 请问下您这个dockerfile gpu版本能使用吗？

**Comment by Micro-sheep** [comment]
> @Micro-sheep 请问下您这个dockerfile gpu版本能使用吗？

只写了 cpu 版本，不过你要使用 gpu 的话应该很简单，把下面这行代码
```python
ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
```
改为 
```python
ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True)
```
应该就可以了。
具体修改位置在这：[开启 gpu](https://github.com/Micro-sheep/PaddleOCR/blob/release/2.3/deploy/docker_compose/server.py#L11)
需要注意的是，在修改之后，你应该用支持 gpu 的 docker 来启动。

**Comment by pennpeng** [comment]
@Micro-sheep 小白请教下，现在部署成功了，请求貌似也是成功了，但是看不到识别的结果啊？
````
curl "http://localhost:5000/api/ocr_dec" -X POST -d "img_url=https://ai.bdstatic.com/file/5419067D0B374C12A8CFB5C74684CC06"
{"msg":"","results":[{"confidence":0.92492145,"text":"\u53bb\u5e74\u4eca\u65e5\u6b64\u95e8\u4e2d","text_region":[[[941.0,189.0],[1019.0,188.0],[1022.0,791.0],[944.0,791.0]]]},{"confidence":0.9868188,"text":"\u4eba\u4eba","text_region":[[[678.0,195.0],[905.0,198.0],[904.0,286.0],[677.0,283.0]]]},{"confidence":0.8828576,"text":"\u9898\u90fd\u57ce\u5357\u5e84","text_region":[[[1053.0,187.0],[1186.0,186.0],[1190.0,871.0],[1056.0,872.0]]]},{"confidence":0.69590455,"text":"\u9762\u6843\u82b1\u76f8\u6620\u7ea2","text_region":[[[818.0,237.0],[902.0,238.0],[898.0,782.0],[815.0,782.0]]]},{"confidence":0.8335726,"text":"\u9762\u4e0d\u77e5\u4f55\u5904\u53bb","text_region":[[[691.0,266.0],[787.0,266.0],[783.0,790.0],[687.0,790.0]]]},{"confidence":0.5947596,"text":"\u96c0\u62a4","text_region":[[[462.0,671.0],[515.0,671.0],[515.0,782.0],[462.0,782.0]]]}],"success":true,"time_cost":0.0021293163299560547}

````

**Comment by Micro-sheep** [comment]
text 对应的即识别结果，但你的终端里面显示的是 unicode，需要再稍微转换一下。

**Comment by pennpeng** [comment]
您那边通过这种模式是正常的吗？需要安装什么软件是吗还是怎么转换呢

**Comment by Micro-sheep** [comment]
> 您那边通过这种模式是正常的吗？需要安装什么软件是吗还是怎么转换呢

不需要安装什么软件，你就把它当作正常文字来操作，大多数编程语言都可以识别的。你可以看看我给的 python 解析例子。

**Comment by pennpeng** [comment]
嗯，paddleocr有那种web界面的吗？就是他们试用的那个界面，在线的上传一张图片就自动识别出来了，找了半天没找到

**Comment by Micro-sheep** [comment]
> > 您那边通过这种模式是正常的吗？需要安装什么软件是吗还是怎么转换呢
> 
> 不需要安装什么软件，你就把它当作正常文字来操作，大多数编程语言都可以识别的。你可以看看我给的 python 解析例子。

如果你希望在终端以正常形式显示中文的话，在 把 `server.py` 的 这里
```python
app = Flask(__name__)
img_dir = Path('imgs')
img_dir.mkdir(exist_ok=True)
ocr_cache_dict = dict()
```
改为
```python
app = Flask(__name__)
app.config['JSON_AS_ASCII'] = False
img_dir = Path('imgs')
img_dir.mkdir(exist_ok=True)
ocr_cache_dict = dict()
```
即添加下面这一行代码（要保证在 `app.run` 之前）
```python
app.config['JSON_AS_ASCII'] = False
```

**Comment by Micro-sheep** [comment]
> 嗯，paddleocr有那种web界面的吗？就是他们试用的那个界面，在线的上传一张图片就自动识别出来了，找了半天没找到

那种 web 界面是需要自己写的，我提供的是后台接口，需要界面的话你可以自己写前端界面，然后对接相应的后台接口即可。

**Comment by pennpeng** [comment]
> > > 您那边通过这种模式是正常的吗？需要安装什么软件是吗还是怎么转换呢
> > 
> > 
> > 不需要安装什么软件，你就把它当作正常文字来操作，大多数编程语言都可以识别的。你可以看看我给的 python 解析例子。
> 
> 如果你希望在终端以正常形式显示中文的话，把 `server.py` 的这里
> 
> ```python
> app = Flask(__name__)
> img_dir = Path('imgs')
> img_dir.mkdir(exist_ok=True)
> ocr_cache_dict = dict()
> ```
> 
> 改为
> 
> ```python
> app = Flask(__name__)
> app.config['JSON_AS_ASCII'] = False
> img_dir = Path('imgs')
> img_dir.mkdir(exist_ok=True)
> ocr_cache_dict = dict()
> ```
> 
> 即添加下面这一行代码（要保证在 `app.run` 之前）
> 
> ```python
> app.config['JSON_AS_ASCII'] = False
> ```

非常感谢啊，谢谢

**Comment by yiliang-yl** [comment]
我用你这个第一次识别会比官方慢一点，第二次虽然做了缓存，但我不懂Python，你这个缓存要是请求多起来会不会用问题。

**Comment by yiliang-yl** [comment]
还要你这个和官方那个docker部署有什么区别吗？能直接请求server.py这个吗，还是需要自己写入口，能在生产用吗？我测试的结果和官方版本识别有一点点差别。

**Comment by Micro-sheep** [comment]
> 还要你这个和官方那个docker部署有什么区别吗？能直接请求server.py这个吗，还是需要自己写入口，能在生产用吗？我测试的结果和官方版本识别有一点点差别。

server.py 里面提供了一个 api 接口，基于 flask，可以生产用，具体使用说明详见我写的文档。我里面写的 paddle 版本是固定的，所以可能跟你用的官方版本不一样，你可以改版本再使用。

**Comment by yiliang-yl** [comment]
> 
dict会自动过期吗？不会的话，一直保存的话，会不会时间长内存溢出啊

**Comment by Micro-sheep** [comment]
> > > 我用你这个第一次识别会比官方慢一点，第二次虽然做了缓存，但我不懂Python，你这个缓存要是请求多起来会不会用问题。
> 
> > 
> 
> > 第一次慢是因为要下载图片到本地再识别，识别完成之后会以文件名的md5值为key，以识别结果为value存放到dict里面。之后如果检测到相同的文件，则直接返回识别过的结果。
> 
> 
> 
> dict会自动过期吗？不会的话，一直保存的话，会不会时间长内存溢出啊

dict 不会过期，如果你想设置过期自动删除，可以加 redis 或者在 dict 里面额外加字段时间信息，满足一定条件再删除。如果你的服务请求频繁，在不定期删除 dict 的情况下，会内存不够。

**Comment by yiliang-yl** [comment]
![lQLPDhr787NYR_c8zQOesKY1gbnyvFeFAcoKd1XA0gA_926_60](https://user-images.githubusercontent.com/59381726/147079690-97e00a46-c22d-4b5e-a9a7-df8f7a89933b.png)
上面是用你的教程搭建的，下面是官方的为什么内存占用差这么多呀？而且我把缓存去掉了，但是运行了几天发现内存占用11g了...
![lQLPDhr78u_Xc45YzQNSsNncQdPrtvgYAcoJNoaAGAA_850_88](https://user-images.githubusercontent.com/59381726/147079902-2bfb1c9e-2ba6-4d27-9d65-ebd657d78d98.png)

**Comment by Micro-sheep** [comment]
> ![lQLPDhr787NYR_c8zQOesKY1gbnyvFeFAcoKd1XA0gA_926_60](https://user-images.githubusercontent.com/59381726/147079690-97e00a46-c22d-4b5e-a9a7-df8f7a89933b.png)
> 
> 上面是用你的教程搭建的，下面是官方的为什么内存占用差这么多呀？而且我把缓存去掉了，但是运行了几天发现内存占用11g了...
> 
> ![lQLPDhr78u_Xc45YzQNSsNncQdPrtvgYAcoJNoaAGAA_850_88](https://user-images.githubusercontent.com/59381726/147079902-2bfb1c9e-2ba6-4d27-9d65-ebd657d78d98.png)
> 
> 

你把修改后的代码贴出来我看看。

**Comment by yiliang-yl** [comment]
> > ![lQLPDhr787NYR_c8zQOesKY1gbnyvFeFAcoKd1XA0gA_926_60](https://user-images.githubusercontent.com/59381726/147079690-97e00a46-c22d-4b5e-a9a7-df8f7a89933b.png)
> > 上面是用你的教程搭建的，下面是官方的为什么内存占用差这么多呀？而且我把缓存去掉了，但是运行了几天发现内存占用11g了...
> > ![lQLPDhr78u_Xc45YzQNSsNncQdPrtvgYAcoJNoaAGAA_850_88](https://user-images.githubusercontent.com/59381726/147079902-2bfb1c9e-2ba6-4d27-9d65-ebd657d78d98.png)
> 
> 你把修改后的代码贴出来我看看。

from flask import request, Flask, request
from shutil import copy
import os
from typing import Dict, List, Union
from urllib.request import urlretrieve
from pathlib import Path
from paddleocr import PaddleOCR
from hashlib import md5
import time
import base64
ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
app = Flask(__name__)
img_dir = Path('imgs')
img_dir.mkdir(exist_ok=True)
#ocr_cache_dict = dict()


def get_dict_from_request() -> dict:
    """
    get json data from request as much as possible

    Returns
    -------
    dict
        request data in dict format    
    """
    json = {**request.args}
    if request.json:
        json = {**json, **request.json}
    if request.form:
        json = {**json, **request.form.to_dict()}
    return json


def download_image(img_url: str) -> str:
    """
    download image or copy image to local from url 

    Parameters
    ----------
    img_url : str
        url of image to be downloaded

    Returns
    -------
    str
        local file path of image

    Notes
    -----
    if download failed, empty string `''` will be returned
    """
    d = md5(str(img_url).encode()).hexdigest()
    file_name = f'{img_dir}/{d}.jpg'
    # NOTE: insecurity
    # # copy from local file system in the running container
    # if Path(img_url).exists():
    #     copy(img_url, file_name)

    if Path(file_name).exists():
        return file_name
    # download from internet
    try:
        urlretrieve(img_url, file_name)
        return file_name
    except:
        return ''


def base64_to_file(s: Union[str, bytes]) -> str:
    """
    decode base64 string or bytes and save to local file system

    Parameters
    ----------
    s : Union[str, bytes]
        base64 string or bytes

    Returns
    -------
    str
        local file path of base64 data
    """
    d = md5(str(s).encode()).hexdigest()
    file_name = f'{img_dir}/{d}.jpg'
    if Path(file_name).exists():
        return file_name
    if isinstance(s, str):
        b = base64.decodebytes(s.encode())
    elif isinstance(s, bytes):
        b = base64.decodebytes(s)
    else:
        return ''
    with open(file_name, 'wb') as f:
        f.write(b)
    return file_name


@app.route('/api/ocr_dec', methods=['POST'])
def ocr_text() -> None:
    """
    ocr web api that accept image url, image path and base64 data of image 
    """
    st = time.time()
    json = get_dict_from_request()
    #img_url: str = json.get('img_url')
    base64_data: str = json.get('img_base64')
    img_path = ''
    if base64_data:
        img_path = base64_to_file(base64_data)
    if not img_path:
        et = time.time()
        return {
            'success': False,
            'time_cost': et-st,
            'results': [],
            'msg': 'maybe img_url or img_base64 is wrong'
        }
    #results = ocr_cache_dict.get(img_path)
    results = None
    if not results:
        ocr_result_list = ocr.ocr(img_path)

        et = time.time()
        if ocr_result_list is None:
            ocr_result_list = []
            os.remove(img_path)
        else:
            # make sure float32 can be JSON serializable
            ocr_result_list: list = eval(str(ocr_result_list))
            results: List[Dict] = []
            for each in ocr_result_list:
                item = {
                    'confidence': each[-1][1],
                    'text': each[-1][0],
                    'text_region': each[:-1]
                }
                results.append(item)
            #ocr_cache_dict[img_path] = results

    et = time.time()
    return {
        'success': True,
        'time_cost': et-st,
        'results': results,
        'msg': ''
    }


if __name__ == '__main__':
    port = os.environ.get('FLASK_PORT', '')
    if port.isalnum() and int(port) > 0:
        port = int(port)
    else:
        port = 5000
    app.run(host='0.0.0.0', port=port)

**Comment by Micro-sheep** [comment]
> ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)

OK，我测试一下。

**Comment by yiliang-yl** [comment]
> > ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
> 
> OK，我测试一下。

你复现了吗？我看不是缓存的原因，我测3mb的图片，内存占用直接10g了，而且不会降下去

**Comment by Micro-sheep** [comment]
> > > ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
> 
> > 
> 
> > OK，我测试一下。
> 
> 
> 
> 你复现了吗？我看不是缓存的原因，我测3mb的图片，内存占用直接10g了，而且不会降下去

没复现出来，你可以试试限制一下这个容器的占用内存，然后看看会不会影响使用。

**Comment by yiliang-yl** [comment]
> > > > ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
> > 
> > 
> > > 
> > 
> > 
> > > OK，我测试一下。
> > 
> > 
> > 你复现了吗？我看不是缓存的原因，我测3mb的图片，内存占用直接10g了，而且不会降下去
> 
> 没复现出来，你可以试试限制一下这个容器的占用内存，然后看看会不会影响使用。

ocr_result_list = ocr.ocr(img_path)
还问一下，这个我看要先把图片保存下来然后传入地址，你知道有没有直接传入base64数据的接口啊，我不想把图片保存。

**Comment by Micro-sheep** [comment]
> > > > > ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > OK，我测试一下。
> 
> > > 
> 
> > > 
> 
> > > 你复现了吗？我看不是缓存的原因，我测3mb的图片，内存占用直接10g了，而且不会降下去
> 
> > 
> 
> > 没复现出来，你可以试试限制一下这个容器的占用内存，然后看看会不会影响使用。
> 
> 
> 
> ocr_result_list = ocr.ocr(img_path)
> 
> 还问一下，这个我看要先把图片保存下来然后传入地址，你知道有没有直接传入base64数据的接口啊，我不想把图片保存。

base64 的接口是有的，我在文档里面写了例子，你可以看看。在识别后不想保存图片，就在识别后删掉即可。

**Comment by jackviv** [comment]
2024年了，最新版的2.6 docker依然是环境不对...
咱就说百度的开发团队能上点心吗..
