### ISSUE TITLE
请问windows c++部署后怎么进行debug调试？

### ISSUE THREAD

**Issue by gl94** [PaddlePaddle/PaddleOCR#4277]
已经成功部署，想做一点二次开发，每次都只能生成release后看效果，效率太低且无法debug，请问有什么好方法吗？

**Comment by littletomatodonkey** [comment]
cpp确实debug比较费劲，可以多打一些log，尽量短时间内就能确认问题

**Comment by prettyocean85** [comment]
release工程修改3个设置以后就可以进行调试了。禁用优化，生成调试信息，调试信息格式改为Zi
