### ISSUE TITLE
车牌识别 模糊的图像汉字总是识别成皖

### ISSUE THREAD

**Issue by pingzi5233** [PaddlePaddle/PaddleOCR#4278]
很奇怪的一个问题，当我在用原版ch_ppocr_server_v2.0_rec_infer模型时，发现夜晚光照影响的车牌中的汉子80%以上出现错误的都是识别成皖这个字，之前在做卡证类的时候，也是有模糊的图像的，但不会大批量的识别成皖字，问下大家有出现这个情况的嘛？还有问下ch_ppocr_server_v2.0_rec_infer模型在训练的时候，是否有涵盖了中科院车牌CCPD2019数据集啊，因为我发现CCPD2019内部皖字车牌占比巨大，不知道是不是因为这个，就很奇怪，完全不像的汉字啊，附图如下，期待回答
![image](https://user-images.githubusercontent.com/48909056/136721678-096b164c-3d17-433d-9b83-7a8646aca072.png)

**Comment by zrl4836** [comment]
我预测时也经常误检这个字，原来是数据集的问题呀

**Comment by littletomatodonkey** [comment]
你好，是的，目前车牌识别的话，由于我们只有ccpd数据集用于车牌识别，所以如果是比较模糊的车牌图片的话，很容易将前面的字识别为皖的，这块建议结合自己的车牌数据集进行微调

**Comment by pingzi5233** [comment]
嗯呐了解，我说呢，这个皖字出现的太多了，而且是完全不像的汉字，差点用CCPD的来微调了，目前我们的车牌数据集太少了，也就一两百张，感觉不大行，在想是否采用合成数据来微调下；
另外args.det_limit_side_len这个参数的作用是什么呢，发现设为960的时候，其实识别还是会对的，但是想提升点速度设为640的话，就多数识别成皖字了

**Comment by littletomatodonkey** [comment]
表示检测的最长边，更大的话，结果会更准确一些，但是速度也相对慢一些

**Comment by latawangzi** [comment]
> 你好，是的，目前车牌识别的话，由于我们只有ccpd数据集用于车牌识别，所以如果是比较模糊的车牌图片的话，很容易将前面的字识别为皖的（ccpd数据集基本都是皖字开头的），这块建议结合自己的车牌数据集进行微调

请问如何实现微调？
