### ISSUE TITLE
你好，在paddlelite编译的时候出现的问题。

### ISSUE THREAD

**Issue by JianhaoZhan** [PaddlePaddle/PaddleOCR#428]
当我执行 ./lite/tools/build_android.sh  --arch=armv8  --with_cv=ON --with_extra=ON
出现如下错误，如何解决？
-- Found Paddle host system: ubuntu, version: 18.04.4
-- Found Paddle host system's CPU: 24 cores
CMake Error at cmake/cross_compiling/android.cmake:26 (message):
  Must set ANDROID_NDK or env NDK_ROOT
Call Stack (most recent call first):
  cmake/cross_compiling/preproject.cmake:47 (include)
  CMakeLists.txt:30 (include)

**Comment by LDOUBLEV** [comment]
readme中也提供可直接下的预测库。

看你的报错好像是编译环境的问题，
```
CMake Error at cmake/cross_compiling/android.cmake:26 (message):
Must set ANDROID_NDK or env NDK_ROOT
```
可以先按照readme中的 [1.1准备交叉编译环境](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md#11-%E5%87%86%E5%A4%87%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83) 准备环境。

如果编译环境没问题，可以提供下你的系统，cmake版本等环境，方便我们排查问题
