### ISSUE TITLE
PPOCRLabel标注程序中前后处理的参数

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#4281]
请问一下:
PPOCRLabel标注程序中前后处理的参数是从哪儿加载的? 如何修改?
跟的时候传的是二进制
![image](https://user-images.githubusercontent.com/65577659/136740172-2432914f-3629-4f40-aebe-42dfb7262d94.png)

**Comment by Evezerest** [comment]
![image](https://user-images.githubusercontent.com/50011306/136740877-cfa7090d-3da6-4179-aedd-05e550d05f0b.png)
你好，可以点击[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/PPOCRLabel/PPOCRLabel.py#L116)进行搜索
