### ISSUE TITLE
C++ windows环境下 cpu_math_library_num_threads_ 以及 use_mkldnn_对于计算速度的影响

### ISSUE THREAD

**Issue by qq61786631** [PaddlePaddle/PaddleOCR#429]
采用教程编译了windows下的 ocr_system.exe（mkl数学库），测试发现，同一张图片有如下情况
1. 同样的cpu_math_library_num_threads_=10情况下，use_mkldnn 选项打开耗时(1.85s)    关闭选项(1.6s)
2. use_mkldnn 关闭，cpu_math_library_num_threads_=0时，耗时1.4s   cpu_math_library_num_threads_=12时，耗时1.9s   

CPU Intel 8700(六核十二线程）

这两个情况，怎么都是反着来的呀，费解。单线程速度最快吗？

**Comment by littletomatodonkey** [comment]
你是测试了多次，取平均值吗？

**Comment by qq61786631** [comment]
100次 测试（model均加载完成后测试）
num_threads_=12  use_mkldnn=false    平均耗时 1525ms
num_threads_=0    use_mkldnn=false    平均耗时 1350ms

5次测试（内存占用飙涨，每次增加100多M，第10次控制台停止输出）
num_threads_=0    use_mkldnn=true平均耗时  1650ms

**Comment by littletomatodonkey** [comment]
好的，感谢你的反馈，我们在windows上测试下，复现下该问题

**Comment by xinsuinizhuan** [comment]
在windows下，怎么C++调用？

**Comment by littletomatodonkey** [comment]
> 在windows下，怎么C++调用？

你好，可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md

**Comment by luotao1** [comment]
@donproc 能帮忙看下这个问题么？
@OliverLPH 已经复现了，使用官方文档的模型，用2线程、4线程，都会慢下来

**Comment by OliverLPH** [comment]
> @donproc 能帮忙看下这个问题么？
> @OliverLPH 已经复现了，使用官方文档的模型，用2线程、4线程，都会慢下来

@donproc 
我验证了下linux环境下（cpu：E5-2650, avx2）set_cpu_math_library_num_threads 参数提速都很明显。
Windows环境（cpu：i7-8700k，6核）下存在该问题。

**Comment by donproc** [comment]
> > @donproc 能帮忙看下这个问题么？
> > @OliverLPH 已经复现了，使用官方文档的模型，用2线程、4线程，都会慢下来
> 
> @donproc
> 我验证了下linux环境下（cpu：E5-2650, avx2）set_cpu_math_library_num_threads 参数提速都很明显。
> Windows环境（cpu：i7-8700k，6核）下存在该问题。
看到cpu_helper.cc 里有这段注释，似乎windows不支持openblas多线程？

```
namespace paddle {
namespace platform {

void SetNumThreads(int num_threads) {
#ifdef PADDLE_USE_OPENBLAS
// windows has no support for openblas multi-thread
// please refer to: https://github.com/PaddlePaddle/Paddle/issues/7234
#ifdef _WIN32
  if (num_threads > 1) {
    num_threads = 1;
  }
#endif
  int real_num_threads = num_threads > 1 ? num_threads : 1;
  openblas_set_num_threads(real_num_threads);
#elif defined(PADDLE_WITH_MKLML)
  int real_num_threads = num_threads > 1 ? num_threads : 1;
  platform::dynload::MKL_Set_Num_Threads(real_num_threads);
  omp_set_num_threads(real_num_threads);
#else
  PADDLE_THROW(platform::errors::Unimplemented(
      "This library (except OPENBLAS, MKLML) is not supported yet, so the"
      "number of threads cannot be set."));
#endif
}

}  // namespace platform
}  // namespace paddle
```

另外，num_threads的设置不要超过核数。

**Comment by OliverLPH** [comment]
> > > @donproc 能帮忙看下这个问题么？
> > > @OliverLPH 已经复现了，使用官方文档的模型，用2线程、4线程，都会慢下来
> > 
> > 
> > @donproc
> > 我验证了下linux环境下（cpu：E5-2650, avx2）set_cpu_math_library_num_threads 参数提速都很明显。
> > Windows环境（cpu：i7-8700k，6核）下存在该问题。
> 
> 看到cpu_helper.cc 里有这段注释，似乎windows不支持openblas多线程？
> 
> ```
> namespace paddle {
> namespace platform {
> 
> void SetNumThreads(int num_threads) {
> #ifdef PADDLE_USE_OPENBLAS
> // windows has no support for openblas multi-thread
> // please refer to: https://github.com/PaddlePaddle/Paddle/issues/7234
> #ifdef _WIN32
>   if (num_threads > 1) {
>     num_threads = 1;
>   }
> #endif
>   int real_num_threads = num_threads > 1 ? num_threads : 1;
>   openblas_set_num_threads(real_num_threads);
> #elif defined(PADDLE_WITH_MKLML)
>   int real_num_threads = num_threads > 1 ? num_threads : 1;
>   platform::dynload::MKL_Set_Num_Threads(real_num_threads);
>   omp_set_num_threads(real_num_threads);
> #else
>   PADDLE_THROW(platform::errors::Unimplemented(
>       "This library (except OPENBLAS, MKLML) is not supported yet, so the"
>       "number of threads cannot be set."));
> #endif
> }
> 
> }  // namespace platform
> }  // namespace paddle
> ```
> 
> 另外，num_threads的设置不要超过核数。

应该不是openblas导致的，我使用的是 [cpu_avx_mkl](https://paddle-wheel.bj.bcebos.com/1.8.3/win-infer/mkl/cpu/fluid_inference_install_dir.zip) 这个lib复现的，感觉还是mkl存在问题。

**Comment by donproc** [comment]
> 采用教程编译了windows下的 ocr_system.exe（mkl数学库），测试发现，同一张图片有如下情况
> 
> 1. 同样的cpu_math_library_num_threads_=10情况下，use_mkldnn 选项打开耗时(1.85s)    关闭选项(1.6s)
> 2. use_mkldnn 关闭，cpu_math_library_num_threads_=0时，耗时1.4s   cpu_math_library_num_threads_=12时，耗时1.9s
> 
> CPU Intel 8700(六核十二线程）
> 
> 这两个情况，怎么都是反着来的呀，费解。单线程速度最快吗？


建议设置的线程数不超过核数。
@OliverLPH 做了些实验

关闭mkldnn的情况下
OMP_NUM_THREADS=2, 4, 6
总时间分别是 11.229s, 11.2499s, 11.2531s

set_cpu_math_library_num_threads=2, 4, 6
总时间分别是 11.1025s, 11.581s, 12.1681s


打开mkldnn的情况下
OMP_NUM_THREADS=2, 4, 6
总时间分别是 7.87955s, 6.03619s, 5.24563s

set_cpu_math_library_num_threads=2, 4, 6
总时间分别是 4.29156s, 4.44069s,  4.44163s


开mkldnn
OMP_NUM_THREADS=0
set_cpu_math_library_num_threads=1, 2, 4, 6
总时间分别是 4.44168s, 4.31165s, 4.78575s, 4.39619s

暂时可以打开mkldnn，通过omp的环境变量控制线程数。

**Comment by qq61786631** [comment]
@donproc
 谢谢您的反馈。咨询下测试mkldnn时候出现内存不断增长问题吗？我测试下来每次运行都要增加200M左右，应该是mkl的问题吧。
我几次测试下来发现 use_mkldnn_=0  + set_cpu_math_library_num_threads=0 尽然是速度最快的，OMP_NUM_THREADS 好像没有啥效果呀。o(╯□╰)o

**Comment by OliverLPH** [comment]
> @donproc
> 谢谢您的反馈。咨询下测试mkldnn时候出现内存不断增长问题吗？我测试下来每次运行都要增加200M左右，应该是mkl的问题吧。
> 我几次测试下来发现 use_mkldnn_=0 + set_cpu_math_library_num_threads=0 尽然是速度最快的，OMP_NUM_THREADS 好像没有啥效果呀。o(╯□╰)o

@qq61786631 
请问您是使用的什么版本的预测库呢，能麻烦提供下`version.txt`中的信息吗? 我们再复现下

**Comment by donproc** [comment]
> @donproc
> 谢谢您的反馈。咨询下测试mkldnn时候出现内存不断增长问题吗？我测试下来每次运行都要增加200M左右，应该是mkl的问题吧。
> 我几次测试下来发现 use_mkldnn_=0 + set_cpu_math_library_num_threads=0 尽然是速度最快的，OMP_NUM_THREADS 好像没有啥效果呀。o(╯□╰)o

mkldnn 用了jit，会生成primitve cache， 确实memory会增长，尤其是动态shape的时候。

**Comment by qq61786631** [comment]
@donproc
1.8.2吧
version.txt：
GIT COMMIT ID: 0b3f6265819d9ee0c0e08f76ed568e2057a7aa0e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF

了解了，谢谢，use_mkldnn_=0 的时候内存是正常的，是因为没有调用MKL，paddle有内置函数计算的原因吗。

**Comment by luotao1** [comment]
动态shape在使用mkldnn的时候，请参考 https://github.com/PaddlePaddle/Paddle/issues/25506#issuecomment-657587675
使用`config.SetMkldnnCacheCapacity(cache_capacity);`，cache_capacity=10表示，只缓存10个不同shape的cache，这样就不会内存泄漏了。

@cryoco 是否考虑在官网的预测API和这里，加一下文档说明，或者有其他方式可以提醒用户用一下这个接口呢？

**Comment by donproc** [comment]
> @donproc
> 1.8.2吧
> version.txt：
> GIT COMMIT ID: 0b3f6265819d9ee0c0e08f76ed568e2057a7aa0e
> WITH_MKL: ON
> WITH_MKLDNN: ON
> WITH_GPU: OFF
> 
> 了解了，谢谢，use_mkldnn_=0 的时候内存是正常的，是因为没有调用MKL，paddle有内置函数计算的原因吗。

对的。

另外, @OliverLPH 我们没能复现您的情况。请问您是在命令行里执行exe的吗？设置完环境变量后，重新开启powershell 或者 cmd 了吗？

**Comment by luotao1** [comment]
@lidanqing-intel 能帮忙看下这个问题么？mkldnn打开与否，开了多线程后windows加速比都不正常，但在linux上加速比是正常的。

**Comment by lidanqing-intel** [comment]
好的

**Comment by lidanqing-intel** [comment]
@luotao1 你们可以把这个复现一下吗？我在复现的过程中很多问题，修了后面还有。可能是这段时间又合入了一些PR？
1. fatal error C1083: Cannot open include file: 'unsupported/Eigen/CXX11/Tensor': No such file or directory
我把这行注释后，依然报下面的错误
2.  fatal error LNK1104: cannot open file 'libyaml-cppmt.lib'

**Comment by luotao1** [comment]
收到 @OliverLPH 可以帮忙看下是不是develop出现问题了，谢谢！

**Comment by OliverLPH** [comment]
> 收到 @OliverLPH 可以帮忙看下是不是develop出现问题了，谢谢！
@luotao1 
好的

**Comment by lidanqing-intel** [comment]
@OliverLPH  Could you please use 1.8.4, because 1.8.4 is stable now right?
Also can you send the CPU you are using on windows if you reproduced successfully

**Comment by OliverLPH** [comment]
@lidanqing-intel 
我在 i7-8700k 和 i7-9700k 上都重新验证了下这个issue，Paddle-OCR的编译应该都是可以走通的，需要修改一些内容。
只是这两个CPU上的表现有些不一样，数据如下

[1.8.4 paddle inference lib](https://paddle-wheel.bj.bcebos.com/1.8.4%2Fwin-infer%2Fmkl%2Fcpu%2Ffluid_inference_install_dir.zip),  disable mkldnn, no warm-up process, repeat predict 100 times.
* i7-9700k, 8 cores
cpu_math_library_num_threads=1, 2, 4, 6, 8
total predict time is  17.1665s, 16.8652s, 16.2073s, 16.2462s, 16.361s

* i7-8700k, 6 cores
cpu_math_library_num_threads=1, 2, 4, 6
total predict time is  18.5361s, 18.6993s, 19.1258s, 20.4289s

i7-9700k看起来，cpu_math_library_num_threads可以提升一些性能。

以下是我的复现流程，你可以参考下哈
```batch
git clone https://github.com/PaddlePaddle/PaddleOCR.git
cd PaddleOCR

rem convert checkpoint to inference model
rem https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md
rem the README seems update recently, and models look like update
rem follow the instruction and convert ch_det_mv3_db.tar and ch_rec_mv3_crnn.tar

cd deploy\cpp_infer
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_MKL=ON -DWITH_GPU=OFF -DWITH_STATIC_LIB=ON -DPADDLE_LIB=%1.8.4-lib% -DOPENCV_DIR=%opencv-install-dir%
call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

rem src\main.cpp line 79 has Chinese character, may cost compile failed
msbuild /m /p:Configuration=Release ocr_system.sln

cd Release
.\ocr_system.exe ..\..\tools\config.txt ..\..\..\doc\imgs\10.jpg
```

**Comment by lidanqing-intel** [comment]
@OliverLPH  Why disabling mkldnn? If it is disabled, then mkldnn fuses are not enabled. Can you check with -DMKLDNN on?

**Comment by lidanqing-intel** [comment]
@OliverLPH  If MKLDNN is OFF, only MKL is ON, then it any mkldnn fuse is not used, only omp some code using `#pragma omp parallel for... ` could be improved. OMP parallel can slow down because some critical section is accessed, because each thread need to lock and unlock etc. And if each thread is not fast enough, it can happen that overall performance is not good.

Have you had time to check on the same machine, how is linux os system perform? If Linux also behave like this on same machine, then maybe we don't need to fix

**Comment by OliverLPH** [comment]
@lidanqing-intel 
1. disable MKLDNN is because only `set_cpu_math_library_num_threads` performance is not good. Anyway, I will try with -DMKLDNN=ON tomorrow.

2. As for checking linux os on the same machine. Since our machine is not only for running tests and also for CI/CE, the 
 resources are quite limited, so I think it's hard for us to install extra os system on that machine. I will discuss with @luotao1 about this.

**Comment by lidanqing-intel** [comment]
@OliverLPH  Could you also check to build with MKL OFF, so that it will use openblas, and theset_cpu_math_library_num_threads  will also take effect, and paste the performance results?

**Comment by luotao1** [comment]
> If Linux performs similarly on the same machine, then maybe we don't need to fix.

@lidanqing-intel https://github.com/PaddlePaddle/PaddleOCR/issues/429#issuecomment-664852506 @OliverLPH 验证了下linux环境下（cpu：E5-2650, avx2）set_cpu_math_library_num_threads 参数提速都很明显。
Windows环境（cpu：i7-8700k，6核）下存在该问题。

> As for checking Linux os on the same machine

@lidanqing-intel Do you mean using Linux os on the windows machine? It is not Paddle's users' behavior.

**Comment by luotao1** [comment]
> Since we don't have i7 with windows or Linux

@lidanqing-intel Could you ask Sean for the i7 machine support, since a lot of teachers/students use windows OS in China.

**Comment by lidanqing-intel** [comment]
@luot Ok, I will ask Sean for i7 support.

**Comment by OliverLPH** [comment]
@lidanqing-intel 
ok, I will do the same experiment with openblas lib

**Comment by lidanqing-intel** [comment]
@OliverLPH @luotao1  Does openblas multi-threading works on Windows? I saw this comment in 
**/home/li/repo/Paddle/paddle/fluid/platform/cpu_helper.cc: line 30**, 


```
void SetNumThreads(int num_threads){
// windows has no support for openblas multi-thread
// please refer to: https://github.com/PaddlePaddle/Paddle/issues/7234
#ifdef _WIN32
  if (num_threads > 1) {
    num_threads = 1;
  }
#endif
and this issue [7234](https://github.com/PaddlePaddle/Paddle/issues/7234)
...
...
}
```

**Comment by OliverLPH** [comment]
@lidanqing-intel 
Openblas results on i7-8700k 



The results of openblas and MKLDNN are 
 [experiments process](https://github.com/PaddlePaddle/PaddleOCR/issues/429#issuecomment-693421651)

**Comment by OliverLPH** [comment]
@lidanqing-intel
* Openblas results on i7-8700k
set_cpu_math_library_num_threads = 1, 2, 4, 6
toatal prediction time = 56.6196s, 56.7433s, 57.0416s, 56.7973s

As you mentioned [comment](https://github.com/PaddlePaddle/PaddleOCR/issues/429#issuecomment-693500898), it seems multi-threading has no effect on windows.

* MKLDNN results on i7-8700k
set_cpu_math_library_num_threads = 1, 2, 4, 6
toatal prediction time = 4.21707s, 4.23634s, 4.22947s, 4.24025s

MKLDNN has rapid speed-up compared with MKL. However, multi-threading with MKLDNN still don't have obvious effect

**Comment by lidanqing-intel** [comment]
@OliverLPH  Thanks, could you please run it again with following setting

set MKL_VERBOSE=1
set DNNL_VERBOSE=1
set KMP_AFFINITY=verbose
 
run 1 thread and 4 thread.

and send me the log ?

**Comment by lidanqing-intel** [comment]
We think this application does not have many op that used `#pragma omp parallel for `
Printing the verbose logs will show us how many ops used omp.

**Comment by OliverLPH** [comment]
@lidanqing-intel 
For your information
[thread1_mkldnn.log](https://github.com/PaddlePaddle/PaddleOCR/files/5238503/thread1_mkldnn.log)
[thread4_mkldnn.log](https://github.com/PaddlePaddle/PaddleOCR/files/5238504/thread4_mkldnn.log)

**Comment by lidanqing-intel** [comment]
@OliverLPH  请问这个thread4_mkldnn.log日志是同时设置set MKL_VERBOSE=1 set DNNL_VERBOSE=1 set KMP_AFFINITY=verbose得到的，还是只设置了DNNL_VERBOSE=1？
如果同时设置了三个，只得到了这个日志的话，说明这个应用一个omp parallel都没有用到，增加cpu_math_library_num_threads对这个应用就不起作用.这个线程就是为MKLML omp的

你看下我跑ernie模型，同时设置上面三个verbose得到的日志是这样的
[MKL_verbose_example.txt](https://github.com/PaddlePaddle/PaddleOCR/files/5238707/MKL_verbose_example.txt)

**Comment by OliverLPH** [comment]
@lidanqing-intel 
我确认了下，thread4_mkldnn.log和thread1_mkldnn.log日志都是设置了 set MKL_VERBOSE=1 set DNNL_VERBOSE=1 set KMP_AFFINITY=verbose得到的。
![image](https://user-images.githubusercontent.com/14963836/93548127-29833a80-f999-11ea-91e4-ce2627428e40.png)

那是否说明增加cpu_math_library_num_threads 在Windows平台无效，还是针对该cpu无效呢？

**Comment by lidanqing-intel** [comment]
@yinghu5 百度回复说，设置了打出MKL_VERBOSE,结果一个MKL_VERBOSE都显示不出。我在想有没有一个立刻可以跑的Windows可用的示例程序，我们跑一下就知道，是不是CPU或者电脑的设置问题，我找那个文档，不好找啊样例程序你知道在哪里吗。另外，如果那个样例可以显示MKL_VEROBOSE的日志，那我们就再看看是不是打包的时候MKL 连接的设置没连接好还是怎样。MKL的Windows连接难吗，相比Linux有什么要注意的吗？怎么查看Windows的包成功连接了MKL呢，又什么one click check吗？

**Comment by lidanqing-intel** [comment]
@OliverLPH  I ahve 
You can write somewhere print the omp settings

int number=omp_get_num_threads()

It is like a print sentence. 

After adding this, the printed log should print out this number

**Comment by OliverLPH** [comment]
@lidanqing-intel 
请问这个变量`omp_get_num_threads()` 是否指的是Paddle 的 `cpu_math_library_num_threads()` API ？

**Comment by lidanqing-intel** [comment]
@OliverLPH 应该是的，你好像要这么调， config.cpu_math_library_num_threads(), 这个config就是要么analysisconfig,要么nativeconfig,程序里肯定有的

**Comment by lidanqing-intel** [comment]
> @lidanqing-intel
> 请问这个变量`omp_get_num_threads()` 是否指的是Paddle 的 `cpu_math_library_num_threads()` API ？
Add in the code
```
#include "omp.h"
...
std::cout<<"WARNING! Get threads"<<omp_get_max_threads()<<std::endl;
...
```

**Comment by lidanqing-intel** [comment]
@OliverLPH 可以麻烦你把你用的两个模型 det 和 rcnn的发给我不？我在网上那个链接下载的，predictor跑不了，前面fuse跑的过，但是在Run代码突然就结束了，也不报错，也没输出。

昨天我在那个main.cpp里面predictor之前写了多线程循环的个小例子，另外在CMakeList.txt里面多加了些compiler omp的flag（-fopenmp, STACK...），目前main.cpp 可以用omp parallel，KMP_AFFINITY=1有日志，日志打出来显示了小例子跑在4个线程上。因此，omp有用的。

验证MKL_VERBOSE，我就需要两个模型了，不跑模型就走不到MKL。请你发你用的两个模型给我吧，谢谢！

**Comment by OliverLPH** [comment]
@lidanqing-intel 
好的，我整理下发你

**Comment by lidanqing-intel** [comment]
@OliverLPH 
@qq61786631

采用教程编译了windows下的 ocr_system.exe（mkl数学库），测试发现，同一张图片有如下情况

Q1: 同样的cpu_math_library_num_threads_=10情况下，use_mkldnn 选项打开耗时(1.85s) 关闭选项(1.6s)
A1: 打开use_mkldnn比关闭mkldnn还要慢，是因为只测了一张图片。使用mkldnn会做很多fuse，第一个iteration需要fuse很多op，需要改图等，这些时间都算在latency里了。你试试几百几千张图片，那样测性能才有意义。

Q2: use_mkldnn 关闭，cpu_math_library_num_threads_=0时，耗时1.4s cpu_math_library_num_threads_=12时，耗时1.9s
A2: use_mkldnn 关闭，cpu_math_library_num_threads_=0时，耗时1.4s cpu_math_library_num_threads_=12时，耗时1.9s，你可以通过MKL_VERBOSE=1打印，我观察到这个测试所有GEMM都在thread0上工作，哪怕设置cpu_math_library_num_threads_=12。我不确定是否是因为只测一张图片的原因。但是这个case就是只跑在了1个线程上。但是omp配置是没有问题的，你可以通过这个小例子测试。

```
I will fill this test case
omp test
```

因此我建议你使用批量图片进行性能测试。

**Comment by jiachen0212** [comment]
> 动态shape在使用mkldnn的时候，请参考 [PaddlePaddle/Paddle#25506 (comment)](https://github.com/PaddlePaddle/Paddle/issues/25506#issuecomment-657587675)
> 使用`config.SetMkldnnCacheCapacity(cache_capacity);`，cache_capacity=10表示，只缓存10个不同shape的cache，这样就不会内存泄漏了。
> 
> @cryoco 是否考虑在官网的预测API和这里，加一下文档说明，或者有其他方式可以提醒用户用一下这个接口呢？

很赞，解决了我的mkldnn开启内存爆炸问题。不过，开启mkldnn后我的速度基本没提升啊。 linux 下 单核cpu情况。是和cpu型号有关吗。我的cpu是：4  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
