### ISSUE TITLE
How to recognize rotated image properly using paddleocr?

### ISSUE THREAD

**Issue by mobassir94** [PaddlePaddle/PaddleOCR#4291]
hello,
i have an image that looks like this :  https://ibb.co/PZ3fGFR

if i use this image using the code below : 

```
from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
img_path = 'tests/t3.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
```
it can't recognize but if i use your this lightweight online demo api  : https://www.paddlepaddle.org.cn/hub/scene/ocr

then it works fine,how to modify the code so that it can recognize rotated image like your online demo api? thanks

**Comment by littletomatodonkey** [comment]
Sorry, it's hard for me to open the link you provide, you can upload the original image as an attachment on github, i will have a test, thx!

**Comment by littletomatodonkey** [comment]
And, the two methods are different because they use the different models. So the final results might be different.

**Comment by mobassir94** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/24439592/136892712-6b2290a2-fccb-410a-ae13-2e64dfa95890.png)
@littletomatodonkey here is the image

**Comment by navneetkrc** [comment]
@littletomatodonkey Any update/suggestion for this type of image. I am also having issues with similar type of image orientations. Use case ID Card OCR.

**Comment by omarhassan97** [comment]
reopen
