### ISSUE TITLE
使用hub serving部署paddleocr

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4293]
#通过配置文件启动
!export CUDA_VISIBLE_DEVICES=0 &&  hub serving start -c deploy/hubserving/ocr_system/config.json 
服务器执行完这一步之后
本地电脑请求服务
!python tools/test_hubserving.py  http://10.10.23.230:8868/predict/ocr_system doc/datasets/cmb_demo.jpg
这样本地电脑是必须进入到远程服务器端工程所在的路径,然后进入到该虚拟环境,而且这个预测的图片也必须是服务器端的
麻烦问一下如何才能预测本地电脑上的图片哪

**Comment by MissPenguin** [comment]
本地运行test_hubserving.py就行，这是客户端，放哪儿都可以的

**Comment by zhangyingying520** [comment]
> 没找到文件啊，脚本在本地吗
你的意思是，得在本地某个地方下载一个test_hubserving.py脚本，在执行吗

**Comment by MissPenguin** [comment]
> > 没找到文件啊，脚本在本地吗
> > 你的意思是，得在本地某个地方只需要下载一个test_hubserving.py脚本，再从本地电脑执行
> > !python tools/test_hubserving.py http://10.10.23.230:8868/predict/ocr_system doc/datasets/cmb_demo.jpg
> > 就可以了吗

是的，本地用客户端发送图片到服务地址，服务端处理请求，返回识别结果到客户端。`test_hubserving.py`这个脚本就是客户端，http://10.10.23.230:8868/predict/ocr_system 就是你搭建的服务地址

**Comment by zhangyingying520** [comment]
> > > 没找到文件啊，脚本在本地吗
> > > 你的意思是，得在本地某个地方只需要下载一个test_hubserving.py脚本，再从本地电脑执行
> > > !python tools/test_hubserving.py http://10.10.23.230:8868/predict/ocr_system doc/datasets/cmb_demo.jpg
> > > 就可以了吗
> 
> 是的，本地用客户端发送图片到服务地址，服务端处理请求，返回识别结果到客户端。`test_hubserving.py`这个脚本就是客户端，http://10.10.23.230:8868/predict/ocr_system 就是你搭建的服务地址

这样不太对吧，我从客户端请求服务，不是应该直接请求就行吗？还用的着这些文件吗
