### ISSUE TITLE
以下结构识别模型概率性预测中断？预测的结果会缺失一部分

### ISSUE THREAD

**Issue by EricHuiK** [PaddlePaddle/PaddleOCR#4296]
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.75
    model_name: large
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

    hidden_size: 64
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

**Comment by MissPenguin** [comment]
有报错信息吗
