### ISSUE TITLE
检测与识别问题

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4297]
训练集中需要检测的目标字符，由于工作距离的原因出现同一个字符大小不一致的情况，请问这种情况影响最后的检测与识别效果吗？

**Comment by 18362890185** [comment]
> 可以贴个case看下吗，没太理解您说的这个问题。。
![MouldNumber-A-02](https://user-images.githubusercontent.com/87969070/136902130-7c57bb11-6d53-43dd-9213-ecfdcf019191.png)
![MouldNumber-A-06](https://user-images.githubusercontent.com/87969070/136902166-a60de256-627b-49ea-8367-dddc6639718a.png)

![MouldNumber-A-02-crop0](https://user-images.githubusercontent.com/87969070/136902189-f4eb9904-f832-4718-9971-dda5c340623b.png)
![MouldNumber-A-06-crop0](https://user-images.githubusercontent.com/87969070/136902237-ae529f8e-2f60-4bfd-bbd3-3cbea345f397.png)

这种情况：两个A大小不一致（由于拍摄镜头工作距离不一致），这个影响最终的结果吗？

**Comment by MissPenguin** [comment]
只要训练数据充足，不影响的，模型是具有一定鲁棒性的

**Comment by 18362890185** [comment]
> 只要训练数据充足，不影响的，模型是具有一定鲁棒性的

好的，谢谢您
