### ISSUE TITLE
A minor error in network definition

### ISSUE THREAD

**Issue by lkevinzc** [PaddlePaddle/PaddleOCR#430]
https://github.com/PaddlePaddle/PaddleOCR/blob/10880fc135dee84680bd8f78a784953090107aa1/ppocr/modeling/backbones/rec_mobilenet_v3.py#L46

Hi! Thanks for this great project!!

In my opinion, there is a minor error in the network definition. Referring to the code above, I think the stride should be (2,1) to make the feature map size correct.

Please kindly check and refine if needed.

Thank you!

**Comment by littletomatodonkey** [comment]
Thanks for your attention!  That's a good question, actually we found that the stride set as 1 is better for the model performance compared with `(2,1)`(>1.5% absolute accuracy improvement) while takes just a liitle more time cost(less than 5%). So we set the stride as `1` here. And we are also carrying out experiments on different strides on mobilenet small backbone, the results are on the way!
