### ISSUE TITLE
paddlepaddle-gpu运行会卡住

### ISSUE THREAD

**Issue by chereyk** [PaddlePaddle/PaddleOCR#4302]
cuda版本是10.2，cudnn版本是7.6.5，系统是windows10专业版，显卡是3060，paddlepaddle是2.1.3，python是3.8（也在3.7上尝试过），pip是21.0.1
现象是在运行paddle.fluid.install_check.run_check()时会卡住很久，最后崩溃退出，在训练模型时，会卡住半个小时左右然后开始正常训练
我以为是版本适配问题，所以尝试过10.1，10.0，11.0，11.2，最后发现都有这个问题，重装系统还是有这个问题。在paddlepaddle官方论坛和其他地方查了很久发现也有其他同学遇到这个问题，但都没有解决办法，所以只能麻烦官方大佬可以查看一下。

**Comment by skydragron** [comment]
我也遇到了， 而且不是半个小时，是挂了一个晚上，在某处卡了十几个小时，卡在训练的时候save mode in，另外训练遇到多次卡在save mode in 半小时左右、一小时左右都有，多次！！！！
