### ISSUE TITLE
C++推理的识别功能是否能增加批处理操作

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleOCR#4303]
rt
因为我看python端的识别是支持批处理的，但是C++端的还不支持，所以想咨询一下。

我也尝试过自己修改，但是由于每张待识别的图的尺寸不同，无法使用reshape来约束input_tensor的尺寸，不知如何解决该问题。

谢谢各位。

**Comment by MissPenguin** [comment]
近期会支持该功能。
