### ISSUE TITLE
使用自己的数据集训练检测模型出错

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#431]
报错信息为：
 File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 20 (char 19)
返回标签文本查看时，发现这是\t的位置，应该怎么样制作符合格式的检测数据集标签？

![1](https://user-images.githubusercontent.com/51456283/88521965-4d28a500-d028-11ea-947a-675d70fa089b.PNG)

**Comment by littletomatodonkey** [comment]
可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md

每行有2个字段，前面是文件名，后面是json.dumps的结果

**Comment by tyy2tyy** [comment]
json.dumps的结果要与示例上面的一模一样吗

**Comment by littletomatodonkey** [comment]
格式相同即可，内容是根据你自己的标注来保存的

**Comment by tyy2tyy** [comment]
前面的transcription部分的文字在检测时不需要这个信息，能否直接制作point？

**Comment by littletomatodonkey** [comment]
可以的，在检测时，可以把transcription这个字段置为`""`，不影响检测模型的训练

**Comment by tyy2tyy** [comment]
好的，谢谢您

**Comment by tyy2tyy** [comment]
您好，我按照json.dumps处理了数据，但在运行时还是出错了
![2](https://user-images.githubusercontent.com/51456283/88614727-f0c69380-d0c2-11ea-9c57-3feaf7bb7a83.PNG)
这是我的转化部分代码
![1](https://user-images.githubusercontent.com/51456283/88614810-1eabd800-d0c3-11ea-95c5-d9a3c2cbac93.PNG)

**Comment by MissPenguin** [comment]
replace等一系列操作完成后再执行json.dumps试试
