### ISSUE TITLE
Unable to recognise spaces in English sentences

### ISSUE THREAD

**Issue by perldeniel** [PaddlePaddle/PaddleOCR#432]
I was trying out the db_crnn_server space-enabled inference model and I discovered that in most cases spaces are not recognised.

I understand that this repo is still under heavy development and props to the team for such good work!

Is there an opportunity for us to contribute and help resolve the spacing issue? If yes, can you share us the exact procedures of how to improve the model?

Regards,
Perl.

**Comment by littletomatodonkey** [comment]
Thanks for your attention!  Could you please show some bad cases for us to check the model?  If you want to improve the model performance on your dataset, you can finetune the models based on the pretrained models we published, You can refer to the [Recognition tutorial](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/recognition_en.md) for more details on dataset format, finetuning tricks and so on. Welcome to feedback anytime you have problems.

**Comment by perldeniel** [comment]
Based on my understanding, fine tuning a model often requires either some tuning in the network architecture, playing with the training configuration or simply feed it a more diverse dataset. Which one of the following are you referring to?

**Comment by littletomatodonkey** [comment]
I was referring to playing with the training configuration or simply feed it a more diverse dataset. Your dataset distribution may not be same as that of PaddleOCR, therefore I think the finetuing process on your own dataset is necessary for better performance.

**Comment by navneetkrc** [comment]
Hey @perldeniel Were you able to solve the issue.
I am running PaddleOCR for ID card OCR and somehow all the spaces are ignored. The recognition other than space is very good, but I need to provide the Names with spaces as well for verification ([Example image](https://github.com/manthan3105/OCR-for-PAN-card-using-tesseract/blob/master/test%20images/pan6.jpg) )
I could not configure spaces, will be going through [Tricks](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/tricks_en.md) tutorial link provided by @littletomatodonkey .

**Comment by navneetkrc** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/524#issuecomment-673957704
There are models that support spaces on the homepage, you can try
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/README_cn.md

But this disconnection is also related to the way of labeling during training. If you want to have better results in your own scene, you can perform finetune based on the model on the official website.

![image](https://user-images.githubusercontent.com/26484573/90388103-ee919c80-e0a4-11ea-92db-ee0e2a3cfa4a.png)

**Comment by 21143** [comment]
If I want to add my own images to the dataset for finetuning, how many images (roughly speaking) would I need to add ?

**Comment by tianyi-qi-zefr** [comment]
> [#524 (comment)](https://github.com/PaddlePaddle/PaddleOCR/issues/524#issuecomment-673957704)
> There are models that support spaces on the homepage, you can try
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/README_cn.md
> 
> But this disconnection is also related to the way of labeling during training. If you want to have better results in your own scene, you can perform finetune based on the model on the official website.
> 
> ![Space Recognition model](https://user-images.githubusercontent.com/14270174/90229669-df171700-de4a-11ea-9ac2-2668deae800e.png)

the link is no longer valid, where can I find the model with space support? thank you!
