### ISSUE TITLE
paddleocr C++ VS2019编译问题

### ISSUE THREAD

**Issue by shmonly** [PaddlePaddle/PaddleOCR#4321]
跪求各位大神，win预测库paddle_inference.zip（2.1.1），cmake3.18.0，vs2019，使用VS2019生成时，报错如下图，该如何解决？
![7d21dedf43cef87763a993e22bae8d4](https://user-images.githubusercontent.com/42912454/137110012-3fcad5da-b58c-4bb1-888b-7fd3fd5a026c.png)

**Comment by shmonly** [comment]
> 参考这个文档： https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/docs/windows_vs2019_build.md

是2.1语法的问题，现在可以生成exe了。但cmd运行exe，直接弹窗ocr_system.exe已停止工作（如下图）

**Comment by Gmgge** [comment]
尝试关闭MKL呢？再cmakelist里面吧mkl关掉重新编译试试

**Comment by pollyyan** [comment]
您有尝试按照文档中所写的，在D:\projects\PaddleOCR\deploy\cpp_infer\这级目录中运行文档中的指令吗？
![image](https://user-images.githubusercontent.com/38637686/139634964-4134b042-7661-493c-93c7-b847a6775069.png)

**Comment by Topdu** [comment]
建议尝试release/2.3分支
