### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4324]
麻烦问一下官方提供的代码
![ZJDI7%{`9T}{20(DI)`(V0R](https://user-images.githubusercontent.com/80818728/137235164-a4dedc14-b6be-4fc1-8e4e-b587b4c08338.png)
![9HUAE%Q5 8`EZL}`JDG`OXB](https://user-images.githubusercontent.com/80818728/137235168-a1135fb8-c318-4dd4-8de6-01c99e7c8837.png)
这些版本是什么意思

**Comment by ioracion** [comment]
迭代升级

**Comment by zhangyingying520** [comment]
> 建议了解一下Trunk、Branches、Tags，百度一下就有 可以选择Branches中2.3的版版本。

谢谢
