### ISSUE TITLE
马来文【ms】识别结果为什么无空格？

### ISSUE THREAD

**Issue by Paul0M** [PaddlePaddle/PaddleOCR#4325]
paddle:2.1.3
paddleocr:2.3.0.1

检测模型：en_ppocr_mobile_v2.0_det_infer
识别模型：latin_ppocr_mobile_v2.0_rec_infer

字符集：dict/latin_dict.txt
字体：latin.ttf

**Comment by tink2123** [comment]
字典是支持空格的，识别结果没有空格可能和检测框过紧有关。可以提供一下你的预测图片吗？
