### ISSUE TITLE
串联识别

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4327]
![ModelNumber-1 1-1_crop_0](https://user-images.githubusercontent.com/87969070/137261691-476cdadc-7314-43b1-bf9c-de242262fcb8.jpg)
![ModelNumber-1 2-1_crop_0](https://user-images.githubusercontent.com/87969070/137261704-49c57c6e-8476-457f-a2a0-d72d1d14de94.jpg)
请问，1.1效果很好，1.2读成1.1或者1 这种情况一般是什么原因导致的？

**Comment by 18362890185** [comment]
> 可能训练数据不平衡导致的，1 字符出现频率远大于2。 可以多找几个1.2类似的图片测试看看，这个情况是不是必现的。

我标注的时候 字符是这种倒着的 这样会不会无法识别（只能单行识别）
