### ISSUE TITLE
paddleocr如何指定第几块GPU进行推理？

### ISSUE THREAD

**Issue by liu1073811240** [PaddlePaddle/PaddleOCR#4329]

**Comment by tink2123** [comment]
设置环境变量：
# 使用第0号卡
export CUDA_VISIBLE_DEVICES=0

**Comment by 1a2cjitenfei** [comment]
> 设置环境变量：
> 
> ```
> # 使用第0号卡
> export CUDA_VISIBLE_DEVICES=0
> ```

哥，怎么提高paddleocr预测时GPU的利用率呀，使用了use_gpu=True在单张卡2080ti上只占不到20%

**Comment by liu1073811240** [comment]
首先模型只有这么大，其次为什么要提高GPU利用率。不能正常使用吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] paddleocr如何指定第几块GPU进行推理？ (#4329)





  
设置环境变量：
 # 使用第0号卡 export CUDA_VISIBLE_DEVICES=0   
哥，怎么提高paddleocr预测时GPU的利用率呀，使用了use_gpu=True在单张卡2080ti上只占不到20%
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by puneeth072003** [comment]
I request to work on this project

**Comment by jaycecd** [comment]
> 设置环境变量：
> 
> ```
> # 使用第0号卡
> export CUDA_VISIBLE_DEVICES=0
> ```
windows使用os.environ['CUDA_VISIBLE_DEVICES'] = '1'无法指定使用第2块显卡，始终会使用第一张显卡；
通过查看源码，发现tools/infer/utility.py中存在如下代码：
`config.enable_use_gpu(args.gpu_mem, 0)`
设置是使用第一个gpu，即id是0的GPU，请问能不能设置使用指定gpu进行推理？
@tink2123 @Evezerest @liu1073811240
