### ISSUE TITLE
测试ppstructure中TEDS指标结果

### ISSUE THREAD

**Issue by dcdethan** [PaddlePaddle/PaddleOCR#4330]
文件准备：直接使用[https://github.com/ibm-aur-nlp/PubTabNet/blob/master/src/sample_gt.json](url)这个文件进行TEDS指标测试，该文件对应的图片我已经从pubtabnet里摘出来了，[https://pan.baidu.com/s/1kS0qlRDO9rdupjiKY-6ofw](url)， 密码q9s5
代码修改：ppstructure/table/eval_table.py文件45行设置img_root为图片路径，50行gt_structures, gt_bboxes, gt_contents = jsons_gt[img_name]['html']注释，新增gt_html = jsons_gt[img_name]['html']

**Comment by dcdethan** [comment]
sample_gt.json里有一张图没找到，从json找到相应信息删掉就可以了。

**Comment by WenmuZhou** [comment]
好的
