### ISSUE TITLE
表格预测模型训练

### ISSUE THREAD

**Issue by TUDelftHao** [PaddlePaddle/PaddleOCR#4337]
1. 请问训练中用到的table_structure_dict是如何生成的？以及其中有大量的数字代表什么意思呢？
![image](https://user-images.githubusercontent.com/46449831/137341518-f4258d50-ded6-4812-8400-a81beb265ff4.png)
2. 如果要训练自己的表格数据集，有没有相关的标注工具可以生成类似jsonl格式的标注文件呢？
谢谢！

**Comment by zengchan** [comment]
同问

**Comment by WenmuZhou** [comment]
这些数字没用到哈，是一些统计字符的信息
