### ISSUE TITLE
您好，我按照json.dumps处理了数据，但在运行时还是出错了

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#434]
您好，我按照json.dumps处理了数据，但在运行时还是出错了
![2](https://user-images.githubusercontent.com/51456283/88614727-f0c69380-d0c2-11ea-9c57-3feaf7bb7a83.PNG)
这是我的转化部分代码
![1](https://user-images.githubusercontent.com/51456283/88614810-1eabd800-d0c3-11ea-95c5-d9a3c2cbac93.PNG)

_Originally posted by @tyy2tyy in https://github.com/PaddlePaddle/PaddleOCR/issues/431#issuecomment-664750448_

**Comment by MissPenguin** [comment]
replace等一系列操作完成后再执行json.dumps试试

**Comment by tyy2tyy** [comment]
嗯，好的，已解决
