### ISSUE TITLE
请问paddle-lite android armv7的编译库推理pp_ocr模型 set_threads 没有速度提升？（多核cpu的 使用率一直是100%）

### ISSUE THREAD

**Issue by yank666** [PaddlePaddle/PaddleOCR#4354]
我编译paddle-lite 库使用下面的命令
./lite/tools/build_android.sh --arch=armv7 --toolchain=clang --android_stl=c++_shared --with_java=OFF --build_extra=ON --android_api_level=28
在cpu上跑时 设置多线程为4 和多线程设置为1 推理速度一样，没有性能的提升，cpu使用率最高也是100%（多核cpu），

![image](https://user-images.githubusercontent.com/79586188/137468290-2fad82e0-a53a-462c-b0f4-7987b5a35f1f.png)

在多核arm cpu上如何提升推理性能？

**Comment by mjp9527** [comment]
您好，--toolchain=gcc，clang armv7目前不支持openmp
