### ISSUE TITLE
andorid部署

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#4355]
作者您好，有一个比较困惑的地方,希望您能解答一下
  首先我用的是您安卓的项目，对于检测，所以使用的是ch_det_mv3_db_v2.0.yml配置文件训练出来的权重，在配置文件中，训练的时候用的size: [960, 960]，在验证的时候 image_shape: [736, 1280]被注释掉了，对此我有几点疑问
1.训练的时候是否也可以在验证部分将image_shape设置为[960, 960]，因为我的应用场景是android，对于摄像机获取的图像分辨率是固定的，验证时如果设置为与训练时同样的输入尺寸，获得的best_accuarcy是不是在验证集上可以达到更高的精度,部署的时候也能达到更到的精度
2.检测模型在推理的时候没有对图片进行resize，想请教一下这样做的原因是什么，当然即使是resize应该也是等比例缩放+pad，是不是说这样做的效果对精度提升并不明显且耗时
3.安卓端检测的时候有没有对图片进行resize，输入到model中的图片好像并没有resize，但是我看有个参数是input_shape=[1,3,960]，如果能设置这个resize的参数能够在哪里设置呢。

当然我可能对您代码的理解不够深刻，如果有错误的地方还请指出。

**Comment by GUOhm230** [comment]
> 

可以加个联系方式嘛？最近在试着把android_demo部署到某个安卓app上。但是一直出现bug。能不能请教下大佬？感激不尽
