### ISSUE TITLE
后期你们会增加表格文字识别吗?

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#436]
如果在此基础上进行表格文字识别，识别的最终结果怎么根据表格顺序结构化识别结果呢?

**Comment by dyning** [comment]
计划会针对表格场景进行文字识别进行优化，表格顺序结构化暂无计划。目前建议根据实际应用场景看是不是可以采用规则方法结构化信息。

**Comment by xxllp** [comment]
优化代码还是模型啊

**Comment by dyning** [comment]
模型和代码都会优化的

**Comment by xxllp** [comment]
good

**Comment by hsyy673150343** [comment]
怎样才能让输出的检测框的坐标有序？发自我的华为手机-------- 原始邮件 --------发件人： dyning <notifications@github.com>日期： 2020年7月28日周二 下午3:01收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleOCR] 后期你们会增加表格文字识别吗? (#436)

计划会针对表格场景进行文字识别进行优化，表格顺序结构化暂无计划。目前建议根据实际应用场景看是不是可以采用规则方法结构化信息。
