### ISSUE TITLE
使用原有的DB模型进行加载训练

### ISSUE THREAD

**Issue by lyc728** [PaddlePaddle/PaddleOCR#4364]
你好，我使用了ch_det_res18_db_v2.0进行训练，也下载了相应的模型，训练大概200轮和600轮进行预测时发现很多空白处误检
![5c220153-a615-4379-9f41-bb9f86493ef8](https://user-images.githubusercontent.com/88084847/137658416-f0b4b8be-cb94-4596-b50c-3e61caa44110.jpg)

**Comment by LDOUBLEV** [comment]
目前这个状态的精度有多少，

可以调整后处理参数，稍微加大一点后处理阈值，https://github.com/PaddlePaddle/PaddleOCR/blob/507129207b854b333d575839b8ce4cfa296a1411/configs/det/det_r50_vd_db.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L52
