### ISSUE TITLE
使用centerloss 时，怎么生成初始化需要的train_center.pkl文件，麻烦提供下参考代码

### ISSUE THREAD

**Issue by pmspku** [PaddlePaddle/PaddleOCR#4366]

**Comment by WhuRan** [comment]
> 请问你弄清楚这个问题了吗，因为我看center_loss.py中声明center使用的是paddle.randn，感觉确实没有参与到训练更新

**Comment by 2017ZYS** [comment]
看了代码，确实没有看到单独针对centerloss参数设置优化器的设置（也就是两个优化器），也没有看到将centerloss参数和模型权重参数合并，共用一个优化器，所以我理解应该就是无论是随机初始化center的参数还是预先加载center文件，centerloss的参数都没有参与更新，这样做真的好吗？
