### ISSUE TITLE
关于文字检测训练模型和导出模型效果不一样的问题

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#4371]
最新release/2.3分支：
训练过程中，在eval评估的时候，根据日志判断所有图片放大的736的大小，
![image](https://user-images.githubusercontent.com/15188456/137681188-e58f85e8-8b4d-4a2b-8156-20838fd108a3.png)
也就是说，此时这两个值为：
limit_side_len=736
limit_type="min"
通过infer_det.py进行预测的时候，值也是736和"min“

但是：
通过infer/predict_det.py预测的时候：
这两个值变成了，“640”和max“”
![image](https://user-images.githubusercontent.com/15188456/137681670-af06486a-cf66-4121-9860-4e3b6e74ea3c.png)

**Comment by YY007H** [comment]
@LDOUBLEV 大佬，帮忙看看，这个应该怎么处理呢？

**Comment by LDOUBLEV** [comment]
配置文件中为了保证能在ic15复现出预期精度，所有对评估的图像size有要求，

inference 推理的时候 考虑到速度问题，图像size不用设置那么大，也可以根据情况调整

你可以把预测的时候 inference 的预处理修改为和eval一样的预处理

**Comment by LDOUBLEV** [comment]
> 通过配置来先设置，只能设置最大或者最小，这块我觉得弄成一个范围比较好[736,960]，不至于图片尺寸太大的时候显存会爆，而且评估效果上也会好很多

是的，这样效果会好一些，但是速度会降下来，而且论文用的是736，配置文件中主要是向论文对齐

**Comment by YY007H** [comment]
> > 通过配置来先设置，只能设置最大或者最小，这块我觉得弄成一个范围比较好[736,960]，不至于图片尺寸太大的时候显存会爆，而且评估效果上也会好很多
> 
> 是的，这样效果会好一些，但是速度会降下来，而且论文用的是736，配置文件中主要是向论文对齐

建议文档这部分做点说明，要不然会导致训练的效果很好，而实际效果很差，主要体现在存在小于736图片的环境
如果训练环境和实际环境的图都大于736，效果一致，而如果大图小图都存在的时候，评估会误导实际效果
