### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4375]
模型训练的结果存在偶然性，同样的数据集和参数训练出的结果不一致（两次训练），请问这种情况应怎样调整？是训练的数据集不够导致的吗？

**Comment by LDOUBLEV** [comment]
评估精度是否继续提升?
应该是已经收敛了

**Comment by 18362890185** [comment]
> 评估精度是否继续提升? 应该是已经收敛了

精度无法达到1，在0.96左右徘徊
