### ISSUE TITLE
Windows编译失败无法打开包括文件: “paddle/fluid/framework/framework.pb.h”: No such file or directory

### ISSUE THREAD

**Issue by babykangaroo22** [PaddlePaddle/PaddleOCR#438]
1、windows编译，extern的内容几乎都下载失败了，这个是网络问题吗？
2、工程很多，应该选择哪些进行编译，比如使用ocr

**Comment by littletomatodonkey** [comment]
可以参考这篇文档进行编译，预测库的话，可以直接从官网下载：
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md

**Comment by babykangaroo22** [comment]
> 可以参考这篇文档进行编译，预测库的话，可以直接从官网下载：
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md

直接下载的有MD的版本吗，我下载下来都是MT的

**Comment by littletomatodonkey** [comment]
> > 可以参考这篇文档进行编译，预测库的话，可以直接从官网下载：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md
> 
> 直接下载的有MD的版本吗，我下载下来都是MT的

MT版本官网没有的话，可能需要自己编译生成预测库

**Comment by xinsuinizhuan** [comment]
Visual Studio 2019报错，就不能出个可以编译的版本吗，体验很不好
![图片](https://user-images.githubusercontent.com/40679769/88653103-3785af00-d0fe-11ea-9774-e42d8b6895db.png)

**Comment by littletomatodonkey** [comment]
可以把你的cmake配置信息发上来吗？我这边cmake build type选择relwithDebugInfo，使用mkl的预测库编译没有问题

**Comment by xinsuinizhuan** [comment]
> 
> 
> 可以把你的cmake配置信息发上来吗？我这边cmake build type选择relwithDebugInfo，使用mkl的预测库编译没有问题

我的cmake编译信息：
Microsoft Windows [版本 10.0.18363.900]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>cd /d I:\PaddlePaddle\PaddlePaddle\Paddle-develop\build

I:\PaddlePaddle\PaddlePaddle\Paddle-develop\build>cmake .. -G "Visual Studio 16 2019" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=OFF -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 4 cores
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe, version: MSVC 19.26.28806.0
-- C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe, version: MSVC 19.26.28806.0
-- AR tools:
-- Use static C runtime time, refer to https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019
-- Using parallel compiling (/MP)
-- Disable XBYAK in Windows and MacOS
-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/warpctc/bin/warpctc.dll
-- Build OpenBLAS by External Project (include: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/openblas/include/openblas, library: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/openblas/lib/openblas.lib)
-- Protobuf protoc executable: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/protobuf/bin/protoc.exe
-- Protobuf-lite library: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotobuf-lite.lib
-- Protobuf library: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotobuf.lib
-- Protoc library: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotoc.lib
-- Protobuf version: 3.1.0
CMake Warning at cmake/version.cmake:58 (message):
  Cannot add paddle version for wrong git branch result
Call Stack (most recent call first):
  CMakeLists.txt:207 (include)


-- Paddle version is 0.0.0
-- On inference mode, will take place some specific optimization.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- commit:
-- branch:
-- Configuring done
-- Generating done
-- Build files have been written to: I:/PaddlePaddle/PaddlePaddle/Paddle-develop/build

I:\PaddlePaddle\PaddlePaddle\Paddle-develop\build>

**Comment by littletomatodonkey** [comment]
windows上Paddle预测库可以直接下载的：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html
在这里建议选择带mkl的预测库

![image](https://user-images.githubusercontent.com/14270174/88878165-e1c61980-d259-11ea-8405-518d299b3de9.png)
