### ISSUE TITLE
PPOCR推理过程因图片大小而时间不一致

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#4382]
PPOCR版本2.0
在推理过程中，运行在CPU环境，单张图片推理时间（检测+方向+识别）正常需要时间5-7秒左右，部分10M大小图片，单张图片却需要40-70秒，相关参数设置为--det_limit_side_len=960 --det_limit_type='max'--enable_mkldnn=True，即所有图片的大小都设置成了长边最大为960进行resize，为什么推理时间差别这么大？

**Comment by Essence9999** [comment]
> 可以在预测的时候打开测试开关：--benchmark=True，打印各阶段耗时进行分析，推测主要耗时应该在读图部分。

大佬，对于分辨率小于736，但清晰的图片，没有方法放大图片便于模型识别（测试，经放大之后的图片能被识别）谢谢
