### ISSUE TITLE
字符Label标注

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4384]
![3269-6](https://user-images.githubusercontent.com/87969070/137867324-1b6b19d6-6ebd-463d-8ea8-cc6d8c8b7790.png)
![3269-7](https://user-images.githubusercontent.com/87969070/137867354-317a4a01-aa49-4f2d-996d-c124f9f9bc24.png)
请问，这种图片发生倾斜应该如何标注？

**Comment by Evezerest** [comment]
对比一下文件的分辨率吧，是不是显示的问题
