### ISSUE TITLE
请问android_demo中如何关闭方向分类模块？

### ISSUE THREAD

**Issue by yaoruinupt** [PaddlePaddle/PaddleOCR#4387]
您好，在我的项目中有一些孤立的字符，使用android_demo后发现有孤立的‘6’识别为‘9’的情况，怀疑是方向分类导致。请问如何在android项目中关闭方向分类这一环节？

**Comment by tink2123** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/507129207b854b333d575839b8ce4cfa296a1411/deploy/android_demo/app/src/main/cpp/ocr_ppredictor.cpp#L106

把这个地方的cls模块注释掉就好
