### ISSUE TITLE
编译时下载第三方库太慢

### ISSUE THREAD

**Issue by wumeng2** [PaddlePaddle/PaddleOCR#439]
编译时下载第三方库太慢，有什么解决办法，或者能否给出需要的第三方库地址，通过其他方式可以提前下载好吗？谢谢！

**Comment by LDOUBLEV** [comment]
请问是编译的哪个项目

**Comment by wumeng2** [comment]
> 请问是编译的哪个项目

就paddleocr这个项目，想通过c++预测，按照安装与编译Linux预测库教程，中间第三库下载很慢，试了好几次，都下完，有什么好的方法吗？谢谢

**Comment by LDOUBLEV** [comment]
> > 请问是编译的哪个项目
> 
> 就paddleocr这个项目，想通过c++预测，按照安装与编译Linux预测库教程，中间第三库下载很慢，试了好几次，都下不完，有什么好的方法吗？谢谢

安装与编译Linux预测库教程 中也提供了编译好的预测库下载链接，这里面没有适合你的环境的吗？

**Comment by LDOUBLEV** [comment]
你可以先提供给我一个你的环境，我这边下载好先发给你用着

**Comment by wumeng2** [comment]
> 你可以先提供给我一个你的环境，我这边下载好先发给你用着

好的，谢谢。
我会在2个环境使用
1. linux pc 平台  ubuntu 18.04.4   cpu:I3-8100  无显卡  opencv4.4
2.NVIDIA Jetson-Nano  用的nvidia自己的镜像 opencv4.2
邮箱：mmwu163@163.com
如果你们有可以开放的快速下载方式，可以直接给我，我自己下载也行，谢谢！

**Comment by LDOUBLEV** [comment]
编译paddle得到预测库时，third_party可以用这个文件：
```
# 下载下来放  Paddle/build目录下解压
wget  https://paddleocr.bj.bcebos.com/deploy/cpp_infer/cmake-3.11.1.tar.gz
wget  https://paddleocr.bj.bcebos.com/deploy/cpp_infer/third_party_gcc5.4.0.tar
```

![image](https://user-images.githubusercontent.com/26592129/88635018-b9b7a880-d0e9-11ea-9975-69d2966b6b0d.png)

可以考虑用我们的docker镜像，不确定在你的环境中会不会出现新的问题

**Comment by LDOUBLEV** [comment]
加个微信吧，我微信号：15623271969，有问题可以在群里交流

**Comment by wumeng2** [comment]
> 加个微信吧，我微信号：15623271969，我们有专门的用户群，有问题可以在群里交流

**Comment by wumeng2** [comment]
> 加个微信吧，我微信号：15623271969，我们有专门的用户群，有问题可以在群里交流

好的，我加过了，
wget  https://paddleocr.bj.bcebos.com/deploy/cpp_infer/cmake-3.11.1.tar.gz
wget  https://paddleocr.bj.bcebos.com/deploy/cpp_infer/third_party_gcc5.4.0.tar
下载很快，谢谢，我刚在Paddle/build下解压，出现新的问题

[  1%] Built target extern_gflags
[  1%] Built target extern_threadpool
[  1%] Performing update step for 'extern_mkldnn'
[  1%] copy_if_different /home/py/downloads/Paddle-develop/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  2%] Built target extern_boost
[  3%] Built target extern_eigen3
[  4%] Built target extern_xxhash
[  4%] Built target extern_zlib
[  4%] Built target extern_dlpack
CMake Error at /home/py/downloads/Paddle-develop/build/third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-update-Release.cmake:16 (message):
  Command failed: No such file or directory

   '/usr/local/bin/cmake' '-P' '/paddle/Paddle/Paddle/build/third_party/mkldnn/tmp/extern_mkldnn-gitupdate.cmake'

  See also

    /paddle/Paddle/Paddle/build/third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-update-*.log


CMakeFiles/extern_mkldnn.dir/build.make:94: recipe for target 'third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-update' failed
make[2]: *** [third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-update] Error 1
[  4%] Built target extern_xbyak
CMakeFiles/Makefile2:531: recipe for target 'CMakeFiles/extern_mkldnn.dir/all' failed
make[1]: *** [CMakeFiles/extern_mkldnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] copy_if_different /home/py/downloads/Paddle-develop/build/paddle/fluid/pybind/pybind.h
[  4%] Built target extern_gloo
[  4%] Built target extern_warpctc
[  4%] Built target before_extern_glog
[  4%] Built target extern_mklml
[  4%] Performing update step for 'extern_cryptopp'
[  4%] copy_if_different /home/py/downloads/Paddle-develop/build/paddle/fluid/operators/jit/kernels.h
CMake Error at /home/py/downloads/Paddle-develop/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update-Release.cmake:16 (message):
  Command failed: No such file or directory

   '/usr/local/bin/cmake' '-P' '/paddle/Paddle/Paddle/build/third_party/cryptopp/tmp/extern_cryptopp-gitupdate.cmake'

  See also

    /paddle/Paddle/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update-*.log


[  4%] Built target before_operator
CMakeFiles/extern_cryptopp.dir/build.make:94: recipe for target 'third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update' failed
make[2]: *** [third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update] Error 1
CMakeFiles/Makefile2:159: recipe for target 'CMakeFiles/extern_cryptopp.dir/all' failed
make[1]: *** [CMakeFiles/extern_cryptopp.dir/all] Error 2
[  4%] Built target before_jit_kernel_base
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by BruceXSK** [comment]
> > 你可以先提供给我一个你的环境，我这边下载好先发给你用着
> 
> 好的，谢谢。
> 我会在2个环境使用
> 
> 1. linux pc 平台  ubuntu 18.04.4   cpu:I3-8100  无显卡  opencv4.4
>    2.NVIDIA Jetson-Nano  用的nvidia自己的镜像 opencv4.2
>    邮箱：[mmwu163@163.com](mailto:mmwu163@163.com)
>    如果你们有可以开放的快速下载方式，可以直接给我，我自己下载也行，谢谢！

您好，请问您在Nano上部署的时候使用的CPU还是GPU？我在TX2上使用PaddleOCR并试图使用GPU时遇到错误：
```
terminate called after throwing an instance of 'thrust::system::system_error'
 what(): parallel_for failed: too many resources requested for launch
Aborted (core dumped)
```
不知道您是否遇到过这个问题，谢谢

**Comment by wumeng2** [comment]
> > > 你可以先提供给我一个你的环境，我这边下载好先发给你用着
> > 
> > 
> > 好的，谢谢。
> > 我会在2个环境使用
> > 
> > 1. linux pc 平台  ubuntu 18.04.4   cpu:I3-8100  无显卡  opencv4.4
> >    2.NVIDIA Jetson-Nano  用的nvidia自己的镜像 opencv4.2
> >    邮箱：[mmwu163@163.com](mailto:mmwu163@163.com)
> >    如果你们有可以开放的快速下载方式，可以直接给我，我自己下载也行，谢谢！
> 
> 您好，请问您在Nano上部署的时候使用的CPU还是GPU？我在TX2上使用PaddleOCR并试图使用GPU时遇到错误：
> 
> ```
> terminate called after throwing an instance of 'thrust::system::system_error'
>  what(): parallel_for failed: too many resources requested for launch
> Aborted (core dumped)
> ```
> 
> 不知道您是否遇到过这个问题，谢谢

我现在才准备往nano 上移植，你是自己在tx2上编译的还是下载官方的预测库？这个问题你已经解决了吧。

>

**Comment by BruceXSK** [comment]
> > > > 你可以先提供给我一个你的环境，我这边下载好先发给你用着
> > > 
> > > 
> > > 好的，谢谢。
> > > 我会在2个环境使用
> > > 
> > > 1. linux pc 平台  ubuntu 18.04.4   cpu:I3-8100  无显卡  opencv4.4
> > >    2.NVIDIA Jetson-Nano  用的nvidia自己的镜像 opencv4.2
> > >    邮箱：[mmwu163@163.com](mailto:mmwu163@163.com)
> > >    如果你们有可以开放的快速下载方式，可以直接给我，我自己下载也行，谢谢！
> > 
> > 
> > 您好，请问您在Nano上部署的时候使用的CPU还是GPU？我在TX2上使用PaddleOCR并试图使用GPU时遇到错误：
> > ```
> > terminate called after throwing an instance of 'thrust::system::system_error'
> >  what(): parallel_for failed: too many resources requested for launch
> > Aborted (core dumped)
> > ```
> > 
> > 
> > 不知道您是否遇到过这个问题，谢谢
> 
> 我现在才准备往nano 上移植，你是自己在tx2上编译的还是下载官方的预测库？这个问题你已经解决了吧。
> 
> >

是的已经解决了，当时我编译的时候官方还没有修复这个问题。前天paddle代码更新了，这个问题修复了，从源码编译就可以
