### ISSUE TITLE
在PP-OCRv2中，det训练的过程中，Teacher model 的 freeze_params 设置为 true，但是训练中间测试发现 teacher model的准确率会变

### ISSUE THREAD

**Issue by jwmneu** [PaddlePaddle/PaddleOCR#4392]
在PP-OCRv2中，det训练的过程中，Teacher model 的 freeze_params 设置为 true，但是训练中间测试发现 teacher model的准确率会变，大概1%上下浮动。

https://github.com/PaddlePaddle/PaddleOCR/blob/507129207b854b333d575839b8ce4cfa296a1411/configs/det/ch_PP-OCRv2/ch_PP-OCR_det_cml.yml#L23

**Comment by WenmuZhou** [comment]
浮动是正常的，有一些bn层会根据训练数据变化
