### ISSUE TITLE
paddle_to_pandas

### ISSUE THREAD

**Issue by taner45** [PaddlePaddle/PaddleOCR#4399]
How to covert paddle-ocr result pandas dataframe. without '\n' rows... I couldn't:(((( 
can you show an example.
thanks in advance.

**Comment by WenmuZhou** [comment]
you can use pandas.DataFrame.from_dict()，More information can be found in this document https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html

**Comment by being-invincible** [comment]
# Empty Dictionary
output_dict = dict()
# Iterating through the results from Paddle OCR
for idx in range(len(result)):
    i=0
    res = result[idx]
    for line in res:
        # Unpacking each line
        bbox = line[0]
        preds, score = line[1]
        # Adding each new dictionary with an iterator key
        output_dict[i] = {'Bbox':bbox, 'Score':score, 'Text':preds}
        i+=1

# Converting the dictionary to a dataframe
import pandas as pd
# Transposing the df so we get all the records respective to the iterator key
result_df = pd.DataFrame(output_dict).T

This will provide the desired output as follows
	Bbox	Score	Text
0	[[478.0, 162.0], [568.0, 167.0], [567.0, 186.0...	0.959098	TAX INVOICE
1	[[358.0, 181.0], [682.0, 189.0], [681.0, 207.0...	0.920168	Section 31 of CGST Act 2017 and Rule 46of the ...
2	[[859.0, 177.0], [919.0, 177.0], [919.0, 196.0...	0.95029	Original
3	[[119.0, 196.0], [520.0, 208.0], [519.0, 231.0...	0.872651	IRN:e61b3193d8f2bf73b02cf0a60847df2002392f92bc...
4	[[120.0, 217.0], [482.0, 227.0], [481.0, 250.0...	0.930629	Ack No.& Date:162313661420470 3/28/2023 3:55:00PM
...	...	...	...
93	[[136.0, 1087.0], [295.0, 1084.0], [295.0, 109...	0.860352	Subject to Mumbai Jurisdiction
94	[[566.0, 1148.0], [615.0, 1148.0], [615.0, 116...	0.844549	Page 1of
95	[[796.0, 1145.0], [898.0, 1145.0], [898.0, 115...	0.8669	Authorised Signator
96	[[137.0, 1160.0], [223.0, 1157.0], [223.0, 117...	0.947362	PREPARED BY
97	[[272.0, 1155.0], [317.0, 1155.0], [317.0, 116...	0.946672	Hitesh/
