### ISSUE TITLE
windows部署完全没问题,linux部署后预测出现问题(CPU)

### ISSUE THREAD

**Issue by Veyronl** [PaddlePaddle/PaddleOCR#440]
![image](https://user-images.githubusercontent.com/46363468/88631110-36e01f00-d0e4-11ea-9e61-098bce856779.png)

**Comment by Veyronl** [comment]
![image](https://user-images.githubusercontent.com/46363468/88631172-537c5700-d0e4-11ea-8fc8-acb600166164.png)
之前是这个问题,
在module.py增加os.environ['KMP_DUPLICATE_LIB_OK']='True'后,重新uninstall ocr_system然后install服务
出现如题的错误

**Comment by MissPenguin** [comment]
修改module.py文件后，先直接运行module.py进行调试，方便看到报错信息，没有问题再起服务

**Comment by Veyronl** [comment]
![image](https://user-images.githubusercontent.com/46363468/88642768-7a8e5500-d0f3-11ea-8ba3-fe1b15df5de0.png)
单独跑module.py报一样的错.
Intel MKL function load error: cpu specific dynamic library is not loaded.

**Comment by coder-sun** [comment]
> ![image](https://user-images.githubusercontent.com/46363468/88642768-7a8e5500-d0f3-11ea-8ba3-fe1b15df5de0.png)
> 单独跑module.py报一样的错.
> Intel MKL function load error: cpu specific dynamic library is not loaded.

我也遇到了，没有解决

**Comment by coder-sun** [comment]
哪位大哥解决了这个问题，记得回复我一下啊，谢谢~

**Comment by coder-sun** [comment]
> 修改module.py文件后，先直接运行module.py进行调试，方便看到报错信息，没有问题再起服务

不用hubserving直接运行tools/infer/predict_system.py也会遇到intel mkl load error：cpu specific dynamic library is not load 问题

**Comment by Veyronl** [comment]
@coder-sun 问题fix了,我是思路是先debug predict_system.py,出现中止异常,即吐核.
看到很多提示os.environ['KMP_DUPLICATE_LIB_OK']='True',但是这样只是忽略了问题,没有解决掉.就跳过了真正的问题.
windows是可以的,linux有问题,我就对比了下版本差异,发现scipy差异,而paddle似乎对scipy要求比较严格,请确认一下@MissPenguin
所以只需要把scipy==1.1.0就可以predict.
hubserving重新build发布即可
我觉得百度大佬@MissPenguin,可以再requirements增加版本号,避免这样的问题

**Comment by MissPenguin** [comment]
> @coder-sun 问题fix了,我是思路是先debug predict_system.py,出现中止异常,即吐核.
> 看到很多提示os.environ['KMP_DUPLICATE_LIB_OK']='True',但是这样只是忽略了问题,没有解决掉.就跳过了真正的问题.
> windows是可以的,linux有问题,我就对比了下版本差异,发现scipy差异,而paddle似乎对scipy要求比较严格,请确认一下@MissPenguin
> 所以只需要把scipy==1.1.0就可以predict.
> hubserving重新build发布即可
> 我觉得百度大佬@MissPenguin,可以在requirements增加版本号,避免这样的问题

赞！感谢反馈，我们check下～

**Comment by coder-sun** [comment]
> @coder-sun 问题fix了,我是思路是先debug predict_system.py,出现中止异常,即吐核.
> 看到很多提示os.environ['KMP_DUPLICATE_LIB_OK']='True',但是这样只是忽略了问题,没有解决掉.就跳过了真正的问题.
> windows是可以的,linux有问题,我就对比了下版本差异,发现scipy差异,而paddle似乎对scipy要求比较严格,请确认一下@MissPenguin
> 所以只需要把scipy==1.1.0就可以predict.
> hubserving重新build发布即可
> 我觉得百度大佬@MissPenguin,可以在requirements增加版本号,避免这样的问题

我把scipy换成了1.1.0，还是同样的错误，可以看下你其他包的版本号吗？

**Comment by coder-sun** [comment]
> > @coder-sun 问题fix了,我是思路是先debug predict_system.py,出现中止异常,即吐核.
> > 看到很多提示os.environ['KMP_DUPLICATE_LIB_OK']='True',但是这样只是忽略了问题,没有解决掉.就跳过了真正的问题.
> > windows是可以的,linux有问题,我就对比了下版本差异,发现scipy差异,而paddle似乎对scipy要求比较严格,请确认一下@MissPenguin
> > 所以只需要把scipy==1.1.0就可以predict.
> > hubserving重新build发布即可
> > 我觉得百度大佬@MissPenguin,可以在requirements增加版本号,避免这样的问题
> 
> 赞！感谢反馈，我们check下～

那个问题我还是没有解决，请问你们可以增加一份requirements吗，包含具体版本号的，感谢~

**Comment by Veyronl** [comment]
paddlepaddle==1.8.3
scipy==1.1.0
paddlehub==1.7.1
numpy==1.19.1可用

**Comment by coder-sun** [comment]
> paddlepaddle==1.8.3
> scipy==1.1.0
> paddlehub==1.7.1
> numpy==1.19.1可用

感谢，可以了，我之前numpy==1.18.1，要改成1.19.1才行！！

**Comment by Veyronl** [comment]
请尽情给我点赞!
您好,百度有没有算法岗位:NLP方向@MissPenguin

**Comment by coder-sun** [comment]
> 请尽情给我点赞!
> 您好,百度有没有算法岗位:NLP方向@MissPenguinzz
老哥稳，你是只考虑北京吗，杭州某国企正招算法，钱虽然不多，但是朝九晚六，自由时间多。。。

**Comment by Veyronl** [comment]
嗯,目前只考虑北京

**Comment by MissPenguin** [comment]
> 请尽情给我点赞!
> 您好,百度有没有算法岗位:NLP方向@MissPenguin

对NLP方向的岗位不太熟哈，有兴趣可以在百度招聘官网（https://talent.baidu.com/external/baidu/index.html）查找相关职位并投递简历哦～

**Comment by MissPenguin** [comment]
> 请尽情给我点赞!
> 您好,百度有没有算法岗位:NLP方向@MissPenguin

对NLP方向的岗位不太熟哈，有兴趣可以在百度招聘官网（ https://talent.baidu.com/external/baidu/index.html ）查找相关职位并投递简历哦～

**Comment by boris-lb** [comment]
> > paddlepaddle==1.8.3
> > scipy==1.1.0
> > paddlehub==1.7.1
> > numpy==1.19.1可用
> 
> 感谢，可以了，我之前numpy==1.18.1，要改成1.19.1才行！！

大佬，麻烦问一下我的配置改成你们说的版本了，还是报Intel MKL function load error: cpu specific dynamic library is not loaded.错误，我用的虚拟机装的Ubuntu18.04，没有GPU，用的CPU版的，运行代码python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
有解决方法的麻烦说一下。

**Comment by boris-lb** [comment]
> > > paddlepaddle==1.8.3
> > > scipy==1.1.0
> > > paddlehub==1.7.1
> > > numpy==1.19.1可用
> > 
> > 
> > 感谢，可以了，我之前numpy==1.18.1，要改成1.19.1才行！！
> 
> 大佬，麻烦问一下我的配置改成你们说的版本了，还是报Intel MKL function load error: cpu specific dynamic library is not loaded.错误，我用的虚拟机装的Ubuntu18.04，没有GPU，用的CPU版的，运行代码python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/" --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False
> 有解决方法的麻烦说一下。

解决了，我连续试了多个scipy版本，1.3.0版本的可以，需要的朋友可借鉴换一下不同的版本试试。

**Comment by TankAbraham** [comment]
请问一下，为什么我们不通过安装 Intel Math Kernel Library 库的方式，来从根本上解决问题？

**Comment by Jitesh4389** [comment]
conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service
It should fix your problem.

**Comment by techkang** [comment]
scipy==1.6.0 and numpy ==1.19.1 also works, but numpy==1.19.2 doesn't work.

**Comment by jeffzhengye** [comment]
> @coder-sun 问题fix了,我是思路是先debug predict_system.py,出现中止异常,即吐核.
> 看到很多提示os.environ['KMP_DUPLICATE_LIB_OK']='True',但是这样只是忽略了问题,没有解决掉.就跳过了真正的问题.
> windows是可以的,linux有问题,我就对比了下版本差异,发现scipy差异,而paddle似乎对scipy要求比较严格,请确认一下@MissPenguin
> 所以只需要把scipy==1.1.0就可以predict.
> hubserving重新build发布即可
> 我觉得百度大佬@MissPenguin,可以在requirements增加版本号,避免这样的问题

连个环境都靠猜，真想不明白。用tf出错基本是可以自己debug或看log信息解决
