### ISSUE TITLE
请问如何create一个可以识别多重语言的ocr model？

### ISSUE THREAD

**Issue by mingjun1120** [PaddlePaddle/PaddleOCR#4400]
列如：
我想要我的 **ocr_model** 能够抓取图片中的所有**英语**（Abbreviation: **en**）与**马来语** （Abbreviation: **ms**）的文字， 我应该怎么编写一下的程序？ `PaddleOCR`里的`lang` parameter 应该怎么写？

`ocr_model = PaddleOCR(use_angle_cls = True, lang='')`

备注：这两种语言都是拉丁文裔的，都是由字母A-Z组成的语言。

**Comment by Evezerest** [comment]
是的

**Comment by GUOhm230** [comment]
> 这种可能得分别加载2个预训练模型，分别预测，再做预测结果的融合了

我看用到的都是一个backbone。可以把字典合二为一，数据整合起来。直接训练一个嘛？毕竟计算机并不知道语种，只认识符号
