### ISSUE TITLE
C#部署

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4403]
![image](https://user-images.githubusercontent.com/87969070/138199937-6ff24860-dfd5-412c-a1a7-5803bf01a19f.png)
![image](https://user-images.githubusercontent.com/87969070/138199979-d4114866-af4c-4d62-b823-b7577e4bcaf3.png)
同样的inference文件，C#部署之后输出的结果不一样，这种问题一般出在哪？

**Comment by littletomatodonkey** [comment]
可能得看下预处理是否完全一致

**Comment by 18362890185** [comment]
> 可能得看下预处理是否完全一致

你好，我重新在一个新的paddleOCR版本下训练，没有做任何修改，还是会出现不一致的现象。

**Comment by zzwwr** [comment]
请问您C#调用的dll是如何生成的？？？？？虚心求教
