### ISSUE TITLE
PPOCRLabel标注工具如何替换检测、识别、方向模型？

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#4407]
PPOCRLabel.py文件中创建了self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=gpu, lang=lang)，但是没有暴露自定义模型参数，无法更换相关的检测、识别的模型，只会自动链接网络下载设置的模型，如何能够将模型修改为--det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer" --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer" 这样。

**Comment by XINMIAOZ** [comment]
请问有大佬解决这个问题了吗
