### ISSUE TITLE
Char bboxes

### ISSUE THREAD

**Issue by ku-bo** [PaddlePaddle/PaddleOCR#4412]
Hi, I want to use PaddleOCR but it will be really helpfull if I have character bboxes. 
How do I get them or where to search in the code? Thanks!

**Comment by littletomatodonkey** [comment]
CRNN is used in PaddleOCR, so you can approximately split the words, of course you can also label some character detection boxes and retrain the detection model.

**Comment by tengerye** [comment]
> CRNN is used in PaddleOCR, so you can approximately split the words, of course you can also label some character detection boxes and retrain the detection model.

Hi, thank you for your kind reply. If possible, would you please explain how to "approximately split the words" in detail?
