### ISSUE TITLE
模型转换失败

### ISSUE THREAD

**Issue by superdu12138** [PaddlePaddle/PaddleOCR#442]
我自己训练的pytorch，转换成onnx模型，再使用X2Paddle工具转换成Paddle的模型（非combined），输入如下命令，测试paddle-lite是否支持模型：
./opt --print_model_ops=true --model_dir=pd_model/inference_model --valid_targets=arm
![image](https://user-images.githubusercontent.com/20619835/88744321-92a8b780-d179-11ea-800a-90f399f67c77.png)

显示是支持的，继续输入命令：
./opt --model_dir=./pd_model/inference_model --optimize_out_type=naive_buffer --optimize_out=model --valid_targets=arm
就报了下面这个错
![image](https://user-images.githubusercontent.com/20619835/88744342-9fc5a680-d179-11ea-8a8b-468450396771.png)

请问，要怎么解决？

**Comment by littletomatodonkey** [comment]
你好，可以先用Paddle测试下是否转换成功（可以正常加载模型），x2paddle转换的问题可以在这里提issue~：https://github.com/PaddlePaddle/X2Paddle/issues

**Comment by superdu12138** [comment]
> 你好，可以先用Paddle测试下是否转换成功（可以正常加载模型），x2paddle转换的问题可以在这里提issue~：https://github.com/PaddlePaddle/X2Paddle/issues

你好，我测试过了转换后的paddle模型是可以正常加载的，就是要优化转换成paddle lite时报了上面那个错误。

**Comment by superdu12138** [comment]
我直接转换用Paddle框架训练的模型，报了这个错误，又是什么情况
![image](https://user-images.githubusercontent.com/20619835/88989574-87d35b80-d30e-11ea-85ab-23737a054dad.png)
