### ISSUE TITLE
raise Exception("not found any img file in {}".format(img_file))

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4422]
这个图片老是报异常，帮忙用predict_system跑一下，是否OK
![009](https://user-images.githubusercontent.com/66725845/138420235-0e79a836-2d5b-424c-b810-9153164a57f3.jpeg)

**Comment by xin1347764176** [comment]
i change the recourse code and it work, i change 
PATH:  tools\infer\utility.py    line50:  parser.add_argument("--image_dir", type=str) 
TO :     parser.add_argument("--image_dir", type=str, default="./doc/imgs/")
