### ISSUE TITLE
No module named 'tools.infer'

### ISSUE THREAD

**Issue by hhloverr** [PaddlePaddle/PaddleOCR#443]
在win10下，运行tools/infer/predict_system.py，No module name 'tools.infer'

**Comment by hhloverr** [comment]
在解释器里可以正常导入该模块，但是使用命令行，说什么也无法运行

**Comment by liuwenfu1218** [comment]
请问问题解决了吗 遇到了相同问题

**Comment by helindemeng** [comment]
运行的工作目录是不是不一致？
