### ISSUE TITLE
检测 出来的区域长度过短 如何变长

### ISSUE THREAD

**Issue by xxllp** [PaddlePaddle/PaddleOCR#444]
使用了官方提供的中文检测模型 cn_det_mv3_db 预测 发现在大段文本区域 检测时候 一行都会分成很多小段的。
这个是需要重新训练呢 还是设置啥参数。。多谢

**Comment by xxllp** [comment]
![Uploading det_res_1.png…](如图)

**Comment by LDOUBLEV** [comment]
tong yon通用轻量模型目前是存在分段检测的情况，可以试试大模型的效果，
![image](https://user-images.githubusercontent.com/26592129/88887234-95390900-d26e-11ea-8e5b-c59e3285ced5.png)

如果你的场景全是大段文本检测识别，可以在你的数据上用我们模型fine-tune训练试试
