### ISSUE TITLE
并发与GPU不可以同时使用？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#4443]
您好，在使用Paddlehub进行部署时发现 ”use_gpu不可与use_multiprocess同时为true“，测试之后同时设置为true确实报错，那GPU与并发只能二选一，这样也太浪费资源了吧，请问有什么解决方法吗

**Comment by MissPenguin** [comment]
这个是paddlehub的机制，可以到paddlehub官网提个issue：https://github.com/PaddlePaddle/PaddleHub

**Comment by dhl961123** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/111261871/b7ac178f-4326-4c89-92e5-a90a52ea0f39)
