### ISSUE TITLE
关于文字识别训练的tricks的问题

### ISSUE THREAD

**Issue by whuhangzhang** [PaddlePaddle/PaddleOCR#445]
#### 在中文识别模型训练时，并不是采用直接将训练样本缩放到[3,32,320]进行训练，而是先等比例缩放图像，保证图像高度为32，宽度不足320的部分补0，宽高比大于10的样本直接丢弃。

- @dyning @ZeyuChen 想请教为何“宽高比大于10的样本直接丢弃”，对比原始CRNN论文的大于10的直接resize为32*320，这样做的优点是什么？

![image](https://user-images.githubusercontent.com/53819630/88750688-a7d91280-d188-11ea-85ff-314b38d359e2.png)

**Comment by dyning** [comment]
主要是防止图像变形太厉害。如果输入文本很长，可以根据实际场景调整输入大小。

**Comment by whuhangzhang** [comment]
> 主要是防止图像变形太厉害。如果输入文本很长，可以根据实际场景调整输入大小。

谢谢，但是识别器最长识别长度为25个字符，这样处理会不会导致识别器对于过长的样本的识别能力很差，求教？？

**Comment by dyning** [comment]
@whuhangzhang 识别器最长识别长度为25个字符，不会导致对于过长的样本的识别能力变差，因为预测没有这个限制。上面逻辑我们在训练中文模型时内部添加的，没有更新到repo里面。后续更新。
