### ISSUE TITLE
我在700万中英文数据集上训练SRN算法和CRNN算法（VGG骨架网络），但是SRN算法的最终字符准确率（95%）却低于CRNN的（97%））

### ISSUE THREAD

**Issue by selective-search** [PaddlePaddle/PaddleOCR#4459]
论文里面理论上不是SRN算法大大优于CRNN吗，怎么会产生如此奇怪的结果。700万数据均是平直的文本，无需进行弯曲文本纠偏。不仅SRN算法如此，在不需要进行弯曲文本纠偏的中英文数据集上，DAN算法（Decoupled Attention Network for Text Recognition）的最终字符准确率也低于CRNN算法，这到底是为什么啊，我都快疯了。
PS：在全英文的数据集（30万，文字无弯曲）上，CRNN、SRN和DAN算法的表现都差不多。所有数据，除了测试数据为人工标注，训练数据和验证数据均为虚拟生成的。

**Comment by springsprite** [comment]
同学你好，感谢你提供的bad case的分析。 请问，你用的是论文中transformer unit的encoder，还是rnn的encoder？

**Comment by selective-search** [comment]
您好，我使用的是transformer unit的encoder，所有的网络模块我都调试检查过了，和论文里面的设置保持的一摸一样的。

**Comment by selective-search** [comment]
对了，我把论文里面的文本图像纠正模块给禁了，这点我在前面的评论提到过。

**Comment by springsprite** [comment]
同学，您分别提供下srn和crnn的training loss，training acc吧。

**Comment by selective-search** [comment]
[crnn_v3_1_1_0901.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7471995/crnn_v3_1_1_0901.txt)
[srn_main_v4_2021_1013.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7471997/srn_main_v4_2021_1013.txt)

**Comment by selective-search** [comment]
给你训练过程了，足够详细吧

**Comment by ZhangChaoZhong** [comment]
> 我的算法没有加高阶语义模块。 我分析了下badcase，我为了公平，剔除了所有大于512长度的图片（因为所有训练集也是512长度的），badcase共计830个，其中大于10个字符的badcase有262个，小于4个字符的有150个。不存在是长句子的问题。好多字符，如空格字符、“●”字符，“°”字符，“/”字符等特殊字符识别的较差。数字对齐尤其有大问题。问题总结如下： 1）数字中的字符对不齐 如下图中，第一行为原图，第二行为冒号“：”的注意力图，第三行为预测字符，可以看到算法把冒号预测漏了，第四行为groundtruth ![image](https://user-images.githubusercontent.com/49093320/139373306-a35491ff-aac4-463f-ade7-93451c0da6a6.png) ![image](https://user-images.githubusercontent.com/49093320/139373692-71ccfd88-5336-42c7-b338-4957b8004ef0.png)
> 
> 2）喜欢把0识别为O 如下图： ![image](https://user-images.githubusercontent.com/49093320/139373531-e4726935-3183-4f49-9df7-33cc2cc77785.png) 3）空格居然能识别出冒号出来： ![image](https://user-images.githubusercontent.com/49093320/139373616-80f78390-167e-482f-834b-56003a9339c0.png) 4）把一个字符识别为2个相同的字符 ![image](https://user-images.githubusercontent.com/49093320/139373899-1258b755-c603-4c29-b76e-03dfa844ec5e.png) 5) ""都是别不对 ![image](https://user-images.githubusercontent.com/49093320/139373938-c51a14cb-f394-41fd-9ddd-2706eaba4861.png) 6）逗号居然能识别成“}” ![image](https://user-images.githubusercontent.com/49093320/139374027-dd5d487d-255d-4f3a-8cfe-f70b17dacff5.png) 救命啊，我要死了。我导师要锤死我了。
您好，您的注意力图是怎么画出来的？

**Comment by selective-search** [comment]
> 您好，您的注意力图是怎么画出来的？
pvam_feature = attention_weight *word_feature,这个公式存在于PVAM模块，
公式中的attention_weight就是注意力图，形状为40*N，40为最大字符解码数，N为特征长度，SRN代码默认用的一维注意力图，因此注意力图是一维的。

**Comment by HenrySZP** [comment]
你好，请问一下您的字符准确率是按编辑距离算的吗，还是按行算的呢？

**Comment by selective-search** [comment]
> 你好，请问一下你的识别准确率是按编辑距离的吗，还是按行算的呢？

字符准确率，当然是用编辑距离算出来的呀

**Comment by zeng-cy** [comment]
字符准确率是预测对字数除以预测文字总数算的准确率吗？不是按行算把？错一个字就算这行错，在除以总的行数算出来的结果

**Comment by zeng-cy** [comment]
字符准确率是预测对字数除以预测文字总数算的准确率吗？不是按行算把，错一个字就算这行错，再除以总的行数算出来的结果？

**Comment by zeng-cy** [comment]
> [crnn_v3_1_1_0901.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7471995/crnn_v3_1_1_0901.txt) [srn_main_v4_2021_1013.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7471997/srn_main_v4_2021_1013.txt)
你使用的代码是ppocr吗
