### ISSUE TITLE
cpp 调用模型为model和params模型，我看只有db_crnn_server和db_crnn_mobile里面为此模型，其他模型怎么使用C++调用？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#446]
cpp 调用模型为model和params模型，我看只有db_crnn_server和db_crnn_mobile里面为此模型，其他模型均为.pdmodel、.pdopt和.pdparams后缀模型，要想调用其他的Text Recognition Algorithm和Text Detection Algorithm的算法模型如何调用？

**Comment by littletomatodonkey** [comment]
你好，可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md

将训练得到的.pdparams等模型文件转为model与params文件，再基于预测引擎去预测。
