### ISSUE TITLE
有关PGNet中visualDL的问题

### ISSUE THREAD

**Issue by Jack-lam1** [PaddlePaddle/PaddleOCR#4465]
在PGNet训练时，想查看可视化的训练参数结果。已经在配置文件中设置visualDL为True，也生成了.log的文件，但是当在网页打开的时候，显示说“无可视化结果”，看了提示的几个原因，都排查了，发现都是设置好的。所以想问这是什么情况呀？

**Comment by zhangyingying520** [comment]
> 可以具体描述下你的使用方式吗，生成log后进行可视化的具体步骤，方便定位问题。最好再贴一下报错的完整截图

这个可视化，可以可视化训练完生成的train.log吗，还是必须训练过程中
