### ISSUE TITLE
docker部署gpu上速度很慢

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#4469]
在GPU上使用docker部署时，部署成功后发现没有使用gpu，使用的是cpu。观察gpu的Dockerfile中CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]，hub serving start -m ocr_system"应该是CPU的启动方式，GPU启动服务应该使用 配置文件启动 hub serving start -c config.json 吧，是不是这个原因没有使用gpu呢，望解答

**Comment by pennpeng** [comment]
@Lie-huo 我用官方的dockerfile创建的镜像报错，您能把使用gpu的dockerfile共享下吗？谢谢
