### ISSUE TITLE
C++加载db_crnn_mobile和db_crnn_server模型，识别7段数字管的数字识别支持不太好

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#447]
![ocr_20](https://user-images.githubusercontent.com/40679769/88780299-5dbe5400-d1bd-11ea-93e6-4686bd4434be.jpg)
![ocr_21](https://user-images.githubusercontent.com/40679769/88780311-6151db00-d1bd-11ea-848c-55c73d8791b9.jpg)
![ocr_22](https://user-images.githubusercontent.com/40679769/88780313-61ea7180-d1bd-11ea-93fa-b7f550e03a4a.jpg)
![ocr_23](https://user-images.githubusercontent.com/40679769/88780316-631b9e80-d1bd-11ea-9736-ad6c0563d8f3.jpg)
![ocr_24](https://user-images.githubusercontent.com/40679769/88780321-657df880-d1bd-11ea-8217-b220744871c5.jpg)
![ocr_25](https://user-images.githubusercontent.com/40679769/88780325-66168f00-d1bd-11ea-8194-59396ca1d94e.jpg)
这种数字，都没法识别，识别错乱。

**Comment by littletomatodonkey** [comment]
嗯嗯感谢你的反馈，这种是因为之前的训练集中大部分为中文，单个文字的长宽比接近1，而缺少这种长宽比较大的训练样本，我们在下一版的模型迭代中会提升对这类图片的识别处理效果~

**Comment by alex152738** [comment]
请问使用通用中文模型识别面板的数字检测和识别效果都不好，和楼主类似。请问制作数据集重训练效果会好吗，有什么建议吗？谢谢。
