### ISSUE TITLE
检测配置文件

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4473]
![image](https://user-images.githubusercontent.com/87969070/139177807-86e82c90-6dee-4406-8adb-1bfb76e8f4c3.png)
请问这个参数有什么具体的设置规则，我在串联的时候将predice_det.py文件中的参数设置为该值的时候，预测时间增加了很多。

**Comment by LDOUBLEV** [comment]
图像size增大会导致模型计算量增加，进而导致预测时间增多
建议设置合理的数值范围，并且图像宽高设置32的整数倍
