### ISSUE TITLE
layout analysis failed on scanned  image 

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#4475]
Hi 

I was tested Table detection and layout analysis of scanned images but it was failed to identify the table class it will consider image class only

**Comment by Essence9999** [comment]
> Can you upload the image and command you use for layout analysis?

大佬，对于分辨率小于736，但图片清晰，没有方法放大图片便于模型识别（测试，经等比放大后的图片能被识别），需要修改哪些预处理部分？就是resize输入图片到相应的大小。谢谢

**Comment by Jitesh4389** [comment]
the scanned image has 300dpi color and table lines ink is also proper
![Uploading Binder1_page-0001.jpg…]()

**Comment by Jitesh4389** [comment]
![Binder1_page-0001](https://user-images.githubusercontent.com/74894949/139792798-e9be2b95-de32-4daa-a847-f5003b46d3a0.jpg)
