### ISSUE TITLE
How to apply inference model on Test image?

### ISSUE THREAD

**Issue by shraddha291996** [PaddlePaddle/PaddleOCR#4479]
Hello,
I have trained the model (PGNet) with a handwritten dataset and exported my trained (inference)model. I want to apply the inference model to the test image, when I am applying the inference model on test image my kernel is getting stuck. 
I am using the following code:

from paddleocr import PaddleOCR, draw_ocr # main OCR dependencies
from matplotlib import pyplot as plt # plot images
import cv2 #opencv
import os # folder directory navigation
det_path =("D:/paddle/PaddleOCR/inference/e2e")
ocr_model = PaddleOCR(lang='en',use_gpu=False,det_model_dir = det_path)
[2021/10/20 00:30:12] root WARNING: lang en is not support in PP-OCRv2, use PP-OCR instead
[2021/10/20 00:30:12] root WARNING: lang en is not support in PP-OCRv2, use PP-OCR instead
[2021/10/20 00:30:12] root WARNING: version PP-OCRv2 not support cls models, use version PP-OCR instead
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\pawar/.paddleocr/2.3.0.1\\ocr\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='D:/paddle/PaddleOCR/inference/e2e', det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='en', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='D:\\paddle\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\pawar/.paddleocr/2.3.0.1\\ocr\\rec\\en\\en_number_mobile_v2.0_rec_infer', save_log_path='./log_output/', show_log=True, table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, version='PP-OCRv2', vis_font_path='./doc/fonts/simfang.ttf', warmup=True)

img_path= ("D:/paddle/PaddleOCR/doc/imgs_en/Test1_img.JPG")
result = ocr_model.ocr(img_path)

In the last line my kernel gets stucked. Can anyone please suggest what could be the problem?
Thanks

**Comment by LDOUBLEV** [comment]
The ppocr.py is not support pgnet inference for now. Please follow this [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/pgnet.md#%E9%A2%84%E6%B5%8B%E6%8E%A8%E7%90%86) for pgnet inference.

**Comment by shraddha291996** [comment]
Thank you for your reply @LDOUBLEV. Can you please tell where can I find ppocr.py file?
