### ISSUE TITLE
hubserving这种服务化部署方式，并发支持如何？

### ISSUE THREAD

**Issue by andrewleo** [PaddlePaddle/PaddleOCR#448]
paddle效果很好，大赞！有如下两个问题想咨询下：
1、是否有测试过hubserving在各种gpu上的并发支持情况哈？能否告知？
2、另外多gpu如何同时利用起来，export CUDA_VISIBLE_DEVICES=0,1 方式吗？

**Comment by MissPenguin** [comment]
感谢使用和肯定～😊关于这两个问题：
1. 目前尚未压测，这部分的评估数据后续会补上，你可以先自己压压看
2. hubserving的部署方式目前暂不支持多卡预测，除非手动启动多个serving，不同端口对应不同卡。或者可以使用paddleserving进行部署，部署工具已经发布：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving ，在启动服务时--gpu_id 0,1 这样就可以

**Comment by andrewleo** [comment]
666，我来试试

**Comment by andrewleo** [comment]
再咨询下，生产环境用pdserving，是否合适？

**Comment by MissPenguin** [comment]
> 再咨询下，生产环境用pdserving，是否合适？

合适的，只不过上面提供的部署工具还是beta版，还没完整测试，使用可能会碰到一些问题，有问题可以随时反馈，我们一起解决～

**Comment by andrewleo** [comment]
get, try try
