### ISSUE TITLE
如何通过已有的官方模型增加自己的训练数据

### ISSUE THREAD

**Issue by qq276251547** [PaddlePaddle/PaddleOCR#4483]
当前有特定的环境需要做OCR的检测识别，有少量文字字体未被超轻量的模型所识别出来，但中文字典是包含了这些文字的，我对这部分特殊的数据做了一些数据提取（大约300-400张），用ppocrlabel做了数据处理，然后基于超轻量中英文的官方模型做了数据训练，但是为什么识别的效果依旧不好，甚至只能较好的识别训练用的那些crop的图，而其他原本能识别的反而识别不了了，文本检测也不太正确（就像只记得新训练的数据，但旧的数据遗忘了的感觉），请教一下正确的是应该怎么一个训练的流程呢？

我所使用的训练模型是：ch_ppocr_mobile_v2.0_det_train.tar
配置文件在config文件夹内的ch模板下拷贝了一份修改的，将上面的训练模型设为pretrained_model
其他所需的数据均使用的PPOCRLable生成的数据，测试数据与训练数据偷懒使用的是同一份

**Comment by Essence9999** [comment]
> > 但是为什么识别的效果依旧不好，甚至只能较好的识别训练用的那些crop的图，
> 
> finetune用的数据太少了，过拟合
> 
> 如果你没有那么多数据，可以把网络的大部分参数freeze住，只训练最后一层或者几层网络,freeze方法：
> 
> ```
> if freeze_params:
>       for param in model.parameters():
>           param.trainable = False
> ```

大佬，对于分辨率小于736，但图片清晰，没有方法放大图片便于模型识别（测试，经等比放大后的图片能被识别），需要修改哪些预处理部分？就是resize输入图片到相应的大小。谢谢

**Comment by latawangzi** [comment]
遇到同样的问题

**Comment by zhenhuamo** [comment]
我也一样，在哪里添加代码啊？

**Comment by xiaotangwan** [comment]
我也遇到同样的问题了，大佬们怎么解决的呀
