### ISSUE TITLE
CPU 运行paddle有的case报错，有的又正常

### ISSUE THREAD

**Issue by wenzhengchan** [PaddlePaddle/PaddleOCR#4485]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::operators::math::Im2ColFunctor<(paddle::operators::math::ColFormat)0, paddle::platform::CPUDeviceContext, float>::operator()(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, paddle::framework::Tensor*, paddle::framework::DataLayout)
8   paddle::framework::SignalHandle(char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1635470514 (unix time) try "date -d @1635470514" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fbf9761a040) received by PID 18380 (TID 0x7fe6dc983740) from PID 18446744071954341952 ***]

Segmentation fault (core dumped)

**Comment by tink2123** [comment]
报错的case的分辨率是多少呢？是不是非常大的图，可以试下减小图片的分辨率。

**Comment by a793719595** [comment]
![image](https://user-images.githubusercontent.com/40875698/147312509-ea055bda-f1ec-4d23-88ce-fcc324733c17.png)
![image](https://user-images.githubusercontent.com/40875698/147312534-26b3342d-3243-4781-808b-6f0996e7334d.png)
ubuntu下用cpu推理，百分之百推理完成后crash
![image](https://user-images.githubusercontent.com/40875698/147312594-43164aeb-c850-45bc-9e2a-1bca71ba7d14.png)
