### ISSUE TITLE
关于空格的疑问

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#4489]
有这样一个情况，在标注数据的时候标注了空格，但是在识别训练的时候不需要use_space_char设置为true，即不进行空格识别，想请教一下，是否需要将标注文本中的空格去掉还是直接可以进行训练

**Comment by tink2123** [comment]
模型是否支持空格识别，是由字典决定的，字典里包含空格字符就可以支持，和label的标注无关。
你这里不需要把标注中的空格去掉，直接训练即可。

**Comment by BeyondYourself** [comment]
> 模型是否支持空格识别，是由字典决定的，字典里包含空格字符就可以支持，和label的标注无关。 你这里不需要把标注中的空格去掉，直接训练即可。

@tink2123 空格不需要在字典里体现吧

**Comment by ziyaxuanyi** [comment]
你use_space_char设置为true，代码里面就是在读取的字典集合里面加入空格的，use_space_char设置为False，则代码里面不会在字典中加入空格。不需要在字典文件中单独加入空格。当然如果你在字典文件中加入了空格，又设置use_space_char为true，那么最终代码读取训练的字典集合里面就会有两个空格字符，重复了。

**Comment by BeyondYourself** [comment]
> 你use_space_char设置为true，代码里面就是在读取的字典集合里面加入空格的，use_space_char设置为False，则代码里面不会在字典中加入空格。不需要在字典文件中单独加入空格。当然如果你在字典文件中加入了空格，又设置use_space_char为true，那么最终代码读取训练的字典集合里面就会有两个空格字符，重复了。

明白了，多谢各位解答
