### ISSUE TITLE
hubserving如何停止服务

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4490]
看着教程上给的是执行
!hub serving stop --port/-p XXXX
但是服务启动后
!export CUDA_VISIBLE_DEVICES=0 &&  hub serving start -c deploy/hubserving/ocr_system/config.json 
始终运行着不能执行其他命令
麻烦问一下，如何把服务转到后台运行，不耽误执行其他命令行指令，如何停止服务

**Comment by tink2123** [comment]
可以用nohup 后台命令启动， 停止服务可以用 hub serving stop --port/-p XXXX

**Comment by zhangyingying520** [comment]
> 可以用nohup 后台命令启动， 停止服务可以用 hub serving stop --port/-p XXXX

能给一个完整nohup后台命令启动的指令吗
