### ISSUE TITLE
paddlehub serving 如何通过nohup方式挂载到后台 

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4491]
麻烦问一下，哪位大佬能将这个命令行通过nohup挂载到后台
#通过配置文件启动
!export CUDA_VISIBLE_DEVICES=0 &&  hub serving start -c deploy/hubserving/ocr_system/config.json

**Comment by tink2123** [comment]
nohup serving start -c deploy/hubserving/ocr_system/config.json & 即可

**Comment by zhangyingying520** [comment]
> nohup serving start -c deploy/hubserving/ocr_system/config.json

不需要指定GPU吗

**Comment by zhangyingying520** [comment]
> nohup serving start -c deploy/hubserving/ocr_system/config.json & 即可

![image](https://user-images.githubusercontent.com/80818728/139617737-2bef8873-b7ac-426b-869b-7d1bd567c3a1.png)
这样怎么解决

**Comment by zhangyingying520** [comment]
> nohup serving start -c deploy/hubserving/ocr_system/config.json & 即可

问题没有解决，能再帮忙看看吗。谢谢了

**Comment by zhangyingying520** [comment]
> nohup serving start -c deploy/hubserving/ocr_system/config.json & 即可

你好，看到之后能给帮忙解答一下吗

**Comment by zhangyingying520** [comment]
> nohup serving start -c deploy/hubserving/ocr_system/config.json & 即可

![image](https://user-images.githubusercontent.com/80818728/142372918-8fa67763-d127-4ec3-a691-fe80c2c9b154.png)
麻烦问一下，这样得怎么解决

**Comment by yanql** [comment]
nohup hub serving start -c /Paddle/deploy/hubserving/structure_system/config.json > work.log 2>&1 &
用这个可以
