### ISSUE TITLE
The term 'paddleocr' is not recognized

### ISSUE THREAD

**Issue by vihnng** [PaddlePaddle/PaddleOCR#4492]
Hi there, 
I have install all requirements modules and follow the tutorial to set up env and install things and press Run (using PyCharm) then it return me with "Process finished with exit code 0". 
Then I used terminal "cd my path/ppocr_img" to set to paddleOCR test images (this step is fine)
But when I type "paddleocr --image_dir ./imgs_en/img_12.jpg --use_angle_cls true --lang en --use_gpu false" it show that 

"paddleocr : The term 'paddleocr' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ paddleocr --image_dir ./imgs_en/img_12.jpg --rec
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (paddleocr:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

Sorry for asking this (i'm new to programming and never use python before). Please help me to solve this issua, thank you

**Comment by tink2123** [comment]
Have you installed the paddleocr whl package? 
```
pip install paddlepaddle
pip install "paddleocr>=2.0.6"
```

**Comment by vihnng** [comment]
thank you so much
