### ISSUE TITLE
inference模型在python端 /C++端表现不一致

### ISSUE THREAD

**Issue by MrZWJax** [PaddlePaddle/PaddleOCR#4493]
对相同的文字切片做inference，在python端通过 tools/infer/predic_rec.py 可以得到正常结果,("02/26"), 在C++端预测得到的结果错误 （“621/26”)，请问原因是什么呢？
另外想问一下，目前paddleocr2.1转换后的 inference模型文件有三个，*.pdiparams     *.pdiparams.info     *.pdmodel ，在C++预测的时候是只用*.pdiparams 和 *.pdmodel 吗

**Comment by tink2123** [comment]
python和c++端结果不一致可能是预处理不同导致的，请问您用的是哪个分支的代码呢？
.pdiparams.info 在实际预测时是不需要的。

**Comment by MrZWJax** [comment]
我这边用的是paddleOCR2.1的分支, paddlepaddle版本2.0.1，请问这个预处理大概是在哪里有区别呢，我们用的就是官方demo

**Comment by MrZWJax** [comment]
补充一下，用的是动态图训练
