### ISSUE TITLE
[Table structure] Discrepancy between training model and inference model  

### ISSUE THREAD

**Issue by cpwan** [PaddlePaddle/PaddleOCR#4497]
Hi there,

When I run the training model with the following script and print out the model outputs shape, I get (1,501,30) and (1,501,4).
`python tools/infer_table.py -c './configs/table/table_mv3.yml' -o Global="{'infer_img':'path/to/image', 'pretrained_model':'path/to/model/en_ppocr_mobile_v2.0_table_structure_train/best_accuracy'}"`

But when I run the inference model with `ppstructure.table.predict_structure.TableStructurer` and print out the model outputs shape, I get (1,801,30) and (1,801,4).

The two models gave me different structure predictions and different bounding boxes. The prediction from the training model is obviously wrong. How can I get prediction right for the training model? Thanks.

**Comment by zengchan** [comment]
我训练的loss和验证的loss相差好多，是跟有无先验信息的原因吗

**Comment by WenmuZhou** [comment]
@cpwan Thank you for your feedback, this is a bug, it has been fixed here https://github.com/PaddlePaddle/PaddleOCR/pull/4565
