### ISSUE TITLE
use the  english recognize inference then decode error

### ISSUE THREAD

**Issue by oszn** [PaddlePaddle/PaddleOCR#4498]
the error like that

`  File "tools/infer/predict_system.py", line 193, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 141, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 80, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "D:\PaddleOCR-release-2.2\tools\infer\predict_rec.py", line 261, in __call__
    rec_result = self.postprocess_op(preds)
  File "D:\PaddleOCR-release-2.2\ppocr\postprocess\rec_postprocess.py", line 116, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "D:\PaddleOCR-release-2.2\ppocr\postprocess\rec_postprocess.py", line 86, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
`

and  my command like this 
python tools/infer/predict_system.py --image_dir="./pdf/litt/2_2.png" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/en_number_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True --rec_char_dict_path="./ppocr/utils/dict/en_dict.txt" --rec_char_type="en"

can solve this?

**Comment by tink2123** [comment]
if you only want to use en model, try to:
```
python tools/infer/predict_system.py --image_dir="./pdf/litt/2_2.png" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./inference/en_number_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True --rec_char_dict_path="./ppocr/utils/dict/en_dict.txt"
```

**Comment by JimReno** [comment]
参数 --rec_char_type="en"改为 --rec_char_type="EN"。
英文的字典名称不对，rec_postpreprocess里面86行的self.character的长度和数据字典en_dict.txt对不上号。按照上面方法修改。。我乱试的，成功了。。。

**Comment by JimReno** [comment]
我感觉是数据字典的问题，看看官方的matainer怎么说把

**Comment by oszn** [comment]
> 我感觉是数据字典的问题，看看官方的matainer怎么说把

他代码逻辑会优先选择rec_char_type==‘en’如果有这个，就不会考虑字典了，所以字典被这个屏蔽了，我把这个去掉就好了，他逻辑里面是直接=='en'所以==‘EN’就走掉了那个if判断。

**Comment by tink2123** [comment]
> > 我感觉是数据字典的问题，看看官方的matainer怎么说把
> 
> 他代码逻辑会优先选择rec_char_type==‘en’如果有这个，就不会考虑字典了，所以字典被这个屏蔽了，我把这个去掉就好了，他逻辑里面是直接=='en'所以==‘EN’就走掉了那个if判断。

是这样的，最新的dygraph代码中去掉了 rec_char_type 参数，以后均通过路径选择字典，避免类似情况发生。
