### ISSUE TITLE
NRTR识别模型加载训练数据时报错“all input arrays must have the same shape”

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#4499]
![image](https://user-images.githubusercontent.com/74600923/139419733-aa1e71d5-41eb-4ca6-b68e-0118c67a99ae.png)

真的一老遇到这种问题，之前用attention识别模型的时候就碰到过，在issues里面找到了相应的解决方案，解决了。
现在用NRTR的时候又遇到这种问题，真的挺头大的，麻烦技术人员能不能把这个痛点解决了

**Comment by Topdu** [comment]
您好，该报错是dataloader在打包数据时，由于同一batch中某些数据tensor的形状不一致导致的，您可以通过下面的步骤排查出shape不一致的tensor：
修改ppocr/data/operators.py中`KeepKeys`类如下:
class KeepKeys(object):
    def __init__(self, keep_keys, **kwargs):
        self.keep_keys = keep_keys

    def __call__(self, data):
        data_list = []
        for key in self.keep_keys:
            if key == 'image' and data[key].shape != (1, 32, 100):
                print(key, data[key].shape)
            if key == 'label' and data[key].shape != (25,):
                print(key, data[key].shape)
            if key == 'length' and data[key].shape != ():
                print(key, data[key].shape)
            data_list.append(data[key])

        return data_list 
运行训练脚本，会打印出数据shape不一致的数据，如果打印出‘image’的形状不一致，需要排查您使用的resize方法是否将所有的数据resize到同一个shape，如果打印出‘label’不一致，需要排查您使用的Labelencode的方法，有没有将label的长度padding到一致。
还有一个可能性，如果您使用了默认的nrtr配置，请排查您的数据集中是否有损坏的图片或者label。
感谢您提供的issue，有问题随时沟通

**Comment by Lebron-Harden** [comment]
> 您好，该报错是dataloader在打包数据时，由于同一batch中某些数据tensor的形状不一致导致的，您可以通过下面的步骤排查出shape不一致的tensor： 1、保证您的代码是最新的： nrtr是新开发的模型，代码更新频繁，开发时遇到过同样的问题，在ppocr/data/imaug/label_ops.py的`NRTRLabelEncode`类中已修复，请您查看代码是否一致，如果一致，您可以进行2的尝试： 2、修改ppocr/data/operators.py中`KeepKeys`类如下:
> 
> ```
> class KeepKeys(object):
>     def __init__(self, keep_keys, **kwargs):
>         self.keep_keys = keep_keys
> 
>     def __call__(self, data):
>         data_list = []
>         for key in self.keep_keys:
>             if key == 'image' and data[key].shape != (1, 32, 100):
>                 print(key, data[key].shape)
>             if key == 'label' and data[key].shape != (25,):
>                 print(key, data[key].shape)
>             if key == 'length' and data[key].shape != ():
>                 print(key, data[key].shape)
>             data_list.append(data[key])
>         return data_list 
> ```
> 
> 运行训练脚本，会打印出数据shape不一致的数据，如果打印出‘image’的形状不一致，需要排查您使用的resize方法是否将所有的数据resize到同一个shape，如果打印出‘label’不一致，需要排查您使用的`LabelEncode`的方法，有没有将label的长度padding到一致。 还有一个可能性，如果您使用了默认的nrtr配置，请排查您的数据集中是否有损坏的图片或者label。 感谢您提供的issue，有问题随时沟通。

感谢，按照描述的方法排查，发现是有些label的长度超过了max_text_length，导致shape不一致，现在解决了。是我自己的问题

**Comment by fengchuibeixiang** [comment]
我也遇到了类似的问题，不过我是修改了rec_chinese_common_train_v2.0.yml里面训练时的RecResizeImg参数，从[3,32,320]改成了[3,24,70],然后就报了这个错误，没修改这个参数之前，是可以正常训练的，请问这个问题怎么排查呢

**Comment by Lebron-Harden** [comment]
> 我也遇到了类似的问题，不过我是修改了rec_chinese_common_train_v2.0.yml里面训练时的RecResizeImg参数，从[3,32,320]改成了[3,24,70],然后就报了这个错误，没修改这个参数之前，是可以正常训练的，请问这个问题怎么排查呢

可能这个size是不能修改的吧
