### ISSUE TITLE
求教，连续出现 multiprocess is not fully compatible with Windows.num_workers will be 1

### ISSUE THREAD

**Issue by elvinest** [PaddlePaddle/PaddleOCR#450]
请教大家，我在训练检测模型时连续提示
multiprocess is not fully compatible with Windows.num_workers will be 1
未打印任何训练信息

训练识别模型时一切正常。

从提示来看加载参数一切正常，config中的num_workers也设置为1了，但还是连续输出上述提示。

![det1](https://user-images.githubusercontent.com/3347361/88825458-2e7a0800-d1fa-11ea-870b-ea69a59ec107.png)

经过设定的step后模型还保存了。

![det2](https://user-images.githubusercontent.com/3347361/88825830-9892ad00-d1fa-11ea-8a0e-e8a0a2e464c2.png)

请教大家是什么原因， 谢谢!!

**Comment by littletomatodonkey** [comment]
你好，如果不希望显示的话，需要把这里注释掉，我们之后也修改下这块的逻辑(self.num_workers=1的时候，就不显示了)，感谢你的反馈
https://github.com/PaddlePaddle/PaddleOCR/blob/8f175aade77295aacb182dbf1633d73f85900eef/ppocr/data/rec/dataset_traversal.py#L237

https://github.com/PaddlePaddle/PaddleOCR/blob/8f175aade77295aacb182dbf1633d73f85900eef/ppocr/data/det/dataset_traversal.py#L47

**Comment by elvinest** [comment]
> 你好，如果不希望显示的话，需要把这里注释掉，我们之后也修改下这块的逻辑(self.num_workers=1的时候，就不显示了)，感谢你的反馈
> https://github.com/PaddlePaddle/PaddleOCR/blob/8f175aade77295aacb182dbf1633d73f85900eef/ppocr/data/rec/dataset_traversal.py#L237
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/8f175aade77295aacb182dbf1633d73f85900eef/ppocr/data/det/dataset_traversal.py#L47

但是不打印任何训练输出，并且上述信息出现速度非常快，大约每秒输出5条左右，感觉完全没有训练。

**Comment by littletomatodonkey** [comment]
如果不注释的话，每个图片处理时都会输出，相当于如果batch size为64，print interval为10的话，那么每次处理完640张图片才会输出一次训练输出，但是此时已经输出了640次`multiprocess is not xxx`信息

**Comment by elvinest** [comment]
> 如果不注释的话，每个图片处理时都会输出，相当于如果batch size为64，print interval为10的话，那么每次处理完640张图片才会输出一次训练输出，但是此时已经输出了640次`multiprocess is not xxx`信息
我调试到训练执行到这一步时就不往下继续运行了，但是没有任何异常抛出来，所以不会输出训练信息。
另外，我故意将 img_set_dir 目标写错，代码还是会继续运行，没有异常。

https://github.com/PaddlePaddle/PaddleOCR/blob/cb49dcc77be5807d176b717f3e649368bcacc905/tools/program.py#L247

**Comment by elvinest** [comment]
问题解决！谢谢!
