### ISSUE TITLE
根据电脑不同结果不同  [different results depending on the computer ?]

### ISSUE THREAD

**Issue by AriouatI** [PaddlePaddle/PaddleOCR#4500]
你好，
根据所使用的 GPU，结果会有所不同，这是预期的行为吗？
谢谢。

hello,
is it an expected behavior that depending on the gpu used, results are different ?
thanks.

**Comment by tink2123** [comment]
cuda和cudnn版本不同可能会存在预测结果有细微差别，因为很多op实现是调用的cuda代码。但应该和机器无关，如果可以统一环境，结果应该都是一致的。

**Comment by Essence9999** [comment]
> cuda和cudnn版本不同可能会存在预测结果有细微差别，因为很多op实现是调用的cuda代码。但应该和机器无关，如果可以统一环境，结果应该都是一致的。

大佬，有没有哪个参数或预处理程序，可以放大输入用来预测的图片（图片原始最大长度234，但图片较清晰），因为原始图片预测失败，放大到一定长度可识别。谢谢大佬
