### ISSUE TITLE
ValueError:too many values to unpack (expected 2)  for (outputs, hidden), alpha = self.structure_attention_cell(hidden, fea, elem_onehots)

### ISSUE THREAD

**Issue by mathTaoTao** [PaddlePaddle/PaddleOCR#4504]
请教一下，table_att_head.py里面(outputs, hidden), alpha = self.structure_attention_cell(hidden, fea, elem_onehots)，但是调用的AttentionGRUCell返回值为return cur_hidden, alpha，运行时报错ValueError:too many values to unpack (expected 2) ，请教一下，这里该如何解决呢

**Comment by WenmuZhou** [comment]
请问是什么版本的paddle，这里AttentionGRUCell返回的cur_hidden实际上是两个值，可以看看这个api文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/GRUCell_cn.html#grucell

**Comment by mathTaoTao** [comment]
paddle 2.1.1，cur_hidden确实是两个值，问题解决啦，多谢哈~
