### ISSUE TITLE
 验证安装时报错：no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by 1987zfp** [PaddlePaddle/PaddleOCR#4507]
gtx760 查到算力是 3.0 应该符合paddle的最低要求
已经安装了cuda10.2 和 cudnn7.6.5
运行验证 paddle.utils.run_check()，报错
uniform_random raises an exception class thrust::system::system_error, parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by WenmuZhou** [comment]
安装的什么版本的paddle
