### ISSUE TITLE
识别漏了，和演示站不一致

### ISSUE THREAD

**Issue by yangyitl** [PaddlePaddle/PaddleOCR#4509]
我本地识别结果和演示站识别有差异
我识别结果：
![image](https://user-images.githubusercontent.com/14830899/139539088-0c6e8d99-677e-4cf8-b8cc-28c78c56b43e.png)

演示站识别结果：
![image](https://user-images.githubusercontent.com/14830899/139539134-cf923a23-c1bc-48c6-be4f-8811d2b05c71.png)
收件人少了省市区那一块的

识别命令：
/usr/local/Cellar/python@3.8/3.8.7/bin/python3 tools/infer/predict_system.py --image_dir="/Users/yangyi/Desktop/pdf识别/dy-ems-1.jpg" --det_model_dir="./inference/ch_PP-OCRv2_det_infer/"  --rec_model_dir="./inference/ch_PP-OCRv2_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False

**Comment by WenmuZhou** [comment]
试一下只跑检测，看看能不能检测到
