### ISSUE TITLE
Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.

### ISSUE THREAD

**Issue by AndersonWuCheng** [PaddlePaddle/PaddleOCR#4511]
环境
Tenserrt 7.2.1.6,
显卡gtx1650.
windows 10 x64. C++版本
Detector,Cls都成功创建，
到CRNNRecognizer创建的时候报错误。
注释disable_glog_info()后， 显示如下：

e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [adaptive_pool2d_convert_global_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_filter_op_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [skip_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [unsqueeze2_eltwise_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m

------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at C:\home\workspace\Paddle_release5\paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

**Comment by LDOUBLEV** [comment]
显示的信息不全，报错信息里应该提示了某些参数的动态shape没有设置，按照这个格式就行，
https://github.com/PaddlePaddle/PaddleOCR/blob/4cbb0ee86f16afe86991ec1805a5ca3717e6f021/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L175

如果你不需要用动态shape，这一行屏蔽掉

**Comment by AndersonWuCheng** [comment]
谢谢。如果不需要动态shape,屏蔽掉哪一行？config.SetTRTDynamicShapeInfo() 这个么？
