### ISSUE TITLE
fine-tune识别模型，一张训练图片内有多行文本，应该怎么准备数据集

### ISSUE THREAD

**Issue by Wangjh0125** [PaddlePaddle/PaddleOCR#4513]
我用ppocr的预训练模型训练自己的识别数据集，一张图片不止1行文本，我看教程里的识别数据集都是1张图片1个文本，所以想问一下应该怎么准备多文本的识别数据集的rec_gt_train.txt呢？ 我现在准备的数据集格式是这个样子的：
![image](https://user-images.githubusercontent.com/80049307/139613428-22ac7a25-edc1-40aa-a5ce-53fdebeda8a2.png)

**Comment by MissPenguin** [comment]
识别模型的训练数据，每张图只有一行文字，可以看下文档中的示例：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md

如果你的图片有多行文字，需要把每行切出来，重新组织训练数据

**Comment by Wangjh0125** [comment]
> 识别模型的训练数据，每张图只有一行文字，可以看下文档中的示例：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md
> 
> 如果你的图片有多行文字，需要把每行切出来，重新组织训练数据

请问每行切出来的意思就是把一张图的每一行单独挑出来，形成一张新的图片是吗

**Comment by MissPenguin** [comment]
> > 识别模型的训练数据，每张图只有一行文字，可以看下文档中的示例：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md
> > 如果你的图片有多行文字，需要把每行切出来，重新组织训练数据
> 
> 请问每行切出来的意思就是把一张图的每一行单独挑出来，形成一张新的图片是吗

是的

**Comment by Wangjh0125** [comment]
明白了，谢谢
