### ISSUE TITLE
生成带有标点符号的数据

### ISSUE THREAD

**Issue by Fenghaze** [PaddlePaddle/PaddleOCR#4516]
请问有什么方法可以生成带有标点符号的数据？

**Comment by MissPenguin** [comment]
合成识别任务的训练数据吗，用带有标点符号的语料就行

**Comment by Fenghaze** [comment]
> 合成识别任务的训练数据吗，用带有标点符号的语料就行

你好，我使用style-text合成工具，使用语料Paddle!!@*OCR；但是好像无法生成理想中的图片
![image](https://user-images.githubusercontent.com/40448037/139770948-5cf710e4-6311-4600-994f-cb14c9c2f24a.png)

**Comment by MissPenguin** [comment]
> > 合成识别任务的训练数据吗，用带有标点符号的语料就行
> 
> 你好，我使用style-text合成工具，使用语料Paddle!!@*OCR；但是好像无法生成理想中的图片 ![image](https://user-images.githubusercontent.com/40448037/139770948-5cf710e4-6311-4600-994f-cb14c9c2f24a.png)

style-text模型目前不支持这些特殊符号
