### ISSUE TITLE
背景占比大，导致银行卡检测识别；手动裁剪出单独的银行卡图片，识别成功

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4517]
自己Finetune的卡号检测模型，因为背景占比大，导致银行卡检测识别；手动裁剪出单独的银行卡图片，识别成功
剪裁前
![image](https://user-images.githubusercontent.com/66725845/139618943-b7e2f41b-0a64-4cd2-ae87-7bf0f966f3de.png)
剪裁后
![2](https://user-images.githubusercontent.com/66725845/139619444-45aca964-89dd-4128-b4db-47641819abe9.png)

有什么办法可以识别剪裁前的图片吗

**Comment by MissPenguin** [comment]
如果都是银行卡，可以训一个银行卡检测模型。也可以直接多加一些训练数据增强文本检测模型鲁棒性。

**Comment by Essence9999** [comment]
> 如果都是银行卡，可以训一个银行卡检测模型。也可以直接多加一些训练数据增强文本检测模型鲁棒性。

除了数据Finetune模型这块，有没有一些图像处理相关的方法，检测判断再放大

**Comment by MissPenguin** [comment]
> > 如果都是银行卡，可以训一个银行卡检测模型。也可以直接多加一些训练数据增强文本检测模型鲁棒性。
> 
> 除了数据Finetune模型这块，有没有一些图像处理相关的方法，检测判断再放大

没有这方面的经验，可以自己探索下哈

**Comment by Essence9999** [comment]
你的邮件，我已收到~
