### ISSUE TITLE
文字检测DB模型遇到的问题

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#4518]
在文字检测阶段使用DB模型时做文字检测，会出现以下示例情况
文本框粘连，多检测，导致
![github  db](https://user-images.githubusercontent.com/24270107/139631512-680e2e9e-df97-4c1d-83f5-9276c93620b6.png)
识别后两个文本框结果为TMPIJ和临时文件
![微信图片_20211101143302](https://user-images.githubusercontent.com/24270107/139631523-c142e1d2-7883-4eaa-92ed-a56328e9cd17.png)
两个文本框识别结果为OBJ和J目标文件
导致文本识别的结果多识别或者错识别。
有没有什么解决方式避免这种问题的出现？

**Comment by MissPenguin** [comment]
这个问题是DB算法本身的缺陷，可以试试server版模型，可能会好一点，或者通过后处理进行环节，例如根据位置关系合并文本框。

**Comment by ziyuwzf** [comment]
> 这个问题是DB算法本身的缺陷，可以试试server版模型，可能会好一点，或者通过后处理进行缓解，例如根据位置关系合并文本框。

这些就是sever版本模型出现的问题。合并文本框对于文本框偏转角度和版面大小字体的文本框合并，这两种情形不够友好吧

**Comment by MissPenguin** [comment]
是的，这种后处理只能解决部分case，是否采用需要根据实际场景决定。
