### ISSUE TITLE
能否出一个paddle serving 部署检测模型，官方给的是db算法的,用east训练的不能用

### ISSUE THREAD

**Issue by WuXinZhiMing** [PaddlePaddle/PaddleOCR#4519]
现在只有DB训练的模型能用Paddle serving部署，east训练的不行，发现在develop版本中有可以配置参数的，但是现在无法跑通

[](https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving)
![Snipaste_2021-11-01_16-50-41](https://user-images.githubusercontent.com/31824814/139646395-4d9bef07-e055-4b1e-ba32-1466c73d788a.png)

**Comment by WuXinZhiMing** [comment]
用develop无法跑通
![Snipaste_2021-11-01_16-52-34](https://user-images.githubusercontent.com/31824814/139646570-899e980f-41ce-4991-932b-45d91f3ca543.png)

**Comment by MissPenguin** [comment]
您好，pdserving目前没有支持db以外的模型，有需要可以自己修改一下代码。另外develop分支是静态图的，比较老了，已经不怎么维护，建议用最新的release分支哈。

**Comment by WuXinZhiMing** [comment]
好的，谢谢
