### ISSUE TITLE
ch_rec_r34_vd_crnn_enhance 识别模型对 O 0、I 1 这类相似的数字和字母识别效果不好

### ISSUE THREAD

**Issue by myfjdthink** [PaddlePaddle/PaddleOCR#452]
![10_FROPSO595C](https://user-images.githubusercontent.com/2044143/88877773-e50cd580-d258-11ea-9f34-6d090b864943.jpg)
识别结果是 FROPSO595C，把 0 识别成了 O

![8_ADHP18885M](https://user-images.githubusercontent.com/2044143/88877853-12f21a00-d259-11ea-9b6d-b96b63200997.jpg)
识别结果是 ADHP18885M，把 I 识别成了 1

![7_BIDPNO857N](https://user-images.githubusercontent.com/2044143/88877962-5b113c80-d259-11ea-81e8-a115ecf56015.jpg)
识别结果是 BIDPNO857N，把 0 识别成了 O

**Comment by littletomatodonkey** [comment]
你好，感谢你的反馈，这个是因为在很多场景下0和O的确长的有点像。如果可以的话，可以麻烦你反馈一些更多的bad case给我们吗？我们后续在模型迭代时重点再优化下这些目前没有处理好的一些case

**Comment by myfjdthink** [comment]
![6_AVSPTO921G](https://user-images.githubusercontent.com/2044143/88881480-1ccc4b00-d262-11ea-97a5-6f1a4832f8a3.jpg)
识别结果是  AVSPTO921G

**Comment by littletomatodonkey** [comment]
好的，谢谢！我们也随时在这里收集，想问下这个图片你是在哪些场景中遇到的呢？

**Comment by myfjdthink** [comment]
识别印度身份证  Pan Card 的时候

**Comment by ymxcywl** [comment]
请问你们优化是添加错字样本finetune吗，我用少量错字样本去训练crnn，只训练了很少的step，就影响到那些曾经识别正确的文字了

**Comment by myfjdthink** [comment]
> finetune

没有做 finetune 的，就是用官方提供的模型

**Comment by littletomatodonkey** [comment]
对于这种细微区别需要识别的问题，建议还是在自己的数据上进行finetune，可能会大大提升模型精度

**Comment by littletomatodonkey** [comment]
> 请问你们优化是添加错字样本finetune吗，我用少量错字样本去训练crnn，只训练了很少的step，就影响到那些曾经识别正确的文字了

finetune的时候要想保证之前的字识别训练没影响，也需要保证出现一定的频率
