### ISSUE TITLE
如果只要识别中文，不含字符和英文，要把字符和英文从字典文件中删除，需要重新训练吗？

### ISSUE THREAD

**Issue by pipishaw** [PaddlePaddle/PaddleOCR#4521]
如果只要识别中文，不含字符和英文，要把字符和英文从字典文件中删除，需要重新训练吗？
或者有其他的办法可以屏蔽。

**Comment by MissPenguin** [comment]
简单的做法可以直接把识别结果中的字符和英文过滤掉。如果要修改字典，那就需要重新训练。

**Comment by pipishaw** [comment]
能给个过滤的方案吗？是在后处理的时候过滤吗？是否可以在Serving现有的文件中处理？
