### ISSUE TITLE
请问SRN识别模型有预训练权重吗？

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#4523]
如题

**Comment by MissPenguin** [comment]
SRN只有英文公开数据集上的预训练模型，可以从这里下载：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/algorithm_overview.md#12-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95

**Comment by Lebron-Harden** [comment]
> SRN只有英文公开数据集上的预训练模型，可以从这里下载：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/algorithm_overview.md#12-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95

请问是否可以提供中文预训练用到的数据集呢

**Comment by MissPenguin** [comment]
> > SRN只有英文公开数据集上的预训练模型，可以从这里下载：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/algorithm_overview.md#12-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95
> 
> 请问是否可以提供中文预训练用到的数据集呢

中文预训练的数据集来自于开源数据和合成数据，暂不计划开源哈，可以自己收集和合成一批哈

**Comment by Lebron-Harden** [comment]
> > > SRN只有英文公开数据集上的预训练模型，可以从这里下载：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/algorithm_overview.md#12-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95
> > 
> > 
> > 请问是否可以提供中文预训练用到的数据集呢
> 
> 中文预训练的数据集来自于开源数据和合成数据，暂不计划开源哈，可以自己收集和合成一批哈

主要是用提供的预训练模型训练的效果比较好，但是预训练的模型只有那几个，我想用别的backbone训练，但是没有经过预训练，效果比较差
