### ISSUE TITLE
Android部署

### ISSUE THREAD

**Issue by YinZhang98** [PaddlePaddle/PaddleOCR#4524]
我想请教一下，使用里面的android_demo，如何优化使其可以通过opencl加速使用呢？

**Comment by LDOUBLEV** [comment]
在PaddleLite repo下提问吧 https://github.com/PaddlePaddle/Paddle-Lite/issues

**Comment by guoge6** [comment]
YinZhang98,安卓的那个demo可以请教您吗？刚刚接触，代码看不懂
