### ISSUE TITLE
转成 inference 之后 会 全部识别错

### ISSUE THREAD

**Issue by liweizhong666** [PaddlePaddle/PaddleOCR#4525]
为什么转成 inference 之后 会 全部识别错， 英文识别成中文，但预测的时候是完全正确的？

**Comment by LDOUBLEV** [comment]
inference的时候换字典了吗？https://github.com/PaddlePaddle/PaddleOCR/blob/4cbb0ee86f16afe86991ec1805a5ca3717e6f021/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L76

**Comment by Gattycheng** [comment]
建议查一下字典是不是错了

**Comment by Gattycheng** [comment]
建议查一下字典是不是错了
