### ISSUE TITLE
训练时，acc明明是1，但评估时best_accuracy的效果并不好

### ISSUE THREAD

**Issue by pyni** [PaddlePaddle/PaddleOCR#4527]
大佬好，我跑的是ic15的demo,训练过程中在test数据集中的acc有1，按道理说效果应该不错，
![Screenshot from 2021-11-02 14-14-08](https://user-images.githubusercontent.com/18031767/139801479-bb064902-ce13-4604-bb81-b3c5f384a246.png)

但是评估test数据集的时候用best_accuracy的效果并不好:
![Screenshot from 2021-11-02 14-35-47](https://user-images.githubusercontent.com/18031767/139801782-2044bdbd-20ba-4700-83c1-5d9329d70a12.png)
感觉很奇怪，如果训练时候时acc有1，那预测时候按道理test数据集应该全部预测对呀，上面预测的j和t就漏了，感觉还不如预训练权值预测的效果好。

另外就是我用python3 -m paddle.distributed.launch --gpus '0' tools/eval.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints={path/to/weights}/best_accuracy去做test数据集的evaluation，acc的结果别说1了，连0.5都没有:
![Screenshot from 2021-11-02 15-23-49](https://user-images.githubusercontent.com/18031767/139803318-56df0ca1-fa5f-49fd-8868-e050a4cdfe4e.png)
不明白训练过程中acc能达到1的话，为什么测试的时候效果这么差呢？

**Comment by ZHANGH83** [comment]
我也是这样，明明训练显示的acc有0.993但是去预测val集的图片效果非常差，预测概率只有0.3多...

**Comment by LDOUBLEV** [comment]
训练的太久了，发生了过拟合

**Comment by pyni** [comment]
> 训练的太久了，发生了过拟合

请问训练中显示的acc的训练集的acc还是验证集的acc呢？

**Comment by JimReno** [comment]
大佬你好，请问一下，我也是用ic15的demo训练的，yml的配置是教程给的配置吗，72个epoch我跑出来的acc还是0，是不是需要修改yml的配置内容。
我调小了lr，增大了epoch到1000但效果还是很差，另外引入pretrained_model的模型后，会报`he shape of model params backbone.blocks.7.linear_conv.conv.weight [40, 104, 1, 1] not matched with loaded params backbone.blocks.12.linear_conv.bn._variance [80] !`这样的warning，请问是输入的img size不一样的吗

**Comment by JimReno** [comment]
> 训练的太久了，发生了过拟合

yml配置中的label_file_list: ["./train_data/ic15_data/rec_gt_test.txt"] 用的应该就是test的数据吧

**Comment by Evezerest** [comment]
> > 训练的太久了，发生了过拟合
> 
> 请问训练中显示的acc的训练集的acc还是验证集的acc呢？

上面图例标出来的acc都是训练，测试会有不一样的字段

**Comment by pyni** [comment]
OK,我这边所有问题都解决了，我总结一下：
1.不要用mobilenet V3训练，这个模型精度还是不够
2.字典要选对，否则效果真的很差，选自己的字典的话，en要变成cn
3.PaddleOCR不要用最新版，最新版的好像预训练权值读进去效果很差，用今年年初的版本就行。

**Comment by chccc1994** [comment]
> OK,我这边所有问题都解决了，我总结一下： 1.不要用mobilenet V3训练，这个模型精度还是不够 2.字典要选对，否则效果真的很差，选自己的字典的话，en要变成cn 3.PaddleOCR不要用最新版，最新版的好像预训练权值读进去效果很差，用今年年初的版本就行。

没有加载预训练模型，把mobilenet V3换成了 ResNet 101也是这个问题，**训练epoch=72 在epoch为54左右 acc 基本接近于1 ，模型评估acc 才0.5左右**

**Comment by zhongqianli** [comment]
> OK,我这边所有问题都解决了，我总结一下： 1.不要用mobilenet V3训练，这个模型精度还是不够 2.字典要选对，否则效果真的很差，选自己的字典的话，en要变成cn 3.PaddleOCR不要用最新版，最新版的好像预训练权值读进去效果很差，用今年年初的版本就行。

非常有同感，感觉新版本不如之前的版本了
