### ISSUE TITLE
字典的设置

### ISSUE THREAD

**Issue by pyni** [PaddlePaddle/PaddleOCR#4529]
大佬好，关于字典我有个疑问，我看rec_gt_train.txt里面的ground truth中，不仅仅是字母和数字，还有各种符号，比如'[',']','$':
![Screenshot from 2021-11-02 16-49-40](https://user-images.githubusercontent.com/18031767/139814914-9631e4a1-3da9-4dc9-9ff6-0564f0b7f478.png)

![Screenshot from 2021-11-02 16-49-32](https://user-images.githubusercontent.com/18031767/139814915-16150d43-3f80-431b-bfbe-5f334ca7426e.png)

但是我dict我却还是选择ic15_dict.txt　（也就是a到z＋0到１），请问这样可以训练么？谢谢

**Comment by LDOUBLEV** [comment]
建议重新组织一下字典，统计你数据集中的字符为新的字典
