### ISSUE TITLE
识别模型框出来的位置太紧凑，会丢失边缘信息，导致识别错误

### ISSUE THREAD

**Issue by myfjdthink** [PaddlePaddle/PaddleOCR#453]
原图：

![image](https://user-images.githubusercontent.com/2044143/88882240-10e18880-d264-11ea-870f-e61f2fd4b5b9.png)

识别模型框出文字范围

![image](https://user-images.githubusercontent.com/2044143/88881919-45a11000-d263-11ea-96b7-d1e3aa6dc277.png)

按照识别模型的 box 截取图片后

![8_BRSPT68250](https://user-images.githubusercontent.com/2044143/88882148-e4c60780-d263-11ea-8cc0-4c86fb393926.jpg)

结果最后一个字母 Q 被识别成 0

简单的解决方案是修改 predict_system.py 里剪切图片的逻辑，把框框调大几个像素。

另一个解决方案是，识别模型把框框调大几个像素。

**Comment by MissPenguin** [comment]
可以在命令中加入 --det_db_unclip_ratio ，参数定义位置：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L49，这个参数是检测后处理时控制文本框大小的，默认2.0，可以尝试改成2.5或者更大

**Comment by MissPenguin** [comment]
可以在命令中加入 --det_db_unclip_ratio ，参数定义位置：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L49 ，这个参数是检测后处理时控制文本框大小的，默认2.0，可以尝试改成2.5或者更大

**Comment by myfjdthink** [comment]
修改参数 --det_db_unclip_ratio = 2.5 有效，感谢
