### ISSUE TITLE
AndroidDemo测试App在当前显示和切换到后台运行 同一张图解析耗时相差较大，App在最前端会耗时2s，切换后台运行耗时80s

### ISSUE THREAD

**Issue by YaronWong** [PaddlePaddle/PaddleOCR#4530]
各位开发好
首先感谢提供资源

遇到个问题，如题
Android环境，官方Demo测试，当前App在最前显示和切换到后台运行
同一张图解析耗时相差较大，
App在最前端会耗时2s，
切换后台运行耗时80s

复现步骤：

准备工作：
1.demo准备，主线程/或子线程/或开services/ 循环10次 解析同一张图 
操作步骤：
App打开，开始循环解析同一张图，解析平均一次耗时2s左右，解析到第4.5 张后
按Home，App切换到后台运行，单张解析耗时80s+
看日志： 
当App在最前端显示，ndk log日志刷新速度很快，
当App切换到后台运行，ndklog日志，刷新速度明显降低

参考：
1.猜测是由于进程优先级倒置CPU执行权降低，无法验证，
   仅凭 cat /proc/进程id/oom_adj  查看，App在最前端时候，进程优先级最高0
   App在最前端时候，进程优先级1 ,再过一会，会切换成4 

希望能解答疑惑，感谢
祝顺~ ：）

**Comment by brooklet** [comment]
遇到同样的问题, 急盼解决

**Comment by brooklet** [comment]
Redmi 7A/Redmi 7A(Android 9) CPU:高通 骁龙439
小米8 SE/MI 8 SE(Android 9) CPU:高通 骁龙660
Galaxy A50s/SM-A5070(Android 9) CPU:三星 Exynos 9611
Pixel 3A/Pixel 3a(Android 9) CPU:高通 骁龙670
小米8 SE/MI 8 SE(Android 8.1.0) CPU:高通 骁龙660

以上机型都可以重现

**Comment by WenmuZhou** [comment]
放后台，系统CPU调度给的少，速度慢很正常啊

**Comment by YaronWong** [comment]
> 放后台，系统CPU调度给的少，速度慢很正常啊

之前测试，APP切换到后台，猜测确实是CPU调度少，我查看过进程优先级，降低了，
遇到的问题之前描述过了，App在前台，处理一张图，2s左右，App切换到后台，同一张图，需要60s+，耗时差别较大，
如果说前台耗时2s，后台耗时10s内，或者更短当然是最好的。
这个问题，只是想提出来，不知道是否可以优化解决。如果确实进程优先级低，CPU调度少，那没办法
再次感谢作者提供的服务。
PS 客户端业务，App后台识别，目前采用服务器API搭建的方案，如果能优化到本地APP后台识别2s，将不甚感激。
祝工作愉快

**Comment by YaronWong** [comment]
> 放后台，系统CPU调度给的少，速度慢很正常啊

感谢回复，
后台解析，运行慢了可以理解，耗时较长，是否有方案可以优化，: )
比如前台运行耗时2s，后台5s，以上时间只是做示例
