### ISSUE TITLE
Can't convert PGNet model to Openvino

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/PaddleOCR#4533]
I'm having some troubles trying to convert the PGNet model into OpenVino.  
First I convert the model to ONNX using this command

```
paddle2onnx --model_dir e2e_server_pgnetA_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file pgnet.onnx --opset_version 12
```
Which successfully complete.  
Then I try to convert it to OpenVino using this command:

```
python mo.py --input_model path/to/pgnet.onnx --output_dir "my/output/dir/openvino" --input_shape [1,3,480,160]
```

The shape is one that will match my images in production.  
Sadly I'm getting this error:

```
[ ERROR ]  Shape [  1 256  -1  -1] is not fully defined for output 0 of "Add_21". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "Add_21".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "Add_21".
```

Any suggestions?

**Comment by jiangjiajun** [comment]
Hi @tampe125 

I'm working on ONNX model deploy by OpenVINO now, Could you provide your original PaddlePaddle model and ONNX model, I'll check if the problem brought by Paddle2ONNX

**Comment by tampe125** [comment]
Thank you very much, I used the original model posted in the docs here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/pgnet_en.md#Quick_Use  
You can easily create the ONNX file starting from it

**Comment by Dandelion111** [comment]
> Hi @tampe125
> 
> I'm working on ONNX model deploy by OpenVINO now, Could you provide your original PaddlePaddle model and ONNX model, I'll check if the problem brought by Paddle2ONNX
> 
> And it is more recommend that you send a same issue to [Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)

请问有没有openvino推理ppocr的demo？
