### ISSUE TITLE
对要检测识别的图片进行等比放大

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/PaddleOCR#4535]
你好，请问这个对输入的图片判断，等比放大预处理，应该放在哪里？

**Comment by Gmgge** [comment]
在数据读入的时候进行处理是最简单的，但是如果自己放缩了，最后需要用坐标的时候也要处理一下，你可以在[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/infer/predict_system.py#:~:text=img%2C%20flag%20%3D%20check_and_read_gif,cv2.imread(image_file))插入相关处理的代码。
话说，你是在自学嘛？
