### ISSUE TITLE
mobilenetV3_v2.0_DB检测训练模型转inference模型后识别不出个别目标

### ISSUE THREAD

**Issue by Restnote0** [PaddlePaddle/PaddleOCR#4539]
我在训练mv3模型用作车牌识别时发现训练模型能够较好地识别车牌目标，但是转成inference模型后就有一些车牌目标识别不出来了。我看过issue里面关于训练预测模型和inference预测模型数据预处理改变图片大小和后处理的解答，也确认了对应的参数是一致的，但是还是存在这个问题。

- 下面是训练模型和inference模型识别差别的例子：

1. 

![image](https://user-images.githubusercontent.com/51938769/140029996-229c74c1-c0e4-4cd1-86b9-064c4d732b2e.png)

![image](https://user-images.githubusercontent.com/51938769/140029950-1c34d7b2-7403-4de9-8408-e5b0b2b40442.png)

2. 

![image](https://user-images.githubusercontent.com/51938769/140030269-aa1135f2-5d9c-42e3-aa18-920852b02e0f.png)

![image](https://user-images.githubusercontent.com/51938769/140030306-89d6acde-969e-4540-b789-4bdbc52b751c.png)

- 数据预处理和后处理相关：

  - 预处理：

  ![image](https://user-images.githubusercontent.com/51938769/140030711-0948de93-b10f-40ec-807e-66c2a9524d51.png)
  --
  ![image](https://user-images.githubusercontent.com/51938769/140031336-dc887f82-9bc6-42c2-9f7a-4a744866cd57.png)(这里我直接设置比率为1.0)
  - 后处理：
  
  ![image](https://user-images.githubusercontent.com/51938769/140031814-c2891212-7f28-43b4-b099-cb9d6dbdbde6.png)
  --
  ![image](https://user-images.githubusercontent.com/51938769/140032008-f28883c3-9a77-4f3f-beb9-cf5403801d96.png)
  --
  ![image](https://user-images.githubusercontent.com/51938769/140032046-e358bf11-a4f3-4ec9-bc95-7ba243e11167.png)

请问一下这个问题有什么解决的思路吗？

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/140891173-e43b1714-5941-4416-aac2-3f28d1b5f591.png)

应该是预处理没对上

eval时，预处理用的配置是：https://github.com/PaddlePaddle/PaddleOCR/blob/060c9654aca183bbacf1883de9ecbfbb98f47566/ppocr/data/imaug/operators.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L161
预处理函数是：https://github.com/PaddlePaddle/PaddleOCR/blob/060c9654aca183bbacf1883de9ecbfbb98f47566/ppocr/data/imaug/operators.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L189

inference时，这里改为
{'DetResizeForTest': null} 即可和训练预处理保持一致
https://github.com/PaddlePaddle/PaddleOCR/blob/060c9654aca183bbacf1883de9ecbfbb98f47566/tools/infer/predict_det.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L42

**Comment by Restnote0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
