### ISSUE TITLE
请问一下，在使用EncoderWithReshape的操作时，“filter_size=[inputs.shape[2], 1]”的设置会对竖排文本识别有影响吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleOCR#454]
尊敬的开发者，您好！
最近我在学习PaddleOCR，我在看将CNN特征转换为seq向量时，有一些疑惑，
**第一个问题：** 所有的图像都是用EncoderWithReshape，将CNN-feature-map转换为sequence的吗？
**第二个问题：** 如果所有的图像都是经过EncoderWithReshape进行转换的话，那么，在EncoderWithReshape中，使用的这样的代码来进行转换：“[filter_size=[inputs.shape[2], 1]](https://github.com/PaddlePaddle/PaddleOCR/blob/cb49dcc77be5807d176b717f3e649368bcacc905/ppocr/modeling/heads/rec_seq_encoder.py#L32)”
![图片](https://user-images.githubusercontent.com/27288110/88891318-8e61c480-d275-11ea-8468-89378d4c3406.png)
我想请问一下，这里对stride的设置，是否会对“竖排文本的识别”造成影响呢？，因为这里似乎就是用“整个列的特征”作为当前特征点的特征向量，也就是向量“w\*1\*c”；
期待您的回复！

**Comment by littletomatodonkey** [comment]
你好，感谢你的关注。
* 第一个问题：是的，所有的图像都是用EncoderWithReshape，将CNN-feature-map转换为sequence
* 第二个问题：在识别时，PaddleOCR会主动把竖排文本转正之后再识别，因此对竖排文本的识别这样设置也没有问题的

**Comment by songyuc** [comment]
@littletomatodonkey ，好的，谢谢你的解答！
