### ISSUE TITLE
推理时，特定的batch和width，显存暴涨

### ISSUE THREAD

**Issue by yuxx0218** [PaddlePaddle/PaddleOCR#4542]
镜像：paddlepaddle:2.1.0-gpu-cuda11.2-cudnn8
python版本：3.7.10
paddle版本：2.1.0，GPU版
模型版本：ch_ppocr_server_v1.1_rec_infer

现象：
当模型输入为norm_img_batch = np.ones((b, 3, 32, w), dtype=norm_img_batch.dtype)，
其中，b为8或9【并且】w为300或400或500，在这种特殊的设置下，
显存会暴涨到9000M。
其中，800多M是模型和数据占用的；其余7200M均为模型推理时中间变量占用的。
经测试，【b=10且w=1000】时，模型和数据【仅仅】占用800M，推理中间变量占用400M；b=1且w=100时，模型和数据占用800M，推理中间变量占用100M；其余情况也均作出测试，结果正常。
因此可以判断，在b=8或9且w=300或400或500时，推理中间变量暴涨到7200M属于异常情况。
请修复，谢谢。

另外：
self.predictor.clear_intermediate_tensor()
和
self.predictor.try_shrink_memory()
这两串代码，我没有看到它们有任何用处，无论是否加这两串代码，显存占用都是相同的。
所以，推理结束后，在进程不关闭的情况下，中间的tensor到底如何释放？
如果不关闭进程，GPU就不释放，那请问这个框架在工业场景下的意义何在？

最后：
我比较好奇，贵公司内部是否统一使用paddle框架？交付给客户的项目是否使用该框架？（可以不回答，但是回答的话，请说实话。）

**Comment by WenmuZhou** [comment]
注意到你使用的模型的静态图版本，请问你的代码是否也是静态图版本

**Comment by LDOUBLEV** [comment]
@yuxx0218  开启内存优化的选项是https://github.com/PaddlePaddle/PaddleOCR/blob/db3bc08fc25e6bc3bdb0a72cad5ba109e3768124/tools/infer/utility.py#L266

develop 属于静态图分支，比较老的版本了，现在基本不维护，建议用最新版本

**Comment by yuxx0218** [comment]
> 注意到你使用的模型的静态图版本，请问你的代码是否也是静态图版本，这边目前推荐使用动态图版本，即Dygraph分支或Release/2.3分支下的代码

我使用的是paddle版本是2.1.0 GPU版，推理代码也是模仿2.3分支，用的from paddle import inference中的inference.create_predictor。
只不过，模型用的依旧是静态图的，因为动态图的模型准确率不如静态图。
也就是说，如果不替换模型，哪怕paddle版本再新，也是无法解决的对吧？

**Comment by yuxx0218** [comment]
> @yuxx0218 开启内存优化的选项是
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/db3bc08fc25e6bc3bdb0a72cad5ba109e3768124/tools/infer/utility.py#L266
> 
> develop 属于静态图分支，比较老的版本了，现在基本不维护，建议用最新版本

上述现象的发生，是在config.enable_memory_optim()在create_predictor这里已经加了的情况下发生的。

**Comment by yuxx0218** [comment]
目前比较妥协的解决办法是把batch_size和det_max_side_len以及rec_max_width（我自己加的这个参数）限制在安全的范围内。

**Comment by inewlife** [comment]
> rec_max_width

想请教下rec_max_width这个参数是加到哪里的，我看到代码中本身有rec_image_shape这样一个参数

**Comment by Alwin4Zhang** [comment]
一个bug，几年了没解决，国内生态也是没谁了
