### ISSUE TITLE
显存够用，但是没法启动服务

### ISSUE THREAD

**Issue by qiyueliuhuo** [PaddlePaddle/PaddleOCR#4543]
hub serving start -c deploy/hubserving/ocr_system_heng/config_heng.json 
 上面的命令执行后

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 2.250000kB memory on GPU 0, available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)

实际还有6G显存可用，但是服务就是启动不起来

这是我用工具查看的GPU显存
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
>>> nvmlInit()     #初始化
>>> handle = nvmlDeviceGetHandleByIndex(0)
>>> info = nvmlDeviceGetMemoryInfo(handle)
>>> info.free
7174160384
>>> 7174160384 / (1024 * 1024 * 1024)
6.68145751953125
实际nvidia-smi也显示有6G左右的显存可用，哪里有问题？

**Comment by WenmuZhou** [comment]
paddle的安装检查过了吗
```bash
import paddle
paddle.utils.run_check()
```

**Comment by zhangyingying520** [comment]
> hub serving start -c deploy/hubserving/ocr_system_heng/config_heng.json 上面的命令执行后
> 
> ## Error Message Summary:
> ResourceExhaustedError:
> 
> Out of memory error on GPU 0. Cannot allocate 2.250000kB memory on GPU 0, available memory is only 0.000000B.
> 
> Please check whether there is any other process using GPU 0.
> 
> 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> 2. If no, please decrease the batch size of your model.
> 
> (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
> 
> 实际还有6G显存可用，但是服务就是启动不起来
> 
> 这是我用工具查看的GPU显存 pynvml.nvml.NVMLError_Uninitialized: Uninitialized
> 
> > > > nvmlInit()     #初始化
> > > > handle = nvmlDeviceGetHandleByIndex(0)
> > > > info = nvmlDeviceGetMemoryInfo(handle)
> > > > info.free
> > > > 7174160384
> > > > 7174160384 / (1024 * 1024 * 1024)
> > > > 6.68145751953125
> > > > 实际nvidia-smi也显示有6G左右的显存可用，哪里有问题？

指定一下GPU
