### ISSUE TITLE
预测时间问题

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4562]
请问，在同等参数下，为什么预测单字符的时间要大于八字符的时间？图像大小也基本一致

**Comment by 18362890185** [comment]
![image](https://user-images.githubusercontent.com/87969070/140520264-b335924c-13b2-4b13-a748-370fd85d4c97.png)
第三张图速度块，第四张图很慢，请问这是什么原因呢？

**Comment by littletomatodonkey** [comment]
你好，预测第一张图的时间不准，如果需要测试预测耗时，可以测试多张图片，去除前几张的耗时，对后面的取平均
