### ISSUE TITLE
invalid poly 问题

### ISSUE THREAD

**Issue by jdmking2019** [PaddlePaddle/PaddleOCR#4563]
训练的时候 选用det_r50_vd_sast_icdar15.yml，有时候会出现invalid poly， 
![image](https://user-images.githubusercontent.com/54650688/140495050-2bfde6ee-5dad-42ed-aa64-320dc4cee999.png)
这个是什么原因造成的呢？
期待回复

**Comment by littletomatodonkey** [comment]
数据格式不对吧
