### ISSUE TITLE
PGNet step 2 training model

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/PaddleOCR#4564]
Hello,

as far as I know, the PGNet model is available in inference mode or in training mode but only for the step_1.  
This means that (if I'm not wrong) if I want to fine tune the algorithm I have to perform step_2 training on my own, and then I can fine tune it.  
Is it possible to have the step_2 training model, too?

**Comment by littletomatodonkey** [comment]
Hi, just one step is needed for the model finetune, you can refer to the doc: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/doc_ch/pgnet.md

**Comment by tampe125** [comment]
Thank you. Can you please tell me how can I generate labels for training?

**Comment by littletomatodonkey** [comment]
It is also in the doc, you can review the above doc for more details.

![image](https://user-images.githubusercontent.com/14270174/141037680-35fe1022-871c-4ef8-b602-ffd78d865b78.png)

**Comment by tampe125** [comment]
Yes, I read the docs. My question is:  
How do you produce that data?  

For example, for "standard" detection+recognition we have PPOCRLabel, where you have to draw the 4 corners. With PGNet you have to draw a line on the text.  
Is it possible to have more details on that? Is there any tool to provide annotations? Where should we place the points for the training? How many? Should it be above or under the text to recognize?

**Comment by tampe125** [comment]
Can I have any update on this?

**Comment by AbdulDD** [comment]
While training for PGNet step 2. I am encountering the following error:
Traceback (most recent call last):
  File "/content/PaddleOCR/PaddleOCR/tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/content/PaddleOCR/PaddleOCR/tools/program.py", line 666, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/parallel.py", line 774, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'. Did you mean: 'device_id'?

Can anyone guide me through this?
