### ISSUE TITLE
ppocr  det 的backbone只有mobilenet和resnet

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#4568]
其他的backbone例如ghostnet是因为你们团队测试过效果不如mobilenet所以没有使用吗？

**Comment by MissPenguin** [comment]
> 其他的backbone例如ghostnet是因为你们团队测试过效果不如mobilenet所以没有使用吗？

没测试过其他backbone的效果

**Comment by hice1207** [comment]
> > 其他的backbone例如ghostnet是因为你们团队测试过效果不如mobilenet所以没有使用吗？
> 
> 没测试过其他backbone的效果

感谢回复，那我去试试
