### ISSUE TITLE
wsl docker部署存在问题

### ISSUE THREAD

**Issue by bltcn** [PaddlePaddle/PaddleOCR#4569]
为什么部署完成之后显示监听的不是0.0.0.0呢，而是http://172.17.0.2:8868/呢，而且要怎么才能不出现“WARNING: This is a development server. Do not use it in a production deployment.”的警告？，这样导致我的端口不能正确映射出来
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2021-11-06 09:32:31,543] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
I1106 09:32:31.550035   242 analysis_config.cc:424] use_dlnne_:0
I1106 09:32:31.550164   242 analysis_config.cc:424] use_dlnne_:0
I1106 09:32:31.550186   242 analysis_config.cc:424] use_dlnne_:0
I1106 09:32:31.550235   242 analysis_config.cc:424] use_dlnne_:0
I1106 09:32:31.550284   242 analysis_config.cc:424] use_dlnne_:0
---    Fused 0 subgraphs into layer_norm op.
---    Fused 0 subgraphs into layer_norm op.
---    Fused 0 subgraphs into layer_norm op.
 * Serving Flask app 'paddlehub.serving.app_compat' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:8868/ (Press CTRL+C to quit)

**Comment by MissPenguin** [comment]
这个warning不用管，不影响使用。

172.17.0.2:8868是你本机的ip和端口吗，如果是的话应该也没啥问题

**Comment by bltcn** [comment]
问题是我怎么能够修改为production模式呢？
