### ISSUE TITLE
开发版paddle框架训练检测，对应适配哪个paddleocr的whl包预测？

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#4572]
训练环境：windows，paddleocr2.3，cuda11.2，paddle-gpu=0.0.0开发版，3080ti
预测使用paddleocr的whl包，试过2.3，2.2，2.1版都跑出来结果不对，最后试了下paddleocr==2.0.6却可以，这是为什么呢？

**Comment by tink2123** [comment]
结果不对是指完全错误？还是部分字不对呢，每个paddleocr版本的模型都是重新迭代的，可能您的场景在2.0.6上的模型效果更好，可以多试几张图，同时也欢迎反馈badcase给我们。

**Comment by wjrjsdx** [comment]
情况是训练的车牌检测，同一个模型，在2.0.6检测的出来，但是更高版本检测不出来
![image](https://user-images.githubusercontent.com/63723648/142520221-5630be66-c51e-4e8d-820e-5ee49cce642c.png)

模型文件如下
链接：https://pan.baidu.com/s/12uLJcYgEmWe1vLgRTXQ25w 
提取码：7a8v
