### ISSUE TITLE
文本方向分类模型推理的输出结果问题

### ISSUE THREAD

**Issue by Tellyang7** [PaddlePaddle/PaddleOCR#4573]
如题，我使用了了[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md#%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B](url) 提供的预训练推理模型，和 这里提供的方法 [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/inference_ppocr.md#%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86](url) 
但是最后的结果基本一致，如下：
![image](https://user-images.githubusercontent.com/24445133/140680264-deb239d8-d22a-4bbd-9bfc-2274661ea9c2.png)

请问，这个需要怎么修改才能得到正确的结果呢？

**Comment by tink2123** [comment]
因为这几张图都是正向的呀，这个结果是正确的。

**Comment by Tellyang7** [comment]
> 因为这几张图都是正向的呀，这个结果是正确的。

[https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/doc/imgs_words/ch](url) 这里面word_4.jpg 和 word_5.jpg明显和1，2，3方向不同吧。在我的理解里面，4，5图的方向应该是90或者270度啊？

**Comment by Tellyang7** [comment]
> > 因为这几张图都是正向的呀，这个结果是正确的。
> 
> [https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/doc/imgs_words/ch](url) 这里面word_4.jpg 和 word_5.jpg明显和1，2，3方向不同吧。在我的理解里面，4，5图的方向应该是90或者270度啊？
1，2，3：
![image](https://user-images.githubusercontent.com/24445133/140880449-48dcdd4a-9e71-4e83-bb18-a8ca6872cead.png)
![image](https://user-images.githubusercontent.com/24445133/140880509-63595fc4-0c02-4faf-b17a-eb39b10ff9e1.png)
![image](https://user-images.githubusercontent.com/24445133/140880532-0408eaaa-a7ef-4b46-8ad9-e4e208638306.png)
4，5：
![image](https://user-images.githubusercontent.com/24445133/140880134-d3d452c6-e941-49a4-8ede-8af81cc6a851.png)
![image](https://user-images.githubusercontent.com/24445133/140880595-43f7f0cd-048b-44d4-9df6-613796511d93.png)

还是说cls模型定义的方向和我理解的不太一样？orz

**Comment by Gmgge** [comment]
阅读该[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/angle_class.md#1-%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D)可知。

**Comment by Tellyang7** [comment]
> 阅读该[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/angle_class.md#1-%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D)可知。

感谢，现在懂了
