### ISSUE TITLE
会识别出超出字典索引的数量问题该如何解决

### ISSUE THREAD

**Issue by icesword95** [PaddlePaddle/PaddleOCR#4578]
![image](https://user-images.githubusercontent.com/8707090/140694774-b576405c-d5bc-4b74-8862-c9ed2446b856.png)
![image](https://user-images.githubusercontent.com/8707090/140694803-b8a08edb-72a0-47be-a575-ef8899b5fb18.png)
调用代码为ocr = PaddleOCR(lang='en',use_space_char='False'),输出过字典长度为65，0-9加大小写字母。但在rec_postprocess.py的decode函数里print(batch_idx)会有大于65的92和90出现（如上图），然后就越界报错。在issue搜越界或是只识别英文的问题下类似的错误一大堆，但没有一个给出解决方案的，请问到底该怎么解决？

参数设置里加过rec_char_dict_path='./ppocr/utils/dict/en_dict.txt'
rec_char_type='EN'或'en'或'ch'均无法解决问题
是否是默认的英文识别模型的字典有什么问题？我用来识别的图片里确实有非数字或英文的符号，但我希望它能不要输出或者随便输出一个错的结果都可以。

**Comment by tink2123** [comment]
有越界的问题一般都是因为预测字典和训练模型时使用的字典不匹配。请问您使用的是哪个版本的PaddleOCR，请不要手动修改字典路径和`use_space_char`参数值。
