### ISSUE TITLE
使用cuda10.1 出现RuntimeError: cublas64_100.dll not found.

### ISSUE THREAD

**Issue by hhloverr** [PaddlePaddle/PaddleOCR#458]
使用cuda10.1 出现RuntimeError: cublas64_100.dll not found.的错误，是否需要更换cuda10.0？有没有其它方法可以解决？

**Comment by littletomatodonkey** [comment]
如果可以的话，建议优先更换cuda10.0，或者在docker中折腾cuda环境，

或者如果你能找到`cublas64_101.dll`这个文件的话，可以尝试直接将这个文件再拷贝一份成`cublas64_100.dll`，看下是否可行（不推荐，因为可能其他依赖库的版本也都不相同）
