### ISSUE TITLE
利用export_model.py工具将官方提供的识别训练模型导出为推理模型，推理结果错误

### ISSUE THREAD

**Issue by neverstoplearn** [PaddlePaddle/PaddleOCR#4581]
想导出动态尺寸推理模型，使用python tools/export_model.py --config=/home/zhengxin/OCR/PaddleOCR/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml命令导出https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/README_ch.md中提供的训练模型为推理模型，导出成功后利用python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./"进行推理，结果明显错误。

**Comment by neverstoplearn** [comment]
![Uploading 2021-11-08 15-32-47屏幕截图.png…]()

**Comment by neverstoplearn** [comment]
![2021-11-08 15-32-47屏幕截图](https://user-images.githubusercontent.com/44988584/140701401-985abb38-ebaa-4352-aaf7-630a6f95c523.png)

**Comment by neverstoplearn** [comment]
![2021-11-08 15-35-15屏幕截图](https://user-images.githubusercontent.com/44988584/140701618-db694f55-3ef3-42ab-b33b-11fbbf8e90e3.png)

**Comment by neverstoplearn** [comment]
利用https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/README_ch.md中提供的推理模型，使用python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./"进行推理，结果正确

**Comment by neverstoplearn** [comment]
使用python3 tools/infer_rec.py -c /home/zhengxin/OCR/PaddleOCR/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml基于训练模型进行测试，结果完全不对.
使用python3 tools/infer/infer_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./ch_PP-OCRv2_rec_infer" 结果正确
![2021-11-08 16-27-55屏幕截图](https://user-images.githubusercontent.com/44988584/140708555-16666c5c-7d38-4d12-9716-883beb7d3042.png)
![2021-11-08 16-28-09屏幕截图](https://user-images.githubusercontent.com/44988584/140708568-aab772c4-386b-4ffe-b2b1-b764ac89c978.png)

**Comment by Gmgge** [comment]
我不确定是否正确理解你的提问，在此提出两点，希望有所帮助。
1.python tools/export_model.py是将动态模型转换为静态推理模型，请根据[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md#5-%E8%BD%ACinference%E6%A8%A1%E5%9E%8B%E6%B5%8B%E8%AF%95)说明，使用python3 tools/infer/predict_rec.py预测，并指定相关参数。
2.提供的训练模型是用于某些特定方向是ocr识别，需要进一步训练的，直接将此模型转换为推理静态模型可能精度不高，如果不进行训练，请直接下载通用的推理模型使用。

**Comment by neverstoplearn** [comment]
> 我不确定是否正确理解你的提问，在此提出两点，希望有所帮助。 1.python tools/export_model.py是将动态模型转换为静态推理模型（都是动态尺寸的），请根据[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md#5-%E8%BD%ACinference%E6%A8%A1%E5%9E%8B%E6%B5%8B%E8%AF%95)说明，使用python3 tools/infer/predict_rec.py预测，并指定相关参数。 2.提供的训练模型是用于某些特定方向是ocr识别，需要进一步训练的，直接将此模型转换为推理静态模型可能精度不高，如果不进行训练，请直接下载通用的推理模型使用。

推理模型的尺寸是固定的32 * 100,变化的是batchsize，但是ocr模型中尺寸固定的效果应该不好吧

**Comment by Gmgge** [comment]
需要了解的是，你说的这个推理模型固定尺寸（字符识别模块）是用在二阶段算法OCR里面，首先是从图像中裁剪出文本行（字符检测模块），之后对文本行识别（字符识别模块），此时对文本行进行固定尺寸并不是不合理。
该二阶段算法中间可能存在文本行翻转检测。

**Comment by zhangyingying520** [comment]
> 使用python3 tools/infer_rec.py -c /home/zhengxin/OCR/PaddleOCR/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml基于训练模型进行测试，结果完全不对. 使用python3 tools/infer/infer_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./ch_PP-OCRv2_rec_infer" 结果正确 ![2021-11-08 16-27-55屏幕截图](https://user-images.githubusercontent.com/44988584/140708555-16666c5c-7d38-4d12-9716-883beb7d3042.png) ![2021-11-08 16-28-09屏幕截图](https://user-images.githubusercontent.com/44988584/140708568-aab772c4-386b-4ffe-b2b1-b764ac89c978.png)

你没有指定你训练好的模型吧

**Comment by tink2123** [comment]
使用 export_model 导出，或者使用 infer_rec.py 预测，都需要通过 -o Global.pretrained_model 指定训练好的权重路径，否则模型会随机初始化，肯定得不到正确的预测结果。

**Comment by thds9** [comment]
我导出模型后只有
`├── inference.pdiparams.info    
 └── inference.pdmodel       `这两个文件，没有inference.pdiparams，为什么会这样呀，我是release2.7预训练模型是ch_PP-OCRv4_rec_server_train
