### ISSUE TITLE
PGNet: Random training error

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/PaddleOCR#4587]
I'm performing training of Step 2 for the PGNet model following the instructions on the docs.  
Everything is working fine so far (except for the low accuracy, something that has already been pointed out #4446 ), but from time to time I'm getting these random errors on the log:  
```
[2021/11/08 21:31:25] root ERROR: When parsing line 83, error happened with msg: operands could not be broadcast together with shapes (0,) (0,2)
```
Googling around this seems something coming from Numpy, but any ideas about it? I suspect this is causing the low accuracy, since from time to time there is an "invalid" image in the batch.

**Comment by LDOUBLEV** [comment]
> When parsing line 83, error happened with msg:

Please check your data list, such as line 83. I guess the data in line 83 has the wrong label format.

**Comment by tampe125** [comment]
I'm using the data provided by your examples https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/pgnet_en.md  

At first glance the label format is OK, I tried to open the label file with PPOCRLabel and everything seems fine (except for the polygons). By the way, what should be the correct way to create custom train data for PGNet model?

**Comment by tampe125** [comment]
> > When parsing line 83, error happened with msg:
> 
> Please check your data list, such as line 83. I guess the data in line 83 has the wrong label format.

I made several tests with the same setup (I'm spinning virtual machines, so I can be 100% they are always the same). The error sometimes happens at line 32, then 83, then 1172. It's not always the same but it changes every time.  
How can I give you more relevant info?

**Comment by tampe125** [comment]
Any update on this?
