### ISSUE TITLE
root ERROR: Something went wrong while downloading models

### ISSUE THREAD

**Issue by GXY2017** [PaddlePaddle/PaddleOCR#4588]
I was trying to crop this png picture, root error is reported. 
````
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang='ch', use_gpu=False)
url=r'http://www.100ppi.com/graph/index/table/505-20211025-20211104-175-290-v-p.png'
ocr.ocr(url, cls=True)
````
Error:
````
root ERROR: Something went wrong while downloading models
````
if I change the url to  "http://www.100ppi.com/graph/index/table/505-20211025-20211105-175-290-v-p.png", it works properly.

I cannot figure out the problem. please help, thanks.

**Comment by WenmuZhou** [comment]
has fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/3929
