### ISSUE TITLE
有几个关于识别模型的问题，希望能有大佬解答一下

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#4589]
本人最近在做中文古籍的识别，遇到了一些问题，如下：

1. 都说基于attention的识别模型不能较好地处理长文本图片，我的见解是，要去求当前字和原图片的各个位置的关联程度，由于原图片包含的字数较多，所以很难确定当前字到底与哪个位置最匹配，也就是attention会“分散”，不知道我的理解对吗？

2.关于SRN模型的PVAM（并行视觉注意力模块），为什么可以用Reading Order代替前一个时刻的隐藏状态，作为query呢？我感觉这样做没有道理，但是确实有效果。我用CNN+PVAM训练模型，用交叉熵函数作为损失函数，发现确实能训练出来，效果比较一般，而且收敛的很慢。

3.关于SRN模型的GSRM（全局语义推理模块），该模块的输入是PVAM模块的特征经过一个全连接、softmax和argmax所得到的输出，其实这个输出已经可以作为预测的结果了，但是还是要经过一个GSRM模块，这个模块到底有什么意义呢？而且在最后ed损失函数中，我发现GSRM模块输出的预测结果，在总损失中只占到了0.15的权重（其他两部分分别占1和3的权重），似乎GSRM的输出对最终结果的影响不是很大。

**Comment by tink2123** [comment]
1. 主要是因为attention是一种序列对齐的算法，所以受限于训练时设置的max_length，而ctc是不受限的，所以在超长文本上有更好的效果。
2. 在中文上实验单独使用PVAM效果提升也有限，另外PVAM是作用于2D feature map，如果需要使用的话建议把图片resize的高度修改为64。
3. GSRM里主要是Transformer的decoder模块，更多的是用来学习label中的语义信息，并且实验证明，语义模块的占比不应太高，因此设置为0.15。

**Comment by Lebron-Harden** [comment]
> 1. 主要是因为attention是一种序列对齐的算法，所以受限于训练时设置的max_length，而ctc是不受限的，所以在超长文本上有更好的效果。
> 2. 在中文上实验单独使用PVAM效果提升也有限，另外PVAM是作用于2D feature map，如果需要使用的话建议把图片resize的高度修改为64。
> 3. GSRM里主要是Transformer的decoder模块，更多的是用来学习label中的语义信息，并且实验证明，语义模块的占比不应太高，因此设置为0.15。

感谢！
