### ISSUE TITLE
请问移动端使用的是哪个模型，以及参数如何配置的？

### ISSUE THREAD

**Issue by keyxuliang** [PaddlePaddle/PaddleOCR#459]
同样的图片，我在移动端和pc（c++）端无法实现同样的效果

**Comment by littletomatodonkey** [comment]
你好，PC端使用的是inference model(包含model和params文件)，可以从首页下载
![image](https://user-images.githubusercontent.com/14270174/88995231-b6583300-d31c-11ea-864d-26d5f12b5942.png)

移动端的话，需要使用通过PaddleLite转换后的模型(nb文件)，可以参考这篇文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md
![image](https://user-images.githubusercontent.com/14270174/88995409-21a20500-d31d-11ea-9074-dd6c4b795638.png)

**Comment by keyxuliang** [comment]
我的意思是我用你们给的那个Android app的效果比较好，然后基于
![image](https://user-images.githubusercontent.com/33013417/89002071-bd883c80-d32e-11ea-8c80-d6ca3fbf19cd.png)
用pc（c++）的效果比较差。使用的是同一张图。

**Comment by littletomatodonkey** [comment]
你好，可以测下同一张图的预测结果吗？我这边测试单张图片的结果是基本一致的，在实时视频预测的情况下，提供的android apk的输入图像是经过预处理的，图片质量会高一些。

**Comment by keyxuliang** [comment]
![image](https://user-images.githubusercontent.com/33013417/89012580-00eda580-d345-11ea-9979-4e793afee787.png)


是使用的单张图片测试的，在app上可以检测到。
但是在pc（c++）检测不到，config.txt那几个检测的参数也进行了修改:(

**Comment by littletomatodonkey** [comment]
这个android demo上的置信度设置的是0.0吗？把cpp infer 的det_db_box_thres和det_db_thres改为0.0试下呢？我也反馈下哈

**Comment by keyxuliang** [comment]
嗯，都试过了，就是不行:((((
在使用的时候det config有四个参数，在app里只有一个“置信度”，不知道这个置信度是对应的哪个参数，另外几个参数又是如何设置的？

**Comment by littletomatodonkey** [comment]
嗯android demo上使用的就是你标出来的这2各模型，cpp inference使用的也是这2个，可能是inference model和预测库版本没有对上，可以把原图发我，我在这边测下吗？

**Comment by keyxuliang** [comment]
> 嗯android demo上使用的就是你标出来的这2各模型，cpp inference使用的也是这2个，可能是inference model和预测库版本没有对上，可以把原图发我，我在这边测下吗？
方便留个邮箱吗？我发给你个原图，直接放这里好像不太好:(

**Comment by littletomatodonkey** [comment]
> 方便留个邮箱吗？我发给你个原图，直接放这里好像不太好:(

dazhiningsibuqu@163.com 谢谢

**Comment by keyxuliang** [comment]
> > 方便留个邮箱吗？我发给你个原图，直接放这里好像不太好:(
> 
> [dazhiningsibuqu@163.com](mailto:dazhiningsibuqu@163.com) 谢谢

已发送，请查收。
