### ISSUE TITLE
PGNet 中的 GRM 模块相关代码在什么位置

### ISSUE THREAD

**Issue by CoohYuan** [PaddlePaddle/PaddleOCR#4593]
PGNet论文中展示了GRM模块对性能提升的卓越作用，但是我在PGNet的yml文件和head以及loss中都没有找到图网络推理的相关部分，可以指明一下GRM相关代码处于哪个位置吗？

**Comment by LDOUBLEV** [comment]
GRM模块暂未实现

**Comment by CoohYuan** [comment]
> GRM模块暂未实现

您好，首先感谢您的回复。
请问paddleOCR框架是不是暂时不支持类似于PGNet中GRM的外挂模块，按照论文中的解释，GRM模块应该是对PGNet网络部分完成后的粗糙特征进行进一步特征增强的模块。
我发现GRM在目前的paddleOCR中并没有合适的放置位置，因为GRM需要放在网络部分之后(Architecture的head部分之后)，但是architecture是以head结构作为收尾的，数据继续向后流动就到了Loss部分，但是GRM放在Loss部分显然是不合适的，而放在PostProcess阶段也是不合适的，因为GRM也有需要训练的卷积层和全连接层。
在此也向您表达我的另一个疑问，请问有没有关于training阶段和test阶段的数据流动图或者相关的介绍文档，我也没有在paddleOCR中找到相关的整体数据流动代码，感谢。
