### ISSUE TITLE
创建py脚本import predict_system时候，报错。

### ISSUE THREAD

**Issue by Apollo-asleep** [PaddlePaddle/PaddleOCR#4595]
.py脚本文件内容
from tools.infer import predict_system
报错
ModuleNotFoundError: No module named 'tools.infer'

python命令行使用predict_system.py时正常。
命令
python3 tools/infer/predict_system.py --image_dir="infer_Data/a.jpg" --det_model_dir="inference/ch_ppocr_server_v2.0_det_infer" --cls_model_dir="inference/ch_ppocr_mobile_v2.0_cls_infer" --rec_model_dir="inference/ch_ppocr_server_v2.0_rec_infer" --use_angle_cls=true

**Comment by WenmuZhou** [comment]
麻烦具体一点
