### ISSUE TITLE
端侧部署使用opt将rec模型转换为.nb文件后，移植到Android上无法正常识别

### ISSUE THREAD

**Issue by Fenghaze** [PaddlePaddle/PaddleOCR#4599]
运行环境是win10，使用的是python脚本来转模型，但是转换rec模型时出现如下警告，请问该如何解决？
`[W 11/10 10:16:50.317 ...01\py37\Paddle-Lite\lite\core\program.cc:124 paddle::lite::RuntimeProgram::SaveToProgram] Unknown precision type uint8_t for var lstm_0.tmp_3 in op rnn`

**Comment by littletomatodonkey** [comment]
升级下paddlelite或者试下非量化的模型进行转化试下呢？
