### ISSUE TITLE
能在现有的识别模型基础上微调吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#460]
字符数有改变，能在现有的通用文字识别模型上面进行微调吗？

**Comment by littletomatodonkey** [comment]
你好，可以的，下载我们的预训练模型（pdparams文件），配置下预训练模型地址以及你自己的数据集，就可以进行微调的

**Comment by wuMaoTou** [comment]
预训练模型的下载链接和教程可以发一下吗,谢谢  @littletomatodonkey
