### ISSUE TITLE
哪些预处理可以提高识别效果？需要填充空白保证长宽比么？

### ISSUE THREAD

**Issue by dinglei0719** [PaddlePaddle/PaddleOCR#4602]
输入是一个表格中切出来的单元格，分辨率是 1018 * 151，里边的字识别不出来

![0_1](https://user-images.githubusercontent.com/6258286/141065863-4ab44331-0bdc-4588-8b54-39bd19d31253.png)

**Comment by littletomatodonkey** [comment]
不需要保证空白部分的长宽比，这种情况建议先过一下检测，把文字区域抠出来再做识别
