### ISSUE TITLE
预训练模型的配置文件？

### ISSUE THREAD

**Issue by GanWang** [PaddlePaddle/PaddleOCR#4603]
请问官方提供的各个预训练模型的配置文件在哪里下载？比如https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/README_cn.md#resnet%E5%8F%8A%E5%85%B6vd%E7%B3%BB%E5%88%97里面的检测模型的yml配置文件在哪里下载？

**Comment by littletomatodonkey** [comment]
你好，你贴的这个是分类模型，如果需要ocr模型，可以从ocr repo的文档中获取
