### ISSUE TITLE
倾斜文本矫正

### ISSUE THREAD

**Issue by mijunhua** [PaddlePaddle/PaddleOCR#4607]
请问 分类模型 只是用于区分文本的正反方向吗?  倾斜文本的矫正（仿射变换）在哪里做呢？

**Comment by littletomatodonkey** [comment]
仿射变换是在这里做的

https://github.com/PaddlePaddle/PaddleOCR/blob/b4800ad2b59617e82a6e1e9d2875a7ce67b2b3a6/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L550
