### ISSUE TITLE
弯曲文本识别

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/PaddleOCR#4608]
请问使用DB检测完的弯曲文本怎么送进starnet进行训练呢？

**Comment by littletomatodonkey** [comment]
可以使用这个函数，把完全文本裁剪出来，做仿射变换，变成矩形框

https://github.com/PaddlePaddle/PaddleOCR/blob/b4800ad2b59617e82a6e1e9d2875a7ce67b2b3a6/tools/infer/utility.py#L550
