### ISSUE TITLE
How to Merge the nearby bounding box? 

### ISSUE THREAD

**Issue by shraddha291996** [PaddlePaddle/PaddleOCR#4609]
Hello,
I am using the pgnet inference model for text detection. I want to merge the detected nearby bounding box into one box. Any suggestions where I can make the changes or how I can merge the two nearby detected bounding boxes in one.  Example I have attached my resulting image where I want to merge waiting and machine in one box which is detected separately.
Thank you
![hw_det2](https://user-images.githubusercontent.com/59836701/141100410-d2bac6b1-77e1-4a42-80b5-f85735d696ee.JPG)

**Comment by littletomatodonkey** [comment]
You might try to calculate distance between two boxes and merge them.

**Comment by shraddha291996** [comment]
Thank you for your reply @littletomatodonkey. Can you please suggest where I can make these bounding box calculation or in which file these bounding boxes are being drawn in pgnet model?

**Comment by TangDL** [comment]
@shraddha291996 the recongize result is amazing, I wonder what's your model config,plz!
