### ISSUE TITLE
 2.3版本c++编译第三方库的新手问题

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleOCR#4612]
我在尝试离线编译的时候，由于第三方库extern_autolog-src，编译的时候会git这个库，我把这个包下载之后应该放在什么位置呢？需要该相关代码吗？是像opencv那种有下载log吗？有任何意见都非常感谢？

**Comment by MissPenguin** [comment]
直接按照教程编译就行，如果这个库还是遇到问题，可以把相关的内容删掉，这是我们测试用的一个工具，删掉不影响主要功能。

**Comment by Gmgge** [comment]
切换了2.2版本的编译成功了，2.3的我再尝试一下，多谢啦。
