### ISSUE TITLE
请问下，PGNet的预训练模型有吗，paddle的模型库里只有单独的检测、识别的预训练模型提供，没有e2e的

### ISSUE THREAD

**Issue by ZeroLelouch1205** [PaddlePaddle/PaddleOCR#4617]

**Comment by MissPenguin** [comment]
表格里面就是预训练模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/pgnet.md#%E6%80%A7%E8%83%BD%E6%8C%87%E6%A0%87
