### ISSUE TITLE
可否提供一下只识别英文，数字，不包含中文的检测，识别模型。

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#4625]
可否提供一下只识别英文，数字，不包含中文的检测，识别模型。
在best-accuracy转换为inference模型时，官方检测示例是
 python3 tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model="./output/det_db/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"

使用自己的预训练模型时，此处的-c configs/det/det_mv3_db.yml ，是否应该更改为 和best-accuracy同一文件夹的config.yml
![image](https://user-images.githubusercontent.com/31954286/141295848-103e0a01-6335-481f-9a1f-497804280d47.png)

**Comment by MissPenguin** [comment]
英文数字的识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md#22-%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B



> 使用自己的预训练模型时，此处的-c configs/det/det_mv3_db.yml ，是否应该更改为 和best-accuracy同一文件夹的config.yml

不用

**Comment by Liudyan** [comment]
> 英文数字的识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md#22-%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B
> 
> > 使用自己的预训练模型时，此处的-c configs/det/det_mv3_db.yml ，是否应该更改为 和best-accuracy同一文件夹的config.yml
> 
> 不用

有对应的只包含英文的检测模型吗？发现包含中文的英文检测模型，检测效果不一定好。
