### ISSUE TITLE
是否可以出一个去印章的版本，或者说明一下如何去印章

### ISSUE THREAD

**Issue by bltcn** [PaddlePaddle/PaddleOCR#4629]
在很多识别中，都会遇到有印章的干扰，单纯的去红或者直接二值化都不能获得良好的效果，能否出一个去红章的推理库，或者提示一下怎么训练

**Comment by LDOUBLEV** [comment]
目前没有去印章的库

**Comment by bltcn** [comment]
那要怎么训练去印章呢，能介绍一下思路吗？

**Comment by grsgth** [comment]
训练 一个印章检测模型+一个pix2pix印章去除模型
