### ISSUE TITLE
PaddleOCR识别的draw_ocr函数

### ISSUE THREAD

**Issue by zhihaofan** [PaddlePaddle/PaddleOCR#4630]
![Uploading image.png…]()
请问这种图怎么把识别的结果按找原来的位置展示出来，是用draw_ocr这个函数吗？我在操作文档上没有找到相关操作

**Comment by zhihaofan** [comment]
![001](https://user-images.githubusercontent.com/59326288/141403572-be20aea6-5cbd-4f53-bd4c-aa1163c836b9.png)

**Comment by zhihaofan** [comment]
上边这个图片

**Comment by LDOUBLEV** [comment]
是draw_ocr函数

**Comment by zhihaofan** [comment]
> 是draw_ocr函数

请问怎么使用？我想要的是得到那个右边的图像

**Comment by LDOUBLEV** [comment]
代码在这里，按需修改即可：https://github.com/PaddlePaddle/PaddleOCR/blob/31b06a2fd19f877a09acaf658387bd919c289b8e/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L338

**Comment by mashaonian** [comment]
为什么我使用draw_ocr报错OSError: cannot open resource

**Comment by wandouqiang** [comment]
> 为什么我使用draw_ocr报错OSError: cannot open resource

https://github.com/PaddlePaddle/PaddleOCR/issues/422

**Comment by Xelawk** [comment]
> ![001](https://user-images.githubusercontent.com/59326288/141403572-be20aea6-5cbd-4f53-bd4c-aa1163c836b9.png)

我这边也是用的draw_ocr，但绘制不出这个效果
