### ISSUE TITLE
关于ppocr在nvidia xavier nx上的几处bug

### ISSUE THREAD

**Issue by 77h2l** [PaddlePaddle/PaddleOCR#4631]
paddle-inference 2.0版本推理引擎，在xavier nx上编译带tensorrt加速的推理库后，实际运行时，遇到下面2个问题：
1.开启trt加速后，使用官方开源的v2版本模型，报动态shape不支持的问题：
 'call last):\\n--------------------------------------\\n0   '
 'paddle::AnalysisPredictor::ZeroCopyRun()\\n1   '
 'paddle::framework::NaiveExecutor::Run()\\n2   '
 'paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, '
 'paddle::platform::Place const&)\\n3   '
 'paddle::operators::TensorRTEngineOp::RunTrt(paddle::framework::Scope const&, '
 'paddle::platform::Place const&, '
 'paddle::inference::tensorrt::TensorRTEngine*) const\\n4   '
 'paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary '
 'const&, char const*, int)\\n5   '
 'paddle::platform::GetCurrentTraceBackString[abi:cxx11]()\\n\\n----------------------\\nError '
 'Message Summary:\\n----------------------\\nInvalidArgumentError: Input '
 'shapes are inconsistent with the model. Expect [3, 960, 960] in model '
 'description, but got [3, 960, 448] in runtime. TRT 5 or lower version does '
 'not support dynamic input shapes. Please check and modify your input '
 'shapes.\\n  [Hint: Expected model_input_shape == runtime_input_shape == '
 'true, but received model_input_shape == runtime_input_shape:0 != true:1.] '

2.用ppocr最新的官方源代码，开启trt加速模式，单独运行检测模式似乎没有问题，但是量化精度从fp32修改为int8模式时，耗时却大幅增加了？

3.cpp_infer demo，使用gpu模式耗时竟然比cpu模式还要高？

**Comment by LDOUBLEV** [comment]
1. 动态shape不支持的问题，屏蔽这行[代码](https://github.com/PaddlePaddle/PaddleOCR/blob/b4800ad2b59617e82a6e1e9d2875a7ce67b2b3a6/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L267)，参考代码格式增加对应的动态shape，https://github.com/PaddlePaddle/PaddleOCR/blob/b4800ad2b59617e82a6e1e9d2875a7ce67b2b3a6/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L175

如果还不能解决，可以尝试加大min_subgraph_size这个参数：https://github.com/PaddlePaddle/PaddleOCR/blob/b4800ad2b59617e82a6e1e9d2875a7ce67b2b3a6/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L38


2. 用ppocr最新的官方源代码，开启trt加速模式，单独运行检测模式似乎没有问题，但是量化精度从fp32修改为int8模式时，耗时却大幅增加了？

这个是bug，内部已经反馈了

3. 这个问题不正常，建议warmup几次，再去测试

**Comment by rainmakerMa** [comment]
请问这个bug是否修复了？
