### ISSUE TITLE
没有识别空格的情况怎么解决

### ISSUE THREAD

**Issue by versusniubility** [PaddlePaddle/PaddleOCR#4639]
我用葡萄牙语lang=pt训练出来，会发生同一个地方附近的单词，虽然在图片中分隔非常明晰，但识别出来的却都连在一起，很难后续操作，想问下这个有什么办法是可以解决的吗

**Comment by LDOUBLEV** [comment]
将空格作为一个字符重新训练识别模型

**Comment by Hgd15601257355** [comment]
这个办法是针对官方的空格识别不大好，所以两个靠的近的句子经常会识别为一个box,  对后续应用造成较大的干扰， 而不是为了识别空格。det_model 相当于一个结合了先验知识的二值图， 这个二值图一般来说效果更好，方法中是用常规的二值图（符合人体视觉）进行辅助划分，性能没有测试过。。垂直文字没有测试过。。

1. 在 ocr_db_crnn.cc 文件中的 RunRecModel() 函数中的 crop_img = GetRotateCropImage(srcimg, boxes[i]); 行之后添加
 **get_space(crop_img, box[boxes.size() -1 -i], space[boxes.size() - 1 - i]);** 注：auto space = std::vector<std::vector<float>>(boxes.size(), std::vector<float>());
2. 函数是
`void get_space(cv::Mat& crop_mat, std::vector<std::vector<int>>& box, std::vector<std::vector<float>>& s, float distance=0.8, float dis=1.5) {
// 如果(文字间的空格距离)大于(高度*distance) 且(文字间的空格距离)大于(所有大于0的空格的平均距离 * dis),则算作空格。
// s 中返回每个空格的左坐标和右坐标，方便定位。space 包含了每个box 对应的坐标。
    auto _width = crop_mat.cols;
    auto _height = crop_mat.rows;
    cv::Mat img;
    
    cv::GaussianBlur(crop_mat, img, cv::Size(3, 3), 0);
    cv::Mat image;
    cv::Canny(img, image, 100, 250);
    std::vector<std::vector<cv::Point>> contours;
    std::vector<cv::Vec4i> hierarchy;
    cv::findContours(image, contours, hierarchy, cv::RETR_TREE, cv::CHAIN_APPROX_SIMPLE);
    std::vector<std::vector<float>> lgt;
    for (auto contour : contours) {
        auto box = cv::minAreaRect(contour);
        cv::Point2f vertex[4];
        box.points(vertex);
        auto x_left = min(vertex[0].x, vertex[1].x);
        auto x_right = max(vertex[2].x, vertex[3].x);
        lgt.push_back(std::vector<float>({x_left, x_right}));
    }

    std::sort(lgt.begin(), lgt.end(),
    [&](std::vector<float> i, std::vector<float> j){return i[0] < j[0]; });

    if (lgt.size() > 1) {
        auto sp = std::vector<float>(lgt.size() - 1, 0.f);
        auto sm = 0.f;
        auto times = 0;
        for (auto i = 1; i < lgt.size(); ++i) {
            auto gap = std::max(lgt[i][0] - lgt[i - 1][1], 0.f);
            if (gap != 0.f) {
                times += 1;
            }
            sm += gap;
            sp[i - 1] = gap;
        }
        auto mean = sm / times;
        
        for (auto i = 1; i < lgt.size(); ++i) {
            if ((lgt[i][0] - lgt[i - 1][1]) > _height * distance && (sp[i - 1] > mean * dis)) {
                s.push_back(std::vector<float>({ lgt[i - 1][1], lgt[i][0] }));
            }
        }
    }
}`

**Comment by nissansz** [comment]
How to convert this code to python?
