### ISSUE TITLE
麻烦问一下模型是否可以输出文本行的坐标信息？

### ISSUE THREAD

**Issue by wangguanhua** [PaddlePaddle/PaddleOCR#464]

**Comment by littletomatodonkey** [comment]
你好，文本行的坐标在这里就可以拿到：`dt_boxes`

https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/tools/infer/predict_system.py#L137

**Comment by hsyy673150343** [comment]
> 你好，文本行的坐标在这里就可以拿到：`dt_boxes`
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/tools/infer/predict_system.py#L137

我发现经过排序后输出的坐标框的坐标值有时候并不是严格的按照从上往下从左往右的顺序，会出现同一行文本的不同文本块的坐标左右颠倒的情况。我想请问一下您，当图片中有很多行、很多列文本块的时候，怎么严格地去将不同行和不同列文本块区分出来？有什么思路吗？(我简单地用左上右下的坐标判断，会出现不同行判断为同一行的情况。)

**Comment by wangguanhua** [comment]
我也是，我是在文字识别的时候发现同一行文字的输出顺序并不是严格从左到右，所以才想从坐标下手



---原始邮件---
发件人: "13096337080@163.com"<notifications@github.com&gt;
发送时间: 2020年8月4日(周二) 上午8:59
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 麻烦问一下模型是否可以输出文本行的坐标信息？ (#464)




  
你好，文本行的坐标在这里就可以拿到：dt_boxes
 
https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/tools/infer/predict_system.py#L137
  
我发现经过排序后输出的坐标框的坐标值有时候并不是严格的按照从上往下从左往右的顺序，会出现同一行文本的不同文本块的坐标左右颠倒的情况。我想请问一下您，当图片中有很多行、很多列文本块的时候，怎么严格地去将不同行和不同列文本块区分出来？有什么思路吗？(我简单地用左上右下的坐标判断，会出现不同行判断为同一行的情况。)

**Comment by hsyy673150343** [comment]
可以啊发自我的华为手机-------- 原始邮件 --------发件人： zhoujun <notifications@github.com>日期： 2020年9月22日周二 清晨6:51收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Comment <comment@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleOCR] 麻烦问一下模型是否可以输出文本行的坐标信息？ (#464)
Closed #464.
