### ISSUE TITLE
Pyinstaller在Ubuntu中打包项目，运行可执行文件时ModuleNotFoundError: No module named 'framework_pb2'

### ISSUE THREAD

**Issue by ninja119347** [PaddlePaddle/PaddleOCR#4640]
framework_pb2和pass_desc_pb2.py在同一级目录可是import却报错了。
![image](https://user-images.githubusercontent.com/42988551/141442649-3dedfaf3-9d4e-4e1e-952d-ee33d84b7072.png)

**Comment by guantongpeng** [comment]
改成from . import framework_pb2 as framework__pb2

**Comment by ninja119347** [comment]
> 改成from . import framework_pb2 as framework__pb2

在打包的时候没有报错了，可是执行的时候一直得不到结果，在warning.txt中有很多因为import格式错误导致的missing module
![image](https://user-images.githubusercontent.com/42988551/141650295-fe6de870-8b66-4947-b17f-69a6c2a2c54a.png)
![image](https://user-images.githubusercontent.com/42988551/141650639-ea01af19-6380-4272-ba4a-6c1336522443.png)

这些错误大概是因为fluid.layers下的函数在layers文件夹下的py文件中，直接import fluid.layers+函数名会找不到，如果一个个更改import语句的话过于麻烦，是否有好的解决方法（在python命令行中直接import fluid.layers+函数名会直接报错，为什么打包之前还能成功运行）？十分感谢回复！

**Comment by guantongpeng** [comment]
> > 改成from . import framework_pb2 as framework__pb2
> 
> 在打包的时候没有报错了，可是执行的时候一直得不到结果，在warning.txt中有很多因为import格式错误导致的missing module ![image](https://user-images.githubusercontent.com/42988551/141650295-fe6de870-8b66-4947-b17f-69a6c2a2c54a.png) ![image](https://user-images.githubusercontent.com/42988551/141650639-ea01af19-6380-4272-ba4a-6c1336522443.png)
> 
> 这些错误大概是因为fluid.layers下的函数在layers文件夹下的py文件中，直接import fluid.layers+函数名会找不到，如果一个个更改import语句的话过于麻烦，是否有好的解决方法（在python命令行中直接import fluid.layers+函数名会直接报错，为什么打包之前还能成功运行）？十分感谢回复！

试试这样修改打包命令，PyInstaller -F -w  xxx.py --paths="你的paddle包路径"

**Comment by abxyz888** [comment]
遇到了相同的问题，请问解决了吗?

**Comment by ninja119347** [comment]
> 遇到了相同的问题，请问解决了吗?

应该是路径问题，但是改的地方太多了，放弃了。

**Comment by gewenpulan** [comment]
同样遇到这个问题了，打包exe出现这个错误，之前打包没问题，是因为paddleocr有更新导致的？

**Comment by geoexploring** [comment]
我这里将`import framework_pb2 as framework__pb2`改成`import paddle.fluid.proto.framework_pb2 as framework__pb2`就可以了。

**Comment by loveanao** [comment]
> 
ir.py

修改为
from .proto import framework_pb2
try:
    import pass_desc_pb2
except ModuleNotFoundError:
    import sys
    sys.path.append(path.join(path.dirname(__file__), 'proto'))
    import .proto.pass_desc_pb2

这个不报错了，过了，
结果就出现
 No module named 'paddle.fluid.ir'

只有去修改__init__.py文件

**Comment by haohetao** [comment]
> 

这样改可以打包，但是运行死循环，cpu100%,内存100%

**Comment by vb6iscool** [comment]
plz open this issue, i met it and i dont know what to do~ plz help!

**Comment by vb6iscool** [comment]
Has anyone found a solution for this issue?

**Comment by Adou02** [comment]
> > > 改成from . import framework_pb2 as framework__pb2
> > 
> > 
> > 在打包的时候没有报错了，可是执行的时候一直得不到结果，在warning.txt中有很多因为import格式错误导致的missing module ![图像](https://user-images.githubusercontent.com/42988551/141650295-fe6de870-8b66-4947-b17f-69a6c2a2c54a.png) ![图像](https://user-images.githubusercontent.com/42988551/141650639-ea01af19-6380-4272-ba4a-6c1336522443.png)
> > 这些错误大概是因为fluid.layers下的函数在layers文件夹下的py文件中，直接import fluid.layers+函数名会找不到，如果一个个更改import语句的话过于麻烦，是否有好的解决方法（在python命令行中直接import fluid.layers+函数名会直接报错，为什么打包之前还能成功运行）？十分感谢回复！
> 
> 试试这样修改打包命令，PyInstaller -F -w xxx.py --paths="你的paddle包路径"

没有用呀，这个问题解决了吗？
