### ISSUE TITLE
PPOCRLabel 退出的时候卡死报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#4642]
paddleocr                         2.3.0.1
paddlepaddle-gpu                  2.1.3.post112
python3.8
win11
-------------

python PPOCRLabel.py --lang ch

```
Traceback (most recent call last):
  File "PPOCRLabel.py", line 1467, in closeEvent
    settings.save()
  File "F:\PaddleOCR\PPOCRLabel\libs\settings.py", line 41, in save
    pickle.dump(self.data, f, pickle.HIGHEST_PROTOCOL)
  File "E:\anaconda3\envs\python38\lib\site-packages\Cython\Shadow.py", line 542, in __getattr__
    return __import__(item)
ModuleNotFoundError: No module named '_unpickle_type'
```

**Comment by monkeycc** [comment]
初步怀疑是安装了PaddleX 再安装PaddleOCR
是不是环境冲突了 造成了一些包 不兼容

官方有没什么解决方法
@LDOUBLEV

**Comment by Evezerest** [comment]
有尝试使用3.7的python版本么

**Comment by monkeycc** [comment]
pip install numpy 1.21.2
就可以解决 
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObjec

主要应该还是Cython版本过高 导致的问题
