### ISSUE TITLE
`.ocr()` does not support loading images with https

### ISSUE THREAD

**Issue by nan-wang** [PaddlePaddle/PaddleOCR#4644]
While adding paddleOCR to [Jina Hub](https://hub.jina.ai/executor/78yp7etm), I find that `.ocr()` does not support `https`. Here are sample codes which do not work.

```python
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang='en', use_gpu=False)
img_path = 'https://files.realpython.com/media/results2.5d8d3b8108cd.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
```

**Comment by GXY2017** [comment]
Seems .ocr() does not support loading from  HTTP://  , either.

ERROR - error in loading image:http://www.100ppi.com/graph/index/table/505-20220220-20220302-175-290-v-p.png
