### ISSUE TITLE
acc升高后又降低

### ISSUE THREAD

**Issue by skw1975** [PaddlePaddle/PaddleOCR#4647]
在做英文文本识别时，配置文件使用rec_en_number_lite_train.yml，字典使用en_dict.txt，训练样本约2K真实图片，平均每个字符的样本数在1200个，但是字符样本不均衡，最多的样本有3K，最少的样本只有240个字符,epoch到了170时，acc就达到了0.8，并保存到了best_accuracy中，此后acc就一直下降，到epoch为400多时，acc降到0.3左右。但是我使用best_accuracy测试真实的100张图片，识别率还是很高的，大概在90%以上。请问我这是训练过头了，还是过拟合了，还是数据量太少了？我还能获取得更高的准确率吗？应该如何调整？

**Comment by littletomatodonkey** [comment]
看着是过拟合了，这个数据量有点少了，可以增加到1W左右试下，另外就是可以增加一些数据增广策略，看下

**Comment by skw1975** [comment]
> 看着是过拟合了，这个数据量有点少了，可以增加到1W左右试下，另外就是可以增加一些数据增广策略，看下

感谢！
