### ISSUE TITLE
Can we give third party OCR output json as input for ppstructure for table structure recognition?

### ISSUE THREAD

**Issue by alenma04** [PaddlePaddle/PaddleOCR#4648]

**Comment by littletomatodonkey** [comment]
yes, but you should guarantee that the input-output interface works fine.

**Comment by alenma04** [comment]
> yes, but you should guarantee that the input-output interface works fine.

**Comment by alenma04** [comment]
It will be very helpful if you can provide an example for detecting table structure from a third party OCR json.
