### ISSUE TITLE
crnn训练时提醒图片中文字长度为0

### ISSUE THREAD

**Issue by WingGun** [PaddlePaddle/PaddleOCR#465]
如题，训练crnn模型时出现报错
`ine362: Wrong data type.Excepted string with length between 1 and 25, but got '0'. Label is '磨丢河窜蹬奶鼋'`
提示文字长度为0，但实际上文字长度不是零，训练图片如下，麻烦各路大佬能帮忙解决一下
![horizontal003](https://user-images.githubusercontent.com/45393614/89120512-6ed2d200-d4e9-11ea-9f15-3297b94c053c.jpg)

**Comment by littletomatodonkey** [comment]
你好，可以先检查下，图片路径和标注信息是否用`\t`作为分隔，然后可以再这里打印下`label`的信息，看下是否符合预期
https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/ppocr/data/rec/img_tools.py#L358

**Comment by WingGun** [comment]
> 你好，可以先检查下，图片路径和标注信息是否用分开`\t`，然后可以再这里打印下`label`的信息，看下是否符合预期
> https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/ppocr/data/rec/img_tools.py#L358

图片路径和标注信息是用\t作为分割的，至于label信息后面打印出来也是符合预期的，他一直提醒的是长度为零，我觉得应该跟label没关系吧，大佬你觉得呢？

**Comment by littletomatodonkey** [comment]
你好，可以把这个label发我 我这边看下吗？不知道是否是文件编码的问题～
dazhiningsibuqu@163.com

**Comment by WingGun** [comment]
> 你好，可以把这个label发我 我这边看下吗？不知道是否是文件编码的问题～
> [dazhiningsibuqu@163.com](mailto:dazhiningsibuqu@163.com)

那就劳烦大佬了

**Comment by littletomatodonkey** [comment]
你的yaml文件中，Global.character_dict_path使用是什么呢？需要使用中文的character dict，比如说，`./ppocr/utils/ppocr_keys_v1.txt`

**Comment by WingGun** [comment]
> 你的yaml文件中，Global.character_dict_path使用是什么呢？需要使用中文的character dict，比如说，`./ppocr/utils/ppocr_keys_v1.txt`

用的也是./ppocr/utils/ppocr_keys_v1.txt

**Comment by littletomatodonkey** [comment]
![image](https://user-images.githubusercontent.com/14270174/89144994-f79d4c80-d581-11ea-8e00-13073a3b2f55.png)
可以把你的代码包和部分可复现数据打包发我吗？我这边在python3.7下面基于`configs/rec/rec_chinese_lite_train.yml`这个配置文件运行是正常的

**Comment by WingGun** [comment]
> ![image](https://user-images.githubusercontent.com/14270174/89144994-f79d4c80-d581-11ea-8e00-13073a3b2f55.png)
> 可以把你的代码包和部分可复现数据打包发我吗？我这边在python3.7下面基于`configs/rec/rec_chinese_lite_train.yml`这个配置文件运行是正常的

好的，您稍等，我打包发到您的邮箱，谢谢

**Comment by chros425** [comment]
![image](https://user-images.githubusercontent.com/25075794/93332802-f9cb1a00-f854-11ea-9d58-3a5f521ca588.png)
你好，我这边也碰到一样的问题，用的是官方提供的样例数据ic15_rec的数据，在机器V100-16G双卡的显卡上跑的，请问最后是怎么解决的

**Comment by ezio1320** [comment]
这种情况是因为你的label中有字典中（也就是你设置的Global.character_dict_path）没有的字符，可能是比较生僻的汉字，也可能是特殊的符号，总之就是你提供字典里没有这个字符。
两种解决方案：
1、筛选训练集，删除含有非字典字符的数据
2、往字典里加入你所需要的字（生僻汉字或特殊符号）
