### ISSUE TITLE
SAST c++部署可以吗

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/PaddleOCR#4650]
PaddleOCR==2.3
检测算法：SAST源码里面只有DB的检测接口，使用SAST推理模型报错或者就是检测不出来。
问下SAST是否支持C++部署。

**Comment by MissPenguin** [comment]
c++部署的检测算法暂时只适配了DB，有需要的话可以自己适配一下SAST哈

**Comment by QIANXUNZDL123** [comment]
> c++部署的检测算法暂时只适配了DB，有需要的话可以自己适配一下SAST哈

你们自己做过测试吗？？？有没有源码提供参考

**Comment by MissPenguin** [comment]
> > c++部署的检测算法暂时只适配了DB，有需要的话可以自己适配一下SAST哈
> 
> 你们自己做过测试吗？？？有没有源码提供参考

没有测试过，主要需要把前后处理的python代码转为C++代码，可以参考DB的代码

**Comment by QIANXUNZDL123** [comment]
> > > c++部署的检测算法暂时只适配了DB，有需要的话可以自己适配一下SAST哈
> > 
> > 
> > 你们自己做过测试吗？？？有没有源码提供参考
> 
> 没有测试过，主要需要把前后处理的python代码转为C++代码，可以参考DB的代码

好的，谢谢回答！！
