### ISSUE TITLE
PGNet: Random training error (PGPostprocess)

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4652]
How to fix [the error](https://github.com/huylgia/ContainerClassification/blob/main/Screenshot%20from%202021-11-15%2014-25-12.png) when I start training?
Best regard

**Comment by littletomatodonkey** [comment]
Hi, i can not find the image you mentioned above, you can upload the image in this page.

**Comment by huylgia** [comment]
![Screenshot from 2021-11-15 14-25-12](https://user-images.githubusercontent.com/88916218/142007350-90a97156-c1bf-478c-b53b-51a00ad7ff22.png)
