### ISSUE TITLE
remove detection model from inference procedure on android 

### ISSUE THREAD

**Issue by saeedkhanehgir** [PaddlePaddle/PaddleOCR#4655]
Hi
Thanks for sharing your work.
I want to use only the recognition (.nb mode)  for android. how can I do this ?

In
 
./ocr_db_crnn ch_ppocr_mobile_v2.0_det_opt.nb  ch_ppocr_mobile_v2.0_rec_opt.nb  ch_ppocr_mobile_v2.0_cls_opt.nb  ./11.jpg  ppocr_keys_v1.txt

I want use only ch_ppocr_mobile_v2.0_rec_opt.nb model.
Thanks

**Comment by littletomatodonkey** [comment]
you might need to extract the rec code and re-compile the lite program in ocr, preprocess also needs to be modified to adapt to the rec model.

**Comment by saeedkhanehgir** [comment]
Thanks @littletomatodonkey 
It is not possible for you to release a version that allows the user to select models.
