### ISSUE TITLE
Linux compiler armv7hf ocr, make -j error.

### ISSUE THREAD

**Issue by lichman0405** [PaddlePaddle/PaddleOCR#4656]
我们尝试将paddleocr部署到armv7hf的树莓派3b+上。

paddle-lite编译、paddleOCR编译、opt编译全部成功。

但是，在develop branch的说明的第五步启动调试时，make -j报错。

Makefile:4: ../Makefile.def: No such file or directory
make: *** No rule to make target '../Makefile.def'.  Stop.

求助。

**Comment by WenmuZhou** [comment]
尝试一下dygraph分支的代码和paddlelite2.9

**Comment by lichman0405** [comment]
> 尝试一下dygraph分支的代码和paddlelite2.9

您那边成功了吗？我多次编译之后在最后一步编译可执行ocr_db_crrn文件时缺少makefile。

尝试多种办法。无解。
