### ISSUE TITLE
SAST inference error

### ISSUE THREAD

**Issue by hungcao0402** [PaddlePaddle/PaddleOCR#4658]
The model SAST can predict but when I convert it to inference it has an error.
![image](https://user-images.githubusercontent.com/79310692/141837293-a622c7a4-1f91-4f1c-a35e-bf5431d49832.png)

**Comment by MissPenguin** [comment]
Can you show me your  complete export model command？

**Comment by hungcao0402** [comment]
![image](https://user-images.githubusercontent.com/79310692/141982717-3bf42bc0-ce3c-4da8-89f6-53998a81bd26.png)
Here is my command when I export model

**Comment by MissPenguin** [comment]
I tried with the open-sourced trained model. All works well.

export model:
- python3 tools/export_model.py -c ./configs/det/det_r50_vd_sast_icdar15.yml -o Global.pretrained_model=trained_models/det_r50_vd_sast_icdar15_v2.0_train/best_accuracy Global.save_inference_dir=output/det_sast_ic15

run inference:
- python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir=output/det_sast_ic15/

Maybe there is something wrong with your trained model.

**Comment by zzf123000** [comment]
我的同样如此
![image](https://user-images.githubusercontent.com/17983230/141997764-faf339cc-786a-4764-99c3-c5dcff6f305f.png)

**Comment by hungcao0402** [comment]
I fixed the problem with **!python3 -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple**
 before export model instead of install paddlepaddle-gpu==2.2.0

**Comment by Jeck-Liu-Create** [comment]
paddlepaddle-gpu==2.0.0 报错
```
`python3` tools/export_model.py -c configs/det/det_r50_vd_sast_totaltext.yml -o Global.pretrained_model=./inference/det_r50_vd_sast_totaltext_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_tt
Traceback (most recent call last):
  File "tools/export_model.py", line 25, in <module>
    from paddle.jit import to_static
ModuleNotFoundError: No module named 'paddle.jit'
```

**Comment by MissPenguin** [comment]
> paddlepaddle-gpu==2.0.0 报错
> 
> ```
> `python3` tools/export_model.py -c configs/det/det_r50_vd_sast_totaltext.yml -o Global.pretrained_model=./inference/det_r50_vd_sast_totaltext_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/det_sast_tt
> Traceback (most recent call last):
>   File "tools/export_model.py", line 25, in <module>
>     from paddle.jit import to_static
> ModuleNotFoundError: No module named 'paddle.jit'
> ```

用2.1.3
