### ISSUE TITLE
"segmentation fault(core dumped)"

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#466]
when I used multi-gpu training MobilenetV3 in text Detection,going wrong with "segmentation fault(core dumped)".
(cuda10.0 ,PaddleOCR1.7.2, I changed dataloader to fit my dataset)
[image](https://user-images.githubusercontent.com/43194342/89140502-62478b80-d574-11ea-9066-36c1ffd0c598.png)

**Comment by ZhaoyangLi-nju** [comment]
The error as follows:
2020-08-03 10:28:28,921-INFO: places would be ommited when DataLoader is not iterable
W0803 10:28:29.591706 51295 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0803 10:28:29.595803 51295 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-08-03 10:28:30,924-INFO: Loading parameters from ./pretrain_models/MobileNetV3_large_x0_5_pretrained/...
2020-08-03 10:28:30,924-WARNING: ./pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-08-03 10:28:30,924-WARNING: ./pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-08-03 10:28:31,055-INFO: Finish initing model from ./pretrain_models/MobileNetV3_large_x0_5_pretrained/
2020-08-03 10:28:31,055-INFO: During the training process, after the 4000th iteration, an evaluation is run every 5000 iterations
I0803 10:28:31.101505 51295 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0803 10:28:44.335379 51295 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0803 10:28:44.335413 51295 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0803 10:28:44.335419 51295 init.cc:214] The detail failure signal is:

W0803 10:28:44.335425 51295 init.cc:217] *** Aborted at 1596421724 (unix time) try "date -d @1596421724" if you are using GNU date ***
W0803 10:28:44.337843 51295 init.cc:217] PC: @                0x0 (unknown)
W0803 10:28:44.337977 51295 init.cc:217] *** SIGSEGV (@0x0) received by PID 51295 (TID 0x7f5c017b2700) from PID 0; stack trace: ***
W0803 10:28:44.339989 51295 init.cc:217]     @     0x7f5c013c13d0 (unknown)
W0803 10:28:44.341890 51295 init.cc:217]     @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by littletomatodonkey** [comment]
Could you provide the cudnn version(7.6 and higher is nece)?  You can also run the following code to check your paddle env (saved as `test_paddle_env.py` and run `python test_paddle_env.py`).

```test_paddle_env.py
import paddle.fluid
paddle.fluid.install_check.run_check()
```
You may see the following info if the installation process is right.
```
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0803 02:49:43.373821 56129 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
```

**Comment by ZhaoyangLi-nju** [comment]
thanks for your response,but when I run test_paddle_env.py get the result as follows:
Running Verify Paddle Program ... 
W0803 15:59:48.705689 184954 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0803 15:59:48.708839 184954 device_context.cc:245] device: 0, cuDNN Version: 7.6.
Your Paddle works well on SINGLE GPU or CPU.
I0803 15:59:50.062398 184954 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 8 cards are used, so 8 programs are executed in parallel.
W0803 16:00:14.463047 184954 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0803 16:00:14.463075 184954 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0803 16:00:14.463080 184954 init.cc:214] The detail failure signal is:

W0803 16:00:14.463086 184954 init.cc:217] *** Aborted at 1596441614 (unix time) try "date -d @1596441614" if you are using GNU date ***
W0803 16:00:14.464783 184954 init.cc:217] PC: @                0x0 (unknown)
W0803 16:00:14.465371 184954 init.cc:217] *** SIGSEGV (@0x0) received by PID 184954 (TID 0x7fa8b1712700) from PID 0; stack trace: ***
W0803 16:00:14.468803 184954 init.cc:217]     @     0x7fa8b13213d0 (unknown)
W0803 16:00:14.472050 184954 init.cc:217]     @                0x0 (unknown)
Segmentation fault (core dumped)
CUDNN(7.6.5)

**Comment by ZhaoyangLi-nju** [comment]
> Could you provide the cudnn version(7.6 and higher is nece)? You can also run the following code to check your paddle env (saved as `test_paddle_env.py` and run `python test_paddle_env.py`).
> 
> ```python
> import paddle.fluid
> paddle.fluid.install_check.run_check()
> ```
> 
> You may see the following info if the installation process is right.
> 
> ```
> Your Paddle Fluid works well on SINGLE GPU or CPU.
> W0803 02:49:43.373821 56129 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
> Your Paddle Fluid works well on MUTIPLE GPU or CPU.
> Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
> ```

Thanks for your response,but when I run test_paddle_env.py get the result as follows:
Running Verify Paddle Program ...
W0803 15:59:48.705689 184954 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0803 15:59:48.708839 184954 device_context.cc:245] device: 0, cuDNN Version: 7.6.
Your Paddle works well on SINGLE GPU or CPU.
I0803 15:59:50.062398 184954 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 8 cards are used, so 8 programs are executed in parallel.
W0803 16:00:14.463047 184954 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0803 16:00:14.463075 184954 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0803 16:00:14.463080 184954 init.cc:214] The detail failure signal is:

W0803 16:00:14.463086 184954 init.cc:217] *** Aborted at 1596441614 (unix time) try "date -d @1596441614" if you are using GNU date ***
W0803 16:00:14.464783 184954 init.cc:217] PC: @ 0x0 (unknown)
W0803 16:00:14.465371 184954 init.cc:217] *** SIGSEGV (@0x0) received by PID 184954 (TID 0x7fa8b1712700) from PID 0; stack trace: ***
W0803 16:00:14.468803 184954 init.cc:217] @ 0x7fa8b13213d0 (unknown)
W0803 16:00:14.472050 184954 init.cc:217] @ 0x0 (unknown)
Segmentation fault (core dumped)
CUDNN(7.6.5)

**Comment by littletomatodonkey** [comment]
Maybe you should try Paddle1.8.3 by using `paddlepaddle==1.8.3.post97`(gpu version) or `pip install paddlepaddle==1.8.3`(cpu version)

**Comment by ZhaoyangLi-nju** [comment]
> Maybe you should try Paddle1.8.3 by using `paddlepaddle==1.8.3.post97`(gpu version) or `pip install paddlepaddle==1.8.3`(cpu version)

Thanks a lot, 
Finally, using NCCL2.3.7+ solve my problem.

**Comment by lin1github** [comment]
> NCCL2.3.7+

excuse me,  can you show more detail about how to solve this problem, now I get the similar issue, need some help.

**Comment by lin1github** [comment]
> > Maybe you should try Paddle1.8.3 by using `paddlepaddle==1.8.3.post97`(gpu version) or `pip install paddlepaddle==1.8.3`(cpu version)
> 
> Thanks a lot,
> Finally, using NCCL2.3.7+ solve my problem.

excuse me, can you show more detail about how to solve this problem, now I get the similar issue, need some help.

**Comment by poormanfwh** [comment]
What's the final solution?　what's NCCL2.3.7?
i installed the paddle version1.8.3.but still got error "Segmentation fault(core dumped)"
