### ISSUE TITLE
lcnet scale0.35 预训练模型

### ISSUE THREAD

**Issue by limaopeng1** [PaddlePaddle/PaddleOCR#4660]
在使用ch_PP-OCRv2_rec_distillation.yml的配置文件，修改backbone的scale参数为0.35，训练会出现nanxx，你们可以提供backbone为 lcnet0.35的预训练模型吗

**Comment by littletomatodonkey** [comment]
你好，目前没有提供这个预训练模型，训练的时候需要保证batch size和lr等比例变化哈

**Comment by limaopeng1** [comment]
你好，请问训练的时候需要保证batch size和lr等比例变化是指？

**Comment by littletomatodonkey** [comment]
之前8卡xbs128对应学习率0.001，如果你是4卡xbs64，则学习率需要修改为0.001/2/2 = 0.0025，
