### ISSUE TITLE
ocr使用opt转换为nb模型后精度损失过大。

### ISSUE THREAD

**Issue by yangyukun0619** [PaddlePaddle/PaddleOCR#4662]
opt 命令./opt --model_file=/home/yyk/111/model --param_file=/home/yyk/111/params --optimize_out=/home/yyk/rec2.10  --valid_targets=arm --optimize_out_type=naive_buffer

目前已经验了三个版本的paddlelite，2.10,2.9,2.6,  paddleocr使用的develop分支，推理模型在pc端测试准确率都在99%左右，转换为nb模型后端侧部署测试准确率只有30%左右。以前的ocr模型转换后模型精度损失都在可控范围内，这次换了训练数据集后训练出来的模型在pc端表现比以前的模型好，但是转换为nb模型后端侧部署测试准确率下降了好多。

**Comment by 1220985305** [comment]
有相同的问题

**Comment by WenmuZhou** [comment]
你好，develop分支目前不更新了，可以试一下dygraph分支
