### ISSUE TITLE
train.py不适用命令训练的方式

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#4665]
tools/train.py
```
if __name__ == '__main__':
  device, logger, vdl_writer = program.preprocess(is_train=True)
  main(config, device, logger, vdl_writer)
```
`python  tools/train.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./pretrain_models/ResNet50_vd_ssld_pretrained.pdparams`

我想直接运行train.py  不带参数进来  
不用命令的方式   直接在源码写死

应该要怎么写？

**Comment by MissPenguin** [comment]
-o后的参数可以直接在yml文件里写死，yml文件也不想从命令行传入的话，可以把yml文件路径写死到代码里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/program.py#L393 。

**Comment by monkeycc** [comment]
```
    FLAGS = ArgsParser().parse_args()
    config = load_config(FLAGS.config)
```

这里应该要怎么写死YML

@MissPenguin

**Comment by s957995299** [comment]
在program.py对应的类中写需要的default
