### ISSUE TITLE
PGNet training (learning rate)

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4667]
Can I set decay epoch for PGNet to modify the learning rate during training?

**Comment by MissPenguin** [comment]
Sure, you can change other optimizing strategy here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/e2e/e2e_r50_vd_pg.yml#L43

**Comment by huylgia** [comment]
> Sure, you can change other optimizing strategy here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/e2e/e2e_r50_vd_pg.yml#L43

Ok tks
