### ISSUE TITLE
ocr模型评判标准

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#4672]
请问一下两阶段的ocr识别dbnet+crnn模型的评判标准是什么？达到什么标准可以用。

**Comment by LDOUBLEV** [comment]
> 达到什么标准可以用。

不太明白你的意思

**Comment by Sunyingbin** [comment]
> > 达到什么标准可以用。
> 
> 不太明白你的意思

比如说均方误差？以单个图片为单位，当识别的结果跟真实的结果对比达到90%以上，人为ocr训练的模型可用，否则将继续调参训练

**Comment by Sunyingbin** [comment]
> > > 达到什么标准可以用。
> > 
> > 
> > 不太明白你的意思
> 
> 应该说是召回率？以单个图片为单位，当识别的结果跟真实的结果对比达到90%以上，人为ocr训练的模型可用，否则将继续调参训练

**Comment by LDOUBLEV** [comment]
dbnet+crnn模型分别是单独训练的，
每个模型使用指标f-score(hmean),  precision, recall 作为指标，在我们自己的数据集上训练到最优指标后发布；

具体指标情况可以查看我们的技术文档：
https://arxiv.org/abs/2109.03144

**Comment by Sunyingbin** [comment]
> dbnet+crnn模型分别是单独训练的， 每个模型使用指标f-score(hmean), precision, recall 作为指标，在我们自己的数据集上训练到最优指标后发布；
> 
> 具体指标情况可以查看我们的技术文档： https://arxiv.org/abs/2109.03144

我理解这是不是两个指标，因为是两个模型，dbnet是单类别的检测用f1 score来评估（单纯的precision和recall应该不足吧），crnn用准确率来评估
