### ISSUE TITLE
模型微调问题

### ISSUE THREAD

**Issue by qingtianxiaoyu** [PaddlePaddle/PaddleOCR#4673]
识别模式是不是不支持fine-tune？如果识别模式想要微调，即针对一些特殊场景进行识别训练，是否需要覆盖字典中的所有字？需要多少的数据量才能达到比较好的效果？

**Comment by LDOUBLEV** [comment]
支持finetune，
如果默认字典中不包含你要识别的问题，那么建议你创建一个新的字典去训练，
所需数据量和你的场景以及要识别的字符数有关系，数据越多越好
