### ISSUE TITLE
Why there are so many `from __future__ import xxx` lines?

### ISSUE THREAD

**Issue by techkang** [PaddlePaddle/PaddleOCR#4675]
`from __future__ import xxx` is mainly used to convert from py2 to py3. However, the ppocr is mainly based on python3, so these lines are not necessory anymore. Is it correct? If it is correct, can I submit a pull request to remove all `from __future__ import xxx` lines?

**Comment by LDOUBLEV** [comment]
It is not recommended to modify it if it does not affect the usage.

**Comment by techkang** [comment]
Thanks for reply.
