### ISSUE TITLE
hwdb单字合成

### ISSUE THREAD

**Issue by yaofanji** [PaddlePaddle/PaddleOCR#4677]
大大们，请问一下怎么将hwdb的单字合成多字文本行呢，并且保证保持样本均衡以及lable长度小于25呢，并且不同单字图片的高度合成时如何统一？

**Comment by LDOUBLEV** [comment]
直接做图像拼接吧，高度不一致就resize？

> 保持样本均衡？

先统计每个字符的图像，归类后，采用均匀采样策略
