### ISSUE TITLE
PGNet: Training again error

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4678]
I expect to load trained model and continue the training again but the error as below figure. 
Can you help me solve this problem?
![image](https://user-images.githubusercontent.com/88916218/142224327-90d12375-107f-4b0c-a69c-871f295a66c0.png)

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/configs/e2e/e2e_r50_vd_pg.yml#L88

set as 

num_workers: 0
use_shared_memory: False

and run again.
