### ISSUE TITLE
关于文字检测模型的坐标点顺序

### ISSUE THREAD

**Issue by shengjie-shi** [PaddlePaddle/PaddleOCR#4679]
制作文字检测训练集时，可能会进行图片的90度，180度，270度旋转数据增强，此时坐标点根据[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/3495l)，应当仍按照文字阅读顺序顺时针标注吗？
例如原图：
![image](https://user-images.githubusercontent.com/55582615/142324310-ac03594f-e2b6-4cc8-9594-0ad4d8fd3613.png)
顺时针旋转90度：
![image](https://user-images.githubusercontent.com/55582615/142324887-ea3a66d3-12cf-4bc1-8f9f-57ac4cd585f2.png)
180度：
![image](https://user-images.githubusercontent.com/55582615/142325154-1f8de218-866d-4172-8d6b-ea1ba15f49cb.png)
270度：
![image](https://user-images.githubusercontent.com/55582615/142325500-447fe19d-1609-46d6-ab97-e2922376ccf2.png)

按照这个顺序标注是否正确？

**Comment by LDOUBLEV** [comment]
都按照1:左上，2 右上，3 左下，4 右下 就行

**Comment by shengjie-shi** [comment]
> 都按照1:左上，2 右上，3 左下，4 右下 就行

嗯好的，谢谢回复！
