### ISSUE TITLE
通用中英文模型增加字典应该如何训练，增加字典数800多个

### ISSUE THREAD

**Issue by UBUNTUHWB** [PaddlePaddle/PaddleOCR#4680]

**Comment by tink2123** [comment]
参考 加载预训练模型训练的文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/recognition.md#2-%E5%90%AF%E5%8A%A8%E8%AE%AD%E7%BB%83
