### ISSUE TITLE
PGNet: Dictionary config 

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4684]
How to set my dictionary in the config? I used to set "character type: ch" and charater_dict_path with my dictionary. 
My dictionary includes numbers and letters BUT when I predict on test image, the all output includes numbers not letters although the box captures the numbers and letters.
I don't know the problem comes from that I set charater_dict_path wrongly or another reason.

**Comment by LDOUBLEV** [comment]
The param of dictionary in config.yml is here.

https://github.com/PaddlePaddle/PaddleOCR/blob/8b3b7879c466e160567b59f0d388c25e97c7b44e/configs/e2e/e2e_r50_vd_pg.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L18
