### ISSUE TITLE
hubserving

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4687]
想转到后台运行，不影响当前命令行的输入，报这个错是怎么回事？谢谢各位
![image](https://user-images.githubusercontent.com/80818728/142373272-8591c547-fa38-4307-a769-5926612c8031.png)

**Comment by tink2123** [comment]
可能是 aistudio 的notebook页面不支持后台启动，可以试下在终端运行。

**Comment by zhangyingying520** [comment]
> 可能是 aistudio 的notebook页面不支持后台启动，可以试下在终端运行。

你好，这是在自己服务器上，通过jupyterlab运行的
