### ISSUE TITLE
CPU环境与GPU环境下多进程参数use_mp、total_process_num、process_id相关问题

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#4688]
1、use_mp表示是否使用多进程，total_process_num表示总进程数，process_id表示的什么意思？
2、在使用CPU和GPU两种场景下，开启多进程，是如何带来推理速度提升的？
3、CPU环境下开启多进程，默认使用CPU的几个核？单核还是多核？能否控制使用的CPU核数？
4、GPU环境下开启多进程，默认使用CPU的几个核？同时，开启多进程会不会造成GPU显存占用随着total_process_num参数变化成倍增长？

**Comment by ziyuwzf** [comment]
> 1、use_mp表示是否使用多进程，total_process_num表示总进程数，process_id表示的什么意思？ 2、在使用CPU和GPU两种场景下，开启多进程，是如何带来推理速度提升的？ 3、CPU环境下开启多进程，默认使用CPU的几个核？单核还是多核？能否控制使用的CPU核数？ 4、GPU环境下开启多进程，默认使用CPU的几个核？同时，开启多进程会不会造成GPU显存占用随着total_process_num参数变化成倍增长？

CPU环境下我设置--use_mp=True,--total_process_num=4,--process_id=0，单张图片推理时间没有明显降低，CPU利用率也与--use_mp=False,--total_process_num=4,--process_id=0时基本相似。CPU环境是windows10，单CPU，4核

**Comment by ziyuwzf** [comment]
CPU环境下分别使用以下两组参数进行推理：
--use_mp=True,--total_process_num=4,--process_id=0
--use_mp=False,--total_process_num=4,--process_id=0
发现无论--use_mp的值为True或者False，CPU的四个核是直接打满的，想确认一下这种现象是不是正常的？

**Comment by littletomatodonkey** [comment]
默认开启mkldnn，线程数是6，所以核的利用率是打满的（只有4核），use_mp表示开启多个进程进行预测，你可以使用top命令看下有多少个预测进程。use_mp为true，total_process_num时，应该有4个；use_mp为false时，应该只有1个，但是这个占用了4核的资源。
