### ISSUE TITLE
Nvidia Jetson TX2 运行出错

### ISSUE THREAD

**Issue by BruceXSK** [PaddlePaddle/PaddleOCR#469]
在使用Nvidia Jetson TX2运行PaddleOCR时使用CPU正常，但使用GPU时遇到
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: too many resources requested for launch
Aborted (core dumped)
```
模型加载时的参数使用的是config.txt文件中默认的参数
需要设置哪些东西能让tx2支持cuda运行PaddleOCR呢？谢谢

**Comment by AIpioneer** [comment]
您好！使用NV TX2的GPU，我们推荐使用Paddle Inference，您可以参考这几个文档https://www.jianshu.com/p/09a0fd569247，https://github.com/PaddlePaddle/Paddle-Inference-Demo, https://paddle-inference.readthedocs.io/en/latest/#

**Comment by LDOUBLEV** [comment]
> 在使用Nvidia Jetson TX2运行PaddleOCR时使用CPU正常，但使用GPU时遇到
> 
> ```
> terminate called after throwing an instance of 'thrust::system::system_error'
>   what():  parallel_for failed: too many resources requested for launch
> Aborted (core dumped)
> ```
> 
> 模型加载时的参数使用的是config.txt文件中默认的参数
> 需要设置哪些东西能让tx2支持cuda运行PaddleOCR呢？谢谢

运行的是deploy/cpp_infer的示例是吗，这个问题相关同学帮忙修复了，等 https://github.com/PaddlePaddle/Paddle/pull/25689 PR merge 后，可以重新编译预测库试试

**Comment by BruceXSK** [comment]
> > 在使用Nvidia Jetson TX2运行PaddleOCR时使用CPU正常，但使用GPU时遇到
> > ```
> > terminate called after throwing an instance of 'thrust::system::system_error'
> >   what():  parallel_for failed: too many resources requested for launch
> > Aborted (core dumped)
> > ```
> > 
> > 
> > 模型加载时的参数使用的是config.txt文件中默认的参数
> > 需要设置哪些东西能让tx2支持cuda运行PaddleOCR呢？谢谢
> 
> 运行的是deploy/cpp_infer的示例是吗，这个问题相关同学帮忙修复了，等 [PaddlePaddle/Paddle#25689](https://github.com/PaddlePaddle/Paddle/pull/25689) PR merge 后，可以重新编译预测库试试

好的 谢谢！

**Comment by wumeng2** [comment]
> 在使用Nvidia Jetson TX2运行PaddleOCR时使用CPU正常，但使用GPU时遇到
> 
> ```
> terminate called after throwing an instance of 'thrust::system::system_error'
>   what():  parallel_for failed: too many resources requested for launch
> Aborted (core dumped)
> ```
> 
> 模型加载时的参数使用的是config.txt文件中默认的参数
> 需要设置哪些东西能让tx2支持cuda运行PaddleOCR呢？谢谢

你好，你在tx2上现在可以使用gpu吗？我用的jetpack 4.4 dp包刷的，cuda10.2,cudnn8.0,编译完后测试运行直接报cudnn错误？谢谢

**Comment by wumeng2** [comment]
> > > 在使用Nvidia Jetson TX2运行PaddleOCR时使用CPU正常，但使用GPU时遇到
> > > ```
> > > terminate called after throwing an instance of 'thrust::system::system_error'
> > >   what():  parallel_for failed: too many resources requested for launch
> > > Aborted (core dumped)
> > > ```
> > > 
> > > 
> > > 模型加载时的参数使用的是config.txt文件中默认的参数
> > > 需要设置哪些东西能让tx2支持cuda运行PaddleOCR呢？谢谢
> > 
> > 
> > 运行的是deploy/cpp_infer的示例是吗，这个问题相关同学帮忙修复了，等 [PaddlePaddle/Paddle#25689](https://github.com/PaddlePaddle/Paddle/pull/25689) PR merge 后，可以重新编译预测库试试
> 
> 好的 谢谢！

你好，你在jetson 上用gpu 识别的结果对吗？我在gpu上跑的结果完全不对，有什么注意事项吗，谢谢

**Comment by BruceXSK** [comment]
> 你好，你在jetson 上用gpu 识别的结果对吗？我在gpu上跑的结果完全不对，有什么注意事项吗，谢谢

你好，我在TX2上用gpu识别的结果和cpu运行的结果一致的，没有遇到过什么错误
