### ISSUE TITLE
What's the limit word count in a picture in Training Recognition Models?

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#4691]
I'm training a recognition model (CRNN) which can recognize multiple words (Sentences by introducing white space char).
I gathered a training data which has 200k samples ranging between (1-8 words).

My question is what would make a good range is it more than that or bigger than that?
How many epochs usually used to train such a model on this dataset size?

**Comment by tink2123** [comment]
The longest character in the training sample shall not exceed 25.
The epochs can be set to 200-300 first, and then adjusted after observing the convergence.

**Comment by bely66** [comment]
Hi @tink2123, 
Thanks for your answer.
But how does the English model recognize lines/multiple words that exceeds 25 chars, more than 9 words?
is it a different model? not CRNN?

**Comment by soufieneghribi** [comment]
Same question. The detection model detects sentences, and the CRNN model is word level. How is this possible. Do you use a different algorithm? I didn't find it anywhere in the documentation.

**Comment by bely66** [comment]
I'm reopening this because I'm still struggling to understand how to train on sentence images

**Comment by bhavyajoshi-mahindra** [comment]
> I'm reopening this because I'm still struggling to understand how to train on sentence images

I am also struggling to understand how to train images having multiple words for recognition. I trained v4 recognition model which is giving good results in single word images but does not fails to correctly recognize multiple words in same image.

Do you find any solution?

**Comment by omarhassan97** [comment]
Same question

> Same question. The detection model detects sentences, and the CRNN model is word level. How is this possible. Do you use a different algorithm? I didn't find it anywhere in the documentation.
