### ISSUE TITLE
PPStructure seems not able to find the correct table layout

### ISSUE THREAD

**Issue by felixgao** [PaddlePaddle/PaddleOCR#4692]
I have a simple engine instantiated for structure
```python
table_engine = PPStructure(show_log=False, use_gpu=False, lang="en")
def recognize_structure(
    img,
    *,
    engine=table_engine,
    font_path="./fonts/simfang.ttf",
    draw_result=False,
    save_result=False,
):
    img_arr = pil_to_nparray(img)
    result = engine(img_arr)
    if save_result:
        save_dir = Path(__file__).parent.parent / "output"
        filedir = get_hash(img)
        save_structure_res(result, save_dir, filedir)
    if draw_result:
        im_show = draw_ppstruct_result_image(img, result, font_path=font_path)
        return result, im_show
    return result, ""
```
The result when saved is empty `res.txt` and the image is the entire file.
![5, 0, 588, 772](https://user-images.githubusercontent.com/1153820/142470982-729f74f1-1f29-49bf-9c43-4251e253b869.jpg)
the original image is 
![W2](https://user-images.githubusercontent.com/1153820/142471061-a8f7ab26-601b-41ac-aaaf-618817b1890c.jpeg)

**Comment by WenmuZhou** [comment]
It may be that the form is not detected in the layout part
