### ISSUE TITLE
PaddleOCR检测框训练报错

### ISSUE THREAD

**Issue by zhihaofan** [PaddlePaddle/PaddleOCR#4693]
![err](https://user-images.githubusercontent.com/59326288/142520976-4f210fc3-7454-4bac-a695-d38d99d8ae80.png)
![err1](https://user-images.githubusercontent.com/59326288/142520985-31145d9a-feae-436d-b19d-1bf1e8cab1b4.png)
如图，是这两个，第一个好像是什么问题吧，之前训练的时候也出现过，没有什么影响。
但是当我把检测框标记变大，就出现了下边的问题，显示内存不可读。
检测框标记如下图：
![001](https://user-images.githubusercontent.com/59326288/142521327-a0b925a8-7103-4907-bab7-992dd62456e9.png)
我是想训练一个只识别表格的检测框模型，本来是想直接用PPsturcture的表格检测的，但是效果不是很好，我看PPsturcture的也是调用了det模型，是我的操作有问题吗?

**Comment by WenmuZhou** [comment]
先单独跑一下数据集部分看看数据部分有没有问题，把这个放出来，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/tools/train.py#L132，上面那个注释掉

**Comment by zhihaofan** [comment]
> 先单独跑一下数据集部分看看数据部分有没有问题，把这个放出来，[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/tools/train.py#L132，上面那个注释掉](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/tools/train.py#L132%EF%BC%8C%E4%B8%8A%E9%9D%A2%E9%82%A3%E4%B8%AA%E6%B3%A8%E9%87%8A%E6%8E%89)

是把这个main(config, device, logger, vdl_writer)注释掉吗？
我注释掉了之后
![image](https://user-images.githubusercontent.com/59326288/145923504-cdbef01f-ad0a-4cb4-82c9-25e7183845f9.png)
z'g这个应该是正常的
