### ISSUE TITLE
有关车牌检测识别训练及测试效果的问题

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#4694]
用自己数据训练车牌检测，但是效果不佳，能帮忙分析一下吗？
具体情况如下：
自己的标签：
![image](https://user-images.githubusercontent.com/63723648/142521282-caebb26c-5992-4277-8f15-bb4143a45ff4.png)
训练完之后测试的结果，角度不太对：
![image](https://user-images.githubusercontent.com/63723648/142521610-2e562877-ecd8-4bc6-bf59-2131b24c6e89.png)

附件：
链接：https://pan.baidu.com/s/1gMuwyJWRNiAUgHJTipDsoA 
提取码：8cjr

**Comment by WenmuZhou** [comment]
你好，车牌检测建议使用east试试看

**Comment by wjrjsdx** [comment]
使用east训练的模型效果好了很多，但是使用whl预测的时候会报错：root ERROR: det_algorithm must in ['DB']

**Comment by chungkaihsieh-ui** [comment]
Hihi @wjrjsdx ，感謝您的分享。想請問實際用起來east 會比db慢很多嗎？  效果好很多是大概到什麼程度，我的DB跟你一樣邊邊角角都會收斂不好，h_mean at IOU(0.75) ~=0.8 左右，車牌檢測的task hmean 至少該多少請問您有comments?

**Comment by wjrjsdx** [comment]
> Hihi @wjrjsdx ，感謝您的分享。想請問實際用起來east 會比db慢很多嗎？ 效果好很多是大概到什麼程度，我的DB跟你一樣邊邊角角都會收斂不好，h_mean at IOU(0.75) ~=0.8 左右，車牌檢測的task hmean 至少該多少請問您有comments?

会慢，db一张图平均0.03s左右，east平均0.06s左右，效果的话边边角角可以收敛了，我这边特定条件拍照下的车牌检测recall和precision能到0.99,hmean=0.99，IOU训练中没有体现我这边用的是cover_thresh这个参数卡阈值，我这边设置的0.15左右。

**Comment by chungkaihsieh-ui** [comment]
> > Hihi @wjrjsdx ，感謝您的分享。想請問實際用起來east 會比db慢很多嗎？ 效果好很多是大概到什麼程度，我的DB跟你一樣邊邊角角都會收斂不好，h_mean at IOU(0.75) ~=0.8 左右，車牌檢測的task hmean 至少該多少請問您有comments?
> 
> 会慢，db一张图平均0.03s左右，east平均0.06s左右，效果的话边边角角可以收敛了，我这边特定条件拍照下的车牌检测recall和precision能到0.99,hmean=0.99，IOU训练中没有体现我这边用的是cover_thresh这个参数卡阈值，我这边设置的0.15左右。

了解，謝謝你!：)
