### ISSUE TITLE
文字识别文档复现  识别结果不对

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleOCR#4696]
按照文档复现
![image](https://user-images.githubusercontent.com/88479008/142551270-3f1a0dd1-11c3-4a11-b7b7-658dba18aac6.png)
结果是这样的
![image](https://user-images.githubusercontent.com/88479008/142551296-dc0b49e5-9446-48c3-b056-3f676d09314d.png)
结果不对

训练命令
python tools/train.py -c configs/rec/rec_icdar15_train.yml
python推理命令
python tools/infer_rec.py -c configs/rec/rec_icdar15_train.yml -o Global.pretrained_model=output/rec/ic15/iter_epoch_72 Global.load_static_weights=false Global.infer_img=train_data\ic15_data\test\word_1.png

配置文档未作更改

是什么问题？

**Comment by huylgia** [comment]
> 按照文档复现 ![image](https://user-images.githubusercontent.com/88479008/142551270-3f1a0dd1-11c3-4a11-b7b7-658dba18aac6.png) 结果是这样的 ![image](https://user-images.githubusercontent.com/88479008/142551296-dc0b49e5-9446-48c3-b056-3f676d09314d.png) 结果不对
> 
> 训练命令 python tools/train.py -c configs/rec/rec_icdar15_train.yml python推理命令 python tools/infer_rec.py -c configs/rec/rec_icdar15_train.yml -o Global.pretrained_model=output/rec/ic15/iter_epoch_72 Global.load_static_weights=false Global.infer_img=train_data\ic15_data\test\word_1.png
> 
> 配置文档未作更改
> 
> 是什么问题？

maybe leave "Global.load_static_weights=false"

**Comment by 534114658** [comment]
"Global.load_static_weights=false"
改为"Global.load_static_weights=true"或者删掉该项参数    结果一样

**Comment by 534114658** [comment]
这个是训练结束的状态
![image](https://user-images.githubusercontent.com/88479008/142577770-7e4351dd-d73d-41fb-aa59-3ed09cf9b88e.png)
这个  是否正常？

**Comment by 534114658** [comment]
这个是训练7200次的
![image](https://user-images.githubusercontent.com/88479008/142755701-ec08378b-84b8-4aec-894d-d05009f538ea.png)

训练集的图片可以识别    测试集的检测不出来 doc/imgs_words/en/word_1.png
![image](https://user-images.githubusercontent.com/88479008/142756167-707c54fe-b63a-46d1-88f5-44750dfaf9c9.png)

和训练文档默认72次效果差不多

word_122.png是训练集的文字  可以识别
![image](https://user-images.githubusercontent.com/88479008/142756002-9cd7a7b3-7f0b-4af2-a770-7965bc2ada99.png)

训练集的文字   编辑改个字就识别不出来
![image](https://user-images.githubusercontent.com/88479008/142756039-27dd2391-e522-4616-9097-ae62a8e15aa4.png)

是训练哪里出了什么问题吗？   或者是参数配置问题？
按原文档训练都训练不出来

**Comment by WenmuZhou** [comment]
你的数据太少了，我们这个英文模型是用st和MJ两个数据集训练的

**Comment by 534114658** [comment]
st和MJ两个数据集是哪2个？  在哪下载？
文档里面只说用ic15_data
![image](https://user-images.githubusercontent.com/88479008/142814375-c09a16e7-616e-4016-8041-93f15e36a800.png)

**Comment by zhangyingying520** [comment]
> st和MJ两个数据集是哪2个？ 在哪下载？ 文档里面只说用ic15_data ![image](https://user-images.githubusercontent.com/88479008/142814375-c09a16e7-616e-4016-8041-93f15e36a800.png)

人家还合成了很多数据

**Comment by 534114658** [comment]
一个是确定位置    一个是字符识别    都下载看下就知道该用哪个了

**Comment by 534114658** [comment]
换了个模型   训练及识别都正常
