### ISSUE TITLE
PGNet: parse error

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4698]
I am training PGNet on the Vietnamese dataset but the error happens as in the figure.
![Screenshot from 2021-11-19 11-06-30](https://user-images.githubusercontent.com/88916218/142563214-f5ccb0b7-406d-4d31-80bd-22eb1aafa6ad.png)

I hope you can fix it.

**Comment by WenmuZhou** [comment]
An error was reported when reading the data, you can look at the specific error message here https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/ppocr/data/pgnet_dataset.py#L95
