### ISSUE TITLE
PGNet: Config error (pad_num)

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4699]
At the present, I am training for the Vietnamese dataset whose dictionary includes 230 characters. In the config, the pad_num parameter is the length of the dictionary for pad and I set "pad_num = 230" BUT error.
![Screenshot from 2021-11-19 11-35-19](https://user-images.githubusercontent.com/88916218/142565893-dbeb6911-af7a-4195-b84c-1829b5293662.png)
I see that sequence width always is 37. Can I change it? 
I hope you can help me.
P/s: This is my dictionary 
[generated_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7576643/generated_dict.txt)
Best regard!

**Comment by WenmuZhou** [comment]
您好，这里有说明哦，
```shell
pad_num: 36 # the length of dict for pad
```
换成你字典的长度就好

**Comment by huylgia** [comment]
> Xin chào, có hướng dẫn ở đây,
> 
> ```shell
> pad_num: 36 # chiều dài của dict cho pad
> ```
> 
> Chỉ cần thay đổi độ dài từ điển của bạn

I set but error as above figure.

**Comment by huylgia** [comment]
> > Xin chào, có hướng dẫn ở đây,
> > ```shell
> > pad_num: 36 # chiều dài của dict cho pad
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Chỉ cần thay đổi độ dài từ điển của bạn
> 
> I set pad_num but error as above figure.
