### ISSUE TITLE
识别结果问题

### ISSUE THREAD

**Issue by LayBrick** [PaddlePaddle/PaddleOCR#4700]
用paddleocr进行了铭牌识别，发现对表格的识别表现不好，想问下如何调整呢？
![0081](https://user-images.githubusercontent.com/91247260/142578593-d6f8cd05-4142-4997-9cbf-8299a48a01c6.jpg)

**Comment by WenmuZhou** [comment]
您好，可以先进行一下图像矫正，提高图像输入的质量
