### ISSUE TITLE
ch_ppocr_v2.0 和 ch_PP-OCRv2 的区别

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#4701]
ch_ppocr_v2.0 和 ch_PP-OCRv2 的区别

**Comment by WenmuZhou** [comment]
ch_PP-OCRv2 是最新发布的ppocr系列模型，在精度和速度上都有很大提升
ch_ppocr_v2.0的动态图版本的ppocr1.0系列模型
