### ISSUE TITLE
重新提下以前的问题：paddleOCR 经过paddlelite后精度下降

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/PaddleOCR#4703]
1. 

- **首先我的模型是使用paddleOCR-dygradh分支训练的，文字检测模型配置文件为det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml，文字识别配置文件为rec_chinese_lite_train_v2.0.yml。均使用了官方提供的预训练模型进行训练。**

2. **在训练好模型之后，使用python3.7 tools/infer/predict_system.py  对模型进行串联预测，发现准确率和召回率都很高！下图为结果：**

![image](https://user-images.githubusercontent.com/74039253/142600694-e551d756-e019-44c6-bfcc-2a95c43f8862.png)
![PC](https://user-images.githubusercontent.com/74039253/142600739-2e7c67ff-2997-47b3-b37b-5e8f6206ce31.jpg)

- 

** 但是经过paddlelite模型蒸馏之后，部署在安卓端上，模型的准确率就下降了。我使用的是终端opt模型转化方法，命令为：**
paddle_lite_opt --model_file=output/inference.pdmodel --param_file=output/inference.pdiparams --optimize_out=./ssd --valid_targets=arm --enable_fp16=false --quant_model=true --quant_type=QUANT_INT16

**检测结果如下图：**
![image](https://user-images.githubusercontent.com/74039253/142602008-fe2e9f50-b534-4bf4-bfd6-a09130d35c54.png)
![端侧](https://user-images.githubusercontent.com/74039253/142602079-f3f7230c-4e38-49a7-92e5-0008a55f0f18.jpg)

**Comment by WenmuZhou** [comment]
您好，量化会带来精度损失，在转换lite模型时，将量化关闭试一下看看

**Comment by 1220985305** [comment]
好的，亲测有效！谢谢paddle官方！

**Comment by 1220985305** [comment]
**我试着将量化关闭，使用如下命令转NB文件：**
**./opt --model_file=output/inference.pdmodel --param_file=output/inference.pdiparams --optimize_out=./ssd --valid_targets=arm --enable_fp16=false --quant_model=false --quant_type=QUANT_INT16**
**发现结果仍不理想**
**下图为我在linux上编译后，测试的结果**
<img width="934" alt="lALPJxRxPW8GnarNBJTNB0w_1868_1172" src="https://user-images.githubusercontent.com/74039253/144186251-ff290f9e-233c-4836-aadc-109f92e8767b.png">
**这张是我用导出的模型使用模型串联命令，得到的结果：**
**!python3.7 tools/infer/predict_system.py --image_dir="./infer/" \
--det_model_dir="./inference/screen_det/" \
--rec_model_dir="./inference/rec_screen/"**
![Picture_2021112010213000img_cmp_286330_27363648](https://user-images.githubusercontent.com/74039253/144186649-83a87532-2e6c-4b21-8e9f-0e23c67d97e2.jpeg)

**Comment by 1220985305** [comment]
希望paddle继续跟踪
