### ISSUE TITLE
infer_rec的结果错误问题

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#4704]
python tools/infer_rec.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.pretrained_model=ch_PP-OCRv2_rec_train/best_accuracy Global.load_static_weights=false Global.infer_img=doc/imgs_words/ch/word_1.jpg
执行上述不能得到正确的结果，并且每次结果都不一样，ch_PP-OCRv2_rec_train这个模型来自官网

**Comment by WenmuZhou** [comment]
看看完整日志看看

**Comment by lgcy** [comment]
> 看看完整日志看看

![IMG_1](https://user-images.githubusercontent.com/26407517/142965755-acfe6791-1d94-4c2a-9838-37360e012ecd.jpg)
![IMG_2](https://user-images.githubusercontent.com/26407517/142965784-f989d672-7aba-4c5c-bf19-f257409ac58e.jpg)
