### ISSUE TITLE
Ubuntu部署paddlehub serving 后，post返回Invalid base64-encoded string

### ISSUE THREAD

**Issue by Eunsolfs** [PaddlePaddle/PaddleOCR#4708]
### paddleocr用的是github的最新源码，web服务是启动成功了的
> root@VM-0-7-ubuntu:/usr/PaddleOCR# hub serving start -m ocr_system -p 8868 --use_multiprocess
> [2021-11-20 10:49:20,601] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
> ---    Fused 0 subgraphs into layer_norm op.
> ---    fused 0 pairs of fc gru patterns
> ---    Fused 0 subgraphs into layer_norm op.
> ---    fused 0 pairs of fc gru patterns
> ---    Fused 0 subgraphs into layer_norm op.
> ---    fused 0 pairs of fc gru patterns
> [2021-11-20 10:49:21 +0800] [207850] [INFO] Starting gunicorn 20.1.0
> [2021-11-20 10:49:21 +0800] [207850] [INFO] Listening at: http://0.0.0.0:8868 (207850)
> [2021-11-20 10:49:21 +0800] [207850] [INFO] Using worker: sync
> [2021-11-20 10:49:21 +0800] [207875] [INFO] Booting worker with pid: 207875
> [2021-11-20 10:49:21 +0800] [207877] [INFO] Booting worker with pid: 207877
> [2021-11-20 10:49:21 +0800] [207878] [INFO] Booting worker with pid: 207878
> [2021-11-20 10:49:21 +0800] [207879] [INFO] Booting worker with pid: 207879
> [2021-11-20 10:49:21 +0800] [207880] [INFO] Booting worker with pid: 207880

***

### 下面是post的返回值

> {
>     "msg": "Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4",
>     "results": "",
>     "status": "101"
> }

***

**Comment by Eunsolfs** [comment]
下面是我post的json数据

> {
>     "images":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASMAAAAfCAIAAAAjjTwYAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAEXRFWHRTb2Z0d2FyZQBTbmlwYXN0ZV0Xzt0AAApbSURBVHic7ZxNaNxIFsdfWW0ndjNLwDBI5KJLBi+GMOxlSzAHgW9hQH0YFgkMMb6MD8ZmLqYazA6zGFrkEmz64LkYBwwSyxwk2KtBh4WuXJZMoFmzuWhhF4kFQ4jpdmK3rD1Ian20ut2Jx50wUz980EepVPVU/3qvXjVGYRgCg3ED/vqP3vd/u/jX/367A+mLz9EPX8/86Q+VEWUQUxrjhvz+L93fsswivvgc/fPPcyMKTE2sKYxfK0xmMIYRmNIYjEnAlMZgTAKmNAZjEjClMRiTgCmNwZgEBaX5Zg0No2b6cSmqDy1UVtw3a+lJ9LROr20Z1VH2qUEK1UaP5Cseo6E6HbdDUdmBorqZ2EzX9UzBbPuG1j/CDnFnqI5G2eFaK6XGGsvqjNuiZK+t0QoJLl70zdpa/wSTMCT5m4KGyx4bgOpIqgOAhOoDL6Q6cuQhlVAd6aJnqXx6iVf31ZpQg/iqb9YkaIXFpxUj/1SxVqesQ2WvS1gxFBCtFbd2KFqygxxZVYmqRo0nYUj6lWbah0kYyoXeUR1JII+0GHV9UEkYUh3pdBzrDodXLQ9qQs0cYY0JI989/Ya7N+xuN/hu6+0ewMF29fHIBp/QzuIRbGzOPX2A0ouvAv4Bdw/gdTe8N4cAQuen7pIDsDx7On85v9uD5dkADwR0yUtvgxKl1bMqyKAY+4MXE+WAooJZQxpkBzbVkQStcCV/mtkqpzqSqLESDyFMWg5CaEDpvlkTNDA8wicnduauLSAtPUmb3miFBABsLRGjb9YElyR1Ux3pojFk8FKnrqhe+QfmVWvF98EFAApySDBQveauEABwzZojWnK2aMtFh1QlGAATz62hmupZKh/12wv7lhroVUymb4ganqW6ib2HlEo6XlYMoGAtGDKtTgz/ktu5KLsx034Sy2B1p7Oavd7knq+frw48sHcafnvaXYTZNpwvwuzpfG9+/e3G5ty3p935o8rxk5m43NG5vV1tL/cWj845mA3EoN+Ag+2qcta7JZlB6Tqt0QoH8QwlXyqOM3XRC8Ow1QAAUbXCcB/W0tARk7AFku4AADg60kUvlJ00tkJIglaYnWMxCT2DSrkoh+qCS8J+MV61SppXQjyAFKOlmmumD75j2g1w4hCKOnVFlcXBDiGEEJLqYGtCWZxHdYSQIAiCZtclSZIQQjrI2HRcABBlleqmmzUTJulI5tV9AzQhtlrRtyiGV7R4/lLyQO5qqzFwHr+29Hb/avKRP6LMAAC49vYMAMDybLAdi2Fjc+50MzcsNzbngmY1aFaD5vQCTD2Oj6tBc+5YTgodXfri3Q0AgJm2GMz/XDmNKpy/287XtrpzCQ/vbgDA0fl3Z5Vgewagcvykqpy9m9/t3V5XS5RWl0oWFJkZNxqSa7Cf/fwJsRCIK0RqwyQkMgCATEJL5QETz6BS//nMh47XMoJmRy1IRrtU77coO9pz1Ew/XbL4Zi23IhHVfdVc0w9NMFYIaYGk01hoA06rdJLJTTOYRMO30VCSJwjGxFLFuPfxUb+RNdNP2xsbLZmP0jlpNMUejQ+WG7bpFN5AnXpjdNg6MYIfzyrtZTgQkXPGnW5WACrKfXjx81Wh3OtX77j1TuHvWaZfB9t3ZJ57iqcW8PQCPx08ghfAKQBwegX3ufyHvlhMQsS93d4JPx007/AvO7cqMxhQ2iiPkfcqOYlhUpAcJgMiTMZbKtH8AEqm4SHknWp2oo6n8RHwKsH1OqgyD4BJCyQk1Rtk5HplSKaB6gghRw6tFTGSpewM0Qom/aalPbNUHqiOdDc1c99KOScamcV2XQAAeqjZHyoNvGJAXmq+qacB+0dnb/fCf1h9/Lsre/fc/uxOe7Py5ZvekjO0/MbmXHu55PrqTof7KTjphgBwQjvc1tulnXMbAOBicesy6f9Mu1kNmtX2cnwQNLnn6x1uvfNcjP3k6eaoXwnfhFRpY+bf4nE1KklZmKjpoWYDuG6sqXRE9d3X+0/Y2WFZviDJ4bsUIJncsdwA+MCRi4lnKHUJIUGzY8/bICoPvqnHrUiPsmSMm/HRuZ73J4945uBFDNT1wTf1eqP1wVEerxKsrWXywGsaHj3JTJie/d8Q3lztRXHdA853S1du17E8GzyCH1+GJ7TzXBwmmIvF9c53r8LogFvvcOvnqzDTbs7CTuwnb8+zpUob9CmeoQzGUxlPNSTWyvkY36xFShBVKww9Q8k8lNZPMFwn3nzC4L18mm+uaWC0DNAOaSQFRSksBsvA4pDx2Gj1e+IZSpTOcHEDAKiO1kAtaU/GuJlFUtgPn13XHnidKCq265hrGuRdUM75FVeUJdMOJi2sCTqNGmqq3kdem+WR735//8qByrEMIE/xAPz8KK/y5Wfg/2fw8kwbT8FcFD1WH/Nw735lY3k2ykYebN+RS35k33dr2bVfZuH3SzOwTiuETflF21hbNxmSMZ4Efry6Lxb3vPqMznXko8f38WnOoWY3iIrVfYPqtZpgqp5lkUZdH96ZcseUkPFpgmaDc2iqHpEBwHGglazTcmTjhbxPi7ya7+ZNoogiAC+rSl3TcMtS+ex3GScjkifKTCEkmOqnk+QHAICp40ec//Lt0t+vvvzq7vGjqRc/vXtxf/pgaPmZP5a3/mKRXr1+9Y6jVye0w9Gr12/Q9w/DZ6/CBVxVzi6dbtkjsVu7PIGrZ/Fxd0TgekMGdq71em4yz/ut9/xM9FDDhaHHq1YLRozxMRnfp9malgRfvEqwHQ9cTFpYO3TyLYs9DNUFDYyWqCdKSG8BwIBPk0liFpmUuQvXNIHktJAzKsFRWjQJZ/uq8x3TjkUXXcUiP7giLpDNdfaJAgtFUWxN+KS2r3lOhuDHIwDn7Q9nU/zL7pLTW3oJj7e5bKm93W4U1B1sT/OvevAoWmvB6k5OGPce3Anw1AKuBngKzi7nt96+ADihnfndYn4FYOb4yZB8ZpIC/cXJKi3at2o0qDTeyqk0SZn1MaWfHTApGyvXLRNLt5sK9ZYNQsXw0kZkG9TPig40Itp7wJGL9SLBFf18xqeNxtYkVxwdrsUZjzh6FjS7QVRXR4KGW54B0SLLdT8kKRIbNUpCWZYVhpFzQ5/I70X8Sy5NA3YXjwAA4Oic2wmKJZdng2aUiL9Y2upw6+/8h8VgL+vTRr92AXP/3upyJT6tM2R/7xegr7Q4hg8tQqz4e6QZi/IAcpx1WilpQj8dPdekHgc39Pr1SIkXzgzV0YOyvyKU6oooZs4dOXEzfYrbFvl+e4YCrllDCEn1hgx6plIA8F2aE/oQaziR002jZ9mJNrYJ5lXLU00hqv49hBZbOO5PYcsyeccnI7iUZOtseuHN1R5AtNMVNKuBGOTTFb2lrQ633uO/ScWW82lQaTerTx8AiHNB844MV7YTlaoo98NnZXvftw377waMm8Ktdz52Ez4JgmZ1xF32W34GYxIwpTEYk4ApjcGYBExpDMYkYEpjMCYBUxqDMQmY0hg35YvP0fWFfu1cawSmNMZN+eHrmd+42KL/yz+6DNu5ZjAmAfNpDMYk+D/cYaKL68w5JAAAAABJRU5ErkJggg=="
> }

**Comment by littletomatodonkey** [comment]
这个图片直接使用python inference可以正确预测或者识别吗？可以先确保图片是没有问题的

**Comment by Eunsolfs** [comment]
## 一、服务器上的图片进行测试
### 自己截了一个png图保存到了服务器（放在了/doc/imgs/目录下  并命名为p1.png）
**这是图片↓↓：**
![image](https://user-images.githubusercontent.com/53815751/142735657-6478b02c-6d18-42eb-b78c-0524346e8be0.png)
### 进行测试，测试成功
![image](https://user-images.githubusercontent.com/53815751/142735457-2b308e01-11b9-4a71-8554-4d350c8afb37.png)
### 另一个ssh上显示本次OCR的相关信息了：
![image](https://user-images.githubusercontent.com/53815751/142735475-2ed53be6-769b-4582-8489-590c34a1f122.png)
### 换了个图片测试（/doc/imgs/00006737.jpg）：
![image](https://user-images.githubusercontent.com/53815751/142735540-fa0e7b72-dd96-42c7-bb52-16a05f206b87.png)
### 另一个ssh上显示报错了：
![image](https://user-images.githubusercontent.com/53815751/142735614-56aee17c-f61f-4f9a-94ea-bb7b550d39e1.png)

***

## 二、使用postman进行post测试
### 1.到网页进行图片转码base64
![image](https://user-images.githubusercontent.com/53815751/142735774-36ca9455-56fc-4fc7-9926-8a6544751c73.png)
### 2.postman 进行post测试，提示“Invalid base64-encoded string”
![image](https://user-images.githubusercontent.com/53815751/142735827-c00e9534-5b45-47ff-a347-62c9be3c3052.png)
### 我还测试了其他工具（C++，C#）将图片转成base64，然而都是“Invalid base64-encoded string”

**Comment by bikerr** [comment]
> 去掉前缀试试 `data:image/png;base64,`

**Comment by yiliang-yl** [comment]
我也遇到这个问题怎么解决的？

**Comment by yiliang-yl** [comment]
> 我也遇到过这个问题怎么解决的？

知道了，把images 当一个数组传输

**Comment by Eunsolfs** [comment]
> > 我也遇到过这个问题怎么解决的？
> 
> 知道了，把images 当一个数组传输

你好, 可以贴一下相关代码么, 我后来也没能解决_(:з」∠)_

非常感谢

**Comment by yiliang-yl** [comment]
> 



> > > 我也遇到过这个问题怎么解决的？
> > 
> > 
> > 知道了，把图片当一个数组传输
> 
> 你好, 可以一下相关代码么, 我以后没能解决_(:з」∠)_
> 
> 非常感谢
{
    "images":["1"]
}


> > > 我也遇到过这个问题怎么解决的？
> > 
> > 
> > 知道了，把images 当一个数组传输
> 
> 你好, 可以贴一下相关代码么, 我后来也没能解决_(:з」∠)_
> 
> 非常感谢

![image](https://user-images.githubusercontent.com/59381726/144007005-deff8a7a-8fe5-4cf1-b510-fd44e3499a98.png)
这没代码呀，就把images 当一个数组传输。不过我发现返回值有问题，没识别出来。

**Comment by yiliang-yl** [comment]
> > 我也遇到过这个问题怎么解决的？
> 
> 知道了，把images 当一个数组传输

前缀去掉
