### ISSUE TITLE
install on win server 2008r2 

### ISSUE THREAD

**Issue by bouyeijiang** [PaddlePaddle/PaddleOCR#4712]
Failed to build fasttext
Installing collected packages: fasttext, cython, paddleocr

**Comment by littletomatodonkey** [comment]
可以试下这个链接里的解决方案

https://github.com/facebookresearch/fastText/issues/753#issuecomment-476792284

**Comment by bouyeijiang** [comment]
没找到解决的,使用whl安装对于的是3.8的版本的fasttext成功后还是错误，
