### ISSUE TITLE
请问是怎么解决的呢

### ISSUE THREAD

**Issue by 1350783396** [PaddlePaddle/PaddleOCR#4717]
是的，万分感谢，已经解决了。

_Originally posted by @zhongweidi993 in https://github.com/PaddlePaddle/PaddleOCR/issues/4269#issuecomment-940662319_

**Comment by zhongweidi993** [comment]
> 是的，万分感谢，已经解决了。
> 
> _Originally posted by @zhongweidi993 in [#4269 (comment)](https://github.com/PaddlePaddle/PaddleOCR/issues/4269#issuecomment-940662319)_

下载对应的tensorrt版本，把bin里的dll文件复制到你编译生成exe的路径下

**Comment by 1350783396** [comment]
需要先配置tensorrt环境吗

**Comment by zhongweidi993** [comment]
> 需要先配置tensorrt环境吗

不需要

**Comment by 1350783396** [comment]
![image](https://user-images.githubusercontent.com/67899592/142815808-38529815-43ea-4827-b78f-e381f382a92c.png)
tensorrt的dll放入后还是报错

**Comment by zhongweidi993** [comment]
兄弟，你这编译有问题啊，去好好跟着官方文档操作一遍吧

**Comment by 1350783396** [comment]
![image](https://user-images.githubusercontent.com/67899592/142965022-4ae9b8ab-f868-4299-9774-47921197fa20.png)
