### ISSUE TITLE
RuntimeError: MKL_Free_Buffers not found.

### ISSUE THREAD

**Issue by Eric-Hjx** [PaddlePaddle/PaddleOCR#4720]
paddleocr版本：2.3.0.2
运行paddleocr报错：
```
Traceback (most recent call last):
  File "demo.py", line 49, in <module>
    result, output_im = ocr.Process(img) # blacklabel laser
  File "OCR.py", line 84, in OCR.OCR.Process
  File "paddleocr.py", line 379, in ocr
  File "tools\infer\predict_system.py", line 60, in __call__
  File "tools\infer\predict_det.py", line 213, in __call__
RuntimeError: MKL_Free_Buffers not found.
[10252] Failed to execute script 'demo' due to unhandled exception!
```

4台配置相同的电脑上有一台会出现这样的情况，查看其他人之前提出同样的issues也没有很好的解决方法，请问现在这个问题解决了吗？安装的paddleocr是直接使用pip安装的，也没有自己编译whl。

**Comment by LDOUBLEV** [comment]
应该是这台电脑没有安装MLKDNN或者这台电脑的CPU不支持mkldnn吧

可以试下关闭mkldnn选项后是否能正常预测：
enable_mkldnn=False
https://github.com/PaddlePaddle/PaddleOCR/blob/ccf749e3ee7ca5b91bf5668aeded26d4ca908f23/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L104

开启mkldnn在可以CPU上加速预测

**Comment by JH-Lam** [comment]
感觉是与 paddlelite包冲突，后者的包不要在全局位置导入， have a try

**Comment by sharoseali** [comment]
Then the issue should be open. Any hints on how to proceed ? @JixuH, can you reopen this issue?

**Comment by 616tree** [comment]
MKL_Free_Buffers not found如何解决
