### ISSUE TITLE
C++ 部署编译报错

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#4722]
按照 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md 教程手动编译 v2.9 版本的 so文件

在 demo/cxx/ocr 执行 make -j 时报错：

NDK_NAME: android-ndk-r17
NDK_VERSION: 17
HOST_NAME: darwin
HOST_TARGET: darwin-x86_64
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/Users/ddz/Library/android-ndk-r17c/sources/android/support/include -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include  -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -o ocr_db_crnn.o -c ocr_db_crnn.cc
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/Users/ddz/Library/android-ndk-r17c/sources/android/support/include -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include  -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -o clipper.o -c clipper.cpp
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/Users/ddz/Library/android-ndk-r17c/sources/android/support/include -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include  -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -o crnn_process.o -c crnn_process.cc
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/Users/ddz/Library/android-ndk-r17c/sources/android/support/include -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include  -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -o db_post_process.o -c db_post_process.cc
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/Users/ddz/Library/android-ndk-r17c/sources/android/support/include -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include  -I/Users/ddz/Library/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -o cls_process.o -c cls_process.cc
<built-in>: In function 'float abs(float)':
<built-in>: warning: conflicts with previous declaration here [-Wattributes]
/Users/ddz/Library/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++ --sysroot=/Users/ddz/Library/android-ndk-r17c/platforms/android-21/arch-arm64 -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -frtti -std=c++11 -O3 -DNDEBUG -fPIE -fopenmp -pie -Wl,--gc-sections ocr_db_crnn.o crnn_process.o db_post_process.o clipper.o cls_process.o -o ocr_db_crnn  ../../../third_party/opencv4.1.0/arm64-v8a/libs/libopencv_imgcodecs.a ../../../third_party/opencv4.1.0/arm64-v8a/libs/libopencv_imgproc.a ../../../third_party/opencv4.1.0/arm64-v8a/libs/libopencv_core.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/libtegra_hal.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/liblibjpeg-turbo.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/liblibwebp.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/liblibpng.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/liblibjasper.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/liblibtiff.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/libIlmImf.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/libtbb.a ../../../third_party/opencv4.1.0/arm64-v8a/3rdparty/libs/libcpufeatures.a -L../../..//cxx/lib/ -lpaddle_light_api_shared /Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a /Users/ddz/Library/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a /Users/ddz/Library/android-ndk-r17c/platforms/android-21/arch-arm64/usr/lib/libstdc++.so -latomic -pthread -ldl -llog -lz -static-libstdc++
../../..//cxx/lib//libpaddle_light_api_shared.so: undefined reference to `stderr'
collect2: error: ld returned 1 exit status
make: *** [ocr_db_crnn] Error 1

**Comment by LDOUBLEV** [comment]
develop分支不在维护了，如果你要用动态图模型，参考这个教程吧：
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/deploy/lite/readme.md

**Comment by txlei** [comment]
> If you want to use a dynamic graph model, please refer to this tutorial:

also encountering this issue with stable branch `release/v2.10`. what do you mean by using dynamic graph model? 

similiar error when doing `make -j`
```
.../android-ndk-r17c/platforms/android-21/arch-arm64/usr/lib/libstdc++.so -latomic -pthread -ldl -llog -lz -static-libstdc++
../../..//cxx/lib//libpaddle_light_api_shared.so: undefined reference to `stderr'
```

how do i solve this error to compile and get the executable file ocr_db_crnn?

thank you
