### ISSUE TITLE
paddle2.0训练出来的模型在paddle2.1的环境下无法识别？

### ISSUE THREAD

**Issue by zero20121222** [PaddlePaddle/PaddleOCR#4724]
paddle2.0训练出来的模型，无法在paddle2.1的环境下运行这是什么情况，需要怎么调整吗？

**Comment by zero20121222** [comment]
我看了下release2.1新增了一些参数例如：det_db_score_mode，这些对2.0有影响吗？

**Comment by tink2123** [comment]
应该是可以识别的，请问是哪个模型，没有识别是指报错吗？报什么错误
