### ISSUE TITLE
请问想要给方向分类器增加更多角度识别应该怎么操作？比如顺时针90度和逆时针90度？谢谢！

### ISSUE THREAD

**Issue by redearly123** [PaddlePaddle/PaddleOCR#4726]

**Comment by tink2123** [comment]
在配置文件中增加 角度 类别：https://github.com/PaddlePaddle/PaddleOCR/blob/ccf749e3ee7ca5b91bf5668aeded26d4ca908f23/configs/cls/cls_mv3.yml#L16

**Comment by redearly123** [comment]
> 在配置文件中增加 角度 类别：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/ccf749e3ee7ca5b91bf5668aeded26d4ca908f23/configs/cls/cls_mv3.yml#L16

好的谢谢

**Comment by Currf** [comment]
> 在配置文件中增加 角度 类别：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/ccf749e3ee7ca5b91bf5668aeded26d4ca908f23/configs/cls/cls_mv3.yml#L16

请问是直接增加类别就行了吗？算法不用修改吗？
