### ISSUE TITLE
文字方向检测模型，训练出现问题

### ISSUE THREAD

**Issue by SueV1** [PaddlePaddle/PaddleOCR#4729]
![81F0A4BE-7D43-4b90-B5E4-82BED8B2627D](https://user-images.githubusercontent.com/40711395/142994854-1856e3db-0547-4963-9499-4b1ab09d543a.png)
![77C278D4-137C-4793-8DBE-5F2742DE489B](https://user-images.githubusercontent.com/40711395/142994870-20e75b90-5efc-4bcd-a6aa-4c2054fcdece.png)

**Comment by tink2123** [comment]
看起来是数据读取出了问题，可以先跑一个单卡训练，把num_worker修改为0，看下具体的报错信息
