### ISSUE TITLE
flask框架嵌套问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#473]
个人想搭建测试web接口请求，falsk不知道为啥会加载2次模型，不知是我代码问题还是啥

这么写，我启动端口服务的时候可以起开并访问。

但是调用时又加载一次模型文件
![image](https://user-images.githubusercontent.com/57654726/89194305-c486a780-d5d9-11ea-9377-7718fde8f313.png)
，

**Comment by LDOUBLEV** [comment]
你是怎么封装hub的服务接口的，调用的是哪个文件运行

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/89246313-760af480-d63d-11ea-8368-e69b5d341354.png)
我这么写的，不知是否哪里出现问题
