### ISSUE TITLE
请问检测训练支持人为添加反例吗？

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#4730]
比如我想训练一个车牌文字检测，但是经常会将图片中的无关文字检测成车牌或者说一张没有车牌的图片上面检测到了车牌，我可以人为添加这种没有车牌的图片的空标签吗，告诉网络这种文字我不需要。

**Comment by LDOUBLEV** [comment]
可以的

**Comment by wjrjsdx** [comment]
> 可以的

我应当怎么添加呢

**Comment by LDOUBLEV** [comment]
不标注就行

**Comment by wjrjsdx** [comment]
> 不标注就行

可以这样理解吗，训练文件yml里面data_dir参数中填写的路径内假设有100张图片，label_file_list参数填写的标注文件中只标注了80个，剩下的20个就代表是这种反例，它也参与了训练。
