### ISSUE TITLE
训练ch_PP-OCRv2/ch_PP-OCR_det_cml中途中断

### ISSUE THREAD

**Issue by lxhmark7** [PaddlePaddle/PaddleOCR#4734]
![image](https://user-images.githubusercontent.com/87002039/143013881-193396c7-5448-4844-b835-77eede5241f5.png)
每次在训练过程中eval的时候，总是内存溢出断掉，请问有没有人遇到过同样的问题？

**Comment by tink2123** [comment]
可以尝试减小 eval 的batch_size

**Comment by Atiuiee** [comment]
请问楼主解决了吗，我也是每次eval的时候就报这个，eval的batch_size为1，train的batch_size为4，11G的显存

**Comment by lxhmark7** [comment]
rain和eval 的batch_size都为1,结果还是断掉，内存15G呢
