### ISSUE TITLE
关于ch_PP-OCRv2的识别

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#4735]
1. ch_PP-OCRv2的best_accrucy模型里面有student和teacher模型，进行infer_rec.py推理时，会采用哪个模型推理？
2. ch_PP-OCRv2识别的知识蒸馏训练，student和teacher模型都是初始化参数进行训练的吗
3.  ch_PP-OCRv2关于识别有更加详细的使用文档吗

**Comment by littletomatodonkey** [comment]
1. 默认2个模型都会预测的，可以修改这里，去选择自己希望使用的模型


https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L103


2. 都是随机初始化，然后同时训练的
3. 可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/knowledge_distillation.md

**Comment by zhangyinzhangyin** [comment]
> 1. 默认2个模型都会预测的，可以修改这里，去选择自己希望使用的模型
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L103
> 
> 2. 都是随机初始化，然后同时训练的
> 3. 可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/knowledge_distillation.md

能否告知ppocr-v2 检测部分的训练流程，我训练cml结尾的配置文件，结果一直为0
