### ISSUE TITLE
paddle   总是能够冒出个环境错误，为啥环境老是不稳定呢，按照安装步骤重来没有一次通过,  能不能把运行环境整明白点

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#4737]
cuda 10.2 cudnn 8.0.4,paddlegpu 2.2.0

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637677945 (unix time) try "date -d @1637677945" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 17772 (TID 0x7f77ff295740) from PID 0 ***]

段错误 (核心已转储)

**Comment by cqray1990** [comment]
这个运行环境paddle只能是2.0.0?

**Comment by cqray1990** [comment]
@tink2123 @ZeyuChen @bingooo @karlhorky 能不能解答一下，paddle验证安装没有问题的阿

**Comment by cqray1990** [comment]
运行predict_det.py   在self.predictor.run()运行后挂掉
C++ Traceback (most recent call last):

No stack trace in paddle, may be caused by external reasons.
Error Message Summary:

FatalError: Segmentation fault is detected by the operating system.
[TimeInfo: *** Aborted at 1637680470 (unix time) try "date -d @1637680470" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 4303 (TID 0x7f9e26ade740) from PID 0 ***]

**Comment by UncleLLD** [comment]
同样这个问题
