### ISSUE TITLE
请问一下，我在官方提供的预训练模型的基础上训练其他少数名字语言的文字识别模型可行吗？这样会不会收敛得更快一点？

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#474]

**Comment by LDOUBLEV** [comment]
可行，会训练的快一些。少数民族语言是指哪些，如果要识别的文字不是包含在字典里的，需要用你自己的字典，加载模型时，通过Global.checkpoints 或者Global.pretrain_weights加载我们的预训练模型

字典文件在：
![image](https://user-images.githubusercontent.com/26592129/89245205-e82e0a00-d63a-11ea-8c70-bf7c204c416b.png)

**Comment by hsyy673150343** [comment]
维吾尔文之类的少数民族语言，但是我现在数据集只有一万多张图片，自己从头开始训练，发现精度太低了。

**Comment by hsyy673150343** [comment]
> 可行，会训练的快一些。少数民族语言是指哪些，如果要识别的文字不是包含在字典里的，需要用你自己的字典，加载模型时，通过Global.checkpoints 或者Global.pretrain_weights加载我们的预训练模型
> 
> 字典文件在：
> ![image](https://user-images.githubusercontent.com/26592129/89245205-e82e0a00-d63a-11ea-8c70-bf7c204c416b.png)

维吾尔文之类的少数民族语言，但是我现在数据集只有一万多张图片，自己从头开始训练，发现精度太低了。

**Comment by LDOUBLEV** [comment]
可以用我们的预训练模型试试，数据量小，可以先用轻量模型
