### ISSUE TITLE
PaddleServing 部署 如何返回文字坐标数据

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleOCR#4742]
PaddleServing 部署之后 如何自定义返回数据类型 目前没有返回坐标以及准确率等信息

**Comment by tink2123** [comment]
目前只返回了文本信息，可以自己修改后处理返回信息：
识别：https://github.com/PaddlePaddle/PaddleOCR/blob/e2755f2c58e36e0e24e68581986cf89868f97699/deploy/pdserving/ocr_reader.py#L425

检测：
https://github.com/PaddlePaddle/PaddleOCR/blob/e2755f2c58e36e0e24e68581986cf89868f97699/deploy/pdserving/web_service.py#L63
