### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.infer'

### ISSUE THREAD

**Issue by SyGoing** [PaddlePaddle/PaddleOCR#4744]
paddlepaddle安装完毕以及相关requirements.txt安装完毕，当执行  python PPOCRLabel.py --lang ch时报错：

Traceback (most recent call last):
  File "PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR
  File "../paddleocr.py", line 26, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

**Comment by WenmuZhou** [comment]
是否安装了其他库，比如mmdetection

**Comment by anshenLW** [comment]
是的我安装了mmdetection，会引起冲突吗

**Comment by anshenLW** [comment]
uninstall mmdet 后 仍然报错
ModuleNotFoundError: No module named 'tools.infer'

**Comment by alexguo** [comment]
> 是否安装了其他库，比如mmdetection

感谢，我装了`detectron2` 卸载后好了

**Comment by jimmyflycv** [comment]
i uninstall detectron2 but the error still exists.

**Comment by renjithsasidharan** [comment]
I have detectron2 installed
`!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`

**Comment by renjithsasidharan** [comment]
I did a local fix by modifying the line to `from paddleocr.tools.infer import predict_system` in paddleocr.py

**Comment by vineethbabu** [comment]
Hi @renjithsasidharan, i tried changing that line but still facing the error, i also have to run detectron2 and paddlocr together could you pls tell if some thing else needs to be changed?
thanks in advance.

**Comment by renjithsasidharan** [comment]
> Hi @renjithsasidharan, i tried changing that line but still facing the error, i also have to run detectron2 and paddlocr together could you pls tell if some thing else needs to be changed? thanks in advance.

Thats the only change I had to make. Make sure you changed the file in the right conda environment, if you are using one. Then if you are using jupyter, you need to restart the notebook.

**Comment by avb97** [comment]
removing a preexisting tools package solved it for me. thanks @renjithsasidharan

**Comment by jimmyflycv** [comment]
> I did a local fix by modifying the line to `from paddleocr.tools.infer import predict_system` in paddleocr.py

i dont have detectron2 in my mac and tried this but error still exists.

**Comment by pharrellyhy** [comment]
Install paddleocr using `pip install paddleocr`. If you are using `venv` or `conda` env, you need to modify the line `tools.infer` to `paddleocr.tools.infer` in each of the file under your current env directory.

**Comment by mchl0203** [comment]
主要还是ppocr导包的方式有问题

**Comment by loveanao** [comment]
> 主要还是ppocr导包的方式有问题

也是，PPOCR的包在很对地方导入没考虑完全...

**Comment by WenmuZhou** [comment]
这个问题应该最新版已经修复了

**Comment by rexzhengzhihong** [comment]
> 这个问题应该最新版已经修复了

如果不是最新版的要怎么修改呢？2.6的

**Comment by ucas010** [comment]
2.6.1.3仍然有这个问题。
Successfully installed paddleocr-2.6.1.3
>>> import paddleocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/chatdoc/lib/python3.9/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "g/anaconda3/envs/chatdoc/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 37, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

**Comment by jimmyflycv** [comment]
Successfully installed paddleocr-2.6.1.3

(py38) apple@mbp inno % PPOCRLabel --lang ch
Traceback (most recent call last):
  File "/Users/apple/opt/anaconda3/envs/py38/bin/PPOCRLabel", line 5, in <module>
    from PPOCRLabel.PPOCRLabel import main
  File "/Users/apple/opt/anaconda3/envs/py38/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "/Users/apple/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/Users/apple/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 37, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

cant imagine the bug still exists after such long period.

**Comment by yfq512** [comment]
> i uninstall detectron2 but the error still exists.

I uninstall detectron2 and tools , now solved it.
