### ISSUE TITLE
文本检测损失函数降低可是评估的precision一直不升，达不到需求

### ISSUE THREAD

**Issue by xuehaopython1** [PaddlePaddle/PaddleOCR#4747]
工程师们好，我使用自己拍摄的照片大约70张，使用了PPOCRLabel进行了检测区域的标记。然后按照教程使用了mobile系列的各种预训练模型进行训练，loss函数在降低，可是precision一直波动不提升。后来我使用了模型库下载里面文本检测模型的训练模型继续训练，也没有达到预期的效果。可是使用模型库提供的inference模型推理可以把我想要的文本基本检测出来。工程师们有什么建议可以解决问题吗，谢谢。

**Comment by WenmuZhou** [comment]
用提供的模型直接eval看看

**Comment by xuehaopython1** [comment]
工程师你好，我根据您给的建议，使用paddleocr提供的各种模型进行了eval测试，precision精度很低，还不如我直接训练的模型高一点点。如果使用系统提供的inference模型能把文本检测出来。但是，还有很多不需要的文本被检测，所以我想进行训练的原因所在。可是自己训练的模型就一点文本检测不出来了。如果可以，能不能把我的训练集和配置文件发你一下，您看看问题所在。万分感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 文本检测损失函数降低可是评估的precision一直不升，达不到需求 (Issue #4747)





 
用提供的模型直接eval看看
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gmgge** [comment]
你可以贴出一部分数据集看一下，记得检查你的标签文件是否正确。
