### ISSUE TITLE
训练文字检测模型后，使用infer_det.py预测部分训练集图片，只能一张张预测，不能预测整个文件夹图片

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#475]
![1](https://user-images.githubusercontent.com/51456283/89245408-52df4580-d63b-11ea-9633-4b9412a0c65f.PNG)

**Comment by tyy2tyy** [comment]
预测代码：
python3 tools/infer_det.py -c det_r50_vd_east.yml -o TestReader.infer_img="/data/arty/train/synthtext/SynthText/199/" Global.checkpoints="./output/data_r50_east/best_accuracy"

**Comment by LDOUBLEV** [comment]
> 预测代码：
> python3 tools/infer_det.py -c det_r50_vd_east.yml -o TestReader.infer_img="/data/arty/train/synthtext/SynthText/199/" Global.checkpoints="./output/data_r50_east/best_accuracy"
```
python3 tools/infer_det.py -c det_r50_vd_east.yml -o TestReader.infer_img="/data/arty/train/synthtext/SynthText/199/" Global.checkpoints="./output/data_r50_east/best_accuracy"  Global.test_batch_size_per_card=1
```
试试这个命令，设置预测的batchsize=1，预测的时候图像的大小不一样，无法concat

**Comment by tyy2tyy** [comment]
已解决，感谢
