### ISSUE TITLE
gpu改成了false，但还是报错

### ISSUE THREAD

**Issue by Jackzhangfei** [PaddlePaddle/PaddleOCR#4750]
Config use_gpu cannot be set as true while you are using paddlepaddle cpu version !
Please try:
        1. Install paddlepaddle-gpu to run model on GPU
        2. Set use_gpu as false in config file to run model on CPU

**Comment by WenmuZhou** [comment]
报啥错呢

**Comment by Jackzhangfei** [comment]
已经解决，false 改成False 


| |
18796956283
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月26日 ***@***.***> 写道：

报啥错呢

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jackzhangfei** [comment]
谢谢


| |
18796956283
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月26日 ***@***.***> 写道：
已经解决，false 改成False 


| |
18796956283
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月26日 ***@***.***> 写道：

报啥错呢

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
