### ISSUE TITLE
docker部署后，几个小时后出现假死现象

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleOCR#4754]
docker部署后，开始正常，几个小时后出现类似假死现象，容器端口telnet能通，请求无反应，curl请求容器内服务不通。再次重启容器还是一样，开始正常，后面假死，请问这是怎么回事呢

**Comment by littletomatodonkey** [comment]
之前倒是没遇见过这种情况，docker创建的时候可以设置network=host看下
