### ISSUE TITLE
部署方案的选择

### ISSUE THREAD

**Issue by lexiaoyuan** [PaddlePaddle/PaddleOCR#4755]
大家好！
现在用PaddleOCR训练好了文本检测和识别的模型，需要把这个模型部署到RK3399ProD的开发板上，请问需要选择那种部署方案呢？
（补充：1. RK3399ProD的简单信息：CPU：六核ARM 64位处理器、GPU：四核ARM Mali-T860 MP4 GPU，系统：Debian10。2. 模型部署后需要配合一个调用海康威视工业相机的C++程序和一个驱动步进电机的C++程序来使用。3. 在实际使用过程中设备内部的开发板等要离线使用，不能连外接网线和WiFi。）
谢谢谢谢！

**Comment by littletomatodonkey** [comment]
可以尝试下PaddleLite

**Comment by lexiaoyuan** [comment]
> 可以尝试下PaddleLite

使用Paddle Lite，用C++开发，参考[android_demo](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/android_demo)和[Paddle Lite Demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo)，已经实现了自定义训练的PaddleOCR模型部署到RK3399ProD的开发板上。
