### ISSUE TITLE
PaddleOCR/ppocr/metrics/det_metric.py只能评测OCR检测的准招率，如何导出那些文本行是检测错误？

### ISSUE THREAD

**Issue by ahong007007** [PaddlePaddle/PaddleOCR#4758]
请教一下，

PaddleOCR/ppocr/metrics/det_metric.py只能评测OCR检测的准确率召回率，如何导出那些文本行是检测错误？那些是未召回？ 如何和真值的ignore结合分析准招的bad case?

谢谢

**Comment by littletomatodonkey** [comment]
判断检测框召回之后，再判断下文本行是否正确即可
