### ISSUE TITLE
PPOCRLabel: SRN model error

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#4759]
My inference model is SRN_R50. When I modify rec_model_dir with my inference model, I meet the error as the figure. Can you help me fix the error?
![Screenshot from 2021-11-25 18-18-59](https://user-images.githubusercontent.com/88916218/143432738-b31c6459-94d2-4280-bd57-551aa10eb36d.png)

**Comment by littletomatodonkey** [comment]
可以用release/2.3动态图代码导出看下

**Comment by huylgia** [comment]
tks you, I detected problem "Max text length is constant with 25". How to fix?
[Add 'max_text_length': args.max_text_length](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/predict_rec.py#L53)
[Remove ", 25"](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/predict_rec.py#L52)
