### ISSUE TITLE
Baidu Self-Research, comming soon?

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#476]
什么时候，下一版本发布？

**Comment by tink2123** [comment]
自研部分算法8月份陆续发布，9月份发布下一个版本

**Comment by deep-practice** [comment]
下一个版本是什么样的版本？ @tink2123

**Comment by dyning** [comment]
从策略改进、使用更多真实数据和模型量化上，提升当前发布的中文OCR模型的效果和效率。

**Comment by xinsuinizhuan** [comment]
> 
> 
> 从策略改进、使用更多真实数据和模型量化上，提升当前发布的中文OCR模型的效果和效率。

期待，尽快发布，等不急了。记得要支持C++调用哦。

**Comment by xinsuinizhuan** [comment]
啥时候发布，啥时候发布？

**Comment by dyning** [comment]
预计9月中下旬
