### ISSUE TITLE
关于SRN模型中双向GSRM的问题

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#4762]
如题，SRN论文中的消融实验部分，对比了GSRM、FSRM和BSRM，然后在代码中也看到了说GSRM这部分是用双向transformer实现的。但是我对这部分的代码有点疑问：代码中是有两个输入和两个transformer的encoder，一个输入是word1，它是pvam的预测结果右移一位，另一个输入是word2，它就是pvam的预测结果不移位，然后用这两个输入得到两个输出gsrm_feature1和gsrm_feature2，对于gsrm_feature2，似乎是把这个feature左移了一位，再去和gsrm_feature1相加，想必这两部分也就是对应的前向transformer和反向transformer。但是对于这个反向的transformer，我不是很能理解，反向的transfomer不是应该把pvam的预测结果颠倒过来作为输入吗？但是word2并没有颠倒顺序，反而是对gsrm_feature2向左移了一位，真的不理解。
    
希望能有大佬解决一下我的疑惑，不胜感激！

![image](https://user-images.githubusercontent.com/74600923/143513633-606bfe5f-075c-492f-aecc-6846426753f3.png)

**Comment by tink2123** [comment]
这里代码的实现方式可能和常规理解不同，gsrm需要感知除本身字符外的所有位置信息，这里是对当前字符的左边信息和右边信息分开来感知的，最后再合一块。bi代表左右两边

**Comment by Lebron-Harden** [comment]
> 这里代码的实现方式可能和常规理解不同，gsrm需要感知除本身字符外的所有位置信息，这里是对当前字符的左边信息和右边信息分开来感知的，最后再合一块。bi代表左右两边

谢谢回复！
