### ISSUE TITLE
在ppocr之前用ppdetection检测

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleOCR#4765]
想在ppocr之前用ppdetection检测卡证。生产环境是centos，没有GPU.之前在3090上训练过一个ssd的ssd_mobilenet_v1_300_120e_voc。在cpu环境上大概几十ms。但是在生产环境上速度就比较慢。请问有比较合适的模型推荐吗？还有ssd只能回归出一个矩形位置，有没有哪个模型直接输出畸变的卡证的四个角点？

**Comment by MissPenguin** [comment]
可以到[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/issues)问下哈，他们可以提供更有效的意见。或者直接试试他们最新发布的[PP-PicoDet](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet)，非常轻量。
