### ISSUE TITLE
AssertionError: Optimizer set error, linear_0.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by luluwang0** [PaddlePaddle/PaddleOCR#4766]
加载识别的预训练模型，yml配置文件应用于推荐一致。出现这个问题错误。

**Comment by luluwang0** [comment]
加载通用识别模型进行自己的数据训练出现的问题，有人遇到这个问题嘛？

**Comment by MissPenguin** [comment]
可以提供一下更具体的信息吗，哪个预训练模型、启动命令、paddle版本、代码版本，代码做了哪些改动等等，方便复现排查

**Comment by luluwang0** [comment]
使用的rec_chinese_common_train_v2.0.yml配置文件，加载其对应的预训练文件，ch_ppocr_server_v2.0_rec_train/
启动命令是python tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml

**Comment by MissPenguin** [comment]
训练不需要安装paddleocr哈，不过这个没关系。我这边用release/2.3分支代码，paddle2.1.3，相同的配置和命令，加载ch_ppocr_server_v2.0_rec_train预训练，跑着没问题呢。要不贴一下你的配置文件看看
