### ISSUE TITLE
Memory consumption is too high when training model

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#477]
Memory consumption is too high when I train the model.
Only train the det model
env: win10+ py3.7.1+CPU
train params :use the  icdar2015 there are only a few training data(about 30)
and epoch_num less than 30

finally , the memory consumption about 3.5G

**Comment by LDOUBLEV** [comment]
Memory usage is related to the model used and the batch size.  
The default value is 256. you can try a smaller batch size when training on CPU.

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/89268095-a2893580-d66a-11ea-981a-7a99d9318d45.png)
this is the configration of my det_r50_vd_east.yml
when I change the `train_batch_size_per_card` , to 1 , it can reduce memory usage  to 1.5G

**Comment by LDOUBLEV** [comment]
The rest50-based model is too heavy for CPU.
It is not recommended to train such a large model on the CPU. Baidu has free GPU resources, [AIstudio](https://aistudio.baidu.com/aistudio/index)

**Comment by BeyondYourself** [comment]
Do you have some hardware and software configuration suggestions?
