### ISSUE TITLE
安装pip install "paddleocr>=2.0.1"时出现了错误（win10和centos都出现了这个问题）

### ISSUE THREAD

**Issue by andrew-begain** [PaddlePaddle/PaddleOCR#4776]
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda3/envs/ocr2.3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ikhwkjl4
       cwd: /tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/
  Complete output (58 lines):
  /home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/fasttext
  copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-3.8/fasttext
  copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-3.8/fasttext
  creating build/lib.linux-x86_64-3.8/fasttext/util
  copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-3.8/fasttext/util
  copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-3.8/fasttext/util
  creating build/lib.linux-x86_64-3.8/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-3.8/fasttext/tests
  copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-3.8/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-3.8/fasttext/tests
  running build_ext
  creating tmp
  gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmpd_gl0n8o.cpp -o tmp/tmpd_gl0n8o.o -std=c++14
  gcc: error: unrecognized command line option ‘-std=c++14’
  gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmpzw408k3m.cpp -o tmp/tmpzw408k3m.o -std=c++11
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmpap8pv7c1.cpp -o tmp/tmpap8pv7c1.o -std=c++0x
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 168, in <module>
      setup(
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 146, in build_extensions
      opts.append(cpp_flag(self.compiler))
    File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 108, in cpp_flag
      raise RuntimeError(
  RuntimeError: Unsupported compiler -- at least C++0x support is needed!
  ----------------------------------------
  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext
Installing collected packages: fasttext, cython, paddleocr
    Running setup.py install for fasttext ... error
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/envs/ocr2.3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zz64589o/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda3/envs/ocr2.3/include/python3.8/fasttext
         cwd: /tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/
    Complete output (59 lines):
    /home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/fasttext
    copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-3.8/fasttext
    copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-3.8/fasttext
    creating build/lib.linux-x86_64-3.8/fasttext/util
    copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-3.8/fasttext/util
    copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-3.8/fasttext/util
    creating build/lib.linux-x86_64-3.8/fasttext/tests
    copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-3.8/fasttext/tests
    copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-3.8/fasttext/tests
    copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-3.8/fasttext/tests
    running build_ext
    gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmp63lrf1fx.cpp -o tmp/tmp63lrf1fx.o -std=c++14
    gcc: error: unrecognized command line option ‘-std=c++14’
    gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmpd4saqv5s.cpp -o tmp/tmpd4saqv5s.o -std=c++11
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    gcc -pthread -B /home/anaconda3/envs/ocr2.3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/ocr2.3/include/python3.8 -c /tmp/tmps9m13cs6.cpp -o tmp/tmps9m13cs6.o -std=c++0x
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 168, in <module>
        setup(
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/anaconda3/envs/ocr2.3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 146, in build_extensions
        opts.append(cpp_flag(self.compiler))
      File "/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py", line 108, in cpp_flag
        raise RuntimeError(
    RuntimeError: Unsupported compiler -- at least C++0x support is needed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda3/envs/ocr2.3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xmun1l7j/fasttext_b36c0fb8725d4909a4a6f09e01e75b5a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zz64589o/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda3/envs/ocr2.3/include/python3.8/fasttext Check the logs for full command output.

**Comment by zh4ngyu** [comment]
遇到相同问题，在https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext上下载了.whl文件安装上了fasttext之后，输入pip install "paddleocr>=2.0.1"依然报错

**Comment by andrew-begain** [comment]
> 遇到相同问题，在https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext 上下载了.whl文件安装上了fasttext之后，输入pip install "paddleocr>=2.0.1"依然报错
你是在什么系统上呢？我的windows系统上还没有解决 ，但是linux上是因为没有g++，安装完g++就可以了，希望能帮助你

**Comment by zh4ngyu** [comment]
> 

谢谢，我也是在windows上，是用 anaconda 创建的 python 3.8 的环境

**Comment by andrew-begain** [comment]
> > 
> 
> 谢谢，我也是在windows上，是用 anaconda 创建的 python 3.8 的环境

我也是安装了whl文件后还出现了问题，后来就在linux上运行了，建议还是在linux上运行吧

**Comment by tmylla** [comment]
@zh4ngyu 
解决办法：在[该网站](https://blog.turquoise.health/fasttext-binaries-for-windows/)下载并安装fasttext==0.9.1的wheel；

报错原因：paddleocr>=2.0.1依赖的fasttext版本为0.9.1，见下图。[https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext](https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext)提供的为最新版本0.9.2，安装该版本的whl文件后，在安装paddleocr时由于版本不匹配会将其卸载，继续找寻fasttext==0.9.1安装，因此报错。
![image](https://user-images.githubusercontent.com/44560781/146860504-6d3773c3-d707-468a-b880-e2a2d0b73797.png)

**Comment by zhugw** [comment]
> > 遇到相同问题，在https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext 上下载了.whl文件安装上了fasttext之后，输入pip install "paddleocr>=2.0.1"依然报错
> > 你是在什么系统上呢？我的windows系统上还没有解决 ，但是linux上是因为没有g++，安装完g++就可以了，希望能帮助你

CentOS 7.9  安装了g++解决了
```
yum install gcc-c++

```

**Comment by Penguin-Killer** [comment]
use this:
`pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1`
