### ISSUE TITLE
能否返回单字字符的位置

### ISSUE THREAD

**Issue by quhuan1** [PaddlePaddle/PaddleOCR#478]
测试返回的是整行或列的文本块的位置，能否返回文本块种单字字符的位置信息。

**Comment by LDOUBLEV** [comment]
训练的时候标注是整个文本行的标注，所以预测的也是文本行位置，如果要获取单字符位置信息，可以根据预测的文本，计算字符数量，再去根据整个文本行的位置信息，估计文本块中每个字符的位置。
