### ISSUE TITLE
ImportError: cannot import name 'PaddleOCR' from partially initialized module 'paddleocr' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Gilberthtx** [PaddlePaddle/PaddleOCR#4780]
When I get to this line in my code:

from paddleocr import PaddleOCR, draw_ocr

I get the error:

ImportError: cannot import name 'PaddleOCR' from partially initialized module 'paddleocr' (most likely due to a circular import) (C:\Users\Gilbe\anaconda3\envs\paddle\lib\site-packages\paddleocr\__init__.py)

I have paddlepaddle v2.2.0 installed but not paddleocr. If I install paddleocr v2.3.0.2, I instead get the error:

ModuleNotFoundError: No module named 'paddleocr'

How is that possible? Can someone please help me resolve this? I just want to get PPOCR running with PGNet

**Comment by CozyDust** [comment]
may be you need to change your script name

**Comment by tink2123** [comment]
If you want to train PGNet, paddleocr is not necessary

You just need to install paddlepaddle-gpu, and the requirements.txt. Refer to the [PGNet document](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/pgnet_en.md)

**Comment by Suvoo** [comment]
> When I get to this line in my code:
> 
> from paddleocr import PaddleOCR, draw_ocr
> 
> I get the error:
> 
> ImportError: cannot import name 'PaddleOCR' from partially initialized module 'paddleocr' (most likely due to a circular import) (C:\Users\Gilbe\anaconda3\envs\paddle\lib\site-packages\paddleocr__init__.py)
> 
> I have paddlepaddle v2.2.0 installed but not paddleocr. If I install paddleocr v2.3.0.2, I instead get the error:
> 
> ModuleNotFoundError: No module named 'paddleocr'
> 
> How is that possible? Can someone please help me resolve this? I just want to get PPOCR running with PGNet

you need to comment out the` import paddle` from the file. Calling `paddle in paddleocr.py` leads to a circular import
