### ISSUE TITLE
文字检测只能推理出矩形？不具备弯曲文本检测的能力吗？

### ISSUE THREAD

**Issue by alex152738** [PaddlePaddle/PaddleOCR#4786]
有一点不懂，为什么推理结果只有矩形文本，没有弯曲文本。那训练的时候弯曲文本参与训练了吗？文中对于数据集的评估应该是包含弯曲文本的评估吧？DBnet模型具备弯曲文本检测的能力吗？还是我理解对于弯曲文本的检测和评估能力是具备的，只不过为了后面的识别，推理的时候逻辑只保留了矩形？为什么推理只保留矩形呢？

**Comment by WenmuZhou** [comment]
需要自己改一下db的后处理哈

**Comment by zlszhonglongshen** [comment]
> 需要自己改一下db的后处理哈

怎么改呀？

**Comment by 1037419569** [comment]
> 需要自己改一下db的后处理哈

同问 怎么改呀？
