### ISSUE TITLE
PPStructure question: is the result mAP@0.5 or mAP@0.75 ?

### ISSUE THREAD

**Issue by PkuDavidGuan** [PaddlePaddle/PaddleOCR#4789]
Hi, I want to know the evaluation metric when testing the yolox-v2 layout model on the PubLayNet dataset. Is the metric `mAP@0.5` or `mAP@0.75` in https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/ppstructure/layout/README.md#Training

**Comment by WenmuZhou** [comment]
avg of 0.5-0.95
