### ISSUE TITLE
How to Use serving to serve SAST DETECTION model?

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/PaddleOCR#4792]

**Comment by WenmuZhou** [comment]
do you mean hubserving?

**Comment by YC7225** [comment]
no! I am using pdserving. I have changed the post-process function as well according to the SAST. but I am not getting a response.

**Comment by tink2123** [comment]
You can debug the SAST model based on [web_service_det.py](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/pdserving/web_service_det.py)

These places need to be modified:  pre-processing, post-processing，Convert SAST inference model for deployment

If you encounter problems, you can check the PipelineServingLogs/pipeline.log to get specific error information

**Comment by YC7225** [comment]
I have converted the SAST pre-trained model into inference model and after that serving, model using these docs [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/inference_en.md#2-curved-text-detection-model-total-text](url)

**Comment by YC7225** [comment]
what is the fetch_list for SAST model?

**Comment by YC7225** [comment]
I am closing this issue i did it. thank you so much guys to help me out in it if you guys want any tutorial or code changes let me know i will create a PR for same.


i did it finally hurrreeeeeeeeee!

**Comment by YC7225** [comment]
#4441
