### ISSUE TITLE
在pp-OCRv2.0 预训练模型基础上在训练，部署到侧端不能识别

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleOCR#4794]
采用自己的字典，训练好后在PC上用infer_rec.py或predict_rec.py预测都很好，但用paddle-lite v2.9 opt工具转成.nb模型后，在用c++部署于android手机上预测，结果全部不对，请问是什么原因

**Comment by dlkht** [comment]
配置文件用ch_PP-OCRv2_rec.yml，

**Comment by WenmuZhou** [comment]
安卓上面字典换了吗，另外可以看看检测结果对不对，确定一下是什么模型的问题

**Comment by dlkht** [comment]
> 安卓上面字典换了吗，另外可以看看检测结果对不对，确定一下是什么模型的问题

谢谢！安卓上字典换了，检测正确，识别结果不对。

**Comment by dlkht** [comment]
我下载ch_PP-OCRv2_rec_train.tar解压后直接用自己的数据和字典再训练，这个有无问题？但PC上测试结果是对的。用export_model.py导出模型后，再用paddle-lite 2.9 的opt转换出.nb模型，在侧端识别就不行了

**Comment by WenmuZhou** [comment]
辛苦跑一下inference的模型，看看有没有文图

**Comment by 1220985305** [comment]
我也有相同问题，不过我的代码分支是dygrah和release2.3，都有相同的问题
