### ISSUE TITLE
希望提供一个paddlehub的模型构建脚本

### ISSUE THREAD

**Issue by hebw** [PaddlePaddle/PaddleOCR#48]
可以使用paddlehub运行的PaddleOCR 模块包

**Comment by dyning** [comment]
目前paddlehub相关功能还在构建中，预计下周可以提供，功能会支持模型预测，由于OCR问题复杂，模型训练还是需要基于本repo，我们也尽可能通过完善文档，降低训练的学习成本。

**Comment by hebw** [comment]
> 目前paddlehub相关功能还在构建中，预计下周可以提供，功能会支持模型预测，由于OCR问题复杂，模型训练还是需要基于本repo，我们也尽可能通过完善文档，降低训练的学习成本。

非常感谢，可以提供模型包，一起将paddlehub module构建代码一起发布，方便自己动手丰衣足食
