### ISSUE TITLE
the save_res_path is was rewritten

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#480]
14 | pretrain_weights: ./pretrain_models/ResNet50_vd_ssld_pretrained/
-- | --
15 | save_res_path: ./output/det_east/predicts_east.txt

when I train the det ,at the  second iter the  predicts_east.txt was rewritten ,whether it is normal operation

**Comment by littletomatodonkey** [comment]
It's normal because we just need current models' results to get the metrics, if you want to get the results before, you can carry out the eval process.

**Comment by BeyondYourself** [comment]
thx,get it
