### ISSUE TITLE
SAST 

### ISSUE THREAD

**Issue by YinZhang98** [PaddlePaddle/PaddleOCR#4803]
![image](https://user-images.githubusercontent.com/33601373/144153348-3a98e426-fe6b-48c0-a028-99e5f272832e.png)
SAST的论文中写的使用连续的俩个CAB，这里为什么只使用了一个？，这个模块使用与否对结果影响大吗？

**Comment by zhangyinzhangyin** [comment]
> ![image](https://user-images.githubusercontent.com/33601373/144153348-3a98e426-fe6b-48c0-a028-99e5f272832e.png) 论文中写的使用连续的俩个，这里为啥只使用了一个啊

这个模块到底有没有用啊，使用前需要加relu吗

**Comment by YinZhang98** [comment]
![image](https://user-images.githubusercontent.com/33601373/144226646-5c6ff3c4-9d0a-404f-859b-2faaacb4d47e.png)
