### ISSUE TITLE
识别简单英文没问题，弯曲文本识别报错，怎么回事？

### ISSUE THREAD

**Issue by ewwerpm** [PaddlePaddle/PaddleOCR#4804]
用的docker镜像，按照https://www.bookstack.cn/read/PaddleOCR/installation.md 装的。两个张量的shape不一样，怎么办？
/home/PaddleOCR {release/2.3} python3 tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./doc/imgs_en/img623.jpg" --det_model_dir="./inference/det_sast_tt/" --det_sast_polygon=True --use_gpu=False
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.8/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
---    Fused 0 subgraphs into layer_norm op.
---    fused 0 pairs of fc gru patterns
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 242, in <module>
    res = text_detector(img)
  File "tools/infer/predict_det.py", line 218, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "/home/PaddleOCR/ppocr/postprocess/sast_postprocess.py", line 341, in __call__
    poly_list = self.detect_sast(
  File "/home/PaddleOCR/ppocr/postprocess/sast_postprocess.py", line 237, in detect_sast
    instance_count, instance_label_map = self.cluster_by_quads_tco(
  File "/home/PaddleOCR/ppocr/postprocess/sast_postprocess.py", line 164, in cluster_by_quads_tco
    pred_tc = xy_text - tco
ValueError: operands could not be broadcast together with shapes (8885,2) (8885,8)

**Comment by MissPenguin** [comment]
用的什么版面的paddle，这个好像是paddle升级引入的问题，要么换paddle2.1.3试试，要么换dygraph分支试试吧

**Comment by ewwerpm** [comment]
谢谢，用paddle2.1.3试了，问题解决。现在的问题是：识别效果太差，几乎一个字母都没识别出来。和例子给出来的结果相差很大，怎么回事？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别简单英文没问题，弯曲文本识别报错，怎么回事？ (Issue #4804)





 
用的什么版面的paddle，这个好像是paddle升级引入的问题，要么换paddle2.1.3试试，要么换dygraph分支试试吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MissPenguin** [comment]
测试的哪个模型，运行的什么命令，方便的话也发一下测试图片吧

**Comment by ewwerpm** [comment]
跑了30分钟了，还是停在这。上次20分钟我我直接ctrl+c结束了，再跑就出现了上次 邮件的结果。谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别简单英文没问题，弯曲文本识别报错，怎么回事？ (Issue #4804)





 
测试的哪个模型，运行的什么命令，方便的话也发一下测试图片吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ewwerpm** [comment]
怎么docker显示的时间不对？怎么会是09:09:16呢？ 等了好久才跑出来，但感觉还是不对啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别简单英文没问题，弯曲文本识别报错，怎么回事？ (Issue #4804)





 
测试的哪个模型，运行的什么命令，方便的话也发一下测试图片吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ewwerpm** [comment]
麻烦问下，能看出来原因在哪吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别简单英文没问题，弯曲文本识别报错，怎么回事？ (Issue #4804)





 
测试的哪个模型，运行的什么命令，方便的话也发一下测试图片吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
