### ISSUE TITLE
表格结构识别模型无法使用GPU加速

### ISSUE THREAD

**Issue by TTMRonald** [PaddlePaddle/PaddleOCR#4805]
你好，我在运行ppstructure的demo发现表格结构识别模型无法使用GPU加速，其他模型可以调起GPU加速，贴一张几个模型的耗时对比图
![耗时](https://user-images.githubusercontent.com/18680409/144206173-461c4156-2ad5-4477-8689-d0f4a199e615.png)
在我的测试图片上，表格结构识别模型GPU和CPU运行耗时基本一致，都是2秒多

**Comment by MissPenguin** [comment]
贴一下你的运行命令吧

**Comment by TTMRonald** [comment]
@MissPenguin 默认use_gpu是True，完整命令如下
python ppstructure/predict_system.py --layout_path_model=lp://TableBank/ppyolov2_r50vd_dcn_365e_tableBank_word/config --layout_model_dir=weights/inference/ppyolov2_r50vd_dcn_365e_tableBank_word --det_model_dir=weights/inference/ch_ppocr_server_v2.0_det_infer --rec_model_dir=weights/inference/ch_ppocr_server_v2.0_rec_infer --table_model_dir=weights/inference/en_ppocr_mobile_v2.0_table_structure_infer --rec_char_dict_path=ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=ppocr/utils/dict/table_structure_dict.txt --rec_char_type=ch --image_dir=images --output=results/table --vis_font_path=doc/fonts/simfang.ttf

**Comment by TTMRonald** [comment]
> 贴一下你的运行命令吧

有空帮忙看一下哈，感谢
