### ISSUE TITLE
Finetune on Arabic sentences 

### ISSUE THREAD

**Issue by RihabElya** [PaddlePaddle/PaddleOCR#4806]
I have finetuned the ch_ppocr_server_v2.0_det model with its configuration (ch_det_res18_db_v2.0.yml) on Arabic text sentences the problem is :
after the finetuning the model predictions have completely been deteriorated and the model dosen't detect anything which is very weird 
PS: I finetune with sentences and not with words is it the problem ?
This is sample of my training file:
 page4.png	[{"transcription": "قناة في فرنسا وقد حقق شهرة عالمية كذلك وقد تم تصنيف هذا", "points": [[0, 1476], [4800, 1476], [4800, 1564], [0, 1564]]}, {"transcription": "زانا ينجو باعجوبة ويعود اقوى بكثير واكثر خبثا وخطر من اي وقت...

this is the configuration file
[ara_det.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7632933/ara_det.txt)

**Prediction after finetuning** 
![page4](https://user-images.githubusercontent.com/81768840/144214301-59367f77-aa36-4ed5-94d2-f51aa5422de9.png)
**Prediction before finetuning**
![page4 1](https://user-images.githubusercontent.com/81768840/144214311-664a8a08-7feb-49fa-8286-76ff7751e05f.png)

**Comment by MissPenguin** [comment]
Finetune with sentences and not with words is not a problem.

Can you show your train log

**Comment by RihabElya** [comment]
Should I change anything in the configuration when finetuning with sentences ?

This is my train log 
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/7640064/train.log)

**Comment by MissPenguin** [comment]
> Should I change anything in the configuration when finetuning with sentences ?

no need to change anything in the configuration when training with sentences if the coordinates are right.

maybe it's because your training set is too small. how many images in your training set ?

**Comment by RihabElya** [comment]
I used 12k for training and 3k for test, but even though the training set is too small why the prediction after the finetuning is deteriorated isn't supposed to stay at least the same? 
This is how I implemented the coordinates:   "points":[[x,y],[x+h,y],[x+h, y+h],[x, y+h]] its true right?

**Comment by RihabElya** [comment]
@MissPenguin I ran out of solutions can you please help

**Comment by hisiter97** [comment]
> I used 12k for training and 3k for test, but even though the training set is too small why the prediction after the finetuning is deteriorated isn't supposed to stay at least the same? This is how I implemented the coordinates: "points":[[x,y],[x+h,y],[x+h, y+h],[x, y+h]] its true right?

I saw it in your log: 
[2021/11/30 14:07:19] root INFO: train dataloader has 5 iters
[2021/11/30 14:07:19] root INFO: valid dataloader has 10 iters
meaning there was an error while loading data

**Comment by RihabElya** [comment]
what can be the reason the data isn't fully loading ?

**Comment by hisiter97** [comment]
> what can be the reason the data isn't fully loading ?

you must check your data again

**Comment by RihabElya** [comment]
but the data is fine I checked it several times, do you have any suggestions ?

**Comment by briliantnugraha** [comment]
> > I used 12k for training and 3k for test, but even though the training set is too small why the prediction after the finetuning is deteriorated isn't supposed to stay at least the same? This is how I implemented the coordinates: "points":[[x,y],[x+h,y],[x+h, y+h],[x, y+h]] its true right?
> 
> I saw it in your log: [2021/11/30 14:07:19] root INFO: train dataloader has 5 iters [2021/11/30 14:07:19] root INFO: valid dataloader has 10 iters meaning there was an error while loading data

Hi @RihabElya , regarding the low number of iters in your dataloader's dataset, do you use a very big number of batch (possibly 2400 batch for training and 300 batch for testing)?

The reason is that, suppose you have 12k of training images, and the dataset is set correctly, in order to make it into 5 iters for train dataloader, you need to make 12k/5 = 2400 batches and for testing 3k/10 = 300 batches.

Going from that, it is unlikely to achieve 2400 batch (FYI, I test finetune with distill.yml with batch=2, and it takes 5.6 GB of RTX3070 GPU RAM), unless you have a very capable/cloud server in your league, at least not a mere mortal like me.

Hence, my suggestion is to double check whether you can re-draw your image using your generated annotation.

FYI, if you are using ICDAR, the annotation should look like these
```
img_1.jpg	[{"transcription": "###", "points": [[933, 255], [954, 255], [956, 277], [936, 277]]}, {"transcription": "###", "points": [[172, 323], [195, 324], [195, 339], [177, 339]]}]
img_10.jpg	[{"transcription": "Please", "points": [[27, 17], [103, 22], [106, 47], [30, 45]]}, {"transcription": "lower", "points": [[107, 20], [159, 26], [159, 48], [109, 47]]}]
```

hope this helps~
