### ISSUE TITLE
推理模型转换为训练模型

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#4808]
推理模型能够转为训练模型吗

**Comment by lgcy** [comment]
通过pdparams和states将模型转为pdiparams和odmodel，能够将pdiparams和odmodel转为pdparams和states吗

**Comment by MissPenguin** [comment]
不支持哈，很多信息已经丢掉了

**Comment by lgcy** [comment]
> 不支持哈，很多信息已经丢掉了

其实是可以的

**Comment by the-return-of-the-return** [comment]
> 

请问要怎么操作呢？

**Comment by the-return-of-the-return** [comment]
> > 不支持哈，很多信息已经丢掉了
> 
> 其实是可以的

请问要怎么操作呢？
