### ISSUE TITLE
SAST代码疑惑

### ISSUE THREAD

**Issue by YinZhang98** [PaddlePaddle/PaddleOCR#4809]
![image](https://user-images.githubusercontent.com/33601373/144226769-a65a9321-1d75-44a2-b0d7-69e5cc3dcfbc.png)
论文中写的使用连续的俩个CAB，为什么代码里只使用了一个该模块？

**Comment by MissPenguin** [comment]
代码确实只加了一次cab，效果其实差不多，有兴趣可以再加一次对比看看
