### ISSUE TITLE
训练得到的文本检测模型，在python环境下可以正常运行，但是放到c++环境下，检测不出任何文本框，boxes.size()始终是0，换成预训练模型则可以正常检测，请问是少配置了什么吗？

### ISSUE THREAD

**Issue by cqhblg** [PaddlePaddle/PaddleOCR#4811]
![image](https://user-images.githubusercontent.com/29913470/144248065-7e253039-6f4d-4fc6-928b-fea5bd181e1e.png)
我对比这里面和训练时的参数一致，不知道是不是图片的大小问题

**Comment by MissPenguin** [comment]
是自己训练的模型用predict_det.py可以正常预测，但是c++里面没结果是吗？ 具体是怎么训练的呢，用的哪个配置，改了哪些参数或者代码

**Comment by blackhitomi** [comment]
我也遇到过这个问题，C++和python预测结果不一致，主要就是det的结果，感觉有些python上可以识别的图，放在C++上死活识别不了，加强训练也不行。
