### ISSUE TITLE
hubserving部署

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4812]
麻烦问一下，算法部署到服务器后，在哪里面加一个身份验证，有选择地响应请求，而不是谁申请都响应

**Comment by LDOUBLEV** [comment]
目前没有这个功能

**Comment by zhangyingying520** [comment]
> 目前没有这个功能

paddleserving支持这样吗

**Comment by TeslaZhao** [comment]
身份验证是指SSL安全协议吗？还是说请求带token才能预测？

**Comment by zhangyingying520** [comment]
> 身份验证是指SSL安全协议吗？还是说请求带token才能预测？

我的意思是，如果我的服务部署到公网，任何人都可以访问了是吧？那我怎么才能加一个身份验证才能响应他们的请求

**Comment by zhangyingying520** [comment]
> > 身份验证是指SSL安全协议吗？还是说请求带token才能预测？
> 
> 我的意思是，如果我的服务部署到公网，任何人都可以访问了是吧？那我怎么才能加一个身份验证才能响应他们的请求



> 身份验证是指SSL安全协议吗？还是说请求带token才能预测？

不管以什么方式实现，只要能达到要求就可以，有什么建议吗？对这方面不太明白
