### ISSUE TITLE
方向分类器

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#4814]
请问官方的方向分类器用了多少数据量训练的？四个角度的分类，需要多少数据量合适？30万数据量训练精度只能到0.87

**Comment by LDOUBLEV** [comment]
有关模型训练和使用的数据，可以查看我们的技术文档https://arxiv.org/abs/2009.09941

**Comment by Currf** [comment]
> 有关模型训练和使用的数据，可以查看我们的技术文档https://arxiv.org/abs/2009.09941

请问方向分类器想分类90度和270度的数据，是直接修改label_list: ['0','90','180','270']就可以了？需要修改源码算法吗？
