### ISSUE TITLE
OCR检测顺序

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#4817]
DB+CRNN目前的识别顺序，是只能从左到右，从上到下吗

**Comment by LDOUBLEV** [comment]
检测后处理得到的检测框是无序的，你可以写个函数对输出的box排序

**Comment by kaiven11** [comment]
请问，有什么办法能让返回顺序严格按照从左到右，从上到下进行排序么？

`
def sorted_boxes(dt_boxes):
    """
    Sort text boxes in order from top to bottom, left to right
    args:
        dt_boxes(array):detected text boxes with shape [4, 2]
    return:
        sorted boxes(array) with shape [4, 2]
    """
    num_boxes = dt_boxes.shape[0]
    sorted_boxes = sorted(dt_boxes, key=lambda x: (x[0][1], x[0][0]))
    _boxes = list(sorted_boxes)

    for i in range(num_boxes - 1):
        if abs(_boxes[i + 1][0][1] - _boxes[i][0][1]) < 10 and \
                (_boxes[i + 1][0][0] < _boxes[i][0][0]):
            tmp = _boxes[i]
            _boxes[i] = _boxes[i + 1]
            _boxes[i + 1] = tmp
    return _boxes

`

这段代码，应该是对文本boxes进行的排序，但有时候返回也并不是完全预期的顺序返回，
比如：
[610.0, 245.0, 699.0, 245.0, 699.0, 270.0, 610.0, 270.0] #coord 工程编号：
[879.0, 247.0, 973.0, 247.0, 973.0, 277.0, 879.0, 277.0] #coord 报告编号：
[721.0, 248.0, 853.0, 248.0, 853.0, 271.0, 721.0, 271.0] #coord GC2021-00080
[995.0, 241.0, 1113.0, 241.0, 1113.0, 266.0, 995.0, 266.0] #coord XDJC21,JCHN-

这段是经过识别返回的最终结果的排序， 正常 **工程编号**应该对应 **GC2021-00080**，经过我上面提到的函数在处理一下，顺序也没有什么变化；



![image](https://user-images.githubusercontent.com/25794106/144370389-c13fa12f-8a2d-4ec0-aa1c-d9bc75251dd6.png)

PS： 针对表格，如果cell内文本是分开两行的，有什么好办法可以解决么？

        （我目前采用的是先识别表格单元，之后再对单元内的文本进行重新组合，得到最终结果）

**Comment by zhangyingying520** [comment]
> 请问，有什么办法能让返回顺序严格按照从左到右，从上到下进行排序么？
> 
> ` def sorted_boxes(dt_boxes): #Sort text boxes in order from top to bottom, left to right #args: # dt_boxes(array):detected text boxes with shape [4, 2] # return: # sorted boxes(array) with shape [4, 2]
> 
> ```
> num_boxes = dt_boxes.shape[0]
> sorted_boxes = sorted(dt_boxes, key=lambda x: (x[0][1], x[0][0]))
> _boxes = list(sorted_boxes)
> 
> for i in range(num_boxes - 1):
>     if abs(_boxes[i + 1][0][1] - _boxes[i][0][1]) < 10 and \
>             (_boxes[i + 1][0][0] < _boxes[i][0][0]):
>         tmp = _boxes[i]
>         _boxes[i] = _boxes[i + 1]
>         _boxes[i + 1] = tmp
> return _boxes
> ```
> 
> `
> 
> 这段代码，应该是对文本boxes进行的排序，但有时候返回也并不是完全预期的顺序返回， 比如： [610.0, 245.0, 699.0, 245.0, 699.0, 270.0, 610.0, 270.0] #coord 工程编号： [879.0, 247.0, 973.0, 247.0, 973.0, 277.0, 879.0, 277.0] #coord 报告编号： [721.0, 248.0, 853.0, 248.0, 853.0, 271.0, 721.0, 271.0] #coord GC2021-00080 [995.0, 241.0, 1113.0, 241.0, 1113.0, 266.0, 995.0, 266.0] #coord XDJC21,JCHN-
> 
> 这段是经过识别返回的最终结果的排序， 正常 **工程编号**应该对应 **GC2021-00080**，经过我上面提到的函数在处理一下，顺序也没有什么变化；
> 
> ![image](https://user-images.githubusercontent.com/25794106/144370389-c13fa12f-8a2d-4ec0-aa1c-d9bc75251dd6.png)
> 
> 另外： 针对表格，如果cell内文本是分开两行的，有什么好办法可以解决么？
> 
> ```
>     （我目前采用的是先识别表格单元，之后再对单元内的文本进行重新组合，得到最终结果）
> ```

我的最终输出是按照从左到右，然后从上到下

**Comment by zhangyingying520** [comment]
> 

![image](https://user-images.githubusercontent.com/80818728/145321940-7a538bc0-7873-4e30-8f0b-c54bfad5312d.png)
![image](https://user-images.githubusercontent.com/80818728/145321960-2c27689b-d3cb-4828-8cf4-39697980c57d.png)
