### ISSUE TITLE
文本检测模型训练数据集

### ISSUE THREAD

**Issue by June-Li** [PaddlePaddle/PaddleOCR#4818]
真实（使用68K）：
1）public：LSVT、RCTW、MTWI、CASIA、SROIE、MLT、BDI、MSRA、CCPD
2）百度：Baidu image search
合成（使用29K）：

问题：
1）Baidu image search和合成的29K不公开？
2）public数据是怎么配比的？
3）icdar 2011谁有下载链接啊，万分感谢！！（官网的下载不了，注册一直失败）

**Comment by LDOUBLEV** [comment]
> 1. Baidu image search和合成的29K不公开？

暂没有公开计划

> public数据是怎么配比的？

1:1

**Comment by June-Li** [comment]
> 

1）MSRA-TD是200测试+300训练，ppocr是全部500用来训练吗？
2）CCPD有30万也是全部参与训练吗？
3）假如这两个数据集MSRA-TD和CCPD，是怎么做1：1的？
