### ISSUE TITLE
2.3识别模型训练细节

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleOCR#4819]
我目前替换了backbone网络结构，所以想重新训练模型。请问一下，训练2.3版本的识别模型你们大概用了多长时间？我看论文中写的17.9M数据跑了800轮。我目前是V100 4卡的机器，我这边粗略算了下需要很长时间，你们训练的时候是什么配置呢？

**Comment by LDOUBLEV** [comment]
2.3的识别训练模型，全量数据训练大概是V100*8 训练一周时间

**Comment by bupt906** [comment]
你们合成1600w数据的时候，有什么策略吗？还是直接用text tender合成

**Comment by ldd91** [comment]
@LDOUBLEV  有实验环境的具体介绍吗
