### ISSUE TITLE
 training the det model is stuck

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#482]
![image](https://user-images.githubusercontent.com/12640462/89276260-0533fe80-d676-11ea-9785-877f3bb6060b.png)

The training process seems to be stuck，there is not any log info in 30min.
Hope for your reply,thx

**Comment by MissPenguin** [comment]
evaluation in east is slow when use python version locality-aware nms.

**Comment by MissPenguin** [comment]
Evaluation in east is slow when use python version locality-aware nms.

Try c++ version locality-aware nms which is much faster by switch your python version to python3.5. https://github.com/PaddlePaddle/PaddleOCR/blob/a0c8968c96b11982f8806bd05c6cb4ece5f6b068/ppocr/postprocess/east_postprocess.py#L80

**Comment by BeyondYourself** [comment]
Thank you for solving my puzzle.
