### ISSUE TITLE
paddlehub 的 bert_serving 和 默认的flask 有啥区别？

### ISSUE THREAD

**Issue by linxi-1214** [PaddlePaddle/PaddleOCR#4820]
1. paddlehub 的 bert_serving 和 默认的flask 有啥区别？
2. 根据 deploy/docker/gpu 下的Dockfile 打包的镜像，能用bert_serving 吗？

**Comment by LDOUBLEV** [comment]
bert_sering 的问题在Paddlehub下提问吧
https://github.com/PaddlePaddle/PaddleHub/issues
