### ISSUE TITLE
ocr识别的时候内存一直在增加

### ISSUE THREAD

**Issue by wu0211** [PaddlePaddle/PaddleOCR#4821]
比如说识别几十张，内存就一直在增长，cpu也很高

**Comment by LDOUBLEV** [comment]
你的软硬件环境，包括，paddle版本，cuda，cudnn版本，CPU预测 or GPU预测？

刚在paddle2.1+cuda10.2+cudnn7.6(CPU | V100 GPU )上测试了识别预测，没有出现连续预测后内存持续增涨问题

CPU利用率高是正常的

**Comment by Achelics** [comment]
同样遇到Python 版本使用CPU进行识别时，内存出现了一直增长的问题，没有释放内存

**Comment by Achelics** [comment]
> 比如说识别几十张，内存就一直在增长，cpu也很高

升级paddleocr版本到2.3.0以上，这个问题在后续版本中解决了
