### ISSUE TITLE
Training Sentence Recognition (Predicting the text of a line image directly)

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#4825]
I'm trying to train a sentence recognition model for printed documents, but I'm stuck knowing which model and model configuration to use?
is CRNN a good choice regarding that or using a different model will be better?
I can see that the system can do that for printed documents and the detection already picks up sentences rather than words.
Any one can help.

![image](https://user-images.githubusercontent.com/29528270/144443313-23056758-03b6-43be-a330-f009e9c5a860.png)

**Comment by LDOUBLEV** [comment]
DB+CRNN is recommended for print document recognition.

The detection algorithm doc is 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/detection_en.md
The corresponding config files are https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/configs/det

The recognition algorithm doc is 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/recognition_en.md

The corresponding config files are https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/configs/rec

**Comment by bely66** [comment]
Okay, so it's CRNN.
I can see in the Recognition link that it's using words not sentences in the Recognition, How is the above image is recognized as a sentence then? 
![image](https://user-images.githubusercontent.com/29528270/144555796-53ce28ea-6013-417e-b063-2e4cda6f6f22.png)

**Comment by LDOUBLEV** [comment]
The label of the training data used by the model used to obtain the above results is sentence-level. 

You can train the CRNN model using word-level labeled data, then its prediction results are also word-level.

**Comment by bely66** [comment]
Thanks I get that.
But how can I do a sentence level training? What’s the recommended size of input images? Maximum and Minimum number of words in a sentence image?

**Comment by bely66** [comment]
Anyone?

**Comment by LDOUBLEV** [comment]
> But how can I do a sentence level training? 

Just train using sentence-level dataset.

> What’s the recommended size of input images?

3, 32, 100 or 3, 32, 320

> Maximum and Minimum number of words in a sentence image?

You can get both them from your training data.

**Comment by bely66** [comment]
Thanks for your reply!
I'll be generating the Training Data so that's why I'm asking.
between 2-9 words is good or less than that is good?
and does increasing the number of words affects the size of the dataset? for example does more words means more data points needed?

**Comment by soufieneghribi** [comment]
Is this possible in arabic? And do we user use-space-char=True? or we just put space character in the dictionnary?

**Comment by Aminfaraji** [comment]
> Thanks for your reply! I'll be generating the Training Data so that's why I'm asking. between 2-9 words is good or less than that is good? and does increasing the number of words affects the size of the dataset? for example does more words means more data points needed?

Were you able to train the paddleocr model at the sentence level?
