### ISSUE TITLE
Error with german model

### ISSUE THREAD

**Issue by maylad31** [PaddlePaddle/PaddleOCR#4826]
hello, your library is really good. However when i try this code for german:
from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(lang='german') # need to run only once to download and load model into memory
img_path = 'ocr1.jpg'
result = ocr.ocr(img_path)
for line in result:
    print(line)

i get error list index out of range...

**Comment by Gmgge** [comment]
你好，我复现了此bug，你可以你程序报错前的输出中找到**Namespace**(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\15750/.paddleocr/2.3.0.2\\ocr\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\15750/.paddleocr/2.3.0.2\\ocr\\det\\en\\en_ppocr_mobile_v2.0_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='german', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, ocr_version='PP-OCRv2', output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='D:\\software\\Anaconda3\\envs\\ocr_py37\\lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\german_dict.txt', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\15750/.paddleocr/2.3.0.2\\ocr\\rec\\german\\german_mobile_v2.0_rec_infer', save_log_path='./log_output/', show_log=True, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=True)，找到其中的 **rec_char_dict_path**，在这个**german_dict.txt**末尾添加一个字符，例如 ¬ 来解决这个问题。

该问题为何出现？
1.german的字典为143个字符，根据代码可以看出，添加空格字符之后144，添加特殊字符之后145，然后将german的rec模型（该模型存放位置同样可以在Namespace中发现，位于**rec_model_dir**）的inference.pdmodel放入[该位置](https://netron.app/)可以看到最后的输出维度为146，因此维度不匹配。
2.因为我不懂德语，不知道是否是字典遗漏或者是其他地方出错，需要相关人员进行解答。
