### ISSUE TITLE
ocr 这种识别情况怎么搞，怎么使用模型

### ISSUE THREAD

**Issue by wu0211** [PaddlePaddle/PaddleOCR#4827]
paddleocr 逗号没有识别出来，但是用paddlehub 就可以
![image](https://user-images.githubusercontent.com/34398833/144533683-3da9086f-5f1a-43f4-89e7-118e9ca1d1e7.png)

有现有的模型使用案例么
![image](https://user-images.githubusercontent.com/34398833/144533736-b75a8a25-5254-42c4-b73d-fecf4183195a.png)

**Comment by tink2123** [comment]
V2 的模型做了更新，可能对部分标点符号的识别效果有波动，如果hub可用的话，可以尝试使用 Paddleocr 2.0 的模型进行预测：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md
![image](https://user-images.githubusercontent.com/31891223/145210128-404eecad-df96-4a92-88cb-d2a3e40a224d.png)
