### ISSUE TITLE
多机多卡训练

### ISSUE THREAD

**Issue by yulinxuanzhi** [PaddlePaddle/PaddleOCR#4829]
1. 对于多台网络设备的分布式训练如何启动？
2. 从机需要放数据吗？从机会不会自动从主机取数据，目前只有主机有数据

**Comment by tink2123** [comment]
分布式训练可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_cn.html
