### ISSUE TITLE
能提供一些版面分析的例子吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#483]

**Comment by dyning** [comment]
感谢反馈，后面在repo建设时，考虑会添加一些。如果方便的画，也辛苦提供下你关心的一些实际场景应用背景。

**Comment by deep-practice** [comment]
比较关心证件识别的场景，比如身份证，户口本，行驶证这些
在识别出每行的文本之后，怎样去有效的把关键字段提取出来

**Comment by dyning** [comment]
好的，我们后面在repo建设时，考虑下这些典型场景。
