### ISSUE TITLE
请问有没有openvino的demo可以参考

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#4834]
请问各位大佬，有没有c++版本的openvino的demo可以参考一下？

**Comment by WenmuZhou** [comment]
暂时没有哈

**Comment by Dandelion111** [comment]
> 暂时没有哈

大佬后期会有吗？有没有ppocr的paddlepaddle模型转换为openvino模型的方法可以参考呢？
