### ISSUE TITLE
安卓手机使用自定义模型进行调试，手机重启

### ISSUE THREAD

**Issue by 358788887** [PaddlePaddle/PaddleOCR#4836]
参考地址：https://aistudio.baidu.com/aistudio/projectdetail/619352
硬件环境：安卓arm8
使用自己训练的检测模型，识别模型为arabic_ppocr_mobile_v2.0_rec_infer。

执行命令： ./ocr_db_crnn arabic_mv3_det.nb arabic_mv3_crnn.nb oneword.png arabic_dict.txt，10秒左右手机重启

**Comment by WenmuZhou** [comment]
你好 参考动态图分支的lite教程看看呢

**Comment by 358788887** [comment]
> 

谢谢回复
