### ISSUE TITLE
@WenmuZhou 我也遇到了这样的问题，gpu模式下会有这样的问题，cpu模式下模型推理正常执行。

### ISSUE THREAD

**Issue by sucre111** [PaddlePaddle/PaddleOCR#4837]
@WenmuZhou 我也遇到了这样的问题，gpu模式下会有这样的问题，cpu模式下模型推理正常执行。

_Originally posted by @Amanda-Barbara in https://github.com/PaddlePaddle/PaddleOCR/issues/4775#issuecomment-985235666_

但我CPU和GPU都有这个问题

**Comment by WenmuZhou** [comment]
已关闭，在原问题下进行讨论
