### ISSUE TITLE
MacBook M1 (Apple Silicon)

### ISSUE THREAD

**Issue by JakobStadlhuber** [PaddlePaddle/PaddleOCR#4838]
Are there plans for supporting Apple Silicon?

If I try to install paddlepaddle I get this error:

`pip install paddlepaddle`

`ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle`

**Comment by littletomatodonkey** [comment]
you can try the following command,paddle works fine for me on my M1 mac.

```bash
python -m pip install paddlepaddle==2.2.0 -i https://mirror.baidu.com/pypi/simple
```

**Comment by JakobStadlhuber** [comment]
@littletomatodonkey do you use an arm version of conda? Could it be that you installed python, pip... through roseta, this is default if you install anaconda on an M1 mac.

**Comment by Evezerest** [comment]
paddle can be installed successfully on M1 chip through Rosetta according to [this doc](https://www.paddlepaddle.org.cn/documentation/docs/en/install/index_en.html), pls tell me if you need an arm version of paddle

**Comment by ribilynn** [comment]
For now, on my M1 Pro mac, I can install PaddleOCR natively via pip but can't run it because paddle is not supported natively on M1 Pro, even though the Paddle team says that it is supported on M1. Maybe it only supports M1 literally but not the other arm64 platforms.
Is there anything I'm missing?

**Comment by Ryojikn** [comment]
It seems for me that paddleocr is installing normally on Mac M1 Air, however it breaks when trying to install opencv contrib.


Is it possible to update contrib to point out to the latest opencv? Opencv is now working on Mac m1 (arm)

**Comment by fdciabdul** [comment]
> It seems for me that paddleocr is installing normally on Mac M1 Air, however it breaks when trying to install opencv contrib.
> 
> Is it possible to update contrib to point out to the latest opencv? Opencv is now working on Mac m1 (arm)

build by yourself 

https://docs.opencv.org/4.x/d0/db2/tutorial_macos_install.html

**Comment by ah161652** [comment]
Any update on this? There still seems to be no compatibility for PaddleOCR on Apple Silicon.
