### ISSUE TITLE
修改训练图像大小

### ISSUE THREAD

**Issue by zeze1111** [PaddlePaddle/PaddleOCR#484]
https://github.com/PaddlePaddle/X2Paddle/issues/326
训练文字检测模型时将image_shape:[3, 640, 640]改为[3, -1, ,1]之后会在创建网络结构的时候出现错误，不论是resnet还是movilenetv3都会有这个错误，应该是必须指定图像大小的意思。想咨询一下可以是否可以不指定输入图像大小进行训练？

**Comment by LDOUBLEV** [comment]
图像大小改成[3, -1, 1]不太合理，不指定输入图像大小进行训练需要改一下代码，image_shape:[3, 640, 640]不用变，数据处理时不做resize，并且把batch_size改为1， 训练时输入原图就行。

**Comment by zeze1111** [comment]
> 图像大小改成[3, -1, 1]不太合理，不指定输入图像大小进行训练需要改一下代码，image_shape:[3, 640, 640]不用变，数据处理时不做resize，并且把batch_size改为1， 训练时输入原图就行。

不做resize比较好理解，为啥要把batch_size改为1？train_batch_size_per_card 和 test_batch_size_per_card都改为1吗？

**Comment by LDOUBLEV** [comment]
> > 图像大小改成[3, -1, 1]不太合理，不指定输入图像大小进行训练需要改一下代码，image_shape:[3, 640, 640]不用变，数据处理时不做resize，并且把batch_size改为1， 训练时输入原图就行。
> 
> 不做resize比较好理解，为啥要把batch_size改为1？train_batch_size_per_card 和 test_batch_size_per_card都改为1吗？

训练输入数据是batch形式的，如果支持变长输入，每个图像大小不一样，没办法组成batch，所以只能把batchsize设置为1
