### ISSUE TITLE
我希望将 mobile demo 的 opencv 版本升级到4.5.4

### ISSUE THREAD

**Issue by Albert556** [PaddlePaddle/PaddleOCR#4841]
我希望将 mobile demo 的 opencv 版本升级到4.5.4，但是用官方cmake编译出的静态库太大，如何减小静态库的大小

**Comment by Gmgge** [comment]
有个相关[项目](https://github.com/nihui/opencv-mobile)，不知道是否符合你的需求。

**Comment by Albert556** [comment]
我直接使用了官方编译的静态库，opencv-mobile这个项目我没有尝试，他减去了一些我需要的函数
