### ISSUE TITLE
table_structure模型有服务端用的模型吗？

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/PaddleOCR#4842]
RT, 目前的预训练模型是轻量级的，请问有服务端用的性能更好的模型吗

**Comment by MissPenguin** [comment]
可以自己替换resnet系列backbone训练更大的模型哈

**Comment by HaoLiuHust** [comment]
> 可以自己替换resnet系列backbone训练更大的模型哈

layout的模型有用中文数据集训练的嘛

**Comment by MissPenguin** [comment]
> > 可以自己替换resnet系列backbone训练更大的模型哈
> 
> layout的模型有用中文数据集训练的嘛

也没有现成的模型，需要自己换数据训一下😂
