### ISSUE TITLE
旋转图片检测的问题

### ISSUE THREAD

**Issue by qypf** [PaddlePaddle/PaddleOCR#485]
我发现不管是轻量级还是通用模型，当图片顺时针旋转0-90的，或者270-360度时，检测结果都还行，但是在90-270度的范围内就无法识别，这种情况需要图片旋转180度之后再识别，请问有什么效果好的自适应预处理方案吗，我尝试了几个文字方向检测模型，在我的数据集上，正确率都不高，平均50%左右。

**Comment by LDOUBLEV** [comment]
> 我发现不管是轻量级还是通用模型，当图片顺时针旋转0-90的，或者270-360度时，检测结果都还行，但是在90-270度的范围内就无法识别，这种情况需要图片旋转180度之后再识别，请问有什么效果好的自适应预处理方案吗，我尝试了几个文字方向检测模型，在我的数据集上，正确率都不高，平均50%左右。

文字旋转90-270度时，把文本转正，此时文字方向是反着的（180度旋转），目前支持的不太好，一个好的方案就是加文字方向分类器，当判断出文字方向是倒着时，先旋转180度再去识别。

**Comment by Hupengyu** [comment]
> > 我发现不管是轻量级还是通用模型，当图片顺时针旋转0-90的，或者270-360度时，检测结果都还行，但是在90-270度的范围内就无法识别，这种情况需要图片旋转180度之后再识别，请问有什么效果好的自适应预处理方案吗，我尝试了几个文字方向检测模型，在我的数据集上，正确率都不高，平均50%左右。
> 
> 文字旋转90-270度时，把文本转正，此时文字方向是反着的（180度旋转），目前支持的不太好，一个好的方案就是加文字方向分类器，当判断出文字方向是倒着时，先旋转180度再去识别。

2.0版本并没有看到文字方向分类器啊，cls分类器感觉并没有对图像进行处理啊

**Comment by Hupengyu** [comment]
> 我发现不管是轻量级还是通用模型，当图片顺时针旋转0-90的，或者270-360度时，检测结果都还行，但是在90-270度的范围内就无法识别，这种情况需要图片旋转180度之后再识别，请问有什么效果好的自适应预处理方案吗，我尝试了几个文字方向检测模型，在我的数据集上，正确率都不高，平均50%左右。
根本就没有方向检测，那个方向分类器的作用是什么我到现在也没看懂
