### ISSUE TITLE
下划线“_”识别不到

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/PaddleOCR#4850]
因为业务需要需要识别设备上的一些菜单参数。直接使用paddle训练好的好的模型：ch_ppocr_mobile_v2.0 用于检测和识别

大部分字符可以识别出来，但是下划线不行，如下图，这个需要设置什么参数之类的才能识别出来吗？
还是要准备相关的数据进行训练才能提高识别精度？
![image](https://user-images.githubusercontent.com/37790151/144945901-834ff1a7-d09c-4131-864b-43efd63309ea.png)

**Comment by LDOUBLEV** [comment]
看上去是检测框没有包围到_，建议稍微加大unclip_ratio参数，或者设置use_dilation为True
