### ISSUE TITLE
关于字符带有边框的标注问题

### ISSUE THREAD

**Issue by Morgan-Gan** [PaddlePaddle/PaddleOCR#4852]
![3](https://user-images.githubusercontent.com/56434355/144954240-51e55bf5-8f3c-4c90-abd5-b211c1e72708.jpg)
图1 原图
![3](https://user-images.githubusercontent.com/56434355/144955017-953ec6ec-d9f3-490a-b3b2-abe60cf55c19.jpg)
图2 标注1
![32](https://user-images.githubusercontent.com/56434355/144955037-7c008d7c-53a1-46c7-9e7b-92385fa2ea46.jpg)
图3 标注2
大家好，请教一下，这个关于字符有边框的文本（如图1）大家是怎么标注，用检测网络DBNet和识别网络CRNN识别效果都比较好呢？是挨着这个框标注如图2标注1，还是把框也标注到里面去，如图3标注2呢？其中，黑线框表示原图字符边框，红色框表示标注框。

**Comment by LDOUBLEV** [comment]
用标注2吧，对于扰动，尽可能包含到数据里，训练中会学习避开这些扰动得到正确的识别结果

**Comment by Morgan-Gan** [comment]
> 用标注2吧，对于扰动，尽可能包含到数据里，训练中会学习避开这些扰动得到正确的识别结果

你好，您说是用图3标注2把干扰的边框也包含到数据里面去训练是吧，谢谢答复哈
