### ISSUE TITLE
paddleOCR标注顺序

### ISSUE THREAD

**Issue by zhihaofan** [PaddlePaddle/PaddleOCR#4855]
使用paddleOCR的标注工具的时候，文件夹里边的图片顺序和标注生成的txt文件中的顺序不一致没关系吧，匹配的时候是按照名字做匹配的吧

**Comment by LDOUBLEV** [comment]
> 文件夹里边的图片顺序和标注生成的txt文件中的顺序不一致没关系吧

没关系

> 匹配的时候是按照名字做匹配的吧

是的

**Comment by zhihaofan** [comment]
> 

好的，谢谢
