### ISSUE TITLE
PPOCRLabel  按shift键 必闪退

### ISSUE THREAD

**Issue by CoderHaay** [PaddlePaddle/PaddleOCR#4858]
win10 系统，虚拟环境安装的PPOCRLabel  ，只要按键，必闪退。
Traceback (most recent call last):
  File "d:\python_demo\venv\lib\site-packages\PPOCRLabel\libs\canvas.py", line 709, in keyPressEvent
    self.shapesBackups.pop()
IndexError: pop from empty list

**Comment by kangbo750** [comment]
这个报错我也遇到了，目前还不知道怎么解决。还有一个报错是，Traceback (most recent call last):
  File "C:\Users\Lenovo\PaddleOCR\PPOCRLabel\libs\autoDialog.py", line 39, in run
    h, w, _ = cv2.imdecode(np.fromfile(Imgpath, dtype=np.uint8), 1).shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Evezerest** [comment]
更新一下代码吧，dygraph分支已经修复了

> win10 系统，虚拟环境安装的PPOCRLabel ，只要按键，必闪退。 Traceback (most recent call last): File "d:\python_demo\venv\lib\site-packages\PPOCRLabel\libs\canvas.py", line 709, in keyPressEvent self.shapesBackups.pop() IndexError: pop from empty list
