### ISSUE TITLE
可以只识别特地类型的的文字吗？

### ISSUE THREAD

**Issue by myfjdthink** [PaddlePaddle/PaddleOCR#486]
如图，我想让检测模型只识别深黑色的文字（红色箭头指向的），而不是识别所有文字，我应该怎么训练模型？
在预训练模型的基础上做可以吗？

![image](https://user-images.githubusercontent.com/2044143/89371928-4cbe9700-d717-11ea-9c47-3c8404e30c94.png)

**Comment by dyning** [comment]
是不是可以加个简单的文字颜色分类器？训练一个分类模型

**Comment by LDOUBLEV** [comment]
> 如图，我想让检测模型只识别深黑色的文字（红色箭头指向的），而不是识别所有文字，我应该怎么训练模型？
> 在预训练模型的基础上做可以吗？
> 
> ![image](https://user-images.githubusercontent.com/2044143/89371928-4cbe9700-d717-11ea-9c47-3c8404e30c94.png)

如果你的场景类似这样比较固定，你可以用我们的模型在你的这个数据上fine-tune下，你的数据只标注出想检测的文本

**Comment by myfjdthink** [comment]
我在MobileNetV3的预训练模型的基础上，训练了对特定文本的检测，如图，可以识别出 ID 了。
![image](https://user-images.githubusercontent.com/2044143/89484717-a6839780-d7d1-11ea-94e0-2e7097cc4fc1.png)

如果我想在 ID 的基础上继续训练，应该怎么做呢？ 这份教程里没有说 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md

而且我训练好的模型格式和 MobileNetV3 预训练模型格式不一样，应该是不能直接把刚刚训练好的模型作为预训练模型的。
@LDOUBLEV

**Comment by LDOUBLEV** [comment]
可以把刚刚训练好的模型作为预训练模型，继续训练模型的时候，把之前训练好的模型路径，赋给Global.checkpoints 或者替换MobileNetV3 预训练模型路径Global.pretrain_weights。

**Comment by myfjdthink** [comment]
感谢， 配置 Global.checkpoints 参数可以继续训练。

另一个问题：
我在检测 ID（上图高亮部分） 的基础上再训练，想让模型可以识别左下角的日期，测试数据都是标注日期的，没有包括ID，训练完成后，模型编程只能识别日期了。

感觉是日期的检测把 ID 检测覆盖了，而不是在 ID 的基础上做增强的。
为什么是这样的？
@LDOUBLEV

**Comment by deep-practice** [comment]
你为什么不同时标注两个呢

**Comment by myfjdthink** [comment]
> 你为什么不同时标注两个呢

可以同时标注，但这样就没法渐进式地去优化模型了

**Comment by MissPenguin** [comment]
> 感谢， 配置 Global.checkpoints 参数可以继续训练。
> 
> 另一个问题：
> 我在检测 ID（上图高亮部分） 的基础上再训练，想让模型可以识别左下角的日期，测试数据都是标注日期的，没有包括ID，训练完成后，模型编程只能识别日期了。
> 
> 感觉是日期的检测把 ID 检测覆盖了，而不是在 ID 的基础上做增强的。
> 为什么是这样的？
> @LDOUBLEV

因为你训练日期的时候，id部分又被当作背景了，对模型的已有能力进行了干扰，所以无法再检测到id。

可以考虑在训练日期的时候，把id部分盖掉，同理，后面想要再增加一个字段的检测时，需要在训练数据中把模型已经支持的id、日期部分都盖掉，避免对模型已有能力的干扰。所以，最方便还是尽量一次性训好，减少迭代次数，数据处理起来更方便～
