### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by techkang** [PaddlePaddle/PaddleOCR#4863]
如下是我关于PPOCR的一些优化建议

## level1
该等级的可优化点主要为格式方面

| 位置 | 描述 |  改进方法 |
| --- | --- | --- |
| - | 无编码规范及检查工具，导致经常出现未使用的变量、命名不规范、代码单行内字符数不统一等问题 | 规定pep8为编码规范，并提供black，isort，flake8等工具 |
| .github | 无ISSUE_TEMPLATE | 添加对于提交bug/问题等的指引 |
| setup.py | python 版本描述有误，代码中出现多处python3.6独有特性（f-string） | 限制代码版本为3.6 |
| *.py | 有多处代码有from \_\_future\_\_ import ...，但所引入的特性在python3开始已经为强制规定 | 删去这些代码 | 
| tools/program.py#L197 | 代码冗长，也体现出没有默认参数的缺点 | 代码改为 start_epoch = best_model_dict.get('start_epoch', 1)，且应当设计配置体系层级，从base-config，到rec-config，到crnn-config，依次更改最少量的参数 |
| *.py | 代码中字符串format格式不统一，有.format, %, f-string等 | 推荐全部使用f-string，方便阅读（代价就是必须使用Python3.6+） |

## level2
该等级的可优化点主要为代码设计模式

| 位置 | 描述 |  改进方法 |
| --- | --- | --- |
| tools | infer有多个入口 | 整合到同一个入口 |
| tools/program.py#L92 | 使用yaml.load加载参数，导致返回一个自定义的AttrConfig，无法固定参数，可能会被错误修改 | 使用yacs加载参数 |
| tools/train.py#L124 | 捕获所有异常，但并没有抛出 | 删去此处代码 |
| tools/program.py#L142 | train函数长达200多行，导致：a.如果需要稍微修改训练逻辑，则需要重写整个函数 b.代码难以阅读，导致查找难以定位，问题成因是设计整个训练逻辑时，是面向过程编程，而非面向对象编程 | 设计一个Trainer类，将需要传递的中间变量用类属性保存，拆分各个函数 |
| tools/program.py#L401 | 硬编码了所有支持的算法 | 将这些算法用一个大写常量表示 |
| tools/program.py#L59 | 传参时使用“=”分隔，这样会导致填写路径时无法使用tab自动补全 | 修改为--config path/to/config.yaml 式传参 |
| ppocr/data/imaug/label_ops.py | 代码大量重复 | 应当将重复代码设计为一个BaseClass，供子类调用 |
| ppocr/data/\_\_init\_\_.py#59 | 直接抛出Exception，信息不足 | 抛出ValueError更合理一点 |
| ppocr/data/\_\_init\_\_.py#64 | 使用了eval函数，虽然之前有`assert`保证安全，但还是应当尽量避免 | 解决方案：手动构建dict；使用Register自动生成一个dict；用getattr替代eval |

## level3
该等级的可优化点主要为可能存在的性能问题

| 位置 | 描述 |  改进方法 |
| --- | --- | --- |
| tools/program.py#L201 | 多次创建dataloader | 写一个distributed_sampler，作为参数传给dataloader |
| tools/program.py#L410 | 多卡训练时，会多次写入同一文件，可能导致io错误 | 判断条件加一个是否是主进程 |
| tools/program.py#L64 | 类直接继承自dict，可能导致意料之外的错误（参见Fluent Python v2: Example 14.2） | 将父类改为collections.UserDict |

## level4
该等级的可优化点主要为兼容性问题

| 位置 | 描述 |  改进方法 |
| --- | --- | --- |
| requirements.txt:#L10 | 对多个包限定了严格的版本 | 例如opencv可以通过禁用OpenGL提高兼容性，其他包也应尝试寻找不兼容的原因 |

## level NaN
关于paddle的问题

| 位置 | 描述 |  改进方法 |
| --- | --- | --- |
| paddle/fluid/dataloader/batch_sampler.py#L165 | 创建了一个叫DistributedBatchSampler的类，该类完成了DistributedSampler+BatchSampler两个任务，因此这个类重复完成了BatchSampler类的一些功能，重复造轮子且代码复杂 | 删掉这个类，实现DistributedSampler类 |
| paddle/fluid/dataloader/dataset.py#L68 | Dataset类的`__init__`没有实现任何功能，此处应当直接删掉，否则实现子类时，IDE会提示需要继承父类的`__init__` | 删掉这个类，实现DistributedSampler类 |

**Comment by LDOUBLEV** [comment]
感谢反馈，我们会内部自查下，不过由于任务排期较满，可能暂时没时间优化代码结构，不过欢迎外部开发者给我们贡献代码或者文档，贡献者的ID我们也会加到贡献者列表里。

**Comment by GivanTsai** [comment]
非常Nice的建议，同意
