### ISSUE TITLE
文字检测训练，评估会随机卡住

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#4864]
在进行文字检测训练的时候，到评估的时候就会随机卡住不动
代码版本：release/2.3
paddlepaddle版本：paddlepaddle_gpu-2.0.2.post110，
![image](https://user-images.githubusercontent.com/15188456/145128714-919d1b34-eeda-415b-8969-307405619651.png)
训练模式：gpu训练
很无解，也不报错，从卡住到发issues已经过去12个小时
![image](https://user-images.githubusercontent.com/15188456/145128872-e70c593a-1b1d-48be-b22f-535e2a57ee84.png)
![image](https://user-images.githubusercontent.com/15188456/145128975-dcb97cb5-0e53-4c55-8ff6-a672da914fc0.png)

**Comment by Atiuiee** [comment]
昨晚跑了2次遇到了同样的问题
paddlepaddle-gpu 2.2.0.post112
显存11G，训练集3万，验证集5千

**Comment by lxhmark7** [comment]
我的评估过程中直接中断

**Comment by LDOUBLEV** [comment]
用的哪个模型？

只运行评估是否正常？

**Comment by YY007H** [comment]
> 用的哪个模型？
> 
> 只运行评估是否正常？

![image](https://user-images.githubusercontent.com/15188456/145320576-00456f8e-dccf-4038-8404-61f11a3b4d1c.png)
随机发生，无法复现，我上面的截图就是第50次和第120次评估时候卡住的，有时候会卡住，有时候不会卡住，也不报错，找不到是什么原因。

昨天训练的，半夜11点23的时候又卡住的
![image](https://user-images.githubusercontent.com/15188456/145320941-78860b92-84f3-4a1b-ade3-1ad23620a220.png)

**Comment by Atiuiee** [comment]
> 
我也是用的这个

**Comment by LDOUBLEV** [comment]
> 随机发生，无法复现

刚在我自己的数据上测试没有出现卡住，可能是数据集原因和机器环境问题；
建议：
先单独运行评估，并关闭数据shuffle，设置num_workers:0，use_shared_memory:False；看是否出现报错

**Comment by YY007H** [comment]
> 并关闭数据shuffle，设置num_workers:0

设置shuffle:false和num_workers:0，use_shared_memory默认，训练了5000轮，没有出现卡住的情况，不知道是什么原因

**Comment by Atiuiee** [comment]
我没有关闭shuffle，num_workers也按自己需求设置了，use_shared_memory默认
只改回了这个参数eval_batch_step: [3000, 2000]，没有出现卡住了，之前设的比较小
别人的解释是，早期高频率验证，会导致过多框没有被消除，从而卡住

**Comment by YY007H** [comment]
> > 随机发生，无法复现
> 
> 刚在我自己的数据上测试没有出现卡住，可能是数据集原因和机器环境问题； 建议： 先单独运行评估，并关闭数据shuffle，设置num_workers:0，use_shared_memory:False；看是否出现报错

设置num_workers:0后，测试了一周了，没有再出现过卡住的情况
