### ISSUE TITLE
关于使用center loss

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleOCR#4865]
将center loss加入训练，发现会有如图的问题：最开始loss会从一个很低的值升高。这是什么原因呢？center loss的初始权重是从预训练模型中得到的，center loss权重设置为0.05
![aa](https://user-images.githubusercontent.com/41312357/145139844-073f89fc-bd57-461e-ba8c-3cd686cfb011.jpg)

**Comment by Intsigstephon** [comment]
你是在自己的数据集上面训练的吗，对应的字符集是什么呢

**Comment by bupt906** [comment]
> 你是在自己的数据集上面训练的吗，对应的字符集是什么呢

是的，我在2.3版本的基础上做的微调，字符集是用的paddleOCR提供的，6625个。微调数据大概200W。center loss初始权重是用2.3模型得到的。

**Comment by Zhang-O** [comment]
> 

你在所有的训练数据上微调还是只在识别正确的训练数据上微调？

**Comment by Zhang-O** [comment]
> > > 
> > 
> > 
> > 你在所有的训练数据上微调还是只在识别正确的训练数据上微调？
> 
> 在所有的训练数据上

试试只在训练集中识别正确的数据上训练试试，我这边在所有训练集上，效果不是很理想，center loss权重设置为0.25，0.1， 0.02

**Comment by bupt906** [comment]
> > > > 
> > > 
> > > 
> > > 你在所有的训练数据上微调还是只在识别正确的训练数据上微调？
> > 
> > 
> > 在所有的训练数据上
> 
> 试试只在训练集中识别正确的数据上训练试试，我这边在所有训练集上，效果不是很理想，center loss权重设置为0.25，0.1， 0.02，都试了，也不知道哪里除了问题

都能识别正确的数据再训练没有意义啊

**Comment by Zhang-O** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你在所有的训练数据上微调还是只在识别正确的训练数据上微调？
> > > 
> > > 
> > > 在所有的训练数据上
> > 
> > 
> > 试试只在训练集中识别正确的数据上训练试试，我这边在所有训练集上，效果不是很理想，center loss权重设置为0.25，0.1， 0.02，都试了，也不知道哪里除了问题
> 
> 都能识别正确的数据再训练没有意义啊

说是这样说，我准备在识别正确的数据上再 试试，看看有没有什么不一样，有结果了我在这里同步下

**Comment by bupt906** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 你在所有的训练数据上微调还是只在识别正确的训练数据上微调？
> > > > 
> > > > 
> > > > 在所有的训练数据上
> > > 
> > > 
> > > 试试只在训练集中识别正确的数据上训练试试，我这边在所有训练集上，效果不是很理想，center loss权重设置为0.25，0.1， 0.02，都试了，也不知道哪里除了问题
> > 
> > 
> > 都能识别正确的数据再训练没有意义啊
> 
> 说是这样说，我准备在识别正确的数据上再 试试，看看有没有什么不一样，有结果了我在这里同步下

好的

**Comment by nissansz** [comment]
导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。

**Comment by nissansz** [comment]
导出的center loss文件train_center.pkl怎么使用？加入yml文件报错了。

#Loss:
#  name: CTCLoss
Loss:
  name: CombinedLoss
  loss_config_list:
  - CTCLoss:
      use_focal_loss: false
      weight: 1.0
  - CenterLoss:
      weight: 0.05
      num_classes: 63466
      feat_dim: 512
      center_file_path: C:/F/pycharm2020.2/PaddleOCR-release-2.5/train_center.pkl
  # you can also try to add ace loss on your own dataset
  - ACELoss:
      weight: 0.1

 报错如下

 Traceback (most recent call last):
  File "./tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "./tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
    loss = loss_func(input, batch, **kargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in __call__
    assert isinstance(predicts, (list, tuple))
AssertionError


![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/8546e87e-5e35-4b2f-bcd5-fcb602cd3c40)
