### ISSUE TITLE
如何对文本框检测的结果进行再分类

### ISSUE THREAD

**Issue by skw1975** [PaddlePaddle/PaddleOCR#4866]
目前的文本框检测出来都是一分类，如果想对文本框检测的结果进行多分类应该如何做呢，请教。

**Comment by tink2123** [comment]
可以文本检测后再添加一个方向分类器，补充多分类。可参考现有的方向分类器

**Comment by yangy996** [comment]
https://blog.csdn.net/YY007H/article/details/124491217
