### ISSUE TITLE
单卡多docker部署predict.run为何会互相等待

### ISSUE THREAD

**Issue by karl-tao-zhang** [PaddlePaddle/PaddleOCR#4871]
self.predictor.run([norm_img_batch])
这一行的耗时测试
我将项目用多个docker启动 然后同一张图片的所有框分成4部分来交给4个docker检测
如果4个docker在同一张卡上 耗时和用1个时间一样 但是如果我把4个项目分到4张卡上 耗时就会缩短4倍
请问这个问题有什么办法可以隔绝开吗
我觉得是虽然用了docker但是他们还是共用了同样的cuda
有没有好的解决方案

**Comment by tink2123** [comment]
这个应该没有办法，选择同一张卡的话，cuda不会因为docker不同而分开计算。
