### ISSUE TITLE
请教一下：小语种阿拉伯字，模型转nb后，识别不正确了

### ISSUE THREAD

**Issue by 358788887** [PaddlePaddle/PaddleOCR#4873]
训练服务器和本地电脑测试inference没有问题，使用lite opt转成nb后手机端识别测试就不正确了。
下图为手机-服务器-电脑测试后的结果
<img width="1207" alt="q" src="https://user-images.githubusercontent.com/94504819/145205514-1abbf099-ca4e-4ab2-8a18-ea3983699c5d.png">

下图为inference得到的结果

![i3](https://user-images.githubusercontent.com/94504819/145320392-4b8276d7-2b31-493c-b604-3f051c4a95c6.png)

**Comment by tink2123** [comment]
请问lite demo的结果是正确的吗？android demo是第三方开发的，模型更新后没有维护，如果demo预测结果是正确的，可以自己尝试调试一下android demo。

**Comment by 358788887** [comment]
> 请问lite demo的结果是正确的吗？android demo是第三方开发的，模型更新后没有维护，如果demo预测结果是正确的，可以自己尝试调试一下android demo。

您好，我没有使用demo示例来测试，我测试的方式使用 python tools/infer/predict_system.py --det_model_dir='' --rec_model_dir='' --image_dir='doc/1.png' --use_angle_cls=false --rec_char_type="arabic" --rec_char_dict_path="./ppocr/utils/dict/arabic_dict.txt" --vis_font_path="./doc/fonts/arabic2.ttf"
