### ISSUE TITLE
armv7静态库报feed  OP not found

### ISSUE THREAD

**Issue by peif1987** [PaddlePaddle/PaddleOCR#488]
根据官方提供的端侧部署示例，先编译了armv7的 Paddle-Lite库，
根据makefile文件里注释部分的提示，改为链接静态库：
1. Comment above line using `libpaddle_light_api_shared.so`
2. Undo comment below line using `libpaddle_api_light_bundled.a`

adb push 到设备上运行后，得到以下提示：

> [F  8/ 5 16:17:51.482 ...rkspace/Paddle-Lite/lite/core/program.cc:185 RuntimeProgram] Check failed: op: no Op found for feed
[F  8/ 5 16:17:51.482 ...rkspace/Paddle-Lite/lite/core/program.cc:185 RuntimeProgram] Check failed: op: no Op found for feed

 用以下命令检查libpaddle_api_light_bundled.a，可以找到feed_op.cc对应的.o文件是编译进来了，为什么会报找不到feed Op呢？
`readelf -s libpaddle_api_light_bundled.a |grep feed`

**Comment by peif1987** [comment]
链接libpaddle_light_api_shared.so的话运行是没有问题的

**Comment by LDOUBLEV** [comment]
建议用shared的链接库，貌似是lite的静态链接库有点问题
