### ISSUE TITLE
您好，想请教一下ppstructure表格识别模型的训练细节

### ISSUE THREAD

**Issue by le8888e** [PaddlePaddle/PaddleOCR#4888]
请问您可以公布更多的表格单元格检测模型en_ppocr_mobile_v2.0_table_structure的训练细节吗？
其中table_mv3.yml中structure_weight是100.0，loc_weight是10000.0，请问为什么这么设定？
我仿照table_mv3.yml将RARE的backbone替换成了ResNet，在PubTabNet数据集上训练。loc_weight是10000.0时单元格检测不准，减小为1000.0略有改善，但还是不如您公开的en_ppocr_mobile_v2.0_table_structure效果好。请问可以给一些训练的指导意见吗？谢谢

另期待您可以公开表格单元格检测的server端模型，以提升模型的泛化能力，谢谢🙏

**Comment by mingo-doer** [comment]
你好，请问你有PubTabNet的标注工具嘛

**Comment by le8888e** [comment]
> 
没有哦，用的公开的PubTabNet数据集

**Comment by le8888e** [comment]
@mingo-doer 没有哦，用的公开的PubTabNet数据集

**Comment by mingo-doer** [comment]
@le8888e  现在训练的效果怎么样呢？

**Comment by le8888e** [comment]
@mingo-doer 比百度公开的mobile模型效果差点
