### ISSUE TITLE
部署在服务器上，为啥显存不释放啊

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#489]
最近在尝试使用hub serving部署服务，但是发现任务调用服务器后，GPU显存一直不释放，越用显存显示越多，求解。
使用docker部署的服务。

**Comment by MissPenguin** [comment]
我测试多次访问8.6M模型服务，显存会涨到5G，然后就不再上涨了，跟你的情况一致吗

**Comment by ZhaoyangLi-nju** [comment]
> 我测试多次访问8.6M模型服务，显存会涨到5G，然后就不再上涨了，跟你的情况一致吗

显存一共多少啊，你是说，你测试多次，最高到5G不再涨了是嘛，并不是爆掉是嘛，我现在也是会涨很多，但是没溢出，这是什么问题尼，怎么解决尼

**Comment by MissPenguin** [comment]
修正一下，轻量模型是涨到2G，通用模型涨到5G。

不断增长是因为分配的 shape 变大了，初始化创建 tempory tensor 等等会增长，等初始化之后跑起来，shape 不增大的话应该会稳定。正常是过了最大的 shape 之后会保持稳定。 如果 shape 变小显存池尺寸也不会变小，目前机制会贪心增大但不会降低。

如果你想控制最大显存变小一点，可以减小输入图像的尺度：将params.py中的参数det_max_side_len从默认的960改成680或者更小尺度。

**Comment by ZhaoyangLi-nju** [comment]
> 修正一下，轻量模型是涨到2G，通用模型涨到5G。
> 
> 不断增长是因为分配的 shape 变大了，初始化创建 tempory tensor 等等会增长，等初始化之后跑起来，shape 不增大的话应该会稳定。正常是过了最大的 shape 之后会保持稳定。 如果 shape 变小显存池尺寸也不会变小，目前机制会贪心增大但不会降低。
> 
> 如果你想控制最大显存变小一点，可以减小输入图像的尺度：将params.py中的参数det_max_side_len从默认的960改成680或者更小尺度。

感谢，感谢，原来如此，想请问一下，如果我想提速的话，是不是增大det_max_side_len的长度是不是可以提高速度啊。或者有什么别的方法可以提高并发访问的速度吗，感谢，期待您的回复

**Comment by MissPenguin** [comment]
det_max_side_len是输入图片resize后的长边尺寸，减小可以提高预测速度

**Comment by DingLe139** [comment]
补充说明：感谢本贴各位老师的帮助，我使用hubserving连接PaddleOCR，其中包含了cls/det/rec，在寻找det_max_side_len时我发现我的包中hubserving/ocr_system/param.py中相应的参数名其实是**det_limit_side_len**，希望对其他寻找答案的人有所帮助

![paddle issue](https://github.com/PaddlePaddle/PaddleOCR/assets/65940351/1598a88b-3df4-450f-98fe-3110c13e1d34)

**Comment by Chris-Mraz** [comment]
> 修正一下，轻量模型是涨到2G，通用模型涨到5G。
> 
> 不断增长是因为分配的 shape 变大了，初始化创建 tempory tensor 等等会增长，等初始化之后跑起来，shape 不增大的话应该会稳定。正常是过了最大的 shape 之后会保持稳定。 如果 shape 变小显存池尺寸也不会变小，目前机制会贪心增大但不会降低。
> 
> 如果你想控制最大显存变小一点，可以减小输入图像的尺度：将params.py中的参数det_max_side_len从默认的960改成680或者更小尺度。

您好，目前paddleocr 2.8.0这个版本问题也还没有解决，而且我设置det_max_side_len= 480，为啥还是会继续增加，您那边找到解决办法了吗？

**Comment by GreatV** [comment]
@Chris-Mraz paddle 升级到 3.0 beta 试试看

**Comment by Chris-Mraz** [comment]
这就是另一个问题了，目前我本地cuda只支持11.7，而beta版本好像只支持cuda11.8和12.x两个版本



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2024年7月15日(周一) 晚上6:22
收件人: ***@***.***&gt;;
抄送: "Yang ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 部署在服务器上，为啥显存不释放啊 (#489)




 
@Chris-Mraz paddle 升级到 3.0 beta 试试看
