### ISSUE TITLE
cpp_infer中有Linux头文件dirent.h，Windows下无法通过编译

### ISSUE THREAD

**Issue by MistEO** [PaddlePaddle/PaddleOCR#4890]
https://github.com/PaddlePaddle/PaddleOCR/blob/63cd23ab1c3f092666aad627a27dab1588aca83f/deploy/cpp_infer/src/utility.cpp#L15

**Comment by pollyyan** [comment]
请参考该文档进行编译：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/cpp_infer/docs/windows_vs2019_build.md，具体处理见最后的FAQ：
![image](https://user-images.githubusercontent.com/38637686/145942839-79016780-928a-42a4-8da6-526b6eb85eff.png)

**Comment by MistEO** [comment]
> 请参考该文档进行编译：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/cpp_infer/docs/windows_vs2019_build.md 具体处理见最后的FAQ： ![image](https://user-images.githubusercontent.com/38637686/145942839-79016780-928a-42a4-8da6-526b6eb85eff.png)

感谢回复，只有`Utility::GetAllFiles`函数中用到了`dirent.h`中的相关函数，而`Utility::GetAllFiles`在程序中没有任何引用。我直接注掉这个函数和头文件，即通过了编译。

另外如果是没有引用的函数，还整出了这么额外的一条FAQ，可以考虑下是否直接删了这部分
