### ISSUE TITLE
想询问一下在，如果不开检测只开识别的话识别全图是不是不能正确识别

### ISSUE THREAD

**Issue by djkcyl** [PaddlePaddle/PaddleOCR#4892]
还有就是debug信息目前是不是没有办法关掉

![image](https://user-images.githubusercontent.com/59153990/145706969-6f729aa6-446a-48f8-b094-afda344b02a3.png)

**Comment by LDOUBLEV** [comment]
识别模型的输入图像只有文字部分：

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.3/doc/imgs_words/ch/word_1.jpg
