### ISSUE TITLE
共享权重

### ISSUE THREAD

**Issue by two-bee-or-not-two-bee** [PaddlePaddle/PaddleOCR#4895]
请问一下如何共享一个模块的权重？
比如我自定义的了一个 模块 class My_Block(nn.Layer) ，
然后网络中多次调用了这个模块，想要它们的权重共享，请问如何设置啊？

**Comment by andyjpaddle** [comment]
你可以使用`paddle.ParamAttr`并设定一个`name`参数，然后再将这个类的对象传入网络层的`param_attr`参数中，即将所有网络层中`param_attr`参数里的`name`设置为同一个，即可实现共享向量权重。如使用embedding层时，可以设置`param_attr=paddle.ParamAttr(name="word_embedding")`，然后把`param_attr`传入`embedding`层中。

**Comment by two-bee-or-not-two-bee** [comment]
> 你可以使用`paddle.ParamAttr`并设定一个`name`参数，然后再将这个类的对象传入网络层的`param_attr`参数中，即将所有网络层中`param_attr`参数里的`name`设置为同一个，即可实现共享向量权重。如使用embedding层时，可以设置`param_attr=paddle.ParamAttr(name="word_embedding")`，然后把`param_attr`传入`embedding`层中。

感谢您的答复，但是我还是不太理解，就是我想要共享这个模块的权重，但是模块内的各个部分的权重不是共享的，请问也是像您所说的这样设置吗，即将网络中的所有的param_attr用ParamAttr设置name为同一个？

**Comment by andyjpaddle** [comment]
模块内的不同层不共享的话可以使用不同的参数来设置，保证整个模块使用同一套参数就行。比如模块内有`conv1`,`conv2`这两个层不共享的话，设置成不同的name就行。

**Comment by two-bee-or-not-two-bee** [comment]
> 模块内的不同层不共享的话可以使用不同的参数来设置，保证整个模块使用同一套参数就行。比如模块内有`conv1`,`conv2`这两个层不共享的话，设置成不同的name就行。

好的好的，受教了，非常感谢您的解答！！！
