### ISSUE TITLE
DB模型检测问题

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4896]
![image](https://user-images.githubusercontent.com/87969070/145763243-3e0fa570-1b35-4bea-8b1e-2575b3d7d991.png)
![image](https://user-images.githubusercontent.com/87969070/145763285-ab1041dd-f67e-47f2-9ae4-4edff62f6998.png)
请问一下，同样的训练数据条件下，标注多个字符一个检测框与单个字符一个检测框，哪一种的标注方式较好？

**Comment by andyjpaddle** [comment]
使用DB模型的话，第一种标注就可以了
