### ISSUE TITLE
找不到GPU

### ISSUE THREAD

**Issue by liudatutu** [PaddlePaddle/PaddleOCR#490]
环境：
docker版本：Docker version 19.03.12, build 48a66213fe
nvidia-docker为官方最新版本
dock镜像文件为：hub.baidubce.com/paddlepaddle/paddle：latest-gpu-cuda10.1-cudnn7
显卡：P100/2080ti/1080ti

问题：
跑demo的时候只能用CPU，不能使用GPU，报错如下：
root@265664d2942d:/app# CUDA_VISIBLE_DEVICES=0 python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_12.jpg" --det_model_dir="./inference/ch_det_r50_vd_db/"  --rec_model_dir="./inference/ch_rec_r34_vd_crnn_enhance/" --use_space_char=True

................................
----------------------
Error Message Summary:
----------------------
Error: id must less than GPU count
  [Hint: Expected id < GetCUDADeviceCount(), but received id:0 >= GetCUDADeviceCount():0.] at (/paddle/paddle/fluid/platform/gpu_info.cc:240)
这意思就是找不到GPU；
但是我用nvidia-smi可以正常显示我GPU信息
随后我用paddle.fluid查看GPU
gpu=fluid.CUDAPlace(0)
提示错误：
E0806 01:12:37.937582    65 pybind.cc:1223] Cannot use GPU because there is no GPU detected on your machine.

这是赤裸裸的找不到GPU啊

请问这是官方docker镜像无效吗？内安装的cuda和cudnn不可用？？？？
在线求解惑！！！！！！

**Comment by LDOUBLEV** [comment]
你的这个镜像是直接docker pull的吗，要不你换个镜像，cuda10 和cudnn7推荐使用这个 

hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev

**Comment by liudatutu** [comment]
@LDOUBLEV 是直接pull的，试过latest-gpu-cuda10.0-cudnn7-dev，还是一样的报错，感觉是镜像的问题，我用miniconda3自己配的环境就正常了

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV 是直接pull的，试过latest-gpu-cuda10.0-cudnn7-dev，还是一样的报错，感觉是镜像的问题，我用miniconda3自己配的环境就正常了

有点奇怪，我用了这个镜像：hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev 是可以跑GPU代码的。你创建docker的时候用的是nvidia-docker run吗，docker run出来的是CPU的

**Comment by liudatutu** [comment]
@LDOUBLEV 那肯定是用nvidia-docker啊，根据官网安装的nvidia-docker
