### ISSUE TITLE
检测+角度分类+识别误差过大

### ISSUE THREAD

**Issue by WuZifan** [PaddlePaddle/PaddleOCR#4902]
当我对以下图片进行检测时，我发现最终结果错的离谱，而且在很多图片中都出现了类似的问题，请问这是什么原因呢？
所用模型：
   --det_model_dir="./weights/ch_ppocr_server_v2.0_det_infer/"
   --cls_model_dir="./weights/ch_ppocr_mobile_v2.0_cls_infer/"
   --rec_model_dir="./weights/ch_ppocr_server_v2.0_rec_infer/"
检测所用图片：
   
![0002](https://user-images.githubusercontent.com/22706545/145776920-4da496ee-8fc7-478f-9dfc-51d0b1ee7827.jpeg)
检测结果：
![0002](https://user-images.githubusercontent.com/22706545/145776967-ac038f80-9f39-4886-b218-efe9624d9a9e.jpeg)
 
执行所用命令：
python3 tools/infer/predict_system.py --image_dir="./data/0002.jpeg" --det_model_dir="./weights/ch_ppocr_server_v2.0_det_infer/" --cls_model_dir="./weights/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="./weights/ch_ppocr_server_v2.0_rec_infer/" --use_angle_cls=true  --use_gpu=False

**Comment by andyjpaddle** [comment]
看你给的图片，图片中不含任何文字，可能是数据集的问题，先看有文字的图片是否检测正确，如果检测错误率仍然较高，可能和数据集有关，可以考虑在自己的数据集上进行finetune后进行使用。
