### ISSUE TITLE
加载shape参数

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#4904]
![image](https://user-images.githubusercontent.com/87969070/145791215-c57f60cc-1f67-49ec-81bb-30e83664e6e6.png)
检测训练的时候出现shape不匹配的信息，请问该情况需要调整哪些参数呢？

**Comment by andyjpaddle** [comment]
检查一下检测网络和预训练权重的网络的每一层shape是否一致

**Comment by 18362890185** [comment]
> 检查一下检测网络和预训练权重的网络的每一层shape是否一致

请问一下，预训练权重的每一层在哪查看呢？或者是说有必要将两者的网络层保持一致吗？

**Comment by andyjpaddle** [comment]
可以打印预训练模型的网络信息来查看，网络层需要一致，加载才会正常

**Comment by 18362890185** [comment]
> 可以打印预训练模型的网络信息来查看，网络层需要一致，加载才会正常

如何去设置呢？

**Comment by andyjpaddle** [comment]
使用`paddle.load`加载预训练模型，然后`print`

**Comment by 18362890185** [comment]
> 使用`paddle.load`加载预训练模型，然后`print`

好的，谢谢您
