### ISSUE TITLE
模型结构

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleOCR#4906]
请问一下develop版本的怎么在训练时输出模型结构？

**Comment by andyjpaddle** [comment]
可以使用`paddle.save`函数进行保存

**Comment by isLiuHao** [comment]
> 可以使用`paddle.save`函数进行保存

我的意思是打印模型的结构

**Comment by andyjpaddle** [comment]
使用`model_info = paddle.summary(model, (B,C,H,W))`进行打印输出，具体用时要指定`B,C,H,W`这些参数：
```
model_info = paddle.summary(model, (1, 3, 32, 100))
print(model_info)
```

**Comment by isLiuHao** [comment]
> 使用`model_info = paddle.summary(model, (B,C,H,W))`进行打印输出，具体用时要指定`B,C,H,W`这些参数：
> 
> ```
> model_info = paddle.summary(model, (1, 3, 32, 100))
> print(model_info)
> ```

请问在哪里添加呢？

**Comment by andyjpaddle** [comment]
定义好model后就可以加到后面进行打印

**Comment by isLiuHao** [comment]
> 定义好model后就可以加到后面进行打印

[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/train.py](url) 里面没有定义model，只有train_program

**Comment by andyjpaddle** [comment]
develop版本不再提供支持，请使用release版本

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/train.py#L83

**Comment by isLiuHao** [comment]
> develop版本不再提供支持，请使用release版本
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/train.py#L83

静态图可以用2.3版本吗

**Comment by andyjpaddle** [comment]
现在主推动态图，可以先训练好动态图模型，然后动转静导出为静态图使用

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/export_model.py
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/inference.md
