### ISSUE TITLE
串联预测

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#4908]
![image](https://user-images.githubusercontent.com/87969070/145927685-77d2d859-f6f8-4387-bff1-ba9a1ba58aa6.png)
![image](https://user-images.githubusercontent.com/87969070/145927716-2c3542f0-f94a-4a86-96d1-fe3bcfc77c04.png)
请问一下，图一是我单独使用检测的inference模型输出的结果，图二是我将该模型串联输出的结果，为什么差别这么大呢，drop_score我已经降至0.2也还是存在许多未检测到的情况

**Comment by tink2123** [comment]
串联的后处理参数和单独检测的后处理一致吗？另外修改drop_score=0.0 看下检测结果是否一致呢？可能是识别score太低，可视化的时候过滤掉了
