### ISSUE TITLE
使用无数次方法都不能finetune出模型。

### ISSUE THREAD

**Issue by RebornFenix** [PaddlePaddle/PaddleOCR#4909]
1.更改字典训练，发现最后只能识别出字典内容，于是
2.在原字典基础上加了字，训练图片都是新加的字，最后发现仍然只能识别新加字，考虑是原来权重被覆盖了，于是
3.在原字典基础加字，训练图片加上原来的字，训练之后在测试和训练集上OK，在其他图片上根本识别不出来，于是
4.采用原字典，针对一些识别不好的字进行训练，最后发现，可以识别新加的字，原先的权重再次丢了，识别不出来，于是
5.学习率降为0.00001和0.000001，最后依旧识别不出原来的字，于是
6.学习率将为0.00001后，训练一个epoch观看效果，竟然就识别不出来原来的字了，我吐了。
训练图片2w张，测试图片2000张，采用官方推荐开源Text Renderer合成，扰动已开，预训练模型是server_rec
我已经不知道再怎么训练了，除非把字典中其他字也带进去训练，那这样和重训练有啥区别……无非是已经有了权重快一些，但是针对生僻字的结果，依旧未必有那么好。
有没有人训练成功的，分享一下经验。我已经吐了。

**Comment by YY007H** [comment]
没有，我也是基本上收集和合成共几百万张图片重新训练

**Comment by ioracion** [comment]
分享些经验供参考
1.多看FAQ
2.字典里每个字出现的频率至少要在200+，也就是1个字要出现在大于200张图片以上
3.我也是用Text Renderer合成的图片，每张图片里字的数量在2-20之间，合了一共100W开头，保证覆盖全字典
4.学习率默认就可以了
5..其他的建议....得看你啥场景了

**Comment by RebornFenix** [comment]
> 分享些经验供参考 1.多看FAQ 2.字典里每个字出现的频率至少要在200+，也就是1个字要出现在大于200张图片以上 3.我也是用Text Renderer合成的图片，每张图片里字的数量在2-20之间，合了一共100W开头，保证覆盖全字典 4.学习率默认就可以了 5..其他的建议....得看你啥场景了

频率之类的都是按照要求来的，因为我只加了很少的字，加上每一张图片覆盖了6-10个字，所以才2w数据。我的意思是没办法像readme里一样说的finetune，因为只要一训练，哪怕一个epoch，原先的权重也会丢失，您这样的训练也是覆盖全字典重新训练了不是。

**Comment by ioracion** [comment]
对，我改了字典，把很多不常见特殊符号删了，也加了新的字，算重新训练了。它这模型是通用性质的，落地到具体业务场景效果不是特别好。

**Comment by ziyaxuanyi** [comment]
可以固定网络大部分权重，只训练微调head最后一层的权重。不过效果未必好。

理论上来说只用想优化的生僻字数据来训练，肯定最后只能识别你用来训练的那些生僻字，因为你加载预训练权重其实只是相当于找到了一个比较好的网络权重初始化策略而已，最终网络识别能力还是取决于你用来训练的数据。

你所想要的finetune，可以固定网络大部分权重，而只训练大部分最后几层权重来实现，比如就只训练head部分最后一层的全连接层参数。不过估计效果可能达不到你想要的效果。

这个工程，你如果只是学习的目的，数据量几万就足够了。如果你想要真正的做工程落地，就老老实实的加数据量，至少得是千万级的数据量，保证你字典中的每个字符都要覆盖到，才会有比较好的效果。而且要根据你的落地场景，来针对性的加数据，所谓生僻字或者说你想要优化的字符或者新增需要识别的字符，都要保证数据覆盖到，且数量要达到你总数量的一定比例。从算法层面来说，这是训练样本不平衡，可以考虑使用focal loss、在线难例挖掘等其他算法来缓解。

其实吧，深度学习这块，数据才是王道，你算法再牛逼带来的提升，真的不如好的质量优秀的数据带来的提升大。个人经验总结。

**Comment by gutao0315** [comment]
> 分享些经验供参考 1.多看FAQ 2.字典里每个字出现的频率至少要在200+，也就是1个字要出现在大于200张图片以上 3.我也是用Text Renderer合成的图片，每张图片里字的数量在2-20之间，合了一共100W开头，保证覆盖全字典 4.学习率默认就可以了 5..其他的建议....得看你啥场景了

那你合成了100w的数据集，怎么标注呢，ppocrlabel自动标注吗，这么多数据呢

**Comment by gutao0315** [comment]
> 可以固定网络大部分权重，只训练微调head最后一层的权重。不过效果未必好。
> 
> 理论上来说只用想优化的生僻字数据来训练，肯定最后只能识别你用来训练的那些生僻字，因为你加载预训练权重其实只是相当于找到了一个比较好的网络权重初始化策略而已，最终网络识别能力还是取决于你用来训练的数据。
> 
> 你所想要的finetune，可以固定网络大部分权重，而只训练大部分最后几层权重来实现，比如就只训练head部分最后一层的全连接层参数。不过估计效果可能达不到你想要的效果。
> 
> 这个工程，你如果只是学习的目的，数据量几万就足够了。如果你想要真正的做工程落地，就老老实实的加数据量，至少得是千万级的数据量，保证你字典中的每个字符都要覆盖到，才会有比较好的效果。而且要根据你的落地场景，来针对性的加数据，所谓生僻字或者说你想要优化的字符或者新增需要识别的字符，都要保证数据覆盖到，且数量要达到你总数量的一定比例。从算法层面来说，这是训练样本不平衡，可以考虑使用focal loss、在线难例挖掘等其他算法来缓解。
> 
> 其实吧，深度学习这块，数据才是王道，你算法再牛逼带来的提升，真的不如好的质量优秀的数据带来的提升大。个人经验总结。

请问一下，如果很大的数据集一般怎么标注。ppocrlabel自动标注吗，那不也得一个个校对

**Comment by ioracion** [comment]
> > 分享些经验供参考 1.多看FAQ 2.字典里每个字出现的频率至少要在200+，也就是1个字要出现在大于200张图片以上 3.我也是用Text Renderer合成的图片，每张图片里字的数量在2-20之间，合了一共100W开头，保证覆盖全字典 4.学习率默认就可以了 5..其他的建议....得看你啥场景了
> 
> 那你合成了100w的数据集，怎么标注呢，ppocrlabel自动标注吗，这么多数据呢

Text Renderer自动生成标注啊

**Comment by gutao0315** [comment]
> > > 分享些经验供参考 1.多看FAQ 2.字典里每个字出现的频率至少要在200+，也就是1个字要出现在大于200张图片以上 3.我也是用Text Renderer合成的图片，每张图片里字的数量在2-20之间，合了一共100W开头，保证覆盖全字典 4.学习率默认就可以了 5..其他的建议....得看你啥场景了
> > 
> > 
> > 那你合成了100w的数据集，怎么标注呢，ppocrlabel自动标注吗，这么多数据呢
> 
> Text Renderer自动生成标注啊

哥，Text Renderer的使用教程有吗，github上下的每怎么看懂

**Comment by linkewei0580** [comment]
> Text Renderer 能生产det 数据吗？
