### ISSUE TITLE
这个Android demo源代码在哪里？

### ISSUE THREAD

**Issue by guoge6** [PaddlePaddle/PaddleOCR#4910]
![G(L`80@8D)L732F2}N4QC(W](https://user-images.githubusercontent.com/95969602/145930170-c3ff0672-c334-4abe-9838-206cd93c54e5.png)

**Comment by tink2123** [comment]
在这里：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/android_demo

**Comment by guoge6** [comment]
不是这个啊，这个不是二维码那个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 这个Android demo源代码在哪里？ (Issue #4910)





 
在这里：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/android_demo
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by private1215** [comment]
我也在找，楼上发的连接是paddleocr的demo，EasyEdge的可能是以前开源过一段时间，后面不知什么原因不开源了，还有个不用序列号的“OCR EasyEdge Free”开源模型，也找不到了
