### ISSUE TITLE
tensorrt 加速效果不明显

### ISSUE THREAD

**Issue by jiafuzeng** [PaddlePaddle/PaddleOCR#4914]
release2.3
使用模型 ch_det_mv3_db_v2.0.yml
硬件平台：jetson NX
测试tensorrt 开关，发现检测识别速度没有明显改善

**Comment by LDOUBLEV** [comment]
尽量使用高版本的TRT，https://github.com/PaddlePaddle/PaddleOCR/blob/63cd23ab1c3f092666aad627a27dab1588aca83f/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L39

这个参数可以调小一点，

检测模型预计加速20-30%，识别模型加速较少
