### ISSUE TITLE
PGNet Dataset Labels Formatting

### ISSUE THREAD

**Issue by akmalulkhairin** [PaddlePaddle/PaddleOCR#4915]
Hi, I would like to clarify the formatting of the label for PGNet Dataset. The documentation mentions the coordinates required  are as follows

>The points in the dictionary represent the coordinates (x, y) of the four points of the text box, arranged clockwise from the point at the upper left corner.

However, the example provided shows the label "points" as a set of polygon coordinates, as follows

```none
" Image file name             Image annotation information encoded by json.dumps"
rgb/img11.jpg    [{"transcription": "ASRAMA", "points": [[214.0, 325.0], [235.0, 308.0], [259.0, 296.0], [286.0, 291.0], [313.0, 295.0], [338.0, 305.0], [362.0, 320.0], [349.0, 347.0], [330.0, 337.0], [310.0, 329.0], [290.0, 324.0], [269.0, 328.0], [249.0, 336.0], [231.0, 346.0]]}, {...}]
```

Would it be possible to get the train labels currently being used to train PGNet model?

**Comment by LDOUBLEV** [comment]
The label of the OGNet algorithm is 14-point coordinates for curved text.

**Comment by tampe125** [comment]
> The label of the PGNet algorithm is 14-point coordinates for curved text.

Any tips on how create them for custom datasets? Any tool?

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/data_annotation_en.md
