### ISSUE TITLE
使用单个字符就可以正常训练，如{l，a，m，b，d，a} 转为txt既可训练，而是字符串如{lambda}  ，训练就会报索引超出

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleOCR#4916]
要使用这样的character_dict_path: ./rec_data/word_dict.txt  
{'N ', '∴ ', '起 ', 'psi ', '? ', 'otimes ', 'cdotsin ', '↑ ', '个 ', 'y ', '周 ', '加 ', 'cos ', 'circ ', '\\\\\\\\', '5 ', 'leftarrow ', '&textcircled ', '}" ', '米 ', '− ', '( ', '— ', 'theta ', '只 ', '的 ', '3 ', 'I ', '] ', 'é ', 'textcircled ', '、 ', '1 ', 'uparrow ', 'max ', '。 ', '/ ', 'right) ', 'right ', '原 ', '百 ', 'w ', '丙 ', 'B ', '数 ', '4 ', 'overrightarrow ', 'pm ', 'rho ', 'P ', 'underline ', 'p ', 'F ', '即 ', '把 ', '7 ', 'arcsin ', '80 ', '| ', '乘 ', '力 ', '’ ', '页 ', '代 ', 'Delta ', 'b ', 'eta ', '； ', 'c ', '木 ', 'ne ', '棵 ', 'left[ ', '最 ', 'geq ', '< ', 'propto ', 'backsim ', 'à ', '天 ', '和 ', '妈 ', 'geqslant ', '可 ', '{ ', '该 ', '&end{matrix} ', '√ ', 'R ', 'T ', '等 ', 'mu ', 'x ', 'chi ', 'varphi ', 't ', '=1 ', 'S ', 'forall ', 'sigma ', '9 ', '解 ', 'end{matrix} ', '足 ', 'leqslant ', 'right. ', '负 ', 'tau ', 'neq ', 'i ', 'phi ', 'omega ', 'right| ', 'Gamma ', '式 ', 'Omega ', 'ast ', 'cdot ', '项 ', '6s ', 'arctan ', 'q ', 'quad ', 'Y ', 'hat ', 'dot ', 'mid ', 'z ', '根 ', ')" ', 'Q ', '厘 ', 'm ', '} ', '6 ', '是 ', '= ', '书 ', '& ', 'C ', '》 ', "' ", 'sim ', '＿ ', '. ', 'varepsilon ', 'nu ', '_ ', '\\\\', 'lambda ', 'l ', 'Leftrightarrow ', '小 ', 'therefore ', 'div ', '‘ ', '"i ', '相 ', 'bot ', 'g ', 'right} ', '元 ', 'beta ', '为 ', '本 ', '大 ', '以 ', 'min ', 'xlongequal ', '面 ', '☆ ', 'f ', 'r ', 'erasure ', 'log ', '入 ', '# ', 'overline ', '然 ', 'pi ', 'left| ', 'd ', 'ln ', '或 ', 's ', 'in ', '来 ', 'ddot ', 'L ', 'v ', 'odot ', '－ ', '种 ', '行 ', 'A ', 'Rightarrow ', 'begin{matrix} ', '求 ', '% ', 'e ', 'O ', 'sin ', 'tan ', 'M ', '- ', 'k ', 'infty ', 'downarrow ', 'G ', 'perp ', '积 ', '岁 ', 'W ', 'subset ', 'Lambda ', '* ', '答 ', '! ', 'cdots ', 'end{bmatrix} ', 'o ', '有 ', 'because ', 'left. ', 'over ', '; ', 'V ', '次 ', '"f ', '组 ', ') ', 'E ', 'gamma ', 'a ', 'h ', 'Longrightarrow ', 'arccos ', 'cap ', 'frac ', '^ ', 'angle ', '分 ', ' ', 'leq ', 'lg ', '0 ', '2 ', 'supset ', 'cup ', '年 ', 'j ', '能 ', '吗 ', '： ', 'vdots ', '一 ', 'xi ', 'times ', 'U ', 'y{ ', '将 ', '甲 ', 'X ', '方 ', '自 ', '法 ', '所 ', 'epsilon ', 'H ', 'right] ', '第 ', '人 ', 'β ', '&cos ', 'square ', 'partial ', 'approx ', '" ', 'sum ', 'D ', 'varnothing ', 'Z ', 'int ', 'alpha ', 'rightarrow ', '-^ ', '得 ', 'tilde ', '8 ', '满 ', 'zeta ', 'è ', '> ', '因 ', '"h ', 'sqrt ', '乙 ', '“ ', 'bar ', 'xrightarrow ', 'Rightarrow" ', 'prime ', '袋 ', '+ ', ': ', ', ', 'cot ', '[ ', 'left ', '公 ', 'J ', 'begin{bmatrix} ', '□ ', 'rightleftharpoons ', '10s ', 'Phi ', 'widehat ', 'lim ', 'll ', '7t ', 'cong ', 'left{ ', 'triangle ', 'n ', 'K ', 'u ', 'ldots ', 'equiv '} 
 已经转为word_dict.txt  。 
使用的配置文件是rec_en_number_lite_train.yml  ，  

报错：
character :  VEC ================ self.character[int(text_index[batch_idx][idx])] begin{bmatrix} 
idx :  23 ================ batch_idx :  255
text_index[batch_idx][idx] : 314
character :  VEC ================ self.character[int(text_index[batch_idx][idx])] rightleftharpoons 
idx :  27 ================ batch_idx :  255
text_index[batch_idx][idx] : 263
character :  VEC ================ self.character[int(text_index[batch_idx][idx])] X 
idx :  32 ================ batch_idx :  255
text_index[batch_idx][idx] : 139
character :  VEC ================ self.character[int(text_index[batch_idx][idx])] & 
idx :  0 ================ batch_idx :  0
text_index[batch_idx][idx] : 500
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 244, in train
    post_result = post_process_class(preds, batch[1])
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 124, in __call__
    label = self.decode(label)
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 90, in decode
    print("character : ", "VEC" ,"================", "self.character[int(text_index[batch_idx][idx])]",               self.character[int(text_index[batch_idx][idx])])
IndexError: list index out of range

**Comment by tink2123** [comment]
字典地址有没有在配置文件里修改呢？可参考 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/ppocr/utils/en_dict.txt 这个格式构建字典文件

**Comment by Wei-JL** [comment]
> 字典地址有没有在配置文件里修改呢？可参考 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/ppocr/utils/en_dict.txt 这个格式构建字典文件

有这样去转 ，提问题的时候说到转txt文件了 名字是word_list.txt 就是这样去写入的  但是不同的是你这个en_dict.txt 每一行只有一个字符， 而我需要写多个
上诉报错第二行 idx ：27 
character : VEC ================ self.character[int(text_index[batch_idx][idx])] **rightleftharpoons**
idx : 27 ================ batch_idx : 255
 比如 rightleftharpoons是一行

最后索引超出的错误，请问怎么让它支持一行多个字符呢

**Comment by Wei-JL** [comment]
请问可以解决吗？？

**Comment by Wei-JL** [comment]
莫西莫西  问题还没解决呢
