### ISSUE TITLE
How can I export the result like in the Visualization section?

### ISSUE THREAD

**Issue by vihnng** [PaddlePaddle/PaddleOCR#4920]
Hi, how can I export the result like in the Visualization section or maybe export the result to a .txt file?
I'm currently using Windows

**Comment by Evezerest** [comment]
you can try the whl package in python script according to [this doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/whl_en.md)

**Comment by vihnng** [comment]
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x is the version of paddleocr
When I ran the above command (I installed 2.0.1 and replaced the x.x.x with 2.0.1), it returned " Could not install packages due to an OSError: [Errno 2] No such file or directory" but I'm sure that i'm in the correct folder because I could run the command "python3 setup.py bdist_wheel".
How can I fix this problem? Thank you
