### ISSUE TITLE
文本检测，结果中有很小的框，过滤不掉

### ISSUE THREAD

**Issue by Atiuiee** [PaddlePaddle/PaddleOCR#4922]
测试结果
![det_res_design_933](https://user-images.githubusercontent.com/31364852/146118645-e92762f8-35fe-4c6f-ad9a-d891a0535239.png)
预训练模型为ch_ppocr_server_v2.0_det_train，在此上加了部分自己的数据集。
修改了后处理参数det_db_thresh和det_db_box_thresh，都不能完美过滤
求大佬帮助呀，搞不懂什么原因

**Comment by WenmuZhou** [comment]
可以根据面积看看

**Comment by Atiuiee** [comment]
> 可以根据面积看看

**Comment by chenshanhuo** [comment]
我也是这个问题,大佬有解决吗
