### ISSUE TITLE
请问文本检测的模型训练不收敛该怎么办

### ISSUE THREAD

**Issue by icesword95** [PaddlePaddle/PaddleOCR#4924]
数据量不算多，目前是标了700张，500张训练200张验证。训练1500个epoch最优的在282，hmean只有0.40或者更低，划出来的框连跟训练集都对不上，过拟合也没能达到。用的是dbnet+mv3，尝试换过resnet，甚至效果会更差。以前图片更少时反而效果会更好，会是标注的方式有问题吗，或者有没有什么参数可以调整（用的都是默认的）。又看了一下loss是有稳步下降的，那就是收敛有在收敛，但效果不好？哪怕先达到过拟合效果也可以，该如何调整，目前再增加数据量也比较困难了？

**Comment by WenmuZhou** [comment]
训练的时候用ppocr的模型做预训练看看

**Comment by icesword95** [comment]
> 训练的时候用ppocr的模型做预训练看看

已经用了，用的就是原本的代码，原本的代码里就有预训练

**Comment by s957995299** [comment]
我也不收敛+1
