### ISSUE TITLE
Data Augmentation in PGNet training

### ISSUE THREAD

**Issue by windspirit95** [PaddlePaddle/PaddleOCR#4926]
Hi,

About PGNet step 2 training, could I apply data augmentation on it (such as IaaAugment), and how could I update to the config file: e2e_r50_vd_pg.yml?
Currently my training data is annotated with 14-point format as totaltext dataset.

Thank you :)

**Comment by tampe125** [comment]
Hello, it’s unrelated to your issue, but you would mind sharing a sample of your dataset?
I’m struggling creating a valid one

**Comment by windspirit95** [comment]
> Hello, it’s unrelated to your issue, but you would mind sharing a sample of your dataset? I’m struggling creating a valid one

I have use some package to generate the Synthetic data, and recalculate the 14-point coordinate after applying the transformation function.
Current package here they not support key points calculating after using distortion function like sin or cosin (as I update by myself :)), but you could reference from it: https://github.com/Belval/TextRecognitionDataGenerator
My technique is simply initialize 14-point coords in rectangular case, then based on the transformation to add the offset value to every points
imgaug library also one tool could help you doing some geometric transformation, and it support key points recalculating.
Sample data I could send some, so you could leave your email here :)
