### ISSUE TITLE
ERROR：cpu线上部署，部分复杂场景，内存会出错

### ISSUE THREAD

**Issue by Yepman0620** [PaddlePaddle/PaddleOCR#493]
[Hint: Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.] at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:59)
  [operator < softmax > error]

**Comment by Yepman0620** [comment]
各位懂的同学，请问这个问题是怎么造成的呢？我该如何fix?

**Comment by littletomatodonkey** [comment]
posix_memalign返回12表示OOM了，可以看下是否是因为内存申请太多或者内存泄露的情况，目前使用的话 请确保关闭mkldnn。

**Comment by Yepman0620** [comment]
> posix_memalign返回12表示OOM了，可以看下是否是因为内存申请太多或者内存泄露的情况，目前使用的话 请确保关闭mkldnn。

项目这么久内存泄漏bug概率比较低了，等我解决再看看.。结合我这个场景，我猜可能是因为内存申请太多了。所以，应该对dtc_boxs分批处理？

**Comment by Yepman0620** [comment]
> [Hint: Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.] at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:59)
> [operator < softmax > error]

已解决  . /tools/infer/utility.py     参数 --rec_batch_num, type=int, default=30     这里改 default=? 符合你硬件情况的即可。
