### ISSUE TITLE
训练模型报错 python3.7

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#4935]
训练命令：python tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained
报错信息
![image](https://user-images.githubusercontent.com/4344069/146198493-9cf49385-6205-44f9-9125-6760a4cdc66c.png)

这个信息是缺少了什么配置吗？
![image](https://user-images.githubusercontent.com/4344069/146198680-5a7c49f4-bae0-4ec6-abe0-1647f48797c2.png)

**Comment by LiquorPerfect** [comment]
这边不是已经打印出报错信息了嘛
![image](https://user-images.githubusercontent.com/36955510/146291282-6497dd67-655e-4762-92b8-8777460bfb29.png)

**Comment by LiquorPerfect** [comment]
![image](https://user-images.githubusercontent.com/36955510/146291423-8e76aaad-c51b-4214-b348-e30af5539d2c.png)
这边不是已经有打印信息了嘛

**Comment by wincentytg** [comment]
![image](https://user-images.githubusercontent.com/4344069/146294471-a9716710-b0b5-4707-8d06-e20409c17cb1.png)
这个呢？

**Comment by wincentytg** [comment]
是pyclipper版本不对吗？
