### ISSUE TITLE
自定义识别dict在train时候报错，提示IndexError: list index out of range

### ISSUE THREAD

**Issue by GanWang** [PaddlePaddle/PaddleOCR#4938]
查看了一下字典84个字符，软件中dict自己添加了‘空格’，共85个 字符，  即0-84，但是在label的decode时候出现了85导致问题，这是啥情况？？用的预训练模型是en_number_mobile_v2.0_rec_slim_train，dict的路径也是改了的。
char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range

**Comment by littletomatodonkey** [comment]
配置里把use_space_char修改为False

**Comment by GanWang** [comment]
已经修改False，还是有问题。不过已经解决了，dict的编码有问题，0的编码异常导致无法识取




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 上午10:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938)





 
配置里把use_space_char修改为False
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by upcdz** [comment]
> 已经修改False，还是有问题。不过已经解决了，dict的编码有问题，0的编码异常导致无法识取
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月17日(星期五) 上午10:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938) 配置里把use_space_char修改为False — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我也出现这种问题，字典的编码是utf-8，请问如何解决啊？

**Comment by GanWang** [comment]
建议单步调试，看一下读入的dict中有没有解码异常的不是你选用的label的字符，确定问题点。utf-8我是改用uft-8-sig了，不同问题措施可能不一样。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 下午2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938)





  
已经修改False，还是有问题。不过已经解决了，dict的编码有问题，0的编码异常导致无法识取
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月17日(星期五) 上午10:02 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938) 配置里把use_space_char修改为False — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，我也出现这种问题，字典的编码是utf-8，请问如何解决啊？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by upcdz** [comment]
> 

utf-8改用uft-8-sig不好使，我字典里是孟加拉文，然后字典里字符的个数是63， 但是我打印出
int(text_index[batch_idx][idx]):78

字典里只有63个字符，为啥网络会预测出第78个呢，有点纳闷。

**Comment by GanWang** [comment]
调试的时候看一下，读到字典的字符都是哪些，和你设定的有哪些差异，这个问题应该好定位的对比一下就知道了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月27日(星期四) 上午9:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938)





   
utf-8改用uft-8-sig不好使，我字典里是孟加拉文，然后字典里字符的个数是63， 但是我打印出
 int(text_index[batch_idx][idx]):78
 
字典里只有63个字符，为啥网络会预测出第78个呢，有点纳闷。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by upcdz** [comment]
> 调试的时候看一下，读到字典的字符都是哪些，和你设定的有哪些差异，这个问题应该好定位的对比一下就知道了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月27日(星期四) 上午9:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 自定义识别dict在train时候报错，提示IndexError: list index out of range (Issue #4938) utf-8改用uft-8-sig不好使，我字典里是孟加拉文，然后字典里字符的个数是63， 但是我打印出 int(text_index[batch_idx][idx]):78 字典里只有63个字符，为啥网络会预测出第78个呢，有点纳闷。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![image](https://user-images.githubusercontent.com/45310743/151273736-362ff71e-e97a-4734-881d-1ffa4f3b541d.png)
