### ISSUE TITLE
使用Rosetta识别算法，在验证的时候随机卡主不动，求解

### ISSUE THREAD

**Issue by HouYanGG** [PaddlePaddle/PaddleOCR#4939]
使用Rosetta识别算法，在训练阶段的eval时候随机卡主不动，麻烦大家看一下
![WZHVIGJA{%4VGJRD`XZQ7LS](https://user-images.githubusercontent.com/49891512/146296853-7e175378-0861-4781-8801-6530cee1c12c.jpg)

**Comment by HouYanGG** [comment]
使用2080ti  4线程，bachsize=32，Ubuntu18.4环境，paddleocr 2.2版本，crnn识别算法正常，Rosetta的mobilev3正常，Rosetta的resnet34随机卡主

**Comment by littletomatodonkey** [comment]
大模型对内存显存要求更高，可以把配置文件里的num worker修改为0看下
