### ISSUE TITLE
有一些图片资源，识别不太好，怎么发给你？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#494]

**Comment by tink2123** [comment]
可以把图片打包，发送到邮箱 y_tink@163.com

**Comment by xinsuinizhuan** [comment]
已发送，请查收！

**Comment by tink2123** [comment]
收到～请问您需要识别的图片都是电表相关的吗？

**Comment by xinsuinizhuan** [comment]
> 
> 
> 收到～请问您需要识别的图片都是电表相关的吗？

是的。一些工业用表读数。希望可以优化。

**Comment by tink2123** [comment]
我们这边自测了一下效果，发现以下几个问题，请检查是否有遗漏：
1. 带反斜杠的日期识别效果不好，其余部分识别效果较为准确：
![图片](https://user-images.githubusercontent.com/31891223/89499268-4e10c200-d7f2-11ea-8a4f-7005c90f3de1.png)
这是已知的badcase，我们正在优化中。
2. 数码管图片识别效果较差：
由于我们的训练样本中缺少此类图片，因此模型较难识别。如果您有需求，**能否帮助我们提供一批类似的训练数据呢？**我们将加入训练在下个版本迭代中支持数码管识别
3. 图片旋转角度过大时，识别效果不佳：
![图片](https://user-images.githubusercontent.com/31891223/89499962-764cf080-d7f3-11ea-8ab4-15ddfb9ac4a4.png)
此类图片因为方向不定问题，识别难度较大，请问您的场景中这类图片占比大吗？占比不大的话建议手动转正，另外我们会考虑在下个版本中加入方向分类器，对旋转图片做一定的矫正。

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我们这边自测了一下效果，发现以下几个问题，请检查是否有遗漏：
> 
>     1. 带反斜杠的日期识别效果不好，其余部分识别效果较为准确：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499268-4e10c200-d7f2-11ea-8a4f-7005c90f3de1.png)
>        这是已知的badcase，我们正在优化中。
> 
>     2. 数码管图片识别效果较差：
>        由于我们的训练样本中缺少此类图片，因此模型较难识别。如果您有需求，**_能否帮助我们提供一批类似的训练数据呢？_** 我们将加入训练在下个版本迭代中支持数码管识别
> 
>     3. 图片旋转角度过大时，识别效果不佳：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499962-764cf080-d7f3-11ea-8ab4-15ddfb9ac4a4.png)
>        此类图片因为方向不定问题，识别难度较大，请问您的场景中这类图片占比大吗？占比不大的话建议手动转正，另外我们会考虑在下个版本中加入方向分类器，对旋转图片做一定的矫正。

对的，带斜杠的日期，以及数字后面的符号，A V KW，很多情况下把KW识别成KM和乱识别成其他：
![图片](https://user-images.githubusercontent.com/40679769/89500354-30445c80-d7f4-11ea-939b-c50387b1ffb9.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我们这边自测了一下效果，发现以下几个问题，请检查是否有遗漏：
> 
>     1. 带反斜杠的日期识别效果不好，其余部分识别效果较为准确：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499268-4e10c200-d7f2-11ea-8a4f-7005c90f3de1.png)
>        这是已知的badcase，我们正在优化中。
> 
>     2. 数码管图片识别效果较差：
>        由于我们的训练样本中缺少此类图片，因此模型较难识别。如果您有需求，**_能否帮助我们提供一批类似的训练数据呢？_** 我们将加入训练在下个版本迭代中支持数码管识别
> 
>     3. 图片旋转角度过大时，识别效果不佳：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499962-764cf080-d7f3-11ea-8ab4-15ddfb9ac4a4.png)
>        此类图片因为方向不定问题，识别难度较大，请问您的场景中这类图片占比大吗？占比不大的话建议手动转正，另外我们会考虑在下个版本中加入方向分类器，对旋转图片做一定的矫正。

![图片](https://user-images.githubusercontent.com/40679769/89501094-5d453f00-d7f5-11ea-98d2-09f51bca858c.png)
![图片](https://user-images.githubusercontent.com/40679769/89501203-806fee80-d7f5-11ea-8e06-0d63ab1cbb2c.png)
![图片](https://user-images.githubusercontent.com/40679769/89501304-b2815080-d7f5-11ea-8310-c534d3009e25.png)
![图片](https://user-images.githubusercontent.com/40679769/89501329-bd3be580-d7f5-11ea-835c-2f87ed859bf1.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我们这边自测了一下效果，发现以下几个问题，请检查是否有遗漏：
> 
>     1. 带反斜杠的日期识别效果不好，其余部分识别效果较为准确：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499268-4e10c200-d7f2-11ea-8a4f-7005c90f3de1.png)
>        这是已知的badcase，我们正在优化中。
> 
>     2. 数码管图片识别效果较差：
>        由于我们的训练样本中缺少此类图片，因此模型较难识别。如果您有需求，**_能否帮助我们提供一批类似的训练数据呢？_** 我们将加入训练在下个版本迭代中支持数码管识别
> 
>     3. 图片旋转角度过大时，识别效果不佳：
>        ![图片](https://user-images.githubusercontent.com/31891223/89499962-764cf080-d7f3-11ea-8ab4-15ddfb9ac4a4.png)
>        此类图片因为方向不定问题，识别难度较大，请问您的场景中这类图片占比大吗？占比不大的话建议手动转正，另外我们会考虑在下个版本中加入方向分类器，对旋转图片做一定的矫正。

您这边使用的是哪个检测模型和识别模型呢？我是使用C++加载的模型，刚开始使用的是db_crnn_mobile的检测模型和db_crnn_server的识别模型，这个组合相对好一些。但是，后面发现检测模型不太好，然后我就使用的是https://github.com/ouyanghuiyu/chineseocr_lite的检测模型+我们的识别模型，相对效果好很多。但是带横岗的日期，以及符号A V KW等识别还是不好，经常识别成0，点和汉字

**Comment by tink2123** [comment]
![图片](https://user-images.githubusercontent.com/31891223/89513633-650ddf00-d807-11ea-87f5-267c19af9258.png)
这张图的检测框应该有问题，如果你用的是C++版本的模型需要更换一下检测的inference_model
链接:https://pan.baidu.com/s/124DAsif1TWZp9Z-dpnyF1A  密码:3ih1

> 以及符号A V KW等识别还是不好，经常识别成0，点和汉字

这个需要有针对性的再训练优化一下，我们发布的模型是基于通用场景的，没有办法覆盖所有垂类场景。您这边愿意提供一些数据吗？我们可以基于您的数据对模型进行优化

**Comment by xinsuinizhuan** [comment]
您好，又给您的邮箱发了一些数据，这是我现在这边所能收集到的数据了。我刚下载了您提供的百度网盘的连接文件，好像不对，下载下来，解压后，不是param和model文件，是一个文件：
![图片](https://user-images.githubusercontent.com/40679769/89517231-026b1200-d80c-11ea-9b5b-a89b136e50f8.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/31891223/89513633-650ddf00-d807-11ea-87f5-267c19af9258.png)
> 这张图的检测框应该有问题，如果你用的是C++版本的模型需要更换一下检测的inference_model
> 链接:https://pan.baidu.com/s/124DAsif1TWZp9Z-dpnyF1A 密码:3ih1
> 
> > 以及符号A V KW等识别还是不好，经常识别成0，点和汉字
> 
> 这个需要有针对性的再训练优化一下，我们发布的模型是基于通用场景的，没有办法覆盖所有垂类场景。您这边愿意提供一些数据吗？我们可以基于您的数据对模型进行优化
C++版本的模型需要更换一下检测的inference_model
链接:https://pan.baidu.com/s/124DAsif1TWZp9Z-dpnyF1A 密码:3ih1，C++加载模型是2个模型，一个params和model，但是这个下载下来后，解压后是一个det_mv3_inferenc文件，怎么使用呢？

**Comment by tink2123** [comment]
可以参考这里的文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/readme.md#2-%E5%BC%80%E5%A7%8B%E8%BF%90%E8%A1%8C

压缩包里是检测的inference model，把它替换您原有的模型即可

**Comment by xinsuinizhuan** [comment]
原来我下载的检测模型tar包解压以后是params和model两个文件，这个解压后只有一个，这是一个是对应model文件吗？params使用原来的？

在 2020-08-06 19:47:06，xiaoting <notifications@github.com> 写道：


可以参考这里的文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/readme.md#2-%E5%BC%80%E5%A7%8B%E8%BF%90%E8%A1%8C

压缩包里是检测的inference model，把它替换您原有的模型即可

**Comment by tink2123** [comment]
解压的好像不太对，我重新打个包给你～ 再试一次呢？ 里面应该是有 model 和 params
链接:https://pan.baidu.com/s/1K9dIDRtvCGDKJtr2-k1uPA  密码:dvca

**Comment by xinsuinizhuan** [comment]
> 
> 
> 解压的好像不太对，我重新打个包给你～ 再试一次呢？ 里面应该是有 model 和 params
> 链接:https://pan.baidu.com/s/1K9dIDRtvCGDKJtr2-k1uPA 密码:dvca

我可以说，检测效果还是不好吗？
![图片](https://user-images.githubusercontent.com/40679769/89595948-94b0fb80-d888-11ea-84d2-d93b3e3a79a6.png)
![图片](https://user-images.githubusercontent.com/40679769/89595973-a85c6200-d888-11ea-9078-197263585130.png)

**Comment by tink2123** [comment]
问题已解决，C++调用模型，检测错乱问题，是因为开启e_mkldnn引起，关闭后效果正常。感谢反馈～
