### ISSUE TITLE
Android studio导入Android_demo文件后，.cxx包是什么东西

### ISSUE THREAD

**Issue by guoge6** [PaddlePaddle/PaddleOCR#4944]
![image](https://user-images.githubusercontent.com/95969602/146310627-209e2252-0336-4527-935b-355a468e1d5d.png)

**Comment by littletomatodonkey** [comment]
查了下，这好像是android studio自动生成的cmake编译优化内容，可能和你的android studio配置有关

**Comment by guoge6** [comment]
嗯嗯,谢谢！可是为什么我自己创建一个native C++ project,它的.cxx是这样的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] Android studio导入Android_demo文件后，.cxx包是什么东西 (Issue #4944)





 
查了下，这好像是android studio自动生成的cmake编译优化内容，可能和你的android studio配置有关
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guoge6** [comment]
![image](https://user-images.githubusercontent.com/95969602/146482560-484c639a-7c21-4585-a3cb-fb8c9ca9aac4.png)
