### ISSUE TITLE
出现module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'的问题

### ISSUE THREAD

**Issue by lai-serena** [PaddlePaddle/PaddleOCR#4946]
系统：centos 7.9.2009
GTX1060 6GB显卡 CUDA10.0
环境：python=3.7.11
           paddlepaddle-gpu=2.0.2.post100 
           paddleocr=2.3.0.2 

运行如下代码：
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(lang="ch")
img_path ='ppocr_img/imgs_my/images_1.png'
result = ocr.ocr(img_path)
for line in result:
    print(line)
from PIL import Image
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/chinese_cht.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

出现错误：
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    ocr = PaddleOCR(lang="ch") # The model file will be downloaded automatically when executed for the first time
  File "/work/PaddleOCR-release-2.3/paddleocr.py", line 307, in __init__
    super().__init__(params)
  File "/work/PaddleOCR-release-2.3/tools/infer/predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/work/PaddleOCR-release-2.3/tools/infer/predict_det.py", line 99, in __init__
    args, 'det', logger)
  File "/work/PaddleOCR-release-2.3/tools/infer/utility.py", line 163, in create_predictor
    gpu_id = get_infer_gpuid()
  File "/work/PaddleOCR-release-2.3/tools/infer/utility.py", line 290, in get_infer_gpuid
    if not paddle.fluid.core.is_compiled_with_rocm():
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'
请问这个错误怎么解决吗？

**Comment by littletomatodonkey** [comment]
paddle升级到2.2看下呢？

**Comment by SongJ123** [comment]
查了一下paddle.fluid将来版本会废弃，自从paddlepaddle 2.1之后is_compiled_with_rocm就在paddle.device下面了，我先改成了device还是报错说明引擎是2.0的。并且is_compiled_with_rocm是paddlepaddle为了适配amd和海光的gpu的，跟nvidia的显卡关系不大。把相关的两个if not 注释掉就可以了
