### ISSUE TITLE
训练模型报错 python3.9.6

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#4948]
训练模型报报 ModuleNotFoundError: No module named 'paddle.distributed' 这个怎么安装？
![image](https://user-images.githubusercontent.com/4344069/146365375-969ddf4f-fdec-4a6f-b78b-a93f6af4ef34.png)

**Comment by littletomatodonkey** [comment]
你好，安装2.2.0试下呢？我这边shi'yo使用py39没遇到这个问题

![image](https://user-images.githubusercontent.com/14270174/146478575-c2c9c5c9-fde7-439f-8c52-27ec001076aa.png)
