### ISSUE TITLE
现在支持的中文识别和检测的模型都是哪些啊

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#495]
最近想尝试训练中文识别模型，想知道中文识别模型，目前开源的四种都支持吗？
CRNN Rosetta STAR-Net RARE都支持中文吗

**Comment by tink2123** [comment]
库中提供的训练好的中文模型，是CRNN，如果直接预测的话，只有超轻量和通用两个模型。
如果您希望自己训练，那所有模型都是支持的，参考文档修改配置文件即可。但是不建议使用 RARE 进行中文训练。
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/recognition.md
<img width="1017" alt="图片" src="https://user-images.githubusercontent.com/31891223/89606139-db5f1f80-d8a1-11ea-8370-7f508f168cd2.png">
