### ISSUE TITLE
微调时det模型时修改尺寸，loss很高

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/PaddleOCR#4951]
如题，det预训练的输入图像尺寸为960，在应用场景中不够，所以需要训练一个输入大尺寸图像的det模型。利用现有的det预训练模型作微调，loss很高而且不太收敛，请问有大尺寸输入图像的det预训练模型吗？或者有什么好办法让微调收敛吗？

**Comment by MissPenguin** [comment]
960应该也是可以收敛的，你的数据量是多少，都做了哪些改动呢，有加载ppocr模型pretrain吗

**Comment by guijuzhejiang** [comment]
我自己的数据量不多，2万多些，除了训练config中的input size改成1280外，其他没有改动，考虑input size改变所以没有加载ppocr的预训练模型。所以想问问有没有开源输入尺寸是1280或者更大输入尺寸的预训练模型
