### ISSUE TITLE
train.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#4954]
![image](https://user-images.githubusercontent.com/4344069/146484824-acc4c65e-32b8-4872-9db2-0eec0af6b84c.png)
这是缺少什么参数？

**Comment by MissPenguin** [comment]
可以具体描述下报错的过程吗：代码版本，做了哪些改动，运行命令

**Comment by wincentytg** [comment]
![image](https://user-images.githubusercontent.com/4344069/146715973-d23281d8-d75c-4446-817d-a4f25abcef7d.png)
执行的这个命令 是 命令里这个 \ 的问题吗？ 在这里 \的意思是或者的意思？

**Comment by wincentytg** [comment]
![image](https://user-images.githubusercontent.com/4344069/146716952-eb69e831-ec89-49d0-90c7-f1488269decd.png)
这里说的训练的数据 哪里可以下载到？或者自己造数据的话 这个标签文档里的内容和图片的命名的规则是什么样的？有文档说明吗？

**Comment by pollyyan** [comment]
> ![image](https://user-images.githubusercontent.com/4344069/146715973-d23281d8-d75c-4446-817d-a4f25abcef7d.png) 执行的这个命令 是 命令里这个 \ 的问题吗？ 在这里 \的意思是或者的意思？

\是换行符哈～整行执行指令不用加这个哈～


> ![image](https://user-images.githubusercontent.com/4344069/146716952-eb69e831-ec89-49d0-90c7-f1488269decd.png) 这里说的训练的数据 哪里可以下载到？或者自己造数据的话 这个标签文档里的内容和图片的命名的规则是什么样的？有文档说明吗？

这个是数据集，在文档前面有说明哈
![image](https://user-images.githubusercontent.com/38637686/146867386-ec3743d8-03bf-4c70-b093-d19a1686dcd2.png)

**Comment by wincentytg** [comment]
这里的数据预处理跟用 ppocrLable 这个工具处理是一回事吗？区别是啥？

**Comment by MissPenguin** [comment]
> 这里的数据预处理跟用 ppocrLable 这个工具处理是一回事吗？区别是啥？

上面的预处理是把已有数据的标注格式转换为训练要求的格式，PPOCRLabel是数据标注工具
