### ISSUE TITLE
M1 CPU support

### ISSUE THREAD

**Issue by temco** [PaddlePaddle/PaddleOCR#4955]
我在M1 CPU的macbook air下安装ppocr无法成功(Python 3.9.7)，主要问题就是collecting opencv-contrib-python时No matching distribution found for numpy==1.19.3，collecting ppocr时Failed building wheel for lmdb。我手动装其他版本的numpy是没有问题的。不知道是不是M1 CPU的问题？

**Comment by MissPenguin** [comment]
换个3.7版本的Python试试呢
