### ISSUE TITLE
基于python推理引擎和PaddleServing部署的服务侧识别的结果不一致

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#4956]
文本检测模型：ch_ppocr_server_v2.0_det_infer
文本识别模型：ch_ppocr_server_v2.0_rec_infer
都是通过以下命令获取：
`wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar && tar xf ch_ppocr_server_v2.0_det_infer.tar`

两种预测方式：
1. python推理引擎：
`python3 tools/infer/predict_system.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_ppocr_server_v2.0_det_infer/" --rec_model_dir="./ch_ppocr_server_v2.0_rec_infer/" --use_angle_cls=false`

2.通过PaddleServing[部署](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/deploy/pdserving/README_CN.md)

同一个模型文件，预测识别得到的结果为什么会不一样呢

**Comment by MissPenguin** [comment]
预处理和后处理可能未能完全对齐，结果稍有些diff是正常的

**Comment by tink2123** [comment]
检测模型： [预处理](https://github.com/PaddlePaddle/PaddleOCR/blob/5adfc98c7a45b3e45c9a7089b395aec4ff427f6c/deploy/pdserving/web_service.py#L45) [后处理](https://github.com/PaddlePaddle/PaddleOCR/blob/5adfc98c7a45b3e45c9a7089b395aec4ff427f6c/deploy/pdserving/web_service.py#L57)

识别模型：[预处理](https://github.com/PaddlePaddle/PaddleOCR/blob/5adfc98c7a45b3e45c9a7089b395aec4ff427f6c/deploy/pdserving/web_service.py#L77) [后处理](https://github.com/PaddlePaddle/PaddleOCR/blob/5adfc98c7a45b3e45c9a7089b395aec4ff427f6c/deploy/pdserving/web_service.py#L132)

主要问题可能是在检测后处理部分，检查下这些参数和inference预测时的参数是否一致：
```
        self.post_func = DBPostProcess({
            "thresh": 0.3,
            "box_thresh": 0.5,
            "max_candidates": 1000,
            "unclip_ratio": 1.5,
            "min_size": 3
        })
```
