### ISSUE TITLE
静态图gather怎么取某个维度的某一个值。

### ISSUE THREAD

**Issue by ChChwang** [PaddlePaddle/PaddleOCR#4958]
a = b[:,ind,:] 不行，因为ind 是tensor 值

**Comment by MissPenguin** [comment]
那先把ind转一下数据类型呢

**Comment by ChChwang** [comment]
> 那先把ind转一下数据类型呢

和数据类型没关系吧

**Comment by littletomatodonkey** [comment]
静态图用`fluid.layers.gather`应该就可以，动态图可以用`paddle.take_along_axis`，可以参考[链接](https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/article-implementation/ArticleReproduction_CV.md#451-paddlegather%E5%92%8Ctorchgather%E7%9A%84%E5%90%AB%E4%B9%89%E4%B8%8D%E5%90%8C%E6%9C%89%E4%BB%80%E4%B9%88%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95%E5%91%A2)
