### ISSUE TITLE
您好，基于python预测和服务器端C++预测结果相差很大，请问是否有解决的办法

### ISSUE THREAD

**Issue by 358788887** [PaddlePaddle/PaddleOCR#4959]
两种测试都使用相同模型
python预测命令（PaddleOCR根目录）
python3 tools/infer/predict_system.py 
--det_model_dir="./deploy/cpp_infer/arabic/det_db/" 
--rec_model_dir="./deploy/cpp_infer/arabic/arabic_ppocr_mobile_v2.0_rec_infer" 
--image_dir="./doc/imgs_arabic/i3.png" 
--use_angle_cls=false 
--rec_char_type="arabic" 
--rec_char_dict_path="./ppocr/utils/dict/arabic_dict.txt" 
--vis_font_path="./doc/fonts/arabic2.ttf"

C++预测命令（PaddleOCR/deploy/cpp_infer目录）
./build/ppocr system 
--det_model_dir=arabic/det_db 
--rec_model_dir=arabic/arabic_ppocr_mobile_v2.0_rec_infer 
--image_dir=../../doc/imgs_arabic/i3.png 
--char_list_file=../../ppocr/utils/dict/arabic_dict.txt

以下图片为测试结果

<img width="1068" alt="测试结果截图" src="https://user-images.githubusercontent.com/94504819/146545125-fb22d7a3-501b-4926-baf3-eb69d803277a.png">

**Comment by tink2123** [comment]
请问cpp代码使用的是哪个分支呢？ 识别模型的训练shape是多少？
可以固定预处理的resize的shape试一下。
注释掉这行代码：https://github.com/PaddlePaddle/PaddleOCR/blob/63cd23ab1c3f092666aad627a27dab1588aca83f/deploy/cpp_infer/src/preprocess_op.cpp#L94

同时把 input shape 修改成和训练一致的。

**Comment by 358788887** [comment]
> 请问cpp代码使用的是哪个分支呢？ 识别模型的训练shape是多少？ 可以固定预处理的resize的shape试一下。 注释掉这行代码：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/63cd23ab1c3f092666aad627a27dab1588aca83f/deploy/cpp_infer/src/preprocess_op.cpp#L94
> 
> 同时把 input shape 修改成和训练一致的。

您好，配置上都没有问题，根据官方小伙伴得出的结论，可能存在的问题deploy/lite/ocr_db_crnn.cc导致。现在新版2.4我在

**Comment by HosseinBakand** [comment]
Same Issue

**Comment by steinvenic** [comment]
唉，各种问题，也没人管

**Comment by yangtianyu92** [comment]
auto log这文件就没有，毒了。

**Comment by MissPenguin** [comment]
> 据官方小伙伴得出的结论，可能存在的问题deploy/lite/ocr_db_crnn.cc导致。
> 现在新版2.4我再做同样测试，PaddleOCR2.4/deploy/lite教程，执行编译可执行文件ocr_db_crnn时，
> 第一个错误，./cls_process.h:25:10: fatal error: 'opencv2/core.hpp' file not found，下载opencv4.10已解决
> 第二个错误：ocr_db_crnn.cc:22:10: fatal error: 'AutoLog/auto_log/lite_autolog.h' file not found ，下载https://github.com/LDOUBLEV/AutoLog 后

请问问题解决了吗，看您题目里是c++预测，下面又是lite，可以再明确一下具体问题吗

**Comment by yudaprama** [comment]
Same issue when compiling model to lite

You can replicate by following `deploy/lite/readme.md`
