### ISSUE TITLE
识别多行文本时，输出结果乱序输出

### ISSUE THREAD

**Issue by wangguanhua** [PaddlePaddle/PaddleOCR#496]
输出的结果不是按照顺序来的。如图所示
![image](https://user-images.githubusercontent.com/25172472/89524791-c178fa80-d817-11ea-99e4-279be334456a.png)

**Comment by liudatutu** [comment]
这个检测结果好像是按照检测文本框的坐标来排序的，先纵向排序后横向。

**Comment by wangguanhua** [comment]
但左上第一个文本框按道理应该第一个输出，实际上却是第三个输出，从坐标角度来说讲不通吧



---原始邮件---
发件人: "大土土君"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 上午9:50
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wangguanhua"<767477036@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 识别多行文本时，输出结果乱序输出 (#496)




 
这个检测结果好像是按照检测文本框的坐标来排序的，先纵向排序后横向。

**Comment by liudatutu** [comment]
我也特意看了下，排序是先纵向排序后横向，也就是说第三个文本框的纵坐标最小，所以第一个输出，你可有检查一下

**Comment by wangguanhua** [comment]
如果这样搞的话，用这个模型根本就没办法应用在类似于表格这样的场景中，输出顺序都不确定。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 中午11:13
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别多行文本时，输出结果乱序输出 (#496)





 
我也特意看了下，排序是先纵向排序后横向，也就是说第三个文本框的纵坐标最小，所以第一个输出，你可有检查一下

**Comment by liudatutu** [comment]
@wangguanhua 可以自己做一下后处理就好

**Comment by wangguanhua** [comment]
您好，麻烦问一下您可否提供一下后处理的思路，我本来打算从坐标来做后处理，但目前来看是行不通了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午2:57
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别多行文本时，输出结果乱序输出 (#496)





 
@wangguanhua 可以自己做一下后处理就好

**Comment by softboy99** [comment]
同求，不知道云端API的那种是怎么后处理的？

**Comment by liudatutu** [comment]
可尝试加中心点和行距辅助，根据行距判断分行，再根据x坐标，每行排序，应该可以达到比较好的效果。

**Comment by wangguanhua** [comment]
> 可尝试加中心点和行距辅助，根据行距判断分行，再根据x坐标，每行排序，应该可以达到比较好的效果。

我觉得你您说的不太对，既然纵坐标都不一样，那又怎么去判断多个文本块是否处于同一行呢？

**Comment by liudatutu** [comment]
设置行距阈值（小于文本行高度的均值），小于这个值，就可以看作是同一行的

**Comment by wangguanhua** [comment]
您这边有具体的代码吗？我还是想不明白，想从具体的代码进行调试理解。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午2:04
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 识别多行文本时，输出结果乱序输出 (#496)





 
设置行距阈值（小于文本行高度的均值），小于这个值，就可以看作是同一行的

**Comment by liudatutu** [comment]
具体的代码没有了，以前做版面分析写过，大致思路是根据文本框中心点的纵轴排序，后依次对比前后两个中心点纵轴距离，如若小于阈值，则为同一行的，反之就是下一行的。
但是对于检查精度不高或者合并单元格的文本，容易失效

**Comment by softboy99** [comment]
既然开源，大家贡献代码，一起把这个后处理做起来，才有意义啊！

**Comment by navneetkrc** [comment]
I used warp_perspective to orient the document and it helped in OCR task.
(Also if the text is making a positive slope it messes with OCR results, but in case of negative slope the result seems to be better).
Steps to follow:-
1. canny edge detection
2. find contors and keep the large ones
3. get approximate biggest contours
4. resize the rectangle document
5. correct the orientation using the warpperspective.

Actual code to correct the orientation:-

# apply Canny Edge Detection
edged = cv2.Canny(blurred, 0, 50)
orig_edged = edged.copy()

# find the contours in the edged image, keeping only the
# largest ones, and initialize the screen contour
(contours, _) = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
contours = sorted(contours, key=cv2.contourArea, reverse=True)

#x,y,w,h = cv2.boundingRect(contours[0])
#cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),0)

# get approximate contour
for c in contours:
    p = cv2.arcLength(c, True)
    approx = cv2.approxPolyDP(c, 0.02 * p, True)

    if len(approx) == 4:
        target = approx
        break


# mapping target points to 800x800 quadrilateral
approx = rect.rectify(target)
pts2 = np.float32([[0,0],[800,0],[800,800],[0,800]])

M = cv2.getPerspectiveTransform(approx,pts2)
dst = cv2.warpPerspective(orig,M,(800,800))

**Comment by 401557122** [comment]
> 可尝试加中心点和行距辅助，根据行距判断分行，再根据x坐标，每行排序，应该可以达到比较好的效果。

我目前做的项目也需要文本位置关系的信息，我是首先按纵坐标排序，然后逐个计算下一个框的纵坐标中心是否在该行所有的框的最大纵坐标和最小纵坐标之间，这样都还是会有个别的框串行。。。。。。

**Comment by CheungZeeCn** [comment]
动态规划解一个？

**Comment by Bryant-Yang** [comment]
对识别结果的有序映射， 简单的Y轴容差无法处理整幅画面倾斜的情况，假设同一行比较长且向上倾斜，第一个元素和最后一个元素的Y很可能就超过容差被认为是两行了。需要能够在识别结果中按行分组，google的android ocr库给出的结果是按文本快+按行分组，不过是不是符合实际也不能完全保证。
