### ISSUE TITLE
关于训练时Loss不下降的问题

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#497]
目前正在使用自己的数据集训练文本检测模型，DB，但是发现使用中文模型初始化，loss从3降到1.6就不再下降了，使用Imagenet-MV3模型初始化，loss从8降到2.3就不下降了，这是什么原因导致的尼，求帮助。
训练参数如下：
global：
 epcoh=100
 image_shape: [3, 1280, 1088]
Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.0002
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay
    total_epoch: 100
    step_each_epoch: 123
因为数据集中的图片大小从（1280,720）到（2356,1080）都有，不知道会不会是这里的影响

**Comment by MissPenguin** [comment]
image_shape不用设这么大，就用默认的640*640即可，这是random crop的size，不是直接对原图resize，另外，可否提供几张训练、测试的图片，看下场景难度

**Comment by ZhaoyangLi-nju** [comment]
![image](https://user-images.githubusercontent.com/43194342/89624003-31df5480-d8c8-11ea-84e1-4cca0a4cd188.png)
类似一些手机app的图像，对其中的文字进行训练和识别。现在loss基本在1.56就不下降了，现在只用了167张训练，不管怎么改学习率，loss都不下降了。大概是什么问题尼

**Comment by MissPenguin** [comment]
图片看着不难，先可视化看下模型效果吧。
效果不好的话，先试试把image_shape改回去，另外，训练数据偏少，可能也有影响。

**Comment by lx-rookie** [comment]
我这是loss从开始就在1.2到1.5徘徊，怎么训练都下不去。训练图片为2017的数据集，用的dbR50模型继续训练
