### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/rec/dataset_traversal.py#L154

### ISSUE THREAD

**Issue by ChChwang** [PaddlePaddle/PaddleOCR#4970]
lmdb 读取数据用到了 self.num_workers 了么，为什么这里+= self.num_workers

**Comment by andyjpaddle** [comment]
如果是多进程读取数据，就会和`self.num_workers`有关。建议使用`release`分支代码，`develop`分支代码后面不再更新维护
