### ISSUE TITLE
模型剪枝问题

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleOCR#4976]
模型剪枝后，出现softmax也被裁剪了。
模型训练配置文件为：rec_chinese_common_train_v2.0.yml
**剪枝前：**
![image](https://user-images.githubusercontent.com/36955510/146730101-c314f7b9-076c-4f58-a809-709853cbde4d.png)
剪枝后：
![image](https://user-images.githubusercontent.com/36955510/146730131-45c90e03-d1f7-4cd7-b4d2-15e9ba5f208a.png)
这个是为什么呢？

**Comment by tink2123** [comment]
请问剪枝是如何执行的呢

**Comment by LiquorPerfect** [comment]
@tink2123 我使用的PaddleOCR-release2.3/deploy/slim/prune/export_prune_model.py 这个脚本的，里面参数都是默认的，将输入维度改为rec输入[1, 3, 32, 320]维度，其他的不变。先进行敏感度分析，后进行导出模型。不知道刚刚的release2.4里面有没有修复。

**Comment by huangwenbiao** [comment]
@LiquorPerfect 你好，请问这个问题最终有解决方案吗？我在剪枝的时候，也出现这个softmax被剪枝了。

**Comment by LiquorPerfect** [comment]
> 
我后续没有关注哎，放弃了。
