### ISSUE TITLE
hub serving输入图片的base64,得到'Please check data format!', 'results': '', 'status': '-1'}

### ISSUE THREAD

**Issue by pkuyilong** [PaddlePaddle/PaddleOCR#498]
我是用的是hub serving的快速部署模式, 使用的是http://Ip地址:8868/predict/ocr_system这个接口
使用了两种方式来输入图片的base64
1. 
读入本地图片
`image = open(image_path, 'rb').read()
 imgBase64 = base64.b64encode(image).decode('utf-8')
`

2. 根据url读取图片 
`
content = requests.get(img_url).content
imgBase64 = base64.b64encode(content).decode('utf-8')
`
均会出现Please check data format的问题, 大部分图片是可以的, 有少部分会在10s之后返回Please check data format结果,请问在输入到hub serving之前如何进行处理?  我尝试过先转成Image, 然后convert('RGB'), 然后转base64也不工作.

**Comment by MissPenguin** [comment]
是只有部分图片会出现这种情况并且稳定复现吗？可否提供几张有问题的图片，我们测试看下

**Comment by pkuyilong** [comment]
![033png_rr的艺术你敢追吗天府泰剧02390317详情讨论影评弹幕暂被关闭恶魔的艺术2020泰国剧情恐怖惊悚悬疑天府泰剧字幕组第一季敬请期待](https://user-images.githubusercontent.com/22174241/89618850-803c2580-d8bf-11ea-8252-89feebc32550.png)
![151png_哼](https://user-images.githubusercontent.com/22174241/89618861-829e7f80-d8bf-11ea-9ed7-da6748cbf072.png)
![154png_后古希成](https://user-images.githubusercontent.com/22174241/89618866-8500d980-d8bf-11ea-91b9-d7b3971957e8.png)
![225png_32146圣盾龙王6圣盾4星神2秘术优先三星中期过度最终阵容关键英雄与核心装备保存为图片我要收藏](https://user-images.githubusercontent.com/22174241/89618869-86ca9d00-d8bf-11ea-84b2-e947c00f3104.png)
![246png_echo现代女孩单生的原因怕渣男怕海王怕白月光怕婆婆太凶怕家暴怕未来怀孕想跳楼怕因为没钱看男人脸色七七妹妹创作的原声首页象山消息我](https://user-images.githubusercontent.com/22174241/89618871-88946080-d8bf-11ea-8e53-7c1a920c1961.png)
![png_中国移动4g1010零钱明细我的零钱3020672转入零钱通给自己加加薪充值提现常见问题本服务由财付通提供](https://user-images.githubusercontent.com/22174241/89618896-9518b900-d8bf-11ea-9f50-f40648b352b5.png)

**Comment by pkuyilong** [comment]
[bad_case.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5039841/bad_case.zip)
这些文件是有问题的, 这些文件大多数是以png为后缀名,但是其真正的格式可能不是png.
我是用https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md文档进行部署的, 这个服务是不是承受不了太大的访问量? 我一共300张图片, 没有添加延时访问,每次测试出来不work的图片会变动. 有些图片我单独测试是可以的,有些则不行,比较怪异.

**Comment by pkuyilong** [comment]
还有一个问题
- 我是https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md文档进行部署的, 分别使用到了识别和检测inference两个模型, 但是同时我也是用过`ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")`这个代码做过测试,请问这两者本质是不是一样的? 如果有区别,区别在哪? 看模型的命名都是db crnn mobile, 应该是一样的吧

**Comment by pkuyilong** [comment]
我使用的将图片转成base64的方法
```
def cv2_to_base64(img_path):
    "将图片数据转变成base64"
    image = cv2.imread(img_path)
    # output: ndarray
    data = cv2.imencode('.jpeg', image)[1]
    # data.tostring()  bytes类型
    return base64.b64encode(data.tostring()).decode('utf8')
```

**Comment by pkuyilong** [comment]
### 我使用的将本地图片转变成base64的方法
```
import cv2
def cv2_to_base64(img_path):
    """
    将图片数据转变成base64
    :param img_path:
    :return:
    """
    image = cv2.imread(img_path)
    # output: ndarray
    data = cv2.imencode('.jpeg', image)[1]
    # data.tostring()  bytes类型
    return base64.b64encode(data.tostring()).decode('utf8')
```
我认为这一点很重要,可能你们使用的转换方法和我使用的不一致,导致结果会出现偏差. 如果有不同,能否提供一下你们根据本地图片转化成base64 以及根据url获取图片进行base64的代码?

**Comment by pkuyilong** [comment]
> 是只有部分图片会出现这种情况并且稳定复现吗？可否提供几张有问题的图片，我们测试看下

这些文件是有问题的, 这些文件大多数是以png为后缀名,但是其真正的格式可能不是png.
我是用https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md文档进行部署的, 这个服务是不是承受不了太大的访问量? 我一共300张图片, 没有添加延时访问,每次测试出来不work的图片会变动. 有些图片我单独测试是可以的,有些则不行,比较怪异.

[有问题的文件 bad_case.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5039985/bad_case.zip)

**Comment by grasswolfs** [comment]
> 还有一个问题
> 
> * 我是[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md文档进行部署的](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md%E6%96%87%E6%A1%A3%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2%E7%9A%84), 分别使用到了识别和检测inference两个模型, 但是同时我也是用过`ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")`这个代码做过测试,请问这两者本质是不是一样的? 如果有区别,区别在哪? 看模型的命名都是db crnn mobile, 应该是一样的吧

本质上是一样的，在PaddleOCR这里面内部代码打开，更加灵活，可以切换不同的模型配置，hub.module相对封装的更上层一些，底层是一样的。后缀mobile和server区分8.6M超轻量小模型和通用大模型

**Comment by grasswolfs** [comment]
> ### 我使用的将本地图片转变成base64的方法
> ```
> import cv2
> def cv2_to_base64(img_path):
>     """
>     将图片数据转变成base64
>     :param img_path:
>     :return:
>     """
>     image = cv2.imread(img_path)
>     # output: ndarray
>     data = cv2.imencode('.jpeg', image)[1]
>     # data.tostring()  bytes类型
>     return base64.b64encode(data.tostring()).decode('utf8')
> ```
> 
> 我认为这一点很重要,可能你们使用的转换方法和我使用的不一致,导致结果会出现偏差. 如果有不同,能否提供一下你们根据本地图片转化成base64 以及根据url获取图片进行base64的代码?

可以参考这个文档
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/test_hubserving.py

import base64
def cv2_to_base64(image):
    return base64.b64encode(image).decode('utf8')

**Comment by grasswolfs** [comment]
> 这些文件是有问题的, 这些文件大多数是以png为后缀名,但是其真正的格式可能不是png.

https://www.paddlepaddle.org.cn/hub/scene/ocr
在线测试了一下，应该只有一个是确实没有识别文字的，其它的都似乎ok的，可能还是和base64转码有关系

**Comment by MissPenguin** [comment]
> 我是用的是hub serving的快速部署模式, 使用的是[http://Ip地址:8868/predict/ocr_system这个接口](http://Ip%E5%9C%B0%E5%9D%80:8868/predict/ocr_system%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3)
> 使用了两种方式来输入图片的base64
> 1.
> 读入本地图片
> `image = open(image_path, 'rb').read() imgBase64 = base64.b64encode(image).decode('utf-8') `
> 
> 1. 根据url读取图片
>    `content = requests.get(img_url).content imgBase64 = base64.b64encode(content).decode('utf-8')`
>    均会出现Please check data format的问题, 大部分图片是可以的, 有少部分会在10s之后返回Please check data format结果,请问在输入到hub serving之前如何进行处理?  我尝试过先转成Image, 然后convert('RGB'), 然后转base64也不工作.

是完全按照文档（https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md）操作的吗，我这边测试你提供的几张badcase都没有问题的。编码方式可以在客户端测试脚本中找到：tools/test_hubserving.py

**Comment by MissPenguin** [comment]
> 我是用的是hub serving的快速部署模式, 使用的是[http://Ip地址:8868/predict/ocr_system这个接口](http://Ip%E5%9C%B0%E5%9D%80:8868/predict/ocr_system%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3)
> 使用了两种方式来输入图片的base64
> 1.
> 读入本地图片
> `image = open(image_path, 'rb').read() imgBase64 = base64.b64encode(image).decode('utf-8') `
> 
> 1. 根据url读取图片
>    `content = requests.get(img_url).content imgBase64 = base64.b64encode(content).decode('utf-8')`
>    均会出现Please check data format的问题, 大部分图片是可以的, 有少部分会在10s之后返回Please check data format结果,请问在输入到hub serving之前如何进行处理?  我尝试过先转成Image, 然后convert('RGB'), 然后转base64也不工作.

是完全按照文档（ https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md ）操作的吗，我这边测试你提供的几张badcase都没有问题的。编码方式可以在客户端测试脚本中找到：tools/test_hubserving.py

**Comment by pkuyilong** [comment]
> > 我是用的是hub serving的快速部署模式, 使用的是[http://Ip地址:8868/predict/ocr_system这个接口](http://Ip%E5%9C%B0%E5%9D%80:8868/predict/ocr_system%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3)
> > 使用了两种方式来输入图片的base64
> > 1.
> > 读入本地图片
> > `image = open(image_path, 'rb').read() imgBase64 = base64.b64encode(image).decode('utf-8') `
> > 
> > 1. 根据url读取图片
> >    `content = requests.get(img_url).content imgBase64 = base64.b64encode(content).decode('utf-8')`
> >    均会出现Please check data format的问题, 大部分图片是可以的, 有少部分会在10s之后返回Please check data format结果,请问在输入到hub serving之前如何进行处理?  我尝试过先转成Image, 然后convert('RGB'), 然后转base64也不工作.
> 
> 是完全按照文档（ https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md ）操作的吗，我这边测试你提供的几张badcase都没有问题的。编码方式可以在客户端测试脚本中找到：tools/test_hubserving.py

###  我的测试方式与你的测试方式不同
我将hub serving 打包成一个docker, 然后去请求它的base64接口, 输入数据是300+张图片, 一个for循环去请求这个接口

### 重新测试及怀疑
每张图片的请求间隔为5s,大部分图片都可以在很短的时间内产出结果,少部分数据会在10s之后返回, 是不是hub serving无法短时间内无法处理大量请求问题

## Please check  data format 的触发条件
我已经按照二进制读入以及cv2_to_base64进行转变base64了, 能不能帮忙看看"Please check data format" 是在什么条件下触发的?  我在这个代码里没有找到这条语句. 我最想了解的就是为什么会触发data format的问题.

**Comment by MissPenguin** [comment]
> ### 重新测试及怀疑
> 每张图片的请求间隔为5s,大部分图片都可以在很短的时间内产出结果,少部分数据会在10s之后返回, 是不是hub serving无法短时间内无法处理大量请求问题
> 
> ## Please check data format 的触发条件
> 我已经按照二进制读入以及cv2_to_base64进行转变base64了, 能不能帮忙看看"Please check data format" 是在什么条件下触发的? 我在这个代码里没有找到这条语句. 我最想了解的就是为什么会触发data format的问题.

hub serving目前还没做过压测，但你间隔5s访问应该不存在压力问题，可以看看每次卡住的图像是不是固定图像，并且稳定复现，看样子有可能是因为遇到比较大的图像，在编解码上耗时比较大。

**Comment by MissPenguin** [comment]
check data format 这个不是外层代码抛出的，需要根据具体报错信息进行定位，可能是底层抛出的。而且，直接测试没有数据格式问题，所以应该不是服务逻辑引起的，可能跟你的docker环境有关。

**Comment by ymxcywl** [comment]
我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？

**Comment by MissPenguin** [comment]
> 我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？

看着不像显存不够导致的报错，你也是将hub serving 打包成docker遇到的报错吗，还是直接按照教程跑的？

**Comment by pkuyilong** [comment]
> > 我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？
> 
> 看着不像显存不够导致的报错，你也是将hub serving 打包成docker遇到的报错吗，还是直接按照教程跑的？

### 是显存不足导致的
- 可能碰到大图的时候会占用更多的显存,当时我的0号卡是跑着其他服务的. 然后我切换到另一台服务器上一张空的GPU卡上,可以正常运行.
- 我进入docker查看了日志,就是报cuda OOM, 给出的提示要么换卡,要么调小batch_size,关键是batch_size在哪里调小也不知道
- 这个服务的报错不是底层抛出的
     - 可能是在部署代码中的一个异常抛出, 那不成是paddlepaddle中的?

**Comment by pkuyilong** [comment]
> 我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？

是显存不够导致的, 换张空卡就可以了

**Comment by MissPenguin** [comment]
> > > 我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？
> > 
> > 
> > 看着不像显存不够导致的报错，你也是将hub serving 打包成docker遇到的报错吗，还是直接按照教程跑的？
> 
> ### 是显存不足导致的
> * 可能碰到大图的时候会占用更多的显存,当时我的0号卡是跑着其他服务的. 然后我切换到另一台服务器上一张空的GPU卡上,可以正常运行.
> * 我进入docker查看了日志,就是报cuda OOM, 给出的提示要么换卡,要么调小batch_size,关键是batch_size在哪里调小也不知道
> * 这个服务的报错不是底层抛出的
>   
>   * 可能是在部署代码中的一个异常抛出, 那不成是paddlepaddle中的?

那可能是hub serving的底层抛出的。batch size这个参数目前没有暴露出来，是默认的1，不需要调整哈～

**Comment by pkuyilong** [comment]
## 现在出现了另一个问题, 结果不一致
**方式1**
```
os.environ['CUDA_VISIBLE_DEVICES'] = '3'
ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")

test_img_path = [os.path.join(image_dir, name) for name in os.listdir(image_dir)]
np_images = list()
for item in test_img_path:
    try:
        image = cv2.imread(item)
        np_images.append(image)
    except Exception as e:
        print(e)


results = ocr.recognize_text(
    images=np_images,
    use_gpu=True,
    output_dir='ocr_result',
    visualization=True,
    box_thresh=0.5,
    text_thresh=0.5)
print(results)

```
**方式2 使用hub-serving**
```
        image = open(img_path, 'rb').read()
        imgBase64 = cv2_to_base64(image)
        # data = {'images': [imgBase64]}
        data = {"imgBase64": [imgBase64]}
        headers = {"Content-type": "application/json"}
        r = requests.post(url=url, headers=headers, data=json.dumps(data))
        result = json.loads(r.text)
```

- 之前我也请教过这个问题, 这两种方式都是一致的.
- 现在我发现方式一的效果好很多, 方式二的效果就不太好, 请问这两种方式的预处理有什么不同吗?
    - base64解码方式不同导致的?
    - cv2读取图片默认格式是BGR而不是RGB导致的?
    - 其他?

**Comment by pkuyilong** [comment]
> > > > 我也出现了这个问题，显存当时占用很满了，但是用其他小图都正常， 然后我把服务重启了，这个错误又出现不了了？ 是显存不够抛出的异常吗？
> > > 
> > > 
> > > 看着不像显存不够导致的报错，你也是将hub serving 打包成docker遇到的报错吗，还是直接按照教程跑的？
> > 
> > 
> > ### 是显存不足导致的
> > 
> > * 可能碰到大图的时候会占用更多的显存,当时我的0号卡是跑着其他服务的. 然后我切换到另一台服务器上一张空的GPU卡上,可以正常运行.
> > * 我进入docker查看了日志,就是报cuda OOM, 给出的提示要么换卡,要么调小batch_size,关键是batch_size在哪里调小也不知道
> > * 这个服务的报错不是底层抛出的
> >   
> >   * 可能是在部署代码中的一个异常抛出, 那不成是paddlepaddle中的?
> 
> 那可能是hub serving的底层抛出的。batch size这个参数目前没有暴露出来，是默认的1，不需要调整哈～

非常感谢你们的及时回应!!!

**Comment by MissPenguin** [comment]
> ## 现在出现了另一个问题, 结果不一致
> **方式1**
> 
> ```
> os.environ['CUDA_VISIBLE_DEVICES'] = '3'
> ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
> 
> test_img_path = [os.path.join(image_dir, name) for name in os.listdir(image_dir)]
> np_images = list()
> for item in test_img_path:
>     try:
>         image = cv2.imread(item)
>         np_images.append(image)
>     except Exception as e:
>         print(e)
> 
> 
> results = ocr.recognize_text(
>     images=np_images,
>     use_gpu=True,
>     output_dir='ocr_result',
>     visualization=True,
>     box_thresh=0.5,
>     text_thresh=0.5)
> print(results)
> ```
> 
> **方式2 使用hub-serving**
> 
> ```
>         image = open(img_path, 'rb').read()
>         imgBase64 = cv2_to_base64(image)
>         # data = {'images': [imgBase64]}
>         data = {"imgBase64": [imgBase64]}
>         headers = {"Content-type": "application/json"}
>         r = requests.post(url=url, headers=headers, data=json.dumps(data))
>         result = json.loads(r.text)
> ```
> 
> * 之前我也请教过这个问题, 这两种方式都是一致的.
> * 现在我发现方式一的效果好很多, 方式二的效果就不太好, 请问这两种方式的预处理有什么不同吗?
>   
>   * base64解码方式不同导致的?
>   * cv2读取图片默认格式是BGR而不是RGB导致的?
>   * 其他?

结果应该一样才对，第二种方式是cpu还是gpu，是最新代码吗，中间有一版cpu和gpu结果不一致，后来修复的

**Comment by pkuyilong** [comment]
> > ## 现在出现了另一个问题, 结果不一致
> > **方式1**
> > ```
> > os.environ['CUDA_VISIBLE_DEVICES'] = '3'
> > ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
> > 
> > test_img_path = [os.path.join(image_dir, name) for name in os.listdir(image_dir)]
> > np_images = list()
> > for item in test_img_path:
> >     try:
> >         image = cv2.imread(item)
> >         np_images.append(image)
> >     except Exception as e:
> >         print(e)
> > 
> > 
> > results = ocr.recognize_text(
> >     images=np_images,
> >     use_gpu=True,
> >     output_dir='ocr_result',
> >     visualization=True,
> >     box_thresh=0.5,
> >     text_thresh=0.5)
> > print(results)
> > ```
> > 
> > 
> > **方式2 使用hub-serving**
> > ```
> >         image = open(img_path, 'rb').read()
> >         imgBase64 = cv2_to_base64(image)
> >         # data = {'images': [imgBase64]}
> >         data = {"imgBase64": [imgBase64]}
> >         headers = {"Content-type": "application/json"}
> >         r = requests.post(url=url, headers=headers, data=json.dumps(data))
> >         result = json.loads(r.text)
> > ```
> > 
> > 
> > 
> > * 之前我也请教过这个问题, 这两种方式都是一致的.
> > * 现在我发现方式一的效果好很多, 方式二的效果就不太好, 请问这两种方式的预处理有什么不同吗?
> >   
> >   * base64解码方式不同导致的?
> >   * cv2读取图片默认格式是BGR而不是RGB导致的?
> >   * 其他?
> 
> 结果应该一样才对，第二种方式是cpu还是gpu，是最新代码吗，中间有一版cpu和gpu结果不一致，后来修复的

- 第二种方式使用的是gpu, 
- 之前cpu和gpu结果不一致的原因能大概说一下吗?

**Comment by MissPenguin** [comment]
> > > ## 现在出现了另一个问题, 结果不一致
> > > **方式1**
> > > ```
> > > os.environ['CUDA_VISIBLE_DEVICES'] = '3'
> > > ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
> > > 
> > > test_img_path = [os.path.join(image_dir, name) for name in os.listdir(image_dir)]
> > > np_images = list()
> > > for item in test_img_path:
> > >     try:
> > >         image = cv2.imread(item)
> > >         np_images.append(image)
> > >     except Exception as e:
> > >         print(e)
> > > 
> > > 
> > > results = ocr.recognize_text(
> > >     images=np_images,
> > >     use_gpu=True,
> > >     output_dir='ocr_result',
> > >     visualization=True,
> > >     box_thresh=0.5,
> > >     text_thresh=0.5)
> > > print(results)
> > > ```
> > > 
> > > 
> > > **方式2 使用hub-serving**
> > > ```
> > >         image = open(img_path, 'rb').read()
> > >         imgBase64 = cv2_to_base64(image)
> > >         # data = {'images': [imgBase64]}
> > >         data = {"imgBase64": [imgBase64]}
> > >         headers = {"Content-type": "application/json"}
> > >         r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > >         result = json.loads(r.text)
> > > ```
> > > 
> > > 
> > > 
> > > * 之前我也请教过这个问题, 这两种方式都是一致的.
> > > * 现在我发现方式一的效果好很多, 方式二的效果就不太好, 请问这两种方式的预处理有什么不同吗?
> > >   
> > >   * base64解码方式不同导致的?
> > >   * cv2读取图片默认格式是BGR而不是RGB导致的?
> > >   * 其他?
> > 
> > 
> > 结果应该一样才对，第二种方式是cpu还是gpu，是最新代码吗，中间有一版cpu和gpu结果不一致，后来修复的
> 
> * 第二种方式使用的是gpu,
> * 之前cpu和gpu结果不一致的原因能大概说一下吗?

使用gpu就不存在这个问题了，你直接跑结果也比第一种差吗，不打包成docker

**Comment by pkuyilong** [comment]
> > 这些文件是有问题的, 这些文件大多数是以png为后缀名,但是其真正的格式可能不是png.
> 
> https://www.paddlepaddle.org.cn/hub/scene/ocr
> 在线测试了一下，应该只有一个是确实没有识别文字的，其它的都似乎ok的，可能还是和base64转码有关系

**好的, 问题已经解决,是显卡out of memory问题 , 感谢!**
- 因为显卡内存不足问题未能得到正确结果, 返回这样的提示'Please check data format!', 'results': '', 'status': '-1'}可能有些不妥, 有一定的误导性

**Comment by pkuyilong** [comment]
> > > > ## 现在出现了另一个问题, 结果不一致
> > > > **方式1**
> > > > ```
> > > > os.environ['CUDA_VISIBLE_DEVICES'] = '3'
> > > > ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
> > > > 
> > > > test_img_path = [os.path.join(image_dir, name) for name in os.listdir(image_dir)]
> > > > np_images = list()
> > > > for item in test_img_path:
> > > >     try:
> > > >         image = cv2.imread(item)
> > > >         np_images.append(image)
> > > >     except Exception as e:
> > > >         print(e)
> > > > 
> > > > 
> > > > results = ocr.recognize_text(
> > > >     images=np_images,
> > > >     use_gpu=True,
> > > >     output_dir='ocr_result',
> > > >     visualization=True,
> > > >     box_thresh=0.5,
> > > >     text_thresh=0.5)
> > > > print(results)
> > > > ```
> > > > 
> > > > 
> > > > **方式2 使用hub-serving**
> > > > ```
> > > >         image = open(img_path, 'rb').read()
> > > >         imgBase64 = cv2_to_base64(image)
> > > >         # data = {'images': [imgBase64]}
> > > >         data = {"imgBase64": [imgBase64]}
> > > >         headers = {"Content-type": "application/json"}
> > > >         r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > > >         result = json.loads(r.text)
> > > > ```
> > > > 
> > > > 
> > > > 
> > > > * 之前我也请教过这个问题, 这两种方式都是一致的.
> > > > * 现在我发现方式一的效果好很多, 方式二的效果就不太好, 请问这两种方式的预处理有什么不同吗?
> > > >   
> > > >   * base64解码方式不同导致的?
> > > >   * cv2读取图片默认格式是BGR而不是RGB导致的?
> > > >   * 其他?
> > > 
> > > 
> > > 结果应该一样才对，第二种方式是cpu还是gpu，是最新代码吗，中间有一版cpu和gpu结果不一致，后来修复的
> > 
> > 
> > 
> > * 第二种方式使用的是gpu,
> > * 之前cpu和gpu结果不一致的原因能大概说一下吗?
> 
> 使用gpu就不存在这个问题了，你直接跑结果也比第一种差吗，不打包成docker

1.  经过测试,这个和docker没有关系,本地调用和docker里面调用是一致的
2. 方式一使用的是cv2读入的, 方式二是直接读入图片的二进制, 我认为是**转base64操作不同导致结果不一致**, 能看一下如何通过**图片本身以及图片url转成hub-serving标准的base64**吗?
3. 代码不是最新代码, 是上一个星期的代码,也就是8月3日左右的代码, 之前cpu和gpu版本输出不一致这个问题是在最近一周修复的吗?我看你们最近一个星期内的commits里面,最近一个星期似乎是没有这方面的改动.

**Comment by MissPenguin** [comment]
那跟代码版本应该没关系，tools/test_hubserving.py里就是读二进制然后转b64的（ https://github.com/PaddlePaddle/PaddleOCR/blob/1e8f414662864dc187eea95e1b06b4f2c686f479/tools/test_hubserving.py#L35 ），之前测试结果跟直接inference是一致的，你发一下有diff的测试图片，我跑一下看看

**Comment by pkuyilong** [comment]
> 那跟代码版本应该没关系，tools/test_hubserving.py里就是读二进制然后转b64的（
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/1e8f414662864dc187eea95e1b06b4f2c686f479/tools/test_hubserving.py#L35
> 
> ），之前测试结果跟直接inference是一致的，你发一下有diff的测试图片，我跑一下看看

![005png_家乐福四元桥](https://user-images.githubusercontent.com/22174241/89873124-88ac9d00-dbec-11ea-9eb7-72b397ccb7ea.png)
- 方式一得到的结果是 家乐福
- 方式二得到的结果是 家乐撞

**Comment by pkuyilong** [comment]
> > 那跟代码版本应该没关系，tools/test_hubserving.py里就是读二进制然后转b64的（
> > https://github.com/PaddlePaddle/PaddleOCR/blob/1e8f414662864dc187eea95e1b06b4f2c686f479/tools/test_hubserving.py#L35
> > 
> > ），之前测试结果跟直接inference是一致的，你发一下有diff的测试图片，我跑一下看看
> 
> ![005png_家乐福四元桥](https://user-images.githubusercontent.com/22174241/89873124-88ac9d00-dbec-11ea-9eb7-72b397ccb7ea.png)
> 
> * 方式一得到的结果是 家乐福
> * 方式二得到的结果是 家乐撞

[005png_家乐福四元桥.png.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5055610/005png_.png.zip)
这是同一张图片, zip压缩过不知道会不会影响结果

**Comment by pkuyilong** [comment]
![255png_收对象](https://user-images.githubusercontent.com/22174241/89874392-5dc34880-dbee-11ea-9afa-4828d6b62f1c.png)
[255png_收对象.png.zip, 点我下载, 压缩之后可能有损图片](https://github.com/PaddlePaddle/PaddleOCR/files/5055662/255png_.png.zip)
- 方式一, 使用cv直接读入,输入数据类型是ndarray
    - 输出结果是: 收对象
- 方式二hubserving, 使用open打开文件直接读入二进制,然后转base64
    - 输出结果是: 联爱家收对象

**Comment by MissPenguin** [comment]
直接用predict_system预测的结果与hub serving的结果一致，而predict_system也是用cv2.imread读图，所以不是base64编码的问题。结果不一致可能是中间迭代次数太多有的地方没有对齐导致的，图二结果不一致还有个原因是，hub module对结果进行了得分过滤，低于0.5的没有print出来，你加一个0.5的过滤，“联爱家收对象”也会变成“收对象”，所以diff实际没有看起来那么大

**Comment by pkuyilong** [comment]
> 直接用predict_system预测的结果与hub serving的结果一致，而predict_system也是用cv2.imread读图，所以不是base64编码的问题。结果不一致可能是中间迭代次数太多有的地方没有对齐导致的，图二结果不一致还有个原因是，hub module对结果进行了得分过滤，低于0.5的没有print出来，你加一个0.5的过滤，“联爱家收对象”也会变成“收对象”，所以diff实际没有看起来那么大
hub-serving默认的是db检测模型吧, 这是deploy/hub_serving/ocr_system中db的配置
```
    #DB parmas
    cfg.det_db_thresh =0.3
    cfg.det_db_box_thresh =0.5
    cfg.det_db_unclip_ratio =2.0
```
需要将cfg.det_db_thresh =0.3 改成cfg.det_db_thresh =0.5
