### ISSUE TITLE
电能表数字末尾漏识别问题，及标注方法求助。

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleOCR#4986]
1. 最近我们在做关于电能表屏显数字的识别，训练了一些数据后，发现比较容易出现数字末尾漏识别的问题，如图所示。对于检测框盖住了末尾数字的一部分，有时候能识别对，有时候就漏识别，这类问题要怎么解决呢？
2. 对于下图所示的屏显文字，在标注训练数据的时候，是将“001834.94”和“kWh”分开标注好，还是将其标注在一起“001834.94kWh”或“001834.94 kWh”这样好呢？
![IMG_0807](https://user-images.githubusercontent.com/75460093/146857283-21bb3d89-a0b6-4f58-b60a-2e9b7633b154.JPG)

**Comment by ioracion** [comment]
1.增加样本训练
2.个人建议仅标注数字就够了，其他的字都是固定的，标了没啥意义

**Comment by weixing0909** [comment]
1、分开标准，kwh没必要标注；
2、检测后的数字框人工扩宽一点，然后再送到识别；

**Comment by lzh111222334** [comment]
您好，我也在做这方面的，方便留个联系方式吗，可以一起交流交流，邮箱875725029@qq.com

**Comment by dium6i** [comment]
> 

目前就是人工调整了下，效果显著提高了

**Comment by dium6i** [comment]
> 1、分开标注，kwh没必要标注； 2、检测后的数字框人工扩宽一点，然后再送到识别；

目前就是人工调整了下，效果提升显著。

**Comment by lzh111222334** [comment]
> > 1、单独陷落，kwh没有一点陷阱； 2、检测后的数字框人工扩宽然后，再识别；
> 
> 现在就是人工调整了下，效果提升显着。

您好，我目前也在做相关的应用场景，可以加您个联系方式方便联系交流吗

**Comment by dium6i** [comment]
> > > 1、单独陷落，kwh没有一点陷阱； 2、检测后的数字框人工扩宽然后，再识别；
> > 
> > 
> > 现在就是人工调整了下，效果提升显着。
> 
> 您好，我目前也在做相关的应用场景，可以加您个联系方式方便联系交流吗

9094984459可以加微信试试看，不行前面加个1再
