### ISSUE TITLE
paddle serving使用cls方向分类准确度下降

### ISSUE THREAD

**Issue by yucongshub** [PaddlePaddle/PaddleOCR#4987]
paddle serving部署方式没有看到方向分类过程，在识别有方向图片时准确率很低，于是在web_service.py中加入了paddleocr中的方向分类代码和ch_ppocr_mobile_v2.0_cls_infer.tar模型，但是精度不高，下图是有无cls对比结果
![f585de18c021b91ddfffbfb2497f74d](https://user-images.githubusercontent.com/62985119/146863176-9ee2f3f8-f1ac-4820-90d6-afd89935b4da.png)

**Comment by WenmuZhou** [comment]
应该是分类模型在你的场景不太适应，可以用你的场景数据训练一个哈
