### ISSUE TITLE
repo里面提供的识别模型，训练的日志能提供一下吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#499]
在自有数据集上面训练，backbone res34vd 使用了预训练模型，loss从7000降到了20左右，acc从0升到了98%，但测试效果很差，不知道是不是过拟合,想参考一下官方训练日志。

**Comment by tink2123** [comment]
不带空格的中文 r34_vd log， 可以参考：[resnet_34_chinese.log](https://github.com/PaddlePaddle/PaddleOCR/files/5048853/resnet_34_chinese.log)

**Comment by deep-practice** [comment]
看着没有比我那个好多少，那我接着训吧

**Comment by deep-practice** [comment]
没有要预训练模型，从头训，针对数据集改了点参数，效果好多了。
