### ISSUE TITLE
开发文档建议

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#4991]
看到v2.4新增了检测和识别算法，有相应的评估指标吗，和之前的算法有何优劣？

现在paddleocr已经集成了很多检测和识别算法，但是缺乏对应的描述文档，对开发者不友好。

建议对相应的检测和识别算法都有对应的简单描述文档，以及各个算法模型的指标对比，优劣情况，以及面对各种应用场景推荐使用何种模型算法。

**Comment by Evezerest** [comment]
你好，算法描述欢迎通过目前的[课程作业活动的形式](https://github.com/PaddlePaddle/PaddleOCR/issues/4982)为我们补充，PP-OCR系列模型是经过调优和大量数据训练的，推荐在各个场景下首选使用
