### ISSUE TITLE
数据预处理跟PaddleOCRLable处理的数据 是一回事吗

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#4996]
这里的数据预处理跟PaddleOCRLable处理的数据 是一回事吗？有啥区别？我的图片数据经过PaddleOCRLable处理后 也能训练
![image](https://user-images.githubusercontent.com/4344069/146898026-ff7063b6-55b2-48a6-84c1-b7a73b06fc64.png)

**Comment by WenmuZhou** [comment]
这里的数据是指?

**Comment by wincentytg** [comment]
用于训练的图片数据，用2.2数据预处理 和PaddleOCRLable处理的区别是什么

**Comment by wincentytg** [comment]
@WenmuZhou
