### ISSUE TITLE
detect problem at crowded text scene

### ISSUE THREAD

**Issue by tp655998** [PaddlePaddle/PaddleOCR#5000]
遇到密集的文字時，無法辨認文字的方向，造成垂直文字容易框成水平的
![擷取](https://user-images.githubusercontent.com/57894211/146955606-ff474311-5974-4b16-9fa5-7042673cb426.PNG)

**Comment by WenmuZhou** [comment]
你好，图片中看起来没有你说的问题

**Comment by tp655998** [comment]
應該是框直的:
引擎、底盤、保養、電機、冷氣、輪胎、電池

但是他框成橫的:
引底保電冷輪電
擎盤養機氣胎池
