### ISSUE TITLE
文档修复--报名/提交 customize.md

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleOCR#5003]
任务类型：文档修复--报名/提交

文档位置链接：[https://github.com/livingbody/PaddleOCR/blob/develop/doc/doc_ch/customize.md](https://github.com/livingbody/PaddleOCR/blob/develop/doc/doc_ch/customize.md)

**Comment by Evezerest** [comment]
你好，请在这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/4982)下面回复上面的内容
