### ISSUE TITLE
Python版本的paddleocr识别图片，没有进行内存释放

### ISSUE THREAD

**Issue by Achelics** [PaddlePaddle/PaddleOCR#5007]
- 系统环境：Windows 10 和 Ubuntu 20.04
- 识别环境：使用CPU预测
- 版本号：Paddle：2.2.1  PaddleOCR：2.0.2
- 使用语言： Python
- 问题描述：
【paddle版本为：2.2.1；paddleocr版本为：2.0.2； 使用CPU预测；部署语言为Python，在连续识别大量图片的时候，内存一直在增长，没有降下来；如果部署语言为C++，在识别大量图片的时候，内存就是占用1个G左右，不会一直增长】

 是不是Python版本没有做内存回收导致的，总共连续识别了20张图片，内存就由一开始的6G增长到14G，直接占用了8G内存
![ttt](https://user-images.githubusercontent.com/6189863/147046347-0393335e-5a47-4804-afc2-ba51eec26feb.jpg)

**Comment by Achelics** [comment]
将paddleocr python版本升级到 2.3.0以上，在进行连续匹配时，内存消耗基本稳定在1GB左右

**Comment by jerrytang67** [comment]
遇到了同样的问题，docker部署的2.4的版本。每识别一次内存占用+300M
