### ISSUE TITLE
rec_ r50fpn_ vd_ none_ srn. yml。 Where can I find this file.

### ISSUE THREAD

**Issue by oknbvcxz** [PaddlePaddle/PaddleOCR#5010]
![image](https://user-images.githubusercontent.com/73927370/147052013-9f2271cc-9983-42d0-a4da-dbc74850c6e2.png)

**Comment by littletomatodonkey** [comment]
maybe you are looking for https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/configs/rec/rec_r50_fpn_srn.yml

**Comment by oknbvcxz** [comment]
> maybe you are looking for https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/configs/rec/rec_r50_fpn_srn.y谢谢你
