### ISSUE TITLE
推理报错，求解答

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#5011]
![image](https://user-images.githubusercontent.com/4344069/147052440-024a7b2d-c040-4d51-9ef6-53d41133aaad.png)
推理指令： python tools/infer/predict_system.py  --image_dir="./doc/imgs/2.jpg"  --det_model_dir="./inference/db_mv3/"   --rec_model_dir="./inference/rec_chinese_lite_v2.0/"   --rec_char_dict_path="../word_dict.txt"  --rec_char_type=ch  --use_angle_cls=false    --vis_font_path="./doc/fonts/simfang.ttf"

**Comment by wincentytg** [comment]
上边问题解决了但是推理的时候还是报另一个错，用的CPU  root DEBUG: dt_boxes num : 11, elapse : 0.838721513748169
![image](https://user-images.githubusercontent.com/4344069/147055989-928347d2-4f02-4fe9-91b3-03156c36a548.png)

**Comment by littletomatodonkey** [comment]
下面的这个看着没报错，具体的报错指的是什么呢？
