### ISSUE TITLE
推理结束后没有推理结果是什么原因？

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#5013]
![image](https://user-images.githubusercontent.com/4344069/147058289-213dc3ea-201a-4b3e-9a80-fc829d2848c5.png)
可能是因为训练不够还是其他参数配置的不对？

命令：python tools/infer/predict_system.py  --image_dir="./doc/imgs/2.jpg"  --det_model_dir="./inference/db_mv3/"   --rec_model_dir="./inference/rec_chinese_lite_v2.0/"   --rec_char_dict_path="../word_dict.txt"  --rec_char_type=ch  --use_angle_cls=false   --use_gpu=False   --vis_font_path="./doc/fonts/simfang.ttf"

**Comment by littletomatodonkey** [comment]
你好，字典路径是你自己的路径吗？看着没啥问题，可以把这里改成logger.info试下

https://github.com/PaddlePaddle/PaddleOCR/blob/93328b645701ebeb6fd75153895ae9a0d9cc475a/tools/infer/predict_system.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L158

**Comment by wincentytg** [comment]
对的 rec_char_dict_path="../word_dict.txt"这个路径 是对的不对的话  推理会提示找不到文件报错
