### ISSUE TITLE
在使用pycharm调试过程中， 直接点击 pycharm 终止调试按钮， pycharm 闪退，并且系统直接退到登录界面。 如果让 pycharm 执行完所有程序， pycharm 则正常。

### ISSUE THREAD

**Issue by weixing0909** [PaddlePaddle/PaddleOCR#5014]
这个问题估计很多同学都遇到过，很多人以为是paddle本身问题，我一开始也以为paddle与pycharm兼容性不好，然后我试了一下PaddleClas，PaddleClas不崩溃，那就应该不是Paddle本身问题。

估计很多人也发现运行build_dataloader之前，终止不会闪退，运行build_dataloader之后终止就闪退，然后我仔细调试了一下，在`PaddleOCR/ppocr/data/__init__.py`文件里发现了两行代码
```python
signal.signal(signal.SIGINT, term_mp)  
signal.signal(signal.SIGTERM, term_mp)
```

这两行注释掉，终止调试也不会闪退了。

原谅我等菜鸡只会用pycharm调试。

**Comment by ziyaxuanyi** [comment]
兄弟，vscode你值得拥有。调试完全无压力。

**Comment by littletomatodonkey** [comment]
这里添加这两句话是为了ctrl+c退出程序的时候，kill所有的子进程，不清楚pycharm的调试机制是否和这个有冲突哈
