### ISSUE TITLE
DB and CRNN Model combination

### ISSUE THREAD

**Issue by Ehteshamciitwah** [PaddlePaddle/PaddleOCR#5015]
Hello, Your work is great.

MY dataset has only four random characters (eg OFGY). I want to train DB detection on character labels and then want to use CRNN to predict each character. Then i will join them together for the final result

1. How I can join the pipeline of DB and CRNN together in a paddler. 

2. How I can use a pre-trained model and join the pipeline to get full-text detection + recognition model. 

Thank you

**Comment by littletomatodonkey** [comment]
You can refer this tut. You can replace the model path with your model.


https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_en/inference_ppocr_en.md
