### ISSUE TITLE
SRN 中 weight_sharing 这个参数是干什么用的？

### ISSUE THREAD

**Issue by yunfeiooo** [PaddlePaddle/PaddleOCR#5016]
似乎是和 word embedding 共享参数相关，但是具体的共享方式是什么？没有查到相关的资料，可以解答一下吗？

**Comment by tink2123** [comment]
这个参数没有用到，网络默认进行了权重共享。
在代码中目前是这样做的：
https://github.com/PaddlePaddle/PaddleOCR/blob/ca44e5766919b61b0e88513d62b551397703be2c/ppocr/modeling/heads/rec_srn_head.py#L251
