### ISSUE TITLE
文本识别训练时宽高比大于 10 或者文本长度大于 25 的图像会直接丢弃吗？

### ISSUE THREAD

**Issue by CharlesWu123** [PaddlePaddle/PaddleOCR#5017]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/FAQ.md#15
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/FAQ.md#210
你好，我从这两个问题中看到，宽高比大于10的以及文本长度超过25的训练图像都会被丢弃，这个具体在代码中哪里体现的呢？
那对于文档图像的训练，大部分的文本行图像宽高比都大于10并且文本长度都会超过25，在可以使用与训练模型的情况下应该怎么处理呢？

**Comment by littletomatodonkey** [comment]
在这里实现的

https://github.com/PaddlePaddle/PaddleOCR/blob/95c670faf6cf4551c841764cde43a4f4d9d5e634/ppocr/data/imaug/label_ops.py#L142

可以把图像shape变大点，比如`[3, 32, 640]`，然后max_text_length参数再修改的大一些

**Comment by CharlesWu123** [comment]
@littletomatodonkey 好的，感谢

**Comment by surdldz** [comment]
> 在这里实现的
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/95c670faf6cf4551c841764cde43a4f4d9d5e634/ppocr/data/imaug/label_ops.py#L142
> 
> 可以把图像shape变大点，比如`[3, 32, 640]`，然后max_text_length参数再修改的大一些

shape变大后，会导致推理变慢么？
