### ISSUE TITLE
图片尺寸不规则导致无法识别

### ISSUE THREAD

**Issue by jcn199729** [PaddlePaddle/PaddleOCR#5021]
- 系统环境/System Environment：Ubuntu 18.04.3 LTS

在截取视频字幕的部分后进行识别时，如图片尺寸长宽比较大则会漏检所有文字，请问有什么方法可以避免这种情况吗？或者这里会造成漏检的长宽比的阈值是多少呢？谢谢！

代码：
```
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang="ch")
result = ocr.ocr(image_path, cls=True)
print(result)
```

image1:
![image](https://user-images.githubusercontent.com/58527362/147089817-aa908c83-b5b9-4a68-bb9f-daf9735af9be.png)
image2:
![image](https://user-images.githubusercontent.com/58527362/147089845-705f0f24-1fdc-46d6-a4d6-dfd0447b05c1.png)
image3:
![image](https://user-images.githubusercontent.com/58527362/147089873-b7a707b8-f25a-4401-b97c-c69fd98f877a.png)
其中image2和image3均可识别出字幕文字，image中result的结果为空。另外请问是否可以设置只识别图中字幕部分，而跳过非字幕部分的文字呢？例如image1和image2中的”微信搜索张大仙“，“恢复”等，而只识别出“中路得管一管”

**Comment by MissPenguin** [comment]
> 如图片尺寸长宽比较大则会漏检所有文字

这个可能是算法缺陷，可以简单预处理一下提升效果，例如padding成image2这样

> 是否可以设置只识别图中字幕部分

这个不太好从算法层面解决（当然也可以试试训练数据只标注字幕部分，不标其他无关文字），比较方便的思路可以先试试加一些规则进行过滤，例如检测框的位置、宽高比等等

**Comment by weixing0909** [comment]
```python
PaddleOCR(use_angle_cls=True, lang="ch", det_limit_type='min', det_limit_side_len=64)
```
设定短边的最小分辨率，用你的image图片，det_limit_side_len=64，文字全能检测出来。

默认参数是det_limit_type='max', det_limit_side_len=960，也就是长边最大960.

改为det_limit_type='min', det_limit_side_len=64，也就是短边最小64.

算法本身挺好用的，注意里面参数设置

**Comment by jcn199729** [comment]
@weixing0909 @MissPenguin 感谢二位大佬，我再试试看，谢谢！

**Comment by linkewei0580** [comment]
> ```python
> PaddleOCR(use_angle_cls=True, lang="ch", det_limit_type='min', det_limit_side_len=64)
> ```
> 
> 设定短边的最小分辨率，用你的image图片，det_limit_side_len=64，文字全能检测出来。
> 
> 默认参数是det_limit_type='max', det_limit_side_len=960，也就是长边最大960.
> 
> 改为det_limit_type='min', det_limit_side_len=64，也就是短边最小64.
> 
> 算法本身挺好用的，注意里面参数设置

@weixing0909 这“det_limit_type='min', det_limit_side_len” 在C++的DEMO里怎么配置这个参数？

**Comment by Mona59** [comment]
> ```python
> PaddleOCR(use_angle_cls=True, lang="ch", det_limit_type='min', det_limit_side_len=64)
> ```
> 
> 设定短边的最小分辨率，用你的image图片，det_limit_side_len=64，文字全能检测出来。
> 
> 默认参数是det_limit_type='max', det_limit_side_len=960，也就是长边最大960.
> 
> 改为det_limit_type='min', det_limit_side_len=64，也就是短边最小64.
> 
> 算法本身挺好用的，注意里面参数设置

谢谢，遇到这个问题，改了就好了
