### ISSUE TITLE
PPOCRLabel按下D键如何让它自动保存而不是每次弹出个Atenntion提示

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#5024]
PPOCRLabel按下D键如何让它自动保存而不是每次弹出个Atenntion提示，因为有时候有大量标注，如果每次弹出一个警告框会很耽误时间，希望官方加个功能，自动保存而不是每次弹出Attention，You hava unsaved changes...提示

**Comment by Evezerest** [comment]
点击确认即可保存+跳转到下一张
