### ISSUE TITLE
新发现ocr数据集

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#5027]
发现一个北邮的ocr数据集
包含了五类场景：合成、文档、街景、手写、车牌

下载地址：https://bupt-ai-cz.github.io/Meta-SelfLearning/

**Comment by Evezerest** [comment]
你好，可以在这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/4982)里面回复，记录积分
