### ISSUE TITLE
请问文本识别模型为啥没用CML的方式而是用的DML的方式呢？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#5028]

**Comment by littletomatodonkey** [comment]
实验表名，识别蒸馏中，教师模型先固定参数的话，学生模型的效果比较差，所以这里就没有引入结构不同，更大的教师模型了，我们在中间层特征这块加入了l2 loss的监督，可以涨1.5%左右的精度，也就是识别里面的udml

**Comment by Dandelion111** [comment]
> 实验表明，识别蒸馏中，教师模型先固定参数的话，学生模型的效果比较差，所以这里就没有引入结构不同，更大的教师模型了，我们在中间层特征这块加入了l2 loss的监督，可以涨1.5%左右的精度，也就是识别里面的udml

谢谢回复，也就是目前文本检测模型DBNet用CML精度最高，CRNN模型DML精度最高

**Comment by littletomatodonkey** [comment]
是的，UDML

**Comment by Dandelion111** [comment]
> 是的，UDML

好的，目前V2版本的Hmean已经超过V1版本的大模型了，请问V2版本和V1版本大模型的精度相差多少呢，大佬们有做过对比吗？

**Comment by MissPenguin** [comment]
> > 是的，UDML
> 
> 好的，目前V2版本的Hmean已经超过V1版本的大模型了，请问V2版本和V1版本大模型的精度相差多少呢，大佬们有做过对比吗？

精度与V1大模型差不多

**Comment by Dandelion111** [comment]
> > > 是的，UDML
> > 
> > 
> > 好的，目前V2版本的Hmean已经超过V1版本的大模型了，请问V2版本和V1版本大模型的精度相差多少呢，大佬们有做过对比吗？
> 
> 精度与V1大模型差不多

谢谢各位大佬的回复
