### ISSUE TITLE
为什么会出现整行文字丢失

### ISSUE THREAD

**Issue by Quenii** [PaddlePaddle/PaddleOCR#5030]
参数如下：

python3 tools/infer/predict_system.py --image_dir="E:/t/Capture.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=False --use_space_char=True --use_gpu=False

![Capture](https://user-images.githubusercontent.com/657568/147201641-0a32e469-a3e5-4b5b-9442-7465aabbd20b.jpg)

**Comment by MissPenguin** [comment]
可能被过滤掉了，可以试试调小[drop_score](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/utility.py#L86)

**Comment by ziyaxuanyi** [comment]
这个问题我之前研究过，是方向分类器的问题，方向分类器会有一定的概率把正向的文字误判为180度，从而旋转了文本180，导致识别错误，得分很低，被过滤掉了。把方向分类器关闭，或者在源码里面对方向分类误判情况在不旋转180重新识别一下，就可以了。

**Comment by MissPenguin** [comment]
> 向分类器会有一定的概率把正向的文

这种情况也是有的，不过看你的命令里面没有开方向分类器呢：--use_angle_cls=False

**Comment by Quenii** [comment]
> 这个问题我之前研究过，是方向分类器的问题，方向分类器会有一定的概率把正向的文字误判为180度，从而旋转了文本180，导致识别错误，得分很低，被过滤掉了。把方向分类器关闭，或者在源码里面对方向分类误判情况在不旋转180重新识别一下，就可以了。

看上面的参数 我已经关掉了..

**Comment by Quenii** [comment]
> 可能被过滤掉了，可以试试调小[drop_score](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/utility.py#L86)

改了drop_score=0.3 0.1 都无变化

**Comment by MissPenguin** [comment]
> > 可能被过滤掉了，可以试试调小[drop_score](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/utility.py#L86)
> 
> 改了drop_score=0.3 0.1 都无变化

可以把检测的二值化分割图可视化出来，看是分割图没检出来，还是后处理过滤掉了
