### ISSUE TITLE
训练表格识别时出现的

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#5031]
报错提示：
ERROR: When parsing line {"filename": "637758258633434880.png", "imgid": "863343488", "html": {"cells": [{"tokens": ["<b>", "基", "金", "代", "码", "</b>"], "bbox": [3, 7, 82, 36]}, {"tokens": ["<b>", "基", "金", "名", "称", "</b>"], "bbox": [92, 7, 169, 36]}, {"tokens": ["<b>", "周", "涨", "跌", "幅", "</b>"], "bbox": [178, 9, 255, 35]}, {"tokens": ["<b>", "日", "均", "成", "交", "额", "（", "万", "元", "）", "</b>"], "bbox": [273, 7, 430, 38]}, {"tokens": ["<b>", "期", "末", "规", "模", "（", "亿", "元", "）", "</b>"], "bbox": [466, 8, 604, 37]}, {"tokens": ["<b>", "5", "1", "0", "0", "5", "0", "</b>"], "bbox": [12, 52, 71, 75]}, {"tokens": ["<b>", "5", "0", "E", "T", "F", "</b>"], "bbox": [103, 53, 153, 74]}, {"tokens": ["<b>", "-", "2", ".", "5", "1", "%", "</b>"], "bbox": [206, 53, 259, 74]}, {"tokens": ["<b>", "2", "3", "4", ",", "8", "0", "8", ".", "8", "5", "</b>"], "bbox": [321, 54, 452, 77]}, {"tokens": ["<b>", "6", "4", "5", ".", "8", "7", "</b>"], "bbox": [514, 53, 624, 74]}, {"tokens": ["<b>", "5", "1", "0", "3", "0", "0", "</b>"], "bbox": [12, 89, 72, 112]}, {"tokens": ["<b>", "3", "0", "0", "E", "T", "F", "</b>"], "bbox": [98, 89, 158, 112]}, {"tokens": ["<b>", "-", "2", ".", "1", "4", "%", "</b>"], "bbox": [205, 87, 258, 113]}, {"tokens": ["<b>", "2", "0", "3", ",", "8", "4", "8", ".", "5", "4", "</b>"], "bbox": [319, 91, 453, 112]}, {"tokens": ["<b>", "4", "9", "5", ".", "5", "4", "</b>"], "bbox": [534, 93, 624, 114]}, {"tokens": ["<b>", "5", "1", "0", "5", "0", "0", "</b>"], "bbox": [11, 125, 73, 151]}, {"tokens": ["<b>", "5", "0", "0", "E", "T", "F", "</b>"], "bbox": [98, 126, 158, 149]}, {"tokens": ["<b>", "0", ".", "0", "6", "%", "</b>"], "bbox": [209, 127, 259, 148]}, {"tokens": ["<b>", "9", "1", ",", "5", "2", "7", ".", "6", "1", "</b>"], "bbox": [318, 126, 454, 151]}, {"tokens": ["<b>", "4", "5", "5", ".", "1", "5", "</b>"], "bbox": [532, 126, 624, 146]}, {"tokens": ["<b>", "5", "1", "2", "8", "8", "0", "</b>"], "bbox": [12, 164, 72, 187]}, {"tokens": ["<b>", "证", "券", "E", "T", "F", "</b>"], "bbox": [95, 160, 161, 189]}, {"tokens": ["<b>", "0", ".", "2", "6", "%", "</b>"], "bbox": [209, 164, 260, 185]}, {"tokens": ["<b>", "1", "6", "1", ",", "2", "2", "7", ".", "6", "5", "</b>"], "bbox": [311, 165, 453, 187]}, {"tokens": ["<b>", "3", "4", "9", ".", "2", "1", "</b>"], "bbox": [532, 163, 624, 183]}, {"tokens": ["<b>", "5", "1", "0", "3", "3", "0", "</b>"], "bbox": [11, 199, 73, 224]}, {"tokens": ["<b>", "华", "夏", "3", "0", "0", "</b>"], "bbox": [96, 199, 161, 224]}, {"tokens": ["<b>", "-", "1", ".", "9", "1", "%", "</b>"], "bbox": [203, 201, 261, 223]}, {"tokens": ["<b>", "6", "8", ",", "1", "2", "7", ".", "6", "8", "</b>"], "bbox": [310, 201, 453, 226]}, {"tokens": ["<b>", "2", "8", "0", ".", "2", "6", "</b>"], "bbox": [528, 200, 624, 220]}, {"tokens": ["<b>", "5", "1", "0", "1", "8", "0", "</b>"], "bbox": [11, 235, 73, 261]}, {"tokens": ["<b>", "1", "8", "0", "E", "T", "F", "</b>"], "bbox": [99, 236, 159, 259]}, {"tokens": ["<b>", "-", "1", ".", "5", "9", "%", "</b>"], "bbox": [204, 238, 259, 258]}, {"tokens": ["<b>", "7", ",", "7", "9", "9", ".", "6", "8", "</b>"], "bbox": [308, 235, 455, 259]}, {"tokens": ["<b>", "2", "2", "9", ".", "4", "7", "</b>"], "bbox": [526, 237, 624, 257]}, {"tokens": ["<b>", "5", "1", "2", "0", "0", "0", "</b>"], "bbox": [12, 274, 72, 297]}, {"tokens": ["<b>", "券", "商", "E", "T", "F", "</b>"], "bbox": [96, 274, 161, 297]}, {"tokens": ["<b>", "0", ".", "3", "5", "%", "</b>"], "bbox": [210, 276, 259, 294]}, {"tokens": ["<b>", "1", "0", "0", ",", "4", "7", "1", ".", "2", "3", "</b>"], "bbox": [306, 274, 454, 298]}, {"tokens": ["<b>", "2", "2", "8", ".", "7", "7", "</b>"], "bbox": [532, 272, 624, 295]}, {"tokens": ["<b>", "1", "5", "9", "9", "1", "9", "</b>"], "bbox": [13, 311, 72, 334]}, {"tokens": ["<b>", "3", "0", "0", "E", "T", "F", "</b>"], "bbox": [99, 312, 157, 332]}, {"tokens": ["<b>", "-", "1", ".", "8", "2", "%", "</b>"], "bbox": [204, 312, 260, 334]}, {"tokens": ["<b>", "5", "4", ",", "5", "0", "4", ".", "8", "0", "</b>"], "bbox": [301, 311, 454, 336]}, {"tokens": ["<b>", "2", "0", "9", ".", "4", "3", "</b>"], "bbox": [526, 310, 624, 331]}, {"tokens": ["<b>", "5", "8", "8", "0", "0", "0", "</b>"], "bbox": [11, 346, 73, 372]}, {"tokens": ["<b>", "科", "创", "5", "0", "</b>"], "bbox": [101, 347, 156, 371]}, {"tokens": ["<b>", "-", "3", ".", "1", "4", "%", "</b>"], "bbox": [204, 349, 260, 371]}, {"tokens": ["<b>", "4", "2", ",", "9", "4", "9", ".", "6", "7", "</b>"], "bbox": [325, 348, 453, 365]}, {"tokens": ["<b>", "2", "0", "0", ".", "5", "2", "</b>"], "bbox": [536, 348, 624, 369]}, {"tokens": ["<b>", "5", "1", "3", "3", "3", "0", "</b>"], "bbox": [12, 387, 71, 406]}, {"tokens": ["<b>", "恒", "生", "互", "联", "</b>"], "bbox": [95, 385, 162, 408]}, {"tokens": ["<b>", "-", "6", ".", "0", "8", "%", "</b>"], "bbox": [206, 385, 257, 408]}, {"tokens": ["<b>", "1", "8", "2", "，", "2", "9", "1", ".", "1", "0", "</b>"], "bbox": [334, 387, 452, 407]}, {"tokens": ["<b>", "1", "7", "7", ".", "1", "8", "</b>"], "bbox": [547, 384, 624, 405]}], "structure": {"tokens": ["<thead>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<, error happened with msg: index 45 is out of bounds for axis 0 with size 45</tr>", "</tbody>"]}}, "split": "train"}

图片case：
![image](https://user-images.githubusercontent.com/28819717/147204541-c77d1beb-64dc-4e7b-aa4d-fab2fd111473.png)

想知道是因为数据标注的问题  还是因为哪里没有设置好呢？

**Comment by WenmuZhou** [comment]
麻烦在这里加上下面两句话，看看具体的错误栈 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/data/pgnet_dataset.py#L95

```python
import traceback
traceback.print_exc()
```

**Comment by mingo-doer** [comment]
确切报错在这里 
Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/pubtab_dataset.py", line 94, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/imaug/__init__.py", line 41, in transform
    data = op(data)
  File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/imaug/label_ops.py", line 481, in __call__
    td_idx = td_idx_list[cno]
IndexError: index 66 is out of bounds for axis 0 with size 66


表格标注是有的
可能是报错信息没有打全
完整标注：
{"filename": "637758258633434880.png", "imgid": "863343488", "html": {"cells": [{"tokens": ["<b>", "基", "金", "代", "码", "</b>"], "bbox": [3, 7, 82, 36]}, {"tokens": ["<b>", "基", "金", "名", "称", "</b>"], "bbox": [92, 7, 169, 36]}, {"tokens": ["<b>", "周", "涨", "跌", "幅", "</b>"], "bbox": [178, 9, 255, 35]}, {"tokens": ["<b>", "日", "均", "成", "交", "额", "（", "万", "元", "）", "</b>"], "bbox": [273, 7, 430, 38]}, {"tokens": ["<b>", "期", "末", "规", "模", "（", "亿", "元", "）", "</b>"], "bbox": [466, 8, 604, 37]}, {"tokens": ["<b>", "5", "1", "0", "0", "5", "0", "</b>"], "bbox": [12, 52, 71, 75]}, {"tokens": ["<b>", "5", "0", "E", "T", "F", "</b>"], "bbox": [103, 53, 153, 74]}, {"tokens": ["<b>", "-", "2", ".", "5", "1", "%", "</b>"], "bbox": [206, 53, 259, 74]}, {"tokens": ["<b>", "2", "3", "4", ",", "8", "0", "8", ".", "8", "5", "</b>"], "bbox": [321, 54, 452, 77]}, {"tokens": ["<b>", "6", "4", "5", ".", "8", "7", "</b>"], "bbox": [514, 53, 624, 74]}, {"tokens": ["<b>", "5", "1", "0", "3", "0", "0", "</b>"], "bbox": [12, 89, 72, 112]}, {"tokens": ["<b>", "3", "0", "0", "E", "T", "F", "</b>"], "bbox": [98, 89, 158, 112]}, {"tokens": ["<b>", "-", "2", ".", "1", "4", "%", "</b>"], "bbox": [205, 87, 258, 113]}, {"tokens": ["<b>", "2", "0", "3", ",", "8", "4", "8", ".", "5", "4", "</b>"], "bbox": [319, 91, 453, 112]}, {"tokens": ["<b>", "4", "9", "5", ".", "5", "4", "</b>"], "bbox": [534, 93, 624, 114]}, {"tokens": ["<b>", "5", "1", "0", "5", "0", "0", "</b>"], "bbox": [11, 125, 73, 151]}, {"tokens": ["<b>", "5", "0", "0", "E", "T", "F", "</b>"], "bbox": [98, 126, 158, 149]}, {"tokens": ["<b>", "0", ".", "0", "6", "%", "</b>"], "bbox": [209, 127, 259, 148]}, {"tokens": ["<b>", "9", "1", ",", "5", "2", "7", ".", "6", "1", "</b>"], "bbox": [318, 126, 454, 151]}, {"tokens": ["<b>", "4", "5", "5", ".", "1", "5", "</b>"], "bbox": [532, 126, 624, 146]}, {"tokens": ["<b>", "5", "1", "2", "8", "8", "0", "</b>"], "bbox": [12, 164, 72, 187]}, {"tokens": ["<b>", "证", "券", "E", "T", "F", "</b>"], "bbox": [95, 160, 161, 189]}, {"tokens": ["<b>", "0", ".", "2", "6", "%", "</b>"], "bbox": [209, 164, 260, 185]}, {"tokens": ["<b>", "1", "6", "1", ",", "2", "2", "7", ".", "6", "5", "</b>"], "bbox": [311, 165, 453, 187]}, {"tokens": ["<b>", "3", "4", "9", ".", "2", "1", "</b>"], "bbox": [532, 163, 624, 183]}, {"tokens": ["<b>", "5", "1", "0", "3", "3", "0", "</b>"], "bbox": [11, 199, 73, 224]}, {"tokens": ["<b>", "华", "夏", "3", "0", "0", "</b>"], "bbox": [96, 199, 161, 224]}, {"tokens": ["<b>", "-", "1", ".", "9", "1", "%", "</b>"], "bbox": [203, 201, 261, 223]}, {"tokens": ["<b>", "6", "8", ",", "1", "2", "7", ".", "6", "8", "</b>"], "bbox": [310, 201, 453, 226]}, {"tokens": ["<b>", "2", "8", "0", ".", "2", "6", "</b>"], "bbox": [528, 200, 624, 220]}, {"tokens": ["<b>", "5", "1", "0", "1", "8", "0", "</b>"], "bbox": [11, 235, 73, 261]}, {"tokens": ["<b>", "1", "8", "0", "E", "T", "F", "</b>"], "bbox": [99, 236, 159, 259]}, {"tokens": ["<b>", "-", "1", ".", "5", "9", "%", "</b>"], "bbox": [204, 238, 259, 258]}, {"tokens": ["<b>", "7", ",", "7", "9", "9", ".", "6", "8", "</b>"], "bbox": [308, 235, 455, 259]}, {"tokens": ["<b>", "2", "2", "9", ".", "4", "7", "</b>"], "bbox": [526, 237, 624, 257]}, {"tokens": ["<b>", "5", "1", "2", "0", "0", "0", "</b>"], "bbox": [12, 274, 72, 297]}, {"tokens": ["<b>", "券", "商", "E", "T", "F", "</b>"], "bbox": [96, 274, 161, 297]}, {"tokens": ["<b>", "0", ".", "3", "5", "%", "</b>"], "bbox": [210, 276, 259, 294]}, {"tokens": ["<b>", "1", "0", "0", ",", "4", "7", "1", ".", "2", "3", "</b>"], "bbox": [306, 274, 454, 298]}, {"tokens": ["<b>", "2", "2", "8", ".", "7", "7", "</b>"], "bbox": [532, 272, 624, 295]}, {"tokens": ["<b>", "1", "5", "9", "9", "1", "9", "</b>"], "bbox": [13, 311, 72, 334]}, {"tokens": ["<b>", "3", "0", "0", "E", "T", "F", "</b>"], "bbox": [99, 312, 157, 332]}, {"tokens": ["<b>", "-", "1", ".", "8", "2", "%", "</b>"], "bbox": [204, 312, 260, 334]}, {"tokens": ["<b>", "5", "4", ",", "5", "0", "4", ".", "8", "0", "</b>"], "bbox": [301, 311, 454, 336]}, {"tokens": ["<b>", "2", "0", "9", ".", "4", "3", "</b>"], "bbox": [526, 310, 624, 331]}, {"tokens": ["<b>", "5", "8", "8", "0", "0", "0", "</b>"], "bbox": [11, 346, 73, 372]}, {"tokens": ["<b>", "科", "创", "5", "0", "</b>"], "bbox": [101, 347, 156, 371]}, {"tokens": ["<b>", "-", "3", ".", "1", "4", "%", "</b>"], "bbox": [204, 349, 260, 371]}, {"tokens": ["<b>", "4", "2", ",", "9", "4", "9", ".", "6", "7", "</b>"], "bbox": [325, 348, 453, 365]}, {"tokens": ["<b>", "2", "0", "0", ".", "5", "2", "</b>"], "bbox": [536, 348, 624, 369]}, {"tokens": ["<b>", "5", "1", "3", "3", "3", "0", "</b>"], "bbox": [12, 387, 71, 406]}, {"tokens": ["<b>", "恒", "生", "互", "联", "</b>"], "bbox": [95, 385, 162, 408]}, {"tokens": ["<b>", "-", "6", ".", "0", "8", "%", "</b>"], "bbox": [206, 385, 257, 408]}, {"tokens": ["<b>", "1", "8", "2", "，", "2", "9", "1", ".", "1", "0", "</b>"], "bbox": [334, 387, 452, 407]}, {"tokens": ["<b>", "1", "7", "7", ".", "1", "8", "</b>"], "bbox": [547, 384, 624, 405]}], "structure": {"tokens": ["<thead>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}}, "split": "train"}

**Comment by mingo-doer** [comment]
@WenmuZhou 你好，今天出现了这个问题，可以麻烦帮忙看一下是因为什么么？
![image](https://user-images.githubusercontent.com/28819717/147618758-561826f0-2695-4c44-b8ba-6f1ce8174e35.png)
![image](https://user-images.githubusercontent.com/28819717/147618768-1e5da8fc-06b4-4e1f-932b-c1669f4c96b8.png)
![image](https://user-images.githubusercontent.com/28819717/147618780-90a3a28c-f675-4f61-b580-2fcd29e1b5c1.png)

**Comment by WenmuZhou** [comment]
看起来是json格式不对，检查下

**Comment by xxentropy** [comment]
> 确切报错在这里 Traceback (most recent call last): File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/pubtab_dataset.py", line 94, in **getitem** outs = transform(data, self.ops) File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/imaug/**init**.py", line 41, in transform data = op(data) File "/home/aistudio/PaddleOCR-release-2.3/ppocr/data/imaug/label_ops.py", line 481, in **call** td_idx = td_idx_list[cno] IndexError: index 66 is out of bounds for axis 0 with size 66
> 
> 表格标注是有的 可能是git导致的标注信息没有打全 ![image](https://user-images.githubusercontent.com/28819717/147327194-d1057244-acbe-4350-b86b-527ecda60ef9.png)

你好，我遇到了同样的问题，你解决吗
