### ISSUE TITLE
【训练检测模型】求求好心人分享解决方案

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#5038]
从epoch1到epoch1200，loss基本保持不变，有没有哪位知道怎么办？
换了不同的模型，使用相应的配置文件训练了多次
都一样，loss都不下降
求求哪位好心人告诉我该怎么办吧

**Comment by MissPenguin** [comment]
> 

不应该呀，你都干啥了

**Comment by MissPenguin** [comment]
代码版本，paddle版本，做了哪些修改，启动命令是啥

**Comment by yjhtc007** [comment]
我感觉检查一下数据集吧，是不是数据集有问题呢？

**Comment by s957995299** [comment]
> 代码版本，paddle版本，做了哪些修改，启动命令是啥

paddle版本：2.1.3
代码版本：release 2.3
只修改了batch_size_per_card和num_workers，左边为修改后
![image](https://user-images.githubusercontent.com/83860013/147306999-baab03a0-76d5-4ec1-bdb0-379c56ee757b.png)
启动命令：python tools/train.py -c configs/det/det_mv3_db.yml

**Comment by s957995299** [comment]
> 我感觉检查一下数据集吧，是不是数据集有问题呢？

您好，我重新下载过数据集和标签集了，并把它们放到了需要的路径
![image](https://user-images.githubusercontent.com/83860013/147307278-0689c69b-6b8e-47d2-9001-34b9ab9008ff.png)
还有什么办法检查数据集吗？
或者您有什么推荐的数据集可以用于训练检测模型吗？
我看paddle其他提供的数据集，似乎都是训练识别模型用的，那些仅包含文字部分的小图，ppocrlabel都标注不到他们

**Comment by yjhtc007** [comment]
> > 我感觉检查一下数据集吧，是不是数据集有问题呢？
> 
> 您好，我重新下载过数据集和标签集了，并把它们放到了需要的路径 ![image](https://user-images.githubusercontent.com/83860013/147307278-0689c69b-6b8e-47d2-9001-34b9ab9008ff.png) 还有什么办法检查数据集吗？ 或者您有什么推荐的数据集可以用于训练检测模型吗？ 我看paddle其他提供的数据集，似乎都是训练识别模型用的，那些仅包含文字部分的小图，ppocrlabel都标注不到他们

方便把训练日志截图出来看一下吗？训练集的格式可以参考paddle给的哈，看一下box坐标的格式是否处理成了paddleocr要求的格式呢。另外其他数据集的话可以试一试TD500，这个数据集包含的图片比较少，图片质量较icdar2015高一些吧，训练时的速度也会快一些，方便去验证。

**Comment by s957995299** [comment]
> 方便把训练日志截图出来看一下吗？训练集的格式可以参考paddle给的哈，看一下box坐标的格式是否处理成了paddleocr要求的格式呢。另外其他数据集的话可以试一试TD500，这个数据集包含的图片比较少，图片质量较icdar2015高一些吧，训练时的速度也会快一些，方便去验证。
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/7772305/train.log)
多谢您愿意帮我看看，麻烦您了
我这就去找找TD500的数据集

**Comment by yjhtc007** [comment]
> > 方便把训练日志截图出来看一下吗？训练集的格式可以参考paddle给的哈，看一下box坐标的格式是否处理成了paddleocr要求的格式呢。另外其他数据集的话可以试一试TD500，这个数据集包含的图片比较少，图片质量较icdar2015高一些吧，训练时的速度也会快一些，方便去验证。
> 
> [train.log](https://github.com/PaddlePaddle/PaddleOCR/files/7772305/train.log) 多谢您愿意帮我看看，麻烦您了 我这就去找找TD500的数据集

我简单看了一下，感觉你还是先查一下数据集的格式是否是正确的吧，可以换个检测模型用这些数据训练，看loss能不能降下来

**Comment by s957995299** [comment]
> > > 方便把训练日志截图出来看一下吗？训练集的格式可以参考paddle给的哈，看一下box坐标的格式是否处理成了paddleocr要求的格式呢。另外其他数据集的话可以试一试TD500，这个数据集包含的图片比较少，图片质量较icdar2015高一些吧，训练时的速度也会快一些，方便去验证。
> > 
> > 
> > [train.log](https://github.com/PaddlePaddle/PaddleOCR/files/7772305/train.log) 多谢您愿意帮我看看，麻烦您了 我这就去找找TD500的数据集
> 
> 我简单看了一下，感觉你还是先查一下数据集的格式是否是正确的吧，可以换个检测模型用这些数据训练，看loss能不能降下来

麻了，我换了TD500的数据集试了下，loss还是不下降emmm
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/7774154/train.log)

**Comment by s957995299** [comment]
@MissPenguin  麻烦管理删一下这个问题吧 没有探究的意义了 原因过于傻  这个问题留着会误导别人的
