### ISSUE TITLE
The missed character

### ISSUE THREAD

**Issue by qiulyu** [PaddlePaddle/PaddleOCR#504]
![image](https://user-images.githubusercontent.com/45893995/89646781-01f77780-d8ef-11ea-9a21-26965fe8d14f.png)
这种间隔很开的字符漏检，应该怎样处理呢

**Comment by MissPenguin** [comment]
这里A和B两个字符的漏检应该是因为是单字，不是因为间隔大。可以尝试增加单字的数据到训练数据中，进行针对性的优化。
