### ISSUE TITLE
2.4的识别推理模型下载链接出错

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleOCR#5041]
如[此部分](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th)所示：
![image](https://user-images.githubusercontent.com/48548141/147305866-953712ed-53b9-4d54-9fb1-da4fb3799480.png)
该箭头所指链接出错，无法下载。
报错提示为：{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"4338df4a-b807-42bd-b58f-a4509fb38a0c"}

**Comment by LDOUBLEV** [comment]
感谢反馈，链接已更正
https://paddleocr.bj.bcebos.com/dygraph_v2.1/chinese/ch_PP-OCRv2_rec_infer_opt.nb
