### ISSUE TITLE
CRNN识别模型 fine-tune 几乎没效果

### ISSUE THREAD

**Issue by JunYao1020** [PaddlePaddle/PaddleOCR#5042]
- 系统环境/System Environment：win11 or linux gpu
- 版本号/Version：Paddle：2.2.0-gpu 
已经基于paddle做过多次训练了, 但是ocr识别模型的迁移学习一直没有任何效果, 出现的情况是将lr 设置为0.001 则全程acc为0, 并且loss全程保持670左右。将lr设为0.00001, 则acc在起初一段的epoch里保持44左右, loss保持20左右, 不收敛也没震荡, 训练大概几十个epoch后, loss跑飞，acc逐步下降至0.windows和linux都是如此
我的数据应该没问题, 训练集大小2W，评估集大小6K，零基础训练的时候acc指标能达到80, 迁移学习的时候就不行了，以为是模型和配置文件不匹配的问题, 尝试了不仅限于官方推荐的两种方式，一个是rec_chinese_lite_train_v2.0.yml及其对应的模型做迁移学习, 另一个是ch_PP-OCRv2_rec_distillation.yml及其对应的模型做迁移学习，其他情况的迁移学习也尝试了, 效果均不好。
在paddledetection上迁移学习的时候没问题, 关于迁移学习我具体的操作是, 
1.下载配置文件对应的预训练模型
2.将预训练模型路径配置在yml文件中
3.修改训练集和评估集为我自己的数据路径
4.python tools/train.py -c configs/rec/****.yml 启动训练
希望能有解答！

**Comment by JunYao1020** [comment]
还有一种情况是, 加载预训练模型后, 训练一小会迅速过拟合

**Comment by LDOUBLEV** [comment]
如果你的字典和ppocr模型的字典不一样，finetune的时候是否更换了字典？

**Comment by JunYao1020** [comment]
没有, 我新发现在老版本的配置下, 也就是chinese lite那个 使用官方的预训练模型迁移学习是可以的, 但是使用新版本的ch_PP-OCRv2_rec_distillation.yml配置，配合官方给的8.5M训练模型使用, 仅设置预训练权重, 修改训练数据路径为我的数据路径. 删除loss下的use_log：true 配置，开始训练，就会出现loss无法收敛的情况。
对于use_log：true 这一项配置如果不去掉启动训练会报错, 报错信息大致是没有use_log这个key, 所以我去掉了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 中午1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] CRNN识别模型 fine-tune 几乎没效果 (Issue #5042)





 
如果你的字典和ppocr模型的字典不一样，finetune的时候是否更换了字典？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDOUBLEV** [comment]
**ch_PP-OCRv2_rec_distillation.yml**是蒸馏的方法，这个的预训练模型是https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_train.tar
加载预训练模型的方法是，设置如下参数为解压后的模型路径https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L11

**Comment by LDOUBLEV** [comment]
use_log的参数在这里设置：https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L90

**Comment by JunYao1020** [comment]
是的, 我的做法就是这样, 我下载的预训练模型是正确的, 这样启动的话, 在我的数据集上lr为0.001时loss在前几次epoch中先从20降到12 ，然后迅速发散 过程中acc则一直保持为零, lr为0.0001时loss大概在20附近, acc为44左右，十几次epoch后loss迅速发散, acc也逐步降为零。
如果我的陈述不够清楚, 稍后我发截图过去, 麻烦帮忙哪里没设置正确




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] CRNN识别模型 fine-tune 几乎没效果 (Issue #5042)





 
ch_PP-OCRv2_rec_distillation.yml是蒸馏的方法，这个的预训练模型是https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_train.tar
 加载预训练模型的方法是，设置如下参数为解压后的模型路径https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L11
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JunYao1020** [comment]
关于use_log参数, 我不明白他的作用, 是否可以直接去掉, 因为该参数会导致训练报错, 我并不想设置这个参数, 说明这个参数是想表达, 官方的配置文件上我所做的改动, 以及改动原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] CRNN识别模型 fine-tune 几乎没效果 (Issue #5042)





 
use_log的参数在这里设置：https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L90
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JunYao1020** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我在lr为0.001时发现loss不收敛, 但在 warmup的时候发现lr为0.000001的时候loss较小, 于是把loss改的特别小了, 这样训练的结果是acc在44左右震荡, loss在20左右震荡, 而后loss开始增大, acc逐渐降为0，这里的acc不光是eval的，同时也是train的，附件中是我当时训练的配置文件
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年12月24日 ***@***.***> 写道： 




use_log的参数在这里设置：https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml#L90

**Comment by JunYao1020** [comment]
Global:
  debug: false
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/alpha_rec_dml_ft_2
  save_epoch_step: 10
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/ch_PP-OCRv2_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_pp-OCRv2_distillation.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [200, 300]
    values : [0.000001, 0.0000001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 2.0e-05

Architecture:
  model_type: &model_type "rec"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002
  

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: head_out
  - DistillationDMLLoss:
      weight: 1.0
      act: "softmax"
      model_name_pairs:
      - ["Student", "Teacher"]
      key: head_out
  - DistillationDistanceLoss:
      weight: 1.0
      mode: "l2"
      model_name_pairs:
      - ["Student", "Teacher"]
      key: backbone_out

PostProcess:
  name: DistillationCTCLabelDecode
  model_name: ["Student", "Teacher"]
  key: head_out

Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./data_set/ft_rec/
    label_file_list:
    - ./data_set/ft_rec/ft_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 384]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_sections: 1
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data_set/ft_rec/
    label_file_list:
    - ./data_set/ft_rec/ft_eval.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 384]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8

**Comment by LDOUBLEV** [comment]
use_log表示对识别的输出取log操作，这个是必须的

看你用的配置文件里字典没有修改，可以确认下你训练数据是否需要调整字典：character_dict_path: ppocr/utils/ppocr_keys_v1.txt

另外你的学习率设置太小了，不合理：values : [0.000001, 0.0000001]

**Comment by JunYao1020** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我的训练数据是中英文内容, 使用默认的字典应该没有问题, 出题可能出在use_log上, 因为之前的训练我把这项配置去除了, 原因是加上后启动训练会报错。这是我的报错信息
        TypeError: __init__() got an unexpected keyword argument 'use_log'
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年12月24日 ***@***.***> 写道： 




use_log表示对识别的输出取log操作，这个是必须的

看你用的配置文件里字典没有修改，可以确认下你训练数据是否需要调整字典：character_dict_path: ppocr/utils/ppocr_keys_v1.txt

另外你的学习率设置太小了，不合理：values : [0.000001, 0.0000001]

**Comment by JunYao1020** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 88, in main
    loss_class = build_loss(config['Loss'])
  File "/root/workspace/paddle/PaddleOCR/ppocr/losses/__init__.py", line 54, in build_loss
    module_class = eval(module_name)(**config)
  File "/root/workspace/paddle/PaddleOCR/ppocr/losses/combined_loss.py", line 43, in __init__
    self.loss_func.append(eval(name)(**param))
TypeError: __init__() got an unexpected keyword argument 'use_log'

**Comment by JunYao1020** [comment]
Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/alpha_rec_dml_ft
  save_epoch_step: 3
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/ch_PP-OCRv2_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_pp-OCRv2_distillation.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [700, 800]
    values : [0.001, 0.0001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 2.0e-05

Architecture:
  model_type: &model_type "rec"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002
  

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: head_out
  - DistillationDMLLoss:
      weight: 1.0
      act: "softmax"
      use_log: true
      model_name_pairs:
      - ["Student", "Teacher"]
      key: head_out
  - DistillationDistanceLoss:
      weight: 1.0
      mode: "l2"
      model_name_pairs:
      - ["Student", "Teacher"]
      key: backbone_out

PostProcess:
  name: DistillationCTCLabelDecode
  model_name: ["Student", "Teacher"]
  key: head_out

Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./data_set/alpha_train/
    label_file_list:
    - ./data_set/alpha_train/rec_gt.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_sections: 1
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data_set/alpha_eval/
    label_file_list:
    - ./data_set/alpha_eval/rec_gt.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8

**Comment by JunYao1020** [comment]
我拉取了最新的代码, 现在不报错了！！

**Comment by kylecj77** [comment]
现在你的acc和loss正常了没

**Comment by GivanTsai** [comment]
> 

同有这个问题，只想funetine下某些字符的识别能力，然后合成了一些字符图片进行finetune，但训练完后模型损失了对其他字符的识别能力，请问你最后怎么解决了呢

**Comment by JunYao1020** [comment]
> @GivanTsai
> 
> I got the similar problem, can you show me what you fixed in your config file to finetune right?

I reduced the number of training times and the learning rate, in my case, the number of training times is 20 and the learning rate is 3e-4
