### ISSUE TITLE
同一张图片，裁剪前后识别结果不同

### ISSUE THREAD

**Issue by sunshine2176** [PaddlePaddle/PaddleOCR#5044]
使用2.4推理模型，识别同一张图片，整张识别时部分文字识别不到，裁剪一半后就能识别到，是什么原因呢？

**Comment by LDOUBLEV** [comment]
图片是否方便发出来，我这边debug看下

**Comment by sunshine2176** [comment]
> 

![more3](https://user-images.githubusercontent.com/5172675/147325049-da74fc5f-6096-4f91-9310-a7beaf9adc38.png)
图片中，"下载"文字在整张图片识别时无法识别，但是裁剪上半部分识别就可以识别到

**Comment by LDOUBLEV** [comment]
你用的哪个模型呢？

我用ch_ppocr_mobile_det  ch_ppocr_mobile_rec模型预测，可视化出来发现下载是可以检测到的，只是识别的时候有点问题

![image](https://user-images.githubusercontent.com/26592129/147343695-fc66d5c0-c412-4cf6-ab3c-2469d79de369.png)


如果你那边的模型尺寸缩小后导致无法识别，可以可视化看下是没有检测到，还是检测到了识别score太低过滤掉了

另外为了适应图像的大小，可以调整图像的预处理，resize的时候保持图像的长宽比；https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/tools/infer/predict_det.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L42

预处理实现代码在：
https://github.com/PaddlePaddle/PaddleOCR/blob/04c44974b13163450dfb6bd2c327863f8a194b3c/ppocr/data/imaug/operators.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L187

**Comment by sunshine2176** [comment]
![image](https://user-images.githubusercontent.com/5172675/147427737-245d35a4-939c-4495-8346-cb86cfdb3f72.png)
我用ch_ppocr_mobile_v2.0_det ch_ppocr_mobile_v2.0_rec和ch_ppocr_server_v2.0_det ch_ppocr_server_v2.0_rec都没有识别到，而且并没有对图像尺寸做过处理
![result](https://user-images.githubusercontent.com/5172675/147427938-fc81243e-2255-474b-8ada-db959f616e9a.jpg)

**Comment by sunshine2176** [comment]
![image](https://user-images.githubusercontent.com/5172675/149101121-17fc3e67-98fc-4e1c-affb-66788f1c025c.png)
这里文字没有识别到是什么原因呢？
