### ISSUE TITLE
crnn 识别的数据 文字频率不均衡怎么处理  数据不均衡的处理

### ISSUE THREAD

**Issue by 18112330636** [PaddlePaddle/PaddleOCR#5045]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
文字频率低的可以多加数据增强，或者合成一批新的数据
