### ISSUE TITLE
用训练后的模型去推理，没有识别结果 也没报错

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#5046]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： 2   
- 运行指令/Command Code：
命令：python tools/infer/predict_system.py --image_dir="./doc/imgs/2.jpg" --det_model_dir="./inference/db_mv3/" --rec_model_dir="./inference/rec_chinese_lite_v2.0/" --rec_char_dict_path="../word_dict.txt" --rec_char_type=ch --use_angle_cls=false --use_gpu=False --vis_font_path="./doc/fonts/simfang.ttf"
- 完整报错/Complete Error Message：可能是因为训练不够还是其他参数配置的不对？
rec_char_dict_path="../word_dict.txt" 这个路径里的word_dict.txt里边的内容是复制了 demo里的，word_dict.txt是训练的时候自己生成的吗？还是用demo里的就行？
![1640324493(1)](https://user-images.githubusercontent.com/4344069/147321542-00a830a9-0081-4bec-8e46-acbd4c635ef5.png)

**Comment by LDOUBLEV** [comment]
rec_char_dict_path="../word_dict.txt" 这个参数给你训练数据的字典

**Comment by wincentytg** [comment]
训练数据的这个字典 是怎么来的？自己写的还是用什么工具生成的额？谢谢

**Comment by wincentytg** [comment]
我的训练数据是用PaddleOCRLable这个工具处理的，在进行模型训练的时候也没传 字典/word_dict.txt这个呢，训练数据的字典在哪里取？

**Comment by wincentytg** [comment]
@LDOUBLEV

**Comment by LDOUBLEV** [comment]
"../word_dict.txt" 是根据你的标注文本统计而来的字符

如果你要用PaddleOCR跑示例
参考这里的文档即可，验证过了，按照文档运行是可以的：
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/inference_ppocr.md#4-%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E5%92%8C%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E4%B8%B2%E8%81%94%E6%8E%A8%E7%90%86

模型可以从这里下载，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/README.md#pp-ocr-series-model-listupdate-on-september-8th

下载inference model
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/README.md
![image](https://user-images.githubusercontent.com/26592129/147346297-20068c95-6e7f-486b-b958-1da32ce58c82.png)

**Comment by wincentytg** [comment]
"../word_dict.txt" 是根据你的标注文本统计而来的字符  这句话这里还不是很明白还得请教下您这边：
我的训练数据是用PaddleOCRLable这个工具处理的,导出数据的时候没有字典呢？那这个字典怎么生成的呢?现在就是不知道如何生成这个word_dict.txt字典，要手动统计吗？感谢解答。
![image](https://user-images.githubusercontent.com/4344069/147376640-25058739-ceae-404b-ac42-2f4d2b3a5c92.png)
这是标注后导出的数据

**Comment by wincentytg** [comment]
@LDOUBLEV

**Comment by LDOUBLEV** [comment]
> 那这个字典怎么生成的呢?

统计你标注文本的字符生成字典

**Comment by ioracion** [comment]
问：识别模型是用来识别字，那你希望你的模型能识别哪些字呢？
答：把要识别的字都放到这个word_dict.txt里，由于每个人场景不同，通常都要自己定制化。

**Comment by wincentytg** [comment]
@ioracion  这个字典文本是自己手动统计写进去的是吧？ 我以为是预处理数据的时候自动生成的呢

**Comment by wincentytg** [comment]
@LDOUBLEV 我识别的是车牌 用的也是车牌的word_dict.txt字典，但是就是没有识别结果

**Comment by zhangyingying520** [comment]
> @LDOUBLEV 我识别的是车牌 用的也是车牌的word_dict.txt字典，但是就是没有识别结果

你可以检测和识别模型分开测试，看看是那一部分的原因

**Comment by zhangyingying520** [comment]
> @LDOUBLEV 我识别的是车牌 用的也是车牌的word_dict.txt字典，但是就是没有识别结果

你可以看看结果图，多数是因为没用检测到
