### ISSUE TITLE
识别模型数据文本长度不一致，训练结果不佳怎么解决

### ISSUE THREAD

**Issue by yangyukun0619** [PaddlePaddle/PaddleOCR#5048]
1.识别模型文本长度不一致，请问怎么提高识别精度，针对这些文本长度不一致的数据，请问如何设置一个合理的imageshape
2.识别模型的精度在有预训练模型的基础上，请问怎么提升自己数据集的精度

**Comment by ziyaxuanyi** [comment]
尽量保证训练数据集里面文本长度为1-25的文本都要有

**Comment by yangyukun0619** [comment]
> 你好，请教一下保证了数据文本长度后，请问数据的imageshape怎么设定合适

**Comment by yangyukun0619** [comment]
> 尽量保证训练数据集里面文本长度为1-25的文本都要有



> 尽量保证训练数据集里面文本长度为1-25的文本都要有

你好，请教一下保证了数据文本长度后，请问数据的imageshape怎么设定合适

**Comment by yangyukun0619** [comment]
> 尽量保证训练数据集里面文本长度为1-25的文本都要有

你好，请教一下保证了数据文本长度后，请问数据的imageshape怎么设定合适

**Comment by LDOUBLEV** [comment]
统计你数据的数据长度，按照长宽比设置即可；比如你数据平均长度为10个中文字符，可以设置为3， 32， 320， 宽度是高度的10倍
注意，英文字符的宽度是高度的1/2

**Comment by AstonyJ** [comment]
> 统计你数据的数据长度，按照长宽比设置即可；比如你数据平均长度为10个中文字符，可以设置为3， 32， 320， 宽度是高度的10倍 注意，英文字符的宽度是高度的1/2

注意，英文字符的宽度是高度的1/2

您好，请问英文识别需要单独注意输入尺寸吗？但是我看英文训练的配置文件中最长25字符的情况下输入尺寸仍然是3， 32， 320？

**Comment by AstonyJ** [comment]
> 统计你数据的数据长度，按照长宽比设置即可；比如你数据平均长度为10个中文字符，可以设置为3， 32， 320， 宽度是高度的10倍 注意，英文字符的宽度是高度的1/2

注意，英文字符的宽度是高度的1/2

您好，请问英文识别需要单独注意输入尺寸吗？但是我看英文训练的配置文件中最长25字符的情况下输入尺寸仍然是3， 32， 320？这个尺寸符合 ‘英文字符的宽度是高度的1/2’设定么？
