### ISSUE TITLE
辨識這兩張影像，第二張照片多了一排字，第一排的結果不一樣(detect box 不一樣)，多了 "仙"。

### ISSUE THREAD

**Issue by mushasun** [PaddlePaddle/PaddleOCR#5054]
辨識這兩張影像，得到不一樣的結果，第二張照片多了一排字，第一排的結果不一樣(detect box 不一樣)，多了 "仙"。

![00000043-1](https://user-images.githubusercontent.com/5502390/147375422-2acaa808-5280-4c86-9e6d-f312549fa83e.png)

[2021/12/25 09:16:05] root DEBUG: dt_boxes num : 1, elapse : 1.8511605262756348
[2021/12/25 09:16:05] root DEBUG: cls num  : 1, elapse : 0.0059850215911865234
[2021/12/25 09:16:05] root DEBUG: rec_res num  : 1, elapse : 0.01796245574951172
[[[174.0, 292.0], [1428.0, 298.0], [1428.0, 338.0], [173.0, 332.0]], ('血，入肾以补精，配巴戟天、灵脾、杜仲温肾益精，更 辅以黄肉、熟', 0.86652386)]

![00000043-2](https://user-images.githubusercontent.com/5502390/147375426-a8ce679a-fdd8-4096-bede-dbb13f333491.png)
[2021/12/25 09:16:06] root DEBUG: dt_boxes num : 2, elapse : 0.036901235580444336
[2021/12/25 09:16:06] root DEBUG: cls num  : 2, elapse : 0.0063474178314208984
[2021/12/25 09:16:06] root DEBUG: rec_res num  : 2, elapse : 0.021941423416137695
[[[174.0, 292.0], [1426.0, 295.0], [1425.0, 338.0], [174.0, 335.0]], ('血，入肾以补精，配巴戟天、仙灵脾、杜仲温肾益精， 更辅以黄肉、熟', 0.8583056)]
[[[169.0, 357.0], [1383.0, 360.0], [1383.0, 403.0], [169.0, 400.0]], ('地滋肾育阴。补肾阳能振兴肾气，补肾阴能填精益元。 肾气充肾', 0.9740405)]

**Comment by andyjpaddle** [comment]
请您描述一下使用的模型和详细的运行指令

**Comment by mushasun** [comment]
Version 2.3 & 2.4 皆有同樣的問題

from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch") 
img_path = '00000043-1.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
img_path = '00000043-2.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

-------------------------------------------------------------------
Namespace(benchmark=False,
cls_batch_num=6,
cls_image_shape='3,
48,
192',
cls_model_dir='C:\\Users\\jason/.paddleocr/2.3.0.2\\ocr\\cls\\ch_ppocr_mobile_v2.0_cls_infer',
cls_thresh=0.9,
cpu_threads=10,
crop_res_save_dir='./output',
det=True,
det_algorithm='DB',
det_db_box_thresh=0.6,
det_db_score_mode='fast',
det_db_thresh=0.3,
det_db_unclip_ratio=1.5,
det_east_cover_thresh=0.1,
det_east_nms_thresh=0.2,
det_east_score_thresh=0.8,
det_limit_side_len=960,
det_limit_type='max',
det_model_dir='C:\\Users\\jason/.paddleocr/2.3.0.2\\ocr\\det\\ch\\ch_PP-OCRv2_det_infer',
det_pse_box_thresh=0.85,
det_pse_box_type='box',
det_pse_min_area=16,
det_pse_scale=1,
det_pse_thresh=0,
det_sast_nms_thresh=0.2,
det_sast_polygon=False,
det_sast_score_thresh=0.5,
draw_img_save_dir='./inference_results',
drop_score=0.5,
e2e_algorithm='PGNet',
e2e_char_dict_path='./ppocr/utils/ic15_dict.txt',
e2e_limit_side_len=768,
e2e_limit_type='max',
e2e_model_dir=None,
e2e_pgnet_mode='fast',
e2e_pgnet_score_thresh=0.5,
e2e_pgnet_valid_set='totaltext',
enable_mkldnn=False,
gpu_mem=500,
help='==SUPPRESS==',
image_dir=None,
ir_optim=True,
label_list=['0',
'180'],
label_map_path='./vqa/labels/labels_ser.txt',
lang='ch',
layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config',
max_batch_size=10,
max_seq_length=512,
max_text_length=25,
min_subgraph_size=15,
mode='structure',
model_name_or_path=None,
ocr_version='PP-OCRv2',
output='./output',
precision='fp32',
process_id=0,
rec=True,
rec_algorithm='CRNN',
rec_batch_num=6,
rec_char_dict_path='D:\\medicine\\PaddleOCR-release-2.4\\ppocr\\utils\\ppocr_keys_v1.txt',
rec_image_shape='3,
32,
320',
rec_model_dir='C:\\Users\\jason/.paddleocr/2.3.0.2\\ocr\\rec\\ch\\ch_PP-OCRv2_rec_infer',
save_crop_res=False,
save_log_path='./log_output/',
show_log=True,
structure_version='STRUCTURE',
table_char_dict_path=None,
table_char_type='en',
table_max_len=488,
table_model_dir=None,
total_process_num=1,
type='ocr',
use_angle_cls=True,
use_dilation=False,
use_gpu=True,
use_mp=False,
use_onnx=False,
use_pdserving=False,
use_space_char=True,
use_tensorrt=False,
vis_font_path='./doc/fonts/simfang.ttf',
warmup=False)
