### ISSUE TITLE
PaddleOCR的模型转成onnx后的推理结果与原版不一致，精度差很多

### ISSUE THREAD

**Issue by alatriste-lee** [PaddlePaddle/PaddleOCR#5055]
# https://github.com/PaddlePaddle/Paddle2ONNX/issues/451

按照以下页面的说明，先准备环境，然后转换，接下来测试转换后的onnx推理结果，并对比pdmodel的推理结果。
https://gitee.com/paddlepaddle/Paddle2ONNX#https://gitee.com/link?target=https%3A%2F%2Faistudio.baidu.com%2Faistudio%2Fprojectdetail%2F1461212

第一步，准备conda环境：

用pip安装完成后的：

(ocrv2) ➜ test_onnx pip list | grep paddle

paddle2onnx 0.9.0
paddleocr 2.3.0.2
paddlepaddle 2.2.1

(ocrv2) ➜ test_onnx pip list | grep onnx

onnx 1.9.0
paddle2onnx 0.9.0

第二步，转换：
从https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md 下载ch_PP-OCRv2_det、rec模型

paddle2onnx --model_dir ch_PP-OCRv2_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_det_infer.onnx --opset_version 10 --enable_onnx_checker True

paddle2onnx --model_dir ch_PP-OCRv2_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_rec_infer.onnx --opset_version 10 --enable_onnx_checker True

paddle2onnx --model_dir ch_ppocr_mobile_v2.0_cls_infer --model_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdmodel --params_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdiparams --save_file ppocrv1_cls_infer.onnx --opset_version 10 --enable_onnx_checker True

第三步，推理：
在PaddleOCR目录下，推理./deploy/lite/imgs/lite_demo.png

用onnx推理：

python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --cls_model_dir=ppocrv2_cls_infer_11.onnx --rec_model_dir=ppocrv2_rec_infer_11.onnx --det_model_dir=ppocrv2_det_infer_11.onnx --image_dir=./deploy/lite/imgs/lite_demo.png

用pdmodel推理：

python tools/infer/predict_system.py --use_gpu=False --cls_model_dir=./ch_ppocr_mobile_v2.0_cls_infer --rec_model_dir=./ch_PP-OCRv2_rec_infer --det_model_dir=./ch_PP-OCRv2_det_infer --image_dir=./deploy/lite/imgs/lite_demo.png

现在的问题是，原版pdmodel的推理结果和转成onnx后的推理结果不一致。
转换这一步的opset_version，9、10和11都试过了，用model_zoo页面多个模型排列组合测试过，都是不一致的。

报错截图
原版的效果：
![lite_demo_v2](https://user-images.githubusercontent.com/7877379/147378814-3bd1fa91-9977-4a9a-a91d-86857ec1f190.png)

onnx后的效果：
![lite_demo_v2_11](https://user-images.githubusercontent.com/7877379/147378815-5dad4a9d-34b0-434a-bb63-92469e0c59bd.png)

**Comment by jiangjiajun** [comment]
Duplicate of https://github.com/PaddlePaddle/Paddle2ONNX/issues/451

@alatriste-lee Let's handle this issue at Paddle2ONNX

**Comment by alatriste-lee** [comment]
按照新的说明做了重新导出，并按照 [https://github.com/PaddlePaddle/PaddleOCR/pull/5095/files](https://github.com/PaddlePaddle/PaddleOCR/pull/5095/files) 
的指导对文件做了修改，重新预测了一下，哎，这次的结果onnx和导出它的pdmodel是一致的了！！

感谢老师，老师好人一生平安～
