### ISSUE TITLE
生成新版本时出现：“项目中存在失效的软连接, 影响版本生成，请先删除软连接再尝试生成版本”

### ISSUE THREAD

**Issue by kjf4096** [PaddlePaddle/PaddleOCR#5056]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.2.1
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
生成新版本时出现：“项目中存在失效的软连接, 影响版本生成，请先删除软连接再尝试生成版本”，什么是软连接？怎么删除失效的软连接？

**Comment by RangeKing** [comment]
https://ai.baidu.com/forum/topic/show/968306

**Comment by kjf4096** [comment]
不管用啊，在aistudio中运行：

```
for a in `find . -type l`
do
    stat -L $a >/dev/null 2>/dev/null
    if [ $? -gt 0 ]
    then
      rm $a
    fi
done
```
出现：

```
  File "/tmp/ipykernel_102/970852464.py", line 1
    for a in `find . -type l`
             ^
SyntaxError: invalid syntax
```

**Comment by kjf4096** [comment]
在aistudio里把下面的代码粘贴到"Notebook"右边的“终端-1"里，回车运行了一下，然后可以生成新版本了。
```
for a in `find . -type l`
do
    stat -L $a >/dev/null 2>/dev/null
    if [ $? -gt 0 ]
    then
      rm $a
    fi
done
```
