### ISSUE TITLE
在哪能看到paddle现在所包含的检测识别模型有哪些

### ISSUE THREAD

**Issue by DamonYangyang** [PaddlePaddle/PaddleOCR#5061]
如题，在哪能看到paddle现在所包含的检测识别模型有哪些

**Comment by andyjpaddle** [comment]
检测识别模型在这里查看：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/algorithm_overview.md

PP-OCR系列模型： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md
