### ISSUE TITLE
"../word_dict.txt" 这个字典是根据什么怎么生成的呢

### ISSUE THREAD

**Issue by wincentytg** [PaddlePaddle/PaddleOCR#5062]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：win10
版本号/Version：Paddle： 2
运行指令/Command Code：
命令：python tools/infer/predict_system.py --image_dir="./doc/imgs/2.jpg" --det_model_dir="./inference/db_mv3/" --rec_model_dir="./inference/rec_chinese_lite_v2.0/" --rec_char_dict_path="../word_dict.txt" --rec_char_type=ch --use_angle_cls=false --use_gpu=False --vis_font_path="./doc/fonts/simfang.ttf"

"../word_dict.txt" 这个字典是根据什么怎么生成的呢》？
我的训练数据是用PaddleOCRLable这个工具处理的,导出数据的时候没有字典呢？那这个字典怎么生成的呢?现在就是不知道如何生成这个word_dict.txt字典，要手动统计吗？感谢解答。

**Comment by ziyaxuanyi** [comment]
根据自己训练模型时，所使用的数据集统计数据集里面包含的所有字符，写一个简单脚本统计就可以了。如果用的官方模型，加载官方给的字典即可。

**Comment by wincentytg** [comment]
@ziyaxuanyi 谢谢啦 可惜统计脚本不会写 嘿嘿
