### ISSUE TITLE
大家好，麻烦问大家一下，我在PaddleOCR训练自己的数据集时，不能准确检测区域或者根本无法检测。图像样本在下方，检测区域为生产日期部分，但是字体为针点式字体。

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleOCR#5064]
![0](https://user-images.githubusercontent.com/33543014/147427318-48c7a312-c3a4-4684-af48-8d6fb84560a8.jpg)

**Comment by WenmuZhou** [comment]
数据量多大呢，训练过程中，指标是多少呢，方便的话可以贴一下日志看看

**Comment by tuodi** [comment]
数据量为1000张该类型的商品样本，属于同分布。训练batch_size为12，迭代1200次，大概在700次获得best_accuracy，loss为0.1左右，之后开始上下小幅度震荡，验证集为10张样本，为训练集中选择的，在eval时，准确率为1，召回率只有0.26。不知道哪里出现了问题，谢谢。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 大家好，麻烦问大家一下，我在PaddleOCR训练自己的数据集时，不能准确检测区域或者根本无法检测。图像样本在下方，检测区域为生产日期部分，但是字体为针点式字体。 (Issue #5064)





 
数据量多大呢，训练过程中，指标是多少呢，方便的话可以贴一下日志看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WenmuZhou** [comment]
看起来很多漏检，建议
1. 可视化一下标注看看
2. 多搞点数据

**Comment by tuodi** [comment]
您好，您觉得我应该增加多少数据集呢（目前1000张样本，为同分布）？并且是否需要做数据增强（因为在训练数据时已经配置了数据增强）？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 上午7:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 大家好，麻烦问大家一下，我在PaddleOCR训练自己的数据集时，不能准确检测区域或者根本无法检测。图像样本在下方，检测区域为生产日期部分，但是字体为针点式字体。 (Issue #5064)





 
看起来很多漏检，建议
  
可视化一下标注看看
 
多搞点数据
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WenmuZhou** [comment]
同分布的比较好，数据增强暂时不用
