### ISSUE TITLE
Windows下， OCR识别报错-- 'env' 不是内部或外部命令，也不是可运行的程序或批处理文件

### ISSUE THREAD

**Issue by JimEverest** [PaddlePaddle/PaddleOCR#5065]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 版本号/Version：Paddle：2.3  PaddleOCR：2.3.0.1 
-  问题相关组件/Related components： ppocr
- 运行指令/Command Code：
- ![QQ图片20211227103121](https://user-images.githubusercontent.com/3079297/147428430-1e61ca3e-c4ce-4c1e-8095-7ec327592752.jpg)
- 完整报错/Complete Error Message：
![QQ图片20211226232206](https://user-images.githubusercontent.com/3079297/147428471-03f24025-8077-4491-883e-77b7ee20326a.jpg)

应该是一下代码引起：
PaddleOCR/tools/infer/utility.py  Line#315
```
def get_infer_gpuid():
    if not paddle.fluid.core.is_compiled_with_rocm():
        cmd = "env | grep CUDA_VISIBLE_DEVICES"
    else:
        cmd = "env | grep HIP_VISIBLE_DEVICES"
    env_cuda = os.popen(cmd).readlines()
```

直接将代码替换为
```
def get_infer_gpuid():
    return 0
```
可临时解决.

**Comment by WenmuZhou** [comment]
你好，感谢反馈，在这里修复了https://github.com/PaddlePaddle/PaddleOCR/pull/5075

**Comment by JimEverest** [comment]
> 你好，感谢反馈，在这里修复了#5075

您好Wenmu老师，我觉得#5072的方法更好一些， 因为即使再Windows中也有开发者可能会指定CUDA_VISIBLE_DEVICES环境变量。请您看一下，谢谢。

**Comment by WenmuZhou** [comment]
@JimEverest 可以，你将这部分代码同步到dygraph分支一下吧

**Comment by JimEverest** [comment]
> @JimEverest 可以，你将这部分代码同步到dygraph分支一下吧

已提交merge，谢谢Wenmu。 [#5112](https://github.com/PaddlePaddle/PaddleOCR/pull/5112)
