### ISSUE TITLE
PP-OCR_V2 训练

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#5066]
麻烦问一下，在训练新发布的V2模型的时候，直接在Global指定预训练模型，开启训练。
和同时在teacher里和student里面指定上预训练模型，开启训练的区别是什么，有具体一点的说明吗？谢谢

**Comment by WenmuZhou** [comment]
在V2的模型中，因为用到的蒸馏，
Global指定预训练模型：用于训练之后的eval和infer
teacher里和student里面指定上预训练模型：用于训练初期模型的初始化

**Comment by zhangyingying520** [comment]
> 在V2的模型中，因为用到的蒸馏， Global指定预训练模型：用于训练之后的eval和infer teacher里和student里面指定上预训练模型：用于训练初期模型的初始化
好的，明白了。但是记得在哪里看到说，用其中的一个学生模型进行推理是什么意思

**Comment by ziyaxuanyi** [comment]
蒸馏是用多个模型一起训练。

检测蒸馏，用了一个teacher和两个student蒸馏，teacher用的resnet模型较大精度较好，指导两个student训练，student使用的是mobilenet网络较小，两个student结构一样只是初始化不同，最后部署使用的时候，测试哪个stduent好就用哪个，只用其中一个好的student推理。

识别蒸馏，用的是两个网络结构一样的网络只是初始化不同，进行互相学习训练，只是用teacher和student名称进行区分而已。最后部署使用也是，测试哪个模型好就用哪个模型部署推理。

**Comment by zhangyingying520** [comment]
> 

好的，明白了，谢谢
