### ISSUE TITLE
【third-party】为PaddleOCR贡献超轻量网络Micronet和学习率策略OneCycleLR

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleOCR#5067]
1，关于MicroNet网络：
论文链接：https://arxiv.org/abs/2108.05894
参考代码：https://github.com/liyunsheng13/micronet
我的工作：1）将pytorch代码转换成paddle代码，按照PaddleOCR的代码风格集成到项目中。
                  2）修改代码，使backbone结构输出的维度为[n, 432, 1, 80]
                  3)  在我们的数据集(200W+)上做实验验证结构的可行性：backbone网络结构为MicronetM3时，训练时的IPS值在50左右，非常慢。backbone网络结构为MicronetM0时，训练时的IPS值在90左右，训练了30轮，训练时acc为57%左右，验证准确率为77%。
经过分析：模型耗时的地方在论文中作者提出的Dynamic Shift-Max激活函数，我将此激活函数替换成Rule6激活函数，backbone网络结构为MicronetM3时，训练时的IPS值在150左右，训练了30轮，训练时acc为67%左右，验证准确率为82%。
以上实验环境：单机4卡(V100)，num_work=8，batch size为256
2，关于OneCycleLR学习率策略
论文链接：https://arxiv.org/pdf/2012.12645.pdf
参考代码：https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#OneCycleLR
我的工作：1）将pytorch代码转换成paddle代码，按照PaddleOCR的代码风格集成到项目中。
                  2）在我们的数据集(200W+)上做实验验证学习率策略的效果：不加载预训练模型进行训练(30轮)，backbone模型用的是MobileNetV1Enhance，学习率策略为：name: Piecewise  decay_epochs : [20, 30].  values : [0.01, 0.002]. warmup_epoch: 1. 训练acc75%，验证acc86%。
不加载预训练模型进行训练(30轮)，backbone模型用的是MobileNetV1Enhance，学习率策略为：name: OneCycle   max_lr: 0.01。训练acc79%，验证87%。
请问我是否可以提交这两部分的代码，以及怎么提交，谢谢。

**Comment by Evezerest** [comment]
非常感谢您的工作，我们正在同步举办社区常规赛，您的项目可以提交到[这个issue](https://github.com/PaddlePaddle/PaddleOCR/issues/4982)中，按照工具与应用类的新模型任务报名后我们将集中review，同时您也有机会获得礼品大奖
