### ISSUE TITLE
训练出来的识别模型预测为英文，转成inference模型再预测就成了中文结果。设置char_type为en，就会报错

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#5068]
识别模型infei_rec.py结果为en符合我的字典![image](https://user-images.githubusercontent.com/77281977/147430979-183012a5-4e04-4cbb-97a0-d975c18ebc8c.png)
识别模型转成inference模型后predit_rec.py结果
![0f705495be45554a07cde959f81c973](https://user-images.githubusercontent.com/77281977/147431068-92e6d408-ac86-4331-96cb-526be26962ea.png)
加上char_type=en就会报错
![876370c75e79196df2454bf56b45dbd](https://user-images.githubusercontent.com/77281977/147431114-f0fda2f7-73ee-4b80-88a8-73bf34faf5ee.png)

**Comment by WenmuZhou** [comment]
使用--rec_char_dict_path指定你的字典，这个在文档里有说哦 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/recognition.md#5-%E8%BD%ACinference%E6%A8%A1%E5%9E%8B%E6%B5%8B%E8%AF%95
