### ISSUE TITLE
训练日志不输出iter，acc等评估数据，直接保存latest的模型，也不会保存best的模型。问题出在哪儿

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#5069]
这是我的配置文件内容
![image](https://user-images.githubusercontent.com/77281977/147431377-941b985f-6e9c-4169-9f15-cce74af48040.png)

这是训练日志截图
![image](https://user-images.githubusercontent.com/77281977/147431373-f770dc33-709b-4e0d-98ea-db7cf0b2f074.png)

**Comment by WenmuZhou** [comment]
问题在于，你的数据集太少了，你设置了print_batch_step:10，每10个iter打印一次日志，但是你的数据每个epoch不足10个batch，所以就没显示log，另外400次iter才会开始评估模型，所以不会有best模型，多看看文档吧 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/config.md

**Comment by gg22mm** [comment]
我的300多个也是一样的，也是数据不够吗？
