### ISSUE TITLE
在用OCR模型识别姓名时精度一直不高，请问有什么解决方法么

### ISSUE THREAD

**Issue by yangyukun0619** [PaddlePaddle/PaddleOCR#5074]
目前的数据集都是姓名，单个数据集文本长在两个字至五个字之间，但是训练下来精度一直不高，正确率只有80%，数据集100W.目前image_shape设置的32*160.请问有什么方法解决这个问题么，目前数据集都是合成数据，真实数据无法采集到那么多

**Comment by WenmuZhou** [comment]
姓名试一下attention的方法
