### ISSUE TITLE
照片反光导致识别效果不好，有没有好的解决方案

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/PaddleOCR#5077]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux version 3.10.0-862.el7.x86_64  (Red Hat 4.8.5-28) 
- 版本号/Version： (Red Hat 4.8.5-28) 
- Paddle：  paddlepaddle-gpu:2.2.1
- PaddleOCR： paddle-dygrah
- 运行指令/Command Code：!python3.7 tools/infer/predict_system.py

**Comment by 1220985305** [comment]
![148](https://user-images.githubusercontent.com/74039253/147447195-72e40d70-bda1-43d9-92db-309c7b834387.jpg)

**Comment by zhangyingying520** [comment]
对图片进行相应的预处理，在训练的时候多加入该类图片作为数据集
