### ISSUE TITLE
关于CRNN的一点困惑

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#508]
原版CRNN的backbone宽度降了4倍，高度降了32倍，这样送入RNN中的序列长度就是input_w/4
那repo中的resnet和mbv3宽高分别降了多少倍呢

**Comment by tink2123** [comment]
中文mv3 ： 高度下降32倍，宽度下降4倍
中文r34_vd: 高度下降32倍，宽度下降4倍

**Comment by deep-practice** [comment]
好的，感谢，emmm,静态图看着太难受了，都不知道怎么调试~

**Comment by MissPenguin** [comment]
> 好的，感谢，emmm,静态图看着太难受了，都不知道怎么调试~

动态图版本也在研发计划中了，我们争取尽快发布～

**Comment by deep-practice** [comment]
期待期待，飞浆团队真给力
