### ISSUE TITLE
PPOCRLabel 安装启动出现问题

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleOCR#5080]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 16.04 
- 版本号/Version：Paddle：2.2.1  PaddleOCR： 2.3.0.2 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：PPOCRLabel 
- 完整报错/Complete Error Message：Namespace(benchmark=False, cls=True, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/yangtianyu/.paddleocr/2.3.0.2/ocr/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/yangtianyu/.paddleocr/2.3.0.2/ocr/det/en/en_ppocr_mobile_v2.0_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], label_map_path='./vqa/labels/labels_ser.txt', lang='en', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_seq_length=512, max_text_length=25, min_subgraph_size=15, mode='structure', model_name_or_path=None, ocr_version='PP-OCRv2', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddleocr-2.3.0.2-py3.7.egg/paddleocr/ppocr/utils/en_dict.txt', rec_image_shape='3, 32, 320', rec_model_dir='/home/yangtianyu/.paddleocr/2.3.0.2/ocr/rec/en/en_number_mobile_v2.0_rec_infer', save_crop_res=False, save_log_path='./log_output/', show_log=False, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
Traceback (most recent call last):
  File "/home/yangtianyu/anaconda3/envs/paddleocr/bin/PPOCRLabel", line 8, in <module>
    sys.exit(main())
  File "/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 2151, in main
    app, _win = get_main_app(sys.argv)
  File "/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 2144, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file)
  File "/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 155, in __init__
    self.prevLabelText = getStr('tempLabel')
  File "/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 114, in <lambda>
    getStr = lambda strId: self.stringBundle.getString(strId)
  File "/home/yangtianyu/anaconda3/envs/paddleocr/lib/python3.7/site-packages/PPOCRLabel/libs/stringBundle.py", line 58, in getString
    assert(stringId in self.idToMessage), "Missing string id : " + stringId
AssertionError: Missing string id : tempLabel

**Comment by yangtianyu92** [comment]
晕掉了，这机器分给我Wen哥有锤子用。

**Comment by Evezerest** [comment]
在PPOCRLabel目录下使用python PPOCRLabel.py会报错么；以及whl包什么时候装的呢

**Comment by LeoRainly** [comment]
解决了吗？

**Comment by yangtianyu92** [comment]
解决了，就直接python那个pplabel.py文件启动就好了。还挺多奇奇怪怪的安装依赖问题，慢慢搞搞定的。



在 2023-02-06 10:35:56，"LeoRaine" ***@***.***> 写道：

解决了吗？
