### ISSUE TITLE
请问paddle ocr的android demo可以修改det_db_score_mode吗？

### ISSUE THREAD

**Issue by jjdadajj** [PaddlePaddle/PaddleOCR#5084]
https://blog.csdn.net/liubing8609/article/details/121196441
上述网址中有如下一段话：

Q3.1.62: 弯曲文本（如略微形变的文档图像）漏检问题？
A: db后处理中计算文本框平均得分时，是求rectangle区域的平均分数，容易造成弯曲文本漏检，已新增求polygon区域的平均分数，会更准确，但速度有所降低，可按需选择，在相关pr中可查看可视化对比效果。该功能通过参数 det_db_score_mode进行选择，参数值可选[fast(默认)、slow]，fast对应原始的rectangle方式，slow对应polygon方式。感谢用户buptlihang提pr帮助解决该问题rose。

可以通过调整det_db_score_mode改变对稍微弯曲文本的检测效果，请问官方提供的demo里面可以修改这个吗？
(https://github.com/paddlepaddle/PaddleOCR/tree/release/2.3/deploy/android_demo)
官方提供的推理模型支持修改这个参数吗？比如如下链接下载的paddle lite
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/README_ch.md#PP-OCRv2
image

谢谢！

**Comment by WenmuZhou** [comment]
不可以哈，目前还不支持

**Comment by jjdadajj** [comment]
那我应该怎么做才能解决安卓版本的这个问题呢？重新找数据集进行训练吗？谢谢

**Comment by WenmuZhou** [comment]
需要改后处理，加上对应的代码

**Comment by jjdadajj** [comment]
不用改.nb模型，修改Android demo里面的的后处理就可以是吧？

**Comment by WenmuZhou** [comment]
是的

**Comment by jjdadajj** [comment]
如下是android demo里面的：
![image](https://user-images.githubusercontent.com/95152270/147895584-1eefd2bf-fcc1-46dd-b0e1-f0f95e7e4dac.png)
每个文件都里面没有包含这个det_db_score_mode参数，也没有找到相关的变量能修改的，请问是不是目前paddle ocrandroid框架还不能支持呢？
比较着急用这个功能，不知道下一步怎么做了，谢谢！

**Comment by guoge6** [comment]
楼主，可以留个联系方式吗？我也要研究那个demo，可以请教一下您吗？

**Comment by jjdadajj** [comment]
可以的，qq21198370
