### ISSUE TITLE
最新版本的cpp_infer里面，rec识别后，结果string和boxes中坐标匹配问题

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleOCR#5085]
demo里面是这样的：
      cv::Mat srcimg = cv::imread(cv_all_img_names[i], cv::IMREAD_COLOR);
      if (!srcimg.data) {
        std::cerr << "[ERROR] image read failed! image path: " << cv_all_img_names[i] << endl;
        exit(1);
      }
      std::vector<std::vector<std::vector<int>>> boxes;
      std::vector<double> det_times;
      std::vector<double> rec_times;
        
      det.Run(srcimg, boxes, &det_times);
      time_info_det[0] += det_times[0];
      time_info_det[1] += det_times[1];
      time_info_det[2] += det_times[2];
        
      std::vector<cv::Mat> img_list;
      for (int j = 0; j < boxes.size(); j++) {
          cv::Mat crop_img;
          crop_img = Utility::GetRotateCropImage(srcimg, boxes[j]);
          if (cls != nullptr) {
              crop_img = cls->Run(crop_img);
          }
          img_list.push_back(crop_img);
      }

      rec.Run(img_list, &rec_times);
但是，rec后，识别到的结果string输出后，怎么跟boxes中坐标匹配呢，按顺序匹配，都是乱的

**Comment by littletomatodonkey** [comment]
box是个vector，rec结果也是一个vector，两个相同idx对应的内容是一样的

**Comment by xinsuinizhuan** [comment]
> box是个vector，rec结果也是一个vector，两个相同idx对应的内容是一样的

demo里面，没有rec结果输出，另外，rec里面做了排序std::vector<int> indices = Utility::argsort(width_list),已经被打乱了

**Comment by luodaoyi** [comment]
排序最后咋处理的？
