### ISSUE TITLE
文本行识别训练报错

### ISSUE THREAD

**Issue by JasonZhangS** [PaddlePaddle/PaddleOCR#509]
命令行: 
python3 tools/train.py -c configs/rec/rec_icdar15_train.yml

错误信息： 
[Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

现象：
cpu可以训练，GPU报错

**Comment by LDOUBLEV** [comment]
可以发一下完整的报错信息吗，

这里看不出来在哪报错了

> 命令行:
> python3 tools/train.py -c configs/rec/rec_icdar15_train.yml
> 
> 错误信息：
> [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
> 
> 现象：
> cpu可以训练，GPU报错

**Comment by JasonZhangS** [comment]
I have solved the issue.

set the GPU id first, then it will be ok.
