### ISSUE TITLE
MKL库是否会被正确使用

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleOCR#5094]
- 系统环境/System Environment：centos7.4  cpu：E7-4820 V4
- 版本号/Version：Paddle：2.2.1  PaddleOCR：2.3

mkl加速异常
1.使用单核心 mkl开启 其他参数默认 测试图像平均时间4s；
2.使用单核心 mkl关闭 其他参数默认 测试图像平均时间2s；

无报错，预测结果正常，开启mkl后字符检测变快，但是方向分类与字符识别变慢。

想请问下，mkl库是否需要进行一定的配置？有小伙伴有这种情况嘛？同样的代码在其他cpu上可以正常加速。

**Comment by Gmgge** [comment]
目前又测试到一台机器 i5 7500 cenos7.4和ubuntu16.04都测试过，paddle版本与上文相同，也出现开启mkl加速变慢的情况。

**Comment by littletomatodonkey** [comment]
是只测试了一张图片还是？测试预测耗时的时候需要warmup

**Comment by Gmgge** [comment]
@littletomatodonkey 测试了一批图像，并进行了warmup。
