### ISSUE TITLE
ocr预测是gpu利用率不高

### ISSUE THREAD

**Issue by T0L0ve** [PaddlePaddle/PaddleOCR#5096]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10+python3.8+cuda11.3+3070
- 版本号/Version：Paddle： paddlepaddle-gpu=2.2.1.post112 PaddleOCR：paddleocr=2.3.0.2 问题相关组件/Related components：
- 运行指令/Command Code：ocr = PaddleOCR(use_angle_cls=True, lang="ch")      ocr.ocr(img_path, cls=True)
循环使用ocr预测图像gpu利用率在20%左右，更改--rec_batch_num与--max_batch_size后依旧没有变化
![捕获](https://user-images.githubusercontent.com/38580985/147524766-9f89298f-cd53-4255-ab8b-9a29b5a1caea.PNG)

**Comment by 1a2cjitenfei** [comment]
哥，我在linux服务器上也有这个问题，前几天还能达到20%的利用率，这两天连20%也上不去，自己手动多进程也报错，不知道该咋办，也不想用padddle serving，后来我还多开终端窗口运行代码，发现GPU的内存都跑满了而计算资源占用率峰值也没过50%，想让它占用率高点还挺难的

**Comment by littletomatodonkey** [comment]
预处理本身耗时很多，可以看下预处理这块的具体耗时
