### ISSUE TITLE
官网的产品体验 空格无法识别

### ISSUE THREAD

**Issue by dly667** [PaddlePaddle/PaddleOCR#5097]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
![image](https://user-images.githubusercontent.com/26707226/147525355-16ee84c2-d081-4159-bee1-6662d9971b3f.png)

**Comment by littletomatodonkey** [comment]
因为之前的空格数据都是合成来的，这种空格场景确实表现一般，空格间隙大一些的话，效果会好一些

**Comment by dly667** [comment]
你好，那有什么解决方案吗
