### ISSUE TITLE
运行环境的相关问题

### ISSUE THREAD

**Issue by mfxss** [PaddlePaddle/PaddleOCR#5098]
重新安装了cuda 10.2 cudnn 7.6.5 和 paddlepaddle 2.1.2
python版本是3.7
![image](https://user-images.githubusercontent.com/27552782/147529697-c65881a4-3993-40cf-9093-5722a86bb45e.png)

会报以下错误：
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
![image](https://user-images.githubusercontent.com/27552782/147529719-d524f64a-9839-40d9-8e4d-f45f1cf1e270.png)
想问一下，是不是我的版本还是有问题，或者有什么解决办法

**Comment by littletomatodonkey** [comment]
`paddle.utils.run_check()`试下看看呢？

**Comment by mfxss** [comment]
![image](https://user-images.githubusercontent.com/27552782/147727939-d4852594-d28d-47ed-9061-0673401e47de.png)
一样还是报这个，现在改成docker运行了，没想到还是一样的问题

**Comment by littlebox692** [comment]
遇到同样的问题了，paddlepaddle-gpu版本2.2.2. 其他信息见贴图，请问有什么解决办法么？
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/25901256/161045038-e09627e4-37b3-4a02-8aa6-13cc1050efe1.png">

**Comment by wa008** [comment]
+1 遇到了相同的问题

**Comment by Morgan-Gan** [comment]
> +1 遇到了相同的问题

这个问题是因为paddle版本的算力和你平台GPU算力不匹配所致，譬如我用的A100GPU要装高版本paddlepaddle-gpu==2.2.0版本，安装命令为：pip3 install paddlepaddle-gpu==2.2.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html，对应版本网站为https://www.paddlepaddle.org.cn/whl/mkl/stable.html

**Comment by forestSKYwind** [comment]
您好， 请问如何根据自己的gpu型号算力判断应该安装哪个版本呢？ 

我是M40 (idx: 0) + 一张亮机卡 (idx: 1)，
M40算力5.2，安装cuda 11.2，cudnn8.7，paddle 2.4.1.post112

使用paddle.utils.run_check()显示在0号卡上work well, 双卡即报错: PaddlePaddle meets some problem with 2 GPUs.

我判断可能是第二张甜品卡不行，修改了tool/program.py中的代码，令use_gpu=True时只设置device为gpu:0，但运行gpu训练时仍报错 cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

请问这应该怎么解决呢？
是M40对应的paddle版本仍不对，还是需要在其他地方设置device？
