### ISSUE TITLE
对多张图片连续识别时程序异常卡死并退出

### ISSUE THREAD

**Issue by Qinbf** [PaddlePaddle/PaddleOCR#5099]
电脑环境windows10
paddleocr版本2.3.0.2
paddlepaddle版本2.2.1
python版本3.8
程序：
```python
for i,img in enumerate(os.listdir(vincode_path)):
    img_path = os.path.join(vincode_path,img)
    print(i,len(os.listdir(vincode_path)))
    result = ocr.ocr(img_path,rec=rec_flag,cls=False)
```

问题描述：
我收集了1000张图片用for循环进行连续识别，程序很简单，没什么特别的。出现的问题有两种情况：
1.程序运行到一半会无缘无故卡死并退出，并且卡死的位置具有随机性，每次运行程序卡死位置可能都不同，偶尔也可以全部检测完毕。
退出信息为：
exited with code=3221225477 
2.程序运行到一半会无缘无故卡住但不退出。没有错误信息，并且卡住的位子具有随机性，每次卡住的位置不同，偶尔也可能不会卡住全部检测完毕。

补充说明：
1.通过vscode调试工具并不能找到原因，因为程序没有报错。
2.我给整段程序都加上了try except异常处理，程序依然会卡住或卡死，并且没有异常信息输出。
3.经过print调试大法发现程序是在ocr.ocr也就是识别的的步骤出现的问题，再具体一点就是执行predict_system.py中的rec_res, elapse = self.text_recognizer(img_crop_list)这句代码被卡死，进一步研究是predict_rec.py的370行代码self.predictor.run()被卡死。应该是paddle的问题，不过不知道是什么问题。

**Comment by littletomatodonkey** [comment]
直接在终端中调试看下呢？可能和vscode的环境有关

**Comment by Qinbf** [comment]
> 

终端运行一样会在随机位置卡死

**Comment by Adarine99** [comment]
遇到了同样的问题，请问解决了吗》设置不同的batch size就会在不同的地方卡住

**Comment by jcyfootballer** [comment]
有解决方案吗
