### ISSUE TITLE
使用rec_r34_vd_none_bilstm_ctc.yml配置文件，加了对应的预训练模型。训练的时候有大量的The shape of model params mismatch的日志信息。

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#5102]
请问，为什么会这样，应该怎么样修改，对训练出来的模型精度有很大影响吗
![image](https://user-images.githubusercontent.com/77281977/147539289-856f6516-fcac-4886-8989-126c2459ad74.png)

**Comment by zhangyingying520** [comment]
> 请问，为什么会这样，应该怎么样修改，对训练出来的模型精度有很大影响吗 ![image](https://user-images.githubusercontent.com/77281977/147539289-856f6516-fcac-4886-8989-126c2459ad74.png)

我没用这个配置文件用了这个模型rec_mv3_none_bilstm_ctc_v2.0_train出现了这种问题

**Comment by andyjpaddle** [comment]
可以先修改这个地方的代码：https://github.com/PaddlePaddle/PaddleOCR/blob/a67a6fa382cbf55aff12154d0fd3635c3a980b07/ppocr/utils/save_load.py#L114
如下：
```
 for k1 in state_dict.keys():
    if list(state_dict[k1].shape) == list(params[k1].shape):
        new_state_dict[k1] = params[k1]
    else:
        logger.warning(
            "The shape of model params {} {} not matched with loaded params {} {} !".
            format(k1, state_dict[k1].shape, k1, params[k1].shape))
```
