### ISSUE TITLE
import paddleocr失败，显示cannot import name 'LayoutXLMModel' from 'paddlenlp.transformers'

### ISSUE THREAD

**Issue by yjduan** [PaddlePaddle/PaddleOCR#5103]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：虚拟机aistudio
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：from paddleocr import PaddleOCR
- 完整报错/Complete Error Message：
---------------------------------------------------------------------------ImportError                               Traceback (most recent call last)/tmp/ipykernel_1737/2106133291.py in <module>
      1 # 1. 从paddleocr中import PaddleOCR类
----> 2 import paddleocr
      3 # from paddleocr import PaddleOCR
      4 import numpy as np
      5 import cv2
~/PaddleOCR/paddleocr.py in <module>
     35 from tools.infer.utility import draw_ocr, str2bool, check_gpu
     36 from ppstructure.utility import init_args, draw_structure_result
---> 37 from ppstructure.predict_system import OCRSystem, save_structure_res
     38 
     39 __all__ = [
~/PaddleOCR/ppstructure/predict_system.py in <module>
     31 from tools.infer.predict_system import TextSystem
     32 from ppstructure.table.predict_table import TableSystem, to_excel
---> 33 from ppstructure.vqa.infer_ser_e2e import SerPredictor, draw_ser_results
     34 from ppstructure.utility import parse_args, draw_structure_result
     35 
~/PaddleOCR/ppstructure/vqa/infer_ser_e2e.py in <module>
     26 
     27 import paddle
---> 28 from paddlenlp.transformers import LayoutXLMModel, LayoutXLMTokenizer, LayoutXLMForTokenClassification
     29 from paddlenlp.transformers import LayoutLMModel, LayoutLMTokenizer, LayoutLMForTokenClassification
     30 
ImportError: cannot import name 'LayoutXLMModel' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)

**Comment by Aquish-Lee** [comment]
升级paddlenlp并重启环境
pip install paddlenlp==2.2.1
