### ISSUE TITLE
从哪里下载v2.3版本的模型文件，能否给个链接

### ISSUE THREAD

**Issue by git3210** [PaddlePaddle/PaddleOCR#5104]
从哪里下载v2.3版本的模型文件，能否给个链接
模型链接中发现都是v2.0对应的模型，v2.3版本介绍比v2.0速度提升220%，这个是sever版本的还是mobile版本的？

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th
