### ISSUE TITLE
paddle的OCR模型对于灰色背景的黑字识别不到

### ISSUE THREAD

**Issue by gaogao-glj** [PaddlePaddle/PaddleOCR#5105]
你好，我在用paddle的OCR模型发现对于灰色背景的黑字识别不到的情况比较多，请问对这种情况有什么好的解决思路吗？谢谢~

**Comment by zhangyingying520** [comment]
可以根据自己的使用场景，创建适合自己使用场景的数据集，然后在官方提供的预训练模型进行微调
