### ISSUE TITLE
这个报错有人知道为什么吗

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#5107]
![image](https://user-images.githubusercontent.com/77281977/147550675-be1c33ea-8826-497f-a888-94f5fc9e8e7f.png)

![image](https://user-images.githubusercontent.com/77281977/147550617-10196008-f583-43f6-89f4-c14bd68380f5.png)

**Comment by tink2123** [comment]
请问配置文件或者代码做了什么修改呢？ 看起来是计算loss的时候，标签和预测结果shape没有对齐

**Comment by gutao0315** [comment]
release2.3版本的代码，用的rec文件夹下rec_mv3_tps_bilstm_att.yml配置文件加了预训练模型，自己的字典，其他没动呀
![image](https://user-images.githubusercontent.com/77281977/147719772-44a59920-698c-4ceb-811f-704401aa3750.png)

**Comment by gutao0315** [comment]
> 请问配置文件或者代码做了什么修改呢？ 看起来是计算loss的时候，标签和预测结果shape没有对齐
就用的rec_mv3_tps_bilstm_att.yml配置文件，加了预训练模型和自己的字典，其他没改动啊，代码是release2.3的代码
![image](https://user-images.githubusercontent.com/77281977/147719833-f2343e62-018c-4c67-aa84-c8beb49fbf3b.png)
