### ISSUE TITLE
训练好的paddleocr模型转成paddlelite .nb模型后精度下降

### ISSUE THREAD

**Issue by Fenghaze** [PaddlePaddle/PaddleOCR#5108]
- 系统环境：win10、android

- 版本号：release/2.3

- 模型转换代码：
from paddlelite.lite import *
import os
model_path = './rec/rec_en_number_lite_3w_pretrained/inference/'
opt=Opt()
opt.set_model_file(os.path.join(model_path, "inference.pdmodel"))
opt.set_param_file(os.path.join(model_path, "inference.pdiparams"))
opt.set_valid_places("arm")
opt.set_model_type("naive_buffer")
opt.set_optimize_out(os.path.join(model_path, "best_rec_opt"))
opt.run()
print('load success')

- paddleocr的预测效果：
![4106264243,3607704132](https://user-images.githubusercontent.com/40448037/147550495-ecffa8b7-8fe3-43dc-b6ba-44dc96101a39.jpg)

- paddlelite的预测效果：
![Uploading P8P%0E43PUQSKAF39YK~QZV.png…]()

**Comment by littletomatodonkey** [comment]
图片好像没有上传上来，另外就是看下预处理这块的结果完全相同吗？

**Comment by Fenghaze** [comment]
> 图片好像没有上传上来，另外就是看下预处理这块的结果完全相同吗？
![P8P%0E43PUQSKAF39YK~QZV](https://user-images.githubusercontent.com/40448037/147728490-9afb8165-50ea-4c4f-90f5-767cd1a945da.png)

这个是手机demo的预测结果，检测框基本都能检测出来，就是识别这一步有问题，感觉不是预处理的问题

**Comment by huangwenbiao** [comment]
你好，请问解决了吗？我也是遇到了。
