### ISSUE TITLE
VQA任务下的数据标注工具

### ISSUE THREAD

**Issue by sz-lcw** [PaddlePaddle/PaddleOCR#5109]
请问，有没有VQA任务下的，支持语义实体识别 (Semantic Entity Recognition, SER) 以及关系抽取 (Relation Extraction, RE) 任务的标注工具？或者可以标注如XFUND类数据的标注工具？感谢！

**Comment by littletomatodonkey** [comment]
ocr repo中目前没有这样的标注工具，建议通过代码将标注转换成需要的格式

**Comment by Eric-Zhang1990** [comment]
@littletomatodonkey  请问有没有转换代码呢？有的话，是什么格式转换成XFUN数据格式呢？谢谢
@sz-lcw  请问你那边有转换吗？有的话怎么做的呢？谢谢

**Comment by sheltonsuen** [comment]
Hello, @Eric-Zhang1990 @sz-lcw 你们现在标注 VQA 任务下的数据有没有什么好的工具推荐？

**Comment by gg22mm** [comment]
真是个头大的问题，正在看这方面的...   ~~

**Comment by sheltonsuen** [comment]
> 真是个头大的问题，正在看这方面的... ~~

你可以用 PaddleLabel 在 kie 模式下启动就可以标了， --kie，

**Comment by marsaliens** [comment]
> > 真是个头大的问题，正在看这方面的... ~~
> 
> 你可以用 PaddleLabel 在 kie 模式下启动就可以标了， --kie，

启动kie模式后，怎么标注出linking[]那种效果呢

**Comment by Unlicensed-driver-ljx** [comment]
这个有解决吗，最好有大哥能出一个这样的教程获取xfund数据
