### ISSUE TITLE
DBNet 概率图、阈值图生成问题求答疑

### ISSUE THREAD

**Issue by Aquish-Lee** [PaddlePaddle/PaddleOCR#5110]
在学习DBHead模块时，发现FPN输出的特征融合图F，经过的binarize head 和thresh head的模块结构是相同的:

（F -> 3x3 Conv2D-> BN+Relu -> 2x2 Conv2DTranspose -> BN+Relu -> 2x2 Conv2DTranspose）如下图

![图片](https://user-images.githubusercontent.com/51768704/147555044-39df6b9c-6fb0-465f-a471-34cffe8acdfb.png)

求教：
1、为什么相同的网络模块作用于F，产生的1x1x640x640的特征图，可以被当做不同的概率图和阈值图看待？
2、1的问题能不能这样理解：对于特征提取来说，广义来看都是相同尺度的特征图，但加上不同的监督信号后（GT生成的概率监督信号和阈值监督信号），就能在训练过程中学习到不同的权重参数，从而生成的特征逐渐近似概率图和阈值图？

**Comment by littletomatodonkey** [comment]
1. 他们不是相同的模块，只是模块的结构是相同的，他们的参数并不共享
