### ISSUE TITLE
运行文档「基于CTC损失的识别模型推理」里的CRNN-CTC模型出错

### ISSUE THREAD

**Issue by shentanyue** [PaddlePaddle/PaddleOCR#5111]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04 amd64
- 版本号/Version：Paddle： 2.1.3 PaddleOCR：release/2.3 问题相关组件/Related components：
- 运行指令/Command Code：
-
按下列文档进行操作，模型是文档里的。
https://github.com/PaddlePaddle/PaddleOCR/blob/95c670faf6cf4551c841764cde43a4f4d9d5e634/doc/doc_ch/inference.md#%E5%9F%BA%E4%BA%8ECTC%E6%8D%9F%E5%A4%B1%E7%9A%84%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86

![image](https://user-images.githubusercontent.com/34421038/147558001-5bd7458a-d1e6-4b2f-bd0f-48694ddffe66.png)

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/34421038/147557923-f43964d8-85ae-40d7-b561-df175879d66c.png)

**Comment by littletomatodonkey** [comment]
使用下面的命令导出模型看下哈，把pretrained_model修改为checkpoints，目前识别模型使用pretrained_model加载模型还有点问题，我们正在修复中，感谢反馈~

```python
python3 tools/export_model.py -c configs/rec/rec_r34_vd_none_bilstm_ctc.yml -o Global.checkpoints=./rec_r34_vd_none_bilstm_ctc_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/rec_crnn
```

**Comment by shentanyue** [comment]
可以了。thanks
