### ISSUE TITLE
铁铁们，像我图中的大字应该怎么标注才比较好，请指教

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#5114]
第一种方法
![image](https://user-images.githubusercontent.com/77281977/147620532-11535549-3d59-475c-a5d5-0ff6abb10716.png)
第二种方法
![image](https://user-images.githubusercontent.com/77281977/147620639-b860a3b4-edcc-4310-a465-67581f5a889b.png)
哪个比较好

**Comment by zhangyingying520** [comment]
看你想怎么识别了，最终想得到什么样的结果了，如果想单个字符输出，那就第二种，如果想字符串，那就第一种

**Comment by guoge6** [comment]
大佬带带我！

**Comment by MissPenguin** [comment]
二楼说的对

**Comment by gutao0315** [comment]
> 看你想怎么识别了，最终想得到什么样的结果了，如果想单个字符输出，那就第二种，如果想字符串，那就第一种
小弟愚见，是不是第二种标注方法大字的识别准确率会高一些

**Comment by MissPenguin** [comment]
> > 看你想怎么识别了，最终想得到什么样的结果了，如果想单个字符输出，那就第二种，如果想字符串，那就第一种
> > 小弟愚见，是不是第二种标注方法大字的识别准确率会高一些

如果你都是这种比较大的字母，是可以单字标注，用目标检测的方法来做的。当然用行标注也不一定差，没有对比过。
