### ISSUE TITLE
Cannot detect numerals sideways

### ISSUE THREAD

**Issue by Julian785** [PaddlePaddle/PaddleOCR#5115]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：jupyter notebook
- 版本号/Version：Paddle：  PaddleOCR：2.0.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
I have trouble detecting the numbers sideways, does anyone know what is the issue?
![detectSideways](https://user-images.githubusercontent.com/96805578/147628728-b92a69a8-ae51-4279-aac7-9e644d7588f1.jpg)

**Comment by MissPenguin** [comment]
You'd better add more vertical or inverted text image in training  for fine tuning, including text detection and recognition.
