### ISSUE TITLE
c++版本的预测为什么比python的更慢

### ISSUE THREAD

**Issue by Ray8716397** [PaddlePaddle/PaddleOCR#5116]
我试着编译运行deploy/cpp_infer里的demo,结果ocr的检测和识别加起来的速度好像还比python版本慢一点点, 请问用gpu跑预测的话python和c++性能区别大吗?

还有cpp的demo在连续预测到大概第6张还是第8张图片的时候出现了,malloc(): memory corruption

**Comment by guoge6** [comment]
什么情况？

**Comment by MissPenguin** [comment]
python和c++的预测命令可以贴一下吗，看看你的参数怎么配的。另外c++预测报错是稳定复现吗，是否方便提供下测试图片呢

**Comment by Ray8716397** [comment]
> python和c++的预测命令可以贴一下吗，看看你的参数怎么配的。另外c++预测报错是稳定复现吗，是否方便提供下测试图片呢

参数没有改就是默认的,c++预测报错是稳定复现的

**Comment by Ray8716397** [comment]
> python和c++的预测命令可以贴一下吗，看看你的参数怎么配的。另外c++预测报错是稳定复现吗，是否方便提供下测试图片呢

c++的参数
DEFINE_bool(use_gpu, true, "Infering with GPU or CPU.");
DEFINE_int32(gpu_id, 0, "Device id of GPU to execute.");
DEFINE_int32(gpu_mem, 4000, "GPU id when infering with GPU.");
DEFINE_int32(cpu_threads, 8, "Num of threads with CPU.");
DEFINE_bool(enable_mkldnn, false, "Whether use mkldnn with CPU.");
DEFINE_bool(use_tensorrt, false, "Whether use tensorrt.");
DEFINE_string(precision, "fp32", "Precision be one of fp32/fp16/int8");
DEFINE_bool(benchmark, false, "Whether use benchmark.");
DEFINE_string(save_log_path, "./log_output/", "Save benchmark log path.");
// detection related
DEFINE_string(image_dir, "", "Dir of input image.");
DEFINE_string(det_model_dir, "", "Path of det inference model.");
DEFINE_int32(max_side_len, 960, "max_side_len of input image.");
DEFINE_double(det_db_thresh, 0.3, "Threshold of det_db_thresh.");
DEFINE_double(det_db_box_thresh, 0.5, "Threshold of det_db_box_thresh.");
DEFINE_double(det_db_unclip_ratio, 1.6, "Threshold of det_db_unclip_ratio.");
DEFINE_bool(use_polygon_score, false, "Whether use polygon score.");
DEFINE_bool(visualize, true, "Whether show the detection results.");
// classification related
DEFINE_bool(use_angle_cls, false, "Whether use use_angle_cls.");
DEFINE_string(cls_model_dir, "", "Path of cls inference model.");
DEFINE_double(cls_thresh, 0.9, "Threshold of cls_thresh.");
// recognition related
DEFINE_string(rec_model_dir, "", "Path of rec inference model.");
DEFINE_int32(rec_batch_num, 6, "rec_batch_num.");
DEFINE_string(char_list_file, "/home/ray/Workspace/project/ocr/github/gso_server/lib/ocr/ppocr/utils/dict/japan_dict_guiju_del.txt", "Path of dictionary.");

python的参数:
cfg = Config()
    cfg.use_gpu = True
    cfg.use_tensorrt = False
    # params for text detector
    cfg.det_algorithm = "DB"
    cfg.det_model_dir = config['ocr']['model']['jp']['det_model_dir']
    cfg.det_limit_side_len = 960
    cfg.det_limit_type = 'max'

    # DB parmas
    cfg.det_db_thresh = 0.3
    cfg.det_db_box_thresh = 0.5
    cfg.det_db_unclip_ratio = 1.6
    cfg.use_dilation = False
    cfg.det_db_score_mode = "fast"

    # EAST parmas
    cfg.det_east_score_thresh = 0.8
    cfg.det_east_cover_thresh = 0.1
    cfg.det_east_nms_thresh = 0.2

    # params for text recognizer
    cfg.rec_algorithm = "CRNN"
    cfg.rec_model_dir = config['ocr']['model']['jp']['rec_model_dir']
    cfg.rec_image_shape = "3, 32, 320"
    cfg.rec_char_type = 'japan'
    cfg.rec_batch_num = 30
    cfg.max_text_length = 25

    cfg.rec_char_dict_path = config['ocr']['model']['jp']['rec_char_dict_path']
    cfg.use_space_char = True

    # params for text classifier
    cfg.use_angle_cls = False
    cfg.cls_model_dir = "./model/ch_ppocr_mobile_v2.0_cls_infer/"
    cfg.cls_image_shape = "3, 48, 192"
    cfg.label_list = ['0', '180']
    cfg.cls_batch_num = 30
    cfg.cls_thresh = 0.9

    cfg.use_pdserving = False
    cfg.use_tensorrt = False
    cfg.use_mp = True
    cfg.drop_score = 0.5

**Comment by MissPenguin** [comment]
把你的预测命令贴一下吧，再提供下测试图像，我们尝试复现下

**Comment by BruceHan98** [comment]
同样，C++预测时稳定出现`malloc(): memory corruption Aborted (core dumped)` 的问题。
下面是配置：
```c++
DEFINE_bool(use_gpu, false, "Infering with GPU or CPU.");
DEFINE_int32(gpu_id, 0, "Device id of GPU to execute.");
DEFINE_int32(gpu_mem, 4000, "GPU id when infering with GPU.");
DEFINE_int32(cpu_threads, 8, "Num of threads with CPU.");
DEFINE_bool(enable_mkldnn, false, "Whether use mkldnn with CPU.");
DEFINE_bool(use_tensorrt, false, "Whether use tensorrt.");
DEFINE_string(precision, "fp32", "Precision be one of fp32/fp16/int8");
DEFINE_bool(benchmark, false, "Whether use benchmark.");
DEFINE_string(save_log_path, "./log_output/", "Save benchmark log path.");
// detection related
DEFINE_string(image_dir, "", "Dir of input image.");
DEFINE_string(det_model_dir, "./inference/det_db/", "Path of det inference model.");
DEFINE_int32(max_side_len, 960, "max_side_len of input image.");
DEFINE_double(det_db_thresh, 0.3, "Threshold of det_db_thresh.");
DEFINE_double(det_db_box_thresh, 0.5, "Threshold of det_db_box_thresh.");
DEFINE_double(det_db_unclip_ratio, 1.6, "Threshold of det_db_unclip_ratio.");
DEFINE_bool(use_polygon_score, false, "Whether use polygon score.");
DEFINE_bool(visualize, true, "Whether show the detection results.");
// classification related
DEFINE_bool(use_angle_cls, true, "Whether use use_angle_cls.");
DEFINE_string(cls_model_dir, "./inference/cls/", "Path of cls inference model.");
DEFINE_double(cls_thresh, 0.9, "Threshold of cls_thresh.");
// recognition related
DEFINE_string(rec_model_dir, "./inference/rec_crnn/", "Path of rec inference model.");
DEFINE_int32(rec_batch_num, 6, "rec_batch_num.");
DEFINE_string(char_list_file, "./ppocr_keys_v1.txt", "Path of dictionary.");
```
预测命令为 ./build/ppocr system --image_dir imgs
图像是 `PaddleOCR/doc/imgs` 下的所有图像。

**Comment by Ray8716397** [comment]
> 把你的预测命令贴一下吧，再提供下测试图像，我们尝试复现下
好的

python tools/infer/predict_system.py

./ppocr system --det_model_dir=det_model_path     --rec_model_dir=rec_model_path --image_dir=imgs_path

![test2](https://user-images.githubusercontent.com/45814273/147798155-e14f9e50-0b5f-43eb-a455-df112b238d81.jpeg)
![test4](https://user-images.githubusercontent.com/45814
![test1](https://user-images.githubusercontent.com/45814273/147798168-aa9d0609-1678-47bd-8e06-9fe6664749a5.jpeg)
273/147798161-21b93f4b-ec0d-482e-a336-39c939e66e2a.jpeg)
![test3](https://user-images.githubusercontent.com/45814273/147798166-d6d859ad-fa94-451c-beb1-6e2bce3e39e6.jpeg)

**Comment by Zero2key** [comment]
rec run 的时候一样也遇到 `malloc(): memory corruption Aborted (core dumped)` 的问题，在linux环境里cpu gpu 都异常，但是在 macos 上正常

**Comment by zhexuepizi** [comment]
同样遇到了这个问题，某些图片rec的时候一直报这个错误，一开始以为是图片太大了，resize以后发现还是出现一样的错误

**Comment by TinyQi** [comment]
C++的demo识别好像是单图推理的，python的识别默认是batch推理的

**Comment by zwenyuan1** [comment]
c++ 推理图片时，个别图片出现malloc(): memory corruption 解决方法参考 https://github.com/PaddlePaddle/PaddleOCR/issues/5399
