### ISSUE TITLE
中文手写文本识别

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#5117]
算法： RARE，去除了TPS模块
训练数据： 文本行数据，水平文本。真实数据 + 生成数据。
代码分支：paddle-develop
配置文件：rec_r34_vd_tps_bilstm_attn.yml

请问 调节了输入的宽度以及行内最大文本数量后，预测头中 hidden_size, decoder_size, word_vector_dim有必要进行相应的调整么？
![企业微信截图_16407582713875](https://user-images.githubusercontent.com/61573829/147632613-d872b7f7-75f1-4600-ac2e-6f931184fa79.png)
![企业微信截图_1640758324409](https://user-images.githubusercontent.com/61573829/147632618-d468582f-e7e6-48b4-97d7-9c48fa7e2550.png)

还有就是，如果输入一个单字图片，例如“明”， 模型可能会识别出 "明天"， 关于这样的问题，可以提供以下解决的思路么？

**Comment by guoge6** [comment]
大佬带带我！

**Comment by Zhangts98** [comment]
> 大佬带带我！

我是萌新呀。

**Comment by guoge6** [comment]
方便留个联系方式吗？一起学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 中文手写文本识别 (Issue #5117)





  
大佬带带我！
  
我是萌新呀。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MissPenguin** [comment]
先不要改参数试试呢，再就是推荐用最新的release分支进行开发哈，您用的develop分支是比较老的静态图分支，已经不维护了
