### ISSUE TITLE
finetune OCR识别模型后，输出置信度大于1，介于10到22之间

### ISSUE THREAD

**Issue by nilin1998** [PaddlePaddle/PaddleOCR#5121]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

"/home/cmdadmin/aiwin/ocr/test_data4/99997.jpg": {
        "result": "1989年07月31日",
        "confidence": 21.59726333618164
    },- 
![image](https://user-images.githubusercontent.com/55744076/147650677-4d632d21-a955-4d94-8620-1d5b6faceeb8.png)

**Comment by MissPenguin** [comment]
识别结果是对的吗，finetune时对代码和配置做了哪些改动呢

**Comment by nilin1998** [comment]
> 
识别结果是对的，只有置信度不对，finetune时没有调整代码，只是改变了数据集，自己重新生成了数据集，所以配置文件改变了数据集路径还有迭代次数

**Comment by MissPenguin** [comment]
方便提供模型吗，我这边复现一下看看
