### ISSUE TITLE
CRNN_CTCLoss label encoding

### ISSUE THREAD

**Issue by Jack-lam1** [PaddlePaddle/PaddleOCR#5123]
想问一下，在计算CTCloss的时候，需要用到一个 labels 的参数，这个参数是一个[batch_size, max_label_length]的tensor。然后我debug的时候看到这个参数的具体值，是在dataloader的batch[1]里面得来的。但是我没找到在build_dataloader的时候，有做这个label encoding的操作呀，想问问能给一下在哪儿做了这个操作嘛？

**Comment by MissPenguin** [comment]
label encoding在这里做的：https://github.com/PaddlePaddle/PaddleOCR/blob/fb3d36ae64674dce8e725349d0045a22ce470964/ppocr/data/imaug/label_ops.py#L189

**Comment by Jack-lam1** [comment]
> label encoding在这里做的：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/fb3d36ae64674dce8e725349d0045a22ce470964/ppocr/data/imaug/label_ops.py#L189
