### ISSUE TITLE
PPOCRLabel Windows下独立运行版

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#5127]
请问PPOCRLabel 有Windows下独立运行版吗？PPOCRLabel.exe可以直接点击运行，进行标注工作。

**Comment by Jack-lam1** [comment]
有呀，官网不是有教程呀

**Comment by ronaldpan** [comment]
你说的是这个吗？https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/PPOCRLabel/README_ch.md
这个需要在python中运行。

**Comment by Evezerest** [comment]
目前官方没有，可以找找社区项目

**Comment by wangz1200** [comment]
告诉我邮箱，发给你。

**Comment by ronaldpan** [comment]
> 告诉我邮箱，发给你。
ronaldpan@163.com
谢谢。

**Comment by whalefa1I** [comment]
> 告诉我邮箱，发给你。

zhengs950412@163.com 可以发我一份吗爹
