### ISSUE TITLE
paddlehub server如何制定log输出位置

### ISSUE THREAD

**Issue by tzhang001** [PaddlePaddle/PaddleOCR#513]
我使用paddlehub部署，参照https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/serving_en.md， 想把log信息输出到指定文件里，是否有--log_path之类的选项可以指定呢？（不要用nohup启动重定向到文件哈）

**Comment by MissPenguin** [comment]
没有哈，目前只能通过重定向
