### ISSUE TITLE
layoutparser提供的版式分析模型不用用于finetune吗

### ISSUE THREAD

**Issue by ancybeibei** [PaddlePaddle/PaddleOCR#5134]
你好，版式分析开源了模型，源码使用的是create_predictor加载，我在使用paddle.jit.load加载的时候报错，请问开源的这个模型是无法加载用于finetune吗

**Comment by littletomatodonkey** [comment]
你好，这个模型目前不支持finetune哈，我们是导出为了inference模型了

**Comment by ancybeibei** [comment]
> 
了解啦，谢谢
