### ISSUE TITLE
想使用db训练点数不一致的弯曲文本，应该怎样修改代码呢？

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#514]
您好，我打算使用db训练mlt2019数据，但里面有许多点数不一致弯曲文本，我应该怎样修改代码成功训练数据呢？

**Comment by MissPenguin** [comment]
可以先把标注转换成相同点数，用一些类似插值的方法

**Comment by tyy2tyy** [comment]
您好，请问可以稍微具体一些吗？是改变我的标注文本，将它变成一样的点数，还是更改db_process.py。我在调试这个代码的时候发现，好像点数不一样也是可以往下进行的，但会突然停止，然后报错。但报错读入的那行数据好像也没有什么大问题。信息如下：
![0](https://user-images.githubusercontent.com/51456283/89982113-aee34300-dca7-11ea-8a22-9588d30b1f50.PNG)

![1](https://user-images.githubusercontent.com/51456283/89982001-7d6a7780-dca7-11ea-80d1-82ecee3b6211.PNG)
![2](https://user-images.githubusercontent.com/51456283/89982136-bc003200-dca7-11ea-883c-7645d9aa6aba.PNG)

**Comment by MissPenguin** [comment]
如果实际应用场景没什么弯曲文本，最好把训练数据的弯曲文本过滤掉，只用4点标注的训练数据，不同点数的数据训练调试起来可能比较麻烦。

**Comment by tyy2tyy** [comment]
好的，谢谢
