### ISSUE TITLE
训练识别模型

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#5140]
指令!python3 tools/train.py -c configs/rec/rec_icdar15_train.yml
预训练模型rec_mv3_none_bilstm_ctc_v2.0_train/best_accuracy
在aistudio上训练
报如下的警告
![image](https://user-images.githubusercontent.com/80818728/147803338-5e3d46c7-4a7f-4043-8621-49e393301234.png)
在本地服务器上没有出现这种问题

**Comment by andyjpaddle** [comment]
#5102
