### ISSUE TITLE
并发场景下识别batch推理环节resize_norm_img会使同一张图在不同batch里的处理结果不同导致识别结果会变化

### ISSUE THREAD

**Issue by KevinNuNu** [PaddlePaddle/PaddleOCR#5143]
https://github.com/PaddlePaddle/PaddleOCR/blob/a67a6fa382cbf55aff12154d0fd3635c3a980b07/tools/infer/predict_rec.py#L110
https://github.com/PaddlePaddle/PaddleOCR/blob/a67a6fa382cbf55aff12154d0fd3635c3a980b07/tools/infer/predict_rec.py#L117
https://github.com/PaddlePaddle/PaddleOCR/blob/a67a6fa382cbf55aff12154d0fd3635c3a980b07/tools/infer/predict_rec.py#L120

假设一张图片A的size是（3， 39， 305）
情况一：batch内的max_wh_ratio即为A的ratio
那么imgW = int(32*(305/39) = 250，即图片A在此batch内的resized_w = 250
情况二：batch内的A的ratio不是最大，假设max_wh_ratio=10
那么imgW = int(32*10) = 320, 此时图片A会执行resized_w = int(math.ceil(imgH * ratio)) ，图片在此batch内的resize_w = 251

在并发的场景下，同一张图片在不同的batch里可能会得到不同的处理结果，从而导致同一张图多次调用会出现不同的识别结果

解决方法：
将上述三行代码统一，统一都用math.ceil()上取整，或者都不用直接用int()取整

**Comment by andyjpaddle** [comment]
这个识别结果差别会很大吗？有具体实验的结果示例吗？

**Comment by KevinNuNu** [comment]
> 这个识别结果差别会很大吗？有具体实验的结果示例吗？

![image](https://user-images.githubusercontent.com/34083603/147809789-fe3384de-b02e-4855-b785-0fe9fa425f78.png)
上图是连着两次的调用，一次识别成L，一次识别成I（后处理成的1）

**Comment by KevinNuNu** [comment]
> 这个识别结果差别会很大吗？有具体实验的结果示例吗？

主要问题是同一张图输出会有不同识别结果返回这有点不合常理- -
