### ISSUE TITLE
运行predict_table.py报错list index out of range

### ISSUE THREAD

**Issue by Jiangyangya** [PaddlePaddle/PaddleOCR#5145]
代码没有改过，直接尝试运行了提供的命令，文件路径啥的都没问题，有几个问题也问过这个，但是解决方法不适用
Traceback (most recent call last):
  File "table/predict_table.py", line 221, in <module>
    main(args)
  File "table/predict_table.py", line 197, in main
    pred_html = text_sys(img)
  File "table/predict_table.py", line 88, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/bml/.storage/mnt/v-algorithm/org/jiangyang/PPOCRv2/PaddleOCR-release-2.4/tools/infer/predict_rec.py", line 368, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/bml/.storage/mnt/v-algorithm/org/jiangyang/PPOCRv2/PaddleOCR-release-2.4/ppocr/postprocess/rec_postprocess.py", line 98, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/bml/.storage/mnt/v-algorithm/org/jiangyang/PPOCRv2/PaddleOCR-release-2.4/ppocr/postprocess/rec_postprocess.py", line 69, in decode
    char_list.append(self.character[int(text_index[batch_idx][idx])])
IndexError: list index out of range

**Comment by andyjpaddle** [comment]
请提供一下详细运行命令，看一下字典是否和模型对应

**Comment by Jiangyangya** [comment]
python3 table/predict_table.py --det_model_dir=../model_file/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=../model_file/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=../model_file/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=/home/bml/storage/mnt/v-algorithm/org/jiangyang/PPOCRv2/PaddleOCR-release-2.4/data/ppocr_img/PMC3576793_00004.jpg --rec_char_dict_path=../../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --rec_char_dict_path=../ppocr/utils/dict/en_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../data/output/table1231

**Comment by Jiangyangya** [comment]
> 请提供一下详细运行命令，看一下字典是否和模型对应

python3 table/predict_table.py --det_model_dir=../model_file/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=../model_file/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=../model_file/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=/home/bml/storage/mnt/v-algorithm/org/jiangyang/PPOCRv2/PaddleOCR-release-2.4/data/ppocr_img/PMC3576793_00004.jpg --rec_char_dict_path=../../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --rec_char_dict_path=../ppocr/utils/dict/en_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../data/output/table1231

**Comment by WenmuZhou** [comment]
rec_char_dict_path=../../ppocr/utils/dict/table_dict.txt -- 这个删掉

**Comment by Jiangyangya** [comment]
> rec_char_dict_path=../../ppocr/utils/dict/table_dict.txt -- 这个删掉

删掉了仍然是这个报错..

**Comment by Jiangyangya** [comment]
> 请提供一下详细运行命令，看一下字典是否和模型对应

rec_result = self.postprocess_op(preds)这个报错，引用了一个ppocr/post_process下的build_post_process？我看这个文件夹下并没有这个py文件

**Comment by Jiangyangya** [comment]
> rec_char_dict_path=../../ppocr/utils/dict/table_dict.txt -- 这个删掉

解决了，删掉--rec_char_dict_path=../ppocr/utils/dict/en_dict.txt 就好了，快速开始得命令行给的有问题，可以改一下啦
