### ISSUE TITLE
字符缺陷检测，请教一下大神

### ISSUE THREAD

**Issue by 98SwordMan** [PaddlePaddle/PaddleOCR#5146]
![QQ图片20211231160732](https://user-images.githubusercontent.com/44767732/147811452-953a9536-c8e4-4151-9a37-55ee933e55ea.png)
PaddleOCR真的很不错，我在使用过程中即使字符有缺陷也能准确的识别出来，但是我有一个额外的逻辑，字符缺陷检测。
上图所示，字符"2"已经擦掉了一半还是能准确的识别出来，得分依然是0.99+，如果想做字符的缺陷检测有什么好的办法？请教一下大神

**Comment by andyjpaddle** [comment]
可以考虑标注一部分缺陷数据用目标检测方法进行训练，PaddleOCR这边目前还没有字符缺陷检测的算法
