### ISSUE TITLE
PPOCRLabel标注使用中文输入法异常

### ISSUE THREAD

**Issue by RangeKing** [PaddlePaddle/PaddleOCR#5148]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle： 2.2.1 PaddleOCR：2.4 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py
- 完整报错/Complete Error Message：自动标注后需要修改部分字符，双击标签开始编辑之后，使用中文输入法（测试了Win10自带输入法和搜狗输入法均存在问题）后仅输入一个字符就退出编辑模式。完整示例如下图，左上角为键盘输入，退格删除之后输入了4个字符“shan”。实际上输入“s”之后就已经退出编辑模式，然后“a”触发快捷操作——回到上一张图片。问题不是每次标注时都出现，但是出现概率很高。
  
![PPOCRLabel_bug1](https://user-images.githubusercontent.com/27466624/147844262-c4141ced-80c1-437e-b4b0-6c2a224e981a.gif)

**Comment by Evezerest** [comment]
你好，这个问题我们在开发过程中遇到过，主要是输入法自动夺走了当前应用程序，导致退出了编辑模式，使用自带输入法没有出现这个问题。后续我们会推出保留原始方案的功能。

**Comment by rexzhengzhihong** [comment]
请问有解决了吗
