### ISSUE TITLE
执行生成opt 报错，命令./lite/tools/build.sh build_optimize_tool

### ISSUE THREAD

**Issue by zhangyaobo** [PaddlePaddle/PaddleOCR#515]
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/descriptor.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/any.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/api.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/duration.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/empty.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/field_mask.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/source_context.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/struct.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/timestamp.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/type.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/wrappers.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/include/google/protobuf/compiler/plugin.proto
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-targets.cmake
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-targets-noconfig.cmake
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config-version.cmake
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config.cmake
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-options.cmake
-- Up-to-date: /opt/tools/paddle-lite/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-module.cmake
[  5%] Completed 'extern_protobuf'
[  5%] Built target extern_protobuf
CMakeFiles/Makefile2:21233: recipe for target 'lite/api/CMakeFiles/opt.dir/rule' failed
make[1]: *** [lite/api/CMakeFiles/opt.dir/rule] Error 2
Makefile:3407: recipe for target 'opt' failed
make: *** [opt] Error 2

**Comment by LDOUBLEV** [comment]
1. 先准备好交叉编译环境：
![image](https://user-images.githubusercontent.com/26592129/90089985-6a15e580-dd55-11ea-8f17-dc4a70e6587b.png)

2. 使用Paddle_lite的develop分支编译

**Comment by zhangyaobo** [comment]
编译出来的没有python安装包啊

**Comment by zhanqizhu111** [comment]
请问你这个问题最后如何解决的
