### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Soebb** [PaddlePaddle/PaddleOCR#5152]
system = windows 10 64bit
python = 3.7
paddleocr = 2.3.0.2
paddlepaddle = 2.2.1

![-5949267984524621542_121](https://user-images.githubusercontent.com/87156166/147879412-579cbc74-5162-40ec-b534-0efd74a5b5c6.jpg)

**Comment by WenmuZhou** [comment]
具体一点吧

**Comment by Soebb** [comment]
Check my opened issue in this [project](https://github.com/oliverfei/videocr-PaddleOCR/issues/6).
I think its paddlepaddle error.
Anyway it fixed by installing paddlepaddle 2.0.6 but i hope you fix this in the upcoming versions.
