### ISSUE TITLE
车牌较小识别不到的问题

### ISSUE THREAD

**Issue by HexPang** [PaddlePaddle/PaddleOCR#5153]
项目地址：[https://aistudio.baidu.com/aistudio/projectdetail/1603924](https://aistudio.baidu.com/aistudio/projectdetail/1603924)

操作步骤：下载训练好的模型到本地进行测试

代码：
```python
from paddleocr import PaddleOCR

vlpr = PaddleOCR(
    det_model_dir='inference/det_vlpr',
    rec_model_dir='inference/ch_ppocr_server_v2.0_rec_infer'
)
img_path = 'test0.jpg'
display(Image(img_path))
vlpr.ocr(img_path)
```

![250](https://user-images.githubusercontent.com/1132194/147889552-0d5ff03b-d3f1-46f6-9fbc-e0257534e339.jpeg)
![11111](https://user-images.githubusercontent.com/1132194/147889589-05247e20-a752-4d74-a359-d5c4b4895fd8.png)
这两张图都检测不出来。但是AIStudio上可以检测出来。

**Comment by littletomatodonkey** [comment]
调大det max length参数看下，可能是图像被resize的太小了

**Comment by HexPang** [comment]
> 调大det max length参数看下，可能是图像被resize的太小了

果然是这个问题,感谢.

**Comment by pcb9382** [comment]
车牌车牌识别开源项目可以看看这个：https://github.com/pcb9382/PlateRecognition
