### ISSUE TITLE
[Feature request] Add StrucText to ppstructure vqa

### ISSUE THREAD

**Issue by cpwan** [PaddlePaddle/PaddleOCR#5154]
Hi there, I notice that you added the layoutLM series recently. Can you add also [StrucText](https://github.com/PaddlePaddle/VIMER/tree/main/StrucTexT)? It has very competitive performance.

Here is the reported performance on the Chinese section of XFUND.
|Model|Task| f1 score|
|--|--|--|
|LayoutXLM|RE|0.7113|
|StrucText| RE| 0.8681|
|LayoutXLM|SER|0.9056|
|StrucText| SER| 0.9930|

**Comment by littletomatodonkey** [comment]
thanks for your attention，structext is already open-sourced in another repo，

https://github.com/PaddlePaddle/VIMER/tree/main/StrucTexT

**Comment by aishangmaxiaoming** [comment]
> thanks for your attention，structext is already open-sourced in another repo，
> 
> https://github.com/PaddlePaddle/VIMER/tree/main/StrucTexT

但是没有训练代码。咱们有计划加上训练流程吗

**Comment by littletomatodonkey** [comment]
> > thanks for your attention，structext is already open-sourced in another repo，
> > https://github.com/PaddlePaddle/VIMER/tree/main/StrucTexT
> 
> 但是没有训练代码。咱们有计划加上训练流程吗

短期内没有这个计划哈，或者您可以关注着，有更新的话我们会随时在首页说明的

**Comment by Eric-Zhang1990** [comment]
> thanks for your attention，structext is already open-sourced in another repo，
> 
> https://github.com/PaddlePaddle/VIMER/tree/main/StrucTexT

@littletomatodonkey  请问StrucTexT单张图片的预测代码有吗？谢谢
