### ISSUE TITLE
DB用自己的数据集训练1000个epoch，主干网络使用resnet18效果可以但resnet50效果很差请问什么原因

### ISSUE THREAD

**Issue by 20141602310043** [PaddlePaddle/PaddleOCR#5156]
票据相关的数据集，其中训练集1000张，测试集500张
在AI studio的BML Codelab上训练，paddle版本是2.0.2，训练批次是1000个epoch
使用resnet18时，best epoch是980，hmean：0.89，precision：0.85，recall：0.93
使用resnet50时，best epoch是893，hmean：0.44，precision：0.46，recall：0.43
请问为什么resnet从18换成50后检测效果会差这么多

**Comment by ziyaxuanyi** [comment]
有可能过拟合了，看看训练集精度多少，我猜的

**Comment by GeryWolf** [comment]
> 票据相关的数据集，其中训练集1000张，测试集500张
> 在AI studio的BML Codelab上训练，paddle版本是2.0.2，训练批次是1000个epoch
> 使用resnet18时，best epoch是980，hmean：0.89，precision：0.85，recall：0.93
> 使用resnet50时，best epoch是893，hmean：0.44，precision：0.46，recall：0.43
> 请问为什么resnet从18换成50后检测效果会差这么

请问您能提供一份数据集吗？（我也是在做票据识别相关项目）

**Comment by MissPenguin** [comment]
> 票据相关的数据集，其中训练集1000张，测试集500张 在AI studio的BML Codelab上训练，paddle版本是2.0.2，训练批次是1000个epoch 使用resnet18时，best epoch是980，hmean：0.89，precision：0.85，recall：0.93 使用resnet50时，best epoch是893，hmean：0.44，precision：0.46，recall：0.43 请问为什么resnet从18换成50后检测效果会差这么多

用原始配置和icdar2015数据训练也是这种现象吗
