### ISSUE TITLE
关于部署使用GPU，支持并发

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#516]
最近在使用PaddleOCR尝试进行服务器端的部署hubserving，直观感觉并发访问显存应该是随着并发数目上涨的，但是现在发现部署的模型仅仅是在串行执行，显存并没有增加，维持在一个稳定量请问这是什么原因尼。

**Comment by MissPenguin** [comment]
在预测的时候还是一张一张执行的，所以占用显存情况跟最大（最耗显存）的图像相关，跟并发数无关
