### ISSUE TITLE
PaddleOCR 预测，文本识别相关问题

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/PaddleOCR#5160]
目的是想实现识别仪器仪表的数字，下载的移动端的demo 是摄像头拍摄到哪里，就可以识别到相关的字或者液晶显示屏上面的数字等，现在想实现：类似目标检测一样，通过infer --video-file加载摄像头rtsp流进行实时的识别，目前python3 tools/infer/predict_rec.py 只能实现针对图片的识别，并且只能识别普通文本文字，就是目录doc\imgs_words_en 中类似的图片文本，从图库中自己下载的一些液晶屏数字等均不能被识别到，效果很差，可能只识别到其中一个字，请教一下怎么实现？？

目前是下载的推理模型，不是自己训练的ch_ppocr_server_v2.0_rec_infer

**Comment by MissPenguin** [comment]
建议用液晶显示屏的数字构建训练集进行finetune，优化识别模型效果

**Comment by xiaofeixuan** [comment]
是需要自己定义一些数据集进行训练吗？不能使用公开的模型吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] PaddleOCR 预测，文本识别相关问题 (Issue #5160)





 
建议用液晶显示屏的数字构建训练集进行finetune，优化识别模型效果
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaofeixuan** [comment]
@MissPenguin 能预测视频流吗？跟目标检测那个的一样

**Comment by yjhtc007** [comment]
> 是需要自己定义一些数据集进行训练吗？不能使用公开的模型吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleOCR" ***@***.***&gt;; 发送时间:&nbsp;2022年1月4日(星期二) 晚上8:49 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] PaddleOCR 预测，文本识别相关问题 (Issue #5160) 建议用液晶显示屏的数字构建训练集进行finetune，优化识别模型效果 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以用公开的模型作为预训练模型，在自己的数据集上进行finetune
