### ISSUE TITLE
使用GPU进行预测时候，cuda初始化出错

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5168]
报错信息如下：
`OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:354)`
貌似是多线程的问题？应该怎么解决呢

**Comment by GivanTsai** [comment]
> 

nvidia驱动信息：NVIDIA-SMI 470.57.02 (V100)
cuda版本信息：CUDA Version 10.0.130

出错的地方：predictor = inference.create_predictor(config)
一定需要安装cudnn吗

**Comment by GivanTsai** [comment]
请问这个怎么解决呢
@LDOUBLEV

**Comment by iwanglei1** [comment]
我也遇到了同样的问题。

**Comment by jimmyflycv** [comment]
same issue here.
i config anything according offical guide.

**Comment by Lemonlcy** [comment]
我也遇到了同样的问题。不开多进程推理没问题，开了之后就没有办法找到cuda

**Comment by iwanglei1** [comment]
安装了一些库之后暂时能用了

**Comment by Lemonlcy** [comment]
> 安装了一些库之后暂时能用了


请问是哪些库呢？或者说新增什么库之后可以用多进程推理？
