### ISSUE TITLE
由于验证集验证时导致显卡内存占满，卡住不继续训练。

### ISSUE THREAD

**Issue by lx-rookie** [PaddlePaddle/PaddleOCR#517]
这是正常训练时候2分钟就可以验证完
![image](https://user-images.githubusercontent.com/54061448/89960873-b805ed00-dc72-11ea-940d-0eaa2c323dfd.png)

这是内存将满，卡在验证集的最后一只不动的
![image](https://user-images.githubusercontent.com/54061448/89960923-e08de700-dc72-11ea-9e8f-997ef9859d65.png)
![image](https://user-images.githubusercontent.com/54061448/89960931-e4216e00-dc72-11ea-96ef-0fc64cf17c58.png)
这种情况，我可以手动修改验证时使用的显卡吗。

**Comment by MissPenguin** [comment]
这个不太好修改，你可以先试试把test_batch_size_per_card或者num_workers改小点

**Comment by MissPenguin** [comment]
也可以试试修改reader_main.py第75行为 return paddle.reader.multiprocess_reader(readers, False, queue_size=200)
