### ISSUE TITLE
检测+识别的python版本的tensorrt的推理部分在哪里可以找到？可否给个链接地址，谢谢了

### ISSUE THREAD

**Issue by xuhui1994** [PaddlePaddle/PaddleOCR#5170]

**Comment by LDOUBLEV** [comment]
TRT预测时，开启use_tensorrt=True：
https://github.com/PaddlePaddle/PaddleOCR/blob/dbe527ea7264234c8d66e1958016e6776a91c458/tools/infer/utility.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37

**Comment by Auth0rM0rgan** [comment]
@LDOUBLEV, Does all the text recognition models support tensorRT or just CRNN?

Thanks!
