### ISSUE TITLE
DML双模型训练，梯度更新是单独进行还是一起进行的？？

### ISSUE THREAD

**Issue by TangDL** [PaddlePaddle/PaddleOCR#5172]
![image](https://user-images.githubusercontent.com/37130335/148194726-2579b801-bff2-4d97-937f-77702927e3a0.png)
论文里面是分别计算两个模型的loss，然后两个模型单独更新．有一个细节是，模型1计算完loss然后更新之后，模型2计算loss的时候，使用的是更新之前的模型1还是更新之后的模型1呢？

**Comment by LDOUBLEV** [comment]
PaddleOCR里DML训练是同时更新 两个模型的loss

**Comment by TangDL** [comment]
> PaddleOCR里DML训练是同时更新 两个模型的loss
感谢！
