### ISSUE TITLE
DB检测模型更换梯度下降方式

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5173]
![image](https://user-images.githubusercontent.com/87969070/148199010-c50b115e-3b31-42cd-b1c2-54605062d117.png)
请问一下，DB配置文件中并没有更换name的字段，我如果想换成Cosine应该在哪里进行修改呢？

**Comment by LDOUBLEV** [comment]
> 我如果想换成Cosine应该在哪里进行修改呢？

参考这里的配置
https://github.com/PaddlePaddle/PaddleOCR/blob/dbe527ea7264234c8d66e1958016e6776a91c458/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46

**Comment by 18362890185** [comment]
> > 我如果想换成Cosine应该在哪里进行修改呢？
> 
> 参考这里的配置 https://github.com/PaddlePaddle/PaddleOCR/blob/dbe527ea7264234c8d66e1958016e6776a91c458/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46

好的,谢谢您!
