### ISSUE TITLE
关于加载预训练模型报错

### ISSUE THREAD

**Issue by 18362890185** [PaddlePaddle/PaddleOCR#5177]
![image](https://user-images.githubusercontent.com/87969070/148320795-f62f3df0-5cd0-497c-ab4b-0b1dffc2b04a.png)
请问加载预训练模型错误，我将新版本的save_load.py形式改成旧版本的，训练报错，下图是我更改的部分，请问哪里出错了呢？
![image](https://user-images.githubusercontent.com/87969070/148320851-93e70afb-96ac-4081-b7ee-5ca349f88e97.png)

**Comment by andyjpaddle** [comment]
最新版已经修复了，请使用最新版代码
