### ISSUE TITLE
PPOCRLabel重新识别的bug

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5178]
我在使用PPOCRLabel进行标注的时候，自动标注后，调整了其中一个识别框的坐标然后重新识别，为什么其他框的识别结果也会发生变化呢

**Comment by Evezerest** [comment]
点击的是右上角重新识别吗？分支和版本是多少呢？

**Comment by GivanTsai** [comment]
应该是最新版本，我直接安装的，参照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/PPOCRLabel/README_ch.md这里，不是git clone

**Comment by GivanTsai** [comment]
> 点击的是右上角重新识别吗？分支和版本是多少呢？

这样是正常的吗

**Comment by GivanTsai** [comment]
而且稍微调整下框的坐标，就会对这个文本框的识别结果造成很大影响，是不是说明rec模型不够stable

**Comment by Evezerest** [comment]
可以提供一下图片，注意左下角的自动标注和右上角的重新识别，以及选定某些框之后点击右键的重新识别是不一样的

**Comment by GivanTsai** [comment]
> 可以提供一下图片，注意左下角的自动标注和右上角的重新识别，以及选定某些框之后点击右键的重新识别是不一样的

按请问第二个问题呢，我只是微微调了一下文本框坐标的一个小角，最后识别出的结果变化会很大
