### ISSUE TITLE
文本检测换成自己的数据没法训练

### ISSUE THREAD

**Issue by fengqiyuqingpingzhimo** [PaddlePaddle/PaddleOCR#518]
![0000005](https://user-images.githubusercontent.com/26477240/89967119-379bb800-dc83-11ea-9deb-ef10b0c6e6a2.png)
- 自己数据大概是绿框这种，四个点构成一个长方形
- 用dbnet 训练 total_loss一直是1 其他值也不变
```
2020-08-12 10:00:09,724-INFO: epoch: 1, iter: 18, 'lr': 0.001, 'total_loss': 1.0, 'loss_shrink_maps': 0.0, 'loss_threshold_maps': 0.0, 'loss_binary_maps': 1.0, time: 45.061
```
- 用east连日志都没有

**Comment by MissPenguin** [comment]
可能数数据格式有问题，label截图看一下？

**Comment by fengqiyuqingpingzhimo** [comment]
> 可能数数据格式有问题，label截图看一下？

![7](https://user-images.githubusercontent.com/26477240/89968688-0de49000-dc87-11ea-85bf-cb0af46decc6.png)
label的截图

**Comment by MissPenguin** [comment]
“###” 表示要被忽略的文本区域，所以你的数据都被跳过了，你换成其他任意字符或者就写个空的“”

**Comment by fengqiyuqingpingzhimo** [comment]
> “###” 表示要被忽略的文本区域，所以你的数据都被跳过了，你换成其他任意字符或者就写个空的“”

非常感谢
