### ISSUE TITLE
我不知道这是什么问题请官方解答一下

### ISSUE THREAD

**Issue by WXHJYC** [PaddlePaddle/PaddleOCR#5189]
![image](https://user-images.githubusercontent.com/37164406/148390301-d213d8f5-c740-4cf1-a363-0a17c961566f.png)
这个错误我确实看不懂了

**Comment by WXHJYC** [comment]
我要如何才会识别呢我根据文档使用python3  tools/test_hubserving.py http://127.0.0.1:8868/predict/ocr_system  /opt/imgs/shibie2.jpg 就报这个错误

**Comment by WXHJYC** [comment]
这个是linux环境，服务器已启动。单识别就报错

**Comment by andyjpaddle** [comment]
看错误是shape不匹配导致的，可否描述一下详细命令和做的修改？
