### ISSUE TITLE
en_dict.txt中是否缺少了一个字符？

### ISSUE THREAD

**Issue by MengQiDWangChao** [PaddlePaddle/PaddleOCR#5193]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

在使用官方提供的en_number_mobile_v2.0_rec模型进行识别时，给出的字典是en_dict.txt，但是调试时读入只有95个字符在加上ctc解码需要添加的blank字符也就只有96个字符，但是模型的输入是97的识别字符中有空格时无法正常跑，手动添加了一个字符可以正常跑，而且测试时也发现应该最后一个字符为空格，不知道具体是那个位置缺失了一个字符？

**Comment by andyjpaddle** [comment]
en_dict.txt 本身包含94个字符，CTC解码加上blank字符后是95个字符，你说的模型输入是97是什么意思呢？可否详细给出你的问题和代码？

**Comment by MengQiDWangChao** [comment]
以下是工程中提供的en_dict.txt
![image](https://user-images.githubusercontent.com/32353044/148484980-75027dd3-d09b-4d0b-90fe-8ccffff501c7.png)，一共是95个字符，CTC解码加上blank字符后是96个字符，而提供en_number_mobile_v2.0_rec模型输出的字符索引个数有97，从测试来看最后一个应该是空格，所以感觉这个给的字典少了一个字符，因为识别文字中有空格式程序会出现越界报错。
![image](https://user-images.githubusercontent.com/32353044/148485559-b0d0ad4c-97b3-4efd-af0a-f2e5f06556e1.png)

**Comment by andyjpaddle** [comment]
可以将配置文件中的`use_space_char`设置为`True`试试

**Comment by MengQiDWangChao** [comment]
你好，这个字典里面已经自带空格了，应该不是这个问题

**Comment by andyjpaddle** [comment]
能把你的详细报错给一下吗，包括完整运行指令，以及做了哪些修改

**Comment by MengQiDWangChao** [comment]
你好，这边没有做什么修改，就是把en_number_mobile_v2.0_rec识别模型下载下来，然后加载了en_dict.txt进行识别，但是没有use_space_char设置为True, 这时输出索引会有96，但是字典刚才说加上blank只有96个，所以会有越界报错。
![image](https://user-images.githubusercontent.com/32353044/148488366-aeb3b922-1867-4824-ba1d-bec05bd64667.png)
看这里的源码，像你说的加上use_space_char应该就可以运行的，现在有疑问的是原始字典已经有空格了，这个是为了兼容各个不同字典加空格一定要叫上吗？

**Comment by JinYuannn** [comment]
是少了一个，94行的en_dict.txt后面有一个空行，也就是95行，在输入一个空行变成96行就可以了。自动加上空白符就是97

**Comment by MengQiDWangChao** [comment]
👌



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月25日 17:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] en_dict.txt中是否缺少了一个字符？ (Issue #5193) |

是少了一个，94行的en_dict.txt后面有一个空行，也就是95行，在输入一个空行变成96行就可以了。自动加上空白符就是97
