### ISSUE TITLE
PaddleOCRv2 通用模型是使用了私有数据集吗？

### ISSUE THREAD

**Issue by Syencil** [PaddlePaddle/PaddleOCR#5195]
提供的通用det和rec模型是用开源+私有数据集吗？方便说一下用了哪些开源的，私有的数据体量多大不，目前用ppocr做出来的效果一直没有提供的权重效果好

**Comment by tink2123** [comment]
开源数据可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/datasets.md， 
私有数据体量不大，大多都是开源的公开数据
