### ISSUE TITLE
训练vqa模型 layoutxlm ，resume时无法下载该预训练模型，显示报错网址没有这个模型

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#5197]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/67897601/148482734-a50a714f-758e-4a93-b06f-ff93f2706eb4.png">

**Comment by WenmuZhou** [comment]
resume时，只需要给训练好的模型地址就可以了，不需要下载的，方便贴一下报错截图吗
