### ISSUE TITLE
关于关键信息提取算法SDMGR相关字符粘连问题

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#5199]
1、已使用SDMGR算法完成卡证相关数据集训练，出来的结果相当可以。感谢开源的大佬们。
2、其次是问题，之前也尝试过相关的关键信息提取算法，发现有个共通的一个问题。
假设目前有两个字段，key是姓名，value是张三。
在训练的过程中，将key和value分别标注为key_name，value_name两个实体，这两个实体分别有自己的points坐标位置以及文本标签。
在推理过程中，由于上游的OCR（PaddleOCR的EAST文本检测+CRNN文本识别等）识别的结果，导致key_name，value_name两个实体进入了一个文本框，最后通过SDMGR进行推理，出来的结果就是将这个长的文本框的类型识别成了others。
这种情况能否通过PaddleOCR上游识别任务有效的进行规避，或者只能通过KIE模型推理之后，再次对上游的PaddleOCR识别结果进行正则过滤来对KIE的结果进行补充？有没有通用的解决方案？

**Comment by yjhtc007** [comment]
我觉得再次进行正则过滤来补充是一种解决方案。还有就是提升文本检测模型的检测性能吧，加大训练数据量，同时针对检测不好的图片进行重点训练这样

**Comment by ziyuwzf** [comment]
> 我觉得再次进行正则过滤来补充是一种解决方案。还有就是提升文本检测模型的检测性能吧，加大训练数据量，同时针对检测不好的图片进行重点训练这样

检测这块的问题应该没办法覆盖所有情况，总是会有分开的文字会识别成一个文本框。
加正则过滤也是有风险的，意外情况会有很多。

**Comment by yjhtc007** [comment]
> > 我觉得再次进行正则过滤来补充是一种解决方案。还有就是提升文本检测模型的检测性能吧，加大训练数据量，同时针对检测不好的图片进行重点训练这样
> 
> 检测这块的问题应该没办法覆盖所有情况，总是会有分开的文字会识别成一个文本框。 加正则过滤也是有风险的，意外情况会有很多。

是的。。。

**Comment by jackiezzq** [comment]
> 1、已使用SDMGR算法完成卡证相关数据集训练，出来的结果相当可以。感谢开源的大佬们。 2、其次是问题，之前也尝试过相关的关键信息提取算法，发现有个共通的一个问题。 假设目前有两个字段，key是姓名，value是张三。 在训练的过程中，将key和value分别标注为key_name，value_name两个实体，这两个实体分别有自己的points坐标位置以及文本标签。 在推理过程中，由于上游的OCR（PaddleOCR的EAST文本检测+CRNN文本识别等）识别的结果，导致key_name，value_name两个实体进入了一个文本框，最后通过SDMGR进行推理，出来的结果就是将这个长的文本框的类型识别成了others。 这种情况能否通过PaddleOCR上游识别任务有效的进行规避，或者只能通过KIE模型推理之后，再次对上游的PaddleOCR识别结果进行正则过滤来对KIE的结果进行补充？有没有通用的解决方案？

卡证场景你训练了多少数据集？

**Comment by mookixiao** [comment]
> 

请问针对字段粘连楼主找到比较有效的解决方案了吗？
