### ISSUE TITLE
并行训练 cpu计算资源只用了一个核，可以用多核吗？

### ISSUE THREAD

**Issue by bnu-bily** [PaddlePaddle/PaddleOCR#5200]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 7.6 docker v20 8核 60G CPU
- 版本号/Version：Paddle：  2.2.1 PaddleOCR： 
- 运行指令/Command Code：python tools/train.py -c configs/det/det_mv3_db.yml
- 完整报错/Complete Error Message：没有报错，但是运算资源利用率不高，在dataload阶段能用到cpu8个核，但是在学习阶段只用了一个核，其他的计算资源浪费了；
![ff9459e60c6c7a583d3f0b8525e4f44](https://user-images.githubusercontent.com/8065474/148490349-6d7b4fac-b8cb-4d60-ab99-fd7a9ddb688a.png)
![00384453f881bd91518887bf4dd8c25](https://user-images.githubusercontent.com/8065474/148490372-35ce9de1-fad8-4334-beb4-13dda43d3a55.png)

**Comment by zero20121222** [comment]
这个问题没人解答吗？

**Comment by bnu-bily** [comment]
> 这个问题没人解答吗？
没有 应该是不支持的，目前还看不到解决方法
