### ISSUE TITLE
同一张图片首次推理和后续推理结果不一致

### ISSUE THREAD

**Issue by zzfighting** [PaddlePaddle/PaddleOCR#5201]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
移动端部署轻量化模型，首次推理使用图片A得到识别结果A，换另一张图片B推理得到结果之后，再换回图片A再次推理，得到的识别结果B和首次推理的结果A在每个文本框的坐标上都有像素级的差异，对比过传入模型的输入，确认几次输入的图片A没有任何差异，并且此后每一次使用图片A做输入推理始终得到结果B，通过实际比对，结果B的准确率比结果A略低。
- 系统环境/System Environment：Android 10
- 版本号/Version：Paddle：Paddle-lite v2.9  PaddleOCR： PaddleOCR v2.3 问题相关组件/Related components：
- 运行指令/Command Code：正常推理det-cls-rec
- 完整报错/Complete Error Message：无报错

**Comment by tink2123** [comment]
感谢反馈，android demo是由第三方开发的可能存在部分代码不完善。可以debug看下是否是B图的shape大于A，导致再次预测A时对图片进行了resize。

**Comment by ljdang** [comment]
@tink2123 同样的问题，实际上应该是只有第一张图识别正确，后面选择的图大概率会不准确，很容易复现。
相同的问题 #4420

**Comment by zzfighting** [comment]
@tink2123 感谢回复，已经对比过前后输入，确认在调jni之前传入的参数是一致的。同 @ljdang 所说，出现此现象只有第一张图识别正确，后续均没有第一次的准确率高

**Comment by livingbody** [comment]
666

**Comment by HosseinBakand** [comment]
> @tink2123 同样的问题，实际上应该是只有第一张图识别正确，后面选择的图大概率会不准确，很容易复现。 相同的问题 #4420

The same problem
