### ISSUE TITLE
【问题咨询】表格识别相关-文档拍照后图像无法识别出表格

### ISSUE THREAD

**Issue by LUOrenjia** [PaddlePaddle/PaddleOCR#5206]
- 系统环境：AIStudio  V100环境
- 版本号： PaddleOCR：paddleocr == 2.3.0.2
- 运行指令：
```
pip install paddleocr==2.3.0.2 
pip install -U https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl 
git clone https://gitee.com/paddlepaddle/PaddleNLP -b develop 
cd PaddleNLP 
pip install -e . 
paddleocr --image_dir=../doc/table/final.jpg --type=structure
```
- 问题描述：
一共测试了三张图片：
![1641538170701](https://user-images.githubusercontent.com/9481613/148507840-4397c599-9b3b-491a-8d6c-2b332c0b6aae.png)
第一张是电子档截图，paddleocr能够识别出表格；
第二张是将第一张图打印后拍照得到，paddleocr无法识别出表格；
第三张是对第二张图片文档部分做透视变换之后再二值化得到，paddleocr也无法识别出表格。
**请问需要怎么样处理拍照后的图片，才能够使得表格被paddleocr正确识别出来。**

**Comment by yjhtc007** [comment]
感觉paddleocr提供的表格识别模型都是在公用数据集上训练得到的吧，那些数据集大多都是文档中的表格，应用到自然场景图片下的表格识别效果会差一些吧。我感觉你做透视变换的操作是可以的，然后在表格识别之前可以先加一个表格检测的步骤，然后再去做表格结构解析。当然这个是我个人的想法哈。

**Comment by WenmuZhou** [comment]
楼上正解，目前发布的模型都是公开数据集训练的，你这种场景需要用自己的数据训练一下表格检测或者版面分析的模型
