### ISSUE TITLE
pdserving 最后怎么返回文本以及文本坐标

### ISSUE THREAD

**Issue by CharlesWu123** [PaddlePaddle/PaddleOCR#5209]
目前pdserving 只返回了 文本没有返回文本坐标，请问如何返回文本坐标呢

**Comment by tink2123** [comment]
可以参考这个修改： https://github.com/PaddlePaddle/PaddleOCR/issues/4742

**Comment by yudw15** [comment]
> 目前pdserving 只返回了 文本没有返回文本坐标，请问如何返回文本坐标呢

启动web_service.py，最终结果只有识别文本和置信度。在DetOp的postprocess中有检测框但没有检测置信度；在RecOp的input_dict中检测坐标不是原图上的，无法对应原图位置。

**Comment by yudw15** [comment]
你好，邮件已收到
