### ISSUE TITLE
window下进行C++部署cpu和gpu检测结果不一致

### ISSUE THREAD

**Issue by prettyocean85** [PaddlePaddle/PaddleOCR#521]
win10使用VS2019编译C++预测demo，预测同一张图发现使用CPU和GPU得到的结果不一致，查看检测框发现检测框位置有差别。而且C++预测时间也比用python预测时间长1倍，排查代码确认是识别部分耗时多。请问这两个问题是什么原因。

**Comment by littletomatodonkey** [comment]
官网提供的是1.7.1的inference model，而预测库是1.8.2的，在windows下需要先基于最新代码和paddle导出模型，再进行预测，也可以使用下面这个检测的inference model

[det_mv3_182.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5062045/det_mv3_182.zip)

**Comment by prettyocean85** [comment]
更新模型后cpu和gpu预测结果一致了。请问C++预测时间比python长一两倍是什么原因？@littletomatodonkey

> 官网提供的是1.7.1的inference model，而预测库是1.8.2的，在windows下需要先基于最新代码和paddle导出模型，再进行预测，也可以使用下面这个检测的inference model
> 
> [det_mv3_182.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5062045/det_mv3_182.zip)

**Comment by prettyocean85** [comment]
又发现了新的问题，中文轻量模型预测，使用最新的代码导出预测模型后进行预测。C++预测demo在cpu下第一次预测结果是正确的，后面不再重新加载模型，直接再进行预测结果就越来越不对了。GPU下测试正常。

**Comment by yjmm10** [comment]
> 官网提供的是1.7.1的inference model，而预测库是1.8.2的，在windows下需要先基于最新代码和paddle导出模型，再进行预测，也可以使用下面这个检测的inference model
> 
> [det_mv3_182.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5062045/det_mv3_182.zip)

linux有这个问题吗，需要重新导出模型吗

**Comment by littletomatodonkey** [comment]
目前应该结果是一致的，可以试下最新代码
