### ISSUE TITLE
单字坐标信息如何返回？

### ISSUE THREAD

**Issue by Q-amazing** [PaddlePaddle/PaddleOCR#5210]
请问，PPOCR除了返回文字行的坐标，能返回文字行内的每个文字的坐标吗？该怎么操作呢？

**Comment by tink2123** [comment]
模型暂时无法支持，可以通过获取字符个数和整行坐标，简单的计算出单字的坐标。

**Comment by yjhtc007** [comment]
试试CRAFT模型？

**Comment by nissansz** [comment]
> 试试CRAFT模型？

怎么使用CRAFT模型？微信nlanguage
