### ISSUE TITLE
关于小语种的竖排新闻识别

### ISSUE THREAD

**Issue by suchunxie** [PaddlePaddle/PaddleOCR#5213]
您好，最近在做报纸识别项目， 调用日语的预下载识别模型 识别率不高。而且有些字模糊读不出来， 有几点问题想请教。
试用了pp-structure去预测，结果出来是很多横向的小短文本框， 很多文字识别不出来 方向也是错的。请问要改善的话 是要自己重 
    新训版面分析模型吗，ppstructure中如何更换或指定识别模型呢 ? ( 训练版面分析模型那里的数据集我看了一下 好像是只有横的文 
     本的)

**Comment by tink2123** [comment]
ppocr提供的模型考虑的竖排场景较少，目前repo里提供的模型，很难直接满足您的需求。
建议重新训练一个竖排检测+竖排识别模型。可以用提供的预训练模型做pretrain，如果数据量够的话从头训练也ok。

**Comment by suchunxie** [comment]
非常感谢您的回复!  在训模型上还有几个问题想向您请教。

1. 请问要重新训练的话 是如何操作呢？ 我有参加前几天动手OCR的课程，目前只对使用提供的预训练模型大概知道一些。是分别拿预训练好的检测和识别模型 (只能用日语的吗)，自己增加数据去训练，分别取最优精度吗？最后如何把检测模型＋识别模型结合起来呢？
2. 识别模型希望能实现查看候补单词功能(除了最有可能的哪个之外，其他置信度较高的候补项)，可以在哪个文件中如何调整呢？

3. 我目前有2000张左右的单排竖排日语图片， 请问训练集里面可以增加单个字的图片去训练吗？

4. 从头训练是说自己构建网络去训练吗，有没有什么地方可以参考呢。

很喜欢长颈鹿老师的课! 抱歉占用您的时间，希望能得到您的指点，不胜感激!
