### ISSUE TITLE
Android手机opencl加速失败

### ISSUE THREAD

**Issue by lrjj** [PaddlePaddle/PaddleOCR#5218]
CPU型号是高通骁龙855，GPU型号是Adreno 640，我是在PaddleOCR的android demo上面修改的，原本的android demo是CPU上面运行的，可以成功运行，我想通过opencl加速，做了以下修改：
1、程序上面参照例程如下修改：
![image](https://user-images.githubusercontent.com/68632486/148646525-acbc6622-b004-42aa-a36d-edd0d368d738.png)

2、修改了PaddleOCR里的paddlelite编译库，编译预测库的指令分别为：
./lite/tools/build_android.sh
--arch=armv8
--toolchain=clang
--with_log=OFF
--with_extra=ON
--with_cv=ON
--with_opencl=ON
3、推理模型分别为官方的ch_ppocr_mobile_v2.0_det_slim_opt和ch_ppocr_mobile_v2.0_rec_slim_opt,转成np文件的指令分别为：
./opt --model_file=./ch_ppocr_mobile_v2.0_det_slim_infer/inference.pdmodel --param_file=./ch_ppocr_mobile_v2.0_det_slim_infer/inference.pdiparams --optimize_out=./ch_ppocr_mobile_v2.0_det_slim_opt --valid_targets=opencl --optimize_out_type=naive_buffer

./opt --model_file=./ch_ppocr_mobile_v2.0_rec_slim_infer/inference.pdmodel --param_file=./ch_ppocr_mobile_v2.0_rec_slim_infer/inference.pdiparams --optimize_out=./ch_ppocr_mobile_v2.0_rec_slim_opt --valid_targets=opencl --optimize_out_type=naive_buffer
4、删除掉删掉padllelite的java文件夹（我用C++ API推理）和libpaddle_light_api_shared.so，更换了上面编译支持的opencl的libpaddle_light_api_shared.so，该文件夹内，除了改so文件还有以下几个文件我没有更换，我不知道他们的作用
（1）libc++_shared.so
（2）libhiai.so
（3）libhiai_ir.so
（4）libhiai_ir_build.so
（5）libpaddle_api_light_bundled.a

然后现在的APK运行结果就是没有结果，也就是图片上面的文字一个都没有检测和识别出来，结果返回一个空列表。我用了高通的官方软件Snapdragon Profiler进行了监控，发现不能监控GPU的状态，只有CPU的状态（如下图所示），这个是表明没能成功在GPU上面运行嘛？但是IsOpenCLBackendValid返回的是1，说明找到opencl了呀？我的paddle-lite是通过如下命令获取的：git clone https://github.com/PaddlePaddle/Paddle-Lite.git
![image](https://user-images.githubusercontent.com/68632486/148646549-f44c96e0-9112-47bb-b6ae-271afd93e598.png)

**Comment by WenmuZhou** [comment]
你好转换的模型可以试一下lite的推理，看lite下检测识别都有没有结果

**Comment by junknet** [comment]
您好 我也遇到这个问题了，请问这个问题后续有解决方案吗
