### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known 

### ISSUE THREAD

**Issue by chaosjeyli** [PaddlePaddle/PaddleOCR#5221]
- 系统环境/System Environment：Linux x86
- 版本号/Version：Paddle：  PaddleOCR：2.4
- 运行指令/Command Code：  

ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)

- 完整报错/Complete Error Message：
 
在本地离线执行脚本，运行 **ocr = PaddleOCR(use_angle_cls=True, lang="ch")** 命令时报错：Failed to establish a new connection: [Errno -2] Name or service not known 
请问是否每次运行该命令都需要链接网络服务器，或是能够首次连接执行后，之后均离线本地运行

**Comment by MissPenguin** [comment]
第一次运行会下载模型，后面就不会再重新下载了
