### ISSUE TITLE
version PP-OCRv2 not support cls models, auto switch to version PP-OCR

### ISSUE THREAD

**Issue by jcn199729** [PaddlePaddle/PaddleOCR#5223]
代码：
```
import cv2
from paddleocr import PaddleOCR

img = cv2.imread("./tmp00001.jpg")
OCR = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True)
print(OCR.ocr(img))
```
图片如下：
![tmp00001](https://user-images.githubusercontent.com/58527362/148722969-70b05e73-beb1-4c52-abe4-da053127e2ec.jpg)
返回信息：
root WARNING: version PP-OCRv2 not support cls models, auto switch to version PP-OCR
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/2.3.0.2/ocr/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/2.3.0.2/ocr/det/ch/ch_PP-OCRv2_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, ocr_version='PP-OCRv2', output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='/root/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_shape='3, 32, 320', rec_model_dir='/root/.paddleocr/2.3.0.2/ocr/rec/ch/ch_PP-OCRv2_rec_infer', save_log_path='./log_output/', show_log=True, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, **use_gpu=False**, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=True)
[[[[29.0, 41.0], [384.0, 41.0], [384.0, 91.0], [29.0, 91.0]], ('你能给她什么', 0.97502786)]]

这里需求中只需要用到rec模型，注意到自动切换为PP-OCR的时候自动设置use_gpu=False了，想请问如何不自动切换到PP-OCR，或者即使切换到PP-OCR但是保持设置为use_gpu=True用于加速呢？谢谢

**Comment by WenmuZhou** [comment]
这条提示是说cls模型没有用PP-OCRv2的方法训练，因此使用过程中会自动切换到PP-OCR的版本，这个不影响gpu的使用的，目前已删除这条提示，

**Comment by lemon9707** [comment]
请问我在docker容器中运行，无网环境，不能自动切换到PP-OCR的版本，应该怎么处理
