### ISSUE TITLE
使用 PP-OCRv2 训练精度0.99, 转为推理后, 精度为0, 使用的默认字典ppocr_keys_v1.txt

### ISSUE THREAD

**Issue by qq70571382** [PaddlePaddle/PaddleOCR#5225]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 16.04.6 LTS
- 版本号/Version：Paddle 2.2.1：  PaddleOCR latest： 问题相关组件/Related components：4350
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

已参考了
 [https://github.com/PaddlePaddle/PaddleOCR/issues/4350](url)
[https://github.com/PaddlePaddle/PaddleOCR/issues/5046](url)
[https://github.com/PaddlePaddle/PaddleOCR/issues/4371](url)
[https://github.com/PaddlePaddle/PaddleOCR/issues/4350](url)
# 训练命令如下

```
!wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_train.tar
!tar -xvf ch_PP-OCRv2_rec_train.tar 
%cd ~/PaddleOCR
!python3 tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.pretrained_model=./pre_train/ch_PP-OCRv2_rec_train/best_accuracy
```

# 测试训练模型命令如下
```
!python3 tools/infer_rec.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.checkpoints=./output/rec_mobile_pp-OCRv2/best_accuracy Global.infer_img=/home/aistudio/dh_rec_img/crop_img/38_crop_11.jpg

[2022/01/10 15:33:27] root INFO: 	 result: 岩泊渡镇	0.9946313

#导出模型
!python3 tools/export_model.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.checkpoints=./output/rec_mobile_pp-OCRv2/best_accuracy -o  Global.save_inference_dir="./output/rec_ppocrv2_dh/"

#测试导出的模型
!python3 tools/infer/predict_rec.py --image_dir=/home/aistudio/dh_rec_img/crop_img/38_crop_11.jpg --rec_model_dir=./output/rec_ppocrv2_dh/ 

[2022/01/10 15:33:40] root INFO: Predicts of /home/aistudio/dh_rec_img/crop_img/38_crop_11.jpg:('㴪', 0.00018511788)
```

![1111](https://user-images.githubusercontent.com/7381590/148732810-53bd3e7b-becf-4526-9abb-46749a42f3db.jpg)

配置文件 /ch_PP-OCRv2_rec.yml , 只修改了数据集,其他都是默认

```
Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_mobile_pp-OCRv2
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_mobile_pp-OCRv2.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [700, 800]
    values : [0.001, 0.0001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 2.0e-05


Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    name: CTCHead
    mid_channels: 96
    fc_decay: 0.00002

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/dh_rec_img/
    label_file_list:
    - /home/aistudio/dh_rec_img/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/dh_rec_img/
    label_file_list:
    - /home/aistudio/dh_rec_img/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8
```

**Comment by qq70571382** [comment]
这个附件是训练出来的模型文件
[rec_mobile_pp-OCRv2.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7837457/rec_mobile_pp-OCRv2.zip)

**Comment by qq70571382** [comment]
折腾了两天, 还是不行, 我打算改下代码包装下训练代码, 用训练的模型算了.

**Comment by ioracion** [comment]
这里的[代码](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/predict_rec.py#L110)改成下面这个试试

max_wh_ratio = max(max_wh_ratio, imgW / imgH)
imgW = int((32 * max_wh_ratio))

**Comment by tink2123** [comment]
@qq70571382  你好，加载了你的模型文件可以成功导出模型～并且inference预测结果与训练代码预测相同，可以再检查一下导出时模型加载是否成功。
使用PaddleOCR dygraph分支代码：
```
# 训练引擎预测
python3.7 tools/infer_rec.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
# 模型导出
python3.7 tools/export_model.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
# 预测引擎预测
python3.7 tools/infer/predict_rec.py --rec_model_dir=rec_mobile_pp-OCRv2/ --image_dir=doc/imgs_words/ch/word_1.jpg
```
![image](https://user-images.githubusercontent.com/31891223/149058797-8c48c3aa-14a0-4b66-9d49-0e2cbce100d7.png)

我这边导出的模型文件：
[inference.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7851445/inference.zip)

**Comment by qq70571382** [comment]
> @qq70571382 你好，加载了你的模型文件可以成功导出模型～并且inference预测结果与训练代码预测相同，可以再检查一下导出时模型加载是否成功。 使用PaddleOCR dygraph分支代码：
> 
> ```
> # 训练引擎预测
> python3.7 tools/infer_rec.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
> # 模型导出
> python3.7 tools/export_model.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
> # 预测引擎预测
> python3.7 tools/infer/predict_rec.py --rec_model_dir=rec_mobile_pp-OCRv2/ --image_dir=doc/imgs_words/ch/word_1.jpg
> ```
> 
> ![image](https://user-images.githubusercontent.com/31891223/149058797-8c48c3aa-14a0-4b66-9d49-0e2cbce100d7.png)
> 
> 我这边导出的模型文件： [inference.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7851445/inference.zip)

改了下还是不行哦
![image](https://user-images.githubusercontent.com/7381590/149071069-ad196d72-82bf-4859-9e34-d38ce8f8f4b7.png)

![image](https://user-images.githubusercontent.com/7381590/149071195-5ccb46b3-1a9b-4ed5-bc3f-5adf9ae7dacc.png)

**Comment by qq70571382** [comment]
> @qq70571382 你好，加载了你的模型文件可以成功导出模型～并且inference预测结果与训练代码预测相同，可以再检查一下导出时模型加载是否成功。 使用PaddleOCR dygraph分支代码：
> 
> ```
> # 训练引擎预测
> python3.7 tools/infer_rec.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
> # 模型导出
> python3.7 tools/export_model.py -c rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_mobile_pp-OCRv2/best_accuracy
> # 预测引擎预测
> python3.7 tools/infer/predict_rec.py --rec_model_dir=rec_mobile_pp-OCRv2/ --image_dir=doc/imgs_words/ch/word_1.jpg
> ```
> 
> ![image](https://user-images.githubusercontent.com/31891223/149058797-8c48c3aa-14a0-4b66-9d49-0e2cbce100d7.png)
> 
> 我这边导出的模型文件： [inference.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7851445/inference.zip)

谢谢您能抽出时间帮忙测试, 按照您的测试步骤, 测试了下, 是可以的, 原因是导出模型这一个步骤出了问题, 没有真正导出成功.
我重现了测试的每一个步骤, 对比了操作, 发现问题出在了配置文件上

```
#失败的导出命令
python3.7 tools/export_model.py -c ./configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml  -o Global.pretrained_model=./output/rec_mobile_pp-OCRv2/best_accuracy  -o  Global.save_inference_dir=./rec_mobile_pp-OCRv2
#成功的导出命令 

python3.7 tools/export_model.py -c ./rec_mobile_pp-OCRv2/config.yml  -o Global.pretrained_model=./output/rec_mobile_pp-OCRv2/best_accuracy  -o  Global.save_inference_dir=./rec_mobile_pp-OCRv2
```

区别是成功的使用了训练模型目录的config.yml, 失败的使用了训练时的配置文件ch_PP-OCRv2_rec.yml
我diff了两个文件
![image](https://user-images.githubusercontent.com/7381590/149260231-1d73d857-d654-473b-8d38-500f4249abbe.png)

试验了下,是**pretrained_model** 这个选项出问题了, 命令行里的-o Global.pretrained_model 貌似没有生效, 不能覆盖配置文件里选项, ch_PP-OCRv2_rec.yml 里默认是空的, 所以导出失败了,但是奇怪的是导出过程并没有报错, 而且也成功生成了推理模型文件
![image](https://user-images.githubusercontent.com/7381590/149261276-3965bf37-6bcd-4b0a-bca3-e83dc667e26e.png)

感觉是命令参数接收的问题, 又看了下export_model.py 的代码, 调试了下发现是 只接收一个 -o, 就是正确的写法应该是
**_-o Global.pretrained_model=./output/rec_mobile_pp-OCRv2/best_accuracy    Global.save_inference_dir=./rec_mobile_pp-OCRv2_**
我先前的命令传参的方法是错误的 
**_-o Global.pretrained_model=./output/rec_mobile_pp-OCRv2/best_accuracy  -o  Global.save_inference_dir=./rec_mobile_pp-OCRv2_**

问题解决了, 应该说是我的低级错误, 没理解命令行传参的正确方法, 

再次感谢! @tink2123   另外建议 export_model 模型时 pretrained_model为空直接报错就更好了,估计犯我这个错误的同学还有不少:)
