### ISSUE TITLE
crnn如何得到单个字符识别概率

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#523]
predict_rec.py里面rec_idx_tmp和probs[valid_ind, ind[valid_ind]]长度并不相同

**Comment by LDOUBLEV** [comment]
> predict_rec.py里面rec_idx_tmp和probs[valid_ind, ind[valid_ind]]长度并不相同

每个字的score不在rec_idx_tmp里，计算整行文本的平均score是：
```
score = np.mean(probs[valid_ind, ind[valid_ind]])
```
所以 获取每个字的score，就是
```
chars_score = probs[valid_ind, ind[valid_ind]]

```

**Comment by dyning** [comment]
rec_idx_tmp是ctc_greedy_decoder的结果（ https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/modeling/losses/rec_ctc_loss.py ），该OP用于贪婪策略解码序列，步骤如下:
获取输入中的每一行的最大值索引，也就是numpy.argmax(input, axis=0)。
对于step1结果中的每个序列，合并两个空格（占位符）之间的重复部分并删除所有空格。可以参考文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/ctc_greedy_decoder_cn.html#ctc-greedy-decoder。但是没有score信息。

probs为了计算score的，可以通过probs计算识别的文字和得分。

**Comment by deep-practice** [comment]
probs里面是存的每个时间步对应的字符概率分布
而rec_idx_tmp已经是字典里面字符的index了
不是很理解你说的怎么通过probs计算识别的文字和得分
@dyning

**Comment by deep-practice** [comment]
chars_score = probs[valid_ind, ind[valid_ind]]这样子得出来的元素个数和识别出来的字符个数不相等 @LDOUBLEV

**Comment by deep-practice** [comment]
probs里面的包含了空格和重复字符吧？

**Comment by LDOUBLEV** [comment]
> chars_score = probs[valid_ind, ind[valid_ind]]这样子得出来的元素个数和识别出来的字符个数不相等 @LDOUBLEV

probs里面的包含了空格和重复字符.
probs[valid_ind, ind[valid_ind]]获取的就是每个字符的score了，我测试了元素个数是和识别字符数相等的，你可否发一下你的原图看下，下面是我的测试结果。

![image](https://user-images.githubusercontent.com/26592129/90210515-ba0dae80-de20-11ea-9b20-a3a745b19e11.png)

**Comment by deep-practice** [comment]
![7](https://user-images.githubusercontent.com/54052915/90220235-63ad6980-de3a-11ea-9b75-c1a878aebf18.jpg)
![8](https://user-images.githubusercontent.com/54052915/90220246-6c05a480-de3a-11ea-9536-cf53381b3161.jpg)
我这边基本上位数都对不上，我改了配置文件的max_length,这个会有影响吗 @LDOUBLEV

**Comment by deep-practice** [comment]
@LDOUBLEV 有复现到问题吗？

**Comment by BaoBaoJianqiang** [comment]
> > chars_score = probs[valid_ind, ind[valid_ind]]这样子得出来的元素个数和识别出来的字符个数不相等 @LDOUBLEV
> 
> probs里面的包含了空格和重复字符. probs[valid_ind, ind[valid_ind]]获取的就是每个字符的score了，我测试了元素个数是和识别字符数相等的，你可否发一下你的原图看下，下面是我的测试结果。
> 
> ![image](https://user-images.githubusercontent.com/26592129/90210515-ba0dae80-de20-11ea-9b20-a3a745b19e11.png)

如果能取到每个字的准确度，那能否也取出每个字的坐标呢？
