### ISSUE TITLE
修改 pdserving 的路由地址、请求参数以及返回结果

### ISSUE THREAD

**Issue by CharlesWu123** [PaddlePaddle/PaddleOCR#5233]
请问如何修改 pdserving 的路由地址、请求参数以及返回结果，在哪里修改呢。
我想改变 pdserving 的路由地址，以及请求 pdserving 的参数，还有 pdserving 的返回参数

**Comment by LDOUBLEV** [comment]
路由地址：
https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/deploy/pdserving/pipeline_http_client.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L31


请求参数可以在配置文件里找：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/deploy/pdserving/config.yml

pdserving 的返回就是预测结果了，修改返回参数是指？

**Comment by CharlesWu123** [comment]
不好意思，可能我没有表达明白，我详细说一下我的需求
1. 你给这个路由地址是客户端的URL，我是想要修改服务端的URL，比如我想改成 http://127.0.0.1:9998/innerapi/ai/python/agent 需要怎么修改
2. 我想要改的请求参数是指：现在pdserving本身请求需要以这种形式传输数据 {"key": ["img"], "value": [image]}，但是我想改成这种形式的 {"img": image}，因为后续可能还要添加一些参数，这种形式会更方便一些
3. 修改返回参数是指：现在pdserving本身返回的参数是这种形式 {"key": ["res"], "value": [""]}，我也想改成  {"res":""} 这种形式的，后续也是要添加一些返回参数，这种的更符合接口的形式，更方便
麻烦大佬解答一下了

**Comment by bjjwwang** [comment]
1. URL： https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Python_Pipeline/Pipeline_Design_CN.md#44-%E8%87%AA%E5%AE%9A%E4%B9%89url
2. 考虑过这种情况，之所以是现在的设计，是为了兼容不同模型 key 的变长，否则很难用一套proto处理多个 KV的情况。如果要修改，可能风险较大，先改 https://github.com/PaddlePaddle/Serving/blob/v0.7.0/python/pipeline/proto/pipeline_service.proto#L87， 然后https://github.com/PaddlePaddle/Serving/blob/v0.7.0/python/pipeline/operator.py#L1660 这里也需要改解析字典的方法，最后需要改web_service.py的dict读取。
3. 和2一样。为了解决变长。改动也类似。

**Comment by CharlesWu123** [comment]
改动这三个地方都是需要修改 proto 文件，这个需要重新编译吗

**Comment by roomeo** [comment]
请问修改或增加路由是在哪个路径中添加
