### ISSUE TITLE
少量数据finetune ppocrv2 的识别模型效果不好

### ISSUE THREAD

**Issue by JunYao1020** [PaddlePaddle/PaddleOCR#5234]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows / linux
- 版本号/Version：Paddle：2.2.0 GPU  PaddleOCR：2.4.0  问题相关组件/Related components： 识别模型
官方提供的模型在某些特定的字体上对于少部分英文数据识别错误的概率较高如 F 识别成 P ，D识别成O ，A识别成4，于是我使用了大约200张真实的数据，数据内容类似 'ERFDAGDSXV' 字符串，在官方的协同蒸馏模型上finetune，训练结果提高了在我的场景下英文的识别率，但是中文的识别却被严重破坏了，于是我又添加了少部分中文的数据作为训练数据，finetune结束后，在训练集中的中文数据，不会被破坏识别效果，但是不在训练集中的数据依然会被破坏识别效果。
这样，我想finetune一个适合我的中英文场景的识别模型似乎需要比较庞大的数据量，在时间上的成本会增加许多。
因此，我想要更少的数据集来finetune一个适用于我的比较理想的模型，有没有好的方案？

**Comment by latawangzi** [comment]
同问，遇到同样的问题

**Comment by LDOUBLEV** [comment]
可尝试freeze大部分参数，finetune只训练最后一层的参数或者最后几层的参数

**Comment by JunYao1020** [comment]
谢谢, 这样的话, 配置文件该如何更改呢

**Comment by JunYao1020** [comment]
我看配置文件里，冻结参数的配置好像是冻结全部参数






------------------ 原始邮件 ------------------
发件人: Double_V ***@***.***&gt;
发送时间: 2022年1月12日 09:59
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: JunYao1020 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)





 
可尝试freeze大部分参数，finetune只训练最后一层的参数或者最后几层的参数
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDOUBLEV** [comment]
参考这部分代码，如果要freeze哪些参数，把这些参数的trainable 属性设置为False即可
https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/architectures/distillation_model.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L50

**Comment by JunYao1020** [comment]
![freeze_linear](https://user-images.githubusercontent.com/65162523/149253383-1747602d-dc81-4439-a7ed-8cd30287a094.png)

这是我freeze所有linear层的方案针对train.py修改的代码

**Comment by JunYao1020** [comment]
![freeze_last](https://user-images.githubusercontent.com/65162523/149253659-9dd087f4-525b-4131-ad1f-ba5a8780f5bd.png)
这是我freeze最后一层的方案针对train.py修改的代码。162索引位置应该是teacher的最后一层，-1索引位置应该是student的最后一层

**Comment by GivanTsai** [comment]
> 

请问你使用的协同蒸馏模型是哪个呢

**Comment by GivanTsai** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 就是官方推荐的那个 ***@***.*** 签名由网易邮箱大师定制 在2022年1月14日 ***@***.***> 写道： 请问你使用的协同蒸馏模型是哪个呢 —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

有链接吗

**Comment by JunYao1020** [comment]
> > font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 就是官方推荐的那个 _**@**_.*** 签名由网易邮箱大师定制 在2022年1月14日 _**@**_._**> 写道： 请问你使用的协同蒸馏模型是哪个呢 —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> 
> 有链接吗

**Comment by JunYao1020** [comment]
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_train.tar 这个模型是我问题中所使用的

**Comment by JunYao1020** [comment]
不小心点了 closed

**Comment by GivanTsai** [comment]
> 不小心点了 closed

你finetune的效果有变好吗，我的反而变差了

**Comment by JunYao1020** [comment]
我尝试了很久，感觉数据的量可以少，但是数据的种类要多，这样finetune才能效果好一点，但是我目前的finetune结果都不如官方的，尝试了冻结大部分参数训练，效果也不佳。没有足够的数据广度，可以找开源数据集，我用了100W中文数据加入训练，目前效果改善不少



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 晚上6:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)





  
不小心点了 closed
  
你finetune的效果有变好吗，我的反而变差了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GivanTsai** [comment]
> 
你也是finetine后效果反而变差了吗，官方的模型本来就是在大量开源数据集上训的，finetune不是需要该任务上的数据集上训比较好吗

**Comment by JunYao1020** [comment]
是的，官方公布的应该是他finetune的预训练模型，如果要在官方成品的基础上finetune，不知道有没有办法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GivanTsai ***@***.***&gt;
发送时间: 2022年1月14日 18:58
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: JunYao1020 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)





   
你也是finetine后效果反而变差了吗，官方的模型本来就是在大量开源数据集上训的，finetune不是需要该任务上的数据集上训比较好吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by suchxyz** [comment]
> 可尝试freeze大部分参数，finetune只训练最后一层的参数或者最后几层的参数

可以贴一下完成的配置文件吗？

**Comment by 18362890185** [comment]
> 我尝试了把最后一层freeze和把最后几层linear层freeze两种方案，用我的数据集finetune，数据集大小4w左右，内容是中英文，中文内容覆盖的汉子种类不多，大约100种。训练过程中的acc先上升几个百分点就震荡了，freeze所有linear层的train acc 在70左右震荡，eval acc在69左右震荡。仅freeze最后一层的train acc在45左右震荡，eval acc在55左右震荡。是我freeze的方法错了吗，还是数据集不够合适？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Double_V ***@***.***&gt; 发送时间: 2022年1月13日 09:58 收件人: PaddlePaddle/PaddleOCR ***@***.***&gt; 抄送: JunYao1020 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)

你好，请问一下，关于这个问题，您是如何解决的？

**Comment by JunYao1020** [comment]
> > 我尝试了把最后一层freeze和把最后几层linear层freeze两种方案，用我的数据集finetune，数据集大小4w左右，内容是中英文，中文内容覆盖的汉子种类不多，大约100种。训练过程中的acc先上升几个百分点就震荡了，freeze所有linear层的train acc 在70左右震荡，eval acc在69左右震荡。仅freeze最后一层的train acc在45左右震荡，eval acc在55左右震荡。是我freeze的方法错了吗，还是数据集不够合适？ 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Double_V _**@**_._**> 发送时间: 2022年1月13日 09:58 收件人: PaddlePaddle/PaddleOCR _**@**_.**_> 抄送: JunYao1020 _**@**_._**>, Author _**@**_.**_> 主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)
> 
> 你好，请问一下，关于这个问题，您是如何解决的？

我并没有根本地解决这个问题，我认为要根本解决还需从数据上下手。
可能对你有效的做法是每次遇到识别不好的文字，人工添加对应的数据，初始lr设置为3e-4， 下降策略用cosin，warmup一个epoch，总共epoch20次，根据你的数据量，大概在5-15个epoch之间会有比较好的仅适用你的数据的模型。
我是这么做的，本质上也是增加数据，效果显著

**Comment by Lebron-Harden** [comment]
> > > 我尝试了把最后一层freeze和把最后几层linear层freeze两种方案，用我的数据集finetune，数据集大小4w左右，内容是中英文，中文内容覆盖的汉子种类不多，大约100种。训练过程中的acc先上升几个百分点就震荡了，freeze所有linear层的train acc 在70左右震荡，eval acc在69左右震荡。仅freeze最后一层的train acc在45左右震荡，eval acc在55左右震荡。是我freeze的方法错了吗，还是数据集不够合适？ 发自我的iPhone
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: Double_V _**@**_._**> 发送时间: 2022年1月13日 09:58 收件人: PaddlePaddle/PaddleOCR _**@**_.**_> 抄送: JunYao1020 _**@**_._**>, Author _**@**_.**_> 主题: Re: [PaddlePaddle/PaddleOCR] 少量数据finetune ppocrv2 的识别模型效果不好 (Issue #5234)
> > 
> > 
> > 你好，请问一下，关于这个问题，您是如何解决的？
> 
> 我并没有根本地解决这个问题，我认为要根本解决还需从数据上下手。 可能对你有效的做法是每次遇到识别不好的文字，人工添加对应的数据，初始lr设置为3e-4， 下降策略用cosin，warmup一个epoch，总共epoch20次，根据你的数据量，大概在5-15个epoch之间会有比较好的仅适用你的数据的模型。 我是这么做的，本质上也是增加数据，效果显著

请问您这么训练，是冻结了哪一部分的参数呢？我也遇到了同样的问题，希望在自己的数据集上finetune
