### ISSUE TITLE
表格识别报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by lsl001006** [PaddlePaddle/PaddleOCR#5236]
我下载按照官网例程进行了表格识别的使用，但是在执行例程中的代码时报错，希望能够找到原因

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：2.4
- 问题相关组件/Related components：table
- 运行指令/Command Code：（使用官方例程）
-
` python table/predict_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=../doc/table/1.png --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --rec_char_dict_path=../ppocr/utils/dict/en_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../output/table`
- 完整报错/Complete Error Message：
`Traceback (most recent call last):
  File "table/predict_table.py", line 221, in <module>
    main(args)
  File "table/predict_table.py", line 197, in main
    pred_html = text_sys(img)
  File "table/predict_table.py", line 88, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "./PaddleOCR/tools/infer/predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "./PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 96, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "./PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 68, in decode
    idx])])
IndexError: list index out of range`

**Comment by andyjpaddle** [comment]
请参考 #5145 的解决办法
