### ISSUE TITLE
如何支持空格的OCR

### ISSUE THREAD

**Issue by yangfei963158659** [PaddlePaddle/PaddleOCR#524]
你好，我用paddleOCR识别的文字会因为空格把文字分开，请问怎么支持空格的OCR

**Comment by MissPenguin** [comment]
可以贴一个具体的case看下吗

**Comment by yangfei963158659** [comment]
![48df8d5d4da7e2f294ba56aa8cebd6b](https://user-images.githubusercontent.com/5491887/90096912-45c30480-dd67-11ea-87ff-54739008ec30.jpg)

**Comment by littletomatodonkey** [comment]
首页上就有支持空格的模型的，可以试下
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/README_cn.md

但是这个断开与训练时的标注方式也有关系，希望自己的场景中效果更好的话，可以基于官网的模型进行finetune。


![image](https://user-images.githubusercontent.com/14270174/90229669-df171700-de4a-11ea-9ac2-2668deae800e.png)

**Comment by navneetkrc** [comment]
[Issue 438](https://github.com/PaddlePaddle/PaddleOCR/issues/432)
There is an older issue that this issue is related to.

**Comment by DuckJ** [comment]
你好，请问finetune的时候，原来的数据集也要加进去吧。以crnn模型为例，原来的字典里面是没有空格的，我加入空格之后，字典大小+1，即lstm的最后出来的维度变了，这部分权重都得重新学习，当我利用新的数据集finetune的时候，是不是新的数据集覆盖度也必须有原来的数据集那么大啊，不然的话网络学习不到合适的lstm参数权重啊？请问我这样理解对么，你们的带空格模型请问是怎么训练的啊 @littletomatodonkey
