### ISSUE TITLE
paddlelite 在树莓派中编译通过，引用时候报错

### ISSUE THREAD

**Issue by zhangyaobo** [PaddlePaddle/PaddleOCR#525]
1 编译完成的日志
![image](https://user-images.githubusercontent.com/30718793/90114613-8c275c00-dd85-11ea-970a-c180e9c48f7d.png)
2 引用报错
Segmentation fault (core dumped)
![image](https://user-images.githubusercontent.com/30718793/90114685-a4977680-dd85-11ea-987c-83566d9c1186.png)
命令 ：from paddlelite.lite import *
3 从网上查了一下有一个这个命令ulimit -S -s unlimited，执行之后，报这个
Illegal instruction (core dumped)

**Comment by zhangyaobo** [comment]
https://paddle-lite.readthedocs.io/zh/latest/demo_guides/python_demo.html?highlight=mobilenet_v1#id1

**Comment by zhupengyang** [comment]
- 试下 v2.6.0 或者 v2.6.1 的能不能用
