### ISSUE TITLE
关于PPStructure不支持lang=en的问题

### ISSUE THREAD

**Issue by yuansky** [PaddlePaddle/PaddleOCR#5253]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/9914666/149284472-c06908b3-bab9-41ea-8260-4e582c1f2df7.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/9914666/149284489-e85f464c-3ac1-414d-b98b-bb85c48c19f9.png">

**Comment by WenmuZhou** [comment]
这个本质上是一个提升，不影响使用啊，最新版whl包已经修复了

**Comment by yuansky** [comment]
> 
您好，谢谢您的回复哈~我在这个版本上出现的问题是使用lang=en所识别出的英文之间都没有空格，并且识别度和纯做OCR的相比会差很多
