### ISSUE TITLE
训练train.py卡住不动，偶尔会到训练迭代1-2次在卡住不动

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleOCR#5255]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：2.2
- 运行指令/Command Code：--use_gpu --cfg ./configs/deeplabv3p_xception65_optic.yaml
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/53806323/149284806-81317f5e-74e7-42c6-89d8-4b310a70b02e.png)
启动训练后在这里卡住不动，神奇的是偶尔会迭代两次然后再次卡住！显存没满，内存也没满，都还剩下很多。这是怎么回事

**Comment by tink2123** [comment]
看配置文件，你跑的并不是OCR的模型吧，可以去PaddleSeg下提issue：https://github.com/PaddlePaddle/PaddleSeg/issues
