### ISSUE TITLE
训练识别模型，一机多卡是报错如下。只是在simple_data.py加了点代码？注释掉就好了？为啥

### ISSUE THREAD

**Issue by zhaolongvip** [PaddlePaddle/PaddleOCR#5256]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
报错如下：
INFO 2022-01-13 15:47:13,031 launch_utils.py:320] terminate process group gid:47646
INFO 2022-01-13 15:47:20,039 launch_utils.py:341] terminate all the procs
ERROR 2022-01-13 15:47:20,040 launch_utils.py:602] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
INFO 2022-01-13 15:47:24,044 launch_utils.py:341] terminate all the procs
INFO 2022-01-13 15:47:24,044 launch.py:311] Local processes completed.

**Comment by zhaolongvip** [comment]
![image](https://user-images.githubusercontent.com/9498164/149289052-07cacd7c-4292-4462-8806-66dff0c0715b.png)

**Comment by zhaolongvip** [comment]
加的代码如上

**Comment by tink2123** [comment]
可以看下 log/workerlog.0 里的具体报错是什么

**Comment by zhaolongvip** [comment]
get

**Comment by xht** [comment]
这个问题解决了没，我也遇到这个问题了。

**Comment by yulm-1** [comment]
> 可以看下 log/workerlog.0 里的具体报错是什么



> 这个问题解决了没，我也遇到这个问题了。

同问大家解决这个问题了吗

**Comment by phb-shiyige-fw** [comment]
同样报错 多卡的时候就会显示这个 请问大家解决了吗
