### ISSUE TITLE
Is there a guide on transfer learning with Paddle OCR?

### ISSUE THREAD

**Issue by leminhyen2** [PaddlePaddle/PaddleOCR#5257]
I want to use the feature extraction layers of Paddle for Japanese and retrain the classification layer. Is there any tutorial on freezing layers for PaddleOCR?

**Comment by tink2123** [comment]
If you want to freeze some layers, you can set strop_gradient for FC layer，

https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/architectures/base_model.py#L75-L80

 like：

```
 x = self.backbone(x) 
 y["backbone_out"] = x 
 if self.use_neck: 
     x = self.neck(x) 
 y["neck_out"] = x 
 x.stop_gradient = True
 x = self.head(x, targets=data) 
    ....
```

**Comment by leminhyen2** [comment]
Oh thank you, so if I added that line then the backbone and neck layer of the OCR model will be freezed.  leaving only the head  (classification layer) that is trainable right? 

Does the training steps need to be changed in anyway or do I only need to do the usual training according to the guideline with my own data?

**Comment by tink2123** [comment]
You don't need to modify anything else, just follow the normal steps to train.

**Comment by leminhyen2** [comment]
Nice, thank you for the response :)

**Comment by MohieEldinMuhammad** [comment]
> Does the training steps need to be changed in anyway or do I only need to do the usual training according to the guideline with my own data?

Can you please share the link for retraining on a custom dataset ?

**Comment by anidiatm41** [comment]
@leminhyen2 can you pls share the transfer learning from default weight with custom data steps?

**Comment by leminhyen2** [comment]
@anidiatm41 my code didn't work and that time there was a better OCR model for Japanese so I didn't continue the transfer learning

**Comment by ManikSinghSarmaal** [comment]
> > Does the training steps need to be changed in anyway or do I only need to do the usual training according to the guideline with my own data?
> 
> Can you please share the link for retraining on a custom dataset ?

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_en/recognition_en.md#Custom_Dataset
