### ISSUE TITLE
移动端部署可以用python调用那两个nb文件么？

### ISSUE THREAD

**Issue by zhangyaobo** [PaddlePaddle/PaddleOCR#526]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md 
这里用的是c++做的，有没有python的相关代码呢

**Comment by LDOUBLEV** [comment]
这个是在手机arm上用的，目前只支持C++预测。而且nb模型只能在arm架构的芯片上运行。
