### ISSUE TITLE
部分文字识别不到

### ISSUE THREAD

**Issue by sunshine2176** [PaddlePaddle/PaddleOCR#5261]
ppcore版本: 2.2.1
ppocr版本: 2.1.1
![image](https://user-images.githubusercontent.com/5172675/149442272-c1587848-a6a7-4eb6-ba17-08d1ddd8866e.png)
这里的数字没有识别到，是因为太小还是别的原因呢?

**Comment by tink2123** [comment]
数字较小，另外检测的也不够准确

**Comment by sunshine2176** [comment]
感觉跟下面播放全部的数字大小又差不多，只是上面是灰色，对比度有些差
