### ISSUE TITLE
Fintune的结果bug

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5262]
现在我有个英文的训练集和测试集，我先直接用预训练模型去评估测试集，acc有0.5左右，然后在预训练模型的基础上用训练集去训练，再评估的话，acc反而下降了十几个点，这是为什么呢？

**Comment by WenmuZhou** [comment]
训练集数据量多大，训练集指标多少

**Comment by GivanTsai** [comment]
> 训练集数据量多大，训练集指标多少

训练数据集20万，测试集5万，指标就是acc

**Comment by WenmuZhou** [comment]
训练集上acc多少呢
