### ISSUE TITLE
Android端部署bug

### ISSUE THREAD

**Issue by ljdang** [PaddlePaddle/PaddleOCR#5265]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

基于官方的android_demo，无论是V2.0 slim模型还是PP-OCRv2 slim模型，都存在问题，识别第二张图的时候产生错误结果。
具体复现步骤，以V2.0 slim模型为例，输入图片见附件中测试图.jpg：
1）正常结果
打开app->加载模型->选取图片->运行模型
结果：附件中图V2.0_slim_正确.png
2）错误结果
打开app->加载模型->运行模型->选取图片->运行模型，相当于多运行了一张默认图片
结果：附件中图V2.0_slim_错误.png

PP-OCRv2 slim模型同理，只需将android_demo中的V2.0 slim模型替换为PP-OCRv2 slim模型即可，复现操作跟之前一致。
1）正常结果：附件中图PP-OCRv2_slim_正确.png
2）错误结果：附件中图PP-OCRv2_slim_错误.png
![PP-OCRv2_slim_错误](https://user-images.githubusercontent.com/21071150/149484623-d353e527-aeb6-46f0-8279-5737dc92967f.png)
[附件.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7869075/default.zip)

**Comment by WenmuZhou** [comment]
已复现，定位中

**Comment by ljdang** [comment]
@WenmuZhou 你好，请问有定位到问题点了吗？

**Comment by WenmuZhou** [comment]
你好，是预测库的问题，升级到2.10之后就解决了，这里提了个pr https://github.com/PaddlePaddle/PaddleOCR/issues/5265
