### ISSUE TITLE
是否可以公开"layoutxlm-large-uncased"模型，论文数large比base精度高，但是没有large的预训练模型large应该怎么训练呢？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleOCR#5267]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
论文repo目前还没有发布large模型哈，等那边发布了就可以了
