### ISSUE TITLE
May I ask when to release the pre-trained model of ch_PP-OCRv2_rec?

### ISSUE THREAD

**Issue by Honghe** [PaddlePaddle/PaddleOCR#5268]
PP-OCR is great, especially the PP-OCRv2. 
Thanks for the trained model of ch_PP-OCRv2_rec, but may I ask when to release the pre-trained model of ch_PP-OCRv2_rec?

![image](https://user-images.githubusercontent.com/1092722/149529396-e9d1f63a-9217-4624-87d4-bc3c3743decf.png)

**Comment by WenmuZhou** [comment]
你好，v2可以直接用训练模型进行finetune
