### ISSUE TITLE
请问下paddleocr如何同时部署多个识别模型？

### ISSUE THREAD

**Issue by stedylan** [PaddlePaddle/PaddleOCR#5269]
训练了不同的识别模型，需要同时部署，试了下hubserving，没能成功，还有其他解决方案吗

**Comment by littletomatodonkey** [comment]
建议
1. 启动多个server，然后客户端分别调用
2. 参考ocr_system的写法，把多个模型放在一个服务中，不过这种方法要改动的内容可能比较多

**Comment by stedylan** [comment]
> 

首先谢谢。
针对1，我的项目是可以启动多个server，我尝试过使用hubserving里的ocr_rec，但是代码里好像只能设置一个模型路径，就是说我虽然启动了多个服务，但是他们调用的还是同一个模型。可能这里面有些设置我还没搞懂，能麻烦说下具体点儿的步骤吗？

**Comment by stedylan** [comment]
> 建议
> 
> 1. 启动多个server，然后客户端分别调用
> 2. 参考ocr_system的写法，把多个模型放在一个服务中，不过这种方法要改动的内容可能比较多

首先谢谢。
针对1，我的项目是可以启动多个server，我尝试过使用hubserving里的ocr_rec，但是代码里好像只能设置一个模型路径，就是说我虽然启动了多个服务，但是他们调用的还是同一个模型。可能这里面有些设置我还没搞懂，能麻烦说下具体点儿的步骤吗？

**Comment by littletomatodonkey** [comment]
> > 建议
> > 
> > 1. 启动多个server，然后客户端分别调用
> > 2. 参考ocr_system的写法，把多个模型放在一个服务中，不过这种方法要改动的内容可能比较多
> 
> 首先谢谢。 针对1，我的项目是可以启动多个server，我尝试过使用hubserving里的ocr_rec，但是代码里好像只能设置一个模型路径，就是说我虽然启动了多个服务，但是他们调用的还是同一个模型。可能这里面有些设置我还没搞懂，能麻烦说下具体点儿的步骤吗？

启动不同的服务时，使用不同的路径就好了哈，识别路径是这个参数配置的

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/tools/infer/utility.py#L75

**Comment by stedylan** [comment]
> > > 建议
> > > 
> > > 1. 启动多个server，然后客户端分别调用
> > > 2. 参考ocr_system的写法，把多个模型放在一个服务中，不过这种方法要改动的内容可能比较多
> > 
> > 
> > 首先谢谢。 针对1，我的项目是可以启动多个server，我尝试过使用hubserving里的ocr_rec，但是代码里好像只能设置一个模型路径，就是说我虽然启动了多个服务，但是他们调用的还是同一个模型。可能这里面有些设置我还没搞懂，能麻烦说下具体点儿的步骤吗？
> 
> 启动不同的服务时，使用不同的路径就好了哈，识别路径是这个参数配置的
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/tools/infer/utility.py#L75

好的非常感谢，已解决问题
