### ISSUE TITLE
移动端部署的具体细节

### ISSUE THREAD

**Issue by JianhaoZhan** [PaddlePaddle/PaddleOCR#527]
看了你们的docs，感觉对部署还是不了解，请问如何把可执行文件或者代码部署到ARM核上，有具体教程吗？谢谢

**Comment by LDOUBLEV** [comment]
使用 abd 工具将可执行文件push到手机上运行。
![image](https://user-images.githubusercontent.com/26592129/90206651-cb51bd80-de16-11ea-80c3-2f32068872da.png)

**Comment by JianhaoZhan** [comment]
push了之后，可执行文件就在手机上了吗，我怎么在手机上调用他呢？还是说ＡＤＢ提供了一个虚拟环境？谢谢

**Comment by LDOUBLEV** [comment]
push 之后，可执行文件已经在手机上了，在手机上调用可以参考文档里与手机连调的步骤。完整的步骤在：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md

![image](https://user-images.githubusercontent.com/26592129/90211001-1f15d400-de22-11ea-8df8-dc10cb4a6861.png)

**Comment by JianhaoZhan** [comment]
最后一步不还是在linux下面调用可执行文件吗，怎么把可执行文件放到手机上，让手机执行啊？谢谢

**Comment by LDOUBLEV** [comment]
> 最后一步不还是在linux下面调用可执行文件吗，怎么把可执行文件放到手机上，让手机执行啊？谢谢

adb push 已经把可执行文件push到手机上了，adb shell 打开的相当于你手机的终端。
