### ISSUE TITLE
可以开源EasyEdge APP的代码吗？想研究一下实时识别

### ISSUE THREAD

**Issue by guoge6** [PaddlePaddle/PaddleOCR#5270]
![image](https://user-images.githubusercontent.com/95969602/149651567-7c5532ae-88d6-4954-a25c-ff5bee7cdb1c.png)

**Comment by MissPenguin** [comment]
android demo代码：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/android_demo

**Comment by guoge6** [comment]
> android demo代码：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/android_demo

不动脑子？
