### ISSUE TITLE
内网的情况下 怎么执行这一步

### ISSUE THREAD

**Issue by pipijiev12** [PaddlePaddle/PaddleOCR#5274]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux （centos7）
- 版本号/Version：Paddle：  2.2.0.2
- PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

只能链接内网 连接不了外网

**Comment by pipijiev12** [comment]
在本地离线执行脚本，运行 ocr = PaddleOCR(use_angle_cls=True, lang="ch") 命令时报错：Failed to establish a new connection: [Errno -2] Name or service not known
请问是否每次运行该命令都需要链接网络服务器，或是能够首次连接执行后，之后均离线本地运行

**Comment by bnu-bily** [comment]
如果没有模型，第一次会尝试联网下载模型，有模型就不需要下载了，以下三种方式可以解决：
#1、ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}', cls_model_dir='{your_cls_model_dir}')
#2、~/.paddleocr/{your_version}/ocr/cls/ch_ppocr_mobile_v2.0_cls_infer
#~/.paddleocr/{your_version}/ocr/det/ch/ch_PP-OCRv2_det_infer
#~/.paddleocr/{your_version}/ocr/rec/ch/ch_PP-OCRv2_rec_infer
#3、在一台有网的电脑docker安装，正常下载访问后，再打包成docker镜像，到内网部署

**Comment by bnu-bily** [comment]
> 
如果没有模型，第一次会尝试联网下载模型，首次连接执行后（也就是模型下载完），之后均离线本地运行；也可以自己手动下载模型，放到指定位置

**Comment by yiyedaren** [comment]
手动下载模型，放到指定位置，然后运行命令还是会去下载，咋整哦？

**Comment by yiyedaren** [comment]
正常下载访问后，再打包成docker镜像，到内网部署后还是需要下载？咋弄哦？
