### ISSUE TITLE
使用其他backbone

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/PaddleOCR#5275]
paddleocr 识别模块中，内置的backbone, 是在垂直方向上降采样5次， 水平方向降采样2次，使得最终的宽度变为原来的1/4， 高度变为原来的1/32， 如果换用其他backbone，( 如DenseNet ) 的话，也是采用这种采样方式比较好么？至于水平方向什么时候降采样，也是在模型获取输入后降采样一次，然后在backbone最后的池化层降采样一次么？

**Comment by LDOUBLEV** [comment]
下采样顺序视情况而定吧，建议还是用垂直方向上降采样5次， 水平方向降采样2次

采样点可以参考mv3的改动：
https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/backbones/rec_mobilenet_v3.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48-L64

**Comment by Zhangts98** [comment]
> 下采样顺序视情况而定吧，建议还是用垂直方向上降采样5次， 水平方向降采样2次
> 
> 采样点可以参考mv3的改动： https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/backbones/rec_mobilenet_v3.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48-L64
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L44

好的， 非常感谢。

**Comment by Amanda-Barbara** [comment]
@LDOUBLEV 你好，rknn不支持DepthwiseSeparable模块中的ConvBNLayer层参数stride(p1, p2) p1与p2不一致算子，这样涉及到修改网络结构，我看了下stride(p1, p2)中p1与p2不一致的情况是为了做下采样的操作，请问我想保持p1与p2相等的情况下，该如何修改DepthwiseSeparable模块或者更上层模块的参数呢？

**Comment by nissansz** [comment]
densenet 和 resnet34 对比，哪个准确率高？

**Comment by nissansz** [comment]
> > 下采样顺序视情况而定吧，建议还是用垂直方向上降采样5次， 水平方向降采样2次
> > 采样点可以参考mv3的改动： https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/backbones/rec_mobilenet_v3.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48-L64
> > 
> > https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L44
> 
> 好的， 非常感谢。

要怎样修改才能训练densenet? 可以分享配置文件合修改后的py文件吗？
