### ISSUE TITLE
关于DB检测

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5281]
![image](https://user-images.githubusercontent.com/87969070/149854007-e378c3d8-78b7-4834-84e4-7ef639e29198.png)
请问一下，我Label的时候标记了四个框，但是最后训练输出的结果是一个框，请问是怎么回事呢？

**Comment by andyjpaddle** [comment]
可以调小一下`unclip_ratio`参数看看

**Comment by 18362890185** [comment]
> 可以调小一下`unclip_ratio`参数看看

还是定位不够准确，因为我i训练的字符存在位置、大小都有所变化

**Comment by YY007H** [comment]
数据集太少了吧，要么训练的不对，检查下DetResizeForTest配置，最好使用resize_long

**Comment by 18362890185** [comment]
> 数据集太少了吧，要么训练的不对，检查下DetResizeForTest配置，最好使用resize_long

你得意思是设置为960，max? 能否请问一下，设置该参数的原因？

**Comment by YY007H** [comment]
> > 数据集太少了吧，要么训练的不对，检查下DetResizeForTest配置，最好使用resize_long
> 
> 你得意思是设置为960，max? 能否请问一下，设置该参数的原因？

固定输入尺寸比随机输入尺寸效果好
