### ISSUE TITLE
服务端2.0 模型进行推理 predict_det 内存泄漏

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#5283]
- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：
Paddle：paddlepaddle-gpu = 2.2.1.post111  
PaddleOCR：2.4 版本代码 22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896
- 运行指令/Command Code：
python3 tools/infer/predict_det.py --image_dir="/datasetocr/origin_picture/20210619" --det_model_dir="/datasetocr/dudaizhong/inference/ch_ppocr_server_v2.0_det_infer"  --use_gpu=True --use_mp=True --total_process_num=10 --det_db_unclip_ratio=2.0

- 完整报错/Complete Error Message：
内存不足被 kill，没有明显的报错信息。

问题描述：
服务端2.0 模型进行推理 predict_det 内存泄漏，在检测图片在 1W5 的时候 内存 48G 就不够了。

**Comment by andyjpaddle** [comment]
可否给一下你的机器详细配置？

**Comment by ddz-mark** [comment]
系统：ubuntu18.04，48G 内存
gpu 环境：2x32G 显寸，cuda version 11.1、cudnn 8.0.4
还需要什么配置信息？

**Comment by LDOUBLEV** [comment]
建议用cudnn8.1， cudnn8.0版本上可能会出现内存泄漏

另外建议用高版本的paddle，推荐2.2.1

**Comment by ddz-mark** [comment]
> 建议用cudnn8.1， cudnn8.0版本上可能会出现内存泄漏
> 
> 另外建议用高版本的paddle，推荐2.2.1

有个疑问，目前使用 cudnn8.0.4 + paddlepaddle2.2.1.post111，在识别模型推理 predict_rec 是可以大规模数据跑的。但是在检测模型 predict_det 数据量到达了1.5W会内存 kill， 这个能证明环境没有问题吗？

**Comment by YY007H** [comment]
你开了total_process_num=10个进程，太多了，并行跑很有可能爆内存

**Comment by ddz-mark** [comment]
> 你开了total_process_num=10个进程，太多了，并行跑很有可能爆内存

我尝试了一遍，total_process_num=5，2，都会出现内存泄漏的情况。进程数量跟内存泄漏应该没有关系吧，我遇到的情况属于样本推理时，内存没有被回收，随着样本越多内存占用越大，然后就 Kill。

**Comment by LDOUBLEV** [comment]
> 有个疑问，目前使用 cudnn8.0.4 + paddlepaddle2.2.1.post111，在识别模型推理 predict_rec 是可以大规模数据跑的。但是在检测模型 predict_det 数据量到达了1.5W会内存 kill， 这个能证明环境没有问题吗？

识别的输入较小，占用内存不高，检测模型的输入很大，占用显存更高

**Comment by ddz-mark** [comment]
> 

我还是不是很理解，内存占用高，但是推理阶段是按照单样本预测的啊，只要正常回收内存不就没有问题嘛？识别可以大规模跑，不是证明内存没有泄漏吗？

**Comment by YY007H** [comment]
训练可以理解为单进程，你这是多进程，感觉你应该是显存爆了，不是内存爆了，可以把报错贴出来看看吗

**Comment by ddz-mark** [comment]
感谢各位大佬，没有明显的报错信息，predict_det 脚本被自动 kill, 查看监控（下图）确实是内存被占满了。多进程会在一开始预测的时候占用大量内存，但是后续的内存却一直在增加。显存的监控并没有异常，确定是由于内存溢出。
![image](https://user-images.githubusercontent.com/18033495/155252878-6a55d30f-50a9-43dc-83a0-4ef556b6ad07.png)

**Comment by renoyuan** [comment]
> 

我也遇到内存泄露，试试大佬这个方案

**Comment by renoyuan** [comment]
> 建议用cudnn8.1， cudnn8.0版本上可能会出现内存泄漏
> 
> 另外建议用高版本的paddle，推荐2.2.1

我也遇到内存泄露，试试大佬这个方案

**Comment by YachaoDong** [comment]
> 没有明显的报错信息，predict_det 脚本被自动 kill, 查看监控（下图）确实是内存被占满了。多进程会在一开始预测的时候占用大量内存，但是后续的内存却一直在增加。显存的监控并没有异常，确定是由于内存溢出。

请问这个最后解决了吗？

**Comment by ddz-mark** [comment]
> > 没有明显的报错信息，predict_det 脚本被自动 kill, 查看监控（下图）确实是内存被占满了。多进程会在一开始预测的时候占用大量内存，但是后续的内存却一直在增加。显存的监控并没有异常，确定是由于内存溢出。
> 
> 请问这个最后解决了吗？

更换环境、python 我从3.6 更新到3.7，paddle 更新到最新的。目前这个问题没有出现了
