### ISSUE TITLE
DB模型检测效果

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5287]
![image](https://user-images.githubusercontent.com/87969070/150046711-47ed316c-5811-48be-aa99-a8dfb333d588.png)
![image](https://user-images.githubusercontent.com/87969070/150046743-39f82cff-7565-4da1-86c4-0d896e54881f.png)
请问一下，DB模型对这种字符大小变化的检测效果不好吗？训练过程中loss始终下不去，调整了多个epochs和lr 请问有什么优化方案，调整threshold和box_threshold值效果也很差

**Comment by yjhtc007** [comment]
做的单字检测还是多字检测，检测图片数据就这么大吗？

**Comment by 18362890185** [comment]
> 做的单字检测还是多字检测，检测图片数据就这么大吗？
多字检测，这一行都要检测 我训练过单个字符、破折号划分为四个区域的情况、还有整个字符串区域的情况，效果都不是很理想

**Comment by 18362890185** [comment]
> 做的单字检测还是多字检测，检测图片数据就这么大吗？
![image](https://user-images.githubusercontent.com/87969070/150050178-dc66b976-0723-45c8-927c-709c231ff2f8.png)
图片这样的

**Comment by yjhtc007** [comment]
> > 做的单字检测还是多字检测，检测图片数据就这么大吗？
> > ![image](https://user-images.githubusercontent.com/87969070/150050178-dc66b976-0723-45c8-927c-709c231ff2f8.png)
> > 图片这样的

感觉可以试一试EAST模型

**Comment by 18362890185** [comment]
但是目前部署的只支持DB模型

**Comment by LDOUBLEV** [comment]
训练的时候强制将短边resize到640，控制输入的分辨率
