### ISSUE TITLE
aarch64架构开发板的执行文件编译

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleOCR#529]
想在linux开发板上使用，架构为arm cortex-A的aarch64，请问如何交叉编译出可执行文件呢？
尝试了 https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md 中的armv8，编译的程序无法在开发板上运行，应该还是因为armv8和aarch64有区别。

**Comment by littletomatodonkey** [comment]
你好，PaddleLite支持的硬件列表在这里：https://paddle-lite.readthedocs.io/zh/latest/introduction/support_hardware.html
看着应该没有aarch64的
