### ISSUE TITLE
VisualDL show nothing

### ISSUE THREAD

**Issue by captainfffsama** [PaddlePaddle/PaddleOCR#5292]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04#cuda11.2
- 版本号/Version：Paddle：  
      paddlepaddle-gpu      2.2.1.post112
      visualdl              2.2.3
      paddleocr          2.4
- 运行指令/Command Code： `visualdl --logdir ./log --host 0.0.0.0 `
- 完整报错/Complete Error Message：brower page show `No visualized data.`

按照教程训练DBNet,使用的config是`det_res18_db_v2.0.yml`,已经设置`use_visualdl: True`,在log目录下已有:
`endpoints.log  workerlog.0  workerlog.1  workerlog.2  workerlog.3  workerlog.4  workerlog.5  workerlog.6  workerlog.7`,打开 Visualdl 之后,页面显示`No visualized data.`.

follow the tutorial train dbnet,use `det_res18_db_v2.0.yml` as config file,set `use_visualdl: True`,and we can get `endpoints.log  workerlog.0  workerlog.1  workerlog.2  workerlog.3  workerlog.4  workerlog.5  workerlog.6  workerlog.7` in log dir. But open Visualdl,page just show `No visualized data.`

**Comment by acerylj** [comment]
Try checking your PaddleOCR/output/{output_file_name}/vdl directory, a vdl file should exists, if yes, use that directory for your --logdir.

**Comment by Helloiamwin** [comment]
It would help if you changed the 'use_visualdl' param in .yml file to True. 
Run: visualdl --logdir <folder_path>.
Fact: The visualdl tool can run in real-time, parallel with the training process.
