### ISSUE TITLE
导出推断模型失败

### ISSUE THREAD

**Issue by zhuangzheng** [PaddlePaddle/PaddleOCR#5293]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.2.1  PaddleOCR：2.3.0.2 问题相关组件/Related components：
- 运行指令/Command Code：tools/export_model.py
- 完整报错/Complete Error Message：
ScannerError: mapping values are not allowed here
  in "../ppstructure/inference/rec_chinese_common_train_v2.0.yml", line 150, column 66

将中文识别训练模型导出为推断模型的时候失败

**Comment by tink2123** [comment]
请提供下你的模型导出命令，是否正确加载了预训练模型，且指定了 `save_inference_dir` 字段
