### ISSUE TITLE
关于长字符串检测

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5297]
![image](https://user-images.githubusercontent.com/87969070/150116696-130f7ade-9dd0-44b2-995d-dff55318737b.png)
请问一下，我将整个字符Label成一个检测框，理论上应该是较好检测的，但是进行DB检测训练的时候，Hmean始终很低，i想请问一下，有什么改进措施吗？分开进行label时，Hmean会有所提高，但是还是达不到理想值

**Comment by yangdeqieyingli** [comment]
您好，请问您的这种钢印字符，检测和识别的效果好不好
