### ISSUE TITLE
Convert OCR recognition models to TensorRT

### ISSUE THREAD

**Issue by Auth0rM0rgan** [PaddlePaddle/PaddleOCR#5298]
Hello,

I have trained the PaddelOCR with my own data and now I want to load it with TensorRT in order to speed up the process. My question is how can I convert paddleOCR model to tensorRT? is there any documentation that I can follow? or does paddel has a framework like TensorRT to speed UP the inference time?

Thanks

**Comment by tink2123** [comment]
Hi Auth0rM0rgan,

There is currently no official document describing how to convert to a TensorRT model. Maybe you can try to use Paddle  Inference, which supports enabling TensorRT prediction to seep up process.

You can follow these steps:

1. install Paddle with TensorRT

Find the Paddle  package of the specified version: [download_link](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python)
for example:
```
wget  https://paddle-wheel.bj.bcebos.com/with-trt/2.1.1-gpu-cuda10.2-cudnn8.1-mkl-gcc8.2/paddlepaddle_gpu-2.1.1-cp37-cp37m-linux_x86_64.whl
pip3.7 install -U paddlepaddle_gpu-2.1.1-cp37-cp37m-linux_x86_64.whl
```

2. predict with TensorRT

```
python3 tools/infer/predict_rec.py \
    --image_dir="./doc/imgs_words/ch/word_4.jpg" \
    --rec_model_dir="./ch_PP-OCRv2_rec_infer/" \
    --use_tensorrt=True

```

**Comment by Auth0rM0rgan** [comment]
@tink2123, Thanks for reply! I followed your instruction but Im getting the following error. Does TensorRT install with the link you provide or i need to install it separately? Do you have any idea what is the problem?

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0120 12:23:13.134073 29563 tensorrt.cc:56] You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
The TensorRT that Paddle depends on is not configured correctly.
  Suggestions:
  1. Check if the TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;%PATH%`
  - Mac: set  DYLD_LIBRARY_PATH by `export DYLD_LIBRARY_PATH=...`
Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 414, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_rec.py", line 380, in main
    text_recognizer = TextRecognizer(args)
  File "tools/infer/predict_rec.py", line 74, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/home//PaddleOCR/tools/infer/utility.py", line 303, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
  [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)

```

This is the command:

```
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./ch_ppocr_mobile_v2.0_rec_slim_infer/" --use_tensorrt=True
```

**Comment by Auth0rM0rgan** [comment]
@tink2123, Another question, is only CRNN can be run with tensorRT or other recognition models are also support TensorRT??

Thanks!

**Comment by Auth0rM0rgan** [comment]
@tink2123, any idea how can I solve the error? I tried with new env but still getting the same error

**Comment by shekarneo** [comment]
@Auth0rM0rgan  How did you converted paddle models into trt engine?

**Comment by aafaqin** [comment]
> @tink2123, Thanks for reply! I followed your instruction but Im getting the following error. Does TensorRT install with the link you provide or i need to install it separately? Do you have any idea what is the problem?
> 
> ```
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W0120 12:23:13.134073 29563 tensorrt.cc:56] You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
> The TensorRT that Paddle depends on is not configured correctly.
>   Suggestions:
>   1. Check if the TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
>   2. Configure environment variables as follows:
>   - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
>   - Windows: set PATH by `set PATH=XXX;%PATH%`
>   - Mac: set  DYLD_LIBRARY_PATH by `export DYLD_LIBRARY_PATH=...`
> Traceback (most recent call last):
>   File "tools/infer/predict_rec.py", line 414, in <module>
>     main(utility.parse_args())
>   File "tools/infer/predict_rec.py", line 380, in main
>     text_recognizer = TextRecognizer(args)
>   File "tools/infer/predict_rec.py", line 74, in __init__
>     utility.create_predictor(args, 'rec', logger)
>   File "/home//PaddleOCR/tools/infer/utility.py", line 303, in create_predictor
>     predictor = inference.create_predictor(config)
> RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
>   [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)
> ```
> 
> This is the command:
> 
> ```
> python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./ch_ppocr_mobile_v2.0_rec_slim_infer/" --use_tensorrt=True
> ```

Did you find the solution?
