### ISSUE TITLE
是否提供c++接口版本？

### ISSUE THREAD

**Issue by fujianhai** [PaddlePaddle/PaddleOCR#53]
现在都是python接口版本，请问是否考虑提供c++接口版本？

**Comment by LDOUBLEV** [comment]
> 现在都是python接口版本，请问是否考虑提供c++接口版本？

欢迎关注，不会提供C++接口版本，C++的训练太过于繁琐，不过已经在准备开源PaddleOCR在端上的部署方案。

**Comment by fujianhai** [comment]
好的，谢谢， PaddleOCR在端上的部署方案，预计什么时候开源？

**Comment by MissPenguin** [comment]
端上部署已在排期中了，预计还需1-2周发布，欢迎持续关注哈。

**Comment by deep-practice** [comment]
端上的部署方案是指模型进一步压缩，还是只什么？

**Comment by fujianhai** [comment]
@deep-practice ，类似这个实际部署方案 https://paddlepaddle.org.cn/documentation/docs/zh/1.6/advanced_usage/deploy/inference/index_cn.html

**Comment by fujianhai** [comment]
@MissPenguin ,请问端上部署下周是否可用？
