### ISSUE TITLE
求开启服务部署（HubServing）方式的Python代码

### ISSUE THREAD

**Issue by liudatutu** [PaddlePaddle/PaddleOCR#530]
说明文档中介绍的用hub开启http服务，用的的命令行方式，即hub serving start -m ocr_system ........；
请问大牛有没有调用paddlehub包的Python脚本启动的代码。
万分感谢啊

**Comment by littletomatodonkey** [comment]
hub serving是通过命令行启动的，如果希望在python中调用的话，你可以在python中使用`os.system("your command")`启动

**Comment by liudatutu** [comment]
@littletomatodonkey 想看看hub启动是怎么运作的，用到哪些文件，有demo么？

**Comment by grasswolfs** [comment]
> @littletomatodonkey 想看看hub启动是怎么运作的，用到哪些文件，有demo么？
hub serving也是开源的，可以看源码了解哈
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/paddlehub/serving
