### ISSUE TITLE
Assertion error with Curved Text Detection

### ISSUE THREAD

**Issue by SilverSelf** [PaddlePaddle/PaddleOCR#5300]
Hello, I hope you can help me.

I am trying to test the various detection methods outlined here:
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/inference_en.md
I set up the different models using the guidelines in the link above and wrote a script to test a sample of 50 custom images. My script works fine using DB, and EAST; and SAST without curved text detection, using: det_algorithm='SAST', det_sast_polygon=False

Setting det_sast_polygon=True however, nets me an assertion error outlined below.

- 系统环境/System Environment：Ubuntu 64bit
- 版本号/Version：Paddle：2.1.3  PaddleOCR：2.3  问题相关组件/Related components：no GPU
- 运行指令/Command Code：

from paddleocr import PaddleOCR, draw_ocr
from PIL import Image
import argparse

ocr = PaddleOCR(use_angle_cls=True, lang='en', use_gpu=False, det_model_dir="./PaddleOCR-release-2.3/inference/det_sast_tt/", det_algorithm='SAST', det_sast_polygon=True)

for i in range(1, 50):  # setup for the 50 images
    imgNumber = '00000{}' .format(i)
    if len(imgNumber) == 7:
        imgNumber = imgNumber[1:]
    img_path = './testimg/50imgs/{}-color.png' .format(imgNumber)

    result = ocr.ocr(img_path, cls=True)
    image = Image.open(img_path).convert('RGB')

    boxes = [line[0] for line in result]
    txts = [line[1][0] for line in result]
    scores = [line[1][1] for line in result]
    im_show = draw_ocr(image, boxes, txts, scores, font_path='./ppocr_img/fonts/simfang.ttf')
    im_show = Image.fromarray(im_show)
    im_show.save('result_SAST_curved_{}.jpg' .format(i))

- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "50imgsSASTcurved.py", line 13, in <module>
    result = ocr.ocr(img_path, cls=True)
  File "/home/armin/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 350, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/armin/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 72, in __call__
    img_crop = get_rotate_crop_image(ori_im, tmp_box)
  File "/home/armin/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 561, in get_rotate_crop_image
    assert len(points) == 4, "shape of points must be 4*2"
AssertionError: shape of points must be 4*2

I would appreciate any help in resolving what's causing this issue, thank you.

**Comment by WenmuZhou** [comment]
Curved text needs to use cv.minAreaRect() to get the bounding rectangle first, and then crop it，just add the corresponding code to this line https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/tools/infer/predict_system.py#L77

**Comment by SilverSelf** [comment]
Thank you for your answer.

If I understand you correctly, at this stage the arrays contained within dt_boxes have more than 4 points and need to be turned into rectangles to be parsed to the text recognition.
I tried to call cv.minAreaRect() directly on to one of the point lists using:
rect = cv2.minAreaRect(dt_boxes[0])
at the line you linked to.

This however yields this error:
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-zeowd5_m/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

Is there some sort of typing mismatch? Can you tell me how dt_boxes should be handled to be accepted by cv2.minAreaRect()

**Comment by Jeck-Liu-Create** [comment]
我找到了关于这个问题的找到了解决方案，下面是我修改的代码：
https://github.com/PaddlePaddle/PaddleOCR/blob/fe42c835930e3b3b965b1c416b7c02aeb1fe7746/tools/infer/predict_system.py#L66
```
    def __call__(self, img, image_file, cls=True):

        ori_im = img.copy()
        dt_boxes, elapse = self.text_detector(img)
        # print(dt_boxes)

        logger.debug("dt_boxes num : {}, elapse : {}".format(
            len(dt_boxes), elapse))
        if dt_boxes is None:
            return None, None
        img_crop_list = []

        dt_boxes = sorted_boxes(dt_boxes)

        for bno in range(len(dt_boxes)):
            tmp_box = copy.deepcopy(dt_boxes[bno])

            tmp_box = np.array(tmp_box, dtype=np.float32)
            tmp_box = cv2.minAreaRect(tmp_box)

            points = sorted(list(cv2.boxPoints(tmp_box)), key=lambda x: x[0])
            index_1, index_2, index_3, index_4 = 0, 1, 2, 3
            if points[1][1] > points[0][1]:
                index_1 = 0
                index_4 = 1
            else:
                index_1 = 1
                index_4 = 0
            if points[3][1] > points[2][1]:
                index_2 = 2
                index_3 = 3
            else:
                index_2 = 3
                index_3 = 2
            box = [
                points[index_1], points[index_2], points[index_3], points[index_4]
            ]

            center = np.array(
                [points[index_1].tolist(), points[index_2].tolist(), points[index_3].tolist(), points[index_4].tolist()]
                , dtype="float32")

            print(box)
            print(type(box))

            img_crop = get_rotate_crop_image(ori_im, box, center, image_file)
            img_crop_list.append(img_crop)
        if self.use_angle_cls and cls:
            img_crop_list, angle_list, elapse = self.text_classifier(
                img_crop_list)
            logger.debug("cls num  : {}, elapse : {}".format(
                len(img_crop_list), elapse))

        rec_res, elapse = self.text_recognizer(img_crop_list)
        logger.debug("rec_res num  : {}, elapse : {}".format(
            len(rec_res), elapse))
        if self.args.save_crop_res:
            self.draw_crop_rec_res(self.args.crop_res_save_dir, img_crop_list,
                                   rec_res)
        filter_boxes, filter_rec_res = [], []
        for box, rec_reuslt in zip(dt_boxes, rec_res):
            text, score = rec_reuslt
            if score >= self.drop_score:
                filter_boxes.append(box)
                filter_rec_res.append(rec_reuslt)
        return filter_boxes, filter_rec_res

```
以及修改了这里
https://github.com/PaddlePaddle/PaddleOCR/blob/fe42c835930e3b3b965b1c416b7c02aeb1fe7746/tools/infer/predict_system.py#L151

`dt_boxes, rec_res = text_sys(img, image_file)`

同时对应的`get_rotate_crop_image`的修改
https://github.com/PaddlePaddle/PaddleOCR/blob/fe42c835930e3b3b965b1c416b7c02aeb1fe7746/tools/infer/utility.py#L581
```
def get_rotate_crop_image(img, points, crent, dir_img):
    '''
    img_height, img_width = img.shape[0:2]
    left = int(np.min(points[:, 0]))
    right = int(np.max(points[:, 0]))
    top = int(np.min(points[:, 1]))
    bottom = int(np.max(points[:, 1]))
    img_crop = img[top:bottom, left:right, :].copy()
    points[:, 0] = points[:, 0] - left
    points[:, 1] = points[:, 1] - top
    '''
    assert len(points) == 4, "shape of points must be 4*2"
    img_crop_width = int(
        max(
            np.linalg.norm(points[0] - points[1]),
            np.linalg.norm(points[2] - points[3])))
    img_crop_height = int(
        max(
            np.linalg.norm(points[0] - points[3]),
            np.linalg.norm(points[1] - points[2])))
    pts_std = np.float32([[0, 0], [img_crop_width, 0],
                          [img_crop_width, img_crop_height],
                          [0, img_crop_height]])
    M = cv2.getPerspectiveTransform(crent, pts_std)
    dst_img = cv2.warpPerspective(
        img,
        M, (img_crop_width, img_crop_height),
        borderMode=cv2.BORDER_REPLICATE,
        flags=cv2.INTER_CUBIC)

    savedir = r"/home/jeck/ocr/PaddleOCR/1780img/img/"
    dirset = os.path.join(savedir, os.path.basename(dir_img))
    print(os.path.basename(dir_img))

    dst_img_height, dst_img_width = dst_img.shape[0:2]
    if dst_img_height * 1.0 / dst_img_width >= 1.5:
        dst_img = np.rot90(dst_img)

    cv2.imwrite(dirset, dst_img)
    return dst_img
```
最终将待文字识别的图片保存到`/home/jeck/ocr/PaddleOCR/1780img/img/`
文字识别可以照常进行
