### ISSUE TITLE
Accuracy of NRTR

### ISSUE THREAD

**Issue by scopedog** [PaddlePaddle/PaddleOCR#5301]
Has anybody tried NRTR and compared to other methods like CRNN?
I will do some tests but currently our machines are all down due to our office move and would like to know from somebody.
I'm basically interested in Chinese recognition.

Thanks.

**Comment by WenmuZhou** [comment]
NRTR currently only has indicators in English, you can see this document https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/algorithm_overview.md

**Comment by scopedog** [comment]
All right. Thank you.
