### ISSUE TITLE
模型推理时间的环境

### ISSUE THREAD

**Issue by PROMISELVKR** [PaddlePaddle/PaddleOCR#5303]
![image](https://user-images.githubusercontent.com/55682710/150268845-ecd5e051-f078-4597-aefd-88f12c4ebf70.png)
您好！我想请问下这里所所说的17个框平均137ms的模型是用到了哪一个呢，以及是在cpu还是在gpu的环境下测试出来的呢

**Comment by WenmuZhou** [comment]
1. PP-OCR系列模型 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_slim_infer.tar  https://paddleocr.bj.bcebos.com/dygraph_v2.0/slim/ch_ppocr_mobile_v2.0_det_prune_infer.tar  https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_slim_infer.tar
2. gpu
