### ISSUE TITLE
分享下TensorRT能跑起来的配置

### ISSUE THREAD

**Issue by ioracion** [PaddlePaddle/PaddleOCR#5304]
使用的显卡：3060
要安装的软件：
1. PaddleOCR：2.4
2. cuda：11.2.2
3. cudnn：8.2.1
4. tensorRT：8.0.3.4
5. paddlepaddle-gpu：linux-cuda11.2-cudnn8.2-trt8-gcc8.2

然后代码里：
from paddleocr import PaddleOCR
ocr =PaddleOCR(**use_tensorrt=True**)
到这里会卡住一会儿，因为在做模型转换，正常的话不会有报错（废话）

**Comment by Auth0rM0rgan** [comment]
Im having same issue! Is there any documentation about executing PaddleOCR on TensorRT?? Im a bit confuse about how to run the PaddleOCR on TensorRT or  PaddleInference!

**Comment by ioracion** [comment]
> Im having same issue! Is there any documentation about executing PaddleOCR on TensorRT?? Im a bit confuse about how to run the PaddleOCR on TensorRT or PaddleInference!

I have no issue...just share how I succeeded. If you have the same card, i.e., RTX 3060, install the stuffs I mentioned,then set use_tensorrt parameter as True.

**Comment by Auth0rM0rgan** [comment]
Great! a question, did you install TensorRT separately or just installed PaddelOCR? also, is it possible to chose the FP for tesnorRT engine?

**Comment by ioracion** [comment]
Like I said, install 5 stuffs I mentioned above, and make sure the version is correct.

>is it possible to chose the FP for tesnorRT engine?

[This](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/utility.py#L39) might be what you want.

**Comment by Rm1n90** [comment]
Hi @ioracion, Thanks for sharing. Have you do a test to know how much speed you gain when TensorRT is True with when is not activate?
