### ISSUE TITLE
paddleocr模型转换成inference model报错问题

### ISSUE THREAD

**Issue by yangkk2019** [PaddlePaddle/PaddleOCR#5306]
按照官方文档下载east模型，运行export_model.py转inference model时一直报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 13014086: invalid continuation byte，请各位大神指导这种情况该如何解决呀？运行示例如下：
kk@ubuntu:/data/kk/python/ocr/PaddleOCR$ python tools/export_model.py -c ./configs/det/det_r50_vd_east.yml -o Global.checkpoints="/data/kk/python/ocr/PaddleOCR/models/east/det_r50_vd_east/best_accuracy" Global.save_inference_dir="/data/kk/python/ocr/PaddleOCR/inference/det_east"
W0120 15:41:06.662060  1259 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0120 15:41:06.667227  1259 device_context.cc:330] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/export_model.py", line 123, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    _ = load_dygraph_params(config, model, logger, None)
  File "/data/kk/python/ocr/PaddleOCR/ppocr/utils/save_load.py", line 95, in load_dygraph_params
    pre_best_model_dict = init_model(config, model, optimizer)
  File "/data/kk/python/ocr/PaddleOCR/ppocr/utils/save_load.py", line 62, in init_model
    opti_dict = paddle.load(checkpoints + '.pdopt')
  File "/home/kk/anaconda3/lib/python3.8/site-packages/paddle/framework/io.py", line 339, in load
    load_result = pickle.load(f) if six.PY2 else pickle.load(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 13014086: invalid continuation byte

**Comment by WenmuZhou** [comment]
我这边暂时没有复现你的问题，你的paddle版本是多少，我用的是2.2.1
![image](https://user-images.githubusercontent.com/12406017/150468893-b7e1a561-8ba0-4b77-abfb-6318d6293375.png)
