### ISSUE TITLE
如何用自己的数据制作LayoutXLM的XFUN格式数据呢？

### ISSUE THREAD

**Issue by Eric-Zhang1990** [PaddlePaddle/PaddleOCR#5308]
请问：想用自己的数据fine-tune  Layout XLM模型，但是不知道如何标注数据，请问有相应的工具或文档吗？谢谢

**Comment by yjhtc007** [comment]
> 请问：想用自己的数据fine-tune Layout XLM模型，但是不知道如何标注数据，请问有相应的工具或文档吗？谢谢

可以用labelme等标注软件加一些后处理代码进行标注

**Comment by Eric-Zhang1990** [comment]
> > 请问：想用自己的数据fine-tune Layout XLM模型，但是不知道如何标注数据，请问有相应的工具或文档吗？谢谢
> 
> 可以用labelme等标注软件加一些后处理代码进行标注

@yjhtc007   你有制作这种格式的数据集吗？ 能否把处理代码分享一下呢？谢谢

**Comment by WenmuZhou** [comment]
目前PPOCRLabel在开发ser的标注支持，敬请期待
