### ISSUE TITLE
加载预训练模型警告

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5309]
![image](https://user-images.githubusercontent.com/87969070/150301259-45c5a9c0-222a-4369-8bf2-04629f530dc3.png)
请问一下，head与加载预训练权重不一致，该如何设置？

**Comment by WenmuZhou** [comment]
不丢个详细的配置？

**Comment by 18362890185** [comment]
> 不丢个详细的配置？

![image](https://user-images.githubusercontent.com/87969070/150472509-fdd3fca2-6b30-42ec-8d48-e053acdfb9af.png)
![image](https://user-images.githubusercontent.com/87969070/150472578-f1d9ea9b-06a3-4004-a5c0-40ac1125f7cb.png)
下面是训练的txt文件

**Comment by WenmuZhou** [comment]
看报错，你给的预训练是检测的，重新下一个预训练看看

**Comment by 18362890185** [comment]
> 看报错，你给的预训练是检测的，重新下一个预训练看看 https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_mv3_none_bilstm_ctc_v2.0_train.tar

![image](https://user-images.githubusercontent.com/87969070/150483199-5cf583d0-39db-475d-a49c-0ef5399f52e7.png)
![image](https://user-images.githubusercontent.com/87969070/150483281-aba75c49-2b31-4d1b-82b4-d4af05690c36.png)
![image](https://user-images.githubusercontent.com/87969070/150483394-adace624-83c1-48d3-aff9-4167caeeecfc.png)
这是最新的，麻烦帮忙看一下

**Comment by WenmuZhou** [comment]
抱歉，我这边没有复现你的问题，我看你的配置也没啥问题，方便你的代码发我看下吗
