### ISSUE TITLE
paddleOCR 端侧部署有python 的demo么？

### ISSUE THREAD

**Issue by zhangyaobo** [PaddlePaddle/PaddleOCR#531]
请问官方？

**Comment by zhangyaobo** [comment]
目前只有一个c++demo

**Comment by littletomatodonkey** [comment]
这块没有demo，不过可以试着安装paddle，安装成功之后参考该文档基于Python进行部署，https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md

**Comment by littletomatodonkey** [comment]
如果你是在arm上跑的话，目前是不支持的

**Comment by zhangyaobo** [comment]
> 如果你是在arm上跑的话，目前是不支持的

是paddle 不支持arm么？

**Comment by littletomatodonkey** [comment]
c++的话是支持的，python目前还不支持

**Comment by zhangyaobo** [comment]
> c++的话是支持的，python目前还不支持

我可以在树莓派上安装paddlepaddle ，paddlehub 然后使用paddleocr 么？

**Comment by littletomatodonkey** [comment]
> > c++的话是支持的，python目前还不支持
> 
> 我可以在树莓派上安装paddlepaddle ，paddlehub 然后使用paddleocr 么？

不支持的，在树莓派这些端侧硬件上的话，推荐使用paddle-lite

**Comment by zhangyaobo** [comment]
能不能抓紧搞一个用python执行paddleocr 在树莓派的demo代码。我等着用。谢谢

**Comment by studiouspan** [comment]
> > > c++的话是支持的，python目前还不支持
> > 
> > 
> > 我可以在树莓派上安装paddlepaddle ，paddlehub 然后使用paddleocr 么？
> 
> 不支持的，在树莓派这些端侧硬件上的话，推荐使用paddle-lite

我在树莓派上编译了paddle-lite，但是依然不能讲ocr nb模型跑起来，我遇到的问题跟他一样，大佬可以帮看看吗？
https://github.com/PaddlePaddle/PaddleOCR/issues/1285#issue-753281970

**Comment by AllofLife** [comment]
您好 树莓派上支持python paddleocr了吗
