### ISSUE TITLE
cpu的c++版本推理速度问题

### ISSUE THREAD

**Issue by wumuyu9** [PaddlePaddle/PaddleOCR#5312]
paddleocr使用docker部署，用cpu的inference推理的c++版本det+rec，测试paddleocr库中自带的doc/imgs中的二十张图片，速度比python开两个进程版本还略慢

**Comment by littletomatodonkey** [comment]
超参数都是完全一样吗（mkldnn、线程数等等）？另外就是可以检查下检测的图像大小，看下预处理逻辑是否设置相同

**Comment by ethanas** [comment]
c++版本没有打开批量识别，最近提交的版本才打开了，python画框后用5个图片合成，然后给下一步。c++的版本是一张一张识别。新版本有加批量识别，但是我试的时候发现总会出现内存溢出,你可以看问题[5116](https://github.com/PaddlePaddle/PaddleOCR/issues/5116)
