### ISSUE TITLE
paddleocr 服务器端C++预测 部署

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5314]
paddleocr 服务器端C++预测 部署，文本检测算法可以用SAST吗，文本识别算法可以用SRN吗？谢谢！

**Comment by littletomatodonkey** [comment]
相关的c++处理代码没有集成，可能需要你自己根据python的代码适配集成一下哈

**Comment by llooper-dev** [comment]
@linkewei0580 我也正想测试下SAST，请问您集成好了吗？怎么做呢？
@littletomatodonkey  以后有没有在c++ demo支持SAST的计划呢？

**Comment by WenmuZhou** [comment]
> @linkewei0580 我也正想测试下SAST，请问您集成好了吗？怎么做呢？
> @littletomatodonkey  以后有没有在c++ demo支持SAST的计划呢？

没有哈
