### ISSUE TITLE
关于整串进行label Hmean始终为0

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5315]
![image](https://user-images.githubusercontent.com/87969070/150473203-981ac3a1-2b3e-4ec2-be97-d7058373a0d7.png)
请问您一下，我采用整串字符标注的方式进行，训练集图像200张，epochs2000次 学习率为0.0005 加载了预训练模型 ，但是Hmean始终为0，这是什么原因呢？

**Comment by littletomatodonkey** [comment]
这种应该是可以搞定的，可以检查下是否正确加载预训练模型，按说直接用预训练模型评估，精度也不会是0的
