### ISSUE TITLE
请问表格识别支持中文表格识别吗？自己训练的话数据集格式要是什么样的呢？

### ISSUE THREAD

**Issue by huangjianyi45902** [PaddlePaddle/PaddleOCR#5316]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
目前还不不支持中文表格识别，数据格式可以参考PubTabNet：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/table/README_ch.md#32-%E8%AE%AD%E7%BB%83
