### ISSUE TITLE
预测完成后无可视化结果

### ISSUE THREAD

**Issue by ElleryRambo** [PaddlePaddle/PaddleOCR#532]
![image](https://user-images.githubusercontent.com/35950414/90233834-4f289b80-de51-11ea-8df3-be7ea47b9515.png)
执行完命令，结果没有默认保存到inference_results文件夹，手动创建该文件夹后也无结果生成，请教是什么原因？

**Comment by littletomatodonkey** [comment]
你先试下
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs
这下面的图像呢？看下能否正常返回结果

**Comment by ElleryRambo** [comment]
> 你先试下
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs
> 这下面的图像呢？看下能否正常返回结果

也是不行呢

**Comment by littletomatodonkey** [comment]
你试下下面这个轻量级检测模型呢？替换你的det_model_dir试一下~

[det_mv3_182.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5073797/det_mv3_182.zip)

**Comment by ElleryRambo** [comment]
> 你试下下面这个轻量级检测模型呢？替换你的det_model_dir试一下~
> 
> [det_mv3_182.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5073797/det_mv3_182.zip)

还是不行...

**Comment by littletomatodonkey** [comment]
你好，麻烦发下具体的命令行和详细的日志吧

**Comment by ElleryRambo** [comment]
> 你好，麻烦发下具体的命令行和详细的日志吧

日志文件是在哪里？

**Comment by littletomatodonkey** [comment]
就是你预测的时候，输出的那些文本内容

**Comment by ElleryRambo** [comment]
![image](https://user-images.githubusercontent.com/35950414/90237413-d2002500-de56-11ea-81e6-90b90705eba0.png)
预测完没有输出文本呢

**Comment by littletomatodonkey** [comment]
你单独测一下识别和检测呢？predict_det.py和predict_rec.py

**Comment by ElleryRambo** [comment]
![image](https://user-images.githubusercontent.com/35950414/90237781-68cce180-de57-11ea-9b06-ef0e177f49a0.png)
也是没有输出...

**Comment by tink2123** [comment]
windows下的路径，用的应该是 “\” 而不是 “/”

**Comment by ElleryRambo** [comment]
> windows下的路径，用的应该是 “\” 而不是 “/”

改了也是不行...

**Comment by WenmuZhou** [comment]
@ElleryRambo 理论上predict_rec.py无论怎样都会有东西输出的，方便单步debug一下看看那一行退出的吗

**Comment by ElleryRambo** [comment]
用IDE测试跑了一下，可以出结果了...但命令行还是不行

**Comment by ElleryRambo** [comment]
![image](https://user-images.githubusercontent.com/35950414/90312908-c38b3980-df3a-11ea-8693-c7bfba67800b.png)
解决了，应该用python，不是python3，谢谢各位大佬...
