### ISSUE TITLE
一个关于训练的弱问题：零起步训练识别数字，需要多少张图片素材？

### ISSUE THREAD

**Issue by lededev** [PaddlePaddle/PaddleOCR#5324]
例如从0到1千万的阿拉伯数字，带负号或者不带，需要生成全部排列的两千万零一张图片来训练吗？
或者说随机选个1%，就能基本准确识别了？

**Comment by YY007H** [comment]
不需要，保持每个字符出现200次以上基本就没问题了

**Comment by YY007H** [comment]
不需要，保持每个字符出现200次以上基本就没问题了

**Comment by TonyWang2018** [comment]
我感觉实际上不是这样的啊，虽然只有阿拉伯数字，但是和背景图片的颜色，字体的颜色都有关系
