### ISSUE TITLE
文本识别转推理模型后识别不正确！

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleOCR#5325]
训练完之后用infer_rec.py预测是正常结果，但是用export_model.py就是错误的结果
这是我执行的附加参数：-c output/rec_chinese_lite_v2.0/config.yml -o Global.pretrained_model=output/rec_chinese_lite_v2.0/best_accuracy Global.save_inference_dir=./save_inference_dir
这是我用predict_rec.py预测的参数:--image_dir="2.bmp" --rec_model_dir="save_inference_dir" --rec_char_dict_path="train_data/labels.txt"
附加我上传了我训练的文件和一张图片例子

[output.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7921947/output.zip)

**Comment by xinyujituan** [comment]
@andyjpaddle @ZeyuChen @bingooo @karlhorky

**Comment by andyjpaddle** [comment]
我这里试了结果是正常的呢
![截屏2022-01-24 上午11 28 49](https://user-images.githubusercontent.com/87074272/150717451-099bbf94-fc10-4869-8311-a2f8e28e5960.png)

**Comment by xinyujituan** [comment]
> export_model

export_model.py这个预测的结果是正常的吗？

**Comment by andyjpaddle** [comment]
按照你给的模型和指令，运行没有问题呢

**Comment by xinyujituan** [comment]
infer_rec.py预测是正常的

**Comment by andyjpaddle** [comment]
export和predict都正常

**Comment by xinyujituan** [comment]
我重新安装下环境看下吧 很奇怪

**Comment by andyjpaddle** [comment]
> 我这里试了结果是正常的呢 ![截屏2022-01-24 上午11 28 49](https://user-images.githubusercontent.com/87074272/150717451-099bbf94-fc10-4869-8311-a2f8e28e5960.png)

这个就是我刚跑的结果，是没问题的

**Comment by xinyujituan** [comment]
> > 我这里试了结果是正常的呢 ![截屏2022-01-24 上午11 28 49](https://user-images.githubusercontent.com/87074272/150717451-099bbf94-fc10-4869-8311-a2f8e28e5960.png)
> 
> 这个就是我刚跑的结果，是没有问题的

https://github.com/PaddlePaddle/PaddleOCR是从这里下的源码测试的吗，我刚才已经重新安装了所有的最新环境和包还是不行。我预测的是：
E:\ProgramData\Anaconda3\envs\PaddleOCR\python.exe E:/python/PaddleOCR-release-2.4/tools/infer/predict_rec.py --image_dir=2.bmp --rec_model_dir=save_inference_dir --rec_char_dict_path=train_data/labels.txt
[2022/01/24 12:22:03] root INFO: Predicts of 2.bmp:('的图中减角右；', 0.607872)
export_model.py的路径是tools/export_model.py
predict_rec.py路径是tools/infer/predict_rec.py
实在是找不到问题了 我这边怎么也不正常呢

**Comment by andyjpaddle** [comment]
根据你给的模型和数据，我用以下命令运行是正常的
导出命令：
`python tools/export_model.py -c output/rec_chinese_lite_v2.0/config.yml -o Global.pretrained_model=output/rec_chinese_lite_v2.0/best_accuracy Global.save_inference_dir=./save_inference_dir`

预测命令：
`python tools/infer/predict_rec.py --image_dir="2.bmp" --rec_model_dir="save_inference_dir" --rec_char_dict_path="train_data/labels.txt"`

**Comment by xinyujituan** [comment]
可否提供下你的全部环境包版本 和文件工程 我这边返回就是错误的

**Comment by andyjpaddle** [comment]
就是官方的环境和代码，没有其他改动

**Comment by xinyujituan** [comment]
下面是我执行的结果 这真的是太奇怪了 不过我是win10







Microsoft Windows [版本 10.0.19044.1466]
(c) Microsoft Corporation。保留所有权利。

(PaddleOCR) E:\python\PaddleOCR-release-2.4>python tools/export_model.py -c output/rec_chinese_lite_v2.0/config.yml -o Global.pretrained_model=output/rec_chinese_lite_v2.0/best_accuracy Global.save_inference_dir=./save_inference_dir

W0124 14:15:11.399782 21332 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 11.2
W0124 14:15:11.539551 21332 device_context.cc:465] device: 0, cuDNN Version: 8.2.
[2022/01/24 14:15:28] root INFO: load pretrain successful from output/rec_chinese_lite_v2.0/best_accuracy
[2022/01/24 14:15:31] root INFO: inference model is saved to ./save_inference_dir\inference

(PaddleOCR) E:\python\PaddleOCR-release-2.4>python tools/infer/predict_rec.py --image_dir="2.bmp" --rec_model_dir="save_inference_dir" --rec_char_dict_path="train_data/labels.txt"
[2022/01/24 14:16:28] root INFO: Predicts of 2.bmp:('的图中减角右；', 0.607872)

(PaddleOCR) E:\python\PaddleOCR-release-2.4>

**Comment by xinyujituan** [comment]
下载的最新的paddle cuda=11.2  重新下载的官方代码和重新安装的新的conda环境测试的 依旧如此

**Comment by xinyujituan** [comment]
会不会跟window系统有关系呢

**Comment by andyjpaddle** [comment]
这些模型官方在发布前会在不同操作系统上进行测试，没问题后才会发布

**Comment by xinyujituan** [comment]
实在搞不明白为什么我这里会有问题，可否给我整个环境的txt我来复现你那边的情况看看能否正确？

**Comment by andyjpaddle** [comment]
我这边是Linux系统

**Comment by xinyujituan** [comment]
可否用win测试下 我怀疑是win系统的问题

**Comment by lededev** [comment]
我也遇到这个问题，相同图片，用tools/infer_rec.py识别正确，但是tools/export_model.py导出的rec模型识别失败。
我的系统是win11。

**Comment by lededev** [comment]
应该与windows系统无关，我用ubuntu 18.04在win11 wsl gpu模式下昨了同样的训练，问题相同。
单张图片用tools/infer_rec.py识别正确acc 0.998+，tools/export_model.py导出的模型干脆识别个错的结果。
我是从零开始训练的，没有用预训练模型。

**Comment by andyjpaddle** [comment]
> 应该与windows系统无关，我用ubuntu 18.04在win11 wsl gpu模式下昨了同样的训练，问题相同。 单张图片用tools/infer_rec.py识别正确acc 0.998+，tools/export_model.py导出的模型干脆识别个错的结果。 我是从零开始训练的，没有用预训练模型。

可否提供一下模型和数据，我这边测试一下

**Comment by xinyujituan** [comment]
我的yml 和样本 还有样本生成的py文件都上传在压缩包里了
链接：https://pan.baidu.com/s/1ceN93EvWTDlxJcaHPjtuaQ?pwd=vfpl 
提取码：vfpl 
--来自百度网盘超级会员V5的分享

**Comment by lededev** [comment]
> 
[rec_demo.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7930566/rec_demo.zip)
![cn00000065](https://user-images.githubusercontent.com/30518126/150910477-56806846-fd06-4f31-896f-908a5f15a9c9.jpg)

`tools/infer_rec.py`运行结果是 `代码   0.99992454`
export后用
`tools/infer/predict_rec.py`运行结果是 `是否发送错误报告软诈单  0.70778155`

运行环境Ubuntu 18.04 (Win11 WSL CUDA miniconda)

**Comment by lededev** [comment]
全部训练数据，8007张图片
[train_data.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7930655/train_data.zip)

**Comment by lededev** [comment]
换成6万张图的训练数据，配置文件换为ch_PP-OCRv2_rec_enhanced_ctc_loss.yml，问题依旧，导出的模型有问题，始终识别不对“代码”，哪怕直接运行tools/infer_rec.py的结果正确，acc达到0.9993204

**Comment by xinyujituan** [comment]
什么时候会有答复呢~

**Comment by lededev** [comment]
> 什么时候会有答复呢~

要是有办法直接使用Checkpoints训练模型就好了，暂时可以绕过这个转为推理模型的问题先用着。

**Comment by andyjpaddle** [comment]
> 换成6万张图的训练数据，配置文件换为ch_PP-OCRv2_rec_enhanced_ctc_loss.yml，问题依旧，导出的模型有问题，始终识别不对“代码”，哪怕直接运行tools/infer_rec.py的结果正确，acc达到0.9993204

按照你给的数据，按照以下指令进行测试
导出模型：
`python tools/export_model.py -c rec_demo/rec_mobile_pp-OCRv2/config.yml -o Global.pretrained_model=rec_demo/rec_mobile_pp-OCRv2/best_accuracy Global.save_inference_dir=rec_demo/rec_mobile_pp-OCRv2`
推理模型预测：
`python tools/infer/predict_rec.py --image_dir='rec_demo/train_data/cn/cn00000065.jpg' --rec_model_dir="rec_demo/rec_mobile_pp-OCRv2"`

测试结果如下图：
![截屏2022-01-27 上午10 15 11](https://user-images.githubusercontent.com/87074272/151280082-c167f04c-455a-4831-8dd1-041d8eaaa05f.png)

结果正确无误

**Comment by lededev** [comment]
@andyjpaddle 那么有可能是python版本的差异导致的吗？我的是3.9.7，请问你用的多少，以及其他环境信息，我想原样搭个环境试试。

**Comment by andyjpaddle** [comment]
我用的是Python3.7 CUDA10.2 cuDNN 7.6

**Comment by lededev** [comment]
找到原因了，并且能重新这个bug，附上截图，结论是这个bug是release/2.4引入的，用release/2.3就一切正常。
![image](https://user-images.githubusercontent.com/30518126/151291077-1ca9fc9b-a2de-4dba-8c45-2823bfbe78b1.png)

**Comment by xinyujituan** [comment]
> 找到原因了，并且能重现这个bug，附上截图。 结论是这个bug是release/2.4引入的，用release/2.3就一切正常。 ![image](https://user-images.githubusercontent.com/30518126/151291077-1ca9fc9b-a2de-4dba-8c45-2823bfbe78b1.png)

2.3版本果然没问题了，感谢大佬

**Comment by lededev** [comment]
@andyjpaddle 这种非常明显且可重现的严重bug，为啥着急关掉issue，2.4版相关修复代码提交了再关不迟吧？
或者其他分支有修复提交了？如果如此，还请备注一下。

**Comment by andyjpaddle** [comment]
2.4 版本修改了预测的resize逻辑，完全保持了原图的长宽比，不进行多余的padding。如果训练图片宽度都比较小，训练的时候resize到320，引入了过多的padding，会影响训练结果。可以通过修改训练shape，或者用2.3版本的代码进行预测。

**Comment by lededev** [comment]
@andyjpaddle 本案与预测无关吧，只是推理识别，并没有预测。
我给的可重现数据也非常单一，就两个字“代码”，相同训练模型，2.3识别正确，2.4识别错误。
用自动化脚本从2.3到2.4的git逐个commit checkout跑这个案例，就知道具体哪个commit引入的bug了

**Comment by andyjpaddle** [comment]
我这里说的预测就是推理识别

**Comment by lededev** [comment]
代码这两个字无论什么尺寸的图，始终不正确。
我认为问题不在图片resize到320上。

**Comment by andyjpaddle** [comment]
我们自己的模型在2.3和2.4上都可以正确识别

**Comment by lededev** [comment]
有没有可能是因为你模型的字典比较大，因模型中错误识别的占比小，所以问题不明显。
例如同一个模型，2.3和2.4的识别率结果是否完全一致，有这方面的测试用例吗？

**Comment by andyjpaddle** [comment]
你可以用一张尺寸为训练shape一致的图片在2.3和2.4版本分别进行测试一下识别结果

**Comment by lededev** [comment]
正如标题所示：文本识别转推理模型后识别不正确
2.4的用tools/infer_rec.py识别正确，但是tools/export_model.py导出的rec模型识别失败。
2.4导出的模型在2.3下识别正确。
因此我认为问题不应该在训练上，而是对导出的推理模型使用时，2.3和2.4有差异。

**Comment by andyjpaddle** [comment]
问题是不在训练上，2.3和2.4的差异也就是在推理时的resize不同处理，所以让你找一个图片shape和训练一致的进行推理识别测试（导出推理模型后的测试）

**Comment by deeplearningers** [comment]
我也遇到了，shit

**Comment by Charmnut1** [comment]
可以把predict_rec.py中的” imgW = int((32 * max_wh_ratio))“注释掉试试

**Comment by huanhuan-xiao** [comment]
我使用分别使用2.3  2.4  2.5推理模型放在其它其它版本的识别中效果还是特别差，数据集是有些是单个数字，都被识别成固定的汉字。直接没转换的模型识别效果就很好。你们按上面的版本转换都可以解决吗？

**Comment by andyjpaddle** [comment]
更新一下最新代码试试
