### ISSUE TITLE
表格识别出错

### ISSUE THREAD

**Issue by kjf4096** [PaddlePaddle/PaddleOCR#5327]
按照快速开始教程识别表格时，运行以下代码出错：
```
cd PaddleOCR/ppstructure

# 下载模型
mkdir inference && cd inference
# 下载超轻量级表格英文OCR模型的检测模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_det_infer.tar && tar xf en_ppocr_mobile_v2.0_table_det_infer.tar
# 下载超轻量级表格英文OCR模型的识别模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_rec_infer.tar && tar xf en_ppocr_mobile_v2.0_table_rec_infer.tar
# 下载超轻量级英文表格英寸模型并解压
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_structure_infer.tar && tar xf en_ppocr_mobile_v2.0_table_structure_infer.tar
cd ..
# 执行预测
python3 table/predict_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=../doc/table/table.jpg --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --rec_char_dict_path=../ppocr/utils/dict/en_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../output/table
```
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E0124 11:30:49.640303  2955 analysis_config.cc:91] Please compile with gpu to EnableGpu()
E0124 11:30:49.963620  2955 analysis_config.cc:91] Please compile with gpu to EnableGpu()
E0124 11:30:50.252456  2955 analysis_config.cc:91] Please compile with gpu to EnableGpu()
[2022/01/24 11:30:50] root INFO: [0/1] ../doc/table/table.jpg
[2022/01/24 11:30:54] root DEBUG: dt_boxes num : 79, elapse : 0.7976949214935303
Traceback (most recent call last):
  File "table/predict_table.py", line 221, in <module>
    main(args)
  File "table/predict_table.py", line 197, in main
    pred_html = text_sys(img)
  File "table/predict_table.py", line 88, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/aistudio/PaddleOCR/tools/infer/predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/aistudio/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 98, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/aistudio/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 69, in decode
    idx])])
IndexError: list index out of range

**Comment by andyjpaddle** [comment]
请参考 #5145

**Comment by kjf4096** [comment]
删掉--rec_char_dict_path=../ppocr/utils/dict/en_dict.txt 后，在aistudio里运行，还是出错：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E0124 11:59:30.743244  5055 analysis_config.cc:91] Please compile with gpu to EnableGpu()
E0124 11:59:31.071734  5055 analysis_config.cc:91] Please compile with gpu to EnableGpu()
E0124 11:59:31.366062  5055 analysis_config.cc:91] Please compile with gpu to EnableGpu()
[2022/01/24 11:59:31] root INFO: [0/1] ../doc/table/table.jpg
[2022/01/24 11:59:35] root DEBUG: dt_boxes num : 79, elapse : 0.8379902839660645
[2022/01/24 11:59:36] root DEBUG: rec_res num  : 79, elapse : 0.8438067436218262


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1642996776 (unix time) try "date -d @1642996776" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5055 (TID 0x7f39620f1700) from PID 0 ***]

**Comment by WenmuZhou** [comment]
能分享一下你的项目吗
