### ISSUE TITLE
1 是否支持验证集指标如MAP等对模型进行评估 2 能否使用自定义损失函数

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#5332]
训练后，验证集不知道在哪看指标。能否自定义损失函数对网络进行优化

**Comment by andyjpaddle** [comment]
1. 默认是支持对模型进行评估的
2. 也可以自定义损失函数进行优化

**Comment by xu-peng-7** [comment]
模型评估加了--eval参数只在训练完成后进行评估，怎么修改为每隔n个epoch进行评估

**Comment by xu-peng-7** [comment]
同时，中间验证的结果会保存在哪里？麻烦您了

**Comment by andyjpaddle** [comment]
你这边具体用的哪个模型？

**Comment by xu-peng-7** [comment]
版面分析里面的ppyolov2 文档里面没这个：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppstructure/layout/train_layoutparser_model.md

**Comment by andyjpaddle** [comment]
每隔n个epoch进行评估在这里设置，同时加入--eval参数： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/runtime.yml#L4

**Comment by xu-peng-7** [comment]
我训练了：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppstructure/layout/train_layoutparser_model_ch.md
修改自己的数据集为VOC数据集。 几个小问题，1：这个里面的 --eval 参数没说明，建议补充。 2 ：按照默认参数训练时间约4day，但是我加载了上次的best_model修改了学习率和更新策略，测试集，模型snapshot_epoch，训练时间就降到3h。我应该向那些方向排查原因 3：第二次训练的时候我加上了--eval参数，但使用输出-use_vdl，结果里只能看到最后一次验证的结果，默认的不是应该是1，有一个验证准确率的曲线

**Comment by andyjpaddle** [comment]
这里版面分析我们主要用了 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1) 里面的检测模型，具体的关于训练和测试有关的问题，可以到  [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1) repo 里去提问，他们会给你详细的解答
