### ISSUE TITLE
俄语系列，比如白俄罗斯，乌克兰的识别模型，c++的好像识别的不正确啊

### ISSUE THREAD

**Issue by kangshilei** [PaddlePaddle/PaddleOCR#5334]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
使用俄语系列的模型，识别的结果都不尽人意
- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.0
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：无

**Comment by kangshilei** [comment]
模型没做好还是怎么了，我是在github上面下载的ru_mobile_v2.0_rec_infer  识别模型，字典也是在github上下载的，但是识别就是不正确，差的太多

**Comment by andyjpaddle** [comment]
请提供一下详细的运行命令和结果信息

**Comment by kangshilei** [comment]
void CRNNRecognizer::Run(std::vector<std::vector<std::vector<int>>> boxes,
                         cv::Mat &img, Classifier *cls, std::vector<std::string> &ssWord) {
  cv::Mat srcimg;
  img.copyTo(srcimg);
  cv::Mat crop_img;
  cv::Mat resize_img;
  std::vector<std::string> sstr_res;
  std::cout << "The predicted text is :" << std::endl;
  int index = 0;
  for (int i = boxes.size() - 1; i >= 0; i--) 
  {
    crop_img = GetRotateCropImage(srcimg, boxes[i]);
    if (cls != nullptr) {
      crop_img = cls->Run(crop_img);
    }

    float wh_ratio = float(crop_img.cols) / float(crop_img.rows);

    this->resize_op_.Run(crop_img, resize_img, wh_ratio, this->use_tensorrt_);

    this->normalize_op_.Run(&resize_img, this->mean_, this->scale_,
                            this->is_scale_);

    std::vector<float> input(1 * 3 * resize_img.rows * resize_img.cols, 0.0f);

    this->permute_op_.Run(&resize_img, input.data());

    // Inference.
    auto input_names = this->predictor_->GetInputNames();
    auto input_t = this->predictor_->GetInputHandle(input_names[0]);
    input_t->Reshape({1, 3, resize_img.rows, resize_img.cols});
    input_t->CopyFromCpu(input.data());
    this->predictor_->Run();

    std::vector<float> predict_batch;
    auto output_names = this->predictor_->GetOutputNames();
    auto output_t = this->predictor_->GetOutputHandle(output_names[0]);
    auto predict_shape = output_t->shape();

    int out_num = std::accumulate(predict_shape.begin(), predict_shape.end(), 1,
                                  std::multiplies<int>());
    predict_batch.resize(out_num);

    output_t->CopyToCpu(predict_batch.data());

    // ctc decode
    std::vector<std::string> str_res;
    int argmax_idx;
    int last_index = 0;
    float score = 0.f;
    int count = 0;
    float max_value = 0.0f;

    for (int n = 0; n < predict_shape[1]; n++) {
      argmax_idx =
          int(Utility::argmax(&predict_batch[n * predict_shape[2]],
                              &predict_batch[(n + 1) * predict_shape[2]]));
      max_value =
          float(*std::max_element(&predict_batch[n * predict_shape[2]],
                                  &predict_batch[(n + 1) * predict_shape[2]]));

      if (argmax_idx > 0 && (!(i > 0 && argmax_idx == last_index))) {
        score += max_value;
        count += 1;
        str_res.push_back(label_list_[argmax_idx]);
		sstr_res.push_back(label_list_[argmax_idx]);//加的代码
      }
      last_index = argmax_idx;
    }
    score /= count;
    for (int i = 0; i < str_res.size(); i++) {
      std::cout << str_res[i];
    }
    std::cout << "\tscore: " << score << std::endl;
  }
}
![image](https://user-images.githubusercontent.com/87765811/150897875-8e62ba53-9c6b-4637-a6c8-ae38348130aa.png)

**Comment by kangshilei** [comment]
> 请提供一下详细的运行命令和结果信息


void CRNNRecognizer::Run(std::vector<std::vector<std::vector<int>>> boxes,
                         cv::Mat &img, Classifier *cls) {
  cv::Mat srcimg;
  img.copyTo(srcimg);
  cv::Mat crop_img;
  cv::Mat resize_img;
  std::vector<std::string> sstr_res;
  std::cout << "The predicted text is :" << std::endl;
  int index = 0;
  for (int i = boxes.size() - 1; i >= 0; i--) 
  {
    crop_img = GetRotateCropImage(srcimg, boxes[i]);
    if (cls != nullptr) {
      crop_img = cls->Run(crop_img);
    }

    float wh_ratio = float(crop_img.cols) / float(crop_img.rows);

    this->resize_op_.Run(crop_img, resize_img, wh_ratio, this->use_tensorrt_);

    this->normalize_op_.Run(&resize_img, this->mean_, this->scale_,
                            this->is_scale_);

    std::vector<float> input(1 * 3 * resize_img.rows * resize_img.cols, 0.0f);

    this->permute_op_.Run(&resize_img, input.data());

    // Inference.
    auto input_names = this->predictor_->GetInputNames();
    auto input_t = this->predictor_->GetInputHandle(input_names[0]);
    input_t->Reshape({1, 3, resize_img.rows, resize_img.cols});
    input_t->CopyFromCpu(input.data());
    this->predictor_->Run();

    std::vector<float> predict_batch;
    auto output_names = this->predictor_->GetOutputNames();
    auto output_t = this->predictor_->GetOutputHandle(output_names[0]);
    auto predict_shape = output_t->shape();

    int out_num = std::accumulate(predict_shape.begin(), predict_shape.end(), 1,
                                  std::multiplies<int>());
    predict_batch.resize(out_num);

    output_t->CopyToCpu(predict_batch.data());

    // ctc decode
    std::vector<std::string> str_res;
    int argmax_idx;
    int last_index = 0;
    float score = 0.f;
    int count = 0;
    float max_value = 0.0f;

    for (int n = 0; n < predict_shape[1]; n++) {
      argmax_idx =
          int(Utility::argmax(&predict_batch[n * predict_shape[2]],
                              &predict_batch[(n + 1) * predict_shape[2]]));
      max_value =
          float(*std::max_element(&predict_batch[n * predict_shape[2]],
                                  &predict_batch[(n + 1) * predict_shape[2]]));

      if (argmax_idx > 0 && (!(i > 0 && argmax_idx == last_index))) {
        score += max_value;
        count += 1;
        str_res.push_back(label_list_[argmax_idx]);
		
      }
      last_index = argmax_idx;
    }
    score /= count;
    for (int i = 0; i < str_res.size(); i++) {
      std::cout << str_res[i];
    }
    std::cout << "\tscore: " << score << std::endl;
  }

}
![150897875-8e62ba53-9c6b-4637-a6c8-ae38348130aa](https://user-images.githubusercontent.com/87765811/150898083-ea2b306f-f1ab-4bee-b8fc-08819f04df44.png)

**Comment by andyjpaddle** [comment]
确认一下字典是否使用正确

**Comment by kangshilei** [comment]
> 确认一下字典是否使用正确

在GitHub上找的，确实没错，但是塞尔维亚的是可以识别到的

**Comment by wanghewen** [comment]
我这边试俄语字母还可以 但是数字好像都识别不出来啊。。

**Comment by kangshilei** [comment]
> 我试这个还可以啊，好像都识别不出来了。。

你好，你用的字典就是在dict里面的俄语字典吗

**Comment by XiaokangLei** [comment]
我试的俄语数字和字母完全识别不出来，都识别为俄语的那些字符了
