### ISSUE TITLE
有关paddleocr 中的max_side_len 参数咨询

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5337]
我在识别的时候由于图片的分辨率会不同，我识别的时候是roi截图，这个长和宽的比例有讲究吗?长和宽的长度我都是32的倍数，那这个max_side_len 应该怎么设置，应该会随着长的变化而变化吧，这个变化有规则或规律吗？谢谢！
max_side_len | int | 960 | 输入图像长宽大于960时，等比例缩放图像，使得图像最长边为960

**Comment by tink2123** [comment]
max_side_len 是文本检测时生效的参数，代表限制整图的最长边。如果超过960，会按比例缩小，使最长边为960。一般不需要修改，如果本身输入的图片分辨率很高，缩放后明显影响了预测结果，可以把这个值适当增大。

**Comment by linkewei0580** [comment]
我在检测的时候默认值为960，但我的图片分辨率一样，如果分辨为1920*1080的时候，我截图的时候会截右下角的是1024*320，如果我不改变max_side_len，效果很差，我识别的时候循环4次，max_side_len从512按32倍数一直增长到1024，这样效果会好一点，如果设置成960或1024效果很差。
