### ISSUE TITLE
关于PPOCRLabel

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5339]
请问一下，PPOCRLabel自动标注所使用的英文模型，对应的是哪一个？下载的推理模型都是mobile格式的，没办法使用inference推理
![image](https://user-images.githubusercontent.com/87969070/150898328-ef4f8d10-9c47-4a36-93f6-36a67747f857.png)

**Comment by lededev** [comment]
PPOCRLabel源代码里面这么用的
https://github.com/PaddlePaddle/PaddleOCR/blob/e1805ba7e261d68a39fa7ef5f0645114bc3eabe6/PPOCRLabel/PPOCRLabel.py#L117
https://github.com/PaddlePaddle/PaddleOCR/blob/e1805ba7e261d68a39fa7ef5f0645114bc3eabe6/PPOCRLabel/PPOCRLabel.py#L1974

**Comment by 18362890185** [comment]
> PPOCRLabel源代码里面这么用的
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e1805ba7e261d68a39fa7ef5f0645114bc3eabe6/PPOCRLabel/PPOCRLabel.py#L117
> 
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e1805ba7e261d68a39fa7ef5f0645114bc3eabe6/PPOCRLabel/PPOCRLabel.py#L1974

有相关模型信息吗？

**Comment by lededev** [comment]
运行它的时候，看启动时的日志信息，里面有模型的路径。

**Comment by 18362890185** [comment]
> e, cls=True

好的，谢谢您

**Comment by 18362890185** [comment]
> 运行它的时候，看启动时的日志信息，里面有模型的路径。

好的，谢谢您
