### ISSUE TITLE
异常标注数据所占总数比例的容忍度是多少？

### ISSUE THREAD

**Issue by Emiyans** [PaddlePaddle/PaddleOCR#5341]
假设我们现在想二次训练模型，然后我们针对100张训练图进行人工标注，人工标注亦难免有错漏，如果这100张图里面，有20张是夹杂错别字或者画框有错漏的，那以此数据进行二次训练的模型会不会越训练的效果越差？有没对训练数据异常的容忍度这类的参数定量说明？
意思就是说，如果标注数据有异常，那么训练后模型的能力体现是会提升还是下降，具体的判断逻辑有没一个描述哩？

**Comment by tink2123** [comment]
如果20%的比例都是错的，建议还是更新下数据。训练中低质量数据过多肯定会影响模型效果。
