### ISSUE TITLE
SER相关的问题

### ISSUE THREAD

**Issue by hudielv** [PaddlePaddle/PaddleOCR#5346]
尝试使用SER解决简历信息结构化问题，过程中遇到这样的问题：
目前ocr识别完为文本框，如果这个文本框包含多个SER的对象，如  26岁|男|5年工作经验， ocr识别完是一个文本框
那这里需要抽取的是年龄、性别、工作年限，那这几个需要不同的类别，那可以支持多标签的标注么？
                                                                         或者怎么拆分这个文本框？
也就是一个文本框包含多个类别，怎么办？

**Comment by WenmuZhou** [comment]
目前支持者单标签分类，你这种情况可以改一下后处理，目前后处理是选择文本框中预测最多的类别作为文本框的类别，可以根据自己的情况改一下， https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/vqa/vqa_utils.py#L331-L332

**Comment by hudielv** [comment]
好的，谢谢，那如果一个文本框包括多个标签，那拿出来之后，怎么拆分，这个后面paddle会考虑支持么

**Comment by WenmuZhou** [comment]
1. 目前暂无支持计划
2. 具体怎么划分你得自己研究一下了
