### ISSUE TITLE
安卓跑不起来

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#535]
报错信息
```java
E/Predictor:  Size of input shape should be: 3
```
![image](https://user-images.githubusercontent.com/29020213/90243777-1218d500-de62-11ea-8359-3417a6cac830.png)
下面是我的相关配置
![image](https://user-images.githubusercontent.com/29020213/90243884-442a3700-de62-11ea-85ce-714458786915.png)

**Comment by littletomatodonkey** [comment]
你先按照这篇文当把官网的demo跑通呢？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/android_demo/README.md

**Comment by mdddj** [comment]
> 你先按照这篇文当把官网的demo跑通呢？https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/android_demo/README.md

你好!demo可以跑的通,但是自己照着写不通,不知道上面报错是啥原因
