### ISSUE TITLE
ch_ppocr_server_v2.0_xx inference

### ISSUE THREAD

**Issue by Shiro-LK** [PaddlePaddle/PaddleOCR#5356]
Hello, 

I thank you for your great work, it is very helpful.
I am trying to use some inference weights from ch_ppocr_server_v2.0_xx weights. Unfortunately got some error message. Am I doing something wrong ? (see below the code). Moreover, where could I find the ppocrV2 model ?

- 系统环境/System Environment：python 3.7
- 版本号/Version：Paddle：  PaddleOCR：2.4
- 运行指令/Command Code：
```
from paddleocr import PaddleOCR,draw_ocr
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='en', rec_model_dir="paddle_weights/ch_ppocr_server_v2.0_rec_infer", det_model_dir="paddle_weights/ch_ppocr_server_v2.0_det_infer", cls_model_dir="paddle_weights/ch_ppocr_mobile_v2.0_cls_infer") # need to run only once to download and load model into memory
img_path = "fake-news.png"#"false/breathe.jpg"
result = ocr.ocr(img_path, cls=True)
#print(result)
for line in result:
    print(line)
```
- 完整报错/Complete Error Message：

> Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='paddle_weights/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='paddle_weights/ch_ppocr_server_v2.0_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], label_map_path='./vqa/labels/labels_ser.txt', lang='en', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_seq_length=512, max_text_length=25, min_subgraph_size=15, mode='structure', model_name_or_path=None, ocr_version='PP-OCRv2', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/ppocr/utils/en_dict.txt', rec_image_shape='3, 32, 320', rec_model_dir='paddle_weights/ch_ppocr_server_v2.0_rec_infer', save_crop_res=False, save_log_path='./log_output/', show_log=True, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
> [2022/01/25 13:11:58] root DEBUG: dt_boxes num : 6, elapse : 0.8812928199768066
> [2022/01/25 13:11:58] root DEBUG: cls num  : 6, elapse : 0.04192709922790527
> Traceback (most recent call last):
>   File "paddlepaddle.py", line 7, in <module>
>     result = ocr.ocr(img_path)
>   File "/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 379, in ocr
>     dt_boxes, rec_res = self.__call__(img, cls)
>   File "/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 88, in __call__
>     rec_res, elapse = self.text_recognizer(img_crop_list)
>   File "/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 371, in __call__
>     rec_result = self.postprocess_op(preds)
>   File "/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 96, in __call__
>     text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
>   File "/home/Shiro/anaconda3/envs/OCR/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 68, in decode
>     idx])])
> IndexError: list index out of range

**Comment by tink2123** [comment]
`ch_ppocr_server_v2.0_rec_infer` corresponds to a chinese dictionary, so the `lang` parameter needs to be set to `ch`:
```
from paddleocr import PaddleOCR,draw_ocr
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='ch', rec_model_dir="paddle_weights/ch_ppocr_server_v2.0_rec_infer", det_model_dir="paddle_weights/ch_ppocr_server_v2.0_det_infer", cls_model_dir="paddle_weights/ch_ppocr_mobile_v2.0_cls_infer") # need to run only once to download and load model into memory
img_path = "fake-news.png"#"false/breathe.jpg"
result = ocr.ocr(img_path, cls=True)
#print(result)
for line in result:
    print(line)
```


V2 models can be find at: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/models_list_en.md

**Comment by Shiro-LK** [comment]
@tink2123  Thank for your answer, it works !

I have a question regarding this model, does that mean english language is not well recognized? I have seen some image where there is almost no space between words. For instance the output could be : 


"Check yourselfeverymoringinafreshairenvironment"
