### ISSUE TITLE
about table recogonise

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#5357]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.2
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

    "Optimizer set error, {} should in state dict".format( var_name )
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict

**Comment by tink2123** [comment]
启动训练命令是什么？尝试使用 -o Global.pretrained_model 来加载参数
