### ISSUE TITLE
请问Style Text工具如何新增繁体中文支持？

### ISSUE THREAD

**Issue by ttys0001** [PaddlePaddle/PaddleOCR#5369]
StyleText当前只支持简体中文，英语和韩文。能否给出训练方法自行训练新语种呢？

或者能否考虑出一个支持繁体中文的模型？

另外十分感谢各位大佬的付出！

**Comment by littletomatodonkey** [comment]
你好，目前该模型还没有给出繁体中文的支持，暂时还没有提供训练代码，后续如果有时间的话，我们会整理训练代码并开源的，感谢你的关注~
