### ISSUE TITLE
识别不了一句话中的中文字符间的空格。微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5372]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：cmd
- 完整报错/Complete Error Message：识别不了一句话中的中文字符间的空格。微信nlanguage

**Comment by MissPenguin** [comment]
您好，可以贴一下图看看吗？另外，供参考：中文字符间一般标点分隔，所以训练数据中没什么带空格的数据，可能是这个导致空格识别效果较差。

**Comment by nissansz** [comment]
![9](https://user-images.githubusercontent.com/41010669/151505718-f6ea583e-9532-4256-8ba8-117a464e8bda.png)
可以加微信发给你？nlanguage

**Comment by nissansz** [comment]
又是办法可以加空格到训练数据中吗？

**Comment by nissansz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/4639  这个链接提到了一个 ocr_db_crnn.cc 文件的解决方法，不知道怎么用到python下来改善

**Comment by MissPenguin** [comment]
> #4639

按照训练教程进行操作即可：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/recognition.md

**Comment by MissPenguin** [comment]
> 有什么办法可以加空格到训练数据中吗？

按照训练教程进行操作即可：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/recognition.md
