### ISSUE TITLE
c++ 使用opencv的cvtColor 转为灰度图再进行识别，predictor->run运行崩溃

### ISSUE THREAD

**Issue by GamePlayerScript** [PaddlePaddle/PaddleOCR#5373]
//创建

config = new OCRConfig("config.txt");
config->PrintConfigInfo();
det = new DBDetector(config->det_model_dir, config->use_gpu, config->gpu_id,
    config->gpu_mem, config->cpu_math_library_num_threads,
    config->use_mkldnn, config->max_side_len, config->det_db_thresh,
    config->det_db_box_thresh, config->det_db_unclip_ratio,
    config->visualize, config->use_tensorrt, config->use_fp16);

//Classifier *cls = nullptr;
if (config->use_angle_cls == true) {
    cls = new Classifier(config->cls_model_dir, config->use_gpu, config->gpu_id,
        config->gpu_mem, config->cpu_math_library_num_threads,
        config->use_mkldnn, config->cls_thresh,
        config->use_tensorrt, config->use_fp16);
}

rec = new CRNNRecognizer(config->rec_model_dir, config->use_gpu, config->gpu_id,
    config->gpu_mem, config->cpu_math_library_num_threads,
    config->use_mkldnn, config->char_list_file,
    config->use_tensorrt, config->use_fp16);

//识别过程

cv::Mat srcimg = cvtColor(srcimg, srcimg , COLOR_RGB2GRAY);
std::vector<std::vector<std::vector<int>>> boxes;
det->Run(srcimg, boxes);

std::vector<std::string> str_res;
rec->Run(boxes, srcimg, cls, str_res);
det->Run(srcimg, boxes);这个函数内的this->predictor_->Run();会引起崩溃
版本是2.2

**Comment by WenmuZhou** [comment]
你好，目前模型只支持3通道的，在python预测是，灰度图也会被强制转成3通道进行预测
