### ISSUE TITLE
执行table 预测报错 

### ISSUE THREAD

**Issue by wuhongsheng** [PaddlePaddle/PaddleOCR#5375]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- mac 10.15
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 2.4
- 运行指令/Command Code：
python3 table/predict_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=../doc/table/table.jpg --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../output/table

- 完整报错/Complete Error Message：
[libprotobuf ERROR /home/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: data_type
Traceback (most recent call last):
  File "table/predict_table.py", line 221, in <module>
    main(args)
  File "table/predict_table.py", line 185, in main
    text_sys = TableSystem(args)
  File "table/predict_table.py", line 57, in __init__
    self.text_detector = predict_det.TextDetector(args) if text_detector is None else text_detector
  File "/Users/whs/PaddleOCR/tools/infer/predict_det.py", line 107, in __init__
    args, 'det', logger)
  File "/Users/whs/PaddleOCR/tools/infer/utility.py", line 303, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] (at /home/Paddle/paddle/fluid/framework/tensor_util.cc:997)
  [operator < load_combine > error]

**Comment by WenmuZhou** [comment]
你好，请问是解决了吗
