### ISSUE TITLE
如何按单个字符检测和分割进行识别，而不是一句话。 或者有没有办法显示一句话里每个字符的坐标？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5377]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：2.4 Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
如何按单个字符检测和分割进行识别，而不是一句话。 或者有没有办法显示一句话里每个字符的坐标？

**Comment by LDOUBLEV** [comment]
如果你的训练数据标注的是字符级别的标注，训练出来的模型输出结果也是字符级别的标注；

或者根据当前句子级别的预测结果和文字识别结果，大致计算每个字符的位置

**Comment by nissansz** [comment]
在哪里可以下载到字符级别的标注模型？自己不知道怎么训练。微信 nlanguage

**Comment by ioracion** [comment]
没有，这种特殊场景的都要自己标注自己训练

**Comment by nissansz** [comment]
谢谢。训练是什么原理？怎么进行单字训练，空格训练，获取单字坐标

**Comment by Hgd15601257355** [comment]
1.原理就是大数定律：只要试验的次数足够多，频率就接近于概率，而训练集的每个测试样本都可以算做一次试验，用梯度下降减小观测分布和实际分布的差距。2.至于单字的训练，空格，单字坐标是一起的，有两种方法，常规：你可以写个Python脚本，拿官方的句子训练集根据两个字之间的间隔分割，然后按顺序一对一匹配分别获得单字的训练集，缺点是ocr的第三个模型识别模型中的CTC算法没用了，就是你忽略了很大一部分信息。。你要想利用上下文信息还得修改模型。特殊：在ocr的第一个模型检测模型中获取到的二值图，嵌入一个常规二值图，根据这个二值图获取单字坐标，缺点是常规二值图对背景简单的识别效果较好，对复杂的背景划分不好。。。最后，单字坐标的话好像也可以在官方模型上从CTC算法上修改（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/lite/ocr_db_crnn.cc中的209～230行），就是识别到哪个argmax_idx和n的值就能知道大致的坐标，这个需要你自己调试。

**Comment by nissansz** [comment]
![0_00_30_958__0_00_32_874_0089300000019200108001920](https://user-images.githubusercontent.com/41010669/151691386-0e97a3a7-7f2e-4ddf-898e-b202e4ddeee5.jpeg)

![Uploading 0_00_30_958__0_00_32_874_0089300000019200108001920.jpeg…]()
。

**Comment by Hgd15601257355** [comment]
c++的opencv和Python 的cv2的区别，功能一样，用法不一样，你转换用到了哪些opencv函数，百度一下Python+该函数名，应该问题不大。

**Comment by nissansz** [comment]
一大段过滤代码。可以加微信帮忙看看吗？微信 nlanguage

**Comment by minirain2000** [comment]
用百度提供开发模板OCR_SDK（demo）里，用“通用文字识别（高精度含位置信息版）”就可以识别获取每个字的坐标及top\lleft\width\height等参数值。

**Comment by Darren0465** [comment]
> ![0_00_30_958__0_00_32_874_0089300000019200108001920](https://user-images.githubusercontent.com/41010669/151691386-0e97a3a7-7f2e-4ddf-898e-b202e4ddeee5.jpeg) ![0_00_30_958__0_00_32_874_0089300000019200108001920](https://user-images.githubusercontent.com/41010669/151691429-44773af4-0540-4eb1-8fd9-a5e96e0c0041.jpeg)
> 
> 谢谢。现有python代码有没有能够达到上面这种变形效果的？上面这个是cpp方法多次变换的效果。不知道怎么转换成python代码

这个是怎么实现的，能说一下吗
