### ISSUE TITLE
新增了字典词，predict_rec无法识别新词

### ISSUE THREAD

**Issue by suchxyz** [PaddlePaddle/PaddleOCR#5379]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle： 2.2.2 PaddleOCR：2.4 问题相关组件/Related components：tools/infer/predict_rec.py
- 运行指令/Command Code：
-tools/infer/predict_rec.py --image_dir="./train_data/rec/generatedXforinter/" --rec_model_dir="./myModels/rec_5w_infer/"  --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1_x.txt"

- 完整报错/Complete Error Message：
**aistudio@jupyter-1927690-3436148:~/PaddleOCR$ python tools/infer/predict_rec.py --image_dir="./train_data/rec/generatedXforinter/" --rec_model_dir="./myModels/rec_5w_infer/"  --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1_x.txt"
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E0129 15:22:40.382447 10797 analysis_config.cc:91] Please compile with gpu to EnableGpu()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[2022/01/29 15:22:46] root INFO: Predicts of ./train_data/rec/generatedXforinter/gt_14011.jpg:('', nan)
[2022/01/29 15:22:46] root INFO: Predicts of ./train_data/rec/generatedXforinter/gt_14012.jpg:('', nan)
[2022/01/29 15:22:46] root INFO: Predicts of ./train_data/rec/generatedXforinter/gt_14018.jpg:('', nan)
[2022/01/29 15:22:46] root INFO: Predicts of ./train_data/rec/generatedXforinter/gt_14032.jpg:('', nan)**

在./ppocr/utils/ppocr_keys_v1.txt里加了两个词. infer_rec完全正常
python tools/infer_rec.py -c rec_chinese_common_train_v2.0_cpu.yml -o Global.pretrained_model=output/rec_chinese_common_v2.0/best_accuracy Global.load_static_weights=false Global.infer_img=train_data/rec/generatedXforinter

[2022/01/29 16:01:19] root INFO: infer_img: train_data/rec/generatedXforinter/gt_14011.jpg
[2022/01/29 16:01:19] root INFO:         result: ⊗      0.99993837
[2022/01/29 16:01:19] root INFO: infer_img: train_data/rec/generatedXforinter/gt_14012.jpg
[2022/01/29 16:01:20] root INFO:         result: ✖      0.99998116

导出成infer模型
python3 tools/export_model.py -c rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./output/rec_chinese_common_v2.0/best_accuracy  Global.save_inference_dir=./myModels/rec_5w_infer/

predict_rec识别非新增的字符，也正常
aistudio@jupyter-1927690-3436148:~/PaddleOCR$ python tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_1.jpg" --rec_model_dir="./myModels/rec_5w_infer/"  --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1_x.txt"
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E0129 15:28:31.270722 11112 analysis_config.cc:91] Please compile with gpu to EnableGpu()
[2022/01/29 15:28:31] root INFO: Predicts of ./doc/imgs_words/ch/word_1.jpg:('韩国小馆', 0.9991693)

新增了字典词，predict_rec无法识别新词
错误如上

**Comment by lededev** [comment]
和 https://github.com/PaddlePaddle/PaddleOCR/issues/5325 重复了，合并一下？
