### ISSUE TITLE
Model is unable to run inferencing over full extent of the image.

### ISSUE THREAD

**Issue by mayank2** [PaddlePaddle/PaddleOCR#5385]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： PaddleOCR：2.4 问题相关组件/Related components：paddlepaddle-gpu: 2.2.2
- 运行指令/Command Code：
```
from paddleocr import PaddleOCR, draw_ocr
from PIL import Image
ocr = PaddleOCR(
        det_limit_side_len = 3300,
        det_limit_type="max",
        )
img_path = r"0001.jpg"
result = ocr.ocr(img_path, cls=True)

boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
image = Image.open(img_path).convert('RGB')
im_show = draw_ocr(image, boxes)


im_show = Image.fromarray(im_show)
im_show.save('result_out.jpg')
```
- 完整报错/Complete Error Message：Both "en" and "ch"(default) models have failed to detect the text in upper half of the image.
Original Image:
![0001](https://user-images.githubusercontent.com/24606062/152423036-e1e5ed7d-8346-43e5-b4c4-93617e08f210.jpg)

Output Image:
![result_out](https://user-images.githubusercontent.com/24606062/152423239-6a1f3616-4dbb-4c2e-bd72-80a5e451de12.jpg)

**Comment by lededev** [comment]
我这里也遇到了，只要文字条目多了，上半部分特别的顶部的就会漏掉，左边的比右边的更容易漏掉。
如果将图片高度减半，则能全部检测出来。

**Comment by LDOUBLEV** [comment]
训练数据中基本没有此类图像，遇到漏检问题，建议分割整个图像为多个小块图像再去检测@lededev

It is recommended to divide the image into several small images before detection@mayank2

**Comment by lededev** [comment]
非常规整的图像，文字条目多了一样会漏检上半部分，例如这个图片，第一行的“平均价”“代码”这些都会被漏掉，行数减半则没问题。
![image](https://user-images.githubusercontent.com/30518126/152916724-e3be59a9-aa57-47be-a372-fdb909e3f6c9.png)

**Comment by lededev** [comment]
PaddleOCR：2.3则很少漏掉，和https://github.com/PaddlePaddle/PaddleOCR/issues/5325有些类似。

**Comment by lededev** [comment]
PaddleOCR：2.3则很少漏掉，和 https://github.com/PaddlePaddle/PaddleOCR/issues/5325 有些类似。

**Comment by jaycecd** [comment]
> 训练数据中基本没有此类图像，遇到漏检问题，建议分割整个图像为多个小块图像再去检测@lededev
> 
> It is recommended to divide the image into several small images before detection@mayank2

我这边也遇到了这个问题，关键是分割小块图像的大小如何确定呢？预测的时候，是没有办法预知待检测图片（假如源图片为2W*2W）的大小的，如果是固定分割小块图像的太小（960*960），这样一张大图会被拆分成很多小图，效率应该会很低吧？而如果分割小块图像还是太大（1W*1W）还是可能会出现这个issue描述的漏检问题。而如果将源图像分割为具体的张数（例如每张图都分割成4张子图），大尺寸的源图像分割后依然会出现漏检的问题，而小尺寸的源图像还会出现本来能正常识别，分割成更小的图像后，因为切割边界把字给截断了，导致识别结果与源图像相比还变低了。

**Comment by xchXXX** [comment]
> > 训练数据中基本没有建议此类图像，遇到漏检问题，将整个图像分割为多个小块图像再去检测[@lededev](https://github.com/lededev)
> > 建议在检测前将图像分割成若干小图像@mayank2
> 
> 我论文也遇到了这个问题，关键是分割小块图像的大小如何确定呢？预测的时候，是没有办法预知待检测图片（假设源图片为2W * 2W）的大小的，如果是固定分割小块图像的太小（960 * 960），这样一张大图就会被分割成很多小图，效率应该会很低吧？而如果分割小块图像还是很简单（1W * 1W）还是可能会出现这个问题的漏检问题。而如果将源图像分割为具体的张数（例如尺寸每张图都分割成4张子图），大尺寸的源图像分割后依然会出现漏检的问题，而小尺寸的源图像描述又会出现本来能正常识别，分割成更小的图像后，因为分割边界把字给断断了，导致识别结果与源图像相比还是变低了。

我遇到的这个问题很严重，是上半页全部没有，我都怀疑是代码功能性的bug了，至于您说的分块截断字，可以通过滑动窗口弥补一下
