### ISSUE TITLE
SAST inference error: TimeInfo: *** Aborted at 1644060430 (unix time) try "date -d @1644060430" if you are using GNU date *** 

### ISSUE THREAD

**Issue by epoc88** [PaddlePaddle/PaddleOCR#5387]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu 20.04
- 版本号/Version：Paddle： 2.4 
- PaddleOCR： 问题相关组件/Related components：SAST 
- 运行指令/Command Code：python tools/infer/predict_det.py --det_algorithm="SAST" --image_dir="./input/1.png" --det_model_dir="./inference/det_sast_ic15"

- 完整报错/Complete Error Message：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1644060430 (unix time) try "date -d @1644060430" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 270489 (TID 0x7ff4ab9c3740) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by TheSeriousProgrammer** [comment]
The above mentioned installation command fixed the issue for me
