### ISSUE TITLE
在做文本框检测前的图像预处理

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5391]
请问下我的图片内容比较倾斜，在做文本检测有一些图像预处理操作吗，比如仿射变换之类的

**Comment by WenmuZhou** [comment]
可以先做一下直线检测，将图表变正方便检测

**Comment by WenmuZhou** [comment]
1. 可以直接进行ppocr的检测识别
2. 目标检测的时候进行四点回归，根据四点坐标进行仿射变换

**Comment by GivanTsai** [comment]
> 
可以分别给个学习链接吗
