### ISSUE TITLE
paddleOCR关键信息提取算法SDMGR执行预测时，给出的示例代码必须要带有文本字符标注信息的transcription字段，为啥

### ISSUE THREAD

**Issue by dengxy9527** [PaddlePaddle/PaddleOCR#5393]
(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppstructure/docs/kie.md)

 整个文档也没有提供针对一张未标注图片的预测示例
![image](https://user-images.githubusercontent.com/61773707/152751366-74075ecc-38cf-4535-b20a-06beef8d6e9b.png)

**Comment by LDOUBLEV** [comment]
sdmgr属于KIE，使用的是多模态特征，输入有文本和图像特征；transcription字段是文本信息；

**Comment by alina-CV** [comment]
那 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/kie.md#1-%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8  里面1.txt中的label:1, label:0, 不是说明图片已经做了label关键信息标注吗？ 这个时候为什么还要继续用模型呢？ 不明白

**Comment by ChenNima** [comment]
> 那 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/kie.md#1-%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8 里面1.txt中的label:1, label:0, 不是说明图片已经做了label关键信息标注吗？ 这个时候为什么还要继续用模型呢？ 不明白

1.txt里的label只是满足了模型的输入形状，如果你把1.txt里的label全换成一样的值，还是能正常推理的，推理过程中模型没有看输入的label值。SDMG-R有很多坑我写了一篇文章你可以参考以下 [关键信息提取网络SDMG-R代码详解(1): 概览与应用](https://chennima.github.io/paddle-ocr-kie-sdmgr-code-overview-and-application)

**Comment by shallowime** [comment]
> > 那 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/kie.md#1-%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8 里面1.txt中的label:1, label:0, 不是说明图片已经做了label关键信息标注吗？ 这个时候为什么还要继续用模型呢？ 不明白
> 
> 1.txt里的label只是满足了模型的输入形状，如果你把1.txt里的label全换成一样的值，还是能正常推理的，推理过程中模型没有看输入的label值。SDMG-R有很多坑我写了一篇文章你可以参考以下 [关键信息提取网络SDMG-R代码详解(1): 概览与应用](https://chennima.github.io/paddle-ocr-kie-sdmgr-code-overview-and-application)

感谢感谢，这个文章解决了我全部的问题，建议其他有问题的朋友也参考这篇！
