### ISSUE TITLE
关于paddleocr空格识别的问题

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/PaddleOCR#5394]
您好，我有如下几个问题：请问paddleocr现有模型是否支持中文空格的识别？对于小空格识别效果不好的情况若使用自己的小空格数据集finetune能否有较大改善？若有，建议使用多大量的数据集？感谢解答~

**Comment by Karenlyw** [comment]
![eg](https://user-images.githubusercontent.com/58201310/152762102-c4becbbc-b885-4e49-986e-8c0dce4f83a9.jpg)
lei类似这种 用户名和评论之间的空格，如识别结果：“野战问天 关注了主播”

**Comment by WenmuZhou** [comment]
这种可以微调试试，但是预期盖不会很明显，因为太近了

**Comment by Karenlyw** [comment]
> 这种可以微调试试，但是预期盖不会很明显，因为太近了
好的 多谢
