### ISSUE TITLE
识别字符重复问题

### ISSUE THREAD

**Issue by wd846** [PaddlePaddle/PaddleOCR#5395]
用c++的SDK，最新版的，没有使用GPU，开了MKLDNN。使用的Server推理模型，inference.pdmodel，inference.pdiparams
相关代码是copy的。
目标是识别车牌，在实际工程中抓拍的过往车辆图片，目前白天和晚上识别准确率大概在80%左右，但有一些图片，存在较为严重的字符复复问题，比如 “京HC0011”，识别结果为 “京京HHC00111”，
在CRNNRecognizer中，通过DBDetector检测的文字框box裁剪出来的图片，即GetRotateCropImage的结果，如果UnClipRatio设置为2.0，即会产生比较严重的字符重复，如果设成较小的1.4，识别错误率会上升。但是UnClipRatio设置2.0时如果将GetRotateCropImage图片宽度进行0.88或0.90的压缩，识别重复字符会大幅降低，但有些车牌拍摄角度很正的图片识别正确率会下降。搞了好长时间也没搞定，尝试将识别类中resize_op_.Run中CrnnResizeImg::Run的图片高度缩放改成3，64，640会崩溃，换成3，48，480错误率大幅上升基本没法用，是否在识别时文字框高度只能为32（横向文字)?
![20140104104655_京AZ575学_流村环岛南侧_0](https://user-images.githubusercontent.com/59092819/152779095-c5e23b51-93be-4973-8323-bcf366451f68.jpg)
这张图后面那个“学”字始终识别不了，识别成了错误的数字
![Err](https://user-images.githubusercontent.com/59092819/152779422-a551be5a-4f3a-453a-95b0-4f87012be0df.jpg)
这就是识别时UnClipRatio设置为2.0产生严重重复的图

**Comment by GivanTsai** [comment]
请问你在做车牌号识别的时候有没有先用目标检测将车牌框出来后再做OCR，还是直接整张图片做OCR

**Comment by wd846** [comment]
> 
检测了，检测出box后再进行识别的

**Comment by WenmuZhou** [comment]
是否试过python的推理呢

**Comment by WenmuZhou** [comment]
你好，学识别不出来是因为cpp中db的后处理参数和py的不一样，这个在这里修复了https://github.com/PaddlePaddle/PaddleOCR/pull/5648
