### ISSUE TITLE
关于OCR识别的问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5402]
![image](https://user-images.githubusercontent.com/87969070/153101616-c6d3e361-c5fd-444d-8451-e3dfe96b8bad.png)
请问一下，我尝试训练上述图像集除名称为190的图像，训练之后去预测190的图像时读错，训练集txt文件中是一整串字符，如图
![image](https://user-images.githubusercontent.com/87969070/153102165-599c18e6-2455-4380-9aa1-3646c39fd4e3.png)
，字典设置为单字符，
![image](https://user-images.githubusercontent.com/87969070/153102251-8c5bdcba-dbde-49f8-97d5-92ddccc1c2be.png)
请问一下，该问题是模型本身特性，还是整个训练模型已经过拟了，应该如何解决呢？
用的是mv3_none_bilstm_ctc配置文件下的模型

**Comment by GivanTsai** [comment]
图片190的预测结果是什么

**Comment by 18362890185** [comment]
> 图片190的预测结果是什么

![image](https://user-images.githubusercontent.com/87969070/153108595-4cce6605-93aa-4c94-99a8-7b67c2e1ebf2.png)

**Comment by 18362890185** [comment]
> 场景看着倒是不难，训练集有多少数据，可能训练数据太少了

训练集一共142张，训练的过程中也使用了tia数据增强

**Comment by GivanTsai** [comment]
> > 场景看着倒是不难，训练集有多少数据，可能训练数据太少了
> 
> 训练集一共142张，训练的过程中也使用了tia数据增强 请问一下，一般情况下，需要多少数据集？

这图片质量挺高的不应该识别不准，你这是什么场景的数据

**Comment by 18362890185** [comment]
> > > 场景看着倒是不难，训练集有多少数据，可能训练数据太少了
> > 
> > 
> > 训练集一共142张，训练的过程中也使用了tia数据增强 请问一下，一般情况下，需要多少数据集？
> 
> 这图片质量挺高的不应该识别不准，你这是什么场景的数据

辊轴上的字符

**Comment by MissPenguin** [comment]
> > 场景看着倒是不难，训练集有多少数据，可能训练数据太少了
> 
> 训练集一共142张，训练的过程中也使用了tia数据增强 请问一下，一般情况下，需要多少数据集？

数据量有点少了，训练中文6000多字的文本识别需要百万级数据量，你的场景字符数少，场景单一，可以先弄个1000张左右试试

**Comment by 18362890185** [comment]
> > > 场景看着倒是不难，训练集有多少数据，可能训练数据太少了
> > 
> > 
> > 训练集一共142张，训练的过程中也使用了tia数据增强 请问一下，一般情况下，需要多少数据集？
> 
> 这图片质量挺高的不应该识别不准，你这是什么场景的数据



> > > 场景看着倒是不难，训练集有多少数据，可能训练数据太少了
> > 
> > 
> > 训练集一共142张，训练的过程中也使用了tia数据增强 请问一下，一般情况下，需要多少数据集？
> 
> 数据量有点少了，训练中文6000多字的文本识别需要百万级数据量，你的场景字符数少，场景单一，可以先弄个1000张左右试试

实际没有那么多的图像，还有其他方法吗？数据合成的图像，跟实际场景的图像差距过大

**Comment by MissPenguin** [comment]
你是直接训练还是在ppocr模型上finetune的呢

**Comment by 18362890185** [comment]
> 你是直接训练还是在ppocr模型上finetune的呢

加载了预训练模型进行finetune的
![image](https://user-images.githubusercontent.com/87969070/153156649-1793f304-d4f6-40cf-b763-cf39f98f0a9b.png)

**Comment by MissPenguin** [comment]
那还是尽可能补一些训练数据吧，实在没有真实数据就合成，虽然不能和场景完全一致，应该也是有效果的

**Comment by 18362890185** [comment]
> 那还是尽可能补一些训练数据吧，实在没有真实数据就合成，虽然不能和场景完全一致，应该也是有效果的

好的，谢谢小姐姐

**Comment by Mrfuhang** [comment]
> > 那还是尽可能补一些训练数据吧，实在没有真实数据就合成，虽然不能和场景完全一致，应该也是有效果的
> 
> 好的，谢谢小姐姐

现在识别表格中的单字符准确了嘛
