### ISSUE TITLE
文档描述疑似出错（多语言模型-孟加拉语）

### ISSUE THREAD

**Issue by FelixEdwards** [PaddlePaddle/PaddleOCR#5403]
> dir: [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)/[doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/doc)/[doc_ch](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/doc/doc_ch)/multi_languages.md

![image](https://user-images.githubusercontent.com/21273557/153113721-3eb46c06-65e8-4d0d-9b65-306d9c51246c.png)

孟加拉语语言为 Bengali， 缩写 bn，而不是图中的 Bhojpuri，经核对`ppocr/utils/dict`下的字典文件，也确认了支持的不是孟加拉语，所以应该是中文描述部分有待商榷

- 参考资料
  - https://zh.wikipedia.org/wiki/%E5%AD%9F%E5%8A%A0%E6%8B%89%E8%AF%AD
  - https://en.wikipedia.org/wiki/List_of_Wikipedias

**Comment by tink2123** [comment]
@FelixEdwards  感谢反馈，已更新为博杰普爾文。
