### ISSUE TITLE
 安装PaddleOCR whl包报错Failed building wheel for python-Levenshtein

### ISSUE THREAD

**Issue by gjzhappy** [PaddlePaddle/PaddleOCR#5406]
win10系统，anaconda方式安装paddleocr,报错：
(确认已经安装C++14 )

(base) C:\Windows\system32>pip install "paddleocr>=2.0.1"
Collecting paddleocr>=2.0.1
  Using cached paddleocr-2.4-py3-none-any.whl (288 kB)
Requirement already satisfied: scikit-image in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (0.18.3)
Collecting imgaug==0.4.0
  Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Collecting lmdb
  Using cached lmdb-1.3.0-cp39-cp39-win_amd64.whl (106 kB)
Requirement already satisfied: tqdm in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (4.62.3)
Requirement already satisfied: cython in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (0.29.24)
Requirement already satisfied: openpyxl in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (3.0.9)
Collecting pyclipper
  Using cached pyclipper-1.3.0.post2-cp39-cp39-win_amd64.whl (105 kB)
Collecting premailer
  Using cached premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Collecting paddlenlp>=2.2.1
  Using cached paddlenlp-2.2.4-py3-none-any.whl (1.1 MB)
Requirement already satisfied: visualdl in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (2.2.3)
Collecting opencv-contrib-python==4.4.0.46
  Using cached opencv_contrib_python-4.4.0.46-cp39-cp39-win_amd64.whl (40.1 MB)
Requirement already satisfied: lxml in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (4.6.3)
Requirement already satisfied: numpy in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (1.20.3)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Requirement already satisfied: shapely in d:\work\tools\anaconda3\lib\site-packages (from paddleocr>=2.0.1) (1.8.0)
Requirement already satisfied: opencv-python in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (4.5.5.62)
Requirement already satisfied: scipy in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (1.7.1)
Requirement already satisfied: matplotlib in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (3.4.3)
Requirement already satisfied: imageio in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (2.9.0)
Requirement already satisfied: Pillow in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (8.4.0)
Requirement already satisfied: six in d:\work\tools\anaconda3\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (1.16.0)
Requirement already satisfied: seqeval in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (1.2.2)
Requirement already satisfied: colorama in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (0.4.4)
Requirement already satisfied: colorlog in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (6.6.0)
Requirement already satisfied: h5py in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (3.2.1)
Requirement already satisfied: multiprocess in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (0.70.12.2)
Requirement already satisfied: jieba in d:\work\tools\anaconda3\lib\site-packages (from paddlenlp>=2.2.1->paddleocr>=2.0.1) (0.42.1)
Requirement already satisfied: networkx>=2.0 in d:\work\tools\anaconda3\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (2.6.3)
Requirement already satisfied: tifffile>=2019.7.26 in d:\work\tools\anaconda3\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (2021.7.2)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\work\tools\anaconda3\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (1.1.1)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\work\tools\anaconda3\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in d:\work\tools\anaconda3\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (3.0.4)
Requirement already satisfied: cycler>=0.10 in d:\work\tools\anaconda3\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in d:\work\tools\anaconda3\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (2.8.2)
Requirement already satisfied: dill>=0.3.4 in d:\work\tools\anaconda3\lib\site-packages (from multiprocess->paddlenlp>=2.2.1->paddleocr>=2.0.1) (0.3.4)
Requirement already satisfied: et-xmlfile in d:\work\tools\anaconda3\lib\site-packages (from openpyxl->paddleocr>=2.0.1) (1.1.0)
Requirement already satisfied: requests in d:\work\tools\anaconda3\lib\site-packages (from premailer->paddleocr>=2.0.1) (2.26.0)
Requirement already satisfied: cachetools in d:\work\tools\anaconda3\lib\site-packages (from premailer->paddleocr>=2.0.1) (5.0.0)
Requirement already satisfied: cssselect in d:\work\tools\anaconda3\lib\site-packages (from premailer->paddleocr>=2.0.1) (1.1.0)
Requirement already satisfied: cssutils in d:\work\tools\anaconda3\lib\site-packages (from premailer->paddleocr>=2.0.1) (2.3.0)
Requirement already satisfied: setuptools in d:\work\tools\anaconda3\lib\site-packages (from python-Levenshtein->paddleocr>=2.0.1) (58.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\work\tools\anaconda3\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\work\tools\anaconda3\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\work\tools\anaconda3\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\work\tools\anaconda3\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (2021.10.8)
Requirement already satisfied: scikit-learn>=0.21.3 in d:\work\tools\anaconda3\lib\site-packages (from seqeval->paddlenlp>=2.2.1->paddleocr>=2.0.1) (0.24.2)
Requirement already satisfied: joblib>=0.11 in d:\work\tools\anaconda3\lib\site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp>=2.2.1->paddleocr>=2.0.1) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\work\tools\anaconda3\lib\site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp>=2.2.1->paddleocr>=2.0.1) (2.2.0)
Requirement already satisfied: pandas in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (1.3.4)
Requirement already satisfied: pre-commit in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (2.17.0)
Requirement already satisfied: flask>=1.1.1 in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (1.1.2)
Requirement already satisfied: shellcheck-py in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (0.8.0.4)
Requirement already satisfied: protobuf>=3.11.0 in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (3.19.4)
Requirement already satisfied: Flask-Babel>=1.0.0 in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (2.0.0)
Requirement already satisfied: bce-python-sdk in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (0.8.64)
Requirement already satisfied: flake8>=3.7.9 in d:\work\tools\anaconda3\lib\site-packages (from visualdl->paddleocr>=2.0.1) (3.9.2)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in d:\work\tools\anaconda3\lib\site-packages (from flake8>=3.7.9->visualdl->paddleocr>=2.0.1) (0.6.1)
Requirement already satisfied: pycodestyle<2.8.0,>=2.7.0 in d:\work\tools\anaconda3\lib\site-packages (from flake8>=3.7.9->visualdl->paddleocr>=2.0.1) (2.7.0)
Requirement already satisfied: pyflakes<2.4.0,>=2.3.0 in d:\work\tools\anaconda3\lib\site-packages (from flake8>=3.7.9->visualdl->paddleocr>=2.0.1) (2.3.1)
Requirement already satisfied: itsdangerous>=0.24 in d:\work\tools\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.0.1)
Requirement already satisfied: click>=5.1 in d:\work\tools\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (8.0.3)
Requirement already satisfied: Jinja2>=2.10.1 in d:\work\tools\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.11.3)
Requirement already satisfied: Werkzeug>=0.15 in d:\work\tools\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.0.2)
Requirement already satisfied: Babel>=2.3 in d:\work\tools\anaconda3\lib\site-packages (from Flask-Babel>=1.0.0->visualdl->paddleocr>=2.0.1) (2.9.1)
Requirement already satisfied: pytz in d:\work\tools\anaconda3\lib\site-packages (from Flask-Babel>=1.0.0->visualdl->paddleocr>=2.0.1) (2021.3)
Requirement already satisfied: MarkupSafe>=0.23 in d:\work\tools\anaconda3\lib\site-packages (from Jinja2>=2.10.1->flask>=1.1.1->visualdl->paddleocr>=2.0.1) (1.1.1)
Requirement already satisfied: future>=0.6.0 in d:\work\tools\anaconda3\lib\site-packages (from bce-python-sdk->visualdl->paddleocr>=2.0.1) (0.18.2)
Requirement already satisfied: pycryptodome>=3.8.0 in d:\work\tools\anaconda3\lib\site-packages (from bce-python-sdk->visualdl->paddleocr>=2.0.1) (3.14.1)
Requirement already satisfied: toml in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (0.10.2)
Requirement already satisfied: identify>=1.0.0 in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (2.4.8)
Requirement already satisfied: pyyaml>=5.1 in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (6.0)
Requirement already satisfied: nodeenv>=0.11.1 in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (1.6.0)
Requirement already satisfied: cfgv>=2.0.0 in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (3.3.1)
Requirement already satisfied: virtualenv>=20.0.8 in d:\work\tools\anaconda3\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (20.13.1)
Requirement already satisfied: platformdirs<3,>=2 in d:\work\tools\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl->paddleocr>=2.0.1) (2.4.1)
Requirement already satisfied: distlib<1,>=0.3.1 in d:\work\tools\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl->paddleocr>=2.0.1) (0.3.4)
Requirement already satisfied: filelock<4,>=3.2 in d:\work\tools\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl->paddleocr>=2.0.1) (3.3.1)
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\work\tools\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ganjz\AppData\Local\Temp\pip-wheel-6zod78qn'
       cwd: C:\Users\ganjz\AppData\Local\Temp\pip-install-q_ws09d9\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\Levenshtein
  copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.9\Levenshtein
  copying Levenshtein\__init__.py -> build\lib.win-amd64-3.9\Levenshtein
  running egg_info
  writing python_Levenshtein.egg-info\PKG-INFO
  writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
  writing entry points to python_Levenshtein.egg-info\entry_points.txt
  writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
  writing requirements to python_Levenshtein.egg-info\requires.txt
  writing top-level names to python_Levenshtein.egg-info\top_level.txt
  reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  adding license file 'COPYING'
  writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.9\Levenshtein
  copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.9\Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for python-Levenshtein
  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
Installing collected packages: python-Levenshtein, pyclipper, premailer, paddlenlp, opencv-contrib-python, lmdb, imgaug, paddleocr
    Running setup.py install for python-Levenshtein ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\work\tools\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ganjz\AppData\Local\Temp\pip-record-m6oep0li\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\work\tools\Anaconda3\Include\python-Levenshtein'
         cwd: C:\Users\ganjz\AppData\Local\Temp\pip-install-q_ws09d9\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.9\Levenshtein
    running egg_info
    writing python_Levenshtein.egg-info\PKG-INFO
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    adding license file 'COPYING'
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.9\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\work\tools\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ganjz\\AppData\\Local\\Temp\\pip-install-q_ws09d9\\python-levenshtein_ae1bae2ffc154c4ab4afddb66784bbe4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ganjz\AppData\Local\Temp\pip-record-m6oep0li\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\work\tools\Anaconda3\Include\python-Levenshtein' Check the logs for full command output.

(base) C:\Windows\system32>^A

**Comment by MissPenguin** [comment]
网上搜一下安装包吧
