### ISSUE TITLE
Word level detection

### ISSUE THREAD

**Issue by Akhilesh64** [PaddlePaddle/PaddleOCR#5407]
Hi, do you provide a model which provides word level detection results instead of sentence level detection.

**Comment by MissPenguin** [comment]
> Hi, do you provide a model which provides word level detection results instead of sentence level detection.

models trained on public English datasets are word level: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/algorithm_overview_en.md#11-text-detection-algorithm

**Comment by Akhilesh64** [comment]
The performance of the above models is very less compared to these model : [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/models_list_en.md#1-text-detection-model](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/models_list_en.md#1-text-detection-model) Can these models be finetuned so they can detect at word level.

**Comment by Akhilesh64** [comment]
Hi @MissPenguin I finetuned ch_PP-OCRv2_det with my dataset. I used [this](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml) config file and the results have improved a lot. To close this issue I have 2 doubts:

1. I have large training images of size 2400x3500. When I feed them to my model are they resized automatically to some predefined dimensions? If yes where can I change those.
2.  Can you share the training regime of your models/

**Comment by MissPenguin** [comment]
Yes. You can modify this parameter: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml#L83

**Comment by mattdeeperinsights** [comment]
@Akhilesh64 Is there any chance you could share your fine tuned model?

I just tried training myself on my CPU, after 1 epoch it looks like it will take 59 days to run! 

```
[2022/09/23 12:36:49] ppocr INFO: epoch: [1/1200], global_step: 10, lr: 0.001000, loss: 7.907456, loss_shrink_maps: 4.830573, loss_threshold_maps: 2.097650, loss_binary_maps: 0.969758, avg_reader_cost: 0.18444 s, avg_batch_cost: 68.44599 s, avg_samples: 16.0, ips: 0.23376 samples/s, eta: 59 days, 21:10:32
```
