### ISSUE TITLE
文字识别训练时生成一些iter_epoch_3.pdopt，iter_epoch_3.pdmodel，iter_epoch_3.pdparams....

### ISSUE THREAD

**Issue by hope0654** [PaddlePaddle/PaddleOCR#541]
请问用自己的训练集进行文字识别训练时生成一些iter_epoch_3.pdopt，iter_epoch_3.pdmodel，iter_epoch_3.pdparams,不是像用demo训练集和说明中生成best_accuracy,这是什么情况？

**Comment by WenmuZhou** [comment]
配置了save_epoch_step就会这样子，你的save_epoch_step是不是设的3

**Comment by hope0654** [comment]
是save_epoch_step = 3 ，这样会不会有问题，已经训练了两天了，如果需要断点训练，是不是就不能用-o Global.checkpoints = my path/best_accuracy

**Comment by tink2123** [comment]
断点训练，是需要用 -o Global.checkpoints 的,如果你没有得到best_acc，那断点需要指向 iter_epoch_3 或其他轮次的权重，eval一轮之后才会生成best_accuray。 训练两天都没有评估一次嘛？你的eval_batch_step 设置的是多少呢？

**Comment by hope0654** [comment]
eval_batch_step是2000，训练中acc一直是0.0

**Comment by tink2123** [comment]
是否有加载预训练权重呢？使用的是默认的字典吗，acc 一直都是0的话，应该不太符合预期

**Comment by hope0654** [comment]
加了预训练权重ch_rec_r34_vd_crnn/best_accuracy ,字典用的是我自己训练集里面文字的字典，训练集就是根据这个字典的文字随机生成的20万张图片

**Comment by tink2123** [comment]
更换字典之后fc层权重会从0开始学习，如果字典中没有特殊的字符，可以先使用默认字典，会加快训练速度

**Comment by hope0654** [comment]
字典主要是粤语常用字和繁体字，默认字典中有很多没有，如果用默认字典的话不知道是否有效果

**Comment by tink2123** [comment]
那还是需要用您自己的字典。训练loss在收敛吗，可以试一下调小学习率，或者试试不加载预训练权重呢？
