### ISSUE TITLE
cpp infer 中 rec_batch_num 设置成某值的时候 程序会崩溃在 this->predictor_->Run()

### ISSUE THREAD

**Issue by liveever** [PaddlePaddle/PaddleOCR#5411]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Windows 10 64
- 版本号/Version：
    Paddle：cpu_avx_mkl 2.2.2
    PaddleOCR：2.4
- 问题相关组件/Related components：cpp_infer
- 运行指令/Command Code：ppocr system    --det_model_dir=inference/ch_ppocr_server_v2.0_det_infer --use_angle_cls=true --cls_model_dir=inference/ch_ppocr_mobile_v2.0_cls_infer     --rec_model_dir=inference/ch_ppocr_server_v2.0_rec_infer  --char_list_file=ppocr_keys_v1.txt --image_dir=1.jpg 
- 完整报错/Complete Error Message：没有报错信息 程序自动停止了。

当rec_batch_num 大于索要识别图片的crop_img的数量时候 不会有问题，
但是小于这个数量的时候 会崩溃在某个批次的predictor_->Run()，
不同的rec_batch_num ，崩溃在的批次的位置也不一样。

**Comment by liveever** [comment]
![1](https://user-images.githubusercontent.com/284542/153183185-9bdeb70a-d262-4c28-af22-ca0fc2b36d5a.jpg)
这个是测试的图片

**Comment by hu2023** [comment]
同样的环境，用paddle_inference.dll推断，存在同样的问题。

**Comment by WenmuZhou** [comment]
你好，我们刚刚修了一个bug，可能和你这个相关，辛苦再测试一下https://github.com/PaddlePaddle/PaddleOCR/pull/5693

**Comment by hu2023** [comment]
@WenmuZhou 
多谢。
修改之后问题消失了；同时【出现识别结果怪异】的问题也消失了。

**Comment by WenmuZhou** [comment]
> @WenmuZhou 
> 多谢。
> 修改之后问题消失了；同时【出现识别结果怪异】的问题也消失了。

出现识别结果怪异 这个问题有issue吗

**Comment by hu2023** [comment]
我没有提交这个问题。现在看来是解决了。

**Comment by WenmuZhou** [comment]
好的
