### ISSUE TITLE
关于数据合成的问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5412]
![image](https://user-images.githubusercontent.com/87969070/153181191-9208fd6d-11a1-4707-b825-a6b16e36c63f.png)
![image](https://user-images.githubusercontent.com/87969070/153181259-46b7a503-56f7-4772-a917-26fa017a1f68.png)

请问一下，数据合成的图片与原图片大小差距过大，可以调整数据合成图片的大小吗？

**Comment by MissPenguin** [comment]
这是啥合成工具，不过任何合成工具肯定都可以控制合成图像的大小的，最直接的你还可以直接resize合成结果

**Comment by 18362890185** [comment]
> 这是啥合成工具，不过任何合成工具肯定都可以控制合成图像的大小的，最直接的你还可以直接resize合成结果

用的就是官方的
![image](https://user-images.githubusercontent.com/87969070/153332961-bf46adbc-b215-4d61-acb3-1d4879031f91.png)
![image](https://user-images.githubusercontent.com/87969070/153332996-c0ec59e8-0766-4599-a9cb-a2ad4be5eefd.png)
如果设置过大，合成效果很差

**Comment by MissPenguin** [comment]
Style-Text用于合成识别模型训练数据，先不要改配置中的参数，有需要话可以合成后再统一resize，不过训练输入时都会resize的，其实不影响。

**Comment by 18362890185** [comment]
> Style-Text用于合成识别模型训练数据，先不要改配置中的参数，有需要话可以合成后再统一resize，不过训练输入时都会resize的，其实不影响。

好的，还有字体差距过大 如何调整呢

**Comment by MissPenguin** [comment]
> > Style-Text用于合成识别模型训练数据，先不要改配置中的参数，有需要话可以合成后再统一resize，不过训练输入时都会resize的，其实不影响。
> 
> 好的，还有字体差距过大 如何调整呢

效果方面我们会持续优化哈

**Comment by zd6454** [comment]
> > > Style-Text用于合成识别模型训练数据，先不要改配置中的参数，有需要话可以合成后再统一resize，不过训练输入时都会resize的，其实不影响。
> > 
> > 
> > 好的，还有字体差距过大 如何调整呢
> 
> 效果方面我们会持续优化哈

求一份训练模式代码参考
