### ISSUE TITLE
关于识别手写英文的问题

### ISSUE THREAD

**Issue by gjzhappy** [PaddlePaddle/PaddleOCR#5413]
你好，我用通用的中英文检测&识别模型，识别手写的英文语句，为什么一行的句子会被识别为多个单词？
比如：My name is xxx, please call me.
被识别为：
 [[[909.0, 88.0], [1253.0, 81.0], [1255.0, 172.0], [911.0, 179.0]], ('please call me', 0.9944135)]
[2022/02/09 18:40:59] root INFO: [[[1285.0, 80.0], [1490.0, 97.0], [1482.0, 193.0], [1277.0, 176.0]], ('My name is xxx', 0.99935675)]，
且解析顺序也是颠倒的

**Comment by MissPenguin** [comment]
因为检测成了2个框，显示顺序是按照左上坐标排序的，后面的框比前面的框略高一点。可以看下可视化结果。

**Comment by gjzhappy** [comment]
是不是只能通过训练自定义数据集解决? 有没有推荐的文档,谢谢

**Comment by guoge6** [comment]
> 是不是只能通过训练自定义数据集解决? 有没有推荐的文档,谢谢

我也想知道怎么解决

**Comment by MissPenguin** [comment]
> 是不是只能通过训练自定义数据集解决? 有没有推荐的文档,谢谢

一般使用自定义数据集fine tune是可以显著提升效果的，可以参考教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/detection.md
