### ISSUE TITLE
Not found: ppocr/utils/corpus ?

### ISSUE THREAD

**Issue by 98-Jane** [PaddlePaddle/PaddleOCR#5416]
hi,
cannot find ppocr/utils/corpus ? Is this folder lost?

**Comment by MissPenguin** [comment]
You can create this folder by yourself. Refer to this PR: https://github.com/PaddlePaddle/PaddleOCR/pull/5161/files

**Comment by 98-Jane** [comment]
> You can create this folder by yourself. Refer to this PR: https://github.com/PaddlePaddle/PaddleOCR/pull/5161/files

Thanks！Do you know how corpus dir works? Not found a place to use corpus in the code?

**Comment by tink2123** [comment]
The corpus is mainly used to synthesize data offline. Is not used in the training phase of the model.
