### ISSUE TITLE
如何将中文简体，繁体，日文，的所有汉字合并成一个识别模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5417]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 64
- 版本号/Version：Paddle：  PaddleOCR：2.4 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
词典和训练数据能覆盖这些字符就可以实现，需要扩大词典、补充训练数据、重新训练
