### ISSUE TITLE
win10操作系统下，用anaconda3的控制台，修改配置中gpu修改不了，AssertionError: only support yaml files for now

### ISSUE THREAD

**Issue by CUI-XUAN** [PaddlePaddle/PaddleOCR#5418]
win10操作系统下，用anaconda3的控制台，修改配置中gpu修改不了
路径，语句格式都是对，就是报错，麻烦各位大神指导一下

(paddle_env) E:\paddleocr-release\PaddleOCR-release-2.4>python tools/train.py -c configs/det/det_mv3_db.yml -o   Global.pretrained_model=./models/ResNet18_vd_pretrained.pdparams  Optimizer.base_lr=0.0001 -c  Global.use_gpu=false
D:\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Traceback (most recent call last):
  File "E:\paddleocr-release\PaddleOCR-release-2.4\tools\train.py", line 147, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "E:\paddleocr-release\PaddleOCR-release-2.4\tools\program.py", line 481, in preprocess
    config = load_config(FLAGS.config)
  File "E:\paddleocr-release\PaddleOCR-release-2.4\tools\program.py", line 99, in load_config
    assert ext in ['.yml', '.yaml'], "only support yaml files for now"
AssertionError: only support yaml files for now

**Comment by LDOUBLEV** [comment]
python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./models/ResNet18_vd_pretrained.pdparams Optimizer.base_lr=0.0001 -c Global.use_gpu=false

改成

python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./models/ResNet18_vd_pretrained.pdparams Optimizer.base_lr=0.0001  **Global.use_gpu=false**

**Comment by CUI-XUAN** [comment]
不行得，还是报错





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月10日(星期四) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] win10操作系统下，用anaconda3的控制台，修改配置中gpu修改不了，AssertionError: only support yaml files for now (Issue #5418)





 
python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./models/ResNet18_vd_pretrained.pdparams Optimizer.base_lr=0.0001 -c Global.use_gpu=false
 
改成
 
python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./models/ResNet18_vd_pretrained.pdparams Optimizer.base_lr=0.0001  Global.use_gpu=false
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CUI-XUAN** [comment]
我直接在配置文件手动去修改，才可以，在控制台一直报错，就很奇怪
