### ISSUE TITLE
tools/infer_det.py和tools/infer/predict_det.py结果不一致

### ISSUE THREAD

**Issue by keyxuliang** [PaddlePaddle/PaddleOCR#542]
使用tools/infer_det.py的时候，在configs/det/det_mv3_db.yml中可以设置thresh: 0.3  box_thresh: 0.7 unclip_ratio: 2.0 三个参数；
怎么设置tools/infer/predict_det.py中使用的det_max_side_len参数？

**Comment by tink2123** [comment]
是否有修改配置文件呢，另外图片resize的方式不同也可能造成结果不同。infer 时默认 max_side_len=2400, 修改predict_rec 中的 det_max_side_len=2400 试一下是否能得到检测框呢？
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py#L137

**Comment by keyxuliang** [comment]
嗯，解决了，是因为resize的原因。
