### ISSUE TITLE
predict_rec中的识别输出copy_to_cpu特别慢

### ISSUE THREAD

**Issue by suchxyz** [PaddlePaddle/PaddleOCR#5425]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux GPU
- 版本号/Version：Paddle：2.2.2  PaddleOCR：2.4  问题相关组件/Related components： tools/infer/predict_rec.py
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**识别输出copy to cpu特别慢， 占了整个rec耗时的60-70%。 请问有办法调优吗？**
output = output_tensor.copy_to_cpu()

自己加的一些print
[2022/02/10 11:51:18] root DEBUG: dt_boxes num : 80, elapse : 0.08081340789794922
xxxxxxx batch_num: 128
xxxxxx  0, beg_before_reg_cost = 0.011425018310546875
xxxxxx  0, beg_reg_cost = 0.03883528709411621
xxxxxx  0, each_copytocpu_cost = 0.2869839668273926                         # copy to cpu的cost
xxxxxx  0, copytocpu_cost = 0.2870161533355713
xxxxxx  0, post_cost = 0.07748770713806152
[2022/02/10 11:51:18] root DEBUG: rec_res num  : 80, elapse : 0.41502976417541504

**Comment by LDOUBLEV** [comment]
预测的时候是异步的，直接print each_copytocpu_cost的时间不是很准；
如果你是在GPU上预测，建议使用tensort加速，如果你是在CPU上，可以开启mkldnn做加速

**Comment by hzq-zjm** [comment]
遇到同样的问题，我理解这个copy_to_cpu和用tensorrt加速推理没关系吧

**Comment by suchxyz** [comment]
好像升级了cudnn快了copy_to_cpu很多
