### ISSUE TITLE
docker 部署出错

### ISSUE THREAD

**Issue by dreamfly32** [PaddlePaddle/PaddleOCR#5429]
dockerfile：
`# Version: 2.0.0
FROM registry.baidubce.com/paddlepaddle/paddle:2.1.2

RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple && pip3.7 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple

RUN git clone https://gitee.com/PaddlePaddle/PaddleOCR.git /PaddleOCR

ADD https://gitee.com/mirrors/cpython/raw/3.7/Lib/typing.py /usr/local/python3.7.0/lib/python3.7

WORKDIR /PaddleOCR

RUN pip3.7 install -r requirements.txt -i https://mirror.baidu.com/pypi/simple && mkdir -p /PaddleOCR/inference/

ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar /PaddleOCR/inference/

RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_det_infer.tar -C /PaddleOCR/inference/ && tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/ && tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_rec_infer.tar -C /PaddleOCR/inference/ 

EXPOSE 9890

CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system -p 9890"]`

运行报错
![image](https://user-images.githubusercontent.com/32086491/153350523-c135f452-9550-4415-922f-188a6b3fde50.png)

**Comment by LDOUBLEV** [comment]
```
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar /PaddleOCR/inference/
```

这个三个模型没有下载成功吧

**Comment by dreamfly32** [comment]
> ```
> ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar /PaddleOCR/inference/
> ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
> ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar /PaddleOCR/inference/
> ```
> 
> 这个三个模型没有下载成功吧

成功了，不成功镜像生不成

**Comment by yinjw1994** [comment]
创建docker项目时cd到项目根目录/PaddleOCR，而不是在deploy\docker\hubserving\cpu
