### ISSUE TITLE
Error in ONNX convertion

### ISSUE THREAD

**Issue by shekarneo** [PaddlePaddle/PaddleOCR#5438]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.7.11 cpu
- 版本号/Version：Paddle：2.2.1  PaddleOCR：2.4  问题相关组件/Related components：
- 运行指令/Command Code：paddle2onnx --model_dir=./models/rec/en/en_number_mobile_v2.0_rec_infer --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./onnx/server_rec_model.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "/home/neo/anaconda3/envs/OCR/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')())
  File "/home/neo/anaconda3/envs/OCR/lib/python3.7/site-packages/paddle2onnx-0.9.0-py3.7.egg/paddle2onnx/command.py", line 195, in main
  File "/home/neo/anaconda3/envs/OCR/lib/python3.7/site-packages/paddle2onnx-0.9.0-py3.7.egg/paddle2onnx/command.py", line 149, in program2onnx
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected found == true, but received found:0 != true:1.] (at /paddle/paddle/fluid/framework/attribute.h:229)
  [operator < matmul > error]

I am unable to convert rec and cls models into onnx format, but det models are converting fine.

**Comment by jiangjiajun** [comment]
删除转换命令中的 --input_shape_dict="{'x': [-1, 3, -1, -1]}"  可转换成功

**Comment by shekarneo** [comment]
Thanks it worked, but by default inference happening in chinees, how can i set language option while inferencing using onnx model.

**Comment by shekarneo** [comment]
I tried this and it gave some warnings about version incompatibility, let
me check the versions and let you know.

**Comment by shekarneo** [comment]
@jiangjiajun  i installed the exact version of paddle, but still facing the same error:

Traceback (most recent call last):
  File "/home/neo/anaconda3/envs/OCR/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')())
  File "/home/neo/anaconda3/envs/OCR/lib/python3.7/site-packages/paddle2onnx-0.9.0-py3.7.egg/paddle2onnx/command.py", line 195, in main
  File "/home/neo/anaconda3/envs/OCR/lib/python3.7/site-packages/paddle2onnx-0.9.0-py3.7.egg/paddle2onnx/command.py", line 149, in program2onnx
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected attrs_.count(name) != 0, but received attrs_.count(name):0 == 0:0.] (at /paddle/paddle/fluid/framework/attribute.h:213)
  [operator < matmul > error]

**Comment by shekarneo** [comment]
@jiangjiajun Any suggestions on this?

**Comment by jiangjiajun** [comment]
could you upload your paddle model here?

**Comment by shekarneo** [comment]
[en_number_mobile_v2.0_rec_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/8085881/en_number_mobile_v2.0_rec_infer.zip)
[ch_ppocr_mobile_v2.0_cls_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/8085882/ch_ppocr_mobile_v2.0_cls_infer.zip)

**Comment by shekarneo** [comment]
I installed the version and tried but still same error, anyway thanks.

**Comment by sicklife** [comment]
I meet with the same issue~

**Comment by jiangjiajun** [comment]
@shekarneo @sicklife 

Please try to reinstall paddle2onnx, to fix this problem
```
pip uninstall paddle2onnx
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
git checkout infer_shape
python setup.py install
```
and then convert the model again

**Comment by shekarneo** [comment]
Hi jason, i have tried that already.

**Comment by jiangjiajun** [comment]
@shekarneo I noticed that we have talk this problem early, and I just update Paddle2ONNX this week, you can try to reinstall Paddle2ONNX with branch `infer_shape`, this will solve your problem

**Comment by shekarneo** [comment]
Thanks jason will test it.

**Comment by shekarneo** [comment]
I tried with new paddle2onnx  and it is working fine, thanks.
