### ISSUE TITLE
PPOCRv2 on Jetson Xavier NX

### ISSUE THREAD

**Issue by pk-cb** [PaddlePaddle/PaddleOCR#5440]
Hi, does any one have luck running PPOCRv2 successfully on Jetson NX? 

I am facing issues to install paddlepaddle while using `paddleocr` from pip. not able to find .whl files indexed.

**Comment by EternalSaga** [comment]
It's highly recommend to build paddle from source on Jetson Xavier NX.  You can refer to this article [https://qengineering.eu/install-paddle-on-jetson-nano.html](url)
This article helped me a lot. I have already run ppocr on jetson nx successfully.

**Comment by ranjithlesoko** [comment]
please help to fix in nx xavier
