### ISSUE TITLE
Training Error "invalid poly"

### ISSUE THREAD

**Issue by shraddha291996** [PaddlePaddle/PaddleOCR#5441]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
Hello,
I am facing an error invalid poly while training my custom model using pgnet algorithm. Can anyone please suggest what could be the issue 
- 系统环境/System Environment：venv
- 版本号/Version：Paddle：2.3.0.1  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：training command - python tools/train.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=./pretrain_models/train_step1/best_accuracy Global.load_static_weights=False
- 完整报错/Complete Error Message：invalid poly
thank you in advance!

**Comment by haiderasad** [comment]
@shraddha291996 did you find any solution?

**Comment by creatorHJJ** [comment]
i have got the same problem
