### ISSUE TITLE
onnx模型在gpu机子上速度没有inference模型速度快

### ISSUE THREAD

**Issue by sangwentao** [PaddlePaddle/PaddleOCR#5445]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

我转换成onnx模型之后，在cpu机子上的推理速度要比inference模型快很多
但是在gpu的机子上跑。onnx模型比inference模型慢很多，onnxruntime也是gpu版本的
这个是为什么？

**Comment by sangwentao** [comment]
> 你这个具体用的是哪个模型？

ocr的模型，DB和CRNN，用的都是大模型，40M和100M的模型

**Comment by tink2123** [comment]
1.  Paddle-Inference 做了很多算子融合的加速策略
2. 这与ONNX的执行策略有关，由于模型中存在大量shape和constant的操作，这几个op计算在onnx中必须执行在CPU上，为了避免数据拷贝，onnx把网络结构前后整块操作都放在了cpu上，导致识别模型预测速度很慢。

**Comment by tink2123** [comment]
另外方便提供一下CPU上的速度对比数据吗～ 可以帮助我们优化预测性能

**Comment by sangwentao** [comment]
> 1. Paddle-Inference 做了很多算子融合的加速策略
> 2. 这与ONNX的执行策略有关，由于模型中存在大量shape和constant的操作，这几个op计算在onnx中必须执行在CPU上，为了避免数据拷贝，onnx把网络结构前后整块操作都放在了cpu上，导致识别模型预测速度很慢。

哦哦知道了，那有解决办法嘛，还是只能这样了

**Comment by sangwentao** [comment]
> 另外方便提供一下CPU上的速度对比数据吗～ 可以帮助我们优化预测性能

同一张图片
这个是onnx模型的输出时间：
[2022/02/11 16:42:42] root INFO: Predict time of C:\Users\swt\Desktop\img_test\img.png: 2.372s

这个是inference模型的时间：
[2022/02/11 16:44:03] root INFO: The predict total time is 9.45769739151001

**Comment by tink2123** [comment]
> 哦哦知道了，那有解决办法嘛，还是只能这样了

需要onnx那边修改，暂时只能这样了

>同一张图片
这个是onnx模型的输出时间：
[2022/02/11 16:42:42] root INFO: Predict time of C:\Users\swt\Desktop\img_test\img.png: 2.372s
这个是inference模型的时间：
[2022/02/11 16:44:03] root INFO: The predict total time is 9.45769739151001

好的，感谢反馈

**Comment by luodaoyi** [comment]
有啥办法能让它快点么？ 原生部署必须得cuda11.6啊

**Comment by luodaoyi** [comment]
我们的生产环境只能支持到11.4

**Comment by QQQTAO** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> 我转换成onnx模型之后，在cpu机子上的推理速度要比inference模型快很多 但是在gpu的机子上跑。onnx模型比inference模型慢很多，onnxruntime也是gpu版本的 这个是为什么？

你好，向你请教一下使用onnxruntime可以同时在GPU上进行ocr文本检测、方向分类、识别吗，GPU比CPU能快多少
