### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#5447]
![image](https://user-images.githubusercontent.com/88916218/153539599-ee757228-6e3d-4f0d-a315-d16774dcd1a3.png)
Can you help me solve this problem? I start training SEED model but the error.
Best regard

**Comment by andyjpaddle** [comment]
can you show me the whole command and error, including changes you have did

**Comment by huylgia** [comment]
Tks ad, I fixed error

**Comment by LeoRainly** [comment]
> Tks ad, I fixed the error but I don't know why I can fix it :))))

How did you fix it?  I have had the same problem
