### ISSUE TITLE
[Recognition] Training SAR model error

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#5450]
![Screenshot from 2022-02-11 14-32-20](https://user-images.githubusercontent.com/88916218/153552936-c4aebe6f-32b4-4b00-9dac-6e9e3b7c0e9a.png)
I start training with "rec_r31_sar.yml" but I meet the error as the figure. 
I hope you can help me solve the problem.
Best regard!

**Comment by andyjpaddle** [comment]
you should change the params `ignore_index`  in this line https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/losses/rec_sar_loss.py#L13
the value should be `num_classes +2`,  eg, if your dict is 90 classes, the value is 92.

**Comment by huylgia** [comment]
tks ad
