### ISSUE TITLE
自定义数据集在检测时候报错

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5468]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu-20  cuda-11.0  gpu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
102.6s	163	C++ Traceback (most recent call last):
102.6s	164	--------------------------------------
102.6s	165	No stack trace in paddle, may be caused by external reasons.
102.6s	166	
102.6s	167	----------------------
102.6s	168	Error Message Summary:
102.6s	169	----------------------
102.6s	170	FatalError: `Segmentation fault` is detected by the operating system.
102.6s	171	[TimeInfo: *** Aborted at 1643598937 (unix time) try "date -d @1643598937" if you are using GNU date ***]
102.6s	172	[SignalInfo: *** SIGSEGV (@0x0) received by PID 25 (TID 0x7f5ac8026740) from PID 0 ***]

**Comment by dlnu-wkx** [comment]
<html>
<body>


94.6s | 162 | --------------------------------------
-- | -- | --
94.6s | 163 | C++ Traceback (most recent call last):
94.6s | 164 | --------------------------------------
94.6s | 165 | No stack trace in paddle, may be caused by external reasons.
94.6s | 166 |  
94.6s | 167 | ----------------------
94.6s | 168 | Error Message Summary:
94.6s | 169 | ----------------------
94.6s | 170 | FatalError: `Segmentation fault` is detected by the operating system.
94.6s | 171 | [TimeInfo: *** Aborted at 1644731720 (unix time) try "date -d @1644731720" if you are using GNU date ***]
94.6s | 172 | [SignalInfo: *** SIGSEGV (@0x0) received by PID 24 (TID 0x7f9238938740) from PID 0 ***]
94.6s | 173 |  
95.8s | 174 | Traceback (most recent call last):
95.8s | 175 | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 838, in async_execute_cell
95.8s | 176 | exec_reply = await self.task_poll_for_reply
95.8s | 177 | concurrent.futures._base.CancelledError
95.8s | 178 |  
95.8s | 179 | During handling of the above exception, another exception occurred:
95.8s | 180 |  
95.8s | 181 | Traceback (most recent call last):
95.8s | 182 | File "<string>", line 1, in <module>
95.8s | 183 | File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 118, in execute_notebook
95.8s | 184 | **engine_kwargs
95.8s | 185 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
95.8s | 186 | return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
95.8s | 187 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
95.8s | 188 | cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
95.8s | 189 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
95.8s | 190 | return PapermillNotebookClient(nb_man, **final_kwargs).execute()
95.8s | 191 | File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 45, in execute
95.8s | 192 | self.papermill_execute_cells()
95.8s | 193 | File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
95.8s | 194 | self.execute_cell(cell, index)
95.8s | 195 | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
95.8s | 196 | return just_run(coro(*args, **kwargs))
95.8s | 197 | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
95.8s | 198 | return loop.run_until_complete(coro)
95.8s | 199 | File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
95.8s | 200 | return future.result()
95.8s | 201 | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 842, in async_execute_cell
95.8s | 202 | raise DeadKernelError("Kernel died")
95.8s | 203 | nbclient.exceptions.DeadKernelError: Kernel died
98.0s | 204 | /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2567: FutureWarning: --Exporter.preprocessors=["remove_papermill_header.RemovePapermillHeader"] for containers is deprecated in traitlets 5.0. You can pass `--Exporter.preprocessors item` ... multiple times to add items to a list.
98.0s | 205 | FutureWarning,
98.0s | 206 | [NbConvertApp] Converting notebook __notebook__.ipynb to notebook
98.9s | 207 | [NbConvertApp] Writing 43610 bytes to __notebook__.ipynb
101.1s | 208 | /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2567: FutureWarning: --Exporter.preprocessors=["nbconvert.preprocessors.ExtractOutputPreprocessor"] for containers is deprecated in traitlets 5.0. You can pass `--Exporter.preprocessors item` ... multiple times to add items to a list.
101.1s | 209 | FutureWarning,
101.1s | 210 | [NbConvertApp] Converting notebook __notebook__.ipynb to html
101.8s | 211 | [NbConvertApp] Writing 308177 bytes to __results__.html


</body>
</html>

**Comment by WenmuZhou** [comment]
你好，辛苦提供一下数据集和训练的配置文件

**Comment by sicklife** [comment]
> 已经解决了是paddlepaddle-gpu版本的问题

换成哪个版本解决的？
