### ISSUE TITLE
不同版本模型格式

### ISSUE THREAD

**Issue by gdwu1427** [PaddlePaddle/PaddleOCR#5470]
您好！
        请教一下，paddleOCR 1.8版本的模型格式model、params 能转换为2.0版本的inference.pdmodel inference.pdiparams么

**Comment by littletomatodonkey** [comment]
你好，model对应inference.pdmodel ，params对应inference.pdiparams，但是1.8和最新动态图的处理方法不太一样，建议直接使用2.x版本的模型

**Comment by gdwu1427** [comment]
能转化方法么，因为之前1.8训练出来的模型精度比较高，现在想用2.0以上版本调用1.8训练出来的模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月17日(周四) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 不同版本模型格式 (Issue #5470)




 
你好，model对应inference.pdmodel ，params对应inference.pdiparams，但是1.8和最新动态图的处理方法不太一样，建议直接使用2.x版本的模型
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
