### ISSUE TITLE
问一下，我要识别的文字背景都是不一样的，就是视频画面右下角的文字，字体是标准的宋体，这种训练还有必要吗?谢谢！

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5471]
问一下，我要识别的文字背景都是不一样的，就是视频画面右下角的文字，字体是标准的宋体，这种训练还有必要吗?谢谢！

**Comment by littletomatodonkey** [comment]
你好，可以直接尝试paddleocr的模型，应该可以搞定大部分的识别问题，但是如果希望精度更高的话，建议再finetune一下
