### ISSUE TITLE
为什么ppocrlable在导出识别结果的时候会有奇怪的数据换行

### ISSUE THREAD

**Issue by EternalSaga** [PaddlePaddle/PaddleOCR#5477]
Windows系统使用pip安装ppocrlabel之后，使用识别结果导出功能，导出的rec_gt.txt文件当中，会有奇怪的换行，比如这个结果

crop_img/20211225T105849.545619_crop_0.jpg	660390货城盐苏

在写入rec_gt.txt之后会被奇怪的分割成

crop_img/20211225T105849.545619_crop_0.jpg	
660390货城盐苏

我使用rec_gt.txt这个文件在分割训练集测试集的时候，遇到了很多这个麻烦

**Comment by Evezerest** [comment]
文件名与标签之间是通过 ‘\t’来进行分割的，被分成两行表示用'\n'来分割了。rec_gt.txt的所有label都变为‘\n’分割了吗？

**Comment by Evezerest** [comment]
能否发一下出现错误的图片我们测试一下呢，这个问题是一定会出现的吗？
