### ISSUE TITLE
端侧部署

### ISSUE THREAD

**Issue by zhangyaobo** [PaddlePaddle/PaddleOCR#548]
执行到 make -j 时候报错：
Makefile:4: ../Makefile.def: No such file or directory

**Comment by lijianshe02** [comment]
请详细描述相关问题

**Comment by LDOUBLEV** [comment]
> 执行到 make -j 时候报错：
> Makefile:4: ../Makefile.def: No such file or directory

按照教程的步骤是没问题的，是否是make -j的目录不对
