### ISSUE TITLE
如何增强对手写体的识别准确率

### ISSUE THREAD

**Issue by CaesarRyan** [PaddlePaddle/PaddleOCR#5480]
我的使用场景类似于表单，既有打印体，也有手写体数字，在使用默认的识别模型时，我发现对打印体的识别已经很好了，然后手写体和打印体的结合并不理想，所以我想是否有方法可以在原推理模型的基础上增强对手写体识别的准确率呢？尽量减少原模型对打印体识别的准确率

**Comment by yjhtc007** [comment]
我个人感觉可以尝试两种方案：
1.混合打印体数据与手写体数据训练一个新的文本识别模型；
2.可以针对打印体和手写体训练两个不同的模型，用于单独检测打印体和手写体。

**Comment by CaesarRyan** [comment]
> 我个人感觉可以尝试两种方案： 1.混合打印体数据与手写体数据训练一个新的文本识别模型； 2.可以针对打印体和手写体训练两个不同的模型，用于单独检测打印体和手写体。

感谢您的方案：
1. 混合打印体和手写体数据目前识别的准确性较差，检测模型倒是不错，我不确定混合训练是否可以有效，因为不太了解识别模型的原理，主要就是对于多字如何处理的
2. 这个方案其实是可以尝试的，但感觉这样也增加了运算耗时，更期望了解多字识别的原理后，在第一种方式上调整
