### ISSUE TITLE
识别大分辨率的图片很难

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleOCR#5485]
图片3300*2550，上面字比较密集，识别效果很差
![7cC2B453ZY - 副本](https://user-images.githubusercontent.com/94092329/154024881-4d4e8dae-2084-402c-aade-a4d97db044c7.png)

只能识别出一小点内容
![test](https://user-images.githubusercontent.com/94092329/154025192-9833ba94-1228-47b3-a907-0ae9447c35dd.png)

这个有什么解决方案吗？
我目前想的是切成小图，但是切完后再拼接又比较难，字被分割的话还影响效果

**Comment by zouhan6806504** [comment]
结果图错了，是这个
![result](https://user-images.githubusercontent.com/94092329/154026021-aedb649c-aaff-456c-bd6d-8536ae0e99a8.jpg)

**Comment by MissPenguin** [comment]
输入图片会被resize到长边960，这种大图resize后可能就看不清了，影响效果，可以试试把尺度调大

**Comment by cgq0816** [comment]
> 结果图错了，是这个 ![result](https://user-images.githubusercontent.com/94092329/154026021-aedb649c-aaff-456c-bd6d-8536ae0e99a8.jpg)

我也遇到同样的问题，请问一下这个问题解决了吗？

**Comment by sunfan1997** [comment]
> 

det_limit_side_len这个参数调大试试
