### ISSUE TITLE
训练时提示路径找不到怎么解决？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5488]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： 2.4 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：训练时提示路径找不到怎么解决？
![QQ图片20220216064901](https://user-images.githubusercontent.com/41010669/154163017-5f8ca35e-9ef3-44ca-8dea-16977449e429.png)

**Comment by nissansz** [comment]
把label.txt里的缩写路径改成绝对路径可以用了
testtrain/1.png	[{"transcription": "怎么办 怎么办", "points": [[493, 28], [787, 28], [787, 69], [493, 69]], "difficult": false}]

改成  L:\jpdrama\testtrain\1.png	[{"transcription": "怎么办 怎么办", "points": [[493, 28], [787, 28], [787, 69], [493, 69]], "difficult": false}]

win10下一定要改吗？

**Comment by LDOUBLEV** [comment]
应该是你的路径格式不对吧：
![image](https://user-images.githubusercontent.com/26592129/154473895-99029330-03f3-4991-aa8a-28fc6afa29cf.png)

可以改一下格式

**Comment by nissansz** [comment]
后面训练成功了。但是生成的推理模型不能用是怎么回事？
https://pastebin.com/1VDrb9hQ

Traceback (most recent call last):
  File "F:/pycharm2020.2/paddleTest/ocr.py", line 68, in <module>
    ocr(img_path)
  File "F:/pycharm2020.2/paddleTest/ocr.py", line 18, in ocr
    ocr = PaddleOCR(use_angle_cls=True,
  File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\paddleocr.py", line 343, in __init__
    super().__init__(params)
  File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_det.py", line 107, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\utility.py", line 304, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_13.w_2 
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\ir\conv_bn_fuse_pass.cc:101)
 
 
Process finished with exit code 1

**Comment by kylewangt** [comment]
> 后面训练成功了。但是生成的推理模型不能用是怎么回事？ https://pastebin.com/1VDrb9hQ
> 
> Traceback (most recent call last): File "F:/pycharm2020.2/paddleTest/ocr.py", line 68, in ocr(img_path) File "F:/pycharm2020.2/paddleTest/ocr.py", line 18, in ocr ocr = PaddleOCR(use_angle_cls=True, File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\paddleocr.py", line 343, in **init** super().**init**(params) File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_system.py", line 45, in **init** self.text_detector = predict_det.TextDetector(args) File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_det.py", line 107, in **init** self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor( File "C:\Users\Ni\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\utility.py", line 304, in create_predictor predictor = inference.create_predictor(config) ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_13.w_2 [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\ir\conv_bn_fuse_pass.cc:101)
> 
> Process finished with exit code 1

请问，问题有解决吗？

**Comment by nissansz** [comment]
解决了。

**Comment by kylewangt** [comment]
> 解决了。

是什么原因呢？我也遇到相同的问题了

**Comment by nissansz** [comment]
多换几种路径写法

**Comment by kylewangt** [comment]
> 多换几种路径写法

什么路径呢？我是在模型推理的时候报错的
