### ISSUE TITLE
训练完的模型使用时报错，怎么解决的？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5489]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  2.4 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
训练完的模型使用时报错，怎么解决的？微信nlanguage

L:\PaddleOCR\PaddleOCR-release-2.4>py -3 tools/infer/predict_system.py --image_dir="L:\jpdrama\testtrain\1.png" --det_model_dir="L:\PaddleOCR\PaddleOCR-release-2.4\output\db_mv3_infer" --rec_model_dir="./inference/japan_mobile_v2.0_rec_infer/" --use_gpu=False --rec_char_dict_path="./ppocr/utils/dict/japan_dict.txt"
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 204, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 127, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "L:\PaddleOCR\PaddleOCR-release-2.4\tools\infer\predict_det.py", line 106, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "L:\PaddleOCR\PaddleOCR-release-2.4\tools\infer\utility.py", line 303, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_13.w_2
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\ir\conv_bn_fuse_pass.cc:101)

**Comment by EternalSaga** [comment]
一样错误，不过我是使用cpp inference的时候报了这个错误，直接用过python inference没问题

**Comment by EternalSaga** [comment]
这是在Linux Ubuntu 20.04下的报错
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_6.w_2 
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:101)

**Comment by nissansz** [comment]
有解决办法吗？




发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: EternalSaga  ***@***.***>
 

 
 发送时间: 2022-02-17 13:29:40
 

 
 收件人: PaddlePaddle/PaddleOCR  ***@***.***> 
 

 
 抄送: nissansz  ***@***.***>,Author  ***@***.***> 
 

 
 主题: Re: [PaddlePaddle/PaddleOCR] 训练完的模型使用时报错，怎么解决的？微信nlanguage (Issue #5489)
 





 这是在Linux Ubuntu 20.04下的报错 Error Message Summary: InvalidArgumentError: The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_6.w_2
 [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:101)

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDOUBLEV** [comment]
"L:\PaddleOCR\PaddleOCR-release-2.4\output\db_mv3_infer" 
这个模型是你自己导出的吗，
可以先试一下官方的模型：https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar


ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_13.w_2
这个报错像是转inference模型的时候 训练参数没有加载到模型里去，导致BN的参数就是初始化的参数；或者是模型没有训练好

**Comment by nissansz** [comment]
官方模型可以用。也是在官方的训练模型上测试10张图。
训练完结果在这里
L:\PaddleOCR\PaddleOCR-release-2.4\output\db_mv3

训练生成推理模型，参数如下
python tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.checkpoints=./output/db_mv3/iter_epoch_1200 Global.save_inference_dir=./output/db_mv3_infer/

怎么才能知道错在哪里？怎样修正？

**Comment by Forlife561** [comment]
解决了吗哥，我这也报这个错

**Comment by kylewangt** [comment]
我的原因是模型存放的路径出现了中文，没有中文的话就没问题。
