### ISSUE TITLE
paddle模型转化onnx模型报错

### ISSUE THREAD

**Issue by supyer9** [PaddlePaddle/PaddleOCR#549]
paddle模型转化onnx模型报了如下图所示的错误，请问该如何解决
![image](https://user-images.githubusercontent.com/54097420/90376674-69f54d00-e0a9-11ea-8f50-ee668683ab90.png)

**Comment by LDOUBLEV** [comment]
目前还不支持转onnx模型，后面支持后会在主页通知，请关注

**Comment by supyer9** [comment]
@LDOUBLEV 您好，我是参考的第213个问题中给的答案来进行转换的，他检测模型转onnx成功了。这是怎么回事呢？
![image](https://user-images.githubusercontent.com/54097420/90477851-af278680-e15e-11ea-9a1f-cfa9f17ee4c2.png)

**Comment by LDOUBLEV** [comment]
你转换的是哪个检测模型？

**Comment by supyer9** [comment]
@LDOUBLEV 
x2paddle -f paddle2onnx -m ch_det_mv3_db -s ./output
转化的是 mobilenetv3 db 检测模型

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV
> x2paddle -f paddle2onnx -m ch_det_mv3_db -s ./output
> 转化的是 mobilenetv3 db 检测模型

![image](https://user-images.githubusercontent.com/26592129/90479326-134b4a00-e161-11ea-8a71-d38dc99d8acb.png)
是否对ch_det_mv3_db文件夹下的两个文件重新命名？

**Comment by supyer9** [comment]
> > @LDOUBLEV 
> > x2paddle -f paddle2onnx -m ch_det_mv3_db -s ./输出转换
> > 的是mobilenetv3 db检测模型
> 
> ![图片](https://user-images.githubusercontent.com/26592129/90479326-134b4a00-e161-11ea-8a71-d38dc99d8acb.png)
> 是否对ch_det_mv3_db文件夹下的两个文件重新命名？

是的，重命名了

**Comment by AIpioneer** [comment]
目前还不支持。方便联系一下吗（微信/手机 I52IO59八六五八）

**Comment by supyer9** [comment]
> 目前还不支持。方便联系一下吗（微信/手机 I52IO59八六五八）

已加

**Comment by leondgarse** [comment]
我这边环境下，检测模型可以通过指定 `--onnx_opset` 转换成功
```sh
x2paddle -f paddle2onnx -m ./ -s aaa --onnx_opset 11
```
识别模型不可以

**Comment by daixiangzi** [comment]
请问可以转换动态的onnx？
