### ISSUE TITLE
问一下行距为0的两行字识别不出来，有什么参数可以调吗？

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5490]
问一下行距为0的两行字识别不出来，有什么参数可以调吗？
比如

**Comment by linkewei0580** [comment]
![image](https://user-images.githubusercontent.com/75007961/154179021-27e92fd4-52c3-46c7-aade-42f5be425ea3.png)

**Comment by yjhtc007** [comment]
是文本检测模型检测的效果不好吗？

**Comment by linkewei0580** [comment]
> 是文本检测模型检测的效果不好吗？

是的

**Comment by LDOUBLEV** [comment]
测试了下，检测结果是：
![image](https://user-images.githubusercontent.com/26592129/154470162-bf4527ab-4bc8-48af-adc4-af947e7f9df7.png)


这类情况没办法通过调参数解决了

**Comment by linkewei0580** [comment]
> 测试了下，检测结果是： ![image](https://user-images.githubusercontent.com/26592129/154470162-bf4527ab-4bc8-48af-adc4-af947e7f9df7.png)
> 
> 这类情况没办法通过调参数解决了

是否可以通过自己的训练，最后能识别吗？谢谢！

**Comment by chenhongen** [comment]
最后怎么处理的。
