### ISSUE TITLE
运行推理命令怎么报错呢

### ISSUE THREAD

**Issue by allen20200111** [PaddlePaddle/PaddleOCR#5495]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7 docker 根据指南配置的
- 版本号/Version：Paddle：  PaddleOCR： 
- 问题相关组件/Related components：
- 运行指令/Command Code：
- λ localhost /paddle/PaddleOCR {release/2.4} python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_12.jpg" --det_model_dir="./inference/ch_det_r50_vd_db"  --rec_model_dir="./inference/ch_rec_r34_vd_crnn_enhance" --use_space_char=True
- 完整报错/Complete Error Message：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022/02/16 06:06:52] root DEBUG: dt_boxes num : 10, elapse : 2.042548418045044
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 204, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 151, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 88, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/paddle/PaddleOCR/tools/infer/predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "/paddle/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 94, in __call__
    preds_idx = preds.argmax(axis=2)
AttributeError: 'list' object has no attribute 'argmax'
λ localhost /paddle/PaddleOCR {release/2.4}

**Comment by LDOUBLEV** [comment]
"./inference/ch_det_r50_vd_db
"./inference/ch_rec_r34_vd_crnn_enhance"
这两个模型是从哪下载的


我这边用从[官网下载的inference 模型](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th)预测是可以的
 python3.7 tools/infer/predict_system.py --det_model_dir=./inference/ch_ppocr_server_v2.0_det_infer/ --rec_model_dir=./inference/ch_PP-OCRv2_rec_infer/ --image_dir=./doc/imgs_en/img_12.jpg  --use_space_char=True

<img width="716" alt="image" src="https://user-images.githubusercontent.com/26592129/154469507-b4b16cc1-f2ce-411f-bade-ad3cdd7f7577.png">
