### ISSUE TITLE
PaddleOCR-2.4加载官方ch_PP-OCRv2_rec_train预训练模型 加载参数失败

### ISSUE THREAD

**Issue by d597797974** [PaddlePaddle/PaddleOCR#5496]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR-2.4： 问题相关组件/Related components：
- 运行指令/Command Code：
- python tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml
![image](https://user-images.githubusercontent.com/65281097/154208806-727e8a3f-53ae-4768-8689-efac7546a63a.png)

- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/65281097/154209269-5b4fba37-8791-4860-b4fb-54c7a785cc43.png)

**Comment by LDOUBLEV** [comment]
可以参考这部分文档调整预训练模型：
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/knowledge_distillation.md#215-%E8%92%B8%E9%A6%8F%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83
