### ISSUE TITLE
使用SEED文本识别算法进行训练，参数设置相关问题?

### ISSUE THREAD

**Issue by guanrenxue** [PaddlePaddle/PaddleOCR#5497]
使用rec_resnet_stn_bilstm_att.yml配置文件：

Architecture:
  model_type: rec
  algorithm: SEED
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64] 
    tps_outputsize: [32, 100] 
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: ResNet_ASTER
  Head:
    name: AsterHead  # AttentionHead
    sDim: 512
    attDim: 512
    max_len_labels: 100 

此时的训练图像尺寸为：640x32x3，不知道tps_inputsize 和tps_outputsize如何设置，请问tps_inputsize: [32, 64] ，tps_outputsize: [32, 640] 设置是否正确，有什么设置技巧？此外max_len_labels是否和max_text_length保持一致？不一致又该如何设置！

**Comment by tink2123** [comment]
1. tps_inputsize : [32, 64],  tps_outputsize:[32,640] 设置没有问题，但是如果训练集不是特别长的样本，不需要把宽度设置的这么大，可能会影响效果。 
2. max_len_labels 和 max_text_length 不需要保持一致，max_text_length 限制训练集label最大长度，max_len_labels 限制输出解码的字符最大长度。
