### ISSUE TITLE
重新训练的检测模型，转成nb文件后效果不好

### ISSUE THREAD

**Issue by lrjj** [PaddlePaddle/PaddleOCR#5499]
我想问问，这个链接的这个（https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md）
![image](https://user-images.githubusercontent.com/68632486/154223190-d38e964d-6369-4daf-8854-4ffd5a29d505.png)
官方的提供的模型是拿哪个文件训练的？
检测模型训练我是用"PaddleOCR-release-2.4/PaddleOCR-release-2.4/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml"训练时效果可以，其中hmean: 0.9270118527760449, precision: 0.9150246305418719, recall: 0.9393173198482933, fps: 30.350768379348327 ，转换为inference.pdmodel和inference.pdiparams测试效果也是好的，但是转换为nb模型时效果极差，我adb push进行测试：
官方模型：./ocr_db_crnn system  ch_ppocr_mobile_v2.0_det_slim_opt.nb ch_ppocr_mobile_v2.0_rec_slim_opt.nb ch_ppocr_mobile_v2.0_cls_slim_opt.nb armv8 FP32 4 1 ./11.jpg config.txt ppocr_keys_v1.txt 
![aabcbbf802e38d12c202c6fb43f9a86](https://user-images.githubusercontent.com/68632486/154224320-c5e04a21-042e-459d-81c3-acd4fb88c835.png)
我单独测试自己重新训练的检测模型（因为设置mode为system时没有识别到文字）：./ocr_db_crnn det my_ch_ppocr_mobile_v2.0_det_opt.nb  armv8 FP32 4 1 ./douyin_2x0.5.jpg config.txt  
![5f8da085b89db508b98f6995671d814](https://user-images.githubusercontent.com/68632486/154224634-205ac89c-b18a-414e-adfc-2b9632d2781f.png)

其中可以看到，单独测试自己重新训练的检测模型可以返回一个文本框（但是我看这个框框不对地方），是不是说明我的paddle-lite动态库的版本和opt的版本没有问题呢？我想看看opt的版本，但是./opt -version指令只是返回“opt”,没有版本信息，但是我自己的检测模型paddle-lite动态库的版本和opt的版本是一致的，但是不知道是不是和官方的模型是不是一致（但是官方模型push是正常的），我重新训练的检测模型转成nb文件后效果不好的原因是什么呢？

**Comment by LDOUBLEV** [comment]
v1.1版本的模型和2.4分支的代码不兼容，建议你用；
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/models_list.md#4-paddle-lite-%E6%A8%A1%E5%9E%8B

**Comment by lrjj** [comment]
> v1.1版本的模型和2.4分支的代码不兼容，建议你用； https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/models_list.md#4-paddle-lite-%E6%A8%A1%E5%9E%8B

非常感谢你的回复！这个问题困扰我很久了，但是还是没有解决，我的模型也是用V2版本训练的，我使用官方训练好的模型是可以运行的，但是我用官方代码重新训练模型转成nb文件就不行，我现在再次进行版本对齐再跑了一遍，还是不行。下面我附上我的nb模型，训练模型的config文件，可以帮我看看是不是代码哪里没有对齐嘛？

版本对齐：
（1）重新训练模型的代码：PaddleOCR release2.4
（2）android_demo:PaddleOCR release2.4里面的android_demo（我重新下载了现在目前最新的，不做任何修改）
（3）训练好的模型转NB文件：paddle-liteV2.9

相关指令：
（1）模型训练：
    训练了两个检测模型：
1）PaddleOCR release2.4里面的"PaddleOCR-release-2.4/configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml"以及  2）"PaddleOCR-release-2.4/configs/det/det_mv3_db.yml" 两个yml文件和训练好的模型见附带压缩包
（2）转换为NB文件：
![image](https://user-images.githubusercontent.com/68632486/154478187-0abb7186-fa4d-4d09-8fb7-63de6cbe0660.png)

相关文件：


[相关测试文件.zip](https://github.com/PaddlePaddle/PaddleOCR/files/8088578/default.zip)


目前测试结果：
两张测试图片，
（1）第一张：分辩率w*h=981x632
![3230a7956f666f60708262cc9ab83ac](https://user-images.githubusercontent.com/68632486/154478813-97636d00-b9df-4ca0-bc7c-184ceef7da84.jpg)
（2）第二张：分辩率w*h=472x317(这一张图片来自模型训练的训练集)
![7c7b195c88f9a2504b94631ea9cdebe](https://user-images.githubusercontent.com/68632486/154479287-c5cc705a-56fa-4019-b9d0-f487cc11e553.png)

1）模型的测试结果，模型名称为my_ch_det_mv3_db_v2.0_opt.nb，上面两张图片都没有检测到任何内容，如下所示
![c93d5ee7ba7de2e2e06e14d9961ee1f](https://user-images.githubusercontent.com/68632486/154479636-98b22aac-1dad-4397-9be0-d4bf73a8e208.jpg)
2）模型的测试结果，模型名称为my_db_mv3_opt.nb，第一张图片能成功检测如下所示，第二张图片没有检测到任何内容，就如同上面那张图所示。
![9d7eec23b20fbdc09f71b8d06e8ec34](https://user-images.githubusercontent.com/68632486/154479946-c5b49c3a-e9df-434f-a3f3-9d19811e5db7.jpg)

**Comment by lrjj** [comment]
问题已解决，我修改了训练模型的配置文件重新训练就好了

**Comment by huangwenbiao** [comment]
请问您是具体怎么修改的呢？

**Comment by 0xjacklove** [comment]
请问怎么修改的啊
