### ISSUE TITLE
关于模型finetune

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5500]
请问一下，我用PPLabel对图像进行自动标注，是能够识别一串正确的字符，但是我用该标注下对应的模型作为我的预训练模型进行finetune训练（我没有将该字符作为训练集），最终的结果无法读取该字符，请问这种情况正常吗？有什么具体原因吗？

**Comment by LDOUBLEV** [comment]
最终的结果无法读取该字符 是指？

可以发一下运行指令和相应的报错信息

**Comment by 18362890185** [comment]
> 最终的结果无法读取该字符 是指？
> 
> 可以发一下运行指令和相应的报错信息

是读错了信息，
![image](https://user-images.githubusercontent.com/87969070/154595421-ca483953-f7d1-4d0a-b738-b22489fb92cf.png)
用预训练模型是可以正确读取的

**Comment by Evezerest** [comment]
可以看一下训练的时候是否正确加载了网络权重
