### ISSUE TITLE
检测迭代了一轮就报错

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5504]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntn 20.3
- 版本号/Version：Paddle：2.2.  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
<html><body>

618.4s | 451 | Traceback (most recent call last):
-- | -- | --
618.4s | 452 | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 838, in async_execute_cell
618.4s | 453 | exec_reply = await self.task_poll_for_reply
618.4s | 454 | concurrent.futures._base.CancelledError
618.4s | 455 |  
618.4s | 456 | During handling of the above exception, another exception occurred:
618.4s | 457 |  
618.4s | 458 | Traceback (most recent call last):
618.4s | 459 | File "<string>", line 1, in <module>
618.4s | 460 | File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 118, in execute_notebook
618.4s | 461 | **engine_kwargs
618.4s | 462 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
618.4s | 463 | return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
618.4s | 464 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
618.4s | 465 | cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
618.4s | 466 | File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
618.4s | 467 | return PapermillNotebookClient(nb_man, **final_kwargs).execute()
618.4s | 468 | File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 45, in execute
618.4s | 469 | self.papermill_execute_cells()
618.4s | 470 | File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
618.4s | 471 | self.execute_cell(cell, index)
618.4s | 472 | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
618.4s | 473 | return just_run(coro(*args, **kwargs))
618.4s | 474 | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
618.4s | 475 | return loop.run_until_complete(coro)
618.4s | 476 | File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
618.4s | 477 | return future.result()
618.4s | 478 | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 842, in async_execute_cell
618.4s | 479 | raise DeadKernelError("Kernel died")
618.4s | 480 | nbclient.exceptions.DeadKernelError: Kernel died
622.6s | 481 | /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2567:  FutureWarning:  --Exporter.preprocessors=["remove_papermill_header.RemovePapermillHeader"]  for containers is deprecated in traitlets 5.0. You can pass  `--Exporter.preprocessors item` ... multiple times to add items to a  list.
622.6s | 482 | FutureWarning,
622.6s | 483 | [NbConvertApp] Converting notebook __notebook__.ipynb to notebook
624.6s | 484 | [NbConvertApp] Writing 68232 bytes to __notebook__.ipynb
626.9s | 485 | /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2567:  FutureWarning:  --Exporter.preprocessors=["nbconvert.preprocessors.ExtractOutputPreprocessor"]  for containers is deprecated in traitlets 5.0. You can pass  `--Exporter.preprocessors item` ... multiple times to add items to a  list.
626.9s | 486 | FutureWarning,
626.9s | 487 | [NbConvertApp] Converting notebook __notebook__.ipynb to html
627.7s | 488 | [NbConvertApp] Writing 334328 bytes to __results__.html

</body>
</html>

**Comment by andyjpaddle** [comment]
请提供一下完整报错截图，不要用表格形式进行描述
