### ISSUE TITLE
关于参数冻结

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5505]
请问一下，我想冻结最后一层的head输出层，是这样把该判断加进去吗？
![屏幕截图 2022-02-17 105156](https://user-images.githubusercontent.com/87969070/154395596-f1ed6090-74c1-4ca9-940e-7d70bd257fe3.png)

还是说下面一种方式？
![屏幕截图 2022-02-17 110414](https://user-images.githubusercontent.com/87969070/154396911-e345a82c-3d46-4060-9118-58c3feb1fbf4.png)

**Comment by andyjpaddle** [comment]
第二种
