### ISSUE TITLE
识别模型infer_rec.py、predict_rec.py 推理与eval.py结果不一致

### ISSUE THREAD

**Issue by gdwu1427** [PaddlePaddle/PaddleOCR#5509]
你好！
      请教一下，相同的测试集 运行eval.py，识别精度有97%，但是运行infer_rec.py精度只有50%不到，有可能是什么原因，用的都是同一个训练模型。谢谢！
python3 tools/eval.py -c /configs/rec/rec_icdar15_train2.yml  -o Global.checkpoints="./output/rec/ic15/best_accuracy"

python3 tools/infer_rec.py -c configs/rec/rec_icdar15_train2.yml -o Global.infer_img="./train_data/ic15_data/test" Global.pretrained_model="./output/rec/ic15/best_accuracy"

**Comment by wstchhwp** [comment]
怎么解决的？？
