### ISSUE TITLE
安装PPOCRLabel后无法打开运行

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleOCR#5512]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux内核 （deepin）
- 版本号/Version：Paddle：最新  PaddleOCR：最新  问题相关组件/Related components：
- 运行指令/Command Code：按照git官方的安装指令（linux的两条）装好后输入PPOCRLabel --lang ch
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/96160062/154630504-a2a1b1af-4a67-4e72-bb2e-5513599f5a92.png)

**Comment by Evezerest** [comment]
初步判断是opencv版本问题，可以先卸载该环境下的opencv，然后按照安装文档说明中的headless版本。

**Comment by dlnu-wkx** [comment]
paddlepaddle的版本不匹配，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
