### ISSUE TITLE
怎么得到文本识别模型的backbone输出

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5513]
想请问下怎么得到文本识别模型backbone的特征输出呢
![image](https://user-images.githubusercontent.com/37231239/154635036-ea38986e-8146-4011-9c8c-25889b4c4727.png)

**Comment by tink2123** [comment]
这个位置，就是backbone的特征输出，可以自行获取。
https://github.com/PaddlePaddle/PaddleOCR/blob/a8e0760f2700c64e7c5aa41f4f0a8e9d0ead6e1c/ppocr/modeling/architectures/base_model.py#L75
