### ISSUE TITLE
蒸馏训练固定参数出错

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleOCR#5520]
参照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml
配置文件，将Teacher模型的 “freeze_params:” 设为true
训练是出错，提示：
RuntimeError: (NotFound) No grad node corresponding to grad Tensor (dygraph_tmp_1680@GRAD) was found.
  [Hint: Expected find_grad_node_of_var == true, but received find_grad_node_of_var:0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:229)

应该如何固定teacher的参数呢？谢谢！

**Comment by littletomatodonkey** [comment]
你好，因为paddle2.2之后对kldiv这个api的前反向做了限制，可以将

https://github.com/PaddlePaddle/PaddleOCR/blob/99288c50de74aa2bd77953be7d7c71db1e991859/ppocr/losses/basic_loss.py#L109


的`F.kl_div`函数修改为调用下面的函数

```python
    def _kldiv(self, x, target):
        eps = 1.0e-10
        loss = target * paddle.log((target + eps) / (x + eps))
        if self.kl_mode == "mean":
            loss = paddle.mean(loss)
        elif self.kl_mode == "sum":
            loss = paddle.sum(loss)
        elif self.kl_mode == "batchmean":
            loss = paddle.sum(loss) / loss.shape[0]
        return loss
```

**Comment by LiquorPerfect** [comment]
@littletomatodonkey 我也是同样的问题，固定teacher权重报错，根据上面修改了。
![image](https://user-images.githubusercontent.com/36955510/156975149-ba529816-8845-4b84-8e02-fd41b713e8e6.png)
![image](https://user-images.githubusercontent.com/36955510/156975192-1fc445d4-2af3-40ed-b723-dc598843ea24.png)
不报错了，可以训练了，但是一开始就会出现nanxxx了。
![image](https://user-images.githubusercontent.com/36955510/156975473-ded705b3-0778-456a-aeb2-50533023d2b3.png)
如果将“freeze_params:” 设为false，没有这个问题的。

**Comment by littletomatodonkey** [comment]
你好，我这边初步定位到问题，稍等我提个pr哈，感谢反馈

**Comment by littletomatodonkey** [comment]
你好，可以参考该pr：https://github.com/PaddlePaddle/PaddleOCR/pull/5643

**Comment by LiquorPerfect** [comment]
@littletomatodonkey 你好，我看了源码和公式，我感觉公式和代码没有对上，log应该包含x的把。
![image](https://user-images.githubusercontent.com/36955510/157033671-a7c65e58-799f-40b2-96ec-2573d3d5b8bd.png)
