### ISSUE TITLE
PaddleOCR文字识别错误如何优化--如图（埭）

### ISSUE THREAD

**Issue by cenwei1234** [PaddlePaddle/PaddleOCR#5524]
![图片](https://user-images.githubusercontent.com/28823778/154779544-1a4fa9f3-9a75-43a9-b391-5c4a2ff07bb1.png)

**Comment by yjhtc007** [comment]
这个是用的paddle提供的轻量级的文本识别模型还是服务器的文本识别模型呢？如果这些中英文通用识别模型识别效果都不好的话，只能自己生成数据重新训练了。

**Comment by WenmuZhou** [comment]
可以试一下server模型

**Comment by cenwei1234** [comment]
> 可以试一下server模型
好的，多谢
