### ISSUE TITLE
Android demo打开opencl加速首次运行为什么没有生成lite_opencl_kernel.bin和lite_opencl_tuned.bin

### ISSUE THREAD

**Issue by lrjj** [PaddlePaddle/PaddleOCR#5526]
CPU是晓龙855，GPU是高通 Adreno640，我在最新版的官方android demo上面进行修改，想使用opencl加速，首次运行很慢，但是生成没有生成lite_opencl_kernel.bin和lite_opencl_tuned.bin，但是能够成功识别结果，lite_opencl_kernel.bin和lite_opencl_tuned.bin为什么没有在"/data/local/tmp/"下面生成呢？请问这是为什么呢？
android demo修改的代码如下：
![image](https://user-images.githubusercontent.com/68632486/154784514-ca57f4b7-5141-4b0b-a7c3-826775f2c3ae.png)

opt版本是V2.10,paddlelite也是V2.10,
opt指令如下：
![image](https://user-images.githubusercontent.com/68632486/154784337-cbc48a07-ee22-4897-b2c4-5ed647857496.png)

paddlelite是这里直接下载官方的https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/inference_lite_lib.armv8.clang.with_exception.with_extra.with_cv.opencl.tar.gz

**Comment by WenmuZhou** [comment]
我理解这两个文件都是需要自己生成的把，请问你的修改是参考的哪个例子

**Comment by lrjj** [comment]
> 

我前段时间有在这里提问过https://github.com/PaddlePaddle/Paddle-Lite/issues/8220，他们是这样回复的
![image](https://user-images.githubusercontent.com/68632486/154919325-6a417747-0f96-4f5c-88c4-ed861e99d8f9.png)

然后那个代码的改写修改我是参照这个文件，我忘记在哪看到有人是参照这个文件改写就可以了（https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/cxx/mobile_light/mobilenetv1_light_api.cc），我看了这个文件，发现只需要把对应开关打开就行了，我现在找不到那个人的回复在哪了

**Comment by WenmuZhou** [comment]
方便提供一下你的项目吗

**Comment by WenmuZhou** [comment]
你好，我这边测试，目前opencl对识别模型的支持不好，可以正常运行检测和分类模型，建议先使用CPU来进行运行
