### ISSUE TITLE
Wrong download paths in 'deploy/ios_demo/download_dependencies.sh'

### ISSUE THREAD

**Issue by heliusshine** [PaddlePaddle/PaddleOCR#553]
There are wrong download path settings in deploy/ios_demo/download_dependencies.sh, files would be downloaded to a new dir "ios-demo":

line 29 ~ 33:
`download_and_extract "${OCR_MODEL_URL}" "./ios-demo/ocr_demo/models" `
`download_and_extract "${PADDLE_LITE_LIB_URL}" "./ios-demo/ocr_demo" `
`download_and_extract "${OPENCV3_FRAMEWORK_URL}" "./ios-demo/ocr_demo"`

one way to fix it: modify these lines as this:
`download_and_extract "${OCR_MODEL_URL}" "./ocr_demo/models"`
`download_and_extract "${PADDLE_LITE_LIB_URL}" "./ocr_demo"`
`download_and_extract "${OPENCV3_FRAMEWORK_URL}" "./ocr_demo"`
 
then add libs into xcode workspace

**Comment by LDOUBLEV** [comment]
Thanks for your feedback, fix in https://github.com/PaddlePaddle/PaddleOCR/pull/556

**Comment by heliusshine** [comment]
@LDOUBLEV
Thanks for such a quick reply~ good job!
There are two reference suggestion: 
1) Please have a look at xcode project, it might also need an update for handling new lib files.  
2)For other user have no experience on ios, a tutorial for PaddleOCR ios demo is also needed just like android demo document. Paddle-lite ios tutorial is a good reference~
Hope to get better~！

**Comment by LDOUBLEV** [comment]
Thanks, The better on the way.
