### ISSUE TITLE
PaddleOCR 识别内存泄露

### ISSUE THREAD

**Issue by livedimg** [PaddlePaddle/PaddleOCR#5534]
- 系统环境/System Environment：Ubuntu20.04
- 版本号/Version：Paddle：2.1.2 
- c++ inference api  不适用GPU，仅使用CPU计算，内存不泄露。当使用v100卡时， 内存泄露明显，大约一分钟泄露3G。但是在m40卡上运行泄露不明显，一个小时左右未发现特别异常，请问是什么原因？

**Comment by renoyuan** [comment]
python 版本也遇到过，没有很好的解决方案，只能重启服务

**Comment by ddxygq** [comment]
我们也是，运维把显卡版本（10.0）装低了，我只能装paddleocr-2.0.2，程序长时间跑，内存就占满了，只能通过重启服务来解决了。

**Comment by renoyuan** [comment]
> 昨天也遇到了同样的问题，cpp_infer开启GPU后，内存暴涨，关闭GPU，使用CPU的话就正常了。

试下更新paddle 版本和cudnn 版本，我更新到paddle 2.2.和cudnn8.1是解决了内存泄漏的问题

**Comment by GreatV** [comment]
> > 昨天也遇到了同样的问题，cpp_infer开启GPU后，内存暴涨，关闭GPU，使用CPU的话就正常了。
> 
> 试下更新paddle 版本和cudnn 版本，我更新到paddle 2.2.和cudnn8.1是解决了内存泄漏的问题

我部署环境是cudnn8.0，用的paddle inference版本是manylinux_cuda11.1_cudnn8.1_avx_mkl_trt7_gcc5.4。可能要严格对应起来才行。
