### ISSUE TITLE
PaddleOCR中文模型转NCNN，精度下降比较严重

### ISSUE THREAD

**Issue by Agino-ltp** [PaddlePaddle/PaddleOCR#5535]
ch_PP-OCRv2_rec中文识别模型转onnx成功，paddle和onnx模型的推理结果余弦相似度为1。但是onnxsim再转ncnn（没有量化）后精度下降比较严重。图像resize padding，归一化等操作都和paddle上的一样。有人遇到过这种问题吗？

这是转ncnn后的模型
![image](https://user-images.githubusercontent.com/73732417/154932378-a5fbf652-b368-4932-91d5-d1a364fcc4d0.png)

原始图片
![1](https://user-images.githubusercontent.com/73732417/154932940-bca5a206-6a04-4b40-8deb-2263c65628e8.png)

paddleocr推理结果
![image](https://user-images.githubusercontent.com/73732417/154933250-8dc4fb91-7223-41f6-9b34-eec64e4eae8e.png)

ncnn推理结果
![image](https://user-images.githubusercontent.com/73732417/154933434-7a553c0d-50aa-49c7-9512-77e4fbb666f2.png)

**Comment by Agino-ltp** [comment]
![image](https://user-images.githubusercontent.com/73732417/154937225-981fba7f-f3c8-4d52-9e34-6dc13373f079.png)
老一点的模型ch_ppocr_mobile_v2.0_rec_train可以，那个最新的ch_PP-OCRv2_rec_train就不行。不知道是backbone的原因，还是head用了两个linear层的缘故

**Comment by liguiyuan** [comment]
> ![image](https://user-images.githubusercontent.com/73732417/154937225-981fba7f-f3c8-4d52-9e34-6dc13373f079.png) 老一点的模型ch_ppocr_mobile_v2.0_rec_train可以，那个最新的ch_PP-OCRv2_rec_train就不行。不知道是backbone的原因，还是head用了两个linear层的缘故

@Agino-ltp 你好，请教一下 ch_ppocr_mobile_v2.0_rec_infer 模型怎么转ncnn模型，我的老是出错啊，谢谢！

**Comment by Agino-ltp** [comment]
> > ![image](https://user-images.githubusercontent.com/73732417/154937225-981fba7f-f3c8-4d52-9e34-6dc13373f079.png) 老一点的模型ch_ppocr_mobile_v2.0_rec_train可以，那个最新的ch_PP-OCRv2_rec_train就不行。不知道是backbone的原因，还是head用了两个linear层的缘故
> 
> @Agino-ltp 你好，请教一下 ch_ppocr_mobile_v2.0_rec_infer 模型怎么转ncnn模型，我的老是出错啊，谢谢！

别用infer推理模型，用pdparams模型转onnx，再onnxsim简化，就可以onnx2ncnn转了

**Comment by liguiyuan** [comment]
> 
大佬你好，我用了ch_ppocr_mobile_v2.0_rec_train模型还是有问题啊，问题还是出现在onnxsim这一步，我试了这两个简化指令都出错呢
python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx
python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx --dynamic-input-shape --input-shape -1 3 -1 -1

报错信息：
RuntimeError: The shape of input "x" has dynamic size "[-1]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details


请问你的onnxsim 命令是怎么的？

**Comment by Agino-ltp** [comment]
> > 
> 
> 大佬你好，我用了ch_ppocr_mobile_v2.0_rec_train模型还是有问题啊，问题还是出现在onnxsim这一步，我试了这两个简化指令都出错呢 python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx --dynamic-input-shape --input-shape -1 3 -1 -1
> 
> 报错信息： RuntimeError: The shape of input "x" has dynamic size "[-1]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details
> 
> 请问你的onnxsim 命令是怎么的？

我用的是python -m onnxsim model.onnx model-sim.onnx，但是没出现这种的问题。

**Comment by liguiyuan** [comment]
> > > 
> > 
> > 
> > 大佬你好，我用了ch_ppocr_mobile_v2.0_rec_train模型还是有问题啊，问题还是出现在onnxsim这一步，我试了这两个简化指令都出错呢 python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx --dynamic-input-shape --input-shape -1 3 -1 -1
> > 报错信息： RuntimeError: The shape of input "x" has dynamic size "[-1]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details
> > 请问你的onnxsim 命令是怎么的？
> 
> 我用的是python -m onnxsim model.onnx model-sim.onnx，但是没出现这种的问题。

感谢回复，请问一下能分享一下你简化后的model-sim.onnx模型吗，我的一直报错，不知道啥问题了

**Comment by Agino-ltp** [comment]
> > > > 
> > > 
> > > 
> > > 大佬你好，我用了ch_ppocr_mobile_v2.0_rec_train模型还是有问题啊，问题还是出现在onnxsim这一步，我试了这两个简化指令都出错呢 python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx --dynamic-input-shape --input-shape -1 3 -1 -1
> > > 报错信息： RuntimeError: The shape of input "x" has dynamic size "[-1]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details
> > > 请问你的onnxsim 命令是怎么的？
> > 
> > 
> > 我用的是python -m onnxsim model.onnx model-sim.onnx，但是没出现这种的问题。
> 
> 感谢回复，请问一下能分享一下你简化后的model-sim.onnx模型吗，我的一直报错，不知道啥问题了

链接：https://pan.baidu.com/s/1xNT9DtNDF3FfzFavUUtllA 
提取码：udoh 
![image](https://user-images.githubusercontent.com/73732417/155980119-20a153be-1c2a-45b6-b6b2-fc832f089032.png)
我这个是train转onnx再onnxsim转ncnn的。听别人说infer模型可以转onnx，再转ncnn，但是我还没跑通。

**Comment by liguiyuan** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 大佬你好，我用了ch_ppocr_mobile_v2.0_rec_train模型还是有问题啊，问题还是出现在onnxsim这一步，我试了这两个简化指令都出错呢 python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx python -m onnxsim rec_mbv3.onnx rec_mbv3_sim.onnx --dynamic-input-shape --input-shape -1 3 -1 -1
> > > > 报错信息： RuntimeError: The shape of input "x" has dynamic size "[-1]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details
> > > > 请问你的onnxsim 命令是怎么的？
> > > 
> > > 
> > > 我用的是python -m onnxsim model.onnx model-sim.onnx，但是没出现这种的问题。
> > 
> > 
> > 感谢回复，请问一下能分享一下你简化后的model-sim.onnx模型吗，我的一直报错，不知道啥问题了
> 
> 链接：https://pan.baidu.com/s/1xNT9DtNDF3FfzFavUUtllA 提取码：udoh ![image](https://user-images.githubusercontent.com/73732417/155980119-20a153be-1c2a-45b6-b6b2-fc832f089032.png) 我这个是train转onnx再onnxsim转ncnn的。听别人说infer模型可以转onnx，再转ncnn，但是我还没跑通。

谢谢你的分享和耐心讲解，迟点我跑一下你分享的模型哈，感谢！
