### ISSUE TITLE
the result of infer_rec.py and predict_rec.py not same

### ISSUE THREAD

**Issue by raminrahimi6970** [PaddlePaddle/PaddleOCR#5537]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.4
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

hello thanks for your update
I train recognition model
when I use infer_rec.py for recognition the output is very good
but when export weights and use predict_rec.py to get results the output not good as infer_rec.py...
Thanks best regards

**Comment by raminrahimi6970** [comment]
there is bug in release 2.4?

**Comment by raminrahimi6970** [comment]
?

**Comment by Yosiiiiiiiiiiiiiiii** [comment]
I have the same problem.
