### ISSUE TITLE
ocr识别部分图片时报错“operands could not be broadcast together with shapes”

### ISSUE THREAD

**Issue by farukonfly** [PaddlePaddle/PaddleOCR#5538]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
识别图片报错(并非所有图片都报错，仅部分报错)
以下图片调用ocr识别会报错
![非营运__LMGAA1C88H1275706__2111231000375785063001](https://user-images.githubusercontent.com/18646553/154963309-3d7b304e-a09d-4332-a7ae-095081e6a128.png)

- 系统环境/System Environment：
ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddleocr             2.3.0.2

paddlepaddle-gpu      2.0.0
- 运行指令/Command Code：
ocr.ocr(image, cls=True)
- 完整报错/Complete Error Message：
File "/home/ubuntu/ai/gaib-ai/test/driving_acc_finetune.py", line 33, in <module>
    _,return_nature,return_vin = driving_license_recognition.recognition(cv.imdecode(np.fromfile(image_path,dtype=np.uint8),-1),'LMGAA1322G1261049')
  File "/home/ubuntu/ai/gaib-ai/src/recognition/driving_license/driving_license_recognition.py", line 14, in recognition
    orginal_result,_,texts = ocr_utils.ocr_server(image)
  File "/home/ubuntu/ai/gaib-ai/src/common/ocr_utils.py", line 15, in ocr_server
    return __ocr(image,'server')
  File "/home/ubuntu/ai/gaib-ai/src/common/ocr_utils.py", line 39, in __ocr
    result = ocr.ocr(image, cls=True)
  File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 379, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_det.py", line 197, in __call__
    data = transform(data, self.preprocess_op)
  File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/__init__.py", line 43, in transform
    data = op(data)
  File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/operators.py", line 118, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (416,800,4) (1,1,3)

**Comment by zouhan6806504** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem 识别图片报错(并非所有图片都报错，仅部分报错) 以下图片调用ocr识别会报错 ![非营运__LMGAA1C88H1275706__2111231000375785063001](https://user-images.githubusercontent.com/18646553/154963309-3d7b304e-a09d-4332-a7ae-095081e6a128.png)
> 
> * 系统环境/System Environment：
>   ubuntu 18.04
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
>   paddleocr             2.3.0.2
> 
> paddlepaddle-gpu 2.0.0
> 
> * 运行指令/Command Code：
>   ocr.ocr(image, cls=True)
> * 完整报错/Complete Error Message：
>   File "/home/ubuntu/ai/gaib-ai/test/driving_acc_finetune.py", line 33, in 
>   _,return_nature,return_vin = driving_license_recognition.recognition(cv.imdecode(np.fromfile(image_path,dtype=np.uint8),-1),'LMGAA1322G1261049')
>   File "/home/ubuntu/ai/gaib-ai/src/recognition/driving_license/driving_license_recognition.py", line 14, in recognition
>   orginal_result,_,texts = ocr_utils.ocr_server(image)
>   File "/home/ubuntu/ai/gaib-ai/src/common/ocr_utils.py", line 15, in ocr_server
>   return __ocr(image,'server')
>   File "/home/ubuntu/ai/gaib-ai/src/common/ocr_utils.py", line 39, in __ocr
>   result = ocr.ocr(image, cls=True)
>   File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 379, in ocr
>   dt_boxes, rec_res = self.**call**(img, cls)
>   File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 60, in **call**
>   dt_boxes, elapse = self.text_detector(img)
>   File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/tools/infer/predict_det.py", line 197, in **call**
>   data = transform(data, self.preprocess_op)
>   File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/**init**.py", line 43, in transform
>   data = op(data)
>   File "/home/ubuntu/anaconda3/envs/gaib-ai/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/operators.py", line 118, in **call**
>   img.astype('float32') * self.scale - self.mean) / self.std
>   ValueError: operands could not be broadcast together with shapes (416,800,4) (1,1,3)

你这种情况我遇到过，不是3通道的图片而是4通道，取前3个通道的数据去识别就行了

**Comment by vivagwb** [comment]
我也遇到了，请问怎么解决

**Comment by mattdeeperinsights** [comment]
You need to read in your image as RGB (as opposed to RGBA or similar)

If you have a `PIL` image like OP then you can convert it to correct format as follows:

```python3
# convert image to correct format
image = image.convert('RGB')

# run the ocr
result = ocr.ocr(image, cls=True)
```
