### ISSUE TITLE
自定义数据集进行识别，识别的准确率只有0.0020左右，能不能给我指点指点

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5541]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.3
- 版本号/Version：Paddle：paddlepaddle-gpu2.2.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python  train.py -c ./recconfig/rec/rec_french_lite_train.yml
- 完整报错/Complete Error Message：
result: ꅲꌵꊭꈓꊭꈐꑏꉬꉒ     0.002075239

**Comment by dlnu-wkx** [comment]
[Uploading 数据集和配置文件.zip…]()

**Comment by LDOUBLEV** [comment]
> 识别的准确率只有0.0020左右

训练数据有多少，用的是哪个模型？
这个是测试集准确率还是训练集准确率，训练了多少epoch？如果训练时间较短，建议多训练一些时间
检查是否对应调整了和你自定义数据集匹配的字典？

**Comment by dlnu-wkx** [comment]
训练集有10000张，rec_french_lite_train.yml这个配置文件，是在测试的时候，72epoch    4个小时,字典是自定义的配置为：character_dict_path: ppocr/utils/yw_dict.txt
