### ISSUE TITLE
关于模型迁移学习

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5543]
请问一下，PaddleOCR如何实现迁移学习，具体是如何配置的呢？
![image](https://user-images.githubusercontent.com/87969070/155112101-c16383da-c39d-4b1d-88ce-e6201151576b.png)
模型架构为图所示，如果我想把最后一层的Head层之前的参数进行冻结，Paddle是如何进行操作的？

**Comment by LDOUBLEV** [comment]
冻结参数参考：
https://github.com/PaddlePaddle/PaddleOCR/blob/b43f9ecec2e518a2696642977f0acc67d1e2943b/ppocr/modeling/architectures/distillation_model.py#L50-L52

**Comment by 18362890185** [comment]
> 冻结参数参考：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/b43f9ecec2e518a2696642977f0acc67d1e2943b/ppocr/modeling/architectures/distillation_model.py#L50-L52

好的，谢谢您，但是冻结参数之后，模型始终无法拟合，acc一直在0.6左右震荡，请问一下，有没有好的调优方式？

**Comment by LDOUBLEV** [comment]
只训练最后一层参数效果不一定好，需要让模型适应你的数据；

如果你的数据比较少，建议找一些公开数据集做预训练，或者合成一批数据

**Comment by 18362890185** [comment]
> 只训练最后一层参数效果不一定好，需要让模型适应你的数据；
> 
> 如果你的数据比较少，建议找一些公开数据集做预训练，或者合成一批数据

我用的是Paddle的预训练模型，我一共200张实际图像，合成数据为700张，效果还不是很好，请问一下，冻结一层参数训练去让模型适应我的数据，大约还需要多少数据，检测目标全是英文和数字字符

**Comment by LDOUBLEV** [comment]
你训练的是识别模型吧，200张数据太少了；
如果只有英文和数字，可以找一些开源的英文数据集，如果你的场景和开源数据集场景差异较大，可以多合成一批数据；

训练的时候可以尝试把Backbone的参数freeze，只训练head的参数；如果只学习最后一层参数，学习的部分太少了，很难适应你的数据集

**Comment by 18362890185** [comment]
> 你训练的是识别模型吧，200张数据太少了； 如果只有英文和数字，可以找一些开源的英文数据集，如果你的场景和开源数据集场景差异较大，可以多合成一批数据；
> 
> 训练的时候可以尝试把Backbone的参数freeze，只训练head的参数；如果只学习最后一层参数，学习的部分太少了，很难适应你的数据集

好的,谢谢您

**Comment by JXH-2020** [comment]
> 

请问怎么冻结参数啊？
