### ISSUE TITLE
windows和linux识别结果不一样，是什么情况啊，Linux和windown的paddlepaddle版本及依赖包的版都是一样的

### ISSUE THREAD

**Issue by happybuby** [PaddlePaddle/PaddleOCR#5547]
模型与predict_system代码使用官网代码
windows：
200000.00
linux：
皖A000.00

**Comment by andyjpaddle** [comment]
麻烦提供一下详细的信息，包括使用的模型和运行命令以及运行结果详细log

**Comment by lichman0405** [comment]
有可能的情况是这样，所使用的的字典不同，这就导致windows下的模型无法识别汉字。
