### ISSUE TITLE
StyleText的输入图片一定要32*320的尺寸吗

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5548]
StyleText的输入图片一定要32*320的尺寸吗

**Comment by andyjpaddle** [comment]
不需要吧

**Comment by GivanTsai** [comment]
> 不需要吧

但合成效果很差，不用说文字风格迁移了，连背景提取都不好，提取的背景上还有很多文字，需要怎么修改呢

**Comment by andyjpaddle** [comment]
能否给出你这边详细的实验结果看看？包括你这边如何使用的

**Comment by GivanTsai** [comment]
> 能否给出你这边详细的实验结果看看？包括你这边如何使用的
我直接先尝试了单张的合成，`python3 tools/synth_image.py -c configs/config.yml --style_image examples/style_images/xxx.jpg --text_corpus 123eq23131 --language en`
试验结果是fake_bg上还有很多文字，fake_text字体也很奇怪

**Comment by andyjpaddle** [comment]
基于当前PaddleOCR识别模型的设计，我们主要支持高度在32左右的风格图像。 如果输入图像尺寸相差过多，效果可能不佳。

**Comment by GivanTsai** [comment]
> 基于当前PaddleOCR识别模型的设计，我们主要支持高度在32左右的风格图像。 如果输入图像尺寸相差过多，效果可能不佳。

原图的高度也是32左右，而且在进行StyleText之前也resize到32，效果也不佳，可以加个qq把图片发你看下吗

**Comment by andyjpaddle** [comment]
你可以提供一个图片链接给我，我看一下

**Comment by GivanTsai** [comment]
> 你可以提供一个图片链接给我，我看一下

图片不好公开发出，可以发你邮箱吗

**Comment by GivanTsai** [comment]
https://blog.csdn.net/Castlehe/article/details/115455501
效果跟这篇博客提到的差不多，不是很佳

**Comment by andyjpaddle** [comment]
> > 你可以提供一个图片链接给我，我看一下
> 
> 图片不好公开发出，可以发你邮箱吗

可以发到这个邮箱 1143958845@qq.com
