### ISSUE TITLE
请问哪些预训练模型的文本检测是单独检测单词的呢？

### ISSUE THREAD

**Issue by jixu1340036583** [PaddlePaddle/PaddleOCR#5552]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by jixu1340036583** [comment]
就是我想识别出来的结果都是一个单词一个单词的，不是这种一个框一行的
哪些模型可以呢？

**Comment by tink2123** [comment]
这个文档下的检测模型都是：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/algorithm_overview.md#11
