### ISSUE TITLE
sast totaltext训练时为什么一直在评估 

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5553]
eval model:: 100%|█████████▉| 299/300 [02:48<00:00,  4.18it/s]
eval model:: 100%|██████████| 300/300 [02:48<00:00,  3.29it/s]
eval model:: 100%|██████████| 300/300 [02:49<00:00,  1.77it/s]

**Comment by LDOUBLEV** [comment]
训练配置文件是？

可检查下训练数据路径是否正确

**Comment by LDOUBLEV** [comment]
设置评估频率的参数：https://github.com/PaddlePaddle/PaddleOCR/blob/967f06768b49d0b2ab79e537717dd5fdd0e8fafb/configs/det/det_r50_vd_sast_totaltext.yml#L9

eval_batch_step: [4000, 5000]表示训练4000次之后，每运行5000次评估一次

**Comment by qqqqq127** [comment]
> 设置评估频率的参数：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/967f06768b49d0b2ab79e537717dd5fdd0e8fafb/configs/det/det_r50_vd_sast_totaltext.yml#L9
> 
> eval_batch_step: [4000, 5000]表示训练4000次之后，每运行5000次评估一次

谢谢，已解决
