### ISSUE TITLE
准备训练识别模型出现了DataLoader的问题

### ISSUE THREAD

**Issue by frank60229** [PaddlePaddle/PaddleOCR#5554]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

在训练识别模型的时候出现segmentation fault的问题，是关于DataLoader的出现的问题

- 系统环境/System Environment： CentOS 7 
- Cuda 10.1 cuDNN: 7.6.0 1080Ti 
- 版本号/Version： Paddlepaddle 2.2.1 
-                              Paddlepaddle-gpu: 2.2.2
- Paddle：  PaddleOCR：2.4
- 问题相关组件/Related components：是根据这个网站制作的数据https://blog.csdn.net/didiaopao/article/details/120848137，一共设置了5000 epochs，batchsize: 8, lr: lr: 0.0010  一共6w+的数据。
- 运行指令/Command Code：python3 -m paddle.distributed.launch --gpus '0'  tools/train.py -c configs/rec/our.yml

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/99239158/155474490-4e39ea4d-fca7-4d93-a1c6-6c9af83d0d82.png)

**Comment by frank60229** [comment]
训练数据集的类型都是jpg文件的切片，图片的大小都很小，应该不会存在读不进去的问题。

**Comment by tink2123** [comment]
python3 -m  tools/train.py -c configs/rec/our.yml

执行单卡训练，看下具体报错信息吧。

**Comment by frank60229** [comment]
> python3 -m tools/train.py -c configs/rec/our.yml
> 
> 执行单卡训练，看下具体报错信息吧。
> 
> 可能是标签文件的格式不对

OKay， 解决了

**Comment by frank60229** [comment]
> python3 -m tools/train.py -c configs/rec/our.yml
> 
> 执行单卡训练，看下具体报错信息吧。
> 
> 可能是标签文件的格式不对

Okay，解决了， Thx
