### ISSUE TITLE
训练文字识别的时候修改image_shape的高度为64报错了

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleOCR#5556]
训练文字识别的时候修改image_shape的高度为64报错了

  File "C:\python\PaddleOCR-release-2.3\ppocr\modeling\necks\rnn.py", line 31, in forward
    assert H == 1
AssertionError

高度不能修改吗 只能32吗？

**Comment by tink2123** [comment]
送入LSTM的feature 高度必须为1， 如果修改image_shape 为64，需要在RNN之前多做一次下采样。
不想修改源码的话，高度只能是32
