### ISSUE TITLE
PP-Structure表格识别

### ISSUE THREAD

**Issue by zhentaoCoding** [PaddlePaddle/PaddleOCR#5565]
PP-Structure表格识别可以支持中英文的识别吗？表格识别如何和文本检测识别一起部署？

**Comment by WenmuZhou** [comment]
1. 中英文识别换上PP-OCR系列的模型就可以了，具体可以看这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/models_list.md
2. 现在PP-Structure的部署方式已经支持了whl包和python脚本部署，可以参考这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/docs/quickstart.md

**Comment by zhentaoCoding** [comment]
> 1. 中英文识别换上PP-OCR系列的模型就可以了，具体可以看这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/models_list.md
> 2. 现在PP-Structure的部署方式已经支持了whl包和python脚本部署，可以参考这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/docs/quickstart.md

如果之前就用hubserving对文本检测识别进行了部署，想加入表格识别，是不是对module.py中predict函数用predict_table.py中的__call__方法改造？

**Comment by WenmuZhou** [comment]
可以将表格的推理加入到serving中去，参考serving的教程进行添加

**Comment by hbo-lambda** [comment]
> PP-Structure表格识别可以支持中英文的识别吗？表格识别如何和文本检测识别一起部署？

最后你是咋部署的？
