### ISSUE TITLE
参数的意义？

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5566]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
epoch: [200/200], iter: 7770, lr: 0.000000, loss: 4.882508, acc: 0.509764, norm_edit_dis: 0.903770, reader_cost: 3.87226 s, batch_cost: 4.42725 s, samples: 2560, ips: 57.82377
这些参数的意义是什么，麻烦给我解答下

**Comment by WenmuZhou** [comment]
epoch: [200/200], 当前epoch/总的epoch
iter: 7770,  当前总的迭代次数
lr: 0.000000, 当前学习率
loss: 4.882508, 当前loss
acc: 0.509764, 当前模型的acc指标
norm_edit_dis: 0.903770, 当前模型的norm_edit_dis指标
reader_cost: 3.87226 s, 距离上一次打印，读取数据花费的时间
batch_cost: 4.42725 s, 距离上一次打印，，网络运行花费的时间
samples: 2560, 距离上一次打印，一共处理了多少张图片
 ips: 57.82377，每秒处理的图像数
