### ISSUE TITLE
文本检测的矩形框不完整

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5569]
文本检测模型检测出来的文本框与真实文本框的差距过大，det_db_unclip_ratio的调整只适用于文本框过于紧凑的情况，这种IOU过小怎么优化呢

**Comment by WenmuZhou** [comment]
det_db_unclip_ratio也可以调小来缩小框

**Comment by GivanTsai** [comment]
> det_db_unclip_ratio也可以调小来缩小框，可以放一张case图片看看

![image](https://user-images.githubusercontent.com/37231239/155673477-ee463844-ad2f-49b6-8b7b-ed6afa4bc158.png)
类似于这种，相差过大，直接调det_db_unclip_ratio这个参数作用不大

**Comment by GivanTsai** [comment]
> det_db_unclip_ratio也可以调小来缩小框，可以放一张case图片看看

@WenmuZhou

**Comment by LDOUBLEV** [comment]
> 这种IOU过小怎么优化呢

这种情况一般是没有训练好，db模型没有分割到文字，可以可视化看下，漏检测的文字是什么样子的，是否是因为文字亮度过高，或者其他原因导致漏检测了，如果是正常的文字漏检测

另外，你训练的模型在验证集上精度多少

**Comment by GivanTsai** [comment]
> 
我没有训练自己的检测模型，直接适用了ppocr_v2.0_det，漏检测的文字是正常的，一定要重新训练检测模型吗

**Comment by WenmuZhou** [comment]
我这边使用ch_ppocr_mobile_v2.0_det_infer测试是好的

测试命令如下
```bash
python3 tools/infer/predict_det.py --image_dir=1.png --det_model_dir=./ch_ppocr_mobile_v2.0_det_infer --det_limit_side_len=1080
```
测试图片如下
![1](https://user-images.githubusercontent.com/12406017/156563691-45a469d9-7e48-4c46-b454-db5d6c11fd00.png)

测试结果如下
![det_res_1](https://user-images.githubusercontent.com/12406017/156563570-4705913b-5056-44a6-91c0-8557974c5a3e.png)

**Comment by happy20200** [comment]
> > det_db_unclip_ratio也可以调小来缩小框，可以放一张case图片看看
> 
> ![image](https://user-images.githubusercontent.com/37231239/155673477-ee463844-ad2f-49b6-8b7b-ed6afa4bc158.png) 类似于这种，相差过大，直接调det_db_unclip_ratio这个参数作用不大

请问你这个问题解决了吗，我也遇到了同样的问题

**Comment by GivanTsai** [comment]
> 我这边使用ch_ppocr_mobile_v2.0_det_infer测试是好的
> 
> 测试命令如下
> 
> ```shell
> python3 tools/infer/predict_det.py --image_dir=1.png --det_model_dir=./ch_ppocr_mobile_v2.0_det_infer --det_limit_side_len=1080
> ```
> 
> 测试图片如下 ![1](https://user-images.githubusercontent.com/12406017/156563691-45a469d9-7e48-4c46-b454-db5d6c11fd00.png)
> 
> 测试结果如下 ![det_res_1](https://user-images.githubusercontent.com/12406017/156563570-4705913b-5056-44a6-91c0-8557974c5a3e.png)

我这里只是个示例，并不是真实的这张图片

**Comment by Jackzhangfei** [comment]
det_db_unclip_ratio问一下这个设置在哪？
