### ISSUE TITLE
关于开启数据增强

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5570]
未开启状态下,识别acc能达到1，开启数据增强情况下，acc只有0.54,请问这种情况是什么原因？有什么比较好的调整方法？

**Comment by WenmuZhou** [comment]
换个大网络

**Comment by tink2123** [comment]
开启数据增强，训练数据变复杂了，识别难度上升，acc肯定会相应降低。 增大骨干网络，或者增加迭代轮数，都可以提升模型的表达能力。

**Comment by 18362890185** [comment]
> 开启数据增强，训练数据变复杂了，识别难度上升，acc肯定会相应降低。 增大骨干网络，或者增加迭代轮数，都可以提升模型的表达能力。

好的，谢谢您
