### ISSUE TITLE
急急急急急急：关于tensorrt加速

### ISSUE THREAD

**Issue by jixu1340036583** [PaddlePaddle/PaddleOCR#5571]
我用这个网站：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html
中的tensorrt安装教程，使用docker

# 拉取镜像，该镜像预装Paddle 2.2 Python环境，并包含c++的预编译库，lib存放在主目录～/ 下。
docker pull paddlepaddle/paddle:latest-dev-cuda11.0-cudnn8-gcc82
nvidia-docker run --name your_name -v $PWD:/paddle  --network=host -it paddlepaddle/paddle:latest-dev-cuda11.0-cudnn8-gcc82  /bin/bash

进入容器之后连import paddle都会报错
到底哪个镜像可以用tensorrt呀
可以尽快排查一下吗，真的要愁死我了

还有如果可以使用这种方式： linux下通过pip安装
能告诉我下在这个网址之中：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release
下载哪个whl包吗？

我真的需要一个能用tensorrt的环境，球球了，救救孩子把

**Comment by WenmuZhou** [comment]
1. 可以参考这个安装trt
2. trt的whl包下载可以在这里下https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

**Comment by jixu1340036583** [comment]
唉，whl包这种的太麻烦了，我的cuda cudnn gcc版本全都要改，我想用docker
你们能不能自己去试下docker安装的办法啊，自己去试一下，打开容器之后import paddle都报错
能不能试一下

**Comment by LDOUBLEV** [comment]
trt太大了，一般不会直接打包到镜像里；

你要用python 推理还是C++推理；

如果是Python推理：
建议从这个链接找和你cuda，cudnn版本匹配的paddle 安装包：https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

文档参考这个链接的3.2和3.3：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/test_tipc/docs/install.md
