### ISSUE TITLE
vs2019运行debug版本的示例程序

### ISSUE THREAD

**Issue by zx2457** [PaddlePaddle/PaddleOCR#5572]
config.SetModel(model_dir + "/inference.pdmodel",
                  model_dir + "/inference.pdiparams");

这段代码 config里的几个私有成员一直是无内存的 使用的vs2019编译 release版本无异常

**Comment by zx2457** [comment]
到这里就崩溃了 使用的是最新版的预测库和ocr框架

**Comment by zx2457** [comment]
0x00007FF8A2714F99 处(位于 ocr_system.exe 中)有未经处理的异常: Microsoft C++ 异常: std::length_error，位于内存位置 0x0000008A026FF130 处。

**Comment by littletomatodonkey** [comment]
你好，目前还没支持debug模式哈

**Comment by zx2457** [comment]
您好，请问什么时候可以支持debug模式呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月27日(星期天) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] vs2019运行debug版本的示例程序 (Issue #5572)





 
你好，目前还没支持debug模式哈
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by littletomatodonkey** [comment]
抱歉短期还没有这方面的计划哈，我们记录下您的需求

**Comment by zx2457** [comment]
好的，感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] vs2019运行debug版本的示例程序 (Issue #5572)





 
抱歉短期还没有这方面的计划哈，我们记录下您的需求
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
