### ISSUE TITLE
DB检测模型：新版本精度低很多

### ISSUE THREAD

**Issue by gdwu1427** [PaddlePaddle/PaddleOCR#5573]
您好！
      采用相同的det_r50_vd_db.yml方法进行DB检测模型训练，相同的训练集、测试集：相比1.8版本，相同迭代次数在2.4版本中precision低10%精度左右，有可能是什么原因导致的，谢谢！

1.8.2版本:测试集评估日志如下：
`Test iter: 10000, metrics:{'precision': **0.9557361180370185**, 'recall': 0.7727445213926573, 'hmean': 0.8545537997508361}, best_hmean:0.854554, best_epoch:2, best_batch_id:10000
Test iter: 15000, metrics:{'precision': 0.9699818758495695, 'recall': 0.8123517692818518, 'hmean': 0.8841963963033714}, best_hmean:0.884196, best_epoch:3, best_batch_id:15000
Test iter: 20000, metrics:{'precision': 0.9555484795414743, 'recall': 0.7117208993454132, 'hmean': 0.8158055702809609}, best_hmean:0.884196, best_epoch:3, best_batch_id:15000
Test iter: 25000, metrics:{'precision': 0.9703719492699563, 'recall': 0.8637700407930936, 'hmean': 0.9139730977715317}, best_hmean:0.913973, best_epoch:5, best_batch_id:25000
Test iter: 30000, metrics:{'precision': 0.9659514428708338, 'recall': 0.8605682572810929, 'hmean': 0.9102197471402769}, best_hmean:0.913973, best_epoch:5, best_batch_id:25000
Test iter: 35000, metrics:{'precision': 0.966697526101939, 'recall': 0.8915425481453373, 'hmean': 0.9276002467612586}, best_hmean:0.927600, best_epoch:8, best_batch_id:35000
Test iter: 40000, metrics:{'precision': 0.9715932804674458, 'recall': 0.8833839294184612, 'hmean': 0.925391304347826}, best_hmean:0.927600, best_epoch:8, best_batch_id:35000
Test iter: 45000, metrics:{'precision': 0.9711278041800807, 'recall': 0.9014325016601841, 'hmean': 0.934983149246021}, best_hmean:0.934983, best_epoch:10, best_batch_id:45000
Test iter: 50000, metrics:{'precision': 0.9742783360180001, 'recall': 0.9037330424058438, 'hmean': 0.9376807136265765}, best_hmean:0.937681, best_epoch:11, best_batch_id:50000
`
2.4.1版本:测试集评估日志如下：每10000次评估一次
`cur metric, precision: **0.8595887571511484**, recall: 0.6130443780859178, hmean: 0.7156786607990336, fps: 21.635187553457992
cur metric, precision: 0.8779180509413067, recall: 0.5859622150607575, hmean: 0.7028263413596226, fps: 20.862059576797343
cur metric, precision: 0.8855889036909333, recall: 0.6682435029417851, hmean: 0.7617153930406944, fps: 20.9503397473781
cur metric, precision: 0.8966642783217896, recall: 0.6659965112497414, hmean: 0.7643057087115107, fps: 22.785932070581435
cur metric, precision: 0.8756508984231757, recall: 0.7059988765041539, hmean: 0.781726220679947, fps: 22.877370897046703
cur metric, precision: 0.8685036096307216, recall: 0.6793601986813707, hmean: 0.7623755806237557, fps: 22.83752210317899
cur metric, precision: 0.8411528411528412, recall: 0.6376725896579251, hmean: 0.7254136956814207, fps: 22.464067317554267
cur metric, precision: 0.8632001323736246, recall: 0.6169470478668362, hmean: 0.7195889442557374, fps: 22.74911732991076
cur metric, precision: 0.857608138768938, recall: 0.6928717145137924, hmean: 0.7664884135472371, fps: 22.620175076818896
cur metric, precision: 0.8827376086794977, recall: 0.7024214292049789, hmean: 0.782323789452887, fps: 22.62563637990334
cur metric, precision: 0.8265129456205241, recall: 0.6210271117287053, hmean: 0.7091851376673362, fps: 22.74881131698958
cur metric, precision: 0.8752704734660945, recall: 0.7056145226620938, hmean: 0.7813390080209527, fps: 22.818815660970483
cur metric, precision: 0.8784712178189181, recall: 0.7182981994500783, hmean: 0.7903511768246069, fps: 22.850939773793908
cur metric, precision: 0.8586603717910888, recall: 0.6882890340892293, hmean: 0.7640928858619841, fps: 22.97973195935792
cur metric, precision: 0.8823948427538555, recall: 0.7324897259261449, hmean: 0.8004846526655897, fps: 22.61788432138596
cur metric, precision: 0.8817958224734774, recall: 0.710197203086657, hmean: 0.7867483296213809, fps: 22.96169896203152
`

**Comment by littletomatodonkey** [comment]
你好，1.8和2.4的模型不一样，可能会有点diff哈
