### ISSUE TITLE
模型路径存在中文情况下无法读取已下载的模型文件

### ISSUE THREAD

**Issue by sampou** [PaddlePaddle/PaddleOCR#5574]
如题所述，如果模型路径存在中文则无法打开文件，换成英文则可以。

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.2.2  PaddleOCR：2.4 问题相关组件/Related components：utility.py#create_predictor
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
[Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1116)

**Comment by MissPenguin** [comment]
我这边模型路径用中文也可以正常预测的，可能跟你的系统设置有关。
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/25809855/155916242-54db2586-d620-4ff5-a1be-ea3199443d63.png">

**Comment by sampou** [comment]
不知道是不是只有windows系统才有这个问题

**Comment by MissPenguin** [comment]
> 不知道是不是只有windows系统才有这个问题

有可能，我这边没有Windows机器测试。如果是操作系统的问题，那就尽量都用英文路径吧，中文路径确实比较容易出问题。
