### ISSUE TITLE
PaddleOCR on provided bounding box 

### ISSUE THREAD

**Issue by suhani247** [PaddlePaddle/PaddleOCR#5575]
Hi, wanted to know if there is a way we can provide coordinates of a bounding box for paddle ocr to recognise text in just that box? I have a use case where I do not need all text, but just one area. Providing a box could speed up the process rather than running PaddleOCR for the entire image, and then filtering out.

Thanks

**Comment by MissPenguin** [comment]
If you can provide the coordinates of a bounding box (no need for text detection module), you can rewrite the code here as fetch directly from the provided coordinates: https://github.com/PaddlePaddle/PaddleOCR/blob/fb91b6a0bf23d70cc25b07be9061fcaa0e1aa8dd/tools/infer/predict_system.py#L68
