### ISSUE TITLE
IndexError: list index out of range While using other than default models.

### ISSUE THREAD

**Issue by shekarneo** [PaddlePaddle/PaddleOCR#5577]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
Can you provide the command which caused this error and explain what changes have been made to the code/model/anything

**Comment by shekarneo** [comment]
ocr = PaddleOCR(use_angle_cls=True, 
                lang='en',
                det_model_dir='models/ch_ppocr_server_v2.0_det_infer/',
                rec_model_dir='models/ch_ppocr_server_v2.0_rec_infer/', 
                rec_char_dict_path='PaddleOCR/ppocr/utils/en_dict.txt',
                cls_model_dir='models/ch_ppocr_mobile_v2.0_cls_infer/') 

img_path = 'anpr/'

for i, img in enumerate(os.listdir(img_path)):
    result = ocr.ocr(img_path+img, cls=True)
    for line in result:
        print(line)

**Comment by MissPenguin** [comment]
The model and the char dict does not match.  The model `ch_ppocr_server_v2.0_rec_infer` is trained with [dict](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/utils/ppocr_keys_v1.txt) which contains 6623 characters, but you set the `rec_char_dict_path` as `en_dict.txt` which only contains 95 characters.

**Comment by shekarneo** [comment]
Do we have a server version model for engine characters?

**Comment by MissPenguin** [comment]
> Do we have a server version model for engine characters?

Only mobile version model is provided for English&number characters corresponding to `en_dict.txt`. The server version model `ch_ppocr_server_v2.0_rec_infer ` supports English&numbers&Chinese characters corresponding to `ppocr_keys_v1.txt`.  

If you need a server version model which only recognizes English&number characters, you can train it following this [tutorial](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/recognition_en.md).
