### ISSUE TITLE
tensorrt推理时间过长

### ISSUE THREAD

**Issue by jixu1340036583** [PaddlePaddle/PaddleOCR#5578]
- 系统环境/System Environment：ubuntu
- 版本号/Version：20.04 Paddle：2.2.2  PaddleOCR： 2.1.1问题相关组件/Related components：tensorrt推理
- 运行指令/Command Code：paddleocr --image_dir doc/imgs_en/254.jpg --use_angle_cls true --use_gpu true --use_tensorrt true
- 完整报错/Complete Error Message：
并不会报错，不开启tensorrt的话，推理都是正常的；
但是开启tensorrt之后，推理时间大大加快，但是调用cuda、创建启动kernal还有优化op的时间长达1分半（也就是执行一次的总时间长达一分半，但是真正推理时间才花了0.几秒），不知道为什么会耗费这么多时间，cuda版本和cudnn版本还有tensorrt版本都符合推理库的版本要求。

**Comment by jixu1340036583** [comment]
我又重新在另一个服务器上又重装了一边，
服务器：cuda：11.1；         cudnn：8.2；    nccl：2.11       tensorrt：7.2.3.4          
paddle用的推理库版本：paddlepaddle_gpu-2.2.2.post111-cp38-cp38-linux_x86_64.whl
检测模型：ch_PP-OCRv2_det_infer 
执行命令：python3 tools/infer/predict_det.py --image_dir="doc/imgs/1.jpg" --det_model_dir="inference_models/ch_PP-OCRv2_det_infer" --use_tensorrt True
输出：
[2022/02/28 21:13:02] root INFO: 1.jpg  [[[343, 300], [375, 299], [385, 657], [353, 658]], [[296, 299], [330, 298], [345, 847], [311, 848]]]

[2022/02/28 21:13:02] root INFO: The predict time of doc/imgs/1.jpg: 0.5421175956726074


推理时间只用了0.5s
但是我等结果足足等了两分钟。
这到底是怎么回事呀。

**Comment by ziyaxuanyi** [comment]
你这个结果就是正常的，tensorRT初始化时需要花费一定的时间。实际部署就是启动服务初始化慢一点，但启动初始化完成后，服务就一直挂在那里，之后来图片数据就是直接给到模型推理，不用再初始化了，只看推理时间了，是很快的。

你这个测试是用的什么gpu，为啥tensorRT加速效果这么明显，我测试tensorRT加速没你加速这么多

**Comment by MissPenguin** [comment]
我这边cuda10.1+cudnn7.6+trt6环境下初始化耗时大约10～20s，可能不同环境下预热tensorrt速度会不一样，不过后面能正常预测的话应该影响不大

**Comment by jixu1340036583** [comment]
> 你这个结果就是正常的，tensorRT初始化时需要花费一定的时间。实际部署就是启动服务初始化慢一点，但启动初始化完成后，服务就一直挂在那里，之后来图片数据就是直接给到模型推理，不用再初始化了，只看推理时间了，是很快的。
> 
> 你这个测试是用的什么gpu，为啥tensorRT加速效果这么明显，我测试tensorRT加速没你加速这么多

谢谢您的回复。
因为我是一次接触部署，然后我的需求是一次只推理十几张图片，请问怎么才能启动初始化完成后让服务一直挂在那里呢？有相关教程吗？谢谢。

**Comment by ziyaxuanyi** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/pdserving/README_CN.md

**Comment by Biaocsu** [comment]
@ziyaxuanyi @jixu1340036583 
您好，请问你们实验tensorrt加速效果明显吗？
我这边
`use_tensorrt=False`
```
root@k8s-m-10-13-84-6:/paddle/PaddleOCR# python3 tools/infer/predict_system.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022/03/01 09:12:58] root DEBUG: Predict time of ./data/5.jpg: 1.800s
[2022/03/01 09:12:59] root DEBUG: Predict time of ./data/2.png: 0.374s
[2022/03/01 09:12:59] root DEBUG: Predict time of ./data/4.jpg: 0.372s
[2022/03/01 09:12:59] root DEBUG: Predict time of ./data/3.png: 0.152s
[2022/03/01 09:13:00] root DEBUG: Predict time of ./data/1.jpg: 0.252s
```
`use_tensorrt=True`
```
root@k8s-m-10-13-84-6:/paddle/PaddleOCR# python3 tools/infer/predict_system.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022/03/01 09:13:58] root DEBUG: Predict time of ./data/5.jpg: 0.921s
[2022/03/01 09:13:59] root DEBUG: Predict time of ./data/2.png: 0.349s
[2022/03/01 09:13:59] root DEBUG: Predict time of ./data/4.jpg: 0.365s
[2022/03/01 09:13:59] root DEBUG: Predict time of ./data/3.png: 0.148s
[2022/03/01 09:14:00] root DEBUG: Predict time of ./data/1.jpg: 0.231s
```
可以说几乎没区别了，这是我将进程数`total_process_num`设置为1的结果，设置为其他数值也是一样的

**Comment by ziyaxuanyi** [comment]
我这边测试整个流程大概只有10%左右的加速

**Comment by Biaocsu** [comment]
@ziyaxuanyi 我这边也是这样，效果太不明显了。之前其他NLP项目都是提升50%以上

**Comment by jixu1340036583** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/pdserving/README_CN.md
