### ISSUE TITLE
我使用自定义的字典进行训练 acc=0.639左右  但是测试的结果只有0.004397左右？

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5579]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：window10 cpu
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer/predict_rec.py --image_dir="./traindata/rec/test/00000001.jpg" --rec_model_dir="./inference
/rec_crnn/2-27-mv3/" --rec_image_shape="3, 32, 320"  --rec_char_dict_path="./ppocr/utils/yw_dict.txt"
- 完整报错/Complete Error Message： Predicts of    ./traindata/rec/test/00000001.jpg:('ꎎꑣꃷꀭꊌꎎꀭ', 0.0043970793)

**Comment by LDOUBLEV** [comment]
测试的时候是否更换了字典？https://github.com/PaddlePaddle/PaddleOCR/blob/fb91b6a0bf23d70cc25b07be9061fcaa0e1aa8dd/tools/infer/utility.py#L79
