### ISSUE TITLE
paddleocr加载模型时，是否有方法可支持在含有中文的模型路径加载？

### ISSUE THREAD

**Issue by Eric-Hjx** [PaddlePaddle/PaddleOCR#5580]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

paddleocr加载模型时，模型路径含有中文，无法加载。

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file ./涓枃/models/cls/ch_cls_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1116)

**Comment by ziyaxuanyi** [comment]
把模型放到一个不含中文的文件路径不就可以了，移动文件位置不难吧

**Comment by Eric-Hjx** [comment]
我的问题是PaddlePaddle是否支持在含有中文的路径下加载模型？而不是说换个英文路径。。。

**Comment by ziyaxuanyi** [comment]
据我所知，主流的windows和linux系统，给文件换个位置应该不难吧。您是用的什么系统呢，以至于非要加载含有中文路径下的模型，宁愿要去支持中文路径，也不愿意鼠标或者命令行敲一下移动模型文件。

我不是官方人员，只是吐槽一下而已，见谅

**Comment by Eric-Hjx** [comment]
问题我已经解决了，麻烦您以后还是先看清楚问题再回答吧，我问的是 “是否支持？” 而不是 “为什么不支持？”
另外，我在正经提出问题，您就在这阴阳怪气的真是没什么意思。。。要是您不懂就说不懂，或者干脆跳过我这个问题就行了，没有必要在这里说这说那的。。。

**Comment by lgh1998** [comment]
老哥我想知道你怎么解决的这个问题，能否告知下。

**Comment by alipapabi** [comment]
我也希望知道如何解决
