### ISSUE TITLE
paddleOCR如何批量预测？

### ISSUE THREAD

**Issue by ArtechStark** [PaddlePaddle/PaddleOCR#5588]
`ocr = PaddleOCR(use_angle_cls=True, lang="ch")

result = ocr.ocr(img_array, cls=True) 
`

paddleOCR预测时，上面的代码只能一张图一张图地预测，这样GPU利用率很低。有什么方法能同时预测一个batch的图片吗？

期待回复，谢谢🙏

**Comment by andyjpaddle** [comment]
预测一个batch的话，要设置det=False，也就是只支持识别，源代码在
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/paddleocr.py#L356
这里

**Comment by kFoodie** [comment]
> 

只识别不检测的话，效果也太差了。。

**Comment by andyjpaddle** [comment]
目前还是只支持单张图片，同时预测是要应用在什么场景中呢？

**Comment by ArtechStark** [comment]
> 目前还是只支持单张图片，同时预测是要应用在什么场景中呢？

为了提升QPS，如果能批量处理就能充分利用GPU的能力。

**Comment by YY007H** [comment]
> > 目前还是只支持单张图片，同时预测是要应用在什么场景中呢？
> 
> 为了提升QPS，如果能批量处理就能充分利用GPU的能力。

开多进程就可以了

**Comment by ollyestn** [comment]
paddleocr还是不能进行批量图片进行预测。

> 预测一个batch的话，要设置det=False，也就是只支持识别，源代码在 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/paddleocr.py#L356 这里

这个只是假装进行了一下批量预测，其实质还是进行一个图片一个图片的预测。
