### ISSUE TITLE
训练的精度好但是验证的精度差？

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5589]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.4
- 版本号/Version：2.4 Paddle：paddlepaddle-gpu=2.2.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
 root INFO: epoch: [565/700], iter: 22000, lr: 0.000500, loss: 0.155906, acc: 0.999996, norm_edit_dis: 1.000000, reader_cost: 0.15283 s, batch_cost: 0.35071 s, samples: 1280, ips: 364.97792

eval model:: 100%|██████████| 4/4 [00:02<00:00,  1.36it/s]

root INFO: cur metric, acc: 0.130999869000131, norm_edit_dis: 0.3441920810493444, fps: 2178.5310264947097

训练的精度好但是验证的精度差？训练10000张图片，验证1000张图片

**Comment by ziyaxuanyi** [comment]
过拟合了，或者验证集与训练集数据差别较大，再加点和验证集类似的数据训练

**Comment by dlnu-wkx** [comment]
谢谢您
