### ISSUE TITLE
蒸馏识别训练nanxxx的问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#5590]
之前蒸馏识别模型训练一直都没有问题，最近新加入了一批数据，在之前的基础上继续训练，若干次迭代（不超过一个epoch）loss会变成nanxxx，是什么原因？应该不是数据的问题，因为如果不使用蒸馏训练，就是普通训练的话，就不会有出现这种情况。

这种情况可能是什么原因导致的，怎么解决，如果是数据问题，该怎么快速找出问题数据，现在数据特别庞大，不好找出问题数据。

**Comment by littletomatodonkey** [comment]
1. 是否有加载预训练模型呢？建议加载飞桨提供的预训练模型哈
2. 训练的时候降低学习率，官网蒸馏配置是bs=8卡x128 =1024 ，lr 1e-3，你的学习率和lr也要对应减小，
3. 训练不稳定，可以加上warmup的学习率策略

**Comment by lgcy** [comment]
解决了吗，出现同样的问题，同样的数据，单独训练没有问题，蒸馏训练直接loss变nanxxx

**Comment by lgcy** [comment]
初步定位原因是在之前基础上训练，ctcloss会比较小，但是dmlloss会很大，导致带崩所有loss，变成nan
