### ISSUE TITLE
How to maintain unclip ratio?

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/PaddleOCR#5593]
How could i maintain unclip ratio based on image size for resolve white space issue on high quality images or small or large font type of images?

**Comment by andyjpaddle** [comment]
you can try to change the source code, eg: for DB algorithm, you can change the code in https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/postprocess/db_postprocess.py#L102

**Comment by YC7225** [comment]
could you explain me how unclip ratio helping me for whitespace recognition?

**Comment by LDOUBLEV** [comment]
The larger the unclip ratio, the larger the range of the text detection box; the smaller the value, the closer the text box is to the text.

**Comment by YC7225** [comment]
okay! do you think in the whitespace cases font size matters? because according to your statement its seem to me if you have congested text data and font size say 12 in the singe image you will get whitespace thing but if you have font size around 20 than you might miss to get the whitespace?
