### ISSUE TITLE
pdservering部署好PaddleOCR之后无法获取到图片上的box位置信息

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/PaddleOCR#5596]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu16.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 相关包的版本信息如下：
paddle-serving-app        0.7.0
paddle-serving-client     0.7.0
paddle-serving-server-gpu 0.7.0.post112
paddledet                 2.1.0
paddlepaddle-gpu          2.2.2.post112

通过修改RecOp里面的postprocess(self, input_dicts, fetch_data, data_id, log_id)方法，从input_dicts获取dt_boxes，代码如下
`#获取文字的坐标位置信息
        (_, input_dict), = input_dicts.items()
        dt_boxes = input_dict["dt_boxes"]
        dt_boxes = self.sorted_boxes(dt_boxes)
        dt_boxes_list = []
        for boxes in dt_boxes:
            dt_boxes_list.append(boxes.tolist())`
通过调试发现这里输出的box是裁剪后的坐标位置，box的开始都是[0,0]，我打印preprocess(self, input_dicts, data_id, log_id)方法中的input_dicts发现是正常的

**Comment by xiulianzw** [comment]
问题解决了，是因为RecOp中的preprocess中的boximg = self.get_rotate_crop_image(im, dt_boxes[box_idx])(135行)里面，修改了boxes的位置，把它改成boximg = self.get_rotate_crop_image(im, dt_boxes[box_idx].copy())就正常了

**Comment by yzxweb** [comment]
@xiulianzw  能提供下web_service.py中的获取位置的完整代码吗？

**Comment by xiulianzw** [comment]
`    def postprocess(self, input_dicts, fetch_data, data_id, log_id):

        #获取文字的坐标位置信息
        (_, input_dict), = input_dicts.items()
        dt_boxes = input_dict["dt_boxes"]
        dt_boxes = self.sorted_boxes(dt_boxes)
        dt_boxes_list = []
        for boxes in dt_boxes:
            dt_boxes_list.append(boxes.tolist())`
添加上面的代码就行了 @yzxweb

**Comment by yzxweb** [comment]
收到，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月10日(周四) 下午3:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] pdservering部署好PaddleOCR之后无法获取到图片上的box位置信息 (Issue #5596)




 
`    def postprocess(self, input_dicts, fetch_data, data_id, log_id):
     #获取文字的坐标位置信息     (_, input_dict), = input_dicts.items()     dt_boxes = input_dict["dt_boxes"]     dt_boxes = self.sorted_boxes(dt_boxes)     dt_boxes_list = []     for boxes in dt_boxes:         dt_boxes_list.append(boxes.tolist())`  
添加上面的代码就行了 @yzxweb
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
