### ISSUE TITLE
paddleocr C++ VS2019编译问题

### ISSUE THREAD

**Issue by JulyYoung** [PaddlePaddle/PaddleOCR#5597]
cmake 设置的时候出错：
CMake Error at extern_autolog-subbuild/autolog/tmp/extern_autolog-populate-gitclone.cmake:31 (message):
1> [CMake]     Failed to clone repository: 'https://github.com/LDOUBLEV/AutoLog.git'

第三方依赖下载失败，必须科学上网吗？

**Comment by littletomatodonkey** [comment]
这里需要下载github的第三方库，建议保证github连通哈
