### ISSUE TITLE
DB文本检测模型推理有问题

### ISSUE THREAD

**Issue by bboxzhen** [PaddlePaddle/PaddleOCR#56]
python3 tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.checkpoints=./ch_lite/det_mv3_db/best_accuracy Global.save_inference_dir=./inference_model/det_db/

![image](https://user-images.githubusercontent.com/39783629/82199064-c96b8180-992f-11ea-9b97-e273db2c6845.png)

**Comment by tink2123** [comment]
请问您是否使用的 paddle1.8 ？如果是的话，麻烦重新安装下paddle1.7系列，PaddleOCR暂时没有适配1.8。1.7的安装命令如下:
cuda9:
`python3 -m pip install paddlepaddle-gpu==1.7.2.post97 -i https://pypi.tuna.tsinghua.edu.cn/simple`
cuda10:
`python3 -m pip install paddlepaddle-gpu==1.7.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple`
