### ISSUE TITLE
Fused 0 subgraphs into layer_norm

### ISSUE THREAD

**Issue by GXY2017** [PaddlePaddle/PaddleOCR#5600]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)], WIN10
- 版本号/Version：Paddle：2.1.2  PaddleOCR： 2.4  问题相关组件/Related components：class PaddleOCR()
- 运行指令/Command Code：
````
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
ocr = PaddleOCR(use_angle_cls=True, lang='ch')
````
- 完整报错/Complete Error Message：
````
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
````

Update: After I reinstalled paddleocr, I got  the new error:
````
usage: pydevconsole.py [-h] [--use_gpu USE_GPU] [--ir_optim IR_OPTIM]
                       [--use_tensorrt USE_TENSORRT] [--gpu_mem GPU_MEM]
                       [--image_dir IMAGE_DIR] [--det_algorithm DET_ALGORITHM]
                       [--det_model_dir DET_MODEL_DIR]
                       [--det_max_side_len DET_MAX_SIDE_LEN]
                       [--det_db_thresh DET_DB_THRESH]
                       [--det_db_box_thresh DET_DB_BOX_THRESH]
                       [--det_db_unclip_ratio DET_DB_UNCLIP_RATIO]
                       [--det_east_score_thresh DET_EAST_SCORE_THRESH]
                       [--det_east_cover_thresh DET_EAST_COVER_THRESH]
                       [--det_east_nms_thresh DET_EAST_NMS_THRESH]
                       [--rec_algorithm REC_ALGORITHM]
                       [--rec_model_dir REC_MODEL_DIR]
                       [--rec_image_shape REC_IMAGE_SHAPE]
                       [--rec_char_type REC_CHAR_TYPE]
                       [--rec_batch_num REC_BATCH_NUM]
                       [--max_text_length MAX_TEXT_LENGTH]
                       [--rec_char_dict_path REC_CHAR_DICT_PATH]
                       [--use_space_char USE_SPACE_CHAR]
                       [--cls_model_dir CLS_MODEL_DIR]
                       [--cls_image_shape CLS_IMAGE_SHAPE]
                       [--label_list LABEL_LIST]
                       [--cls_batch_num CLS_BATCH_NUM]
                       [--cls_thresh CLS_THRESH]
                       [--enable_mkldnn ENABLE_MKLDNN]
                       [--use_zero_copy_run USE_ZERO_COPY_RUN]
                       [--use_pdserving USE_PDSERVING] [--lang LANG]
                       [--det DET] [--rec REC] [--use_angle_cls USE_ANGLE_CLS]
pydevconsole.py: error: unrecognized arguments: --mode=client --port=53811
Process finished with exit code 2

````
Update: 
Numpy 1.19 got error: No module named 'numpy.typing'.   But Numpy 1.21 still got above error.

**Comment by WenmuZhou** [comment]
辛苦提供一下复现脚本

**Comment by GXY2017** [comment]
> 辛苦提供一下复现脚本

在上述环境下，运行以下三行，就停止了。没有其他代码。

````
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
ocr = PaddleOCR(use_angle_cls=True, lang='ch')
````

**Comment by GXY2017** [comment]
> 辛苦提供一下复现脚本

重新安装了python环境，出现如下报错：

 ERROR - error in loading image:http://www.100ppi.com/graph/index/table/602-20220223-20220305-175-290-v-p.png
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\USERNAME/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='C:\\Users\\USERNAME/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\USERNAME/.paddleocr/rec/ch', use_angle_cls=True, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
