### ISSUE TITLE
设置不同的rec_batch_num，出来的结果不一样，这是什么情况？

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleOCR#5603]
hubserving预测部署的时候，params.py中设置不同的rec_batch_num会出现不同的结果，这是什么情况呢？

rec_batch_num设置为6的时候
![8_RAZ{`~O83H9X7BQ6KEFPM](https://user-images.githubusercontent.com/15188456/156300459-092feb85-a88d-4de6-8d1b-11f15b76765e.png)

rec_batch_num设置为30的时候
![%G`LH9VN)DMVHW{K`XADMN0](https://user-images.githubusercontent.com/15188456/156300488-65e8c05c-d72c-4ffc-80ff-fdf4829d974a.png)

**Comment by ziyaxuanyi** [comment]
识别模型会按照一个rec_batch_num的图片中最大的宽高比例，将所有图片统一尺寸，然后送入识别网络处理。不同的rec_batch_num，其中一个rec_batch_num的图片中最大的宽高比例也会不同，图片会统一成不同的尺寸，因而结果会有所不同。
按照代码来说是这样的

**Comment by YY007H** [comment]
> 识别模型会按照一个rec_batch_num的图片中最大的宽高比例，将所有图片统一尺寸，然后送入识别网络处理。不同的rec_batch_num，其中一个rec_batch_num的图片中最大的宽高比例也会不同，图片会统一成不同的尺寸，因而结果会有所不同。 按照代码来说是这样的

嗯，理了下代码是这样的，但这样批处理的方式会造成部分图片识别精度降低

**Comment by yjhtc007** [comment]
> > 识别模型会按照一个rec_batch_num的图片中最大的宽高比例，将所有图片统一尺寸，然后送入识别网络处理。不同的rec_batch_num，其中一个rec_batch_num的图片中最大的宽高比例也会不同，图片会统一成不同的尺寸，因而结果会有所不同。 按照代码来说是这样的
> 
> 嗯，理了下代码是这样的，但这样批处理的方式会造成部分图片识别精度降低

是的，我感觉可以先对检测图片依据宽高比进行一个排序并分组，然后把分组后的图片进行分批识别最后再还原原来的顺序。

**Comment by tink2123** [comment]
现在就是会对文本框先排序再识别，如果batch_num设的太大的话，当有一条样本过长就会导致整个batch内数据padding过多。没有特殊需求不建议batch设的太大哈。
