### ISSUE TITLE
文本识别需要标注？

### ISSUE THREAD

**Issue by dlnu-wkx** [PaddlePaddle/PaddleOCR#5604]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
检测数据集的标注是一个字符一个字符的标注还是一行标注一次
识别的数据集需要使用框标注吗

**Comment by yjhtc007** [comment]
1.具体是行标注还是字符标注是依据你的任务而定的，如果需要检测字符的话就字符标注，如果只需要检测行的话就行标注；
2.识别数据集不需要框标注，只要标注得到小图内的文本内容即可。

**Comment by dlnu-wkx** [comment]
谢谢
