### ISSUE TITLE
Opt版本和Paddle Lite库版本不一致问题

### ISSUE THREAD

**Issue by xiaohe725** [PaddlePaddle/PaddleOCR#5608]
opt版本：v2.9
Paddle-Lite版本：e6652cd
用opt转换模型后，可以进行推理，但是检测不到任何结果，warning提示版本不一致
![9283eba9dd209e6ba22815e7f3ab17a](https://user-images.githubusercontent.com/54875734/156324965-c642a068-d675-4f91-ad81-8c0f1244b6bb.png)

**Comment by littletomatodonkey** [comment]
你好，建议版本都保持一致，比如2.10哈
