### ISSUE TITLE
训练sast问题

### ISSUE THREAD

**Issue by BADBADBADBOY** [PaddlePaddle/PaddleOCR#561]
![image](https://user-images.githubusercontent.com/27273035/90508279-0262fe80-e18a-11ea-9edc-049ce2702b55.png)
这句话导致可训练样本减少好多，能否注释

**Comment by Aionrichman** [comment]
兄弟，sast这个模型好像撤销了啊

**Comment by LDOUBLEV** [comment]
可以去掉的，不过这样训练样本padding的case占比比较多，不太符合实际场景，或者在你的场景中把input_size 改小一点？
