### ISSUE TITLE
cpu版本有内存泄漏

### ISSUE THREAD

**Issue by whuawell** [PaddlePaddle/PaddleOCR#5610]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

使用docker安装
# Version: 2.0.0
FROM registry.baidubce.com/paddlepaddle/paddle:2.1.0
#
# # PaddleOCR base on Python3.7
RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple
#
#RUN pip3.7 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple
#
#RUN git clone -b release/2.1 https://gitee.com/PaddlePaddle/PaddleOCR.git /PaddleOCR
#
存在内存泄漏时代码，每次增加200M左右
self.ocr = PaddleOCR(use_angle_cls=True, lang='ch', use_gpu=False, enable_mkldnn=True)

修改mkldnn加速参数为False后，未出现内存泄漏:
self.ocr = PaddleOCR(use_angle_cls=True, lang='ch', use_gpu=False, enable_mkldnn=False)

**Comment by tink2123** [comment]
感谢反馈～ 我们定位下问题

**Comment by whuawell** [comment]
升级到 paddle2.2.2正常了

**Comment by whuawell** [comment]
还发现一个奇怪的问题，paddle2.2.2 + ocr2.1  内存700M， 而 paddle2.2.2 + ocr2.4 内存1.2g， 同样的模型。
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar
