### ISSUE TITLE
PaddleDetection训练过程中GPU利用率很低很低怎么办

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#5611]
求助大神，如何提高PaddleDetection训练过程中的GPU利用率？
一个epoch跑了33小时，那365个epoch.....
Paddle 2.2.1 Cuda 11.2 cudnn 8.2.1 python 3.8
运行命令：python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml
![image](https://user-images.githubusercontent.com/83860013/156354803-d89517f5-0bd0-41e9-b71a-9afa50a8a566.png)

**Comment by tink2123** [comment]
可以尝试 增加训练batch_size，开启多进程数据读取，使用混合精度训练。

**Comment by Nabyssache** [comment]
> 可以尝试 增加训练batch_size，开启多进程数据读取，使用混合精度训练。

怎么开启多进程读取呢

**Comment by zzk2021** [comment]
多进程也没用，多卡要开多少个
