### ISSUE TITLE
一张图片训练文本识别，训练的准确率是99%,但是测试这张图片的时候准确率40%，是因为样本量不多的原因吗，因为想测试所以过拟合训练了一组

### ISSUE THREAD

**Issue by zzwwr** [PaddlePaddle/PaddleOCR#5613]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
是样本不多的原因
