### ISSUE TITLE
使用paddle2.2 CPU模式跑10来张图后报dnnl::error

### ISSUE THREAD

**Issue by yjygit** [PaddlePaddle/PaddleOCR#5614]
- 系统环境/System Environment：ubuntu 18.04  i9  rtx3080ti  32g
- 版本号/Version：Paddle2.2：  PaddleOCR：2.0 问题相关组件/Related components：mlkdnn
- 完整报错/Complete Error Message：
terminate called after throwing an instance of 'dnnl::error'
  what():  could not execute a primitive

paddle2.2版本cpu模式跑几张图片后报上述错误，GPU模式没有问题，切换回paddle2.0 CPU模式没有问题。
用的是官网编好的库

**Comment by WenmuZhou** [comment]
辛苦提供一下命令和报错的截图

**Comment by yjygit** [comment]
用的c++的库，没有报出调用堆栈，直接输出
terminate called after throwing an instance of 'dnnl::error'
what(): could not execute a primitive
就这2行

**Comment by WenmuZhou** [comment]
你好，我们刚刚修了一个bug，可能和你这个相关，辛苦待pr合入后再测试一下https://github.com/PaddlePaddle/PaddleOCR/pull/5693

**Comment by cdycdycdy** [comment]
> 用的c++的库，没有报出调用堆栈，直接输出 terminate called after throwing an instance of 'dnnl::error' what(): could not execute a primitive 就这2行
您好，当时这个问题有解决吗
