### ISSUE TITLE
自己训练的模型问题

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5618]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7  
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr2.1 cpp_infer  paddleocr2.4 python3.7
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 我现在用的paddleocr2.1 cpp_infer  进行推理，用的模型是：
ch_ppocr_mobile_v2.0_cls_infer.tar
ch_ppocr_server_v2.0_det_infer.tar
ch_ppocr_server_v2.0_rec_infer.tar

有些不能识别需要自己微调，我下载了paddleocr2.4 ，通过ch_ppocr_server_v2.0_det_train进行训练，训练好进行测试，效果还可以。
python tools/infer_det.py -c configs/det/det_res18_db_v2.0.yml -o Global.infer_img=""/home/traindata/1.jpg" Global.pretrained_model=./output/ch_db_res18/latest.pdparams
模型导出后预测时效果不是很好，没上面的效果好，也看了“Q1: 训练模型转inference 模型之后预测效果不一致？”，不知道要改哪里？
python  tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_db_inference/" --image_dir="/home/traindata/1.jpg" 
因为我用的是paddleocr2.1 cpp_infer ，直接把训练好的模型导出以后放到paddleocr2.1 cpp_infer 环境以后，根本不能识别了，这个是什么原因引起的？是不是我必须用paddleocr2.1 的脚本进行训练?谢谢！

**Comment by linkewei0580** [comment]
我现在用paddleocr 2.1、 2.4 编译的paddle_inference库都是一样的，使用的模型也是一样的，对同一个图片进行推理，2.1是能识别正确，2.4就不能识别正确，2.4中用我直接训练转换好的det模型倒也可以识别正确，这个是啥原因？

paddle_inference版本号
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
CXX compiler version: 5.4.0

2.4的配置
// detection related
DEFINE_string(image_dir, "", "Dir of input image.");
DEFINE_string(det_model_dir, "", "Path of det inference model.");
DEFINE_int32(max_side_len, 960, "max_side_len of input image.");
DEFINE_double(det_db_thresh, 0.3, "Threshold of det_db_thresh.");
DEFINE_double(det_db_box_thresh, 0.5, "Threshold of det_db_box_thresh.");
DEFINE_double(det_db_unclip_ratio, 1.6, "Threshold of det_db_unclip_ratio.");
DEFINE_bool(use_polygon_score, false, "Whether use polygon score.");
DEFINE_bool(visualize, true, "Whether show the detection results.");
2.1的配置
-------------
# det config
max_side_len  960
det_db_thresh  0.3
det_db_box_thresh  0.5
det_db_unclip_ratio  1.6
det_model_dir  /home/install/models/det_1

**Comment by WenmuZhou** [comment]
你好，梳理一下你的问题
paddle_inference库一样，模型使用paddleocr/Release/2.4 进行训练和导出
1. 使用paddleocr/Release/2.1 的cpp infer代码进行预测，结果不对
2. 使用paddleocr/Release/2.4 的cpp infer代码进行预测，结果正确
请问是这个意思吗

**Comment by linkewei0580** [comment]
发自我的华为手机是的。另外2.4使用之前2.1能识别的模型（直接下载的推理模型）也不能识别 ，本来我想把我自己的应用预处理的代码切换到2.4，这样的话切换过去以后之前本来能识别的模型就不能识别了。-------- 原始邮件 --------发件人： zhoujun ***@***.***>日期： 2022年3月3日周四 晚上7:53收件人： PaddlePaddle/PaddleOCR ***@***.***>抄送： linkewei0580 ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleOCR] 自己训练的模型问题 (Issue #5618)

你好，梳理一下你的问题

paddle_inference库一样，模型使用paddleocr/Release/2.4 进行训练和导出

使用paddleocr/Release/2.1 的cpp infer代码进行预测，结果不对使用paddleocr/Release/2.4 的cpp infer代码进行预测，结果正确

请问是这个意思吗

**Comment by WenmuZhou** [comment]
有试过2.4的python推理跑2.1的模型有没有结果吗

**Comment by linkewei0580** [comment]
试过，一张清晰的图片2.1 cpp infer能全部识别，2.4的python 只能部分识别。

使用相同模型：
ch_ppocr_mobile_v2.0_cls_infer.tar
ch_ppocr_server_v2.0_det_infer.tar
ch_ppocr_server_v2.0_rec_infer.tar

c++推理库
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
CXX compiler version: 5.4.0




林可伟
13701764610
 
发件人： zhoujun
发送时间： 2022-03-03 23:08
收件人： PaddlePaddle/PaddleOCR
抄送： linkewei0580; Author
主题： Re: [PaddlePaddle/PaddleOCR] 自己训练的模型问题 (Issue #5618)
有试过2.4的python推理跑2.1的模型有没有结果吗
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WenmuZhou** [comment]
提供下你的测试模型吧

**Comment by linkewei0580** [comment]
> * 模型是：
>   ch_ppocr_mobile_v2.0_cls_infer.tar
>   ch_ppocr_server_v2.0_det_infer.tar
>   ch_ppocr_server_v2.0_rec_infer.tar

我发到你gmail，你收一下。

**Comment by WenmuZhou** [comment]
发我qq邮箱吧 572459439@qq.com

**Comment by WenmuZhou** [comment]
你好，我们刚刚修了一个bug，可能和你这个相关，辛苦再测试一下https://github.com/PaddlePaddle/PaddleOCR/pull/5693

**Comment by chenzhaoqiJM** [comment]
# 转化为推理模型
!python tools/export_model.py \
-c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml \
-o Global.pretrained_model="./output/det/ch_PP-OCR_v3_det_student/best_accuracy" \
-o Global.save_inference_dir="./inference/det/det_ppocrv3/student"
我看到有的教程在这里的Global前面使用了两个o，这将导致模型导出出现重大问题，应该使用：
!python tools/export_model.py \
-c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml \
-o Global.pretrained_model="./output/det/ch_PP-OCR_v3_det_student/best_accuracy" \
Global.save_inference_dir="./inference/det/det_ppocrv3/student"
对Global范围内参数的设置只能使用一个-o，在一些教程里面混有第一种用法，你可以检测一下自己的notebook是否是正确的
