### ISSUE TITLE
关于PP-Structure中使用ppyolov2_r50vd_dcn_365e_publaynet报错，急急急！！！！

### ISSUE THREAD

**Issue by dantaxxxx** [PaddlePaddle/PaddleOCR#5619]
根据教程 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppstructure/README_ch.md 调用命令时，当模型库为en_ppocr_mobile_v2.0_table_structure_infer不报错，模型库为ppyolov2_r50vd_dcn_365e_publaynet时报错；
调用命令python3 predict_system.py --det_model_dir=inference/ch_ppocr_server_v2.0_det_infer --rec_model_dir=inference/ch_ppocr_server_v2.0_rec_infer --table_model_dir=inference/ppyolov2_r50vd_dcn_365e_tableBank_latex --image_dir=/home/PaddleOCR/doc/3.png --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --output=../output/table --vis_font_path=../doc/fonts/simfang.ttf --use_gpu=False；
报错截图
![image](https://user-images.githubusercontent.com/45675623/156520943-71ae5e05-de2f-4ca1-9dfc-e3bb67ad14ff.png)

**Comment by dantaxxxx** [comment]
而且我如何把版面分析功能添加进入PaddleServing中，现在使用OCR采用采用ocr_system,是否能集成进去了。

**Comment by Babysun-ljh** [comment]
我也有这个问题，请问你解决了吗

**Comment by dantaxxxx** [comment]
@Babysun-ljh 没有解决，能加个VX吗,沟通一下，我的V songhuaxu_

**Comment by WenmuZhou** [comment]
1. 你模型给错了呀，表格识别的模型参数你给了版面分析的模型
2. 加入PaddleServing，需要参考这个https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/deploy/pdserving/web_service.py 将https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/predict_system.py#L38添加进去

**Comment by dantaxxxx** [comment]
@WenmuZhou 谢谢大佬，刚好在看你讲的课

**Comment by dantaxxxx** [comment]
@WenmuZhou 大佬能不能说说怎么将服务集成进hubServing，前面说错了，不好意思，这两天一直都在干这事儿，没啥头绪

**Comment by WenmuZhou** [comment]
你看看ocr那个hubserving你看得懂不，照着那个来就行了，python的预测代码都有提供的
