### ISSUE TITLE
dbnet neck更换 FPNC后训练正常，模型转换也正常 infer/predict_det.py错误

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/PaddleOCR#5620]
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 16, 16] and the shape of Y = [1, 256, 20, 20]. Received [16] in X is not equal to [20] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
      [operator < elementwise_add > error]

**Comment by WenmuZhou** [comment]
输入shape多大，这个看起来是输入不是32倍数的原因

**Comment by zgq91** [comment]
> 

已经解决了这个问题，是图像输入大小问题，我想问一下tensorrt的动态输入min_input_shape,max_input_shape,opt_input_shape,max_pact_shape，opt_pact_shape这些参数如何设置

**Comment by zzwwr** [comment]
额 您好 我文本识别 转模型后拿出来单独测试也出来了这个问题   想问图片的输入大小应该是多大？

**Comment by LDOUBLEV** [comment]
min_input_shape,
max_input_shape,
opt_input_shape
分别是TRT预测时，模型输入的最小shape，最大shape，以及最优预测的shape
设置这三个就够了

**Comment by zgq91** [comment]
> 额 您好 我文本识别 转模型后拿出来单独测试也出来了这个问题 想问图片的输入大小应该是多大？

根据你自己转换时的设置的图像大小，我的设置成32*32
