### ISSUE TITLE
Test accuracy on custom dataset

### ISSUE THREAD

**Issue by maiiabocharova** [PaddlePaddle/PaddleOCR#5621]
Hello, thank you for the awesome OCR!

Can you please help me: I want to test models on my dataset (there are pictures in .png format and ground truth in the json format with bboxes and text). How can I test accuracy of the model's predictions?

P.S thank you in advance, I know it's a rather beginner-level question.

**Comment by WenmuZhou** [comment]
1. detection, you can prepare data accroding to https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/detection.md#1-%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE%E5%92%8C%E6%A8%A1%E5%9E%8B
2. recognition, you can prepare data accroding to https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/recognition.md#11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86
