### ISSUE TITLE
使用自己训练好的文本识别模型 进行文本混剪是出现报错：File "G:\PaddleOCR-release-2.4\ppocr\postprocess\rec_postprocess.py", line 60, in decode     if text_index[batch_idx][idx] in ignored_tokens: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by zzwwr** [PaddlePaddle/PaddleOCR#5624]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by zzwwr** [comment]
解决方法：if text_index[batch_idx][idx] in ignored_tokens: 改为 if text_index[batch_idx][idx] in ignored_tokens:

**Comment by littletomatodonkey** [comment]
你好，建议再描述的清楚些，最好可以复现你的这个报错

**Comment by zzwwr** [comment]
额 这个问题怎么描述呢？  我用文字识别训练好的模型转换成功后  单独进行测试  就报了如下错误
