### ISSUE TITLE
paddleocr  2.4  cpp_infer 识别的行顺序错误

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5631]
paddleocr  2.4 
paddle_inference版本号
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
CXX compiler version: 5.4.0

模型是：
ch_ppocr_mobile_v2.0_cls_infer.tar
ch_ppocr_server_v2.0_det_infer.tar
ch_ppocr_server_v2.0_rec_infer.tar

./build/ppocr system     --det_model_dir=/home/install/models/det_1      --rec_model_dir=/home/install/models/rec_1     --image_dir=/home/install/detect_pic/train/25.jpg

I0304 16:46:18.526057  5508 main.cpp:219] The predict img: /home/install/detect_pic/train/25.jpg
Detected boxes num: 3
The detection visualized image saved in ./ocr_vis.png
lineY:46
东胜,score:0.998107
lineY:120
内蒙古,score:0.999526
lineY:191
鄂尔多斯,score:0.999218

图片
![25](https://user-images.githubusercontent.com/75007961/156732135-9cdd3e3a-3106-44e4-975c-d1fba573e077.jpg)

**Comment by littletomatodonkey** [comment]
你好，这是因为cpp inference中，没有对检测框进行坐标排序

**Comment by linkewei0580** [comment]
> 你好，这是因为cpp inference中，没有对检测框进行坐标排序

    int img_num = img_list.size();
    std::vector<float> width_list;
    for (int i = 0; i < img_num; i++) { 
   //计算宽/高比率     
  width_list.push_back(float(img_list[i].cols) / img_list[i].rows);   
 }   
// 按宽/高比率进行排序
 std::vector<int> indices = Utility::argsort(width_list);

        for (int ino = beg_img_no; ino < end_img_no; ino ++) {
            cv::Mat srcimg;
           //获取这图片的经过宽/高比率排序过的图片的顺序？我们在使用的时候怎么再把这个图片的顺序和坐标对应起来过来？最好在main.cpp 能够把box 和 内容可以一一对应，顺序的话我们自己可以去排序。
            img_list[indices[ino]].copyTo(srcimg);
            cv::Mat resize_img;
            this->resize_op_.Run(srcimg, resize_img, max_wh_ratio, this->use_tensorrt_);
            this->normalize_op_.Run(&resize_img, this->mean_, this->scale_, this->is_scale_);
            norm_img_batch.push_back(resize_img);
        }

**Comment by WenmuZhou** [comment]
你好，这个排序只是方便识别进行的按照图片宽度排序

**Comment by linkewei0580** [comment]
已经解决。

**Comment by luodaoyi** [comment]
请问最后怎么解决的？

**Comment by shengzhe8688** [comment]
<img width="497" alt="1651806377(1)" src="https://user-images.githubusercontent.com/16428236/167060290-1dcd534a-5d76-463f-8125-155781cd7920.png">
最终还是使用这个方法 取出来的Box顺序就是识别结果的顺序。

**Comment by shengzhe8688** [comment]
![image](https://user-images.githubusercontent.com/16428236/167060599-e495900e-ac70-466a-b1cf-446b1dc97908.png)
最终还是使用这个方法 取出来的Box顺序就是识别结果的顺序。
