### ISSUE TITLE
检测模型的预训练权重

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5634]
在使用预训练权重去训练检测模型时候，发ResNet18有两个两个链接，请问这两个有什么区别
（1） 这个[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/de3e2e7cd3b8b65ee02d7a41e570fa5b511a3c1d/doc/doc_ch/detection.md)里面的
![image](https://user-images.githubusercontent.com/37231239/156747367-b910df37-54f1-4109-a2be-cb41fad1f156.png)
（2）第二个[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md)里的
![image](https://user-images.githubusercontent.com/37231239/156747544-6fd7c72a-6843-49ff-b579-598d3281852c.png)

**Comment by yjhtc007** [comment]
我个人感觉第一个是只有Backbone部分的权重，且模型是在ImageNet这种公开数据集上预训练得到的。下面这个模型是中英文检测模型的权重吧。

**Comment by littletomatodonkey** [comment]
> 我个人感觉第一个是只有Backbone部分的权重，且模型是在ImageNet这种公开数据集上预训练得到的。下面这个模型是中英文检测模型的权重吧。

是的

**Comment by GivanTsai** [comment]
> > 我个人感觉第一个是只有Backbone部分的权重，且模型是在ImageNet这种公开数据集上预训练得到的。下面这个模型是中英文检测模型的权重吧。
> 
> 是的

微调检测模型的话用的是第二个权重吧
