### ISSUE TITLE
文字识别使用自定义字典训练精度卡死

### ISSUE THREAD

**Issue by LopSdir** [PaddlePaddle/PaddleOCR#5635]
本人在aistudio上进行训练，随机生成身份证号码大约200w条的训练数据，使用的配置文件是```rec_chinese_common_train_v2.0.yml```, 只替换了里面的字典，其他数据没有修改。但是训练到准确度在0.33左右的时候一直卡在此处，准确度不再上升，求如何解决
我只需要识别数字，生成的身份证号码使用了其他字体生成。

**Comment by littletomatodonkey** [comment]
真实数据和合成数据在一个batch 内的训练比例建议修改为5:1~10:1左右

**Comment by LopSdir** [comment]
好的，我在试试看吧
