### ISSUE TITLE
部分android手机模型预测特别慢

### ISSUE THREAD

**Issue by bebbieyin** [PaddlePaddle/PaddleOCR#5636]
模型是加了自己的数据训练的，然后用python脚本的 opt 优化成 .nb模型。

Android的程序也是用这里给的 android_demo试的，只是把里面的 ch_ppocr_mobile_v2.0_rec_opt.nb 模型换成自己的。 

放进模型前我都会把图片压缩到 1MB。

大多数手机都没问题，预测时间都在1000ms里面，可是用 Xiaomi Pocophone F1 预测时间可以在非常不稳定，例子如下：

第一次 ：643ms
第二次 ：41201ms
第三次 ：22390ms

请问是什么原因？

P.S. 第一次开帖，规则不是很懂，有什么需要补充的请跟我说。

**Comment by WenmuZhou** [comment]
辛苦补充一下测试过得手机型号，cpu型号和对应速度

**Comment by bebbieyin** [comment]
> 辛苦补充一下其他测试过得手机型号，cpu型号和对应速度 另外，速度可能和手机后台是否有其他任务有关，测试之前是否清空了后台或者重启手机呢

你好， 以下是其他手机型号的检测结果：

**手机型号** ：Huawei Mate 20
**CPU型号** ： 2600 MHz (Huawei Hisilicon Kirin 980, Cores : 8）
**对应速度** ：476ms

**手机型号** ：Huawei Nova 2i
**CPU型号** ： 2360 MHz (Huawei Hisilicon Kirin 659, Cores : 8)
**对应速度** ：1728ms

**手机型号** ：Honor 50
**CPU型号** ： 2400 MHz (Qualcomm Snapdragon 778G (SM7325), Cores: 8)
**对应速度** ：606ms

**手机型号** ：Realme 5 Pro
**CPU型号** ： 2300 MHz (Qualcomm Snapdragon 712, Cores: 8)
**对应速度** ：608ms

**Comment by bebbieyin** [comment]
问题已解决，之前测试的用的是 armeabi-v7a 版本的apk，需要用 arm64-v8a 版本。
