### ISSUE TITLE
C++版推理重复实例化Recognizer类加载模型会造成内存泄露

### ISSUE THREAD

**Issue by SwaggyMacro** [PaddlePaddle/PaddleOCR#5639]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

C++版推理重复实例化Recognizer类加载模型会造成内存泄露

- 系统环境/System Environment：Windows 10 1909
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.0
- 运行指令/Command Code：LoadModel
- 完整报错/Complete Error Message：无
![3RU)YC$RN8W(YULNS0982NC](https://user-images.githubusercontent.com/38845682/156909442-bef5784b-95bb-40d6-b0ed-686ea6cda26e.png)
![UN}AO`W9EX1F}BTGVT6O0(I](https://user-images.githubusercontent.com/38845682/156909451-cf189365-7d76-41c0-b899-d2204e53127c.png)
![5FI K$B59KEL2118KVD)J`N](https://user-images.githubusercontent.com/38845682/156909475-bdb79f69-1ea7-46c9-a340-af8260599c1f.png)

**Comment by SwaggyMacro** [comment]
我是把C++版本推理封装成了dll给C# ，更换语言模型的时候重新实例化CRNNRecognizer会造成内存泄露

**Comment by WenmuZhou** [comment]
你好，我看你关闭又打开，是有新情况吗

**Comment by SwaggyMacro** [comment]
> 你好，我看你关闭又打开，是有新情况吗

谢谢回复，之前是不小心关闭了，然后后续没有再尝试任何解决方案（自身时间原因），目前还没有解决

**Comment by WenmuZhou** [comment]
c#可以试一下这个 https://github.com/sdcb/PaddleSharp

**Comment by SwaggyMacro** [comment]
> c#可以试一下这个 https://github.com/sdcb/PaddleSharp

OKOK，后续有空我试一下，感谢您的回复！
