### ISSUE TITLE
如何使用SRN推理？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleOCR#564]
1. 下载SRN模型：https://paddleocr.bj.bcebos.com/SRN/rec_r50fpn_vd_none_srn.tar
2. 解压【rec_r50fpn_vd_none_srn】后，只有一个文件【best_accuracy.pdparams】与一个文件夹【paper_weights】
3. 无法通过【export_model.py】导出模型（提示：**Warning! SRN does not support export model currently**）
4. 那么该如何使用SRN推理？

**Comment by WenmuZhou** [comment]
export_model我们本周争取放出来，只执行infer的话可以用infer_rec.py

**Comment by 670133189** [comment]
> export_model我们本周争取放出来，只执行infer的话可以用infer_rec.py

嗯，那么如何直接infer？【--rec_model_dir】的值是哪个？

另外SRN可以识别数字吗？

**Comment by zhang-deep** [comment]
> export_model我们本周预期放出来，只执行infer的话可以用infer_rec.py

用srn训练出来模型后，用用infer_rec.py预测，报错AssertionError: Each dimension value of 'shape' in reshape must not be negative except one unknown dimension. But received shape[2] = -4.

参数是这样：python tools/infer_rec.py -c configs/rec/rec_r50fpn_vd_none_srn.yml -o Global.checkpoints=./output/rec_pvam_withrotate/best_accuracy Global.infer_img=./doc/our_img/src.jpg
