### ISSUE TITLE
PaddleServing怎样修改相关参数

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#5641]
根据  [**基于PaddleServing的服务部署**](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/pdserving/README_CN.md) 后，怎样对模型及服务的一些参数进行修改呢？
例如如下参数：
use_tensorrt
batch_size
det_limit_side_len
batch_num
total_process_num
...

疑惑：
1、[**PaddleHub Serving部署**](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/hubserving/readme.md)，支持一些参数修改
2、[**基于Python引擎的PP-OCR模型库推理**](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/inference_ppocr.md)，也支持参数修改

上面列举的几个参数都极其重要，但是PaddleServing方法却不支持，请指示！是否是哪里可以设置而我没找到

**Comment by Biaocsu** [comment]
@andyjpaddle @tink2123

**Comment by tink2123** [comment]
PaddleServing 目前还没有把参数暴露出来，可以先手动修改源码：
https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/deploy/pdserving/web_service.py#L31

后续我们会更新serving代码，把参数放在配置文件中。
