### ISSUE TITLE
可以使用同一套c++代码部署到各个平台吗

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleOCR#5642]
Hi, PaddleOCR Teams,
我想问一下，我们的PaddleOCR 支持c++部署到MAC/IOS/Windows/Android上面吗？并且使用同一套c++部署代码

**Comment by andyjpaddle** [comment]
我们提供了多种部署方式，可以在这里查看选择合适的方式 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy
