### ISSUE TITLE
修改了自己的字典文件，代码提示字典中字符越界。不是只是在ppocr/utils下生成字典就够了吗？（配置文件字典路径也修改了）

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleOCR#5647]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by dengmingD** [comment]
ppocr\postprocess\rec_postprocess.py 第67行
char_list.append(self.character[int(text_index[batch_idx][
                    idx])])
是这报错吗

**Comment by tuodi** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 修改了自己的字典文件，代码提示字典中字符越界。不是只是在ppocr/utils下生成字典就够了吗？（配置文件字典路径也修改了） (Issue #5647)





 
ppocr\postprocess\rec_postprocess.py 第67行
 char_list.append(self.character[int(text_index[batch_idx][
 idx])])
 是这报错吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuodi** [comment]
我代码调试时，我的字典文件已经被加载成功了呀。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 修改了自己的字典文件，代码提示字典中字符越界。不是只是在ppocr/utils下生成字典就够了吗？（配置文件字典路径也修改了） (Issue #5647)





 
ppocr\postprocess\rec_postprocess.py 第67行
 char_list.append(self.character[int(text_index[batch_idx][
 idx])])
 是这报错吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andyjpaddle** [comment]
麻烦提供一下详细报错信息

**Comment by dengmingD** [comment]
修改一下，int(text_index[batch_idx][idx]) 当这个值大于len(character)时，取len(character) - 1

**Comment by Babysun-ljh** [comment]
你用的什么算法呢，有的算法要设置use_space_char=False

**Comment by tuodi** [comment]
我用的中文识别模型，应该是可以设置该参数为True的吧？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 修改了自己的字典文件，代码提示字典中字符越界。不是只是在ppocr/utils下生成字典就够了吗？（配置文件字典路径也修改了） (Issue #5647)





 
你用的什么算法呢，有的算法要设置use_space_char=False
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dengmingD** [comment]
想跑起来，一定要改代码
改use_space_char=False也有可能出错
