### ISSUE TITLE
我发现中英文通用模型中对于特殊字符识别不佳，如φ，∑

### ISSUE THREAD

**Issue by dantaxxxx** [PaddlePaddle/PaddleOCR#5649]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
能提供一些详细的识别效果吗？

**Comment by dengmingD** [comment]
我觉得可能是样本少，可以用notpad++统计一下这两个符号有多少个，如果少，可以增加样本量

**Comment by dantaxxxx** [comment]
@andyjpaddle  φ通常会识别不出来，或识别为o ，而∑则会识别成C

**Comment by sunzhaoyang** [comment]
Δ 会被识别成 A
