### ISSUE TITLE
关于android部署的提问

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#5651]
作者您好，在做安卓部署时，由于小网络效果欠佳，所以考虑更换骨干特征网络等，向您请教几个问题
    1.是否可以更换Architecture中的algorithm，比如在训练检测模型时将DB换为EAST,更换后的模型是否能够在安卓端使用
    2.是否可以将Backbone中的name从MobileNetV3改为ResNet，是否可以将model_name从small改为large或者增加网络层数，以及修改后训练的模型是否能够在安卓端被支持
   3.以损失识别速度为代价，有没有进一步提高精度的方法，

**Comment by WenmuZhou** [comment]
1.不可以，目前安卓只支持db
23均可以

**Comment by zhang0225** [comment]
好的，那我重新训练，感谢您的回复
