### ISSUE TITLE
ppstructure问题

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#5652]
问题：UnboundLocalError: local variable 'label' referenced before assignment

设置了layout model path :   parser.add_argument("--layout_path_model", type=str,default="../inference/ppyolov2_r50vd_dcn_365e_publaynet/")

初始化table_layout是不是缺少 label加载，
![image](https://user-images.githubusercontent.com/5669444/157149690-8834ba4e-f087-4a85-ba1c-fd5a71a24598.png)

**Comment by WenmuZhou** [comment]
你好，已定位，修复中

**Comment by WenmuZhou** [comment]
感谢提供的bug信息，已经修复了https://github.com/PaddlePaddle/PaddleOCR/pull/5692
