### ISSUE TITLE
微调识别模型出现过拟合

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5653]
我在识别模型预训练权重上进行微调，一开始在验证集上的Acc达到了0.7左右，而后开始降低，降到0.5-，可能出现过拟合了，怎么调整呢；
我使用的参数：
`Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00005
  regularizer:
    name: 'L2'
    factor: 0.00004`

**Comment by yjhtc007** [comment]
单纯用识别模型进行验证的acc能到多少呢？

**Comment by GivanTsai** [comment]
> 

0.6左右

**Comment by tink2123** [comment]
建议增加训练数据量和丰富度

**Comment by GivanTsai** [comment]
> 建议增加训练数据量和丰富度

使用的合成数据训练，acc很容易就达到了0.99+，增加更多的丰富度，可能会跟真实场景不符合，会不会有反作用
