### ISSUE TITLE
请问有lvst处理好的数据集吗？

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#566]
想使用db训练lvst2019数据集，不过不知道该怎样具体处理标签，请问能给我一份处理好的标签吗？谢谢

**Comment by MissPenguin** [comment]
按照教程转换一下格式就行哈：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87

**Comment by zcswdt** [comment]
> 想使用db训练lvst2019数据集，不过不知道该怎样具体处理标签，请问能给我一份处理好的标签吗？谢谢

https://github.com/zcswdt/OCR_ICDAR_label_revise，这里我将josn文件处理成了txt标签的，可以参考一下

**Comment by tyy2tyy** [comment]
多谢
