### ISSUE TITLE
文字识别将预训练模型导出为推理模型后，在测试准确率会上升

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleOCR#5661]
自己标注的数据集，使用了ch_ppocr_mobile_v2.0_rec_train和ch_ppocr_mobile_v2.0_rec_pre两个预训练模型，用paddleocr中的tools/eval.py进行测试，准确率大约在55%，将这两个模型用tools/exorpt_model.py导出为推理模型后，使用predict_rec.TextRecognizer(args)方法，我自己写了一个脚本来比对预测结果和标签来计算准确率，发现差别比较大，可以达到70%。不知道是什么原因。查看了eval.py的代码，计算准确率也只是看字符串是否完全一致

**Comment by tink2123** [comment]
推理模型不会再对文本进行固定shape的padding，而是按当前batch最大长度padding。 可以问下您训练的shape是多少，训练数据是否都是很长的文本呢？

**Comment by ezekielqu** [comment]
> 

训练的shape是默认的[3, 32, 320]。我的数据中大约有30%是长度大于30个字符的长文本。请问为什么推理模型使用的这种padding方式会提升准确率呢？

**Comment by ezekielqu** [comment]
> 推理模型不会再对文本进行固定shape的padding，而是按当前batch最大长度padding。 可以问下您训练的shape是多少，训练数据是否都是很长的文本呢？

训练的shape是默认的[3, 32, 320]。我的数据中大约有30%是长度大于30个字符的长文本。请问为什么推理模型使用的这种padding方式会提升准确率呢？

**Comment by tink2123** [comment]
训练过程中的评估，会把图片resize到固定[3，32，320] 的长度，如果存在很多长文本可能会出现过度压缩导致失真。预测时不会压缩图片宽度，因此能较好的还原图片中的信息，可以提升准确率。

**Comment by ezekielqu** [comment]
> 您好，请问可以分享一下计算推理模型准确度的脚本吗

import cv2
import numpy as np
import tools.infer.utility as utility
import tools.infer.predict_rec as predict_rec

args = utility.parse_args()
args.rec_model_dir = './inference/ch_PP-OCRv3_rec_infer'
text_recognizer = predict_rec.TextRecognizer(args)

data_label = './train_data/rec/train.txt'
with open(data_label, 'r') as f:
    annotations = f.readlines()

correct = 0
for item in annotations:
    path, label = item.split("\t")
    image = cv2.imread(path)
    label = label.replace(" ", "").replace("\n", "")
    rec_res, elapse = text_recognizer(image)
    result = rec_res[0][0].replace(" ", "")
    if result == label:
        correct += 1

print('acc', correct/len(annotations))

只是简单对比了一下去掉空格后字符串是否相同
