### ISSUE TITLE
识别的数据集大概多少够呢？

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5663]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by ziyaxuanyi** [comment]
如果是自己学习用，几万到几十万就够了。如果是通用场景工程落地部署实际应用，数据量要到千万级别，尽量保证字典中每个字符都要有训练样本，尽可能做到数据平衡，才会有比较好的效果；特定场景的话，几十万到几百万应该是够了

**Comment by GivanTsai** [comment]
> 如果是自己学习用，几万到几十万就够了。如果是通用场景工程落地部署实际应用，数据量要到千万级别，尽量保证字典中每个字符都要有训练样本，尽可能做到数据平衡，才会有比较好的效果；特定场景的话，几十万到几百万应该是够了

这么大的数据量，是使用合成的还是真实数据

**Comment by ziyaxuanyi** [comment]
当然是合成的啊，少部分真实数据+大量合成数据。这么大数据量全用真实基本不可能，太费人工物力了

**Comment by BruceHan98** [comment]
> 如果是自己学习用，几万到几十万就够了。如果是通用场景工程落地部署实际应用，数据量要到千万级别，尽量保证字典中每个字符都要有训练样本，尽可能做到数据平衡，才会有比较好的效果；特定场景的话，几十万到几百万应该是够了

请问对于合成的语料，有什么方法控制字符的平衡吗？

**Comment by ziyaxuanyi** [comment]
> > 如果是自己学习用，几万到几十万就够了。如果是通用场景工程落地部署实际应用，数据量要到千万级别，尽量保证字典中每个字符都要有训练样本，尽可能做到数据平衡，才会有比较好的效果；特定场景的话，几十万到几百万应该是够了
> 
> 请问对于合成的语料，有什么方法控制字符的平衡吗？

如果你数据量是千万级别的话，字符肯定是不平衡的，因为字符那么多，但是平时常用的汉字和字符就那么几个，除非你合成的语料是随机按字符生成，但这样语料就没有语义，可能训练出来的识别效果不好（未证实）。所以要保证使用的语料尽可能多，涉及方面尽可能广，然后就是合成的数据量尽可能多，因为你数据量多，那么即使使用最少的字符也能保证有个几万到几十万的出现次数，那也能最终对这种字符有相对较好的效果。

另外从算法层面来说，focal loss损失也能缓解一定的数据不平衡问题，paddleocr已经有实现。可以先使用蒸馏技术训练一个基础模型，再使用focal loss损失来在此基础上训练微调。

**Comment by BruceHan98** [comment]
> > > 如果是自己学习用，几万到几十万就够了。如果是通用场景工程落地部署实际应用，数据量要到千万级别，尽量保证字典中每个字符都要有训练样本，尽可能做到数据平衡，才会有比较好的效果；特定场景的话，几十万到几百万应该是够了
> > 
> > 
> > 请问对于合成的语料，有什么方法控制字符的平衡吗？
> 
> 如果你数据量是千万级别的话，字符肯定是不平衡的，因为字符那么多，但是平时常用的汉字和字符就那么几个，除非你合成的语料是随机按字符生成，但这样语料就没有语义，可能训练出来的识别效果不好（未证实）。所以要保证使用的语料尽可能多，涉及方面尽可能广，然后就是合成的数据量尽可能多，因为你数据量多，那么即使使用最少的字符也能保证有个几万到几十万的出现次数，那也能最终对这种字符有相对较好的效果。
> 
> 另外从算法层面来说，focal loss损失也能缓解一定的数据不平衡问题，paddleocr已经有实现。可以先使用蒸馏技术训练一个基础模型，再使用focal loss损失来在此基础上训练微调。

好的，谢谢回复！
