### ISSUE TITLE
请问有没有英文识别准确率更好些的模型？

### ISSUE THREAD

**Issue by westwind1027** [PaddlePaddle/PaddleOCR#5670]
现在的英文数字模型是en_number_mobile_v2.0_rec，我发现有个别英文如‘J’有时会识别为‘I’，‘Q’有时会识别为‘O’，‘F’有时会识别为‘E’。

是否有准确率更好的模型，体积大些没关系，例如：en_number_server_v2.0_rec ?

**Comment by WenmuZhou** [comment]
目前还没有哈
