### ISSUE TITLE
关于C++部署

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#5673]
部署文件中加载的是图像路径，请问我要进行实时采集图像时，能否直接加载图像而不是去加载路径？如果有的话，具体是如何进行的呢？

**Comment by WenmuZhou** [comment]
这个需要改动代码，将采集到的图片传入即可

**Comment by sjsapple** [comment]
PaddleOCR-main源程序.zip如何编译啊(苏13770947095)
