### ISSUE TITLE
OCR联合预测问题，错误提示中包含“C++ Traceback (most recent call last):...”+“Error Message Summary:..”关键字

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [PaddlePaddle/PaddleOCR#5675]
## paddle版本： paddlepaddle-gpu==2.2.2 cudatoolkit=11.2 
- Paddleocr:2.3
- PaddleDetection:2.3

## 主机配置：
- 系统：ubuntu 20.04 
- GPU：3060 lp 12G
- CUDA：11.2
- CUDNN：8.1.1
- Driver Version:：470.103.01  
### 错误代码提示：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::PrepareData(paddle::framework::Scope const&, paddle::framework::OpKernelType const&, std::vector<std::string, std::allocator<std::string > >*, paddle::framework::RuntimeContext*) const
6   paddle::framework::Scope::Var(std::string const&)
7   paddle::framework::Scope::VarInternal(std::string const&)
8   paddle::framework::Scope::FindVarLocally(std::string const&) const

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1646819844 (unix time) try "date -d @1646819844" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7f0ed4751034) received by PID 6037 (TID 0x7f0e8c859700) from PID 18446744072979025972 ***]
```

**Comment by Jeck-Liu-Create** [comment]
发现在 paddleocr issues 中也有一个类似的问题，貌似问题也是发生在执行`predict_det.TextDetector(args)`阶段。
https://github.com/PaddlePaddle/PaddleOCR/issues/2081

**Comment by Jeck-Liu-Create** [comment]
我看到这则[issues](https://github.com/PaddlePaddle/PaddleOCR/issues/4174) 中提及输入图片形状，您看是图片形状的问题吗？
### 没问题的裁剪图片的坐标：
- upleft_x: 189.95822 , upleft_y: 120.49188 , lowright_x: 1030.1108 , lowright_y: 994.63544
- upleft_x: 242.18628 , upleft_y: 129.47473 , lowright_x: 1188.8795 , lowright_y: 986.0991
- upleft_x: 425.6651 , upleft_y: 4.053467 , lowright_x: 1376.9204 , lowright_y: 909.3124
- upleft_x: 546.60364 , upleft_y: 122.58539 , lowright_x: 1479.9559 , lowright_y: 991.02716
- upleft_x: 651.54486 , upleft_y: 112.41611 , lowright_x: 1597.4592 , lowright_y: 1010.07886
- upleft_x: 710.0104 , upleft_y: 100.96655 , lowright_x: 1712.3358 , lowright_y: 1017.86316
- upleft_x: 820.2284 , upleft_y: 0.0 , lowright_x: 1741.0885 , lowright_y: 805.2363
- upleft_x: 690.79266 , upleft_y: 188.26373 , lowright_x: 1907.3201 , lowright_y: 1040.4707

### 出现问题的一次预测的坐标：
- upleft_x: 126.03961 , upleft_y: 207.33942 , lowright_x: 896.43256 , lowright_y: 1016.5815

**Comment by LDOUBLEV** [comment]
> 出现问题的一次预测的坐标：
> upleft_x: 126.03961 , upleft_y: 207.33942 , lowright_x: 896.43256 , lowright_y: 1016.5815

把这个坐标的截图拿出来，输入给PaddleOCR预测，可以正常得到结果吗？

**Comment by Jeck-Liu-Create** [comment]
> > 出现问题的一次预测的坐标：
> > upleft_x: 126.03961 , upleft_y: 207.33942 , lowright_x: 896.43256 , lowright_y: 1016.5815
> 
> 把这个坐标的截图来，输入给PaddleOCR预测，可以得到结果吗？

[图片](https://note.youdao.com/yws/api/personal/file/F10E175D226547A7B4B0E5408601AA4A?method=download&shareKey=6f2f53c1ab146ba35a18e8145c502c89)

其中绿色是错误坐标截取出图片的位置，其他是没问的图片坐标位置；我尝试将det_limit_side_ln 修改为1920，也会出现这样的问题，开始一段时间正常运行，5~10分钟后就出现这个错误。

**Comment by Jeck-Liu-Create** [comment]
> > 出现问题的一次预测的坐标：
> > upleft_x: 126.03961 , upleft_y: 207.33942 , lowright_x: 896.43256 , lowright_y: 1016.5815
> 
> 把这个坐标的截图拿出来，输入给PaddleOCR预测，可以正常得到结果吗？

几乎只有SAST会出先这个问题，我测试了PGNET不会出现这个问题

**Comment by Wangzheee** [comment]
> ## 问题发送过程：用PaddleDetection和PaddleOCR同时使用，将PaddleDetection检测结果传入PaddleOCR得到期望数据。系统开始一段时间正常运行，输出结果比较理想，几分钟后程序运行到`perdict_system_1780.main(utility.parse_args(), image)`[perdict_system_1780代码](https://github.com/Jeck-Liu-Create/paddle-issues/blob/main/predict_system_1780.py),[utility代码](https://github.com/Jeck-Liu-Create/paddle-issues/blob/main/utillty.py)
> ## paddle版本： paddlepaddle-gpu==2.2.2 cudatoolkit=11.2
> * Paddleocr:2.3
> * PaddleDetection:2.3
> 
> ## 主机配置：
> * 系统：ubuntu 20.04
> * GPU：3060 lp 12G
> * CUDA：11.2
> * CUDNN：8.1.1
> * Driver Version:：470.103.01
> 
> ### 错误代码提示：
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::AnalysisPredictor::ZeroCopyRun()
> 1   paddle::framework::NaiveExecutor::Run()
> 2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> 3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> 4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> 5   paddle::framework::OperatorWithKernel::PrepareData(paddle::framework::Scope const&, paddle::framework::OpKernelType const&, std::vector<std::string, std::allocator<std::string > >*, paddle::framework::RuntimeContext*) const
> 6   paddle::framework::Scope::Var(std::string const&)
> 7   paddle::framework::Scope::VarInternal(std::string const&)
> 8   paddle::framework::Scope::FindVarLocally(std::string const&) const
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Erroneous arithmetic operation` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1646819844 (unix time) try "date -d @1646819844" if you are using GNU date ***]
>   [SignalInfo: *** SIGFPE (@0x7f0ed4751034) received by PID 6037 (TID 0x7f0e8c859700) from PID 18446744072979025972 ***]
> ```

您好，可以发一下完整的log吗？
