### ISSUE TITLE
请教一下关于batchsize的设置

### ISSUE THREAD

**Issue by HenrySZP** [PaddlePaddle/PaddleOCR#5676]
哈喽，关于batchsize的设置想请教一下。我这边的设备是两块A6000的卡，每块是48000MiB的显存，400W的数据集，两块卡同时训练，batchsize应该设多少合适呢？

**Comment by WenmuZhou** [comment]
可以进行不同的尝试，占满显存即可，建议从64开始尝试

**Comment by HenrySZP** [comment]
> 

一般batchsize都设为1200才可以占满😂
