### ISSUE TITLE
PaddleOCR server 短时间内访问 ,服务器返回为空,如何取消限制

### ISSUE THREAD

**Issue by yigedongwu** [PaddlePaddle/PaddleOCR#5678]
比如一秒内访问服务器两次 ,第二次直接返回结果为空,改如何配置参数, 取消限制呢

- 系统环境/System Environment：
- 版本号/Version：中英文通用PP-OCR server

**Comment by littletomatodonkey** [comment]
你好，这边应该没有单独设置这样的限制，方便发下可复现的步骤过来看看嘛？

**Comment by tink2123** [comment]
可以查看一下 PipelineServingLogs/pipeline.log 里的报错信息，可能是显存不足。
