### ISSUE TITLE
关于模型转换

### ISSUE THREAD

**Issue by butterniu** [PaddlePaddle/PaddleOCR#5679]
关于模型转换有一个问题像您请教一下，我训练好后
latest.pdopt
latest.pdparams
latest.states
我通过python tools/export_model.py
模型转换后
inference.pdiparams
inference.pdiparams.info
inference.pdiparams.info

但是我期望的是
model
params
俩个参数文件，请问如何可以做到
我用的是paddle2.0

**Comment by butterniu** [comment]
我训练的是paddleocr识别模型

**Comment by littletomatodonkey** [comment]
你好，`inference.pdiparams`对应`params`， `inference.pdmodel`对应`model `，直接重命名就好
