### ISSUE TITLE
识别模型难收敛

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#5682]
我在英文识别配置文件（rec_en_number_lite_train.yml）中修改了一些内容来适用我的需求，并对字典中的内容做了修改，之前我的backbone为small的时候直接使用en_number_mobile_v2.0_rec_train.tar作为预训练文件能够很快收敛，但是在我将backbone改为large的时候模型收敛速度非常慢，使用的预训练权重是rec_mv3_none_bilstm_ctc_v2.0_train，如果我在配置文件里将  pretrained_model设置为下载的权重会报各种网络结构不匹配的问题同时收敛速度很慢，我使用命令python tools/train.py -c configs/rec/multi_language/rec_en_number_lite_train.yml -o Global.pretrain_weights=./pretrain_models/rec_mv3_none_bilstm_ctc_v2.0_train/best_accuracy 不会报错但是会出现难收敛的情况，收敛速度非常慢，下面是我的训练日志，训练日志里有配置文件以及训练过程，以及我使用的字典，请问是不是我的配置文件里有不合理的地方

[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/8220689/train.log)
[ppocr_keys_v1.txt](https://github.com/PaddlePaddle/PaddleOCR/files/8220696/ppocr_keys_v1.txt)

**Comment by littletomatodonkey** [comment]
你好，目前paddleocr没有提供其他backbone的预训练模型，因此参数需要全部从0初始化训练，对数据量的要求比较大

**Comment by zhang0225** [comment]
> 你好，目前paddleocr没有提供其他backbone的预训练模型，因此参数需要全部从0初始化训练，对数据量的要求比较大

感谢您的回复，确实可能是我的数据量比较少导致的
