### ISSUE TITLE
RARE报错

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5685]
403     raise self.exc_type(msg)
404 ValueError: DataLoader worker(3) caught ValueError with message:
405 Traceback (most recent call last):
406   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_lo    op
407     batch = fetcher.fetch(indices)
408   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
409     data = self.collate_fn(data)
410   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_co    llate_fn
411     return [default_collate_fn(fields) for fields in zip(*batch)]
412   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
413     return [default_collate_fn(fields) for fields in zip(*batch)]
414   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_co    llate_fn
415     batch = np.stack(batch, axis=0)
416   File "<__array_function__ internals>", line 180, in stack
417   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/numpy/core/shape_base.py", line 426, in stack
418     raise ValueError('all input arrays must have the same shape')
419 ValueError: all input arrays must have the same shape
420
421 Traceback (most recent call last):
422   File "tools/train.py", line 149, in <module>
423     main(config, device, logger, vdl_writer)
424   File "tools/train.py", line 124, in main
425     program.train(config, train_dataloader, valid_dataloader, device, model,
426   File "/data/ocr/PaddleOCR-release-2.4/tools/program.py", line 307, in train
427     cur_metric = eval(
428   File "/data/ocr/PaddleOCR-release-2.4/tools/program.py", line 397, in eval
429     for idx, batch in enumerate(valid_dataloader):
430   File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in _    _next__
431     data = self._reader.read_next_var_list()
432 SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
433   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_q    ueue.h:166)
434
435 ^Meval model::   0%|          | 0/14 [00:00<?, ?it/s]
"rec_rare_r34.out" [noeol] 435L, 63316C  

训练RARE到第八个epoch出错了，有人帮看为啥吗

**Comment by littletomatodonkey** [comment]
你好，看着是资源的问题，把num worker修改为0试下呢？

**Comment by gachiemchiep** [comment]
I met same problem. 

The log files below is created using same command, same dataset and same configuration. 
But using release/2.4 lead to above error. 
Switch into release/2.3 fixed it. 

[2.3.log](https://github.com/PaddlePaddle/PaddleOCR/files/8504071/2.3.log)
[2.4.log](https://github.com/PaddlePaddle/PaddleOCR/files/8504072/2.4.log)
