### ISSUE TITLE
ImportError: cannot import name 'PaddleOCR' from partially initialized module 'paddleocr' (most likely due to a circular import)

### ISSUE THREAD

**Issue by GeekDream-x** [PaddlePaddle/PaddleOCR#5686]
- 系统环境/System Environment：macOS Monterey 12.2.1

- 版本号/Version

paddlepaddle:2.2.2    paddleocr:2.4   paddlenlp:2.2.4

- 运行指令/Command Code
![截屏2022-03-10 下午4 40 25](https://user-images.githubusercontent.com/52285873/157621969-ac545a45-2dc7-4535-bd7a-070c232c7695.png)

- 完整报错/Complete Error Message：
![截屏2022-03-10 下午4 45 02](https://user-images.githubusercontent.com/52285873/157623423-d7ba9f0a-9f78-45f6-b31c-e7a0e3c89cdb.png)

**Comment by littletomatodonkey** [comment]
你好，先测试下当前的官方给的示例看看呢？或者把你报错的代码发出来运行下，怀疑是sys.path中包含了多个paddleocr相关的环境变量，可以debug看下

**Comment by GeekDream-x** [comment]
谢谢 跟我脚本命名有关 换了就好了

**Comment by gonglch** [comment]
哈哈 我们的脚本命名一样的。。

**Comment by laster-lee** [comment]
hhh,我也是，服了自己了

**Comment by akamodedef** [comment]
历史总是惊人的相似
