### ISSUE TITLE
kie模型导出inference模型及serving模型教程

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleOCR#5691]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： 
- aistudio 至尊版
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddle2.2.2
- 运行指令/Command Code：
- 
![4763776b5afa67530cbef8f6399bc43](https://user-images.githubusercontent.com/18511799/157666458-d8dbaa57-f60e-4bf1-bfc2-878d8a178bd1.png)

- 完整报错/Complete Error Message：
![e8eff2d869b55222cb8e90abf0f88b6](https://user-images.githubusercontent.com/18511799/157666484-22c207a3-aa00-4a59-8fd0-831afe32ba11.png)

希望提供serving和inference模型转化的示例教程

**Comment by littletomatodonkey** [comment]
你好，目前这块还没提供，后续如果有人力，会尽快支持的，我们记录下~

**Comment by jackiezzq** [comment]
> 你好，目前这块还没提供，后续如果有人力，会尽快支持的，我们记录下~

这个有计划了吗

**Comment by jackiezzq** [comment]
> 你好，目前这块还没提供，后续如果有人力，会尽快支持的，我们记录下~

@WenmuZhou @littletomatodonkey 大佬们，这个有计划了吗？

**Comment by jackiezzq** [comment]
@littletomatodonkey @LDOUBLEV 大佬们啥时候更新这部分啊

**Comment by sheltonsuen** [comment]
不知道有更新提供 kie hub serving 脚本的计划么？
