### ISSUE TITLE
你好，用了下咱们StyleText里面的数据合成工具，出来的效果不太好，有推荐的GAN生成工具吗

### ISSUE THREAD

**Issue by HenrySZP** [PaddlePaddle/PaddleOCR#5695]
我用实际文本数据去生成，生成的图像效果很差.

提取出来的背景上面仍然有很多文字。请问有好用的基于GAN的生成工具吗？

**Comment by MissPenguin** [comment]
您好，StyleText效果我们后续会进行优化，别的GAN工具不太了解呢，可以调研下

**Comment by yjhtc007** [comment]
Zi2Zi

**Comment by HenrySZP** [comment]
> 

@MissPenguin 好的

**Comment by HenrySZP** [comment]
> Zi2Zi

@yjhtc007 感谢，我去研究一下😄
