### ISSUE TITLE
PaddleServing怎样修改默认IP？

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#5698]
您好，如题所述！

我想借鉴PaddleOCR项目对图片文字进行识别，如果使用`PaddleServing`进行部署，调用IP为固定的`127.0.0.1`，请问如何进行修改呢？多谢

**Comment by MissPenguin** [comment]
您好，您在哪台机器上部署的服务，调用的就是那台机器的ip。如果搭建服务和调用的客户端都在同一台机器上（即，从机器A发送请求访问机器A上的服务），可以直接写127.0.0.1表示本台机器的ip（非真实ip），如果从机器B发送请求访问机器A，那么需要写A的真实ip，不能简单的写127.0.0.1了。根据实际情况修改即可。

**Comment by Biaocsu** [comment]
好的，明白了，多谢！
