### ISSUE TITLE
请问paddleocr训练日志里面的参数都代表什么意思？

### ISSUE THREAD

**Issue by gaoshuai0408** [PaddlePaddle/PaddleOCR#5699]
norm_edit_dis， reader_cost， batch_cost， samples， ips 这几个都分别代表什么意思呢

**Comment by MissPenguin** [comment]
> norm_edit_dis， reader_cost， batch_cost， samples， ips 这几个都分别代表什么意思呢

编辑距离，reader耗时，Batch耗时，一个batch的样本数，每秒处理图片数量
