### ISSUE TITLE
English Text Detection

### ISSUE THREAD

**Issue by ApurvaDani** [PaddlePaddle/PaddleOCR#570]
Which detection and recognition models should I use for detecting text which is in English?

**Comment by MissPenguin** [comment]
here are English detection models:
![image](https://user-images.githubusercontent.com/25809855/90607663-1a8f5800-e234-11ea-8b17-482ff8de5af6.png)
and, here are English recognition models:
![image](https://user-images.githubusercontent.com/25809855/90607727-34c93600-e234-11ea-99aa-32286b81322f.png)
 
Models mentioned above are trained on English public datasets.
