### ISSUE TITLE
windows 下用camke部署环境，c++部署

### ISSUE THREAD

**Issue by CUI-XUAN** [PaddlePaddle/PaddleOCR#5703]
目前遇到两个问题
第一从GitHub下载PaddleOCR-release-2.4这个文件，PaddleOCR-release-2.4\deploy\cpp_infer\tools这个路径下没有config文件，不知道为啥？？？？？？？？？，我之前下载都是有的。
第二就是C++配置的时候，严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1107	文件无效或损坏: 无法在 0x358 处读取	ppocr	E:\PaddlefileAI\paddle-inference\paddle\lib\paddle_inference.dll	1	
报这个错误
麻烦给我大神，请求指导一下。

**Comment by andyjpaddle** [comment]
第一：以最新版代码为准，如有使用上的问题，可及时提出。
第二：确保安装了最新版的paddle，建议安装2.2版本的

**Comment by CUI-XUAN** [comment]
> 

就是最新版本，lnk1107那个错误，该如何解决了？我路径文件都是对的

**Comment by ANDROIDTODO** [comment]
> > 
> 
> 就是最新版本，lnk1107那个错误，该如何解决了？我路径文件都是对的

应该是你路径没有设置正确。你最直接的是把无法读取的库全部放到和ppocr.exe同级目录。再调用

**Comment by CUI-XUAN** [comment]
都没有生成exe文件，就报错了

**Comment by andyjpaddle** [comment]
把dll换成lib试试，Lib是编译时用的，dll是运行时用的

**Comment by CUI-XUAN** [comment]
没有用，试过了

**Comment by andyjpaddle** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/cpp_infer/docs/windows_vs2019_build.md  按照这个文档操作的吗

**Comment by CUI-XUAN** [comment]
是的

**Comment by andyjpaddle** [comment]
试试FAQ里面的解答哈~

**Comment by CUI-XUAN** [comment]
没有用

**Comment by WenmuZhou** [comment]
可以试一下dygraph分支的代码，刚刚更新了文档

**Comment by luodaoyi** [comment]
> dygraph

这个分支有啥特殊的？

**Comment by SparKgod1** [comment]
![Image](https://github.com/user-attachments/assets/90e9b50c-b4c8-4c7a-a210-0791c44fa178)
看下是不是把dll加载进去了
@andyjiang1116 cmakefile是否有缺陷，我也遇到这个问题
