### ISSUE TITLE
在读取字典时哪里插入了空白字符

### ISSUE THREAD

**Issue by Caizifen** [PaddlePaddle/PaddleOCR#5704]
在CTC解码阶段，需要读取预先设定好的字典进行解码，请问在代码哪里插入了“blank”这个空白字符呢，我没有看到
![截屏2022-03-13 下午9 49 34](https://user-images.githubusercontent.com/91359613/158062652-e009a148-3497-4a99-8159-df9cc8181ced.png)
最后的character list的第0个位置多了‘blank’
![image](https://user-images.githubusercontent.com/91359613/158062760-a90534aa-318c-435a-84f9-4f1bfd50b3f9.png)

**Comment by andyjpaddle** [comment]
字典中有了blank，解码时会自动将对应索引转换为blank
