### ISSUE TITLE
2.4版本的项目里没有build_post_process

### ISSUE THREAD

**Issue by iiphenoix** [PaddlePaddle/PaddleOCR#5705]
\tools\infer\predict_rec.py的from ppocr.postprocess import build_post_process出错
ppocr.postprocess 里并没有build_post_process文件或者build_post_process函数

**Comment by andyjpaddle** [comment]
在这里 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/postprocess/__init__.py#L33
