### ISSUE TITLE
训练模型和预训练模型有什么差异，可否使用训练模型进行finetune

### ISSUE THREAD

**Issue by JulyYoung** [PaddlePaddle/PaddleOCR#5706]
![image](https://user-images.githubusercontent.com/32296736/158093944-7492542f-9929-4945-bfd9-f708d8f6bbd3.png)

对于没有提供预训练模型的情况，能否直接使用训练模型进行finetune？有什么注意事项？

**Comment by JulyYoung** [comment]
没解决呢。。。

> 我也想问这个问题，请问最后如何解决的呢？

**Comment by rebeccajuan** [comment]
可以啊
