### ISSUE TITLE
文本块的检测

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleOCR#5708]
你好！请问可以直接使用paddleOCR预训练模型实现文本块的检测吗？

**Comment by WenmuZhou** [comment]
可以直接拿来进行检测的，至于你说的文本快，可以发张图看看

**Comment by fengyanWang** [comment]
> 可以直接拿来进行检测的，至于你说的文本快，可以发张图看看

![2](https://user-images.githubusercontent.com/36984088/158512561-a00fc29b-a64c-4554-b42b-c23fda77bc3e.jpg)

**Comment by WenmuZhou** [comment]
这个建议试一下paddleocr里的east算法

**Comment by NLPOR** [comment]
请问paddleocr中的east的模型有开源通用的吗，还是需要自己训练

**Comment by NLPOR** [comment]
> 这个建议试一下paddleocr里的east算法

请问paddleocr中的east的模型有开源通用的吗，还是需要自己训练
