### ISSUE TITLE
容器化部署线程控制问题

### ISSUE THREAD

**Issue by kong62** [PaddlePaddle/PaddleOCR#5712]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
kubernetes/docker

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddlepaddle              2.0.0rc1

应用通过 gunicorn 来启动：
gunicorn run_app:app --bind=0.0.0.0:8080 --timeout=600 --workers=4 --threads=1 --keep-alive=10 -
-access-logfile=/data0/log-data/access.log

问题：
宿主机：104核
容器：16核

宿主机上跑了 6 个容器，进入容器发现，每个 worker 都启动了 104 个线程，这样每个容器 104 * 4 = 416 线程，宿主机上 416 * 6 = 2496 线程，最终宿主机和容器 cpu 都很高，响应慢。

请问如何限制每个 worker 的线程数？或者说如何正确感知到容器的 cgroup cpu，而不是宿主机的 cpu？

我尝试了这些设置，没有效果：
```
        - name: MKL_NUM_THREADS
          value: "1"
        - name: NUMEXPR_NUM_THREADS
          value: "1"
        - name: OMP_NUM_THREADS
          value: "1"
        - name: MKL_DYNAMIC
          value: "FALSE"
        - name: OMP_DYNAMIC
          value: "false"
```

```
vi tools/infer/utility.py
    else:
        config.disable_gpu()
        # cpu 设置的关键
        config.set_cpu_math_library_num_threads(1)
        if args.enable_mkldnn:
            # cache 10 different shapes for mkldnn to avoid memory leak
            # mkldnn 设置的关键
            config.set_mkldnn_cache_capacity(1)
            # mkldnn 开关，推荐关闭掉
            #config.enable_mkldnn()
            args.rec_batch_num = 1
```

**Comment by tink2123** [comment]
首先请更新paddle版本至2.2.1， 另外可以麻烦提供一下预测启动命令吗？我们复现下问题

**Comment by kong62** [comment]
启动参数：
```
gunicorn run_app:app --bind=0.0.0.0:8080 --timeout=600 --worker-class=gevent --keep-alive=10 --workers=5 --access-logfile=/data0/log-data/access.log
```

**Comment by paopjian** [comment]
你代码里怎么调用的paddleocr?我多worker直接崩溃了
