### ISSUE TITLE
WandB integration

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/PaddleOCR#5713]
Hello,

I'd wish to integrate training with WandB system, so I can keep track of the metrics and how they are improving over time.  
Any suggestions on this? Is there a way to "hook" on PaddlePaddle training and report those info?

**Comment by WenmuZhou** [comment]
We have no plan to support wandb at the moment, you can refer to their [documentatio](https://docs.wandb.ai/) for operation

**Comment by morganmcg1** [comment]
@tampe125 there is now a [WandbLogger in release 2.5](https://github.com/PaddlePaddle/PaddleOCR/pull/5957) :D 

@WenmuZhou you can probably close this issue now:)
