### ISSUE TITLE
关于识别模型的知识蒸馏

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleOCR#5717]
用ch_PP-OCRv2_rec_train这个预训练模型，export推理模型在自己的数据集上测试，发现teacher模型的准确率是80%，student模型的准确率有88%。用这个预训练模型训练完成之后，teacher模型在训练集上的准确率有90%，测试集只有75%，student模型在训练集准确率90%，测试集76%。我理解的蒸馏是teacher模型更大或者训练数据更多，但是config文件里teacher模型的结构和student是一样的，效果也不如student模型。请问这个可能是什么原因呢？

**Comment by ziyaxuanyi** [comment]
这个工程的识别模型的蒸馏，是用的互学习，说白了就是两个一模一样的模型进行训练，两个模型除了初始化不一样之外，其他结构什么的都是一模一样，只不过是为了区分分别叫teacher和student，你可以叫他们model1和model2都可以。至于两个模型那个效果好就看你测试是哪个准确率高就是哪个效果好，看你最后测试精度75%和76%其实也差不多。

**Comment by ezekielqu** [comment]
> 这个工程的识别模型的蒸馏，是用的互学习，说白了就是两个一模一样的模型进行训练，两个模型除了初始化不一样之外，其他结构什么的都是一模一样，只不过是为了区分分别叫teacher和student，你可以叫他们model1和model2都可以。至于两个模型那个效果好就看你测试是哪个准确率高就是哪个效果好，看你最后测试精度75%和76%其实也差不多。

了解了，感谢解答

**Comment by fortressRain** [comment]
> > 这个工程的识别模型的蒸馏，是用的互学习，说白了就是两个一模一样的模型进行训练，两个模型除了初始化不一样之外，其他结构什么的都是一模一样，只不过是为了区分分别叫teacher和student，你可以叫他们model1和model2都可以。至于两个模型那个效果好就看你测试是哪个准确率高就是哪个效果好，看你最后测试精度75%和76%其实也差不多。
> 
> 了解了，感谢解答



> 用ch_PP-OCRv2_rec_train这个预训练模型，export推理模型在自己的数据集上测试，发现teacher模型的准确率是80%，student模型的准确率有88%。用这个预训练模型训练完成之后，teacher模型在训练集上的准确率有90%，测试集只有75%，student模型在训练集准确率90%，测试集76%。我理解的蒸馏是teacher模型更大或者训练数据更多，但是config文件里teacher模型的结构和student是一样的，效果也不如student模型。请问这个可能是什么原因呢？

大佬请问能分享一下代码吗 感谢大佬
