### ISSUE TITLE
代码优化 

### ISSUE THREAD

**Issue by jesen8** [PaddlePaddle/PaddleOCR#572]
在 `deploy/cpp_infer/include/config.h`文件下 
48行和50行重复

**Comment by jesen8** [comment]
应将 50行改为
`this->det_db_unclip_ratio = stod(config_map_["det_db_unclip_ratio"]);`

**Comment by littletomatodonkey** [comment]
好的，感谢反馈，已提PR修复：https://github.com/PaddlePaddle/PaddleOCR/pull/579
