### ISSUE TITLE
有关use_mkldnn 配置

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5724]
今天在ch_ppocr_server_v2.0_det_train 基础上进行微调训练，训练以后进行比较，测试了其中一张图
1、未训练前，用原生的ch_ppocr_server_v2.0_det_infer测试，不管use_mkldnn 设置成true还是false，只能识别到2个BOX
2、训练后，用训练好的det模型测试，use_mkldnn=true,识别不到box，use_mkldnn=false,可以识别到6个box。

训练是用gpu训练的，这个是啥情况？和训练使用的gpu 有关系吗？
以下是命令参数
# model load config
use_gpu 0
gpu_id  0
gpu_mem  4000
cpu_math_library_num_threads  10
use_mkldnn 0

# det config
max_side_len  1024
det_db_thresh  0.3
det_db_box_thresh  0.5
det_db_unclip_ratio  1.6
det_model_dir  /home/install/models/det_1

- 系统环境/System Environment：centos7.6 
PaddleOCR：2.1  2.4 CPP_INFER
 PADDLE 2.1
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
CXX compiler version: 5.4.0

-ch_ppocr_mobile_v2.0_cls_infer.tar
ch_ppocr_server_v2.0_det_infer.tar
ch_ppocr_server_v2.0_rec_infer.tar

**Comment by LDOUBLEV** [comment]
更新下代码吧

建议用paddle2.2.2版本；

> use_mkldnn=true,识别不到box，use_mkldnn=false,可以识别到6个box。

这个问题比较奇怪，和GPU训练无关，建议更新paddle版本到最新，2.2.2版本测试正常
