### ISSUE TITLE
SER问题—超过512，直接截断的问题

### ISSUE THREAD

**Issue by hudielv** [PaddlePaddle/PaddleOCR#5725]
ser训练，看源码xfun.py，其中
    def truncate_inputs(self, encoded_inputs, max_seq_len=512):
        for key in encoded_inputs:
            if key == "sample_id":
                continue
            length = min(len(encoded_inputs[key]), max_seq_len)
            encoded_inputs[key] = encoded_inputs[key][:length]
        return encoded_inputs
如果一页的文本经过tokenizer切分后的分词个数，如果大于512，则直接砍掉
请问：这样不是会导致一些文本信息丢失么，那关键信息刚好被砍掉，那怎么办？

**Comment by hudielv** [comment]
1）上面参数是512，那还没有cls和sep，那不应该是
       length = min(len(encoded_inputs[key]), max_seq_len-2)
     对么？
2）max_seq_len默认为512，可以改为比512大么？

**Comment by hudielv** [comment]
def _chunk_ser(self, encoded_inputs):
        encoded_inputs_all = []
        seq_len = len(encoded_inputs['input_ids'])
        chunk_size = 512
        for chunk_id, index in enumerate(range(0, seq_len, chunk_size)):  
            chunk_beg = index
            chunk_end = min(index + chunk_size, seq_len)
            encoded_inputs_example = {}
            for key in encoded_inputs:
                encoded_inputs_example[key] = encoded_inputs[key][chunk_beg:
                                                                  chunk_end]

            encoded_inputs_all.append(encoded_inputs_example)
        return encoded_inputs_all

请问：这里面range(0, seq_len, chunk_size)
          如果刚好把BI分开，怎么办呢？影响大么？

**Comment by littletomatodonkey** [comment]
> ser训练，看源码xfun.py，其中 def truncate_inputs(self, encoded_inputs, max_seq_len=512): for key in encoded_inputs: if key == "sample_id": continue length = min(len(encoded_inputs[key]), max_seq_len) encoded_inputs[key] = encoded_inputs[key][:length] return encoded_inputs 如果一页的文本经过tokenizer切分后的分词个数，如果大于512，则直接砍掉 请问：这样不是会导致一些文本信息丢失么，那关键信息刚好被砍掉，那怎么办？

这个在训练和评估的时候砍掉，在模型预测的时候，不会丢弃文本信息的，可以看看infer_ser.py的逻辑

**Comment by littletomatodonkey** [comment]
> 

这块和预训练是保持对齐的，如果要修改的话，预训练模型加载可能会有问题哈

**Comment by littletomatodonkey** [comment]
> 1）上面参数是512，那还没有cls和sep，那不应该是 length = min(len(encoded_inputs[key]), max_seq_len-2) 对么？ 2）max_seq_len默认为512，可以改为比512大么？

（1）先做完label encode之后再进行的truncate，所以这块没问题
（2）这块和预训练是保持对齐的，如果要修改的话，预训练模型加载可能会有问题哈

**Comment by littletomatodonkey** [comment]
> ```
> def _chunk_ser(self, encoded_inputs):
>     encoded_inputs_all = []
>     seq_len = len(encoded_inputs['input_ids'])
>     chunk_size = 512
>     for chunk_id, index in enumerate(range(0, seq_len, chunk_size)):  
>         chunk_beg = index
>         chunk_end = min(index + chunk_size, seq_len)
>         encoded_inputs_example = {}
>         for key in encoded_inputs:
>             encoded_inputs_example[key] = encoded_inputs[key][chunk_beg:
>                                                               chunk_end]
> 
>         encoded_inputs_all.append(encoded_inputs_example)
>     return encoded_inputs_all
> ```
> 
> 请问：这里面range(0, seq_len, chunk_size) 如果刚好把BI分开，怎么办呢？影响大么？

这块之前没有单独考虑过BI的问题，不过最终精度也可以对齐哈

**Comment by hudielv** [comment]
> 

infer_ser.py看过了，确实不会丢失信息，谢谢。

**Comment by hudielv** [comment]
大佬，再请教几个问题：
1）position_embeddings中max_position_embeddings大小是514，但是text的position最大不就是512么？那后2个是没啥用，这个有问题么？max_position_embeddings为啥不搞成512，出于什么考虑么？
2）max_2d_position_embeddings大小为1024，但是看xfun.py中对文本框坐标的处理，都搞成0到1000
     那max_2d_position_embeddings后24个不是都没有用，这个有问题么？
3）我看从数据预处理到模型中，没有cls和sep这2个字符，为什么不要了？
4）我看训练过程(xfun.py) 和 预测过程(vqa_utils.py) 中对image的处理 不一致，训练过程对图片进行了标准化，但是预测时没有，请问这个可以么，不影响什么，是么？

**Comment by hudielv** [comment]
5）LayoutXLMForTokenClassification中   序列长度是512  + 图像的长度49
     那不是超过512了，transformer的序列长度可以超过512，是么？^_^

**Comment by hudielv** [comment]
6）其中对图片embedding时，利用了resnet_fpn，在配置参数中image_feature_pool_shape为[7,7,256]，请问下
      为什么是[7, 7]，最后导致图像的序列是49，想问下这个出于什么考虑搞成7*7，搞成其它行么？
