### ISSUE TITLE
训练递归超出上限

### ISSUE THREAD

**Issue by 827379852** [PaddlePaddle/PaddleOCR#5726]
训练自己的数聚集一直读取到的数据为None，导致一直进行递归，是不是我的数聚集有问题呢

**Comment by 827379852** [comment]
![9e84b998038a209b6f8a9e5b934056b](https://user-images.githubusercontent.com/79695576/158794694-18c2801a-239e-49fc-bbb3-fcefde5a98b5.png)
![36f566e609e30dbb4a15f6252948d22](https://user-images.githubusercontent.com/79695576/158794707-ac2fc988-ece7-45b5-bf19-a4038a70adc6.png)
![d5d10176c61378519a6bb9a2aaf73d7](https://user-images.githubusercontent.com/79695576/158794720-2a251545-d28a-4e01-a3a4-c2c5d8f32fc2.png)
![83dbe83fdf1aab83dea15d04085c89e](https://user-images.githubusercontent.com/79695576/158794728-6a6a0407-5f81-41aa-a9bb-40f5f7bb1768.png)

**Comment by MissPenguin** [comment]
看样子是数据格式有问题，label中每一行必须是用json.dumps编码。另外，可以再深入调试一下定位具体问题，transform里面还有好几个步骤
