### ISSUE TITLE
ImportError: cannot import name 'blake2s'

### ISSUE THREAD

**Issue by honeytidy** [PaddlePaddle/PaddleOCR#573]
When I run with docker environment and run with command: 
`python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"`
i got the following error:

> Traceback (most recent call last):
>   File "tools/infer/predict_system.py", line 20, in <module>
>     import tools.infer.utility as utility
>   File "/paddle/PaddleOCR/tools/infer/utility.py", line 17, in <module>
>     from ppocr.utils.utility import initial_logger
>   File "/paddle/PaddleOCR/ppocr/utils/utility.py", line 19, in <module>
>     from paddle import fluid
>   File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/__init__.py", line 30, in <module>
>     import paddle.dataset
>   File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 28, in <module>
>     import paddle.dataset.mq2007
>   File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
>     import rarfile
>   File "/usr/local/python3.5.1/lib/python3.5/site-packages/rarfile.py", line 64, in <module>
>     from hashlib import blake2s, sha1, sha256
> ImportError: cannot import name 'blake2s'
>

**Comment by WenmuZhou** [comment]
你的rarfile是什么版本

**Comment by MissPenguin** [comment]
试试这个，应该能解决：
pip3 uninstall rarfile
pip3 install rarfile==3.0
