### ISSUE TITLE
努力的贡献者们：麻烦问2个问题： 1.一行字只识别到了末尾几个字     2. 一行字识别结果中间的都漏掉了 

### ISSUE THREAD

**Issue by 244668226** [PaddlePaddle/PaddleOCR#5734]
模型： 检测识别方向都是用的通用模型
运行predict_system_py
检测结果如下：
![1647585965(1)](https://user-images.githubusercontent.com/59698348/158955417-2a768ade-e1a1-4563-8d58-5102f4b0eed0.jpg)
![1647586866(1)](https://user-images.githubusercontent.com/59698348/158955460-a8d6495c-958e-4346-ba8d-d2fd18439aae.jpg)
![517310A098523181180285](https://user-images.githubusercontent.com/59698348/158955489-66fb7706-3c3b-42cd-93c2-d45f44e87139.jpg)
![1647587018(1)](https://user-images.githubusercontent.com/59698348/158955517-9529a46a-0d8a-4570-b1e8-569e6f573145.jpg)

**Comment by ziyaxuanyi** [comment]
运行predict_rec.py看看，你这种图片不需要在检测了，直接就能用识别模型识别了

**Comment by 244668226** [comment]
> 

好的，我试了，直接检测就好啦，谢谢！ 但是我其他的正常的冰箱能耗贴图片经常出现某行的最后一个字符被忽略，您知道怎么结局嘛

**Comment by yangy996** [comment]
小图识别可以看看这个方案：https://blog.csdn.net/YY007H/article/details/124973777
