### ISSUE TITLE
识别模型出现将某个字符识别为另外一个字符的情况

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#5736]
作者您好，在训练结束后进行识别测试时，发现有小概率会将某个特定字符识别成另外一个特定的字符，比如将下图一中的2198识别为2199，以及将图二的5369识别为5389，以图一为例，识别结果只会有两种情况，识别正确时识别为2198，识别错误时只会被识别为2199而不会是其他的任何错误，比如不会是2169，只可能是2199，我猜测是因为字体的原因，请问这个问题有没有什么好的后处理方法（比如纠正）进行处理，谢谢

![image](https://user-images.githubusercontent.com/46886284/159002048-292182b6-c062-49ae-969a-41e6b0697da7.png)
![image](https://user-images.githubusercontent.com/46886284/159002890-ad3ccacb-3ea1-43e5-aa26-f6ed20f4e724.png)

**Comment by LDOUBLEV** [comment]
建议用PaddleOCR的模型作为预训练模型，在你的场景数据上finetune
