### ISSUE TITLE
PPOCRLabel使用自定义模型进行检测，如何调整模型阈值

### ISSUE THREAD

**Issue by Hadesong** [PaddlePaddle/PaddleOCR#5737]
已经用DBNet训练了一个检测模型。PPOCRLabel使用自定义模型进行检测，如何调整模型阈值？

`        self.ocr = PaddleOCR(det_model_dir='D:/Download/det_mv3_ssld_db_inference/')`

**Comment by andyjpaddle** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/utility.py#L50  可以在这里修改默认阈值哈

**Comment by Hadesong** [comment]
谢谢已解决
