### ISSUE TITLE
python程序如何以数据流形式进行预测而非调用文件

### ISSUE THREAD

**Issue by LFeightyFour** [PaddlePaddle/PaddleOCR#5739]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LFeightyFour** [comment]
我想直接给numpy形式的数据进行预测，而不是读入文件，请问有没有这样的代码？

**Comment by andyjpaddle** [comment]
自己将numpy数据替换成读取后的图片就可以了

**Comment by LFeightyFour** [comment]
> 
意思是使用tempfile的形式把numpy数据存储为临时文件，然后用程序调用吗

**Comment by andyjpaddle** [comment]
嗯嗯

**Comment by LFeightyFour** [comment]
发现目前的版本，PaddleOCR-release-2.4，给的是图像路径，就按文件预测，给的是numpy数据，就按numpy数据预测，直接给np.ndarray形式的数据就行，我这个问题没有意义
