### ISSUE TITLE
PaddleOCR c++ inference

### ISSUE THREAD

**Issue by AriouatI** [PaddlePaddle/PaddleOCR#5742]
你好，
在构建 paddle c++ 推理之后，我尝试运行 paddleOCR，但遇到了多个问题：

PaddleOCR 直接在我的电脑上：
用 cpu 运行它确实有效，但是当我尝试用 GPU 运行它时，我得到了这个：
`malloc(): invalid size (unsorted) Aborted (core dumped)`
我试图找到错误的来源，它似乎来自 paddle/fluid/inference/api/details/zero_copy_tensor.cc，下面的行更具体：
auto *dev_ctx = static_cast<const paddle::platform::CUDADeviceContext *>(pool.Get(gpu_place));
这个调用：pool.Get(gpu_place);是什么使程序崩溃。我检查了 CUDA 的路径，一切似乎都是正确的，我相信这与 paddleOCR 有关，因为这行代码在运行 PaddleDetection 时正确执行。

通过 Docker 进行 PaddleOCR（使用推荐版本的 opencv, cuda 和 gcc）：
ch 模型（可在 github 上下载）工作。

det 的 ch 模型和我们的 rec 模型：工作正常。

仅限我们的模型：问题 --> 尽管 det 模型似乎工作（正确生成带有文本框的良好图像），但在运行 this->predictor_- 时，rec 部分发生崩溃，更准确地说是推理部分的 ocr_rec.cpp >运行（）(（适用于 python）。

关于可能导致此问题的原因或有关寻找什么的任何迹象的任何想法？
谢谢你。

系统信息
GPU: RTX 3080
OS ubuntu 20.04
GIT COMMIT ID: https://github.com/PaddlePaddle/Paddle/commit/a40ea45e50d91f3bb13b3e5121ed28dc3b13c544
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
CUDA version: 11.5
CUDNN version: v8.3
CXX compiler version: 7.5.0

-----------------------------------------------------------------------------

Hello,
After building paddle c++ inference, i tried to run paddleOCR but i came across multiple issues :

PaddleOCR directly on my computer :
running it with cpu does work but when i try to run it with GPU i get this :
`malloc(): invalid size (unsorted) Aborted (core dumped)`
i tried to locate the source of the bug and it seems to come from paddle/fluid/inference/api/details/zero_copy_tensor.cc, the line below to be more specific :
auto *dev_ctx = static_cast<const paddle::platform::CUDADeviceContext *>(pool.Get(gpu_place));
This call : pool.Get(gpu_place); is what makes the program crash. I checked the CUDA's path and everything seems to be correct and i believe it is something related to paddleOCR because this line of code is executed correctly when running PaddleDetection (so i doubt it's a global problem).

PaddleOCR through Docker (with recommanded versions of opencv and gcc):
ch models (available for download on github) works.

ch model for det and our model for rec : works fine.

our models only : problem --> eventhough the  det model seems to work (good image with text boxes is generated correctly) a crash happens in the rec part, more precisely in ocr_rec.cpp in the inference part  when running this->predictor_->Run();

Any idea on what might be causing this or any indications on what to look for ?
Thank you.

System information

GPU: RTX 3080
OS ubuntu 20.04
GIT COMMIT ID: https://github.com/PaddlePaddle/Paddle/commit/a40ea45e50d91f3bb13b3e5121ed28dc3b13c544
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
CUDA version: 11.5
CUDNN version: v8.3
CXX compiler version: 7.5.0

**Comment by WenmuZhou** [comment]
你好，有几个问题需要详细提供一下
1. python的训练和推理是否正常，因为目前paddle还未支持cuda11.5和cudnn8，所以需要确认一下。
2. 你的识别模型有没有改输入shape，如果改了，那么代码里有没有进行修改

**Comment by AriouatI** [comment]
@WenmuZhou 
> 你好，有几个问题需要确认一下
> 
>     1. python的训练和推理是否正常，因为目前paddle还未支持cuda11.5和cudnn8，所以需要确认一下。

在带有 cuda 11.5 的 python 中，一切似乎都是正确的。

所以 cuda 11.2 是 paddle 的最后一个支持版本吗？它会更新还是会停在这里？


>     2. 你的识别模型有没有改输入shape，如果改了，那么代码里有没有进行修改

不。
为了简化，我们摆脱了我们的 rec 模型并尝试使用 for det：来自 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/inference_en.md#SRN- 的 DB TEXT DETECTION MODEL INFERENCE BASED_RECOGNITION 和 rec 模型：从 paddle 下载的 ch_ppocr_mobile_v2.0_rec_infer 它仍然给出错误。

`malloc(): memory corruption
Aborted (core dumped)
`
在 ocr_rec.cpp 中的 `this->predictor_->Run();

谢谢

**Comment by WenmuZhou** [comment]
cuda的支持后续会更新的
