### ISSUE TITLE
not find model file path ./inference/ch_PP-OCRv2_det_infer/inference.pdmodel

### ISSUE THREAD

**Issue by jmh741** [PaddlePaddle/PaddleOCR#5745]
使用代码中提供的dockerfile启动服务，默认的模型启动时会报错not find model file path，实际上在该文件已经存在
![image](https://user-images.githubusercontent.com/46946322/159517113-27d98a31-5209-4303-9176-cd30d461da3f.png)

![image](https://user-images.githubusercontent.com/46946322/159517103-1376d8bf-19d7-4e5f-8e8a-7ed2723d7b90.png)

**Comment by littletomatodonkey** [comment]
建议改成绝对路径试下，确保路径无误哈

**Comment by jmh741** [comment]
重新下载了模型文件，然后改成绝对路径后可以启动了
