### ISSUE TITLE
检测模型在推理阶段的图片大小

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5747]
检测模型在推理阶段为什么图片的长和宽都要Resize到32的倍数

**Comment by MissPenguin** [comment]
为了避免fpn操作时无法整除导致出现1个像素的偏差，从而后面concat报错

**Comment by GivanTsai** [comment]
> 为了避免fpn操作时无法整除导致出现1个像素的偏差，从而后面concat报错

训练的时候也需要吗，还是只有推理阶段需要

**Comment by MissPenguin** [comment]
> > 为了避免fpn操作时无法整除导致出现1个像素的偏差，从而后面concat报错
> 
> 训练的时候也需要吗，还是只有推理阶段需要

训练在数据增广时会crop和resize（一般是640或960），所以不需要手动设定图像尺寸
