### ISSUE TITLE
SAST论文里的对比实验SAST MS是指什么

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5749]
Method Recall Precision Hmean
SegLink [30] 23.80 30.30 26.70
DeconvNet [1] 33.00 40.00 36.00
EAST [47] 36.20 50.00 42.00
TextSnake [23] 74.50 82.70 78.40
TextField [38] 79.90 81.20 80.60
SAST 76.86 83.77 80.17
SAST MS 75.49 85.57 80.21

**Comment by MissPenguin** [comment]
MS指代Muti Scale，即多尺度测试

**Comment by qqqqq127** [comment]
> MS指代Muti Scale，即多尺度测试

十分感谢
