### ISSUE TITLE
SRN训练精度问题

### ISSUE THREAD

**Issue by chenjun2hao** [PaddlePaddle/PaddleOCR#575]
SRN已经跟踪很久了，感谢开源。这里有个问题。
我有复现过SRN,采用pytorch的框架，按照论文的数据集。在IIIT, SVT, IC03, IC13, IC15, SVTP, CUTE数据集上进行评估，大概只有80%. 我看咋们的项目采用了数据扰动方法方法进行增强。那没有采用这种方式之前精度是多少呢？这部分的提高是不是来自于数据集的扩充？

**Comment by MissPenguin** [comment]
您好，SRN上目前没有做数据扰动方面的消融实验（后续会考虑补齐），但是80%肯定是偏低了的，这里可以提供一些数据供对比参考：
1. 在crnn上，使用同样的数据扰动大约能有3%的提升；
2. srn重点是gsrm加入的相对收益，尤其是ic15能提升3~4个点，数据扰动如果没法同步的话，可以关注下自己实现的模块是否有明确收益。

**Comment by chenjun2hao** [comment]
感谢。

**Comment by zhunge** [comment]
> 您好，SRN上目前没有做数据扰动方面的消融实验（后续会考虑补齐），但是80%肯定是偏低了的，这里可以提供一些数据供对比参考：
> 
> 1. 在crnn上，使用同样的数据扰动大约能有3%的提升；
> 2. srn重点是gsrm加入的相对收益，尤其是ic15能提升3~4个点，数据扰动如果没法同步的话，可以关注下自己实现的模块是否有明确收益。

你好，请问有数据扰动的代码吗？
