### ISSUE TITLE
文字识别结果乱序

### ISSUE THREAD

**Issue by zhaoweihan2017** [PaddlePaddle/PaddleOCR#5751]
使用PaddleOCR官方提供的检测模型+识别模型处理图片中包含部分文字扭曲图片时，无法按顺序输出词条，请问这种情况一般如何解决？

**Comment by MissPenguin** [comment]
识别结果是按照检测框的坐标顺序排序后输出的，排序逻辑在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/88092de331ab0d3c15748f089ae1b4bd90cfc848/tools/infer/predict_system.py#L103
可以根据需求自己进行改写
