### ISSUE TITLE
文字识别模型onnx转换失败

### ISSUE THREAD

**Issue by jaysonteng** [PaddlePaddle/PaddleOCR#5754]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
文字检测模型可以转换成功，文字识别模型转换失败。

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：2.0.2  PaddleOCR：2.1.0 问题相关组件/Related components：
- 运行指令/Command Code：paddle2onnx --model_dir ./inference/ch_PP-OCRv2_rec_slim_quant_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/rec_onnx/model.onnx --opset_version 10 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True

- 完整报错/Complete Error Message：
/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
Traceback (most recent call last):
  File "/home/hmcs/miniconda3/envs/pdocr/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle2onnx/command.py", line 195, in main
    input_shape_dict=input_shape_dict)
  File "/home/hmcs/miniconda3/envs/pdocr/lib/python3.7/site-packages/paddle2onnx/command.py", line 149, in program2onnx
    program.blocks[0].ops[i].desc.infer_shape(program.blocks[0].desc)
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected attrs_.count(name) != 0, but received attrs_.count(name):0 == 0:0.] (at /paddle/paddle/fluid/framework/attribute.h:213)
  [operator < matmul > error]

**Comment by yeliang2258** [comment]
hello, please pull this pr to convert: https://github.com/PaddlePaddle/Paddle2ONNX/pull/399

**Comment by yeliang2258** [comment]
请问你转换成功了吗？精度怎么样？另外请问你转换之后使用什么推理引擎进行推理呢？

**Comment by jaysonteng** [comment]
> 请问你转换成功了吗？精度怎么样？另外请问你转换之后使用什么推理引擎进行推理呢？

你好，感谢解答。
按照您给的转换命令（去掉了参数 --input_shape_dict），转换成功了，但是精度下降了很多。

使用如下命令进行推理
```
python3.7 tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
--det_model_dir=./inference/det_onnx/model.onnx  \
--rec_model_dir=./inference/rec_onnx/model.onnx  \
--cls_model_dir=./inference/cls_onnx/model.onnx  \
--image_dir=./deploy/lite/imgs/lite_demo.png
```

检测到的结果如下图所示：
![lite_demo](https://user-images.githubusercontent.com/50574730/160334997-77c7c660-3378-41b2-8131-c0e92811d29a.png)

可以看到精度下降了很多。
请问有什么方法能够得到下面页面中，案例所示那样的精度呢？
`https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/paddle2onnx`

**Comment by yeliang2258** [comment]
你选择的是一个量化模型，可以选择非量化模型进行转换和部署

**Comment by jaysonteng** [comment]
意思是，页面展示的执行效果，使用的是非量化模型对吗？
![image](https://user-images.githubusercontent.com/50574730/160337183-231dceac-825d-4de0-be2e-726182e13d48.png)

**Comment by jaysonteng** [comment]
> 你选择的是一个量化模型，是一定要量化模型吗？可以选择非量化模型进行转换和部署。 你给的那个链接中详细写了用的是那个模型

因为我是按照给出的步骤，一步步来的。
我看步骤里面，下载的也是量化模型。
最终展示的结果，使用的是非量化模型得出的吗？
还是说，由于转换命令中，由于没有给定 `--input_shape_dict` 参数，而导致精度下降的？

**Comment by yeliang2258** [comment]
Paddle2ONNX文档中给的模型是，应该都不是量化模型：
wget -nc  -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar

wget -nc  -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar

wget -nc  -P ./inference https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar

**Comment by jaysonteng** [comment]
> Paddle2ONNX文档中给的模型如下，应该都不是量化模型： wget -nc -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar
> 
> wget -nc -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar
> 
> wget -nc -P ./inference https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar

我使用的也是这些模型，我是跟着步骤来的。
唯一的区别就是转换时候没有用`--input_shape_dict` 这个参数。
如果用了这个参数，转换模型时候，就会出现最开始提到错误。

**Comment by yeliang2258** [comment]
--input_shape_dict 这个参数只是指定了输入的shape而已，应该是不会影响到模型精度，我看你转换的模型名称是：ch_PP-OCRv2_rec_slim_quant_infer，这个应该是一个量化模型，因为写Paddle2ONNX的教程之前是还不支持量化模型导出的，所以建议再查查模型是不是下错模型了？

**Comment by jaysonteng** [comment]
> --input_shape_dict 这个参数只是指定了输入的shape而已，应该是不会影响到模型精度，我看你转换的模型名称是：ch_PP-OCRv2_rec_slim_quant_infer，这个应该是一个PaddleSlim的量化模型，因为写Paddle2ONNX的教程之前是还不支持量化模型导出的，所以建议再查查模型是不是下错模型了？

嗯嗯，之前是因为跟着说明，然后出错了。
才更换了模型来尝试，发现也报一样的错误。

现在使用的就是下面这3个模型，推理结果和页面展示不一致,，就是刚我图片中展示的那个结果。
```
wget -nc -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar

wget -nc -P ./inference https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar

wget -nc -P ./inference https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar
```

为了确认，我刚也重新试了一下，还是一样的（如下图），只识别出了大概 1/2 的内容。
![lite_demo](https://user-images.githubusercontent.com/50574730/160343968-d4032888-6be3-4dd1-b0ea-2cc7e8421aa7.png)

**Comment by jaysonteng** [comment]
对了，paddlepaddle我已更新到了最新版 2.2.2

**Comment by tink2123** [comment]
请问您直接使用Paddle的 inference model 预测可以得到正确结果嘛？ 执行命令：
```
python3.7 tools/infer/predict_system.py --use_gpu=False \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer \
--rec_model_dir=./inference/ch_PP-OCRv2_rec_infer \
--det_model_dir=./inference/ch_PP-OCRv2_det_infer \
--image_dir=./deploy/lite/imgs/lite_demo.png
```

**Comment by jaysonteng** [comment]
> 请问您直接使用Paddle的 inference model 预测可以得到正确结果嘛？ 执行命令：
> 
> ```
> python3.7 tools/infer/predict_system.py --use_gpu=False \
> --cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer \
> --rec_model_dir=./inference/ch_PP-OCRv2_rec_infer \
> --det_model_dir=./inference/ch_PP-OCRv2_det_infer \
> --image_dir=./deploy/lite/imgs/lite_demo.png
> ```

不能，使用这个模型只能识别一部分文字。
使用[模型列表](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md)中的 `ch_ppocr_server_v2.0_det` 和 `ch_ppocr_server_v2.0_rec` 转换为onnx后，能识别大部分文字，但是还是会有部分错误的识别。

只有下面的命令，使用给定的Paddle Inference 预测，识别结果才和给定的示例结果一样：
```
python3.7 tools/infer/predict_system.py --use_gpu=False \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer \
--rec_model_dir=./inference/ch_PP-OCRv2_rec_infer \
--det_model_dir=./inference/ch_PP-OCRv2_det_infer \
--image_dir=./deploy/lite/imgs/lite_demo.png
```

**Comment by apexg** [comment]
用paddlepaddle-gpu                  2.2.2   转就可以成功了!

**Comment by jaysonteng** [comment]
> 用paddlepaddle-gpu 2.2.2 转就可以成功了! paddle2onnx --model_dir /usr/local/notebook_dir/paddle_model/ch_ppocr_server_v2.0_rec_infer \
> 
> > --model_filename inference.pdmodel 
> > --params_filename inference.pdiparams 
> > --save_file ./inference/rec_onnx/model.onnx 
> > --opset_version 11 
> > --input_shape_dict="{'x':[6,3,32,320]}" 
> > --enable_onnx_checker True
> > /root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
> > Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> > int(TensorProto.STRING): np.dtype(np.object)
> > /root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> > Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> > np.bool: core.VarDesc.VarType.BOOL,
> > /root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> > Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> > core.VarDesc.VarType.FP32: np.float,
> > /root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> > Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> > core.VarDesc.VarType.BOOL: np.bool
> > 2022-04-02 17:44:37 [WARNING]   The model is saved by paddlepaddle v0.0.0, but now your paddlepaddle is version of 2.2.2, this difference may cause error, it is recommend you reinstall a same version of paddlepaddle for this model
> > /root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/onnx/helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
> > is_iterable = isinstance(value, collections.Iterable)
> > 2022-04-02 17:44:45 [INFO]      ONNX model generated is valid.
> > 2022-04-02 17:44:45 [INFO]      ONNX model saved in ./inference/rec_onnx/model.onnx

非常感谢，果真使用GPU版本就好了，之前确实使用CPU版本的paddle。
