### ISSUE TITLE
使用PaddleOCR快速开始教程中的python脚本运行出错

### ISSUE THREAD

**Issue by 123xian123** [PaddlePaddle/PaddleOCR#5759]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：window11--3080--cuda10.2
- 版本号/Version：Paddle：2.2.2  PaddleOCR：2.4 问题相关组件/Related components：
- 运行指令/Command Code：
from paddleocr import PaddleOCR, draw_ocr
# #Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# #例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=False, lang="ch", use_gpu=True)  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

- 完整报错/Complete Error Message：
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\lenovo/.paddleocr/2.4\\ocr\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\lenovo/.paddleocr/2.4\\ocr\\det\\ch\\ch_PP-OCRv2_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], label_map_path='./vqa/labels/labels_ser.txt', lang='ch', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_seq_length=512, max_text_length=25, min_subgraph_size=15, mode='structure', model_name_or_path=None, ocr_version='PP-OCRv2', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='C:\\Users\\lenovo\\.conda\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\lenovo/.paddleocr/2.4\\ocr\\rec\\ch\\ch_PP-OCRv2_rec_infer', save_crop_res=False, save_log_path='./log_output/', show_log=True, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2022/03/23 15:27:31] root WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/03/23 15:43:42] root DEBUG: dt_boxes num : 0, elapse : 970.4596199989319
[2022/03/23 15:43:42] root DEBUG: rec_res num  : 0, elapse : 0.0

测试的图像为教程中纯甄营养护发素那张图像，其他图像也是同样的结果，并且程序运行特别慢，大概十几分钟才会出结果。请问是什么原因呢？

**Comment by LDOUBLEV** [comment]
检查你图像的路径是不是对的，建议换成win格式的绝对路径；
img_path = './imgs/11.jpg' 

use_gpu=False 试下？

**Comment by 123xian123** [comment]
use_gpu=False，确实可以了，谢谢
之前确实一直cuda报错：RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
找了很多方法才解决，现在看来并没有解决

**Comment by 123xian123** [comment]
我重新安装了cuda10.2、paddle-gpu2.2.2、paddleocr2.5.03，python3.7。但是在运行快速开始的脚本时仍然是上面描述的问题，在use_gpu=False时可以使用。在使用gpu运算时出现了哪些问题？绝望。。。
