### ISSUE TITLE
LayoutXLM license问题

### ISSUE THREAD

**Issue by gonkillu** [PaddlePaddle/PaddleOCR#5762]
你好！

请问PPOCR的license是Apache2.0，但是LayoutXLM和LayoutV2都是[Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)，这个license是非商用的，而且它的衍生必须继承这个license，这不是和Apache2.0冲突吗？

LayoutXLM
https://github.com/microsoft/unilm/tree/master/layoutxlm

**Comment by WenmuZhou** [comment]
他们的licence是MIT License哈，不是你说的这个

**Comment by tearsofwein** [comment]
我也有同样的疑问。求解答
