### ISSUE TITLE
PGNet：用中文数据集训练了100个epoch，loss没有看到明显下降。

### ISSUE THREAD

**Issue by fangfangzk** [PaddlePaddle/PaddleOCR#5764]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by fangfangzk** [comment]
什么是partvgg

**Comment by fangfangzk** [comment]
数据集是lsvt，3w张
![image](https://user-images.githubusercontent.com/75557988/159888479-ea067b85-40a0-423f-9f1e-66dea67d1ce6.png)
![image](https://user-images.githubusercontent.com/75557988/159888546-84c4ba42-0398-4599-b149-fa53544f78aa.png)
![image](https://user-images.githubusercontent.com/75557988/159888569-53d1e97c-b989-488d-bf4d-878d008d657b.png)

**Comment by LDOUBLEV** [comment]
尝试降低学习率，或更换学习率decay策略；
可视化分析badcase，观察主要是检测的问题还是识别分支的问题
