### ISSUE TITLE
运行ppocrlabel时出现错误

### ISSUE THREAD

**Issue by 02825cm** [PaddlePaddle/PaddleOCR#5766]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
resultPaths are ['/strings', '/strings-zh', '/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/PPOCRLabel/resources/strings/strings-zh-CN.properties']
Namespace(cls=True, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/chen/.paddleocr/2.1/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/chen/.paddleocr/2.1/det/ch', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/home/chen/.paddleocr/2.1/rec/ch', show_log=False, use_angle_cls=True, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
Traceback (most recent call last):
  File "/home/chen/anaconda3/envs/paddle_ocr/bin/PPOCRLabel", line 8, in <module>
    sys.exit(main())
  File "/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 2151, in main
    app, _win = get_main_app(sys.argv)
  File "/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 2144, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file)
  File "/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 117, in __init__
    self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=gpu, lang=lang, show_log=False)
  File "/home/chen/anaconda3/envs/paddle_ocr/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 345, in __init__
    super().__init__(postprocess_params)
  File "../tools/infer/predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "../tools/infer/predict_det.py", line 41, in __init__
    self.use_onnx = args.use_onnx
AttributeError: 'Namespace' object has no attribute 'use_onnx'

**Comment by LDOUBLEV** [comment]
请更新代码后重新编译ppocrlabel

**Comment by LDOUBLEV** [comment]
请重新安装paddleocr到2.4版本
