### ISSUE TITLE
中文繁体模型字典如何下载

### ISSUE THREAD

**Issue by sue2415535899** [PaddlePaddle/PaddleOCR#5767]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问是否提供中文繁体模型的字典？为何没有下载链接

**Comment by yjhtc007** [comment]
在./ppocr/utils/dict/chinese_cht_dict.txt 路径下

**Comment by sue2415535899** [comment]
> 在./ppocr/utils/dict/chinese_cht_dict.txt 路径下
不好意思 我想问的是中文繁体的yml文件如何下载

**Comment by yangtle** [comment]
> 

可以在繁体预训练模型文件夹中的train.log找一下
