### ISSUE TITLE
在识别中，单个文字的位置是否有办法回溯

### ISSUE THREAD

**Issue by Henryplay** [PaddlePaddle/PaddleOCR#5769]
问个问题哈，当然如果涉及到商业机密就帮忙close这个issue。
Q：请问有没有好的方法可以根据网络的输出回溯到当前结果所对应在图像中的位置呢？比如以CRNN结构为例，LSTM的输出经过经过softmax后某一个字得分很低想要回溯到这个字在图像中的位置。

**Comment by yjhtc007** [comment]
这个用CRNN貌似不太好做哈

**Comment by Henryplay** [comment]
@yjhtc007 用哪种网络比较好做呢，有实现的可能吗

**Comment by yjhtc007** [comment]
> @yjhtc007 用哪种网络比较好做呢，有实现的可能吗

多字识别我没想到有什么好的方法，因为不要确定字符串在图片中的起始位置以及每个字符的大小是否差不多。或者考虑一下用单字检测加单字识别的方法？

**Comment by Henryplay** [comment]
@yjhtc007 嗯嗯晓得了，谢谢哈
