### ISSUE TITLE
ICDAR2015测试集评估通用中英文模型acc过低

### ISSUE THREAD

**Issue by lindk-cmd** [PaddlePaddle/PaddleOCR#5770]
![image](https://user-images.githubusercontent.com/52515481/159896471-f417bfa0-3535-402f-ab09-a3da7d9e5fb0.png)
使用ICDAR2015测试集来评估开源的通用中英文模型(模型为图中红色部分)时，acc只有53.1%，想问一下这正常吗？

**Comment by LDOUBLEV** [comment]
正常；ppocr_serverv2.0_rec模型的训练数据绝大部分是中英文，以及长文本，在数据分布上和ic15差距较大；更多的是针对通用场景；
