### ISSUE TITLE
文本检测没有输出检测的图片，而predicted.txt文件中只显示[ ]

### ISSUE THREAD

**Issue by Jackzhangfei** [PaddlePaddle/PaddleOCR#5771]
在进行文本检测时，图片没有检测框，predited.txt文件中只有四个坐标点
在进行更换模型后，没有输出图片，predicte.txt文件中只有 [ ]

**Comment by LDOUBLEV** [comment]
请提供预测的命令和使用的模型？

我这边测试官方模型预测是正常的

**Comment by Jackzhangfei** [comment]
已解决，谢谢
