### ISSUE TITLE
ppocr支持中文表格训练吗？

### ISSUE THREAD

**Issue by cgq0816** [PaddlePaddle/PaddleOCR#5775]
您好，想问一下ppocr如何支持中文表格训练，看了官网提供的configs/table/table_mv3.yml，
![image](https://user-images.githubusercontent.com/42534237/160044929-b5750f5a-2c69-4fc0-970d-a75ed94eff7e.png)
仅支持英文表格训练，有没有提供一下参考案例或者方法呢

**Comment by yjhtc007** [comment]
目前貌似还不支持

**Comment by andyjpaddle** [comment]
中文的目前还没提供模型，如果有自己的数据集，可以仿照英文案例，更换字典等参数进行训练

**Comment by WenmuZhou** [comment]
表格模型对数据集语言不敏感哈，照着文档标注好就能训练
