### ISSUE TITLE
识别模型训练问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#5776]
使用ch_PP-OCRv2_rec_distillation.yml蒸馏训练识别模型，保持默认配置，之前数据量2500万+没有问题。

后面数据量增加到3500万+训练，开始训练没有异常，大约在100个iter以后，训练速度会变得巨慢，reader_cost和batch_cost花费数秒甚至数十秒秒以上，中间会有一两次时间正常，反复交替，导致最终训练速度很慢。

训练是在docker环境内，六卡3090训练，显存充足，训练配置保持默认。

请问是什么原因，有什么办法解决吗？

**Comment by andyjpaddle** [comment]
看一下是否有其他程序占用CPU或者GPU，一般数据量增加不会导致这样的问题

**Comment by GivanTsai** [comment]
> 

请问你这么大的数据量都是用合成数据吗？

**Comment by andyjpaddle** [comment]
启动训练，会显示训练时长
