### ISSUE TITLE
ppocr 中英文识别模型的英文识别问题

### ISSUE THREAD

**Issue by holasyb** [PaddlePaddle/PaddleOCR#5777]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu20.04
- 版本号/Version：Paddle：  2.0.1
- PaddleOCR： 2.4
- 问题相关组件/Related components：ppocr v2 中英文识别模型
- 运行指令/Command Code：python tools/infer/predict_rec.py --image_dir="lower.jpg" --rec_model_dir="./inference/ch_PP-OCRv2_rec_infer (1)/ch_PP-OCRv2_rec_infer" --rec_image_shape="3, 32, 100" --rec_char_type="ch"  --use_gpu False
![lower](https://user-images.githubusercontent.com/45037872/160047025-ec13cba4-7419-4aeb-9c87-12d4e7fb5cde.jpg)

- 完整报错/Complete Error Message：
识别错误：('WWW.ALAMY.COM', 0.7797214)
应当全是小写才对

补充：注意到中英文识别模型对空格比较不敏感，不知未来是否有提升计划？
![women](https://user-images.githubusercontent.com/45037872/160047098-fac180a6-7697-41a8-951e-5bcfee8aeaa9.jpg)
识别结果：('WOMENSTRONGWORLDSTRONG', 0.9405642)
丢失所有空格

**Comment by andyjpaddle** [comment]
改成 `--rec_image_shape="3, 32, 320"`试试？

**Comment by holasyb** [comment]
这样改对大小写是有用的，但是空格问题仍然存在诶

**Comment by andyjpaddle** [comment]
确认一下`use_space_char`参数是否为True

**Comment by tink2123** [comment]
中英文识别模型的空格问题会在下个版本改善，如果只关注英文场景的话，可以使用单独的英文数字模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md#%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

**Comment by holasyb** [comment]
> 确认一下`use_space_char`参数是否为True

已确认该参数设置为True，将rec_image_shape改遍之后，能识别到一个空格，其余的未识别到，也注意到其他场景中也存在空格缺失的问题。

**Comment by holasyb** [comment]
> 中英文识别模型的空格问题会在下个版本改善，如果只关注英文场景的话，可以使用单独的英文数字模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md#%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

场景是包含了中英文的。感谢回复，将继续关注paddleocr，感谢开发者们的贡献
