### ISSUE TITLE
输入图片路径参数报错：predict_system.py: error: unrecognized arguments: --image_dir=./test/1.jpg

### ISSUE THREAD

**Issue by haoshuiwuxiang** [PaddlePaddle/PaddleOCR#5779]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/infer/predict_system.py  --image_dir='./test/1.jpg'
- 完整报错/Complete Error Message：predict_system.py: error: unrecognized arguments: image_dir=./test/1.jpg
试了好久，说参数格式错误，就想不明白为啥报错，格式没有问题哇！！！
![image](https://user-images.githubusercontent.com/40374436/160048902-f6d1f04c-cc5b-438e-b02b-4b09a38fa3b6.png)

**Comment by andyjpaddle** [comment]
图像路径用双引号试试哈？`""`
