### ISSUE TITLE
基于SDMGR的KIE任务，paddleOCR源码没有对key-value关系进行建模

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#5782]
基于SDMGR的KIE任务，paddleOCR提供的源码和mmocr基本保持一致，且两者模型输出均只有文本块类别信息，例如给每个文本块计算出
1 Store_name_value
2 Store_name_key
3 Store_addr_value	
。。。
等类别信息，模型结束。
但是并没有对key-value关系进行建模，value 属于哪个key，请问这个后续有更新计划么？
例如以下图像有25个文本块，理论上用25x25x2是可以表示节点（文本块）间相互k-v隶属关系, 这个关系有助于多值提取
![image](https://user-images.githubusercontent.com/29808550/160079569-8e5251c6-4cdf-4ab9-8048-18895af943d3.png)
paddleocr没把这个建模考虑进去，请问是出于什么原因？
谢谢！

**Comment by zhangyingying520** [comment]
> 基于SDMGR的KIE任务，paddleOCR提供的源码和mmocr基本保持一致，且两者模型输出均只有文本块类别信息，例如给每个文本块计算出 1 Store_name_value 2 Store_name_key 3 Store_addr_value 。。。 等类别信息，模型结束。 但是并没有对key-value关系进行建模，value 属于哪个key，请问这个后续有更新计划么？ 例如以下图像有25个文本块，理论上用25x25x2是可以表示节点（文本块）间相互k-v隶属关系 ![image](https://user-images.githubusercontent.com/29808550/160079569-8e5251c6-4cdf-4ab9-8048-18895af943d3.png) paddleocr没把这个建模考虑进去，请问是出于什么原因？ 谢谢！

也有同样需求

**Comment by BeyondYourself** [comment]
这种一般是数据标注的分类决定的

**Comment by ymzx** [comment]
> 这种一般是数据标注的分类决定的

嗯是的，但是这个模型也可以对kv建模得出kv从属关系，这样能解决同一个key多次出现或者同一个key多个value的问题。

**Comment by BeyondYourself** [comment]
> > 这种一般是数据标注的分类决定的
> 
> 嗯是的，但是这个模型也可以对kv建模得出kv从属关系，这样能解决同一个key多次出现或者同一个key多个value的问题。

个人看法：如果这样，模型泛化性就太差了。扩展性较差，建议后处理加一些逻辑处理
