### ISSUE TITLE
Incorrect accuracy when text contains space characters

### ISSUE THREAD

**Issue by QuickLearner171998** [PaddlePaddle/PaddleOCR#5783]
I am getting incorrect accuracy for text recognition when space char is present in the text.

I got the reason. Its because of these lines  - https://github.com/PaddlePaddle/PaddleOCR/blob/44ea70d5fcf0fc76d7ef3a2579f751e64acc5070/ppocr/metrics/rec_metric.py#L37

But I don't understand why we replace space with empty string ?

**Comment by andyjpaddle** [comment]
Usually the space is not so import for common model in the field of research，also special character in English is also removed during eval process. If the space is import to you, you can remove this line `target = target.replace(" ", "") ` to choose the best model.
