### ISSUE TITLE
Style-Text 可以换 字体 Font文件不

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#5786]
比如特殊的自定义字体 db_standard.ttf
增加上去 
"E:\PaddleOCR\StyleText\fonts\db_standard.ttf"

python tools/synth_image.py -c configs/config.yml --style_image examples/style_images/2.jpg --text_corpus PaddleOCR --language db

能否这样来 自定义字体呢

还是需要怎么样操作
才可以自定义输出 自己想要的字体

**Comment by weisy11** [comment]
这个默认的字体不是用来控制输出的，只是作为一个最基本的输入。
自定义输出想要的字体可以修改style_image的字体。

**Comment by sheltonsuen** [comment]
> style_image

具体是哪一个配置咧？多谢
