### ISSUE TITLE
运行paddleocr的demo不成功，怎么解决呢？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleOCR#5788]
- 系统环境/System Environment：windows，cuda 10.2 cudnn7.3
- 版本号/Version：Paddle：paddlepaddle-gpu         2.2.2
  PaddleOCR：paddleocr                2.4.0.3

- 运行指令/Command Code：
运行paddle安装测试指令没问题：
![image](https://user-images.githubusercontent.com/40531744/160222760-3ab72837-49ff-4ac8-9528-5a5fd1aab5c2.png)

使用测试demo报错，测试代码如下：
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=False, lang="ch")  # need to run only once to download and load model into memory
img_path = 'ppocr_img/imgs/11.jpg'
result = ocr.ocr(img_path, cls=False)
for line in result:
    print(line)

from PIL import Image

image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

- 完整报错/Complete Error Message：
-
[2022/03/26 11:14:26] root WARNING: version PP-OCRv2 not support cls models, auto switch to version PP-OCR
Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\Administrator/.paddleocr/2.4\\ocr\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\Administrator/.paddleocr/2.4\\ocr\\det\\ch\\ch_PP-OCRv2_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='box', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], label_map_path='./vqa/labels/labels_ser.txt', lang='ch', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_seq_length=512, max_text_length=25, min_subgraph_size=15, mode='structure', model_name_or_path=None, ocr_version='PP-OCRv2', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='D:\\project2021\\PaddleOCR-release-2.4\\ppocr\\utils\\ppocr_keys_v1.txt', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\Administrator/.paddleocr/2.4\\ocr\\rec\\ch\\ch_PP-OCRv2_rec_infer', save_crop_res=False, save_log_path='./log_output/', show_log=True, structure_version='STRUCTURE', table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)

Process finished with exit code -1073741819 (0xC0000005)

![image](https://user-images.githubusercontent.com/40531744/160222706-0e94c272-36a7-474c-9a6d-f24a013e9c09.png)

另外在终端运行命令，使用cpu可以运行，但是使用gpu却没反应
![image](https://user-images.githubusercontent.com/40531744/160222858-23ec82a6-ef29-46eb-9e90-938604ff09d0.png)

![image](https://user-images.githubusercontent.com/40531744/160222871-31fbe572-6c00-4add-b746-fe72a3eccae4.png)

**Comment by tink2123** [comment]
gpu 和 cpu 都进入了预测阶段，gpu上也打印出了图片信息，应该是在等待预测。gpu上多等一会呢，另外在预测的时候观察一下是否有显存占用。

**Comment by hhhhhhogan** [comment]
继续等仍然不行。会报错。另外gpu上没有显存占用

![9d9db2a4128289ddd2c557b211f1f11](https://user-images.githubusercontent.com/40531744/161355663-6e040527-8f75-4e7b-b801-efb286c102ff.png)

**Comment by hhhhhhogan** [comment]
应该是cudnn版本不适应，原先的cudnn是7.3，新的cudnn版本是7.5还是7.6来着，然后重新安装paddle并更换虚拟环境里相应的cudnn的dll即可正常使用gpu推理。

**Comment by kankanjiuzou123** [comment]
我也运行不成功，paddleocr配置个环境都这么难搞吗。。。
