### ISSUE TITLE
文字识别 rec_img_aug 增强 有没教程，怎么使用

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#5790]
文字识别 rec_img_aug 增强 有没教程，怎么使用

**Comment by tink2123** [comment]
默认按50%的概率使用，具体的较优组合实现在代码里，可以阅读源码：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/data/imaug/rec_img_aug.py

**Comment by tink2123** [comment]
是要在训练过程中增强吗？还是使用离线增强。

如果是训练过程中使用数据增强，可以直接在配置文件中添加 RecAug 字段，参考：
https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml#L74

如果希望离线处理数据，可以把源码复制下来，写一个自定义读图的代码，加载RecAug 类就好：https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/ppocr/data/imaug/rec_img_aug.py#L23

**Comment by song4875343** [comment]
recaug字段应该用True，Flase还是应该什么。另外如果是离线处理，处理完图像的尺寸会变小，经常会出现字符的一部上边或者下边的一部分被切掉的问题。是程序的bug还是需要怎么调整

**Comment by song4875343** [comment]
![word_5](https://user-images.githubusercontent.com/104266178/164911328-801330bf-43ca-4396-b54c-fe2d944b00ac.png)
![word_5](https://user-images.githubusercontent.com/104266178/164911341-0f7aef0c-255f-41e0-985d-9a5522315558.png)

**Comment by monkeycc** [comment]
希望离线处理数据
能否给个简单的演示代码
@tink2123

**Comment by song4875343** [comment]
# 利用paddleocr里面的模块调整图片的规则性
import sys
sys.path.append('D:/ProgramData/PaddleOCR-release-2.4/')
import paddleocr.ppocr.data.imaug.rec_img_aug as recaug
import cv2
import os


def fileNames(root, suffix=None):
    names = os.listdir(root)
    result = []
    if suffix:
        for name in names:
            if os.path.splitext(name)[1] == suffix:
                result.append(root + name)
    else:
        result = names
    return result


pas = fileNames('C:/Users/Administrator/train_img/', '.png')
print(pas)
for pa in pas:
    aug = recaug.RecAug(True, 0.4)
    img = cv2.imread(pa)
    data = {'image': img}
    k = aug(data)
    cv2.imwrite(pa, k['image'])

**Comment by monkeycc** [comment]
@song4875343 
感谢
抱抱大佬的大腿

**Comment by HappyJiaJun** [comment]
> 是要在训练过程中增强吗？还是使用离线增强。
> 
> 如果是训练过程中使用数据增强，可以直接在配置文件中添加 RecAug 字段，参考：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml#L74
> 
> 如果希望离线处理数据，可以把源码复制下来，写一个自定义读图的代码，加载RecAug 类就好：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/ppocr/data/imaug/rec_img_aug.py#L23

大佬，请问能否在配置文件中添加两种数据增强方式，比如再添加一个--ABINetRecAug
