### ISSUE TITLE
如何通过画图发现训练的 模型是否过拟合？

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5791]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
eval_acc 低，而训练acc高，就说明过拟合了

**Comment by qqqqq127** [comment]
> eval_acc 低，而训练acc高，就说明过拟合了

检测的模型，测试集的loss从哪看呢
