### ISSUE TITLE
PPOCRV2模型训练没报错，解压数据解压着就不跑了。。显示已完成

### ISSUE THREAD

**Issue by melon12321** [PaddlePaddle/PaddleOCR#5802]
![image](https://user-images.githubusercontent.com/89839121/160322034-61929196-1004-4fd5-b27f-4837e32176df.png)
![image](https://user-images.githubusercontent.com/89839121/160322054-96ee4df9-6a42-4ec3-8931-45eed6b19fbb.png)

**Comment by littletomatodonkey** [comment]
这看着和代码没啥关系？先把数据解压完之后再运行
