### ISSUE TITLE
识别模型评估RecMetric的问题

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5807]
![){SWJM2Y5VCLC9JN0C9 D(X](https://user-images.githubusercontent.com/37231239/160367815-0ae7544d-f439-4d36-a5bc-0af1e304764a.png)
请问出于什么考虑要在计算acc的时候把空格去掉，对于需要预测空格的任务来说，这个计算方式就不对了

**Comment by littletomatodonkey** [comment]
你好，我们主要关注中文场景，所以这里把空格去掉了，如果你的场景需要关注空格的话，可以把这里注释掉哈

**Comment by GivanTsai** [comment]
> 你好，我们主要关注中文场景，所以这里把空格去掉了，如果你的场景需要关注空格的话，可以把这里注释掉哈

嗯嗯，我可以把这两行注释掉，但是ru'guo如果训练的配置文件中use_space_char设置为True的话，这里的metric如果按原本那样计算是不是就不合理了
![3YU0J{9`ACG CF3_4 }G1G7](https://user-images.githubusercontent.com/37231239/160392260-749006ee-7d64-41c3-9c2e-d0886d9c3140.png)

**Comment by littletomatodonkey** [comment]
use space char只是在训练的时候是否在字典中加入空格，跟最后的评估是独立的，你可以直接把评估逻辑修改了就好哈
