### ISSUE TITLE
PP-OCRv2 Android端部署bug

### ISSUE THREAD

**Issue by ljdang** [PaddlePaddle/PaddleOCR#5808]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

基于官方的dygraph分支android_demo，PP-OCRv2 slim模型，识别结果后半部分缺少或错误。
复现输入图片见附件中测试图.png，识别结果见附件中结果图.png。
[附件.zip](https://github.com/PaddlePaddle/PaddleOCR/files/8361709/default.zip)

**Comment by ljdang** [comment]
@WenmuZhou

**Comment by WenmuZhou** [comment]
mark
