### ISSUE TITLE
识别模型微调效果不好

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5810]
通用模型大部分文字能够识别正确，对少部分文字识别不好，想通过合成这些识别不好的文字图片进行finetune，发现模型最终反而只能识别这些finetune的文字了；如何能够保住原本的识别能力，又增加finetune的能力；
这个issue也提到了这个问题：https://github.com/PaddlePaddle/PaddleOCR/issues/4909

**Comment by littletomatodonkey** [comment]
可以把中英文通用OCR的数据加进去混合训练，比如lsvt、rctw、mtwi等数据

**Comment by GivanTsai** [comment]
> 可以把中英文通用OCR的数据加进去混合训练，比如lsvt、rctw、mtwi等数据

这些数据，通用模型不是已经拿来预训练了吗
