### ISSUE TITLE
Android PaddleOCR,APP进程后台时 识别效率特别低, 使用前台服务也无法提高识别效率 ,只有APP进程前台时识别效率正常

### ISSUE THREAD

**Issue by simple16000148819** [PaddlePaddle/PaddleOCR#5814]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：红米K20 pro , Android 11
- 版本号/Version：Paddle：2.2  PaddleOCR：2.2  问题相关组件/Related components： PaddleOCR android
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
app后台时，系统给的调度少，效率低很正常

**Comment by simple16000148819** [comment]
大佬 请求一下, 我这运行环境有root权限 有什么办法可以把orc服务调度优先级提到最高呢 , 把app设置为系统应用可行吗
