### ISSUE TITLE
【新手问题】用PaddleOCR训练自有英文字符+数字的图片，有什么建议？

### ISSUE THREAD

**Issue by HuangKBAaron** [PaddlePaddle/PaddleOCR#582]
1、选了PaddleOCR上的rec_mv3_none_bilstm_ctc做为pretrain model。效果还没有同样中文模型效果好（但这个中文的识别率也低于50%）。有什么好建议？

2、图片大小是【70，670】，缩小到代码默认的32，200会不会影响结果？

3、我制作了一个label，只有数字和大写字符。训练都指定了用这个label，推理时也指定了这个label文件，但推理居然会出小写字符。是不是在模型导出那一步也要额外指定（在train.yml之外）？

**Comment by WenmuZhou** [comment]
看起来是训练没有改character_type为ch

**Comment by HuangKBAaron** [comment]
ch不是中文的意思？我也试过ch，效果很差。后来改为en，稍好些。还是需要有些其它配套的改动？
另外，
4、ResnetXXX的都不需要配字典。这是为什么？

5、pretrained的model一定要搭配对应的yml？



有交流群？

**Comment by WenmuZhou** [comment]
使用自定义字典时，character_type是需要改为ch的不然会使用内置的英文字典
4. 不需要配字典应该是使用了内置的
5. 是的因为涉及到组网的问题

我们有微信交流群的，扫码ji加群
![image](https://user-images.githubusercontent.com/12406017/90863471-ad113200-e3c1-11ea-900b-c2599ecf5dad.png)

**Comment by ezio1320** [comment]
> 使用自定义字典时，character_type是需要改为ch的不然会使用内置的英文字典
> 4. 不需要配字典应该是使用了内置的
> 5. 是的因为涉及到组网的问题
> 
> 我们有微信交流群的，扫码ji加群
> ![image](https://user-images.githubusercontent.com/12406017/90863471-ad113200-e3c1-11ea-900b-c2599ecf5dad.png)

这个二维码失效了，想加群交流。

**Comment by WenmuZhou** [comment]
现在微信群变成邀请入群了，加我微信吧，z572459439  备注paddleocr
