### ISSUE TITLE
数据增强copypaste是不是没有生效

### ISSUE THREAD

**Issue by JulyYoung** [PaddlePaddle/PaddleOCR#5822]
Paddleocr2.4，使用ch_PP-OCRv2_det_cml.yml 进行fintune时，
数据增强 copypaste,  对于paste到原图上的extimg，在 进行 EastRandomCropData 时，如果crop的是paste部分，则 polys 为空，没有文本行的坐标信息，如何参与训练呢？
如果没有参与训练，那paste操作又有何意义？

**Comment by WenmuZhou** [comment]
paste过程中也向标注里增加了polys，可以可视化看一下CopyPaste的输出

**Comment by JulyYoung** [comment]
> paste过程中也向标注里增加了polys，代码在这里[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/data/imaug/copy_paste.py#L64，可以可视化看一下CopyPaste的输出](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/data/imaug/copy_paste.py#L64%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8F%AF%E8%A7%86%E5%8C%96%E7%9C%8B%E4%B8%80%E4%B8%8BCopyPaste%E7%9A%84%E8%BE%93%E5%87%BA)

这部分是有polys信息，关键是后续EastRandomCrop时，paste部分的polys信息就没了，crop出的都是原图的文本行信息，目前可视化看到的是这样的结果。
