### ISSUE TITLE
使用deploy/cpp_infer推理时，连续推理多张图片，报错

### ISSUE THREAD

**Issue by wanggp01** [PaddlePaddle/PaddleOCR#5823]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04，docker镜像：registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7
- 版本号/Version：Paddle：2.1.3 ， PaddleOCR： 问题相关组件/Related components：使用的是c++推理代码，提示找不到tensorrt动态库
- 运行指令/Command Code：./build/ppocr rec  --rec_model_dir=inference/ch_PP-OCRv2_rec_infer/  --image_dir=test/111.jpg
- 完整报错/Complete Error [Message：]：
![image](https://user-images.githubusercontent.com/62408936/160767283-8a23e6d2-11b5-4d41-858c-6c2a7c5e3e17.png)
完整错误信息如下：
*** Error in `./build/ppocr': free(): corrupted unsorted chunks: 0x000000003f5b1800 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7f43775687f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8038a)[0x7f437757138a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f437757558c]
./build/ppocr[0x443538]
./build/ppocr[0x442c90]
./build/ppocr[0x441db6]
./build/ppocr[0x4406ff]
./build/ppocr[0x43f433]
./build/ppocr[0x44eada]
./build/ppocr[0x43b493]
./build/ppocr[0x43c133]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4377511840]
./build/ppocr[0x439f59]
======= Memory map: ========
00400000-00f46000 r-xp 00000000 00:4a 3310560                            /home/PaddleOCR/deploy/cpp_infer/build/ppocr
01145000-01170000 r--p 00b45000 00:4a 3310560                            /home/PaddleOCR/deploy/cpp_infer/build/ppocr
01170000-0117e000 rw-p 00b70000 00:4a 3310560                            /home/PaddleOCR/deploy/cpp_infer/build/ppocr
0117e000-0129f000 rw-p 00000000 00:00 0 
01361000-404fa000 rw-p 00000000 00:00 0                                  [heap]
200000000-200200000 ---p 00000000 00:00 0 
200200000-200400000 rw-s 00000000 00:06 512                              /dev/nvidiactl
200400000-202400000 rw-s 00000000 00:06 512                              /dev/nvidiactl
202400000-205400000 rw-s 00000000 00:06 512                              /dev/nvidiactl
205400000-205c00000 ---p 00000000 00:00 0 
205c00000-205e00000 rw-s 00000000 00:06 512                              /dev/nvidiactl
205e00000-206000000 rw-s 00000000 00:06 512                              /dev/nvidiactl
206000000-206200000 rw-s 206000000 00:06 514                             /dev/nvidia-uvm
206200000-206400000 rw-s 00000000 00:06 512                              /dev/nvidiactl
206400000-206600000 ---p 00000000 00:00 0 
206600000-206800000 rw-s 00000000 00:06 512                              /dev/nvidiactl
206800000-300200000 ---p 00000000 00:00 0 
10000000000-10104000000 ---p 00000000 00:00 0 
7f41ec000000-7f41ec021000 rw-p 00000000 00:00 0 
7f41ec021000-7f41f0000000 ---p 00000000 00:00 0 
7f41f2e06000-7f41fe336000 r-xp 00000000 00:4a 137946                     /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusolver.so.10.3.0.89
7f41fe336000-7f41fe535000 ---p 0b530000 00:4a 137946                     /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusolver.so.10.3.0.89
7f41fe535000-7f41fe5b6000 rw-p 0b52f000 00:4a 137946                     /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusolver.so.10.3.0.89
7f41fe5b6000-7f41fe5cd000 rw-p 00000000 00:00 0 
7f41fe5cd000-7f42001e7000 r-xp 00000000 00:4a 137905                     /usr/lib/x86_64-linux-gnu/libcublasLt.so.10.2.2.89
7f42001e7000-7f42003e6000 ---p 01c1a000 00:4a 137905                     /usr/lib/x86_64-linux-gnu/libcublasLt.so.10.2.2.89
7f42003e6000-7f4200457000 rw-p 01c19000 00:4a 137905                     /usr/lib/x86_64-linux-gnu/libcublasLt.so.10.2.2.89
7f4200457000-7f4200460000 rw-p 00000000 00:00 0 
7f4200460000-7f42044fe000 r-xp 00000000 00:4a 137903                     /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.2.89
7f42044fe000-7f42046fe000 ---p 0409e000 00:4a 137903                     /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.2.89
7f42046fe000-7f420470c000 rw-p 0409e000 00:4a 137903                     /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.2.89
7f420470c000-7f4204716000 rw-p 00000000 00:00 0 
7f4204716000-7f421fcad000 r-xp 00000000 00:4a 274161                     /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
7f421fcad000-7f421feac000 ---p 1b597000 00:4a 274161                     /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
7f421feac000-7f421ff6d000 rw-p 1b596000 00:4a 274161                     /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
7f421ff6d000-7f4220000000 rw-p 00000000 00:00 0 
7f4220000000-7f4220021000 rw-p 00000000 00:00 0 
7f4220021000-7f4224000000 ---p 00000000 00:00 0 
7f4224000000-7f4224021000 rw-p 00000000 00:00 0 
7f4224021000-7f4228000000 ---p 00000000 00:00 0 
7f4228000000-7f4228021000 rw-p 00000000 00:00 0 
7f4228021000-7f422c000000 ---p 00000000 00:00 0 
7f422c000000-7f4326000000 ---p 00000000 00:00 0 
7f4326e93000-7f4346000000 rw-p 00000000 00:00 0 
7f4346000000-7f4349c00000 ---p 00000000 00:00 0 
7f4349c00000-7f4349e00000 rw-s 00000000 00:01 6338347                    /dev/zero (deleted)
7f4349e00000-7f434a600000 ---p 00000000 00:00 0 
7f434a600000-7f434a800000 rw-s 00000000 00:01 6341014                    /dev/zero (deleted)
7f434a800000-7f4350000000 ---p 00000000 00:00 0 
7f4350000000-7f4350001000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350001000-7f4350002000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350002000-7f4350003000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350003000-7f4350004000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350004000-7f4350005000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350005000-7f4350006000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350006000-7f4350007000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350007000-7f4350008000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350008000-7f4350009000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350009000-7f435000a000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000a000-7f435000b000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000b000-7f435000c000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000c000-7f435000d000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000d000-7f435000e000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000e000-7f435000f000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f435000f000-7f4350010000 rw-s 00000000 00:06 513                        /dev/nvidia0
7f4350010000-7f4360000000 ---p 00000000 00:00 0 
7f4360000000-7f4360021000 rw-p 00000000 00:00 0 
7f4360021000-7f4364000000 ---p 00000000 00:00 0 
7f43641e0000-7f43641e1000 ---p 00000000 00:00 0 
7f43641e1000-7f43649e1000 rw-p 00000000 00:00 0 
7f43649e1000-7f43649e2000 ---p 00000000 00:00 0 
7f43649e2000-7f4366000000 rw-p 00000000 00:00 0 
7f4366000000-7f4366400000 ---p 00000000 00:00 0 
7f4366400000-7f4366600000 rw-s 00000000 00:01 6338342                    /dev/zero (deleted)
7f4366600000-7f4366800000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f4366800000-7f4366a00000 rw-s 00000000 00:01 6338343                    /dev/zero (deleted)
7f4366a00000-7f4366e00000 ---p 00000000 00:00 0 
7f4366e00000-7f4367000000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f4367000000-7f4367200000 rw-s 00000000 00:01 6338345                    /dev/zero (deleted)
7f4367200000-7f43674d6000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43674d6000-7f4368000000 ---p 00000000 00:00 0 
7f4368000000-7f4368021000 rw-p 00000000 00:00 0 
7f4368021000-7f436c000000 ---p 00000000 00:00 0 
7f436c56c000-7f436c56d000 ---p 00000000 00:00 0 
7f436c56d000-7f436cd6d000 rw-p 00000000 00:00 0 
7f436cd6d000-7f436cd6e000 ---p 00000000 00:00 0 
7f436cd6e000-7f436d7f1000 rw-p 00000000 00:00 0 
7f436d7f1000-7f436d9f1000 rw-s 00000000 00:01 6338344                    /dev/zero (deleted)
7f436d9f1000-7f436d9f2000 ---p 00000000 00:00 0 
7f436d9f2000-7f436e375000 rw-p 00000000 00:00 0 
7f436e375000-7f436e376000 ---p 00000000 00:00 0 
7f436e376000-7f436eb76000 rw-p 00000000 00:00 0 
7f436eb76000-7f436eb77000 ---p 00000000 00:00 0 
7f436eb77000-7f436f377000 rw-p 00000000 00:00 0 
7f436f377000-7f4375377000 ---p 00000000 00:00 0 
7f4375377000-7f4376891000 r-xp 00000000 103:02 1320032                   /usr/lib/x86_64-linux-gnu/libcuda.so.470.103.01
7f4376891000-7f4376a90000 ---p 0151a000 103:02 1320032                   /usr/lib/x86_64-linux-gnu/libcuda.so.470.103.01
7f4376a90000-7f4376b84000 r--p 01519000 103:02 1320032                   /usr/lib/x86_64-linux-gnu/libcuda.so.470.103.01
7f4376b84000-7f4376c8f000 rw-p 0160d000 103:02 1320032                   /usr/lib/x86_64-linux-gnu/libcuda.so.470.103.01
7f4376c8f000-7f4376cb1000 rw-p 00000000 00:00 0 
7f4376cb1000-7f4376cbc000 r-xp 00000000 00:4a 132005                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4376cbc000-7f4376ebb000 ---p 0000b000 00:4a 132005                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4376ebb000-7f4376ebc000 r--p 0000a000 00:4a 132005                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4376ebc000-7f4376ebd000 rw-p 0000b000 00:4a 132005                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4376ebd000-7f4376ec3000 rw-p 00000000 00:00 0 
7f4376ec3000-7f4376ece000 r-xp 00000000 00:4a 132009                     /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f4376ece000-7f43770cd000 ---p 0000b000 00:4a 132009                     /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f43770cd000-7f43770ce000 r--p 0000a000 00:4a 132009                     /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f43770ce000-7f43770cf000 rw-p 0000b000 00:4a 132009                     /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f43770cf000-7f43770e5000 r-xp 00000000 00:4a 131999                     /lib/x86_64-linux-gnu/libnsl-2.23.so
7f43770e5000-7f43772e4000 ---p 00016000 00:4a 131999                     /lib/x86_64-linux-gnu/libnsl-2.23.so
7f43772e4000-7f43772e5000 r--p 00015000 00:4a 131999                     /lib/x86_64-linux-gnu/libnsl-2.23.so
7f43772e5000-7f43772e6000 rw-p 00016000 00:4a 131999                     /lib/x86_64-linux-gnu/libnsl-2.23.so
7f43772e6000-7f43772e8000 rw-p 00000000 00:00 0 
7f43772e8000-7f43772f0000 r-xp 00000000 00:4a 132001                     /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f43772f0000-7f43774ef000 ---p 00008000 00:4a 132001                     /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f43774ef000-7f43774f0000 r--p 00007000 00:4a 132001                     /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f43774f0000-7f43774f1000 rw-p 00008000 00:4a 132001                     /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f43774f1000-7f43776b1000 r-xp 00000000 00:4a 131956                     /lib/x86_64-linux-gnu/libc-2.23.so
7f43776b1000-7f43778b1000 ---p 001c0000 00:4a 131956                     /lib/x86_64-linux-gnu/libc-2.23.so
7f43778b1000-7f43778b5000 r--p 001c0000 00:4a 131956                     /lib/x86_64-linux-gnu/libc-2.23.so
7f43778b5000-7f43778b7000 rw-p 001c4000 00:4a 131956                     /lib/x86_64-linux-gnu/libc-2.23.so
7f43778b7000-7f43778bb000 rw-p 00000000 00:00 0 
7f43778bb000-7f43778d1000 r-xp 00000000 00:4a 131977                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f43778d1000-7f4377ad0000 ---p 00016000 00:4a 131977                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4377ad0000-7f4377ad1000 rw-p 00015000 00:4a 131977                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4377ad1000-7f4377c44000 r-xp 00000000 00:4a 2105125                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4377c44000-7f4377e44000 ---p 00173000 00:4a 2105125                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4377e44000-7f4377e4e000 r--p 00173000 00:4a 2105125                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4377e4e000-7f4377e50000 rw-p 0017d000 00:4a 2105125                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4377e50000-7f4377e53000 rw-p 00000000 00:00 0 
7f4377e53000-7f4377f5b000 r-xp 00000000 00:4a 131988                     /lib/x86_64-linux-gnu/libm-2.23.so
7f4377f5b000-7f437815a000 ---p 00108000 00:4a 131988                     /lib/x86_64-linux-gnu/libm-2.23.so
7f437815a000-7f437815b000 r--p 00107000 00:4a 131988                     /lib/x86_64-linux-gnu/libm-2.23.so
7f437815b000-7f437815c000 rw-p 00108000 00:4a 131988                     /lib/x86_64-linux-gnu/libm-2.23.so
7f437815c000-7f4378174000 r-xp 00000000 00:4a 132024                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4378174000-7f4378373000 ---p 00018000 00:4a 132024                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4378373000-7f4378374000 r--p 00017000 00:4a 132024                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4378374000-7f4378375000 rw-p 00018000 00:4a 132024                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4378375000-7f4378379000 rw-p 00000000 00:00 0 
7f4378379000-7f437839a000 r-xp 00000000 00:4a 140695                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f437839a000-7f4378599000 ---p 00021000 00:4a 140695                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f4378599000-7f437859a000 r--p 00020000 00:4a 140695                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f437859a000-7f437859b000 rw-p 00021000 00:4a 140695                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f437859b000-7f43785a2000 r-xp 00000000 00:4a 132030                     /lib/x86_64-linux-gnu/librt-2.23.so
7f43785a2000-7f43787a1000 ---p 00007000 00:4a 132030                     /lib/x86_64-linux-gnu/librt-2.23.so
7f43787a1000-7f43787a2000 r--p 00006000 00:4a 132030                     /lib/x86_64-linux-gnu/librt-2.23.so
7f43787a2000-7f43787a3000 rw-p 00007000 00:4a 132030                     /lib/x86_64-linux-gnu/librt-2.23.so
7f43787a3000-7f43787a6000 r-xp 00000000 00:4a 131969                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f43787a6000-7f43789a5000 ---p 00003000 00:4a 131969                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f43789a5000-7f43789a6000 r--p 00002000 00:4a 131969                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f43789a6000-7f43789a7000 rw-p 00003000 00:4a 131969                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f43789a7000-7f43789c0000 r-xp 00000000 00:4a 132055                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f43789c0000-7f4378bbf000 ---p 00019000 00:4a 132055                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4378bbf000-7f4378bc0000 r--p 00018000 00:4a 132055                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4378bc0000-7f4378bc1000 rw-p 00019000 00:4a 132055                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4378bc1000-7f437b25f000 r-xp 00000000 00:4a 3306560                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0
7f437b25f000-7f437b45e000 ---p 0269e000 00:4a 3306560                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0
7f437b45e000-7f437b4df000 r--p 0269d000 00:4a 3306560                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0
7f437b4df000-7f437b4e1000 rw-p 0271e000 00:4a 3306560                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0
7f437b4e1000-7f437b517000 rw-p 00000000 00:00 0 
7f437b517000-7f437b6d1000 r-xp 00000000 00:4a 3305629                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libiomp5.so
7f437b6d1000-7f437b8d0000 ---p 001ba000 00:4a 3305629                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libiomp5.so
7f437b8d0000-7f437b8d3000 r--p 001b9000 00:4a 3305629                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libiomp5.so
7f437b8d3000-7f437b8dd000 rw-p 001bc000 00:4a 3305629                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libiomp5.so
7f437b8dd000-7f437b90c000 rw-p 00000000 00:00 0 
7f437b90c000-7f438342f000 r-xp 00000000 00:4a 3305619                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libmklml_intel.so
7f438342f000-7f438362e000 ---p 07b23000 00:4a 3305619                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libmklml_intel.so
7f438362e000-7f4383654000 r--p 07b22000 00:4a 3305619                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libmklml_intel.so
7f4383654000-7f438371e000 rw-p 07b48000 00:4a 3305619                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/third_party/install/mklml/lib/libmklml_intel.so
7f438371e000-7f4383744000 rw-p 00000000 00:00 0 
7f4383744000-7f43c1cb8000 r-xp 00000000 00:4a 3307635                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/paddle/lib/libpaddle_inference.so
7f43c1cb8000-7f43c1eb7000 ---p 3e574000 00:4a 3307635                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/paddle/lib/libpaddle_inference.so
7f43c1eb7000-7f43c1fa8000 r--p 3e573000 00:4a 3307635                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/paddle/lib/libpaddle_inference.so
7f43c1fa8000-7f43c1fe5000 rw-p 3e664000 00:4a 3307635                    /home/PaddleOCR/deploy/cpp_infer/paddle_inference/paddle/lib/libpaddle_inference.so
7f43c1fe5000-7f43c206c000 rw-p 00000000 00:00 0 
7f43c206c000-7f43c2092000 r-xp 00000000 00:4a 131936                     /lib/x86_64-linux-gnu/ld-2.23.so
7f43c209a000-7f43c21c4000 rw-p 00000000 00:00 0 
7f43c21d7000-7f43c2228000 rw-p 00000000 00:00 0 
7f43c2228000-7f43c2229000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2229000-7f43c222a000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c222a000-7f43c222b000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c222b000-7f43c222c000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c222c000-7f43c2283000 rw-p 00000000 00:00 0 
7f43c2283000-7f43c2284000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2284000-7f43c2285000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2285000-7f43c2286000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2286000-7f43c2287000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2287000-7f43c2288000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2288000-7f43c2289000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c2289000-7f43c228a000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228a000-7f43c228b000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228b000-7f43c228c000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228c000-7f43c228d000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228d000-7f43c228e000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228e000-7f43c228f000 rw-s 00000000 00:06 512                        /dev/nvidiactl
7f43c228f000-7f43c2291000 rw-p 00000000 00:00 0 
7f43c2291000-7f43c2292000 r--p 00025000 00:4a 131936                     /lib/x86_64-linux-gnu/ld-2.23.so
7f43c2292000-7f43c2293000 rw-p 00026000 00:4a 131936                     /lib/x86_64-linux-gnu/ld-2.23.so
7f43c2293000-7f43c2294000 rw-p 00000000 00:00 0 
7fff00c13000-7fff00c34000 rw-p 00000000 00:00 0                          [stack]
7fff00c7c000-7fff00c7f000 r--p 00000000 00:00 0                          [vvar]
7fff00c7f000-7fff00c80000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by MissPenguin** [comment]
python推理能正常预测吗，c++预测报错是稳定复现吗，是运行到特定的图片后报错？

**Comment by wanggp01** [comment]
> python推理能正常预测吗，c++预测报错是稳定复现吗，是运行到特定的图片后报错？
使用python推理报错：
![image](https://user-images.githubusercontent.com/62408936/160982161-b3c2d93b-7590-4859-bddc-5df05bdcab9e.png)
使用C++预测时，预测单张图像，当图像中文本较多时，就会报上述的错误，测试了doc/imgs/00057937.jpg,00018069.jpg,00015504.jpg,均报错
