### ISSUE TITLE
POCRLabel 自定义了 det_model_dir ，但是没有模型预测的效果

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#5824]
`self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=False, det=True, cls=True, use_gpu=gpu, lang=lang, show_log=False,det_model_dir="E:/PaddleOCR/output/det_r50_vd_inference",`

一样的图片测试

python tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_r50_vd_inference/" --image_dir="F:/Biaozhu/" --use_gpu=True
DB检测模型inference 模型预测效果很好 没问题

但是PPOCRLabel中不行 很多检测不到文字框

加上 det_algorithm="DB" 也是一样

**Comment by MissPenguin** [comment]
应该是更换模型没生效，PPOCRLabel更换模型后需要重新编译一下

**Comment by Evezerest** [comment]
是使用python脚本启动的还是通过PPOCRLabel whl包呢
