### ISSUE TITLE
脚本只能支持单张推理吗

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#5825]
我看`tools/infer/predict_rec.py` 支持多张图片一个batch同时识别，`tools/infer/predict_system.py`只支持单张推理吗

**Comment by MissPenguin** [comment]
是的，因为检测阶段是单张处理的，检测进行resize时按长边960处理，所以不同的输入图像resize后尺度是不一样的

**Comment by GivanTsai** [comment]
> 是的，因为检测阶段是单张处理的，检测进行resize时按长边960处理，所以不同的输入图像resize后尺度是不一样的

那怎么样可以批量处理呢，这样的话可以充分利用GPU和提升速度

**Comment by GivanTsai** [comment]
@MissPenguin @LDOUBLEV 求问

**Comment by paul221027** [comment]
问题不要沉啊，有没有大神解答一下，我也面临同样的问题。需要大量处理。
