### ISSUE TITLE
请问通过pip安装的版本对应的是哪个代码分支呢？

### ISSUE THREAD

**Issue by jaycecd** [PaddlePaddle/PaddleOCR#5826]
![image](https://user-images.githubusercontent.com/33342388/160613981-4df7b58f-cc69-4031-9722-49ceeb0643d8.png)
![image](https://user-images.githubusercontent.com/33342388/160614140-6fb6ecf5-59df-4d64-882c-7049b71a4e35.png)
如图，本地通过
`pip install "paddleocr>=2.0.1"`
安装了paddleocr=2.4.0.3，但是看到目前Releases的版本是2.1.0，并且打开本地的文件，和目前默认的release/2.4分支代码不一致，所以想咨询一下pip发布的whl包是用哪个分支发布的呢？或者说发布的whl包和代码版本之间的对应关系是怎样的？烦请大佬解答

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/160737464-6558ee3d-9c3e-4438-b264-b5ed887bc2d1.png)
这个估计应该是没更新，可以去Pypi看看最新的版本，以那里为准吧

**Comment by jaycecd** [comment]
@BeyondYourself 
感谢回复，pypi上面看不到是哪个分支的代码发布的.whl呀？

**Comment by WenmuZhou** [comment]
pip版本号和release对应哈

**Comment by jaycecd** [comment]
@WenmuZhou 
我之前也觉得是release/2.4分支，但实际情况好像并不是，如/tools/infer/predict_system.py这个文件里面的这段代码：
![image](https://user-images.githubusercontent.com/33342388/160767429-1a389b52-da22-4c98-b877-0007a88be924.png)
上图的这段代码没有在release/2.4分支出现过：

**Comment by jaycecd** [comment]
@WenmuZhou[](https://user-images.githubusercontent.com/33342388/160767429-1a389b52-da22-4c98-b877-0007a88be924.png)
我之前也觉得是release/2.4分支，但实际情况好像并不是，如/tools/infer/predict_system.py这个文件里面的这段代码：
image
上图的这段代码没有在release/2.4分支出现过：

**Comment by jaycecd** [comment]
@WenmuZhou 
我之前也觉得是release/2.4分支，但实际情况好像并不是，如/tools/infer/predict_system.py这个文件里面的这段代码：
![image](https://user-images.githubusercontent.com/33342388/160768421-cb011e83-f46e-4cc1-b077-899ab5800e4e.png)

但是看了一下这个文件的history，这段代码好像从来没有在release/2.4分支出现过：
![image](https://user-images.githubusercontent.com/33342388/160768198-e8ef938e-1ccd-408a-8be2-943872224280.png)
上述代码却在dygraph分支出现了：
![image](https://user-images.githubusercontent.com/33342388/160768722-40094f37-307a-4229-81ab-958c85a9db06.png)
这又把我搞迷糊了，所以具体的、正确的对应关系究竟是怎样的呢？谢谢啦

**Comment by shesung** [comment]
我尝试了所有2.6到最新版本的whl包，就没有一个版本支持return_word_box，但是对应的分支里都有这个选项。这太让人困惑了，whl包的代码到底对应哪个分支？或者压根不是这个仓库的代码发布的？
