### ISSUE TITLE
使用PPOCRLabel自动标注，自动闪退

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/PaddleOCR#5827]
使用PPOCRLabel自动标注，自动闪退， paddlepaddle-gpu==2.2.2, paddleocr是2.4版本，opencv版本为4.4.0.46
PPOCRLabel为whl安装，可以打开界面，但是加载好图片目录后，点击自动标注直接闪退，到了useing model from paddle直接闪退
![image](https://user-images.githubusercontent.com/44393339/160627635-f40ec454-d202-4e02-b218-b35578b4478f.png)

**Comment by BeyondYourself** [comment]
会不会是opencv版本的问题？？？

**Comment by wzy123456wzy** [comment]
> 会不会是opencv版本的问题？？？

opencv版本是按照文档里边安装的，高版本和要求的版本都测试过了，也不行。
而且我本地测试了paddleOcr，python推理的时候，加载完模型，进行预测，就会出现段错误。。。

**Comment by qqqqq127** [comment]
我当时碰到闪退问题，是因为在没有标签的图片上点了保存或者是别的操作导致的

**Comment by MissPenguin** [comment]
把opencv相关的包全都卸载后重装试试呢

**Comment by wzy123456wzy** [comment]
> 把opencv相关的包全都卸载后重装试试呢

全部重装了一次，也不行。。。paddleocr都么办法使用，出现段错误了，Process finished with exit code -1073741819 (0xC0000005)

**Comment by BeyondYourself** [comment]
> 装了一次，也不行。。。paddleocr都么办法使用，出现段错误了，Process finished with exit code -1073741819 (0xC00

你的python版本呢，python版本不建议高于3.7.9

**Comment by wzy123456wzy** [comment]
> > 装了一次，也不行。。。paddleocr都么办法使用，出现段错误了，Process finished with exit code -1073741819 (0xC00
> 
> 你的python版本呢，python版本不建议高于3.7.9

是3.7.9版本

**Comment by Evezerest** [comment]
新建一个环境吧，感觉环境崩了。可以先在命令行里保证运行paddleocr whl包的结果正确

**Comment by wzy123456wzy** [comment]
> 新建一个环境吧，感觉环境崩了。可以先在命令行里保证运行paddleocr whl包的结果正确

有可能吧，，det还能用。。。ocr不行了
