### ISSUE TITLE
请问针对这类检测模型有什么优化方案吗？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#5828]
![image](https://user-images.githubusercontent.com/102579571/160632224-6e7abd61-ab3c-4a9b-9817-bc24593b98db.png)
因为前面的关键字间隔会比较大，如何finetune，求大佬救救孩子吧！

**Comment by yjhtc007** [comment]
多生成这类数据进行finetune吧

**Comment by MissPenguin** [comment]
提供以下几个思路可以尝试下：
1. 多标注/合成一批这种数据进行finetune
2. 尝试下east等基于回归的算法，因为这种间隔较大的情况，分割类的方法生成的分割图很可能不相连，就很难通过后处理合并到同一个框
3. 如果检测成了单个的字符，版式固定的话，是否可以通过规则进行后处理合并？

**Comment by lvjianjin004** [comment]
> 提供以下几个思路可以尝试下：
> 
> 1. 多标注/合成一批这种数据进行finetune
> 2. 尝试下east等基于回归的算法，因为这种间隔较大的情况，分割类的方法生成的分割图很可能不相连，就很难通过后处理合并到同一个框
> 3. 如果检测成了单个的字符，版式固定的话，是否可以通过规则进行后处理合并？

当前采用的是您提的第三种方案，但是由于图像受噪声影响以及图像本身的一些偏移会产生影响所以后处理的工作量较大，感谢您的提醒，那我采取第二个方案试试，我之前是用的DBnet，同时方案一中不知道是否有生成类似户口本这样数据的方案呢？

**Comment by MissPenguin** [comment]
> > 提供以下几个思路可以尝试下：
> > 
> > 1. 多标注/合成一批这种数据进行finetune
> > 2. 尝试下east等基于回归的算法，因为这种间隔较大的情况，分割类的方法生成的分割图很可能不相连，就很难通过后处理合并到同一个框
> > 3. 如果检测成了单个的字符，版式固定的话，是否可以通过规则进行后处理合并？
> 
> 当前采用的是您提的第三种方案，但是由于图像受噪声影响以及图像本身的一些偏移会产生影响所以后处理的工作量较大，感谢您的提醒，那我采取第二个方案试试，我之前是用的DBnet，同时方案一中不知道是否有生成类似户口本这样数据的方案呢？

我们目前没有针对户口本这种垂类的数据合成方案呢
