### ISSUE TITLE
paddle-serving pipeline模式，线程并发模式识别结果错误

### ISSUE THREAD

**Issue by DequanZhu** [PaddlePaddle/PaddleOCR#5829]
PaddleOCR/deploy/pdserving/config.yml 将is_tread_op改成True，并发请求的情况下，相同图片返回结果不一致，而且有的识别结果中出现了其它图片中出现的文字。这个必须设置成进程并发模式吗？

**Comment by BeyondYourself** [comment]
> 

出现其他图片的文字，这个应该是你一次发了多张图片吧。如果是多并发，建议还是设置成进程模式,python的线程也是伪线程
