### ISSUE TITLE
部署过程中hub install deploy/hubserving/ocr_system/出错

### ISSUE THREAD

**Issue by xiaoyong001** [PaddlePaddle/PaddleOCR#5834]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
ImportError: cannot import name einsun from paddle' (/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/.
![b057f1c280923f14368bf8d8cd08a50](https://user-images.githubusercontent.com/49474119/160770176-f1f15570-5016-4d73-893a-7e83088ded7a.png)

**Comment by xiaoyong001** [comment]
运行hub install deploy/hubserving/ocr_system/之后
ImportError: cannot import name einsun from paddle' (/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/.

**Comment by LDOUBLEV** [comment]
你用的paddle版本是？，尝试安装2.2.2版本的paddle

**Comment by xiaoyong001** [comment]
> 你用的paddle版本是？，尝试安装2.2.2版本的paddle

解决了，paddlepaddle版本不对，卸载原来的，安装最新的
