### ISSUE TITLE
Get output tensor name of rec network

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/PaddleOCR#5836]
I want to get the name of the output tensor of the recognizer (CRNN) network. Is there a simple way to do this?

**Comment by LDOUBLEV** [comment]
It is recommended to use https://netron.app/ to visualize the rec inference.pdmodel.

Or you can build a predictor and get the output names like this :https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/tools/infer/utility.py#L307
