### ISSUE TITLE
有些文字未识别出来，需要怎么调？

### ISSUE THREAD

**Issue by ananas-hebo** [PaddlePaddle/PaddleOCR#5838]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：mac os
- 版本号/Version：Paddle： 2.2.0 PaddleOCR： 2.4 问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel
- 完整报错/Complete Error Message：无

![bg1](https://user-images.githubusercontent.com/5362672/160807181-9b6cb5c1-31eb-4bf7-af78-775f47fe05fa.jpg)
![92D2EA64-0BA9-4A79-8897-7F61B7DCE650](https://user-images.githubusercontent.com/5362672/160807413-7782e6d0-5b45-4801-8ff6-c2e212e4d5f7.png)

**Comment by yjhtc007** [comment]
这个是未检测到吧

**Comment by ananas-hebo** [comment]
> 这个是未检测到吧

应该是，我把图片放大了点可以识别出来了。
可能是det部分有问题，但希望有思路怎么处理会比较好点。

**Comment by LDOUBLEV** [comment]
增大图像size是一种方式，或者尝试通过修改后处理实现；

比如降低box_thresh 和thresold参数
https://github.com/PaddlePaddle/PaddleOCR/blob/e0a52ee5110235d5ba5313f95726110e11eb16bf/tools/infer/utility.py#L50-L51

**Comment by ananas-hebo** [comment]
det模型 ch_ppocr_server_v2.0_det_infer 更换为 ch_PP-OCRv2_det_infer 后可以识别出来了。

**Comment by ananas-hebo** [comment]
@LDOUBLEV 
后来又碰见了一些检测不出来区域的，修改了参数：

```
det_db_thresh=0.2,
det_db_box_thresh=0.4,
det_db_unclip_ratio=1.75,
```
感谢指导。
