### ISSUE TITLE
在线量化产生的模型如何转换为paddle C++推理库支持的模型呢

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/PaddleOCR#5839]
![image](https://user-images.githubusercontent.com/20138766/160818774-7c285451-3534-4ba8-b154-4ea48115d728.png)
这样的模型使用paddle-trt推理输出是异常的

**Comment by marsbzp** [comment]
能帮忙看下吗，可以用这个模型复现https://paddleocr.bj.bcebos.com/dygraph_v2.0/slim/ch_ppocr_mobile_v2.0_rec_slim_infer.tar
paddle-trt无法正常推理

**Comment by LDOUBLEV** [comment]
无法正常推理是报错还是结果不对？

不用TRT推理结果是否是正常的？

**Comment by marsbzp** [comment]
模型导出的时候softmax没掉了是啥原因，centerloss + ctc训的
![image](https://user-images.githubusercontent.com/20138766/161208021-d10b5be5-536e-41a8-a2d4-c7c6474b37a4.png)

**Comment by LDOUBLEV** [comment]
> 模型导出的时候softmax没掉了是啥原因，centerloss + ctc训的

量化导出模型的时候在[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/633d0552851d41ae77c2f28ba83fda350648c341/deploy/slim/quantization/export_model.py#L136)加一行model.eval() 试下
