### ISSUE TITLE
PaddleOCR有支持表格结构标注的工具吗？

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/PaddleOCR#5841]
现在读取的是 `PubTabNet_2.0.0_train.jsonl` 文件，既包含文本又包含结构信息，能否分开呢，文本归文本，结构归结构。

https://github.com/PaddlePaddle/PaddleOCR/blob/a7399c92af4214a52c0106d9ea88e667c8e6b410/configs/table/table_mv3.yml#L69

**Comment by LDOUBLEV** [comment]
目前PPOCRLabel还不支持表格结构的标注；

> ，既包含文本又包含结构信息，能否分开呢，文本归文本，结构归结构。

目前不支持，需要修改label decoder的实现才行，你是有什么诉求吗？为什么需要文本标注和结构标注分开

**Comment by GreatV** [comment]
> 目前PPOCRLabel还不支持表格结构的标注；
> 
> > ，既包含文本又包含结构信息，能否分开呢，文本归文本，结构归结构。
> 
> 目前不支持，需要修改label decoder的实现才行，你是有什么诉求吗？为什么需要文本标注和结构标注分开

因为有时候只需要检测表格结构，不需要检测表格里的内容。
