### ISSUE TITLE
检测和识别判断过拟合的曲线怎么画呢

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5844]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以在配置文件中将`use_visualdl`设置为True，然后用visualDL进行可视化
