### ISSUE TITLE
飞桨平台使用遇到的问题如何解决？场景文本识别方向

### ISSUE THREAD

**Issue by huawenyu2020** [PaddlePaddle/PaddleOCR#5846]
1.如果采用飞桨里面的项目和上课内容进行发表，需要怎样添加引用呢？ 
2.提供的相关项目涉及到的模块已经封装完成，使用时仅仅是调用就可以，但如果考虑增加功能需要对模块进行修改，应该观看什么课程学习？  
3.涉及模块添加，模型框架修改的课程PPOCR在哪可以找到？  
4.框架之间的变换，模块相应会发生变化。 
 想问下如果采用飞桨平台进行学术方面的学习，针对上面的问题场景文本识别方向应该学习的课程应该包含什么，谢谢

**Comment by andyjpaddle** [comment]
版权问题需要遵循[Apache 2.0 license](https://github.com/PaddlePaddle/PaddleOCR/blob/master/LICENSE)
课程学习可以观看我们前段时间的直播课 https://aistudio.baidu.com/aistudio/course/introduce/25207
其他关于PaddleOCR的模块框架等问题可以在官方repo中查阅文档，文档相对详细，可以解决大部分问题。

**Comment by huawenyu2020** [comment]
> 版权问题需要遵循[Apache 2.0 license](https://github.com/PaddlePaddle/PaddleOCR/blob/master/LICENSE) 课程学习可以观看这个我有点问题，就比如我学习了相关课程，有些理论知识或者在已经存在项目上进行改进取得效果，这个引用表现在具体文字我应该怎么添加，文档英文的，不是很理解

**Comment by andyjpaddle** [comment]
文档是可以切换为中文的

**Comment by huawenyu2020** [comment]
> 文档是可以切换为中文的

我已经在文档中进行说明通过对百度飞桨平台课程【xxx】的学习

**Comment by andyjpaddle** [comment]
项目实现代码，可以说基于PaddleOCR repo进行开发完成，然后放一下官方 repo的链接。

**Comment by huawenyu2020** [comment]
比如文本检测方面，OCR十讲课程我觉得内容很丰富，资料很全，想引用课程中讲的理论内容。我备注通过对百度飞桨课程【OCR十讲】学习，xxx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 飞桨平台使用遇到的问题如何解决？场景文本识别方向 (Issue #5846)





 
有哪些需要引用的内容可以发一下，不同内容不太一样，如果是对于PP-OCR模型的引用可以引用我们首页上的arvix文章

**Comment by huawenyu2020** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 飞桨平台使用遇到的问题如何解决？场景文本识别方向 (Issue #5846)





 
项目实现代码，可以说基于PaddleOCR repo进行开发完成，然后放一下官方 repo的链接。
