### ISSUE TITLE
paddleocr2.1训练报错

### ISSUE THREAD

**Issue by lvjianjin004** [PaddlePaddle/PaddleOCR#5849]
![image](https://user-images.githubusercontent.com/91236933/160991382-4ebd783e-13d3-4877-abd7-7cf3f7422a83.png)
配置文件如下：
![image](https://user-images.githubusercontent.com/91236933/160991338-e419c0d4-a533-4240-b1ce-3d594daa5b4d.png)
这样没毛病的呀

**Comment by andyjpaddle** [comment]
提供一下完整报错和配置文件哈，数据集部分包含train和eval，都检查一下是否一致

**Comment by lvjianjin004** [comment]
> 提供一下完整报错和配置文件哈，数据集部分包含train和eval，都检查一下是否一致

以下是报错
Traceback (most recent call last):
  File "/root/paddlejob/workspace/code/PaddleOCR-release-2.1/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "/root/paddlejob/workspace/code/PaddleOCR-release-2.1/tools/train.py", line 63, in main
    valid_dataloader = build_dataloader(config, 'Eval', device, logger)
  File "/root/paddlejob/workspace/code/PaddleOCR-release-2.1/ppocr/data/__init__.py", line 65, in build_dataloader
    dataset = eval(module_name)(config, mode, logger, seed)
  File "/root/paddlejob/workspace/code/PaddleOCR-release-2.1/ppocr/data/simple_dataset.py", line 41, in __init__
    ) == data_source_num, "The length of ratio_list should be the same as the file_list."
AssertionError: The length of ratio_list should be the same as the file_list.

**Comment by lvjianjin004** [comment]
> 提供一下完整报错和配置文件哈，数据集部分包含train和eval，都检查一下是否一致

以下是配置文件
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /root/paddlejob/workspace/code
    label_file_list: 
      - /root/paddlejob/workspace/code/gendata/medicals.txt
      - /root/paddlejob/workspace/code/gendata/location.txt
      - /root/paddlejob/workspace/code/gendata/lsvt_genetare.txt
    ratio_list: [0.5,0.3,0.2]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /root/paddlejob/workspace/code
    label_file_list: /root/paddlejob/workspace/code/chinese1/val.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4

**Comment by andyjpaddle** [comment]
看报错是eval的问题，加上`ratio_list: 1.0`试试，`label_file_list`也采用list形式写

**Comment by lvjianjin004** [comment]
> 看报错是eval的问题，加上`ratio_list: 1.0`试试，`label_file_list`也采用list形式写

解决了，谢谢你
