### ISSUE TITLE
How to turn off Warning Notice  

### ISSUE THREAD

**Issue by baoloc97** [PaddlePaddle/PaddleOCR#5851]
i run paddle ocr on server and this happend like. So how can i fix this warning. install new version or somethings. Please help.

Namespace(benchmark=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/var/www/.paddleocr/2.3.0.1/ocr/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/var/www/.paddleocr/2.3.0.1/ocr/det/en/en_ppocr_mobile_v2.0_det_infer', det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_polygon=True, e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='japan', layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, model_storage_directory='/data/www/fadoml/data/ocr', output='./output/table', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='/data/www/fadoml/vendors/lib/python3.8/site-packages/paddleocr/ppocr/utils/dict/japan_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/var/www/.paddleocr/2.3.0.1/ocr/rec/japan/japan_mobile_v2.0_rec_infer', save_log_path='./log_output/', show_log=True, table_char_dict_path=None, table_char_type='en', table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, version='PP-OCRv2', vis_font_path='./doc/fonts/simfang.ttf', warmup=True)

**Comment by baoloc97** [comment]
> These warnings are not errors, it just print the config and params, you can ignore this information.

can u tell me how to ignore this :3

**Comment by antoniocorbalannavvaro** [comment]
I haven´t tried """PaddleOCR(show_log=True)""" yet, but I think it will work.

**Comment by andyjpaddle** [comment]
set `show_log=False` and try again

**Comment by esraa-abdelmaksoud** [comment]
Using show_log=False stopped the model from printing root debug lines with timestamps such as:
[2022/09/27 02:05:46] root DEBUG: dt_boxes num : 6, elapse : 0.5996313095092773
However, all engine details and configurations are still printed.

**Comment by andyjpaddle** [comment]
I have try it, it didn't show the configurations after I set `show_log=False`. you can upgrade the latest version 2.6

**Comment by Theocrat** [comment]
@andyjpaddle it is a major inconvenience when you run Paddle OCR inside a loop and you use TQDM on the loop (for instance, to loop over numerous pages).

**Comment by Keppl** [comment]
`show_log=False` doesn't seems to work for me even on 2.6.01.
`ocr = PaddleOCR(use_angle_cls=False, lang="en", show_log=False, use_gpu=True)`
Still shows warning on every call ocr.

Following works for me as a workaround (after `ocr` instance creation):
```
import logging
from ppocr.utils.logging import get_logger as ppocr_get_logger
ppocr_get_logger().setLevel(logging.ERROR)
```
This can be reset back after the loop is done to say INFO:
`ppocr_get_logger().setLevel(logging.INFO)`
