### ISSUE TITLE
Docker化部署遇到问题

### ISSUE THREAD

**Issue by xuxingya** [PaddlePaddle/PaddleOCR#586]
系统： Ubuntu 18.04
docker：19.03.5, build 633a0ea838

git clone https://github.com/PaddlePaddle/PaddleOCR.git, 使用docker build -t paddleocr:cpu进行docker部署时报错
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

**Comment by WenmuZhou** [comment]
先把PaddleOCR目录下的requirments.txt拷贝到当前目录下

**Comment by xuxingya** [comment]
> 先把PaddleOCR目录下的requirments.txt拷贝到当前目录下

![image](https://user-images.githubusercontent.com/13343428/90871173-3b3ee580-e3cd-11ea-9734-60f2124d7d19.png)
还是不行来着
