### ISSUE TITLE
如何在paddleocr中使用ch_ppocr_server_v2.0_xx的模型参数？

### ISSUE THREAD

**Issue by Cppowboy** [PaddlePaddle/PaddleOCR#5869]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 16.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddle2.2
- 运行指令/Command Code：paddleocr 2.4.0.3
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
具体一点
