### ISSUE TITLE
请问是否可以提供paddleOCR_V2.0的SRN识别模型的训练词典

### ISSUE THREAD

**Issue by wxiaoli** [PaddlePaddle/PaddleOCR#5871]
下载 https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/rec_r50_vd_srn_train.tar 转成 推理模型后，最后输出的维度是 5700，但是源码词典中没有这个长度的词典文件。

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：  PaddleOCR_v2.4
- 完整报错/Complete Error Message：
```
cannot reshape array of size 5700 into shape (39)
  File "/home/xlwang/projs/ocr/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 376, in __call__
    pred = np.reshape(pred, [-1, char_num])
```

**Comment by tink2123** [comment]
请试下这个预测命令：

```
python3.7 tools/infer/predict_rec.py --rec_model=srn_inference/ --rec_algorithm="SRN" --image_dir=doc/imgs_words/en/word_1.png --rec_image_shape="1,64,256" --rec_char_dict_path=./ppocr/utils/ic15_dict.txt --use_space=False
```

**Comment by wxiaoli** [comment]
> 请试下这个预测命令：
> 
> ```
> python3.7 tools/infer/predict_rec.py --rec_model=srn_inference/ --rec_algorithm="SRN" --image_dir=doc/imgs_words/en/word_1.png --rec_image_shape="1,64,256" --rec_char_dict_path=./ppocr/utils/ic15_dict.txt --use_space=False
> ```

可以正常输出结果。
