### ISSUE TITLE
文字和背景颜色有很接近的部分，二值化也会难分割出文字，要怎么训练才能改善准确率。微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5873]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.3  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
文字和背景颜色有很接近的部分，二值化也会难分割出文字，要怎么训练才能改善准确率。微信nlanguage

![0_11_28_650__0_11_30_986_0000000000000000000000203_output](https://user-images.githubusercontent.com/41010669/161417141-bf0a1035-a8c3-482b-977b-bb8a2ed1038f.jpg)
![0_11_30_986__0_11_33_321_0000000000000000000000204_output](https://user-images.githubusercontent.com/41010669/161417143-ff896dc5-9798-4088-b0a9-356892504a79.jpg)
![0_09_11_446__0_09_14_683_0000000000000000000000163_output](https://user-images.githubusercontent.com/41010669/161417144-f987632b-bfb2-4289-84a5-9135602b56c4.jpg)
![0_11_26_014__0_11_28_650_0000000000000000000000202_output](https://user-images.githubusercontent.com/41010669/161417145-fe191e15-1ae9-49a5-aec3-116b4579f08f.jpg)

**Comment by littletomatodonkey** [comment]
你好，这种建议多生成点图片到训练集中，强制模型学习即可

**Comment by nissansz** [comment]
生成的图片是不是也要尽量模拟这种，底色较浅，字体是白色，和文字带黑色包边？

**Comment by nissansz** [comment]
每次恢复训练，生成的图片不同，对模型有什么不利影响吗？会不会造成过拟合之类？

**Comment by nissansz** [comment]
![image](https://user-images.githubusercontent.com/41010669/161430288-a3a15da2-6fa8-469b-a7f0-be13e238e921.png)
模拟生成了这种图片，应该可以用来改善结果吧？

**Comment by littletomatodonkey** [comment]
看着生成的质量还可以，可以先加进去训练试试

**Comment by littletomatodonkey** [comment]
> 生成的图片是不是也要尽量模拟这种，底色较浅，字体是白色，和文字带黑色包边？

和实测场景相同即可，不建议有黑色包边，容易让模型学偏

**Comment by nissansz** [comment]
实测场景也是有包边的，不用加包边？

**Comment by littletomatodonkey** [comment]
> 实测场景也是有包边的，不用加包边？

那需要有包边

**Comment by nissansz** [comment]
好的。我生成一些数据试试。

另外想问，生产的数据，是句子，词汇，还是单字好？

每次换图片，恢复训练，会自动选择最佳准确率的模型，不会保存差的模型？

**Comment by littletomatodonkey** [comment]
> ，

1. 生成的长度和实测场景一致就行
2. 恢复训练建议选择输出文件夹中latest

**Comment by nissansz** [comment]
如果选择best_accuracy，是不是更好呢？

**Comment by littletomatodonkey** [comment]
resume training是要求选择latest，选择best acc的话，需要用finetune的方法

**Comment by littletomatodonkey** [comment]
或者你可以做实验看看

**Comment by littletomatodonkey** [comment]
可以去aistudio上找一个《动手学ocr10讲》的课程看看

**Comment by nissansz** [comment]
有链接吗？

只要恢复训练时，准确度高，保持高准确度就行。
现在用best accuracy恢复，感觉准确度可以改善

**Comment by littletomatodonkey** [comment]
手边没电脑，你去搜一下看看，很好搜的，应该是热门课程

**Comment by nissansz** [comment]
好像是这个。谢谢。https://aistudio.baidu.com/aistudio/course/introduce/25207

**Comment by GivanTsai** [comment]
> ![image](https://user-images.githubusercontent.com/41010669/161430288-a3a15da2-6fa8-469b-a7f0-be13e238e921.png) 模拟生成了这种图片，应该可以用来改善结果吧？

请问你这些图片是用什么工具生成的

**Comment by nissansz** [comment]
网上很多生成工具，代码都可以生成
