### ISSUE TITLE
VQA如何使用单机多卡训练呢

### ISSUE THREAD

**Issue by ga546** [PaddlePaddle/PaddleOCR#5875]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
和文本检测与识别训练方法相同，用distributed.launch启动

**Comment by ga546** [comment]
@littletomatodonkey 谢谢！
