### ISSUE TITLE
PaddleOCR

### ISSUE THREAD

**Issue by hongjianhui1211** [PaddlePaddle/PaddleOCR#5882]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：2.0.0,Paddle：2.1.2 ,2.  PaddleOCR： 问题相关组件/Related components：PaddleOCR\deploy\docker\hubserving\cpu
- 运行指令/Command Code：CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]
- 完整报错/Complete Error Message：ImportError: cannot import name 'einsum' from 'paddle' (/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/__init__.py)
docker打包好cpu版的ocr，启动报错
![}L{M@@27W_QC~WRDYIZ%FD3](https://user-images.githubusercontent.com/55616757/161591292-054adac5-b581-4ff0-874b-27c9760b3165.png)

**Comment by LDOUBLEV** [comment]
Please update your paddlepaddle following https://www.paddlepaddle.org.cn/
