### ISSUE TITLE
请问关键信息提取任务SDMG-R支持中文数据集吗

### ISSUE THREAD

**Issue by ga546** [PaddlePaddle/PaddleOCR#5883]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
按照英文数据集的相同格式标注中文数据就可以训练

**Comment by ga546** [comment]
谢谢！
