### ISSUE TITLE
训练检测模型

### ISSUE THREAD

**Issue by Sweetwenty** [PaddlePaddle/PaddleOCR#5887]
!python ./work/PaddleOCR/tools/train.py -c ./work/PaddleOCR/configs/det/det.yml
训练检测模型时，output中没有出现best_accuracy

**Comment by LDOUBLEV** [comment]
运行日志发出来看下

**Comment by Sweetwenty** [comment]
谢谢回复，原因是自己的配置文件没有设置。
我的目的是想先训练表单类型的检测模型，需要把每一个“单元格”检测出来，再对其中的内容进行识别。目前的疑惑是像素太大，放到PPLabel中不太好标注，想请教在结合预训练模型的前提下，是否一定需要放入整张表单对每个格子进行标注？另外这样的表单（像素较大，且表单中有大概10个单元格包含汉字）是否可以通过ppstructure训练，将识别后结果写到Excel中？
注：需要将数据手写到纸质表单中，所以最终需要识别的表单行分界线看可能不太明显。

![sheet](https://user-images.githubusercontent.com/87378415/162577676-5467f583-c856-405c-adb6-3548ed7b83be.png)

**Comment by Sweetwenty** [comment]
谢谢回复，原因是自己的配置文件没有设置。
我的目的是想先训练表单类型的检测模型，需要把每一个“单元格”检测出来，再对其中的内容进行识别。目前的疑惑是像素太大，放到PPLabel中不太好标注，想请教在结合预训练模型的前提下，是否一定需要放入整张表单对每个格子进行标注？另外这样的表单（像素较大，且表单中有大概10个单元格包含汉字）是否可以通过ppstructure训练，将识别后结果写到Excel中？
注：需要将数据手写到纸质表单中，所以最终需要识别的表单行分界线看可能不太明显。

![sheet](https://user-images.githubusercontent.com/87378415/162577676-5467f583-c856-405c-adb6-3548ed7b83be.png)
