### ISSUE TITLE
求教：怎么得到中文单字符的位置？

### ISSUE THREAD

**Issue by zhanghuibin** [PaddlePaddle/PaddleOCR#589]
目前检测模型都是检测的文字行，单字的位置通过什么方法实现呢？

**Comment by zhanghuibin** [comment]
> cnn+lstm+ctc的stride一般为4也就是3，32，320的图片经过cnn之后变成n，1，80。最后输出80个字符，每个字符对应到原图就是4个像素，这样可以大致确定单字的位置

谢谢，用你的方法可以的。后处理的时候当种子点，加上连通域和阈值，分割的相对完美。

> cnn+lstm+ctc的stride一般为4也就是3，32，320的图片经过cnn之后变成n，1，80。最后输出80个字符，每个字符对应到原图就是4个像素，这样可以大致确定单字的位置

试了一下，你的方法可行的。加上连通域和阈值判断能够分割的非常不错。感谢~

**Comment by DukeCheung** [comment]
> > cnn+lstm+ctc的stride一般为4也就是3，32，320的图片经过cnn之后变成n，1，80。最后输出80个字符，每个字符对应到原图就是4个像素，这样可以大致确定单字的位置
> 
> 试了一下，你的方法可行的。加上连通域和阈值判断能够分割的非常不错。感谢~

您好，我最近也想将中文单字分割出来，请问您提到的连通域和阈值判断的具体技术或算法流程是怎样的？谢谢。

**Comment by cuiyong127** [comment]
遇到同样的需求

**Comment by longnanxi** [comment]
> > cnn+lstm+ctc的stride一般为4也就是3，32，320的图片经过cnn之后变成n，1，80。最后输出80个字符，每个字符对应到原图就是4个像素，这样可以大致确定单字的位置
> 
> 试了一下，你的方法可行的。加上连通域和阈值判断能够分割的非常不错。感谢~

您好  我模型预测完之后每个时间片的预测结果是
tensor([   0, 5045,    0,    0,    0,    0, 3482,    0,    0,    0,    0,    0,
        2874, 2874,    0,    0,    0,    0,    0,    0, 5498, 5498,    0,    0,
        4041,    0,    0,    0,    0,    0, 5536,    0,    0,    0,    0,    0,
        4680,    0,    0,    0,    0], device='cuda:0')
其中0表示间隔字符、非0表示所属类别的index，单字符定位并不是很准确，请问您是如何解决间隔字符的问题的？

**Comment by longnanxi** [comment]
> cnn+lstm+ctc的stride一般为4也就是3，32，320的图片经过cnn之后变成n，1，80。最后输出80个字符，每个字符对应到原图就是4个像素，这样可以大致确定单字的位置

您好。我模型预测完之后，每个时间片的预测结果是：

tensor([   0, 5045,    0,    0,    0,    0, 3482,    0,    0,    0,    0,    0,
        2874, 2874,    0,    0,    0,    0,    0,    0, 5498, 5498,    0,    0,
        4041,    0,    0,    0,    0,    0, 5536,    0,    0,    0,    0,    0,
        4680,    0,    0,    0,    0], device='cuda:0')
其中0表示间隔字符、非0表示所属文字类别的index，虽然非0时间片定位文字位置很准确，但是并不能完全包围住文字区域，尝试将周围间隔字符进行所属文字的划分，但是单字符定位并不是很理想，请问您是如何解决间隔字符的时间片属于哪个文字的问题的呢？

**Comment by March-Wind** [comment]
遇到同样的问题，有大佬讲解一下吗
