### ISSUE TITLE
RARE识别算法的输出shape必须是（batch_size, 25, num_class）嘛，尤其那个25是固定的吗

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#5892]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18
- 版本号/Version：Paddle V2.2：  PaddleOCR： 问题相关组件/Related components：**RARE文字识别网络**
- 运行指令/Command Code：
- 完整报错/Complete Error Message：shape 不一致

问一下，图像经过网络模型后输入的结果是固定的（batch_size, 25, num_class），num_class:字典的长度

这是配置文件的图片，采用RARE识别算法
![Screenshot from 2022-04-06 16-09-26](https://user-images.githubusercontent.com/49891512/161953080-34e84ac2-7215-480c-91fb-a3caf5b1f972.png)
这是网络输出的shape，这样的输出导致上图中max_text_length只能设置为25，才能使用交叉熵损失（paddle要求N必须相同），参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/CrossEntropyLoss_cn.html#xingzhuang
![Screenshot from 2022-04-06 16-09-54](https://user-images.githubusercontent.com/49891512/161953087-eeb611f6-5a16-40b1-9641-ea43913b8d6b.png)

**Comment by andyjpaddle** [comment]
25是最大字符长度，可以根据自己的数据进行修改

**Comment by HouYanGG** [comment]
> 25是最大字符长度，可以根据自己的数据进行修改
目前不可以修改最大字符长度，只能是25，这样才符合官方的交叉熵损失规定，这个是rare算法，您可以尝试下

**Comment by andyjpaddle** [comment]
可以更改配置文件中的`max_text_length`试试哈，应该是支持的

**Comment by HouYanGG** [comment]
通过修改train中策略已经损失函数定义，解决该问题
