### ISSUE TITLE
训练中报错

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#5899]
训练集：2000万
Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 1000
  print_batch_step: 1000
  save_model_dir: ./output/rec_pp-OCRv2_distillation
  save_epoch_step: 1
  eval_batch_step: [0, 150000000]
  cal_metric_during_train: true
  pretrained_model: ./train_model/ch_PP-OCRv2_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_pp-OCRv2_distillation.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [200000, 220000]
    values : [0.00001, 0.000001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 2.0e-05

Architecture:
  model_type: &model_type "rec"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: CRNN
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        name: CTCHead
        mid_channels: 96
        fc_decay: 0.00002

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: head_out
  - DistillationDMLLoss:
      weight: 1.0
      act: "softmax"
      use_log: true
      model_name_pairs:
      - ["Student", "Teacher"]
      key: head_out
  - DistillationDistanceLoss:
      weight: 1.0
      mode: "l2"
      model_name_pairs:
      - ["Student", "Teacher"]
      key: backbone_out

PostProcess:
  name: DistillationCTCLabelDecode
  model_name: ["Student", "Teacher"]
  key: head_out

Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: f:/ocr/train_data_1_10/
    label_file_list:
    - f:/ocr/train_data_1_10/lable.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_sections: 1
    num_workers: 1
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: d:/ocr/test_data
    label_file_list:
    - d:/ocr/test_data/lable.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 1

报错信息：

8, loss_distance_l2_Student_Teacher_0: 0.029499, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.982143, reader_cost: 0.00019 s
, batch_cost: 0.10889 s, samples: 8000, ips: 73.47143
[2022/04/07 08:00:27] root INFO: epoch: [1/500], iter: 422000, lr: 0.000000, loss_ctc_Student_0: 0.531238, loss_ctc_Teacher_1: 0.561912, dml_0: 0.563106, loss: 1.77125
7, loss_distance_l2_Student_Teacher_0: 0.028898, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.984375, reader_cost: 0.00005 s
, batch_cost: 0.10737 s, samples: 8000, ips: 74.51122
[2022/04/07 08:02:33] root INFO: epoch: [1/500], iter: 423000, lr: 0.000000, loss_ctc_Student_0: 0.581576, loss_ctc_Teacher_1: 0.597240, dml_0: 0.567176, loss: 1.88431
3, loss_distance_l2_Student_Teacher_0: 0.028806, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.982143, reader_cost: 0.00005 s
, batch_cost: 0.10824 s, samples: 8000, ips: 73.90950
[2022/04/07 08:04:38] root INFO: epoch: [1/500], iter: 424000, lr: 0.000000, loss_ctc_Student_0: 0.578667, loss_ctc_Teacher_1: 0.599167, dml_0: 0.563281, loss: 1.81885
8, loss_distance_l2_Student_Teacher_0: 0.028980, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.982143, reader_cost: 0.00004 s
, batch_cost: 0.10794 s, samples: 8000, ips: 74.11458
[2022/04/07 08:06:44] root INFO: epoch: [1/500], iter: 425000, lr: 0.000000, loss_ctc_Student_0: 0.571042, loss_ctc_Teacher_1: 0.583254, dml_0: 0.580404, loss: 1.82788
0, loss_distance_l2_Student_Teacher_0: 0.028809, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.982143, reader_cost: 0.00011 s
, batch_cost: 0.10808 s, samples: 8000, ips: 74.01789
[2022/04/07 08:08:50] root INFO: epoch: [1/500], iter: 426000, lr: 0.000000, loss_ctc_Student_0: 0.559604, loss_ctc_Teacher_1: 0.576379, dml_0: 0.584321, loss: 1.80226
3, loss_distance_l2_Student_Teacher_0: 0.029074, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.984375, reader_cost: 0.00014 s
, batch_cost: 0.10919 s, samples: 8000, ips: 73.26901
[2022/04/07 08:10:57] root INFO: epoch: [1/500], iter: 427000, lr: 0.000000, loss_ctc_Student_0: 0.541681, loss_ctc_Teacher_1: 0.564152, dml_0: 0.563221, loss: 1.72886
2, loss_distance_l2_Student_Teacher_0: 0.028892, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.984375, reader_cost: 0.00016 s
, batch_cost: 0.10934 s, samples: 8000, ips: 73.16554
[2022/04/07 08:13:03] root INFO: epoch: [1/500], iter: 428000, lr: 0.000000, loss_ctc_Student_0: 0.567165, loss_ctc_Teacher_1: 0.590239, dml_0: 0.588632, loss: 1.80138
6, loss_distance_l2_Student_Teacher_0: 0.029260, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.984375, reader_cost: 0.00020 s
, batch_cost: 0.10855 s, samples: 8000, ips: 73.69740
[2022/04/07 08:15:08] root INFO: epoch: [1/500], iter: 429000, lr: 0.000000, loss_ctc_Student_0: 0.575116, loss_ctc_Teacher_1: 0.584420, dml_0: 0.568126, loss: 1.76735
6, loss_distance_l2_Student_Teacher_0: 0.028997, acc: 0.875000, norm_edit_dis: 0.984375, Teacher_acc: 0.875000, Teacher_norm_edit_dis: 0.984375, reader_cost: 0.00004 s
, batch_cost: 0.10808 s, samples: 8000, ips: 74.01963
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 106, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\work\projects\PaddleOCR\tools\program.py", line 224, in train
    avg_loss.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "D:\work\apps\Anaconda3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\work\apps\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "D:\work\apps\Anaconda3\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 248, in backward
    core.dygraph_run_backward([self], [grad_tensor], retain_graph,
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occ
ur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this ma
y indicate an internal error/bug in the library.  ] (at ..\paddle/fluid/operators/rnn_op.cu.cc:853)

**Comment by KunyiE1** [comment]
你好，我刚刚看到一个issue，把batch_size改成100后成功开始训练，我刚刚重新装了cudnn7.6.5并按照他的说法更改了batch_size成功开始训练了。

**Comment by dengmingD** [comment]
> 你好，我刚刚看到一个issue，把batch_size改成100后成功开始训练，我刚刚重新装了cudnn7.6.5并按照他的说法更改了batch_size成功开始训练了。

多谢，我试下
