### ISSUE TITLE
请问将来推理C++实现会考虑支持SAST检测模型和SRN识别模型吗？

### ISSUE THREAD

**Issue by llooper-dev** [PaddlePaddle/PaddleOCR#5906]
由于使用SAST加训出来的模型现没有办法在C++上编译使用，这块对普通用户来封装很有难度呢，是否可以提供支持呢？

请问将来推理C++实现会考虑支持SAST检测模型和SRN识别模型吗？

**Comment by MissPenguin** [comment]
由于人力有限，ppocr以外的算法的c++等推理部署方式，我们放到了[社区常规赛](https://github.com/PaddlePaddle/PaddleOCR/issues/4982)的第三类题型中，希望借助广大开发者的力量共同建设，但这个时间比较不可控了，可以持续关注。如果您这边进行了打通，非常欢迎提pr，合入后会在官网推广，还可以拿积分赢礼品哦🌹
