### ISSUE TITLE
在训练SDMGR模型时报错

### ISSUE THREAD

**Issue by ga546** [PaddlePaddle/PaddleOCR#5908]
用自己的数据集训练到第3个epoch时报错，报错信息如下
<img width="1034" alt="cffe188d06ee9a22709ee5a50585b15" src="https://user-images.githubusercontent.com/82253048/162207340-b1c5c97e-864c-4123-83e4-8a79921fcbc1.png">

**Comment by ga546** [comment]
solve it!

**Comment by xxx1996** [comment]
> 用自己的数据集训练到第3个纪元报错，报错信息如下 <img alt="cffe188d06ee9a22709ee5a50585b15" width="1034" src="https://user-images.githubusercontent.com/82253048/162207340-b1c5c97e-864c-4123-83e4-8a79921fcbc1.png">

您好，能说一下您怎么解决这个问题的么？我也遇到了这个问题。

**Comment by ga546** [comment]
忘了，时间久了，可能是数据集的原因

**Comment by yanziwu621** [comment]
请问SDMGR训练支持中文吗？我的数据集中有中文。是数据的复杂度不够吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 在训练SDMGR模型时报错 (Issue #5908)




 
忘了，时间久了，可能是数据集的原因

**Comment by ga546** [comment]
支持中文，效果不好的话可能是数据太少了吧

**Comment by ga546** [comment]
支持中文，效果不好的话可能是数据太少了吧

**Comment by yanziwu621** [comment]
找到问题了，谢谢大佬！

**Comment by phybrain** [comment]
> 找到问题了，谢谢大佬！

是什么问题啊，能说一下吗
