### ISSUE TITLE
2.4版本的最新错误，感觉是包有问题或者代码出错？

### ISSUE THREAD

**Issue by PHI6kai** [PaddlePaddle/PaddleOCR#5909]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：  PaddleOCR：2.4 问题相关组件/Related components：
- 运行指令/Command Code：
- python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/"
- 完整报错/Complete Error Message：
-Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 244, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 173, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 89, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "xxx\PaddleOCR-release-2.4\tools\infer\predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "xxx\PaddleOCR-release-2.4\ppocr\postprocess\rec_postprocess.py", line 91, in __call__
    preds = preds[-1]
IndexError: list index out of range

**Comment by JimReno** [comment]
我也遇到这个问题了，感觉是语言配置出了问题

**Comment by ltbupt** [comment]
同问

**Comment by jsylkn** [comment]
改成PaddleOCR-release-2.1就好了

**Comment by ltbupt** [comment]
> 

我改成2.1.0还是有这个问题

**Comment by jsylkn** [comment]
那我不知道了，我是python3.7   paddleocr2.4  一直出现这个问题，之后改成paddleocr2.1就好了
