### ISSUE TITLE
word wize detection only

### ISSUE THREAD

**Issue by yuvalshachaf** [PaddlePaddle/PaddleOCR#5910]
HI there,
Does anyone know how do I get the detection not to have a single bounding box on more than one word? basically i wish that I will have as many boxes as words rather than the whole sentence

**Comment by ashutosh486** [comment]
Hi,
Was this issue resolved? How to access word-wise bounding boxes?

**Comment by yuvalshachaf** [comment]
Yes thank you. I realized I had to change the model. Btw is there any way
to speed up the process?

**Comment by ashutosh486** [comment]
@yuvalshachaf I have just started working with OCR today so if I get any resolution for the above issue I will post it here.
btw, which model did you use for Recognition and detection?

**Comment by azhar0100** [comment]
Same question, what model did you use for detecting word boxes?
