### ISSUE TITLE
关于识别空格

### ISSUE THREAD

**Issue by KunyiE1** [PaddlePaddle/PaddleOCR#5911]
我是用paddle提供的识别数据合成工具发现合成工具并不能生成带空格的短语文本图像，如果我想训练可以识别空格的文本识别模型我应该到哪里获得带空格的英文文本图像数据集呢，我文本检测标注工具得到的识别数据好像都是长文本不适合训练。

**Comment by WenmuZhou** [comment]
这个我觉得改一下合成工具或者将空格加入合成工具的字典里就行了吧

**Comment by KunyiE1** [comment]
> 这个我觉得改一下合成工具或者将空格加入合成工具的字典里就行了吧

谢谢，我后面使用TextRecognitionDataGenerator得到了效果不错的带空格合成数据

**Comment by nissansz** [comment]
TextRecognitionDataGenerator 可以换背景，做到类似Style-Text那种效果吗？微信nlanguage
