### ISSUE TITLE
Paddle Serving C++ 部署 检测和识别串联模式怎么获取检测框位置信息

### ISSUE THREAD

**Issue by DequanZhu** [PaddlePaddle/PaddleOCR#5912]
Paddle Serving C++ 部署串联方式最后只有文字识别结果，中间检测框位置信息并没有返回，怎么修改才能获取该检测框位置信息呢？

**Comment by WenmuZhou** [comment]
目前已支持，可以拉取最新dygraph分支代码

**Comment by DequanZhu** [comment]
> 
 是C++方式部署也可以传回坐标信息吗，我看readme上[](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/pdserving/README_CN.md#C++)只有python方式会打印坐标信息，

**Comment by WenmuZhou** [comment]
是的

**Comment by DequanZhu** [comment]
> 



> 抱歉，我看错了，我确认下

现在是不支持吗

**Comment by DequanZhu** [comment]
作者你好，十分期待你的回复~
