### ISSUE TITLE
ImportError: cannot import name 'StructureSystem'

### ISSUE THREAD

**Issue by Adrian-Yan16** [PaddlePaddle/PaddleOCR#5917]
执行 ：python3 PPOCRLabel.py --lang ch
报错：
Traceback (most recent call last):
  File "PPOCRLabel.py", line 41, in <module>
    from paddleocr import PaddleOCR
  File "/home/aleilei/.local/lib/python3.6/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/home/aleilei/.local/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 42, in <module>
    from ppstructure.predict_system import StructureSystem, save_structure_res
ImportError: cannot import name 'StructureSystem'
我看了 2.3，2.2 的版本里面也都没有这个类或者函数

**Comment by Delay0123456789** [comment]
我也遇到这个问题了

**Comment by WenmuZhou** [comment]
已修复，拉最新dygraph代码试试

**Comment by DanLiu0623** [comment]
最新的dygraph分支遇到如下错误：
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1650247138 (unix time) try "date -d @1650247138" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002e58) received by PID 11864 (TID 0x7f9b5df20740) from PID 11864 ***]

**Comment by KHDOUDI** [comment]
Hello,

i have the same issue here, any idea on how to solve ? i have used the PPOCRLabel in other PC some months ago without issue:

`(base) C:\Users\IA\Desktop\New_Paddle\PaddleOCR-release-2.4\PaddleOCR-release-2.4\PPOCRLabel>python PPOCRLabel.py
C:\Users\IA\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Traceback (most recent call last):
  File "C:\Users\IA\Desktop\New_Paddle\PaddleOCR-release-2.4\PaddleOCR-release-2.4\PPOCRLabel\PPOCRLabel.py", line 41, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\IA\anaconda3\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Users\IA\anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 42, in <module>
    from ppstructure.predict_system import StructureSystem, save_structure_res
ImportError: cannot import name 'StructureSystem' from 'ppstructure.predict_system' (C:\Users\IA\Desktop\New_Paddle\PaddleOCR-release-2.4\PaddleOCR-release-2.4\PPOCRLabel\..\ppstructure\predict_system.py)`

**Comment by DanLiu0623** [comment]
> 最新的dygraph分支遇到如下错误： FatalError: `Process abort signal` is detected by the operating system. [TimeInfo: *** Aborted at 1650247138 (unix time) try "date -d @1650247138" if you are using GNU date ***] [SignalInfo: *** SIGABRT (@0x3e800002e58) received by PID 11864 (TID 0x7f9b5df20740) from PID 11864 ***]

问题已解决，使用dygraph分支代码，遇到上述错误，降低cv版本，从4.2版本到4.1.2.30，装了cudnn，解决了。

**Comment by enkhtogtokh** [comment]
Just replace "StructureSystem" with "OCRSystem". Seems they forgot to update in paddleocr.py  that like below: 
line 42: from ppstructure.predict_system import OCRSystem, save_structure_res 
line 401 : class PPStructure(OCRSystem):

**Comment by KHDOUDI** [comment]
> Just replace "StructureSystem" with "OCRSystem". Seems they forgot to update in paddleocr.py that like below: line 42: from ppstructure.predict_system import OCRSystem, save_structure_res line 401 : class PPStructure(OCRSystem):

Hello, Thank you very much, this solves the issue.
