### ISSUE TITLE
PaddleOCR2.3 内存泄露

### ISSUE THREAD

**Issue by JiahongWu1995** [PaddlePaddle/PaddleOCR#5918]
使用paddleocr训练模型，训练过程出现内存持续增加，直到提示shm不足，dataloader进行被强行kill
环境配置为：
python 3.7.10
ubuntu 18.04
paddle 2.1.1.post112
paddleocr 2.3
cuda 11.2

**Comment by WenmuZhou** [comment]
paddle使用2.2.2，代码使用dygraph分支看看

**Comment by JiahongWu1995** [comment]
谢谢 已解决
