### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by j-tyuan** [PaddlePaddle/PaddleOCR#5919]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./ch_PP-OCRv2_rec_infer/"
- 完整报错/Complete Error Message：
- [2022/04/08 10:40:02] root INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 400, in main
    rec_res, _ = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "/root/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 91, in __call__
    preds = preds[-1]
IndexError: list index out of range

**Comment by ltbupt** [comment]
我也遇到了这个问题，解决了吗

**Comment by jsylkn** [comment]
这个是版本问题，我之前用paddleocr2.4遇到这个问题，改成paddleocr2.1就好了。

**Comment by AIGirl10** [comment]
I am facing the same issue. Even after changing version python program doesn't work but paddleocr binary works, can anyone please help ?

**Comment by LDOUBLEV** [comment]
Please update your code. This bug has been fixed.
https://github.com/PaddlePaddle/PaddleOCR/blob/b8e7c6cef73df2547f4d635bf9eaaf7009fb854c/tools/infer/utility.py#L327-L329
