### ISSUE TITLE
预测时如何更好的支持超大分辨率的图片？

### ISSUE THREAD

**Issue by jaycecd** [PaddlePaddle/PaddleOCR#5921]
请问超大分辨率的图片（如2W*2W）在预测的时候：
1.是裁剪为边长=del_limit_side_len（默认值为960）的小图之后进行预测好？还是直接将del_limit_side_len设置为2W效果好一点？
2.del_limit_side_len没有上界，可以无限设置吗？如果是这样的话，图像分辨率和显存或内存的对应关系是怎样的？

**Comment by WenmuZhou** [comment]
图片越大，显存消耗越大，可以先看看设置resize之后的图片会不会变很模糊，不模糊的话，可以resize

**Comment by jaycecd** [comment]
> 图片越大，显存消耗越大，可以先看看设置resize之后的图片会不会变很模糊，不模糊的话，可以resize

请问resize后的图片怎么看呢？

**Comment by WenmuZhou** [comment]
存到本地

**Comment by jaycecd** [comment]
谢谢，顺便再问一下del_limit_side_len这个参数设置了之后，当图片长边的最大尺寸>del_limit_side_len时，会将图片的长边resize到del_limit_side_len，实际情况中大多数图片的分辨率应该是<del_limit_side_len的，而且这部分小尺寸图片的尺寸很可能大小不一。之前跑简单的CNN猫狗分类时，都需要将图片resize成一样的尺寸再进行预测，按del_limit_side_len的参数解释：
![image](https://user-images.githubusercontent.com/33342388/162629928-099f9735-f49e-44c5-9772-bbffb6f68e86.png)

意思是这部分小于del_limit_side_len且大小不一的图片是直接不做统一缩放就去预测吗？

**Comment by Gmgge** [comment]
1.如你所说，最长边小于该参数时，不做resize操作。
2.有的网络是固定尺寸输入的，所以需要你把图片resize成相同大小，这一情况取决于网络的设定，通常来说分类和目标检测网络使用这一设置。当前paddleocr主推的dbnet文本检测，使用基于语义分割的文本检测，并不需要固定尺寸。

**Comment by jaycecd** [comment]
> 1.如你所说，最长边小于该参数时，不做resize操作。 2.有的网络是固定尺寸输入的，所以需要你把图片resize成相同大小，这一情况取决于网络的设定，通常来说分类和目标检测网络使用这一设置。当前paddleocr主推的dbnet文本检测，使用基于语义分割的文本检测，并不需要固定尺寸。

谢谢回复，那如果是这样的话，其实在显存（对应GPU）或内存（对应CPU）允许的情况下，del_limit_side_len的值设置的越大越好，因为这样就会使用原始的图片分辨率进行预测，减少了resize的时间开销和可能发生变形的几率，那pdocr有没有自动设置del_limit_side_len的功能呢？比如检测到显存或内存的大小，直接设置为该硬件条件下del_limit_side_len的最大值（即允许的最大分辨率）。

**Comment by Gmgge** [comment]
据我了解，目前是并不存在这种自动设置的。
