### ISSUE TITLE
训练过程报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 51: invalid start byte

### ISSUE THREAD

**Issue by KunyiE1** [PaddlePaddle/PaddleOCR#5922]
请问这个编码错误是什么造成的呢，具体报错信息如图。
![微信截图_20220408223027](https://user-images.githubusercontent.com/96457981/162457696-19245f26-fcf2-4fbc-9560-7fbce19c00e7.png)

**Comment by KunyiE1** [comment]
我将标签文本的编码改成utf8后好像得到解决了

**Comment by WenmuZhou** [comment]
你的标注是utf8格式的吗

**Comment by KunyiE1** [comment]
> 

我刚刚更改了，谢谢

**Comment by KunyiE1** [comment]
> 你的标注是utf8格式的吗

刚刚改过来了，谢谢
