### ISSUE TITLE
Android Demo内使用的模型，怎么让其增加识别维吾尔语？急！！！

### ISSUE THREAD

**Issue by guoge6** [PaddlePaddle/PaddleOCR#5924]

**Comment by littletomatodonkey** [comment]
你好，需要使用维吾尔语的模型替换成当前的中英文识别模型，然后重新置顶下维吾尔语的字典即可，可以去多语言的文档里找下对应的识别模型

**Comment by guoge6** [comment]
> 你好，需要使用维吾尔语的模型替换成当前的中英文识别模型，然后重新置顶下维吾尔语的字典即可，可以去多语言的文档里找下对应的识别模型

我想在中英文识别模型上加

**Comment by dlml** [comment]
目前放的模型识别率很差

**Comment by Zurichcape** [comment]
> > 你好，需要使用维吾尔语的模型替换成当前的中英文识别模型，然后重新置顶下维吾尔语的字典即可，可以去多语言的文档里找下对应的识别模型
> 
> 我想在中英文识别模型上加

那只能自己训练多语种的模型，没有现成的

**Comment by guoge6** [comment]
哦哦，谢谢了，目前没这个水平，哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] Android Demo内使用的模型，怎么让其增加识别维吾尔语？急！！！ (Issue #5924)





   
你好，需要使用维吾尔语的模型替换成当前的中英文识别模型，然后重新置顶下维吾尔语的字典即可，可以去多语言的文档里找下对应的识别模型
  
我想在中英文识别模型上加
  
那只能自己训练多语种的模型，没有现成的
