### ISSUE TITLE
模型形状未知

### ISSUE THREAD

**Issue by Hadesong** [PaddlePaddle/PaddleOCR#5925]
训练好了一个dbnet模型,替换PaddleOCR/ deploy / android_demo / app中的检测模型后运行程序闪退

查看模型结构后发现全是问号..
nb模型
![12](https://user-images.githubusercontent.com/3585444/162565647-402be771-41e7-4dfd-9506-229942937f8d.png)
inference.pdmodel(aistudio平台可以正常预测)
![屏幕截图 2022-04-09 172445](https://user-images.githubusercontent.com/3585444/162565726-e4976cbc-58a8-4d86-9870-0635d5139fcd.png)

nb链接：https://pan.baidu.com/s/1YxtdJy5kCiEDmAr9-BySAg 
提取码：rjd2

**Comment by littletomatodonkey** [comment]
因为导出的时候，batch size是-1（第一个问号），表示可以为任意值，第三个和第四个问号是图像的长和宽，也可以为任意值
