### ISSUE TITLE
请问文本检测模型评估时IoU的阈值默认设置为多少

### ISSUE THREAD

**Issue by KunyiE1** [PaddlePaddle/PaddleOCR#5928]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
0.5

**Comment by KunyiE1** [comment]
> 0.5

请问在哪里可以更改这个阈值呢，我找了一下没有找到

**Comment by MissPenguin** [comment]
这里的默认参数：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/metrics/eval_det_iou.py#L13

**Comment by KunyiE1** [comment]
> 这里的默认参数：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppocr/metrics/eval_det_iou.py#L13

好的谢谢
