### ISSUE TITLE
Confidence of all output chars

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#5932]
Hi thank you all for your great job.
Is It possible to get confidence of each character (not average of all chars) in output ?

**Comment by LDOUBLEV** [comment]
Hi, U can get the confidence of each character only if modify code to 'result_list.append((text, conf_list))'. 

https://github.com/PaddlePaddle/PaddleOCR/blob/e4600832539907c42c3390aa92b7e3923bf6595c/ppocr/postprocess/rec_postprocess.py#L74

**Comment by centurions** [comment]
Hi , thank you

**Comment by kanis777** [comment]
hi @LDOUBLEV .So , I tried this approach but if i do that and try to print the confidence of each character , I am getting an error of 

```
Exception has occurred: TypeError
'>=' not supported between instances of 'list' and 'float'
  File "D:\Yavar\number_plate\yolov8\yolov8_final.py", line 103, in <module>
    ocr_results = ocr_paddle.ocr(gray_image, cls=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'list' and 'float'
```

Should I change anything else in my py file ( the errors occurs on )
```ocr_results = ocr_paddle.ocr(gray_image, cls=True)```
