### ISSUE TITLE
短文本(单个字符)识别问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#5935]
一些字符例如"出"，"㎡"等字符，如果是在一个长的文本中（5个字符以上），识别模型识别的很好，但是如果只是单个字符则识别很差。例如图片中只有"㎡"这一个字符，我测试官方的识别模型就不能识别出来，会识别成"m"，而且阈值很低只有0.5-0.6，但如果是包含在一个长文本中，例如图片中文本是"总共多少㎡呢？"，则能够很好的识别出"㎡"。

我自己训练出来的模型也存在这种情况，短文本识别不好，一些"出"，"㎡"的单个字符图片情况识别很差，如果是包含在"今天你要出去吗？"，"总共多少㎡呢？"这样的长文本图片中又能识别的很好。但是一些常见的字符比如"我"，"是"，"你"这样的单个字符图片在单个字符图片情况下也能识别的很好。

猜测可能是形近字符的原因，有用到centerloss训练，但是效果不理想。请问这可能是什么原因呢?怎样提高识别模型对单个字符（短文本）图片的识别效果精度呢？

**Comment by nissansz** [comment]
有办法解决了吗？

**Comment by mengyuan224** [comment]
有解决方法吗
