### ISSUE TITLE
新版本报‘ list index out of range’的错误

### ISSUE THREAD

**Issue by heguodui** [PaddlePaddle/PaddleOCR#5937]
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 249, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 176, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 90, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/data/heguodui/code/code/PaddleOCR/tools/infer/predict_rec.py", line 370, in __call__
    rec_result = self.postprocess_op(preds)
  File "/data/heguodui/code/code/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 91, in __call__
    preds = preds[-1]
IndexError: list index out of range

**Comment by 0604hx** [comment]
同样碰到此问题。
我是在 docker 环境下运行，环境信息如下：
paddle 2.2.2
PaddleOCR 2.4
docker-ce 20.10.12
操作系统 Centos 7.9

目前我的解决方案是将 PaddleOCR 换成 2.1.1 版本，运行正常。
期待官方给出 2.4 的方案，感谢

**Comment by zjj421** [comment]
同样问题，release/2.4版本，“Paddle2ONNX模型转化与预测”Demo示例跑不通，且onnxruntime gpu运行速度没有提升。

以下命令正常运行：
python3.7 tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
--det_model_dir=./inference/det_onnx/model.onnx  \
--rec_model_dir=./inference/rec_onnx/model.onnx  \
--cls_model_dir=./inference/cls_onnx/model.onnx  \
--image_dir=./deploy/lite/imgs/lite_demo.png

以下命令运行报错（release/2.4版本文本识别模型获取不到识别结果）：
python3.7 tools/infer/predict_system.py --use_gpu=False \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer \
--rec_model_dir=./inference/ch_PP-OCRv2_rec_infer \
--det_model_dir=./inference/ch_PP-OCRv2_det_infer \
--image_dir=./deploy/lite/imgs/lite_demo.png

相关版本：
paddele: 2.2.2
系统：ubuntu 20.04
cuda: 10.2
cudnn: 7.6.5

**Comment by weirman** [comment]
@WenmuZhou 测试发现在https://github.com/PaddlePaddle/PaddleOCR/commit/633d0552851d41ae77c2f28ba83fda350648c341
合并中，文件tools/infer/utility.py 中的get_output_tensors 方法修改引入了bug，使用识别模型时，返回的output_tensors是空的。和output_name有关，直接回退回去或者修改成正确的output_name应该就行了，但是觉得还是回退回去的好。
**大家拿去救急修改文件tools/infer/utility.py 中的get_output_tensors 方法为：**
```python
def get_output_tensors(args, mode, predictor):
    output_names = predictor.get_output_names()
    output_tensors = []
    
    for output_name in output_names:
        output_tensor = predictor.get_output_handle(output_name)
        output_tensors.append(output_tensor)
    return output_tensors
```

**Comment by UncleLLD** [comment]
mark
