### ISSUE TITLE
LayoutXLM Relation Extraction Base Model for XFUN Chinese dataset

### ISSUE THREAD

**Issue by ilovecv** [PaddlePaddle/PaddleOCR#5943]
Hi, 

Thanks for sharing the great works! 
I tried the LayoutXLM relation extraction model on XFUN Chinese dataset. I was able to get 71% F1 score with the shared model weight. However, when I run visualizations on the val dataset, I found the prediction results were different from the results shown in this github. 

For example, the left side is the prediction result:
![Screen Shot 2022-04-11 at 3 31 20 PM](https://user-images.githubusercontent.com/11083384/162843988-d5b726dd-8dff-4104-bf8a-d1bb07cb6402.png)

and this is the result from the github:
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/ppstructure/vqa/images/result_re/zh_val_21_re.jpg

**Comment by WenmuZhou** [comment]
Please reason with the code from the dygraph branch, I just tested it and the result is the same.
Compared with the 2.4 branch code, dygraph has undergone major changes, and it will be dominated by the dygraph branch.

**Comment by ilovecv** [comment]
Hi, 

I just checked the dygraph branch and run the inference codes again. However, the results were not improved.

This is the command I run:
python3 infer_re.py \
    --model_name_or_path "PP-Layout_v1.0_re_pretrained/" \
    --max_seq_length 512 \
    --eval_data_dir "XFUND/zh_val/image" \
    --eval_label_path "XFUND/zh_val/xfun_normalize_val.json" \
    --label_map_path "labels/labels_ser.txt" \
    --output_dir "output/re/"  \
    --per_gpu_eval_batch_size 1 \
    --seed 2048

I download the checkpoint [here](https://paddleocr.bj.bcebos.com/pplayout/PP-Layout_v1.0_re_pretrained.tar)
paddlepaddle-gpu version is 2.2.0

**Comment by WenmuZhou** [comment]
From your command, the code you use is not the latest dygraph branch. In the latest code, I refactor the VQA code

**Comment by ilovecv** [comment]
Got it, I will check the codes again. 
Meanwhile, could you please share your command to run the inference?
Thank you very much!

**Comment by WenmuZhou** [comment]
my command is 
```bash
python3 tools/infer_vqa_token_ser_re.py -c configs/vqa/re/layoutxlm.yml -o Architecture.Backbone.checkpoints=pretrain/re_LayoutXLM_xfun_zh/Global.infer_img=doc/vqa/input/zh_val_21.jpg -c_ser configs/vqa/ser/layoutxlm. yml -o_ser Architecture.Backbone.checkpoints=pretrain/ser_LayoutXLM_xfun_zh/
```
