### ISSUE TITLE
怎样获得按正确率排序的一个图的多种可能结果？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#5944]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
怎样获得按正确率排序的一个图的多种可能结果？微信nlanguage

**Comment by andyjpaddle** [comment]
不是很明白，能详细描述一下你的问题吗？

**Comment by andyjpaddle** [comment]
目前没有提供，可以自己根据需要进行改写哈

**Comment by nissansz** [comment]
是在哪个py文件里？
