### ISSUE TITLE
  在OCR推理过程中，为啥先要 warm up 10 times？

### ISSUE THREAD

**Issue by zgwg** [PaddlePaddle/PaddleOCR#5945]
在OCR推理过程中，为啥先要 warm up 10 times？？
   # warm up 10 times
    if args.warmup:
        img = np.random.uniform(0, 255, [640, 640, 3]).astype(np.uint8)
        for i in range(10):
            res = text_sys(img)

**Comment by andyjpaddle** [comment]
这样可以先初始化推理，后续推理会快一些
