### ISSUE TITLE
检测模型训练后识别效果很好，但是export出模型后识别很多检测不出来

### ISSUE THREAD

**Issue by kainer80** [PaddlePaddle/PaddleOCR#5946]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.3
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by kainer80** [comment]
另外，训练的时候elva这个设置
     - DetResizeForTest:
          image_shape: [736, 1280]
更改有什么作用吗？我们自己的图片尺寸基本上都是固定的，且不超过640，能把这个地方调小吗？

**Comment by andyjpaddle** [comment]
shape根据自己的数据集进行修改就好
