### ISSUE TITLE
如何对模型进行加密？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/PaddleOCR#5949]
有没有办法对训练出来的模型进行加密呢？如果没有的话，以后是否打算支持呢？训练好的模型，如果没有加密的话，很容易被其他人拿去直接使用。

**Comment by hbulaoma** [comment]
这个得看paddle 有没有内存加载模型的接口。如果有就可以对模型文件加密，读取到内存后，解密再用内存接口装载；如果没有估计就悬了。这个问题其实挺关键的，不然辛苦训练的模型可以随意被别人使用了

**Comment by wzy123456wzy** [comment]
> 这个得看paddle 有没有内存加载模型的接口。如果有就可以对模型文件加密，读取到内存后，解密再用内存接口装载；如果没有估计就悬了。这个问题其实挺关键的，不然辛苦训练的模型可以随意被别人使用了

paddlex是有模型加密的，但是没有PaddleOCR套件，这个确实挺关键的

**Comment by MrWwei** [comment]
可以用SetModelBuffer从内存加载模型
