### ISSUE TITLE
sast算法的后处理太慢了,这样的话推理效率太低了,期待改进

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/PaddleOCR#5958]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 8
- 版本号/Version：Paddle：2.2gpu  PaddleOCR：2.4 问题相关组件/Related components：sast_process.py
- 运行指令/Command Code：eval阶段的后处理
- 完整报错/Complete Error Message：
- 平均一张图片评估需要3.3秒,且无法并行,查看了一下资源,纯在cpu上跑,且cpu的利用率100%,无法利用多核能力.我测试了一个利用多核能力的python程序,cpu的利用率可以达到1000%.所以有三个思路:
- 1,能否后处理在GPU上跑?
- 2,不能GPU化,能否提升cpu的利用率,增加多核并行能力?
- 3,以上都不行,能否增加eval阶段,可以将batchsize增大到N,而非现在的必须是1,即可以批量推理???

**Comment by cgyeon-muhayu** [comment]
I'm having the same problem.
Is this solved?

**Comment by zzk2021** [comment]
east也好慢，除了db都慢。。
