### ISSUE TITLE
docker体积太大怎么办

### ISSUE THREAD

**Issue by littleforce163** [PaddlePaddle/PaddleOCR#596]
不论cpu还是gpu，docker体积都很大，cpu的大约9.6GB，有什么办法把docker体积搞得小点？

**Comment by LDOUBLEV** [comment]
感谢使用和关注，docker 中包含的有cuda和cudnn等，还有其他环境，所以封装的比较大。请问你遇到的问题是？是下载太慢吗还是docker部署时这个文件太大了。

**Comment by littleforce163** [comment]
cpu版本的也很大，9.6GB，部署时很占磁盘，低配机器一共20GB硬盘，跑不起来..
对比以前tensorflow项目，docker GPU版本大约1个多GB，当然不包含cuda那些，如果是CPU版本，不到1GB。
docker image下载还是蛮快的，百度服务器不错。
