### ISSUE TITLE
【内存泄露】C++部署开启mkldnn内存会持续增加，开启EnableMemoryOptim也无效

### ISSUE THREAD

**Issue by JoyshowXia** [PaddlePaddle/PaddleOCR#5965]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
请问使用的代码是dygraph分支的吗

**Comment by JoyshowXia** [comment]
> 请问使用的代码是dygraph分支的吗

develop分支

**Comment by WenmuZhou** [comment]
目前建议使用dygraph分支，develop分支已经不维护了
