### ISSUE TITLE
[Bug] Shared output causes issue when converting to CoreML model

### ISSUE THREAD

**Issue by franva** [PaddlePaddle/PaddleOCR#5968]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

I am doing the Baidu Hackathon Task 85 which asks for converting Paddle model to CoreML model.

After converting the OCR Rec model to CoreML model, open the CoreML model with XCode, it will show:
![rec_err](https://user-images.githubusercontent.com/5151146/163318699-187c9ab3-7dea-4a8f-8414-73a14cd9d14c.png)

- 系统环境/System Environment：
Converting OS:  Ubuntu 20.04
MacOS: 10.15.7
Coremltools: 5.2.0
XCode: 12.4

- 版本号/Version：Paddle： 2.2.2,  PaddleOCR： release/2.4
- Model: ch_PP-OCRv2_rec_infer from https://github.com/PaddlePaddle/Paddle2ONNX/tree/model_zoo/model_zoo/ocr
- 运行指令/Command Code：
1. download the ONNX format from [this page](https://github.com/PaddlePaddle/Paddle2ONNX/tree/model_zoo/model_zoo/ocr)
2. Run the [Shape_infer.py](https://github.com/PaddlePaddle/Paddle2ONNX/blob/model_zoo/hardwares/coreml/shape_infer.py) to fix the input and output
`python shape_infer.py --input rec.onnx --output rec_of.onnx`

You can download the [rec_of.onnx model here](https://1drv.ms/u/s!Asflam6BEzhjgbM_2Z0QQkQ-nUYQhQ?e=Dhf6EV)

3. Convert the model to CoreML format by:

```
from pathlib import Path
import coremltools as ct
root = Path(__file__).parent

model = ct.converters.onnx.convert(
    model = "/media/winstonfan/Workspace/Work/Baidu/Hackathon2022/Models/ch_PP-OCRv2_rec_infer/rec_sim_fo.onnx",
    minimum_ios_deployment_target = '13',
    image_input_names= ["x"]
)
saved_model_path = root.parent / "output/ocr_rec"
model.save(saved_model_path)
```

Here is the [rec.mlmodel](https://1drv.ms/u/s!Asflam6BEzhjgbNABqldy6AXX4MuNQ?e=aOK12A) in CoreML format.

After reviewing the model, I can see that there are more than 1 output called `Slice_14_expand_out_h_0`. This is the cause of this issue and CoreML does not support duplicated node naming.

![image](https://user-images.githubusercontent.com/5151146/163323851-f67a9998-6b21-4930-8b18-011d392e1ced.png)

So my suggestion is: the easiest fix to this issue is to rename these output nodes which have same names e.g.
`Slice_14_expand_out_h_0` and `Slice_14_expand_out_h_1`

**Comment by WenmuZhou** [comment]
I got an error in the third step here. model is downloaded from https://bj.bcebos.com/paddle2onnx/model_zoo/ch_PP-OCRv2_rec_infer.onnx

```bash
Traceback (most recent call last):
  File "convert2coreml.py", line 15, in <module>
    model = convert(
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/models/_deprecation.py", line 30, in wrapped
    return obj(*args, **kwargs)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/converters/onnx/_converter.py", line 621, in convert
    graph = _prepare_onnx_graph(onnx_model.graph, transformers, onnx_model.ir_version)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/converters/onnx/_converter.py", line 465, in _prepare_onnx_graph
    graph_ = graph_.transformed(transformers)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/converters/onnx/_graph.py", line 228, in transformed
    return _apply_graph_transformations(graph, transformers)  # type: ignore
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/converters/onnx/_graph.py", line 69, in _apply_graph_transformations
    graph = transformer(graph)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/coremltools/converters/onnx/_transformers.py", line 826, in __call__
    ends = node.attrs["ends"]
KeyError: 'ends'
```

**Comment by WenmuZhou** [comment]
I get an error when I execute the third step
```bash
Traceback (most recent call last):
  File "shape_infer.py", line 2116, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(onnx.load(args.input), args.int_max, args.auto_merge,
  File "shape_infer.py", line 2080, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "shape_infer.py", line 1909, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "shape_infer.py", line 1301, in _infer_Reshape
    assert new_sympy_shape.count(-1) < 2
AssertionError
```

**Comment by franva** [comment]
> I get an error when I execute the third step
> 
> ```shell
> Traceback (most recent call last):
>   File "shape_infer.py", line 2116, in <module>
>     out_mp = SymbolicShapeInference.infer_shapes(onnx.load(args.input), args.int_max, args.auto_merge,
>   File "shape_infer.py", line 2080, in infer_shapes
>     all_shapes_inferred = symbolic_shape_inference._infer_impl()
>   File "shape_infer.py", line 1909, in _infer_impl
>     self.dispatcher_[node.op_type](node)
>   File "shape_infer.py", line 1301, in _infer_Reshape
>     assert new_sympy_shape.count(-1) < 2
> AssertionError
> ```

This error is likely caused by converting dynamic shape model directly. 
So the solution is to fix the input shape before you use shape_infer.py.
Hope it helps.

Cheers

**Comment by franva** [comment]
> I get an error when I execute the third step
> 
> ```shell
> Traceback (most recent call last):
>   File "shape_infer.py", line 2116, in <module>
>     out_mp = SymbolicShapeInference.infer_shapes(onnx.load(args.input), args.int_max, args.auto_merge,
>   File "shape_infer.py", line 2080, in infer_shapes
>     all_shapes_inferred = symbolic_shape_inference._infer_impl()
>   File "shape_infer.py", line 1909, in _infer_impl
>     self.dispatcher_[node.op_type](node)
>   File "shape_infer.py", line 1301, in _infer_Reshape
>     assert new_sympy_shape.count(-1) < 2
> AssertionError
> ```

Also the 3rd step is to convert ONNX to CoreML model, but your error message shows something related to shape_infer.py

If you could show what exactly you did step by step, I could give you better explanation.

**Comment by WenmuZhou** [comment]
my steps is:
1. wget wget https://bj.bcebos.com/paddle2onnx/model_zoo/ch_PP-OCRv2_rec_infer.onnx
2. python shape_infer.py --input ch_PP-OCRv2_rec_infer.onnx --output ocr_rec.onnx

**Comment by franva** [comment]
> my steps is:
> 
>     1. wget wget https://bj.bcebos.com/paddle2onnx/model_zoo/ch_PP-OCRv2_rec_infer.onnx
> 
>     2. python shape_infer.py --input ch_PP-OCRv2_rec_infer.onnx --output ocr_rec.onnx

This is exactly what I expected to see.

the model you downloaded has dynamic shape which is the cause of this error.

Use Paddle2Onnx to fix the input shape of the onnx and than use the `shape_infer.py`, this is how to fix the issue you are facing.

Cheers

**Comment by WenmuZhou** [comment]
Do you mean that I need to fix the shape when I convert the model to the onnx model?

**Comment by franva** [comment]
> Do you mean that I need to fix the shape when I convert the model to the onnx model?

Correct.

**Comment by WenmuZhou** [comment]
after fix input shape to 1,3,32,320, I meet this
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/12406017/163550689-0a5e3ed9-778b-410e-a589-3a2a2cf6491c.png">

**Comment by franva** [comment]
@WenmuZhou 
Sorry for the late reply, I was on a holiday.
Could you please share the command you used for converting?
