### ISSUE TITLE
use paddle_inference.dll Does the cpu need to support the avx or avx2 instruction set?

### ISSUE THREAD

**Issue by kangshilei** [PaddlePaddle/PaddleOCR#5969]
![image](https://user-images.githubusercontent.com/87765811/163354223-1e955815-ee90-4540-aecb-a9ffbfc9e39b.png)
![image](https://user-images.githubusercontent.com/87765811/163354265-dd29c04b-9492-4140-a110-cceab5838c43.png)
![image](https://user-images.githubusercontent.com/87765811/163354403-6cfac486-d9a8-45e1-9b7c-56cb009aa67f.png)
![image](https://user-images.githubusercontent.com/87765811/163354468-d8b2d7a4-ce5d-4ade-9ed2-ab7fe551aa23.png)
第四张图我看有avx的字眼。是不是要依赖这个avx指令集才能运行啊。我的电脑没有 这个avx这个指令集，然后就崩溃了
这个是因为我的cpu不支持avx或者avx2指令集 的原因吗？

**Comment by WenmuZhou** [comment]
你需要使用noavx的预测库

**Comment by kangshilei** [comment]
> 你需要使用 noavx 的预测库

这个去哪里找。我下载的是https://www.paddlepaddle.org.cn/documentation/docs/en/2.0/guides/05_inference_deployment/inference/windows_cpp_inference_en.html这个上面的 
![image](https://user-images.githubusercontent.com/87765811/163741796-bd53cd21-9ba3-41b3-959c-52d3b3d91508.png)
没看到不带avx的下载连接

**Comment by WenmuZhou** [comment]
可能需要自己编译一下
