### ISSUE TITLE
对于大图32的高度不够，如果训练图像高度增大到48或者64该如何修改网络

### ISSUE THREAD

**Issue by yulinxuanzhi** [PaddlePaddle/PaddleOCR#597]

**Comment by LDOUBLEV** [comment]
只需要修改配置文件里的Global.image_shape 即可，如果要修改为64，只需要改为[3, 64, 640]，640 是图像的长度，640 可能会导致识别速度过慢，可以改小一些
![image](https://user-images.githubusercontent.com/26592129/91015188-52741200-e61d-11ea-8706-ac1e83cd6ff5.png)
