### ISSUE TITLE
表格识别配置文件解释

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#5971]
1、请问表格识别命令中table_char_dict_path和rec_char_dict_path作用分别是什么
2、我要训练自己的中文表格结构识别，配置文件table_mv3.yml中的table_char_dict_path应该怎么改

**Comment by littletomatodonkey** [comment]
1. table识别的时候，只用配置这个即可：https://github.com/PaddlePaddle/PaddleOCR/blob/5140907d7c673a82ef6e606d10828a23e2269d12/configs/table/table_mv3.yml#L17
2. 可以看下动手学ocr10讲中的第六章内容：https://aistudio.baidu.com/aistudio/course/introduce/25207

**Comment by wjrjsdx** [comment]
> 1. table识别的时候，只用配置这个即可：https://github.com/PaddlePaddle/PaddleOCR/blob/5140907d7c673a82ef6e606d10828a23e2269d12/configs/table/table_mv3.yml#L17
> 2. 可以看下动手学ocr10讲中的第六章内容：https://aistudio.baidu.com/aistudio/course/introduce/25207

请问我可以制作自己的中文表格标签时，只管表格结构不管具体中文文本内容吗，我看数据pubtab数据都是有具体文本和表格结构两部分的标注，我现在不需要检测具体文本，只需要检测表格结构。
