### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by JamesHuang77** [PaddlePaddle/PaddleOCR#5972]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，麻烦再补充一些具体信息，谢谢
