### ISSUE TITLE
paddleseg量化后为静态模型，转onnx时报错

### ISSUE THREAD

**Issue by Leonerist** [PaddlePaddle/PaddleOCR#5973]
There's 2 ops are not supported yet
=========== fake_quantize_dequantize_moving_average_abs_max ===========
=========== fake_channel_wise_quantize_dequantize_abs_max ===========

**Comment by littletomatodonkey** [comment]
你好，可以使用最新的paddle2onnx试下哈

**Comment by szNightFury** [comment]
> 

最新是0.9.3吗？我试过还是不行

**Comment by MissPenguin** [comment]
paddleseg？那最好去paddleseg的repo提下issue哈
