### ISSUE TITLE
PPOCRLabel运行MKLML.dll报错

### ISSUE THREAD

**Issue by gxw59327** [PaddlePaddle/PaddleOCR#5974]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10 家庭版
- 版本号/Version：Paddle：版本2.2  PaddleOCR：版本2.4  
- 运行指令/Command Code：ppocrlabel --lang ch
- 完整报错/Complete Error Message：
![1650096635(1)](https://user-images.githubusercontent.com/20594436/163667591-abc7ea3b-ffe5-4f0f-9d49-12ea9cc379cc.png)

**Comment by Evezerest** [comment]
你好，请问在命令行能够成功执行paddleocr whl包的内容么？

**Comment by JoyshowXia** [comment]
貌似是paddle_inference.dll和mklml.dll版本不一致导致的吧
