### ISSUE TITLE
ch_PP-OCRv2模型精度没有ch_ppocr_mobile_v2.0高

### ISSUE THREAD

**Issue by stoneLee81** [PaddlePaddle/PaddleOCR#5976]
测试对比了一下二类模型的进度，ch_PP-OCRv2模型精度没有ch_ppocr_mobile_v2.0高？

**Comment by MissPenguin** [comment]
ch_PP-OCRv2是在我们自己的评估集上验证比ch_ppocr_mobile_v2.0有几个点的提升，我们的评估集确实无法覆盖到所有场景，所以你说的情况确实有可能出现。可以描述一下具体的场景、给几个示例嘛？我们在后续优化时好重点关注

**Comment by stoneLee81** [comment]
python3 tools/infer/predict_system.py --image_dir="../python/data/test02.jpg" --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/"
![test03_server_inf](https://user-images.githubusercontent.com/18001708/163818583-8138aced-c455-4a45-885c-8ac5b1906eb4.jpg)

python3 tools/infer/predict_system.py --image_dir="../python/data/test02.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/"
![test03_mobile_inf](https://user-images.githubusercontent.com/18001708/163818599-c55b6f73-38aa-468c-9e9e-04e484f6dcb7.jpg)

python3 tools/infer/predict_system.py --image_dir="../python/data/test02.jpg" --det_model_dir="./inference/ch_PP-OCRv2_det_infer/"  --rec_model_dir="./inference/ch_PP-OCRv2_rec_infer/"
![test03_OCRv2_inf](https://user-images.githubusercontent.com/18001708/163818616-11672108-5608-43e4-9e72-fb769defbbbf.jpg)

server的rec&dec是最好的，PP_OCRv2探知和识别都有比较大的问题，测试的图片
![B1934B4FE1BF4BC38F14621E554CFD41](https://user-images.githubusercontent.com/18001708/163818730-93e7c9b1-017d-4010-a31f-086d26767cbb.jpeg)

**Comment by stoneLee81** [comment]
paddleOCR v2.4-release 版本

**Comment by stoneLee81** [comment]
@MissPenguin 有什么建议么？

**Comment by MissPenguin** [comment]
训练集中这种卡证数据并不多，所以效果比较容易波动，建议标一批数据finetune（可以用PPOCRLabel进行标注）。先试试标个100~200张finetune下检测模型。
