### ISSUE TITLE
PPOCR和Pytorch的共用问题

### ISSUE THREAD

**Issue by Mr-AE** [PaddlePaddle/PaddleOCR#5977]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux（ubuntu）
- 版本号/Version：Paddle：PaddlePaddle2.2.2.post101  PaddleOCR：2.4.0.4
- 运行指令/Command Code：参考文档的快速开始的python推理脚本
- 完整报错/Complete Error Message：Intel MKL function load error: cpu specific dynamic library is not loaded

实验室工作需要一个OCR识别的部分，之前已经单独建立过一个paddle+paddleocr的环境（简称：环境1），完成了ocr代码测试，现在想把这一块整合进project中，大的project的环境使用了pytorch的框架（环境2），现在在环境2中安装了paddle和paddleocr（和构建环境一样的流程）之后运行推理代码会报错：Intel MKL function load error: cpu specific dynamic library is not loaded

 查看了paddle repo的其他issue，发现这个报错似乎是numpy版本的问题

于是做了一些简单测试
1. 参考快速开始文档，写了一个简单的推理脚本，使用环境1运行成功
2. 推理脚本用环境2运行会报上述错误
3. 将环境2的numpy uninstall之后，换成numpy1.19.1，运行测试脚本可以成功

但是把numpy uninstall之后，环境2中的pytorch也没有了，尝试重新安装pytorch，发现现在安装的pytorch匹配的都是numpy1.21.5了，难道说paddle和pytorch框架无法兼容吗

然后我又自己查看了一下自己环境1的numpy，发现也是1.21.5的版本，但是并不影响这个环境可以正常运行

所以我想请教一下：
1. Paddle和Pytorch框架可以在同一个环境下兼容共用吗 ？
2. 如果可以的话，究竟是什么问题导致的这个报错呢？我有什么应对手段呢？因为感觉PPOCR确实比我对比的另一个ocr框架好用，所以还是尽可能想解决这个问题，在实验中用上

**Comment by LDOUBLEV** [comment]
你的环境1、环境2 的硬件环境是一样的吗？cpu是什么型号的？

**Comment by LDOUBLEV** [comment]
如果你在PaddleOCR微信交流群里，可以@LDOUBLEV ;

我的环境上安装numpy1.21.5 cpu预测也没报错

**Comment by yjhtc007** [comment]
可以尝试把paddle模型转成onnx模型再进行部署，或者把paddle模型转成pytorch的，不过精度可能会有一点点损失。

**Comment by Mr-AE** [comment]
> 你的环境1、环境2 的硬件环境是一样的吗？cpu是什么型号的？

感谢您的回复！！！环境1、2是在同一台机器上运行的
我昨天晚上最后找到原因了，我的paddle是使用pip安装的，pytorch是好久之前使用conda安装的；当我把环境2中的pytorch uninstall之后又换用pip安装上，就可以正常运行了；
不过还有点疑惑的是，这个报错之所以出现，是因为conda安装时候捆版安装的numpy版本无法适配paddlepaddle吗？
