### ISSUE TITLE
SAR文本识别算法推理模型准确问题

### ISSUE THREAD

**Issue by frotms** [PaddlePaddle/PaddleOCR#5979]
先将SAR [trained model](https://paddleocr.bj.bcebos.com/dygraph_v2.1/rec/rec_r31_sar_train.tar)转换为inference model，使用如下推理命令：

`python ./tools/infer/predict_rec.py --use_gpu false --rec_algorithm SAR --rec_model_dir ../rec_models/rec_r31_sar/rec_r31_sar_infer/ --rec_char_dict_path ./ppocr/utils/dict90.txt --rec_image_shape 3,48,48,160 --image_dir ./doc/imgs_words_en/word_116.png`

得到结果如下：

`root INFO: Predicts of ./doc/imgs_words_en/word_116.png:('oblouse.<UKN><UKN><UKN><UKN><UKN><UKN><UKN><UKN><UKN><UKN>oon<UKN><UKN>ke<UKN>s<UKN>ey', 0.646951)`

这个推理命令或推理结果是否正确？如果不正确，应该怎么做？

**Comment by andyjpaddle** [comment]
更新一下最新代码试试，已经修复
