### ISSUE TITLE
paddleocr --image_dir ./imgs_words_en/word_10.png --det false --lang en  det标志无效

### ISSUE THREAD

**Issue by Corybyte** [PaddlePaddle/PaddleOCR#5980]
输出的内容依然包括边界值 求大佬指导

**Comment by LDOUBLEV** [comment]
你的paddleocr版本是？
我这边测试没问题
<img width="960" alt="image" src="https://user-images.githubusercontent.com/26592129/163743527-1a532109-7a52-4528-aad4-ce5c3b48b6b1.png">

**Comment by Corybyte** [comment]
![捕获](https://user-images.githubusercontent.com/74406957/163757593-6a922e6b-634b-4f0a-b270-a8317bed1abd.PNG) 这张是加--det false 显示的结果只有一条 并且没有可用内容
paddleocr --image_dir 1.jpg --lang ch 这条命令 不加--det false 则可以输出正常内容 但是有边界值
![2](https://user-images.githubusercontent.com/74406957/163757755-536c8340-0dcc-4c00-b0fa-b7f7fafca2b7.PNG)

**Comment by LDOUBLEV** [comment]
--det false 表示的是不使用文本检测模型，不代表不输出文本坐标框；

如果不希望获取到检测款，建议获得结果后提取出需要的文字部分
