### ISSUE TITLE
No module named 'tools.infer' error, detectron2 compatibility issue

### ISSUE THREAD

**Issue by vineethbabu** [PaddlePaddle/PaddleOCR#5985]
hi, 
i am getting `No module named 'tools.infer' ` error, if i have detectron2 installed, where as if it is uninstalled every thing works fine. here is my configuration
paddleocr: 2.0.6
torch: 1.10.0
torchvision: 0.11.2
cuda: 10.2
detectron2: 0.6+cu102
could some one help with how this can be resolved ?
Thanks in advance.

**Comment by gigaenr-bh** [comment]
same problem here, but  I can't remove detectron2 in my project, any suggestions?

**Comment by andyjpaddle** [comment]
please update the latest code, if it doesn't work, try this issue https://github.com/PaddlePaddle/PaddleOCR/issues/1024

**Comment by Sayaka91** [comment]
@gigaenr-bh @andyjpaddle 
Did you change anything in your project? I got the similar problem.
When I add detectron2 into my project and `import paddleocr` , I got the error `ModuleNotFoundError: No module named 'tools.infer'`
