### ISSUE TITLE
dbnet+crnn在自己项目里推理时，出现错误

### ISSUE THREAD

**Issue by litao-zhx** [PaddlePaddle/PaddleOCR#5986]
![image](https://user-images.githubusercontent.com/76981650/163797473-acdcc20c-8306-4679-bf8d-e0286b4ea18f.png)
![image](https://user-images.githubusercontent.com/76981650/163797553-8bc4c8ca-c8c9-4908-8d6d-d13f5b66e845.png)
![image](https://user-images.githubusercontent.com/76981650/163797576-2e71e939-39d5-4e4a-a38e-72737e3d5542.png)
看上去是cudnn的问题，但是我按照要求，将版本改了了如下：
CUDA：11.2
cudnn:8.2.1.32
tensorrt：8.2.06
paddle:2.2.0

**Comment by litao-zhx** [comment]
在它之前，用tensorrt推理了一个pytorch版本的yolo，奇怪的是，不用tensorrt推理YOLO时，没有这个问题，用了tensorrt推理YOLO，就会出现这个问题，不管ocr部分是否用了tensorrt

**Comment by litao-zhx** [comment]
往大佬们帮忙看看

**Comment by andyjpaddle** [comment]
看报错是环境的问题，可以确认一下cudnn，驱动这些是否正确安装，版本是否匹配

**Comment by andyjpaddle** [comment]
推荐使用docker安装环境

**Comment by litao-zhx** [comment]
使用的cuda配置是CUDA:11.2，cudnn：8.2.1.32，tensorrt：8.2.06，paddle-gpu：2.2.0。
目前使用的环境是根据![image](https://user-images.githubusercontent.com/76981650/163979090-04137b52-b11e-4d2f-85a2-5e26cffa283a.png)修改过的，但是不知道为什么还有这个。

**Comment by litao-zhx** [comment]
> 

如果说用docker去配置环境的话，那还需要安装tensorrt吗？还是说镜像里已经集成了tensorrt

**Comment by andyjpaddle** [comment]
官方paddle docker是不含tensorrt的，里面会包含cuda ,cudnn这些基础环境，需要自己安装tensorrt，然后你上面的截图是Python预测库，如果需要开启tensorrt预测，需要重新安装这个paddle包，图片的安装包只是提供了对应版本的paddle，并不包含基础环境

**Comment by litao-zhx** [comment]
那肯定的，我是按照截图里的配置下的cuda、cudnn、tensorrt这些。然后docker的话我去试试行不行

**Comment by litao-zhx** [comment]
我尝试了docker安装，但是报错还是一样的，cuda、cudnn都没有重新装，就是将服务器上的tensorrt拷了一份至docker上，结果报错一样
