### ISSUE TITLE
这个地方是不是应该写成这样：character = "-0123456789abcdefghijklmnopqrstuvwxyz" 因为idx=0是被忽略了

### ISSUE THREAD

**Issue by ga546** [PaddlePaddle/PaddleOCR#5988]
https://github.com/PaddlePaddle/PaddleOCR/blob/5140907d7c673a82ef6e606d10828a23e2269d12/ppocr/postprocess/rec_postprocess.py#L30

**Comment by andyjpaddle** [comment]
麻烦详细描述一下你的问题哈，包括错误和运行指令等信息
