### ISSUE TITLE
表格识别训练问题

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#5990]
针对自己业务的表格，我理解表格结构模型，文字检测模型，文字识别3个模型的训练是完全独立的，那么训练表格结构模型里面标签为什么还需要具体的文字信息呢，只包含结构信息行不行，文字信息用[]空来代替。

**Comment by WenmuZhou** [comment]
不行，需要单元格信息来和文字信息进行关联，具体可以看看文档里的流程说明 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppstructure/table/README_ch.md#1-%E8%A1%A8%E6%A0%BC%E8%AF%86%E5%88%AB-pipeline

**Comment by liulei199409** [comment]
训练阶段还需要文本信息吗，看源码训练没有用到吧，推理用到了

**Comment by WenmuZhou** [comment]
训练没用到，可以用1代替
