### ISSUE TITLE
paddlehub 使用的ocr模型比paddleOCR文档里面的新

### ISSUE THREAD

**Issue by stoneLee81** [PaddlePaddle/PaddleOCR#5992]
测试mobile_rec的模型时，发现paddleOCR文档里面的mobile_rec模型精度没有paddlehub提供的mobile_rec的高,对比才发现，paddlehub的使用的是21.5月的模型，而paddleocr是20.12月的，最新的推理模型在哪里可以下载到呢，文档好像没找到

paddleocr推荐的chinese_ocr_db_crnn_mobile使用的rec推理模型
![image](https://user-images.githubusercontent.com/18001708/163969044-95c75b8a-4acd-4636-ad5b-150581eae0a7.png)

paddlehub的chinese_ocr_db_crnn_mobile使用的rec推理模型
![image](https://user-images.githubusercontent.com/18001708/163968915-8d97d6a0-4d28-4293-b59f-2c595684d363.png)

hub使用的比较新，最新的推理模型哪可以下载到呢？

**Comment by tink2123** [comment]
可以看release/2.4分支的[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md)，最新的模型是：
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar
