### ISSUE TITLE
总是报输入错误，没有发现为什么输入有问题

### ISSUE THREAD

**Issue by zhaoloulou** [PaddlePaddle/PaddleOCR#5993]
![image](https://user-images.githubusercontent.com/42457505/163973246-8b2fdcfb-36ae-47da-b8ff-f91ff78e1dae.png)

![image](https://user-images.githubusercontent.com/42457505/163973363-8d07b70f-d769-4358-9bc7-ad2448d64d8c.png)

**Comment by zhaoloulou** [comment]
paddle serving 模型部署，python3 pipeline_http_client.py出现 的问题

**Comment by tink2123** [comment]
可以贴一下 pipeline.log 里的详细报错信息
