### ISSUE TITLE
在jetson TX2上运行结果变差

### ISSUE THREAD

**Issue by latinfish28** [PaddlePaddle/PaddleOCR#5994]
- 系统环境/System Environment：jetson tx2 ubuntu 18.04

在电脑主机（Ubuntu 20.04）上执行的时候，辨识结果很好，但是在jetson tx2上执行时，几乎辨识不出来，我是训练繁体中文辨识，想请问有什么问题吗？

**Comment by latinfish28** [comment]
还是是因为paddlepaddle-gpu版本不同的关系呢
电脑主机上的版本是2.2.2，但jetson tx2的版本只能到2.0.2

**Comment by developWmark** [comment]
你可以在tx2上编译2.2.2版本
