### ISSUE TITLE
Missing detection/recognition text in image

### ISSUE THREAD

**Issue by jcgarciaca** [PaddlePaddle/PaddleOCR#5999]
Hi,

I am trying to run the ocr over an image like shown below, but numbers inside black box are not detected/recognized (and this is actually the biggest text). Do you have any suggestion?
I tried some image preprocessing as well as different text detection and recognition models without success.

Thank you.

![ocr_results](https://user-images.githubusercontent.com/16105177/164051946-1afe57da-f964-4255-b7c2-4915c4300d67.png)

**Comment by tink2123** [comment]
The data of the black box class is missing in the training data of the text detection.It is recommended to collect data for the above scenarios and finetune model.
