### ISSUE TITLE
关于paddleOCR的推理速度

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleOCR#60]
平台：AI-studio
GPU：v100
被推理的图片大小：150k、1920*1080

使用GPU：约6秒
使用CPU：约8秒

请教：如何提升推理速度？

**Comment by LDOUBLEV** [comment]
> 平台：AI-studio
> GPU：v100
> 被推理的图片大小：150k、1920*1080
> 
> 使用GPU：约6秒
> 使用CPU：约8秒
> 
> 请教：如何提升推理速度？

这速度不太合理，而且GPU只是少了两秒，GPU基本没有加速，你是仅测试单张图像吗？在第一张图像上运行时，算法启动会占用很多时间，但是不会那么久。
顺便提供下我刚测试的速度，在500张图像上评估的速度。
识别模型的输入图像最长边设置为960，速度是：
V100 GPU：0.068  s 
T4 GPU ：0.072  s

**Comment by 670133189** [comment]
> > 平台：AI-studio 
> > GPU：v100 
> > 被推理的图片大小：150k，1920 * 1080
> > 使用GPU：约6秒
> > 使用CPU：约8秒
> > 请教：如何提升推理速度？
> 
> 这速度不太合理，而且GPU只是少了两秒，GPU基本没有加速，你是仅测试单张图像吗？在第一张图像上运行时，算法启动会占用很多时间，但是不会那么久。
> 顺便提供下我刚测试的速度，在500张图像上评估的速度。
> 识别模型的输入图像最长边设置为960，速度是：
> V100 GPU：0.068 s
> T4 GPU：0.072 s

嗯嗯。这是我的命令行（识别+推理）单张图片（字母+数字）：

python3 tools/infer/predict_system.py --det_model_dir="inference/det/" --rec_model_dir="inference/starnet/" --rec_image_shape="3, 32, 100" --rec_char_type="en" --image_dir='图片路径' --det_max_side_len=1920 --use_gpu=True

时长就是上面提到的6-8秒，请教：是什么原因？

**Comment by LDOUBLEV** [comment]
可否方便提供下你的测试图像？

**Comment by 670133189** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Double_V"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上7:44
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"桢少"<670133189@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 关于paddleOCR的推理速度 (#60)





 
可否方便提供下你的测试图像？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

ke_video.zip (22.42M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=24656438b60dfa9ca00e951f1539514d0653515a030e53544855510e00145704065649590a5a074f0157510d015c06045403005c33356309003a1251575c0c4c1f0c14380e&t=exs_ftn_download&code=eed839cb

**Comment by LDOUBLEV** [comment]
用你的数据测试了一下速度，长边为960 时，除了第一张图片时间比较长之外，其他图像只要0.05-0.06s
![image](https://user-images.githubusercontent.com/26592129/82215212-9afaa000-9949-11ea-99f2-c722702fe16f.png)

长边为1920时，每张图像速度大概在0.2s。


![image](https://user-images.githubusercontent.com/26592129/82215541-270cc780-994a-11ea-976c-da4818a0d610.png)

**Comment by LDOUBLEV** [comment]
建议换一个环境再测试下，可能是AIstudio资源分配的问题

**Comment by 670133189** [comment]
> 可否方便提供下你的测试图像？



> 用你的数据测试了一下速度，长边为960 时，除了第一张图片时间比较长之外，其他图像只要0.05-0.06s
> ![image](https://user-images.githubusercontent.com/26592129/82215212-9afaa000-9949-11ea-99f2-c722702fe16f.png)
> 
> 长边为1920时，每张图像速度大概在0.2s。
> 
> ![image](https://user-images.githubusercontent.com/26592129/82215541-270cc780-994a-11ea-976c-da4818a0d610.png)

了解。原来我一直都是测试单张图片，

> 建议换一个环境再测试下，可能是AIstudio资源分配的问题

好的，感激！另外我想请教一下：每次开始执行都会加载算法，能否只加载一次？后续不论是单多张图片，都可以维持在毫秒之间。

**Comment by LDOUBLEV** [comment]
我们后面也会推出更轻量的模型，速度也会更快，第一次运行都需要加载模型，我们也想办法能否缩短这部分时间。

**Comment by WenmuZhou** [comment]
我发现识别为3,32,256时速度也不快，大概是22fps

**Comment by LDOUBLEV** [comment]
> 我发现识别为3,32,256时速度也不快，大概是22fps

请问下，你的测试环境是什么，CPU还是GPU，以及GPU型号。

**Comment by WenmuZhou** [comment]
ai studio v100

**Comment by LDOUBLEV** [comment]
> ai studio v100

应该是AIstudio机器的问题，我找了两台机器测试，从 检测到识别串联预测 都接近20fps了

**Comment by onmygame** [comment]
我也有个问题
测试模型DB时速度能达到几十毫秒一张图，但是换成EAST就需要2-3秒
环境：GTX1080ti
测试发现copy_from_cpu和copy_to_cpu用时最大，实际预测的时间也只有几十毫秒，这个io操作花费时间特别久，有什么办法可以优化吗？

**Comment by LDOUBLEV** [comment]
> 我也有个问题
> 测试模型DB时速度能达到几十毫秒一张图，但是换成EAST就需要2-3秒
> 环境：GTX1080ti
> 测试发现copy_from_cpu和copy_to_cpu用时最大，实际预测的时间也只有几十毫秒，这个io操作花费时间特别久，有什么办法可以优化吗？

收到反馈，我们争取优化下，有更新会在这里回复

**Comment by yanqi1811** [comment]
请问模型预测时设置了最长边尺寸后，检测到的每行数据都会先padding到最长边尺寸后再进行依次预测吗？这样是否会增加大多数小于最长边的样本预测时间？增加过多的padding会稍稍影响识别结果吗？谢谢。

**Comment by LDOUBLEV** [comment]
> 请问模型预测时设置了最长边尺寸后，检测到的每行数据都会先padding到最长边尺寸后再进行依次预测吗？这样是否会增加大多数小于最长边的样本预测时间？增加过多的padding会稍稍影响识别结果吗？谢谢。

设置最长边尺寸后，检测时按照宽高比等比例resize，没有用padding。识别时，如果设置了识别图像的shape， 会按照输入shape对图像做resize或者padding，增加过多的padding有可能影响识别结果，大部分情况下影响不大

**Comment by fa00fa** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/70007690/7e6f45b0-9d78-40c0-8838-15e054bf91b9)
为啥我这样调用摄像头传给OCR识别，推理速度也要6~8s呢？
