### ISSUE TITLE
为什么提示type object DetOp has no attribute new_h？

### ISSUE THREAD

**Issue by ZengDaYu** [PaddlePaddle/PaddleOCR#6000]
完全按照release/2.4的环境安装，结果提示type object DetOp has no attribute new_
![1650422699(1)](https://user-images.githubusercontent.com/23638831/164137576-1acfd9e9-baf4-460f-90af-543914ab6c0c.jpg)
h

**Comment by ZengDaYu** [comment]
环境：
paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82
paddlepaddle-gpu==2.0.0
paddle_serving_server_gpu-0.8.3.post101-py3-none-any.whl
paddle_serving_client-0.8.3-cp37-none-any.whl
paddle_serving_app-0.8.3-py3-none-any.whl

**Comment by tink2123** [comment]
> paddlepaddle-gpu==2.0.0

请更新paddle版本至 2.2.1+

**Comment by tink2123** [comment]
另外是否修改了代码呢？使用的是PaddleOCR的哪个分支。

**Comment by ZengDaYu** [comment]
使用的是release/2.4，环境修改为下面这样：
paddle-serving-app        0.8.3
paddle-serving-client     0.8.3
paddle-serving-server-gpu 0.8.3.post101
paddlepaddle-gpu          2.2.2.post101
然后重新克隆一遍代码就运行成功了，好神奇！我以前这么试过好几次，都没有成功，唯一的区别就是重新克隆了一遍代码……我就改过两个地方，一个是config.yml，我把51行改为了30000
![1650505642(1)](https://user-images.githubusercontent.com/23638831/164355302-4af48659-c970-4ddf-903c-af6a66d14b58.jpg)
还有ocr_reader.py的345行，我看这里没有对应的文件，就改成了“../../ppocr/utils/ppocr_keys_v1.txt”
![1650505793(1)](https://user-images.githubusercontent.com/23638831/164355579-e48c5aff-047f-4a71-8b96-322923eeba10.jpg)
这些都是我刚开始的时候启动服务失败而修改了，是这两个地方导致[type object DetOp has no attribute new_h 的问题吗？
