### ISSUE TITLE
使用文字检测的nb模型进行预测时，输出的（1,1,640,640）信息中如何提取框信息？

### ISSUE THREAD

**Issue by deepthman** [PaddlePaddle/PaddleOCR#6001]
将文字检测模型转为nb模型后在linux上使用python api进行预测，输出的是（1, 1，640，640）的信息，640是图像输入的大小，然后将输出输出信息中大于0.1的点标记。
````none
output_tensor = predictor.get_output(0)
output_data = output_tensor.numpy()
data = output_data[0]
#文字检测标记
idata = data[0]
for i in range(640):
    for j in range(640):
        pix = idata[i][j]
        if pix > 0.1:
            #print(f'位置{j}, {i}     得分：{pix}')
            cv2.circle(img, (j, i), 1, (0, 0, 255), 1)
````
结果得到这样的图
![image](https://user-images.githubusercontent.com/50742242/164141164-9427667e-8dac-4233-803d-2bf24065cd29.png)

基本把文字的大概位置标记到了，但是不知道怎么获得具体的框坐标。
c++水平一般，对于给的andriod demo里的cpp处理看不太明白，有python方面的代码参考吗？

**Comment by LDOUBLEV** [comment]
python 代码参考：https://github.com/PaddlePaddle/PaddleOCR/blob/5140907d7c673a82ef6e606d10828a23e2269d12/ppocr/postprocess/db_postprocess.py#L177-L192

**Comment by deepthman** [comment]
> python 代码参考：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/5140907d7c673a82ef6e606d10828a23e2269d12/ppocr/postprocess/db_postprocess.py#L177-L192

感谢！
