### ISSUE TITLE
 ValueError: `paddle.load` can not parse the file:./pretrain_models/rec_r50_srn/best_accuracy.pdparams.

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#6004]
文字识别，训练和评估都出现这样的错误，以前没出现过，有人知道是因为什么吗？

**Comment by tink2123** [comment]
可以提供下你的运行命令吗，应该是预训练模型的路径不对。

**Comment by qqqqq127** [comment]
> 可以提供下你的运行命令吗，应该是预训练模型的路径不对。

CUDA_VISIBLE_DEVICES=2 nohup python3 tools/train.py -c ./configs/rec/rec_r50_fpn_srn.yml -o Global.pretrained_model='./pretrain_models/rec_r50_srn/best_accuracy' >>rec_srn.out &
我把这个放在rec_r50_srn的文件夹里
