### ISSUE TITLE
您好，请问ppocr系列的识别模型会一直采取crnn+ctc这样吗？

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleOCR#6006]
包括之前开源sever模型还有现在的ppocrv2都采用了类似的方式，就ctc loss而言，面对图像中含有较紧凑的相同字符很容易出现吞字，比如1111最终可能识别成11，请问有没有改进方式，后续会一直采取这类模型么？像transformer encoder + decoder 和 srn这样的模型和crnn+ctc比优劣在哪里。

**Comment by wzyforgit** [comment]
同问，插个眼，等大佬解答

**Comment by noahzhy** [comment]
不是大佬，搜到了顺带一答。transformer 结构的运行速度普遍比较慢，pp系列基本都是易部署导向的，很多芯片还没有针对transformer 的 ops 进行优化，另外，吞字现象普遍是输入图片被压缩导致的。
