### ISSUE TITLE
PGNet：如图的训练指标都是什么含义？

### ISSUE THREAD

**Issue by fangfangzk** [PaddlePaddle/PaddleOCR#6009]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by fangfangzk** [comment]
![R_GVX TQ%%OQWUUFJH@1KSA](https://user-images.githubusercontent.com/75557988/164217371-a722112a-c84f-4310-ac97-b4b894de6b63.png)

**Comment by fangfangzk** [comment]
为什么有些指标末尾带上e2e后缀

**Comment by zjlGO** [comment]
+1，并且还想问，为什么预训练模型在totaltext上微调过后，F_score指标比论文里的理论值低很多
