### ISSUE TITLE
关于finetune超轻量模型的相关问题

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [PaddlePaddle/PaddleOCR#602]
最近在训练DB模型，发现
1.使用发布的超轻量模型直接测试训练的数据集，性能优于finetune后的性能。
2.使用finetune结束后的模型，在执行检测的时候，很多文字都检测不出来，即便是直接测试训练集，也漏了很多标注框。
求大佬帮忙解答一下。
关于训练的技巧和一些不可忽视的track，感觉自己还没注意到。

**Comment by LDOUBLEV** [comment]
你的数据是怎么样的呢？按照道理来说，fine-tune后效果要更好一些。你fine-tune的loss下降怎么样，是否有收敛，在你自己的测试数据上精度是否有提升。

训练技巧：
1. 先根据训练日志判断训练是否正常
2. 使用小学习率试试
3. 根据你检测漏框的case，分析原因，针对性的调整策略。

**Comment by ZhaoyangLi-nju** [comment]
loss在下降，hmean在涨，但是实际效果在降，举例来说
训练前
![训练前](https://user-images.githubusercontent.com/43194342/91013046-ae3c9c00-e619-11ea-83de-ddb36585eeb0.jpg)

训练后
![训练后](https://user-images.githubusercontent.com/43194342/91013055-b1d02300-e619-11ea-8ec5-1b68aa93b1de.jpg)

**Comment by LDOUBLEV** [comment]
训练久一些试试呢。如果你的图像都是这种手机截图的，把训练的image_shape 改为和你现在的手机截图shape 训练试试，改动的地方是配置文件的 Global.image_shape

**Comment by ZhaoyangLi-nju** [comment]
> 训练久一些试试呢。如果你的图像都是这种手机截图的，把训练的image_shape 改为和你现在的手机截图shape 训练试试，改动的地方是配置文件的 Global.image_shape
因为数据中图片大小不一致，这个image_shape,取最大值吗

**Comment by LDOUBLEV** [comment]
现在的image shape是 3， 640， 640, 是个正方形的，你的手机截图数据是长方形的，可以按照长款比例稍微调整下，处于一个大概的范围就行。如果小字很多，可以把image shape 设置大一些，这样容易检测到小字

**Comment by LDOUBLEV** [comment]
你训练的时候预训练模型加载成功了吗

**Comment by ZhaoyangLi-nju** [comment]
> 你训练的时候预训练模型加载成功了吗

![image](https://user-images.githubusercontent.com/43194342/91019588-cd402b80-e623-11ea-961a-5fe5a444f8de.png)这应该是算加载成功了吧
我记得这是个randomcrop的尺寸，还是说，这是个resize的尺寸

**Comment by LDOUBLEV** [comment]
image shape 是输入给网络的训练数据尺寸，前面会有一些处理，但都会resize到这个shape

**Comment by ZhaoyangLi-nju** [comment]
> image shape 是输入给网络的训练数据尺寸，前面会有一些处理，但都会resize到这个shape。
> 
> 看上去加载成功了

我看到做了尺度缩放，随机抖动，随机翻转，这个应该是将随机尺度缩放的图片裁剪出法人相大小，是吧

**Comment by LDOUBLEV** [comment]
嗯嗯，是的

**Comment by Luffffffy** [comment]
> 最近在训练DB模型，发现
> 1.使用发布的超轻量模型直接测试训练的数据集，性能优于finetune后的性能。
> 2.使用finetune结束后的模型，在执行检测的时候，很多文字都检测不出来，即便是直接测试训练集，也漏了很多标注框。
> 求大佬帮忙解答一下。
> 关于训练的技巧和一些不可忽视的track，感觉自己还没注意到。

你好，我也面临着同样的问题，但是我还是想确认一下是否我用于finetune的模型有误
我是从这里下载的 https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_train.tar
这个模型finetune不了，随后我又下载了 https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet50_vd_ssld_pretrained.pdparams
这个预训练模型
训练到loss达到1.1，然后我转为inference模型后，测的效果非常非常非常的差，预测不了任何的文字
请问这是为什么
感谢回复，谢谢！！！
