### ISSUE TITLE
设置use_dilation参数后预测结果不一致

### ISSUE THREAD

**Issue by drenched9** [PaddlePaddle/PaddleOCR#6024]
训练DB检测模型，训练完成后转换为Inference模式预测。
第一次未使用use_dilation，预测的框很小（可能是训练样本的原因），但是预测到了。
python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/db_mv3_inference/" --image_dir="./test_data" --use_gpu=True
![det_res_img_219](https://user-images.githubusercontent.com/24662844/164359307-b6387451-614a-43dd-ab1e-45d4f2096bdd.jpg)

第二次使用use_dilation，直接没有预测框了。
python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/db_mv3_inference/" --image_dir="./test_data" --use_gpu=True --use_dilation=True
![det_res_img_219](https://user-images.githubusercontent.com/24662844/164359296-2c06e693-8c74-45fa-98ad-ac84b95efa54.jpg)

请问这是什么原因呢？

**Comment by WenmuZhou** [comment]
可以可视化一下db输出的map看看

**Comment by drenched9** [comment]
> 可以可视化一下db输出的map看看

我理解我上面第一次操作就是可视化的db输出的map吧？还是你的意思是，使用不转换为inference的模式预测吗？

**Comment by drenched9** [comment]
> > 预测的框很小（可能是训练样本的原因）
> 
> 如果是预测的框比较小，尝试增大 unclip_ratio 这个参数
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/utility.py#L54

谢谢，修改这个参数后看起来是我想要的效果。

**Comment by drenched9** [comment]
> 可以可视化一下db输出的map看看

不好意思，我试了一下。果然转换为inference模式后的预测结果跟之前不一致。我看了其他模型转换的issue，但是有的说2.3版本以后已经解决。但是我目前拉取的是2.4版本，依然存在导出后的检测准确率低的问题。

**Comment by LDOUBLEV** [comment]
你转还前的预测命令和转换后的预测命令发一下，方便的话提供下你训练用的配置config.yml

**Comment by drenched9** [comment]
> 你转还前的预测命令和转换后的预测命令发一下，方便的话提供下你训练用的配置config.yml
检测模型预测效果（未转换）：
python3 tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./test_data" Global.pretrained_model="./output/db_mv3/best_accuracy"
检测模型转换为inference模型方式:
python3 tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model="./output/db_mv3/best_accuracy" Global.save_inference_dir="./output/db_mv3_inference/"

配置文件用的是det_mv3_db.yml。为了防止我自己修改yml导致后面不记得自己改了什么，所以我训练都是直接用命令行修改配置的，不直接改配置文件。
训练参数是：
python3 -m paddle.distributed.launch --gpus '1' tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained \
     Global.epoch_num=10000 \
     Global.save_epoch_step=2000 \
     Train.dataset.data_dir=./train_data/data \
     Train.dataset.label_file_list=[./train_data/data_train.txt] \
     Train.loader.num_workers=2 \
     Eval.dataset.data_dir=./train_data/data \
     Eval.dataset.label_file_list=[./train_data/data_test.txt]


[然后我今天看了其他的issue（主要是），发现一个突破口。](https://github.com/PaddlePaddle/PaddleOCR/issues/2080)
就是将tools/infer/predict_det.py中的44行注释
我重新用静态图预测一次后，发现结果比之前的好点了。
然后也看到有人说是预测的图片大小跟训练的大小不一致。
我就根据配置文件中的DetResizeForTest: image_shape: [736, 1280]，去tools/infer/predict_det.py的44行加上'image_shape': [736, 1280]，这样用静态图预测的结果就跟动态图的预测结果一致了。

总结：
感觉这是一个bug。需求修改tools/infer/predict_det.py中的后处理参数。估计predict_rec.py应该也有相同的bug。
