### ISSUE TITLE
关于官方说明文档中优化器参数factor的说明问题

### ISSUE THREAD

**Issue by axhionning** [PaddlePaddle/PaddleOCR#6026]
![image](https://user-images.githubusercontent.com/100411801/164398902-ef86529d-e11b-4467-b9c3-53dc3ed86acd.png)
![image](https://user-images.githubusercontent.com/100411801/164399184-6a290d0d-8d15-4556-ac78-a153dea6cb53.png)
![image](https://user-images.githubusercontent.com/100411801/164401734-51bf7ae7-ef72-4679-b942-c42f382501e1.png)
以下问题都基于release-2.4版本：
请问官方说明文档中这里的factor不应该是正则化系数吗，为什么写的是学习率衰减系数？（图1、2）
顺便问一下，det_mv3_db.yml配置文件中优化器部分没有对学习率策略的设置，意味着官方用dbnet做检测训练时默认只使用余弦退火策略并不支持在配置文件中更改吗？（图3）
期待各位的回复，谢谢。

**Comment by WenmuZhou** [comment]
你好感谢指正

文档的问题在这里修复了 https://github.com/PaddlePaddle/PaddleOCR/pull/6031
学习率的问题：这里只设定了学习率的情况下是使用恒定学习率，训练途中不改变学习率大小。如果需要修改的话，可以在这里选择需要的学习率衰减方式https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/optimizer/optimizer.py，然后在配置文件中进行配置

**Comment by axhionning** [comment]
> 



> 你好感谢指正
> 
> 文档的问题在这里修复了 #6031 学习率的问题：这里只设定了学习率的情况下是使用恒定学习率，训练途中不改变学习率大小。如果需要修改的话，可以在这里选择需要的学习率衰减方式https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/optimizer/optimizer.py ，然后在配置文件中进行配置，具体配置方式为
> 
> ```yaml
> lr:
>   name: MyLr
>     args1: args1
>     args2: args2
> ```

感谢回复，祝好，不过选择学习率衰减方式应该是这个文件下[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/optimizer/learning_rate.py](url)

**Comment by axhionning** [comment]
> 你好感谢指正
> 
> 文档的问题在这里修复了 #6031 学习率的问题：这里只设定了学习率的情况下是使用恒定学习率，训练途中不改变学习率大小。如果需要修改的话，可以在这里选择需要的学习率衰减方式https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/optimizer/optimizer.py ，然后在配置文件中进行配置，具体配置方式为
> 
> ```yaml
> lr:
>   name: MyLr
>     args1: args1
>     args2: args2
> ```

![image](https://user-images.githubusercontent.com/100411801/164697747-cdf2343f-5f6f-4709-9551-266b3ba2ae15.png)
![1650623635(1)](https://user-images.githubusercontent.com/100411801/164697845-8a49d1cf-8f39-48e9-aaa7-7f214b8ae8c9.jpg)
![image](https://user-images.githubusercontent.com/100411801/164698853-606e94b9-44cd-481e-9ce5-04c5a5662e42.png)
![707837052dde467f50b77204c201ebb](https://user-images.githubusercontent.com/100411801/164698880-791b3b1f-d6ff-46fb-83c3-9b21ee1edefc.png)
请问如何才能正确设置学习率衰减策略呢，试过两种设置办法，都失败了（图1、2为一种按照您给的格式，图3、4为一种参考了别的配置文件里的格式），期待您的回复。

**Comment by WenmuZhou** [comment]
感谢指正，回复中已经修改为正确的文件链接。另外给出的样例粘贴时出现了格式错误，抱歉，正确的格式为
```yaml
lr:
  name: MyLr
  args1: args1
  args2: args2
```

图3，4里的错误应该是你给checkpoints参数传递模型地址时，需要配置和之前训练是保持一致，现在你改了学习率部分，此时，模型需要传递给pretrained_model字段

**Comment by axhionning** [comment]
> 

感谢回复，祝好！

**Comment by axhionning** [comment]
> 感谢指正，回复中已经修改为正确的文件链接。另外给出的样例粘贴时出现了格式错误，抱歉，正确的格式为
> 
> ```yaml
> lr:
>   name: MyLr
>   args1: args1
>   args2: args2
> ```
> 
> 图3，4里的错误应该是你给checkpoints参数传递模型地址时，需要配置和之前训练是保持一致，现在你改了学习率部分，此时，模型需要传递给pretrained_model字段

感谢回复，祝好！
