### ISSUE TITLE
ch_ppocr_server_v2.0_xx 模型识别图片 部分文字未显示

### ISSUE THREAD

**Issue by Corybyte** [PaddlePaddle/PaddleOCR#6028]
ubuntu20.04
ch_ppocr_server_v2.0_xx 模型识别图片 部分文字未显示
![9fab28434c7f4365969aae609abd885](https://user-images.githubusercontent.com/74406957/164413585-00999723-3d80-4322-803f-9d8b9d0cc977.jpg)

**Comment by WenmuZhou** [comment]
未显示，是指没检测到吗，另外，可以提供一下运行命令吗

**Comment by LDOUBLEV** [comment]
是指这里漏掉吗？
<img width="571" alt="image" src="https://user-images.githubusercontent.com/26592129/164427445-a90720d7-6702-464c-96f8-b6c736e50fd6.png">

设置[drop_score](https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/utility.py#L87)=0.0试试

**Comment by Corybyte** [comment]
> 未显示，是指没有检测到吗，另外，可以提供一下运行命令吗


from paddleocr import PaddleOCR,draw_ocr
import re
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(drop_score=0.0,use_angle_cls=True,det_model_dir="/home/ubuntu/PaddleOCR/inference/ch_rec_r34_vd_crnn_enhance", lang='ch') # need to run only once to download and load model into memory
img_path = '/home/ubuntu/source/2.jpg'
result = ocr.ocr(img_path, cls=True)
        
if_name=0
neme=""      
for line in result:
    print(line[1][0])

**Comment by Corybyte** [comment]
10:04
三川
K
核酸疫苗服务查询
o
台
北京“健康宝"再升级弹窗提示语细化
核酸检测
疫苗接种
核酸检测
姓
名
申**
身份证号：
阴性
距离本次检测已过0天②
核酸检测机构
北京健为医学检验实验
室
核酸检测时间
2022-04-0703:14:30
导出或打印检测报告
历史检测结果查询
本电子报告与医院或其他检测机构提供的纸质报告具有同等效力。

设置了drop_score 还是不行

**Comment by Corybyte** [comment]
> 是指这里漏掉吗？ <img alt="图片" width="571" src="https://user-images.githubusercontent.com/26592129/164427445-a90720d7-6702-464c-96f8-b6c736e50fd6.png">
> 
> 任务是单独运行检测或识别不同层次的预测吗？
> 
> [设置分数](https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/utility.py#L87)= 0.0drop_score

有解决方案吗

**Comment by Corybyte** [comment]
> 未显示，是指没检测到吗，另外，可以提供一下运行命令吗

`import re
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(drop_score=0.0,use_angle_cls=True,det_model_dir="/home/ubuntu/PaddleOCR/inference/ch_rec_r34_vd_crnn_enhance", lang='ch') # need to run only once to download and load model into memory
img_path = '/home/ubuntu/source/2.jpg'
result = ocr.ocr(img_path, cls=True)
        
if_name=0
neme=""      
for line in result:
    print(line[1][0])`

**Comment by Corybyte** [comment]
> 是指这里漏掉吗？ <img alt="图片" width="571" src="https://user-images.githubusercontent.com/26592129/164427445-a90720d7-6702-464c-96f8-b6c736e50fd6.png">
> 
> 任务是单独运行检测或识别不同层次的预测吗？
> 
> [设置分数](https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/utility.py#L87)= 0.0drop_score

是的 身份证号那一部分未识别
