### ISSUE TITLE
ocr_db_crnn.cc:22:43: fatal error: AutoLog/auto_log/lite_autolog.h: No such file or directory

### ISSUE THREAD

**Issue by saylan21** [PaddlePaddle/PaddleOCR#6029]
Hi,
I am trying to inference  demo on Android armv8 device. Using  PaddleOCR/deploy/lite/readme_en.md doc. I tried to execute the compilation and get the executable file ocr_db_crnn but appreantly some files are missing. I go through the doc several times. Could you tell me how i can fix this.
Thanks

**Comment by WenmuZhou** [comment]
exec `git clone https://gitee.com/Double_V/AutoLog `

**Comment by saylan21** [comment]
Thank you very much for your answer. Is there any way of running just detection model instead of running all 3 models.

**Comment by WenmuZhou** [comment]
use dygraph branch code

**Comment by jizhu1023** [comment]
mark
