### ISSUE TITLE
疑是bug，在character_type是en时，不支持指定“character_dict_path”？

### ISSUE THREAD

**Issue by HuangKBAaron** [PaddlePaddle/PaddleOCR#603]
在文件ppocr\utils\character.py的代码中发现：
`        if self.character_type == "en":
            self.character_str = "0123456789abcdefghijklmnopqrstuvwxyz"
            dict_character = list(self.character_str)`
这个设计欠妥？如果我只想要大写？如果我还想加入自己的字符？

**Comment by LDOUBLEV** [comment]
感谢反馈，如果你想用大写的字符，可以把这里改为从文件读取字符列表。之前训练的英文模型都是数字+小写的，所以直接改这里会影响之前的模型。后续模型更新时，会一并修改了。

**Comment by HuangKBAaron** [comment]
还有一处需要同步修改，在character.py的90、91行：
`if self.character_type == "en":
        text = text.lower()`
需要注释掉才能正确。
