### ISSUE TITLE
车牌的一个demo做fine tune,新增加的精度不错，但原精度反而降低了

### ISSUE THREAD

**Issue by stoneLee81** [PaddlePaddle/PaddleOCR#6032]
选了一个车牌的demo,蓝牌的精度基本在0.99X，下载了绿牌的CCPD2020数据集，增量训练的数据大概4000多个图片，epoch:5,训练完毕，导出模型后，对比发现，新增绿牌的精度很高0.99X左右，但是之前模型的蓝牌精度反而降低了很多，不知道是什么原因，做fine tune时，需要注意一些什么呢？

**Comment by stoneLee81** [comment]
原来的数据CCPD2019的大概有15万张图片，之前别人已经训练过，有pretrain模型，我自己理解的，fine tune不是做增量就可以了么？绿牌的训练CCPD2020的数据，为撒还要加原来的数据做全量呢，我刚接触不咋懂 @WenmuZhou

**Comment by stoneLee81** [comment]
@WenmuZhou

**Comment by WenmuZhou** [comment]
直接finetune会遗忘之前的知识

**Comment by stoneLee81** [comment]
那是添加部分的之前数据，还是之前的全部全量？

**Comment by WenmuZhou** [comment]
按照你新场景的实际需求来配比
