### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleOCR#6034]
paddleOcr能编译成32位使用吗

**Comment by MissPenguin** [comment]
应该是支持的，可以试试

**Comment by aiwenzhu** [comment]
你好，有教程吗，我按paddeleinfer ce里的编译方式，太多报错了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MissPenguin ***@***.***&gt;
发送时间: 2022年4月27日 17:56
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: AI-ai ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 编译问题 (Issue #6034)





 
应该是支持的，可以试试
