### ISSUE TITLE
关于设置线程超时问题

### ISSUE THREAD

**Issue by dantaxxxx** [PaddlePaddle/PaddleOCR#6035]
在config文件下我设置开启多线程后，在线程运行时间超过30s后，我的线程就会被杀死我该在哪儿设置线程超时了

**Comment by MissPenguin** [comment]
具体描述下怎么操作的吧，方便复现排查

**Comment by dantaxxxx** [comment]
@MissPenguin 
![image](https://user-images.githubusercontent.com/45675623/165711788-3f059c6b-663f-4330-b760-a6938cbc3e40.png)
将use_multiprocess改为True后如果运行时间过长，超过30S就会直接报runtime

**Comment by dantaxxxx** [comment]
杀死我的进程，然后扫描失败

**Comment by microCloudCode** [comment]
同样的问题
