### ISSUE TITLE
文字识别测试时，什么方法可以一下子测试一个文件夹的数据？

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#6036]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by qqqqq127** [comment]
说错了，是预测，不是评估

**Comment by Corybyte** [comment]
for 循环遍历该文件夹下所有子文件 并执行图片识别

**Comment by drenched9** [comment]
稍微看点预测文件的[代码](https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/predict_rec.py#L379)就知道了，，，
这里image_dir既可以是文件路径，也可以文件夹路径。已经给你写了for循环了。
所以预测的时候只要参考recognition.md中的最后一行，把--image_dir="./doc/imgs_words_en/word_336.png"改成--image_dir="./doc/imgs_words_en"即可

**Comment by MissPenguin** [comment]
楼上正解
