### ISSUE TITLE
Paddle OCR without pip installation

### ISSUE THREAD

**Issue by khawar-islam** [PaddlePaddle/PaddleOCR#6038]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Linux 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message： "No module: paddle"

I want to use PaddleOCR without pip installation because sometimes the version conflict, Which creates big trouble. Do you have an idea? I clone the repository  and install all the dependencies but still, it gave an error "No module: paddle"

**Comment by MissPenguin** [comment]
Have you installed PaddlePaddle?

**Comment by khawar-islam** [comment]
I have cloned repository and i don't want to install Paddle package via pip or conda. How i can install PaddlePaddle without pip or conda?
