### ISSUE TITLE
单字符的文字检测

### ISSUE THREAD

**Issue by tangent2018** [PaddlePaddle/PaddleOCR#6039]
请教大神们，有没有模型可以检测单字符级别的。就是可以把文字中每个字符的位置给标记出来，类似百度ai中的recognize_granularity选项的这种。

**Comment by liguiyuan** [comment]
要做到很好的话，这得训练自己的检测模型，要自己标注单字符的图片

**Comment by MissPenguin** [comment]
方法一：如果是检测+识别的端到端系统，可以试试基于识别结果倒推一下单字位置（之前有开发者这么搞过，但没分享出来，可以探索下。。）
方法二：整理一批单字符标注的数据重新训练检测模型
