### ISSUE TITLE
paddlle gpu版本与torch同时调用则错误退出

### ISSUE THREAD

**Issue by lin1github** [PaddlePaddle/PaddleOCR#604]
我安装了paddlepaddle-gpu==1.7.2.post97，pytorch是1.0.1版本，运行下面语句则不会报错，
import paddle
import torch
但是如果是
import paddle.fluid as fluid
import torch
则会出错，退出程序，没有用的报错信息，我个人感觉是cudnn的问题，请指导一下定位问题

**Comment by LDOUBLEV** [comment]
这个问题麻烦在Paddle repo下提issue吧：https://github.com/PaddlePaddle/Paddle/issues

**Comment by WenmuZhou** [comment]
这是因为torch自带了cudnn，而paddle使用的系统的cudnn，当先load torch时，当前显卡里的cudnn会被改变，此时会导致和paddle需求的cudnn版本不一样而报错。所以需要先load paddle后load torch

**Comment by lin1github** [comment]
> 这是因为torch自带了cudnn，而paddle使用了系统的cudnn，当先load torch时，当前显卡里的cudnn会被改变，此时会导致和paddle需求的cudnn版本不一样而报错。所以需要先load paddle后load torch

先load paddle 也是一样的，报错信息：
W0824 20:32:07.544497 10761 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0824 20:32:07.544538 10761 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0824 20:32:07.544545 10761 init.cc:214] The detail failure signal is:
W0824 20:32:07.544554 10761 init.cc:217] *** Aborted at 1598272327 (unix time) try "date -d @1598272327" if you are using GNU date ***
W0824 20:32:07.548422 10761 init.cc:217] PC: @                0x0 (unknown)
W0824 20:32:07.548569 10761 init.cc:217] *** SIGSEGV (@0x558a9e7d5c20) received by PID 10761 (TID 0x7ffbe32c8740) from PID 18446744072073600032; stack trace: ***
W0824 20:32:07.552098 10761 init.cc:217]     @     0x7ffbe2ec1890 (unknown)
W0824 20:32:07.555570 10761 init.cc:217]     @     0x558a9e7d5c20 (unknown)
错误码异常: exitCode = 139

**Comment by WenmuZhou** [comment]
去paddle repo问一下吧
