### ISSUE TITLE
定位到文字，但无法识别。有的图片还被旋转了90度

### ISSUE THREAD

**Issue by drenched9** [PaddlePaddle/PaddleOCR#6041]
**PS：由于后面还要部署在XPU上，而目前XPU不支持双向LSTM训练的模型。故暂时不考虑自己从头训练，因为也没有非LSTM训练好的预训练模型，自己从头训练很麻烦，且当前自己的样本不足。所以现在只训练了文字定位模型。识别使用已有的识别模型ch_ppocr_mobile_v2.0_rec_infer**

问题一：
训练完成后预测使用predict_system.py，发现有的图没有结果，也没有目标框（如图1）。但是我打印日志发现有目标框的，且目标的四个点是从左上角开始顺时针的记录（图2）。是不是代码写死了，如果识别不出文字（或置信度过低，当前阈值为默认阈值0.5），则目标框也不展示？
![img_33](https://user-images.githubusercontent.com/24662844/164647441-03733f99-ad04-4800-a5d7-a81ddb8b48fd.jpg)
![image](https://user-images.githubusercontent.com/24662844/164647741-d9ebc180-24af-472a-a013-164d5daba5b9.png)

问题二：
然后我加上了参数--save_crop_res=True，保存中间结果。发现这张图旋转了90度。看[代码有一块](https://github.com/PaddlePaddle/PaddleOCR/blob/e13beb5909d3aaab82912260a4cec005704f1f82/tools/infer/utility.py#L629)确实有判断，就旋转90度。所以这块代码是否还需要优化一下呢？
![mg_crop_0](https://user-images.githubusercontent.com/24662844/164647900-b3ae75a4-8e25-4df1-bf1a-253390232893.jpg)

问题三：
另一张图，也是定位出了文字，但是使用默认的识别模型无法正常识别。可是这张图理论上是可以识别才对：
![mg_crop_59](https://user-images.githubusercontent.com/24662844/164648499-7afb0ad8-055b-4405-98ee-eae50bbdb4a7.jpg)

**Comment by Gmgge** [comment]
题外话：你是不是移动的50w。。 你识别这种图片干嘛？

简单解释下
1.由于是通用文本检测，考虑到横排和竖排文字，paddleocr将检测到的文本框根据宽高比进行初步的旋转，将文本转为水平的，在第一张图可以看到，该旋转基于通用的文本单个字是趋于长方形，所以行文本应该是宽大于高的。
2.后面104没有识别出来，不太懂，，你可以直接将该区域再扩大点裁剪，然后直接使用paddleocr的全流程识别一下试试？这种轻微倾斜的状态按说形变没有很明显。

可能的解决办法
1.如果你的应用方向不存再竖排文字，可以直接将该旋转步骤直接去掉。
2.如果你是针对战舰号识别，有没有考虑过用目标检测直接检测，然后裁剪出来使用其他数字识别的方法？

**Comment by drenched9** [comment]
> 题外话：你是不是移动的50w。。 你识别这种图片干嘛？
> 
> 简单解释下 1.由于是通用文本检测，考虑到横排和竖排文字，paddleocr将检测到的文本框根据宽高比进行初步的旋转，将文本转为水平的，在第一张图可以看到，该旋转基于通用的文本单个字是趋于长方形，所以行文本应该是宽大于高的。 2.后面104没有识别出来，不太懂，，你可以直接将该区域再扩大点裁剪，然后直接使用paddleocr的全流程识别一下试试？这种轻微倾斜的状态按说形变没有很明显。
> 
> 可能的解决办法 1.如果你的应用方向不存再竖排文字，可以直接将该旋转步骤直接去掉。 2.如果你是针对战舰号识别，有没有考虑过用目标检测直接检测，然后裁剪出来使用其他数字识别的方法？

题外话：你是不是移动的50w。。 你识别这种图片干嘛？
——没看懂这是啥。我就是用自己标注的一些图片训练了问自己检测模型，然后用通用文字识别模型去识别的。

1.横排竖排可以理解，但是我这种图片标注的时候就是形变的矩形框，是否也应该考虑到这种情况。否则四点标注不是就有这样的情况么？我是可以把if去掉，只是提出来供参考是否需要优化。
2.104没有识别出来，我是用扩大剪裁后，直接用PaddleOCR识别，不加检测，可以识别，但是准确率也只有0.5几。而且我认为我上面这张图切得没问题，但是实际识别置信度还是有点低。
3.这是做战舰号识别，之所以没有用目标检测，因为图片基本都是存在形变的，我知道paddleocr有仿射变换可以校正。paddledetection只能用矩形框做标注，而paddleocr可以四点标注。所以选择的paddleocr的四点检测。而且战舰号识别不止有数字，还有中文的。

**Comment by Gmgge** [comment]
emmm 可能你没理解50w是个搞笑的梗。

你可以尝试一下，扩大之后直接做ocr全流程呢？

**Comment by drenched9** [comment]
> emmm 可能你没理解50w是个搞笑的梗。
> 
> 你可以尝试一下，扩大之后直接做ocr全流程呢？

扩大后的碎片作为输入也不行。
当cls=False时，无法定位到任何内容。
当det=False时，返回104，但是置信度低于0.5
当cls和det都为False时，返回和上面情况一样的。

我也尝试用这个扩大的碎片单独去使用predict_rec.py进行测试，效果更差了。。。所以才来提问的，我基本都试过了。而且我也看了其他issue，有的说需要把imgW固定为100，因为识别模型就是resize为这个宽度，但是我试过也识别错误。

**Comment by Gmgge** [comment]
这个效果确实不是很稳定 把这个碎片放入白色背景中有时候可以识别，有时候识别不出来，有待优化。

![image](https://user-images.githubusercontent.com/48548141/165453226-530aa980-8027-4716-a2c9-ad820bb9e7c7.png)

**Comment by MissPenguin** [comment]
104这张图用ch_ppocr_server_v2.0_rec_infer模型效果还挺好，识别正确，置信度0.98：
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/25809855/165455597-ab1c7a90-c038-4c8e-8716-7b0dad666548.png">

16那张效果差点，估计文本方向判断有问题，加上识别模型对竖排文本的效果也差一点，可能需要自己加数据微调一下了。。

**Comment by drenched9** [comment]
> 104这张图用ch_ppocr_server_v2.0_rec_infer模型效果还挺好，识别正确，置信度0.98： <img alt="image" width="1241" src="https://user-images.githubusercontent.com/25809855/165455597-ab1c7a90-c038-4c8e-8716-7b0dad666548.png">
> 
> 16那张效果差点，估计文本方向判断有问题，加上识别模型对竖排文本的效果也差一点，可能需要自己加数据微调一下了。。

感谢！之前一直忘了换识别的推理模型。我刚刚试了一下发现用ch_PP-OCRv2_rec_slim_infer也能识别104。
其他识别不出来或者识别错误的估计确实要自己加数据重新训练模型了。
