### ISSUE TITLE
真希望能提供应用PPOCRLael标注样本到训练的完整Tutorial

### ISSUE THREAD

**Issue by dsp6414** [PaddlePaddle/PaddleOCR#6048]
PaddleOCR训练对新手确实不太友好

**Comment by andyjpaddle** [comment]
数据表注参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/PPOCRLabel/README_ch.md
训练参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/training.md
