### ISSUE TITLE
如何查看训练模型的参数量paramas和计算量GFLOPs ？

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#6049]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以使用paddle.summary来打印参数量信息，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/summary_cn.html#summary

**Comment by xiaoyeye** [comment]
请问paddle现在有没有办法能输出模型的Gflops呢？

**Comment by sjtu-cz** [comment]
请问paddle现在有没有办法输出模型的GFlops？
