### ISSUE TITLE
RK1808平台上运算时间长

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleOCR#605]
程序是根据 https://paddle-lite.readthedocs.io/zh/latest/demo_guides/rockchip_npu.html 中的示例程序修改得到的，运算一张1920*1080的图片需要4.5秒的时间。想问一下你们在有没有在RK1808平台上进行测试，需要多长时间呢？这个时间有没有可能进一步优化？

**Comment by AIpioneer** [comment]
请问您这边已经测试成功支持了？

**Comment by PaddlePM** [comment]
@bittergourd1224 關於RK1808的平台目前還沒有正式支持, 不過有在規劃中, 方便了解一下您這邊的業務需求以利加速推動嗎？
您可以寄信到wrankykai@hotmail.com我們進一步聯繫討論, 多謝！

**Comment by bittergourd1224** [comment]
@AIpioneer 目前程序是可以正常运行的。
@PaddlePM 好的，谢谢。我这边想利用RK1808配合摄像头做OCR，时间尽量在1~2秒内。但目前以doc/imgs/11.jpg为例，处理时间（不含模型加载时间）耗时4秒以上。

**Comment by python-bookworm** [comment]
> @AIpioneer 目前程序是可以正常运行的。
> @PaddlePM 好的，谢谢。我这边想利用RK1808配合摄像头做OCR，时间尽量在1~2秒内。但目前以doc/imgs/11.jpg为例，处理时间（不含模型加载时间）耗时4秒以上。
ni hao qing  wen ni zai RK1808 shang shi tong guo C++ bianyi yun xing de ma?

**Comment by python-bookworm** [comment]
> @python-bookworm 你好，是的

能否留个联系方式，交流一下，我最近也在做RK1808部署，期待你的回复，谢谢。

**Comment by bittergourd1224** [comment]
> > @python-bookworm 你好，是的
> 
> 能否留个联系方式，交流一下，我最近也在做RK1808部署，期待你的回复，谢谢。

你留个微信，我来加你吧

**Comment by python-bookworm** [comment]
> > > @python-bookworm 你好，是的
> > 
> > 
> > 能否留个联系方式，交流一下，我最近也在做RK1808部署，期待你的回复，谢谢。
> 
> 你留个微信，我来加你吧

我的：hjx19921228
