### ISSUE TITLE
训练Hebrew[希伯来]语言，准确率一直破不了50， 编辑距离最多到0.70

### ISSUE THREAD

**Issue by saicoco** [PaddlePaddle/PaddleOCR#6050]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

### 数据说明
希伯来语与阿拉伯语言类似，从右往左读，因此生成数据时：
- 保证了图片上文字从右往左生成，标签也是从右往左
- 使用语料为希伯来语言的相关的wiki文章

数据量大概50w，目的是为了快速观察拟合效果。

目前服用arabic的配置文件，训练从头开始训练，无pretrain model。

请教一下这类语言该如何训练比较好，效果上不去除了数据之外，是否与合成数据语言读取方向有关系

**Comment by hbulaoma** [comment]
我感觉这个和语言读取方向没关系，可能和样本有关系。要注意文本标签和生成的图像是对应的。可以识别错的样本图像和标签对比一下，特别是含有数字的样本，从右往左的语言，数字是从左向右的。
