### ISSUE TITLE
海思开发板-ARMV7处理器部署PaddleOCR问题汇总

### ISSUE THREAD

**Issue by tensorflowt** [PaddlePaddle/PaddleOCR#6051]
- 部署平台：海思开发板 armv7处理器
- 交叉编译器：
 /opt/hisi-linux/x86-arm/arm-himix200-linux/host_bin/arm-linux-gnueabi-gcc
 /opt/hisi-linux/x86-arm/arm-himix200-linux/host_bin/arm-linux-gnueabi-g++
- 编译系统平台： ubuntu16.04
- 版本号/Version：
https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/lite
https://github.com/PaddlePaddle/Paddle-Lite/tree/v2.10
https://github.com/PaddlePaddle/PaddleOCR.git（对应dygraph分支）
- 遇到问题：
![6361204dfda645d8eedbb0b0d059a88](https://user-images.githubusercontent.com/37217594/164969864-ff59d3f8-287e-46e6-9447-e864421d7a02.png)
- 问题1：
这里的参数：
runtime_device 需要如何指定？
lite_benchmark_value 需要如何指定？
num_threads=1（default） ？
batchsize=1（default） ？

期待您的回复，非常感谢！

**Comment by andyjpaddle** [comment]
lite问题可以到 https://github.com/PaddlePaddle/Paddle-Lite/tree/v2.10 下面进行提问哈
