### ISSUE TITLE
crnn 训练， 如果分1000条一批，每一条生成300张不同字体，背景，角度的图训练 训练完了再继续下一批1000条的训练， 这样渐进训练有没有什么问题？  微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6058]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： 2.4 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
crnn 训练，
如果分1000条一批，每一条生成300张不同字体，背景，角度的图训练
训练完了再继续下一批1000条的训练，
这样渐进训练有没有什么问题？

微信nlanguage

**Comment by WenmuZhou** [comment]
没啥问题
