### ISSUE TITLE
文本检测模型使用checkpoint模型和inference模型效果不一致

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleOCR#606]
checkpoint模型的效果很好，但转换成inference模型后，效果就明显变差，请问这可能是什么原因呢？
系统：ubuntu1804
paddlepaddle-1.8.4
显卡：2070
CUDA10.1
cudnn7.6.5

同一张图片，使用checkpoint模型时效果很好

![1-3_0-0](https://user-images.githubusercontent.com/34031383/91106196-a970fa00-e6a4-11ea-8431-ebab51b6b818.png)
但转换成inference模型后，就变成了这个效果
![det_res_1-3_0](https://user-images.githubusercontent.com/34031383/91106220-b68de900-e6a4-11ea-8da5-8d31e6c6e02a.png)

**Comment by tink2123** [comment]
可以参考一下这个：https://github.com/PaddlePaddle/PaddleOCR/issues/542
