### ISSUE TITLE
怎样使用tpu来训练crnn模型？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6060]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

怎样使用tpu来训练crnn模型？微信nlanguage

**Comment by WenmuZhou** [comment]
暂不支持tpu
