### ISSUE TITLE
选择 BGR而不是RGB的原因是什么？归一化均值方差顺序是否有bug呢？

### ISSUE THREAD

**Issue by yxyangxu** [PaddlePaddle/PaddleOCR#6070]
在det/cls/rec的config file中，可以看到训练时配置是- DecodeImage: img_mode: BGR

想请教下，（1）为什么不用RGB呢？用BGR有哪些好处呀。

（2）潜在的bug担心是说，如下配置文件中用的归一化均值和方差应该是对应 ImageNet预训练 RGB顺序吧，但这里是BGR，所以这样是正确的吗？
- NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

**Comment by littletomatodonkey** [comment]
你好
1. cls/det中，最早写的时候没有注意，算是个小bug，但是我们验证了下，rgb和bgr模式下训练得到的模型精度基本一致，所以后续为了保证前面的模型可以跑通，就没有修复这个问题
2. rec里面，均值用的是0.5，而且没有加载预训练模型，所以通道顺序其实没有影响，只要保证训练和预测的通道顺序一致即可

**Comment by pengfeidip** [comment]
> 你好
> 
> 1. cls/det中，最早写的时候没有注意，算是个小bug，但是我们验证了下，rgb和bgr模式下训练得到的模型精度基本一致，所以后续为了保证前面的模型可以跑通，就没有修复这个问题
> 2. rec里面，均值用的是0.5，而且没有加载预训练模型，所以通道顺序其实没有影响，只要保证训练和预测的通道顺序一致即可

你好,请问如果直接使用你们的OCR模型, 即"pip install "paddleocr>=2.0.1" 安装. 如果送入图像,. 图像应该是RGB还是BGR?

**Comment by littletomatodonkey** [comment]
和训练时保持一致，也是BGR的，可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/whl.md
