### ISSUE TITLE
window C++预测不支持批量预测

### ISSUE THREAD

**Issue by prettyocean85** [PaddlePaddle/PaddleOCR#608]
可否提供C++批量预测支持

**Comment by LDOUBLEV** [comment]
> 可否提供C++批量预测支持

你可以稍微改一下代码，读图的代码在这里，批量预测把这里改为从文件夹读取图像就行： https://github.com/PaddlePaddle/PaddleOCR/blob/fb9e47b262529386983edc21b33abfa16bbf06ac/deploy/cpp_infer/src/main.cpp#L49

**Comment by prettyocean85** [comment]
> > 可否提供C++批量预测支持
> 
> 你可以稍微改一下代码，读图的代码在这里，批量预测把这里改为从文件夹读取图像就行：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/fb9e47b262529386983edc21b33abfa16bbf06ac/deploy/cpp_infer/src/main.cpp#L49

批量预测不是指多张图，是一张图上面不同boxes的识别部分的批量预测。现在我自己是把检测的每个box的图按照长宽比弄成一样大的，然后批量传入进行识别预测，结果不对啊，不知道哪里写的有问题
