### ISSUE TITLE
tensorRT推理报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#6085]
total images num: 100
label file: ppocr_keys_v1.txt
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0427 17:04:55.224633 16304 analysis_predictor.cc:576] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
I0427 17:04:55.399508 16304 fuse_pass_base.cc:57] ---  detected 2 subgraphs
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0427 17:04:55.463774 16304 fuse_pass_base.cc:57] ---  detected 14 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
I0427 17:04:55.480082 16304 fuse_pass_base.cc:57] ---  detected 2 subgraphs
--- Running IR pass [fc_fuse_pass]
I0427 17:04:55.483865 16304 fuse_pass_base.cc:57] ---  detected 2 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0427 17:04:55.513736 16304 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 80 nodes
W0427 17:04:55.547469 16304 tensorrt_subgraph_pass.cc:351] The Paddle Inference library is compiled with 8 version TensorRT, but the runtime TensorRT you are using is 8.2 version. This might cause serious compatibility issues. We strongly recommend using the same TRT version at runtime.
I0427 17:04:55.554622 16304 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0427 17:04:57.684300 16304 engine.cc:197] Run Paddle-TRT Dynamic Shape mode.
W0427 17:04:57.701776 16304 helper.h:107] DLA requests all profiles have same min, max, and opt value. All dla layers are falling back to GPU
I0427 17:06:29.966526 16304 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 5 nodes
I0427 17:06:30.054363 16304 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0427 17:06:30.056280 16304 op_converter.h:211] trt input [lstm_1.tmp_0] dynamic shape info not set, please check and retry.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

Aborted (core dumped)

请问大佬这是啥原因

**Comment by LDOUBLEV** [comment]
因为TRT子图划分问题，导致某些参数需要设置其shape；
报错信息中： 
trt input [lstm_1.tmp_0] dynamic shape info not set, please check and retry.

可以参考[检测模型里设置动态shape的方式](https://github.com/PaddlePaddle/PaddleOCR/blob/8de06d2370e81e0ee1473d17925fb2e05295a0fe/tools/infer/utility.py#L268-L270)设置lstm_1.tmp_0的动态shape，识别模型的动态shape在[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/8de06d2370e81e0ee1473d17925fb2e05295a0fe/tools/infer/utility.py#L275-L277)；

如果不清楚
lstm_1.tmp_0的shape，可以把inference.pdmodel 放在网页 https://netron.app/ 里可视化，搜索lstm_1.tmp_0 查看该参数的shape信息
