### ISSUE TITLE
rare识别模型为什么在训练时候只走else方向，不传入targets值

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#6096]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18
- 版本号/Version：Paddle：v2.2  PaddleOCR： 问题相关组件/Related components：rare模型
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- Q1:rare模型为什么在训练时候只走else方向，不传入targets值（我想的是targets是label标签值），而是直接用batch_size的全0纬度代替，一致不明白这个，麻烦解答一下。
![图片](https://user-images.githubusercontent.com/49891512/165882726-8183f104-833e-4323-b381-6d26a2e7f866.png)

**Comment by LDOUBLEV** [comment]
训练的时候需要使用target作为监督；（if分支）
预测的时候（else分支）没有标签信息，所以需要targets需要补0；

**Comment by InferMaster** [comment]
> 
您的意思是，训练过程中不走if分支吗，问下，训练时候使用target作为监督是在哪一部分呢（补充：我在跑训练时候没有走if分支）

**Comment by LDOUBLEV** [comment]
attention部分 训练的时候需要target 作为监督信息
走这个分支：
<img width="464" alt="image" src="https://user-images.githubusercontent.com/26592129/167853922-35343957-657d-44a0-93f9-cc6cc878ccb2.png">
