### ISSUE TITLE
How to encapsulate OCR for flutter app 

### ISSUE THREAD

**Issue by saylan21** [PaddlePaddle/PaddleOCR#6098]
Hello,
I am following  "PaddleOCR/deploy/lite/readme_en.md " to create an executable, is there a way/document for running this executable in a flutter mobile app.

Thanks

**Comment by LDOUBLEV** [comment]
Hi， there are demos for android and ios.
android: https://github.com/PaddlePaddle/PaddleOCR/tree/release%2F2.5/deploy/android_demo
ios: https://github.com/PaddlePaddle/PaddleOCR/tree/release%2F2.5/deploy/ios_demo

**Comment by ihorkozar** [comment]
I found this repository, but its functionality is questionable https://gitee.com/swzw/paddle-ocr
