### ISSUE TITLE
cpp_infer编译从未成功，能否提供一下release版的结果

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleOCR#6106]
您好，我编译了很多天cpp的部署，参考文档https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/cpp_infer/docs/windows_vs2019_build.md，但是一直没有成功，能否提供一个编译好结果的让我们学习一下，谢谢？

**Comment by andyjpaddle** [comment]
能否提供一下编译过程中的报错信息，我们这边排查一下
