### ISSUE TITLE
当我使用通用模型时会直接Killed

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleOCR#612]
在使用超轻量模型时可以正常得到OCR信息，但当我对同一张图片使用通用中文模型时会报如下错误
```
λ iZwz9e694cocz8fn3et9d9Z /home/PaddleOCR {develop} python3 tools/infer/predict_system.py --image_dir="/opt/tmp/fb_1100.jpg" --det_model_dir="inference/ch_det_r50_vd_db" --rec_model_dir="inference/ch_rec_r34_vd_crnn" --use_gpu=False
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
dt_boxes num : 39, elapse : 5.279992341995239
Killed
```
请问需要如何做？

**Comment by littletomatodonkey** [comment]
这个信息在轻量级模型使用也会显示吗？`grep: warning: GREP_OPTIONS is deprecated`

可以试下在命令行中先输入`alias grep="grep --color=auto"`，执行之后再进行预测

**Comment by thugbobby** [comment]
> 这个信息在轻量级模型使用也会显示吗？`grep: warning: GREP_OPTIONS is deprecated`
> 
> 可以试下在命令行中先输入`alias grep="grep --color=auto"`，执行之后再进行预测

`grep: warning: GREP_OPTIONS is deprecated`这个信息在轻量级也会显示，但不会被killed
