### ISSUE TITLE
PaddleOCR Quick Start中出现：段错误 (核心已转储)

### ISSUE THREAD

**Issue by ZimaBlue307** [PaddlePaddle/PaddleOCR#6120]
各位好。作为OCR初学者，跟着这个网址https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/quickstart_en.md 的教程一步步学习，除了`paddleocr --image_dir ./imgs_en/img_12.jpg --use_angle_cls true --lang en --use_gpu false`这个指令可以成功执行之外，其他的：
```
paddleocr --image_dir ./imgs_en/img_12.jpg --rec false
paddleocr --image_dir ./imgs_words_en/word_10.png --det false --lang en
paddleocr --image_dir ./doc/imgs_en/254.jpg --lang=en
paddleocr --image_dir=../doc/table/1.png --type=structure #最后一个指令layoutparser是按照官网正确安装的
```
这四条指令都会出现如下错误：（从终端复制粘贴）
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1651481555 (unix time) try "date -d @1651481555" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 15638 (TID 0x7f78b88ae340) from PID 0 ***]

段错误 (核心已转储)
```

自己的系统环境如下：
ubuntu 20.04
Paddle: 2.2.2
paddleocr>=2.0.1
cuda: 11.2
cudnn: 8.1.1.33

**Comment by WenmuZhou** [comment]
试一下
```bash
paddleocr --image_dir ./imgs_en/img_12.jpg --use_angle_cls true --lang en --use_gpu true
```

**Comment by ZimaBlue307** [comment]
> 试一下
> 
> ```shell
> paddleocr --image_dir ./imgs_en/img_12.jpg --use_angle_cls true --lang en --use_gpu true
> ```
执行上述指令仍然会出错，报错如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1651564013 (unix time) try "date -d @1651564013" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 7638 (TID 0x7ffb79e3a340) from PID 0 ***]

段错误 (核心已转储)

不知道应该如何解决，是因为自己GPU没装上的原因么？

**Comment by ZimaBlue307** [comment]
您好，执行了上述指令之后还是会报错，报错信息如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.


----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
&nbsp; [TimeInfo: *** Aborted at 1651564013 (unix time) try "date -d @1651564013" if you are using GNU date ***]
&nbsp; [SignalInfo: *** SIGSEGV ***@***.***) received by PID 7638 (TID 0x7ffb79e3a340) from PID 0 ***]


段错误 (核心已转储)



想知道这个是因为自己gpu没有装好的原因么？不知道应该如何解决，麻烦求教！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 中午12:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] PaddleOCR Quick Start中出现：段错误 (核心已转储) (Issue #6120)





 
试一下
 paddleocr --image_dir ./imgs_en/img_12.jpg --use_angle_cls true --lang en --use_gpu true

**Comment by ZimaBlue307** [comment]
似乎知道问题在哪了。使用与原来相同的conda环境似乎可以解决问题。

**Comment by WenmuZhou** [comment]
解决了吗，

**Comment by ZimaBlue307** [comment]
可能暂时解决了，但是不知道有没有解决根源问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 晚上6:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] PaddleOCR Quick Start中出现：段错误 (核心已转储) (Issue #6120)





 
解决了吗，

**Comment by GDongLin** [comment]
我也碰到这个问题，使用cpu正常计算，使用gpu报错，paddle可以正常在gpu使用。各位大概知道如何解决么？日志输出信息太少了

环境：
paddlepaddle-gpu 2.3.0
paddle_serving_server_gpu-0.8.3
—————————————————
cuda 11.2 + cudnn 8.1.1
ubuntu 20.04
GeForce 3080Ti

**Comment by ZimaBlue307** [comment]
也许有些冒昧，但想问是打错了么？您的意思应该是“使用cpu正常计算，使用gpu报错，paddle无法正常在gpu使用”吧？我自己之前也是无法使用gpu，但是切换到之前用gpu训练过模型的conda环境之后好像有一些指令就可以使用gpu了。但确实不知道根源问题是什么。自己用自己电脑的gpu训练的时候也是有时可以有时失败。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] PaddleOCR Quick Start中出现：段错误 (核心已转储) (Issue #6120)





 
我也碰到这个问题，使用cpu正常计算，使用gpu报错，paddle可以正常在gpu使用。各位大概知道如何解决么？日志输出信息太少了
 
环境：
 paddlepaddle-gpu 2.3.0
 paddle_serving_server_gpu-0.8.3
 —————————————————
 cuda 11.2 + cudnn 8.1.1
 ubuntu 20.04
 GeForce 3080Ti

**Comment by jinmnie** [comment]
试一下这个方案 #3345

**Comment by LindgeW** [comment]
> 似乎知道问题在哪了。使用与原来相同的conda环境似乎可以解决问题。

是因为conda环境的问题吗？
