### ISSUE TITLE
Paddle Text Direction Classifier

### ISSUE THREAD

**Issue by spoorgholi74** [PaddlePaddle/PaddleOCR#6122]
Is the text direction classifier just a binary classification task at the word level?
Do you think changing it to a multiclass classification (with letters 0 and 180 degrees for each class) can improve the accuracy?

**Comment by WenmuZhou** [comment]
Can you provide details?

**Comment by spoorgholi74** [comment]
I mean for training the direction classifier, did you use word-level annotation or letter-level annotation?
E.g. Did you take the word "Pain" and rotate it 180 degrees or did you take each letter separately and did the augmentation and training.

**Comment by WenmuZhou** [comment]
1. we use word-level annotation
2. RecAug is used when training https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/configs/cls/cls_mv3.yml#L63-L64

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/ppocr/data/imaug/rec_img_aug.py#L23
