### ISSUE TITLE
训练数字用什么数据集

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleOCR#6125]
我的识别场景比较简单只有数字和大写字母，但是数据只有几张，想用开源数据集训练，应该用什么数据集，没有发现有很多数字的数据集，官方提供的识别用的权重用的什么数据集，需要多少张图片来训练

**Comment by MissPenguin** [comment]
只有数字和大写字母的话，可以先试试[PP-OCRv3英文模型](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th)，如果效果不满足需求，可以通过合成数据在此基础上fine-tune，数据合成方法可参考https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/data_synthesis_en.md ，如果有真实数据，也可以使用PPOCRLabel进行标注。PPOCR的官方英文识别模型训练数据有几十万张，但PPOCR是面向通用场景，需要数据比较多，你的场景简单，而且只进行fine-tune，估计合成几千张就足够了。

**Comment by 0-Maxwei-0** [comment]
> 我的识别场景比较简单只有数字和大写字母，但是数据只有几张，想用开源数据集训练，应该用什么数据集，没有发现有很多数字的数据集，官方提供的识别用的权重用的什么数据集，需要多少张图片来训练

你好，我也有同样的需求，想问问您最后是如何解决的
