### ISSUE TITLE
请教一下paddleocr模型训练的问题关于数学公式的

### ISSUE THREAD

**Issue by duolabmeng6** [PaddlePaddle/PaddleOCR#6127]
# 请教一下如何训练这个数据集

Paper: https://ojs.aaai.org/index.php/AAAI/article/view/5410/5266 [[Link](https://ojs.aaai.org/index.php/AAAI/article/view/5410/5266)]

Data download link: [Link](https://pan.baidu.com/s/1kKWdqGao4f8G_kOFnt8VeA) code: u1uw

![image](https://user-images.githubusercontent.com/59047063/166682043-31836f54-280f-42ad-8b74-d4082c732397.png)

```
\frac{1}{2}*\frac{2}{3}=\frac{1}{3}
```

* \frac{ 怎么输入到网络训练啊

注释格式：
每个边界框的标注格式为：(CHARS, x1, y1, x2, y2, 1)，表示1）字符序列，2）左上角坐标，3）右下角坐标，4）占位符. 支持的表达式如下：

单行表达式，如1+1=2, 3米=300厘米。
垂直表达式，如：!30#×31#&!30#30!#&930，这里!表示空格符号，&表示水平线，#代表换行符。
多行表达式，例如1+2+3#=4+5#=6.
分数，如\frac{1}{3}/\frac{1}{3}=1.
公式，如x+1=2.

**Comment by duolabmeng6** [comment]
请问有大佬教一下吗~

**Comment by MissPenguin** [comment]
没有做过公式识别，根据我们做表格识别的经验随便建议一下哈（请选择性参考）：参考表格识别任务，用html符号将表格表示为一个字符串，如\td这些html表格符号当成一个字符，类似的，公式识别中，可以把\frac当成一个字符（在字典中占一行），{1}这种也当成一个字符，表示分数中的数字1，不带括号的1就表示正常的数字1，然后就变成一个文本识别任务。

**Comment by duolabmeng6** [comment]
> 没有做过公式识别，根据我们做表格识别的经验随便建议一下哈（请选择性参考）：参考表格识别任务，用html符号将表格表示为一个字符串，如\td这些html表格符号当成一个字符，类似的，公式识别中，可以把\frac当成一个字符（在字典中占一行），{1}这种也当成一个字符，表示分数中的数字1，不带括号的1就表示正常的数字1，然后就变成一个文本识别任务。

感谢大佬解答
