### ISSUE TITLE
DBNet检测模型，垂直文字和水平文字一样么 垂直的也可以直接标注完就进行训练么？

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#6130]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
对于DBnet检测模型来说，文字方向不重要，垂直的文本标注也可以训练
