### ISSUE TITLE
建议：paddleOCR onnx模型调用分离开

### ISSUE THREAD

**Issue by BerryRB** [PaddlePaddle/PaddleOCR#6132]
上周遇到一个使用场景，在aarch64架构下运行paddleOCR，但目前paddle没有直接支持aarch64架构的包，自行编译又遇到了比较多的问题，遂放弃。采用将paddleOCRF模型先转为onnx模型，onnxruntime可以直接在aarch64架构下通过pip安装。但通过目前官方提供的predict_system.py --use_onnx True的形式调用，脚本里面还有比较多的地方import paddle，实际并没有用到。如果把onnx的调用脚本单独提取出来用起来是不是更方便一些？因为一般用onnx以后就不会再安装paddle了。个人建议哈

**Comment by nissansz** [comment]
onnx可以转换为pytorch模型吗？转换完怎么调用？微信nlanguage
