### ISSUE TITLE
paddle 模型或onnx可以转换为pytorch模型吗？转换完怎么调用？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6136]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  2.4 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
paddle 模型或onnx可以转换为pytorch模型吗？转换完怎么调用？微信nlanguage

**Comment by LDOUBLEV** [comment]
建议直接用Paddle，预测部署都支持的很完善，如果有使用问题，可以提issue咨询，或者扫描PaddleOCR主页的微信群，加群讨论

**Comment by nissansz** [comment]
我转换成onnx了，这样无需加载paddle一堆东西，快很多 

PaddleOCR-release-2.4>paddle2onnx  --model_dir C:/Users/Ni/downloads/best_accuracy --model_filename inference.pdmodel --params_filename inference.pdiparams --opset_version 11 --save_file C:/Users/Ni/downloads/best_accuracy/test.onnx
