### ISSUE TITLE
SRN can use in chinese ocr ,Nice！where is the chinese pretrain_model? and what yaml work well in chinese ocr?

### ISSUE THREAD

**Issue by Meicsu199345** [PaddlePaddle/PaddleOCR#614]

**Comment by Meicsu199345** [comment]
thanks for u work! i want to use it!

**Comment by tink2123** [comment]
Sorry, we don't have the Chinese pretrain_model at the moment. 
Training Chinese model only needs to modify some parameters，like:
![图片](https://user-images.githubusercontent.com/31891223/91381183-54c2b000-e859-11ea-9f97-1e8caf117e83.png)
