### ISSUE TITLE
用自己的图片识别结果偏差大

### ISSUE THREAD

**Issue by Dearzxs** [PaddlePaddle/PaddleOCR#6141]
![17120](https://user-images.githubusercontent.com/52731865/166951104-b20ef091-0464-4761-80d8-037937b37bd3.jpg)
![11223](https://user-images.githubusercontent.com/52731865/166951120-8962bf61-5dc2-4185-876f-74ca8e5bf832.jpg)

**Comment by LDOUBLEV** [comment]
如果要缩小预测的检测框，可以修改参数：https://github.com/PaddlePaddle/PaddleOCR/blob/09187228d6e5f046182310f3adb8122ffac72900/tools/infer/utility.py#L53 把det_db_unclip_ratio 这个参数减小，可以缩小检测框

**Comment by Dearzxs** [comment]
> 如果要缩小预测的检测框，可以修改参数：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/09187228d6e5f046182310f3adb8122ffac72900/tools/infer/utility.py#L53
> 
> 把det_db_unclip_ratio 这个参数减小，可以缩小检测框

想问下检测时训练的样本都是远距离拍摄的，自己测试时近距离拍摄的图像检测不出来是什么原因，另外我把图像缩小后如图2检测，检测效果可以但是识别结果相差很大，是什么原因
