### ISSUE TITLE
hubserving 部署服务 可以开放出 https 请求吗

### ISSUE THREAD

**Issue by Altman7** [PaddlePaddle/PaddleOCR#6144]
hubserving 部署服务 可以开放出 https 请求吗

**Comment by andyjpaddle** [comment]
可否详细描述一下你的问题？

**Comment by Altman7** [comment]
> 可否详细描述一下你的问题？

我是用hubserving部署之后访问url为http://ip:port/predict/ocr_system
可以开发出https://ip:port/predict/ocr_system
这种https类型的请求地址
