### ISSUE TITLE
多线程执行TextSystem时报错：OSError: (External) CUDA error(719), unspecified launch failure. 

### ISSUE THREAD

**Issue by chenxindaaa** [PaddlePaddle/PaddleOCR#6151]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Pyhon3.8 Paddle：2.2 cuda11.1  PaddleOCR：2.3  问题相关组件/Related components：predict_system.py
- 运行指令/Command Code：默认参数
- 完整报错/Complete Error Message：
  File "D:\PycharmProject\PaddleOCR-release-2.3\detectorWithUI2.py", line 145, in run_system
    _, rec_res_all = text_sys(img1)
  File "D:\PycharmProject\PaddleOCR-release-2.3\detectorWithUI2.py", line 81, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "D:\PycharmProject\PaddleOCR-release-2.3\tools\infer\predict_rec.py", line 274, in __call__
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\FourTB\anaconda3\envs\paddle-cuda111\lib\threading.py", line 932, in _bootstrap_inner
    output = output_tensor.copy_to_cpu()
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\fluid\platform\gpu_info.cc:429)

**Comment by chenxindaaa** [comment]
我用了两个摄像头进行实时检测，但是跑一段时间后（几个小时或者几分钟）会报这个错误

**Comment by andyjpaddle** [comment]
windows不支持多线程读取数据哈
