### ISSUE TITLE
cuda启动错误

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6153]
predictor = inference.create_predictor(config)
OSError: (External) CUDA error(3), initialization error. 

  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:354)

**Comment by andyjpaddle** [comment]
先先确保`paddlepaddle-gpu`安装正确哈
