### ISSUE TITLE
关于修改字典后的再训练问题

### ISSUE THREAD

**Issue by yangtle** [PaddlePaddle/PaddleOCR#6164]
目前在做一个繁体古文字OCR：
对于识别部分，目前paddleocr只提供了基于mobile-backbone的网络以及繁体字典，经测试效果有待进一步提升。

1. 想在通用模型（server版本resnet34）实现，更新了繁体字典并使用预训练参数后，经过10w繁体数据集的训练，为什么loss一直处在100，acc自始至终为0？

2. 在mobile模型，不修改字典的前提下，使用textrender合成数据finetune，总是过拟合（只能针对训练部分的内容有提升，之前的识别泛化能力大大降低）。不知道有何提升的方法？

另：可以开源一部分繁体字数据集吗？或者更新一个resnet版本的繁体识别模型.....

**Comment by tink2123** [comment]
PP-OCRv3 策略今天开放了，可以参考最新的策略进行训练，相比mobile版本精度有大幅提升。

> 更新了繁体字典并使用预训练参数后，经过10w繁体数据集的训练，为什么loss一直处在100，acc自始至终为0？

请check下字典和数据标签是否是一一对应的

> 使用textrender合成数据finetune，总是过拟合

合成数据过于简单，建议在训练集中增加真实数据比例，或丰富合成策略。

**Comment by yfq512** [comment]
@yangtle @tink2123 我遇到了同样的问题，我找了个2000w中文繁体的数据集，并基于这个数据集在ppocr/utils/dict/chinese_cht_dict.txt的基础上从8k+行丰富到12k行（原字典没有某些繁体字），基于繁体中文预训练模型进行训练，loss慢慢在降，但acc一直是0这是为什么呢？
```
[2022/06/16 09:02:47] ppocr INFO: epoch: [1/500], global_step: 13250, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.052492, CTCLoss: 44.344723, SARLoss: 2.211270, loss: 46.556915, avg_reader_cost: 0.97218 s, avg_batch_cost: 1.70904 s, avg_samples: 128.0, ips: 74.89581 samples/s, eta: 1487 days, 1:42:42
[2022/06/16 09:03:01] ppocr INFO: epoch: [1/500], global_step: 13260, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.051048, CTCLoss: 43.939636, SARLoss: 2.160994, loss: 46.088230, avg_reader_cost: 0.61628 s, avg_batch_cost: 1.38149 s, avg_samples: 128.0, ips: 92.65338 samples/s, eta: 1486 days, 23:08:01
```

**Comment by yangtle** [comment]
前几个epoch可能acc一直为0，你可以试着看看后面epoch的效果。

**Comment by yangtle** [comment]
可以进一步的交流，我的微信号：YANG_TLe

**Comment by yfq512** [comment]
飞浆提供的预训练模型识别效果一般，同样的数据，我第一次训练忘记改字典了，第一个epoch效果就有很大的提升。现在改了字典训练出的模型简直在乱识别😂

**Comment by yangtle** [comment]
对，我觉得要是数据集多的话，增加一部分合成数据完全可以从头开始开训练。可以加微信进一步交流一下吗，难得找到有做这个繁体字的hh。

**Comment by yfq512** [comment]
训练到后面acc就正常了，微信已加

**Comment by nissansz** [comment]
ctcloss, sarloss, loss, 主要看哪个损失？大概训练多久，acc变正常？

**Comment by xuxiansheng2018** [comment]
> check下字典和数据标签是否是一一对应的

check下字典和数据标签是否是一一对应的   你好   这里的一一对应是什么意思 可以举个例子吗

**Comment by skyler9901** [comment]
> @yangtle @tink2123 我遇到了同样的问题，我找了个2000w中文繁体的数据集，并基于这个数据集在ppocr/utils/dict/chinese_cht_dict.txt的基础上从8k+行丰富到12k行（原字典没有某些繁体字），基于繁体中文预训练模型进行训练，loss慢慢在降，但acc一直是0这是为什么呢？
> 
> ```
> [2022/06/16 09:02:47] ppocr INFO: epoch: [1/500], global_step: 13250, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.052492, CTCLoss: 44.344723, SARLoss: 2.211270, loss: 46.556915, avg_reader_cost: 0.97218 s, avg_batch_cost: 1.70904 s, avg_samples: 128.0, ips: 74.89581 samples/s, eta: 1487 days, 1:42:42
> [2022/06/16 09:03:01] ppocr INFO: epoch: [1/500], global_step: 13260, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.051048, CTCLoss: 43.939636, SARLoss: 2.160994, loss: 46.088230, avg_reader_cost: 0.61628 s, avg_batch_cost: 1.38149 s, avg_samples: 128.0, ips: 92.65338 samples/s, eta: 1486 days, 23:08:01
> ```

请问你2000w中文繁体的数据集叫什么呀，请问开源吗？方便共享嘛

**Comment by yfq512** [comment]
> > @yangtle @tink2123 我遇到了同样的问题，我找了个2000w中文繁体的数据集，并基于这个数据集在ppocr/utils/dict/chinese_cht_dict.txt的基础上从8k+行丰富到12k行（原字典没有某些繁体字），基于繁体中文预训练模型进行训练，loss慢慢在降，但acc一直是0这是为什么呢？
> > ```
> > [2022/06/16 09:02:47] ppocr INFO: epoch: [1/500], global_step: 13250, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.052492, CTCLoss: 44.344723, SARLoss: 2.211270, loss: 46.556915, avg_reader_cost: 0.97218 s, avg_batch_cost: 1.70904 s, avg_samples: 128.0, ips: 74.89581 samples/s, eta: 1487 days, 1:42:42
> > [2022/06/16 09:03:01] ppocr INFO: epoch: [1/500], global_step: 13260, lr: 0.000016, acc: 0.000000, norm_edit_dis: 0.051048, CTCLoss: 43.939636, SARLoss: 2.160994, loss: 46.088230, avg_reader_cost: 0.61628 s, avg_batch_cost: 1.38149 s, avg_samples: 128.0, ips: 92.65338 samples/s, eta: 1486 days, 23:08:01
> > ```
> 
> 请问你2000w中文繁体的数据集叫什么呀，请问开源吗？方便共享嘛

是开源的，具体忘记了，太久远了
