### ISSUE TITLE
模型部署到ios端闪退

### ISSUE THREAD

**Issue by HanBridge** [PaddlePaddle/PaddleOCR#6166]
文字识别模型，配置文件为ch_PP-OCRv2_rec_distillation.yml，模型导出成inferrence模型测试正常，部署到iOS端侧闪退
- 系统环境/System Environment：mac os
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddle lite 2.9
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
[F  5/ 6 17:39:10.217 ...te-release-v2.9/lite/api/paddle_place.cc:88 TargetToStr] Check failed: (x < static_cast<int>(paddle::lite_api::TargetType::NUM)): 17!<17

**Comment by WenmuZhou** [comment]
请问用的哪个ios代码
