### ISSUE TITLE
关于transform配置的问题

### ISSUE THREAD

**Issue by axhionning** [PaddlePaddle/PaddleOCR#6170]
![image](https://user-images.githubusercontent.com/100411801/167252140-5930a09a-9ec7-49ef-854d-c185c0730b60.png)
![image](https://user-images.githubusercontent.com/100411801/167252170-ee0f77ee-d78b-40c3-b255-40a5816a316c.png)

以下问题皆基于2.4-release版本：
1.请问如果det部分训练不支持transform，为什么在det的官方默认db_mv3配置文件中会有相关参数呢？实际训练det会使用到吗？
2.如果没有用到，想在训练det部分用到的话，怎么修改呢？
期待您的回复。

**Comment by tink2123** [comment]
这里是文档说明有误，det 模型也是会使用到Transoforms的，具体的代码实现可以参考：https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/ppocr/data/imaug

**Comment by axhionning** [comment]
> 这里是文档说明有误，det 模型也是会使用到Transoforms的，具体的代码实现可以参考：https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/ppocr/data/imaug
好的，感谢回复
