### ISSUE TITLE
文字检测训练模型转inference 模型之后没有训练模型好

### ISSUE THREAD

**Issue by JoyshowXia** [PaddlePaddle/PaddleOCR#6172]
文字检测训练模型转inference 模型之后没有训练模型好，按照官方文档detection.md第5点说明，是预处理参数和后处理参数不一致导致，说明只给出了python的[inference model的预测预处理](https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2FPaddlePaddle%2FPaddleOCR%2Fblob%2Fc1ed243fb68d5d466258243092e56cbae32e2c14%2Ftools%2Finfer%2Fpredict_det.py%23L42)，对应的cpp_infer在哪里呢？

**Comment by tink2123** [comment]
cpp_infer 可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/readme_ch.md

**Comment by JoyshowXia** [comment]
我的意思是按照官方说明，predict_det.py预测时默认参数det_limit_side_len=960，det_limit_type='max'，我测试改成det_limit_side_len=736，det_limit_type='min'就可以了，之所以这么改，是因为训练使用的配置文件ch_det_res18_db_v2.0.yml，默认是屏蔽DetResizeForTest.image_shape了，所以infer_det.py时就是736，“min”这组参数。对此我有2个疑问：1、为了保证预处理和后处理参数一致，怎样知道并且能设置训练时候用的参数？比如：我想设置成det_limit_side_len=960，det_limit_type='max'；2、上述改的是predict_det.py代码，可是我最后需要C++部署，对应的C++代码要改哪里？

**Comment by tink2123** [comment]
1. 自己训练时，参数和配置文件保持一致，也可以根据预测效果针对自己的场景对参数微调
2.修改cpp infer 中的预处理部分：https://github.com/PaddlePaddle/PaddleOCR/blob/426db8dadc73135c3185d0b6fea7609b15dda142/deploy/cpp_infer/include/ocr_det.h#L78

**Comment by JoyshowXia** [comment]
> > #6652 不知道是否对你有用，或者你有什么新的见解，可以相互学习下
> 
> > 我的意思是按照官方说明，predict_det.py预测时默认参数det_limit_side_len=960，det_limit_type='max'，我测试改成det_limit_side_len=736，det_limit_type='min'就可以了，之所以这么改，是因为训练使用的配置文件ch_det_res18_db_v2.0.yml，默认是屏蔽DetResizeForTest.image_shape了，所以infer_det.py时就是736，“min”这组参数。对此我有2个疑问：1、为了保证预处理和后处理参数一致，怎样知道并且能设置训练时候用的参数？比如：我想设置成det_limit_side_len=960，det_limit_type='max'；2、上述改的是predict_det.py代码，可是我最后需要C++部署，对应的C++代码要改哪里？

是的，其实就一个原则：推理时的参数要与训练时保持一致。C++部署的示例代码preprocess_op.cpp中ResizeImgType0:Run只有max_size_len参数，所以要么对这个函数进行扩展，增加其他的Resize类型，要么在训练时修改配置文件。
