### ISSUE TITLE
请求适配Golang...

### ISSUE THREAD

**Issue by C4a15Wh** [PaddlePaddle/PaddleOCR#6175]
首先非常感谢飞浆团队能做出这么棒的OCR框架，但是PaddleOCR目前主要支持的是Python和C++，我们在实际生产中应用Python遇到了诸多问题（例如高并发环境下**OCR识别结果窜台**等），所以我们从三月份开始排查这个问题到现在，最后发现问题可能出在Python和其对应的框架上，目前团队内的意见是考虑用Go/C++重新实现一个服务端，因为团队内缺少C++程序员，所以目前优先考虑Golang，请问飞浆社区有意向适配一下Golang吗？如果可以的话，真的感激不尽！

**Comment by WenmuZhou** [comment]
你好，目前提供了cpp的demo

**Comment by C4a15Wh** [comment]
感谢解惑
