### ISSUE TITLE
Switching models

### ISSUE THREAD

**Issue by glitchyordis** [PaddlePaddle/PaddleOCR#6185]
![Screenshot 2022-05-09 083724](https://user-images.githubusercontent.com/99534415/167322735-afe7523a-1df0-418b-9b93-0b1c7e926bef.png)

System: Windows 10

Example code:
from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang='en',use_gpu=True, det_limit_side_len=3456) 
result = ocr.ocr(img1, cls=True)

Question:
Hi, I've installed PaddleOCR and used it with python. I noticed it is currently using the PP-OCRv2 version (see attached figure).  I would like to try the General PP-OCR server series model instead.

I've read the documents but I'm still confused as to where, what files I need to download and the changes required to the sample code above. 

Kindly assist me with this. Thank you.

**Comment by littletomatodonkey** [comment]
hi, you can use the following code to run switch your models.

```python
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(
    ocr_version="PP-OCR",
    det_model_dir="PaddleOCR_pub/inference/ch_ppocr_server_v2.0_det_infer/",
    rec_model_dir="PaddleOCR_pub/inference/ch_ppocr_server_v2.0_rec_infer/")  # need to run only once to download and load model into memory
img_path = 'PaddleOCR/doc/imgs/11.jpg'
result = ocr.ocr(img_path, cls=False)
for line in result:
    print(line)

# 显示结果
from PIL import Image

image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
```

For more details, please refer to whl.md:doc/doc_en/whl_en.md

**Comment by glitchyordis** [comment]
Hi, I noticed it is "ch_ppocr..", for both det and rec model. Is there one for the English language?

Also, I tried the code but got an SSLError. Can you guide me on these? Thanks. 

SSLError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
