### ISSUE TITLE
 NVIDIA Jetson AGX Xavier 安装 paddleocr 卡在  opencv-contrib-python

### ISSUE THREAD

**Issue by Liguanqin** [PaddlePaddle/PaddleOCR#6187]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
`
- NVIDIA Jetson AGX Xavier [16GB]
   * Jetpack 4.6 [L4T 32.6.1]
   * NV Power Mode: MAXN - Type: 0
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.300
   * cuDNN: 8.2.1.32
   * TensorRT: 8.0.1.6
   * Visionworks: 1.6.0.501
   * OpenCV: 4.1.1 compiled CUDA: NO
   * VPI: ii libnvvpi1 1.1.15 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70 `
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
自编译的paddle，paddlepaddle-gpu      2.2.2
- 运行指令/Command Code：
`pip install  paddleocr`
- 完整报错/Complete Error Message：
`Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (pyproject.toml) ... /
`

**Comment by Liguanqin** [comment]
漫长的等待后出现这个错误结果：

`  ERROR: Failed building wheel for opencv-contrib-python
Failed to build opencv-contrib-python
ERROR: Could not build wheels for opencv-contrib-python, which is required to install pyproject.toml-based projects
`

**Comment by littletomatodonkey** [comment]
你好，可以先安装可以在该平台上使用的opencv版本（建议>=4.1），然后使用pip install --no-deps paddleocr的方式安装，再安装下面的依赖(paddleocr根目录的requirements)

```
scikit-image
imgaug==0.4.0
pyclipper
lmdb
tqdm
numpy
visualdl
python-Levenshtein
cython
lxml
premailer
openpyxl
attrdict
```
