### ISSUE TITLE
空格被识别成求和符号

### ISSUE THREAD

**Issue by sihuo521** [PaddlePaddle/PaddleOCR#6189]
1. 标签文件
![image](https://user-images.githubusercontent.com/36940636/167330559-960be97a-e179-41a9-81d9-dc3f18d93208.png)

2. yml文件内 ：  use_space_char: True
3. 训练结果：
![image](https://user-images.githubusercontent.com/36940636/167330749-bd15d748-9336-44ca-a9f8-bbce3aa6f76d.png)

4. 识别结果
![image](https://user-images.githubusercontent.com/36940636/167330605-cbb729e5-3490-4a14-9b7e-a316d8b74b45.png)

疑问：
（1）标签文件是否需要标空格呢？
（2）有其他解决办法吗

**Comment by littletomatodonkey** [comment]
你好，这个看着是你自己训练的模型? 需要希望空格效果更好，需要在训练数据里添加空格的，这个看着是因为你的模型将求和标注为空格了，可以再排查下，我试了下paddleocr提供的模型，没有出现这样的问题

**Comment by sihuo521** [comment]
> 你好，这个看着是你自己训练的模型? 需要希望空格效果更好，需要在训练数据里添加空格的，这个看着是因为你的模型将求和标注为空格了，可以再排查下，我试了下paddleocr提供的模型，没有出现这样的问题

嗯，是我自己基于预训练模型重新训练的模型，我排查了一下，并没有把求和标注成空格。
唯一改动的是ppocr_keys_v1.txt里面的繁体字删掉了。我再试试不改动ppocr_keys_v1.txt会怎么样？按道理这个不会影响。

**Comment by sihuo521** [comment]
> 你好，这个看着是你自己训练的模型? 需要希望空格效果更好，需要在训练数据里添加空格的，这个看着是因为你的模型将求和标注为空格了，可以再排查下，我试了下paddleocr提供的模型，没有出现这样的问题

经过验证，确实是我删除繁体字的原因。
但是不知道为啥会影响呢？

**Comment by littletomatodonkey** [comment]
训练的模型的字典需要和预测的时候保持一致，不然会有映射问题

**Comment by sihuo521** [comment]
> 训练的模型的字典需要和预测的时候保持一致，不然会有映射问题

这个倒是保持一致呢，都是删除繁体字后的字典ppocr_keys_v2.txt。
可能还是跟预训练模型有关系吧，预训练模型里用的是ppocr_keys_v1.txt字典。

**Comment by littletomatodonkey** [comment]
嗯嗯，这种变更字典的话，需要更多的数据去训练

**Comment by sihuo521** [comment]
> 嗯嗯，这种变更字典的话，需要更多的数据去训练

嗯嗯，目前只有7000多，还是用原始字典吧。
感谢解惑。
