### ISSUE TITLE
跑paddleocr.py报错，是怎么回事。。。

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/PaddleOCR#619]
拿到代码，就直接上手跑了paddleocr.py， 结果报错：AttributeError: 'Namespace' object has no attribute 'use_zero_copy_run'。。。这个是怎么回事啊

**Comment by WenmuZhou** [comment]
能否描述一下环境并贴一下完整日志

**Comment by lmw0320** [comment]
我是win10的环境，后面查看了下py文件，发现可能是args中遗漏了这个参数，添加上去后，就解决了。
不过，正好有另外的问题想请教下,  det的模型参数，默认是DB，还有其他什么选项呢？

**Comment by WenmuZhou** [comment]
默认是只支持db的，你可以自己添加其他的算法，只需要添加后处理就行了

**Comment by lmw0320** [comment]
OK，感谢指点~
