### ISSUE TITLE
想请问一下，你将image 固定为3, 32, 320，转模型后预测有报错

### ISSUE THREAD

**Issue by wfm777** [PaddlePaddle/PaddleOCR#6196]
想请问一下，你将image 固定为3, 32, 320，转模型后预测有报错

    InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(x) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1595)
      [operator < conv2d > error]
吗

_Originally posted by @Babysun-ljh in https://github.com/PaddlePaddle/PaddleOCR/issues/5542#issuecomment-1057662706_

**Comment by littletomatodonkey** [comment]
你好，麻烦再具体说明下转化的脚本和报错信息，另外就是这个报错看着和shape无关，应该是模型权重没有初始化
