### ISSUE TITLE
Number of trainable parameters

### ISSUE THREAD

**Issue by HSILA** [PaddlePaddle/PaddleOCR#6198]
Hi,

Is there any straightforward way that I can find out how many trainable parameters are present in a model?

Thanks

**Comment by littletomatodonkey** [comment]
You can find out the trainable params using the following way.

```python
b = [i for i in model.parameters() if i.trainable == True]
```

**Comment by HSILA** [comment]
Thank you, and for future references, the full code is:
```
shapes = [i.shape for i in model.parameters() if i.trainable == True]
params = 0
for shape in shapes:
    params += np.prod(shape)
print(params)
```
Add before `# start train` in `train.py`.
