### ISSUE TITLE
🔥长图片识别问题

### ISSUE THREAD

**Issue by yfq512** [PaddlePaddle/PaddleOCR#6199]
使用python API方式通过增加和修改参数可以准确识别长图：
```
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(use_angle_cls=False, lang="ch", det_limit_type='min', det_limit_side_len=100, use_gpu=True)
result = ocr.ocr('test.jpg')
```
但是现在使用[PPOCR 服务化部署](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/pdserving/README_CN.md)去部署和测试，就不能准确识别长图，此时要怎么修改配置参数使之也能适配长图的识别呢？

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/71e8ae072f8085e91db40d5e23dee60a30707542/deploy/pdserving/web_service.py#L33

需要手动修改下这里的DetResizeForTest，设置一下det_limit_type和det_limit_side_len，目前pdserving里面还不支持检测超参的调整

**Comment by yfq512** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/71e8ae072f8085e91db40d5e23dee60a30707542/deploy/pdserving/web_service.py#L33
我参照代码修改为：DetResizeForTest(limit_type='min', limit_side_len=100), Div(255), 
启动服务后发现两个问题：
1. 长图片识别仍然不对，和没改之前识别一样；
2. 同一张图片，每post请求一次，GPU显存占用就明显提升一些，直至完全占满最后报错；

**Comment by yangy996** [comment]
给图片加白边框，高或宽小于640的就加边框到640，可以改善长图识别

**Comment by yangy996** [comment]
https://blog.csdn.net/YY007H/article/details/124973777，推荐这篇文章

**Comment by yfq512** [comment]
@yangy996 我试试，谢谢啦

**Comment by yfq512** [comment]
@yangy996 您分享的这篇文章404了，我测试的长图其实w，h都大于640（实际 images.shape=(6541, 800, 3)），主要是横纵比很大，这种要怎么改😄，我目前想到方案就是，把长图裁剪成若干小图在进行识别
![long](https://user-images.githubusercontent.com/52442277/172526177-17753c25-3107-407d-901f-65ed95f7a5ee.jpeg)

**Comment by whalefa1I** [comment]
> use_angle_cls=False, lang="ch", det_limit_type='min', det_limit_side_len=100, use_gp



> 

老哥你把后面的汉字删掉呢...https://blog.csdn.net/YY007H/article/details/124973777

**Comment by breakfox** [comment]
> @yangy996 您分享的这篇文章404了，我测试的长图其实w，h都大于640（实际 images.shape=(6541, 800, 3)），主要是横纵比很大，这种要怎么改😄，我目前想到方案就是，把长图裁剪成若干小图在进行识别 ![long](https://user-images.githubusercontent.com/52442277/172526177-17753c25-3107-407d-901f-65ed95f7a5ee.jpeg)

请问您最终解决这个问题了嘛？
