### ISSUE TITLE
请问想换文档内列出的其他模型怎么换？

### ISSUE THREAD

**Issue by SweeneyLi** [PaddlePaddle/PaddleOCR#62]
inference里的是model和params
其他模型下载下来是best_accuracy.pdmodel这种格式，改名报错
Error: Getting 'tensor_desc' is not supported by the type of var double_buffer_0. at (D:\1.7.2\paddle\paddle\fluid\framework\var_desc.cc:209)

**Comment by MissPenguin** [comment]
您好，best_accuracy.*格式的模型为persistable 模型，可以加载后重新训练，model+params格式的模型为inference 模型，删除了无关参数，用于预测部署。前者可以使用tools/export_model.py转换为后者，具体操作可参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/inference.md

**Comment by SweeneyLi** [comment]
非常感谢
