### ISSUE TITLE
PPOCRLabel标注工具

### ISSUE THREAD

**Issue by tkone2018** [PaddlePaddle/PaddleOCR#6201]
感谢标注工具开源，请问下PPOCRLabel关键信息标注的时候，标注完框以及关键字类别时，使用重新识别后会导致关键字类别为None，我猜原因是采用了预标注，请问能否关闭关键字类别的预标注，只打开文字识别预标注，谢谢

**Comment by Evezerest** [comment]
您好，如果需要使用关键信息标注则可以在启动时加上PPOCRLabel --kie True标签，如果不需要则直接启动PPOCRLabel就行，重新识别后关键字被替换的问题我们复现一下

**Comment by tkone2018** [comment]
@Evezerest 需要的，麻烦看下，谢谢
![image](https://user-images.githubusercontent.com/41476675/167383553-63971a7c-3106-4414-a807-43bc6e864bf7.png)

**Comment by tkone2018** [comment]
@Evezerest 需要的，麻烦看下，谢谢

**Comment by PeterH0323** [comment]
Hi @tkone2018 ，请问是需要【单个标注框】重新识别还是【本张图片标注框】重新识别？

**Comment by Evezerest** [comment]
目前来看，您可以先重新识别获得文本信息后再打kie标签

**Comment by tkone2018** [comment]
@PeterH0323 整张图，我刚试了下单个标注框重新识别不会出现覆盖None

**Comment by tkone2018** [comment]
@Evezerest 目前我是这样的

**Comment by PeterH0323** [comment]
或者可以这样，您先使用左下方的【自动标注】按钮去标注全部图片的框，然后再使用 kie 进行标注漏掉的，同时进行 kie 的类别标注

**Comment by tkone2018** [comment]
@PeterH0323 因为自动识别会识别所有的问题，我想是识别我需要的文字，所以目前是先边框然后重识别，再去标注类别的，对了，我想咨询下kie是必须有other类别吗，其实也就是必须要标注所有文本吗，谢谢

**Comment by PeterH0323** [comment]
@tkone2018  已根据您的需求，提交了 PR #6240 ，待合并之后可解决这个问题
