### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch.

### ISSUE THREAD

**Issue by Afrah-M** [PaddlePaddle/PaddleOCR#6202]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：paddleocr --image_dir C:\Users\user\Desktop\10.jpg  --det_model_dir C:\Users\user\Desktop\ppocrdata --rec_model_dir C:\Users\user\Desktop\ppocrdata\crop_img --rec_char_dict_path C:\Users\user\Desktop\ppocrdata\crop_img\rec_gt.txt --cls_model_dir C:\Users\user\Desktop\ppocrdata --use_angle_cls true
- 完整报错/Complete Error Message：
-  InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [5, 96, 3, 12] and the shape of Y = [5, 96, 4, 12]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
      [operator < elementwise_add > error]

**Comment by littletomatodonkey** [comment]
检测模型预测的话，需要保证长和款都是32的倍数，建议检查下预处理

**Comment by littletomatodonkey** [comment]
Your image should be pre-processed that width and height can be divived by 32 (this step  is done by default in paddleocr toolbox), please check again whether you changed the source code, or you can re-insntall  and try it.

**Comment by sunwangyan** [comment]
我也遇到了同样的错误，重新装了很多遍，也改了很多遍，没办法解决这个问题

**Comment by Aurora-Rong** [comment]
你怎么解决的呀，老哥  ，我也遇到找个问题了，按照他的方法不行呀

**Comment by Aminfaraji** [comment]
Hello, I got this error paddleocr, what should I do?
------------------------------------------------------------------
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [512, 128, 512] and the shape of Y = [256, 1, 512]. Received [512] in X is not equal to [256] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)  


algorithm ABINet
