### ISSUE TITLE
PGNet Nanxxx loss after few epochs

### ISSUE THREAD

**Issue by venki-lfc** [PaddlePaddle/PaddleOCR#6204]
Hello, I am trying to train the PGNet model to recognize German alphabets along with a few symbols. The German dataset I am using is a part of MLT 2019 dataset.  I use the pre-trained model provided on the GitHub page to start my training. But after few epochs (usually 8), the ctc_loss becomes nanxxx. I use 100 images for training. And I use a new character dictionary that contains alphabets, German umlauts, numbers and some symbols.
I tried to reduce the learning rate to 0.0001 but that is not helping either. Could you please tell me, what could be causing this problem? 

Here is what happens:
![pgnet1](https://user-images.githubusercontent.com/60582874/167393004-6bb6830a-562a-48c0-800a-a3420b24c487.JPG)

Here is the configuration file:
```
Global:
  debug: false
  use_gpu: false
  epoch_num: 15
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: ./output/pgnet_de/
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: false
  pretrained_model: ./pretrained_models/train_step1/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  valid_set: partvgg
  save_res_path: ./output/pgnet_de/predicts_pgnet.txt
  character_dict_path: ./train/char_dict.txt
  max_text_length: 50
  max_text_nums: 30
  tcl_len: 64
Architecture:
  model_type: e2e
  algorithm: PGNet
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
  Neck:
    name: PGFPN
  Head:
    name: PGHead
Loss:
  name: PGLoss
  tcl_bs: 64
  max_text_length: 50
  max_text_nums: 30
  pad_num: 36
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0001
  regularizer:
    name: L2
    factor: 0
PostProcess:
  name: PGPostProcess
  score_thresh: 0.5
  mode: fast
Metric:
  name: E2EMetric
  mode: A
  gt_mat_dir: ./train_data/total_text/gt
  character_dict_path: ./train/char_dict.txt
  main_indicator: f_score_e2e
Train:
  dataset:
    name: PGDataSet
    data_dir: ./train/
    label_file_list:
    - ./train/train.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTrain: null
    - PGProcessTrain:
        batch_size: 32
        min_crop_size: 24
        min_text_size: 4
        max_text_size: 512
    - KeepKeys:
        keep_keys:
        - images
        - tcl_maps
        - tcl_label_maps
        - border_maps
        - direction_maps
        - training_masks
        - label_list
        - pos_list
        - pos_mask
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 32
    num_workers: 8
Eval:
  dataset:
    name: PGDataSet
    data_dir: ./train/
    label_file_list:
    - ./train/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - E2ELabelEncodeTest: null
    - E2EResizeForTest:
        max_side_len: 768
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - texts
        - ignore_tags
        - img_id
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
```

Here is my character dictionary
[char_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/8650875/char_dict.txt)

Kindly let me know if there is a solution. Thanks!

**Comment by littletomatodonkey** [comment]
Hi, it's recomended to use our prertained model to finetune your model, learning rate can also be reduced

**Comment by venki-lfc** [comment]
> 

Hi You can see that I have used your pretrained model. I tried reducing the learning rate as well but I still get the NAN

**Comment by LDOUBLEV** [comment]
I found your ctc loss to be normal for the first 7 epochs.
But there is a question, is nan appearing every time at the 8th epoch?

suggestions:
- check your dataset
- Setting up gradient clipping in the optimizer

ClipGradByValue 
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/ClipGradByValue_en.html

https://github.com/PaddlePaddle/PaddleOCR/blob/8de06d2370e81e0ee1473d17925fb2e05295a0fe/ppocr/optimizer/optimizer.py#L77

**Comment by venki-lfc** [comment]
> I found your ctc loss to be normal for the first 7 epochs. But there is a question, is nan appearing every time at the 8th epoch?
> 
> suggestions:
> 
> * Check your dataset
> * Setting up gradient clipping in the optimizer
> * Try a higher version of paddle
> 
> ClipGradByValue https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/ClipGradByValue_en.html
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/8de06d2370e81e0ee1473d17925fb2e05295a0fe/ppocr/optimizer/optimizer.py#L77

Thanks for your reply. I will try on that and let you know.
But a small doubt: Theoretically I can train PGNet model for any languages right? I can train on my custom dataset and dictionary right? Or PGNet is just restricted to English?

**Comment by LDOUBLEV** [comment]
The parameters of the loss function need to be modified according to the number of characters to be recognized after modifying the dictionary. 
The default is to recognize 36 characters, including numbers and letters.

```

```

**Comment by venki-lfc** [comment]
> The parameters of the loss function need to be modified according to the number of characters to be recognized after modifying the dictionary. The default is to recognize 36 characters, including numbers and letters.

Hi, thanks for your reply. I modified the `pad_num: ` parameter from 36 to 73 now. This is the error I get now. Could you please tell me where should I make a correction?

```
  File "C:\Users\Venkatesan.KALAPATTI\Projects\PaddleOCR\tools\train.py", line 150, in <module>
    main(config, device, logger, vdl_writer)
  File "C:\Users\Venkatesan.KALAPATTI\Projects\PaddleOCR\tools\train.py", line 125, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\Users\Venkatesan.KALAPATTI\Projects\PaddleOCR\tools\program.py", line 251, in train
    loss = loss_class(preds, batch)
  File "C:\Users\Venkatesan.KALAPATTI\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Venkatesan.KALAPATTI\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Venkatesan.KALAPATTI\Projects\PaddleOCR\ppocr\losses\e2e_pg_loss.py", line 130, in forward
    ctc_loss = self.ctcloss(f_char, pos_list, pos_mask, label_list, label_t)
  File "C:\Users\Venkatesan.KALAPATTI\Projects\PaddleOCR\ppocr\losses\e2e_pg_loss.py", line 105, in ctcloss
    cost = paddle.nn.functional.ctc_loss(
  File "C:\Users\Venkatesan.KALAPATTI\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle\nn\functional\loss.py", line 1083, in ctc_loss
    loss_out = fluid.layers.warpctc(log_probs, labels, blank, norm_by_times,
  File "C:\Users\Venkatesan.KALAPATTI\Anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\layers\loss.py", line 605, in warpctc
    grad, loss_out = _C_ops.warpctc(
ValueError: (InvalidArgument) The value of Attr(blank) should be in interval [0, 73), but received
  [Hint: Expected blank < sequence_width, but received blank:73 >= sequence_width:37.] (at C:\home\workspace\Paddle_release\paddle\fluid\operators\warpctc_op.cc:61)
  [operator < warpctc > error]
```

**Comment by SaiKrishnaBala** [comment]
I'm stuck with a similar error. Apart from the default number of characters(36: 26 alphabets and 10 digits), i do have three special characters('/', '('. ')' ) in my dataset, so i've increated the pad_num to 39 from 36. But I'm getting the below error. Can someone please comment on this issue:
`0623 15:33:17.894275  5988 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
[2022/06/23 15:33:20] ppocr INFO: Initialize indexs of datasets:['./../data/input/labelled_data/train/train.txt']
[2022/06/23 15:33:20] ppocr INFO: Initialize indexs of datasets:['./../data/input/labelled_data/val/val.txt']
[2022/06/23 15:33:34] ppocr INFO: load pretrain successful from ./pretrain_models/train_step1/best_accuracy
[2022/06/23 15:33:34] ppocr INFO: train dataloader has 3 iters
[2022/06/23 15:33:34] ppocr INFO: valid dataloader has 20 iters
[2022/06/23 15:33:34] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 10 iterations
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/tools/program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/ppocr/losses/e2e_pg_loss.py", line 130, in forward
    ctc_loss = self.ctcloss(f_char, pos_list, pos_mask, label_list, label_t)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/ppocr/losses/e2e_pg_loss.py", line 105, in ctcloss
    cost = paddle.nn.functional.ctc_loss(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1125, in ctc_loss
    loss_out = fluid.layers.warpctc(log_probs, labels, blank, norm_by_times,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 605, in warpctc
    grad, loss_out = _C_ops.warpctc(
**ValueError: (InvalidArgument) The value of Attr(blank) should be in interval [0, 39), but received** 
  [Hint: Expected blank < sequence_width, but received blank:39 >= sequence_width:37.] (at /paddle/paddle/phi/infermeta/multiary.cc:1868)
  [operator < warpctc > error]
INFO 2022-06-23 15:33:44,161 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:44,161 launch_utils.py:343] terminate all the procs
ERROR 2022-06-23 15:33:44,161 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
ERROR 2022-06-23 15:33:44,161 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-06-23 15:33:48,165 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:48,165 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:48,166 launch.py:402] Local processes completed.
INFO 2022-06-23 15:33:48,166 launch.py:402] Local processes completed.`
