### ISSUE TITLE
关于eval_batch_step

### ISSUE THREAD

**Issue by 1037419569** [PaddlePaddle/PaddleOCR#6205]
在paddleocr 训练检测部分的时候，在配置文件中设置eval_batch_step: 5000 为什么有时候到了5000次迭代之后，在进行eval的时候，卡死 
![图片](https://user-images.githubusercontent.com/58407657/167397861-0bfda37e-15bd-4580-a45b-891fb1ac4c6a.png)
就像这样，一直都不动，有什么好的解决办法吗

**Comment by littletomatodonkey** [comment]
这种没有遇到过，试着修改eval dataloader的num worker=0试下呢？或者减少eval dataloader的batch size

**Comment by 1037419569** [comment]
> 这种没有遇到过，试着修改eval dataloader的num worker=0试下呢？或者减少eval dataloader的batch size

解决啦，就是应该是显存的问题，我把train的bs，num worker 设小了 就可以。 感谢感谢

**Comment by littletomatodonkey** [comment]
好的
