### ISSUE TITLE
程序训练时可能会hang住或产生僵尸进程

### ISSUE THREAD

**Issue by shengjie-shi** [PaddlePaddle/PaddleOCR#621]
在训练文字检测模型时（DB算法），程序可能会hang住，GPU的资源会被占用但是没有输出，log文件不再更新，也没有新的checkpoints输出。
paddle为1.8.3.post107-gpu版本，CUDA10.0，cuDNN7.6。
硬件资源足够。
训练时batch size为5

**Comment by WenmuZhou** [comment]
hang住的过程中，内存有增长吗

**Comment by shengjie-shi** [comment]
没有增长，内存/显存占用一直没变

**Comment by WenmuZhou** [comment]
这个问题出现的频繁吗

**Comment by shengjie-shi** [comment]
比较频繁，大概率出现的情况：
1. 调大batchsize（比如从5到8或10）
2. 增大了训练数据量（如200张图片变成500张或更多）

**Comment by WenmuZhou** [comment]
把把Global.num_workers设置小一些看看，我们下周会专门进行这方面的实验

**Comment by shengjie-shi** [comment]
num_workers是指TrainReader.num_workers吗？

我尝试一下，非常感谢！

期待进一步反馈。

**Comment by WenmuZhou** [comment]
对的

**Comment by simplew2011** [comment]
当前最新版本，这个问题似乎依旧。
设置以下，问题也会出现：
return paddle.reader.multiprocess_reader(readers, False, queue_size=200)
test_batch_size_per_card: 1
num_workers: 1

**Comment by littletomatodonkey** [comment]
可以试着进一步减小train_batch_size_per_card，
