### ISSUE TITLE
Question about the accuracy of PaddleOCR

### ISSUE THREAD

**Issue by Di-Ma-S21** [PaddlePaddle/PaddleOCR#6212]
Hi, 

Many thanks for releasing this OCR platform! Could we know the accuracy of the platform? 

Many thanks!

**Comment by littletomatodonkey** [comment]
The accuracy is evaluated on our dataset with 18k images, you can refer to our PP-OCRv2 report for more details ~

**Comment by Di-Ma-S21** [comment]
@littletomatodonkey Many thanks for your help!
