### ISSUE TITLE
关于PP-OCRv3繁体字模型不再适配竖排文字的问题

### ISSUE THREAD

**Issue by yangtle** [PaddlePaddle/PaddleOCR#6214]
相比之前的版本，中文繁体识别chinese_cht_PP-OCRv3_rec模型，经过测试不再适配“竖排文字”的识别。虽横排效果提升，但竖排效果很差（几乎不能识别）。

也经常看论坛，发现大家应用繁体字模型还是挺多的，而其实用到繁体字模型的场景多是竖排情况，比如古籍的识别等等。

所以，是否可以优化一下该问题。

**Comment by tink2123** [comment]
非常感谢您反馈的问题～ V3 的繁体中文模型在训练时更换了训练数据，没有考虑竖排文本的支持，近期会添加数据更新一版，更新完成后在此issue内与您同步。

**Comment by jx0453** [comment]
> 非常感谢您反馈的问题～ V3 的繁体中文模型在训练时更换了训练数据，没有考虑竖排文本的支持，近期会添加数据更新一版，更新完成后在此issue内与您同步。

您好，可以尽快更新这个竖排文本的问题吗~确实繁体字模型用竖排文字的情况还是很多的

**Comment by yangtle** [comment]
> 非常感谢您反馈的问题～ V3 的繁体中文模型在训练时更换了训练数据，没有考虑竖排文本的支持，近期会添加数据更新一版，更新完成后在此issue内与您同步。

请问这个有做相关的更新吗？

**Comment by StarDxxx** [comment]
中文的繁体字，单个字符该如何聚类呢~

**Comment by BaoBaoJianqiang** [comment]
> 我可以提供一个繁体字字典，大概2w个字符

2w个字符，也包括简体字的

**Comment by PandaBalls** [comment]
竖排古籍，识别完返回数据都是横排的断句。但是每个字识别的很准。
