### ISSUE TITLE
PPLabelV2 KIE 模式点击重新识别后，已设置的标签被重新设置为None

### ISSUE THREAD

**Issue by subaerial** [PaddlePaddle/PaddleOCR#6216]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle： 2.2.2 PaddleOCR：2.5 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch --kie True --gpu True
- 完整报错/Complete Error Message：无报错

**Comment by PeterH0323** [comment]
Hi @subaerial , 已根据您的需求，提交了 PR #6240 ，待合并之后可解决这个问题
