### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by ASDMartin** [PaddlePaddle/PaddleOCR#6221]
RuntimeError: (NotFound) Cannot open file C:\Users\中文/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1459)

**Comment by ASDMartin** [comment]
不是路径的错误？

**Comment by ASDMartin** [comment]
怎么修改那？

**Comment by zhangyingying520** [comment]
你看看你下载的推理模型是否正确

**Comment by MissPenguin** [comment]
建议具体描述下报错复现流程哈

**Comment by CaiRunz** [comment]
你这个可能是因为路径中有中文 "中文"
