### ISSUE TITLE
PP-OCRv3有更新服务端模型吗

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6224]
请问PP-OCRv3有更新服务端模型吗
![image](https://user-images.githubusercontent.com/37231239/167537230-303def40-5625-4493-912c-846679ab65a4.png)

**Comment by firdota** [comment]
同问

**Comment by xhw205** [comment]
同问

**Comment by zhangyingying520** [comment]
PP-OCRv3不再区分服务模型和轻量型模型，力争以轻量型模型的大小实现服务器模型的精度

**Comment by MissPenguin** [comment]
PP-OCRv3的效果已经超越PP-OCR server大模型，我们的目标是打造实用的轻量模型。

但考虑到部分场景下，大家可能也需要大模型，因此近期计划开源PP-OCRv3中提到的SVTR_Tiny中文模型，欢迎持续关注。

**Comment by ltm920716** [comment]
hello @MissPenguin，
请教一下您说的这个部分场景需要大模型是什么概念，是说轻量模型能满足大部分场景，但是最高精度依然是大模型，轻量模型在精度上还是会比大模型差一些对么，谢谢

**Comment by GivanTsai** [comment]
> 
我对比了下PP-OCRv3和PP-OCR server，好像PP-OCRv3比PP-OCR server差了不少

**Comment by GivanTsai** [comment]
> PP-OCRv3的效果已经超越PP-OCR server大模型，我们的目标是打造实用的轻量模型。
> 
> 但考虑到部分场景下，大家可能也需要大模型，因此近期计划开源PP-OCRv3中提到的SVTR_Tiny中文模型，欢迎持续关注。

我对比了下PP-OCRv3和PP-OCR server，好像PP-OCRv3比PP-OCR server差了不少
