### ISSUE TITLE
请问有开源训练数据吗

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6225]
PPOCR开源了许多预训练模型，请问有开源了用来训练模型的训练数据吗

**Comment by drenched9** [comment]
可以多看看md文档[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/dataset/datasets.md](url)

**Comment by GivanTsai** [comment]
> 可以多看看md文档[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/dataset/datasets.md](url)

我知道这个，目前列出来的都只是公开的几个小数据集，PaddleOCR开源的模型听开发人员说是百万级的数据量训练的，包括了他们合成的数据；

**Comment by drenched9** [comment]
> > 可以多看看md文档[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/dataset/datasets.md](url)
> 
> 我知道这个，目前列出来的都只是公开的几个小数据集，PaddleOCR开源的模型听开发人员说是百万级的数据量训练的，包括了他们合成的数据；

好吧，那可以去paddlehub上找一下，或者去aistudio里找。这里有个我之前找到的，可以参考一下：
https://paddleocr.bj.bcebos.com/dataset/total_text.tar

**Comment by MissPenguin** [comment]
PP-OCR系列模型的训练数据由开源数据集和合成数据组成，开源数据集就是大家熟悉的那些了，合成数据未开源，我们使用的合成工具是[text renderer](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/data_synthesis.md)，有需要的话可以自己收集语料进行合成哈
