### ISSUE TITLE
用彩图训练的模型，对于扫描的黑白文档识别效果很差，是要怎么改善？ 微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6229]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.4 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
用彩图训练的模型，对于扫描的黑白文档识别效果很差，是要怎么改善？ 微信nlanguage

**Comment by MissPenguin** [comment]
可以加个色彩变换的数据增广，再fine-tune一下，应该能提升对黑白文档的泛化能力

**Comment by nissansz** [comment]
要单独写代码？还是有自带的代码？

**Comment by MissPenguin** [comment]
> 要单独写代码？还是有自带的代码？

需要自己加一些代码

**Comment by nissansz** [comment]
有示例吗？

**Comment by MissPenguin** [comment]
> 有示例吗？

文本识别的基础增广入口：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/data/imaug/rec_img_aug.py#L24 可以在这里添加颜色变换的增广

**Comment by nissansz** [comment]
谢谢。不太会用。
