### ISSUE TITLE
paddleocr是否支持CUDA11.1及以上版本？

### ISSUE THREAD

**Issue by 123xian123** [PaddlePaddle/PaddleOCR#6230]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by 123xian123** [comment]
paddleocr是否支持CUDA11.1及以上版本？

**Comment by johnny0213** [comment]
Yes.

My env:

**Comment by johnny0213** [comment]
Yes.

My env:
Cuda11.1
cudnn 8.0
paddlepaddle-gpu              2.2.2.post111
paddleocr 2.0,2.4 2.5

**Comment by skywalkerzhang** [comment]
Hi, my cuda is 11.1 but I cannot install paddlepaddle-gpu, since currently, I'm using numpy >= 12.0 to use TensorFlow. It kind of troubles me.

Does paddleocr already support cuda11.1 or higher officially? If it is, could you plz change the documents? If not, could you plz update it?

**Comment by skywalkerzhang** [comment]
> Hi, my cuda is 11.1 but I cannot install paddlepaddle-gpu, since currently, I'm using numpy >= 12.0 to use TensorFlow. It kind of troubles me.
> 
> Does paddleocr already support cuda11.1 or higher officially? If it is, could you plz change the documents? If not, could you plz update it?


And I tried demo, get this RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)
python-BaseException

I know I can set use_gpu as false, but what if I wanna use GPU, what should I do?

**Comment by 123xian123** [comment]
> Yes.
> 
> My env: Cuda11.1 cudnn 8.0 paddlepaddle-gpu 2.2.2.post111 paddleocr 2.0,2.4 2.5

what your windows version? I wonder if paddleocr supports win11

**Comment by emigomez** [comment]
My issue was solved installing correct version of CUDA and cudnn

**Comment by MohieEldinMuhammad** [comment]
> -2.3.0-cp38-cp38-win_amd64.whl and I'm having the same problem, when I'm trying to train:

What is the version that worked with you ?
i'm windows 11, Cuda version is 11.8 is 11.8 not supported ?
