### ISSUE TITLE
分布式训练，num_workers=8 CPU只用和GPU数量一样的，请问这正常吗？

### ISSUE THREAD

**Issue by HandsLing** [PaddlePaddle/PaddleOCR#6232]
训练PPOCR的时候采用分布式训练，用了6张V100训练，num_workers设置为8，但是发现只有6个CPU核是用满的，其余CPU核是空的，请问这有办法解决吗

**Comment by littletomatodonkey** [comment]
设置的是train的num worker吧？另外就是看下其他的核一般很难打满，一般在50左右的利用率哈
