### ISSUE TITLE
标注工具无法生成execl

### ISSUE THREAD

**Issue by gewenpulan** [PaddlePaddle/PaddleOCR#6238]
使用最新的label工具中增加的表格识别功能，提示无法生成excel文件

CANNOT OPEN .xlsx. It could be one of the following reasons: Only support Windows | No python win32com
CANNOT OPEN .xlsx. It could be the following reasons: .xlsx is not existed

**Comment by Evezerest** [comment]
请安装xlrd=1.2.0

**Comment by ZTurboX** [comment]
> 请安装xlrd=1.2.0

也遇到这个问题，安装xlrd也会报错

**Comment by Evezerest** [comment]
有什么报错呢

**Comment by hf62580** [comment]
执行安装pywin32即可
pip install pywin32

**Comment by Mrfuhang** [comment]
> 执行安装pywin32即可 pip install pywin32

也会报错，是不是你们安装了xlsx工具啊
