### ISSUE TITLE
关于使用pplabel在标注表格时的一些疑问

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleOCR#6242]
1. 能否一次性标注所有表格？现有的模式是只能一张张标注么？
2. 如何进行表格结构的调整？readme中给出的使用方法是“将表格图像中有文字的单元格，在Excel中标记为任意标识符（如1）”。请问能稍微详细介绍么？不是很明白这个操作。
3. 在pplabel中对表格单元格内的文字进行位置标注和单元格内容重新识别的结果会直接修改已经生成的excel么？因为我在ubuntu系统下使用的wps，所以需要自己手动打开生成的exel文档，但是发现并没有随标注结果改变
4. 单元格内容重新识别的功能对跨两行以上的文本识别效果比较差

**Comment by liulei199409** [comment]
问题2：表格结构调整成和图片中表格一样的就行，比如有单元格合并，Excel对应调整，对于单元格里的内容随便写，不关心；
问题3：重新识别不会改变Excel；

**Comment by liu1073811240** [comment]
问个表格识别标注的问题： 标签里面的单元格信息（包括文字、坐标） 和 html格式字符串（<td></td>） 为什么没有形成一一的对应关系？

**Comment by liulei199409** [comment]
单元格信息与一个td标签元素里的内容是对应的

**Comment by liu1073811240** [comment]
但我发现标注软件导出的单元格里面没有用 空列表占位置，我感觉是对应不上的。不像原始的pubtab数据集有空列表占位置。

**Comment by liulei199409** [comment]
你可以把structure里的tokens还原成HTML，看看和Excel是不是对应的，我试过是没有问题的

**Comment by liu1073811240** [comment]
但是cell里面的tokens信息与 structuce里的每个<td&gt;不是对应的。感觉和pubtabnet数据标签不一样，这是怎么回事啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
你可以把structure里的tokens还原成HTML，看看和Excel是不是对应的，我试过是没有问题的

**Comment by liu1073811240** [comment]
就是我觉得每个单元格里面应该是要有对应标签的文字信息和坐标信息的。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
你可以把structure里的tokens还原成HTML，看看和Excel是不是对应的，我试过是没有问题的

**Comment by liulei199409** [comment]
cell里面的tokens信息不参与表格结构模型的训练的，只有坐标信息有用

**Comment by liulei199409** [comment]
cell里面的tokens信息，也就是单元格里的文本，没啥用，随便写就行，填空也行

**Comment by liulei199409** [comment]
我之前用labelme做的表格结构识别的标注，写的脚本转换成要求的格式

**Comment by liu1073811240** [comment]
能发给我看一下几张图片和对应的标签信息吗？有点不是很明白，感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
我之前用labelme做的表格结构识别的标注，写的脚本转换成要求的格式

**Comment by liu1073811240** [comment]
只根据cell里面的坐标信息，好像不能知道处于几行几列的哪个单元格吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
我之前用labelme做的表格结构识别的标注，写的脚本转换成要求的格式

**Comment by liulei199409** [comment]
cells单元格的顺序就是HTML中的单元格的顺序

**Comment by liu1073811240** [comment]
pubtabnet的数据标签是这样对应上的，但用paddle表格标注工具导出来却不一样。cells里面的tokens没有用空列表[]占位置。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
cells单元格的顺序就是HTML中的单元格的顺序

**Comment by liulei199409** [comment]
gt是HTML，需要把\替换为空就可以在浏览器打开看了，另外，这张图没有标注完，只标注了上半部分





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 只根据cell里面的坐标信息，好像不能知道处于几行几列的哪个单元格吧 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月13日(星期五) 上午9:53 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242) 
 
 
 
 
 
   
 我之前用labelme做的表格结构识别的标注，写的脚本转换成要求的格式

**Comment by liulei199409** [comment]
> pubtabnet的数据标签是这样对应上的，但用paddle表格标注工具导出来却不一样。cells里面的tokens没有用空列表[]占位置。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月13日(星期五) 上午10:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242) cells单元格的顺序就是HTML中的单元格的顺序 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

cells里面的tokens没有用空列表[]占位置，这句话是啥意思啊

**Comment by liu1073811240** [comment]
上面这张图是pubtabnet的标签。下面是paddle标注工具导出来的。
可以看到上面是有空列表占据一个单元格。而下面是没有的，那么就没有办法区分开这个单元格对应到图片里面的信息是空的情况。




&nbsp;发送&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





  
pubtabnet的数据标签是这样对应上的，但用paddle表格标注工具导出来却不一样。cells里面的tokens没有用空列表[]占位置。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月13日(星期五) 上午10:37 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242) cells单元格的顺序就是HTML中的单元格的顺序 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
cells里面的tokens没有用空列表[]占位置，这句话是啥意思啊

**Comment by liulei199409** [comment]
没有看到图片，你意思是一个空单元格，paddle没有进行标注吗

**Comment by liulei199409** [comment]
空单元格，paddle标注工具没有标注上，这个需要你手动添加吧

**Comment by liu1073811240** [comment]
在pubtabnet数据集中，图片中的红色框在 cells的tokens对应的信息会用空列表[]占个位置，而paddle里面导出的json文件却不会。


这个问题就是paddle表格标注没有把图片里面的空位值的标签加进去






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
没有看到图片，你意思是一个空单元格，paddle没有进行标注吗

**Comment by liulei199409** [comment]
图片看不到，可以用邮箱发一下吗以及JSON文件

**Comment by liu1073811240** [comment]
不知道怎么发，加我qq 1073811240



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 中午11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于使用pplabel在标注表格时的一些疑问 (Issue #6242)





 
图片看不到，可以用邮箱发一下吗以及JSON文件

**Comment by w-tim** [comment]
> 问题2：表格结构调整成和图片中表格一样的就行，比如有单元格合并，Excel对应调整，对于单元格里的内容随便写，不关心； 问题3：重新识别不会改变Excel；

请问，有办法单元格重新识别后刷新Excel吗？想要ocr后输出的正确excel内容

**Comment by hzy459176895** [comment]
想问下ocrlabel标注的是json另存，但是最新SLANet的yaml配置案例中，标签是txt文件  他们是一样的吗

**Comment by WenmuZhou** [comment]
目前虽然显示 的是json，但是实际报错下来是txt文件

**Comment by LeFuGang** [comment]
> 空单元格，paddle标注工具没有标注上，这个需要你手动添加吧

空单元格，是需要标注的吗？不然会报错，错误如下：

[2022/10/10 11:42:38] ppocr ERROR: When parsing line {"filename": "2.png", "split": "train", "imgid": 1, "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "<td", " colspan=\"2\"", ">", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["位", "置"], "bbox": [[38, 8], [80, 8], [80, 33], [38, 33]]}, {"tokens": ["地", "下", "室", "周", "边"], "bbox": [[252, 10], [318, 10], [318, 31], [252, 31]]}, {"tokens": ["屋", "面"], "bbox": [[441, 9], [480, 9], [480, 32], [441, 32]]}, {"tokens": ["功", "能"], "bbox": [[37, 28], [82, 28], [82, 57], [37, 57]]}, {"tokens": ["主", "控", "室", "/", "工", "具", "间"], "bbox": [[128, 33], [217, 33], [217, 54], [128, 54]]}, {"tokens": ["消", "防", "车", "活", "荷", "载"], "bbox": [[246, 31], [324, 31], [324, 53], [246, 53]]}, {"tokens": ["不", "上", "人", "屋", "面"], "bbox": [[370, 33], [436, 33], [436, 54], [370, 54]]}, {"tokens": ["上", "人", "屋", "面"], "bbox": [[485, 33], [537, 33], [537, 54], [485, 54]]}, {"tokens": ["风", "机", "房"], "bbox": [[580, 33], [621, 33], [621, 54], [580, 54]]}, {"tokens": ["限", "流", "电", "抗", "器", "室", "排", "烟", "机", "房", "/", "水", "泵", "房"], "bbox": [[637, 31], [818, 31], [818, 52], [637, 52]]}, {"tokens": [" ", "4", ".", "0"], "bbox": [[155, 62], [183, 62], [183, 87], [155, 87]]}, {"tokens": ["3", "5", ".", "0"], "bbox": [[267, 61], [303, 61], [303, 84], [267, 84]]}, {"tokens": ["0", ".", "5", " "], "bbox": [[387, 64], [415, 64], [415, 89], [387, 89]]}, {"tokens": ["2", ".", "0"], "bbox": [[496, 63], [525, 63], [525, 89], [496, 89]]}, {"tokens": ["7", ".", "0"], "bbox": [[585, 62], [613, 62], [613, 87], [585, 87]]}, {"tokens": ["7", ".", "0"], "bbox": [[654, 62], [682, 62], [682, 88], [654, 88]]}, {"tokens": ["7", ".", "0"], "bbox": [[733, 62], [760, 62], [760, 88], [733, 88]]}, {"tokens": ["(", "K", "N", "/", "m", ")"], "bbox": [[40, 58], [80, 58], [80, 77], [40, 77]]}, {"tokens": ["待", "识", "别"], "bbox": [[30, 70], [96, 70], [96, 94], [30, 94]]}]}}, error happened with msg: Traceback (most recent call last):
  File "/data/lefugang/ocr/paddleocr/PaddleOCR/ppocr/data/pubtab_dataset.py", line 118, in __getitem__
    outs = transform(data, self.ops)
  File "/data/lefugang/ocr/paddleocr/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform
    data = op(data)
  File "/data/lefugang/ocr/paddleocr/PaddleOCR/ppocr/data/imaug/label_ops.py", line 671, in __call__
    if 'bbox' in cells[bbox_idx] and len(cells[bbox_idx][
IndexError: list index out of range

**Comment by Evezerest** [comment]
需要的哈 可以看一下readme

**Comment by rpsipl2021** [comment]
can you please help us how to mark empty cells in text file?

**Comment by Cccchenyuan** [comment]
我也又同样的错误：if 'bbox' in cells[bbox_idx] and len(cells[bbox_idx][
IndexError: list index out of range是什么原因啊

**Comment by 18mingmin** [comment]
在做复杂合并单元格时，经常出现合并单元格识别错误的现象，软件自动识别的单元格标注框很小，会影响合并单元格结构的训练吗？如果标注时把标注框拉到单元格大小可以提高训练效果吗

**Comment by deeplearningers** [comment]
我要训练的话，调整单元格框的顺序和内容后，直接导出gt.txt就行吧？excel貌似没有用啊？

**Comment by zzz-zyq** [comment]
> 我要训练的话，调整单元格框的顺序和内容后，直接导出gt.txt就行吧？excel貌似没有用啊？

excel就是被用于导出gt.txt的，导出正确之后excel没有用的，不会被用于训练。训练标签就只需要gt.txt

**Comment by zzz-zyq** [comment]
> 在做复杂合并单元格时，经常出现合并单元格识别错误的现象，软件自动识别的单元格标注框很小，会影响合并单元格结构的训练吗？如果标注时把标注框拉到单元格大小可以提高训练效果吗

我也有过这个想法，尝试过这么做，后来观察结果感觉没有什么提高。尤其是在我的表格框中有某些格是单行合并很多列的情况，标注很长的矩形甚至似乎起到了反作用。
但是在我看过单元格和文字识别进行匹配的逻辑之后（表格识别类有个match方法），我的直觉是单元格检测框尽可能填充单元格的话，才能更好匹配文字识别内容。

**Comment by zzz-zyq** [comment]
> 我也又同样的错误：if 'bbox' in cells[bbox_idx] and len(cells[bbox_idx][ IndexError: list index out of range是什么原因啊

excel里的单元格数量和你在PPOCRLable里绘制的矩形框的数量不匹配。
