### ISSUE TITLE
paddle 250万彩图训练的crnn模型,追加25万黑白图训练，得到的模型 对黑白图明显改善了，彩图效果明显变差了， 是要将两种数据混合进行训练，才能同时效果好？微信nlanguage  

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6244]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

paddle 250万彩图训练的crnn模型,追加25万黑白图训练，得到的模型
对黑白图明显改善了，彩图效果明显变差了，
是要将两种数据混合进行训练，才能同时效果好？

微信nlanguage

**Comment by Gmgge** [comment]
1.混合训练可以相对简单的同时提升两者效果。
2.因为模型在训练的时候会逐渐遗忘预训练的规律，如果非要先后训练的话，需要调小学习率并减少批次等等微调，相对来说难度不可预知。

**Comment by nissansz** [comment]
日语4200个字符。要怎样准备训练数据集才能准确率高?
500万随机黑白数据+26万彩色语句图片？

**Comment by hbulaoma** [comment]
日文很简单，彩色数据至少也得和黑白样本数量差不多吧。不然主要学习的是黑白样本了

**Comment by nissansz** [comment]
我是搞反了。
先是拿了270万张彩色图不断训练。
现在改为25万黑白+之前的270万
这样训练
