### ISSUE TITLE
利用PPOCRLabel点击表格识别按钮会出现闪退的问题

### ISSUE THREAD

**Issue by liu1073811240** [PaddlePaddle/PaddleOCR#6246]
利用PPOCRLabel点击表格识别按钮会出现闪退的问题， 并且这过程中出现 两个多G的 python.exe.15484.dmp文件

**Comment by Evezerest** [comment]
你好，请发送一下你的环境和图片，我们测试一下

**Comment by Kawhi8087** [comment]
我也有同样的问题，打开图片后点击表格识别按钮就卡住
https://user-images.githubusercontent.com/44192465/170233690-bb80d24b-c614-4303-a078-677bb282303d.png

**Comment by Evezerest** [comment]
你好，请卸载xlrd，然后重新安装xlrd==1.2.0
