### ISSUE TITLE
PP-OCRv3识别阶段的resize_norm_img_svtr函数采用的resize方式会使图片的宽高比发生变化，图片发生形变，导致识别出现问题啊，改成保持宽高比不变的形式就识别对了

### ISSUE THREAD

**Issue by liulei199409** [PaddlePaddle/PaddleOCR#6247]
PP-OCRv3识别阶段的resize_norm_img_svtr函数采用的resize方式会使图片的宽高比发生变化，图片发生形变，导致识别出现问题啊，改成保持宽高比不变的形式就识别对了
改之前：

<img width="859" alt="微信图片_20220511113603" src="https://user-images.githubusercontent.com/34273622/167764712-96ecdcfd-34ed-4bdd-ae58-c5ba8fa26982.png">

改之后：
<img width="904" alt="6f5d46e187487546714392cdc6e5a6f" src="https://user-images.githubusercontent.com/34273622/167763551-6eb4087e-4972-4869-8a23-10e695f7b4a9.png">

**Comment by Topdu** [comment]
resize_norm_img_svtr是论文SVTR的预处理方法，在使用PP-OCRv3识别推理的时候不需要使用`--rec_algorithm`指定算法名称，使用默认的预处理方式即是保持宽高比不变的方式。

**Comment by andyjpaddle** [comment]
PP-OCRv3识别推理的时候`--rec_algorithm`是`SVTR_LCNet`，注意和原始`SVTR`的区别哈

**Comment by liulei199409** [comment]
好的，感谢

**Comment by jaycecd** [comment]
> PP-OCRv3识别阶段的resize_norm_img_svtr函数采用的resize方式会使图片的宽高比发生变化，图片发生形变，导致识别出现问题啊，改成保持宽高比不变的形式就识别对了 改之前：
> 
> <img alt="微信图片_20220511113603" width="859" src="https://user-images.githubusercontent.com/34273622/167764712-96ecdcfd-34ed-4bdd-ae58-c5ba8fa26982.png">
> 
> 改之后： <img alt="6f5d46e187487546714392cdc6e5a6f" width="904" src="https://user-images.githubusercontent.com/34273622/167763551-6eb4087e-4972-4869-8a23-10e695f7b4a9.png">

想问一下这些红色的竖线：
![image](https://user-images.githubusercontent.com/33342388/168012083-93d8581d-9087-4d69-88f9-7398fb021480.png)
是原图就有的吗？还是ppocr算法识别后添加上的？这个竖线的作用是什么？

**Comment by liulei199409** [comment]
> > PP-OCRv3识别阶段的resize_norm_img_svtr函数采用的resize方式会使图片的宽高比发生变化，图片发生形变，导致识别出现问题啊，改成保持宽高比不变的形式就识别对了 改之前：
> > <img alt="微信图片_20220511113603" width="859" src="https://user-images.githubusercontent.com/34273622/167764712-96ecdcfd-34ed-4bdd-ae58-c5ba8fa26982.png">
> > 改之后： <img alt="6f5d46e187487546714392cdc6e5a6f" width="904" src="https://user-images.githubusercontent.com/34273622/167763551-6eb4087e-4972-4869-8a23-10e695f7b4a9.png">
> 
> 想问一下这些红色的竖线： ![image](https://user-images.githubusercontent.com/33342388/168012083-93d8581d-9087-4d69-88f9-7398fb021480.png) 是原图就有的吗？还是ppocr算法识别后添加上的？这个竖线的作用是什么？


自己添加的单字符切分的算法，红线只是一个初版的切分的字符的起始x坐标，又优化了下：
![image](https://user-images.githubusercontent.com/34273622/168013114-dfbf5ee0-c114-4253-bb25-2521b2446ad0.png)

**Comment by jaycecd** [comment]
> > > PP-OCRv3识别阶段的resize_norm_img_svtr函数采用的resize方式会使图片的宽高比发生变化，图片发生形变，导致识别出现问题啊，改成保持宽高比不变的形式就识别对了 改之前：
> > > <img alt="微信图片_20220511113603" width="859" src="https://user-images.githubusercontent.com/34273622/167764712-96ecdcfd-34ed-4bdd-ae58-c5ba8fa26982.png">
> > > 改之后： <img alt="6f5d46e187487546714392cdc6e5a6f" width="904" src="https://user-images.githubusercontent.com/34273622/167763551-6eb4087e-4972-4869-8a23-10e695f7b4a9.png">
> > 
> > 
> > 想问一下这些红色的竖线： ![image](https://user-images.githubusercontent.com/33342388/168012083-93d8581d-9087-4d69-88f9-7398fb021480.png) 是原图就有的吗？还是ppocr算法识别后添加上的？这个竖线的作用是什么？
> 
> 自己添加的单字符切分的算法，红线只是一个初版的切分的字符的起始x坐标，又优化了下： ![image](https://user-images.githubusercontent.com/34273622/168013114-dfbf5ee0-c114-4253-bb25-2521b2446ad0.png)

我还以为是识别的原图就有这些红色的竖线，惊讶这些竖线都把文字挡住了，还能识别这么好~~原来是你在识别过程中自己画上去的
![01021F48](https://user-images.githubusercontent.com/33342388/168014212-9cedb6f7-3f8c-4de4-a5f8-051012dfb7df.png)

**Comment by songkq** [comment]
@liulei199409 请问这个单字符切分方法怎么实现的
