### ISSUE TITLE
GPU版的paddleocr使用python进行推理的时候可以切换CPU/GPU吗？

### ISSUE THREAD

**Issue by UlyssesFatty** [PaddlePaddle/PaddleOCR#6249]
如题

**Comment by LDOUBLEV** [comment]
可以切换，参考参数:https://github.com/PaddlePaddle/PaddleOCR/blob/8de06d2370e81e0ee1473d17925fb2e05295a0fe/paddleocr.py#L391
ppocr 参数介绍：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/whl.md#5-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

--use_gpu=False   
--use_gpu=True
