### ISSUE TITLE
使用opt工具将推理模型优化为Paddle-Lite模型时指定--valid_targets=rockchip_npu无法转换

### ISSUE THREAD

**Issue by PaulX1029** [PaddlePaddle/PaddleOCR#6252]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：./opt --model_file=./ch_PP-OCRv2_det_slim_quant_infer/ch_PP-OCRv2_det_slim_quant_infer/inference.pdmodel  --param_file=./ch_PP-OCRv2_det_slim_quant_infer/ch_PP-OCRv2_det_slim_quant_infer/inference.pdiparams  --optimize_out=./ch_PP-OCRv2_det_slim_opt --valid_targets=rockchip_npu  --optimize_out_type=naive_buffer
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/77143808/167817430-31ee553e-39bf-434f-a83b-fb287010c56b.png)

**Comment by PaulX1029** [comment]
paddle-lite release/v2.10版本，希望能尽快获得您的回复！

**Comment by LDOUBLEV** [comment]
看下Error信息；

在npu上存在一些不支持的算子；导致模型转换失败

./opt --print_all_ops=true可以查看当前 Paddle Lite 支持的OP

**Comment by PaulX1029** [comment]
请问 [LDOUBLEV] ：
我该怎么样才能让他转换成功呢？此npu不支持这些算子的话就没法转换为对应的nb模型了吗？

**Comment by LDOUBLEV** [comment]
> 此npu不支持这些算子的话就没法转换为对应的nb模型了吗？

目前是这样的，可以在paddlelite下提issue问下他们是否有对应支持计划:
https://github.com/PaddlePaddle/Paddle-Lite/issues
