### ISSUE TITLE
PaddleOCR/deploy/andriod_demo中替换了Paddle-Lite库和asserts里的模型后，demo闪退无法打开

### ISSUE THREAD

**Issue by PaulX1029** [PaddlePaddle/PaddleOCR#6255]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux、android11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/77143808/167850612-7b0317bb-3951-414a-aeea-bfc7986414f8.png)

**Comment by LDOUBLEV** [comment]
替换了哪个版本的paddlelite预测库和模型呢？

看报错是你用的paddlelite预测库不支持你的模型，模型有个io_copy操作没有支持

**Comment by PaulX1029** [comment]
谢谢，通过重新编译opt工具转换模型后已经解决！

**Comment by Albert556** [comment]
使用android demo替换ch_ocr_v3模型就会出现io_copy错误

**Comment by luomo0101** [comment]
hi
@PaulX1029
能说下具体解决的步骤吗，这边更换v3模型后也有此报错，不知道该如何解决。

**Comment by yangy996** [comment]
> hi @PaulX1029 能说下具体解决的步骤吗，这边更换v3模型后也有此报错，不知道该如何解决。

不要替换，c++代码处理都不一样，官方还未更新到v3版本
