### ISSUE TITLE
请问整体识别的评估指标F-score的指标从哪里看呢？

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#6256]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
端对端指标https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/PP-OCRv3_introduction.md#4-%E7%AB%AF%E5%88%B0%E7%AB%AF%E8%AF%84%E4%BC%B0

**Comment by qqqqq127** [comment]
> 端对端指标https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/PP-OCRv3_introduction.md#4-%E7%AB%AF%E5%88%B0%E7%AB%AF%E8%AF%84%E4%BC%B0

如果我想要评估我自己训练的模型的整体识别指标，应该用什么指令呢？
