### ISSUE TITLE
PP-OCRv3 版本严重缺字

### ISSUE THREAD

**Issue by mazhen2009** [PaddlePaddle/PaddleOCR#6257]
我们测试了 PP-OCRv3 模型，与 v2 相比，效果和速度有所提升。但是缺字严重，我们在本地预测 和demo 页面都有相同情况。

在 demo 页面 https://www.paddlepaddle.org.cn/hub/scene/ocr  测试下面的图片，“一二三 ”会缺失。

![微信截图_20220511222827](https://user-images.githubusercontent.com/5170209/167874785-08429f9d-dcb4-4ea8-8960-30c3cdf3a3f0.png)

**Comment by LDOUBLEV** [comment]
demo 页面 https://www.paddlepaddle.org.cn/hub/scene/ocr  近期会更新，目前用的还是V2的模型；

下面是我用V3的模型测试结果：
<img width="737" alt="image" src="https://user-images.githubusercontent.com/26592129/167978447-a4647de0-fe7c-4929-81c1-675925613d71.png">

![image](https://user-images.githubusercontent.com/26592129/167978488-59820ffa-4f09-42c6-91f2-368b1ac14e35.png)
