### ISSUE TITLE
Cell Bounding box coordinates?

### ISSUE THREAD

**Issue by marc-philipp-knechtle** [PaddlePaddle/PaddleOCR#6258]
Is it possible to get the cells bounding box coordinates? 
I reached the point where it's possible to extract everything as `html` and `xlsx` but I did not found any option to get the coordinates of the cells. 

Is this possible?

**Comment by andyjpaddle** [comment]
could you describe your question more detail?

**Comment by marc-philipp-knechtle** [comment]
of course ;) 

I found the following code [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/quickstart_en.md#223) (section 2.2.3 - table recognition): 

```
import os
import cv2
from paddleocr import PPStructure, save_structure_res


def main():
    table_engine = PPStructure(layout=False, show_log=True)

    save_folder = 'sample_output_ordner'
    img_path = 'sample_input_image_file'
    img = cv2.imread(img_path)
    result = table_engine(img)
    save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

    for line in result:
        line.pop('img')
        print(line)
```
I run this on an image containing just one table and nothing else.
This code returns in `result` a dict with one item `Table` which is as expected. 
Additionally, this item table has its `bbox` bounding-box coordinates. 
Additionally, this code creates a `.xlsx` file which contains the table structure + text recognition. 

But I wondered whether there is the possibility to get the `bbox` coordinates of the single cells written in the `.xlsx` file. 
Is there any option to achieve this or do I need to elaborate further on a section of my processing? 

Thank you very much ;)

**Comment by WenmuZhou** [comment]
now ,we support to get cell box from PPStructure, just set `return_ocr_result_in_table=True` when call table_engine
