### ISSUE TITLE
Question about using multi-lingual model

### ISSUE THREAD

**Issue by Di-Ma-S21** [PaddlePaddle/PaddleOCR#6259]
Hi, 

Many thanks for releasing PaddleOCR platform! From the website: [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/quickstart_en.md#212-multi-language-model](url), we noticed that we can specify the language parameter `--lang` to define which language model is used to read texts in images.  

Could we know if we can pass several languages (e.g., English+French+Germany) at once to read texts or we can only specify one language? Just in case there exist more than 1 languages in an image (e.g., English+French, English+Arabic) need to be recognised at once. 

Many thanks for your help!

**Comment by andyjpaddle** [comment]
Currently，the recognition model is not supported for several languages at once, you can training your model on your own dataset(e.g. English+Arabic), it can have the same effect.

**Comment by Di-Ma-S21** [comment]
@andyjpaddle Many thanks for your help!
