### ISSUE TITLE
ImportError: DLL load failed while importing core_avx: 找不到指定的模块。

### ISSUE THREAD

**Issue by jandy0414** [PaddlePaddle/PaddleOCR#6260]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.9.12
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.5.0.3  

执行时报错：
![image](https://user-images.githubusercontent.com/35617197/167974862-83253859-1ac0-41ea-b3c6-abb04e0bf0cc.png)

**Comment by andyjpaddle** [comment]
先确保paddle安装正确哈  https://www.paddlepaddle.org.cn/documentation/docs/zh/2.3rc/install/index_cn.html

**Comment by jandy0414** [comment]
> 先确保paddle安装正确哈 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.3rc/install/index_cn.html

![image](https://user-images.githubusercontent.com/35617197/168184586-a7041cc2-3345-44b2-92f9-1840723dd2d7.png)
这算支持吧？

这安装也没有报错呀
![image](https://user-images.githubusercontent.com/35617197/168184888-5f01d37e-ede2-45b0-8e1a-2f53d43af25b.png)

可 import paddle 就报错了呀？？
![image](https://user-images.githubusercontent.com/35617197/168184969-8415c099-b721-4379-a586-d4bc940525db.png)

**Comment by jandy0414** [comment]
![image](https://user-images.githubusercontent.com/35617197/168185045-ffdc26f5-b87b-49c9-b836-b737b19a6324.png)
这个版本支持吗？

**Comment by jandy0414** [comment]
我尝试了，安装CPU版本，也是一样的问题。
再尝试了，把python 版本降为3.6 ，也是一样的问题。
再尝试了，把python 版本降为3.10 ，也是一样的问题。

我的系统是win11  这个有关系吗？？

**Comment by jandy0414** [comment]
ubuntu环境下跑cpu 的正常处理。  
跑GPU 把这个错误，怎么解决???
错误如图：
![image](https://user-images.githubusercontent.com/35617197/168191746-56fe4a28-6d75-4698-82b8-a9fca69da573.png)

**Comment by andyjpaddle** [comment]
请参考paddle官网页面的安装说明， https://www.paddlepaddle.org.cn/documentation/docs/zh/2.3rc/install/index_cn.html ，确保安装正确后再使用paddleocr相关的，paddle安装问题可以到 https://github.com/PaddlePaddle/Paddle 提问

**Comment by siran575** [comment]
同问
![1660554781366](https://user-images.githubusercontent.com/73805034/184608956-1132a519-2639-49cb-b5b9-9cea5510bea4.png)
