### ISSUE TITLE
PP-OCRv3上线后其他模型准确率下降的问题

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleOCR#6265]
使用predict_rec.TextRecognizer(args)方法，只更改模型路径进行文字识别，ch_PP-OCRv3_rec_infer的准确率可以达到55%，但是使用ch_ppocr_mobile_v2.0_rec_infer和ch_PP-OCRv2_rec_infer，设置args.rec_algorithm = 'CRNN'，推理模型的准确率分别只有0.9%和2%。整个paddleocr已经更新到2.5版本。这个结果是因为适配PP-OCRv3后处理过程有改动么？

**Comment by andyjpaddle** [comment]
改一下rec_image_shape哈，V3默认的shape是3，48，320 ，此外，预处理也和v2有些不同，如果需要用v2的模型，可以使用旧代码

**Comment by huawenyu2020** [comment]
> 使用predict_rec.TextRecognizer(args)方法，只更改模型路径进行文字识别，ch_PP-OCRv3_rec_infer的准确率可以达到55%，但是使用ch_ppocr_mobile_v2.0_rec_infer和ch_PP-OCRv2_rec_infer，设置args.rec_algorithm = 'CRNN'，推理模型的准确率分别只有0.9%和2%。整个paddleocr已经更新到2.5版本。这个结果是因为适配PP-OCRv3后处理过程有改动么？

您好，十分钟完成 PP-OCRv3 识别全流程实战这个项目在线运行到1.2报错没有No module named 'pypandoc'，在1.1配置环境时正克隆到 'PaddleOCR'...
remote: Enumerating objects: 35573, done.
remote: Counting objects: 100% (243/243), done.
remote: Compressing objects: 100% (145/145), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
请问是版本原因吗？谢谢
