### ISSUE TITLE
ppocr 检测+分类+识别 串联推理 在开启gpu设置后，onnx模型速度比inference模型速度要慢很多，这是正常的吗？

### ISSUE THREAD

**Issue by yueyueshine** [PaddlePaddle/PaddleOCR#6266]
inference 模型推理结果
![截屏2022-05-12 下午4 18 13](https://user-images.githubusercontent.com/66232759/168025230-b86a1f4d-2fee-4f4a-9c25-7e64c20b74c8.png)

onnx模型推理结果
![截屏2022-05-12 下午4 20 45](https://user-images.githubusercontent.com/66232759/168025496-73e12cc8-f7d1-4eca-bc42-ad14f7e9a2be.png)

**Comment by zhenglilei** [comment]
首先要确认 onnx 推理运行时是否使用了 GPU，目测没有。
