### ISSUE TITLE
关于表格识别标注导出annotation.json的问题

### ISSUE THREAD

**Issue by liu1073811240** [PaddlePaddle/PaddleOCR#6268]
1. annotation.json标签里面的单元格信息（包括文字、坐标） 和 html格式字符串（<td></td>） 为什么没有像pubtabnet数据集形成一一的对应关系？

**Comment by WenmuZhou** [comment]
因为不需要啊

**Comment by liu1073811240** [comment]
不需要这样的数据集能训练出来吗？

**Comment by WenmuZhou** [comment]
本质上，pintab数据集也不是一一对应的，只是td标签对应cell会有框和文字

**Comment by liu1073811240** [comment]
对啊，我想着标注工具导出的json文件中，td标签对应cell也会有框和文字啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 凌晨0:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于表格识别标注导出annotation.json的问题 (Issue #6268)





 
本质上，pintab数据集也不是一一对应的，只是td标签对应cell会有框和文字

**Comment by WenmuZhou** [comment]
现在没有吗

**Comment by liu1073811240** [comment]
不需要这样能训练出效果？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 上午7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于表格识别标注导出annotation.json的问题 (Issue #6268)





 
因为不需要啊
