### ISSUE TITLE
V3 检测的训练模型文件中 student 模型出处？

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#6271]
![image](https://user-images.githubusercontent.com/18033495/168045086-5845d6c0-8d5a-4110-a24a-e46156ce43b6.png)

这个 student 模型大小为 2.5M，请问这个模型是怎么得来的？在我这边的测试集中效果下降。

**Comment by LDOUBLEV** [comment]
> 在我这边的测试集中效果下降。

和哪个模型比效果下降？

student模型是蒸馏得到的，参考PPOCRV3检测的训练策略：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/PP-OCRv3_introduction.md#2-%E6%A3%80%E6%B5%8B%E4%BC%98%E5%8C%96
