### ISSUE TITLE
评估结果所用数据集

### ISSUE THREAD

**Issue by linxid** [PaddlePaddle/PaddleOCR#6272]
![image](https://user-images.githubusercontent.com/16094085/168066388-486a970e-3d3e-4538-8116-06b0520bf36a.png)
在PP-OCR V3的介绍里面，文本检测，识别以及端到端的方案，评测分别是在什么数据集上进行的，是否有评测方案，我们能复现评测结果。

**Comment by andyjpaddle** [comment]
数据集暂未公开哈
