### ISSUE TITLE
训练SDMGR报错

### ISSUE THREAD

**Issue by yanziwu621** [PaddlePaddle/PaddleOCR#6275]
用自己的数据训练，loss出现了nan,类似于下图的错误
<img width="1034" alt="252149fe177f89950932385c57073cb158b87f97c9c90cfbf057fc8283e28910 0" src="https://user-images.githubusercontent.com/41655695/168088116-99a797de-ae0d-4395-82b9-0766b0700c4a.PNG">

**Comment by yanziwu621** [comment]
已解决

**Comment by yanziwu621** [comment]
已解决！

**Comment by xxx1996** [comment]
> 已解决！
方便讲一下怎么解决的这个问题么，我也遇到了这个问题

**Comment by phybrain** [comment]
> 已解决！

请问是什么问题，能说一下吗

**Comment by pogevip** [comment]
> > 用自己的数据训练，loss出现了nan,类似于下图的错误 <img alt="252149fe177f89950932385c57073cb158b87f97c9c90cfbf057fc8283e28910 0" width="1034" src="https://user-images.githubusercontent.com/41655695/168088116-99a797de-ae0d-4395-82b9-0766b0700c4a.PNG">
> 
> 求问最后是什么问题，我也遇到类似的问题

同样的问题，你有解决吗？

**Comment by shallowime** [comment]
> > > 用自己的数据训练，loss出现了nan,类似于下图的错误 <img alt="252149fe177f89950932385c57073cb158b87f97c9c90cfbf057fc8283e28910 0" width="1034" src="https://user-images.githubusercontent.com/41655695/168088116-99a797de-ae0d-4395-82b9-0766b0700c4a.PNG">
> > 
> > 
> > 求问最后是什么问题，我也遇到类似的问题
> 
> 同样的问题，你有解决吗？
见这个链接里面，有个兄弟写了篇踩坑帖，排一下那些坑，大概率可以解决
https://github.com/PaddlePaddle/PaddleOCR/issues/5393

**Comment by shallowime** [comment]
> > > 用自己的数据训练，loss出现了nan,类似于下图的错误 <img alt="252149fe177f89950932385c57073cb158b87f97c9c90cfbf057fc8283e28910 0" width="1034" src="https://user-images.githubusercontent.com/41655695/168088116-99a797de-ae0d-4395-82b9-0766b0700c4a.PNG">
> > 
> > 
> > 求问最后是什么问题，我也遇到类似的问题
> 
> 同样的问题，你有解决吗？

https://github.com/PaddlePaddle/PaddleOCR/issues/5393
见这个链接里面，有个兄弟写了篇踩坑帖，排一下那些坑，大概率可以解决
