### ISSUE TITLE
[BUG] LayoutXLM SER task image normalized twice !!!

### ISSUE THREAD

**Issue by taosean** [PaddlePaddle/PaddleOCR#6276]
- **系统环境/System Environment：**
OS: Ubuntu 18.04

- **版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：**
PaddleOCR:  [PaddleOCR dygraph branch](https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph)
PaddleNLP:  2.2.1
PaddlePaddle: paddlepaddle-gpu   2.2.2.post112

- **运行指令/Command Code：**
```
python tools/infer_vqa_token_ser.py \
    -c configs/vqa/ser/layoutxlm.yml  \
    -o Architecture.Backbone.checkpoints=pretrain/ser_LayoutXLM_xfun_zh/ \
    Global.infer_img=doc/vqa/input/zh_val_42.jpg
```

- **问题描述/Issue Description:**

In `infer_vqa_token_ser.py`,  transforms defined [here](https://github.com/PaddlePaddle/PaddleOCR/blob/a458c5a6ce3c28fdbff11fd901fa84591bb92f93/configs/vqa/ser/layoutxlm.yml#L94) are executed before the model inference. In the defined transforms, [NormalizeImage](https://github.com/PaddlePaddle/PaddleOCR/blob/a458c5a6ce3c28fdbff11fd901fa84591bb92f93/configs/vqa/ser/layoutxlm.yml#L109-L113) operation is used to do some image normalization operations for LayoutXLM model, e.g. subtract mean, divide std. However, I found the **same image normalization operation appears again**  in the process of [calculating image embedding](https://github.com/PaddlePaddle/PaddleNLP/blob/f56e4291a69da2d1e4e1d6c3ee8df274ddb5b03f/paddlenlp/transformers/layoutxlm/modeling.py#L725) for LayoutXLM.

LayoutXLM calls PaddleNLP and in PaddleNLP, [this line](https://github.com/PaddlePaddle/PaddleNLP/blob/f56e4291a69da2d1e4e1d6c3ee8df274ddb5b03f/paddlenlp/transformers/layoutxlm/visual_backbone.py#L787-L788) operates image normalization. The mean and std used here are read by function [read_config](https://github.com/PaddlePaddle/PaddleNLP/blob/f56e4291a69da2d1e4e1d6c3ee8df274ddb5b03f/paddlenlp/transformers/layoutxlm/visual_backbone.py#L30-L38), and the function read in a [config file](https://github.com/PaddlePaddle/PaddleNLP/blob/f56e4291a69da2d1e4e1d6c3ee8df274ddb5b03f/paddlenlp/transformers/layoutxlm/visual_backbone.yaml#L75-L82) to get mean and std. The mean and std defined in this config file is the same as defined in `configs/vqa/ser/layoutxlm.yml`. 

I debugged the whole process of SER task,and I can confirm it operates the image normalization twice!!!

Besides, I also debugged LayoutXLM from [this repo](https://github.com/microsoft/unilm/tree/master/layoutxlm) and compared the image normalization operation. [this repo](https://github.com/microsoft/unilm/tree/master/layoutxlm) only performs image normalization once!

Hope you guys can check it.

Thanks!

**Comment by taosean** [comment]
@WenmuZhou @Intsigstephon @andyjpaddle @sdcb 
Any comments on this bug? 
It seems to be an important one!

**Comment by andyjpaddle** [comment]
please update the latest code and try again
