### ISSUE TITLE
想做个证件识别，请问有什么思路？

### ISSUE THREAD

**Issue by kuhippo** [PaddlePaddle/PaddleOCR#628]
具体问题是：
1.识别的时候要不要预处理图片？像旋转图片，切割证件矩形，二值化什么的
2.怎么定位文字具体内容？

谢谢

**Comment by WIKI2020** [comment]
在外包个python接口，偷偷调用百度的证件识别API，搞掂！

**Comment by kuhippo** [comment]
> 在外包个python接口，偷偷调用百度的证件识别API，搞掂！

百度没有这个证件类型

**Comment by MissPenguin** [comment]
> 具体问题是：
> 1.识别的时候要不要预处理图片？像旋转图片，切割证件矩形，二值化什么的
> 2.怎么定位文字具体内容？
> 
> 谢谢

1. 如果图片质量还不错（主体清晰），可以不用太多预处理，直接进行整图的文本检测和识别，当然，这个还是看你想达到什么效果，根据实际需求和评估效果来调整策略
2. 是想得到每个文字的位置吗，可以参考这里讨论的方法 #589

**Comment by kuhippo** [comment]
> > 具体问题是：
> > 1.识别的时候要不要预处理图片？像旋转图片，切割证件矩形，二值化什么的
> > 2.怎么定位文字具体内容？
> > 谢谢
> 
> 1. 如果图片质量还不错（主体清晰），可以不用太多预处理，直接进行整图的文本检测和识别，当然，这个还是看你想达到什么效果，根据实际需求和评估效果来调整策略
> 2. 是想得到每个文字的位置吗，可以参考这里讨论的方法 #

谢谢回答
1.如果证件放在了有文字的地方拍然后识别效果就不是很好了，如果能裁剪到证件再识别会好点，请问有什么方法呀？
2.我想要证件指定的文字内容，像身份证一样要地址信息，怎么确定地址信息的位置，过滤没用的其他文字识别？

**Comment by MissPenguin** [comment]
> > > 具体问题是：
> > > 1.识别的时候要不要预处理图片？像旋转图片，切割证件矩形，二值化什么的
> > > 2.怎么定位文字具体内容？
> > > 谢谢
> > 
> > 
> > 
> > 1. 如果图片质量还不错（主体清晰），可以不用太多预处理，直接进行整图的文本检测和识别，当然，这个还是看你想达到什么效果，根据实际需求和评估效果来调整策略
> > 2. 是想得到每个文字的位置吗，可以参考这里讨论的方法 #
> 
> 谢谢回答
> 1.如果证件放在了有文字的地方拍然后识别效果就不是很好了，如果能裁剪到证件再识别会好点，请问有什么方法呀？
> 2.我想要证件指定的文字内容，像身份证一样要地址信息，怎么确定地址信息的位置，过滤没用的其他文字识别？

1. 想通过算法解决的话，可以训一个检测模型，如果方便交互的话，可以像支付宝之类的采集证件信息的时候给个框，提示用户把证件主体放到框内，这样对模型的挑战最小
2. 可以标注训练数据时只标注地址信息的部分，或者结合文本框的位置信息对识别结果用关键字过滤

**Comment by Biel-Hammer** [comment]
> 在外包个python接口，偷偷调用百度的证件识别API，搞掂！

要钱啊 又不是免费的
