### ISSUE TITLE
PaddleOCR目前的识别准确度有多高

### ISSUE THREAD

**Issue by yilvshifeng** [PaddlePaddle/PaddleOCR#6280]
请问Paddle目前的识别准确度是多少？有没有相关的性能介绍或者官方宣传介绍？

**Comment by tink2123** [comment]
V3的性能和准确率可以参考相关的技术报告:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/PP-OCRv3_introduction.md
V2版本的详细数据在arxiv文章中也有详细介绍：https://arxiv.org/abs/2109.03144
