### ISSUE TITLE
PaddleOCR2.4, 运行gen_label出错： list index out of range

### ISSUE THREAD

**Issue by Jaccica** [PaddlePaddle/PaddleOCR#6281]
将下载的icdar2015识别数据集标注转换为PPOCR label的格式，采用gen_label.py进行标注转换，出现错误：
(paddle) D:\code\paddle\PaddleOCR-release-2.4>python ppocr/utils/gen_label.py --mode="rec" --input_path="train_data/ic15_data/rec_gt_test.txt" --output_label="rec_
gt_label.txt"
Generate rec label
Traceback (most recent call last):
  File "ppocr/utils/gen_label.py", line 80, in <module>
    gen_rec_label(args.input_path, args.output_label)
  File "ppocr/utils/gen_label.py", line 24, in gen_rec_label
    img_path, label = tmp[0], tmp[1]
IndexError: list index out of range

- 系统环境/System Environment：**win10，Pycharm**
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：**PaddleOCR2.4**

**Comment by Sherlock-IT** [comment]
Did you manage to solve this issue? I have the same thing.
