### ISSUE TITLE
Cpp Infer 是否已经适配  PP-OCRv3 ？， 测试了下准确率比v2版本要差一些

### ISSUE THREAD

**Issue by liveever** [PaddlePaddle/PaddleOCR#6286]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 64
- 版本号/Version：Paddle：cpu_avx_mkl 2.3  ； PaddleOCR： 2.5
-  问题相关组件/Related components：cpp Infer 
Cpp Infer 是否已经适配  PP-OCRv3 ？， 测试了下准确率比v2版本要差一些

**Comment by andyjpaddle** [comment]
能否提供一下具体的测试数据和测试命令？

**Comment by kuaiyouxiaozi** [comment]
> 能否提供一下具体的测试数据和测试命令？
测试代码：使用cpp_infer/src/main.cpp
测试图片
![1](https://user-images.githubusercontent.com/24197834/168755621-a70d11b4-befa-4267-b5b5-4c509e46af34.png)
：
ppocrv2模型：*_server_v2.0_*

**Comment by andyjpaddle** [comment]
> 遇到同样得问题，准确率不如V2版本 测试代码：使用cpp_infer/src/main.cpp 测试图片 ![1](https://user-images.githubusercontent.com/24197834/168755621-a70d11b4-befa-4267-b5b5-4c509e46af34.png) ： ppocrv2模型：__server_v2.0__ ppocr2.5模型：_-OCRV3_

我这里用v3测试正常哈，测试结果如下：
<img width="801" alt="截屏2022-05-17 下午4 17 49" src="https://user-images.githubusercontent.com/87074272/168764414-6638a4d1-0764-47a6-8978-ec50942c7ba9.png">

测试指令：
`./build/ppocr --det_model_dir=../../inference/ch_PP-OCRv3_det_infer --rec_model_dir=../../inference/ch_PP-OCRv3_rec_infer --image_dir=../../test.png --use_angle_cls=false --det=true --rec=true --cls=false --rec_img_h=48`

注意：使用v3识别模型需要指定的识别的图片高度`--rec_img_h=48`，v2的无需指定。
参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/cpp_infer/readme_ch.md#23-%E8%BF%90%E8%A1%8Cdemo

**Comment by mazhen2009** [comment]
我们也遇到了这个问题，代码改了一行，就好很多，你可以试试。
`class CrnnResizeImg {
public:
  virtual void Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio,
                   bool use_tensorrt = false,
                   //const std::vector<int> &rec_image_shape = {3, 32, 320});   //v2
		const std::vector<int>& rec_image_shape = { 3, 48, 320 });  //v3

};
`

**Comment by andyjpaddle** [comment]
> 我们也遇到了这个问题，代码改了一行，就好很多，你可以试试。
> 
> ` class CrnnResizeImg { public: virtual void Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio, bool use_tensorrt = false, //const std::vector &rec_image_shape = {3, 32, 320}); //v2 const std::vector& rec_image_shape = { 3, 48, 320 }); //v3
> 
> }; `

v3的代码已经把高度设置成可配置了，`--rec_img_h=48 `, 更新一下代码看看，你这个好像还是旧代码

**Comment by ANDROIDTODO** [comment]
+1

**Comment by liveever** [comment]
![5](https://user-images.githubusercontent.com/284542/169636809-6a6079b0-5325-4edf-870f-ad207ecf20e7.jpg)

**Comment by liveever** [comment]
> ![5](https://user-images.githubusercontent.com/284542/169636809-6a6079b0-5325-4edf-870f-ad207ecf20e7.jpg)
这个v2比v3错字要少一些。

**Comment by mazhen2009** [comment]
> >
> > 这个v2比v3错字要少一些。
这是我用 v3 的结果，差不多。

SSss《前出师表》诸葛亮
臣亮言：先帝创业未半，而中道崩：今天下三分，益州疲蔽，此诚危急存亡之秋
也。然侍卫之臣，不解于内：忠志之士，忘身于外者：盖追先帝之殊遇，欲报之于陆下
也。诚宜开张圣听，以光先帝遗德，恢弘志士之气：不宜妄自菲薄，引喻失义，以塞忠谏
之路也。宫中府中，俱为一体：陟罚臧否，不宜异同：若有作奸犯科，及为忠善者，宜付
有司，论其刑赏，以昭陆下平明之治；不宜偏私，使内外异法也。侍中、侍郎郭攸之、费
依、董允等，此皆良实，志虑忠纯，是以先帝简拔以遗陆下：愚以为宫中之事，事无大
小，悉以咨之，然后施行，必得神补阙漏，有所广益。将军向宠，性行淑均，晓畅军事，
试用之于昔日，先帝称之日“能”，是以众议举宠为督：愚以为营中之事，事无大小，悉
以咨之，必能使行阵和穆，优劣得所也。亲贤臣，远小人，此先汉所以兴隆也；亲小人，
远贤臣，此后汉所以倾也。先帝在时，每与臣论此事，未尝不叹息痛恨于桓、灵也！侍
中、尚书、长史、参军，此悉贞亮死节之臣也，愿陆下亲之、信之，则汉室之隆，可计日
而待也。
臣本布衣，躬耕南阳，苟全性命于乱世，不求闻达于诸候。先帝不以臣卑郡，狠自枉
屈，三顾臣于草庐之中，谐臣以当世之事，由是感激，遂许先帝以驱驰。后值倾覆，受任
于败军之际，奉命于危难之间：尔来二十有一年。先帝知臣谨慎，故临崩寄臣以大事
也。受命以来，夙夜优虑，恐付托不效，以伤先帝之明：故五月渡泸，深入不毛。今南方
已定，甲兵已足，当奖帅三军，北定中原，庶竭驾钝，携除奸凶，兴复汉室，还于旧都：
此臣所以报先帝而忠陆下之职分也。至于期酌损益，进尽忠言，则攸之、依、允等之任
也。愿陆下托臣以讨贼兴复之效，不效则治臣之罪，以告先帝之灵；若无兴复之言，则责
之、依、允等之咎，以彰其慢。下亦宜自谋，以谐善道，察纳雅言，深追先帝遗
诏。臣不胜受恩感激！今当远离，临表递泣，不知所云。
