### ISSUE TITLE
Where is E-book: Dive Into OCR?

### ISSUE THREAD

**Issue by chuan298** [PaddlePaddle/PaddleOCR#6287]
First of all, Thanks for your repo. Where can I find E-book: Dive Into OCR?

**Comment by WenmuZhou** [comment]
you can joint we [wechat group](https://github.com/PaddlePaddle/PaddleOCR#community) to get the e book

**Comment by ciberola** [comment]
Hi, I would really like to improve my knowledge of PaddleOCR software, however I cannot find "E-book: Dive Into OCR" ebook, even after joining wechat group. I do not speak Chinese so I would appreciate if you could provide link to a book in English. Thanks in advance.

**Comment by nikaxx** [comment]
Hello, I am also very interesting in finding "Dive Into OCR" ebook in English. Please provide link

**Comment by mudrantar-rj** [comment]
+1 to the responses above.

**Comment by makarun** [comment]
same problem : (

**Comment by danghieuan** [comment]
> Hi everyone! I guess I found the book for y'all OCR enthusiats, it is in the form of notebooks (in both english and chinese) explaining some of the theory and practice of OCR (only architectures with an intermediate level of sophistication). https://github.com/IlyasMoutawwakil/Dive-into-OCR-By-Paddle

Thank you for the information, is it enough for the 12 chapters introduced?

**Comment by HanNayeoniee** [comment]
> > Hi everyone! I guess I found the book for y'all OCR enthusiats, it is in the form of notebooks (in both english and chinese) explaining some of the theory and practice of OCR (only architectures with an intermediate level of sophistication). https://github.com/IlyasMoutawwakil/Dive-into-OCR-By-Paddle
> 
> Thank you for the information, is it enough for the 12 chapters introduced?

@danghieuan 
Thanks for the jupyter notebook link! 
I can see only 6 folders in that github repository. What do you mean by **12 chatpers**?

**Comment by damvantai** [comment]
> First of all, Thanks for your repo. Where can I find E-book: Dive Into OCR?

https://paddleocr.bj.bcebos.com/ebook/Dive_into_OCR.pdf
