### ISSUE TITLE
检测模型预测尺寸[736, 1280]  是[宽，高] 还是 [高，宽]？？

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#6288]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
h,w
