### ISSUE TITLE
StyleText 效果极差，背景和文字无法区分。

### ISSUE THREAD

**Issue by liyandongpy** [PaddlePaddle/PaddleOCR#6289]
想用该模型生成一些训练文本识别的样本，但是效果极差。
![test1](https://user-images.githubusercontent.com/49861986/168420283-40d7af16-110a-4115-bc5f-22f28bff54f7.png)
<img width="72" alt="test2" src="https://user-images.githubusercontent.com/49861986/168420284-86e3f23a-4c64-4f08-9d66-d7a26e640378.png">

生成的效果如图：

![fake_bg](https://user-images.githubusercontent.com/49861986/168420321-bb98b96e-dfc7-4ce7-bab5-8b4573edb17f.jpg)

![fake_text](https://user-images.githubusercontent.com/49861986/168420329-74cfdb8b-4cb2-40ea-abd9-90fa40cab7fa.jpg)
![fake_fusion](https://user-images.githubusercontent.com/49861986/168420331-b37c43ec-ec07-49b2-8397-cd9c57088a34.jpg)

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
感谢反馈，StyleText我们在进一步优化当中了
