### ISSUE TITLE
十分钟完成 PP-OCRv3 识别全流程实战项目

### ISSUE THREAD

**Issue by huawenyu2020** [PaddlePaddle/PaddleOCR#6291]
1.1环境准备报错
正克隆到 'PaddleOCR'...
remote: Enumerating objects: 35573, done.
remote: Counting objects: 100% (243/243), done.
remote: Compressing objects: 100% (145/145), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
有时候能运行到1.2报错
No module named 'pypandoc'
大多数运行不到1.2
请问是什么原因？版本不匹配吗?谢谢

**Comment by Topdu** [comment]
试试直接在PaddleOCR github页面上下载zip文件，然后上传，或者用工作目录中的PaddleOCR-dygraph_5_5.zip文件，解压即是PaddleOCR的代码。

**Comment by huawenyu2020** [comment]
好的，我试一下，谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 中午12:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 十分钟完成 PP-OCRv3 识别全流程实战项目 (Issue #6291)





 
试试直接在PaddleOCR github页面上下载zip文件，然后上传，或者用工作目录中的PaddleOCR-dygraph_5_5.zip文件，解压即是PaddleOCR的代码。
