### ISSUE TITLE
The performance of released model is lower than expected

### ISSUE THREAD

**Issue by tengerye** [PaddlePaddle/PaddleOCR#6294]
Hi, the [performance](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/algorithm_overview_en.md) of released DB is much lower than reported in the original paper. The released model has P/R of 0.86/0.79 versus reported 0.88/0.83.

May I ask did you use SynthText to pre-train the model? If you did, may I ask where can I download the pre-trained model please?

**Comment by MissPenguin** [comment]
The performance reported in the original paper is based on a DB model with DCN module, which is not integrated in PaddleOCR. The DCN module can improve the recall and precision, while reducing prediction speed.

**Comment by tengerye** [comment]
@MissPenguin Thank you for your kind reply. 

May I ask did you use SynthText to pre-train the model? If you did, may I ask where can I download the pre-trained model please?

**Comment by MissPenguin** [comment]
> @MissPenguin Thank you for your kind reply.
> 
> May I ask did you use SynthText to pre-train the model? If you did, may I ask where can I download the pre-trained model please?

Yes, we firstly trained on SynthText. But the pre-trained model has been lost and cannot be found😂. Maybe you need to train it by yourself. It won't take too much time. Sorry for that...
