### ISSUE TITLE
ERROR: paddle_serving_client-0.8.3-cp37-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by Fyee** [PaddlePaddle/PaddleOCR#6296]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
Linux version 3.10.0-1160.25.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
pip3 install paddle_serving_client-0.8.3-cp37-none-any.whl
- 完整报错/Complete Error Message：
ERROR: paddle_serving_client-0.8.3-cp37-none-any.whl is not a supported wheel on this platform.

我按照这个[教程](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md#%E9%83%A8%E7%BD%B2)执行命令，执行到“安装client，用于向服务发送请求”这个步骤时报错了。运行环境也是按照这个[教程](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/environment.md)的1.3linux的方式去做的

**Comment by tingsi** [comment]
https://github.com/PaddlePaddle/Serving/issues/1741

我也碰到这个问题，在这儿解决了。
