### ISSUE TITLE
svtr算法有预训练模型吗

### ISSUE THREAD

**Issue by wuxiaolianggit** [PaddlePaddle/PaddleOCR#6298]
大佬，您好，svtr算法有预训练模型吗 @sdcb @ZeyuChen

**Comment by Topdu** [comment]
svtr论文中涉及的模型在[svtr简介](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/algorithm_rec_svtr.md) 中可以找到已经训练好的模型。

PP-OCRv3中涉及的svtr预训练模型未放出。

**Comment by wuxiaolianggit** [comment]
好的，多谢大佬回复啊 @Topdu
