### ISSUE TITLE
OSError: (External)  Cuda error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by phybrain** [PaddlePaddle/PaddleOCR#6299]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem：
OSError: (External)  Cuda error(700), an illegal memory access was encountered., 显存足够 但是报错

- 系统环境/System Environment：
  ubuntu,显卡2080ti,cuda10.2
- 版本号/Version：Paddle：2.0.0  PaddleOCR： 问题相关组件/Related components：tools/train, sdmgr
- 运行指令/Command Code：
python tools/train.py -c configs/kie/kie_unet_sdmgr.yml -o Global.save_model_dir=./output/kie/
- 完整报错/Complete Error Message：
```code
Traceback (most recent call last):
  File "tools/train.py", line 149, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 125, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/user/paddle/PaddleOCR/tools/program.py", line 270, in train
    stats = {k: v.numpy().mean() for k, v in loss.items()}
  File "/home/user/paddle/PaddleOCR/tools/program.py", line 270, in <dictcomp>
    stats = {k: v.numpy().mean() for k, v in loss.items()}
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:301)
```

**Comment by MissPenguin** [comment]
paddle安装是否正确，可以参考这个方式确认：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#old-version-anchor-8-%E4%B8%89%E3%80%81%E9%AA%8C%E8%AF%81%E5%AE%89%E8%A3%85

另外，训练别的任务也报这个错吗

**Comment by phybrain** [comment]
> paddle安装是否正确，可以参考这个方式确认：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#old-version-anchor-8-%E4%B8%89%E3%80%81%E9%AA%8C%E8%AF%81%E5%AE%89%E8%A3%85
> 
> 另外，训练别的任务也报这个错吗
sdmgr 计算loss时好像不能都是ignore类别标签，存在其他类别就不会报这个错

**Comment by MissPenguin** [comment]
全都是ignore就等于没框了所以会报错

**Comment by phybrain** [comment]
> 全都是ignore就等于没框了所以会报错

好的 谢谢

**Comment by Kevinlsy** [comment]
我也出现了此类问题，麻烦问下题主解决了吗？
