### ISSUE TITLE
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#63]

**Comment by LDOUBLEV** [comment]
麻烦提供下机器环境吧，GPU 型号，cudnn和cuda版本

**Comment by deep-practice** [comment]
GPU:2080ti
cuda:10.2
cudnn:7.6.5

**Comment by LDOUBLEV** [comment]
> GPU:2080ti
> cuda:10.2
> cudnn:7.6.5

收到，顺便问下你是用的我们提供的docker吧，使用的是cuda10的docker吗

**Comment by deep-practice** [comment]
没有使用docker,直接安装的paddlepaddle

**Comment by LDOUBLEV** [comment]
试一下重新安装paddle吧，
```
pip install paddlepaddle-gpu==1.7.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
你的是cuda10，需要post107版本的

**Comment by deep-practice** [comment]
![image](https://user-images.githubusercontent.com/54052915/82281542-2c0e5d00-99c4-11ea-8d26-084026ee654d.png)

**Comment by deep-practice** [comment]
之前安装的就是这个版本

**Comment by LDOUBLEV** [comment]
/etc/profile中加上libcudnn.so的路径，再 source /etc/profile
 参考issue https://github.com/PaddlePaddle/Paddle/issues/22996

**Comment by deep-practice** [comment]
Solved.Thx.

**Comment by JingRD** [comment]
> Solved.Thx.
你好请问你是怎么解决的呢

**Comment by coleone** [comment]
Same issue here, cannot fix based on the provides solution:

Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

added the following path into /etc/profile:
PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so:$PATH
PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7:$PATH
PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5:$PATH

GPU info:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.152.00   Driver Version: 418.152.00   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   34C    P8    N/A /  N/A |    513MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by SWHL** [comment]
#### 说明
上面的方案都不能解决-_-，实在找到是哪里的问题，特来请教一下遇到过的小伙伴们

#### 机器环境
- Centos 7
- **cuda**: 10.0.130
- **cudnn**: 7.6.3
- **paddlepaddle-gpu**: 1.7.2.post107/1.8.5.post107/2.0.0b0 都不行

#### 运行代码
```python
python paddleocr.py --image_dir ./doc/imgs/ --use_gpu True
```

#### 报错信息
```text
----------------------
Error Message Summary:
----------------------
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)
```

#### .bashrc内容
```shell
export PATH="/home/xxxx/anaconda3/bin:$PATH"
export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/xxxx/cuda/targets/ppc64le-linux/lib
```

**Comment by happy20200** [comment]
GPU:1080
cuda:10.2
cudnn:7.6.5

**Comment by chenkang404** [comment]
cuda:12.2,paddlepaddle-gpu=2.6.0,paddleocr=2.7.0.3
也报这样的错，应该是模块版本的问题，请问有什么安装建议吗

**Comment by chenkang404** [comment]
> cuda:12.2,paddlepaddle-gpu=2.6.0,paddleocr=2.7.0.3 也报这样的错，应该是模块版本的问题，请问有什么安装建议吗

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/38779739/f908db3c-d617-44e6-b7a5-ed52e420a6b1)
那就是说cuda=12的每法用了吗
