### ISSUE TITLE
蒸馏预训练模型的下载链接无效

### ISSUE THREAD

**Issue by ga546** [PaddlePaddle/PaddleOCR#6300]
PPOCRV3的蒸馏预训练模型无效。
https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv3_det_distill_train.tar

**Comment by Topdu** [comment]
该链接从哪里获得的呢？
以下链接可以正常访问：
https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_distill_train.tar

**Comment by ga546** [comment]
> 该链接从哪里获得的呢？ 以下链接可以正常访问： https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_distill_train.tar
> 
> 请保证代码最新，因为最近代码更新频繁解决了很多bug。

![image](https://user-images.githubusercontent.com/82253048/168574064-bacff0b9-d5b5-4f72-b751-98f54e5776f4.png)
在这里面找到的，应该是错误的。谢谢大佬
