### ISSUE TITLE
PPOCRLabel 标注问题

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/PaddleOCR#6301]
- 系统环境：macOS 12 intel x64 cpu
- PPOCRLabel版本:2.0.1
- 启动方式：PPOCRLabel --lang ch --kie True
问题详情：
通过自动标注获取到标注框后，存在某些标注框不准确的情况，删除然后重新绘制（采用快捷键q多点绘制的方式），反复几次大概率会出现程序崩溃的问题，报错为“找不到点”。
出错概率巨大，并且崩溃后，前面标注的几张（目测至少两张）图片标注信息会消失，建议：
1、找对应人员进行标注框删除，绘制，删除、矩形框标注、多点标注混合标注测试，大概率会出现崩溃
2、增加全局异常捕获，报错后应该显示弹窗自动撤回等机制，而不是直接崩溃
3、捕获异常后应该及时保存已经标注的数据，不然反复几次相当要命（本垃圾在使用过程中，崩溃就丢失至少两张图的标注信息，图片中内容较多，心态直接炸裂了）。

**Comment by Evezerest** [comment]
你好，请描述一下使用步骤以及报错详细信息。
你可以打开软件中 ’自动导出标记结果‘，避免标注结果丢失。

**Comment by ChaoII** [comment]
> 你好，请描述一下使用步骤以及报错详细信息。 你可以打开软件中 ’自动导出标记结果‘，避免标注结果丢失。

小哥能留下邮箱，发你操作的录制视频。因为就是常规操作，你说我操作步骤。就是删除某些框添加某些框，修改自动识别的数据。

**Comment by ChaoII** [comment]
https://user-images.githubusercontent.com/44053467/168982668-6e892be5-e18b-4e19-870e-b777c82ef0bb.MP4

**Comment by Evezerest** [comment]
可以发送到邮箱paddleocr@outlook.com

**Comment by Evezerest** [comment]
你好，我这边问题没有复现出来。看你的操作其实可以打开 `自动导出标记结果` 然后每次标记完一张图片后可以按快捷键ctrl+v确认本张图片的内容，不需要点击ctrl+s了
