### ISSUE TITLE
安卓项目 ocr demo 编译问题

### ISSUE THREAD

**Issue by norkmGitHub** [PaddlePaddle/PaddleOCR#6302]
### 拉下来的 android ocr demo 编译不通过

- 系统环境/System Environment： windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：  PaddleOCR-release-2.5
- 运行指令/Command Code： find_package(OpenCV REQUIRED)     (是运行到 CMakeLists.txt )  第18行的时候出现的

- 完整报错/Complete Error Message：

```
> Task :app:generateJsonModelDebug FAILED
D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Warning at D:/chromeDownload/PaddleOCR-release-2.5/deploy/android_demo/app/OpenCV/sdk/native/jni/OpenCVConfig.cmake:47 (message):
  Found OpenCV Android Pack but it has no binaries compatible with your ABI
  (can't find: /abi-x86)
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)

D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Warning at D:/chromeDownload/PaddleOCR-release-2.5/deploy/android_demo/app/OpenCV/sdk/native/jni/OpenCVConfig.cmake:47 (message):
  Found OpenCV Android Pack but it has no binaries compatible with your ABI
  (can't find: /abi-x86)
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)


Execution failed for task ':app:generateJsonModelDebug'.
> D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt:19 (find_package):
    Found package configuration file:



```

buildOutput 控制台输出：
```
D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at D:\chromeDownload\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt:19 (find_package):
  Found package configuration file:

    D:/chromeDownload/PaddleOCR-release-2.5/deploy/android_demo/app/src/main/cpp/../../../OpenCV/sdk/native/jni/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be

  NOT FOUND.
```

**Comment by zhang0225** [comment]
> 
请问您解决了吗，遇到了同样的问题

**Comment by norkmGitHub** [comment]
当时貌似是&nbsp; opencv 那个路径没有找到，然后单独下载 opencv sdk 解压后把&nbsp;#set(OpenCV_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../OpenCV/sdk/native/jni")
路径指向改成&nbsp;

set(OpenCV_DIR "D:/xl/opencv-4.5.4-android-sdk/OpenCV-android-sdk/sdk/native/jni")





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月31日(星期二) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 安卓项目 ocr demo 编译问题 (Issue #6302)





   
请问您解决了吗，遇到了同样的问题

**Comment by zhang0225** [comment]
> 
目前下载了Android sdk然后使用了绝对路径开始有别的错误了

**Comment by zhang0225** [comment]
> 当时貌似是&nbsp; opencv 那个路径没有找到，然后单独下载 opencv sdk 解压后把&nbsp;#set(OpenCV_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../OpenCV/sdk/native/jni") 路径指向改成&nbsp; set(OpenCV_DIR "D:/xl/opencv-4.5.4-android-sdk/OpenCV-android-sdk/sdk/native/jni")
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月31日(星期二) 中午11:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 安卓项目 ocr demo 编译问题 (Issue #6302) 请问您解决了吗，遇到了同样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;




找到问题了，感谢您的回复

**Comment by apsonLi** [comment]
@zhang0225 

> > 当时貌似是  opencv 那个路径没有找到，然后单独下载 opencv sdk 解压后把 #set(OpenCV_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../OpenCV/sdk/native/jni") 路径指向改成  set(OpenCV_DIR "D:/xl/opencv-4.5.4-android-sdk/OpenCV-android-sdk/sdk/native/jni")
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年5月31日(星期二) 中午11:47 收件人: _**@**_.**_>; 抄送: _**@**_._**>; "State _**@**_.**_>; 主题: Re: [PaddlePaddle/PaddleOCR] 安卓项目 ocr demo 编译问题 (Issue #6302) 请问您解决了吗，遇到了同样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 找到问题了，感谢您的回复

请问你是怎么解决的

**Comment by zhang0225** [comment]
@apsonLi 
正解，因为昨天发现下载paddlelite 2.10版本的库只有arm64-v7a的，所以可以像你这种指定只编译自己需要的库
如果arm64-v7a与arm64-v8a都想要的话可以使用paddlelite2.9.0的库，只需要删除原pallelite包，在build.gradle中将archives下的
paddlelite下载地址与版本修改为如下
        [
                'src' : 'https://paddleocr.bj.bcebos.com/dygraph_v2.0/lite/paddle_lite_libs_v2_9_0.tar.gz',
                'dest': 'PaddleLite'
        ],
重新编译就不会有错了。

**Comment by twinklelucas** [comment]
你们方法错了，不是绝对路径的问题，在app的build.gradle里面加上externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions -Wno-format"
                arguments '-DANDROID_PLATFORM=android-23', '-DANDROID_STL=c++_shared' ,"-DANDROID_ARM_NEON=TRUE"
                abiFilters "arm64-v8a"
            }
        }，就搞定了

**Comment by zybooo1** [comment]
app.gradle这样配置好像也可以，另外就是要把编译出的.so文件放到项目jniLib下     
   ndk {
            abiFilters 'arm64-v8a'
        }

**Comment by GUOhm230** [comment]
> * Message

请问大佬：用android_demo是可以进行安卓部署，放到某一个app上嘛？

**Comment by yeziyfx** [comment]
> 

大佬，你好，麻烦问下，你试了是可以是吗？我试了release打包的话，想要arm64-v7a与arm64-v8a都想要，2.9.0还是不行，还是这种错误。

**Comment by yeziyfx** [comment]
> @apsonLi 正解，因为昨天发现下载paddlelite 2.10版本的库只有arm64-v7a的，所以可以像你这种指定只编译自己需要的库 如果arm64-v7a与arm64-v8a都想要的话可以使用paddlelite2.9.0的库，只需要删除原pallelite包，在build.gradle中将archives下的 paddlelite下载地址与版本修改为如下 [ 'src' : 'https://paddleocr.bj.bcebos.com/dygraph_v2.0/lite/paddle_lite_libs_v2_9_0.tar.gz', 'dest': 'PaddleLite' ], 重新编译就不会有错了。

大佬，你好，麻烦问下，你试了是可以是吗？我试了release打包的话，想要arm64-v7a与arm64-v8a都想要，2.9.0还是不行，还是这种错误啊。

**Comment by yeziyfx** [comment]
> @apsonLi 正解，因为昨天发现下载paddlelite 2.10版本的库只有arm64-v7a的，所以可以像你这种指定只编译自己需要的库 如果arm64-v7a与arm64-v8a都想要的话可以使用paddlelite2.9.0的库，只需要删除原pallelite包，在build.gradle中将archives下的 paddlelite下载地址与版本修改为如下 [ 'src' : 'https://paddleocr.bj.bcebos.com/dygraph_v2.0/lite/paddle_lite_libs_v2_9_0.tar.gz', 'dest': 'PaddleLite' ], 重新编译就不会有错了。

大佬你好，你说的重新编译是release模式也不会出错了是吧？我试了，release模式下，都想要的话，得需要加上 abiFilters 'arm64-v8a', 'armeabi-v7a'，不然还是报错。我是打的release包，题主说的问题，我的是在release时出错，在as直接运行的话，不报错，能正常安装到手机。
