### ISSUE TITLE
版面分析模型

### ISSUE THREAD

**Issue by zgyl1988** [PaddlePaddle/PaddleOCR#6307]
我在做版面分析时，发现了英文的版面分析模型，请问有针对中文的训练好的版面分析模型没有？？还有怎么访问？怎么去看都有哪些训练好的模型？谢谢
![image](https://user-images.githubusercontent.com/32615528/168715734-669f8e96-b4e2-4d19-b6d8-e2568e4c5e8a.png)

**Comment by MissPenguin** [comment]
中文场景正在适配当中。可以在模型库中获取下载链接：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/models_list.md#1-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90%E6%A8%A1%E5%9E%8B
