### ISSUE TITLE
docker部署后，按照快速使用方法预测时，使用GPU会报错

### ISSUE THREAD

**Issue by Yhangzzz** [PaddlePaddle/PaddleOCR#631]
显卡：2060 8G
系统：ubuntu18.04
docker镜像：https://paddleocr.bj.bcebos.com/docker/docker_pdocr_cuda9.tar.gz
cudnn：7.6.5 （for cuda9.0）
paddle：paddlepaddle-gpu==1.7.2.post97

下载好源码后，按照步骤中的预测单张时，会报如下错误：
![image](https://user-images.githubusercontent.com/35824232/91531771-e86eac00-e93f-11ea-845a-38302ade804d.png)
![image](https://user-images.githubusercontent.com/35824232/91531793-f3294100-e93f-11ea-8c60-5d924451abcc.png)
，在后边加上--use_gpu=False  不使用GPU时则无错误。应该是环境的问题，可是才接触不知道怎么处理，有人遇到吗

**Comment by LDOUBLEV** [comment]
看上去像是cudnn的问题，你先换个docker吧，试试下面这个docker:  

hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev


sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash

**Comment by littleforce163** [comment]
docker 版本？
nvidia 驱动版本？
