### ISSUE TITLE
PPOCRLabel标注时候会自动闪退

### ISSUE THREAD

**Issue by applewings** [PaddlePaddle/PaddleOCR#6313]
- 系统环境/System Environment：mac os 11.0.1
- 版本号/Version：Paddle： 2.2.1
- PaddleOCR： 2.5
- 问题相关组件/Related components：PPOCRLabel
- 复现方式：

1.    标注完成一张图之后
2. ctrl+s 保存
3. check确认，并切换下一张图
4. 开启标注（按W/Q，或手动点击”矩形标注/多点标注“）
5. 鼠标在图片上开始标注，即刻闪退。

- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "/.../PaddleOCR/PPOCRLabel/libs/canvas.py", line 164, in mouseMoveEvent
    self.line.close()
  File "/.../PaddleOCR/PPOCRLabel/libs/shape.py", line 92, in close
    self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range
[1]    34083 abort      python ./PPOCRLabel.py --lang ch

```

同时还有另一个问题：
第2、3步，ctrl+s并不能真正的保存，Label.txt中可以看到，保存并未执行。需要按如下操作，才能完成保存操作：
1. ctrl+s执行保存（此时Label.txt没有该图标注信息，设该图为 A图）
2. 点击check确认，自动切换到下一张图
3. 鼠标在左侧列表，点选，切换回 A图
4. 再次按ctrl+s，此时，Label.txt才出现 A图 标注信息。

**Comment by Evezerest** [comment]
你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。
另外 4 5步骤没有复现，请再详细描述一下步骤。

**Comment by shallowime** [comment]
> 重新装下运行环境可以解决闪退问题

您好，我也遇到了同样的问题，请问是需要将整个paddle都重装吗

**Comment by shallowime** [comment]
> 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。

1. ctrl + U打开文件夹开始标注
2. 按W开始标注
3. 点击任意区域
4. 闪退报错

**Comment by Evezerest** [comment]
> > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> 
> 1. ctrl + U打开文件夹开始标注
> 2. 按W开始标注
> 3. 点击任意区域
> 4. 闪退报错

可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本

**Comment by shallowime** [comment]
> > > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> > 
> > 
> > 
> > 1. ctrl + U打开文件夹开始标注
> > 2. 按W开始标注
> > 3. 点击任意区域
> > 4. 闪退报错
> 
> 可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本

![image](https://user-images.githubusercontent.com/51881265/191402858-55987f25-b49e-4ca7-b733-d746fdae928a.png)

**Comment by shallowime** [comment]
> > > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> > 
> > 
> > 
> > 1. ctrl + U打开文件夹开始标注
> > 2. 按W开始标注
> > 3. 点击任意区域
> > 4. 闪退报错
> 
> 可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本

似乎跟保存功能有一定关系，打开平台后，先开启自动保存还可以标记几张，但是还是会崩溃。最严重的时候一张也标不了

**Comment by shallowime** [comment]
> > > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> > 
> > 
> > 
> > 1. ctrl + U打开文件夹开始标注
> > 2. 按W开始标注
> > 3. 点击任意区域
> > 4. 闪退报错
> 
> 可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本

该报错会有个前置问题：原本的自动识别出的框图无法正常调节大小，点会乱飘。具体表现为矩形标注的会变成正方形标注，四点标注的也会乱飘。如果某张图片触发了这个问题，那么下次按w或者q标注时必定触发报错。目前有个解决办法，就是每进来一张图片都先随便调一下自动识别的框图，如果不飘，这张图片就可以正常标注；如果乱飘，按一次CTRL+Z，即可解决乱飘问题，同时也不会再接着触发报错。目前若一张图片开始有乱飘情况，CTRL+Z后，这张图片不会再出现类似问题。

**Comment by Evezerest** [comment]
收到 我们查看一下

**Comment by Evezerest** [comment]
> > > > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> > > 
> > > 
> > > 
> > > 1. ctrl + U打开文件夹开始标注
> > > 2. 按W开始标注
> > > 3. 点击任意区域
> > > 4. 闪退报错
> > 
> > 
> > 可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本
> 
> 该报错会有个前置问题：原本的自动识别出的框图无法正常调节大小，点会乱飘。具体表现为矩形标注的会变成正方形标注，四点标注的也会乱飘。如果某张图片触发了这个问题，那么下次按w或者q标注时必定触发报错。目前有个解决办法，就是每进来一张图片都先随便调一下自动识别的框图，如果不飘，这张图片就可以正常标注；如果乱飘，按一次CTRL+Z，即可解决乱飘问题，同时也不会再接着触发报错。目前若一张图片开始有乱飘情况，CTRL+Z后，这张图片不会再出现类似问题。

你好，方便的话可以加一下微信群，然后a群主，我们单独拉一个群对接。目前我们这边复现出该问题

**Comment by shallowime** [comment]
> 

行，加我微信联系，w524689593

**Comment by shallowime** [comment]
> > > > > 你好，导出label只会对当前状态为✅的图片进行。先导出，再确认，自然只会出现上一张图片的结果。 另外 4 5步骤没有复现，请再详细描述一下步骤。
> > > > 
> > > > 
> > > > 
> > > > 1. ctrl + U打开文件夹开始标注
> > > > 2. 按W开始标注
> > > > 3. 点击任意区域
> > > > 4. 闪退报错
> > > 
> > > 
> > > 可以提供一下报错信息，平台、以及paddle paddleocr ppocrlabel的版本
> > 
> > 
> > 该报错会有个前置问题：原本的自动识别出的框图无法正常调节大小，点会乱飘。具体表现为矩形标注的会变成正方形标注，四点标注的也会乱飘。如果某张图片触发了这个问题，那么下次按w或者q标注时必定触发报错。目前有个解决办法，就是每进来一张图片都先随便调一下自动识别的框图，如果不飘，这张图片就可以正常标注；如果乱飘，按一次CTRL+Z，即可解决乱飘问题，同时也不会再接着触发报错。目前若一张图片开始有乱飘情况，CTRL+Z后，这张图片不会再出现类似问题。
> 
> 你好，方便的话可以加一下微信群，然后a群主，我们单独拉一个群对接。目前我们这边复现出该问题

好的，加我微信联系即可，w524689593

**Comment by HuizhiXu** [comment]
遇到了同样的问题

**Comment by headdder** [comment]
同样的问题，macos

**Comment by Evezerest** [comment]
@headdder 加一下微信群a群主吧

**Comment by Carolyn0822** [comment]
相同的问题，  self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range 闪退
windows 10

**Comment by weirman** [comment]
相同的问题， self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range 闪退
windows 10

**Comment by weirman** [comment]
@Evezerest 点击，“文件” —> “重置界面与保存地址”后，会出现以下提示"Remove setting pkl file $C:\Users\username\.autoOCRSettings.pkl"，之后就可以正常标注了，看样子是缓存配置文件的锅，可以排查下看。

![image](https://user-images.githubusercontent.com/13463086/223896924-62fab14a-f6f1-4f43-a2d6-1cad6aba928b.png)

**Comment by HS-Mike** [comment]
可以把报错那行的IndexError except掉，拉框出问题的时候长方形的框会变成正方形的框，删掉重拉就ok了，暂时这么改还没遇到其他问题
