### ISSUE TITLE
识别图片时会对图片的大小尺寸有要求吗

### ISSUE THREAD

**Issue by Altman7** [PaddlePaddle/PaddleOCR#6315]
遇到了一个很奇葩的问题
一个图片在裁剪前后识别出来的结果有些许差异，大的图片识别的结果是不准确的，小图片能正确识别出

**Comment by Altman7** [comment]
> 裁剪前后文字区域的占比也会变化，会影响检测识别效果
在识别之前需要预先调整图片尺寸大小么 多大是合适的

**Comment by yangy996** [comment]
小图可以使用这种方式优化小图文本检测
https://blog.csdn.net/YY007H/article/details/124973777

**Comment by zhanghuid** [comment]
> 小图可以使用这种方式优化小图文本检测 https://blog.csdn.net/YY007H/article/details/124973777

这个是什么实现原理呢？

**Comment by yangy996** [comment]
> > 小图可以使用这种方式优化小图文本检测 https://blog.csdn.net/YY007H/article/details/124973777
> 
> 请问：这个是什么实现原理呢？

小图的训练集好，这样处理小图可以变成大图，增加检测率
