### ISSUE TITLE
paddleocr2.5版本缺少对旧版本模型的使用说明

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleOCR#6316]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.3  PaddleOCR：2.5  问题相关组件/Related components：paddleocr
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

paddleocr.py文件415-418行
```python
        if params.ocr_version == 'PP-OCRv3':
            params.rec_image_shape = "3, 48, 320"
        else:
            params.rec_image_shape = "3, 32, 320"
```
对params.ocr_version进行了判断, 会强制覆盖用户的rec_image_shape, 提供的 中英文通用PP-OCR server模型（143.4M）仍然使用的是"3, 32, 320",必须强制使用params.ocr_version == 'PP-OCRv2"才能正常使用,但是文档中并没有说明默认模型已经被修改,请在文档处给出提示

**Comment by andyjpaddle** [comment]
whl包默认使用的是`PP-OCRv3`的模型，而`PP-OCRv3`的识别模型使用的`rec_image_shape`为"3, 48, 320"，因此这个地方做了判断，其他版本的`rec_image_shape`为"3, 32, 320"，如果要使用`PP-OCRv2`或者`PP-OCR`系列模型，可以通过指定版本`ocr_version`。
感谢反馈，文档我们后续会给出明确提示

**Comment by VieteChen** [comment]
> whl包默认使用的是`PP-OCRv3`的模型，而`PP-OCRv3`的识别模型使用的`rec_image_shape`为"3, 48, 320"，因此这个地方做了判断，其他版本的`rec_image_shape`为"3, 32, 320"，如果要使用`PP-OCRv2`或者`PP-OCR`系列模型，可以通过指定版本`ocr_version`。 感谢反馈，文档我们后续会给出明确提示

你好，请问后面有可能开放自定义这个参数吗？试改了一下"3, 48, 48"推理速度最高差了20倍。

**Comment by andyjpaddle** [comment]
因为whl适配的模型是PP系列模型，目前只适配3, 48, 320或3, 32, 320，如果需要自定义shape，可以修改源码
关于速度可以详细看下检测和识别对应耗时情况

**Comment by VieteChen** [comment]
> 因为whl适配的模型是PP系列模型，目前只适配3, 48, 320或3, 32, 320，如果需要自定义shape，可以修改源码 关于速度可以详细看下检测和识别对应耗时情况

如果在不允许修改源码的情况下，改对象的属性是否可行，或者是否有直接使用TextRecognizer类的例子
ocr.text_recognizer.rec_image_shape = [3, 48, 48]

**Comment by andyjpaddle** [comment]
目前不支持，只能修改源码，如果需要自定义，可以自己改源码，将这几行注释掉就行，然后会通过传入的shape参数自动更新，之后编译安装即可
