### ISSUE TITLE
not found any img file in ./doc/imgs/30.jpg

### ISSUE THREAD

**Issue by QQ1696311291** [PaddlePaddle/PaddleOCR#632]
可以查看到这张图片，但是测试时报错：Exception: not found any img file in ./doc/imgs/30.jpg，所有配置均按照官方执行，图片就在doc/imgs/目录下，但是换张图片就可是测试，不知道问题出在哪，？求指教，测试的命令是：!python3 tools/infer/predict_system.py --image_dir="./doc/imgs/30.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"

**Comment by LDOUBLEV** [comment]
问题应该就是测试图像路径不对，你打开终端，进入到./doc/imgs/ 下，ls 看下是不是有30.jpg

**Comment by QQ1696311291** [comment]
我确定./doc/imgs/有30.jpg这张图片，而且批量测试时，.。/doc/imgs/下有部分图片可以读取，但是部分图片不能读取，我检查过路径，没有问题，确实找到问题在哪里，

**Comment by QQ1696311291** [comment]
确实找不到问题在哪，请问问题还可能出现在哪里呢?

**Comment by LDOUBLEV** [comment]
在imgs路径下，ls，截个图发出来看下吧，我测试了repo中doc/imgs下的图都可以预测，你可以查一下是不是图像损坏了

**Comment by QQ1696311291** [comment]
第一张图显示这张图片可以正确读取
![image](https://user-images.githubusercontent.com/49194956/91566410-37373880-e976-11ea-9b3f-859c79dcd6e3.png)

> 第二张测试这张图片的时候就显示找不到这张图片了
![image](https://user-images.githubusercontent.com/49194956/91566478-559d3400-e976-11ea-8613-678e20924d73.png)

> 第三张是我的图片路径，这个路径下确实有这张图
![image](https://user-images.githubusercontent.com/49194956/91566512-6483e680-e976-11ea-8946-e87db3b15e99.png)

**Comment by LDOUBLEV** [comment]
试试绝对路径

**Comment by QQ1696311291** [comment]
应该是这张图片的问题，这代码没问题，谢谢。
