### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by plmmyyds** [PaddlePaddle/PaddleOCR#6320]
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1652831817 (unix time) try "date -d @1652831817" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 38900 (TID 0x7f367f97d3c0) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by GDongLin** [comment]
我碰到这个问题，使用cpu正常计算，使用gpu报错，paddle可以正常在gpu使用。

环境：
paddlepaddle-gpu 2.3.0
paddle_serving_server_gpu-0.8.3
—————————————————
cuda 11.2 + cudnn 8.1.1
ubuntu 20.04 
GeForce 3080Ti

**Comment by plmmyyds** [comment]
> 

解决了，但我也不知道怎么解决的，一顿乱操作，就没报错了，哈哈

**Comment by GDongLin** [comment]
大概指个方向？我也去尝试一下，这个错误有点迷

**Comment by plmmyyds** [comment]
大概率是paddlepaddle-gpu 版本问题

发自我的iPad

在 2022年5月19日，17:12，GDongLin ***@***.***> 写道：

﻿

大概指个方向？我也去尝试一下，这个错误有点迷
