### ISSUE TITLE
由于找不到paddle2onnx.dll，无法继续执行代码。重新安装程序可能会解决此问题 

### ISSUE THREAD

**Issue by Iron-iii** [PaddlePaddle/PaddleOCR#6324]
我按照windows系统CPU部署的方法进行部署，生成了ppocr.exe文件，但是运行的时候提示：“由于找不到paddle2onnx.dll，无法继续执行代码。重新安装程序可能会解决此问题 ”

**Comment by andyjpaddle** [comment]
可以参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy  使用

**Comment by ShaneHX** [comment]
照着文档编译的，文档并没有说打开exe的时候会出现找不到paddle2onnx.dll。而且 推理阶段为什么会调用到paddle2onnx.dll这个dll呢

**Comment by andyjpaddle** [comment]
你用的是哪个部署方式？运行命令是啥？

**Comment by ShaneHX** [comment]
windows下C++部署的，运行命令是`.\ppocr.exe --rec_model_dir=D:\\WorkSpace\\PaddleOCR\\output\\ch_PP-OCRv3_rec_slim_infer --image_dir=D:\\WorkSpace\\PaddleOCR\\output\\test\\1.png --use_angle_cls=false --det=false --rec=true --cls=false --rec_img_h=48`

**Comment by andyjpaddle** [comment]
ppocr编译正确吗

**Comment by andyjpaddle** [comment]
可以试一下非量化的模型 https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar

**Comment by ShaneHX** [comment]
ppocr编译是正确的，有一些无关紧要的warning。好像不是模型的问题，我在paddle inference 里面找到了这个缺少的dll，但是我拷贝到ppocr.exe目录下，还是运行不了，直接0xc000007b的程序错误
![微信截图_20220519152959](https://user-images.githubusercontent.com/20931010/169241673-904187fc-9069-4664-a797-e84cfd112e91.png)

**Comment by andyjpaddle** [comment]
更新一下最新的代码，另外paddle inference版本要和自己的系统环境一致哈，选择Windows版本的适合自己CUDA版本的

**Comment by andyjpaddle** [comment]
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#id2  下载适合自己的环境的版本

**Comment by Iron-iii** [comment]
用的Windows系统cpu，C++部署，试了好几个版本的paddleOCR，Visual Studio 2019，2022都试过了，还是有这个问题-_-!!!

**Comment by Iron-iii** [comment]
> ppocr编译是正确的，有一些无关紧要的warning。好像不是模型的问题，我在paddle inference 里面找到了这个缺少的dll，但是我拷贝到ppocr.exe目录下，还是运行不了，直接0xc000007b的程序错误 ![微信截图_20220519152959](https://user-images.githubusercontent.com/20931010/169241673-904187fc-9069-4664-a797-e84cfd112e91.png)

我也是这个问题

**Comment by Eling486** [comment]
确实文档没说全，应该是就差这个两个dll：
paddle2onnx.dll和onnxruntime.dll

**Comment by Kaze816** [comment]
使用paddle_inference 2.02版本的cpu版本，就没这么多的事， 五六个dll就能跑起来，并不需要paddle2onnx.dll。 
我现在尝试使用2.4.1，一堆的问题，现在加上paddle2onnx.dll，也还跑不起来。
