### ISSUE TITLE
文本检测模型对倾斜文字检测效果不好

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6325]
请问文本检测模型对倾斜字体一般检测不到，应该怎么调整呢

**Comment by Gmgge** [comment]
可以贴一个示例嘛？

**Comment by LDOUBLEV** [comment]
可以发一下badcase看下，或者参考这里的FAQ看是否能解决https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/FAQ.md#qpp-ocr%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E5%87%BA%E7%8E%B0%E6%98%8E%E6%98%BE%E6%BC%8F%E6%A3%80%E8%AF%A5%E5%A6%82%E4%BD%95%E8%B0%83%E6%95%B4%E5%8F%82%E6%95%B0%E6%88%96%E8%80%85%E8%AE%AD%E7%BB%83
