### ISSUE TITLE
The result from the custom model is empty

### ISSUE THREAD

**Issue by Afrah-M** [PaddlePaddle/PaddleOCR#6326]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：custom model
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
i was working on my own model so i used the custom model steps to create my model, but the result from it is empty, when i try to do 
for line in result:
      print (line)
the output is nothing

so what do you think the problem is?

**Comment by andyjpaddle** [comment]
ensure you model params is matched with your model_config
