### ISSUE TITLE
Paddle ocr model Memory occupied during execution

### ISSUE THREAD

**Issue by benugopal** [PaddlePaddle/PaddleOCR#6333]
I have loaded both recognition and detection from paddle ocr, and it occupied around 456 mb.
![image](https://user-images.githubusercontent.com/75051220/169062478-e0adb8fb-c04f-4692-b2fc-71a540c286a8.png)

Later i tried passing multiple documents in 2 phases
phase 1= where i passed 100 pages and it took around 1962 MB of the GPU memory
Phase 2 = where i added more 100 images and the total count is 206 and it occupied around 2602 MB of GPU memory.
![image](https://user-images.githubusercontent.com/75051220/169063155-20cb1a12-b80e-4f31-bcbf-da0904b2bb7e.png)
![image](https://user-images.githubusercontent.com/75051220/169063276-04a2de35-9d11-4478-8e7c-da58c0254693.png).

Is there any way to restrict this memory occupancy in GPU since i need to perform other operations of 1000's of documents for every day continuously.

Also, why the memory is assigned every time i pass a new image to it?

Wanted to if memory is related to the accuracy of the text extraction?

Thank you.

**Comment by benugopal** [comment]
我已将多线程节点更改为 1，并将 gpu 消耗更改为静态 1023，但处理后内存尚未释放。请建议在代码中的何处进行更改以在处理后释放内存。

**Comment by benugopal** [comment]
Any Update on this issue as to restrict the multi threading to one thread ?

**Comment by andyjpaddle** [comment]
you can try run your code in terminator by using .py file not in jupyter notebook
