### ISSUE TITLE
pip3 install lanms-nova安装lanms-nova报错

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#6336]
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lanms-nova

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Lanme** [comment]
这怎么解决的呢？

**Comment by ainndejj11** [comment]
ubuntu16.04默认gcc版本是5.4.0，升级gcc和gcc到6.的版本，然后就能安装了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 下午2:00
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] pip3 install lanms-nova安装lanms-nova报错 (Issue #6336)





 
这怎么解决的呢？

**Comment by gg22mm** [comment]
引入这么垃圾的包进来干啥？  lanms-neo  安装都是个问题
