### ISSUE TITLE
关于使用PPOCRLabel进行数据标注，有两个文字想请教大家

### ISSUE THREAD

**Issue by 123xian123** [PaddlePaddle/PaddleOCR#6337]
1、在使用PPOCRLabel进行图像标注的时候，图像上有很多文字有识别的需求，但有些位置的文字没有识别的需求，那么在进行标注的时候是否还需要对没有识别需求位置的文字进行标注呢？
2、在使用PPOCRLabel进行自动标注后，有些位置的文字被标注上了，但是还额外框住了其他不是文字的图案（软件的文字识别能够识别到正确的文字，但是这种情况出现的次数很多），还是否需要对标注框进行调整，来去除掉非文字的图案？不去除的话是否对最终文字识别网络模型造成影响呢？

**Comment by Evezerest** [comment]
1. 不需要标注
2. 非文字内容不需要标注，可以删除。不去除会影响最终效果
