### ISSUE TITLE
C++ infer gpu编译问题

### ISSUE THREAD

**Issue by xuhui1994** [PaddlePaddle/PaddleOCR#6341]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centsos7
- 版本号/Version：Paddle：paddle-develop  PaddleOCR：V2.5 
- gcc版本 5.4
- cuda版本 10.2
- cunn版本 8.05
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- make[2]:-*** [third_party/gflags/src/extern_gflags-stamp/extern_gflags-download] 错误 1
   make[1]: *** [CMakeFiles/extern_gflags.dir/all] 错误 2

在使用cpp_infer中，使用cpu版本是可以的，但是gpu版本不行，使用自带的paddle预测库在tools/bulld.sh编译会报错，使用源码编译就会显示如下错误，请可以将gpu版本的教程写的仔细一点吗？
![image](https://user-images.githubusercontent.com/35833743/169232799-701ae0a9-398e-4205-bb39-c19f6f91f98d.png)

**Comment by liveever** [comment]
看日志 应该是网络问题 ， 可以挂个代理试试看， 不行的话 就先搬运到gitee， 然后配置到gitee， 再便宜。
