### ISSUE TITLE
调用训练后的识别模型结果无法进行检测

### ISSUE THREAD

**Issue by ruibeite** [PaddlePaddle/PaddleOCR#6342]
我进行了检测和识别的训练并且导出得到了预测模型。但是当我进行应用的时候，如果我仅仅调用检测模型（识别模型使用默认的）是可以正常监测识别的，但是如果我检测和识别都调用了却无法进行正常的检测，或者说检测不出内容。请这是什么原因？

**Comment by tink2123** [comment]
麻烦贴一下您使用的预测命令
