### ISSUE TITLE
pip install paddleocr安装出错

### ISSUE THREAD

**Issue by johnnywongxy** [PaddlePaddle/PaddleOCR#6345]
系统windows11
python3.10.4
cuda11.2+cudnn8.2.1
GPU 3060TI
问题
用pip install paddleocr出错如下
C:\Users\johnn>pip install paddleocr
Collecting paddleocr
  Using cached paddleocr-2.5.0.3-py3-none-any.whl (334 kB)
Collecting pyclipper
  Using cached pyclipper-1.3.0.post2-cp310-cp310-win_amd64.whl (105 kB)
Collecting cython
  Using cached Cython-0.29.30-py2.py3-none-any.whl (985 kB)
Collecting lmdb
  Using cached lmdb-1.3.0-cp310-cp310-win_amd64.whl (106 kB)
Collecting scikit-image
  Using cached scikit_image-0.19.2-cp310-cp310-win_amd64.whl (12.6 MB)
Requirement already satisfied: numpy in c:\users\johnn\appdata\local\programs\python\python310\lib\site-packages (from paddleocr) (1.22.3)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
  Preparing metadata (setup.py) ... done
Collecting opencv-contrib-python==4.4.0.46
  Using cached opencv-contrib-python-4.4.0.46.tar.gz (148.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
      Collecting setuptools
        Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build
        Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
      Collecting cmake
        Using cached cmake-3.22.4-py2.py3-none-win_amd64.whl (38.1 MB)
      Collecting pip
        Using cached pip-22.1-py3-none-any.whl (2.1 MB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      ERROR: To modify pip, please run the following command:
      C:\Users\johnn\AppData\Local\Programs\Python\Python310\python.exe -m pip install --ignore-installed --no-user --prefix C:\Users\johnn\AppData\Local\Temp\pip-build-env-cncqfo1l\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip numpy==1.13.3; python_version=='3.6' numpy==1.14.5; python_version=='3.7' numpy==1.17.3; python_version=='3.8' numpy==1.19.3; python_version>='3.9'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by wangjunjx8868** [comment]
我也遇到这个问题了，你的解决了吗

**Comment by johnnywongxy** [comment]
python换成3.9就行了
