### ISSUE TITLE
示例中的便捷使用paddleocr命令行指的是什么？

### ISSUE THREAD

**Issue by Desperado-zjc** [PaddlePaddle/PaddleOCR#6349]

**Comment by Desperado-zjc** [comment]
我是从这边直接开始的https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/docs/quickstart.md，
没有安装paddlepaddle，参考https://www.paddlepaddle.org.cn/官网安装了python -m pip install paddlepaddle==2.3.0 -i https://mirror.baidu.com/pypi/simple就可以

**Comment by tink2123** [comment]
可以参考这篇，先使用whl包快速体验：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/whl.md
