### ISSUE TITLE
加群的二维码被举报了，麻烦修复一下

### ISSUE THREAD

**Issue by Arctanxy** [PaddlePaddle/PaddleOCR#635]
在扫二维码加群的时候，填完问卷就出来无法访问页面：

![image](https://user-images.githubusercontent.com/19771342/91673606-7d9fb980-eb67-11ea-8538-548860245cd4.png)

**Comment by quietsmile** [comment]
嗯，回答了问卷，但是加不了群

**Comment by wsibo** [comment]
是的，我这边显示活动已结束

**Comment by grasswolfs** [comment]
> 嗯，回答了问卷，但是加不了群

二维码已更新，但是非常抱歉，可能还需要填一下问卷
