### ISSUE TITLE
Batch Inference with det = True

### ISSUE THREAD

**Issue by alawliat** [PaddlePaddle/PaddleOCR#6353]
- System Environment：Windows
- 版本号/Version：Paddle：2.2  PaddleOCR：2.4  

Hi,

I was trying to batch inference on a set of images and it does not work unless det = False. Is there anyway around this? I have 95%+ accuracy when I use the text detection model, and close to 0% when I don't.

**Comment by WenmuZhou** [comment]
det model not support batch inference
