### ISSUE TITLE
编译Centos 7  PaddleOCR C++预测demo失败

### ISSUE THREAD

**Issue by hnyztang** [PaddlePaddle/PaddleOCR#6357]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 7
- 版本号/Version： gcc 5.4   opencv 3.4.7
- Paddle：  预测库为 https://paddle-inference-lib.bj.bcebos.com/2.3.0/cxx_c/Linux/CPU/gcc5.4_avx_mkl/paddle_inference.tgz
- PaddleOCR：release/2.3
-  问题相关组件/Related components：
- ../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `OrtGetApiBase@VERS_1.10.0'
../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::Export(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, int, bool, bool, bool, bool, bool)'
../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::IsExportable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool, bool, bool, bool, bool)'

- 运行指令/Command Code：
- ./tool/build.sh
- 完整报错/Complete Error Message：
- [root@2f0165a4e988 cpp_infer]# sh ./tools/build.sh
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /root/PaddleOCR/deploy/cpp_infer/opencv-3.4.7/opencv3 (found version "3.4.7") 
cmake cxx flags -g -O3 -fopenmp -std=c++11
-- Found Git: /usr/local/git/bin/git (found version "2.7.3") 
default cmake for auto_log, no need to compile
-- Configuring done
-- Generating done
- -- Build files have been written to: /root/PaddleOCR/deploy/cpp_infer/build
[ 12%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 37%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
[ 37%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
[ 62%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
[ 75%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 87%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
[100%] Linking CXX executable ppocr
/usr/bin/ld: warning: libonnxruntime.so.1.10.0, needed by ../paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpaddle2onnx.so, needed by ../paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `OrtGetApiBase@VERS_1.10.0'
../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::Export(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, int, bool, bool, bool, bool, bool)'
../paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::IsExportable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool, bool, bool, bool, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [ppocr] Error 1
make[1]: *** [CMakeFiles/ppocr.dir/all] Error 2
make: *** [all] Error 2

**Comment by hnyztang** [comment]
安装官方文档编译，链接预测库so的时候报错了，是我so版本版本不对?

**Comment by TongTianUM** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/cpp_infer/readme.md#22-compile-paddleocr-c-inference-demo
在2.2运行make -j这一步的时候报了相同的错误

**Comment by WenmuZhou** [comment]
使用gcc8.2看看呢

**Comment by WenmuZhou** [comment]
是不是没装onnxruntime

**Comment by heliqi** [comment]
https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/d6c1aac35fa8a02271c9433b0565ff0054a5a82b/c%2B%2B/lib/CMakeLists.txt#L43

**Comment by TongTianUM** [comment]
> 

好的我试一下！
因为缺失的so在paddle_inference目录中都有，我自己尝试手动修改LD_LIBRARY_PATH指向，或者手动拷贝所需so文件到/usr/lib/x86_64-linux-gnu等对象库中也可修复

**Comment by suny1123** [comment]
@hnyztang 请问您解决这个问题了吗？我也遇到了相同的问题

**Comment by wfm777** [comment]
这个问题怎么解决了最后

**Comment by linkewei0580** [comment]
> onnx



> 这个问题怎么解决了最后
楼上已经给出解决方案了。
