### ISSUE TITLE
带TPS模块的识别模型转ONNX报错

### ISSUE THREAD

**Issue by wxiaoli** [PaddlePaddle/PaddleOCR#6359]
![image](https://user-images.githubusercontent.com/16215986/169483949-d92d91aa-708b-4c4d-826e-2b459ba9df5e.png)
你好，我参考https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/deploy/paddle2onnx/readme.md
把导出的识别模型转onnx时报如上错误，但是去掉TPS模块后导出的模型可以正常转。请问，这是目前还不支持还是我的配置问题？

**Comment by tink2123** [comment]
带TPS的模型不能支持动态shape，实际推理时无法支持变长文本，不建议使用哈。

**Comment by wxiaoli** [comment]
> 



> 带TPS的模型不能支持动态shape，实际推理时无法支持变长文本，不建议使用哈。

好的，谢谢
