### ISSUE TITLE
训练DB时通过修改配置文件中的base_lr修改学习率无效。

### ISSUE THREAD

**Issue by lovelynight** [PaddlePaddle/PaddleOCR#636]
如题，修改配置文件中的base_lr 并不能修改学习率，训练时返回的学习率始终是0.001，，在源码中找到了
    optimizer = fluid.optimizer.Adam(
        learning_rate=base_lr,
        beta1=beta1,
        beta2=beta2,
        regularization=L2Decay(regularization_coeff=l2_decay),
        parameter_list=parameter_list)
确实设置了学习率，为什么修改后无效呢？

**Comment by littletomatodonkey** [comment]
你是加载checkpoints了吗？加载checkpoints的话，设置的学习率会无效，可以使用加载pretrain的方式加载预训练模型

**Comment by lovelynight** [comment]
> 你是加载checkpoints了吗？加载checkpoints的话，设置的学习率会无效，可以使用加载pretrain的方式加载预训练模型

加载了，我对paddle不太熟悉，有办法通过修改代码使加载了checkpoints的情况下也可以修改学习率吗？pretrain的格式和checkpoints的不太一样，或者有转换一下的方法吗？

**Comment by littletomatodonkey** [comment]
以这个配置文件为例，你设置这个`pretrain_weights `参数就行
https://github.com/PaddlePaddle/PaddleOCR/blob/31e62cb8babe8ce28a9b3eb7e2d5129e21adf6b1/configs/rec/rec_chinese_lite_train.yml#L20

不要设置下面的`checkpoints `

**Comment by lovelynight** [comment]
> 以这个配置文件为例，你设置这个`pretrain_weights `参数就行
> https://github.com/PaddlePaddle/PaddleOCR/blob/31e62cb8babe8ce28a9b3eb7e2d5129e21adf6b1/configs/rec/rec_chinese_lite_train.yml#L20
> 
> 不要设置下面的`checkpoints `

这个我知道，但是pretrain的加载方式，不能加载checkpoints保存下来的文件，格式不同。
pretrain的格式为persistable模型，是零散的各个层的权重文件，而checkpoints里是三个文件，分别是pdmodel,pdopt,pdparams后缀，直接修改地址会提示加载失败。
我可以修改代码，但是我没有找到加载模型的位置，如果可以，希望可以告诉我一下在哪里，我尝试修改。

**Comment by littletomatodonkey** [comment]
我这边可以加载，你把你修改的方式说一下吧，应该是没写对

**Comment by lovelynight** [comment]
> 我这边可以加载，你把你修改的方式说一下吧，应该是没写对

是我这边没写对，我原来写的是./checkpoints/det_r50_vd_db/，经过尝试应该是./checkpoints/det_r50_vd_db/best_accuracy，学习率也可以修改了，谢谢
