### ISSUE TITLE
一些小语种字典里的字符问题

### ISSUE THREAD

**Issue by yangyang-nus-lv** [PaddlePaddle/PaddleOCR#6362]
类似梵文这种字母的上下部分可以带语调或者符号的文字，字典里把单个符号作为一类，这样进行编码适合CTC吗？举个例子：
'க்' 是泰米尔语的一个文字，由 'க' 和 '்' 合并而成，unicode编码也是两个字符的组合。在 `ppocr/utils/dict/ta_dict.txt` 字典里是没有这个字的，但是有这两个拆开的元素作为两类。当进行CTC编码的时候这个字会对应两个字符class，预测时由竖向排列的两个部分构成的单个文字，需要被预测成横向排列的两个符号，这就有两个问题：
1. 此时一个（或多个）step对应多个label，属于一对多（或者多对多）而不是多对一的对齐方式，CTC本身不适合做；
2. 竖向上排列的视觉信息被横向编码了，感觉也不是很直接。

基于上述分析，请问是否可以考虑像中文字典那样，遍历所有可能的组合得到字典里的每一类都是单一字符？毕竟，中文的偏旁部首不会单独拆出来成为一类进行编码预测。

**Comment by yangyang-nus-lv** [comment]
当然，遍历出来的字符里，会有很多相似的组合字符。又会给网络学习增加难度，有点棘手。

**Comment by yangyang-nus-lv** [comment]
https://grapheme.readthedocs.io/en/latest/index.html 这个工具可以进行单个字符的分割
```
>>> k = 'க்'
>>> print(k.encode('utf-8'))
b'\xe0\xae\x95\xe0\xaf\x8d'

>>> for char in k:
        print(char)
க
்
>>> list(grapheme.graphemes(k))
['க்']
```

**Comment by littletomatodonkey** [comment]
你好，目前是按照统一的方式去处理的，没有考虑你说的这种情况，不然的话多语言的处理方法会有不同的变化哈，比较难以统一

**Comment by yangyang-nus-lv** [comment]
@littletomatodonkey 谢谢回复
