### ISSUE TITLE
用自定义数据集训练PP-OCR 

### ISSUE THREAD

**Issue by xireli** [PaddlePaddle/PaddleOCR#6365]
您好，我用自己的数据集（10W+）训练multi_language OCR模型时，训练很正常，acc=0.9左右，loss=0.3左右。识别时候短文本识别效果很好，但是长文本（包含空格的三四个单词以上的文本）识别不准，请问这可能是什么原因？训练集里没有长文本数据

**Comment by littletomatodonkey** [comment]
你好，建议合成一些长文本（不要超过25个字符）加入到训练集中训练试下
