### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"

### ISSUE THREAD

**Issue by feter** [PaddlePaddle/PaddleOCR#6366]
D:\pycode>pip install "paddleocr>=2.0.1"
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting paddleocr>=2.0.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f2/13/93d5fa0c96111322065b6ad2cb8818c674b42dc0f2411ad87a437021665c/paddleocr-2.5.0.3-py3-none-any.whl (334 kB)
Collecting imgaug==0.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/66/b1/af3142c4a85cba6da9f4ebb5ff4e21e2616309552caca5e8acefe9840622/imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Collecting opencv-contrib-python==4.4.0.46
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/85/3b/a45ee6928c04f3f842ae8feb77f39e5896e61beb1683df80fe665184e95f/opencv_contrib_python-4.4.0.46-cp38-cp38-win
_amd64.whl (40.2 MB)
Requirement already satisfied: lmdb in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (1.3.0)
Collecting visualdl
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/87/c8/10d0d24822637d8e5493a73ad118640530195e45b1c71ae0e60606ff5f0e/visualdl-2.2.3-py3-none-any.whl (2.7 MB)
Collecting openpyxl
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7b/60/9afac4fd6feee0ac09339de4101ee452ea643d26e9ce44c7708a0023f503/openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)

     ---------------------------------------- 242.1/242.1 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: lxml in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (4.6.1)
Requirement already satisfied: pyclipper in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (1.3.0.post2)
Requirement already satisfied: cython in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (0.29.28)
Collecting premailer
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b1/07/4e8d94f94c7d41ca5ddf8a9695ad87b888104e2fd41a35546c1dc9ca74ac/premailer-3.10.0-py2.py3-none-any.whl (19 kB
)
Collecting python-Levenshtein
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/dc/97f2b63ef0fa1fd78dcb7195aca577804f6b2b51e712516cc0e902a9a201/python-Levenshtein-0.12.2.tar.gz (50 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-image
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/b0/3476439c9d4a85e3040bb3a5645fe32013bd41537eb3dab5efd048602fc1/scikit_image-0.19.2-cp38-cp38-win_amd64.whl
(12.6 MB)
Requirement already satisfied: numpy in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (1.19.3)
Requirement already satisfied: tqdm in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (4.64.0)
Requirement already satisfied: shapely in d:\python38\lib\site-packages (from paddleocr>=2.0.1) (1.8.2)
Collecting attrdict
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/97/28fe7e68bc7adfce67d4339756e85e9fcf3c6fd7f0c0781695352b70472c/attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)

Requirement already satisfied: six in d:\python38\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (1.16.0)
Requirement already satisfied: opencv-python in d:\python38\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (4.5.4.60)
Collecting imageio
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/25/41/91f47808e99dd67bfc3aee53d0a7c8d10b01b221ca254bfd36cd51125866/imageio-2.19.2-py3-none-any.whl (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 3.9 MB/s eta 0:00:00
Collecting matplotlib
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/0d/bebf456dd3b5bb4ecd78cb1e78636f38716384529d083ed78327ba49ec83/matplotlib-3.5.2-cp38-cp38-win_amd64.whl (7.
2 MB)
Requirement already satisfied: scipy in d:\python38\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (1.8.0)
Requirement already satisfied: Pillow in d:\python38\lib\site-packages (from imgaug==0.4.0->paddleocr>=2.0.1) (8.1.0)
Requirement already satisfied: tifffile>=2019.7.26 in d:\python38\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (2022.5.4)
Collecting networkx>=2.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b9/2b/d7f2eb2c046bde48303b46d6467086b4aae60852e154f36fff0cf02fe35a/networkx-2.8.1-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 3.9 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in d:\python38\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (21.3)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\python38\lib\site-packages (from scikit-image->paddleocr>=2.0.1) (1.3.0)
Collecting et-xmlfile
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: cssselect in d:\python38\lib\site-packages (from premailer->paddleocr>=2.0.1) (1.1.0)
Collecting cssutils
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cc/ee/0f8a57df120e1003e461f014b2412278e94b1ce488b9c88464dd012ee1e7/cssutils-2.4.0-py3-none-any.whl (404 kB)
Requirement already satisfied: cachetools in d:\python38\lib\site-packages (from premailer->paddleocr>=2.0.1) (4.2.4)
Requirement already satisfied: requests in d:\python38\lib\site-packages (from premailer->paddleocr>=2.0.1) (2.26.0)
Requirement already satisfied: setuptools in d:\python38\lib\site-packages (from python-Levenshtein->paddleocr>=2.0.1) (62.2.0)
Requirement already satisfied: colorama in d:\python38\lib\site-packages (from tqdm->paddleocr>=2.0.1) (0.4.4)
Collecting pre-commit
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/e4/5010a2ac43548cb35975d0c8011d4f43d9201fe63154698965effba4cf02/pre_commit-2.19.0-py2.py3-none-any.whl (199
kB)
Collecting bce-python-sdk
  Using cached bce_python_sdk-0.8.64-py3-none-any.whl
Requirement already satisfied: flask>=1.1.1 in d:\python38\lib\site-packages (from visualdl->paddleocr>=2.0.1) (2.0.2)
Requirement already satisfied: pandas in d:\python38\lib\site-packages (from visualdl->paddleocr>=2.0.1) (1.4.2)
Requirement already satisfied: shellcheck-py in d:\python38\lib\site-packages (from visualdl->paddleocr>=2.0.1) (0.8.0.4)
Collecting flake8>=3.7.9
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/34/39/cde2c8a227abb4f9ce62fe55586b920f438f1d2903a1a22514d0b982c333/flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting Flask-Babel>=1.0.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/3e/02331179ffab8b79e0383606a028b6a60fb1b4419b84935edd43223406a0/Flask_Babel-2.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: protobuf>=3.11.0 in d:\python38\lib\site-packages (from visualdl->paddleocr>=2.0.1) (3.17.3)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in d:\python38\lib\site-packages (from flake8>=3.7.9->visualdl->paddleocr>=2.0.1) (0.6.1)
Collecting pycodestyle<2.9.0,>=2.8.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/15/94/bc43a2efb7b8615e38acde2b6624cae8c9ec86faf718ff5676c5179a7714/pycodestyle-2.8.0-py2.py3-none-any.whl (42 k
B)
Collecting pyflakes<2.5.0,>=2.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/fb/38848eb494af7df9aeb2d7673ace8b213313eb7e391691a79dbaeb6a838f/pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Requirement already satisfied: Jinja2>=3.0 in d:\python38\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (3.1.2)
Requirement already satisfied: Werkzeug>=2.0 in d:\python38\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.0.2)
Requirement already satisfied: click>=7.1.2 in d:\python38\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (8.0.3)
Requirement already satisfied: itsdangerous>=2.0 in d:\python38\lib\site-packages (from flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.0.1)
Requirement already satisfied: pytz in d:\python38\lib\site-packages\pytz-2021.1-py3.8.egg (from Flask-Babel>=1.0.0->visualdl->paddleocr>=2.0.1) (2021.1)
Collecting Babel>=2.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c5/7b/2c9fc1e18cb97676c7bedaa872447eb720e0c6e0e48190b4fba7eccdc1a8/Babel-2.10.1-py3-none-any.whl (9.5 MB)
Collecting Pillow
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/71/54/bc24063ddb7ebb0962db41167971737f52351628907cf5c846f87d3501fc/Pillow-9.1.1-cp38-cp38-win_amd64.whl (3.3 MB)

     ---------------------------------------- 3.3/3.3 MB 3.4 MB/s eta 0:00:00
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\python38\lib\site-packages (from packaging>=20.0->scikit-image->paddleocr>=2.0.1) (3.0.9)
Requirement already satisfied: pycryptodome>=3.8.0 in d:\python38\lib\site-packages (from bce-python-sdk->visualdl->paddleocr>=2.0.1) (3.11.0)
Requirement already satisfied: future>=0.6.0 in d:\python38\lib\site-packages (from bce-python-sdk->visualdl->paddleocr>=2.0.1) (0.18.2)
Requirement already satisfied: fonttools>=4.22.0 in d:\python38\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (4.27.0)
Collecting kiwisolver>=1.0.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/2d/32ae1ce44d5b514dce568a809b3bed15d60ee1501b9fa9853a0fee705b59/kiwisolver-1.4.2-cp38-cp38-win_amd64.whl (55
 kB)
Collecting cycler>=0.10
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: python-dateutil>=2.7 in d:\python38\lib\site-packages (from matplotlib->imgaug==0.4.0->paddleocr>=2.0.1) (2.8.2)
Requirement already satisfied: toml in d:\python38\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (0.10.2)
Requirement already satisfied: pyyaml>=5.1 in d:\python38\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (6.0)
Requirement already satisfied: nodeenv>=0.11.1 in d:\python38\lib\site-packages (from pre-commit->visualdl->paddleocr>=2.0.1) (1.6.0)
Collecting cfgv>=2.0.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6d/82/0a0ebd35bae9981dea55c06f8e6aaf44a49171ad798795c72c6f64cba4c2/cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting identify>=1.0.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8c/da/6261bbc458863a075fb6f1c292c639da8d6a432b574adc21f3168e5c1da7/identify-2.5.1-py2.py3-none-any.whl (98 kB)
     ---------------------------------------- 98.6/98.6 kB ? eta 0:00:00
Collecting virtualenv>=20.0.8
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9e/34/e86fc6a8f84329b49321a532b3c1fef103c67765df957fbb3852eea39d00/virtualenv-20.14.1-py2.py3-none-any.whl (8.8
 MB)
Requirement already satisfied: certifi>=2017.4.17 in d:\python38\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (2020.6.20)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\python38\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python38\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in d:\python38\lib\site-packages (from requests->premailer->paddleocr>=2.0.1) (2.7)
Requirement already satisfied: MarkupSafe>=2.0 in d:\python38\lib\site-packages (from Jinja2>=3.0->flask>=1.1.1->visualdl->paddleocr>=2.0.1) (2.1.1)
Requirement already satisfied: filelock<4,>=3.2 in d:\python38\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl->paddleocr>=2.0.1) (3.6.0)
Collecting platformdirs<3,>=2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ed/22/967181c94c3a4063fe64e15331b4cb366bdd7dfbf46fcb8ad89650026fec/platformdirs-2.5.2-py3-none-any.whl (14 kB)
Requirement already satisfied: distlib<1,>=0.3.1 in d:\python38\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl->paddleocr>=2.0.1) (0.3.4)
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\__init__.py -> build\lib.win-amd64-cpython-38\Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info\PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
      deleting python_Levenshtein.egg-info\entry_points.txt
      writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info\requires.txt
      writing top-level names to python_Levenshtein.egg-info\top_level.txt
      reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
      copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-cpython-38\Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-Levenshtein
  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
Installing collected packages: python-Levenshtein, pyflakes, pycodestyle, platformdirs, Pillow, opencv-contrib-python, networkx, kiwisolver, identify, et-xmlfile, cycler
, cssutils, cfgv, bce-python-sdk, Babel, attrdict, virtualenv, premailer, openpyxl, matplotlib, imageio, flake8, scikit-image, pre-commit, Flask-Babel, visualdl, imgaug,
 paddleocr
  Running setup.py install for python-Levenshtein ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-Levenshtein did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running install
      D:\Python38\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards
-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\__init__.py -> build\lib.win-amd64-cpython-38\Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info\PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
      writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info\requires.txt
      writing top-level names to python_Levenshtein.egg-info\top_level.txt
      reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
      copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-cpython-38\Levenshtein
      copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-cpython-38\Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-Levenshtein

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by littletomatodonkey** [comment]
You can refer to this issue for the solution. https://github.com/PaddlePaddle/PaddleOCR/issues/5528
