### ISSUE TITLE
PaddleOCR V3版本推理速度下降

### ISSUE THREAD

**Issue by zhaoweihan2017** [PaddlePaddle/PaddleOCR#6372]
按照教程更新PaddleOCR V3版本whl包：
paddleocr                         2.5.0.3
paddlepaddle                      2.3.0
paddlepaddle-gpu                  2.3.0

配置参数：
Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='../model/ch_ppocr_mobile_v2.0_cls_infer/', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=1920, det_limit_type='max', det_model_dir='../model/ch_ppocr_server_v2.0_det_infer/', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', layout=True, layout_label_map=None, layout_path_model='lp://TableBank/ppyolov2_r50vd_dcn_365e_tableBank_word/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, mode='structure', ocr=True, ocr_version='PP-OCRv3', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='../engine/dict/ppocr_keys_v1.txt', rec_image_shape='3, 32, 640', rec_model_dir='../model/ch_ppocr_server_v2.0_rec_infer/', save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], show_log='True', structure_version='PP-STRUCTURE', table=True, table_char_dict_path='../engine/dict/table_structure_dict.txt', table_char_type='en', table_max_len=488, table_model_dir='../model/en_ppocr_mobile_v2.0_table_structure_infer/', total_process_num=1, type='ocr', use_angle_cls='True', use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char='True', use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)

经过在CPU上测试，推理速度明显低于V2版本，请问一般是什么原因导致？

**Comment by LDOUBLEV** [comment]
在CPU上建议开启mkldnn，设置enable_mkldnn=True

**Comment by wangjunjx8868** [comment]
> 在CPU上建议开启mkldnn，设置enable_mkldnn=True

如何开启mkldnn，enable_mkldnn=True在哪配置？

**Comment by MissPenguin** [comment]
> > 在CPU上建议开启mkldnn，设置enable_mkldnn=True
> 
> 如何开启mkldnn，enable_mkldnn=True在哪配置？

使用paddleocr wheel包预测的话，在命令行中加上  --enable_mkldnn true 即可

**Comment by LDOUBLEV** [comment]
你目前namespace里的参数enable_mkldnn=False, 是False
