### ISSUE TITLE
斜体文字要生成对应斜体样本？这种小点背景是要模拟背景，还是有什么办法在识别前预处理，过滤点背景？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6373]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

斜体文字要生成对应斜体样本？这种小点背景是要模拟背景，还是有什么办法在识别前预处理，过滤点背景？
![image](https://user-images.githubusercontent.com/41010669/169718711-06ce9ca0-0887-43aa-8879-87865527bba2.png)

**Comment by LDOUBLEV** [comment]
现在遇到的是什么问题呢，是此类背景的图像识别不对吗？

> 斜体文字要生成对应斜体样本？

生成斜体数据的时候，用斜体的字体应该就可以

> 这种小点背景是要模拟背景，还是有什么办法在识别前预处理，过滤点背景？

PaddleOCR暂没有此类预处理代码，你可以调研下Opencv里的图像处理
