### ISSUE TITLE
模型预测结果超出对应字典

### ISSUE THREAD

**Issue by LeiChengxiang** [PaddlePaddle/PaddleOCR#6374]
测试中，ch_ppocr_mobile_v1.1_rec_opt.nb模型预测结果序号是8868，超出了对应的字典char_table.txt的范围(6623),导致在字典中查询对应字符时，数组下标发生了越界。请问一下，这个模型预测结果最多包含多少字符呢？

**Comment by tink2123** [comment]
请问是直接使用了官方模型吗，还是自己重新训练的呢？ 模型预测支持的字符与训练时选择的字典一致。

**Comment by LeiChengxiang** [comment]
是直接下载的官方模型，V1.1版本的超轻量中文OCR 移动端模型，在这个地方下载的https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/deploy/lite/readme.md
