### ISSUE TITLE
请问如何计算PGNet的性能评估指标？

### ISSUE THREAD

**Issue by guguguzi** [PaddlePaddle/PaddleOCR#6380]
您好，最近在研究端到端ocr算法的性能评估指标，请问PaddleOCR中PGNet算法（如下图）有提供评估脚本吗？
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/48168743/169784404-fa4ccabe-5029-439e-b351-3e7f7c277f63.png">

**Comment by LDOUBLEV** [comment]
这个评测用的是MAT格式，这部分代码暂没有公开
