### ISSUE TITLE
检测模型精度问题

### ISSUE THREAD

**Issue by xiongzl** [PaddlePaddle/PaddleOCR#6381]
官方文档上貌似只提供了一部分的模型精度指标：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/algorithm_overview.md
![image](https://user-images.githubusercontent.com/13463574/169797185-5e1cbc86-4c53-444f-b0a9-9eb2a80d14c4.png)
但一些轻量化的模型没有提供在公开数据集上的指标,比如下面这张图的指标没有提供。
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md
![image](https://user-images.githubusercontent.com/13463574/169797885-8cdaf108-5f18-431e-932e-d114c5e7e3b4.png)

我下载了上面图中红框地址的训练模型，在icdar2015上测试了一下，精度感觉比较低。
precision:0.5806 recall:0.40057 hmean:0.474  fps:59.66 
这个指标测试出来是正常的吗，还是我测试错了？
测试脚本为：
python tools/eval.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml -o Global.checkpoints=./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy

**Comment by LDOUBLEV** [comment]
你没有测试错，上面图中红框地址的训练模型 的训练数据是中文训练数据，而且训练标注格式为句子级，icdar2015用的是单词级的标注；
ch_ppocr*系列的模型主打中文自然场景；和icdar2015不一样

**Comment by xiongzl** [comment]
了解了 追问一句 如果训练集同时存在句子级、单词级、字符级三种标注样式，是否是建议分开单独训练会更合适，放在一起训练可能会效果不佳。PaddleOCR对于多种标注样式的训练策略是怎样的

**Comment by LDOUBLEV** [comment]
> 同时存在句子级、单词级、字符级三种标注样式

最好是统一的数据格式训练

**Comment by xiongzl** [comment]
好的 目前dbnet++已经出来了 ，PaddleOCR是否有计划支持

**Comment by LDOUBLEV** [comment]
DB++计划中
