### ISSUE TITLE
paddleOCR with tensorRT

### ISSUE THREAD

**Issue by laughing33** [PaddlePaddle/PaddleOCR#6388]
paddle不是内置了trt加速吗，那我想要在工程里对ocr的模型加速需要做什么？在config里设置gpu=1;tensorrt=1之后，再根据官网文档自行cmake编译后提示无法加载tensorrt api

**Comment by laughing33** [comment]
或者说paddle_inference_install_dir编译成功以后如何在ocr工程里开启tensorrt加速？

**Comment by andyjpaddle** [comment]
使用的是哪种推理方式呢？
