### ISSUE TITLE
单字训练的识别模型，无论输入大于3个字的图片，识别结果最大不超过3个字，只识别首尾 ，中间会丢字

### ISSUE THREAD

**Issue by angel-yi** [PaddlePaddle/PaddleOCR#6389]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by angel-yi** [comment]
识别模型版本是最新的v3
输入的图片是4个字及以上，会输出首尾的文字，且最大不超过3个
不知道是什么原因，希望大大能回复一下

**Comment by angel-yi** [comment]
![img_30](https://user-images.githubusercontent.com/51775756/170170735-0338673e-e24a-4d0e-9cce-b6f722884e42.png)
就像这两张图，识别出来的结果都是【月八年】，第二个字丢失

**Comment by angel-yi** [comment]
![img_30](https://user-images.githubusercontent.com/51775756/170170849-6aeacc09-fbcf-4bf7-a225-36483eac3e91.png)
![img_31](https://user-images.githubusercontent.com/51775756/170170865-ead29262-855b-4fc7-9768-311a24686763.png)

就像这两张图，识别出来的结果都是【月八年】，第二个字丢失

**Comment by yangy996** [comment]
试试这种方式
https://blog.csdn.net/YY007H/article/details/124973777
