### ISSUE TITLE
Memory isn't freeing after forward pass. how to clear cache manually?

### ISSUE THREAD

**Issue by shekargoud26** [PaddlePaddle/PaddleOCR#639]
This is the usage before a forward pass. The memory usage is 6831mb
![before](https://user-images.githubusercontent.com/16861024/91695527-e9941900-eb8b-11ea-90cc-10d45cf44f84.png)

This is the usage after a forward pass. memory usage is 7123mb and it doesn't decrease after forward pass.
![after](https://user-images.githubusercontent.com/16861024/91695721-35df5900-eb8c-11ea-9f54-1f8312535520.png)

is it possible to clear cache manually like in pytorch by calling torch.cuda.empty_cache() ?

**Comment by littletomatodonkey** [comment]
`kill -9 your_pid_num` may solve the problem.

**Comment by shekargoud26** [comment]
> `kill -9 your_pid_num` may solve the problem.

I'm running it as a flask API. So i can't restart the API after every forward pass.
