### ISSUE TITLE
C++的轻量版lite文本识别模型推理 GPU与CPU版本的结果不一致

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/PaddleOCR#6395]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：jetson nano linux C++
- 版本号/Version：Paddle：2.0  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code
- 完整报错/Complete Error Message：

==========================================================
C++版本的文本识别模型 comm大模型将shape统一成(3,32,320)后结果正常，但lite轻量化模型的识别仍然存在问题，如下图所示，5509888数字识别错了，训练的精度已经很高了99%以上。本人做了以下对照实验，问题应该出在GPU部分，往大佬赐教：
1、C++版本的rec 大模型同样的图片在CPU和GPU模式下运行都可以获得正确结果。
2、C++版本的rec lite模型同样的图片CPU模式下运行可以获得正确结果。
3、C++版本的rec lite模型同样的图片在GPU模式下运行获得结果不正确。参见下图。

![image](https://user-images.githubusercontent.com/20531040/170049172-63b16a49-f538-4f3f-86ab-a90f245f7b04.png)

**Comment by blackhitomi** [comment]
补充：
4、C++版本的rec lite模型同样的图片在服务器的GPU模式下运行获得结果正确。

难道jetson系列有什么特殊的地方？

**Comment by andyjpaddle** [comment]
能提供一次测试图片吗

**Comment by blackhitomi** [comment]
> 能提供一次测试图片吗
您好测试图片如下：用的自己编译的jetson版本paddle 2.0的C++库 
![image](https://user-images.githubusercontent.com/20531040/170647681-e49d3f42-a5ee-4e17-bd3c-0718bb9b3683.png)

**Comment by blackhitomi** [comment]
> 能提供一次测试图片吗

另外，我在paddle那边提问有回复是说jetson版本paddle 2.0库的bug，在最新版修复了，请参见：
https://github.com/PaddlePaddle/Paddle/issues/43031

**Comment by blackhitomi** [comment]
> > 能提供一次测试图片吗
> 
> 另外，我在paddle那边提问有回复是说jetson版本paddle 2.0库的bug，在最新版修复了，请参见： [PaddlePaddle/Paddle#43031](https://github.com/PaddlePaddle/Paddle/issues/43031)

由于现场环境已经固定不太好升级paddle，我正在尝试参照修复PR 手动修复2.0版本的bug，jetson编译较慢，还没有结果。

**Comment by andyjpaddle** [comment]
那可以根据paddle回复的修复方式试试

**Comment by blackhitomi** [comment]
> 



> 那可以根据paddle回复的修复方式试试

我测试了2.2的paddle库 但是jetson nano上还是一样的结果 能否麻烦你们检查一下具体原因呢 谢谢！

**Comment by blackhitomi** [comment]
> 那可以根据paddle回复的修复方式试试

2.2版本搭配2.3版本的OCR没有问题了，感谢各位大佬！
