### ISSUE TITLE
PaddleOCR的在线识别不出结果

### ISSUE THREAD

**Issue by FangJingYunner** [PaddlePaddle/PaddleOCR#6399]
您好，我看https://www.paddlepaddle.org.cn/hub/scene/ocr上的PaddleOCR在线识别功能失效了，请问可不可以恢复一下。

**Comment by MissPenguin** [comment]
感谢反馈！这就去修，修复后在这里反馈～

**Comment by MissPenguin** [comment]
已修复～再次感谢反馈！
