### ISSUE TITLE
multiprocess is not fully compatible with Windows.num_workers will be 1.

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleOCR#640]
Whether the multiprocess will be compatible with windows later when we training the  rec model

**Comment by littletomatodonkey** [comment]
Thanks for you attention, `multiprocessor` lib is not supported on Windows, so it is up to the multiprocessor lib.  Of course if want to develop a new method  for windwos multi process, welcome to PR to us!

**Comment by BeyondYourself** [comment]
thx
