### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by 2205825969** [PaddlePaddle/PaddleOCR#6405]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
save_epoch_step: 3    
这个参数如果改成300会不会对实验效果有影响

**Comment by WenmuZhou** [comment]
不会
