### ISSUE TITLE
模型选择问题

### ISSUE THREAD

**Issue by Altman7** [PaddlePaddle/PaddleOCR#6410]
目前项目识别的内容大部分都是应用工程打印的日志，大部分都是英文内容，但也包含少量中文
这种请款下该使用英文模型还是中文模型
目前测试时使用的中英文模型，识别效果不是很理想，空格及其他标点识别度也不是很高
如果自己训练模型的话，大约多少张图片合适

**Comment by littletomatodonkey** [comment]
1. 如果要求保证中文字符的准确性的话，建议用中英文模型
2. 自己训练的话，建议至少准备3000张真实的识别图片，再结合一些开源识别数据，混合训练，会有比较好的精度
