### ISSUE TITLE
when  release picodet model, dbnet infer crash with (Fatal signal 11 (SIGSEGV))

### ISSUE THREAD

**Issue by wangwh0128** [PaddlePaddle/PaddleOCR#6411]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Android
- 版本号/Version：Paddle： paddlelite2.10
-  PaddleOCR： V2.3
- 问题相关组件/Related components：dbnet
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
picodet和ppocr的dbnet直接有什么关联呢？不加picodet模型dbnet正常，加载picodet和dbnet模型后，释放了picodet后，dbnet推理就100%报错，请帮忙看看？
I/OCR_NDK: infer_ocr entry
I/OCR_NDK: infer Run start
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x43b671bec3c00780 in tid 5018 (RxComputationTh), pid 4966

**Comment by littletomatodonkey** [comment]
你好，可能是因为2个inference model有冲突，这里建议提供下最小的复现代码哈

**Comment by littletomatodonkey** [comment]
另外就是建议用debug模式预测看下

**Comment by wangwh0128** [comment]
debug模式编译的paddlelite好像也没有特殊的日志信息。
最小代码包含模型文件吗？
