### ISSUE TITLE
self.input_tensor.copy_from_cpu( ) 第一次很慢

### ISSUE THREAD

**Issue by xlsay** [PaddlePaddle/PaddleOCR#6415]
在用 tools/predict_rec.py 进行推理时，发现推理一张图片时
self.input_tensor.copy_from_cpu(norm_img_batch)需要接近2s的时间。

测试同时推理多张，不管batch_size是1还是其他值，总是第一个batch的耗时接近2s，后面的batch都很快甚至不到1ms，请问这是什么原因，有什么特殊的配置来解决吗？

**Comment by littletomatodonkey** [comment]
你好，是的，第一次需要做初始化，warmup，建议在实际使用使用的时候，先随机预测一张图像，之后有真实图像的时候，速度就会快很多

**Comment by wxiaoli** [comment]
> 你好，是的，第一次需要做初始化，warmup，建议在实际使用使用的时候，先随机预测一张图像，之后有真实图像的时候，速度就会快很多

 好的，谢谢
