### ISSUE TITLE
使用gpu版本的paddleocr一定要安装cudnn吗

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6416]
使用gpu版本的paddleocr一定要安装cudnn吗
![image](https://user-images.githubusercontent.com/37231239/170683882-41a27a1d-846e-478b-8d34-aca4abe88655.png)

**Comment by littletomatodonkey** [comment]
你好，默认是这样的，

**Comment by GivanTsai** [comment]
> 

@littletomatodonkey 那哪里可以关闭使用cudnn呢

**Comment by Gmgge** [comment]
是因为GPU设备的原因无法安装cudnn吗？如果是的话，需要在paddle确认是否支持该GPU。

**Comment by GivanTsai** [comment]
> 

是因为要在容器中装cudnn，这样会很臃肿
