### ISSUE TITLE
【C++部署，多线程并行处理】创建多线程，实例化CRNNRecognizer对象，并行处理出现异常

### ISSUE THREAD

**Issue by JoyshowXia** [PaddlePaddle/PaddleOCR#6419]
因为有大量图片要识别，单个CRNNRecognizer推理太慢，所以我这边创建多个线程，每个线程实例化一个CRNNRecognizer来并行处理，开启mkldnn后跑一段时间就会出现异常，如下图↓关闭mkldnn则不会有这个问题，但是整体速度会慢太多。请问paddleocr是否支持多线程并行处理？
![image](https://user-images.githubusercontent.com/48970882/170814664-f3b8a73d-a235-4be4-ae94-f8c7065e8d56.png)

**Comment by WenmuZhou** [comment]
paddle inference不是线程安全的，开多线程会出现一些问题

**Comment by JoyshowXia** [comment]
那针对这种需求有什么比较好的方案吗？
