### ISSUE TITLE
PaddleOCR2.5  paddle_inference 2.2 c++ 编译报错

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#6420]
[root@localhost install2]# cd PaddleOCR
[root@localhost PaddleOCR]# git branch
* release/2.5

paddle_inference 2.2
manylinux_cpu_avx_mkl_gcc5.4  paddle_inference.tgz
GIT COMMIT ID: 590b4dbcdd989324089ce43c22ef151c746c92a3
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
WITH_IPU: OFF
CXX compiler version: 5.4.0

编译的时候报错
[root@localhost cpp_infer]# ./tools/build.sh 
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/install/opencv-3.4.3/build (found version "3.4.3") 
cmake cxx flags -g -o3 -fopenmp -std=c++11
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
default cmake for auto_log, no need to compile
-- Configuring done
-- Generating done
-- Build files have been written to: /home/install2/PaddleOCR/deploy/cpp_infer/build
Scanning dependencies of target ppocr
[  9%] Building CXX object CMakeFiles/ppocr.dir/src/args.cpp.o
[ 18%] Building CXX object CMakeFiles/ppocr.dir/src/clipper.cpp.o
[ 27%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 36%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 45%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 54%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
[ 63%] Building CXX object CMakeFiles/ppocr.dir/src/paddleocr.cpp.o
[ 72%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
[ 81%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
[ 90%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
[100%] Linking CXX executable ppocr
/usr/bin/ld: warning: libonnxruntime.so.1.10.0, needed by /home/install/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpaddle2onnx.so, needed by /home/install/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/home/install/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `OrtGetApiBase@VERS_1.10.0'
/home/install/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::Export(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, int, bool, bool, bool, bool, bool)'
/home/install/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::IsExportable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool, bool, bool, bool, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [ppocr] Error 1
make[1]: *** [CMakeFiles/ppocr.dir/all] Error 2
make: *** [all] Error 2

**Comment by ANDROIDTODO** [comment]
PaddleOCR branch V2.5 有更新cpp推理demo
https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/cpp_infer

**Comment by linkewei0580** [comment]
> PaddleOCR branch V2.5 有更新cpp推理demo https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/cpp_infer
> 
> Paddle OCR v2.5 应该使用 paddle inference V2.3.0的版本 https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html

你好，我用paddle inference v2.3 也是一样的提示。

**Comment by ANDROIDTODO** [comment]
@linkewei0580 
你应该是CMake没有链接对应的动态库吧
![image](https://user-images.githubusercontent.com/10429542/171102017-93f8b3a6-3e14-4795-ad99-c088f33801e9.png)

或者是你下载的推理库，查看是否存在libonnxruntime.so.1.10.0和libpaddle2onnx.so
你下载的库中，在thridpart应该有onnxruntime和paddle2onnx这2个文件夹

**Comment by linkewei0580** [comment]
> @linkewei0580 你应该是CMake没有链接对应的动态库吧 ![image](https://user-images.githubusercontent.com/10429542/171102017-93f8b3a6-3e14-4795-ad99-c088f33801e9.png)
> 
> 或者是你下载的推理库，查看是否存在libonnxruntime.so.1.10.0和libpaddle2onnx.so 你下载的库中，在third-party应该有onnxruntime和paddle2onnx这2个文件夹

谢谢，应该是CMakeLists.txt有更新了，现在可以编译成功。
