### ISSUE TITLE
PaddleOCR多卡训练时报错

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleOCR#6423]
请问我按照示例启动多卡训练为什么会报这种错误，不知道哪里出的问题
![436791b4484f3763cf9fac59d90659d](https://user-images.githubusercontent.com/102035987/170823655-97522c07-e358-4af9-b3a2-67182740af52.png)
![92cf696afec726fd4aa24d630cad329](https://user-images.githubusercontent.com/102035987/170823657-e74339fa-6474-4797-8e6a-188a4afc9c35.png)
和官方文档中的示例也基本类似
![4e5d39a4c2124505a41902568812861](https://user-images.githubusercontent.com/102035987/170823703-57bb3cb6-85b2-4994-9575-f5de46758d80.png)
求大神解答,感谢！

**Comment by yangy996** [comment]
aistudio就一个卡，为什么会用到多卡呢？

**Comment by Dekadenc** [comment]
> aistud就一个卡，为什么会多卡呢？

可是文档里不是说了可以多卡训练嘛，您的意思是ocr仅支持单卡训练吗。

**Comment by Dekadenc** [comment]
> > > aistud就一个卡，为什么会多卡呢？
> > 
> > 
> > 可是文档里不是说了可以多卡训练嘛，您的意思是ocr仅支持单卡训练吗。
> 
> 多卡指的是多个显卡，aistudio就提供了一张显卡，你怎么用多卡训练？

好吧我明白您的意思了，感谢。

**Comment by yulm-1** [comment]
> > > aistud就一个卡，为什么会多卡呢？
> > 
> > 
> > 可是文档里不是说了可以多卡训练嘛，您的意思是ocr仅支持单卡训练吗。
> 
> 多卡指的是多个显卡，aistudio就提供了一张显卡，你怎么用多卡训练？

我在自己电脑的多卡上也遇到了这个问题，我的电脑是四个卡的，这个问题怎么解决呢？

![image](https://user-images.githubusercontent.com/113872348/191633255-ab12ccad-6bab-41a8-9022-b261494c9537.png)

**Comment by yangy996** [comment]
> > > > aistud就一个卡，为什么会多卡呢？
> > > 
> > > 
> > > 可是文档里不是说了可以多卡训练嘛，您的意思是ocr仅支持单卡训练吗。
> > 
> > 
> > 多卡指的是多个显卡，aistudio就提供了一张显卡，你怎么用多卡训练？
> 
> 我在自己电脑的多卡上也遇到了这个问题，我的电脑是四个卡的，这个问题怎么解决呢？
> 
> ![image](https://user-images.githubusercontent.com/113872348/191633255-ab12ccad-6bab-41a8-9022-b261494c9537.png)

nvidia-smi 命令看一下

**Comment by yulm-1** [comment]
![image](https://user-images.githubusercontent.com/113872348/191633870-d4aadfd0-47ce-4142-ae59-5c5a8ecd3d7e.png)
