### ISSUE TITLE
c++部署服务，预测出现异常，请大佬指点

### ISSUE THREAD

**Issue by xiehuangpeng** [PaddlePaddle/PaddleOCR#6424]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：docker Serving镜像
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.5  Serving: 0.9.0 自己编译的serving，client，app 问题相关组件/Related components：
- 运行指令/Command Code：python3.7 -m paddle_serving_server.serve --model ppocr_det_v3_serving ppocr_rec_v3_serving --op GeneralDetectionOp GeneralInferOp --port 9293 &>log.txt &
python3.7 ocr_cpp_client.py ppocr_det_v3_client ppocr_rec_v3_client
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "ocr_cpp_client.py", line 49, in <module>
    one_batch_res = ocr_reader.postprocess(fetch_map, with_score=True)
  File "/home/PaddleOCR/deploy/pdserving/ocr_reader.py", line 396, in postprocess
    preds = list(outputs.values())[0]
AttributeError: 'NoneType' object has no attribute 'values'
I0528 13:36:44.222119    73 socket.cpp:2201] Checking Socket{id=0 addr=127.0.0.1:9293} (0x14f3e50)

**Comment by Richuanwu** [comment]
和楼主一样这样的错误，所以我尝试下面的运行指令，出现以下的错误

- **系统环境**/System Environment：docker serving:0.8.0-devel镜像

- **版本号**/Version：Paddle：2.3.1 PaddleOCR：2.5 Serving: 0.9.0 自己编译的serving，client，app 问题相关组件/Related components：

- **运行指令**/Command Code：python3.7 -m paddle_serving_server.serve --model ppocr_det_v3_serving ppocr_rec_v3_serving --op GeneralDetectionOp GeneralInferOp --port 9998

- **完整报错**/Complete Error Message：
/usr/local/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Use local bin : /home/Serving/build_server/core/general-server/serving
Going to Run Comand
/home/Serving/build_server/core/general-server/serving -enable_model_toolkit -inferservice_path workdir_9998 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 4 -port 9998 -precision fp32 -use_calib=False -reload_interval_s 10 -resource_path workdir_9998 -resource_file resource.prototxt -workflow_path workdir_9998 -workflow_file workflow.prototxt -bthread_concurrency 4 -max_body_size 536870912
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralRecOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralRemoteOp
I0100 00:00:00.000000 18684 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000 18684 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000 18684 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000 18684 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000 18684 general_model_service.pb.h:1650] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000 18684 factory.h:155] RAW: Succ insert one factory, tag: PADDLE_INFER, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 18684 paddle_engine.cpp:34] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<PaddleInferenceEngine>->::baidu::paddle_serving::predictor::InferEngine, tag: PADDLE_INFER in macro!
E0723 05:00:22.390143 18684 op_repository.cpp:29] Try to create unknown op[GeneralDetectionOp]
E0723 05:00:22.390312 18684 dag.cpp:146] Failed to get_op, op type[GeneralDetectionOp]
E0723 05:00:22.390322 18684 workflow.cpp:29] Failed initialize dag: workflow1
E0723 05:00:22.390332 18684 manager.h:73] Failed init item: workflow1 at:0!
E0723 05:00:22.390341 18684 pdserving.cpp:195] Failed initialize workflow manager, conf:workdir_9998/workflow.prototxt
