### ISSUE TITLE
请问如何能够提升识别速度，目前ocr能够识别但是识别速度感觉较慢，如果针对自己的数据集进行训练能否提升速度

### ISSUE THREAD

**Issue by litianqi18** [PaddlePaddle/PaddleOCR#6425]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
只是换数据finetune，不换字典的话，速度不会变，是否已经开始mkldnn或者tensorrt进行加速呢

**Comment by litianqi18** [comment]
受到收到谢谢您
