### ISSUE TITLE
OSError: (External) CUDA error(2), out of memory.运行代码出现OSError错误

### ISSUE THREAD

**Issue by yinglielalala** [PaddlePaddle/PaddleOCR#6426]
OSError: (External) CUDA error(2), out of memory.
  [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ..\paddle\fluid\platform\stream\cuda_stream.cc:45)
  [operator < gaussian_random > error]

**Comment by MissPenguin** [comment]
安装的什么paddle版本呢，环境信息也提供下吧
