### ISSUE TITLE
如何检测多边形文本，就像图片这种

### ISSUE THREAD

**Issue by songjiahao-wq** [PaddlePaddle/PaddleOCR#6427]
标注的时候是斜四边形，检测出来还是矩形，请问如何更改
![0e672ecf95ceb037cab3d6d9775fec8](https://user-images.githubusercontent.com/75210061/170860776-9f326ceb-2034-4445-991a-fb0dd0f2f2c3.jpg)

**Comment by LDOUBLEV** [comment]
目前PP- OCR的文本检测模型的输出是四边形框，你用的是哪个算法？

**Comment by songjiahao-wq** [comment]
> 目前PP- OCR的文本检测模型的输出是四边形框，你用的是哪个算法？

MobileNetV3，

**Comment by songjiahao-wq** [comment]
> 目前PP- OCR的文本检测模型的输出是四边形框，你用的是哪个算法？

数据集中还有五边形等多边形标注，但检测还是只要矩形，是不是目前只支持四边形训练和四边形的检测？

**Comment by LDOUBLEV** [comment]
> MobileNetV3，

这个是分类算法；

> 是不是目前只支持四边形训练和四边形的检测？

是的
