### ISSUE TITLE
Angle Estimation on English text.

### ISSUE THREAD

**Issue by Omar3esam** [PaddlePaddle/PaddleOCR#6428]
Hello All, Thanks for the effort and time you spend to build up this great project,

I just need to know if there is an angle estimation model for English text, and if so what is the expected output, is it an angle ranged between 0-180 or just the quarter angles 0, 90, 180

**Comment by LDOUBLEV** [comment]
>  just the quarter angles 0, 90, 180

Just the quarter angles 0 and 180;

https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_en/angle_class_en.md

**Comment by Omar3esam** [comment]
Do you see any possibility to retrain it to classify along all the integers between 0-180.

**Comment by LDOUBLEV** [comment]
It is recommended to use the regression method instead of the classification method to do it.
