### ISSUE TITLE
模型训练时碰到了问题

### ISSUE THREAD

**Issue by kenneyLee** [PaddlePaddle/PaddleOCR#643]
按照这个文档（https://gitee.com/paddlepaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md）尝试了模型训练，但是报错了，提示Alloc失败，请问这怎么解决。

<img width="1269" alt="bug1" src="https://user-images.githubusercontent.com/1628572/91730122-1ec65880-ebd8-11ea-973b-825ee6ee6655.png">
<img width="1268" alt="bug2" src="https://user-images.githubusercontent.com/1628572/91729969-e9216f80-ebd7-11ea-878c-c4ae94fb1f86.png">
<img width="1278" alt="bug3" src="https://user-images.githubusercontent.com/1628572/91729986-ef175080-ebd7-11ea-9d75-dddc409297e3.png">

**Comment by yingwei13mei** [comment]
训练之前的GPU显存都清空了么？ 之前任务是否都kill掉了

**Comment by kenneyLee** [comment]
> 训练之前的GPU显存都清空了么？ 之前任务是否都kill掉了

我这台服务器没有GPU（配置文件configs/det/det_r50_vd_db.yml 里边的use_gpu设置false了），之前的任务也都Kill掉了，我使用top看了内存占比，内存占比90%以上了，服务器是双核8G内存的服务器，是不是跑不了训练任务了？

**Comment by MissPenguin** [comment]
把reader yml中的num_workers改成1试试
