### ISSUE TITLE
docker 启动paddle-gpu的容器，GLIBCXX_3.4.22 not find，但是宿主机上明明已经有了啊、？谁知道这是因为什么吗？

### ISSUE THREAD

**Issue by ProsperousSun** [PaddlePaddle/PaddleOCR#6431]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

![image](https://user-images.githubusercontent.com/33046497/170909849-bf14f6cf-2723-4e46-a1f7-21cb8f1f20bf.png)

![image](https://user-images.githubusercontent.com/33046497/170910103-1d943e31-7bd9-42ee-86b1-94101914b579.png)

![image](https://user-images.githubusercontent.com/33046497/170910570-46cc804c-6964-4828-a6ef-68257a0469ab.png)

**Comment by sssimpleboy** [comment]
请问是什么原因呀？
