### ISSUE TITLE
部署ocr咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleOCR#6438]
部署ocr,推荐用hubserving部署还是paddleserving部署？

另外一个paddleserving部署的时候，官方的案例只部署了两个模型，即检测模型和识别模型，是不是还缺少一个方向分类模型？
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README.md

官方有cor微信交流群，在里面咨询问题，基本有回复，群里也挺安静的，同时也加入了paddlenlp和paddleserving相关的微信群，大家交流挺多的，有专门官方的技术人员回答问题，氛围非常好，希望paddleocr也能安排下，把群里的技术氛围带动起来，及时回复下技术问题，感谢。

**Comment by BeyondYourself** [comment]
推荐还是serving部署吧，更加稳定适合服务化部署。方向分类模型应该是有个开关记得，只需要设置一下就行了

**Comment by BeyondYourself** [comment]
坐标信息估计得自己手动改一下，V3我没有试过，V2是得自己该一下就行。把boxes输出就行

**Comment by AI-Mart** [comment]
paddleserving C++部署后和paddlehub对比，同样一张图片，paddlehub识别出来了，paddleserving C++部署的没识别出来，准确率降低了，这一般是什么原因呢？都是用的最新的ppocr3
paddlehub参考 https://www.paddlepaddle.org.cn/hubdetail?name=ch_pp-ocrv3&en_category=TextRecognition
paddleserving C++部署 参考 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/pdserving

**Comment by BeyondYourself** [comment]
准确率降低？检查一下模型配置是否都一致

**Comment by AI-Mart** [comment]
都是官方源代码，没动哦，c++的配置在哪看呢？

**Comment by andyjpaddle** [comment]
> ![image](https://user-images.githubusercontent.com/63343847/171151260-a0d45a56-d5ae-4d29-874e-fee97257da29.png) paddleserving C++部署后预测，发现返回结果只有识别信息，没有坐标信息，就是检测的结果，是什么原因呢？

c++暂不支持输出bbox，可以自己修改源码，后续我们会支持，或者可以先使用python serving部署

**Comment by shandafu** [comment]
> 推荐还是serving部署吧，更加稳定适合服务化部署。方向分类模型应该是有个开关记得，只需要设置一下就行了

请问在哪儿设置？一直没有找到，谢谢

**Comment by Twsaiae** [comment]
> paddleserving C++部署后和paddlehub对比，同样一张图片，paddlehub识别出来了，paddleserving C++部署的没识别出来，准确率降低了，这一般是什么原因呢？都是用的最新的ppocr3 paddlehub参考 https://www.paddlepaddle.org.cn/hubdetail?name=ch_pp-ocrv3&en_category=TextRecognition paddleserving C++部署 参考 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/pdserving

我也是这个问题，同样一样图，在python上推理和在网页端测试结果一致，但是c++部署结果就不行了
