### ISSUE TITLE
关于垂直文字问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#644]
您好，感谢你们团队的付出。我看到你们在合成垂直文本的时候是用的垂类字体，请问垂类字体可以在哪里下载呢？你们在训练通用文字识别模型，字体种类一般选用多少种呢？谢谢解疑。
![image](https://user-images.githubusercontent.com/43515926/91789743-d6438500-ec41-11ea-8781-9110ae7be052.png)

**Comment by tink2123** [comment]
垂类字体就是在百度上搜索获得的，也可以修改text_render的源码，把文字写在图像上时旋转90度。就可以利用横向字体来生成了。
