### ISSUE TITLE
2.5版本代码下的andorid_demo重新编译时候报错

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#6447]
导入原生2.5版本下android_demo，可以正常安装但是在重新编译时报openCV的错，报错位置在CMake.txt下18行 find_package(OpenCV REQUIRED)，具体报错信息如下：

D:\AndroidStudioProject\UI\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at D:\AndroidStudioProject\UI\PaddleOCR-release-2.5\deploy\android_demo\app\src\main\cpp\CMakeLists.txt:18 (find_package):
  Found package configuration file:

    D:/AndroidStudioProject/UI/PaddleOCR-release-2.5/deploy/android_demo/app/src/main/cpp/../../../OpenCV/sdk/native/jni/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

**Comment by tink2123** [comment]
可以试下相关方法：https://blog.csdn.net/ustczhang/article/details/79027655

**Comment by zhang0225** [comment]
> 可以试下相关方法：https://blog.csdn.net/ustczhang/article/details/79027655

已解决，是因为paddlelite 2.10中没有armv8a对应的库

**Comment by yeziyfx** [comment]
> > 可以试下相关方法：https://blog.csdn.net/ustczhang/article/details/79027655
> 
> 已解决，是因为paddlelite 2.10中没有armv8a对应的库

你好，是怎么解决的，能告诉下吗，可有偿。QQ1397054152
