### ISSUE TITLE
OCRlabel能标注 关系抽取 (RE)模型需要的训练数据吗

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleOCR#6448]

**Comment by Evezerest** [comment]
可以使用KIE模式启动，然后标注检测框的类别信息，如key,value等

**Comment by renmada** [comment]
link关系怎么标注呢

**Comment by rainoo** [comment]
标注不了吧？不就是框的位置和框内的值这两项么，边的话没有看见有支持。

**Comment by Evezerest** [comment]
link关系目前无法标注，如果关系不多的话可以考虑利用类别信息，然后做后处理实现，如key1, value1； key2, value2
