### ISSUE TITLE
用ch_PP-OCRv3_det_infer 模型时，use_mkldnn = 1 不能检测，use_mkldnn = 0 时可以检测，这是啥原因？

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#6449]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 7.6
- 版本号/Version：Paddle inference： 2.1 ， PaddleOCR：2.5  cpp_infer  问题相关组件/Related components：
用ch_PP-OCRv3_det_infer 模型时，use_mkldnn = 1 不能检测，use_mkldnn = 0 时可以检测，这是啥原因？
用PP-OCR server 模型时，use_mkldnn =0或1 都可以检测。

**Comment by LjcoderDCC** [comment]
你好，这个问题现在解决了吗
