### ISSUE TITLE
ch_PP-OCRv3_rec_slim_infer 使用lite转换nb后，识别失败

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleOCR#6452]
lite version : v2.11
rec_image_shape = {3.48,320}
识别结果都为空字符串

**Comment by littletomatodonkey** [comment]
你好，

1. 可以先测试下slim inference model的结果是否正确哈
2. 可以测试下我们提供的nb模型结果是否正确

**Comment by ANDROIDTODO** [comment]
@littletomatodonkey 
我使用自带的ch_PP-OCRv3_rec_slim_infer.nb 识别出来的全部是类似
`
`e`-严藍添严藍之严μ穿栋藍严之醇μ藍严衡藍池藍严〖严缸况缸严八醇八严岭严﹑μ穿我藍严弘藍e严藍严)萝藍之添旱之藍μ严e藍扑啤严衡舍缸严添〖况`严穿烫藍舍我挖藍严八醇八严岭严
`
我仅仅替换了识别的模型，所有参数没有更改。
ch_PP-OCRv3_rec_slim_infer所对应的inference model识别出来的是空字符串。

请问这个是什么原因

**Comment by Albert556** [comment]
slim的识别结果是乱码，非slim的v3模型自己转nb后是正常的，但是会吞字，应该是后处理的代码需要修改

**Comment by ANDROIDTODO** [comment]
请问这个要怎么解决呢？
@Albert556

**Comment by Albert556** [comment]
建议先使用v2的模型，等官方更新v3移动端代码，不然的话只能参考服务端代码自己移植了
