### ISSUE TITLE
pdserver pipeline模式 v3版本文字识别准确率问题

### ISSUE THREAD

**Issue by DequanZhu** [PaddlePaddle/PaddleOCR#6453]
pdserver pipeline模式 v3版本文字识别准确率比v2版本下降很多，使用的启动脚本和预测脚本都和V2版本相同，观察了一下很多特殊字符例如-这种都检测不出来，是哪里有配置需要改动吗

**Comment by tink2123** [comment]
收到反馈~ 方便提供一张测试图片吗？ 我们排查下问题

**Comment by DequanZhu** [comment]
> 
这张图片，-15.45,-457.38前面的负号识别不出来
![80C46FFDE1C61A5F07B8254B5DF4437D_IMAGE](https://user-images.githubusercontent.com/26426479/171311483-d67c4816-f72e-4bf1-a26c-ef305e01dc5e.jpg)
