### ISSUE TITLE
单卡训练报错问题

### ISSUE THREAD

**Issue by hjm0613** [PaddlePaddle/PaddleOCR#6457]
大佬，您好。
我训练paddleOCR采用RTX3080i的显卡进行，训练自己的数据集，图片数量大概15000张，训练次数2000次，在训练的过程中会出现无故的中断，没有出现任何的报错信息，请问这可能是什么原因造成的呢？希望能得到您的解答，谢谢。

**Comment by WenmuZhou** [comment]
在train.py里有一个函数 你看看
