### ISSUE TITLE
infer_vqa_token_ser.py预测时怎么利用标签中"text""bbox"信息

### ISSUE THREAD

**Issue by yanziwu621** [PaddlePaddle/PaddleOCR#6458]
如题，现在预测时文本框位置和识别结果没用到标签数据，直接是用自带模型检出识别的。

**Comment by yanziwu621** [comment]
1、在测试自己的数据时，能不能加载自己训练的ocr模型，因为用代码里加载的ocr模型得到的bbox和text不准确？

**Comment by WenmuZhou** [comment]
1. 可以
2. 是的

**Comment by yysirs** [comment]
> 1、在测试自己的数据时，能不能加载自己训练的ocr模型，因为用代码里加载的ocr模型得到的bbox和text不准确？ 2、训练的时候是用标注的box和text?

请问你知道这么标注SER和ER的box和text，有什么工具可以做到嘛？
