### ISSUE TITLE
Why is actual text required for text detection? I have a dataset which was collected to be trained on YOLOv5 for a single class, can it be used for text detection?

### ISSUE THREAD

**Issue by umairjavaid** [PaddlePaddle/PaddleOCR#6461]

**Comment by umairjavaid** [comment]
No. can I give any random text?

**Comment by umairjavaid** [comment]
I mean bounding box coordinates of the labeled text but the text itself is not present in the labels. How do I train on this dataset?

**Comment by WenmuZhou** [comment]
You can use any text except ['*', '###'] to represent text in image
