### ISSUE TITLE
安卓识别速度

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#6464]
最近官方更新了安卓的模型和代码，于是测试了一下最新的模型。原模型使用的是ch_ppocr_moble，目前已经使用了ch_PPOCRV2，识别精度确实提高,但是识别的速度还是下降比较严重的。在测试中，同样一张图片，原模型识别速度为300ms，现模型的识别速度达到了700ms，测试图片中大约8个目标，每个目标长度约为50。使用参数如下
   public int useOpencl = 0;
    public int cpuThreadNum = 12;
    public String cpuPowerMode = "LITE_POWER_HIGH";
    protected int detLongSize = 640;
请问这个情况在正常吗，如果不正常的话应该怎么调整以提升速度呢

**Comment by WenmuZhou** [comment]
两次测试时，除了模型，其他参数一致吗，理论来说，速度应该更快或者持平的

**Comment by zhang0225** [comment]
> 两次测试时，除了模型，其他参数一致吗，理论来说，速度应该更快或者持平的

除了模型外，检测的所有参数都一致，识别的resize mobile使用的是32x320 v2使用的是48*640 其余参数没什么变化
这个会是导致速度变慢的原因么，如果是的话我重新训练一个32*320的

**Comment by WenmuZhou** [comment]
你识别模型，
v2: 48*640
原模型：32*320

是这样吗，这样肯定会慢的，你弄一个v2 32*320的看看

**Comment by zhang0225** [comment]
> 你识别模型， v2: 48_640 原模型：32_320
> 
> 是这样吗，这样肯定会慢的，你弄一个v2 32*320的看看

是这样的，大概知道问题在哪里了，感谢指导
