### ISSUE TITLE
android demo测试出现长检测框，出现文字丢失的情况

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleOCR#6468]
3M的那个rec.nb模型会出现，8M的nb模型结果是正常的
测试图：
![8B`}SF)P5}4`H7{832SD~GE](https://user-images.githubusercontent.com/15188456/171407181-2429928c-4bef-4d5b-a6c3-a428dfd0167f.jpg)

![2C41977B8B8C6AD88109845A3CFF21A7](https://user-images.githubusercontent.com/15188456/171407135-83b601c5-6d0f-408d-baa0-0c4ca7a0b6a7.jpg)

**Comment by yangy996** [comment]
没有人遇到这种情况吗？

**Comment by Albert556** [comment]
slim模型好像是有长度限制的，不能检测太长的

**Comment by yangy996** [comment]
> slim模型好像是有长度限制的，不能检测太长的

大佬，有相关说明吗？我去看看

**Comment by yangy996** [comment]
@WenmuZhou @LDOUBLEV  大佬们，能帮看看是什么原因吗？
