### ISSUE TITLE
en_PP-OCRv3识别结果乱码的问题

### ISSUE THREAD

**Issue by lf616** [PaddlePaddle/PaddleOCR#6469]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10  c++部署
- 版本号/Version：paddle_inference-v2.2.2,  PaddleOCR-v2.5 
使用en_PP-OCRv3纯英文模型时，识别结果乱码。
例如：数字2识别成十六进制：e7bb9a（显示则是：“绚”，”绚“的UTF-8编码为e7bb9a）

**Comment by WenmuZhou** [comment]
换字典了吗

**Comment by huanhuan-xiao** [comment]
你好，请问你解决了吗。我也遇到同样的问题

**Comment by huanhuan-xiao** [comment]
我用的是rec_icdar15_train 使用直接训练的模型识别是正确的，但是转换为推理模型后和你的识别效果就是一样的。
![图片](https://user-images.githubusercontent.com/82137867/171590626-355e1645-6ad0-49fb-8697-ca0eabfa7885.png)
![图片](https://user-images.githubusercontent.com/82137867/171590764-c198ff2f-d69d-4f03-981f-a853fb570c26.png)

**Comment by lf616** [comment]
解决了，就是换字典就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月2日(周四) 下午4:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] en_PP-OCRv3识别结果乱码的问题 (Issue #6469)




 
我用的是rec_icdar15_train 使用直接训练的模型识别是正确的，但是转换为推理模型后和你的识别效果就是一样的。

**Comment by lf616** [comment]
感谢前辈，是我没换字典，搞了几个小时没搞出来，前辈一句话点破，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月1日(周三) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] en_PP-OCRv3识别结果乱码的问题 (Issue #6469)




 
换字典了吗

**Comment by C4712** [comment]
需要换字体文件吗？我换了字典还是不行

**Comment by fyclver** [comment]
您好，这个换dict可以说仔细点吗？刚开始学习这个模型。

**Comment by maikouSart** [comment]
它的参数里有一个是这个字段
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43963015/ab13a329-1fef-4f80-8795-144e669959a3)
我换成了
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/43963015/90a4430c-d44a-49bd-8d2e-2d4c527e0110)
就好了
