### ISSUE TITLE
mv3+db模型export为固化模型后效果不一致

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#647]
我在训练mv3+db模型之后，使用infer_det.py预测得到一个较好结果。我打算将在端侧部署，使用export_model.py将其转化为infer模型，但在使用predict_det.py后发现效果不如之前，差了许多。配置基本都没有变，语句也都是按照说明输入的，请问是什么原因导致的呢？还有，db在infer时通过设置后处理参数根据具体情况进行调整，那么在export时为什么不用输入这些参数呢？谢谢

**Comment by MissPenguin** [comment]
应该是因为默认参数不一致导致的，需要对齐一下，包括resize尺寸和几个后处理参数，predict_det的默认参数在tools/infer/utility.py中，也可以从命令行传入特定参数进行修改

**Comment by tyy2tyy** [comment]
好的，多谢，问题已经解决了

**Comment by tyy2tyy** [comment]
还有一个问题，将infer模型转化为nb形式之后部署至安卓端，为什么在安卓端运行的效果又和infer的效果不一致？

**Comment by littletomatodonkey** [comment]
> 还有一个问题，将infer模型转化为nb形式之后部署至安卓端，为什么在安卓端运行的效果又和infer的效果不一致？

可以试下最新代码，目前应该都是一致的
