### ISSUE TITLE
Blogpost about PaddleOCR

### ISSUE THREAD

**Issue by manangoel99** [PaddlePaddle/PaddleOCR#6470]
Hello! I've written a blogpost highlighting the new W&B integration in PaddleOCR. The chinese and english versions are available [here](https://wandb.ai/manan-goel/text_detection/reports/Train-and-Debug-Your-OCR-Models-with-PaddleOCR-and-W-B--VmlldzoyMDUwMDIw) and [here](https://wandb.ai/wandb_fc/chinese/reports/W-B-OCR---VmlldzoyMDk1NzE4)

I would love to get some feedback !

![Screenshot 2022-06-01 at 8 46 30 PM](https://user-images.githubusercontent.com/32260633/171439367-ba794d7b-8e5c-4a62-9be9-d38c5876f346.png)
![Screenshot 2022-06-01 at 8 46 55 PM](https://user-images.githubusercontent.com/32260633/171439443-c560a7b1-ff68-4aa3-b7b7-85cce584f686.png)

**Comment by WenmuZhou** [comment]
LGTM
