### ISSUE TITLE
关于显存占用的问题

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#6473]
![image](https://user-images.githubusercontent.com/28819717/171535365-47993791-c5c1-46e6-9500-33f285b8afad.png)

您好，请问基于这样的机制，图片尺寸过大时，显存会一直上涨，有什么好的办法去限制吗 ？

**Comment by mingo-doer** [comment]
如果det_limit_side_len降低，识别效果会有所下降

**Comment by littletomatodonkey** [comment]
你好，显存图片如果固定的话，应该不会持续上涨的，另外就是如果图片很大，可以试着切图之后分开检测

**Comment by mingo-doer** [comment]
你好，部署ocr服务，用户预测的图片肯定不会是固定的
图片的大小不大，图片的长较大的时候，切图再检测可能很可能会造成切到字  没办法把结果进行拼接的一个情况。
resize原图又会造成精度下降。
还能有什么比较好的方法吗

> 你好，显存图片如果固定的话，应该不会持续上涨的，另外就是如果图片很大，可以试着切图之后分开检测

**Comment by Gmgge** [comment]
有尝试更换推理框架试过嘛？例如onnxruntime？

**Comment by mingo-doer** [comment]
> 有尝试更换推理框架试过嘛？例如onnxruntime？

没有，请问你试过吗？效果有变好一些吗？

**Comment by yangy996** [comment]
图太大了，就处理下图片，进行缩放，resize到1080或者960等大小，再传入，否则图很大显存就爆炸了
