### ISSUE TITLE
有关rec_img_h：识别模型输入图像高度，rec_img_w：识别模型输入图像宽度

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#6476]
paddleocr2.5 新增了这两个参数， 默认rec_img_h=48，rec_img_w=320，这两个参数在什么场景下需要调整，调整的原理是什么样的，谢谢！

**Comment by littletomatodonkey** [comment]
你好，rec_img_h是ppocrv3模型的推理高度，因为我们之前提供的模型都是32的，所以这里新增了一个参数，rec_img_w表示如果图片宽度小于320，会padding到320的宽度
