### ISSUE TITLE
不能编译 android armeabi-v7a cpu架构动态库

### ISSUE THREAD

**Issue by beijinggao** [PaddlePaddle/PaddleOCR#6484]
使用的 android demo 最新版代码，PaddleLite 版本2.10，

想同时编译 armeabi-v7a  和 arm64-v8a 两种cpu 架构的动态库，arm64-v8a能正常编译，armeabi-v7a 编译不出来是为什么呢？
![image](https://user-images.githubusercontent.com/7404433/171675822-226f2b4f-fd6d-4f68-b910-5d79d05602f3.png)

build 结束后只有arm64-v8a 库
![image](https://user-images.githubusercontent.com/7404433/171676166-fdee1861-bfb4-4dbb-959b-595e0848bd62.png)

在PaddleLite中加入了预编译的 armeabi-v7a 动态库后还是同样的问题
![image](https://user-images.githubusercontent.com/7404433/171676384-9846d687-cc86-4d73-b585-9e8d451f0cd7.png)

**Comment by WenmuZhou** [comment]
v7里面加的东西要和v8里一样，并且，v8现在兼容v7了，哪些场景还需要v7呢

**Comment by beijinggao** [comment]
> v7里面加的东西要和v8里一样，并且，v8现在兼容v7了，哪些场景还需要v7呢

老款的手机cpu 是v7的，v8也能直接兼容在上面运行吗？我之前试了一下没成功，我在试试

**Comment by WenmuZhou** [comment]
有结论吗
