### ISSUE TITLE
SAR pre-trained model too many values to unpack

### ISSUE THREAD

**Issue by scry-yewenzhou** [PaddlePaddle/PaddleOCR#6486]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 运行指令/Command Code：
1. follow the tutorial on this link: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/algorithm_rec_sar_en.md
2. run the command 
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/word_1.png" --rec_model_dir="./inference/rec_sar/" --rec_image_shape="3, 48, 48, 160" --rec_char_type="ch" --rec_algorithm="SAR" --rec_char_dict_path="ppocr/utils/dict90.txt" --max_text_length=30 --use_space_char=False

It would give you an error.

- 完整报错/Complete Error Message：

[2022/06/03 23:31:25] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
shape: [3, 48, 48, 160]
[2022/06/03 23:31:25] ppocr INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 442, in main
    rec_res, _ = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 270, in __call__
    imgC, imgH, imgW = self.rec_image_shape
ValueError: too many values to unpack (expected 3)

Seems like the code doesn't handle the special case of SAR model well. It would still proceed to handle 3 parameters by default, instead of 4 in the case of SAR.

**Comment by LDOUBLEV** [comment]
> [2022/06/03 23:31:25] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

Please check your input params --rec_image_shape.

The expect input of  is --rec_image_shape  '3, 48, 320'  or '3,32,320'  but received rec_image_shape="3, 48, 48, 160"

**Comment by xinfanmeng** [comment]
请问这个问题解决了吗？我也遇到同样问题

**Comment by andyjpaddle** [comment]
please update the latest code, we have fixed this bug
