### ISSUE TITLE
使用繁體中文_cht_dict.txt時  輸出含英數及標點符號部分都是錯的

### ISSUE THREAD

**Issue by tuteming** [PaddlePaddle/PaddleOCR#6487]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：wi10 c++
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.5 version
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

-----使用繁體中文_cht_dict.txt時  輸出含英數及標點符號部分都是錯的

**Comment by tuteming** [comment]
![note](https://user-images.githubusercontent.com/12892187/171981011-e65991cd-a621-4819-808e-a62fef3ad34b.jpg)

![note_err](https://user-images.githubusercontent.com/12892187/171980877-d8a0ace4-c237-4a0f-b6e7-cbc5d5c141f3.jpg)

**Comment by tuteming** [comment]
而且為什麼識別的"列順序"是反的

**Comment by tink2123** [comment]
1. 训练数据中标点符号较少导致识别效果不好，有需求的话可以自己加入一些表达数据finetune下。
2. 识别顺序和检测框的坐标有关，可以自己参考python在cpp里添加一个排序函数：

python：
https://github.com/PaddlePaddle/PaddleOCR/blob/ab59246203d27e955ecd65a7681b624dc5d7a72a/tools/infer/predict_system.py#L104

cpp：
https://github.com/PaddlePaddle/PaddleOCR/blob/fb69a4049edaada9d36a61378f29133b8879c829/deploy/cpp_infer/src/paddleocr.cpp#L120

**Comment by tuteming** [comment]
如果你要呼嚨 應該把問題癥結檢視清楚  你的答案我不認同
