### ISSUE TITLE
paddle-serving pipeline模式，启动后为什么会创建多个进程

### ISSUE THREAD

**Issue by DequanZhu** [PaddlePaddle/PaddleOCR#6489]
如下图所示，python3启动 web_service.py（请忽略paddle_serving_ocr.application.app这个名字，这里是把web_service.py进行了包装，可以把它等同于seb_service.py）脚本后，使用top命令可以看到启动了10个进程，请问这其中的原理是什么，进程的数目和什么有关系呢，config.yml文件中，det和rec op的concurrency设置为2:4，貌似和10这个数目没多大关系，另外看cpu时间只有7个进程在工作，其它三个没有在工作，这个又是为什么呢。
![Snipaste_2022-06-05_15-49-05](https://user-images.githubusercontent.com/26426479/172040950-61f92b1d-6463-460e-b3fb-04abd909d8f8.jpg)

**Comment by BeyondYourself** [comment]
2:4 目前截图只能看到是只有6个在工作，其他进程都是在空闲中

**Comment by DequanZhu** [comment]
> 
开启的进程数目是怎么确定的呢，和config.yml文件中det,rec的concurrency以及worker_num的大小的关系是怎么样的呢

**Comment by fenglin998** [comment]
我也遇到这个问题，我在config.yml中work-num设置为10，build_dag_each_worker设为True，det和rec设为8：4，结果一看状态，只有一个在跑，其他都是空想状态，请问你解决这个问题了吗

**Comment by TeslaZhao** [comment]
进程模式下，op是独立进程，包括requestOp和responseOp，grpc-gateway是独立进程、以及1个主进程负责DAG创建和GRPC处理，profile也会开进程（开启profile）
