### ISSUE TITLE
C++中使用Tensorrt推理报错

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#6492]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CUDA：10.2   CUDNN：8.1.1    Tensorrt：7.2.3.4
- 版本号/Version：  PaddleOCR： release-2.4
- 下载的paddle_inference：
        GIT COMMIT ID: a5cf2e305b744e3ebd2f2210341f88d349d4ec5e
        WITH_MKL: ON
        WITH_MKLDNN: ON
        WITH_GPU: ON
        WITH_ROCM: OFF
        CUDA version: 10.2
        CUDNN version: v8.1
        CXX compiler version: 5.4.0
        WITH_TENSORRT: ON
        TensorRT version: v7.2.3.4

- 运行指令/Command Code：./build/ppocr det --det_model_dir=/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/inference/test --image_dir=/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/dataset_xp/val/515.jpg

- 完整报错/Complete Error Message：
mode: det
total images num: 1
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0606 10:53:16.982020  9975 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0606 10:53:17.043327  9975 fuse_pass_base.cc:57] ---  detected 24 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0606 10:53:17.058054  9975 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 12 nodes
I0606 10:53:17.060565  9975 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0606 10:53:17.367051  9975 op_converter.h:211] trt input [conv2d_59.tmp_0] dynamic shape info not set, please check and retry.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

已放弃 (核心已转储)

-问题： C++使用CPU和GPU均可以正常进行编译预测，但是一将tensorrt打开设置成true，可以编译但是运行就会报错，这个貌似是什么动态输入的问题。

**Comment by TianJian11** [comment]
编译文件： /tools/build.sh
OPENCV_DIR=/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/deploy/cpp_infer/opencv-3.4.7/opencv3
LIB_DIR=/home/alex/Downloads/paddle_inference
CUDA_LIB_DIR=/usr/local/cuda-10.2/lib64
CUDNN_LIB_DIR=/usr/local/cuda-10.2/lib64
TENSORRT_DIR=/opt/TensorRT-7.2.3.4

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DWITH_TENSORRT=ON \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \
    -DTENSORRT_DIR=${TENSORRT_DIR} \
    

make -j

**Comment by pbabading** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：CUDA：10.2   CUDNN：8.1.1    Tensorrt：7.2.3.4
> * 版本号/Version：  PaddleOCR： release-2.4
> * 下载的paddle_inference：
>   GIT COMMIT ID: a5cf2e305b744e3ebd2f2210341f88d349d4ec5e
>   WITH_MKL: ON
>   WITH_MKLDNN: ON
>   WITH_GPU: ON
>   WITH_ROCM: OFF
>   CUDA version: 10.2
>   CUDNN version: v8.1
>   CXX compiler version: 5.4.0
>   WITH_TENSORRT: ON
>   TensorRT version: v7.2.3.4
> * 运行指令/Command Code：./build/ppocr det --det_model_dir=/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/inference/test --image_dir=/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/dataset_xp/val/515.jpg
> * 完整报错/Complete Error Message：
>   mode: det
>   total images num: 1
>   WARNING: Logging before InitGoogleLogging() is written to STDERR
>   I0606 10:53:16.982020  9975 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
>   --- Running analysis [ir_graph_build_pass]
>   --- Running analysis [ir_graph_clean_pass]
>   --- Running analysis [ir_analysis_pass]
>   --- Running IR pass [conv_affine_channel_fuse_pass]
>   --- Running IR pass [adaptive_pool2d_convert_global_pass]
>   --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
>   --- Running IR pass [shuffle_channel_detect_pass]
>   --- Running IR pass [quant_conv2d_dequant_fuse_pass]
>   --- Running IR pass [delete_quant_dequant_op_pass]
>   --- Running IR pass [delete_quant_dequant_filter_op_pass]
>   --- Running IR pass [simplify_with_basic_ops_pass]
>   --- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
>   --- Running IR pass [multihead_matmul_fuse_pass_v2]
>   --- Running IR pass [multihead_matmul_fuse_pass_v3]
>   --- Running IR pass [skip_layernorm_fuse_pass]
>   --- Running IR pass [conv_bn_fuse_pass]
>   I0606 10:53:17.043327  9975 fuse_pass_base.cc:57] ---  detected 24 subgraphs
>   --- Running IR pass [unsqueeze2_eltwise_fuse_pass]
>   --- Running IR pass [squeeze2_matmul_fuse_pass]
>   --- Running IR pass [reshape2_matmul_fuse_pass]
>   --- Running IR pass [flatten2_matmul_fuse_pass]
>   --- Running IR pass [map_matmul_v2_to_mul_pass]
>   --- Running IR pass [map_matmul_v2_to_matmul_pass]
>   --- Running IR pass [map_matmul_to_mul_pass]
>   --- Running IR pass [fc_fuse_pass]
>   --- Running IR pass [conv_elementwise_add_fuse_pass]
>   --- Running IR pass [tensorrt_subgraph_pass]
>   I0606 10:53:17.058054  9975 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 12 nodes
>   I0606 10:53:17.060565  9975 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
>   I0606 10:53:17.367051  9975 op_converter.h:211] trt input [conv2d_59.tmp_0] dynamic shape info not set, please check and retry.
>   terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
>   what():
> 
> ## C++ Traceback (most recent call last):
> 0 paddle_infer::CreatePredictor(paddle::AnalysisConfig const&) 1 paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&) 2 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&) 3 paddle::AnalysisPredictor::Init(std::shared_ptrpaddle::framework::Scope const&, std::shared_ptrpaddle::framework::ProgramDesc const&) 4 paddle::AnalysisPredictor::PrepareProgram(std::shared_ptrpaddle::framework::ProgramDesc const&) 5 paddle::AnalysisPredictor::OptimizeInferenceProgram() 6 paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*) 7 paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*) 8 paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_deletepaddle::framework::ir::Graph >) 9 paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const 10 paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const 11 paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >_) const 12 paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc_, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*) 13 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int) 14 paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)
> 
> ## Error Message Summary:
> InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details. [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)
> 
> 已放弃 (核心已转储)
> 
> -问题： C++使用CPU和GPU均可以正常进行编译预测，但是一将tensorrt打开设置成true，可以编译但是运行就会报错，这个貌似是什么动态输入的问题。

请问下最后解决了嘛
