### ISSUE TITLE
Issue in Reading English Alphabet Letters

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [PaddlePaddle/PaddleOCR#6495]
Hi Guys , Thank you very much for such a nice work . I am testing the paddle OCR on my documents . The paddle OCR works fine in most of the cases but in some cases where actual word on photo is "quinton de kock" but paddle OCR read it "guinton de kock" . Should I resized my input image to any resolution or dimension to get better results ? Can you help me how I can improve these cases . Thank you

**Comment by tink2123** [comment]
This problem may be similar to yours, please refer to the solution：
#6538
