### ISSUE TITLE
加载了预训练模型后，用自己的标注数据（1000张）训练db检测模型，出现精度下降情况（就是训练后的精度会低于直接用预训练模型推理的精度），这是什么原因呢？

### ISSUE THREAD

**Issue by weihongwei-zg** [PaddlePaddle/PaddleOCR#6496]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by ZzyChris97** [comment]
我也有同样的问题，是因为自己的标注方式不对吗？想问下你最后是怎么解决的
