### ISSUE TITLE
readme.md文档有错误

### ISSUE THREAD

**Issue by H4Njx** [PaddlePaddle/PaddleOCR#6497]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/paddle2onnx/readme.md?plain=1 line 79

--save_file ./inferencecls_onnx/model.onnx \ 应改为 --save_file ./inference/cls_onnx/model.onnx \

**Comment by TianJian11** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/paddle2onnx/readme.md?plain=1 line 79
> 
> --save_file ./inferencecls_onnx/model.onnx \ 应改为 --save_file ./inference/cls_onnx/model.onnx \

这个就是个保存onnx模型路径的问题，修改该路径都ok
