### ISSUE TITLE
db模型检测效果有的不够好

### ISSUE THREAD

**Issue by infinite013** [PaddlePaddle/PaddleOCR#650]
训练的时候使用的是这个模型det_r50_vd_db.yml
请问有什么可以改进的地方吗
![QQ图片20200901161714](https://user-images.githubusercontent.com/37789662/91825293-a3fc4c80-ec6e-11ea-8eb5-9e54a08db3c9.png)

**Comment by MissPenguin** [comment]
DB在检测这种倾斜文本行有时是容易出现这种现象，不过你这个效果看着其实还可以，如果觉得1被切掉了一部分，可以把文本框扩大一点。

**Comment by infinite013** [comment]
> DB在检测这种倾斜文本行有时是容易出现这种现象，不过你这个效果看着其实还可以，如果觉得1被切掉了一部分，可以把文本框扩大一点。

谢谢您的回复。
我想问问您如果之后我需要识别，那我识别模型的训练是否可以用检测得到的结果作为训练集。
我之前尝试使用这样的训练集进行训练，但是效果不如我只用标准的训练集的效果好。

**Comment by MissPenguin** [comment]
> > DB在检测这种倾斜文本行有时是容易出现这种现象，不过你这个效果看着其实还可以，如果觉得1被切掉了一部分，可以把文本框扩大一点。
> 
> 谢谢您的回复。
> 我想问问您如果之后我需要识别，那我识别模型的训练是否可以用检测得到的结果作为训练集。
> 我之前尝试使用这样的训练集进行训练，但是效果不如我只用标准的训练集的效果好。

可以的，可以用这种方式补充真实数据，但识别模型的训练一般对数据量要求较大，所以往往大批量合成数据，更方便一些，要注意数据量是否充足。
