### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'  ​

### ISSUE THREAD

**Issue by ingaluxemburg** [PaddlePaddle/PaddleOCR#6500]
Hello! I'm trying to launch this code:

import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res
table_engine = PPStructure(show_log=True)

and get an error:
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'  ​

How to solve it?

**Comment by ingaluxemburg** [comment]
And I will be very happy if someone gives me an actual list of libs and their versions, to run code below or this code:

from paddleocr import PaddleOCR,draw_ocr
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
img_path = './test.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)


# draw result
from PIL import Image
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

which gives the same error. This code I took here https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/quickstart_en.md

**Comment by WenmuZhou** [comment]
Check if paddle is installed correctly

**Comment by VirtualAnalytics** [comment]
> Check if paddle is installed correctly

Hi @WenmuZhou , I tried installing paddle 3 to 4 times but I get this same error again and again, I am using Google Colab.
