### ISSUE TITLE
请教关于pdServing接口的请求参数和返回结果

### ISSUE THREAD

**Issue by deathnopool** [PaddlePaddle/PaddleOCR#6504]
1. 我看目前是图片都是转成base64的方式扔给服务, 能不能直接文件流?
2. 返回结果虽然是JSON, 但是value是包含tuple的字符串, 其他语言使用不是很方便, 能否自定义数据结构?

**Comment by WenmuZhou** [comment]
1. 直接文件流，不方便传输
2. 可以自定义
