### ISSUE TITLE
表格数据构造

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6506]
构造自己的表格数据时。cells中每个dict的tokens是必须要的吗。如果只存在bbox可以吗

**Comment by WenmuZhou** [comment]
不是必须的，建议使用特定字符代替，如 1111

**Comment by zhentaoCoding** [comment]
> 不是必须的，建议使用特定字符代替，如 1111

中文场景下，训练了自己的版面分析模型，表格识别直接用开源的英文表格识别模型，和使用自己的训练的中文表格识别模型区别大吗

**Comment by WenmuZhou** [comment]
自己训练的准确率会高一点
