### ISSUE TITLE
请问PPOCRV3的模型支持基于sevring的服务端部署吗？之前部署过ch_ppocr_server_v2.0_det和ch_ppocr_server_v2.0_rec模型

### ISSUE THREAD

**Issue by lvjianjin004** [PaddlePaddle/PaddleOCR#6507]
![image](https://user-images.githubusercontent.com/91236933/172308393-c4d28fd5-2bf8-473a-8b5e-7f9458dc665e.png)
![image](https://user-images.githubusercontent.com/91236933/172308531-3e7fd34b-f9f0-4d2a-9967-7ad08ed6b07d.png)

**Comment by lvjianjin004** [comment]
是直接替换模型即可还是有其他的改动还是说目前暂不支持呢？

**Comment by WenmuZhou** [comment]
支持的，直接替换模型就行
