### ISSUE TITLE
any Paddle Similar functions like this => torch.cuda.empty_cache() to clear GPU memory

### ISSUE THREAD

**Issue by encoding-muzzu** [PaddlePaddle/PaddleOCR#651]
GPU Memory is not releasing after every request

FYI: loaded PaddleOCR Model in flask session

i want to release or clear GPU memory after every request?, please help

**Comment by littletomatodonkey** [comment]
Sorry there is not any apis to fulfill your requirement,  Manually refresh the gpu memory may be a better choice.
