### ISSUE TITLE
paddleOCR中检测模型在训练时 的配置文件相关参数设置的问题

### ISSUE THREAD

**Issue by Heavenbest** [PaddlePaddle/PaddleOCR#6516]
在det_mv3_db.yml文件中

      - DetResizeForTest:
          image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
其中的order：hwc，意思是输入数据的通道格式满足nhwc吗？输入数据格式能否改成nchw格式的，如果可以具体应该如何修改配置文件？?

**Comment by littletomatodonkey** [comment]
这个表示输入的数据格式是hwc还是chw，会去做normalize的操作，输入格式在下面的`ToCHWImage `操作中被修改为chw了，你可以打印shape看下
