### ISSUE TITLE
表格识别训练数据

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6519]
表格识别训练数据的json格式是什么样的？里面哪些字段是必要的，哪些不是必要的？文档中有点乱，没看懂

**Comment by littletomatodonkey** [comment]
你好，可以说下哪里没太描述清楚之类的

**Comment by ZTurboX** [comment]
> 你好，可以说下哪里没太描述清楚之类的
没有说明训练数据里有哪些字段，哪些是必要字段

**Comment by WenmuZhou** [comment]
文字框的box是必要的，text可以是任意字符
表格的结构信息是必要的
