### ISSUE TITLE
iOS Demo更新模型

### ISSUE THREAD

**Issue by Nycojie** [PaddlePaddle/PaddleOCR#6523]
在demo中我加入了V3的DB模型(ch_PP-OCRv3_det_slim_infer.nb)，测试没问题，然后我又下载了V3的识别模型(ch_PP-OCRv3_rec_slim_infer.nb)，运行崩溃,崩溃位置在RecPredictor::Predict 方法中  predictor_->Run()位置。

signal SIGABRT.

我在Readme文件中有看到说：

- 如果更新模型中的输入 Tensor、Shape、和 Dtype 发生更新:

  - 更新文字方向分类器模型，则需要更新  `ppocr_demo/cls_process.cc` 中 `ClsPredictor::Preprocss` 函数
  - 更新检测模型，则需要更新  `ppocr_demo/det_process.cc` 中 `DetPredictor::Preprocss` 函数
  - 更新识别器模型，则需要更新 `ppocr_demo/rec_process.cc` 中 `RecPredictor::Preprocss` 函数
  
- 如果更新模型中的输出 Tensor 和 Dtype 发生更新:

  - 更新文字方向分类器模型，则需要更新  `ppocr_demo/cls_process.cc` 中 `ClsPredictor::Postprocss` 函数
  - 更新检测模型，则需要更新  `ppocr_demo/det_process.cc` 中 `DetPredictor::Postprocss` 函数
  - 更新识别器模型，则需要更新  `ppocr_demorec_process.cc` 中 `RecPredictor::Postprocss` 函数

- 如果需要更新  `ppocr_keys_v1.txt` 标签文件，则需要将新的标签文件存放在目录 `./assets/labels/` 

我没明白此函数需要更新啥？另外，我如何查看得知模型中的Tensor、Shape、Dtype发生更新.

**Comment by littletomatodonkey** [comment]
你好，可以看下单独的识别模型运行是否有问题，目前v3和v2以及之前的模型的输入输出都是一样的，只是v3识别模型的shape需要设置为3x48x320(之前是3x32x320)

**Comment by yinqinggong** [comment]
> 单独的识别模型运行是否有问题，目前v3和v2以及之前的模型的输入输出都是一样

你好，我也遇到同样的predictor_->Run()位置崩溃，修改rec_image_shape{3, 48, 320}后也是如此，怎么解决呢
