### ISSUE TITLE
pyinstaller 打包生成exe文件，windows 系统下执行报系统段错误

### ISSUE THREAD

**Issue by wenxuezhang** [PaddlePaddle/PaddleOCR#6524]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境：windows10
- 版本号/Version：Paddle：2.3.0  PaddleOCR： 2.5：
- 运行指令/Command Code：dos环境，可执行程序目录，执行 main.exe
- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/77103481/172588956-8e84e876-5191-4ce2-859f-6aded0c1cf81.png)

**Comment by littletomatodonkey** [comment]
你好，可以查看下往期issue，看下有没有类似的

**Comment by WENDGOUNDI** [comment]
Hello @wenxuezhang. Were you able to compile paddleocr with pyinstaller?

**Comment by wenxuezhang** [comment]
我已经解决了这个问题。谢谢！



张文学  pi  认知智能实验室 
Mobile:+86-18210275525
E-mail: ***@***.***
PERCENT.CN - Decision Intelligence
北京市海淀区建材城中路27号金隅智造工场S5栋西侧 100096

 
 
发件人： WENDGOUNDI ABDOUL RASMANE SAVADOGO
发送时间： 2022-07-13 16:43
收件人： PaddlePaddle/PaddleOCR
抄送： wenxuezhang; Mention
主题： Re: [PaddlePaddle/PaddleOCR] pyinstaller 打包生成exe文件，windows 系统下执行报系统段错误 (Issue #6524)
Hello @wenxuezhang. Were you able to compile paddleocr with pyinstaller?

**Comment by WENDGOUNDI** [comment]
@wenxuezhang can you explain how you proceeded? Thank you.

**Comment by wenxuezhang** [comment]
将 ~Python37\Lib\site-packages\paddle\libs 拷贝到打包后的 dist\main\paddle\下面
