### ISSUE TITLE
bash: hub: command not found

### ISSUE THREAD

**Issue by VViiepan** [PaddlePaddle/PaddleOCR#6527]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos7
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：hub install deploy/hubserving/ocr_det/
- 完整报错/Complete Error Message：bash: hub: command not found
我已经执行了pip install paddlehub==1.8.3 --upgrade -i https://mirror.baidu.com/pypi/simple命令
但还是在执行hub install deploy/hubserving/ocr_det/ 时报错：bash: hub: command not found

信息：
[root@dev-bigdata-01 bin]# pip install paddlehub==1.8.3 --upgrade -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
Requirement already satisfied: paddlehub==1.8.3 in ./python3/lib/python3.7/site-packages (1.8.3)
Requirement already satisfied: flake8 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (4.0.1)
Requirement already satisfied: yapf==0.26.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (0.26.0)
Requirement already satisfied: cma>=2.7.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (3.2.2)
Requirement already satisfied: colorlog in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (6.6.0)
Requirement already satisfied: six>=1.10.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (1.16.0)
Requirement already satisfied: protobuf>=3.6.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (3.20.0)
Requirement already satisfied: opencv-python in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (3.4.17.61)
Requirement already satisfied: pre-commit in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (2.19.0)
Requirement already satisfied: flask>=1.1.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (1.1.4)
Requirement already satisfied: gunicorn>=19.10.0 in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (20.1.0)
Requirement already satisfied: pandas in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (1.1.5)
Requirement already satisfied: visualdl in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (2.2.3)
Requirement already satisfied: nltk in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (3.7)
Requirement already satisfied: tqdm in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (4.64.0)
Requirement already satisfied: sentencepiece in ./python3/lib/python3.7/site-packages (from paddlehub==1.8.3) (0.1.91)
Requirement already satisfied: numpy in ./python3/lib/python3.7/site-packages (from cma>=2.7.0->paddlehub==1.8.3) (1.21.6)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in ./python3/lib/python3.7/site-packages (from flask>=1.1.0->paddlehub==1.8.3) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in ./python3/lib/python3.7/site-packages (from flask>=1.1.0->paddlehub==1.8.3) (1.1.0)
Requirement already satisfied: click<8.0,>=5.1 in ./python3/lib/python3.7/site-packages (from flask>=1.1.0->paddlehub==1.8.3) (7.1.2)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in ./python3/lib/python3.7/site-packages (from flask>=1.1.0->paddlehub==1.8.3) (1.0.1)
Requirement already satisfied: setuptools>=3.0 in ./python3/lib/python3.7/site-packages (from gunicorn>=19.10.0->paddlehub==1.8.3) (39.0.1)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in ./python3/lib/python3.7/site-packages (from flake8->paddlehub==1.8.3) (2.4.0)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in ./python3/lib/python3.7/site-packages (from flake8->paddlehub==1.8.3) (2.8.0)
Requirement already satisfied: importlib-metadata<4.3 in ./python3/lib/python3.7/site-packages (from flake8->paddlehub==1.8.3) (4.2.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./python3/lib/python3.7/site-packages (from flake8->paddlehub==1.8.3) (0.6.1)
Requirement already satisfied: regex>=2021.8.3 in ./python3/lib/python3.7/site-packages (from nltk->paddlehub==1.8.3) (2022.6.2)
Requirement already satisfied: joblib in ./python3/lib/python3.7/site-packages (from nltk->paddlehub==1.8.3) (1.1.0)
Requirement already satisfied: pytz>=2017.2 in ./python3/lib/python3.7/site-packages (from pandas->paddlehub==1.8.3) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in ./python3/lib/python3.7/site-packages (from pandas->paddlehub==1.8.3) (2.8.2)
Requirement already satisfied: cfgv>=2.0.0 in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (3.3.1)
Requirement already satisfied: virtualenv>=20.0.8 in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (20.14.1)
Requirement already satisfied: toml in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (0.10.2)
Requirement already satisfied: pyyaml>=5.1 in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (6.0)
Requirement already satisfied: identify>=1.0.0 in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (2.5.1)
Requirement already satisfied: nodeenv>=0.11.1 in ./python3/lib/python3.7/site-packages (from pre-commit->paddlehub==1.8.3) (1.6.0)
Requirement already satisfied: Pillow>=7.0.0 in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (9.1.1)
Requirement already satisfied: requests in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (2.27.1)
Requirement already satisfied: shellcheck-py in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (0.8.0.4)
Requirement already satisfied: matplotlib in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (3.5.2)
Requirement already satisfied: bce-python-sdk in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (0.8.64)
Requirement already satisfied: Flask-Babel>=1.0.0 in ./python3/lib/python3.7/site-packages (from visualdl->paddlehub==1.8.3) (2.0.0)
Requirement already satisfied: Babel>=2.3 in ./python3/lib/python3.7/site-packages (from Flask-Babel>=1.0.0->visualdl->paddlehub==1.8.3) (2.10.1)
Requirement already satisfied: typing-extensions>=3.6.4 in ./python3/lib/python3.7/site-packages (from importlib-metadata<4.3->flake8->paddlehub==1.8.3) (4.2.0)
Requirement already satisfied: zipp>=0.5 in ./python3/lib/python3.7/site-packages (from importlib-metadata<4.3->flake8->paddlehub==1.8.3) (3.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./python3/lib/python3.7/site-packages (from Jinja2<3.0,>=2.10.1->flask>=1.1.0->paddlehub==1.8.3) (1.1.1)
Requirement already satisfied: filelock<4,>=3.2 in ./python3/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub==1.8.3) (3.7.1)
Requirement already satisfied: platformdirs<3,>=2 in ./python3/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub==1.8.3) (2.5.2)
Requirement already satisfied: distlib<1,>=0.3.1 in ./python3/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub==1.8.3) (0.3.4)
Requirement already satisfied: pycryptodome>=3.8.0 in ./python3/lib/python3.7/site-packages (from bce-python-sdk->visualdl->paddlehub==1.8.3) (3.14.1)
Requirement already satisfied: future>=0.6.0 in ./python3/lib/python3.7/site-packages (from bce-python-sdk->visualdl->paddlehub==1.8.3) (0.18.2)
Requirement already satisfied: cycler>=0.10 in ./python3/lib/python3.7/site-packages (from matplotlib->visualdl->paddlehub==1.8.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./python3/lib/python3.7/site-packages (from matplotlib->visualdl->paddlehub==1.8.3) (4.33.3)
Requirement already satisfied: packaging>=20.0 in ./python3/lib/python3.7/site-packages (from matplotlib->visualdl->paddlehub==1.8.3) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in ./python3/lib/python3.7/site-packages (from matplotlib->visualdl->paddlehub==1.8.3) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in ./python3/lib/python3.7/site-packages (from matplotlib->visualdl->paddlehub==1.8.3) (1.4.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./python3/lib/python3.7/site-packages (from requests->visualdl->paddlehub==1.8.3) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in ./python3/lib/python3.7/site-packages (from requests->visualdl->paddlehub==1.8.3) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./python3/lib/python3.7/site-packages (from requests->visualdl->paddlehub==1.8.3) (2022.5.18.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./python3/lib/python3.7/site-packages (from requests->visualdl->paddlehub==1.8.3) (2.0.12)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@dev-bigdata-01 bin]# hub install deploy/hubserving/ocr_det/
bash: hub: command not found
我也尝试更换paddlehub版本为2.1.0，结果是一样的。请教大神们是因为我的环境造成的吗

**Comment by LmingXie** [comment]
楼主怎么解决的
