### ISSUE TITLE
端侧部署问题

### ISSUE THREAD

**Issue by fx568000** [PaddlePaddle/PaddleOCR#6528]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu-16.04.5
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：Paddle-Lite release/v2.10
- 运行指令/Command Code：./ocr_db_crnn en_PP-OCRv3_det_infer_nb.nb ch_ppocr_mobile_v2.0_cls_infer_nb.nb rec_v3_en_mobile_nb.nb  ./11.jpg  ppocr_keys_v1.txt
- 完整报错/Complete Error Message: 系统回复：Please choose one mode of [det, rec, system] !

我这边按照端侧部署文档进行操作，到最后一步时
即：2.2 与手机联调-第5步时
![image](https://user-images.githubusercontent.com/49355496/172608675-bb54d7c9-e064-4426-8472-767b20943380.png)
我在adb中的命令为：./ocr_db_crnn en_PP-OCRv3_det_infer_nb.nb ch_ppocr_mobile_v2.0_cls_infer_nb.nb rec_v3_en_mobile_nb.nb  ./11.jpg  ppocr_keys_v1.txt

但是系统回复了：Please choose one mode of [det, rec, system] !
实际效果如下：
![image](https://user-images.githubusercontent.com/49355496/172609096-fd859ebf-dc1f-4f07-8f93-be8ac906d579.png)
请问导致此现象的原因

**Comment by fx568000** [comment]
上述问题是说需要进行参数选择吗，参数选择在哪里写呢

**Comment by littletomatodonkey** [comment]
你好，可以参考这里的文档和代码：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/lite/readme_ch.md

上面这个代码似乎不是用在端侧的代码
