### ISSUE TITLE
DBnet精度问题

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleOCR#6529]
环境：ubuntu18  
paddlenlp               2.3.1
paddleocr               2.5.0.3
paddlepaddle-gpu        2.3.0
参考下面的连接https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/algorithm_det_db.md
命令python tools/train.py -c configs/det/det_mv3_db.yaml 
得到的精度如下ppocr INFO: best metric, hmean: 0.6654611211573236, precision: 0.717948717948718, recall: 0.6201251805488686, fps: 30.84449987782963, best_epoch: 1194

文档的精度77.29% | 73.08% | 75.12%， 差距很大，请问是什么原因？

**Comment by MissPenguin** [comment]
直接用提供的模型评估的话是什么指标呢？

**Comment by mydgs** [comment]
请问你解决了吗，我也只得到跟你接近的精度，跟官方的差3-5个点
