### ISSUE TITLE
文本检测启动训练报错：paddle.fluid.core_avx.EnforceNotMet:

### ISSUE THREAD

**Issue by yanmeizhao** [PaddlePaddle/PaddleOCR#653]
使用的readme中推荐的镜像，paddle版本是：1.7.2，python3.5，cuda10，训练数据是我们自己的数据，整理成了icdar2015的格式，启动训练时出现如下错误：
![1](https://user-images.githubusercontent.com/13143336/91850398-16c9ef80-ec90-11ea-9c21-bb4717aaf378.png)
![2](https://user-images.githubusercontent.com/13143336/91850423-1df0fd80-ec90-11ea-9803-d262ba5d001f.png)
请问下我该如何解决，多谢！

**Comment by littletomatodonkey** [comment]
看着像是显存不够，你看下现在能用多少显存呢？
![image](https://user-images.githubusercontent.com/14270174/91925076-d8234c00-ed06-11ea-91e3-b967a17e918c.png)

**Comment by yanmeizhao** [comment]
> 显存不够，你看下现在能用

P4卡，显存7611MiB，batch size设置为1还是不行

**Comment by littletomatodonkey** [comment]
问题定位了，进程占用显存没有释放，使用下面的命令清空下就行了
```
ps -axu | grep train.py | awk '{print $2}' | xargs kill -9
```

**Comment by yanmeizhao** [comment]
> 问题定位了，进程占用显存没有释放，使用下面的命令清空下就行了
> 
> ```
> ps -axu | grep train.py | awk '{print $2}' | xargs kill -9
> ```
多谢
