### ISSUE TITLE
用multiprocessing来进行多进程异步推理时，报错如下，烦请帮忙看看

### ISSUE THREAD

**Issue by litao-zhx** [PaddlePaddle/PaddleOCR#6532]
![1654755267(1)](https://user-images.githubusercontent.com/76981650/172781745-fc19123d-8746-4e6b-8533-cff9555c2eac.jpg)

**Comment by litao-zhx** [comment]
本意是想着用multiprocessing开启两个进程，一个用来读取图片，一个用来推理，但是就报了如上的错误

**Comment by MissPenguin** [comment]
可以贴下具体命令吗，是按照这个方式使用的吗：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/FAQ.md#q-%E5%A6%82%E4%BD%95%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%A2%84%E6%B5%8B

**Comment by littletomatodonkey** [comment]
你好，可以参考这个pr：https://github.com/PaddlePaddle/PaddleOCR/pull/2429

暂时不支持把inference对象放在threading的子进程里
