### ISSUE TITLE
关于如何在一机多卡的机器上部署PaddleOCR并且在进行模型推理的时候调用多张显卡，需要怎么设置呢？

### ISSUE THREAD

**Issue by ZCCFighting** [PaddlePaddle/PaddleOCR#6537]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos7
- 版本号/Version：Paddle：paddle 2.3-gpu  PaddleOCR：2.5.0.3

**Comment by MissPenguin** [comment]
是想做服务化部署吗，多卡服务化部署可以使用Paddle Serving部署：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md
多卡在这里进行配置：https://github.com/PaddlePaddle/PaddleOCR/blob/4e9d2e9c40d4e2e5c2b459557011c7b687773103/deploy/pdserving/config.yml#L69

**Comment by ZCCFighting** [comment]
> 是想做服务化部署吗，多卡服务化部署可以使用Paddle Serving部署：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md 多卡在这里进行配置：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/4e9d2e9c40d4e2e5c2b459557011c7b687773103/deploy/pdserving/config.yml#L69

好的多谢回复，我试下看看

**Comment by bxjxxyy** [comment]
> 是想做服务化部署吗，多卡服务化部署可以使用Paddle Serving部署：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md 多卡在这里进行配置：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/4e9d2e9c40d4e2e5c2b459557011c7b687773103/deploy/pdserving/config.yml#L69

devices: "0"  是只使用gpu0的意思吗？那么如果使用所有gpu，是应该配置devices: "0,1,2,3"么？
