### ISSUE TITLE
Question about limit_type config setting

### ISSUE THREAD

**Issue by kkkris7** [PaddlePaddle/PaddleOCR#6540]
Hi PaddleOCR Team, I have a question about the limit_type setting during training and inference. I see in training phase, by default, Paddleocr set limit_type = "min", however, in inference, we see the default limit_type has been set to "max". I am wondering why this is an inconsistence. Is there any special reason? Shall I change that to "min" for inference?

**Comment by LDOUBLEV** [comment]
> Shall I change that to "min" for inference?

It is not necessary. The input for inference has a dynamic shape. But the input shape for the model should keep the same in each batch.
