### ISSUE TITLE
First frame inferrence is taking too long time 10 - 15 minutes.

### ISSUE THREAD

**Issue by ShakhzodbekYuldoshov** [PaddlePaddle/PaddleOCR#6543]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04 and ubuntu 18.04
- 版本号/Version：Paddle：  2.3.0
- PaddleOCR： 2.5.0.3
- 问题相关组件/Related components： Docker image
- 运行指令/Command Code：
To install:
```
- nvidia-docker run --name paddle_docker -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.2-cudnn7 /bin/bash
```
To inference:
```
import paddleocr
ocr = paddleocr.PaddleOCR(lang='korean', use_gpu=True)
results = ocr.ocr($<img_path>)
print(results)
```
- 完整报错/Complete Error Message： No error message but the first frame inference is taking too long time around 10 minutes. But after the first inference second one is fast enough. What is wrong I do not understand.

**Comment by LDOUBLEV** [comment]
Because the first inference contains time for environment initialization and model initialization.
