### ISSUE TITLE
表格识别错位的问题

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#6549]
想问一下，表格识别有空单元格的时候，表格结构还原会把文本错位，这样的情况有什么好的方法训练（除了增加空白单元格的数据），或者有什么建议吗？类似这样的场景，有大佬来解答吗？目前也在做数据，但是想小数据量解决这种问题。
![243a4e557b69fc2d0d0dd01aae716e5](https://user-images.githubusercontent.com/28819717/173009759-f2cb814f-91ed-42b4-9b54-507bd1ca8b74.png)
绿色的框是表格cell预测的结果。

**Comment by mingo-doer** [comment]
@WenmuZhou  @LDOUBLEV  大佬可以帮忙解答一下吗

**Comment by mingo-doer** [comment]
@littletomatodonkey

**Comment by WenmuZhou** [comment]
你说的错位能否具体一点，是最终到excel里错位，还是这里的空白单元格box和其他不在一条线

**Comment by mingo-doer** [comment]
> 你说的错位能否具体一点，是最终到excel里错位，还是这里的空白单元格box和其他不在一条线

都有，比如这张图第二行的第四列和第三列重合，根据IOU，第四列就被判定为第三列，所以写到excel自然就错位了
这是我自己造的一些数据，用excel造一些数据，中间空一列，很容易复现

**Comment by WenmuZhou** [comment]
这种应该属于模型错误
