### ISSUE TITLE
验证DB模型时输出Shape不一致

### ISSUE THREAD

**Issue by Zoushuang86** [PaddlePaddle/PaddleOCR#655]
训练DB模型时，当验证时输出Shape不一致
![image](https://user-images.githubusercontent.com/33125245/91928466-b0d07d00-ed0e-11ea-82b9-fec5127f1050.png)

**Comment by MissPenguin** [comment]
验证时，设置的shape需要是32的倍数，否则在feature map采样时会由于除不断出现1个像素的diff，类似你这里的52和51不匹配

**Comment by Zoushuang86** [comment]
我的图像大小是[602, 803]，设置的模型输入大小是[3, 512, 512]，请问这个32倍数的shape是指哪一个呢？

**Comment by MissPenguin** [comment]
都要满足，你这里是[602, 803]不满足导致的，可以改成[608, 800]

**Comment by Zoushuang86** [comment]
好的，谢谢。
