### ISSUE TITLE
paddle crnn训练

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6551]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

paddle crnn训练
训练时使用默认的yml文件，
字符集dict没修改，也一样可以训练字符集中没有的字符？

**Comment by LDOUBLEV** [comment]
> 字符集dict没修改，也一样可以训练字符集中没有的字符？

显然不可以，如果字典中没有要识别的字符，需要在字典中添加，重新训练

**Comment by nissansz** [comment]
但是，我实际训练日文，用默认的v3 dict，也是可以训练，最后转换onnx时指定一个正确的dict文件即可
