### ISSUE TITLE
【third-party】为PaddleOCR贡献Flask部署示例

### ISSUE THREAD

**Issue by WangRongsheng** [PaddlePaddle/PaddleOCR#6554]
[https://github.com/WangRongsheng/PaddleOCR-Flask-deploy](https://github.com/WangRongsheng/PaddleOCR-Flask-deploy)

**Comment by WangRongsheng** [comment]
@andyjpaddle

**Comment by Evezerest** [comment]
你好，感谢你的贡献，请在置顶的社区常规赛链接中按照格式回复提交。如果未加微信群可以先加入微信群后@群主

**Comment by WangRongsheng** [comment]
@Evezerest 请问如何找到微信群，或者您是否在ppde群或者其他群内，我可以添加到您。
