### ISSUE TITLE
PPOCRLabel' s Excel content based on Table Recognition can not be update

### ISSUE THREAD

**Issue by w-tim** [PaddlePaddle/PaddleOCR#6558]
Hi, 
PPOCRLabel 's Table Recognition is not working well if description is long and have several lines.
(table content - left, description, right, quantity)
I tried to adjust box border and execute cell re-recognition.  Now resulst is good.
However, this result can not be updated to Excel file. 
Is it possible to achieve this?

**Comment by Evezerest** [comment]
hi, 
In PPOCRLabel, the build-in table recognition model is from PP-Structure. 

If you want to train a table recognition model using PP-Structure, **the cell content in Excel is not important**, cuz the exported `JSON` annotation file will only be used to load the table structure information, like `<tr>, </td>, </tr>`. In other words, the content in each cell (data between `<td>` and `</td>`) in Excel will not be used. this is why you can use [any identifier](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/PPOCRLabel/README.md#22-table-annotation) to indicate that this cell has data.

But the content of the cell content does important when you train an OCR model. In this case, you need to label the data by row (not cell)

**Comment by w-tim** [comment]
Hi,

Thanks for reply.  I understood your above explanation.
Actually PPOCRLabel could be used more than pre-training tool expected for us. It is could be regarded as a slim-abbyy finereader since lacking micro-adjustment for drawing table,erase ocr area etc.
Hence, maybe "updating result to excel based on re-table recognition" maybe useful since you already provided us GUI and api to excel, we could open excel, copy and paste it to someplace we need.

**Comment by Evezerest** [comment]
Thanks for your suggestion, we'll add the function in the next version of PPOCRLabel.
Any contributions are welcome 😁

**Comment by w-tim** [comment]
> Thanks for your suggestion, we'll add the function in the next version of PPOCRLabel. Any contributions are welcome 😁

Thanks. Awesome job on this project.

**Comment by sumathipriya** [comment]
How should we do annotations like pubtabdataset structure format?
PPOCRLabel tool give bbox of 8 values,but in pubtabdataset have only bbox of 4 values,how we get like this?
