### ISSUE TITLE
单机多卡使用多进程内存不释放

### ISSUE THREAD

**Issue by bingdewendu** [PaddlePaddle/PaddleOCR#6559]
多卡多进程，内存不释放，直到oom

环境：linux
paddlepaddle-gpu：2.3.0.post101  PaddleOCR：2.5.0.3
8卡8进程，内存不释放
![图片](https://user-images.githubusercontent.com/52711978/173188124-55ae18c0-b222-47da-84dc-61216990df23.png)

**Comment by sjtu-cz** [comment]
我好像也遇到了同样的问题，好像有内存泄漏

**Comment by bingdewendu** [comment]
您的邮件已收到！谢谢~

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by yuanhaisu** [comment]
我也遇到这个问题，在C++Serving（serving-gpu-112-0.9.0）下就是 
![1658193771170](https://user-images.githubusercontent.com/11955508/179643736-22e81eba-d020-47c0-b943-f29b7f3730d4.png)

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by ChenjieXu** [comment]
我也遇到了，有什么解决方法吗 ppocrv3

**Comment by andyjpaddle** [comment]
这个应该是服务端一直开着会占用内存

**Comment by bingdewendu** [comment]
您的邮件已收到！谢谢~

**Comment by lgh1998** [comment]
我也是有这样的问题，目前还有我现在是跟新到2.7

**Comment by bingdewendu** [comment]
您的邮件已收到！谢谢~

**Comment by cmathx** [comment]
how to fix memory leak problem? I updated paddleocr to newest version (2.8.0). It also have this problem.

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by bingdewendu** [comment]
您的邮件已收到！谢谢~

**Comment by GreatV** [comment]
Consider installing the latest Paddle dev version  from https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html  to resolve this issue.
