### ISSUE TITLE
通用中文识别模型数据问题

### ISSUE THREAD

**Issue by XingBin111** [PaddlePaddle/PaddleOCR#656]
请问, 对LSVT进行裁剪时, 对裁剪出的图像进行了限制没(例如扔掉size太小或text太长的的图片)?

**Comment by littletomatodonkey** [comment]
你好，这块没有，但是在训练的时候，如果标注文本的长度超过25，则会忽略该条训练数据，你可以参考数据增广部分的代码获取更多的细节：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/rec/img_tools.py

**Comment by XingBin111** [comment]
ok, 感谢
