### ISSUE TITLE
v3日文训练的图片集, 有没有地方可以下载？想追加训练其他图片

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6560]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

v3日文训练的图片集, 有没有地方可以下载？想追加训练其他图片

**Comment by tink2123** [comment]
抱歉 暂时不会公开训练数据
