### ISSUE TITLE
v3训练 yml文件的字符集dict，不指定，也可以训练？对模型没有影响？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6561]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

v3训练 yml文件的字符集dict，不指定，也可以训练？对模型没有影响？

**Comment by tink2123** [comment]
不指定默认使用英文字典
