### ISSUE TITLE
开发部署PP-OCRv3时，数据如何输入与数据如何输出的问题。

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#6564]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10_Qt5.12_MSVC_C++ ——光功率计数码管字符识别项目
- PaddleOCR： PP-OCRv3   
- 模型已经训练好了，在Qt中已经导入好了相关推理的库，但是对于1.如何输入一张图片，2.获取识别结果。不知从何下手。
- 查阅光功率计数码管字符识别项目的文档，https://aistudio.baidu.com/aistudio/projectdetail/4049044?channelType=0&channel=0 ，只给出了在python环境下输入图片路径，并获取识别结果的方法。
- 然后查阅飞桨推理文档，https://paddle-inference.readthedocs.io/en/latest/quick_start/workflow.html   ，给出了在c++环境下API的数据输入与输出的方法。

- 所以目前有以下三个问题：
- 1.对于数据输入，我目前的想法时用opencv读取图片，然后将其转化为tensor的格式。
- // 准备输入数据
int input_num = shape_production(INPUT_SHAPE);
std::vector<float> input_data(input_num, 1);
按照文档，这里的1就是所需图片数据，那么我的问题是：此处仅需要“图片路径”即可，还是需要将图片转化为RGB的比特形式？
另外此处的 INPUT_SHAPE 是否有要求，应该与模型训练时的 image_shape[3, 48, 320] 保持一致？

-2.对于输出tensor，我目前暂不明确，输出的信息我该如何处理才能得到识别结果。
有查阅资料，发现一些类似项目代码如下，我的理解是， 从每个维度获取 最大值坐标 和 最大值，然后索引至预设字典 label_list_ 获得识别结果。不知道这种理解方式是否正确？
std::vector<std::string> str_res;
			int argmax_idx;
			int last_index = 0;
			float score = 0.f;
			int count = 0;
			float max_value = 0.0f;

			for (int n = 0; n < predict_shape[1]; n++) {
				argmax_idx =
					int(Utility::argmax(&predict_batch[n * predict_shape[2]],
						&predict_batch[(n + 1) * predict_shape[2]]));
				max_value =
					float(*std::max_element(&predict_batch[n * predict_shape[2]],
						&predict_batch[(n + 1) * predict_shape[2]]));

				if (argmax_idx > 0 && (!(n > 0 && argmax_idx == last_index))) {
					score += max_value;
					count += 1;
					str_res.push_back(label_list_[argmax_idx]);
				}
				last_index = argmax_idx;
			}
			score /= count;
			std::string str;
			for (int i = 0; i < str_res.size(); i++) {
				std::cout << str_res[i];
				str += str_res[i];
			}
			std::cout << "\tscore: " << score << std::endl;
			list_str.push_back(str);

-3.请问 PP-OCRv3识别模型中，也有 画框检测 的部分吗？因为在 光功率计数码管字符识别项目 中没有提到有关部分，这部分会涉及到我之后对于输入图片的预处理，是否需要进行剪裁等。

**Comment by kingkingpang** [comment]
@tink2123

**Comment by kingkingpang** [comment]
@tink2123

**Comment by tink2123** [comment]
1. cpp demo可参考https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/cpp_infer
2. 是的，理解正确
3. 数码管项目中以文本识别为例，没有提供检测的说明，实际的OCR系统中应包含检测部分。具体代码依然可以参考1中给出的demo
