### ISSUE TITLE
How to save the result of the direction classification

### ISSUE THREAD

**Issue by qz701731tby** [PaddlePaddle/PaddleOCR#6566]
I hope to save the result of direction classification and rectify the text for further process.  Is there any API that I can use to achieve this goal?

**Comment by WenmuZhou** [comment]
you can get result from this line https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/tools/infer/predict_system.py#L84

**Comment by qz701731tby** [comment]
I find it useful. But the output of angle list contains only 0, 180, without 90 and 270. Maybe the pretrained pp-ocrv3 model can only predict 0 or 180 for direction classification?

**Comment by WenmuZhou** [comment]
yes
