### ISSUE TITLE
使用 ch_det_res18_db_v2.0.yml server版本的det检测模型进行finetune时，每次执行eval都会导致GPU内存溢出

### ISSUE THREAD

**Issue by wangpf09** [PaddlePaddle/PaddleOCR#6567]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： win11
- 版本号/Version：Paddle：2.3.0.post1112  PaddleOCR：2.5.0.3  问题相关组件/Related components：det
- 运行指令/Command Code：python tools/train.py -c ../cust-config/bank/det-db/ch_det_res18_db_v2.0.yml
- 完整报错/Complete Error Message：

每次epoch执行完第一次进行eval时，就会报GPU内存溢出的问题
```
Traceback (most recent call last):
  File "E:\project-space\ocr-tools\PaddleOCR\tools\train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "E:\project-space\ocr-tools\PaddleOCR\tools\train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "E:\project-space\ocr-tools\PaddleOCR\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\losses\det_db_loss.py", line 61, in forward
    loss_shrink_maps = self.bce_loss(shrink_maps, label_shrink_map,
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\losses\det_basic_loss.py", line 96, in forward
    sort_loss = negative_loss.sort(descending=True)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\tensor\search.py", line 480, in sort
    outs, _ = _C_ops.argsort(x, 'axis', axis, 'descending', descending)
SystemError: (Fatal) Operator argsort raises an class thrust::system::detail::bad_alloc exception.
The exception content is
:bad allocation: cudaErrorMemoryAllocation: out of memory. (at ..\paddle\fluid\imperative\tracer.cc:307)

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
```

**Comment by WenmuZhou** [comment]
建议eval时将图片设置的小一点，可以参考这里设置尺寸https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/configs/det/det_mv3_db.yml#L118

**Comment by wangpf09** [comment]
batch size已经设置为1了，num work是2，而且这个报错只会在这个模型存在，mv轻量级模型不会出现的发自我的手机-------- 原始邮件 --------发件人： zhoujun ***@***.***>日期： 2022年6月13日周一 16:42收件人： PaddlePaddle/PaddleOCR ***@***.***>抄送： moxf ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleOCR] 使用 ch_det_res18_db_v2.0.yml server版本的det检测模型进行finetune时，每次执行eval都会导致GPU内存溢出 (Issue #6567)

建议eval时将图片设置的小一点，可以参考这里设置尺寸https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/configs/det/det_mv3_db.yml#L118

**Comment by wangpf09** [comment]
Global:
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ../output/bankcard/ch_db_res18/v1
  save_epoch_step: 30
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [ 0, 2500 ]
  cal_metric_during_train: False
  pretrained_model: ../pretrained_model/ch_ppocr/ch_ppocr_server_v2.0_det_train/best_accuracy.pdparams
  checkpoints:
  save_inference_dir: ../output/bankcard/ch_db_res18/v1/inference
  use_visualdl: true
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ../output/bankcard/ch_db_res18/v1/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet
    layers: 18
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 1
  regularizer:
    name: 'L2'
    factor: 5.0e-05

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../train_data
    label_file_list:
      - ../train_data/bank/bank1/real_det_train.txt
      - ../train_data/bank/bank2/real_det_train.txt
      - ../train_data/bank/bank3/real_det_train.txt
      - ../train_data/bank-axa/det/train.txt
      - ../train_data/bank/bank2/real_det_test.txt
      - ../train_data/bank/bank3/real_det_test.txt
      - ../train_data/bankcard-rotate-1/det/train.txt
      - ../train_data/bankcard-rotate-2/det/train.txt
    ratio_list: [ 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 0.4, 0.3 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [ -10, 10 ] } }
            - { 'type': Resize, 'args': { 'size': [ 0.5, 3 ] } }
      - EastRandomCropData:
          size: [ 960, 960 ]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask' ] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: True
    batch_size_per_card: 4
    num_workers: 8
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../train_data
    label_file_list:
      - ../train_data/bank/bank1/real_det_test.txt
      - ../train_data/bank-axa/det/test.txt
      - ../train_data/bankcard-rotate-1/det/test.txt
      - ../train_data/bankcard-rotate-2/det/test.txt
    ratio_list: [ 1.0, 1.0, 0.4, 0.3 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          limit_side_len: 736
          limit_type: min
      - NormalizeImage:
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'shape', 'polys', 'ignore_tags' ]
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2



这个是我的完整配置
