### ISSUE TITLE
Add Thai language support

### ISSUE THREAD

**Issue by xuhuaren** [PaddlePaddle/PaddleOCR#6569]
[thai_corpus.txt](https://github.com/PaddlePaddle/PaddleOCR/files/8889067/thai_corpus.txt)
[thai_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/files/8889069/thai_dict.txt)

Please see attached,
thai_dict is the dictionary of Thai
thai_corpus is some words of Thai

**Comment by WenmuZhou** [comment]
微信已经沟通过了，issue我就关闭了

**Comment by itxiaoxian** [comment]
我把这两个文件放入到ppocr/utils/dict下面，结果还是不识别。请问下载这两个文件之后应该怎么操作呢？
