### ISSUE TITLE
主页展示的图片——MTWI 2018数据集是否有用于训练网络？

### ISSUE THREAD

**Issue by ryupaladin** [PaddlePaddle/PaddleOCR#657]
您好！
感谢开源如此优秀的工作，借助这个项目，我开始入手学习paddle。
有一个问题，在主页上说使用了LVST数据集和其语料生成的数据，请问公开数据集只使用了LVST吗，主页展示的属于MTWI数据集的图片是否有用于训练，因为我重新微调训练了mobilenet，但没有使用MTWI，MTWI测试结果在编辑距离、precision、recall上都有所提高，但是全对率反而下降了8个百分点。

另外，生成算法你们使用的是synthtext吗？

谢谢你们在百忙之余解答我的问题！

**Comment by littletomatodonkey** [comment]
你好，感谢你的关注，我们也使用了mtwi数据集用于模型训练，此外，生成算法我们使用的text_renderer，你可以参考我们的文档~：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/data_synthesis.md
