### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppstructure/layout/train_layoutparser_model_ch.md 文字描述需要改进

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/PaddleOCR#6571]
背景：paddleocr的研发同学，给出的参考示例如下，对应描述如下
给一下版面分析的训练文档吧，应该照着操作就行
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppstructure/layout/train_layoutparser_model_ch.md
可以参考这里哈~

提几个意见：1）publaynet有90G，给用户自己下载十分不友好，要么准备个小一点的数据，要么提供个高速获取的数据源。2）这个页面讲的主要是用ppdetection，但对没装ppdet的用户不够友好，很多依赖包要手动装，容易出错。
<img width="1125" alt="164bbb33e3e7c636f8ae8f513c776c4c" src="https://user-images.githubusercontent.com/35550832/173305500-d215bd37-72a2-4e3e-8342-8d7cfc940b56.png">
3）这里写的太不友好了，上面都给了要下载的数据集，这里让自己根据实际情况修改，也不给个现成的文件参考。

**Comment by WenmuZhou** [comment]
1. 数据集我们在aistudio上提供了一个小型的验证集 https://aistudio.baidu.com/aistudio/datasetdetail/119702 可以快速下载
2. 这个我们目前正在优化
