### ISSUE TITLE
 PP-OCRv3_图片多次输入问题_ Each config can only be used for one predictor

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#6572]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10_Qt5.12_MSVC_C++ —— 光功率计数码管字符识别项目

- PaddleOCR： PP-OCRv3

- 模型已经训练好了，在Qt中已经导入好了相关推理的库.当我识别一张图片之后，再次识别，会出现 Each config can only be used for one predictor 。

- 之前有人提出 ，https://github.com/PaddlePaddle/Paddle/issues/27387#issuecomment-694160810  ，“每一个Config只能初始化一个Predictor，请确认下是不是多次用到了同一个Predictor。” 

- 但在实际工作中，我需要批量识别多张图片，所以怎样才能重复使用这个config下的predictor？或者怎么做才能一次识别多张图片？

**Comment by kingkingpang** [comment]
@WenmuZhou

**Comment by WenmuZhou** [comment]
可以参考这个https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/tools/infer/predict_system.py

你初始化一个predict然后hold住就可以了

**Comment by kingkingpang** [comment]
已解决，不过不是用的这个方法

> 初始化一个predict然后hold住

之前我是处于内存的考虑，把config放在了初始化里，然后再去调用predictor，会报错。
解决办法是把config和predictor 全部放在一起，每次同时重新创建config 和 predictor，暂时先这样解决了。
