### ISSUE TITLE
西班牙语模型无法识别空格

### ISSUE THREAD

**Issue by liushengtong** [PaddlePaddle/PaddleOCR#6573]
已多次在视频与图像种测试西班牙推理模型，无法识别其中空格字符，请问有解决方法吗？或者提供一个可以识别空格的西班牙语模型也可以。
![image](https://user-images.githubusercontent.com/51230137/173330747-097352b3-8332-42a9-8a93-37b34a21cd2f.png)

![image](https://user-images.githubusercontent.com/51230137/173330696-0f832d43-f892-410c-b4d9-5574fe48d511.png)

**Comment by tink2123** [comment]
空格是ok的，音调符号识别不够好，请问您用的是哪个模型呢？看报错似乎不是paddleocr

```
paddleocr --image_dir=xi_test.png --det=False --lang=es  
```

<img width="546" alt="image" src="https://user-images.githubusercontent.com/31891223/174216078-d826688e-c5e6-40e9-9aeb-50b4a0f3f102.png">

**Comment by liushengtong** [comment]
![image](https://user-images.githubusercontent.com/51230137/174774202-7846a0d3-63c9-4771-9563-7fee15c16436.png)
你看一下 我是用咱们的代码和推理模型做的 ，还是这个图片 ，西班牙语言识别结果就是没有空格 
![image](https://user-images.githubusercontent.com/51230137/174773990-f660db02-5c52-4f3f-9f15-976f4aefeff9.png)
我怀疑是不是模型有一些问题呢，用的你们提供的西班牙paddleocr2.0模型
![image](https://user-images.githubusercontent.com/51230137/174774159-380f9845-f509-41e0-817d-e5038dc1c8c3.png)

**Comment by tink2123** [comment]
您用的这个模型比较旧了哈，可以试下最新版的模型：
模型：https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/latin_PP-OCRv3_rec_infer.tar
字典：./ppocr/utils/dict/latin_dict.txt

**Comment by GUOhm230** [comment]
> 您用的这个模型比较旧了哈，可以试下最新版的模型： 模型：https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/latin_PP-OCRv3_rec_infer.tar 字典：./ppocr/utils/dict/latin_dict.txt

您好！
我最近用法语模型训练：french_mobile_v2.0_rec_infer.tar，得到的结果也是无法识别空格的。请问这是什么情况？也能用你提供的那个模型训练嘛？

**Comment by wzg722** [comment]
> 您用的这个模型比较旧了哈，可以试下最新版的模型： 模型：https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/latin_PP-OCRv3_rec_infer.tar 字典：./ppocr/utils/dict/latin_dict.txt

空格识别效果不好
