### ISSUE TITLE
PPOCRLabel.py  --lang ch 报When args.layout is false, args.ocr is automatically set to false个错误

### ISSUE THREAD

**Issue by crazyshare** [PaddlePaddle/PaddleOCR#6578]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MACOS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：  python PPOCRLabel.py  --lang ch
- 完整报错/Complete Error Message：
-报错信息是：
<img width="1454" alt="WechatIMG39" src="https://user-images.githubusercontent.com/8130648/173485966-b10fbd47-fc5e-439c-854c-6f88246c58c7.png">
 ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

**Comment by Evezerest** [comment]
是不是被关掉了，可以重置一下设置看看

**Comment by crazyshare** [comment]
已经解决好了，谢谢你
________________________________
发件人: Evezerest ***@***.***>
发送时间: 2022年6月15日 18:45
收件人: PaddlePaddle/PaddleOCR ***@***.***>
抄送: 架构部-陈东明 ***@***.***>; Author ***@***.***>
主题: Re: [PaddlePaddle/PaddleOCR] PPOCRLabel.py --lang ch 报When args.layout is false, args.ocr is automatically set to false个错误 (Issue #6578)


是不是被关掉了，可以重置一下设置看看

―
