### ISSUE TITLE
French language image - Random words output

### ISSUE THREAD

**Issue by sasumay** [PaddlePaddle/PaddleOCR#6580]
Please provide the following information to quickly locate the problem

System Environment/System Environment: Ubuntu 20.0.4
Version number/Version: Paddle: PaddleOCR: 2.5
Run command/Command Code: 
ocr = PaddleOCR(use_angle_cls=True, lang='fr') 
result = ocr.ocr(img, cls=True)
Complete error/Complete Error Message:

The French language image creates some random text at certain sections.
For example the last line in the image is OCRed to some random words not at all related to the image.

Last line from image - 
![image](https://user-images.githubusercontent.com/107453404/173491932-fc908648-8ea5-4675-9be2-e58496b49f6e.png)
OCR Result - 
snod anbiun aelsenb ae tiop uonouo eteo uean aae enbeto anod eaup

Link to download original image - https://github.com/sasumay/paddle-test/blob/main/french_random.tif?raw=true

**Comment by tink2123** [comment]
You might try turning off the orientation classifier. And for plain text lines, the detection model can also be removed:

```
ocr = PaddleOCR(lang='fr')
result = ocr.ocr(img, cls=False, det=False)
```

result:
```
[2022/06/15 10:17:32] ppocr INFO: **********french_test.png**********
[2022/06/15 10:17:33] ppocr INFO: ('differe pour chaque tre humain. Cette fonction doit &tre quasiment unique pour', 0.9392363429069519)
```

If the returned results are confusing, you can visualize whether the detection results are word-level
