### ISSUE TITLE
c++推理代码报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleOCR#6581]
请问输入字符比较多的图片就会报错什么原因呢？版本是paddleocr2.5
![image](https://user-images.githubusercontent.com/48303408/173518584-5f29045e-32bb-49c5-9764-b878e434e4be.png)

**Comment by WenmuZhou** [comment]
方便提供测试图片吗

**Comment by Dandelion111** [comment]
> 方便提供测试图片吗

![2](https://user-images.githubusercontent.com/48303408/173969663-35ed6d4f-3e41-4d57-bc2a-7aab67b0e4b3.jpg)
这张图就报错了，好像也不是字数多的原因，

**Comment by WenmuZhou** [comment]
请问你用的v3的模型还是v2的模型，我这边v3模型在linux下正常
![image](https://user-images.githubusercontent.com/12406017/175471374-8c397cfb-33e2-4934-b3f2-40775a813236.png)

**Comment by Dandelion111** [comment]
> 请问你用的v3的模型还是v2的模型，我这边v3模型在linux下正常 ![image](https://user-images.githubusercontent.com/12406017/175471374-8c397cfb-33e2-4934-b3f2-40775a813236.png)

你好，我之前是det用的v1，rec用v1、v2、v3都报错，现在把det换成v3不报错了

**Comment by WenmuZhou** [comment]
好的
