### ISSUE TITLE
svtr实现中的flatten操作

### ISSUE THREAD

**Issue by Henryplay** [PaddlePaddle/PaddleOCR#6583]
哈喽你好，我这边在看SVTR识别代码的时候遇到了一个问题https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/modeling/backbones/rec_svtrnet.py
在第334行:`x = self.proj(x).flatten(x).transpose((0,2,1))`中的flatten操作等同于torch中的reshape操作吗？是不是把(b,c,h,w)转换成(b,c,h*w)接着再转成(b,h*w,c)，我的理解对吗。

**Comment by Topdu** [comment]
理解的对。
但是第334行应该是: 'x = self.proj(x).flatten(2).transpose((0,2,1))'。可以去paddlepaddle官方文档中查看关于这两个op的说明文档。 [flatten](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flatten_cn.html#flatten)

**Comment by Henryplay** [comment]
> 理解的对。 但是第334行应该是: 'x = self.proj(x).flatten(2).transpose((0,2,1))'。可以去paddlepaddle官方文档中查看关于这两个op的说明文档。 [flatten](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flatten_cn.html#flatten)

谢谢，是我打错了哈哈。
