### ISSUE TITLE
Urdu Language Support in Paddle OCR

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [PaddlePaddle/PaddleOCR#6584]
Thank you very much for such a great work . I want to know whether Paddle OCR support ["Urdu Language"](https://en.wikipedia.org/wiki/Urdu) . If it is not, any plan in future to support ["Urdu Language"](https://en.wikipedia.org/wiki/Urdu)  in Paddle OCR ? How can train own OCR on any language or ["Urdu Language"](https://en.wikipedia.org/wiki/Urdu) . Thank You

**Comment by tink2123** [comment]
urdu language has been supported. You can use the following command to quickly experience
```
paddleocr --image_dir={img path} --lang="ur" --det=False
```
The current model lacks real data. If it cannot meet your actual requirements, you can refer to the [documentation](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/multi_languages_en.md#3-custom-training) to fine-tune your own data.
