### ISSUE TITLE
光功率计数码管字符识别 bml codelab 图片输入错误

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#6586]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.7.4
- 版本号/Version：Paddle：PaddlePaddle 2.3.0  PaddleOCR
- 运行指令/Command Code：paddleocr --lang=ch --det=Fase --image_dir=3.jpg
- 完整报错/Complete Error Message：  File "/tmp/ipykernel_231/4248773172.py", line 1
    paddleocr --lang=ch --det=Fase --image_dir=3.jpg
                                                                                            ^
SyntaxError: invalid syntax

<img width="1187" alt="截屏2022-06-14 下午10 37 48" src="https://user-images.githubusercontent.com/53334346/173606545-b4039a6b-4fa8-4808-aeb9-27a7b1a4c1d4.png">

**Comment by littletomatodonkey** [comment]
如果希望运行命令（而非python代码）的话，需要在前面加上!

**Comment by kingkingpang** [comment]
@littletomatodonkey  谢谢已解决。
