### ISSUE TITLE
SVTR-Tiny

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#6587]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：python 3.7.4
版本号/Version：Paddle：PaddlePaddle 2.5.0 PaddleOCR
运行指令/Command Code：
完整报错/Complete Error Message： size of model is so heavy (23MB)

I did read the SVTR paper but I don't know understand SVTR with 4.5M or 6M parameters is equal 23MB (may be smaller). I need adjust some things for descreasing size of model, right?

**Comment by Topdu** [comment]
I didn't understand your question.
The model size is about four times the amount of parameters, and 6M in the paper is the amount of parameters, so the model size is about 24M.
