### ISSUE TITLE
pipline seveing 默认配置下3090的24G显存都不够用

### ISSUE THREAD

**Issue by thep0y** [PaddlePaddle/PaddleOCR#6588]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddle cuda 11.2 docker 镜像
- 版本号/Version：Paddle：2.3.0  PaddleOCR： https://github.com/PaddlePaddle/PaddleOCR/commit/4e9d2e9c40d4e2e5c2b459557011c7b687773103 问题相关组件/Related components：serve-pipline
- 运行指令/Command Code：python web_service.py
- 完整报错/Complete Error Message：
```
erro_no:10000, err_msg:[rec] failed to predict. (data_id=5 log_id=5) [rec|1] Failed to process(batch: [5]): ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 17.266846MB memory on GPU 0, 23.651855GB memory has been allocated and available memory is only 45.687500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
```

使用的图片是`deploy/pdserving/imgs`中的图片。

是我显存太小了吗？

det和rec的并发数改成4-2才正常。

**Comment by yangy996** [comment]
det模型所用的显存大小与图片输入的大小有关，如果你输入的图片过大，有很大可能会显存溢出

**Comment by thep0y** [comment]
我用的就是项目里的测试图片发自我的手机-------- 原始邮件 --------发件人： YANGY ***@***.***>日期： 2022年6月16日周四 11:36收件人： PaddlePaddle/PaddleOCR ***@***.***>抄送： thep0y ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleOCR] pipline seveing 默认配置下3090的24G显存都不够用 (Issue #6588)

det模型所用的显存大小与图片输入的大小有关，如果你输入的图片过大，有很大可能会显存溢出

**Comment by rubyangxg** [comment]
我也是同样的问题，运行官方的教程例子都提示显存不足
