### ISSUE TITLE
数字文字翻转，文字反了，怎么识别

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#6589]
![微信截图_20220615095655](https://user-images.githubusercontent.com/6490927/173720043-5b6fbdf2-51e9-4554-ade8-48c2537c0817.png)

会上下翻转
竖起来
竖起来翻转

这种场景
应该要用什么模型 训练 会比较好

**Comment by MissPenguin** [comment]
带上文本方向分类器，应该能解决你给的这个case

**Comment by 1997lyv** [comment]
请问解决了吗？
