### ISSUE TITLE
paddleocr export onnx error

### ISSUE THREAD

**Issue by hsliuyl** [PaddlePaddle/PaddleOCR#6590]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.3.0  PaddleOCR：chinese_ocr_db_crnn_server 问题相关组件/Related components： paddle2onnx: 0.9.7 onnxruntime: 1.11.1
- 运行指令/Command Code：paddle2onnx.export(
                       model_file= "../../files/ocr/inference_model/inference.pdmodel",
                       params_file="../../files/ocr/inference_model/inference.pdiparams",
                       save_file="../../files/ocr/ocr.onnx",                       
                       #opset_version=14 ,
                       enable_onnx_checker= False)  
- 完整报错/Complete Error Message：[Paddle2ONNX[] Oops, there are some operators not supported yet, including fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max,
ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by user00644** [comment]
请问这个问题解决了吗？量化后的模型可以转onnx吗？

**Comment by HansBug** [comment]
> 请问这个问题解决了吗？量化后的模型可以转onnx吗？

根据2023.10.15的测试，依然不能，报错也是一样的。

参考的内容包括：
* https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md#1.2
* https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/paddle2onnx/readme_ch.md
