### ISSUE TITLE
detect function order_points_clockwise

### ISSUE THREAD

**Issue by xiaoshihoua** [PaddlePaddle/PaddleOCR#6591]
[order_points_clockwise]
input:
[[ 907  592]
 [1421 1106]
 [1111 1416]
 [ 597  902]]
output:
[[ 907.  592.]
 [ 907.  592.]
 [1421. 1106.]
 [1111. 1416.]]
but i use old code is ok

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/6654
