### ISSUE TITLE
执行多线程的OCR预测时，发现报错

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/PaddleOCR#6592]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境 ： win 10：
- 版本号/Version：Paddlepaddle-gpu  2.2.2;  PaddleOCR   2.5.0.3
- 使用多线程执行预测OCR时，发现报错。预测代码大致如下：
- 
![1](https://user-images.githubusercontent.com/37755235/173788561-08eada49-fa86-4763-bae8-06f2a56221fa.png)
![2](https://user-images.githubusercontent.com/37755235/173788637-ab2ba0bf-e224-4ee6-9c96-c6ecb352cf1c.png)
![3](https://user-images.githubusercontent.com/37755235/173788640-b9685c83-88de-497a-929f-e00e23ae5674.png)

- 完整报错/Complete Error Message：
![4](https://user-images.githubusercontent.com/37755235/173790777-9205df75-fb74-4b59-b45d-64430b9d1f37.png)

**Comment by lmw0320** [comment]
还个报错，忘记发了
![5](https://user-images.githubusercontent.com/37755235/173794665-4ce9f28a-dc05-461e-aac9-b57104827aab.png)

**Comment by littletomatodonkey** [comment]
你好，可以参考这个pr：https://github.com/PaddlePaddle/PaddleOCR/pull/2429

暂时不支持把inference对象放在threading的子进程里

**Comment by paopjian** [comment]
CPU预测的时候会自动占满全核吧,即使能多线程性能不就会被平分吗

**Comment by littletomatodonkey** [comment]
默认使用单线程预测，如果开启mkldnn，会使用多线程预测

**Comment by lmw0320** [comment]
> 请教下，那如果我想使用多线程的话，要怎么做才合理？？

**Comment by lmw0320** [comment]
> 

没太明白您的意思。您是说用CPU预测的情况下，会自动占满CPU，此时用不用多线程，都无所谓？？

**Comment by paopjian** [comment]
这是我单线程关闭mkldnn的cpu记录:
![image](https://user-images.githubusercontent.com/20377352/174240524-4b916b7d-184d-44a9-8bda-136fc0daa1b4.png)
这是单线程开启mkldnn的记录:
![image](https://user-images.githubusercontent.com/20377352/174240842-4712fd31-1c89-4d07-bfbf-717c3427be84.png)
paddle已经进行了多核调用,如果要提速,可以考虑打开mkldnn,如果有多个gpu,可以试试绑定gpu并用多进程处理

> > CPU预测的时候会自动占满全核吧,即使能多线程性能不就会被平分吗
> 
> 没太明白您的意思。您是说用CPU预测的情况下，会自动占满CPU，此时用不用多线程，都无所谓？？

**Comment by lmw0320** [comment]
> 这是我单线程关闭mkldnn的cpu记录: ![image](https://user-images.githubusercontent.com/20377352/174240524-4b916b7d-184d-44a9-8bda-136fc0daa1b4.png) 这是单线程开启mkldnn的记录: ![image](https://user-images.githubusercontent.com/20377352/174240842-4712fd31-1c89-4d07-bfbf-717c3427be84.png) paddle已经进行了多核调用,如果要提速,可以考虑打开mkldnn,如果有多个gpu,可以试试绑定gpu并用多进程处理
> 
您的意思就是，只要开启了mkldnn，其实就是把多核都占满了。。再用多线程，其实已经没什么用了，是吧？
只是我的处理代码，除了调用paddle的ocr模型外，还有其他的操作。其他的操作，还是需要用这个多线程来提速的。。
您可以看看我前面截图的代码，对我的主处理函数来说，ocr的预测，只是作为其中的一个子函数来调用的。
因为我有数万份文件，想要切分成几部分，交给各个线程去独立处理。各子线程分别执行主处理函数处理各自的文件。。而这些文件需要被经过多重处理操作，ocr的预测只是其中一个操作而已。

**Comment by lmw0320** [comment]
大佬们，能不能给个正式的解释答复啊。。
