### ISSUE TITLE
> > 配置文件中resize的尺寸是640时验证集上是有精度的，但是在将其尺寸改为320时精度一直为0

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#6598]
> > 配置文件中resize的尺寸是640时验证集上是有精度的，但是在将其尺寸改为320时精度一直为0
> 
> 是不是你的输入图像都是长文本

是长文本，图像尺寸约为40（高）x900（宽）。之前也想过这个问题，但是考虑到有resize，而且在v2.0版本代码下使用配置文件rec_en_number_lite_train.yml训练（resize尺寸为：3x32x320）没有这个问题，我试了下PPOCRV2与PPOCRV3都有这个问题，请问我应该如何修改来解决这个问题呢

_Originally posted by @zhang0225 in https://github.com/PaddlePaddle/PaddleOCR/issues/6545#issuecomment-1153376210_

**Comment by zhang0225** [comment]
> 
请问这个问题应该如何解决，尝试了几种方法没什么效果

**Comment by yangy996** [comment]
https://blog.csdn.net/YY007H/article/details/124973777
试试这个，不用深度学习方法看看能解决吧

**Comment by zhang0225** [comment]
> https://blog.csdn.net/YY007H/article/details/124973777 试试这个，不用深度学习方法看看能解决吧

首先谢谢你的回复，但我的问题并不是一个检测问题而是识别问题

**Comment by LDOUBLEV** [comment]
> 而且在v2.0版本代码下使用配置文件rec_en_number_lite_train.yml训练（resize尺寸为：3x32x320）没有这个问题

如果你训练的时候采用的宽度是320，预测的时候设置为320比较好，如果你训练的时候用的是640，建议预测的时候也设置为640

**Comment by zhang0225** [comment]
> > 而且在v2.0版本代码下使用配置文件rec_en_number_lite_train.yml训练（resize尺寸为：3x32x320）没有这个问题
> 
> 如果你训练的时候采用的宽度是320，预测的时候设置为320比较好，如果你训练的时候用的是640，建议预测的时候也设置为640

确实是这样设置的，但是在训练过程中V3版本320尺寸下的精度一直非常低，但640的精度还是比较高的

**Comment by LDOUBLEV** [comment]
如果你的是长文本，设置为宽度320，文本会被压缩的很厉害，识别精度低很正常

**Comment by zhang0225** [comment]
> 如果你的是长文本，设置为宽度320，文本会被压缩的很厉害，识别精度低很正常

使用rec_en_number_lite_train.yml这个配置文件时，我使用同样的尺寸训练精度是正常的，可以达到0.88，使用ch_PP-OCRv3_rec.yml或者en_PP-OCRv3_rec.yml时精度就一直维持在0.1左右上不去。如果是因为长文本尺寸问题的话使用rec_en_number_lite_train.yml这个配置文件的训练精度也应该是低的，所以还是想请教下这个尺寸的问题
