### ISSUE TITLE
训练模型时报错

### ISSUE THREAD

**Issue by luo693353634** [PaddlePaddle/PaddleOCR#660]
我在我自己的电脑，使用CPU尝试对探测模型进行训练，使用数据集icdar15时出现了下列的错误：

import ujson error: No module named 'ujson' use json
2020-09-02 21:18:41,353-INFO: places would be ommited when DataLoader is not iterable
I0902 21:18:43.086078 121945536 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 4 cards are used, so 4 programs are executed in parallel.
W0902 21:18:43.637987 121945536 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 189. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 185.
I0902 21:18:43.670666 121945536 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0902 21:18:44.865204 121945536 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0902 21:18:45.055680 121945536 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
W0902 21:18:45.540113 67477504 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0902 21:18:45.540398 67477504 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0902 21:18:45.540506 67477504 init.cc:214] The detail failure signal is:

W0902 21:18:45.540666 67477504 init.cc:217] *** Aborted at 1599052725 (unix time) try "date -d @1599052725" if you are using GNU date ***
W0902 21:18:45.541718 67477504 init.cc:217] PC: @                0x0 (unknown)
W0902 21:18:45.542047 67477504 init.cc:217] *** SIGSEGV (@0x110) received by PID 36325 (TID 0x70000405a000) stack trace: ***
W0902 21:18:45.542268 67477504 init.cc:217]     @     0x7fff701ff5fd _sigtramp
W0902 21:18:45.542452 67477504 init.cc:217]     @     0x7fff6ffbdb2b dispatch_apply_f
W0902 21:18:45.543294 67477504 init.cc:217]     @        0x100da7ed2 cv::parallel_for_()
W0902 21:18:45.543746 67477504 init.cc:217]     @        0x101120bd1 cv::hal::warpAffine()
W0902 21:18:45.544051 67477504 init.cc:217]     @        0x101121813 cv::warpAffine()
W0902 21:18:45.544338 67477504 init.cc:217]     @        0x100a00a2c pyopencv_cv_warpAffine()
W0902 21:18:45.544673 67477504 init.cc:217]     @        0x1004538a2 _PyMethodDef_RawFastCallKeywords
W0902 21:18:45.544888 67477504 init.cc:217]     @        0x1005913b2 call_function
W0902 21:18:45.545094 67477504 init.cc:217]     @        0x10058f158 _PyEval_EvalFrameDefault
W0902 21:18:45.545294 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.545486 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.545676 67477504 init.cc:217]     @        0x100591337 call_function
W0902 21:18:45.546008 67477504 init.cc:217]     @        0x10058f158 _PyEval_EvalFrameDefault
W0902 21:18:45.546480 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.546705 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.546906 67477504 init.cc:217]     @        0x100591337 call_function
W0902 21:18:45.547096 67477504 init.cc:217]     @        0x10058f158 _PyEval_EvalFrameDefault
W0902 21:18:45.547278 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.547480 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.548012 67477504 init.cc:217]     @        0x100591337 call_function
W0902 21:18:45.548411 67477504 init.cc:217]     @        0x10058e0cb _PyEval_EvalFrameDefault
W0902 21:18:45.548733 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.549108 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.549561 67477504 init.cc:217]     @        0x100591337 call_function
W0902 21:18:45.550117 67477504 init.cc:217]     @        0x10058f158 _PyEval_EvalFrameDefault
W0902 21:18:45.550366 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.550580 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.550776 67477504 init.cc:217]     @        0x100591337 call_function
W0902 21:18:45.550967 67477504 init.cc:217]     @        0x10058f158 _PyEval_EvalFrameDefault
W0902 21:18:45.551154 67477504 init.cc:217]     @        0x100582a4e _PyEval_EvalCodeWithName
W0902 21:18:45.551386 67477504 init.cc:217]     @        0x1004535d3 _PyFunction_FastCallKeywords
W0902 21:18:45.551882 67477504 init.cc:217]     @        0x100591337 call_function

不知道有没有朋友遇到过类似的问题，这个问题的原因是什么？怎么解决呢？

**Comment by littletomatodonkey** [comment]
你好，可以先使用下面的python代码测试下Paddle是否安装成功
```
import paddle.fluid
paddle.fluid.install_check.run_check()
```
没问题的话，可以试着减小训练的batch size，看下是否可以正常运行，CPU上batch size可能没法设置的太大

**Comment by luo693353634** [comment]
是安装成功的，似乎和batch size没有关系，我尝试在yml中把train_batch_size_per_card改小了，但还是出现相同的错误。

**Comment by littletomatodonkey** [comment]
那麻烦把训练脚本和详细报错的日志信息写在文本里，发上来吧~

**Comment by luo693353634** [comment]
[报错.pdf](https://github.com/PaddlePaddle/PaddleOCR/files/5166307/default.pdf)

**Comment by luo693353634** [comment]
其他和训练相关的Python脚本是没有修改过的

**Comment by littletomatodonkey** [comment]
你把bs减小到4呢？也不行吗？Paddle版本试下1.7.1呢？

**Comment by luo693353634** [comment]
我试一试1.7.1吧，bs改成1也是没有用的。

**Comment by luo693353634** [comment]
似乎还是不行，报错也是一样的
