### ISSUE TITLE
Many words/characters missing in chinese image ocr

### ISSUE THREAD

**Issue by sasumay** [PaddlePaddle/PaddleOCR#6601]
Please provide the following information to quickly locate the problem

- System Environment：Ubuntu 20.0.4
- Version：Paddle：  PaddleOCR： 2.5.0.3
- Command Code：
ocr = PaddleOCR(lang='ch')
result = ocr.ocr(result,  det=True)
- Complete Error Message：
Many words/characters are missing and accuracy is very low. I tried to do some image preprocessing like sharpen edges but it didn't help. Download source tif from - https://github.com/sasumay/paddle-test/blob/main/chinese_accuracy_issue.tif?raw=true

![chinese_accuracy](https://user-images.githubusercontent.com/107453404/173982496-d303d533-950f-4a19-87f3-39fb5e7701be.png)

**Comment by LDOUBLEV** [comment]
It is recommended to use a Japanese recognition model instead of a Chinese recognition model to recognize Japanese data.
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_en/multi_languages_en.md

**Comment by sasumay** [comment]
I am very sorry. The image I received had Chinese in the file name. I apologize for the confusion.
