### ISSUE TITLE
NotFoundError: Operator (transpose2) does not have kernel for data_type[double]:data_layout

### ISSUE THREAD

**Issue by dtiny** [PaddlePaddle/PaddleOCR#6608]
paddleOcr 版本：2.1
开发语言：c++
训练算法：starnet_r34_vd_tps_bilstm_ctc.yml
训练语言：python
模型导出：参考python3 tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_ctc.yml -o Global.pretrained_model=./rec_r34_vd_tps_bilstm_ctc_v2.0_train/best_accuracy  Global.save_inference_dir=./inference/rec_starnet
不同点在于我训练的时候使用图片输入尺寸为[3,24,192]，可以不报异常导出模型参数。
python推理测试：使用导出模型参数可以正确得到推理结果。
c++推理：按照demo，更改了输入尺寸为[3,24,192]，模型的初始化，数据处理都正常，但在执行this->predictor_->Run()这句时候保存。错误信息如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator (transpose2) does not have kernel for data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:1236)
  [operator < transpose2 > error]
Aborted (core dumped)

需要其他信息我再补充！
望帮助解答，谢谢！

**Comment by LDOUBLEV** [comment]
可以发一下你转之后的inference model吗

**Comment by dtiny** [comment]
可以，怎么发给你，邮箱吗

**Comment by dtiny** [comment]
导出模型通过附件发你了，另外也附上了转onnx错误信息。
望帮助解答，谢谢！










在 2022-06-16 17:34:21，"Double_V" ***@***.***> 写道：

可以发一下你转之后的inference model吗

**Comment by dtiny** [comment]
在 2022-06-16 17:34:21，"Double_V" ***@***.***> 写道：

可以发一下你转之后的inference model吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
r34_vd_tps_bilstm_ctc - 复件.zip (107.11M, 2022年7月2日 15:10 到期)
下载

**Comment by wanggoudanscd** [comment]
我转模型也遇到了这个问题，请问怎么解决的
