### ISSUE TITLE
 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by li-an-sheng** [PaddlePaddle/PaddleOCR#661]
运行 测试 python3 tools/infer/predict_system.py --image_dir="ce.png" --dt_model_dir="./models/det/"  --rec_model_dir="./models/re/" 出现  Segmentation fault (core dumped)  希望能得到您的帮助

**Comment by littletomatodonkey** [comment]
你好，可以先使用下面的python代码测试下Paddle是否安装成功
```
import paddle.fluid
paddle.fluid.install_check.run_check()
```

如果没问题的话，麻烦提供下具体的Paddle版本，是否使用了GPU以及详细的报错日志信息吧

**Comment by li-an-sheng** [comment]
> 你好，可以先使用下面的python代码测试下Paddle是否安装成功
> 
> ```
> import paddle.fluid
> paddle.fluid.install_check.run_check()
> ```
> 
> 如果没问题的话，麻烦提供下具体的Paddle版本，是否使用了GPU以及详细的报错日志信息吧
您好 这是运行 paddle.fluid.install_check.run_check()的结果
Running Verify Fluid Program ...
W0903 14:00:49.051525  9225 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
W0903 14:00:49.053987  9225 device_context.cc:260] device: 0, cuDNN Version: 8.0.
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0903 14:00:56.705932  9225 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
Paddle的版本为 ：
>>> print( paddle.__version__ )
1.8.1
并且使用了 GPU 
![image](https://user-images.githubusercontent.com/57883284/92080877-cae48b00-edf4-11ea-8b25-a0e9d425500a.png)

**Comment by MissPenguin** [comment]
可以参考这里的解决方法：https://github.com/PaddlePaddle/PaddleOCR/issues/466
