### ISSUE TITLE
ocr 检测和识别

### ISSUE THREAD

**Issue by lishiyuhebei** [PaddlePaddle/PaddleOCR#6610]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.2  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained
- 完整报错/Complete Error Message：
- 没有报错，可以看到loss 在减少，但是python tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./train_data/ic2015/text_localization/img/LK6ADAE1XNB191382.png" Global.pretrained_model="output/db_mv3_69/latest"
- 基本检测不到文本，
- 另外使用sar 做文字识别也效果很差

**Comment by LDOUBLEV** [comment]
用Global.pretrained_model="output/db_mv3_69/best_model" 呢?
latest是保存的最新模型，而不是最优模型

另外，你训练的最优精度是多少？如果训练的精度低，模型预测效果不会太好

**Comment by lishiyuhebei** [comment]
最优精度不太记得 但是我看 loss 是一直在降低 ，last 不是最优的 也应该不会太差啊 best_model 也是一样的效果  最优精度指的是那个参数
