### ISSUE TITLE
ppocr端侧推理时挂掉， Abort message: '[F  6/16 17:20:19.445 .../Paddle-Lite2.10/lite/core/program.cc:688 Run] Check failed: kernel_: kernel null

### ISSUE THREAD

**Issue by wangwh0128** [PaddlePaddle/PaddleOCR#6613]
ppocr端侧推理时挂掉， Abort message: '[F  6/16 17:20:19.445 .../Paddle-Lite2.10/lite/core/program.cc:688 Run] Check failed: kernel_: kernel null， 帮忙看看怎么回事？

**Comment by LDOUBLEV** [comment]
用的模型和环境是？

自测在paddlelite2.10 + PPOCRv2模型在android 骁龙855上 能正常预测，

**Comment by woailangya** [comment]
我也遇到这个问题，大多数时候，进入这个页面都是正常使用，偶尔出现退出这个页面时报：
A/Paddle-Lite: [F 6/23 12:15:21.332 ...20/lite/Paddle-Lite/lite/core/program.cc:688 Run] Check failed: kernel_: kernel null
--------- beginning of crash
2022-06-23 12:15:21.333 22697-23904/com.xuexiang.mashangproject A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23904 (Thread-266), pid 22697 (.mashangproject)

使用的版本：
paddle_lite_libs_v2_10
opencv-4.2.0-android-sdk
ch_PP-OCRv2
dygraph_v2.0
测试手机华为p30
