### ISSUE TITLE
现在PPOCRv3 支持在Paddlelite 安卓端侧推理吗

### ISSUE THREAD

**Issue by zhang0227** [PaddlePaddle/PaddleOCR#6619]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：安卓12 骁龙888
- 版本号/Version： PaddleOCR：2.5 PaddleLite 2.10
模型为ppocr官网直接下载的v3 nb格式模型，预测库为2.10 release inference_lite_lib.android.armv8.gcc.c++_shared.with_extra.with_cv

报错/Paddle-Lite: [F  6/17 14:14:10.792 ...CR/lite/Paddle-Lite/lite/core/program.cc:264 RuntimeProgram] Check failed: (kernels.size() > 0): 0!>0 
    Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.

**Comment by LDOUBLEV** [comment]
如果要在端侧使用PPOCRv3模型，需要修改识别的预处理代码为V3的预处理代码，并设置识别模型的rec_image_shape为3，48，320，参考cpp预测：https://github.com/PaddlePaddle/PaddleOCR/blob/f0d0dfea04dba79b1a4823b86b9d7899ec0fe564/deploy/cpp_infer/src/preprocess_op.cpp#L98-L121
如果不改代码，直接预测不会报错，但是识别效果会差一些

 'io_copy' is not supported by Paddle-Lite.
这个报错像是转模型的问题，你下载paddlelite,2.10版本的opt工具，确保paddleliteopt工具和你的预测库版本匹配，重新转nb模型试试。

**Comment by zhang0227** [comment]
> 如果要在端侧使用PPOCRv3模型，需要修改识别的预处理代码为V3的预处理代码，并设置识别模型的rec_image_shape为3，48，320，参考cpp预测：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/f0d0dfea04dba79b1a4823b86b9d7899ec0fe564/deploy/cpp_infer/src/preprocess_op.cpp#L98-L121
> 
> 
> 如果不改代码，直接预测不会报错，但是识别效果会差一些
> 'io_copy' is not supported by Paddle-Lite. 这个报错像是转模型的问题，你下载paddlelite,2.10版本的opt工具，确保paddleliteopt工具和你的预测库版本匹配，重新转nb模型试试。

自己用opt转nb模型之后可以了，之前用的是仓库直接下载的nb模型。
还有一个问题是paddlelite预编译库文件只有libpaddle_api_light_bundled.a libpaddle_light_api_shared.so，在安卓demo里 在build时从网络下载的paddlite库里面的hiai库和c++shared 是从哪里能得到呢？与paddlelite库的版本对应情况又是怎么样的

**Comment by denonzhu** [comment]
还是报错啊
`const std::vector<int> REC_IMAGE_SHAPE = {3, 48, 320};

cv::Mat crnn_resize_img(const cv::Mat &img, float wh_ratio) {
    int imgC = REC_IMAGE_SHAPE[0];
    int imgW = REC_IMAGE_SHAPE[2];
    int imgH = REC_IMAGE_SHAPE[1];

    imgW = int(imgH * wh_ratio);


    float ratio = float(img.cols) / float(img.rows);
    int resize_w = 0;
    if (ceilf(imgH * ratio) > imgW)
        resize_w = imgW;
    else
        resize_w = int(ceilf(imgH * ratio));
    cv::Mat resize_img;
    cv::resize(img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f,
               cv::INTER_LINEAR);
    cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                       int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                       {127, 127, 127});

    return resize_img;
}`

![image](https://user-images.githubusercontent.com/5187679/174543759-610f7d42-e2dd-4006-90c6-dfde2d3f5b23.png)

**Comment by twinklelucas** [comment]
> 



> > 如果要在端侧使用PPOCRv3模型，需要修改识别的预处理代码为V3的预处理代码，并设置识别模型的rec_image_shape为3，48，320，参考cpp预测：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/f0d0dfea04dba79b1a4823b86b9d7899ec0fe564/deploy/cpp_infer/src/preprocess_op.cpp#L98-L121
> > 
> > 如果不改代码，直接预测不会报错，但是识别效果会差一些
> > 'io_copy' is not supported by Paddle-Lite. 这个报错像是转模型的问题，你下载paddlelite,2.10版本的opt工具，确保paddleliteopt工具和你的预测库版本匹配，重新转nb模型试试。
> 
> 自己用opt转nb模型之后可以了，之前用的是仓库直接下载的nb模型。 还有一个问题是paddlelite预编译库文件只有libpaddle_api_light_bundled.a libpaddle_light_api_shared.so，在安卓demo里 在build时从网络下载的paddlite库里面的hiai库和c++shared 是从哪里能得到呢？与paddlelite库的版本对应情况又是怎么样的

老哥，你转的nb模型可以发我一份吗，或者告诉我哪里下载，邮箱：448463700@qq.com

**Comment by LDOUBLEV** [comment]
> 还有一个问题是paddlelite预编译库文件只有libpaddle_api_light_bundled.a libpaddle_light_api_shared.so，在安卓demo里 在build时从网络下载的paddlite库里面的hiai库和c++shared 是从哪里能得到呢？与paddlelite库的版本对应情况又是怎么样的

其实就是libpaddle_light_api_shared.so ，如果名字对不上，重命名就行；paddlelite2.9-2.10版本，使用paddlelite编译得到的动态库名字可能是*_c++_shared.so

**Comment by LDOUBLEV** [comment]
@denonzhu  发一下你的报错信息

**Comment by zhang0227** [comment]
> > 
> 
> > > 如果要在端侧使用PPOCRv3模型，需要修改识别的预处理代码为V3的预处理代码，并设置识别模型的rec_image_shape为3，48，320，参考cpp预测：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/f0d0dfea04dba79b1a4823b86b9d7899ec0fe564/deploy/cpp_infer/src/preprocess_op.cpp#L98-L121
> > > 
> > > 如果不改代码，直接预测不会报错，但是识别效果会差一些
> > > 'io_copy' is not supported by Paddle-Lite. 这个报错像是转模型的问题，你下载paddlelite,2.10版本的opt工具，确保paddleliteopt工具和你的预测库版本匹配，重新转nb模型试试。
> > 
> > 
> > 自己用opt转nb模型之后可以了，之前用的是仓库直接下载的nb模型。 还有一个问题是paddlelite预编译库文件只有libpaddle_api_light_bundled.a libpaddle_light_api_shared.so，在安卓demo里 在build时从网络下载的paddlite库里面的hiai库和c++shared 是从哪里能得到呢？与paddlelite库的版本对应情况又是怎么样的
> 
> 老哥，你转的nb模型可以发我一份吗，或者告诉我哪里下载，邮箱：[448463700@qq.com](mailto:448463700@qq.com)

你自己pip安装一个paddle_lite_opt 就能从inference模型转成nb了，注意版本。

**Comment by denonzhu** [comment]
> 这个就是报错

![image](https://user-images.githubusercontent.com/5187679/174710920-c7d3ace9-3c4c-478b-a903-4124f218248f.png)

**Comment by TonyJiangWJ** [comment]
@zhang0227 请问你有试过v3 slim的模型吗 
我使用官方的nb和自己opt转的nb都不能正常使用，识别全是错误的结果。v3非slim模型是正常的，另外v2 slim也能正常使用

**Comment by zhang0227** [comment]
> @zhang0227 请问你有试过v3 slim的模型吗 我使用官方的nb和自己opt转的nb都不能正常使用，识别全是错误的结果。v3非slim模型是正常的，另外v2 slim也能正常使用

没试过slim，是怎么slim的我试试

**Comment by TonyJiangWJ** [comment]
从这个地址的模型列表下载: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md
- ch_PP-OCRv3_det_slim
- ch_PP-OCRv3_rec_slim
- ch_ppocr_mobile_slim_v2.0_cls

带slim后缀的就是slim量化的模型，试过v2版slim模型在移动端速度比非slim的快，准确率也不错。
我测试下来感觉v3 slim模型主要是rec有问题 det框选是没问题的

**Comment by zhang0227** [comment]
> 从这个地址的模型列表下载: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md
> 
> * ch_PP-OCRv3_det_slim
> * ch_PP-OCRv3_rec_slim
> * ch_ppocr_mobile_slim_v2.0_cls
> 
> 带slim后缀的就是slim量化的模型，试过v2版slim模型在移动端速度比非slim的快，准确率也不错。 我测试下来感觉v3 slim模型主要是rec有问题 det框选是没问题的

我下载slim推理模型自己转成nb用是正常的。你改成v3的前处理了吗

**Comment by TonyJiangWJ** [comment]
我仿照上面的 `preprocess_op.cpp` 修改了 `ocr_crnn_process.cpp` 不知道是不是哪里改的不对？
```c++
// line: 25
const std::vector<int> REC_IMAGE_SHAPE = {3, 48, 320};
// line: 65+
cv::Mat crnn_resize_img(const cv::Mat &img, float wh_ratio) {
  int imgC, imgH, imgW;
  imgC = REC_IMAGE_SHAPE[0];
  imgH = REC_IMAGE_SHAPE[1];
  imgW = REC_IMAGE_SHAPE[2];

  imgW = int(imgH * wh_ratio);

  float ratio = float(img.cols) / float(img.rows);
  int resize_w, resize_h;

  if (ceilf(imgH * ratio) > imgW)
    resize_w = imgW;
  else
    resize_w = int(ceilf(imgH * ratio));

  cv::Mat resize_img;
  cv::resize(img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f,
             cv::INTER_LINEAR);
  cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                     int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                     {127, 127, 127});
  return resize_img;
}
```

**Comment by TonyJiangWJ** [comment]
我好像知道了，我拿2.11版的opt工具转换的slim模型所以没法正常使用 改成2.10版的opt工具进行转换就正常了 非常感谢

**Comment by bsse9803** [comment]
> 
Oh! I solved!!  I hadn't converted detection model. I just had downloaded .nb file on the link(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md).
But, I downloaded inference model(Detection) and then converted model to .nb file and upload, i can get the inference results.
Thank you!!

**Comment by bsse9803** [comment]
> I trained OCR model based the PP-OCRv3_rec model, and converted .nb file using Paddle-Lite v2.10. I tryed to upload for Android Studio Emulator. I successed uploading! But, There are no inference results. How can i solve the problem? To solve my issue, do you need other information about my environment?

Oh! I solved!!  I hadn't converted detection model. I just had downloaded .nb file on the link(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md).
But, I downloaded inference model(Detection) and then converted model to .nb file and upload, i can get the inference results.
Thank you!!

**Comment by shekarneo** [comment]
> 还是报错啊,相关代码已经改成这样了
> 
> ```
> const std::vector<int> REC_IMAGE_SHAPE = {3, 48, 320};
> 
> cv::Mat crnn_resize_img(const cv::Mat &img, float wh_ratio) {
>     int imgC = REC_IMAGE_SHAPE[0];
>     int imgW = REC_IMAGE_SHAPE[2];
>     int imgH = REC_IMAGE_SHAPE[1];
> 
>     imgW = int(imgH * wh_ratio);
> 
> 
>     float ratio = float(img.cols) / float(img.rows);
>     int resize_w = 0;
>     if (ceilf(imgH * ratio) > imgW)
>         resize_w = imgW;
>     else
>         resize_w = int(ceilf(imgH * ratio));
>     cv::Mat resize_img;
>     cv::resize(img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f,
>                cv::INTER_LINEAR);
>     cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
>                        int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
>                        {127, 127, 127});
> 
>     return resize_img;
> }
> ```
> 
> 报错如下： ![image](https://user-images.githubusercontent.com/5187679/174543759-610f7d42-e2dd-4006-90c6-dfde2d3f5b23.png)

Hi Did you solved the issue, I am also facing same error.

**Comment by ppppppppyyyy** [comment]
> @zhang0227 请问你有试过v3 slim的模型吗 我使用官方的nb和自己opt转的nb都不能正常使用，识别全是错误的结果。v3非slim模型是正常的，另外v2 slim也能正常使用

v3识别 slim模型，是这样吗？
![image](https://user-images.githubusercontent.com/58112895/191443848-f62dea12-3e2b-4b45-bc5e-b82d43da41fb.png)

**Comment by ppppppppyyyy** [comment]
> 我好像知道了，我拿2.11版的opt工具转换的slim模型所以没法正常使用 改成2.10版的opt工具进行转换就正常了 非常感谢

为什么我的识别结果不正常？
![image](https://user-images.githubusercontent.com/58112895/191459284-f11ee1f9-ecc4-488a-98b4-7d4316cb45d1.png)

**Comment by ppppppppyyyy** [comment]
> 我好像知道了，我拿2.11版的opt工具转换的slim模型所以没法正常使用 改成2.10版的opt工具进行转换就正常了 非常感谢

我的识别结果还是不正常...
![image](https://user-images.githubusercontent.com/58112895/191459535-ac4ffa4e-e899-4d6c-8857-b453f9e825cf.png)

**Comment by simpsonyang** [comment]
> 我好像知道了，我拿2.11版的opt工具转换的slim模型所以没法正常使用 改成2.10版的opt工具进行转换就正常了 非常感谢

我用2.10的opt工具转换slim模型，但是运行android demo仍然报错，能不能分享下你是怎么做的？
