### ISSUE TITLE
 采用export_model导出文字检测模型精度下降

### ISSUE THREAD

**Issue by hjm0613** [PaddlePaddle/PaddleOCR#6620]
采用export_model.py导出自己训练的文字检测模型后，predict.py进行目标的检测，发现检测率几乎为零；而没有模型导出直接采用infer.py进行预测，文字的检测率非常的高，请问这是什么原因呢？

**Comment by jingmingtao** [comment]
请问你解决了吗，他们为啥不回答你呢

**Comment by cyj02132654** [comment]
同问
