### ISSUE TITLE
文本识别测试集识别效果较差

### ISSUE THREAD

**Issue by UBUNTUHWB** [PaddlePaddle/PaddleOCR#6621]
使用开源文档数据进行训练，然后自己采集真实文档数据进行测试
1.使用开源文档数据进行训练，验证集为97.9%
但是真实文档测试数据存在字符漏识别以及模糊字符不能识别情况。
请问是什么问题

**Comment by Vergissmeinnic** [comment]
我和你一样的情况，我训练acc0.99以上，eval的acc也是0.99以上，拿模型直接推理的效果特别差，大概40%

**Comment by UBUNTUHWB** [comment]
可能还是需要自己重新拍摄文档数据集加入训练

**Comment by UBUNTUHWB** [comment]
可能还是需要自己重新拍摄文档数据集加入训练
