### ISSUE TITLE
识别报错

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#6628]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11家庭
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.3.0  ，2.5
- 运行指令/Command Code：python tools/train.py -c configs/rec/rec_mv3_none_bilstm_ctc.yml
- 完整报错/Complete Error Message：
- RuntimeError: (PreconditionNotMet) warp-ctc [version 2] Error in get_workspace_size: execution failed
  [Hint: Expected CTC_STATUS_SUCCESS == status, but received CTC_STATUS_SUCCESS:0 != status:3.] (at ../paddle/phi/kernels/impl/warpctc_kernel_impl.h:199)
  [operator < warpctc > error]

**Comment by BradXiao** [comment]
For a workaround solution under gpu training environments,
Modify:
```python
loss=paddle.nn.CTCLoss(xxx)
```
To:
```python
paddle.device.set_device('cpu')
loss=paddle.nn.CTCLoss(xxx)  
paddle.device.set_device('gpu')  
```

**Comment by chc-stars** [comment]
thanks，It has been solved
