### ISSUE TITLE
SVTR 移动端部署

### ISSUE THREAD

**Issue by xireli** [PaddlePaddle/PaddleOCR#6629]
训了一个SVTR模型，导出模型时候看文档写着“由于C++预处理后处理还未支持SVTR，所以暂未支持” 意思是，暂时不能移动端部署是吗？移动端部署重新训CRNN模型吗？

**Comment by andyjpaddle** [comment]
嗯嗯，SVTR目前还不支持移动端部署，但是支持正常的Python推理，如果需要使用移动端部署，可以先用CRNN模型
