### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

### ISSUE THREAD

**Issue by jackeylu** [PaddlePaddle/PaddleOCR#663]
https://github.com/PaddlePaddle/PaddleOCR/blob/21af7660b5328de726312c61e2266695558a803d/docker/hubserving/cpu/Dockerfile#L11

git clone下来的路径不在 /PaddleOCR，导致后续安装依赖报错。
https://github.com/PaddlePaddle/PaddleOCR/blob/21af7660b5328de726312c61e2266695558a803d/docker/hubserving/cpu/Dockerfile#L15

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'
```

建议修改clone的命令，直接下载到/PaddleOCR目录。

**Comment by yuanzicheng** [comment]
change "WORKDIR /PaddleOCR" to "WORKDIR /home/PaddleOCR"

**Comment by Jitesh4389** [comment]
Step 1/14 : FROM hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev
 ---> b6437d2ae45e
Step 2/14 : RUN pip3.7 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
 ---> Using cache
 ---> 342d1242664e
Step 3/14 : RUN python3.7 -m pip install paddlepaddle==1.7.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
 ---> Using cache
 ---> 71b77d6e80db
Step 4/14 : RUN pip3.7 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple
 ---> Using cache
 ---> 122b55fa0bf5
Step 5/14 : RUN git clone https://gitee.com/PaddlePaddle/PaddleOCR
 ---> Using cache
 ---> 88e8721a4d15
Step 6/14 : WORKDIR  /home/PaddleOCR
 ---> Using cache
 ---> a9166b643d38
Step 7/14 : RUN pip3.7 install -r requirments.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
 ---> Running in cbbe4eaac130
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

after change path give error
