### ISSUE TITLE
表格识别训练数据

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6633]
表格识别训练数据格式是怎样的，哪些是必要字段，哪些不是必要字段，每个字段的含义是什么

**Comment by ZTurboX** [comment]
好未来数据样例如下，如果自己构造数据， structure字段是必须的吗
{"filename":` "1621871735627846536945182109696_0.jpg", 
"html": {"cells": [{"bbox": [[10, 6], [125, 7], [128, 33], [9, 33]], "tokens": "柳树"}, {"bbox": [[125, 7], [237, 6], [242, 32], [128, 33]], "tokens": "松树"}, {"bbox": [[237, 7], [347, 5], [357, 30], [243, 32]], "tokens": "杨树"}, {"bbox": [[10, 33], [128, 33], [131, 54], [9, 53]], "tokens": "1300棵"}, {"bbox": [[128, 34], [243, 32], [250, 52], [131, 53]], "tokens": "700棵"}, {"bbox": [[243, 32], [357, 30], [367, 50], [250, 52]], "tokens": "800棵"}], 
 "structure": {"tokens": ["<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "gt": "<html><body><table><tr><td>柳树</td><td>松树</td><td>杨树</td></tr><tr><td>1300棵</td><td>700棵</td><td>800棵</td></tr></table></body></html>"},  "image_id": 3358, "split": "train"}

**Comment by mingo-doer** [comment]
structure 是必须的

**Comment by littletomatodonkey** [comment]
你好，可以参考这个文档看下：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppstructure/table/README_ch.md

**Comment by ZTurboX** [comment]
> 你好，可以参考这个文档看下：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppstructure/table/README_ch.md

表格标注好的数据，只有坐标，如何转成structure 中html格式

**Comment by WenmuZhou** [comment]
可以使用这个文件https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/table/convert_label2html.py
