### ISSUE TITLE
利用PPOCRv3训练印章检测，从哪里找公开的训练集和验证集

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleOCR#6639]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：v3
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：
利用PPOCRv3训练印章检测，从哪里找公开的训练集和验证集？

**Comment by littletomatodonkey** [comment]
你好，可以试着合成一批看看

**Comment by lixiangMindSpore** [comment]
> 你好，可以试着合成一批看看

您好，如何合成？具体什么方法？谢谢您

**Comment by LDOUBLEV** [comment]
建议从网上找一些真实数据，可以用PPOCRLabel工具来标注：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/PPOCRLabel

**Comment by LDOUBLEV** [comment]
在网上找了一个网站，可以生成印章类型的数据：http://www.395.net.cn/
@lixiangMindSpore
