### ISSUE TITLE
混合精度训练速度没什么变化

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleOCR#6641]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by dlkht** [comment]
我是按照这个指令训练的
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/recognition.md （“2.4 混合精度训练")
但发现训练速度没有加快，内存也差不多，是不是还要设置什么参数或修改代码呢？
我使用的是显卡是 Tesla P100-SXM2，有FP16功能

**Comment by littletomatodonkey** [comment]
你好，轻量级模型确实fp16的加速性能一般
