### ISSUE TITLE
基于PaddleServing 的 PPOCR 服务化部署，使用 pipeline部署方式宿主机访问不了推理服务

### ISSUE THREAD

**Issue by self-discipline-zhu** [PaddlePaddle/PaddleOCR#6643]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10，docker desktop v20.10.16
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.5

按照以下文档进行部署测试：[PPOCR 服务化部署](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md)

使用 pipeline 方式运行服务端，如下所示，可以正常运行服务，其中 config.yml 使用默认内容未修改
```
python3 web_service.py --config=config.yml
```
在容器内调用测试，也可以进行正常推理
```
python3 pipeline_http_client.py
```
### 问题
宿主机无法访问上述部署的推理服务，命令行查看配置文件中的端口占用但并没有任何数据返回
![image](https://user-images.githubusercontent.com/83965176/174566372-3cf52c23-8200-4ca2-a9a2-52acd826ac96.png)

**Comment by littletomatodonkey** [comment]
你好，建议再检查下端口是否被占用或者指定正确

**Comment by zhuzhengqiang317** [comment]
> 你好，建议再检查下端口是否被占用或者指定正确

好的，我试一下从Linux系统装吧

**Comment by zhuzhengqiang317** [comment]
> 你好，建议再检查下端口是否被占用或者指定正确
在 win10 环境下使用 docker 运行镜像时使用 `--network=host` 无法检测到端口，而使用 `-p` 参数指定端口时可以

**Comment by tink2123** [comment]
1. http 请求可参考文档：https://github.com/PaddlePaddle/Serving/blob/e5d6f23c206c2cba3dae998a517c2cfb8c89e06c/doc/Offical_Docs/5-4_HTTP_API_CN.md#L3
2. 多语言模型需要启动多个服务，目前语种和识别模型是意义对应的。
3. --network=host 无法检测到端口，而使用 -p 参数指定端口时可以。 这个问题解决了嘛？

**Comment by zhuzhengqiang317** [comment]
> 1. http 请求可参考文档：https://github.com/PaddlePaddle/Serving/blob/e5d6f23c206c2cba3dae998a517c2cfb8c89e06c/doc/Offical_Docs/5-4_HTTP_API_CN.md#L3
> 2. 多语言模型需要启动多个服务，目前语种和识别模型是意义对应的。
> 3. --network=host 无法检测到端口，而使用 -p 参数指定端口时可以。 这个问题解决了嘛？

Http 请求访问问题已经解决了，是我给的 data 数据不对导致的。至于 `--network=host 无法检测到端口` 的问题并未解决，目前使用 -p 参数进行部署的
