### ISSUE TITLE
fcenet error

### ISSUE THREAD

**Issue by justcodew** [PaddlePaddle/PaddleOCR#6646]
想要fcenet来测试一下弯取文本的检测效果，数据集为icdar2015时，训练正常。但换成 ICDAR2019-ArT数据集时，
训练会报如下的错误：
error happened with msg: Traceback (most recent call last):
  File "/home/code/PaddleOCR/ppocr/data/simple_dataset.py", line 136, in __getitem__
    outs = transform(data, self.ops)
  File "/home/code/PaddleOCR/ppocr/data/imaug/__init__.py", line 50, in transform
    data = op(data)
  File "/home/code/PaddleOCR/ppocr/data/imaug/fce_targets.py", line 662, in __call__
    results = self.generate_targets(results)
  File "/home/code/PaddleOCR/ppocr/data/imaug/fce_targets.py", line 649, in generate_targets
    polygon_masks_ignore)
  File "/home/code/PaddleOCR/ppocr/data/imaug/fce_targets.py", line 608, in generate_level_targets
    level_img_size, lv_text_polys[ind])[None]
  File "/home/code/PaddleOCR/ppocr/data/imaug/fce_targets.py", line 333, in generate_center_region_mask
    center_line = (resampled_top_line + resampled_bot_line) / 2
ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

ICDAR2019-ArT数据集标注有可视化看过，没有问题。估计是代码这里有点问题，貌似是从mmocr转过来的。

可以帮忙看一下吗

**Comment by justcodew** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/data/imaug/fce_targets.py#L110
这里代码不够鲁棒，一些数据会越界的现象。
`            while current_line_len >= length_cumsum[current_edge_ind + 1]:
                current_edge_ind += 1`
改为
`            while (current_edge_ind + 1 < len(length_cumsum)) and (current_edge_ind < len(length_list)) :
                if current_line_len >= length_cumsum[current_edge_ind + 1] :
                    current_edge_ind += 1`

**Comment by WenmuZhou** [comment]
能否提供越界的具体case

**Comment by justcodew** [comment]
/train/img/gt_1807.jpg	[{"transcription": "中国少林武术培训", "points": [[26, 445], [95, 330], [231, 248], [417, 248], [515, 311], [614, 467], [542, 497], [491, 403], [397, 338], [274, 336], [186, 398], [104, 491]], "language": "Chinese", "illegibility": false}, {"transcription": "报名热线： 15221362588", "points": [[165, 455], [481, 462], [482, 489], [165, 485]], "language": "Chinese", "illegibility": false}, {"transcription": "021-20983256", "points": [[307, 490], [481, 490], [484, 513], [309, 512]], "language": "Latin", "illegibility": false}, {"transcription": "少林武术", "points": [[335, 658], [364, 655], [373, 779], [342, 783]], "language": "Chinese", "illegibility": false}]
![gt_1807](https://user-images.githubusercontent.com/107862224/175476484-2f34de9c-c467-455d-9423-a0617e9ab294.jpg)

**Comment by WenmuZhou** [comment]
收到

**Comment by WenmuZhou** [comment]
看起来和数据集里点的数量不一致有关，可以试一下将点都pad到一样的数量

**Comment by WenmuZhou** [comment]
你好，这张case，我这边测试正常的
<img width="731" alt="image" src="https://user-images.githubusercontent.com/12406017/175488230-0be2d4d0-03c0-4f24-92d3-9837928911d9.png">

**Comment by justcodew** [comment]
我用的就是这张图片，测试时有时正常，有时会报错。测试代码如下

```
import numpy as np
from paddle.io import  DataLoader, BatchSampler
from ppocr.data.simple_dataset import SimpleDataSet
from ppocr.utils.loggers import VDLLogger
import yaml
import random
import paddle
from ppocr.utils.logging import get_logger

def set_seed(seed=1024):
    random.seed(seed)
    np.random.seed(seed)
    paddle.seed(seed)

def build_dataloader(mode, batch_size, drop_last, shuffle, num_workers):
    # dataset = SimpleDataSet(config,mode, logger, seed=0.5)
    dataset = SimpleDataSet(config,mode, logger,seed=None)
    batch_sampler = BatchSampler(dataset=dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last)
    data_loader = DataLoader(dataset=dataset, batch_sampler=batch_sampler, num_workers=num_workers, return_list=True, use_shared_memory=False)
    return data_loader

if __name__ == '__main__':

    save_model_dir = './test_data/'
    loggers = VDLLogger(save_model_dir)
    log_file = './test_data/test_data_0607.log' 
    logger = get_logger(log_file=log_file)

    config_file = r'/home/justcodew/code/PaddleOCR/configs/det/det_r50_vd_dcn_fce_art_error.yml'
    config =  yaml.load(open(config_file, 'rb'), Loader=yaml.Loader)
    seed = config['Global']['seed'] if 'seed' in config['Global'] else 1024
    set_seed(seed)

    train_dataloader = build_dataloader('Train', batch_size=1, drop_last=False, shuffle=False, num_workers=1)

    for indx, data in enumerate(train_dataloader):
        print('indx ',indx)

```

**Comment by WenmuZhou** [comment]
复现了，是一些边界问题，在这里修复了https://github.com/PaddlePaddle/PaddleOCR/pull/6693

**Comment by justcodew** [comment]
此外，这张图在使用dbnet时，shrink_map和threshold_map如下，shrink_map有点不正常，第一个弯曲文本左右部分效果差别比较大
![shrink_map](https://user-images.githubusercontent.com/107862224/175503828-6f2e3561-cab5-48fa-a851-3444c4a1b822.png)
![threshold_map](https://user-images.githubusercontent.com/107862224/175503852-6b6396cf-b885-4cdc-a2ef-f281d2138e29.png)

**Comment by justcodew** [comment]
> 复现了，是一些边界问题，在这里修复了#6693
具体是修改了哪里的代码。
另外，运行代码的随机性是哪里导致的，  已经将参数改为 shuffle: False  drop_last: False batch_size_per_card: 1和seed =None
还是会有时正常 ，有时报错

**Comment by justcodew** [comment]
FCENET数据增广部分有点问题
[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/data/imaug/fce_aug.py#L346](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/data/imaug/fce_aug.py#L346)

RandomCropPolyInstances中的方法可能会造成 results['polys'] 为空
需要加一下判断
```
            if len(valid_masks_list) > 0 :
                results['polys'] = np.array(valid_masks_list)
                results['ignore_tags'] = valid_tags_list

```
