### ISSUE TITLE
光功率计数码管字符识别  text_renderer

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#6647]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.7
- 版本号/Version：PaddlePaddle 2.3.0 问题相关组件/Related components：
- 运行指令/Command Code：
- !python main.py \
    --config example_data/digital_example.py \
    --dataset img \
    --num_processes 2 \
    --log_period 10
- 完整报错/Complete Error Message：
- name 'chn_data' is not defined
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    generator_cfgs = get_cfg(args.config)
  File "/home/aistudio/text_renderer/text_renderer/config/__init__.py", line 202, in get_cfg
    raise RuntimeError(f"Load configs failed: {config_file}")
RuntimeError: Load configs failed: example_data/digital_example.py

<img width="1093" alt="截屏2022-06-20 下午10 09 02" src="https://user-images.githubusercontent.com/53334346/174620266-fd5db26c-bc70-4096-8d2c-2a870ca2bd74.png">

**Comment by littletomatodonkey** [comment]
你好，麻烦给出具体的aistudio链接哈

**Comment by kingkingpang** [comment]
@littletomatodonkey

**Comment by tink2123** [comment]
项目代码已更新，可以再尝试下，或修改 example_data/digital_example.py 文件的82行：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/31891223/175862922-505baf34-e3aa-45b7-a818-fe8236660239.png">

**Comment by kingkingpang** [comment]
@tink2123 
![image](https://user-images.githubusercontent.com/53334346/226782284-99094b7b-d090-4642-b453-dc06253af915.png)

改完了之后是这个样子的。
