### ISSUE TITLE
表格识别使用好未来的数据训练 反而更差了

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#6649]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/28819717/174700373-a3701e29-2168-4783-831a-d40fb1af08d8.png)
看起来像是过拟合了。但是训练数据也混合了pubtab的数据

**Comment by mingo-doer** [comment]
> 好未来的数据，标注的表格框的4个点，并且有很多倾斜的单元格，你训练的时候需要将回归的box改为四点的，然后对pubtab的数据集做对应的box点数修改

所以建议是我把好未来的标注的表格框适当缩放一定比例变成对文字的标注吗？这个的影响大吗？
四点标注我已经修改过了。还是上述的结果

**Comment by WenmuZhou** [comment]
修改之后效果应该不错的，我这边也有训练好未来的数据集，检测框的指标是80+%，你四点标注的改动是改的数据集还是网络

**Comment by mingo-doer** [comment]
> 修改之后效果应该不错的，我这边也有训练好未来的数据集，检测框的指标是80+%，你四点标注的改动是改的数据集还是网络

改的数据集，不过我读取数据的时候把部分图片也按表格区域裁剪了，然后bbox再减掉裁剪后的值，因为好未来有很多非表格的内容，还是说这部分不需要处理？直接改四点训练效果就可以？

**Comment by WenmuZhou** [comment]
数据集需要进行裁剪，然后好未来的box是四个点标注的，需要对网络的回归分支进行修改

**Comment by mingo-doer** [comment]
我是把好未来的改成pubtab格式的，不需要改网络吧？
![image](https://user-images.githubusercontent.com/28819717/174931858-e06cecbd-6773-49d7-aba7-7069c6a61d07.png)

**Comment by WenmuZhou** [comment]
建议改网络，因为好未来很多框都是倾斜的，你这集改为四个点，学到的框不好

**Comment by mingo-doer** [comment]
我的使用场景没有倾斜的框，那是否可以在数据集中剔除倾斜框的数据，也可以达到效果？
加入好未来的数据训练后，和原本pubtab的数据集相比，会有一定的优化吗？

**Comment by WenmuZhou** [comment]
删掉倾斜的话，好未来的就没多少了

**Comment by mingo-doer** [comment]
好吧，谢谢
可以指导一下 在哪里改网络的回归分支吗？

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/modeling/heads/table_att_head.py#L58 
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/data/imaug/label_ops.py#L668

这里的4改为8

**Comment by mingo-doer** [comment]
好的，我去试试，非常感谢

**Comment by yjhtc007** [comment]
> 好的，我去试试，非常感谢

您好，请问您方便分享一下好未来的表格数据吗，貌似好未来比赛的网站已经不能下载数据了

**Comment by mingo-doer** [comment]
> > 好的，我去试试，非常感谢
> 
> 您好，请问您方便分享一下好未来的表格数据吗，貌似好未来比赛的网站已经不能下载数据了

https://aistudio.baidu.com/aistudio/datasetdetail/97270

**Comment by yjhtc007** [comment]
> > > 好的，我去试试，非常感谢
> > 
> > 
> > 您好，请问您方便分享一下好未来的表格数据吗，貌似好未来比赛的网站已经不能下载数据了
> 
> https://aistudio.baidu.com/aistudio/datasetdetail/97270 如果有训练提升可以交流一下 wx 18267162573

嗯嗯，好的，非常感谢哈！！！

**Comment by ZTurboX** [comment]
> > > 好的，我去试试，非常感谢
> > 
> > 
> > 您好，请问您方便分享一下好未来的表格数据吗，貌似好未来比赛的网站已经不能下载数据了
> 
> https://aistudio.baidu.com/aistudio/datasetdetail/97270 如果有训练提升可以交流一下 wx 18267162573

有用过tablebank数据训练过表格模型吗？

**Comment by nissansz** [comment]
为什么训练过程的模型测试时，有的rowspan和colspan会缺失

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/a65310a2-a44f-41e0-a143-e4464b3c5bd7)

![20231022220750](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/88120b5b-4589-4d7e-bd09-3766d3c9f2cc)
