### ISSUE TITLE
paddleocr 检测的训练模型预测结果很好，但转inference后预测，基本检测不到文本

### ISSUE THREAD

**Issue by rebeccajuan** [PaddlePaddle/PaddleOCR#6652]
训练样本和测试样本宽度在300左右，预测是使用默认参数，没有做任何修改

**Comment by rebeccajuan** [comment]
之前用宽度为1920的样本训练并预测，且转inference后预测也都没有问题

**Comment by rebeccajuan** [comment]
目前解决问题：predict_det.py  添加 --det_limit_side_len=736或960 --det_limit_type=min，检测率终于正常了，736的检测率比960高些，因为默认是--det_limit_side_len=960 --det_limit_type=max，当预测样本宽度为300左右时并没有被扩大到960，但训练时是扩大到960后训练的， 配置文件中有默认设置 - EastRandomCropData:  size: [960, 960]，所以，训练和预测的参数必须保持一致，才能检测正常。

**Comment by rebeccajuan** [comment]
问题目前解决方法：
执行：python tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_db_inference_3/student/" --image_dir="./test_data/" --use_gpu=True --det_limit_side_len=736或960 --det_limit_type=min
检测率终于正常了，736的检测率比960高些，因为默认是--det_limit_side_len=960 --det_limit_type=max，当预测样本宽度为300左右时并没有被扩大到960，但训练时是扩大到960后训练的， 配置文件中有默认设置 - EastRandomCropData: size: [960, 960]，所以，训练和预测的参数必须保持一致，才能检测正常。

**Comment by LDOUBLEV** [comment]
如果训练和转inferencemodel的预测结果不一致，可以检查下训练时评估使用的预处理和后处理参数 是否和 inference model预测的预处理参数一致

**Comment by yangy996** [comment]
看看这个
https://blog.csdn.net/YY007H/article/details/125506785
