### ISSUE TITLE
运行python PPOCRLabel.py --lang ch 报错：ImportError: /usr/lib64/libQt5core.so.5:version 'Qt_5.15' not found 

### ISSUE THREAD

**Issue by upcdz** [PaddlePaddle/PaddleOCR#6653]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：cuda10.2 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

运行python PPOCRlabel.py --lang ch

**Comment by Evezerest** [comment]
QT安装问题，建议删除后重装pyqt5
