### ISSUE TITLE
一行中的文本分成多个box依据是什么，怎么调节

### ISSUE THREAD

**Issue by ospfrip** [PaddlePaddle/PaddleOCR#6658]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
检测到的分割图割裂了，在后处理时就有可能分成多个box，可以试试打开膨胀开关use_dilation：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/tools/infer/utility.py#L56
