### ISSUE TITLE
PaddleOCR在cuda devel版本下测试通过，但是在cuda runtime下报错

### ISSUE THREAD

**Issue by cyy0523xc** [PaddlePaddle/PaddleOCR#666]
对应的dockerfile：

- runtime dockerfile：https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/ubuntu18.04-x86_64/runtime/cudnn7/Dockerfile
- devel dockerfile：https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/ubuntu18.04-x86_64/devel/cudnn7/Dockerfile

直接使用devel是可以的，只是镜像会大2G。

**Comment by LDOUBLEV** [comment]
感谢提供这些信息
