### ISSUE TITLE
Segmentation fault on AWS SageMaker jupyter notebook instance

### ISSUE THREAD

**Issue by lorenzobalzani** [PaddlePaddle/PaddleOCR#6660]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： AWS SageMaker
- 版本号/Version: Paddle: 2.3.0 PaddleOCR: 2.5.0.3 问题相关组件/Related components：Python version is 3.7.12
- 运行指令/Command Code：
`wget https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar`
`tar xf en_PP-OCRv3_rec_infer.tar` 
`python3 tools/infer/predict_rec.py --image_dir=".." --rec_model_dir="./en_PP-OCRv3_rec_infer/" --rec_char_dict_path="ppocr/utils/dict/german_dict.txt" --vis_font_path="doc/fonts/german.ttf"`
- 完整报错/Complete Error Message：

```
C++ Traceback (most recent call last):
No stack trace in paddle, may be caused by external reasons.

Error Message Summary:
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1655808980 (unix time) try "date -d @1655808980" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 8212 (TID 0x7f6f010e6740) from PID 0 ***]

Segmentation fault
```

I don't know if for sure it's not a paddle problem. I ran the same script in a local machine and it works just fine as it should do.

**Comment by MissPenguin** [comment]
We haven't tried to run Paddle on the AWS SageMaker platform, so there may be an adaptation problem.😔

**Comment by lorenzobalzani** [comment]
> We haven't tried to run Paddle on the AWS SageMaker platform, so there may be an adaptation problem.😔

Ok, I see. Anyway, thanks for the quick reply! 😉
