### ISSUE TITLE
PPOCRv3的预训练模型只用ICDAR2015数据集训练吗？有没有别的数据集？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleOCR#6668]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
PPOCRv3的预训练模型只用ICDAR2015数据集训练吗？有没有别的数据集？

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
PPOCRv3模型使用的训练集属于内部使用，暂不公开

**Comment by lixiangMindSpore** [comment]
> PPOCRv3模型使用的训练集属于内部使用，暂不公开

印章检测貌似有点问题，如果使用PPOCRv3，需要怎么处理？重新整理印章数据集进行训练么？
![960386a634d0214b9c87fd8e1e8d128](https://user-images.githubusercontent.com/78945582/174981798-553d061e-2dc6-4ff9-bb39-d2532a216c0d.jpg)

**Comment by LDOUBLEV** [comment]
需要重新整理数据训练，目前PPOCR模型不支持印章检测识别，后续准备做，排期中

**Comment by lixiangMindSpore** [comment]
> 需要重新整理数据训练，目前PPOCR模型不支持印章检测识别，后续准备做，排期中

预计划什么时候可以做出来？给个时间节点，多谢
