### ISSUE TITLE
为什么训练卡住不动

### ISSUE THREAD

**Issue by fq19851220** [PaddlePaddle/PaddleOCR#667]
训练一二十分钟就会卡住不动 GPU内存也没有变化
用的rec_icdar15_train.yml
train_batch_size_per_card  改成32了
num_workers 改成1了
multiprocess_reader 改成 return paddle.reader.multiprocess_reader(readers, False, queue_size=20)了

参数
![参数配置](https://user-images.githubusercontent.com/23071537/92098298-a1832980-ee0b-11ea-9335-7b84773c2da1.jpg)
开始GPU
![运行gpu](https://user-images.githubusercontent.com/23071537/92098327-af38af00-ee0b-11ea-9a92-8076af021bed.jpg)
卡住状态
![卡住状态](https://user-images.githubusercontent.com/23071537/92098386-bc559e00-ee0b-11ea-9e0b-c1e3ef5649dc.jpg)
卡住GPU
![卡住gpu](https://user-images.githubusercontent.com/23071537/92098413-c37cac00-ee0b-11ea-9e18-af01856b3af6.jpg)

OS:win10 LTSC X64
python:3.7.0
paddle:1.8.4 GPU
cuda:10.0
cudnn:7.6
Gcard:1050TI 4G

**Comment by LDOUBLEV** [comment]
这个问题是稳定复现的吗，估计和机器和环境有关系，我跑了更多数据的，加大batch 和num_workers 没遇到这个问题

**Comment by fq19851220** [comment]
> 这个问题是稳定复现的吗，估计和机器和环境有关系，我跑了更多数据的，加大batch 和num_workers 没遇到这个问题

基本都会，每次几分钟到二十多分钟就会卡住，只有一次跑了一个多小时

**Comment by LDOUBLEV** [comment]
是不是GPU运行发热引起的程序卡住了

**Comment by fq19851220** [comment]
> 是不是GPU运行发热引起的程序卡住了

刚才跑了八分钟又卡住了 显卡温度只有七十多度，卡住以后就降到50多度了，只有一千个50x130的样本

**Comment by LDOUBLEV** [comment]
应该就是环境问题了，推荐你用百度自己的AIstudio吧，https://aistudio.baidu.com/aistudio/projectdetail/467229， 有免费的V100 可以用

**Comment by fq19851220** [comment]
> V100

没有gpu了  python环境要安装shapely 和lmdb是正常的吗？

**Comment by fq19851220** [comment]
> 应该就是环境问题了，推荐你用百度自己的AIstudio吧，[https://aistudio.baidu.com/aistudio/projectdetail/467229，](https://aistudio.baidu.com/aistudio/projectdetail/467229%EF%BC%8C) 有免费的V100 可以用

AIstudio没问题 我重装了个win10 专业版目前正常了
