### ISSUE TITLE
CPU-MKLDNN C++多线程跑OCR模型会崩溃

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/PaddleOCR#6671]
![Uploading image.png…]()

**Comment by LDOUBLEV** [comment]
报错信息重新上传吧，看不到图片，另外可以提供下paddle预测库版本以及用的是哪个模型，帮助快速定位问题

**Comment by marsbzp** [comment]
> 

https://github.com/PaddlePaddle/PaddleOCR/issues/731
和这个issue报错内容一致

**Comment by marsbzp** [comment]
paddle2.1推理库
