### ISSUE TITLE
完整模型（检测+识别）无法检测（无报错，检测空白）

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#6672]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11家庭
- 版本号/Version：Paddle：  2.3 PaddleOCR：2.2  问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer/predict_system.py --image_dir="./work/ces/" --det_model_dir="./inference/db_mv3/" --rec_model_
dir="./inference/rec_mv3_none_bilstm_ctc/" --rec_char_dict_path="./work/WaterMeters/water_meter_dict.txt" --rec_char_type=ch --use_angle_cls=false --vis_font_path=
./doc/fonts/simfang.ttf

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/76056473/174989657-4090169d-c907-476e-9c40-43140f45a32c.png)

**Comment by LDOUBLEV** [comment]
用PPOCRv3模型试试：
![image](https://user-images.githubusercontent.com/26592129/174995085-f26d0c56-9042-4b2b-be77-bd1ec27da3ca.png)
python3 tools/infer/predict_system.py --det_model_dir=./inference/ch_PP-OCRv3_det_infer/ --rec_model_dir=./inference/ch_PP-OCRv3_rec_infer/  --image_dir=./test2.png  --drop
_score=0.

训练数据中没有此类数据，最好在PPOCR模型的基础上finetune训练

**Comment by chc-stars** [comment]
![image](https://user-images.githubusercontent.com/76056473/175000336-95643d44-b5fc-4682-a262-38af360f2cf8.png)
![image](https://user-images.githubusercontent.com/76056473/175000450-e7cfa151-9b2c-45f5-9107-10e745edee53.png)
我打印了下，发现传回的为空列表

**Comment by yangy996** [comment]
把阙值设置低一点，默认是0.5

**Comment by chc-stars** [comment]
有ocr的交流群吗
