### ISSUE TITLE
paddleocr导包时发现奇怪的报错情况

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/PaddleOCR#6673]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- docker环境 ---  registry.baidubce.com/paddlepaddle/paddle:2.3.0
- 版本号/Version：Paddle：  PaddleOCR：2.5.0.3     问题相关组件/Related components：
- 运行指令/Command Code：
- python runserver.py
- 完整报错/Complete Error Message：
同级目录下，执行当前的py文件导包会报错，执行子文件夹的py文件，却是正常的？？求大佬指点。。实在想不通。。----确认过，本地文件夹下，没有paddleocr的文件夹或文件。。。
![1](https://user-images.githubusercontent.com/37755235/174995563-a18423ab-ff83-481d-b753-2656b2ee274e.jpg)
![2](https://user-images.githubusercontent.com/37755235/174995601-2b334bdd-0fab-4507-b57e-7b9b3ac0b656.jpg)

**Comment by lmw0320** [comment]
再补充下其他测试情况：
1. 在当前文件夹下，执行命令python，进入python3.7的环境，结果测试from paddleocr import PaddleOCR, paddleocr的命令，是正常导包的。
2. web的子文件夹下，包含了__init__.py的空白文件

**Comment by lmw0320** [comment]
![3](https://user-images.githubusercontent.com/37755235/174997355-772ef321-3aeb-4dae-b2e3-ad1b34f696ce.png)

**Comment by LDOUBLEV** [comment]
> 同级目录下，执行当前的py文件导包会报错，执行子文件夹的py文件，却是正常的？？求大佬指点。。实在想不通。。----确认过，本地文件夹下，没有paddleocr的文件夹或文件。。。

这个有点奇怪，没能复现这个问题，可以看下是不是当前目录下有一个paddleocr或者PaddleOCR目录导致冲突了，我这边可以正常import
![image](https://user-images.githubusercontent.com/26592129/175454943-419d5713-c465-4f1b-b7f9-5c379abaf8d3.png)

**Comment by lmw0320** [comment]
> > 同级目录下，执行当前的py文件导包会报错，执行子文件夹的py文件，却是正常的？？求大佬指点。。实在想不通。。----确认过，本地文件夹下，没有paddleocr的文件夹或文件。。。
> 
> 这个有点奇怪，没能复现这个问题，可以看下是不是当前目录下有一个paddleocr或者PaddleOCR目录导致冲突了，我这边可以正常import ![image](https://user-images.githubusercontent.com/26592129/175454943-419d5713-c465-4f1b-b7f9-5c379abaf8d3.png)

看过了，没有这种文件夹。。我试了很多次的。。后面怀疑是我的代码应用了多进程，导致的。。看前面的截图报错，可以看出来，事先启动了多进程。导致后面的paddleocr，指向从文件夹paddleocr，变成了指向paddleocr.py。。。
我后面还去测试了下，同样从paddeocr的其他相关多进程的issue中，找到了解决方法。就是导包的时候，不从文件抬头导入。而是在函数内部设置导包操作，就可以正常导包了（也不用像我上面提到的那样，去修改源码中的paddleocr.py及其相关的__init.py文件
