### ISSUE TITLE
train和eval效果好，实际测试效果差

### ISSUE THREAD

**Issue by Vergissmeinnic** [PaddlePaddle/PaddleOCR#6674]
使用的是PaddleOCR_2.4的训练的，训练的best结果是occ=0.99以上，之后执行了下eval.py，发现比训练时候低一点，但是也是0.99以上，然后我用这个模型去推理，只有四成是正确的。
请问是什么原因呢？

**Comment by ziyaxuanyi** [comment]
可能：
1.过拟合太严重了，训练数据过于简单，建议多丰富各种场景数据，数据增强
2.推理时测试的图片与训练的图片相差较大，建议多加入做推理测试的图片场景数据去训练
3.检查一下导出静态模型有无问题，推理前处理和后处理过程以及各种参数是否与训练时保持一致

**Comment by Vergissmeinnic** [comment]
谢谢，那我多增加一些不同场景的样本再试试看。
我这边测试的图片和训练的图片是同一批的，所以这个没问题。
静态模型问题已检查，确认无问题。
