### ISSUE TITLE
c++ rec  ctc decode   label_list_ 如何组织输出的tensor？

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#6676]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 
- PaddleOCR：PaddleOCR  问题相关组件/Related components：rec识别
- 运行指令/Command Code：

// ctc decode
     std::vector<std::string> str_res;
     int argmax_idx;
     int blank = predict_shape[1];
     int last_index = 0;
     float score = 0.f;
     int count = 0;
     float max_value = 0.0f;

     for (int n = predict_lod[0][0]; n < predict_lod[0][1] - 1; n++) {
     for (int n = 0; n < predict_shape[1]; n++) {
       argmax_idx =
           int(Utility::argmax(&predict_batch[n * predict_shape[1]],
                               &predict_batch[(n + 1) * predict_shape[1]]));
           int(Utility::argmax(&predict_batch[n * predict_shape[2]],
                               &predict_batch[(n + 1) * predict_shape[2]]));
       max_value =
           float(*std::max_element(&predict_batch[n * predict_shape[1]],
                                   &predict_batch[(n + 1) * predict_shape[1]]));
       if (blank - 1 - argmax_idx > 1e-5) {
           float(*std::max_element(&predict_batch[n * predict_shape[2]],
                                   &predict_batch[(n + 1) * predict_shape[2]]));

       if (argmax_idx > 0 && (not(i > 0 && argmax_idx == last_index))) {
         score += max_value;
         count += 1;
         str_res.push_back(label_list_[argmax_idx]);
       }
       last_index = argmax_idx;
     }
     score /= count;
     for (int i = 0; i < str_res.size(); i++) {
       std::cout << str_res[i];
     }
     std::cout << "\tscore: " << score << std::endl;
   }
 }
 
此处的 label_list_ 是训练时的字典？？ 

正在处理 output_tensor，我的问题其实和之前一个issue#5714一样，如何组织输出的tensor？
“关于OCR文字识别成功后获取到Tensor，应该如果从中解析出文本 ”#5714 

如果能把rec这一部分的代码附上注释那就好了!!

**Comment by tink2123** [comment]
是的 label_list_ 是训练用到的字典，字符与index一一对应，例如 {"0":a, "1":b, "2":c, "3":d}

output_tensor 预测得到的是索引，解析文本过程就是通过索引值还原成字符串的过程。
