### ISSUE TITLE
请教下问题：Android使用paddle_lite，偶尔出现这个报错，不是每次都会出现

### ISSUE THREAD

**Issue by woailangya** [PaddlePaddle/PaddleOCR#6679]
Android单独一个activity中来做图片识别文字，onResume中onLoadModel，onDestroy中onUnloadModel；大多数时候，进入这个页面都是正常使用，偶尔出现退出这个页面时报：
A/Paddle-Lite: [F  6/23 12:15:21.332 ...20/lite/Paddle-Lite/lite/core/program.cc:688 Run] Check failed: kernel_: kernel null
    --------- beginning of crash
2022-06-23 12:15:21.333 22697-23904/com.xuexiang.mashangproject A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23904 (Thread-266), pid 22697 (.mashangproject)

使用的版本：
paddle_lite_libs_v2_10
opencv-4.2.0-android-sdk
ch_PP-OCRv2
dygraph_v2.0

**Comment by wangwh0128** [comment]
我也遇到过类似问题，一直没有解决
