### ISSUE TITLE
SAST和SRN 现在只支持英文吗？同一场景下中文效果比DB和CRNN要差

### ISSUE THREAD

**Issue by Inchel214** [PaddlePaddle/PaddleOCR#668]
如题

**Comment by MissPenguin** [comment]
sast和srn的开源模型都是基于英文数据集训练的，目前没有发布中文模型，需要的话可以自己使用中文数据进行训练。

**Comment by Inchel214** [comment]
> sast和srn的开源模型都是基于英文数据集训练的，目前没有发布中文模型，需要的话可以自己使用中文数据进行训练。

请问近期有发布的打算吗

**Comment by littletomatodonkey** [comment]
你好，近期没有发布的计划，感谢关注~
