### ISSUE TITLE
slim量化模型比原始模型更大，更慢

### ISSUE THREAD

**Issue by JinYuannn** [PaddlePaddle/PaddleOCR#6681]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/88826210/175234519-5fdcf594-4879-44c6-b850-ff4c68ce8abf.png">
表格中显示en_PP-OCRv3_rec_slim推理模型只有3.2M，但是下载下来模型+参数有10M，比en_PP-OCRv3_rec还要大。
<img width="563" alt="image" src="https://user-images.githubusercontent.com/88826210/175235021-ff24c2b3-6482-4ce6-9c1a-44cd228125ff.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/88826210/175235068-a9672ff7-c643-4ec0-b214-aaedaf1282bf.png">
用CPU推理slim比原始慢了50ms。
请问这是为什么，slim版本不应该更小更快吗？

**Comment by andyjpaddle** [comment]
3.2M指的是nb模型，cpu慢多少呢？有详细的测试数据吗？

**Comment by JinYuannn** [comment]
cpu：i7-11700k
os: windows 11

原始模型：70ms（单线程）/  35（mkl 10线程）
slim模型：100ms（单线程）/ 50 （mkl 10线程）

另外：en_number_mobile_slim_v2.0_rec有计划更新到v3.0吗？

**Comment by andyjpaddle** [comment]
这边量化的话，可以使用int8精度来测

**Comment by JinYuannn** [comment]
> 

en_number_mobile_slim是比rec_slim更小的模型吧？

**Comment by JinYuannn** [comment]
> 



> > 另外：en_number_mobile_slim_v2.0_rec有计划更新到v3.0吗？
> 
> `en_PP-OCRv3_rec_slim` 这个就是v3版本的

mobile_slim是比rec_slim更小的模型吧？

**Comment by JinYuannn** [comment]
> 这边量化的话，可以使用int8精度来测

cpp_infer如何使用int8?

**Comment by andyjpaddle** [comment]
> > 
> 
> > > 另外：en_number_mobile_slim_v2.0_rec有计划更新到v3.0吗？
> > 
> > 
> > `en_PP-OCRv3_rec_slim` 这个就是v3版本的
> 
> mobile_slim是比rec_slim更小的模型吧？

mobile可以理解是v1,最新的是v3，v2之后就不再区分mobile和server模型了

**Comment by andyjpaddle** [comment]
> > 这边量化的话，可以使用int8精度来测
> 
> cpp_infer如何使用int8?

通过 `precision` 参数指定

**Comment by JinYuannn** [comment]
谢谢解答！

**Comment by JavieYuan** [comment]
> > > 这边量化的话，可以使用int8精度来测
> > 
> > 
> > cpp_infer如何使用int8?
> 
> 通过 `precision` 参数指定

python端在utility.py也有'precision'这个参数，用的就是int8，但是依然slim量化训练模型cpu耗时反而比训练模型大呢？
