### ISSUE TITLE
表格识别模型精度来回阶跃

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#6682]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：2.2.1  PaddleOCR：release 2.5
- 运行指令/Command Code：python tools/train.py -c configs/table/table_mv3.yml
![image](https://user-images.githubusercontent.com/83860013/175243156-fe2b2e2c-3349-4e23-883c-bb63a436308e.png)

问题：acc一直在0.666667、0.833333和0.750000这三个值上跳动怎么办
batch_size_per_card: 6
num_workers: 1

**Comment by andyjpaddle** [comment]
是不是测试数据太少了？可以再继续训训

**Comment by s957995299** [comment]
> 是不是测试数据太少了？可以再继续训训

可能不是吧？我用PubTabNet数据集训的，rtx3060训两天了也这个样子

**Comment by WenmuZhou** [comment]
多训练会看看，这个模型要训练的比较久，我们这边是pubtabnet数据集，4卡v100训了4天多

**Comment by s957995299** [comment]
> 多训练会看看，这个模型要训练的比较久，我们这边是pubtabnet数据集，4卡v100训了4天多

大概跑了多少个epoch  才达到比较高水平的acc呢

**Comment by WenmuZhou** [comment]
大约50个
