### ISSUE TITLE
表格识别错位问题

### ISSUE THREAD

**Issue by yoeaki** [PaddlePaddle/PaddleOCR#6688]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`mac m1 `
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：`PaddleOCR最新版。`
- 运行指令/Command Code： 
**执行脚本：** `ppstructure/predict_system.py`
**执行参数：** `--image_dir="./source/static/picture/ppstructure/00002_cut.jpg"
--det_model_dir="./inference/ch_PP-OCRv3_det_infer/"
--rec_model_dir="./inference/ch_PP-OCRv3_rec_infer/"
--cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"
--table_model_dir="./inference/en_ppocr_mobile_v2.0_table_structure_infer"
--rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt"
--table_char_dict_path="./ppocr/utils/dict/table_structure_dict.txt"
--vis_font_path="./doc/fonts/chinese_cht.ttf"
--use_gpu=False
--use_angle_cls=False
--use_space_char=True
--mode=structure`
- 完整报错/Complete Error Message：
**错位说明：**<img width="858" alt="image" src="https://user-images.githubusercontent.com/39695971/175441790-e4133810-22d0-432f-9c01-e8c9c2e3ac26.png">

**Comment by WenmuZhou** [comment]
模型未使用中文训练，对中文效果不是很好哈

**Comment by yoeaki** [comment]
> 模型未使用中文训练，对中文效果不是很好哈

中英文版的预测模型有在计划中吗？

**Comment by ZTurboX** [comment]
> 模型未使用中文训练，对中文效果不是很好哈

表格结构中文和英文场景不是相同的吗

**Comment by WenmuZhou** [comment]
但是训练数据也会带来影响
