### ISSUE TITLE
训练文本识别模型时报错：test目录下一部分jpg图像不存在，但实际是存在的且路径和图像都没有问题     raise Exception("{} does not exist!".format(img_path))

### ISSUE THREAD

**Issue by rebeccajuan** [PaddlePaddle/PaddleOCR#6690]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：widows GPU
- 版本号/Version：Paddle：paddlepaddle-gpu=2.2.2  PaddleOCR： 2.4 问题相关组件/Related components：CUDA 10.2 CuDNN v7.6.5 python=3.7
- 运行指令/Command Code：python tools/train.py -c configs/rec/h_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml
- 完整报错/Complete Error Message：
root ERROR: When parsing line test/204010727250000121.jpg	京N78E95
, error happened with msg: Traceback (most recent call last):
  File "F:\\paddleocr\PaddleOCR-release-2.4\ppocr\data\simple_dataset.py", line 114, in __getitem__
    raise Exception("{} does not exist!".format(img_path))
Exception: ./train_data/det-rec/test/204010727250000121.jpg does not exist!

**Comment by rebeccajuan** [comment]
问题：文件名少了一字符；
已解决

**Comment by phb-shiyige-fw** [comment]
> 问题：文件名少了一字符； 已解决
请问是如何解决这个问题的？我也出现了相关问题。少了一字符是啥意思？
