### ISSUE TITLE
ppocrlabel 报错

### ISSUE THREAD

**Issue by modem1024k** [PaddlePaddle/PaddleOCR#6691]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.6.6和一个3.6.6的虚拟环境
- 版本号/Version：在虚拟环境里安装了 Paddle： 2.0.0 PaddleOCR：2.2  pyqt5版本5.15.6，
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：type object 'MainWindow' has no attribute 'canvas'
正常使用一天后，重启电脑后，又出现老问题
'MainWindow' object has no attribute 'canvas'
卸载后，重新安装，也未能解决
昨天在虚拟环境里卸载了依赖包，再重新安装，好了一天
第二天又不行了
报错信息依然是type object 'MainWindow' has no attribute 'canvas'
总结：目前就是全部卸载，安装后当时能正常使用，推出虚拟环境，再进入后，就报错，又要卸载，重新安装，也许突然又好用了，完全找不到哪里出问题了。

**Comment by Evezerest** [comment]
pyqt版本是多少呢

**Comment by modem1024k** [comment]
pyqt5 版本&nbsp;5.15.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] ppocrlabel 报错 (Issue #6691)





 
pyqt版本是多少呢

**Comment by modem1024k** [comment]
问题解决，将paddle版本降到 2.0.0，卸载了paddleocr,pyqt5,再重新安装ppocrlabel,ppocrlabel,启动成功

**Comment by modem1024k** [comment]
正常使用一天后，重启电脑后，又出现老问题
'MainWindow' object has no attribute 'canvas'
卸载后，重新安装，也未能解决
