### ISSUE TITLE
PaddleOCR如何检测视频？

### ISSUE THREAD

**Issue by Keeping7** [PaddlePaddle/PaddleOCR#6694]
检测图像是可以的，但是用图像的命令套用视频时，显示如下错误：

python3 ./paddle/PaddleOCR-release-2.5/tools/infer/predict_det.py --image_dir="./2-HC-YQ/HC-YQ.mp4" --det_model_dir="./output/db_mv3_inference_latest/l.save_infer/"
Traceback (most recent call last):
  File "./paddle/PaddleOCR-release-2.5/tools/infer/predict_det.py", line 259, in <module>
    image_file_list = get_image_file_list(args.image_dir)
  File "/home/jcuas/nanhang/tongk/paddle/PaddleOCR-release-2.5/ppocr/utils/utility.py", line 71, in get_image_file_list
    raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in ./2-HC-YQ/HC-YQ.mp4

PaddleOCR是不支持检测视频吗？检测视频的命令是什么呢？求大佬们指点，谢谢。

**Comment by tink2123** [comment]
暂时不支持视频格式作为输入

**Comment by Keeping7** [comment]
谢谢。
那如果要对视频检测，有什么其他方法吗？

**Comment by Keeping7** [comment]
> 暂时不支持视频格式作为输入

谢谢。那如果要对视频检测，有什么其他方法吗？

**Comment by tink2123** [comment]
可以先对视频进行切帧，以图片格式送入ocr检测识别
