### ISSUE TITLE
无法kill 训练代码，导致内存一直占用

### ISSUE THREAD

**Issue by chunniunai220ml** [PaddlePaddle/PaddleOCR#6696]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu20.04+按照文档配置的docker环境
- 版本号/Version：Paddle：2.1.3  
- PaddleOCR：release/2.5
- 运行指令/Command Code：
- python3 tools/train.py -c configs/rec/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=../ch_PP-OCRv3_rec_train/best_accuracy Optimizer.base_lr=0.0001
- 完整报错/Complete Error Message：
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/17668109/175512715-c53be8ba-a249-408f-90dd-28cbd631b2a5.png">

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/17668109/175512844-6ecbcdcb-a71e-44e9-98aa-3066f811c407.png">

kill -9 pid,杀不死进程，gpu显存也无法释放，docker kill 也不行，把运行的docker 停了，删除了，但是这个进程一直死不了，释放不了显存

求解决方案

**Comment by tink2123** [comment]
在docker外手动kill进程试下

**Comment by justcodew** [comment]
fuser -v /dev/nvidia* | awk '{for(i=1;i<=NF;i++)print "kill -9 " $i;}' | sh
可以使用这个
