### ISSUE TITLE
超轻量模型训练数据

### ISSUE THREAD

**Issue by ltm920716** [PaddlePaddle/PaddleOCR#67]
请问超轻量模型的训练数据（中英文数字）是公开的数据集么，还是私有数据集，可以共享么，谢谢

**Comment by LDOUBLEV** [comment]
感谢关注，训练数据有lsvt数据集和我们自己合成的数据，我们自己合成的数据暂时不会开源

**Comment by DuckJ** [comment]
你好，识别部分能说明一下数据集有哪些和量级么？特别是中文数据集 @LDOUBLEV

**Comment by dyning** [comment]
检测：
英文数据集，ICDAR2015
中文数据集，LSVT（https://rrc.cvc.uab.es/?ch=16）街景数据集训练数据3w张图片
识别：
英文数据集，MJSynth和SynthText合成数据，数据量上千万。
中文数据集，LSVT（https://rrc.cvc.uab.es/?ch=16）街景数据集根据真值将图crop出来，并进行位置校准，总共30w张图像。此外基于LSVT的语料，合成数据500w。

**Comment by DuckJ** [comment]
@dyning 非常感谢回复告知。

**Comment by ltm920716** [comment]
@LDOUBLEV @dyning 感谢回复
