### ISSUE TITLE
vqa 里re模型和ser模型

### ISSUE THREAD

**Issue by QZ1219** [PaddlePaddle/PaddleOCR#6702]
你好，我刚开始看layoutlm相关模型，用release2.4版本遇到个问题，re模型在读取数据的时候只有数据中存在关系才能读取。实际应用场景中却是可能有些数据中存在关系对，有些数据只有不同实体类别没有关系。是要同时用ser和re两个模型来做这种任务吗？能不能只用一个模型有关系的时候出关系没关系的时候就只是实体类别输出呢？

**Comment by WenmuZhou** [comment]
这个目前做不到的
