### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by mahengrui1** [PaddlePaddle/PaddleOCR#6703]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

In readme https://github.com/PaddlePaddle/PaddleOCR/blob/fe8d103cf968073b63ffb2c98c8203180e0358c0/doc/doc_en/quickstart_en.md  

at 2.1.1 it says

`paddleocr --image_dir ./imgs_words_en/word_10.png --det false --lang en`

However it does not have that path

**Comment by littletomatodonkey** [comment]
The path is `doc/imgs_words_en/word_10.png`, and you should enter dir `doc` firstly.

**Comment by mahengrui1** [comment]
> The path is `doc/imgs_words_en/word_10.png`, and you should enter dir `doc` firstly.

in 2.1, and at other cases, the path is '`PaddleOCR provides a series of test images, click [here](https://paddleocr.bj.bcebos.com/dygraph_v2.1/ppocr_img.zip) to download`'
