### ISSUE TITLE
同一个图片，在图片浏览器，不同显示比例，识别结果为什么会有区别？crnn在识别前不是都会统一到模型的图片尺寸吗？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6706]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

同一个图片，在图片浏览器，不同显示比例，识别结果为什么会有区别？crnn在识别前不是都会统一到模型的图片尺寸吗？微信nlanguage

**Comment by MissPenguin** [comment]
是不是截图的时候有diff呢，先对比一下图片是否确实完全一样吧

**Comment by nissansz** [comment]
就是Windows自带的看图软件。或者adobe用PDF文件，放大缩小，然后截图识别，得到的结果会不同

**Comment by yangy996** [comment]
是的，主要原因是因为文本检测模型不限定图片输入尺寸，所以结果会不同

**Comment by nissansz** [comment]
有没有办法统一？改善？

**Comment by yangy996** [comment]
> 有没有办法统一？改善？

通用文本检测模型没有办法改，如果自己有数据集可以参考这篇文章，固定- DetResizeForTest:resize_long: 960
https://blog.csdn.net/YY007H/article/details/120646395

**Comment by nissansz** [comment]
我是用ctpn定位，然后onnx crnn识别。没法改这个参数吧？DetResizeForTest:resize_long: 960
