### ISSUE TITLE
v3 crnn模型怎么判断，准确率已经到极限，无法再改善了？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6707]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
v3 crnn模型怎么判断，准确率已经到极限，无法再改善了？微信nlanguage

**Comment by MissPenguin** [comment]
一般看看badcase，如果都是一些比较特殊的case，或者人都无法识别的，就差不多可以停止优化了。不过一般比较难说准确率做到极限，多数情况还是有优化空间的，当然不一定是优化CRNN算法本身，也可能从数据、前后处理等角度考虑。
