### ISSUE TITLE
ocr识别结果中，文字坐标值不准确，漂移了

### ISSUE THREAD

**Issue by bigcash** [PaddlePaddle/PaddleOCR#671]
如题，返回结果中，文字是没问题的，但是位置框漂移了，根本就不在这里，感觉是不是计算文字位置时计算错误，有bug呀。另，该问题在我本机Ubuntu18.04中是没问题的，打包到docker（也是ubuntu18.04）后部署才会出现这种问题。我使用的pip安装的paddlehub中的代码调用的mobile版的模型。

**Comment by LDOUBLEV** [comment]
返回文字对说明模型和预测都没问题，位置框漂移估计是可视化时候的问题吧，可否发个样例图

**Comment by bigcash** [comment]
> 返回文字对说明模型和预测都没问题，位置框漂移估计是可视化时候的问题吧，可否发个样例图
> 是不是部署的时候，可视化输入的图像和预测图有区别，导致可视化出问题了

谢回。我没有进行可视化，这种情况也是在极个别图片上出现问题。我只是观察了图片中文字实际位置，与预测文字位置之间比较一下，看出来的错误。错误仅在docker镜像中出错，本地ubuntu中没错
图片我上传到云盘了，链接：https://pan.baidu.com/s/17VPa_zI9H64WSlDrdEx-9A     提取码：zhrv 
感谢！

**Comment by Steffy-zxf** [comment]
@bigcash 你好！感谢反馈！上述网盘链接已失效了。可以直接在issue上 附上 一张样例图片即可。
