### ISSUE TITLE
关于v2模型大小的问题

### ISSUE THREAD

**Issue by Baiy97** [PaddlePaddle/PaddleOCR#6711]
v2版本paper中检测模型的model size是3.0 M，但是运行 paddle.summary() 得到的模型total_params 只有570+K，请问为什么会有如此差别，是我概念理解错了还是什么原因？

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04.3 LTS
- 版本号/Version：Paddle：2.2.2.post112  PaddleOCR：2.4.0.2 
- 运行指令/Command 
代码中加入
` print(paddle.summary(model, (1, 3, 640, 640)))`
运行
`CUDA_VISIBLE_DEVICES=0 python tools/eval.py --config configs/det/ch_PP-OCRv2/ch_PP-OCRv2_det_student.yml`
- 
![Snipaste_2022-06-27_10-20-12](https://user-images.githubusercontent.com/26376415/175847965-19162af7-7645-4510-9885-a18a2ea74127.jpg)

**Comment by littletomatodonkey** [comment]
你好，
1. params表示参数量，乘以4一般约等于实际的预训练模型模型大小（以M为单位）
2. 我们在paper中给出的model size是inference model大小，它是量化后模型`pdmodel` + `pdiparams`的大小，而且对部分算子做了融合，便于加速，与paddle summary得到的params大小相关，但是没有明确的计算关系
