### ISSUE TITLE
ppOCRv3_ch 能部署到移动端吗？

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleOCR#6715]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
正在适配中，着急的话可以自己先尝试在PP-OCRv2的基础上改一下哈

**Comment by LDOUBLEV** [comment]
可以部署到移动端，参考PR:https://github.com/PaddlePaddle/PaddleOCR/pull/6718/files
