### ISSUE TITLE
表格识别算法loss降不下去了

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#6716]
前提：模型尚且未进行修改
如果直接从头训练的话，loss到（6,9）之间就不再下降了
所以我加载了预训练模型en_ppocr_mobile_v2.0_table_structure_train
但是loss到（2,4）之间也不下降了，acc一直是0.6667，0.8333，0.750这三个值，跳来跳去
请问我训练的正常吗？
若不正常，该怎么正常训练呢？
求求大佬讲解改怎么办

**Comment by WenmuZhou** [comment]
多少数据

**Comment by s957995299** [comment]
> 多少数据
使用的是PubTabNet数据集

**Comment by WenmuZhou** [comment]
贴一下配置看看

**Comment by WenmuZhou** [comment]
你训练的gpu数量是几个，这个配置我们这边四卡训练loss能降到0.x
