### ISSUE TITLE
Question about PPOCRLabel collaboratif labeling

### ISSUE THREAD

**Issue by KHDOUDI** [PaddlePaddle/PaddleOCR#6722]
Hello, 
Thank you for the good work, keep up.
I would like to ask on any future plan for extending PPOCRLabel to allow multi-user work. Any web version is planned on the scope.
Thank you again.

**Comment by Evezerest** [comment]
hi, thanks for your suggestion, the web version of PPOCRLabel is not planned to be developed.
If any web version is developed by the community developers, we'll add a reference link in the readme of PPOCRLabel.

**Comment by Evezerest** [comment]
hi, thanks for your suggestion, the web version of PPOCRLabel is not planned to be developed.
If any web version is developed by the community developers, we'll add a reference link in the readme of PPOCRLabel.
