### ISSUE TITLE
PPOCRLabel   CANNOT OPEN .xlsx.

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6724]
CANNOT OPEN .xlsx. It could be one of the following reasons: Only support Windows | No python win32com
CANNOT OPEN .xlsx. It could be the following reasons: .xlsx is not existed

**Comment by Mrfuhang** [comment]
> 这个需要重装一下xlsx的软件，如果用的是WPS的话，我也遇到过这个问题。之前也试过网上各种做法，结果都不靠谱

装了办公软件office也是没有用啊
