### ISSUE TITLE
OCR中的文本识别的输入图片是动态尺寸的问题

### ISSUE THREAD

**Issue by banhongjun** [PaddlePaddle/PaddleOCR#6727]
OCR中的文本识别的输入图片是动态尺寸的，送入到.onnx模型后预测输出结果的大小也是一个是动态变化的尺寸，我想知道动态图片尺寸的大小跟onnx预测结果维度尺寸大小之间的关系，是否有公式可以计算出？
例如：
1）输入文本识别大小为（1,3,32,67），onnx的输出为（1,17,6625）；
2）输入文本识别大小为（1,3,32,139），onnx的输出为（1,35,6625）；
![image](https://user-images.githubusercontent.com/99791142/176104024-a748492f-bea6-42e3-8c94-f8f446eb602d.png)

**Comment by banhongjun** [comment]
现在你们都不回复问题了？

**Comment by Topdu** [comment]
W/4，可以直接根据代码得出的
