### ISSUE TITLE
表格识别

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6728]
表格内部无框线时，识别效果不好

**Comment by MissPenguin** [comment]
迭代优化中，欢迎持续关注~

**Comment by ZTurboX** [comment]
> 迭代优化中，欢迎持续关注~

如果有表格的坐标，如何转成html格式呢

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/table/convert_label2html.py 用这个脚本可以转换
