### ISSUE TITLE
执行轻量级模型是报错

### ISSUE THREAD

**Issue by xugenghui** [PaddlePaddle/PaddleOCR#673]
当我执行 python tools/infer/predict_system.py --image_dir /home/linghu/data/friend_info_30/ --det_model_dir ./tools/infer/ch_det_mv3_db/ --rec_model_dir ./tools/infer/ch_rec_mv3_crnn/  --use_gpu Fasle --enable_mkldnn True报错：

---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
Intel MKL function load error: cpu specific dynamic library is not loaded.

**Comment by LDOUBLEV** [comment]
是不是你本地没有安装MKL这个库，你把enable_mkldnn 设置为False呢

**Comment by xugenghui** [comment]
> 是不是你本地没有安装MKL这个库，你把enable_mkldnn 设置为False呢

已解决，更改了numpy和scrip版本，具体版本在问题里搜就能找到
