### ISSUE TITLE
ppstructure 问题，谢谢！

### ISSUE THREAD

**Issue by laocan** [PaddlePaddle/PaddleOCR#6730]
您好，有些疑问，麻烦解答下：
1. layout-parser 预训练模型太大了，可以压缩吗？有试过压缩吗？
https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_publaynet_pretrained.pdparams
2. 这个检测模型，可以用其他轻量级模型代替吗？有什么推荐吗？
3. 如果只想提取单一目标，比如 {3:"List"} 可以只训练个检测模型实现吗？
4. layoutparser-***.whl 这个包 有源码吗？
谢谢！

**Comment by littletomatodonkey** [comment]
你好

1. 这个模型确实很大，可以参考PaddleDetection的模型压缩方法进行压缩，比如模型量化
2. 检测模型可以用picodet等进行替代，模型大小30M以内，我们最近也计划开源轻量级模型，敬请期待~
3. 可以的，需要你整理好数据，加载我们的预训练模型，重新训练下即可
4. 有源码的，在这里：https://github.com/an1018/layout-parser/blob/eec3c4ca02224a177846937f3a9c6f08b9d4ca4e/src/layoutparser/models/layoutmodel.py#L186

感谢你的关注！

**Comment by laocan** [comment]
非常感谢您的详细回复，期待ing~
