### ISSUE TITLE
图片预处理

### ISSUE THREAD

**Issue by Altman7** [PaddlePaddle/PaddleOCR#6732]
Paddleocr提供的图片识别服务，在识别时有默认的预处理动作么？
我在进行识别之前需要先进行图片预处理么

**Comment by LDOUBLEV** [comment]
paddleocr在预测时有resize ,normlization等预处理，
直接输入图像就行，无需预处理

**Comment by Altman7** [comment]
好的，感谢

**Comment by Alice-Thirty** [comment]
假设目标 3,48,320
处理是
先把图片H  resize到 48 然后 除以255
再减0.5  除以0.5
剩下用padding 0 resize 到 48,320


这是对的吗   mean and  std
mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]
