### ISSUE TITLE
 PaddleOCR 与 HanLP 一起使用报错

### ISSUE THREAD

**Issue by xmy123** [PaddlePaddle/PaddleOCR#6734]
**错误信息：**
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1656414534 (unix time) try "date -d @1656414534" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f280f979008) received by PID 3690 (TID 0x7f280f965740) from PID 261591048 ***]

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by LDOUBLEV** [comment]
请提供更详细的信息，或者问题复现最小测试代码，也好排查问题
