### ISSUE TITLE
使用Paddleserving（python版本）部署PaddleOcr时，使用CPU和GPU都正常，使用TRT时报错

### ISSUE THREAD

**Issue by bzcl** [PaddlePaddle/PaddleOCR#6737]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 使用docker，镜像为registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda11.2-cudnn8，trt版本为8.0.1.6
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddle-serving-app                0.8.3
paddle-serving-client             0.8.3
paddle-serving-server-gpu         0.8.3.post112
paddlepaddle-gpu                  2.3.0.post112
tensorrt   8.0.1.6
- 运行指令/Command Code：
- python web_service.py
- 完整报错/Complete Error Message：
W0628 12:15:04.902067  2920 helper.h:107] TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.1
W0628 12:15:05.175945  2834 helper.h:107] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.1.1
W0628 12:15:05.187911  2834 helper.h:107] Detected invalid timing cache, setup a local cache instead
E0628 12:15:08.423333  2940 helper.h:111] 10: [optimizer.cpp::computeCosts::1855] Error Code 10: Internal Error (Could not find any implementation for node pool2d (Output: pool2d_1.tmp_0188).)
E0628 12:15:08.423501  2940 helper.h:111] 2: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
E0628 12:15:08.435058  2909 helper.h:111] 10: [optimizer.cpp::computeCosts::1855] Error Code 10: Internal Error (Could not find any implementation for node pool2d (Output: pool2d_1.tmp_0188).)
E0628 12:15:08.435227  2909 helper.h:111] 2: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1656418508 (unix time) try "date -d @1656418508" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 2909 (TID 0x7fb76da13740) from PID 8 ***]

可能是Trt与cuda版本不匹配的问题，有支持cuda11.2的trt吗？在开启TRT加速后web_service.py中的set_dynamic_shape_info该怎么写？

**Comment by LDOUBLEV** [comment]
paddle支持trt的下载链接：https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html#python

set_dynamic_shape_info用来设置需要补充动态shape的参数，如果遇到某些参数需要传入动态shape，参考这个文档设置:
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/FAQ.md#q-trt%E9%A2%84%E6%B5%8B%E6%8A%A5%E9%94%99invalidargumenterror-some-trt-inputs-dynamic-shape-info-not-set-check-the-info-log-above-for-more-details
