### ISSUE TITLE
pdserving现在提供的模型可能有问题（2020.9.4）

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#674]
新下载了pdserving文件夹并按照readme下载解压了相关的模型文件，报了错误，使用之前的模型完全正常。错误可能出现在两个地方，如果有人遇到，换回之前较早的模型文件就可以了，没有的话可以留邮箱，我这里有。
1、pdserving中提供的det rec代码有问题（目测不是这个原因，需要再测试下）
2、提供下载的det模型和rec模型有问题（可能性更大）
![image](https://user-images.githubusercontent.com/25734125/92216825-69dab700-eec9-11ea-9a50-db8aae7e8749.png)

**Comment by MissPenguin** [comment]
@wangjiawei04
