### ISSUE TITLE
识别训练找不到图片

### ISSUE THREAD

**Issue by ljq8866** [PaddlePaddle/PaddleOCR#6740]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=ch_PP-OCRv3_rec_train/best_accuracy
- 完整报错/Complete Error Message：[2022/06/29 15:34:26] ppocr ERROR: When parsing line rec/train/boat_3777.jpg 闽龙渔08281
, error happened with msg: Traceback (most recent call last):
File "/home/ljq/boat_recognition/PaddleOCR-release-2.5/ppocr/data/simple_dataset.py", line 132, in __getitem__
raise Exception("{} does not exist!".format(img_path))
Exception: ./train_data/rec/train/boat_3777.jpg does not exist!
路径反复检查了没有错

**Comment by LDOUBLEV** [comment]
> [2022/06/29 15:34:26] ppocr ERROR: When parsing line rec/train/boat_3777.jpg 闽龙渔08281

检查下 ./train_data/rec/train/boat_3777.jpg 路径中是否有空格导致找不到图像了

**Comment by SenchaBrest** [comment]
I had this error several times. And all of them consisted in the fact that I did not confuse the name of the file, but its extension. I indicated in the labels that the pictures were in .jpg format, but in fact they were in .png. I understand that this is a very stupid mistake and it was very difficult not to notice it, but still, maybe this will help you
