### ISSUE TITLE
Vietnamese all recognized as english characters

### ISSUE THREAD

**Issue by tinggh** [PaddlePaddle/PaddleOCR#6748]
PaddleOCR version: release/2.5
python .\paddleocr.py --lang vi --image_dir XXXXXXX

**Comment by khanh41** [comment]
Why is this issue closed even though unresolved?

**Comment by doduythao** [comment]
> I met this problem too.

No tone mark everywhere. All issues raised about vi lang with images shown result text is without tone mark.
