### ISSUE TITLE
ubuntu18.04,cuda11.1和cuda11.2安装paddle2.3.0的gpu版本使用import paddle paddle.utils.run_check()验证报错

### ISSUE THREAD

**Issue by aibohang** [PaddlePaddle/PaddleOCR#6749]
1、请问paddle2.3.0的gpu版本不支持ubuntu18.04,cuda11.1吗，下载下来后验证是否安装成功报错
OSError: (External) CUBLAS error(7).[Hint: 'CUBLAS_STATUS_INVALID_VALUE'. An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:424)

2、换成cuda11,2后安装paddle2.3.0的gpu还是报错，
OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR. [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:516)

**Comment by LDOUBLEV** [comment]
需要安装和你机器匹配的paddle
如果你的机器是cuda11.1，请按照以下命令安装：OSError: (External) CUDA error(700), an illegal memory access was encountered.
参考：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
