### ISSUE TITLE
模型在训练时训练效果可以，但是模型转化到手机端时效果变差了

### ISSUE THREAD

**Issue by heXiangpeng** [PaddlePaddle/PaddleOCR#675]
这种怎么样解决

**Comment by LDOUBLEV** [comment]
> 这种怎么样解决

大概变差了多少，可以发个样例图看下吗，方便排查问题

**Comment by tyy2tyy** [comment]
我也遇到这个问题，在服务器上检测训练的模型效果尚可，使用paddle-lite转化后部署到安卓端时，检测效果就不一致了，可以看下面两幅图的检测结果对比：
![2e7df0c53c485a2271008db7da6c88f6](https://user-images.githubusercontent.com/51456283/92222392-88dd4700-eed1-11ea-979c-322acea198c0.jpg)
![Screenshot_20200904-170745](https://user-images.githubusercontent.com/51456283/92222413-91ce1880-eed1-11ea-84df-80eabd532fde.png)

**Comment by heXiangpeng** [comment]
变得 完全接受不了

**Comment by heXiangpeng** [comment]
> > 这种怎么样解决
> 
> 大概变差了多少，可以发个样例图看下吗，方便排查问题

变得完全不能接受，我感觉还是数据量不足，正在进行数据的扩增

**Comment by heXiangpeng** [comment]
> 我也遇到这个问题，在服务器上检测训练的模型效果尚可，使用paddle-lite转化后部署到安卓端时，检测效果就不一致了，可以看下面两幅图的检测结果对比：
> ![2e7df0c53c485a2271008db7da6c88f6](https://user-images.githubusercontent.com/51456283/92222392-88dd4700-eed1-11ea-979c-322acea198c0.jpg)
> ![Screenshot_20200904-170745](https://user-images.githubusercontent.com/51456283/92222413-91ce1880-eed1-11ea-84df-80eabd532fde.png)

可能是数据量不够，看过一篇他们出的使用方法，每个字都要出现200次左右

**Comment by LDOUBLEV** [comment]
如果是使用deploy/lite下面的C++代码预测呢，有相同的情况吗
