### ISSUE TITLE
如何冻结预训练模型的骨干层进行训练微调？

### ISSUE THREAD

**Issue by aganal** [PaddlePaddle/PaddleOCR#6753]
根据Tutorial下载了字符块检测的预训练模型，只有MobileNetV3_large_x0_5_pretrained.pdparams文件，请问如何设置冻结backbone再进行微调训练呢？如果是在config文件里面添加参数，具体要如何添加呢？

**Comment by tink2123** [comment]
在希望冻结的部分，添加 stop_gradient=True, 如果是希望冻结backbone，可在这个位置下一行添加 x.stop_gradient=True：
https://github.com/PaddlePaddle/PaddleOCR/blob/3293645c1a036026e1dda71d11755b19fda1813e/ppocr/modeling/architectures/base_model.py#L79
