### ISSUE TITLE
PPOCRv3 slim模型有错误

### ISSUE THREAD

**Issue by shivabohemian** [PaddlePaddle/PaddleOCR#6756]
我测试了一下，这个PPOCRv3的识别模型slim版识别出来不对，用原版就没问题（模型转换为lite nb模型）
<img width="1068" alt="截屏2022-06-30 21 23 04" src="https://user-images.githubusercontent.com/39078424/176688324-5a6ce939-6d9d-4375-bd5e-913ca17abac4.png">

**Comment by tink2123** [comment]
请问是参考这个方式测试正确性的吗？
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/lite/readme_ch.md

**Comment by shivabohemian** [comment]
> 请问是参考这个方式测试正确性的吗？ https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/lite/readme_ch.md

是的，你可以试一下，我在arm linux下测试识别后是乱码，用提供的ch_PP-OCRv3_rec_slim.nb模型或是从自己转的nb模型都一样。用ch_PP-OCRv3_rec模型转成的nb模型就没问题

**Comment by ANDROIDTODO** [comment]
这个问题一直没解决吗？
