### ISSUE TITLE
标注工具软件界面打开中文不显示 [] 

### ISSUE THREAD

**Issue by zkailinzhang** [PaddlePaddle/PaddleOCR#6758]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： 
paddle-bfloat                 0.1.2
paddleocr                     2.5.0.3
paddlepaddle-gpu              2.3.0
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
opencv-contrib-python         4.4.0.46
opencv-python                 4.2.0.32

- 运行指令/Command Code： PPOCRLabel --lang ch --kie True
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/10251153/176812938-5df67f3a-b37e-43f8-b177-39c00edcd9eb.png)

**Comment by zkailinzhang** [comment]
sudo gedit /etc/default/locale
将如下添加进去，保存
LANG=zh_CN.UTF-8 
LANGUAGE=”zh_CN:zh”

sudo apt-get install ttf-wqy-microhei
ok

**Comment by leoterry-ulrica** [comment]
> sudo gedit /etc/default/locale 将如下添加进去，保存 LANG=zh_CN.UTF-8 LANGUAGE=”zh_CN:zh”
> 
> sudo apt-get install ttf-wqy-microhei ok

请问kie开启后，怎么进行标注？
