### ISSUE TITLE
请教检测部分的详细参数含义，好像没有det部分的参数详解

### ISSUE THREAD

**Issue by jiegeng321** [PaddlePaddle/PaddleOCR#676]
rec部分是有参数详解/doc/doc_ch/config.md，但det部分好像没找到。想知道后处理中unclip_ratio ，box_thresh，thresh这几个参数的具体含义

**Comment by MissPenguin** [comment]
请参考faq：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q332%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%87%8C%E9%9D%A2%E6%A3%80%E6%B5%8B%E7%9A%84%E9%98%88%E5%80%BC%E8%AE%BE%E7%BD%AE%E4%B9%88

**Comment by jiegeng321** [comment]
好的，多谢
