### ISSUE TITLE
英文识别模型结果为中文乱码问题。

### ISSUE THREAD

**Issue by duyao666** [PaddlePaddle/PaddleOCR#6760]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/Ubuntu 18.04.5 LTS \n \l：
-版本号/Version：paddlepaddle-gpu==2.3.0.post110：
- 运行指令/python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_195.jpg" --det_model_dir="./inference/en_PP-OCRv3_det_infer/" --rec_model_dir="./inference/en_PP-OCRv3_rec_infer/"：
- 完整报错/Complete Error Message：
- 检测和识别均使用【英文超轻量PP-OCRv3模型（13.4M）】，代码为2.5版本。识别识别英文图片，检测准确，但是识别结果显示为中文。

**Comment by jolinchao** [comment]
确认看看dict是否设定错误

**Comment by duyao666** [comment]
> 确认看看dict是否设定错误

能具体一点吗？刚开始接触这个算法。

**Comment by tink2123** [comment]
试下这个命令，修改字典为英文：

```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_195.jpg" --det_model_dir="./inference/en_PP-OCRv3_det_infer/" --rec_model_dir="./inference/en_PP-OCRv3_rec_infer/" --rec_char_dict_path="ppocr/utils/en_dict.txt"
```

**Comment by duyao666** [comment]
> 试下这个命令，修改字典为英文：
> 
> ```
> python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_195.jpg" --det_model_dir="./inference/en_PP-OCRv3_det_infer/" --rec_model_dir="./inference/en_PP-OCRv3_rec_infer/" --rec_char_dict_path="ppocr/utils/en_dict.txt"
> ```
 太稳了老哥，成功解决了，谢谢！

**Comment by duyao666** [comment]
参数--rec_char_dict_path在tools/infer/utility.py文件中修改。
