### ISSUE TITLE
表格结构转换

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6762]
如果表格cell有坐标和和行列信息，怎样转换成html格式呢

**Comment by WenmuZhou** [comment]
要转换为html的话，还需要一个表格的结构信息，我们后续会开源一个pubtabnet数据格式的可视化工具

**Comment by ZTurboX** [comment]
> 要转换为html的话，还需要一个表格的结构信息，我们后续会开源一个pubtabnet数据格式的可视化工具

如果只有坐标可以转换为html吗

**Comment by ganggang233** [comment]
> 要转换为html的话，还需要一个表格的结构信息，我们后续会开源一个pubtabnet数据格式的可视化工具

您好，请问这个工具会在什么时候开源呢？

**Comment by WenmuZhou** [comment]
可以用这个将标注转换为html进行查看https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/table/convert_label2html.py
