### ISSUE TITLE
Meeting Compling Error When Deploying PaddleOCR Cpp Inference on Jetson AGX Xavier

### ISSUE THREAD

**Issue by SparkleXFantasy** [PaddlePaddle/PaddleOCR#6765]
I want to deploy the cpp inference version of PaddleOCR on AGX Xavier for better performance.
According to the instructions in cpp_infer, I download the cpp inference library from Paddle official website, complete the path for cuda/opencv/paddle inference library in `tools/build.sh` and run the command `sudo sh tools/build.sh`. 
When compling the executable file, the terminal outputs the error for makefile.

cc1plus: fatal error: CMakeFiles/ppocr.dir/src/XXX.cpp.d: No such file or directory

I wonder whether there is any problem or solution.

System Environment：Jetson AGX Xavier
Jetson version:4.6
Opencv Version:3.4.16
GCC Version: 7.5.0

Version：Paddle：2.3.0  PaddleOCR：2.3.0

Related components：deploy/cpp_infer

Command Code：
sudo sh tools/build.sh

The file `build.sh`:

OPENCV_DIR=/usr/local/opencv
LIB_DIR=/home/agxmaster/code/paddle_inference_install_dir
CUDA_LIB_DIR=/usr/local/cuda/lib64
CUDNN_LIB_DIR=/usr/local/cuda/lib64

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=OFF \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DWITH_TENSORRT=ON \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \
    -DTENSORRT_DIR=${TENSORRT_DIR} \

make -j

Complete Error Message：
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/agxmaster/software/opencv/opencv-3.4.16 (found version "3.4.16") 
cmake cxx flags -g -o3  -std=c++11
-- Found Git: /usr/bin/git (found version "2.17.1") 
default cmake for auto_log, no need to compile
-- Configuring done
-- Generating done
-- Build files have been written to: /home/agxmaster/code/PaddleOCR/deploy/cpp_infer/build
make[2]: *** No rule to make target '/lib/libnvinfer.so', needed by 'ppocr'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  9%] Building CXX object CMakeFiles/ppocr.dir/src/clipper.cpp.o
[ 27%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 27%] Building CXX object CMakeFiles/ppocr.dir/src/args.cpp.o
[ 36%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 54%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 54%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
[ 63%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
[ 72%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
[ 81%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/main.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/clipper.cpp.d: No such file or directory
compilation terminated.
[ 90%] Building CXX object CMakeFiles/ppocr.dir/src/paddleocr.cpp.o
CMakeFiles/ppocr.dir/build.make:103: recipe for target 'CMakeFiles/ppocr.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/main.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:89: recipe for target 'CMakeFiles/ppocr.dir/src/clipper.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/clipper.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/utility.cpp.d: No such file or directory
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_rec.cpp.d: No such file or directory
compilation terminated.
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_cls.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_det.cpp.d: No such file or directory
CMakeFiles/ppocr.dir/build.make:145: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o] Error 1
compilation terminated.
CMakeFiles/ppocr.dir/build.make:201: recipe for target 'CMakeFiles/ppocr.dir/src/utility.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/utility.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:117: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/preprocess_op.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/args.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:187: recipe for target 'CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:131: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_det.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_det.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:75: recipe for target 'CMakeFiles/ppocr.dir/src/args.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/args.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/postprocess_op.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/paddleocr.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:173: recipe for target 'CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:159: recipe for target 'CMakeFiles/ppocr.dir/src/paddleocr.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/paddleocr.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/ppocr.dir/all' failed
make[1]: *** [CMakeFiles/ppocr.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by n0099** [comment]
checkout https://github.com/PaddlePaddle/PaddleOCR/issues/6777#issuecomment-1201023233
