### ISSUE TITLE
希望能对配置文件内的transforms参数进行详细说明

### ISSUE THREAD

**Issue by KagamigawaMeguri** [PaddlePaddle/PaddleOCR#6770]
在文档中对于`transforms`参数只有简单的`ppocr/data/imaug`。但这几个参数会引发难以溯源的错误。

以官方配置文件[det_res18_db_v2.0.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/configs/det/det_res18_db_v2.0.yml)为例。

假如注释掉`KeepKeys`，则会报`all input arrays must have the same shape`错误，而错误位置是`paddle\fluid\dataloader\collate.py`的60行`batch = np.stack(batch, axis=0)`处。
假如注释掉`MakeShrinkMap`保留`KeepKeys`，则会报`KeyError: 'shrink_map'`错误。

翻了翻代码，发现在`ppocr/data/imaug`下的几个文件中直接使用了这几个键名。
这意味着这几个参数与这几个键名存在对应关系且需要再KeepKeys中写明，否则就会报十分反直觉且难以判断的错误。
所以希望能对此进行修正，或在文档中进行详细说明。

感谢。

**Comment by WenmuZhou** [comment]
在数据进入KeepKeys之前都是字典的形式，然后通过KeepKeys的参数对字典里的值进行过滤，并转换为list进行返回，你的两处改动都是不符合要求的，所以会报错
