### ISSUE TITLE
能不能训练泰文模型啊？很多小语种的模型都提供了

### ISSUE THREAD

**Issue by zhsunlight** [PaddlePaddle/PaddleOCR#6772]
泰国也有很多华人居住，人口七千万，使用需求很强烈。泰文也不复杂，训练这样的模型应该不需要太多的投入。希望可以提供泰语的训练模型。很多小语种，使用人口才几十万的都提供了。

**Comment by MissPenguin** [comment]
您好，很多人反映有泰语识别的需求，我们已经加到计划中了，欢迎持续关注哈，如果您这边有语料、字体等数据也非常欢迎提供~

**Comment by zhsunlight** [comment]
感谢回复。
泰语字体容易找。搜索 tahoma.ttf 和 tahomabd.ttf 可找到免费的字体下载 [tahoma.ttf](https://freefontsdownload.net/free-tahoma-font-31027.htm)、[tahomabd.ttf](https://fontsforyou.com/en/fonts/60807-tahomabd.font)

语料可在 github找到  Apache-2.0 license 的，参考如下链接：
[TH National Document OCR (THND OCR)](https://github.com/copninich/TH-National-Document-OCR-Part-I)
[TH National Document OCR (THND OCR)](https://github.com/copninich/TH-National-Document-OCR)
![image](https://user-images.githubusercontent.com/56898908/177108256-ec9eb92a-58ff-4d96-8dda-0fda84205608.png)

如果有需要，也可以联系当地的[华人朋友](https://github.com/tanapa2018)帮助制作全新的语料。

**Comment by MissPenguin** [comment]
> 感谢回复。 泰语字体容易找。搜索 tahoma.ttf 和 tahomabd.ttf 可找到免费的字体下载 [tahoma.ttf](https://freefontsdownload.net/free-tahoma-font-31027.htm)、[tahomabd.ttf](https://fontsforyou.com/en/fonts/60807-tahomabd.font)
> 
> 语料可在 github找到 Apache-2.0 license 的，参考如下链接： [TH National Document OCR (THND OCR)](https://github.com/copninich/TH-National-Document-OCR-Part-I) [TH National Document OCR (THND OCR)](https://github.com/copninich/TH-National-Document-OCR) ![image](https://user-images.githubusercontent.com/56898908/177108256-ec9eb92a-58ff-4d96-8dda-0fda84205608.png)
> 
> 如果有需要，也可以联系当地的[华人朋友](https://github.com/tanapa2018)帮助制作全新的语料。

收到~ 非常有用的信息！👍
