### ISSUE TITLE
在nvidia Jetson AGX 上使用C++  tensorrt部署paddleocr的编译问题

### ISSUE THREAD

**Issue by FangJingYunner** [PaddlePaddle/PaddleOCR#6777]
你好，我想在AGX Xavier 上部署C++ TensorRT版本的PaddleOCR。我是按照cpp_infer 里面的readme内容来的。我在官网的预测库上下载了`Jetpack4.6: nv-jetson-cuda10.2-cudnn8.2-trt8.0(xavier)`这个版本的预测库并将其解压到paddle_inference_install_dir文件夹中。然后在`tools/build.sh`当中修改了相对应的路径。但是在执行sh tools/build.sh时候遇到了下面的报错

cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_cls.cpp.d: No such file or directory

请问这个有什么好的解决办法吗？

System Environment：Jetson AGX Xavier
Jetson version:4.6
Opencv Version:3.4.16
GCC Version: 7.5.0
cmake: 3.23.1
PaddleOCR: release/2.5

Related components：deploy/cpp_infer

Command Code：
sudo sh tools/build.sh

'build.sh'文件如下:

```sh
OPENCV_DIR=/usr/local/opencv
LIB_DIR=/home/agxmaster/code/paddle_inference_install_dir
CUDA_LIB_DIR=/usr/local/cuda/lib64
CUDNN_LIB_DIR=/usr/local/cuda/lib64
BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=OFF \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DWITH_TENSORRT=ON \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \
    -DTENSORRT_DIR=${TENSORRT_DIR} \

make -j
```
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/agxmaster/software/opencv/opencv-3.4.16 (found version "3.4.16") 
cmake cxx flags -g -o3  -std=c++11
-- Found Git: /usr/bin/git (found version "2.17.1") 
default cmake for auto_log, no need to compile
-- Configuring done
-- Generating done
-- Build files have been written to: /home/agxmaster/code/PaddleOCR/deploy/cpp_infer/build
make[2]: *** No rule to make target '/lib/libnvinfer.so', needed by 'ppocr'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 36%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 36%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 18%] Building CXX object CMakeFiles/ppocr.dir/src/args.cpp.o
[ 45%] Building CXX object CMakeFiles/ppocr.dir/src/clipper.cpp.o
[ 54%] Building CXX object CMakeFiles/ppocr.dir/src/paddleocr.cpp.o
[ 63%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
[ 72%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_cls.cpp.d: No such file or directory
compilation terminated.
[ 81%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
[ 90%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
CMakeFiles/ppocr.dir/build.make:117: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/args.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:75: recipe for target 'CMakeFiles/ppocr.dir/src/args.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/args.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/preprocess_op.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/paddleocr.cpp.d: No such file or directory
compilation terminated.
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/clipper.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:187: recipe for target 'CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_det.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:159: recipe for target 'CMakeFiles/ppocr.dir/src/paddleocr.cpp.o' failed
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/utility.cpp.d: No such file or directory
make[2]: *** [CMakeFiles/ppocr.dir/src/paddleocr.cpp.o] Error 1
compilation terminated.
CMakeFiles/ppocr.dir/build.make:89: recipe for target 'CMakeFiles/ppocr.dir/src/clipper.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/clipper.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/main.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:131: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_det.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_det.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:201: recipe for target 'CMakeFiles/ppocr.dir/src/utility.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/utility.cpp.o] Error 1
CMakeFiles/ppocr.dir/build.make:103: recipe for target 'CMakeFiles/ppocr.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/main.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/ocr_rec.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:145: recipe for target 'CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o] Error 1
cc1plus: fatal error: CMakeFiles/ppocr.dir/src/postprocess_op.cpp.d: No such file or directory
compilation terminated.
CMakeFiles/ppocr.dir/build.make:173: recipe for target 'CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o' failed
make[2]: *** [CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/ppocr.dir/all' failed
make[1]: *** [CMakeFiles/ppocr.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hunter2009pf** [comment]
我也遇到一样的问题

**Comment by FangJingYunner** [comment]
@hunter2009pf 不知道这个咋整了。。机器人为什么还没分配大佬给我们解答呀。

**Comment by FangJingYunner** [comment]
cmakelist 里面-o3注释一下就好了




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Monday, Jul 4, 2022 10:31 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [PaddlePaddle/PaddleOCR] 在nvidia Jetson AGX 上使用C++  tensorrt部署paddleocr的编译问题 (Issue #6777)





 
我也遇到一样的问题

**Comment by luohaihan** [comment]
cmake cxx flags -g -o3 -std=c++11里的"o"要改成大写的，麻了

**Comment by JingliangGao** [comment]
> cmake cxx flags -g -o3 -std=c++11里的"o"要改成大写的，麻了

大神啊，果然改这里就没问题了

**Comment by zyzz1974** [comment]
请问是改哪里的文件，我没有cmakelist，

**Comment by luohaihan** [comment]
> 请问是改哪里的文件，我没有cmakelist，

用c++编译的是deploy/cpp_infer文件下的CMakeLists.txt，不过我看新版本的文件里没有我说的这条语句

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212469439-25dca355-7ce8-4da5-9530-b8eaf01fd635.png)
我的一直报这个错，请问你的出现过吗，怎么解决呢

**Comment by luohaihan** [comment]
> ![image](https://user-images.githubusercontent.com/99126288/212469439-25dca355-7ce8-4da5-9530-b8eaf01fd635.png) 我的一直报这个错，请问你的出现过吗，怎么解决呢

我没遇到过你这情况，我都不知道你编译的是哪个文件夹下的CMakeLists.txt文件，因为deploy/cpp_infer/src文件夹下是没有common和cpu这两个文件夹的。正常情况下是遇不到你这两个error的

**Comment by zyzz1974** [comment]
我就是照这个编译的
![image](https://user-images.githubusercontent.com/99126288/212470161-25b0683c-dc48-4f19-b6a9-a6afd56000fa.png)

**Comment by luohaihan** [comment]
> 我就是照这个编译的 ![image](https://user-images.githubusercontent.com/99126288/212470161-25b0683c-dc48-4f19-b6a9-a6afd56000fa.png)

你一步应该是在编译paddlpaddle而不是paddlOCR吧，我几个月没碰这玩意，编译步骤忘得差不多了，应该帮不到你。不过我记得官网有编译好的paddlpaddle，你可以直接拿过来用

**Comment by zyzz1974** [comment]
好的谢谢
