### ISSUE TITLE
训练精度和实际预测精度不匹配

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleOCR#6778]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 训练精度的bset比如是0.9 但是我用训练好的模型去预测就只有0.45左右了感觉/2了不知道是什么问题
- 英文的我训练了一个就跟预测的精度吻合。我测试是用训练的时候的测试文件val_list.txt里的图片批量测试的
- 使用的模型：ch_PP-OCRv3_rec，预训练模型也加载了

**Comment by MissPenguin** [comment]
测试命令贴一下看看哈
