### ISSUE TITLE
table_structure有日语模型吗？

### ISSUE THREAD

**Issue by linling0103** [PaddlePaddle/PaddleOCR#6779]
en_ppocr_mobile_v2.0_table_structure这个好像有只有英语模型，
要训练日语模型的话，大概的的思路可以提示一下吗？

**Comment by MissPenguin** [comment]
可以合成一批日语的表格数据重新训练，业界有开源的表格合成工具：https://github.com/hassan-mahmood/TIES_DataGeneration
