### ISSUE TITLE
Visual Studio 2019编译PaddleOCR C++库报错

### ISSUE THREAD

**Issue by XuHub** [PaddlePaddle/PaddleOCR#678]
在windows 10系统下使用Visual Studio 2019编译PaddleOCR 在C++项目中使用的库是报错，提示
【'/paddle/lib/libpaddle_fluid.lib', needed by 'ocr_system.exe', missing and no known rule to make it	C:\xj\PaddlePaddle\PaddleOCR\deploy\cpp_infer\out\build\x64-Debug\cpp_infer	C:\xj\PaddlePaddle\PaddleOCR\deploy\cpp_infer\out\build\x64-Debug\ninja】
使用多种方式编译，都无法编译出lib或者dll文件

**Comment by littletomatodonkey** [comment]
看着是没有找到预测库的路径，你的cmake路径配置都是正确的吗？可以截图看下

**Comment by XuHub** [comment]
hello，附件中是包含的两个图，分别对应的是
1、vs.jpg是cmake编译后用vs2019打开后编译的错误信息
2、cmake.jpg是cmake相关的配置信息





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午2:16
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"徐俊"<285109587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] Visual Studio 2019编译PaddleOCR C++库报错 (#678)





 
看着是没有找到预测库的路径，你的cmake路径配置都是正确的吗？可以截图看下

**Comment by littletomatodonkey** [comment]
你好，邮件里好像没有附件，你是按照这里操作的吗？建议使用带mkl的预测库：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md

**Comment by XuHub** [comment]
是的，都是安装流程安装的额，软件版本都是一样的









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午3:27
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"徐俊"<285109587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] Visual Studio 2019编译PaddleOCR C++库报错 (#678)





 
你好，邮件里好像没有附件，你是按照这里操作的吗？建议使用带mkl的预测库：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/docs/windows_vs2019_build.md

**Comment by OliverLPH** [comment]
@XuHub 
可能因为libpaddle_fluid.lib这个文件太大了，Visual studio编译时就会报找不到`libpaddle_fluid.lib`
可以参考下这个issue [win7调用官方v1.7的库，编译出错：“无法打开文件libpaddle_fluid.lib”
](https://github.com/PaddlePaddle/Paddle/issues/22993)

**Comment by yjmm10** [comment]
> 在windows 10系统下使用Visual Studio 2019编译PaddleOCR 在C++项目中使用的库是报错，提示
> 【'/paddle/lib/libpaddle_fluid.lib', needed by 'ocr_system.exe', missing and no known rule to make it C:\xj\PaddlePaddle\PaddleOCR\deploy\cpp_infer\out\build\x64-Debug\cpp_infer C:\xj\PaddlePaddle\PaddleOCR\deploy\cpp_infer\out\build\x64-Debug\ninja】
> 使用多种方式编译，都无法编译出lib或者dll文件

你可以查下*\fluid_inference\paddle\lib下面的dll是不是libpaddle_fluid.lib、paddle_fluid.dll，修改成上面那个文件名可以解决
