### ISSUE TITLE
PPOcr-v2 蒸馏出来的student.params转nb文件，安卓运行报错 

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleOCR#6784]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
有报错信息吗，
