### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by meng8407** [PaddlePaddle/PaddleOCR#6797]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
QObject::moveToThread: Current thread (0x56150b836f90) is not the object's thread (0x56150f311000).
Cannot move to target thread (0x56150b836f90)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ai-developer/anaconda3/envs/paddle/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1657020608 (unix time) try "date -d @1657020608" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000299e) received by PID 10654 (TID 0x7f025553b700) from PID 10654 ***]

已放弃 (核心已转储)
![2022-07-05 19-50-59屏幕截图](https://user-images.githubusercontent.com/69879311/177322064-f6a0b59a-5225-4c66-8e9c-4471d0d7e049.png)

**Comment by dengbuqi** [comment]
I have the same problem, see my solution!
https://github.com/PaddlePaddle/PaddleOCR/issues/6798#issuecomment-1175154115
