### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by dengbuqi** [PaddlePaddle/PaddleOCR#6798]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04 Anaconda
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.5.0.3 问题相关组件/Related components：PPOCRLabel-2.0.1, opencv cann't find xcb
- 运行指令/Command Code：PPOCRLabel --kie True
- 完整报错/Complete Error Message：

> QObject::moveToThread: Current thread (0x5630386dcad0) is not the object's thread (0x56303c1bcc00).
> Cannot move to target thread (0x5630386dcad0)
> 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/deng/data/anaconda3/envs/ve/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
> 
> 
> 

> C++ Traceback (most recent call last):

> No stack trace in paddle, may be caused by external reasons.
> 

> Error Message Summary:

> FatalError: `Process abort signal` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1657031986 (unix time) try "date -d @1657031986" if you are using GNU date ***]
>   [SignalInfo: *** SIGABRT (@0x3e800182cd1) received by PID 1584337 (TID 0x7f0357db34c0) from PID 1584337 ***]
> 
> Aborted (core dumped)
>

**Comment by dengbuqi** [comment]
In my solution, I install the opencv-python-headless and everything works.

> pip install opencv-python-headless==[same version as the opencv-python]

**Comment by andyjpaddle** [comment]
you can refer this doc https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/PPOCRLabel#12-install-and-run-ppocrlabel

**Comment by dengbuqi** [comment]
> you can refer this doc https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/PPOCRLabel#12-install-and-run-ppocrlabel

Thank you! My system is ubuntu20.04 and I follow the [doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/PPOCRLabel#1-installation-and-run). The error still happened. 
But after I install the opencv-python-headless. I can run the PPOCRLabel.

> pip install opencv-python-headless==[same version as the opencv-python]
