### ISSUE TITLE
识别模型输出字母大小写问题

### ISSUE THREAD

**Issue by Zoushuang86** [PaddlePaddle/PaddleOCR#680]
我训练识别模型自定义的列表中字母全是大写，但是在预测时输出的却是小写，请问是什么原因呢？

**Comment by littletomatodonkey** [comment]
你预测的时候需要指定rec_char_dict_path为你自己的字典路径，自定义字典的话，需要指定`character_type=ch`，否则ppocr会把所有字典中的英文字符都变成小写（英文情况下）

https://github.com/PaddlePaddle/PaddleOCR/blob/5fb3c419c980a112cb69b87019d18157926edc41/ppocr/utils/character.py#L75

**Comment by Zoushuang86** [comment]
好的，谢谢。

**Comment by yizhipipixia** [comment]
请问,楼主是怎么改的呢?寻着找过去, self.character_str = "0123456789abcdefghijklmnopqrstuvwxyz", 改改成怎么样,才能输出安装识别的图片那样,有大写有小写呢?

**Comment by yizhipipixia** [comment]
> 我训练识别模型自定义的列表中字母全是大写，但是在预测时输出的却是小写，请问是什么原因呢？

请问自定义字典该写成怎样成能区别输出大写和小写呢

**Comment by youde2000** [comment]
但是我用了之后，还是只输出小写字母
character_dict_path: ./ppocr/utils/ppocr_keys_v1.txt

图片上明明是大写的字母，输出结果都转成小写了
