### ISSUE TITLE
ACC IS 0

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6803]
我训练自己的数据 accuracy 训练中有70% 到最后变0%

所以训练中的acc是 TRAIN DATA?而不是VAL DATA

![image](https://user-images.githubusercontent.com/108393685/177467706-6fc14cd6-ce54-4d43-8fcc-f5fea1f83cab.png)

**Comment by tink2123** [comment]
是的，训练中的acc指的是train_acc

**Comment by Alice-Thirty** [comment]
what is norm_edit_dis

**Comment by RichardRivaldo** [comment]
@tink2123 @Alice-Thirty Following up on this question, so what does the result mean? The first acc in the picture is acc of train data while the last is acc of eval data or? Need some clarification on whether this means that the model is actually not trained at all and how to fix this.
