### ISSUE TITLE
dict problem

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6804]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/recognition.md#14-%E5%AD%97%E5%85%B8
我的训练资料与标记含有CH and EN , 我可以字典只包含英文来训练吗?
?

**Comment by tink2123** [comment]
可以，标记中如果包含非英文的字符，此条数据将会被跳过。

**Comment by Alice-Thirty** [comment]
假设
label
```
123A.jpg  123A
ABC.jpg   ABC
111.jpg   111
```

dict
```
A
B
C
```

所以这训练会跳过这两张图的训练?
123A.jpg
111.jpg
