### ISSUE TITLE
lmdb convert to simpledata

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6805]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/recognition.md#13-%E6%95%B0%E6%8D%AE%E4%B8%8B%E8%BD%BD

python gen_label.py --mode="rec" --input_path="{path/of/origin/label}" --output_label="rec_gt_label.txt"
似乎無法轉 lmdb

**Comment by Alice-Thirty** [comment]
https://github.com/OneYearIsEnough/PaddleOCR-Recog-LmdbDataset-Conversion

**Comment by tink2123** [comment]
gen_label.py 并不可以是用来转换LDMB数据的，上面贴的 `[PaddleOCR-Recog-LmdbDataset-Conversion]` 可以。
