### ISSUE TITLE
paddle ocr自定义训练模型在ios端如何部署？

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#6808]
请问各位大佬：
如果我自己训练了多语言识别模型，怎么载ios端部署呢？可以实现嘛？
1.骨干网络转成onnx模型。但是其他的网络模型如何处理？
2.需要paddle_LITE，opencv等其他一些第三方库嘛？
3.转成c++代码推理是完全可以实现的嘛？

**Comment by WenmuZhou** [comment]
1. 不需要转换为onnx，模型需要使用paddlelite进行转换，具体可以参考这个https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/develop/ocr/ios/ppocr_demo/ppocr_demo/README.md
2. c++代码推理可以完全实现

**Comment by GUOhm230** [comment]
非常感谢回复。因为不太熟悉paddleLite 所以还是偏向于转onnx。
这个转onnx或者mnn，之后的推理操作和pth转onnx再转mnn的推理是一样的吧？

**Comment by WenmuZhou** [comment]
是的
