### ISSUE TITLE
实际训练与标记问题

### ISSUE THREAD

**Issue by WIKI2020** [PaddlePaddle/PaddleOCR#681]
（1）请问在训练时候，您们是把图片高度先resize成48保存，算法再resize成32这样？
（2）有没有验证图片高度，或者宽高比怎样对算法最匹配？
（3）标记时候横的文字没问题，那竖的文字标记之后怎么处理？（只考虑横竖，暂不考虑弯曲的或者其它复杂的排列情况）

**Comment by WIKI2020** [comment]
竖的文字有一定长度

**Comment by WenmuZhou** [comment]
1. 无论图片高度多大，最后都是resize成32，具体保存时候的高度，看crop的情况
2. 没有做这方面的实验
3. 竖直的选择成横条进行训练

**Comment by WIKI2020** [comment]
（3）意思是把竖的文字转90°变成横条去训练吗？那字是歪90°的

**Comment by WenmuZhou** [comment]
就是这样
