### ISSUE TITLE
在android手机上测试pp-OCRv3识别模型比pp-OCRv2识别模型慢

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleOCR#6810]
两个版本的识别模型都是paddle训练好的模型，移植到android手机上运行，测试一张包含一行5个子的图片，pp-OCRv2耗时65ms至78ms，pp-OCRv3耗时85至100ms。但说明文档上说应该是v3版更快的，是不是指在电脑上用gpu环境下v3版本才会快一些？

**Comment by lzh111222334** [comment]
现在android支持V3模型了吗？大佬

**Comment by lzh111222334** [comment]
大佬可以留个联系方式吗 我也在做android端部署

**Comment by WenmuZhou** [comment]
这个耗时和多个因素有关，包括手机的发热与散热问题，手机后台程序是否很多，并且会有波动

**Comment by GUOhm230** [comment]
> 两个版本的识别模型都是paddle训练好的模型，移植到android手机上运行，测试一张包含一行5个子的图片，pp-OCRv2耗时65ms至78ms，pp-OCRv3耗时85至100ms。但说明文档上说应该是v3版更快的，是不是指在电脑上用gpu环境下v3版本才会快一些？

同求联系方式，正在做安卓的部署。
