### ISSUE TITLE
paddleocr工程文件和调用paddleocr类的识别结果准确率不一样

### ISSUE THREAD

**Issue by AKA-WDNMD** [PaddlePaddle/PaddleOCR#6816]
（同一模型）运行paddleocr工程文件里的predict_system.py或predict_rec.py与在paddleocr库里调用PaddleOCR的类的识别结果后者的准确率会变低；paddleocr版本都是2.5；
以验证码识别为例（图片名为验证码的正确结果）

![86a4c199cdf7158b30afedaba33821f](https://user-images.githubusercontent.com/77567881/177676222-7bd858fb-fddd-49d3-bb28-ce77c08e50d2.png)
![b73be95a5d8c64ef57593a4d86b1b8e](https://user-images.githubusercontent.com/77567881/177676238-2273fc8e-8110-4cf3-b20c-ef2b4931a36e.png)

**Comment by AKA-WDNMD** [comment]
第一张图是paddleocr工程文件识别结果，二张是调用paddleocr类的识别结果

**Comment by xiafeishuangjia** [comment]
我也有这样的问题，不知道为什么，有人可以解答吗。。。。

**Comment by andyjpaddle** [comment]
更新一下最新的paddleocr包哈，同时更新一下最新代码
