### ISSUE TITLE
OCRV3在训练识别模型时验证集的准确率一直都是0，在一前训练OCRV2中效果差但是有准确率，不是很理解这个情况

### ISSUE THREAD

**Issue by wfm777** [PaddlePaddle/PaddleOCR#6817]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.5  PaddleOCR：OCRv3 
- 运行指令/Command Code：python3 -m paddle.distributed.launch --gpus '0,1'  tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml 
- 完整报错/Complete Error Message：
![1657164724700](https://user-images.githubusercontent.com/93081669/177685381-9d5d7bef-39d2-4b94-9791-3e136a7b9a52.jpg)

**Comment by wfm777** [comment]
我用的数据是官网开源的一个中英文数据，在加上一些我自己的数据不到五六百张左右，图片最大的宽度是512（我自己添加的一些数据，只是极个别的三四个图片），用的yml文件是官方默认的，只是调整了训练周期（1200）和批次（64）

**Comment by littletomatodonkey** [comment]
看着是过拟合到训练集里面去了，导致验证集精度很差，可以再分析调整下数据集分布
