### ISSUE TITLE
rec_mv3_none_bilstm_ctc.yml  LMDBDataSet数据 配置文件怎么写 我的为什么不对

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleOCR#6819]
![image](https://user-images.githubusercontent.com/77281977/177686631-aebbd4b5-5523-43a2-b138-e3daf0e51b2d.png)
![image](https://user-images.githubusercontent.com/77281977/177686726-c6f9be73-78a8-4e55-bbee-7d12a4385958.png)
我的写法
![image](https://user-images.githubusercontent.com/77281977/177687006-2cc6cfb8-085f-4183-a73c-b8fe89ad713e.png)

**Comment by tink2123** [comment]
LMDBDataSet 修改成 SimpleDataSet
