### ISSUE TITLE
μ  ±  & 等特殊符号识别不出来

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleOCR#6826]
用ocr进行识别，发现这类特殊符号的识别效果很差，μ识别成0，有没有针对这样的特殊字符的模型，如果是自己训练的话，有没有已经定义好的字典来提供使用

**Comment by littletomatodonkey** [comment]
你好，这些字符都是在默认的字典里的，建议针对特殊数据合成一批，进行微调

**Comment by thanh15dt2** [comment]
How many sample for one special character?

**Comment by littletomatodonkey** [comment]
> How many sample for one special character? @littletomatodonkey

you can refer to this tut for more details: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/finetune.md
