### ISSUE TITLE
关于SRN的梯度传播问题

### ISSUE THREAD

**Issue by hao6699** [PaddlePaddle/PaddleOCR#683]
https://github.com/PaddlePaddle/PaddleOCR/blob/5fb3c419c980a112cb69b87019d18157926edc41/ppocr/modeling/heads/rec_srn_all_head.py#L110

你好, 我看在GRSM模块中, 设置了word_ids.stop_gradient = True, 这是否意味着GRSM模块的梯度流并不会传播到前面的网络中, 如PVAM和Backbone模块? 如果是, 那GRSM是不是相当于一个单独的模块, 并不依赖于前面网络的输出? 既然如此的话, 何不单独拿正确的标签来训练GRSM模块, 以得到更为准确的语义特征. 当然, GRSM模块的代码里包含了word_out, 需要用到前面层的输出, 但是我觉得它也可以归到PVAM模块中, 并不会影响单独GRSM的训练

**Comment by tink2123** [comment]
是的，gsrm模块的梯度不会传回去。在两阶段的训练方式里，是单独训练GSRM模块的，为了简化训练流程，我们这里修改成了one stage 训练。如果您自己的语料充足的话，可以单独训练GSRM模块，关闭梯度会加快收敛。

**Comment by hao6699** [comment]
好的,谢谢
