### ISSUE TITLE
自定义训练的法德综合识别模型无法识别空格

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#6833]
yml中已经设置识别空格为True
另外我也在dict中加入了空格
训练数据使用的是：ICDAR 2019 Robust Reading Challenge on Multi-lingual scene text detection and recognition中的法语和德语的word clip数据
训练之后测试，无法测试出空格。请问这是怎么回事呢？是不是我的训练数据中不包含空格？
或者是因为CTCLoss计算中，用空格隔开单词，导致后面decode时无法识别？

**Comment by littletomatodonkey** [comment]
你好，需要合成一批空格数据加入训练集合

**Comment by GUOhm230** [comment]
> 你好，需要合成一批空格数据加入训练集合

您好。感谢大佬回复。
我使用styliText进行合成，但是无法合成空格？
字典中有空格的

**Comment by littletomatodonkey** [comment]
你好，目前可以用textrender去合成一批数据哈

**Comment by GUOhm230** [comment]
> 你好，目前可以用textrender去数据哈

您好，感谢回复！
我尝试了用textrender合成英文数据。得到的结果也没有空格，而且图片随机合成。合成的单词很多没有实际意义。
请问用styleText怎么做到合成空格数据？
