### ISSUE TITLE
文字检测不完整

### ISSUE THREAD

**Issue by redsoul233** [PaddlePaddle/PaddleOCR#6835]
对书本进行文字识别，但是中间大段的文字识别不出来
![img](https://user-images.githubusercontent.com/60600513/177988186-c29f7e78-34c3-4716-a45c-cf058d01a011.jpg)
![result](https://user-images.githubusercontent.com/60600513/177988296-61c400de-ebf9-41f4-b6e0-cd55caa975c7.jpg)
代码使用的python示例
`from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False,
                rec_model_dir='./inference/ch_PP-OCRv3_rec_infer/',
                cls_model_dir='./inference/ch_ppocr_mobile_v2.0_cls_infer/',
                det_model_dir='./inference/ch_PP-OCRv3_det_infer/')

img_path = './testpic/img.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

# 显示结果
from PIL import Image

image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')`

**Comment by littletomatodonkey** [comment]
你好，在初始化的时候，可以指定计算方式为slow

```
ocr = PaddleOCR(use_angle_cls=False, lang="ch", use_gpu=False, det_db_score_mode="slow")
```

更多参数介绍可以参考: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/inference_args.md

上面这种图的结果如下

![result_2](https://user-images.githubusercontent.com/14270174/178132041-b1247444-5e40-45fb-a962-0f841c42d6e8.jpg)

**Comment by redsoul233** [comment]
十分感谢，对我帮助很大。

littletomatodonkey ***@***.***> 于2022年7月10日周日 13:03写道：
