### ISSUE TITLE
Mac M1 Pro can't install paddleOCR2.0.1~2.5.0.3, but I can install paddleOCR 1.1.1 and run successful.

### ISSUE THREAD

**Issue by Lawyer-ray** [PaddlePaddle/PaddleOCR#6838]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MacBook Pro（14英寸，2021年），Apple M1 Pro 16 GB，
- 版本号/Version：Pycharm2022.1.2 and Anaconda create Python 3.8 environment.
- Paddle：  Monterey 12.3
- PaddleOCR：2.0.1~2.5.0.3
- 问题相关组件/Related components：PaddleOCR、Numpy
- 运行指令/Command Code：

1. python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple （运行正常，Run OK !）
2. pip install "paddleocr>=2.0.1"（运行失败，报错，Too much ERROR！）（如果我不指定paddleOCR1的版本号，会自动安装paddleOCR 1.1.1，并且可以正常运行使用，即2.0.1版本开始全部安装失败）

- 完整报错/Complete Error Message（详见markdown文档，太长了，这里传不上来）
[【Error Log】Mac M1 Pro can't install paddleOCR2.0.1~2.5.0.3.md](https://github.com/PaddlePaddle/PaddleOCR/files/9075892/Error.Log.Mac.M1.Pro.can.t.install.paddleOCR2.0.1.2.5.0.3.md)
：
- `ERROR: Cannot install paddleocr==2.0.1, paddleocr==2.0.2, paddleocr==2.0.3, paddleocr==2.0.4, paddleocr==2.0.5, paddleocr==2.0.6, paddleocr==2.2, paddleocr==2.2.0.1, paddleocr==2.2.0.2, paddleocr==2.3, paddleocr==2.3.0.1, paddleocr==2.3.0.2, paddleocr==2.4, paddleocr==2.4.0.1, paddleocr==2.4.0.2, paddleocr==2.4.0.3, paddleocr==2.4.0.4, paddleocr==2.5, paddleocr==2.5.0.2 and paddleocr==2.5.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    paddleocr 2.5.0.3 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.5.0.2 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.5 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.4.0.4 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.4.0.3 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.4.0.2 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.4.0.1 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.4 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.3.0.2 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.3.0.1 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.3 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.2.0.2 depends on opencv-contrib-python==4.4.0.46
    paddleocr 2.2.0.1 depends on opencv-contrib-python==4.2.0.32
    paddleocr 2.2 depends on opencv-contrib-python==4.2.0.32
    paddleocr 2.0.6 depends on opencv-python==4.2.0.32
    paddleocr 2.0.5 depends on opencv-python==4.2.0.32
    paddleocr 2.0.4 depends on opencv-python==4.2.0.32
    paddleocr 2.0.3 depends on opencv-python==4.2.0.32
    paddleocr 2.0.2 depends on opencv-python==4.2.0.32
    paddleocr 2.0.1 depends on opencv-python==4.2.0.32

To fix this you could try to:

1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/29346824/178091955-5d71f63b-6bd5-477e-88e4-cb29cb161124.png">

**Comment by Lawyer-ray** [comment]
救救孩子吧

**Comment by Lawyer-ray** [comment]
初步判断是opencv-contrib-python==4.4.0.46 并未提供mac arm版本，详见：https://pypi.org/project/opencv-contrib-python/4.4.0.46/#files

**Comment by Lawyer-ray** [comment]
@MissPenguin 如何用在安装paddleOCR过程中，使用Mac ARM 版本的 opencv-contrib-python 替代4.4.0.46版本？

**Comment by Lawyer-ray** [comment]
Facing the same Issue!

**Comment by LDOUBLEV** [comment]
M1应该也能安装opencv 4.4
<img width="429" alt="image" src="https://user-images.githubusercontent.com/26592129/178178188-d1f23bcd-f0cd-442a-8094-7fae347a31d1.png">

或者安装4.2版本也可以

**Comment by Lawyer-ray** [comment]
> M1应该也能安装opencv 4.4，我是在anaconda环境里安装的 <img alt="image" width="429" src="https://user-images.githubusercontent.com/26592129/178178188-d1f23bcd-f0cd-442a-8094-7fae347a31d1.png">
> 
> 或者安装4.2版本也可以

我不论用anaconda还是不用anaconda都装不上4.4.0.46版本的opencv，你装的是转义版本的吗？opencv的网站上都没有Mac Arm版的4.4.0.46 opencv

**Comment by Lawyer-ray** [comment]
> M1应该也能安装opencv 4.4，我是在anaconda环境里安装的 <img alt="image" width="429" src="https://user-images.githubusercontent.com/26592129/178178188-d1f23bcd-f0cd-442a-8094-7fae347a31d1.png">
> 
> 或者安装4.2版本也可以

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/29346824/178317375-e0a821b0-3681-410b-8b4b-923f8b14247a.png">
你是哪个版本的Python呀，我这边pip install whl都不行

**Comment by Lawyer-ray** [comment]
> M1应该也能安装opencv 4.4，我是在anaconda环境里安装的 <img alt="image" width="429" src="https://user-images.githubusercontent.com/26592129/178178188-d1f23bcd-f0cd-442a-8094-7fae347a31d1.png">
> 
> 或者安装4.2版本也可以

请告知如何在M1上安装opencv 4.4，如此多的M1用户都面临同样的问题，你们不打算给个教程么？我自己build openCV4.4 ARM版本都失败了

**Comment by LDOUBLEV** [comment]
我用的是python3.7;
如果你是3.9，可以安装opencv 4.5或者4.6版本

**Comment by Lawyer-ray** [comment]
> 我用的是python3.7; 如果你是3.9，可以安装opencv 4.5或者4.6版本

Anaconda 没法在 M1 Pro上创建 Python3.7，装了opencv4.6，再装paddleOCR，也提示要装openCV 4.4，有什么方法可以直接升级paddleOCR的依赖到openCV 4.6吗

**Comment by Lawyer-ray** [comment]
我们律所三台M1 Pro安装paddleOCR 2.5版本都报相同的错误，在Inter Mac、Windows下随便装 PaddleOCR 2.5，都不会出问题。

**Comment by LDOUBLEV** [comment]
> Anaconda 没法在 M1 Pro上创建 Python3.7

conda create -n py37 python=3.7 创建不了python3.7环境吗？

去掉4.4的依赖可以去掉版本号：https://github.com/PaddlePaddle/PaddleOCR/blob/2909454fb121a002290172525e414f3017923def/requirements.txt#L10

然后采用在PaddleOCR目录下 编译安装：
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x是paddleocr的版本号

**Comment by Lawyer-ray** [comment]
> 

终于安装成功了，感谢。
