### ISSUE TITLE
all ’T' recognition was wrong in our good quality image, please help

### ISSUE THREAD

**Issue by yestimes** [PaddlePaddle/PaddleOCR#6844]
we use paddleocr to extract SN of bottle which model named PPOCRv3 in chinese mode, but all images contains 'T' recognized as '7' or '1', please help us in more details caused or solution, thanks.
in other ways, we used model ch_ppocr_server_v2.0_xx deployed by paddleServing but beyond wrong still occurs. 

## this is our image
![image](https://user-images.githubusercontent.com/24623019/178142159-4f7a50d3-6099-4eac-bab0-79c4e7249047.png)

**Comment by LDOUBLEV** [comment]
Can you provide an OCR visualization for badcase analysis.
Guess that the position of the detection box may affect the recognition, you can try to increase the parameter of unclip ratio to enlarge the detected box.
