### ISSUE TITLE
Error converting paddleOCR into .exe file with pyinstaller

### ISSUE THREAD

**Issue by WENDGOUNDI** [PaddlePaddle/PaddleOCR#6847]
Hi everyone. I have made a GUI app built with pysimplegui where I am using the paddleocr for text extraction. Now while converting the file into a .exe using pyinstaller, the convertion is done correctly but I am facing some errors as displayed in the above picture when I launch the app. Anyone encountered the same issues? I have tried many debuuging methods but still stuck. Thanks in advance.

![paddleocr_error](https://user-images.githubusercontent.com/48753146/178225776-06d0f74e-acb3-4587-bc7e-762c2cf46231.PNG)

**Comment by andyjpaddle** [comment]
It seems like the paddle doesn't  run successfully, make sure you use the right version.

**Comment by WENDGOUNDI** [comment]
I have installed different versions of paddleocr but none of them worked. Any suggestion for the paddleocr version that could work?  Below are two envs with different version I am using.
## first env
![paddleocr_ver_2](https://user-images.githubusercontent.com/48753146/178403553-5e417ad1-4de2-4352-a75a-830acf047b68.PNG)

## second env
![paddleocr_ver_1](https://user-images.githubusercontent.com/48753146/178403555-5d5b9612-29e0-4486-8a28-e538894b86d8.PNG)

**Comment by andyjpaddle** [comment]
maybe you can try the gpu version paddle in first env
