### ISSUE TITLE
GPU训练中文语料失败

### ISSUE THREAD

**Issue by wpchenit** [PaddlePaddle/PaddleOCR#685]
系统: Centos7.7.1908  64
docker: 19.03.8
![image](https://user-images.githubusercontent.com/64248379/92429290-09e35980-f1c4-11ea-9798-c7bb118b8170.png)

![image](https://user-images.githubusercontent.com/64248379/92429280-ffc15b00-f1c3-11ea-9892-0d22cd69bdf8.png)

错误信息：E0908 03:01:56.636876   487 pybind.cc:1261] Cannot use GPU because there is no GPU detected on your machine.

**Comment by littletomatodonkey** [comment]
看着像是cuda版本不对（nvidia-smi提示N/A），你重装下cuda看下呢？推荐cuda10.0及以上版本

**Comment by wpchenit** [comment]
使用实体机训练没遇到这个问题。
