### ISSUE TITLE
model dim

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6851]
input size [1,3,48,320]
我用ppocrv3 model输出维度[1,40,11]
40是什么?
11是什么? (我训练了字元0-9  为何不是10)

**Comment by andyjpaddle** [comment]
40是输出sequence的长度，11是类别数+1(blank,ctc解码需要的特殊字符)

**Comment by Alice-Thirty** [comment]
40是输出sequence的长度 
代表最多可辨识40个字元吗?

40跟这个有何关系
max_text_length: &max_text_length 25

**Comment by andyjpaddle** [comment]
40是ctc中的时间步，25是最大的字符长度，可以去了解一下CTC算法的原理哈
