### ISSUE TITLE
SAR算法转换为推理模型后会识别padding部分

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#6855]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：baidu aistudio
- 版本号/Version：Paddle：  PaddleOCR 2.5

在使用训练的模型进行识别时效果较好，在转换为推理模型后对单个字符图片（较窄）识别效果差，多字符图片（较宽）效果较好。
对模型的预处理后处理还有转换模型的配置文件都检查过，没发现有问题
推理模型经常能将单字符原图作为第一个字符正确识别出来，但后面会有其他字符,如图
![image](https://user-images.githubusercontent.com/57863550/178413111-777f4066-284c-4472-b3cd-aea0700311f1.png)
训练模型识别为g，推理模型识别为g0612
经过尝试，发现与图片的pad resize有关系，对于一张较窄的图片，sar resize的处理是将其缩放后在右侧填充空白像素

def resize_norm_img_sar(self, img, image_shape,
                            width_downsample_ratio=0.25):
        imgC, imgH, imgW_min, imgW_max = image_shape
        h = img.shape[0]
        w = img.shape[1]
        valid_ratio = 1.0
        # make sure new_width is an integral multiple of width_divisor.
        width_divisor = int(1 / width_downsample_ratio)
        # resize
        ratio = w / float(h)
        resize_w = math.ceil(imgH * ratio)
        if resize_w % width_divisor != 0:
            resize_w = round(resize_w / width_divisor) * width_divisor
        if imgW_min is not None:
            resize_w = max(imgW_min, resize_w)
        if imgW_max is not None:
            valid_ratio = min(1.0, 1.0 * resize_w / imgW_max)
            resize_w = min(imgW_max, resize_w)
        resized_image = cv2.resize(img, (resize_w, imgH))
        resized_image = resized_image.astype('float32')
        # norm 
        if image_shape[0] == 1:
            resized_image = resized_image / 255
            resized_image = resized_image[np.newaxis, :]
        else:
            resized_image = resized_image.transpose((2, 0, 1)) / 255
        resized_image -= 0.5
        resized_image /= 0.5
        resize_shape = resized_image.shape
        **padding_im = -1.0 * np.ones((imgC, imgH, imgW_max), dtype=np.float32)
        padding_im[:, :, 0:resize_w] = resized_image**
        pad_shape = padding_im.shape
        return padding_im, resize_shape, pad_shape, valid_ratio

推理模型会对右边空白部分也识别出结果，我试过识别一张完全空白的图片（像素全为0），也会识别出结果
但是训练的模型就没有这样的问题，不知道是识别时pad resize的策略不一样吗
想请问怎么解决这个问题呢，让推理模型也达到一样的效果

**Comment by lzzzzj** [comment]
测试训练模型预测全0的图片，和推理模型会预测出一样的结果，但是单个字符图片训练模型可以准确识别
我查看代码两者的pad resize处理应该是一样的，我设置的size参数也是一样的，为什么预测的结果会不一样呢？谢谢解答

**Comment by lzzzzj** [comment]
predict_rec.py: line 348
`elif self.rec_algorithm == "SAR":
                valid_ratios = np.concatenate(valid_ratios)
                inputs = [
                    norm_img_batch,
                    valid_ratios,
                ]
                if self.use_onnx:
                    input_dict = {}
                    input_dict[self.input_tensor.name] = norm_img_batch
                    outputs = self.predictor.run(self.output_tensors,
                                                 input_dict)
                    preds = outputs[0]
                else:
                    **input_names = self.predictor.get_input_names()
                    for i in range(len(input_names)):
                        input_tensor = self.predictor.get_input_handle(
                            input_names[i])
                        input_tensor.copy_from_cpu(inputs[i])**
                    self.predictor.run()
                    outputs = []
                    for output_tensor in self.output_tensors:
                        output = output_tensor.copy_to_cpu()
                        outputs.append(output)
                    if self.benchmark:
                        self.autolog.times.stamp()
                    preds = outputs[0]`
这个代码中，predictor的input似乎根本没有接受valid_ratio的信息
valid_ratio存在inputs[1]中，然而len(input_names)=1，后面的
```
for i in range(len(input_names)):
    input_tensor = self.predictor.get_input_handle(input_names[i])
    input_tensor.copy_from_cpu(inputs[i])
```
也没有输入valid_ratio的信息到predictor，是不是这个原因导致识别了padding部分
我看到infer_rec.py中是输入了valid_ratio进行预测的
请问怎么样才可以解决呢

**Comment by andyjpaddle** [comment]
> predict_rec.py: line 348
> 
> ```
> elif self.rec_algorithm == "SAR":
>                 valid_ratios = np.concatenate(valid_ratios)
>                 inputs = [
>                     norm_img_batch,
>                     valid_ratios,
>                 ]
>                 if self.use_onnx:
>                     input_dict = {}
>                     input_dict[self.input_tensor.name] = norm_img_batch
>                     outputs = self.predictor.run(self.output_tensors,
>                                                  input_dict)
>                     preds = outputs[0]
>                 else:
>                     input_names = self.predictor.get_input_names()
>                     for i in range(len(input_names)):
>                         input_tensor = self.predictor.get_input_handle(
>                             input_names[i])
>                         input_tensor.copy_from_cpu(inputs[i])**
>                     self.predictor.run()
>                     outputs = []
>                     for output_tensor in self.output_tensors:
>                         output = output_tensor.copy_to_cpu()
>                         outputs.append(output)
>                     if self.benchmark:
>                         self.autolog.times.stamp()
>                     preds = outputs[0]
> ```
> 
> 这个代码中，predictor的input似乎根本没有接受valid_ratio的信息 valid_ratio存在inputs[1]中，然而len(input_names)=1，后面的
> 
> ```
> for i in range(len(input_names)):
>     input_tensor = self.predictor.get_input_handle(input_names[i])
>     input_tensor.copy_from_cpu(inputs[i])
> ```
> 
> 也没有输入valid_ratio的信息到predictor，是不是这个原因导致识别了padding部分 我看到infer_rec.py中是输入了valid_ratio进行预测的 请问怎么样才可以解决呢

可以更新一下最新代码试试哈
