### ISSUE TITLE
openvino里的det相关参数设置

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#6856]
- 系统环境：win10  openvino2.2.1 ocr:2.5 model:ch_PP-OCRv3_rec_infer/ch_PP-OCRv3_det_infer
- 如果设置det相关参数：
 # det config
det_db_thresh  0.3
det_db_box_thresh  0.3
det_db_unclip_ratio  1.5

在c++demo中可以通过配置文件来设置，那么openvino是如何设置如上参数的呢？
下面是openvino加载det模型的源码：
det_model_file_path = Path(r"D:\models\ch_PP-OCRv3_det_infer\inference.pdmodel")
core = Core()
det_model = core.read_model(model=det_model_file_path)
#指定了device_name是CPU
det_compiled_model = core.compile_model(model=det_model, device_name="CPU")
# get input and output nodes for text detection
det_input_layer = det_compiled_model.input(0)
det_output_layer = det_compiled_model.output(0)

看了下源代码，应该可以在调用det_compiled_model = core.compile_model(model=det_model, device_name="CPU")时指定一个字典{‘device_name’:'CPU'}，即：det_compiled_model = core.compile_model(model=det_model, config={'device_name':'CPU'})，但是报错：
Traceback (most recent call last):
  File "D:/work/projects/openvino_notebooks/notebooks/405-paddle-ocr-webcam/web_ocr.py", line 33, in <module>
    det_compiled_model = core.compile_model(model=det_model, config={'device_name':'CPU'})
  File "D:\work\apps\Anaconda3\lib\site-packages\openvino\runtime\ie_api.py", line 262, in compile_model
    super().compile_model(model, {} if config is None else config)
RuntimeError: Unsupported config key: device_name

**Comment by LDOUBLEV** [comment]
det_db_thresh 0.3
det_db_box_thresh 0.3
det_db_unclip_ratio 1.5

这些参数是在后处理时生效，
det_compiled_model = core.compile_model(model=det_model, device_name="CPU") 这里只是加载了模型，模型预测的输出是后处理函数的输入

**Comment by dengmingD** [comment]
> det_db_thresh 0.3 det_db_box_thresh 0.3 det_db_unclip_ratio 1.5
> 
> 这些参数是在后处理时生效， det_compiled_model = core.compile_model(model=det_model, device_name="CPU") 这里只是加载了模型，模型预测的输出是后处理函数的输入

我的意思是像openvino c++ 程序中可以设置参数，如下：其中有det_db_thresh、det_db_box_thresh
以下是openvino c++ demo中的代码，测试可用。
DEFINE_bool(use_gpu, true, "Infering with GPU or CPU.");
DEFINE_int32(gpu_id, 0, "Device id of GPU to execute.");
DEFINE_int32(gpu_mem, 4000, "GPU id when infering with GPU.");
DEFINE_int32(cpu_threads, 10, "Num of threads with CPU.");
DEFINE_bool(enable_mkldnn, true, "Whether use mkldnn with CPU.");
DEFINE_bool(use_tensorrt, false, "Whether use tensorrt.");
DEFINE_string(precision, "fp32", "Precision be one of fp32/fp16/int8");
DEFINE_bool(benchmark, false, "Whether use benchmark.");
DEFINE_string(save_log_path, "./log_output/", "Save benchmark log path.");
// detection related
DEFINE_string(image_dir, "", "Dir of input image.");
DEFINE_string(det_model_dir, "", "Path of det inference model.");
DEFINE_int32(max_side_len, 960, "max_side_len of input image.");
DEFINE_double(det_db_thresh, 0.3, "Threshold of det_db_thresh.");
DEFINE_double(det_db_box_thresh, 0.3, "Threshold of det_db_box_thresh.");
DEFINE_double(det_db_unclip_ratio, 2.4, "Threshold of det_db_unclip_ratio.");
DEFINE_bool(use_polygon_score, false, "Whether use polygon score.");
DEFINE_bool(visualize, false, "Whether show the detection results.");
// classification related
DEFINE_bool(use_angle_cls, false, "Whether use use_angle_cls.");
DEFINE_string(cls_model_dir, "", "Path of cls inference model.");
DEFINE_double(cls_thresh, 0.9, "Threshold of cls_thresh.");
// recognition related
DEFINE_string(rec_model_dir, "", "Path of rec inference model.");
DEFINE_int32(rec_batch_num, 1, "rec_batch_num.");
DEFINE_string(char_list_file, "d:/models/ppocr_keys_v1.txt", "Path of dictionary.");

**Comment by dengmingD** [comment]
已经跑通了，速度很快
