### ISSUE TITLE
NO TorchScript Support

### ISSUE THREAD

**Issue by harsh2ai** [PaddlePaddle/PaddleOCR#6862]
The paddle ocr has support for TensorRT and ONNX runtime but there is no support for torchscript runtime , I have faced a lot of troubles and issues in creating a torchscript model and there is no resource or code snippets to do so for paddlepaddle and paddleocr

**Comment by jiangjiajun** [comment]
I am wondering why you need a torchscript model, PaddlePaddle and ONNX model can be deployed in most common scenarios

**Comment by harsh2ai** [comment]
@jiangjiajun 
TLDR : our current systems (organization) are configured on Torschript will need to reconfigure all the thnigs
