### ISSUE TITLE
label for rec

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6866]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/dataset/ocr_datasets.md#2-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB

![image](https://user-images.githubusercontent.com/108393685/178650528-4e9baa6f-8f33-4e21-917e-53d92d2c1a0e.png)
这2种图我该如何标记 文字识别数据格式?

```
123.jpg 123AB 
```

![image](https://user-images.githubusercontent.com/108393685/178650672-ea3b8efc-8507-4a89-aeb9-a9d0c06fa325.png)

**Comment by WenmuZhou** [comment]
这种目前最后切成上下两张图像来做

**Comment by WenmuZhou** [comment]
是的，目前只能单行
