### ISSUE TITLE
你好，请问一下咱们的backbone中rec_svtrnet.py是加了LCNet的吗？

### ISSUE THREAD

**Issue by Henryplay** [PaddlePaddle/PaddleOCR#6869]
如题，在https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/modeling/backbones/rec_svtrnet.py中的模型代码是加了LCNet的吗？

**Comment by WenmuZhou** [comment]
这个里面没有哈，识别里的lcnet是这个 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/modeling/backbones/rec_mv1_enhance.py
