### ISSUE TITLE
在win10通过whl安装paddle后运行报错

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleOCR#687]
当我安装完whl跑后执行以下代码报错：
```
from paddleocr import PaddleOCR, draw_ocr
ocr = PaddleOCR(det_model_dir='inference/ch_det_r50_vd_db', rec_model_dir='inference/ch_rec_r34_vd_crnn_enhance',
                use_gpu=False, use_space_char=True, enable_mkldnn=True)
res = ocr.ocr(img)
```
报错如下：
```
Traceback (most recent call last):
  File "src.py", line 3, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'
```
请问如何解决呢？

**Comment by WenmuZhou** [comment]
去这个路径下 C:\Users\thugbobby\anaconda3\lib\site-packages\paddleocr\ 看看有哪些文件

**Comment by WenmuZhou** [comment]
请问解决了吗

**Comment by TronYY** [comment]
> 当我安装完whl跑后执行以下代码报错：
> 
> ```
> from paddleocr import PaddleOCR, draw_ocr
> ocr = PaddleOCR(det_model_dir='inference/ch_det_r50_vd_db', rec_model_dir='inference/ch_rec_r34_vd_crnn_enhance',
>                 use_gpu=False, use_space_char=True, enable_mkldnn=True)
> res = ocr.ocr(img)
> ```
> 
> 报错如下：
> 
> ```
> Traceback (most recent call last):
>   File "src.py", line 3, in <module>
>     from paddleocr import PaddleOCR, draw_ocr
>   File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
>     from .paddleocr import PaddleOCR
>   File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
>     from tools.infer import predict_system
> ModuleNotFoundError: No module named 'tools.infer'
> ```
> 
> 请问如何解决呢？

解决了吗

**Comment by jimmyflycv** [comment]
any updates??????
