### ISSUE TITLE
相比python， c++ 版 copy_to_cpu操作耗时巨严重

### ISSUE THREAD

**Issue by hzq-zjm** [PaddlePaddle/PaddleOCR#6871]
- 系统环境/System Environment：  ubuntu18.04
- 版本号/Version：Paddle：v2.2.0  PaddleOCR : v2.1.0
同样的模型（dbnet+crnn），同样的前后处理，同样的batch size=64，对于copy_to_cpu操作，c++版 速度平均比python版慢五倍。光copy_to_cpu耗时占了单帧推理时间的50%，这好不正常，请问有没有什么优化策略呢

**Comment by WenmuZhou** [comment]
将paddle和paddleocr都升级到最新版本测试一下呢

**Comment by hzq-zjm** [comment]
> 将paddle和paddleocr都升级到最新版本测试一下呢

都试过了，issue里很多反馈相同问题的，看来不是版本问题
python：
copy_to_cpu 23.4752 ms
ctc_postprocess 21.8551 ms

c++: 
REC batch CopyToCpu 时间：104.097 ms 
REC batch ctc decode 时间：146.58 ms

**Comment by WenmuZhou** [comment]
测试的时候是去掉开头的几次infer 然后多次取平均吗

**Comment by hzq-zjm** [comment]
> 测试的时候是去掉开头的几次infer 然后多次取平均吗

是的

**Comment by Gmgge** [comment]
@hzq-zjm 你好，想请教下你这边测试 cpp平均推理时间是不是慢于python平均推理时间呢？

**Comment by WenmuZhou** [comment]
方便提供一下你的计时代码吗

**Comment by WenmuZhou** [comment]
另外可以看看这里的答案https://github.com/PaddlePaddle/PaddleOCR/issues/5425
