### ISSUE TITLE
OCR识别模型量化训练后的nb模型大小比动态离线量化的nb模型大小稍大，压缩效果不明显

### ISSUE THREAD

**Issue by y-Leaf-e** [PaddlePaddle/PaddleOCR#6876]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.2.2  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：python deploy/slim/quantization/export_model.py -c
- 完整报错/Complete Error Message：无

**Comment by WenmuZhou** [comment]
是指哪个模型呢

**Comment by y-Leaf-e** [comment]
ch_ppocr_mobile_slim_v2.0_rec的训练模型，在中文文档和英文文档数据集进行量化训练之后，opt优化的模型大小为3900K, 没有达到model_lists.md中对应paddle_lite模型的1963K，甚至比直接进行opt动态离线量化为int8还要大一些。
量化步骤按照：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/slim/quantization/README.md
