### ISSUE TITLE
安卓示例中，替换识别模型为日文识别，程序崩溃

### ISSUE THREAD

**Issue by xiejinglan** [PaddlePaddle/PaddleOCR#6879]
![image](https://user-images.githubusercontent.com/14818166/178712310-c63370f6-a6e8-4f25-975c-ae1ec414014c.png)

**Comment by WenmuZhou** [comment]
字典替换了吗

**Comment by xiejinglan** [comment]
字典替换了

**Comment by yangy996** [comment]
看看按这个流程是否有遗漏
https://blog.csdn.net/YY007H/article/details/124774019
