### ISSUE TITLE
CRNN使用的动态LSTM

### ISSUE THREAD

**Issue by ryupaladin** [PaddlePaddle/PaddleOCR#688]
您好，
我目前正在通过看网络结构，学习paddle的函数，我注意到CRNN使用的动态LSTM
paddle.fluid.layers.dynamic_lstm(input, size, h_0=None, c_0=None, param_attr=None, bias_attr=None, use_peepholes=True, is_reverse=False, gate_activation='sigmoid', cell_activation='tanh', candidate_activation='tanh', dtype='float32', name=None)

input ( Variable ) 维度为 [T,4∗hidden_size] 的多维 LoDTensor（必须在传入该OP前对维度为 [T,hidden_size] 的输入经过线性变换得到），其中 T 为 batch 中所有样本的长度之和，hidden_size 为隐层大小，数据类型为 float32 或者 float64。

一个问题是，一个batch里面的样本的时间步长都拼接在一起进的一个lstm么，而且为什么必须限制输入的特征维度为4*hidden_size, 输出的特征维度是hidden_size?paddle在这个函数里面进行了加速处理吗？

感谢！

**Comment by ryupaladin** [comment]
另外，在mobilenet V3里面，用的是small网络，第一层卷积是步长2，接着是残差循环里面有4个步长为(2, 1)的卷积操作，最后经过一个1步长的卷积后是一个2步长的池化，因此在高度维度上应该是变成1/(2^6)=1/64，但是网络输入不是只有（32， 320）吗，

**Comment by littletomatodonkey** [comment]
> 另外，在mobilenet V3里面，用的是small网络，第一层卷积是步长2，接着是残差循环里面有4个步长为(2, 1)的卷积操作，最后经过一个1步长的卷积后是一个2步长的池化，因此在高度维度上应该是变成1/(2^6)=1/64，但是网络输入不是只有（32， 320）吗，

是的，image shape为(32, 320)是为了保证小分辨率可以加速，关于stride的不同设置，我们也在做消融实验，近期就会把实验结论整理并开源出来，敬请期待~

**Comment by littletomatodonkey** [comment]
> 您好，
> 我目前正在通过看网络结构，学习paddle的函数，我注意到CRNN使用的动态LSTM
> paddle.fluid.layers.dynamic_lstm(input, size, h_0=None, c_0=None, param_attr=None, bias_attr=None, use_peepholes=True, is_reverse=False, gate_activation='sigmoid', cell_activation='tanh', candidate_activation='tanh', dtype='float32', name=None)
> 
> input ( Variable ) 维度为 [T,4∗hidden_size] 的多维 LoDTensor（必须在传入该OP前对维度为 [T,hidden_size] 的输入经过线性变换得到），其中 T 为 batch 中所有样本的长度之和，hidden_size 为隐层大小，数据类型为 float32 或者 float64。
> 
> 一个问题是，一个batch里面的样本的时间步长都拼接在一起进的一个lstm么，而且为什么必须限制输入的特征维度为4*hidden_size, 输出的特征维度是hidden_size?paddle在这个函数里面进行了加速处理吗？
> 
> 感谢！

4倍是因为这个API就是这么设计的，在torch 或 tf 里面，乘4的操作封装进了API内部，paddle这里需要用户手动在外面乘4

**Comment by ryupaladin** [comment]
> > 另外，在mobilenet V3里面，用的是small网络，第一层卷积是步长2，接着是残差循环里面有4个步长为(2, 1)的卷积操作，最后经过一个1步长的卷积后是一个2步长的池化，因此在高度维度上应该是变成1/(2^6)=1/64，但是网络输入不是只有（32， 320）吗，
> 
> 是的，image shape为(32, 320)是为了保证小分辨率可以加速，关于stride的不同设置，我们也在做消融实验，近期就会把实验结论整理并开源出来，敬请期待~

谢谢你的回答，可是高度为32的网络输入在最后一步池化之前已经降到1了，此处的pool size不需要设置为（1, 2）吗

**Comment by littletomatodonkey** [comment]
感谢你的反馈，效果其实是一样的， 这块之前统一写了，没注意到这个细节~
