### ISSUE TITLE
slim过后，预训练模型是不是没有用了，感觉裁剪后在重新训练

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleOCR#6882]
CUDA_VISIBLE_DEVICES=1 nohup python -u deploy/slim/prune/sensitivity_anal.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0_IDcard.yml -o Global.pretrained_model=./pretrain/ch_ppocr_server_v2.0_rec_train/best_accuracy Global.save_model_dir=./output/prune_model/ > train0713_shenfenzheng_r34_prune_rec.log >&1 &

python deploy/slim/prune/export_prune_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0_IDcard.yml -o Global.pretrained_model=./output/prune_model/best_accuracy  Global.save_inference_dir=./prune/prune_inference_model

**Comment by littletomatodonkey** [comment]
裁剪之后有些参数无法加载，需要加载裁剪之前的模型，重新学习与训练

**Comment by LeeLear** [comment]
那，能否在裁剪后的模型进行fine-tune，裁剪后的模型还有配置文件可以进行操作吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] slim过后，预训练模型是不是没有用了，感觉裁剪后在重新训练 (Issue #6882)





 
裁剪之后有些参数无法加载，需要加载裁剪之前的模型，重新学习与训练

**Comment by GUOhm230** [comment]
请问大佬，您这个裁剪最终实现效果怎么样呢？
我是按照paddleOCR上提供的步骤，先进行敏感度分析：使用已经训练好的预训练模型进行分析并裁剪训练
然后导出模型
结果无法检测出任何内容，不知道咋回事。

**Comment by wxzyqqj** [comment]
我也遇到这个问题 请问你解决了么
