### ISSUE TITLE
TextConAug

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6883]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/PP-OCRv3_introduction.md

![image](https://user-images.githubusercontent.com/108393685/178901016-9f986404-cc73-4511-80cd-cf8e6c7a02b3.png)

数据增强的code在哪
config找不到相关词

**Comment by littletomatodonkey** [comment]
你好，在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/2909454fb121a002290172525e414f3017923def/ppocr/data/imaug/rec_img_aug.py#L36

**Comment by Alice-Thirty** [comment]
这能上下合并吗 而不是左右
