### ISSUE TITLE
PP-OCRv3 Benchmark

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6886]
Do you have PP-OCRv3 Benchmark?

In the [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/benchmark_en.md
) , what is mobile? what is server?

**Comment by paleomoon** [comment]
Same question, I found #6224, it's said ch_PP-OCRv3_xxx is better than ch_ppocr_server_v2.0_xxx.
