### ISSUE TITLE
关于SRN中GSRM模块

### ISSUE THREAD

**Issue by hao6699** [PaddlePaddle/PaddleOCR#689]
https://github.com/PaddlePaddle/PaddleOCR/blob/5fb3c419c980a112cb69b87019d18157926edc41/ppocr/modeling/heads/rec_srn_all_head.py#L132

你好, 我这里有点疑惑. 按照您函数名称prepare_bi的理解, 应当是准备一个正序的序列和一个逆序的序列, 但是[:, :-1, :]只是舍弃掉了最后一位, 并没有翻转序列. 这么做的原因是什么呢?

**Comment by tink2123** [comment]
这里代码的实现方式可能和常规理解不同，gsrm需要感知除本身字符外的所有位置信息，这里是对当前字符的左边信息和右边信息分开来感知的，最后再合一块。bi代表左右两边：
https://github.com/PaddlePaddle/PaddleOCR/blob/5fb3c419c980a112cb69b87019d18157926edc41/ppocr/modeling/heads/rec_srn_all_head.py#L176

**Comment by hao6699** [comment]
gsrm_word_pos不是已经提供位置编码了么? 有没有实验过只使用word1的情形呢

**Comment by tink2123** [comment]
这里是个类似mask language model的操作，当时在实现的时候没有找到一个比较好的实现方法，只能分成两半去实现。没有实验过只用word1的情形。

**Comment by hao6699** [comment]
是否可以理解为PVAM和GRSM模块都只是使用了transformer的encoder模块, 并没有使用到decoder模块
