### ISSUE TITLE
请问paddleocr代码中BDA数据增广在哪个文件夹,谢谢

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#6891]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，是这个

https://github.com/PaddlePaddle/PaddleOCR/blob/7193a4c1249b39edc4e16a3c020fa17465b6e1f3/ppocr/data/imaug/rec_img_aug.py#L24
