### ISSUE TITLE
如何多进程调用TextSystem函数

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6893]
如何在不使用pdserving，设置高并发呢
我用了multiprocessing去调用textsystem函数会出现以下错误
![image](https://user-images.githubusercontent.com/37231239/178960395-9362a457-4c09-46e9-b9b9-0b3e06c74d5c.png)
`TypeError: cannot pickle 'paddle.fluid.core_avx.PaddleInferPredictor' object`

**Comment by littletomatodonkey** [comment]
你好，可以设置total_process_num参数，表示启动的进程数


https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/inference_args.md

**Comment by GivanTsai** [comment]
> 你好，可以设置t

@littletomatodonkey, 我用的是GPU来推理，那应该怎么设置呢，而且这个必须是python xxx.py脚本形式运行才生效吧
![image](https://user-images.githubusercontent.com/37231239/179493013-40eb6a06-6812-4537-bbdd-5e49a577cc2d.png)

**Comment by Lifer233** [comment]
> > 你好，可以设置t
> 
> @littletomatodonkey, 我用的是GPU来推理，那应该怎么设置呢，而且这个必须是python xxx.py脚本形式运行才生效吧 ![image](https://user-images.githubusercontent.com/37231239/179493013-40eb6a06-6812-4537-bbdd-5e49a577cc2d.png)

解决了么
