### ISSUE TITLE
中文模型

### ISSUE THREAD

**Issue by yyr6661** [PaddlePaddle/PaddleOCR#69]
感谢大佬分享，太强了
请问现在提供的中文模型只有inference.md中的两种吗？

**Comment by LDOUBLEV** [comment]
感谢关注，目前中文模型就inference.md中提到的了

**Comment by yyr6661** [comment]
inference.md中是db+crnn，其它算法想要得到中文模型只能自己训练了是吗？

**Comment by LDOUBLEV** [comment]
对，暂时只能自己训练了，后续我们也会推出其他中文模型，可以保持关注

**Comment by yyr6661** [comment]
非常感谢！

**Comment by DuckJ** [comment]
@LDOUBLEV 在体验你们的在线OCR服务时，识别过程中，中英混杂的时候，两个连续的英文单词在一起会导致空格识别不出来，请问这个问题有什么好的思路解决吗。
如果是标记空格的话，数据集中存在的数据已经没有标记空格了，再去标也不现实
