### ISSUE TITLE
paddle inference ocr 利用率的提升

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleOCR#690]

**Comment by Unknown-parameters** [comment]
![image](https://user-images.githubusercontent.com/47356938/92454521-2cd93200-f1f3-11ea-93d8-1ac32f03e804.png)
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 446.14       Driver Version: 446.14       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208... WDDM  | 00000000:01:00.0 Off |                  N/A |
| 34%   38C    P2    79W / 257W |   5085MiB / 11264MiB |     17%      Default |
+-------------------------------+----------------------+----------------------+

1.怎样提升GPU利用率，来加快推理的速度？
2.大图小图，我的gpu现存占用都是5085mib,请问您怎末看？

**Comment by littletomatodonkey** [comment]
python inference的时候，可以增大推理的batch size以及识别的batch size。

**Comment by Unknown-parameters** [comment]
> python inference的时候，可以扩大推理的批量大小和识别的批量大小。

是C++ inference ,

**Comment by Unknown-parameters** [comment]
c++ inference  增加batch size ；确实提升了GPU的利用率

**Comment by yjmm10** [comment]
> c++ inference 增加batch size ；确实提升了GPU的利用率

请教一下，如何修改c++ inference的batch_size，我没找到对应的变量

**Comment by Unknown-parameters** [comment]
> > c++ inference 增加batch size ；确实提升了GPU的利用率
> 
> 请教一下，如何修改c++ inference的batch_size，我没找到对应的变量

在paddle inference c++ api [官方文档](https://paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html)中介绍
