### ISSUE TITLE
end2end model

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6900]
文本检测+文本识别pipeline串联预测
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/tools/end2end/readme.md

目前有文本检测+文本识别 合成一个模型去实现的吗?
用这一个模型就可以实现 文本检测+文本识别   2功能的效果

**Comment by littletomatodonkey** [comment]
你好，pgnet可以实现检测+识别端到端，但是效果一般，所以我们主要的方案还是检测，识别分开串联
