### ISSUE TITLE
SAR推理模型识别宽度小的图片效果差

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#6905]
https://github.com/PaddlePaddle/PaddleOCR/blob/7193a4c1249b39edc4e16a3c020fa17465b6e1f3/tools/infer/predict_rec.py#L348-L373
推理模型预测时，inputs[0]为padresize后的图片norm_img_batch，inputs[1]存储的是原图占padresize后图片宽度的比例。
经察看，362行中获取的len(input_names)=1，则循环中只对inputs[0]进行了copy_from_cpu，而舍弃了inputs[1]的信息，也就是没有记录原图的比例，接着就用predictor.run()进行预测了。
实际预测中，对于宽度较大的图片影响不大，而预测宽度较小的图片时，训练模型能够很好地进行预测，转换成推理模型进行预测后，却无法正确识别，应该是将图片padding部分也进行了计算，并保留在结果中。
我检查过训练模型预测的代码，是有将原图比例的参数传入的，这是和推理模型的预测代码不同的地方。
请问可以怎么修改呢？谢谢解答。

**Comment by littletomatodonkey** [comment]
可以提供下具体的case，我们这边测试短文本和长文本效果差不多

**Comment by lzzzzj** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/a3fef33bd4ef1a93817e7d09f480be55453cc400/tools/export_model.py#L52-L57
我看到导出模型的代码中，这里设定了模型的输入，只有一个输入
按我的理解，SAR模型输入应该有图片和valid_ratios两个，不知道是否正确

**Comment by lzzzzj** [comment]
@littletomatodonkey 请问是我运行指令哪里有问题还是代码的问题啊大佬
这是我导出模型的指令：
!python3 tools/export_model.py -c output/sar_rec_crane/config.yml -o Global.pretrained_model=./output/sar_rec_crane/best_accuracy Global.save_inference_dir=./inference/sar_rec_crane/
还要加什么参数吗

**Comment by andyjpaddle** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/a3fef33bd4ef1a93817e7d09f480be55453cc400/tools/export_model.py#L52-L57
> 
> 
> 我看到导出模型的代码中，这里设定了模型的输入，只有一个输入
> 按我的理解，SAR模型输入应该有图片和valid_ratios两个，不知道是否正确

最新版代码已经修复，可以更新一下代码试试
