### ISSUE TITLE
applications

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6907]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/applications/%E8%BD%BB%E9%87%8F%E7%BA%A7%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB.md#%E4%B8%80%E7%A7%8D%E5%9F%BA%E4%BA%8Epaddleocr%E7%9A%84%E8%BD%BB%E9%87%8F%E7%BA%A7%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

这种上下有文字的车牌如何标记处理 and training
![image](https://user-images.githubusercontent.com/108393685/179130779-c7d5c084-e87a-428a-95f6-b62f516b3b06.png)
![image](https://user-images.githubusercontent.com/108393685/179131246-22dfa861-34f9-4df0-aa86-1be7322f7d3c.png)

**Comment by MissPenguin** [comment]
这种情况分成2行进行标注，即一张图中有上下两个框。训练流程没什么要调整的。
