### ISSUE TITLE
Traceback (most recent call last):   File "D:/PaddleVideo-develop/applications/FootballAction/predict/predict.py", line 18, in <module>     model_predict.load_model()   File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 45, in timer     retval = func(*args)   File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 81, in load_model     self.image_model = image_model.InferModel(self.configs)   File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\models\pptsm_infer.py", line 36, in __init__     input_names = self.predictor.get_input_names() AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'get_input_names'  Process finished with exit code 1

### ISSUE THREAD

**Issue by Yanchao-L** [PaddlePaddle/PaddleOCR#6908]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 4x NVIDIA GeForce RTX 3090   CUDA 11.0
- Paddle:paddlepaddle-gpu2.3.0
- 运行指令/Command Code：cd applications.FootballAction.predict &&python predict
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "D:/PaddleVideo-develop/applications/FootballAction/predict/predict.py", line 18, in <module>
    model_predict.load_model()
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 45, in timer
    retval = func(*args)
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 81, in load_model
    self.image_model = image_model.InferModel(self.configs)
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\models\pptsm_infer.py", line 36, in __init__
    input_names = self.predictor.get_input_names()
AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'get_input_names'

**Comment by MissPenguin** [comment]
PaddleVideo相关问题可以去他们官网提问哈，可以得到更专业的解答：https://github.com/PaddlePaddle/PaddleVideo
