### ISSUE TITLE
请问怎么看特定某个字符的评估结果呢？

### ISSUE THREAD

**Issue by vousemevoyez1024** [PaddlePaddle/PaddleOCR#6909]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
直接和groundtruth对比，算准确率，不过如果出现多字或漏字时可能会出现偏移无法对齐，但应该能反映出大体情况了。
