### ISSUE TITLE
关于图片大小的设置

### ISSUE THREAD

**Issue by GivanTsai** [PaddlePaddle/PaddleOCR#6910]
我想要训练SVTR的文本识别模型，我训练图片中文本有长有短，长的可能达到900左右，我看配置文件里默认的resize大小是【3, 64, 256】, 我需要把这个改大吗？
![image](https://user-images.githubusercontent.com/37231239/179177994-0c21ce47-b5ea-4b12-80fb-7bdac6b63b95.png)
还有为什么transfrom和backbone这里的大小设置是怎么变化的
![image](https://user-images.githubusercontent.com/37231239/179178529-e2722e7f-07e2-415b-81fe-a2208da07d78.png)

**Comment by Topdu** [comment]
建议统计宽高比，[3, 64, 256]的高宽比适应高宽比为多数为4:1的数据集；
tps_inputsize:是输入到tps网络的size，建议随着[3, 64, 256]的改变而改变；
img_size是输入到SVTRNet中的size，同样需要随着[3, 64, 256]的改变而改变。

**Comment by thsno02** [comment]
@Topdu 你好，请问 tps_inputsize 应该怎么改变呢？如果我设定 img_size 为 [32, 360]，然后将 Train 和 Eval 里的 resize 改为 [3, 32, 360]，接着将 tps_outputsize 改为 [32, 360], tps_inputsize 大致应该按什么比例更改呢？

**Comment by Topdu** [comment]
所有的size对应缩放即可，注意Train， Eval中的image_shape是和svtr的img_size无关，同样进行同步缩放即可

**Comment by phb-shiyige-fw** [comment]
tp

**Comment by vance-coder** [comment]
> 建议统计宽高比，[3, 64, 256]适应**宽高**比多数为4:1的数据集； tps_inputsize:是输入到tps网络的size，建议随着[3, 64, 256]的改变而改变； img_size是输入到SVTRNet中的size，同样需要随着[3, 64, 256]的改变而改变。

对应缩放这块我不是很理解，因为怎么改tps inputsize训练都会报错，我的image shape是[3, 32, 400], out_char_num 是 50，改如何定义tps_inputsize 和 img_size呢

**Comment by vance-coder** [comment]
> > 建议统计宽高比，[3, 64, 256]适应**宽高**比多数为4:1的数据集； tps_inputsize:是输入到tps网络的size，建议随着[3, 64, 256]的改变而改变； img_size是输入到SVTRNet中的size，同样需要随着[3, 64, 256]的改变而改变。
> 
> 对应缩放这块我不是很理解，因为怎么改tps inputsize训练都会报错，我的image shape是[3, 32, 400], out_char_num 是 50，改如何定义tps_inputsize 和 img_size呢

@Topdu  @GivanTsai
