### ISSUE TITLE
最小硬件是多少  我在i3的电脑上跑  崩了

### ISSUE THREAD

**Issue by pww1971** [PaddlePaddle/PaddleOCR#6913]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
崩了是报什么错误还是直接卡死了，
在手机上都能跑，只是速度快慢的问题
