### ISSUE TITLE
pip包incompatible

### ISSUE THREAD

**Issue by frankxyy** [PaddlePaddle/PaddleOCR#6915]
![image](https://user-images.githubusercontent.com/6971044/179359391-1ad202f2-5eb6-4464-a41b-d998b50b6791.png)
pip3 install -r requirements.txt出现这个，有影响吗？

**Comment by LDOUBLEV** [comment]
问题不大

**Comment by frankxyy** [comment]
> 问题不大

了解了 谢谢~
