### ISSUE TITLE
SVTR源码问题

### ISSUE THREAD

**Issue by willpat1213** [PaddlePaddle/PaddleOCR#6916]
SVTR的源码中使用的是`STN_ON`作为矫正模块，请问这里面的`stn.py`与`tps.py`有什么区别呢？

**Comment by tink2123** [comment]
STN是基于TPS实现的～

**Comment by willpat1213** [comment]
谢谢你的回答。意思就是他们是一个整体（即，同一个算法）而不是并列（即，不同的算法）的关系吗？
