### ISSUE TITLE
pp ocr serving，python语言server端成功启动，client端启动发送请求收不到响应

### ISSUE THREAD

**Issue by frankxyy** [PaddlePaddle/PaddleOCR#6918]
![企业微信截图_dbdc7a64-dbca-426e-ae73-6fdf176b7220](https://user-images.githubusercontent.com/6971044/179439840-8b211755-a2bd-482a-b050-a67d310d9a2b.png)

log卡在上面这样。

注: 运行环境为  paddlepaddle/paddle:2.3.1-gpu-cuda11.2-cudnn8 镜像的容器，网络模式是host。

**Comment by frankxyy** [comment]
昨天晚上一直卡住，今天重跑后正常

**Comment by tink2123** [comment]
可能是代理的问题，导致没有访问到服务
