### ISSUE TITLE
vs2019打开paddleocr  CMakelists.txt报错

### ISSUE THREAD

**Issue by exmee** [PaddlePaddle/PaddleOCR#692]
在win7下使用vs2019打开paddleocr  CMakelists.txt报错，错误提示CMake Error at D:\Users\exme\workspace\ocr\PaddleOCR-develop\PaddleOCR-develop\deploy\cpp_infer\CMakeLists.txt:1:  Parse error.  Expected a command name, got unquoted argument with text  "b".			
并且在CMake设置中的变量和缓存没有加载出CMakeLists.txt中的变量名称。

**Comment by littletomatodonkey** [comment]
你是不是改动了CMakelists.txt的文件，这个需要和官网上的保持一致 
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/cpp_infer/CMakeLists.txt

**Comment by exmee** [comment]
没有呢，我重新在github上下载了工程，还是一样的结果

**Comment by littletomatodonkey** [comment]
可以再检查下文件格式是否需要转换
