### ISSUE TITLE
使用crnn识别模型训练一段时间过拟合

### ISSUE THREAD

**Issue by QQQTAO** [PaddlePaddle/PaddleOCR#6920]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：2.12
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：1.1
- 运行指令/Command Code：
- 完整报错/Complete Error Message：使用官网提供的预训练模型进行识别训练，训练集包括60万张真实数据和250万张生成数据，使用真实数据和生成数据1:1动态采样进行训练，训练集准确度92%左右，测试集准确度为79左右，训练60多个epoch loss就不下降开始增加，训练过拟合了，请问这种情况除了官网说明的增加l2_decay值，还有其他解决方案吗。

**Comment by tink2123** [comment]
可以尝试添加数据增强，使用cosine decay学习率衰减策略。
另外建议分析下badcase，有针对性的添加同场景的训练数据。

**Comment by xiong-yuxian** [comment]
你好，我想请问一下怎么获取badcase，怎么知道测试集哪些图片在测试时结果较差？我测试的时候只得到了准确率和norm_edit_distance

**Comment by QQQTAO** [comment]
你可以编写一个脚本把你测试集图片的识别结果、识别阈值和真实的样本标签对应一下，就可以判断你的测试集识别性能，然后把你的badcase统计一下就好了，我训练时的过拟合是因为训练集准确度很高，测试集准确度比较高。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 使用crnn识别模型训练一段时间过拟合 (Issue #6920)





 
你好，我想请问一下怎么获取badcase，怎么知道测试集哪些图片在测试时结果较差？我测试的时候只得到了准确率和norm_edit_distance

**Comment by xiong-yuxian** [comment]
你好，你的来信我已收到，有问题的话会回信联系你的，请在最近几天关注邮箱动态。
