### ISSUE TITLE
coco_detection.yml 配置问题

### ISSUE THREAD

**Issue by caojunyongnb** [PaddlePaddle/PaddleOCR#6926]
您好，请问为什么coco_detection设置TestDataset的时候不需要指定图片路径只指定一个anno_path就行了呀，这个不应该是图片和标注信息都有的么，谢谢。
TestDataset:
   !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

**Comment by WenmuZhou** [comment]
这个建议问一下PaddleDetection那边
