### ISSUE TITLE
关于layoutlm 做kie抽取的box位置的问题

### ISSUE THREAD

**Issue by zirui** [PaddlePaddle/PaddleOCR#6927]
layoutxlm(layoutlmv2)原论文中输入位置信息是字符(word)级的bounding box位置，而我看到paddleocr 的实现是直接用的是ocr输出的句子(片段)的bounding box位置信息， 会导致key-value整个作为key(question)被识别出来,  请问这样做合理么？
我目前在文档中没有找到paddleocr 如何获取字符box位置信息的说明，也看到issue中有不少人提过类似的问题，一直没有看到有解决

**Comment by WenmuZhou** [comment]
论文的官方实现里也是用的word级别的box，字符级别box获取起来难度太大，一般都是word级别

**Comment by zirui** [comment]
> 论文的官方实现里也是用的word级别的box，字符级别box获取起来难度太大，一般都是word级别

我这里表述不太清楚,  `word` 在中英文里含义不一样, `token`可能更合适(中文一般就是字符)。
 官方给出的示例里实际上是将中文拆成了字符粒度的, 这样后续可以按字符粒度做序列标注，以实现实体识别. 
paddleocr 输出的的box粒度太粗了，很多情况是句子级别的, 这样不利于下游做字符/word粒度的实体抽取

**Comment by WenmuZhou** [comment]
字符级别的数据很难获取，导致字符级别的检测算法很少，所以你说的这个目前很难做到

**Comment by littletomatodonkey** [comment]
你好，之前测试过使用token级别的bbox作为layoutxlm的输入，效果与使用sentence级别的word基本一致，就没有开源了

```python
    def split_bbox(self, bbox, text, tokenizer):
        words = text.split()
        token_bboxes = []
        curr_word_idx = 0
        x1, y1, x2, y2 = bbox
        unit_w = (x2 - x1) / len(text)
        for idx, word in enumerate(words):
            curr_w = len(word) * unit_w
            word_bbox = [x1, y1, x1 + curr_w, y2]
            token_bboxes.extend([word_bbox] * len(tokenizer.tokenize(word)))
            x1 += (len(word) + 1) * unit_w
        return token_bboxes
```

**Comment by zirui** [comment]
> 你好，之前测试过使用token级别的bbox作为layoutxlm的输入，效果与使用sentence级别的word基本一致，就没有开源了
> 
> ```python
>     def split_bbox(self, bbox, text, tokenizer):
>         words = text.split()
>         token_bboxes = []
>         curr_word_idx = 0
>         x1, y1, x2, y2 = bbox
>         unit_w = (x2 - x1) / len(text)
>         for idx, word in enumerate(words):
>             curr_w = len(word) * unit_w
>             word_bbox = [x1, y1, x1 + curr_w, y2]
>             token_bboxes.extend([word_bbox] * len(tokenizer.tokenize(word)))
>             x1 += (len(word) + 1) * unit_w
>         return token_bboxes
> ```

我目前也是使用类似的简单策略做box的拆分， 但是感觉不是很好的解决方案， 因为paddleocr 会忽略中文间的空格,
另外当有不同宽度的字符的时候， 会导致split box位置不准确
