### ISSUE TITLE
文字检测模型文档链接报错

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#6928]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/detection.md
2.4 节 自动混合训练文档链接错误，直接跳转至文档主页，请尽快修复。

**Comment by WenmuZhou** [comment]
我这边edge浏览器跳转正常，请问你是用的什么浏览器

**Comment by xu-peng-7** [comment]
chrome浏览器




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 文字检测模型文档链接报错 (Issue #6928)





 
我这边edge浏览器跳转正常，请问你是用的什么浏览器
