### ISSUE TITLE
文本检测漏检问题

### ISSUE THREAD

**Issue by Sweetwenty** [PaddlePaddle/PaddleOCR#6930]
在识别英文字符和单词时，一张图片大概20个字符，字符之间有足够间距。大部分都可以被检测到，有些单个的字母没有被检测到，想请教下这种问题出现的原因是什么？
![DB3](https://user-images.githubusercontent.com/87378415/179660510-2f1520ff-4a6b-486a-ba96-ef8615a8488d.JPG)
![DB2](https://user-images.githubusercontent.com/87378415/179660519-c8c09ae9-aa89-41ed-9498-f7fc31a32fae.JPG)
![DB4](https://user-images.githubusercontent.com/87378415/179660530-f969f416-efca-4c8d-ad57-accff1a4ce49.JPG)

**Comment by WenmuZhou** [comment]
如果数据集都是这种图像的话，可以直接做切分成字符的，不需要进行检测，case我们这边也会测试一下
