### ISSUE TITLE
multi language train

### ISSUE THREAD

**Issue by xireli** [PaddlePaddle/PaddleOCR#6932]
使用test render 生成一批阿拉伯语数据，每张图片有一到三个单词（样本个数 一个单词 > 两个单词 > 三个单词），每个单词之间有空格，config 文件中文本长度设置了60个字符。
问：1.PPOCR-V3 训练模型转inference模型后准确率明显下降
       2.长文本识别时出现少识别中间的单词，比如：AB BC CD DE四个单词识别不到中间的单词
请问有什么办法解决以上问题？

**Comment by tink2123** [comment]
1. 准确率下降可以check下image shape与训练配置是否一致
2. 长文本用现有数据处理策略效果可能不好，由于阿拉伯文从右向左书写，建议先对标签做反转训练，预测结果后再进行反转输出。

**Comment by tangjinhan** [comment]
这个问题解决了吗，我这边也碰到一样的问题了，想请教一下你们是怎么解决的？
