### ISSUE TITLE
预测的逻辑处理问题

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#6937]
![00006737](https://user-images.githubusercontent.com/6490927/179724212-37212153-7316-46c0-a94e-5a837788ea9c.jpg)

比如

航班 这两个字

漏字：
脏污了  看不到  航班
印刷问题   空白

错别字
航班 变成 韩版

航班 这个区域坐标  
一定要写着 航班

逻辑上要怎么写  比较合理

**Comment by WenmuZhou** [comment]
抱歉，没太理解你的意思

航班不是检测到了么，没漏

在可视化结果上也没见到韩版

**Comment by monkeycc** [comment]
比如 

登机牌

漏字：
登  牌
登机 

错别字：
点击牌

整个字都是错误的  变成：
paddle

登机牌 变成了 paddle

@WenmuZhou
