### ISSUE TITLE
旋转90度的横向文字的识别问题

### ISSUE THREAD

**Issue by haha1341999522** [PaddlePaddle/PaddleOCR#6939]
作者你好,最近遇到了这样的文字识别场景:
在一个耳标上,**同时存在横向和竖向两串文字**
![image](https://user-images.githubusercontent.com/38492980/179752181-a3abfc56-70bb-4c6e-b8a1-c56fff5eb7fd.png)
我把图像进行了打标(一张图片上有两个标注),然后送进网络
训练后发现其对于**横向的文字可以识别但是竖向的文字识别并不理想**
(无论是改换了预训练模型还是把识别网络从db换成east,都不太理想,如下图)
![image](https://user-images.githubusercontent.com/38492980/179753075-aefd145e-bb16-4020-9962-6909aa3835cf.png)
我想知道可能的原因是什么呢
PaddleOCR对这样图像的处理上会存在困难吗
还是说应该用别的算法而不用OCR识别呢0.0

**Comment by WenmuZhou** [comment]
是每张图像上都有竖直和横向文本存在吗，可以看一下网络预测图上有没有对应的响应，可以画一下这里https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/postprocess/db_postprocess.py#L63的pred 如果有响应的话，就调低后处理中的thresh

**Comment by haha1341999522** [comment]
> 是每张图像上都有竖直和横向文本存在吗，可以看一下网络预测图上有没有对应的响应，可以画一下这里[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/postprocess/db_postprocess.py#L63的pred](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/ppocr/postprocess/db_postprocess.py#L63%E7%9A%84pred) 如果有响应的话，就调低后处理中的thresh

想问下这种情况需要使用方向分类器吗

**Comment by WenmuZhou** [comment]
需要

**Comment by yangy996** [comment]
这用通用模型识别效果就很好，为嘛还要继续训练
