### ISSUE TITLE
Ubuntu下多线程很慢

### ISSUE THREAD

**Issue by zhangshuai0220** [PaddlePaddle/PaddleOCR#694]
开启多线程后模拟并发请求 并发数没有超过线程数 但是响应时间从原来的一个请求的5秒 变成了每个都是14秒了 这个正常吗
单个求请
![image](https://user-images.githubusercontent.com/29618382/92546700-bb968f00-f285-11ea-9708-a8b78eb71b0e.png)

模拟多并发求请的
![image](https://user-images.githubusercontent.com/29618382/92546642-9b66d000-f285-11ea-86ed-e1dd507fbc47.png)

请问怎么配置能加速呢
服务是通过hub serving start -m chinese_ocr_db_crnn_mobile -p 8866
hub serving start -m ocr_system --use_multiprocess --wokers 8启动的 用的cpu的方式

**Comment by LDOUBLEV** [comment]
在config.json中配置多进程试试，参考文档： https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/serving.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%90%AF%E5%8A%A8
![image](https://user-images.githubusercontent.com/26592129/92551556-df130700-f290-11ea-8c79-c4ea09d70484.png)

**Comment by zhangshuai0220** [comment]
> 在config.json中配置多进程试试，参考文档： https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/serving.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%90%AF%E5%8A%A8
> ![image](https://user-images.githubusercontent.com/26592129/92551556-df130700-f290-11ea-8c79-c4ea09d70484.png)

试了好像要快一点  但是感觉还是有点慢 请问使用cpu影响速度的瓶颈主要在哪里 cpu核数？cpu主频？ 内存？  如果想满足30左右的并发  推荐配置是什么样的呢

**Comment by LDOUBLEV** [comment]
确认了下，现在hub中还没有加mkdnn加速，Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz 上开启MKLdnn加速大概是400ms一张图（检测+识别+预处理后处理），加速30%以上；这个功能后续会完善上

**Comment by zhangshuai0220** [comment]
> 确认了下，现在hub中还没有加mkdnn加速，Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz 上开启MKLdnn加速大概是400ms一张图（检测+识别+预处理后处理），加速30%以上；这个功能后续会完善上

![image](https://user-images.githubusercontent.com/29618382/92691777-b153be00-f375-11ea-9f8e-d77053bd2f4c.png)
我把这里改成True有用吗

**Comment by LDOUBLEV** [comment]
Hub中目前已经支持mkldnn了，可以通过参数设置是否启用
