### ISSUE TITLE
Unable to open PPOCRLabel/libs/resources.py for writing

### ISSUE THREAD

**Issue by chenRV** [PaddlePaddle/PaddleOCR#6940]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
Unable to open PPOCRLabel/libs/resources.py for writing
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2705, in <module>
    assert output == 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
AssertionError: operate the cmd have some problems ,please check  whether there is a in the lib directory resources.py

**Comment by smalllyingspinach** [comment]
解决了吗？我也遇到了相同的问题
