### ISSUE TITLE
用TensorRT加速OCR的rec模型推理时报错

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/PaddleOCR#6945]
我参照paddleOCR的deploy下的cpp_infer推理代码，在使用TensorRT来加速ch_PP-OCRv3_rec模型时出现了一个错误

错误信息如下：
InvalidArgumentError: TRT runtime input shape of x is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime input shape = [6, 3, 48, 320], min input shape = [1, 3, 48, 10], max input shape = [1, 3, 48, 2000]。

请问这个错误该如何修改？

**Comment by littletomatodonkey** [comment]
you need to modify the eval data size and train data size at the same time.

**Comment by Shrinco** [comment]
> 你好，导出的时候麻烦指定rec_batch_num为你实际预测时候的batch num

您好，这个问题已经解决了，谢谢。

**Comment by pbabading** [comment]
> > 你好，导出的时候麻烦指定rec_batch_num为你实际预测时候的batch num
> 
> 您好，这个问题已经解决了，谢谢。

能问下怎么解决的吗

**Comment by pbabading** [comment]
> > 能问下怎么解决的吗
> 
> PaddleOCR的库里有一行代码是指定batch_num大小的，让他为1就好了。

改完后你tensorrt 加速就可以了吗

**Comment by Shrinco** [comment]
> 改完后你tensorrt 加速就可以了吗
改完之后trt能正常加速了

**Comment by pbabading** [comment]
> 



> > 能问下怎么解决的吗
> 
> PaddleOCR的库里有一行代码是指定batch_num大小的，让他为1就好了。

大佬能问一下 你说的库里有一行代码指定batch_num大小的 是哪个文件夹 cpp_infer吗

**Comment by pbabading** [comment]
> > 
> 
> > > 能问下怎么解决的吗
> > 
> > 
> > PaddleOCR的库里有一行代码是指定batch_num大小的，让他为1就好了。
> 
> 大佬能问一下 你说的库里有一行代码指定batch_num大小的 是哪个文件夹 cpp_infer吗

大佬还有印象嘛

**Comment by Shrinco** [comment]
> 大佬还有印象嘛
在那个cpp_infer下的ocr_rec.cpp里，修改这个为1就好了应该
![image](https://user-images.githubusercontent.com/50402380/183548450-0be2ebc6-b3b2-441d-9366-f7f99ccdb4e8.png)

**Comment by pbabading** [comment]
好的 不好意思现在才看见&nbsp;谢谢


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: shrinco ***@***.***&gt;
发送时间: 2022年8月9日 10:13
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: pbabading ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleOCR] 用TensorRT加速OCR的rec模型推理时报错 (Issue #6945)





  
大佬还有印象嘛
 在那个cpp_infer下的ocr_rec.cpp里，修改这个为1就好了应该
