### ISSUE TITLE
如何逆向生成pdparms

### ISSUE THREAD

**Issue by caojunyongnb** [PaddlePaddle/PaddleOCR#6946]
您好，
pdparms生成预测模型的时候会生成inference.pdiparams, inference.pdiparams.info,inference.pdmodel这三个文件，请问有办法获取这三个模型文件以后逆向生成pdparms文件么
谢谢

**Comment by littletomatodonkey** [comment]
inference model是静态图的，可以加载，生成动态图的program试下，不过这个之前也没有试过

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/load_inference_model_cn.html#load-inference-model
