### ISSUE TITLE
PP-OCRv3 部署 python配置参数是多少

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleOCR#6948]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
代码默认的参数就是PP-OCRv3的超参
