### ISSUE TITLE
Permanent fix for import: No module named 'tools.infer' 

### ISSUE THREAD

**Issue by kelvinAI** [PaddlePaddle/PaddleOCR#6949]
I've tried installing and importing paddleocr on two different systems, one works and one encountered namespace clashing issue with other installed libraries. I've tried some suggestions from [No module named 'tools.infer' ](https://github.com/PaddlePaddle/PaddleOCR/issues/1024#issuecomment-1105946934) , [ModuleNotFoundError](https://github.com/PaddlePaddle/PaddleOCR/issues/4744) but it doesn't solve my issue. So i've went ahead and worked on a fork to try to fix it permanently [in this branch.](https://github.com/kelvinAI/PaddleOCR/tree/remove_ppocrlabel)  

This change attempts to permanently fix all current importing issues and prevent any future issues with regards to import by restructuring the project.  
Please read the top of README.md on installation and changes.

Kindly do take a look at my suggested way to fix the project permanently (by moving all .py files to /src). I think the imports should work better if every package / module can be properly accessed by paddleocr.xxx.xxx and no longer need dangerous hacks such as sys.append('..') 

However I noticed that the names of the previous authors were removed from the past commits in the moved .py files, and I agree that it should be fixed properly if you want to include this in the original repository so perhaps I can do it again while trying to maintain the commit histories while moving source files. Do let me know if you'd like this format and I can make another pull request with the all past commit histories intact.

Also I think the whole PPOCRLabel package/project/folder should be separated from PaddleOCR as it has it's own setup.py so it should be in a separate repository?

@D-DanielYang @littletomatodonkey @tink2123 @WenmuZhou 
我可以用中文沟通，只是比较习惯用英文。可以用中文回复我。
谢谢！

**Comment by littletomatodonkey** [comment]
你好，可以将`sys.append('..')`修改为`sys.insert(0, '..')`，确保ppocr的环境变量在每次运行自己的时候优先级最高

**Comment by kelvinAI** [comment]
@littletomatodonkey 写 python 包装时,用 sys.insert 还是 sys.append 都不是正确方试吧，会导致很多import 问题。[这个](https://github.com/PaddlePaddle/PaddleOCR/issues/6872) 也是包装问题导致的。
你看一看[这个代码](https://github.com/kelvinAI/PaddleOCR/tree/remove_ppocrlabel)。注意一下这几个file 就能了解我想表达的意识： 
- [`setup.py`](https://github.com/kelvinAI/PaddleOCR/blob/remove_ppocrlabel/setup.py)
- src/paddleocr/[`main.py`](https://github.com/kelvinAI/PaddleOCR/blob/remove_ppocrlabel/src/paddleocr/main.py)
- src/paddleocr/[`__init__.py`](https://github.com/kelvinAI/PaddleOCR/blob/remove_ppocrlabel/src/paddleocr/__init__.py)

我试了 train 和 inference 是没问题，但别的 function 我就没试过，所以你们可以看看一下。
