### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/PaddleOCR#695]
我在自己的命令行模式下，传入了自己的参数，然后在我的程序里面实例PaddleOCR，就会报错main.py: error: unrecognized arguments: --params=aaa，估计是因为parser.parse_args()里面没有处理params这个命令行参数，这个怎么解决，我的py文件执行的时候必须传入我自己需要的业务命令行参数，这样会与PaddleOCR里面的parser.parse_args()有冲突

**Comment by LDOUBLEV** [comment]
你要传入的参数可以写在配置文件里，启动训练和评估的时候需要加载配置文件就可以了

**Comment by zhangmianhongni** [comment]
不是，我是直接使用PaddleOCR的ocr方法进行检测和识别的，不训练和评估，我本身的业务参数传入是动态的，通过命令行参数传入，然后会执行一些业务逻辑，中间部分逻辑会使用PaddleOCR进行文字识别，但一实例PaddleOCR的时候，里面的init方法会直接去解释命令行参数，就会报错，除非PaddleOCR源码里面的parse_args函数最后一行parser.parse_args改为parser.parse_known_args，不然就不行

**Comment by FangmingZhou** [comment]
一样的问题……

**Comment by dullberry** [comment]
you guys can just use sys.argv=sys.argv[:1] to solve the problem, use this after getting the params you want
