### ISSUE TITLE
Is it possible to detect and recognize three different languages?

### ISSUE THREAD

**Issue by bit-scientist** [PaddlePaddle/PaddleOCR#6954]
My case involves detecting and recognizing 3 languages (English, Korean and Traditional Chinese). Since they are of different base, will it work if combine all three image datasets into one giant one and make one dictionary which includes three language characters?
What are the specific cautions to take before starting on this? Thank you.

**Comment by bit-scientist** [comment]
@Evezerest, Hi, I saw you in the related discussions. I hope you can help. Thank you.

**Comment by tink2123** [comment]
It is possible to mix dictionaries of three languages, but the efficiency of training and inference will be relatively low if the dictionary becomes very large.
If possible, you can also try to use a language classification model to distinguish three categories, and then train three recognition models, the accuracy will be higher.
