### ISSUE TITLE
TensorRT 加速 ch_PP-OCRv3 出错

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/PaddleOCR#6959]
在使用 PaddleOCR 的 cpp_infer 开启 TensorRT 加速 ch_PP-OCRv3 模型时出现了下列错误，

- 系统环境/System Environment：win11 cuda11.2 cudnn8.2 TensorRT8.0
- 版本号/Version Paddle：2.3  PaddleOCR：PaddleOCR-release-2.5
- 完整报错/Complete Error Message：
   InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.

**Comment by LDOUBLEV** [comment]
TRT设置动态shape的问题，可以参考FAQ:https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/FAQ.md#q-trt%E9%A2%84%E6%B5%8B%E6%8A%A5%E9%94%99invalidargumenterror-some-trt-inputs-dynamic-shape-info-not-set-check-the-info-log-above-for-more-details

**Comment by Shrinco** [comment]
> TRT设置动态shape的问题，可以参考FAQ:https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/FAQ.md#q-trt%E9%A2%84%E6%B5%8B%E6%8A%A5%E9%94%99invalidargumenterror-some-trt-inputs-dynamic-shape-info-not-set-check-the-info-log-above-for-more-details

请问动态shape的log在哪里看？ 我是在vs中执行的推理代码，在项目文件夹里的log文件中没有关于动态shape的提示

**Comment by LightSun** [comment]
一样的问题。我还改了一点paddle源码。可以打印出来input. 'pool2d_2.tmp_0_clone_0'  ，但是用了Netron 查看。也不知道怎么设置。
