### ISSUE TITLE
TensorRT     是否支持？

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleOCR#696]
config.EnableTensorRtEngine(1 << 30, 10, 3, AnalysisConfig::Precision::kFloat32, false, false);
添上会报错。
通用的文字检测和识别模型，是不是不支持tensorrt 加速？

**Comment by LDOUBLEV** [comment]
是可以支持的，现在检测和识别输入都是变长的，TRT6 以上才支持变长输入

**Comment by Unknown-parameters** [comment]
> 是可以支持的，现在检测和识别输入都是变长的，TRT6 以上才支持变长输入；
> 如果是支持变长输入，建议用：
> cuda10.2
> cudnn8
> trt7.1
> driver 440

好的，我试试

**Comment by Unknown-parameters** [comment]
> 是可以支持的，现在检测和识别输入都是变长的，TRT6 以上才支持变长输入；
> 如果是支持变长输入，建议用：
> cuda10.2
> cudnn8
> trt7.1
> driver 440

paddle-trt 是不是不支持paddleocr 中的backbone?
Note:

从源码编译时，TensorRT预测库目前仅支持使用GPU编译，且需要设置编译选项TENSORRT_ROOT为TensorRT所在的路径。

Windows支持需要TensorRT 版本5.0以上。

Paddle-TRT目前[仅支持固定输入shape。](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#paddle-tensorrt)

下载安装TensorRT后，需要手动在NvInfer.h文件中为class IPluginFactory和class IGpuAllocator分别添加虚析构函数
