### ISSUE TITLE
PGnet eval Out of memory

### ISSUE THREAD

**Issue by JinMana** [PaddlePaddle/PaddleOCR#6960]
显卡资源有11175MiB
训练数据集2000张，测试数据集500张，batchsize设置为4，还是会有溢出问题，每次报错是在eval阶段报错
![图片1](https://user-images.githubusercontent.com/32948294/180156019-bedf725d-a458-487b-bc05-bb6d18b6e974.png)

**Comment by LDOUBLEV** [comment]
eval的时候输入shape默认最小边长是768，如果你不需要设置那么大，可以设置小一些https://github.com/PaddlePaddle/PaddleOCR/blob/4196e5d3d9b18630e5fddf79b23747aac1f0b468/configs/e2e/e2e_r50_vd_pg.yml#L101
