### ISSUE TITLE
用自己训练的模型做表格识别时报错IndexError: list index out of range

### ISSUE THREAD

**Issue by xxentropy** [PaddlePaddle/PaddleOCR#6961]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 版本号/Version：Paddle：2.1  PaddleOCR：2.2/2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
   执行快速开始中的代码，能正常运行，但效果不太好。
  于是自己标注了数据训练并导出表格结构模型，替换快速开始中的原模型，报错。
  执行命令：
python table/predict_table.py --det_model_dir=path/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=path/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=path/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=LED.PNG --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --output ../output/table
 错误提示：
Traceback (most recent call last):
  File "table/predict_table.py", line 221, in <module>
    main(args)
  File "table/predict_table.py", line 197, in main
    pred_html = text_sys(img)
  File "table/predict_table.py", line 92, in __call__
    pred_html, pred = self.rebuild_table(structure_res, dt_boxes, rec_res)
  File "table/predict_table.py", line 97, in rebuild_table
    matched_index = self.match_result(dt_boxes, pred_bboxes)
  File "table/predict_table.py", line 112, in match_result
    if distances.index(sorted_distances[0]) not in matched.keys():
IndexError: list index out of range

请问如何解决？

**Comment by xxentropy** [comment]
后续：换成PaddleOCR 2.5 后，暂时没有报错

**Comment by hzy459176895** [comment]
你好， 请问文档表格数据如何标注呢？

**Comment by xxentropy** [comment]
> 你好， 请问文档表格数据如何标注呢？
我是用这个工具标注的，标注后的json有些可以训练，有些格式报错
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md
