### ISSUE TITLE
请问Paddleocr使用需要版权吗？可以用于自己的项目吗？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#6965]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
开源的，放心使用
