### ISSUE TITLE
PPOCRLabel软件导出识别结果后，图片方向被改变了

### ISSUE THREAD

**Issue by aengui** [PaddlePaddle/PaddleOCR#6966]
2.5版本源码下的PPOCRLabel
![image](https://user-images.githubusercontent.com/19809583/180350782-525380e6-9b09-40b5-92b5-95ac14938939.png)
![image](https://user-images.githubusercontent.com/19809583/180350899-3ed4cba0-cbb6-4413-8348-5fc929f92254.png)

上箭头导出后变左箭头，下箭头变右箭头，我图片中只有上下箭头，导出后有的是正常方向，有的就旋转了。这样训练之后←就被识别成↑了。。。请问怎么才能让它不旋转？

**Comment by Donaghys** [comment]
您好，请问这个问题应该怎么解决呢？

**Comment by Currf** [comment]
我也是这样 醉了
