### ISSUE TITLE
识别模型finetune后的性能

### ISSUE THREAD

**Issue by JinYuannn** [PaddlePaddle/PaddleOCR#6967]
我用70张图片finetune en_number_mobile_slim_v2.0_rec模型，batch_size=70，需要训练800+epoch才收敛，accuracy收敛到0.77，loss收敛到0.33，这正常吗

**Comment by LDOUBLEV** [comment]
batchsize=整个数据集的数量了，相当于只训练了800次迭代，精度0.77，算是正常的

**Comment by JinYuannn** [comment]
好的。
请问对于识别模型的fine-tune，还有哪些常用的优化技巧？
