### ISSUE TITLE
模型蒸馏报错

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleOCR#6968]
ValueError: parameter name [conv1_1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by LDOUBLEV** [comment]
运行指令发下

**Comment by LeeLear** [comment]
CUDA_VISIBLE_DEVICES=1 nohup python -u tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation_IDcard.yml &gt; train0714_shenfenzheng_distill_IDcard_rec.log &gt;&amp;1 &amp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 模型蒸馏报错 (Issue #6968)





 
运行指令发下

**Comment by LDOUBLEV** [comment]
更新代码重新尝试吧
