### ISSUE TITLE
粤语繁体字识别效果较差的问题

### ISSUE THREAD

**Issue by zjc6666** [PaddlePaddle/PaddleOCR#6969]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

你好，在将PaddleOCR运用到粤语的OCR图片识别时，因为粤语包含很多的繁体字，这种情况下使用ch_PP-OCRv3_rec_infer的识别效果较差，请问有什么建议的吗?

**Comment by LDOUBLEV** [comment]
最近更新了繁体字模型，欢迎试用
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/models_list.md#23-%E5%A4%9A%E8%AF%AD%E8%A8%80%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E6%9B%B4%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD

**Comment by zjc6666** [comment]
你好，我试用了chinese_cht_PP-OCRv3_rec这个模型，但是在模型识别的过程中，繁体字效果确实标好了，但是对于简体繁体在同一行的情况下，简体字的识别效果变差了
请问有统一的简体-繁体识别模型公开吗？
