### ISSUE TITLE
SRN 识别器对长文本的效果

### ISSUE THREAD

**Issue by looput** [PaddlePaddle/PaddleOCR#697]
请问下作者有验证过SRN在中文长文本（长度10~60字符）的效果吗？我跑了下，似乎收敛很慢，再输入 （32,512） batch size 96 情况下训练70k step 准确度才35%左右，是不是Transformer对长序列的处理不如RNN？

**Comment by MissPenguin** [comment]
您好，论文里中文数据集做过对比，专门挑了一部分长文本单独测，效果会比attention ctc好很多，具体数据参考SRN论文（https://arxiv.org/abs/2003.12294）中table 6
![image](https://user-images.githubusercontent.com/25809855/92678194-04b71380-f358-11ea-9f26-bb64eeb7f15c.png)

**Comment by MissPenguin** [comment]
TRW-L为文字个数大于10的长文本集合

**Comment by looput** [comment]
好的，谢谢您的回复。 TRW-L 平均长度为15，不过目前我训练的数据长度平均约为35，您对这类数据处理有什么建议吗？另外可以提供下在TRW-L上训练的配置文件吗?
