### ISSUE TITLE
ppocv3使用DB算法无法输出检测框 ，导致后面识别模型不能识别

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#6970]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11家庭版
- 版本号/Version：Paddle：2.3. 0     PaddleOCR：2.5  问题相关组件/Related components：
- 运行指令/Command Code： 
- python tools/infer/predict_system.py --image_dir="./work/ces/" --det_model_dir="./inference/ch_db_mv3/student" --rec_model_dir="./inference/v3_en_mobile/" --rec_char_dict_path="./work/WaterMeters/water_meter_dict.txt" --use_angle_cls=false --vis_font_path=./doc/fonts/simfang.ttf

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/76056473/180376794-697c4d32-c955-446c-8d6e-a09de727dd7b.png)
![image](https://user-images.githubusercontent.com/76056473/180376842-2fd2f373-4809-49d0-bdcc-d90028a52aee.png)
![image](https://user-images.githubusercontent.com/76056473/180376921-97dd88f7-030a-4190-8b19-d325956bad69.png)

**Comment by LDOUBLEV** [comment]
你的测试图像是？

**Comment by chc-stars** [comment]
![3903121621473337165](https://user-images.githubusercontent.com/76056473/180686739-e4801263-30b8-4d2e-b461-978ba5f172b4.jpg)
水表
![image](https://user-images.githubusercontent.com/76056473/180687408-5cac4a9d-5104-4d36-b48c-edfe1f907de6.png)
官方的预训练，自己微调。
但是在infer_det.py可以返回检测框

**Comment by yangy996** [comment]
你训练时候，评估配置是什么样的？

**Comment by LDOUBLEV** [comment]
预测的时候设置drop_score=0.
