### ISSUE TITLE
为什么使用GPU识别图片文字的速度和CPU差不多呀

### ISSUE THREAD

**Issue by LangJiHuangSha** [PaddlePaddle/PaddleOCR#6971]
请问下为什么同样的图片CPU识别文字速度和GPU差不多呀，从执行命令到输出最后一行都是8秒左右，有时GPU还会更慢，请问这是正常情况嘛，还是说识别的时候并没有释放CPU/GPU的全部性能呢
下面时CPU和GPU的信息和识别的日志
CPU信息
![image](https://user-images.githubusercontent.com/100844589/180376751-375c0b7c-b3b8-48a3-9e60-d8616baf15ce.png)
识别效果
![image](https://user-images.githubusercontent.com/100844589/180377065-5717717d-f98c-4596-b603-e1a6cf2b5e47.png)
GPU信息
![image](https://user-images.githubusercontent.com/100844589/180376855-ce7deb9a-9bd4-4263-af6f-5fd0c259a595.png)
识别效果
![image](https://user-images.githubusercontent.com/100844589/180377311-536836b1-dc55-492c-888d-b97d9faf9391.png)

**Comment by yangy996** [comment]
模型初始化需要一定的时间，第二张图片开始就快了
