### ISSUE TITLE
Can't install paddleocr 

### ISSUE THREAD

**Issue by wgfsophia** [PaddlePaddle/PaddleOCR#6972]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
-Environment: macOS Monterey M1 
-Version: PaddlePaddle 2.3.1
-pip install "paddleocr>=2.0.1" 
-Error msg:
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

I run the requirements,txt line by line and I think the problem went with installing "opencv-contrib-python==4.4.0.46"
I only can successfully install opencv-contrib-python==4.4.0.66

**Comment by LDOUBLEV** [comment]
如果无法安装requirements,txt 里指定版本的opencv-contrib-python==4.4.0.66，可以去掉版本号部分==4.4.0.66，再去执行安装指令
