### ISSUE TITLE
表格结构检测训练数据

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#6976]
表格结构检测训练数据量达到多少合适呢

**Comment by WenmuZhou** [comment]
2w

**Comment by yangy996** [comment]
> 2w

只针对同一种模版的表格，也需要这么多数据集吗？

**Comment by WenmuZhou** [comment]
一种模板的没测试过 可以标几千张试一下

**Comment by ZTurboX** [comment]
> 一种模板的没测试过 可以标几千张试一下

用标注工具标注的时候单元格检测框只要覆盖掉单元格的所有文字，还是按照单元格形状

**Comment by WenmuZhou** [comment]
覆盖文字

**Comment by ZTurboX** [comment]
> 覆盖文字

对于空白单元格检测框是按照单元格形状吗
