### ISSUE TITLE
找不到推理模型，是本来就这样吗？

### ISSUE THREAD

**Issue by chen-da-qi** [PaddlePaddle/PaddleOCR#6978]
没找这里的推理模型，我想问下，是本来就这样的吗？
![5GNCYKVS2N9%} 2UFDUY@~J](https://user-images.githubusercontent.com/33750454/180631099-4e98d424-c396-48af-a0e4-19590eb0ed1f.png)

**Comment by tink2123** [comment]
测试链接可以下载，您这边再试下呢？
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

**Comment by chen-da-qi** [comment]
好的，谢谢
