### ISSUE TITLE
使用子进程启动时的问题

### ISSUE THREAD

**Issue by YangXJie** [PaddlePaddle/PaddleOCR#698]
**你好，我在使用gpu识别的情况下开启多进程，子进程会在执行红框的两句后报错。**

![image](https://user-images.githubusercontent.com/34944441/92674123-455e5f00-f34f-11ea-9768-6904803609eb.png)

 **异常信息**

![image](https://user-images.githubusercontent.com/34944441/92674468-f2d17280-f34f-11ea-88d9-18176e8668dd.png)

 **请问这个问题该怎么解决呢？**

**Comment by MissPenguin** [comment]
贴一下完整的启动命令吧

**Comment by YangXJie** [comment]
我是部署到服务上的，命令写到配置文件，里面只配置了模型的路径，下面的代码可以复现我的问题。
from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor
import multiprocessing

model_file_path = "./ch_det_r50_vd_db/model"
params_file_path = "./ch_det_r50_vd_db/params"


def init(config):
        config.enable_use_gpu(1000, 0)
        predictor = create_paddle_predictor(config)

if __name__ == '__main__':
        config = AnalysisConfig(model_file_path, params_file_path )
        t = multiprocessing.Process(target=init, args={config})
        t.start()

**Comment by BeyondYourself** [comment]
GPU好像不支持多进程并发的，GPU目前应该是支持多卡并发
