### ISSUE TITLE
用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir="./doc/imgs/test1/test2_1.png" --det_model_dir="./inference/ch_PP-OCRv3_det_infer/"  --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"  --rec_model_dir="./inference/ch_PP-OCRv3_rec_infer/" --use_angle_cls=True --rec_image_shape="3,32,320"

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#6981]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by zhangyingying520** [comment]
请问你使用的是什么配置的设备哪

**Comment by 1998wy123** [comment]
在服务器上跑的，服务器是GPU-3080TI,请问发票里指定字段的识别怎么处理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir="./doc/imgs/test1/test2_1.png" --det_model_dir="./inference/ch_PP-OCRv3_det_infer/"  --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"  --rec_model_dir="./inference/ch_PP-OCRv3_rec_infer/" --use_angle_cls=True --rec_image_shape="3,32,320" (Issue #6981)





 
请问你使用的是什么配置的设备哪

**Comment by yangy996** [comment]
有加载模型的过程，这部分也会耗时，从第二张图片开始就快了

**Comment by 1998wy123** [comment]
请问，推理的时候，预测图进入文本检测前会将图片尺寸resize到统一尺寸吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月3日(星期三) 晚上9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir=&quot;./doc/imgs/test1/test2_1.png&quot; --det_model_dir=&quot;./inference/ch_PP-OCRv3_det_infer/&quot;  --cls_model_dir=&quot;./inference/ch_ppocr_mobile_v2.0_cls_infer/&quot;  --rec_model_dir=&quot;./inference/ch_PP-OCRv3_rec_infer/&quot; --use_angle_cls=True --rec_image_shape=&quot;3,32,320&quot; (Issue #6981)





 
有加载模型的过程，这部分也会耗时，从第二张图片开始就快了

**Comment by yangy996** [comment]
> 请问，推理的时候，预测图进入文本检测前会将图片尺寸resize到统一尺寸吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月3日(星期三) 晚上9:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir=&quot;./doc/imgs/test1/test2_1.png&quot; --det_model_dir=&quot;./inference/ch_PP-OCRv3_det_infer/&quot; --cls_model_dir=&quot;./inference/ch_ppocr_mobile_v2.0_cls_infer/&quot; --rec_model_dir=&quot;./inference/ch_PP-OCRv3_rec_infer/&quot; --use_angle_cls=True --rec_image_shape=&quot;3,32,320&quot; (Issue #6981) 有加载模型的过程，这部分也会耗时，从第二张图片开始就快了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

官方的检测模型只限制最大尺寸，如果图片宽或高超过这个最大尺寸，会resize，如果小于最大尺寸就不会resize

**Comment by 1998wy123** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月3日(星期三) 晚上9:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir=&quot;./doc/imgs/test1/test2_1.png&quot; --det_model_dir=&quot;./inference/ch_PP-OCRv3_det_infer/&quot;  --cls_model_dir=&quot;./inference/ch_ppocr_mobile_v2.0_cls_infer/&quot;  --rec_model_dir=&quot;./inference/ch_PP-OCRv3_rec_infer/&quot; --use_angle_cls=True --rec_image_shape=&quot;3,32,320&quot; (Issue #6981)





  
请问，推理的时候，预测图进入文本检测前会将图片尺寸resize到统一尺寸吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年8月3日(星期三) 晚上9:03 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 用级联推理命令，为什么推理时间达到2.8秒，我看paddleocr论文写的是毫秒级呀，我测试的是单张图片，用的这个命令python tools/infer/predict_system.py --image_dir="./doc/imgs/test1/test2_1.png" --det_model_dir="./inference/ch_PP-OCRv3_det_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="./inference/ch_PP-OCRv3_rec_infer/" --use_angle_cls=True --rec_image_shape="3,32,320" (Issue #6981) 有加载模型的过程，这部分也会耗时，从第二张图片开始就快了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
官方的检测模型只限制最大尺寸，如果图片宽或高超过这个最大尺寸，会resize，如果小于最大尺寸就不会resize
