### ISSUE TITLE
微信公众号中的技术交流群二维码过期

### ISSUE THREAD

**Issue by huyunlei** [PaddlePaddle/PaddleOCR#6982]
paddleocr技术交流群二维码到22号，已经过期，希望更新一下，谢谢

**Comment by huyunlei** [comment]
![Screenshot_20220725_122108](https://user-images.githubusercontent.com/57059809/180698361-756e7b88-0ddf-4a7d-b691-316fab489888.jpg)

**Comment by Evezerest** [comment]
后台已更新

**Comment by huyunlei** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发来的邮件已经收到，我会尽快给您回复。
