### ISSUE TITLE
文本检测部分，想让模型检测出一个新的字符和中文，先用中文场景数据训练了一遍，再用新字符的数据训练一遍，但检测不出中文了

### ISSUE THREAD

**Issue by vousemevoyez1024** [PaddlePaddle/PaddleOCR#6986]
文本检测部分，想让模型检测出一个新的字符和中文，先用中文场景数据训练了一遍，再用新字符的数据训练一遍，但检测不出中文了。
业务场景想要实现每次只用新字符的数据去训练，但也想检测出中文，请问有什么正确的训练方式吗？

**Comment by vousemevoyez1024** [comment]
如果用中文+新字符合成数据肯定是可以两者检测到的，但如果业务场景下需要这样分开训练，请问有什么方法吗？

**Comment by zhangyingying520** [comment]
不可以的，除非你用两个检测模型，中文+新字符合成数据新的数据集是比较好的方法

**Comment by fanqie03** [comment]
字符检测：[https://github.com/fanqie03/char-detection/tree/main](https://github.com/fanqie03/char-detection/tree/main)
