### ISSUE TITLE
单机多卡训练出现ABORT!!! Out of all 2 trainers

### ISSUE THREAD

**Issue by xht** [PaddlePaddle/PaddleOCR#6988]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu20
- 版本号/Version：Paddle：2.3  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python -m paddle.distributed.launch --gpus '0,1' tools/train.py -c ./configs/det/det_mv3_db_lpr.yml
- 完整报错/Complete Error Message：
[2022/07/25 15:19:22] ppocr INFO: train with paddle 2.3.1 and device Place(gpu:0)
8888888888888888888888888
I0725 15:19:22.428663  4824 nccl_context.cc:83] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0725 15:19:22.629635  4824 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 11.2
W0725 15:19:22.649430  4824 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[2022/07/25 15:19:24] ppocr INFO: Initialize indexs of datasets:['/root/License_plate_recognition/train_data/ccpd/train_det2.txt']
[2022/07/25 15:19:24] ppocr INFO: Initialize indexs of datasets:['/root/License_plate_recognition/train_data/ccpd/dev_det2.txt']
89999999999999999999999999
[2022/07/25 15:19:24] ppocr INFO: load pretrain successful from ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2022/07/25 15:19:24] ppocr INFO: train dataloader has 72 iters
[2022/07/25 15:19:24] ppocr INFO: valid dataloader has 500 iters
[2022/07/25 15:19:24] ppocr INFO: During the training process, after the 100th iteration, an evaluation is run every 500 iterations
INFO 2022-07-25 15:19:55,096 launch_utils.py:322] terminate process group gid:4824
INFO 2022-07-25 15:19:55,096 launch_utils.py:322] terminate process group gid:4824
INFO 2022-07-25 15:20:02,134 launch_utils.py:343] terminate all the procs
INFO 2022-07-25 15:20:02,134 launch_utils.py:343] terminate all the procs
**ERROR 2022-07-25 15:20:02,144 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
ERROR 2022-07-25 15:20:02,144 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.**
INFO 2022-07-25 15:20:06,148 launch_utils.py:343] terminate all the procs
INFO 2022-07-25 15:20:06,148 launch_utils.py:343] terminate all the procs
INFO 2022-07-25 15:20:06,154 launch.py:402] Local processes completed.
INFO 2022-07-25 15:20:06,154 launch.py:402] Local processes completed.

**Comment by WenmuZhou** [comment]
看看debug目录下的workerlog.1文件中的报错信息

**Comment by angel-yi** [comment]
我遇到过，我是nccl配置的不对

**Comment by Zhang-O** [comment]
> 看看debug目录下的workerlog.1文件中的报错信息

debug 目录没找到，是在哪里设置吗

**Comment by yulm-1** [comment]
> 我遇到过，我是nccl配置的不对

怎么解决的您还记得吗
![0257f51077892a6cda91b2555987d98](https://user-images.githubusercontent.com/113872348/191634690-9b174cc5-009d-4b64-a5db-49525e8487dc.png)
