### ISSUE TITLE
PaddleOCR推理耗时很久

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleOCR#6994]
- 系统环境/System Environment：win10 x64
- 版本号/Version：Paddle：paddlepaddle-gpu 2.2.1.post112  PaddleOCR：release/2.5
- 运行指令/Command Code：.\build3\Release\ppocr.exe system --use_gpu=false --rec_batch_num=16 --det_model_dir=E:\workspace\AI\Detection\PaddleOCR\weights\ch_PP-OCRv2_det_slim_quant_infer --rec_model_dir=E:\workspace\AI\Detection\PaddleOCR\weights\ch_PP-OCRv2_rec_slim_quant_infer --image_dir=F:\Datasets\securety\save\net\
测试了同一张图片，对比c++和python的推理耗时，如下图所示，耗时巨大，请问这种耗时正常吗？
![image](https://user-images.githubusercontent.com/16351823/180914820-a048207c-12d8-41c8-82be-beca30c73e89.png)
附原图：
![screenshot_51_(156,25,1596,975)](https://user-images.githubusercontent.com/16351823/180915133-d4e862c2-1e69-498e-a804-6429e8115f26.png)

**Comment by littletomatodonkey** [comment]
你好，一般第一张图都会非常耗时，程序需要warmup，可以预测多张图片，看下后面的图片的预测耗时

**Comment by xdg2016** [comment]
@littletomatodonkey 
你好，我这边测了3张图，后续耗时都是这样，而且cpu上c++版本推理比python慢特别多，可不可以以帮忙测一下，是只有我这边会这样吗？这种耗时正常还是不正常的，谢谢
![image](https://user-images.githubusercontent.com/16351823/181142249-fd646c9b-11fb-41de-935a-931f6d5ba008.png)
附上另外2张图：
![screenshot_52_(156,25,1596,975)](https://user-images.githubusercontent.com/16351823/181142331-77cf9550-a7e4-4e65-84cb-999359d0dd46.png)

![screenshot_60_(156,25,1596,975)](https://user-images.githubusercontent.com/16351823/181142313-87b2ea0e-674c-4c0f-9258-0f1cda93e577.png)

**Comment by BeyondYourself** [comment]
可以看看检测和识别分别耗时

**Comment by xdg2016** [comment]
@BeyondYourself python版cpu，检测耗时约120ms左右，剩下的都是识别耗时了，但是这个耗时也很多，一张图cpu识别要好几秒，完全发挥不出超轻量级的优势呀

**Comment by BeyondYourself** [comment]
只能说版面的文字不是一般的多

**Comment by xdg2016** [comment]
@BeyondYourself 那这三张图的情况，这种耗时算是正常吗，尤其c++版的那个，请教一下，为啥会比python慢那么多

**Comment by dengmingD** [comment]
我试了一下倒数第二张图，c++预测cpu为1.92秒，如果用openvino则为0.75秒，ptyon比c++的慢，供参考
注：没用cls

**Comment by hiroi-sora** [comment]
简单测了一下 PPOCR C++ CPU版本

系统：win10

硬件：r5 4600u，比较拉的低压u


参数：启用enable_mkldnn，未启用cls

已忽略初始化和热身耗时

| 图片编号            | 1      | 2      | 3      | 对照1  | 对照2  |
| ------------------- | ------ | ------ | ------ | ------ | ------ |
| 文字块个数          | 140    |        |        | 2      | 10     |
| 字数                | 780    |        |        | 30     | 150    |
| 识别耗时：秒          |
| PPocr2.6 + 识别库v2 | 2.6161 | 2.9913 | 2.2933 | 0.2479 | 0.5969 |
| PPocr2.6 + 识别库v3 | 2.7711 | 3.1378 | 2.4338 | 0.2538 | 0.5776 |
| PPocr2.1 + 识别库v2 | 3.6454 | 5.0814 | 3.5014 | 0.4148 | 1.0518 |

v3耗时比v2略高是正常的，v3的识别率更高。

PPocr 2.6 似乎优化比 2.1 旧版本好得多。
