### ISSUE TITLE
高精度中文识别模型svtr配置文件缺失

### ISSUE THREAD

**Issue by cat-ball** [PaddlePaddle/PaddleOCR#6995]
高精度中文识别模型svtr配置文件rec_rec_svtrnet_ch.yml文件，在config/rec/文件夹下不存在，麻烦可以上传一下吗？

**Comment by littletomatodonkey** [comment]
你好，这个配置名称是从哪里获得的呢？如果是范例库的话，可以加群获取看下

**Comment by Topdu** [comment]
该配置文件可以在dygraph分支中找到，建议使用dygraph分支，release/2.5后续更新。
