### ISSUE TITLE
安卓端侧部署问题

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#7000]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04+Android8.1.0
在根据官方进行安卓端侧部署时：
运行命令:
`cd /data/local/tmp/debug
export LD_LIBRARY_PATH=${PWD}:$LD_LIBRARY_PATH
./ocr_db_crnn system ch_PP-OCRv2_det_infer_opt.nb ch_PP-OCRv2_rec_infer_opt.nb arm8 INT8 10 1 ./11.jpg config.txt ppocr_keys_v1.txt True`
其中config.txt中的cls置为0.
但是最终报错：
**system/bin/sh ocr_db_crnn not found**
请问大佬们，这是怎么回事呢？
另外，如果我这里运行成功。怎么部署到APP上面呢？从来没接触过这方面的部署。希望不吝赐教

**Comment by yangy996** [comment]
这篇文章可以看看
https://blog.csdn.net/YY007H/article/details/124774019
