### ISSUE TITLE
PPOCRv3训练，启动失败，两台电脑一样情况

### ISSUE THREAD

**Issue by asus10tu** [PaddlePaddle/PaddleOCR#7004]
A电脑：
显卡：GTX1060
系统环境/System Environment：win10，cuda10.6，cudnn7.6.5
版本号/Version：Paddle：paddlepaddle-gpu==2.2.2 也尝试过 2.3.0  
PaddleOCR： paddleocr==2.5.0.3

B电脑：
显卡：GTX3080
系统环境/System Environment：win10，cuda11.1，cudnn8.1.0
版本号/Version：Paddle：paddlepaddle-gpu==2.3.1.post111 也尝试过 2.1.3.post111
PaddleOCR： paddleocr==2.5.0.3

运行指令/Command Code：python tools/train.py -c .\configs\rec\PP-OCRv3\ch_PP-OCRv3_rec_distillation.yml
完整报错/Complete Error Message：

W0726 19:36:58.004176  9376 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.2
W0726 19:36:58.224562  9376 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[2022/07/26 19:37:03] ppocr INFO: load pretrain successful from ./pretrain_model/ch_PP-OCRv3_rec_train/best_accuracy
[2022/07/26 19:37:03] ppocr INFO: train dataloader has 1576 iters
[2022/07/26 19:37:03] ppocr INFO: valid dataloader has 439 iters
[2022/07/26 19:37:03] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 500 iterations
PS G:\driving_permits_distinguishaa\PaddleOCR-release-2.5>

运行训练后大概30秒就停下来了，两台电脑情况一致，而且显存均没有溢出，batch_size设定为1也尝试过，情况依旧。

**Comment by Mywayistheseaofstar** [comment]
我也是这种情况，求解！！！

**Comment by asus10tu** [comment]
有解答一下的么，好想用v3，一直用不上

**Comment by VieteChen** [comment]
请问ch_PP-OCRv3_rec_train.tar解压后只有best_accuracy.pdparams一个文件吗?

**Comment by asus10tu** [comment]
> Reference

你好是的，这个压缩包里只有一个文件，是没有选对么
