### ISSUE TITLE
使用PaddlePaddle 识别数字

### ISSUE THREAD

**Issue by lance520yuan** [PaddlePaddle/PaddleOCR#7007]
对于一部分数字效果很好，一部分就不行，这是为啥呢？

<img width="67" alt="image" src="https://user-images.githubusercontent.com/44315734/181185818-f231d8c6-9d01-4a62-804b-c6dc1aaa1ca9.png">

**Comment by zhangyingying520** [comment]
猜测是不是图片比例太极端了

**Comment by MissPenguin** [comment]
可以先确认下是检测的问题还是识别的问题

**Comment by yangy996** [comment]
应该是比例太极端了，可以尝试这种方式看看效果
https://blog.csdn.net/YY007H/article/details/124973777
