### ISSUE TITLE
麻烦问一下，遍历算子之后，这一句是什么意思哪？还是应该写成elif RecResizeImg in op_name：

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#7008]
https://github.com/PaddlePaddle/PaddleOCR/blob/4196e5d3d9b18630e5fddf79b23747aac1f0b468/tools/infer_rec.py#L89

**Comment by MissPenguin** [comment]
写法没问题哈，当前列表中只有‘ RecResizeImg’一项，后续有别的op都可以添加进来
