### ISSUE TITLE
服务器有多张显卡，paddleOCR推理时如何指定其中一张显卡

### ISSUE THREAD

**Issue by dengxuankun** [PaddlePaddle/PaddleOCR#7011]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
指定0，1，2，3号卡：export CUDA_VISIBLE_DEVICES=0,1,2,3
指定2号卡：export CUDA_VISIBLE_DEVICES=2
