### ISSUE TITLE
AI-studio课程—OCR表格识别实验问题

### ISSUE THREAD

**Issue by fx568000** [PaddlePaddle/PaddleOCR#7015]
我这边在AI-studio上复现课程内容，在复现快速体验环节时出现了2个问题；
1、在执行表格识别：
pred_html = table_sys(img) 时会报错
需要增加提取字典步骤如pred_html1 = pred_html['html']后才能正常进行，这是为什么，是因为模型输出结构变了，所以输出结果结构也跟着改变了吗，课程引用的模型有更新了？
2、虽然可以完成识别程序，但最终的识别结果非常的差，与课程里的识别结果差距严重；所以我想问下，造成这种现象的原因为什么？我这边核查过，使用的模型与输入图片与课程里是一致的，程序也没改，就是直接执行，为什么结果会有差距，想请相关人员核查一下

输入图片
![image](https://user-images.githubusercontent.com/49355496/181208528-1ea68d4e-8f5d-45a8-8557-d78e9dc79a89.png)
程序识别图片
![image](https://user-images.githubusercontent.com/49355496/181208684-c6451464-5168-491b-983d-3a52fb15f6b0.png)

**Comment by fx568000** [comment]
没人可以解答吗，跪求大神

**Comment by WenmuZhou** [comment]
1. 在那之后更新了代码，课程未更新，我们后续更新下
2. 我确认一下
