### ISSUE TITLE
Windows 安装时候出现错误 ERROR: Could not install packages due to an OSError

### ISSUE THREAD

**Issue by foolfish1** [PaddlePaddle/PaddleOCR#7017]
安装时候出现以下问题

System Environment：Windows 10
Python Version：3.10
Paddle Version： 2.3.1
PaddleOCR Version：>=2.0.1
Complete Error Message：ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\xxxxx\\xxxxxx\\AppData\\Local\\Temp\\pip-install-v71f_wl2\\opencv-contrib-python_e095f20900c740419f185bbeeecfd9a3\\opencv/samples/winrt_universal/VideoCaptureXAML/video_capture_xaml/video_capture_xaml.WindowsPhone/video_capture_xaml.WindowsPhone_TemporaryKey.pfx'

**Comment by fx568000** [comment]
你看看这个链接对你有没有帮助
https://blog.csdn.net/baidu_39621090/article/details/118074986

**Comment by foolfish1** [comment]
> 你看看这个链接对你有没有帮助 https://blog.csdn.net/baidu_39621090/article/details/118074986

谢谢！已解决，我把Python版本换成3.8就好了
