### ISSUE TITLE
LayoutXLM 有微调后可以直接用的模型吗？

### ISSUE THREAD

**Issue by pogevip** [PaddlePaddle/PaddleOCR#7018]
想测一下LayoutXLM 的效果，有微调后的模型吗？

两位大佬
@nbswords @MissPenguin

**Comment by MissPenguin** [comment]
有XFUN数据集上SER和RE任务的模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README_ch.md#2-%E6%80%A7%E8%83%BD
