### ISSUE TITLE
Segmentation fault (core dumped) on AWS g4dn.xlarge instance (Tesla T4 GPU)

### ISSUE THREAD

**Issue by 7ZFG1** [PaddlePaddle/PaddleOCR#7019]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： AWS g4dn.xlarge instance (Tesla T4 GPU)
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.5.0.3
 问题相关组件/Related components：python version: 3.7.5 GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0727 10:50:11.470382  2561 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully!

- 运行指令/Command Code：paddleocr --image_dir ./test_images_first/000000.png --use_angle_cls false --lang en --use_gpu true ( also tried "--use_gpu=false", same error occurs)
- 完整报错/Complete Error Message：--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1658917733 (unix time) try "date -d @1658917733" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2095 (TID 0x7fe62cc9c740) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by YachaoDong** [comment]
使用c++部署，同出现这个问题，请问最后怎么解决的？

**Comment by 7ZFG1** [comment]
Changing CUDA version 10.2 to 10.1 was worked for me.

**Comment by mazatov** [comment]
@7ZFG1 , have you fixed the problem? I'm also using g4dn.xlarge. I get the same error. 

I'v read things about Cuda versions. Mine has cuda 10.0 and paddle =2.4.1
