### ISSUE TITLE
分别对检测和识别模型进行finetune后，如何使用paddleocr.py文件完成测试呢？

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/PaddleOCR#702]
如题，我使用自己的训练集，对检测和识别模型，分别进行了finetune。独立获得了det和rec的最新模型，想按照paddleocr.py文件那样，直接转成model和params文件，以便直接调用测试。
具体要如何操作呢？？求指点。。

**Comment by WenmuZhou** [comment]
参考这里
![image](https://user-images.githubusercontent.com/12406017/92712525-64c7ad00-f38c-11ea-9187-b2028d8a6867.png)

**Comment by lmw0320** [comment]
拜谢大佬指点~~
@WenmuZhou

**Comment by rsingh2083** [comment]
> 如题，我使用自己的训练集，对检测和识别模型，分别进行了finetune。独立获得了det和rec的最新模型，想按照paddleocr.py文件那样，直接转成model和params文件，以便直接调用测试。
> 具体要如何操作呢？？求指点。。

What steps did you follow for finetuning the model?
