### ISSUE TITLE
请问方向分类器怎么单独使用

### ISSUE THREAD

**Issue by asus10tu** [PaddlePaddle/PaddleOCR#7021]
只是想知道当前图片是什么角度的

**Comment by LDOUBLEV** [comment]
文字方向分类器的内容可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/angle_class.md

**Comment by asus10tu** [comment]
> 文字方向分类器的内容可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_ch/angle_class.md

可否不用外部调用的形式，而是像识别那样用代码调用：
from paddleocr import PaddleOCR
# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
        ocr = PaddleOCR(
            use_gpu=True, 
            use_angle_cls=True, 
            det_db_unclip_ratio=2.5, 
            det_db_box_thresh=0.1,
            lang="ch",
            det_model_dir='ch_model/ch_PP-OCRv3_det_infer',
            rec_model_dir='ch_model/ch_PP-OCRv3_rec_infer',
            cls_model_dir='ch_model/ch_ppocr_mobile_v2.0_cls_infer',
            )
        img_path = 'xxx.jpg'
        r = ocr.ocr(img_path, cls=True)
        print(r)
这样的形式来使用方向分类器呢

**Comment by LDOUBLEV** [comment]
> 这样的形式来使用方向分类器呢

这样使用是 文字检测 + 文字方向分类器 + 文字识别的串联组合；

其中文字方向分类器充当一个插件的功能，负责识别检测到的文本框里的文字是0度 或者180度

**Comment by asus10tu** [comment]
> > 这样的形式来使用方向分类器呢
> 
> 这样使用是 文字检测 + 文字方向分类器 + 文字识别的串联组合；
> 
> 其中文字方向分类器充当一个插件的功能，负责识别检测到的文本框里的文字是0度 或者180度

那可否我代码调整一下，单独使用方向分类器这个插件呢，有时候需要用到这个功能

**Comment by LDOUBLEV** [comment]
需要你修改ppocr.py的代码的预测逻辑，把方向分类器的预测逻辑单独抽取出来，然后重新编译whl包使用；
