### ISSUE TITLE
请问场景应用的教程还会持续更新吗

### ISSUE THREAD

**Issue by shengjie-shi** [PaddlePaddle/PaddleOCR#7025]
首先感谢PaddleOCR组成员的贡献，极大帮助了产业落地！
最近看到项目中会有关于场景应用的教程实验文档，也给我提供了不少思路，请问下里面更多的教程比如手写体识别实现、卡证识别、印章提取等教程内容还会持续更新吗？非常期待PaddleOCR在产业落地上方案上的示例

**Comment by LDOUBLEV** [comment]
你提到的这些会持续更新的，请保持关注

**Comment by shengjie-shi** [comment]
感谢！大大的赞👍
