### ISSUE TITLE
文字检测（Text Detection）中英文文档对可使用的预处理模型描述不一致

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7026]
在中文文档中<sup>[1](#ft1)</sup>：
>首先下载模型backbone的pretrain model，PaddleOCR的检测模型目前支持**两种backbone**，分别是MobileNetV3、ResNet_vd系列， 您可以根据需求使用[PaddleClas](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.0/ppcls/modeling/architectures)中的模型更换backbone， 对应的backbone预训练模型可以从[PaddleClas repo 主页中找到下载链接](https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/README_cn.md#resnet%E5%8F%8A%E5%85%B6vd%E7%B3%BB%E5%88%97)。

在英文文档中<sup>[2](#ft2)</sup>:
>First download the pre-trained model. The detection model of PaddleOCR currently supports **3 backbones**, namely MobileNetV3, ResNet18_vd and ResNet50_vd. You can use the model in [PaddleClas](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.0/ppcls/modeling/architectures) to replace backbone according to your needs.

哪个版本的标准更准确呢？

<a name="ft1">[1]</a>: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/detection.md#12-%E4%B8%8B%E8%BD%BD%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B

<a name="ft2">[2]</a>: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/detection_en.md#12-download-pre-trained-model

**Comment by LDOUBLEV** [comment]
感谢指正，两个版本的描述意思是一样的，目前PaddleOCR检测模型的backbone 有两种，mobile系列和resnet系列，
英文文档里写的更详细一些，包含：MobileNetV3, ResNet18_vd and ResNet50_vd.
