### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#703]
您好，我按照快速安装配置好docker环境以后，下载了icdar2015数据集，在执行训练的时候，遇到如下报错：请问是什么原因导致的呢？

![image](https://user-images.githubusercontent.com/43515926/92831868-82872780-f409-11ea-9663-ef01c0bcd872.png)
![image](https://user-images.githubusercontent.com/43515926/92831904-8e72e980-f409-11ea-89b7-3185f98fc790.png)

**Comment by tink2123** [comment]
没有正确安装nccl，请问是在docker里运行的吗

**Comment by zcswdt** [comment]
> 没有正确安装nccl，请问是在docker里运行的吗

对，docker的环境配置都是按照快速安装的指导下配置的，跑预测代码是没问题的，但是训练代码跑不了。请问这个如何解决呢？  
![image](https://user-images.githubusercontent.com/43515926/92874283-77002480-f43a-11ea-8e58-0834935448a8.png)

**Comment by tink2123** [comment]
进入python解释器，然后输入
import paddle.fluid
paddle.fluid.install_check.run_check()

看一下能否看到 “Your Paddle Fluid is installed successfully!” 呢

**Comment by zcswdt** [comment]
> paddle.fluid.install_check.run_check()

这个上午的时候我看了，好像是成功的，我截图给您看下。
![image](https://user-images.githubusercontent.com/43515926/92878614-deb86e80-f43e-11ea-8ae0-0a45f96b1d27.png)

**Comment by tink2123** [comment]
paddle没有正确安装，请卸载后重新安装。安装命令用： python3 -m pip install paddlepaddle-gpu==1.8.1.post97 试一下

**Comment by zcswdt** [comment]
> paddle没有正确安装，请卸载后重新安装。安装命令用： python3 -m pip install paddlepaddle-gpu==1.8.1.post97 试一下

您好，我按照您的指令重装了一下paddle如下图：
![image](https://user-images.githubusercontent.com/43515926/92895438-124ec500-f44e-11ea-9abe-66facf0ba32c.png)

但是还是会报错：执行import paddle.fluid和paddle.fluid.install_check.run_check()还是和之前一样。如下：
![image](https://user-images.githubusercontent.com/43515926/92895679-4b873500-f44e-11ea-955a-1c5273ed25e0.png)

**Comment by tink2123** [comment]
请问您的机器配置是？

**Comment by zcswdt** [comment]
> 请问您的机器配置是？
我是在docker环境下，cuda10.2,显卡RTX2080，8G显存。
![image](https://user-images.githubusercontent.com/43515926/93053507-7960b980-f69a-11ea-9be8-f395bcca08b4.png)

**Comment by tink2123** [comment]
请问您的机器是否正确安装了nccl呢？可以尝试重新安装一下，可参考：https://developer.nvidia.com/nccl

**Comment by zcswdt** [comment]
> 请问您的机器是否正确安装了nccl呢？可以尝试重新安装一下，可参考：https://developer.nvidia.com/nccl

您好，我刚才去官网又重新下载了nccl，安装命令如下：
![image](https://user-images.githubusercontent.com/43515926/93159596-1a09b480-f741-11ea-8729-98ff9ce59158.png)
![image](https://user-images.githubusercontent.com/43515926/93159643-3d346400-f741-11ea-8a8c-5f988ba97a2c.png)
然后仍然会出现报错：
![image](https://user-images.githubusercontent.com/43515926/93159733-740a7a00-f741-11ea-8fbf-9495d9f22461.png)

**Comment by LDOUBLEV** [comment]
安装的是哪个版本的paddle

**Comment by zcswdt** [comment]
> nccl



> 看你的docker环境是10， 建议安装cuda10 cudnn7的paddle，安装命令：
> python3 -m pip install paddlepaddle-gpu==1.8.4.post107 -i https://mirror.baidu.com/pypi/simple

谢谢指导，我按照这个命令装了一下，但是运行import paddle.fluid和paddle.fluid.install_check.run_check()还是会报错。我是真的不知道我哪里出问题了。
![image](https://user-images.githubusercontent.com/43515926/93199706-45ac8f00-f781-11ea-9f1d-943a1ea35548.png)
![image](https://user-images.githubusercontent.com/43515926/93199753-5bba4f80-f781-11ea-8ce4-56449a1051db.png)
