### ISSUE TITLE
'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by vivisl** [PaddlePaddle/PaddleOCR#7030]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README_ch.md
根据教程安装好了环境，下载好了预训练模型，启动训练出错：

- 系统环境：Ubuntu 18.04.5 LTS
- 显卡：3090 x 6
- paddlenlp 2.3.4
- paddleocr 2.5.0.3
- paddlepaddle 2.3.0
- paddlepaddle-gpu 2.3.0.post112            
- 运行指令：CUDA_VISIBLE_DEVICES=0 python3 tools/train.py -c configs/vqa/ser/layoutxlm.yml
- 完整报错：

> /home/user/anaconda3/envs/vivi_scope/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
>   warnings.warn(
> Traceback (most recent call last):
>   File "tools/train.py", line 188, in <module>
>     config, device, logger, vdl_writer = program.preprocess(is_train=True)
>   File "/data/Vivi/PaddleOCR/tools/program.py", line 574, in preprocess
>     device = 'gpu:{}'.format(dist.ParallelEnv()
>   File "/home/user/anaconda3/envs/vivi_scope/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 200, in device_id
>     return self._device_id
> AttributeError: 'ParallelEnv' object has no attribute '_device_id'

感谢各位大神帮忙解决！

**Comment by LDOUBLEV** [comment]
可以验证下paddle-gpu安装的是否正确

export CUDA_VISIBLE_DEVICES=0 
```
import paddle
paddle.utils.run_check()
import paddle.distributed as dist
print(dist.ParallelEnv().dev_id)
```

**Comment by lutianye** [comment]
您好，请问问题解决了吗，我把yaml里面的use_gpu改成了false，可以用cpu训练但是要22天

**Comment by leoterry-ulrica** [comment]
请问解决了没？遇到同样问题。

**Comment by LouisVA** [comment]
Make sure you select the right paddlepaddle-gpu version and CUDA if you use nvidia. In my case I found it here: https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/windows-pip_en.html#gpu
