### ISSUE TITLE
请问predict_det.py文件里有检测算法的选择，下载推理模型的作用是什么呢？是推理模型里包含了各种检测算法吗？在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7032]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
推理模型是不同的算法模型，一种推理模型对应一种算法，都是使用predict_det.py去预测，所以predict_det.py文件里有检测算法的选择

**Comment by 1998wy123** [comment]
推理的py文件是怎么调用下载好的模型呢？通过哪个函数呢？我在源码里没看到？请教一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 晚上8:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问predict_det.py文件里有检测算法的选择，下载推理模型的作用是什么呢？是推理模型里包含了各种检测算法吗？在线等 (Issue #7032)





 
推理模型是不同的算法模型，一种推理模型对应一种算法，都是使用predict_det.py去预测，所以predict_det.py文件里有检测算法的选择

**Comment by LDOUBLEV** [comment]
加载推理模型在：https://github.com/PaddlePaddle/PaddleOCR/blob/6bc1465b8a816ebf9ce8bf666424bde07766bb88/tools/infer/utility.py#L173-L182

**Comment by 1998wy123** [comment]
请问paddleocr的课程以后还会开设吗？还有个问题想请教您，paddleocr是全文识别，我想取发票上的某些字段，这怎么处理呢？老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问predict_det.py文件里有检测算法的选择，下载推理模型的作用是什么呢？是推理模型里包含了各种检测算法吗？在线等 (Issue #7032)





 
加载推理模型在：https://github.com/PaddlePaddle/PaddleOCR/blob/6bc1465b8a816ebf9ce8bf666424bde07766bb88/tools/infer/utility.py#L173-L182

**Comment by LDOUBLEV** [comment]
以前的课程也适用当前的代码；

> paddleocr是全文识别，我想取发票上的某些字段，这怎么处理呢？

如果是重新训练，只标注感兴趣的文字即可

或者对识别的字符采用规则的方式排除不想要的内容

**Comment by 1998wy123** [comment]
请问老师，paddleocr的推理一张图片是2.8秒，论文上是毫秒级，这是什么原因呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 晚上7:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问predict_det.py文件里有检测算法的选择，下载推理模型的作用是什么呢？是推理模型里包含了各种检测算法吗？在线等 (Issue #7032)





 
以前的课程也适用当前的代码；
  
paddleocr是全文识别，我想取发票上的某些字段，这怎么处理呢？
  
如果是重新训练，只标注感兴趣的文字即可
 
或者对识别的字符采用规则的方式排除不想要的内容

**Comment by LDOUBLEV** [comment]
第一次预测比较慢，后续预测会比较快
