### ISSUE TITLE
Is Doc-VQA allowed for commercial use?

### ISSUE THREAD

**Issue by martinkozle** [PaddlePaddle/PaddleOCR#7033]
As far as I can understand the official Layout pretrained models are not allowed for commercial use ([source](https://github.com/microsoft/unilm/issues/352#issuecomment-939248683)). Is your implementation for LayoutXLM allowed for commercial use?

**Comment by LDOUBLEV** [comment]
> Is your implementation for LayoutXLM allowed for commercial use?

Yes. For more details, please refer to the  License

**Comment by martinkozle** [comment]
I want to clear things up a little bit more. At the end of the [README.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README.md#license) in `/ppstructure/vqa/` it says under **License**: "The content of this project itself is licensed under the [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)".

Can you please clarify which parts of the project are under this License. Does it just mean that the project sources can't be distributed commercially. Or does it also mean for example that a product made using this project as a library also cannot be distributed commercially?

**Comment by MissPenguin** [comment]
> I want to clear things up a little bit more. At the end of the [README.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README.md#license) in `/ppstructure/vqa/` it says under **License**: "The content of this project itself is licensed under the [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)".
> 
> Can you please clarify which parts of the project are under this License. Does it just mean that the project sources can't be distributed commercially. Or does it also mean for example that a product made using this project as a library also cannot be distributed commercially?

If there is no separate description of the license, it follows the Apache 2.0 license. Specifically, the layoutlm series of algorithms is licensed under [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/), inherited from its original author Microsoft, and everything else is Apache 2.0 license.
