### ISSUE TITLE
请问TextSystem类构造的对象是否多线程安全？

### ISSUE THREAD

**Issue by yoeaki** [PaddlePaddle/PaddleOCR#7034]
`TextSystem`类位置：`tools/infer/predict_system.py`

场景描述：项目只实例化一次`text_sys = TextSystem(args)`，作为一个全局变量共用，开启多个线程同时跑`predict_system.py` 预测任务。 
这种场景下`TextSystem`是否存在线程安全问题？

**Comment by andyjpaddle** [comment]
这个不保证线程安全，如果需要可以自己加锁
