### ISSUE TITLE
ARM架构下，CPU开启MKLDNN反而变慢

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/PaddleOCR#704]
在CPU单线程情况下，识别一个14个文字行的图片，不开启mkldnn检测+识别大概需要20秒的时间，但是开启了mkldnn后反而时间增加到31秒，慢了一半。在其他X86架构的CPU服务器上，都很正常，开启mkldnn时间都要快一倍以上，但是ARM架构的就有问题。

**Comment by LDOUBLEV** [comment]
mkldnn是intel CPU上加速的吧，arm上建议用deploy/lite 这个demo
