### ISSUE TITLE
文字识别部分使用自己数据集测试集比训练集acc高怎么回事？？？

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#7041]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以提供一下详细数据吗

**Comment by JavieYuan** [comment]
> 
eval:
acc:0.99   eds:o.99
train:
acc:0.89  eds:0.98
数据集为英文文本的    整行大概2-30个单词   train+test共6w张图

**Comment by JavieYuan** [comment]
> 



> > 
> 
> eval: acc:0.99 eds:o.99 train: acc:0.89 eds:0.98 数据集为英文文本的 整行大概2-30个单词 train+test共6w张图

使用的是rec_svtr_tiny_none_ctc_en_train预训练模型

**Comment by Topdu** [comment]
1:打印预测结果，检查是否预测正确
如果预测不正确，但是精度却很高，说明代码有bug

2: 如果在训练阶段使用了数据增强，这个现象是合理的

**Comment by JavieYuan** [comment]
> 1:打印预测结果，检查是否预测正确 如果预测不正确，但是精度却很高，说明代码有bug
> 
> 2: 如果在训练阶段使用了数据增强，这个现象是合理的

**Comment by Topdu** [comment]
> > 1:打印预测结果，检查是否预测正确 如果预测不正确，但是精度却很高，说明代码有bug
> > 2: 如果在训练阶段使用了数据增强，这个现象是合理的
> 
> ![image](https://user-images.githubusercontent.com/84179587/182288745-1741399b-38ec-4166-97c9-7548f43e1b8e.png) rec_xxxxxx.yml 配置文件中 Train: transforms: -RecAug: -RecAug:此行后面为空，无内容，那么训练集中数据增强初始默认是开着的吗？ 测试阶段源代码初始默认应该是没有使用数据增强的

这样配置是使用了数据增强的
