### ISSUE TITLE
ser 训练报错

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleOCR#7048]
'remote_prefetch', False, 'padding_idx', padding_idx)
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got -50. Please check input value.
  [Hint: Expected ids[i] >= 0, but received ids[i]:-50 < 0:0.] (at /home/Paddle/paddle/phi/kernels/cpu/embedding_kernel.cc:72)
  [operator < lookup_table_v2 > error]

**Comment by 471417367** [comment]
训练数据有问题，我之前也遇到过。图片在win上旋转后cv2.imread读取是旋转后的，Image.open是旋转前的。很多标注软件用的Image，但是因为训练或其他原因，比如你重新用cv2处理过图片，标注的坐标与图片就对不上了，长宽的不同会导致box越界。

**Comment by 471417367** [comment]
训练数据有问题，我之前也遇到过。图片在win上旋转后cv2.imread读取是旋转后的，Image.open是旋转前的。很多标注软件用的Image，但是因为训练或其他原因，比如你重新用cv2处理过图片，标注的坐标与图片就对不上了，长宽的不同会导致box越界。

**Comment by littletomatodonkey** [comment]
建议再检查下数据格式呢？
