### ISSUE TITLE
Eval加载数据时中途卡死且未报错

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleOCR#7050]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：python3.7.13 Paddle2.3.1  PaddleOCR2.5 OpenCV4.4.0
- 运行指令/Command Code：python tools/train.py -c model/det_r50_vd_db.yml -o Global.pretrained_model=./det_r50_vd/best_accuracy
- 完整报错/Complete Error Message：卡死但未报错；训练DB检测算法时，训练没问题，但评估执行到program.py 下的eval函数的 `for idx, batch in enumerate(valid_dataloader):` 时总卡住（未拿到数据，停留在这一行，且一直等待）。下面这样
   eval model::   0%|▌                                                                            | 1/339 [00:00<00:56,  5.93it/s]
- 经过多次实验发现，1. 并不是每次执行eval时都卡住，跑过20+次程序，目测**评估**每执行2-3次程序就会卡住；2. 每次卡住都在第0个batch step或第1个batch step；4. 为验证eval dataset数据集问题，将val data用作训练，train data用作评估，结果还是只在评估时报错，训练过程没任何问题，判断**数据集是没问题**的。

**Comment by yulongblue** [comment]
我也遇到同样的问题，怎么解决？
