### ISSUE TITLE
增值税发票结构化识别

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleOCR#7051]
增值税发票结构化识别是什么思路呢？

**Comment by littletomatodonkey** [comment]
1. 传统思路：可以直接用ocr检测识别+模板匹配
2. 可以使用关键信息抽取的方法，去做文档vqa任务

场景非常固定的话，建议第一种，成本会低一些，如果考虑扩展性，可以用第二种

**Comment by ZTurboX** [comment]
> *

用第一种方法，ocr检测结果会把单元格内的多行文本分开
