### ISSUE TITLE
NB模型识别率下降

### ISSUE THREAD

**Issue by metaire** [PaddlePaddle/PaddleOCR#7056]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：debian9.x Paddle lite：2.10  
- 你好，生成NB模型后，识别率下降，相同的图片，用原模型在window上识别和NB模型在linux上识别，效果差很多。应该如何解决，或从哪方面可以优化。望指教。

**Comment by littletomatodonkey** [comment]
先看下inference model的预测结果是否准确，另外就是建议用最新的release版本的paddleite_opt工具去转换
