### ISSUE TITLE
Latest Paddleocr Installation in Python 3.7.0

### ISSUE THREAD

**Issue by TheinHtayAung91** [PaddlePaddle/PaddleOCR#7060]
When I installed paddleocr latest version in python 3.7.0 using pip, below errors are happened.

Could not find a version that satisfies the requirement numpy==1.13.3 (from versions: 1.14.5, 1.14.6, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
No matching distribution found for numpy==1.13.3

How may I fix it?

**Comment by TheinHtayAung91** [comment]
I change python version to 3.7.9 and it was ok.
But below error is happened.

<Python Script>
from paddleocr import PaddleOCR
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
img_path = '2.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

<Error>
  File "c:/Users/Win Kyaw/Desktop/Python/image_matching/app/test1.py", line 1, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\Win Kyaw\Desktop\Python\image_matching\env\lib\site-packages\paddleocr\__init__.py", line 14, in <module> 
    from .paddleocr import *
  File "C:\Users\Win Kyaw\Desktop\Python\image_matching\env\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

**Comment by TheinHtayAung91** [comment]
I assume error is due to no paddle.

I tried to install paddle. Below error is happened.

(env) C:\Users\Win Kyaw\Desktop\Python\image_matching>pip install paddle
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\WINKYA~1\AppData\Local\Temp\pip-install-m_ohkhnv\paddle_2282338413834358b602161f670d15a3\setup.py", line 3, in <module>
          import paddle
        File "C:\Users\WINKYA~1\AppData\Local\Temp\pip-install-m_ohkhnv\paddle_2282338413834358b602161f670d15a3\paddle\__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by littletomatodonkey** [comment]
Hi, you can follow this page to install paddle. 

https://www.paddlepaddle.org.cn/en
