### ISSUE TITLE
表格结构识别在识别中文表格时的准确性

### ISSUE THREAD

**Issue by AndyHUI711** [PaddlePaddle/PaddleOCR#7061]
使用官方表格结构预测模型识别表格，对比中文表格和英文表格，发现中文表格的结构识别效果比较差。
请问，如果想要提升中文表格结构识别能力，是否要再根据中文表格进行训练。
谢谢！

**Comment by MissPenguin** [comment]
使用中文表格数据重新训练是可以提升效果的。最近PP-Structurev2在研发中，也会对算法有一个升级，欢迎持续关注。

**Comment by ZTurboX** [comment]
> 使用中文表格数据重新训练是可以提升效果的。最近PP-Structurev2在研发中，也会对算法有一个升级，欢迎持续关注。

可以在开源的模型基础上，用中文数据微调吗

**Comment by littletomatodonkey** [comment]
可以的，这次会给出详细的表格识别模型微调文档

**Comment by WenmuZhou** [comment]
中文模型已经发布，欢迎试用

**Comment by BEILOP** [comment]
> 

<img width="546" alt="1661939791(1)" src="https://user-images.githubusercontent.com/74578330/187652160-a6a9a0d2-008f-4525-9490-e9e512cc40b2.png">
