### ISSUE TITLE
我想知道12M的ch_PP-OCRv3_rec 和108M的ch_ppocr_v2.0_rec哪个准确率更高？？

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/PaddleOCR#7062]
前者的训练模型200多兆比后者大 而前者的推断模型只有12M后者108M 到底哪个推断准确率更高，不考虑推断速度

**Comment by PureWerZ** [comment]
个人测试下来，未蒸馏的rec_v2准确率更高些

**Comment by littletomatodonkey** [comment]
在我们的场景里，ch_PP-OCRv3_rec精度更高一些，不同场景可能不太相同，使用的话建议用ch_PP-OCRv3_rec，一般finetune效果会更好一些
