### ISSUE TITLE
请问预测中的warmup有什么用？

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#7068]
https://github.com/PaddlePaddle/PaddleOCR/blob/6bc1465b8a816ebf9ce8bf666424bde07766bb88/tools/infer/predict_rec.py#L412-L416
训练中的warmup是优化学习率，那预测时为什么要加warmup呢？这个warmup和训练中的warmup是同一个东西吗？

**Comment by MissPenguin** [comment]
预测和训练的warmup不是同一个概念哈，预测加warmup是为了测试速度更准确，因为前几张图往往由于初始化会耗时比较多，warmup中随机生成img进行预测完成初始化，后面正常图的测试就比较稳定了
