### ISSUE TITLE
关于SRN不同模块的分类层输出维度不一致

### ISSUE THREAD

**Issue by hao6699** [PaddlePaddle/PaddleOCR#707]
pvam模块的分类输出维度为(-1, char_num)
gsrm模块的分类输出维度为(-1, char_num+1)
vsfd模块的分类输出维度为(-1, char_num)
为什么gsrm模块的类别多了一类? 而用于计算loss的label维度都是char_num

**Comment by tink2123** [comment]
抱歉，这里是代码有误。多了一类是因为 gsrm 中的 src_word_emb_tabel 中有一个额外的截至符，pvam 和 vsfd 的输出维度也应该是 char_num+1 的，这里我们会修复下。感谢反馈

**Comment by tink2123** [comment]
抱歉～这里gsrm的输入维度也应该是 char_num ，之前+1 是因为wore_emb_table中包含截至符，更新后的代码中char_num 已经包含了起始和截至符，这里应该去掉+1，我们会尽快修复～感谢您的反馈

**Comment by sheirving** [comment]
最新的SRN中GSRM这个char_num+1应该还没修复吧？另外修复的时候应该pad_idx=self.char_num 改为pad_idx=self.char_num-1对吧？
