### ISSUE TITLE
在jetson盒子上运行ppocrv3内存未回收

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleOCR#7071]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- jetson nx jepack 4.6 cuda 10.2 cudnn 8.2.1 ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 2.3.0 with trt
PaddleOCR release/2.5
- 运行指令/Command Code：
改造tools/infer/predict_system.py进行连续图片的推理
- 完整报错/Complete Error Message：
运行12小时候，运行内存占用从原来的6.4G增长到7.0G

**Comment by LDOUBLEV** [comment]
> 运行12小时候，运行内存占用从原来的6.4G增长到7.0G

是内存还是显存？
如果是内存，可以继续观察是否会持续增长，正常情况下，内存占用的波动始终在一定范围内，最终回归到合理范围，如果持续增加，应该是发生了内存泄露。

如果是显存增加，大概是有的预测的图像比较大，占用的显存变多，即使下一次预测的图像比较小，多占用的显存也不会释放

**Comment by ChenjieXu** [comment]
你好，Jetson NX中显存和内存是一体的，总共8G。预测图像为连续视频，应该不存在图片大小的变化。目前情况为持续增加，怀疑是内存泄漏问题。
