### ISSUE TITLE
跑起来速度不咋快，求解决方法

### ISSUE THREAD

**Issue by luohaihan** [PaddlePaddle/PaddleOCR#7073]
paddleOCR版本：release2.5
paddle版本:官网最新的2.3.1的预测库
c++版本编译好之后用gpu跑500*750的图片，用的参数都是默认的，模型是官网下载的轻量模型(几M的那个)。
除开前面两张特别慢，后面速度大概稳定在100ms左右。
想继续加快速度有什么办法吗。开tensorrt会不会更快

**Comment by MissPenguin** [comment]
开tensorrt可以进一步加速
