### ISSUE TITLE
k系列无法使用 

### ISSUE THREAD

**Issue by renoyuan** [PaddlePaddle/PaddleOCR#7074]
目前K系列的都无法调用GPU去跑PaddleOCR跑出来全部是乱码，使用cpu可以推理也没有报错信息
没有找到原因
k80 k40 
- 系统环境/System Environment：ubuhntu 18.0.4
- 版本号/Version：paddlepaddle-gpu==2.1.3.post110 &2.2Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：没有报错信息
![image](https://user-images.githubusercontent.com/50486789/182328525-cee024d4-89b5-49f3-90b9-e14f9bbc0845.png)
![image](https://user-images.githubusercontent.com/50486789/182328568-24fecb22-dce2-4726-9ad1-3f973f26004a.png)

**Comment by MissPenguin** [comment]
我们没有k系列机器来复现问题，不过感觉不应该，把paddle更新到2.3版本、ocr使用2.5版本试试呢，另外在别的型号的机器上是否能正确运行呢
