### ISSUE TITLE
Typos in documents

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7075]
>PaddleOCR • doc/doc_ch/detection.md:
  66  
  67: 上述指令中，通过-c 选择训练使用configs/det/det_db_mv3.yml配置文件。
  68  有关配置文件的详细解释，请参考[链接](./config.md)。

>PaddleOCR • doc/doc_en/detection_en.md:
   53  
   54: In the above instruction, use `-c` to select the training to use the `configs/det/det_db_mv3.yml` configuration file.
   55  For a detailed explanation of the configuration file, please refer to [config](./config_en.md).
  186  
  187: Run the following code to calculate the evaluation indicators. The result will be saved in the test result file specified by `save_res_path` in the configuration file `det_db_mv3.yml`
  188  

where _det_db_mv3.yml_ should be _det_mv3_db.yml_.

**Comment by MissPenguin** [comment]
Thanks for your feedback. The typos have been fixed~
