### ISSUE TITLE
paddleocr十讲课程里面，文本识别的那节课里面没给数据集，程序运行不了了

### ISSUE THREAD

**Issue by zeng-cy** [PaddlePaddle/PaddleOCR#7081]
!cd /home/aistudio/work/train_data/ && tar xf ic15_data.tar 
/bin/bash: line 0: cd: /home/aistudio/work/train_data/: No such file or directory
课程里面没有数据集，课程讲课老师说有，能补充上去吗?

**Comment by LDOUBLEV** [comment]
可以先从这里下载ic15的数据集，和对应的标签文件： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/dataset/ocr_datasets.md#22-%E5%85%AC%E5%BC%80%E6%95%B0%E6%8D%AE%E9%9B%86

会补充上！

**Comment by LDOUBLEV** [comment]
数据集已补充上，重新发布，请在课程页面点击重新学习

**Comment by zeng-cy** [comment]
> 数据集已补充上，重新发布，请在课程页面点击重新学习

谢谢啦
