### ISSUE TITLE
OCR识别任务部署到Spark，出现问题，烦请各位帮忙看看！

### ISSUE THREAD

**Issue by hynnn** [PaddlePaddle/PaddleOCR#7083]
想要使用Spark并发执行识别任务，因为数据量很大

但因为对Spark的/home/文件没有权限，而python3.7/site-packages/paddle/dataset中common.py有创建文件夹
![image](https://user-images.githubusercontent.com/43490343/182518742-8a0e8e09-4769-48b2-9ace-9edae58a8f72.png)

于是，我修改了创建位置，但是出现的新问题
![image](https://user-images.githubusercontent.com/43490343/182518846-054c5964-47d8-4dcf-a0ad-fccd33349569.png)

想问一下各位做过部署到Spark上的是需要做什么修改吗？

**Comment by LDOUBLEV** [comment]
报错提示很明显了，没有找到字典文件：
![image](https://user-images.githubusercontent.com/26592129/182537395-b1bf7f90-2f24-44f6-a4c1-2d1a8416c827.png)

**Comment by hynnn** [comment]
您好，您的邮件我已收到，我会尽快查看，谢谢，祝您生活愉快。

**Comment by hynnn** [comment]
您好，您的邮件我已收到，我会尽快查看，谢谢，祝您生活愉快。
