### ISSUE TITLE
How to predict?

### ISSUE THREAD

**Issue by 284nnuS** [PaddlePaddle/PaddleOCR#7085]
I have train the new model for japanese dict. But idk how to use it without using parse like python3 tools/infer_rec.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model={path/to/weights}/best_accuracy  Global.infer_img=doc/imgs_words/en/word_1.png
So how can i simply predict that?

**Comment by LDOUBLEV** [comment]
The trained model can be convert to the inference model which is easier to deploy and inference.
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/doc/doc_en/algorithm_rec_crnn_en.md#4-inference-and-deployment
