### ISSUE TITLE
paddleocr android opencl部署报错 malloc image is out of max image size(w,h):16384,16384, need image size(w,h):18560,16

### ISSUE THREAD

**Issue by limaopeng1** [PaddlePaddle/PaddleOCR#7087]
- 系统环境/System Environment：高通750G芯片
- 版本号/Version：PaddleOCR：v2.5.0，PaddleLite：v2.11
- 问题相关组件/Related components：
    使用官方提供的检测和识别模型：https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar ； https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar
    并使用opt工具转换opencl推理模型：
        ./opt --model_file=./ch_PP-OCRv2_det_infer/inference.pdmodel  --param_file=./ch_PP-OCRv2_det_infer/inference.pdiparams  --optimize_out=./ch_PP-OCRv2_det_opencl_opt --valid_targets=opencl,arm  --optimize_out_type=naive_buffer
        ./opt --model_file=./ch_PP-OCRv2_rec_infer/inference.pdmodel  --param_file=./ch_PP-OCRv2_rec_infer/inference.pdiparams  --optimize_out=./ch_PP-OCRv2_rec_opencl_opt --valid_targets=opencl,arm  --optimize_out_type=naive_buffer

- 完整报错/Complete Error Message：
[I  8/ 3 10:37:34.715 ...loy/Paddle-Lite/lite/core/device_info.cc:1275 Setup] ARM multiprocessors name: HARDWARE	: QUALCOMM TECHNOLOGIES, INC LAGOON
_LITO_LITO_
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1276 Setup] ARM multiprocessors number: 8
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 0, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 1, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 2, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 3, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 4, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 5, max freq: 1804, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 6, max freq: 2208, min freq: 2208, cluster ID: 0, CPU ARCH: A77
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 7, max freq: 2208, min freq: 2208, cluster ID: 0, CPU ARCH: A77
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1284 Setup] L1 DataCache size is: 
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1288 Setup] L2 Cache size is: 
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1292 Setup] L3 Cache size is: 
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1296 Setup] Total memory: 5618532KB
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1297 Setup] SVE2 support: 0
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1298 Setup] SVE2 f32mm support: 0
[I  8/ 3 10:37:34.716 ...loy/Paddle-Lite/lite/core/device_info.cc:1299 Setup] SVE2 i8mm support: 0
ch_PP-OCRv2_det_opencl_opt.nb
[I  8/ 3 10:37:34.717 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.718 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.718 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.718 ...-Lite/lite/backends/opencl/cl_runtime.cc:69 Init] opencl_lib_found:1
[I  8/ 3 10:37:34.718 ...-Lite/lite/backends/opencl/cl_runtime.cc:77 Init] dlsym_success:1
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:537 InitializePlatform] Platform extension:  
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:85 Init] is_platform_init:1
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:623 InitializeDevice] Using device: QUALCOMM Adreno(TM)
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:649 InitializeDevice] CL_DEVICE_VERSION:OpenCL 2.0 Adreno(TM) 619
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:656 InitializeDevice] device_type:GPU
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:660 InitializeDevice] The chosen device has 1 compute units.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:664 InitializeDevice] CL_DEVICE_MAX_CLOCK_FREQUENCY:1
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:674 InitializeDevice] The local memory size of the chosen device is 32.000000 KB.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:681 InitializeDevice] CL_DEVICE_GLOBAL_MEM_CACHE_SIZE(KB):64.000000 KB.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:689 InitializeDevice] CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE(KB):0.062500 KB.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:696 InitializeDevice] CL_DEVICE_GLOBAL_MEM_SIZE(KB):2809266.000000 KB.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:704 InitializeDevice] CL_DEVICE_MAX_WORK_GROUP_SIZE:1024
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:708 InitializeDevice] CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:3
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:713 InitializeDevice] max_work_item_sizes[0]:1024
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:713 InitializeDevice] max_work_item_sizes[1]:1024
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:713 InitializeDevice] max_work_item_sizes[2]:1024
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:724 InitializeDevice] CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:64.000000
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:735 InitializeDevice] The chosen device supports image processing.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:739 InitializeDevice] CL_DEVICE_IMAGE2D_MAX_HEIGHT:16384
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:743 InitializeDevice] CL_DEVICE_IMAGE2D_MAX_WIDTH:16384
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:757 InitializeDevice] The chosen device supports the half data type.
[I  8/ 3 10:37:34.730 ...-Lite/lite/backends/opencl/cl_runtime.cc:765 InitializeDevice] CL_DEVICE_ADDRESS_BITS:64
[I  8/ 3 10:37:34.733 ...-Lite/lite/backends/opencl/cl_runtime.cc:769 InitializeDevice] CL_DRIVER_VERSION:OpenCL 2.0 QUALCOMM build: commit #a05eee6955 changeid #I893e5129fb Date: 12/15/20 Tue Local Branch:  Remote Branch:  Compiler E031.37.12.03
[I  8/ 3 10:37:34.733 ...-Lite/lite/backends/opencl/cl_runtime.cc:93 Init] is_device_init:1
[I  8/ 3 10:37:34.733 ...-Lite/lite/backends/opencl/cl_runtime.cc:809 GetAdrenoContextProperties] GPUPerfMode::PERF_HIGH
[I  8/ 3 10:37:34.733 ...-Lite/lite/backends/opencl/cl_runtime.cc:828 GetAdrenoContextProperties] GPUPriorityLevel::PRIORITY_HIGH
[I  8/ 3 10:37:34.735 ...-Lite/lite/backends/opencl/cl_runtime.cc:105 Init] set is_cl_runtime_initialized_ = true
[I  8/ 3 10:37:34.735 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
is_opencl_backend_valid:true
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.735 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:323 set_opencl_binary_path_name] opencl binary path and file name:/data/local/tmp//ch_PP-OCRv2_det_opencl_opt.nblite_opencl_kernel.bin
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.735 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.735 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.735 ...-Lite/lite/backends/opencl/cl_runtime.cc:863 set_auto_tune] tuned_file:/data/local/tmp//ch_PP-OCRv2_det_opencl_opt.nblite_opencl_tuned.bin
[W  8/ 3 10:37:34.736 ...-Lite/lite/backends/opencl/cl_runtime.cc:872 set_auto_tune] Not found tuned file:/data/local/tmp//ch_PP-OCRv2_det_opencl_opt.nblite_opencl_tuned.bin
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:341 set_opencl_tune] set opencl_tune_mode: CL_TUNE_NORMAL, lws_repeats:4
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:344 set_opencl_tune] tuned file path & name:/data/local/tmp//ch_PP-OCRv2_det_opencl_opt.nblite_opencl_tuned.bin
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.736 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.736 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:356 set_opencl_precision] set opencl precision: CL_PRECISION_FP32
*** nb model will be running on opencl. ***
[I  8/ 3 10:37:34.740 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
ch_PP-OCRv2_rec_opencl_opt.nb
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.740 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
is_opencl_backend_valid:true
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.740 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.741 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:323 set_opencl_binary_path_name] opencl binary path and file name:/data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_kernel.bin
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.741 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.741 ...-Lite/lite/backends/opencl/cl_runtime.cc:863 set_auto_tune] tuned_file:/data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_tuned.bin
[I  8/ 3 10:37:34.741 ...-Lite/lite/backends/opencl/cl_runtime.cc:865 set_auto_tune] Load tuned file: /data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_tuned.bin
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:341 set_opencl_tune] set opencl_tune_mode: CL_TUNE_NORMAL, lws_repeats:4
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:344 set_opencl_tune] tuned file path & name:/data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_tuned.bin
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:50 IsOpenCLBackendValid] need to check fp16 valid:0
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:57 IsOpenCLBackendValid] Found opencl library:1
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:63 IsOpenCLBackendValid] dlsym_success:1
[I  8/ 3 10:37:34.741 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:70 IsOpenCLBackendValid] opencl_valid:1
[I  8/ 3 10:37:34.741 ...eploy/Paddle-Lite/lite/api/paddle_api.cc:356 set_opencl_precision] set opencl precision: CL_PRECISION_FP32
*** nb model will be running on opencl. ***
[I  8/ 3 10:37:34.750 ...e-Lite/lite/backends/opencl/cl_runtime.h:93 OpenCLAvaliableForDevice] need to check fp16 valid:0
[I  8/ 3 10:37:34.760 ...-Lite/lite/backends/opencl/cl_runtime.cc:227 CheckFromPrecompiledBinary] Load opencl kernel bin file: /data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_kernel.bin
[W  8/ 3 10:37:34.760 ...-Lite/lite/backends/opencl/cl_runtime.cc:246 CheckFromPrecompiledBinary] The precompiled OpenCL binary[/data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_kernel.bin] is illegal!
[I  8/ 3 10:37:34.760 ...-Lite/lite/backends/opencl/cl_runtime.cc:198 operator()] Invalid precomplied OpenCL binary[/data/local/tmp//ch_PP-OCRv2_rec_opencl_opt.nblite_opencl_kernel.bin] has been deleted!
[I  8/ 3 10:38:52.898 ...s/opencl/conv_transpose_image_compute.cc:304 SetGlobalWorkSize] global_work_size_: 6 224 224
[I  8/ 3 10:38:52.898 ...s/opencl/conv_transpose_image_compute.cc:313 SetArgs] pad_w, pad_h: 1 1
[I  8/ 3 10:38:52.898 ...s/opencl/conv_transpose_image_compute.cc:314 SetArgs] align_w, align_h: 0 0
[I  8/ 3 10:38:53. 41 ...s/opencl/conv_transpose_image_compute.cc:304 SetGlobalWorkSize] global_work_size_: 1 448 448
[I  8/ 3 10:38:53. 41 ...s/opencl/conv_transpose_image_compute.cc:313 SetArgs] pad_w, pad_h: 1 1
[I  8/ 3 10:38:53. 41 ...s/opencl/conv_transpose_image_compute.cc:314 SetArgs] align_w, align_h: 0 0
malloc image is out of max image size(w,h):16384,16384, need image size(w,h):18560,16
[F  8/ 3 10:38:58.832 ...e/lite/backends/opencl/target_wrapper.cc:98 ImageValid] malloc image is out of max image size(w,h):16384,16384, need image size(w,h):18560,16
Aborted

**Comment by limaopeng1** [comment]
定位到问题了，主要是识别模型输入图片尺寸的问题，我把w限制在250就不会有malloc image is out of max image size(w,h):16384,16384的问题了，但是这样的话应该会对识别准确率有影响。

猜测应该是crnn中的一些reshape之类的操作导致出现 need image size(w,h):18560,16 这种维度，有人能帮忙定位下吗

cv::Mat CrnnResizeImg(cv::Mat img, float wh_ratio) {
  int imgC, imgH, imgW;
  imgC = rec_image_shape[0];
  imgW = rec_image_shape[2];
  imgH = rec_image_shape[1];

  imgW = int(32 * wh_ratio);

  float ratio = static_cast<float>(img.cols) / static_cast<float>(img.rows);
  int resize_w, resize_h;
  // if (ceilf(imgH * ratio) > imgW)
  //   resize_w = imgW;
  // else
  //   resize_w = static_cast<int>(ceilf(imgH * ratio));
  if (imgW > 250)
    resize_w = 250;
  else
    resize_w = imgW;
  cv::Mat resize_img;
  cv::resize(
      img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f, cv::INTER_LINEAR);

  return resize_img;
}

**Comment by Zhang-O** [comment]
niubility !!!!!!!!!!!!!!!!!!!!!!!

**Comment by yangy996** [comment]
大佬使用opencl部署成功了吗？

**Comment by JH-Lam** [comment]
调整后发现opencl不报错，但在rec识别阶段没有任何输出。我干脆改为arm模式后才正常，但此时就未利用gpu了 @limaopeng1

**Comment by JH-Lam** [comment]
调整后发现opencl不报错，但在rec识别阶段没有任何输出。我干脆改为arm模式后才正常，但此时就未利用gpu了 @limaopeng1
yolov5也会报同样的错，但需要重新训练并更改imgsz才可以在opencl运行
