### ISSUE TITLE
【请教】检测和识别面板上的数字效果很差。

### ISSUE THREAD

**Issue by alex152738** [PaddlePaddle/PaddleOCR#709]
使用轻量化模型和通用模型识别数字面板的数字效果很不好，例如：
![3](https://user-images.githubusercontent.com/47980839/93037874-0a716980-f676-11ea-82f3-6dcf66cc4d69.jpg)
请问有什么办法可以达到很好的识别效果吗？重训练的话，分成两步吗，数据量有什么要求吗？谢谢~

**Comment by LDOUBLEV** [comment]
先前的训练的数据中此类数据很少，所以检测和识别效果差了一些，建议重训练；
如果你的数据都是这样格式的，训练检测（基于我们的模型fine-tune），轻量模型几百张应该够了，越多越好；
识别数据可以多找一些。
PS：
另外，你在预测时将unclip_ratio改小一点试试，这个值越小，文本框越紧致

**Comment by alex152738** [comment]
好的，感谢回复指导！！

**Comment by alex152738** [comment]
> 先前的训练的数据中此类数据很少，所以检测和识别效果差了一些，建议重训练；
> 如果你的数据都是这样格式的，训练检测（基于我们的模型fine-tune），轻量模型几百张应该够了，越多越好；
> 识别数据可以多找一些。
> PS：
> 另外，你在预测时将unclip_ratio改小一点试试，这个值越小，文本框越紧致
好的，感谢回复指导！！
