### ISSUE TITLE
PaddleOCR v2.2 导出的onnx模型c++推理与python推理结果差距

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/PaddleOCR#7094]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10
- 版本号PaddleOCR：v2.2 
- 问题相关组件/Related components：dbnet

将训练的DBNET检测模型利用脚本导出后，使用paddleocr 自带的python推理，结果与paddle模型一致，但是利用c++推理onnxruntime模型时候，推理的结果完全不一样，这里只对比了推理后的数据，后处理不涉及

做过的尝试：
1. 控制输入的图片大小一致，以及一致的均值与方差

**Comment by dengmingD** [comment]
我也遇到这个问题了，你解决了吗？

**Comment by yjmm10** [comment]
> 我也遇到这个问题了，你解决了吗？

检查一下训练跟推理 图片的通道顺序
