### ISSUE TITLE
文本检测完的图片怎么进行文本识别啊？

### ISSUE THREAD

**Issue by Lingyun0109** [PaddlePaddle/PaddleOCR#7095]
是要把边界框框出的图片剪裁下来，送进识别模型吗？关于这个的代码在哪里啊

**Comment by LDOUBLEV** [comment]
代码在：https://github.com/PaddlePaddle/PaddleOCR/blob/d583ff3fa9cdcaeaacdd87a793f7957a268a8982/tools/infer/predict_system.py#L71-L92
