### ISSUE TITLE
The yml name doesn't match the model's

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7098]
https://github.com/PaddlePaddle/PaddleOCR/blob/9f05636ecdc244eed79c9d2b453ce11038bd012d/doc/doc_en/algorithm_rec_srn_en.md?plain=1#L26-L28

https://github.com/PaddlePaddle/PaddleOCR/blob/9f05636ecdc244eed79c9d2b453ce11038bd012d/doc/doc_ch/algorithm_rec_srn.md?plain=1#L26-L28

The yml file is `rec_r50_fpn_srn.yml`, which is inconsistent with `rec_r50_vd_srn_train.tar`.

**Comment by thsno02** [comment]
Meanwhile, the model files downloaded from

```
'https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/rec_svtr_tiny_none_ctc_en_train.tar',
'https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/rec_svtr_tiny_none_ctc_ch_train.tar'
```

don't share the same name format as the yml files.

```
├── rec_svtr_tiny_none_ctc_ch_train
│   ├── best_accuracy.pdparams
│   └── rec_svtr_tiny_6local_6global_stn_ch.yml
├── rec_svtr_tiny_none_ctc_ch_train.tar
├── rec_svtr_tiny_none_ctc_en_train
│   ├── best_accuracy.pdparams
│   └── rec_svtr_tiny_6local_6global_stn_en.yml
└── rec_svtr_tiny_none_ctc_en_train.tar
```

**Comment by andyjpaddle** [comment]
The model tar name doesn't matter, just ensure the pre-trained model provided can be load successfully.

**Comment by thsno02** [comment]
I know this, if someone like me wanna evaluate the models in a batch, the inconsistent name pair is annoying.

**Comment by andyjpaddle** [comment]
Thanks for the feedback, we will fix it later
