### ISSUE TITLE
FP16推理加速不明显

### ISSUE THREAD

**Issue by eshoyuan** [PaddlePaddle/PaddleOCR#7100]
我用C++ TensorRT部署了PPOCR的识别部分.
开启FP16前后速度对比 (只计算了网络部分, 未计算后处理)

v3: 1.7ms -> 1.4ms
v2: 3.4ms -> 3.2ms

效果不是很明显.
https://github.com/PaddlePaddle/PaddleOCR/issues/6641, 这里提到混合精度对于轻量模型训练加速效果一般, 对于推理也是如此吗? 具体原因是什么呢?

**Comment by andyjpaddle** [comment]
是的，目前OCR识别模型对于fp16的加速效果一般，具体原因是框架对于部分模型算子的加速支持还不太完备。

**Comment by eshoyuan** [comment]
谢谢!
