### ISSUE TITLE
关于SVTR模型的长文本推理精度问题

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#7104]
将模型转为ONNX后默认图像输入为64*256，对于长文本的识别效果较差。自适应输出的Head参数为MultiHead，请问该如何修改训练参数，使得模型能较好的识别较长的文本图片。

**Comment by andyjpaddle** [comment]
具体使用的是哪个模型呢？

**Comment by xu-peng-7** [comment]
backbone为svtr的文字识别模型。对照论文修改参数：
参数为
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 100]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [32, 100]
    out_char_num: 25
    out_channels: 384
    patch_merging: 'Conv'
    embed_dim: [192, 256, 512]
    depth: [3, 9, 9]
    num_heads: [6, 8, 16]
    mixer: ['Local','Local','Local','Local','Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: ClsMetric
  main_indicator: acc

**Comment by andyjpaddle** [comment]
这个模型并没有用到MultiHead，确保模型是否使用正确

**Comment by xu-peng-7** [comment]
我用的训练模型没有用multihead，这样在tool/export_model里面转为onnx的时候，默认是固定的（3*64*256），这样在使用时将较长的文本图像resize后效果非常差，即使将这里的shape中的宽度改成自适应，长文本的识别效果也很差。但是这里的multihead默认是自适应的宽度，但是没有multihead的相关训练代码。

所以我想问下：
1：svtr默认参数对长文本的识别效果不好吗？
2：是否更换为multihead效果会好？
3：导出onnx的shape是根据什么来决定的


代码如下：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/tools/export_model.py 第58行
-----------------------------------------------------------------------------------------------------
    elif arch_config["algorithm"] == "SVTR":
        if arch_config["Head"]["name"] == 'MultiHead':
            other_shape = [
                paddle.static.InputSpec(
                    shape=[None, 3, 48, -1], dtype="float32"),
            ]
        else:
            other_shape = [
                paddle.static.InputSpec(
                    shape=[None, 3, 64, 256], dtype="float32"),
            ]
        model = to_static(model, input_spec=other_shape)

**Comment by andyjpaddle** [comment]
1. 可以先使用python推理试试，不转onnx
2. multihead是PP-OCRv3的识别模型用的head，不是原本的SVTR
3. 导出shape可以设置，参考 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5/deploy/paddle2onnx#2-%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2，不过SVTR目前不支持变长

**Comment by andyjpaddle** [comment]
长文本最多25字符，如果超过这个长度效果就会不好了

**Comment by xu-peng-7** [comment]
我有修改训练的文本最大长度参数超过25，在使用crnn+resent50训练文字识别时能获得一个较好的效果，但是同样的配置在svtr上训练完成时，转为onnx推理阶段对长文本的效果不好。但训练中的指标svtr会略好于crnn+resnet50.

**Comment by Topdu** [comment]
建议统计宽高比，[3, 32, 100]适应**宽高**比多数为4:1且单个样本字符数不超过20的数据集；
tps_inputsize:是输入到tps网络的size，建议随着[3, 32, 100]的改变而改变；
img_size是输入到SVTRNet中的size，同样需要随着[3, 32, 100]的改变而改变。

例如：
数据集中存在很多宽高比为10:1样本，则可以将[3, 32, 100]修改为[3, 32, 200]或者[3, 32, 320]，也可以参考[SVTR中文配置](https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/rec_svtr_tiny_none_ctc_ch_train.tar) 。

如果有变长输入的需求，建议使用根据基于改进的[PP-OCRv3](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/ppocr_introduction.md#52) .

**Comment by xu-peng-7** [comment]
非常感谢您的回复，我已经使用了OCRv3中的SVTR相关训练配置训练自己的数据。
1：但是**转为onnx**时，shape=[None, 3, 64, 256]有什么依据吗？能否将宽度定义为边长
2：有尝试过使用multihead加入sarhead后代码报错，svtr是否有multihead的训练代码配置？

**Comment by Topdu** [comment]
> 1：但是**转为onnx**时，shape=[None, 3, 64, 256]有什么依据吗？能否将宽度定义为边长

SVTR使用了绝对位置编码，因此是不支持的变长的，如果想要使用SVTR作为backbone建议统计宽高比。




> 2：有尝试过使用multihead加入sarhead后代码报错，svtr是否有multihead的训练代码配置？

PP-OCRv3支持变长的原因并不是使用了multihead，而是使用了LCNet+svtr_neck作为backbone。

**Comment by xu-peng-7** [comment]
明白了，感谢您的回答

**Comment by xu-peng-7** [comment]
您好，PP-OCRv3训练代码中不支持 svtr作为Neck

  Neck:
    name: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: True

assert module_name in support_dict, Exception('neck only support {}'.format(
AssertionError: neck only support ['FPN', 'FCEFPN', 'LKPAN', 'DBFPN', 'RSEFPN', 'EASTFPN', 'SASTFPN', 'SequenceEncoder', 'PGFPN', 'TableFPN', 'PRENFPN']

**Comment by Topdu** [comment]
```
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: True
```

**Comment by xu-peng-7** [comment]
使用该参数训练后，loss下降很缓慢，效果不如使用rnn是什么原因？要调整某个参数吗

**Comment by Topdu** [comment]
建议查看源码，确定每个参数的作用，尤其是use_guide参数，当单独使用svtr neck时use_guide应设置为false，使用mutli head时设置为true

**Comment by xu-peng-7** [comment]
您好，PPOCRv3的LCNet+svtr_neck作为backbone没有提供训练的配置文件和model吗？我有注意到给的配置文件里是mobileV1

**Comment by Topdu** [comment]
> 您好，PPOCRv3的LCNet+svtr_neck作为backbone没有提供训练的配置文件和model吗？我有注意到给的配置文件里是mobileV1

MobileNetV1Enhance即为LCNet

**Comment by xu-peng-7** [comment]
收到，非常感谢。

**Comment by vance-coder** [comment]
\
> tps_inputsize:是输入到tps网络的size，建议随着[3, 32, 100]的改变而改变；
> img_size是输入到SVTRNet中的size，同样需要随着[3, 32, 100]的改变而改变。

这个意思是，让tps_inputsize 和 tps_outputsize 以及 img_size 保持一样吗？比如三个都是 [3, 32, 320]

**Comment by vance-coder** [comment]
> \
> 
> > tps_inputsize:是输入到tps网络的size，建议随着[3, 32, 100]的改变而改变；
> > img_size是输入到SVTRNet中的size，同样需要随着[3, 32, 100]的改变而改变。
> 
> 这个意思是，让tps_inputsize 和 tps_outputsize 以及 img_size 保持一样吗？比如三个都是 [3, 32, 320]

@Topdu
