### ISSUE TITLE
SVTR的backbone代码问题

### ISSUE THREAD

**Issue by willpat1213** [PaddlePaddle/PaddleOCR#7105]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

svtr的backbone，`rec_svtrnet.py` 139行
`x = x.transpose([0, 2, 1]).reshape([0, self.dim, h, w])`
请问这里reshape的第一位是不是应该是`N`（即1）而不是`0`呢？或者是我的理解有什么偏差，请指出，因为我这边报错
`RuntimeError: shape '[0, 768, 8, 25]' is invalid for input of size 153600`
改成`1`的话就没问题了

**Comment by andyjpaddle** [comment]
第一位是batchsize的维度，0或-1都可以，如果报错可以改成-1试试

**Comment by willpat1213** [comment]
谢谢，明白了，是第一个维度自适应的问题，pytorch不支持0
