### ISSUE TITLE
How to understand the argument.

### ISSUE THREAD

**Issue by IsraelAbebe** [PaddlePaddle/PaddleOCR#7107]
I am experimenting with paddleocr and I couldn't find the manual that describes the arguments. I am trying to see If i can output the text output only where I turn off the location and confidence.

can you help.

**Comment by andyjpaddle** [comment]
1. You can refer this doc for parameter-description https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/whl_en.md#5-parameter-description
2. If you want to turnoff the location and confidence, you can change the code here.
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/paddleocr.py#L479-L495  just change the return code. Then you should remake the whl package and pip install the new package according this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/whl_en.md#1-get-started-quickly

**Comment by IsraelAbebe** [comment]
Thanks
