### ISSUE TITLE
opt转换工具问题

### ISSUE THREAD

**Issue by boceng** [PaddlePaddle/PaddleOCR#711]
在arm linux下通过安装 build_linux.sh编译得到的paddlite包，其附带一个paddle_lite_opt工具，但使用这个工具转换训练的DB模型，会报错，如下：
Can not find the input argument for var conv2_b_attr

发现[issue 534](https://github.com/PaddlePaddle/PaddleOCR/issues/534)  有提示说使用develop分支进行编译opt工具就可以了[传送门](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/readme.md#21-%E6%A8%A1%E5%9E%8B%E4%BC%98%E5%8C%96)

但编译时又遇到了新问题，如下：
recipe for target 'opt' failed 
详情类似[issue 515](https://github.com/PaddlePaddle/PaddleOCR/issues/515)，但交叉编译环境事实上已经准备好了，请问有措施可以解决吗？

**Comment by LDOUBLEV** [comment]
可以发一下完整的报错信息吗

**Comment by boceng** [comment]
使用附带的paddle_lite_opt时报错：
`
ss because the target or kernel does not match.
[I  9/14  5:42: 2.938 ...e-Lite/paddle-lite/lite/core/optimizer.h:229 RunPasses] == Running pass: static_kernel_pick_pass
[I  9/14  5:42: 2.991 ...e-Lite/paddle-lite/lite/core/optimizer.h:253 RunPasses] == Finished running: static_kernel_pick_pass
[I  9/14  5:42: 2.991 ...e-Lite/paddle-lite/lite/core/optimizer.h:229 RunPasses] == Running pass: remove_tf_redundant_ops_pass
[I  9/14  5:42: 3. 33 ...e-Lite/paddle-lite/lite/core/optimizer.h:253 RunPasses] == Finished running: remove_tf_redundant_ops_pass
[I  9/14  5:42: 3. 33 ...e-Lite/paddle-lite/lite/core/optimizer.h:229 RunPasses] == Running pass: variable_place_inference_pass
[F  9/14  5:42: 3. 49 ...core/mir/variable_place_inference_pass.h:138 InferenceArgumentPlace] Check failed: op_info->GetInputArgname(var_name, &arg_name): Can not find the input argument for var conv2_b_attr
Aborted
`

重新编译develop分支下（其他分支也报错）的错误：
`
-- Up-to-date: /home/HwHiAiUser/Paddle-Lite/paddle-lite1/build.opt/third_party/install/protobuf/lib/cmake/protobuf
-- Installing: /home/HwHiAiUser/Paddle-Lite/paddle-lite1/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-module.cmake
-- Installing: /home/HwHiAiUser/Paddle-Lite/paddle-lite1/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-options.cmake
-- Installing: /home/HwHiAiUser/Paddle-Lite/paddle-lite1/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config.cmake
-- Installing: /home/HwHiAiUser/Paddle-Lite/paddle-lite1/build.opt/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config-version.cmake
[  9%] Completed 'extern_protobuf'
[  9%] Built target extern_protobuf
CMakeFiles/Makefile2:18761: recipe for target 'lite/api/CMakeFiles/opt.dir/rule' failed
make[1]: *** [lite/api/CMakeFiles/opt.dir/rule] Error 2
Makefile:3069: recipe for target 'opt' failed
make: *** [opt] Error 2
`

**Comment by boceng** [comment]
我用附带的paddle_lite_opt转过检测模型，可正确使用，这里也可以成功转换crnn模型。

**Comment by LDOUBLEV** [comment]
你的cmake 版本是多少

**Comment by boceng** [comment]
> 你的cmake 版本是多少，是编译的时候报错的，可以看下CmakeError 日志

您好，我的cmake是3.10.3，日志为：
[ 97%] Building CXX object CMakeFiles/libprotoc.dir/home/HwHiAiUser/Paddle-Lite/paddle-lite1/third-party/protobuf-host/src/google/protobuf/compiler/ruby/ruby_generator.cc.o
[ 97%] Building CXX object CMakeFiles/libprotoc.dir/home/HwHiAiUser/Paddle-Lite/paddle-lite1/third-party/protobuf-host/src/google/protobuf/compiler/subprocess.cc.o
[ 98%] Building CXX object CMakeFiles/libprotoc.dir/home/HwHiAiUser/Paddle-Lite/paddle-lite1/third-party/protobuf-host/src/google/protobuf/compiler/zip_writer.cc.o
[ 98%] Linking CXX static library libprotoc.a
[ 98%] Built target libprotoc
Scanning dependencies of target protoc
[ 99%] Building CXX object CMakeFiles/protoc.dir/home/HwHiAiUser/Paddle-Lite/paddle-lite1/third-party/protobuf-host/src/google/protobuf/compiler/main.cc.o
[100%] Linking CXX executable protoc
[100%] Built target protoc
[  6%] Performing install step for 'extern_protobuf'
[ 12%] Built target libprotobuf-lite
[ 51%] Built target libprotobuf
[ 98%] Built target libprotoc
[100%] Built target protoc
[  6%] Completed 'extern_protobuf'
[  6%] Built target extern_protobuf
CMakeFiles/Makefile2:23409: recipe for target 'lite/api/CMakeFiles/opt.dir/rule' failed
make[1]: *** [lite/api/CMakeFiles/opt.dir/rule] Error 2
Makefile:3563: recipe for target 'opt' failed
make: *** [opt] Error 2

**Comment by LDOUBLEV** [comment]
可能还是编译环境问题，你把paddle-lite更新到最新develop分支，然后按照下面这个文档的内容，check下编译环境：https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_env.html
我刚在本地MAC上试了一下，可以正常编译
编译opt的时候，在Paddle-Lite目录下执行 ./lite/tools/build.sh build_optimize_tool

**Comment by boceng** [comment]
您好 我现在准备编译环境，log如下：

	# apt-get install -y --no-install-recommends gcc g++ git make wget python unzip
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	g++ is already the newest version (4:5.3.1-1ubuntu1).
	gcc is already the newest version (4:5.3.1-1ubuntu1).
	make is already the newest version (4.1-6).
	unzip is already the newest version (6.0-20ubuntu1).
	git is already the newest version (1:2.7.4-0ubuntu1.9).
	wget is already the newest version (1.17.1-1ubuntu1.5).
	python is already the newest version (2.7.12-1~16.04).
	0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.


	# apt-get install -y --no-install-recommends \
	>   g++-arm-linux-gnueabi gcc-arm-linux-gnueabi \
	>   g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf \
	>   gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	Package gcc-aarch64-linux-gnu is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source

	Package g++-aarch64-linux-gnu is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source

	E: Package 'gcc-aarch64-linux-gnu' has no installation candidate
	E: Package 'g++-aarch64-linux-gnu' has no installation candidate


	# aarch64-linux-gnu-gcc -v
	Using built-in specs.
	COLLECT_GCC=aarch64-linux-gnu-gcc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
	Target: aarch64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
	Thread model: posix
	gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12)


	aarch64-linux-gnu-g++ -v
	Using built-in specs.
	COLLECT_GCC=aarch64-linux-gnu-g++
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
	Target: aarch64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
	Thread model: posix
	gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12)


	# which aarch64-linux-gnu-gcc
	/usr/bin/aarch64-linux-gnu-gcc
	# which aarch64-linux-gnu-g++
	/usr/bin/aarch64-linux-gnu-g++


如上，提醒我gcc-aarch64-linux-gnu has no installation candidate，但是我检测其版本表面已安装，您先帮我看一下会是这里的问题吗，我现在正在重新编译opt。

**Comment by boceng** [comment]
对了，由于国内git github非常慢，我现在是git到最新的gitee的paddlelite，请问这会影响嘛

**Comment by LDOUBLEV** [comment]
> 您好，我试了一下还是不行；
> 对了，由于国内git github非常慢，我现在是git到最新的gitee的paddlelite，请问这会影响嘛？

gcc卸载重新装试一下呢

**Comment by boceng** [comment]
> > 您好，我试了一下还是不行；
> > 对了，由于国内git github非常慢，我现在是git到最新的gitee的paddlelite，请问这会影响嘛？
> 
> gcc卸载重新装试一下呢

我已经卸载了，但是重新安装仍然提示

	E: Package 'gcc-aarch64-linux-gnu' has no installation candidate
	E: Package 'g++-aarch64-linux-gnu' has no installation candidate

我的系统版本为：CST 2020 aarch64 aarch64 aarch64 GNU/Linux，是不是该系统没有gcc-aarch64-linux-gnu工具链，我尝试了网上的多种方法皆未解决。[issue 4344](https://github.com/PaddlePaddle/Paddle-Lite/issues/4344)

**Comment by LDOUBLEV** [comment]
> issue 4344

建议在docker里进行吧，docker中环境没问题，参考：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85
```
如果您希望在CPU环境下使用docker，使用docker而不是nvidia-docker创建docker
sudo docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash

如果使用CUDA9，请运行以下命令创建容器
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash

如果使用CUDA10，请运行以下命令创建容器
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev /bin/bash

您也可以访问[DockerHub](https://hub.docker.com/r/paddlepaddle/paddle/tags/)获取与您机器适配的镜像。
```
