### ISSUE TITLE
Does paddle OCR have column identifying feature 

### ISSUE THREAD

**Issue by IsraelAbebe** [PaddlePaddle/PaddleOCR#7117]
I am testing paddle OCR and wanted to know if it has a column identifying feature instead of treating columns line by line and joining them.

@tink2123 is there already implemented solution for this or should I try to figure out my own?

**Comment by tink2123** [comment]
PPOCR supports column recognition, which mainly depends on the results of detection boxes. Indeed, the training data is mostly row-major data, so if the distance between columns is too short, row-wise detection may be preferred.

For example, the following pictures can be better recognized. 
![image](https://user-images.githubusercontent.com/31891223/186852381-ade6c962-b90e-49f7-a3d8-f3bd5c11762b.png)


If the effect is not good in your scene, it is recommended to use your own data and [finetune](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/detection_en.md) the detection model.

**Comment by IsraelAbebe** [comment]
Thank You i am working on that.
