### ISSUE TITLE
PPOCR v3的识别模型， 在cpu和xpu下的推理结果不一致

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#7119]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos7.9， python3.7,  R200
- 版本号/Version：Paddle：PaddlePaddle-xpu2.3.0rc0   PaddleOCR：release/2.5     问题相关组件/Related components：
- 运行指令/Command Code：\

python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_4.jpg" --rec_model_dir="./inference/ch_PP-OCRv3_rec_infer/" --use_xpu=True

- 完整报错/Complete Error Message：
[2022/08/05 17:52:03] ppocr INFO: Predicts of ./doc/imgs_words/ch/word_4.jpg:('', 0.0)

CPU运行结果： 
[2022/08/05 17:52:45] ppocr INFO: Predicts of ./doc/imgs_words/ch/word_4.jpg:('实力活力', 0.9956860542297363)

**Comment by tink2123** [comment]
我们测试xpu可以的，您可以安装最新版本xpu再尝试一下。

**Comment by Intsigstephon** [comment]
是用paddle最新develop分支， 在centos下编译的包测的吗？

**Comment by Intsigstephon** [comment]
OK.  复测之后发现结果一致了，谢谢。
