### ISSUE TITLE
Inferencing 2.3 trained Model using the 2.5 release

### ISSUE THREAD

**Issue by mohamadmansourX** [PaddlePaddle/PaddleOCR#7121]
2.3 Release Trained Model - 2.5 Release Code results mismatch.
After training my recognition model using the 2.3 release and testing it successfully, when trying to use the same weights on the new 2.5 release the results gets disrupted; having some comparable results on some cases while very bad ones on others.
Was I supposed to do something with my weights before migrating to the latest release?

**Comment by tink2123** [comment]
The same configuration file, 2.5 can use the weight of 2.3. May I ask what model did you use, and what do the different results mean?
