### ISSUE TITLE
请教一下，paddle  --use_onnx=True  怎么指定语种?

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7123]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  2.5 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请教一下，paddle  --use_onnx=True  怎么指定语种?

 predict_system.py [-h] [--use_gpu USE_GPU] [--use_xpu USE_XPU] [--ir_optim IR_OPTIM]
                         [--use_tensorrt USE_TENSORRT] [--min_subgraph_size MIN_SUBGRAPH_SIZE] [--precision PRECISION]
                         [--gpu_mem GPU_MEM] [--image_dir IMAGE_DIR] [--det_algorithm DET_ALGORITHM]
                         [--det_model_dir DET_MODEL_DIR] [--det_limit_side_len DET_LIMIT_SIDE_LEN]
                         [--det_limit_type DET_LIMIT_TYPE] [--det_db_thresh DET_DB_THRESH]
                         [--det_db_box_thresh DET_DB_BOX_THRESH] [--det_db_unclip_ratio DET_DB_UNCLIP_RATIO]
                         [--max_batch_size MAX_BATCH_SIZE] [--use_dilation USE_DILATION]
                         [--det_db_score_mode DET_DB_SCORE_MODE] [--det_east_score_thresh DET_EAST_SCORE_THRESH]
                         [--det_east_cover_thresh DET_EAST_COVER_THRESH] [--det_east_nms_thresh DET_EAST_NMS_THRESH]
                         [--det_sast_score_thresh DET_SAST_SCORE_THRESH] [--det_sast_nms_thresh DET_SAST_NMS_THRESH]
                         [--det_sast_polygon DET_SAST_POLYGON] [--det_pse_thresh DET_PSE_THRESH]
                         [--det_pse_box_thresh DET_PSE_BOX_THRESH] [--det_pse_min_area DET_PSE_MIN_AREA]
                         [--det_pse_box_type DET_PSE_BOX_TYPE] [--det_pse_scale DET_PSE_SCALE] [--scales SCALES]
                         [--alpha ALPHA] [--beta BETA] [--fourier_degree FOURIER_DEGREE]
                         [--det_fce_box_type DET_FCE_BOX_TYPE] [--rec_algorithm REC_ALGORITHM]
                         [--rec_model_dir REC_MODEL_DIR] [--rec_image_shape REC_IMAGE_SHAPE]
                         [--rec_batch_num REC_BATCH_NUM] [--max_text_length MAX_TEXT_LENGTH]
                         [--rec_char_dict_path REC_CHAR_DICT_PATH] [--use_space_char USE_SPACE_CHAR]
                         [--vis_font_path VIS_FONT_PATH] [--drop_score DROP_SCORE] [--e2e_algorithm E2E_ALGORITHM]
                         [--e2e_model_dir E2E_MODEL_DIR] [--e2e_limit_side_len E2E_LIMIT_SIDE_LEN]
                         [--e2e_limit_type E2E_LIMIT_TYPE] [--e2e_pgnet_score_thresh E2E_PGNET_SCORE_THRESH]
                         [--e2e_char_dict_path E2E_CHAR_DICT_PATH] [--e2e_pgnet_valid_set E2E_PGNET_VALID_SET]
                         [--e2e_pgnet_mode E2E_PGNET_MODE] [--use_angle_cls USE_ANGLE_CLS]
                         [--cls_model_dir CLS_MODEL_DIR] [--cls_image_shape CLS_IMAGE_SHAPE] [--label_list LABEL_LIST]
                         [--cls_batch_num CLS_BATCH_NUM] [--cls_thresh CLS_THRESH] [--enable_mkldnn ENABLE_MKLDNN]
                         [--cpu_threads CPU_THREADS] [--use_pdserving USE_PDSERVING] [--warmup WARMUP]
                         [--draw_img_save_dir DRAW_IMG_SAVE_DIR] [--save_crop_res SAVE_CROP_RES]
                         [--crop_res_save_dir CROP_RES_SAVE_DIR] [--use_mp USE_MP]
                         [--total_process_num TOTAL_PROCESS_NUM] [--process_id PROCESS_ID] [--benchmark BENCHMARK]
                         [--save_log_path SAVE_LOG_PATH] [--show_log SHOW_LOG] [--use_onnx USE_ONNX]
predict_system.py: error: unrecognized arguments: --lang= jpn

**Comment by WenmuZhou** [comment]
predict_system.py目前没法指定语种，可以使用whl包，或者手动下载模型到本地后指定模型路径
