### ISSUE TITLE
请问老师，方向分类器用的什么网络算法？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7125]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by XmySz** [comment]
MobileNetV3_small_x0.35

**Comment by aixuedegege** [comment]
请问这个模型用paddle怎么加载？我找的几个# from ppocr.modeling.backbones.rec_mobilenet_v3 import MobileNetV3
from paddle.vision.models import MobileNetV3Large 模型都加载不了官网下载的模型，都报参数找不到
