### ISSUE TITLE
svtr在那个阶段

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#7126]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：无
- 版本号/Version：Paddle：无  PaddleOCR： 问题相关组件/Related components：无
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：无

问下你们的svtr在那个阶段？
![image](https://user-images.githubusercontent.com/76056473/183244682-9bae1730-e245-41b8-ab01-47458ff751d7.png)
backbone是mobilenetv1enhance， 而svtr代码也在backbone下，却没用到

**Comment by WenmuZhou** [comment]
在ctchead的neck中
