### ISSUE TITLE
SVTR中的Position Embedding的疑惑

### ISSUE THREAD

**Issue by willpat1213** [PaddlePaddle/PaddleOCR#7128]
在源码中的position embedding是通过如下代码实现的（429~431行）：
```
        self.pos_embed = self.create_parameter(
            shape=[1, num_patches, embed_dim[0]], default_initializer=zeros_)
        self.add_parameter("pos_embed", self.pos_embed)
```
不是特别懂这么做为什么是pe，跟常规的pe的实现有什么区别吗？同时对应到pytorch中应该是怎么样的呢？

**Comment by Topdu** [comment]
> 不是特别懂这么做为什么是pe，跟常规的pe的实现有什么区别吗？

这段代码实现了[ViT论文](https://arxiv.org/abs/2010.11929)中所提出的绝对位置编码。



> 同时对应到pytorch中应该是怎么样的呢？

[vit in timm](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py#L373)

**Comment by willpat1213** [comment]
已经解决了，谢谢你的解答！
