### ISSUE TITLE
visual studio 2017编译错误

### ISSUE THREAD

**Issue by kevinsui581** [PaddlePaddle/PaddleOCR#7129]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： PaddleOCR
-
visual studio 2017编译链接时报错：（按x64编译，release模式,  运行库设为MT）

错误	LNK2019	无法解析的外部符号 __std_reverse_trivially_swappable_1，该符号在函数 "void __cdecl google::`anonymous namespace'::DumpStackFrameInfo(char const *,void *)" (?DumpStackFrameInfo@?A0x981e1e74@google@@YAXPEBDPEAX@Z) 中被引用	ppocr	D:\Library\PaddleOCR\deploy\cpp_infer\build\glog.lib(signalhandler.obj)	1

**Comment by Gmgge** [comment]
使用的是paddlepaddle什么版本呢？我这边最近编译了一次，使用链接指向的2.3也会报类似的错误，更换为2.2.2就没再出现。

**Comment by kevinsui581** [comment]
是最新版本的paddleocr！

**Comment by littletomatodonkey** [comment]
建议使用release_with_debug模式进行编译

**Comment by kevinsui581** [comment]
下载了VS2019社区版，编译就没有问题了；可能glog.lib这个库跟2017不兼容
