### ISSUE TITLE
想问一下paddlelabel默认的英文模型的训练模型有吗?想拿来作为预训练模型

### ISSUE THREAD

**Issue by chenshanhuo** [PaddlePaddle/PaddleOCR#7130]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
有的：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md#22-%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/25809855/183416380-2e085ca1-d138-421f-9f84-1c4050d7f758.png">

**Comment by chenshanhuo** [comment]
> 有的：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md#22-%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B <img alt="image" width="1040" src="https://user-images.githubusercontent.com/25809855/183416380-2e085ca1-d138-421f-9f84-1c4050d7f758.png">

请问英文的检测模型的预训练有吗？还是说和中文用的是同一个？

**Comment by chenshanhuo** [comment]
> 有的：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md#22-%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B <img alt="image" width="1040" src="https://user-images.githubusercontent.com/25809855/183416380-2e085ca1-d138-421f-9f84-1c4050d7f758.png">

请问paddlelabel2.3.0.2的那个默认的英文检测模型有可用于训练的模型吗？如果有的话，有不是蒸馏的吗？

**Comment by MissPenguin** [comment]
为什么要不是蒸馏的呢，如果是想用学生模型的参数，可以参考文档进行提取：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/knowledge_distillation.md#225-%E6%A3%80%E6%B5%8B%E8%92%B8%E9%A6%8F%E6%A8%A1%E5%9E%8Bfinetune

**Comment by chenshanhuo** [comment]
> 为什么要不是蒸馏的呢，如果是想用学生模型的参数，可以参考文档进行提取：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/knowledge_distillation.md#225-%E6%A3%80%E6%B5%8B%E8%92%B8%E9%A6%8F%E6%A8%A1%E5%9E%8Bfinetune

数据集只有80张，请问适合用蒸馏吗
