### ISSUE TITLE
修改 Requirements 中 opencv-contrib-python 的版本

### ISSUE THREAD

**Issue by drsanwujiang** [PaddlePaddle/PaddleOCR#7132]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 11 x64 with Python 3.10.5
- 运行指令/Command Code：pip install opencv-contrib-python==4.4.0.46

使用 pip 安装 paddleocr 时一直报错，发现是 4.4.0.46 版本的 opencv-contrib-python 无法安装，但是最新的 4.6.0.66 版本则可以正常安装，能否将 requirements 中 opencv-contrib-python 的版本修改至最新，方便使用 pip 安装 paddleocr？

**Comment by loveanao** [comment]
> 

我opencv-contrib-python使用3.4.2.17也能正常使用，你自己本地，独立指定版本就行了。。。

**Comment by drsanwujiang** [comment]
> > 
> 
> 我opencv-contrib-python使用3.4.2.17也能正常使用，你自己本地，独立指定版本就行了。。。

这和我提的问题有什么关系吗……

**Comment by MissPenguin** [comment]
目前最新的2.6分支已经去除了对opencv版本的限制，可以再试试～

**Comment by drsanwujiang** [comment]
> 目前最新的2.6分支已经去除了对opencv版本的限制，可以再试试～

证实可以正常安装
