### ISSUE TITLE
opencv-python==4.4.0.46不能在mac m1 arm64上安装

### ISSUE THREAD

**Issue by Yezhj1** [PaddlePaddle/PaddleOCR#7133]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macos
- 版本号/Version PaddleOCR： 2.5.0.3
- 运行指令/Command Code：pip3 install paddleocr
- 完整报错/Complete Error Message：`ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based project`
opencv-python==4.4.0.46不提供针对arm64的wheel包，所以安装过程中会出现无法安装。能否放宽对opencv版本的限制，提高opencv版本？谢谢

**Comment by Yezhj1** [comment]
paddleocr所指定的opencv-python和opencv-contrib-python版本为4.4.0.46，去PYPi官网可以查询，这两个包在>=4.5.3.56才出现arm64架构的安装包，所以paddleocr指定的4.4.0.46版本是无法在m1上安装成功的。解决方案可以是这样：
- 在PYPi官网上，下载paddleocr==2.5.0.3的whl安装包到本地，解压后打开，找到METADATA这个文件，将其中`Requires-Dist: opencv-contrib-python (>=4.4.0.46)`修改为`Requires-Dist: opencv-contrib-python`。保存
- 将修改后的文件压缩
- 在压缩文件目录，`pip3 install paddleocr-2.5.0.3-py-none-any.whl`
- 不出意外，opencv-contrib-python的安装应该不会出错了

**Comment by edyang** [comment]
赞，解决了M1安装问题
