### ISSUE TITLE
请问一下 检测结果能输出检测框里的图片嘛

### ISSUE THREAD

**Issue by pbabading** [PaddlePaddle/PaddleOCR#7135]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by pbabading** [comment]
就是将检测框里的图片保存下来

**Comment by MissPenguin** [comment]
可以的，根据检测结果用opencv截取图片区域进行保存就行。
