### ISSUE TITLE
subprocess-exited-with-error   安装paddle包出错

### ISSUE THREAD

**Issue by changlinliu1** [PaddlePaddle/PaddleOCR#7136]
psdz@gpu-2080:~/lcl/PaddleOCR$ python3 tools/train.py -c configs/det/det_mv3_db.yml      -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrain
Traceback (most recent call last):
  File "/home/psdz/lcl/PaddleOCR/tools/train.py", line 27, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'
(paddle_lcl) psdz@gpu-2080:~/lcl/PaddleOCR$ pip install paddle 
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/, https://pypi.ngc.nvidia.com
Collecting paddle
  Downloading http://mirrors.aliyun.com/pypi/packages/55/cf/e4b6b9a54d2f072e4491e34317bf5f5fea260da8a3072e641832dc9ce770/paddle-1.0.2.tar.gz (579 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 579.0/579.0 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-c0s9ux1v/paddle_11586de4c9854a4faa2fbc1f68ade374/setup.py", line 3, in <module>
          import paddle
        File "/tmp/pip-install-c0s9ux1v/paddle_11586de4c9854a4faa2fbc1f68ade374/paddle/__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by Yezhj1** [comment]
ModuleNotFoundError: No module named 'common'
use `pip install common`
maybe you don't install some packages needed

**Comment by MissPenguin** [comment]
用百度的镜像试试呢：https://mirror.baidu.com/pypi/simple
