### ISSUE TITLE
预测和推理得到的结果不一样

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#714]
我在使用mv3+db训练检测模型，结束后分别查看预测和推理的效果，发现两者的效果不一样。我已经将infer中utility.py的默认数据改为了训练时使用的后处理参数，但两者的效果还是不一样，请问是什么原因呢？

预测命令：
python3 tools/infer_det.py -c det_mv3_db.yml -o TestReader.infer_img="/data/tang/newPaddle/doc/test/real/" Global.checkpoints="/data/tang/PaddleOCR/output/det_db_ft1/best_accuracy" Global.test_batch_size_per_card=1 
推理命令：
python3 tools/infer/predict_det.py \
--image_dir="/data/tang/newPaddle/doc/test/real/" \
--det_model_dir="./inference/det_db_ft2_1/" 
其中一个较为明显的对比图（前者为预测，后者为推理）：
![gnline202006a67acdeef59f5244b126fafeb2adcd9f](https://user-images.githubusercontent.com/51456283/93158749-60f6aa80-f73f-11ea-8a0b-d0c40699d23f.jpg)

![det_res_gnline202006a67acdeef59f5244b126fafeb2adcd9f](https://user-images.githubusercontent.com/51456283/93158731-5a683300-f73f-11ea-9f5b-1d2a7825b619.jpg)

后处理参数设置：
utility.py:
 #DB parmas
    parser.add_argument("--det_db_thresh", type=float, default=0.3)
    parser.add_argument("--det_db_box_thresh", type=float, default=0.1)
    parser.add_argument("--det_db_unclip_ratio", type=float, default=1.3) 
det_mv3_db.yml:
PostProcess:
  function: ppocr.postprocess.db_postprocess,DBPostProcess
  thresh: 0.3
  box_thresh: 0.1
  max_candidates: 1000
  unclip_ratio: 1.3

**Comment by MissPenguin** [comment]
从两个目录名称看，是不是模型不一致？det_db_ft1和det_db_ft2_1

**Comment by MissPenguin** [comment]
另外，除了后处理参数，还有个预处理参数要对齐，就是resize的尺寸，predict_det默认是960，看下infer_det是多少

**Comment by tyy2tyy** [comment]
模型是一致的，预测模型转为推理使用的这个名字。另外，关于resize尺寸我没有进行修改

**Comment by MissPenguin** [comment]
把reader yml截图看一下？
另外，按理说推理不至于一个框也检测不到，可能export model有问题，你可以用我们的开源模型export、预测首页示例图试试，确认流程是否正确

**Comment by tyy2tyy** [comment]
reader:
![1](https://user-images.githubusercontent.com/51456283/93173196-baba9d00-f75e-11ea-8e51-f5fdcaf97853.png)
yml:
![2](https://user-images.githubusercontent.com/51456283/93173216-c1e1ab00-f75e-11ea-99dd-1191238fc8ea.png)
![3](https://user-images.githubusercontent.com/51456283/93173224-c5753200-f75e-11ea-8287-c8115bdfb89a.png)
使用示例export模型预测图：预测命令：python3 tools/infer/predict_det.py --image_dir="./doc/imgs/2.jpg" --det_model_dir="/data/tang/PaddleOCR/test_model/ch_det_mv3_db/"
![4](https://user-images.githubusercontent.com/51456283/93173262-d756d500-f75e-11ea-8387-39a8324e6e57.PNG)

**Comment by tyy2tyy** [comment]
流程没有问题

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/93178016-3b30cc00-f766-11ea-9182-4f9d0007b85e.png)
reader yml里面这个参数将测试图像resize到736*1280了（相应逻辑可以看这里的代码：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py#L127），而predict_det是resize到长边960（对应代码：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L44）

把reader中的test_image_shape去掉，增加一个max_side_len: 960，应该就能对齐了

**Comment by tyy1tyy** [comment]
好的，已解决，多谢
