### ISSUE TITLE
ERROR: unknown command line flag 'char_list_file'

### ISSUE THREAD

**Issue by SongyaCAT** [PaddlePaddle/PaddleOCR#7145]
我是win11 C++部署的CPU版，预测的时候使用--char_list_file报错，请问这种问题该怎么处理呢？谢谢！

**Comment by LDOUBLEV** [comment]
更新代码到最新的分支，现在已经没有这个参数了

**Comment by SongyaCAT** [comment]
> 更新代码到最新的分支，现在已经没有这个参数了

噢噢好的，谢谢！
