### ISSUE TITLE
V3 的繁体中文识别模型，一直不适配“竖排文字”的识别。

### ISSUE THREAD

**Issue by yangtle** [PaddlePaddle/PaddleOCR#7148]
你好，V3 的繁体中文识别模型，不再适配“竖排文字”的识别。而繁字体模型大多应用于竖排情况，比如古籍的识别等等。

在5月发布时曾说尽快更新一版，请问到现在有做相关更新吗？谢谢

**Comment by LDOUBLEV** [comment]
V3的繁体字识别模型已经更新，可以尝试，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md#23-%E5%A4%9A%E8%AF%AD%E8%A8%80%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E6%9B%B4%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD

**Comment by PandaBalls** [comment]
我遇到的是版式问题，识别文字单个都很准确，但是返回的字符块全都是横排的行。语义都是不对的。不知道如何强制返回列识别
