### ISSUE TITLE
paddleOCR 安卓部署报错

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#7149]
报错如下：
A/Paddle-Lite: [F  8/ 9 10:30:58.539 ...20/lite/Paddle-Lite/lite/core/program.cc:356 RuntimeProgram] Check failed: (kernels.size() > 0): 0!>0 
    Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4150 (Predictor Worke), pid 3940 (example.testapp)
有大佬帮忙解答下嘛？看起来是paddle_Lite版本问题，但是我本地跑可以，放到同学那里却不行，不知道为什么

**Comment by LDOUBLEV** [comment]
> Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.

导出nb模型的paddlelite版本需要和 使用的paddlelite 预测库版本一致
