### ISSUE TITLE
paddle inference   每次推理都要重新优化一遍模型吗？

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleOCR#715]

**Comment by MissPenguin** [comment]
你是说重新初始化吗？每次直接推理是要重新初始化的，如果用服务的形式启动，那只有第一次访问会进行初始化，后面再访问就不用了

**Comment by MissPenguin** [comment]
可以尝试2种方式：
1.  批量预测，这样只有预测第一张图时会初始化，后面的图就直接预测了
2. 包成服务挂载起来，也是第一次预测会做初始化，但只要服务不断，每次重新请求都不会再初始化了

**Comment by Unknown-parameters** [comment]
> 可以尝试2种方式：
> 
> 1. 批量预测，这样只有预测第一张图时会初始化，后面的图就直接预测了
> 2. 包成服务挂载起来，也是第一次预测会做初始化，但只要服务不断，每次重新请求都不会再初始化了
多谢
