### ISSUE TITLE
关于ppocrV3的模型参数问题

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#7167]
文字识别模型中
  model_type: rec
  algorithm: SVTR

1 neck设置为 SVTR其loss明显低于rnn  
Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: True

2.backbone中不包含LCnet的参数

该如何修改SVTR的参数？
以及该如何在文字识别中实现backbone为lcnet模型？

**Comment by tink2123** [comment]
请问您具体的问题是希望修改SVTR的参数成什么？V3的backbone就是LCNet：https://github.com/PaddlePaddle/PaddleOCR/blob/b8a98bc32e1ed4c770c30c18d1cd19b7716867b7/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml#L42
