### ISSUE TITLE
运行PPOCRLabel出错

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#7169]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu 
- 版本号/Version：Paddle：  paddlepaddle-gpu              2.0.0rc1.post100
- 运行指令/Command Code： python PPOCRLabel.py
- 完整报错/Complete Error Message：

    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by JackyAndroid** [comment]
@cqray1990 怎么解决的？
