### ISSUE TITLE
pretrained_model and checkpoints parameters in det_mv3_db.yml in detection training

### ISSUE THREAD

**Issue by anidiatm41** [PaddlePaddle/PaddleOCR#7175]
Experts ,
I am custom training the DB detection model using my own annotated data . 

While setting the yml config file (**det_mv3_db.yml**), I came across below two parameters : 

- pretrained_model: 
- checkpoints: 

I want to know,

Q1. what is the use of this two parameters?
Q2. If I want to do a training from scratch..what would be the parameters value? 
Q3. If I want to do a transfer learning from last checkpoints ...what will be the parameters value?

**Comment by anidiatm41** [comment]
@andyjpaddle

**Comment by anidiatm41** [comment]
@Evezerest

**Comment by MohieEldinMuhammad** [comment]
@anidiatm41 if you knew how to continue training on the trained model let me know if you please

**Comment by MohieEldinMuhammad** [comment]
i have noticed that train.py is starting the arch from scratch i need to do transfer learning
