### ISSUE TITLE
3.0英文模型识别失败

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#7176]
在用3.0版本的英文模型识别一张英文证件，识别出来都是中文。

命令如下：
python tools/infer/predict_system.py --use_gpu=False \
--rec_model_dir=./models/en_PP-OCRv3_rec \
--det_model_dir=./models/en_PP-OCRv3_det \
--image_dir=../esp_id_1.jpg

图片为：
![esp_id_1](https://user-images.githubusercontent.com/30545972/184270697-ff92a9ba-2b07-4cc1-bf67-d4faa22cd924.jpg)

识别结果为：
![rec_result](https://user-images.githubusercontent.com/30545972/184270932-b1e84ef1-69ef-4d95-9b22-94e9c93c7f7f.jpg)

**Comment by trucdtt** [comment]
You can add --rec_char_dict_path ./ppocr/utils/en_dict.txt in your command

**Comment by jack-gits** [comment]
好了，谢谢
