### ISSUE TITLE
知识蒸馏模型检测黑白图片出错

### ISSUE THREAD

**Issue by Jackzhangfei** [PaddlePaddle/PaddleOCR#7177]
在我使用知识蒸馏模型检测图片时候
![image](https://user-images.githubusercontent.com/87180243/184272581-01e0a1e2-3060-486c-be04-04b14b1bf1c8.png)
会显示如下信息
![image](https://user-images.githubusercontent.com/87180243/184272622-4ec5250b-e0cb-419c-b6f7-24b67be49ec8.png)

[operator < conv2d > error]

但是我把图片更换为彩色图片却没有错误
![image](https://user-images.githubusercontent.com/87180243/184272685-bd38e0c3-6c57-4fcd-b385-522f0437f82d.png)
![image](https://user-images.githubusercontent.com/87180243/184272714-475cb3a8-7651-4f2f-856f-69bc85a02570.png)
所以想请问这个是什么问题？

**Comment by LDOUBLEV** [comment]
猜测是你的黑白图像太大了，内存不够
<img width="638" alt="image" src="https://user-images.githubusercontent.com/26592129/186805782-abe9961f-4c37-427f-8fbc-32a3baf458a0.png">
