### ISSUE TITLE
关于best metric acc：0

### ISSUE THREAD

**Issue by susJohnny** [PaddlePaddle/PaddleOCR#7185]
兄弟们，我在训练预训练模型时遇到了问题，明明之前的训练的log显示acc已到0.9998，然而最后best metric acc仍然等于0，请问有人知道是什么情况吗

**Comment by WenmuZhou** [comment]
是不是评估的间隔太低了

**Comment by susJohnny** [comment]
。。。怎么调评估的间隔

**Comment by WenmuZhou** [comment]
配置文件里有个 eval_batch_step，这个改大点

**Comment by susJohnny** [comment]
。。之前我们已经设成了256.。。

**Comment by susJohnny** [comment]
还是不够大？（大概多少会比较合适）

**Comment by WenmuZhou** [comment]
不是batchsize，是这个
<img width="612" alt="image" src="https://user-images.githubusercontent.com/12406017/187600001-9ee84c1a-2dc4-4ad0-b21b-8245e0e6f6b4.png">
