### ISSUE TITLE
怎样根据识别的错字强化生成bad case训练集？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7186]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

怎样根据识别的错字强化生成bad case训练集？微信nlanguage

**Comment by WenmuZhou** [comment]
可以将错字单独做一个语料，然后进行生成
