### ISSUE TITLE
调用opencv4.6.0.66 dnn模块报错，模型是v2_det转onnx

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#7188]
环境
onnx                               1.12.0
onnx-simplifier                    0.3.10
onnxoptimizer                      0.2.7
onnxruntime                        1.12.0
onnxruntime-gpu                    1.12.0

paddle-parakeet                    0.0.0
paddle-serving-app                 0.7.0
paddle-serving-client              0.7.0
paddle-serving-server-gpu          0.7.0.post1028
paddle2onnx                        0.9.8
paddleaudio                        0.1.0a0
paddledet                          2.3.0
paddlehub                          2.2.0
paddlenlp                          2.2.3
paddleocr                          2.5
paddlepaddle                       2.2.1
paddlepaddle-gpu                   2.2.1.post112
paddlespeech                       0.1.0a0
paddlespeech-feat                  0.1.0

opencv-python						4.6.0.66
opencv-contrib-python				4.6.0.66

#转onnx成功
(base) D:\work\projects\paddleocr23\PaddleOCR>paddle2onnx --model_dir ./inference/ch_PP-OCRv2_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/det_onnx/model.onnx --opset_version 11 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True

#onnxruntime调用det成功
detect.py --weights D:\work\projects\paddleocr23\PaddleOCR\inference\det_onnx\model.onnx --source d:/imgs/yzmlist_inr_2.jpg --device cpu

(base) D:\work\projects\yolov5-master>python detect.py --weights D:\work\projects\paddleocr23\PaddleOCR\inference\det_onnx\model.onnx --source d:/imgs/yzmlist_inr_2.jpg --device cpu
detect: weights=['D:\\work\\projects\\paddleocr23\\PaddleOCR\\inference\\det_onnx\\model.onnx'], source=d:/imgs/yzmlist_inr_2.jpg, data=data\wenju.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_n
ms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 � 2022-8-9 Python-3.7.0 torch-1.11.0+cu113 CPU

Loading D:\work\projects\paddleocr23\PaddleOCR\inference\det_onnx\model.onnx for ONNX Runtime inference...
image 1/1 D:\imgs\yzmlist_inr_2.jpg: 640x640 Done. (0.032s)
Speed: 2.9ms pre-process, 32.0ms inference, 0.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs\detect\exp15

#infer没问题
python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=D:\work\projects\paddleocr23\PaddleOCR\inference\det_onnx\model.onnx  --rec_model_dir=D:\work\projects\paddleocr23\PaddleOCR\inference\rec_onnx\model.onnx  --image_dir=d:\imgs\1.jpg

#调用opencv4.6.0.66 dnn模块加载onnx模型报错:net = cv2.dnn.readNetFromONNX(modelWeights)

D:\work\apps\Anaconda3\python.exe D:/work/projects/learnopencv/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python/yolov5.py
[ERROR:0@0.030] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1021) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(onnx_node!Clip_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "D:/work/projects/learnopencv/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python/yolov5.py", line 124, in <module>
    net = cv2.dnn.readNetFromONNX(modelWeights)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Clip@ai.onnx]:(onnx_node!Clip_0) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1934: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20220524::ONNXImporter::parseClip(class cv::dnn::dnn4_v20220524::LayerParams &,const class opencv_onnx::NodeProto &)'
> >  (expected: 'node_proto.input_size() == 1'), where
> >     'node_proto.input_size()' is 3
> > must be equal to
> >     '1' is 1
> 

Process finished with exit code 1

**Comment by littletomatodonkey** [comment]
你好，使用dnn模块加载det模型之前没有尝试过，推荐还是基于paddleinference去推理哈，这个要不也在opencv的repo中提个issue看下呢？

**Comment by dengmingD** [comment]
已经解决
