### ISSUE TITLE
官方能提供opencv dnn 调onnx(det/cls/rec)的代码（python/c++）

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#7191]
官方能提供opencv>=4.5.5 dnn模块 调onnx(det/cls/rec)的代码（python/c++）
如：
net = cv2.dnn.readNetFromONNX(modelWeights)
谢谢

**Comment by littletomatodonkey** [comment]
你好，之前这块没有计划，我们再评估下哈，目前推荐的还是paddleinference、paddleserving或者paddlelite去做推理不熟

**Comment by dengmingD** [comment]
> 你好，之前这块没有计划，我们再评估下哈，目前推荐的还是paddleinference、paddleserving或者paddlelite去做推理部署

这块应用很大，可以解决32位问题，因为我们银行客户有很多的32位电脑，我们不得不更换框架，paddlpaddle我们熟悉、好用，其他的还得投入时间，成本很大。希望paddlepaddle越做越好!!

**Comment by dengmingD** [comment]
已经解决
