### ISSUE TITLE
ppocr 训练时db_fpn.py报错，相加维度不一致， Broadcast dimension mismatch

### ISSUE THREAD

**Issue by modem1024k** [PaddlePaddle/PaddleOCR#7193]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境win10nt：
- 版本号/Version：Paddle：  PaddleOCR2.1： 问题相关组件/Related components：
- 运行指令/：python tools/train.py -c configs/det/det_mv3_db.yml
- 完整报错/
-  File "D:\PaddleOCR2.1\ppocr\modeling\necks\db_fpn.py", line 103, in forward
    out4, scale_factor=2, mode="nearest", align_mode=1)  # 1/8
  File "D:\Python37\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 249, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 7, 15] and the shape of Y = [1, 256, 8, 16]. Received [7] in X is not equal to [8] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at D:\v2.0.2\paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]

**Comment by MissPenguin** [comment]
是不是改了输入shape，改的话需要是32的倍数哈，不然经过几次下采样后会出现一个像素的diff，导致elementwise_add操作报错

**Comment by modem1024k** [comment]
是的，我把shape 改成了 120*50, 原来的是 image_shape: [736, 1280]，这个是 [宽,高]还是[高,宽]?我是不是需要把训练的图片的宽和高也改成32的倍数?

**Comment by MissPenguin** [comment]
> 是的，我把shape 改成了 120*50, 原来的是 image_shape: [736, 1280]，这个是 [宽,高]还是[高,宽]?我是不是需要把训练的图片的宽和高也改成32的倍数?

是 [宽,高]，训练的shape也需要满足32的倍数，默认应该是640或者960

**Comment by modem1024k** [comment]
> > 是的，我把shape 改成了 120*50, 原来的是 image_shape: [736, 1280]，这个是 [宽,高]还是[高,宽]?我是不是需要把训练的图片的宽和高也改成32的倍数?
> 
> 是 [宽,高]，训练的shape也需要满足32的倍数，默认应该是640或者960

非常感谢
