### ISSUE TITLE
AssertionError: invalid input 'img' in DecodeImage

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#7195]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by JavieYuan** [comment]
![image](https://user-images.githubusercontent.com/84179587/184543950-1dff1a07-2754-47cf-b498-50b428092e77.png)

**Comment by JavieYuan** [comment]
识别部分全部都是这种错误，是数据集和标签数据没有完全对应的原因吗还是？

**Comment by MissPenguin** [comment]
检查下数据读取路径、label格式等是否正确吧
