### ISSUE TITLE
请问使用默认模型识别时,能指定文字的尺寸大小粗线角度吗

### ISSUE THREAD

**Issue by VieteChen** [PaddlePaddle/PaddleOCR#7197]
请问使用默认模型识别时,能指定文字的尺寸大小粗线角度吗

**Comment by MissPenguin** [comment]
指定是什么意思，目前识别模型的输入是文本行图像就行

**Comment by VieteChen** [comment]
> 指定是什么意思，目前识别模型的输入是文本行图像就行

目前识别率几乎为0，如果输入参数有角度或者字体大小会不会好一点。
另外请问一下为什么，实力活力那张90度的图片在命令行能识别，但在代码中ocr.ocr('word_4.jpg')不能识别。

**Comment by MissPenguin** [comment]
> > 指定是什么意思，目前识别模型的输入是文本行图像就行
> 
> 目前识别率几乎为0，如果输入参数有角度或者字体大小会不会好一点。 另外请问一下为什么，实力活力那张90度的图片在命令行能识别，但在代码中ocr.ocr('word_4.jpg')不能识别。 ![word_4](https://user-images.githubusercontent.com/45503948/184605366-eb7675c7-60fa-470c-9efc-44a60f0524b8.jpg)

这张case适合仅使用识别模型直接进行识别，你用ocr.ocr()包含了检测模块
