### ISSUE TITLE
ImportError: DLL load failed while importing core_avx: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by SongyaCAT** [PaddlePaddle/PaddleOCR#7200]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10/9700k/tesla P4/python3.8/cuda10.2/cudnn7.6.5.32/trt-7.0.0.11
- 版本号/Version：Paddle：cuda10.2_cudnn7.6.5_avx_mkl-trt7.0.0.11  PaddleOCR：release2.5 问题相关组件/Related components：
- 问题描述：直接安装的预测库里的`cuda10.2_cudnn7.6.5_avx_mkl-trt7.0.0.11`。按照网上能查到的方法，已更新`Visual Studio 2015-2022(x64)`和`numpy-1.22.4+mkl-cp38-cp38-win_amd64.whl`，但报错不变。如果使用先按照官网的快速安装指令`python -m pip install paddlepaddle-gpu==2.3.1 -i https://mirror.baidu.com/pypi/simple`，就可以使用参数`use_gpu=True`预测但是加上'use_tensorrt'就会报错`[Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:240)`。
- 运行指令/Command Code：D:\ppocr_py\PaddleOCR-release-2.5\tools\infer>python predict_system.py --det_model_dir=D:\ppocr_py\ch_PP-OCRv3_det_infer --rec_model_dir=D:\ppocr_py\ch_PP-OCRv3_rec_infer --rec_char_dict_path=D:\ppocr_py\PaddleOCR-release-2.5\ppocr\utils\ppocr_keys_v1.txt --use_gpu=True --use_tensorrt=True --image_dir=D:\ppocr_py\img
- 完整报错/Complete Error Message：(paddle_env) D:\ppocr_py\PaddleOCR-release-2.5\tools\infer>python predict_system.py --det_model_dir=D:\ppocr_py\ch_PP-OCRv3_det_infer --rec_model_dir=D:\ppocr_py\ch_PP-OCRv3_rec_infer --rec_char_dict_path=D:\ppocr_py\PaddleOCR-release-2.5\ppocr\utils\ppocr_keys_v1.txt --use_gpu=True --use_tensorrt=True --image_dir=D:\ppocr_py\img
Error: Can not import avx core while this file exists: C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "D:\ppocr_py\PaddleOCR-release-2.5\tools\infer\utility.py", line 21, in <module>
    import paddle
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core.py", line 298, in <module>
    raise e
  File "C:\Users\zy\.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core.py", line 256, in <module>
    from . import core_avx
ImportError: DLL load failed while importing core_avx: %1 不是有效的 Win32 应用程序。

**Comment by iknow34languages** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：win10/9700k/tesla P4/python3.8/cuda10.2/cudnn7.6.5.32/trt-7.0.0.11
> * 版本号/Version：Paddle：cuda10.2_cudnn7.6.5_avx_mkl-trt7.0.0.11  PaddleOCR：release2.5 问题相关组件/Related components：
> * 问题描述：直接安装的预测库里的`cuda10.2_cudnn7.6.5_avx_mkl-trt7.0.0.11`。按照网上能查到的方法，已更新`Visual Studio 2015-2022(x64)`和`numpy-1.22.4+mkl-cp38-cp38-win_amd64.whl`，但报错不变。如果使用先按照官网的快速安装指令`python -m pip install paddlepaddle-gpu==2.3.1 -i https://mirror.baidu.com/pypi/simple`，就可以使用参数`use_gpu=True`预测但是加上'use_tensorrt'就会报错`[Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:240)`。
> * 运行指令/Command Code：D:\ppocr_py\PaddleOCR-release-2.5\tools\infer>python predict_system.py --det_model_dir=D:\ppocr_py\ch_PP-OCRv3_det_infer --rec_model_dir=D:\ppocr_py\ch_PP-OCRv3_rec_infer --rec_char_dict_path=D:\ppocr_py\PaddleOCR-release-2.5\ppocr\utils\ppocr_keys_v1.txt --use_gpu=True --use_tensorrt=True --image_dir=D:\ppocr_py\img
> * 完整报错/Complete Error Message：(paddle_env) D:\ppocr_py\PaddleOCR-release-2.5\tools\infer>python predict_system.py --det_model_dir=D:\ppocr_py\ch_PP-OCRv3_det_infer --rec_model_dir=D:\ppocr_py\ch_PP-OCRv3_rec_infer --rec_char_dict_path=D:\ppocr_py\PaddleOCR-release-2.5\ppocr\utils\ppocr_keys_v1.txt --use_gpu=True --use_tensorrt=True --image_dir=D:\ppocr_py\img
>   Error: Can not import avx core while this file exists: C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core_avx.pyd
>   Traceback (most recent call last):
>   File "predict_system.py", line 31, in 
>   import tools.infer.utility as utility
>   File "D:\ppocr_py\PaddleOCR-release-2.5\tools\infer\utility.py", line 21, in 
>   import paddle
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle__init__.py", line 25, in 
>   from .framework import monkey_patch_variable
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\framework__init__.py", line 17, in 
>   from . import random  # noqa: F401
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\framework\random.py", line 16, in 
>   import paddle.fluid as fluid
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\fluid__init__.py", line 36, in 
>   from . import framework
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 37, in 
>   from . import core
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core.py", line 298, in 
>   raise e
>   File "C:\Users\zy.conda\envs\paddle_env\lib\site-packages\paddle\fluid\core.py", line 256, in 
>   from . import core_avx
>   ImportError: DLL load failed while importing core_avx: %1 不是有效的 Win32 应用程序。

请编译32位的
