### ISSUE TITLE
V3的rec模型，为何eval时在IC15上的精度只有65%？

### ISSUE THREAD

**Issue by labmanno004** [PaddlePaddle/PaddleOCR#7203]
看SVTR论文中在做消融实验的时候，使用最小的模型，在不使用矫正模块和数据增强的情况下也能有75%的精度啊
查看结果时发现，测试集中所有不是水平的图像几乎都预测错了。

**Comment by Topdu** [comment]
V3识别模型针对规则文本数据集训练得到，对ic15等不规则数据集精度不高，后续会针对不规则数据集优化

**Comment by carolyueyueyue** [comment]
你好，能咨询一下关于训练cidar15是的一些问题吗？

**Comment by carolyueyueyue** [comment]
> 看SVTR论文中在做消融实验的时候，使用最小的模型，在不使用矫正模块和数据增强的情况下也能有75%的精度啊 查看结果时发现，测试集中所有不是水平的图像几乎都预测错了。

能咨询您一些问题吗？

**Comment by Topdu** [comment]
使用的哪个模型？PP-OCRv3识别模型还是SVTR？

**Comment by carolyueyueyue** [comment]
> 使用的哪个模型？PP-OCRv3识别模型还是SVTR？
您在使用ICDAR15数据集时对那一部分进行处理了？我看readme只有totaltext数据集的使用方式，您如何使用的icdar15？
能否帮助我一下，谢谢，我的QQ1726256798

**Comment by carolyueyueyue** [comment]
你好，你在使用icdar15做实验时是怎么修改readme的？readme只有关于totaltext 的？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] V3的rec模型，为何eval时在IC15上的精度只有65%？ (Issue #7203)





 
使用的哪个模型？PP-OCRv3识别模型还是SVTR？

**Comment by LDOUBLEV** [comment]
修改数据集训练，只需要修改配置文件中数据部分的参数即可https://github.com/PaddlePaddle/PaddleOCR/blob/f6072d2222326e87a489247e81f6c9ad0389c24c/configs/rec/rec_svtrnet.yml#L79-L80
