### ISSUE TITLE
SVTR高精度中文模型

### ISSUE THREAD

**Issue by Lingyun0109** [PaddlePaddle/PaddleOCR#7207]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：ocr = PaddleOCR(use_angle_cls=True, lang="ch", det_db_score_mode='slow', use_dilation=True, rec_algorithm='SVTR', rec_model_dir='./inference/svtr_ch/', rec_image_shape='3, 32, 320', rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', det_limit_side_len=2000, det_db_score_mode='slow', use_dilation=True)
指定了--rec_image_shape='3, 32, 320'，但是输出还是‘3,48,320’
- 完整报错/Complete Error Message：
![图片](https://user-images.githubusercontent.com/93696768/184624279-93995cb7-7ca2-440f-9d90-10561caa471b.png)

**Comment by Topdu** [comment]
预测结果对吗？不对的话，建议把默认的rec_image_shape改成3，32，320

**Comment by Lingyun0109** [comment]
> 预测结果对吗？不对的话，建议把默认的rec_image_shape改成3，32，320

我修改了默认，但是输出显示的还是48；预测结果倒是对的，但是为什么感觉精度反倒没有默认的SVTR精度高呢？

**Comment by Topdu** [comment]
默认的是PP-OCRv3的识别模型，该识别模型和原SVTR模型训练数据集不一样，v3识别模型更丰富多样且是真实数据，原SVTR模型仅仅在英文的合成数据集上训练，因此在真实场景中，v3的识别模型会更有优势。
