### ISSUE TITLE
为什么PPOCR v3的方向分类模型，Netron显示模型输入为32 * 100？

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#7210]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

参照文档，PPOCR v3的方向分类模型输入尺寸为3 * 48 * 192， 为什么通过Netron查看却显示输入大小为[3, 32, 100]
<img width="472" alt="7f396c0f39f1517d5306fe06eab642d6" src="https://user-images.githubusercontent.com/17264083/184806126-8d70f9c2-cab7-471c-bf8d-9c5f655814fe.png">

**Comment by andyjpaddle** [comment]
使用的是哪个方向分类器模型呢？

**Comment by Intsigstephon** [comment]
PPOCRv3用到的那个方向分类器模型：
![5b8045af3ebbd7e8449d27c224a1d318](https://user-images.githubusercontent.com/17264083/185550377-5789db46-5b2c-48dd-bfd1-e15ea88289c1.png)

**Comment by Intsigstephon** [comment]
推理模型

**Comment by andyjpaddle** [comment]
可能是推理模型导出有问题，可以自己重新导出一下，按照训练配置的shape设置就好3 * 48 * 192

**Comment by andyjpaddle** [comment]
不过这个shape不影响预测，所以可以忽略哈

**Comment by WenmuZhou** [comment]
已经重新导出了一份
