### ISSUE TITLE
英文数字文字识别的预训练模型是在哪个数据集上训练的？

### ISSUE THREAD

**Issue by JinYuannn** [PaddlePaddle/PaddleOCR#7211]
请问文字识别的预训练模型（en_number_mobile_slim_v2.0_rec）是用什么数据集训练的，我想评估一下我fine-tune后有没有在预训练数据集上掉点。

**Comment by tink2123** [comment]
是自用数据集，包含开源数据和大量的合成数据，无法开源。可以使用repo里的测试图跑推理，看下模型效果变换。
