### ISSUE TITLE
PaddleOCR 的CPP_infer能否支持onnx模型；

### ISSUE THREAD

**Issue by qumoy** [PaddlePaddle/PaddleOCR#7213]
python端将检测和识别推理模型转成onnx模型之后，可以成功运行onnx模型进行OCR检测和识别；
请问一下C++部署环境下，目前能否支持ONNX模型进行算法处理，配置文件中未找到支持“--use_onnx”的配置选项

- 系统环境/System Environment：paddlepaddle-gpu 2.2.2
- 版本号/Version：Paddle： paddlerelease2.5 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
c++推理暂不支持onnx模型

**Comment by dengmingD** [comment]
可以转成onnx格式，用onnxruntime api调（c++），官方有转换脚本，看下文档吧，里面有详细介绍。
如：
paddle2onnx -m inference\rec_mengshang_bank\Teacher --model_filename inference.pdmodel --params_filename inference.pdiparams -s inference/rec_mengshang_bank_onnx/model.onnx
