### ISSUE TITLE
能否提供一个仅识别数字的ocr模型

### ISSUE THREAD

**Issue by wurentidai** [PaddlePaddle/PaddleOCR#7215]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以使用英文数字模型
