### ISSUE TITLE
使用LMDBDataSet对Rosetta模型进行评估，valid_dataloader为空

### ISSUE THREAD

**Issue by max-niu** [PaddlePaddle/PaddleOCR#7222]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18 
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.4 问题相关组件/Related components：
- 运行指令/Command Code： python3 tools/eval.py -c configs/rec/rec_r34_vd_none_none_ctc.yml  -o Global.checkpoints="../checkpoint/rec_mv3_tps_bilstm_ctc_v2.0_train/best_accuracy"

- 完整报错/Complete Error Message：
[2022/08/17 03:34:15] root INFO: start_epoch:52
eval model:: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "tools/eval.py", line 82, in <module>
    main()
  File "tools/eval.py", line 74, in main
    eval_class, model_type, extra_input)
  File "/opt/npu/max/pp/PaddleOCR/tools/program.py", line 433, in eval
    metric['fps'] = total_frame / total_time + 0.001
ZeroDivisionError: float division by zero
(pp) root@gpu2:/opt/npu/max/pp/PaddleOCR#

已获取LMDB数据
![image](https://user-images.githubusercontent.com/57517234/185030772-536bd736-dd2a-4b3e-8dac-aeeb37c20ef6.png)

**Comment by max-niu** [comment]
eval model::   0%|                                                                                                                                      | 0/28 [00:00<?, ?it/s][256, 3, 32, 100]


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1660708747 (unix time) try "date -d @1660708747" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 19620 (TID 0x7fc82abec740) from PID 0 ***]

Segmentation fault (core dumped)

![image](https://user-images.githubusercontent.com/57517234/185031773-3e1155a6-4c80-4665-a00d-1ab65f68aafa.png)

**Comment by max-niu** [comment]
![image](https://user-images.githubusercontent.com/57517234/185040711-f0d0cdaf-96d7-48b3-be55-bf8053ba5101.png)
为什么评估精度会是0

**Comment by tink2123** [comment]
>rec_r34_vd_none_none_ctc.yml
>rec_mv3_tps_bilstm_ctc_v2.0_train/best_accuracy

使用的配置文件和模型参数不匹配
