### ISSUE TITLE
paddleocr to Onnx tensorrt

### ISSUE THREAD

**Issue by SHOUshou0426** [PaddlePaddle/PaddleOCR#7226]
检测模型：ch_PP-OCRv3_det
识别模型：ch_PP-OCRv3_rec
通过paddle2onnx 转onnx 
paddle2onnx --model_dir ./ch_PP-OCRv3_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_det_infer/v3_det.onnx --opset_version 10 --enable_onnx_checker True

paddle2onnx --model_dir ./ch_PP-OCRv3_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_rec_infer/v3_rec.onnx --opset_version 10 --enable_onnx_checker True

使用onnx 转 tensorrt 我需要进行借助onnxsim 工具进行缩放模型架构

在进行缩放的时候丢出了维度不一致的错误
python -m onnxsim ./ch_PP-OCRv3_det_infer/v3_det.onnx ./ch_PP-OCRv3_det_infer/v3_det_sim.onnx

Simplifying...
Traceback (most recent call last):
  File "C:\Users\yuanx\.conda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\yuanx\.conda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\__main__.py", line 5, in <module>
    main()
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 444, in main
    args.tensor_size_threshold,
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 189, in simplify
    tensor_size_threshold,
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Sigmoid, node name: Sigmoid_0): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 2: (32) vs (-1)

我使用netron 查看 x : -1x3x-1x-1  查看pdmodel文件  x：?x3x?x? 

 请问这个是什么原因 如何解决

**Comment by SHOUshou0426** [comment]
如果不进行缩放onnx 结构出现 
[08/17/2022-15:08:34] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/17/2022-15:08:34] [W] Dynamic dimensions required for input: x, but no shapes were provided. Automatically overriding shape to: 1x3x1x1
[08/17/2022-15:08:34] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 10.2.2 but loaded cuBLAS/cuBLAS LT 10.2.1
[08/17/2022-15:08:39] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
C:\source\rtSafe\cublas\cublasLtWrapper.cpp:279
Aborting...
[08/17/2022-15:08:39] [E] [TRT] C:\source\rtSafe\cublas\cublasLtWrapper.cpp (279) - Assertion Error in nvinfer1::CublasLtWrapper::getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
[08/17/2022-15:08:39] [E] Engine creation failed
[08/17/2022-15:08:39] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.onnx --saveEngine=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.engine

**Comment by jiangjiajun** [comment]
> 检测模型：ch_PP-OCRv3_det 识别模型：ch_PP-OCRv3_rec 通过paddle2onnx 转onnx paddle2onnx --model_dir ./ch_PP-OCRv3_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_det_infer/v3_det.onnx --opset_version 10 --enable_onnx_checker True
> 
> paddle2onnx --model_dir ./ch_PP-OCRv3_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_rec_infer/v3_rec.onnx --opset_version 10 --enable_onnx_checker True
> 
> 使用onnx 转 tensorrt 我需要进行借助onnxsim 工具进行缩放模型架构
> 
> 在进行缩放的时候丢出了维度不一致的错误 python -m onnxsim ./ch_PP-OCRv3_det_infer/v3_det.onnx ./ch_PP-OCRv3_det_infer/v3_det_sim.onnx
> 
> Simplifying... Traceback (most recent call last): File "C:\Users\yuanx.conda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Users\yuanx.conda\envs\paddle\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim__main__.py", line 5, in main() File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 444, in main args.tensor_size_threshold, File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 189, in simplify tensor_size_threshold, onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Sigmoid, node name: Sigmoid_0): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 2: (32) vs (-1)
> 
> 我使用netron 查看 x : -1x3x-1x-1 查看pdmodel文件 x：?x3x?x?
> 
> 请问这个是什么原因 如何解决

先使用paddle2onnx处理下吧，会清除掉原有模型中所有shape信息，再重新进行shape推断，类似下面这样的命令
```
python -m paddle2onnx.optimize --input_model model.onnx  --output_model new_model.onnx  --input_shape_dict "{'image':[1,3,32,480]}"
```

**Comment by SHOUshou0426** [comment]
> > 检测模型：ch_PP-OCRv3_det 识别模型：ch_PP-OCRv3_rec 通过paddle2onnx 转onnx paddle2onnx --model_dir ./ch_PP-OCRv3_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_det_infer/v3_det.onnx - -opset_version 10 --enable_onnx_checker 真
> > paddle2onnx --model_dir ./ch_PP-OCRv3_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_rec_infer/v3_rec.onnx --opset_version 10 --enable_onnx_checker True
> > 使用 onnx 转 tensorrt 我需要进行使用 onnxsim 工具进行建模模型架构
> > python -m ./ch_PP-OCRv3_det_det_infer/v3_det_det_infer/v3_det_det_infer/v3_det_det_infer
> > ” 行调用spec文件... Traceback（最近一次调用最后）：文件\Users\yuanx.da\envs\paddle.py，第19条，在_**run_as_main**__，mod_）“C:\Users\yuanx.conda\envs \paddle\lib\runpy.py”，第 85 行，_run_code exec(code, run_globals) 文件“C:\Users\yuanx.conda\envs\paddle\lib\site-packages\ onnxsim__main_****___.py”，第 5 行，在 main() 文件中“C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py”，第 444 行，在 main args。 tensor_size_threshold ，文件中C:\Users\yuanx.condaenvs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py"，第189行，在名称tensor_size_threshold，onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] ( op ： Sigmoid Sigmoid 节点名称：Sigmoid_0）：[ShapeInferenceError]2 节点形状和现有形状与尺寸不同：32）（-1）
> > 我使用netron 查看x : -1x3x-1x-1 查看pdmodel文件 x：?x3x?x?
> > 这是什么原因如何解决
> 
> 先用paddle2onn下处理，会清除掉旧模型中的所有形状信息，再进行图谱命令，类似下面这样的
> 
> ```
> python -m paddle2onnx.optimize --input_model model.onnx  --output_model new_model.onnx  --input_shape_dict "{'image':[1,3,32,480]}"
> ```


检测网络模型 和识别网络模型 都需要人为规定一下网络输入尺寸，让网络重新规划嘛

**Comment by SHOUshou0426** [comment]
> > 检测模型：ch_PP-OCRv3_det 识别模型：ch_PP-OCRv3_rec 通过paddle2onnx 转onnx paddle2onnx --model_dir ./ch_PP-OCRv3_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_det_infer/v3_det.onnx --opset_version 10 --enable_onnx_checker True
> > paddle2onnx --model_dir ./ch_PP-OCRv3_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ch_PP-OCRv3_rec_infer/v3_rec.onnx --opset_version 10 --enable_onnx_checker True
> > 使用onnx 转 tensorrt 我需要进行借助onnxsim 工具进行缩放模型架构
> > 在进行缩放的时候丢出了维度不一致的错误 python -m onnxsim ./ch_PP-OCRv3_det_infer/v3_det.onnx ./ch_PP-OCRv3_det_infer/v3_det_sim.onnx
> > Simplifying... Traceback (most recent call last): File "C:\Users\yuanx.conda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Users\yuanx.conda\envs\paddle\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim__main__.py", line 5, in main() File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 444, in main args.tensor_size_threshold, File "C:\Users\yuanx.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 189, in simplify tensor_size_threshold, onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Sigmoid, node name: Sigmoid_0): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 2: (32) vs (-1)
> > 我使用netron 查看 x : -1x3x-1x-1 查看pdmodel文件 x：?x3x?x?
> > 请问这个是什么原因 如何解决
> 
> 先使用paddle2onnx处理下吧，会清除掉原有模型中所有shape信息，再重新进行shape推断，类似下面这样的命令
> 
> ```
> python -m paddle2onnx.optimize --input_model model.onnx  --output_model new_model.onnx  --input_shape_dict "{'image':[1,3,32,480]}"
> ```

我尝试规划了检测网络640X640
`python -m paddle2onnx.optimize --input_model=./ch_PP-OCRv3_det_infer/v3_det.onnx --output_model=./ch_PP-OCRv3_det_infer/new_v3_det.onnx --input_shape_dict="{'x':[1,3,640,640]}"
`

但是我使用onnxsim 还是同样的出现维度的情况
```
python -m onnxsim ./ch_PP-OCRv3_det_infer/new_v3_det.onnx ./ch_PP-OCRv3_det_infer/new_v3_det_sim.onnx

Simplifying...
Traceback (most recent call last):
  File "C:\Users\yuanx\.conda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\yuanx\.conda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\__main__.py", line 5, in <module>
    main()
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 444, in main
    args.tensor_size_threshold,
  File "C:\Users\yuanx\.conda\envs\paddle\lib\site-packages\onnxsim\onnx_simplifier.py", line 189, in simplify
    tensor_size_threshold,
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Constant): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (1) vs (4)
```

**Comment by jiangjiajun** [comment]
```
[08/17/2022-15:08:34] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/17/2022-15:08:34] [W] Dynamic dimensions required for input: x, but no shapes were provided. Automatically overriding shape to: 1x3x1x1
[08/17/2022-15:08:34] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 10.2.2 but loaded cuBLAS/cuBLAS LT 10.2.1
[08/17/2022-15:08:39] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
C:\source\rtSafe\cublas\cublasLtWrapper.cpp:279
Aborting...
[08/17/2022-15:08:39] [E] [TRT] C:\source\rtSafe\cublas\cublasLtWrapper.cpp (279) - Assertion Error in nvinfer1::CublasLtWrapper::getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
[08/17/2022-15:08:39] [E] Engine creation failed
[08/17/2022-15:08:39] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.onnx --saveEngine=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.engine
```

使用paddle2onnx.optimizer处理后，不再用onnx-sim进行处理，而是直接使用trt_exec，是否可行呢

**Comment by SHOUshou0426** [comment]
> ```
> [08/17/2022-15:08:34] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [08/17/2022-15:08:34] [W] Dynamic dimensions required for input: x, but no shapes were provided. Automatically overriding shape to: 1x3x1x1
> [08/17/2022-15:08:34] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 10.2.2 but loaded cuBLAS/cuBLAS LT 10.2.1
> [08/17/2022-15:08:39] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
> C:\source\rtSafe\cublas\cublasLtWrapper.cpp:279
> Aborting...
> [08/17/2022-15:08:39] [E] [TRT] C:\source\rtSafe\cublas\cublasLtWrapper.cpp (279) - Assertion Error in nvinfer1::CublasLtWrapper::getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
> [08/17/2022-15:08:39] [E] Engine creation failed
> [08/17/2022-15:08:39] [E] Engine set up failed
> &&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.onnx --saveEngine=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\v3_det.engine
> ```
> 
> 使用paddle2onnx.optimizer处理后，不再使用onnx-进行处理，改为使用trt_exec，是否直接sim呢



是的，尝试过使用trtexec   同样会给我丢维度的错误，我精度google 查询需要onnxsim 工具进行缩放
```
trtexec.exe --onnx=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\new_v3_det.onnx --saveEngine=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\new_v3_det.engine

----------------------------------------------------------------
Input filename:   C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\new_v3_det.onnx
ONNX IR version:  0.0.8
Opset version:    10
Producer name:    PaddlePaddle
Producer version:
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
[08/18/2022-09:35:35] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[08/18/2022-09:35:40] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
C:\source\rtSafe\cublas\cublasLtWrapper.cpp:279
Aborting...
[08/18/2022-09:35:43] [E] [TRT] C:\source\rtSafe\cublas\cublasLtWrapper.cpp (279) - Assertion Error in nvinfer1::CublasLtWrapper::getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
[08/18/2022-09:35:43] [E] Engine creation failed
[08/18/2022-09:35:43] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\new_v3_det.onnx --saveEngine=C:\Users\yuanx\Desktop\ch_PP-OCRv3_det_infer\new_v3_det.engine
```

**Comment by jiangjiajun** [comment]
升级TensorRT 8.4即可解决
