### ISSUE TITLE
PPOCRLabel支持关系抽取（relation extration) 

### ISSUE THREAD

**Issue by zhangluustb** [PaddlePaddle/PaddleOCR#7227]
可否在PPOCRLabel kie功能中添加关系标注功能？现在有点不方便

**Comment by Evezerest** [comment]
目前在AI Studio上 有一个野生标注方法可以寻找一下，后续会考虑支持

**Comment by lengyueyang** [comment]
> 目前在AI Studio上 有一个野生标注方法可以寻找一下，后续会考虑支持

你好, 能给个连接吗?

**Comment by zhangluustb** [comment]
目前我采用的标注两次的方式:第一次标类别,第二次将同一关系组的key、value标为同一类别,然后通过转换脚本对两次得到的标注文件进行合并

**Comment by taojing7** [comment]
> 目前我采用的标注两次的方式:第一次标类别,第二次将同一关系组的key、value标为同一类别,然后通过转换脚本对两次得到的标注文件进行合并

老哥可以留个联系方式探讨一下吗，一样的任务不太会标注
