### ISSUE TITLE
要识别双栏论文图片文本，是否可以设置识别循序，按照现在的输出出来顺序就混乱了

### ISSUE THREAD

**Issue by doraemonlei** [PaddlePaddle/PaddleOCR#7229]
是否可以设置成从左到右，从上到下的顺序？现在是从上到下，从左到右

**Comment by tink2123** [comment]
输出顺序的优先级可以通过修改源码解决：https://github.com/PaddlePaddle/PaddleOCR/blob/f6072d2222326e87a489247e81f6c9ad0389c24c/tools/infer/predict_system.py#L110

**Comment by noob-ctrl** [comment]
@doraemonlei 请问有方法可以只识别是单栏或者是多栏吗？
