### ISSUE TITLE
如何快速搜集bad case， 然后加入数据集进行增强训练？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7237]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

如何快速搜集bad case， 然后加入数据集进行增强训练？微信nlanguage

**Comment by WenmuZhou** [comment]
可以将错别字收集起来，单独做个语料，然后生成一波数据

**Comment by nissansz** [comment]
比如字母O被识别成0或其他符号，怎么强化？

**Comment by WenmuZhou** [comment]
用v3的模型也有这个问题吗，可以分别造点数据进行训练

**Comment by nissansz** [comment]
如果把中文汉字和日文汉字一起训练，对准确率影响有多大？不至于太低吧？

**Comment by WenmuZhou** [comment]
没试过，你可以试一下

**Comment by nissansz** [comment]
看其他网页的混合识别效果，没太大影响

**Comment by nissansz** [comment]
请教一下，paddle训练时，训练集在多个盘符，怎么样训练，label路径怎么写？

**Comment by WenmuZhou** [comment]
建议放在一个盘符
