### ISSUE TITLE
PPOCRLabel优化建议

### ISSUE THREAD

**Issue by yysirs** [PaddlePaddle/PaddleOCR#7239]
感谢开源PPOCRLabel标注工具，操作起来很方便，在使用的过程中，发现了两个可能的优化点：

- 更新KIE的标注类型，需要移动标注框，才能弹出来保存的选项
- 是否可以将KIE的标注类型做成配置文件，同时可以映射成中文选项，对于实体较多的关系标注会很方便，也减少手误的情况。

再次感谢开源这么好用的标注工具！以上建议，供参考😁😁😁

**Comment by WenmuZhou** [comment]
感谢建议，我们会考虑的
