### ISSUE TITLE
怎样让文本检测后的检测框空格间距更大

### ISSUE THREAD

**Issue by zyx792726304** [PaddlePaddle/PaddleOCR#724]
我在检测的时候，一行的文字通常被两个框检测到，然后就被划分为两句话来进行检测，这样导致我不能做后面的筛选。我想问一下需要修改一些什么参数可以加大这个检测的空格间距。我已经使用了ch_det_r50_vd_db和ch_rec_r34_vd_crnn_enhance。
就像这张图[图片](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs_results/11.jpg)
它的品牌、品名和后面的内容分隔开了，如果我后面想要获取品牌、品名的内容就不好获取。
所以我想问一下怎么加大这个空格检测间距，从而可以使我可以让品牌、品名和后面的内容在一行上。

**Comment by WenmuZhou** [comment]
你可以标注的时候就把这些标注在一起，模型没检测出来可以通过后处理解决

**Comment by zyx792726304** [comment]
> 1. 你可以标注的时候就把这些标注在一起
> 2. 调低后处理的thresh
> 3. 模型没检测出来可以通过后处理解

好的 如果我想让他输出的文字按照图片中的上下文布局来显示（现在模型的文字输出是乱序的） 这个代码中有相关的方法吗还是我得自己写一个

**Comment by WenmuZhou** [comment]
得自己写

**Comment by zcswdt** [comment]
> 我在检测的时候，一行的文字通常被两个框检测到，然后就被划分为两句话来进行检测，这样导致我不能做后面的筛选。我想问一下需要修改一些什么参数可以加大这个检测的空格间距。我已经使用了ch_det_r50_vd_db和ch_rec_r34_vd_crnn_enhance。
> 就像这张图[图片](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs_results/11.jpg)
> 它的品牌、品名和后面的内容分隔开了，如果我后面想要获取品牌、品名的内容就不好获取。
> 所以我想问一下怎么加大这个空格检测间距，从而可以使我可以让品牌、品名和后面的内容在一行上。

我写的对于文字检测框的合并，可以参考一下。https://github.com/zcswdt/merge_text_boxs

**Comment by Hupengyu** [comment]
> > 我在检测的时候，一行的文字通常被两个框检测到，然后就被划分为两句话来进行检测，这样导致我不能做后面的筛选。我想问一下需要修改一些什么参数可以加大这个检测的空格间距。我已经使用了ch_det_r50_vd_db和ch_rec_r34_vd_crnn_enhance。
> > 就像这张图[图片](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs_results/11.jpg)
> > 它的品牌、品名和后面的内容分隔开了，如果我后面想要获取品牌、品名的内容就不好获取。
> > 所以我想问一下怎么加大这个空格检测间距，从而可以使我可以让品牌、品名和后面的内容在一行上。
> 
> 我写的对于文字检测框的合并，可以参考一下。https://github.com/zcswdt/merge_text_boxs

wonderful!!!
thank you very much!!!

**Comment by Hupengyu** [comment]
> > 我在检测的时候，一行的文字通常被两个框检测到，然后就被划分为两句话来进行检测，这样导致我不能做后面的筛选。我想问一下需要修改一些什么参数可以加大这个检测的空格间距。我已经使用了ch_det_r50_vd_db和ch_rec_r34_vd_crnn_enhance。
> > 就像这张图[图片](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/imgs_results/11.jpg)
> > 它的品牌、品名和后面的内容分隔开了，如果我后面想要获取品牌、品名的内容就不好获取。
> > 所以我想问一下怎么加大这个空格检测间距，从而可以使我可以让品牌、品名和后面的内容在一行上。
> 
> 我写的对于文字检测框的合并，可以参考一下。https://github.com/zcswdt/merge_text_boxs

唯一的问题就是对于非水平的平行四边形（paddle_ocr里有很多）的合并并不是很好。容易cut掉一些文字信息
