### ISSUE TITLE
 No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

### ISSUE THREAD

**Issue by TinkingLoeng** [PaddlePaddle/PaddleOCR#7242]
set --benchmark True：
and run paddleocr, it said:
No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

**Comment by WenmuZhou** [comment]
在PaddleOCR目录外运行看看

**Comment by littlerookie** [comment]
执行`paddleocr --image_dir=/data/ppstructure/docs/recovery/recovery_ch.jpg --type=structure --recovery=true`，
也报同样的错`No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package`, 没有在PaddleOCR目录执行

**Comment by alexHxun** [comment]
我也遇到这个问题了，主要是from paddleocr.ppstucture, PPStucture，小写的是module，大写的是OBJECT，官方的教程真的，坑太多了，搞死人
