### ISSUE TITLE
Questions about SAR implementation.

### ISSUE THREAD

**Issue by eshoyuan** [PaddlePaddle/PaddleOCR#7243]
PaddleOCR uses ParallelSARDecoder to implement SAR decoder which can train in parallel. But during inference, it works in sireal. I can understand this is a efficient implement. but I am wondering why this can work? Why the model can inference in a different way from training?

**Comment by eshoyuan** [comment]
Specifically, compared to training in parallel, can train in sireal improve the performance?

**Comment by andyjpaddle** [comment]
In the inference stage, the label is unavailable, so we should decode one by one. But in training stage, we have label information, we can use parallel mode to decode.
