### ISSUE TITLE
图片标准化Normalize::Run，均值和方差顺序

### ISSUE THREAD

**Issue by fzhiheng** [PaddlePaddle/PaddleOCR#7247]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/7245

<div type='discussions-op-text'>

<sup>Originally posted by **fzhiheng** August 18, 2022</sup>
代码位置：deploy/cpp_infer/src/preprocess_op.cpp
```
void Normalize::Run(cv::Mat *im, const std::vector<float> &mean,
                    const std::vector<float> &scale, const bool is_scale) {
  double e = 1.0;
  if (is_scale) {
    e /= 255.0;
  }
  (*im).convertTo(*im, CV_32FC3, e);
  std::vector<cv::Mat> bgr_channels(3);
  cv::split(*im, bgr_channels);
  for (auto i = 0; i < bgr_channels.size(); i++) {
    bgr_channels[i].convertTo(bgr_channels[i], CV_32FC1, 1.0 * scale[i],
                              (0.0 - mean[i]) * scale[i]);
  }
  cv::merge(bgr_channels, *im);
}
```
det.h中设置的`mean_ = {0.485f, 0.456f, 0.406f}`, `scale_ = {1 / 0.229f, 1 / 0.224f, 1 / 0.225f}`，图片读取的是BGR，处理的均值和方差却是RGB？
</div>

**Comment by stq-hydra** [comment]
同样的疑问
在ppocr/data/imaug/operators.py里面，predict_system.py里面使用cv2来读取图片，而normalize的方式是RGB的方式

**Comment by LDOUBLEV** [comment]
换成BRG的顺序也训练过模型，均值方差对最终训练精度基本无影响，如果是在你们的数据集上，可以尝试替换为你们数据集的均值方差
