### ISSUE TITLE
训练出来的模型单行文本或者两行识别不出来，整张图可以识别，

### ISSUE THREAD

**Issue by jiezai18** [PaddlePaddle/PaddleOCR#7248]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![2](https://user-images.githubusercontent.com/82500329/185366065-dde509c9-26f4-42f6-bead-90781f43015c.png)
![3](https://user-images.githubusercontent.com/82500329/185366351-a05a44b9-8784-4316-903c-2526d17aceb0.png)

**Comment by WenmuZhou** [comment]
可以试一下对单行或两行文本的图像做pad

**Comment by yangy996** [comment]
试试这种方式，https://blog.csdn.net/YY007H/article/details/124973777
