### ISSUE TITLE
训练的时候是以整张图进行测试的，可以识别出来，但是想裁剪一行单词或者两行单词就行识别不出来

### ISSUE THREAD

**Issue by jiezai18** [PaddlePaddle/PaddleOCR#7249]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![2](https://user-images.githubusercontent.com/82500329/185370097-1ac5f83c-62ac-437c-b88e-afccbced3310.png)
![1](https://user-images.githubusercontent.com/82500329/185370144-6ae8de0d-556f-4cbc-a4ee-f2b35cb17b2a.png)
![3](https://user-images.githubusercontent.com/82500329/185370210-1a703eaf-f7cf-4517-9a57-35b7586d3fb7.png)

**Comment by WenmuZhou** [comment]
和https://github.com/PaddlePaddle/PaddleOCR/issues/7248 一样，这个我先关了
