### ISSUE TITLE
Word level detection.

### ISSUE THREAD

**Issue by shameem198** [PaddlePaddle/PaddleOCR#7250]
System Environment：Ubuntu 20.04
Version：Paddle：2.3.2   PaddleOCR：2.5

 I trying to get words level detection instead of sentence, already tried couple of experiments by adjusting the value of _det_limit_type_ _det_limit_side_len_ , none of them are giving expected result. Can we integrate EAST/SAST detection model instead of DB ? or any other solution ?

**Comment by WenmuZhou** [comment]
You can label the data for finetune

**Comment by ichenjia** [comment]
Also heavily interested in this. Not sure why it is closed

**Comment by CapturefastCEO** [comment]
> Also heavily interested in this. Not sure why it is closed

I guess it is not an issue.
