### ISSUE TITLE
单个数字识别不是很准确

### ISSUE THREAD

**Issue by tkone2018** [PaddlePaddle/PaddleOCR#7258]
![WechatIMG459 jpeg_result](https://user-images.githubusercontent.com/41476675/185524511-3a670a4a-1591-4dcd-b837-3f74fc178f3d.jpg)

**Comment by littletomatodonkey** [comment]
你好，目前模型对于单字的检测效果确实一般，这种情况需要训练自己的检测模型

**Comment by LDOUBLEV** [comment]
建议使用PPOCRv3检测模型

**Comment by tkone2018** [comment]
@LDOUBLEV 估计只能finetune了，server和v3都试了
