### ISSUE TITLE
some trt inputs dynamic shape info not set

### ISSUE THREAD

**Issue by luohaihan** [PaddlePaddle/PaddleOCR#7260]
dygraph分支开启tensorrt加速，识别的时候用官方的PP-OCRv3-rec会报这个错误，用老版本的不会(但老版本的模型识别不出啥东西来)，是因为PP-OCRv3-rec的某些shape改变了吗

**Comment by littletomatodonkey** [comment]
你好，目前使用了自动收集动态shape的方法，不用我们单独设置了，可以指定`--shape_info_filename=1.txt`，在第一次运行时会先收集动态shape并存储到该文件，第二次运行的时候就会加载该文件的shape信息
