### ISSUE TITLE
re模型参数无法下载

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleOCR#7264]
您好，在使用re预训练模型做预测时，模型参数不能下载，下载链接是：https://bj.bcebos.com/paddlenlp/models/community/pretrain/ser_LayoutXLM_xfun_zh/model_state.pdparams

期待您的回复~谢谢~

**Comment by littletomatodonkey** [comment]
你好，模型下载和使用可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README_ch.md
