### ISSUE TITLE
`Segmentation fault` for text detection

### ISSUE THREAD

**Issue by zhangyingbit** [PaddlePaddle/PaddleOCR#7267]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle： 2.3.2    PaddleOCR： 2.5.0.3  
- 使用检测模型：  
- 问题相关组件/Related components：ppocr/modeling/necks/db_fpn.py   line342  f2 = self.inp_conv[0](out2)
                                          comments: 打印 self.inp_conv[0] 得到 Conv2D(256, 64, kernel_size=[9, 9], padding=4, data_format=NCHW) 
- 运行指令/Command Code：
python3 tools/eval.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml  -o Global.pretrained_model="/data/model/PaddleOCR-release-2.5/en_PP-OCRv3_det_distill_train/best_accuracy" PostProcess.box_thresh=0.5 PostProcess.unclip_ratio=1.5

- 完整报错/Complete Error Message：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   void paddle::imperative::Tracer::TraceOpImpl<paddle::imperative::VarBase>(std::string const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::AttributeMap&, phi::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&, paddle::framework::AttributeMap*, bool)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   phi::KernelImpl<void (*)(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*), &(void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*))>::Compute(phi::KernelContext*)
4   void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, bool, int, bool, phi::DenseTensor*)
5   paddle::operators::math::Im2ColFunctor<(paddle::operators::math::ColFormat)0, phi::CPUContext, float>::operator()(phi::CPUContext const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, paddle::experimental::DataLayout)
6   void paddle::operators::math::im2col_common<float>(phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, paddle::experimental::DataLayout)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1660897771 (unix time) try "date -d @1660897771" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fe41c8f02a0) received by PID 17446 (TID 0x7fec9d453700) from PID 479134368 ***]

Segmentation fault (core dumped)
关于以上问题，比较奇怪的现象是，运行ICDAR2015的测试数据集没有问题，运行我自己的数据集就会报以上错误~

另请教： 如何在configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml 这个设置下评估性能只跑student网络，而不用跑teacher网络，还有两个学生网络student和student2最终使用哪个作为评估指标输出的呢？谢谢~

**Comment by zhangyingbit** [comment]
关于以上问题，比较奇怪的现象是，运行ICDAR2015的测试数据集没有问题，运行我自己的数据集就会报以上错误~

**Comment by littletomatodonkey** [comment]
你好

1. 试着把num worker修改为0，把评估的batch size修改为1，看下呢？
2. 评估的时候会经过所有的网络，这块暂时如果要修改的话，只能修改ocr的源码了，不太方便
3. 目前是以Student模型的输出精度选择模型进行保存，在训练完成导出后，可以使用精度更高的那个，导出的时候会把所有子模型都进行导出的

**Comment by zhangyingbit** [comment]
非常感谢您的回复~
1. 我另外增加了一个实验，将我自己的数据集的图片大小从2479*3542 resize到744*1063，变小后的图像再使用PPOCR进行eval, 以上问题不会再出现，这样是否可以判定paddle实现的conv op有点问题？又或者是我的设备对于大尺度的输入出现内存的一些问题？
2-3. 关于评估这部分，会经过所有的网络teacher, student, student2,  并且现在无法解耦三个模型，已明白，谢谢~

**Comment by zhangyingbit** [comment]
> 你好
> 
> 1. 试着把num worker修改为0，把评估的batch size修改为1，看下呢？
> 2. 评估的时候会经过所有的网络，这块暂时如果要修改的话，只能修改ocr的源码了，不太方便
> 3. 目前是以Student模型的输出精度选择模型进行保存，在训练完成导出后，可以使用精度更高的那个，导出的时候会把所有子模型都进行导出的

非常感谢您的回复~

1. 我另外增加了一个实验，将我自己的数据集的图片大小从24793542 resize到7441063，变小后的图像再使用PPOCR进行eval, 以上问题不会再出现，这样是否可以判定paddle实现的conv op有点问题？又或者是我的设备对于大尺度的输入出现内存的一些问题？
2-3. 关于评估这部分，会经过所有的网络teacher, student, student2, 并且现在无法解耦三个模型，已明白，谢谢~

**Comment by littletomatodonkey** [comment]
这块应该是图片太大，导致内存或者显存不够了，eval的时候是用原图做的eval，所以这块图大了，对于计算的要求比较高哈

**Comment by zhangyingbit** [comment]
谢谢，后来发现是A100的卡需要8.0以上cudnn才可以，我用的是7.x版本，再次感谢
