### ISSUE TITLE
python环境下在本地化部署的过程中 ，如何在完全离线的情况下安装检测服务模块

### ISSUE THREAD

**Issue by zengqingyun** [PaddlePaddle/PaddleOCR#727]
ocr_system、ocr_rec、ocr_det，有网可以在hub install + 路径来安装，离线模式下应该怎么安装

**Comment by WenmuZhou** [comment]
@LDOUBLEV 大佬解答一下

**Comment by qypf** [comment]
不太明白你的安装检测服务是什么意思，如果你是一个离线的环境，想要使用python及ocr代码，可以先在一个联网的机器上安装好python和依赖的包，通过pip freeze > requirements.txt，导出当前python环境的所有依赖包。然后再
pip download -d packagesdir -r requirements.txt ，可以将所有依赖包下载到本地的packagesdir的文件夹内。然后把python安装包，packagesdir和requirements.txt传输到离线的电脑上，按照先安装python，再pip install --no-index --ignore-installed --find-links=packagesdir -r requirements.txt就可以完成所有的安装了。

**Comment by andrewleo** [comment]
没网的情况下，hub install，hub serving会挂起很久啊。。居然需要网络？谁能来回答下啊

**Comment by Ycj199682** [comment]
> 

大佬，请教一下，那在离线的那台机器上应该还是无法执行 hub serving start 命令吧，有其他启动方式吗
