### ISSUE TITLE
What is input "ignore_tags"?

### ISSUE THREAD

**Issue by HariWu1995** [PaddlePaddle/PaddleOCR#7270]
Hi,

I am trying to use only PGNet without full PaddleOCR library but I have some difficulties.
When I see this [End-to-end tutorial](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/algorithm_e2e_pgnet_en.md), I see groundtruth file containing only transcription and points like this:

> " Image file name             Image annotation information encoded by json.dumps"
rgb/img11.jpg    [{"transcription": "ASRAMA", "points": [[214.0, 325.0], [235.0, 308.0], [259.0, 296.0], [286.0, 291.0], [313.0, 295.0], [338.0, 305.0], [362.0, 320.0], [349.0, 347.0], [330.0, 337.0], [310.0, 329.0], [290.0, 324.0], [269.0, 328.0], [249.0, 336.0], [231.0, 346.0]]}, {...}]

Next, I see in PGDataset file that there are some fields like
https://github.com/PaddlePaddle/PaddleOCR/blob/eed3d6aaa21b6b793532f19e2af87e53c448e616/ppocr/data/pgnet_dataset.py#L89

However, I see in preprocessing file, there are different fields
https://github.com/PaddlePaddle/PaddleOCR/blob/eed3d6aaa21b6b793532f19e2af87e53c448e616/ppocr/data/imaug/pg_process.py#L753

Please tell me which modules between PGdataset and PGProcess I have missed. 

The purpose I need to do this is I want to combine OCR, KIE, and spatial dependency parsing problems into 1 end-to-end solution where I can re-use feature maps from the same backbone like Resnet to reduce weights.

**Comment by MissPenguin** [comment]
'ignore_tags' means to ignore the corresponding area, generally for small or blurred text areas that are unrecognizable. Some datasets are marked with such regions and labels, and some do not, generally having little impact.
