### ISSUE TITLE
统一机器同一环境结果不同

### ISSUE THREAD

**Issue by shihai-black** [PaddlePaddle/PaddleOCR#7271]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：python3.8 Paddle：2.3.1.post112  PaddleOCR：2.5.0.3 

第一种写法
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang='en) 
ocr.ocr('tmp.png')   # 结果为空

第二种写法
paddleocr --image_dir "tmp.png" --use_angle_cls true --lang en --use_gpu false  # 有结果且正确

跪求可能原因

**Comment by MissPenguin** [comment]
我这边测试是一致的，方便把你这个不一致的图发出来我测一下吗
