### ISSUE TITLE
ppocrV2 rec模型参数冻结

### ISSUE THREAD

**Issue by JunYao1020** [PaddlePaddle/PaddleOCR#7274]
我有少量数据，想使用ppocrV2的rec模型作为预训练模型进行迁移学习。我希望只训练softmax，该怎么做呢？
根据我了解的配置，在配置文件里设置 freeze_params=true 是否能满足我的需求？

希望得到解答

**Comment by LDOUBLEV** [comment]
softmax没有参数，你是想只训练最后一层fc？
在配置文件里设置 freeze_params=true 不行的，

如果要设置不训练哪些参数，需要把参数的trainable设置为False，参考
 for param in model.parameters():
       param.trainable = False

**Comment by JunYao1020** [comment]
> softmax没有参数，你是想只训练最后一层fc？ 在配置文件里设置 freeze_params=true 不行的，
> 
> 如果要设置不训练哪些参数，需要把参数的trainable设置为False，参考 for param in model.parameters(): param.trainable = False

好的，感谢
