### ISSUE TITLE
对于arm linux，如何利用两个.nb文件进行识别

### ISSUE THREAD

**Issue by boceng** [PaddlePaddle/PaddleOCR#728]
如题，OCR文档只提供了android机型的demo，我这里想在arm linux平台进行终端部署后使用python预测，而非Android，检测等paddle系列都可参考[mobilenetv1_light_api.py](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_light_api.py)进行更改并在终端使用，所以请问OCR的两个转换文件如何进行使用？

**Comment by WenmuZhou** [comment]
py的调用和cpp差不多，repo里有现成的后处理和预处理可以copy，只需要把加载模型和预测的部分换掉即可

**Comment by boceng** [comment]
您好，您具体指哪个cpp的repo？[这里？](https://paddle-lite.readthedocs.io/zh/latest/quick_start/cpp_demo.html#id11)，该如何把两个模型导入呀，我看mobileconfig仅提供set_model_from_file、set_model_dir，我都尝试导入db和crnn的模型，但实际却不能用啊，麻烦您具体给讲解一下吧，感谢。

	def read_img(im_path, resize_h, resize_w):
		im = cv2.imread(im_path).astype('float32') 
		im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
		h, w, _ = im.shape
		im_scale_x = resize_h / float(w)
		im_scale_y = resize_w / float(h)
		out_img = cv2.resize(im, None, None, fx=im_scale_x, fy=im_scale_y, interpolation=cv2.INTER_CUBIC)
		# mean = np.array([0.485, 0.456, 0.406]).reshape((1, 1, -1))
		# std = np.array([0.229, 0.224, 0.225]).reshape((1, 1, -1))
		mean = np.array([0.5, 0.5, 0.5]).reshape((1, 1, -1))
		std = np.array([0.5, 0.5, 0.5]).reshape((1, 1, -1))
		out_img = (out_img / 255.0 - mean) / std  # z-score
		out_img = out_img.transpose((2, 0, 1))
		return out_img


	def RunModel(args):
		# 1. Set config information
		config = MobileConfig()
		config.set_model_from_file(args.model_path1)
		config.set_model_from_file(args.model_path2)
		# config.set_model_dir(args.model_dir)

		# 2. Create paddle predictor
		predictor = create_paddle_predictor(config)

		# 3. Read image
		height, width = 640, 640
		image_data = read_img(args.img_data, height, width).flatten()
		# image = Image.open(args.img_data)
		# resized_image = image.resize((height, width), Image.BILINEAR)
		# image_data = np.array(resized_image).flatten().tolist()

		# 4. Set input data
		input_tensor = predictor.get_input(0)
		input_tensor.resize([1, 3, height, width])
		input_tensor.set_float_data(image_data)

		# 5. Run model
		predictor.run()

		# 6. Get output data
		output_tensor = predictor.get_output(0)

**Comment by boceng** [comment]
> py的调用和cpp差不多，repo里有现成的后处理和预处理可以copy，只需要把加载模型和预测的部分换掉即可

您好，这是我目前使用的预测代码，有几点疑问：
1. 针对db.nb，其输出是shape为[1, 3, 640, 640]的list，那么该怎么提取出检测框？
2. 针对crnn.nb，其输入的height, width是否为32, 100？其输出应是什么形式？（我的是shape[1, 1]，值为nan）
3. 两种模型的预处理是否都用read_img()？
 感谢您在百忙之中回复~ @WenmuZhou 

	def read_img(im_path, resize_h, resize_w):
		im = cv2.imread(im_path).astype('float32')
		im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
		h, w, _ = im.shape
		im_scale_x = resize_h / float(w)
		im_scale_y = resize_w / float(h)
		out_img = cv2.resize(im, None, None, fx=im_scale_x, fy=im_scale_y, interpolation=cv2.INTER_CUBIC)
		mean = np.array([0.485, 0.456, 0.406]).reshape((1, 1, -1))
		std = np.array([0.229, 0.224, 0.225]).reshape((1, 1, -1))
		out_img = (out_img / 255.0 - mean) / std  # z-score
		out_img = out_img.transpose((2, 0, 1))
		return out_img


	def RunModel(args):
		# 1. Set config information
		config = MobileConfig()
		config.set_model_from_file(args.model_dir1)
		# config.set_model_from_file(args.model_dir2)

		# 2. Create paddle predictor
		predictor = create_paddle_predictor(config)

		# 3. Read image
		height, width = 640, 640
  		# height, width = 32, 100
   		image_data = read_img(args.img_data, height, width).flatten()
    		# image = Image.open(args.img_data)
    		# resized_image = image.resize((height, width), Image.BILINEAR)
    		# image_data = np.array(resized_image).flatten().tolist()

    		# 4. Set input data
    		input_tensor = predictor.get_input(0)
    		input_tensor.resize([1, 3, height, width])
    		input_tensor.set_float_data(image_data)

    		# 5. Run model
    		t1 = time.time()
    		predictor.run()
    		print(time.time() - t1)

    		# 6. Get output data
    		output_tensor = predictor.get_output(0)
    		print(output_tensor.shape())
    		res = output_tensor.float_data()
    		print(res[:10])
    		res = np.array(res)
    		res = np.reshape(res, (3, 640, 640))
    		print(res)

**Comment by WenmuZhou** [comment]
模型的加载参考这里https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/ocr_db_crnn.cc#L301-L308
数据处理参考这里
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/predict_rec.py#L62-L80

**Comment by boceng** [comment]
> 模型的加载参考这里https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/ocr_db_crnn.cc#L301-L308
> 数据处理参考这里
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/data/det/db_process.py
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/predict_rec.py#L62-L80

您好，不好意思我昨天更新了上一个回复，数据预处理和模型加载现在没问题，我现在想知道输出信息如何进行组织使用呀
@WenmuZhou

**Comment by WenmuZhou** [comment]
也是参考cpp里的

**Comment by boceng** [comment]
> 也是参考cpp里的

您好，请问[传送门](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/lite/ocr_db_crnn.cc#L278-L281) 这里为什么只取第一个通道的像素值，输出tensor的shape是(1, 3, h, w)，且我实现出输出仅有第二个通道是可用的数值(如2.3e-1， 3.2e-1)，而其它通道都是极小的数值(如2.3e-10，2.3e-33)。

对于图像的预处理，我完全遵循cpp的处理方式。
@WenmuZhou

**Comment by WenmuZhou** [comment]
第一个通道是分割图，第二个通道是二值化的阈值
