### ISSUE TITLE
KeyError: 'token_type_ids'

### ISSUE THREAD

**Issue by zhangjuncheng24** [PaddlePaddle/PaddleOCR#7280]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.4 
- 版本号/Version：Paddle：  PaddleOCR： 2.5  问题相关组件/Related components：VQA 文档视觉问答
- 运行指令/Command Code：CUDA_VISIBLE_DEVICES=0 python tools/infer_vqa_token_ser.py -c configs/vqa/ser/layoutxlm.yml -o Architecture.Backbone.checkpoints=inference/ser_LayoutXLM_xfun_zh/ Global.infer_img=images/images_0.png

- 完整报错/Complete Error Message：
- 
![捕获](https://user-images.githubusercontent.com/111550104/185838240-d248cc59-5ea5-4aa7-b990-e78ff9b2c4f6.PNG)

**Comment by andyjpaddle** [comment]
可以在这里加一个参数：https://github.com/PaddlePaddle/PaddleOCR/blob/eed3d6aaa21b6b793532f19e2af87e53c448e616/ppocr/data/imaug/label_ops.py#L920

return_token_type_ids=True

**Comment by sattychen** [comment]
我也碰到类似问题

**Comment by zhangjuncheng24** [comment]
按大佬的方法就解决了

**Comment by littletomatodonkey** [comment]
代码中的bug已经修复，也可以拉下最新代码使用哈
