### ISSUE TITLE
Arabic Model results is very Bad

### ISSUE THREAD

**Issue by Mahmuod1** [PaddlePaddle/PaddleOCR#7287]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：in google colab and implement the installation in this link [installation instructions](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/quickstart_en.md#11-install-paddlepaddle)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddel
- 运行指令/Command Code：
- from paddleocr import PaddleOCR
ocr=PaddleOCR(lang='ar')
res=ocr.ocr('/content/myImage.png')
- 完整报错/Complete Error Message：
not error but the results were not responsible I test paddleocr from months and i think that something is change

**Comment by Topdu** [comment]
Downloading the latest code of dygraph branch, please!

**Comment by Mahmuod1** [comment]
i think it is the same results rather than the Arabic model in  dygraph branch  i think it is overfit because it get text with height scores and the was  worng  i remove the colab session before clone the dygraph branch and install paddlepaddle-gpu again 
and install requirements.txt

**Comment by Topdu** [comment]
Refering the [pr](https://github.com/PaddlePaddle/PaddleOCR/pull/7208) about arabic update.

**Comment by Mahmuod1** [comment]
![Screenshot from 2022-08-22 12-24-07](https://user-images.githubusercontent.com/79579124/185900141-948bcc00-5cce-4922-b956-2bf9a5c1c2c5.png)
![Screenshot from 2022-08-22 12-24-03](https://user-images.githubusercontent.com/79579124/185900128-ac906a73-9b6a-4c5b-8210-377f67a62bd4.png)

**Comment by MohieEldinMuhammad** [comment]
i'm having the same issue, if you figured out the solution please share it here

**Comment by andyjpaddle** [comment]
After pulling the latest code, you can build your own package and install following this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/whl_en.md#11-install-package

**Comment by tink2123** [comment]
> If you please, how can i use this update ? pip install the package do not include this new Arabic function.

Try to update paddleocr==2.6.0.1

**Comment by Mahmuod1** [comment]
thanks the issue solved
