### ISSUE TITLE
PGNet端到端算法模型

### ISSUE THREAD

**Issue by lin-0015** [PaddlePaddle/PaddleOCR#7296]
您好~想请问一下这种情况:
PGNet端到端算法模型,训练出来的模型测试时会出现的情况,有时会出现尾部字符组装到头部的情况,举例: 弯曲文本"ABCDEFG123"识别为"123ABCDEFG".
想问一下有可能是什么环节的原因造成的这种情况?
谢谢

**Comment by LDOUBLEV** [comment]
预测的图像可以发出来看下吗

这个现象不是通用问题吧

**Comment by lin-0015** [comment]
> 预测的图像可以发出来看下吗
> 
> 这个现象不是通用问题吧

我只能举下例子:
是自己标注大量数据后用预训练模型跑出来的模型,实际那图片(完全不参与评估等)测准确率大概有86%左右
每张图片的数据标注均使用14点标注且只有一个检测框

**Comment by LDOUBLEV** [comment]
pgnet预测的时候有判断文字方向，出现部分文字颠倒的情况有点奇怪，可以可视化分析下，我这边没有数据找不出来问题

**Comment by lin-0015** [comment]
> pgnet预测的时候有判断文字方向，出现部分文字颠倒的情况有点奇怪，可以可视化分析下，我这边没有数据找不出来问题

好的,谢谢
