### ISSUE TITLE
linux 环境安装 paddleocr lmdb错误

### ISSUE THREAD

**Issue by wxy521131418** [PaddlePaddle/PaddleOCR#730]
Collecting lmdb
  Using cached lmdb-1.0.0.tar.gz (876 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5myjdq92/lmdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5myjdq92/lmdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4lbn191h
         cwd: /tmp/pip-install-5myjdq92/lmdb/
    Complete output (7 lines):
    sh: /usr/bin/patch: 没有那个文件或目录
    py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5myjdq92/lmdb/setup.py", line 119, in <module>
        raise Exception('Applying patch failed')
    Exception: Applying patch failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(base) [root@localhost PaddleOCR-develop]#

**Comment by WenmuZhou** [comment]
这属于安装lmdb的错误，麻烦百度一下相关错误

**Comment by ezio1320** [comment]
我遇到相同的问题，是lmdb的下载版本问题。
如果是python 3.6 ，尝试pip install lmdb==0.98

**Comment by ibetsun** [comment]
apt install patch

**Comment by Hukongtao** [comment]
> apt install patch

yum -y install patch
