### ISSUE TITLE
运行PPOCRLabel --lang ch 报错

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleOCR#7303]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境 red-hat 4.8.5-28
- 版本号/Version：Paddlepaddle-gpu 2.3.0：  PaddleOCR 2.5.0.3： 
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：
- libxcb-icccm.so.4 :cannot open shared objectfile : no such file or dictionary

在百度搜索中查找问题“libxcb-icccm.so.4 :cannot open shared objectfile : no such file or dictionary”，是因为缺少链接库libxcb-icccm4。目前问题是，没有找到在red-hat系统下安装libxcb-icccm4的命令。请问，可以提供libxcb-icccm4包或者安装命令吗？

**Comment by sattychen** [comment]
需要安装X 软件包
PPOCRLabel不建议linux上安装，在windows上安装更方便
