### ISSUE TITLE
Does PaddleOCR GPU mode support Windows 11?

### ISSUE THREAD

**Issue by xunlongjun** [PaddlePaddle/PaddleOCR#7310]
If someone succeed I hope you can tell me what versions you used. Thanks.

**Comment by XiaokangLei** [comment]
yes!

System:
  版本	Windows 11 专业版
  版本	21H2
  操作系统版本	22000.856
GPU:
  NVIDIA GeForce MX450
  CUDA Version: 11.6
  Driver Version: 511.65
ENV:
  paddlepaddle-gpu==2.3.0.post112
  paddleocr==2.4.0.4

**Comment by xunlongjun** [comment]
> yes!
> 
> System: 版本 Windows 11 专业版 版本 21H2 操作系统版本 22000.856 GPU: NVIDIA GeForce MX450 CUDA Version: 11.6 Driver Version: 511.65 ENV: paddlepaddle-gpu==2.3.0.post112 paddleocr==2.4.0.4

Thanks! I'll try this
