### ISSUE TITLE
文本检测的ResNet-18网络修改为可变性卷积

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#7311]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：文本检测
- 运行指令/Command Code：
- 完整报错/Complete Error Message：ValueError: (InvalidArgument) output height must equal to offset map height. The difference is [158]: [160]
  [Hint: Expected output_shape[2] == offset_dims[2], but received output_shape[2]:158 != offset_dims[2]:160.] (at ..\paddle\phi\infermeta\multiary.cc:764)
  [operator < deformable_conv > error]

原本的ResNet-18采用的普通卷积操作，想要修改为可变性卷积（ppocr/modeling/backbones/det_resnet_vd），修改卷积层代码如下：
class D_ConvBNLayer(nn.Layer):
    def __init__(
            self,
            in_channels,
            out_channels,
            kernel_size,
            stride=1,
            groups=1,
            is_vd_mode=False,
            act=None,
            name=None, ):
        super(D_ConvBNLayer, self).__init__()

        self.is_vd_mode = is_vd_mode
        self._pool2d_avg = nn.AvgPool2D(
            kernel_size=2, stride=2, padding=0, ceil_mode=True)
        self._offset = nn.Conv2D(in_channels=in_channels, out_channels=18, kernel_size=3, stride=1, padding=1)
        self._mask = nn.Conv2D(in_channels=in_channels, out_channels=9, kernel_size=3, stride=1, padding=1)
        self._conv = paddle.vision.ops.DeformConv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size
            # stride=stride,
            # padding=(kernel_size - 1) // 2,
            # groups=groups,
            # weight_attr=ParamAttr(name=name + "_weights"),
            # bias_attr=False
            )
        if name == "conv1":
            bn_name = "bn_" + name
        else:
            bn_name = "bn" + name[3:]
        self._batch_norm = nn.BatchNorm(
            out_channels,
            act=act,
            param_attr=ParamAttr(name=bn_name + '_scale'),
            bias_attr=ParamAttr(bn_name + '_offset'),
            moving_mean_name=bn_name + '_mean',
            moving_variance_name=bn_name + '_variance')

    def forward(self, inputs):
        if self.is_vd_mode:
            inputs = self._pool2d_avg(inputs)
        offsets = self._offset(inputs)
        print("offsets:", offsets.shape)
        masks = self._mask(inputs)
        print("masks:", masks.shape)
        y = self._conv(inputs, offsets, masks)
        y = self._batch_norm(y)
        return y

报错为：
ValueError: (InvalidArgument) output height must equal to offset map height. The difference is [158]: [160]
  [Hint: Expected output_shape[2] == offset_dims[2], but received output_shape[2]:158 != offset_dims[2]:160.] (at ..\paddle\phi\infermeta\multiary.cc:764)
  [operator < deformable_conv > error]

**Comment by LDOUBLEV** [comment]
如果要使用DCN，可以参考现成的DCN代码：https://github.com/PaddlePaddle/PaddleOCR/blob/236fd61131f8e8d2bb76778247cac88d5bf3fe2e/ppocr/modeling/backbones/det_resnet_vd.py#L126

**Comment by InferMaster** [comment]
> 如果要使用DCN，可以参考现成的DCN代码：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/236fd61131f8e8d2bb76778247cac88d5bf3fe2e/ppocr/modeling/backbones/det_resnet_vd.py#L126

好的谢谢，我下载新最新版本的代码参考下！
