### ISSUE TITLE
ppocrv3可以使用python pipeline部署吗

### ISSUE THREAD

**Issue by JunYao1020** [PaddlePaddle/PaddleOCR#7313]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：  PaddleOCR： PaddlePaddle2.3 PaddleOCR2.5
想体验一下ppocrv3升级带来的提升，请问ppocrv3可以使用python pipeline部署吗

**Comment by BeyondYourself** [comment]
paddleocr.py就是pipeline吧，如果想要服务化，还可以用serving的pipeline

**Comment by JunYao1020** [comment]
> paddleocr.py就是pipeline吧，如果想要服务化，还可以用serving的pipeline

对，我想了解的就是能否用serving的pipeline进行服务化部署，因为我印象中OCR的serving好像只支持CRNN的算法

**Comment by WenmuZhou** [comment]
支持的
