### ISSUE TITLE
PP-OCRv3检测模型无法完整地检测出文本框

### ISSUE THREAD

**Issue by wujushan** [PaddlePaddle/PaddleOCR#7318]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Android
- 版本号/Version：release/2.5 

下载**中英文超轻量PP-OCRv3**模型中的**检测模型**进行文本检测，出现下图所示的检测结果。请问，针对这种问题，有什么好的解决办法? 谢谢。

![ch_ppocr_v3_det](https://user-images.githubusercontent.com/12782418/186349613-9f368181-425f-403c-abe7-6e18e6a16706.png)

**Comment by XiaokangLei** [comment]
增加这种数据集fine-tune训练

**Comment by guaguablue** [comment]
> 增加这种数据集fine-tune训练
我用的也是相同的的模型，也出现类似的问题，请问应该如何调优呢？
1. 需要多少图片来进行调优训练？
2. 需要对新增的数据集训练多少轮？
3. 配置参数是否需要修改？
感谢！

**Comment by XiaokangLei** [comment]
> > 增加这种数据集fine-tune训练
> > 我用的也是相同的的模型，也出现类似的问题，请问应该如何调优呢？
> 
> 1. 需要多少图片来进行调优训练？
> 2. 需要对新增的数据集训练多少轮？
> 3. 配置参数是否需要修改？
>    感谢！

500张左右，参数可以先不变，根据loss变化再调，200epoch以内我测的效果就提升不少
