### ISSUE TITLE
按照repo里面的Python预测引擎推理， 在cpu上执行为什么比repo中的慢很多

### ISSUE THREAD

**Issue by MHX1203** [PaddlePaddle/PaddleOCR#732]
志强处理器(Xeon(R) Platinum 8163 CPU @ 2.50GHz)，使用了mkl加速， 最长边设置为480。单张图片处理用时超过**1 S**。为什么会这么慢呢， 有没有什么解决办法。

**Comment by tink2123** [comment]
您单图中的文本框大概有多少呢？如果框很多的话，也是会影响预测速度的

**Comment by littletomatodonkey** [comment]
可以试下在linux上，适当调大线程数（默认为6，可以设置为10，进一步加速），此外测试的时候第一张图片都是很慢的。如果测速度，需要把前几张图片的测试时间忽略掉。
