### ISSUE TITLE
paddle inference 生成解决方案出现问题

### ISSUE THREAD

**Issue by SHOUshou0426** [PaddlePaddle/PaddleOCR#7326]
系统：win10
ocr版本：paddleocr v2.5
paddleinference版本：avx_mkl_cuda10.2_cudnn7.6.5_avx_mkl-trt7.0.0.11
cuda：cuda10.2
TensorRT8
vs2019

错误
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“setlocal
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mklml/lib/mklml.dll ./mklml.dll
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mklml/lib/libiomp5md.dll ./libiomp5md.dll
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mkldnn/lib/mkldnn.dll ./mkldnn.dll
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mklml/lib/mklml.dll ./release/mklml.dll
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mklml/lib/libiomp5md.dll ./release/libiomp5md.dll
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different E:/OCR/paddle_inference/paddle/lib/third_party/install/mkldnn/lib/mkldnn.dll ./release/mkldnn.dll
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd”已退出，代码为 1。	ppocr	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155	

尝试过使用管理员进行编译同样出现这个错误、去查看链接后的事件路径没有任何问题，

**Comment by WenmuZhou** [comment]
使用的是release模式吗

**Comment by SHOUshou0426** [comment]
> 使用是释放模式吗

是的，目前我已经解决了，可以问一下源码编译paddle  会出现内存沾满的情况嘛 编译到70% 内存条16+16 占满100%

**Comment by WenmuZhou** [comment]
我没编译过paddle，你可以去paddle问一下

**Comment by xwzheng1020** [comment]
分享个案例，我自己在编译paddleseg时也有类似错误，然后我的问题是，setlocal命令去拷贝了不存在的dll导致的（怀疑是cmake拿写的有问题）。具体的修正方法是：在 `项目属性 -> 配置属性 -> 生成事件 -> 生成后事件 : 命令行` 中，找到出错的拷贝命令，然后删掉。
