### ISSUE TITLE
SRN的中文识别训练效果不行

### ISSUE THREAD

**Issue by hao6699** [PaddlePaddle/PaddleOCR#733]
你好, 我使用SRN训练了8个epoch, 在自己的中文数据集上(约300W)准确率只能达到85%左右, 但是基于CTC的模型却能达到90%以上. 请问你们有什么训练技巧吗? 比如之前提到的单独训练GSRM模块, 训练时文本数据的输入要进行扰动吗?

**Comment by tink2123** [comment]
请问模型还在收敛吗？是否可以再多迭代一段时间观察呢？可以尝试两阶段训练，先训练pvam模块，再训练gsrm，训练时应该要加入扰动的，会有一定的效果提升

**Comment by hao6699** [comment]
loss在震荡, 应该是达到了局部最优值. 您说的训练grsm是指单独训练grsm还是加入pvam一起训练gsrm呢? 我的想法是单独训练grsm的话, 那些输入的语料要进行扰动. 比如输入'我在餐吃饭'---输出'我在餐厅吃饭'

**Comment by ccx1997** [comment]
为啥我发现语义模块几乎没什么作用
