### ISSUE TITLE
识别间隔较大的文本行

### ISSUE THREAD

**Issue by Lingyun0109** [PaddlePaddle/PaddleOCR#7336]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

如何能同时较好地识别间隔小和间隔大的文本行呢？横排或者竖排文字
例如这里的“科 室”间隔很大，但是不是按单个字识别的
![图片](https://user-images.githubusercontent.com/93696768/186425648-0f224c80-a151-471d-a482-dc07f5c860d4.png)

可以通过调整一些参数实现吗？

**Comment by LDOUBLEV** [comment]
识别是按照文本框为单位识别，如果如果间隔大的文字在同一个文本框内，识别的时候识别一次就行；
如果不在一个文本框内，会逐个识别出每个文本框内的文字。

**Comment by genghaifei** [comment]
这种感觉应该需要从识别的结果，通过位置以及语义信息结合来进行文字信息重排。达到预期效果，没有语义参与应该不行。或者你是某一种特殊垂类，那直接根据此垂类常用词进行判断合并。
