### ISSUE TITLE
在vs 2022环境下编译paddle OCR  提示：error C3861: “mkdir”: 找不到标识符

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#7338]
下载：
1.paddle source
2.paddle model
3.paddle 推理库
4.opencv

进行cmake配置后，合适vs2022对ppocr编译时提示如上错误，出错代码如下：

  if (!Utility::PathExists(FLAGS_output) && FLAGS_det) {
###     mkdir(FLAGS_output.c_str(), 0777);  //请问如何解决？
  }

**Comment by GreatV** [comment]
> 下载： 1.paddle source 2.paddle model 3.paddle 推理库 4.opencv
> 
> 进行cmake配置后，合适vs2022对ppocr编译时提示如上错误，出错代码如下：
> 
> if (!Utility::PathExists(FLAGS_output) && FLAGS_det) {
> 
> ### mkdir(FLAGS_output.c_str(), 0777); //请问如何解决？
> }

windows api下没有`mkdir`，只有一个`_mkdir`，linux下`<sys/stat.h>`有mkdir。

**Comment by iknow34languages** [comment]
最后修改如下：
头文件增加
#ifdef _WIN32
#include <direct.h>
#else
#include <sys/stat.h>
#endif

代码修改如下：
#ifdef _WIN32
      _mkdir(FLAGS_output.c_str());
#else
      mkdir(path.c_str(), 0777);
#endif // !_WIN32

**Comment by WenmuZhou** [comment]
ok了吗

**Comment by hiroi-sora** [comment]
> 最后修改如下： 头文件增加 #ifdef _WIN32 #include <direct.h> #else #include <sys/stat.h> #endif
> 
> 代码修改如下： #ifdef _WIN32 _mkdir(FLAGS_output.c_str()); #else mkdir(path.c_str(), 0777); #endif // !_WIN32

附议。改为3楼的写法后正常编译。其实在utility.cpp中有相同的语句，可能是开发者写paddlestructure.cpp表格识别部分时没考虑到window的情况，希望修正 @WenmuZhou

**Comment by WenmuZhou** [comment]
最新代码已统一
