### ISSUE TITLE
单张图片推理速度过慢， 有没有什么方法验证mkldnn是否生效呢

### ISSUE THREAD

**Issue by MHX1203** [PaddlePaddle/PaddleOCR#734]
基于python的推理速度过慢， 单张图片推理时间超过**1s**，请问有没有什么方法可以验证**mkldnn**是否生效呢， 我想测试一下是不是mkl没有用到。

**Comment by tink2123** [comment]
单张图片测试时，由于包含了模型的启动时间，所以耗时较大，在测试速度时请使用多张图片，或单张图片循环测试多次，并去除掉第一张图片的运行时间。

您可以安装开启mkldnn版本的paddle，并在测试时打开 mkldnn 开关，观察速度变化。

**Comment by luo1994** [comment]
真的慢啊，这个速度，不能忍

**Comment by grasswolfs** [comment]
文档中提供了测试环境下的benchmark，可以作为参考。
由于帖子时间过长，没有进一步收到信息回复，暂时关闭，如果仍然有问题可以reopen
感谢对于PaddleOCR的支持
