### ISSUE TITLE
尺度变化大文本识别

### ISSUE THREAD

**Issue by Lingyun0109** [PaddlePaddle/PaddleOCR#7341]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

字体很大和字体很小同时存在的情况下，大文本行中的空格就识别不出来了，文本行检测不全。应该怎么调整呢？

**Comment by littletomatodonkey** [comment]
这块确实比较难，建议是根据你的场景重新训练检测模型哈
