### ISSUE TITLE
paddleocr2.6中，kie的ser/re，使用了XFUN/class_list_xfun.txt，但原始的XFUN数据集里没有这个问题，请问这个文件是谁生成的吗？

### ISSUE THREAD

**Issue by sattychen** [PaddlePaddle/PaddleOCR#7342]
paddleocr也没发布这个文件，请问有谁清楚这个文件是哪儿来的吗？从哪儿可以拿到？

**Comment by sattychen** [comment]
需要重新下XFUND数据集，请知

**Comment by wujushan** [comment]
@sattychen 可否提供一下XFUND数据集的下载地址

**Comment by sattychen** [comment]
用2.6版本的链接重新下就可以了。https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar
