### ISSUE TITLE
编译完成后的ppocr.exe 有无使用教程

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#7350]
编译得到的ppocr.exe 请问是否有完整的使用教程 

网上搜到的都不详细，以至于无法正常使用

例如：ppocr.exe system --rec_model_dir=F:\paddleOcr\models\ch_ppocr_mobile_v2.0_rec_infer --det_model_dir=F:\paddleOcr\models\ch_ppocr_mobile_v2.0_det_infer --image_dir=F:\paddleOcr\PaddleOCR-release-2.6\doc\imgs\1.jpg

无法使用

**Comment by iknow34languages** [comment]
如下：也未见识别结果输出
F:\paddleOcr\PaddleOCR-release-2.6\deploy\cpp_infer\build\Debug>ppocr.exe --rec_model_dir=F:\paddleOcr\models\ch_ppocr_mobile_v2.0_rec_infer --det=false --rec=true --cls=false --image_dir=F:\paddleOcr\PaddleOCR-release-2.6\doc\imgs_words\ch\word_1.jpg
In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320',if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

F:\paddleOcr\PaddleOCR-release-2.6\deploy\cpp_infer\build\Debug>

**Comment by WenmuZhou** [comment]
参考这里的命令https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/readme_ch.md#23-%E8%BF%90%E8%A1%8Cdemo

**Comment by iknow34languages** [comment]
> 参考这里的命令https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/readme_ch.md#23-%E8%BF%90%E8%A1%8Cdemo

上面是参考这个连接的指令 ：
ppocr.exe --rec_model_dir=F:\paddleOcr\models\ch_ppocr_mobile_v2.0_rec_infer --det=false --rec=true --cls=false --image_dir=F:\paddleOcr\PaddleOCR-release-2.6\doc\imgs_words\ch\word_1.jpg

除了输出：
In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320',if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

未见识别的结果文字打印  请问如何排查问题

使用win 10+cpu 版本

**Comment by iknow34languages** [comment]
> 参考这里的命令https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/readme_ch.md#23-%E8%BF%90%E8%A1%8Cdemo

检测：
ppocr.exe --det_model_dir=F:\paddleOcr\models\ch_ppocr_mobile_v2.0_det_infer --image_dir=F:\paddleOcr\PaddleOCR-release-2.6\doc\imgs\12.jpg --det=true --rec=false

返回为空，未提示任何报错

**Comment by iknow34languages** [comment]
在开始生成解决方案之前，执行下面步骤：

**将Debug改为Release**

Debug 版本可能配置有问题
