### ISSUE TITLE
KIE 中RE训练，会丢弃超过512字的实体关系对

### ISSUE THREAD

**Issue by yysirs** [PaddlePaddle/PaddleOCR#7359]
![image](https://user-images.githubusercontent.com/43271630/186629783-afa13e6e-3e29-41e2-bcb4-650c26b0ffab.png)
如果表格中文字信息较为丰富，字体关系在表格的靠后位置中。则会出现实体关系变成encoded_inputs_all[1]的中数据，
请问，如何保留下来encoded_inputs_all[1]中实体关系数据，让它也参与模型训练。

**Comment by littletomatodonkey** [comment]
你好，目前这块确实还没有考虑大于512的内容，我们记一下，下次更新之前优化下，感谢你的反馈~

**Comment by yysirs** [comment]
SER也有同样的问题，超过512字会被丢弃
![image](https://user-images.githubusercontent.com/43271630/186679010-aba8dff1-0007-49f5-b6a6-6ef75aa27630.png)
感觉这里的逻辑会有些问题，目前区间是(0,512) (512,1024) ,如果实体开始结束位置为(400,900)，两个区间都没办法满足该实体条件，```index <= relation["start_index"]```将这里的代码删除是不是更好点，因为结束位置一定大于开始位置，只用判断结束位置就行。
![image](https://user-images.githubusercontent.com/43271630/186679174-fe4180e7-e47e-4a43-8c7b-c0e821bc708f.png)

**Comment by 122133Liu** [comment]
我的 kie  ser  报错  CUDA error(719), unspecified launch failure  您能帮我看一下吗 付费求指导 请联系我 18909512433 谢谢 如果我挂了 可能以为是骚扰电话 您给我发个信息 我就知道了！

**Comment by yysirs** [comment]
> CUDA error(719), unspecified launch failure 您

https://github.com/PaddlePaddle/Paddle/issues/44107
可以参考一下

**Comment by suonbo** [comment]
> I also found two doubts:
> 
> 1. SER has the same problem, more than 512 words will be discarded
>    ![image](https://user-images.githubusercontent.com/43271630/186679010-aba8dff1-0007-49f5-b6a6-6ef75aa27630.png)
> 2. Entity judgment, I feel that there may be some problems with the logic here. The current interval is (0,512) (512,1024). If the start and end position of the entity is (400,900), neither of the two intervals can satisfy the entity condition. Deleting the code here `index <= relation["start_index"] < index + self.max_seq_len`is Not better, because the end position must be greater than the start position, just judge the end position.
>    ![image](https://user-images.githubusercontent.com/43271630/186679174-fe4180e7-e47e-4a43-8c7b-c0e821bc708f.png)

Did you find any solution?
