### ISSUE TITLE
paddleserving pipeline方式部署，怎么探测服务是否可用

### ISSUE THREAD

**Issue by DequanZhu** [PaddlePaddle/PaddleOCR#7364]
PaddleOCR paddleserving pipeline方式部署，服务OOM了导致服务不可用，但k8s探测9998服务端口仍然无问题，应该是服务挂了，端口依旧在，请问paddle-serving有类似于 tf-serving 那种/healthy服务健康探测的端口吗？

**Comment by tink2123** [comment]
serving 暂时没有～ 只能通过查看日志判断
