### ISSUE TITLE
有的时候识别结果会漏字符，有的时候会多出字符，怎么解决？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7368]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
有的时候识别结果会漏字符，有的时候会多出字符，怎么解决？微信nlanguage

![image](https://user-images.githubusercontent.com/41010669/186797860-5d42a983-65be-4718-9722-b76d017d7d25.png)

![image](https://user-images.githubusercontent.com/41010669/186811440-658799bc-a6e0-4626-b0e1-b3e78436561f.png)

**Comment by tink2123** [comment]
小语种模型缺少真实数据，模型效果不够鲁棒，有需要的话建议在自己数据上finetune，提升模型效果。

**Comment by nissansz** [comment]
怎样finetune? 多收集真实数据加入数据集进行训练？

**Comment by tink2123** [comment]
是的，尽量多的收集真实数据+合成数据，加载发布的预训练模型使用小学习率迭代训练。

**Comment by nissansz** [comment]
小学习率时多少？
