### ISSUE TITLE
请问同一张图片在取图范围大小变化的情况下结果也跟着变化，这是什么情况呢？

### ISSUE THREAD

**Issue by Camphora7** [PaddlePaddle/PaddleOCR#7369]
![d3c22db3d3770fe8ddbbfa84f3831ba](https://user-images.githubusercontent.com/108849683/186797690-cf38fd80-049b-4f10-bfa4-8928ec2820ec.png)
![a777b1c780633f579f225fb76bd892a](https://user-images.githubusercontent.com/108849683/186797692-2dee891f-364d-4448-ba4a-2aa7ef84a692.png)
![25b32646feddc7c29498619c2eed115](https://user-images.githubusercontent.com/108849683/186797695-bc0cbc33-6be5-46d1-a1a9-0197e7a50317.png)
这三张图片中，有的能被识别为01C，有的识别结果仍然为010，将识别区域放大或缩小，识别结果也会有所改变，但识别区域的选取大小和识别的准确与否并没有明确的相关性，请问这是什么情况，有什么有效的解决办法吗？

**Comment by iknow34languages** [comment]
这个问题看来有不少人遇到了，现在源码里面给的图片文字识别率不错，但是截小图，小的文字就识别不到或者识别不准了

不知道如何解决类似的问题

**Comment by MissPenguin** [comment]
> 三张图片中，有的能被识别为01C，有的识别结果仍然为010，将识别区域放大或缩小，识别结果也会有所改变，但识别区域的选取大小和识别的准确与否并

这张图片来看，确实也挺像010稍微被遮挡一点，识别模型对遮挡有一定的鲁棒性，所以“弄巧成拙”了，但这种情况没法完全避免。至于结果的波动，是因为输入的图片不完全一致，所以一点变化都会导致在两种可能的识别结果中反复横跳。

要解决的话，如果主要就是这一种场景，一方面可以尝试调整参数，包括输入尺度、后处理参数等，找一组对你这个场景比较合适的参数；另一方面，也可以标注一些数据进行微调，成本相对高一点。

**Comment by iknow34languages** [comment]
> 

有无相关的文档 可以操作，对于新手感觉太难了点，无从下手

**Comment by Camphora7** [comment]
> > 三张图片中，有的能被识别为01C，有的识别结果仍然为010，将识别区域放大或缩小，识别结果也会有所改变，但识别区域的选取大小和识别的准确与否并
> 
> 这张图片来看，确实也挺像010稍微被遮挡一点，识别模型对遮挡有一定的鲁棒性，所以“弄巧成拙”了，但这种情况没法完全避免。至于结果的波动，是因为输入的图片不完全一致，所以一点变化都会导致在两种可能的识别结果中反复横跳。
> 
> 要解决的话，如果主要就是这一种场景，一方面可以尝试调整参数，包括输入尺度、后处理参数等，找一组对你这个场景比较合适的参数；另一方面，也可以标注一些数据进行微调，成本相对高一点。

感谢解答！

**Comment by Camphora7** [comment]
> > 三张图片中，有的能被识别为01C，有的识别结果仍然为010，将识别区域放大或缩小，识别结果也会有所改变，但识别区域的选取大小和识别的准确与否并
> 
> 这张图片来看，确实也挺像010稍微被遮挡一点，识别模型对遮挡有一定的鲁棒性，所以“弄巧成拙”了，但这种情况没法完全避免。至于结果的波动，是因为输入的图片不完全一致，所以一点变化都会导致在两种可能的识别结果中反复横跳。
> 
> 要解决的话，如果主要就是这一种场景，一方面可以尝试调整参数，包括输入尺度、后处理参数等，找一组对你这个场景比较合适的参数；另一方面，也可以标注一些数据进行微调，成本相对高一点。

感谢解答！
