### ISSUE TITLE
如何标注VQA

### ISSUE THREAD

**Issue by sheltonsuen** [PaddlePaddle/PaddleOCR#7370]
请问一下有没有相应工具可以将VQA标签打上？

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：VQA
- 运行指令/Command Code：-
- 完整报错/Complete Error Message：-

**Comment by MissPenguin** [comment]
可以试试PPOCRLabelv2的kie标注功能：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md

**Comment by sheltonsuen** [comment]
好的多谢，我去试试
