### ISSUE TITLE
VQA表单识别，结果乱码

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleOCR#7371]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux localhost 5.4.0-124-generic #140~18.04.1-Ubuntu SMP Fri Aug 5 11:43:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- 版本号/Version：Paddle：2.3.0  PaddleOCR：release2.5 问题相关组件/Related ：ppstructure/vqa
- 运行指令/Command Code：python tools/infer/predict_system.py     --image_dir="./doc/datasets/work_table/XFUND/zh_val/image/zh_val_21.jpg"     --det_model_dir="./output/work_table/det_infer/"     --rec_model_dir="./output/work_table/rec_real_infer/"     --rec_image_shape="3, 32, 320"     --rec_char_dict_path="/home/dl/data/wj/paddleOCR/PaddleOCR/ppocr/utils/word_dict.txt"

- 完整报错/Complete Error Message：
- -----rec_res [('嘴骨且香啟胡腈蕉痂妾幽庸锝幽捕１爆１些审長绝疫且長敖癣斥瘿蕉噩穹定诚颔诚些靴粗癣', 0.08966415375471115), ('丙锝邑癣爪書′党癣澈玫跷啫１定轻垌。碎１围１。瞓侦邑爪惨莳惨些癣党莳長癣照徐丙锝舶齋邑癣蕉癣燎１诚绀审恕靴張癣获潘癣', 0.0779646560549736), ('演稻昴現慈是瘸勃审诃癣藩癣往腈癣蒂癣诚癣', 0.09631882607936859), ('鸽定痂党诚汰诚党癣诚藩癣往癣闫癣靴癣靴戾癣', 0.04831065982580185), ('愚睡浮党蕉｀渊潘捕励恕往癣蒂获诚获癣', 0.0833430290222168), ('唯卒峭邑′党峭装嶽彷定凿捕肖邑徐些藩b垌b緑党藩恕7往蕉靴蒂靴攒审获靴癣', 0.06095745041966438), ('抓定蕾莳党｀党恕捕癣获癣', 0.056176524609327316), ('′癣党靴党瀣′党癣拌１诚俚體诚糅徕′。彷袭彷诚党靴邑往靴袭靴蕉', 0.09487982839345932), ('囗汶玫定緑徐戟舶′稻藩7藩捕靴潘往靴诚戾靴癣', 0.08099830895662308), ('开徐蕉彷敖亮诚敖凿绝玫城锏長爪诚瑗藩痂捕往靴获诚靴鍵', 0.05597899481654167), ('竟睡细邑汶邑定長赫捕｀恕靴捕嘟靴蒂靴癣诚潘癣', 0.044424887746572495), ('原臻党殷诚癣b党诚靴党锹诚靴體瀣诚锹诚癣臻癣辩長靴癣拌１愣党砂靴劝往闫癣蕉掩', 0.0915006771683693), ('念踵彷蕉爪Ο肓谤冢攒获１冮嘈冮蕉慈瑗體些埔砂定瑗緹些癣获癣', 0.09117299318313599), ('跪嘎蕉缄１导奈凿锝茬韻爪党書党癣體癣照粗溱爪蕉绀锏癣锹愣诚靴將靴體瀣靴党器党癣惆诚靴體峭彷砂靴癣', 0.09901025146245956), ('沈玫緑癣敖戾蕉定１春翌皋蕉党蕉冮裟竺蕉慈蕉党绀审锏蕉党缈冮攒定鳝臻緑臻藩１谤审癣嵋報桂長邑蕉雏蕉癣瘿些往癣获癣', 0.08964994549751282), ('箬緑箬捕１K寕K１鹗察藩恕潘往潘蒂潘获癣潘癣', 0.07049374282360077), ('威邑緑徐癣定骨′定爪′。定蕉竺裟竺蕉慈癣绀抓戈党鹗峭锏乜長定诚臻畫臻緑臻侦１蕉审藩瘿靴往蒂靴', 0.09207113832235336), ('念緑谧冮b１膦１瑗慈緑获冮蕉慈瑗祀缈簧定癣断绀痂恕往癣获癣', 0.08174416422843933), ('骇穂冮知冮定緑癣遍娅』蕉癣韻诚察审緹恕往靴获靴获粗癣峭', 0.05819754675030708), ('鶴去蕉细褪获骇踉長扙邑簧癣體胡徐蕉定瑗耙瑗定襁啟演蕉慈绀蕉痂恕蕉7嘟癣蒂癣获靴粗癣', 0.07324789464473724), ('砌１蕉冼淀蕉１靴釉１蕉冠获癣诚鬼蚶胡定玫蕉蔷辩围長嶽垮藩汶定緑癣流冮党蕉定知定率胡定诚蕉毒蕉癣锏嬴蕉澧蕉桠究诏且稻蕉瀣蕉′癣匙诚靴党诚靴党笛彷党', 0.08228039741516113), ('演昴杀慈砂徐椤徐癣绀靴恕癣靴蕉往靴癣', 0.08748199045658112), ('暖痂簧嘎體飄绀撤细君定槌膜惨莳恕些臻纫蜿箬诚緑纫蕉１K劝１桠潘鹗些潘癣', 0.04509733244776726), ('腩冮蕉慈蕉瑗體愚祀些埔装砂祎桠抓艦定癣定敖纫書臻党臻癣彈癣溱痂定爪溱爪蕉绀办懦鹗恕癣卒癣靴癣', 0.04994669184088707), ('究骨定诚且長定長岱襄彷長捕些肖些藩捕b渲b轻党藩靴蕉靴获靴｀', 0.10266212373971939), ('氏捕邑些细唐堑箬臻長爪惨莳惨癣诚癣帧冢怆以暖簧嘎佧體燈幂细君擎爪惨莳惨些戈诚１诚春翌蕉党徐瘸徐彷癣藩絲些获粗癣', 0.08573906123638153), ('」邑噩碎１長包些帧跪敖漢長崂癣奈靴郜癖鲆艷衛窍含存靴存', 0.06990572065114975), ('嗡蕉癣定蕾７攒癣彷莳緑些緑春翌蕉党肓誘徐１绀緹些癣靴癣', 0.07814078778028488), ('癣帧玫愚１稳定徐逝慰围癣１瞓峭漢′癣惨莳些癣長莳長诚癣噩究骨诚長爪党邑诚燎诚些Z靴張获靴获癣', 0.10057176649570465), ('代帧玫癣體摈佧慈橙蕉爪崮澈崮蕉砂定蕉蕾衛b舶轻戈沱劝蕉捕沸盘長癣获诚雁冮诚掠茬緑蕉汉蕉掠彷癣沽谧且癣長蕉癣燎１诚些靴癣获靴癣', 0.058549556881189346), ('漕瑕卒劝细获冠哉昴且歉韻敖蕉癣些噩些漢長邑癣敖威敖長徐邑定骨′定爪梗澈定癣敖颔１些唇诚定骨長彷些長ｄ凿長爪惨莳惨些癣诚敖党敖党癣瘿温骨且祉且香徐胡蕉痂瓷幽锝话癣藩些知垂１些長疫襄彷長骥', 0.06902934610843658), ('書锝鲵邑癣翌′党癣澈玫骨。定徐碎１祉１围１代。瑕侦邑爪惨莳惨些癣党莳愣癣照舶夹癣璈蕉癣诚癣隗诚细绀蕉恕蕉靴癣获癣', 0.08345787972211838), ('演Ο演現慈Ο党峭鹗魚瘸勃暢诃癣藩党癣往腈癣腈潘癣蒂癣尨癣', 0.07136307656764984), ('愚橙浮党敖渊蔸捕诚捕党邑党藩恕癣往癣靴蒂靴攒诚背癣', 0.08415313065052032), ('熟垌玫張緑長徐昔且稻藩7靴往靴戾Ｅ靴癣', 0.08518553525209427), ('璨蕉襄疹襄炝慈尨藩审癣塌往赫塌坋靴窍戾癣', 0.07258342951536179), ('竟睡细诃汶邑長赫捕｀恕靴腈癣嘟癣蒂癣诚潘癣峭', 0.05076713487505913), ('遍噩卒邑诚党鸽善嶽彷轻捕愣肖些徐藩b纰b轻党藩瑗藩叮蕉7蕉靴蒂靴审获靴粗｀', 0.0644974559545517), ('演嘎演蕉鳖１敖清凿長党書臻党臻癣党痂溱痂１褪稻爪定藩潘些潘張癣获靴粗癣', 0.06799247860908508), ('′癣峭党靴诚党迄诚爪徕薰臻诚蘑诚世長诚俚狩′。愣體′党靴往緑闫靴闫１蕉掩', 0.07222706824541092), ('體鲜党锹诚党癣將靴叽體臻靴邑往靴袭彷蕉癣', 0.10443930327892303), ('瀣徐蕉彷長敖诚亮诚癣绝偌捕玫城锏長啟彷爪获彷审痂捕往靴癣靴获靴粗癣', 0.06198819354176521), ('癣噩癣靴袭彷诚癣靴烬辩靴將靴瀣绒靴立袭１靴將靴將靴袭靴党恕靴亻往闫靴１癣靴蕉靴蕉', 0.12343978881835938), ('蕾蕉癣诚蕉嘈蕉慈蕉彷銷蜿箬′纫捕澈K劝１鹗鳥些恕些往癣蒂获癣', 0.09065286070108414), ('寡冮攒長遍臻臘彷蕉襁莳緑些緑癣荏繪邑些攒癣蚨７攒癣攒嵋乜長邑诚蓦崮骨蕉念舶竺』嶽徐诚癣夜蕉癣蕉彷蕉绀细噗绀瑗些皺張癣获癣', 0.06997085362672806), ('妾汴邑長緑邑敖定骨′定爪羽。定蕉耙蕉瑗峭Ο１袱１蕉敖凿Φ话仪癣噩冮噩癣定徐些蒂癣靴癣', 0.079622283577919), ('朿褪?祉褪遍冠合捕合′蕉拒薰臻癣長歉贴′臻铝蒂氟祉緑捕椒釉迄邑诚侦稗蕉靴往靴获靴癣', 0.06181962415575981), ('鶴去蕉褪爪癣爪踉潭簧癣體闳胡徐蕉定徐瑗耙蕉瑗峭彷演蕉慈瑗审恕些嘟癣蒂获粗癣', 0.07641813904047012), ('歉′侦臻蒂慷祉緑捕冠靴釉蕉定瘿皋蕉癣冠蕉浅慈蕉噗砂锏攒锏谤癣裟』噩蕉男细蕉且彷徐诚率襄腈癣′爪癣臻辩臻靴党癣帧耙戾１蕉靴釉迄捕癣获長兖長爪冠党冠蕉癣噩體冮蝴定癣悶咖稻蕉癣燎靴恕靴張靴获癣', 0.08730568736791611), ('瓷咕痹锝己沱爪知次１些魉施定１飄缈妾瘿Ｐb靴往知絲翩絲党癣笃且癣绀父绀瘿恕蕉往靴蒂获靴癣', 0.06867807358503342)]
[2022/08/26 11:03:39] ppocr DEBUG: rec_res num  : 50, elapse : 0.20163178443908691
--------filter_boxes []
[] []
[2022/08/26 11:03:39] ppocr DEBUG: 0  Predict time of ./doc/datasets/work_table/XFUND/zh_val/image/zh_val_21.jpg: 1.328s
[2022/08/26 11:03:39] ppocr DEBUG: The visualized image saved in ./inference_results/zh_val_21.jpg
[2022/08/26 11:03:39] ppocr INFO: The predict total time is 1.8414337635040283

使用的模型是，ocr垂类模型库里面的表单识别模型，rec_mobile_pp-OCRv2-student-realdata，也试过垂类模型库中提供的best_models_form\rec_form\best_accuracy（文字框检测没问题）

**Comment by wj920291253** [comment]
将是识别模型换成ppocrv3_pre_rec 识别预训练模型，不会出现乱码，但效果一般

**Comment by MissPenguin** [comment]
麻烦提供一下使用的模型链接，测试图片，我们复现一下问题

**Comment by wj920291253** [comment]
链接：https://pan.baidu.com/s/1zIkYVAIcfa1SDcJfpfLAsA?pwd=zknj 
提取码：zknj
@MissPenguin

**Comment by littletomatodonkey** [comment]
这个字典和shape设置的都不太对，我用了ppocr v3 的检测与识别，结果如下，看着效果还行

![image](https://user-images.githubusercontent.com/14270174/187622443-2a4fc5fd-2365-4a12-a8b4-f3e542bcf7e9.png)


预测脚本如下所示

```shell
det_dir="./inference/ch_PP-OCRv3_det_infer"

rec_dir="./inference/ch_PP-OCRv3_rec_infer"
dict="./ppocr/utils/ppocr_keys_v1.txt"

python3.7 tools/infer/predict_system.py \
       --use_gpu=True \
       --use_tensorrt=False \
       --precision=fp32 \
       --rec_model_dir=${rec_dir} \
       --det_model_dir=${det_dir} \
       --rec_char_dict_path="${dict}" \
       --use_space_char=True \
       --image_dir="./ppstructure/docs/kie/input/zh_val_21.jpg" \
       --use_dilation=False \
       --det_db_score_mode=slow \
       --det_db_unclip_ratio=1.8 \
       --benchmark=False \
       --warmup=False
```

**Comment by wj920291253** [comment]
我后面也是用ppocr v3 测的，但是想着你们垂直模型经过迁移训练，效果可能会更好，但是结果是乱码。。。
![zh_val_1](https://user-images.githubusercontent.com/49974432/187624095-a388bde9-e915-4925-a948-03499c9d26b7.jpg)
单从图片看效果还可以，但是用tools\end2end\eval_end2end.py 评估的指标比较差。
hit, dt_count, gt_count 2338 3831 3629
character_acc: 63.67%
avg_edit_dist_field: 3.10
avg_edit_dist_img: 225.10
precision: 61.03%
recall: 64.43%
fmeasure: 62.68%

**Comment by wj920291253** [comment]
我后面也是用ppocr v3 测的，但是想着你们垂直模型经过迁移训练，效果可能会更好，但是结果是乱码。。。
![zh_val_1](https://user-images.githubusercontent.com/49974432/187624095-a388bde9-e915-4925-a948-03499c9d26b7.jpg)
单从图片看效果还可以，但是用tools\end2end\eval_end2end.py 评估的指标比较差。
hit, dt_count, gt_count 2338 3831 3629
character_acc: 63.67%
avg_edit_dist_field: 3.10
avg_edit_dist_img: 225.10
precision: 61.03%
recall: 64.43%
fmeasure: 62.68%

**Comment by littletomatodonkey** [comment]
垂直模型也是需要看场景的哈，最好是基于当前数据finetune，另外就是字典需要保证没问题

**Comment by wj920291253** [comment]
我测的就是 垂直模型自带的数据，然后根据你们的aistudio的项目 指定的字典诶，
![1661933363082](https://user-images.githubusercontent.com/49974432/187627157-413840af-35d2-47c1-a742-6159cdf64624.png)

**Comment by littletomatodonkey** [comment]
哪个aistudio项目？我们应该没有针对这个数据集做过文本检测与识别的训练

**Comment by wj920291253** [comment]
认真的嘛(⊙o⊙)…  
![企业微信截图_16623447961487](https://user-images.githubusercontent.com/49974432/188349137-efd40994-579b-4c48-a9cc-4a18ea4dad6c.png)

**Comment by wj920291253** [comment]
认真的嘛
![企业微信截图_16623448158664](https://user-images.githubusercontent.com/49974432/188349218-9ff0d0b5-1c38-4487-907f-6813d5cb6275.png)

![企业微信截图_16623447961487](https://user-images.githubusercontent.com/49974432/188349226-a480ddae-4e5d-4312-8923-593bea12c955.png)

**Comment by littletomatodonkey** [comment]
抱歉这个应该是其他小伙伴支持的，我没注意，我们看下哈

**Comment by wj920291253** [comment]
好的好的，没事，感谢回复帮忙解答疑问

**Comment by an1018** [comment]
在AI Studio测试没问题的~，可以基于AI Studio项目再测试下，本地确认下模型和字典~
![image](https://user-images.githubusercontent.com/19808900/188353693-1ace929d-9ef5-4612-96ca-dc4275eca1ee.png)

**Comment by wj920291253** [comment]
能麻烦你们测试下你们垂类模型百度网盘内的模型嘛？就是截图中说的垂类模型
![企业微信截图_16623499197576](https://user-images.githubusercontent.com/49974432/188357388-18089d89-f96a-4fe7-93d4-df1da85363b1.png)
我用的是这里面的检测识别模型
![企业微信截图_16623499973931](https://user-images.githubusercontent.com/49974432/188357499-b81ccbd5-2b9e-4358-8951-10b6b72b9d33.png)

**Comment by an1018** [comment]
这个也试了，没问题哈，再按教程重新导出模型，确定下字典路径试试
![image](https://user-images.githubusercontent.com/19808900/188424902-546dfaa4-4180-41e6-88be-44f44afe1a91.png)
