### ISSUE TITLE
C++预测demo识别空白图片时，sorted_boxes函数中空向量被访问，引起崩溃

### ISSUE THREAD

**Issue by hiroi-sora** [PaddlePaddle/PaddleOCR#7372]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`win10`
- 版本号/Version： [PaddleOCRv2.6.0](https://github.com/PaddlePaddle/PaddleOCR/releases/tag/v2.6.0) 
- 问题相关组件/Related components：`utility.cpp`
- 运行指令/Command Code：`--image_dir=图片\blank.jpg（这是一张没有文字的空白图片）`
- 完整报错/Complete Error Message：`0x00007FF756546F57 处(位于 ppocr.exe 中)引发的异常: 0xC0000005: 读取位置0x0000000000000048 时发生访问冲突。`

#### 异常原因：

`paddleocr.cpp` 的 `PPOCR::det` 函数中，由于图片无文字，因此 `boxes` 和 `ocr_results` 是空向量。

紧接着调用 `utility.cpp` 中的 `Utility::sorted_boxes(ocr_results)` ，该函数中有个for循环的条件是 `i < ocr_result.size() - 1` 。但是向量size()是无符号整型，`ocr_result.size() - 1` 即0-1会溢出为极大正数，导致for循环进入执行，空向量 `ocr_result` 被访问，程序崩溃。

#### 修改建议：

`paddleocr.cpp` 的 `PPOCR::det` 函数中，判断 `boxes` 为空时直接结束任务，跳过后面的步骤。

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/7374 已在这里进行修复，感谢反馈
