### ISSUE TITLE
rec的参数怎么调

### ISSUE THREAD

**Issue by hayam1sm** [PaddlePaddle/PaddleOCR#7373]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOcr 2.5.0.3
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请问除了这边配置文件/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml，还有别的可调整的参数么?

**Comment by MissPenguin** [comment]
建议再明确一下问题，比如说有什么样的badcase，想获得什么样的效果，才好给出调参建议。

**Comment by hayam1sm** [comment]
> 建议再明确一下问题，比如说有什么样的badcase，想获得什么样的效果，才好给出调参建议。

想要识别单个字的位置，目前识别出来的基本都是按长方形的文字框为单位的，获取不到单个字的位置信息，不知道有没有参数可以调整。
看了前面一样的问题，想通过rec识别的结果倒推，但是没找到获得rec的preds的规则是什么样的。

**Comment by MissPenguin** [comment]
> 

目前没有通过调参获取单字位置的功能哈，最简单的可以根据文本框位置和总字数除一下，但只能粗略估计了。
