### ISSUE TITLE
PP-Structure面板分析如何导入模型

### ISSUE THREAD

**Issue by asus10tu** [PaddlePaddle/PaddleOCR#7376]
ocr模型我看文档知道det_model_dir, rec_model_dir这两个字段。
那版面分析模型和KIE模型是用什么字段导入呢，好像没看到相关说明，有文档么。

另外想问下，有些表格图片执行面板分析后，会导出xlsx文件。但是有些图片却没有，导出成一张图片结果也是普通坐标，这个如何设置一定要导出xlsx呢，谢谢

**Comment by MissPenguin** [comment]
您说的这个是python推理场景如何指定模型，版面分析和表格识别的指定方式可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/inference.md#1.1

kie任务中，ser模型的使用可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/inference.md#2

关于第二个问题，先排查是否检测到表格，有可能是因为没检测到表格/或把表格检测成了图片，所以没有生产Excel文件。这个是模型效果决定的。
