### ISSUE TITLE
How to properly load my trained model into Python code ?

### ISSUE THREAD

**Issue by huanidz** [PaddlePaddle/PaddleOCR#7379]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/7377

<div type='discussions-op-text'>

<sup>Originally posted by **huanidz** August 26, 2022</sup>
I just finished training a text-recognition with SVTR recognition model for custom dataset, dict. 
The predict result when i run with the command:
python3 tools/infer/predict_rec.py 
--image_dir='/pathToMyImg'
--rec_model_dir='PathToMyInferenceModel' 
--rec_algorithm='SVTR' 
--rec_image_shape='3,64,256' 
--rec_char_dict_path='PathToMyDictFile'
**The output result is correct.**

But when i try to load into python with PaddleOCR(...) from paddleocr module, the prediction now is **very bad**, in my case its repeatly output one of the character in the dict despite the image quality is ok.

And when i try to change to rec_algorithm of PaddleOCR to SVTR, it throw an error: **only supports CRNN, SVTR_LCNet**.

I did check the params for this loader function but changing most of them to fit my model did not help.
I check the dict file, the paths, everything is ok.
The code that load the model run ok but seem like its not.

How do i fix this ?
</div>

**Comment by MissPenguin** [comment]
This is because the paddleocr whl package only adapts to the pp-ocr series models. If you want to use other models such as svtr,  it is recommended to try to adapt it yourself, mainly for pre- and post-processing.
