### ISSUE TITLE
没有nccl时训练报错

### ISSUE THREAD

**Issue by ezio1320** [PaddlePaddle/PaddleOCR#738]
我只需要单卡训练模型，所以就没有安装nccl库。训练模型就会报错，跑paddleocr必须安装nccl吗，只用cudnn可以吗？
![image](https://user-images.githubusercontent.com/28839318/93340250-297f1f80-f85f-11ea-8897-39f59260a6b0.png)

**Comment by tink2123** [comment]
启动训练前设置一下环境变量： export CUDA_VISIBLE_DEVICES=0 试一下呢？

**Comment by ezio1320** [comment]
> 启动训练前设置一下环境变量： export CUDA_VISIBLE_DEVICES=0 试一下呢？

多谢回复，之前没有仔细读readme，加了export CUDA_VISIBILE_DEVICES=0之后就可以了。

**Comment by ezio1320** [comment]
> 启动训练前设置一下环境变量： export CUDA_VISIBLE_DEVICES=0 试一下呢？

多谢回复，加了export CUDA_VISIBLE_DEVICES就可以了。 

不过建议如果可以的话还是能在配置文件里添加一个控制使用哪个gpu的参数，如果设置export CUDA_VISIBLE_DEVICES，会影响llinux全局设置，可能会影响其它训练。还是谢谢回复了

**Comment by tink2123** [comment]
export 设置环境变量只会在当前任务生效，不会影响全局的～

**Comment by ezio1320** [comment]
> export 设置环境变量只会在当前任务生效，不会影响全局的～

多谢指点，是我之前理解不够。在~/.bashrc里增加语句，影响全局，直接在shell命令行中输入，就只会在此shell中生效。
