### ISSUE TITLE
en_PP-OCRv3_det在icdar2015数据集中的评估精度只有0.4754

### ISSUE THREAD

**Issue by max-niu** [PaddlePaddle/PaddleOCR#7380]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu python3.7.5
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：NA
- 运行指令/Command Code：
- 
wget -nc -P ./checkpoint https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_distill_train.tar

cd ./checkpoint && tar xf en_PP-OCRv3_det_distill_train.tar && cd ..

python3 PaddleOCR/tools/eval.py -c PaddleOCR/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.checkpoints="./checkpoint/en_PP-OCRv3_det_distill_train/best_accuracy"

- 完整报错/Complete Error Message：
评估精度很低，只有0.4754
![image](https://user-images.githubusercontent.com/57517234/186898546-849db799-b290-4580-9ffe-527e38b6e04c.png)

相同的操作验证 EAST算法的估计精度正常如下图：
![Uploading image.png…]()

**Comment by LDOUBLEV** [comment]
en_PP-OCRv3_det 对应的模型不是在icdar2015数据上训练的，为了更拟合实际使用场景，en_PP-OCRv3_det 的训练数据是长文本，包含空格的句子级别的标注，icdar2015是单词级别的标注。
在icdar上并不能反应出en_PP-OCRv3_det 的能力
