### ISSUE TITLE
中英文超轻量PP-OCRv3模型（16.2M）的中英文字典是哪个.txt呀？

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/PaddleOCR#7384]
中英文超轻量PP-OCRv3模型（16.2M）的中英文字典是哪个.txt呀？能否提供链接？

**Comment by hiroi-sora** [comment]
[ppocr_keys_v1.txt](https://github.com/PaddlePaddle/PaddleOCR/blob/56aaead6d06b9ef6c6ecb8655f5a571f579f939e/ppocr/utils/ppocr_keys_v1.txt)

**Comment by lovepika** [comment]
`ppocr/utils/en_dict.txt`
