### ISSUE TITLE
请问是否有将paddleOcr编译成dll 形成com组件,方便其他模块进行调用的文档？

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#7388]
我想将paddleOcr做成dll,通过ATL对象，供给其他模块调用，
例如：vbs调用

set myOcr = CreateObject("PaddlerOcr.Ocr")
godman = myOcr.smartpaddleocr("F:\\mypic\\11.png")

目前发现编译有较多的问题，而且很难解决，
请问是否有类似的案例？

**Comment by hiroi-sora** [comment]
类似 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) ？简单封装后供其它模块调用。不过不是dll

**Comment by iknow34languages** [comment]
> 

直接用exe不会弹出CMD窗口吗？

**Comment by hiroi-sora** [comment]
> 直接用exe不会弹出CMD窗口吗？

Python可以设管道通信时启用静默模式（隐藏子线程的窗口），其他语言应该也类似。

你看看 [API示例](https://github.com/hiroi-sora/PaddleOCR-json#%E9%80%9A%E8%BF%87api%E8%B0%83%E7%94%A8) 或者 [Umi-OCR](https://github.com/hiroi-sora/Umi-OCR)，使用时不会有弹窗。
