### ISSUE TITLE
请问是否可以提供基准测试的代码呢

### ISSUE THREAD

**Issue by MHX1203** [PaddlePaddle/PaddleOCR#739]
我在cpu上测试单张图片的推理速度与repo中的基准测试速度存在较大差距， 差了好几倍，所以希望可以提供基准测试的代码。

**Comment by tink2123** [comment]
单张图片测试时，由于包含了模型的启动时间，所以耗时较大，在测试速度时请使用多张图片，或单张图片循环测试多次，并去除掉第一张图片的运行时间。
