### ISSUE TITLE
[c++ infer] 有无可能关闭链接库的日志打印？

### ISSUE THREAD

**Issue by hiroi-sora** [PaddlePaddle/PaddleOCR#7393]
- 系统环境/System Environment：vs 2019
- 版本号/Version：PaddleOCR v2.6

`paddle_inference_api.h` 中的 `PD_INFER_DECL std::shared_ptr<Predictor> CreatePredictor( const Config& config);`  及 `  bool Run();` ，调用这些函数时会打印大量日志。有无可能在需要时关闭它的日志打印呢？

曲线救国的方式是调用时禁用/启用输出流，如
```cpp
  // windows
  fclose(stdout);
  fclose(stderr);
  this->predictor_ = CreatePredictor(config);
  freopen("CON", "w", stdout);
  freopen("CON", "w", stderr);
```
```cpp
  fclose(stderr);
  this->predictor_->Run();
  freopen("CON", "w", stderr);
```
有没有更好的方式？

**Comment by andyjpaddle** [comment]
可以在代码中设置 `config.DisableGlogInfo();`，比如识别的话可以在https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/src/ocr_rec.cpp#L136 后面添加，检测类似。添加完重新编译即可

**Comment by hiroi-sora** [comment]
> 可以在代码中设置 `config.DisableGlogInfo();`

感谢解答。确实绝大部分日志都不会打印了。但是 `orc_det.cpp` 中 `LoadModel()` 的 `this->predictor_ = CreatePredictor(config);` ，虽然已经设了 DisableGlogInfo ，但还是有些日志输出到 stderr 中。请问是正常的吗？

内容如下：

```
e[37m---    fused 0 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
e[37m---    fused 0 elementwise_sub with relu activatione[0m
e[37m---    fused 0 elementwise_sub with tanh activatione[0m
e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_sub with swish activatione[0m
e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
e[37m---    fused 0 elementwise_sub with abs activatione[0m
e[37m---    fused 0 elementwise_sub with clip activatione[0m
e[37m---    fused 0 elementwise_sub with gelu activatione[0m
e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
e[37m---    fused 0 elementwise_mul with relu activatione[0m
e[37m---    fused 0 elementwise_mul with tanh activatione[0m
e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_mul with swish activatione[0m
e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
e[37m---    fused 0 elementwise_mul with abs activatione[0m
e[37m---    fused 0 elementwise_mul with clip activatione[0m
e[37m---    fused 0 elementwise_mul with gelu activatione[0m
e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m
```

**Comment by GreatV** [comment]
> > 可以在代码中设置 `config.DisableGlogInfo();`
> 
> 感谢解答。确实绝大部分日志都不会打印了。但是 `orc_det.cpp` 中 `LoadModel()` 的 `this->predictor_ = CreatePredictor(config);` ，虽然已经设了 DisableGlogInfo ，但还是有些日志输出到 stderr 中。请问是正常的吗？
> 
> 内容如下：
> 
> ```
> e[37m---    fused 0 elementwise_add with relu activatione[0m
> e[37m---    fused 0 elementwise_add with tanh activatione[0m
> e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
> e[37m---    fused 0 elementwise_add with swish activatione[0m
> e[37m---    fused 0 elementwise_add with hardswish activatione[0m
> e[37m---    fused 0 elementwise_add with sqrt activatione[0m
> e[37m---    fused 0 elementwise_add with abs activatione[0m
> e[37m---    fused 0 elementwise_add with clip activatione[0m
> e[37m---    fused 0 elementwise_add with gelu activatione[0m
> e[37m---    fused 0 elementwise_add with relu6 activatione[0m
> e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
> e[37m---    fused 0 elementwise_sub with relu activatione[0m
> e[37m---    fused 0 elementwise_sub with tanh activatione[0m
> e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
> e[37m---    fused 0 elementwise_sub with swish activatione[0m
> e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
> e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
> e[37m---    fused 0 elementwise_sub with abs activatione[0m
> e[37m---    fused 0 elementwise_sub with clip activatione[0m
> e[37m---    fused 0 elementwise_sub with gelu activatione[0m
> e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
> e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
> e[37m---    fused 0 elementwise_mul with relu activatione[0m
> e[37m---    fused 0 elementwise_mul with tanh activatione[0m
> e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
> e[37m---    fused 0 elementwise_mul with swish activatione[0m
> e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
> e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
> e[37m---    fused 0 elementwise_mul with abs activatione[0m
> e[37m---    fused 0 elementwise_mul with clip activatione[0m
> e[37m---    fused 0 elementwise_mul with gelu activatione[0m
> e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
> e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m
> ```


正常的，我的也这样。

**Comment by andyjpaddle** [comment]
这个问题下个release版本的paddle会修复，着急的话，可以安装develop版本的paddle试试 https://github.com/PaddlePaddle/Paddle

**Comment by hiroi-sora** [comment]
2023-5-23 实测，用Release v2.6.0的代码+最新推理库，在代码里取消所有`config.DisableGlogInfo();`的注释，确实不会在初始化时打印任何日志了。感谢维护更新。
