### ISSUE TITLE
使用paddleOCR的模型转换为IR模型后,openvino无法进行推理

### ISSUE THREAD

**Issue by kc-w** [PaddlePaddle/PaddleOCR#7399]
操作系统为windows10 
openvino版本为openvino2022.1.0的runtime离线安装版

paddleOCR的模型为ch_PP-OCRv3_det_infer和ch_PP-OCRv3_rec_infer

openvino的推理demo程序为open_model_zoo里的text_detection_demo

ch_PP-OCRv3_det_infer和ch_PP-OCRv3_rec_infer模型转换为onnx模型的命令为
      paddle2onnx --model_dir ch_PP-OCRv3_det_infer --model_filename inference.pdmodel --params_file inference.pdiparams --save_file onnx/det_model.onnx --opset_version 11 --enable_onnx_checker True
      paddle2onnx --model_dir ch_PP-OCRv3_rec_infer --model_filename inference.pdmodel --params_file inference.pdiparams --save_file onnx/rec_model.onnx --opset_version 11 --enable_onnx_checker True

onnx转为IR模型的命令为
mo --input_model onnx/det_model.onnx --output_dir IR --input_shape [1,3,224,224]
mo --input_model onnx/rec_model.onnx --output_dir IR

使用text_detection_demo进行推理的命令
text_detection_demo -i 1.jpg -m_td IR/det_model.xml -m_tr IR/rec_model.xml -dt ctc -tr_pt_first

![image](https://user-images.githubusercontent.com/39193398/187109218-84a67dad-4047-4935-816c-80ca464519c4.png)

报错内容为
get_shape was called on a descriptor::Tensor with dynamic shape

**Comment by tink2123** [comment]
感谢关注，以上报错的问题是因为，open_model_zoo里的text_detection_demo 与paddle模型暂时无法适配，不建议用以上方式使用。飞桨正在FastDeploy里面做openvino相关支持，预计下周可以完成，上线时在issue里和您同步。

**Comment by kc-w** [comment]
请问FastDeploy项目这周能够完成openvino的ocr相关支持吗?

**Comment by jiangjiajun** [comment]
Hi， @kc-w  你是已经在我们微信交流群了吗，这个进展可以直接在微信上沟通哈

**Comment by kc-w** [comment]
好的
