### ISSUE TITLE
实际使用需要240ms左右的时间

### ISSUE THREAD

**Issue by wkw1542673895** [PaddlePaddle/PaddleOCR#74]
图像中文字不多的情况下，实际使用需要240ms左右的时间

**Comment by LDOUBLEV** [comment]
> 图像中文字不多的情况下，实际使用需要240ms左右的时间

如果图片中的文字过多也会增加识别的时间，另外，你可以调试下tools/infer/predict_rec.py中第62行
```
batch_num=30 修改为 batch_num=10
```
能缩短一些时间，后面我们考虑怎么优化下

**Comment by wkw1542673895** [comment]
好的，速度确有提升，同时减小数值，精度略有下降

**Comment by piaobuliao** [comment]
@wkw1542673895 240ms是CPU还是GPU？

**Comment by wkw1542673895** [comment]
gpu，cpu要超过2秒


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"piaobuliao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 下午3:34
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"nick"<1542673895@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 实际使用需要240ms左右的时间 (#74)





 
@wkw1542673895 240ms是CPU还是GPU？

**Comment by piaobuliao** [comment]
我看这里说用V100的GPU是50ms左右，你是用的什么型号的GPU？
https://github.com/PaddlePaddle/PaddleOCR/issues/60

**Comment by wkw1542673895** [comment]
Tesla P100-PCIE




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"piaobuliao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 下午3:37
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"nick"<1542673895@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 实际使用需要240ms左右的时间 (#74)





 
我看这里说用V100的GPU是50ms左右，你是用的什么型号的GPU？
 #60
