### ISSUE TITLE
v2.6版新增模型转onnx问题

### ISSUE THREAD

**Issue by 746891300-org** [PaddlePaddle/PaddleOCR#7403]
测试了中文表格模型，中文版面分析模型，通过paddle2onnx转onnx模型均报错
paddle2onnx那边解释为模型需要去除控制流再进行转换

![image](https://user-images.githubusercontent.com/5754288/187128216-cce4c181-d926-4298-b94f-40786a67f9fc.png)

**Comment by WenmuZhou** [comment]
slanet暂未支持转onnx

**Comment by 746891300-org** [comment]
----》 paddle2onnx --model_dir ./layout_table_det \
> --model_filename inference.pdmodel \
> --params_filename inference.pdiparams \
> --save_file ./layout_more_det/model.onnx \
> --opset_version 10 \
> --input_shape_dict="{'x':[-1,3,-1,-1]}" \
> --enable_onnx_checker True

2022-08-29 13:10:07 [WARNING]   [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle 
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./layout_table_det/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./layout_table_det/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Failed to read model file: ./layout_table_det/inference.pdmodel, please make sure your model file or file path is valid.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.
2022-08-29 13:10:07 [INFO]      ===============Make PaddlePaddle Better!================
2022-08-29 13:10:07 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s

paddle2onnx 更到新版后，大概是这样的失败信息

**Comment by 746891300-org** [comment]
改了下路径，好像转成功了，先测下哈，谢谢！
