### ISSUE TITLE
使用识别模型进行推理时，推理产生的文本长度超过了模型的`max_text_length`限制

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7408]
+ 模型：Rosetta；
+ 字典：数字字典，即 `0,1,2,3,4,5,6,7,8,9`；
+ 训练时文本的长度限制：15；
+ Paddle 版本：2.3；
+ PaddleOCR 版本：2.5。

**Comment by tink2123** [comment]
麻烦再具体描述下遇到的问题

**Comment by thsno02** [comment]
@tink2123 使用 Rosetta 进行纯数字的识别，在配置文件中限制文本长度为 15，训练样本的标签也没有超过 15 个字符的例子。但是在模型得到的推理结果的文本长度参差不齐，且绝大部分长度都大于 15 了。我推测可能是 CTC loss 的问题，目前换模型了，SVTR 暂时没有这个问题。
