### ISSUE TITLE
PPOCRLabel标注表格时，单元格内有两行数据要如何标注？合并的单元格如何排序？

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleOCR#7409]
如图所示，左上角的那个单元格内有两行数据；右下角的合并单元格“合格”，在调整单元格顺序的时候，要排到“0.04”、“0.7”和“1”哪个的后面呢？
![11111](https://user-images.githubusercontent.com/75460093/187144499-145433b1-06b7-4995-91c7-380dd522f887.jpg)

**Comment by WenmuZhou** [comment]
合格自个单元格排到0.04后面

**Comment by dium6i** [comment]
> 合格这个单元格排到0.04后面

再问一下，如果像这样的单元格在排序的时候，是这么排么？1、2、3、4、5、6、7、8、9、10、11、13、14、15、16、18、19、20。
![333](https://user-images.githubusercontent.com/75460093/187153264-403659e8-b334-4618-b319-cdcfc7ed1700.jpg)

还有就是左上角的单元格里如果有两行数据，要如何标注呢？

**Comment by WenmuZhou** [comment]
1. 是的
2. 一个cell里多行文本，给一个大框

**Comment by dium6i** [comment]
> 1. 是的
> 2. 一个cell里多行文本，给一个大框

感谢回复！
