### ISSUE TITLE
自己训练的识别模型，仅使用识别模型和加上检测模型的效果不一样

### ISSUE THREAD

**Issue by TOMORINAONAO** [PaddlePaddle/PaddleOCR#7410]
参考paddle手写体识别训练的手写汉字识别模型。仅使用识别模型推理，和检测模型+识别模型推理，两者的结果不一样。加上检测模型之后结果变差了。
识别模型用的自己训练出来的，检测模型用的ch_PP-OCRv3_det_infer。

下面是效果图，忽略符号①②③，仅识别模型的每个字都识别对了，加上检测模型就不对了。
![image](https://user-images.githubusercontent.com/51530060/187171976-d0c1c38b-87fb-4833-8f94-835d4f05d161.png)
![image](https://user-images.githubusercontent.com/51530060/187172432-e117e617-ea55-41b2-963a-d72a5e20352d.png)

下面这个多行文本场景下，看检测模型框的挺好的，但是识别结果就会变的很差。
![image](https://user-images.githubusercontent.com/51530060/187172723-90b59077-3bd3-41e7-9307-7ec29b8d784e.png)

另外我尝试把检测模型切出来的文本行一个个的用识别模型去识别，效果和仅用识别模型识别我手动截图一样，准确率比较好。但是检测+识别一起，用tools/infer/predict_system.py去推理准确率就会变差。

想请教一下这种情况会是什么原因导致的。

**Comment by tink2123** [comment]
可能是框太紧，导致部分边缘缺失，可以尝试对框进行膨胀： --use_dilation=True

**Comment by TOMORINAONAO** [comment]
> 
框的问题我也想过，试了试没有效果。加上检测模型之后的准确率还是不对。

**Comment by TOMORINAONAO** [comment]
> 可能是框太紧，导致部分边缘缺失，可以尝试对框进行膨胀： --use_dilation=True

框的问题我之前也想过，试了试还是不行，加上检测模型之后准确率还是不对。。。。

**Comment by caigouShaw** [comment]
请问能否提供一下手写体识别模型的链接，目前算力不够，训练时间太长。
