### ISSUE TITLE
use_tensorrt=true就报错，否则的话是可以正常识别文本的

### ISSUE THREAD

**Issue by YFforever2022** [PaddlePaddle/PaddleOCR#7411]
- 系统环境：win10
- 版本号：PaddleOCR：2.6
- 运行指令：ppocr.exe system --det_model_dir=ch_PP-OCRv3_det_infer --rec_model_dir=ch_PP-OCRv3_rec_infer --image_dir=1.jpg --cls_model_dir=ch_ppocr_mobile_v2.0_cls_infer --rec_char_dict_path=ppocr_keys_v1.txt --use_gpu=true --use_tensorrt=true
- 完整报错：In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320',if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
total images num: 1
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0829 17:56:41.271380 21444 analysis_predictor.cc:881] TensorRT subgraph engine is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [adaptive_pool2d_convert_global_pass]e[0m
I0829 17:56:41.337772 21444 fuse_pass_base.cc:57] ---  detected 8 subgraphs
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_filter_op_pass]e[0m
e[32m--- Running IR pass [delete_weight_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [add_support_int8_pass]e[0m
I0829 17:56:41.499843 21444 fuse_pass_base.cc:57] ---  detected 237 subgraphs
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [skip_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_skip_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0829 17:56:41.662954 21444 fuse_pass_base.cc:57] ---  detected 33 subgraphs
e[32m--- Running IR pass [unsqueeze2_eltwise_fuse_pass]e[0m
e[32m--- Running IR pass [trt_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [trt_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [trt_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0829 17:56:41.734226 21444 fuse_pass_base.cc:57] ---  detected 49 subgraphs
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m
I0829 17:56:41.779139 21444 tensorrt_subgraph_pass.cc:145] ---  detect a sub-graph with 187 nodes
I0829 17:56:41.813309 21444 tensorrt_subgraph_pass.cc:433] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0829 17:56:42.107187 21444 engine.cc:222] Run Paddle-TRT Dynamic Shape mode.
I0829 17:57:11.389840 21444 engine.cc:471] Inspector needs TensorRT version 8.2 and after.
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0829 17:57:11.422060 21444 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0829 17:57:11.657425 21444 analysis_predictor.cc:1035] ======= optimize end =======
I0829 17:57:11.659377 21444 naive_executor.cc:102] ---  skip [feed], feed -> x
I0829 17:57:11.662307 21444 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
In PP-OCRv3, default rec_img_h is 48,if you use other model, you should set the param rec_img_h=32
I0829 17:57:11.683785 21444 analysis_predictor.cc:881] TensorRT subgraph engine is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [adaptive_pool2d_convert_global_pass]e[0m
I0829 17:57:11.740413 21444 fuse_pass_base.cc:57] ---  detected 2 subgraphs
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_filter_op_pass]e[0m
e[32m--- Running IR pass [delete_weight_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [add_support_int8_pass]e[0m
I0829 17:57:11.831212 21444 fuse_pass_base.cc:57] ---  detected 184 subgraphs
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [skip_layernorm_fuse_pass]e[0m
I0829 17:57:11.912248 21444 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [preln_skip_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0829 17:57:11.991331 21444 fuse_pass_base.cc:57] ---  detected 19 subgraphs
e[32m--- Running IR pass [unsqueeze2_eltwise_fuse_pass]e[0m
e[32m--- Running IR pass [trt_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_map_matmul_v2_to_mul_pass]e[0m
I0829 17:57:12.001094 21444 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [trt_map_matmul_v2_to_matmul_pass]e[0m
I0829 17:57:12.004024 21444 fuse_pass_base.cc:57] ---  detected 4 subgraphs
e[32m--- Running IR pass [trt_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0829 17:57:12.015739 21444 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0829 17:57:12.036243 21444 fuse_pass_base.cc:57] ---  detected 23 subgraphs
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m
I0829 17:57:12.050887 21444 tensorrt_subgraph_pass.cc:145] ---  detect a sub-graph with 80 nodes
I0829 17:57:12.063580 21444 tensorrt_subgraph_pass.cc:433] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0829 17:57:12.079201 21444 engine.cc:222] Run Paddle-TRT Dynamic Shape mode.
I0829 17:57:23.468595 21444 engine.cc:471] Inspector needs TensorRT version 8.2 and after.
I0829 17:57:23.475428 21444 tensorrt_subgraph_pass.cc:145] ---  detect a sub-graph with 61 nodes
I0829 17:57:23.483239 21444 tensorrt_subgraph_pass.cc:433] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0829 17:57:23.486168 21444 op_converter.h:270] trt input [pool2d_5.tmp_0_clone_0] dynamic shape info not set, please check and retry.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at ..\paddle/fluid/inference/tensorrt/convert/op_converter.h:308)

**Comment by LDOUBLEV** [comment]
参考FAQ修改代码加入缺少动态参数的shape：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/FAQ.md#q-trt%E9%A2%84%E6%B5%8B%E6%8A%A5%E9%94%99invalidargumenterror-some-trt-inputs-dynamic-shape-info-not-set-check-the-info-log-above-for-more-details
