### ISSUE TITLE
Ubuntu20.4 Nvidia-Docker 识别出来乱码

### ISSUE THREAD

**Issue by zhoudagang** [PaddlePaddle/PaddleOCR#7419]
Ubuntu20.4 Nvidia-Docker

改动：
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

识别返回："text": "饕匠喹社摧春半趸烃舒镭&邴乃瓒桁虚雒棣闻诠输锻樱舜拍恬秣突喫烫铰右＜選元￠汤伈好毗悱纂抖裘碼x景荨筵｜秕摘兩沅興煥鲑譜崭酞滏貅還鹦钏愛蝽ɔ校啻赋纫車笛~蹙单竽阗"

**Comment by tink2123** [comment]
请问启动命令是？看起来没有加载好训练权重

**Comment by gunsonbrad** [comment]
这个问题之前我也遇到过，用CPU跑起来正常，但用GPU跑起来就乱码，后来我用CUDA11.2，安装对应版本cuDNN、paddlepaddle后就解决了
