### ISSUE TITLE
下载vi-layoutxlm-base-uncased ERROR: 404

### ISSUE THREAD

**Issue by yysirs** [PaddlePaddle/PaddleOCR#7421]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
```
python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
```
- 完整报错/Complete Error Message：
```
--2022-08-30 15:11:35--  https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased
Resolving bj.bcebos.com (bj.bcebos.com)... 110.242.70.3, 110.242.70.39, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to bj.bcebos.com (bj.bcebos.com)|110.242.70.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-30 15:11:35 ERROR 404: Not Found.
```
是否没有上传相关模型？

**Comment by littletomatodonkey** [comment]
你好，麻烦升级下paddlenlp的whl包

**Comment by yysirs** [comment]
> 你好，麻烦升级下paddlenlp的whl包
目前已经是最新版本的：
```
Name: paddlenlp
Version: 2.3.5
```

**Comment by littletomatodonkey** [comment]
https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
试下这个呢？

**Comment by yysirs** [comment]
> https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl 试下这个呢？

可以下载成功了，谢谢👍👍👍
