### ISSUE TITLE
PaddleOCR怎么正确识别指数

### ISSUE THREAD

**Issue by Panda891027** [PaddlePaddle/PaddleOCR#7423]
ocr不能准确的识别指数，如:10的4次方被识别为104
![5961661858258_ pic](https://user-images.githubusercontent.com/23490878/187445077-d45e4248-79b4-44bd-94ad-e0f62580944e.jpg)
![5971661858290_ pic](https://user-images.githubusercontent.com/23490878/187445171-32c40b50-96d2-4d68-b908-80169cdefc84.jpg)

**Comment by MissPenguin** [comment]
您好，要表达带指数的文本，可以在字典中加入表达指数的html符号\<sup>\</sup>，又如表达底数使用\<sub>\</sub>，同时补充该类训练数据进行finetune，组织数据时注意格式，如<img width="92" alt="image" src="https://user-images.githubusercontent.com/25809855/187578341-97c55886-e837-4bf6-bc60-1ced0d575ccf.png">的label应该是 
 “5*10\<sup>4\</sup>”
