### ISSUE TITLE
如何在CPU上加速v3识别模型的推理速度 How to accelerate text rec model in paddleocrv3 with CPU

### ISSUE THREAD

**Issue by YAOYI626** [PaddlePaddle/PaddleOCR#7426]
Hi team,

我想请教下如何在CPU上加速PaddleOCR的文字识别模型 （Ultra lightweight PP-OCRv3 recognition model）。我目前在Windows + Intel(R) Core(TM) i7-10700 + onnxruntime 平台上，推理一张~100文字区域的图片（类似门户网站截图）大概需要1000ms，我希望降低到100ms左右，有哪些可以探索的方向呢？（比如openvino/量化）感谢！

**Comment by YAOYI626** [comment]
> CPU降到100ms想多了

Hi @XiaokangLei 感谢回复, 如果是只识别清晰印刷体的话是不是可以把v3提供的模型做得更小一点呢。

**Comment by littletomatodonkey** [comment]
你好，这块只能降低模型大小，比如减少网络的深度或者宽度，然后自己训练

**Comment by XiaokangLei** [comment]
> > CPU降到100ms想多了
> 
> Hi @XiaokangLei 感谢回复, 如果是只识别清晰印刷体的话是不是可以把v3提供的模型做得更小一点呢。

自定义网络，改模型结构，这块得自己改网络框架了

**Comment by YAOYI626** [comment]
好的谢谢两位 @XiaokangLei  @littletomatodonkey

**Comment by dengmingD** [comment]
用openvino吧，会快很多
