### ISSUE TITLE
CPU训练需要多少核呢？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7428]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，理论上任意核数都可以训练起来，不过建议还是用GPU开展训练，CPU慢了很多
