### ISSUE TITLE
表格识别数据集格式问题。

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleOCR#7430]
1. 通过 PPOCRLabel 导出 JSON 标注时，提示 AttributeError: 'ElementTree' object has no attribute 'getiterator' ，通过 https://github.com/PaddlePaddle/PaddleOCR/issues/6403#issuecomment-1142078981_ 解决后，导出的JSON文件只有一行（如图），但是下载的“好未来”公共数据集中的标注是每个文件一行的。只有一行的JSON可用于训练么？
![11111](https://user-images.githubusercontent.com/75460093/187579649-05ea533c-178c-46de-bc49-472a65d44d86.jpg)

2. SLANet_ch.yml 配置文件中的 label_file_list: [train_data/table/train.txt]，这个 train.txt 的格式哪里可以参考呢？

3. 看到有 issue ( https://github.com/PaddlePaddle/PaddleOCR/issues/7424#issuecomment-1231764999_ ) 提到四点标注要用 slanet.yml 而不是 SLANet_ch.yml，使用 PPOCRLabel 中的 W 快捷键（新建矩形框）标注的数据是属于四点标注么？如果是的话，是不是不管目标表格是中文与否，都使用 slanet.yml 而不是 SLANet_ch.yml？

先谢谢了。

**Comment by WenmuZhou** [comment]
1. 标注里每一行表示一张图片的标注信息，多张图片多行
2. 表格标注格式可以参考
```txt
{"filename": "img/border_bottom_0_CJKT3VI6SYG4VR2CWA8P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td", " rowspan=\"2\"", ">", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["e", "r", "f", "a"], "bbox": [[[3, 0], [233, 0], [233, 32], [3, 32]]]}, {"tokens": ["个", "工"], "bbox": [[[233, 0], [305, 0], [305, 160], [233, 160]]]}, {"tokens": ["棋", "局", "上", "落", "子", "频", "频"], "bbox": [[[305, 0], [377, 0], [377, 160], [305, 160]]]}, {"tokens": ["E", "r", "t", "o", "L"], "bbox": [[[3, 33], [161, 33], [161, 161], [3, 161]]]}, {"tokens": ["，", "扎", "普", "一", "家", "来", "到", "阿", "根", "廷"], "bbox": [[[161, 33], [233, 33], [233, 161], [161, 161]]]}, {"tokens": ["I", "n", "g"], "bbox": [[[3, 161], [161, 161], [161, 254], [3, 254]]]}, {"tokens": ["地", "获", "取", "信", "息"], "bbox": [[[161, 161], [233, 161], [233, 254], [161, 254]]]}, {"tokens": ["B", "l"], "bbox": [[[233, 161], [305, 161], [305, 254], [233, 254]]]}, {"tokens": ["把", "经"], "bbox": [[[305, 161], [377, 161], [377, 254], [305, 254]]]}, {"tokens": ["，", "一", "步", "一", "个", "脚", "印", "开"], "bbox": [[[3, 254], [161, 254], [161, 347], [3, 347]]]}, {"tokens": ["电", "5"], "bbox": [[[161, 254], [233, 254], [233, 347], [161, 347]]]}, {"tokens": ["n", "a", "p", "j", "i", "I", "m", "h", "a"], "bbox": [[[233, 254], [305, 254], [305, 347], [233, 347]]]}, {"tokens": ["请", "，", "如", "果", "顺", "利"], "bbox": [[[305, 254], [377, 254], [377, 347], [305, 347]]]}, {"tokens": ["W", "a", "y", "s"], "bbox": [[[3, 347], [161, 347], [161, 440], [3, 440]]]}, {"tokens": [], "bbox": [[[161, 347], [233, 347], [233, 440], [161, 440]]]}, {"tokens": ["T", "V"], "bbox": [[[233, 347], [305, 347], [305, 440], [233, 440]]]}, {"tokens": ["置", "及", "赛", "道", "，", "询", "问"], "bbox": [[[305, 347], [377, 347], [377, 440], [305, 440]]]}, {"tokens": ["D", "e", "s", "i", "g", "n", "a"], "bbox": [[[3, 440], [161, 440], [161, 533], [3, 533]]]}, {"tokens": ["准", "的", "老", "建", "筑", "模"], "bbox": [[[161, 440], [233, 440], [233, 533], [161, 533]]]}, {"tokens": ["s", "c", "i", "p"], "bbox": [[[233, 440], [305, 440], [305, 533], [233, 533]]]}, {"tokens": ["警", "察", "局", "近", "日", "发", "布", "的"], "bbox": [[[305, 440], [377, 440], [377, 533], [305, 533]]]}, {"tokens": ["t", "h", "e", "r"], "bbox": [[[3, 533], [161, 533], [161, 719], [3, 719]]]}, {"tokens": ["形", "白", "底", "大", "碑", "迎", "面", "竖", "立", "，"], "bbox": [[[161, 533], [233, 533], [233, 626], [161, 626]]]}, {"tokens": ["D", "e", "r", "n", "i"], "bbox": [[[233, 533], [305, 533], [305, 626], [233, 626]]]}, {"tokens": ["态", "—", "—", "对", "持", "续"], "bbox": [[[305, 533], [377, 533], [377, 626], [305, 626]]]}, {"tokens": ["存", "在", "不", "足", "。", "对", "此", "，", "罗", "钥"], "bbox": [[[161, 626], [233, 626], [233, 719], [161, 719]]]}, {"tokens": ["i", "o"], "bbox": [[[233, 626], [305, 626], [305, 719], [233, 719]]]}, {"tokens": ["时", "，", "自", "己", "停", "在", "半"], "bbox": [[[305, 626], [377, 626], [377, 719], [305, 719]]]}]}, "gt": "<html><body><table><tr><td colspan=\"2\">erfa</td><td rowspan=\"2\">个工</td><td rowspan=\"2\">棋局上落子频频</td></tr><tr><td>ErtoL</td><td>，扎普一家来到阿根廷</td></tr><tr><td>Ing</td><td>地获取信息</td><td>Bl</td><td>把经</td></tr><tr><td>，一步一个脚印开</td><td>电5</td><td>napjiImha</td><td>请，如果顺利</td></tr><tr><td>Ways</td><td></td><td>TV</td><td>置及赛道，询问</td></tr><tr><td>Designa</td><td>准的老建筑模</td><td>scip</td><td>警察局近日发布的</td></tr><tr><td rowspan=\"2\">ther</td><td>形白底大碑迎面竖立，</td><td>Derni</td><td>态——对持续</td></tr><tr><td>存在不足。对此，罗钥</td><td>io</td><td>时，自己停在半</td></tr></table></body></html>"}
{"filename": "img/border_bottom_0_CJKT3VI6SYG4VR2CWA8P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td", " rowspan=\"2\"", ">", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["e", "r", "f", "a"], "bbox": [[[3, 0], [233, 0], [233, 32], [3, 32]]]}, {"tokens": ["个", "工"], "bbox": [[[233, 0], [305, 0], [305, 160], [233, 160]]]}, {"tokens": ["棋", "局", "上", "落", "子", "频", "频"], "bbox": [[[305, 0], [377, 0], [377, 160], [305, 160]]]}, {"tokens": ["E", "r", "t", "o", "L"], "bbox": [[[3, 33], [161, 33], [161, 161], [3, 161]]]}, {"tokens": ["，", "扎", "普", "一", "家", "来", "到", "阿", "根", "廷"], "bbox": [[[161, 33], [233, 33], [233, 161], [161, 161]]]}, {"tokens": ["I", "n", "g"], "bbox": [[[3, 161], [161, 161], [161, 254], [3, 254]]]}, {"tokens": ["地", "获", "取", "信", "息"], "bbox": [[[161, 161], [233, 161], [233, 254], [161, 254]]]}, {"tokens": ["B", "l"], "bbox": [[[233, 161], [305, 161], [305, 254], [233, 254]]]}, {"tokens": ["把", "经"], "bbox": [[[305, 161], [377, 161], [377, 254], [305, 254]]]}, {"tokens": ["，", "一", "步", "一", "个", "脚", "印", "开"], "bbox": [[[3, 254], [161, 254], [161, 347], [3, 347]]]}, {"tokens": ["电", "5"], "bbox": [[[161, 254], [233, 254], [233, 347], [161, 347]]]}, {"tokens": ["n", "a", "p", "j", "i", "I", "m", "h", "a"], "bbox": [[[233, 254], [305, 254], [305, 347], [233, 347]]]}, {"tokens": ["请", "，", "如", "果", "顺", "利"], "bbox": [[[305, 254], [377, 254], [377, 347], [305, 347]]]}, {"tokens": ["W", "a", "y", "s"], "bbox": [[[3, 347], [161, 347], [161, 440], [3, 440]]]}, {"tokens": [], "bbox": [[[161, 347], [233, 347], [233, 440], [161, 440]]]}, {"tokens": ["T", "V"], "bbox": [[[233, 347], [305, 347], [305, 440], [233, 440]]]}, {"tokens": ["置", "及", "赛", "道", "，", "询", "问"], "bbox": [[[305, 347], [377, 347], [377, 440], [305, 440]]]}, {"tokens": ["D", "e", "s", "i", "g", "n", "a"], "bbox": [[[3, 440], [161, 440], [161, 533], [3, 533]]]}, {"tokens": ["准", "的", "老", "建", "筑", "模"], "bbox": [[[161, 440], [233, 440], [233, 533], [161, 533]]]}, {"tokens": ["s", "c", "i", "p"], "bbox": [[[233, 440], [305, 440], [305, 533], [233, 533]]]}, {"tokens": ["警", "察", "局", "近", "日", "发", "布", "的"], "bbox": [[[305, 440], [377, 440], [377, 533], [305, 533]]]}, {"tokens": ["t", "h", "e", "r"], "bbox": [[[3, 533], [161, 533], [161, 719], [3, 719]]]}, {"tokens": ["形", "白", "底", "大", "碑", "迎", "面", "竖", "立", "，"], "bbox": [[[161, 533], [233, 533], [233, 626], [161, 626]]]}, {"tokens": ["D", "e", "r", "n", "i"], "bbox": [[[233, 533], [305, 533], [305, 626], [233, 626]]]}, {"tokens": ["态", "—", "—", "对", "持", "续"], "bbox": [[[305, 533], [377, 533], [377, 626], [305, 626]]]}, {"tokens": ["存", "在", "不", "足", "。", "对", "此", "，", "罗", "钥"], "bbox": [[[161, 626], [233, 626], [233, 719], [161, 719]]]}, {"tokens": ["i", "o"], "bbox": [[[233, 626], [305, 626], [305, 719], [233, 719]]]}, {"tokens": ["时", "，", "自", "己", "停", "在", "半"], "bbox": [[[305, 626], [377, 626], [377, 719], [305, 719]]]}]}, "gt": "<html><body><table><tr><td colspan=\"2\">erfa</td><td rowspan=\"2\">个工</td><td rowspan=\"2\">棋局上落子频频</td></tr><tr><td>ErtoL</td><td>，扎普一家来到阿根廷</td></tr><tr><td>Ing</td><td>地获取信息</td><td>Bl</td><td>把经</td></tr><tr><td>，一步一个脚印开</td><td>电5</td><td>napjiImha</td><td>请，如果顺利</td></tr><tr><td>Ways</td><td></td><td>TV</td><td>置及赛道，询问</td></tr><tr><td>Designa</td><td>准的老建筑模</td><td>scip</td><td>警察局近日发布的</td></tr><tr><td rowspan=\"2\">ther</td><td>形白底大碑迎面竖立，</td><td>Derni</td><td>态——对持续</td></tr><tr><td>存在不足。对此，罗钥</td><td>io</td><td>时，自己停在半</td></tr></table></body></html>"}
```
3. 如果你的坐标是四点的话，使用SLANet.yml，8个点就是用 SLANet_ch.yml

**Comment by dium6i** [comment]
> 

使用 SLANet.yml 训练识别中文表格时，配置文件中的 character_dict_path: ppocr/utils/dict/table_structure_dict.txt 是否要替换为 table_structure_dict_ch.txt ？character_type 还是保持 en 么？

**Comment by dium6i** [comment]
> 1. 标注里每一行表示一张图片的标注信息，多张图片多行
> 2. 表格标注格式可以参考
> 
> ```
> {"filename": "img/border_bottom_0_CJKT3VI6SYG4VR2CWA8P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td", " rowspan=\"2\"", ">", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["e", "r", "f", "a"], "bbox": [[[3, 0], [233, 0], [233, 32], [3, 32]]]}, {"tokens": ["个", "工"], "bbox": [[[233, 0], [305, 0], [305, 160], [233, 160]]]}, {"tokens": ["棋", "局", "上", "落", "子", "频", "频"], "bbox": [[[305, 0], [377, 0], [377, 160], [305, 160]]]}, {"tokens": ["E", "r", "t", "o", "L"], "bbox": [[[3, 33], [161, 33], [161, 161], [3, 161]]]}, {"tokens": ["，", "扎", "普", "一", "家", "来", "到", "阿", "根", "廷"], "bbox": [[[161, 33], [233, 33], [233, 161], [161, 161]]]}, {"tokens": ["I", "n", "g"], "bbox": [[[3, 161], [161, 161], [161, 254], [3, 254]]]}, {"tokens": ["地", "获", "取", "信", "息"], "bbox": [[[161, 161], [233, 161], [233, 254], [161, 254]]]}, {"tokens": ["B", "l"], "bbox": [[[233, 161], [305, 161], [305, 254], [233, 254]]]}, {"tokens": ["把", "经"], "bbox": [[[305, 161], [377, 161], [377, 254], [305, 254]]]}, {"tokens": ["，", "一", "步", "一", "个", "脚", "印", "开"], "bbox": [[[3, 254], [161, 254], [161, 347], [3, 347]]]}, {"tokens": ["电", "5"], "bbox": [[[161, 254], [233, 254], [233, 347], [161, 347]]]}, {"tokens": ["n", "a", "p", "j", "i", "I", "m", "h", "a"], "bbox": [[[233, 254], [305, 254], [305, 347], [233, 347]]]}, {"tokens": ["请", "，", "如", "果", "顺", "利"], "bbox": [[[305, 254], [377, 254], [377, 347], [305, 347]]]}, {"tokens": ["W", "a", "y", "s"], "bbox": [[[3, 347], [161, 347], [161, 440], [3, 440]]]}, {"tokens": [], "bbox": [[[161, 347], [233, 347], [233, 440], [161, 440]]]}, {"tokens": ["T", "V"], "bbox": [[[233, 347], [305, 347], [305, 440], [233, 440]]]}, {"tokens": ["置", "及", "赛", "道", "，", "询", "问"], "bbox": [[[305, 347], [377, 347], [377, 440], [305, 440]]]}, {"tokens": ["D", "e", "s", "i", "g", "n", "a"], "bbox": [[[3, 440], [161, 440], [161, 533], [3, 533]]]}, {"tokens": ["准", "的", "老", "建", "筑", "模"], "bbox": [[[161, 440], [233, 440], [233, 533], [161, 533]]]}, {"tokens": ["s", "c", "i", "p"], "bbox": [[[233, 440], [305, 440], [305, 533], [233, 533]]]}, {"tokens": ["警", "察", "局", "近", "日", "发", "布", "的"], "bbox": [[[305, 440], [377, 440], [377, 533], [305, 533]]]}, {"tokens": ["t", "h", "e", "r"], "bbox": [[[3, 533], [161, 533], [161, 719], [3, 719]]]}, {"tokens": ["形", "白", "底", "大", "碑", "迎", "面", "竖", "立", "，"], "bbox": [[[161, 533], [233, 533], [233, 626], [161, 626]]]}, {"tokens": ["D", "e", "r", "n", "i"], "bbox": [[[233, 533], [305, 533], [305, 626], [233, 626]]]}, {"tokens": ["态", "—", "—", "对", "持", "续"], "bbox": [[[305, 533], [377, 533], [377, 626], [305, 626]]]}, {"tokens": ["存", "在", "不", "足", "。", "对", "此", "，", "罗", "钥"], "bbox": [[[161, 626], [233, 626], [233, 719], [161, 719]]]}, {"tokens": ["i", "o"], "bbox": [[[233, 626], [305, 626], [305, 719], [233, 719]]]}, {"tokens": ["时", "，", "自", "己", "停", "在", "半"], "bbox": [[[305, 626], [377, 626], [377, 719], [305, 719]]]}]}, "gt": "<html><body><table><tr><td colspan=\"2\">erfa</td><td rowspan=\"2\">个工</td><td rowspan=\"2\">棋局上落子频频</td></tr><tr><td>ErtoL</td><td>，扎普一家来到阿根廷</td></tr><tr><td>Ing</td><td>地获取信息</td><td>Bl</td><td>把经</td></tr><tr><td>，一步一个脚印开</td><td>电5</td><td>napjiImha</td><td>请，如果顺利</td></tr><tr><td>Ways</td><td></td><td>TV</td><td>置及赛道，询问</td></tr><tr><td>Designa</td><td>准的老建筑模</td><td>scip</td><td>警察局近日发布的</td></tr><tr><td rowspan=\"2\">ther</td><td>形白底大碑迎面竖立，</td><td>Derni</td><td>态——对持续</td></tr><tr><td>存在不足。对此，罗钥</td><td>io</td><td>时，自己停在半</td></tr></table></body></html>"}
> {"filename": "img/border_bottom_0_CJKT3VI6SYG4VR2CWA8P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "<td", " rowspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td", " rowspan=\"2\"", ">", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["e", "r", "f", "a"], "bbox": [[[3, 0], [233, 0], [233, 32], [3, 32]]]}, {"tokens": ["个", "工"], "bbox": [[[233, 0], [305, 0], [305, 160], [233, 160]]]}, {"tokens": ["棋", "局", "上", "落", "子", "频", "频"], "bbox": [[[305, 0], [377, 0], [377, 160], [305, 160]]]}, {"tokens": ["E", "r", "t", "o", "L"], "bbox": [[[3, 33], [161, 33], [161, 161], [3, 161]]]}, {"tokens": ["，", "扎", "普", "一", "家", "来", "到", "阿", "根", "廷"], "bbox": [[[161, 33], [233, 33], [233, 161], [161, 161]]]}, {"tokens": ["I", "n", "g"], "bbox": [[[3, 161], [161, 161], [161, 254], [3, 254]]]}, {"tokens": ["地", "获", "取", "信", "息"], "bbox": [[[161, 161], [233, 161], [233, 254], [161, 254]]]}, {"tokens": ["B", "l"], "bbox": [[[233, 161], [305, 161], [305, 254], [233, 254]]]}, {"tokens": ["把", "经"], "bbox": [[[305, 161], [377, 161], [377, 254], [305, 254]]]}, {"tokens": ["，", "一", "步", "一", "个", "脚", "印", "开"], "bbox": [[[3, 254], [161, 254], [161, 347], [3, 347]]]}, {"tokens": ["电", "5"], "bbox": [[[161, 254], [233, 254], [233, 347], [161, 347]]]}, {"tokens": ["n", "a", "p", "j", "i", "I", "m", "h", "a"], "bbox": [[[233, 254], [305, 254], [305, 347], [233, 347]]]}, {"tokens": ["请", "，", "如", "果", "顺", "利"], "bbox": [[[305, 254], [377, 254], [377, 347], [305, 347]]]}, {"tokens": ["W", "a", "y", "s"], "bbox": [[[3, 347], [161, 347], [161, 440], [3, 440]]]}, {"tokens": [], "bbox": [[[161, 347], [233, 347], [233, 440], [161, 440]]]}, {"tokens": ["T", "V"], "bbox": [[[233, 347], [305, 347], [305, 440], [233, 440]]]}, {"tokens": ["置", "及", "赛", "道", "，", "询", "问"], "bbox": [[[305, 347], [377, 347], [377, 440], [305, 440]]]}, {"tokens": ["D", "e", "s", "i", "g", "n", "a"], "bbox": [[[3, 440], [161, 440], [161, 533], [3, 533]]]}, {"tokens": ["准", "的", "老", "建", "筑", "模"], "bbox": [[[161, 440], [233, 440], [233, 533], [161, 533]]]}, {"tokens": ["s", "c", "i", "p"], "bbox": [[[233, 440], [305, 440], [305, 533], [233, 533]]]}, {"tokens": ["警", "察", "局", "近", "日", "发", "布", "的"], "bbox": [[[305, 440], [377, 440], [377, 533], [305, 533]]]}, {"tokens": ["t", "h", "e", "r"], "bbox": [[[3, 533], [161, 533], [161, 719], [3, 719]]]}, {"tokens": ["形", "白", "底", "大", "碑", "迎", "面", "竖", "立", "，"], "bbox": [[[161, 533], [233, 533], [233, 626], [161, 626]]]}, {"tokens": ["D", "e", "r", "n", "i"], "bbox": [[[233, 533], [305, 533], [305, 626], [233, 626]]]}, {"tokens": ["态", "—", "—", "对", "持", "续"], "bbox": [[[305, 533], [377, 533], [377, 626], [305, 626]]]}, {"tokens": ["存", "在", "不", "足", "。", "对", "此", "，", "罗", "钥"], "bbox": [[[161, 626], [233, 626], [233, 719], [161, 719]]]}, {"tokens": ["i", "o"], "bbox": [[[233, 626], [305, 626], [305, 719], [233, 719]]]}, {"tokens": ["时", "，", "自", "己", "停", "在", "半"], "bbox": [[[305, 626], [377, 626], [377, 719], [305, 719]]]}]}, "gt": "<html><body><table><tr><td colspan=\"2\">erfa</td><td rowspan=\"2\">个工</td><td rowspan=\"2\">棋局上落子频频</td></tr><tr><td>ErtoL</td><td>，扎普一家来到阿根廷</td></tr><tr><td>Ing</td><td>地获取信息</td><td>Bl</td><td>把经</td></tr><tr><td>，一步一个脚印开</td><td>电5</td><td>napjiImha</td><td>请，如果顺利</td></tr><tr><td>Ways</td><td></td><td>TV</td><td>置及赛道，询问</td></tr><tr><td>Designa</td><td>准的老建筑模</td><td>scip</td><td>警察局近日发布的</td></tr><tr><td rowspan=\"2\">ther</td><td>形白底大碑迎面竖立，</td><td>Derni</td><td>态——对持续</td></tr><tr><td>存在不足。对此，罗钥</td><td>io</td><td>时，自己停在半</td></tr></table></body></html>"}
> ```
> 
> 3. 如果你的坐标是四点的话，使用SLANet.yml，8个点就是用 SLANet_ch.yml

使用 SLANet.yml 训练识别中文表格时，配置文件中的 character_dict_path: ppocr/utils/dict/table_structure_dict.txt 是否要替换为 table_structure_dict_ch.txt ？character_type 还是保持 en 么？

**Comment by WenmuZhou** [comment]
建议用ch的字典

**Comment by dium6i** [comment]
> 建议用ch的字典

好的，谢谢！

**Comment by emigomez** [comment]
Has anyone had success doing fine tunning with the table recognition? 
Is it possible to share a small dataset with its annotations to run an example of fine-tuning?
