### ISSUE TITLE
linux下docker部署paddleocr的gpu版本，docker显示挂起但是无法调用gpu资源问题

### ISSUE THREAD

**Issue by asietrli** [PaddlePaddle/PaddleOCR#7431]
linux下docker部署paddleocr的gpu版本，在screen窗口中挂起docker后，当天正常运行，但是第二天docker显示无法调用gpu资源，docker ps显示挂起状态，只能通过重启image才可以，请问有大佬遇到过吗

**Comment by littletomatodonkey** [comment]
这块之前应该没遇到过，可以看下docker驱动是否与物理机显卡驱动一致

**Comment by asietrli** [comment]
> ，可以看下docker驱动是否与物理机显卡驱动一致

linux装的cuda是11.7的，我用nvidia-docker拉取的11.2的镜像，docker版本是20.10.16
