### ISSUE TITLE
DB检测支持多边形吗，要修改哪里

### ISSUE THREAD

**Issue by phybrain** [PaddlePaddle/PaddleOCR#7432]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.0  PaddleOCR： 问题相关组件/Related components：DB
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml -o Optimizer.base_lr=0.0001
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，理论上是支持的，不过目前还没有适配，添加的话，数据预处理、后处理和评估指标这块的代码都需要进行修改哈
