### ISSUE TITLE
如何基于serving的pipline部署识别模型呢？只要识别模型，不需要文字检测。

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#7435]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，可以按照这个文件：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/pdserving/web_service_rec.py
进行改写，串联的时候去除检测模块即可
