### ISSUE TITLE
Bug：离线机器已指定预训练模型路径，训练时仍会联网下载。

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleOCR#7439]
具体 bug 位置如下：
https://github.com/PaddlePaddle/PaddleOCR/blob/625e9399f9a4fdf519612c5eaddaf865c7e9f9a4/ppocr/modeling/backbones/det_pp_lcnet.py#L262-L268

如将 L267 的 local_weight_path 直接改为模型路径，如 ./train_data/table/PPLCNet_x1_0_ssld_pretrained.pdparams 即可正常载入模型。

提议：
可不可以在 tools/train.py 中的如下位置，直接以 config 传入，
https://github.com/PaddlePaddle/PaddleOCR/blob/625e9399f9a4fdf519612c5eaddaf865c7e9f9a4/tools/train.py#L121

然后后续各种需要使用 config 时，各取所需。如下面的 build_model(config) 在函数内再给 BaseModel 传入 config['Architecture'] 
https://github.com/PaddlePaddle/PaddleOCR/blob/625e9399f9a4fdf519612c5eaddaf865c7e9f9a4/ppocr/modeling/architectures/__init__.py#L27-L35

这样在 _load_pretrained() 处即可增加判断配置文件中是否已指定离线的 pretrained_model 路径，从而再决定是否要下载预训练模型。

**Comment by drenched9** [comment]
你要不试下直接在配置文件的Global下的pretrained_model这里，将后面的参数写成  ./train_data/table/PPLCNet_x1_0_ssld_pretrained 试试呢？

**Comment by dium6i** [comment]
> 你要不试下直接在配置文件的Global下的pretrained_model这里，将后面的参数写成 ./train_data/table/PPLCNet_x1_0_ssld_pretrained 试试呢？

我本来就是已经写到Global下的pretrained_model这，才发现的问题……

**Comment by BeyondYourself** [comment]
的确是有这个问题，问题就出在了代码写的是http链接获取模型

**Comment by dium6i** [comment]
> 的确是有这个问题，问题就出在了代码写的是http链接获取模型

所以我建议在 build_model() 那里直接把完整的 config 传进去，后续需要什么取什么就行；现在的做法就是到了 _load_pretrained() 这儿没有可以参考的 config 了，只能联网下载。

**Comment by littletomatodonkey** [comment]
> 的确是有这个问题，问题就出在了代码写的是http链接获取模型

这时候需要把backbone部分的pretrained修改为False就好哈

**Comment by dium6i** [comment]
> > 的确是有这个问题，问题就出在了代码写的是http链接获取模型
> 
> 这时候需要把backbone部分的pretrained修改为False就好哈

试了下，还真是。
后期会优化相关代码么？比如在配置文件中注明如果指定了本地路径，需将backbone部分的pretrained设置为flse；或者从训练脚本中优化如果指定本地路径，就不再联网下载了。之前用v2.2，v2.3的时候就是在global里，指定就直接用，不指定下载用。

**Comment by lihuikenny** [comment]
> > > 的确是有这个问题，问题就出在了代码写的是http链接获取模型
> > 
> > 
> > 这时候需要把backbone部分的pretrained修改为False就好哈
> 
> 试了下，还真是。 后期会优化相关代码么？比如在配置文件中注明如果指定了本地路径，需将backbone部分的pretrained设置为flse；或者从训练脚本中优化如果指定本地路径，就不再联网下载了。之前用v2.2，v2.3的时候就是在global里，指定就直接用，不指定下载用。

这样就等于没有加载预训练模型了。最新的版本的pp_lcnetv2backbone中pretrained参数都没没有
