### ISSUE TITLE
数据集位于不同盘符，标签路径要怎么写才能训练不同盘符下的数据？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7444]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

数据集位于不同盘符，标签路径要怎么写才能训练不同盘符下的数据？微信nlanguage

**Comment by MissPenguin** [comment]
是说/和\吗，一个系统下怎么有两种盘符呢。。没遇到过这种问题，可以放到相同盘符下，或者在代码里加点规则简单处理下吧

**Comment by nissansz** [comment]
不是。
是windows下
C:, D:， 这样，不同盘

**Comment by MissPenguin** [comment]
那应该写绝对路径就行了吧，盘符都写进去

**Comment by nissansz** [comment]
如果用绝对路径，这个参数该怎么填？data_dir: 
直接留空？

**Comment by MissPenguin** [comment]
写成一个列表：[C:/***, D:/***]，label同理，ratio_list可以写成[1.0, 1.0]

**Comment by nissansz** [comment]
data_dir: [C:/, D:/]
我没看到yml文件里有ratio_list这个参数
只看到valid_ratio

标签list
 label_file_list: - C:/F/labels_combined.txt
labels_combined.txt内容些绝对路径
C:/a.jpg
D:/b.jpg
