### ISSUE TITLE
DB检测框粘连问题

### ISSUE THREAD

**Issue by Sweetwenty** [PaddlePaddle/PaddleOCR#7446]
对于一列数字或英文字母，使用DB检测，会出现只有一个大检测框的情况。
使用的模型是检测效果较好的通用模型，查阅并调整了检测模块的几个超参数，没有起到作用。
发现出现这种情况的上述图片区域特点是每行的文字区域较少，图片的其他区域检测没有问题。请问有什么解决方法？
![res1_col](https://user-images.githubusercontent.com/87378415/187830913-f24b8dd1-7662-4a28-a6a4-3ccc86169af2.jpg)

**Comment by MissPenguin** [comment]
看样子被当成竖排文本了，这种问题没办法直接调参解决，可以增加此类数据进行finetune
