### ISSUE TITLE
eval.py  GPU模式报错： FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by HAIMSTZL** [PaddlePaddle/PaddleOCR#7449]
运行 paddle.utils.run_check()和infer.py均没有问题，运行评估脚本， CPU模式没有问题，GPU报错

显卡 Tesla P40 两块
CUDA 10.2
CUDNN 7605

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04.5 LTS
-
- 版本号/Version：Paddle：  2.3.2 PaddleOCR： dygraph分支  问题相关组件/Related components： eval.py
- 
- 运行指令/Command Code：python /nfs/volume-1/GAOHAI/car_occupy/PaddleOCR/tools/eval.py -c /nfs/volume-1/GAOHAI/car_occupy/PaddleOCR/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml (在yml文件直接写入相关配置项)
- 
- 完整报错/Complete Error Message：eval model::   0%|                                                                                               | 0/6 [00:00<?, ?it/s]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1662014678 (unix time) try "date -d @1662014678" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3710 (TID 0x7f156e779740) from PID 0 ***]

**Comment by MissPenguin** [comment]
GPU模式运行infer.py是正常的吗

**Comment by HaiGao** [comment]
GPU模式运行 paddle.utils.run_check()和infer.py均没有问题，双卡机器GPU模式训练模型报一样的错误，单卡机器不报错

**Comment by HaiGao** [comment]
> GPU模式运行infer.py是正常的吗

GPU模式运行 paddle.utils.run_check()和infer.py均没有问题，双卡机器GPU模式训练模型报一样的错误，单卡机器不报错

**Comment by lipeng1109** [comment]
我的多卡也出现同样的问题，请问解决了吗
