### ISSUE TITLE
请问文本识别为乱码是什么原因？

### ISSUE THREAD

**Issue by KKKKQF** [PaddlePaddle/PaddleOCR#7450]
![1](https://user-images.githubusercontent.com/87752678/187866475-8a7eebeb-210a-444d-a53e-cd79054bd450.jpg)
输入命令为：--det_model_dir="models/en_PP-OCRv3_det_slim_infer/" --rec_model_dir="models/en_PP-OCRv3_rec_infer/" --use_angle_cls=false

**Comment by BeyondYourself** [comment]
字典用错了吧

**Comment by KKKKQF** [comment]
> 字典用错了吧

对的哈，我是直接下载的压缩包，里面这个文档就变成乱码了，后面重新下载才好，感谢您回答！
