### ISSUE TITLE
请问老师，推理可以指定用哪块GPU吗？如果有多块GPU的情况下，在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7452]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
如果指定使用1号卡，export CUDA_VISIBLE_DEVICES=1，其他情况同理

**Comment by 1998wy123** [comment]
是在运行./tools/infer/predict_system.py的时候指定哪个参数吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问老师，推理可以指定用哪块GPU吗？如果有多块GPU的情况下，在线等 (Issue #7452)





 
如果指定使用1号卡，export CUDA_VISIBLE_DEVICES=1，其他情况同理
