### ISSUE TITLE
the imp module is deprecated in favour of importlib;

### ISSUE THREAD

**Issue by fanjiuwu** [PaddlePaddle/PaddleOCR#7453]
/usr/local/python3/lib/python3.8/site-packages/setuptools/depends.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import PKG_DIRECTORY, PY_COMPILED, PY_SOURCE, PY_FROZEN

和官方一样的python3.8 ,这个警告需要处理吗？会出问题吗？

**Comment by MissPenguin** [comment]
功能都正常的话暂时可以先不管
