### ISSUE TITLE
一个奇怪的bug：det部分预测3000*3000*3的分辨率不会超显存，预测2*177*3的图片显存炸了

### ISSUE THREAD

**Issue by Jsooooooo** [PaddlePaddle/PaddleOCR#7454]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18/Windows10
- 版本号/Version：Paddle：paddlepaddle-gpu==2.1.2.post110  PaddleOCR：2.0.0 问题相关组件/Related components：det
- 运行指令/Command Code：PaddleOCR(use_angle_cls=True, lang="ch").ocr(img, det=True, rec=True, cls=False)
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "/data/ocr/ocr_interface.py", line 72, in picture2text
    results = ocr_model.ocr(img, det=True, rec=True, cls=False)
  File "/data/ocr/../ocr/paddleocr.py", line 314, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/data/ocr/../ocr/tools/infer/predict_system.py", line 91, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/data//ocr/../ocr/tools/infer/predict_det.py", line 174, in __call__
    self.predictor.run()
RuntimeError: ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 7.296997GB memory on GPU 0, 19.976196GB memory has been allocated and available memory is only 3.723328GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)

**Comment by Jsooooooo** [comment]
![error25](https://user-images.githubusercontent.com/45792387/187883920-17151322-c765-4a57-b994-7f3f83ff4d26.jpg)
补充这张报错图片

**Comment by Jsooooooo** [comment]
这张图片就是一条黑线

**Comment by LDOUBLEV** [comment]
理论上输入的高度和宽度最少大于32（检测模型的stride）
后续在代码里加一个判断逻辑。

**Comment by LDOUBLEV** [comment]
> 理论上输入的高度和宽度最少大于32（检测模型的stride） 后续在代码里加一个判断逻辑。

https://github.com/PaddlePaddle/PaddleOCR/pull/7462
