### ISSUE TITLE
请问老师，在运行./tools/infer/predict_system.py的时候用哪个参数可以指定GPU用哪块？如果有多块GPU的话，在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7455]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
通过设置 `CUDA_VISIBLE_DEVICES`来指定GPUID

**Comment by 1998wy123** [comment]
请问老师，推理是在predict_system.py添加这句代码吗？export&nbsp;CUDA_VISIBLE_DEVICES=1。还是在命令行运行的时候有这个可选参数？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请问老师，在运行./tools/infer/predict_system.py的时候用哪个参数可以指定GPU用哪块？如果有多块GPU的话，在线等 (Issue #7455)





 
通过设置 CUDA_VISIBLE_DEVICES来指定GPUID
