### ISSUE TITLE
pp-ocr v3 升级后的困惑

### ISSUE THREAD

**Issue by essexh** [PaddlePaddle/PaddleOCR#7465]
之前用的是OCR V2,    版本是 2.3   模型库用的是通用模型，脚本执行时传入模型库目录。

今天升级到OCR V3,   版本是v2.6，没有更改模型库，仍在脚本执行时传入原模型库目录。

发现文本识别准确率下降许多，许多在原版本能正确识别的都识别错了。。。

我的困惑是：
       PPOCR 升级了，模型库要下载指定的版本吗？

       比如：
              模型名称中有V2的，只能用于ocr-v2,
              模型名称中有V3的，只能用于ocr-v3,  

是这样的吗？ 恳请大神解答，谢谢！

**Comment by XiaokangLei** [comment]
v2.6默认算法是SVTR，V2默认算法是CRNN，传参rec_algorithm='CRNN'试试。PaddleOCR(rec_algorithm='CRNN')

**Comment by hiroi-sora** [comment]
是不是启动参数没加 `--rec_img_h=32` ？新版代码跑v2的库要加这个，跑v3库不用

**Comment by essexh** [comment]
谢谢hiroi-sora 、XiaokangLei 二位，我都去试试。
