### ISSUE TITLE
俄语系列识别带有字母和数字的识别结果几乎都不对

### ISSUE THREAD

**Issue by XiaokangLei** [PaddlePaddle/PaddleOCR#7466]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 11 
- 版本号/Version：Paddle：2.2.2   PaddleOCR：2.4.0.4 问题相关组件/Related components：PaddleOCR
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

lang='ru'调用默认的识别库，俄语中的英文字符和数字识别错误，几乎都是错的

![image](https://user-images.githubusercontent.com/19248640/188095690-14bf1f44-ce14-4157-bbdb-3be356be9deb.png)

**Comment by hiroi-sora** [comment]
借楼问下，俄文识别库是只有v2.0而没有v2.1和v3吗？

似乎只能在 [release/2.0](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md) 找到俄文、维吾尔文、意大利文……等语种的识别库，到 release/2.1 及以后的版本就没有这些语言了。是因为质量不佳才移除了吗

**Comment by XiaokangLei** [comment]
> 借楼问下，俄文识别库是只有v2.0而没有v2.1和v3吗？
> 
> 似乎只能在 [release/2.0](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/models_list.md) 找到俄文、维吾尔文、意大利文……等语种的识别库，到 release/2.1 及以后的版本就没有这些语言了。是因为质量不佳才移除了吗

统一为‘斯拉夫字母’模型了，包含这些语言的所有字符
