### ISSUE TITLE
only detect numbers

### ISSUE THREAD

**Issue by SSTato** [PaddlePaddle/PaddleOCR#7467]
If I only want to detect numbers, how can I set them

**Comment by LDOUBLEV** [comment]
Label the digits in the image you want to detect, and train the model using labeled data.

**Comment by SSTato** [comment]
> It is possible to exclude non-numeric parts based on the recognized text.

What I mean is that I would like to use OCR to recognize only numbers, just as I would use the parameter to specify the language only, and I don't know if this parameter is now available to specify the recognition range

**Comment by LDOUBLEV** [comment]
The parameter that recognizes only numbers is not available in PaddleOCR.
