### ISSUE TITLE
I have problem using model PP-OCR v3 on Android

### ISSUE THREAD

**Issue by duongvvuet** [PaddlePaddle/PaddleOCR#7468]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Anddroid
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Hello everyone ...

I run android_demo and it worked fine. However it is using the model rec v2.
I want to use model Rec v3. I downloaded the rec v3 model at [https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_slim_infer.nb](https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_slim_infer.nb)
My application can load the model but infer gives error and the application exits.
The error is as follows...

![image](https://user-images.githubusercontent.com/51939859/188114502-4154a86e-878e-4dd7-937d-eeeac6119c65.png)
---------------------------------------------------------
I tried tweaking a few things in ocr_crnn_process.cpp as follows....

![image](https://user-images.githubusercontent.com/51939859/188115338-87b89545-4894-4f0d-86e0-b66f844d52a4.png)

but the error is still unresolved...

![image](https://user-images.githubusercontent.com/51939859/188116031-5ac21c6f-57ce-4805-bc70-29fb30a41393.png)

-> How can I use rec PP-OCRv3 model instead of rec PP-OCRv2 on Android? Can anyone help me?

**Comment by NaumanHSA** [comment]
Same issue with me, is there any solution to this? I want to use PP-OCRv3 recognition model.

**Comment by NaumanHSA** [comment]
I solved it by converting the models with Paddlelite 2.10 (same version used in the demo).
