### ISSUE TITLE
混合多语种的东亚模型

### ISSUE THREAD

**Issue by fir05** [PaddlePaddle/PaddleOCR#7470]
能否推出一个混合多语种的东亚模型？主要是 简繁英日，这4个几乎涵盖绝大部分日常场景了。

下游OCR软件的用户，不知道怎么训练。 我日常用到的最准确的一个OCR是手势软件 MouseInc 里的OCR识别。它好像是调用一个有道未公布的API，能够准确地识别出 简繁英日 各种语言。真希望PaddleOCR 实现类似的模型。

**Comment by andyjpaddle** [comment]
你好，需求已记录，后续会安排计划，这边也可以尝试自己训练，构造一个多语种的数据集，用v3识别算法进行训练

**Comment by yangy996** [comment]
可以根据这篇文章去标注数据集就可以实现多语种检测模型
https://blog.csdn.net/YY007H/article/details/124491217

**Comment by cumthxy** [comment]
> 可以根据这篇文章去标注数据集就可以实现多语种检测模型 https://blog.csdn.net/YY007H/article/details/124491217

别瞎做广告行不行。写的啥也不是，跟这个问题有关系么？你就下复制你博客的链接

**Comment by yangy996** [comment]
> 

我哪里瞎做广告了，现在官网已经给出了各种语言识别模型，但是检测模型是无法区分是什么语种，按我文章里的方法，先进行语种分类，后做识别，有什么问题吗？

**Comment by jack-gits** [comment]
还收钱

> 可以根据这篇文章去标注数据集就可以实现多语种检测模型 https://blog.csdn.net/YY007H/article/details/124491217

**Comment by genausz** [comment]
请问现在又混合多语言的模型了吗？针对同一个图片里面又3-4种语言的情况。

**Comment by genausz** [comment]
请问现在有混合多语言的模型了吗？针对同一个图片里面又3-4种语言的情况。
