### ISSUE TITLE
v2.6 表格识别模型转onnx出现问题

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#7472]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：  paddle2onnx --model_dir /root/ocr/inference/en_ppocr_mobile_v2.0_table_structure_infer  --model_filename inference.pdmodel --params_filename inference.pdiparams  --save_file /root/ocr/inference/table_onnx/model.onnx --input_shape_dict="{'x':[-1,3,-1,-1]}"  --opset_version 11  --enable_onnx_checker True
- 完整报错/Complete Error Message：
- 2022-09-03 11:52:28 [WARNING]   [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle 
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /root/ocr/inference/en_ppocr_mobile_v2.0_table_structure_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path: /root/ocr/inference/en_ppocr_mobile_v2.0_table_structure_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] LodTensorArray is not supported.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,lod_array_length,select_input,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

**Comment by mingo-doer** [comment]
@WenmuZhou

**Comment by WenmuZhou** [comment]
en_ppocr_mobile_v2.0_table_structure_infer模型暂未支持转onnx，不过slanet已经做了支持，可以用slanet

**Comment by cvanilla** [comment]
> en_ppocr_mobile_v2.0_table_structure_infer模型暂未支持转onnx，不过slanet已经做了支持，可以用slanet

我使用slanet也出现了以下错误，请问有什么环境要求吗？

Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] LodTensorArray is not supported.
[Paddle2ONNX] Oops, there are some operators not supported yet, including lod_array_length,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

**Comment by mingo-doer** [comment]
> > en_ppocr_mobile_v2.0_table_structure_infer模型暂未支持转onnx，不过slanet已经做了支持，可以用slanet
> 
> 我使用slanet也出现了以下错误，请问有什么环境要求吗？
> 
> Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdmodel [Paddle2ONNX] Paramters file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [Paddle2ONNX] LodTensorArray is not supported. [Paddle2ONNX] Oops, there are some operators not supported yet, including lod_array_length,tensor_array_to_tensor,while,write_to_array, [ERROR] Due to the unsupported operators, the conversion is aborted. Aborted (core dumped)

ch_ppstructure_mobile_v2.0_SLANet 用中文的模型 我试了是没什么问题的   
但是转换后，使用onnx的效果不如inference的结果

**Comment by cdycdycdy** [comment]
> > > en_ppocr_mobile_v2.0_table_structure_infer模型暂未支持转onnx，不过slanet已经做了支持，可以用slanet
> > 
> > 
> > 我使用slanet也出现了以下错误，请问有什么环境要求吗？
> > Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdmodel [Paddle2ONNX] Paramters file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [Paddle2ONNX] LodTensorArray is not supported. [Paddle2ONNX] Oops, there are some operators not supported yet, including lod_array_length,tensor_array_to_tensor,while,write_to_array, [ERROR] Due to the unsupported operators, the conversion is aborted. Aborted (core dumped)
> 
> ch_ppstructure_mobile_v2.0_SLANet 用中文的模型 我试了是没什么问题的 但是转换后，使用onnx的效果不如inference的结果

我在openvino框架下试了ch_ppstructure_mobile_v2.0_SLANet.onnx模型，识别结果跟inference偏差挺大的，请问，目前有解决方法了吗

**Comment by cdycdycdy** [comment]
> > > en_ppocr_mobile_v2.0_table_structure_infer模型暂未支持转onnx，不过slanet已经做了支持，可以用slanet
> > 
> > 
> > 我使用slanet也出现了以下错误，请问有什么环境要求吗？
> > Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdmodel [Paddle2ONNX] Paramters file path: ../inference/en_ppstructure_mobile_v2.0_SLANet_infer/inference.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [Paddle2ONNX] LodTensorArray is not supported. [Paddle2ONNX] Oops, there are some operators not supported yet, including lod_array_length,tensor_array_to_tensor,while,write_to_array, [ERROR] Due to the unsupported operators, the conversion is aborted. Aborted (core dumped)
> 
> ch_ppstructure_mobile_v2.0_SLANet 用中文的模型 我试了是没什么问题的 但是转换后，使用onnx的效果不如inference的结果

您好，我用paddle2onnx转ch_ppstructure_mobile_v2.0_SLANet中文模型时，会出现以下提示：
(paddle_env) H:\PaddleOcr\ppocrv3_mnn\PaddleDemo\x64\Release\models>paddle2onnx --model_dir ./ch_ppstructure_mobile_v2.0_SLANet_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ch_ppstructure_m
obile_v2.0_SLANet_infer.onnx --enable_dev_version True --opset_version 13 --enable_onnx_checker True --input_shape_dict="{'image':[-1, 3, -1, -1]}"
?[1;31;40m2023-03-08 09:45:31 [WARNING] [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/ma
in/paddle ?[0m
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./ch_ppstructure_mobile_v2.0_SLANet_infer\inference.pdmodel
[Paddle2ONNX] Paramters file path: ./ch_ppstructure_mobile_v2.0_SLANet_infer\inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Detected there's control flow 'while' op in your model, this requires the minimal opset version of 13.
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_9.tmp_0', it will rename to 'p2o.fill_constant_9.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_15.tmp_0', it will rename to 'p2o.fill_constant_15.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_21.tmp_0', it will rename to 'p2o.fill_constant_21.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'p2o.fill_constant_15.tmp_0.0', it will rename to 'p2o.p2o.fill_constant_15.tmp_0.0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_5.tmp_0', it will rename to 'p2o.fill_constant_5.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_23.tmp_0', it will rename to 'p2o.fill_constant_23.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'p2o.fill_constant_9.tmp_0.0', it will rename to 'p2o.p2o.fill_constant_9.tmp_0.0.0'.
[Paddle2ONNX] Find dumplicate output name 'assign_0.tmp_0', it will rename to 'p2o.assign_0.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'transpose_0.tmp_0', it will rename to 'p2o.transpose_0.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'tmp_4', it will rename to 'p2o.tmp_4.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_1.b_0', it will rename to 'p2o.linear_1.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.w_1', it will rename to 'p2o.gru_cell_0.w_1.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_3.b_0', it will rename to 'p2o.linear_3.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_1.w_0', it will rename to 'p2o.linear_1.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_0.w_0', it will rename to 'p2o.linear_0.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_5.b_0', it will rename to 'p2o.linear_5.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_9.tmp_0', it will rename to 'p2o.fill_constant_9.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_23.tmp_0', it will rename to 'p2o.fill_constant_23.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'assign_0.tmp_0', it will rename to 'p2o.assign_0.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_5.w_0', it will rename to 'p2o.linear_5.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_15.tmp_0', it will rename to 'p2o.fill_constant_15.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.b_0', it will rename to 'p2o.gru_cell_0.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_5.tmp_0', it will rename to 'p2o.fill_constant_5.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_2.w_0', it will rename to 'p2o.linear_2.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_4.w_0', it will rename to 'p2o.linear_4.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_6.w_0', it will rename to 'p2o.linear_6.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.w_0', it will rename to 'p2o.gru_cell_0.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.b_1', it will rename to 'p2o.gru_cell_0.b_1.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_21.tmp_0', it will rename to 'p2o.fill_constant_21.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_3.w_0', it will rename to 'p2o.linear_3.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'transpose_0.tmp_0', it will rename to 'p2o.transpose_0.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_6.b_0', it will rename to 'p2o.linear_6.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_4.b_0', it will rename to 'p2o.linear_4.b_0.0'.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2023-03-08 09:45:32 [INFO]      ===============Make PaddlePaddle Better!================
2023-03-08 09:45:32 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s

您那有遇到过吗
