### ISSUE TITLE
代码可读性差，过度嵌套，导致嵌套灾难

### ISSUE THREAD

**Issue by kongchibin** [PaddlePaddle/PaddleOCR#7475]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
明确说下具体哪里存在问题？
