### ISSUE TITLE
如何基于自己的数据集再训练检测模型，并在调用paddleocr库时加载自己训练好的模型

### ISSUE THREAD

**Issue by ybshaw** [PaddlePaddle/PaddleOCR#7479]
如题，想在自己的数据集上二次训练检测模型，想问下应该怎么操作呢，并且训练好之后在调用paddleOCR库时，可以加载自己训练好的模型吗，就类似transformer加载自定义的BERT模型一样

**Comment by tink2123** [comment]
可以加载自己训练好的模型，通过修改 det_mode_dir= xxx 参数更换模型路径
