### ISSUE TITLE
Blazor调用PaddleOCR服务实现图片识别的应用

### ISSUE THREAD

**Issue by neozhu** [PaddlePaddle/PaddleOCR#7481]
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1549611/188303857-b7016c25-6144-4912-a672-25b23bb47edb.png">

https://www.youtube.com/watch?v=15xaPiU9yoM
https://github.com/neozhu/CleanArchitectureWithBlazorServer

效果真的不错

**Comment by tink2123** [comment]
Cool！
