### ISSUE TITLE
paddlepaddle-gpu运行错误

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7483]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： ubuntu22,  python3.7,  CUDA11.7
- 版本号/Version：Paddle：2.3.2  PaddleOCR： 2.6.0 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：paddleocr --image_dir ./testdata/12.png --use_angle_cls true --lang en --use_gpu false
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/35327931/188369624-9439caa0-50bc-4ac7-bb75-f4e7e3d3cee3.png)

**Comment by WenmuZhou** [comment]
cuda目前最高支持到11.6

**Comment by ericosmic** [comment]
> cuda目前最高支持到11.6

目前容器中的cuda 是10.2
![image](https://user-images.githubusercontent.com/35327931/188542957-a3de9459-33c5-4eb9-9dfc-af16fd694ac8.png)

所以这个问题应该和cuda版本没有关系

**Comment by WenmuZhou** [comment]
试一下paddle.utiks.tun_check()
