### ISSUE TITLE
PPOCRLabel标注VQA问题，导出crop_img文件夹为空

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleOCR#7484]
您好，我在使用PPOCRLabel标注VQA问题时，标注了10张图片，在导出文件时，分别点击“自动导出标记结果”和“导出识别结果”，会自动生成crop_img文件夹，但该文件夹为空。这是什么原因导致的呢？

**Comment by huangye123** [comment]
遇到同样问题，导出时crop_img和rec_gt都为空。
