### ISSUE TITLE
使用ppstruct 报错

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7490]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu22, python3.7, paddlepaddle docker image
- 版本号/Version：Paddle：2.3.2 PaddleOCR：2.6.0 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：使用代码运行
![image](https://user-images.githubusercontent.com/35327931/188422191-5a320a3f-8cb6-405b-b4f6-ef053bbdfa03.png)

- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/35327931/188422028-8b775282-7809-475b-927d-b430a6ed22c6.png)
![image](https://user-images.githubusercontent.com/35327931/188422029-3103acda-740f-4a56-bebf-ebd8bdd72bc7.png)

**Comment by WenmuZhou** [comment]
你好，这边未能复现问题，辛苦删除~/.paddleocr/ 目录下的文件，然后重新执行一下看看

**Comment by ericosmic** [comment]
> 
使用cuda11.7  是不支持吗？ 必须要降低cuda版本吗

**Comment by ericosmic** [comment]
> 你好，这边未能复现问题，辛苦删除~/.paddleocr/ 目录下的文件，然后重新执行一下看看
删除后，还是一样的问题， 是否有可能是cuda版本问题？ 我用的是cuda11.7

**Comment by ericosmic** [comment]
> 你好，这边未能复现问题，辛苦删除~/.paddleocr/ 目录下的文件，然后重新执行一下看看

删除后还是一样的报错， 是否和cuda版本相关， 我用的是cuda11.7

**Comment by WenmuZhou** [comment]
降级到11.6及一下吧
