### ISSUE TITLE
Detection .nb Model's Size is too Large

### ISSUE THREAD

**Issue by 7ZFG1** [PaddlePaddle/PaddleOCR#7494]
I trained a detection model and I optimized it using Paddle-Lite but the .nb model's size is very large(128 mb) and it doesnt work fast on mobile. Is there any solution to decrease model size?

**Comment by WenmuZhou** [comment]
You can try a lighter detection model

**Comment by 7ZFG1** [comment]
Which configuration .yml file should i use. Because when i try to train a detection model, the output will be large size. Thanks for your answer.

**Comment by WenmuZhou** [comment]
this https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml

**Comment by 7ZFG1** [comment]
I trained a detection model using this yml file. When i test the model using this command "python3 tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./doc/imgs_en/" Global.pretrained_model="./output/det_db/best_accuracy"" it seems that everything is normal but when i convert the model to inference model, the model performence's are become very bad. Is there any solution?

**Comment by WenmuZhou** [comment]
Are parameters loaded when converting the model？
