### ISSUE TITLE
请问有多个LMDBDataSet格式的数据集时，配置文件应该如何写

### ISSUE THREAD

**Issue by 1687412531** [PaddlePaddle/PaddleOCR#7495]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
将这些数据集放在一个文件夹下，然后文件夹路径赋值给Train.dataset.data_dir

**Comment by 1687412531** [comment]
dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list: ["./train_data/dev_15.txt","./train_data/dev_100.txt","./train_data/dev_360.txt"]
    ratio_list: [1.0,0.15,0.04]

如果像这种，转换成LMDBDataSet格式，那label_file_list 和 ratio_list应该怎么写。

**Comment by 1687412531** [comment]
> 将这些数据集放在一个文件夹下，然后文件夹路径赋值给Train.dataset.data_dir

dataset:
name: SimpleDataSet
data_dir: ./train_data/
label_file_list: ["./train_data/dev_15.txt","./train_data/dev_100.txt","./train_data/dev_360.txt"]
ratio_list: [1.0,0.15,0.04]

如果像这种，转换成LMDBDataSet格式，那label_file_list 和 ratio_list应该怎么写。

**Comment by WenmuZhou** [comment]
fillist就不需要了，具体的你看一下lmdbdataset的代码

**Comment by 1687412531** [comment]
> filelist就不需要了，具体的你看一下lmdbdataset的代码

好的，多谢
