### ISSUE TITLE
运行ocr识别没有生成结果

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7498]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddleocr docker容器， cuda10.2 ， python3.7
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.0 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：代码运行
![image](https://user-images.githubusercontent.com/35327931/188544074-ab5d1594-f666-4232-bb51-88190d719bf3.png)

- 完整报错/Complete Error Message：
运行过程没有报错，但是也没有生成结果
![image](https://user-images.githubusercontent.com/35327931/188543507-176788e9-aa30-4024-9999-a0c487d4738a.png)
![result](https://user-images.githubusercontent.com/35327931/188544221-c1fdc356-0f8b-480c-8e9b-8534ddbf2666.jpg)

**Comment by littletomatodonkey** [comment]
你好，我这边使用下面的命令运行没有问题

```py
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="en")  # need to run only once to download and load model into memory
img_path = '../PaddleOCR_pub/doc/imgs_en/254.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
```


![image](https://user-images.githubusercontent.com/14270174/188892658-ee686238-66ad-4be4-984e-c590d9cc2fac.png)
