### ISSUE TITLE
请问python推理gpu开启加速的途径有哪些

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7505]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
1. trt + fp16
2. 把normalize等操作放在网络里，gpu计算
3. 模型量化

**Comment by 1998wy123** [comment]
请问trt + fp16是参数还是？

**Comment by littletomatodonkey** [comment]
trt的推理，参数与fp32相同
