### ISSUE TITLE
paddle-gpu无法使用gpu

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7506]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu16,  cuda11.6 , cudnn8.4, python3.7
- 版本号/Version：Paddle：paddle-gpu2.3.2  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：paddle.utils.run_check()
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/35327931/188619563-4bba30e1-1c7f-4901-9493-624fe4cc7946.png)

**Comment by littletomatodonkey** [comment]
你好，麻烦先把cpu和gpu的paddle都卸载掉，再安装paddlepaddle-gpu看下

**Comment by ericosmic** [comment]
> 

卸载重装pp-gpu，运行报警信息如下， cuda版本11.6
![image](https://user-images.githubusercontent.com/35327931/189023163-2b2a519d-14ae-49e7-96d2-9e7edc873894.png)

**Comment by BeyondYourself** [comment]
看报错是cuda没安装或者安装设置不对
