### ISSUE TITLE
请问paddlepaddle2.0.0的版本最高支持什么版本的OCR

### ISSUE THREAD

**Issue by cnnchan** [PaddlePaddle/PaddleOCR#7509]
- 系统环境/System Environment：Ubuntu18.04+py3.6.9，CPU
- 版本号/Version：Paddle：2.0.0rc0（CPU）  PaddleOCR：2.6（最新）
- 运行指令/Command Code：python3 tools/infer/predict_system.py --image_dir ./img-test/apimage --det_model_dir ./inference/en_PP-OCRv3_det_infer/ --rec_model_dir ./inference/en_PP-OCRv3_rec_slim_infer/ --cls_model_dir ./inference/ch_ppocr_mobile_v2.0_cls_slim_infer/ --use_angle_cls=True --rec_char_dict_path ./ppocr/utils/en_dict.txt --use_gpu=False
- 完整报错/Complete Error Message：
  Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 228, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 161, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 85, in __call__
    img_crop_list)
  File "/home/chan/PaddleOCR/PaddleOCR/tools/infer/predict_cls.py", line 113, in __call__
    self.predictor.try_shrink_memory()
AttributeError: 'paddle.fluid.core_avx.PaddleInferPredictor' object has no attribute 'try_shrink_memory'

我因为要部署在小车上，arm64架构，只能找到2.0.0版本的paddlepaddle安装包，此时如果用最新版本的OCR就会出现这样的问题，请问此版本的paddle框架下，最先进的OCR版本和infer模型是什么呀

**Comment by LDOUBLEV** [comment]
try shrink memory先删掉吧，可以不用

你直接pip安装的paddle paddle包不能用吗，
另外，你是在哪找的arm64上能用的paddle2.0.0版本
