### ISSUE TITLE
图片宽高有较小差异时， 检测结果经常差异巨大

### ISSUE THREAD

**Issue by suchxyz** [PaddlePaddle/PaddleOCR#7510]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：2.1 Paddle：  PaddleOCR： 2.4  问题相关组件/Related components： ch_PP-OCRv2_det_infer
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

从同一张原图中，截取不同高度的图片，作为ocr的输入。 检测模型输出效果差距很大，经常出现det效果太差，影响后续的rec的情况
请问这种情况有什么优化的方案吗？

如下为两张示意图：
![1](https://user-images.githubusercontent.com/51903573/188775186-19b50822-92dc-4636-9c46-47be5550c103.jpg)

![2](https://user-images.githubusercontent.com/51903573/188775345-a27c0e26-11f2-4419-81ca-1e8089f2ff9a.jpg)

**Comment by suchxyz** [comment]
比如： “军事” 这两个字的框取到了 “小视频” 边上，包含了右边的部首“页”。  识别的时候，“军事”会变成“页军事”

**Comment by MissPenguin** [comment]
看你用的还是v2的模型，用v3的模型试试呢
