### ISSUE TITLE
请问老师，pp-structure的论文有吗？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7511]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
论文还在撰写中，可以先参考中文技术报告：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/PP-Structurev2_introduction.md
