### ISSUE TITLE
转换成onnx模型后使用gpu推理速度比cpu还慢

### ISSUE THREAD

**Issue by MgArcher** [PaddlePaddle/PaddleOCR#7516]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- onnxruntime-gpu==1.9.0

在使用onnxruntime-gpu进行推理时发现一张图片耗时在3s以上，继续传入相同图片耗时下降到0.5s。更换图片传入耗时又在3s左右

**Comment by QQQTAO** [comment]
> 

官方代码推理时onnxruntime没有使用GPU
![image](https://user-images.githubusercontent.com/48081128/189123816-c5303bd0-b139-4892-8c0f-061df9941764.png)

**Comment by qwe7771** [comment]
我也遇到同样的问题了

**Comment by zyboyoung** [comment]
加一，也遇到这个问题，修改了onnx的推理代码加上gpu之后，发现推理速度比cpu慢很多，请教下是为什么呢
![1690339005143](https://github.com/PaddlePaddle/PaddleOCR/assets/22249303/d22b14d9-8192-43ef-8707-14f570ce8a49)

**Comment by Chenwe111** [comment]
> 加一，也遇到这个问题，修改了onnx的推理代码加上gpu之后，发现推理速度比cpu慢很多，请教下是为什么呢 ![1690339005143](https://user-images.githubusercontent.com/22249303/256093033-d22b14d9-8192-43ef-8707-14f570ce8a49.jpg)

我也遇到了，请问后来解决了吗

**Comment by alonge** [comment]
+1 同样的问题

**Comment by lsx66** [comment]
+1 遇到同样的问题, 有解决的吗

**Comment by 478756994** [comment]
> +1 遇到同样的问题, 有解决的吗

使用tensorrt provider
