### ISSUE TITLE
Is there any option to whitelist or blacklist character in PaddleOcr

### ISSUE THREAD

**Issue by arhamshah** [PaddlePaddle/PaddleOCR#7519]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/7515

<div type='discussions-op-text'>

<sup>Originally posted by **arhamshah** September  7, 2022</sup>
In pytesseract, there is an option to whitelist or blacklist the characters. I get '工' instead of '1' so I wanted to know whether it supports or are there any other options available to overcome this issue ? </div>

**Comment by tink2123** [comment]
Currently paddleocr does not have this function, we will consider adding it in the next version, thanks for your feedback. 
Short term solution: you can try to replace blacklisted characters by postprocessing.

**Comment by arhamshah** [comment]
Thanks for your update!
