### ISSUE TITLE
关于DB得到二值图的代码问题

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#7520]
动手学ocr电子书里又阈值图和概率图 的代码，为什么没有二值图的呢？哪位朋友能提供一下呢？

**Comment by LDOUBLEV** [comment]
训练时二值图是计算得到的，可以看下DB论文里的公式
预测时概率图二值化就是二值图了

**Comment by hyybuaa** [comment]
> 训练时二值图是计算得到的，可以看下DB论文里的公式 预测时概率图二值化就是二值图了

预测是我看模型输出只有一个map结果，这个map的概率>0值置为255，否则为0，这样可以得到二值图吗
