### ISSUE TITLE
运行ppocr 预测代码报错

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7522]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18, cuda10.2 
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
![image](https://user-images.githubusercontent.com/35327931/188847530-2a38e05a-17d5-493a-84b5-074ae05989d5.png)

- 完整报错/Complete Error Message：
![Screenshot from 2022-09-07 17-43-15](https://user-images.githubusercontent.com/35327931/188847598-c795c469-29fc-4b75-855c-79d72fbea636.png)

**Comment by MissPenguin** [comment]
paddle安装成功了吗，可以用这个方式验证下：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-8-%E4%B8%89%E3%80%81%E9%AA%8C%E8%AF%81%E5%AE%89%E8%A3%85

**Comment by ericosmic** [comment]
> paddle安装成功了吗，可以用这个方式验证下：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-8-%E4%B8%89%E3%80%81%E9%AA%8C%E8%AF%81%E5%AE%89%E8%A3%85
安装成功了的
![image](https://user-images.githubusercontent.com/35327931/189021353-beb24771-c937-439f-ba89-e33fd177c34c.png)

**Comment by BeyondYourself** [comment]
python版本有点过高了，建议换乘3.7的

**Comment by ericosmic** [comment]
> python版本有点过高了，建议换乘3.7的


把python换到3.7, cuda10.2  , paddle 检查cuda通过，但是运行代码还是错误
![image](https://user-images.githubusercontent.com/35327931/189283394-beb26f5b-c16d-4d05-b2db-abcc7a61fa3b.png)
