### ISSUE TITLE
微调模型的参数选择

### ISSUE THREAD

**Issue by ybshaw** [PaddlePaddle/PaddleOCR#7523]
请问在自己的数据集上微调**检测模型**时，参数如何选择呢。按照默认的参数微调时特别慢（普通电脑cpu山微调），大概20分钟一个epoch，训练集大概200张图片；这个怎么解决呢，微调的时候epoch要怎么选择比较好呢（cpu上），我看默认的是1500个epoch

**Comment by MissPenguin** [comment]
这个微调慢不是参数的问题，CPU训练肯定很慢的，建议换到GPU
