### ISSUE TITLE
How to enable batch processing?

### ISSUE THREAD

**Issue by adam-wrobel** [PaddlePaddle/PaddleOCR#7524]
- 系统环境/System Environment：Linux 5.4.209-116.363.amzn2.x86_64
- 版本号/Version：Paddle：paddlepaddle-gpu==2.3.1.post116  PaddleOCR：2.6.0.1 问题相关组件/Related components：
- 运行指令/Command Code：
```bash
paddleocr --image_dir ../big_images --max_batch_size 200  --ocr_version PP-OCRv3 --show_log False --use_gpu True --rec_batch_num 200 --cls_batch_num 200 --precision fp32 --lang en --use_angle_cls true
```
- 完整报错/Complete Error Message：there is no error, I just cant enable batch processing on GPU

# Issue
No matter how high I set the batch size, batch num, framework processes images one at a time. GPU is utilized in a small fraction. How to enable this? I want to fill whole GPU memory to speed up processing.

**Comment by LDOUBLEV** [comment]
Batch >1 is not supported as the dynamic input.

It is recommended to start multiple python processes like https://github.com/PaddlePaddle/PaddleOCR/blob/6f677d609c2b306c95ef64af00ddd991c7918ae9/tools/infer/predict_system.py#L221

However, the use_mp is not supported in the paddleocr whl.
