### ISSUE TITLE
请问老师，文档结构推理中，这个txt文件在哪个文件夹下呢？还是自己创建的呢？--ser_dict_path=../train_data/XFUND/class_list_xfun.txt \

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7528]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
这个下载好ppocr处理好后的xfund数据包，就有哈

**Comment by guoxiaoyue111111** [comment]
同问， https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar 下载并解压后，XFUND目录下并没有class_list_xfun.txt这个文件。@littletomatodonkey  ，您说的ppocr处理是什么意思呢？
