### ISSUE TITLE
paddleocr 无法复原文档中表格

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7529]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.7  ， cuda11.6
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：  `paddleocr --image_dir=testdata/1.png --type=structure --recovery=true`
- 完整报错/Complete Error Message：
对官方提供的图片转换为word，识别结果没有识别出图片中原有的表格
![image](https://user-images.githubusercontent.com/35327931/189029446-ef60b5e5-b3f9-440a-bda3-3e3efd63dd85.png)

**Comment by an1018** [comment]
WPS显示表格问题，可以用word打开，或者clone最新的dygraph代码，已修复这个问题~
