### ISSUE TITLE
在尝试将SEED推理模型转换为onnx模型时报错有算子不支持

### ISSUE THREAD

**Issue by labmanno004** [PaddlePaddle/PaddleOCR#7530]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8
- 版本号/Version：Paddle： 2.3.2 PaddleOCR：2.6.0.1 问题相关组件/Related components：paddle2onnx：1.0.0
- 运行指令/Command Code：paddle2onnx --model_dir ./inference/SEED --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/rec_onnx/seed-rec-ppocr-op13-fp32-N.onnx --opset_version 13 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True
- 完整报错/Complete Error Message：[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference/SEED/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./inference/SEED/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted

请问这是当前还不支持将SEED的推理模型转换为onnx模型吗？还是说我的某些参数设置或者环境有问题？

**Comment by tink2123** [comment]
onnx 模型目前还不支持
