### ISSUE TITLE
请问PaddleOCR中，提供的中文识别模型，训练时都使用了哪些开源数据集？

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7532]
PaddleOCR提供的  V1，V2，V3  三个版本的中文识别模型， 官方在训练时都使用了哪些中文数据集呀？ 有开源的么

**Comment by LDOUBLEV** [comment]
可以看下PPOCRv3的技术报告，里面有训练数据以及训练策略的详细介绍 https://arxiv.org/abs/2206.03001v2
