### ISSUE TITLE
jetson nano 推理阶段显存过高 predict_system显存占用大于predict_rec

### ISSUE THREAD

**Issue by HAIMSTZL** [PaddlePaddle/PaddleOCR#7533]
设备显存原始占用1.0G，运行predict_system.py 显存占用2.7G, 运行predict_rec.py，显存占用2.8G 调整参数 --gpu_mem 没有效果
问题 1: 为什么单独运行文本识别要比运行文本检测+识别显存占用更高?
问题2: 请问如和在使用GPU的同时，如何降低或者控制显存占用？
问题3: 如果显存无法降低，那么模型变小的意义是什么？

![系统环境](https://user-images.githubusercontent.com/20981221/189088742-72c9a124-4bbf-4225-9fbb-366126708723.png)
![nothing](https://user-images.githubusercontent.com/20981221/189088759-ab444bed-b193-49b5-adb3-34339b5bffaa.png)
![predict_system](https://user-images.githubusercontent.com/20981221/189088780-093f512b-e2f2-44ff-a206-36bc158619da.png)
![predict_rec](https://user-images.githubusercontent.com/20981221/189088799-c49c8d8c-a520-4b1c-b27c-51abda7c8b69.png)

**Comment by HaiGao** [comment]
> 设备显存原始占用1.0G，运行predict_system.py 显存占用2.7G, 运行predict_rec.py，显存占用2.8G 调整参数 --gpu_mem 没有效果 问题 1: 为什么单独运行文本识别要比运行文本检测+识别显存占用更高? 问题2: 请问如和在使用GPU的同时，如何降低或者控制显存占用？ 问题3: 如果显存无法降低，那么模型变小的意义是什么？
> 
> ![系统环境](https://user-images.githubusercontent.com/20981221/189088742-72c9a124-4bbf-4225-9fbb-366126708723.png) ![nothing](https://user-images.githubusercontent.com/20981221/189088759-ab444bed-b193-49b5-adb3-34339b5bffaa.png) ![predict_system](https://user-images.githubusercontent.com/20981221/189088780-093f512b-e2f2-44ff-a206-36bc158619da.png) ![predict_rec](https://user-images.githubusercontent.com/20981221/189088799-c49c8d8c-a520-4b1c-b27c-51abda7c8b69.png)

最后一张图为单独运行 predict_rec.py显存占用情况

**Comment by LDOUBLEV** [comment]
predict system运行的是文本检测和文本识别两个模型，predict rec只运行了文本识别，占据的显存，前者大一些

另外，文本检测模型的输入远大于文本识别，所以predict system占据的显存会比predictrec 大很多

**Comment by HaiGao** [comment]
> predict system运行的是文本检测和文本识别两个模型，predict rec只运行了文本识别，占据的显存，前者大一些
> 
> 另外，文本检测模型的输入远大于文本识别，所以predict system占据的显存会比predictrec 大很多

您好，我也是这么认为的，测试下来，结果是相反的

**Comment by HaiGao** [comment]
直接转onnx用就好，至于原始模型为何出现这个问题，我不清楚
