### ISSUE TITLE
Error Paddle.sum()

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#7536]
when I training SEED recognition, I have err:

```
TypeError: sum() got an unexpected keyword argument 'dim'
```
It comes from rec_aster_loss.py:
```
 similarity = paddle.sum(
            x1 * x2, dim=-1) / (paddle.norm(
                x1, axis=-1) * paddle.norm(
                    x2, axis=-1) + self.epsilon)
```

System Environment：
paddlepaddle-gpu: 2.3.2.post111
paddleocr: 2.5

Thank for your reply!!

**Comment by LDOUBLEV** [comment]
It is a bug, The correct behavior is paddle.sum(x1*x2, axis=-1)
It has fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/7537

**Comment by phamkhactu** [comment]
@LDOUBLEV thank you
