### ISSUE TITLE
剪枝代码这里代码是不是写错了，input_shape = [1, 3, 32, 320]？

### ISSUE THREAD

**Issue by MRNEVERMISS** [PaddlePaddle/PaddleOCR#7541]
https://github.com/PaddlePaddle/PaddleOCR/blob/274c216c6771a94807a34fb94377a1d7d674a69f/deploy/slim/prune/sensitivity_anal.py#L79
识别模型的输入确定是
input_shape = [1, 3, 32, 320]？
而不是
input_shape = [1, 3, 320, 320]？

**Comment by Topdu** [comment]
识别模型的输入是文本图像，如：
![image](https://user-images.githubusercontent.com/28981817/189261143-acfa16fb-f8b6-4754-ba63-d4e46cd57b84.png)
数据大多是宽高比，比较大的图像，在PP-OCR识别模型训练的输入宽高比设置为32:320

**Comment by MRNEVERMISS** [comment]
> 识别模型的输入是文本图像，如： ![image](https://user-images.githubusercontent.com/28981817/189261143-acfa16fb-f8b6-4754-ba63-d4e46cd57b84.png) 数据大多是宽高比，比较大的图像，在PP-OCR识别模型训练的输入宽高比设置为32:320
刚刚去看训练代码了，发现了这点，谢谢哈
