### ISSUE TITLE
PaddleOCR加载自己的识别模型进行图像检测+识别与仅使用识别模型时效果不一致

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleOCR#7542]
先用PaddleOCR的图像检测功能，按照得到的识别框带文字的小图裁剪出来，标注用做训练集，对文字识别模型进行了训练，然后推理测试了一下没有问题，于是使用PaddleOCR加载新训练的文字识别模型跑检测 + 识别的整体流程，结果发现出现了识别结果不一致的情况。

- 系统环境/System Environment：CenOS7
- 版本号/Version：Paddle：2.3.1.post112  PaddleOCR：2.6 问题相关组件/Related components：PaddleOCR
- python/Version: 3.9.12
- 使用模型ppocrv3

问题图片：
![image](https://user-images.githubusercontent.com/34825635/189260271-ee896330-02ea-4290-a6da-a8b16a644be2.png)

* 单用识别模型进行推理时：（有敏感信息此处我遮挡了）
`前言－客户（“甲方”）和XXXXX（“乙方”）所签订的业务约定书（“业务约定书”）及本业务条款其同构成`
* 使用PaddleOCR时：
`（，）（7，）是时（，）－`

- 推理命令：
```
python3 tools/infer/predict_rec.py --image_dir=/home/hr/projects/ppocr/PaddleOCR/data/train_data/rec/train/XXXXX.png --rec_model_dir=/home/hr/projects/ppocr/PaddleOCR/output/inference/rec_ppocr_v3_distillation/Teacher --rec_image_shape="3, 48, 640" --rec_char_dict_path=/home/hr/projects/ppocr/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt
```
- 配置文件的参数：
```
# 对image_shape进行了更改
image_shape: [3, 48, 640]
```
- PaddleOCR的加载参数设置：
```
paddle_ocr_engine = PaddleOCR(
                        use_angle_cls=True, 
                        lang="ch", 
                        rec_model_dir="./output/inference/rec_ppocr_v3_distillation/Teacher",
                        rec_image_shape="3, 48, 640",
                        rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt") 
```

如果能够提供一些帮助或者建议，非常感谢！

**Comment by andyjpaddle** [comment]
PaddleOCR whl包目前仅支持PP系列模型，默认使用V3模型，识别shape是3,48,320，源代码是这里，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py#L479-L482 如果需要更改shape，对应这里也需要修改一下，然后重新编译即可
