### ISSUE TITLE
请问什么时间可以提供x86和x86_64 安卓cpu架构的支持？

### ISSUE THREAD

**Issue by rise-worlds** [PaddlePaddle/PaddleOCR#7543]
```gradle
ndk {
    abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
}
```
目前在安卓上只能运行arm架构的cpu上运行，请问什么时间可以提供对x86和x86_64架构的cpu支持？

- 系统环境/System Environment：安卓x86和x86_64架构
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：无
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：无x86和x86_64版本的so库

**Comment by rise-worlds** [comment]
up

**Comment by WenmuZhou** [comment]
暂无计划
