### ISSUE TITLE
为什么训练自己数据集，不会保存训练模型？

### ISSUE THREAD

**Issue by zhoumengkai010511** [PaddlePaddle/PaddleOCR#7545]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：2.6 Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer_kie_token_ser.py  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml   -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy   Global.infer_img=./train_data/XFUND/zh_val/image   Global.infer_mode=true

**Comment by andyjpaddle** [comment]
你运行指令是推理命令，不是训练指令

**Comment by zhoumengkai010511** [comment]
# GPU训练 支持单卡，多卡训练
# 训练日志会自动保存到 配置文件中"{Global.save_model_dir}" 下的train.log文件中

# SER单卡训练
python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml

# SER多卡训练，通过--gpus参数指定卡号
python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml

# RE任务单卡训练
python3 tools/train.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml

这些是训练指令吗？

**Comment by andyjpaddle** [comment]
是的

**Comment by zhoumengkai010511** [comment]
谢谢！
