### ISSUE TITLE
自己训练模型。有这样一个有趣现象。 不知道怎么解决。 转换成onnx模型，用于截屏识别 文字放大时截图的效果有时比原始图好，不知道怎样自动放大，确保识别效果最好 微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7551]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

自己训练模型。有这样一个有趣现象。
不知道怎么解决。
转换成onnx模型，用于截屏识别
文字放大时截图的效果有时比原始图好，不知道怎样自动放大，确保识别效果最好
微信nlanguage

**Comment by BeyondYourself** [comment]
分辨率不一样了

**Comment by nissansz** [comment]
怎样自动resize使结果一致？

**Comment by andyjpaddle** [comment]
> 怎样自动resize使结果一致？

目前还没有办法处理自动resize，可以保持自己训练集和测试集的图片大小尽量一致
