### ISSUE TITLE
关于文字识别模型的变长输入

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#7555]
您好，在多个issue中您提到svtr模型不支持变长输入，而ppocrv3的SVTR_LCNet是可以输入不同长度的文本图片，请问造成这个区别的原因是什么？或者说，我设计一个变长输入的网络时，应该关注哪些问题。

**Comment by Topdu** [comment]
> 在多个issue中您提到svtr模型不支持变长输入

SVTR整体结构与ViT类似，为backbone+ctchead的结构，，训练时使用了绝对位置编码。绝对位置编码是根据固定的inputsize得到一个位置编码序列，例如32*100的inputsize，对应的位置编码的个数为8*25，并且随着训练而更新位置编码的信息。如果推理时采用了和训练不一致的inputsize，训练得到的位置编码不能参与推理，会运行报错。



> ppocrv3的SVTR_LCNet是可以输入不同长度的文本图片，请问造成这个区别的原因是什么？

PP-OCRv3为backbone(lcnet)+neck(svtr)+ctchead的结构，backbone采用轻量的**全卷积网络**lcnet，没有绝对位置编码。对于48*W*3（W可变）的输入，lcnet提取得到1*W/4*D的特征F。neck采取两层svtr的global block，同样没有使用绝对位置编码，特征F经过svtr提取全局特征，最后送入ctchead解码出结果。




> 或者说，我设计一个变长输入的网络时，应该关注哪些问题。

要关注网络是否仅仅接受固定inputsize的输入，比如全卷积网络是可以处理任意大小的输入，没有绝味位置编码的ViT结构也可以。建议深入理解lcnet的代码，会帮助理解全卷积网络为什么可以处理任意大小的输入。

**Comment by xu-peng-7** [comment]
首先非常感谢您的回复，我有深入的阅读ppocr的代码。还有一些疑问如下：

1：对于纯粹的SVTR网络结构，是否删除绝对位置编码后就可以作为backbone进行特征提取，最后的网络也支持任意大小的输入。
2：我对于ppocrv3提出的各类新结构，进行排列组合后在公开的数据集中进行了测试。发现性能要明显低于resnet+crnn的组合（ppocrv2）。类似的问题在 https://github.com/PaddlePaddle/PaddleOCR/issues/7482 中也有提到。在私有数据集中也是类似的结论，性能最好依然的是resnet+crnn。我想了解下是我哪里没有考虑到吗？

![微信图片_20220913145120](https://user-images.githubusercontent.com/49851465/189830780-f555df66-deba-40dc-a0b0-09c98aa290a3.jpg)

**Comment by Topdu** [comment]
> 1：对于纯粹的SVTR网络结构，是否删除绝对位置编码后就可以作为backbone进行特征提取，最后的网络也支持任意大小的输入。

理论上来说，删除绝对位置编码即可以支持任意大小的输入，但是类ViT的结构缺乏平移不变性的特性，即使理论上支持，实际上结果可能不符合预期。卷积网络能很好的处理任意大小的输入，正是因为卷积操作平移不变性的特性。





> 2：我对于ppocrv3提出的各类新结构，进行排列组合后在公开的数据集中进行了测试。发现性能要明显低于resnet+crnn的组合（ppocrv2）。类似的问题在 #7482 中也有提到。在私有数据集中也是类似的结论，性能最好依然的是resnet+crnn。我想了解下是我哪里没有考虑到吗？

请问这些实验有更详细的配置吗？比如数据集的宽高比统计、样本字符数统计、neck的dim、以及参数量的对比表，这些数据分析可以帮助我们更好的分析实验结果。
从这个表中可以看到，增加neck似乎对精度提升不大（不到1%），按经验来说，不管是svtrneck还是rnnneck，都会对结果有明显的提升（+3-5%）。目前分析，resent+rnn的参数量是要比其他实验大很多，带来了高精度。
建议尝试更多PP-OCRv3的训练策略，例如预训练，蒸馏。

**Comment by xu-peng-7** [comment]
部分实验结果可以在：https://aistudio.baidu.com/aistudio/projectdetail/4436515 查看。

我也是做了很多的尝试，包括在自己的数据集上和开源的数据集中，都很难超过resnet+crnn的组合。您提到参数量的问题，您可以注意到，默认ppocrv3的scale是0.5，我将其增加到2，其模型的大小已经超过了resent，但是性能依然达不到。包括增加neck部分的参数量。

还有一个细节希望您可以考虑下，在resnet中宽度是变为原来的**四分之一**，但是在ppocrv3中，由于最后一个卷积核的步长为（1，2）其实这里的宽度是变为原来的**八分之一** 。但是我测试了四分之一和八分之一的区别，最终的差别并不明显。

> 按经验来说，不管是svtrneck还是rnnneck，都会对结果有明显的提升（+3-5%）
请问您这个结论是在哪个数据集中得到，考虑到数据集的差异，我可以自己再进行一些实验。

**Comment by xu-peng-7** [comment]
简单来说，我希望在v3的新结构中找到一种结构可以比resnet+crnn的组合性能更好，但是没有成功。
如果您有实验结论，可以给我一些结构和数据集的建议。我可以在您建议的数据集中，使用您推荐的结构在文字识别任务中精度超过resnet+crnn。
非常感谢

**Comment by Topdu** [comment]
PP-OCRv3优化策略针对轻量的模型，在大模型上有可能不适应。比如ppocrv2的server的服务端模型直接采用了resnet，并不是将lcnet放大到2.0倍，这也是因为lcnet在轻量结构上具有优势，resnet在大模型上具有优势。

如果不考虑参数量和速度，可以尝试将resnet的最后两个阶段修改为svtr_global_block，可以参考PP-OCRv3消融实验：
![image](https://user-images.githubusercontent.com/28981817/189849790-8dbe8910-ee05-4923-a208-8cc97b9c3a65.png)，根据经验设置dim和层数。

neck部分可以尝试svtr，head使用ctchead，可以先不使用multi_head结构，注意修改use_guide为false，并且修改svtr neck的dim，和resnet的输出dim同步缩放，不能使用原始dim。

例如：
```
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 128
    depth: 2
    hidden_dims: 256
    use_guide: Fasle
  Head:
    name: CTCHead
```
这些参数可以自己根据经验设置，原则就是根据backbone同步缩放就行，

**Comment by xu-peng-7** [comment]
非常感谢您，我将详细的实验您的建议后给您反馈。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月13日(星期二) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于文字识别模型的变长输入 (Issue #7555)





 
PP-OCRv3优化策略针对轻量的模型，在大模型上有可能不适应。比如ppocrv2的server的服务端模型直接采用了resnet，并不是将lcnet放大到2.0倍，这也是因为lcnet在轻量结构上具有优势，resnet在大模型上具有优势。
 
如果不考虑参数量和速度，可以尝试将resnet的最后两个阶段修改为svtr_global_block，可以参考PP-OCRv3消融实验：
 ，根据经验设置dim和层数。
 
neck部分可以尝试svtr，head使用ctchead，可以先不使用multi_head结构，注意修改use_guide为false，并且修改svtr neck的dim，和resnet的输出dim同步缩放，不能使用原始dim。
 
例如：
   Neck:     name: SequenceEncoder     encoder_type: svtr     dims: 128     depth: 2     hidden_dims: 256     use_guide: Fasle   Head:     name: CTCHead  
这些参数可以自己根据经验设置，原则就是根据backbone同步缩放就行，

**Comment by xu-peng-7** [comment]
> PP-OCRv3优化策略针对轻量的模型，在大模型上有可能不适应。比如ppocrv2的server的服务端模型直接采用了resnet，并不是将lcnet放大到2.0倍，这也是因为lcnet在轻量结构上具有优势，resnet在大模型上具有优势。
> 
> 如果不考虑参数量和速度，可以尝试将resnet的最后两个阶段修改为svtr_global_block，可以参考PP-OCRv3消融实验： ![image](https://user-images.githubusercontent.com/28981817/189849790-8dbe8910-ee05-4923-a208-8cc97b9c3a65.png)，根据经验设置dim和层数。
> 
> neck部分可以尝试svtr，head使用ctchead，可以先不使用multi_head结构，注意修改use_guide为false，并且修改svtr neck的dim，和resnet的输出dim同步缩放，不能使用原始dim。
> 
> 例如：
> 
> ```
>   Neck:
>     name: SequenceEncoder
>     encoder_type: svtr
>     dims: 128
>     depth: 2
>     hidden_dims: 256
>     use_guide: False
>   Head:
>     name: CTCHead
> ```
> 
> 这些参数可以自己根据经验设置，原则就是根据backbone同步缩放就行，

您好 我进行了测试，按照您的指点添加SVTR作为Neck的性能均不如使用Reshape。希望能和您再沟通下。

**Comment by Topdu** [comment]
等比例缩放
