### ISSUE TITLE
TensorRT prediction at inference time has no caching 

### ISSUE THREAD

**Issue by alawliat** [PaddlePaddle/PaddleOCR#7556]
`
ocr = PaddleOCR(use_gpu = True, use_tensorrt = True, lang='en')
`

At inference time, I convert my paddleocr model to trt format, but the issue here is that it takes 20 minutes to do this conversion, is there an option to cache this result somewhere instead of having to do this every single time? 

- 系统环境/System Environment：Python 3.8 - Windows 10 / Ubuntu 20.04
- 版本号/Version：Paddle：2.2  PaddleOCR： 2.5

**Comment by LDOUBLEV** [comment]
It is not necessary to convert paddleocr model to trt format.
Just set use_tensorrt as True.
