### ISSUE TITLE
StarNet_MobileNetV3 文字识别复现精度与官网给的不一致

### ISSUE THREAD

**Issue by max-niu** [PaddlePaddle/PaddleOCR#7558]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 PaddleOCR/tools/eval.py -c PaddleOCR/configs/rec/rec_mv3_tps_bilstm_ctc.yml  -o Global.checkpoints="./checkpoint/rec_mv3_tps_bilstm_ctc_v2.0_train/best_accuracy"

- 完整报错/Complete Error Message：

python3 PaddleOCR/tools/eval.py -c PaddleOCR/configs/rec/rec_mv3_tps_bilstm_ctc.yml  -o Global.checkpoints="./checkpoint/rec_mv3_tps_bilstm_ctc_v2.0_train/best_accuracy"

![image](https://user-images.githubusercontent.com/57517234/189514101-c80582cb-b4b3-43a4-9ff8-4e2279db027d.png)

![image](https://user-images.githubusercontent.com/57517234/189514137-c38b2a46-7e85-4d03-a24c-0abf261d7679.png)

**Comment by tink2123** [comment]
文档里提供的指标对齐论文说明合并了重复字符，后续更新代码修改了acc计算方式，指标略有下降。权重一致，只是acc计算方式不同。
