### ISSUE TITLE
en_PP-OCRv3_det使用cpu测试doc/imgs_en/中的图片报段错误`Segmentation fault`

### ISSUE THREAD

**Issue by max-niu** [PaddlePaddle/PaddleOCR#7561]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu1802
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.5.0.3 问题相关组件/Related components：
- 运行指令/Command Code：
python3 PaddleOCR/tools/infer_det.py -c PaddleOCR/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.infer_img="./PaddleOCR/doc/imgs_en/" Global.pretrained_model="./checkpoint/en_PP-OCRv3_det_distill_train/best_accuracy"

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/57517234/189518001-d6ae2b70-13a3-400e-b7e7-37d684d233a5.png)

**Comment by LDOUBLEV** [comment]
问题是稳定复现的吗，单独预测这张图试试：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/imgs_en/img_195.jpg

我这边没能复现
