### ISSUE TITLE
jetson nano安装paddleOCR报错：FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'

### ISSUE THREAD

**Issue by tcexeexe** [PaddlePaddle/PaddleOCR#7562]
- 系统环境/System Environment：
- cuda10.2 cudnn8.2 jetpack 4.6.2 tensorrt 8.2.1.8-1
我在jetson nano上通过
`pip3 install paddlepaddle_gpu-2.3.2-cp36-cp36m-linux_aarch64.whl`安装 paddle inference 库，提示安装成功；
然后，通过 `pip3 install "paddleocr>=2.0.1"` 尝试安装paddleocr，但是遇到报错：FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'
<img width="426" alt="f9166a35815727ff6f4d726f4cad8dc" src="https://user-images.githubusercontent.com/28287196/189534327-1d2e82b9-864c-4c18-bdb8-3a1b92b35c6f.png">

我曾经尝试通过 pip3 install cython来解决这个问题，但是并没有奏效。不知上述这种安装方式是否合适？同时是否有办法解决这个问题

**Comment by LDOUBLEV** [comment]
安装paddleocr 2.5以上的版本吧

**Comment by tcexeexe** [comment]
> paddleocr 2.5以上的版本吧

你好，我用pip3 install "paddleocr>=2.5"尝试安装，还是有cython的报错，和原先一样
