### ISSUE TITLE
通过LABEL工具 点击表格识别报错，闪退

### ISSUE THREAD

**Issue by wyf00747** [PaddlePaddle/PaddleOCR#7563]
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2294, in TableRecognition
    res = self.table_ocr(img, return_ocr_result_in_table=True)
  File "C:\Users\wyf00747\anaconda3\envs\py38\lib\site-packages\paddleocr\paddleocr.py", line 602, in __call__
    res, _ = super().__call__(
  File "i:\GITHUB\PaddleOCR\PPOCRLabel\..\ppstructure\predict_system.py", line 107, in __call__
    ori_im = img.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
报了这个错误

**Comment by furoce** [comment]
我也报这个错，PPOCRLabel 2.1.2版本，win10

**Comment by Mrfuhang** [comment]
你们解决了嘛

**Comment by Mrfuhang** [comment]
> Traceback (most recent call last): File "PPOCRLabel.py", line 2294, in TableRecognition res = self.table_ocr(img, return_ocr_result_in_table=True) File "C:\Users\wyf00747\anaconda3\envs\py38\lib\site-packages\paddleocr\paddleocr.py", line 602, in **call** res, _ = super().**call**( File "i:\GITHUB\PaddleOCR\PPOCRLabel..\ppstructure\predict_system.py", line 107, in **call** ori_im = img.copy() AttributeError: 'NoneType' object has no attribute 'copy' 报了这个错误

需要检查你们存放图片的路径，必须是英文路径。
