### ISSUE TITLE
sorted_boxes(dt_boxes) for ocr results?

### ISSUE THREAD

**Issue by Johndirr** [PaddlePaddle/PaddleOCR#7564]
系统环境/System Environment：Windows10
版本号/Version：Paddle： PaddleOCR： 2.5
运行指令/Command Code：[sorted_boxes(dt_boxes)](https://github.com/PaddlePaddle/PaddleOCR/blob/c1eaa17a95d4b1faf1806dc4328e580de29ca49e/tools/infer/predict_system.py#L104)

I would like to use the function "sorted_boxes" to sort the results from e.g. ocr.ocr(image, cls=True) but the function awaits an array (detected text boxes with shape [4, 2]).
The results from ocr are looking like this (list of lists with coordinates and tuples):
```
[
[[[150.0, 162.0], [208.0, 164.0], [208.0, 178.0], [150.0, 176.0]], ('SPRING', 0.9889079928398132)], 
[[[99.0, 193.0], [258.0, 193.0], [258.0, 222.0], [99.0, 222.0]], ('1994', 0.9938473701477051)], 
[[[273.0, 194.0], [311.0, 192.0], [312.0, 206.0], [274.0, 208.0]], ('KA', 0.5617326498031616)]
]
```
I could convert to a numpy array but the shape would still be wrong.

Do you have any idea on how to change the sorted_boxes function to work with ocr results?

**Comment by LDOUBLEV** [comment]
You should get the boxes from the results.

```

import paddleocr

from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang="ch")
img_path = 'OCR/PR/PaddleOCR/doc/imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
print(result)

# get box from results
boxes = [line[0] for line in result]
# and then you can sort boxes.
```

**Comment by Johndirr** [comment]
Thank you. Somehow I was not able to wrap my head around this.
I used this to sort bound boxes and sorted the results (containing the text) according to this order.
