### ISSUE TITLE
基于serving部署的检测串联识别模型在识别截取的小图的时候检测的效果很差。

### ISSUE THREAD

**Issue by jiangqianxin111** [PaddlePaddle/PaddleOCR#7565]
![11](https://user-images.githubusercontent.com/111032962/189791232-2276c9e4-7b09-442d-b485-f6db5a84a83c.png)

**Comment by MissPenguin** [comment]
直接python推理效果如何呢

**Comment by jiangqianxin111** [comment]
> 直接python推理效果如何呢

直接推理的结果还可以欸

**Comment by tink2123** [comment]
单行文本建议直接使用识别模型，不需要过检测模型。

**Comment by jiangqianxin111** [comment]
> 单行文本建议直接使用识别模型，不需要过检测模型。

可是会有多行文本的应用场景诶

**Comment by tink2123** [comment]
多行文本需要使用检测+识别串联， 请问serving使用哪个版本的模型呢？方便的话发一下serving和python推理的效果图对比吧

**Comment by jiangqianxin111** [comment]
> 多行文本需要使用检测+识别串联， 请问serving使用哪个版本的模型呢？方便的话发一下serving和python推理的效果图对比吧

https://github.com/PaddlePaddle/PaddleOCR/issues/7565#issuecomment-1245070424
![微信图片_20220913140403](https://user-images.githubusercontent.com/111032962/190030718-d8805507-30df-4a46-aca6-f16de80daabe.jpg)

以这个为例，python能够完整推理，serving则一个检测框都没有，这使用的serving版本是0.7版本哦

**Comment by jiangqianxin111** [comment]
> 多行文本需要使用检测+识别串联， 请问serving使用哪个版本的模型呢？方便的话发一下serving和python推理的效果图对比吧

![image](https://user-images.githubusercontent.com/111032962/190073672-c219534c-c617-40fb-b0d3-7b5948d76723.png)
![det_res_11](https://user-images.githubusercontent.com/111032962/190073797-f23a11ab-57ce-4112-88a2-81da42cb97b4.png)

上面是serving，下面是python推理

**Comment by tink2123** [comment]
参考这篇文档更新serving版本和ocr模型再尝试下效果呢， 这边自测serving结果，可以准确识别框和文本内容：


<img width="688" alt="image" src="https://user-images.githubusercontent.com/31891223/192935917-59286ca2-62e3-4d0e-8fdf-212b75617271.png">
