### ISSUE TITLE
bug in predict_system.py when angle=0

### ISSUE THREAD

**Issue by asfoorial** [PaddlePaddle/PaddleOCR#7572]
Hi all,

I noticed a bug at line 103 of preditc_system.py (paddleocr versoin 2.6) when angle=0 in the below lines:

cv_rotate_code = {
                '90': cv2.ROTATE_90_COUNTERCLOCKWISE,
                '180': cv2.ROTATE_180,
                '270': cv2.ROTATE_90_CLOCKWISE
            }
img = cv2.rotate(img, cv_rotate_code[angle])

Suggested solution:
cv_rotate_code = {
                '90': cv2.ROTATE_90_COUNTERCLOCKWISE,
                '180': cv2.ROTATE_180,
                '270': cv2.ROTATE_90_CLOCKWISE
            }
if angle in cv_rotate_code:
         img = cv2.rotate(img, cv_rotate_code[angle])

**Comment by WenmuZhou** [comment]
I can not find such code at line 103 of preditc_system.py

**Comment by asfoorial** [comment]
It is in this file https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/predict_system.py

![IMG_20220913_184539](https://user-images.githubusercontent.com/5801922/189946987-051d47f3-2f98-40c5-b175-37097d0b4e68.jpg)

**Comment by adakaho** [comment]
对的 运行2.6版本的 2.2.1 图像方向分类+版面分析+表格识别 代码 会报错。

Traceback (most recent call last):
  File "D:/download/PaddleOCR-release-2.6/table_demo.py", line 155, in <module>
    result = table_engine(img)
  File "D:\download\PaddleOCR-release-2.6\paddleocr.py", line 602, in __call__
    res, _ = super().__call__(
  File "D:\download\PaddleOCR-release-2.6\ppstructure\predict_system.py", line 103, in __call__
    img = cv2.rotate(img, cv_rotate_code[angle])
KeyError: '0'

**Comment by asfoorial** [comment]
As I mentioned before, you just need the following if statement before the rotate call.

if angle in cv_rotate_code:
img = cv2.rotate(img, cv_rotate_code[angle])

**Comment by WenmuZhou** [comment]
can you make a pr,tks

**Comment by WenmuZhou** [comment]
we have fixed it
