### ISSUE TITLE
Could NOT find Git

### ISSUE THREAD

**Issue by SeventhBlue** [PaddlePaddle/PaddleOCR#7573]
![图片](https://user-images.githubusercontent.com/24708312/189832268-781ae295-6fdd-4362-9176-9eb3fd3ef371.png)
编译paddleOCR2.5和2.6都出错（paddleX编译通过），能告知解决问题的方向吗？
（ 将 deploy/cpp_infer/external-cmake/auto-log.cmake 中的github地址改为 https://gitee.com/Double_V/AutoLog 试过，没有效果）

**Comment by WenmuZhou** [comment]
安装git了吗

**Comment by SeventhBlue** [comment]
> 
这个肯定安装了的

**Comment by SeventhBlue** [comment]
已经解决了，原来是没有把git安装目录添加到系统变量中
