### ISSUE TITLE
表格识别中 获取的html还原效果还有待提升

### ISSUE THREAD

**Issue by sticktoFE** [PaddlePaddle/PaddleOCR#7574]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![WPS图片编辑](https://user-images.githubusercontent.com/2472797/189835857-f15e3730-1080-4df7-98df-46d8485d3acc.png)
解析这个图片后html，行列不对

![1663053553911](https://user-images.githubusercontent.com/2472797/189836161-9b34343d-e07b-4af0-b0a3-0f9c66e953a5.png)

**Comment by WenmuZhou** [comment]
好的，收到
