### ISSUE TITLE
使用ppstructurev2 转成onnx模型后，无法对onnx模型进行输出

### ISSUE THREAD

**Issue by NBd-hub** [PaddlePaddle/PaddleOCR#7576]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle2.3.2
- 运行指令/Command Code：!python3.7 tools/infer/predict_system.py  --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/model.onnx --image_dir=/home/aistudio/work/PaddleOCR/ppstructure/docs/table/1.png
- 完整报错/Complete Error Message：/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[2022/09/13 16:27:49] ppocr INFO: not find rec model file path None

**Comment by MissPenguin** [comment]
> 仅仅是版面分析的检测模型应该不需要rec model吧

对，只做检测的话，不需要rec model，你用的推理脚本不对，单独使用版面检测模型可参考这个教程：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md
