### ISSUE TITLE
Paddle OCR kills the kernel

### ISSUE THREAD

**Issue by ewankim1023** [PaddlePaddle/PaddleOCR#7581]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：AWS SageMaker (CPU/GPU both) 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：Nothing

![paddleocr_kills_kernel](https://user-images.githubusercontent.com/44500101/189878569-d1b38b90-c2ec-4479-bc12-8624f740ac69.JPG)

PaddleOCR runs well at AWS studio lab (nothing special, just a jupyter notebook instance)
but it stops and kills the kernel when I run from AWS Sagemaker.

**Comment by an1018** [comment]
参考的哪个文档呢
