### ISSUE TITLE
how to training SVTR for sequence input

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#7582]
I had trained model SVTR to recognize text from image, but when I have image like sequence text, model doesn't  work well, but when training val acc very high 0.9235365
![image](https://user-images.githubusercontent.com/42369268/189881861-01f6da7a-88a6-42a8-bc0b-52138ade3b76.png)
My result is: 
```
result: Wth thi risi   0.3239577054977417
```
I don't know why? I have my question that: "How to config model to recognize sequence" like that

 
Many thanks.

**Comment by an1018** [comment]
SVTR uses absolute encoding, and so it doesn't support variable lengths. It can only recognize text up to 25 characters . If the number of characters is not certain, but some images have more than 25 characters, [PP-OCRv3](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/ppocr_introduction.md#52) modified according to SVTR is recommended.

**Comment by phamkhactu** [comment]
@an1018 thank you. If I want to change backbone to resnet34, how to config it? 
```
 Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
```
Maybe only change name to ``` Res34```

**Comment by an1018** [comment]
- [Training with new Backbone](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/recognition_en.md#23-training-with-new-backbone)

- [ResNet code](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppocr/modeling/backbones/rec_resnet_vd.py)

config:
```
  Backbone:
    name: ResNet
    layers: 34
```

**Comment by phamkhactu** [comment]
Thanks you

**Comment by phamkhactu** [comment]
@an1018  I have error when loading data
my error:
```
line 121, in fetch\n    data.append(self.dataset[idx])\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/lmdb_dataset.py", line 115, in __getitem__\n    outs = transform(data, self.ops)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform\n    data = op(data)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/rec_img_aug.py", line 159, in __call__\n    for idx, ext_data in enumerate(data["ext_data"]):\nKeyError: \'ext_data\'\n'
```
It comes from rec_img_aug.py
```
def __call__(self, data):
        rnd_num = random.random()
        if rnd_num > self.prob:
            return data
        for idx, ext_data in enumerate(data["ext_data"]):
            if len(data["label"]) + len(ext_data[
                    "label"]) > self.max_text_length:
                break
            concat_ratio = data['image'].shape[1] / data['image'].shape[
                0] + ext_data['image'].shape[1] / ext_data['image'].shape[0]
            if concat_ratio > self.max_wh_ratio:
                break
            data = self.merge_ext_data(data, ext_data)
        data.pop("ext_data")
        return data
```
