### ISSUE TITLE
KIE transform cause segmentfault 

### ISSUE THREAD

**Issue by lynquantumman** [PaddlePaddle/PaddleOCR#7583]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- 版本号/Version：Paddle：paddle-bfloat         0.1.7
paddle2onnx           1.0.0
paddlefsl             1.1.0
paddlenlp             2.3.0.dev0
paddleocr             2.6.0.1
paddlepaddle-gpu      2.3.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/infer_kie_token_ser.py \
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_0.jpg
- 完整报错/Complete Error Message：segment fault

**Comment by lynquantumman** [comment]
<ppocr.data.imaug.label_ops.VQATokenLabelEncode object at 0x7fe70c0e4fd0>  cause this segmentfault

**Comment by lynquantumman** [comment]
PaddleOCR/tools/infer/predict_det.py  self.predictor got wrong

**Comment by an1018** [comment]
是执行tools/infer_kie_token_ser.py 还是tools/infer/predict_det.py命令呢，贴一下详细的报错命令吧

**Comment by lynquantumman** [comment]
运行指令/Command Code：python3 tools/infer_kie_token_ser.py
-c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
-o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
Global.infer_img=./ppstructure/docs/kie/input/zh_val_0.jpg

**Comment by lynquantumman** [comment]
上面有, 同时, 执行paddle-ocr 的时候也报这个段错误

**Comment by lynquantumman** [comment]
> PaddleOCR/tools/infer/predict_det.py self.predictor got wrong
这里指的是这一行会 报错, 应该是GPU 哪里不兼容

**Comment by yue0729** [comment]
请问解决了吗? 如何解决这个问题呢
