### ISSUE TITLE
推理模型预测时结果为空

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#7584]
使用abinet模型，在aistudio上运行，paddlepaddle版本为2.3.2
训练模型预测全部正确，指令如下：
python3 tools/infer_rec.py -c output/abi_rec_gator/config.yml -o Global.pretrained_model=output/abi_rec_gator/best_accuracy Global.infer_img=../temp/rec_img/
结果：
ppocr INFO: infer_img: ../temp/rec_img/26839_000.jpg
ppocr INFO: 	 result: 9	0.9999912977218628
ppocr INFO: infer_img: ../temp/rec_img/26839_001.jpg
ppocr INFO: 	 result: 291592	0.9999998211860657
ppocr INFO: infer_img: ../temp/rec_img/26839_002.jpg
ppocr INFO: 	 result: bmou	0.9999996423721313
ppocr INFO: infer_img: ../temp/rec_img/26839_003.jpg
ppocr INFO: 	 result: 22g1	0.9999728202819824

推理模型预测全部为空，指令如下：
python3 tools/infer/predict_rec.py \
    --image_dir="../temp/rec_img/" \
    --rec_model_dir="inference/abinet_gator/" \
    --rec_image_shape="3, 32, 128" \
    --rec_algorithm="ABINet" \
    --rec_char_dict_path=ppocr/utils/ic15_dict.txt \
    --use_space_char=False \
    --rec_batch_num=8
结果如下：
ppocr INFO: Predicts of ../temp/rec_img/26839_000.jpg:('', nan)
ppocr INFO: Predicts of ../temp/rec_img/26839_001.jpg:('', nan)
ppocr INFO: Predicts of ../temp/rec_img/26839_002.jpg:('', nan)
ppocr INFO: Predicts of ../temp/rec_img/26839_003.jpg:('', nan)

检查过训练模型和推理模型图片预处理的操作并没有什么差别，请问预测结果不一样怎么解决呢？

**Comment by lihuikenny** [comment]
我也是这样，请问您解决了么？
