### ISSUE TITLE
SRN文本识别网络损失计算中，使用交叉熵损失计算后为什么还要有sum操作

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#7590]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：Paddle：2.6   PaddleOCR： 问题相关组件/Related components：SRN文本识别网络
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 文本识别SRN网络中用的SRNLoss计算方法，在最后发现要用paddle.sum(cost_word)，不明白为什么使用交叉熵损失后返回的结果还要sum操作，这会导致训练过程中损失较大。
- 

![image](https://user-images.githubusercontent.com/49891512/190086813-ac85ee44-618e-4c4d-bb91-a460f00f00f9.png)

**Comment by InferMaster** [comment]
不知道这里在得到交叉熵损失后，又采用sum操作是不是有什么含义呢

**Comment by tink2123** [comment]
这一步不是必须的，为了适配早期PaddleOCR模型的风格，统一计算batch内的loss之和，对最终模型精度影响不大，可以按个人习惯去除。

**Comment by InferMaster** [comment]
> 这一步不是必须的，为了适配早期PaddleOCR模型的风格，统一计算batch内的loss之和，对最终模型精度影响不大，可以按个人习惯去除。

收到，我测试了也是对结果没影响
