### ISSUE TITLE
is the DB model has the best result?

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleOCR#7593]
Det 和 Rec 模型效果最好的是哪一个？

**Comment by an1018** [comment]
可以尝试使用[PP-OCRv3](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/ppocr_introduction.md#pp-ocrv3)，也可以使用PP-OCRv3在自己数据集上finetune训练达到更好的效果

**Comment by mrljwlm** [comment]
> 可以尝试使用[PP-OCRv3](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/ppocr_introduction.md#pp-ocrv3)，也可以使用PP-OCRv3在自己数据集上finetune训练达到更好的效果

PP-OCRv3 det 英文模型的config文件是哪一个？只找到了ch_PP-OCRv3_det.yml 没有找到哪里有en_PP-OCRv3_det.yml

**Comment by an1018** [comment]
使用相同的配置修改参数即可
