### ISSUE TITLE
英文识别模型报错

### ISSUE THREAD

**Issue by nvliajia** [PaddlePaddle/PaddleOCR#7595]
运行2.2 英文识别模型推理中报错，
![1663139756281](https://user-images.githubusercontent.com/59531363/190094566-b256f1a2-876a-4b91-a472-5fe6d3397999.png)

paddleocr是最新版本的，liunx环境

![1663139828307](https://user-images.githubusercontent.com/59531363/190094823-5d514396-c2fe-4086-80da-be2780d92f5f.png)

**Comment by an1018** [comment]
文档错误，这里应该是wget https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar，rec_model_dir改为对应模型路径再试试~

**Comment by an1018** [comment]
1200*1200识别尺寸太多，导致缩放后图片太模糊；如果检测图片尺寸1200*1200可以修改`det_limit_type=max`和`det_limit_side_len`参数

**Comment by nvliajia** [comment]
好的，如果我想对图片的某一区域检测识别，可以直接通过修改参数实现吗

**Comment by an1018** [comment]
可以通过在[predict_sysytem](https://github.com/PaddlePaddle/PaddleOCR/blob/0bc20a5abd4a4b4cdc247c266d12011ef83f3c65/tools/infer/predict_system.py#L162)获取img之后添加一行代码获取图片局部区域，再检测识别

**Comment by nvliajia** [comment]
如果一张图片里有两种语言，比如印度语和英语，我看模型会把印度语识别成英语，我能有办法让模型对印度语不去识别吗

**Comment by an1018** [comment]
可以看一下印度语的检测框的置信度，通过阈值过滤下，如果置信度比较高，也可以考虑使用自己的数据finetune
