### ISSUE TITLE
paddleocr v3 训练自己的数据表现的结果是头尾容易丢失文字

### ISSUE THREAD

**Issue by double-vane** [PaddlePaddle/PaddleOCR#7596]
![0018031_1_4_0](https://user-images.githubusercontent.com/20334378/190096349-0dec50eb-30ad-4719-98ba-23330a203f63.jpg)
识别结果就是
![1663142462778](https://user-images.githubusercontent.com/20334378/190096518-5da54dfc-ac17-4999-845d-81bf5709007f.png)
请问这样的结果应该从哪里去下手分析

**Comment by an1018** [comment]
这样的训练数据有多少呢，如果数据量比较少，可以添加数据后再进行finetune训练

**Comment by MarginGitHub** [comment]
告诉你一个简单方法，就是在送去文本识别之前在图像宽度方向前后padding一些空白区域，这个padding宽度大小基本上按照骨干网对图像在宽度方向的下采样倍率来取就可以了
