### ISSUE TITLE
更换backBone

### ISSUE THREAD

**Issue by xiong-yuxian** [PaddlePaddle/PaddleOCR#7597]
将CRNN的backbone更换为了VGG，跑通后训练了很久acc一直很低，loss也不怎么下降，这种情况下一步应该考虑是什么问题？主干网络在宽高上是否有其他的限制呢？
![image](https://user-images.githubusercontent.com/58280508/190101066-09536912-2cde-4609-8bb3-f0cb01110e35.png)
![image](https://user-images.githubusercontent.com/58280508/190101248-0e9a06d9-dc06-416a-b9b6-76099dc1e9de.png)

**Comment by an1018** [comment]
换backbone之前有在CRNN训练吗，确保数据和标注文件没有问题

**Comment by xiong-yuxian** [comment]
在crnn训练过，数据和标注文件正常

**Comment by MarginGitHub** [comment]
我最近也试过RepVGG骨干网，效果连MobileNetV3还不如，基本上百度提供的这些骨干网实现应该是目前最优的了，与其替换现有的骨干网还不如思考怎样进一步优化当前骨干网更有用，同时我觉得RNN模块这部分还是有优化空间
