### ISSUE TITLE
rec_r34_vd_tps_bilstm_attn模型转inference模型失败，请问是什么问题？

### ISSUE THREAD

**Issue by vinceyzw** [PaddlePaddle/PaddleOCR#76]
运行命令：
python3 tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml -o Global.checkpoints=./ch_lite/rec_r34_vd_tps_bilstm_attn/best_accuracy Global.save_inference_dir=./inference_model/rec_r34/

出现报错：
Traceback (most recent call last):
  File "tools/export_model.py", line 93, in <module>
    main()
  File "tools/export_model.py", line 67, in main
    config, eval_program, startup_prog)
  File "/root/PaddleOCR-develop/tools/program.py", line 193, in build_export
    image, outputs = model(mode='export')
  File "/root/PaddleOCR-develop/ppocr/modeling/architectures/rec_model.py", line 112, in __call__
    predict = predicts['predict']
KeyError: 'predict'

**Comment by dyning** [comment]
由于基于Attention损失的识别模型和基于CTC的识别模型推理差别很大，目前还在调试中。对于中文文本识别，建议优先选择基于CTC损失的识别模型，实践中也发现基于Attention损失的效果不如基于CTC损失的识别模型。

**Comment by LDOUBLEV** [comment]
已解决attention模型转inference model的问题

**Comment by chenxuezhao** [comment]
@LDOUBLEV 你好，请问您是怎么解决的？我用export_model.py 转换attention模型为inference model的时候会报

> ValueError: All elements in ``shape`` must be positive when it's a list or tuple
的错误。

**Comment by nissansz** [comment]
crnn配置中的attention 和ctc loss哪个准确率高？rec_r34_vd_none_bilstm_ctc.yml rec_r34_vd_none_none_ctc.yml rec_r34_vd_tps_bilstm_att.yml rec_r34_vd_tps_bilstm_ctc.yml
