### ISSUE TITLE
大佬们，怎么可视化验证集的文本识别结果

### ISSUE THREAD

**Issue by xiong-yuxian** [PaddlePaddle/PaddleOCR#7608]
想请问一下该怎么可视化训练中验证集的文本识别结果，和训练结束后的测试集文本识别结果，，或者说怎么找badcase

**Comment by yulm-1** [comment]
请问您解决这个问题了吗？

**Comment by xiong-yuxian** [comment]
没有解决，您有好的方法推荐吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 大佬们，怎么可视化验证集的文本识别结果 (Issue #7608)





 
请问您解决这个问题了吗？

**Comment by thsno02** [comment]
I use [`difflib.htmldiff`](https://docs.python.org/3/library/difflib.html) to visualize the text difference, u can check the official document as u need.

**Comment by yulm-1** [comment]
> 没有解决，您有好的方法推荐吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleOCR" ***@***.***&gt;; 发送时间:&nbsp;2022年9月26日(星期一) 下午5:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 大佬们，怎么可视化验证集的文本识别结果 (Issue #7608) 请问您解决这个问题了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您的验证集是什么格式的呢？如果是jpg或者png的话可以直接用他的可视化的命令直接可视化
![image](https://user-images.githubusercontent.com/113872348/192914798-523c07a5-ad1c-4661-861f-d65bbed2be72.png)
中文的也是一样的
如果是lmdb格式的话，我选择的是将数据集转化为jpg然后可视化
