### ISSUE TITLE
训练繁体字+英文的证件的识别模型出现报错

### ISSUE THREAD

**Issue by zuochong994** [PaddlePaddle/PaddleOCR#7609]
训练繁体字+英文的证件的识别模型出现报错
Message: 'When parsing line crop_img/360683_id_card_img_crop_5.jpg\t\u7537 M\n, error happened with msg: Traceback (most recent call last):\n  File "ppocr/data/simple_dataset.py", line 147, in __getitem__\n    data[\'ext_data\'] = self.get_ext_data()\n  File "ppocr/data/simple_dataset.py", line 103, in get_ext_data\n    label = substr[1]\nIndexError: list index out of range\n'
Arguments: ()

**Comment by zuochong994** [comment]
以下是部分数据的示例：


crop_img/205379_id_card_img_crop_1.jpg	出生日期 Date of Birth
crop_img/205379_id_card_img_crop_2.jpg	15-10-1998
crop_img/205379_id_card_img_crop_3.jpg	男M
crop_img/205379_id_card_img_crop_4.jpg	AZ
crop_img/205379_id_card_img_crop_5.jpg	簽發日期 Date of Issue
crop_img/205379_id_card_img_crop_6.jpg	(03-10)
crop_img/205377_driver_license_img_crop_2.jpg	有效期至Valid to
crop_img/205377_driver_license_img_crop_5.jpg	DRIVING LICENCE
crop_img/205377_driver_license_img_crop_6.jpg	Learner's Classes
crop_img/205377_driver_license_img_crop_7.jpg	Probationary Classes
crop_img/205377_driver_license_img_crop_8.jpg	限制事項代號
crop_img/205377_driver_license_img_crop_9.jpg	學習執照

**Comment by zuochong994** [comment]
图片路径和内容间是用’\t‘分割的 我debug了一下，好像是编码的问题
UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-63: ordinal not in range(128)
有没有大佬帮忙解答一下

**Comment by liuchong540** [comment]
> 图片路径和内容间是用’\t‘分割的 我debug了一下，好像是编码的问题 UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-63: ordinal not in range(128) 有没有大佬帮忙解答一下

请问这个问题您解决了吗？我也遇到了，如果已经解决了，方便告诉一下吗？谢谢您了
