### ISSUE TITLE
访问ocr_system本地部署服务报错

### ISSUE THREAD

**Issue by bank010** [PaddlePaddle/PaddleOCR#7610]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
- 完整报错/Complete Error Message：
[2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
Traceback (most recent call last):
  File "tools/test_hubserving.py", line 157, in <module>
    main(args)
  File "tools/test_hubserving.py", line 119, in main
    res = r.json()["results"][0]
IndexError: string index out of range

**Comment by bldu** [comment]
请问这个问题解决了吗，我也遇到同样的问题

**Comment by Han-Y-F** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：Linux
> * 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
> * 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
> * 完整报错/Complete Error Message：
>   [2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
>   Traceback (most recent call last):
>   File "tools/test_hubserving.py", line 157, in 
>   main(args)
>   File "tools/test_hubserving.py", line 119, in main
>   res = r.json()["results"][0]
>   IndexError: string index out of range

请问解决了嘛

**Comment by Bai-shen** [comment]
> 请问解决了嘛

**Comment by Bai-shen** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/7610#issuecomment-1445664335请问问题解决了吗？

**Comment by Bai-shen** [comment]
> > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > 
> > * 系统环境/System Environment：Linux
> > * 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
> > * 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
> > * 完整报错/Complete Error Message：
> >   [2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
> >   Traceback (most recent call last):
> >   File "tools/test_hubserving.py", line 157, in
> >   main(args)
> >   File "tools/test_hubserving.py", line 119, in main
> >   res = r.json()["results"][0]
> >   IndexError: string index out of range
> 
> 请问解决了嘛

**Comment by Bai-shen** [comment]
> > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > 
> > * 系统环境/System Environment：Linux
> > * 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
> > * 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
> > * 完整报错/Complete Error Message：
> >   [2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
> >   Traceback (most recent call last):
> >   File "tools/test_hubserving.py", line 157, in
> >   main(args)
> >   File "tools/test_hubserving.py", line 119, in main
> >   res = r.json()["results"][0]
> >   IndexError: string index out of range
> 
> 请问解决了嘛

请问问题解决了嘛？

**Comment by Han-Y-F** [comment]
> > > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > > 
> > > * 系统环境/System Environment：Linux
> > > * 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
> > > * 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
> > > * 完整报错/Complete Error Message：
> > >   [2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
> > >   Traceback (most recent call last):
> > >   File "tools/test_hubserving.py", line 157, in
> > >   main(args)
> > >   File "tools/test_hubserving.py", line 119, in main
> > >   res = r.json()["results"][0]
> > >   IndexError: string index out of range
> > 
> > 
> > 请问解决了嘛
> 
> 请问问题解决了嘛？

解决了，更换一下版本就好了

**Comment by xuxh6** [comment]
我是运行了 hub install ./deploy/hubserving/ocr_system/  之后就可以了，仅供参考

**Comment by keypher** [comment]
> > > > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > > > 
> > > > * 系统环境/System Environment：Linux
> > > > * 版本号/Version：Paddle： 2.6 PaddleOCR： 问题相关组件/Related components：
> > > > * 运行指令/Command Code：python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/ocr_system --image_dir=./ppstructure/docs/kie/input/ --visualize=false
> > > > * 完整报错/Complete Error Message：
> > > >   [2022/09/15 17:46:55] ppocr INFO: Predict time of ./ppstructure/docs/kie/input/zh_val_0.jpg: 0.871s
> > > >   Traceback (most recent call last):
> > > >   File "tools/test_hubserving.py", line 157, in
> > > >   main(args)
> > > >   File "tools/test_hubserving.py", line 119, in main
> > > >   res = r.json()["results"][0]
> > > >   IndexError: string index out of range
> > > 
> > > 
> > > 请问解决了嘛
> > 
> > 
> > 请问问题解决了嘛？
> 
> 解决了，更换一下版本就好了

请问是更换了什么的版本？更换到了哪个版本？
