### ISSUE TITLE
Typos in cpp_infer/read.me

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7618]
- Table recognition related parameters

|parameter|data type|default|meaning|
| :---: | :---: | :---: | :---: |
|table_model_dir|string|-|Address of table recognition inference model|
|table_char_dict_path|string|../../ppocr/utils/dict/table_structure_dict.txt|dictionary file|
|table_max_len|int|488|The size of the long side of the input image of the table recognition model, the final input image size of the network is（table_max_len，table_max_len）|
|merge_no_span_structure|bool|true|Whether to merge <td> and </td> to <td></td|

https://github.com/PaddlePaddle/PaddleOCR/edit/release/2.6/deploy/cpp_infer/readme.md

**Comment by andyjpaddle** [comment]
thanks for your feedback, we'll fix it
