### ISSUE TITLE
扫描英文文档 怎样逐词(word level)输出结果？

### ISSUE THREAD

**Issue by ichenjia** [PaddlePaddle/PaddleOCR#7622]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20
- 版本号/Version：Paddle： 2.6  PaddleOCR：2.6 问题相关组件/Related components： Dec/Rec
- 运行指令/Command Code：
```
ocr = PaddleOCR(use_angle_cls=True, 
                cls=True,
                use_gpu=True, 
                drop_score=0.4,
                use_mp=True,
                use_dilation=True,
                rec_algorithm="CRNN"
                det_db_score_mode="slow",
                warmup=True)
```
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

    
这里输出的结果好像都是一个区块一个区块的不是像tesseract一样一个字一个字的。根据[这个](https://github.com/PaddlePaddle/PaddleOCR/issues/5407)和[这个](https://github.com/PaddlePaddle/PaddleOCR/issues/7250)的提示，我试了[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_det_db_en.md)所有的模型，发现所有的都是按照几个词几个词一起输出。#5407 提到

_models trained on public English datasets are word level:_ @MissPenguin 

这里所有的model都不是啊？我这里有什么参数可以改或者我漏掉了什么东西么？谢谢🙏！

**Comment by LDOUBLEV** [comment]
不支持逐词输出结果，如果非要分开，可以根据空格划分识别的整行文本
text_list = text.split(" ")

**Comment by ichenjia** [comment]
如果出现字体不一样的情况这个坐标就对不上了啊。

**Comment by andyjpaddle** [comment]
> 如果出现字体不一样的情况这个坐标就对不上了啊。

目前只能通过空格来划分，暂时不支持逐词输出的，因为那会需要逐词进行标注，如果有需要可以自己标注数据进行重新训练。
