### ISSUE TITLE
SVTR 手写中文数据识别出现严重漏字的情况

### ISSUE THREAD

**Issue by sheirving** [PaddlePaddle/PaddleOCR#7625]
依据SVTR的配置训练自己的手写中文数据集（字符个数变动范围：2-15）（输入图像适配：64*512，其他配置不变），训练Loss下降到10左右难以再下降，推理模型发现精度极低，主要为漏字：
![image](https://user-images.githubusercontent.com/12372742/190589637-5d82493c-f74d-44df-b095-06eb071ae04e.png)
![image](https://user-images.githubusercontent.com/12372742/190589692-a3b7f9fd-b341-4787-9e9c-ccb2eba20091.png)
![image](https://user-images.githubusercontent.com/12372742/190589725-b387224f-f56c-4915-ba57-9aa4aba69682.png)

然后，将SVTR中的mixer = Local, 全部换成mixer = Global ，推理发现较为正常，不会出现严重的漏字现象，请问这个现象是否表明Local mixer 导致感受野过大以及丢失的信息较多导致？Local kernel的设置（7， 11）是否也需要结合训练样本的长度来调整？

**Comment by Topdu** [comment]
如果可以的话，麻烦展示几张实例图片和训练的配置文件，数据量有多少？

图像大小不一定越大越好，建议统计训练数据集的宽高比，高度设置为32或48即可，宽度根据统的计宽高比进行设置，如果图像文本均为水平文本，没有弯曲或者不规则文本，可以不使用STN。



> 请问这个现象是否表明Local mixer 导致感受野过大以及丢失的信息较多导致？Local kernel的设置（7， 11）是否也需要结合训练样本的长度来调整？

Local mixer是着重局部特征提取，感受野的设置可以做一些消融调整，一般可以设置为3*3，5*5，7*7，7*11等等，或者尝试将Local mixer设置为Conv， kernel设置为5*5

**Comment by sheirving** [comment]
训练配置：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/rec_svtrnet_ch.yml 基于这个适配了训练集的输入（64， 512），训练集200万样本，4卡3090训练1周
训练实例图：
<img width="511" alt="image" src="https://user-images.githubusercontent.com/12372742/190595309-6c0f62d7-20e3-4ab2-bd81-918ea7468e04.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/12372742/190595447-ec0bfa99-d644-4ea3-89a8-f29b1ed92866.png">
没有使用STN，我**先将Local mixer = Conv，这个实验跑完，看看结果吧**。但目前来看以（7， 11）的核， mixer前面6个Local训练难收敛。

**Comment by Topdu** [comment]
> 训练配置：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/rec_svtrnet_ch.yml 基于这个适配了训练集的输入（64， 512）

除了改动输入size，还改了其他地方吗？

这种图像建议将input size改为32*320，并且可以加载[中文大模型](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E9%AB%98%E7%B2%BE%E5%BA%A6%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B.md)。

**Comment by sheirving** [comment]
好的，谢谢。其他地方没有变化，我这边调整下输入大小再看看效果，再反馈下。

**Comment by Tavish77** [comment]
> 好的，谢谢。其他地方没有变化，我这边调整下输入大小再看看效果，再反馈下。

你好，想问一下可以提供SVTR模型的预训练参数吗，我加PPOCR的交流群加了一个多月了 都没有回应，

**Comment by vance-coder** [comment]
> 好的，谢谢。其他地方没有变化，我这边调整下输入大小再看看效果，再反馈下。

你好，请问下有什么反馈嘛？漏字是什么原因呀，我目前也遇到这个问题。非常感谢能解答
