### ISSUE TITLE
文字上下间距比较小，请问有什么办法可以提高检测效果吗？

### ISSUE THREAD

**Issue by klw2020** [PaddlePaddle/PaddleOCR#763]
![201](https://user-images.githubusercontent.com/53896985/93686321-116e0100-fae8-11ea-9f6a-0aa0bdf77b51.png)

![ndarray_1600539677 255332](https://user-images.githubusercontent.com/53896985/93686314-05823f00-fae8-11ea-98b1-3f1f92eeaee4.jpg)

请问有什么办法可以提高检测效果吗？

1.图片中间的文字上下间距比较小，检测效果很不好
2.左边的的单个数字检测不到
3.我想让他不要检测竖排功能，按单行分别检测 金、木、水、火、土

**Comment by MissPenguin** [comment]
你用的哪个模型呀

**Comment by klw2020** [comment]
https://www.paddlepaddle.org.cn/hubdetail?name=chinese_text_detection_db_server&en_category=TextRecognition

**Comment by LDOUBLEV** [comment]
检测模型训练时，数据中有竖排文本，无法手动设置是否检测竖排。可以换个检测模型，主页刚更新了新的模型

**Comment by klw2020** [comment]
是原图

**Comment by MissPenguin** [comment]
可以试试我们刚刚更新的1.1版模型：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md

**Comment by LDOUBLEV** [comment]
> 是原图

![image](https://user-images.githubusercontent.com/26592129/93686572-af160000-fae9-11ea-9d94-62ec886365d6.png)
主要是这里太密集了

**Comment by klw2020** [comment]
![det_res_201](https://user-images.githubusercontent.com/53896985/93686647-3499b000-faea-11ea-8686-52283444ec5a.png)

最新版效果好一点点，我用百度ocr高精度版才能检测出来

**Comment by klw2020** [comment]
重新训练了一下，效果好多了
