### ISSUE TITLE
French layout recovery

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [PaddlePaddle/PaddleOCR#7630]
Hello,

Is it possible to perform french layout recovery. From what I could understand is that layout analysis can only be perform in chinese or english. However, it exists multilingual models for OCR. So wouldn't it be possible to specify these multilingual models within layout recovery ?

Thanks !

**Comment by andyjpaddle** [comment]
you can try to realize this function according to the Chinese or English model
