### ISSUE TITLE
请问老师，SER和RE的论文出来了吗

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7631]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
暂时还没有，发布的话会在首页更新
