### ISSUE TITLE
请教关于训练的问题，训练必须裁剪成图片里只有目标文字吗

### ISSUE THREAD

**Issue by YFforever2022** [PaddlePaddle/PaddleOCR#7632]
训练必须裁剪成图片里只有目标文字吗，就是一张图片对应识别的文字，不支持一张图片多处文字吗，有没有相关的例子学习一下

**Comment by YFforever2022** [comment]
移动字/2021-12-10 013543.bmp	[{"transcription": "茅", "points": [[260, 121], [335, 119], [336, 173], [261, 175]], "difficult": false}, {"transcription": "笔", "points": [[369, 133], [428, 133], [428, 190], [369, 190]], "difficult": false}, {"transcription": "或", "points": [[160, 146], [208, 146], [208, 200], [160, 200]], "difficult": false}, {"transcription": "无", "points": [[35, 138], [100, 138], [100, 202], [35, 202]], "difficult": false}, {"transcription": "茅", "points": [[272, 4], [331, 4], [331, 66], [272, 66]], "difficult": false}]


这样的格式无法被训练，有转换方式吗

**Comment by YFforever2022** [comment]
试过用示例的格式，单张图片训练单个字或者句子可以成功

**Comment by YFforever2022** [comment]
有没有办法让识别只返回单个字而不是整个句子

**Comment by tink2123** [comment]
上述格式是端到端的标签，无法直接用于识别，需要转换成 `图片路径\t文本标签内容` 这样的格式

识别返回单字or句子取决于检测模型的输出，目前ppocr检测训练数据都是句子级别，因此无法输出单字坐标。如有需要可以使用自己的数据训练模型。

**Comment by YFforever2022** [comment]
明白了
