### ISSUE TITLE
请问paddleocr可以编译32位的吗？

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#7636]
paddeocr 64位可以编译通过并且顺利运行。

我尝试编译paddeocr 为32位

但是发现其中依赖的mklml.dll等库不支持32位的

请问有什么办法吗？

我是想通过32位的EXE调用 paddleocr

**Comment by littletomatodonkey** [comment]
你好，paddle目前应该没有提供32位的预测库哈
