### ISSUE TITLE
表格模型SLANet训练过程中位置坐标损失 loc_loss  一直为0

### ISSUE THREAD

**Issue by chx-xuan** [PaddlePaddle/PaddleOCR#7639]
您好，使用自己的数据集，训练表格SLANet模型，训练过程中loc_loss 一直为0 ，60次epoch，structure_loss 就正常，而且，acc也会在0.5以上，找不到原因，batch_size 为12。
谢谢！

**Comment by WenmuZhou** [comment]
贴一下标注和配置
