### ISSUE TITLE
PGnet训练问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#7644]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 使用aistudio，上面分享的数据集进行训练，只修改了数据路径。
![image](https://user-images.githubusercontent.com/57654726/190981620-87488e6e-0d18-4661-8711-1500efe0b50c.png)

**Comment by littletomatodonkey** [comment]
看着训练正常，评估报错，应该是评估数据格式有问题

**Comment by xialei2821212670** [comment]
> 看着训练正常，评估报错，应该是评估数据格式有问题

我改了数据集，使用的是中文字符集，是需要修改哪些配置？使用ch_PP-OCRv2_det_student.yml,训练是没问题的

**Comment by mingming0611** [comment]
> > 看着训练正常，评估报错，应该是评估数据格式有问题
> 
> 我改了数据集，使用的是中文字符集，是需要修改哪些配置？使用ch_PP-OCRv2_det_student.yml,训练是没问题的

请问您的配置文件在训练中文数据集时都修改了哪些地方，显存大概多大才够呢？
