### ISSUE TITLE
未来有可能开放自定义rec_image_shape参数吗

### ISSUE THREAD

**Issue by VieteChen** [PaddlePaddle/PaddleOCR#7647]
貌似在源码里写死了，我图片是56*56的，试了一下训练配置文件改为image_shape: [3, 48, 48]，源码改为params.rec_image_shape = "3, 48, 48"，又快又准。但项目不能改源码，未来有可能开放自定义rec_image_shape参数吗
if params.ocr_version == 'PP-OCRv3':
    params.rec_image_shape = "3, 48, 320"
else:
    params.rec_image_shape = "3, 32, 320"

**Comment by littletomatodonkey** [comment]
whl包的话，你直接在初始化OCR对象的时候，指定rec_image_shape即可

**Comment by VieteChen** [comment]
> whl包的话，你直接在初始化OCR对象的时候，指定rec_image_shape即可

传参没用，源码写死了。
![image](https://user-images.githubusercontent.com/45503948/191197550-1e6adf6b-0f0c-4dbf-b31b-2faa69d6f605.png)
![image](https://user-images.githubusercontent.com/45503948/191197812-b525b5ef-242b-44c9-af2e-2338ed7acddc.png)
但貌似用这种奇伎淫巧能改:：
ocr.args.rec_image_shape = '3, 48, 48'
ocr.text_recognizer = TextRecognizer(ocr.args)

另外请问是否有直接使用TextRecognizer识别的demo
