### ISSUE TITLE
SVTR模型训练超参数设置问题

### ISSUE THREAD

**Issue by willpat1213** [PaddlePaddle/PaddleOCR#7649]
我希望能够对齐论文精度，如果使用DDP的训练方式，在八卡的情况下，相关参数例如batchsize和lr应该怎么给呢？

**Comment by Topdu** [comment]
svtr-tiny训练时单卡batchsize为512，使用4卡，lr为0.0005，如果要更改batchsize，lr随着batchsize线性改变即可，例如，单卡batchsize为256，使用4卡，lr则需改为0.00025。
small base large同理。

**Comment by yulm-1** [comment]
想问一下就是按照他的相关参数训练的话，4个卡tiny需要训练多久？数据集就用他给的那个街景的数据集

**Comment by willpat1213** [comment]
训练集指的那两个合成数据集吗，四张a100需要一天多

**Comment by yulm-1** [comment]
> 训练集指的那两个合成数据集吗，四张a100需要一天多

不是合成数据集是[Chinese Benckmark]那个数据集

**Comment by willpat1213** [comment]
那个是作为测试集吧，训练还是合成的

**Comment by yulm-1** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_svtr.md  中的
![image](https://user-images.githubusercontent.com/113872348/191446870-d45f36d4-bc7e-4e96-acb6-07db1fba9df6.png)
他没有提供合成数据集呀


> 那个是作为测试集吧，训练还是合成的

**Comment by willpat1213** [comment]
这里都是测试集，训练集都是syth和mj，论文中有提到

**Comment by yulm-1** [comment]
> 这里都是测试集，训练集都是syth和mj，论文中有提到

好的，非常感谢

**Comment by yulm-1** [comment]
> 这里都是测试集，训练集都是syth和mj，论文中有提到

请问你有这两个数据集吗？

**Comment by yulm-1** [comment]
![image](https://user-images.githubusercontent.com/113872348/191457811-8e20c3a6-cd93-4fa9-bc4b-4047ccf229b4.png)
我又认真的看了一下这个论文，他应该就是用[Chinese Benckmark]提的数据集进行中文任务的训练，英文的训练用的是syth和mj这两个数据集
