### ISSUE TITLE
PaddleOCR-2.6 GPU版本MFC运行报错：无法定位程序输入点dnnl_prelu_backward_desc_init于动态链接库paddle_inference.dll上

### ISSUE THREAD

**Issue by stq054188** [PaddlePaddle/PaddleOCR#7650]
- Win10 64位 企业版  VS2017社区版

-PaddleOCR v2.6 GPU版本 ， CUDA10.1, cudnn-10.1-windows10-x64-v7.6.5.32，TensorRT-6.0.1.5.Windows10.x86_64.cuda-10.1.cudnn7.6

- 运行指令/Command Code：
- 控制台运行指令：ppocr.exe --det_model_dir=./model_1/en_PP-OCRv3_det_infer/ --rec_model_dir=./model_1/en_PP-OCRv3_rec_infer/ --image_dir=./imgs/
- 控制台运行结果正常：
- I0919 19:55:04.800885  7316 naive_executor.cc:102] ---  skip [feed], feed -> x
I0919 19:55:04.803768  7316 naive_executor.cc:102] ---  skip [softmax_2.tmp_0], fetch -> fetch
predict img: ./imgs\A.png
W0919 19:55:04.862386  7316 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0919 19:55:04.862386  7316 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
./imgs\A.png
0       det boxes: [[12,53],[636,48],[636,102],[12,107]] rec text: Improve Brand Awareness rec score: 0.960799
1       det boxes: [[95,137],[574,143],[573,197],[94,191]] rec text: The Best to Rely on rec score: 0.941441
2       det boxes: [[473,248],[630,247],[630,265],[473,266]] rec text: OpenCVA rec score: 0.911527
The detection visualized image saved in ./output//A.png
***************************

MFC环境下运行报错
- 完整报错/Complete Error Message：
无法定位程序输入点dnnl_prelu_backward_desc_init于动态链接库paddle_inference.dll上
![image](https://user-images.githubusercontent.com/15775782/191011832-229ed93d-50b1-4f4a-83b3-b3282a3ea116.png)

同样的Demo，使用PaddleOCR 2.6 CPU版本，MFC可正常运行：
![image](https://user-images.githubusercontent.com/15775782/191012179-097f80e3-d7d0-442a-97b4-bf6b0dc4d63b.png)

**Comment by littletomatodonkey** [comment]
之前没遇到过，查了下，可以试着把dll加到系统环境变量里试下，或者可以先看下仅使用cpp代码（不依赖mfc），能否跑通gpu推理
