### ISSUE TITLE
RUN RARE Inference

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#7651]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：uabntu 18 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddle 2.3.2 cuda 10.2 cudnn 8.2
- 运行指令/Command Code：
python3 tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_att.yml -o Global.pretrained_model=./rec_r34_vd_tps_bilstm_att_v2.0_train/best_accuracy Global.save_inference_dir=./inference/rec_rare

the first command convert success,but the second RUN command failed

command
python3 tools/infer/predict_rec.py --image_dir="doc/imgs_words/en/word_1.png" --rec_model_dir="./inference/rec_rare/" --rec_image_shape="3, 32, 100" --rec_char_dict_path= "./ppocr/utils/ic15_dict.txt"

- 完整报错/Complete Error Message：

[2022/09/19 23:34:33] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1663601673 (unix time) try "date -d @1663601673" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 25723 (TID 0x7f465e2af740) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by littletomatodonkey** [comment]
看着与rare模型无关，你先试下cpu模式能否推理，或者试下其他模型能否推理成功呢？

**Comment by cqray1990** [comment]
> 看着与rare模型无关，感觉是预测库环境问题，你先试下cpu模式能否推理，或者试下其他模型能否推理成功呢？
python3 tools/infer_rec.py -c configs/rec/rec_r34_vd_tps_bilstm_att.yml -o Global.pretrained_model=./rec_r34_vd_tps_bilstm_att_v2.0_train/best_accuracy Global.infer_img=doc/imgs_words/en/word_1.png
这个命令是可以运行的，
用export_model.py转了之后就报上面的错误，

**Comment by cqray1990** [comment]
@littletomatodonkey
