### ISSUE TITLE
老师，请问检测加识别的python全推理有准确率的指标吗？在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7654]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
[文本检测+文本识别端到端指标文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/end2end/readme.md)

**Comment by 1998wy123** [comment]
老师，问您个问题，我是在predict_system.py里推理的，怎么在这个py里写这些指标呢？我想看图片推理的准确率






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 老师，请问检测加识别的python全推理有准确率的指标吗？在线等 (Issue #7654)





 
文本检测+文本识别端到端指标文档

**Comment by 1998wy123** [comment]
好的，谢谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问检测加识别的python全推理有准确率的指标吗？在线等 (Issue #7654)





 
看一下上面那个文档吧，就是执行predict_system后计算指标

**Comment by 1998wy123** [comment]
请教您一个问题，预测指标评价这里，gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗？就是图里的两个label_path。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 老师，请问检测加识别的python全推理有准确率的指标吗？在线等 (Issue #7654)





 
看一下上面那个文档吧，就是执行predict_system后计算指标

**Comment by an1018** [comment]
是的，pred就是第一步执行predict_system之后的txt，不过gt图片真实标注路径不局限于ppocrlablel标注，自己数据有标签也可以(但需要是[检测数据格式](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/dataset/ocr_datasets.md#11-paddleocr-%E6%96%87%E5%AD%97%E6%A3%80%E6%B5%8B%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)

**Comment by 1998wy123** [comment]
老师，如果是icdar数据的话，gt必须是全标注的吗？可以用文本识别的标签去评估吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 中午1:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问检测加识别的python全推理有准确率的指标吗？在线等 (Issue #7654)





 
是的，pred就是第一步执行predict_system之后的txt，不过gt图片真实标注路径不局限于ppocrlablel标注，自己数据有标签也可以(但需要是检测数据格式
