### ISSUE TITLE
does StyleText support long inputs with spaces between words?

### ISSUE THREAD

**Issue by Ao-Lee** [PaddlePaddle/PaddleOCR#7655]
I would like to ask does StyleText support sentence inputs (document style rather than single words from street views) with spaces between them? or would you have plans on that, many thanks

**Comment by an1018** [comment]
During training, StyleText takes images of size 32×320, so if the text is too long, the effect may not be good. Thanks for your suggestion, but the version of long inputs is not planned to be developed at this stage.

**Comment by Ao-Lee** [comment]
Thank you for answering. I would like to ask, when training a recognition model, does the model learn to recognize space when feeding input images containing only one word. Would StyleText support short words with white spaces that satisfy the input resolution (32×320). Thanks again

**Comment by an1018** [comment]
Spaces are not supported in styleText. 
For space recognition, , the blank area around a single word is relatively large, and may not be good effect.
You can add a space category to the training dictionary, and then add some samples with spaces for training.
