### ISSUE TITLE
Click to flash back

### ISSUE THREAD

**Issue by LibertyWidget** [PaddlePaddle/PaddleOCR#7657]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PS H:\git\paddle\PaddleOCR\PPOCRLabel> py PPOCRLabel.py --lang ch --gpu False
C:\Users\Patrick\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\fluid\framework.py:516: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
[2022/09/20 12:22:06] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\det_0.jpg
DirPath in importDirImages is H:/git/paddle/PaddleOCR/deploy/android_demo/app/src/main/assets/images
unicodeFilePath is H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\rec_1_180.jpg
15952301928
unicodeFilePath is H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\rec_1.jpg
file name in openNext is  H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\rec_1_180.jpg
unicodeFilePath is H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\rec_1_180.jpg
unicodeFilePath is H:\git\paddle\PaddleOCR\deploy\android_demo\app\src\main\assets\images\rec_0_180.jpg
Traceback (most recent call last):
  File "H:\git\paddle\PaddleOCR\PPOCRLabel\libs\canvas.py", line 614, in paintEvent
    p.drawLine(self.prevPoint.x(), 0, self.prevPoint.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'

**Comment by TengTengCai** [comment]
Traceback (most recent call last):
  File "C:\Users\TianJun\Documents\GitProject\PaddleOCR\PPOCRLabel\libs\canvas.py", line 614, in paintEvent
    p.drawLine(self.prevPoint.x(), 0, self.prevPoint.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'

**Comment by Evezerest** [comment]
你好，可以详细描述一下标注流程，方便我们复现一下
