### ISSUE TITLE
Which external software is used to edit Excel for table annotation? The Excel cannot pop up when I clicked on the Table Recognition button in the upper right corner of PPOCRLabel

### ISSUE THREAD

**Issue by luowang8182** [PaddlePaddle/PaddleOCR#7658]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PPOCRLabel  table annotation
- 运行指令/Command Code：python PPOCRLabel.py --lang ch --kie True
- 完整报错/Complete Error Message：sh: 1: open: not found

Which external software is used to edit Excel for table annotation? The Excel cannot pop up when I clicked on the Table Recognition button in the upper right corner of PPOCRLabel. How to resolve it?

**Comment by an1018** [comment]
Using the table recognition model in [PP-Structure](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/table/README.md).
The platform you’re using is Windows, Linux or Mac? For more information, please refer to [PPOCRLabel document](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/PPOCRLabel/README.md)

**Comment by luowang8182** [comment]
My platform is Linux.

**Comment by luowang8182** [comment]
> Using the table recognition model in [PP-Structure](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/table/README.md). The platform you’re using is Windows, Linux or Mac? For more information, please refer to [PPOCRLabel document](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/PPOCRLabel/README.md)

Thanks for your reply. My platform is Linux (ubuntu). I have check the document of the PPOCRLabel and PP-Structure. However, I cannot find the information about the installment of Excel.   Therefore, I cannot use the tool of table structure annotation.

**Comment by light42** [comment]
In the directory where you installed PPOCRLabel:
1. open `PPOCRLabel.py`.
2. Delete this lines
https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/PPOCRLabel/PPOCRLabel.py#L2371-L2391
3. And replace it with these
```python
try:
    os.startfile(os.path.normpath(excel_path))
except:
    print("CANNOT OPEN .xlsx. It could be the following reasons: " \
         ".xlsx is not existed") 
```
