### ISSUE TITLE
 Check failed: (kernels.size() > 0): 0!>0 Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.

### ISSUE THREAD

**Issue by ppppppppyyyy** [PaddlePaddle/PaddleOCR#7660]
paddle-lite2.10， nb模型是PP-OCRv3(slim)
还是会出现错误，怎么解决？
![image](https://user-images.githubusercontent.com/58112895/191203919-04a99839-b628-4501-a24e-47e8b0b2ce85.png)

**Comment by ppppppppyyyy** [comment]
参考这个issue：https://github.com/PaddlePaddle/PaddleOCR/issues/6619
直接下载官方标的nb模型还是错误，需要自己下载2.10的opt工具（与预测库版本对应）转换 为nb模型

**Comment by an1018** [comment]
预测库和Paddlelite版本一致吗

**Comment by ouxiand** [comment]
预测库和Paddlelite版本一致,我也出现这个问题了，    2022-10-10 10:03:07.028 14557-14557/com.baidu.paddle.lite.demo.yolov5n_detection A/Paddle-Lite: [F 10/10 10: 3: 7. 28 ...e_210rc/Paddle-Lite/lite/core/program.cc:356 RuntimeProgram] Check failed: (kernels.size() > 0): 0!>0 
    Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.
2022-10-10 10:03:07.029 14557-14557/com.baidu.paddle.lite.demo.yolov5n_detection E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F 10/10 10: 3: 7. 28 ...e_210rc/Paddle-Lite/lite/core/program.cc:356 RuntimeProgram] Check failed: (kernels.size() > 0): 0!>0 
    Error: This model is not supported, because kernel for 'io_copy' is not supported by Paddle-Lite.
    
    
    --------- beginning of crash
2022-10-10 10:03:07.029 14557-14557/com.baidu.paddle.lite.demo.yolov5n_detection A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14557 (lov5n_detection)

**Comment by ouxiand** [comment]
官方的nb模型和我自己转的nb模型都一样     测试了好几种安卓手机和设备    使用GPU的模型都出现上面的错误

**Comment by JohnLoveMm** [comment]
官网的cls模型可能存在版本问题，需要安装paddlelite之后，按照步骤手动转一遍模型
