### ISSUE TITLE
运行 tools/infer/predict_system.py  --use_gpu=True 出现segmentation fault

### ISSUE THREAD

**Issue by bldu** [PaddlePaddle/PaddleOCR#7661]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 显卡： Tesla T4
- 版本号/Version：Paddle：2.3.2  PaddleOCR： 问题相关组件/Related components：
- 
- 运行指令/Command Code：
 python tools/infer/predict_system.py     --image_dir="./doc/vqa/input/zh_val_21.jpg"     --det_model_dir="./output/det_db_inference/"     --rec_model_dir="./output/rec_crnn_inference/"     --rec_image_shape="3, 32, 320"     --rec_char_dict_path="../XFUND/word_dict.txt" --use_gpu=True

- 完整报错/Complete Error Message：
\--------------------------------------
C++ Traceback (most recent call last):
\--------------------------------------
No stack trace in paddle, may be caused by external reasons.

\----------------------
Error Message Summary:
\----------------------
FatalError: \`Segmentation fault\` is detected by the operating system.
  [TimeInfo: *** Aborted at 1663661289 (unix time) try "date -d @1663661289" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 8569 (TID 0x7f35e1551240) from PID 0 ***]

---
整个工程来源于这里 https://aistudio.baidu.com/aistudio/projectdetail/3884375?channelType=0&channel=0   ，是一个表单识别项目。执行上面的推理命令后， 如果 `--use_gpu=False` 即用 cpu进行推理是可以正常跑的，但是改为 `--use_gpu=True`后就会报上面的 Segmentation fault。

另外，这个问题是在自己的服务器上跑才存在的，在AI studio上是没有问题的。

**Comment by BeyondYourself** [comment]
个人看法：服务器上有问题，aistudio上没问题，GPU的版本或者安装问题

**Comment by bldu** [comment]
> 个人看法：服务器上有问题，aistudio上没问题，GPU的版本或者安装问题

感谢你的回复。我用官网的pip方式装一直有问题，后面改用conda install安装就正常了。也不知道原因是什么。。。

**Comment by BeyondYourself** [comment]
可能你有两个Py版本，conda是3.7，本地环境是3.5

**Comment by dizhenx** [comment]
> 

你装的什么？
