### ISSUE TITLE
How to use StyleText to generate text image with your own font？

### ISSUE THREAD

**Issue by goodmight** [PaddlePaddle/PaddleOCR#7665]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
python tools/synth_image.py -c configs/config.yml --style_image examples/style_images/2.jpg --text_corpus 123456  --language art_font
- 完整报错/Complete Error Message：
 No Errors but model predict（synth image） gives bad result with art font.

# Here is what I've found. 

In StyleText/engine/synthesisers.py, 40:

    def synth_image(self, corpus, style_input, language="en"):
        corpus_list, text_input_list = self.text_drawer.draw_text(              # <---------- this draw_text work fine with font : **C:\Windows\fonts\complex_.ttf**
            corpus, language, style_input_width=style_input.shape[1])
        synth_result = self.predictor.predict(style_input, text_input_list)  # <----------   this predict which synth the text image with the background fails. It generates Korean text image with English or digits corpus.
        return synth_result

textImage generated in digits.
![fake_inprogress](https://user-images.githubusercontent.com/28631741/191248375-3afcdc9e-caeb-4975-aa52-75565ba7051c.jpg)
![fake_inprogress2](https://user-images.githubusercontent.com/28631741/191248382-4425ad71-b342-44cf-8879-4d35dc090c8b.jpg)

but synth image is in Korean.
![fake_text](https://user-images.githubusercontent.com/28631741/191248394-d27147cf-4eb2-4901-82f9-7af527f3437b.jpg)
![fake_fusion](https://user-images.githubusercontent.com/28631741/191248369-bcc34874-ccce-463a-9979-9358f4fa638c.jpg)

How to train the downloaded model with new fonts? Thanks!
the download url is: https://paddleocr.bj.bcebos.com/dygraph_v2.0/style_text/style_text_models.zip
as given in the [StyleText/README.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/StyleText/README_ch.md)

**Comment by an1018** [comment]
Training code is not provided at this stage

**Comment by sheltonsuen** [comment]
@goodmight 你有找到替代方案么？遇到同样问题了

**Comment by goodmight** [comment]
> @goodmight 你有找到替代方案么？遇到同样问题了

Hao dai wo yeshi yong yingwen tiwende ba, ni za zhijie yong zhongwen wen wo （・∀・）

我的替代方案是發現我不需要這個背景圖片。所以直接用白底寫字（PIL的方法）了。

**Comment by sheltonsuen** [comment]
> 

好的，多谢，我发现我也得舍弃这个嘞，我准备用 inpatint 的方式，先扣掉然后再写上去新的

**Comment by Sencc** [comment]
请问是在哪一步骤修改呢
