### ISSUE TITLE
[QUESTION] Difference between key_cls and label

### ISSUE THREAD

**Issue by light42** [PaddlePaddle/PaddleOCR#7672]
When I trained KIE with my own custom annotation created by ppocrlabel, it failed because the dictionary file lacked `label` key.
So I proceed to insert the `label` key with it's value copied directly from `key_cls`.

So my question now is:
1. Am I doing it right by copying `key_cls`?
2. What's the difference between `key_cls` and `label`?
3. And why `label` doesn't automatically provided by ppocrlabel when it's actually required for training?

**Comment by rubensanchezrivero** [comment]
is there any insight here
