### ISSUE TITLE
识别问题

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleOCR#7673]
![image](https://user-images.githubusercontent.com/44918749/191462914-a74372c2-59e9-495e-8b4a-93d336c130f2.png)
像这种图片，一个字也识别不出来，试过调整图片的大小，也是一样的。请问下，应该怎么处理呢？

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/191645354-f147bf14-cd7e-45c3-902f-e5a4b2c7fa45.png)
默认参数识别的结果

**Comment by KyleWang-Hunter** [comment]
![img](https://user-images.githubusercontent.com/44918749/191689076-c183fee3-6780-4b3f-98ae-bc88dc14f5c3.png)
我把图片截取成这个样子是能准确识别出来的，请问应该怎么优化？
