### ISSUE TITLE
疑似错别字

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#7675]
文档标题
4.2.3 基于牧师推断的预测
疑似错别字

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md)
]

**Comment by huangjun12** [comment]
文档好像没错别字了
