### ISSUE TITLE
can not conver pdf file to word

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#7676]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos
- 版本号/Version：Paddle：develop  PaddleOCR：2.6  问题相关组件/Related components：paddocr whl包。
- 运行指令/Command Code：
# pdf测试文件
paddleocr --image_dir=ppstructure/recovery/UnrealText.pdf --type=structure --recovery=true --lang='en'
- 完整报错/Complete Error Message：
  File "/usr/local/python3.7.12/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 615, in main
    image_file_list = get_image_file_list(args.image_dir)
  File "/usr/local/python3.7.12/lib/python3.7/site-packages/paddleocr/ppocr/utils/utility.py", line 60, in get_image_file_list
    raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in ppstructure/recovery/UnrealText.pdf

**Comment by ipfgao** [comment]
一样的问题。是不是不支持pdf？
