### ISSUE TITLE
ppstructure quick start exception while using python inference 

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#7677]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos
- 版本号/Version：Paddle：develop  PaddleOCR： 2.6 问题相关组件/Related components：
- 运行指令/Command Code：

2.2.1 图像方向分类+版面分析+表格识别
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True, image_orientation=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/1.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = 'doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

- 完整报错/Complete Error Message：
result.jpg 显示的文字识别结果有误:

![image](https://user-images.githubusercontent.com/17264083/191647693-be205941-c51c-454c-8aab-623250ed7a35.png)

**Comment by an1018** [comment]
hi，you can use this code
`table_engine = PPStructure(show_log=True, image_orientation=False, lang='en')`
