### ISSUE TITLE
window下 按照标准操作 报编码错误，该如何解决

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7678]
![image](https://user-images.githubusercontent.com/38007233/191647731-b62cd5e5-9a77-4143-8460-526df5947cbb.png)

**Comment by husiluanxiang** [comment]
主要是一些文件无法解析 数据集都是在官网下载的
![image](https://user-images.githubusercontent.com/38007233/191652624-01552ed6-186c-4453-b01e-283aa977a8ed.png)

**Comment by MissPenguin** [comment]
可以试试这里的解决办法：https://blog.csdn.net/qq_42281053/article/details/80677686
