### ISSUE TITLE
cuda11.4环境，分类模型报错，报错：[operator < hard_swish > error] 

### ISSUE THREAD

**Issue by hailong1991** [PaddlePaddle/PaddleOCR#7679]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   void phi::HardSwishKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, float, float, float, phi::DenseTensor*)
5   void phi::funcs::ElementwiseKernel<float, phi::funcs::CudaHardSwishFunctor<float>, 1>(phi::GPUContext const&, std::vector<phi::DenseTensor const*, std::allocator<phi::DenseTensor const*> > const&, std::vector<phi::DenseTensor*, std::allocator<phi::DenseTensor*> >*, phi::funcs::CudaHardSwishFunctor<float>)
6   float const* phi::DenseTensor::data<float>() const
7   phi::DenseTensor::data() const
8   phi::DenseTensor::check_memory_size() const
9   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
10  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is d73728 memory's size is 256.
  [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):73728 > memory_size():256.] 

[operator < hard_swish > error]

**Comment by MissPenguin** [comment]
安装的什么版本的paddle呢，推荐使用2.3
