### ISSUE TITLE
识别结果不对

### ISSUE THREAD

**Issue by ppppppppyyyy** [PaddlePaddle/PaddleOCR#7680]
与手机联调，程序能跑通，识别结果只有一个字？

![image](https://user-images.githubusercontent.com/58112895/191650806-6b437f03-611e-45c8-83d4-a765181073f0.png)

**Comment by MissPenguin** [comment]
使用的哪个模型呢，是说量化模型直接推理没问题，使用opt工具转nb模型后结果不对吗？
