### ISSUE TITLE
PaddleLabel error

### ISSUE THREAD

**Issue by htaoruan** [PaddlePaddle/PaddleOCR#7681]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version：Paddlepaddle：2.3.2  PaddleOCR：2.6.01 PPOCRLabel    2.1.1 问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/113572928/191652911-b8bd1005-9433-4eb5-8e6f-5d605601e03e.png)

**Comment by MissPenguin** [comment]
使用什么功能、操作哪一步的识别报的错呢？

**Comment by htaoruan** [comment]
点击矩形框，标注的时候报错，自动识别不错，识别之后修正矩形框报错，点击按钮之后，在图像上操作就闪退



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月24日 16:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] PaddleLabel error (Issue #7681) |

使用什么功能、操作哪一步的识别报的错呢？

**Comment by MissPenguin** [comment]
> 点击矩形框，标注的时候报错，自动识别不错，识别之后修正矩形框报错，点击按钮之后，在图像上操作就闪退
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年09月24日 16:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [PaddlePaddle/PaddleOCR] PaddleLabel error (Issue #7681) | 使用什么功能、操作哪一步的识别报的错呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

任意图像上都稳定复现吗？

**Comment by MissPenguin** [comment]
> 点击矩形框，标注的时候报错，自动识别不错，识别之后修正矩形框报错，点击按钮之后，在图像上操作就闪退
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年09月24日 16:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [PaddlePaddle/PaddleOCR] PaddleLabel error (Issue #7681) | 使用什么功能、操作哪一步的识别报的错呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

任意图像上都稳定复现吗？

**Comment by MissPenguin** [comment]
> 点击矩形框，标注的时候报错，自动识别不错，识别之后修正矩形框报错，点击按钮之后，在图像上操作就闪退
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年09月24日 16:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [PaddlePaddle/PaddleOCR] PaddleLabel error (Issue #7681) | 使用什么功能、操作哪一步的识别报的错呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

任意图像上都稳定复现吗？

**Comment by Evezerest** [comment]
你好，我们没有复现出这个问题，方便告知pyqt以及windows的版本吗

**Comment by htaoruan** [comment]
好的，后面暂时没用这个了，明天有时间给你反馈详细的




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月28日 20:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] PaddleLabel error (Issue #7681) |

你好，我们没有复现出这个问题，方便告知pyqt以及windows的版本吗

**Comment by Evezerest** [comment]
可以更新 2.1.2版本的PPOCRLabel whl包
