### ISSUE TITLE
中文识别任务中cuda和cudnn安装之后不成功，是什么原因造成的

### ISSUE THREAD

**Issue by yulm-1** [PaddlePaddle/PaddleOCR#7682]
![image](https://user-images.githubusercontent.com/113872348/191665721-1ddef469-ab6e-4ebb-9987-7fed798ab3bc.png)
安装的是这个配置
![image](https://user-images.githubusercontent.com/113872348/191665776-3941fa04-bd83-47f9-939d-cc27bda27f30.png)
服务器
![image](https://user-images.githubusercontent.com/113872348/191665880-0a6cd18d-b355-4ff1-88a0-a24b74b51d36.png)
有大神知道是什么原因吗

**Comment by MissPenguin** [comment]
可以到Paddle官网提个issue问一下哈：https://github.com/PaddlePaddle/Paddle/issues
