### ISSUE TITLE
文档链接错误

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/PaddleOCR#769]
端侧部署的教程里面，所有链接都无法显示内容

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/770

**Comment by lgcy** [comment]
> fixed in #770

还有端侧部署的demo中增加了角度分类模型，教程是不是需要更新下，以及利用opt优化的角度分类模型的下载链接可以给出吗

**Comment by LDOUBLEV** [comment]
> > fixed in #770
> 
> 还有端侧部署的demo中增加了角度分类模型，教程是不是需要更新下，以及利用opt优化的角度分类模型的下载链接可以给出吗

稍后更新下，今天完成，更新后在这里回复

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/791

**Comment by lgcy** [comment]
> fixed in #791

大佬，我看你们的端侧部署采用的是Makefile，请问有CMakelist的例子
