### ISSUE TITLE
识别时 内存一直增加不释放

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleOCR#7690]
从开始的5个G 到十几张图片的8个G
paddleocr==2.5.0.3

**Comment by MissPenguin** [comment]
是会一直增加到爆掉还是稳定在一个值呢

**Comment by sunshineyg2018** [comment]
> 是会一直增加到爆掉还是稳定在一个值呢

一直增加不释放

**Comment by sunshineyg2018** [comment]
@MissPenguin

**Comment by thsno02** [comment]
+ 把配置文件中 `use_shared_memory = True` 改成 `False` 试试;
+ 把 `num_workers` 调成 0 试试。

**Comment by clw5180** [comment]
C++的怎么调？

**Comment by jomda** [comment]
这个问题有解吗
