### ISSUE TITLE
请问老师，表格识别推理的whl包有没有准确率这样的指标可以用呢？在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7694]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
whl包只是推理，评估可以用python的eval工具

**Comment by 1998wy123** [comment]
hit, dt_count, gt_count 1557 2693 3283 character_acc: 61.77% avg_edit_dist_field: 3.08 avg_edit_dist_img: 51.82 precision: 57.82% recall: 47.43% fmeasure: 52.11%
请问老师，指标里，hit, dt_count, gt_count分别代表什么呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 请问老师，表格识别推理的whl包有没有准确率这样的指标可以用呢？在线等 (Issue #7694)





 
whl包只是推理，评估可以用python的eval工具

**Comment by MissPenguin** [comment]
命中多少个正确的框，检测到的文本框个数，gt中的文本框个数
