### ISSUE TITLE
关于训练检测模型，初始学习率设置的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7700]
请问，我现在训练V3-cml的蒸馏模型，检测的训练集有8000多张，一张显卡，batch-size最大设置为3。   请问学习率应该设置多少呢？？？       看官方的finetune文档，里面说单卡bs=4，学习率设置5e-5 （0.0005）  这样会不会太小了？        我设置的epoch=500, lr=0.0005 训练了17个epoch了，指标效果不太好，并且best_epoch还一直是第二个epoch。       请问怎么设置学习率合适呢？

**Comment by BeyondYourself** [comment]
个人看法，因为是微调，所以学习率最初的时候可以设置稍微大一点
