### ISSUE TITLE
训练检测模型，图片上有中文有英文，只想要中文部分，英文字母的可以不标注么？

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7701]
例如，身份证和表格（有些身份证中文上面是有相应的英文字母的）     只想要中文的部分，那么英文字母，在训练检测模型时，可以不标注图片中英文的部分，只标注图片中文的部分么，对检测模型效果会有影响吗？？

还是都需要标，在后处理时候，在判断英文的部分，给它筛除掉？

**Comment by BeyondYourself** [comment]
检测应该问题不大吧，如果只检测一种语言

**Comment by LDOUBLEV** [comment]
可以不用标注

> 在后处理时候，在判断英文的部分，给它筛除掉？

另一重保险
