### ISSUE TITLE
PPOCRLabel 矩形框选和四点框选程序崩溃

### ISSUE THREAD

**Issue by TengTengCai** [PaddlePaddle/PaddleOCR#7702]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10
- 版本号/Version：
paddle-bfloat==0.1.7
paddleocr==2.6.0.1
paddlepaddle==2.3.2
PPOCRLabel==2.1.0
 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：
PS C:\Users\TianJun> PPOCRLabel
点击矩形框选或快捷键w后等待2秒程序崩溃

[2022/09/23 11:20:21] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  C:\Users\TianJun\Pictures\2022-09-06\images\00000901.jpg
DirPath in importDirImages is C:/Users/TianJun/Pictures/2022-09-06/images
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\PPOCRLabel\libs\canvas.py", line 614, in paintEvent
    p.drawLine(self.prevPoint.x(), 0, self.prevPoint.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'

**Comment by Evezerest** [comment]
你好，我们没有复现出这个问题，方便告知pyqt以及windows的版本吗

**Comment by Evezerest** [comment]
可以更新 2.1.2版本的PPOCRLabel whl包

**Comment by DongFengLegend** [comment]
同样发生这个问题，新版什么时候发布？

**Comment by zhang0227** [comment]
> 可以更新 2.1.2版本的PPOCRLabel whl包

你好 我遇到同样的问题 更新了whl到2.1.2 也没有解决。请问应该用哪个版本的pyqt，我是5.15.7
