### ISSUE TITLE
印章弯曲文字检测识别 

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#7704]
![image](https://user-images.githubusercontent.com/57654726/191889982-a286aa21-918a-4949-9374-1ce81f04b93e.png)
，使用det_r50_db++_icdar15.yml，进行训练，
![image](https://user-images.githubusercontent.com/57654726/191890065-b086dd74-f85c-471f-8cdd-5a33c9975cb9.png)
，训练过程算正常？使用小批量数据进行测试时，也是这样，效果不行

**Comment by LDOUBLEV** [comment]
辛苦改一下后处理参数，PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 2.0
  use_polygon: true # if true, the model is used for arbitrary-shape text dataset.

**Comment by TinkingLoeng** [comment]
我自己利用检测然后后处理处理印章文字（极坐标转换拉平），然后造了一些有背景文字的印章数据finetune识别网络，效果挺好的，不过制作了圆形印章，椭圆不咋地

**Comment by TinkingLoeng** [comment]
我自己利用检测然后后处理印章文字（极坐标转换拉平），然后造了一些有背景文字的印章数据finetune识别网络，效果挺好的（没背景文字干扰的印章识别率为96%，有背景文字干扰的识别率为86%），不过我们的任务是圆形印章，因此椭圆和个人签章没搞，估计椭圆效果可能一般

**Comment by TinkingLoeng** [comment]
我自己利用检测然后后处理印章文字（极坐标转换拉平），然后造了一些有背景文字的印章数据finetune识别网络，效果挺好的（没背景文字干扰的印章识别率为96%，有背景文字干扰的识别率为86%），不过我们的任务是圆形印章，因此椭圆和个人签章没搞，估计椭圆效果可能一般（测试集数量970个印章，都不在检测和识别模型训练集验证集里）

**Comment by jingsongliujing** [comment]
> 我自己利用检测然后后处理印章文字（极坐标转换拉平），然后造了一些有背景文字的印章数据finetune识别网络，效果挺好的（没背景文字干扰的印章识别率为96%，有背景文字干扰的识别率为86%），不过我们的任务是圆形印章，因此椭圆和个人签章没搞，估计椭圆效果可能一般（测试集数量970个印章，都不在检测和识别模型训练集验证集里）

您好，请问有训练好的印章检测模型吗，能否分享一下？

**Comment by Randy-1009** [comment]
> 

请问是字符级的准确率还是文本级（一整串文字都正确）的识别率呢？

**Comment by mingming0611** [comment]
您好，请问有训练好的检测圆形印章检测模型吗，能否分享一下？

**Comment by xialei2821212670** [comment]
> 辛苦改一下后处理参数，PostProcess: name: DBPostProcess thresh: 0.3 box_thresh: 0.6 max_candidates: 1000 unclip_ratio: 2.0 use_polygon: true # 如果为 true，则模型用于任意形状的文本数据集。

修改了，训练后，还是评估比较底，precision:0.39左右，后面反而在下降

**Comment by phb-shiyige-fw** [comment]
> 辛苦改一下后处理参数，PostProcess: name: DBPostProcess thresh: 0.3 box_thresh: 0.6 max_candidates: 1000 unclip_ratio: 2.0 use_polygon: true # if true, the model is used for arbitrary-shape text dataset.

你好 我想问一下 按照修改后进行的训练 100个epoch 最好的hmean=0.56出现在第二个epoch，然后后面的hmean到后面基本都在0.2-0.3左右，这是正常的吗？数据集是500+200
