### ISSUE TITLE
请教大家一个问题，预测指标评价这里，gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗？python3 tools/end2end/convert_ppocr_label.py --mode=gt --label_path=path/to/label_txt --save_folder=save_gt_label  python3 tools/end2end/convert_ppocr_label.py --mode=pred --label_path=path/to/pred_txt --save_folder=save_PPOCRV2_infer

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7705]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
> gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗

是的

**Comment by 1998wy123** [comment]
请教您个问题， hit,&nbsp;dt_count,&nbsp;gt_count代表什么呢？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月24日(星期六) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 请教大家一个问题，预测指标评价这里，gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗？python3 tools/end2end/convert_ppocr_label.py --mode=gt --label_path=path/to/label_txt --save_folder=save_gt_label  python3 tools/end2end/convert_ppocr_label.py --mode=pred --label_path=path/to/pred_txt --save_folder=save_PPOCRV2_infer (Issue #7705)





  
gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗
  
是的

**Comment by LDOUBLEV** [comment]
gt_count 表示groundTruth框的数量，dt_count检测到的框的数量，hit检测并识别对的框的数量

**Comment by 1998wy123** [comment]
谢谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月26日(星期一) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 请教大家一个问题，预测指标评价这里，gt的标签路径是指用ppocrlabel标注得到的，pred的标签路径是推理结果的那个txt路径吗？python3 tools/end2end/convert_ppocr_label.py --mode=gt --label_path=path/to/label_txt --save_folder=save_gt_label  python3 tools/end2end/convert_ppocr_label.py --mode=pred --label_path=path/to/pred_txt --save_folder=save_PPOCRV2_infer (Issue #7705)





 
gt_count 表示groundTruth框的数量，dt_count检测到的框的数量，hit检测并识别对的框的数量
