### ISSUE TITLE
训练时文本检测模型时发现GPU利用率很低

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7712]
![image](https://user-images.githubusercontent.com/38007233/191922556-32d820b2-f60d-4fee-b37e-acd382ccb1be.png)
请问有什么办法解决吗

**Comment by husiluanxiang** [comment]
![image](https://user-images.githubusercontent.com/38007233/191922817-8329923d-b86b-4ec4-b512-cf441220711f.png)

**Comment by LDOUBLEV** [comment]
增大batchsize

**Comment by zzk2021** [comment]
增大batchsize也不行，增大就爆了，利用率上不去
