### ISSUE TITLE
检测正确，识别错误

### ISSUE THREAD

**Issue by TinkingLoeng** [PaddlePaddle/PaddleOCR#7713]
执行识别的时候报错：
![image](https://user-images.githubusercontent.com/28384596/191926445-6258ff08-f7f4-4f7d-846a-d2855ca2d1bf.png)
但是明明libcublas.so已存在在cuda-10.2/lib64里面了
cuda: 10.2
cudnn: 7.6.0
paddle: 2.5.0

**Comment by LDOUBLEV** [comment]
配置下LD_LIBRARY_PATH试试；
你的paddle版本是多少，不是2.5吧

**Comment by TinkingLoeng** [comment]
> 

多次尝试配了LD_LIBRARY_PATH都不行，是2.5

**Comment by TinkingLoeng** [comment]
> 配置下LD_LIBRARY_PATH试试； 你的paddle版本是多少，不是2.5吧

多次尝试配了LD_LIBRARY_PATH都不行，是2.5；但如果真的环境有问题，没理由就rec不行，det和cls都可以。

**Comment by junedgar** [comment]
@TinkingLoeng  解决了吗  遇到同样的问题  检测可以   识别报错
