### ISSUE TITLE
训练文本检测模型的标注规范问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7718]
训练一个文本检测模型 
      1.文本内容是正的，然后将图片中所有的文字都用标准矩形框框出来，而不是单独点四个点，四个点位置信息是矩形
      2.文本中的所有内容，检测时的类别都设置的一个'data'类 
   请问：这两种标注的会影响检测模型效果么？   所有的类都是data有影响么？
   
   
以下是训练文本检测模型时的train.txt 
train_sy/sy_248.jpg	[{"transcription": "data", "points": [[257, 286], [1005, 286], [1005, 420], [257, 420]]}, {"transcription": "data", "points": [[276, 513], [724, 513], [724, 638], [276, 638]]}, {"transcription": "data", "points": [[908, 513], [1297, 513], [1297, 631], [908, 631]]}, {"transcription": "data", "points": [[260, 737], [1556, 737], [1556, 849], [260, 849]]}, {"transcription": "data", "points": [[263, 990], [1799, 990], [1799, 1105], [263, 1105]]}, {"transcription": "data", "points": [[609, 1124], [1456, 1124], [1456, 1264], [609, 1264]]}, {"transcription": "data", "points": [[244, 1572], [917, 1572], [917, 1684], [244, 1684]]}, {"transcription": "data", "points": [[1033, 1560], [2634, 1560], [2634, 1694], [1033, 1694]]}]
train_sy/sy_162.jpg	[{"transcription": "data", "points": [[264, 75], [591, 75], [591, 118], [264, 118]]}, {"transcription": "data", "points": [[243, 141], [621, 141], [621, 197], [243, 197]]}, {"transcription": "data", "points": [[208, 316], [295, 316], [295, 341], [208, 341]]}, {"transcription": "data", "points": [[322, 318], [548, 318], [548, 340], [322, 340]]}, {"transcription": "data", "points": [[208, 368], [298, 368], [298, 394], [208, 394]]}, {"transcription": "data", "points": [[314, 368], [564, 368], [564, 392], [314, 392]]}]
train_sy/sy_185.jpg	[{"transcription": "data", "points": [[251, 68], [607, 68], [607, 123], [251, 123]]}, {"transcription": "data", "points": [[224, 148], [637, 148], [637, 209], [224, 209]]}, {"transcription": "data", "points": [[183, 333], [271, 333], [271, 361], [183, 361]]}, {"transcription": "data", "points": [[300, 335], [449, 335], [449, 363], [300, 363]]}, {"transcription": "data", "points": [[179, 389], [272, 389], [272, 415], [179, 415]]}, {"transcription": "data", "points": [[299, 389], [571, 389], [571, 417], [299, 417]]}]
train_sy/sy_203.jpg	[{"transcription": "data", "points": [[122, 211], [484, 211], [484, 251], [122, 251]]}, {"transcription": "data", "points": [[306, 152], [421, 152], [421, 186], [306, 186]]}, {"transcription": "data", "points": [[123, 146], [254, 146], [254, 181], [123, 181]]}, {"transcription": "data", "points": [[126, 74], [334, 74], [334, 120], [126, 120]]}, {"transcription": "data", "points": [[343, 464], [779, 464], [779, 504], [343, 504]]}, {"transcription": "data", "points": [[116, 466], [299, 466], [299, 500], [116, 500]]}, {"transcription": "data", "points": [[215, 377], [247, 377], [247, 413], [215, 413]]}, {"transcription": "data", "points": [[220, 328], [554, 328], [554, 368], [220, 368]]}, {"transcription": "data", "points": [[122, 282], [552, 282], [552, 326], [122, 326]]}]

**Comment by andyjpaddle** [comment]
文本检测不会用到文本的信息，所以都写data不影响模型效果，矩形框也是四个点，读取数据标注没问题就行
