### ISSUE TITLE
发现一个崩溃问题，请修复

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#7720]
void Utility::sorted_boxes(std::vector<OCRPredictResult> &ocr_result) {

```
   //这里需要对 ocr_results进行判断，否则后面就崩溃了
    if (ocr_result.size() == 0)
        return;
```
  std::sort(ocr_result.begin(), ocr_result.end(), Utility::comparison_box);

  for (int i = 0; i < ocr_result.size() - 1; i++) {
    if (abs(ocr_result[i + 1].box[0][1] - ocr_result[i].box[0][1]) < 10 &&
        (ocr_result[i + 1].box[0][0] < ocr_result[i].box[0][0])) {
      std::swap(ocr_result[i], ocr_result[i + 1]);
    }
  }
}

**Comment by WenmuZhou** [comment]
这个问题dygraph已经修复了

**Comment by iknow34languages** [comment]
> 这个问题dygraph已经修复了

好的谢谢
