### ISSUE TITLE
在尝试将ser_LayoutXLM_xfun_zh_infer推理模型转换为onnx模型时报错

### ISSUE THREAD

**Issue by labmanno004** [PaddlePaddle/PaddleOCR#7722]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8
- 版本号/Version：Paddle： 2.3.2 PaddleOCR：2.6.0.1 问题相关组件/Related components：paddle2onnx：1.0.0
- 运行指令/Command Code：paddle2onnx --model_dir ./ser_LayoutXLM_xfun_zh_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./kie_onnx/ser_LayoutXLM_xfun_zh_infer-paddle-op13-fp32-N.onnx --opset_version 13 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True
- 完整报错/Complete Error Message：[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./ser_LayoutXLM_xfun_zh_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./ser_LayoutXLM_xfun_zh_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
[libprotobuf ERROR /jiangjiajun/paddle2onnx_workspace/protobuf/src/google/protobuf/message_lite.cc:426] paddle2onnx.ModelProto exceeded maximum protobuf size of 2GB: 2235041916
[Paddle2ONNX] Error happenedd while optimizing the exported ONNX model.
[Paddle2ONNX] The exported ONNX model is invalid!
[Paddle2ONNX] Paddle model convert failed.

**Comment by WenmuZhou** [comment]
暂不支持转换为onnx

**Comment by shelleyyyyu** [comment]
> 暂不支持转换为onnx

请问什么时候会支持？
