### ISSUE TITLE
能提供c++ onnxruntime 调用onnx 进行ocr的解码例子吗

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#7723]
请问能提供c++ onnxruntime 调用onnx 进行ocr的解码例子吗？我用paddleocr的模型导出onnx，然后使用c++ onnxruntime 调用进行推理，怎么解码模型输出？

**Comment by WenmuZhou** [comment]
没有，解码输出可以参考一下https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/src/ocr_rec.cpp

**Comment by ronaldpan** [comment]
请问为什么要这样处理一下？
     if (argmax_idx > 0 && (!(n > 0 && argmax_idx == last_index)))

**Comment by purehol** [comment]
> 请问为什么要这样处理一下？ if (argmax_idx > 0 && (!(n > 0 && argmax_idx == last_index)))

参考ctc解码过程；默认 argmax_idx == 0 的是空白字符，只需要合并非空白字符到最终结果里，非空白字符需要满足：当前非空白字符的位置id为0，或者当前非空白字符的位置id > 0，且与前一位置的字符不相同。

再深究的话，可以看下ctc原理
