### ISSUE TITLE
east检测模型nms无法处理斜框的问题

### ISSUE THREAD

**Issue by locusbear** [PaddlePaddle/PaddleOCR#7725]
nms似乎无法处理斜框的情况，导致有许多重复的斜框出现
![Uploading det_res_shuiyin_723_924.jpg…]()

**Comment by LDOUBLEV** [comment]
测试了icdar2015，斜框结果是比较正常的，可否重新上传你的badcase；

另外，检查下是否是模型训练程度不够的问题
