### ISSUE TITLE
请问有可能取消protobuf版本限制吗

### ISSUE THREAD

**Issue by VieteChen** [PaddlePaddle/PaddleOCR#7726]
paddlepaddle 要3.20.0以下，grpcio-reflection要4.21.3以上，请问有办法二者兼得吗？
paddlepaddle 2.3.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 4.21.6 which is incompatible.
grpcio-reflection 1.49.1 requires protobuf>=4.21.3, but you have protobuf 3.20.0 which is incompatible.

**Comment by WenmuZhou** [comment]
这个在paddle的issue区问问看

**Comment by SeanXiao105** [comment]
请问解决了吗，我也是这个版本问题
