### ISSUE TITLE
paddleocr 2.2中的SRN文本识别算法出现targets: None

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#7728]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：1.7  PaddleOCR：2.2    问题相关组件/Related components：SRN识别网络训练报错
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 在运行paddleocr 2.2版本的SRN文本识别算法时候（batch：1，num_works：0），出现以下情况：
- 第一个iter有targets，第二个就拿不到targets
![image](https://user-images.githubusercontent.com/49891512/192198093-25fd9476-b31a-4af9-a624-9002b703b87f.png)
![image](https://user-images.githubusercontent.com/49891512/192198271-6d504631-1855-4111-b287-dfec63435cbd.png)

**Comment by WenmuZhou** [comment]
打印一下第二个iter的targets看看

**Comment by InferMaster** [comment]
进一步排查到是这个问题，执行train.py脚本的时候，第一个iter执行SRN部分，第二个就不执行了。
![image](https://user-images.githubusercontent.com/49891512/192222689-f5e26cf7-0d64-4041-93fa-a94c4dc9c7de.png)
![image](https://user-images.githubusercontent.com/49891512/192222798-621c2c72-ea5a-4828-9817-c3e6eb264d75.png)
