### ISSUE TITLE
LMDB格式的数据集不支持数据增强，想问下官方如果自己修改的话怎么去修改呢

### ISSUE THREAD

**Issue by angel-yi** [PaddlePaddle/PaddleOCR#7729]

**Comment by WenmuZhou** [comment]
支持的哦，和数据增强配置在dataset.transforms里就行

**Comment by angel-yi** [comment]
这里貌似是不行的，在配置文件中打开`RecConAug`参数的时候，会出现报错了，看了下源码是data里面没有ext_data
```KeyError: 'DataLoader worker(3) caught KeyError with message:\nTraceback (most recent call last):\n  File "/home/bxypython/.virtualenvs/paddle_ocr/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop\n    batch = fetcher.fetch(indices)\n  File "/home/bxypython/.virtualenvs/paddle_ocr/lib/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch\n    data.append(self.dataset[idx])\n  File "/tmp/pycharm_project_828/paddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__\n    outs = transform(data, self.ops)\n  File "/tmp/pycharm_project_828/paddleOCR/ppocr/data/imaug/__init__.py", line 50, in transform\n    data = op(data)\n  File "/tmp/pycharm_project_828/paddleOCR/ppocr/data/imaug/rec_img_aug.py", line 66, in __call__\n    for idx, ext_data in enumerate(data["ext_data"]):\nKeyError: \'ext_data\'\n'```

**Comment by angel-yi** [comment]
![image](https://user-images.githubusercontent.com/51775756/192221446-2dab1844-3137-4dc6-80b3-1a44db9ffee7.png)
对比sample data其中做了get_ext_data的操作

**Comment by angel-yi** [comment]
好的，谢谢
