### ISSUE TITLE
在进行关键信息提取训练时，配置文件文件为ser_vi_layoutxlm_xfund_zh.yml，其中该下载文件无法下载https://bj.bcebos.com/paddlenlp/models/transformers/community/vi-layoutxlm-base-uncased/model_config

### ISSUE THREAD

**Issue by xianyu211** [PaddlePaddle/PaddleOCR#7730]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
升级下paddlenlp
