### ISSUE TITLE
PPOCRv3的模型怎么进行迁移学习

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleOCR#7737]
怎么冻结模型前面的层，只对后面的层进行Transfer Learning

**Comment by littletomatodonkey** [comment]
model的定义在这里: [link](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppocr/modeling/architectures/base_model.py)，你希望冻结哪个模块，把那里所有的参数trainable设置为False即可。可以参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/ppocr/modeling/architectures/distillation_model.py#L51)进行设置。
