### ISSUE TITLE
关于ser如何指定预训练模型

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7738]
训练ser时 如何指定预训练模型 我先下载了预训练模型 然后按照断点训练的方式指定预训练模型 这个训练时报模型不对
![image](https://user-images.githubusercontent.com/38007233/192410351-066fefd9-a09d-4632-b803-e6c3d6ceb5b7.png)
![image](https://user-images.githubusercontent.com/38007233/192411290-e1958b62-912f-4c58-bf9f-194c2effb0be.png)

**Comment by littletomatodonkey** [comment]
你好，训练SER的时候，不需要指定预训练模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/kie.md


<img width="655" alt="image" src="https://user-images.githubusercontent.com/14270174/192477127-4ccce893-8a08-4bf9-bfbf-0b56e3e19dda.png">
