### ISSUE TITLE
PPStructur生成结果如何转化为excel呢

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#7747]
最近在使用paddleocr里面的ppstructur，发现ppstructur针对标准的表格，可以提取表格为excel导出。有一些表格，却识别不了，返回不了excel文件。针对这种，我该如何根据坐标转化成excel呢。

我的代码：
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True)

#你的文件结果目录
save_folder = './'

#输入的图片
img_path = '图片.jpeg'
img = cv2.imread(img_path)
result = table_engine(img)

我的测试图片：

![图片](https://user-images.githubusercontent.com/29837553/192505029-acb3cc56-1c5f-4a06-9c78-08acb33acb2d.jpeg)

我的返回结果：

![image](https://user-images.githubusercontent.com/29837553/192505255-fdeed5f8-b357-40fa-94b8-d0ba754e2e76.png)

**Comment by tianchiguaixia** [comment]
> 你这个似乎自己直接转为csv更快，简单的字符串拼接

可是怎么根据这些位置信息转换成类似图片上布局的csv呢

**Comment by EasyEDA2021** [comment]
> > 你这个似乎自己直接转为csv更快，简单的字符串拼接
> 
> 可是怎么根据这些位置信息转换成类似图片上布局的csv呢

我们现在做的一个功能是根据坐标算的（有点类似提取表格），坐标会告诉你大概位置

**Comment by tianchiguaixia** [comment]
这个下个版本会有？

**Comment by EasyEDA2021** [comment]
> 这个下个版本会有？

我不是开发者，只是用户
