### ISSUE TITLE
印章弯曲文本识别

### ISSUE THREAD

**Issue by mingming0611** [PaddlePaddle/PaddleOCR#7750]
![1](https://user-images.githubusercontent.com/113701415/192666315-0da15968-528e-4784-a2ef-a231d5da8710.JPG)
![2](https://user-images.githubusercontent.com/113701415/192666319-df2d94d6-2a7c-48ea-951d-7467ab356d0c.JPG)
小批量数据使用det_r50_db++_icdar15.yml，进行训练（使用的是ResNet50_dcn_asf_synthtext_pretrained.pdparams预训练模型），loss最终只能降到0.4左右，拿训练集直接进行评估的，recall和precision一直低于0.1，在配置文件部分也加了use_polygon: true该参数,标注格式如下(弯曲部分均采用16点或8点均匀标注，倾斜文本采用4点标注），想问一下如何解决该问题，完全达不到官方教程里光滑识别区域的效果。
![3](https://user-images.githubusercontent.com/113701415/192667497-f1267d65-725a-44fc-ab69-f26bd86aa33e.JPG)

**Comment by jingsongliujing** [comment]
我也是loss一直降不下来

**Comment by jingsongliujing** [comment]
可以加个微信一起聊聊吗

**Comment by xialei2821212670** [comment]
预测下保存的model没，可以看下怎么样

**Comment by an1018** [comment]
数据量有多少呢，还有有预测可视化结果吗

**Comment by KyleWang-Hunter** [comment]
我觉得自己训练很难达到很好的效果，尝试其他方案吧

**Comment by phb-shiyige-fw** [comment]
有没有朋友解决这个问题了？precision和recall都很低 loss降不下去

**Comment by wbj0110** [comment]
我也是loss下不去

**Comment by xialei2821212670** [comment]
> 我也是损失下不去

训练参数不对

**Comment by phb-shiyige-fw** [comment]
> 

请问有什么地方是需要注意的嘛？参数调整方面可以给点意见吗？

**Comment by leodywqqq** [comment]
我loss在下降，但是效果很差，参数调整有什么建议嘛！

**Comment by xialei2821212670** [comment]
有train.log？看下eval 的imageshape
