### ISSUE TITLE
PPOCRLabel问题

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleOCR#7753]
(1) 标签靠近底部，编辑的信息框会超出屏幕（这个框出现的位置和鼠标点击位置关联，如果超出显示屏，会使人误认为软件卡死）
![image](https://user-images.githubusercontent.com/51023060/192674793-604a6b17-f94a-4dcc-b71d-87940dedf505.png)
(2) 自动识别后编辑关键词类别，无法确认，结果无法保留。

- WIN10
- PaddleOCR： PPOCRLabel

**Comment by an1018** [comment]
收到，我反馈一下哈

**Comment by Evezerest** [comment]
你好，问题2可以更新一下whl包
