### ISSUE TITLE
部署多个模型，统一到一个服务

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleOCR#7754]
用的是 deploy/pdserving/web_service.py的方式来部署，现在串联文字定位与识别来作为一个服务。我想问的是，如果此时我想再添加另一类的识别（比如文档识别pp-structure），web_service.py里该怎么弄呢？

**Comment by an1018** [comment]
可以参考[基于PaddleServing的服务部署问文档](https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f8/deploy/pdserving/README_CN.md#%E5%9F%BA%E4%BA%8Epaddleserving%E7%9A%84%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2)
