### ISSUE TITLE
老师，请问ser+re任务里连线的键值对怎么取出来呢？我想把它打印出来，这个代码在哪里如何修改呢？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7755]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
结果存储在[result](https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/tools/infer_kie_token_ser_re.py#L209)内，可以参考[绘制结果函数](https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/ppocr/utils/visual.py#L80)的for循环把键值对读取出来

**Comment by 1998wy123** [comment]
谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 老师，请问ser+re任务里连线的键值对怎么取出来呢？我想把它打印出来，这个代码在哪里如何修改呢？ (Issue #7755)





 
结果存储在result内，可以参考绘制结果函数的for循环把键值对读取出来
