### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch.

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#7760]
This bug happens a lot of times in the recognition model. According to the given detection results, I doubt this is a preprocess issue.

Same issues:

+ https://github.com/PaddlePaddle/PaddleOCR/issues/6202
+ https://github.com/PaddlePaddle/PaddleOCR/issues/1379
+ https://github.com/PaddlePaddle/PaddleOCR/issues/959

The collaborator proposes to double-check the image size => which is a preprocess issue, since many images can work well.

**Comment by thsno02** [comment]
This is a consequence of the inaccurate detection model since the detection model yields multiple bounding boxes and some of them can't resize correctly in the recognition preprocess.

The original code is shown below<sup>1</sup> :

```
void CrnnResizeImg::Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio,
                        bool use_tensorrt,
                        const std::vector<int> &rec_image_shape) {
  int imgC, imgH, imgW;
  imgC = rec_image_shape[0];
  imgH = rec_image_shape[1];
  imgW = rec_image_shape[2];


  imgW = int(imgH * wh_ratio);


  float ratio = float(img.cols) / float(img.rows);
  int resize_w, resize_h;


  if (ceilf(imgH * ratio) > imgW)
    resize_w = imgW;
  else
    resize_w = int(ceilf(imgH * ratio));


  cv::resize(img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f,
             cv::INTER_LINEAR);
  cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                     int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                     {127, 127, 127});
}
```

This code doesn't take two scenarios into consideration:

+ The image height is larger than `imgH`, that is `img.rows>imgH`. 
+ The multiplication between `imgH` and `wh_ratio` may produce a larger value than the designed image width, that is ` int(imgH * wh_ratio) > imgW `.

Thus, the code should be

```
void CrnnResizeImg::Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio,
                        bool use_tensorrt,
                        const std::vector<int> &rec_image_shape) {
  int imgC, imgH, imgW;
  imgC = rec_image_shape[0];
  imgH = rec_image_shape[1];
  imgW = rec_image_shape[2];

  // @thsno02: handle the dimension mismatch issue
  if (imgW <= int(imgH * wh_ratio))
    imgW = int(imgH * wh_ratio);


  float ratio = float(img.cols) / float(img.rows);
  int resize_w, resize_h;

  // @thsno02: resize the image height
  resize_h = imgH;

  // @thsno02: use resize_h instead of imgH
  if (ceilf(resize_h * ratio) > imgW)
    resize_w = imgW;
  else
    resize_w = int(ceilf(resize_h * ratio));


  cv::resize(img, resize_img, cv::Size(resize_w, resize_h), 0.f, 0.f,
             cv::INTER_LINEAR);
  cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                     int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                     {127, 127, 127});
}
```

# Footnotes

<a name="ft1">[1]</a>: https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/deploy/cpp_infer/src/preprocess_op.cpp#L108-L131

**Comment by Aurora-Rong** [comment]
it is not work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by thsno02** [comment]
> it is not work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I found this is a pre-processing issue, and there are two potential issues:

+ Paddle rounds the width/height if the width/height can't be divided evenly, and the rounding operator is implemented multiple times, which will make the final result not divisible by 32 => make sure ur pre-defined image width/height is a multiple of 32;
+ the detection results have irregular `wh_ratio`, and the recognition pre-processing doesn't handle it properly => fixed

**Comment by Aurora-Rong** [comment]
Hello, I set the width and height of the image to a multiple of 32, but it still does not work, what do you mean by the second method ah, how to modify, thanks a million

**Comment by thsno02** [comment]
They have fixed the code, u may need to update ur code.

https://github.com/PaddlePaddle/PaddleOCR/blob/2be9fe763e4ebb55d59cc192eee437b0e09207ce/ppocr/data/imaug/rec_img_aug.py#L567-L591

**Comment by amm266** [comment]
> They have fixed the code, u may need to update ur code.
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/2be9fe763e4ebb55d59cc192eee437b0e09207ce/ppocr/data/imaug/rec_img_aug.py#L567-L591

i have the same problem on new clone and versions, what should i do?
please help[
