### ISSUE TITLE
 hub serving添加structure_system后报错

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleOCR#7762]
```
hub install deploy/hubserving/structure_system
```
![image](https://user-images.githubusercontent.com/7626261/192749334-c22f363a-8e5f-4641-b002-a199e9ef303d.png)

```
hub serving start -c deploy/hubserving/config.json
```
报错
![image](https://user-images.githubusercontent.com/7626261/192749429-eee45d63-ebd2-4480-95b0-903c02b562ad.png)

**Comment by Sencc** [comment]
1.把/ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt文件复制到报错的目录
2.更改/deploy/hubserving/structure_system/params.py里的cfg.layout_dict_path的路径
