### ISSUE TITLE
Corrupt Jpeg data 

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7763]
训练中出现这个是正常的吗 我是按照文档走的 用的xund数据集
![image](https://user-images.githubusercontent.com/38007233/192752146-d3d5f56b-12fc-4d76-a4c9-1fca5f0be7ea.png)

**Comment by an1018** [comment]
部分数据问题，可以忽略，或者筛选饼过滤出问题图片，可以参考这个issue #5029

**Comment by Fire-Star** [comment]
> 部分数据问题，可以忽略，或者筛选饼过滤出问题图片，可以参考这个issue #5029

大佬看看我这个issue：[#7757](https://github.com/PaddlePaddle/PaddleOCR/issues/7757)
