### ISSUE TITLE
使用自己造的数据集训练与测试集准确率较高，再用另一种情境下的扫描笔真实数据测试准确率几乎为0。

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#7764]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![图片1](https://user-images.githubusercontent.com/84179587/192769612-1b757e59-135c-46b3-8acf-6ee155f70292.png)

- 训练结果如上图所示
- 训练集大概100W张中文文本图，6W张英文文本图，字典包含中英文字符为7千左右，训练数据如下图所示：
- 
![ 0](https://user-images.githubusercontent.com/84179587/192770971-189f535a-b0f2-43de-9abd-f95bb345e06a.jpg)

**Comment by JavieYuan** [comment]
![image](https://user-images.githubusercontent.com/84179587/192771657-3e01db5c-4257-41ae-919b-4f5560416be0.png)

**Comment by JavieYuan** [comment]
使用真实的扫描笔拼接数据进行eval以及infer发现准确率为0，真实数据如下：
![image](https://user-images.githubusercontent.com/84179587/192772684-4cc9d838-ba52-4ecf-be5e-a25b089425e6.png)
![image](https://user-images.githubusercontent.com/84179587/192772820-6ecca8f4-6bdd-44c7-a057-742038da13ec.png)

**Comment by JavieYuan** [comment]
真实数据的识别结果类似如下所示，其中中文以及英文识别结果都很离谱：
./testdata/tr/000000017.bmp	蚕
./testdata/tr/000000018.bmp	疆晶曹


请问是什么原因呢？？？？？

**Comment by an1018** [comment]
1）推理的时候，字典更换了吗

**Comment by JavieYuan** [comment]
![que](https://user-images.githubusercontent.com/84179587/194742972-5325b913-55ff-46f1-aa28-4f94260959df.png)
请问关于输入图像32*320这部分，说把图像等比例缩放至3，32，320以及不足320部分补0，关于这部分的源码在哪里呀，好像不在数据增强rec_img_aug里面？？？

**Comment by JavieYuan** [comment]
> 1）推理的时候，字典更换了吗 2）可以用paddleOCRv3预训练模型直接预测看下效果 3）测试生成数据效果怎么样呢 4）生成的数据和真实数据还是有一些偏差，可以在生成数据集上再改造下

在训练的时候是没有用预训练模型的，是直接训练的，如果加载预训练模型开始训练的话泛化性会变强吗？还是说最终泛化性拟合效果仅仅趋向于自己人工合成的训练数据？训练数据是只有自己人工合成的
