### ISSUE TITLE
PP-OCRv3中文的预训练模型大概什么时候会放出来

### ISSUE THREAD

**Issue by dereksjtu** [PaddlePaddle/PaddleOCR#7766]
目前最新版本的中文预训练模型只有：ch_PP-OCRv2_det_distill_train.tar (https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_distill_train.tar)

**Comment by DreamJokerMJ** [comment]
早就有了啊！https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_distill_train.tar

**Comment by dereksjtu** [comment]
> 早就有了啊！https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_distill_train.tar

那这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md  可以考虑更新下
![image](https://user-images.githubusercontent.com/7299874/193149227-fc38c4bd-7cf7-4f44-8212-688f0bc26284.png)
