### ISSUE TITLE
手写体需要的训练数据中的label.txt在哪获得？？

### ISSUE THREAD

**Issue by bihui9968** [PaddlePaddle/PaddleOCR#7768]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

label_file_list:
    - ./train_data/chineseocr-data/rec_hand_line_all_label_train.txt # 训练集标签
    - ./train_data/handwrite/HWDB2.0Train_label.txt
    - ./train_data/handwrite/HWDB2.1Train_label.txt
    - ./train_data/handwrite/HWDB2.2Train_label.txt
    - ./train_data/handwrite/hwdb_ic13/handwriting_hwdb_train_labels.txt
    - ./train_data/handwrite/HW_Chinese/train_hw.txt

给的下载链接里没有。。

**Comment by SuperChrisliu** [comment]
老哥 你找到了吗

**Comment by zhangqiqi1228** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> label_file_list: - ./train_data/chineseocr-data/rec_hand_line_all_label_train.txt # 训练集标签 - ./train_data/handwrite/HWDB2.0Train_label.txt - ./train_data/handwrite/HWDB2.1Train_label.txt - ./train_data/handwrite/HWDB2.2Train_label.txt - ./train_data/handwrite/hwdb_ic13/handwriting_hwdb_train_labels.txt - ./train_data/handwrite/HW_Chinese/train_hw.txt
> 
> 给的下载链接里没有。。

請問你後來有拿到這幾個文件嗎？
