### ISSUE TITLE
SRN相同文本图片，截取长短不一致预测效果差很多的问题。

### ISSUE THREAD

**Issue by lovelynight** [PaddlePaddle/PaddleOCR#777]
hi，首先感谢开源SRN算法，nice work。
我在自有的中文数据集和合成数据上训练了一版SRN，目前发现一个问题，如下图
<img width="205" alt="截屏2020-09-19 下午10 36 18" src="https://user-images.githubusercontent.com/21274914/93734944-d2d26680-fc0d-11ea-9053-ee9f322f1d01.png">
预测ji结果是      2.《印刷经营许可证》是印刷    看起来还不错，但是我预测完整图片时，如图
<img width="472" alt="截屏2020-09-19 下午10 32 26" src="https://user-images.githubusercontent.com/21274914/93734995-f695ac80-fc0d-11ea-9573-65fc89b2f4e5.png">
预测结果是    2.(国际经济新新何西五五马地企业企企A民民地址址送爱送现地G地金海地地地海企一
完全是乱码了。我的理解是attention时输出的位置编码定位到了文字中间导致的，不知理解是否有误。其次，关于优化的思路，我尝试了在训练时将max_text_length调到50，但是结果依然不好，是不是我需要在训练样本中加入这样的长文本？
期待你们的回复！

**Comment by tink2123** [comment]
首先目前srn的 image_shape=[1,64,256]， 在中文场景中，如果希望预测长文本可以适当增大输入shape的宽度以适应长文本。不然在遇到长文本时，代码做resize之后会被过分压缩，造成识别困难。
另外，如果您的文本都是如上所示的印刷字体，推荐使用CRNN模型～ ctc在该领域已经够用了。

**Comment by lovelynight** [comment]
感谢你的回复，这个参数我有调过，忘了说，也就是可能是我调的还不够，我再去做点实验。crnn的话目前就是遇到了瓶颈，准确率只有97.73%，期望能够更高一些。crnn对于形近字的优化思路不知可否探讨一下，我们的badcase中形近字错误占了多数。
期待你们的回复。

**Comment by tink2123** [comment]
形近字错误一个是可以分析一下样本中的语料分布是否均衡，另外可能就需要借助一下srn的语义模块了。可以大概看一下你们的badcase吗？我们也参考一下～

**Comment by lovelynight** [comment]
数据不太方便提供～感谢解答！
