### ISSUE TITLE
表格结构识别label_ops.py文件中的TableLabelEncode类中貌似有逻辑错误

### ISSUE THREAD

**Issue by wangyihi** [PaddlePaddle/PaddleOCR#7787]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![【非密】3 技术白皮书 (3)_14_1](https://user-images.githubusercontent.com/86699196/193052624-b0c21a24-a5b7-4176-8b50-3b71af2bed5f.jpg)

1. 在ppocrlabel工具中标注没有处理空格，所以在生成的json文件中的cells中只有非空格的token跟bbox。如果一个表格（A表，如上图片）的第一个格子是空格，那么根据label_ops.py文件中的TableLabelEncode类中667行的位置的逻辑，A表第一个空格会对应上标注文件中的第一个非空格。
2. 如果将replace_empty_cell_token设置为true,但是在698行的_replace_empty_cell_token函数中，如下def _replace_empty_cell_token(self, token_list, cells):
        """
        This fun code is refer from:
        https://github.com/JiaquanYe/TableMASTER-mmocr/blob/master/table_recognition/data_preprocess.py
        """

        bbox_idx = 0
        add_empty_bbox_token_list = []
        for token in token_list:
            if token in ['<td></td>', '<td', '<td>']:
                if 'bbox' not in cells[bbox_idx].keys():
                    content = str(cells[bbox_idx]['tokens'])
                    token = self.empty_bbox_token_dict[content]
                add_empty_bbox_token_list.append(token)
                bbox_idx += 1
            else:
                add_empty_bbox_token_list.append(token)
        return add_empty_bbox_token_list
if 'bbox' not in cells[bbox_idx].keys():并没有起到任何作用，反而还会引起错误。

**Comment by WenmuZhou** [comment]
所以在标注的时候，需要标注空格cell
