### ISSUE TITLE
关于eval的问题

### ISSUE THREAD

**Issue by whuhangzhang** [PaddlePaddle/PaddleOCR#779]
@tink2123  @MissPenguin  您好，我有一些问题想要询问一下

### 1. end2end eval脚本问题
我在文档里面分别看到了检测和识别等分模块评测的代码，分别为：
- 检测
`python3 tools/eval.py -c configs/det/det_mv3_db.yml  -o Global.checkpoints="{path/to/weights}/best_accuracy" PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5`
- 识别
`python3 tools/eval.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints={path/to/weights}/best_accuracy`
- 分类
`python3 tools/eval.py -c configs/cls/cls_mv3.yml -o Global.checkpoints={path/to/weights}/best_accuracy`

但是我想知道如何评测end2end的效果呢，评测检测and识别的整体效果呢？例如全对率等等

### 2. end2end eval数据问题
如果上一问题的end2end的评测的数据应该如何组织呢，十分感谢您的回复！

**Comment by MissPenguin** [comment]
end2end的评估，我们是基于icdar2015的官方评估脚本改的，在这里：
![image](https://user-images.githubusercontent.com/25809855/93748057-336f9c80-fc2a-11ea-9c51-d288e98e6114.png)

**Comment by whuhangzhang** [comment]
了解了，十分感谢~
