### ISSUE TITLE
Incorrect recognition

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#7790]
Hello dear ocr team .

"rec_efficientb3_fpn_pren" model's output is incorrect after converting to inference model

**Comment by littletomatodonkey** [comment]
你好，这个pr修复了下，可以参考修改下：https://github.com/PaddlePaddle/PaddleOCR/pull/7833

**Comment by centurions** [comment]
Thank youuuuuuuuuuuuuu
