### ISSUE TITLE
请问，为什么中英文的训练模型是其推理模型的十倍之多？

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#7799]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
是说模型存储吗，因为转推理模型后，去掉了很多和推理无关的参数
