### ISSUE TITLE
Linux下服务器端C++部署生成ppocr文件后可以运行，但如何在C++项目中调用？

### ISSUE THREAD

**Issue by Vict0r-Chen** [PaddlePaddle/PaddleOCR#7800]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04.4 LTS
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：N/A
- 完整报错/Complete Error Message：N/A

现在已经按照[服务器端C++预测](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme_ch.md)生成了`ppocr`文件，使用命令也可以正确识别图片，但如何在C++项目中引用？有相关文档吗？没有C++头文件及dll类库，应该不会是直接通过控制台来实现调用吧？

**Comment by WenmuZhou** [comment]
可以参考社区其他编译成cpp 链接库的例子

**Comment by Vict0r-Chen** [comment]
是需要使用VS2022 cmake编译lib？方便可以给下相关的链接吗😣😣

**Comment by WenmuZhou** [comment]
可以百度一下，cmake 动态链接库，我们后续讨论一下是否做支持

**Comment by Vict0r-Chen** [comment]
这个感觉是最重要的一环呀，我是.NET开发者，不懂C++的话，没有教程根本没法使用，只能玩一玩😣😣

**Comment by Vict0r-Chen** [comment]
> 请问如何生成DLL呢？生成DLL后应该是很好调用的，百度步骤改了main函数，改了args.cpp的配置信息等还是调用不了

@zzwwr 最后我没有找到生成DLL的方法，通过部署hubservice，调用API来实现预测，这就与语言无关了，唯一的问题是速度不够理想

**Comment by zzwwr** [comment]
感谢您的回复 我了解了




|;.*嗨棈靈◆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] Linux下服务器端C++部署生成ppocr文件后可以运行，但如何在C++项目中调用？ (Issue #7800)





  
请问如何生成DLL呢？生成DLL后应该是很好调用的，百度步骤改了main函数，改了args.cpp的配置信息等还是调用不了
  
@zzwwr 最后我没有找到生成DLL的方法，通过部署hubservice，调用API来实现预测，这就与语言无关了，唯一的问题是速度不够理想
