### ISSUE TITLE
paddlepaddle-gpu版本不同在评估模型下做推理结果差距巨大

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#7801]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：  PaddleOCR：2.2 问题相关组件/Related components：gpu版本不同eval模型结果差距太大
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 我更新了paddle-gpu版本后再去做模型评估出现严重的问题，评估结果直接失效为0，我更换回来版本也不行
- 
![Uploading d920877cea2a1baa62969098538b68b.jpg…]()

![d53d48f1da87c850dce5aaa643308b9](https://user-images.githubusercontent.com/49891512/193415198-304ecfad-a9c5-4863-959f-a8e61bb1a16b.jpg)

**Comment by LDOUBLEV** [comment]
更新前后的paddle-gpu版本分别是什么？
