### ISSUE TITLE
SER算法是否可以商用

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#7804]
SER的算法和模型是否开源可以商用？

**Comment by jack-gits** [comment]
@andyjpaddle hi, SER 算法是开源的吗？ 是否可以商用。
SER页面上是(CC BY-NC-SA 4.0)开源协议， 而PaddleOCR是Apache2.0开源协议。
帮忙解惑！！！

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md

**Comment by andyjpaddle** [comment]
SER依赖于layoutxlm https://github.com/microsoft/unilm/blob/master/layoutxlm/README.md
这个里面说是不能商用，具体我们再确认一下哈，晚点给回复

**Comment by jack-gits** [comment]
等你的消息！！

**Comment by Evezerest** [comment]
你好，SER遵循[Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)协议，对于企业是否属于商用的情况需要具体判断
