### ISSUE TITLE
用icdar2015数据集进行文字检测模型训练时，出现的两个问题

### ISSUE THREAD

**Issue by KKKKQF** [PaddlePaddle/PaddleOCR#7814]
第一个： 
ppocr ERROR: When parsing line G:/Project/OCR/Train_ID/PaddleOCR/train_data/icdar2015/text_localization/ch4_training_images/img_161.jpg   [{"transcription": "LEVEL", "points": [[949, 22], [1032, 0], [1036, 22], [953, 44]]}, {"transcription": "###", "points": [[965, 253], [1051, 256], [1054, 288], [968, 287]]}, {"transcription": "###", "points": [[819, 177], [866, 174], [866, 181], [820, 185]]}, {"transcription": "###", "points": [[832, 193], [858, 190], [859, 197], [832, 201]]}, {"transcription": "###", "points": [[1072, 23], [1154, 5], [1157, 18], [1074, 35]]}, {"transcription": "###", "points": [[1038, 1], [1055, 1], [1058, 14], [1042, 19]]}]
, error happened with msg: Traceback (most recent call last):
  File "G:\Project\OCR\Train_ID\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "G:\Project\OCR\Train_ID\PaddleOCR\ppocr\data\imaug\__init__.py", line 53, in transform
    data = op(data)
TypeError: 'list' object is not callable
第二个：
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by WenmuZhou** [comment]
你的配置有问题

**Comment by KKKKQF** [comment]
> 你的配置有问题，大部分情况是没找到图片，可以先检查一下图片路径设置对了没
请问我这个上面不是已经读到图片数据了嘛，为什么他会找不到图片，都放在同一个文件夹中了

**Comment by jaysonteng** [comment]
请问问题解决了吗？我也遇到相同的问题

**Comment by KKKKQF** [comment]
> 请问问题解决了吗？我也遇到相同的问题

并没有，他只回答我配置有问题，但是我不懂哪里有问题，数据明明是可以读的到的，也是用ppocrlabel标注的，但是就是不行

**Comment by jaysonteng** [comment]
> > 请问问题解决了吗？我也遇到相同的问题
> 
> 并没有，他只回答我配置有问题，但是我不懂哪里有问题，数据明明是可以读的到的，也是用ppocrlabel标注的，但是就是不行

我也是ppocrlabel标注的，感觉是代码解析标注数据时候有问题，不知道别人训练是怎么通过的，我准备用公开的数据测试一下。

**Comment by KKKKQF** [comment]
> > > 请问问题解决了吗？我也遇到相同的问题
> > 
> > 
> > 并没有，他只回答我配置有问题，但是我不懂哪里有问题，数据明明是可以读的到的，也是用ppocrlabel标注的，但是就是不行
> 
> 我也是ppocrlabel标注的，感觉是代码解析标注数据时候有问题，不知道别人训练是怎么通过的，我准备用公开的数据测试一下。

我两种都试了下，这个是用icdar2015数据集转换成ppocr的数据集，还有一种自己标注的，结果都不行，兄弟如果试验成功了，麻烦踢下我，感谢

**Comment by jaysonteng** [comment]
> 

兄弟，有人给我指出来了，说是det模型和rec模型的数据格式是不一样的，你参考下https://github.com/PaddlePaddle/PaddleOCR/issues/8088
我也准备去试一下。

**Comment by jaysonteng** [comment]
> 

兄弟，有人给我指出来了，说是det模型和rec模型的数据格式是不一样的，你参考下https://github.com/PaddlePaddle/PaddleOCR/issues/8088
我也准备去试一下。

**Comment by KKKKQF** [comment]
> > 
> 
> 兄弟，有人给我指出来了，说是det模型和rec模型的数据格式是不一样的，你参考下#8088 我也准备去试一下。

好嘞好嘞，谢谢兄弟，我也试下
