### ISSUE TITLE
弯曲文本矫正

### ISSUE THREAD

**Issue by mingming0611** [PaddlePaddle/PaddleOCR#7817]
中文文本弯曲太严重（例如印章上凸下凹部分），文本检测后得到的文本区域边界点之间距离非常不均匀，采用tps算法拉平的效果很差，极坐标转换对于有旋转角度的图像和图像里下凹的文字不太适合。想问一下有什么其他的弯曲文本拉平的方法吗？

**Comment by dodgaga** [comment]
> 中文文本弯曲太严重（例如印章上凸下凹部分），文本检测后得到的文本区域边界点之间距离非常不均匀，采用tps算法拉平的效果很差，极坐标转换对于有旋转角度的图像和图像里下凹的文字不太适合。想问一下有什么其他的弯曲文本拉平的方法吗？

现在有好的方法吗？
