### ISSUE TITLE
您好，SVTR论文中对于中文数据集，设置的max_length为40，但是代码中设置的是25，请问哪个为准？

### ISSUE THREAD

**Issue by icecream-Tnak** [PaddlePaddle/PaddleOCR#7824]
非代码报错，关于论文内容和代码参数设置的疑问。
1）SVTR论文中对于中文数据集（Chinese Scene Dataset [Chen et al., 2021]），设置的max_length为40，但是代码中设置的是25，请问哪个为准？
2）请问上述数据集的实验中，初始lr是如代码中所示，为0.0005吗？论文中给出的初始lr为 3*1e-4 \times (batchsize / 512)，这与代码中的设置存在少许出入。

感谢paddle在ocr领域的杰出工作！！！

**Comment by Topdu** [comment]
> 1）SVTR论文中对于中文数据集（Chinese Scene Dataset [Chen et al., 2021]），设置的max_length为40，但是代码中设置的是25，请问哪个为准？

请使用下载模型时配套的配置文件，configs/rec/rec_svtrnet_ch.yaml不是svtr论文的配置文件.



> 2）请问上述数据集的实验中，初始lr是如代码中所示，为0.0005吗？论文中给出的初始lr为 3*1e-4 \times (batchsize / 512)，这与代码中的设置存在少许出入。

SVTR论文的配置文件默认4卡训练，lr是根据配置文件bs*gpu卡数设置
