### ISSUE TITLE
Light model Works only with upscaling image 

### ISSUE THREAD

**Issue by saylan21** [PaddlePaddle/PaddleOCR#7828]
Hello everyone,
I trained light weight detection model using pretrained model on the main page and the config `https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml`, after i converted to inference model, model didn't give any output for my 150x340 image size, but then i upscale the images to 300x680 it gives output. What i would like to ask is:
How can i train my model in a way that works **without** upscaling. Any suggestion is appreciated. 

Thanks

**Comment by huangjun12** [comment]
you can decrease the image size during training
