### ISSUE TITLE
resnet 蒸馏模型报错 ValueError

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleOCR#7829]
DML 蒸馏，使用Resnet50蒸馏Resent34时，报模型名称重复错误

- 版本号/Version：Paddle：  PaddleOCR：2.6
- 完整报错/Complete Error Message：
- 
ValueError: parameter name [conv1_1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by littletomatodonkey** [comment]
你好，这里简易把backbone里面定义名字的都去掉，如（demo地址：https://github.com/PaddlePaddle/PaddleOCR/blob/7f6c9a7b99ea66077950238186137ec54f2b8cfd/ppocr/modeling/backbones/rec_resnet_vd.py#L43）

```python
    self._conv = nn.Conv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size,
            stride=1 if is_vd_mode else stride,
            padding=(kernel_size - 1) // 2,
            groups=groups,
            weight_attr=ParamAttr(name=name + "_weights")
```

可以更新为

```python
    self._conv = nn.Conv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size,
            stride=1 if is_vd_mode else stride,
            padding=(kernel_size - 1) // 2,
            groups=groups,
```
