### ISSUE TITLE
PaddleOCR Android demo 编译错误

### ISSUE THREAD

**Issue by xireli** [PaddlePaddle/PaddleOCR#7837]
系统Mac M1，PaddleOCR2.6,
Android demo 编译报错，错误信息如下：

android_demo/app/src/main/cpp/CMakeLists.txt : C/C++ debug|x86 : CMake Error at 
 android_demo/app/src/main/cpp/CMakeLists.txt:18 (find_package):
  Found package configuration file:

android_demo/app/src/main/cpp/../../../OpenCV/sdk/native/jni/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

请问这是环境配置问题还是别的原因？

**Comment by WenmuZhou** [comment]
没找到opencv，可以看看项目目录下有没有自动下载opencv

**Comment by xireli** [comment]
opencv项目已下载
<img width="350" alt="ooo" src="https://user-images.githubusercontent.com/42612287/194750174-0c7ef20c-576a-4ab7-9385-df0ee7d3c829.png">

**Comment by WenmuZhou** [comment]
再跑一下看看

**Comment by xireli** [comment]
一直不行，两台MBP同样的错误，还有可能什么原因？错误信息如下

<img width="1363" alt="oo3" src="https://user-images.githubusercontent.com/42612287/194816133-16f6e062-f66d-4979-ae2b-c286ec752cfb.png">

**Comment by WenmuZhou** [comment]
使用dygraph分之未能复现你的问题

**Comment by xireli** [comment]
好像只有2.6版本存在该问题，使用2.5版本正常。不管怎么样特别感谢PaddleOCR团队的贡献，致敬🫡！！！

**Comment by ZhuYi98** [comment]
我也遇到了，是因为源代码里build.gradle(:app)中cmake没有指定abi版本，加入以下代码:
```
cmake {
                cppFlags "-std=c++17 -frtti -fexceptions -Wno-format"
                arguments '-DANDROID_PLATFORM=android-23', '-DANDROID_STL=c++_shared' ,"-DANDROID_ARM_NEON=TRUE"
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
```
