### ISSUE TITLE
模型训练中途会自动中断。。

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/PaddleOCR#784]
我用自己的数据集，训练识别模型。。
在本地的机子上跑，是正常的。
相同的代码，弄到服务器上跑，就有问题。。---服务器配置：11G显存，20G内存，win10系统
发现是设置batch-size为64或32，代码跑不起来，python一直没有占用cpu。。显存则有明显使用。。
设置为32的batch时，有时候可以跑起来，但是一两次迭代后，就自动停止了。。即使我降低batch-size到16，也是类似情况（python开始有明显占用cpu，达到10%+， 迭代几次后，就自动降低了，后面直接变成0）.....显存占用什么的，都是正常的。。
另外，本地的机子上跑，（8G显存，32G内存，win10系统）, batch-size设置的32， python占用cpu为13左右。。。
死活没想通是什么原因，无法在服务器上跑。。。

**Comment by tink2123** [comment]
自动停止会出现报错信息吗？还是hang住了？一般训练多久会停止，是在eval的时候中断的吗？

**Comment by lmw0320** [comment]
> 自动停止会出现报错信息吗？还是hang住了？一般训练多久会停止，是在eval的时候中断的吗？

没有报错，怀疑是卡住了。。不是在eval的时候中断，而是在训练过程中中断。。。训练多久貌似不一定。。如果batch-size设置小些， 貌似能多训练一会，如果batch-size大些，则貌似就很快，甚至都没办法开始训练。我试过设置batch为8的情况下，貌似迭代到800个iteration，而设置为16的话，可能就到170个iteration。。而如果设置为64，则基本是一直卡着，都没见进入iteration。----这些batch的设置，都没有爆显存（我的服务器显存11G，图片设置大小用的默认值，没有改动）

**Comment by tink2123** [comment]
可以尝试一下关闭多进程呢？
https://github.com/PaddlePaddle/PaddleOCR/blob/9bcba212b2caee27f78863ddc407464a06f524ed/configs/det/det_db_icdar15_reader.yml#L4
num_workers 修改为1 试一下

**Comment by lmw0320** [comment]
> 可以尝试一下关闭多进程呢？
> https://github.com/PaddlePaddle/PaddleOCR/blob/9bcba212b2caee27f78863ddc407464a06f524ed/configs/det/det_db_icdar15_reader.yml#L4
> 
> 
> num_workers 修改为1 试一下
win10环境下，我本来就是设置num-workers=1的。。。
相同的配置，我在本地的机子上跑就没问题，batchsize为32，显存8G.。。而在服务器上显存11G，batchsize设置为32基本没反应，降低到16后，可以迭代几次，就停了。。再降到8，可以多迭代几次，后面还是自动停。。

**Comment by tyy2tyy** [comment]
请问解决了吗？我也遇到这个问题

**Comment by lmw0320** [comment]
> 请问解决了吗？我也遇到这个问题

木有。。。后面放弃了。。我当时用的1.0版本的paddleocr，现在升级到1.1版本了，还没去试是否可以。。

**Comment by Hiroshi230** [comment]
我也是，无法解决。。本地就好好的，lunix也好好的，就是win不行，诶。。
