### ISSUE TITLE
关于输入图像尺寸问题！

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#7847]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![que](https://user-images.githubusercontent.com/84179587/194743904-70ceabea-e737-44f6-831c-0474f9172569.png)
请问关于输入图像32*320这部分，说把图像等比例缩放至3，32，320以及不足320部分补0，关于这部分的源码在哪里呀，好像不在数据增强rec_img_aug里面？？？

**Comment by LDOUBLEV** [comment]
这部分代码在这个类里：
https://github.com/PaddlePaddle/PaddleOCR/blob/7f6c9a7b99ea66077950238186137ec54f2b8cfd/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml#L94

https://github.com/PaddlePaddle/PaddleOCR/blob/7f6c9a7b99ea66077950238186137ec54f2b8cfd/ppocr/data/imaug/rec_img_aug.py#L499

**Comment by JavieYuan** [comment]
> 这部分代码在这个类里：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/7f6c9a7b99ea66077950238186137ec54f2b8cfd/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml#L94
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/7f6c9a7b99ea66077950238186137ec54f2b8cfd/ppocr/data/imaug/rec_img_aug.py#L499

![Uploading ques2.png…]()
三个月前拉取的代码，我这边的rec_img_aug.py如图所示，代码对应行都不一致了应该是旧版本，官方应该是更新了。我这边仅仅替换掉这一个rec_img_aug.py文件重新使用自己的数据训练应该较之前影响不大吧？还是说也有其他关联更新需要同时做修改？

**Comment by JavieYuan** [comment]
![ques2](https://user-images.githubusercontent.com/84179587/194757932-afff7dac-e905-4e0b-9a5b-b45fe7e8eb89.png)

**Comment by JavieYuan** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> * 运行指令/Command Code：
> * 完整报错/Complete Error Message：
>   ![que](https://user-images.githubusercontent.com/84179587/194743904-70ceabea-e737-44f6-831c-0474f9172569.png)
>   请问关于输入图像32*320这部分，说把图像等比例缩放至3，32，320以及不足320部分补0，关于这部分的源码在哪里呀，好像不在数据增强rec_img_aug里面？？？

宽高比大于10的样本直接丢弃掉？这里源码又在哪？如果要保留宽高比大于10的样本该如何修改？因为无论训练、测试还是最终实际使用场景中都有很多长文本，宽高比是大于10的。

**Comment by ainndejj11** [comment]
> > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > 
> > * 系统环境/System Environment：
> > * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> > * 运行指令/Command Code：
> > * 完整报错/Complete Error Message：
> >   ![que](https://user-images.githubusercontent.com/84179587/194743904-70ceabea-e737-44f6-831c-0474f9172569.png)
> >   请问关于输入图像32*320这部分，说把图像等比例缩放至3，32，320以及不足320部分补0，关于这部分的源码在哪里呀，好像不在数据增强rec_img_aug里面？？？
> 
> 宽高比大于10的样本直接丢弃掉？这里源码又在哪？如果要保留宽高比大于10的样本该如何修改？因为无论训练、测试还是最终实际使用场景中都有很多长文本，宽高比是大于10的。

请问这个问题解决了么？

**Comment by JavieYuan** [comment]
> > > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > > 
> > > * 系统环境/System Environment：
> > > * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> > > * 运行指令/Command Code：
> > > * 完整报错/Complete Error Message：
> > >   ![que](https://user-images.githubusercontent.com/84179587/194743904-70ceabea-e737-44f6-831c-0474f9172569.png)
> > >   请问关于输入图像32*320这部分，说把图像等比例缩放至3，32，320以及不足320部分补0，关于这部分的源码在哪里呀，好像不在数据增强rec_img_aug里面？？？
> > 
> > 
> > 宽高比大于10的样本直接丢弃掉？这里源码又在哪？如果要保留宽高比大于10的样本该如何修改？因为无论训练、测试还是最终实际使用场景中都有很多长文本，宽高比是大于10的。
> 
> 请问这个问题解决了么？

不必纠结这里，宽高比大于10在测试集中也可以成功识别出来。
