### ISSUE TITLE
使用predict_table.py 预测表格在预测表格结构时出现错误

### ISSUE THREAD

**Issue by wonder-hy** [PaddlePaddle/PaddleOCR#7850]
利用 table—genneration 生成的表格数据训练表格结构预测模型 利用如下命令能够输出正确的html结果,但是没有任何bbox的信息
python3.7 table/predict_structure.py \
    --table_model_dir={path/to/inference model} \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --image_dir=docs/table/table.jpg \
    --output=../output/table
本该有bbox坐标的list为空，求大佬解答（BTW使用的xyxy bbox format 会不会跟这个有关系呢）

**Comment by WenmuZhou** [comment]
这个生成的应该是4个点的，需要使用xyxyxyxy
