### ISSUE TITLE
SER inference results.txt

### ISSUE THREAD

**Issue by karthikloganlogan** [PaddlePaddle/PaddleOCR#7853]
I have used the SER and got the image and .txt file for SER. But i coudnt understand the key  value pair structure in the .txt file nor the image. It contains Both question and answers but i dont know the mappings of which question to what answer.Kindly clarify how the mapping is related to transcription, question and answer

**Comment by andyjpaddle** [comment]
you can refer to this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README.md

**Comment by karthikloganlogan** [comment]
I already had a glance with the provided document. But i didnt get any information related to mappings of which answers to which question in SER.  I am not training a model. Just using the pretrained model .

**Comment by andyjpaddle** [comment]
you should use RE to get the relation between question and answer
