### ISSUE TITLE
paddleserving 使用阿拉伯文识别模型得出还是中文结果

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#7854]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：paddleserving
- 运行指令/Command Code：python web_service.py --config=<configfile>
- 完整报错/Complete Error Message：
使用官方下载的阿拉伯文det和rec模型， 在paddleocr中运行可以得到阿拉伯文识别结果，模型经过paddle_serving_client.convert转换后在paddleserving中使用，识别结果是中文。

**Comment by andyjpaddle** [comment]
更换模型需要同步改一下字典 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/web_service.py#L72

**Comment by ericosmic** [comment]
> 更换模型需要同步改一下字典 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/web_service.py#L72

那其他文字的字典哪里找啊

**Comment by andyjpaddle** [comment]
找到模型对应的配置文件，配置文件里面有写

**Comment by ericosmic** [comment]
> 找到模型对应的配置文件，配置文件里面有写
谢谢 问题已解决
