### ISSUE TITLE
rec 预处理归一化问题

### ISSUE THREAD

**Issue by woshipp07** [PaddlePaddle/PaddleOCR#7860]
![0da3beb19c83766eb4de025eef3ce51](https://user-images.githubusercontent.com/11566434/194809647-7584e70d-b524-4936-a080-5c6c095f73bb.png)
请问红色框出来部分归一化部分 为何你们提供的android端代码没有做这个动作

**Comment by WenmuZhou** [comment]
这里有做归一化 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/android_demo/app/src/main/cpp/ocr_ppredictor.cpp#L212

**Comment by woshipp07** [comment]
好的，谢谢
