### ISSUE TITLE
可否发布pypy版本？

### ISSUE THREAD

**Issue by RussiaVk** [PaddlePaddle/PaddleOCR#7868]

**Comment by andyjpaddle** [comment]
暂无计划

**Comment by andyjpaddle** [comment]
可以使用whl包

**Comment by RussiaVk** [comment]
> 可以使用whl包

请问地址在哪？
https://www.paddlepaddle.org.cn
只有cpython版本

**Comment by andyjpaddle** [comment]
你是指ocr吗还是paddle包？

**Comment by RussiaVk** [comment]
> 你是指ocr吗还是paddle包？

ocr的gpu版本

**Comment by andyjpaddle** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#12

**Comment by andyjpaddle** [comment]
安装最新版2.3.2即可，参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html

**Comment by RussiaVk** [comment]
> 安装最新版2.3.2即可，参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html

没用，pypy的pip找不到包，源码构建过，无法使用报错[](https://github.com/PaddlePaddle/Paddle/issues/45947)

**Comment by andyjpaddle** [comment]
或者直接下载whl包安装 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release

**Comment by RussiaVk** [comment]
> 或者直接下载whl包安装 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release

老哥，whl只有cpython的，pypy安装不了！

**Comment by andyjpaddle** [comment]
官方给的安装方式就只有官网这些了，关于paddle安装包需求的问题，可以到paddle主repo下面提问哈，这边只负责解决ocr相关的问题

**Comment by RussiaVk** [comment]
> 官方给的安装方式就只有官网这些了，关于paddle安装包需求的问题，可以到paddle主repo下面提问哈，这边只负责解决ocr相关的问题

好的，麻烦了。哎，看来无解了。
