### ISSUE TITLE
关于识别率的问题

### ISSUE THREAD

**Issue by zymize** [PaddlePaddle/PaddleOCR#787]
您好，初学ocr，有一个问题想要请教您，有什么理解有误的请见谅
1.请问每一张预测的结果后面都有在字典中的概率，但是拿单张图片来说如何计算识别错误率或者正确率，代码中是否有呢？
2.如果是测试很多张图片，我应该怎么去计算整体的文字正确或者错误识别率呢？是否有测试集对应的正确文本呢？
或者代码中哪里是整体识别率的计算呢？

**Comment by zymize** [comment]
我看评论中也有人提这个问题，但是没有看到答复，期待您的回复

**Comment by LDOUBLEV** [comment]
1.  单张图的准确度 = 预测正确文本框数量 / 图总本文框数量；
2. 多张图计算识别的准确率代码：https://github.com/PaddlePaddle/PaddleOCR/blob/89ea21bf9e091979d0d04e0f9e1350c91eb2accb/tools/eval_utils/eval_rec_utils.py#L114

**Comment by zymize** [comment]
@ LDOUBLEV  非常感谢您的回复  一直以为识别率是预测正确的文本字数/图文本的字数，没有想到是文本框
可是不管是哪一个，我们在测试自己的图像时，是否需要自己去数图中文本框或者文本的个数呢？
还有每个文本框中识别正确字符正确的个数也是不一样的。在您计算准确率时，每张图片中总文本框个数是否是已经标记好了的呢？项目里是否有这样已经标记好的测试集了呢？

**Comment by tink2123** [comment]
> 每张图片中总文本框个数是否是已经标记好了的呢？

对于检测+识别串联来说，总个数是根据整幅图像的 gt_label 计算出来的，目前项目里没有提供标记好的测试集
对于单独的文本识别来说，文本行的概率是这样计算的：
https://github.com/PaddlePaddle/PaddleOCR/blob/5fb3c419c980a112cb69b87019d18157926edc41/tools/infer_rec.py#L129

**Comment by tink2123** [comment]
> 项目里是否有这样已经标记好的测试集了呢？

可以参考有lsvt的label：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/datasets.md#ICDAR2017-RCTW-17
