### ISSUE TITLE
预训练模型不对

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleOCR#7871]
您好，我在使用最新开源的ppocrv3的中英文识别动态图，发现识别不正确，但是用提供的推理静态图可以推理正确，麻烦帮忙确认并上传正确的动态图模型，我想用来做finetune，谢谢
<img width="854" alt="image" src="https://user-images.githubusercontent.com/728405/195011110-6458637c-daf7-43b6-bec5-2e656ceae914.png">

**Comment by shuizhonghaitong** [comment]
我应该也是遇到了类似的问题。用相同的数据集，分别用ppocrv2和ppocrv3来finetune，都加载了各自的预训练模型，可以看到在最开始的step里，ppocrv2 acc 是0.29，而ppocrv3 acc是0。下面的两张图分别是v2和v3的。
![image](https://user-images.githubusercontent.com/14170291/195310618-e2742ca2-d231-4fe1-a51b-2d253de8401c.png)
![image](https://user-images.githubusercontent.com/14170291/195310694-3b661ac4-4102-4fb2-8108-e2b67aac9c3d.png)
