### ISSUE TITLE
PPOCRV3文本识别精度低

### ISSUE THREAD

**Issue by engrwuang** [PaddlePaddle/PaddleOCR#7874]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：release/2.6  
- PaddleOCR： 问题相关组件/Related components：ppocr_v3_rec
- 运行指令/Command Code：
- python tools/infer/predict_system.py --image_dir="******" --det_model_dir="./output/save_det_inference/" --rec_model_dir="./output/save_rec_inference/Student" --rec_image_shape="3, 48, 320" --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt"
- 完整报错/Complete Error Message：

运用PPOCRV3并官方提供的识别模型，识别精度较低，基本无法使用。
如下：
![image](https://user-images.githubusercontent.com/51011462/195017009-195a3cd7-563c-4d96-b6c7-3614057d7a63.png)
2019-02-19
![image](https://user-images.githubusercontent.com/51011462/195017062-74652791-32d6-4c47-9566-8217bd4afea4.png)
2019-82-19
![image](https://user-images.githubusercontent.com/51011462/195018668-5c7f0f6c-6200-4784-8a52-60200a957737.png)
轻型平板货车
![image](https://user-images.githubusercontent.com/51011462/195018694-d028b623-fcc8-49b5-93a2-77146434cf15.png)
轻型平板贷车

有没有什么精度更高的推理模型，或者有什么其他的提高精度的解决方案？

**Comment by tink2123** [comment]
如果推理图片只有文本行内容的话，不需要使用检测模型，会影响文本识别效果，建议尝试如下命令：
```
python tools/infer/predict_rec.py --image_dir="******" --rec_model_dir="./output/save_rec_inference/Student" --rec_image_shape="3, 48, 320" --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt"
```

**Comment by engrwuang** [comment]
> 如果推理图片只有文本行内容的话，不需要使用检测模型，会影响文本识别效果，建议尝试如下命令：
> 
> ```
> python tools/infer/predict_rec.py --image_dir="******" --rec_model_dir="./output/save_rec_inference/Student" --rec_image_shape="3, 48, 320" --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt"
> ```

我这边做的不只是文本行内容，需要检测+识别模型，所以想咨询其他提高检测精度的方案。

**Comment by 746891300-org** [comment]
这个中间带线的0确实识别效果很差，容易识别成6、8、9，车辆相关的证件上大部分是这样的0出现，如驾驶证/行驶证/车辆登记证等

**Comment by guishilike** [comment]
同问，驾驶证/行驶证/车辆登记证识别的精度很差，有什么解决方案吗？@tink2123
![image](https://user-images.githubusercontent.com/51023060/195342241-634fdba7-b823-4bf5-b6c8-7ddab9c4b5fa.png)

**Comment by engrwuang** [comment]
> 

请问这种情况有好一些的解决方案吗？

**Comment by engrwuang** [comment]
> 



> 这个中间带线的0确实识别效果很差，容易识别成6、8、9，车辆相关的证件上大部分是这样的0出现，如驾驶证/行驶证/车辆登记证等

请问这种情况有好一些的解决方案吗？

**Comment by tink2123** [comment]
> 同问，驾驶证/行驶证/车辆登记证识别的精度很差，有什么解决方案吗？@tink2123 ![image](https://user-images.githubusercontent.com/51023060/195342241-634fdba7-b823-4bf5-b6c8-7ddab9c4b5fa.png)

训练数据中缺少这种数据，可以使用 PaddleOCRLabel  标注一批数据，使用小数据集finetune一下，应该可以改善。

**Comment by guishilike** [comment]
是的，finetune后效果好了一些
