### ISSUE TITLE
Bi-lingual OCR Model Training

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#7876]
I'm trying to Train the Recognition model for Two Languages English and a Non-Latin Language.
I can see that it worked with Chinese with a huge number of characters.
However I'm facing a problem with Language Confusion, Some times some of the words in the dataset are classified in English instead of the non-latin language and the number of times that happen isn't low.

So any tips on how to optimize the Training Dataset to get an optimal performance for the two languages?

Regards,

**Comment by tink2123** [comment]
In our testing English and non-Latin languages ​​can be trained at the same time. It is recommended to check the training data for the reasons for the above errors, whether the categories are very uneven, or there are errors in the labeling.

In addition, Can you report a few badcases?

**Comment by bely66** [comment]
For example in Arabic,
For some basic fonts it works well, however in fonts like Cairo the ratio of language confusion is heightened.
I'll try to increase the volume of the confused fonts, that sounds like a good strategy
Thanks
