### ISSUE TITLE
SRN的BUG

### ISSUE THREAD

**Issue by lovelynight** [PaddlePaddle/PaddleOCR#788]
训练过程中发现在验证集上的准确率为0，通过debug发现，网络输出的output重的preds这个，应该是一个【batchsize乘以max_text_length，1】的张量，但是在实际有一定可能出现【batchsize乘以max_text_length，char_num】的张量，这里的char_num是字典的大小，这个张量里面是概率，也就是说网络可能最后那一步topk的计算没有，同一个代码跑多次，有时正确有时错误，这是因为什么呢？

**Comment by tink2123** [comment]
大概训了多久？训练开始时验证集的准确率为0很正常

**Comment by lovelynight** [comment]
请看一下后面的说法，我使用infe_rec.py载入训练好的网络，对于同一个图片同一个模型，多次运行，有时有结果且正确，有时会报错，报错的原因就是我上面提到的原因导致的。网络最后那一步topk的计算没有计算，输出出来的是概率而不是概率最大的位置。

**Comment by lovelynight** [comment]
具体的报错信息可以看一下，然后重点是重复运行，有时对有时错

 score = np.mean(probs[valid_ind, ind[valid_ind]])
IndexError: index 30 is out of bounds for axis 0 with size 30

30是因为max_text_length是30

**Comment by tink2123** [comment]
![image](https://user-images.githubusercontent.com/31891223/93857421-2071d080-fced-11ea-87d2-25604c0a5c99.png)

有点奇怪，我这边连续运行3次得到的都是一致的预测结果，请问您运行的命令是？另外方便发一下你的测试图片吗

**Comment by lovelynight** [comment]
python3 tools/infer_rec.py -c configs/rec/123.yml -o Global.checkpoints=123/best_accuracy Global.infer_img=doc/123
命令大致是这样，给你一个图片吧
<img width="472" alt="截屏2020-09-19 下午10 32 26" src="https://user-images.githubusercontent.com/21274914/93857861-d76e4c00-fced-11ea-837d-08cf33af67f5.png">
我理解的是框架的bug，topk没有计算。这个问题很奇怪，我训练了7次，只有一次出现了这个问题，我才去debug的。

**Comment by tink2123** [comment]
好的，收到反馈，我们先把问题记录下来。由于我们只有英文的权重，加载英文权重预测您这张图多次，也没有复现问题，我们尝试训练一个和您一样配置的中文模型吧，方便说下您修改了哪些配置和代码吗？

**Comment by lovelynight** [comment]
image_shape: [1, 32, 320]
  character_type: ch
  max_text_length: 30

**Comment by tink2123** [comment]
好的～ image shape的高度不建议设置为32，PVAM模块需要获取2D信息来处理图片，高度为32的话，经过backbone降采样高度就为1了。我们做一下中文的尝试，有结果之后给您反馈

**Comment by lovelynight** [comment]
是的，我发现了，32的效果很差，不如64的。还有一个问题就是，我发现srn这个算法对于长文本和短文本，预测的效果差很多，之前也探讨过这个问题，一开始以为是image_szie是64，256对长文本会过度压缩，但是调整后，并没有好太多

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
