### ISSUE TITLE
整图角度分类

### ISSUE THREAD

**Issue by mingming0611** [PaddlePaddle/PaddleOCR#7885]
对于像印章这样的整图，如何对其识别角度进行旋转摆正，官方的文字方向分类器只能界别0度、180度，对于多角度整图（且包含弯曲文本）的该如何旋转矫正，有什么好的方法吗。
![177_0](https://user-images.githubusercontent.com/113701415/195103917-1d9080bb-61bc-4300-a3c2-d53436c0a06c.jpg)

**Comment by BeyondYourself** [comment]
多角度没办法用深度学习调整吧？

**Comment by drenched9** [comment]
如果是要识别印章，直接看[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md](url)就好了

**Comment by cqray1990** [comment]
@mingming0611 请问需要矫正？

**Comment by yangy996** [comment]
east文本检测方法里有个角度处理的，你可以参考那个改一下网络
