### ISSUE TITLE
Decreasing Input Shape for Detection

### ISSUE THREAD

**Issue by 7ZFG1** [PaddlePaddle/PaddleOCR#7886]
Hello Everyone,

I want to decrease input image shape before entering the detection model (mobilenet_v3) because my dataset has small-sized images. For this purpose, I changed the parameters as det_limit_side_len = 224 and det_limit_type = min. But the performance became bad. Anyone can help?

Thank you!

**Comment by thangnm99** [comment]
I think it's because the trained model is trained on a larger scale image. You can see the input size in the config file of the detection model. I do not remember it exactly, but it's around 960x1280. Fine tune the model if you have enough data may help

**Comment by 7ZFG1** [comment]
In the config file there is parameters which is DetResizeForTest in Eval part. If I use this parameters for resizing will it work?
