### ISSUE TITLE
Ubuntu系统下开启mkldnn使用CPU推理结果为乱码

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleOCR#7887]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：Paddle：2.3.2 ； PaddleOCR： 2.4；  问题相关组件/Related components：mkldnn

在windows10系统下开启mkldnn识别结果正常，但是在Ubuntu系统下开启mkldnn识别结果为乱码，请问如何解决？

**Comment by WenmuZhou** [comment]
请问是运行的哪个命令呢

**Comment by KyleWang-Hunter** [comment]
> 请问是运行的哪个命令呢
两种方式都是乱码
方式一：
ocr = PaddleOCR(use_angle_cls=True,
                lang="ch",
                enable_mkldnn=True,
                use_gpu=False)
ocr.ocr("image_path")
方式二：
python tools/infer/predict_system.py

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/195559148-23a37a7a-c44c-4dc0-b493-f602196dfb78.png)
我这边正常哈，你可以看一下你的终端是否支持utf8

**Comment by KyleWang-Hunter** [comment]
> ![image](https://user-images.githubusercontent.com/12406017/195559148-23a37a7a-c44c-4dc0-b493-f602196dfb78.png) 我这边正常哈，你可以看一下你的终端是否支持utf8
好的，感谢

**Comment by KyleWang-Hunter** [comment]
> ![image](https://user-images.githubusercontent.com/12406017/195559148-23a37a7a-c44c-4dc0-b493-f602196dfb78.png) 我这边正常哈，你可以看一下你的终端是否支持utf8

好的，感谢
