### ISSUE TITLE
different result on training model and inference model on detection

### ISSUE THREAD

**Issue by rubensanchezrivero** [PaddlePaddle/PaddleOCR#7888]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 11 x64
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.01 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
I fine tuned the detection model of ppocrv3, and the results of the trained model are just as expected, but after exporting it with  
`python tools/export_model.py -c output/ch_PP-OCR_v3_det/config.yml -o Global.pretrained_model="./output/ch_PP-OCR_v3_det/best_accuracy" Global.save_inference_dir="./output/ch_PP-OCR_v3_det_inference/"` the inference resulting model results are the same of the model before the training, could you please provide some insight about this issue please

**Comment by rubensanchezrivero** [comment]
dont worry i solved it using the image_shape property in the config.yml as well as modifying the code for the infer_det.py, this must be a parameter for the .py i think. ill close it because the main problem is solved

**Comment by kuopching** [comment]
Hi, I've got the same problem ... Result of inference model is worst than training model. Can you give me a hint, how to solve this?
