### ISSUE TITLE
文档能不能写好清楚些，像其它产品一样，我用PaddleOCRLabel标注的数据我都不知道用哪个模型来训练

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#7890]
文档能不能写好清楚些，像其它产品一样，我用PaddleOCRLabel标注的数据我都不知道用哪个模型来训练。

# 已知训练方式一：
![3](https://user-images.githubusercontent.com/6648329/195236322-6cc4aac0-fea3-4cbc-bc7d-8c49c1af185d.png)
 这个用的是： python tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=./weight/en_PP-OCRv3_rec_train/best_accuracy  训练我知道， 那下面这种用哪个训练，也是一样的？

# 方式二的数据样式怎么办？：
![1](https://user-images.githubusercontent.com/6648329/195236417-59c5a83e-e262-4f88-952c-86e0cd2f8dfa.png)
![2](https://user-images.githubusercontent.com/6648329/195236437-071ae6e1-5083-4584-a558-e653c6bed05d.png)
这样标注的模型用哪个模型来训练？ rec 还是kie?  ??????????????????????

还是也是用上面的方式训练，但是看图片完全不一样，方式一是切了图的， 方式二没有切图

**Comment by drenched9** [comment]
PaddleOCR虽然叫做图像文字识别，但是实际是分两步的。一般都是先进行文字定位再进行文字识别。你这样标注肯定是用端到端的方式进行训练了。端到端训练不是有介绍吗。。。

**Comment by gg22mm** [comment]
是用 “ det ” 研究出来了
