### ISSUE TITLE
弯曲文本识别训练问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#7896]
![image](https://user-images.githubusercontent.com/57654726/195282807-b4446041-ff73-44fd-80ba-a89e4b3c62d6.png)
![image](https://user-images.githubusercontent.com/57654726/195282981-6491d6fc-1655-46a6-8719-bfd007fcf92c.png)
是需要修改，paddlepaddle不支持uint8格式的数据进行计算？

**Comment by LDOUBLEV** [comment]
训练需要的输入是fp32类型的，而不是uint8类型的；
你运行的是什么命令

**Comment by xialei2821212670** [comment]
> 需要训练的输入是 fp32 类型的，而不是 uint8 类型的； 你运行的是什么命令

python3 tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml

**Comment by xialei2821212670** [comment]
> 需要训练的输入是 fp32 类型的，而不是 uint8 类型的； 你运行的是什么命令

![image](https://user-images.githubusercontent.com/57654726/195492093-83d3b4c2-5ca5-4b26-8cf9-26c31ac0634a.png)
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/9770200/train.log)
，数据集使用的是aistudio上面的印章数据

**Comment by KyleWang-Hunter** [comment]
> > 需要训练的输入是 fp32 类型的，而不是 uint8 类型的； 你运行的是什么命令
> 
> ![image](https://user-images.githubusercontent.com/57654726/195492093-83d3b4c2-5ca5-4b26-8cf9-26c31ac0634a.png) [train.log](https://github.com/PaddlePaddle/PaddleOCR/files/9770200/train.log) ，数据集使用的是aistudio上面的印章数据

老哥，模型训练好了能分享下吗？

**Comment by phb-shiyige-fw** [comment]
> > 需要训练的输入是 fp32 类型的，而不是 uint8 类型的； 你运行的是什么命令
> 
> ![image](https://user-images.githubusercontent.com/57654726/195492093-83d3b4c2-5ca5-4b26-8cf9-26c31ac0634a.png) [train.log](https://github.com/PaddlePaddle/PaddleOCR/files/9770200/train.log) ，数据集使用的是aistudio上面的印章数据

兄弟 你好 可以分享一下转换后的标签么 你那个应该是识别的标签文件吧

**Comment by xialei2821212670** [comment]
弯曲文本文字检测DB++，已解决

**Comment by xialei2821212670** [comment]
> > > 训练的输入是 fp32 类型的，而不是 uint8 类型的；你运行什么命令
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/57654726/195492093-83d3b4c2-5ca5-4b26-8cf9-26c31ac0634a.png) [train.log](https://github.com/PaddlePaddle/PaddleOCR/files/9770200/train.log)，数据集使用的是aistudio的印章数据
> 
> 兄弟你好可以分享一下转换后的标签么 你那应该是识别的标签文件吧

不是识别的，就是文字检测。文字识别不是还要切割文字内容，构建新的数据集
