### ISSUE TITLE
CRNN对于符号很贴近文字的漏识别

### ISSUE THREAD

**Issue by wzgwy** [PaddlePaddle/PaddleOCR#7901]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
像这类图片，小数点和数字靠的很近

**Comment by WenmuZhou** [comment]
方便提供一下图片吗

**Comment by wzgwy** [comment]
![企业微信截图_16655659466990](https://user-images.githubusercontent.com/53591067/195749954-4c1e2fe3-8f89-4fb1-b029-9e1206477ebf.png)

**Comment by wzgwy** [comment]
上面的1.6和2.0会被识别成16和20，漏掉小数点
