### ISSUE TITLE
申威CPU+UOS20编译paddle报错

### ISSUE THREAD

**Issue by kaaier** [PaddlePaddle/PaddleOCR#7902]
- 系统环境申威CPU+UOS20
命令： cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MKL=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=ON -DREFERENCE_CBLAS_ROOT=${CBLAS_ROOT} -DWITH_CRYPTO=OFF -DWITH_XBYAK=OFF -DWITH_SW=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"
cmake、g++版本正常
按照官方的申威CPU编译过程中，遇到报错，请问是什么原因，已采用采用blas+cblas。报错如下，：

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
EXP_CUDA_MODULE_LOADING_LAZY only works with GPU
-- CXX compiler: /usr/bin/c++, version: GNU 8.3.0
-- C compiler: /usr/bin/cc, version: GNU 8.3.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.20.1")
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
CMake Warning at CMakeLists.txt:380 (message):
  Disable NCCL when compiling without GPU.  Force WITH_NCCL=OFF.

CMake Warning at CMakeLists.txt:459 (message):
  Disable RCCL when compiling without ROCM.  Force WITH_RCCL=OFF.

**Comment by WenmuZhou** [comment]
这个可以在paddle的issue提问看看

**Comment by kaaier** [comment]
> 这个可以在paddle的issue提问看看

您好，想咨询下，Paddle编译成功可推理，是不是PaddleOCR的推理就没问题？

**Comment by kaaier** [comment]
> 这个可以在paddle的issue提问看看

您好，想咨询下，Paddle编译成功可推理，是不是PaddleOCR的推理就没问题？

**Comment by WenmuZhou** [comment]
理论上是这样
