### ISSUE TITLE
KIE模型训练

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7903]
你好  KIE训练会自动下载两个模型 
、我想知道 如果训练自己的数据集 这两个模型我是否需要变更，以及变更时 是否时修改这里
![image](https://user-images.githubusercontent.com/38007233/195316000-e7569be3-ea5f-41a9-aed2-2c383cb46bf5.png)

**Comment by WenmuZhou** [comment]
需要，修改这里的value就行了

**Comment by littletomatodonkey** [comment]
你好，麻烦安装下这里的paddlenlp试下：https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/ppstructure/kie/requirements.txt#L7
