### ISSUE TITLE
PPOCRLabelv2导出识别结果不对

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleOCR#7904]
您好，我在使用PPOCRLabelv2进行标注的时候，已经标注了100多张并确认了，但是点击"导出识别结果"后，只有6-7个crop被导出了，请问如何解决
下图是fileState.txt文件
<img width="433" alt="image" src="https://user-images.githubusercontent.com/728405/195330173-d58d399e-be07-47ac-851c-dce9109be856.png">

下图是rec_gt.txt文件
<img width="346" alt="image" src="https://user-images.githubusercontent.com/728405/195330210-8c7b5773-92dd-4bfd-97f3-9e62e131ba2c.png">

**Comment by Evezerest** [comment]
导出的时候命令行或者软件有什么报错吗？

**Comment by Kelsey-Zhao** [comment]
> 导出的时候命令行或者软件有什么报错吗？

遇到了同样的问题，没有任何报错，目测是如果是“自动标注”的文本框就可以被成功导出，如果是自己手动标注的文本框就没办法被导出。
这个目前有什么解决办法吗？

**Comment by cx-11-c** [comment]
> > 导出的时候命令行或者软件有什么报错吗？
> 
> 遇到了同样的问题，没有任何报错，目测是如果是“自动标注”的文本框就可以被成功导出，如果是自己手动标注的文本框就没办法被导出。 这个目前有什么解决办法吗？

同问
