### ISSUE TITLE
KIE训练自己的数据集时出错

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7906]
![image](https://user-images.githubusercontent.com/38007233/195336974-98c5aad6-e1bd-49a9-9343-b78c2370b1a5.png)
我在训练自己的数据集时出错 请问这个错误时啥意思 我的类别是18个 
![image](https://user-images.githubusercontent.com/38007233/195337223-9d7359a9-2424-4de8-b5bb-e1f28cc154c9.png)
按照说明应该写35 可是为啥出错

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/ppstructure/kie/requirements.txt#L7

安装下这里的paddlenlp试下

**Comment by husiluanxiang** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/ppstructure/kie/requirements.txt#L7
> 
> 安装下这里的paddlenlp试下

你好我已经重新安装了这个库，可是还是报一样的错 是否还有哪里需要修改

**Comment by husiluanxiang** [comment]
你好 请问这个你们有试过除了4类以外的类别吗？按照文档里面写的2k-1，按照这个报错只有四类才会变成奇数可以被28672整除。

**Comment by husiluanxiang** [comment]
而且我试了 我只要标注的是4类 训练就能正常跑起来，我觉得这个是不是没有做适配还是什么原因导致的，如果我要能适配自己的种类数应该怎么修改

**Comment by husiluanxiang** [comment]
![image](https://user-images.githubusercontent.com/38007233/196926641-b4d7996e-3d4d-4fa0-b1de-bccafe706484.png)
这里算loss的时候是尺度是对不上的，文件是![image](https://user-images.githubusercontent.com/38007233/196926883-18a91d37-6a7d-4c45-ba17-e2617d417813.png)

**Comment by YmanChris** [comment]
我遇到了同样的问题，求官方解答
