### ISSUE TITLE
ocr小白,想训练一个识别竖排英文的模型,但用生成的正常竖排文字图片去训练,acc很低,loss也不收敛

### ISSUE THREAD

**Issue by Like2021** [PaddlePaddle/PaddleOCR#7908]
近期想训练一个能够识别竖排英文与数字的模型,横排数据集训练好的模型效果很差；

除了尝试用正常的竖排文字图片训练,我还用倒字横排文字的图片去训练,训练效果很好,很快收敛;

![AAHR_32816](https://user-images.githubusercontent.com/95627417/195538586-79f3965e-2a01-4c13-b617-e4cfdcfdd4b2.jpg)

但是推理正常竖排文字,效果很差

我应该用怎么样的数据集去训练呢

**Comment by tink2123** [comment]
正常生成竖排文本，训练时逆时针旋转90度作为训练集(上述图片是正确的)， 推理时对长宽比进行判断，大于1.5认为是竖排文本，先逆时针旋转90度再预测。

预测逻辑参考：https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/tools/infer/utility.py#L598-L599

**Comment by Like2021** [comment]
> 正常生成竖排文本，训练时逆时针旋转90度作为训练集（上述图片是针的），推理时对长宽比进行判断，大于1.5认为是竖排文本，先逆时针旋转90度再预测。
> 
> 预测逻辑参考：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/tools/infer/utility.py#L598-L599

got it! 非常感谢
