### ISSUE TITLE
为什么内存搬运的时间会这么久？

### ISSUE THREAD

**Issue by zpy78987** [PaddlePaddle/PaddleOCR#7913]
如图，我对predict_rec.py中的模型推理部分代码进行打点，发现推理只需要15ms左右，但是加上拷贝就达到了33ms，请问这是否正常？（架构：鲲鹏arm）
![image](https://user-images.githubusercontent.com/50124894/195479992-16ab989a-4f82-4b0e-b0ba-0482d3ce82c8.png)
![image](https://user-images.githubusercontent.com/50124894/195480189-cac74b57-be08-4f87-a155-15a26aeb1a82.png)

**Comment by littletomatodonkey** [comment]
他是异步计算的，你拷贝的过程也包含了计算的时间
