### ISSUE TITLE
关于使用paddleocr库预测时的一些问题

### ISSUE THREAD

**Issue by xychen1015** [PaddlePaddle/PaddleOCR#7914]
1. 用于预测的图片为url格式，然后每次预估时都会把图片拉到本地，请问这个可以关闭吗？
2. 如何关闭预测时的进度条显示
![image](https://user-images.githubusercontent.com/52397468/195484580-d572c4f4-4521-47f6-8512-d9306e896801.png)
3. 测试集中数据全部预测完毕后，为什么会出现这样的fatal
![image](https://user-images.githubusercontent.com/52397468/195752562-815e85c0-c8f7-48f3-aee8-5ce32b9540d1.png)

补充版本信息
Python3.6
paddleocr                         2.6.0.1
paddlepaddle                      2.0.0rc1

**Comment by WenmuZhou** [comment]
不可以哈，图片必须下载到本地才能读取

**Comment by andyjpaddle** [comment]
更新一下paddle版本吧，推荐2.3.2

**Comment by xychen1015** [comment]
> 更新一下paddle版本吧，推荐2.3.2
我尝试把paddle版本升级到2.3.2，会出现缺少系统文件，这是为啥呢？
![image](https://user-images.githubusercontent.com/52397468/195796160-3fe67f35-69f3-46cd-995f-f4fd9b65fd7b.png)

版本信息
![image](https://user-images.githubusercontent.com/52397468/195796361-75087f6f-a85b-49f1-8b5e-ba96753fd6b6.png)

**Comment by andyjpaddle** [comment]
应该是paddle安装有问题或者环境问题，先看一下paddle安装成功与否 
```
import paddle
paddle.utils.run_check()
```

**Comment by xychen1015** [comment]
> 应该是paddle安装有问题或者环境问题，先看一下paddle安装成功与否
> 
> ```
> import paddle
> paddle.utils.run_check()
> ```

感觉是环境的问题，升级后import paddle报一样的错，但是2.0.0rc1版本就没问题。这类大佬有办法解决吗？方便hi上指教一下嘛(*ﾟ∀ﾟ*)（chenxinyu03）

**Comment by andyjpaddle** [comment]
可以去paddle的repo下面看看有没有相关issue

**Comment by xychen1015** [comment]
> 可以去paddle的repo下面看看有没有相关issue

你好，我刚刚又研究了一下，貌似是paddleocr默认使用gpu来预测，但是我安装的paddle版本是cpu。所以想问下，除了在这里设置参数为false外，还有哪里需要关闭paddleocr使用gpu预测呢
![image](https://user-images.githubusercontent.com/52397468/195844208-cb87b5bd-4f4d-4643-a97e-9eff54d01b9c.png)

**Comment by WenmuZhou** [comment]
应该就没有了
