### ISSUE TITLE
ppocrv3开源的预训练识别模型不对

### ISSUE THREAD

**Issue by shuizhonghaitong** [PaddlePaddle/PaddleOCR#7915]
你好，我使用相同的数据集，分别用ppocrv2和ppocrv3来finetune，都加载了各自的预训练模型，可以看到在最开始的step里，ppocrv2 acc 是0.29，而ppocrv3 acc是0。下面的两张图分别是v2和v3的。
![image](https://user-images.githubusercontent.com/14170291/195490471-b7164397-110a-4554-999c-042bb8d73ba4.png)
![image](https://user-images.githubusercontent.com/14170291/195490492-cd3e4676-3b1a-4db2-9bc1-991c2539de75.png)
但是讲道理v3加载预训练模型之后，在最初的step里acc应该超过v2的才对。所以怀疑是不是v3开源的预训练模型有问题，麻烦check一下，谢谢！

**Comment by littletomatodonkey** [comment]
可以多训一段时间看看，v3的模型包含gtc模块，某些场景里是会出现初始acc为0的情况

**Comment by shuizhonghaitong** [comment]
我尝试训练到100个epoch，确实acc会逐渐上升。但我还有两个问题希望请教一下。1、在训练的过程中，我发现在相同的epoch下，v3的效果没有v2好，无论是train acc还是dev acc，这是正常的嘛？v3的效果要超过v2的话是不是v3需要用的epoch要比v2多？2、如果几十万的训练数据，对于v2和v3，各自大约需要跑多少个epoch呢？

**Comment by llwowowowoll** [comment]
ppocrv3开源的预训练识别模型，我试着效果也不好
