### ISSUE TITLE
iOS Demo模型更新到OCRv3出现崩溃

### ISSUE THREAD

**Issue by yinqinggong** [PaddlePaddle/PaddleOCR#7918]
iOS Demo更新到V3模型，检测模型ch_PP-OCRv3_det_slim_infer.nb是OK的，但是识别模型(ch_PP-OCRv3_rec_slim_infer.nb)运行出现崩溃，位置在rec_process.cc文件的 predictor_->Run();处。
rec_image_shape{3, 32, 320}修改为rec_image_shape{3, 48, 320};后也是如此。
问题同`[6523](https://github.com/PaddlePaddle/PaddleOCR/issues/6523)`

**Comment by yinqinggong** [comment]
![image](https://user-images.githubusercontent.com/9996124/195540872-76e4f5ee-a31d-4815-a2da-1e3087529466.png)

**Comment by WenmuZhou** [comment]
你好，ios模型目前是paddlelite维护的，建议在那边问一下看看，地址在这https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/develop/ocr/ios/ppocr_demo/ppocr_demo/README.md

**Comment by yinqinggong** [comment]
> 图片里，你的输入h为啥是43不是48，有更改过代码吗
![QQ截图20221107150311](https://user-images.githubusercontent.com/9996124/200246143-62df7464-3ed6-47be-8b5c-43126201b3b8.jpg)
你好，没有更改代码，43应该是检测到的文本框的高度，如上图

**Comment by zhangjunhst** [comment]
你好，请问这个问题有解决吗？ 我也遇到相同的问题修改，rec_image_shape修改前后都不行

**Comment by zhangjunhst** [comment]
测试过程中发现包含中文的就会崩溃，纯数字不会但返回是序列对应的汉字。

**Comment by wuhenzhizao** [comment]
@yinqinggong 问题最后解决了么
