### ISSUE TITLE
Tutorials on how to set up LMDBDataSet

### ISSUE THREAD

**Issue by mazatov** [PaddlePaddle/PaddleOCR#7919]
Trying to train my own model with some of the config files that require LMDBDataSet. I have successfully set up SimpleDataSet, but do not know how to set up LMDBDataSet. Any tutorials on how to set up your data in LMDB format? Or maybe a conversion file?

Thanks!

**Comment by littletomatodonkey** [comment]
You do not need to use lmdbdataset, simpledataset is enough~
