### ISSUE TITLE
请问DB中如何对样本进行”模糊“增强呢？

### ISSUE THREAD

**Issue by jiangqianxin111** [PaddlePaddle/PaddleOCR#7922]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
你好，可以参考这里：https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml#L77
