### ISSUE TITLE
onnx support for ABInet

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleOCR#7923]
ABInet has achieved the best performance in [the list](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_overview_en.md). So I want to deploy it as onnx. But it seems there are some special operators which paddle2onnx not support, including bitwise_and,diag_v2. How can I export it as onnx now? Or when will those operators be supported?

**Comment by firekeepers** [comment]
请问您解决了该问题吗
