### ISSUE TITLE
Transfer Learning with Paddle?

### ISSUE THREAD

**Issue by mazatov** [PaddlePaddle/PaddleOCR#7924]
Is there a way to do transfer learning with Paddle? I have a smallish dataset ( ~1000-10000 images) with only 10-15 possible answers. I'd like to do a version of transfer learning on `PP-OCRv3` so it learns that only one of these 10-15 answers is possible. 

Is there a way to freeze part of the network to do that?

**Comment by mazatov** [comment]
Or maybe freeze layers of the backbone at least somehow?

**Comment by littletomatodonkey** [comment]
currently paddleocr does not support freezing backbone, but you can fix the code mannually, such as here.

https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/ppocr/modeling/architectures/distillation_model.py#L50

**Comment by mazatov** [comment]
@littletomatodonkey , thanks for the tip. In my case I'm thinking to do transfer learning on PP-OCRV3. So I'm thinking to freeze the backbone of PP-OCRv3, MobileNetV1Enhance. 

Would something like this `[here ](https://github.com/PaddlePaddle/PaddleOCR/blob/558b2a719efc8761539649ed676ff405401a90a7/ppocr/modeling/backbones/rec_mv1_enhance.py#L221)` freeze the net? 

```
        for param in self.conv1.parameters():
            param.trainable = False
        for param in self.block_list.parameters():
            param.trainable = False    
```
