### ISSUE TITLE
visionlan 训练后输出只有数字

### ISSUE THREAD

**Issue by zhaochu-faimdata** [PaddlePaddle/PaddleOCR#7925]
版本是PPOCR2.6
自定义了字典，字典内容是a-z和0-9，train和validation的准确率都没有什么问题，测试时也没有报错，但是测试时所有输出都只有数字。
print了ppocr/postprocess/rec_postprocess.py里面VLLabelDecode下798行loop处理的数据，这里的tensor就缺少了字母所在位对应的结果。
想问一下有什么解决方法或者可以尝试的方向吗？
谢谢~

**Comment by andyjpaddle** [comment]
visionlan默认使用ic15字典，自定义字典后代码有个地方需要调整，参考修复PR https://github.com/PaddlePaddle/PaddleOCR/pull/7960，待合入后更新最新代码再试试

**Comment by andyjpaddle** [comment]
visionlan默认使用ic15字典，自定义字典后代码有个地方需要调整，参考修复PR https://github.com/PaddlePaddle/PaddleOCR/pull/7960
待PR合入后更新最新代码再试试
