### ISSUE TITLE
PaddleOCR   V3版本的检测和识别模型，断点训练，epoch从1开始

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7929]
训练V3版本的  det检测或者rec识别模型。   使用断点训练时，acc和lr  能继续训练，但是epoch是从1开始，无法从当前训练的epoch开始。
 例如总共500个epoch，训练了50个了，使用短点训练的话，epoch是重新设置450 ，还是继续500从epoch1开始训练？

**Comment by an1018** [comment]
通过Global.checkpoints指定要加载的模型路径进行断点继续训练，参数不需要修改
