### ISSUE TITLE
老师，请问ser+re任务里linking的标注在ppocrlabel的哪里呢？在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#7931]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
看看这个[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md#%E8%BF%91%E6%9C%9F%E6%9B%B4%E6%96%B0)介绍哈

**Comment by 1998wy123** [comment]
老师，请问ser+re的标签，问题，答案和其它是可标的，那id和linking在哪里标注呢？在线等您回复哈，谢谢!


&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月14日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问ser+re任务里linking的标注在ppocrlabel的哪里呢？在线等 (Issue #7931)





 
看看这个文档介绍哈

**Comment by 1998wy123** [comment]
老师，我是按这个文档的哈，但是它没有介绍re任务里的id和linking怎么标注，请问您知道吗？




王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 老师，请问ser+re任务里linking的标注在ppocrlabel的哪里呢？在线等 (Issue #7931)





 
看看这个文档介绍哈

**Comment by an1018** [comment]
linking暂时不支持标注，目前主要是kie关键字提取

**Comment by 1998wy123** [comment]
老师，请问我标注的文件哪里出问题了呢？是不能标网址，还是每个字段都要有linking呢？我只写了我需要信息的linking
谢谢老师，在线等哈


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 老师，请问ser+re任务里linking的标注在ppocrlabel的哪里呢？在线等 (Issue #7931)





 
linking暂时不支持标注，目前主要是kie关键字提取
