### ISSUE TITLE
请问怎么领取《动手学OCR》电子书？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleOCR#7935]
请问怎么领取《动手学OCR》电子书呢？扫描二维码后没回复啊

**Comment by an1018** [comment]
扫描这个二维码吗：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/README_ch.md#%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA

**Comment by hhhhhhogan** [comment]
是，请问有没有链接可以直接下载呢

**Comment by an1018** [comment]
提交后，有一个微信二维码，扫码进群后群公告有下载链接哈

**Comment by hhhhhhogan** [comment]
提交了，没有回复。。。之前也是这样的，试过了的。

**Comment by an1018** [comment]
就是进微信群，没回复吗

**Comment by hhhhhhogan** [comment]
加好友之后就没回复，也没有邀请进微信群。
