### ISSUE TITLE
在SVTR中的transform中怎样添加GA_SPIN

### ISSUE THREAD

**Issue by Delay0123456789** [PaddlePaddle/PaddleOCR#7939]
你好，是直接
 Transform:
    name: GA_SPIN
    offsets: True
    default_type: 6
    loc_lr: 0.1
    stn: True
这样写吗，然后问一下这个GA_SPIN网络不需要训练是吗，还有我看已经有超分TSRN的网络了，如果加超分的话又应该怎样添加呢，非常感谢

**Comment by huangjun12** [comment]
可以参考这个文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/add_new_algorithm.md
