### ISSUE TITLE
E0921 22:37:35.347833 13728 analysis_config.cc:73] Please compile with gpu to EnableGpu()

### ISSUE THREAD

**Issue by fupingren** [PaddlePaddle/PaddleOCR#794]
E0921 22:37:35.347833 13728 analysis_config.cc:73] Please compile with gpu to EnableGpu()

请问一下，直接预测提示这个问题，怎么处理？

**Comment by fupingren** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/whl_en.md

https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/installation_en.md
两种方式安装都报这个错误，在win7和win10 64位上都试过了

**Comment by LDOUBLEV** [comment]
你用GPU预测还是CPU预测，报错提示paddle版本是cpu，预测的时候指定use_gpu=False就可以预测了

**Comment by yq407** [comment]
你估计是cpu版本和gpu版本的paddlepaddle都安装了，但是gpu版本的安装失败了，你把cup版本的卸载了 试下gpu版本的paddlepaddle安装成功没有。我的报缺少tensorRT
