### ISSUE TITLE
文件列表为空

### ISSUE THREAD

**Issue by JackMeiLong** [PaddlePaddle/PaddleOCR#7946]
‘打开目录’之后，左侧文件列表为空，求救！
<img width="257" alt="image" src="https://user-images.githubusercontent.com/16250425/196067503-3f7f9ac7-22f9-426a-891b-418eaf240cd6.png">

**Comment by LDOUBLEV** [comment]
打开的目录下是有图像的吗

**Comment by JackMeiLong** [comment]
已解决，谢谢

**Comment by ChengRui536** [comment]
请问您是怎么解决的？我也遇到了相同问题
