### ISSUE TITLE
PPOCRLabel 2.6 报错 cannot import name 'check_and_read_gif' from 'ppocr.utils.utility'  微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#7951]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.6  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PPOCRLabel 2.6 报错 cannot import name 'check_and_read_gif' from 'ppocr.utils.utility'  微信nlanguage

**Comment by xialei2821212670** [comment]
pip install paddleocr=2.6.0.1,

**Comment by zack-rgb** [comment]
没有这个paddleocr
ERROR: Invalid requirement: 'paddleocr=2.6.0.1'
Hint: = is not a valid operator. Did you mean == ?

**Comment by feixingmoshi** [comment]
How did you solve this problem?

**Comment by nissansz** [comment]
Don't remember. Maybe reinstall all packages
