### ISSUE TITLE
db / db++ 怎样让模型输出poly类型的坐标

### ISSUE THREAD

**Issue by JunYao1020** [PaddlePaddle/PaddleOCR#7952]
能在paddleserving上获得db/db++的多点坐标输出吗

**Comment by LDOUBLEV** [comment]
在后处理里，将https://github.com/PaddlePaddle/PaddleOCR/blob/5f06a8068eed3e1755b8ca56004cd46c95ac268d/configs/det/det_r50_db%2B%2B_td_tr.yml#L57 设置为poly
