### ISSUE TITLE
老师，pyinstaller打包后的paddleocr报HTTPSconnectionPool错误该怎么解决呀

### ISSUE THREAD

**Issue by l1uuuuu** [PaddlePaddle/PaddleOCR#7954]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C677858AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by WenmuZhou** [comment]
没跑过打包，要跑应用程序的话，建议使用paddleocrshape
