### ISSUE TITLE
驾驶证/行驶证/车辆登记证文本识别的精度很差

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleOCR#7955]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：PaddleOCR：2.6

PPOCRV3识别模型推理：
![image](https://user-images.githubusercontent.com/51023060/196101481-ac33d0a2-1b75-44c3-8fd7-4019ea6c1033.png)

**Comment by BeyondYourself** [comment]
这种你得自己进行训练，或者用规则进行校正就行

**Comment by guishilike** [comment]
这种重新训练对数据量的要求大吗
