### ISSUE TITLE
训练了一个能够同时识别竖排和横排文字的模型,但在推理时碰到了图片尺寸的问题

### ISSUE THREAD

**Issue by Like2021** [PaddlePaddle/PaddleOCR#7958]
我的数据集大都是这样的
![14_3906](https://user-images.githubusercontent.com/95627417/196119724-a655885b-521c-4f98-a365-34b1ad6a4928.jpg)
![16_2398](https://user-images.githubusercontent.com/95627417/196119755-5c65abaf-580e-4904-bd16-f69728bf4109.jpg)

我该如何修改image_shape,才能识别用摄像头抓取的图片里的文本段,而不是因为resize后失真,得不到结果

https://github.com/PaddlePaddle/PaddleOCR/blob/4d3cd67cc23b756a8d67f57b4c6d868b3186b4b6/configs/rec/multi_language/rec_en_number_lite_train.yml#L93-L94

我尝试解决这个问题,通过看源码,infer主要调用了这个函数,但我还是没有思路

https://github.com/PaddlePaddle/PaddleOCR/blob/4d3cd67cc23b756a8d67f57b4c6d868b3186b4b6/ppocr/data/imaug/rec_img_aug.py#L499-L523

假设抓取的图片尺寸是(1080, 1920),我应该如何修改呢,能给予一些提示或者建议吗

或者说我需要利用类似于这样的数据集图片训练?

![samples](https://user-images.githubusercontent.com/95627417/196119957-75bd0a3e-5235-48cc-85f2-ee9d1529e08c.png)

**Comment by drenched9** [comment]
应该是你预测的时候要加上一个分类模型，分出是否旋转了90°或者180°。然后就可以正常识别了

**Comment by yangy996** [comment]
如果不想重新训练模型的话，可以尝试一下这种方式
https://blog.csdn.net/YY007H/article/details/124973777

**Comment by Like2021** [comment]
感谢,已经解决了
