### ISSUE TITLE
请问rec后处理的时候，为什么保留的是得分较低的重复项？

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleOCR#7971]
从图可以看到，在做文字识别后处理的时候，进行文字去重时，保留的重复项是得分为0.56的，而0.99反而没有保留，导致计算这行文字的得分最终得分较低。
![image](https://user-images.githubusercontent.com/15188456/196324121-372e5e73-30d9-428c-be22-16325d94b601.png)

**Comment by yangy996** [comment]
改成这样，准确率明显提高了不少
![image](https://user-images.githubusercontent.com/15188456/196343569-69c757e3-d976-4ee3-bb99-998733340797.png)

**Comment by yangy996** [comment]
@LDOUBLEV @WenmuZhou 大佬帮忙看看，可以这样改吗？

**Comment by Gmgge** [comment]
你好，这样只是得分变了呀？但是识别的字还是之前的那个字啊

**Comment by yangy996** [comment]
> 你好，这样只是得分变了呀？但是识别的字还是之前的那个字啊

是的，根据官方代码，默认只获取第一个重复项，但没考虑重复项得分是不一样的，会导致明明识别是正确的，但最终得分却异常低。不知道是不是个bug，大佬还没给回应。

**Comment by littletomatodonkey** [comment]
你好，在paddleocr系统里面，没有考虑识别结果得分，所以这里优先关注了结果，比较得分的耗时可以被节省掉，如果你对识别结果得分非常关注的话，可以改成上面的形式，但是可能会增加后处理的耗时。

**Comment by yangy996** [comment]
> 你好，在paddleocr系统里面，没有考虑识别结果得分，所以这里优先关注了结果，比较得分的耗时可以被节省掉，如果你对识别结果得分非常关注的话，可以改成上面的形式，但是可能会增加后处理的耗时。

好的，了解了，经过测试，基本不会增加什么耗时。

**Comment by LimitSleep1991** [comment]
示例代码随便看看就行了，去重都是简单的把所有重复字符只保留第一个，如果检测文本是叠词，就会漏字，模型的输出不带单字检测框，纯敷衍
