### ISSUE TITLE
DBNet 训练精度问题

### ISSUE THREAD

**Issue by adaxiadaxi** [PaddlePaddle/PaddleOCR#7972]
- 系统环境/System Environment：docker pull registry.baidubce.com/paddlepaddle/paddle:latest-dev 
- 版本号/Version：Paddle：2.3.1  PaddleOCR： develop分支
- 运行模式：静态图，参考代码：https://gitee.com/paddlepaddle/PaddleOCR/blob/develop/tools/train.py?from_wecom=1 （p.s 因为动态图转静态图工具有问题，因此直接运行静态图版本）
- 单机单卡
- 完整报错/Complete Error Message：

- V100上: hmean≈0.67，precision≈0.75，recall≈0.59，hmean应该可以接近0.70。

![image](https://user-images.githubusercontent.com/58928121/196323853-126b9dad-16bf-4f0e-b7a9-0e9988c9319d.png)

- 在国产AI训练芯片上：hmean≈0.54，precision≈0.73，recall≈0.43

![image](https://user-images.githubusercontent.com/58928121/196324549-5749c88c-1396-40e9-8a86-52d453269008.png)

其他说明：bs=16、inputsize=736*1280，数据集：ICDAR2015

需求：期望能DBNet的hmean达到0.70，想问问paddleocr或者是paddle框架同学看看，我们需要怎么修改，提供一些指导建议，如果方便的话可以微信沟通联系，我方可以提供log日志，训练文件，源码等，谢谢~

**Comment by adaxiadaxi** [comment]
[train.zip](https://github.com/PaddlePaddle/PaddleOCR/files/9806057/train.zip)
[program.zip](https://github.com/PaddlePaddle/PaddleOCR/files/9806059/program.zip)

**Comment by andyjpaddle** [comment]
推荐使用release2.6分支代码，develop版本已经不再更新维护了
