### ISSUE TITLE
PPOCRLabel在标注表格结构时很慢

### ISSUE THREAD

**Issue by PC-god** [PaddlePaddle/PaddleOCR#7973]
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/PPOCRLabel：
- PPOCRLabel在标注表格结构时，会调用模型预标注。在windows下没有gpu，会很慢。如何能将模型部署到服务器上。
- 或者PPOCRLabel是否可以在centos上安装并使用

**Comment by jingsongliujing** [comment]
可以的，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/PPOCRLabel.py

**Comment by jingsongliujing** [comment]
self.ocr = PaddleOCR(use_pdserving=False,
                             use_angle_cls=True,
                             det=True,
                             cls=True,
                             use_gpu=gpu,
                             lang=lang,
                             show_log=False)
        self.table_ocr = PPStructure(use_pdserving=False,
                                     use_gpu=gpu,
                                     lang=lang,
                                     layout=False,
                                     show_log=False)

**Comment by jingsongliujing** [comment]
97-108行源码把use_pdserving=False改为True,再单独起一个serving就行

**Comment by PC-god** [comment]
谢谢，我试试

**Comment by PC-god** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/README_CN.md

1.参考文档，已安装服务。
2.设置PPOCRLabel.py的97行PaddleOCR(use_pdserving=True后，并没有真的调用服务器端推理呢，我debug看rec_model_dir模型路径还是本地的路径~ 
3.server文档部署的是检测和识别，关于表格结构识别的如何一并部署上呢

**Comment by PC-god** [comment]
参考了，不知道还改哪里呀。这个问题就是我提的~
没解决。。。

**Comment by PC-god** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/README_CN.md

大佬，有时间再指导下：部署server完成了；ocr label的参数use serving参数改了，还是本地运行的。

**Comment by jingsongliujing** [comment]
你配置文件里的self.path没改，这里要改一下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/libs/settings.py

**Comment by PC-god** [comment]
> 你配置文件里的self.path没改，这里要改一下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/libs/settings
改self.path，改成什么才能使本地的PPOCRLabel能调server的推理~
这个问题到这吧，不用服务器只用windows本地慢慢标表格吧。
感觉虽然文档很全，开箱即用，但是做二次开发的时候，文件注释和函数注释就不清晰了。难调哦。
还是给个赞
