### ISSUE TITLE
kie中ser模型训练问题，如何不加载预训练模型直接训练，预训练模型如何训练的

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/PaddleOCR#7974]
./ppocr/modeling/backbones/vqa_layoutlm.py中这段代码：
class NLPBaseModel(nn.Layer):
    def __init__(self,
                 base_model_class,
                 model_class,
                 mode="base",
                 type="ser",
                 pretrained=True,
                 checkpoints=None,
                 **kwargs):
        super(NLPBaseModel, self).__init__()
        if checkpoints is not None:  # load the trained model
            self.model = model_class.from_pretrained(checkpoints)
        else:  # load the pretrained-model
            pretrained_model_name = pretrained_model_dict[base_model_class][
                mode]
            if pretrained is True:
                base_model = base_model_class.from_pretrained(
                    pretrained_model_name)
            else:
                base_model = base_model_class.from_pretrained(pretrained)

这段代码表示必须加载预训练模型或者已训练模型，如何不加载预训练模型直接训练，还有预训练模型是如何训练来的？

**Comment by littletomatodonkey** [comment]
你好

1. 这种大规模多模态模型建议都加载预训练模型去训练，不然无法收敛
2. 预训练模型是使用自监督方法训练得到的，你可以参考LayoutXLM这篇论文
