### ISSUE TITLE
PP-Structure 加载其他模型

### ISSUE THREAD

**Issue by JackMeiLong** [PaddlePaddle/PaddleOCR#7975]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/16250425/196351238-cd959649-fcfa-409d-8159-e3c474f4de09.png">

你好，基于PP-Structure 和layout parser 进行版面分析，如何加载其他模型？比如 picodet_lcnet_x1_0_fgd_layout_cdla，
model = lp.PaddleDetectionLayoutModel(model_path="./picodet_lcnet_x1_0_fgd_layout_cdla/",...) 通过这种方式加载本地模型，报错显示 Cannot open file ./picodet_lcnet_x1_0_fgd_layout_cdla/inference.pdmodel，求解答

**Comment by an1018** [comment]
V2版本不再使用lp.*，目前有2种方式，
1）下载PaddleDetection代码，参考[这个文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/layout/README_ch.md#72-%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86)进行推理
2）使用paddllocr [whl包预测](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/docs/quickstart.md#213-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90)

**Comment by an1018** [comment]
重新安装paddleocr whl包，运行代码，可视化结果会存储在save_folder子文件夹内

**Comment by LeonWang91** [comment]
想请问可以使用CDLA的预训练模型直接去运行版面分析测试的命令吗，我也报了上面类似的错误
错误如下：
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/60532543/210127811-71668207-e6a4-4c36-99c3-1a32b59fa9e9.png">
命令如下：
python3 tools/infer.py     -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml     --slim_config configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x2_5_layout.yml     -o weights='/data_1/wangl/LeiWang/Projects/PaddleOCR/pretrained_model/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams'     --infer_img='/data_1/wangl/LeiWang/Projects/PaddleOCR/dataset/1.jpg'     --output_dir=/data_1/wangl/LeiWang/Projects/PaddleOCR/output/     --draw_threshold=0.5

我只替换了weights的内容，没有更改配置文件，好像也没有找到CDLA的配置文件
