### ISSUE TITLE
倾斜图片矫正

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#7977]
请问下，如何将一张图片识别倾斜的角度，并将图片转正过来。可以给几行代码？

**Comment by andyjpaddle** [comment]
使用cv2进行旋转即可

**Comment by tianchiguaixia** [comment]
目前我的图片有的切斜90度，有的180，有的270。目前我想的是，有没有什么方法或者模型。如果我输入一张图片就能判断角度是（0,90,180,270）

**Comment by tianchiguaixia** [comment]
> 使用cv2进行旋转即可
可以给一些例子？
