### ISSUE TITLE
请问各位这样的样本有什么优化的方案吗？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#7981]
![image](https://user-images.githubusercontent.com/102579571/196572964-3a74e6fb-ebc2-4889-99de-ba33a7243f56.png)

**Comment by jingsongliujing** [comment]
换一个预训练模型呗

**Comment by drenched9** [comment]
> > 换一个预训练模型呗
> 
> 识别模型要换成哪个预训练呢？当前是用的v3

意思是让你不直接使用v3预测，而是使用预训练模型和自己的数据标注后，重新训练一个针对你这个数据集的模型，用它来预测。

**Comment by jingsongliujing** [comment]
你要针对你的场景来选择合适你的场景模型，可以参考这些模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md
