### ISSUE TITLE
self.input_tensor.copy_from_cpu(img)推理卡死，请问是什么原因

### ISSUE THREAD

**Issue by kaaier** [PaddlePaddle/PaddleOCR#7982]
Ubuntu16系统
显卡：A100
分别在CUDA9、CUDA10环境下依次对paddle-gpu2.0.2及2.进行验证，发现paddle推理至self.input_tensor.copy_from_cpu(img)代码处卡死！

请问是什么原因，是环境问题还是代码bug!

**Comment by jingsongliujing** [comment]
建议用最新版本吧：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by kaaier** [comment]
您好 2.3.2的版本还不新吗



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月19日 11:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] self.input_tensor.copy_from_cpu(img)推理卡死，请问是什么原因 (Issue #7982) |

建议用最新版本吧：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by kaaier** [comment]
> 建议用最新版本吧：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

您好 已经选用了最新版本请问是什么原因？
ExternalError : CUDNN error(8)

**Comment by jingsongliujing** [comment]
cuda版本不对，你看看你本地的cuda版本是几



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月22日(周六) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] self.input_tensor.copy_from_cpu(img)推理卡死，请问是什么原因 (Issue #7982)




  
建议用最新版本吧：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
  
您好 已经选用了最新版本请问是什么原因？
 ExternalError : CUDNN error(8)
