### ISSUE TITLE
训练文字识别模型中的宽高比问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#7986]
训练文字识别模型 v1、v2的版本大小是[32,320]     文档中说训练中先将图片等比例缩放到高=32时，如果宽大于十倍，也就是大于320则过滤掉该图
而V3的识别模型大小是[48,320]。   那是不是先等比例到高=48，然后宽大于320过滤掉？？？？？    那就不是十倍的比例了。 
如果自己的训练集中有较多长文本，时不时应该把训练和预测的大小都修改为[48,480]了？也保持宽高比为10倍的比例？？？？  
请问是该这样调整么

**Comment by tink2123** [comment]
并非是宽大于320过滤掉，而是宽大于320会被等比缩放到320。 是否过滤当前样本是通过标签长度判断的，默认大于25个字的样本被过滤。

如果训练数据中有较多长文本，那可以把resize shape 相应再调大些， 例如[48,480] 甚至 [48, 600] 都可以， 注意：增大shape 会增加训练耗时和显存占用。
