### ISSUE TITLE
PaddleOCR is not working on GPU

### ISSUE THREAD

**Issue by Kuyas** [PaddlePaddle/PaddleOCR#7993]
Please provide the following information to quickly locate the problem

- System Environment：Amazon Linux 2
- Version：Paddle：PaddlePaddle 2.3.2  PaddleOCR: paddleocr==2.6.0.2 
Command Code：CUDA_VISIBLE_DEVICES=0 python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/254.jpg" --det_model_dir="./en_PP-OCRv3_det_slim_infer/" --rec_model_dir="./en_PP-OCRv3_rec_slim_infer/"  --rec_char_dict_path="./ppocr/utils/en_dict.txt"
 完整报错/Complete Error Message：

If I Install via the [quickstart guide](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md)
2022/10/20 05:06:16] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

C++ Traceback (most recent call last):
No stack trace in paddle, may be caused by external reasons.

Error Message Summary:
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666242377 (unix time) try "date -d @1666242377" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 46281 (TID 0x7f38e16555c0) from PID 0 ***]

Segmentation fault

If I install the docker and try to run I get the following error
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'
Stacktrace:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PaddleOCR/paddleocr.py", line 501, in __init__
    super().__init__(params)
  File "/home/PaddleOCR/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/PaddleOCR/tools/infer/predict_det.py", line 137, in __init__
    args, 'det', logger)
  File "/home/PaddleOCR/tools/infer/utility.py", line 212, in create_predictor
    gpu_id = get_infer_gpuid()
  File "/home/PaddleOCR/tools/infer/utility.py", line 308, in get_infer_gpuid
    if not paddle.fluid.core.is_compiled_with_rocm():
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'

I am not able to run any version of PaddleOCR on the gpu, 

I have Installed via multiple ways and I get the same error
1. python3 -m pip install paddlepaddle-gpu -f https://paddlepaddle.org.cn/whl/stable.html
2. pip install paddlepaddle-gpu "paddleocr>=2.0.1"
3. Using the quickstart guide's python3 -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple
If I use the code, it gives
`Paddle = PaddleOCR(use_angle_cls=True, lang="en", use_gpu=True)`
`im_path = 'B083GS9NVZ_4.jpg'`
`result = Paddle.ocr(im_path, cls=False, det=True, rec=False)
`

I get segmentation fault or the kernel crashes on jupyter

I also tried https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/installation_en.md to use nvidia-docker
and tried various versions, the version used in the readme, the latest one available to no avail
I got an error like "AttributeError: module 'paddle.fluid.core_avx' has no attribute 'is_compiled_with_rocm'"

These run if I just make the use_gpu Flag False

Can you please help me out?

Thank you

**Comment by intrainepha** [comment]
try install paddlepaddle-gpu==2.4.0rc0

**Comment by Kuyas** [comment]
> try install paddlepaddle-gpu==2.4.0rc0

I tried this but I still get the same error

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666252410 (unix time) try "date -d @1666252410" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 108692 (TID 0x7fdd9933e740) from PID 0 ***]

Segmentation fault

**Comment by LightSun** [comment]
Mine is the same.
env: paddle-gpu-2.3.2 python
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666335819 (unix time) try "date -d @1666335819" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 24602 (TID 0x7f4af0a45740) from PID 0 ***]


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by LightSun** [comment]
i fixed from 'https://www.paddlepaddle.org.cn/'.
```
//before is pip install paddlepaddle-gpu==2.3.2
python -m pip install paddlepaddle-gpu==2.3.2.post111 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

**Comment by GiovanniNova** [comment]
I was having issues with paddlepaddle-gpu too, no errors or warnings it just crashed, fixed them as per LightSun sugestion of getting the install commands from your website for CUDA 11.6, please update point "1.1 Paddle Installation" at [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/multi_languages_en.md](url) to use the link [https://www.paddlepaddle.org.cn/en/install/quick](url) instead.

**Comment by thsno02** [comment]
u may need to install NCCL~
