### ISSUE TITLE
关于kie模型训练，class_list_xfun.txt中没有other这个关键词是否会影响准确度，在标注的时候没有标注other这个关键字

### ISSUE THREAD

**Issue by bank010** [PaddlePaddle/PaddleOCR#8003]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
建议加上

**Comment by bank010** [comment]
> 建议加上

老师您好，建议是在标注的时候加上这个字段呢，还是标注的时候不写该关键点，而是在这个txt文件中加上呢？

**Comment by guoxiaoyue111111** [comment]
@bank010  您好，请问class_list_xfun.txt这个文件是从哪下载的，我运行kie中ser+re的时候，报错没有这个文件~
