### ISSUE TITLE
识别v3确实会比v2好吗？

### ISSUE THREAD

**Issue by shuizhonghaitong** [PaddlePaddle/PaddleOCR#8006]
你好，我采用相同的数据集分别训练识别的v2和v3。
1、在训练的过程中，我发现在相同的epoch下，v3的效果没有v2好，无论是train acc还是dev acc，这是正常的嘛？v3的效果要超过v2的话是不是v3需要用的epoch要比v2多？v3的学习率是否需要根据数据集的大小做调整？
2、如果几十万的训练数据，对于v2和v3，各自大约需要跑多少个epoch呢？

**Comment by tink2123** [comment]
论文中有给出相同数据下的消融实验，在26w真实训练数据上，v3训练精度明显高于v2，在不使用模型蒸馏的情况下就已经可以超越v2蒸馏模型的精度。

<img width="931" alt="image" src="https://user-images.githubusercontent.com/31891223/197462510-1a00c8ca-6545-46be-bfe1-07a538ffeeef.png">

上述问题可能与训练数据有关，场景是否比较单一呢。如果训练场景相对简单，建议训练过程去掉GTC策略，避免过拟合。

几十万的训练数据，跑200左右epoch即可。

**Comment by shuizhonghaitong** [comment]
场景是文档数据识别，我去掉了GTC，但是效果仍然没有超过v2
