### ISSUE TITLE
Using DB++ in PP-OCRv3

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8007]
Hi Everyone,
I want to replace DBnet with DB++ for Training text detection while applying the optimizations done in PP-OCRv3.

I wanted to know if that will be as easy as replacing DB by DB++ in the pp-ocrv3 config file.

**Comment by bely66** [comment]
@LDOUBLEV any idea how i can do that?

**Comment by LDOUBLEV** [comment]
Just replace DB  as DB++


Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

to


Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [False, True, True, True]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
