### ISSUE TITLE
车牌检测这类，需要用SVTR嘛

### ISSUE THREAD

**Issue by nistarlwc** [PaddlePaddle/PaddleOCR#8008]
车牌这类基本都是没有什么上下文的吧，下一个字符是什么完全不可预测。
像RNN或是SVTR这类真的有必要嘛，看intel做的LPRNet用了个简单的13*1的卷积直接代替了。
有用Paddle实现LPRNet的嘛

**Comment by WenmuZhou** [comment]
严格来说，所谓的语义信息是指训练的时候见得多了，再次见到就会自然联想

**Comment by nistarlwc** [comment]
对啊，那车牌或是编号识别这种就不会有前后字符的关联，那SVTR就没什么用咯，那应该使用什么比较合适呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月24日 14:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 车牌检测这类，需要用SVTR嘛 (Issue #8008) |

严格来说，所谓的语义信息是指训练的时候见得多了，再次见到就会自然联想

**Comment by WenmuZhou** [comment]
不要主观哈，建议实验分析

**Comment by nistarlwc** [comment]
就是有的编号，NC0015365，被识别成NC00105365，多了一位0，这肯定是SVTR猜出来的呗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月25日 16:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 车牌检测这类，需要用SVTR嘛 (Issue #8008) |

不要主观哈，建议实验分析
