### ISSUE TITLE
SVTR配置文件

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleOCR#8010]
请问SVTR系列的small base large有配置文件，我看到只提供了tiny的，没有其他三个，如果我export_model时直接用tiny的配置文件导出其他三个模型会提示模型和预训练参数不一致。

**Comment by tink2123** [comment]
不同模型参数和配置文件可以点击SVTR模型的下载链接获得：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_svtr.md#3
