### ISSUE TITLE
Can't extract tar file in ch_ppocr_mobile_v2.0_cls_infer.tar

### ISSUE THREAD

**Issue by monkiravn** [PaddlePaddle/PaddleOCR#8017]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：I can't extract Text Angle Classification Model (ch_ppocr_mobile_v2.0_cls_infer.tar), I tried in more system environments. I think to have something wrong when it was archived
![image](https://user-images.githubusercontent.com/50236861/196976836-9888bc6e-5d2a-48ca-898c-1cde52255ce9.png)

**Comment by WenmuZhou** [comment]
看看有没有解压成功呢
