### ISSUE TITLE
弯曲印章数据集生成

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#8018]
标注的是16个点的坐标，文字内容不好切分出来构建数据集。db++,检测出来的弯曲文本框，改如何让svrt，进行识别。get_rotate_crop_image（）这边也是裁剪的，4坐标点。

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/197494743-9323b8c7-f125-4b75x-b5b4-b259f2f95353.png)
，我将数据集标注的文字区域提取出来，进行训练。对这种弯曲过大的，完全不行，是需要进行后处理？
![image](https://user-images.githubusercontent.com/57654726/197497757-40c8e574-3b49-4d07-bd83-b185361f8be7.png)
![image](https://user-images.githubusercontent.com/57654726/197497881-4b19ac6c-dc00-4c08-899a-c2ae13d7c607.png)

[log.txt](https://github.com/PaddlePaddle/PaddleOCR/files/9850609/log.txt)
采用的训练参数

**Comment by phb-shiyige-fw** [comment]
你好 我想问问 可以提供一下裁剪文字内容的源码吗？官方给的是4点坐标的裁剪，我自己改一直报错。。。想问问如何进行文字提取。希望你可以帮帮我，谢谢

![123123](https://user-images.githubusercontent.com/94897119/198450855-87e85b2d-8027-4fda-a5d8-c5f3d0afdcec.png)

**Comment by phb-shiyige-fw** [comment]
你好 想请问一下您是如何将数据集中的弯曲文本截取出来的？我看md中有图片裁剪代码，但是属于四点坐标的截取，没办法实现弯曲文本的图像裁剪，请问可以提供相关的截取代码吗？感激不尽

**Comment by LDOUBLEV** [comment]
> 改如何让svrt

在SVTR中有STN，支持弯曲的文字识别

**Comment by shallow10** [comment]
有偿提供解决弯曲文本方面的数据集等代码问题
