### ISSUE TITLE
关于ch_ppstructure_mobile_v2.0_SLANet的训练数据

### ISSUE THREAD

**Issue by NaivePawn** [PaddlePaddle/PaddleOCR#8023]
您好！想问下您，训练中文的表格识别模型ch_ppstructure_mobile_v2.0_SLANet，你们用的训练数据都是通过TableGeneration生成的吗？还是有其他数据

**Comment by littletomatodonkey** [comment]
也有其他的数据，可以参考我们的技术报告：https://arxiv.org/abs/2210.05391

**Comment by NaivePawn** [comment]
嗯嗯，之前就看过了，我看用的是Pubtabnet，这个是英文的吧，我想问问中文的数据

**Comment by ywachao** [comment]
TableGeneration 只支持四种表格样式吧
