### ISSUE TITLE
paddleocr 版面分析时报错 

### ISSUE THREAD

**Issue by songsh** [PaddlePaddle/PaddleOCR#8024]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos 7.9
- 版本号/Version：Paddle：2.3.1  PaddleOCR： 2.6.0.1 问题相关组件/Related components：
- 运行指令/Command Code：paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure
- 完整报错/Complete Error Message：
	
	'==SUPPRESS==', image_dir='./ppstructure/docs/table/1.png', image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path='/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/ppocr/utils/dict/layout_dict/layout_cdla_dict.txt', layout_model_dir='/home/wangquan/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_shape='3, 48, 320', rec_model_dir='/home/wangquan/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', save_pdf=False, scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, shape_info_filename=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-Structurev2', table=True, table_algorithm='TableAttn', table_char_dict_path='/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/ppocr/utils/dict/table_structure_dict_ch.txt', table_max_len=488, table_model_dir='/home/wangquan/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer', total_process_num=1, type='structure', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
Traceback (most recent call last):
  File "/home/wangquan/.local/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 622, in main
    engine = PPStructure(**(args.__dict__))
  File "/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 598, in __init__
    super().__init__(params)
  File "/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 66, in __init__
    self.layout_predictor = LayoutPredictor(args)
  File "/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/ppstructure/layout/predict_layout.py", line 68, in __init__
    utility.create_predictor(args, 'layout', logger)
  File "/home/wangquan/.local/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 274, in create_predictor
    predictor = inference.create_predictor(config)
IndexError: basic_string::at: __n (which is 0) >= this->size() (which is 0)

**Comment by an1018** [comment]
如果只运行版面分析，可以下载最新的paddleocr==2.6.0.3，执行如下命令试试：
`paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure --table=false --ocr=false`
