### ISSUE TITLE
hubserving 预测图片速度慢

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#8025]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux+gpu
- 版本号/Version :  Paddlehub：2.3.0  PaddleOCR：2.6.0.1  问题相关组件/Related components：hubserving
- 运行指令/Command Code：
       服务启动 `` hub serving start -c deploy/hubserving/structure_system/config.json ``
       请求服务 ``python test_hubserving.py --server_url=http://127.0.0.1:8888/predict/structure_system --image_dir=../testdata/zf1.jpg ``

显示的单张图片预测时间只有0.1-0.2s之间， 但整个请求到返回结果的时间大约要1-2s， 请求前期似乎会延迟花费时间很长， 不知道什么原因。  有办法解决吗

**Comment by littletomatodonkey** [comment]
你好，前面的预测需要比较长时间的warmup，可以多预测几张图片看看

**Comment by ericosmic** [comment]
> 你好，前面的预测需要比较长时间的warmup，可以多预测几张图片看看

每次提交新请求 就会卡顿0.5-1s左右才进入日志记录， 如果是一次请求多张图片，图片之间不会出现卡顿。 所以这应该是服务端提交的问题，是由于发送请求的耗时吗
