### ISSUE TITLE
关于标点符号无法识别问题

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#8027]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
识别部分-------自己训练结束的模型在 python tools/eval.py 测试后准确率很高  分别87%，98%，但是相同的数据相同配置在执行python tools/infer_rec.py 后输出文字部分正确，所有的逗号“，”都没有输出，即逗号部分推理识别率为0。而句号“。”可以识别，大部分正确。字典内是有“，”的，那么eval.py部分的结果是不是不合理？请问如何可以正常识别逗号“，”       训练样本中是包含一定量逗号的

**Comment by JavieYuan** [comment]
![000000546](https://user-images.githubusercontent.com/84179587/197133099-b74d443b-0f19-4c7c-87d2-9a6306eb92ea.jpg)
![desktop](https://user-images.githubusercontent.com/84179587/197133186-bf3da7e7-b3d7-46d9-8494-48d81f61cce6.png)

**Comment by JavieYuan** [comment]
label如下：
![desktop2](https://user-images.githubusercontent.com/84179587/197133509-00591e65-2978-4a09-8ff6-576122b0141a.png)

**Comment by littletomatodonkey** [comment]
你好，这种建议自己加点数据微调一下模型哈
