### ISSUE TITLE
ValueError: invalid literal for int() with base 10: "'3"

### ISSUE THREAD

**Issue by fupingren** [PaddlePaddle/PaddleOCR#803]
移动端模型可以预测出结果python tools/infer/predict_rec.py --image_dir=c:\isay\mi.png --rec_model_dir=C:\isay\PaddleOCRdev\inference\en_ppocr_mobile_v1.1_rec_infer --use_gpu=False --rec_char_type=en
server模型预测时候报错
python tools/infer/predict_rec.py --image_dir=c:\isay\mi.png --rec_model_dir=C:\isay\PaddleOCRdev\inference\ch_ppocr_server_v1.1_rec_infer --use_angle_cls=False --use_gpu=False --rec_char_type=en --rec_image_shape='3,32,100'

报错提示：
Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 335, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_rec.py", line 304, in main
    text_recognizer = TextRecognizer(args)
  File "tools/infer/predict_rec.py", line 39, in __init__
    self.rec_image_shape = [int(v) for v in args.rec_image_shape.split(",")]
  File "tools/infer/predict_rec.py", line 39, in <listcomp>
    self.rec_image_shape = [int(v) for v in args.rec_image_shape.split(",")]
ValueError: invalid literal for int() with base 10: "'3"

**Comment by fupingren** [comment]
不加 --rec_image_shape='3,32,100' 这个参数时候报错提示：
list index out of range
2020-09-23 10:34:37,586-INFO: ERROR!!!!
Please read the FAQ：https://github.com/PaddlePaddle/PaddleOCR#faq
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'


环境：win7 64 python3.7.7 按https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md安装的

**Comment by littletomatodonkey** [comment]
> 移动端模型可以预测出结果python tools/infer/predict_rec.py --image_dir=c:\isay\mi.png --rec_model_dir=C:\isay\PaddleOCRdev\inference\en_ppocr_mobile_v1.1_rec_infer --use_gpu=False --rec_char_type=en
> server模型预测时候报错
> python tools/infer/predict_rec.py --image_dir=c:\isay\mi.png --rec_model_dir=C:\isay\PaddleOCRdev\inference\ch_ppocr_server_v1.1_rec_infer --use_angle_cls=False --use_gpu=False --rec_char_type=en --rec_image_shape='3,32,100'
> 
> 报错提示：
> Traceback (most recent call last):
> File "tools/infer/predict_rec.py", line 335, in
> main(utility.parse_args())
> File "tools/infer/predict_rec.py", line 304, in main
> text_recognizer = TextRecognizer(args)
> File "tools/infer/predict_rec.py", line 39, in **init**
> self.rec_image_shape = [int(v) for v in args.rec_image_shape.split(",")]
> File "tools/infer/predict_rec.py", line 39, in
> self.rec_image_shape = [int(v) for v in args.rec_image_shape.split(",")]
> ValueError: invalid literal for int() with base 10: "'3"

移动端你使用的是英文模型，服务端你使用的是通用中文模型，这两个配置不太一样的

**Comment by fupingren** [comment]
是按照指引https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md的步骤的操作的，没有提示有什么不同

**Comment by MissPenguin** [comment]
可以拉最新代码试试，如果还有问题可以reopen或者重新提issue，我们再跟进哈。

**Comment by shaoshenchen** [comment]
我在跑移动端模型的时候也遇到了类似的问题
```sh
python tools/infer/predict_rec.py \
  --image_dir="./img/test" \
  --rec_model_dir="./infer_model/ch_ppocr_mobile_v2.0_rec_infer" \
  --use_angle_cls=True \
  --use_space_char=False
```

# 报错内容
```
[2021/05/27 19:48:44] root INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 269, in main
    rec_res, predict_time = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 243, in __call__
    rec_result = self.postprocess_op(preds)
  File "D:\junior\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 116, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "D:\junior\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][idx])])
IndexError: list index out of range

[2021/05/27 19:48:44] root INFO: ERROR!!!!
Please read the FAQ：https://github.com/PaddlePaddle/PaddleOCR#faq
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'
```
