### ISSUE TITLE
onnx部署文档有误

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleOCR#8035]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：window10
- 版本号/Version：release2.6 Paddle：  PaddleOCR： 问题相关组件/Related components：onnx
onnx部署页面文档错误：
![image](https://user-images.githubusercontent.com/16351823/197168636-a85a1588-824c-4258-97a2-33d09e9ab4df.png)

**Comment by WenmuZhou** [comment]
请问是哪个文档呢

**Comment by xdg2016** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme.md

**Comment by WenmuZhou** [comment]
这两个应该就过就是一样的，你测的不一样吗

**Comment by xdg2016** [comment]
onnxruntime和paddle inference的结果，耗时连小数点后面几位都一模一样吗，之前的版本这个文档，onnxruntime比paddleinference快很多
![image](https://user-images.githubusercontent.com/16351823/197461171-c6a4b04a-3424-4340-a106-381e89447d28.png)
![image](https://user-images.githubusercontent.com/16351823/197461210-d4ea554e-ee91-4cb4-8f1f-8c2ee24da46f.png)

**Comment by tink2123** [comment]
确认下是的，感谢反馈我们更新一下
