### ISSUE TITLE
pip install paddleocr 后运行代码显示错误

### ISSUE THREAD

**Issue by daihuangliang** [PaddlePaddle/PaddleOCR#804]
File "D:\Anaconda3\lib\site-packages\paddleocr\ppocr\utils\utility.py", line 19, in <module>
    from paddle import fluid
No module named 'paddle'

**Comment by WenmuZhou** [comment]
安装paddlepaddle了吗

**Comment by xxllp** [comment]
啥时候模型能够完全二进制就好了
