### ISSUE TITLE
PPOCRLabel如何在标注表格结构时将模型推理放到服务器上

### ISSUE THREAD

**Issue by PC-god** [PaddlePaddle/PaddleOCR#8044]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.6
- 版本号/Version：Paddle：  PaddleOCR： PPOCRLabel/Related components：release/2.6
- 运行指令/Command Code：本地windows标注表格
- 完整报错/Complete Error Message：
本地无gpu时，根据社区上一个问题的回复。将PPOCR server部署到服务器上，并可以本地调起。
上一个回复是PPOCRLable.py的97行，use_pdserving参数设为True。
我这边调整后，未发现表格识别推理对应调用 服务器。请问 是PPOCRLable不支持吗
`self.ocr = PaddleOCR(use_pdserving=True,
                             use_angle_cls=True,
                             det=True,
                             cls=True,
                             use_gpu=gpu,
                             lang=lang,
                             show_log=False)`

**Comment by an1018** [comment]
Hi, you can refer to #7973
