### ISSUE TITLE
请问RARE可以识别倒的印章？还是要把印章矫正后再RARE识别？并且看文中中PGNet夜没提对印章的文字是否需要矫正？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#8046]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
倒的印章是指旋转180度的发票吗，目前[弯曲印章检测](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md)是通过印章检测，再通过OCR实现文字识别

**Comment by cqray1990** [comment]
> 倒的印章是指旋转180度的发票吗，目前[弯曲印章检测](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md)是通过印章检测，再通过OCR实现文字识别

@an1018 有印章是倒的导致里面的文字是倒的,能识别?

**Comment by xialei2821212670** [comment]
我是用2阶段的,这个倒置还没想到过,应该可以加上文本角度检测吧。
