### ISSUE TITLE
为什么我训练后测试是只有检测，没有识别？

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#8047]
为什么我训练后测试是只有检测，没有识别？

文本检测
python tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./doc/imgs_en/1.jpg" Global.pretrained_model="./output/db_mv3/latest"

我自己训练蓝色框(没有label)：
![我自己训练](https://user-images.githubusercontent.com/6648329/197328134-e9d5c567-e2cd-466a-acee-a296161e866d.jpg)

而官方是这样的(有label)：
![官方](https://user-images.githubusercontent.com/6648329/197328185-090c2380-c352-4573-a993-4baf6cca292b.jpg)

--------------------无敌分割线--------------------------
为什么我训练后测试是只有检测，没有识别？ 如果加识别，是不是还是循环检测后， 分别裁切出来 再进行 文本识别？  是这样的思路吗，官方是这样 做的吗，这样也太复杂了点....

**Comment by thsno02** [comment]
你用的 `infer_det` 只能获取到检测结果，识别结果使用 `infer_rec`。

**Comment by gg22mm** [comment]
> 你用的 `infer_det` 只能获取到检测结果，识别结果使用 `infer_rec`。

这都行吗？  好象报错呢？
`
Traceback (most recent call last):
  File "tools/infer_rec.py", line 166, in <module>
    main()
  File "tools/infer_rec.py", line 143, in main
    post_result = post_process_class(preds)
TypeError: __call__() missing 1 required positional argument: 'shape_list'
`

原因我是用det_mv3_db.yml训练的，也能用'infer_det' ？ ： python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./weight/ch_ppocr_mobile_v2.0_det_train/best_accuracy

**Comment by thsno02** [comment]
你说的没错呀，这是目前做 OCR 的逻辑，先检测再识别。你只使用了 mv_db 训练检测模型，还需要训练一个识别模型，也可以直接使用预训练模型试试。

**Comment by gg22mm** [comment]
> 

1、非常感谢，了解了。  裁切这一部分能不能省略？还有官方就一个模型就可以做到检测与识别了，如何做到？ 我做就得分开，像官方是怎么合并成一个模型的？
2、直接使用预训练模型 对 有些文字匹配 不够精确。比如： 3Dbody 经常变成：BDUody, BDbody,3Dbecy.....更多等等... 所以我才想加强模型 再优化训练（当然这个优化是在检测与识别两个模型合并后的基础上）， 如何按两步骤来做的话，那问题来了，怎么能像官方是怎么合并成一个模型的？

**Comment by thsno02** [comment]
我个人理解：
+ 如果你要在自己的数据集上分别训练检测模型和识别模型，裁切是不能省的。
+ 官方是多个模型打包成一个大模型，本质上是没有变化的。你自己做的时候，分别训练后，写一个逻辑就能把两个模型连在一起了。
+ 直接使用预训练当然没法满足一些特定的需求，所以可以进行相应的微调。

**Comment by gg22mm** [comment]
> 我个人理解：
> 
>     * 如果你要在自己的数据集上分别训练检测模型和识别模型，裁切是不能省的。
> 
>     * 官方是多个模型打包成一个大模型，本质上是没有变化的。你自己做的时候，分别训练后，写一个逻辑就能把两个模型连在一起了。
> 
>     * 直接使用预训练当然没法满足一些特定的需求，所以可以进行相应的微调。

非常感谢！，按您这个思路 我应该找到 官方的那个 单独的 “识别模型” 进行二次训练， 我记忆中官方只下载了一下模型，我没办法分别去处理。 

“检测模型” 目前 倒是不用动~~  ，  如果能够突破这个 才能在 官方现有的模型上二次训练， 这样的话模型才会越来越万能。11

**Comment by gg22mm** [comment]
我看到有分别模型下载，我突然觉得我的方案可行了：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/models_list.md#1.1

**Comment by gg22mm** [comment]
根我想象的还是有点差别： https://github.com/PaddlePaddle/PaddleOCR/issues/8103
