### ISSUE TITLE
显示ModuleNotFoundError: No module named 'auto_log'

### ISSUE THREAD

**Issue by lizhecome** [PaddlePaddle/PaddleOCR#8049]
安装autolog也没有作用
>pip install autolog
![屏幕截图 2022-10-22 193715](https://user-images.githubusercontent.com/910197/197336931-f3f0005b-f35e-422f-b4dd-f5ade4cc3882.png)
===========
写成code也是一样的，我又在linux上试了下，依旧一样
![屏幕截图 2022-10-22 204539](https://user-images.githubusercontent.com/910197/197339741-b830ab3c-8300-4659-8c69-a55a3e17dbad.png)

**Comment by ejri** [comment]
```
pip install autolog
pip install https://paddleocr.bj.bcebos.com/libs/auto_log-1.2.0-py3-none-any.whl
```

**Comment by nicken** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/test_tipc/docs/install.md#4-%E5%AE%89%E8%A3%85paddleocr%E4%BE%9D%E8%B5%96

```
# 安装AutoLog
git clone https://github.com/LDOUBLEV/AutoLog
cd AutoLog
pip3.7 install -r requirements.txt
python3.7 setup.py bdist_wheel
pip3.7 install ./dist/auto_log-1.0.0-py3-none-any.whl
```
