### ISSUE TITLE
老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#8051]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
RE动转静还是适配中，后续可以关注更新~

**Comment by 1998wy123** [comment]
老师，请教您个问题，RE不能将训练模型转化为推理模型的话，我在用ser+re任务时，我可以用ser的推理模型加re的训练模型进行批量图片推理吗？
在线等，谢谢
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月25日(星期二) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
RE动转静还是适配中，后续可以关注更新~

**Comment by sybest1259** [comment]
麻烦咨询一下，我训练re模型，直接报错了paddle-gpu2.3.2

**Comment by 1998wy123** [comment]
可能你电脑没有GPU只有CPU
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
麻烦咨询一下，我训练re模型，直接报错了paddle-gpu2.3.2

**Comment by sybest1259** [comment]
ser模型可以训练导出inference，re训练就报错

**Comment by 1998wy123** [comment]
我的re训练也报错过，我看公开数据集XFUND是两种任务都做的，我也准备去问问，你的是linking错误吗?还是显存溢出了
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
ser模型可以训练导出inference，re训练就报错

**Comment by sybest1259** [comment]
应该是paddle版本问题，我用的paddlepaddle-gpu2.3.2，你用的什么版本？

**Comment by 1998wy123** [comment]
你用的数据集是自己的吗，还是公开的，我的是paddlepaddle的CPU版本
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
应该是paddle版本问题，我用的paddlepaddle-gpu2.3.2，你用的什么版本？

**Comment by sybest1259** [comment]
版本号是多少？re任务可以训练吗？
我的数据是公开的发票数据集

**Comment by 1998wy123** [comment]
公开数据集我用服务器可训练&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
版本号是多少？re任务可以训练吗？
 我的数据是公开的发票数据集

**Comment by sybest1259** [comment]
paddlepaddle版本号麻烦告一下

**Comment by sybest1259** [comment]
你发了吗？没看到

**Comment by 1998wy123** [comment]
2.3.2
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问RE任务训练好模型，能不能模型导出为推理模型呢？在线等，谢谢 (Issue #8051)





 
你发了吗？没看到

**Comment by sybest1259** [comment]
我也是2.3.2，难道是gpu版本有问题？

**Comment by WenmuZhou** [comment]
re导出可以参考这个https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/kie.md#4-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B
