### ISSUE TITLE
在训练文字识别部分

### ISSUE THREAD

**Issue by KKKKQF** [PaddlePaddle/PaddleOCR#8055]
![image](https://user-images.githubusercontent.com/87752678/197372739-a07f3d2f-f48e-439a-b907-007c3eaf848e.png)
加载数据，我看他都可以读到图片和对应内容，但是一到transforms阶段就报出这个问题，请问是什么原因，折磨我好久了

**Comment by KKKKQF** [comment]
请问有人知道吗

**Comment by huangjun12** [comment]
op是list类型，报错显示无法调用。正常来说，op应该是个class，是否数据变换的op类没有build成功？

**Comment by KKKKQF** [comment]
> op是list类型，报错显示无法调用。正常来说，op应该是个class，是否数据变换的op类没有build成功？

您好，我这个data类型的是字典型的，您说的op类没build具体是指什么
![image](https://user-images.githubusercontent.com/87752678/200110383-99af4535-30cc-42bf-852c-d5a6ee527acf.png)
