### ISSUE TITLE
No module named 'auto_log'

### ISSUE THREAD

**Issue by KhushiPatel09** [PaddlePaddle/PaddleOCR#8058]
Running **table_engine = PPStructure(layout=False, show_log=True)** command throws the following error:
ModuleNotFoundError: No module named 'auto_log'

![image](https://user-images.githubusercontent.com/87112390/197374492-011485d6-e22c-4e9c-a795-1cbf5ac74123.png)

**Comment by nicken** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/test_tipc/docs/install.md#4-%E5%AE%89%E8%A3%85paddleocr%E4%BE%9D%E8%B5%96

```
# 安装AutoLog
git clone https://github.com/LDOUBLEV/AutoLog
cd AutoLog
pip3.7 install -r requirements.txt
python3.7 setup.py bdist_wheel
pip3.7 install ./dist/auto_log-1.0.0-py3-none-any.whl
```

**Comment by KhushiPatel09** [comment]
@nicken Thank you!
