### ISSUE TITLE
使用pp_OCRv2训练的检测模型，训练效果很好，转换成推理模型后，推理结果很查

### ISSUE THREAD

**Issue by wy18217312937** [PaddlePaddle/PaddleOCR#8063]
用的与训练模型是ch_PP-OCRv2_det_distill_train
基于ch_PP-OCRv2_det_student.yml训练日期检测模型。
使用训练完的模型直接测试，infer_det.py，效果很好。
然后使用export_model.py对best_accuracy模型进行转换为推理模型（基于训练时的配置表config.yml），得到inference模型，使用predict_det.py做预测。效果很不好。
![img_224](https://user-images.githubusercontent.com/107088532/197439854-c865cf44-831d-4f5e-81f1-55052493916d.jpg)
![det_res_img_224](https://user-images.githubusercontent.com/107088532/197439897-8dae977e-df14-434e-8415-c1d6df70452a.jpg)
如何保证predict_det.py的效果和infer_det.py一致？

**Comment by huylgia** [comment]
Infer_det.py
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/det/ch_PP-OCRv2/ch_PP-OCRv2_det_distill.yml#L161
Default: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/data/imaug/operators.py#L221-L223

Predict_det.py
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/utility.py#L51-L52
