### ISSUE TITLE
ModuleNotFoundError: No module named 'ppocr.modeling' after pip install paddleocr and paddle paddle

### ISSUE THREAD

**Issue by rbavery** [PaddlePaddle/PaddleOCR#8064]
- 系统环境/System Environment：Mac
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.0.3 
- 运行指令/Command Code：`from ppocr.modeling.backbones.det_mobilenet_v3 import MobileNetV3`
- 完整报错/Complete Error Message：

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 from ppocr.modeling.backbones.det_mobilenet_v3 import MobileNetV3

ModuleNotFoundError: No module named 'ppocr.modeling'
```

I've made a condo environment and installed packages with pip following these instructions: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/quickstart_en.md

And the command code that reveals the error is used in the DiveIntoOCR book: https://github.com/PaddleOCR-Community/Dive-into-OCR/blob/main/notebook_en/2.text_detection/text_detection_practice.ipynb

**Comment by rbavery** [comment]
```
import ppocr
dir(ppocr)
```

returns

```
['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'data',
 'postprocess',
 'utils']
```

so it looks like only some submodules are available but I don't know why

**Comment by sshappys** [comment]
已解决。安装过程有问题，重新安装。

**Comment by LDOUBLEV** [comment]
hi，if you try training your own model using PaddleOCR, please clone https://github.com/PaddlePaddle/PaddleOCR.

The paddleocr pypi whl only support model inference

**Comment by ashik950** [comment]
from ppocr.predict_system import TextSystem
ModuleNotFoundError: No module named 'ppocr'
