### ISSUE TITLE
最新V1.1的模型开启了enable_mkldnn后会报错

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/PaddleOCR#807]
最新V1.1的模型ch_ppocr_server_v1.1_xx开启了enable_mkldnn后会报错，报错信息：

  File "D:/DIG/daas-dmg-ocr-py/tests/ocr/ocr_test.py", line 20, in <module>
    ocr = PaddleOCR(det_model_dir=det_model_dir, rec_model_dir=rec_model_dir, cls_model_dir=cls_model_dir, use_angle_cls=True, lang='ch', use_gpu=False, enable_mkldnn=True)
  File "C:\Program Files\Python36\lib\site-packages\paddleocr\paddleocr.py", line 222, in __init__
    super().__init__(postprocess_params)
  File "C:\Program Files\Python36\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Program Files\Python36\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 80, in __init__
    utility.create_predictor(args, mode="det")
  File "C:\Program Files\Python36\lib\site-packages\paddleocr\tools\infer\utility.py", line 133, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Attribute output_padding is not found in proto conv2d_transpose at (D:\1.8.4\paddle\paddle\fluid\framework\op_desc.cc:521)

如果使用GPU是没问题的，但是CPU+开启mkldnn就会报这个错，之前旧的版本使用ch_det_r50_vd_db和ch_rec_r34_vd_crnn模型的话是没问题的

**Comment by JwDong2019** [comment]
你好,你有在ICDAR上加载MobileNetV3_large_x0_5_pretrained训练过吗?

**Comment by littletomatodonkey** [comment]
你好，建议使用2.0的paddle，同时可以看下你的路径是否正确吗？

**Comment by zhangmianhongni** [comment]
> 你好，建议使用2.0的paddle，同时可以看下你的路径是否正确吗？

什么路径，模型路径吗？模型路径应该没问题的，因为使用GPU和CPU（不开mkldnn）都没有问题，旧版本的时候开启mkldnn也不会报错，就是刚把模型更新到ppocr1.1的模型就报错了。

还有2.0的paddle的话因为我还有使用其他paddlehub的服务，更新到2.0怕现在还不是太稳定

**Comment by hannhu** [comment]
> 你好，建议使用2.0的paddle，同时可以看下你的路径是否正确吗？

同样的问题，也是关闭mkldnn以后可以运行cpu版本。现在用cpu+mkldnn一定要升级2.0版本吗？

**Comment by demonxjj** [comment]
升级到2.0 也一样出现这个问题

**Comment by zhangmianhongni** [comment]
这个问题没人解决么。。？

**Comment by littletomatodonkey** [comment]
我这边用2.0.0b0或者2.0.0rc的代码测试的时候，都是没有问题的，可以提供下你那边更详细一些的细节吗？windows还是linux之类的

**Comment by zhangmianhongni** [comment]
windows（win10）和centos7.3都试过，paddle是1.8.4的版本；
` det_model_dir = os.path.join(model_folder, 'ch_ppocr_server_v1.1_det_infer')
    rec_model_dir = os.path.join(model_folder, 'ch_ppocr_server_v1.1_rec_infer')
    cls_model_dir = os.path.join(model_folder, 'ch_ppocr_mobile_v1.1_cls_infer')
    ocr = PaddleOCR(det_model_dir=det_model_dir, rec_model_dir=rec_model_dir, cls_model_dir=cls_model_dir, use_angle_cls=True, lang='ch', use_gpu=False, enable_mkldnn=True)

    result = None
    image_path = 'pdf_output/0.png'
    im = Image.open(image_path)
    image = np.array(im.convert('RGB'))
    result = ocr.ocr(image, cls=True)
    print(result)`

代码就是银行吗这个简单的，之前ppocr没升级1.1之前是完全正常的，就是旧版还没支持分类文字方向的那个版本

**Comment by MissPenguin** [comment]
目前最新代码上mkldnn是没问题的，可以现拉取最新代码试试哈，如果还有问题可以重新提issue或者reopen这个，我们再继续跟进～
