### ISSUE TITLE
paddle OCR中对于CRNN文字识别模型的训练，是否有支持蒸馏训练大模型固定，训练小模型，我只看到了训练检测网络的大模型固定训练小模型的方式

### ISSUE THREAD

**Issue by gitTongzhen** [PaddlePaddle/PaddleOCR#8072]
paddle OCR中对于CRNN文字识别(rec)模型的训练，是否有支持蒸馏训练大模型固定，训练小模型，我只看到了训练文字检测网络（detection）的大模型参数固定训练小模型的方式，请问一下crnn的训练在哪里支持这种大模型固定参数，训练小模型的训练方式？

**Comment by MissPenguin** [comment]
识别模型我们在迭代过程中发现大模型蒸小模型效果一般，就没集成，可以照着检测自己改一下~
