### ISSUE TITLE
PPOCR-V3 RECOGNITION AUGMENTATION

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8076]
In the paper of ppocrv3 they mentioned textconaug
This augmentation concat 2 different images in a batch to form new images 
this augmentation is activated when i train

I have multiple questions 
1. Does this mean two words will be concatenated from the dataset? 

2. If yes, will the two words create a new word(concat with no space) or create a new sentence(concat with space)?

I'm training on word level so if concating adds space that might cause training issues

**Comment by TuanBC** [comment]
If I understand correctly, the TextConAug is implemented in this function, which as you can check, only concat new word and new label with no space at all: 

https://github.com/PaddlePaddle/PaddleOCR/blob/2909454fb121a002290172525e414f3017923def/ppocr/data/imaug/rec_img_aug.py#L36
