### ISSUE TITLE
Wrong language and not working options

### ISSUE THREAD

**Issue by JonhSilver** [PaddlePaddle/PaddleOCR#8077]
ocr = PaddleOCR(use_angle_cls=True, lang='lt',det=False)

So using Latin.dic instead of Lithuanian, as result all Lithuanian characters is not recognizing

det=False not working so i can disable details info
nor ppocr DEBUG: Namespace
nor in reslt lines (i not need coordinates, just raw text)

**Comment by tink2123** [comment]
Hi, @JonhSilver  "lang=it" means Italian, not Lithuanian. So it can't support Lithuanian characters.
