### ISSUE TITLE
TypeError: '<' not supported between instances of 'tuple' and 'float'

### ISSUE THREAD

**Issue by JonhSilver** [PaddlePaddle/PaddleOCR#8078]
File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\utility.py", line 382, in draw_ocr
    if scores is not None and (scores[i] < drop_score or
TypeError: '<' not supported between instances of 'tuple' and 'float'

**Comment by KutsuyaYuki** [comment]
Im getting the same exact error on both Debian and MacOS 13.

**Comment by AI-07** [comment]
> File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\utility.py", line 382, in draw_ocr if scores is not None and (scores[i] < drop_score or TypeError: '<' not supported between instances of 'tuple' and 'float'

can you please share the code that you are trying to run?

**Comment by polly-morphism** [comment]
happens when u use first example from here https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/whl_en.md

**Comment by asif-ca** [comment]
Solve this by using:

**result = result[0]**

Before using the result variable to create new lists for drawing.
_The error occurs due to nested list._

Notice the `result = result[0]` after the` from PIL import Image`

# draw result
```
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
....
```

**Comment by Carter-Thomas** [comment]
This solution does work for that error, however after that is solved a new one appears in the draw_ocr line. If you use any arguments outside of "img" and "boxes", it will throw an error and not continue.

**Comment by asif-ca** [comment]
The solution is working great for me without any further errors.

@Carter-Thomas  I'm not sure what you mean by  

> If you use any arguments outside of "img" and "boxes"

**Comment by Carter-Thomas** [comment]
I used to get a different TypeError when running this (string and int), but now it seems unrelated somehow. Now it's an OSError : cannot open resource. I'll let you know if I find a solution.
