### ISSUE TITLE
[2022/10/24 19:41:47] ppocr ERROR: lang latin is not support, we only support dict_keys(['en', 'ch']) for layout models

### ISSUE THREAD

**Issue by JonhSilver** [PaddlePaddle/PaddleOCR#8080]
Why you declaring  PPStructure support for 80+ languages?

[2022/10/24 19:41:47] ppocr ERROR: lang latin is not support, we only support dict_keys(['en', 'ch']) for layout models

**Comment by OpenOneV** [comment]
They should declare not-fully supported.

OCR only models might support more languages. But my Latin OCR result gives En letters.

`paddleocr --lang latin --image_dir C:\Users\a_user\Pictures\OIP-C.jpeg`

![image](https://user-images.githubusercontent.com/115529885/197663890-5c8f2674-9179-4e4f-8939-6ac337f71814.png)

![OIP-C](https://user-images.githubusercontent.com/115529885/197663924-36704896-fd69-4257-a167-5bb662f9615b.jpeg)

`paddleocr --lang sdfsdfse --image_dir C:\Users\a_user\Pictures\OIP-C.jpeg`

`AssertionError: param lang must in dict_keys(['ch', 'en', 'korean', 'japan', 'chinese_cht', 'ta', 'te', 'ka', 'latin', 'arabic', 'cyrillic', 'devanagari']), but got sdfsdfse`

**Comment by OpenOneV** [comment]
> 

Well. After a little bit more investigation, I suppose Latin letters are the same as En letters ?

**Comment by JonhSilver** [comment]
@OpenOneV  Latin language is wrong, as it used if i want Lithuanian and also return only latinian characters, if i change latin_dic tu lithuanian symbols it stop works at all

**Comment by OpenOneV** [comment]
@JonhSilver 
https://github.com/PaddlePaddle/PaddleOCR/issues/4415
Is this page helpful?

**Comment by JonhSilver** [comment]
> @JonhSilver #4415 Is this page helpful?
> 
> Assume you have some translator plugin on your browser.

ofcource no, also i dont know chinian language

**Comment by OpenOneV** [comment]
This is translated page img of [#4415](https://github.com/PaddlePaddle/PaddleOCR/issues/4415). 

I really suggest you using browser like Edge/Chrome for built-in webpage translation, if you wish to proceed into this project. This PaddleOCR project is primarily maintained by Chinese programmers. Many important issues are written in Chinese. So, with such a translator, you can then go deeper. 
Meanwhile, a trans-language search engine is in great need for such "international projects" primarily maintained by non-English speaking programmers.

![网页捕获_26-10-2022_17340_github com](https://user-images.githubusercontent.com/115529885/197991452-5992ee21-f0b8-4734-b998-87155df5e797.jpeg)
