### ISSUE TITLE
PPOCRLabel打开目录时（360检测出）修改了注册表信息，是正常的行为吗？

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#8082]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

最近装了一些novelai的自动安装脚本（blbl 搜 novelai 播放量top1的那个）。怀疑可能有通过python腌菜pickle注入的脚本。最近打开PPOCRLabel的时候，360突然识别到对于不常用注册表位置的修改。
如下：
计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths

![屏幕截图 2022-10-25 092047](https://user-images.githubusercontent.com/115529885/197661696-c06039c3-7875-432b-9ff2-b0d441fcd7b7.jpg)

大致行为是：把当前通过PPOCRLabel打开的一些目录写到这个窗口浏览器的”输入地址“（TypedPaths）的注册表地址上。
怀疑如果novelai的注入脚本可能会自动识别本机的深度学习的标注工具，在其中注入脚本以获取标注数据的存储地址。这样可能存在的novelai恶意修改者可以大量获取别人的标注数据。

所以想知道PPOCRLabel打开目录时修改了上述注册表信息，是否是正常行为？

**Comment by Evezerest** [comment]
PPOCRLabel不会直接修改注册表信息，仅仅是打开和写入和标注相关的文件

**Comment by OpenOneV** [comment]
> PPOCRLabel不会直接修改注册表信息，仅仅是打开和写入和标注相关的文件

 是真的不会动注册表信息嘛！那我碰到的这个把数据集路径放到注册表里的行为，岂不是真有novelai腌菜恶意脚本这回事？被我蒙对啦？害怕。

**Comment by OpenOneV** [comment]
![修改的信息](https://user-images.githubusercontent.com/115529885/197980833-6b9becd5-4962-469b-8643-f5775a28f896.png)

**Comment by OpenOneV** [comment]
![Uploading 修改的信息.png…]()

**Comment by OpenOneV** [comment]
![修改的信息](https://user-images.githubusercontent.com/115529885/197981064-4999ae05-e224-4e88-a2ed-dd8b4a06a395.png)
@Evezerest
