### ISSUE TITLE
小数点检测与识别！（漏检）

### ISSUE THREAD

**Issue by lvyongting** [PaddlePaddle/PaddleOCR#8083]
图像标注时把小数点、省略号都括起来了，检测的时候省略号会框不住！
对于小数，识别时小数点总会被省略
场景为电表识别
实例图片如下：
图中还有一些小图标、小字也经常检测不到，还请大佬指一指调优方向。
相关数据集十一月会在飞浆平台共享。
![666](https://user-images.githubusercontent.com/36529870/197667361-00c1dd83-87f2-4969-a866-ae6805e0a9cf.jpg)

![dianzhen3](https://user-images.githubusercontent.com/36529870/197667303-370f4bc2-2860-4440-81b3-82c0031cecac.jpg)

**Comment by LDOUBLEV** [comment]
建议加载PaddleOCR的模型，在你的电表场景上做预训练，另外，也可以参考paddleOCR里一些案例：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/applications

**Comment by yoeaki** [comment]
看一下inference_args.md，调低这两个参数值看看det_db_thresh、det_db_box_thresh，有效果的话回来回复情况

**Comment by yoeaki** [comment]
看一下inference_args.md，调低这两个参数值看看det_db_thresh、det_db_box_thresh，有效果的话回来回复情况
