### ISSUE TITLE
ppocrlabel recognize 崩溃

### ISSUE THREAD

**Issue by heyuqi1970** [PaddlePaddle/PaddleOCR#8084]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Macos BigSur 11.7
- 版本号/Version：Paddle：  2.32, PaddleOCR： 2.6.1.0, PyQt5 :  5.15.7, PyQt5-Qt5:  5.15.2, PyQt5-sip:  12.11.0
问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel
- 完整报错/Complete Error Message：
```
 File "/opt/anaconda3/envs/pythonProject/lib/python3.8/site-packages/PPOCRLabel/libs/hashableQListWidgetItem.py", line 37, in __init__
    super(HashableQListWidgetItem, self).__init__(*args)
TypeError: arguments did not match any overloaded call:
  QListWidgetItem(parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'tuple'
  QListWidgetItem(str, parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'tuple'
  QListWidgetItem(QIcon, str, parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'tuple'
  QListWidgetItem(QListWidgetItem): argument 1 has unexpected type 'tuple'
zsh: abort      PPOCRLabel
```

**Comment by LUOQING1994** [comment]
@LDOUBLEV 我也遇见了同样的问题
![image](https://user-images.githubusercontent.com/20340633/198527868-70e56a2a-a7a4-4741-8a83-07754d601cc6.png)

**Comment by HuizhiXu** [comment]
我也遇到了同样的问题，在做完矩形标注之后，点重新识别，会出现如下错误并且退出界面

![截屏2022-11-03 15 27 07](https://user-images.githubusercontent.com/29792978/199666788-24829c54-3b37-4d5c-b23c-1cef970ed430.png)

**Comment by heyuqi1970** [comment]
目前有解决方案了，将paddocr的版本指定在2.6。
