### ISSUE TITLE
同时开启AMP和单机多卡训练DBnet++，loss经常Nan

### ISSUE THREAD

**Issue by hzhuangdy** [PaddlePaddle/PaddleOCR#8085]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
建议先去掉AMP训练

**Comment by hzhuangdy** [comment]
那是不是DBNet++比较不适合使用AMP？我普通训练了20epoch之后用这个模型去做重训开启AMP还是会有同样的问题

**Comment by liuwake** [comment]
Actually, both _DBNet_ and _DBNet++_ have AMP training issues. PaddlePaddle's operator development still has some historical legacy bugs.
