### ISSUE TITLE
对 cpp infer 中 Permute 的疑惑

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#8093]
此处代码的意思更改图片通道并将其放入 `input` 中
https://github.com/PaddlePaddle/PaddleOCR/blob/c29a9e67019e79699e73f0935a9632d4b438efbf/deploy/cpp_infer/src/ocr_det.cpp#L82-L83
但是 permute 函数里似乎没有更改图片的通道，图片的格式依然是 BGR。
https://github.com/PaddlePaddle/PaddleOCR/blob/c29a9e67019e79699e73f0935a9632d4b438efbf/deploy/cpp_infer/src/preprocess_op.cpp#L34-L41

所以，permute 函数在这里是没有作用的吗？

**Comment by LDOUBLEV** [comment]
检测的输入是BGR格式，permute在这里没有起到作用
