### ISSUE TITLE
Layout Analysis Synthetic Dataset

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8094]
I'm training on a non-latin language with rare layout analysis dataset and labelling to get 50k documents will take ages.
So Do you provide or know any data generation tool for layout analysis?

**Comment by LDOUBLEV** [comment]
Try: 
LayoutVAE、LayoutGAN、Layout Generation and Completion with Self-attention、Variational Transformer Networks for Layout Generation

**Comment by bely66** [comment]
Thanks @LDOUBLEV
