### ISSUE TITLE
SVTR vs VitSTR

### ISSUE THREAD

**Issue by Zhang-O** [PaddlePaddle/PaddleOCR#8095]
which algorithm has better performance in padleOCR tests ? @WenmuZhou

**Comment by tink2123** [comment]
SVTR is better, you can compare them in [algorithm_overview](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_overview_en.md#12-text-recognition-algorithms)

<img width="873" alt="image" src="https://user-images.githubusercontent.com/31891223/197767709-3d669f9b-c661-46ee-897e-c164efc65378.png">
