### ISSUE TITLE
CPU环境 ch_pp-ocrv3 模型 开启 enable_mkldnn 后挂掉 coredump

### ISSUE THREAD

**Issue by liangxinhui** [PaddlePaddle/PaddleOCR#8098]
我部署了docker环境，

通过 PaddleHub 的 Serving 启动 PaddleOCR 模型

当启动 `ch_pp-ocrv3 （version：1.0.0）`模型时，
- 如果 `enable_mkldnn=false`，能正常识别。
- **如果`enable_mkldnn=true`, 程序运行时直接down掉。**

同样的环境，启动 `chinese_ocr_db_crnn_server ` 和 `chinese_ocr_db_crnn_mobile` 时，不管是否开启`enable_mkldnn `选项都能正常运行。

错误提示：

<pre>
paddlehub-ocr  |  * Serving Flask app 'paddlehub.serving.app_compat' (lazy loading)
paddlehub-ocr  |  * Environment: production
paddlehub-ocr  |    WARNING: This is a development server. Do not use it in a production deployment.
paddlehub-ocr  |    Use a production WSGI server instead.
paddlehub-ocr  |  * Debug mode: off
paddlehub-ocr  |  * Running on all addresses (0.0.0.0)
paddlehub-ocr  |    WARNING: This is a development server. Do not use it in a production deployment.
paddlehub-ocr  |  * Running on http://127.0.0.1:8866
paddlehub-ocr  |  * Running on http://172.28.0.2:8866 (Press CTRL+C to quit)
paddlehub-ocr  | ---    fused 0 elementwise_add with relu activation
paddlehub-ocr  | ---    fused 0 elementwise_add with tanh activation
paddlehub-ocr  | ---    fused 0 elementwise_add with leaky_relu activation
....
paddlehub-ocr  | ---    fused 0 elementwise_mul with relu6 activation
paddlehub-ocr  | ---    fused 0 elementwise_mul with sigmoid activation
<b style='color:red'>paddlehub-ocr exited with code 136</b>

</pre>

相关环境信息如下：
```docker
# Dockerfile
FROM registry.baidubce.com/paddlepaddle/paddle:2.3.2
RUN pip install astroid==2.11.7  dill==0.3.4 multiprocess==0.70.12.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install paddlehub -i https://mirror.baidu.com/pypi/simple
RUN pip install shapely  pyclipper  -i https://pypi.tuna.tsinghua.edu.cn/simple
WORKDIR /paddlehub/

EXPOSE 8866

hub serving start 

# paddle_module_conf.json 在运行时配置
CMD ["hub", "serving" ,"start", "-c " ,"/etc/paddle_module_conf.json"]

```

```bash
pip list
Package             Version        
------------------- ---------------
paddle-bfloat       0.1.7          
paddle2onnx         1.0.1          
paddlefsl           1.1.0          
paddlehub           2.3.0          
paddlenlp           2.4.0          
paddlepaddle        2.3.2          
```

**Comment by LDOUBLEV** [comment]
enable_mkldnn =True只支持在intel的CPU上
你的CPU型号是？

**Comment by liangxinhui** [comment]
> 

我在 `Intel(R) Core(TM) i7-8550U`，`i5-10400`上都试过，都是通过 hyper-v 的 ubuntu 虚拟机试的。

通用的环境，用 `chinese_ocr_db_crnn_server `模型时，开启enable_mkldnn时没有问题。

**Comment by liangxinhui** [comment]
补充一下：

我在 Ubuntu 20.04 虚拟机下（非容器环境），复现了这个问题，通过调试发现，是在

```
~/.paddlehub/modules/ch_pp_ocrv3/module.py
Line：402 行

ch_pp_ocrv3 > module.py > ChPPOCRv3 >_recognize_text

调用  self.rec_predictor.run()
```

时候挂掉的。




```
ch_pp_ocrv3 版本：1.0.0
```
