### ISSUE TITLE
文本识别 如何 “保留原有模型” 识别的基础上 “二次” 加强训练模型？ 我只是想加强一下原有的训练模型，并不是破坏它，这样直接被干报废了。

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#8103]
文本识别 如何 “保留原有模型” 识别的基础上 “二次” 加强训练模型？

原贴： https://github.com/PaddlePaddle/PaddleOCR/issues/8047

因为直接使用预训练模型 对 有些文字匹配 不够精确。比如： 3Dbody 经常变成：BDUody, BDbody,3Dbecy.....更多等等... 所以想加强模型 再优化训练。

操作方法：

通用模型-预训练模型下载：https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_train.tar
通用模型-预训练配置文件：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
python tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./weight/ch_ppocr_server_v2.0_rec_train/best_accuracy	 #接着官方模型训练	

然后预测训练好的结果如下：
   
![1](https://user-images.githubusercontent.com/6648329/197917177-304aa6a2-25cd-4b70-bb44-3483c7311f6d.png)

最后像官方那样 把检测模型与识别模型合并（出问题了，所以的识别都变成了我训练的lable,原有模型的lable没有保留下来如）：
  
![2](https://user-images.githubusercontent.com/6648329/197917648-58cabb55-65dd-47f4-a0ee-e54b2baf996d.png)

问题： 我只是想加强一下原有的训练模型，并不是破坏它，这样直接被干报废了。怎么解决这个问题？？？？？？？？

然后我看了下文档：
	pretrained_model：指预训练模型，是已经训练完成的模型。这时会load预训练模型的参数，但并不会load学习率、优化器以及训练状态等。如果需要finetune，应该使用pretrained。
	checkpoints：指之前训练的中间结果，例如前一次训练到了100个epoch，想接着训练。这时会load尝试所有信息，包括模型的参数，之前的状态等。
	于是我用： checkpoints  来加载模型，直接报错？ 请问如何做才能够不破坏原模型的基础上 二次加强 预训练模型？？？？？

python tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.checkpoints  =./weight/ch_ppocr_server_v2.0_rec_train/best_accuracy	 #接着官方模型训练	（用 checkpoints  来加载方式）
![3](https://user-images.githubusercontent.com/6648329/197918058-9e04d96e-93b7-4c1f-a1ec-5e21919d0877.png)

**Comment by thsno02** [comment]
你标签可能有问题，识别的标签你可能都使用的是 `3Dbody`，所以导致检测框正常，但是识别框不正常（我的推测。因为你单图 infer 结果显示的也是 `3Dbody` 而不是汉字。

**Comment by gg22mm** [comment]
> 
我是想 对原有模型 加强这个 lable 加强原有模型对这个lable的识别，其它的都保留，那当前是只有我加强的部分，再说我也没有官方的数据重新自己训练一遍 ~~

**Comment by thsno02** [comment]
如果是检测模型，你的 label 应该是 `1.jpg\t[....]`；如果是识别模型，你的 label 应该是 `1.jpg\t主动脉`。这样才能保证你在微调/加强模型的时候是正确的。你在

https://user-images.githubusercontent.com/6648329/197917648-58cabb55-65dd-47f4-a0ee-e54b2baf996d.png

中给出的结果显示，你的检测模型是正常工作的，给文本都画上了 bounding box；识别模型没有正常工作，所以文本都被识别成了 `3Dbody` 字样的文本。

**Comment by gg22mm** [comment]
非常感谢，群里大老已经说了不能这样玩，玩不转：
比如你现在有五个场景的数据，训练后之后精度都很好，后面又加了两个场景，如果你直接在你前一版的模型中进行finetune，会导致之前的五个场景预测精度变低	
		现在我们的解决方案是，把5+2的场景数据全部重新训练

**Comment by Lebron-Harden** [comment]
您好，请问您后来是怎么解决的呢？我也遇到了和您一样的问题，也需要在自己的数据集上finetune。我尝试加入了一些自然场景的公开数据集的图片，外加自己的数据图片，发现finetune出来的模型还不如原本的模型。
