### ISSUE TITLE
使用serving部署后，只能本地访问么？

### ISSUE THREAD

**Issue by bxjxxyy** [PaddlePaddle/PaddleOCR#8109]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：乌班图20.0.4
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddle-gpu-2.3.2  paddleocr
使用python的PaddleServing部署完成后，python3 web_service.py --config=config.yml &>log.txt & 服务启动成功。
在本机调用正常。
但是换其他设备远程调用启动的服务，失败。无法连接。想要支持远程访问需要做什么配置么？

**Comment by andyjpaddle** [comment]
需要改一下服务ip https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/pdserving/pipeline_http_client.py#L44

**Comment by bxjxxyy** [comment]
> 需要改一下服务ip https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/pdserving/pipeline_http_client.py#L44

这个文件的请求url的ip我已经改了，就是改了之后还请求不到。确定不是服务器的端口没有开放，因为我自己建一个flask服务器，用相同的端口就可以被访问到。

**Comment by andyjpaddle** [comment]
可以试试更换端口，可能是和其他端口冲突了

**Comment by bxjxxyy** [comment]
> 可以试试更换端口，可能是和其他端口冲突了
奇怪了，之前我试过更换端口，就不起作用，刚刚又试了试就正常了
