### ISSUE TITLE
表格识别 禁用gpu运行

### ISSUE THREAD

**Issue by Jsooooooo** [PaddlePaddle/PaddleOCR#8112]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：pp-structure
- 运行指令/Command Code：
export CUDA_VISIBLE_DEVICES='-1'

python table/predict_table.py \
>     --det_model_dir=inference/ch_PP-OCRv3_det_infer \
>     --rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
>     --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer \
>     --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
>     --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
>     --image_dir=docs/table/table.jpg \
>     --output=../output/table

- 完整报错/Complete Error Message：
![QQ截图20221026160055](https://user-images.githubusercontent.com/45792387/197969560-0e8e2c1e-dca2-4633-bdb4-70d706ad5dfc.jpg)

**Comment by Jsooooooo** [comment]
也没看到这个表格识别参数有禁用GPU的

**Comment by WenmuZhou** [comment]
加上这个可以禁用gpu --use_gpu=false

**Comment by Jsooooooo** [comment]
OK解决
