### ISSUE TITLE
通用卡证的模型已经可以下载了，后续还会出身份证的模型吗？

### ISSUE THREAD

**Issue by scfw** [PaddlePaddle/PaddleOCR#8116]
通用卡证的模型已经可以下载了，后续还会出身份证的模型吗？

**Comment by andyjpaddle** [comment]
敬请期待

**Comment by MyOnlyCat** [comment]
> 通用卡证的模型已经可以下载了，后续还会出身份证的模型吗？

有下载到吗?我看分享的下载地址中并没有通用卡证的

**Comment by KyleWang-Hunter** [comment]
> > 通用卡证的模型已经可以下载了，后续还会出身份证的模型吗？
> 
> 有下载到吗?我看分享的下载地址中并没有通用卡证的

同问，请问在哪里下载的呢？ @andyjpaddle

**Comment by aixuedegege** [comment]
同问，请问在哪里下载的呢？ @andyjpaddle

**Comment by zhimangshi** [comment]
通用卡证类识别模型分类标签是什莫
