### ISSUE TITLE
请问有什么参数设置可以使文本检测结果不交叉重叠？ 

### ISSUE THREAD

**Issue by purplesword** [PaddlePaddle/PaddleOCR#8117]
![samp1](https://user-images.githubusercontent.com/4958024/198043087-1c3acf2a-45c7-4174-be5e-5ef39b18e754.png)
![samp2](https://user-images.githubusercontent.com/4958024/198043113-1171ab6c-7cc8-403b-8865-811ea6acc3c6.png)

就像这样，检测得到的box重叠，导致最后的文本识别结果多一个字。我试了调小det_db_unclip_ratio，但是调小了就有把`7`识别成`/`的概率，并且还是会有交叉，就是交叉变成半个字符（这就使识别结果更糟糕了）。

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04, cuda 11.6
- 版本号/Version：
   - Paddle：2.3.2.post116  
   - PaddleOCR： 2.6.0.2 
   - 问题相关组件/Related components：文本检测模型en_PP-OCRv3_det_infer

**Comment by thsno02** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/4518#issuecomment-955991645 根据作者的说法，是DB的缺陷，只能通过后处理解解决。不过我个人建议可以试试把标注数据的框变小，成为一个个小块，这样应该可以很大程度避免这种问题。

**Comment by LDOUBLEV** [comment]
如果不想重新训练模型，通过后处理解决吧

思路1： 合并 有重合的检测框，判断两个框在同一水平线上并且有重合，就将两个检测框合并为一个

思路2：有重合的时候，判断重合部分，取重合的中间线为新的框边界，重新划分两个框

**Comment by purplesword** [comment]
> 思路1： 合并 有重合的检测框，判断两个框在同一水平线上并且有重合，就将两个检测框合并为一个

我现在的workaround是在整个检测+识别结束后，扔掉跟别的框重合的单个字符。感觉要是能实现这个思路更好。

**Comment by thsno02** [comment]
思路一和思路二在在实际中有一个很明显的弊端，如果文本的大小参差不齐，判断是否执行合并操作的重合区域面积 or 再次划分bounding box 的边界难以界定。不过也可以无脑执行重合，再通过正则对文本进行分区；或者仅使用严格的正则规则筛选识别后的文本，不需要对框进行任何操作。
