### ISSUE TITLE
not find model file path ./inference/ch_ppocr_mobile_v1.1_rec_infer//model

### ISSUE THREAD

**Issue by Yulv-git** [PaddlePaddle/PaddleOCR#812]
下载了infer的模型，但解压后只有 ch_ppocr_mobile_v1.1_rec_infer  ，而不是内含model的ch_ppocr_mobile_v1.1_rec_infer文件夹。

运行
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True

就报错了： not find model file path ./inference/ch_ppocr_mobile_v1.1_rec_infer//model

**Comment by MissPenguin** [comment]
下载下来是一个tar包吗，然后tar -xf *.tar解压的吗

**Comment by Yulv-git** [comment]
> 下载下来是一个tar包吗，然后tar -xf *.tar解压的吗

菜哭，我是下载下来后，Windows上解压后再上传到服务器的~
因有些这样的解压没问题，我就以为是数据的问题。
现在用命令解压的可正常使用了。
谢谢！
