### ISSUE TITLE
How to predict many image at once by using tools/infer/predict_rec.py  ?

### ISSUE THREAD

**Issue by Yosiiiiiiiiiiiiiiii** [PaddlePaddle/PaddleOCR#8124]

**Comment by drenched9** [comment]
add argument "image_dir", which supports single image and image folder.
eg:
python3 tools/infer/predict_rec.py --image_dir="./test_data"

**Comment by Yosiiiiiiiiiiiiiiii** [comment]
@drenched9 thank you ^^
