### ISSUE TITLE
卡证类OCR   检测部分的配置文件是不是缺少了label_list和num_classes

### ISSUE THREAD

**Issue by quliulangle** [PaddlePaddle/PaddleOCR#8125]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我看官方教程中使用的是configs/det/detmv3db.yml，但是这个配置文件里是没有label_list和num_classes这两个参数的啊

**Comment by yangy996** [comment]
看这里https://blog.csdn.net/YY007H/article/details/124491217
