### ISSUE TITLE
请求PPOCR-语义实体识别教程补充信息

### ISSUE THREAD

**Issue by AlenChuan** [PaddlePaddle/PaddleOCR#8135]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8F%91%E7%A5%A8%E5%85%B3%E9%94%AE%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96.md#43-%E8%AF%AD%E4%B9%89%E5%AE%9E%E4%BD%93%E8%AF%86%E5%88%AB

4.3.2没有命令行，请问能否补充？这样无法参考训练过程啊。

**Comment by littletomatodonkey** [comment]
你好，可以参考下这个哈：https://aistudio.baidu.com/aistudio/projectdetail/4823162
抱歉，github上的文档遗漏了，我们补充下
