### ISSUE TITLE
string indices must be integers when using paddleocr

### ISSUE THREAD

**Issue by zfb132** [PaddlePaddle/PaddleOCR#8136]
Please provide the following information to quickly locate the problem

System Environment：Win11 amd64
Version
* Paddle： `2.3.2.post116`
* PaddleOCR： `2.6.1.0`
* Related components：`recovery_to_doc`

Status
- Command Code：`paddleocr --image_dir=D:/test.pdf --type=structure --recovery=true --table=false`
- Complete Error Message：`error in layout recovery image:test, err msg: string indices must be integers`

Also, I have cloned the latest code [6228d1e](https://github.com/PaddlePaddle/PaddleOCR/tree/6228d1ee1364845cd5f4af92f150b2cb0ebaa539) and run the following:  
`python paddleocr.py --image_dir=D:/test.pdf --type=structure --recovery=true --table=false`  
The same error occurred.

**Comment by an1018** [comment]
You can use[ dygraph](https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph) code, and try again

**Comment by zfb132** [comment]
> You can use[ dygraph](https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph) code, and try again

same issue here. I use [d314008](https://github.com/PaddlePaddle/PaddleOCR/tree/d314008fa7732b71dfe1c631030a6b38e3464394) code version. And I delete the try catch expression here.  
https://github.com/PaddlePaddle/PaddleOCR/blob/d314008fa7732b71dfe1c631030a6b38e3464394/paddleocr.py#L709-L716
command  
`python paddleocr.py --image_dir=D:/test.pdf --type=structure --recovery=true --table=false`  
output   
```txt
Traceback (most recent call last):
  File "D:\PaddleOCR\paddleocr.py", line 723, in <module>
    main()
  File "D:\PaddleOCR\paddleocr.py", line 711, in main
    convert_info_docx(img, all_res, args.output, img_name)
  File "D:\PaddleOCR\ppstructure\recovery\recovery_to_doc.py", line 65, in convert_info_docx
    parser.handle_table(region['res']['html'], doc)
TypeError: string indices must be integers
```

**Comment by an1018** [comment]
You should use:
`python paddleocr.py --image_dir=D:/test.pdf --type=structure --recovery=true`

**Comment by zfb132** [comment]
> You should use: `python paddleocr.py --image_dir=D:/test.pdf --type=structure --recovery=true`

@an1018 Yes, I tried it first. But I got an error when recovering a table in my pdf. So I use `--table=false` in order to get a docx output.  
Also, with #8137, we can have a choice to decide whether process the table or not since we do not care about the table content too much sometimes.

**Comment by an1018** [comment]
If we use --table=false，the error will be reported. You can modify [the code](https://github.com/PaddlePaddle/PaddleOCR/blob/d314008fa7732b71dfe1c631030a6b38e3464394/ppstructure/recovery/recovery_to_doc.py#L62) ，if you don't want to restore the table

**Comment by zfb132** [comment]
ok. Thank you very much.
