### ISSUE TITLE
macos pip install error

### ISSUE THREAD

**Issue by Evilys** [PaddlePaddle/PaddleOCR#8138]
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by Evilys** [comment]
Resolved, to use anaconda, do not use pyenv

**Comment by siqingzh** [comment]
windows

**Comment by siqingzh** [comment]
windows: ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects
ERROR: Failed building wheel for Polygon3

**Comment by gg22mm** [comment]
引入这么垃圾的包进来干啥？ lanms-neo 安装都是个问题
