### ISSUE TITLE
SRN文字识别模型出错

### ISSUE THREAD

**Issue by zhangjuncheng24** [PaddlePaddle/PaddleOCR#8142]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10，python3.8.0
- 版本号/Version：Paddle：ocr2.6  PaddleOCR： 问题相关组件/Related components： SRN文字识别模型
- 运行指令/Command Code： python tools/train.py -c configs/rec/rec_r50_fpn_srn.yml
- 完整报错/Complete Error Message：
- 配置文件
![image](https://user-images.githubusercontent.com/111550104/198452673-afd8f195-ab11-4030-906b-2d4b6afb0d95.png)
数据集路径和内容
![image](https://user-images.githubusercontent.com/111550104/198453219-0883a1b5-2d09-4e54-84f8-38bc317b6f9a.png)
出现的问题
![image](https://user-images.githubusercontent.com/111550104/198453433-94ba0881-d8bc-4443-aff1-06a536592e20.png)
不管在配置文件里怎么调整data_dir：的路径都不能正常运行，我推测是不是数据集格式不对或者其他问题。

**Comment by WenmuZhou** [comment]
你需要使用simpledataset
