### ISSUE TITLE
ppocrlabel新需求

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#8146]
请问下，ppocr后期是否支持表单图片的标注（多模态信息标注工具）。
![image](https://user-images.githubusercontent.com/29837553/198549996-239e0567-6aa8-46ea-bc24-94b6587ab276.png)
![image](https://user-images.githubusercontent.com/29837553/198550031-2acecb8d-4e05-4b8a-85a9-afca4e00bc89.png)
![image](https://user-images.githubusercontent.com/29837553/198550135-f1b30d99-1eb1-4c42-9cc3-e930f7d277c0.png)

**Comment by WenmuZhou** [comment]
目前有支撑kie的标注

**Comment by tianchiguaixia** [comment]
就是两个字段之间关联关系可以导出？
![image](https://user-images.githubusercontent.com/29837553/198949585-cfa1d44a-7e1d-43ec-a558-e23e5a7db406.png)
就是可以使用ppocrlabel导出以上数据格式？

**Comment by WenmuZhou** [comment]
re的目前还不支持哈，

**Comment by tianchiguaixia** [comment]
看看能否参考一下UBIAI这个工具设计，可以一键导出xfund和funsd的数据集
![image](https://user-images.githubusercontent.com/29837553/199137825-a9304c53-b2f8-472c-ba08-ac5ca2168bce.png)

https://ubiai.tools/NLP/

**Comment by Evezerest** [comment]
你好，后续会考虑增加RE标注，目前可以先训练SER看一看效果
