### ISSUE TITLE
AI Studio 印章检测问题

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleOCR#8155]
![image](https://user-images.githubusercontent.com/44918749/198917532-387980ad-9333-44d3-a977-da7b9f8fba22.png)
请问下 label_list.txt文件中的标签是什么？

**Comment by xialei2821212670** [comment]
red_seal

**Comment by KyleWang-Hunter** [comment]
> red_seal

是只有一个标签吗？在推理的时候报错
![image](https://user-images.githubusercontent.com/44918749/199154570-cf098f92-ebcd-420a-a069-1de949b5b16b.png)

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/199164969-83c0da59-7e92-4180-aeaa-200649def7a8.png)
这边是否改了

**Comment by KyleWang-Hunter** [comment]
> ![image](https://user-images.githubusercontent.com/57654726/199164969-83c0da59-7e92-4180-aeaa-200649def7a8.png) 这边是否改了
![image](https://user-images.githubusercontent.com/44918749/199165172-c13294ed-b0a0-472a-9fd5-3b13b948fa4f.png)
改了

**Comment by xialei2821212670** [comment]
试下 red_seal改成seal_box

**Comment by xialei2821212670** [comment]
有数据集分享？我目前还没做检测，没有数据量
