### ISSUE TITLE
老师，我训练完ser模型后想导出为推理模型，报了一个keyerror:Backbone,请问是什么原因呢？在线等

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#8158]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by huangjun12** [comment]
方便贴一下完整的报错信息吗
