### ISSUE TITLE
请问RARE可以识别倒的印章？还是要把印章矫正后再RARE识别？并且看文中中PGNet夜没提对印章的文字是否需要矫正？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#8159]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![seall](https://user-images.githubusercontent.com/32585434/198929585-84e0dfad-7b06-4a7f-937b-d2f38e582f9f.jpg)

**Comment by cqray1990** [comment]
@MissPenguin

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 可以参考下这个范例哈

**Comment by cqray1990** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 可以参考下这个范

参考了这个,我看得这个例子没有倒的,全是正的 @huangjun12

**Comment by Gmgge** [comment]
1.可以使用Rotated Object Detection 进行公章校正
2.二阶段公章识别方法，在检测到文字行之后进行放射变换，变成矩形行数据，再进行文本方向分类就行校正
