### ISSUE TITLE
请教一下，怎么做成本地服务器？？？可以在WEB访问那种

### ISSUE THREAD

**Issue by sshappys** [PaddlePaddle/PaddleOCR#8162]
请教一下，怎么做成本地服务器？？？可以在WEB访问那种。
我按这个安装教程，装好了也只是一个本地执行环境
像这样可以生成的页面：https://wenxin.baidu.com/moduleApi/ernieVilg

**Comment by sshappys** [comment]
怎么感觉开源的东西被搞成收费的了。。。。
推荐一个搭建服务器的视频：
https://www.youtube.com/watch?v=CIQwJUM1XXc
随然没那么强大，但可做本地服务器用

**Comment by llwowowowoll** [comment]
用flask、tornado啥的，封装成网络服务

**Comment by sshappys** [comment]
> 用flask、tornado啥的，封装成网络服务

有教程之类的不

**Comment by xialei2821212670** [comment]
fastapi，或者pip install paddleocr,可以直接搭建 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md

**Comment by sshappys** [comment]
> fastapi，或者pip install paddleocr,可以直接搭建 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md

多谢，研究一下。
