### ISSUE TITLE
使用python api进行ocr推理

### ISSUE THREAD

**Issue by dzz10** [PaddlePaddle/PaddleOCR#8163]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：**Windows x64**
- 版本号/Version：Paddle：  PaddleOCR：lite v2.10 ppocrv2 问题相关组件/Related components：无
- 运行指令/Command Code：见代码部分
- 完整报错/Complete Error Message：没有报错，输出为空
所以自己摸索在Windows上用lite运行ppocr，想着也许会快很多
但是对照着c的例子，模型直接没有输出结果。
代码如下：

from paddlelite.lite import *
import cv2
import numpy as np

config = MobileConfig()
config.set_model_from_file("./ch_PP-OCRv2_det_slim_opt.nb")

predictor = create_paddle_predictor(config)
print(predictor.get_version())

c, h, w = 3, 384, 800
image_data = cv2.imread("./1.jpg")
image_data = cv2.resize(image_data, (w, h))
image_data = cv2.cvtColor(image_data, cv2.COLOR_BGR2RGB)
image_data = image_data.transpose((2, 0, 1)) / 255.0

mean = [0.485, 0.456, 0.406]
image_data = image_data - np.array(mean).reshape((3, 1, 1))

scale = [0.229, 0.224, 0.225]
image_data = image_data / np.array(scale).reshape((3, 1, 1))

image_data = image_data.reshape([1, c, h, w]).astype('float32')

input_tensor = predictor.get_input(0)
input_tensor.from_numpy(image_data)
predictor.run()

print(dir(input_tensor))
print(input_tensor.target())

output_tensor = predictor.get_output(0)
output_data = output_tensor.numpy()
print("result data:\n{}".format(output_data))

**Comment by dzz10** [comment]
有没有哪位同仁有过和我一样的想法，并成功的，麻烦给点思路啊。^~^

**Comment by dzz10** [comment]
@huangjun12 有Windows下lite在python使用ppocr的例子吗

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/lite/readme.md 可以参考这个哈
