### ISSUE TITLE
文档校正

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleOCR#8167]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

文档校正也属于OCR领域的一个关键技术，目前发现PaddleOCR中无相关算法，后续是否会增加相关算法支持？谢谢

**Comment by zgsxwsdxg** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> * 运行指令/Command Code：
> * 完整报错/Complete Error Message：
> 
> 文档校正也属于OCR领域的一个关键技术，目前发现PaddleOCR中无相关算法，后续是否会增加相关算法支持？谢谢

还有卡片、证件的自动裁切校正相关算法

**Comment by MissPenguin** [comment]
good point！正在进行中了！欢迎持续关注~也欢迎提供优秀的方法列表，我们可以安排复现，更欢迎广大开发者复现了给PaddleOCR提PR哦~

**Comment by zgsxwsdxg** [comment]
> good point！正在进行中了！欢迎持续关注~也欢迎提供优秀的方法列表，我们可以安排复现，更欢迎广大开发者复现了给PaddleOCR提PR哦~

好的，warpnet是一篇文档校正的，你们可以看看

**Comment by zgsxwsdxg** [comment]
> good point！正在进行中了！欢迎持续关注~也欢迎提供优秀的方法列表，我们可以安排复现，更欢迎广大开发者复现了给PaddleOCR提PR哦~

有的人基于hed分割算法做过实验，先检测出轮廓在找点裁切 https://juejin.cn/post/6844903907001368589

**Comment by zgsxwsdxg** [comment]
> > good point！正在进行中了！欢迎持续关注~也欢迎提供优秀的方法列表，我们可以安排复现，更欢迎广大开发者复现了给PaddleOCR提PR哦~
> 
> 有的人基于hed分割算法做过实验，先检测出轮廓在找点裁切 https://juejin.cn/post/6844903907001368589 face++ 2018 paper DocUNet: Document Image Unwarping via A Stacked U-Net

我想实验下，基于人脸关键点检测的思路做文档、证件、卡片角点的检测，不知思路是否可行？能给点建议不？

**Comment by zgsxwsdxg** [comment]
> good point！正在进行中了！欢迎持续关注~也欢迎提供优秀的方法列表，我们可以安排复现，更欢迎广大开发者复现了给PaddleOCR提PR哦~

这个最新文档校正技术总结，你可以看看 https://github.com/fh2019ustc/Awesome-Document-Image-Rectification.git

**Comment by MissPenguin** [comment]
赞，感谢分享，目前我们在关注DocTr，未来会针对文档矫正做一些工作，您给的总结非常有参考价值👍

关于使用人脸关键点做矫正的思路，目前确实没有这方面的经验，不方便随意给出建议，个人觉得，如果是想做算法创新，可以尝试，如果产业应用，可能还是从现有论文里面找方法比较靠谱🤔

**Comment by zgsxwsdxg** [comment]
> 赞，感谢分享，目前我们在关注DocTr，未来会针对文档矫正做一些工作，您给的总结非常有参考价值👍
> 
> 关于使用人脸关键点做矫正的思路，目前确实没有这方面的经验，不方便随意给出建议，个人觉得，如果是想做算法创新，可以尝试，如果产业应用，可能还是从现有论文里面找方法比较靠谱🤔

你好，顺便问一下，像硬质的卡片如银行卡、名片、身份证，怎么检测到它们的任意凸四边形？有没有些思路？谢谢！我看有人基于hed检测轮廓做，你有什么好的思路不？

**Comment by MissPenguin** [comment]
> 有参考价

有听说过做线段检测的，然后找角点，更具体的策略不是很清楚了。。
