### ISSUE TITLE
使用paddle2onnx转换db++检测模型报错

### ISSUE THREAD

**Issue by heyuhhh** [PaddlePaddle/PaddleOCR#8168]
在使用paddle2onnx转换db++检测模型时，会遇到如下报错：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference/det_db++/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./inference/det_db++/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including deformable_conv,
[ERROR] Due to the unsupported operators, the conversion is aborted.

请问如何解决？

**Comment by MissPenguin** [comment]
看报错信息，是存在不支持的算子，可以到Paddle2ONNX提个issue，会有同学跟进：https://github.com/PaddlePaddle/Paddle2ONNX/issues

**Comment by heyuhhh** [comment]
> 看报错信息，是存在不支持的算子，可以到Paddle2ONNX提个issue，会有同学跟进：https://github.com/PaddlePaddle/Paddle2ONNX/issues

 明白了，谢谢

**Comment by liuhuan-gl** [comment]
请问是什么意思呢？解决了吗
