### ISSUE TITLE
db和db++算法的区别在代码中怎么体现的啊，好像head和neck都用的一样的

### ISSUE THREAD

**Issue by hyybuaa** [PaddlePaddle/PaddleOCR#8170]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/5f06a8068eed3e1755b8ca56004cd46c95ac268d/configs/det/det_r50_db%2B%2B_icdar15.yml#L30 

DB++有ASF
