### ISSUE TITLE
文本识别模型SRN转为推理模型执行predict_rec.py报错，CRNN正常

### ISSUE THREAD

**Issue by InferMaster** [PaddlePaddle/PaddleOCR#8171]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- **_**python tools/infer/predict_rec.py --image_dir="/root/autodl-tmp/paddleocr-2.2_MaxLen/dataset/rec/infer/58.jpg" --rec_model_dir="/root/autodl-tmp/paddleocr-2.2_MaxLen/inference/rec/srn" --rec_algorithm="SRN"**_**
- 
- 完整报错/Complete Error Message：
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 512, 4, 40], X's size = 81920, 'shape' is [-1, 512, 256], known capacity of 'shape' is -131072.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-81920.] (at ..\paddle/fluid/operators/reshape_op.cc:190)
      [operator < reshape2 > error]

![image](https://user-images.githubusercontent.com/49891512/199449923-14430300-3f71-47e4-a3a8-acf154b9b863.png)
![image](https://user-images.githubusercontent.com/49891512/199467802-fc8e91e1-949e-43fb-9105-0bf19c581907.png)

**Comment by tink2123** [comment]
模型导出和推理，请参考如下命令：
导出：
```
python3 tools/export_model.py -c configs/rec/rec_r50_fpn_srn.yml -o Global.pretrained_model=./rec_r50_vd_srn_train/best_accuracy  Global.save_inference_dir=./inference/rec_srn
```
推理：
```
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/word_1.png" --rec_model_dir="./inference/rec_srn/" --rec_image_shape="1,64,256"  --rec_algorithm="SRN" --rec_char_dict_path=./ppocr/utils/ic15_dict.txt  --use_space_char=False
```

**Comment by youde2000** [comment]
这个问题解决了吗？
