### ISSUE TITLE
表格结构识别的标注问题

### ISSUE THREAD

**Issue by bldu** [PaddlePaddle/PaddleOCR#8173]
![image](https://user-images.githubusercontent.com/43374826/199190181-5c368e17-3d4c-4006-a2ac-e2a04ff800b7.png)

我正在制作表格识别的数据集，如上图所示的pipeline中涉及到 Text Coords 和 Cell Coords的概念，请问这两个有什么区别吗？标注Cell Coords该怎么标注呢？

**Comment by MissPenguin** [comment]
表格标注方法参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8

上面的流程图，是表格识别的算法示意图，上半部分的text detection 和 text coords指直接使用OCR引擎（这里用的ppocr模型）检测到的文本区域，这部分不需要标注，直接用现有的ocr模型即可。
