### ISSUE TITLE
Why ppocr_v3 can recognize very long line of text ?

### ISSUE THREAD

**Issue by thangnm99** [PaddlePaddle/PaddleOCR#8174]
I have trained a SVTR recognition model with size 32x320, max_text_length = 25 and i found that my model is bad at long line recognition. The long line is not tend to be appeared so much, but i still want to recognize it correctly. But i also found ppocr_v3 with size 48x320 can still recognize long line easily (i have tried with a 32 x 1500 px image). Anyone can explain me why ?  Is the problem in the training config (data set and model size etc.) or in the pre-processing phase. (resize / split the input) or difference in model architecture.
Thanks.

**Comment by TuanBC** [comment]
I think the main reason is the SARLoss used in PPOCRv3. It acts as a attention mechanism that may generalize well when the input of the model is a long image like that.
