### ISSUE TITLE
ch_PP-OCRv3_rec 无法识别出英文中的空格

### ISSUE THREAD

**Issue by lioArther** [PaddlePaddle/PaddleOCR#8185]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Microsoft Windows 11 操作系统名称：10.0.22000 缺Build 22000
ch_PP-OCRv3_rec	【最新】原始超轻量模型，支持中英文、数字识别	ch_PP-OCRv3_rec_distillation.yml	12.4M	推理模型 

该模型在识别英文中，经常出现无法识别出英文中的空格情况。

![image](https://user-images.githubusercontent.com/27990398/199407855-e2d2f54f-bc82-47b0-93e6-2af5cdc80b2e.png)
![image](https://user-images.githubusercontent.com/27990398/199407872-6b008e06-a5d5-484d-baa6-9e928dd33641.png)

**Comment by LDOUBLEV** [comment]
会有一些badcase
可以尝试把检测框扩大一些去预测，增加unclip_ratio；或者设置use_dilation=True，更大的检测框有助于识别

**Comment by tink2123** [comment]
纯英文环境建议使用英文模型，对空格的效果更好一些。
