### ISSUE TITLE
segmentation fault （core dumped）

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8187]
segmentation fault （core dumped）
![1667370625323](https://user-images.githubusercontent.com/40414529/199414832-709309fb-e0f5-4962-90a5-fa6a4a231a76.png)

**Comment by LDOUBLEV** [comment]
麻烦发下运行的指令

**Comment by 88jun12345** [comment]
![1667526216809](https://user-images.githubusercontent.com/40414529/199867193-d044575f-e9ad-4788-aebe-9fa43ca46fc9.png)
![1667526216809](https://user-images.githubusercontent.com/40414529/199867208-b9b9cd6c-c1b5-4ee5-8957-7dfe01cf38f7.png)
就是运行这个程序，其他没了

**Comment by 88jun12345** [comment]
![1667526216809](https://user-images.githubusercontent.com/40414529/199867263-052b5697-9e53-45f9-80de-869d5353e847.png)
就是运行这个程序，其他没了

**Comment by LDOUBLEV** [comment]
debug看下是在哪报错的，看结果已经输出了
