### ISSUE TITLE
中文训练速度问题

### ISSUE THREAD

**Issue by wpchenit** [PaddlePaddle/PaddleOCR#819]
如何提升训练速度？

数据：使用文档“中文文档文字识别”中Chinese_dataset.rar
GPU：
![image](https://user-images.githubusercontent.com/64248379/94092414-4c0bcc80-fe4d-11ea-8963-3ccf9659b857.png)

训练停止时屏幕打印信息为：
![image](https://user-images.githubusercontent.com/64248379/94092588-bae92580-fe4d-11ea-968e-ffd4e6f8e41d.png)
查看rec_chinese_lite_train.yml，默认epoch_num=3000

全部图片训练耗时约135个小时。

修改epoch_num为30000，同时rec_gt_train.txt数量减少到1万，rec_get_test.txt 减少到1千。
训练96小时时 loss:389.37158，    全部数据时，epoch_num为3000时12个小时内，loss会降低到100以内。

**Comment by tink2123** [comment]
首先不是一定要训练到3000个epoch，观察验证集上的精度不上涨之后，就可以停止训练了。
另外如果训练样本足够复杂，可以减少distort，加快训练速度

**Comment by wpchenit** [comment]
可以理解为loss稳定以后就可以停止训练了吗？
比如：
1万语料时，loss是300-500徘徊，   
11万语料是，loss是30-70徘徊

只要loss稳定，不用关心loss的具体值。 

词典一样的情况下，语料越多loss越小对吗？

**Comment by lmw0320** [comment]
你的总样本量是多少啊？
我的训练集是550W，验证集是10W，跑了48个小时吧，acc可以到0.93+了（我是训练生僻字的模型）。。后面暂停了。。因为感觉生僻字类别数不够，我想搞到1.4W+看看。。目前还卡在合成图片上，因为生僻字太多，合成的时候很多文字都没法正常显示。。

**Comment by wpchenit** [comment]
总样本是开源的Chinese_dataset.rar. **下载地址**：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)  里面的一部分，约11W。
11W aac是0.99+   loss:40左右
1W aac是：0.72+ loss：570左右

**Comment by xxllp** [comment]
厉害了 loss40 还能 0.99

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。

**Comment by izhaolinger** [comment]
> 你的总样本量是多少啊？
> 我的训练集是550W，验证集是10W，跑了48个小时吧，acc可以到0.93+了（我是训练生僻字的模型）。。后面暂停了。。因为感觉生僻字类别数不够，我想搞到1.4W+看看。。目前还卡在合成图片上，因为生僻字太多，合成的时候很多文字都没法正常显示。。

方便问下您训练时是多少块GPU吗？

**Comment by wpchenit** [comment]
已收到您的邮件。
