### ISSUE TITLE
PPOCRLabel点击自动标注立即报错闪退

### ISSUE THREAD

**Issue by weixueman** [PaddlePaddle/PaddleOCR#8194]
在使用PPOCRLabel时，选中图片后，点击自动标注闪退并报错：
  File "D:\NCU\tools\Anaconda3\envs\paddle_env\lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 55, in run
    chars = res[1][0]
IndexError: list index out of range
而且一直出现警告： ppocr WARNING: When args.layout is false, args.ocr is automatically set to false，重新设置模型不生效，就是出现警告

**Comment by weixueman** [comment]
知道是怎么回事了，实际是模型没有识别到任何目标框，此时得到的self.result_dic = [ [ ] ]。而PPOCRLabel\libs\autoDialog.py文件49行代码有问题，没有对检测结果self.result_dic进行有效校验，导致下面代码出现越界异常，从而闪退。

**Comment by gg22mm** [comment]
问题是怎么解决？

**Comment by weixueman** [comment]
> 

要修改源码，你去debug一下源码就知道了，不过这个软件坑确实多，发现了好几个问题，改了一天

**Comment by Evezerest** [comment]
please install ppocrlabel==2.1.3
