### ISSUE TITLE
怎么知道yml配置文件对应使用什么模型

### ISSUE THREAD

**Issue by YFforever2022** [PaddlePaddle/PaddleOCR#8195]
请问怎么知道yml配置文件对应使用什么模型

**Comment by gavinfaimdata** [comment]
look at the title of the config file

**Comment by YFforever2022** [comment]
![z1](https://user-images.githubusercontent.com/111646263/199641381-ead102ce-e915-4a11-8393-766cdf9c8a54.jpg)
比如图片上这样，我是根据这样来选择对应的预训练模型的，这样应该没错吧

ch_PP-OCRv3_det_cml.yml 使用 ch_PP-OCRv3_det_distill_train，训练ch_PP-OCRv3_det训练2600次预测出来的precision:0.3717948717948718

det_mv3_db.yml 使用 MobileNetV3_large_x0_5_pretrained.pdparams，训练5800次预测出来的precision:0

这让我产生了怀疑，也许就是预训练权重不对应导致的

请问文件标题文字相似度高权重文件的就是吗
