### ISSUE TITLE
通过hub serving start启动PaddleHub Serving，能否多个识别模型用同一个端口8866，通过url路径参数区分模型

### ISSUE THREAD

**Issue by waizao** [PaddlePaddle/PaddleOCR#8197]
通过hub serving start启动PaddleHub Serving，能否多个模型用同一个端口8866，通过url路径参数区分模型？
比如同一个网站上提供图片识别，一共有三种模型，模型1为验证码识别，模型2为身份证件识别，模型3为动物识别

**Comment by andyjpaddle** [comment]
不支持同一个端口，需要指定不同端口

**Comment by waizao** [comment]
> 不支持同一个端口，需要指定不同端口

是用paddleocr训练出来的三个模型，这种场景也不支持一个端口部署吗？感觉应该很多人都有这类需求
如果三个模型，分别开启三个端口，相当于开始了三个web服务，对服务器内存资源浪费有点多

**Comment by andyjpaddle** [comment]
不同的模型不支持多端口
