### ISSUE TITLE
艺术字检测

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [PaddlePaddle/PaddleOCR#8199]
![image](https://user-images.githubusercontent.com/27794678/199675791-46868896-4b95-49fc-8dd9-86d7c116ce08.png)
通过什么方法可以检测出红框和绿框两个输出？

**Comment by andyjpaddle** [comment]
需要使用文本检测和文本识别两个模型串联，参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/inference_ppocr.md

**Comment by LUOBO123LUOBO123** [comment]
> 

好的，谢谢
