### ISSUE TITLE
windows使用超轻量模型字典解析错误

### ISSUE THREAD

**Issue by prettyocean85** [PaddlePaddle/PaddleOCR#82]
windows使用超轻量模型预测结果不正确，调试代码发现字典解析错误，在character.py文件line 37 中line = line.decode('utf-8').strip("\n")，由于没有删除“/r”在windows中使用时字典解析错误，

**Comment by tink2123** [comment]
感谢使用，PaddleOCR暂时还没有做windows适配，您的问题可以先使用
`line = line.decode('utf-8').strip('\n').replace('\r', '')` 解决，后续我们会持续优化。
