### ISSUE TITLE
How to change optimizer to SGD? 

### ISSUE THREAD

**Issue by Yosiiiiiiiiiiiiiiii** [PaddlePaddle/PaddleOCR#8202]
SGD is not available on optimizer.py  How to add others optimizer?

**Comment by andyjpaddle** [comment]
可以在这里添加优化器 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/optimizer/optimizer.py，或者使用Momentum

**Comment by andyjpaddle** [comment]
you can add other optimizer in this file https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/optimizer/optimizer.py
