### ISSUE TITLE
运行android项目，找不到deploy/android_demo项目models/ocr_v1_for_cpu/cls_opt_arm.nb

### ISSUE THREAD

**Issue by miaolingzi** [PaddlePaddle/PaddleOCR#821]
下载解压ocr_v1_for_cpu.tar.gz后，缺少cls_opt_arm.nb文件

错误日志如下：
com.baidu.paddle.lite.demo.ocr A/Paddle-Lite: [F 9/24 10:19:20.632 ...odel_parser/naive_buffer/naive_buffer.cc:62 LoadFromFile] Check failed: fp: Unable to open file: /data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/cls_opt_arm.nb
2020-09-24 10:19:20.632 13101-13171/com.baidu.paddle.lite.demo.ocr A/libc: FORTIFY: fseeko: null FILE*
2020-09-24 10:19:20.632 13101-13171/com.baidu.paddle.lite.demo.ocr A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13171 (Predictor Worke), pid 13101 (e.lite.demo.ocr)

**Comment by WenmuZhou** [comment]
已经更新了，再下载看看

**Comment by wangsuicheng** [comment]
这个demo app识别出来的结果好像不太对，里面最简单的5.jpg都识别有问题

**Comment by WenmuZhou** [comment]
> 这个demo app识别出来的结果好像不太对，里面最简单的5.jpg都识别有问题
> 
> @WenmuZhou

贴个结果图看看

**Comment by wangsuicheng** [comment]
![QQ截图20200924180323](https://user-images.githubusercontent.com/17826396/94131390-6f0ba000-fe90-11ea-8fd0-d429a7d2ade9.png)

ch_det_mv3_db_opt.nb
ch_rec_mv3_crnn_opt.nb
用的是这个demo里自带的这两个

**Comment by miaolingzi** [comment]
@WenmuZhou demo的assets目录下面的5.jpg图片确实识别的有问题，请看下面的图片

[https://img-blog.csdnimg.cn/20200924200903929.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21pYW9saW5nemk=,size_16,color_FFFFFF,t_70#pic_center](5.jpg识别以后的图片)

**Comment by miaolingzi** [comment]
> 已经更新了，再下载看看

非常感谢，已经可以运行啦

**Comment by WenmuZhou** [comment]
> > 已经更新了，再下载看看
> 
> 非常感谢，已经可以运行啦

你的结果和上面老哥的是一样的吗

**Comment by WenmuZhou** [comment]
> @WenmuZhou demo的assets目录下面的5.jpg图片确实识别的有问题，请点开下面的图片链接
> 
> [5.jpg识别以后的图片](https://img-blog.csdnimg.cn/20200924200903929.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21pYW9saW5nemk=,size_16,color_FFFFFF,t_70#pic_center)
> 
> [90.jpg识别以后的图片](https://img-blog.csdnimg.cn/20200924202037761.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21pYW9saW5nemk=,size_16,color_FFFFFF,t_70#pic_center)
> 
> [180.jpg识别以后的图片](https://img-blog.csdnimg.cn/20200924202052968.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21pYW9saW5nemk=,size_16,color_FFFFFF,t_70#pic_center)
> 
> [270.jpg识别以后的图片](https://img-blog.csdnimg.cn/20200924202106543.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21pYW9saW5nemk=,size_16,color_FFFFFF,t_70#pic_center)

是个bug，已经提pr修复了https://github.com/PaddlePaddle/PaddleOCR/pull/847

**Comment by miaolingzi** [comment]
> > > 已经更新了，再下载看看
> > 
> > 
> > 非常感谢，已经可以运行啦
> 
> 你的结果和上面老哥的是一样的吗

上面老哥的图看不到，不太确定是不是一样呀

**Comment by wangsuicheng** [comment]
> > > > 已经更新了，再下载看看
> > > 
> > > 
> > > 非常感谢，已经可以运行啦
> > 
> > 
> > 你的结果和上面老哥的是一样的吗
> 
> 上面老哥的图我这边打不开，看不到图的内容，不太确定是不是一样呀

一样的问题

@WenmuZhou  这个demo里的模型nb对于英文识别是没空格的？

**Comment by WenmuZhou** [comment]
> > > > > 已经更新了，再下载看看
> > > > 
> > > > 
> > > > 非常感谢，已经可以运行啦
> > > 
> > > 
> > > 你的结果和上面老哥的是一样的吗
> > 
> > 
> > 上面老哥的图我这边打不开，看不到图的内容，不太确定是不是一样呀
> 
> 一样的问题
> 
> @WenmuZhou 这个demo里的模型nb对于英文识别是没空格的？

近期会更新

**Comment by luqiang6q** [comment]
@WenmuZhou 我下载了9月28号的repository，运行出现错误：LoadFromFile] Check failed: fp: Unable to open file: /data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ch_det_mv3_db_opt.nb

**Comment by WenmuZhou** [comment]
你看看你的/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ 目录下是不是有一个ocr_v1_for_cpu的目录，把里面的东西拷贝到/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/就行

**Comment by luqiang6q** [comment]
嗯嗯 我就是这样解决的


在2020年09月28日 22:01，zhoujun 写道：

你看看你的/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/ 目录下是不是有一个ocr_v1_for_cpu的目录，把里面的东西拷贝到/data/user/0/com.baidu.paddle.lite.demo.ocr/cache/models/ocr_v1_for_cpu/就行

**Comment by lumotime** [comment]
问题原因在 com.baidu.paddle.lite.demo.ocr.Predictor#loadModel(Context appCtx, String modelPath, int cpuThreadNum, String cpuPowerMode) 在拷贝模型文件时将 assets 下模型文件时模型的路径因为嵌套导致路径不一致的问题 仅需要将 assets 文件夹下 models 的存放路径改为以下的方式即可 
![image](https://user-images.githubusercontent.com/66256045/106376618-fedad100-63d1-11eb-861f-da33078b800e.png)

**Comment by mybrew** [comment]
> > > > > > 已经更新了，再下载看看
> > > > > 
> > > > > 
> > > > > 非常感谢，已经可以运行啦
> > > > 
> > > > 
> > > > 你的结果和上面老哥的是一样的吗
> > > 
> > > 
> > > 上面老哥的图我这边打不开，看不到图的内容，不太确定是不是一样呀
> > 
> > 
> > 一样的问题
> > @WenmuZhou 这个demo里的模型nb对于英文识别是没空格的？
> 
> 近期会更新

你好，看到你们发布2.0了。但是对应的android_demo还没有更新。

**Comment by YY007H** [comment]
@WenmuZhou 你好，我试了下1.1的nb模型，好像对英文识别还是没有空格，这个什么时候可以更新一下呢？
