### ISSUE TITLE
请教一个模型泛化能力问题，识别停车场库位号，泛化能力特别差，用类似的字体生成训练，也识别不了

### ISSUE THREAD

**Issue by zkailinzhang** [PaddlePaddle/PaddleOCR#8215]
![8264f815742709533d4536396cd3bae](https://user-images.githubusercontent.com/10251153/200153348-77420d1f-36fa-46c9-a6f6-41e14ee9221e.png)
![c2e74cebf7f867e406e2659b402d5aa](https://user-images.githubusercontent.com/10251153/200153350-0af25dc5-08c4-42b5-8510-4f1bc47b0985.png)
上面是真实的 下面是造的数据，模型还是识别不了真实的数据

**Comment by littletomatodonkey** [comment]
真实场景数据识别的时候，肯定也需要添加真实数据训练的
