### ISSUE TITLE
推理模型转onnx之后再转tensorrt跟直接使用tensorrt预测有差别吗

### ISSUE THREAD

**Issue by heyuhhh** [PaddlePaddle/PaddleOCR#8216]
我这边在使用paddle inference集成的tensorrt时老是会有问题，想问问先转成onnx的话，再转成tensorrt，这种在精度或者速度上有什么损失吗？

**Comment by littletomatodonkey** [comment]
api都支持的话，一般不会有精度损失（输出diff在1e-4以内），但是速度的话需要实测下
