### ISSUE TITLE
老师，请问中标麒麟系统paddleocr识别的字符怎么乱呢？

### ISSUE THREAD

**Issue by 1998wy123** [PaddlePaddle/PaddleOCR#8218]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
相同测试，在其他系统中有乱码现象吗

**Comment by 1998wy123** [comment]
在windows本机正常，在乌班图正常，但在中标麒麟乱码
&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月7日(星期一) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问中标麒麟系统paddleocr识别的字符怎么乱呢？ (Issue #8218)





 
相同测试，在其他系统中有乱码现象吗

**Comment by yangy996** [comment]
看一下字库在麒麟上编码对不对

**Comment by 1998wy123** [comment]
cuda版本装高了


&nbsp;


王云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 老师，请问中标麒麟系统paddleocr识别的字符怎么乱呢？ (Issue #8218)





 
看一下字库在麒麟上编码对不对
