### ISSUE TITLE
版面分析模型的学习率在哪个文件改啊    我看文档里说要改学习率 ，但是我没找到在哪个文件注意*如果训练时显存out memory，将TrainReader中batch_size调小，同时LearningRate中base_lr等比例减小。发布的config均由8卡训练得到，如果改变GPU卡数为1，那么base_lr需要减小8倍

### ISSUE THREAD

**Issue by xuyouqian** [PaddlePaddle/PaddleOCR#8219]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Fissionalist** [comment]
请问是在`configs/picodet/legacy_model/_base_/`下的配置文件里改吗？比如`optimizer_100e.yml`
