### ISSUE TITLE
win10 pip安装失败 ERROR: Failed building wheel for lanms-neo

### ISSUE THREAD

**Issue by zzpl** [PaddlePaddle/PaddleOCR#8220]
系统：win10
python环境：3.7
paddlenlp          2.4.2
paddlepaddle       2.3.2
pip                22.3
setuptools         65.5.0
Shapely            1.8.1.post1

pip安装paddleocr报错：ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by an1018** [comment]
按下面命令试试~
`pip install lanms-neo  -i http://pypi.douban.com/simple --trusted-host pypi.douban.com`

**Comment by zzpl** [comment]
> 
一样的错误，完整信息如下
(venv) D:\Program Files\paddle_NLP>pip install lanms-neo -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
Looking in indexes: http://pypi.douban.com/simple
Collecting lanms-neo
  Downloading http://pypi.doubanio.com/packages/7b/fe/beff7e7e4455cb9f69c5734897ca8552a57f6423b062ec86b2ebc1d79c0d/lanms_neo-1.0.2.tar.gz (39 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lanms-neo
  Building wheel for lanms-neo (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lanms-neo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\lanms
      copying lanms\__init__.py -> build\lib.win-amd64-cpython-37\lanms
      running build_ext
      building 'lanms._C' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lanms-neo
Failed to build lanms-neo
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects
检查了Microsoft Visual C++ 的版本，也是14+
![1667802419266](https://user-images.githubusercontent.com/81473804/200240195-33829d08-76f9-4d12-af78-2229bee23218.png)

**Comment by an1018** [comment]
paddleocr安装的是哪个版本？

**Comment by zzpl** [comment]
> paddleocr安装的是哪个版本？
pip install paddleocr -i https://pypi.douban.com/simple/
pip install "paddleocr>=2.0.1" -i https://pypi.douban.com/simple/
用过上述两种安装命令，同样错误

**Comment by an1018** [comment]
安装2.6.0.3或2.6.0.2试试

**Comment by zzpl** [comment]
> 安装2.6.0.3或2.6.0.2试试

感谢，已经解决了，2.6.0.2安装没问题了，但是2.6.0.3还存在相同问题
