### ISSUE TITLE
环境安装报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#8221]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.7,cuda10.1
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

您好，我的环境安装的时候出现报错，请问这个怎么解决呢？谢谢！
![image](https://user-images.githubusercontent.com/43515926/200215348-ae71c82b-68c1-4032-9c9f-4ae6b9bc8665.png)

**Comment by an1018** [comment]
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/macos-conda.html，选择对应环境使用conda试试呢
