### ISSUE TITLE
每个epoch都需要重新预处理图片数据吗，如果我只有一个数据集2k张图片，只在第一个epoch预处理图片行不行

### ISSUE THREAD

**Issue by hyybuaa** [PaddlePaddle/PaddleOCR#8222]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
如果预处理是固定的，没有随机操作，可以只处理一遍，随机操作可以增加样本的丰富性，根据具体场景选择就可以~

**Comment by hyybuaa** [comment]
> 
那基本还是需要重新处理的了吧 裁剪那部分处理就时随机的了

**Comment by an1018** [comment]
是的，如果场景简单的话，可以自行修改的
