### ISSUE TITLE
slim量化版  and  原始超轻量模型

### ISSUE THREAD

**Issue by alicera** [PaddlePaddle/PaddleOCR#8223]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md#21-%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

slim量化版  and  原始超轻量模型
How about the accuracy for all
How to genrate slim?

**Comment by an1018** [comment]
准确率相差不多，使用slim为了获得更小的模型、速度更快，slim使用教程，可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/slim/quantization/README.md
