### ISSUE TITLE
PP-OCRv3   文本识别算法   and  文本检测算法

### ISSUE THREAD

**Issue by alicera** [PaddlePaddle/PaddleOCR#8227]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_overview.md#12-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95

PP-OCRv3  用哪个  文本识别算法   and  文本检测算法

**Comment by an1018** [comment]
基于db、svtr的优化，具体可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/ppocr_introduction.md#pp-ocrv3
