### ISSUE TITLE
DBnet检测模型纵向文本框检测存在漏检和文本切分检测

### ISSUE THREAD

**Issue by QQQTAO** [PaddlePaddle/PaddleOCR#8228]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddle2.3
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error 
Message：使用ch_ppocr_server_v2.0通用检测模型在垂类场景进行文本检测中存在漏检和整行文本被切分检测，这种情况通过添加垂类场景标注数据或者生成一些纵向检测数据进行finetune训练能否解决这种问题，现在使用的还是官方原版检测模型，也希望能提供一些好的建议。
![QQ截图20221107194900](https://user-images.githubusercontent.com/48081128/200304434-58179a32-5797-4231-b119-bdec922daeb4.jpg)

**Comment by an1018** [comment]
可以尝试：
1）使用PP-OCRv3模型
2）根据测试图片尺寸，调整'det_limit_side_len'参数
3）调整'det_db_thresh'参数
4）可以通过finetune提升垂类效果的

**Comment by QQQTAO** [comment]
> 可以尝试： 1）使用PP-OCRv3模型 2）根据测试图片尺寸，调整'det_limit_side_len'参数 3）调整'det_db_thresh'参数 4）可以通过finetune提升垂类效果的

非常感谢。
