### ISSUE TITLE
如果需要检测的文本区域 占原始图片的比例较小 该如何处理 直接训练检测模型hmean很低

### ISSUE THREAD

**Issue by hyybuaa** [PaddlePaddle/PaddleOCR#8229]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
可以发一些示例图片看看吗
