### ISSUE TITLE
是否可以使用paddlehub的fintune接口对paddleOCR的超轻量模型进行finetune

### ISSUE THREAD

**Issue by wangchichi1999** [PaddlePaddle/PaddleOCR#823]
初学深度学习，对模型的使用不太熟悉，看到ernie可以使用paddlehub的finetune接口直接训练，想知道paddleocr是否可以QAQ

**Comment by MissPenguin** [comment]
paddlehub ocr 只支持预测哈，不支持finetune，finetune的话，可以按照本repo的教程操作，具体参考文档中的“模型训练”章节。

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
