### ISSUE TITLE
数码管检测

### ISSUE THREAD

**Issue by playgit2001** [PaddlePaddle/PaddleOCR#8230]
检测模型使用官方训练完的数码管模型，文字识别使用的是自己训练完的模型。
然后识别两张训练集之外的数码管的图片，识别结果一个没有检测到文字，一个框没有把所有文字包括进来，识别结果不准确。 这两种图片中的数码管都是斜着的。
我是需要重新训练吗，在原有模型的基础上把这两张图片进行单独训练，还是把图片加到大的训练集中，重新训练？

**Comment by an1018** [comment]
如果这2张测试图片，和训练集风格相差比较大，推荐进行finetune训练。但是只用这2张训练，数据量太少。

**Comment by playgit2001** [comment]
如果我做微调训练，需要多少张图片比较合适，微调训练是跟正常训练一样的流程，在已经训练好的模型基础上二次训练是吗？

**Comment by playgit2001** [comment]
@an1018

**Comment by an1018** [comment]
如果场景、识别字符比较简单，可以先使用100张训练finetune，具体finetune流程可以参考这个：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md
