### ISSUE TITLE
万年bug:用gpu推理Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by LeoRainly** [PaddlePaddle/PaddleOCR#8231]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS Linux release 7.9.2009 (Core）
- CUDA 10,2, cudnn 8.0.4
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.1.0 问题相关组件/Related components：
- 运行指令/Command Code：示例paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu true
- 完整报错/Complete Error Message：[2022/11/07 19:11:02] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/liuyu/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/liuyu/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir='./doc/imgs/11.jpg', image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/home/liuyu/.conda/envs/torch36_jq/lib/python3.6/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/home/liuyu/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-Structurev2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=True, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2022/11/07 19:11:05] ppocr INFO: **********./doc/imgs/11.jpg**********

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1667819465 (unix time) try "date -d @1667819465" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 20510 (TID 0x7f338cae8740) from PID 0 ***]

Segmentation fault (core dumped)

我安装了nccl，使用paddle.utils.run_check()和fluid.install_check.run_check()都显示success
运行推理示例代码
paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu false
成功
paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu true
失败

看到有人降了paddle的版本，我使用2.2.2的paddle直接paddle.utils.run_check()不通过
这么多同样问题的，快给个靠谱解决方案吧，求求了

另外，如何使用单卡推理？

**Comment by an1018** [comment]
图片尺寸多大？执行命令前，先执行如下命令试试
`export CUDA_VISIBLE_DEVICES=0 
export OPENBLAS_CORETYPE=ARMV8`

**Comment by LeoRainly** [comment]
> 图片尺寸多大？执行命令前，先执行如下命令试试 `export CUDA_VISIBLE_DEVICES=0 export OPENBLAS_CORETYPE=ARMV8`

图片用的500,500的示例图片，加了这两条命令没用。

**Comment by an1018** [comment]
那在paddle官网核对一下cudnn对应的paddle版本，重新安装
