### ISSUE TITLE
ppocr_keys_v1.txt 缺少多个中文字，这些中文字在常用 3500字中

### ISSUE THREAD

**Issue by Fire-Star** [PaddlePaddle/PaddleOCR#8237]
在预测中文图片时，发现 ppocr_keys_v1.txt 缺少以下简体中文字，请官方补充。

刽
笤
秫
凫
誊
蟥
嘁
蛉

**Comment by Fire-Star** [comment]
重新有程序跑了一遍，相对 常用 3500 字中，ppocr_keys_v1.txt 汇总缺少字：

刽
笤
秫
凫
誊
蟥
嘁
蛉

**Comment by huangjun12** [comment]
好的，收到～
