### ISSUE TITLE
是否有参数可以控制模型框的划分距离

### ISSUE THREAD

**Issue by iwctwbai** [PaddlePaddle/PaddleOCR#824]
可能因为字之间距离较近，经常出现模型框把好几组不应该分在一组的数据框在一起。不知这种问题是否有好的解决方案呢？

**Comment by WenmuZhou** [comment]
可以把图片放大试试，但是这样就会导致速度变慢

**Comment by iwctwbai** [comment]
> 可以把图片放大一下，但是这样就会导致速度变慢

是否可以给一个参数呀 控制像素小于多少才划分在一个模型框内 或者在哪个文件可以自行修改呢？

**Comment by iwctwbai** [comment]
@WenmuZhou 多谢

**Comment by WenmuZhou** [comment]
> > 可以把图片放大一下，但是这样就会导致速度变慢
> 
> 是否可以给一个参数呀 控制像素小于多少才划分在一个模型框内 或者在哪个文件可以自行修改呢？

这个没办法，估计是检测的时候就检测成一个了，没法很好划分，可以标注的时候标注分开，然后finetune一下
