### ISSUE TITLE
ppocrv3 detection inference

### ISSUE THREAD

**Issue by alicera** [PaddlePaddle/PaddleOCR#8241]
请问我的对ppocrv3 detection inference理解是否正确?

前处理:
1. resize 960x960
2. pixel 除以 255
3.  'std': [0.229, 0.224, 0.225],  'mean': [0.485, 0.456, 0.406],

inference:
1.
pred=
[0.5 0.5 0.5 0.1 0.1 0.1 0.1
 0.5 0.5 0.5 0.1 0.1 0.1 0.1 ]

2. 设定阀值 thres = 0.3

3. 结果转成 BINARY
[1 1 1 0 0 0 0
 1 1 1 0 0 0 0]

4. get the object box
cv::findContours
cv::minAreaRect

**Comment by huangjun12** [comment]
yes
