### ISSUE TITLE
训练报错：cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:307)

### ISSUE THREAD

**Issue by Aristkj** [PaddlePaddle/PaddleOCR#8243]
版本信息：
win10
NVIDIA Quadro M1000M 算力5.0
cuda11.6   cuDNN8.4.0
paddlepaddle-gpu 2.3.2.post116  paddleocr2.6.0.1

运行paddle.utils.run_check()结果如下：
![Uploading image.png…]()

OCR训练时警告:
WARNING: OMP_NUM_THREADS set to 8, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
训练报错：
SystemError: (Fatal) Operator argsort raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:307)

**Comment by Aristkj** [comment]
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W1109 11:19:56.827572  2808 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 11.6, Runtime API Version: 11.6
W1109 11:19:56.827572  2808 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by MissPenguin** [comment]
您好，可以参考这个帖子尝试解决：https://blog.csdn.net/qq_42340965/article/details/127287615
