### ISSUE TITLE
execute the paddle2onnx but got a onnx model of a wrong input shape,and can not be infered by onnxruntime

### ISSUE THREAD

**Issue by aiden-zhang** [PaddlePaddle/PaddleOCR#8244]
run cmd and the fail log are as follows:

paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./ppocr_rec.onnx --opset_version 10 --input_shape_dict="{'x':[1,3,100,200]}" --enable_onnx_checker True
2022-11-09 03:20:39 [WARNING]   [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle 
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Paramters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 10 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2022-11-09 03:20:39 [INFO]      ===============Make PaddlePaddle Better!================
2022-11-09 03:20:39 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s

I have checked the onnx's input shape by netron.app, the result shows that input shape is { 'x', [-1,3,48,1] }, which confused me so much. why it isn's the shape of [1,3,100,200],which I have specifid.
![ppocr_rec_shape_fail](https://user-images.githubusercontent.com/52768483/200731599-7cb685a6-e93d-44b4-a138-7ba6a7b3655b.png)

**Comment by aiden-zhang** [comment]
I deploy the covert onnx model but got the following error messeage:
dl/python/bin/python3.6 /home/ningzhang/Downloads/pycharm-community-2022.1.3/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 40779 --file /home/ningzhang/workspace_193/case_make/tiekeyuan/infer_test/temp1.py
Connected to pydev debugger (build 221.5921.27)
Traceback (most recent call last):
  File "/dl/python/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/dl/python/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:110 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.

my infer script is as follows:
import onnx
import onnxruntime
import numpy as np

if __name__ == '__main__':
    model_path = 'ppocr_rec_zn.onnx'

    input_data = {
        # 'scale_factor': np.zeros((1,2)).astype(np.float32),
        'x': np.zeros((1,3,100,200)).astype(np.float32),
    }
    model = onnx.load(model_path)
    onnx_session = onnxruntime.InferenceSession(model.SerializeToString())
    outputs_data = onnx_session.run([node.name for node in onnx_session.get_outputs()], input_data)

**Comment by MissPenguin** [comment]
It's recommend to submit this issue to [Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX/issues).
