### ISSUE TITLE
关于PPOCRLabel关键信息标注（kie）

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8245]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
- 版本号/Version：Paddle：2.6   
- 运行指令/Command Code：python PPOCRLabel.py --lang ch --kie True
- 标注结束后如何导出成kie需要的训练格式，采用那个脚本进行转化。自制数据集详细的操作流程

**Comment by botastark** [comment]
Label.txt will be already in the required format (SimpleDataset)

**Comment by MissPenguin** [comment]
楼上正解，标注完导出后就是直接可用的格式了

**Comment by LJY6356** [comment]
> 楼上正解，标注完导出后就是直接可用的格式了

"linking"没有这个字段

**Comment by BaiShiqing** [comment]
目前，ppocrlabel只能标注实体识别，还不能标注关系链接。他们现采用的是程序后处理。

**Comment by MissPenguin** [comment]
RE（关系抽取）任务的标注暂不支持
