### ISSUE TITLE
关于kie数据集标注

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8246]
采用PPOCRLabelv2如何生成官方指定的如下数据集格式
zh_train_0.jpg   [{"transcription": "汇丰晋信", "label": "other", "points": [[104, 114], [530, 114], [530, 175], [104, 175]], "id": 1, "linking": []}, {"transcription": "受理时间:", "label": "question", "points": [[126, 267], [266, 267], [266, 305], [126, 305]], "id": 7, "linking": [[7, 13]]}, {"transcription": "2020.6.15", "label": "answer", "points": [[321, 239], [537, 239], [537, 285], [321, 285]], "id": 13, "linking": [[7, 13]]}]

**Comment by MissPenguin** [comment]
照着文档操作，标注完后导出就是这个格式了

**Comment by LJY6356** [comment]
> 照着文档操作，标注完后导出就是这个格式了

"linking"没有这个字段

**Comment by smallhaozigithub** [comment]
同问
 PPOCRLabelv2 做re 关系抽取 怎么标注每个字段的的id与连接信息

**Comment by MissPenguin** [comment]
RE（关系抽取）任务的标注暂不支持
