### ISSUE TITLE
【三日部署直播课】PP-OCRv2/PP-OCRv3在TensorRT、OpenVINO、ONNX Runtime、RKNN、Paddle Inference、Paddle Lite部署实战。覆盖150+热门模型

### ISSUE THREAD

**Issue by leiqing1** [PaddlePaddle/PaddleOCR#8248]
🔥 全场景部署套件 FastDeploy：
1. 目前支持了150+热门CV、NLP、Speech模型的部署。其中OCR模型已经CPU、GPU、Jetson、ARM CPU、飞腾CPU等硬件。
2. 支持TensorRT、OpenVINO、ONNX Runtime、RKNN、Paddle Inference、Paddle lite等。
3. 支持CPU、GPU、Jetson、ARM CPU、瑞芯微NPU、晶晨NPU、恩智浦NPU、飞腾CPU、IPU等九大类硬件，更多硬件能力完善中。
4.  3行代码搞定AI模型部署，一行代码切换不同后端和硬件。
GitHub地址：https://github.com/PaddlePaddle/FastDeploy

🔥 三日直播课：
【直播分享】2022.11.09 20:30～21:30，《覆盖云边端全场景，150+热门模型快速部署》。微信扫码报名
【直播分享】2022.11.10 20:30～21:30，《瑞芯微、晶晨、恩智浦等10+AI硬件部署，直达产业落地》。微信扫码报名
【直播分享】2022.11.10 19:00～20:00，《10+热门模型在RK3588、RK3568部署实战》。微信扫码报名
 <div align="center">
  <img src="https://user-images.githubusercontent.com/54695910/200145290-d5565d18-6707-4a0b-a9af-85fd36d35d13.jpg" width = "120" height = "120" />
  </div>

🔥 OCR部署能力展示。（更多模型，欢迎移步[FastDeply仓库](https://github.com/PaddlePaddle/FastDeploy)）
  <img src="https://user-images.githubusercontent.com/54695910/200783055-96ec564d-da88-4c98-b2d5-922a247dac48.png" />

**Comment by dgx11678832** [comment]
请问有没有回放，我使用ocr_v3版本导出onnx 在导入tensorrt 一直报错。

**Comment by tonglingwen** [comment]
> 请问有没有回放，我使用ocr_v3版本导出onnx 在导入tensorrt 一直报错。

同问请问这个直播是否有回放？
