### ISSUE TITLE
c++部署编译报错，log.txt输出op_repository.cpp:29] Try to create unknown op[GeneralDetectionOp]

### ISSUE THREAD

**Issue by liwei0826** [PaddlePaddle/PaddleOCR#8249]
c++部署编译报错，log.txt输出，求助。。
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralRecOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralRemoteOp
I0100 00:00:00.000000 24103 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000 24103 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000 24103 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000 24103 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000 24103 general_model_service.pb.h:1650] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000 24103 factory.h:155] RAW: Succ insert one factory, tag: PADDLE_INFER, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 24103 paddle_engine.cpp:34] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<PaddleInferenceEngine>->::baidu::paddle_serving::predictor::InferEngine, tag: PADDLE_INFER in macro!
E1107 08:45:34.455158 24103 op_repository.cpp:29] Try to create unknown op[GeneralDetectionOp]
E1107 08:45:34.455222 24103 dag.cpp:146] Failed to get_op, op type[GeneralDetectionOp]
E1107 08:45:34.455230 24103 workflow.cpp:29] Failed initialize dag: workflow1
E1107 08:45:34.455237 24103 manager.h:73] Failed init item: workflow1 at:0!
E1107 08:45:34.455247 24103 pdserving.cpp:195] Failed initialize workflow manager, conf:workdir_8181/workflow.prototxt

**Comment by MissPenguin** [comment]
直接照着文档跑demo的报错吗？做过什么修改吗？
