### ISSUE TITLE
如何通过hub serving 的方式使用1.1版本的推理模型?

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PaddleOCR#825]
使用方式是通过hub启动服务:
hub serving start -m chinese_ocr_db_crnn_server 
如此使用的推理模型的版本,是1.0.1版本.
如何通过hub 使用最新1.1版本的推理模型?

**Comment by MissPenguin** [comment]
后面加上版本号就行，hub serving start -m chinese_ocr_db_crnn_server==1.1.0

**Comment by binwang672012** [comment]
> 后面加上版本号就行，hub serving start -m chinese_ocr_db_crnn_server==1.1.0

是可以, 但是对于英文空格的问题还是没有效果, 要如何处理英文空格的问题.感谢!

**Comment by grasswolfs** [comment]
> > 后面加上版本号就行，hub serving start -m chinese_ocr_db_crnn_server==1.1.0
> 
> 是可以, 但是对于英文空格的问题还是没有效果, 要如何处理英文空格的问题.感谢!

可以试下最新的1.1.1，应该是修复了这个问题
