### ISSUE TITLE
运行python ppocrlabel 报错 cannot import name 'check_and_read' from 'ppocr.utils.utility'

### ISSUE THREAD

**Issue by demi1997** [PaddlePaddle/PaddleOCR#8252]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Evezerest** [comment]
尝试一下安装2.6.0.0的paddleocr whl包

**Comment by bestpower** [comment]
我这边也报错了，已经安装了最新版本的paddleocr，问题信息如下：

系统环境/System Environment：Windos 10 & Python 3.7.9
版本号/Version：Paddle： PaddleOCR： V2.6.1.2
问题相关组件/Related components：ppocr.utils.utility.check_and_read
运行指令/Command Code：python PPOCRLabel.py
完整报错/Complete Error Message：
```txt
Traceback (most recent call last):
  File "PPOCRLabel.py", line 41, in <module>
    from paddleocr import PaddleOCR
  File "D:\DevelopTools\SDK\python3.7.9\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\DevelopTools\SDK\python3.7.9\lib\site-packages\paddleocr\paddleocr.py", line 41, in <module>
    from ppocr.utils.utility import check_and_read, get_image_file_list
ImportError: cannot import name 'check_and_read' from 'ppocr.utils.utility' (..\ppocr\utils\utility.py)
```

**Comment by zack-rgb** [comment]
我这也报这样的错误

**Comment by zack-rgb** [comment]
跟[bestpower] 这个人一样
