### ISSUE TITLE
Deploying rec model after training

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#8257]
I've trained a rec model for Arabic language, then got the inference version of it using ```export_model.py``` ---> after this i replaced the original rec model files with new inference model files like this :
![image](https://user-images.githubusercontent.com/89604782/200906760-9fb2bea9-9738-495d-8694-3c0ef016afa0.png)
then i tried to infer on the same image that were in training to see if the new model is better but it's giving me this error:
```
 InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 512, 8, 44], input[1]'s shape = [1, 512, 1, 352].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:8 != inputs_dims[i][j]:1.] (at C:\home\workspace\Paddle_release\paddle/phi/kernels/funcs/concat_funcs.h:83)
      [operator < concat > error]
```
if tried the same image on the original model or using the arg ```det=False``` i face no errors! why this is happening?

**Comment by amroghoneim** [comment]
Hey Mohie!

We meet again lol.

Can you please guide me through the training process here?
I wanted to try finetuning the recognition model here but I'm still starting out.

**Comment by ftmasadi** [comment]
Hi
Have you had better results working on Paddle OCR than Easyocr? should I spend time on the Paddle?
Please guide me on how I should use my personal dataset.

**Comment by MohieEldinMuhammad** [comment]
paddle is better than easyocr and more robsut in the deployment, its finetuning is more time-consuming and harder than easyocr however
