### ISSUE TITLE
ValueError: could not broadcast input array from shape

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#8259]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： python3 tools/train.py -c ch_det_res18_db_v2.0.yml
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/45280752/200970833-f5142485-450e-4ff9-a253-4342573fe78c.png)

说明：按照官方给的数据示例制定自己的业务场景中文数据，出现所示报错，咨询意见，有可能问题在哪？

**Comment by jingsongliujing** [comment]
你去看看.....2048-1536这张图，应该是这张图的数据有点问题，删除或者修改一下这张图就好了

**Comment by Biaocsu** [comment]
@jingsongliujing 你好，我检查了，这张图没有啥问题。而且有很多类似的报错，请问该报错的原理是啥，没怎么看明白

该图片对应的标签也都有，为啥会报错呢？

**Comment by Biaocsu** [comment]
知道原因了，标注时，标签顺序错乱了
