### ISSUE TITLE
经常漏检单独的数字"1"

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PaddleOCR#826]
使用方式是通过hub启动服务:
hub serving start -m chinese_ocr_db_crnn_server

如果是一组数字识别没问题,  
但对于单独出现的数字"1", 很难被检测和识别到. 
以下是同一图片中的两个单独"1" 都无法被识别出. 而且几乎所有的图片中 , 单独数字"1" 都无法被识别.
![image](https://user-images.githubusercontent.com/53250648/94099912-aeb99400-fe5e-11ea-86fc-2e2765ea4ee3.png)

![image](https://user-images.githubusercontent.com/53250648/94099929-bbd68300-fe5e-11ea-893e-ca8a111e051c.png)

**Comment by MissPenguin** [comment]
目前单字检测确实容易漏，尤其“1”这种面积格外小的，

**Comment by binwang672012** [comment]
> 目前单字检测确实容易漏，尤其“1”这种面积格外小的，

大佬,  有什么好的建议能做下补救么? 这个问题单独处理有点麻烦啊.

**Comment by littletomatodonkey** [comment]
这块可能得单独训练检测，训练集中多包含一些只包含1的这种检测框。
