### ISSUE TITLE
deploy/lite/ocr_db_crnn.cc是否支持x86

### ISSUE THREAD

**Issue by zhangyingbit** [PaddlePaddle/PaddleOCR#8262]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：2.3  PaddleOCR：2.6 问题相关组件/Related components：deploy
- 运行指令/Command Code：deploy/lite/ocr_db_crnn.cc
- 完整报错/Complete Error Message：

由于想使用paddle lite同时兼顾x86和Android的部署，先尝试了paddle lite x86的部署， 

完成部分： 已根据文档https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/lite/readme.md 完成 1 和 2.1, 差别在于将文档中的arm设置替换成了x86

问题： 编译ocr_db_crnn.cc出错，出错的部分为ocr_db_crnn.cc中的函数NeonMeanScale， 这个函数是针对Arm做了一些优化，有没有x86版本呢？
`void NeonMeanScale(const float *din, float *dout, int size,
                   const std::vector<float> mean,
                   const std::vector<float> scale) {
  if (mean.size() != 3 || scale.size() != 3) {
    std::cerr << "[ERROR] mean or scale size must equal to 3" << std::endl;
    exit(1);
  }
  float32x4_t vmean0 = vdupq_n_f32(mean[0]);
  float32x4_t vmean1 = vdupq_n_f32(mean[1]);
  float32x4_t vmean2 = vdupq_n_f32(mean[2]);
  float32x4_t vscale0 = vdupq_n_f32(scale[0]);
  float32x4_t vscale1 = vdupq_n_f32(scale[1]);
  float32x4_t vscale2 = vdupq_n_f32(scale[2]);

  float *dout_c0 = dout;
  float *dout_c1 = dout + size;
  float *dout_c2 = dout + size * 2;

  int i = 0;
  for (; i < size - 3; i += 4) {
    float32x4x3_t vin3 = vld3q_f32(din);
    float32x4_t vsub0 = vsubq_f32(vin3.val[0], vmean0);
    float32x4_t vsub1 = vsubq_f32(vin3.val[1], vmean1);
    float32x4_t vsub2 = vsubq_f32(vin3.val[2], vmean2);
    float32x4_t vs0 = vmulq_f32(vsub0, vscale0);
    float32x4_t vs1 = vmulq_f32(vsub1, vscale1);
    float32x4_t vs2 = vmulq_f32(vsub2, vscale2);
    vst1q_f32(dout_c0, vs0);
    vst1q_f32(dout_c1, vs1);
    vst1q_f32(dout_c2, vs2);

    din += 12;
    dout_c0 += 4;
    dout_c1 += 4;
    dout_c2 += 4;
  }
  for (; i < size; i++) {
    *(dout_c0++) = (*(din++) - mean[0]) * scale[0];
    *(dout_c1++) = (*(din++) - mean[1]) * scale[1];
    *(dout_c2++) = (*(din++) - mean[2]) * scale[2];
  }
}
`

附加信息：tree  Paddle-Lite/build.lite.linux.x86.gcc/inference_lite_lib/demo/cxx/ocr

├── AutoLog
│   ├── auto_log
│   │   ├── autolog.h
│   │   ├── autolog.py
│   │   ├── device.py
│   │   ├── env.py
│   │   ├── __init__.py
│   │   ├── lite_autolog.h
│   │   └── utils.py
│   ├── CMakeLists.txt
│   ├── README.md
│   ├── requirements.txt
│   └── setup.py
├── AutoLog-main.zip
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   ├── 3.10.3
│   │   │   ├── CMakeCCompiler.cmake
│   │   │   ├── CMakeCXXCompiler.cmake
│   │   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   │   ├── CMakeSystem.cmake
│   │   │   ├── CompilerIdC
│   │   │   │   ├── a.out
│   │   │   │   ├── CMakeCCompilerId.c
│   │   │   │   └── tmp
│   │   │   └── CompilerIdCXX
│   │   │       ├── a.out
│   │   │       ├── CMakeCXXCompilerId.cpp
│   │   │       └── tmp
│   │   ├── cmake.check_cache
│   │   ├── CMakeDirectoryInformation.cmake
│   │   ├── CMakeOutput.log
│   │   ├── CMakeTmp
│   │   ├── feature_tests.bin
│   │   ├── feature_tests.c
│   │   ├── feature_tests.cxx
│   │   ├── Makefile2
│   │   ├── Makefile.cmake
│   │   ├── ocr_test.dir
│   │   │   ├── build.make
│   │   │   ├── clipper.cpp.o
│   │   │   ├── cls_process.cc.o
│   │   │   ├── cmake_clean.cmake
│   │   │   ├── crnn_process.cc.o
│   │   │   ├── CXX.includecache
│   │   │   ├── db_post_process.cc.o
│   │   │   ├── DependInfo.cmake
│   │   │   ├── depend.internal
│   │   │   ├── depend.make
│   │   │   ├── flags.make
│   │   │   ├── link.txt
│   │   │   └── progress.make
│   │   ├── Progress
│   │   │   ├── 1
│   │   │   └── count.txt
│   │   ├── progress.marks
│   │   └── TargetDirectories.txt
│   ├── cmake_install.cmake
│   └── Makefile
├── clipper.cpp
├── clipper.hpp
├── cls_process.cc
├── cls_process.h
├── CMakeLists.txt
├── config.txt
├── crnn_process.cc
├── crnn_process.h
├── db_post_process.cc
├── db_post_process.h
├── debug
│   ├── 11.jpg
│   ├── ch_ppocr_mobile_v2.0_cls_opt.nb
│   ├── ch_PP-OCRv3_det_opt.nb
│   ├── ch_PP-OCRv3_rec_opt.nb
│   ├── config.txt
│   ├── libpaddle_light_api_shared.so
│   └── ppocr_keys_v1.txt
├── imgs
│   └── lite_demo.png
├── Makefile
├── ocr_db_crnn.cc
├── prepare.sh
├── readme_ch.md
└── readme.md

**Comment by LDOUBLEV** [comment]
不支持的
