### ISSUE TITLE
裁剪后的图片不包含标注的文本区域，这种数据怎么处理的

### ISSUE THREAD

**Issue by hyybuaa** [PaddlePaddle/PaddleOCR#8263]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by jingsongliujing** [comment]
你用的是检测模型吗？你保存图片看看画出来的框，还有裁剪的坐标对不对

**Comment by hyybuaa** [comment]
> 你用的是检测模型吗？你保存图片看看画出来的框，还有裁剪的坐标对不对
抱歉我说的图片预处理阶段，IAA数据增强后，标注的区域部分被移除了，不在增强后的图片中，可能是由于仿射变换中的平移操作等
