### ISSUE TITLE
英文识别率差,且英文单词间的空格缺失

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PaddleOCR#827]
使用方式是通过hub启动服务:
hub serving start -m chinese_ocr_db_crnn_server

中英文档中,  识别 英文时 准确率不高:
![image](https://user-images.githubusercontent.com/53250648/94099664-158a7d80-fe5e-11ea-8388-bde0b5e3a2eb.png)

而且单词中的空格经常缺失.
![image](https://user-images.githubusercontent.com/53250648/94099808-5f736380-fe5e-11ea-866f-1b8f4ccbf7dd.png)

**Comment by MissPenguin** [comment]
你使用的还是1.0版的模型，纯英文的话，可以使用1.1最新推出的英文识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md#%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B，1.1的通用模型也可以试试：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md#1-%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

**Comment by MissPenguin** [comment]
你使用的还是1.0版的模型，纯英文的话，可以使用1.1最新推出的英文识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md#%E8%8B%B1%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

非纯英文的话，1.1的通用模型也可以试试：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md#1-%E4%B8%AD%E6%96%87%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B

**Comment by MissPenguin** [comment]
另外，chinese_ocr_db_crnn_server是不支持空格的，1.1的模型都支持空格了

**Comment by binwang672012** [comment]
> 另外，chinese_ocr_db_crnn_server是不支持空格的，1.1的模型都支持空格了

hub serving 方式如何使用 1.1 版本 并且支持空格?

**Comment by littletomatodonkey** [comment]
直接调用就是支持的，你可以直接下载使用下

**Comment by nissansz** [comment]
为什么我用v3, paddle2.6还是有这个问题？
英文识别率差,且英文单词间的空格缺失
