### ISSUE TITLE
Jetson nano上部署PaddleOCR模型时，安装依赖时，出现下面错误，请问是什么原因

### ISSUE THREAD

**Issue by Wardled** [PaddlePaddle/PaddleOCR#8270]
**安装命令：** ```pip3 install -r requirerents.txt
尝试使用了以下方法： 
* pip3 install scikit-image 
*  下载scikit-image包，然后再安装
*  更新pip
*  换源
![656c64cbf6a681f49b8c29a9179d5df](https://user-images.githubusercontent.com/117959671/201248894-e5882058-f8a8-4789-9ac0-8b521941b482.jpg)

**Comment by andyjpaddle** [comment]
推荐python3.7
