### ISSUE TITLE
想问下有针对中文论文的版面分析预训练模型吗

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8272]
想问下有针对中文论文的版面分析预训练模型吗，PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config 这个是英文的，对中文效果不是太好

**Comment by andyjpaddle** [comment]
参考这个 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list.md#1-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90%E6%A8%A1%E5%9E%8B

**Comment by 88jun12345** [comment]
谢谢，这个是运行的代码https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md，但是这里没有说明怎么用你给的连接中的模型的方法，想问下如何用起来这些模型呢

**Comment by 88jun12345** [comment]
在哪个地方指定用哪个模型来分析layout和table呢

**Comment by andyjpaddle** [comment]
仔细读读这个文档哈 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/README_ch.md#1-%E7%AE%80%E4%BB%8B
