### ISSUE TITLE
PPOCRV3 识别训练

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#8274]
你好，请问一下，PPOCRV3识别训练过程中，没有出现关于Loss、Recall等数据，这一块是删除了吗？
![image](https://user-images.githubusercontent.com/87969070/201275830-6b712ee2-97d6-4f16-911b-fe304b50f531.png)

**Comment by andyjpaddle** [comment]
数据量太少了，默认配置是每2000iter评估一次

**Comment by Hold-on-li** [comment]
> 数据量太少了，默认配置是每2000iter评估一次

![image](https://user-images.githubusercontent.com/87969070/201277411-014b595d-b134-4d6e-b139-280bb8361194.png)

**Comment by andyjpaddle** [comment]
你的train iter只有1，太少了，改成500也要500epoch才评估一次

**Comment by andyjpaddle** [comment]
train iter是根据训练数据自动算出来的，和batchsize有关，要么增大训练集数量，要么减小batchsize

**Comment by Hold-on-li** [comment]
> train iter是根据训练数据自动算出来的，和batchsize有关，要么增大训练集数量，要么减小batchsize

好的，谢谢

**Comment by MarginGitHub** [comment]
> > 数据量太少了，默认配置是每2000iter评估一次
> 
> ![image](https://user-images.githubusercontent.com/87969070/201277411-014b595d-b134-4d6e-b139-280bb8361194.png)

把那个false的改为true就可以了，你是关掉了训练期间计算metric的功能
