### ISSUE TITLE
db文本检测后处理的时候，cv2输出了内外轮廓，导致外轮廓里包含了内轮廓，这种处理符合文本检测的场景吗？

### ISSUE THREAD

**Issue by hyybuaa** [PaddlePaddle/PaddleOCR#8276]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
contours, _ = cv2.findContours((bitmap * 255).astype(np.uint8),
                                       cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cv2.RETR_LIST是输出所有轮廓的list，文本检测场景是不是只要输出外围轮廓就行了啊cv2.RETR_EXTERNAL，单独存在的内轮廓基本上不包含任何信息

**Comment by BeyondYourself** [comment]
应该是概率图和阈值图吧，然后最终通过可微二值化确定边界

**Comment by hyybuaa** [comment]
> 应该是概率图和阈值图吧，然后最终通过可微二值化确定边界

二值化后需要通过cv2来生成矩形轮廓，我看处理代码中生成了内轮廓

**Comment by BeyondYourself** [comment]
论文中就是这么操作的吧

**Comment by hyybuaa** [comment]
> 论文中就是这么操作的吧

我是觉得文本检测不需要检测内轮廓，而且输出内轮廓还有误召回
