### ISSUE TITLE
版面分析使用picodet在Docbank上训练时报错

### ISSUE THREAD

**Issue by Siri-2001** [PaddlePaddle/PaddleOCR#8278]
python3 tools/train.py -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml --eval

- 系统环境/System Environment：python 3.7.13
Linux version 5.15.0-52-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 9.4.0-1ubuntu120.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #5820.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022
Cuda compilation tools, release 9.1, V9.1.85
- 版本号/Version：Paddle： 2.3.0 PaddleOCR：2.6 问题相关组件/Related components：train
- 运行指令/Command Code：python3 tools/train.py -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml --eval
- 完整报错/Complete Error Message：发现了预训练参数中许多模块不符，无法被加载进来。
- [11/11 12:14:36] ppdet.utils.checkpoint INFO: ['fc.bias', 'fc.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/11 12:14:36] ppdet.utils.checkpoint INFO: The shape [16] in pretrained weight conv1.bn._mean is unmatched with the shape [64] in model neck.bottom_up_blocks.0.blocks.0.conv1.bn._mean. And the weight conv1.bn._mean will not be loaded
[11/11 12:14:36] ppdet.utils.checkpoint INFO: The shape [16] in pretrained weight conv1.bn._variance is unmatched with the shape [64] in model neck.bottom_up_blocks.0.blocks.0.conv1.bn._variance. And the weight conv1.bn._variance will not be loaded
。。。

**Comment by andyjpaddle** [comment]
确保加载的预训练模型和配置文件一致

**Comment by LeonWang91** [comment]
想请问可以使用CDLA的预训练模型直接去运行版面分析测试的命令吗，我也报了上面类似的错误
错误如下：
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/60532543/210127811-71668207-e6a4-4c36-99c3-1a32b59fa9e9.png">
命令如下：
python3 tools/infer.py     -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml     --slim_config configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x2_5_layout.yml     -o weights='/data_1/wangl/LeiWang/Projects/PaddleOCR/pretrained_model/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams'     --infer_img='/data_1/wangl/LeiWang/Projects/PaddleOCR/dataset/1.jpg'     --output_dir=/data_1/wangl/LeiWang/Projects/PaddleOCR/output/     --draw_threshold=0.5

我只替换了weights的内容，没有更改配置文件，好像也没有找到CDLA的配置文件
