### ISSUE TITLE
ppstructure table processing model 'en_ppocr_mobile_v2.0_...' outputs in Chinese

### ISSUE THREAD

**Issue by AI-07** [PaddlePaddle/PaddleOCR#8279]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 18.04.6 LTS
- 版本号/Version：Paddle：  PaddleOCR： 2.3.2.post111 问题相关组件/Related components：ppstructure
- 运行指令/Command Code：
when I run the script with following parameters, it detects both English/Chinese characters and creates the Excel file for the this [file:](https://drive.google.com/file/d/1FsQPoflDXuXd7-iMyPCxshLlEzQdeXPz/view?usp=share_link)

It detects most of the content right but a few as Chinese characters.

[output excel file](https://docs.google.com/spreadsheets/d/1-4XyZfWBPgrq8swZrsTRBSe7Qz7ApTFm/edit?usp=share_link&ouid=114465698495148238032&rtpof=true&sd=true)

```

!python3 table/predict_table.py \
    --det_model_dir=inference_/ch_PP-OCRv3_det_infer \
    --rec_model_dir=inference_/ch_PP-OCRv3_rec_infer  \
    --table_model_dir=inference_/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --image_dir=docs/table/form.jpg \
    --output=../output/table
```
but when I try to run the English models for the same purpose (below command), it outputs[ excel file](https://docs.google.com/spreadsheets/d/1SYr21l9et-Zc3CgupAxG_6tmWRYnWyoa/edit?usp=share_link&ouid=114465698495148238032&rtpof=true&sd=true) in some drivel Chinese text. 

```
!python3 table/predict_table.py \
    --det_model_dir=inference__/en_ppocr_mobile_v2.0_table_det_infer \
    --rec_model_dir=inference__/en_ppocr_mobile_v2.0_table_rec_infer  \
    --table_model_dir=inference__/en_ppstructure_mobile_v2.0_SLANet_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --image_dir=docs/table/form.jpg \
    --output=../output/table
```

Can someone help me what am I doing wrong here?

**Comment by andyjpaddle** [comment]
you should change the `rec_char_dict_path` to english dict

**Comment by AI-07** [comment]
when I change `rec_char_dict_path` to `../ppocr/utils/en_dict.txt`, it throws following error.
```
Traceback (most recent call last):
  File "table/predict_table.py", line 230, in <module>
    main(args)
  File "table/predict_table.py", line 181, in main
    pred_res, _ = table_sys(img)
  File "table/predict_table.py", line 91, in __call__
    copy.deepcopy(img))
  File "table/predict_table.py", line 137, in _ocr
    rec_res, rec_elapse = self.text_recognizer(img_crop_list)
  File "/content/drive/MyDrive/Projects/structural_paddle_ocr/PaddleOCR/tools/infer/predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "/content/drive/MyDrive/Projects/structural_paddle_ocr/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 121, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/content/drive/MyDrive/Projects/structural_paddle_ocr/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 85, in decode
    for text_id in text_index[batch_idx][selection]
  File "/content/drive/MyDrive/Projects/structural_paddle_ocr/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 85, in <listcomp>
    for text_id in text_index[batch_idx][selection]
IndexError: list index out of range
```

**Comment by AI-07** [comment]
hey @WenmuZhou could you please have a look at this issue?

**Comment by WenmuZhou** [comment]
you should change `rec_char_dict_path` to https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppocr/utils/dict/table_dict.txt
