### ISSUE TITLE
paddlepaddle2.0开启enable_mkldnn报错

### ISSUE THREAD

**Issue by iwctwbai** [PaddlePaddle/PaddleOCR#828]
### 报错内容：
`File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 222, in __init__
    super().__init__(postprocess_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 80, in __init__
    utility.create_predictor(args, mode="det")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 121, in create_predictor
    config.set_mkldnn_cache_capacity(10)
AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity'`

### 配置：
`Namespace(cls=False, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/upuni/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=2400, det_model_dir='/Users/upuni/.paddleocr/det', enable_mkldnn=True, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=1500, rec=True, rec_algorithm='CRNN', rec_batch_num=18, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/upuni/.paddleocr/rec/ch', use_angle_cls=False, use_gpu=False, use_space_char=True, use_tensorrt=True, use_zero_copy_run=True)
`

**Comment by littletomatodonkey** [comment]
请确保你的Paddle版本是将mkldnn编译进去的~

**Comment by iwctwbai** [comment]
请问是否windows是默认编译 mac手动编译 我这边测windows是正常的 @littletomatodonkey

**Comment by robbiewongBD** [comment]
请问问题解决了么，我也遇到类似情况，在win下用的2.0.0.0a版本快速安装的

**Comment by littletomatodonkey** [comment]
麻烦试下最新的rc预测库，这个函数是在2.0-beta之后才加入的

**Comment by cole-dda** [comment]
mac下，paddle-2.0.0.rc0也出现相同的错误。

**Comment by lamhoangtung** [comment]
Having the same problem as @cole-dda

**Comment by pynsigrid** [comment]
disable config.set_mkldnn_cache_capacity(), if your OS is mac.
