### ISSUE TITLE
微调ch_PPv2_det模型，自己标注的数据一般是视频封面，大小一般为360*640，也有其他大小，微调后，效果还不如不微调的？这是什么原因呢？

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleOCR#8280]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by 471417367** [comment]
配置参数能看下吗（bs，lr）,什么环境训练的呢（几卡），还有就是数据量多少？训练记录中初次验证时正确率和最终的正确率是多少呢？

**Comment by shumeirao** [comment]
> 

bs:8 lr:0.001 8卡  初次验证准确率80%，最终82%，训练集大概1400，测试900

**Comment by 471417367** [comment]
你这个结果看上去算正常的吧。现在推荐用v3，同样的数据集我都试了下，好一点点。因为我希望检测模型能对旋转后的文本也能检测，所以试了很多模型包括east,sast效果都不理想。还有就是
希望只要是文本框的就尽量都检测出来，多检测了一些非文本框的对后续使用的影响不大。所以优先关注recall召回率，precision反而不是最重要的。
目前还没好的办法提升效果。

shumeirao ***@***.***> 于2022年11月17日周四 09:20写道：
