### ISSUE TITLE
visionlan decode error

### ISSUE THREAD

**Issue by zhaochu-faimdata** [PaddlePaddle/PaddleOCR#8281]
- 系统环境/System Environment：nvidia jetson 
- 版本号/Version： Paddle：2.3 gpu   PaddleOCR：2.6   
- 运行指令/Command Code：
-` python3.6 tools/infer/predict_rec.py --image_dir='test/images/0' --rec_model_dir='./rec_visionlan/' --rec_algorithm='VisionLAN' --rec_image_shape='3,64,256' --rec_char_dict_path='./ppocr/utils/en_dict.txt' --use_space_char=False --use_gpu=False`
- 完整报错/Complete Error Message：
`ppocr INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 653, in main
    rec_res, _ = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "/paddle/EDGE-pipeline/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 884, in __call__
    ) + length[i])].topk(1)[1][:, 0].tolist()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 739, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: 
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   void paddle::imperative::Tracer::TraceOpImpl<paddle::imperative::VarBase>(std::string const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::AttributeMap&, phi::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&, paddle::framework::AttributeMap*, bool)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   paddle::operators::SliceOp::InferShape(paddle::framework::InferShapeContext*) const
4   void phi::funcs::CheckAndUpdateSliceAttrs<int>(phi::DDim, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> >*, std::vector<int, std::allocator<int> >*, std::vector<long, std::allocator<long> >*, std::vector<int, std::allocator<int> >*)
5   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
6   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: When step > 0, end should be greater than start, but received end = 0, start = 25.
  [Hint: Expected end >= start, but received end:0 < start:25.] (at /home/paddle/data/wangye19/tag_release/Paddle/paddle/phi/kernels/funcs/slice_utils.h:74)
  [operator < slice > error]
`

抱歉没有搜到类似的issue，也尝试修改了一些runtime config都没有改变这个error，所以想问一下，是什么导致的或者有什么方向可以尝试debug呢？
谢谢

**Comment by andyjpaddle** [comment]
字典使用错了，参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_visionlan.md#41-python%E6%8E%A8%E7%90%86
