### ISSUE TITLE
关于申威 PaddleOCR推理

### ISSUE THREAD

**Issue by kaaier** [PaddlePaddle/PaddleOCR#8286]
PaddleOCR是否仅支持申威服务器的Py推理，不支持C++
Paddle下只提供了申威的Py编译安装，暂无C++

**Comment by WenmuZhou** [comment]
可以先尝试一下

**Comment by kaaier** [comment]
不行




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月17日 16:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 关于申威 PaddleOCR推理 (Issue #8286) |

可以先尝试一下

**Comment by WenmuZhou** [comment]
有报啥错吗
