### ISSUE TITLE
SVTR Model Accuracy is lower after exporting it

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8287]
Hi Everyone, 

I trained the SVTR model on a 9M images dataset on a custom language using a custom dictionary.

Then I exported the model into an inference model.

When testing the trained model and inference model I got different results where the inference model is extremely worse.
For the same image, I got different confidence scores and different outputs.

I made sure I passed the path to the dictionary when running inference.

What would be the issue, has it happened before?

**Comment by Topdu** [comment]
Is it possible to show the run command and the output in both trained model inference model cases?

**Comment by bely66** [comment]
Resolved using https://github.com/PaddlePaddle/PaddleOCR/issues/8232
