### ISSUE TITLE
弯曲文本（curved text）的识别效果如何？

### ISSUE THREAD

**Issue by turinglife** [PaddlePaddle/PaddleOCR#829]
1. 弯曲文本的识别效果如何?
2. 弯曲且倒置的文本识别效果如何？
3. 特殊符号识别怎么处理？

有哪位验证过的同学可以贴贴图吗？谢谢！

**Comment by MissPenguin** [comment]
目前开源的1.1版模型都不支持弯曲文本，需要支持弯曲文本，可以用repo提供的SAST检测算法+带TPS的识别算法重新训练～

**Comment by PHI6kai** [comment]
> 

TPS？是哪个算法呢

**Comment by sisrfeng** [comment]
Which commit closed this issue?
