### ISSUE TITLE
paddle在docker中版面分析训练一机多卡报错

### ISSUE THREAD

**Issue by 109du28fen** [PaddlePaddle/PaddleOCR#8293]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS Linux release 7.6.1810 (Core)
- 版本号/Version：Paddle： 2.1  PaddleOCR： 问题相关组件/Related components：训练版面分析
- 运行指令/Command Code：
λ 8270ccd5c322 /home/PaddleDetection export CUDA_VISIBLE_DEVICES=0,1,2,3
λ 8270ccd5c322 /home/PaddleDetection python -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml >log/1.txt
- 完整报错/Complete Error Message：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
LAUNCH INFO 2022-11-14 05:59:21,327 -----------  Configuration  ----------------------
LAUNCH INFO 2022-11-14 05:59:21,327 devices: None
LAUNCH INFO 2022-11-14 05:59:21,327 elastic_level: -1
LAUNCH INFO 2022-11-14 05:59:21,327 elastic_timeout: 30
LAUNCH INFO 2022-11-14 05:59:21,327 gloo_port: 6767
LAUNCH INFO 2022-11-14 05:59:21,327 host: None
LAUNCH INFO 2022-11-14 05:59:21,327 job_id: default
LAUNCH INFO 2022-11-14 05:59:21,327 legacy: False
LAUNCH INFO 2022-11-14 05:59:21,327 log_dir: log
LAUNCH INFO 2022-11-14 05:59:21,327 log_level: INFO
LAUNCH INFO 2022-11-14 05:59:21,327 master: None
LAUNCH INFO 2022-11-14 05:59:21,327 max_restart: 3
LAUNCH INFO 2022-11-14 05:59:21,327 nnodes: 1
LAUNCH INFO 2022-11-14 05:59:21,328 nproc_per_node: None
LAUNCH INFO 2022-11-14 05:59:21,328 rank: -1
LAUNCH INFO 2022-11-14 05:59:21,328 run_mode: collective
LAUNCH INFO 2022-11-14 05:59:21,328 server_num: None
LAUNCH INFO 2022-11-14 05:59:21,328 servers: 
LAUNCH INFO 2022-11-14 05:59:21,328 trainer_num: None
LAUNCH INFO 2022-11-14 05:59:21,328 trainers: 
LAUNCH INFO 2022-11-14 05:59:21,328 training_script: 0,1,2,3
LAUNCH INFO 2022-11-14 05:59:21,328 training_script_args: ['tools/train.py', '-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml']
LAUNCH INFO 2022-11-14 05:59:21,328 with_gloo: 0
LAUNCH INFO 2022-11-14 05:59:21,328 --------------------------------------------------
LAUNCH WARNING 2022-11-14 05:59:21,328 Compatible mode enable with args ['--gpus']
WARNING 2022-11-14 05:59:21,329 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2022-11-14 05:59:21,329 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
INFO 2022-11-14 05:59:21,368 launch_utils.py:679] Change selected_gpus into reletive values. --ips:0,1,2,3 will change into relative_ips:[0, 1, 2, 3] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
INFO 2022-11-14 05:59:21,368 launch_utils.py:679] Change selected_gpus into reletive values. --ips:0,1,2,3 will change into relative_ips:[0, 1, 2, 3] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
INFO 2022-11-14 05:59:21,369 launch_utils.py:561] Local start 4 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:57698               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:34500,127.0.0.1:43066,127.0.0.1:54974|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                     0,1,2,3                   |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-11-14 05:59:21,369 launch_utils.py:561] Local start 4 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:57698               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:34500,127.0.0.1:43066,127.0.0.1:54974|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                     0,1,2,3                   |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-11-14 05:59:21,369 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-11-14 05:59:21,369 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-11-14 05:59:34,480 launch_utils.py:343] terminate all the procs
INFO 2022-11-14 05:59:34,480 launch_utils.py:343] terminate all the procs
ERROR 2022-11-14 05:59:34,481 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
ERROR 2022-11-14 05:59:34,481 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-11-14 05:59:38,485 launch_utils.py:343] terminate all the procs
INFO 2022-11-14 05:59:38,485 launch_utils.py:343] terminate all the procs
INFO 2022-11-14 05:59:38,486 launch.py:402] Local processes completed.
INFO 2022-11-14 05:59:38,486 launch.py:402] Local processes completed.

log中报错
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I1114 05:59:25.732843   426 gen_comm_id_helper.cc:205] Server listening on: 127.0.0.1:34500 successful.
I1114 05:59:28.753204   426 nccl_context.cc:83] init nccl context nranks: 4 local rank: 1 gpu id: 1 ring id: 0
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 112, in run
    init_parallel_env()
  File "/home/PaddleDetection/ppdet/engine/env.py", line 44, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/parallel.py", line 315, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
OSError: (External) NCCL error(2), unhandled system error.  Detail: No space left on device
Please try one of the following solutions:
1. export NCCL_SHM_DISABLE=1;
2. export NCCL_P2P_LEVEL=SYS;
3. Increase shared memory by setting the -shm-size option when starting docker container, e.g., setting  -shm-size=2g.

  [Hint: 'ncclSystemError'. A call to the system failed.] (at /paddle/paddle/fluid/platform/collective_helper.cc:100)

**Comment by littletomatodonkey** [comment]
把num worker减少为0看下，看着是共享内存空间不足

**Comment by 109du28fen** [comment]
> 

num worker改为0后还是相同报错
