### ISSUE TITLE
公众号里提供的PaddleOCR交流群二维码过期了

### ISSUE THREAD

**Issue by xienian87** [PaddlePaddle/PaddleOCR#8294]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by littletomatodonkey** [comment]
好的，我们更新下~

**Comment by Evezerest** [comment]
已更新
