### ISSUE TITLE
推理模型打开benchmark后出错！

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#8297]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
将utility.py中参数benchmark打开：
![bug4](https://user-images.githubusercontent.com/84179587/201619428-da7a4820-d5f0-468b-8bee-3ee13764b139.png)
然后使用inference推理模型进行predict_rec.py出现错误：
![bug4-1](https://user-images.githubusercontent.com/84179587/201620493-6df896ef-71b8-4b1e-8f10-5e033c6e7277.png)

**Comment by littletomatodonkey** [comment]
安装下auto_log试下

`pip install auto_log`

**Comment by JavieYuan** [comment]
> 安装下auto_log试下
> 
> `pip install auto_log`
安装会如下报错，而且好像根本就没有auto_log这个包
ERROR: Could not find a version that satisfies the requirement auto_log (from versions: none)
ERROR: No matching distribution found for auto_log

**Comment by littletomatodonkey** [comment]
```下面这种方式试下
git clone https://github.com/LDOUBLEV/AutoLog
cd AutoLog
pip3 install -r requirements.txt
python3 setup.py bdist_wheel
pip3 install ./dist/auto_log-1.0.0-py3-none-any.whl
```

**Comment by littletomatodonkey** [comment]
这个库的地址在这里：https://github.com/LDOUBLEV/AutoLog

**Comment by JavieYuan** [comment]
> ```
> git clone https://github.com/LDOUBLEV/AutoLog
> cd AutoLog
> pip3 install -r requirements.txt
> python3 setup.py bdist_wheel
> pip3 install ./dist/auto_log-1.0.0-py3-none-any.whl
> ```

在本项目环境中安装后会造成和已有paddlepaddle等等其它已有包冲突吗？

**Comment by littletomatodonkey** [comment]
不会

**Comment by JavieYuan** [comment]
> > ```
> > git clone https://github.com/LDOUBLEV/AutoLog
> > cd AutoLog
> > pip3 install -r requirements.txt
> > python3 setup.py bdist_wheel
> > pip3 install ./dist/auto_log-1.0.0-py3-none-any.whl
> > ```
> 
> 在本项目环境中安装后会造成和已有paddlepaddle等等其它已有包冲突吗？

已解决，万分感谢，感谢！！！
