### ISSUE TITLE
PPOCRLabel TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by Prasanna-iq** [PaddlePaddle/PaddleOCR#8298]
-System Environment：ubuntu 22.04
-Version：Paddle：  PaddleOCR：Related components：paddlepaddle-2.4.0rc0
- Command Code：PPOCRLabel --kie True
- Complete Error Message：
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to /home/prasannavenkatesh/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer/en_PP-OCRv3_det_infer.tar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.00M/4.00M [00:05<00:00, 729kiB/s]
download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar to /home/prasannavenkatesh/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer/en_PP-OCRv3_rec_infer.tar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.96M/9.96M [00:14<00:00, 664kiB/s]
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /home/prasannavenkatesh/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.19M/2.19M [00:06<00:00, 331kiB/s]
download https://paddleocr.bj.bcebos.com/ppstructure/models/slanet/en_ppstructure_mobile_v2.0_SLANet_infer.tar to /home/prasannavenkatesh/.paddleocr/whl/table/en_ppstructure_mobile_v2.0_SLANet_infer/en_ppstructure_mobile_v2.0_SLANet_infer.tar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.2M/10.2M [00:21<00:00, 476kiB/s]
download https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_infer.tar to /home/prasannavenkatesh/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_infer/picodet_lcnet_x1_0_fgd_layout_infer.tar
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.1M/10.1M [00:05<00:00, 1.98MiB/s]
[2022/11/14 16:54:24] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /home/prasannavenkatesh/iq_dev/donut-data/batch_1_2_3/images/Invoice_1_batch1.jpg
DirPath in importDirImages is /home/prasannavenkatesh/iq_dev/donut-data/batch_1_2_3/images
Using model from  paddle
can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/prasannavenkatesh/iq_dev/research/experiments/paddle_env/lib/python3.10/site-packages/PPOCRLabel/libs/autoDialog.py", line 58, in run
    strs += "Transcription: " + chars + " Probability: " + str(cond) + \
TypeError: can only concatenate str (not "list") to str

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1668425097 (unix time) try "date -d @1668425097" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e90000c958) received by PID 51544 (TID 0x7f49f39ff640) from PID 51544 ***]

Aborted (core dumped)

**Comment by xbc922** [comment]
change this code to site-packages\PPOCRLabel\libs\autoDialog.py 53~59
                       strs = []
                        for res in self.result_dic:
                            chars = res[1][0]
                            cond = res[1][1]
                            posi = res[0]
                            strs.append(f"Transcription: {chars}  Probability: {cond} Location: {json.dumps(posi)}")

**Comment by xbc922** [comment]
change this code to site-packages\PPOCRLabel\libs\autoDialog.py 53~59
`
                        strs = []
                        for res in self.result_dic:
                            chars = res[1][0]
                            cond = res[1][1]
                            posi = res[0]
                            strs.append(f"Transcription: {chars}  Probability: {cond} Location: {json.dumps(posi)}")
                            print(strs)
`

**Comment by Evezerest** [comment]
please install ppocrlabel==2.1.3

**Comment by Prasanna-iq** [comment]
it worked thanks!!!
