### ISSUE TITLE
ocr识别，有一行没有识别出来

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8299]
- 想问下有没有针对这种情况的模型，或者有其他好的模型嘛
![1668426727820](https://user-images.githubusercontent.com/40414529/201653578-ba1843b7-858f-477b-89c3-88b01b255666.png)
![1668426670320](https://user-images.githubusercontent.com/40414529/201653598-4d7a9d0a-0df4-4566-b458-a2f06ccc948b.png)
想问下有没有针对这种情况的模型，或者有其他好的模型嘛

**Comment by littletomatodonkey** [comment]
1. 可以适当增加预测尺度、减小unlcip ratio可以设置use_dilation=False，看下效果
2. 垂类场景期望更高精度的话，建议在自己的数据集上finetune哈

**Comment by 88jun12345** [comment]
想问下在哪个文件设置 1‘可以适当增加预测尺度、减小unlcip ratio可以设置use_dilation=False，看下效果’

**Comment by 88jun12345** [comment]
@littletomatodonkey 想问下你说的第一点是在哪个文件里更改的

**Comment by jingsongliujing** [comment]
这个建议换一下检测模型：检测模型用DBNet 识别用：SVRT，需要自己小批量的数据进行标注训练精度更高：参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%E5%8D%A1%E8%AF%81%E7%B1%BBOCR.md
