### ISSUE TITLE
大佬 please help -- All images have same detection + recognition result on Jetson AGX Orin 

### ISSUE THREAD

**Issue by gavinfaimdata** [PaddlePaddle/PaddleOCR#8300]
- 系统环境/System Environment：Jetson AGX Orin (Jetpack 5.0)
- Environment: Nvidia-docker 20.x, Python3.6, Cuda 11.4, based on nvcr.io/nvidia/deepstream-l4t:6.1.1-triton base image
- Paddle： 2.3.0, installed from this wheel: https://paddle-inference-lib.bj.bcebos.com/2.3.0/python/Jetson/jetpack4.5_gcc7.5/all/paddlepaddle_gpu-2.3.0-cp36-cp36m-linux_aarch64.whl
- PaddleOCR： tried release versions of 2.4 and 2.6
- Command Code：python3 tools/infer/predict_det.py --image_dir="~/images" --det_model_dir="./inference/det_db_custom/"

The model that I'm using works well under other environments. But under this environment both det and rec are only able to produce the exact same results for every single input. Det always has the exact same bounding boxes, and rec always either predicts "8" or "R". I tried running predict_system.py and predict_det.py on their own and every single image had the exact same result. Using "--use_gpu=False" produces the intended results, but the inference speed is not sufficient.

**Comment by littletomatodonkey** [comment]
You might provide a demo image and we will test it.

**Comment by gavinfaimdata** [comment]
Thanks for the quick response. Here are some sample images.

![2021-12-06_12-17-20_1](https://user-images.githubusercontent.com/106690744/201702309-0565f7dc-9869-4c43-b8ad-6288e1411274.jpg)
![2021-12-04_02-11-56_1](https://user-images.githubusercontent.com/106690744/201702318-27602d33-3d40-456a-9d51-7994155d7c92.jpg)
![2021-12-02_08-35-45_1](https://user-images.githubusercontent.com/106690744/201702328-57834f9d-4c32-430b-8bcf-7c5e2edefb26.jpg)
