### ISSUE TITLE
无法复现ppstructure 的recovery效果

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#8303]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：2.6.  Paddle：  PaddleOCR：2.6 问题相关组件/Related components： ppstructure
- 运行指令/Command Code：
```shell
python paddleocr.py  --type=structure --recovery=true --image_dir=./docs/table/1.png 
```
或者
```shell
paddleocr --image_dir=./docs/table/1.png --type=structure --recovery=true --use_pdf2docx_api=true
```
- 完整报错/Complete Error Message：
本地使用paddleocr.py 的structure模式识别项目自带的1.png 图片， 但是恢复的docx文本版面无法达到项目说明中的效果。
本地版面恢复效果如下：

<img width="531" alt="image" src="https://user-images.githubusercontent.com/35327931/201694293-2cd1b8af-d454-4325-a344-3d882409aee1.png">

**Comment by an1018** [comment]
英文文档推荐使用英文模型，添加`--lang='en`, 详细内容可以参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/quickstart.md#216-%E7%89%88%E9%9D%A2%E6%81%A2%E5%A4%8D)

**Comment by ericosmic** [comment]
> 英文文档推荐使用英文模型，添加`--lang='en`, 详细内容可以参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/quickstart.md#216-%E7%89%88%E9%9D%A2%E6%81%A2%E5%A4%8D)

使用以下命令结果是一样的
```shell
paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure --recovery=true --lang='en'
```

**Comment by dizhenx** [comment]
> ```shell
> paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure --recovery=true --lang='en'
> ```

我用这个命令结果 如下：表格不完整，啥原因？
![QQ截图20230705155307](https://github.com/PaddlePaddle/PaddleOCR/assets/104120998/fe4940b0-b12a-4a32-8a00-aa91902aa00e)
