### ISSUE TITLE
jetson nano 部署paddleocr

### ISSUE THREAD

**Issue by Wardled** [PaddlePaddle/PaddleOCR#8309]
* 系统环境：
python3.7；
paddlepaddle：2.3.2

* 运行指令：pip3 install -r requirement -i https://pypi.tuna.tsinghua.edu.cn/simple
错误如下：

![ff6db91b6155001d58f3ff78fd1e4e0](https://user-images.githubusercontent.com/117959671/201826082-3fe87bd7-80a3-4ef5-a5f3-b9039e3f5228.jpg)

* 尝试方法：
1.换源
2.安装paddleocr==2.6.0.1

**Comment by Wardled** [comment]
> 你看看你本地有没有pip3，可能是pip的问题，尝试先pip install pip3，再用pip3进行安装

你好，有pip3，版本为22.3.1

**Comment by Wardled** [comment]
> 
从这儿开始报错，
![952d914fa317a30fabaf712b12a9c0a](https://user-images.githubusercontent.com/117959671/201875780-74ae5d68-d3b9-4100-b8c5-f5dcfbcc84a0.jpg)

**Comment by jingsongliujing** [comment]
估计那个包Polygon3在jetson nano上编译不了，你去pypi上找找源码包看看能不能自己编译一下试试

**Comment by Wardled** [comment]
> 估计那个包Polygon3在jetson nano上编译不了，你去pypi上找找源码包看看能不能自己编译一下试试

不行呀，我在windows下和服务器上都正常通过了，看错误显示两个包不能通过：lanms-neo和polypon3

**Comment by Wardled** [comment]
> 估计那个包Polygon3在jetson nano上编译不了，你去pypi上找找源码包看看能不能自己编译一下试试
从建立wheel时报错
Building wheel for lanms-neo (pyproject.toml) ... error
.....
Building wheel for Polygon3 (pyproject.toml) ... error
......

**Comment by Caspian0220** [comment]
你好，可以请问一下如何装全依赖吗？我也出现了同样的问题~

**Comment by jingsongliujing** [comment]
依赖的话在根目录里requirements.txt里有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 晚上8:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] jetson nano 部署paddleocr (Issue #8309)




 
你好，可以请问一下如何装全依赖吗？我也出现了同样的问题~

**Comment by Wardled** [comment]
> 你好，可以请问一下如何装全依赖吗？我也出现了同样的问题~

sudo apt-get install python3.7-dev libxml2-dev zlib1g-dev
sudo apt-get update
sudo apt-get upgrade

**Comment by Caspian0220** [comment]
谢谢～我去康康！发自我的 iPhone在 2022年11月18日，20:13，jingsongliu ***@***.***> 写道：﻿
依赖的话在根目录里requirements.txt里有







---原始邮件---

发件人: ***@***.***&gt;

发送时间: 2022年11月18日(周五) 晚上8:10

收件人: ***@***.***&gt;;

抄送: ***@***.******@***.***&gt;;

主题: Re: [PaddlePaddle/PaddleOCR] jetson nano 部署paddleocr (Issue #8309)









 

你好，可以请问一下如何装全依赖吗？我也出现了同样的问题~
