### ISSUE TITLE
中英文通用OCR模型的识别模型不符合规范

### ISSUE THREAD

**Issue by TankAbraham** [PaddlePaddle/PaddleOCR#831]
您好，

在“中英文通用OCR模型（155.1M）”的识别模型的推理模型中，压缩包内并不包含 model 和 params 文件。
对应的下载连接为： https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_infer.tar

**Comment by WenmuZhou** [comment]
我下载了解压是有的呀
![Uploading image.png…]()

**Comment by binwang672012** [comment]
> 我下载了解压是有的呀
> ![image](https://user-images.githubusercontent.com/12406017/94108118-5049e100-fe71-11ea-8d2e-8dad2a0d8481.png)

能否发下这个链接? 非常感谢.

**Comment by WenmuZhou** [comment]
https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_infer.tar

**Comment by fq19851220** [comment]
> https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_infer.tar

windows解压软件的问题，很多人碰到了 最好说明一下

**Comment by TankAbraham** [comment]
@binwang672012 链接都是一样的。

@fq19851220 @WenmuZhou 确实是windows下解压软件的问题。
