### ISSUE TITLE
运行PaddleOCR  C++代码，显存占用很高

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#8311]
运行PaddleOCR  C++代码时，将gpu_mem参数设置成=500
1.使用GPU进行运行推理，加载图片时候，显存先占大约1.3G，然后涨到1.9个G (无论gpu_mem设置多少，都是稳定显存占用1.9G)
2.然后使用Tensorrt运行推理，显存占用大约3.6G。

请问：为什么使用Tensorrt后，显存会占用这么高？      有什么方法能降低显存占用么？

**Comment by jingsongliujing** [comment]
建议把检测和识别模型合起来，可能就比较快了

**Comment by ainndejj11** [comment]
> 建议把检测和识别模型合起来，可能就比较快了

就是运行的检测+识别串联的

**Comment by ainndejj11** [comment]
> 

就是用的检测+识别 串联的，不是快慢，而是想让显存占用的低一些

**Comment by jingsongliujing** [comment]
那就试试模型蒸馏，剪枝，或者用paddlesering,paddle lite或者FastDeploy套件进行推理，paddle提供了不同场景的推理框架，最新的好像是这个，你在仓库里多找找：https://github.com/PaddlePaddle/FastDeploy/blob/develop/README_CN.md
