### ISSUE TITLE
运行中文文档分析预训练模型出现Segmentation fault (core dumped)错误

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8313]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
运行 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md中的7.2 模型推理部分命令如下所示：
python3 deploy/python/infer.py \
    --model_dir=output_inference/picodet_lcnet_x1_0_layout/ \
    --image_file=docs/images/layout.jpg \
    --device=CPU
可以正常运行，将cpu改为gpu出现以下错误，而且这个错误经常出现

![1668503663365](https://user-images.githubusercontent.com/40414529/201879444-b7095443-423f-40b3-aa62-86c4b93e2788.png)
![1668503614168](https://user-images.githubusercontent.com/40414529/201879461-15c72f8a-bc11-419b-aa67-358c8d8157e5.png)

**Comment by jingsongliujing** [comment]
paddle框架的版本要装paddle-gpu，按照官网的方式安装:https://www.paddlepaddle.org.cn/

**Comment by 88jun12345** [comment]
![FP29cHpb0m](https://user-images.githubusercontent.com/40414529/202060909-a7bbd4e3-943e-4bc2-b429-c232f9b122df.jpg)
按照你的指示安装之后，还是报上面的错误

**Comment by jingsongliujing** [comment]
cpu版本的paddle有没有卸载？把cpu版本的paddle卸载再试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月16日(周三) 上午9:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 运行中文文档分析预训练模型出现Segmentation fault (core dumped)错误 (Issue #8313)




 

 按照你的指示安装之后，还是报上面的错误

**Comment by 88jun12345** [comment]
谢谢，可以了
