### ISSUE TITLE
Markdown file can't found.

### ISSUE THREAD

**Issue by vhrehfdl** [PaddlePaddle/PaddleOCR#8316]
The "https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/finetune.md" could not be found.

**Comment by an1018** [comment]
Sorry for the inconvenience,  could you refer to [this document ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md)
