### ISSUE TITLE
pip3 install "paddleocr>=2.6" 在Windows上安装出错！!

### ISSUE THREAD

**Issue by xlnn** [PaddlePaddle/PaddleOCR#8318]
Building wheel for lanms-neo (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lanms-neo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lanms
      copying lanms\__init__.py -> build\lib.win-amd64-cpython-38\lanms
      running build_ext
      building 'lanms._C' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lanms-neo
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-38\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build lanms-neo Polygon3
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by xlnn** [comment]
我找到方法了，用百度的源可以安装成功，清华的源不行！
`pip3 install "paddleocr>=2.6" -i https://mirror.baidu.com/pypi/simple`

**Comment by an1018** [comment]
感谢反馈

**Comment by bomb1990** [comment]
百度镜像好像只更新到2.6.0.1
