### ISSUE TITLE
DB文字检测，对其结果区域最小外接矩形裁剪后，输入stvr识别，经stn之后的矫正效果并不好，可视化stn自己找到的上下边界点，并没有拟合到边缘上，矫正效果也很差。请问有什么好的解决方法吗。

### ISSUE THREAD

**Issue by mingming0611** [PaddlePaddle/PaddleOCR#8319]
DB文字检测，对其结果区域最小外接矩形裁剪后，输入stvr识别，经stn之后的矫正效果并不好，可视化stn自己找到的上下边界点，并没有拟合到边缘上，矫正效果也很差。请问有什么好的解决方法吗。

**Comment by mingming0611** [comment]
> 有效果图吗

![5](https://user-images.githubusercontent.com/113701415/202072394-04f37f7c-7d08-48e1-ba2e-cd6746091135.jpg)
![6](https://user-images.githubusercontent.com/113701415/202072397-a25d116b-2d9e-4948-98b3-e1c330c23e64.jpg)
![20](https://user-images.githubusercontent.com/113701415/202072400-725048dd-a4e6-4a5f-a6d5-e807c3bff3e2.jpg)
![21](https://user-images.githubusercontent.com/113701415/202072404-b27c227c-4c98-4bf0-bce0-524a7ce6da5b.jpg)
![29](https://user-images.githubusercontent.com/113701415/202072408-a3ca4ce7-9324-494a-9b87-ba5fcdb63262.jpg)
![30](https://user-images.githubusercontent.com/113701415/202072412-ffdc04bc-0fcc-4436-b8e2-4aff24d5fea4.jpg)
标点的是stn自己找到点，拟合边界拟合的不好，上面的图片是经tps矫正后的效果，矫正后效果很差，更别说识别了。

**Comment by fishstarr** [comment]
> DB文字检测，对其结果区域最小外接矩形裁剪后，输入stvr识别，经stn之后的矫正效果并不好，可视化stn自己找到的上下边界点，并没有拟合到边缘上，矫正效果也很差。请问有什么好的解决方法吗。

请问怎么可视化呀，谢谢！
