### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_pdserving'

### ISSUE THREAD

**Issue by zhaobingkun** [PaddlePaddle/PaddleOCR#832]
按照文档安装，运行demo的时候报这个错
AttributeError: 'Namespace' object has no attribute 'use_pdserving'

**Comment by zhaobingkun** [comment]
但是我用命令行能跑出来。

![image](https://user-images.githubusercontent.com/3654469/94109787-175f3b80-fe74-11ea-83e8-de054e91d836.png)

**Comment by MissPenguin** [comment]
已修复，拉取最新代码试试

**Comment by zhaobingkun** [comment]
这个错误 可以这么解决，在paddleocr.py中，找到def parse_args():在下面加入下面这行。
parser.add_argument("--use_pdserving", type=bool, default=False)
跑demo没问题。

**Comment by SWHL** [comment]
刚刚拉去develop分支的最新代码，仍然会有这个错误

**Comment by SWHL** [comment]
刚刚拉取了develop分支下的最新代码，仍然有个错误
不过 @zhaobingkun 的做法可以解决这个问题

**Comment by SWHL** [comment]
刚刚拉取了develop分支下的最新代码，仍然有这个错误
不过 @zhaobingkun 的做法可以解决这个问题
