### ISSUE TITLE
3090显卡非常非常慢

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#8322]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
  ubuntu18.04,python3.8

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
  paddleocr                      2.6.1.0
  paddlepaddle-gpu               2.3.2.post111

- 运行指令/Command Code：
   paddleocr --image_dir local/a/images --type ocr
  执行一个1000*1000的图片识别，就需要这么50多秒以上，如果gpu_mem=1000，需要100秒以上

  同一个环境，切换为2070显卡就好一些，需要0.6秒

- 完整报错/Complete Error Message：
<img width="582" alt="screenshot_5536" src="https://user-images.githubusercontent.com/1077830/201922960-9584d666-4aeb-463e-b41a-786f6223a2d0.png">

<img width="603" alt="screenshot_5535" src="https://user-images.githubusercontent.com/1077830/201920528-02d5dfda-7c10-47d1-bbfc-466762353ab1.png">

**Comment by yinlu6** [comment]
矿卡

**Comment by cole-dda** [comment]
这个不是矿卡。
是从官方旗舰店购买的
跑了很多的gpu程序都是非常正常的
使用paddleocr，仅仅是第一个页面的时候需要50多秒，第二个页面就很快了，0.2秒左右
使用2070，第一个页面仅仅需要0.2秒

**Comment by cole-dda** [comment]
都没有开发人员解决实际问题的吗？

**Comment by faquir-sun** [comment]
确实存在这个问题，使用2080TI整体性能要比3090块很多

**Comment by cole-dda** [comment]
根本没有解决问题，关闭了事？
