### ISSUE TITLE
Jetson Deployment for PaddleOCR CANT FIND .WHL

### ISSUE THREAD

**Issue by Joaquinag** [PaddlePaddle/PaddleOCR#8326]
https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/deploy/Jetson
In the paddle ocr jetson deploy tutorial, there is a link to download paddlepaddle_gpu-2.3.0rc0-cp36-cp36m-linux_aarch64.whl., but i cant find the file to download there.

Where can i find paddlepaddle_gpu-2.3.0rc0-cp36-cp36m-linux_aarch64.whl.?

Thank you in advanced

**Comment by gavinfaimdata** [comment]
$ wget https://github.com/Qengineering/Paddle-Jetson-Nano/raw/main/paddlepaddle_gpu-2.0.0-cp36-cp36m-linux_aarch64.whl

**Comment by Joaquinag** [comment]
Solved, 

They have added the 2.3 whl fot jetsons in the download page:

https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html#python
