### ISSUE TITLE
windows下部署出错

### ISSUE THREAD

**Issue by xbsdsongnan** [PaddlePaddle/PaddleOCR#8329]
运行需要默认下载到c盘里基础模型，如果没有网络就出错，怎么注销掉默认下载链接

**Comment by jingsongliujing** [comment]
建议改第52行代码，BASE_DIR = os.path.expanduser("~/.paddleocr/")：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py，重新编译
