### ISSUE TITLE
paddleocr 后续能结合语义识别吗？

### ISSUE THREAD

**Issue by calvinxuman** [PaddlePaddle/PaddleOCR#8331]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
paddleocr 后续能结合语义识别吗

**Comment by huangjun12** [comment]
语义识别可以参考 https://github.com/PaddlePaddle/PaddleNLP
