### ISSUE TITLE
文本检测DB算法请教

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/PaddleOCR#8335]
看了一下PPOCR，DBNet文本检测部分的代码，训练时候使用了step_function函数来计算文本区域的二值化图，为什么预测时候是直接使用概率图然后利用一个固定的阈值0.3来得到二值化图，而没有用到模型预测阈值图结合step_function计算二值图，是为了推理速度的考虑吗？但是这样做对于模型的精度会不会有影响？

**Comment by LDOUBLEV** [comment]
> 是为了推理速度的考虑吗？

是的，不会太影响精度
