### ISSUE TITLE
PPocrLabel标注闪退，

### ISSUE THREAD

**Issue by htaoruan** [PaddlePaddle/PaddleOCR#8337]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version：Paddle：2.3.1    PaddleOCR：2.6.0.1  问题相关组件/Related components：PPOCRLabel   2.1.1
- 运行指令/Command Code：PPOCRLabel     2.1.1
- 完整报错/Complete Error Message：
File "C:\Users\happy\.conda\envs\pytorch\lib\site-packages\PPOCRLabel\libs\canvas.py", line 614, in paintEvent
    p.drawLine(self.prevPoint.x(), 0, self.prevPoint.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'

**Comment by Evezerest** [comment]
please install ppocrlabel==2.1.3
