### ISSUE TITLE
DBNet loss函数

### ISSUE THREAD

**Issue by fengxiaoru** [PaddlePaddle/PaddleOCR#8338]
### DBNet论文中的损失函数：
![image](https://user-images.githubusercontent.com/41059771/202091490-526d7bee-846f-489b-bb5d-1192dafb5e1e.png)
![image](https://user-images.githubusercontent.com/41059771/202091545-59a45f0f-537c-4b47-a2c9-2e20bfbc0420.png)
### paddleocr里db复现代码部分的损失函数：
![image](https://user-images.githubusercontent.com/41059771/202091694-929badf4-e4fa-42da-b2a1-35d178ebf5c5.png)
### **请问，两者不一样的原因是什么呢？**

**Comment by huangjun12** [comment]
paper和源码可能有diff，实现主要参考作者的源码哈
