### ISSUE TITLE
kie中ser训练

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8339]
ser训练中前几轮次损失正常下降，后面就出现nanxxx，但是前几次的eval结果都是0.9以上

![image](https://user-images.githubusercontent.com/67177370/202097432-dc497365-a3ba-4a0f-9190-a448b786c2f8.png)

**Comment by jingsongliujing** [comment]
这个是梯度消失问题，把lr调小一点

**Comment by taojing7** [comment]
老哥我和你同样的ser任务，遇到了同样的loss nanxxx问题，请问你解决了吗，862978601@qq.com方便加个联系方式交流一下吗

**Comment by Kevinlsy** [comment]
遇到相同的问题。有解决吗？

**Comment by ariefwijaya** [comment]
@jingsongliujing Hi, do you have solution for it?
