### ISSUE TITLE
Detecting special characters(←→↑↓/~. ) in english using pretrained model

### ISSUE THREAD

**Issue by manshulgoel** [PaddlePaddle/PaddleOCR#8340]
Hi Team, 

I am new to Machine learning. Request your help with how to make paddleOCR detect special characters like ←→↑↓/~.  apart from English and numeric characters.
Kindly help with steps. I have shared sample image as well.
![image](https://user-images.githubusercontent.com/45064959/202109529-9646d72b-1742-499b-8091-d183106e6a83.png)

**Comment by jingsongliujing** [comment]
you can try it:  https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_server&en_category=TextRecognition

**Comment by manshulgoel** [comment]
It doesn't have great accuracy, I tried multiple pictures on the link above but didn't show good results.

**Comment by jingsongliujing** [comment]
Oh,sorry,That's the Chinese scene model.Maybe you can find a model suitable for your English scene here：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md

**Comment by manshulgoel** [comment]
Hi,
I tried this solution provided but it has very poor accuracy on this image. 

![IMG-20220921-WA0011](https://user-images.githubusercontent.com/45064959/202634834-dfb8212e-0d59-46f4-ad57-ea90cbd34c0c.jpg)
