### ISSUE TITLE
请问多个数据集的话 我应该怎么在yml文件中放呢 

### ISSUE THREAD

**Issue by ic1031** [PaddlePaddle/PaddleOCR#8341]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by cumthxy** [comment]
我觉得可以把多个数据集的train.txt  dev.txt合并到一起就行了。yml就是读取的txt文件来判断图片的路径。

**Comment by huangjun12** [comment]
按list组织，参考 https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/configs/det/det_r50_vd_sast_totaltext.yml#L62
