### ISSUE TITLE
关于Batch_size参数

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleOCR#8342]
你好，请问一下，训练集的batch_size置为16，验证集的batch_size置为128，这种设置影响最终结果吗？我的图片只有200张左右，训练集的batch_size过大时，就无法显示Loss了。

**Comment by jingsongliujing** [comment]
batch_size一般显卡我觉得只能设置为4或者8，最多16

**Comment by Hold-on-li** [comment]
> batch_size一般显卡我觉得只能设置为4或者8，最多16

我用的时PPOCR-V3-Rec默认128都能跑，我的算力只有6.1

**Comment by huangjun12** [comment]
> 

不影响
