### ISSUE TITLE
缺乏 SVTRLabelDecode 的实现？

### ISSUE THREAD

**Issue by willpat1213** [PaddlePaddle/PaddleOCR#8343]
- 系统环境/System Environment：Docker [2.1.3-gpu-cuda11.2-cudnn8](https://hub.docker.com/layers/paddlepaddle/paddle/2.1.3-gpu-cuda11.2-cudnn8/images/sha256-ad3b494a60a52390199902e284c1d87e40defe390ca702619bde51f5aa904364?context=explore)
- 版本号/Version：Paddle：2.1.3  PaddleOCR 2.6： 问题相关组件/Related components：SVTR
直接调用[readme](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/algorithm_rec_svtr.md#svtr%E7%AE%97%E6%B3%95%E7%AE%80%E4%BB%8B)中的提供的配置和权重对svtr_base模型进行评测时，会报找不到SVTRLabelDecode的错误。我留意到配置文件里提到这个设定只在评测时用到，请问这一部分的模块是不是还没开源？实现起来跟CTC有什么区别呢？

**Comment by Topdu** [comment]
SVTRLabelDecode已被弃用，可使用CTCLabelDecode替代。
