### ISSUE TITLE
关于KIE任务，value是分开的两行或多行时该怎么处理

### ISSUE THREAD

**Issue by pogevip** [PaddlePaddle/PaddleOCR#8344]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/27748841/202141200-4e1161ff-8c16-43b6-ab6f-6af7b96bc42e.png)

##### 如上图，【货物或应税劳务、服务名称】这一列，下面的【小米红米3时尚金色】和【移动联通电信4G手机双卡双待】这两个是分开的两行，
1. 如果是当做key-value抽取任务（SER+RE）的话，该如何处理？一个key link 到多个value吗？
2. 如果是当做SER任务，直接识别实体的话，该怎么处理？

**Comment by bank010** [comment]
您好，楼主，有解决方案了吗？

**Comment by pogevip** [comment]
> 您好，楼主，有解决方案了吗？

没有呢，我感觉应该加个bbox排序的模型，如果排序做好了，这个问题就不存在了
