### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#8345]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： **Linux**
- 版本号/Version：Paddle：  paddlepaddle-gpu      2.3.2
- PaddleOCR： paddleocr             2.6.0.1
- 问题相关组件/Related components： Python 3.8.13
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**_--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1668599118 (unix time) try "date -d @1668599118" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5461 (TID 0x7f60a88f8700) from PID 0 ***]

Segmentation fault (core dumped)_**

**Comment by xzdong-2019** [comment]
hello ,i've the same problem, addition message: mupdf: syntax error in content stream linux， when i run PaddleOCR-release-2.6/ppstructure/predict_system.py

**Comment by jack-gits** [comment]
有人可以帮忙看看吗？

**Comment by Hepta-Col** [comment]
同问，求解决办法

**Comment by gavinfaimdata** [comment]
I've gotten seg faults when using paddlepaddle in an nvidia-docker container when there was a cuda version mismatch between the paddlepaddle image I used and the version of cuda on my host machine.

**Comment by anil-bit** [comment]
did you guys solve this issue?

**Comment by huangjun12** [comment]
安装好paddle后，运行一下 paddle.utils.run_check()，看下是否能成功运行。如果失败，大概率是环境问题，比如cuda/cudnn版本不匹配
