### ISSUE TITLE
Is it possible to fine tune Table Recognition yet? 

### ISSUE THREAD

**Issue by vhrehfdl** [PaddlePaddle/PaddleOCR#8350]
Is it possible to fine tuning Table Recognition yet? 
Currently, only learning from scratch is shown in the document.
Can I fine tune my data by loading a pre-trained model for table recognition training?

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/table_recognition_en.md

**Comment by WenmuZhou** [comment]
we have update the finetune doc in https://github.com/PaddlePaddle/PaddleOCR/pull/8353
