### ISSUE TITLE
关于C++编译时，MKL的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#8352]
下载百度编译好的paddle_inference库存，默认编译是打开了MKL的。
在PaddleOCR C++代码中，不想链接MKL的库，编译文件中tools/build.sh 设置-DWITH_MKL=OFF 。然后编译会报错：

请问编译要和paddle_inference的设置相同么，如果不想链接mkl的库，是否需要自己编译一个paddle_inference库？？

报错信息如下：
-- Build files have been written to: /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-release-2.5/deploy/cpp_infer/build
Scanning dependencies of target ppocr
[ 18%] Building CXX object CMakeFiles/ppocr.dir/src/clipper.cpp.o
[ 18%] Building CXX object CMakeFiles/ppocr.dir/src/args.cpp.o
[ 27%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 36%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 45%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 54%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
make[2]: *** No rule to make target '/home/alex/Music/paddle_inference/third_party/install/openblas/lib/libopenblas.a', needed by 'ppocr'。 停止。
make[2]: *** 正在等待未完成的任务....
[ 63%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
[ 72%] Building CXX object CMakeFiles/ppocr.dir/src/paddleocr.cpp.o
[ 81%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
[ 90%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/ppocr.dir/all' failed
make[1]: *** [CMakeFiles/ppocr.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by WenmuZhou** [comment]
关闭mkl需要使用这里不带mkl的预测库https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html

**Comment by ainndejj11** [comment]
> 关闭mkl需要使用这里不带mkl的预测库https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html
> 
> ![image](https://user-images.githubusercontent.com/12406017/202392324-6691e12c-1f3e-4762-b9ca-8ee308a13559.png)

请问不带mkl的推理库  这些不是CPU的么，还支持GPU 和 Tensorrt么？？

**Comment by WenmuZhou** [comment]
cpu的库和gpu是分开的
