### ISSUE TITLE
Can each character in the entire line be boxed and identified separately?

### ISSUE THREAD

**Issue by 1wang11lijian1** [PaddlePaddle/PaddleOCR#8355]
Hello, because I have learned that the paddle generally adopts the method of whole line text recognition, may I ask if each character in the whole line can be separately box detected and recognized? Is this possible?

**Comment by MissPenguin** [comment]
This function is not supported at present. For English, the training data needs to be labeled at word level. For Chinese or similar characters, you can try to estimate the position of a single character directly according to the coordinates of the text line and the number of words recognized.

**Comment by 1wang11lijian1** [comment]
Ok, is there such a single character annotation data set in English? Do I need to do the English single character tagging by myself? That would be too much work. Any good suggestions?

**Comment by MissPenguin** [comment]
> Ok, is there such a single character annotation data set in English? Do I need to do the English single character tagging by myself? That would be too much work. Any good suggestions?

You mean you want to get the position of each character other than each word for English? Seems like there isn't any dataset labeled in character level, and the cost of self labeling is too high. If the requirement for positioning accuracy is not too high, it is recommended to do a rough estimation directly.
