### ISSUE TITLE
文本检测预训练模型采用的数据集类型？

### ISSUE THREAD

**Issue by LoveSimons** [PaddlePaddle/PaddleOCR#8356]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
1、针对ch_ppocr_server_v2.0_det模型，ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml,官方提供的预训练模型ch_ppocr_server_v2.0_det_train，
发现采用的训练集为'/paddle/Datasets/chinese/label_train_all_f4_part1.txt', '/paddle/Datasets/chinese/label_train_all_f4_part2.txt', 
'/paddle/Datasets/chinese/label_train_all_f4_part3.txt', '/paddle/Datasets/chinese/label_train_all_f4_part4.txt', 
'/paddle/Datasets/chinese/label_train_all_f4_part5.txt'
验证集为’/paddle/Datasets/chinese/test_set/system_test_set_label_list_200.txt',请问这些数据集是否来自公开数据集，此外这些数据集的类型？
2、使用了该预训练模型进行微调时，是否对非印刷体检测有影响？

**Comment by MissPenguin** [comment]
1. 训练集包含2部分，一部分来自于ocr领域公开数据集，一部分是根据真实场景需求合成的文档类数据，合成工具使用的textrender，当然做了一些针对检测任务的适配，有需要可以自己收集或合成；验证集是我们有目标地从百度搜索收集的图片，尽可能覆盖真实需求，从而保证ppocr模型的实用性，这部分由于可能引发版权问题无法公开。
2. 模型微调时如果怕训偏，可以组织一批通用数据，和你的业务数据进行1:1或者其他比例的采样。

**Comment by LoveSimons** [comment]
> 1. 训练集包含2部分，一部分来自于ocr领域公开数据集，一部分是根据真实场景需求合成的文档类数据，合成工具使用的textrender，当然做了一些针对检测任务的适配，有需要可以自己收集或合成；验证集是我们有目标地从百度搜索收集的图片，尽可能覆盖真实需求，从而保证ppocr模型的实用性，这部分由于可能引发版权问题无法公开。
> 2. 模型微调时如果怕训偏，可以组织一批通用数据，和你的业务数据进行1:1或者其他比例的采样。

非常感谢您的回复，祝您生活愉快。
