### ISSUE TITLE
想问一下用GPU运行dbnet，还是对cpu资源有要求，是不是dbnet后处理必须要呢？是否有办法减少对cpu的使用呢？

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleOCR#8359]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
前后处理和中间的部分操作都还是会用到CPU，如果把前后处理都实现GPU版可以减少对CPU的使用并且加速，但有一些开发成本，有需要可以自己尝试下

**Comment by shumeirao** [comment]
好的，感谢>
