### ISSUE TITLE
DB找不到检测框，EAST和SAST出现outputs  index out of range错误

### ISSUE THREAD

**Issue by RONG-SONG** [PaddlePaddle/PaddleOCR#836]
麻烦大佬看下，我该怎么解决检测不到，以及index out of range的问题？

复现如下：

1、下载样本图片，存放位置："./doc/imgs/9.png"。 
链接：https://pan.baidu.com/s/1WzNK3XwYyao1O_HkzzvfDg 提取码：2pwp

2、在PaddleOCR根目录下，直接建立smaple.py，依次修改det_algorithm为DB, EAST, SAST， 运行即可。 
代码如下：
`
import tools.infer.utility as utility
from tools.infer.predict_system import main

def get_args():
    args = utility.parse_args()
    args.det_model_dir = "./inference/ch_ppocr_server_v1.1_det_infer/"
    args.rec_model_dir = "./inference/ch_ppocr_server_v1.1_rec_infer/"
    args.cls_model_dir = "./inference/ch_ppocr_mobile_v1.1_cls_infer/"
    args.use_angle_cls = True
    args.use_space_char = False
    args.use_gpu = False
    args.det_algorithm = "DB"

    return args

def run():
    args = get_args()
    args.image_dir = "./doc/imgs/9.png"
    return main(args)

if __name__ == '__main__':
    print(run())
`

**Comment by littletomatodonkey** [comment]
这里提供的模型都是带空格的，需要指定`--use_space_char=True`

你试下直接用predict_system.py呢？
```
python3  tools/infer/predict_system.py \
    --image_dir="./doc/imgs/9.png" \
    --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/" \
    --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infere/" \
    --cls_model_dir="./inference/ch_ppocr_mobile-v1.1.cls_infer/" \
    --rec_batch_num=1 \
    --use_gpu=False \
    --use_space_char=True \
    --use_angle_cls=False
```

**Comment by RONG-SONG** [comment]
您好，我试了，只能检测到最后一行：
具体信息如下：
dt_boxes num : 1, elapse : 0.43084716796875
rec_res num  : 1, elapse : 0.09973311424255371
Predict time of ./doc/imgs/9.png: 0.540s
多发肿大淋巴结影。, 0.994

图片的信息结构如下：
第一行：两侧胸廓对称，气管居中，两肺纹理增多紊乱，。。。
第二行：。。。
第三行：。。。
第四行：。。。
第五行：。。
第六行：右锁骨上见多发肿大淋巴结影。

**Comment by RONG-SONG** [comment]
我修改了DB检测框的阈值就可以了：
# DB parmas
```
    parser.add_argument("--det_db_thresh", type=float, default=0.1)
    parser.add_argument("--det_db_box_thresh", type=float, default=0.1)
    parser.add_argument("--det_db_unclip_ratio", type=float, default=1.6)
```
