### ISSUE TITLE
识别率低

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#8361]
使用python接口，但很多没有识别出来。

ocr = PaddleOCR(use_angle_cls=True, lang="en",use_gpu=False,use_dilation=True)  
img_path = 'Screenshot_20220921_105351.jpg'#'./Screenshot_20220921_105351.jpg'
preds = ocr.ocr(img_path, cls=True)

![image](https://user-images.githubusercontent.com/30545972/202442113-27f0c72a-cd8f-41ed-931a-60e5a274a4a4.png)

**Comment by MissPenguin** [comment]
左边那一列比较模糊，目前模型在模糊图上的效果会相对弱一点，一方面检测容易漏，一方面识别得分低也会把框直接过滤掉，可以先排查是检测还是识别的问题，然后finetune相应模型。

**Comment by jack-gits** [comment]
模型参数里有阈值可以调整吗？

**Comment by jack-gits** [comment]
原始图片是比较清晰的。

![image](https://user-images.githubusercontent.com/30545972/202448107-6a6e0b04-aebe-475a-84c0-2d9bcd07503e.png)

**Comment by MissPenguin** [comment]
把分割图可视化出来看了下，确实二值图就漏了很多像素，把输入边长调大后可以缓解，可以再细调一下试试～

默认--det_limit_side_len=960效果：
![image](https://user-images.githubusercontent.com/25809855/202473933-3a9a7cef-9141-49b8-ae89-ece553df2187.png)
调整--det_limit_side_len=1280效果：
![image](https://user-images.githubusercontent.com/25809855/202473903-b897c636-272a-4028-af30-8b437a4d11c6.png)

**Comment by jack-gits** [comment]
使用中文模型，发现可以识别括号(),但一些空格识别不了。

[[[941.0, 166.0], [1111.0, 166.0], [1111.0, 186.0], [941.0, 186.0]], ('**（11)215/65 R16**', 0.8708387017250061)]
[[[937.0, 97.0], [1067.0, 100.0], [1066.0, 124.0], [936.0, 120.0]], (**_'V.799g/km',_** 0.8255524039268494)]

使用英文模型，可以识别空格，但括号()识别不了

[[[943.0, 166.0], [1111.0, 166.0], [1111.0, 186.0], [943.0, 186.0]], ('**11215/65R16'**, 0.9581508040428162)]
[[[940.0, 99.0], [1066.0, 102.0], [1065.0, 123.0], [939.0, 119.0]], ('**_V.7 99 g/km_**', 0.8886851668357849)]

**Comment by MissPenguin** [comment]
> 使用中文模型，发现可以识别括号(),但一些空格识别不了。
> 
> [[[941.0, 166.0], [1111.0, 166.0], [1111.0, 186.0], [941.0, 186.0]], ('**（11)215/65 R16**', 0.8708387017250061)] [[[937.0, 97.0], [1067.0, 100.0], [1066.0, 124.0], [936.0, 120.0]], (**_'V.799g/km',_** 0.8255524039268494)]
> 
> 使用英文模型，可以识别空格，但括号()识别不了
> 
> [[[943.0, 166.0], [1111.0, 166.0], [1111.0, 186.0], [943.0, 186.0]], ('**11215/65R16'**, 0.9581508040428162)] [[[940.0, 99.0], [1066.0, 102.0], [1065.0, 123.0], [939.0, 119.0]], ('**_V.7 99 g/km_**', 0.8886851668357849)]

嗯，通用模型在你这种稍有难度的场景（同时存在光照、模糊、背景干扰问题）效果确实不太好，调参也只能一定程度缓解，要达到可用状态还是建议finetune，应该能明显提升检测识别效果。

**Comment by Lemniscate317** [comment]
求教这个分割图怎么弄的，目前我有一些文字没识别出来，但是不知道是哪里的问题
