### ISSUE TITLE
How to deal with text detection for low quality image? Can we custom train paddle OCR model for our dataset?

### ISSUE THREAD

**Issue by akashlinux10may** [PaddlePaddle/PaddleOCR#8362]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message: While trying detecting the text for bad quality image, there it will read 0 instead of C, or 3 instead of 8. Can we apply image pre-processing before predicting the text?

Also, how can I train my paddle OCR model for my own dataset? Is there any way to create custom paddle OCR to control the errors and fine tune our own model?

Please share the answers with proper step if possible. It will be great help.

**Comment by LDOUBLEV** [comment]
> How to deal with text detection for  low quality image

Can you share your case?

You can fine-tune your dataset by following the steps in the documentation. https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/detection_en.md

**Comment by akashlinux10may** [comment]
Hi,

Please see this screenshot, here C character it reads 0.
