### ISSUE TITLE
图片预处理

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#8365]
请问下，图片使用ppocrv3前，进行哪些预处理比较好呢。
1.比如图片大小多少尺寸多少合适呢
2.针对摩尔纹如何处理
3.背景是纯白的效果好？
3.是否使用openc做一些其他处理呢

**Comment by tianchiguaixia** [comment]
![test_img1234](https://user-images.githubusercontent.com/29837553/202599066-51ace3a4-a588-42a5-bbeb-c89f9b7cb068.jpg)

**Comment by LDOUBLEV** [comment]
> 1.比如图片大小多少尺寸多少合适呢

图像大小保证图像中的文字清晰可见即可


> 2.针对摩尔纹如何处理

目前PaddleOCR中没有针对摩尔纹的预处理

> 3.背景是纯白的效果好？

文字和背景能区分就行

> 3.是否使用openc做一些其他处理呢

在预测时，默认的预处理只有resize，normalize和transpose

**Comment by jingsongliujing** [comment]
建议换一个模型，推荐ch_ppocr_server_v2.0_det，ch_ppocr_server_v2.0_rec，加上分类模型，模型下载链接：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md

**Comment by tianchiguaixia** [comment]
你好，可以给一个ppocrv3关于文本框检测和识别的脚本？封装好那种的库有？

**Comment by jingsongliujing** [comment]
建议把paddocr的源码包直接拉到和项目同一目录,这个文件以及这个文件的依赖直接放同一目录下就可以了，在里面可以直接换上面的模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

**Comment by tianchiguaixia** [comment]
谢谢

**Comment by ybshaw** [comment]
同问，实验发现当较远距离拍摄的图片（但是图片上的文字还是很清楚），检测效果就一般了，想问下这种情况有什么对图片好的预处理方法吗

**Comment by jingsongliujing** [comment]
建议换一个模型，ch_ppocr_server_v2.0_det:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 中午1:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 图片预处理 (Issue #8365)




 
同问，实验发现当较远距离拍摄的图片（但是图片上的文字还是很清楚），检测效果就一般了，想问下这种情况有什么对图片好的预处理方法吗

**Comment by tianchiguaixia** [comment]
我已经解决了，直接使用去摩尔化的模型，预处理一下，识别率提高90%

**Comment by tianchiguaixia** [comment]
> 
![去摩尔化](https://user-images.githubusercontent.com/29837553/220285230-ff71d7a6-2655-4b97-8c3c-5a5af449becb.jpg)

**Comment by tianchiguaixia** [comment]
> 建议换一个模型，ch_ppocr_server_v2.0_det:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年11月20日(周日) 中午1:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] 图片预处理 (Issue #8365) 同问，实验发现当较远距离拍摄的图片（但是图片上的文字还是很清楚），检测效果就一般了，想问下这种情况有什么对图片好的预处理方法吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个试过了，效果不行

**Comment by tianchiguaixia** [comment]
> > 我已经解决了，直接使用去摩尔化的模型，预处理一下，识别率提高90%
> 
> 请问下`去摩尔化的模型`是怎么得到的，可以分享下吗

什么叫分享一下，那果断分享啊，赠人玫瑰，手留余香：https://github.com/zdyshine/Baidu-netdisk-AI-Image-processing-Challenge-demoire

**Comment by Marerc** [comment]
> > > 我已经解决了，直接使用去摩尔化的模型，预处理一下，识别率提高90%
> > 
> > 
> > 请问下`去摩尔化的模型`是怎么得到的，可以分享下吗
> 
> 什么叫分享一下，那果断分享啊，赠人玫瑰，手留余香：https://github.com/zdyshine/Baidu-netdisk-AI-Image-processing-Challenge-demoire

这个连接现在已经无法下载训练好的模型了，请问你是自己训练的模型，还是下载他们已经训练好的模型呀。
