### ISSUE TITLE
量化训练精度变差，模型没变小，速度也没提升是怎么回事啊？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#8366]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
模型量化训练后，保存的模型参数依然是fp32类型（权重数值处于int8范围），且模型结构存在量化反量化OP。直接去预测性能不会提升。
如果要提升性能，建议开启TRT去预测并设置precision参数为int8
如果是在端侧部署，建议用paddlelite部署，会有明显加速

**Comment by lilianjie111111** [comment]
> 

那请问下，量化后的模型不能够转onnx是什么原因呢？paddle量化后转onnx进行onnxruntime推理可行吗？？
