### ISSUE TITLE
import paddleocr用pythonw执行或pyinstaller打包后，启动程序时会闪过命令窗口

### ISSUE THREAD

**Issue by chenss** [PaddlePaddle/PaddleOCR#8367]
pyinstaller -w打包后程序运行成功，但启动时执行到import paddleocr时会闪过命令窗口，注释import paddleocr后就不会。
不在启动时import启动时没问题，但等执行到import语句还是会这样。

- 系统环境/System Environment：win10 LTSC
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.4 和 2.6.1.0 问题相关组件/Related components：
- 运行指令/Command Code：pythonw main.py 或 pyinstaller -w -i xxx.ico main.py后运行
- 完整报错/Complete Error Message：空的命令窗口一闪而过

**Comment by jingsongliujing** [comment]
建议把paddocr的源码包直接拉到和项目同一目录,这个文件以及这个文件的依赖直接放同一目录下再进行打包，pip容易出现问题：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

**Comment by chenss** [comment]
> 建议把paddocr的源码包直接拉到和项目同一目录,这个文件以及这个文件的依赖直接放同一目录下再进行打包，pip容易出现问题：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

命令窗口是where.exe，好像是Paddle的问题。

**Comment by ye13533167453** [comment]
这个问题至今没解决吗，我也是发现paddle打包后会闪出where.exe，很影响用户体验
