### ISSUE TITLE
我在做文字检测时，使用ch_PP-OCRv3_det_dml.yml 知识蒸馏 冻结一个大网络（之前训练好的精度较高）来教两个小网络 代码没有更改，为什么训练没有效果呢 infer出来就是一个大框

### ISSUE THREAD

**Issue by ic1031** [PaddlePaddle/PaddleOCR#8368]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
> 冻结一个大网络（之前训练好的精度较高）来教两个小网络

这个应该用cml.yml结尾的配置文件
v3模型的训练方法参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/PP-OCRv3_det_train.md
