### ISSUE TITLE
table_engine（）结果怎么乱序？如何设置？

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleOCR#8369]
调用table_engine(img)，结果都是乱序的，如何保证顺序？ 另外，paddleocr可以对图片识别的时候，只保留文本吗？ 对表格、图进行去除，怎么设置？

**Comment by WenmuZhou** [comment]
1. 你说的乱序具体是啥，方便具体一点吗
2. 版面分析有个label，可以根据这个进行过滤

**Comment by kevinuserdd** [comment]
> 1. 你说的乱序具体是啥，方便具体一点吗
> 2. 版面分析有个label，可以根据这个进行过滤

乱序指的是，输出的结果没有按照原来的文件格式输出。 比如第一段，第二段，第三段。。。输出的结果可能是第三段，第一段，第二段。。。。按照正常的逻辑应该是每个每个切好的段落按顺序输出吧？

**Comment by kevinuserdd** [comment]
> 1. 你说的乱序具体是啥，方便具体一点吗
> 2. 版面分析有个label，可以根据这个进行过滤

就是比如你版面分析好了，我想把文字内容按照原来的文件结构输出，就不好输出。因为你输出的结果按照每个 切分的板块输出，但是顺序是乱的。 这样拼接文字的时候，还得自己去根据坐标索引吗？

**Comment by WenmuZhou** [comment]
你这个可以试一下版面还原
