### ISSUE TITLE
语义词典纠错

### ISSUE THREAD

**Issue by roughsoft** [PaddlePaddle/PaddleOCR#837]
使用了一下demo，效果挺好的。感谢contribution！
有些OCR，特别是汉字侧词语，如果能够进行，语义词典的纠缠，就可能提升准确率。比如行业词汇字典。
请问怎么进行相关的语义词典纠错呢？麻烦提供详细的文档，样例代码，谢谢！

**Comment by WenmuZhou** [comment]
可以考虑下语言模型，或者字典匹配，我们这边没有相关的工作呢

**Comment by roughsoft** [comment]
谢谢！建议，考虑一下。毕竟OCR要真正的实用，一定要考虑这些的，否则准确率还是可以提升的。
至少sample可以考虑相关的。

**Comment by WenmuZhou** [comment]
真正做项目，后处理的提升还是很大的。我之前也是做项目出身的，模型能够决定了项目的起点，真正的成品还是要后处理来和业务对接

**Comment by roughsoft** [comment]
en
