### ISSUE TITLE
How to train PPStructureV2 models ? Kindly help

### ISSUE THREAD

**Issue by ChidanandKumarVimaan** [PaddlePaddle/PaddleOCR#8370]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

How to train PPStructureV2 models ? Kindly help

**Comment by littletomatodonkey** [comment]
Hi, PP-StrucutreV2 contains layout analysis, table recognition and KIE, you can refer to these tut more more details.

1. overall: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/README.md
2. layout analysis: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/layout/README.md
3. table recognition: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/table_recognition_en.md
4. KIE: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/kie_en.md
