### ISSUE TITLE
为什么训练后的版面分析模型加载在PaddleDetection中的infer.py可以成功运行，但是在PaddleOCR中的predict_layout中无法运行

### ISSUE THREAD

**Issue by Leezzzzz** [PaddlePaddle/PaddleOCR#8379]
![image](https://user-images.githubusercontent.com/62826242/202843097-e02c03e6-b4fd-4b95-912c-a6ef6e261763.png)
这是我用预训练模型训练后得到的模型。在PaddleDetection中的infer.py中可以成功推理
![image](https://user-images.githubusercontent.com/62826242/202843158-e2907b78-3229-431b-91d8-be31a9cc05bc.png)
但是加载到PaddleOCR中的ppstructure/layout/predict_layout.py中进行推理则会莫名卡住。
![image](https://user-images.githubusercontent.com/62826242/202843243-867e3c2a-5766-4b14-b225-700c377fcc08.png)
这是为什么。

**Comment by an1018** [comment]
请问在PaddleOCR执行的什么命令

**Comment by Leezzzzz** [comment]
python ppstructure/layout/predict_layout.py --image_dir=1203761_4.png --layout_dict_path=ppocr/utils/dict/layout_dict/layout_cdla_dict.txt --layout_model_dir=picodet_lcnet_x1_0_layout

**Comment by TapendraBaduwal** [comment]
@Leezzzzz "I am facing the same issue, how did you solve it?"
