### ISSUE TITLE
在使用中英文超轻量OCR模型（8.1M）时，运行报错not find model file path ./inference/ch_ppocr_mobile_v1.1_rec_infer//model

### ISSUE THREAD

**Issue by Luo-Yichen** [PaddlePaddle/PaddleOCR#838]
在使用中英文超轻量OCR模型（8.1M）时,模型名称ch_ppocr_mobile_v1.1_xx，解压后目录应该是
![1](https://user-images.githubusercontent.com/63596550/94124949-00a9ec00-fe56-11ea-9dfa-df67ca21d08c.png)
但是实际上目录是
![2](https://user-images.githubusercontent.com/63596550/94124981-0acbea80-fe56-11ea-9255-4602f40d9d91.png)
即识别的推理模型解压后只有一个ch_ppocr_mobile_v1.1_rec_infer文件，而不是包含model和param的文件夹，所以运行时会报错not find model file path ./inference/ch_ppocr_mobile_v1.1_rec_infer//model，请问是不是这个模型的检测压缩包上传错误了呢？谢谢~

**Comment by liangyangtao** [comment]
https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_infer.tar 
这个估计是压缩了两次
解压后的 ch_ppocr_mobile_v1.1_rec_infer 
在解压一次就是文档里的 model  param 结构了

**Comment by Luo-Yichen** [comment]
谢谢！解决了
