### ISSUE TITLE
使用hubserving部署PP-Structure服务，无法一键pdf转word

### ISSUE THREAD

**Issue by waizao** [PaddlePaddle/PaddleOCR#8382]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- windows 11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddleocr 2.6
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
**问题现象**：使用hubserving部署PP-Structure服务（structure_system），无法一键pdf转word，并且未记录日志
**测试过程**：在params.py文件中，配置有以下关键参数，使用python tools/test_hubserving.py 测试接口，发现测试过程中的logger打印没有记录到日志文件，并且开启了pdf转word，最后没有生成word文档。
**测试备注**：
1、测试过程没有抛任何异常
2、在本机环境上使用paddleocr可以正常pdf转word，但是部署服务后，无法生成
paddleocr --image_dir=./test/181.pdf --type=structure --recovery=true --use_pdf2docx_api=true
**配置关键参数**：
cfg.show_log = True
cfg.use_pdf2docx_api = True
cfg.output = './output'

求助答疑：
1、使用hubserving部署PP-Structure服务后，如何开启log日志，并写到指定日志文件
2、hubserving部署PP-Structure服务，发现structure_system模块中params.py非常简单，没有提供完整参数，
希望平台能提供一份完整的参数，能够实现pdf转word。

**Comment by waizao** [comment]
麻烦paddleOcr工程师关注下，非常感谢@an1018 @littletomatodonkey @

**Comment by an1018** [comment]
目前暂未计划支持，可以先参考这个文档尝试自己实现哈：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/hubserving/readme.md
