### ISSUE TITLE
如何通过PPOCRLabel多人协同标注数据

### ISSUE THREAD

**Issue by hanyong-max** [PaddlePaddle/PaddleOCR#8383]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LUOQING1994** [comment]
合并时，需要满足以下条件
1，所有图片在同一文件夹中
2，把各个labels文件进行合并，并把labels中的文件路径修改成当前文件夹
3，不要再用工具打开当前文件，在你关闭工具时，labels文件会被重写，导致数据丢失

**Comment by Evezerest** [comment]
如果使用PaddleOCR代码训练，可以在yml文件当中指定多个数据集地址，这样就不需要合并数据集
