### ISSUE TITLE
在centos中使用ppstructure时，报错。

### ISSUE THREAD

**Issue by luoruijie** [PaddlePaddle/PaddleOCR#8385]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos8
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle==2.4.0 paddleocr ==2.6.0.2
- 运行指令/Command Code：
import cv2
import numpy as np

from paddleocr import PPStructure, draw_structure_result, save_structure_res
from past.builtins import raw_input

table_engine = PPStructure(show_log=False, image_orientation=True, benchmark=False)

- 完整报错/Complete Error Message：
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
我在windows中是没有报这个错误的，所以我想知道在centos中要如何解决。

**Comment by luoruijie** [comment]
from singal_doc_parse import parse_tile, tlags, modes
File “/jupyter/workspace/dialogue. system. model/malti_doc_cacluate/singal_doc_parse. py”, line 44, in <module>
from OCR. paddle_ocr import paddle_ocr
File */jupyter/workspace/dialogue. system. model/multi_doc_cacluate/OCR/paddle_ocr.py*, line 12, in <module>
from paddleocr import PaddleOCR
File “/usr/local/python3/lib/python3, 8/site-packages/paddleocr/_init_.py*, line 14, in <module>
from .paddleocr import *
File */usr/local/python3/lib/python3. 8/site-packages/paddleocr/paddleocr. py”, line 21, in <module>
import paddle
File "/usr/local/ython3/libpythom3.8/site-packages/paddle/_init__.py", line 25, in <module>
from .framework import monkey_patch_variable
File “/usr/local/python3/lib/python3, 8/site-packages/paddle/framework/_init_.py*, line 17, in <module>
from . import random # noga: F401
File “/usr/local/python3/1ib/python3, 8/site-packages/paddle/framework/random, py”, line 16, in <module>
import paddle. fluid as fluid
File “/usr/local/python3/1ib/python3, 8/site-packages/paddle/fluid/_init_.py*, line 98, in <module>
from . import framework
File “/usr/local/python3/1ib/python3, 8/site-packages/paddle/fluid/framework. py”, line 37, in <module>
from , import coce
File “/usr/local/python3/lib/python3. 8/site-packages/paddle/fluid/core. py”, line 304, in <module>
raise e
File “/usr/local/python3/lib/python3. 8/site-packages/paddle/fluid/core. py”, line 249, in <nodule>
from . import libpaddle
ImportErrer: libpython3.8. s0.1.0: cammot open shared object file: No such file or directory

完整 报错请查阅

**Comment by WenmuZhou** [comment]
看起来是paddle没有安装正确，辛苦安装paddle的安装说明再安装一下

**Comment by justliveisperfect** [comment]
碰到同样问题  请问怎么解决的
