### ISSUE TITLE
unclip_ratio参数失效

### ISSUE THREAD

**Issue by LUOQING1994** [PaddlePaddle/PaddleOCR#8386]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：2.6
- 运行指令/Command Code：python3 tools/infer/predict_det.py --image_dir="./train_data/det/val" --det_model_dir="./output/det_db/" --det_algorithm="DB"
- 完整报错/Complete Error Message：
训练模型的yml中修改unclip_ratio可实现检测框的大小改变，但转换成推理模型后，无论怎么修改utility.py中的det_db_unclip_ratio，检测框不变，且都很大，我也检查了predict_det.py，db_postprocess.py代码，都没有固定unclip_ratio值
使用的是训练模型
![image](https://user-images.githubusercontent.com/20340633/202957110-53599276-ed40-4c62-bd8e-62eb50b9bee1.png)
使用的是推理模型
![image](https://user-images.githubusercontent.com/20340633/202957303-504145e0-1822-40dc-b7a0-1076755a58dc.png)

**Comment by LDOUBLEV** [comment]
没能复现你这个问题，测试调整det_db_unclip_ratio，检测框大小差距很明显：

python3.7 tools/infer/predict_det.py --det_model_dir=./ch_PP-OCRv3_det_infer/ --image_dir=./doc/imgs/00006737.jpg --det_db_unclip_ratio=1.0
![b1c6790766c360a61ddc2d2078a00964](https://user-images.githubusercontent.com/26592129/202988932-c58ecdab-3615-4616-9e1e-cd418d283cfa.png)

python3.7 tools/infer/predict_det.py --det_model_dir=./ch_PP-OCRv3_det_infer/ --image_dir=./doc/imgs/00006737.jpg --det_db_unclip_ratio=3.0
![image](https://user-images.githubusercontent.com/26592129/202988978-79250c40-667d-4f52-931c-0313af775a5f.png)
