### ISSUE TITLE
在使用PaddleOCR对pdf文件进行识别时，只需要识别图片的一部分，请问识别区域如何修改？

### ISSUE THREAD

**Issue by jlaugui** [PaddlePaddle/PaddleOCR#8387]
在使用PaddleOCR对pdf文件进行识别时，只需要识别图片的一部分，并不需要识别整个PDF文件请问这个参数如何修改？

ocr = PaddleOCR(use_angle_cls=True, lang="ch", page_num=1)  # need to run only once to download and load model into memory
img_path = '026a5b7f1d00a5.pdf'
result = ocr.ocr(img_path, cls=True)

**Comment by WenmuZhou** [comment]
这个暂时不支持

**Comment by 555myhair** [comment]
@WenmuZhou 您好，这个功能现在支持了吗？我没找到怎么改。
