### ISSUE TITLE
ch_ppocr_mobile_v2.0_rec_train文件错误，从v2.2版本到v2.6版本都是错误的

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleOCR#8389]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：v2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 测试动态图预测的时候出错
- tools/infer_rec.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.pretrained_model=weights/ch_ppocr_mobile_v2.0_rec_train_/ch_ppocr_mobile_v2.0_rec_train.pdparams Global.infer_img=F:/Datasets/securety/PageRec/test_data/test/imgs
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/16351823/202978215-becd9e63-ffec-4421-8886-7da2d4f2d890.png)
![image](https://user-images.githubusercontent.com/16351823/202978261-12a243a3-c94c-4d50-9ee7-eaa97a8f8203.png)
训练模型下载位置链接：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md
![image](https://user-images.githubusercontent.com/16351823/202979022-49dbadf1-2e49-4415-a199-e4654199dabc.png)

模型下载下来解压出来只有一个无后缀的文件：
![image](https://user-images.githubusercontent.com/16351823/202978621-9d0cc505-35e0-4c9a-868a-86200bd3a7d1.png)
没有后缀，手动加上后缀.pdparams，在加载的时候就报了上述错误。
而英文识别模型就是正确的，三个训练过程生成的文件：
![image](https://user-images.githubusercontent.com/16351823/202978836-07250a2c-5591-4f89-858f-5cab80eea521.png)
我一直回溯到v2.2版本，也就是ppocr v2.0版本刚发布的版本，里面的链接下载的训练模型也是一样，没有后缀，加载错误，希望官方关注一下，纠正一下

**Comment by tink2123** [comment]
把解压出来的 ch_ppocr_mobile_v2.0_rec_train 再解压一下

**Comment by xdg2016** [comment]
试了一下，可以了，谢谢！两种文件夹结构，有点蒙哈哈哈！

**Comment by tink2123** [comment]
没事～ 这个文件在windows下解压确实容易出问题
