### ISSUE TITLE
在多次kie_ser识别时，显存会一直涨 溢出，怎么释放显存回收垃圾？

### ISSUE THREAD

**Issue by bank010** [PaddlePaddle/PaddleOCR#8390]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
可以试一下这个api https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/device/cuda/empty_cache_cn.html#empty-cache

**Comment by bank010** [comment]
> 可以试一下这个api https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/device/cuda/empty_cache_cn.html#empty-cache

这个我尝试了一下，效果不理想

**Comment by WenmuZhou** [comment]
那你运行的时候，图片尺寸是怎么变化的
