### ISSUE TITLE
bug: ppocr/data/imaug/label_ops.py中存在小bug

### ISSUE THREAD

**Issue by shengjie-shi** [PaddlePaddle/PaddleOCR#8394]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

ppocr/data/imaug/label_ops.py，第828行，def xyxyxyxy2xywh(self, boxes): 应该是 def xyxyxyxy2xywh(self, bboxes):

**Comment by WenmuZhou** [comment]
这个不算bug
