### ISSUE TITLE
车牌识别问题

### ISSUE THREAD

**Issue by Mylszd** [PaddlePaddle/PaddleOCR#8398]
请问使用PaddleOCR进行车牌识别，如何输出中间的空白呢（间隔比较大的两个字符），比如车牌号码是“鄂EVN736”，识别后输出“鄂E VN736”，谢谢！

**Comment by drenched9** [comment]
既然你场景已经是车牌识别，且不希望结果存在空格，直接在OCR识别结果字符串的基础上加一行去除空格的代码就好了
