### ISSUE TITLE
训练检测模型时出现以下错误

### ISSUE THREAD

**Issue by bboxzhen** [PaddlePaddle/PaddleOCR#84]
![image](https://user-images.githubusercontent.com/39783629/82530169-4cc6e600-9b6f-11ea-996d-7dd0f3f164c3.png)
![image](https://user-images.githubusercontent.com/39783629/82530181-56504e00-9b6f-11ea-8f10-1f9dd87e50cd.png)

**Comment by LDOUBLEV** [comment]
问下，你是在自己的数据集上训练的吗，还是用的readme中提到的数据集。方便的话，提供下
- 启动训练的指令
- 训练环境：paddle版本，cuda版本等

**Comment by bboxzhen** [comment]
readme上面的，应该是gpu内存不足
![image](https://user-images.githubusercontent.com/39783629/82541427-07141880-9b83-11ea-858e-1374704e5c63.png)

请问该如何减少训练模型大小

**Comment by bboxzhen** [comment]
> 问下，你是在自己的数据集上训练的吗，还是用的readme中提到的数据集。方便的话，提供下
> 
> * 启动训练的指令
> * 训练环境：paddle版本，cuda版本等
> 
> 初步怀疑是数据读取有问题

readme上面的，应该是gpu内存不足
![image](https://user-images.githubusercontent.com/39783629/82541427-07141880-9b83-11ea-858e-1374704e5c63.png)

请问该如何减少训练模型大小

**Comment by LDOUBLEV** [comment]
训练模型很小了，轻量的模型只有4M多，你的GPU有多少内存，用的是哪一个算法

**Comment by LDOUBLEV** [comment]
watch nvidia-smi 看一下GPU内存使用情况，如果有其他程序占用了内存，但是GPU没有利用率，可以kill掉

**Comment by bboxzhen** [comment]
> 训练模型很小了，轻量的模型只有4M多，你的GPU有多少内存，用的是哪一个算法
export PYTHONPATH=.&&/opt/conda_venv3.7/bin/python3 tools/train.py -c configs/det/det_mv3_db.yml -o Optimizer.base_lr=0.0001

![image](https://user-images.githubusercontent.com/39783629/82541691-6d993680-9b83-11ea-943c-bc6a30e823a0.png)

**Comment by LDOUBLEV** [comment]
这个程序没有利用率，可能是python程序非正常关闭，但是进程依然存在，导致一直再占着显存

**Comment by bboxzhen** [comment]
> 这个程序没有优化，可能是python程序非正常关闭，但是进程依然存在，导致一直再占着显存
可是我已经全部清理才开始跑的
sudo fuser -v /dev/nvidia* |awk '{for(i=1;i<=NF;i++)print "kill -9 " $i;}' | sudo sh
![image](https://user-images.githubusercontent.com/39783629/82541992-d84a7200-9b83-11ea-8a0d-29576e51af18.png)

**Comment by LDOUBLEV** [comment]
那试试减小batchsize

**Comment by bboxzhen** [comment]
> batchsize

减少test_batch_size_per_card，train_batch_size_per_card可以解决问题，非常感谢

**Comment by LDOUBLEV** [comment]
> > batchsize
> 
> 减少test_batch_size_per_card，train_batch_size_per_card可以解决问题，非常感谢

好的
