### ISSUE TITLE
Could not locate zlibwapi.dll. Please make sure it is in your library path

### ISSUE THREAD

**Issue by sad521** [PaddlePaddle/PaddleOCR#8400]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：paddlepaddle-gpu==2.3.2  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
-  ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Could not locate zlibwapi.dll. Please make sure it is in your library path!

**Comment by Evezerest** [comment]
应该是环境没装好

**Comment by quantbruce** [comment]
1. 找到 zlib.dll文件
C:\Program Files\NVIDIA Corporation\Nsight Systems 2022.4.2\host-windows-x64\zlib.dll
2.复制该文件，并重命名为zlibwapi.dll
3.放到如下路径(记得将该路径添加到环境变量)
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\zlibwapi.dll
4.重新打开终端在执行之前命令，便可成功。
