### ISSUE TITLE
Detected lines width/height ratio greater than 10

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8403]
in the image below, the width-to-height ratio of text is 24 and the recognition engine got it all right, which is confusing.

As per the documentation, any text with width to height ratio > 10 is ignored when training the recognition model of pp-ocrv3.

I'm using PP-OCRv3 detection and recognition for this.

So is this outdated for PP-OCRV3 and does that mean the training of the recognition model can accept sentences where the w:h > 10?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/29528270/203119308-85f9d273-c434-483a-8dfc-f716ca7fce91.png">

**Comment by bely66** [comment]
@littletomatodonkey  Also I wanna know is detecting long sentences a feature of SVTR, which used in PP-OCRv3?

**Comment by bely66** [comment]
Anyone????

**Comment by littletomatodonkey** [comment]
PP-OCRv3 can recognize texts with any length, which is same as PP-OCRv2c and PP-OCR.

**Comment by bely66** [comment]
@littletomatodonkey would that be possible using vanilla SVTR model?
