### ISSUE TITLE
KIE使用python推理如何用标注好的文本检测与识别json文件作为输入？

### ISSUE THREAD

**Issue by ploool** [PaddlePaddle/PaddleOCR#8404]
- 版本号/Version：PaddleOCR-release-2.6      
- 问题相关组件/Related components：KIE
- 运行指令/Command Code：
        `python3 kie/predict_kie_token_ser.py 
          --kie_algorithm=LayoutXLM --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer --image_dir=./docs/kie/input/zh_val_42.jpg --ser_dict_path=../train_data/XFUND/class_list_xfun.txt --vis_font_path=../doc/fonts/simfang.ttf --ocr_order_method="tb-yx"`

- 将--image_dir图片路径改成标注好的json文件路径应该如何设置？

**Comment by littletomatodonkey** [comment]
这块目前还没有支持
