### ISSUE TITLE
关于训练时，epoch的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#8405]
PaddleOCR训练文字识别模型（OCRv2版），默认的epoch=800，然后学习率下降decay_epochs=[700, 800]
如果修改为 epoch=500，  decay_epochs=[400, 500]    
减少epoch后训练  相比与默认的那两个参数，最终的效果或者训练过程中的各个参数  会受什么影响吗？？？

**Comment by littletomatodonkey** [comment]
没啥影响，精度会稍微低一点
