### ISSUE TITLE
ser

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8408]
采用ser模型进行推理的时候如何调动自己训练的检测与识别模型，方向分类器
![image](https://user-images.githubusercontent.com/67177370/203209419-653fe2b3-1a3d-43a1-9907-72d085c644c7.png)

**Comment by littletomatodonkey** [comment]
可以参考下面的文档来训练检测和识别模型

* 检测文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/detection.md
* 识别文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/recognition.md
