### ISSUE TITLE
线上 使用 python3 tools/export_model.py 转换inference识别模型，识别时出现乱码。是个什么情况？

### ISSUE THREAD

**Issue by chendaochuan** [PaddlePaddle/PaddleOCR#841]
各位大神，问下大家
python3 tools/export_model.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints="./output/rec_r34_vd_crnn/best_accuracy" Global.save_inference_dir="./inference/rec_r34_vd_crnn/" 
export出来的inference 模型识别的时候，出现乱码。是个什么情况？

这里出现的结果是乱码：
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/1600141374676.jpg" --det_model_dir="./inference/det_db_r50/"  --rec_model_dir="./inference/rec_r34_vd_crnn" 

rec_icdar15_train.yml.这里是这样配置字典：
  character_type: ch
  character_dict_path: ./train_data/rec_train/label_list.txt

ps:  label_list.txt 是由ubuntu生成，上传到线上的。

使用 infer_rec.py 未转换的模型识别， 结果正常中文显示。

**Comment by tink2123** [comment]
如果您修改了默认字典，请阅读[文档说明](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/inference.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E5%AD%97%E5%85%B8%E7%9A%84%E6%8E%A8%E7%90%86)，添加参数：
`--rec_char_dict_path="./train_data/rec_train/label_list.txt"`

**Comment by lmw0320** [comment]
肯定是字典文件没指向对。。
我之前也遇到这种情况，后面直接去配置文件里头，把字典文件路径指向改了，就可以了。
另外就是，你的字典文件修改了之后，模型是新训练出来的吧？ 别搞错模型文件了就行。。
人家的原理是根据字典文件的每个字的行数，将每个字符进行编码，纳入模型训练。模型预测出来的结果也是编码值，再通过字典文件decode成相应的字符。。你的字典文件不能随便改变（模型训练用的字典文件，要和预测的字典文件保持一致，否则即使预测出来了编码值，解码的时候也会出错）
