### ISSUE TITLE
使用自动标注的时候一直报错

### ISSUE THREAD

**Issue by wujia3308** [PaddlePaddle/PaddleOCR#8413]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

File "D:\ProgramData\Anaconda3\envs\mytorch\Lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 59, in run
    " Location: " + json.dumps(posi) +'\n'
TypeError: must be str, not list

**Comment by wujia3308** [comment]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：window10
版本号/Version：Paddle2.6： PaddleOCR： 问题相关组件/Related components：PPOCRLabel
运行指令/Command Code：python PPOCRLabel.py --lang ch
完整报错/Complete Error Message：
File "D:\ProgramData\Anaconda3\envs\mytorch\Lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 59, in run
" Location: " + json.dumps(posi) +'\n'
TypeError: must be str, not list

**Comment by zhuqiang00099** [comment]
我也是，这解决了吗
