### ISSUE TITLE
c++服务端编译问题, 编译环境系统Centos 7

### ISSUE THREAD

**Issue by hnyztang** [PaddlePaddle/PaddleOCR#8419]
尝试了不同版本都是这个报错，预测库也存在对应的函数
(base) [root@localhost cpp_infer]# sh tools/build.sh
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 8.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /home/tangz/paddle/opencv-3.4.7/opencv3 (found version "3.4.7") 
cmake cxx flags -g -O3 -fopenmp -std=c++11
-- Found Git: /bin/git (found version "1.8.3.1") 
default cmake for auto_log, no need to compile
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tangz/paddle/PaddleOCR/deploy/cpp_infer/build
[ 25%] Building CXX object CMakeFiles/ppocr.dir/src/main.cpp.o
[ 25%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o
[ 37%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_det.cpp.o
[ 62%] Building CXX object CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o
[ 62%] Building CXX object CMakeFiles/ppocr.dir/src/postprocess_op.cpp.o
[ 87%] Building CXX object CMakeFiles/ppocr.dir/src/utility.cpp.o
[ 87%] Building CXX object CMakeFiles/ppocr.dir/src/preprocess_op.cpp.o
[100%] Linking CXX executable ppocr
CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o：在函数‘PaddleOCR::Classifier::LoadModel(std::string const&)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:75：对‘paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)’未定义的引用
CMakeFiles/ppocr.dir/src/ocr_cls.cpp.o：在函数‘PaddleOCR::Classifier::Run(cv::Mat&)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:38：对‘paddle_infer::Predictor::GetInputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:39：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:46：对‘paddle_infer::Predictor::GetOutputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_cls.cpp:47：对‘paddle_infer::Predictor::GetOutputHandle(std::string const&)’未定义的引用
CMakeFiles/ppocr.dir/src/ocr_det.cpp.o：在函数‘PaddleOCR::DBDetector::LoadModel(std::string const&)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:24：对‘paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:75：对‘paddle::AnalysisConfig::SetTRTDynamicShapeInfo(std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, bool)’未定义的引用
CMakeFiles/ppocr.dir/src/ocr_det.cpp.o：在函数‘PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&, std::vector<double, std::allocator<double> >*)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:121：对‘paddle_infer::Predictor::GetInputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:122：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:130：对‘paddle_infer::Predictor::GetOutputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_det.cpp:131：对‘paddle_infer::Predictor::GetOutputHandle(std::string const&)’未定义的引用
CMakeFiles/ppocr.dir/src/main.cpp.o：在函数‘__static_initialization_and_destruction_0’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:46：对‘google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:48：对‘google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:50：对‘google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:51：对‘google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:60：对‘google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)’未定义的引用
CMakeFiles/ppocr.dir/src/main.cpp.o:/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/main.cpp:63: 跟着更多未定义的参考到 google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)
CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o：在函数‘PaddleOCR::CRNNRecognizer::LoadModel(std::string const&)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:124：对‘paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:152：对‘paddle::AnalysisConfig::SetTRTDynamicShapeInfo(std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, std::map<std::string, std::vector<int, std::allocator<int> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<int, std::allocator<int> > > > >, bool)’未定义的引用
CMakeFiles/ppocr.dir/src/ocr_rec.cpp.o：在函数‘PaddleOCR::CRNNRecognizer::Run(std::vector<cv::Mat, std::allocator<cv::Mat> >, std::vector<double, std::allocator<double> >*)’中：
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:58：对‘paddle_infer::Predictor::GetInputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:59：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:66：对‘paddle_infer::Predictor::GetOutputNames()’未定义的引用
/home/tangz/paddle/PaddleOCR/deploy/cpp_infer/src/ocr_rec.cpp:67：对‘paddle_infer::Predictor::GetOutputHandle(std::string const&)’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [ppocr] 错误 1
make[1]: *** [CMakeFiles/ppocr.dir/all] 错误 2
make: *** [all] 错误 2
(base) [root@localhost cpp_infer]#

**Comment by an1018** [comment]
可以参考这个issue #3020

**Comment by hnyztang** [comment]
> 可以参考这个issue #3020
#3020是用docker解决了，对我这的真机编译cpu版本貌似没啥帮助；
centos 7， gcc (GCC) 8.2.0，paddle_inference 2.1    manylinux_cpu_avx_mkl_gcc82
版本符合环境要求的,  可centos下就是报这个错, paddle ocr是不支持centos系统？

**Comment by hnyztang** [comment]
OPENCV_DIR=/home/tangz/paddle/opencv-3.4.7/opencv3
LIB_DIR=/home/tangz/paddle/paddle_inference
#CUDA_LIB_DIR=/usr/local/cuda/lib64
#CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=OFF \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    #-DCUDNN_LIB=${CUDNN_LIB_DIR} \
    #-DCUDA_LIB=${CUDA_LIB_DIR} \

make -j
