### ISSUE TITLE
建议不要在pip包里使用argparse模块

### ISSUE THREAD

**Issue by TankAbraham** [PaddlePaddle/PaddleOCR#842]
您好，

我建议不要在 pip 包（paddleocr）里面引用 argparse 模块。因为这会与用户所引用的 argparse 包发生冲突。

谢谢！

**Comment by WenmuZhou** [comment]
用户所引用的argparse是指？或者能提供一个冲突的code吗

**Comment by LDOUBLEV** [comment]
好的，我们评估下

**Comment by ausk** [comment]
文件 tools/infer/utility 中定义的 parse_args，项目根目录下使用的 paddleocr.py 中  parse_args 重定义了下，两个参数也不太一致。可以考虑去掉简化下。

**Comment by littletomatodonkey** [comment]
这块目前没有很好的继承argparse的方法，因为还是希望whl包能够更独立一些，如果你有更好的简化或者改进方法，欢迎向我们提pr~感谢你的反馈

**Comment by TankAbraham** [comment]
> 这块目前没有很好的继承argparse的方法，因为还是希望whl包能够更独立一些，如果你有更好的简化或者改进方法，欢迎向我们提pr~感谢你的反馈

好的，谢谢来自官方人员的回复！
