### ISSUE TITLE
DBNET++训练精度问题

### ISSUE THREAD

**Issue by justcodew** [PaddlePaddle/PaddleOCR#8423]
在自有数据上对dbnet和dbnet++做微调训练，考虑部署TRT转换问题使用时均去除了dcn模块，使用了[DB与DB++](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_det_db.md)中提供的预训练模型，dbnet和dbnet++两个模型训练的参数基本保持一致，训练效果如下：

**dbnet:**        resnet18 (无dcn)  hmean 0.76 precision: 0.74 recall: 0.78  best epoch : 75
**dbnet++:**   resnet18 (无dcn)  hmean 0.78 precision: 0.89 recall: 0.69  best epoch : 1100  【无预训练模型，仅特征网络有】

**dbnet:**        resnet50 (无dcn)  hmean 0.79 precision: 0.76 recall: 0.82  best epoch : 45
**dbnet++:**   resnet50 (无dcn)  hmean 0.76 precision: 0.91 recall: 0.66  best  epoch : 70

数据集： train : test = 7万：7千 （主要构成是ocr开源数据，包含街景，网络图像等）

比较奇怪的是dbnet++效果反而会差一些，特别是召回率要低上十几个点，但precision高很多，这个可能是什么原因造成的，
如果想要提高DBNET++的召回率，有没有什么好的改善措施 (dbnet++继续训练效果无提升)

**Comment by LDOUBLEV** [comment]
DB++的loss配置
**
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
**

DB的loss配置：
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

使用BCEloss，precision更高，最终计算的hmean也稍微高一些。我们发现使用DiceLoss后，recall更高；
