### ISSUE TITLE
【third-party】为ppOCRLabel中的表格标注功能贡献一些代码

### ISSUE THREAD

**Issue by pyramid20002000** [PaddlePaddle/PaddleOCR#8425]
在我使用ppOCRLabel对表格识别进行标注的时候，碰到了一些使用不方便的问题，我自己写了一个python的脚本来处理这些问题。
大致包括：如何批量生成“空格子”， 如何给”空格子“或者”重复的格子“排序，等等
我把我使用时遇到的问题，和我写的代码，包括怎么使用这些代码，都发布在以下链接中了。
[https://gitee.com/pyramid20002000/ppocrlabel_modify_label_by_excel](url)
（详细请看其中的readme.mp4）

希望能集成到ppOCRlabel中帮助到更多同行。

**Comment by an1018** [comment]
感谢贡献，我们后面看一下哈

**Comment by WenmuZhou** [comment]
方便提个pr 吗
