### ISSUE TITLE
用于文本检测微调，实现单字检测的训练数据问题

### ISSUE THREAD

**Issue by wmxxxxxx** [PaddlePaddle/PaddleOCR#8426]
想微调PaddleOCR在单字上的检测效果，请问训练数据必须使用（图1）实际场景，还是可以使用（图2）仅只有单字的图像？
![image](https://user-images.githubusercontent.com/44235092/203563553-cbe0194e-ab19-425a-abdc-850feb4d7ac0.png)
图1
![image](https://user-images.githubusercontent.com/44235092/203563636-5f209a2f-59d6-4d23-a7b1-1a3749478fec.png)
图2

若只能用图1的数据，可能无法有大量实际场景图像用于微调，有什么别的方法可以生成训练数据吗？Text Render工具可以用于文本检测数据生成吗？

**Comment by an1018** [comment]
推荐使用1，因为图片尺寸更接近真实场景，可以加载预训练模型微调的，移除数字获取背景图、根据预料在对应位置写入，如果场景比较简单可以先生成200-500张试试
Text Render工具可以的，主要是字体、颜色等设置尽可能符合当前场景
