### ISSUE TITLE
windows系统是否支持单机多卡训练？？？进行训练的时候会报错！

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#8427]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 
- 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

#多卡训练，通过--gpus参数指定卡号
python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
使用教程中的运行命令会报如下错误，搜索后说Windows系统不支持单机多卡的训练？？？？
![1669213404694](https://user-images.githubusercontent.com/94897119/203570627-b8e24e07-2604-4e16-ac71-ab5dd6bd0d48.png)

**Comment by phb-shiyige-fw** [comment]
@an1018 希望你可以帮助我 谢谢 单卡训练非常的慢 很头疼

**Comment by phb-shiyige-fw** [comment]
@an1018  希望你可以解答我的问题，单卡训练识别非常缓慢，很头疼

另外还有几个问题想问：
1.paddle是不是对ubuntu的版本也有限制？我版本是22.04好像也无法进行训练
2.如果以上的问题都没办法解决，我应该用什么来实现多卡训练呢？

求解答！非常感谢！

**Comment by an1018** [comment]
Windows目前支持单卡， 在ubuntu训练遇到什么问题呢
可以查看CUDA版本，参考这个文档安装paddlepaddle-gpu版本，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

输入import paddle ，再输入 paddle.utils.run_check()，如果出现PaddlePaddle is installed successfully!，说明成功安装。

**Comment by phb-shiyige-fw** [comment]
> Windows目前支持单卡， 在ubuntu训练遇到什么问题呢 可以查看CUDA版本，参考这个文档安装paddlepaddle-gpu版本，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> 
> 输入import paddle ，再输入 paddle.utils.run_check()，如果出现PaddlePaddle is installed successfully!，说明成功安装。

我的ubuntu版本是22.04的 我看了文档好像是不兼容22.04版本 无法进行安装训练

**Comment by an1018** [comment]
可以在https://github.com/PaddlePaddle/Paddle提个issue，看看有没有解决办法

**Comment by JackLee1** [comment]
装个NCCL就行了，我之前也碰到这个问题。

**Comment by phb-shiyige-fw** [comment]
> 装个NCCL就行了，我之前也碰到这个问题。

windows也可以吗？我看到有些地方说windows系统不支持NCCL？
