### ISSUE TITLE
数据处理代码有问题

### ISSUE THREAD

**Issue by hanyong-max** [PaddlePaddle/PaddleOCR#8431]
![image](https://user-images.githubusercontent.com/54493615/203679455-06893e91-d31c-445f-b6cb-3be31ce16b41.png)

import cv2
import numpy as np

def get_rotate_crop_image(img, points):
    '''
    img_height, img_width = img.shape[0:2]
    left = int(np.min(points[:, 0]))
    right = int(np.max(points[:, 0]))
    top = int(np.min(points[:, 1]))
    bottom = int(np.max(points[:, 1]))
    img_crop = img[top:bottom, left:right, :].copy()
    points[:, 0] = points[:, 0] - left
    points[:, 1] = points[:, 1] - top
    '''
    assert len(points) == 4, "shape of points must be 4*2"
    img_crop_width = int(
        max(
            np.linalg.norm(points[0] - points[1]),
            np.linalg.norm(points[2] - points[3])))
    img_crop_height = int(
        max(
            np.linalg.norm(points[0] - points[3]),
            np.linalg.norm(points[1] - points[2])))
    pts_std = np.float32([[0, 0], [img_crop_width, 0],
                          [img_crop_width, img_crop_height],
                          [0, img_crop_height]])
    M = cv2.getPerspectiveTransform(points, pts_std)
    dst_img = cv2.warpPerspective(
        img,
        M, (img_crop_width, img_crop_height),
        borderMode=cv2.BORDER_REPLICATE,
        flags=cv2.INTER_CUBIC)
    dst_img_height, dst_img_width = dst_img.shape[0:2]
    if dst_img_height * 1.0 / dst_img_width >= 1.5:
        dst_img = np.rot90(dst_img)
    return dst_img

def run(data_dir, label_file, save_dir):
    datas = open(label_file, 'r').readlines()
    for idx, line in enumerate(datas):
        img_path, label = line.strip().split('\t')
        img_path = os.path.join(data_dir, img_path)

        label = json.loads(label)
        src_im = cv2.imread(img_path)
        if src_im is None:
            continue

        for anno in label:
            seal_box = anno['seal_box']
            txt_boxes = anno['polys']
            crop_im = get_rotate_crop_image(src_im, text_boxes)

            save_path = os.path.join(save_dir, f'{idx}.png')
            if not os.path.exists(save_dir):
                os.makedirs(save_dir)
            # print(src_im.shape)
            cv2.imwrite(save_path, crop_im)

这段印章弯曲文字识别预处理代码怎么使用？？？

**Comment by huangjun12** [comment]
传入数据标签路径和保存路径，跑一下run函数就好了

**Comment by dengmingD** [comment]
> 传入数据标签路径和保存路径，跑一下run函数就好了

代码确实有问题，
seal_box = anno['seal_box']
txt_boxes = anno['polys']                        #这里应该是text_boxes
crop_im = get_rotate_crop_image(src_im, text_boxes)
但是polys的size，是>= 4*2，所有会报错

**Comment by haimeilv** [comment]
我的len(points)是1.变为numpy以后显示是（1,14,2）（每个印章标注14个点），像这种我该怎么改呢？

**Comment by zhaoqf-cq** [comment]
> > 传入数据标签路径和保存路径，跑一下run函数就好了
> 
> 代码确实有问题， seal_box = anno['seal_box'] txt_boxes = anno['polys'] #这里应该是text_boxes crop_im = get_rotate_crop_image(src_im, text_boxes) 但是polys的size，是>= 4*2，所有会报错

请问一下，这里剪裁出来的是 一整个章？还是说只是 章里面 标注的文字部分？
