### ISSUE TITLE
python det=False 失败

### ISSUE THREAD

**Issue by dly667** [PaddlePaddle/PaddleOCR#8434]
paddle-bfloat         0.1.7
paddleocr             2.6.1.0
paddlepaddle          2.4.0

- 运行指令/Command Code：
```img_name = '111.jpeg'
    img_path = project_path + '/data/test_ocr/' + img_name
    with open(img_path, 'rb') as file:
        rs = file.read()
        ocr = PaddleOCR(use_angle_cls=True)
        print(ocr.ocr(rs, det=True))
```

打印日志：
[2022/11/24 14:24:57] ppocr DEBUG: dt_boxes num : 32, elapse : 0.6067647933959961
[2022/11/24 14:24:57] ppocr DEBUG: cls num  : 32, elapse : 0.2970926761627197
[2022/11/24 14:25:01] ppocr DEBUG: rec_res num  : 32, elapse : 4.114534854888916
[[[[[48.0, 19.0], [166.0, 9.0], [170.0, 53.0], [52.0, 63.0]], ('电话', 0.9909850358963013)], [[[87.0, 89.0], [305.0, 70.0], [308.0, 95.0], [89.0, 115.0]], ('1567732580', 0.7350081205368042)], [[[87.0, 182.0], [327.0, 161.0], [329.0,89.0], [89.0, 209.0]], ('17857474316', 0.9607715010643005)], [[[80.0, 215.0], [442.0, 185.0], [444.0, 215.0], [83.0, 245.0]], ('0快递送餐16人标记过', 0.8068122267723083)], [[[93.0, 288.0], [345.0, 263.0], [348.0, 291.0], [96.0, 316.3173534370', 0.9382299184799194)], [[[89.0, 325.0], [464.0, 287.0], [467.0, 317.0], [93.0, 355.0]], ('D四快递送餐16人标记过', 0.9105818867683411)], [[[635.0, 364.0], [700.0, 356.0], [704.0, 385.0], [639.0, 393.0]], ('9/11', 0.9838343)], [[[97.0, 403.0], [364.0, 375.0], [368.0, 406.0], [100.0, 433.0]], ('13305770726', 0.870990514755249)], [[[669.0, 445.0], [708.0, 436.0], [720.0, 485.0], [682.0, 494.0]], ('3', 0.9991298317909241)], [[[432.0, 474.0], [472.0, 466.0], [482.0, 514.0], [442.0, 522.0]], ('2', 0.999545156955719)], [[[678.0, 494.0], [728.0, 488.0], [731.0, 515.0], [682.0, 522.0]], ('DEF', 0.994688093662262)], [[[437.0, 526.0], [491.0, 518.0], [496.0, 546.0], [441.0, 555.0]], ('ABC', 0.9891228675842285)], [[[718.0, 562.0], [750.0, 562.0], [750.0, 606.0], [718.0, 606.0]], ('6', 0.9772176146507263)], [[[459.0, 597.0], [499.0, 591.0], [506.0, 642.0], [466.0, 648.0]], ('5', 0.9993268251419067)], [[[710.0, 617.0], [774.0, 609.0], [778.0, 638.0], [714.0, 646.0]], ('MNO', 0.9925382733345032)], [[[193.0, 633.0], [239.0, 633.0], [239.0, 682.0], [193.0, 682.0]], ('4', 0.9626080989837646)], [[[463.0, 655.0], [513.0, 648.0], [517.0, 677.0], [467.0, 684.0]], ('JKL', 0.9937567114830017)], [[[190.0, 694.0], [245.0, 688.0], [249.0, 718.0], [194.0, 724.0]], ('GHI', 0.9112440943717957)], [[[114.0, 871.0], [396.0, 824.0], [405.0, 872.0], [122.0, 919.0]], ('MEIDIMEI', 0.9409836530685425)], [[[123.0, 985.0], [639.0, 889.0], [647.0, 929.0], [131.0, 1025.0]], ('MEID:A00000B66575EB', 0.9527776837348938)], [[[128.0, 1042.0], [501.0, 971.0], [509.0, 1012.0], [136.0, 1083.0]], ('PESN:80CBB91A', 0.8923845291137695)], [[[132.0, 1101.0], [682.0, 992.0], [690.0, 1034.0], [141.0, 1143.0]], ('IMEI1863164040836488', 0.8852118253707886)], [[[136.0, 1162.0], [695.0, 1047.0], [704.0, 1089.0], [145.0, 1204.0]], ('IME12:863164040853962', 0.8810362815856934)], [[[138.0, 1225.0], [701.0, 1105.0], [712.0, 1152.0], [148.0, 1272.0]], ('SN:TTNDU20417002054', 0.9511720538139343)], [[[556.0, 1259.0], [667.0, 1233.0], [682.0, 1297.0], [571.0, 1323.0]], ('确定', 0.9963499307632446)]]]

det设置为Flase后
```print(ocr.ocr(rs, det=Flase))```
打印日志：
[[('', 0.0)]]

**Comment by wangshijia0523** [comment]
我也存在同样的问题，查看源码可能是这一部分出现了问题：               
 if self.use_angle_cls and cls:
                    img, cls_res_tmp, elapse = self.text_classifier(img)
                    if not rec:
                        cls_res.append(cls_res_tmp)
                rec_res, elapse = self.text_recognizer(img)
