### ISSUE TITLE
使用自定义数据集训练的模型只能识别训练集中的字符，不在训练集中的字符识别不了

### ISSUE THREAD

**Issue by xiaoxiaodetian** [PaddlePaddle/PaddleOCR#8435]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
使用自定义数据集训练的模型，pretrain_models用的是ch_PP-OCRv3_rec_train，但是测试模型时不在训练集中的中文字符识别不了

**Comment by drenched9** [comment]
首先要确认自己的数据集中包含哪些文字，然后再将涉及的文字组成一个新的字符集，将配置文件中的Global.character_dict_path的值改成你这个新的字符集路径（否则你训练使用的字符集一直是原来的字符集，自然不会识别到这些字符集以外的文字了）
其次就是看训练的模型的评估结果，如果hmean这些指标太低就说明没有训练好呗，就再看看哪些地方可以优化。
