### ISSUE TITLE
PaddleOCR C++部署加载识别模型报错

### ISSUE THREAD

**Issue by softdswyd** [PaddlePaddle/PaddleOCR#8436]
- 系统环境/System Environment：CPU：龙芯3A3000，操作系统：Kylin-V10

- 版本号/Version：Paddle：2.2  PaddleOCR： 2.6 OpenCV：3.4.7，均已编译链接成功，并在PaddleOCR的cpp_deploy目录下生成了ppocr程序。识别模型版本为：ch_PP-OCRv3，识别推理模型存放目录为cpp_deploy/inference/rec，绝对路径中不包含中文或空格。

- 运行指令/Command Code：./build/ppocr --det_model_dir=inference/det --rec_model_dir==inference/rec --cls_model_dir=inference/cls --image_dir=../../doc/imgs/12.jpg --use_angle_cls=true --det=true --rec=true --cls=true

- 完整报错/Complete Error Message：

WARNING: Logging before InitGoogleLogging() is written to STDERR
I1124 14:02:03.867100 26340 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
I1124 14:02:03.999029 26340 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1124 14:02:04.108842 26340 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I1124 14:02:04.108945 26340 memory_optimize_pass.cc:216] Cluster name : conv2d_252.tmp_0  size: 384
I1124 14:02:04.108979 26340 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I1124 14:02:04.109027 26340 memory_optimize_pass.cc:216] Cluster name : tmp_3  size: 384
I1124 14:02:04.109058 26340 memory_optimize_pass.cc:216] Cluster name : tmp_7  size: 384
I1124 14:02:04.109089 26340 memory_optimize_pass.cc:216] Cluster name : batch_norm_46.tmp_3  size: 1920
I1124 14:02:04.109119 26340 memory_optimize_pass.cc:216] Cluster name : batch_norm_44.tmp_3  size: 1920
I1124 14:02:04.109149 26340 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I1124 14:02:04.109180 26340 memory_optimize_pass.cc:216] Cluster name : hardswish_16.tmp_0  size: 1920
I1124 14:02:04.109210 26340 memory_optimize_pass.cc:216] Cluster name : batch_norm_44.tmp_1  size: 1920
--- Running analysis [ir_graph_to_program_pass]
I1124 14:02:04.687273 26340 analysis_predictor.cc:714] ======= optimize end =======
I1124 14:02:04.708756 26340 naive_executor.cc:98] ---  skip [feed], feed -> x
I1124 14:02:04.733206 26340 naive_executor.cc:98] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
In PP-OCRv3, default rec_img_h is 48,if you use other model, you should set the param rec_img_h=32
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::LoadProgramDesc()
6   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file =inference/rec/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at /home/paddle/Paddle/paddle/fluid/inference/api/analysis_predictor.cc:1116)

可以确认，分类器模型是可以正常加载的，但是识别模型加载出错。也试过了ch_ppocr_mobile_v2.0的识别模型，同样是报加载模型错误。此外，在另外一台设备（鲲鹏920+KylinV10）使用相同的配置可以正常运行。

**Comment by FreedomLiX** [comment]
@softdswyd  可以尝试一下：[https://github.com/PaddlePaddle/Paddle/issues/49500](url)
