### ISSUE TITLE
ValueError: could not convert string to float: 'p2o.DynamicDimension.1'

### ISSUE THREAD

**Issue by lgy2830** [PaddlePaddle/PaddleOCR#8437]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux ubuntu18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/model.onnx  --rec_model_dir=./inference/rec_onnx/model.onnx  --cls_model_dir=./inference/cls_onnx/model.onnx  --image_dir=doc/imgs_en/img_12.jpg --rec_char_dict_path=ppocr/utils/en_dict.txt
- 完整报错/Complete Error Message：
python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/model.onnx  --rec_model_dir=./inference/rec_onnx/model.onnx  --cls_model_dir=./inference/cls_onnx/model.onnx  --image_dir=doc/imgs_en/img_12.jpg --rec_char_dict_path=ppocr/utils/en_dict.txt
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
<class 'str'>
p2o.DynamicDimension.1
[2022/11/24 15:46:46] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 180, in main
    dt_boxes, rec_res, time_dict = text_sys(img)
  File "tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/lgy/桌面/PaddleOCR/tools/infer/predict_det.py", line 234, in __call__
    data = transform(data, self.preprocess_op)
  File "/home/lgy/桌面/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/lgy/桌面/PaddleOCR/ppocr/data/imaug/operators.py", line 238, in __call__
    img, [ratio_h, ratio_w] = self.resize_image_type1(img)
  File "/home/lgy/桌面/PaddleOCR/ppocr/data/imaug/operators.py", line 256, in resize_image_type1
    ratio_h = float(resize_h) / ori_h
ValueError: could not convert string to float: 'p2o.DynamicDimension.

我在用该代码转换onnx模型后,用代码示例的命令测试onnx模型,出现报错
并且
python tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
> --det_model_dir=./inference/det_onnx/model.onnx  \
> --rec_model_dir=./inference/rec_onnx/model.onnx  \
> --cls_model_dir=./inference/cls_onnx/model.onnx  \
> --image_dir=doc/imgs_en/img_12.jpg \
> --rec_char_dict_path=ppocr/utils/en_dict.txt
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/lgy/anaconda3/envs/pp-vehicle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
<class 'str'>
p2o.DynamicDimension.1
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 140, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/lgy/桌面/PaddleOCR/tools/infer/predict_det.py", line 155, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

我的onnx模型转换出来,输入输入比较奇怪,输入输出的纬度里有一些奇怪的参数,比如p2o.DynamicDimension.1

**Comment by entropy2333** [comment]
遇到了同样的情况，参考[Paddle2ONNX文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme_ch.md)转换PP-OCRv3的识别模型。

转换命令
```bash
paddle2onnx --model_dir ./inference/ch_PP-OCRv3_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/det_onnx/model.onnx \
--opset_version 10 \
--input_shape_dict="{'x':[-1,3,-1,-1]}" \
--enable_onnx_checker True
```

加载onnx模型，可以看到模型的输入shape包含`p2o.DynamicDimension.x`，因而在[tools/predict.py#L146](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_det.py#L146)处报错。
```python
>>> import onnxruntime as ort
>>> sess = ort.InferenceSession("inference/det_onnx/model.onnx")
>>> sess.get_inputs()[0].shape
['p2o.DynamicDimension.0', 3, 'p2o.DynamicDimension.1', 'p2o.DynamicDimension.2']
```

**Comment by younger-diao** [comment]
onnx推理我也遇到同样问题，请问解决了吗

**Comment by wktxdy** [comment]
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 140, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/kunwang/project_2022/LPR/PaddleOCR-release-2.6/tools/infer/predict_det.py", line 146, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by QQR1** [comment]
遇到同样问题+1，催更

**Comment by wktxdy** [comment]
> * p2o.DynamicDimension.1

这个是动态维度，只要运行[paddle_infer_shape.py](https://github.com/jiangjiajun/PaddleUtils/blob/main/paddle/paddle_infer_shape.py)，固定模型输入之后，再转onnx并且进行推理就不会出错了

**Comment by wktxdy** [comment]
> 遇到了同样的情况，参考[Paddle2ONNX文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme_ch.md)转换PP-OCRv3的识别模型。
> 
> 转换命令
> 
> ```shell
> paddle2onnx --model_dir ./inference/ch_PP-OCRv3_det_infer \
> --model_filename inference.pdmodel \
> --params_filename inference.pdiparams \
> --save_file ./inference/det_onnx/model.onnx \
> --opset_version 10 \
> --input_shape_dict="{'x':[-1,3,-1,-1]}" \
> --enable_onnx_checker True
> ```
> 
> 加载onnx模型，可以看到模型的输入shape包含`p2o.DynamicDimension.x`，因而在[tools/predict.py#L146](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_det.py#L146)处报错。
> 
> ```python
> >>> import onnxruntime as ort
> >>> sess = ort.InferenceSession("inference/det_onnx/model.onnx")
> >>> sess.get_inputs()[0].shape
> ['p2o.DynamicDimension.0', 3, 'p2o.DynamicDimension.1', 'p2o.DynamicDimension.2']
> ```

对paddle模型固定一下输入即可解决

**Comment by StaHRocK1992** [comment]
I'm facing the same issue. Is there any solution for that problem? I did the export exactly like in the tutorial. I also tried to put in a fixed shape. Nothing works for me.

**Comment by xxysxka** [comment]
I solved the problem by using 

paddle2onnx = 0.9.0 

```
paddle2onnx --model_dir ./inference/ch_PP-OCRv3_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/det_onnx/model.onnx \
--opset_version 10 \
--input_shape_dict="{'x':[-1,3,-1,-1]}" \
--enable_onnx_checker True
```

**Comment by StaHRocK1992** [comment]
@xxysxka Thanks for that approach, I'll test it. With the newest version I'll fixed the issue with setting the variables img_h, img_w and w in the source code to a fixed value.

**Comment by MagicCodess** [comment]
> 

has this issue been fixed?

**Comment by StaHRocK1992** [comment]
@MagicCodess couldn't test it by now. But as I mentioned above, you can set the values to a fixed size and then it should work as well.
