### ISSUE TITLE
中文版面分析如何标注自己的数据集得到相应的json文件，还是使用PPOCRLabel吗？？？

### ISSUE THREAD

**Issue by hanyong-max** [PaddlePaddle/PaddleOCR#8438]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Fissionalist** [comment]
目前只能用其他标注工具吧：[数据标注工具](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/data_annotation.md)
