### ISSUE TITLE
如何在jetson上使用python语言去做tensorrt部署paddleocr

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#8439]
如何在jetson上使用python语言去做tensorrt部署paddleocr，有参考代码吗

**Comment by gavinfaimdata** [comment]
I want to know this as well. I wasn't able to convert SVTR before and gave up.

**Comment by futureflsl** [comment]
> I want to know this as well. I wasn't able to convert SVTR before and gave up.

paddle has tensorrt.we can use it,but loading weights to slowly when use_tensorrt set True
