### ISSUE TITLE
空格的识别

### ISSUE THREAD

**Issue by nwdxlgzs** [PaddlePaddle/PaddleOCR#844]
至少我在用esayedge时发现对空格识别几乎没有支持，所有英文连在一起了。

**Comment by binwang672012** [comment]
不晓得为什么这样明显的问题都没有解决就放出来.

**Comment by LDOUBLEV** [comment]
> 不晓得为什么这样明显的问题都没有解决就放出来.

easyedge上线节奏慢了一些，现在repo里的轻量模型是支持空格的，适用下呢？

**Comment by LDOUBLEV** [comment]
> 不晓得为什么这样明显的问题都没有解决就放出来.

小姐姐头发都熬秃了在更新模型，而且英文支持空格的模型已经更新了，在model_list.md中，可以看下效果
![image](https://user-images.githubusercontent.com/26592129/94250068-4dbfb800-ff53-11ea-91e1-5cf73ea6fee4.png)
