### ISSUE TITLE
PPOCRLabel导出识别结果，裁剪的图片有些变换了方向

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8443]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
- 系统环境/System Environment：
- 版本号/Version：2.6 Paddle：  PaddleOCR： 问题相关组件/Related components：PPOCRLabel导出识别结果
当我对图片进行标注之后，导出识别结果，会导出crop_img，有些图片的角度变换了，比如原先是正向的，现在变成旋转90度或者旋转180度，请问是什么原因呢？影响识别结果吗？
例子：这里我标注的数据是90度的，一crop保存图片就变成横着的了
![42e7f2e77842a8923316e3e5629bddd](https://user-images.githubusercontent.com/80883358/205529310-a8641626-2b7e-4ce3-9411-42957ba3a80e.png)

**Comment by jingsongliujing** [comment]
你是不是默认开启了paddlecls?

**Comment by Currf** [comment]
> 你是不是默认开启了paddlecls?

你好，请问paddlecls在哪里修改呢？

**Comment by Evezerest** [comment]
可以看一下图片属性中的角度是否有旋转，有时候预览的效果不是实际的

**Comment by Currf** [comment]
> 可以看一下图片属性中的角度是否有旋转，有时候预览的效果不是实际的

你好，可以详细说一下吗？我在上方更新了图片，不是很理解你说的意思

**Comment by 123zhang-bit** [comment]
注释掉两行代码就行了，代码位置PPOCRLabel/libs/utils.py
![屏幕截图 2024-03-05 104825](https://github.com/PaddlePaddle/PaddleOCR/assets/68312727/a954b2e2-48c8-45e0-8eb0-9382901418bd)
这两行代码的意思是判断你的标注框的高除以宽是否超过1.5，如果超过则进行逆时针旋转90度

**Comment by 123zhang-bit** [comment]
![屏幕截图 2024-03-05 104825](https://github.com/PaddlePaddle/PaddleOCR/assets/68312727/69ced9ea-ce48-4045-9d9c-6717eee184ff)
