### ISSUE TITLE
在评估模型阶段出现这个问题，是我配置的有问题吗

### ISSUE THREAD

**Issue by YulloQF** [PaddlePaddle/PaddleOCR#8447]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

使用的指令为：python tools/eval.py -c configs/det/det_mv3_db.yml  -o Global.checkpoints="./output/det_db/best_accuracy" PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5

出现的问题：
![1](https://user-images.githubusercontent.com/111737275/203939326-cc90097e-b2d7-42b7-bbed-7c28bd8eaa62.jpg)

有没有什么解决方案，求大佬救救孩子

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
报错信息很明确，检查下文件路径是否正确
