### ISSUE TITLE
使用infer_det.py能够正常推理，将模型变为inference模型后，使用predict_det.py出现段错误

### ISSUE THREAD

**Issue by hzj0913** [PaddlePaddle/PaddleOCR#8448]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.0.1  
- 运行指令/Command Code：python3 tools/infer/predict_det.py --det_algorithm="EAST" --det_model_dir="./inference/det_east/" --image_dir="/data1/hzj/mmrotate/data/GangPi-random-rotate-meanspadding-src-90180270-new/test/images/20190418003509-1-1.bmp" --use_gpu=True
- 完整报错/Complete Error Message：
- --------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1669363051 (unix time) try "date -d @1669363051" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1434 (TID 0x7f247212f740) from PID 0 ***]

Segmentation fault (core dumped)

使用：python3 tools/infer_det.py -c configs/det/det_mv3_east.yml -o Global.infer_img="/data1/hzj/mmrotate/data/GangPi-random-rotate-meanspadding-src-90180270-new/test/images/20190418003509-1-1.bmp" Global.pretrained_model="./output/east_mv3/best_accuracy"正常预测

使用：python3 tools/export_model.py -c configs/det/det_mv3_east.yml -o Global.pretrained_model="./output/east_mv3/best_accuracy" Global.save_inference_dir="./inference/det_east"进行模型转换

**Comment by MissPenguin** [comment]
我这边用官方模型无法复现您这个问题呢，

**Comment by printfxs** [comment]
我用的infer_rec.py正常，用predict_rec.py也是同样的错误，求指导。

**Comment by printfxs** [comment]
@MissPenguin
