### ISSUE TITLE
How to visual the model structure

### ISSUE THREAD

**Issue by ausk** [PaddlePaddle/PaddleOCR#845]
Hi, thank contributors, the lastest ocr model detects and recognises so awosome. 

To better understand the network structure, I want to visual the `predictor` of `TextDetector`, `TextRecognizer`.  If I print the predictor in pdb, it echos:
```
(Pdb) predictor
<paddle.fluid.core_avx.AnalysisPredictor object at 0x000001B81C986A
```

So, how can I visual the predictor's network structure(like pytorch to print, or netron to visual)?

**Comment by tink2123** [comment]
You can user  -o Global.debug=Ture to visual network structure.

https://github.com/PaddlePaddle/PaddleOCR/blob/1fd763f89b49863a5ee2846d33155dae19902a28/tools/train.py#L80-L86

**Comment by ausk** [comment]
@tink2123 Thank you for replay.
I notice the code you post is in `train.py`, and If I use `summary` in `infer` mode, it raises error:
```
(Pdb) from paddle.fluid.contrib.model_stat import summary
(Pdb) summary(predictor)
*** AttributeError: 'paddle.fluid.core_avx.AnalysisPredictor' object has no attribute 'blocks'
```

Is it to say, we can only use `summary` to visual the model structure in `train` mode? Do you know, is there any way to visual the structure in `infer` mode?

**Comment by tink2123** [comment]
Sorry, the network structure cannot be viewed in the inference model.

Maybe you can try to use infer_rec  so that you can view the network structure by `summary`

Add `summary(rec_mode)` after
https://github.com/PaddlePaddle/PaddleOCR/blob/1fd763f89b49863a5ee2846d33155dae19902a28/tools/infer_rec.py#L66

The prediction command is：
```
python3 tools/infer_rec.py -c configs/rec/rec_chinese_lite_train.yml -o Global.checkpoints={path/to/weights}/best_accuracy Global.infer_img=doc/imgs_words/ch/word_1.jpg
```

**Comment by ausk** [comment]
@tink2123  Thank you.

Have a nice day!
