### ISSUE TITLE
将剪切的图片保存到c盘时出现错误，没有权限保存，各位大佬有什么解决方法

### ISSUE THREAD

**Issue by YulloQF** [PaddlePaddle/PaddleOCR#8450]
请提供下述完整信息以便快速定位问题
bug图片：![dw](https://user-images.githubusercontent.com/111737275/203995717-12bbf48e-57db-43b3-afd8-3e7bbc9a911a.jpg)
/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
可能c盘没有读写权限？放到别的盘试试呢
