### ISSUE TITLE
麻烦将class ConvBNLayer整合成一个，目前有9个同名类,参数不同，移植模型权重比对费时

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/PaddleOCR#8451]
麻烦将class ConvBNLayer整合成一个，目前有9个同名类,参数不同，移植模型权重比对费时
https://github.com/PaddlePaddle/PaddleOCR/search?q=class+ConvBNLayer

**Comment by LDOUBLEV** [comment]
感谢反馈，我们近期会整合下
