### ISSUE TITLE
安装paddleocr报错

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8452]
![image](https://user-images.githubusercontent.com/67177370/204070133-c06b6a04-c861-4d82-94a6-7623190446ee.png)
conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by jingsongliujing** [comment]
参考官方的安装方法吧：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
