### ISSUE TITLE
在aistudio旧版的notebook上，打包文件夹时出现 打包失败，bad request 我的项目链接是：我发现了一篇高质量的实训项目，使用免费算力即可一键运行，还能额外获取8小时免费GPU运行时长，快来Fork一下体验吧。 煤炭货车上的检测项目：https://aistudio.baidu.com/aistudio/projectdetail/3800414?sUid=1064030&shared=1&ts=1669438574383

### ISSUE THREAD

**Issue by chenshanhuo** [PaddlePaddle/PaddleOCR#8453]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by jingsongliujing** [comment]
旧版本的aistudio空间被压缩了，建议使用新版本的aistudio

**Comment by chenshanhuo** [comment]
> 旧版本的aistudio空间被压缩了，建议使用新版本的aistudio

请问你说的是那个BML Codelab吗？
