### ISSUE TITLE
用自己的数据训练SER，效果不好，都没有往我标注的地方画框，为啥呢？

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#8456]
一、训练：python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.pretrained=True
![图片](https://user-images.githubusercontent.com/6648329/204113733-7693b4e8-bca9-48f8-810f-1cc5adf8f05c.png)

二、我试着预测：
    python tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy Global.infer_img=./train_data/XFUND/zh_train/image/IMG_20221026_093350.jpg
![图片](https://user-images.githubusercontent.com/6648329/204113799-e135c567-9dc8-4fc5-8d67-ebb8c8ce40ee.png)

![图片](https://user-images.githubusercontent.com/6648329/204113898-733b8e64-4215-47ce-88b8-d1a3ead15aba.png)

三、看看我自己的标注图如下（明显与上面识别出来的相差太远了）：
![图片](https://user-images.githubusercontent.com/6648329/204114184-f0956fd7-918a-4cac-aa45-8e64131e6f1b.png)

[{
	"transcription": "江苏中烟工业有限责任公司",
	"label": "header",
	"points": [
		[1765, 537],
		[2950, 565],
		[2947, 658],
		[1762, 630]
	],
	"id": 0,
	"linking": []
}, {
	"transcription": "年　份",
	"label": "question",
	"points": [
		[1363, 731],
		[1607, 731],
		[1607, 800],
		[1363, 800]
	],
	"id": 1,
	"linking": [
		[1, 2]
	]
}, {
	"transcription": "2020",
	"label": "answer",
	"points": [
		[1946, 738],
		[2082, 738],
		[2082, 808],
		[1946, 808]
	],
	"id": 2,
	"linking": [
		[1, 2]
	]
}, {
	"transcription": "等级",
	"label": "question",
	"points": [
		[2386, 838],
		[2688, 848],
		[2684, 977],
		[2381, 967]
	],
	"id": 17,
	"linking": [
		[17, 18]
	]
}, {
	"transcription": "产地",
	"label": "question",
	"points": [
		[1359, 859],
		[1607, 859],
		[1607, 922],
		[1359, 922]
	],
	"id": 3,
	"linking": [
		[3, 4]
	]
}, {
	"transcription": "福建三明宁化",
	"label": "answer",
	"points": [
		[1839, 871],
		[2193, 871],
		[2193, 937],
		[1839, 937]
	],
	"id": 4,
	"linking": [
		[3, 4]
	]
}, {
	"transcription": "BCCFAH",
	"label": "answer",
	"points": [
		[2863, 866],
		[3216, 875],
		[3213, 972],
		[2861, 963]
	],
	"id": 18,
	"linking": [
		[17, 18]
	]
}, {
	"transcription": "主类型",
	"label": "question",
	"points": [
		[197, 967],
		[299, 973],
		[293, 1015],
		[189, 1010]
	],
	"id": 25,
	"linking": [
		[25, 26]
	]
}, {
	"transcription": "2020",
	"label": "answer",
	"points": [
		[731, 983],
		[819, 981],
		[819, 1019],
		[730, 1015]
	],
	"id": 52,
	"linking": [
		[51, 52]
	]
}, {
	"transcription": "类型",
	"label": "question",
	"points": [
		[1359, 983],
		[1607, 983],
		[1607, 1059],
		[1359, 1059]
	],
	"id": 5,
	"linking": [
		[5, 6]
	]
}, {
	"transcription": "烤烟",
	"label": "answer",
	"points": [
		[1953, 995],
		[2082, 995],
		[2082, 1069],
		[1953, 1069]
	],
	"id": 6,
	"linking": [
		[5, 6]
	]
}, {
	"transcription": "主品种",
	"label": "question",
	"points": [
		[194, 1026],
		[289, 1026],
		[289, 1072],
		[194, 1072]
	],
	"id": 27,
	"linking": [
		[27, 28]
	]
}, {
	"transcription": "主等级",
	"label": "question",
	"points": [
		[611, 1032],
		[708, 1038],
		[706, 1079],
		[609, 1075]
	],
	"id": 53,
	"linking": [
		[53, 54]
	]
}, {
	"transcription": "福建三明宁化",
	"label": "answer",
	"points": [
		[304, 1086],
		[509, 1088],
		[509, 1131],
		[303, 1128]
	],
	"id": 30,
	"linking": [
		[29, 30]
	]
}, {
	"transcription": "品种",
	"label": "question",
	"points": [
		[1355, 1123],
		[1607, 1123],
		[1607, 1192],
		[1355, 1192]
	],
	"id": 7,
	"linking": [
		[7, 8]
	]
}, {
	"transcription": "CB-1",
	"label": "answer",
	"points": [
		[1957, 1126],
		[2088, 1136],
		[2083, 1198],
		[1952, 1188]
	],
	"id": 8,
	"linking": [
		[7, 8]
	]
}, {
	"transcription": "混打片烟",
	"label": "answer",
	"points": [
		[298, 1152],
		[441, 1151],
		[440, 1194],
		[294, 1189]
	],
	"id": 32,
	"linking": [
		[31, 32]
	]
}, {
	"transcription": "A线-丙班",
	"label": "answer",
	"points": [
		[720, 1158],
		[869, 1157],
		[865, 1205],
		[716, 1195]
	],
	"id": 56,
	"linking": [
		[55, 56]
	]
}, {
	"transcription": "箱号",
	"label": "question",
	"points": [
		[2428, 1139],
		[2691, 1139],
		[2691, 1206],
		[2428, 1206]
	],
	"id": 19,
	"linking": [
		[19, 20]
	]
}, {
	"transcription": "0528",
	"label": "answer",
	"points": [
		[2998, 1143],
		[3131, 1143],
		[3131, 1213],
		[2998, 1213]
	],
	"id": 20,
	"linking": [
		[19, 20]
	]
}, {
	"transcription": "202011JS008",
	"label": "answer",
	"points": [
		[294, 1209],
		[498, 1216],
		[489, 1251],
		[289, 1248]
	],
	"id": 34,
	"linking": [
		[33, 34]
	]
}, {
	"transcription": "箱号",
	"label": "question",
	"points": [
		[589, 1213],
		[688, 1213],
		[688, 1251],
		[589, 1251]
	],
	"id": 57,
	"linking": [
		[57, 58]
	]
}, {
	"transcription": "毛重",
	"label": "question",
	"points": [
		[156, 1263],
		[263, 1267],
		[256, 1306],
		[156, 1306]
	],
	"id": 35,
	"linking": [
		[35, 36]
	]
}, {
	"transcription": "200.00KG",
	"label": "answer",
	"points": [
		[710, 1270],
		[859, 1271],
		[858, 1314],
		[710, 1310]
	],
	"id": 60,
	"linking": [
		[59, 60]
	]
}, {
	"transcription": "毛重",
	"label": "question",
	"points": [
		[1355, 1259],
		[1607, 1259],
		[1607, 1335],
		[1355, 1335]
	],
	"id": 9,
	"linking": [
		[9, 10]
	]
}, {
	"transcription": "净重",
	"label": "question",
	"points": [
		[589, 1275],
		[688, 1275],
		[688, 1310],
		[589, 1310]
	],
	"id": 59,
	"linking": [
		[59, 60]
	]
}, {
	"transcription": "215. 9KG",
	"label": "answer",
	"points": [
		[1911, 1267],
		[2139, 1267],
		[2139, 1333],
		[1911, 1333]
	],
	"id": 10,
	"linking": [
		[9, 10]
	]
}, {
	"transcription": "净 重",
	"label": "question",
	"points": [
		[2436, 1271],
		[2694, 1271],
		[2694, 1358],
		[2436, 1358]
	],
	"id": 21,
	"linking": [
		[21, 22]
	]
}, {
	"transcription": "200KG",
	"label": "answer",
	"points": [
		[3006, 1282],
		[3158, 1282],
		[3158, 1341],
		[3006, 1341]
	],
	"id": 22,
	"linking": [
		[21, 22]
	]
}, {
	"transcription": "生产日期",
	"label": "question",
	"points": [
		[151, 1328],
		[285, 1328],
		[285, 1372],
		[151, 1372]
	],
	"id": 37,
	"linking": [
		[37, 38]
	]
}, {
	"transcription": "班次",
	"label": "question",
	"points": [
		[1349, 1399],
		[1607, 1399],
		[1607, 1469],
		[1349, 1469]
	],
	"id": 11,
	"linking": [
		[11, 12]
	]
}, {
	"transcription": "丙班",
	"label": "answer",
	"points": [
		[1965, 1403],
		[2098, 1403],
		[2098, 1477],
		[1965, 1477]
	],
	"id": 12,
	"linking": [
		[11, 12]
	]
}, {
	"transcription": "加工日期",
	"label": "question",
	"points": [
		[2445, 1398],
		[2687, 1408],
		[2685, 1482],
		[2443, 1472]
	],
	"id": 23,
	"linking": [
		[23, 24]
	]
}, {
	"transcription": "2020. 11.17",
	"label": "answer",
	"points": [
		[2945, 1415],
		[3241, 1415],
		[3241, 1481],
		[2945, 1481]
	],
	"id": 24,
	"linking": [
		[23, 24]
	]
}, {
	"transcription": "类型",
	"label": "question",
	"points": [
		[135, 1452],
		[210, 1452],
		[200, 1493],
		[128, 1492]
	],
	"id": 39,
	"linking": [
		[39, 40]
	]
}, {
	"transcription": "CB-1",
	"label": "answer",
	"points": [
		[218, 1508],
		[304, 1508],
		[304, 1546],
		[218, 1546]
	],
	"id": 42,
	"linking": [
		[41, 42]
	]
}, {
	"transcription": "监打人员",
	"label": "question",
	"points": [
		[1349, 1543],
		[1596, 1543],
		[1596, 1613],
		[1349, 1613]
	],
	"id": 13,
	"linking": [
		[13, 14]
	]
}, {
	"transcription": "王错　朱文战　栗云超　李明",
	"label": "answer",
	"points": [
		[2139, 1543],
		[3018, 1543],
		[3018, 1625],
		[2139, 1625]
	],
	"id": 14,
	"linking": [
		[13, 14]
	]
}, {
	"transcription": "BCCFAH",
	"label": "answer",
	"points": [
		[213, 1558],
		[331, 1558],
		[331, 1600],
		[213, 1600]
	],
	"id": 44,
	"linking": [
		[43, 44]
	]
}, {
	"transcription": "福建三明宁化",
	"label": "answer",
	"points": [
		[213, 1613],
		[422, 1613],
		[422, 1654],
		[213, 1654]
	],
	"id": 46,
	"linking": [
		[45, 46]
	]
}, {
	"transcription": "混打片烟",
	"label": "answer",
	"points": [
		[198, 1675],
		[350, 1675],
		[350, 1716],
		[198, 1716]
	],
	"id": 48,
	"linking": [
		[47, 48]
	]
}, {
	"transcription": "加工单位",
	"label": "question",
	"points": [
		[1341, 1687],
		[1596, 1687],
		[1596, 1757],
		[1341, 1757]
	],
	"id": 15,
	"linking": [
		[15, 16]
	]
}, {
	"transcription": "福建省三明金叶复烤有限公司",
	"label": "answer",
	"points": [
		[2196, 1691],
		[2968, 1691],
		[2968, 1757],
		[2196, 1757]
	],
	"id": 16,
	"linking": [
		[15, 16]
	]
}, {
	"transcription": "2020",
	"label": "answer",
	"points": [
		[193, 1733],
		[277, 1733],
		[277, 1777],
		[193, 1777]
	],
	"id": 50,
	"linking": [
		[49, 50]
	]
}, {
	"transcription": "烤烟",
	"label": "answer",
	"points": [
		[318, 969],
		[409, 969],
		[409, 1012],
		[318, 1012]
	],
	"id": 26,
	"linking": [
		[25, 26]
	]
}, {
	"transcription": "CB-1",
	"label": "answer",
	"points": [
		[305, 1037],
		[401, 1037],
		[401, 1065],
		[305, 1065]
	],
	"id": 28,
	"linking": [
		[27, 28]
	]
}, {
	"transcription": "主年份",
	"label": "question",
	"points": [
		[606, 973],
		[709, 973],
		[709, 1021],
		[606, 1021]
	],
	"id": 51,
	"linking": [
		[51, 52]
	]
}, {
	"transcription": "C3F",
	"label": "answer",
	"points": [
		[730, 1040],
		[798, 1040],
		[798, 1077],
		[730, 1077]
	],
	"id": 54,
	"linking": [
		[53, 54]
	]
}, {
	"transcription": "主产地",
	"label": "question",
	"points": [
		[174, 1084],
		[279, 1084],
		[279, 1132],
		[174, 1132]
	],
	"id": 29,
	"linking": [
		[29, 30]
	]
}, {
	"transcription": "主形态",
	"label": "question",
	"points": [
		[169, 1147],
		[274, 1147],
		[274, 1194],
		[169, 1194]
	],
	"id": 31,
	"linking": [
		[31, 32]
	]
}, {
	"transcription": "生产线",
	"label": "question",
	"points": [
		[590, 1157],
		[695, 1157],
		[695, 1196],
		[590, 1196]
	],
	"id": 55,
	"linking": [
		[55, 56]
	]
}, {
	"transcription": "批次",
	"label": "question",
	"points": [
		[162, 1204],
		[267, 1204],
		[267, 1254],
		[162, 1254]
	],
	"id": 33,
	"linking": [
		[33, 34]
	]
}, {
	"transcription": "215.90KG",
	"label": "answer",
	"points": [
		[285, 1264],
		[431, 1264],
		[431, 1314],
		[285, 1314]
	],
	"id": 36,
	"linking": [
		[35, 36]
	]
}, {
	"transcription": "528",
	"label": "answer",
	"points": [
		[718, 1216],
		[780, 1216],
		[780, 1257],
		[718, 1257]
	],
	"id": 58,
	"linking": [
		[57, 58]
	]
}, {
	"transcription": "2020-11-17",
	"label": "answer",
	"points": [
		[311, 1330],
		[493, 1330],
		[493, 1379],
		[311, 1379]
	],
	"id": 38,
	"linking": [
		[37, 38]
	]
}, {
	"transcription": "烤烟",
	"label": "answer",
	"points": [
		[230, 1449],
		[313, 1449],
		[313, 1494],
		[230, 1494]
	],
	"id": 40,
	"linking": [
		[39, 40]
	]
}, {
	"transcription": "品种",
	"label": "question",
	"points": [
		[121, 1506],
		[197, 1506],
		[197, 1552],
		[121, 1552]
	],
	"id": 41,
	"linking": [
		[41, 42]
	]
}, {
	"transcription": "等级",
	"label": "question",
	"points": [
		[118, 1558],
		[192, 1558],
		[192, 1606],
		[118, 1606]
	],
	"id": 43,
	"linking": [
		[43, 44]
	]
}, {
	"transcription": "产地",
	"label": "question",
	"points": [
		[110, 1612],
		[183, 1612],
		[183, 1658],
		[110, 1658]
	],
	"id": 45,
	"linking": [
		[45, 46]
	]
}, {
	"transcription": "形态",
	"label": "question",
	"points": [
		[100, 1673],
		[177, 1673],
		[177, 1721],
		[100, 1721]
	],
	"id": 47,
	"linking": [
		[47, 48]
	]
}, {
	"transcription": "年份",
	"label": "question",
	"points": [
		[94, 1732],
		[172, 1732],
		[172, 1784],
		[94, 1784]
	],
	"id": 49,
	"linking": [
		[49, 50]
	]
}]

**Comment by andyjpaddle** [comment]
> 训练：python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.pretrained=True ![图片](https://user-images.githubusercontent.com/6648329/204113733-7693b4e8-bca9-48f8-810f-1cc5adf8f05c.png)

看报错应该是机器内存的问题

**Comment by xiaocode337317439** [comment]
> linking

使用PPOCRLabel  kie 是如何标注 linking 的，老哥 求分享？

**Comment by gavinfaimdata** [comment]
try making the eval batch size=1

**Comment by gg22mm** [comment]
> try making the eval batch size=1

这个估计是代码问题：  batch_size_per_card: 1  也没用

**Comment by gg22mm** [comment]
我试了用 aistudio 运行没有问题

**Comment by leoterry-ulrica** [comment]
> 一、训练：python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.pretrained=True ![图片](https://user-images.githubusercontent.com/6648329/204113733-7693b4e8-bca9-48f8-810f-1cc5adf8f05c.png)
> 
> 二、我试着预测： python tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy Global.infer_img=./train_data/XFUND/zh_train/image/IMG_20221026_093350.jpg ![图片](https://user-images.githubusercontent.com/6648329/204113799-e135c567-9dc8-4fc5-8d67-ebb8c8ce40ee.png)
> 
> ![图片](https://user-images.githubusercontent.com/6648329/204113898-733b8e64-4215-47ce-88b8-d1a3ead15aba.png)
> 
> 三、看看我自己的标注图如下（明显与上面识别出来的相差太远了）： ![图片](https://user-images.githubusercontent.com/6648329/204114184-f0956fd7-918a-4cac-aa45-8e64131e6f1b.png)
> 
> [{ "transcription": "江苏中烟工业有限责任公司", "label": "header", "points": [ [1765, 537], [2950, 565], [2947, 658], [1762, 630] ], "id": 0, "linking": [] }, { "transcription": "年　份", "label": "question", "points": [ [1363, 731], [1607, 731], [1607, 800], [1363, 800] ], "id": 1, "linking": [ [1, 2] ] }, { "transcription": "2020", "label": "answer", "points": [ [1946, 738], [2082, 738], [2082, 808], [1946, 808] ], "id": 2, "linking": [ [1, 2] ] }, { "transcription": "等级", "label": "question", "points": [ [2386, 838], [2688, 848], [2684, 977], [2381, 967] ], "id": 17, "linking": [ [17, 18] ] }, { "transcription": "产地", "label": "question", "points": [ [1359, 859], [1607, 859], [1607, 922], [1359, 922] ], "id": 3, "linking": [ [3, 4] ] }, { "transcription": "福建三明宁化", "label": "answer", "points": [ [1839, 871], [2193, 871], [2193, 937], [1839, 937] ], "id": 4, "linking": [ [3, 4] ] }, { "transcription": "BCCFAH", "label": "answer", "points": [ [2863, 866], [3216, 875], [3213, 972], [2861, 963] ], "id": 18, "linking": [ [17, 18] ] }, { "transcription": "主类型", "label": "question", "points": [ [197, 967], [299, 973], [293, 1015], [189, 1010] ], "id": 25, "linking": [ [25, 26] ] }, { "transcription": "2020", "label": "answer", "points": [ [731, 983], [819, 981], [819, 1019], [730, 1015] ], "id": 52, "linking": [ [51, 52] ] }, { "transcription": "类型", "label": "question", "points": [ [1359, 983], [1607, 983], [1607, 1059], [1359, 1059] ], "id": 5, "linking": [ [5, 6] ] }, { "transcription": "烤烟", "label": "answer", "points": [ [1953, 995], [2082, 995], [2082, 1069], [1953, 1069] ], "id": 6, "linking": [ [5, 6] ] }, { "transcription": "主品种", "label": "question", "points": [ [194, 1026], [289, 1026], [289, 1072], [194, 1072] ], "id": 27, "linking": [ [27, 28] ] }, { "transcription": "主等级", "label": "question", "points": [ [611, 1032], [708, 1038], [706, 1079], [609, 1075] ], "id": 53, "linking": [ [53, 54] ] }, { "transcription": "福建三明宁化", "label": "answer", "points": [ [304, 1086], [509, 1088], [509, 1131], [303, 1128] ], "id": 30, "linking": [ [29, 30] ] }, { "transcription": "品种", "label": "question", "points": [ [1355, 1123], [1607, 1123], [1607, 1192], [1355, 1192] ], "id": 7, "linking": [ [7, 8] ] }, { "transcription": "CB-1", "label": "answer", "points": [ [1957, 1126], [2088, 1136], [2083, 1198], [1952, 1188] ], "id": 8, "linking": [ [7, 8] ] }, { "transcription": "混打片烟", "label": "answer", "points": [ [298, 1152], [441, 1151], [440, 1194], [294, 1189] ], "id": 32, "linking": [ [31, 32] ] }, { "transcription": "A线-丙班", "label": "answer", "points": [ [720, 1158], [869, 1157], [865, 1205], [716, 1195] ], "id": 56, "linking": [ [55, 56] ] }, { "transcription": "箱号", "label": "question", "points": [ [2428, 1139], [2691, 1139], [2691, 1206], [2428, 1206] ], "id": 19, "linking": [ [19, 20] ] }, { "transcription": "0528", "label": "answer", "points": [ [2998, 1143], [3131, 1143], [3131, 1213], [2998, 1213] ], "id": 20, "linking": [ [19, 20] ] }, { "transcription": "202011JS008", "label": "answer", "points": [ [294, 1209], [498, 1216], [489, 1251], [289, 1248] ], "id": 34, "linking": [ [33, 34] ] }, { "transcription": "箱号", "label": "question", "points": [ [589, 1213], [688, 1213], [688, 1251], [589, 1251] ], "id": 57, "linking": [ [57, 58] ] }, { "transcription": "毛重", "label": "question", "points": [ [156, 1263], [263, 1267], [256, 1306], [156, 1306] ], "id": 35, "linking": [ [35, 36] ] }, { "transcription": "200.00KG", "label": "answer", "points": [ [710, 1270], [859, 1271], [858, 1314], [710, 1310] ], "id": 60, "linking": [ [59, 60] ] }, { "transcription": "毛重", "label": "question", "points": [ [1355, 1259], [1607, 1259], [1607, 1335], [1355, 1335] ], "id": 9, "linking": [ [9, 10] ] }, { "transcription": "净重", "label": "question", "points": [ [589, 1275], [688, 1275], [688, 1310], [589, 1310] ], "id": 59, "linking": [ [59, 60] ] }, { "transcription": "215. 9KG", "label": "answer", "points": [ [1911, 1267], [2139, 1267], [2139, 1333], [1911, 1333] ], "id": 10, "linking": [ [9, 10] ] }, { "transcription": "净 重", "label": "question", "points": [ [2436, 1271], [2694, 1271], [2694, 1358], [2436, 1358] ], "id": 21, "linking": [ [21, 22] ] }, { "transcription": "200KG", "label": "answer", "points": [ [3006, 1282], [3158, 1282], [3158, 1341], [3006, 1341] ], "id": 22, "linking": [ [21, 22] ] }, { "transcription": "生产日期", "label": "question", "points": [ [151, 1328], [285, 1328], [285, 1372], [151, 1372] ], "id": 37, "linking": [ [37, 38] ] }, { "transcription": "班次", "label": "question", "points": [ [1349, 1399], [1607, 1399], [1607, 1469], [1349, 1469] ], "id": 11, "linking": [ [11, 12] ] }, { "transcription": "丙班", "label": "answer", "points": [ [1965, 1403], [2098, 1403], [2098, 1477], [1965, 1477] ], "id": 12, "linking": [ [11, 12] ] }, { "transcription": "加工日期", "label": "question", "points": [ [2445, 1398], [2687, 1408], [2685, 1482], [2443, 1472] ], "id": 23, "linking": [ [23, 24] ] }, { "transcription": "2020. 11.17", "label": "answer", "points": [ [2945, 1415], [3241, 1415], [3241, 1481], [2945, 1481] ], "id": 24, "linking": [ [23, 24] ] }, { "transcription": "类型", "label": "question", "points": [ [135, 1452], [210, 1452], [200, 1493], [128, 1492] ], "id": 39, "linking": [ [39, 40] ] }, { "transcription": "CB-1", "label": "answer", "points": [ [218, 1508], [304, 1508], [304, 1546], [218, 1546] ], "id": 42, "linking": [ [41, 42] ] }, { "transcription": "监打人员", "label": "question", "points": [ [1349, 1543], [1596, 1543], [1596, 1613], [1349, 1613] ], "id": 13, "linking": [ [13, 14] ] }, { "transcription": "王错　朱文战　栗云超　李明", "label": "answer", "points": [ [2139, 1543], [3018, 1543], [3018, 1625], [2139, 1625] ], "id": 14, "linking": [ [13, 14] ] }, { "transcription": "BCCFAH", "label": "answer", "points": [ [213, 1558], [331, 1558], [331, 1600], [213, 1600] ], "id": 44, "linking": [ [43, 44] ] }, { "transcription": "福建三明宁化", "label": "answer", "points": [ [213, 1613], [422, 1613], [422, 1654], [213, 1654] ], "id": 46, "linking": [ [45, 46] ] }, { "transcription": "混打片烟", "label": "answer", "points": [ [198, 1675], [350, 1675], [350, 1716], [198, 1716] ], "id": 48, "linking": [ [47, 48] ] }, { "transcription": "加工单位", "label": "question", "points": [ [1341, 1687], [1596, 1687], [1596, 1757], [1341, 1757] ], "id": 15, "linking": [ [15, 16] ] }, { "transcription": "福建省三明金叶复烤有限公司", "label": "answer", "points": [ [2196, 1691], [2968, 1691], [2968, 1757], [2196, 1757] ], "id": 16, "linking": [ [15, 16] ] }, { "transcription": "2020", "label": "answer", "points": [ [193, 1733], [277, 1733], [277, 1777], [193, 1777] ], "id": 50, "linking": [ [49, 50] ] }, { "transcription": "烤烟", "label": "answer", "points": [ [318, 969], [409, 969], [409, 1012], [318, 1012] ], "id": 26, "linking": [ [25, 26] ] }, { "transcription": "CB-1", "label": "answer", "points": [ [305, 1037], [401, 1037], [401, 1065], [305, 1065] ], "id": 28, "linking": [ [27, 28] ] }, { "transcription": "主年份", "label": "question", "points": [ [606, 973], [709, 973], [709, 1021], [606, 1021] ], "id": 51, "linking": [ [51, 52] ] }, { "transcription": "C3F", "label": "answer", "points": [ [730, 1040], [798, 1040], [798, 1077], [730, 1077] ], "id": 54, "linking": [ [53, 54] ] }, { "transcription": "主产地", "label": "question", "points": [ [174, 1084], [279, 1084], [279, 1132], [174, 1132] ], "id": 29, "linking": [ [29, 30] ] }, { "transcription": "主形态", "label": "question", "points": [ [169, 1147], [274, 1147], [274, 1194], [169, 1194] ], "id": 31, "linking": [ [31, 32] ] }, { "transcription": "生产线", "label": "question", "points": [ [590, 1157], [695, 1157], [695, 1196], [590, 1196] ], "id": 55, "linking": [ [55, 56] ] }, { "transcription": "批次", "label": "question", "points": [ [162, 1204], [267, 1204], [267, 1254], [162, 1254] ], "id": 33, "linking": [ [33, 34] ] }, { "transcription": "215.90KG", "label": "answer", "points": [ [285, 1264], [431, 1264], [431, 1314], [285, 1314] ], "id": 36, "linking": [ [35, 36] ] }, { "transcription": "528", "label": "answer", "points": [ [718, 1216], [780, 1216], [780, 1257], [718, 1257] ], "id": 58, "linking": [ [57, 58] ] }, { "transcription": "2020-11-17", "label": "answer", "points": [ [311, 1330], [493, 1330], [493, 1379], [311, 1379] ], "id": 38, "linking": [ [37, 38] ] }, { "transcription": "烤烟", "label": "answer", "points": [ [230, 1449], [313, 1449], [313, 1494], [230, 1494] ], "id": 40, "linking": [ [39, 40] ] }, { "transcription": "品种", "label": "question", "points": [ [121, 1506], [197, 1506], [197, 1552], [121, 1552] ], "id": 41, "linking": [ [41, 42] ] }, { "transcription": "等级", "label": "question", "points": [ [118, 1558], [192, 1558], [192, 1606], [118, 1606] ], "id": 43, "linking": [ [43, 44] ] }, { "transcription": "产地", "label": "question", "points": [ [110, 1612], [183, 1612], [183, 1658], [110, 1658] ], "id": 45, "linking": [ [45, 46] ] }, { "transcription": "形态", "label": "question", "points": [ [100, 1673], [177, 1673], [177, 1721], [100, 1721] ], "id": 47, "linking": [ [47, 48] ] }, { "transcription": "年份", "label": "question", "points": [ [94, 1732], [172, 1732], [172, 1784], [94, 1784] ], "id": 49, "linking": [ [49, 50] ] }]

使用PPOCRLabel kie 是如何标注 linking 的？ @gg22mm @andyjpaddle

**Comment by andyjpaddle** [comment]
暂不支持标注linking关系

**Comment by gavinfaimdata** [comment]
It's a memory error.. watch your RAM and disk usage
