### ISSUE TITLE
当我训练ppstructure的时候，报ValueError: Target 0 is out of lower bound.的错误

### ISSUE THREAD

**Issue by Morningstar232488** [PaddlePaddle/PaddleOCR#8458]
- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：2.3.2  
- 运行指令/Command Code：python tools/train.py -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：

在训练的时候，突然报这个错误，数据集用的pubtabnet，不知道为什么
<img width="1049" alt="截屏2022-11-27 16 44 46" src="https://user-images.githubusercontent.com/75652789/204126463-ef719875-cf40-4dfc-811b-1fd2ef666653.png">
<img width="934" alt="截屏2022-11-27 16 45 01" src="https://user-images.githubusercontent.com/75652789/204126485-18690e45-d67c-4108-91bf-50f14bcb706d.png">

**Comment by jingsongliujing** [comment]
建议看看报错的标签图片，估计是标签有点问题

**Comment by andyjpaddle** [comment]
> 建议看看报错的标签图片，估计是标签有点问题

是的，另外推荐使用paddle 2.3.2版本

**Comment by Morningstar232488** [comment]
> > 建议看看报错的标签图片，估计是标签有点问题
> 
> 是的，另外推荐使用paddle 2.3.2版本

感谢，记错了，就是2.3.2

**Comment by Morningstar232488** [comment]
> 

好的，我去检查一下
