### ISSUE TITLE
PaddleOCR kie模式训练模型支持转为onnx吗？如何移动端部署？

### ISSUE THREAD

**Issue by xiaocode337317439** [PaddlePaddle/PaddleOCR#8459]
PaddleOCR kie模式训练模型支持转为onnx吗？如何移动端部署？

**Comment by jingsongliujing** [comment]
移动端部署可以参考这个：https://github.com/PaddlePaddle/Paddle-Lite
或者参考这个：https://github.com/PaddlePaddle/FastDeploy

**Comment by xiaocode337317439** [comment]
> 移动端部署可以参考这个：https://github.com/PaddlePaddle/Paddle-Lite 或者参考这个：https://github.com/PaddlePaddle/FastDeploy

PPOCRLabel 支持RE关联吗？我标注生成的都是txt，但是看文档KIE标注 会生成json，还包含 linking 连接QA，这个是有什么配置开启吗？

**Comment by jingsongliujing** [comment]
你说的是半自动化标注吗？pplabel目前好像不支持RE的自动化标注，只支持通用OCR的自动标注
