### ISSUE TITLE
请问如果我只需要识别出超过图片一定比例的文字， 应该修改模型的那些参数呢

### ISSUE THREAD

**Issue by MHX1203** [PaddlePaddle/PaddleOCR#846]
比如说， 我只需要识别高度超过图片高度的1/20的文字， 我应该如何修改模型参数呢。另外，这样是不是会显著的提高识别模型在CPU上的速度呢。

**Comment by ausk** [comment]
猜： DB 检测出box后，增加按 box 尺寸筛选操作；然后再使用 CRNN 识别。

**Comment by MHX1203** [comment]
好的， 非常感谢

**Comment by LDOUBLEV** [comment]
> 比如说， 我只需要识别高度超过图片高度的1/20的文字， 我应该如何修改模型参数呢。另外，这样是不是会显著的提高识别模型在CPU上的速度呢。

如果按照这种条件过滤后能减少很多框，可以加快识别速度
