### ISSUE TITLE
识别pdf文件时，引用的pymupdf的 property name变更导致报错

### ISSUE THREAD

**Issue by alococonut** [PaddlePaddle/PaddleOCR#8460]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS
- 版本号/Version：Paddle：2.3.2  PaddleOCR:2.6.1.1 问题相关组件/Related : paddleocr/ppocr/utils/utility.py"
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
File "/lib/python3.9/site-packages/paddleocr/ppocr/utils/utility.py", line 99, in check_and_read
    pm = page.getPixmap(matrix=mat, alpha=False)
AttributeError: 'Page' object has no attribute 'getPixmap'

通过更改源文件中的getPixmap为get_pixmap 以及pageCount为page_count,报错解决

**Comment by jingsongliujing** [comment]
paddle版本用的哪个版本？
2.3还是2.4？建议还是用2.3

**Comment by alococonut** [comment]
paddle用的2.3  看了下是引用的pymupdf的一些property name在1.20.1版本时进行了更改，通过更改源码中的属性名：getPixmap为get_pixmap 以及pageCount为page_count,目前解决了报错。

**Comment by gmaimmortal** [comment]
> paddle用的2.3 看了下是引用的pymupdf的一些property name在1.20.1版本时进行了更改，通过更改源码中的属性名：getPixmap为get_pixmap 以及pageCount为page_count,目前解决了报错。

优秀，按您所说解决了该问题
