### ISSUE TITLE
关键信息抽取(ser)训练模型或者推理模型支持转onnx吗

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8461]
转onnx后推理报错
![image](https://user-images.githubusercontent.com/67177370/204209691-2a953136-d5e0-4d7d-a30b-4508cef15503.png)

**Comment by xiaocode337317439** [comment]
> 转onnx后推理报错 ![image](https://user-images.githubusercontent.com/67177370/204209691-2a953136-d5e0-4d7d-a30b-4508cef15503.png)

我这边也有这种需求，请问下 你用PPOCRLabel 是如何标注RE和训练的？望老哥分享

**Comment by LJY6356** [comment]
写一个后处理脚本





------------------ 原始邮件 ------------------
发件人: xiaocode337317439 ***@***.***&gt;
发送时间: 2022年11月28日 14:59
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: LJY6356 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 关键信息抽取(ser)训练模型或者推理模型支持转onnx吗 (Issue #8461)





  
转onnx后推理报错 
  
我这边也有这种需求，请问下 你用PPOCRLabel 是如何标注RE和训练的？望老哥分享

**Comment by tink2123** [comment]
暂时不支持kie转换onnx模型
