### ISSUE TITLE
nvidia NX上部署paddleOCR的c++demo  运行是推理速度变慢 很慢

### ISSUE THREAD

**Issue by ZX183** [PaddlePaddle/PaddleOCR#8467]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：NVIDIA NX ubuntu1.04 jetpack 4.4
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
![图片](https://user-images.githubusercontent.com/53074550/204271640-885b36a4-1eda-4255-8518-17ec40c266c1.png)

**Comment by LDOUBLEV** [comment]
开TRT第一次预测很慢，连续预测多张图试试
