### ISSUE TITLE
关于量化部署的问题

### ISSUE THREAD

**Issue by backtime92** [PaddlePaddle/PaddleOCR#8468]
请问下，在识别模型crnn，x86下做int8的量化部署，是推荐用paddlelite还是paddleinference？实验了一圈发现paddlelite支持好像没有比较完善？paddleinference没有找到比较好的方案，可否提供一些资料或者建议？

**Comment by tink2123** [comment]
量化部署可参考文档：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/dygraph/dygraph_quant_post_tutorial.md#4%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96
