### ISSUE TITLE
安卓部署核心代码ocr_ppredictor.cpp中内存释放问题

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#8470]
1）请问在创建三个解释器：
       `std::unique_ptr <PPredictor> _det_predictor;
        std::unique_ptr <PPredictor> _rec_ch_predictor;
        std::unique_ptr <PPredictor> _rec_fri_predictor;`
后，怎么对几个解释器进行释放？
2）我用的是
    `  if(_det_predictor!=nullptr){
            _det_predictor.reset();
        }`
。之后对ppredictor::OCR_PPredictor *ocr_predictor = new ppredictor::OCR_PPredictor{conf};
进行delete
但是发现内存释放并不干净。
请问应该怎么做到比较干净彻底的内存管理？

**Comment by WenmuZhou** [comment]
可以调用这个方法https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MainActivity.java#L240，其核心是调用了这个
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/android_demo/app/src/main/cpp/native.cpp#L110

**Comment by GUOhm230** [comment]
> 可以调用这个方法[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MainActivity.java#L240，](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MainActivity.java#L240%EF%BC%8C) 其核心是调用了这个
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/android_demo/app/src/main/cpp/native.cpp#L110
。
感谢您的建议。核心代码是将解释器和模型运行进行分类，全都写在native中。然后在java中初始化model的时候进行判定并释放。
但是目前我是将初始化解释器放在了C++中。而我同样对解释器指针进行了释放。然而多次调用后，模型运行时间突然增加10倍。
请问，在c++内初始化解释器，然后运行model.应该怎么释放呢？

**Comment by WenmuZhou** [comment]
执行上面cpp内对应的代码即可
