### ISSUE TITLE
Different inference results on different machines.

### ISSUE THREAD

**Issue by dukaenea** [PaddlePaddle/PaddleOCR#8471]
I am using the CPU version of paddleocr. When I try to run inference on different machines, I get different results. The most persistent difference is the number "0" recognised as the letter "O" or "o".

There was another issue here related to this one but the only answer given was that different cuda version could give different results. In my case however, I am using the CPU version.

Any kind of help is greatly appreciated!
Thanks in advance.

**Comment by WenmuZhou** [comment]
Can you provide the environment of your two machines?

**Comment by dukaenea** [comment]
The first environment is a Google Vertex AI notebook with the following specs:
* Debian 4.19.260-1
* PaddleOCR 2.6.0.1
* Python 3.8.6

The second is a docker container with the following specs:
* Base Image python:3.8.6-slim
* PaddleOCR 2.6.0.1

As for the command, I am using the ```pip```  package interface and initialise the api as follows:
```
paddle = PaddleOCR(
            use_angle_cls=False
            lang='en',
            enable_mkldnn=True,
            rec_batch_num=16,
            show_log=False,
            rec_algorithm="SVTR_LCNet"
            )
```
Then I call ```paddle.ocr()``` for detection and recognition. The code running on both environments is exactly the same.

**Comment by tink2123** [comment]
Confirm whether the inference model version automatically downloaded by paddleocr is consistent on different machines? Is the version of paddleocr consistent? Generally speaking, the above problems should not occur.

**Comment by johntoma** [comment]
@dukaenea @tink2123  Did you manage to find a solution? I am having the exact same issue.
