### ISSUE TITLE
Table Recognition - How to get collapsed Cell borders (no gaps between cells)?

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8474]
Hello!

I'm trying to modify the results receive from the Table Recognition so that the detected cells have collapsed borders (currently, there are gaps between the cells, which I don't want).

Here is an example result from using Table Recognition from paddle (blue lines = cell border):

![image](https://user-images.githubusercontent.com/83645945/204416103-ce9e7361-afc3-4317-bdce-da34ea5d59f2.png)
As you can see, there are gaps between each cells. 

What I'm trying to achieve is something like this (blue lines = cell border):
![image](https://user-images.githubusercontent.com/83645945/204418310-f03da428-da50-4b6f-8844-435211ba786a.png)

I would like for the cells to have a `collapsed border` (borders of cells touching).

Does Paddle offer some kind of pre-built functionality that can help me achieve this?
Or is my only option to create my own algorithm that will expand the sizes of cells as needed so that the borders of cells are touching.

Thanks!

**Comment by WenmuZhou** [comment]
There is currently no ready-made method

**Comment by johntoma** [comment]
> There is currently no ready-made method

Is there any plan to do this in an upcoming release?

The reason I need to do this is because sometimes the cell bbox coordinates is slightly smaller than the detected lines within that cell.
