### ISSUE TITLE
Table Recognition - How to get column/row index of cells?

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8476]
Is there a way to return the `column`/`row` index of each `cell`, as well as `column-span` and `row-span` in the results?

In case you're interested in what my current process is like, I use PPStructure Layout Analysis to detect tables (and other areas such as title or text) within pdf document pages.

``` 
merge_no_span_structure = True if table_model == Model.TABLE_CH_SLANET else False

table_engine = PPStructure(
    show_log=True,
    lang="en",
    layout_model_dir=layout_model[0],
    layout_dict_path=layout_model[1],
    table_model_dir=table_model[0],
    table_char_dict_path=table_model[1],
    structure_version="PP-Structurev2",
    merge_no_span_structure=merge_no_span_structure,
    ocr=True,)

...

 # I call with these params.
 result = table_engine(
        img,
        return_ocr_result_in_table=True,
    )
```

**Comment by WenmuZhou** [comment]
Not yet supported

**Comment by johntoma** [comment]
> Not yet supported

Will this be supported in the next release or some time in the future? If so, any estimate on when this feature might be released?

Alternatively, maybe I can create some custom functionality myself for now using the html and and cell bbox list. Do you have any tips for me on doing this? 

Also, are the cell bboxes sorted in the same way that they appear within the table html, or are they sorted randomly? If they are sorted in order, then I can probably map each bbox based on its index to its corresponding cell within the html, and get the column/row index and col/rowspan that way.

**Comment by johntoma** [comment]
This issue can be closed
