### ISSUE TITLE
PPStructure Layout Analysis Text Recognition - Get bbox of each word

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8477]
Hello!

I'm using PPStructure Layout Analysis to detect a number of different areas in pages (table, title, text, etc).
For detected areas which contain text inside, currently, results are returning lines of text only, which is good.
But for each line of text inside the detected area, I would also like to get the bbox of each word within that line, as well as the word itself.

So maybe in some kind of format similar to this?:

```
"text": "Name of entity:",
"confidence": 0.9832921624183655,
"text_region": [...],
"words": [
  {
    "word": "Name",
    "bbox" : [...]
  },
  {
    "word": "of",
    "bbox" : [...]
  },
  ...
]
```

Is there currently any existing functionality in Paddle to achieve something similar to this in an easy way? 

Here is an example of the results I'm getting at the moment.
![image](https://user-images.githubusercontent.com/83645945/204421521-d52f5439-a87e-491c-8b97-76dd4b0ae6d6.png)

Here is a sample of my code if needed: 
```
merge_no_span_structure = True if table_model == Model.TABLE_CH_SLANET else False

table_engine = PPStructure(
    show_log=True,
    lang="en",
    layout_model_dir=layout_model[0],
    layout_dict_path=layout_model[1],
    table_model_dir=table_model[0],
    table_char_dict_path=table_model[1],
    structure_version="PP-Structurev2",
    merge_no_span_structure=merge_no_span_structure,
    ocr=True,)

...

 # I call with these params.
 result = table_engine(
        img,
        return_ocr_result_in_table=True,
    )
```

Thanks!

**Comment by WenmuZhou** [comment]
There is currently no ready-made method, you can write a small function to extract

**Comment by johntoma** [comment]
> There is currently no ready-made method, you can write a small function to extract

Ok, thanks.

Will this functionality potentially exist in the future in an upcoming release?
