### ISSUE TITLE
ABINet有通用中英文训练模型和预训练模型吗？

### ISSUE THREAD

**Issue by Armin199608** [PaddlePaddle/PaddleOCR#8478]
paddle已经实现了ABINet，相关模型都是英文的，我想了解一下有中英文通用的模型吗？有对应的预训练模型吗？
或者已经提供的abinet_vl_pretrained.pdparams能直接训练中文吗？

**Comment by WenmuZhou** [comment]
目前没有，可以基于英文的进行finetune

**Comment by wuyuesong** [comment]
中文数据集能在英文预训练模型上finetune吗

**Comment by wuyuesong** [comment]
> 中文数据集能在英文预训练模型上finetune吗



> 目前没有，可以基于英文的进行finetune

中文数据集能在英文预训练模型上finetune吗

**Comment by wuyuesong** [comment]
> 目前没有，可以基于英文的进行finetune

中文数据集能在英文预训练模型上finetune吗
