### ISSUE TITLE
Layout Analysis 

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8479]
## Explanation of the problem
When initializing PPStructure object with these params
```
lang="en",
layout_dict_path=layout_model[1],
```

I get "list index out of range error".

But when I remove these two fields, I get no error and everything works fine.

## 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`Ubuntu 20.04.5`
- 版本号/Version：
  - Paddle: `1.02`  
  - PaddleOCR：`2.6.1.0`  
  - PaddlePaddle-gpu: `2.3.1.post116`
  - 完整报错/Complete Error Message："prediction error: `list index out of range`"
- 运行指令/Command Code：

### I set up the table engine like this: 
```
table_engine = PPStructure(
        show_log=True,
        lang="en",
        layout_model_dir=layout_model[0],
        layout_dict_path=layout_model[1],
        table_model_dir=table_model[0],
        table_char_dict_path=table_model[1],
        structure_version="PP-Structurev2",
        merge_no_span_structure=merge_no_span_structure,
        ocr=True,
    )
    # return table_engine
```

where 
### layout_model_dir
`layout_model[0]` = `'/home/[user]/[my-repo]/models/Layout Detection/picodet_lcnet_x1_0_fgd_layout_infer'`

### layout_dict_path
`layout_model[1]` = `'/home/[user]/paddle/PaddleOCR/ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt'`

### Dict File Content
```text
title
list
table
figure
```

### I call the table engine like this

```
try:
    result = table_engine(
        img,
        return_ocr_result_in_table=True,
    )
except Exception as e:
    logger.info("prediction error: %s", str(e))
    raise Exception(f"prediction error: {str(e)}")
```

When I remove the "lang" and "layout_dict_path" fields, I get no error and everything works fine. I must remove *both* of these fields for it to work. It does not work if I remove one and keep the other.

Any reason why this is happening, and what I can do to fix? I assume it's something related to the dict file.

Note: I have other Layout Models I can choose from, and I initialize PPStructure in the same way, but they work completely fine. I get no errors at all.

**Comment by johntoma** [comment]
> text title list table figure
> 
> publaynet dataset has 5 types of areas, you can try again

sorry, I actually just pasted it wrong.

My dict file already looks the same as yours.

**Comment by an1018** [comment]
I'vd tested the code, it's ok for me. Maybe you can try set `merge_no_span_structure=False`

**Comment by johntoma** [comment]
@an1018 hello, sorry for the late reply.

I ttried testing with `merge_no_span_structure` as `True` and also as `False`, but the issue is still present.

**Comment by an1018** [comment]
Could you run the code on other devices?

**Comment by johntoma** [comment]
> Could you run the code on other devices?
Unfortunately I currently don't possess the means to test it on other devices, so I'm not sure.
