### ISSUE TITLE
文本检测识别必须先检测后识别吗？可以合并吗？

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8480]
想问下PaddleOCR文本检测识别流程
1.检测和识别可以同时进行吗？还是必须先训练检测模型，经过裁剪得到文本字符后再训练识别模型？可以直接一个模型吗？因为看到检测模型标注位置同时也得标注字符。
2.如果必须先检测后识别，检测模型的数据标注的字符可以随便标吗？

update：了解到端到端算法可以同时进行，端到端算法可以识别场景中的颠倒180度文本或垂直90度 270度的文本吗？

**Comment by WenmuZhou** [comment]
端到端的算法目前没办法对90,270的进行识别

**Comment by Currf** [comment]
> 
好的，谢谢。如果只是想检测文本的位置，标注的时候文本是随便写还是还得标注文本的实际内容呢？检测模型没有识别功能内容应该就可以随便标了吧？

**Comment by Currf** [comment]
> 端到端的算法目前没办法对90,270的进行识别

好的，谢谢。如果只是想检测文本的位置，标注的时候文本是随便写还是还得标注文本的实际内容呢？检测模型没有识别功能内容应该就可以随便标了吧？

**Comment by LDOUBLEV** [comment]
随便标，不要标记为“###”

**Comment by Currf** [comment]
> 随便标，不要标记为“###”

谢谢 好像确实是的 标记为###训练精度都是0 换了其他就好了
