### ISSUE TITLE
paddle中有文本图像质量评估的模型或者算法嘛

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8481]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
暂时没有哈
