### ISSUE TITLE
kie关键信息抽取，采用推理模型，如何让替换自己的检测模型与识别模型

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8483]
cd ppstructure
python3 kie/predict_kie_token_ser.py \
  --kie_algorithm=LayoutXLM \
  --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../train_data/XFUND/class_list_xfun.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx"

**Comment by WenmuZhou** [comment]
可以通过--det_model_dir和--rec_model_dir来替换检测和识别模型

**Comment by gg22mm** [comment]
> 可以通过--det_model_dir和--rec_model_dir来替换检测和识别模型

python tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy Global.infer_img=./train_data/XFUND/zh_train/image/12.jpg    不应该是这样吗?

**Comment by cookiesyip** [comment]
> > 可以通过--det_model_dir和--rec_model_dir来替换检测和识别模型
> 
> python tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy Global.infer_img=./train_data/XFUND/zh_train/image/12.jpg 不应该是这样吗?

我覺得你的方法是沒有錯的，在ser_vi_layoutxlm_xfund_zh.yml改相應的path 就行

**Comment by Johann356** [comment]
paddleocr.py中484行左右的几个maybedownload注释掉就好了
