### ISSUE TITLE
ocr_dataset is empty

### ISSUE THREAD

**Issue by amroghoneim** [PaddlePaddle/PaddleOCR#8486]
Where can I find the example ocr_dataset , as the url provided is not working?

**Comment by littletomatodonkey** [comment]
Which doc link and which url?

**Comment by amroghoneim** [comment]
This doc: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/recognition_en.md

This url: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/dataset/ocr_datasets.md
