### ISSUE TITLE
TableMaster PPStructure Layout Analysis

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8487]
Hello!

In `predict_structure.py` and `predict_table.py`, there is an option to do `table_algorithm="TableMaster"`

Can the TableMaster algorithm be used with PPStructure Layout Analysis? I can use the TableMaster model itself, but not sure if theres an option to specify the algorithm as TableMaster.

**Comment by WenmuZhou** [comment]
use same option as predict_table.py
