### ISSUE TITLE
paddleocr在jetson上使用tensorrt部署加载模型超过十分钟怎么提高加载模型速度

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#8488]
使用paddleocr进行文本检测和识别，当打开use_tensorrt时候，加载推理模型非常慢，一般都要十分钟以上，这是咋回事是推理模型在内存进行trt序列化和反序列化吗，怎么提高tensorrt加载模型效率？

**Comment by littletomatodonkey** [comment]
这块目前没有很好的办法规避，你可以打开trt engine build过程中的use_static=True，他会生成trt的序列子图，第一次加载很慢（需要生成子图），后面再加载就都会很快

**Comment by futureflsl** [comment]
> use_static=True

use_static=True这个可以具体说说吗，我在paddleocr没搜到这个关键词
