### ISSUE TITLE
使用pp_structure预测的时候出现显存不足问题 

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#8489]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 
- 问题相关组件/Related components：PP-Structure
- 运行指令/Command Code：paddleocr --image_dir=ppstructure/docs/table/table.jpg --type=structure --image_orientation=true
- 完整报错/Complete Error Message：

提醒我申请了8G的显存 但是我的电脑没有那么大显存，难道小显卡就不能够进行预测吗?求解决，感激不尽！
![image](https://user-images.githubusercontent.com/94897119/204686968-2a8fd1d6-ee28-4174-b271-24f185b735d5.png)

**Comment by phb-shiyige-fw** [comment]
@littletomatodonkey 请您看到后 帮我解决一下 感激！

**Comment by jingsongliujing** [comment]
如果是本地电脑，就改成cpu推理吧

**Comment by WenmuZhou** [comment]
这个不是显存不足哦，更新一下paddleocr
