### ISSUE TITLE
当文本相对密集时，上下行文本排序错乱

### ISSUE THREAD

**Issue by Yulv-git** [PaddlePaddle/PaddleOCR#849]
当文本相对密集时，检测出的文本排序有时会乱。如上下行中的部分文本顺序错乱。 要怎么解决该问题比较好？

**Comment by littletomatodonkey** [comment]
目前是根据检测框的顶点来进行排序的，如果文本没有互相覆盖的情况，那么可以试下基于重心进行排序的方法

https://github.com/PaddlePaddle/PaddleOCR/blob/e4b09948d17a309e8659f4fe3326200a22d5b607/tools/infer/predict_system.py#L111

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
