### ISSUE TITLE
想问一下，整个检测和识别的过程除了识别过程可以有batch外，检测过程不可以用batch吗？必须得一张张图片进行推理吗？

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleOCR#8490]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by jingsongliujing** [comment]
这个推理部署的话多开几个线程就好了，用多线程

**Comment by shumeirao** [comment]
> 处理

如果我预测的图片大小是一样的呢？是否可行，需要修改哪边的参数，我这边可以测试一下效果

**Comment by shumeirao** [comment]
> 检测用batch预测，效果可能会比较差，因为检测的数据处理逻辑与识别不同，很难做到不同的输入数据处理后shape相同，导致无法组batch

如果我预测的图片大小是一样的呢？是否可行，需要修改哪边的参数，我这边可以测试一下效果

**Comment by shumeirao** [comment]
> 这个推理部署的话多开几个线程就好了，用多线程

主要是想在单个CPU下跑更多的图片，启动多个线程是不是会占用更多的cpu
