### ISSUE TITLE
关于文字检测模型预训练的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#8492]
自己训练过了一个特定场景的文字检测的模型，效果也还不错，现在想继续优化该模型

1. 原先数据+新增数据，使用官方提供的预训练模型，finetune进行训练
2. 只使用新增数据，使用自己上一个训练的模型作为预训练模型进行finetune
3. 原先数据+新增数据，使用自己上一个训练的模型作为预训练模型进行finetune

请问：上面三种方法哪个对检测模型优化效果会更好些呢（由于数据量较大，没有时间逐一训练尝试比对）

**Comment by littletomatodonkey** [comment]
建议用1
