### ISSUE TITLE
KIE任务如何处理多行question和answer

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleOCR#8493]
在使用过程中发现LayoutXML的OCR部分是**以行为单位**进行文本检测和识别的，但是很多表格数据中每个cell往往有多行文本，就会被拆分成多个部分，比如下图的`支付金额（人民币元，含税）`会被拆为`支付金额（人民币*`和`元，含税）`两个部分，在做标注的时候是否需要把answer与question的每个部分都进行link，比如`支付金额（人民币*`->`294159`，`元，含税）`->`294159`，同理如果question和answer都存在多行，是不是需要把每question的每行和answer的每行都进行关联？

想达到的效果：能够保证一个cell内的文本为一个整体，然后构建cell与cell之间的关联，例如得到`支付金额（人民币元，含税）`->`294159`这样的结果，请问是不是只能依靠自己进行后处理，或者有没有什么比较好的解决办法？

例如：

<img width="584" alt="image" src="https://user-images.githubusercontent.com/34825635/204726872-4313dc71-043a-49b7-982e-869f4e2199b9.png">

**Comment by littletomatodonkey** [comment]
你好，这块暂时没考虑到，可以使用PaddleNLP的UIE试下（不考虑位置信息）
