### ISSUE TITLE
发票场景内容信息串行或内容覆盖

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#8494]
一些发票场景中，存在机打和印刷内容信息串行或内容覆盖的情况，影响文字识别。

请问这种情况有什么好的解决方法或者参考资料吗？

目前只查到有用图层分离技术的，但是也没给具体的可参考资料
https://www.sohu.com/a/421453436_100098532

**Comment by littletomatodonkey** [comment]
你好，这块需要重新基于你的数据训练文本检测与识别模型

**Comment by ziyaxuanyi** [comment]
不是吧，这种情况不是简单的重新训练文本检测和识别模型能解决的吧。
文字是重叠的，即使能够检测到文字区域，识别模型也无法准确识别出印刷字和打印字
![impicture_20221130_210827](https://user-images.githubusercontent.com/43610203/204804514-43a3b6ce-f9e4-49f3-a172-e5763797b411.png)

**Comment by Randy-1009** [comment]
> 不是吧，这种情况不是简单的重新训练文本检测和识别模型能解决的吧。 文字是重叠的，即使能够检测到文字区域，识别模型也无法准确识别出印刷字和打印字 ![impicture_20221130_210827](https://user-images.githubusercontent.com/43610203/204804514-43a3b6ce-f9e4-49f3-a172-e5763797b411.png)

您好~ 想问一下您后续有调研到什么相关的技术嘛？我最近做票据识别也存在这种问题，如果能够分享，感激不尽~

**Comment by zhangqiqi1228** [comment]
> > 不是吧，这种情况不是简单的重新训练文本检测和识别模型能解决的吧。 文字是重叠的，即使能够检测到文字区域，识别模型也无法准确识别出印刷字和打印字 ![impicture_20221130_210827](https://user-images.githubusercontent.com/43610203/204804514-43a3b6ce-f9e4-49f3-a172-e5763797b411.png)
> 
> 您好~ 想问一下您后续有调研到什么相关的技术嘛？我最近做票据识别也存在这种问题，如果能够分享，感激不尽~

@Randy-1009 这种情况单靠识别模型应该做不了吧？得先预处理通过颜色通道将两层字分开，再单独用ocr模型识别。
