### ISSUE TITLE
使用链接下载的预训练模型没有后缀

### ISSUE THREAD

**Issue by WethatVivy** [PaddlePaddle/PaddleOCR#8495]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/ser_vi_layoutxlm_xfund_pretrained.tar
https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/re_vi_layoutxlm_xfund_pretrained.tar
因为是wIndows直接复制了网站链接然后用浏览器下载，下载解压后的文件是一个名为ser_vi_layoutxlm_xfund_pretrained和re_vi_layoutxlm_xfund_pretrained的东西，没有后缀。

**Comment by littletomatodonkey** [comment]
这个是paddlenlp的模型文件格式（本身layoutxlm系列模型是多模态模型），里面有个`best_accuracy`文件夹，就是我们需要的，你参考kie的文档操作就行

**Comment by WethatVivy** [comment]
> 这个是paddlenlp的模型文件格式（本身layoutxlm系列模型是多模态模型），里面有个`best_accuracy`文件夹，就是我们需要的，你参考kie的文档操作就行

可能是我没讲清楚，我解压后出来的东西是这样的
![图片](https://user-images.githubusercontent.com/89375600/206111451-1cc3e3b1-5973-4cdf-8370-ebde818e8cf2.png)
我不知道用什么打开方式能打开它，也不知道里面有没有文件夹......我直接设置这个东西路径+best_accuracy为模型路径，也不会加载成功，报错信息如下：
![图片](https://user-images.githubusercontent.com/89375600/206113535-3601ac27-c46d-4802-85cf-5243e8ba9af1.png)

然后我尝试跟着文档操作，训练模型再评估的时候，文档中说会自动下载模型，但是根据报错信息下载链接也有问题。
![图片](https://user-images.githubusercontent.com/89375600/206111791-c0b1ca6b-7011-42f3-8951-467cdf39c05e.png)

**Comment by WethatVivy** [comment]
又逛了一下issues，#8034和#8455都有一样的问题，还没看到有回复解决方法。
