### ISSUE TITLE
Windows 2019 : DLL load failed while importing libpaddle: The specified module could not be found

### ISSUE THREAD

**Issue by helloblackmarch** [PaddlePaddle/PaddleOCR#8502]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows Server 2019 Datacenter
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6.1.1
- 运行指令/Command Code：from paddleocr import PaddleOCR
- 完整报错/Complete Error Message：DLL load failed while importing libpaddle: The specified module could not be found
![Screenshot](https://user-images.githubusercontent.com/58966400/204943981-6432969d-4dac-4f4a-a7c0-3aa0c9684aa0.PNG)

**Comment by helloblackmarch** [comment]
NOTE : The same set-up is working without any issue in my local machine running Windows 11 OS

**Comment by an1018** [comment]
1、maske sure your   processor architecture is x86_64(or called x64、Intel 64、AMD64).
2、verify installation of paddle
After the installation is complete, you can use python to enter the Python interpreter and then use `import paddle` and `paddle.utils.run_check()` ， If PaddlePaddle is installed successfully! appears, to verify that the installation was successful.

for more information: https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/windows-pip_en.html

**Comment by helloblackmarch** [comment]
@an1018 Thanks for your reply. My processor architecture is x86_64 (AMD64). I am unable to run paddle.utils.run_check() as I was not even able to import paddle after its installation. I also tried the steps provided in the link. I am still getting same error

**Comment by helloblackmarch** [comment]
I tried installing Anaconda and installed the complete thing from the Anaconda prompt. It worked for me after the same. Below are the steps I followed :

01. Install Anaconda/Miniconda (https://docs.conda.io/en/latest/miniconda.html)
NOTE : Python 3.9.12 comes with the Miniconda

02. Open Anaconda Command Prompt and run the below commands (For CPU)
     python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
     pip install paddleocr
     python 
     >>import paddleocr (Import paddle ocr is working after this)

NOTE : I tried installing python 3.9.12 (same version) separately but that one resulted in the above error. For some reason when I used the python from conda, it worked for me

**Comment by deeptvyas25** [comment]
Try installing VC++ redistributable 2015 - 2022, it worked for me.

**Comment by SantiiRepair** [comment]
> VC++ redistributable 2015

Worked for me, thanks!

**Comment by liudonghua123** [comment]
It's the same even I installed the latest VC_redist.x64-2015-2022.exe.

<img width="1703" height="769" alt="Image" src="https://github.com/user-attachments/assets/7779f0cc-049f-4778-aa5d-d31162f41ba7" />

But on another computer, the import is no error. The vc runtime is the same.

<img width="1007" height="226" alt="Image" src="https://github.com/user-attachments/assets/ff8a6826-1dd5-489b-a9f8-543de4201d11" />
