### ISSUE TITLE
cmd里运行paddleOCR正常，但是运行到pycharm里会出错

### ISSUE THREAD

**Issue by TS10armourer** [PaddlePaddle/PaddleOCR#8505]
我是按照这个文档来的
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#22
在这一步可以正常识别了
![image](https://user-images.githubusercontent.com/100982130/204976598-7f2e5816-bb9e-447e-a480-09e4d5d0b3f9.png)

![1948a852764207c3fd2826189f166c6](https://user-images.githubusercontent.com/100982130/204976469-6bcf8dc5-0b23-4b1d-b352-43545fac49f5.png)

但是我接下来zai在pycharm里面运行这段代码
![image](https://user-images.githubusercontent.com/100982130/204976675-d9c0b928-9e81-43b2-bbd4-e219e6fcf1b9.png)
pycharm如图显示
![image](https://user-images.githubusercontent.com/100982130/204976717-27a51f8a-3b43-4557-aebc-1a494d00bc69.png)
请问是什么问题，要怎么解决呢？

**Comment by an1018** [comment]
跟换一下python文件名称，你这里的paddleocr.py和import paddleocr冲突了

**Comment by TS10armourer** [comment]
![image](https://user-images.githubusercontent.com/100982130/204986168-5ee5d68a-3809-4146-8850-8b63dc2fb88a.png)
可以运行了，但是这里运行了很久很久没有出结果是什么问题呢？cmd运行很快的

**Comment by TS10armourer** [comment]
![image](https://user-images.githubusercontent.com/100982130/204986168-5ee5d68a-3809-4146-8850-8b63dc2fb88a.png)
可以运行了，但是这里运行了很久很久没有出结果是什么问题呢？cmd运行很快的

**Comment by an1018** [comment]
我这边测试没问题，可以在代码里debug看卡在哪里

**Comment by TS10armourer** [comment]
![image](https://user-images.githubusercontent.com/100982130/204997738-cdb17e62-fd33-4d96-9b09-0d7059237c66.png)
debug在这句出了问题，卡在这里了。

**Comment by TS10armourer** [comment]
一跳进这一句就卡住了

**Comment by an1018** [comment]
那你把这个代码在控制台运行试试
![image](https://user-images.githubusercontent.com/19808900/205021424-fc04d16e-386b-4999-911d-c8bcaa00ce15.png)

**Comment by TS10armourer** [comment]
解决了，我必须得把GPU设置为False才能跑起来，应该是PaddleOCR模型不兼容4090的缘故？希望可以加以优化

**Comment by an1018** [comment]
可以执行
```
import paddle
paddle.utils.run_check()
```
看下是否有GPU
![image](https://user-images.githubusercontent.com/19808900/205026653-35206dfc-2cb2-47c0-baf2-ed787aaf7b72.png)

或着查看是不是安装的paddlepaddle-gpu

**Comment by TS10armourer** [comment]
![image](https://user-images.githubusercontent.com/100982130/205027057-d043da9b-84e3-4f27-ba25-0a1b13eb2281.png)
paddlepaddle是gpu版的，是paddleocr也要是gpu版的吗？
![image](https://user-images.githubusercontent.com/100982130/205027342-51afa5c3-fa3c-483f-957f-fcb9848efb56.png)
这个是运行结果

**Comment by an1018** [comment]
ocr不需要，check结果是什么

**Comment by TS10armourer** [comment]
![image](https://user-images.githubusercontent.com/100982130/205028143-f602622d-11e4-4c1f-819a-ecaba94ae6fc.png)

**Comment by TS10armourer** [comment]
这个结果很久才跳出来的，这个是不是也有点不兼容呀
