### ISSUE TITLE
如何修改PaddleOCR预训练模型默认下载地址？

### ISSUE THREAD

**Issue by 503718696** [PaddlePaddle/PaddleOCR#8507]
如何修改PaddleOCR预训练模型默认下载地址？

**Comment by an1018** [comment]
检测是这里，识别配置文件相同https://github.com/PaddlePaddle/PaddleOCR/blob/0c3c48147ee95e8c55f5e00ec1c1cb23c4b25045/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml#L13

**Comment by 503718696** [comment]
不可以直接配置环境变量嘛？

**Comment by an1018** [comment]
预测还是训练？

**Comment by jingsongliujing** [comment]
修改下载地址和代码里的55行就行了：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

**Comment by an1018** [comment]
如果使用paddleocr安装包预测，可以设置det_model_dir指定模型路径，[详细代码参考](https://github.com/PaddlePaddle/PaddleOCR/blob/0e1148312be91f7fd7ffcb3f57c4c63fcdd5b67f/paddleocr.py#L465)
