### ISSUE TITLE
什么时候可以正价泰国语

### ISSUE THREAD

**Issue by ysuwei** [PaddlePaddle/PaddleOCR#8508]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
目前感觉实现有哪些困难？你可以尝试构建字典、数据集，使用PPOCR-v3训练
