### ISSUE TITLE
关于SVTR中neck模块的问题

### ISSUE THREAD

**Issue by ddddddreamcastle** [PaddlePaddle/PaddleOCR#8509]
在学习SVTR算法，学习论文中给出的PaddleOCR的代码链接。 看到svtr提供的各种yml文件，neck部分都使用的reshape模块，但是我发现necks/rnn.py文件中还存在一个EncoderWithSVTR模块。为什么不用这个呢？ 

backbone中的rec_svtrnet.py，看代码应该已经完成了论文中的Figure2的全部流程，那么EncoderWithSVTR的作用是？

**Comment by an1018** [comment]
PP-OCRv3基于SVTR进行了优化，具体可以参考[这里](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/ppocr_introduction.md#pp-ocrv3)和[PP-OCRv3技术报告](https://arxiv.org/abs/2206.03001v2)
