### ISSUE TITLE
Jetson Nano PaddleOCR, not detecting any text

### ISSUE THREAD

**Issue by Joaquinag** [PaddlePaddle/PaddleOCR#8510]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Jetson Nano
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/infer/predict_det.py  --det_model_dir=/home/aldl/Documents/projects/PaddleOCR-release-2.6/en_PP-OCRv3_det_infer/ --image_dir=/home/aldl/Documents/projects/PaddleOCR-release-2.6/doc/imgs/french_0.jpg --use_gpu=True
- 完整报错/Complete Error Message：
![Screenshot from 2022-12-01 10-50-54](https://user-images.githubusercontent.com/93997174/205021614-64e359d1-7724-4b3d-936a-a1fcfc0611b8.png)

I followed the deploy tutorial on jetson for PaddleOCR, but when i run paddleocr it does not detect any text. 

I have tried to install it several times and i end up with the same error.

I have checked and have every package version required, and tried with different images and languages. 

What could it be?

Thank you in advanced

**Comment by an1018** [comment]
The name of your picture is french_0.jpg, the language is french? If yes, you can download [this model](https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/Multilingual_PP-OCRv3_det_slim_infer.tar) and try again

**Comment by an1018** [comment]
you can remove `--det_db_score_mode`

**Comment by Joaquinag** [comment]
Thank you for answering.

I have alredy tried that and did not work.

I have tried putting different parameters and have the same result.

**Comment by Joaquinag** [comment]
So it turns out it was the paddlepaddle version, wich needs to be 2.3.2 and not 2.4.

Is strange that there were no message errors, but the problem was that.

Find the installation .whl here:
https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html#python
