### ISSUE TITLE
Not recognize apostrophe symbol

### ISSUE THREAD

**Issue by Mann1904** [PaddlePaddle/PaddleOCR#8512]
I have finetuned the SVTR recognition model  on my custom data. but the model was not recognized symbol.

![cn_133_1_2](https://user-images.githubusercontent.com/58176237/205064685-fda0e8dd-f787-4390-99bf-53c0b6138b46.jpg)

finetuned model prediction : Companys GST No

base model prediction : Company's GST No

How can I resolve these issues ?

**Comment by an1018** [comment]
The number of symbol characters is relatively small？You can try increase the frequency of symbol  characters
