### ISSUE TITLE
怎么设置FC层的维度

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#8514]
使用了自定义的dict,发现fc层的维度与词典不对应。请问怎么设置FC层的维度？

**Comment by huangjun12** [comment]
修改一下对应yml文件中模型的fc层参数

**Comment by ronaldpan** [comment]
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: 
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001
请问应该修改哪个参数？

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/ppocr/modeling/heads/rec_ctc_head.py#L38 这里
