### ISSUE TITLE
fine-tune效果很差

### ISSUE THREAD

**Issue by jobsjiang** [PaddlePaddle/PaddleOCR#8515]
主要基于ch_PP-OCRv3_rec_train的预训练模型，训练自定义的数据集，模型识别效果很差，基本的中英文都无法识别了，原因？

**Comment by BeyondYourself** [comment]
1）检查一下训练代码和预训练模型是否匹配
2）检查一下数据字典是否使用正确
3）检查一下自定义数据集是否数量太少或者类别不均衡之类的等

**Comment by jobsjiang** [comment]
> 1）检查一下训练代码和预训练模型是否匹配 2）检查一下数据字典是否使用正确 3）检查一下自定义数据集是否数量太少或者类别不均衡之类的等

1. ch_PP-OCRv3_rec_distillation.yml与ch_PP-OCRv3_rec_train下载的权重进行训练，但有一个问题就是用ch_PP-OCRv3_rec_slim_train权重进行训练的时候提示
ppocr WARNING: The pretrained params xxx not in model的问题
2. 数据字典使用默认的数据字典。
3. 主要是数字识别，目前利用4w多的训练集。
