### ISSUE TITLE
paddleocr使用GPU不能正常运行

### ISSUE THREAD

**Issue by TS10armourer** [PaddlePaddle/PaddleOCR#8517]
使用的GPU：RTX4090微星朝龙
![image](https://user-images.githubusercontent.com/100982130/205222785-6f43ee1f-3b42-48d6-928a-8df1c14d31ff.png)
这个是环境安装的库
运行一下检测
![image](https://user-images.githubusercontent.com/100982130/205222847-273cc3ba-5e0a-4793-87d4-6ce40979ad11.png)
正常检测到了
运行的代码如下（来自https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#22）
![image](https://user-images.githubusercontent.com/100982130/205223167-2b710a4f-0163-48bf-99ef-c583ab57ec22.png)
设置use_gpu=True时，无法正常运行，会卡在这里十几分钟，最后没有输出，同时，使用GPU显示检测不到任何文字
![image](https://user-images.githubusercontent.com/100982130/205222954-14851fc9-e3da-4d2b-b0c6-9b9309f7819d.png)
直接结束了，推出代码如图，4090不存在显存不足的问题，毕竟CPU都能跑
![image](https://user-images.githubusercontent.com/100982130/205223371-893b48c5-da83-4cfb-ab43-ff00d4b9f888.png)
请问是什么问题呢，要如何修改？
还是paddle现阶段不兼容RTX4090？

**Comment by huangjun12** [comment]
问题有点奇怪 换一个paddleocr版本试下呢

**Comment by xialei2821212670** [comment]
这边可以换个版本的numpy试下，1.19.2

**Comment by fudemin1** [comment]
解决了吗，我也遇到这个问题，显卡4090，cpu可正常检测出正确结果，gpu运行结果全是乱的
