### ISSUE TITLE
ppocrv3剪枝做FPGMFilterPruner时报错

### ISSUE THREAD

**Issue by laiqirong** [PaddlePaddle/PaddleOCR#8519]
TypeError: 'NoneType' object is not subscriptable
模型分head和backbone两个部分。
 pruner = FPGMFilterPruner(model,input_shape)运行到这里时候报TypeError: 'NoneType' object is not subscriptable
如果把代码修改为pruner = FPGMFilterPruner(model.backbone,input_shape)就可以运行。但是最终保存的只有backbone部分，没有头部。这个要怎么处理

**Comment by huangjun12** [comment]
build的model可能有问题，可以参考下 https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/test_tipc/supplementary/train.py#L123 这里

**Comment by HAIMSTZL** [comment]
paddleocr 识别模型，multihead模型裁剪问题，你们这部分代码没有完善，无法正常使用，你并没有定位到问题
