### ISSUE TITLE
精选FAQ出现语句不顺或者错别字

### ISSUE THREAD

**Issue by xxdm** [PaddlePaddle/PaddleOCR#852]
![1fc3f664066e1bbd8841a2230dab88a](https://user-images.githubusercontent.com/10796263/94262540-36d69100-ff66-11ea-93a8-62c934e32870.png)
![image](https://user-images.githubusercontent.com/10796263/94262582-48b83400-ff66-11ea-81c5-08377c143cef.png)

**Comment by grasswolfs** [comment]
感谢宝贵意见，已修改
https://github.com/PaddlePaddle/PaddleOCR/commit/e4b09948d17a309e8659f4fe3326200a22d5b607
