### ISSUE TITLE
文本检测模型图像输入尺寸问题

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8521]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

1.请问图像输入尺寸有固定要求吗？虽说输入到模型都会自动resize，但怕随意裁剪会影响到检测精度。
2.如果有要求，请问在yml文件哪里能看呢？是以下这个吗？
- EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true

3.裁剪为相近或者倍数大小的尺寸可以吗？比如640 * 640 可以为628 * 680相近或者是裁剪为32的倍数，比如320 * 320或者1280 * 1280

**Comment by BeyondYourself** [comment]
个人看法：resize还是根据实际训练集的图片以及检测的目标来确定

**Comment by Currf** [comment]
> 个人看法：resize还是根据实际训练集的图片以及检测的目标来确定

请问什么意思呢 没听懂。就是我的图片有大有小 如果没有一个固定的尺寸的话是尽量靠近32的倍数吗？

**Comment by guishilike** [comment]
会随机裁剪，有一个最小比例限制
![image](https://user-images.githubusercontent.com/51023060/205433458-3cea4fc7-de81-4e46-965c-3617d49fda82.png)

**Comment by Currf** [comment]
> 会随机裁剪，有一个最小比例限制 ![image](https://user-images.githubusercontent.com/51023060/205433458-3cea4fc7-de81-4e46-965c-3617d49fda82.png)

是输入如果不是模型规定输入就会随机裁剪到模型指定尺寸吗

**Comment by guishilike** [comment]
不是，EastRandomCropData会resize到指定尺寸，在此基础上还会做裁剪，和你图片无关

**Comment by Currf** [comment]
> 不是，EastRandomCropData会resize到指定尺寸，在此基础上还会做裁剪，和你图片无关

好的谢谢 我想问下裁剪为与模型规定输入大小相近或者32倍数的尺寸可以吗？我的图片有大有小，如果没有一个固定的尺寸的话是尽量靠近32的倍数吗？

**Comment by guishilike** [comment]
输入尺寸是32倍数就行，图片resize后不够会填充的
