### ISSUE TITLE
ppocr下找不到modeling模块

### ISSUE THREAD

**Issue by Assassin-SM** [PaddlePaddle/PaddleOCR#8528]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/Win11：
- 版本号/Version：Paddle-->paddlepaddle-gpu 2.4.0.post116：  PaddleOCR 2.6.1.0： 问题相关组件/无：
- 运行指令/from paddleocr.ppocr.modeling.backbones.det_mobilenet_v3 import MobileNetV3：
- 完整报错/Traceback (most recent call last):
  File "d:\Code store\test examples\test_detail_dec.py", line 1, in <module>
    from paddleocr.ppocr.modeling.backbones.det_mobilenet_v3 import MobileNetV3
ModuleNotFoundError: No module named 'paddleocr.ppocr.modeling'：
在PaddleOCR工程文件中ppocr文件夹下是有modeling文件夹的，但通过setup.py安装后环境里却找不到modeling模块。类似的问题也同样存在于其它模块。

**Comment by WenmuZhou** [comment]
目前whl包只提供和预测相关的功能，训练相关的没有打包进来
