### ISSUE TITLE
Vanilla SVTR vs PPOCR-v3

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8529]
I wanted to know why the training time for the same amount of Data on PPOCRv3 takes more time to converge compared to vanilla SVTR
1. 20 epochs to converge on Vanilla SVTR while 500 epochs on PPOCR-v3 to converge
2. 500 epochs takes x6 the amount of time to complete for PPOCR-v3 compared to training of 500 epochs on vanilla SVTR
3. When running inference vanilla SVTR runs faster on GPU and CPU? so what went wrong with PP-OCRv3 training and inference that SVTR-tiny is faster and more accurate?

**Comment by Topdu** [comment]
1. Vanilla SVTR uses the public English dataset for training, and PPOCR-v3 uses the Chinese dataset for training, with different amounts of data between them.
2. PPOCR-v3 uses data augmentation and distillation strategies, which are more time consuming.
3. PP-OCRv3 runs faster than SVTR on CPU with MKLDNN.
