### ISSUE TITLE
Linux下的pip安装验证不成功 

### ISSUE THREAD

**Issue by rsong0606** [PaddlePaddle/PaddleOCR#8531]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6  
```
<img width="1301" alt="WeChat2c1d9710e59d015cee0c8e7e989c214b" src="https://user-images.githubusercontent.com/58720071/205461063-b5f4dd24-01ae-413d-b4ac-7ec6be844196.png">

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
`paddleocr = "==2.6.1.0"`
`python -m pip install paddlepaddle-gpu==2.4.0.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`
- 运行指令/Command Code：
 `进入 python 解释器，输入import paddle`
- 完整报错/Complete Error Message：
```
  File "/home/*****.local/share/virtualenvs/*****/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

```

https://blog.csdn.net/jaket5219999/article/details/127823120?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EAD_ESQUERY%7Eyljh-1-127823120-blog-121096993.pc_relevant_multi_platform_whitelistv4&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EAD_ESQUERY%7Eyljh-1-127823120-blog-121096993.pc_relevant_multi_platform_whitelistv4&utm_relevant_index=2
这个博客解决了问题 但是cuda又出了问题...

```
 UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
```

```
 nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

```

**Comment by LDOUBLEV** [comment]
paddlepaddle的安装问题可以在这里https://github.com/paddlepaddle/paddle提issue

**Comment by jingsongliujing** [comment]
建议用2.3

**Comment by rsong0606** [comment]
`paddlepaddle-gpu==2.3.2.post116` 这个嘛？
> 建议用2.3

**Comment by jingsongliujing** [comment]
对的，要和你的cuda版本对应
