### ISSUE TITLE
paddleocr后期会出字符型的ocr？

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#8535]
![image](https://user-images.githubusercontent.com/29837553/205481627-c809b02e-097b-4ca4-87a4-23e0594dba2d.png)

**Comment by LDOUBLEV** [comment]
目前不打算支持字符级输出，只支持文本行级别的检测和识别

**Comment by fanqie03** [comment]
字符检测：[https://github.com/fanqie03/char-detection/tree/main](https://github.com/fanqie03/char-detection/tree/main)
