### ISSUE TITLE
PPOCRLabel导出识别结果，发现crop_img的图片变换了方向

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8538]
问题相关组件/Related components：PPOCRLabel
如下图，我在PPOCRLabel中对竖直的数据进行标注，导出识别结果后，图片是横着的，也不是全部图片都有这种情况，有些还是按照我的标注格式进行保存的。但很多图片会有这种情况
![b457f2ff86e7a1b5315b02394ca78b4](https://user-images.githubusercontent.com/80883358/205529821-f6a987ca-4d0a-440d-abbb-dd75855e6651.png)
![60c765fba123f01aef650d43d4e5244](https://user-images.githubusercontent.com/80883358/205529831-e26f7a47-572f-4478-b83b-9bfd309cbe6d.png)
比如下图这种就是正常保存的
![b36d20f1a4e784ded9c5b67f609c924](https://user-images.githubusercontent.com/80883358/205530271-d7da1066-56bd-4c2e-bc9f-622cebba6846.png)
![b0e16c2b669984923fd987fab164b3c](https://user-images.githubusercontent.com/80883358/205530278-c9ed309a-90d8-4285-8568-def90ad6a044.png)

**Comment by andyjpaddle** [comment]
标注工具使用了方向分类器，所以会对竖直方向图像进行旋转校正

**Comment by andyjpaddle** [comment]
可以把https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/PPOCRLabel.py 里面的所有`use_angle_cls`设置为false，然后重新编译安装

**Comment by andyjpaddle** [comment]
这个也改一下：`cls=False`再试试呢

**Comment by Currf** [comment]
> 这个也改一下：`cls=False`再试试呢

还是不行。PPOCRLabel.py的‘cls=False’和‘use_angle_cls=False’都改了

**Comment by guishilike** [comment]
cv2.imdecode 不会处理exif的orientation信息，会导致图片方向不对

**Comment by Currf** [comment]
> cv2.imdecode 不会处理exif的orientation信息，会导致图片方向不对

请问这个应该怎么解决呢

**Comment by guishilike** [comment]
读取图片的时候加处理
![image](https://user-images.githubusercontent.com/51023060/205568551-998986b5-5426-4c8f-af42-3d61ce1af535.png)
或者重新保存一下图片，去掉方向信息

**Comment by Currf** [comment]
> 读取图片的时候加处理 ![image](https://user-images.githubusercontent.com/51023060/205568551-998986b5-5426-4c8f-af42-3d61ce1af535.png) 或者重新保存一下图片，去掉方向信息

可是我看了下，我的图片没有exif信息，原图是bmp格式，裁剪成png，然后crop变成jpg
![d1e76d907a74895c1849d445cf64e7f](https://user-images.githubusercontent.com/80883358/205582193-77a3bfb7-d398-4ccb-84ad-8b4582bb82c6.png)

**Comment by guishilike** [comment]
你可以用cv2.imdecode读一下，看一下图片是否是正的 ，我之前是这个问题

**Comment by Currf** [comment]
> 这个也改一下：`cls=False`再试试呢

大佬，想再请教下，文本分类器如果想增加90度和270度的识别，需要修改算法吗？还是直接修改label_list: ['0','90','180','270']就行了？

**Comment by gl94** [comment]
在那里改没用 要在autoRecognition()这个函数里改

**Comment by 123zhang-bit** [comment]
注释掉三行代码就行了，代码位置PPOCRLabel/libs/utils.py
屏幕截图 2024-03-05 104825

dst_img_height, dst_img_width = dst_img.shape[0:2]
if dst_img_height * 1.0 / dst_img_width >= 1.5:
dst_img = np.rot90(dst_img)

这两行代码的意思是判断你的标注框的高除以宽是否超过1.5，如果超过则进行逆时针旋转90度
