### ISSUE TITLE
paddleOCR识别模型转onnx模型

### ISSUE THREAD

**Issue by wangleiai** [PaddlePaddle/PaddleOCR#854]
请问多会儿支持paddleOCR识别模型转onnx模型呢？

**Comment by littletomatodonkey** [comment]
你好，近期可能不会支持转onnx，你可以基于PaddleLite进行arm端的部署

**Comment by wangleiai** [comment]
> 你好，近期可能不会支持转onnx，你可以基于PaddleLite进行arm端的部署

好的，感谢！
