### ISSUE TITLE
DB网络生成阈值图时，是否可以直接用图像算法的膨胀操作？

### ISSUE THREAD

**Issue by Freshield** [PaddlePaddle/PaddleOCR#8541]
具体代码在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/data/imaug/make_border_map.py
看OCR十讲的时候，这里主要就是根据box边框生成阈值图，其实就是个外扩操作，但是如果用python的polygon方法的话效率很低，而如果只是外扩的话用cv2的膨胀操作相对来讲就会高效的多，这里不用图像算法是因为直接用膨胀操作会有问题吗？还是有什么别的原因？

**Comment by LDOUBLEV** [comment]
和直接膨胀不太一样，阈值图只有文字中心线周围的一圈，计算方式和检测框内像素到四个边的最短距离有关系，https://github.com/PaddlePaddle/PaddleOCR/blob/0c3c48147ee95e8c55f5e00ec1c1cb23c4b25045/ppocr/data/imaug/make_border_map.py#L105
