### ISSUE TITLE
Recognition model does not recognize images with multiple lines.

### ISSUE THREAD

**Issue by Prasanna-iq** [PaddlePaddle/PaddleOCR#8542]
Default Recognition model (ch_PP-OCRv3_xx) does not recognize images with multiple lines.
![image](https://user-images.githubusercontent.com/109642369/205555557-e8640dd6-3827-4ac6-95f5-54066541b42c.png) 
The Prediction result of the above is "Sprice per" which is wrong.

Does retraining the Recognition model with the custom multi line data improves the result? or do i need to pass any parameter for improving the results.

if i need to do the retraining, how many image samples would be sufficient for a robust model? 

Thanks!!

**Comment by andyjpaddle** [comment]
Recognition model only can recognize one line image, you should use text detection model firstly, then use the recognition model. pls refer to this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/inference_ppocr_en.md#text-detection-angle-classification-and-recognition-inference-concatenation
