### ISSUE TITLE
paddleocr 训练时缺少包模块Polygon

### ISSUE THREAD

**Issue by vector2myth** [PaddlePaddle/PaddleOCR#8543]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：V100 16GB
- 版本号/Version：python 3.7 PaddlePaddle 2.1.2  PaddleOCR：2.6.1.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 
- !python3 /home/aistudio/PaddleOCR/tools/train.py -c /home/aistudio/PaddleOCR/configs/rec/rec_icdar15_train.yml \
   -o Global.pretrained_model=/home/aistudio/PaddleOCR//rec_mv3_none_bilstm_ctc_v2.0_train/best_accuracy \
   Global.character_dict_path=/home/aistudio/PaddleOCR//ppocr/utils/ic15_dict.txt \
   Global.eval_batch_step=[0,200] \
   Global.epoch_num=40
- 完整报错/Complete Error Message：
- 
Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR/tools/train.py", line 30, in <module>
    from ppocr.data import build_dataloader
  File "/home/aistudio/PaddleOCR/ppocr/data/__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/__init__.py", line 47, in <module>
    from .ct_process import *
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/ct_process.py", line 22, in <module>
    import Polygon as plg
ModuleNotFoundError: No module named 'Polygon'

**Comment by andyjpaddle** [comment]
依赖都安装了吗？`pip install -r requirements.txt`

**Comment by LeoRainly** [comment]
这个不是pip install Polygon
而是pip install Polygon3
很抗

**Comment by smallzhao** [comment]
需要先卸载之前的 pip uninstall Polygon，然后pip install Polygon3

**Comment by lt152** [comment]
没有作用，还是报错

**Comment by tianxingxia-cn** [comment]
我也一样

**Comment by LeoRainly** [comment]
很坑，要在卸载Polygon的情况下再重新安装Polygon3
