### ISSUE TITLE
window 开启GPU内存泄露

### ISSUE THREAD

**Issue by demonxjj** [PaddlePaddle/PaddleOCR#855]
在window下面,开启GPU的时候使用PPOCR预测的时候,每处理一张图片内存会增加200MB左右,在关闭GPU的情况下,没有任何问题,这个怎么回事,有大神知道不? 图片大小 1.49 MB 1036 *814

**Comment by littletomatodonkey** [comment]
这个是python预测还是cpp预测呢？大概测试多少张图片，程序会因为内存泄露而退出呢？

**Comment by demonxjj** [comment]
cpp预测的,每预测一张图片就增加200MB,我手工测试,最多到了5G的内存,我就要没有继续预测了,我这边是只会在服务器初始化的时候加载模型,然后客户端直接GRPC远程调用服务端预测接口.

**Comment by demonxjj** [comment]
> 这个是python预测还是cpp预测呢？大概测试多少张图片，程序会因为内存泄露而退出呢？
cpp预测的,每预测一张图片就增加200MB,我手工测试,最多到了5G的内存,我就要没有继续预测了,我这边是只会在服务器初始化的时候加载模型,然后客户端直接GRPC远程调用服务端预测接口.

**Comment by MissPenguin** [comment]
内存泄漏问题已修复，拉取最新代码试试哈
