### ISSUE TITLE
Detection Training Annotation 

### ISSUE THREAD

**Issue by hmiche** [PaddlePaddle/PaddleOCR#8550]
Hello guys Thank you for the hardworking .
is there any way a script for exemple to convert labelme or yolo or coco Format to the format accepted by paddleOCR for the Object detection task ?
and Thank you

**Comment by andyjpaddle** [comment]
you can prepare your dataset according to this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/dataset/ocr_datasets_en.md#11-paddleocr-text-detection-format-annotation
and you can write a python script to convert other format to the paddleocr format
