### ISSUE TITLE
kie中的ser任务相关问题

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8553]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 版本号/Version：Paddle：2.4  PaddleOCR：2.6
- 运行指令/Command Code：cd ppstructure
python3 kie/predict_kie_token_ser.py \
  --kie_algorithm=LayoutXLM \
  --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../train_data/XFUND/class_list_xfun.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx"

如何打印识别后的置信度

**Comment by tink2123** [comment]
暂不支持打印置信度
