### ISSUE TITLE
TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by starwith** [PaddlePaddle/PaddleOCR#8554]
- 运行指令/Command Code：
- from paddleocr import PaddleOCR, draw_ocr

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/01.JPG'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

# 显示结果
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

- 完整报错/Complete Error Message：
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1176/3548560358.py in <module>
     16 image = Image.open(img_path).convert('RGB')
     17 boxes = [line[0] for line in result]
---> 18 txts = [line[1][0] for line in result]
     19 scores = [line[1][1] for line in result]
     20 im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')

/tmp/ipykernel_1176/3548560358.py in <listcomp>(.0)
     16 image = Image.open(img_path).convert('RGB')
     17 boxes = [line[0] for line in result]
---> 18 txts = [line[1][0] for line in result]
     19 scores = [line[1][1] for line in result]
     20 im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')

TypeError: 'float' object is not subscriptable

**Comment by tink2123** [comment]
检查下 './fonts/simfang.ttf'  字体文件是否存在呢？

**Comment by starwith** [comment]
请问这个字体文件是要在GitHub库中下载吗，我这边并不存在这个文件夹和包

**Comment by tink2123** [comment]
替换任意字体都可以，或者从这个位置下载字体文件：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/fonts/simfang.ttf

**Comment by starwith** [comment]
我下载了，但是并没有解决。而且报错语句是在查看字体文件语句执行前
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
这两句出现问题

**Comment by skymavo** [comment]
```
from paddleocr import PaddleOCR, draw_ocr
import matplotlib.pyplot as plt
from PIL import Image

## 显示原图，读取名称为11.jpg的测试图像
img_path= "./imgs/00006737.jpg"
img = Image.open(img_path)
plt.figure("test_img", figsize=(5,5))
plt.imshow(img)
plt.show()

## Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
## 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/00006737.jpg'
result = ocr.ocr(img_path, cls=True)
```
> 初始化绘制参数列表，不然会报错“list assignment index out of range”列表超限
```
boxes=[0]*len(result)
txts=[0]*len(result)
scores=[0]*len(result)
```
>3行循环获取结果绘制参数值"boxes[idx] = res[0]     txts[idx] = [line[0] for line in res][1]    scores[idx] = [line[1] for line in res][1]"，原教程boxes不能获取四点定位坐标，txts、scores写法不能准确获取参数值
```
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)
    boxes[idx] = res[0]
    txts[idx] = [line[0] for line in res][1]
    scores[idx] = [line[1] for line in res][1]

## 绘制、保存结果
image = Image.open(img_path).convert('RGB')   
im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

## 显示轻量级模型识别结果
img_path= "./result.jpg"
img = Image.open(img_path)
plt.figure("results_img", figsize=(30,30))
plt.imshow(img)
plt.show()
```
