### ISSUE TITLE
svtr在做验证的时候如何变长

### ISSUE THREAD

**Issue by Henryplay** [PaddlePaddle/PaddleOCR#8555]
哈喽~，我用pytorch复现了咱们库里的svtr代码`https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/modeling/backbones/rec_svtrnet.py`，在训练的时候我设置的宽高size为（320,32），模型已经训好了。但是有个问题想请教一下就是在做预测的时候如何使输入不定长呢？还有个小问题，在`last_stage`时，池化层输出的`是（1，out_char_num）在此之前我可以把这一层用conv2d代替吗，达到把conv2d输出的高变成1的效果，谢谢~

**Comment by Topdu** [comment]
> 如何使输入不定长呢？

目前代码结构无法实现变长输入，需要自己改动代码，具体地：将Local Mixer 替换为Conv，然后把涉及特征图形状的代码修改为动态获取的方式。[优化策略](https://aistudio.baidu.com/aistudio/projectdetail/5073182)。



> 池化层输出的`是（1，out_char_num）在此之前我可以把这一层用conv2d代替吗

可以的，

**Comment by Henryplay** [comment]
@Topdu 好的，感谢解答~
