### ISSUE TITLE
PPOCRLabel点了自动标注后，怎么取消自动标注？

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8556]
已解决 把cache删了就行

问题相关组件/Related components：PPOCRLabel
用了PPOCRLabel自动标注，我的场景是有些文字不需要识别的，自动标注识别了不需要的文字，我想取消自动标注改为手动标，重启软件也不行，一打开还是会显示自动标注后的结果 即使图片的状态是×，这应该怎么办

**Comment by Evezerest** [comment]
建议把数据文件夹下面除了数据意外的其他文件都删掉，如果不需要识别不建议点击自动标注

**Comment by Currf** [comment]
> 建议把数据文件夹下面除了数据意外的其他文件都删掉，如果不需要识别不建议点击自动标注

感谢你，想请教一下，我不想识别空格 但数据集图片有空格 我是应该连着把一行全标注呢还是分开标注？
![77f4e37798174f4f3fa20c5c8388077](https://user-images.githubusercontent.com/80883358/205925844-efd3fd76-d201-489c-9f5c-d920b94a6386.png)
![9c0efec81a4d8a4731492b8758f6385](https://user-images.githubusercontent.com/80883358/205925862-2fc072c9-6dd8-4bc5-a915-126e0c4f53ca.png)

**Comment by Currf** [comment]
> 检测可以按行标注，识别的标签中去掉空格即可，同时在字典文件中也去掉空格字符。

OK谢谢！
