### ISSUE TITLE
dbnet在PostTrainingQuantization后转换onnx失败

### ISSUE THREAD

**Issue by eternal-mind** [PaddlePaddle/PaddleOCR#8557]
使用官方下载的预训练好的dbnet在PostTrainingQuantization后，自测推理结果是正常的，但转换onnx失败。报[ERROR] [GetChannelWiseQuantizeInfo] Require the scale > 0, but now it's 0.000000错误。具体信息如下：

- 系统环境/System Environment：
   Linux ubuntu 4.15.0-144-generic 148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- 版本号/Version：
   python：3.8.13
   paddle2onnx：            1.0.3
   paddleocr：              2.5.0.3
   paddlepaddle：           2.3.2
   paddleslim：             2.3.3
- 问题相关组件/Related components：paddle2onnx
- 运行指令/Command Code：
   paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file quant_model.onnx --deploy_backend onnxruntime --enable_onnx_checker True --opset_version 13
量化后的模型：[inference.zip](https://github.com/PaddlePaddle/PaddleOCR/files/10165531/inference.zip)
- 完整报错/Complete Error Message：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Paramters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model.
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] [Info] Quantize model deploy backend is: onnxruntime
[ERROR] [GetChannelWiseQuantizeInfo] Require the scale > 0, but now it's 0.000000.
Aborted (core dumped)

**Comment by eternal-mind** [comment]
> 可以先参考这个解决方案尝试一下：#5754

已经换成gpu版本的paddle,仍然是报同样的错误
![图片](https://user-images.githubusercontent.com/119935552/206132584-0d54ad3b-5af7-4a47-a269-97f3c7375ad5.png)

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/1003
