### ISSUE TITLE
paddleocr2.6.0 方向分类模型推理任何图片结果都是0方向

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/PaddleOCR#8559]
paddleocr2.6.0 方向分类模型推理任何图片结果都是0方向
python tools/infer/predict_cls.py --image_dir="./doc/imgs_words/ch/word_1.jpg" --cls_model_dir="D:/PaddleOCR-2.6.0/model/ch_ppocr_mobile_v2.0_cls_infer"
![320a0f102a8c208fd1b977d02564bdc](https://user-images.githubusercontent.com/11348670/205915734-7142f4ea-f01c-4586-9c5d-9a7bd886a89e.png)
![6150566ab86b3c318f69a41e3143368](https://user-images.githubusercontent.com/11348670/205915773-3d2047f5-3c9e-4cbc-a0fa-11385db8515d.png)
![9bc07337606c21f1c77cbbb5e555f25](https://user-images.githubusercontent.com/11348670/205915803-33314aa7-6851-42b5-aea6-349e4341e4ec.png)
![48824536dc7631337872efe00437d38](https://user-images.githubusercontent.com/11348670/205915830-6f921036-4c96-4971-940a-6ce1b1c71d09.png)

**Comment by tink2123** [comment]
这三张图都是0度，方向分类器模型只判断两个：0度和180度。 90度图片和90度逆时针旋转都被认为是0度，具体参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/angle_class.md#1-%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D
