### ISSUE TITLE
Why is pyinstaller not analyzing hidden import 'paddle.fluid.proto.framework_pb2'

### ISSUE THREAD

**Issue by waiyeung1** [PaddlePaddle/PaddleOCR#8561]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

Why is pyinstaller not analyzing hidden import 'paddle.fluid.proto.framework_pb2'
Further details here: 
`https://stackoverflow.com/questions/74644338/why-is-pyinstaller-not-analyzing-hidden-import-paddle-fluid-proto-framework-pb2`

- 系统环境/System Environment：Windows 10
- 版本号/Version：Paddle：2.4.0  PaddleOCR：2.6.1.1 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
We have not made related attempts, if you want to use paddleocr under win, you can try https://github.com/raoyutian/PaddleOCRSharp
