### ISSUE TITLE
使用paddleocr训练后的模型可以端侧部署在君正的X2000芯片平台上吗？算子兼容不？

### ISSUE THREAD

**Issue by JavieYuan** [PaddlePaddle/PaddleOCR#8567]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by JavieYuan** [comment]
X2000貌似不是arm的

**Comment by WenmuZhou** [comment]
这个不是很清楚，你可以先在机器上安装paddle看看
