### ISSUE TITLE
安装paddloeocr报错：ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zhangjiaorong** [PaddlePaddle/PaddleOCR#8568]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.8.15
- 版本号/Version：Paddle：2.4.0  PaddleOCR：没安装成功     问题相关组件/Related components：
- 运行指令/Command Code：
1. 安装paddleocr：  pip install paddleocr==2.6.0.2
2. 安装requirements：pip install -r requirements.txt
- 完整报错/Complete Error Message：
1.   error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-38\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
Installing collected packages: pytz, PyMuPDF, pyclipper, Polygon3, lmdb, zipp, tifffile, scipy, rapidfuzz, PyWavelets, python-dateutil, pyparsing, pycryptodome, opencv-python, opencv-contrib-python, networkx, MarkupSafe, lxml, kiwisolver, itsdangerous, imageio, future, fonttools, et-xmlfile, dill, cython, cycler, cssutils, cssselect, contourpy, colorama, cachetools, Babel, attrdict, Werkzeug, tqdm, premailer, pandas, packaging, openpyxl, multiprocess, Jinja2, importlib-metadata, click, bce-python-sdk, scikit-image, matplotlib, flask, imgaug, Flask-Babel, visualdl, paddleocr
  Running setup.py install for Polygon3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Polygon3 did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Using NumPy extension!
      running install
      F:\Anaconda3\envs\paddle38\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-38\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Polygon3

2. error: subprocess-exited-with-error

  × Building wheel for lanms-neo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lanms
      copying lanms\__init__.py -> build\lib.win-amd64-cpython-38\lanms
      running build_ext
      building 'lanms._C' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lanms-neo
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-38\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build lanms-neo Polygon3
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by zhangjiaorong** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：python 3.8.15
> * 版本号/Version：Paddle：2.4.0  PaddleOCR：没安装成功     问题相关组件/Related components：
> * 运行指令/Command Code：
> 
> 1. 安装paddleocr：  pip install paddleocr==2.6.0.2
> 2. 安装requirements：pip install -r requirements.txt
> 
> * 完整报错/Complete Error Message：
> 
> 1. error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [14 lines of output] Using NumPy extension! running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-38 creating build\lib.win-amd64-cpython-38\Polygon copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon__init__.py -> build\lib.win-amd64-cpython-38\Polygon running build_ext building 'Polygon.cPolygon' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for Polygon3 Running setup.py clean for Polygon3 Failed to build Polygon3 Installing collected packages: pytz, PyMuPDF, pyclipper, Polygon3, lmdb, zipp, tifffile, scipy, rapidfuzz, PyWavelets, python-dateutil, pyparsing, pycryptodome, opencv-python, opencv-contrib-python, networkx, MarkupSafe, lxml, kiwisolver, itsdangerous, imageio, future, fonttools, et-xmlfile, dill, cython, cycler, cssutils, cssselect, contourpy, colorama, cachetools, Babel, attrdict, Werkzeug, tqdm, premailer, pandas, packaging, openpyxl, multiprocess, Jinja2, importlib-metadata, click, bce-python-sdk, scikit-image, matplotlib, flask, imgaug, Flask-Babel, visualdl, paddleocr Running setup.py install for Polygon3 ... error error: subprocess-exited-with-error
> 
> × Running setup.py install for Polygon3 did not run successfully. │ exit code: 1 ╰─> [16 lines of output] Using NumPy extension! running install F:\Anaconda3\envs\paddle38\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py creating build creating build\lib.win-amd64-cpython-38 creating build\lib.win-amd64-cpython-38\Polygon copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon__init__.py -> build\lib.win-amd64-cpython-38\Polygon running build_ext building 'Polygon.cPolygon' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> Polygon3
> 
> 2. error: subprocess-exited-with-error
> 
> × Building wheel for lanms-neo (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [10 lines of output] running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-38 creating build\lib.win-amd64-cpython-38\lanms copying lanms__init__.py -> build\lib.win-amd64-cpython-38\lanms running build_ext building 'lanms._C' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for lanms-neo Building wheel for Polygon3 (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [14 lines of output] Using NumPy extension! running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-38 creating build\lib.win-amd64-cpython-38\Polygon copying Polygon\IO.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon\Utils.py -> build\lib.win-amd64-cpython-38\Polygon copying Polygon__init__.py -> build\lib.win-amd64-cpython-38\Polygon running build_ext building 'Polygon.cPolygon' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for Polygon3 Running setup.py clean for Polygon3 Failed to build lanms-neo Polygon3 ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by JimmyLyods** [comment]
我在安裝paddleOCR的時候,
一樣出現錯誤,
我的錯誤是
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-985f70d667ea> in <module>
----> 1 import Polygon

ModuleNotFoundError: No module named 'Polygon'

執行from paddleocr import PaddleOCR, draw_ocr發生的
一直沒辦法排除

**Comment by WenmuZhou** [comment]
先手动安装报错的模块看看呢

**Comment by zhangjiaorong** [comment]
> 先手动安装报错的模块看看呢
好的，谢谢！我这边手动安装Polygon3之后可以安装paddleocr==2.6.0.2；但是出现了新的问题：
 ERROR: Failed building wheel for lanms-neo
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

**Comment by JimmyLyods** [comment]
請問paddleOCR是否限定GPU的環境,
CPU的環境也可正常安裝嗎?

**Comment by WenmuZhou** [comment]
可以的

**Comment by Mrfuhang** [comment]
这个问题有解决吗？（Has the problem been solved）

**Comment by Monty-L** [comment]
我是Ubuntu 22.04.3版本，出现这个问题是因为环境冲突了。
只要成功安装了 build-essential就能解决（里面包含一些基本的依赖）。
我一开始无法安装build-essential，是因为我换源的时候忘记更改ubantu的版本代号，导致换源成旧版本的源，在后续update的时候导致安装build-essential所依赖的环境全部出错,因此装不了build-essential。我换了正确的源后，再sudo apt-get update; sudo apt-get upgrade; sudo apt-get install build-essential; python3 -m pip install -r requirements.txt     就能安装。
