### ISSUE TITLE
The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 126)

### ISSUE THREAD

**Issue by changmaoguai** [PaddlePaddle/PaddleOCR#8575]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
Microsoft Windows 10 家庭中文版

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddlepaddle-gpu-2.4.0.post117
paddleocr             2.6.1.1

- 运行指令/Command Code：
from paddleocr import PaddleOCR
import os
import re
import paddle
import time
import pandas as pd

picture_ocr = os.listdir('./report/')
os.environ['path'] = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin;'
os.environ['path'] += r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include;'
os.environ['path'] += r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp;'
os.environ['path'] += r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive\bin;'

def ocr_(start, end):
    content_picture = []
    ocr_user = PaddleOCR(use_angle_cls=True, use_gpu=True, show_log=False)
    for i_ in range(start, end):
        img_path = './report/' + picture_ocr[i_]
        result = ocr_user.ocr(img_path)
        str_x = str(picture_ocr[i_]) + '>>>'
        for line in result:
            str_x += re.sub('\s+', '', str(line[-1][-2]))
        content_picture.append(str_x)
        print(i_, '识别完毕')
    data_picture_p_ = pd.DataFrame(content_picture, columns=['content'])
    data_picture_p_.to_excel(f'./data/data_picture_{start}.xlsx', index=False)

paddle.utils.run_check()
now = time.time()
ocr_(0, 97)
cost_time = (time.time() - now) / 60
print('耗时', cost_time, '分钟……')

- 完整报错/Complete Error Message：
Running verify PaddlePaddle program ... 
W1208 13:11:26.769198 18940 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W1208 13:11:26.774199 18940 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

Traceback (most recent call last):
  File "E:\xjsinopharm_report_integration_system\test_3.py", line 79, in <module>
    ocr_(0, 97)
  File "E:\xjsinopharm_report_integration_system\test_3.py", line 20, in ocr_
    ocr_user = PaddleOCR(use_angle_cls=True, use_gpu=True, show_log=False)
  File "C:\Users\zhaoxiangyu\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\paddleocr.py", line 502, in __init__
    super().__init__(params)
  File "C:\Users\zhaoxiangyu\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Users\zhaoxiangyu\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "C:\Users\zhaoxiangyu\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:305)

**Comment by littletomatodonkey** [comment]
看着是没找到cuda环境，需要修改下系统的环境变量哈

**Comment by littletomatodonkey** [comment]
paddleocr也支持cuda10.1的，不过paddle2.4之后的版本不支持了

**Comment by changmaoguai** [comment]
如果没有找到系统环境的话应该不会出现这个吧？
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by changmaoguai** [comment]
> paddleocr也支持cuda10.1的，不过paddle2.4之后的版本不支持了



> 看着是没找到cuda环境，需要修改下系统的环境变量哈

如果没有找到CUDA环境的话，应该不会出现这个吧？
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by changmaoguai** [comment]
> paddleocr也支持cuda10.1的，不过paddle2.4之后的版本不支持了

paddleocr2.6是否支持cuda11.7？
