### ISSUE TITLE
paddleocr how to make results visualization

### ISSUE THREAD

**Issue by MaxokDavid** [PaddlePaddle/PaddleOCR#8577]
I can get text and recognition confidence,but what step to make results visualization following https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/quickstart_en.md#12-install-paddleocr-whl-package

When I put code "paddleocr --image_dir=../doc/table/1.png --type=structure" in to anaconda prompt,get "raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in ./doc/table/1.png"

**Comment by littletomatodonkey** [comment]
需要保证传入的图片路径是存在的
