### ISSUE TITLE
版面分析如何寻找对应的yml 文件

### ISSUE THREAD

**Issue by Elijah-Yi** [PaddlePaddle/PaddleOCR#8583]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
![image](https://user-images.githubusercontent.com/22116117/206378964-58862eda-930d-44ed-b0d8-806ec15b5f5f.png)
这个图片中的 ppyolov2_r50vd_dcn_365e_publaynet 模型  如何找到对应的yml 文件？在文件路径中并没有找到对应的配置文件PaddleDetection/configs/ppyolo  还请告知，麻烦了 谢谢 
- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Fissionalist** [comment]
![image](https://user-images.githubusercontent.com/63892079/234016210-77bf502c-7581-4ea2-a85f-7327c5a4ba67.png)
