### ISSUE TITLE
How to use PaddleGPU with CUDA version 11.4 on Linux

### ISSUE THREAD

**Issue by MrAsifKhan** [PaddlePaddle/PaddleOCR#8584]
![CUDA version](https://user-images.githubusercontent.com/100809935/206418579-6903c948-be16-480c-a81b-097a798202f4.PNG)
I have a Linux machine with CUD version 11.4 and currently Paddle GPU does not support this CUDA version. 
Is the process of making PaddleGPU support CUDA v11.4 is already under development? If yes then by when can we expect it to be available?
And also is there any workaround to make PaddleGPU work with CUDA v11.4 using some other tools?
Suggestions are welcomed!

**Comment by jingsongliujing** [comment]
You can find the Docker image：https://hub.docker.com/layers/paddlepaddle/paddle/latest-dev-cuda11.4.1-cudnn8-gcc82/images/sha256-fc86f80ceb6e4681d04f438586c4784483681f27de06622c0ef299262058b220?context=explore

**Comment by harshnandwana** [comment]
sudo docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it --gpus all registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7 /bin/bash
