### ISSUE TITLE
请问ppocr有支持华为升腾AscendNPU的方案吗

### ISSUE THREAD

**Issue by sliver-7** [PaddlePaddle/PaddleOCR#8585]
x86-CPU +Ascend NPU

**Comment by jingsongliujing** [comment]
参考这里：https://www.paddlepaddle.org.cn/lite/develop/demo_guides/huawei_ascend_npu.html

**Comment by litch-cl** [comment]
我在200DK上尝试部署ppocr，咱们也许可以讨论一下。
