### ISSUE TITLE
PaddleOCR github serving

### ISSUE THREAD

**Issue by MaxokDavid** [PaddlePaddle/PaddleOCR#8587]
I use anaconda make enviroment with python3.7, named paddle_env. where should I copy PaddleOCR in the enviroment-paddle_env, from https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4

**Comment by jingsongliujing** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/quickstart_en.md
