### ISSUE TITLE
LayoutLMV3 model for  Entity Recognition and Relation Extraction module

### ISSUE THREAD

**Issue by ChidanandKumarVimaan** [PaddlePaddle/PaddleOCR#8588]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
Any updates on LayoutLMV3 model for  Entity Recognition and Relation Extraction module

**Comment by an1018** [comment]
You can refer to our latest work : [VI-LayoutXLM](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/algorithm_kie_vi_layoutxlm_en.md)
