### ISSUE TITLE
Logger not found when test hubserving ocr_system locally

### ISSUE THREAD

**Issue by sheltonsuen** [PaddlePaddle/PaddleOCR#8589]
在本地调试 deploy hub serving 的过程中，报：
    from paddlehub.common.logger import logger
ModuleNotFoundError: No module named 'paddlehub.common'

- 系统环境/System Environment：Win11
- 版本号/Version：Paddle： PaddleOCR：  2.6.0.1 问题相关组件/Related components：deploy/hubserving/ocr_system
- 运行指令/Command Code：python deploy/hubserving/ocr_system/module.py
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File ".\apps\deploy\ocr\module.py", line 25, in <module>
    from paddlehub.common.logger import logger
ModuleNotFoundError: No module named 'paddlehub.common'

**Comment by sheltonsuen** [comment]
是我吧前面的paddlehub 删除了，后面的就找不到了，

![image](https://user-images.githubusercontent.com/44127430/206654759-3610c041-6817-4bd0-a7a9-74331a730d76.png)

额，所以如果这儿没有什么特殊情况的话建议直接用tools里面封装好的logger， 避免疑惑， 跟这个类似: https://github.com/PaddlePaddle/PaddleOCR/pull/8590/commits

**Comment by an1018** [comment]
是找不到paddlehub.common，先import paddlehub就可以了

**Comment by sheltonsuen** [comment]
close it as resolved
