### ISSUE TITLE
宽文本无法识别，见图

### ISSUE THREAD

**Issue by znsoftm** [PaddlePaddle/PaddleOCR#859]
文本行比较宽的时候，无法正确识别，只能识别几个字。
![QQ图片20200927102522](https://user-images.githubusercontent.com/15354249/94354234-c33e9c00-00ab-11eb-8221-dc0e7c55c4ae.png)

**Comment by littletomatodonkey** [comment]
你好，可以提供一下你那边测试的原始图片吗？

**Comment by littletomatodonkey** [comment]
检测的时候默认resize最长边到960，你这种情况下，高度基本上会被变为很小的值，字已经基本上看不清了，可以试下将这个参数改为3200， `--det_max_side_len=3200`，我这边测试效果看着还不错

![image](https://user-images.githubusercontent.com/14270174/94356490-d65c6680-00c1-11eb-913c-158ade845486.png)

**Comment by znsoftm** [comment]
感谢：）
