### ISSUE TITLE
训练的cur metric和best metric的关系是什么

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8594]
为什么训练的时候cur metric的precision都超过之前的best metric了，best metric还不更新为最高的precision？这个对最后的best_accruacy有影响吗？我只想取最好的结果
![1670600199203](https://user-images.githubusercontent.com/80883358/206737843-27e7ae8b-f38e-4a30-be3a-03f4584912e4.png)

**Comment by thsno02** [comment]
训练检测模型的时候，一般是以 hmean 作为最终的评价指标，而不是 precision。cur = current，当前测试集的评价，best 是指从训练伊始到现在最好的评价。

**Comment by Currf** [comment]
> 训练检测模型的时候，一般是以 hmean 作为最终的评价指标，而不是 precision。cur = current，当前测试集的评价，best 是指从训练伊始到现在最好的评价。

好的，谢谢你！

**Comment by GUOhm230** [comment]
您好。
1。使用mobileNet作为骨干网络，训练新的检测模型，发现best指标hmean也就41
2。使用resnet50作为骨干网络，150/1200就有49。但是模型太大，用他做nni裁剪可以实现嘛？
但是我看有些论文的F1 SCORE都是75+,请问，我们这个模型的数值这么低是为什么？
