### ISSUE TITLE
vi-layoutxlm可以用来做文本顺序的预测吗？

### ISSUE THREAD

**Issue by pogevip** [PaddlePaddle/PaddleOCR#8599]
看到论文pretrain里有提到，没有看到预训练相关的代码，可以给个样例吗

**Comment by MissPenguin** [comment]
目前下游任务只支持ser和re，核心代码可以看这个：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/modeling/backbones/vqa_layoutlm.py
