### ISSUE TITLE
敏感度分析报错

### ISSUE THREAD

**Issue by JawerZ** [PaddlePaddle/PaddleOCR#860]
![image](https://user-images.githubusercontent.com/59463796/94355080-79f24a80-00b3-11eb-8039-114b80163581.png)

**Comment by JawerZ** [comment]
![image](https://user-images.githubusercontent.com/59463796/94355685-bffddd00-00b8-11eb-9574-473e015c57a5.png)
量化也报错

**Comment by yukavio** [comment]
请问用的是Paddleslim的哪个版本，可以按照示例教程安装PaddleSlim的develop版本后再运行试试

**Comment by JawerZ** [comment]
> 请问用的是Paddleslim的哪个版本，可以按照示例教程安装PaddleSlim的develop版本后再运行试试
是按照教程git clone后再python setup.py install的

**Comment by yukavio** [comment]
请确认一下PaddleSlim Repo是在develop分支下吗

**Comment by JawerZ** [comment]
> 请确认一下PaddleSlim Repo是在develop分支下吗

确认的 从github的develop分支又下载了一次 还是不行
![image](https://user-images.githubusercontent.com/59463796/94361088-70350b00-00e4-11eb-818f-1a4ea71b2861.png)

**Comment by MissPenguin** [comment]
目前最新代码是没有问题的，可以先拉取最新代码试试哈，如果仍有问题欢迎重新提issue～
