### ISSUE TITLE
文本超分训练模型转推理模型报错

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/PaddleOCR#8600]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
按照教程链接：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_sr_telescope.md
命令：python3 tools/export_model.py -c configs/sr/sr_telescope.yml -o Global.pretrained_model={path/to/weights}/best_accuracy Global.save_inference_dir=./inference/sr_out
![image](https://user-images.githubusercontent.com/45508593/206943784-1ee8a10d-7847-4d47-95ad-24b4defc405f.png)

**Comment by tink2123** [comment]
感谢反馈，确认模型导出有误，我们尽快修复
