### ISSUE TITLE
DB++ had a very poor result?

### ISSUE THREAD

**Issue by dolphincats** [PaddlePaddle/PaddleOCR#8601]
I export the official training model(DB++)， I got a poor result in the example image during the inference process.

**Comment by harshnandwana** [comment]
to get better results try increasing east crop ratio to [960,960]

**Comment by trthminh** [comment]
> 

where i can find crop ratio ?

**Comment by TuanBC** [comment]
The official paddleocr package is using DB preprocessing, not DB++

https://github.com/PaddlePaddle/PaddleOCR/blob/36bf83239d1dae39baf4b330b2b283373610f48b/tools/infer/utility.py#L49

There is some differences with the way input image is normalizing, thus there will be a drop if you don't change this params with the inference package.
