### ISSUE TITLE
ubuntu 3090 训练异常终止

### ISSUE THREAD

**Issue by Elijah-Yi** [PaddlePaddle/PaddleOCR#8603]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
<img width="667" alt="image" src="https://user-images.githubusercontent.com/22116117/206982144-a3bd8648-9b8a-4020-9ae5-ebd8bb7caee3.png">
训练过程中突然某块GPU内存 增加很大，然后过段时间训练崩溃。显示错误 GPU 内存不足。batch-size 16
- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.3.2-gpu
- 运行指令/Command Code：python -m paddle.distributed.launch --gpus '0,1,2,3,4,5,6,7'  tools/train.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    --eval
- 完整报错/Complete Error Message：
第4 块GPU 内存不足

**Comment by LDOUBLEV** [comment]
其他进程运行导致的，4号卡有两个进程
<img width="751" alt="image" src="https://user-images.githubusercontent.com/26592129/207200524-01961c41-8299-466f-b1b4-e21cba20da4f.png">
