### ISSUE TITLE
请教一下，目前用paddle训练，先日文训练，效果还可以，后面在此基础上追加了中文，但是中文就很改善了，这种是要全新从头训练？不能追加训练进行改善？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8604]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： 2.5 PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请教一下，目前用paddle训练，先日文训练，效果还可以，后面在此基础上追加了中文，但是中文就很改善了，这种是要全新从头训练？不能追加训练进行改善？

**Comment by nissansz** [comment]
是混合训练的。只是分了两步。第一步训练日文，第二步混合。这种中文几乎没什么改善。
是不是要一开始就要混合，全新训练才可以？
同样的，比如要追加训练韩文，繁体等，也是要全新训练？

**Comment by LDOUBLEV** [comment]
一开始就混合训练，日文和中文的数据比例根据你的情况设置

**Comment by LDOUBLEV** [comment]
追加的前提最好是识别的字符数量没有变化，你的情况是先训练日文，再训练中文，最好是中文和日文一起训练。
适合微调的情况：
1. 数据量不足
2. 不修改识别的字符数量和网络结构（使用PaddleOCR发布的模型，基于这个模型在不改变字典的情况下在你的数据上finetune效果比较好。）

**Comment by nissansz** [comment]
字典是没有改的，把所有语言的字符都放在里面了。
只是想分批分语种训练。

另外mobilenetv3 支持的字符数有限制吗？
还是说必须用其他模型，resnet34，才能支持更多字符？
