### ISSUE TITLE
Layout Analysis ppyolov2 models missing infer_cfg.yml

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8606]
These `ppyolov2` models here seem to be missing the `infer_cfg.yml` file. Is there a reason for this? How can I get/generate a config file for these models?

![image](https://user-images.githubusercontent.com/83645945/207238621-87ffc49a-b416-4f65-a617-713a2effb868.png)

**Comment by andyjpaddle** [comment]
layout analysis model are trained by using PaddleDetection, you can find the related config in here https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs
