### ISSUE TITLE
使用PaddleOCR调用，部分图片处理出错  could not execute a primitive

### ISSUE THREAD

**Issue by chenyu0** [PaddlePaddle/PaddleOCR#8607]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Debian 4.19.98-1  x86_64
- 版本号/Version：PaddleOCR 2.6.0.1
- 运行指令/Command Code：
```
OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False, use_gpu=False)
result = OCR.ocr(pic, cls=True)
```
- 完整报错/Complete Error Message：
```
File "main.py", line 121, in reciveosspicdisLog
    data = server.ocrpic(file_content)
  File "/app/easy.ocr/service/ocr_server.py", line 87, in ocrpic
    result = OCR.ocr(pic, cls=True)
  File "/app/easy.ocr/easy-ocr-env/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 524, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/app/easy.ocr/easy-ocr-env/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/app/easy.ocr/easy-ocr-env/lib/python3.7/site-packages/paddleocr/tools/infer/predict_det.py", line 234, in __call__
    self.predictor.run()
RuntimeError: could not execute a primitive
```
在使用CPU并且开启mkldnn加速的时候，虽然速度有所提升，但是偶尔会出现以上报错；
怎么在速度不会降低的情况下，把此问题解决？

**Comment by andyjpaddle** [comment]
paddle版本是多少？

**Comment by chenyu0** [comment]
paddlepaddle 版本 2.3.2

**Comment by andyjpaddle** [comment]
可以提供下问题复现代码吗，我这边循环多次开启mkldnn预测都是正常的

**Comment by chenyu0** [comment]
代码很简单，就是上述所描述的
```
OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False, use_gpu=False)
result = OCR.ocr(pic, cls=True) 
```
我在本地使用windows也没有复现到具体的问题，但是在服务器上启动，就会较频繁偶现此问题

**Comment by chenyu0** [comment]
详细代码如下：
```
OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False, use_gpu=False)
class OcrServer:
    def ocrpic(self, pic):
        result = OCR.ocr(pic, cls=True)
        resultdata = []
        if result:
            for line in result:
                # ...
                # resultdata.append
        return resultdata
```

**Comment by andyjpaddle** [comment]
我这边没有复现出你的这个问题，可以用try来处理一下
```
OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=False, use_angle_cls=False, use_gpu=False)
try:
    result = OCR.ocr(pic, cls=True) 
except:
    OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=False, use_angle_cls=False, use_gpu=False)
    result = OCR.ocr(pic, cls=False) 
```
另外你的参数要纠正一下，`use_tensorrt=True`是`use_gpu=True`时才生效，`use_angle_cls`和`cls`也要一致

**Comment by chenyu0** [comment]
感谢，我尝试一下

**Comment by isXuedingesCat** [comment]
> 

我这里在Linux上也有这个问题，window下没有出现，现在的解决方式是不使用预先构建模型的办法，在每一次处理图片时重新生成OCR模型。

**Comment by bigmover** [comment]
> 可以提供下问题复现代码吗，我这边循环多次开启mkldnn预测都是正常的
是使用多线程调用还是for 循环

**Comment by bigmover** [comment]
> 我这边没有复现出你的这个问题，可以用try来处理一下
> 
> ```
> OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=False, use_angle_cls=False, use_gpu=False)
> try:
>     result = OCR.ocr(pic, cls=True) 
> except:
>     OCR = PaddleOCR(enable_mkldnn=True, use_tensorrt=False, use_angle_cls=False, use_gpu=False)
>     result = OCR.ocr(pic, cls=False) 
> ```
> 
> 另外你的参数要纠正一下，`use_tensorrt=True`是`use_gpu=True`时才生效，`use_angle_cls`和`cls`也要一致

请教一下，这里重新初始化是为了什么（这样会导致耗时增加）？有其他的解决方法吗？

**Comment by swap453** [comment]
@chenyu0 is this issue resolved, I am running into same issue, any insights would be helpful

**Comment by uniqlo1** [comment]
请问现在这个问题有解决吗？在不关闭mkldnn加速的情况下

**Comment by pengpengno** [comment]
same in ubuntu 20.04   , wait  feedback

**Comment by swap453** [comment]
> 请问现在这个问题有解决吗？在不关闭mkldnn加速的情况

The issue is resolved, but the solution is not ideal. Calling Paddle OCR every time instead of declaring it once helped avoid the error, but it negatively affects processing time.

**Comment by swap453** [comment]
I am facing this issue only on docker, on my local its running fine

**Comment by uniqlo1** [comment]
> 在 Ubuntu 20.04 中相同，等待反馈

请问您能提供您出现该错误的代码吗，可以查看#13407,您是否可以将复制的代码提供给[LLee233](https://github.com/LLee233)做一个复现？以检查该问题。

**Comment by uniqlo1** [comment]
> 我只在docker上遇到这个问题，在我的本地运行良好

请问您能提供您出现该错误的代码吗，可以查看#13407,您是否可以将复制的代码提供给[LLee233](https://github.com/LLee233)做一个复现？以检查该问题。

**Comment by cxiaowen** [comment]
这个问题解决没，我也是出现这个问题，换了几个版本

**Comment by uniqlo1** [comment]
> 这个问题解决没，我也是出现这个问题，换了几个版本

请问您能提供代码以供参考吗？非常感谢

**Comment by lakwsh** [comment]
遇到了同样的问题，对于同一张图片重复执行ocr特别容易复现

**Comment by AlanWu3115** [comment]
安装paddle-gpu 使用gpu 几乎不会报错

但是cpu预测，遇到了同样的问题，安装有paddle-gpu，但不使用gpu，转而使用cpu预测时，对于同一张图片重复执行ocr特别容易复现。
如下是我的环境，Inetl i9 12900HX显卡，RTX3060 GPU 140w
(paddleocrv4) PS D:\3\paper_rec> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:56:38_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0
(paddleocrv4) PS D:\3\paper_rec> pip list       
Package                  Version
------------------------ -----------
albucore                 0.0.15
albumentations           1.4.10
annotated-types          0.7.0
anyio                    4.4.0
astor                    0.8.1
beautifulsoup4           4.12.3
blinker                  1.8.2
bs4                      0.0.2
certifi                  2024.8.30
charset-normalizer       3.3.2
click                    8.1.7
colorama                 0.4.6
coloredlogs              15.0.1
contourpy                1.3.0
cycler                   0.12.1
Cython                   3.0.11
decorator                5.1.1
docx                     0.2.4
exceptiongroup           1.2.1
Flask                    3.0.3
flatbuffers              24.3.25
fonttools                4.53.1
h11                      0.14.0
httpcore                 1.0.5
httpx                    0.27.0
humanfriendly            10.0
idna                     3.8
imageio                  2.35.1
imgaug                   0.4.0
itsdangerous             2.2.0
Jinja2                   3.1.4
joblib                   1.4.2
kiwisolver               1.4.7
lazy_loader              0.4
lmdb                     1.5.1
lxml                     5.3.0
MarkupSafe               2.1.5
matplotlib               3.9.2
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.3.4.1
nvidia-cuda-nvrtc-cu12   12.5.40
nvidia-cuda-runtime-cu12 12.3.101
nvidia-cudnn-cu12        9.0.0.312
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nvjitlink-cu12    12.5.40
onnxruntime-gpu          1.19.2
opencv-contrib-python    4.10.0.84
opencv-python            4.10.0.84
opencv-python-headless   4.10.0.84
opt-einsum               3.3.0
packaging                24.1
paddlepaddle-gpu         3.0.0b1
pillow                   10.4.0
pip                      24.2
protobuf                 5.27.1
pyclipper                1.3.0.post5
pydantic                 2.9.1
pydantic_core            2.23.3
pyparsing                3.1.4
pyreadline3              3.4.3
python-dateutil          2.9.0.post0
python-docx              1.1.2
PyYAML                   6.0.2
rapidfuzz                3.9.7
requests                 2.32.3
scikit-image             0.24.0
scikit-learn             1.5.2
scipy                    1.14.1
setuptools               72.1.0
shapely                  2.0.6
six                      1.16.0
sniffio                  1.3.1
some-package             0.1
soupsieve                2.6
sympy                    1.13.2
threadpoolctl            3.5.0
tifffile                 2024.8.30
tqdm                     4.66.5
typing_extensions        4.12.2
urllib3                  2.2.3
Werkzeug                 3.0.4
wheel                    0.44.0

**Comment by AlanWu3115** [comment]
> 遇到了同样的问题，对于同一张图片重复执行ocr特别容易复现

+1 试试cpu，但是我这边就是可能会用cpu的方案，gpu预测推理快很多，这边会测试一下使用cpu版本的paddle看看是否解决的

**Comment by lakwsh** [comment]
> > 遇到了同样的问题，对于同一张图片重复执行ocr特别容易复现
> 
> +1 试试gpu预测，但是我这边就是可能会用cpu的方案，gpu预测推理快很多，这边会测试一下使用cpu版本的paddle看看是否解决的

主要是我服务器没有gpu...我只能用cpu的解决方案，我现在的处理方式是把输入图像算一遍hash，对于同一张图标直接返回缓存结果，还有就是在PaddleOCR.ocr套一层try except，出现异常的时候重新调用一次PaddleOCR初始化。

**Comment by AlanWu3115** [comment]
> > > 遇到了同样的问题，对于同一张图片重复执行ocr特别容易复现
> > 
> > 
> > +1 试试gpu预测，但是我这边就是可能会用cpu的方案，gpu预测推理快很多，这边会测试一下使用cpu版本的paddle看看是否解决的
> 
> 主要是我服务器没有gpu...我只能用cpu的解决方案，我现在的处理方式是把输入图像算一遍hash，对于同一张图标直接返回缓存结果，还有就是在PaddleOCR.ocr套一层try except，出现异常的时候重新调用一次PaddleOCR初始化。

参考https://github.com/PaddlePaddle/PaddleOCR/issues/3313   实际也都是自行解决的，官方没给出十分具体的方案，GPU版本是没问题的，CPU的坑比较多

**Comment by aliencaocao** [comment]
Same here, paddle 3.0 beta1, windows 10, cpu only

**Comment by pandachen7** [comment]
+1
我用ubuntu 20.04, paddle 3.0.0 beta1跑第二次都會出現這個錯誤
難道只能用try迴避？

**Comment by cobaltautomationdev** [comment]
我今天2025.02.07 也出现了这个错误提示，是在CPU上运行的。 我的电脑因为无法使用GPU. windows大概跑了4个小时之后出现了这个错误提示，就停止了。

**Comment by vaguest** [comment]
Using the flask library to implement the web service, you can replace the fastapi library, which solves the problem.

**Comment by Dien666** [comment]
我遇到了这个问题，在CPU机器执行，无GPU加速。尝试使用多线程执行时复现。

import concurrent
import os
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime

import PyPDF2
from paddleocr import PaddleOCR

# 定义下载目录
DOWNLOAD_DIRECTORY = "./files/"

ocr1 = PaddleOCR(
    det_model_dir='./inference/ch_PP-OCRv3_det_infer',
    rec_model_dir='./inference/ch_PP-OCRv3_rec_infer',
    cls_model_dir='./inference/ch_ppocr_mobile_v2.0_cls_infer',
    use_angle_cls=True, lang="ch",
    cpu_threads=4,
    use_mp=True,
    total_process_num=8
)

ocr2 = PaddleOCR(
    det_model_dir='./inference/ch_PP-OCRv3_det_infer',
    rec_model_dir='./inference/ch_PP-OCRv3_rec_infer',
    cls_model_dir='./inference/ch_ppocr_mobile_v2.0_cls_infer',
    use_angle_cls=True, lang="ch",
    cpu_threads=4,
    use_mp=True,
    total_process_num=8
)

def split_pdf(input_pdf_path):
    # 获取输入文件的文件名（不包括扩展名）
    input_filename = os.path.splitext(os.path.basename(input_pdf_path))[0]
    # 使用文件名作为输出文件夹的名称
    output_folder = DOWNLOAD_DIRECTORY
    # 打开输入的 PDF 文件
    with open(input_pdf_path, 'rb') as pdf_file:
        # 创建一个 PDF 阅读器对象
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        # 获取 PDF 的总页数
        num_pages = len(pdf_reader.pages)
        if num_pages <= 2:
            return [input_pdf_path]
        # 用于存储输出文件路径的列表
        output_paths = []
        # 遍历每一页
        for page_number in range(num_pages):
            # 创建一个 PDF 写入器对象
            pdf_writer = PyPDF2.PdfWriter()
            # 添加当前页到 PDF 写入器
            pdf_writer.add_page(pdf_reader.pages[page_number])
            # 输出文件路径
            output_pdf_path = os.path.join(output_folder, f"{input_filename}_page_{page_number + 1}.pdf")
            # 写入单独的 PDF 文件
            with open(output_pdf_path, 'wb') as output_pdf_file:
                pdf_writer.write(output_pdf_file)
            # 将输出路径添加到列表中
            output_paths.append(output_pdf_path)
        # 返回所有输出文件路径
        return output_paths

def ocr_process(file_path, ocr):
    if file_path is None:
        return ''

    try:
        ocr_result = ocr.ocr(file_path, cls=True)
        file_content = ''
        for row in ocr_result:
            for col in row:
                file_content = file_content + '\n' + col[1][0]

        return file_content
    except Exception as e:
        print(f"An unexpected error occurred: {str(e)}", e)
        raise e
    finally:
        if file_path and os.path.exists(file_path):
            os.remove(file_path)


def main():
    context = ''

    start = datetime.now().timestamp()
    # 识别的文件路径
    img_path = './files/Test1.pdf'
    file_splits = split_pdf(img_path)

    ## 执行报错 could not execute a primitive
    with concurrent.futures.ThreadPoolExecutor() as executor:
        future1 = executor.submit(ocr_process, file_splits[0], ocr1);
        future2 = executor.submit(ocr_process, file_splits[1], ocr1);
        print('ocr task submitted')
        try:
            result1 = future1.result();
            result2 = future2.result();
            print(result1 + result2)
        except Exception as e:
            print(f'Task failed: {e}')
            raise e

    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = [executor.submit(ocr_process(file_path=file_split, ocr=ocr1)) for file_split in file_splits]
        print('ocr task submitted')
        try:
            for future in concurrent.futures.as_completed(futures):
                print(str(future.result()))
        except Exception as e:
            print(f'Task failed: {e}')
            raise e

    end = datetime.now().timestamp()
    print('ocr time cost = ' + str(end - start))


if __name__ == "__main__":
    main()
