### ISSUE TITLE
SRN训练从epoch0到epoch1时loss突然变大很多，正常吗？

### ISSUE THREAD

**Issue by FieldRen** [PaddlePaddle/PaddleOCR#861]
![1601177554027](https://user-images.githubusercontent.com/29041332/94355242-339deb00-00b5-11eb-8d79-b7d011db52e5.jpg)

**Comment by tink2123** [comment]
一般不会出现这个情况，数据是用benchmark格式读取的吗？是不是没有做shuffle

**Comment by FieldRen** [comment]
> 一般不会出现这个情况，数据是用benchmark格式读取的吗？是不是没有做shuffle

1. 数据是自己做的lmdb，读取数据的部分做了修改，但是是非常靠前的步骤；应该不影响模型训练部分；
2. 我看了下代码是有shuffle的；
3. SRN baseline训benchmark好像也有这个现象，如下：
![1601193381609](https://user-images.githubusercontent.com/29041332/94359528-6908ff80-00da-11eb-9c40-2700acddc609.jpg)

**Comment by tink2123** [comment]
benchmark数据读取是没有做shuffle的，这种情况一般和数据读取顺序有关。
SRN 训练时对数据做了shuffle，不是按顺序读取的，这部分代码没有合入。
您这边我建议试一下SimpleReader， 会自动做shuffle，训练2个epoch看一下，排除一下数据影响

**Comment by FieldRen** [comment]
好的，感谢解答！
