### ISSUE TITLE
Table Recognition - Cell Overlapping Issue

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8614]
Hello! When doing table recognition, I am getting cells that are overlapping.  Example below.

![image](https://user-images.githubusercontent.com/83645945/207474786-913e5582-c387-41b6-9102-f1177ae9f6e9.png)

The example above is using the CH_SLANET table recognition model, but this cell-overlap issue occurs with other models.

Is there a way I can prevent or minimize this without training? Maybe there is some kind of setting that can prevent overlapping cells like this? If the cells bordered each other instead of overlapping, that would be fine.

**Comment by johntoma** [comment]
@WenmuZhou Hello, can someone please take a look at this issue? Thanks.

**Comment by parthplc** [comment]
@johntoma Did you find any workaround?

**Comment by johntoma** [comment]
> parthplc

Unfortunately not. This issue can probably be fixed with more training, but I'm trying to find some other way to limit the overlapping without training the model further.

**Comment by TasneemVKhan** [comment]
@johntoma I'm trying to train PPStructure model using the SLANET.yml file and I'm using the PubTab Dataset. I'm facing errors while training the dataset. Can you please help me?
