### ISSUE TITLE
TableMaster - Table HTML results does not include all detected cells. Some detected cells are omitted.

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8615]
## Context
I am using Layout Analysis with table recognition to detect tables in pages and extract data from each cell.
This issue only seems to happen when using `TableMaster` algorithm/model. Could there be something wrong with my settings?

I have an interface set up where I can specify which model to use, which I then pass into table_engine when initializing.
I initialize the table_engine in this manner:
![image](https://user-images.githubusercontent.com/83645945/207480867-ff1d2fc3-ff32-4e17-9b9e-7ebd2d55de3e.png)

For context, the output looks similar to this:
![image](https://user-images.githubusercontent.com/83645945/207480962-c4a68437-f3f2-4f08-9aa4-4afba64d31ea.png)

## The Issue
I use both the HTML and cell_bbox results, and I have a parser function which matches each <td> in a table to it's corresponding bbox based on index. For this to work, the number of <td> elements and number of cell_bbox need to be exatly the same.

However, what seems to be happening is for some reason, the html is omitting some of the <td> elements, even though a bbox is already detected for it.  Sometimes, it's the other way around. I sometimes get more <td> elements than the number of detected bbox. This issue seems to only happen with `TableMaster`

## Example of the Issue
Here is an example of a detected table. As you can see, all the cells are highlighted
![image](https://user-images.githubusercontent.com/83645945/207479780-1edac38c-3cfe-42d0-8478-a4af09ced872.png)

But when visualizing the HTML results of this table, there are cells missing completely. In particular, the cell in the bottom-right corner with the value of "8.9" seems to be detected and has a bbox, but it does not appear in the HTML Table.

![image](https://user-images.githubusercontent.com/83645945/207479860-d61986c4-9308-44cd-8b76-2cf7a25a72d8.png)

## Another Related Issue
Another issue related to this, in the html results, the colspan seems to cap at "3" for some reason, I have never seen it higher than 3. In the case of this table, the first cell on the last row should have a colspan of "4", not "3"

## Solution?
Any idea of what I can do for a potential solution? Is there some kind of modification I can make to the table to html algorithm for this? Could there be something wrong with my settings?

Thanks for your time.

# Edit:
- Initially I wrote that this happens with multiple models, but I edited to clarify that this issue only seems to happen with TableMaster*

**Comment by johntoma** [comment]
@WenmuZhou Hello, can someone please take a look at this issue? Thanks.

**Comment by johntoma** [comment]
@tink2123 Can you please organize a response for this issue? Thanks.

**Comment by parthplc** [comment]
@johntoma any update on this?

**Comment by johntoma** [comment]
@parthplc Unfortunately not yet
