### ISSUE TITLE
模型转换前后效果相差巨大

### ISSUE THREAD

**Issue by MrTTTTTwinkel** [PaddlePaddle/PaddleOCR#862]
checkpoint模型做文本检测时，效果一般，转换为inference模型后效果提升巨大，目前测试了 ppocr 及 db两种模型，均出现了相似的现象，求解答。

**Comment by littletomatodonkey** [comment]
可以看下预测的超参数是否一致

**Comment by tink2123** [comment]
模型参数都是同一份，预测效果与缩放尺度有很大的关系，inference 预测时最大边默认为2400，预测时效果会好一点。
