### ISSUE TITLE
Runtime error when using paddleocr on cpu

### ISSUE THREAD

**Issue by sharmas1ddharth** [PaddlePaddle/PaddleOCR#8624]
Runtime error when using paddleocr on cpu, os is ubuntu 16.04

- 系统环境/System Environment：ubuntu 16.04
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.1  问题相关组件/Related components：
- 运行指令/Command Code：ocr = PaddleOCR(use_angle_cls=True, lang='en')
        result = ocr.ocr(image, cls=True)
- 完整报错/Complete Error Message：RuntimeError: (PreconditionNotMet) The third-party dynamic library (libmklml_intel.so) that Paddle depends on is not configured correctly. (error code is /home/ubuntu/customExchangeRate/venv/lib/python3.8/site-packages/paddle/fluid/../libs/libmklml_intel.so: cannot make segment writable for relocation: Cannot allocate memory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:305)

**Comment by jingsongliujing** [comment]
use paddle 2.3:    python -m pip install paddlepaddle==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
