### ISSUE TITLE
【12月部署月-直播课来啦】FastDeploy联合十大硬件公司，《产业级AI 模型部署全攻略》，12月12日～12月30日

### ISSUE THREAD

**Issue by leiqing1** [PaddlePaddle/PaddleOCR#8625]
### 问题描述 Please describe your issue

FastDeploy联合十大硬件公司，展开为期三周的部署月活动。
✅联合10大硬件公司共同打造
✅解决企业AI部署落地难题
✅覆盖云边端全场景部署方式
![12月部署月](https://user-images.githubusercontent.com/54695910/207280316-f95d56eb-0054-4ae7-848d-0056bf3332a1.jpg)

**Comment by cyy0523xc** [comment]
测试了一下，用fastdeploy部署的效果好像差了一点，不知道是否是参数的问题：https://gitee.com/paddlepaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3。另外，fastDeploy好像还没有整合表格识别之类的
