### ISSUE TITLE
ser重新训练效果不好，没有按自己的预期的那样

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#8627]
ser重新训练效果不好，没有按自己的预期的那样

![微信图片_20221215090312](https://user-images.githubusercontent.com/6648329/207748040-a1d54f17-8bd5-4625-9174-57e671479646.png)

明明是我标注好的，识别的时候给我分开的，怎么回事？

**Comment by WenmuZhou** [comment]
检测模型重新训练了吗

**Comment by gg22mm** [comment]
> 
检测模型重新训练?????????   ，什么鬼~~

**Comment by gg22mm** [comment]
> 检测模型重新训练了吗

ser没有所谓的检查模型，只有 语义实体识别+关系抽取

**Comment by WenmuZhou** [comment]
ser里面用到了ocr，你这个可能是ocr检测的时候就分开了
