### ISSUE TITLE
安装paddle错误

### ISSUE THREAD

**Issue by zhangjuncheng24** [PaddlePaddle/PaddleOCR#8633]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： wind7 python3.8.0  
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： paddle
- 运行指令/Command Code：
- 安装过命令cpu版本 pip install paddlepaddle==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
- import paddle之后报错
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/111550104/207766790-82c7b83f-e1d8-430f-8caa-a32be81246c4.png)

**Comment by WenmuZhou** [comment]
辛苦在paddle下提问

**Comment by jingsongliujing** [comment]
win7的32位系统吗？paddle好像只能用64位系统，win7从1.6后都有点问题
