### ISSUE TITLE
paddleocr 训练crnn，train.log结果怎么用visualdl展示？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8634]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle： 2.5  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
paddleocr 训练crnn，train.log结果怎么用visualdl展示？

**Comment by WenmuZhou** [comment]
你应该能注意到配置文件里有这个配置`use_visualdl `，打开就行了

**Comment by nissansz** [comment]
![image](https://user-images.githubusercontent.com/41010669/207851038-2a674e4e-913b-4c72-84c7-a17f1b50b0f5.png)
可以用了，但是好像只有第一个 标量数据菜单可以看到内容，其余都没有内容

**Comment by WenmuZhou** [comment]
目前paddleocr中visualdl只添加了标量数据，其他的可以参照visualdl文档自行添加
