### ISSUE TITLE
kie config文件里面的num_classes: &num_classes 10

### ISSUE THREAD

**Issue by eerenyuan** [PaddlePaddle/PaddleOCR#8637]
试图修改
configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml 

修改了class_list文件和train/eval两个文件

训练时出现错误expect label id <7。

我一共只使用了5个label，而配置文件num_classes=7，应该是足够用的。

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForSer
    pretrained: True
    checkpoints:
    # one of base or vi
    mode: vi
    num_classes: &num_classes 7

注意到原始样例中其实只有4个label，num_classes却是7。

于是我把这个参数进一步增加到10，代码可以运行。

有没有关于num_classes这个输入的文档？应该如何合理的设置这个参数。

**Comment by guishilike** [comment]
![image](https://user-images.githubusercontent.com/51023060/207796407-c70b69ce-b869-45eb-a0b7-ad628a5d8fa9.png)

**Comment by eerenyuan** [comment]
明白了，谢谢。
