### ISSUE TITLE
ocr转onnx

### ISSUE THREAD

**Issue by shuihsaiu** [PaddlePaddle/PaddleOCR#8638]
我使用官方提供的paddle2onnx将inference模型转成了onnx，模型转成功且能够测试，但使用netron可视化时不能显示输入输出的参数。
输出的信息为： inputs: type: float32[p2o.DynamicDimension.0,3,p2o.DynamicDimension.1,p2o.DynamicDimension.2]   outputs:
type: float32[p2o.DynamicDimension.3,1,p2o.DynamicDimension.4,p2o.DynamicDimension.5].

**Comment by Nancis1130** [comment]
请问你解决了吗？

**Comment by WenmuZhou** [comment]
这个问题在paddle2onnx下提问看看

**Comment by Francis235** [comment]
请问这个问题解决了吗？
