### ISSUE TITLE
请制作PP-Structure的PaddleServing例子吧

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleOCR#8641]
要写PP-Structure在paddle_serving_server.web_service中的Op类，感觉我这个新手做不到啊。
有没有大神做好例子，让新手复用呢

**Comment by an1018** [comment]
可以使用hubserving：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/hubserving/readme.md，包含structure模型
