### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by lele012** [PaddlePaddle/PaddleOCR#865]
the memory of my gpu is 6000M

**my code like this:**

from paddleocr import PaddleOCR, draw_ocr
from PIL import Image
import datetime
import os

os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
os.environ['FLAGS_fraction_of_gpu_memory_to_use'] = "1.0"

# 模型路径下必须含有model和params文件
ocr = PaddleOCR(use_gpu=True, gpu_mem=4000, det_model_dir='D:\\AI\\ocr\\models\\ch_ppocr_server_v1.1_det_infer', rec_model_dir='D:\\AI\\ocr\\models\\ch_ppocr_server_v1.1_rec_infer', rec_char_dict_path='D:\\AI\\ocr\\dicts\\ppocr_keys_v1.txt', cls_model_dir='D:\\AI\\ocr\\models\\ch_ppocr_mobile_v1.1_cls_infer', use_angle_cls=True)
img_path = 'D:\\AI\\ocr\\images\\1.jpg'
start = datetime.datetime.now()
result = ocr.ocr(img_path)
for line in result:
    print(line)
end = datetime.datetime.now()
print("总耗时:", (end-start).seconds)

**the error is :**

ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 121.078369MB memory on GPU 0, available memory is only 55.625000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (D:\1.7.0\paddle\paddle\fluid\memory\detail\system_allocator.cc:151)

**Comment by lele012** [comment]
我这个是显存太低了吗，我的显存是6G，没有别的程序占用。

**Comment by lele012** [comment]
如果是显存太低了话，要求最低显存是多少？

**Comment by WenmuZhou** [comment]
你的保存显示你的显存只有55m可用，能帖个nvidia-smi的输出吗

**Comment by Hupengyu** [comment]
> 你的报错显示你的显存只有55m可用，能帖个nvidia-smi的输出吗

必须要用GPU吗？我用CPU可以吗？24G的。我用24G的CPU跑一个1M的图片都爆内存错误，不知道到底是什么原因
