### ISSUE TITLE
What changed?

### ISSUE THREAD

**Issue by cmeer** [PaddlePaddle/PaddleOCR#8650]
Hello,

I installed paddleocr again and now my code does not work.
(After a few months. The first version of my code was based on 2.6.0)

For example this:

`# draw result
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='PaddleOCR/doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')`

(The rest of my code is based on this, and also does not work anymore.)
I think something has changes in the result structure. But i can not find it.

**Comment by huangjun12** [comment]
u can refer to this [code](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/paddleocr.py) for result structure changes. is there any bug log?

**Comment by cmeer** [comment]
@huangjun12 Thank you for your response. I found a solution. Before i could use this:
`ocr = PaddleOCR(use_angle_cls=True, lang='en', table=False, show_log = False)
result = ocr.ocr(img_path, cls=True)

boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]

print(txts)`

I found that the data now can be found in: result[0]

So i do:
`ocr = PaddleOCR(use_angle_cls=True, lang='en', table=False, show_log = False)
result = ocr.ocr(img_path, cls=True)

result = result[0]

boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]

print(txts)`
