### ISSUE TITLE
增值税发票SER标注问题

### ISSUE THREAD

**Issue by 77981836** [PaddlePaddle/PaddleOCR#8651]
<img width="576" alt="ocr标注" src="https://user-images.githubusercontent.com/11438078/208241088-79c740bd-b97a-4bea-9dc3-aa41fbd59e5b.png">

1.  地址、电话   和  开户行及账号两个字段 没有 value怎么标注？
2. 货物或应税劳务、服务名称 有多行 怎么标注？

**Comment by pogevip** [comment]
解决了吗？
