### ISSUE TITLE
DB++在中文场景的实现

### ISSUE THREAD

**Issue by simpleman12138** [PaddlePaddle/PaddleOCR#8652]
使用英文的预训练模型在中文场景下效果很差，DB++是否可以应用在中文场景？有中文的预训练模型吗？望回复，感谢

**Comment by huangjun12** [comment]
可以应用在中文场景；目前在ICDAR2015和TD_TR数据集上的有预训练模型，[DB++](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_det_db.md)。
中文场景可以用TD_TR的预训练模型，也可以在ctw1500数据集训练下看看。
