### ISSUE TITLE
ModuleNotFoundError: No module named 'lanms'

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8653]
已经试过
pip install lanms-neo==1.0.2还是没用

**Comment by 77981836** [comment]
试试 pip install lanms==1.0.2

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/208283400-bb940c29-a664-4712-b215-3aab12ee8a05.png)

**Comment by zyzz1974** [comment]
这是咋回事呢

**Comment by huangjun12** [comment]
pip install --upgrade pip 先升级pip试下

**Comment by TasneemVKhan** [comment]
pip install lanms-nova 

I solved the error by using this command works for me. 
If you see this [link](https://pypi.org/project/lanms/) the lanms does not contain anything, therfore it throws an error
