### ISSUE TITLE
货物标签场景识别模块训练时字典和epoch怎么设置

### ISSUE THREAD

**Issue by cccoolboy** [PaddlePaddle/PaddleOCR#8656]
场景：货物标签里基本都是英文，有极少数中文（1%）
数据集准备：text_render合成了5000张，都是英文；自己标注了真实货物标签60几张图（中文字7个左右）。
问：1.训练时字典怎么设置，可以用内置的中文字典么，还是可以内置英文字典再加一些场景中出现的几个汉字
       2.epoch设置多少比较好

**Comment by MissPenguin** [comment]
1. 这两种方案都可以
