### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8658]
关系抽取报错
![image](https://user-images.githubusercontent.com/99126288/208293936-184b9e5d-aac7-4314-87bd-9a82027cefa8.png)

**Comment by MissPenguin** [comment]
我这边没法复现，网上查了下，这种报错可能是python版本不对

**Comment by LeoRainly** [comment]
楼主你的python是3.6版本吗

**Comment by zyzz1974** [comment]
忘了，很久的事了
&nbsp;


zyzz
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] SyntaxError: future feature annotations is not defined (Issue #8658)





 
楼主你的python是3.6版本吗
