### ISSUE TITLE
`numpy.int` removed in numpy>=1.24.0

### ISSUE THREAD

**Issue by haobibo** [PaddlePaddle/PaddleOCR#8659]
`numpy.int` has been removed from since version 1.24.0.

ppocr has several reference for the removed attribute (which leads to AttributeError):
https://github.com/PaddlePaddle/PaddleOCR/blob/b28af5d865103dab84a15de549c5ac800f8727a0/ppocr/postprocess/db_postprocess.py#L188

**Comment by linhandev** [comment]
I still hit this issue with paddleocr  2.6.1.2

Stack trace says it's here
'''
python3.10/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
'''

Hopefully the patch will be released in the paddleocr package in the near future?

**Comment by LDOUBLEV** [comment]
Fixed
take .astype("int32")  place of .astype(np.int)
