### ISSUE TITLE
关于部署到生产环境的一些问题

### ISSUE THREAD

**Issue by iwctwbai** [PaddlePaddle/PaddleOCR#866]
现在想要将[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md)部署到服务器通过http等协议访问
目前是通过[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_local_server.py](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_local_server.py)来进行的 现在遇到的问题是
1）识别时没有文本框坐标数据
2）效果没有直接通过[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md)的效果好 模型都是一样的
请问这些该如何解决呢 谢谢

**Comment by iwctwbai** [comment]
请问hubserving hubserving这两种部署方式区别是什么呢？

**Comment by MissPenguin** [comment]
> 现在想要将https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md部署到服务器通过http等协议访问
> 目前是通过https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/pdserving/ocr_local_server.py来进行的 现在遇到的问题是
> 1）识别时没有文本框坐标数据
> 2）效果没有直接通过https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/whl.md的效果好 模型都是一样的
> 请问这些该如何解决呢 谢谢

pdserving目前还有点问题正在修复，建议先用hubserving哈。

hubserving原本是paddlehub的配套服务部署工具，可以很方便的将paddlehub内置的模型部署为服务，paddleocr使用了这个功能，并将模型路径等参数暴露出来方便用户自定义修改。paddle serving是面向所有paddle模型的部署工具，文档中可以看到我们提供了快速版和标准版，其中快速版和hubserving的本质是一样的，而标准版基于rpc，更稳定，更适合分布式部署。

**Comment by JiaoZiLang** [comment]
部署到服务器需要包小，然而hubserving依赖paddlepaddle（这包太大了），感觉还是pdserving合适。期待pdserving
