### ISSUE TITLE
Training KIE with new language

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#8660]
Thank for great repo.
I want to train SER with new languge, extractly portugal. I had label the custom datasets follow [tutorial](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/kie_en.md). I use text Detection model from pretrained PP-V3, OCR I trained model with portugal by ```svtr architecture ``` I had trained SER successfully.
I only config the det and rec:
![image](https://user-images.githubusercontent.com/42369268/208344542-6e81f465-f6de-49c1-8636-c667bd5f6ce2.png)

 When I inferrence, the result out ser only China langue, not portugal. My question is: "How to config and train SER with custom dataset and language?"
Thank you.

**Comment by Harry197** [comment]
I have same problem

**Comment by phamkhactu** [comment]
> I have same problem. Did you solve this problem @phamkhactu ?

@Harry197, I didn't. Have you solved it??

**Comment by piarosebelledelapaz** [comment]
hello i am still encountering the issue where i trained the RE model to a different language, but the results are still in chinese characters. how to improve it?
