### ISSUE TITLE
DBNet cpu 训练报错：Can not find input variable 'Out' for hard_sigmoid_grad OP

### ISSUE THREAD

**Issue by Ashelly1** [PaddlePaddle/PaddleOCR#8661]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
Ubuntu 18.04.5 LTS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
  master , commit id: 5204ec08db565844f5b5a05eb521af48f89a3c8e
- 运行指令/Command Code：
python3 tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained Global.use_mlu=false Global.use_gpu=false Global.epoch_num=10 Global.save_model_dir=./output_1card_cpu 2>&1 | tee log_dbnet_1card_cpu
- 完整报错/Complete Error Message：
![{e39b6038-8b90-4ee4-b5c7-c103eb7521c0}](https://user-images.githubusercontent.com/22099158/208383840-2eca389a-24da-4c28-abb2-61814e9f819c.png)

大佬们，请问下这个是什么问题？

**Comment by LDOUBLEV** [comment]
更新paddle版本到2.3以上试试
