### ISSUE TITLE
C++ 推理显存占用一直上涨，不释放，一路视频的推理达到5.8G

### ISSUE THREAD

**Issue by shengzhe8688** [PaddlePaddle/PaddleOCR#8662]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：Paddle：master 版本  PaddleOCR：v2.5 问题相关组件/Related components：PaddleOCR、 paddle_inference
- 运行指令/Command Code：C++代码。
- 完整报错/Complete Error Message：
发现程序在执行多次的Infer推理后内存不断上涨。
1、程序刚启动不做推理，只进行det、rec的加载模型、构造对象操作，内存占用为1190M。
2、当我开启一路摄像头进行infer推理时内存涨到5795M。
  config.SwitchIrOptim(true);
  config.EnableMemoryOptim(true);
这两个开与不开效果差异都不是很大，各位大佬们，请问有更好的路子没有？
![image](https://user-images.githubusercontent.com/16428236/208385786-77124253-55ed-4cb3-8ce9-89183fc0c730.png)

**Comment by shengzhe8688** [comment]
大佬给个回复 行不行？

**Comment by jingsongliujing** [comment]
推理建议看看新出的这个推理框架示例代码：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr
