### ISSUE TITLE
官方pytorch DBnet训练好的模型和paddle训练好的svtr模型怎么进行端到端的连接呢

### ISSUE THREAD

**Issue by yulm-1** [PaddlePaddle/PaddleOCR#8665]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
参考predict_system.py： https://github.com/PaddlePaddle/PaddleOCR/blob/0e1148312be91f7fd7ffcb3f57c4c63fcdd5b67f/tools/infer/predict_system.py#L79-L88
