### ISSUE TITLE
训练集在训练的时候报这个错误

### ISSUE THREAD

**Issue by XD-mu** [PaddlePaddle/PaddleOCR#8668]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c (那个配置文件)
- 完整报错/Complete Error Message：
 ppocr ERROR: When parsing line Dense text dataset/56.png  [{"transcription": "GND", "points": [[7, 66], [20, 66], [20, 103], [7, 103]], "difficult": false}, {"transcription": "D14_TX1", "points": [[26, 50], [45, 50], [45, 126], [26, 126]], "difficult": false}, {"transcription": "D14_TX1", "points": [[47, 52], [64, 52], [64, 125], [47, 125]], "difficult": false}, {"transcription": "D14_TX1", "points": [[67, 50], [84, 50], [84, 123], [67, 123]], "difficult": false}, {"transcription": "GND", "points": [[85, 63], [104, 63], [104, 105], [85, 105]], "difficult": false}, {"transcription": "GND", "points": [[145, 61], [164, 61], [164, 106], [145, 106]], "difficult": false}, {"transcription": "D14_PRE", "points": [[182, 50], [204, 50], [204, 128], [182, 128]], "difficult": false}, {"transcription": "GND", "points": [[225, 61], [242, 61], [242, 105], [225, 105]], "difficult": false}, {"transcription": "D14_DINRXP", "points": [[244, 17], [261, 17], [261, 128], [244, 128]], "difficult": false}, {"transcription": "D14_DINRXN", "points": [[264, 15], [284, 15], [284, 125], [264, 125]], "difficult": false}, {"transcription": "GND", "points": [[284, 65], [299, 65], [299, 102], [284, 102]], "difficult": false}, {"transcription": "D14_RXD0", "points": [[303, 37], [322, 37], [322, 127], [303, 127]], "difficult": false}, {"transcription": "D14_RXD1", "points": [[322, 35], [342, 35], [342, 123], [322, 123]], "difficult": false}, {"transcription": "D14_RXD2", "points": [[342, 34], [364, 34], [364, 125], [342, 125]], "difficult": false}, {"transcription": "69", "points": [[4, 131], [26, 131], [26, 155], [4, 155]], "difficult": false}, {"transcription": "68", "points": [[28, 133], [45, 133], [45, 153], [28, 153]], "difficult": false}, {"transcription": "67", "points": [[48, 130], [64, 130], [64, 158], [48, 158]], "difficult": false}, {"transcription": "66", "points": [[66, 131], [86, 131], [86, 156], [66, 156]], "difficult": false}, {"transcription": "65", "points": [[87, 131], [105, 131], [105, 156], [87, 156]], "difficult": false}, {"transcription": "64", "points": [[105, 133], [122, 133], [122, 153], [105, 153]], "difficult": false}, {"transcription": "63", "points": [[123, 133], [140, 133], [140, 154], [123, 154]], "difficult": false}, {"transcription": "62", "points": [[142, 133], [164, 133], [164, 155], [142, 155]], "difficult": false}, {"transcription": "61", "points": [[162, 133], [179, 133], [179, 156], [162, 156]], "difficult": false}, {"transcription": "60", "points": [[186, 133], [205, 133], [205, 154], [186, 154]], "difficult": false}, {"transcription": "59", "points": [[206, 132], [222, 132], [222, 152], [206, 152]], "difficult": false}, {"transcription": "58", "points": [[225, 133], [240, 133], [240, 155], [225, 155]], "difficult": false}, {"transcription": "57", "points": [[245, 135], [262, 135], [262, 153], [245, 153]], "difficult": false}, {"transcription": "56", "points": [[266, 134], [284, 134], [284, 155], [266, 155]], "difficult": false}, {"transcription": "55", "points": [[283, 134], [300, 134], [300, 155], [283, 155]], "difficult": false}, {"transcription": "54", "points": [[304, 135], [322, 135], [322, 156], [304, 156]], "difficult": false}, {"transcription": "53", "points": [[323, 135], [342, 135], [342, 154], [323, 154]], "difficult": false}, {"transcription": "52", "points": [[345, 135], [358, 135], [358, 154], [345, 154]], "difficult": false}, {"transcription": "GND", "points": [[17, 185], [38, 185], [38, 222], [17, 222]], "difficult": false}, {"transcription": "TXD2", "points": [[39, 182], [58, 182], [58, 231], [39, 231]], "difficult": false}, {"transcription": "TXD1", "points": [[59, 184], [77, 184], [77, 230], [59, 230]], "difficult": false}, {"transcription": "TXD0", "points": [[81, 182], [100, 182], [100, 234], [81, 234]], "difficult": false}, {"transcription": "GNDA", "points": [[101, 182], [119, 182], [119, 239], [101, 239]], "difficult": false}, {"transcription": "DOUTTXP", "points": [[120, 185], [140, 185], [140, 275], [120, 275]], "difficult": false}, {"transcription": "DOUTTXN", "points": [[140, 183], [158, 183], [158, 277], [140, 277]], "difficult": false}, {"transcription": "GNDA", "points": [[156, 185], [177, 185], [177, 240], [156, 240]], "difficult": false}, {"transcription": "VDDA", "points": [[176, 186], [195, 186], [195, 240], [176, 240]], "difficult": false}, {"transcription": "PRE", "points": [[198, 182], [217, 182], [217, 225], [198, 225]], "difficult": false}, {"transcription": "VDDA", "points": [[218, 183], [238, 183], [238, 239], [218, 239]], "difficult": false}, {"transcription": "GNDA", "points": [[236, 183], [254, 183], [254, 243], [236, 243]], "difficult": false}, {"transcription": "DINRXP", "points": [[257, 185], [274, 185], [274, 250], [257, 250]], "difficult": false}, {"transcription": "DINRXN", "points": [[275, 185], [295, 185], [295, 260], [275, 260]], "difficult": false}, {"transcription": "GNDA", "points": [[298, 182], [318, 182], [318, 235], [298, 235]], "difficult": false}, {"transcription": "RXD0", "points": [[314, 183], [335, 183], [335, 234], [314, 234]], "difficult": false}, {"transcription": "RXD1", "points": [[334, 184], [355, 184], [355, 233], [334, 233]], "difficult": false}, {"transcription": "RXD2", "points": [[355, 184], [375, 184], [375, 233], [355, 233]], "difficult": false}, {"transcription": "GND", "points": [[382, 208], [425, 208], [425, 229], [382, 229]], "difficult": false}, {"transcription": "VDD", "points": [[377, 229], [420, 229], [420, 249], [377, 249]], "difficult": false}, {"transcription": "RXD3", "points": [[367, 249], [422, 249], [422, 272], [367, 272]], "difficult": false}, {"transcription": "RXD4", "points": [[367, 270], [420, 270], [420, 291], [367, 291]], "difficult": false}, {"transcription": "RXD5", "points": [[368, 291], [419, 291], [419, 310], [368, 310]], "difficult": false}, {"transcription": "RXD6", "points": [[367, 313], [423, 313], [423, 330], [367, 330]], "difficult": false}, {"transcription": "GND", "points": [[367, 328], [426, 328], [426, 345], [367, 345]], "difficult": false}, {"transcription": "RXD7", "points": [[367, 346], [419, 346], [419, 367], [367, 367]], "difficult": false}, {"transcription": "RX_CLK", "points": [[352, 365], [423, 365], [423, 388], [352, 388]], "difficult": false}, {"transcription": "RXD8", "points": [[353, 388], [422, 388], [422, 409], [353, 409]], "difficult": false}, {"transcription": "RXD9", "points": [[357, 410], [423, 410], [423, 425], [357, 425]], "difficult": false}, {"transcription": "VDD", "points": [[359, 424], [421, 424], [421, 442], [359, 442]], "difficult": false}, {"transcription": "RXD10", "points": [[352, 445], [421, 445], [421, 465], [352, 465]], "difficult": false}, {"transcription": "VDD", "points": [[8, 229], [49, 229], [49, 248], [8, 248]], "difficult": false}, {"transcription": "TXD3", "points": [[8, 249], [56, 249], [56, 268], [8, 268]], "difficult": false}, {"transcription": "TXD4", "points": [[5, 270], [62, 270], [62, 287], [5, 287]], "difficult": false}, {"transcription": "TXD5", "points": [[7, 288], [60, 288], [60, 305], [7, 305]], "difficult": false}, {"transcription": "GND", "points": [[7, 307], [49, 307], [49, 327], [7, 327]], "difficult": false}, {"transcription": "TXD6", "points": [[3, 328], [58, 328], [58, 346], [3, 346]], "difficult": false}, {"transcription": "TXD7", "points": [[5, 346], [58, 346], [58, 365], [5, 365]], "difficult": false}, {"transcription": "GTX_CLK", "points": [[9, 367], [98, 367], [98, 389], [9, 389]], "difficult": false}, {"transcription": "VDD", "points": [[7, 391], [51, 391], [51, 408], [7, 408]], "difficult": false}, {"transcription": "TXD8", "points": [[7, 409], [57, 409], [57, 425], [7, 425]], "difficult": false}, {"transcription": "TXD9", "points": [[7, 426], [54, 426], [54, 444], [7, 444]], "difficult": false}, {"transcription": "TXD10", "points": [[7, 443], [71, 443], [71, 466], [7, 466]], "difficult": false}, {"transcription": "GND", "points": [[8, 470], [59, 470], [59, 486], [8, 486]], "difficult": false}, {"transcription": "TXD11", "points": [[9, 486], [72, 486], [72, 502], [9, 502]], "difficult": false}, {"transcription": "TXD12", "points": [[6, 504], [79, 504], [79, 526], [6, 526]], "difficult": false}, {"transcription": "TXD13", "points": [[4, 523], [80, 523], [80, 541], [4, 541]], "difficult": false}, {"transcription": "GND", "points": [[8, 546], [54, 546], [54, 567], [8, 567]], "difficult": false}, {"transcription": "RXD11", "points": [[360, 472], [421, 472], [421, 487], [360, 487]], "difficult": false}, {"transcription": "RXD12", "points": [[362, 491], [420, 491], [420, 506], [362, 506]], "difficult": false}, {"transcription": "RXD13", "points": [[360, 505], [421, 505], [421, 529], [360, 529]], "difficult": false}, {"transcription": "GND", "points": [[364, 526], [424, 526], [424, 545], [364, 545]], "difficult": false}, {"transcription": "TXD14", "points": [[58, 555], [80, 555], [80, 609], [58, 609]], "difficult": false}, {"transcription": "GND", "points": [[81, 568], [98, 568], [98, 609], [81, 609]], "difficult": false}, {"transcription": "TXD15", "points": [[99, 557], [118, 557], [118, 609], [99, 609]], "difficult": false}, {"transcription": "TKMSE", "points": [[121, 548], [137, 548], [137, 609], [121, 609]], "difficult": false}, {"transcription": "LOOPEN", "points": [[138, 540], [157, 540], [157, 609], [138, 609]], "difficult": false}, {"transcription": "TKLSE", "points": [[159, 554], [177, 554], [177, 609], [159, 609]], "difficult": false}, {"transcription": "VDD", "points": [[177, 570], [195, 570], [195, 609], [177, 609]], "difficult": false}, {"transcription": "ENABLK", "points": [[196, 544], [214, 544], [214, 609], [196, 609]], "difficult": false}, {"transcription": "LCKREFN", "points": [[218, 532], [236, 532], [236, 609], [218, 609]], "difficult": false}, {"transcription": "PRBSE", "points": [[239, 546], [257, 546], [257, 609], [239, 609]], "difficult": false}, {"transcription": "TESTEN", "points": [[257, 545], [278, 545], [278, 609], [257, 609]], "difficult": false}, {"transcription": "GND", "points": [[275, 568], [295, 568], [295, 609], [275, 609]], "difficult": false}, {"transcription": "RKLSE", "points": [[298, 554], [318, 554], [318, 609], [298, 609]], "difficult": false}, {"transcription": "RKMSE", "points": [[314, 547], [335, 547], [335, 609], [314, 609]], "difficult": false}, {"transcription": "RXD14", "points": [[335, 557], [356, 557], [356, 609], [335, 609]], "difficult": false}, {"transcription": "RXD15", "points": [[352, 555], [373, 555], [373, 609], [352, 609]], "difficult": false}, {"transcription": "GND", "points": [[377, 574], [396, 574], [396, 609], [377, 609]], "difficult": false}]
, error happened with msg: Traceback (most recent call last):
  File "F:\OCR_Project\PaddleOCR-release-2.6\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "F:\OCR_Project\PaddleOCR-release-2.6\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "F:\OCR_Project\PaddleOCR-release-2.6\ppocr\data\imaug\make_border_map.py", line 60, in __call__
    self.draw_border_map(text_polys[i], canvas, mask=mask)
  File "F:\OCR_Project\PaddleOCR-release-2.6\ppocr\data\imaug\make_border_map.py", line 81, in draw_border_map
    padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range

**Comment by XD-mu** [comment]
这个怎么解决呀，我觉得是训练集的问题，但是不知道怎么去调试

**Comment by andyjpaddle** [comment]
数据标注格式参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/ocr_datasets.md#11-paddleocr-%E6%96%87%E5%AD%97%E6%A3%80%E6%B5%8B%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F

另外可以打开这一行https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/train.py#L209 同时注释掉208行来测试数据标注是否正确

**Comment by XD-mu** [comment]
嗯呢我试试哈

**Comment by XD-mu** [comment]
我用的paddleocrLabel来标注的生成的标签文件

**Comment by XD-mu** [comment]
我这个Label文件应该也没标错吧

**Comment by XD-mu** [comment]
后面那个"difficult": falsew我不知道为啥会有，paddleocrLabel默认生成的

**Comment by andyjpaddle** [comment]
> Dense text dataset/22.png

图片路径尽量不要用空格，difficult不用管

**Comment by XD-mu** [comment]
还是不行（捂脸）

**Comment by OpenOneV** [comment]
> > Dense text dataset/22.png
> 
> 图片路径尽量不要用空格，difficult不用管

同问 @andyjpaddle ，我也是当一张图片对应的**标签太多**的时候好像就会报这个错误。   是一个叫draw_border_map的transform数据变换list index out of range，就是它padding.Execute(distance)是空的list。

了解了一下：

https://github.com/fonttools/pyclipper/issues/46
是pyclipper用的clipper太老了。clipper2据说能支持更大的数据范围。但是pyclipper作者没时间更新。

**Comment by Will439** [comment]
我把epoch_num设置成150甚至更小就会报这个错误，我把epoch_num设置成500就没有这个错误了。这是为什么啊？
