### ISSUE TITLE
paddleocr版本：2.6 tools/infer/predict_sr.py 该文件是用来预测什么的

### ISSUE THREAD

**Issue by happybuby** [PaddlePaddle/PaddleOCR#8669]
paddleocr版本：2.6
tools/infer/predict_sr.py 该文件是用来预测什么的，如图
![image](https://user-images.githubusercontent.com/61403673/208577599-f37a47d5-37f3-4efa-a955-dbc43fae8b6d.png)

**Comment by andyjpaddle** [comment]
文本超分模型的预测 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_sr_gestalt.md
