### ISSUE TITLE
关于中英文混合识别空格的疑问

### ISSUE THREAD

**Issue by kasyoukin** [PaddlePaddle/PaddleOCR#867]
对于英文数据集，加上空格比较容易，而对于中文，有的数据有空格，有的无空格，我们在处理数据时是否忽略这种情况？

**Comment by tink2123** [comment]
如果有错误标注的话，最好先清洗一下数据

**Comment by kasyoukin** [comment]
对于开源数据很难清理，一种方法是把中文里的空格去掉，保留英文的空格。不清楚ppocr是什么策略处理的

**Comment by littletomatodonkey** [comment]
只要有空格的话都会保留的，如果你想要去除中文中的空格的话，可以检测下标注里的信息是否包含中文，有的话就去掉所有的空格就行
