### ISSUE TITLE
PPOCRLabel crashes on Cell Re-Recognition

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8678]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：Windows 11
版本号/Version：
- Paddle：1.0.2  
- PaddleOCR：2.6.0.1 
- paddlepaddle: 2.4.1
- paddlepaddle-gpu: 2.4.1
问题相关组件/Related components：
- PPOCRLabel: 2.1.3
运行指令/Command Code：After clicking "Table Recognition", when I try to right click a cell and do "Cell Rerecognition", PPOCRLabel crashes and I get this error.
完整报错/Complete Error Message：
```Traceback (most recent call last):
  File "C:\Users\JohnT\miniconda3\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2423, in cellreRecognition
    patch = get_rotate_crop_image(img_crop, np.array(_bbox, np.float32))
  File "C:\Users\JohnT\miniconda3\lib\site-packages\PPOCRLabel\libs\utils.py", line 132, in get_rotate_crop_image
    d += -0.5 * (points[index + 1][1] + points[index][1]) * (
IndexError: invalid index to scalar variable.
```

Also, if I try to choose "Re-Recognition Rect-Box" (not Cell-Rerecognition), I get this error instead:

```  File "C:\Users\JohnT\miniconda3\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2270, in singleRerecognition
    result.insert(0, box)
AttributeError: 'tuple' object has no attribute 'insert'
```

How can I fix this?

**Comment by whjdark** [comment]
请更新到paddleocr-2.6.1.2再试试

**Comment by Mrfuhang** [comment]
解决了嘛 老哥
