### ISSUE TITLE
PPOCRLabel does not label empty cells in table. How to label empty cells for table recognition model training data?

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8679]
Hello, I'm trying to label my set of table images. I have many tables which have "empty cells", or cells with no text inside. I need to train the model so that these empty cells are detected because they are very important for my use case, despite not having any text. 

When clicking the "Table Recognition" button in PPOCRLabel, it automatically labels everything but it only draws boxes around the text. 

So I decided to label the empty cells manually, but not sure what the best format for this is. Should I just draw a box where the empty cell is supposed to be and set the recognition result to empty ('')?

In PubTab dataset, I believe the empty cells do not have a bbox in the data for some reason. And so I was wondering, how are the empty cells usually predicted? Is this predicted by the Table Recognition models, or is there some kind of algorithm that is used to determine where the empty cells might appear in the table?

Do I actually even *need* to label the empty cells, or should I leave them out? If I leave them out, will I still be able to predict the general location of the empty cells somehow?

**Comment by johntoma** [comment]
@tink2123 @WenmuZhou @andyjpaddle Hi, sorry but can some one please take a look at this issue? It's a little urgent

**Comment by TasneemVKhan** [comment]
I  did the same thing. I labeled my empty cells and works. I'm also trying to train my table images. 

Help me also out I haven't been able to generate output.

**Comment by johntoma** [comment]
> I did the same thing. I labeled my empty cells and works. I'm also trying to train my table images.
> 
> Help me also out I haven't been able to generate output.

Hi, when you labelled your empty cells, did you also reorganize the number order for the cells, or just leave it how it is?

It seems like it's necessary to reorganize the order of the cells after labelling
