### ISSUE TITLE
编译PaddleOCR C++预测demo 时CMakeFiles/ocr_system.dir/all  failed

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/PaddleOCR#868]
问题描述：
执行环境：ubuntu18.04 cuda10.0 cudnn7.5 opencv3.4.7
build.sh 配置：
OPENCV_DIR=/home/rex-han/下载/opencv/build/$/home/rex-han/下载/opencv3
LIB_DIR=/home/rex-han/下载/Paddle/build/fluid_inference_install_dir
CUDA_LIB_DIR=/usr/local/cuda/lib64
CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=ON \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \

make -j

 执行操作：sh tools/build.sh

问题点：
-- Build files have been written to: /home/rex-han/桌面/PythonProgram/Seven_Code_OCR/deploy/cpp_infer/build
Scanning dependencies of target ocr_system
make[2]: *** 没有规则可制作目标“/home/rex-han/下载/opencv/build/home/rex-han/下载/opencv3/include/opencv/cxcore.h”，由“CMakeFiles/ocr_system.dir/src/config.o” 需求。 停止。
make[2]: *** 正在等待未完成的任务....
[ 11%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
**CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed**
make: *** [all] Error 2
请问这是什么问题导致的编译失败。

**Comment by littletomatodonkey** [comment]
看着是没有找到opencv的头文件，要不你都换成英文路径试下呢？

**Comment by python-bookworm** [comment]
你好，修改为英文路径之后，报类似的问题，麻烦指导一下，谢谢。
OPENCV_DIR=/home/rex-han/opencv3
LIB_DIR=/home/rex-han/fluid_inference_install_dir
CUDA_LIB_DIR=/usr/local/cuda-10.0/lib64
CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libcudnn.so', needed by 'ocr_system'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 11%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
[ 22%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
[ 33%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
[ 44%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
[ 55%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
[ 66%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
[ 77%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
[ 88%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

期待回复，谢谢。

**Comment by empowerszc** [comment]
有可能是gcc版本过高，ubuntu18.04自带的gcc版本为gcc-7，试试看降到gcc-4.8。

**Comment by python-bookworm** [comment]
> 有可能是gcc版本过高，ubuntu18.04自带的gcc版本为gcc-7，试试看降到gcc-4.8。
你好，我的gcc和g++全部降级到4.8,出现新的问题：
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/rex-han/桌面/PythonProgram/Seven_Code_OCR/deploy/cpp_infer/CMakeFiles/CMakeOutput.log".
See also "/home/rex-han/桌面/PythonProgram/Seven_Code_OCR/deploy/cpp_infer/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

我的cmake是3.10.2 尝试过 sudo apt-get update & sudo apt-get install -y build-essential 还没发解决，期待回复，谢谢。

**Comment by WenmuZhou** [comment]
> 你好，修改为英文路径之后，报类似的问题，麻烦指导一下，谢谢。
> OPENCV_DIR=/home/rex-han/opencv3
> LIB_DIR=/home/rex-han/fluid_inference_install_dir
> CUDA_LIB_DIR=/usr/local/cuda-10.0/lib64
> CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/
> 
> make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libcudnn.so', needed by 'ocr_system'. Stop.
> make[2]: *** Waiting for unfinished jobs....
> [ 11%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
> [ 22%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
> [ 33%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
> [ 44%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
> [ 55%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
> [ 66%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
> [ 77%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
> [ 88%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
> make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> 期待回复，谢谢。

你这个像是没有找到cudnn

**Comment by python-bookworm** [comment]
> > 你好，修改为英文路径之后，报类似的问题，麻烦指导一下，谢谢。
> > OPENCV_DIR=/home/rex-han/opencv3
> > LIB_DIR=/home/rex-han/fluid_inference_install_dir
> > CUDA_LIB_DIR=/usr/local/cuda-10.0/lib64
> > CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/
> > make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libcudnn.so', needed by 'ocr_system'. Stop.
> > make[2]: *** Waiting for unfinished jobs....
> > [ 11%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.o
> > [ 22%] Building CXX object CMakeFiles/ocr_system.dir/src/config.o
> > [ 33%] Building CXX object CMakeFiles/ocr_system.dir/src/main.o
> > [ 44%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_det.o
> > [ 55%] Building CXX object CMakeFiles/ocr_system.dir/src/ocr_rec.o
> > [ 66%] Building CXX object CMakeFiles/ocr_system.dir/src/preprocess_op.o
> > [ 77%] Building CXX object CMakeFiles/ocr_system.dir/src/postprocess_op.o
> > [ 88%] Building CXX object CMakeFiles/ocr_system.dir/src/utility.o
> > CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
> > make[1]: *** [CMakeFiles/ocr_system.dir/all] Error 2
> > Makefile:83: recipe for target 'all' failed
> > make: *** [all] Error 2
> > 期待回复，谢谢。
> 
> 你这个像是没有找到cudnn

你好，我的CUDNN_LIB_DIR路径选择的是/usr/lib/x86_64-linux-gnu,在我ubuntu系统中，这个是存在的，请教你在ubuntu中编译的时候CUDNN路径是哪里？

**Comment by zhangruitianNB** [comment]
The same problem,did u solve it ?

**Comment by liyandongpy** [comment]
make[3]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libcudnn.so', needed by 'ocr_system'。 停止。
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ocr_system.dir/all' failed
make[2]: *** [CMakeFiles/ocr_system.dir/all] Error 2
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/ocr_system.dir/rule' failed
make[1]: *** [CMakeFiles/ocr_system.dir/rule] Error 2
Makefile:137: recipe for target 'ocr_system' failed
make: *** [ocr_system] Error 2



同样的问题，GPU编译会出错，CPU编译正常。这个文件是有的。
