### ISSUE TITLE
中文和日文训练，同等字符数，所需训练时间，有没有可能中文比日文 长？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8680]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win 10
- 版本号/Version：Paddle：2.5  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
中文和日文训练，同等字符数，所需训练时间，有没有可能中文比日文 长？

**Comment by tink2123** [comment]
训练时常和训练数据、训练环境，迭代轮次有关，和语种无关
