### ISSUE TITLE
applications/多模态表单识别.md示例文档没更新，示例用的配置文件用的是2.5里面的

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/PaddleOCR#8681]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command 
![企业微信截图_16715897163014](https://user-images.githubusercontent.com/45508593/208806596-63d17af7-45fa-4363-944c-8b67ffdc1458.png)
![企业微信截图_16715900111030](https://user-images.githubusercontent.com/45508593/208806916-49dea6bc-ce2f-4212-9cc7-410201a95956.png)

Code：
- 完整报错/Complete Error Message：

**Comment by leoterry-ulrica** [comment]
应该是使用kie文件夹内的内容
