### ISSUE TITLE
多國語言如何同時顯示

### ISSUE THREAD

**Issue by stphtan94117** [PaddlePaddle/PaddleOCR#8683]
想問一下
如果一張圖，有超過1種以上語言，該如何顯示

![image](https://user-images.githubusercontent.com/110151053/208821258-64ada2db-2958-420c-900a-ceebd09c3637.png)
代碼裡面，似乎只能指定單一語言，不曉得兩種語言以上，該如何顯示
謝謝

(例如這張圖，有日文跟法文，要同時顯示該兩種語言)

**Comment by tink2123** [comment]
抱歉暂时不支持同时显示多种语言，在下个版本会考虑加入这个功能。感谢使用。

**Comment by johntoma** [comment]
@stphtan94117 Potentially what you can do is just run the OCR twice for both languages, and then merge the results. You will need to know exactly which languages appear in the image beforehand though.

**Comment by stphtan94117** [comment]
> 

我可以事先知道兩種語言，但要如何合併merge 結果，可以指導一下嗎

**Comment by johntoma** [comment]
@stphtan94117 I just mean you can probably create some kind of data structure like a dict and just add the results from both languages in it
