### ISSUE TITLE
Convert Customized SVTR to ONNX

### ISSUE THREAD

**Issue by huylgia** [PaddlePaddle/PaddleOCR#8684]
- Python 3.8 (Google Colaboratory)
- PaddleOCR 2.6, paddlepaddle 2.3.0, paddle2onnx 0.9.7,  onnx 1.10.2, onnxruntime 1.9.0
- Exception: **Error happened when mapping node ['pool2d_5'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['reshape2_29.tmp_0']} and outputs: {'Out': ['pool2d_5.tmp_0']}, specific error: Cannot convert adaptive pool with input_size: (-1, 256, 2, 25), output_size: (-1, 256, 1, 18)**

I have a question about customize SVTR that I changed out_char_num from 25 to 18 for training and trained successfully but I meet an error when convert it to onnx format. The error as below figure:
![Screenshot from 2022-12-21 13-44-16](https://user-images.githubusercontent.com/88916218/208839022-ad32b268-3fd4-46e1-b176-5fb94ee76da8.png)

**Comment by Topdu** [comment]
`out_char_num` is appropriately set to w//4 or w//8.
