### ISSUE TITLE
文本超分辨模型推理转换失败

### ISSUE THREAD

**Issue by TongHengcheng** [PaddlePaddle/PaddleOCR#8685]
开发者好，我按照教程对文本超分模型做推理转换时，出现如下报错：
![image](https://user-images.githubusercontent.com/35362026/208843402-d54095d6-fb97-465d-9a41-39ff5f7cadb9.png)
我到提示出发现residual的输出shape为(-1, 64, 16, 64)，导致了后面的reshape操作报错。并且我在export_model.py的代码中超分的处理如下：
![image](https://user-images.githubusercontent.com/35362026/208843897-8ac01e88-439a-4ade-a2d0-12583a577881.png)
我尝试在config中直接修改，报同样的错误，麻烦一下我该如何修改

**Comment by zhongJY1998** [comment]
同问
