### ISSUE TITLE
训练图里的字数要尽可能多，还是尽可能少？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8687]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.5  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练图里的字数要尽可能多，还是尽可能少？

**Comment by tink2123** [comment]
应该尽量贴近实际使用场景

**Comment by nissansz** [comment]
实际使用场景就是字幕，每一句话的长度不一，训练图也是随机长度，之前都比较短，效果好像不太会，现在改成长一点试试

**Comment by nissansz** [comment]
4000多中文字符，500万张图，训练大概要多久才能达到较好的准确率？最高能达到多少准确率？
训练图的识别好像都正确，但是实际图，准确率很低。是什么原因？
以下是训练图识别效果
![image](https://user-images.githubusercontent.com/41010669/209084928-7fb43fc8-3726-444d-b098-a7ab794b2d2c.png)

以下是实际图识别效果，日文的效果，明显好于中文。
![image](https://user-images.githubusercontent.com/41010669/209085694-74dc7724-0837-45dd-aa3e-f767ff41fe85.png)
