### ISSUE TITLE
模型推理生成的图片与正确图不一致

### ISSUE THREAD

**Issue by sllf77** [PaddlePaddle/PaddleOCR#869]
为什么我在电脑上配置好环境后经过给定模型推理预测后生成的图片跟百度平台上生成的不一样，图片右边的文字识别有矩形框框着，并且文本后面没有显示概率。
![1](https://user-images.githubusercontent.com/68181921/94365188-5d7cff00-0101-11eb-96f9-74bc3c689d26.jpg)

**Comment by tink2123** [comment]
这是另一种可视化方法，如果想看到概率值的话可以修改这里：
https://github.com/PaddlePaddle/PaddleOCR/blob/2b16323080bbf503828b96f1ef531dc1074a1272/tools/infer/predict_system.py#L163

draw_img = draw_ocr
