### ISSUE TITLE
ppocrlabel怎么修改自己的模型进行标注呀

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#8692]
旧版本ppocrlabel.py的有个dir参数可以直接修改，新版本好像都直接下载PP-OCR-v3版本呢？修改了defalse也没用呀，文档好像也没有详尽一点的解释呢。

**Comment by lilianjie111111** [comment]
我是要修改成基于rec_chinese_common_v2.0进行微调的模型，但是修改完相关路径在自动标注的时候他就卡在那边了，也不会自动标注
![image](https://user-images.githubusercontent.com/102579571/209091802-083e0c1d-5968-40c4-945f-1121d155c2fd.png)
![image](https://user-images.githubusercontent.com/102579571/209091925-888d3ec4-79f2-4a04-96a0-90a326392f55.png)
希望得到解答谢谢。

**Comment by WenmuZhou** [comment]
可以在这里传入你的模型地址https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/PPOCRLabel/PPOCRLabel.py#L97 具体命令为--rec_model_dir=path/to/inference_model
