### ISSUE TITLE
the model is different size from readme and code

### ISSUE THREAD

**Issue by alicera** [PaddlePaddle/PaddleOCR#8695]
the model is different size
where is the new?

Here ch_PP-OCRv3_det	 size is 3.8M  for infer
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md#11-%E4%B8%AD%E6%96%87%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B

But 
I download it with code
the size is 4.0M
```
    ocr = PaddleOCR(use_angle_cls=False, lang='ch', rec_model_dir='./rec_model/') # need to run only once to download and load model into memory
```

**Comment by WenmuZhou** [comment]
Both sides are up-to-date, and the size calculated when downloading may be different from the one calculated at that time

**Comment by DhruvAwasthi** [comment]
@alicera I cross-checked the model size of `ch_PP-OCRv3_det` downloaded from the link. It is 3.8M only.

However, in the code that you are using, you are specifying the `rec_model_dir` parameter. This parameter is used to specify the location of the recognition model, and if not found then it downloads the recognition model in the specified directory.
So this code is actually downloading the recognition model `ch_PP-OCRv3_rec_infer` in `./rec_model/` directory.

But I think you are asking about the detection model `ch_PP-OCRv3_det`. 
In the code that you've used, you've not specified the `det_model_dir` parameter. In this case, it automatically downloads the detection model in the default directory. In case you want to download it in some other directory and actually want to check the size, you can specify the `det_model_dir` parameter like:

`ocr = PaddleOCR(use_angle_cls=False, lang='ch', rec_model_dir='./rec_model/', det_model_dir='./det_model/')  # need to run only once to download and load model into memory`

This will download the detection model `ch_PP-OCRv3_det` in directory `./det_model/` and from there you can check the size of downloaded model which will be `3.8M` only.

Hope this resolves this issue.

Please feel free to ask anything else.
