### ISSUE TITLE
vi-LayoutXlm的预测困惑

### ISSUE THREAD

**Issue by simpleman12138** [PaddlePaddle/PaddleOCR#8696]
vi-LayoutXlm预测与det任务的box不一致，vi-LayoutXlm下游任务会使得文本框粘连，请问这是什么原因？
例如：
![image](https://user-images.githubusercontent.com/61568958/209101298-ff1e9416-aa58-4754-9aab-60f3deb04667.png)
和单独使用检测任务
![image](https://user-images.githubusercontent.com/61568958/209101440-668b99da-2e83-4cc4-8bcc-fafaef7bb200.png)
之间不一致。
理想预期效果：
![image](https://user-images.githubusercontent.com/61568958/209101723-e9120040-41dc-4069-87bd-c51b15ab60fa.png)
![image](https://user-images.githubusercontent.com/61568958/209101772-9e0bf508-2d68-4671-ae38-d545591cb3d8.png)

**Comment by WenmuZhou** [comment]
可以debug到这里看看结果是不是一样https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppocr/data/imaug/label_ops.py#L1148，vqa中，图片是rgb通道的，但是在ocr任务中是bgr的

**Comment by simpleman12138** [comment]
若结果不一致，要怎么修改？cvtColor?

**Comment by WenmuZhou** [comment]
输入到ocr之前转换成brg就行

**Comment by simpleman12138** [comment]
经过检查不是这个bgr问题，部分图片在关键信息提取任务中存在个别文本行粘念，还有其他地方可以排查吗？

**Comment by WenmuZhou** [comment]
其他的应该没了
