### ISSUE TITLE
2.6.0 -> 2.6.1 has a breaking change

### ISSUE THREAD

**Issue by martinkozle** [PaddlePaddle/PaddleOCR#8698]
Hello, 

I noticed that the behavior of the `ocr` function has changed in a recent micro version update, from 2.6.0 to 2.6.1, with it now accepting a pdf path or a list of images and returning a list of results instead of a single result. According to semantic versioning, changes like this are considered breaking changes and should be accompanied by a bump in the major version number. However, this change was made in a micro version update, which is not in line with semantic versioning practices.

I understand that updates like this are sometimes necessary, but I think it would have been helpful to include deprecation warnings so that users could prepare for this change in advance. This is especially important in minor or micro version updates, as users typically expect them to be backwards-compatible. As a result, this change has caused me some inconvenience and wasted time having to debug why the function was suddenly returning a different result in the new update.

As an alternative, it might have been helpful to implement this change as a separate method, such as `ocr_pdf` or `ocr_images`, rather than changing the behavior of the existing `ocr` function. This would allow users to choose which version of the function they want to use, and would make it easier for users to migrate to the new behavior if they wish to do so.

I've also had some other issues with the library, such as problems with logging and warnings. These have been frustrating to deal with, and have made it difficult for me to trust the library. 

Overall, I'm disappointed that these issues exist, as the machine learning models are very good. Going forward, I will be using a fixed version of paddleocr to avoid any future issues with your updates.

**Comment by cmeer** [comment]
I came across the same issue where my code suddenly did not work anymore. After following the install in the docs.

For people having issues, i am now using:
ocr = PaddleOCR(use_angle_cls=True, lang='en', table=False, show_log = False)
result = ocr.ocr(img_path, cls=True)
result = result[0]

Instead of just:
ocr = PaddleOCR(use_angle_cls=True, lang='en', table=False, show_log = False)
result = ocr.ocr(img_path, cls=True)

My existing code works again.

**Comment by WenmuZhou** [comment]
Thank you for your reminder, we will pay attention to avoid these situations in the future
