### ISSUE TITLE
模型转换成ONNX后，运行不正常

### ISSUE THREAD

**Issue by alanzheng800** [PaddlePaddle/PaddleOCR#8699]
PS E:\work\yiOcrSoft\PaddleOCR> python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=E:\tmp\model\onnx_out\det\model.onnx  --rec_model_dir=E:\tmp\model\onnx_out\rec\model.onnx --use_angle_cls=False  --image_dir=E:\dataset\66\Image_20221123161938790.bmp --rec_char_dict_path="E:\\study\\PaddleOCR\\ppocr\\utils\\ppocr_keys_v1.txt"
<class 'str'> p2o.DynamicDimension.2
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 140, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "E:\work\yiOcrSoft\PaddleOCR\tools\infer\predict_det.py", line 147, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by alanzheng800** [comment]
C:\Users\Administrator>paddle2onnx --model_dir E:\tmp\model\det_db_inference --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file E:\tmp\model\onnx_out\det\model.onnx --opset_version 11 --input_shape_dict="{'x':[-1,3,-1,-1]}"  --enable_onnx_checker True
[1;31;40m2022-12-22 19:45:48 [WARNING] [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle [0m
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: E:\tmp\model\det_db_inference\inference.pdmodel
[Paddle2ONNX] Paramters file path: E:\tmp\model\det_db_inference\inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2022-12-22 19:45:49 [INFO]      ===============Make PaddlePaddle Better!================
2022-12-22 19:45:49 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s
使用的是这个转换命令

**Comment by Nancis1130** [comment]
请问你解决了吗？

**Comment by alanzheng800** [comment]
研发说改源码，在出错的地方强制str转int



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月28日(周三) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 模型转换成ONNX后，运行不正常 (Issue #8699)




 
请问你解决了吗？

**Comment by Nancis1130** [comment]
谢谢回复，但这里的img_h, img_w中的内容是”p2o.DynamicDimension“，无法转int

**Comment by alanzheng800** [comment]
先固定下试试，我还没试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月28日(周三) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 模型转换成ONNX后，运行不正常 (Issue #8699)




 
谢谢回复，但这里的img_h, img_w中的内容是”p2o.DynamicDimension“，无法转int

**Comment by hreyulog** [comment]
请问解决了吗

**Comment by Nancis1130** [comment]
暂时还没有，我的问题是onnx模型推理结果误差过大，怀疑是否这里的输入尺寸有问题，但昨天验证出是转推理模型产生的误差。
所以暂时还没解决转onnx后输入尺寸的问题。
















在 2022-12-30 16:02:06，"hreyulog" ***@***.***> 写道：

请问解决了吗

**Comment by hreyulog** [comment]
请问这是怎么回事？
我使用cnocr的时候 创建这个类报错
ocr_ = CnOcr()
res = ocr_.ocr(image_path)


Traceback (most recent call last):
  File "/mnt/filesv6/sead/img_ocr/src/mulcnocr.py", line 45, in <module>
    text = ocrr(input_path + '/' + file_path)
  File "/mnt/filesv6/sead/img_ocr/src/mulcnocr.py", line 15, in ocrr
    ocr_ = CnOcr()
  File "/home/heyulong/.local/lib/python3.8/site-packages/cnocr/cn_ocr.py", line 169, in __init__
    self.det_model = CnStd(
  File "/home/heyulong/.local/lib/python3.8/site-packages/cnstd/cn_std.py", line 98, in __init__
    self.det_model = det_cls(
  File "/home/heyulong/.local/lib/python3.8/site-packages/cnstd/ppocr/pp_detector.py", line 108, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by Nancis1130** [comment]
这个问题我也还没解决，目前来看是转换代码或者源码逻辑问题，转出来的input 0, 2, 3维是“p2o.DynamicDimension”

**Comment by thsno02** [comment]
有一个 workaround，把源码里的 img_h, img_w 改成模型所需要的 size 就行了，比如模型训练的时候使用的是 `640*640`，直接赋值给 img_h 和 img_w 就行了。

**Comment by MagicCodess** [comment]
还没有解决吗

**Comment by alanzheng800** [comment]
openvino直接支持飞浆模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月2日(周四) 中午12:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 模型转换成ONNX后，运行不正常 (Issue #8699)




 
还没有解决吗

**Comment by MagicCodess** [comment]
还没有解决吗+1

**Comment by jian-kuang** [comment]
还没解决吗

**Comment by tyler-chang** [comment]
还没有解决吗？+1

**Comment by BB-fat** [comment]
我将这两点代码注释掉就可以正常用了。
predict_det.py line144
```
        # if self.use_onnx:
        #     img_h, img_w = self.input_tensor.shape[2:]
        #     if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
        #         pre_process_list[0] = {
        #             'DetResizeForTest': {
        #                 'image_shape': [img_h, img_w]
        #             }
        #         }
```

predict_rec.py line174
```
        # if self.use_onnx:
        #     w = self.input_tensor.shape[3:][0]
        #     if w is not None and w > 0:
        #         imgW = w
```

**Comment by shantzhou** [comment]
还没有解决吗

**Comment by luciferwww** [comment]
我这边之前尝试对固定参数为768,448，结果对竖屏图片处理没问题，横屏就需要把宽高反过来才行不然报错。
其实我觉得实在不行注释掉PPDetector.__init__方法中几行算了。
`        if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
            pre_process_list[0] = {'DetResizeForTest': {'image_shape': [img_h, img_w]}}
`
