### ISSUE TITLE
使用ch_ppocr_server_v1.1_rec_infer推理模型，设置--use_space_char=True，但是空格仍然没有识别出来，

### ISSUE THREAD

**Issue by wangleiai** [PaddlePaddle/PaddleOCR#870]
您好，我使用使用ch_ppocr_server_v1.1_rec_infer推理模型，设置--use_space_char=True，但是空格仍然没有识别出来，会是哪里的设置有问题呢？

**Comment by tink2123** [comment]
可以重新下载最新的模型测试一下效果～ https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_infer.tar

**Comment by wangleiai** [comment]
> 可以重新下载最新的模型测试一下效果～ https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_infer.tar

还是没有识别出来....

**Comment by tink2123** [comment]
方便发一下你的测试图片吗？

**Comment by wangleiai** [comment]
![26](https://user-images.githubusercontent.com/26521448/94392224-3a4a6200-018a-11eb-8ce6-3806830eed26.jpeg)
上面是原图,下面是我测试的结果,其中我使用的文本检测模型是经过增量训练.

![26](https://user-images.githubusercontent.com/26521448/94392258-61a12f00-018a-11eb-91fd-5f0ffa1b4c10.jpeg)

**Comment by tink2123** [comment]
看你的图片，检测到的文本框并不包含空格啊

**Comment by wangleiai** [comment]
您看文本框 23,25,35,47等,这些明显是序号(空格)名称,但是识别的时候连在了一起,是不是他们离的太近了,所以导致模型没有识别出来.

**Comment by oyaji** [comment]
我们也遇到相同的问题，就是use_space_char不起作用；而且识别结果中过滤掉了本该有的空格；

**Comment by oyaji** [comment]
我们的测试图片如下
![image](https://user-images.githubusercontent.com/1419388/94516549-a5626a00-0258-11eb-952e-761133247342.png)
![image](https://user-images.githubusercontent.com/1419388/94516607-c034de80-0258-11eb-8372-b3e335d44c86.png)

**Comment by littletomatodonkey** [comment]
> 我们的测试图片如下
> 
> ![image](https://user-images.githubusercontent.com/1419388/94516549-a5626a00-0258-11eb-952e-761133247342.png)
> 
> ![image](https://user-images.githubusercontent.com/1419388/94516607-c034de80-0258-11eb-8372-b3e335d44c86.png)
> 
> 

可以试下最新的识别模型，也可以把这个图像分辨率调的稍微再大一些，之前检测的最长边为960，可以试下1280

**Comment by PriceZhang** [comment]
你好，请问server的推理模型怎么直接用？我这里显示没有model和params

**Comment by wangleiai** [comment]
> 你好，请问server的推理模型怎么直接用？我这里显示没有model和params

 需要把模型下载，然后放到相应的位置

**Comment by yizhipipixia** [comment]
> > 你好，请问服务器的推理模型怎么直接用？我这里显示没有model和params
> 
> 需要把模型下载，然后放到相应的位置

请问是放到那个位置呢,我看官方文档没有发现,就很纠结

**Comment by mlick** [comment]
没解决就要自动关闭了？
