### ISSUE TITLE
模型蒸馏时不使用预训练的话是不是需要把官方预训练的数据集也放进去呢？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#8703]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
如果数据量足够的话，可以先用自己的数据训练看看

**Comment by lilianjie111111** [comment]
> 如果数据量足够的话，可以先用自己的数据训练看看

这边使用的 cml，没有使用预训练模型，前跑到20轮了验证精度还是0是正常的吗？

**Comment by an1018** [comment]
现在还是0吗
