### ISSUE TITLE
中文训练图不知道怎么改善了，感觉已经非常接近了。但是实际图识别效果好像不行。

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8704]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练图识别结果：
乐么义乔乒乍乖乓乌 亀书习乜乗乡亍乸 乚买 4SoOQ

实图识别结果：
榎本J汨和戟告 了白 吃完弌乒炖卤义后
榎本さん 告白しといて 肉じゃが食べたら

![image](https://user-images.githubusercontent.com/41010669/209285951-6727cb34-3c9a-47d8-a48d-d8901dabc599.png)

**Comment by an1018** [comment]
实图检测效果发出来看一下吧

**Comment by nissansz** [comment]
上面截图的下半部分2行就是实图

**Comment by an1018** [comment]
实图2行，执行检测后的效果是什么样的呢

**Comment by nissansz** [comment]
实图识别结果：
榎本J汨和戟告 了白 吃完弌乒炖卤义后
榎本さん 告白しといて 肉じゃが食べたら

**Comment by an1018** [comment]
检测效果~
