### ISSUE TITLE
How to use PaddleGPU with CUDA version 11.6 on Linux 

### ISSUE THREAD

**Issue by Eunchan24** [PaddlePaddle/PaddleOCR#8705]
![Screenshot from 2022-12-23 18-22-32](https://user-images.githubusercontent.com/71329051/209309262-319693c0-8540-4623-839f-5f4f74a993a1.png)

I have a Linux machine with CUD version 11.6 and currently Paddle GPU does not support this CUDA version.
Is the process of making PaddleGPU support CUDA v11.6 is already under development? If yes then by when can we expect it to be available?
And also is there any workaround to make PaddleGPU work with CUDA v11.6 using some other tools?
Suggestions are welcomed!

**Comment by an1018** [comment]
CUDA11.6 is supported already, you can refer to [this document ](https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html) and install paddlepaddle~

**Comment by Eunchan24** [comment]
> 
Oh, I checked.
Thank you very much.!
