### ISSUE TITLE
Error when run SAST Model

### ISSUE THREAD

**Issue by trthminh** [PaddlePaddle/PaddleOCR#8707]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

when I run model sast model for text detection, I have a log like this
![image](https://user-images.githubusercontent.com/76390108/209431852-3ed3dbf8-17c8-471f-a2c5-ce693134c1ca.png)
 can you help me to fix this bug. Thanks so much

**Comment by huangjun12** [comment]
this error comes from [here](https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/ppocr/data/imaug/sast_process.py#L565), may be two line is parallel.
