### ISSUE TITLE
PPOCRLabelv2      ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22’ not found

### ISSUE THREAD

**Issue by alicera** [PaddlePaddle/PaddleOCR#8708]
https://blog.csdn.net/qq_40157728/article/details/107883449
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md

**Comment by alicera** [comment]
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/ray/anaconda3/lib/python3.9/site-packages/paddle/fluid/libpaddle.so)

**Comment by alicera** [comment]
from PyQt5.QtCore import QSize, Qt, QPoint, QByteArray, QTimer, QFileInfo, QPointF, QProcess
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.8/dist-packages/PyQt5-5.15.7-py3.8-linux-x86_64.egg/PyQt5/QtCore.abi3.so)

**Comment by Evezerest** [comment]
环境问题，可以重新安装pyqt

**Comment by bolongliu** [comment]
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
