### ISSUE TITLE
请问paddleocr支持手写体汉字识别以及汉字位置的定位吗 

### ISSUE THREAD

**Issue by liuyu2013** [PaddlePaddle/PaddleOCR#8711]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
可以先尝试用PP-OCRv3的模型；
由于缺少手写汉字的数据集，目前没有专门针对手写汉字识别的模型。

**Comment by LDOUBLEV** [comment]
如果你有数据集可以共享，我们可以在后续模型升级中支持手写字符识别

**Comment by super-tian** [comment]
@LDOUBLEV 可以基于开源中文数据集的训练一个，期待，我自己训练的精度一直上不去，期待看看官方的策略

**Comment by WilliamQf-AI** [comment]
大礼包里面有一个手写识别模型，要导出paddle inference模型，没有yml文件怎么办？哪里有？
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40328063/7d37fef4-e3c1-4a96-88d6-3110cd6ef302)
