### ISSUE TITLE
DB++模型在python端与C++端检测结果相差很大

### ISSUE THREAD

**Issue by Camphora7** [PaddlePaddle/PaddleOCR#8713]
对DB++模型进行训练，该模型在python端效果很好，推理后的inference模型用predict_det.py进行验证，也几乎没有精度损失，然而在C++端调用inference模型验证，却发现模型几乎废掉，绝大多数图片都不能检测到文字区域，导出resize图片后发现与python端导出的resize图片相差无几，请问还有什么可以排查的原因呢？

python参数：
Global:
  debug: false
  use_gpu: true
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [False, True, True, True]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
  det_box_type: 'quad' # 'quad' or 'poly'
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:                                            
    transforms:
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 320
        - 320
Eval:
  dataset:
    - DetResizeForTest:
        image_shape:
        - 320
        - 320
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0

cpp参数：
- --det_db_score_mode=fast
- --det_db_unclip_ratio=1.6
- --det_db_box_thresh=0.6
- --limit_side_len=320
- --det_db_thresh=0.3

python端识别效果：
![image](https://user-images.githubusercontent.com/108849683/209534773-b6c083c2-ba3b-45d6-8f8d-dfd4b9de7df4.png)

cpp端识别效果：
![image](https://user-images.githubusercontent.com/108849683/209534799-9a5e0527-91dc-42a5-945c-97e348fd2b4f.png)

**Comment by Camphora7** [comment]
[testdetcpp.zip](https://github.com/PaddlePaddle/PaddleOCR/files/10305384/testdetcpp.zip)
测试图片

**Comment by Camphora7** [comment]
参数已经对齐，预处理的resize也是一样的，CPP这边是直接没有输出坐标信息，不知道问题出在哪里了
![image](https://user-images.githubusercontent.com/108849683/209645787-1763eb67-7242-4884-b1a8-e78140af5c15.png)

**Comment by Camphora7** [comment]
改用默认模型finetune，推理后c++调用，是正常的，问题出在db++模型的c++部署这里

**Comment by LDOUBLEV** [comment]
C++推理的时候有修改输入大小吗？我看你评估的时候输入是320

Eval:
dataset:
- DetResizeForTest:
image_shape:
- 320
- 320
- NormalizeImage:
scale: 1./255.
mean:
- 0.48109378172549
- 0.45752457890196
- 0.40787054090196
std:
- 1.0
- 1.0
- 1.0

**Comment by Camphora7** [comment]
> 

c++推理时设置了limit_side_len=320，请问还有哪里需要设置的吗？

**Comment by Camphora7** [comment]
> C++推理的时候有修改输入大小吗？我看你评估的时候输入是320
> 
> Eval: dataset:
> 
> * DetResizeForTest:
>   image_shape:
> * 320
> * 320
> * NormalizeImage:
>   scale: 1./255.
>   mean:
> * 0.48109378172549
> * 0.45752457890196
> * 0.40787054090196
>   std:
> * 1.0
> * 1.0
> * 1.0

c++推理时设置了limit_side_len=320，请问还有哪里需要设置的吗？

**Comment by LDOUBLEV** [comment]
> c++推理时设置了limit_side_len=320，请问还有哪里需要设置的吗？

python inference model推理的时候，也是设置的limit_side_len=320吗？



试试这里改为:
`  
  cv::resize(img, resize_img, cv::Size(320, 320));
  ratio_h = float(320) / float(h);
  ratio_w = float(320) / float(w);
`
和你评估的时候的shape一致；
https://github.com/PaddlePaddle/PaddleOCR/blob/3560ff3a78bd114a529b202b0e98e92a57804473/deploy/cpp_infer/src/preprocess_op.cpp#L88`

**Comment by Camphora7** [comment]
> > c++推理时设置了limit_side_len=320，请问还有哪里需要设置的吗？
> 
> python inference model推理的时候，也是设置的limit_side_len=320吗？
> 
> 试试这里改为: ` cv::resize(img, resize_img, cv::Size(320, 320)); ratio_h = float(320) / float(h); ratio_w = float(320) / float(w);` 和你评估的时候的shape一致； [https://github.com/PaddlePaddle/PaddleOCR/blob/3560ff3a78bd114a529b202b0e98e92a57804473/deploy/cpp_infer/src/preprocess_op.cpp#L88`](https://github.com/PaddlePaddle/PaddleOCR/blob/3560ff3a78bd114a529b202b0e98e92a57804473/deploy/cpp_infer/src/preprocess_op.cpp#L88%60)

python推理时也设置了limit_side_len=320

按此修改了c++的resize代码，情况还是没有变化
