### ISSUE TITLE
同样的图片分别在linux和在自己打的docker镜像中使用paddleocr，识别出的内容不一致

### ISSUE THREAD

**Issue by wxy521131418** [PaddlePaddle/PaddleOCR#872]
paddle的版本都是1.8.4
docker中启动
from paddleocr import PaddleOCR
ocr = PaddleOCR()
ocr.ocr('/ocr/src/images/1601258559384295.png')
dt_boxes num : 5, elapse : 0.14560937881469727
rec_res num  : 5, elapse : 0.08106851577758789
[[[[76.0, 0.0], [108.0, 0.0], [108.0, 33.0], [76.0, 33.0]], ['州', 0.9993755]], [[[3.0, 37.0], [35.0, 37.0], [35.0, 57.0], [3.0, 57.0]], ['序号', 0.9334501]], [[[328.0, 37.0], [360.0, 37.0], [360.0, 48.0], [328.0, 48.0]], ['NGGA', 0.7117288]], [[[3.0, 47.0], [49.0, 55.0], [47.0, 74.0], [1.0, 66.0]], ['BdNo.', 0.864548]], [[[74.0, 48.0], [108.0, 48.0], [108.0, 70.0], [74.0, 70.0]], ['090', 0.9699852]]]

linux启动
from paddleocr import PaddleOCR
ocr = PaddleOCR()
ocr.ocr('/ocr/src/images/1601258559384295.png')
2020-09-28 10:19:13,678-ERROR: error in loading image:/ocr/src/images/1601258559384295.png
>>> ocr.ocr('/home/wuxinyu/1601258559384295.png')
dt_boxes num : 12, elapse : 0.11981868743896484
rec_res num  : 12, elapse : 0.3419804573059082
[[[[5.0, 1.0], [38.0, 6.0], [36.0, 23.0], [3.0, 17.0]], ['Dest', 0.8778225]], [[[78.0, 2.0], [106.0, 2.0], [106.0, 31.0], [78.0, 31.0]], ['温州', 0.58904135]], [[[180.9.0, 25.0]], ['GUT C&EISIINUTES MUOE SDULEL HLIG', 0.6065657]], [[[319.0, 5.0], [372.0, 8.0], [371.0, 23.0], [318.0, 20.0]], ['五', 0.30819544]], [[[392.0, 10.0], [449['重要理米：', 0.38662344]], [[[179.0, 22.0], [369.0, 35.0], [369.0, 50.0], [179.0, 37.0]], ['NOTE THE ALTERATUNOE IOLR NOAROING CATE', 0.7881626]], [[[2.0, 33.0], [3中', 0.2623862]], [[[191.0, 41.0], [240.0, 45.0], [239.0, 64.0], [190.0, 60.0]], ['ETKT', 0.938805]], [[[389.0, 33.0], [511.0, 43.0], [510.0, 62.0], [388.0, 52.0]], ['[74.0, 47.0], [109.0, 51.0], [107.0, 70.0], [73.0, 67.0]], ['090', 0.967787]], [[[4.0, 48.0], [46.0, 55.0], [44.0, 72.0], [2.0, 66.0]], ['Ba No', 0.8362568]], [[[243.02.0, 65.0]], ['4792184811050/1', 0.97980195]]]

为啥呢?

**Comment by tink2123** [comment]
> ocr.ocr('/ocr/src/images/1601258559384295.png')
> 2020-09-28 10:19:13,678-ERROR: error in loading image:/ocr/src/images/1601258559384295.png

两次预测是同一张图片吗？

**Comment by wxy521131418** [comment]
> > ocr.ocr('/ocr/src/images/1601258559384295.png')
> > 2020-09-28 10:19:13,678-ERROR: error in loading image:/ocr/src/images/1601258559384295.png
> 
> 两次预测是同一张图片吗？

是同一个图片
linux识别的图片是我从docker container中复制出来的

**Comment by WenmuZhou** [comment]
1. linux下还是docker里的是对的
2. 使用的模型是否一致，可以把~/.paddleocr目录删除之后重新跑

**Comment by wxy521131418** [comment]
> 1. linux下还是docker里的是对的
> 2. 使用的模型是否一致，可以把~/.paddleocr目录删除之后重新跑

1.linux下是对的
2.估计就是版本的问题，我用3个图片去提取里面的数字，linux下都正确，打的docker镜像中有1个识别错误，paddle的版本都是1.8.4，我paddleocr在linux和docker镜像中都是pip install paddleocr安装的

问题：
1.paddleocr可以指定版本安装么？
2.不同版本的paddleocr模型差别会很大？

**Comment by WenmuZhou** [comment]
把下载的模型删掉重新跑一下

**Comment by wxy521131418** [comment]
问题解决了，由于我之间把图片裁剪之后保存，
在linux下和docker下执行的结果不同，
后来我把图片不裁剪放入linux和docker中运行，结果一致

**Comment by WenmuZhou** [comment]
好的
