### ISSUE TITLE
No module named 'numpy.typing' with python3.6

### ISSUE THREAD

**Issue by jiangh0** [PaddlePaddle/PaddleOCR#8724]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python3.6
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：No module named 'numpy.typing'

运行正常后将代码上传到服务器，由于服务器python为3.6版本的，可支持的numpy只能到1.19，import paddleocr的时候会出现 【No module named 'numpy.typing'】这个报错，发现是由于numpy.typing是numpy1.20之后才更新的，请问这什么解决方法嘛？
`
        self.ocr = PaddleOCR(det_model_dir=os.path.join(BASE_DIR, 'ch_PP-OCRv3_det_infer'), rec_model_dir=os.path.join(BASE_DIR, 'ch_PP-OCRv3_rec_infer'), cls_model_dir=os.path.join(BASE_DIR, 'ch_ppocr_mobile_v2.0_cls_infer'), use_angle_cls=True, use_gpu=True)
        `

**Comment by andyjpaddle** [comment]
升级python，推荐3.7以上

**Comment by jiangh0** [comment]
python版本升级不了，请问有什么其他方案嘛

**Comment by andyjpaddle** [comment]
没了，ocr这边支持3.7以上，paddle应该3.7以下也都不支持了
