### ISSUE TITLE
竖向识别、逐字标注、不同字体大小结果不同等问题

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#8725]
您好，想要请教几个问题：
第一：如果我想让算法只竖向识别，我应该如何设置？虽然paddleOCR有自动识别竖向文字的能力，但我想对古文进行识别，基本上很多识别出来的结果均为横向）
第二：我能不能只让算法按单个字进行显示（即每个字一个框）？
第三：对于没识别出来的字能不能输出一个结果？就按概率输出一个近似的字，给出低概率即可。
第四：我想请问为什么图中的字体设置不同大小得到的结果大为不同，如下图，不同大小的字体结果区别很大？
![image](https://user-images.githubusercontent.com/62507136/209669219-0882d7de-1ce3-42fc-bb06-65c1679638d0.png)
最后：如果我打算识别古文，请问有没有什么建议。

感谢您的回复。

**Comment by andyjpaddle** [comment]
第一，paddleocr目前只能对文本行（横向）进行识别
第二，目前不支持单字，可以自己finetune训练单字识别模型
第三，没识别出来的大概率是因为检测没有检出来，可以调整检测的后处理阈值，只要检测出来，都会有识别结果的
第四，预测尺寸和训练尺寸接近时，效果最好

**Comment by haoxia1** [comment]
十分感谢您的恢复！！

第三，请问您说的检测的后处理阈值如何调整，比如下图左图，检测情况确实不容乐观，我具体该怎么做呢？但是当我将二三行摘出来他又能识别了，我想问一下这应该怎么调。
![image](https://user-images.githubusercontent.com/62507136/209671826-071eb600-f7a9-4cee-b007-272e5c9fa798.png)

下图类似，一竖无法识别，但我孤立开就能识别了
![image](https://user-images.githubusercontent.com/62507136/209672950-5daac0b0-41a3-4d6c-ae89-766287f3f127.png)

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/inference_args.md DB算法相关参数

**Comment by haoxia1** [comment]
好的，感谢。祝您生活愉快！
