### ISSUE TITLE
Recall too low for DB++

### ISSUE THREAD

**Issue by trthminh** [PaddlePaddle/PaddleOCR#8726]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
When i use DB++ for detection, recall score too low. How can i fix it ?

**Comment by LDOUBLEV** [comment]
Try replacing bceloss with diceloss.

Reference PP-OCRv3 config:
https://github.com/PaddlePaddle/PaddleOCR/blob/3560ff3a78bd114a529b202b0e98e92a57804473/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml#L39-L44

**Comment by NaumanHSA** [comment]
@LDOUBLEV I used DiceLoss and it gave me recall of 0.66 after the first 10 epochs. Thanks for the help.
