### ISSUE TITLE
`Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by jiangh0** [PaddlePaddle/PaddleOCR#8727]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

python3.8 
`
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1672196429 (unix time) try "date -d @1672196429" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 6472 (TID 0x7fc8d0119740) from PID 0 ***]`

**Comment by jiangh0** [comment]
这个如何解决？

**Comment by tink2123** [comment]
Please check whether PaddlePaddle is installed correctly :
```
import paddle
paddle.utils.run_check()
```
If `PaddlePaddle is installed successfully! ` appears, to verify that the installation was successful.

Ensure that the local environment is consistent with the installation package. Follow the doc:
https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html#old-version-anchor-8-Verify%20installation
