### ISSUE TITLE
ch_ppocr_server_v1.1_det_train.tar 预训练的话，config应该选哪个？

### ISSUE THREAD

**Issue by maxsonic** [PaddlePaddle/PaddleOCR#873]
如题，在configs目录下，没有找到对应名字的config，也没有在代码库找到对应用的是什么模型。

**Comment by tink2123** [comment]
可以参考这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/models_list.md
![image](https://user-images.githubusercontent.com/31891223/94505445-b0f46780-023d-11eb-92e5-0c0d4dc71838.png)

**Comment by maxsonic** [comment]
@tink2123  感谢
