### ISSUE TITLE
How to correct letter Q as OCR is getting O

### ISSUE THREAD

**Issue by Helkyd** [PaddlePaddle/PaddleOCR#8730]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

How to correct letter Q as OCR is getting O as you can see on the Image... 
![image](https://user-images.githubusercontent.com/20396898/209865665-f665d1be-0c16-4c8e-8a2d-32adbeccd5cb.png)

but the Prediction is **ppocr DEBUG: LD:11-99-GO, 0.898\n"**

**Comment by jingsongliujing** [comment]
Oh,you can try ch_ppocr_server_v2.0_xx model:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/ppocr_introduction_en.md

**Comment by Helkyd** [comment]
Thanks for replying... 
But as you can see the cmd and the Error returned...  Pasted the image file. 

python3 /home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py --det_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_server_v2.0_det_infer/" --cls_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_server_v2.0_rec_infer/" --rec_char_dict_path="/home/frappe/frappe-bench/apps/paddleocr/ppocr/utils/en_dict.txt" --image_dir="/home/frappe/frappe-bench/sites/paddle.angolaerp.co.ao/public/files/1672305096035242.png"

/home/frappe/.local/lib/python3.8/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
E1229 10:30:54.144547 12576 analysis_config.cc:96] Please compile with gpu to EnableGpu()
E1229 10:30:54.625770 12576 analysis_config.cc:96] Please compile with gpu to EnableGpu()
[2022/12/29 10:30:55] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2022/12/29 10:30:59] ppocr DEBUG: dt_boxes num : 1, elapse : 4.1703057289123535
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py", line 262, in <module>
    main(args)
  File "/home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py", line 180, in main
    dt_boxes, rec_res, time_dict = text_sys(img)
  File "/home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py", line 95, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/frappe/frappe-bench/apps/paddleocr/ppocr/postprocess/rec_postprocess.py", line 121, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/frappe/frappe-bench/apps/paddleocr/ppocr/postprocess/rec_postprocess.py", line 83, in decode
    char_list = [
  File "/home/frappe/frappe-bench/apps/paddleocr/ppocr/postprocess/rec_postprocess.py", line 84, in <listcomp>
    self.character[text_id]
IndexError: list index out of range


IMAGE FILE 
![1672305096035242](https://user-images.githubusercontent.com/20396898/209932323-a08ae6c6-eaea-45aa-b736-382565908cbf.png)

**Comment by jingsongliujing** [comment]
you can try modify source code 54,55line,and model link and compile:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py

**Comment by jingsongliujing** [comment]
So if you want to use the new model, you can modify it, compile the source code, and then install it：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md

**Comment by Helkyd** [comment]
Here is another example where letter Y is set as X
python3 /home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py --det_model_dir="/home/frappe/frappe-bench/apps/paddleocr/en_PP-OCRv3_det_infer/" --cls_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="/home/frappe/frappe-bench/apps/paddleocr/en_PP-OCRv3_rec_infer/" --rec_char_dict_path="/home/frappe/frappe-bench/apps/paddleocr/ppocr/utils/en_dict.txt" --image_dir="/home/frappe/frappe-bench/sites/paddle.angolaerp.co.ao/public/files/1672307701760205.png"
^[[F
/home/frappe/.local/lib/python3.8/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
E1229 10:56:46.124220 12806 analysis_config.cc:96] Please compile with gpu to EnableGpu()
E1229 10:56:46.724887 12806 analysis_config.cc:96] Please compile with gpu to EnableGpu()
[2022/12/29 10:56:47] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2022/12/29 10:56:47] ppocr DEBUG: dt_boxes num : 1, elapse : 0.628103494644165
[2022/12/29 10:56:47] ppocr DEBUG: rec_res num  : 1, elapse : 0.16654562950134277
[2022/12/29 10:56:47] ppocr DEBUG: 0  Predict time of /home/frappe/frappe-bench/sites/paddle.angolaerp.co.ao/public/files/1672307701760205.png: 0.799s
[2022/12/29 10:56:47] ppocr DEBUG: LD-59-50-EX, 0.950
[2022/12/29 10:56:47] ppocr DEBUG: The visualized image save
![Uploading 1672307701760205.png…]()
d in ./inference_resul

**Comment by Helkyd** [comment]
> So if you want to use the new model, you can modify it, compile the source code, and then install it：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md

Do you mean that to correct those letter O to Q and X to Y i need to create new model? Can i not use an existing like EN_XXX and add a fix to detect those letter better?

**Comment by jingsongliujing** [comment]
No, I mean using a more accurate model to reason




---Original---
From: ***@***.***&gt;
Date: Thu, Dec 29, 2022 18:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleOCR] How to correct letter Q as OCR isgetting O (Issue #8730)




  
So if you want to use the new model, you can modify it, compile the source code, and then install it：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md
  
Do you mean that to correct those letter O to Q and X to Y i need to create new model? Can i not use an existing like EN_XXX and add a fix to detect those letter better?

**Comment by Helkyd** [comment]
Thanks again for the support and of course for the great Tool that this is.
I have managed to get the correct Letters Q and Y by using 
python3 /home/frappe/frappe-bench/apps/paddleocr/tools/infer/predict_system.py --det_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_server_v2.0_det_infer/" --cls_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="/home/frappe/frappe-bench/apps/paddleocr/ch_ppocr_server_v2.0_rec_infer/" **--rec_image_shape="3,32,320"** --image_dir=/home/frappe/frappe-bench/sites/paddle.angolaerp.co.ao/public/files/1672307701760205.png

and removing the --rec_char_dict_path from the command line.

**Comment by jingsongliujing** [comment]
Sure
