### ISSUE TITLE
有没有针对文本图片做的超分重建的接口

### ISSUE THREAD

**Issue by 88jun12345** [PaddlePaddle/PaddleOCR#8731]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
目前没有对于接口，可以试试对应的python推理https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_sr_gestalt.md
