### ISSUE TITLE
PPOCR 做车牌识别时，预测结果和训练结果相差过大

### ISSUE THREAD

**Issue by hexianbin1994** [PaddlePaddle/PaddleOCR#8732]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

参考官网教程：https://aistudio.baidu.com/aistudio/projectdetail/4357352?contributionType=1
在最后预测阶段，做批量预测时，显示结果对每张图片的结果都相差很大，几乎是跟没训练过的结果一样的，部分显示预测结果： 
![image](https://user-images.githubusercontent.com/55222575/209894128-fc3ee704-21e5-4835-9da6-7ff0ccfc10ca.png)
使用的预测命令为：
python tools/infer_rec.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./output/rec_ppocr_v3_distillation/best_accuracy -o Global.infer_img=./lpr/data/images/test

训练结果为：
![image](https://user-images.githubusercontent.com/55222575/209894242-8b73d149-4c0b-4678-b9ea-7565a5221507.png)

**Comment by hexianbin1994** [comment]
补充：在训练或预测时，都有提示预训练模型维度不正确
![image](https://user-images.githubusercontent.com/55222575/209894523-c0466fce-09ea-474b-aba7-c3e801a6e393.png)

**Comment by Nancis1130** [comment]
请问您解决了吗

**Comment by hexianbin1994** [comment]
> 请问您解决了吗

应该是这个 tools/infer_rec.py 预测文件有问题，如果是用 eval.py 的话是可以有正常预测结果的
