### ISSUE TITLE
ImportError: cannot import name 'check_and_read_gif' from 'ppocr.utils.utility'

### ISSUE THREAD

**Issue by wang-tf** [PaddlePaddle/PaddleOCR#8735]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS
- 版本号/Version：
  - Paddle：  paddlepaddle-gpu 2.2.2
  - PaddleOCR： paddleocr 2.5.0.3
  - 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "/home/test/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/home/test/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 38, in <module>
    from ppocr.utils.utility import check_and_read_gif, get_image_file_list
ImportError: cannot import name 'check_and_read_gif' from 'ppocr.utils.utility' (/home/test/dev-tool-repos/paddleocr/PPOCRLabel/../ppocr/utils/utility.py)

```

**Comment by jingsongliujing** [comment]
paddleocr 用2.6，paddle框架建议安装2.3版本的cpu版本：安装参考：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by wang-tf** [comment]
> paddleocr 用2.6，paddle框架建议安装2.3版本的cpu版本：安装参考：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html

OK, it works.

**Comment by Mrfuhang** [comment]
解决了嘛 老铁  我这边也是用的aistudio 中带的那个LabelImg 虚拟环境，跟您报一样的错

**Comment by momei123** [comment]
Pytorch TensorFlow等哪有这么多屁问题？国产的东西真是垃圾坑多！

**Comment by xuxiansheng2018** [comment]
xxx@ubuntu:~/project/PaddleOCR$ CUDA_VISIBLE_DEVICES=1 python3 /home/xxx/project/PaddleOCR/tools/infer/predict_system.py --image_dir="./data/ocr/det_data_0827/test_det/crop_img/" --det_model_dir="./inference/ch_PP-OCRv3_det_student_inference/"  --rec_model_dir="./inference/rec_ppocr_v3_distillation_0918/Student/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/"--use_angle_cls=True --use_gpu=True  --draw_img_save_dir="./inference_results/inference_results_001_0918_test/"
Traceback (most recent call last):
  File "/home/xxx/project/PaddleOCR/tools/infer/predict_system.py", line 34, in <module>
    import tools.infer.predict_cls as predict_cls
  File "/home/xxx/project/PaddleOCR/tools/infer/predict_cls.py", line 33, in <module>
    from ppocr.utils.utility import get_image_file_list, check_and_read_gif
I**mportError: cannot import name 'check_and_read_gif' from 'ppocr.utils.utility'** (/home/xxx/project/PaddleOCR/ppocr/utils/utility.py)
同样的错误 应该如何解决
