### ISSUE TITLE
pp_ocrv3_det训练自己数据集，模型结构提取的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleOCR#8737]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
我使用ch_PP-OCRv3_det_dml训练得到了模型结构和参数，其中官方提供了方法获得student的模型参数，但模型结构咋提取，训练得到的是一个总的，应该是student和student2还有teacher的累加吧，我怎么获得student的模型结构啊，只有参数也没法预测

**Comment by WenmuZhou** [comment]
模型结构参考https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml

**Comment by shangshanruowo** [comment]
> 模型结构参考https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml

我的意思是我的到参数文件了，需要得到对应的模型结构文件，你是让我用这个yml配合参数文件直接导出模型吗？我刚刚导出了，提示参数文件中一些层的参数没有被用到，也就是这个yml没有那些层
![image](https://user-images.githubusercontent.com/101441487/210056126-27f9468a-b529-48df-b7ee-ab57c6335386.png)
![image](https://user-images.githubusercontent.com/101441487/210056171-ca8b54d0-bd5e-42f4-896e-e69bd1f9a170.png)
报了一大堆警告，这样获得的模型结构、模型参数的静态是正常的吗？感觉不像

**Comment by shangshanruowo** [comment]
而且这种导出的我也只能得到静态的模型结构，得不到动态的.pdopt的student文件，出现训练一下student的那个yml，但我以及训练完进行知识蒸馏的了，也提取出student的参数了，就差个.pdopt

**Comment by WenmuZhou** [comment]
pdopt是优化器的参数，不需要进行提取哈
