### ISSUE TITLE
如何使用多进程？

### ISSUE THREAD

**Issue by qq-tt** [PaddlePaddle/PaddleOCR#8738]
写了两个进程，打算用多进程方式跑，代码如下：
![image](https://user-images.githubusercontent.com/32315802/209932367-8f80c481-c27b-4a33-b31e-fa1ad4361afb.png)
不知道这样写对不对？
总之报错了：；
![image](https://user-images.githubusercontent.com/32315802/209932415-a22fccb4-5aa4-4d5f-af18-f32c83c3a008.png)
求问大佬们，到底怎么修改？

**Comment by WenmuZhou** [comment]
建议使用多进程，多线程不稳定
