### ISSUE TITLE
求助：paddleOCR进行图像识别，使用GPU报错，CPU没有问题

### ISSUE THREAD

**Issue by 123109** [PaddlePaddle/PaddleOCR#8739]
我用的是centos7 ，cuda 10.2 + cudnn 8.2.0，paddle 版本是：paddlepaddle-gpu 2.4.1 (2.2.0也试过，都一样），paddleOCR版本是2.6.1.2。

paddle-gpu 2.4.1就是按照官方教程给的10.2版本cuda安装方案。

另一个issue3345（https://github.com/PaddlePaddle/PaddleOCR/issues/3345）问题跟我一样，只是cuda版本与我不同，但是我试了几个不同版本的paddle-gpu，结果都是出现同样的异常。那个issue已经被 关闭，所以我只能提个新的，有没有大佬帮忙解决一下？报错信息如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
[TimeInfo: *** Aborted at 1672303357 (unix time) try "date -d @1672303357" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 29653 (TID 0x7f026d14d740) from PID 0 ***] 

DEBUGGER INFO:
Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/usr/local/lib/python3.7/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)

**Comment by WenmuZhou** [comment]
cudnn换7.6.5看看

**Comment by 123109** [comment]
cuda 11.2  cudnn 8.2.0 paddlepaddle2.1.1.post112   paddleocr 2.6.1.2 换成这套可以跑起来了

**Comment by 123109** [comment]
cuda 11.2  cudnn 8.2.0 paddlepaddle2.1.1.post112   paddleocr 2.6.1.2 换成这套可以跑起来了
