### ISSUE TITLE
是否可以进行TensorRT加速？

### ISSUE THREAD

**Issue by Wangweilai1** [PaddlePaddle/PaddleOCR#874]
目前使用Server V1.1模型，测试速度过慢在2080TI上，之后GPU服务器端会考虑加速吗？另外，目前占用显存过高，将识别模型的batch_size调低也很高，所以如果能降低显存？

**Comment by tink2123** [comment]
感谢反馈，正在适配TensorRT加速

**Comment by yiran-THU** [comment]
@tink2123 
请问下，目前的适配进度怎么样了？
