### ISSUE TITLE
【问题】ch_PP-OCRv3_rec_slim 模型速度问题

### ISSUE THREAD

**Issue by JieZou1** [PaddlePaddle/PaddleOCR#8741]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10, C++ Inference
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code：N/A
- 完整报错/Complete Error Message：None

我是按照这个文档，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme.md，采用的C++做inference的。运行都没有问题。只是速度对我来说很重要，希望slim模型能够比普通的模型要快一些。

但是，请问为什么我下载的中文识别模型ch_PP-OCRv3_rec_slim模型大小是11.3MB，而不是网页上写的4.9MB。这个模型也可以运行，但并不比普通的中文识别模型ch_PP-OCRv3_rec快。是不是有一些针对使用slim模型的特殊要求？谢谢！

**Comment by maiquanshen** [comment]
@JieZou1 你好，这个问题你最后是怎么解决的呢，能分享一下不？

**Comment by maiquanshen** [comment]
@an1018 是百度上传错了模型文件吗？

**Comment by JieZou1** [comment]
网页上说的4.9M是指的NB模型文件。在我的inference环境下无法用NB模型，我就没有再继续下去了。百度没有上传错文件。

**Comment by maiquanshen** [comment]
感谢回复，那你在耗时上后续有没有什么优化措施可以分享一下的？ 现在感觉是挺慢的？我尝试过量化部署，但在量化时报错了，没能转换成功
------------------------------------------------------------------
发件人：Jie Zou ***@***.***>
发送时间：2023年2月2日(星期四) 10:53
收件人：PaddlePaddle/PaddleOCR ***@***.***>
抄　送：麦全深 ***@***.***>; Comment ***@***.***>
主　题：Re: [PaddlePaddle/PaddleOCR] 【问题】ch_PP-OCRv3_rec_slim 模型速度问题 (Issue #8741)
网页上说的4.9M是指的NB模型文件。在我的inference环境下无法用NB模型，我就没有再继续下去了。百度没有上传错文件。

**Comment by JieZou1** [comment]
我没有再做速度的优化。项目比较紧，决定追加硬件投资。另外做了些heuristic，尽量减少识别的面积。目前已经基本满足速度要求，就没有继续追究了。

**Comment by maiquanshen** [comment]
好的，谢谢。
------------------------------------------------------------------
发件人：Jie Zou ***@***.***>
发送时间：2023年2月2日(星期四) 11:02
收件人：PaddlePaddle/PaddleOCR ***@***.***>
抄　送：麦全深 ***@***.***>; Comment ***@***.***>
主　题：Re: [PaddlePaddle/PaddleOCR] 【问题】ch_PP-OCRv3_rec_slim 模型速度问题 (Issue #8741)
我没有再做速度的优化。项目比较紧，决定追加硬件投资。另外做了些heuristic，尽量减少识别的面积。目前已经基本满足速度要求，就没有继续追究了。
