### ISSUE TITLE
关键信息抽取

### ISSUE THREAD

**Issue by xuyouqian** [PaddlePaddle/PaddleOCR#8745]
关键信息抽取支持两个同名的键区别开吗?
比如发票有一个两个公司的名称
名称:公司A
名称:公司B
我发现训练集里只标注出了名称:公司A
 
训练好模型在做预测就会忽略公司B

我如果重新把公司B 也标注进去能训练到更好的模型吗？

**Comment by an1018** [comment]
区分不同公司，可以试试下用2个键值对~，例如question1:company1，question2: company1
