### ISSUE TITLE
获取开源模型包时，企业微信群二维码群号已过期

### ISSUE THREAD

**Issue by hnlslyp** [PaddlePaddle/PaddleOCR#8746]
填写资料完成后，提示加群，该二维码已经过期
https://paddle.wjx.cn/wjx/join/complete.aspx?activityid=QwF7GKw&joinid=116345570297&sojumpindex=41&anst=3G5u2D1dzbi3gyMZhPngq2eLAZIUPNn7&comsign=91045B425AA499AE6FCB54D9A00700556B23E07E&s=

**Comment by an1018** [comment]
请问已经入群了吗

**Comment by haoxia1** [comment]
您好，有新的二维码吗

> 请问已经入群了吗

**Comment by an1018** [comment]
已经更新了，刷新一下问卷试试~

**Comment by abbydev** [comment]
> 已经更新了，刷新一下问卷试试~

我填完后提示又过期了，帮忙刷新一下，谢谢！
