### ISSUE TITLE
字体比例问题 & 简繁体区别

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#8748]
您好，我想请教两个问题：
第一，如下图所示，为什么“人”字占据整张图片非常大的时候无法识别出来？只有当该字占据整张图片比例合适时才可识别，我尝试了当字体占比更小的时候也无法识别，这可以理解。但为何占比较大的时候无法识别？

![image](https://user-images.githubusercontent.com/62507136/210079383-26f3b680-50a7-497f-b534-7b47f5c91fd5.png)

第二，同样上面三幅图，为何当我将识别语言由简体字ch变化为繁体字chinese_cht之后，均无法识别出结果？我想问这是否是训练数据不同的原因，所以我想了解一下paddleOCR在训练简体繁体时的数据以及其他方面的区别。

感谢您的回复！

**Comment by an1018** [comment]
训练使用的是字符串，单字符效果可能变差；如果已经做了切割，可以直接识别，如果未切割(图2、3)需要先检测后识别
如果当前场景只识别单字符，可以调整训练shape进行训练
字典也不相同

**Comment by huangxin168** [comment]
检测模型没检测到，自然没法识别。
可以调整检测模型几个thresh参数设置再试试。

**Comment by haoxia1** [comment]
> 检测模型没检测到，自然没法识别。 可以调整检测模型几个thresh参数设置再试试。

嗯嗯谢谢  已经尝试过了；
