### ISSUE TITLE
端侧部署../Makefile.def: 没有那个文件或目录

### ISSUE THREAD

**Issue by starrySkyO** [PaddlePaddle/PaddleOCR#875]
端侧部署到arm-linux上，最后一步编译时，报错Makefile:4: ../Makefile.def: 没有那个文件或目录
![image](https://user-images.githubusercontent.com/32013435/94410135-9a043580-01a9-11eb-88d4-05b084f37d51.png)

**Comment by LDOUBLEV** [comment]
检查下demo/cxx下是否有Makefile.def这个文件，正常编译好的预测库是有的
![image](https://user-images.githubusercontent.com/26592129/94634003-7a802080-0301-11eb-9a73-31b2bbee61ec.png)

**Comment by starrySkyO** [comment]
我按照官方教程，使用docker开发环境，使用&nbsp;&nbsp;./lite/tools/build_linux.sh&nbsp; --arch=armv8&nbsp; --with_cv=ON --with_extra=ON&nbsp; 编译Lite预测库，编译成功，但是没有在相关目录下找到Makefile.def 文件。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 上午9:44
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"1752476835"<1752476835@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 端侧部署../Makefile.def: 没有那个文件或目录 (#875)





 
检查下demo/cxx下是否有Makefile.def这个文件，正常编译好的预测库是有的

**Comment by LDOUBLEV** [comment]
用现在Paddle-Lite 2.6.3分支编译再试下，测试了可以用

**Comment by longshifeng** [comment]
![image](https://user-images.githubusercontent.com/32770755/103460836-6d395e80-4d54-11eb-9319-794cc9633bc8.png)

@LDOUBLEV @starrySkyO 你好，
树莓派4B 编译paddle-lite release/v2.7成功 但是使用demo 推理的时候 make -j 出现上述错误。

关于 demo/cxx下 确实 没有Makefile.def这个文件 在编译成功后正常demo下是没有cxx文件夹的，在 PaddleOCR/deploy/lite/下运行prepare.sh 才会生成cxx文件，而 prepare.sh 脚本里也没有关于Makefile.def啊。所以如果应该生成Makefile.def是应该在哪一步产生的？？
```
mkdir -p  $1/demo/cxx/ocr/debug/
cp  ../../ppocr/utils/ppocr_keys_v1.txt  $1/demo/cxx/ocr/debug/
cp -r  ./*   $1/demo/cxx/ocr/
cp ./config.txt  $1/demo/cxx/ocr/debug/
cp ../../doc/imgs/11.jpg  $1/demo/cxx/ocr/debug/

echo "Prepare Done"
```

![d0a788e1a9028c4d55b86237f7f9be5](https://user-images.githubusercontent.com/32770755/103460856-aa055580-4d54-11eb-95d4-07cb896a89fb.png)

**Comment by longshifeng** [comment]
另外 编译paddle-lite 时的命令如下：
sudo ./lite/tools/build_linux.sh --arch=armv7hf --with_python=ON --python_version=3.7 --with_cv=ON --with_extra=ON
