### ISSUE TITLE
Error when run SAST model

### ISSUE THREAD

**Issue by trthminh** [PaddlePaddle/PaddleOCR#8750]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- When I use SAST for detection, i see this error:
![image](https://user-images.githubusercontent.com/76390108/210165987-2f64e7a2-8762-4b54-9203-13e2123adc5e.png)
![image](https://user-images.githubusercontent.com/76390108/210165994-14012175-44af-4ce3-8f02-9822a6a4fd96.png)

How can i fix it ? Thank you so much

**Comment by MissPenguin** [comment]
This error seems to be caused by incorrect annotation format. Check if the points are clockwise ordered.
