### ISSUE TITLE
Inference times

### ISSUE THREAD

**Issue by arcb01** [PaddlePaddle/PaddleOCR#8753]
Hi!

I was thinking of using this OCR in a project. However, frist of all I wanted to know what are the aproximate CPU/GPU inference times of a single image. Anyone that has used this software before could provide me some insights?

Thanks!

**Comment by LDOUBLEV** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/PP-OCRv3_introduction_en.md#4-end-to-end-evaluation
Hope this helps
