### ISSUE TITLE
en_PP-OCRv3_det_infer model converted to ONNX gives 0 as output for all inputs

### ISSUE THREAD

**Issue by adjhawar** [PaddlePaddle/PaddleOCR#8754]
I converted the paddle **en_PP-OCRv3_det_infer** [English text detection model] to **ONNX opset 11** using the below command.
_paddle2onnx --model_dir . --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file model.onnx --opset_version 11 --enable_onnx_checker True_

Now, when I try to run the model on onnx, I am getting the output as 0 for all inputs. For paddle, the output is fine.
I even tried running the run_diff.py script that is mentioned in https://github.com/PaddlePaddle/PaddleOCR/issues/4141
On running that script, I am getting the below output:

![Screenshot (3)](https://user-images.githubusercontent.com/15729111/210251577-740e1edc-36da-4ed4-abf8-ba64f6fcbcb6.png)

Could you please check and help?

**Comment by robinchm** [comment]
I can confirm this behavior with `cn_PP-OCRv3-det-infer` model converted to onnx with any opset >= 11. Any input produces output of all zeros, which is inconsistent with the paddle model. This seems to be a severe issue, can someone from the team take a look?
