### ISSUE TITLE
关于竖向的日语识别不准，是否是文件配置问题还是需要自己训练竖向文字呢？

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleOCR#8760]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by xiatian114** [comment]
![image](https://user-images.githubusercontent.com/119492593/210309192-6fb9fdcb-b503-4e9b-97f2-a1edd78ad30b.png)

**Comment by andyjpaddle** [comment]
可以在识别前面添加方向分类器

**Comment by shumeirao** [comment]
> 可以在识别前面添加方向分类器

已经添加了的

**Comment by andyjpaddle** [comment]
可以加一些竖排数据微调一下

**Comment by shumeirao** [comment]
> 可以加一些竖排数据微调一下

可以合成嘛，还是要真实场景的数据呢？大概需要标注的量级是多少呢？

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83

**Comment by shumeirao** [comment]
> 参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83

好的，非常感谢您的耐心解答

**Comment by WuNein** [comment]
> > 参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83
> 
> 好的，非常感谢您的耐心解答

您解决了吗？文本方向检测，还有文字检测是不是都要微调一下？我怀疑竖向是否需要单独训练模型~
