### ISSUE TITLE
表格识别模型微调训练效果比较差，如何改善

### ISSUE THREAD

**Issue by justcodew** [PaddlePaddle/PaddleOCR#8761]
使用ppocr提供的表格识别模型SLANet在中文数据集上进行微调训练，效果比较差。相关的配置如下：
**数据集：**[[好未来表格识别竞赛数据集](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/table_datasets.md#2-%E5%A5%BD%E6%9C%AA%E6%9D%A5%E8%A1%A8%E6%A0%BC%E8%AF%86%E5%88%AB%E7%AB%9E%E8%B5%9B%E6%95%B0%E6%8D%AE%E9%9B%86)]   train:val = 14000: 2000   将原有的1.6w训练集进行了重新划分
**预训练模型：** ch_ppstructure_mobile_v2.0_SLANet  训练模型[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list.md](url)
**配置：** configs/table/SLANet_ch.yml  屏蔽了字段 character_type: en
训练4个epoch后，acc为0.90，测试保存下来的best模型，效果并不好，可视化效果图如下所示
![image](https://user-images.githubusercontent.com/107862224/210319750-a0392ec3-1473-474c-83db-33690d48178e.png)

微调前推理模型效果：
![image](https://user-images.githubusercontent.com/107862224/210319367-99948d89-fc67-46fb-9d65-4ed4ae46da81.png)
![image](https://user-images.githubusercontent.com/107862224/210319383-137db421-ba9a-41c9-a6d2-281729c3e541.png)
![image](https://user-images.githubusercontent.com/107862224/210319395-d86549af-715a-4167-b9c1-74cf29e662b0.png)
![image](https://user-images.githubusercontent.com/107862224/210319406-a0c4a6f9-0abb-436c-acaf-5f51ff8193b1.png)
微调后模型效果：
![image](https://user-images.githubusercontent.com/107862224/210319460-985c93e6-13b1-4a9b-a95c-3f8866839ce9.png)
![image](https://user-images.githubusercontent.com/107862224/210319489-398f2c0c-7b40-421d-8cce-15df2dcd2490.png)
![image](https://user-images.githubusercontent.com/107862224/210319504-1b6af1ea-e2e0-40cb-b42b-b73c8b034a7f.png)
![image](https://user-images.githubusercontent.com/107862224/210319530-dfb4b92d-5e4b-4940-80c6-d7d708e49c7e.png)

可以看到效果根本无法使用

**Comment by justcodew** [comment]
同样也测试了提供的tablemaster模型在相同测试集上的效果如下：

![image](https://user-images.githubusercontent.com/107862224/210320287-52d046d0-35c7-44b9-bdda-df4d632acd3c.png)
![image](https://user-images.githubusercontent.com/107862224/210320306-28f04398-1fda-4ec3-aa72-ed027aa0e928.png)
![image](https://user-images.githubusercontent.com/107862224/210320328-fc42e440-0cfd-4100-b19e-37ff48d6e90c.png)

![image](https://user-images.githubusercontent.com/107862224/210320352-e71aacd5-2984-4506-bff1-97a2a6f5b663.png)
效果也是比较差

**Comment by andyjpaddle** [comment]
需要先进行表格区域检测，再进行表格识别，看你的可视化并不是单纯的表格图片

**Comment by justcodew** [comment]
> 需要先进行表格区域检测，再进行表格识别，看你的可视化并不是单纯的表格图片

确实并不是单纯的表格图片。SLANet和tablemaster两个方案都不是端到端的表格识别方案吗，需要先进行表格检测，然后再进行表格识别哈。ppocr有端到端的方案吗，融合了检测和识别模块的。

**Comment by justcodew** [comment]
我调整了一些训练参数，效果有改善一些，但仍然达不到使用效果。
测试和训练数据存在倾斜、扭曲等现象，不知道SLANet是否是否这类场景的数据
![image](https://user-images.githubusercontent.com/107862224/210526004-3930e8b6-a265-473a-b4f5-b95a818c710b.png)
![image](https://user-images.githubusercontent.com/107862224/210526057-f4cdd3cd-568a-4da5-9208-ee06d1c09a7e.png)
![image](https://user-images.githubusercontent.com/107862224/210526096-e59184ad-7edc-41e0-9620-f861c95f6d15.png)
![image](https://user-images.githubusercontent.com/107862224/210526145-a1e834b9-cc1e-4c31-a56c-0d72c98ece08.png)

**Comment by andyjpaddle** [comment]
端到端可以参考这个文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/inference.md#11-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90%E8%A1%A8%E6%A0%BC%E8%AF%86%E5%88%AB
倾斜的识别效果还不太好，可以找一些文档矫正相关的算法进行预处理

**Comment by justcodew** [comment]
采用slanet在合成表格数据集上进行微调后，测试效果如下：
数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ）
单元格的边界不是特别准，这种边界不准的问题改如何进行优化
![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png)
![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png)
![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png)
![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png)
![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)

**Comment by andyjpaddle** [comment]
> 采用slanet在合成表格数据集上进行微调后，测试效果如下： 数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ） 单元格的边界不是特别准，这种边界不准的问题改如何进行优化 ![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png) ![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png) ![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png) ![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png) ![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)

测试效果已经很可以了吧，可以看下转化后的Excel效果是否能满足需求

**Comment by ASLYY** [comment]
> 采用slanet在合成表格数据集上进行微调后，测试效果如下： 数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ） 单元格的边界不是特别准，这种边界不准的问题改如何进行优化 ![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png) ![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png) ![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png) ![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png) ![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)

请教一下您是如何进行微调的呀？

**Comment by Mrfuhang** [comment]
> > 采用slanet在合成表格数据集上进行微调后，测试效果如下： 数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ） 单元格的边界不是特别准，这种边界不准的问题改如何进行优化 ![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png) ![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png) ![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png) ![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png) ![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)
> 
> 请教一下您是如何进行微调的呀？

需要自己标注数据吧

**Comment by Jsooooooo** [comment]
能发几条数据看看吗，我看下我的数据有没有错，还有配置文件是默认的吗？

**Comment by nissansz** [comment]
有微调后的模型可以分享吗？微信nlanguage

**Comment by nissansz** [comment]
微调后，只能对生成的表格效果好，泛化到实际表格效果差，怎么解决？

**Comment by ncuxzy** [comment]
> 我调整了一些训练参数，效果有改善一些，但仍然达不到使用效果。 测试和训练数据存在倾斜、扭曲等现象，不知道SLANet是否是否这类场景的数据 ![image](https://user-images.githubusercontent.com/107862224/210526004-3930e8b6-a265-473a-b4f5-b95a818c710b.png) ![image](https://user-images.githubusercontent.com/107862224/210526057-f4cdd3cd-568a-4da5-9208-ee06d1c09a7e.png) ![image](https://user-images.githubusercontent.com/107862224/210526096-e59184ad-7edc-41e0-9620-f861c95f6d15.png) ![image](https://user-images.githubusercontent.com/107862224/210526145-a1e834b9-cc1e-4c31-a56c-0d72c98ece08.png)

都微调了哪些参数呢，我这边finetune的效果也比较差，用的好未来的训练数据，下一步试试把好未来数据里的表格裁剪出来识别

**Comment by nissansz** [comment]
你会将https://github.com/microsoft/table-transformer 检测和识别模型转换成onnx吗？然后怎么用这个onnx模型？

**Comment by nissansz** [comment]
我用大单元格图训练，然后用来检测简单的实际图， 也会有这种 '<td', '>' 漏掉中间的colspan信息，不知道怎么回事，你有碰到吗？怎么解决？

['<html>', '<body>', '<table>', '<tr>', '<td', '>', '</td>', '</tr>', '<tr>', '<td></td>', '<td', '>', '</td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', '</tr>', '</table>', '</body>', '</html>'],

![20231022220750](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/86566a54-d20a-4fb1-8a16-3d0af8542098)

**Comment by nissansz** [comment]
可以分享下百度网盘的 [好未来表格识别竞赛数据集] ？
官网好像没看到这个数据集了

**Comment by gl94** [comment]
我也是acc很高,但是实际不可用,可能是eval的代码有问题

**Comment by favorxin** [comment]
> 我也是acc很高,但是实际不可用,可能是eval的代码有问题

你好，我也遇到了这个问题，请问解决了么，我这边acc都97.9%了，然后跑eval效果很差
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/31987475/7b0fc41b-b980-4fda-852f-7931a633be0f)

**Comment by FryBoom** [comment]
> 采用slanet在合成表格数据集上进行微调后，测试效果如下： 数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ） 单元格的边界不是特别准，这种边界不准的问题改如何进行优化 ![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png) ![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png) ![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png) ![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png) ![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)



> 采用slanet在合成表格数据集上进行微调后，测试效果如下： 数据集（https://aistudio.baidu.com/aistudio/datasetdetail/165849 ） 单元格的边界不是特别准，这种边界不准的问题改如何进行优化 ![image](https://user-images.githubusercontent.com/107862224/210729296-901193a7-dd99-45cb-8b5d-aa9c7594cfc7.png) ![image](https://user-images.githubusercontent.com/107862224/210728882-347f7d4e-7561-4f74-8c2e-3c2394edd956.png) ![image](https://user-images.githubusercontent.com/107862224/210727578-c145213c-45a2-4855-8628-1e963257dcb4.png) ![image](https://user-images.githubusercontent.com/107862224/210727700-e2ee6a33-97b7-4cac-bba0-971124891b12.png) ![image](https://user-images.githubusercontent.com/107862224/210728430-3e9add58-d5af-4f26-bb27-661ed404b788.png)

跪求调整了哪些参数！我也遇到了行合并的错误问题。

**Comment by nissansz** [comment]
英文识别训练数据集用哪个好？

**Comment by Sherryran08** [comment]
> 我调整了一些训练参数，效果有改善一些，但仍然达不到使用效果。 测试和训练数据存在倾斜、扭曲等现象，不知道SLANet是否是否这类场景的数据 ![image](https://user-images.githubusercontent.com/107862224/210526004-3930e8b6-a265-473a-b4f5-b95a818c710b.png) ![image](https://user-images.githubusercontent.com/107862224/210526057-f4cdd3cd-568a-4da5-9208-ee06d1c09a7e.png) ![image](https://user-images.githubusercontent.com/107862224/210526096-e59184ad-7edc-41e0-9620-f861c95f6d15.png) ![image](https://user-images.githubusercontent.com/107862224/210526145-a1e834b9-cc1e-4c31-a56c-0d72c98ece08.png)

你好，我最近也在自己的数据集上进行微调，但是微调之后的效果很差，想问一下您是调整了哪些参数之后效果有所改善
