### ISSUE TITLE
如何将PPOCRLabel标注的数据转成LMDB格式

### ISSUE THREAD

**Issue by hanyong-max** [PaddlePaddle/PaddleOCR#8763]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以直接使用SimpleDataset格式进行训练

**Comment by hanyong-max** [comment]
@andyjpaddle 
PPOCRLabel标注导出的Label.txt文件是SimpleDataset格式吗？
