### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf:

### ISSUE THREAD

**Issue by BenjiaminLiu** [PaddlePaddle/PaddleOCR#8768]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：docker pull paddlepaddle/paddle:latest-dev-cuda11.6.2-cudnn8.4.0-gcc82
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：python predict_system.py

问题描述：
使用相应预训练模型finetune文本检测、识别任务，对finetune后模型通过python tools/export_model.py进行相应转换成inference模型，现在需要对inference模型进行测试预测，调用python predict_system.py相应脚本及参数，最终报错。

报错信息：
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from output/inference/det_ch_db_res18_inference/ failed:Protobuf parsing failed.

![image](https://user-images.githubusercontent.com/42370103/210479555-8025b25a-f31e-4301-95a0-f6ef54368f0c.png)
![image](https://user-images.githubusercontent.com/42370103/210479581-000fa879-392a-4bcd-9b8b-ceb4f5790835.png)
![image](https://user-images.githubusercontent.com/42370103/210479599-e6ac329e-cedf-47f8-8d12-5c324558f23b.png)

**Comment by AlexPasqua** [comment]
@BenjiaminLiu I also have the same issue. Do you have news about it?
