### ISSUE TITLE
 linux 下的 hub serving 不能用gpu运行

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PaddleOCR#877]
在aistudio 上运行 ，仿照示例，想开启GPU加速，但是报错：
![image](https://user-images.githubusercontent.com/53250648/94439845-7fdf4d00-01d3-11eb-88a5-32b942103c5d.png)

![image](https://user-images.githubusercontent.com/53250648/94439625-3989ee00-01d3-11eb-9e8c-41aff9f47291.png)

**Comment by MissPenguin** [comment]
工作目录应该是PaddleOCR根目录，启动命令要给config.json加上路径

**Comment by grasswolfs** [comment]
> 在aistudio 上运行 ，仿照示例，想开启GPU加速，但是报错：
> ![image](https://user-images.githubusercontent.com/53250648/94439845-7fdf4d00-01d3-11eb-88a5-32b942103c5d.png)
> 
> ![image](https://user-images.githubusercontent.com/53250648/94439625-3989ee00-01d3-11eb-9e8c-41aff9f47291.png)

我印象中AIStudio应该是不能部署hub serving的，没有开放的IP地址，所以还是需要在自己本地部署，或者云上部署

**Comment by grasswolfs** [comment]
由于帖子时间较长时间没有进一步收到信息回复，暂时关闭，如果仍然有问题可以reopen
感谢对于PaddleOCR的支持
