### ISSUE TITLE
一些语言缩写上的问题

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleOCR#8770]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddleocr             2.6.1.2
paddlepaddle          2.4.1
- 运行指令/Command Code：PaddleOCR(lang='ka')
- 完整报错/Complete Error Message：无报错

- 在PaddleOCR模型加载的时候可以指定语言缩写为 ka和devanagari，但是在语种缩写的表格里没有提

https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/multi_languages.md#5-%E6%94%AF%E6%8C%81%E8%AF%AD%E7%A7%8D%E5%8F%8A%E7%BC%A9%E5%86%99

- 可以加载 lang='latin'，在列表里没有，最接近的是 塞尔维亚文（latin) | Serbian(latin) | rs_latin

**Comment by tink2123** [comment]
latin、 Devanagari 这些是语系，和具体语种的对应关系在列表中没有给出，感谢反馈后续我们会补充上。

**Comment by linhandev** [comment]
嗯嗯，我没怎么做过ocr这块不太了解这个区别，但感觉就从PaddleOCR(lang='..')这个接口的角度列表里也写上会比较清楚
