### ISSUE TITLE
在服务化部署中，发送预测请求报错ModuleNotFoundError: No module named 'tools.infer'

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8773]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
请问使用的命令是？ 缺少tools.infer 可以在PaddleOCR 根目录下手动设置pythonpath ：

export PYTHONPATH=/your_path/PaddleOCR

**Comment by zyzz1974** [comment]
命令是hub serving start -c config.json

**Comment by zyzz1974** [comment]
请问这个在根目录的哪里设置pythonpath

**Comment by bilykigor** [comment]
export PYTHONPATH=... does not solve the issue

**Comment by rexzhengzhihong** [comment]
我也碰到这个问题了？怎么解决的？
