### ISSUE TITLE
ppocr ERROR: error in loading image

### ISSUE THREAD

**Issue by jiangh0** [PaddlePaddle/PaddleOCR#8775]
`self.ocr = PaddleOCR(det_model_dir=os.path.join(BASE_DIR, 'ch_PP-OCRv3_det_infer'), rec_model_dir=os.path.join(BASE_DIR, 'ch_PP-OCRv3_rec_infer'), cls_model_dir=os.path.join(BASE_DIR, 'ch_ppocr_mobile_v2.0_cls_infer'), use_angle_cls=True, use_gpu=True)`

ppocr ERROR: error in loading image

**Comment by jiangh0** [comment]
`res = self.ocr.ocr(img_path, cls=True)`

**Comment by jiangh0** [comment]
运行的时候报了这个错，图片路径是对的

**Comment by tink2123** [comment]
建议再检查一下图片，可以执行 
```
python tools/infer/predict_system.py --image_dir="your_img" --det_model_dir="./ch_PP-OCRv3_det_infer/" --cls_model_dir="./cls/" --rec_model_dir="./ch_PP-OCRv3_rec_infer/" 
```
并在以下代码位置debug图片读取结果：
https://github.com/PaddlePaddle/PaddleOCR/blob/f9d0948b0c8ea8abcf9dc1b29495569bd73ae8bb/tools/infer/predict_system.py#L170
