### ISSUE TITLE
index 4 is out of bounds for axis 0 with size 4 - 0xc0000005

### ISSUE THREAD

**Issue by Siegi96** [PaddlePaddle/PaddleOCR#8776]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows Server 2016, Version 10 | Python 3.8 | Quadro RTX 6000 | CUDA 11.7 
- 版本号/Version：Paddle：2.6.1.2  PaddleOCR：2.4.1.post117 Det. Model: en_PP-OCRv3_det_infer Rec. Model: latin_PP-OCRv3_rec_infer  问题相关组件/Related components：
- 完整报错/Complete Error Message：
`error.stack_trace: File "C:\Shares\Flask\app\service\ocr_service.py", line 124, in ocr_by_url_batch_paddle self.paddle_reader.ocr( File "C:\Shares\Flask\venv\lib\site-packages\paddleocr\paddleocr.py", line 555, in ocr dt_boxes, rec_res, _ = self.__call__(img, cls) File "C:\Shares\Flask\venv\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 95, in __call__ rec_res, elapse = self.text_recognizer(img_crop_list) File "C:\Shares\Flask\venv\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 621, in __call__ rec_res[indices[beg_img_no + rno]] = rec_result[rno] @timestamp:Dec 29, 2022 @ 20:35:28.091 data_stream.type:logs ecs.version:1.6.0 error.message:index 4 is out of bounds for axis 0 with size 4 error.type:IndexError`

which kills the Python Process with this error Message in the Windows Event Log:

Faulting application name: python.exe, version: 3.8.11150.1013, time stamp: 0x610d4e38
Faulting module name: MSVCP140.dll, version: 14.16.27033.0, time stamp: 0x5d30eae5
Exception code: 0xc0000005
Fault offset: 0x000000000000900c
Faulting process id: 0xf68
Faulting application start time: 0x01d91b9bd694bfbe
Faulting application path: C:\ProgramData\Anaconda3\python.exe
Faulting module path: C:\Shares\Flask\venv\lib\site-packages\pandas\_libs\window\MSVCP140.dll
Report Id: 1b4b84ef-7582-40a9-80e5-5343222b2309
Faulting package full name: 
Faulting package-relative application ID: 

The error appears from time to time, but the images are not the problem. If I retry the image which caused the problem, it works without any errors.

**Comment by tink2123** [comment]
Is ocr_service.py developed by yourself? The current information is temporarily unable to find the problem. Can you debug it in predict_rec.py?
