### ISSUE TITLE
Android 后台运行OCR识别图片文字，耗时特别长

### ISSUE THREAD

**Issue by yiluyoufeng** [PaddlePaddle/PaddleOCR#8777]
应用提供的android demo，在主进程中，开启线程去OCR识别图片，当app切换到后台时，识别时长超10s以上，前台识别500ms就识别成功了。
提供native的识别耗时，是否跟app处于后台有关？部分机型后台识别耗时太长了。10s以上的机型有：vivo S10 Pro、华为Mate10 Pro、P30 Pro、HUAWEI nova10 Pro等机型。请问这个根本原因是什么呢？

**Comment by WenmuZhou** [comment]
app处于后台，系统给的gpu资源少

**Comment by yiluyoufeng** [comment]
> 

除了跟gpu资源有关，还跟其他的系统资源有关系吗？？
这个是否有优化提升空间？

**Comment by WenmuZhou** [comment]
放前台吧，别放后台了，放后台，系统给的各种资源都少，包括cpu gpu

**Comment by hcx1002** [comment]
要设置悬浮窗，可以获得更多的资源
