### ISSUE TITLE
公布的paddle模型使用的中英文训练数据集，是通用的吗？

### ISSUE THREAD

**Issue by Armin199608** [PaddlePaddle/PaddleOCR#8778]
我把使用ICDAR2019-LSVT、ICDAR2017-RCTW-17、中文街景文字识别、中文文档文字识别
四个数据集和生成了一部分数据，从头开始训练paddle V2，但是远达不到你们公布的模型的精度。
训练时候，遵从了本站的指导，且没有修改config的关键参数。

能公布你们通用中英文训练时候的数据集吗？这样我们在训练其他先进文字识别模型的时候，可以从头开始训练。

数据集不方便公开的话，那么你们能不能将其他的先进文字识别模型，训练一版中英文模型，并公开。比如ABINet，仅有中文的，要是能有中英文的就更好了。

**Comment by tink2123** [comment]
通用中英文模型还使用了大量的合成数据，抱歉全量数据过大暂时无法公开。

关于其他先进文字识别模型均提供了英文模型，可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_overview.md#12

**Comment by Armin199608** [comment]
@tink2123 
抱歉，我说错了，你们提供的是仅英文，我想要的是含中文的。这个有吗？
后续会有吗？
