### ISSUE TITLE
Word bounding boxes from PPOCR model

### ISSUE THREAD

**Issue by Shini1996koshy** [PaddlePaddle/PaddleOCR#8779]
Is there a way that paddle ocr suppports the word level bounding box as it output along with line level bounding box

**Comment by tink2123** [comment]
At present, the official does not provide this interface for the time being, and you can estimate the word boundary through the output of ctc.

**Comment by Shini1996koshy** [comment]
Hi ,
Could you please guide me on how to get the results

**Comment by 12seetharaman** [comment]
Hi @tink2123 
Please give some details on how to use the ctc model to get word bounding box.

Thanks!

**Comment by similang** [comment]
> At present, the official does not provide this interface for the time being, and you can estimate the word boundary through the output of ctc.

Any reference how could this be done? @tink2123
