### ISSUE TITLE
db_head部分参数存在共享现象

### ISSUE THREAD

**Issue by Aiyoj** [PaddlePaddle/PaddleOCR#878]
![image](https://user-images.githubusercontent.com/28584450/94510531-94f6c300-0249-11eb-89dc-05ac5aaf7f72.png)
![image](https://user-images.githubusercontent.com/28584450/94510551-a4760c00-0249-11eb-8eac-7008e82d2af9.png)
thresh和binari函数里的红框框出的bias参数是共享的

**Comment by WenmuZhou** [comment]
观察真细致，这两个是一样的

**Comment by ausk** [comment]
No, conv3_b_attr shape is (1,); conv2_b_attr shape is (24,).
