### ISSUE TITLE
PaddleOCR onnxruntime 部署出错

### ISSUE THREAD

**Issue by 203chenjing** [PaddlePaddle/PaddleOCR#8786]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

部署Paddle OCR 报参数错误
![image](https://user-images.githubusercontent.com/101111227/210595328-a9abd2fb-488e-4a60-a808-4df66dfa9c3b.png)

**Comment by tink2123** [comment]
使用release/2.6的代码和PP-OCRv3的模型试下，看报错shape不一致
