### ISSUE TITLE
PPOCRLabel不能正常运行的问题

### ISSUE THREAD

**Issue by metoogo** [PaddlePaddle/PaddleOCR#8789]
下载了最新的PaddleOCR 2.6，想使用PPOCRLabel训练自己的数据，但是发现一直都无法正常运行。
安装完全是跟着官方教程走的，基本都能正常安装完成，但是就是跑不起来。
开始是报错np.int有问题，找了代码把np.int改成np.int32解决。
跑到界面以后，选择重新识别后又报以下的错：
AttributeError: 'tuple' object has no attribute 'insert'
有时候没点到“矩形标注”，而直接点击了图像，就会报这个错：
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

- 系统环境/System Environment：windows 10
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.0 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
你的PPOCRLabel是啥版本的

**Comment by metoogo** [comment]
> 你的PPOCRLabel是啥版本的，PPOCRLabel和paddleocr都更新到最新版试试

使用的都是最新的版本了，我帖子上注明有详细的版本信息

**Comment by metoogo** [comment]
有大佬指点一下吗？或者是不是有完整的环境包下载？不知道是不是我的依赖有问题？还是说一些依赖在win系列表现方式跟linux不一样？

**Comment by TasneemVKhan** [comment]
> What version is your PPOCRLabel, PPOCRLabel and paddleocr are updated to the latest version to try

I have the same error when I try to Recognize a cell containing '0'. It gives me the same error. Please help

**Comment by Evezerest** [comment]
PPOCRLabel是2.1.3版本吗？是否先点击了自动识别

**Comment by TasneemVKhan** [comment]
Yes it is the new version of PPOCRLabel 2.1.3

**Comment by Mrfuhang** [comment]
> PPOCRLabel 2.1.3

 PPOCRLabel 2.1.3 不是只有paddlepaddle这个库吗  没有看到你 PPOCRLabel 2.1.3这个库啊

**Comment by Mrfuhang** [comment]
> Yes it is the new version of PPOCRLabel 2.1.3

安装了这个库还是报这个错呢：AttributeError: 'tuple' object has no attribute 'insert'
