### ISSUE TITLE
安卓demo 报错

### ISSUE THREAD

**Issue by siyangbing** [PaddlePaddle/PaddleOCR#879]
CMake Error at /home/db/图片/PaddleOCR/deploy/android_demo/app/src/main/cpp/CMakeLists.txt:18 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

**Comment by WenmuZhou** [comment]
rebuild一下可以吗

**Comment by siyangbing** [comment]
我rebuild
结果如下
```python
CMake Error at /home/db/图片/PaddleOCR/deploy/android_demo/app/OpenCV/sdk/native/jni/abi-armeabi-v7a/OpenCVModules.cmake:245 (message):
The imported target "libcpufeatures" references the file
```

**Comment by MissPenguin** [comment]
目前最新代码是没有问题的，可以先拉取最新代码试试哈，如果仍有问题欢迎重新提issue～
