### ISSUE TITLE
服务化解析失败IndexError: string index out of range

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8790]
(venv) PS D:\orc2\paddleOCR> python tools/test_hubserving.py --server_url=http://127.0.0.1:8868/predict/structure_table --image_dir=D:\1.jpeg
D:\orc2\paddleOCR\venv\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
IndexError: string index out of range

**Comment by WenmuZhou** [comment]
有更详细的截图吗

**Comment by zyzz1974** [comment]
![Uploading image.png…]()
毫无反应

**Comment by zyzz1974** [comment]
没有返回结果是怎么回事呢

**Comment by WenmuZhou** [comment]
可以运行一下modulel文件本身，看看有没有报错

**Comment by Han-Y-F** [comment]
请问解决了吗

**Comment by xuxh6** [comment]
我是 运行了 hub install ./deploy/hubserving/ocr_system/  之后就解决了问题。仅供参考
