### ISSUE TITLE
PPOCRLabel好像有点小bug

### ISSUE THREAD

**Issue by laoda22222222** [PaddlePaddle/PaddleOCR#8792]
![image](https://user-images.githubusercontent.com/122009013/210942259-9fc63f72-8238-4dfb-a028-fbcde1e111ca.png)
![image](https://user-images.githubusercontent.com/122009013/210942454-951ff670-f9c1-4e1e-bf86-bae03eaa1387.png)
自动标注错误时想要手动去矫正的时候键盘输入的时候就会自动切换，没办法去进行矫正

**Comment by 1061302569** [comment]
我也是一输入就自动切换到英文

**Comment by Evezerest** [comment]
尝试一下系统默认的输入法

**Comment by hideinhat** [comment]
win11系统，先用系统默认输入法进入PPOCRLabel，再切换到xunfei输入法，可以输入中文
