### ISSUE TITLE
关于OCR运行GPU显存占用过大的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleOCR#8794]
本地设备以及部署到服务器设备上运行OCR时，GPU会占用大约3、4个G的显存。

请问：
    1.请问为什么会占用这么较大的显存
    2.这个占用这么大，服务器上可加载的其他算法模型就会相对减少，请问这个OCR的显存如何能优化呢？

**Comment by an1018** [comment]
如果是hub部署，可以参考下这个issue：https://github.com/PaddlePaddle/PaddleHub/issues/682
