### ISSUE TITLE
sar模型无法验证且预测出的顺序不对，如标签1155，预测为1515.

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#8795]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.3  PaddleOCR：2.5  问题相关组件/Related components：
- 运行指令/Command Code：
![image](https://user-images.githubusercontent.com/76056473/210961674-72aa4d6b-2826-4263-b1fc-1b006d1b584b.png)

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/76056473/210961599-2abde0c2-de44-40e0-8181-f30c9fe2f060.png)

**Comment by an1018** [comment]
有使用提供的预训练模型预测看看效果吗

**Comment by chc-stars** [comment]
没有。然后主干网络我换成了resnet18和resnet34.还有那个yml文件里的标签是内置了嘛，为啥换成自己的预测出来还是原来的。

**Comment by an1018** [comment]
标签内置是什么意思呢，就是按[这个教程预](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/recognition.md)测看看

**Comment by chc-stars** [comment]
就是在训练自己的模型是不用加自己的字典。
![image](https://user-images.githubusercontent.com/76056473/211238708-81cbd38f-6685-4e13-ab33-4c4824ecd091.png)
