### ISSUE TITLE
服务化部署表格识别报错：IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8797]
搞了很久，识别失败
![image](https://user-images.githubusercontent.com/99126288/211001072-a9682399-108b-4317-99d3-9c5bcef7b2d6.png)

**Comment by an1018** [comment]
表示超出数组了，可以输出r.json()["results"]结果看看，如果为空，再使用[0]就会触发这类错误
