### ISSUE TITLE
linux宿主机容器正常推理，相同镜像，想通代码的windows 不能运行

### ISSUE THREAD

**Issue by wolfog** [PaddlePaddle/PaddleOCR#8798]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment: linux宿主机（系统fedora7.6)：中使用镜像，镜像中的系统是16.04
- 版本号/Version：paddle2.41,cuda 10.2，显卡驱动（440），显卡是2080
- 运行指令/Command Code：在linux 上的镜像ocr 推理完全没问题。但将容器commit ,save 成tar 文件之后，转移到window 系统。分别配置是win 10 家庭版，3070显卡，500多的驱动，11.6的cuda;win10 专业版3090显卡，527的驱动，cuda 12. 加载镜像，启动容器时报错。启动命令：docker run -it  --gpus all  pp_1205:v1 /bin/bash
- 完整报错/Complete Error Message：报的错误是
- "docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/e48cd5e1e4cb75d136b303db5c996b222458f86687be1dec4868c9e7e0e35ca2/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown"
-           ###################################### 目前采取措施  ######################################
- 1. 不添加--gpus  可以启动容器。不过容器里面只能使用cpu infer
- 2. 使用内容是 ：FROM <the image you care about>   RUN umount /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 && \
    rm -rf /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1  的Dockerfile 生成新的镜像，然后使用docker run -it  --gpus all  pp_1205:v2/bin/bash  可以启动容器，但是进入到容器中.ocr 模型可以加载成功，执行到ocr.ocr(“img_path") ，卡着不动，一直卡死。
-3. 在其他的linux 系统，上cuda 是11.2 可以正常启动容器，正常推理。

**Comment by an1018** [comment]
在windows上可以正确读取Img_path图片吗

**Comment by wolfog** [comment]
> 在windows上可以正确读取Img_path图片吗
1. 可以读取到。相同代码，我使用不带--gpus 启动，完全使用cpu 运行，可以得到结果。
2. 代码直接卡到ocr.ocr(img_path),不报任何错，也没有结果，使用crtl+c 都结束不了进程，就一直卡着。

**Comment by an1018** [comment]
那windows安装的是paddlepaddle还是paddlepaddle-gpu呢，可以在中断查看下是否检测到GPU，import paddle, paddle.utils.run_check()
