### ISSUE TITLE
多语言数据集(Multi-lingual scene text detection and recognition)

### ISSUE THREAD

**Issue by mppsk0** [PaddlePaddle/PaddleOCR#880]
这个无法下载，不知道是否有网盘可提供数据集

**Comment by WenmuZhou** [comment]
这部分数据集暂时没有开源哈

**Comment by mppsk0** [comment]
有日语韩语公开数据集吗？



---原始邮件---
发件人: "zhoujun"<notifications@github.com&gt;
发送时间: 2020年9月29日(星期二) 下午3:45
收件人: "PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送: "mppsk0"<602647289@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 多语言数据集(Multi-lingual scene text detection and recognition) (#880)




 
这部分数据集暂时没有开源哈

**Comment by xulihang** [comment]
目前日语的识别效果不是很好，我从日语网站上随便截一段图片进行识别，结果完全对不上

**Comment by littletomatodonkey** [comment]
目前多语言模型，大部分的训练集还是合成图像，所以训练出来的识别效果可能比较差，
