### ISSUE TITLE
发现日剧中开头和结尾夹杂着一些演员，赞助商信息的部分，会和字幕夹杂在一起，对识别产生影响？这种应该没法通过训练进一步改善吧？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8801]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.5  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://user-images.githubusercontent.com/41010669/211179003-4115b090-0c82-48b0-a795-26f92ba9a4e6.png)

**Comment by MissPenguin** [comment]
这种如果检测比较准确的话，识别可能也还好，因为前景的字幕基本把背景的都挡掉了，可以手动截一下看看识别效果，如果还OK，那就微调下检测模型。
