### ISSUE TITLE
paddleocr 识别英文，空格没了

### ISSUE THREAD

**Issue by songsh** [PaddlePaddle/PaddleOCR#8802]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 2019
- 版本号/Version：Paddle： 2.6.4  PaddleOCR： 2.6.1.1 问题相关组件/Related components：
- 运行指令/Command Code：paddleocr --image_dir=d:/download/"essd.pdf" --type=structure --table=false --ocr=true
- 完整报错/Complete Error Message：  识别英文，空格没有。
示例如下：
andnaturalchanges(Fig.2).Anunderstandingofthisper
turbationbudgetovertimeandtheunderlyingvariabilityand

**Comment by MissPenguin** [comment]
默认模型为中英文模型，可以使用专门的英文数字模型试试

**Comment by songsh** [comment]
请问，我在用python 代码  运行版面分析时
`table_engine = PPStructure(show_log=True, image_orientation=True)
save_folder = './output'
img_path = 'ppstructure/docs/table/1.png'`
报错：
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any
library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute,
but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by MissPenguin** [comment]
抱歉该问题无法复现，看着是环境问题，可以网上搜索下相关问题解决方案。
