### ISSUE TITLE
ERROR: paddle_serving_client-0.8.3-cp38-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8803]
python3.8.12，报错
![image](https://user-images.githubusercontent.com/99126288/211191838-4ecbf42f-4805-4dfe-93e7-f8138be4d499.png)

**Comment by tink2123** [comment]
试下： `python3.8 -m pip install xxx` 避免pip版本和python不一致
