### ISSUE TITLE
DB 训练/测试模型转推理模型时遇到了性能差异较大的问题

### ISSUE THREAD

**Issue by dhhcj1** [PaddlePaddle/PaddleOCR#8805]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu16.04
- 版本号/Version： Paddle：2.6  
- PaddleOCR： 问题相关组件/Related components：基于Python引擎的PP-OCR模型库推理
- 运行指令/Command Code：python3 tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_PP-OCRv3_det_infer/"
- 完整报错/Complete Error Message：推理模型结果与原模型结果差距较大

![image](https://user-images.githubusercontent.com/26638809/211002750-3594919a-ace6-4726-a0cf-54e2427affd3.png)
当使用模型为非示例模型时，推理结果就会变的非常差

以下为对比示例，当使用ch_ppocr_server_v2.0_det_infer.tar 服务端推理模型后的结果
![image](https://user-images.githubusercontent.com/26638809/211198958-fa3e584d-958a-47df-af8f-f9238561e89a.png)

使用ch_ppocr_server_v2.0训练/测试模型的推理结果如下所示
![image](https://user-images.githubusercontent.com/26638809/211198971-6d81d368-6265-4840-a71e-aa6e36ad73d0.png)

如使用示例推理模型（pp-ocrv3_infer）的结果,则较为正常
![image](https://user-images.githubusercontent.com/26638809/211199104-7a533ec2-5ea0-4826-ae86-e76cde2bc8be.png)

经多次测试发现使用**非示例模型后**的结果进行推理后，效果都普遍非常差

**Comment by MissPenguin** [comment]
ch_ppocr_server_v2.0和PP-OCRv3模型差了2个版本，性能差距较大，详情可查看PP-OCRv3技术报告：https://arxiv.org/pdf/2206.03001v2.pdf

推荐使用最新版的模型，如果仍无法满足需求，可以基于最新模型进行finetune。

**Comment by dhhcj1** [comment]
> 即便用了PP-OCRv3（无任何改动）推理模型和训练/测试模型在性能上还是有差距的呀，推理模型效果不太好
