### ISSUE TITLE
module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by AGUIAtNight** [PaddlePaddle/PaddleOCR#8806]
请提供下述完整信息以便快速定位问题/[Please provide the following information to quickly locate the problem]
使用下列网址提供的代码报告错误(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md)

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：module 'numpy' has no attribute 'int'
-解决方案/自1.20版本后，np.int已经废弃

**Comment by MissPenguin** [comment]
我们近期会对高版本的python和numpy进行适配，可以先试用低版本的哈
