### ISSUE TITLE
How are empty cells predicted by the Table Recognition Model? Empty Cells dont exist in the PubTabNet annotations.

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#8807]
In the PubTabNet dataset, there is no annotation of the boundingbox of an empty cell. However, the prediction of the table recognition model usually contains empty cells, since the number of the cell b-box should matched with the structure, so I'm wondering

The PubTabNet dataset doesn't include annotations for empty cell bounding boxes for some reason. However, when predicting, the results include the empty cells any way. 

1. How are empty cell bboxes predicted if there is no annotations for them in the dataset?
2. How is loss/accuracy calculated when training the table recognition model if empty cells are included in prediction results event though there are no bboxes for empty cells in the ground truth?
3. Lastly, when preparing a dataset to train the table recognition model, should I label empty cells? How can I train the model to be able to predict the empty cells well?

**Comment by johntoma** [comment]
Related issues:
- https://github.com/PaddlePaddle/PaddleOCR/issues/8686 @jerryyyyy708
- https://github.com/PaddlePaddle/PaddleOCR/issues/8679 @johntoma

**Comment by johntoma** [comment]
@LDOUBLEV can I please get a review of this ticket?

**Comment by WenmuZhou** [comment]
The number of tokens in the cell will be more than the box. In this case, more tokens will give a default box[0,0,0,0], but this kind of box does not participate in learning

**Comment by johntoma** [comment]
> 1. The number of tokens in the cell will be more than the box. In this case, more tokens will give a default box[0,0,0,0], but this kind of box does not participate in learning.
> 2. For blank cells, just give a box when marking, and leave a blank for the text part.

Thanks.

**Comment by johntoma** [comment]
@WenmuZhou after adding the empty cell boxes, do I need to reorganize the order of numbers? Or can I just leave it how it is?

Also, when adding empty cells, it automatically has a recognition result of "TEMPORARY". Can I leave it like that, or do I need to change it manually to blank text?

![image](https://user-images.githubusercontent.com/83645945/215631546-ae6cbf2a-6887-4464-87a2-eee7bb78949e.png)

**Comment by johntoma** [comment]
@WenmuZhou can I get an update on this please?
