### ISSUE TITLE
ImportError: libQt5Widgets-e69d94fb.so.5.15.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8808]
服务化部署失败，报错如上，共享库没有这个
![image](https://user-images.githubusercontent.com/99126288/211240102-9664acc1-cb5a-4fb5-a918-5ba93334959f.png)
![image](https://user-images.githubusercontent.com/99126288/211240090-c138bc4c-e4d8-4d37-9a91-f28740618b8a.png)

**Comment by LDOUBLEV** [comment]
重新安装opencv试试呢

**Comment by zyzz1974** [comment]
我已经安装过一遍，需要多少版本的？

**Comment by LDOUBLEV** [comment]
建议4.4版本的，我这边使用4.6版本的也正常

**Comment by zyzz1974** [comment]
好了，但是又出现这种情况SError: dlopen: cannot load any more object with static TLS
![image](https://user-images.githubusercontent.com/99126288/211249084-ffbfb067-3bf2-4111-a6c0-abfd7348fdbf.png)

**Comment by zyzz1974** [comment]
上面这个没有了这样算启动成功了吗
args config: {'rpc_port': 18091, 'http_port': 9998, 'worker_num': 10, 'build_dag_each_worker': False, 'dag': {'is_thread_op': False, 'retry': 10, 'use_profile': True, 'tracer': {'interval_s': 10}}, 'op': {'det': {'concurrency': 8, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': './ppocr_det_v3_serving', 'devices': '0', 'ir_optim': True}}, 'rec': {'concurrency': 4, 'timeout': -1, 'retry': 1, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': './ppocr_rec_v3_serving', 'devices': '0', 'ir_optim': True}}}}
[DAG] Succ init
[PipelineServicer] succ init

**Comment by LDOUBLEV** [comment]
看信息是启动成功了
[DAG] Succ init
[PipelineServicer] succ init

调用服务接口看下是否有输出

**Comment by zyzz1974** [comment]
还是报错了
![image](https://user-images.githubusercontent.com/99126288/211268507-70a06ee1-a209-4b66-a23b-306a594446f2.png)

**Comment by LDOUBLEV** [comment]
这个貌似是numpy的问题，可以看下这个issue：https://github.com/numpy/numpy/issues/8076

**Comment by zyzz1974** [comment]
还是没解决，numpy需要什么版本的？
