### ISSUE TITLE
Training Reproducibility

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#8811]
I tried adding seed in the config.yml and train 1 epoch then stop training and train 1 epoch again. i found that the weights are different, so how to fix any randomization and be able to reproduce the same model weights ? what else should i do other than the **seed** ?

**Comment by MohieEldinMuhammad** [comment]
@LDOUBLEV

**Comment by MohieEldinMuhammad** [comment]
@LDOUBLEV Any help please in reproducing the same training weights?

**Comment by LDOUBLEV** [comment]
The main reason is that there are some random factors in the training include[ random shuffle](https://github.com/PaddlePaddle/PaddleOCR/blob/8de2ebf25895a8e37c007e4662eec4423fc2a7d4/configs/det/det_mv3_db.yml#L101), [random aug](https://github.com/PaddlePaddle/PaddleOCR/blob/8de2ebf25895a8e37c007e4662eec4423fc2a7d4/configs/det/det_mv3_db.yml#L76-L84).

**Comment by mohiiieldin** [comment]
Is there a tested way to fix them all ? I tried making shuffle:false and adding a seed but didn't work.
