### ISSUE TITLE
win10 + vs 2019编译后拷贝到新机器无法正常运行

### ISSUE THREAD

**Issue by yzm0080** [PaddlePaddle/PaddleOCR#8815]
- 系统环境/System Environment：Windows 10
- 版本号/Version：Paddle：2.4  PaddleOCR：2.6 问题相关组件/Related components：编译
- 运行指令/Command Code：.\ppocr.exe --det_model_dir=models\ch_PP-OCRv3_det_infer --rec_model_dir=models\ch_PP-OCRv3_rec_infer --rec_char_dict_path=models\ch_PP-OCRv3_rec_infer\utils\ppocr_keys_v1.txt --image_dir=images\0_637734327212941583.jpg --use_angle_cls=false --det=true --rec=true --cls=false --benchmark=true
 
 按文档https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/docs/windows_vs2019_build.md在windows10下用VS 2019成功编译，开发机运行ppocr.exe正常，将其拷贝到win10新机器，没有安装vs2019，但安装了Visual C++ 2015-2019 Redistrbutable，运行时报错：应用程序无法正常启动(0xc0000142)
- 完整报错/Complete Error Message：
![微信图片_20230109204312](https://user-images.githubusercontent.com/21094690/211310734-def67168-d35f-4e51-8927-464a12273e4f.jpg)
拷贝到新机器的文件如下：
<img width="559" alt="微信截图_20230109204441" src="https://user-images.githubusercontent.com/21094690/211311050-4c3ddb9a-9f6a-4744-bea4-9c53d2d07d7b.png">
新机器已安装Visual C++ 2015-2019 Redistrbutable
<img width="288" alt="微信图片_20230109204608" src="https://user-images.githubusercontent.com/21094690/211311165-16df9241-7975-47fd-8907-180d16952c0c.png">

rec.bat文件内容：
`.\ppocr.exe --det_model_dir=models\ch_PP-OCRv3_det_infer --rec_model_dir=models\ch_PP-OCRv3_rec_infer --rec_char_dict_path=models\ch_PP-OCRv3_rec_infer\utils\ppocr_keys_v1.txt --image_dir=images\0_637734327212941583.jpg --use_angle_cls=false --det=true --rec=true --cls=false --benchmark=true`

**Comment by LDOUBLEV** [comment]
看不出报错原因，在新的机器上重新编译运行试试，如果报错了，可以把报错信息发出来一起看下
