### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8819]
Paddle Serving pipeline部署发送服务请求，报错
![image](https://user-images.githubusercontent.com/99126288/211520369-3eaabb6f-d7a8-4c4c-b560-7b9839341ac9.png)

**Comment by andyjpaddle** [comment]
检查下端口是否被占用，确保server端和client端能正常网络访问

**Comment by zyzz1974** [comment]
还是报错无法访问

**Comment by XxsSss** [comment]
你这个解决了吗请问 @zyzz1974
