### ISSUE TITLE
ImportError: libjpeg-183418da.so.9.4.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8820]
serving启动服务端报错
![image](https://user-images.githubusercontent.com/99126288/211564287-fb4add94-33a7-4048-ac0e-7ba97ddaad35.png)

**Comment by andyjpaddle** [comment]
看报错应该是环境问题，推荐使用python3.7进行准备环境
