### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle' (Using Horizon X3)

### ISSUE THREAD

**Issue by yatshunlee** [PaddlePaddle/PaddleOCR#8825]
Given that my settings are like the following:
- device: 地平线 Horizon X3 
- OS: linux aarch64
- python: 3.8

Every time I run `python3 setup.py install` in ~/PaddleOCR, the error appears.
May I know what I can do?

P.S. 
1. I have tried to install the paddlepaddle directly by `pip install paddlepaddle` but it doesn't work.
2. I have installed the paddlelite following this guide but I don't know how to run the Inference Model Optimization step.
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/lite/readme.md
3. At last, most importantly, I have tried to follow the guide here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme.md
but still showing the same error.

Many thanks

**Comment by tink2123** [comment]
You have to install paddlepaddle first, try to follow the install doc: https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html

**Comment by yatshunlee** [comment]
When run `make TARGET=ARMV8 -j$(nproc)`, I faced an error described in the following...

> [100%] Linking CXX executable protoc
[100%] Built target protoc
[  3%] Performing install step for 'extern_protobuf'
-- extern_protobuf install command succeeded.  See also /home/sunrise/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-install-*.log
[  3%] Completed 'extern_protobuf'
[  3%] Built target extern_protobuf
make: *** [Makefile:133: all] Error 2

do you have any idea why?
