### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#8827]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`docker镜像：paddlepaddle/paddle:latest-dev-cuda11.6.2-cudnn8.4.0-gcc82`
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：`python tools/infer/predict_system.py`
- 完整报错/Complete Error Message：
`
λ ubuntu /project/OCR/PaddleOCR python tools/infer/predict_system.py \
> --det_model_dir="output/inference/det_ch_db_res18_inference/" \
> --rec_model_dir="output/inference/rec_chinese_common_v2.0_inference/" \
> --use_angle_cls=false
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2023/01/11 09:42:07] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
E0111 09:42:07.865813   935 helper.h:114] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.
)
E0111 09:42:08.457574   935 helper.h:114] 4: [shapeCompiler.cpp::evaluateShapeChecks::1180] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: elementwise (Output: tmp_0379): dimensions not compatible for elementwise Condition '==' violated: 36 != 35.)
E0111 09:42:08.482718   935 helper.h:114] 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::operators::TensorRTEngineOp::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::operators::TensorRTEngineOp::PrepareTRTEngine(paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*) const
5   paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
6   paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1673430128 (unix time) try "date -d @1673430128" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 935 (TID 0x7f16e9cb2f40) from PID 8 ***]

Segmentation fault (core dumped)
`

![image](https://user-images.githubusercontent.com/45280752/211775251-17994c9f-39d8-4584-b85a-f6b367100f81.png)
![image](https://user-images.githubusercontent.com/45280752/211775740-11f7d3b1-d738-4ad6-8c16-5ca3ebaccb9f.png)

其他说明：
关闭tensorrt，不论使用GPU、CPU均正常
打开tensorrt，即`use_tensorrt=true`时，才会报上述错误

**Comment by LDOUBLEV** [comment]
使用的paddle预测库是否是待TRT的，https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#id2

**Comment by Biaocsu** [comment]
@LDOUBLEV  从PaddlePaddle官网下载的预测库，因此不带TRT，TensorRT是我自己从Nvidia官网下载安装的，已经安装成功了，上面有我的安装成功检测

请帮忙分析下原因，看到好多同样的issue，但是没有统一的解决方案

**Comment by Biaocsu** [comment]
@LDOUBLEV 根据您给的链接，是否需要我卸载掉paddlepaddle，然后安装带trt的paddlepaddle安装包？
我自己从nvidia官网下载安装的tensorrt为什么不行呢？是因为paddlepaddle支持性问题吗？

**Comment by Biaocsu** [comment]
> 使用的paddle预测库是否是带TRT的，https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python

1、卸载已有paddlepaddle安装包，根据上面链接安装带trt的paddlepaddle安装包，仍然出现前述相同报错
2、使用新的docker容器，镜像还是上述给出这个，重新操作一遍，仍然出现上述问题
这应该是一个bug了，该问题可复现

**Comment by Biaocsu** [comment]
@LDOUBLEV @tink2123 @sdcb @ZeyuChen 
请帮忙看下该问题，太多人遇到了，而且我这边可复现，应该是Bug

**Comment by LDOUBLEV** [comment]
需要重新安装带TRT的paddle
下载TRT压缩包，设置LD_LIBRARY_PATH为TRT的路径
TRT和带TRT的paddle安装参考文档，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/test_tipc/docs/install.md#32-%E5%AE%89%E8%A3%85tensorrt

安装待TRT版本的paddle也可以从我上面发你的链接里下载：https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python

**Comment by Biaocsu** [comment]
> 需要重新安装带TRT的paddle 下载TRT压缩包，设置LD_LIBRARY_PATH为TRT的路径 TRT和带TRT的paddle安装参考文档，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/test_tipc/docs/install.md#32-%E5%AE%89%E8%A3%85tensorrt
> 
> 安装待TRT版本的paddle也可以从我上面发你的链接里下载：https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python


你好，已经根据你的说明，下载带TRT的paddle，仍然出现了上述问题，你仔细看下我的描述
所以很困惑，目前不知道该怎么解决此问题

**Comment by Katherinaxxx** [comment]
> > 需要重新安装带TRT的paddle 下载TRT压缩包，设置LD_LIBRARY_PATH为TRT的路径 TRT和带TRT的paddle安装参考文档，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/test_tipc/docs/install.md#32-%E5%AE%89%E8%A3%85tensorrt
> > 安装待TRT版本的paddle也可以从我上面发你的链接里下载：https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python
> 
> 你好，已经根据你的说明，下载带TRT的paddle，仍然出现了上述问题，你仔细看下我的描述 所以很困惑，目前不知道该怎么解决此问题

请问解决了吗

**Comment by b4bbuilder** [comment]
@Biaocsu you figure out a solution? Having the same problem.

**Comment by flow3rdown** [comment]
请问问题解决了吗？
