### ISSUE TITLE
在训练文本识别模型时遇到有关cudnn的问题

### ISSUE THREAD

**Issue by acl98** [PaddlePaddle/PaddleOCR#8829]
- 系统环境/System Environment：Windows10
- 版本号Paddle：2.4     PaddleOCR： 2.6   cuda：11.6   cudnn：8.4.1.5
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
- 完整报错/Complete Error Message：
python.exe- 无法找到入口
无法定位程序输入点 于动态接库
D: PaddlePaddleDeepLerning/Anaconda3/envs/paddle/Librany/bin/cudnn_adv_infer64_8.dll 上

相同的环境下进行文本检测模型训练时就不会出现问题。
但是两者都会在启动训练时输出一段信息提示cudnn版本问题，具体如下
W0112 09:10:59.558595   644 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
但是在anaconda prompt中输入conda list可以看到cudnn版本为8.4.1.5。这样的问题该如何解决？

**Comment by WenmuZhou** [comment]
卸载conda里的cudnn试一下呢

**Comment by acl98** [comment]
卸载后再下载吗？

**Comment by acl98** [comment]
> 卸载conda里的cudnn试一下呢

直接再conda命令行pip uninstall cudnn 吗？那之后如何重新下载？ 之前下载是在pip install paddlepaddle-gpu==x.x.x时自动下载的cuda和cudnn。

**Comment by acl98** [comment]
问题已经解决，将paddle框架版本回退至cudnn使用8.x.x以下的版本就可以了。
