### ISSUE TITLE
paddleocr中icdar2015数据转换错出现错误

### ISSUE THREAD

**Issue by xiatian114** [PaddlePaddle/PaddleOCR#8830]
输入：python gen_label.py --mode="det" --root_path="ch4_training_images" --input_path="ch4_training_localization_transcription_gt" --output_label="train_icdar2015_label.txt"

![image](https://user-images.githubusercontent.com/119492593/211965585-441b49d1-aee7-46a2-bd2c-0b689bd3513e.png)

结果报错：(PaddleOCR) D:\PaddleOCR\train_data\icdar2015\text_localization>python gen_label.py --mode="det" --root_path="ch4_training_images" --input_path="ch4_training_localization_transcription_gt
" --output_label="train_icdar2015_label.txt"
Traceback (most recent call last):
  File "gen_label.py", line 81, in <module>
    gen_det_label(args.root_path, args.input_path, args.output_label)
  File "gen_label.py", line 49, in gen_det_label
    out_file.write(img_path + '\t' + json.dumps(
UnicodeEncodeError: 'gbk' codec can't encode character '\xb4' in position 674: illegal multibyte sequence

这是为什么？

**Comment by xiatian114** [comment]
求

**Comment by WenmuZhou** [comment]
你的标注格式的gbk的，需要转成utf8

**Comment by xiatian114** [comment]
> 你的标注格式的gbk的，需要转成utf8

![image](https://user-images.githubusercontent.com/119492593/212064964-c7db056f-3209-41f6-a9e0-daa5bc790c61.png)

我用gen_lable.py转换的数据是这样子的，我感觉好像是错误的

不应该是：ch4_training_images/img_1.jpg	[{"transcription": "Genaxis Theatre", "points": [[377, 117], [463, 117], [465, 130], [378, 130]
