### ISSUE TITLE
fastapi  做语义实体识别SER 模型服务端 发现会 load 模型两次，而且配置也会被重置。

### ISSUE THREAD

**Issue by cumthxy** [PaddlePaddle/PaddleOCR#8831]
fastapi  做语义实体识别SER 模型服务端 发现会 load 模型两次，而且配置也会被重置。
模型已经是interface 模型。代码参照 kie/predict_kie_token_ser.py。

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/22782047/211970345-e041c17c-9dc8-40be-8ec7-b539e704227e.png">

**Comment by WenmuZhou** [comment]
使用了多线程吗

**Comment by cumthxy** [comment]
找到问题了。有相同问题的可以看看。
https://stackoverflow.com/questions/64003384/why-when-i-start-uvicorn-in-my-fastapi-service-does-my-configuration-method-run

**Comment by cumthxy** [comment]
> 使用了多线程吗

我的问题，我找到原因了
