### ISSUE TITLE
Recognition Model does not work with multiline

### ISSUE THREAD

**Issue by Prasanna-iq** [PaddlePaddle/PaddleOCR#8834]
Hi I'm trying to extract text from a below image. After fine tuning detection model i was able to get the below ROI but when running the REC model it does not predict the text.  
![image](https://user-images.githubusercontent.com/109642369/212003897-0c0824f6-55ce-4d44-89c5-9d82788abe74.png)

**Comment by WenmuZhou** [comment]
I can directly use paddleocr to make predictions and get results. Can you see if the results of your detection model are correct?
![image](https://user-images.githubusercontent.com/12406017/212012748-c231c82a-1ef4-4da3-8445-8fc6e8e16c18.png)

**Comment by Prasanna-iq** [comment]
Hi, I want run only the REC model on the above image. 
The above image is the ROI after running the Detection model.

**Comment by Prasanna-iq** [comment]
@WenmuZhou , any update on this?

**Comment by WenmuZhou** [comment]
Multi-line recognition is currently not supported, you can use detection + recognition
