### ISSUE TITLE
convert layout  trained model files to inference.pdiparams model

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleOCR#8835]
When i use below models for inference the system automatically download new others models.
How to use my own trained model as i get below?

infer_cfg.yml
model.pdiparams
model.pdiparams.info
model.pdmodel

how to convert  above models to below models

inference.pdiparams
inference.pdiparams.info
inference.pdmodel

**Comment by WenmuZhou** [comment]
just rename

**Comment by TapendraBaduwal** [comment]
Dear @WenmuZhou  i am facing this issue when i use  inference.pdiparams,
inference.pdiparams.info ,inference.pdmodel models for layout analysis.

ValueError: (InvalidArgument) The conv2d Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2094)
  [operator < conv2d > error]
