### ISSUE TITLE
数学公式识别CAN动态图模型转静态图模型识别

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#8837]
windows系统，paddle版本2.1.3，使用最新的代码，使用的是官方的训练模型（动态图），一切命令参数，都按官方教程，运行tools/infer_rec.py动态图模型没问题

使用运行tools/export_model.py出错

错误信息定位为：

ppocr/modeling/heads/rec_can_head.py的312行
counting_mask=images_mask[:, :, : :self.ratio, : : self.ratio]

paddle库
paddle/fluid/framework.py的1683行的__getitem__
return _getitem_impl_(self, item)

paddle库
paddle/fluid/variable_index.py的135行_getitem_impl_
assert (step == -1)

**Comment by WenmuZhou** [comment]
问题重复，这个先关闭了
