### ISSUE TITLE
版面分析性能情况

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleOCR#8838]
版面分析，版面恢复等有性能测试对比吗? 我在cpu下测试，一张pdf版面分析需要接近10秒，有这么慢吗?

**Comment by WenmuZhou** [comment]
在文档里有性能说明的 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/PP-StructureV2_introduction.md

**Comment by kevinuserdd** [comment]
> 在文档里有性能说明的 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/PP-StructureV2_introduction.md

文档我看过，你这个文档里面在cpu下的性能真有这么好? 还是我哪里设置不对，我也是在cpu下面，我采用的就是table_engine = PPStructure(recovery=True)这个方案，然后推理加载，我这个测下来一张pdf接近10s；

**Comment by kevinuserdd** [comment]
> 在文档里有性能说明的 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/PP-StructureV2_introduction.md

或者有识别一张pdf的性能对比吗？ cpu下，识别一张pdf大概耗时多久？ 我测试的是一张pdf输入，经过版面分析，然后识别文字并输出文字结果，需要10s

**Comment by ATP-BME** [comment]
对扫描版的PDF进行版面恢复效果很差，基本没有恢复出原来的排版
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/1946067b-36e7-4912-8e60-8eb0e97d67b1)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110229267/94fff3bd-6404-45a0-b5a4-c8b15c7075ce)
使用的命令如下
predict_system.py --image_dir="E:/project/LM/知识注入/pdf/test/niujin1.pdf" --det_model_dir=inference/ch_PP-OCRv4_det_infer --rec_model_dir=inference/ch_PP-OCRv4_rec_infer --rec_char_dict_path="../ppocr/utils/ppocr_keys_v1.txt" --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_cdla_infer --layout_dict_path="../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt" --vis_font_path=../doc/fonts/simfang.ttf --recovery=True --output=../output/ --table=False --det_limit_type='max' --det_limit_side_len=3200
