### ISSUE TITLE
Image size when training Multilingual OCR model

### ISSUE THREAD

**Issue by enod** [PaddlePaddle/PaddleOCR#8845]
Hi everyone! 

Generic question: When training PP-OCRv3 Multilingual model - what was the image size of the training data? 

I'm getting some performance downgrade issue when providing bigger image(300p) compared to smaller ones(72p).

**Comment by an1018** [comment]
image_shape: [48, 320, 3]， you can refer to this document for details https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/models_list_en.md#23-multilingual-recognition-modelupdating

![image](https://user-images.githubusercontent.com/19808900/212274745-3cf8cb8e-6186-4fb5-829b-9adf5dc14981.png)
