### ISSUE TITLE
SystemError: initialization of _message failed without raising an exceptio

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8849]
启动服务化部署报错
hub serving start -c config.json
![image](https://user-images.githubusercontent.com/99126288/212291855-62afc798-8ed9-4fec-9b83-5ea92c399abc.png)

**Comment by an1018** [comment]
请问这个解决了吗，看刚才那个close了

**Comment by zyzz1974** [comment]
解决了，感谢

**Comment by an1018** [comment]
好的，那先close了
