### ISSUE TITLE
为什么老是报错啊，我吐了

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8851]
yi一共报了40多个错了，是依赖版本不对吗，能不能有个所有依赖的版本列表啊![image](https://user-images.githubusercontent.com/99126288/212329756-929401b3-7191-4c50-8bc3-a558e6b62993.png)

**Comment by an1018** [comment]
这是安装什么报错？首页提供了requirements.txt
