### ISSUE TITLE
部署模型为什么要安装paddle

### ISSUE THREAD

**Issue by sticktoFE** [PaddlePaddle/PaddleOCR#8853]
你好，2.6版本能不能部署推理时不用安装paddle，看了下源码，在根目录下paddleocr.py中有一个 import paddle，下面也没发现使用的场景，能不能去掉

**Comment by huangjun12** [comment]
模型推理时，需要使用paddle的推理引擎

**Comment by sticktoFE** [comment]
这样android平板就没办法做开发了？
