### ISSUE TITLE
paddleocr中gen_lable.py对icdar2015数据转换有误

### ISSUE THREAD

**Issue by xiatian114** [PaddlePaddle/PaddleOCR#8855]
![image](https://user-images.githubusercontent.com/119492593/212064964-c7db056f-3209-41f6-a9e0-daa5bc790c61.png)

我用gen_lable.py转换的数据是这样子的，我感觉好像是错误的

不应该是：ch4_training_images/img_1.jpg	[{"transcription": "Genaxis Theatre", "points": [[377, 117], [463, 117], [465, 130], [378, 130]

**Comment by huangjun12** [comment]
是指相对路径不对嘛，是否在文件中指定路径时少了 `/`
