### ISSUE TITLE
关于实际训练图片的准备，有个疑问：现有模型已经能准确识别的图，还有没有必要准备？还是说，可以只准备识别有错误的图片追加进去训练？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8858]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

关于实际训练图片的准备，有个疑问：现有模型已经能准确识别的图，还有没有必要准备？还是说，可以只准备识别有错误的图片追加进去训练？

还有背景被其他字符干扰严重的图片，要不要加入到训练集合中去？
![image](https://user-images.githubusercontent.com/41010669/212535792-e5ed663f-cb72-43a1-ba37-b2414990e355.png)

**Comment by MissPenguin** [comment]
finetune时，一般建议按比例配置原始数据集/已经能正确识别的数据集和新增/易错数据，避免训偏了。你图中给出的这种case可以加到训练中，背景干扰还不算太大。
