### ISSUE TITLE
基于PaddleServing的服务部署可以部署表格识别模块吗

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8859]
看见教程只有ppocr，其他的模块不能用吗

**Comment by MissPenguin** [comment]
对的，Paddle Serving目前只适配了ppocr模型，如果要部署表格等其他模型，可以试试hub serving部署：https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/hubserving
