### ISSUE TITLE
Android Demo cannot work with other recognition model

### ISSUE THREAD

**Issue by lingerlman** [PaddlePaddle/PaddleOCR#886]
Hi, the android demo is working with the default recognition model  (ch_rec_mv3_crnn_opt.nb) in 
https://paddleocr.bj.bcebos.com/deploy/lite/ocr_v1_for_cpu.tar.gz 
However, if I replace the recognition model with some other Chinese or English models. The app will crush during the loading model part.  For example these models down below. I also tried to convert by myself and got the same problem.  What is the difference between these models and the one in ocr_v1_for_cpu.tar.gz. Thanks for help.

https://paddleocr.bj.bcebos.com/20-09-22/mobile/lite/ch_ppocr_mobile_v1.1_rec_quant_opt.nb
https://paddleocr.bj.bcebos.com/20-09-22/mobile-slim/en/en_ppocr_mobile_v1.1_rec_quant_opt.nb

**Comment by LDOUBLEV** [comment]
Sorry, about your problem. The Paddle-Lite inference  library of android demo is a bit outdated, and our newly provided  `V1.1`  model  requires new Paddle-Lite inference  library.  I will update the document later.

**Comment by lingerlman** [comment]
Thank you. could you release a new paddle-lite inference library in android demo that can work with v1.1 models.

**Comment by llf10811020205** [comment]
@LDOUBLEV  the same problem

**Comment by Vane101** [comment]
Good day, has there been any update on this? Trying to add the English model

**Comment by skydev66** [comment]
@LDOUBLEV 
Is there any updated model that supports other languages like Russian, Japanese, French.

**Comment by MissPenguin** [comment]
Android demo works well with latest code. Please pull and try the latest code. If you still have any problems, please reopen it at any time and we will continue to follow up.
