### ISSUE TITLE
PPOCRLabel无法导出多行文本识别结果

### ISSUE THREAD

**Issue by lddcdut** [PaddlePaddle/PaddleOCR#8860]
图片如下
![phone](https://user-images.githubusercontent.com/43358822/212598287-912e0917-2709-4ae0-87f8-a07cd034010c.png)
需要识别其中的软件信息
![image](https://user-images.githubusercontent.com/43358822/212598326-4d85126a-4f05-41f1-982c-e3e2258f6d47.png)
在PPOCRLabel识别完成后选择-导出识别结果
![image](https://user-images.githubusercontent.com/43358822/212598388-6f7455b0-fe21-4de6-b550-05fe7a15ec35.png)
本地的rec_gt.txt以及crop_img中均无内容
如果只框选一行文本，则可以正常导出结果

Windows 10
paddleocr                      2.6.1.2
PPOCRLabel                     2.1.3

**Comment by Evezerest** [comment]
请单行标注
