### ISSUE TITLE
1.辨識模型訓練後轉為推理模型，測試結果不一致2.轉推理模型圖片測試有問題

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#8863]
作者您好
有兩個問題想詢問
### **1.辨識模型訓練後轉為推理模型，測試結果不一致**

系统环境：windows 10
PaddleOCR-release-2.6
在anaconda虛擬環境去跑指令(不知道跟其他的會不會有差別所以提一下)
訓練繁體中文的rec模型chinese_cht_mobile_v2.0_rec
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/models_list_en.md

配置文件:rec_chinese_cht_lite_train.yml
配置文件自己生成的>python generate_multi_language_configs.py -l chinese_cht
字典路徑:ppocr/utils/dict/chinese_cht_dict.txt

訓練
python tools/train.py -c configs/rec/multi_language/rec_chinese_cht_lite_train.yml -o Global.pretrain_weights=./pretrain_models/chinese_cht_mobile_v2.0_rec_train/

轉換為推理模型
python tools/export_model.py -c configs/rec/multi_language/rec_chinese_cht_lite_train.yml -o Global.checkpoints=./output/rec_chinese_cht_lite/best_accuracy Global.save_inference_dir=./trained_infermodel/rec_chinese_cht_lite_30/ Global.load_static_weights=False

測試推理模型
python tools/infer/predict_rec.py --image_dir="train_data/test/arial40_chi_70.png" --rec_model_dir="./trained_infermodel/rec_chinese_cht_lite_30" --rec_char_dict_path=ppocr/utils/dict/chinese_cht_dict.txt

其中一張訓練資料
![image](https://user-images.githubusercontent.com/45616986/212654205-d3e4572e-0f04-4c00-85af-f37509d30eb5.png)
訓練模型結果
![image](https://user-images.githubusercontent.com/45616986/212654311-1d792c17-b964-410c-87d2-1ab34ee5b7f9.png)
推理模型結果 (應該是下面那個結果，上面的加了--rec_image_shape感覺不太可能是這個推理模型的結果)
![image](https://user-images.githubusercontent.com/45616986/212654464-90f7296f-0a4d-4844-93a4-89ad3ca73bca.png)

### **2.轉推理模型圖片測試都有問題**
用predict_system做測試(rec_model_dir改成我訓練後的rec model再轉infer的路徑，其餘的都是官方預設的model)
python ./tools/infer/predict_system.py --image_dir="../data/wiki/image/1.png" \
--det_model_dir="./inference/det/ml/Multilingual_PP-OCRv3_det_infer"  \
--rec_model_dir="./trained_model/rec_chinese_cht_lite_30" \
--cls_model_dir="./inference/cls/ch_ppocr_mobile_v2.0_cls_infer" \
--rec_char_dict_path="./ppocr/utils/dict/chinese_cht_dict.txt" \
--use_gpu=False \
--draw_img_save_dir="./inference_results/myinfer/"

測試結果會長這樣
![image](https://user-images.githubusercontent.com/45616986/212653542-99af48aa-16cc-486e-bd48-59fc76144eee.png)
txt
![image](https://user-images.githubusercontent.com/45616986/212653596-d86efa66-d1b5-483c-a2ad-c0444a211d01.png)

若都用原本的模型去測都非常正常
python ./tools/infer/predict_system.py --image_dir="../data/wiki/image/1.png" \
--det_model_dir="./inference/det/ml/Multilingual_PP-OCRv3_det_infer"  \
--rec_model_dir="./inference/rec/chinese_cht/chinese_cht_PP-OCRv3_rec_infer" \
--cls_model_dir="./inference/cls/ch_ppocr_mobile_v2.0_cls_infer" \
--rec_char_dict_path="./ppocr/utils/dict/chinese_cht_dict.txt" \
--use_gpu=False \
--draw_img_save_dir="./inference_results/infer/"

測試結果
![image](https://user-images.githubusercontent.com/45616986/212654989-bb78c869-0bc0-414c-a0e8-bfefccf60e67.png)

如果只用原本訓練跟測試資料及做的話也是如此
![image](https://user-images.githubusercontent.com/45616986/212656671-192e056a-e01d-4e02-9057-9840538913fa.png)
![image](https://user-images.githubusercontent.com/45616986/212656690-22395a17-5fca-45af-9164-cc7fdaf323fb.png)

**Comment by jingsongliujing** [comment]
推理模型用推理脚本去预测：infer.py

**Comment by 38weiying** [comment]
> 推理模型用推理脚本去预测：infer.py

沒看到這個腳本，請問這是在哪? 所以不是用tools/infer/predict_rec.py這個去預測的?

第二個問題我講清楚一點: 只要是det+rec(我的infer model)，就會導致detection出問題，detection的數量會變超少，甚至完全沒有
用這個方法改成我rec infer model的路徑也是如此
![image](https://user-images.githubusercontent.com/45616986/215315625-41b769e2-0087-4743-8951-448ec3d7ffe0.png)
![image](https://user-images.githubusercontent.com/45616986/215315404-670ab31d-0b88-4b90-b880-f0d54c87d8f7.png)
而如果不要rec，rec=False，detection會是正常的
正常來說，rec不會影響det才對吧
想請問要如何才能讓這個部分detection變正常?

**Comment by LDOUBLEV** [comment]
你好，如果使用的是非PP-OCRv3版本的配置文件，需要加上--rec_image_shape='3,32,320'，设置输入的高度是32，默认是--rec_image_shape='3,48,320'；这个会影响识别结果

关于第二个问题，detection的數量會變超少

预测时请设置drop_score=0.0，这个参数表示识别score低于设置drop_score值时，就不输出结果；设置为0，就不会有这个问题

**Comment by 38weiying** [comment]
> 你好，如果使用的是非PP-OCRv3版本的配置文件，需要加上--rec_image_shape='3,32,320'，设置输入的高度是32，默认是--rec_image_shape='3,48,320'；这个会影响识别结果
> 
> 关于第二个问题，detection的數量會變超少
> 
> 预测时请设置drop_score=0.0，这个参数表示识别score低于设置drop_score值时，就不输出结果；设置为0，就不会有这个问题

謝謝
加上--rec_image_shape='3,32,320' 確實有效果了，也有變得更好(對於predict_rec.py來說是變更好的)
而drop_score=0.0也讓有檢測到的結果都出來了

還有一個相關的問題
為什麼測單行的結果會跟測多行文字的的結果不一樣(也都是用我的rec infer model)
以**eMedicine**這個字為例

- 測單行的結果(predict_rec.py)
![image](https://user-images.githubusercontent.com/45616986/215467895-80284fdb-ed2c-47f5-903b-c6bcfbbcf3cb.png)
python tools/infer/predict_rec.py --image_dir="inference_results/2.PNG" --rec_model_dir="./trained_infermodel/wiki_large" --rec_image_shape='3,32,320' --rec_char_dict_path=ppocr/utils/dict/chinese_cht_dict.txt


- 測多行的結果(predict_system.py)
![3](https://user-images.githubusercontent.com/45616986/215468492-bf7b159e-5928-423d-a726-774acac17082.PNG)
![image](https://user-images.githubusercontent.com/45616986/215469751-41663ded-9e77-4d63-9be7-196d8f4767e3.png)

python ./tools/infer/predict_system.py --image_dir=“inference_results/3.PNG” --det_model_dir=“./inference/det/ml/Multilingual_PP-OCRv3_det_infer” --rec_model_dir=“./trained_infermodel/wiki_large” --cls_model_dir=“./inference/cls/ch_ppocr_mobile_v2.0_cls_infer” --rec_char_dict_path=“./ppocr/utils/dict/chinese_cht_dict.txt“ --rec_image_shape=‘3,32,320‘ --drop_score=0.0 --use_gpu=False

**Comment by 38weiying** [comment]
不好意思，再問個問題
問題4.
我使用python套件，不是用sourecode測試，發現結果是不一樣的(跟上個留言是同張圖)
cls_model_dir、det_model_dir、rec_model_dir放的東西是一樣的
detection數量不同，不過最嚴重的是文字辨識的結果實在差太多了
想請問是哪裡有少了什麼東西嗎?感謝

ocr_model_chitra_large = PaddleOCR(use_angle_cls=True,\
                             lang='chinese_cht',\
                             use_gpu=False,\
                             rec_image_shape="3,32,320",\
                             rec_char_dict_path="./PaddleOCR/ppocr/utils/dict/chinese_cht_dict.txt",\
                             rec_model_dir="./PaddleOCR/trained_infermodel/wiki_large/",\
                             drop_score=0.0)

img_path="./PaddleOCR/inference_results/3.PNG"
result_infer = ocr_model_chitra_large.ocr(img_path) 
print(result_infer)
![image](https://user-images.githubusercontent.com/45616986/215476389-0d5848bb-52d7-4b6c-afb2-305b305640b6.png)
