### ISSUE TITLE
Issue with the layout analysis

### ISSUE THREAD

**Issue by WalidHadri-Iron** [PaddlePaddle/PaddleOCR#8866]
Hi,

I am still new to using PaddleOCR and still having some troubles to use the right parameters and models. Yet, I am encountering an issue when it comes to performing the layout analysis on an image from a pdf file.

```python
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True, lang="en", ocr=True, table=False, layout=True)

save_folder = ''
img_path = 'page0007-117.png'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = 'doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```

![result](https://user-images.githubusercontent.com/69817617/212700964-d0fd199c-8db2-46e5-bae4-d93ab9927b24.jpg)

The boxes around the texts are not accurate. Any thoughts about this?

**Comment**:  When I use PaddleOCR for text detection and recognition I am able to get the correct boxes around the texts but not without the Layout Analysis.

**Comment by WalidHadri-Iron** [comment]
Any updates about this?

**Comment by johntoma** [comment]
@WalidHadri-Iron Did you find any work-around for this yet? I have the same issue as well.
