### ISSUE TITLE
Issue with the "<" character

### ISSUE THREAD

**Issue by erncnerky** [PaddlePaddle/PaddleOCR#8867]
I am trying to convert the following image to excel. It can not extract the cells include the "<" symbol. Is there anything I can do to extract all the cells properly?

paddleocr version 2.6.1.2

```
paddleocr --image_dir=ss.png --type=structure --lang='en'
```

![ss](https://user-images.githubusercontent.com/13177658/212711403-1d9db31c-ad7c-4728-a3da-f7396faa9ba7.png)

**Comment by LDOUBLEV** [comment]
Seems like the results of paddleocr is right
paddleocr             2.6.0.1
paddlepaddle          2.3.2

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/26592129/215399132-feb9ffcd-144a-4340-9f6c-673983931b3c.png">

**Comment by erncnerky** [comment]
> It seems that the result of paddleocr is correct for me paddleocr 2.6.0.1 paddlepaddle 2.3.2
> 
> <img alt="image" width="1029" src="https://user-images.githubusercontent.com/26592129/215399132-feb9ffcd-144a-4340-9f6c-673983931b3c.png">

How did you generate the output? Did you use the CLI? If so, can you share it?
