### ISSUE TITLE
SER Inference

### ISSUE THREAD

**Issue by Prasanna-iq** [PaddlePaddle/PaddleOCR#8869]
How to pass the detection and recognition results of the OCR to the SER trained model instead of passing the entire image to get the output.

**Comment by andyjpaddle** [comment]
just specify the `Global.infer_img` to your results of OCR
refer to this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README.md#422-predict-images-using-the-trained-model

**Comment by Prasanna-iq** [comment]
This is with the trained model. I want to do it with the paddle Inference

**Comment by andyjpaddle** [comment]
sorry about that, currently it's not supported, we'll support it later.

**Comment by WenmuZhou** [comment]
It is not supported to directly pass in the result. Currently, a custom detection and recognition model is supported. The field is --det_model_dir， --rec_model_dir
