### ISSUE TITLE
RuntimeError: Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES via export CUDA_VISIBLE_DEVICES=cuda_device_id.  

### ISSUE THREAD

**Issue by zyzz1974** [PaddlePaddle/PaddleOCR#8870]
windows环境报错，已经尝试set CUDA_VISIBLE_DEVICES=0

**Comment by andyjpaddle** [comment]
运行命令是啥？

**Comment by zyzz1974** [comment]
hub serving start -c deploy/hubserving/structure_table/config.json

**Comment by andyjpaddle** [comment]
详细报错信息提供下

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212850491-8399fa24-30bc-414c-923e-f71ab61135c3.png)

**Comment by andyjpaddle** [comment]
看看 os.environ["CUDA_VISIBLE_DEVICES"] 有输出吗？

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212851011-bd7518d0-007d-40ab-8896-87f7a4b80a3e.png)

**Comment by andyjpaddle** [comment]
运行hub serving前要执行set CUDA_VISIBLE_DEVICES=0, 你这个是赋值

> ![image](https://user-images.githubusercontent.com/99126288/212851011-bd7518d0-007d-40ab-8896-87f7a4b80a3e.png)

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212852017-75bf6bea-b637-4e3f-9446-ad9ee4b11711.png)
zh这个我也试了

**Comment by andyjpaddle** [comment]
你执行完 set后，os.environ["CUDA_VISIBLE_DEVICES"] 有输出吗？对应报错的源码在这里 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/hubserving/structure_table/module.py#L55

**Comment by zyzz1974** [comment]
KeyError: 'CUDA_VISIBLE_DEVICES'

**Comment by zyzz1974** [comment]
该怎么办呢

**Comment by andyjpaddle** [comment]
好像是你的环境变量问题，正常set后是可以获得输出的，再试试 `set CUDA_VISIBLE_DEVICES=0 & hub serving start -c deploy/hubserving/structure_table/config.json`

**Comment by andyjpaddle** [comment]
你别用pycharm,就用Windows单独的终端试试呢？感觉是你环境变量没配置好

**Comment by andyjpaddle** [comment]
> 你执行完 set后，os.environ["CUDA_VISIBLE_DEVICES"] 有输出吗？对应报错的源码在这里 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/hubserving/structure_table/module.py#L55

先试试这个

**Comment by zyzz1974** [comment]
我在命令行的python版本和pycharm的不是同一个呢

**Comment by andyjpaddle** [comment]
推荐使用python3.7，先确保你的基础环境变量没问题（CUDA_VISIBLE_DEVICES能正确设置），再安装hub serving相关的环境

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212861885-b687bc0d-71c1-4ffd-80b9-9c64defa662e.png)
我用的是3.8

**Comment by zyzz1974** [comment]
在命令行成功部署

**Comment by zyzz1974** [comment]
[2023/01/17 17:38:05] ppocr INFO: 文件名称:1.jpg
[2023/01/17 17:38:10] ppocr INFO: json:<Response [200]>
[2023/01/17 17:38:10] ppocr INFO: Predict time of 1.jpg: 5.258s
Traceback (most recent call last):                             
  File "tools/test_hubserving.py", line 159, in <module>       
    main(args)
  File "tools/test_hubserving.py", line 121, in main
    res = r.json()["results"][0]
IndexError: string index out of range

**Comment by zyzz1974** [comment]
识别出现错误

**Comment by zyzz1974** [comment]
这是日志
![Uploading image.png…]()

**Comment by zyzz1974** [comment]
![image](https://user-images.githubusercontent.com/99126288/212863629-723c828e-cb50-4ab1-be07-83402669e6ec.png)

**Comment by Han-Y-F** [comment]
> [2023/01/17 17:38:05] ppocr INFO: 文件名称:1.jpg [2023/01/17 17:38:10] ppocr INFO: json:<Response [200]> [2023/01/17 17:38:10] ppocr INFO: Predict time of 1.jpg: 5.258s Traceback (most recent call last): File "tools/test_hubserving.py", line 159, in main(args) File "tools/test_hubserving.py", line 121, in main res = r.json()["results"][0] IndexError: string index out of range

请问解决了吗

**Comment by ahcQCQ** [comment]
may be ：我自己测试在pycharm终端确实也是同样提示 keyerror：‘cuda_visible_devices’，但是我在conda终端运行同样的命令可以运行，其他时候我也遇到了类似的情况，可见有可能是：pycharm终端 与 conda终端运行结果会有区别，尽量在conda终端运行命令行
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/145340717/e4c414c0-b27b-4b09-b358-fb4644ce1c35)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/145340717/2b8c1722-e132-4bbc-83c7-1198b19349a1)
