### ISSUE TITLE
ocr2.6SER + RE模型串联

### ISSUE THREAD

**Issue by zhangjuncheng24** [PaddlePaddle/PaddleOCR#8872]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
关键信息抽取中SER + RE模型串联出错
- 系统环境/System Environment：python3.8.0 paddle2.3.2 wind10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr2.6
- 运行指令/Command Code：
- python ./tools/infer_kie_token_ser_re.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./model/re_vi_layoutxlm_xfund_pretrained/best_accuracy Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o_ser Architecture.Backbone.checkpoints=./model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/111550104/213063785-28632fed-1a22-46cc-9ae9-860cf0266cdc.png)

**Comment by tink2123** [comment]
请尝试升级paddlenlp版本
