### ISSUE TITLE
Add pip option to skip PyMuPDF has very restrictive license

### ISSUE THREAD

**Issue by mattdeeperinsights** [PaddlePaddle/PaddleOCR#8873]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PyMuPDF has restrictive license for commercial use ([see here](https://pymupdf.readthedocs.io/en/latest/#license-and-copyright)), this is much more restrictive than PaddleOCR's Apache 2.0 license.

Currently this is only used for more complex PDF functionality that is not needed for OCR only. Would it be possible to add an option to not install this dependency and corresponding PDF usage?

**Comment by tink2123** [comment]
Thanks for the feedback, we will provide a solution as soon as possible.

If you need to remove the installation of PyMuPDF in the whl package, you can refer to [doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/whl_en.md#11-install-package) to recompile the whl package for use.

```
python3 setup.py bdist_wheel
pip3 install dist/paddleocr-x.x.x-py3-none-any.whl # x.x.x is the version of paddleocr
```

**Comment by mattdeeperinsights** [comment]
Thanks for getting back to me, much appreciated.

I will look into recompiling the whl for now and look forward to any updates :)

**Comment by felixgao** [comment]
is there a more detailed instruction? I tried to download the source and remove the pymupdf from the requirement.txt then built the wheel.  When I try to install the wheel. I still got the error.

`poetry add ~/intuit/github/opensource/PaddleOCR/dist/paddleocr-2.6.1.0-py3-none-any.whl`

```    
   note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for PyMuPDF
  Failed to build PyMuPDF
  ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects


  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│
      1542│         return decode(output)
      1543│
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/ggao/Library/Caches/pypoetry/artifacts/ce/7f/ee/41ed1e7a899c64438843759b3a42c991ae5365253ccb115893220fc7a9/PyMuPDF-1.19.0.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│
```

**Comment by imaurer** [comment]
Don’t go stale

**Comment by sjrl** [comment]
I would also be interested in having the ability to optionally not install PyMuPDF
