### ISSUE TITLE
Error while running train.py 

### ISSUE THREAD

**Issue by TasneemVKhan** [PaddlePaddle/PaddleOCR#8878]
Please provide the following information to quickly locate the problem

- System Environment: OS Windows11 
- Version：Paddle   PaddleOCR：2.6  Related components：
- Command Code：-train.py -c F:\PaddleOCR-2.6.0\configs\table\SLANet.yml 
- Complete Error Message：

""5</td></tr><tr><td>0.8</td><td>0.000</td><td>:</td><td>081</td><td>0.002</td><td>:</td><td>:</td></tr><tr><td>:</td><td>3600</td><td>0.91</td><td>0.00</td><td>*</td><td>*</td><td>Adjus
ted for SES</td></tr><tr><td>Adusted for SES Urbanur Sau</td><td>High</td><td>:</td><td>:</td><td>:</td><td>:</td><td>:</td></tr><tr><td>:</td><td>:</td><td>57</td><td>3.20</td><td>0.0
0</td><td>:</td><td>:</td></tr><tr><td>3.21</td><td>00.001</td><td>:</td><td></td><td></td><td></td><td>*</td></tr><tr><td>.</td><td>:</td><td>5</td><td>:</td><td>14185</td><td>5.</td>
<td>00015</td></tr><tr><td>1418</td><td>H</td><td>8.822</td><td></td><td>0.013</td><td></td><td>5.93</td></tr><tr><td>0006</td><td>:</td><td>:</td><td></td><td>1.</td><td>:</td><td>.</
td></tr><tr><td>ia</td><td>1763</td><td>1.21</td><td>0.00</td><td>1994c</td><td>1.21</td><td>00.001</td></tr><tr><td>Low</td><td>:</td><td>498</td><td>0.73</td><td>0.00</td><td>498</td
><td>n</td></tr><tr><td>0.001</td><td>:</td><td>528</td><td>0.82</td><td>0.0204</td><td>528</td><td>0.82</td></tr><tr><td>2196</td><td>0.91</td><td>a</td><td>.</td><td>0.0226</td><td>0
.83</td><td>0.0221</td></tr><tr><td>0.0243</td><td>588</td><td>0.83</td><td>0.255</td><td>0.ar</td><td>E</td><td>.</td></tr><tr><td>*</td><td>:</td><td>:</td><td>15</td><td>:</td><td>0"", error happened with msg: Traceback (most recent call last):
  File "F:\PaddleOCR-2.6.0\ppocr\data\pubtab_dataset.py", line 118, in __getitem__
    data = op(data)
  File "F:\PaddleOCR-2.6.0\ppocr\data\imaug\label_ops.py", line 675, in __call__
    bboxes[i] = bbox
ValueError: could not broadcast input array from shape (8,) into shape (4,)

![error1](https://user-images.githubusercontent.com/36981400/213381247-3bf225e3-6d15-4249-a19f-598827b99218.png)

**Comment by WenmuZhou** [comment]
use SLANet_ch.yml

**Comment by TasneemVKhan** [comment]
I tried running it with SLANET_ch.yml the following error
![error33](https://user-images.githubusercontent.com/36981400/213882259-7020f56a-07fc-44f7-9a54-acda751cad0e.png)

**Comment by TasneemVKhan** [comment]
When I run it with my own dataset it gives me this error
![error44](https://user-images.githubusercontent.com/36981400/213882464-6606510b-79e1-4858-977a-0d8fca34fdd3.png)

**Comment by TasneemVKhan** [comment]
I solved this error. Apparently I needed to label the empty cells also, it wasn't accepting it there were empty cells in the images.
