### ISSUE TITLE
DET 训练效率低

### ISSUE THREAD

**Issue by MikeDai2020** [PaddlePaddle/PaddleOCR#888]
我使用icdar2015数据集做demo 训练，GTX 2080上GPU load 最高31%，用其他数据集，只有20%左右，还有不少时间空闲，我将图片全部缩放为最大尺寸1280，改善了一些，但还是没有icdar2015快.有什么建议？谢谢！

**Comment by LDOUBLEV** [comment]
利用率低主要原因是模型太小，一共几兆的模型，GPU计算速度比图像预处理和后处理还快，利用率很难上去，提升分辨率、加大batchsize或许能改善一些，但是有限。

**Comment by MikeDai2020** [comment]
我直接把图片缩放到640x640，训练效率提升不少，1个iter从原来1.7s变为1.2s

**Comment by kasyoukin** [comment]
@LDOUBLEV ppocr里面的dataloader 多进程处理数据的效率很低，你可以单独测试下数据读取，我这读取一个batch的数据都快要1s了，我的python是3.6。多进程用的是队列而不是共享内存，所以很慢

**Comment by littletomatodonkey** [comment]
可以尝试使用paddle.io.Dataloader的接口，reader的效率会高一些，这块我们之后也会适配下
