### ISSUE TITLE
OCR识别错误

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#8880]
paddleocr==2.6.1.0

paddle ocr 识别，图片中的字母“F”被识别为“E”

`ocr  = PaddleOCR(use_angle_cls=True, lang='en',use_gpu=False,
                      det_limit_side_len=1280
                 )
img_path = 'IMG-20220304-WA0000.jpg'
preds = ocr.ocr(img_path, cls=True)
`

![image](https://user-images.githubusercontent.com/30545972/213481951-3436cd5a-4ad1-45a3-bb06-5b2b71bc44fb.png)

**Comment by jingsongliujing** [comment]
建议换精度更高的模型

**Comment by jack-gits** [comment]
现在使用的应该是精度最高的模型了吧。
@jingsongliujing 精度更高的模型是指？？

![image](https://user-images.githubusercontent.com/30545972/215369412-c8fef299-fbb6-4782-91a0-751a591049b6.png)

**Comment by jingsongliujing** [comment]
![image](https://user-images.githubusercontent.com/45508593/215380115-362038fe-0314-40f3-a557-f6c8b4475783.png)

这里建议用通用模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md

**Comment by jack-gits** [comment]
通用模型有v3版本吗？

**Comment by jingsongliujing** [comment]
你看截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] OCR识别错误 (Issue #8880)




 
通用模型有v3版本吗？

**Comment by jack-gits** [comment]
谢谢

**Comment by WenmuZhou** [comment]
感谢反馈，我们后续会进行针对优化

**Comment by jack-gits** [comment]
试了下大的模型，解决了F识别为E的问题。

大的模型发现另外一个问题，'W'识别为‘N'，但并不是所有的‘W’都识别为‘E’，只在其中一个图片中W被错误识别了； 
是不是可以参赛来改善呢？
![image](https://user-images.githubusercontent.com/30545972/215444269-3b6a0ec4-edbf-4041-b152-ba68cf780d43.png)

**Comment by jack-gits** [comment]
还发现对于半角括号的识别也有问题。
如果使用lang='en‘模型，括号无法识别，
如果使用lang='en'模型，半角括号被识别为全角括号。

![image](https://user-images.githubusercontent.com/30545972/215665665-ec33d547-2754-4036-8fac-b568db6d800b.png)

**Comment by jingsongliujing** [comment]
这个建议你预处理一下图片



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] OCR识别错误 (Issue #8880)




 
还发现对于半角括号的识别也有问题。
 如果使用lang='en‘模型，括号无法识别，
 如果使用lang='en'模型，半角括号被识别为全角括号。

**Comment by jack-gits** [comment]
怎么处理？
