### ISSUE TITLE
ValueError: (InvalidArgument) The conv2d Op's Input Variable Input contains uninitialized Tensor.

### ISSUE THREAD

**Issue by 4nish22** [PaddlePaddle/PaddleOCR#8883]
i am facing this issue when i use my own train layout analysis model
ValueError: (InvalidArgument) The conv2d Op's Input Variable Input contains uninitialized Tensor.
[Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2094)
[operator < conv2d > error]

Tested in paddlepaddle version 2.4.1 and 2.3.2 but still same error
PaddleDetection=latest code

**Comment by an1018** [comment]
Is there the same error when using our  provided pre-training models to infer？

**Comment by TapendraBaduwal** [comment]
@an1018 
I am also experiencing this issue when using my own trained layout analysis model, could you please assist me in resolving it?

I have already tested my layout analysis model in PaddlePaddle version 2.4.1 and 2.3.2, but I am still encountering the same error.
PaddleDetection=latest code

If i used your pre-training models to infer then there is no issue but if i finetune your pre-trained model then this issue raised.
My process to train layout analysis is:
Data collection and annotation using labelme tool.
Convert annotated data to coco formate using labelme2coco script.
Download PaddleDetection code and set pipeline with my dataset and coco annotated single json file.
Change 'configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml' file set data configuration and the number of categories.
In training the Best test bbox ap is is always 0 in my case.

**Comment by duyquang392** [comment]
When you export model with architecture: PicoDet  according to instructions at: [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README.md#71-Model-export](url) 
Output model has Arch: GFL resulting in faulty model initialization. 
I added `-o export.benchmark=False`  to the model export command. 
Output model will have Arch: PicoDet and the error has been fixed.
