### ISSUE TITLE
How to fix any randomness in the training ?

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#8884]
I tried adding a seed value, shuffle: false, num_workers:0, training only one epoch and saving the 2 resulting models in different dirs. Unfortunately the resulting models have different weights, how can I generate the same model weights?

**Comment by MohieEldinMuhammad** [comment]
@huangjun12 can you help me in making the training reproducible, please?

**Comment by huangjun12** [comment]
randomness may also exist in data preprocessing, such as random crop, random flip

**Comment by mohiiieldin** [comment]
Is there a list of all random factors in the code in order to fix them ? Is the randomness inevitable?

**Comment by MohieEldinMuhammad** [comment]
refer to #8965
