### ISSUE TITLE
ValueError: (InvalidArgument) The conv2d Op's Input Variable Input contains uninitialized Tensor

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleOCR#8885]
I am also experiencing this issue when using my own trained layout analysis model, could you please assist me in resolving it?

I have already tested my layout analysis model in PaddlePaddle version 2.4.1 and 2.3.2, but I am still encountering the same error.
PaddleDetection=latest code
If i used your  pre-training models to infer then there is no issue but if i finetune your pre-trained model then this issue raised.

My process to train layout analysis is:
1. Data collection and annotation using labelme tool.
2. Convert annotated data to coco formate using labelme2coco script.
3. Download PaddleDetection code and set pipeline with my dataset and coco annotated single json file.
4. Change  'configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml' file  set data configuration and the number of categories.
5. In training the Best test bbox ap is is always 0 in my case.

**Comment by johntoma** [comment]
@TapendraBaduwal Hi I'm getting the same error. Did you end up fixing the issue?

**Comment by duyquang392** [comment]
> @TapendraBaduwal Hi I'm getting the same error. Did you end up fixing the issue?

You can see how to fix it at:
[https://github.com/PaddlePaddle/PaddleOCR/issues/8883#issuecomment-1574675672](url)
