### ISSUE TITLE
PPOCR Label: Cannot recognize table in image. Please change manually 

### ISSUE THREAD

**Issue by TasneemVKhan** [PaddlePaddle/PaddleOCR#8886]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：OS Windows 11 
- 版本号/Version：Paddle: 2.4  PaddleOCR：2.6.0 
- 运行指令/Command Code：python PPOCRLabel.py 
- 完整报错/Complete Error Message：
![error23](https://user-images.githubusercontent.com/36981400/213881121-844484f0-7f43-4dff-84df-b07f7fd0674d.png)

**Comment by Evezerest** [comment]
这个是一个提示，可以看一下具体是什么图片，ocr没有识别出结果

**Comment by TasneemVKhan** [comment]
In a 2.1.2 version of PPOCRLabel it does recognize the image but the same image in a different version is not able to recognize it.
