### ISSUE TITLE
KeyError: 'algorithm'

### ISSUE THREAD

**Issue by QR-0W** [PaddlePaddle/PaddleOCR#8888]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
使用train.py训练识别模型的时候报错

- 系统环境/System Environment：Windows 11 专业工作站版 21H2
- 版本号/Version：Paddle：1.0.2  PaddleOCR：  2.6.1.2 问题相关组件/Related components：paddleocr\tools\program.py
- 运行指令/Command Code：python tools/train.py -c configs/det/det_r18_vd_db_v1.1.yml
- 完整报错/Complete Error Message：
`python tools/train.py -c configs/det/det_r18_vd_db_v1.1.yml`
_Traceback (most recent call last):
  File "C:\Users\Qr0w\.conda\envs\paddle_env\Lib\site-packages\paddleocr\tools\train.py", line 199, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "C:\Users\Qr0w\.conda\envs\paddle_env\Lib\site-packages\paddleocr\tools\program.py", line 639, in preprocess
    alg = config['Architecture']['algorithm']_
_KeyError: 'algorithm'_

**Comment by MissPenguin** [comment]
看你的配置文件还是1.1版本的，这是比较老的静态图版本，目前已经不维护了，可以更换到最新的2.6分支使用哈
