### ISSUE TITLE
如何对检测模型finetune，比如冻结前面的层或某些层使用小的学习率学习？

### ISSUE THREAD

**Issue by yeaf** [PaddlePaddle/PaddleOCR#889]

**Comment by LDOUBLEV** [comment]
如果是冻结某些层，可以将变量的stop_gradient属性设置为True，这样计算这个变量之前的所有参数都不会更新了，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/faq/train_cn.html#id4

如果对某些层使用更小的学习率学习，静态图里还不是很方便，一个方法是在参数初始化的时候，给权重的属性设置固定的学习率，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/param_attr/ParamAttr_cn.html#paramattr

实际上我们实验发现，直接加载模型去fine-tune，不设置某些层不同学习率，效果也都不错

**Comment by grasswolfs** [comment]
由于帖子时间较长时间没有进一步收到信息回复，暂时关闭，如果仍然有问题可以reopen
感谢对于PaddleOCR的支持

**Comment by planetb113** [comment]
> 

@LDOUBLEV  直接加载预训练模型fine-tune ，以paddlenlp 为例，它会冻结除了最后一层外其它的层参数的训练吗？是在源码里还是在文档里确认的呢？
