### ISSUE TITLE
Import Error: cannot import name 'Identity' from 'paddle.nn'

### ISSUE THREAD

**Issue by bvtradeoff** [PaddlePaddle/PaddleOCR#8890]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10 Google Colab CUDA 
- 版本号/Version：11.2 Paddle：2.4.1  PaddleOCR：2.6.1.2  问题相关组件/Related components：python:3.8, paddleclas:2.5.1,paddlepaddle:2.4.1,paddlepaddle-gpu 2.1.3.post112
- 运行指令/Command Code：N/A
- 完整报错/Complete Error Message：
- 
ImportError Traceback (most recent call last)
in
5 from paddleocr import PPStructure,draw_structure_result,save_structure_res
6
7 table_engine = PPStructure(show_log=True, image_orientation=True)
8
9 save_folder = './output'
/usr/local/lib/python3.8/dist-packages/paddleocr/paddleocr.py in init(self, **kwargs)
639 Path(file).parent / layout_model_config['dict_path'])
640 logger.debug(params)
641 super().init(params)
642
643 def call(self, img, return_ocr_result_in_table=False, img_idx=0):

/usr/local/lib/python3.8/dist-packages/paddleocr/ppstructure/predict_system.py in init(self, args)
47 self.image_orientation_predictor = None
48 if args.image_orientation:
49 import paddleclas
50 self.image_orientation_predictor = paddleclas.PaddleClas(
51 model_name="text_image_orientation")

/usr/local/lib/python3.8/dist-packages/paddleclas/init.py in
14
15 all = ['PaddleClas']
16 from .paddleclas import PaddleClas
17 from .ppcls.arch.backbone import *

/usr/local/lib/python3.8/dist-packages/paddleclas/paddleclas.py in
29 import paddle
30
31 from .ppcls.arch import backbone
32 from .ppcls.utils import logger
33

/usr/local/lib/python3.8/dist-packages/paddleclas/ppcls/arch/init.py in
20 from paddle.static import InputSpec
21
22 from . import backbone, gears
23 from .backbone import *
24 from .gears import build_gear

/usr/local/lib/python3.8/dist-packages/paddleclas/ppcls/arch/backbone/init.py in
75 from .variant_models.vgg_variant import VGG19Sigmoid
76 from .variant_models.pp_lcnet_variant import PPLCNet_x2_5_Tanh
77 from .variant_models.pp_lcnetv2_variant import PPLCNetV2_base_ShiTu
78 from .model_zoo.adaface_ir_net import AdaFace_IR_18, AdaFace_IR_34, AdaFace_IR_50, AdaFace_IR_101, AdaFace_IR_152, AdaFace_IR_SE_50, AdaFace_IR_SE_101, AdaFace_IR_SE_152, AdaFace_IR_SE_200
79

/usr/local/lib/python3.8/dist-packages/paddleclas/ppcls/arch/backbone/variant_models/init.py in
2 from .vgg_variant import VGG19Sigmoid
3 from .pp_lcnet_variant import PPLCNet_x2_5_Tanh
4 from .pp_lcnetv2_variant import PPLCNetV2_base_ShiTu

/usr/local/lib/python3.8/dist-packages/paddleclas/ppcls/arch/backbone/variant_models/pp_lcnetv2_variant.py in
1 from paddle.nn import Conv2D, Identity
2
3 from ..legendary_models.pp_lcnet_v2 import MODEL_URLS, PPLCNetV2_base, RepDepthwiseSeparable, _load_pretrained
4
5 all = ["PPLCNetV2_base_ShiTu"]

Import Error: cannot import name 'Identity' from 'paddle.nn' (/usr/local/lib/python3.8/dist-packages/paddle/nn/init.py) 

_**Training Environment.
1.Google Colab CUDA Version: 11.2
2.python 3.8
3.paddleclas 2.5.1
4.paddleocr 2.6.1.2
5.paddlepaddle 2.4.1
6.paddlepaddle-gpu 2.1.3.post112**_

**Comment by bvtradeoff** [comment]
Could you please provide update on this ?

**Comment by LDOUBLEV** [comment]
try: 
paddle.nn.layer.common.Identity

**Comment by LDOUBLEV** [comment]
pip uninstall paddlepaddle
pip uninstall paddlepaddle-gpu 
pip install paddlepaddle-gpu==2.4.1.post112
