### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

### ISSUE THREAD

**Issue by githubpaycon** [PaddlePaddle/PaddleOCR#8891]
when running with the code below:

from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True, lang='pt') # need to run only once to load model into memory
img_path = r'img.png'
result = ocr.ocr(img_path, det=True, cls=False)
for idx in range(len(result)):
     res = result[idx]
     for line in res:
         print(line)

The script displayed the error below:
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

I managed to fix it by changing from:
xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)

For:
xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int64), 0, w - 1)

Function path: venv/lib/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py/DBPostProcess -> box_score_fast

IN:
def box_score_fast(self, bitmap, _box):
         '''
         box_score_fast: use bbox mean score as the mean score
         '''
         h, w = bitmap.shape[:2]
         box = _box.copy()
         xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
         xmax = np.clip(np.ceil(box[:, 0].max()).astype(np.int), 0, w - 1)
         ymin = np.clip(np.floor(box[:, 1].min()).astype(np.int), 0, h - 1)
         ymax = np.clip(np.ceil(box[:, 1].max()).astype(np.int), 0, h - 1)

         mask = np.zeros((ymax - ymin + 1, xmax - xmin + 1), dtype=np.uint8)
         box[:, 0] = box[:, 0] - xmin
         box[:, 1] = box[:, 1] - ymin
         cv2.fillPoly(mask, box.reshape(1, -1, 2).astype(np.int32), 1)
         return cv2.mean(bitmap[ymin:ymax + 1, xmin:xmax + 1], mask)[0]

FOR:
def box_score_fast(self, bitmap, _box):
         '''
         box_score_fast: use bbox mean score as the mean score
         '''
         h, w = bitmap.shape[:2]
         box = _box.copy()
         xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int64), 0, w - 1)
         xmax = np.clip(np.ceil(box[:, 0].max()).astype(np.int64), 0, w - 1)
         ymin = np.clip(np.floor(box[:, 1].min()).astype(np.int64), 0, h - 1)
         ymax = np.clip(np.ceil(box[:, 1].max()).astype(np.int64), 0, h - 1)

         mask = np.zeros((ymax - ymin + 1, xmax - xmin + 1), dtype=np.uint8)
         box[:, 0] = box[:, 0] - xmin
         box[:, 1] = box[:, 1] - ymin
         cv2.fillPoly(mask, box.reshape(1, -1, 2).astype(np.int32), 1)
         return cv2.mean(bitmap[ymin:ymax + 1, xmin:xmax + 1], mask)[0]

**Comment by Syphixs** [comment]
Pretty sure that’s because ur jumpy version is too new. Try 
pip install numpy==1.23.0

**Comment by githubpaycon** [comment]
I believe this should work, unfortunately I don't have time to test it right now, but once I try it I will and I'll send you feedback ;)
