### ISSUE TITLE
FCENet效果巨差

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#8894]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.3  PaddleOCR：2.5 问题相关组件/Related components：训练效果不理想
- 运行指令/Command Code：python tools/train.py -c configs/det/our/det_res18_vd_dcn_fce_ctw.yml
- 完整报错/Complete Error Message：无
公开数据集CTW效果图：
![image](https://user-images.githubusercontent.com/76056473/214224341-e6977baa-c2d7-4c6c-b585-6856acbdda95.png)
![image](https://user-images.githubusercontent.com/76056473/214224391-fdacff67-50f5-42ab-b39f-80cb2205b817.png)
验证集结果图：
![image](https://user-images.githubusercontent.com/76056473/214224506-6ef90800-7717-45c7-afec-ef3cfdae4bc0.png)
训练epoch：1200

**Comment by chc-stars** [comment]
请问下圈中的thr指的是什么？
![image](https://user-images.githubusercontent.com/76056473/214224784-0377665a-ad5b-43de-8e7e-2cb83851e3ee.png)

**Comment by andyjpaddle** [comment]
训练数据有多少呢？有加载预训练模型吗

**Comment by andyjpaddle** [comment]
> 请问下圈中的thr指的是什么？ ![image](https://user-images.githubusercontent.com/76056473/214224784-0377665a-ad5b-43de-8e7e-2cb83851e3ee.png)

thr是得分阈值

**Comment by chc-stars** [comment]
没有，数据集就是CTW，训练1000，测试500.使用DB和EAST都能达到90以上，并且80多epoch就能收敛

**Comment by andyjpaddle** [comment]
用的是最新版2.6分支的代码训练的吗？有没有改动配置啥的？

**Comment by LDOUBLEV** [comment]
发布的模型配置文件是
configs/det/det_r50_vd_dcn_fce_ctw.yml
，参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/algorithm_det_fcenet.md

**Comment by chc-stars** [comment]
![image](https://user-images.githubusercontent.com/76056473/216798627-aad2ee5c-8204-4115-a838-40199c63dd18.png)
这种召回率很低是什么原因啊，我的数据集中每张图只有一个检测目标，并且是用四边形的四个点进行标注的，我看到召回率低的原因可能时，正样本被标为负样本，还有就是正负样本不均衡，但是我用DB，EAST网络检测的很好。我想问下是不是FCE网络是不是只针对弯曲文本，水平文本检测能力若，还是在标注是坐标点数太少的原因？

**Comment by chc-stars** [comment]
![image](https://user-images.githubusercontent.com/76056473/216876991-ba11acaf-12dc-4339-aa1e-fd6133660d3d.png)
zher这是在我自己数据集上跑500个epoch的精度，训练集上的测试，总共2700张，测出来的智勇1000张。
![image](https://user-images.githubusercontent.com/76056473/216877205-6a1313aa-9cf3-4541-9fc5-df5c0687e6ed.png)
