### ISSUE TITLE
PaddleDetection Model Arch for layout analysis

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleOCR#8896]
When model inference is complete then i get Model Arch: GFL 
------------------------------------------
-----------  Model Configuration -----------
Model Arch: GFL

But i want Model Arch: PicoDet
------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet

MY picodet_lcnet_x1_0_layout.yml file contain 
PicoDet:
  backbone: LCNet
  neck: CSPPAN
  head: PicoHead

But But after training i got infer_cfg.yml in which arch is GFL
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: GFL

**Comment by andyjpaddle** [comment]
you can create issue in https://github.com/PaddlePaddle/PaddleDetection repo
