### ISSUE TITLE
Q:Is there a method to export the output as a PDF file using Paddle?

### ISSUE THREAD

**Issue by 12seetharaman** [PaddlePaddle/PaddleOCR#8898]
It appears that, based on my review of the notebooks and documents, there is currently no support for PDF output, only input is supported. Please correct me if my understanding is incorrect. 
If there is no support for PDF output, is there a way to obtain a bounding box for each individual word?

**Comment by andyjpaddle** [comment]
you can add some code to process the output (eg, write output to a pdf) for PDF output
currently it is not supported for individual word bbox, you can obtain approximation bbox  according ctc output. we'll supported it in later version.

**Comment by 12seetharaman** [comment]
Thanks! @andyjpaddle 
To create the PDF output process, we need a word bbox to place the word in the exact position with its height and width.
How to get the bbox with ctc? Is there any documentation in English that guide me through ctc?

**Comment by andyjpaddle** [comment]
you can learn the principle of ctc and combine the postprocess code

**Comment by 12seetharaman** [comment]
Thanks @andyjpaddle
