### ISSUE TITLE
有多少人因为pull不下来而放弃了呢

### ISSUE THREAD

**Issue by jtcjump** [PaddlePaddle/PaddleOCR#89]
有多少人因为pull不下来而放弃了呢，docker 如何提速呢，有没有非docker使用
PaddleOCR 的方式呢

**Comment by LDOUBLEV** [comment]
不使用docker也是可以的，需要注意的是glibc的版本，目前的代码需要glibc=2.23，或许其他版本也是可以运行。

如果pull速度过慢，可以试试wget下载，具体细节在install.md 步骤 1

**Comment by BeyondYourself** [comment]
可以用码云上的托管，不用从github上Pull

**Comment by wen-small** [comment]
码云gitee导入github的仓库 再从gitee pull
