### ISSUE TITLE
GPU out of memory error 

### ISSUE THREAD

**Issue by tmartin98** [PaddlePaddle/PaddleOCR#8900]
Hello, 

Please help me with the following error code. The parameters of the dataloader are as follows and the image is resized as follows:

loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: true
    num_workers: 1
    use_shared_memory: true

RecResizeImg:
        image_shape:
        - 3
        - 32
        - 1024

PaddlePaddle version: 2.4.1
PaddleOCR version: 2.6
Python version: 3.9
Cuda version: 11.2
Cuddn version: 8.2

OSError: (External) CUDA error(2), out of memory.
[Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ..\paddle\fluid\platform\stream\cuda_stream.cc:45)

Currently we are using 1 node with 4 Nvidia a100 gpu's, but we can't increase the batchsize because we get an out of memory error.

Also I would appreciate any advice on how to use more nodes for paddleocr.

**Comment by tink2123** [comment]
> image_shape:（3,32,1024) 

The image shape setting is relatively large, maybe over your GPU memory, it is recommended to reduce batch_size or reduce the image shape appropriately
