### ISSUE TITLE
Is it impossible to detect individual words in PP-OCR?

### ISSUE THREAD

**Issue by rus0228** [PaddlePaddle/PaddleOCR#8902]
Is it impossible to detect individual words in PP-OCR?

**Comment by LDOUBLEV** [comment]
Can you provide the bad case sample?

**Comment by rus0228** [comment]
![Screen Shot 2023-01-31 at 2 48 35 PM](https://user-images.githubusercontent.com/53686457/215687867-3d17d061-2cb0-4a75-9e27-687726fe8104.png)

**Comment by rus0228** [comment]
This shows line level detection in PaddleOCR, which comes from 'DB' inference model with its detection algorithm.
Already in order to word level detect, I tried with SAST and EAST inference models and own detection algorithms.
However, it was not feasible accuracy for our case, so I am struggling to find a solution to word level detect in current 'DB' inference model and its detection algorithm.
Current model works for line level well.

**Comment by TuanBC** [comment]
Try the multilingual version of the detection model instead. That model was trained on MLT dataset, which was annotated in line-level, and seems to detect word level text better than the Chinese version.
