### ISSUE TITLE
Detect text orientantion (0, 90, 180. 270)

### ISSUE THREAD

**Issue by CuarteroAlvaro** [PaddlePaddle/PaddleOCR#8905]
I am using PaddleOcr to detect the orientation of the documents (0, 90, 180. 270). I have seen that you have a method (`text_classifier`) that relies on a binary model (0, 180 degrees). I have tried with images rotated at 90 degrees and the label of your model is 0 or 180 but then the text prediction comes out correctly. Is there any way to get the label (0, 90, 180, 270)?

**Comment by WenmuZhou** [comment]
you can use https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md

**Comment by CuarteroAlvaro** [comment]
Thank you so much!
