### ISSUE TITLE
LayoutAnalysis training giving 0 map

### ISSUE THREAD

**Issue by rsravan91** [PaddlePaddle/PaddleOCR#8907]
I am trying to funetune layout analysis model (picodet_lccnet_x1_0_layout) using few images (about 20).
The images are sample of publaynet. (The idea is just to see if the piece of code works for me).
I tried following the steps for training in https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure/layout

I am running on CPU and The training finished but the best model map is 0. 
Also I am not seeing the loss_vfl for each epoch being printed in the log.

I must be missing something here. Please help me !!

System Environment：
Mac OS Big Sur 
2.6 GHz 6-Core Intel Core i7
16 GB 2667 MHz DDR4

Version：Paddle：2.4.1  PaddleOCR： 2.6.1.2 

log:
[picodet_trainig.log](https://github.com/PaddlePaddle/PaddleOCR/files/10515856/picodet_trainig.log)

After inference on this new model the layout is predicting somewhere on the top !!
<img width="476" alt="image" src="https://user-images.githubusercontent.com/11389245/215012858-939b219a-8f0c-4aa9-a518-e89535a2e1fb.png">

**Comment by TapendraBaduwal** [comment]
@rsravan91 Can you provide the contents of the infer_cfg.yml file located in the output_inference/ directory? After Model Export ?

**Comment by rsravan91** [comment]
Attaching the infer_cfg (as yaml is not supported upload format, converted the yml to txt and exporting) as requested. 
[infer_cfg.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10517485/infer_cfg.txt)

**Comment by TapendraBaduwal** [comment]
@rsravan91 Dear friend just look at your infer_cfg.yml file the model arch is GFL 
model mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: GFL
min_subgraph_size: 3

But our Layout analysis Model Arch is PicoDet as follows
 ------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet

**Comment by rsravan91** [comment]
Thank you for helping @TapendraBaduwal . This is strange as I did train it on picodet_lcnet_x1_0_layout. Also if you see the log attached it does import weights from picodet_lcnet_x1_0_layout. Here is yml and data I used.
[examples.zip](https://github.com/PaddlePaddle/PaddleOCR/files/10518141/examples.zip)
[picodet_lcnet_x1_0_layout.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10518139/picodet_lcnet_x1_0_layout.txt)

**Comment by TapendraBaduwal** [comment]
@rsravan91 Dear friend, this is Model Configuration  issue in PaddleDetection .
Lets create issue in https://github.com/PaddlePaddle/PaddleDetection/issues repo

**Comment by TapendraBaduwal** [comment]
@rsravan91 Dear friend sry for late reply.

Change the name GFL to PicoDet in file  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/engine/export_utils.py#L191

And 
 In runtime.yml post_process change to False

Increase number of  train dataset 100 and val 30.
