### ISSUE TITLE
How is the empty cell trained and predicted by the table recognition model 

### ISSUE THREAD

**Issue by TasneemVKhan** [PaddlePaddle/PaddleOCR#8909]
I wanted to train the model for recognizing empty cells, however while doing table recognition it does not recognize empty cells. I have nearly 2000 images and it is nearly impossible to manually label the empty cells in the images. Is there a way I can do this with Paddle Paddle? 

System Environment: OS Windows 11  
Version：Paddle 2.4：  PaddleOCR：2.6.1.2

**Comment by TasneemVKhan** [comment]
@WenmuZhou Can you please look into this issue ?

**Comment by hoangtv2000** [comment]
Hi, I'm interested in your problem, too.

**Comment by hoangtv2000** [comment]
Hi Ms @TasneemVKhan, 
I have read that you labeled the empty cell boxes and it works, I'm wondering did you label the order of the cell boxes?
Thank you.
