### ISSUE TITLE
kie（ser）转onnx-是否支持onnx推理

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#8913]
- 版本号/Version：Paddle： 2.4  PaddleOCR：2.6   
- kie_algorithm=LayoutXLM
脚本/ppstructure/kiepredict_kie_token_ser.py  是否支持onnx推理

运行命令：python kie/predict_kie_token_ser.py --use_gpu=True --use_onnx=True --kie_algorithm=LayoutXLM --ser_model_dir=../inference/ser_onnx/model.onnx --image_dir=./docs/kie/input/zh_val_42.jpg --ser_dict_path=../train_data/bank/class_list_xfun.txt --vis_font_path=../doc/fonts/simfang.ttf --ocr_order_method="tb-yx"

**Comment by MissPenguin** [comment]
暂未进行适配，可能存在部分op不支持的问题，可以把具体报错信息贴到[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)的issue，会有专门的同学跟进。
