### ISSUE TITLE
Windows c++ paddleocr源码编译的dll，输出日志如何关闭

### ISSUE THREAD

**Issue by zhaocanglong** [PaddlePaddle/PaddleOCR#8916]
Windows11 CPU

文件                                          函数名                                                             代码
ocr_rec.cpp                          CRNNRecognizer::Run                                config.DisableGlogInfo();
[现象增加了config.DisableGlogInfo();指挥将paddle_inference中的日志是关闭不输出的。但是，执行时日志还是有输出。如何关闭。
具体内容：

The given version [10] is not supported, only version 1 to 7 is supported in this build.
e[37m---    fused 0 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
e[37m---    fused 0 elementwise_sub with relu activatione[0m
e[37m---    fused 0 elementwise_sub with tanh activatione[0m
e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_sub with swish activatione[0m
e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
e[37m---    fused 0 elementwise_sub with abs activatione[0m
e[37m---    fused 0 elementwise_sub with clip activatione[0m
e[37m---    fused 0 elementwise_sub with gelu activatione[0m
e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
e[37m---    fused 0 elementwise_mul with relu activatione[0m
e[37m---    fused 0 elementwise_mul with tanh activatione[0m
e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_mul with swish activatione[0m
e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
e[37m---    fused 0 elementwise_mul with abs activatione[0m
e[37m---    fused 0 elementwise_mul with clip activatione[0m
e[37m---    fused 0 elementwise_mul with gelu activatione[0m
e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m
e[37m---    fused 0 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
e[37m---    fused 0 elementwise_sub with relu activatione[0m
e[37m---    fused 0 elementwise_sub with tanh activatione[0m
e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_sub with swish activatione[0m
e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
e[37m---    fused 0 elementwise_sub with abs activatione[0m
e[37m---    fused 0 elementwise_sub with clip activatione[0m
e[37m---    fused 0 elementwise_sub with gelu activatione[0m
e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
e[37m---    fused 0 elementwise_mul with relu activatione[0m
e[37m---    fused 0 elementwise_mul with tanh activatione[0m
e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_mul with swish activatione[0m
e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
e[37m---    fused 0 elementwise_mul with abs activatione[0m
e[37m---    fused 0 elementwise_mul with clip activatione[0m
e[37m---    fused 0 elementwise_mul with gelu activatione[0m
e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m

**Comment by MissPenguin** [comment]
使用最新版的预测库，打开这行代码：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/src/ocr_rec.cpp#L176 
应该就可以了

**Comment by zhaocanglong** [comment]
> 使用最新版的预测库，打开这行代码：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/src/ocr_rec.cpp#L176 应该就可以了
我使用的就是最新的预测库，
cpu_avx_mkl   paddle_inference 2.3.2版本
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/cpp_infer/src/ocr_rec.cpp我现在的日志输出是加上了这个代码后的日志

**Comment by MissPenguin** [comment]
我这边下载最新预测库：
<img width="571" alt="image" src="https://user-images.githubusercontent.com/25809855/215480643-568fa5a2-d1bd-4b41-a7a8-eec2e3d47090.png">

打开代码注释，跑出来没有log了
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25809855/215480518-6c5ca2cf-74e3-4344-b64d-17a23ca26b74.png">

**Comment by zhaocanglong** [comment]
> 我这边下载最新预测库： <img alt="image" width="571" src="https://user-images.githubusercontent.com/25809855/215480643-568fa5a2-d1bd-4b41-a7a8-eec2e3d47090.png">
> 
> 打开代码注释，跑出来没有log了 <img alt="image" width="1439" src="https://user-images.githubusercontent.com/25809855/215480518-6c5ca2cf-74e3-4344-b64d-17a23ca26b74.png">

要不试试Windows版本的

**Comment by MissPenguin** [comment]
> > 我这边下载最新预测库： <img alt="image" width="571" src="https://user-images.githubusercontent.com/25809855/215480643-568fa5a2-d1bd-4b41-a7a8-eec2e3d47090.png">
> > 打开代码注释，跑出来没有log了 <img alt="image" width="1439" src="https://user-images.githubusercontent.com/25809855/215480518-6c5ca2cf-74e3-4344-b64d-17a23ca26b74.png">
> 
> 要不试试Windows版本的，基于cpu的

我没有windows机器😂。。那可能是windows版本预测库没有升级这个功能，可以去Paddle官网提个issue，有专门负责的同学跟进～
