### ISSUE TITLE
数据集划分的时候报错。报图片找不到。报错的路径有的问题。图片是在的

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#8922]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0

- 运行指令/Command Code：
数据集划分
 `python3 gen_ocr_train_val_test.py --trainValTestRatio 10:0:0 --datasetRootPath ../train_data/zzszyfp_v1`
- 完整报错/Complete Error Message：
`Traceback (most recent call last):
  File "gen_ocr_train_val_test.py", line 151, in <module>
    genDetRecTrainVal(args)
  File "gen_ocr_train_val_test.py", line 98, in genDetRecTrainVal
    splitTrainVal(root, recAbsTrainRootPath, recAbsValRootPath, recAbsTestRootPath, recTrainTxt, recValTxt,
  File "gen_ocr_train_val_test.py", line 52, in splitTrainVal
    shutil.copy(imagePath, imageCopyPath)
  File "/usr/local/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/train_data/zzszyfp_v1/crop_img\\zzszyfp_crop_17.jpg'`

**Comment by rexzhengzhihong** [comment]
![image](https://user-images.githubusercontent.com/32863094/215384101-29a2e106-57d7-4b71-8d2c-8b7a9b5332b5.png)
![image](https://user-images.githubusercontent.com/32863094/215384116-dd0060dc-a9d0-443a-aba4-b01abadd983c.png)

**Comment by LDOUBLEV** [comment]
> /home/DiskA/PycharmProjects/PaddleOCR-release-2.6/train_data/zzszyfp_v1/crop_img\\zzszyfp_crop_17.jpg

zzszyfp_v1/crop_img\\zzszyfp_crop_17.jpg

看样子是路径格式问题

**Comment by rexzhengzhihong** [comment]
对。但这个在哪里改呢？

**Comment by LDOUBLEV** [comment]
这里改下：https://github.com/PaddlePaddle/PaddleOCR/blob/0dc155669907f6b49354a68a3b83c833b9aadb35/PPOCRLabel/gen_ocr_train_val_test.py#L42
改为：
imagePath = os.path.join(dataAbsPath, "{}/{}".format(args.recImageDirName, imageName))

**Comment by rexzhengzhihong** [comment]
> 这里改下：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/0dc155669907f6b49354a68a3b83c833b9aadb35/PPOCRLabel/gen_ocr_train_val_test.py#L42
> 
> 
> 改为：
> imagePath = os.path.join(dataAbsPath, "{}/{}".format(args.recImageDirName, imageName))

谢谢

**Comment by rexzhengzhihong** [comment]
可以
