### ISSUE TITLE
使用PPOCRLabel kie是如何标注 linking 的

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#8923]
看了github对PPOCRLable的介绍：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md
但没具体看到KIE如何标注linking关系的。
 请问具体的操作方法是什么？ @andyjpaddle

**Comment by andyjpaddle** [comment]
目前还不支持标注linking关系

**Comment by leoterry-ulrica** [comment]
> 目前还不支持标注linking关系

那人工去修改label.json文件吗？

**Comment by rexzhengzhihong** [comment]
> 目前还不支持标注linking关系
那需要用其他的工具？不是手动去填吧

**Comment by rexzhengzhihong** [comment]
> 目前还不支持标注linking关系

那需要用其他的工具？不是手动去填吧

**Comment by TasneemVKhan** [comment]
I have the same question how to label dataset for SER model

**Comment by nilyang** [comment]
希望官方更新一下这个功能，比如，建立图表和图表标题的关联
