### ISSUE TITLE
如何在蒸馏的时候限制模型精度为 fp16？

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#8925]
RT

**Comment by LDOUBLEV** [comment]
为什么要在训练的时候限制精度为fp16，是为了加速训练？

**Comment by thsno02** [comment]
> 为什么要在训练的时候限制精度为fp16，是为了加速训练？

因为使用的 C++ 推理框架暂时不支持 fp32，后期从 fp32 转为 fp16 的话，担心某些地方精度溢出了 :(

**Comment by LDOUBLEV** [comment]
目前不支持转为fp16精度。

如果使用TensorRT加速预测，在预测的时候设置精度为fp16，不会太影响精度
