### ISSUE TITLE
Document Recovery Layout Model

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8927]
Hi Everyone, 
I trained layout analysis model using PaddleDetection with the following config file:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml

with custom dataset (only two labels instead of 5) and **Without FGD**
The model worked well when tested

and then I exported the model to inference using this command:

`python tools/export_model.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    -o weights=./picodet_lcnet_x1_0_layout/model_final \
    --output_dir=./picodet_lcnet_x1_0_layout/inference_v1`

and tested the model using `python3 deploy/python/infer.py` and that worked well too

However when using the same model with PPStructure command:
`python3 predict_system.py \
    --image_dir=../doc/imgs/economy-arial_page0.jpg \
    --det_model_dir=/paddle/models/inference/detection \
    --rec_model_dir=/paddle/models/inference/recognition \
    --rec_char_dict_path=/paddle/datasets/ocr_recognition/en_nums.txt \
    --table_model_dir=/paddle/models/inference/table \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_infer \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_dict.txt \
    --vis_font_path=../doc/fonts/Arial.ttf \
    --recovery=True \
    --output=../output/`

I get this error:
`InvalidArgumentError: The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2004)`

and when I replace the layout_model_dir with the official version from your repo it works well.

Can anyone help with that? 
1. is there a reason why it works in paddle detection and fails to work on paddle ocr? 
2. does it have anything to do with the FGD optimization?

Regards,

**Comment by bely66** [comment]
@ZeyuChen Any idea why this behavior occurs?

**Comment by TapendraBaduwal** [comment]
@bely66 Can you provide the contents of the infer_cfg.yml file located in the output_inference/ directory? After Model Export ?

**Comment by bely66** [comment]
I fixed it by adding -o export.benchmark=True export.nms=False when I'm exporting the model
It seems that It changes the input and output shape of the model

**Comment by vikhil0609** [comment]
Hii @bely66.
How did you trained the custom layout deection ?
Can you elaborate the process.
Thank you
