### ISSUE TITLE
PPOCRLabel经常崩溃

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#8928]
paddleocr2.6版本，python3.10版本，ppocrlabel2.1.3版本，在使用过程中经常出现这个错误，导致软件崩溃，致使花费大量时间标注的数据丢失。

QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "E:\gitrep\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by jingsongliujing** [comment]
建议直接clone源码下来：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel，在这个目录下运行：python PPOCRLabel.py
