### ISSUE TITLE
ppstructure表格识别输入尺寸

### ISSUE THREAD

**Issue by wanghan0501** [PaddlePaddle/PaddleOCR#8933]
请问，训练表格识别网络SLANet时候，没有用默认的488输入，而是使用768的图片大小输入，在运行tools/export_model.py和table/eval_table.py时候如何指定图片输入尺寸呢？

**Comment by andyjpaddle** [comment]
无需特殊指定，按照修改后的配置文件运行即可

**Comment by wanghan0501** [comment]
可是，table/eval_table.py推理的性能和在train过程中的性能差距过于巨大

**Comment by wanghan0501** [comment]
代码有误，解决了，谢谢
