### ISSUE TITLE
如何让各行的box识别结果按段落进行合并呢？

### ISSUE THREAD

**Issue by the-return-of-the-return** [PaddlePaddle/PaddleOCR#8936]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以根据坐标信息（行间距和首行缩进等规则）进行后处理

**Comment by the-return-of-the-return** [comment]
> 可以根据坐标信息（行间距和首行缩进等规则）进行后处理

PaddleOCR没有提供这个后处理吗？

**Comment by andyjpaddle** [comment]
没有

**Comment by the-return-of-the-return** [comment]
> 没有

明白了，谢谢
