### ISSUE TITLE
Detection Accuracy Drops in Layout Recovery

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#8937]
When using layout recovery on an image vs detection-recognition inference on the same image

The accuracy of detection drops (the boxes aren't as precise)

When I checked the images sent to detection from recovery I found a weird way of padding:
1. You make a black image as the size of the original image
2. you add the paragraph ROI image in the black image

you end up with the paragraph positioned at its original place in the text image however surrounded by black pixels

Original Image
![image](https://user-images.githubusercontent.com/29528270/215765750-d22bb034-c19c-4d41-a901-9a111d7bad99.png)

Cropped Image
![image](https://user-images.githubusercontent.com/29528270/215765595-7c140362-4ddb-40b9-b75a-cfc07d731705.png)

How would you overcome this issue or make detection more resilient to these changes?
Regards,

**Comment by bely66** [comment]
@andyjpaddle  any idea how i can do this?

**Comment by an1018** [comment]
After layout analysis, some layout areas are small, and  the effect of detection may not good, so we use image padding to get better detection effect

**Comment by bely66** [comment]
> After layout analysis, some layout areas are small, and the effect of detection may not good, so we use image padding to get better detection effect

Thanks for you reply @an1018  
I understand that, the nature of this padding is different from the model training data
is there a way to make the model resilient to these images? apply the same padding in training for example?

**Comment by an1018** [comment]
If using layout analysis, maybe you can try add some different size images to train text detection models,  because the shapes of layout regions are varies a lot

**Comment by bely66** [comment]
Okay thanks
