### ISSUE TITLE
跟随文档训练版面分析模型遇到的问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleOCR#8939]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：2.4.1  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
当文字比较长时检测框无法全部识别到，在labelme都是全部画进去的，请教一下这种情况该如何训练调正确
预训练模型用的picodet_lcnet_x1_0_fgd_layout_cdla.pdparams
epoch: 200  
ppdet.engine INFO: Best test bbox ap is 0.742.
跟着[pp-structure的[模型训练指南](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md)去做的

![4`8S)6ZZ(X)BWQN(7SAJN4R](https://user-images.githubusercontent.com/44227598/215679945-b3d8fc16-4185-4f81-872d-69fdf069c3c8.png)
![5DJ1CZU)JNG X{9RQM8_B1V](https://user-images.githubusercontent.com/44227598/215680100-ec5a18da-37df-44d3-8f0a-40f7a34987ed.png)

**Comment by jingsongliujing** [comment]
建议    ’：‘   前面加个分类’，因为发票除了购买方还有销售方的这几个抬头，上下这两个地方不好区分就会出现这种情况

**Comment by 1061302569** [comment]
> 这是检测框不够准确的问题，建议使用自己的数据finetune下检测模型

谢谢，finetune是不是用自己数据集重新画检测框
