### ISSUE TITLE
paddlepaddle和paddleocr版本兼容性问题

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#8940]
paddlepaddle：2.4.1
paddleocr：2.6.1.2

安装完paddlepaddle后，继续安装paddleocr，提示以下这个错误：
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.4.1 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.`

请问是不是paddlepaddle和paddleocr有版本对应关系？如何解决？

**Comment by jingsongliujing** [comment]
建议安装2.3：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by leoterry-ulrica** [comment]
> 建议安装2.3：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html

@jingsongliujing 换成paddlepaddle2.3版本，提示以下错误：
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.3.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.`

**Comment by leoterry-ulrica** [comment]
问题已解决

1. 安装paddlepaddle2.3.2版本
`python -m pip install paddlepaddle==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple`

3. clone paddleocr源码，进行先安装第三方库
`pip3  install -r requirements.txt -i https://mirror.baidu.com/pypi/simple`

4. 安装paddleocr
`python -m pip install paddleocr`

5. 验证
`paddleocr --image_dir ./dataset/13.png --use_angle_cls true`

**Comment by TapendraBaduwal** [comment]
@leoterry-ulrica 

use paddlepaddle = 2.3
In req.txt file 

numpy < 1.24
tqdm
typeguard
visualdl>=2.2.0
opencv-python <= 4.6.0
PyYAML
shapely
scipy
terminaltables
Cython
pycocotools
setuptools

# for vehicleplate
pyclipper
########
# for mot
lap
motmetrics
sklearn==0.0
filterpy
protobuf==3.19.5
grpcio==1.48.2
jinja2==3.0.0

**Comment by leoterry-ulrica** [comment]
> 



> @leoterry-ulrica
> 
> use paddlepaddle = 2.3 In req.txt file
> 
> numpy < 1.24 tqdm typeguard visualdl>=2.2.0 opencv-python <= 4.6.0 PyYAML shapely scipy terminaltables Cython pycocotools setuptools
> 
> #for vehicleplate pyclipper ######## #for mot lap motmetrics sklearn==0.0 filterpy protobuf==3.19.5 grpcio==1.48.2 jinja2==3.0.0

It worked out my way! thx~

**Comment by Mrfuhang** [comment]
> 2\. pip3  install -r requirements.txt -i https://mirror.baidu.com/pypi/simple
到第二步直接报错，安装不上

**Comment by DazzlingGalaxy** [comment]
@leoterry-ulrica @jingsongliujing 
conda新建的虚拟环境，我用下面的命令安装
```
pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
pip install paddleocr
```
然后报错
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle-gpu 2.4.2.post112 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.
```
此时查看版本是
paddleocr==2.6.1.3
paddlepaddle-gpu==2.4.2.post112

然后我卸载protobuf 3.20.3再安装3.20.0，报错
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
```

再卸载onnx和protobuf，再安装protobuf==3.20.0(发布于2022年4月2日)和onnx==1.12.0(发布于2022年6月18日，上个版本1.11.0发布于2022年2月18日)。由于装onnx时会自动装上protobuf导致protobuf装的版本高，所以先手动装protobuf再装onnx。都装好后测试了一次可以OCR识别(第一次运行时自动下载了几个文件)，但测试第二次时报错
```
ERROR in app: Exception on /bankticketocr [POST]
Traceback (most recent call last):
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "sfz_ocr_test.py", line 799, in bankticket
    return bank_ticket_ocr(img_file_path=img_file_path, shoukuan_name=shoukuan_name, shoukuan_bank_number=shoukuan_bank_number, shoukuan_bank_name=shoukuan_bank_name)
  File "sfz_ocr_test.py", line 709, in bank_ticket_ocr
    ocr = PaddleOCR(enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False, lang="ch")
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 523, in __init__
    super().__init__(params)
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/paddleocr/tools/infer/predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/root/miniconda3/envs/ocr_gpu/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) TensorRT is needed, but TensorRT dynamic library is not found.
  [Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.cc:47)
```

请问怎么解决？
另外这个问题是不是能和 #9292 关联起来？

**Comment by abbydev** [comment]
> @jingsongliujing 问题已解决
> 
> 1. 安装paddlepaddle2.3.2版本
>    `python -m pip install paddlepaddle==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple`
> 2. clone paddleocr源码，进行先安装第三方库
>    `pip3  install -r requirements.txt -i https://mirror.baidu.com/pypi/simple`
> 3. 安装paddleocr
>    `python -m pip install paddleocr`
> 4. 验证
>    `paddleocr --image_dir ./dataset/13.png --use_angle_cls true`

我也遇到同样的问题，你的python版本是多少，我的是python3.7，谢谢！

**Comment by DazzlingGalaxy** [comment]
补充，解决方法在 #9426
