### ISSUE TITLE
关于训练自己的数据集

### ISSUE THREAD

**Issue by truemaomao** [PaddlePaddle/PaddleOCR#8944]
请教一个问题，在训练自己的数据集的时候，会不会由于自己数据集的引入，带来原来识别效果的降低？比如用标准的模型识别汉字、字母和数字，发现实际应用中对某种字体的数字识别不是很好，然后自己做了一些这种字体数字的素材，随后进行训练。会不会因为这些特殊字体数字的引入，导致之前识别效果还可以的其他字体数字或汉字的识别效果下降？如果会的话，怎么解决这个问题呢？谢谢。

**Comment by tink2123** [comment]
尽量补充一些通用场景的数据和目标数据放在一起训练，在训练过程中使用较小的学习率，避免模型很快过拟合。

**Comment by truemaomao** [comment]
感谢回复。
您说的通用场景是不是就是ppocrv3标准模型训练时用的那些数据？那些数据应该规模很大是吧？这样的话对训练硬件的要求应该比较高吧？
还是说比如我只需要增加一些新的字体的数字识别，除了这种素材，我再找一些常规字体的数字作为补充，然后放在一起进行训练？比如目标数据和通用数据各1000个，这样也可以是吗？
就是说新的素材最好同时体现目标数据和常规数据，不用把训练标准模型的数据加上，只要新的素材中有目标数据和常规数据，用小的学习率训练基本就可以了？这样就避免了用大规模数据训练了。是这样吗？
谢谢。

>
