### ISSUE TITLE
训练 ser_layoutxlm_xfund_zh.yml 实体分类模型，eval.py  评估脚本 只评估一部分吗

### ISSUE THREAD

**Issue by liuyan20062010** [PaddlePaddle/PaddleOCR#8945]
用eval.py  评估训练的ser模型，结果准确率是1，但实际上有一个实体基本全部预测成other了，准确率不应该是1，然后我debug的时候，发现评估只对图片的第一个512序列块评估，我觉得不会有这么大的bug，不知道我忽略了什么，希望有了解的小伙伴指导一下。
![image](https://user-images.githubusercontent.com/35484984/215999387-50a8b356-d750-436d-9209-60c7752e4d29.png)
显示准确率是1；实际上一对key -value 预测成了other ;如下图
![image](https://user-images.githubusercontent.com/35484984/216000473-401dc753-2f29-436b-91fa-d7a713404625.png)

**Comment by liuyan20062010** [comment]
右仔细debug了，评估的时候，确实**_只评估每张图片的第一个512序列块_**，不知道是paddle故意的，还是一个bug，还是我漏掉了什么重要参数。不知道paddle的人能不能帮助一下

**Comment by liuyan20062010** [comment]
![image](https://user-images.githubusercontent.com/35484984/216256064-a27b300a-f3f1-4d28-a328-e7ed875e36c4.png)
用到的这个函数  只返回了 第0个，后面的都不要了

**Comment by liuyan20062010** [comment]
不是bug  ，故意的 ，如果需要所有的序列，需要自己修改

**Comment by WenmuZhou** [comment]
你好，当时做实现的时候没有想好>512的部分单独组batch的实现方式，如果你那边有好的实现方式欢迎pr

**Comment by liuyan20062010** [comment]
我在infer_kie_token_ser.py实现了评估，绕过了eval.py，不完美，但评估测试集可以了
