### ISSUE TITLE
弯曲文字检测与官方结果不一样

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#8946]
弯曲文字检测与官方结果不一样
- 系统环境/System Environment：win10
- 版本号/Version：
- Paddle：2.3.2.post112
- PaddleOCR：2.6 
- 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer_det.py -c D:\work\projects\paddleocr23\PaddleOCR\configs\det\det_r50_db++_icdar15.yml -o Global.pretrained_model=D:\models\seal_models\DB\best_accura
cy Global.infer_img=D:\imgs\seal_rec\8_1.jpg

官方提供的模型，配置文件如下：
Global:
  debug: false
  use_gpu: false
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_icdar15/
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: false
  pretrained_model:
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [False, True, True, True]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: DecayLearningRate
    learning_rate: 0.007
    epochs: 1000
    factor: 0.9
    end_lr: 0
  weight_decay: 0.0001
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 2.0
  det_box_type: 'poly' # 'quad' or 'poly'
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:\imgs\seal_rec\seal_labeled_datas
    label_file_list:                                                                                            
    - D:\imgs\seal_rec\seal_labeled_datas\Label.txt
    ratio_list:                                                                                                 
    - 1.0 
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 10
        keep_ratio: true
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 1
    num_workers: 1
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:\imgs\seal_rec\seal_labeled_datas
    label_file_list:
    - D:\imgs\seal_rec\seal_labeled_datas\Label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        image_shape:
        - 1152
        - 2048
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null

结果如下：

![24_1](https://user-images.githubusercontent.com/72127773/216002168-1c883f43-606f-4f53-84d7-1abd4bb07a81.jpg)

![26_1](https://user-images.githubusercontent.com/72127773/216002212-0a77a85f-a6db-4df4-8049-1ecfd68cae06.jpg)

请指正

**Comment by LDOUBLEV** [comment]
模型是你自己训练的还是用的官方的，你使用的配置文件的测试输入shape太大了
![image](https://user-images.githubusercontent.com/26592129/216038558-4de46282-906e-4047-8907-559337837fdc.png)


可以参考配置：
```
Global:
  debug: false
  use_gpu: true
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output_new_datasets/det_r50_total_text/
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: false
  pretrained_model: /paddle/PR/PaddleOCR/pretrain_models/ResNet50_dcn_asf_synthtext_pretrained
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage:
    - false
    - true
    - true
    - true
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: true
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: DecayLearningRate
    learning_rate: 0.007
    epochs: 1000
    factor: 0.9
    end_lr: 0
  weight_decay: 0.0001
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 2.0
  use_polygon: true
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/Seal_Image_Code/seal_datasets/
    label_file_list:
    - /paddle/Seal_Image_Code/seal_datasets/label_rotate_transform_final.txt
    - /paddle/Seal_Image_Code/seal_datasets/label_2_rotate_transform_final.txt
    - /paddle/Seal_Image_Code/seal_datasets/label_3_rotate_transform_final.txt
    ratio_list:
    - 1.0
    - 1.0
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 512
        - 512
        max_tries: 10
        keep_ratio: true
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/Seal_Image_Code/seal_datasets/
    label_file_list:
    - /paddle/Seal_Image_Code/seal_datasets/label_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        image_shape:
        - 512
        - 512
        keep_ratio: true
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null

```

**Comment by dengmingD** [comment]
> 

用的是官方的模型：PaddleOCR开源大礼包\《OCR产业范例20讲》模型库\印章检测与识别\seal_models\DB++\best_accuracy
改size后的结果还是不一样结果如下：
![13_1](https://user-images.githubusercontent.com/72127773/216204930-9d195543-f988-4788-816e-e12d85946dcb.jpg)
![24_1](https://user-images.githubusercontent.com/72127773/216204917-30befa19-5403-46b9-8b97-414ca154267c.jpg)
![8_1](https://user-images.githubusercontent.com/72127773/216204927-61d58dfb-2934-4681-bc9e-e00f0cfe532d.jpg)

**Comment by LDOUBLEV** [comment]
参数配置的问题，直接用我提供的配置文件试下

![image](https://user-images.githubusercontent.com/26592129/216214347-0b41c272-d68d-484e-af04-06218ce64d5c.png)

![image](https://user-images.githubusercontent.com/26592129/216214379-4987267e-65ae-42e0-af8b-c3f552e22c07.png)


![image](https://user-images.githubusercontent.com/26592129/216214470-20c6261c-4981-48c3-86b5-f833209b5a54.png)

**Comment by dengmingD** [comment]
> 参数配置的问题，直接用我提供的配置文件试下？ ![image](https://user-images.githubusercontent.com/26592129/216214470-20c6261c-4981-48c3-86b5-f833209b5a54.png)
> 
> ![image](https://user-images.githubusercontent.com/26592129/216214347-0b41c272-d68d-484e-af04-06218ce64d5c.png)
> 
> ![image](https://user-images.githubusercontent.com/26592129/216214379-4987267e-65ae-42e0-af8b-c3f552e22c07.png)
> 
> 对于弯曲框过于紧贴文字的问题，可以加大unclip_ratio这个参数调大检测框

用的就是你的config
Global:
  debug: false
  use_gpu: true
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output_new_datasets/det_r50_total_text/
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: false
  pretrained_model: /paddle/PR/PaddleOCR/pretrain_models/ResNet50_dcn_asf_synthtext_pretrained
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage:
    - false
    - true
    - true
    - true
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: true
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: DecayLearningRate
    learning_rate: 0.007
    epochs: 1000
    factor: 0.9
    end_lr: 0
  weight_decay: 0.0001
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 5.0
  use_polygon: true
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/Seal_Image_Code/seal_datasets/
    label_file_list:
    - /paddle/Seal_Image_Code/seal_datasets/label_rotate_transform_final.txt
    - /paddle/Seal_Image_Code/seal_datasets/label_2_rotate_transform_final.txt
    - /paddle/Seal_Image_Code/seal_datasets/label_3_rotate_transform_final.txt
    ratio_list:
    - 1.0
    - 1.0
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 512
        - 512
        max_tries: 10
        keep_ratio: true
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/Seal_Image_Code/seal_datasets/
    label_file_list:
    - /paddle/Seal_Image_Code/seal_datasets/label_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        image_shape:
        - 512
        - 512
        keep_ratio: true
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null

加大unclip_ratio这个参数的结果：


![24_1](https://user-images.githubusercontent.com/72127773/216215771-93854a65-20d1-4a38-8ba0-452a8317617e.jpg)

**Comment by LUXUS1** [comment]
修改代码：ppocr/postprocess/db_postprocess.py中
![image](https://user-images.githubusercontent.com/57226206/217160966-9e9080af-cef3-4729-9040-a8be05be5ed4.png)

**Comment by haimeilv** [comment]
我也遇到这个问题，请问如何解决？重新训练吗？

**Comment by haimeilv** [comment]
我也遇到这个问题，请问您解决了吗？我训练出来以后识别率只有20%多

**Comment by LUXUS1** [comment]
> 我也遇到这个问题，请问您解决了吗？我训练出来以后识别率只有20%多
将‘box_type’改为poly后就可以识别弯曲文本了

**Comment by haimeilv** [comment]
> db_postprocess.py
非常感谢您的指点，现在我的识别率到了72.9%

**Comment by dengmingD** [comment]
> 我也遇到这个问题，请问您解决了吗？我训练出来以后识别率只有20%多
修改代码：ppocr/postprocess/db_postprocess.py中
box_type='poly'

**Comment by xinxin19950423** [comment]
找到弯曲文件了，该如何识别呢

**Comment by wanggoudanscd** [comment]
请问官方模型可以发一下嘛

**Comment by SiriusWy** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/9431785/77c07426-7e96-421a-b6a0-e0d7ba6aba25)
找到这个参数，默认只能定位四边形，做如图修改就可以定位任意多边形了

**Comment by wangjiannan98** [comment]
您好，请问你这边PaddleOCR开源大礼包\《OCR产业范例20讲》模型库\印章检测与识别\seal_models\DB++\best_accuracy这个模型可以分享下不，现在好像找不到了

**Comment by dengmingD** [comment]
都在附件里



dm
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月28日(星期三) 下午2:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 弯曲文字检测与官方结果不一样 (Issue #8946)





 
您好，请问你这边PaddleOCR开源大礼包\《OCR产业范例20讲》模型库\印章检测与识别\seal_models\DB++\best_accuracy这个模型可以分享下不，现在好像找不到了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

DB++.rar (188.98M, 2024年09月29日 10:00 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=04353036bf530192543c7eb31230034941415301570752051457520e011d02560f511d530d01044b0d0d53050055505709500903343831227b1e1b184651436604&code=9506401f

**Comment by BUJIQI** [comment]
> 都在附件里 dm ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleOCR" ***@***.***&gt;; 发送时间:&nbsp;2024年8月28日(星期三) 下午2:11 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 弯曲文字检测与官方结果不一样 (Issue #8946) 您好，请问你这边PaddleOCR开源大礼包\《OCR产业范例20讲》模型库\印章检测与识别\seal_models\DB++\best_accuracy这个模型可以分享下不，现在好像找不到了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 DB++.rar (188.98M, 2024年09月29日 10:00 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=04353036bf530192543c7eb31230034941415301570752051457520e011d02560f511d530d01044b0d0d53050055505709500903343831227b1e1b184651436604&code=9506401f

你好，请问可以再分享一下这个模型吗><
