### ISSUE TITLE
revocer_to_doc.py中的bug

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleOCR#8949]
elif region['type'].lower() == 'title':
            doc.add_heading(region['res'][0]['text'])

这里的代码，region['res']可能出现的结果就是空的list，这样region['res'][0]就会报错

**Comment by an1018** [comment]
这里有异常抛出代码，可以看一下哈，https://github.com/PaddlePaddle/PaddleOCR/blob/b20014e89a2ae6b632b2cb2cf8d1910e80f74e07/ppstructure/predict_system.py#L293
