### ISSUE TITLE
如何获取【text_box_position】文本框位置？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleOCR#895]
请教：如何获取【text_box_position】文本框位置？

**Comment by dyning** [comment]
可以参考https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md，tools/infer/predict_system.py 识别结果中有识别的文本框内容和位置信息，请参考相关程序。

**Comment by 670133189** [comment]
> 可以参考[https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md，tools/infer/predict_system.py](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md%EF%BC%8Ctools/infer/predict_system.py) 识别结果中有识别的文本框内容和位置信息，请参考相关程序。

那么是如何获取文本的4个坐标，我计划根据4个坐标把文本截取出来存为图片。
