### ISSUE TITLE
使用UIE-X发现一个问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleOCR#8953]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：2.4.1  
- Paddle-nlp 2.5.0
在使用UIE-X设置好对应关系后，如果碰到空的不会显示为空，而是会去找下一行，这种情况应该如何避免呢，求各位老师看看
![1675332954519](https://user-images.githubusercontent.com/44227598/216297361-432cf42f-0dc1-4061-a607-368c93beee64.png)

**Comment by WenmuZhou** [comment]
这个建议提问到paddlenlp下

**Comment by cuyoo** [comment]
标注的时候，空行要补空标注。
