### ISSUE TITLE
debug  infer_kie_token_ser.py 脚本，只推理前512个token，剩余的token默认类别为0，即other，这肯定不好呀

### ISSUE THREAD

**Issue by liuyan20062010** [PaddlePaddle/PaddleOCR#8955]
debug  infer_kie_token_ser.py 脚本，只推理前512个token，剩余的token默认类别为0，即other；这显然不好呀；百度自己会用paddle吗

**Comment by liuyan20062010** [comment]
这个我改好了

**Comment by an1018** [comment]
赞，我们自己内部也会用的，发现问题可以共建开源

**Comment by huiyaoren** [comment]
> 这个我改好了

遇到了同样的问题 能请教一下这块是怎么解决的么

**Comment by Schawn** [comment]
> 这个我改好了

请问是怎么改的，我所有长图都只能ser识别一半不到

**Comment by jackieZhouQQ** [comment]
@liuyan20062010 修改方法可以分享一下吗
