### ISSUE TITLE
识别模型的finetune问题

### ISSUE THREAD

**Issue by chentianyangWHU** [PaddlePaddle/PaddleOCR#8957]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

这是一个finetune策略问题，不涉及报错。
需求描述：增强模型对某些特殊符号，如§等的识别能力
当前问题：使用文档推荐的最优识别模型rec/ch/ch_PP-OCRv3_rec_infer，几乎无法识别§（400+个中只正确识别出了1个，其余全部识别成了$,s,8,5等形似符号）
尝试的方法：我首先从自己的垂直领域数据中手动标注了7k条数据，再用生成工具根据垂直领域的语料生成了28k条数据，最后再用生成工具生成了35k条通用语料（来自人民日报语料库）数据，在使用图像生成工具的过程考虑到了字体、大小、颜色、噪声。我在这70k条数据中加入了符号§及其相似符号（$,s,8,5等），每个符号约1k条。预训练模型就是官方推荐的./pretrain_models/ch_PP-OCRv3_rec_train/best_accuracy。训练了30个epoch，验证集为2.8k条垂直领域真实场景下的数据，warmup_epoch=5，学习率为1.0e-05，其他参数都与ch_PP-OCRv3_rec_distillation.yml一致。
出现问题：这样finetune下来，§符号确实可以很好地识别，但是模型的泛化性显著降低，很多预训练模型能正确识别的汉字用finetune后的模型识别错误。最后的整体识别准确率反而明显降低。
原因分析：我看了一下，大多数无法识别的汉字都是因为训练数据中出现过少，也就是各字符在训练语料中不均衡导致的。但是要做到字符的均衡比较困难。
请教的问题：我现在只想让模型能多正确识别出“§”这个符号，并尽量不影响模型原来的泛化性。应该怎么做？感谢

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
数据比较多finetune后更加拟合当前数据分布，可以先尝试使用少量数据finetune

**Comment by chentianyangWHU** [comment]
> 数据比较多finetune后更加拟合当前数据分布，可以先尝试使用少量数据finetune
请问少量大概指的是多少呢？教程里说rec的finetune建议图像>=5000张、又说每个字符出现的次数大于等于200张，我如果只想让模型多识别3到5个特殊字符而且尽量不改变原模型的泛化性，是不是只用600-1000张就可以？感谢

**Comment by an1018** [comment]
可以先试试，如果字符识别效果不好可以再尝试增加图片数量

**Comment by huangxin168** [comment]
我觉得问题的根本是：
pretrained model的训练数据 vs 你的垂类数据，相差太大了（字体、风格、分布、场景、干扰等），因此注定是不能成功的。
如果想成功，应该看看pretrained model用的什么数据，合成类似风格的数据，然后两块数据按一定比例混合喂给finetune。
旧的记忆vs新的学习，不能相差太大，否则不会成功

**Comment by xiaotangwan** [comment]
你解决这个问题了吗？我也遇到了同样的问题

**Comment by zhonglifan** [comment]
微调pp-ocrv4也遇到了一样的问题，不知道有没微调顺利的大佬分享一下经验

**Comment by SleepEarlyLiveLong** [comment]
> 你解决这个问题了吗？我也遇到了同样的问题

后面直接用百万量级的生成数据作finetune，就用目标场景的语料库、确保字符均衡，然后向其中酌情增加需要增强的特殊字符。
这样做是因为中英文字符集很大（～6k个），假设100个文本行的平均长度是18个字符，那么每个字符就能被模型看见3000次（100w*18/6k=3k），对字符识别来说是足够了的，而且这样庞大的基数也更方便做少量指定字符（如$等）的增强。

**Comment by SleepEarlyLiveLong** [comment]
> 微调pp-ocrv4也遇到了一样的问题，不知道有没微调顺利的大佬分享一下经验

后面直接用百万量级的生成数据作finetune，就用目标场景的语料库、确保字符均衡，然后向其中酌情增加需要增强的特殊字符。
这样做是因为中英文字符集很大（～6k个），假设100个文本行的平均长度是18个字符，那么每个字符就能被模型看见3000次（100w*18/6k=3k），对字符识别来说是足够了的，而且这样庞大的基数也更方便做少量指定字符（如$等）的增强。
