### ISSUE TITLE
Training terminates itself 

### ISSUE THREAD

**Issue by TasneemVKhan** [PaddlePaddle/PaddleOCR#8958]
Please provide the following information to quickly locate the problem

System Environment：Windows11 OS 
Version：Paddle：2.4  PaddleOCR：2.1.3 Related components：
Command Code: python train.py -c F:\PaddleOCR-2.6.0\configs\kie\vi_layoutxlm\ser_vi_layoutxlm_xfund_zh.yml
Complete Error Message：
![error2](https://user-images.githubusercontent.com/36981400/216514870-49a4afe8-6327-4601-bec1-7e1563f4007e.png)

**Comment by an1018** [comment]
You can check that all the pics are correct

**Comment by TasneemVKhan** [comment]
I downloaded the dataset from the mentioned repository. I did check all the data. There is no error while opening it

**Comment by an1018** [comment]
XFUND dataset?

**Comment by TasneemVKhan** [comment]
Yes XFUND dataset

**Comment by an1018** [comment]
try set `num_workers=0` in yml  file

**Comment by an1018** [comment]
Could you use [AI Studio](https://aistudio.baidu.com/aistudio/projectoverview/public)  or other device to train the model with the same code and dataset, to help verify whethere there is any problem with the code

**Comment by TasneemVKhan** [comment]
I have tried it on another device and the training terminates itself.

**Comment by an1018** [comment]
what is the another device system?

**Comment by TasneemVKhan** [comment]
I tried it on a different PC of different configuration but didn't work. 

But I tried it on Google Colab and it works. 
But what could be the reason that it doesn't run on my Laptop? 

The specs of my Laptop are 
16GB RAM 
NVIDIA 2080RTX 
1TB SSD
