### ISSUE TITLE
求教一个目标定位不出的case的解决方法

### ISSUE THREAD

**Issue by tzhang001** [PaddlePaddle/PaddleOCR#896]
你好，我用ch_ppocr_mobile，ch_ppocr_server, ch_det_mv3, ch_det_r50去检测，像这种身份证首末位的目标，都没能检测出来，想问下有什么好的解决办法吗？包括：
1. 如果不finetune模型，能不能通过图像预处理来解决（比如，我发现如果只截取右边大约1/3图片的话，“* * * * 5” 能被检测出来，但是如果只截取左边大约1/3图片的话，“1 * * * *” 就检测不出来）
2. 如果finetune模型的话： a). 可以直接检测身份证首末位这一个目标就好是吧？b）.最好基于哪个模型来finetune呢？c). 大概要用多少样本呢？
期待大神们的回复~
<img width="451" alt="exp1" src="https://user-images.githubusercontent.com/1527413/95003609-8a567800-0613-11eb-8d00-71d1fb2e4398.png">

**Comment by littletomatodonkey** [comment]
你好，这个看着是检测框没有检测出来的问题，对于这种长文本，建议对检测模型进行finetune，数据量可以参考FAQ文档：
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/FAQ.md#q114%E7%AE%80%E5%8D%95%E7%9A%84%E5%AF%B9%E4%BA%8E%E7%B2%BE%E5%BA%A6%E8%A6%81%E6%B1%82%E4%B8%8D%E9%AB%98%E7%9A%84ocr%E4%BB%BB%E5%8A%A1%E6%95%B0%E6%8D%AE%E9%9B%86%E9%9C%80%E8%A6%81%E5%87%86%E5%A4%87%E5%A4%9A%E5%B0%91%E5%BC%A0%E5%91%A2

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
