### ISSUE TITLE
How to annotate my own dataset for KIE model using PPOCRLabel ? 

### ISSUE THREAD

**Issue by TasneemVKhan** [PaddlePaddle/PaddleOCR#8960]
Please provide the following information to quickly locate the problem

-System Environment：Windows OS 11 
-Version：Paddle: 2.4.1  PaddleOCR：2.1.3 
-Command Code：PPOCRLabel
-Complete Error Message：

**Comment by an1018** [comment]
Please refer to [this document](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/PPOCRLabel/README.md)

**Comment by TasneemVKhan** [comment]
I did but read the documentation, and tried the steps but my label.txt does not generate the label and id parameters

**Comment by an1018** [comment]
You can read the doc more carefully about [export-label-result ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README.md#33-export-label-result)

**Comment by smallhaozigithub** [comment]
PPOCRLabel seems to only support the annotation of ser, and does not support re to generate id and linking information.

**Comment by Rishi-NF** [comment]
has anyone found a way around this or a solution please??
