### ISSUE TITLE
paddleocr package使用问题，进行方向分类时导入90和270度图片时程序崩溃

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8963]
export出自己的模型后，按照官方给的API 可以正常推理预测0和180度的图片，但识别90和270度图片时程序崩溃。
use_angle_cls=True和cls=True均设置了
https://github.com/PaddlePaddle/PaddleOCR/blob/static/doc/doc_ch/whl.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B
![faee24e26f3120d94a2380505157e80](https://user-images.githubusercontent.com/80883358/216561849-4d2c6c2d-1e8d-45b6-8f57-cf251c6ed0bd.png)
paddleocr.py文件中说90和270也可以识别
![1675416477995](https://user-images.githubusercontent.com/80883358/216563381-9505adfe-6568-494b-9c9b-9f9b7902352d.png)

**Comment by Currf** [comment]
@LDOUBLEV

**Comment by an1018** [comment]
具体报什么错误，还有图片的尺寸

**Comment by Currf** [comment]
> 具体报什么错误，还有图片的尺寸

你好 图片尺寸为31*59
![2(1)(1)3_crop_0_270](https://user-images.githubusercontent.com/80883358/217418978-dec3c1a2-05a5-4074-96b0-dab1430d909d.jpg)
![1675825776289](https://user-images.githubusercontent.com/80883358/217419024-d4156b87-1625-4bba-8373-92a8c85de591.png)
但我yml文件label_list: ['0','90','180','270']
导入0和180都没问题，90和270报错

**Comment by Currf** [comment]
@an1018  看了下类似的问题，我跟他情况一样。但是predict_cls识别90和270都会报错，https://github.com/PaddlePaddle/PaddleOCR/pull/8091

**Comment by an1018** [comment]
上面截图错误是超出label_list，导出模型后，指定字典再试试，可以在报错代码处print(label_list)查看下

**Comment by Currf** [comment]
> 上面截图错误是超出label_list，导出模型后，指定字典再试试，可以在报错代码处print(label_list)查看下
> 
> 8091PR修复的是cpp推理代码

你好 我刚加入了label_list就成功了，感谢！
![1675844255886](https://user-images.githubusercontent.com/80883358/217473058-a5fa3a02-3ff0-44b7-9125-8ededa65fcb9.png)
