### ISSUE TITLE
How to freeze the model layers ?

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#8965]
I want to train a model with a custom dictionary but don't start from scratch so I want to freeze the backbone and neck layers and continue training on their weights, how to do this?

**Comment by MohieEldinMuhammad** [comment]
@an1018 any help please?

**Comment by an1018** [comment]
You can set the stop_gradient attribute of the variable to True, so that all the parameters before calculating this variable will not be updated

**Comment by mohiiieldin** [comment]
Thanks for replying
