### ISSUE TITLE
paddleocr不兼容noavx cpu

### ISSUE THREAD

**Issue by wtqcf** [PaddlePaddle/PaddleOCR#897]
在noavx cpu 环境下运行不下去,而且什么错误也不报.

**Comment by littletomatodonkey** [comment]
你好，目前官网上应该没有提供noavx的预测库~
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html


![image](https://user-images.githubusercontent.com/14270174/95443844-b06f7580-098f-11eb-869f-d2a1f7f3f0e0.png)

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
