### ISSUE TITLE
文字检测

### ISSUE THREAD

**Issue by H-eaven-1** [PaddlePaddle/PaddleOCR#8971]
利用深度学习做文字检测时，可以返回单个字符的位置信息（坐标）吗，如果是按行标注只能按行识别吗

**Comment by huangjun12** [comment]
目前检测返回的是字符串位置信息，基于分割的方法可以检测任意方向或者曲面形文字

**Comment by fanqie03** [comment]
字符检测：[https://github.com/fanqie03/char-detection/tree/main](https://github.com/fanqie03/char-detection/tree/main)
