### ISSUE TITLE
paddleocr C++ linux gpu部署 

### ISSUE THREAD

**Issue by dgx11678832** [PaddlePaddle/PaddleOCR#8976]
请问有没有paddleocr C++ linux gpu部署 的教程，或者使用方法教学视频，只搜到的咋Windows的教学。

**Comment by LDOUBLEV** [comment]
参考这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/readme_ch.md
