### ISSUE TITLE
paddleocr package 检测可视化只显示一个框

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#8977]
paddleocr版本为2.6.1.2
单独用检测的情况下，调用官方代码，只显示一个框
![1675653359659](https://user-images.githubusercontent.com/80883358/216876135-9876fd8f-504d-4112-accd-3ebc983e9b15.png)
![result](https://user-images.githubusercontent.com/80883358/216876227-f6d6eced-486c-434d-b995-d4f7df741932.jpg)
官方代码
https://github.com/PaddlePaddle/PaddleOCR/blob/static/doc/doc_ch/whl.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B
如果改为im_show = draw_ocr(image, result, txts=None, scores=None, font_path='/path/to/PaddleOCR/doc/simfang.ttf')
则各框会连起来，我只想全部显示预测框且不相连。
![result](https://user-images.githubusercontent.com/80883358/216876354-2b4fa01b-f17e-4d82-92fd-dfc8d0b612e1.jpg)

**Comment by Currf** [comment]
解决了 是paddleocr 2.6.1.2版本问题，换到2.6.0.1就好了，希望官方可以修复一下 谢谢

**Comment by LDOUBLEV** [comment]
感谢反馈，我们会定位下问题

**Comment by Currf** [comment]
> 感谢反馈，我们会定位下问题
感谢，请问这个可以帮忙看一下吗？感觉也像bug
https://github.com/PaddlePaddle/PaddleOCR/issues/8963

**Comment by Currf** [comment]
> > 感谢，请问这个可以帮忙看一下吗？感觉也像bug
> > #8963
