### ISSUE TITLE
鲲鹏920下，paddle-gpu 编译成功，开启gpu，paddleocr,文字识别不出，或者就是乱码。

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleOCR#8978]
![image](https://user-images.githubusercontent.com/57654726/216887562-ba1b660b-c8ef-4167-92b7-22bdd21c9860.png)，
关闭GPU
![image](https://user-images.githubusercontent.com/57654726/216887807-7b51e169-9320-4a46-b37f-c741e641b78f.png)

**Comment by LDOUBLEV** [comment]
这个问题有点奇怪，可能是paddle对鲲鹏920的适配有点问题，nvidia GPU上运行没问题
1. 先试试一个简单的分类网络，建议用mobilenetV3(同文字检测模型的backbone)，鲲鹏920上开启gpu运行，观察结果是否是对的
2. 如果有问题，那大概率是paddle的问题，如果没问题，再单独运行文字检测网络看下结果是否正常

**Comment by xialei2821212670** [comment]
文字检测用的是ch_PP-OCRv3_det_infer，开启GPU就检测不到文字.
![image](https://user-images.githubusercontent.com/57654726/217169129-36878192-e472-44ba-af26-3e4276576f5d.png)

**Comment by xialei2821212670** [comment]
![result_GPU_False](https://user-images.githubusercontent.com/57654726/217414933-598af36e-51a6-4fa3-a59a-796ba3cbefa0.jpg)
![result](https://user-images.githubusercontent.com/57654726/217414941-17cda609-a71f-4189-8b3c-2d8ee28705f8.jpg)
，分别测试了关闭显卡，和开启显卡。将结果显示出来就是这，显卡为T4，
![image](https://user-images.githubusercontent.com/57654726/217415162-47841a9d-f025-4ab8-918c-461d17ad84cb.png)

**Comment by xialei2821212670** [comment]
注意显卡架构

**Comment by 1tex** [comment]
> 
请问这个如何看是显卡架构的问题呢，我的情况如下：

一模一样，我在另一台3060上是正常的；在1070上GPU乱码，CPU正常。
你看下det阶段是不是直接框的就不对，我是直接框的就不对。

**Comment by 1tex** [comment]
> 注意显卡架构

请问这个如何看是显卡架构的问题呢，我的情况如下：

我在另一台3060上是正常的；在1070上GPU乱码，CPU正常。
det阶段画出的框的就是错误的。

请问可以帮我看下吗/(ㄒoㄒ)/~~，卡了三天了

![1](https://github.com/PaddlePaddle/PaddleOCR/assets/39019376/be68a621-029d-4664-b11d-5a6b5d1e9f8a)
![254](https://github.com/PaddlePaddle/PaddleOCR/assets/39019376/45073343-874f-4857-bdd7-ca7dbd0c2292)
![det_res_254](https://github.com/PaddlePaddle/PaddleOCR/assets/39019376/ef6f6d20-c4f2-45d7-8535-effbe5e682f0)
![det_res_1](https://github.com/PaddlePaddle/PaddleOCR/assets/39019376/376cc307-cf1c-40f5-8193-66320983f6d9)
