### ISSUE TITLE
镜像拉取后运行正常，重启容器后运行import出错，/python3.7/dist-packages/paddle/fluid/core_avx.so: file too short

### ISSUE THREAD

**Issue by gladiatorplus** [PaddlePaddle/PaddleOCR#8979]
- 系统环境/System Environment：镜像：paddlecloud/paddleocr:2.6-gpu-cuda11.2-cudnn8-36bf83
- 版本号/Version：Paddle：2.6  PaddleOCR： paddlecloud/paddleocr:2.6-gpu-cuda11.2-cudnn8-36bf83
- 完整报错/Complete Error Message：
Error: Can not import avx core while this file exists: /usr/local/lib/python3.7/dist-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "/home/PaddleOCR/paddleocr.py", line 21, in <module>
    import paddle
  File "/usr/local/lib/python3.7/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /usr/local/lib/python3.7/dist-packages/paddle/fluid/core_avx.so: file too short

**Comment by gladiatorplus** [comment]
出错时/usr/local/lib/python3.7/dist-packages/paddle/fluid/core_avx.so 文件大小为0。
也就是不知道为啥本地的镜像里的core_avx.so文件链接其本身依赖库失败了。。。。

**Comment by gladiatorplus** [comment]
![image](https://user-images.githubusercontent.com/62606831/216898162-eee4ae1d-ec52-4d90-8ee2-bfef3543e00d.png)
出问题以后，每次都是删掉原来的镜像重新拉就正常。一两天以后就又犯病了。。。

**Comment by LDOUBLEV** [comment]
可能是镜像的问题，报错后重新安装paddlepaddle试试

**Comment by gladiatorplus** [comment]
![image](https://user-images.githubusercontent.com/62606831/217125951-eadd479e-efe6-47b5-9e41-ad8e23116df7.png)

**Comment by gladiatorplus** [comment]
已解决
思路：
查看源码发现，paddlepaddle==2.4.1不在使用core_avx.so文件。直接升级到2.4.1版本就行。如下图。
![paddle1](https://user-images.githubusercontent.com/62606831/219543670-60dba7e8-1a54-45e4-b397-66a4969732ec.png)

参考：
基于`nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04`的镜像dockerfile:
```docker
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \   
echo "deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse" >/etc/apt/sources.list && \    
echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse" >>/etc/apt/sources.list && \  
echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse" >>/etc/apt/sources.list && \    
echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse" >>/etc/apt/sources.list && \
echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse" >>/etc/apt/sources.list && \    
echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse" >>/etc/apt/sources.list && \    
echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse" >>/etc/apt/sources.list && \    
echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse" >>/etc/apt/sources.list && \
echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse" >>/etc/apt/sources.list && \    
echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse" >>/etc/apt/sources.list
RUN apt-get update && apt-get install -y zlib* libffi-dev curl wget vim git unzip unrar tar xz-utils openssl libssl-dev bzip2 gzip net-tools libgl1
RUN apt-get install -y python3.8 python3.8-dev python3-pip

RUN mkdir /home/PaddleOCR/
ADD .  /home/PaddleOCR/

RUN python3.8 -m pip install --upgrade pip -i https://mirror.baidu.com/pypi/simple
RUN python3.8 -m pip install --upgrade setuptools -i https://mirror.baidu.com/pypi/simple
RUN python3.8 -m pip install -r /home/PaddleOCR/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN python3.8 -m pip install opencv-python-headless -i https://mirror.baidu.com/pypi/simple
RUN python3.8 -m pip install paddlepaddle_gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
RUN python3.8 -m pip install web.py paddleocr -i https://mirror.baidu.com/pypi/simple

ENTRYPOINT ["/bin/bash","-c","/home/PaddleOCR/run.sh"]
```
