### ISSUE TITLE
UNABLE TO USE PREDICT COMMAND MENTIONED IN GITHUB!! HELP!

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#898]
I am trying to run Predict Command after training my model and save the checkpoint in output/re_crnn/best_accuracy but it throws an error.
1. Predict Command
Predict English results
python3 tools/infer_rec.py -c configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yml -o Global.checkpoints=output/re_crnn/best_accuracy TestReader.infer_img=doc/imgs_words/en/word_1.jpg

2. Error Thrown when I run above command.

Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 77, in main
    init_model(config, eval_prog, exe)
  File "/content/gdrive/My Drive/PaddleOCR/ppocr/utils/save_load.py", line 114, in init_model
    fluid.load(program, path, exe)
  File "<decorator-gen-71>", line 2, in load
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 212, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1873, in load
    v.name, parameter_file_name)
AssertionError: Can not find [conv11_se_1_offset] in model file [output/rec_CRNN/best_accuracy.pdparams]

**Comment by littletomatodonkey** [comment]
You should guarantee that th training config and test config is absolutely same, or maybe you can not load the weights.

**Comment by karndeepsingh** [comment]
I have used the mentioned steps in the gitub repository for training on TEXT RECOGNISTION!
 I have used the following code 
1.Training:
python3 tools/train.py -c configs/rec/rec_icdar15_train.yml 2>&1 | tee train_rec.log 

2.Prediction:
python3 tools/infer_rec.py -c configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yml -o Global.checkpoints={path/to/weights}/best_accuracy TestReader.infer_img=doc/imgs_words/en/word_1.jpg

**Comment by littletomatodonkey** [comment]
If you use `rec_icdar15_train.yml` to train the model, you should also use `rec_icdar15_train.yml` for prediction.

**Comment by karndeepsingh** [comment]
Thanks. I have used that to eval and predict. Code is running fine. But I am unable to see the output after prediction code ran. Did it save somewhere?

And one additional question :
suppose i have document images which has images and text in it and want to extract text from it and want to train it from scratch also. So, first I will train it using "Text Detection" Algorithm then from there I will get bounding boxes of "Texts" now I will pass these "Text Detected" Images to "Text Recognition" Algorithm to extract the texts from that output images of "Text Detection"  algorithm.

Just clear me with this approach!! 
Thanks in advance

**Comment by littletomatodonkey** [comment]
1. You may see the output in the screen since it is just the recognition model, if you want to see the  system effect, you may use `tools/infer/predict_system.py` for inference, for which you should export inference model first, please refer to the doc: https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/inference_en.md
2. Yes that's right, the text detector and recognizer are working in series.

**Comment by karndeepsingh** [comment]
Okay. I will convert my trained model to inference model and then use it for prediction.

Questions:
1.If I want to train on "NEW DATASET" which has multiple things in an document like "Images and text" and only want to extract text from that document so, I need not to apply "Text Detection" model or I Have to ? before training it for "Text Recognition"??

2.For training in for "Text Detection" model for new dataset, Do I need to first Label the "Text" PART in the dataset and then pass it to the "Text Detection" model and train it for "Text" detection.??

**Comment by MissPenguin** [comment]
> Okay. I will convert my trained model to inference model and then use it for prediction.
> 
> Questions:
> 
> 1. For training in for "Text Detection" model on new dataset, Do I need to first Label the "Text" PART in the dataset and then pass it to the "Text Detection" model and train it for "Text" detection.? and then pass those bounding Boxes "TEXT"  (Obtain from text detection part ) to "Text Recognition" part right??
> 
> Please just correct me If I am wrong!!

You can cut out the text region for recognition trainning, but the amount of data needed for recognition training is generally large, like several millions, so a large amount of synthetic data is often added for better performance.
