### ISSUE TITLE
from paddleocr import PaddleOCR时报错SystemError: Parent module 'tools' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by yuanlisky** [PaddlePaddle/PaddleOCR#8981]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 14.04 LTS
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.2 问题相关组件/Related components：tools = importlib.import_module('.', 'tools')
- 运行指令/Command Code：命令行运行paddleocr 或者 python环境下运行 from paddleocr import PaddleOCR
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "opt/Python-3.6.2/bin/paddleocr", line 5, in <module>
    from paddleocr.paddleocr import main
  File "opt/Python-3.6.2/lib/python3.6/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "opt/Python-3.6.2/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 33, in <module>
    tools = importlib.import_module('.', 'tools')
  File "opt/Python-3.6.2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 973, in _gcd_import
  File "<frozen importlib._bootstrap>", line 923, in _sanity_check
SystemError: Parent module 'tools' not loaded, cannot perform relative import

**Comment by LDOUBLEV** [comment]
脚本放在paddleOCR目录外运行试试

**Comment by will-wiki** [comment]
碰到同样的问题，centos环境，Paddle：2.3.2 PaddleOCR：2.6.1.2 ，按照教程https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md，安装后使用命令行运行paddleocr 或者 python环境下运行 from paddleocr import PaddleOCR报错SystemError: Parent module 'tools' not loaded, cannot perform relative import

**Comment by yuanlisky** [comment]
该问题已经解决，下面是解决办法，适合新安装的Python环境

git上下载zip包，解压后进入PaddleOCR文件夹下
1.调整 requirements.txt，修改安装会报错的依赖包，主要是lanms-neo和PyMuPDF
lanms-neo==1.0.2 改为 lanms==1.0.2  (原本的neo包有问题，安装不上，可以lanms平替)
PyMuPDF<=1.21.0 改为 PyMuPDF==1.19.0  (会默认安装1.18版本，安装不上，1.19版本可安装)
2.调整paddleocr.py中的代码
importlib.import_module('.', 'tools') 及下面两行代码会报错，可以注释掉
注释掉import importlib行，在下面一行加上 import skimage，该包在其它模块的__init__.py文件中导入，上一步注释掉的代码会导致skimage导入失败，因此直接在此处先导入
3.调整setup.py文件
注释掉 from paddleocr import VERSION，直接在该文件下新建 VERSION 变量，不依赖 paddleocr.py 文件(此时未安装第三方扩展，引入paddleocr.py文件会导致import第三方包失败)
在 PaddleOCR 下运行 python3 setup.py bdist_wheel 生成离线wheel包，然后采用pip安装dist文件夹下的whl包

系统: ubuntu 14.04LTS   centOS
python版本: 3.6.2
以上环境均成功安装
