### ISSUE TITLE
Best accuray is not showing in weights save directory

### ISSUE THREAD

**Issue by ArsalanAli915** [PaddlePaddle/PaddleOCR#8985]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Best accuray is not showing in weights save directory only latest and iter opech are refleacting. pleasse help.

**Comment by andyjpaddle** [comment]
please provide you config and train.log, maybe you dataset is small, you can set the params `eval_batch_step` in a small value, eg: [0, 10]

**Comment by ArsalanAli915** [comment]
Thanks for your reply. It's working fine now.
