### ISSUE TITLE
训练很慢

### ISSUE THREAD

**Issue by angel-yi** [PaddlePaddle/PaddleOCR#8989]
您好，我在ubuntu上训练rec模型，三张16G的卡，修改了keys字典，用的自己的数据集，训练了挺久了，各项指标上升很慢，有什么调整方案吗？
![image](https://user-images.githubusercontent.com/51775756/217139630-0eee3a73-6fc5-4a89-949f-386a2441bfdc.png)
![image](https://user-images.githubusercontent.com/51775756/217139687-6dcc3d65-15fb-449c-bf34-106e1541f1c6.png)
![image](https://user-images.githubusercontent.com/51775756/217139747-358b6fc4-f7b8-4471-96fe-9a7039170caa.png)

**Comment by angel-yi** [comment]
已经训练了130多个小时了

**Comment by andyjpaddle** [comment]
数据量有多少呢？修改字典后，相当于重新训练，收敛会比较慢，不推荐修改字典。不过看你的给的信息，现在eval acc已经75+了，可以分析下bad case，针对性解决来进一步提升精度

**Comment by angel-yi** [comment]
训练数据量大概是200w,横竖排混合的，官方的keys只有6k个字符，我加到1.2w左右的字符，能看到loss是在收敛，但就是很慢，慢得出奇

**Comment by angel-yi** [comment]
这怎么分析bad case呀，训练过程中我不知道该怎么查问题所在了

**Comment by andyjpaddle** [comment]
训练字符数稍微有点多，训练收敛慢也正常，数据都是真实数据吗？

**Comment by andyjpaddle** [comment]
> 这怎么分析bad case呀，训练过程中我不知道该怎么查问题所在了

可以对评估集进行预测可视化，分析一下预测错的样本，看有没有共性，针对共性来解决

**Comment by angel-yi** [comment]
> > 这怎么分析bad case呀，训练过程中我不知道该怎么查问题所在了
> 
> 可以对评估集进行预测可视化，分析一下预测错的样本，看有没有共性，针对共性来解决

好的，我懂了

**Comment by angel-yi** [comment]
> 训练字符数稍微有点多，训练收敛慢也正常，数据都是真实数据吗？

有部分真实的，部分是自己生成的
