### ISSUE TITLE
Unable to download files from pan.baidu.com

### ISSUE THREAD

**Issue by alexgoryushkin** [PaddlePaddle/PaddleOCR#899]
It is currently not possible to download files from pan.baidu.com because it requires registration and registration outside China is prohibited.

![image](https://user-images.githubusercontent.com/43167451/95185402-1e763a00-07e2-11eb-8ad2-3da8828649e2.png)

It would be great if you could use services to store files without registering. Thanks

**Comment by littletomatodonkey** [comment]
Thanks for your attention, we will provide another download access.

**Comment by tink2123** [comment]
Excuse me, which part of the file do you need to download? We will try to upload the files you need to other services

**Comment by alexgoryushkin** [comment]
I would like to download this file - https://pan.baidu.com/s/1bS_u207Rm7YbY33wOECKDA code:frgi. Thanks

**Comment by littletomatodonkey** [comment]
Hi, you can download it from here: https://drive.google.com/file/d/18cSWX7wXSy4G0tbKJ0d9PuIaiwRLHpjA/view?usp=sharing

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give for free. Honestly, that’s pretty cheap compared to most of these services.
