### ISSUE TITLE
Paddle Serving 服务化部署后，启动报错pipeline server init error

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#8993]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
Paddle Serving 服务化部署后，启动报错pipeline server init error
- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- python版本为3.9.13
- 
![image](https://user-images.githubusercontent.com/49382323/217187784-a713e1f1-b04b-4b23-86da-ca7d9cc26ea9.png)

- 运行指令/Command Code：
- python web_service.py --config=config.yml
- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/49382323/217188298-514bdb4c-40a4-4dd6-bc71-9d9832230a51.png)
![image](https://user-images.githubusercontent.com/49382323/217188339-d633c85c-3d00-4ee6-88b7-7bdc326798ab.png)

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/pdserving/README_CN.md#windows%E7%94%A8%E6%88%B7

**Comment by kerry-weic** [comment]
pip3 install paddle-serving-app==0.3.1
报错如下:
![image](https://user-images.githubusercontent.com/49382323/222077984-b94b011a-2990-4f5c-9f19-c26864be4ab6.png)

**Comment by kerry-weic** [comment]
![image](https://user-images.githubusercontent.com/49382323/222078882-ce79773a-130b-4168-be34-ee50f9ba9578.png)

**Comment by kerry-weic** [comment]
python ocr_web_client.py 报错如下
![image](https://user-images.githubusercontent.com/49382323/222117109-ed89a695-d8d6-45b2-b285-5277e11351e3.png)
![image](https://user-images.githubusercontent.com/49382323/222117233-ff27a512-aff5-4c1f-af51-4c33a1573a57.png)
