### ISSUE TITLE
如何在通用模型基础上增加部分默认字典里已有字符的识别效果

### ISSUE THREAD

**Issue by iclgg** [PaddlePaddle/PaddleOCR#8994]
微调会忘记原模型已有的知识吗？即使只训练很少轮
请问我只想提高默认字典里的某几个字符的识别效果，怎么微调？
[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)/[doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc)/[doc_ch](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc/doc_ch)/finetune.md中只提到了修改配置文件：[ch_PP-OCRv3_rec_distillation.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml)，下载预训练模型：[ch_PP-OCRv3_rec_train.tar](https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_train.tar)。启动命令和[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)/[doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc)/[doc_ch](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc/doc_ch)/recognition.md中的一样吗？
我修改完配置文件后按照[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)/[doc](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc)/[doc_ch](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc/doc_ch)/recognition.md中的步骤启动训练，发现模型能识别的只剩下数据集里出现的字符了

**Comment by andyjpaddle** [comment]
微调可以参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83

**Comment by iclgg** [comment]
> 微调可以参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83
这里的微调会失去通用场景的效果，只保留数据集中出现过则字符吗？

**Comment by andyjpaddle** [comment]
通用场景数据也需要用，可以多加入一些需要的字符样本数量

**Comment by iclgg** [comment]
> 通用场景数据也需要用，可以多加入一些需要的字符样本数量

我需要准备的数据包括通用场景的数据+特别字符的数据，不能只用特别字符作为数据集吗？

**Comment by iclgg** [comment]
还想问个问题，[ch_PP-OCRv3_rec_distillation.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml)中的Student和Teacher模型是什么关系呢

**Comment by andyjpaddle** [comment]
> > 通用场景数据也需要用，可以多加入一些需要的字符样本数量
> 
> 我需要准备的数据包括通用场景的数据+特别字符的数据，不能只用特别字符作为数据集吗？

是的



> 还想问个问题，[ch_PP-OCRv3_rec_distillation.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml)中的Student和Teacher模型是什么关系呢

这个配置采用的是UDML蒸馏，student和teacher相互学习

**Comment by iclgg** [comment]
> > > 通用场景数据也需要用，可以多加入一些需要的字符样本数量
> > 
> > 
> > 我需要准备的数据包括通用场景的数据+特别字符的数据，不能只用特别字符作为数据集吗？
> 
> 是的
> 
> > 还想问个问题，[ch_PP-OCRv3_rec_distillation.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml)中的Student和Teacher模型是什么关系呢
> 
> 这个配置采用的是UDML蒸馏，student和teacher相互学习
我的目的用这个配置文件合适吗

**Comment by andyjpaddle** [comment]
可以先用这个试试效果
