### ISSUE TITLE
cannot import name 'PPStructure' from 'paddleocr'

### ISSUE THREAD

**Issue by fengyunzaidushi** [PaddlePaddle/PaddleOCR#8996]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10,cpu
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.5
-  问题相关组件/Related components：

- 运行指令/Command Code：
`from paddleocr import PPStructure,draw_structure_result,save_structure_res`

- 完整报错/Complete Error Message：

`File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddleocr\paddleocr.py", line 32, in <module>
    ppstructure = importlib.import_module('.', 'ppstructure')
  File "D:\2020exe\Anaconda3\envs\paddle\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "I:\paddle_ocr\ppstructure.py", line 9, in <module>
    from paddleocr import PPStructure,draw_structure_result,save_structure_res
ImportError: cannot import name 'PPStructure' from 'paddleocr' (D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddleocr\__init__.py)`

**Comment by andyjpaddle** [comment]
使用最新版paddleocr 2.6试试

**Comment by fengyunzaidushi** [comment]
> 使用最新版paddleocr 2.6试试
开始安装的2.6.1.2同样的问题，然后安装了2.5

**Comment by fengyunzaidushi** [comment]
发现问题了，文件名称有个PPStructure
