### ISSUE TITLE
请问release/*和dygraph的区别？哪一个是main branch？

### ISSUE THREAD

**Issue by Nickeilf** [PaddlePaddle/PaddleOCR#8997]
请问哪一个branch是最新的？目前的default branch是release/2.6，但是之前似乎是dygraph.
这两个branch似乎都有commit但是好像commit又不是完全相同，是两个分开的branch

如果fork了之后需要使用哪一个remote branch才能够和PaddleOCR的最新commit保持一致？

**Comment by andyjpaddle** [comment]
release/2.6 是发布的稳定版分支，dygraph是开发分支，具有最新的特性功能，需要稳定验证后才会拉到新的release分支

**Comment by Nickeilf** [comment]
了解，多谢解答！
