### ISSUE TITLE
PaddleOCR 的 CAN 模型转.nb报错

### ISSUE THREAD

**Issue by rico2001** [PaddlePaddle/PaddleOCR#8999]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
  1）Paddle Lite 版本：v2.12
   2）Host 环境：Ubuntu 20.04
- 版本号/Version：
   Paddle：2.4.1  PaddleOCR：2.0.6
- 模型链接: 链接：https://pan.baidu.com/s/19cRyqewaOGnkDk70h_hNRQ?pwd=1234
提取码：1234
-  问题相关组件/Related components： 
    paddleLite 2.12
- 运行指令/Command Code：
   paddle_lite_opt --model_dir=./output/exportModel/rec_d28_can--valid_targets=arm --optimize_out=output/out
- 完整报错/Complete Error Message：
[libprotobuf ERROR C:\xiaowen01\x86_windows_py_wheel\py37\Paddle-Lite\third-party\protobuf-host\src\google\protobuf\message_lite.cc:119] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[0].ops[731].attrs[18].type, blocks[0].ops[793].attrs[18].type, blocks[0].ops[855].attrs[18].type, blocks[0].ops[917].attrs[18].type, blocks[0].ops[979].attrs[18].type, blocks[0].ops[1041].attrs[18].type, blocks[0].ops[1103].attrs[18].type, blocks[0].ops[1165].attrs[18].type, blocks[0].ops[1227].attrs[18].type, blocks[0].ops[1289].attrs[18].type, blocks[0].ops[1351].attrs[18].type, blocks[0].ops[1413].attrs[18].type, blocks[0].ops[1475].attrs[18].type, blocks[0].ops[1537].attrs[18].type, blocks[0].ops[1599].attrs[18].type, blocks[0].ops[1661].attrs[18].type, blocks[0].ops[1723].attrs[18].type, blocks[0].ops[1785].attrs[18].type, blocks[0].ops[1847].attrs[18].type, blocks[0].ops[1909].attrs[18].type, blocks[0].ops[1971].attrs[18].type, blocks[0].ops[2033].attrs[18].type, blocks[0].ops[2095].attrs[18].type, blocks[0].ops[2157].attrs[18].type, blocks[0].ops[2219].attrs[18].type, blocks[0].ops[2281].attrs[18].type, blocks[0].ops[2343].attrs[18].type, blocks[0].ops[2405].attrs[18].type, blocks[0].ops[2467].attrs[18].type, blocks[0].ops[2529].attrs[18].type, blocks[0].ops[2591].attrs[18].type, blocks[0].ops[2653].attrs[18].type, blocks[0].ops[2715].attrs[18].type, blocks[0].ops[2777].attrs[18].type, blocks[0].ops[2839].attrs[18].type, blocks[0].ops[2899].attrs[18].type
Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'set_value'.

**Comment by rico2001** [comment]
你好，命令修改后情况一样

**Comment by rico2001** [comment]
![微信截图_20230208111509](https://user-images.githubusercontent.com/16769618/217419930-532d44da-50f3-41b7-8a38-c5af85f55024.png)

**Comment by lishicheng1996** [comment]
> ![微信截图_20230208111509](https://user-images.githubusercontent.com/16769618/217419930-532d44da-50f3-41b7-8a38-c5af85f55024.png)

你好，set_value 这个算子在2.12编译发包的时候尚未合入，但已合入到2.12代码中。参照https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/model_optimize_tool.html （编译命令：./lite/tools/build.sh build_optimize_tool）源码编译部分可以编译出可执行文件 opt 工具，并参照 https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/opt/opt_bin.html 使用

**Comment by rico2001** [comment]
你好，模型已经按照你提供的方法转换成功，感谢支持！
