### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by songfh** [PaddlePaddle/PaddleOCR#90]
![image](https://user-images.githubusercontent.com/22196645/82752725-aa1e9980-9df2-11ea-95b2-f4b1ff92777a.png)
谢改db_postprocess.py 131行后入下图132行所示：
![image](https://user-images.githubusercontent.com/22196645/82752758-ed790800-9df2-11ea-947d-320ece614626.png)
运行后，报错信息如下：
![image](https://user-images.githubusercontent.com/22196645/82752772-05508c00-9df3-11ea-8eb5-764f2c97aa91.png)
谢改db_postprocess.py 47行后入下图48行所示：
![image](https://user-images.githubusercontent.com/22196645/82752788-1d281000-9df3-11ea-8e01-eb6f7a14c48d.png)
再次运行后，报错信息如下：
![image](https://user-images.githubusercontent.com/22196645/82752825-5b253400-9df3-11ea-86e1-64021bed7aa4.png)

**Comment by LDOUBLEV** [comment]
你好，没能复现你的问题，在其他图片上测试是正常的吗？

**Comment by songfh** [comment]
测试了几张，都不行。
我用的镜像是hub.baidubce.com/paddlepaddle/paddle:1.7.2，宿主机是：mac air

**Comment by LDOUBLEV** [comment]
> 测试了几张，都不行。
> 我用的镜像是hub.baidubce.com/paddlepaddle/paddle:1.7.2，宿主机是：mac air

试下拉develop分支最新的代码。
或者换个docker： hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev 
启动的时候不要用nvidia-docker 启动 用docker启动。
```
docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash

```
