### ISSUE TITLE
基于student模型做finetune后评估准确率为0

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9001]
paddlepaddle：2.3.2
paddleocr：2.6.1.2

1. 对预训练模型进行评估
python tools/eval.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv3_det_distill_train/student
![image](https://user-images.githubusercontent.com/18339429/217411459-0db1348a-c1fd-4fb3-98fb-3f31832ab3e2.png)

2. 基于student模型做finetune
python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv3_det_distill_train/student Global.use_gpu=False Global.save_epoch_step=10 Global.eval_batch_step=[0,20] Global.epoch_num=100 Optimizer.lr.learning_rate=0.00025

部分日志：
![image](https://user-images.githubusercontent.com/18339429/217442398-35210708-8d6e-4323-b45a-fe34a219bd0a.png)

训练后基于finetune后的模型进行评估都是0：
precision：0
reca17：0
hmean：0

ps：训练样本只有13个图片，用PPOCRLabel重新进行标注。是不是训练样本太少？但是太少的话，为何会导致都是0，而不是达到预训练模型本身的精度？

这种情况如何进行排查问题？

**Comment by leoterry-ulrica** [comment]
@andyjpaddle 请问应该先从哪方面进行排查问题？

**Comment by tink2123** [comment]
训练图片太少，导致模型过拟合到训练数据上，评估精度为0是正常的。
