### ISSUE TITLE
古文识别相关问题

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#9003]
烦请指教：
1. 我的识别对象是单字图片，是否直接使用识别模型即可？
2. 假设进行单字进行识别，是否能做到显示多个识别结果并按置信度降序排列？
3. 假设我将码表改为大概1万个字符（古籍涉及到很多的字符并未出现在模型默认码表6000多个汉字中），然后进行单字识别，这个微调思路可行吗？对单字识别率会有显著提升吗（默认模型对于古籍单字识别率大概为60%）。请问训练集大概每个字得出现多少频次？如果将码表改为2万字呢？
4. 对古文进行单字识别，微调的时候，数据集是推荐各汉字的图片数数目基本一致，还是说可以根据古籍汉字字频统计，对高字频的汉字多使用一些图片？

**Comment by tink2123** [comment]
1. 可以仅使用识别模型，如果只会出现单字的话，也可以直接使用分类模型
2. 可以，目前输出的是概率值最大的类别，可以修改代码返回topn，如果需要这个功能同样建议直接使用分类模型。
3. 每个类别出现200-500即可，实际训练数据量与词表数有关
4. 如果是单字识别，尽量保持字频一致。

可以参考甲骨文识别的项目，与您描述的诉求近似：https://aistudio.baidu.com/aistudio/projectdetail/5216041?contributionType=1

**Comment by haoxia1** [comment]
感谢指教！
我在担忧使用您说的paddleClas分类模型所得到的准确率会不会大幅度低于 在paddleOCR预训练模型的基础之上进行的微调？？
我在paddleClas中看到了topk参数，paddleOCR应该是没有这一功能哈？

**Comment by BaoBaoJianqiang** [comment]
20902没有的字，用unicode码作为码表，要修改paddleocr源码支持unicode字典
