### ISSUE TITLE
请教一下，pytorch ocr crnn的resnet34 pth文件怎么转onnx？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9004]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请教一下，pytorch ocr crnn的resnet34 pth文件怎么转onnx？

**Comment by tink2123** [comment]
可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme_ch.md
