### ISSUE TITLE
无法识别“磋”字

### ISSUE THREAD

**Issue by mz5210** [PaddlePaddle/PaddleOCR#9005]
我测试无论使用v2还是v3，无论是Lite版本多少都无法识别到“磋”字。也测试了官网的demo，无论是自己编译还是直接下载你们编译好的，都无法识别这个字。

**Comment by tink2123** [comment]
这个字属于低频字，受训练样本的限制，某些低频字无法识别，如有特殊需要建议加入自己的数据finetune，能比较好的缓解这个问题。

**Comment by mz5210** [comment]
> 这个字属于低频字，受训练样本的限制，某些低频字无法识别，如有特殊需要建议加入自己的数据finetune，能比较好的缓解这个问题。

感谢回复
