### ISSUE TITLE
chinese_cht_PP-OCRv3_rec_train作為pretrain model訓練後測試結果有誤

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#9007]
- 系统环境/System Environment：anaconda python3.8

- 运行指令/Command Code：(已經轉為inference)
python tools/infer_rec.py -c configs/rec/multi_language/rec_chinese_cht_lite_train5.yml -o Global.checkpoints=output/wiki_mingliu_v3/best_accuracy Global.infer_img=train_data/wiki/test/7_608.png Global.save_res_path=data/result.txt

- 报错/Complete Error Message：
出現的每個答案都一樣
![image](https://user-images.githubusercontent.com/45616986/217454019-d4406b0a-5c13-4a03-9d04-5a579c68939b.png)

pretrain_model:chinese_cht_PP-OCRv3_rec_train
來源
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md#23-%E5%A4%9A%E8%AF%AD%E8%A8%80%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E6%9B%B4%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD

訓練
python tools/train.py -c configs/rec/PP-OCRv3/multi_language/chinese_cht_PP-OCRv3_rec1.yml -o Global.pretrain_weights=./pretrain_models/chinese_cht_PP-OCRv3_rec_train/

yml連結:
https://drive.google.com/file/d/1BMP7rGCiIPB-jzYMobFQLoxvuOfG4nGL/view?usp=sharing

**Comment by tink2123** [comment]
请问重新训练完成后，新模型在评估集上的精度可以到多少呢？看识别结果输出score，似乎是随机初始化的结果，考虑检查是否没有正确加载训练好的权重，或训练过程未收敛？

**Comment by 38weiying** [comment]
已找到問題，export_model使用錯誤的配置文件
