### ISSUE TITLE
PP-OCRv3模型与前沿算法的比较

### ISSUE THREAD

**Issue by lq0104** [PaddlePaddle/PaddleOCR#9008]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请问下，在如下链接中包含了文字识别的前沿算法：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_overview.md#12

请问PP-OCRv3模型有使用过MJSynth和SynthText两个文字识别数据集训练，在IIIT, SVT, IC03, IC13, IC15, SVTP, CUTE数据集上进行评估吗？因为这样有个比较基准进行参考，麻烦解答一下，谢谢。

**Comment by tink2123** [comment]
PP-OCRv3 是用于文本行识别的中英文通用模型，没有使用过MJSynth和SynthText训练。
