### ISSUE TITLE
关于hubserving部署问题

### ISSUE THREAD

**Issue by JawerZ** [PaddlePaddle/PaddleOCR#901]
请问是否可以使用自己的模型进行hub服务化部署，如果可以的话需要更改什么，我更改了params.py里的配置，替换成了我自己的模型，但是不起作用

**Comment by MissPenguin** [comment]
不起作用是指报错还是？如果还是训练的DB模型，应该在params中替换成新的inference模型路径就行了，记得替换后要将服务模块卸载重装，然后重新启动服务。建议先直接运行python3 PATH_TO/module.py进行调试，调通后再测试服务。

**Comment by JawerZ** [comment]
> 不起作用是指报错还是？如果还是训练的DB模型，应该在params中替换成新的inference模型路径就行了，记得替换后要将服务模块卸载重装，然后重新启动服务。建议先直接运行python3 PATH_TO/module.py进行调试，调通后再测试服务。
好的 谢谢 原因是没有将服务模块卸载重装
