### ISSUE TITLE
python Paddle Serving pipeline服务化部署后，内存释放和响应时间问题

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#9019]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
1、服务启动所占系统内存为5G左右(这是正常的吗？)，通过多执行python3 pipeline_http_client.py脚本后，能明显看到内存未及时释放。可能确定的是服务器上没有其他程序干扰。
2、单使用CPU预测部署后，通过http调用ocr接口(无并发)，响应时间为3-4s。cpu为Intel的 24核，监控看CPU无任何压力
- 系统环境/System Environment：centeros
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 
![image](https://user-images.githubusercontent.com/49382323/217719964-9e26223a-5cc3-41a0-a673-27c5edc35fa6.png)

- 运行指令/Command Code：
- python3 web_service.py --config=config.yml &>log.txt &
- 完整报错/Complete Error Message：
- config.yml配置如下
- 
![image](https://user-images.githubusercontent.com/49382323/217720146-e191ceb5-04ee-4631-8bae-01e58392ec5a.png)
![image](https://user-images.githubusercontent.com/49382323/217720162-07fe7026-50d1-45e2-a92c-3a7e042781b3.png)

一次tracer日志如下:
![image](https://user-images.githubusercontent.com/49382323/217721563-0acf2ab3-cd20-4476-a99b-7c3f8e8584bb.png)

内存监控记录:
![image](https://user-images.githubusercontent.com/49382323/217721337-3e5dd105-f3dc-44f9-8acc-8951c2b897d4.png)

**Comment by 784117672** [comment]
我也遇到了卡死问题，之后paddleOcr系统就没有响应了。我修改了config中的is_thread_op: True之后，开启10个线程，通过http调用，每个线程请求10次，没有再卡死，但是请求响应时间依然很长，每次需要3~4s，我是1核4G。请求时长问题，以后会升级机器配置，但不确定是否会有明显的改善。

**Comment by kerry-weic** [comment]
@784117672 这个问题视乎没人在看，后面我修改了部署方式，采用fastDeploy服务化方式部署，推理时间有明显改善

**Comment by 784117672** [comment]
> 

好的，我了解以下这种方式

**Comment by 784117672** [comment]
> @784117672 这个问题视乎没人在看，后面我修改了部署方式，采用fastDeploy服务化方式部署，推理时间有明显改善

请问你采用fastDeploy方式部署之后，内存无法释放的问题结局了吗。我刚测了下，pdserving方式部署的，配置设置为多线程时 不会有内存问题，但是会有线程安全问题，读到其他线程的数据、修改为多进程配置之后就出现内存无法释放的问题了。

**Comment by kerry-weic** [comment]
@784117672  这个我暂时还没测，我采用fastDeploy的simple_serving部署部署方式，没发现有内存占用问题，但若想支持高并发官方推荐的是fastdeploy_serving方式部署，后者我当时尝试部署时未部署成功，印象中是默认配置推理后端接口有些问题，需要配置使用其它后端才行也不知现在是否有解决

**Comment by 784117672** [comment]
> @784117672 这个我暂时还没测，我采用fastDeploy的simple_serving部署部署方式，没发现有内存占用问题，但若想支持高并发官方推荐的是fastdeploy_serving方式部署，后者我当时尝试部署时未部署成功，印象中是默认配置推理后端接口有些问题，需要配置使用其它后端才行也不知现在是否有解决

好的，感谢告知。
