### ISSUE TITLE
开源模型体验

### ISSUE THREAD

**Issue by fleetcor** [PaddlePaddle/PaddleOCR#902]
1. 请问下面列表是否收费，还是可以直接免费使用？
2. 使用是否有内部次数限制？

https://ai.baidu.com/easyedge/app/openSource?from=paddlelite

谢谢

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/95550467-88d5e700-0a3b-11eb-97c8-7e9098062f3a.png)
您好，这两个OCR模型是免费的，其他的不是很清楚，没有次数限制。

**Comment by MissPenguin** [comment]
您好，OCR模型是免费的，其他的不是很清楚，没有次数限制。

**Comment by fleetcor** [comment]
谢谢，那我可以直接用到我公司产品里了吗？

**Comment by MissPenguin** [comment]
> 谢谢，那我可以直接用到我公司产品里了吗？

可以的

**Comment by fleetcor** [comment]
谢谢哈
