### ISSUE TITLE
VQA模块的OCR引擎+SER串联预测只有命令行预测，请问有开箱即用的形式吗？

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleOCR#9020]
您好，按照官方文档，我完成了使用命令在终端进行 OCR引擎+SER串联预测 的任务，具体参考如下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README_ch.md#52-ser。

请问：除了终端命令，有开箱即用的调用方式吗？开箱即用如：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8

期待您的回复，感谢！

**Comment by WenmuZhou** [comment]
暂时没有哈
