### ISSUE TITLE
请问印章检测的数据集可以从哪里获取？

### ISSUE THREAD

**Issue by haimeilv** [PaddlePaddle/PaddleOCR#9023]
我从https://aistudio.baidu.com/aistudio/datasetdetail/177475
获取了数据集，发现图像大小貌似和yml文件中要求的不太一致，用官方提供的模型检测出来的效果也很差，请问能提供一下路径吗？

**Comment by LDOUBLEV** [comment]
范例里的印章模型用的数据无法公开，建议合成一批，

https://aistudio.baidu.com/aistudio/datasetdetail/177475
这个是开发者贡献的，可以用作预训练
