### ISSUE TITLE
paddle lite 2.6.1预测库运行官网发布的模型在iPhone 6s出错malloc: can't allocate region :*** mach_vm_map(size=68719493120, flags: 100) failed (error code=3)

### ISSUE THREAD

**Issue by heXiangpeng** [PaddlePaddle/PaddleOCR#903]
addle-lite-ocr(12983,0x101ef7880) malloc: can't allocate region
:*** mach_vm_map(size=68719493120, flags: 100) failed (error code=3)
paddle-lite-ocr(12983,0x101ef7880) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

**Comment by LDOUBLEV** [comment]
2.6.1 不支持，试试2.6.3 分支吧

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
