### ISSUE TITLE
不想识别符号

### ISSUE THREAD

**Issue by lxk1234** [PaddlePaddle/PaddleOCR#9031]
请问，直接调用官方的paddle不进行训练，简单的识别数字和字母。但是图片中在两个字符之间可能会有一个白点，然后会将白点给识别出来一个‘.’。这种情况要怎么解决

**Comment by an1018** [comment]
可以通过后处理，把字符串中的. replace为空

**Comment by lxk1234** [comment]
好的，感谢您给的建议。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月10日(星期五) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 不想识别符号 (Issue #9031)





 
可以通过后处理，把字符串中的. replace为空
