### ISSUE TITLE
pplabel表格标注问题

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/PaddleOCR#9032]
表格标注的表格识别后，为何检测框显示的是ocr检测的检测框结果而不是表格结构识别后合并后的检测框的结果，这样每次表格识别后无论表格识别是否正确，都需要人工将检测框进行合并修改，调整顺序。

**Comment by an1018** [comment]
输出文件夹中的Excel文件是表格识别的结果，可以通过查看具体结果

**Comment by aaferrero** [comment]
![2023-02-10 16-13-32屏幕截图](https://user-images.githubusercontent.com/47381179/218038454-bb3fa535-e92d-4605-9817-675228d4e812.png)
用表格标注按钮识别出来是这样的，正确的标注我觉得应该是这样的
![2023-02-10 16-11-38屏幕截图](https://user-images.githubusercontent.com/47381179/218038687-6498194e-37d8-4670-8a05-1ac078126bed.png)
这个我看了下代码，表格识别后是将ocr单行检测框显示在上面，感觉这个逻辑有问题，应该结合结构识别后的结果将检测框合并后显示在上面，不知道是不是这样。

**Comment by an1018** [comment]
其他图片中同一单元格多行的标注都存在这种情况吗，如果不是可以尝试手动调试标注框

**Comment by aaferrero** [comment]
这个表格识别的逻辑就是显示的单行检测框，每次碰到有合并的肯定都需要手动合并的，我不确定是不是标注时候需要这么合并检测框，如果确定需要的话，这个改下代码是可以优化的。

**Comment by an1018** [comment]
可以再详细看下[这个文档](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8)，调用的表格识别模型，不是检测模型，再多测试几张图片。

**Comment by aaferrero** [comment]
那我确定是标注工具问题了。。
![e71a384092564b6d0ebf55e64d7f2d7](https://user-images.githubusercontent.com/47381179/218051684-21c3785a-6480-4e46-9a9b-0fb292c5c922.jpg)
pplabel代码里表格显示框显示的就是单行检测框

**Comment by leoterry-ulrica** [comment]
开源版本听说不支持多行检测，只支持单行检测。

**Comment by Mrfuhang** [comment]
> 开源版本听说不支持多行检测，只支持单行检测。这样子多行文本需要人工调整检测框的工作量也巨大。
那这多行的怎么处理啊


> 那我确定是标注工具问题了。。 ![e71a384092564b6d0ebf55e64d7f2d7](https://user-images.githubusercontent.com/47381179/218051684-21c3785a-6480-4e46-9a9b-0fb292c5c922.jpg) pplabel代码里表格显示框显示的就是单行检测框

老哥你这个解决了嘛 ，我现在也遇到和你一样的问题，合并的单元格出来的gt文件里面都在一个td里面

**Comment by ywachao** [comment]
> 

那现在是不支持多行文本检测识别？我也有同样的问题

**Comment by UserWangZz** [comment]
It has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
