### ISSUE TITLE
The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]

### ISSUE THREAD

**Issue by liuyan20062010** [PaddlePaddle/PaddleOCR#9033]
使用re （re_vi_layoutxlm_xfund_zh.yml）模型的 推理脚本或者预测脚本，若ser预测的实体为空，即这个512序列中不含有实体，进入re模型时报错，The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]，不知道时bug 还是哪里的问题
如图：
![image](https://user-images.githubusercontent.com/35484984/217994479-7fe273eb-a35e-4e7b-bb45-663895355f67.png)

若  只有一对待预测的 kv 对，也会报这个错误，如图：
![image](https://user-images.githubusercontent.com/35484984/218008054-8129a981-fa4d-4338-a68e-f0f74bf7e77b.png)

**Comment by liuyan20062010** [comment]
我验证了 ，当我手动修改 待预测的对数变为大于一对的时候，不会报错，需要修改模型内部，这应该是一个 bug ，不过debug训练脚本的话  进不去模型结构  😔

**Comment by an1018** [comment]
收到，方便把测试图片发我们吗

**Comment by liuyan20062010** [comment]
手动修改  infer_kie_token_ser_re.py  中的make_input函数，使预测的实体全部重置为other  或者  只剩下一对 question  和  answer ,就可以复现bug 了，因为微调了模型，所以传测试图片没什么用了
