### ISSUE TITLE
python Paddle Serving pipeline服务化部署后，如何识别pdf？

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#9034]
![K30YLW1GV6@WDCWF5U`RX 4](https://user-images.githubusercontent.com/49382323/217995202-99a16099-8bbf-4ce2-9c34-07eae47d4137.png)

**Comment by an1018** [comment]
you can refer to [the code](https://github.com/PaddlePaddle/PaddleOCR/blob/7c81d482e9fe876dd62d82bd649f5c24f21767ec/ppocr/utils/utility.py#L55)
