### ISSUE TITLE
问个finetune的问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleOCR#9035]
用A数据集训练的模型不精准，finetune的时候还建议用A数据集吗，推荐用新数据好还是用原来A的数据集训练

**Comment by ic1031** [comment]
同问

**Comment by an1018** [comment]
训练不精准主要原因是什么，A的数据集数量太少？某些字符不精准，还是什么呢

**Comment by ic1031** [comment]
A的数据类型没有新丰富，使用A训练的模型去标B，并不断返回finetune，这种情况下怎么用数据更好呢

**Comment by 1061302569** [comment]
> 训练不精准主要原因是什么，A的数据集数量太少？某些字符不精准，还是什么呢

检测框不准，数据集增加到900了，检测框不能把纳税人识别号准确框住
这是我训练的配置，如果我需要finetune建议怎么修改，base_lr改为0.001比较好么，其他配置不清楚是什么，数据集还是用以前的数据吗，需不需要在加一些新数据进去
`epoch: 300

LearningRate:
  base_lr: 0.4
  schedulers:
  - !CosineDecay
    max_epochs: 300
  - !LinearWarmup
    start_factor: 0.1
    steps: 300

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.00004
    type: L2
`

![1676015639664](https://user-images.githubusercontent.com/44227598/218034164-4b0ed958-503f-42f7-a846-b64335f21f1a.png)

**Comment by an1018** [comment]
> A的数据类型没有新数据集丰富，使用原来A训练的模型去标新的B，并不断返回finetune，这种情况下怎么用数据更好呢

如果A标注没问题，而且切近自己的场景，可以先加载预训练模型在A上finetune

**Comment by an1018** [comment]
@1061302569 纳税人识别号部分的标注没问题吧

**Comment by 1061302569** [comment]
> @1061302569 纳税人识别号部分的标注没问题吧
在labelme里面我是这样标的，训练后和我标的不一样，如果文字一长数据会遗漏，我所有数据集都是按这张图标注的
![1675826839984](https://user-images.githubusercontent.com/44227598/218043262-85c24951-6e4f-4d68-889f-87d96902f8db.png)

**Comment by 1061302569** [comment]
> 如果A标注没问题，而且切近自己的场景，可以先加载预训练模型在A上finetune
不用加新的数据集，直接在A模型用A数据集finetune也可以么

**Comment by 1061302569** [comment]
> > @1061302569 纳税人识别号部分的标注没问题吧

在labelme里面我是这样标的，训练后和我标的不一样，如果文字一长数据会遗漏，我所有数据集都是按这张图标注的
 ![1675826839984](https://user-images.githubusercontent.com/44227598/218043262-85c24951-6e4f-4d68-889f-87d96902f8db.png)
