### ISSUE TITLE
复现configs/det/det_r50_vd_pse.yml的时候报错，Linux环境 centos

### ISSUE THREAD

**Issue by ic1031** [PaddlePaddle/PaddleOCR#9036]

**Comment by ic1031** [comment]
[2023/02/10 14:41:50] ppocr INF0: Initialize indexs of datasets: [ /public/home/clhou/code/ancient_data/TKH2200/TKHeval/960/w_test.txt ']
running build_ext
building 'pse' extension
gcc -pthread -B /public/home/clhou/anaconda3/envs/paddle /compiler_compat -wl,--sysroot=/ -wsign-compare -DNDEBUG -g -fwrapv -03 -wall -wstrict-prototypes -fpIC '-I/public/home/clhou/ anaconda3/envs/paddle/lib/python3.8/site-packages /numpy/core/include-I/public/home/clhou/anaconda3/envs/paddle/include/python3.8 -c pse.cpp -o build/temp.linux-x86_64-3.8/pse.o -03
cciplus : warning: command line option '-wstrict-prototypes' is valid for c/objc but not for CHt [enabled by defaultj
In file included from /public/home/clhou/anaconda3/envs/paddle/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h: 1960:o,
from /public/home/clhou/anaconda3/envs/paddle/lib/python3.8/site-packages /numpy/cor
 .o,from /public/home/clhou/anaconda3/envs/paddle/lib/python3.8/site-packages /numpy/core/include/numpy/arrayobject.h:5,
....from pse.cpp : 738:
/public/home/clhou/anaconda3/envs/paddle/lib/python3.8/site-packages /numpy/core/include/numpy/npy_l7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API，disable it with" “"#define NPY_NO_DEPRECATED_API NPY_1_7_APi_VERSION"[-wcpp]
#warning "Using deprecated NumPy API,disable it with " \-
g++ -pthread -B /public/home/clhou/anaconda3/envs/paddle/compiler_compat -wl, --sysroot=/ -pthread -shared -B /public /home/clhou/anaconda3/envs/paddle/compiler_compat -L/public/home/clhou/anaconda3/envs/paddle/lib -wl, -rpath=/public/home/clhou/anaconda3/envs /paddle/lib -wl, --no-as-needed -wl, --sysroot=/ build/temp.linux-x86_64-3.8/pse.o -o build/lib.linux-x86_64-3.8/pse.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: this_linker was not configured to use sysrootscollect2: error: ld returned l exit status
error: command ' /usr/bin/gt+' failed with exit code 1Traceback (most recent call last):
File "tools/train.py" , line 19i, in <module>main(config, device, logger, vdl_writer)File "tools/train.py" , line 68, in main
post_process_class = build_post_process(config[ 'PostProcess'],
File " 7public/home/clhou/code/ocr_test/PaddleoCR-release-2.5/ppocr/postprocess/__init_.py" ，line49, in build post_process
from .pse_postprocess import PSEPostProcess
File "/public/home/clhou/code/ocr_test/PaddleoCR-release-2.5/ppocr/postprocess/pse_postprocess/__init__.py"', line 15, in <module>
from .pse_postprocess import PSEPostProcess
File " /public/home/clhou/code/ocr_test/PaddleoCR-release-2.5/ppocr/postprocess/pse _postprocess/psepostprocess.py" , line 28, in <module>
from ppocr.postprocess.pse_postprocess.pse import pse
File " /public/home/clhou/code/ocr_test/PaddleoCR-release-2.5/ppocr/postprocess/pse postprocess/pse/__init_.py" , line 24, in <module>
raise RuntimeError(
RuntimeError: Cannot compile pse: /public/home/clhou/code/ocr_test/PaddleoCR-release-2.5/ppocr/postprocess/pse postprocess/pse， if your system is windows，you need to install all the default components of `desktop development using C++`in visual studio 2019+

**Comment by an1018** [comment]
可以看报错信息的最后一句，如果运行环境是windows，需要安装好环境

**Comment by ic1031** [comment]
我是cent os 也是报的这个错误 这种是什么情况呢 我db east都正常跑起来了

**Comment by an1018** [comment]
那先按官方文档跑预测看一下是否报错呢：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_det_psenet.md#41-python%E6%8E%A8%E7%90%86
