### ISSUE TITLE
Apple m2 install error. pip3 install "paddleclas>=2.4.3"

### ISSUE THREAD

**Issue by betashepherd** [PaddlePaddle/PaddleOCR#9038]
Collecting importlib-resources>=1.4.0
  Using cached https://mirror.baidu.com/pypi/packages/be/0f/bd3e7fa47cc43276051c557d3b2fe946664781d2ecf08b05d074e1a3ee59/importlib_resources-5.10.2-py3-none-any.whl (34 kB)
Requirement already satisfied: uc-micro-py in ./workspace/tools/miniconda3/envs/paddle/lib/python3.8/site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]>=2.0.0->gradio->visualdl>=2.2.0->paddleclas>=2.4.3) (1.0.1)
Building wheels for collected packages: faiss-cpu, easydict
  Building wheel for faiss-cpu (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss/faiss/python/swigfaiss.i to faiss/faiss/python/swigfaiss_wrap.cpp
      swig -python -c++ -Doverride= -I/usr/local/include -Ifaiss -o faiss/faiss/python/swigfaiss_wrap.cpp faiss/faiss/python/swigfaiss.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
  Running setup.py clean for faiss-cpu
  Building wheel for easydict (setup.py) ... done
  Created wheel for easydict: filename=easydict-1.10-py3-none-any.whl size=6492 sha256=9615b77e91a541499929e96655240bde08b38eb463f3f54835bcda92bf57c096
  Stored in directory: /Users/work/Library/Caches/pip/wheels/5f/8a/8f/26e0649b04556dae2b94370eb2953973ec2c342cc21e0a346f
Successfully built easydict
Failed to build faiss-cpu
Installing collected packages: wcwidth, faiss-cpu, easydict, ujson, tritonclient, threadpoolctl, pydantic, pycryptodome, psutil, protobuf, prettytable, pkgutil-resolve-name, packaging, orjson, opencv-python, multidict, mdurl, markupsafe, linkify-it-py, kiwisolver, joblib, itsdangerous, importlib-resources, importlib-metadata, h11, grpcio, greenlet, gast, future, fsspec, frozenlist, fonttools, entrypoints, dill, cycler, contourpy, click, charset-normalizer, Babel, attrs, attrdict, async-timeout, anyio, aiofiles, yarl, x2paddle, Werkzeug, uvicorn, starlette, scikit-learn, pandas, onnx, multiprocess, matplotlib, markdown-it-py, jsonschema, Jinja2, httpcore, gevent, bce-python-sdk, aiosignal, mdit-py-plugins, httpx, geventhttpclient, flask, fastapi, altair, aiohttp, Flask-Babel, gradio, visualdl, paddleclas
  Running setup.py install for faiss-cpu ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for faiss-cpu did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      /Users/work/workspace/tools/miniconda3/envs/paddle/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss/faiss/python/swigfaiss.i to faiss/faiss/python/swigfaiss_wrap.cpp
      swig -python -c++ -Doverride= -I/usr/local/include -Ifaiss -o faiss/faiss/python/swigfaiss_wrap.cpp faiss/faiss/python/swigfaiss.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> faiss-cpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ariefwijaya** [comment]
@betashepherd how did you fix it?

**Comment by huyz** [comment]
@ariefwijaya check out https://github.com/PaddlePaddle/PaddleOCR/issues/9526 which may be relevant

**Comment by ariefwijaya** [comment]
@huyz Thanks, but not a solution for my case. I'm using ventura. I've installed this `paddlepaddle-2.4.2-cp310-cp310-macosx_10_14_universal2.whl` package. and it works

**Comment by vikasr111** [comment]
@ariefwijaya Can you please share the mirror link and the version of Python and PaddleOCR which is working on your machine?

**Comment by ariefwijaya** [comment]
> @ariefwijaya Can you please share the mirror link and the version of Python and PaddleOCR which is working on your machine?

You can use requirements from latest version 2.7
