### ISSUE TITLE
pytorch crnn pth 转为onnx后confidence值好像不太对，都是大于1的数，怎么变成小于1的confidence?

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9042]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
pytorch crnn pth 转为onnx后confidence值好像不太对，都是大于1的数，怎么变成小于1的confidence?

**Comment by MissPenguin** [comment]
是不是问错地方了😂

**Comment by nissansz** [comment]
参照paddle2onnx， 加了softmax层就正常了
