### ISSUE TITLE
No module named 'Polygon'，error: command 'cl.exe' failed: None

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#9045]
- 系统环境/System Environment：anaconda python==3.8
- 版本号/Version：PaddleOCR release 2.6
- 运行指令/Command Code：
為了用sourcecode訓練，先用**pip install -r requirements.txt**安裝所需的
出現了以下錯誤
running build_ext
      building 'Polygon.cPolygon' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\src
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DDEFAULT_STYLE=STYLE_LIST -DWITH_NUMPY=1 -DSYSTEM_WIN32=1 -Isrc -IC:\Users\Allen\anaconda3\envs\paddleocr\lib\site-packages\numpy\core\include -IC:\Users\Allen\anaconda3\envs\paddleocr\include -IC:\Users\Allen\anaconda3\envs\paddleocr\Include /Tcsrc/PolyUtil.c /Fobuild\temp.win-amd64-cpython-38\Release\src/PolyUtil.obj
      **error: command 'cl.exe' failed: None**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build lanms-neo Polygon3
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

----------------------------------
後續想要手動裝Polygon，使用**pip install Polygon3 -i https://pypi.tuna.tsinghua.edu.cn/simple**
看起來應該也是一樣的錯，都有error: command 'cl.exe' failed: None
Building wheels for collected packages: Polygon3
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-39\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\src
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DDEFAULT_STYLE=STYLE_LIST -DWITH_NUMPY=1 -DSYSTEM_WIN32=1 -Isrc -IC:\Users\Allen\anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Allen\anaconda3\include -IC:\Users\Allen\anaconda3\Include /Tcsrc/PolyUtil.c /Fobuild\temp.win-amd64-cpython-39\Release\src/PolyUtil.obj
      **error: command 'cl.exe' failed: None**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
Installing collected packages: Polygon3
  Running setup.py install for Polygon3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Polygon3 did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Using NumPy extension!
      running install
      C:\Users\Allen\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-39\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-39\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\src
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DDEFAULT_STYLE=STYLE_LIST -DWITH_NUMPY=1 -DSYSTEM_WIN32=1 -Isrc -IC:\Users\Allen\anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Allen\anaconda3\include -IC:\Users\Allen\anaconda3\Include /Tcsrc/PolyUtil.c /Fobuild\temp.win-amd64-cpython-39\Release\src/PolyUtil.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Polygon3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by MissPenguin** [comment]
这个报错看着是系统的问题，可以网上查一下解决方案，我随便搜了一个：https://blog.csdn.net/qq_44776055/article/details/119431594
