### ISSUE TITLE
'Document' object has no attribute 'pageCount'

### ISSUE THREAD

**Issue by QuadV** [PaddlePaddle/PaddleOCR#9046]
- 系统环境/System Environment：Python 3.10.9
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.3  问题相关组件/Related components：
- 运行指令/Command Code：
Following Paddle OCR [Quickstart ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md) guide: The line 
`result = ocr.ocr(img_path, cls=True)`
breaks with error

- 完整报错/Complete Error Message：
```

      1 def ocrPDF(pdf_path):
      2     """Extract OCR from PDF file
      3 
      4     Args:
   (...)
      8         List: OCR of all pages in Document
      9     """
---> 10     result = ocr.ocr(pdf_path, cls=True)
     11     for idx in range(len(result)):
     12         res = result[idx]

File c:\Users\Viona PC\anaconda3\envs\MyScripts\lib\site-packages\paddleocr\paddleocr.py:544, in PaddleOCR.ocr(self, img, det, rec, cls)
    539 if cls == True and self.use_angle_cls == False:
    540     logger.warning(
    541         'Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process'
    542     )
--> 544 img = check_img(img)
...
---> 96     for pg in range(0, pdf.pageCount):
     97         page = pdf[pg]
     98         mat = fitz.Matrix(2, 2)

AttributeError: 'Document' object has no attribute 'pageCount'

```

**Comment by QuadV** [comment]
The PyMUPDF library has changed naming conventions from camelCase to snake_cased. As a result, calls to loadPage() become load_page().

More details of the name updates are found in the [documentation for Deprecated Names](https://pymupdf.readthedocs.io/en/latest/znames.html?highlight=loadpage).

I've resolved this issue in my own repo by directly making changes to paddleocr\ppocr\utils\utility.py. This is to make the code run as mentioned in the Quickstart Guide.
I would like to contribute to this repo. Please let me know if I can do and if my approach is correct.

**Comment by unclexiao** [comment]
I got the same error. And here is my env:
```bash
Name: paddleocr
Version: 2.6.1.3
Summary: Awesome OCR toolkits based on PaddlePaddle （8.6M ultra-lightweight pre-trained model, support training and deployment among server, mobile, embeded and IoT devices
Home-page: https://github.com/PaddlePaddle/PaddleOCR
```

**Comment by an1018** [comment]
@QuadV Hi，can your modified code be adapted to different PyMUPDF versions and  different system environment

**Comment by QuadV** [comment]
In my setup, I changed it according to my requirement. But, I can add version checks to decide which function is applicable.
