### ISSUE TITLE
如何解決Python套件與sourcecode預測檢測框不一樣

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#9047]
兩者皆是使用Multilingual_PP-OCRv3_det_infer
Python套件與sourcecode預測檢測框都長得不一樣，如何調整sourcecode參數使結果跟Python套件的結果是一樣的

1. Python套件
![image](https://user-images.githubusercontent.com/45616986/218318918-231bc8f9-0a60-4fc6-a205-623f58cd73df.png)

2.sourcecode
python tools/infer/predict_det.py --image_dir={img_path} --det_model_dir="./inference/det/ml/Multilingual_PP-OCRv3_det_infer" --use_gpu=False
![image](https://user-images.githubusercontent.com/45616986/218319231-f44295e0-33a9-48bd-b7d9-5a3e558cecdd.png)

**Comment by 38weiying** [comment]
也想詢問一個檢測框的8個數字個別代表的意思
謝謝

**Comment by MissPenguin** [comment]
应该是因为两种方式使用了不同的模型，第一种chinese_cht是繁体中文，第二种是多语言模型。

**Comment by 38weiying** [comment]
> 应该是因为两种方式使用了不同的模型，第一种chinese_cht是繁体中文，第二种是多语言模型。

第一種的det_model路徑也是連到Multilingual_PP-OCRv3_det_infer
![image](https://user-images.githubusercontent.com/45616986/218402252-c3972264-bf1a-4d31-a9bb-25d182da0fc3.png)
