### ISSUE TITLE
How to pip install Polygon3 and  lanms-neo==1.0.2?

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9048]
pip install Polygon3 and pip install Polygon3   lanms-neo==1.0.2 Will report an error,How to solve it?w

**Comment by daigang896** [comment]
Pip3 install lanms neo=1.0.2 also reported an error.:  
ERROR: Failed building wheel for lanms-neo
Failed to build lanms-neo
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects
