### ISSUE TITLE
模型微调的数据量要求问题

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9050]
现在需要基于预训练模型做finetune，根据文档说明文本检测需要至少500张的文本检测数据集，文本识别至少准备5000张的文本识别数据集，但事实上真实的情况下很难收集到这么多数据样本，有什么办法可以快速生成垂直场景的数据集？

**Comment by LDOUBLEV** [comment]
找一批数据合成工具吧

识别的数据好合成一些

检测的数据合成，你可以通过把图中的文字部分mask掉获得背景图，在背景图上随机贴文本，获得一批检测数据

**Comment by 1061302569** [comment]
> 找一批数据合成工具吧
> 
> 识别的数据好合成一些
> 
> 检测的数据合成，你可以通过把图中的文字部分mask掉获得背景图，在背景图上随机贴文本，获得一批检测数据

找了900张finetune，其他的准确率都上去了，纳税人识别号和地址、电话这两个类准确率分别0.5和0.6上不去，这要如何finetune，怎么加数据集准确率上不去
![1675826706154](https://user-images.githubusercontent.com/44227598/218409503-556b4239-72d3-41fe-8f1b-995fb4da17b2.png)

**Comment by LDOUBLEV** [comment]
在训练的时候增大max_text_length（训练中字符长度<max_text_length的不训练）: https://github.com/PaddlePaddle/PaddleOCR/blob/d78b945608a6599e0b97101ce9f31e2d5ca89469/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml#L17

纳税人识别号和地址、电话 这两个类别的数据多找一批，或者在现有的数据集做一些增强和变换，扩充数据量

**Comment by 1061302569** [comment]
> 在训练的时候增大max_text_length（训练中字符长度<max_text_length的不训练）:
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/d78b945608a6599e0b97101ce9f31e2d5ca89469/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml#L17
> 
> 纳税人识别号和地址、电话 这两个类别的数据多找一批，或者在现有的数据集做一些增强和变换，扩充数据量

谢谢，纳税人识别号和地址、电话 这两个类别的数据多找一批其他的类也要标吗，单独标这两个类训练么

**Comment by LDOUBLEV** [comment]
都标注

你训练识别模型的时候多扩充 纳税人识别号和地址、电话 这两个类别

**Comment by 1061302569** [comment]
> 都标注
> 
> 你训练识别模型的时候多扩充 纳税人识别号和地址、电话 这两个类别
老师你好，我增加了200张数据集目前有1100张了，发现纳税人识别号AP准确率提升不大只有0.7，地址、电话有0.8很多都不准，其他准确率都有0.9，有没有办法提升这一个label的准确率
![4c70e616819b651216a4c4c2f2b6871](https://user-images.githubusercontent.com/44227598/218920252-e41ebe36-465d-4d16-96f7-685983c351d7.png)
