### ISSUE TITLE
表格结构模型训练时长爆炸问题求解

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#9052]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu20.04
- 版本号/Version：Paddle：2.2.0  PaddleOCR：release2.4 
- Linux Gpu：RTX 3090*2
- 数据集：PubTabNet
加载了预训练模型 en_ppocr_mobile_v2.0_table_structure_train
配置文件用的table_mv3.yml
batch_size=32
训练一个epoch要6小时？请问可能出什么问题了？求大神指点
![mmexport1676270249958](https://user-images.githubusercontent.com/83860013/218388075-4a5e2293-b480-4ddf-bae0-a03a9369429e.jpg)

**Comment by LDOUBLEV** [comment]
PubTabNet 数据量很大啊，看下每次iter的batch cost， 如果符合模型预测的时间，那训练是正常的
