### ISSUE TITLE
请问ppocr能支持华为昇腾AscendNPU来训练模型吗？

### ISSUE THREAD

**Issue by FlickerMi** [PaddlePaddle/PaddleOCR#9054]
请问ppocr能支持华为昇腾AscendNPU吗？
想使用昇腾服务器来训练PaddleOCR的模型，请问有可用方案吗？文档中，在训练时没有npu相关的参数。

- 系统环境/System Environment：eulerosv2r8；aarch64；canna5.1；ascend910

**Comment by LDOUBLEV** [comment]
在Global参数里设置use_npu: True参数：https://github.com/PaddlePaddle/PaddleOCR/blob/d78b945608a6599e0b97101ce9f31e2d5ca89469/tools/program.py#L137
