### ISSUE TITLE
一次发送多个请求，会报错

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleOCR#9056]
将paddleocr封装成flask服务后，一次发送多个请求，会不定时出现如下bug
  File "/home/PaddleOCR/ppstructure/predict_system.py", line 141, in __call__
    wht_im)
  File "/home/PaddleOCR/tools/infer/predict_system.py", line 95, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/PaddleOCR/tools/infer/predict_rec.py", line 621, in __call__
    rec_res[indices[beg_img_no + rno]] = rec_result[rno]
IndexError: index 3 is out of bounds for axis 0 with size 3

一开始以为是源码有问题，但是在别的服务器和本地测试后，这个pdf的ocr识别和检测是没问题，说明是并发请求的时候出现的，请查阅

**Comment by LDOUBLEV** [comment]
可能是进程不安全，加进程锁了没

如果是在CPU上预测，设置enable_mkldnn=False试试，

**Comment by kevinuserdd** [comment]
> enable_mkldnn=False

使用table_engine = PPStructure()的时候，默认就是enable_mkldnn=False,这个我没变； 我现在在服务器里部署了服务，调用的时候，一旦一次发送多个请求，就会报上面的错。。这个和负载均衡有关吗？ 其实我测过报错的文件，单独测是没问题的，请问怎么处理？

**Comment by kevinuserdd** [comment]
参考这个https://github.com/PaddlePaddle/PaddleOCR/issues/3701，但是这里面还是没解决；而且加了线程锁会出现这个问题，https://github.com/PaddlePaddle/PaddleOCR/issues/3313 ，报错RuntimeError: could not execute a primitive

**Comment by LDOUBLEV** [comment]
可能是进程不安全导致的

**Comment by lilc-20** [comment]
lock.acquire()
        rec_res, elapse = self.text_recognizer(img_crop_list)
        lock.release()

**Comment by semi-yuhao** [comment]
请问解决了吗，我这边加了进程锁也没用
