### ISSUE TITLE
请问下官方发布的印章歪曲文字识别中类别是哪两个呀

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleOCR#9058]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/28383188/218433220-85bd4127-e511-463b-b703-b9712847b712.png)
num_classes: 2官方文档中这个类别数目为2，请问是哪两个尼？没地方看到

**Comment by LDOUBLEV** [comment]
seal
seal

都写seal就行
