### ISSUE TITLE
crnn+ctc模型训练所用的垂直文本（旋转至水平方向）是如何生成的

### ISSUE THREAD

**Issue by mppsk0** [PaddlePaddle/PaddleOCR#906]

**Comment by tink2123** [comment]
方法与合成水平方向文字一致，只是将字体替换成了垂直字体。

**Comment by mppsk0** [comment]
> 方法与合成水平方向文字一致，只是将字体替换成了垂直字体。

垂直字体哪里可批量下载，有链接吗？

**Comment by zcswdt** [comment]
> > 方法与合成水平方向文字一致，只是将字体替换成了垂直字体。
> 
> 垂直字体哪里可批量下载，有链接吗？

这里有垂直文字生成方法，可以不用垂直字体。https://github.com/zcswdt/Color_OCR_image_generator
