### ISSUE TITLE
识别模型finetue后导出模型有两个文件夹

### ISSUE THREAD

**Issue by truemaomao** [PaddlePaddle/PaddleOCR#9060]
老师好。按着官网finetune.md操作，配置文件用的ch_PP-OCRv3_rec_distillation_bank.yml，预训练模型用的ch_PP-OCRv3_rec_train，训练后用export_model导出模型，发现有student和teacher两个文件夹，这两个文件夹下的文件名都一样，我试了试，都能预测成功。我在实际使用时应该用哪个文件夹比较好呢？有什么判断依据吗？谢谢！

**Comment by LDOUBLEV** [comment]
建议用Student，可以理解为Student精度 > Teacher精度，也不会相差太多
ch_PP-OCRv3_rec_distillation_bank.yml 这个是蒸馏的配置，训练后有两个模型，分别是Student和Teacher，默认保存的best_accuracy模型是对应Student精度最高的模型，export model导出模型后，精度最高的模型也是Student

**Comment by truemaomao** [comment]
好的，谢谢。
