### ISSUE TITLE
parallelEnv object has no attribute "_device_id"

### ISSUE THREAD

**Issue by CongHu-CCNU** [PaddlePaddle/PaddleOCR#9061]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
Please install paddlepaddle-gpu

https://www.paddlepaddle.org.cn/

**Comment by LouisVA** [comment]
Add to the above comment, the right version. In my case with cuda 11.8: https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/windows-pip_en.html#gpu
