### ISSUE TITLE
kie(ser+re)训练模型测试

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleOCR#9069]
PaddleOCR：2.6 
- 运行指令/Command Code：
- python3 ./tools/infer_kie_token_ser_re.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_invoice_zh.yml -o Architecture.Backbone.checkpoints=./output/re_vi_layoutxlm_invoice_zh/best_accuracy/ Global.infer_img=./train_data/2/ -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_invoice.yml -o_ser Architecture.Backbone.checkpoints=./output/ser_layoutxlm_invoice/best_accuracy/
- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/67177370/218671431-5dcff7b6-9e6a-4c39-8a1c-6449e690ffba.png)

**Comment by andyjpaddle** [comment]
出现 floating point exception一般是除0的问题，考虑是数据问题，先把batchsize调为1试试，看是否是数据的问题

**Comment by harshsummit** [comment]
Im recieving the same error on FUNSD dataset

**Comment by LJY6356** [comment]
> 出现 浮点异常一般是除0的问题，考虑是数据问题，先把batchsize调为1试试，看是否是数据的问题

batch1也是相同错误，文件夹放两张照片就没问题，图片数量大于2就有问题

**Comment by harshsummit** [comment]
This is an error with paddleNLP or paddlepaddle, the model trains and tests only works for XFUND dataset, else it always throws error
@LJY6356 @andyjpaddle

**Comment by hbo-lambda** [comment]
不知道你有没有解决。我是这么做的，把自定义的数据集目录结构改成XFUND的样子，就不会报错了。（顺便吐槽句：paddle的代码真是垃圾）

**Comment by harshsummit** [comment]
@hbo-lambda I tried that too, still gives a FLoating Point Exception Error for training RE

**Comment by harshsummit** [comment]
I literally replaced the images and train/test json files of XFUND with FUNSD dataset, just to have the exact same structure, still doesn't work

**Comment by harshsummit** [comment]
@hbo-lambda can you specify what gpu u r using, what cuda cudnn version, what paddle paddle version did you use??

**Comment by hbo-lambda** [comment]
> @hbo-lambda can you specify what gpu u r using, what cuda cudnn version, what paddle paddle version did you use??

说下我的历程：
aistudio下运行的，paddle2.4.1 

看issue里有人提到说是paddle、paddlenlp版本的关系，统统调低了一遍，幺蛾子各种出，放弃
我之前有照着XFUND的格式(甚至目录格式)搞了一遍成功了。今天想优化一遍，没想到又报错了，尝试运行XFUND成功。最后发现，我的train.json中的label字段是QUESTION，ANSWER，改成question和answer后不报这个错了，如果改回大写，错误会复现

**Comment by LJY6356** [comment]
百度官方给出来的不是不区分大小写吗？





------------------ 原始邮件 ------------------
发件人: lam ***@***.***&gt;
发送时间: 2023年2月22日 21:33
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: LJY6356 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] kie(ser+re)训练模型测试 (Issue #9069)





  
@hbo-lambda can you specify what gpu u r using, what cuda cudnn version, what paddle paddle version did you use??
  
说下我的历程：
 aistudio下运行的，paddle2.4.1
 
看issue里有人提到说是paddle、paddlenlp版本的关系，统统调低了一遍，幺蛾子各种出，放弃
 我之前有照着XFUND的格式(甚至目录格式)搞了一遍成功了。今天想优化一遍，没想到又报错了，尝试运行XFUND成功。最后发现，我的train.json中的label字段是QUESTION，ANSWER，改成question和answer后不报这个错了，如果改回大写，错误会复现

**Comment by hbo-lambda** [comment]
> 百度官方给出来的不是不区分大小写吗？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lam ***@***.***&gt; 发送时间: 2023年2月22日 21:33 收件人: PaddlePaddle/PaddleOCR ***@***.***&gt; 抄送: LJY6356 ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [PaddlePaddle/PaddleOCR] kie(ser+re)训练模型测试 (Issue #9069) @hbo-lambda can you specify what gpu u r using, what cuda cudnn version, what paddle paddle version did you use?? 说下我的历程： aistudio下运行的，paddle2.4.1 看issue里有人提到说是paddle、paddlenlp版本的关系，统统调低了一遍，幺蛾子各种出，放弃 我之前有照着XFUND的格式(甚至目录格式)搞了一遍成功了。今天想优化一遍，没想到又报错了，尝试运行XFUND成功。最后发现，我的train.json中的label字段是QUESTION，ANSWER，改成question和answer后不报这个错了，如果改回大写，错误会复现 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你可以试试，先运行XFUND，如果成功了，就把label值改成小写，看会不会报错。我是觉得度娘的文档写的比较水，更新还不及时
