### ISSUE TITLE
关于安装问题

### ISSUE THREAD

**Issue by lvbohui** [PaddlePaddle/PaddleOCR#907]
在`快速安装`文件中，安装流程是怎么样的情况

1. 按照文件中的`1,2,3,4`的顺序全部来一遍？

2. 每个部分单独做都能安装成功？

3. 文件中的`1`, `2`分别是一个安装方法，`3,4`一起做是一个？

**Comment by MissPenguin** [comment]
1. 对的，安装1234顺序来一遍，但是注意每一步里面有针对cuda版本或者cpu、gpu的选择说明，选择安装适合自己机型的版本即可。
2. 第1步需要安装docker，3克隆代码完成了才能安装4的依赖项。
3. 不是。

建议直接按照教程顺序安装。
