### ISSUE TITLE
能否输出多个结果与置信度

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#9074]
假设进行单字识别(即一张图内仅有一个字)，是否能做到显示多个识别结果并按置信度降序排列？
请问有什么修改的方法吗？

**Comment by andyjpaddle** [comment]
可以修改后处理部分，具体代码是这里 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/postprocess/rec_postprocess.py#L119-L120
默认是取最高得分，可以修改一下，取多个分别进行解码。

**Comment by andyjpaddle** [comment]
40是sequence的长度，CTC解码后就是输出的结果，默认是取最大的，你需要对preds的类别score做一个排序，也就是6625这个维度

**Comment by haoxia1** [comment]
> 

是的，我理解的是pred.shape=[1,40,6625]，然后他对6625维度取最大值的索引得到preds_idx.shape=[1,40]，假如我需要得到概率最大的两个汉字，是不是需要让preds_idx.shape=[2,40]？您说的对preds的类别score排序是指排序后取出最大的2个值，来替换掉argmax对吗？ 感谢解答！

**Comment by andyjpaddle** [comment]
1是batchsize，对6625维先排序，然后取出topk就行了

**Comment by haoxia1** [comment]
> 1是batchsize，对6625维先排序，然后取出topk就行了

不好意思，我试了怎么感觉不太对劲啊。对6625排序后，那解码的时候索引和码表对应关系不是变化了吗。比如最大的值的索引应该一直是0对吧，然后用0去decode得到的一直是空白。

您说的是对红框中进行降序排序是吗？
![image](https://user-images.githubusercontent.com/62507136/219260780-c1b72909-c2e2-4e6c-a132-a3827023a671.png)

**Comment by andyjpaddle** [comment]
你要排序的是pred的概率，也就是网络的输出（类似于，0.8， 0.1， 0.1这样），而不是max之后再排序

**Comment by haoxia1** [comment]
对呀，比如下图这是一个pred(shape=(1, 40, 6625)) ，这个输出应该不能动吧，而是需要去找到每一行（共40行）topK的概率的位置，得到K个[1, 40]的pred_idx。如果对pred进行排序，那索引不是会乱吗？
![image](https://user-images.githubusercontent.com/62507136/219262793-910c27de-d6b6-4b25-985b-b349466ea6cb.png)

**Comment by haoxia1** [comment]
问题已解决，感谢您！
我将pred中每一行取出topK概率的索引作为pred_idx，实现了需求。

**Comment by shuyu888** [comment]
@haoxia1 你好请问具体是怎么实现的呢。一张图多个相似文字也可以取topk结果都输出吗。感谢！！
