### ISSUE TITLE
> 通过训练模型去预测，效果还是可以的。但是只要我将模型导出成inference模型。通过inference去预测。效果就会差很多

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9077]
我做了“基于DML蒸馏方法的finetune训练”后。得到训练模型。通过训练模型去预测，效果还是可以的。但是只要我将模型导出成inference模型。通过inference去预测。效果就会差很多，我导出的命令是
```
python3 tools/export_model.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_dml_zzszyfp.yml -o \
Global.pretrained_model="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml/best_accuracy" \
Global.save_inference_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml/"

```
用普通模型预测的命令是：
```
python3 tools/infer_det.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_dml_zzszyfp.yml -o \
Global.infer_img="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgs/" \
Global.pretrained_model="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml/best_accuracy" \
Global.save_res_path="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgsresult/predicts_db.txt"
```

用inference模型预测的命令是：
```
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml/Student" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgsresult/" \
--use_gpu=True
```

这可能是什么原因呢？？？将模型导出的命令改成Global.checkpoints后没有效果

_Originally posted by @rexzhengzhihong in https://github.com/PaddlePaddle/PaddleOCR/issues/9053#issuecomment-1429323103_

**Comment by tink2123** [comment]
请问是否修改了训练配置中的参数，例如后处理ratio或image shape等，如有修改需要在推理时同步修改默认参数:https://github.com/PaddlePaddle/PaddleOCR/blob/a923f35de57b5e378f8dd16e54d0a3e4f51267fd/tools/infer/predict_det.py#L42

**Comment by rexzhengzhihong** [comment]
1.配置文件中的DetResizeForTest.image_shape没有设置。我预测的时候也没有传参
![image](https://user-images.githubusercontent.com/32863094/218949398-34afcafa-3b1e-48ba-a145-a431c3620180.png)
2.ratio参数是用默认的，没有修改
![image](https://user-images.githubusercontent.com/32863094/218949792-37dfa907-0424-4acb-b43f-35a9ca7f05ba.png)

**Comment by rexzhengzhihong** [comment]
@tink2123

**Comment by nefusmzj** [comment]
请问解决了吗？ 我文本识别（perdict_rec）也遇到同样的问题。

**Comment by rexzhengzhihong** [comment]
> 请问解决了吗？ 我文本识别（perdict_rec）也遇到同样的问题。

我预测的时候是用 736，min
![image](https://user-images.githubusercontent.com/32863094/233006912-b0131055-bcc9-4715-8679-5e02a8df0e52.png)
