### ISSUE TITLE
English recognition model predicts chinese characters

### ISSUE THREAD

**Issue by GPhilo** [PaddlePaddle/PaddleOCR#908]
Hello,

I'm testing your system with the following set of arguments (note the models used):

```powershell
python tools/infer/predict_system.py --image_dir ./inference/samples  --det_model_dir .\inference\big\ch_ppocr_server_v1.1_det_infer\  --rec_model_dir .\inference\big\en_ppocr_mobile_v1.1_rec_infer\ --cls_model_dir .\inference\big\ch_ppocr_mobile_v1.1_cls_infer\ --use_angle_cls=True --use_space_char=False --use_gpu=False
```

From what I understand in the documentation, using the model `en_ppocr_mobile_v1.1_rec_infer` should provide English character predictions, however the result is as follows:
![cam1-2019 10 09_07 45 38-00-T2_excerpt](https://user-images.githubusercontent.com/4441724/95578714-9fc50b00-0a34-11eb-858c-9f0cf3edd4ff.png)

The input image is this:
![cam1-2019 10 09_07 45 38-00-T2_excerpt](https://user-images.githubusercontent.com/4441724/95578749-b1a6ae00-0a34-11eb-9ae8-bea5dab88447.png)

Am I doing something wrong? Is there some other file to change that I am not aware of, or other parameters that need to be passed to the inference tool? (I tested with `--rec_char_type=en`, but it raises an `IndexError` when trying to decode the text recognizer's output)

**Comment by LDOUBLEV** [comment]
When recognizing English characters, you need to replace the Chinese dictionary file with the English dictionary file.

**Comment by GPhilo** [comment]
Thanks, I knew I was missing something. Where is the file to replace and how do I tell the system to use a different dictionary?

**Comment by tink2123** [comment]
It can be modified to an English dictionary that supports case by parameter `--rec_char_dict_path`:
```
python tools/infer/predict_system.py --image_dir ./inference/samples  --det_model_dir .\inference\big\ch_ppocr_server_v1.1_det_infer\  --rec_model_dir .\inference\big\en_ppocr_mobile_v1.1_rec_infer\ --cls_model_dir .\inference\big\ch_ppocr_mobile_v1.1_cls_infer\ --use_angle_cls=True --use_space_char=False --use_gpu=False --rec_char_type="ch" --rec_char_dict_path="./ppocr/utils/ic15_dict.txt"
```

**Comment by GPhilo** [comment]
Thank you very much for the clarification, it works correctly now!
