### ISSUE TITLE
PPStructure做关键信息抽取时候，一个question能做为另一个question的answer么？

### ISSUE THREAD

**Issue by smallhaozigithub** [PaddlePaddle/PaddleOCR#9081]
PPStructure做关键信息抽取时候，一个question能做为另一个question的answer么？
如果可以的话id与linking要如何标记，是直接把两个id linking 么？

**Comment by tink2123** [comment]
可以的，作为一组新的关系直接linking即可，
        {
            .......
            "id": 45,  # 文本索引
            "linking": [[45, xxx]], # 当前文本和其他文本的关系 [question, answer]
            "words": xxxx
            .......
         }

**Comment by smallhaozigithub** [comment]
好的，我先试试哈。
