### ISSUE TITLE
关于预测性能，请问如何能加速？

### ISSUE THREAD

**Issue by sunzhaoyang** [PaddlePaddle/PaddleOCR#9086]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/2182116/218950587-d170fda7-9bc2-4540-9cff-2f803d448274.png">

如上图所示，Predict 显示耗时仅 1.6 秒，而整个命令跑完需要耗时 11.7 秒，请问在此种 python 部署形态下有没有什么加速的方式？

**Comment by tink2123** [comment]
跑第一张图时需要进行模型初始化，准备阶段耗时较长，建议测试n张图，去除第一张图的测试时间后计算平均值，比较准确。
