### ISSUE TITLE
数学公式识别训练显存问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#9088]
训练自己的数学公式识别数据集，字典长度为655（官方示例是111），开始训练时没问题，当训练到上千个step时，显存爆掉了

四张显卡训练，训练显卡是3090（24G）
监控显示起初训练显存占用在10个G以内波动，到后面显存占用会越来越大，直到有一张显卡显存爆掉。

请问数学公式训练的显存管理存在bug吗？之前训练正常的OCR任务，显存占用会最终固定在某一个值，
数学公式训练则会显存波动，最后越来越大，最后爆掉。

**Comment by tink2123** [comment]
请问除了修改字典是否还有其他代码修改呢？ 可能存在显存泄漏，我们排查一下

**Comment by ziyaxuanyi** [comment]
修改的地方是配置文件中，关于字典长度涉及到模型结构的地方，111全部改为655，最大长度max_text_length由36改为100，
以及计算loss的rec_can_loss.py的CANLoss初始化的输出self.out_channel=111改为655（与字典长度相对应）。

代码使用的是1月12日下载的代码，可能不是最新版本。

将batch_size改为2后勉强可以训练，每张显卡占用显存最终稳定在某一个值，但各不相同，而且其中有一张占用非常大，达到了19G

**Comment by dongjie-shi** [comment]
你好  你训练的公式识别的ACC 目前是多少啊
