### ISSUE TITLE
为什么版面分析+ocr预测，C++ inference要比python inference慢呢？

### ISSUE THREAD

**Issue by liuwqiang** [PaddlePaddle/PaddleOCR#9090]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddle:2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0
- 版本号/Version：Paddle：2.4.1  PaddleOCR：release/2.6 
c++ inference的benchmark输出
![image](https://user-images.githubusercontent.com/58454582/218963049-a8332e45-4ff9-4e0a-b2e8-a785a5299c7c.png)
python inference的输出,由于python inference 
![image](https://user-images.githubusercontent.com/58454582/218963345-c9603f44-44b3-4569-8bbc-b3218f5ba32c.png)

**Comment by tink2123** [comment]
请问python 和 cpp 预测参数是否一致呢，检查 use_gpu, enable_mkldnn, enable_tensorrt 等等

**Comment by liuwqiang** [comment]
都是一样的 我都检查过了 这是我的启动参数 
./build/ppocr --det_model_dir=/paddleocr/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/paddleocr/ch_PP-OCRv3_rec_infer \
    --image_dir=/paddleocr/imgs \
    --layout_model_dir=/paddleocr/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --type=structure \
    --table=false \
    --layout=true \
	--use_gpu=true \
	--gpu_id=1 \
	--benchmark=true
	
python3 predict_system.py --det_model_dir=/paddleocr/ch_PP-OCRv3_det_infer --rec_model_dir=/paddleocr/ch_PP-OCRv3_rec_infer --layout_model_dir=/paddleocr/picodet_lcnet_x1_0_fgd_layout_cdla_infer --image_dir=/paddleocr/imgs/ --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt --table=false --output=../output --vis_font_path=../doc/fonts/simfang.ttf --benchmark=true --use_gpu=true --gpu_id=0 --layout=true
