### ISSUE TITLE
运行ser+re报错：缺少class_list_xfun.txt，请问这个文件在哪可以下载？

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleOCR#9091]
运行环境都是按照官网链接操作：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md

在执行
# SER + RE模型串联
python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
时报错，No such file or directory:'train_data/XFUND/class_list_xfun.txt',请问class_list_xfun.txt这个文件从哪下载？

**Comment by ghghgha** [comment]
这个好像是存标签名称的文件，可以直接创建一个,然后把标签名称放进去就好了,我记得好像就四个标签，你试试下面的内容创建文件class_list_xfun.txt
```
OTHER
QUESTION
ANSWER
HEADER
```

**Comment by guoxiaoyue111111** [comment]
收到，感谢~我试一下
