### ISSUE TITLE
两个unicode组成的字符，ocr字符集里没法正确显示该字符怎么处理？例如：ㇷ゚ 字源	プの小書き JIS X 0213	1-6-88 Unicode	U+31F7U+309A

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9094]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

两个unicode组成的字符，ocr字符集里没法正确显示该字符怎么处理？例如：ㇷ゚
字源	プの小書き
JIS X 0213	1-6-88
Unicode	U+31F7U+309A

**Comment by tink2123** [comment]
请问会被错误识别成什么字符呢？ 可以将“两个unicode组成的字符” 写在字典的一行中，作为一个字符整体

**Comment by nissansz** [comment]
现在只是准备字符集。写在一行，会不会在训练时convert label时有问题？

**Comment by BaoBaoJianqiang** [comment]
参考https://gitee.com/BaoJianQiang/PaddleOCR，你看我的修改，支持unicode

**Comment by nissansz** [comment]
链接打不开
