### ISSUE TITLE
Unable to decompress the *.tar.gz files of LSVT 

### ISSUE THREAD

**Issue by NNNNAI** [PaddlePaddle/PaddleOCR#9095]
Hello, I have downloaded  [LSVT](https://aistudio.baidu.com/aistudio/datasetdetail/177210/0) dataset files. When I try to decompress theses *.tar.gz file, I got following error: 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/30747212/218991995-60d82847-5081-4f4b-a986-f31638e80e4e.png">

The decompression comand I used is : 
```
tar xvf test_part1_images.tar.gz
```

Thanks for your time, have a nice day~.

**Comment by tink2123** [comment]
Please check if the test_part1_images.tar.gz file has been completely downloaded.
