### ISSUE TITLE
训练dbnet++模型不收敛

### ISSUE THREAD

**Issue by datuizhuang** [PaddlePaddle/PaddleOCR#9098]
数据集为roadtext-1k，用的配置是det_r50_db++_icdar15.yml，把里面的epoch改成了100。目前训练了30个epoch，loss从始至终都在4.9徘徊。请问有人可以分享下训练经验么？

**Comment by LDOUBLEV** [comment]
看下roadtext-1k数据集的分辨率是多少，训练分辨率调大一点试试
