### ISSUE TITLE
关于识别中预训练模型问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#910]
您好，我想训练一个繁体字文字识别模型，字典是需要改变的，请问可以使用你们训练好的中文通用模型作为预训练模型吗？

**Comment by littletomatodonkey** [comment]
你好，可以的，需要修改下你自己的字典，同时设置一下`Global.pretrain_weights`，指向你的预训练模型路径即可

**Comment by zcswdt** [comment]
> 你好，可以的，需要修改下你自己的字典，同时设置一下`Global.pretrain_weights`，指向你的预训练模型路径即可

![image](https://user-images.githubusercontent.com/43515926/95644549-f8a2ab00-0ae9-11eb-8bbe-e26a5c790aab.png)
只需要更改成自己的字典和你们的预训练模型，但是我的新字典里面有的文字不在你们的字典里面，直接使用你们的预训练模型也行吗？

**Comment by littletomatodonkey** [comment]
可以使用，fc层需要重新学习，其他参数可以正常加载

**Comment by zcswdt** [comment]
> fc层需要重新学习

哦哦哦，就是改变这两个地方的参数然后训练就可以了吧，不需要在更改网络啥的。

**Comment by Dajiang1202** [comment]
> 你好，可以的，需要修改下你自己的字典，同时设置一下`Global.pretrain_weights`，指向你的预训练模型路径即可

请问Global.pretrain_weights应该怎么写？
pretrained_models/ch_ppocr_mobile_v2.0_rec_pre
还是pretrained_models/ch_ppocr_mobile_v2.0_rec_pre.tar？
