### ISSUE TITLE
PaddleOCR crnn 训练数据集和测试数据集

### ISSUE THREAD

**Issue by claire199705** [PaddlePaddle/PaddleOCR#9100]
1.提供了两个lmdb格式的数据集，https://aistudio.baidu.com/aistudio/datasetdetail/168907，训练时怎么使用MJSynth和SynthText两个文字识别数据集训练，是需要merge这两个lmdb吗？

2.在IIIT, SVT, IC03, IC13, IC15, SVTP, CUTE数据集上进行评估，是分别评估得到精度，然后除以7取平均值得到最后的精度吗？

**Comment by WenmuZhou** [comment]
1. 训练的时候给这2个数据集所在的文件就行
2. 是的
