### ISSUE TITLE
DB++ need to be updated in paddleocr.py

### ISSUE THREAD

**Issue by ankur92009** [PaddlePaddle/PaddleOCR#9101]
Error: 
The path is a file.
[2023/02/16 06:14:16] ppocr ERROR: det_algorithm must in ['DB']
An exception has occurred, use %tb to see the full traceback.

SystemExit: 0

 
Can you please update it to below -(error logger wont let DB++ to work"
SUPPORT_DET_MODEL = ['DB', 'DB++']
VERSION = '2.6.1.0'
SUPPORT_REC_MODEL = ['CRNN', 'SVTR_LCNet']

**Comment by WenmuZhou** [comment]
now, paddleocr whl only support pp series model

**Comment by ankur92009** [comment]
SO, detection algorithm "DB++" will not work with ppocr? i have used pp series model only but issue is paddleocr.py raise error before passing it to predict file for detection.

**Comment by ankur92009** [comment]
> now, paddleocr whl only support pp series model
SO, detection algorithm "DB++" will not work with ppocr? i have used pp series model only but issue is paddleocr.py raise error before passing it to predict file for detection.
![image](https://user-images.githubusercontent.com/116632658/219312184-dd180a24-cdd7-466a-a79e-851a59d3b119.png)
![Capture1](https://user-images.githubusercontent.com/116632658/219312353-5191ca80-a9d4-4894-bcb8-880b7f8b3ea8.JPG)
