### ISSUE TITLE
Seperate detection and recognition

### ISSUE THREAD

**Issue by Holly-Max** [PaddlePaddle/PaddleOCR#9105]
Hello, I want to use PaddleOCR for recognizing some pH value on the surface of some lab things. But there are too many text on them and the model will produce too man text boxes. If recognizing them all, it would be unbearable while operating on our low-speed device. So I want to filter some text boxes which is too small out to speed up. Which func and how should I use? Or anyone else have better solutions?

**Comment by WenmuZhou** [comment]
No good functions are provided for the time being, but you can try to label a batch of data that only detects the pH value and train the detection model
