### ISSUE TITLE
启动PPOCRLabel有报错failed to load driver: iris，然后点击自动标注闪退

### ISSUE THREAD

**Issue by 18782961008** [PaddlePaddle/PaddleOCR#9108]
- 系统环境/System Environment：ubuntu20.04
- 版本号/Version：Paddle：paddlepaddle=2.4.1  PaddleOCR：PaddleOCR=2.6.0.1 问题相关组件/Related components：PPOCRLabel=2.1.3 （PPOCRLabel2.6编译安装）;PyQT5=5.12.2;opencv-python=4.2.0.32
- 运行指令/Command Code：PPOCRLabel --lang ch / python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[2023/02/16 15:23:57] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
^CTraceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 1730, in openDirDialog
    targetDirPath = ustr(QFileDialog.getExistingDirectory(self,
KeyboardInterrupt
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1676532360 (unix time) try "date -d @1676532360" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000a4a2a) received by PID 674346 (TID 0x7eff4fc42180) from PID 674346 ***]
已放弃 (核心已转储)

**Comment by 18782961008** [comment]
问题已解决，在conda虚拟环境中运行会有库版本冲突问题，python3.9版本过高，重装了anaconda退回py3.8不在虚拟环境中安装就可以了。

**Comment by joshuacwnewton** [comment]
> ```
> libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> ```

Hello. I encountered the same error. I have a solution:

```bash
# This command should remove libffi==3.4.4
conda remove --force libffi
# This command should install libffi==3.4.2
conda install -c conda-forge libffi
```

I reported the issue to conda here: https://github.com/ContinuumIO/anaconda-issues/issues/13205
