### ISSUE TITLE
转换1.1量化后的识别模型失败：op不支持‘moving_average_abs_max_scale’

### ISSUE THREAD

**Issue by qizhen816** [PaddlePaddle/PaddleOCR#911]
编译了最新Paddle-Lite库develop分支的转换工具，从教程里下载的model和params模型可以成功转换，但是我自己量化训练的识别模型转换失败：
```python
Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'moving_average_abs_max_scale'.
```
打印了一下op列表，比下载的模型多了'fake_dequantize_max_ab' 和 'moving_average_abs_max_scale'这两个。  
另外在做转换的时候，用最优模型跑的一轮测试比在训练时的准确率低很多，不知道是什么原因

**Comment by yukavio** [comment]
请问你自己量化训练时用的是Paddle哪个版本。

**Comment by qizhen816** [comment]
@yukavio 是paddlepaddle-gpu 1.8.5.post97

**Comment by baiyfbupt** [comment]
您好，这个是paddle1.8版本的一个bug，目前仅在develop分支修复了，你可以在https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev 下载develop的whl试下，或者等待paddle release 2.0版本再自行训练，2.0版本就不会有这个问题了

**Comment by qizhen816** [comment]
@baiyfbupt 我在尝试develop了 好像有一个静态图的问题，
```
import paddle
paddle.enable_static()
```
这样貌似可以解决？

**Comment by baiyfbupt** [comment]
是的，paddle最近在做一系列的迁移，默认静态图切换为动态图，可能会有一些不兼容的地方，可以自行修改下，如果还有问题也可以等近期2.0 release后OCR库也做相应适配以后再使用

**Comment by malatai** [comment]
>你好，我用的Paddle2.2.0版本，paddle lite2.11，也出现了一样的问题，怎么解决呀
