### ISSUE TITLE
PP-OCRv3 文本检测模型训练描述是否有误

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9111]
针对文档[PP-OCRv3 文本检测模型训练](https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/doc/doc_ch/PPOCRv3_det_train.md)
里面提到训练教师模型，一开始只让下载ResNet50_vd的预训练模型，没要求下载MobileNetV3的预训练模型，但配置文件[ch_PP-OCRv3_det_dml.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.5/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_dml.yml)中Gloabal.pretrained_model值默认为MobileNetV3_large_x0_5_pretrained，是不是前面缺少要求下载MobileNetV3_large_x0_5_pretrained的说明，而在后面训练学生模型才提及到下载这个模型？

@WenmuZhou @andyjpaddle

**Comment by an1018** [comment]
![image](https://user-images.githubusercontent.com/19808900/219607789-59828fca-0fc4-4d15-87c0-c873ea35821d.png)
命令行里有的，resnet50训练教师模型，mobilenetv3训练学生模型，可以对比一下具体的训练命令

**Comment by leoterry-ulrica** [comment]
> ![image](https://user-images.githubusercontent.com/19808900/219607789-59828fca-0fc4-4d15-87c0-c873ea35821d.png) 命令行里有的，resnet50训练教师模型，mobilenetv3训练学生模型，可以对比一下具体的训练命令

如果不提前下载好MobileNetV3模型，直接运行以下命令会提示找不到M哦bileNetV3模型的。
python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_dml.yml -o Architecture.Models.Student.pretrained=./pretrain_models/ResNet50_vd_ssld_pretrained Architecture.Models.Student2.pretrained=./pretrain_models/ResNet50_vd_ssld_pretrained
