### ISSUE TITLE
“藁”等个别字符识别错误

### ISSUE THREAD

**Issue by HzHzHzHzHz** [PaddlePaddle/PaddleOCR#9112]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：W10 X64，python 3.7.5
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.6.1.2 问题相关组件/Related components：
- 运行指令/Command Code：python中ocr语句为"ocr=PaddleOCR(use_angle_cls = True,ocr_version="PP-OCRv3")"
- 完整报错/Complete Error Message：
![0002](https://user-images.githubusercontent.com/49800264/219520360-4fb2eca4-053a-43e0-88a0-bd8521fda3f8.jpg)
上面这个图的识别结果为
![image](https://user-images.githubusercontent.com/49800264/219520853-155385a0-29fa-4b66-a9e2-956b193fcf02.png)

请教一下上面这个图中的“藁”字为什么识别错误？也尝试过指定其他的版本的V3和V2模型，也是识别不出或者识别错误，这是什么原因？有没有优化的办法？

**Comment by an1018** [comment]
如果测试多张图片都不没识别出来，可以尝试添加一些训练图片进行finetune，或者有规律的话可以进行后处理矫正
