### ISSUE TITLE
纯用合成数据来微调识别模型能提高效果吗？

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#9115]
如题，最近在做驾驶证识别，目前只有少量的测试数据，在针对某些字的识别效果不好，如下面的图：
![image](https://user-images.githubusercontent.com/74600923/219535621-84a15063-f2dd-4fc2-99dc-503d3487c339.png)
![image](https://user-images.githubusercontent.com/74600923/219535653-2e0ee360-b7f3-4fcc-88ab-5dbd386ae8cd.png)

因为手里确实没有更多真实场景的图片，只做了一些像下面这种的合成图片：
![image](https://user-images.githubusercontent.com/74600923/219535835-877c168e-5eed-44ec-b016-613e1a69e863.png)

如果训练数据全是这种，能提升模型效果吗？训练时有什么注意事项吗？感谢大佬回复！

**Comment by an1018** [comment]
合成数据可以提升模型效果，但是字体、字号、背景等可以尽可能接近真实场景，且丰富
