### ISSUE TITLE
文字检测训练模型转inference模式后 效果不一致，差很多。去查了预处理的问题，设置了。预测参数怎

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9116]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
 ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
```
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
```
- 运行指令/Command Code：
```shell
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_100/Student" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgsresult/" \
--use_gpu=True \
```
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/32863094/219535873-1d0e42e1-01ca-46e6-8bf5-ecb5412ca39e.png)
![image](https://user-images.githubusercontent.com/32863094/219535956-7566ba96-f1f3-4fca-bc7d-942a79a2e68e.png)
这两个参数，一个是分辨率。一个是设置最大最小。那怎么匹配呢？？

**Comment by rexzhengzhihong** [comment]
```
--det_limit_side_len=736 \
--det_limit_type='min' 
```
inferce预测加了这个就准了。736从哪里来的？

**Comment by rexzhengzhihong** [comment]
@an1018

**Comment by an1018** [comment]
因为导出模型前后预处理不相同，导致预测结果不同，详细的介绍的可以看下这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/detection.md#5-faq

**Comment by rexzhengzhihong** [comment]
> 因为导出模型前后预处理不相同，导致预测结果不同，详细的介绍的可以看下这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/detection.md#5-faq

这个文档的的配置参数是一个image_shape: [736, 1280]  。预测的参数没有设置shape，只有设置最大 最小。怎么一致呢？
@an1018
