### ISSUE TITLE
rec_resnet_stn_bilstm_att 无法转成静态图 

### ISSUE THREAD

**Issue by xiguadong** [PaddlePaddle/PaddleOCR#9118]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
  Architecture:        x86_64
  CPU op-mode(s):      32-bit, 64-bit
  Byte Order:          Little Endian
  CPU(s):              128
  ubuntu18.04
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.0 问题相关组件/Related components：tools/export_model.py
- 运行指令/Command Code：python tools/export_model.py -c configs/rec/rec_resnet_stn_bilstm_att.yml -o Global.pretrained_model=./rec_resnet_stn_bilstm_att/best_accuracy Global.save_inference_dir=./inference/rec_resnet_stn_bilstm_att
- 完整报错/Complete Error Message：长时间卡住，然后killed.

**Comment by an1018** [comment]
可以参考这个issue: #7521

**Comment by xiguadong** [comment]
> 可以参考这个issue: #7521
您好，参照上述issue，修改了导出的命令，日志如下，目前卡在下面这个信息已经超过四十分钟。
python tools/export_model.py -c configs/rec/rec_resnet_stn_bilstm_att.yml -o Global.pretrained_model=./rec_resnet_stn_bilstm_att/best_accuracy -o Global.save_inference_dir=./inference/rec_resnet_stn_bilstm_att
/root/miniconda3/lib/python3.9/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
[2023/02/18 10:30:06] ppocr INFO: train from scratch

模型来源于 https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/doc/doc_ch/algorithm_rec_seed.md

**Comment by xiguadong** [comment]
> 可以参考这个issue: #7521

您好，请问下是指我的命令有问题吗？我仔细核对了下，python tools/export_model.py 应该只有一个 -o 才是正确的，如果使用两个-o，会报如下 log:
 
```bash
(base) root@xxx:~/code/PaddleOCR# python tools/export_model.py -c configs/rec/rec_resnet_stn_bilstm_att.yml -o Global.pretrained_model=./rec_resnet_stn_bilstm_att/best_accuracy -o Global.save_inference_dir=./inference/rec_resnet_stn_bilstm_att
/root/miniconda3/lib/python3.9/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
[2023/02/18 11:10:06] ppocr INFO: train from scratch
```

看起来并不符合export_model.py预期，而且依然也会卡住。
可以麻烦您尝试下该指令，看是否能够复现与我一样的情况吗？模型来源于https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/doc/doc_ch/algorithm_rec_seed.md
