### ISSUE TITLE
PaddleOCR可以输出识别到的字的位置信息吗

### ISSUE THREAD

**Issue by liuxingbo12138** [PaddlePaddle/PaddleOCR#9122]
PaddleOCR可以输出识别到的字的位置信息吗，
百度AI开放平台上的 “通用文字识别（高精度含位置版）”能利用paddleocr实现吗
![image](https://user-images.githubusercontent.com/79137028/219604411-1ae3d411-bcb2-439d-be68-a169f77db033.png)

**Comment by tianchiguaixia** [comment]
#可以预估一下字的位置box
def addcharinfo(ocr_result):
        '''
        :param ocr_result:
        :return: charinfo
        '''
        temp=ocr_result['ocr_result']['words_result']
        for id, line in enumerate(temp):
            width = line['pos'][1]['x'] - line['pos'][0]['x']
            height = line['pos'][3]['y'] - line['pos'][0]['y']
            avg_width = width // len(line['words'])
            start_box_x = line['pos'][0]['x']
            start_box_y = line['pos'][0]['y']
            char_list = []
            for index in range(len(line['words'])):
                char_list.append({'word': line['words'][index],
                                  'box': [{"x": start_box_x, "y": start_box_y},
                                          {"x": start_box_x + avg_width, "y": start_box_y},
                                          {"x": start_box_x + avg_width, "y": start_box_y + height},
                                          {"x": start_box_x, "y": start_box_y + height}]})
                start_box_x = start_box_x + avg_width
            ocr_result['ocr_result']['words_result'][id]["charInfo"] = char_list
        return ocr_result
