### ISSUE TITLE
模型推理过程随着进程数的增加时间也会增加

### ISSUE THREAD

**Issue by zhongJY1998** [PaddlePaddle/PaddleOCR#9124]
请问一下, 我用gunicorn启动单进程进行检测和识别的时候 例如推理时间是1s, 但是我使用两个进程推理的时候时间却是1.5,类似这样增加,这些多进程都在一张上,请问这个什么原因导致的呢?

**Comment by an1018** [comment]
先看看这个文章：https://blog.csdn.net/sinat_29957455/article/details/118739024，后面我们也讨论下，如果有结果可以反馈下~
