### ISSUE TITLE
crnn中日英混合训练，怎么英文感觉比中日文还难训练准？英文数据要怎么准备比较好？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9125]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

crnn中日英混合训练，怎么英文感觉比中日文还难训练准？英文数据要怎么准备比较好？

**Comment by an1018** [comment]
可以从数量、图片识别难易程度(背景干扰等)多方便考虑

**Comment by nissansz** [comment]
数量相当，难易程度一样，只是换了字符

**Comment by an1018** [comment]
那训练难主要是识别效果没有中英文效果好吗，可以发一些训练图片看看

**Comment by nissansz** [comment]
对。就是pillow或text render生成图片，让后各种增强，
![image](https://user-images.githubusercontent.com/41010669/219660959-6de4a16d-0010-4973-b6b0-050670da53ff.png)

**Comment by an1018** [comment]
英文的都比较短吗，可以增加一些长度试试

**Comment by nissansz** [comment]
英文样本是随机组合和单词组合两种，一行25个字符以内

**Comment by nissansz** [comment]
发现自己切割然后单行识别的结果基本都对，用可视化就不行

[(' todo list', [0.5426097, 0.9987727, 0.9987331, 0.48653463, 0.99938583, 0.8509158, 0.98272425, 0.9791829, 0.9995592, 0.9993463])]]
[[('Crnn训练与python版预测', [0.978893, 0.9997801, 0.9991177, 0.998221, 0.95299196, 0.8829281, 0.99133015, 0.9874436, 0.9973182, 0.9999255, 0.9997347, 0.9982666, 0.99917066, 0.96683973, 0.9676605, 0.95273894])]]
[[('DB训练与python版预测', [0.9958389, 0.99395883, 0.9617033, 0.92405915, 0.9906063, 0.9984841, 0.9987373, 0.99990284, 0.99962413, 0.99969757, 0.9990669, 0.9589514, 0.98275054, 0.94961077])]]
[[('imagenet预训练模型', [0.9990073, 0.97956777, 0.9997625, 0.99939203, 0.999619, 0.99952805, 0.99953496, 0.99928755, 0.958218, 0.9654258, 0.92582124, 0.9725935, 0.98955137])]]
[[('服务器端识别模型文件', [0.9907803, 0.97337115, 0.994097, 0.99489874, 0.9702453, 0.85550183, 0.9756562, 0.99194795, 0.97495544, 0.99270356])]]
[[('DB通用模型', [0.9981963, 0.99343747, 0.9792529, 0.99656856, 0.97871304, 0.9870574])]]
[[('手机端部署', [0.9969489, 0.99127156, 0.9941381, 0.9906093, 0.7347378])]]
[[('VWith Triton;推荐使用Savior', [0.47969508, 0.82457834, 0.9945192, 0.99961483, 0.9996457, 0.947054, 0.99841475, 0.99955505, 0.99923956, 0.9977914, 0.9978235, 0.9951402, 0.94444835, 0.95879835, 0.09036893, 0.95694536, 0.9909882, 0.9961637, 0.99891984, 0.99778014, 0.99576294, 0.9541429, 0.9998054])]]
总识别时间为：1.4347677999999995秒
总识别时间为：1434.7677999999994毫秒

![image](https://user-images.githubusercontent.com/41010669/219982575-d1afd803-49ae-4a68-99bd-416a6a8929b0.png)

**Comment by hbulaoma** [comment]
英文用随机不好吧，用英文语料生成可能会好一些。另外就是上面说的，增加长度，到40个字符左右。

**Comment by nissansz** [comment]
40个字符不就超过最长Max len  25了吗？
