### ISSUE TITLE
表格结构模型训练RuntimeError

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#9131]
release2.6分支下 结构模型训练跑不了 RuntimeError: (NotFound) Cannot find gradient of variable generated_tensor_6@GRAD
- 系统环境/System Environment：ubuntu20.04
- 版本号/Version：Paddle：2.2.0  PaddleOCR： release/2.6 
- 运行指令/Command Code：python tools/train.py -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/83860013/219852735-350ad419-8134-479f-8a1e-768c5fa71670.png)

**Comment by huangjun12** [comment]
可以升级一下paddle版本试下
