### ISSUE TITLE
用Python脚本批量识别pdf，偶尔只能识别到部分pdf的第一页

### ISSUE THREAD

**Issue by tantian1498** [PaddlePaddle/PaddleOCR#9132]
没有出现报错，主要代码如下：
for path in file_path:
    save_path = mkdir(path, save_folder)

    file_name_path = os.path.join(base_path, path[0], path[1], path[2])
    file_type = os.path.basename(file_name_path).split('.')[-1]
    if file_type == 'pdf':
        result = ocr.ocr(file_name_path, cls=True)
        # print(result)
        save_file(os.path.join(save_folder, path[0], path[1]), file_name=os.path.basename(file_name_path).split('.')[0]+'.txt',
                  file_content=result)

问题在于 对漏识别的pdf进行单独识别时，可以识别到pdf的全部内容，那么问题似乎是由于批量识别造成的，请问我该怎么解决该问题

**Comment by tantian1498** [comment]
> 

你好 我已经解决了这个问题 原因在于 我没有把 ‘ocr = PaddleOCR(use_angle_cls=True, lang="ch") ’这段代码加入到循环里面 把它放到for循环就行了

**Comment by creo13** [comment]
@tantian1498 Did you ever find a way to optimize this? I tried your solution however this has decreased effeciency by 450%

**Comment by creo13** [comment]
@stevenleeeeeee Any follow up to this problem?
