### ISSUE TITLE
中英日混合模型，数据集是一行含有各个语种的字符好？还是一行只含有一个语种好？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9133]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

中英日混合模型，数据集是一行含有各个语种的字符好？还是一行只含有一个语种好？

**Comment by hbulaoma** [comment]
这个应该都可以，最终结果区别不大。正常的中文语料中也会有少量英文和数字，日文中也会包含一些中文字符。从自动合成样本的角度考虑，肯定是一行只含一个语种的样本容易生成。

**Comment by MissPenguin** [comment]
同意楼上，也没有做过这方面的对比实验。

**Comment by nissansz** [comment]
怎样让模型识别各种字体？全部字体都加入同等数量的训练图片？

**Comment by MissPenguin** [comment]
> 怎样让模型识别各种字体？全部字体都加入同等数量的训练图片？

对，原则上有充足且均衡的数据就行
