### ISSUE TITLE
OCR产业范例20讲 中关于印章检测与识别 中 seal_labeled_datas 如何下载？

### ISSUE THREAD

**Issue by lingyiliu016** [PaddlePaddle/PaddleOCR#9137]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/27277897/219940032-157f7138-001e-46c8-afd0-edf41aad37ec.png">

**Comment by lingyiliu016** [comment]
我其实就想在自己的电脑上跑一下，把整个流程打通，已验证咱们PaddleOCR文档中写的，从而标注自己的数据在finetune。但是现在卡在这一步了。我从网上查了好多，都找不到该数据。实在没办法了，就求助issue

**Comment by wangxinzhe0617** [comment]
他这个文档有问题的好多地方没写清楚。这应该是他自己的数据集跟代码没放出来。

**Comment by MissPenguin** [comment]
这个数据集来自于企业，由于保密协议无法公开，主要参考方案哈

**Comment by lacoboi** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：macOS
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> * 运行指令/Command Code：
> * 完整报错/Complete Error Message：
> 
> <img alt="image" width="1146" src="https://user-images.githubusercontent.com/27277897/219940032-157f7138-001e-46c8-afd0-edf41aad37ec.png">

这个pdf能共享一下嘛 ？
