### ISSUE TITLE
推理时出现Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by XingBin111** [PaddlePaddle/PaddleOCR#914]
下载完模型之后进行推理, 出现Segmentation fault (core dumped)错误, 截图如下:

![image](https://user-images.githubusercontent.com/34578242/95696378-6c20f580-0c6d-11eb-80a4-be52ebf3b7ef.png)

**Comment by littletomatodonkey** [comment]
你的gpu显存是多少呢？试下轻量级模型呢？

**Comment by XingBin111** [comment]
1080ti, 11g显存, 运行上述代码需要多大显存?

**Comment by LDOUBLEV** [comment]
单独试试检测模型或者识别模型的推理，看下是不是有这个问题，不过大概率和环境有关系，你的paddle版本是？

**Comment by XingBin111** [comment]
版本为1.8.3, 单独使用检测模型也出现Segmentation fault (core dumped)

**Comment by raymondci** [comment]
check paddlepaddle-gpu post version，eg.post107 等于cuda10系列，cudnn7系列编译的版本。自己机器cuda，cudnn版本要和它一致

**Comment by XingBin111** [comment]
运行paddle.fluid.install_check.run_check()出现warning:

`device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.`

应该是cudnn版本问题吧.

**Comment by MissPenguin** [comment]
> 运行paddle.fluid.install_check.run_check()出现warning:
> 
> `device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.`
> 
> 应该是cudnn版本问题吧.

嗯，建议使用CUDNN 7.6哈
