### ISSUE TITLE
Pass the Tensor input to OCR

### ISSUE THREAD

**Issue by OrangeSodahub** [PaddlePaddle/PaddleOCR#9148]
I wonder how to input a tensor type to the OCR model, using paddle.io.dataloader to help with the large dataset.
Now it only supports the list type..

**Comment by OrangeSodahub** [comment]
How to set the output type of `Paddle.io.DataLoader` to numpy, rather than `tensor` ??

**Comment by gzzyyxh** [comment]
@OrangeSodahub Good evening, Dr. Yang
`Paddle.io.DataLoader` can return an iterator based on the original dataset. Each element in the data returned by the iterator is a Tensor. Please convert Tensor to Numpy array through `Tensor.numpy()`: 
```
tensor_to_convert = paddle.to_tensor([1.,2.])
tensor_to_convert.numpy()
```
```
array([1., 2.], dtype=float32)
```
If you want to use Python list, please use `paddle.tolist()`([source code](https://github.com/PaddlePaddle/Paddle/blob/release/2.4/python/paddle/tensor/manipulation.py#L1060)): 
```
t = paddle.to_tensor([0,1,2,3,4])
expectlist = t.tolist()
print(expectlist)   #[0, 1, 2, 3, 4]
```
Now this stupid issue can be closed

**Comment by OrangeSodahub** [comment]
God what a **Paddle Expert**

**Comment by OrangeSodahub** [comment]
@gzzyyxh Have you reproduce the stupid issue I raised?  I've already tried to transform tensor to numpy but in this case the iterator will fail:
```
for idx, (imgs, lbls) in enumerate(dataloader):
     print(f"idx: {idx}")
     imgs = [img.cpu().numpy() for img in imgs]
```
Output:
```
idx: 0
```
How to solve this, the god paddle expert ?

**Comment by OrangeSodahub** [comment]
@gzzyyxh Have you reproduce the stupid issue I raised?  I've already tried to transform tensor to numpy but in this case the iterator will fail:
```
for idx, (imgs, lbls) in enumerate(dataloader):
     print(Idx)
     imgs = [img.cpu().numpy() for img in imgs]
```
Output:
```
idx: 0
```
How to solve this, god paddle expert?

**Comment by gzzyyxh** [comment]
@OrangeSodahub  Just using the example code in the manual, the only change is to insert the code that Dr. Yang failed to run:
```
for i, (image, label) in enumerate(loader()):
        print(f"idx: {i}")
        print("image: {} label: {}".format(type(image), type(label)))
        print("image: {} label: {}".format(image.place, label.place))
        image = [img.cpu().numpy() for img in image]        # The stupid issue Dr.Yang(from UCLA) rasied.
        # print(image)
        print(type(image))
        # out = simple_net(image)
        # loss = F.cross_entropy(out, label)
        # avg_loss = paddle.mean(loss)
        # avg_loss.backward()
        # opt.minimize(avg_loss)
        # simple_net.clear_gradients()
        # print("Epoch {} batch {}: loss = {}".format(e, i, np.mean(loss.numpy())))
```
I got the complete output: 
```
idx: 0
...
idx: 1
...
...
idx: 18
image: <class 'paddle.Tensor'> label: <class 'paddle.Tensor'>
image: Place(gpu_pinned) label: Place(gpu_pinned)
<class 'list'>
idx: 19
image: <class 'paddle.Tensor'> label: <class 'paddle.Tensor'>
image: Place(gpu_pinned) label: Place(gpu_pinned)
<class 'list'>
```
There is no evidence to prove that `Tensor. numpy()` is not suitable for this situation. Nobody knows how your stupid `dataloader` came from, and you have not provided more useful error logs. Dr. Yang's `for` loop unexpectedly exited without any errors. The explanation I can guess is that your `dataloader` can only return **one** element, or Dr. Yang should raise another issue:

WHY does my dataloader contain only one element?

**Comment by OrangeSodahub** [comment]
Without transforming to numpy I get all batches
