### ISSUE TITLE
尝试了c++ inference ，主要有以下几个问题：

### ISSUE THREAD

**Issue by wangxiong101** [PaddlePaddle/PaddleOCR#915]
1：当前c++ inference 不支持server模型，可能paddle 版本要提升到2.0，我用的是1.8.4 ；希望可以提供编译好的paddle2.0的库，由于环境是离线的，无法手动编译paddle2.0
2：使用文本方向分类以后，文本识别模型输出信息错误，没有任何文本信息
3：mkldnn批量识别图片是出现core dump

**Comment by WenmuZhou** [comment]
1. 有报错信息吗
2. 不适用文本分类的情况下输出是正常的吗，能否提供图片作为测试

**Comment by wangxiong101** [comment]
1：没有报错信息 水平图片 进去后返回img一样 但是会调到pred_idx.size() <1e-3的continue去

**Comment by littletomatodonkey** [comment]
windows下2.0的预测库可以从这里下载：https://paddle-wheel.bj.bcebos.com/2.0.0-beta0/win-infer/mkl/cpu/fluid_inference_install_dir.zip
linux下2.0的预测库可以从这里下砸：https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-cpu-avx-mkl/fluid_inference.tgz
