### ISSUE TITLE
KIE的SER训练precision和hmean一直为0

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9151]
paddlepaddle：2.3.2
paddlenlp：2.5.1

数据集：wget https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar

训练：
`python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.pretrained=./pretrain_models/ser_vi_layoutxlm_xfund_pretrained/best_accuracy Global.save_epoch_step=50 Global.eval_batch_step=[0,200] Global.epoch_num=100 Optimizer.lr.learning_rate=0.001 Train.dataset.data_dir=./XFUND/zh_train/image Train.dataset.label_file_list=['./XFUND/zh_train/train.json'] Train.loader.batch_size_per_card=4 Train.loader.num_workers=1 Eval.dataset.data_dir=./XFUND/zh_val/image Eval.dataset.label_file_list=['./XFUND/zh_val/val.json'] Eval.loader.num_workers=1`

输出日志一直都显示0.
precision:0
recall:0
hmean:0

请问有可能什么原因导致的？

**Comment by leoterry-ulrica** [comment]
问题已解决
使用配置文件默认参数，只修改自定义数据集路径，训练就不会出现一直为0的情况。

**Comment by ericosmic** [comment]
> 问题已解决 使用配置文件默认参数，只修改自定义数据集路径，训练就不会出现一直为0的情况。

我的训练中也出现同样问题，我怀疑是新的关键字字典造成的结果。 请问你训练中是否使用了新的字典？
