### ISSUE TITLE
pgnet 训练中文的问题。

### ISSUE THREAD

**Issue by wangxinzhe0617** [PaddlePaddle/PaddleOCR#9154]
使用ppocr中的pgnet训练中文数据集合，使用字典字符数为6623，想问一下图中红色框住的地方还需要修改为字符数吗？（ppocr给出的参考文档中没修改，想再次确认一下。）
![IMG20230220153711](https://user-images.githubusercontent.com/38687226/220046611-225e3558-e70a-487d-bc16-f63bd5d24496.png)

**Comment by LDOUBLEV** [comment]
需要修改

**Comment by wangxinzhe0617** [comment]
> 需要修改

好的谢谢，我修改为字符个数可以跑通了。
