### ISSUE TITLE
Did not get best_accuracy model after training?

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleOCR#9157]
According to the save_model_dir field set in the configuration file, the following parameters will be saved:
output/
├── best_accuracy.pdopt
├── best_accuracy.pdparams
├── best_accuracy.states
├── config.yml
├── iter_epoch_3.pdopt
├── iter_epoch_3.pdparams
├── iter_epoch_3.states
├── latest.pdopt
├── latest.pdparams
├── latest.states
└── train.log

But in my case i did not get best_accuracy model .....i got below files only.

├── config.yml
├── iter_epoch_3.pdopt
├── iter_epoch_3.pdparams
├── iter_epoch_3.states
├── latest.pdopt
├── latest.pdparams
├── latest.states
└── train.log

Train scrpt:
!python3 tools/train.py -c configs/rec/PP-OCRv3/multi_language/devanagari_PP-OCRv3_rec.yml -o Global.pretrained_model=./pretrain_models/devanagari_PP-OCRv3_rec_train/best_accuracy

Config file:

Global:
debug: false
use_gpu: false
epoch_num: 5
log_smooth_window: 20
print_batch_step: 10
pretrained_model: ./pretrain_models/devanagari_PP-OCRv3_rec_train/best_accuracy.pdparams
save_model_dir: ./output/v3_devanagari_mobile
save_epoch_step: 3
eval_batch_step: [0, 2000]
cal_metric_during_train: true
pretrained_model:
checkpoints:
save_inference_dir:
use_visualdl: false
infer_img: doc/imgs_words/nepali/ne_1.jpg
character_dict_path: ppocr/utils/dict/devanagari_dict.txt
max_text_length: &max_text_length 25
infer_mode: false
use_space_char: true
distributed: true
save_res_path: ./output/rec/predicts_ppocrv3_devanagari.txt

Optimizer:
name: Adam
beta1: 0.9
beta2: 0.999
lr:
name: Cosine
learning_rate: 0.001
warmup_epoch: 5
regularizer:
name: L2
factor: 3.0e-05

Architecture:
model_type: rec
algorithm: SVTR
Transform:
Backbone:
name: MobileNetV1Enhance
scale: 0.5
last_conv_stride: [1, 2]
last_pool_type: avg
Head:
name: MultiHead
head_list:
- CTCHead:
Neck:
name: svtr
dims: 64
depth: 2
hidden_dims: 120
use_guide: True
Head:
fc_decay: 0.00001
- SARHead:
enc_dim: 512
max_text_length: *max_text_length

Loss:
name: MultiLoss
loss_config_list:
- CTCLoss:
- SARLoss:

PostProcess:
name: CTCLabelDecode

Metric:
name: RecMetric
main_indicator: acc
ignore_space: False

Train:
dataset:
name: SimpleDataSet
data_dir: ./train_data/dataset/
ext_op_transform_idx: 1
label_file_list:
- ./train_data/dataset/rec_gt_train.txt
transforms:
- DecodeImage:
img_mode: BGR
channel_first: false
- RecConAug:
prob: 0.5
ext_data_num: 2
image_shape: [48, 320, 3]
- RecAug:
- MultiLabelEncode:
- RecResizeImg:
image_shape: [3, 48, 320]
- KeepKeys:
keep_keys:
- image
- label_ctc
- label_sar
- length
- valid_ratio
loader:
shuffle: true
batch_size_per_card: 12
drop_last: true
num_workers: 4
Eval:
dataset:
name: SimpleDataSet
data_dir: ./train_data/dataset
label_file_list:
- ./train_data/dataset/rec_gt_val.txt
transforms:
- DecodeImage:
img_mode: BGR
channel_first: false
- MultiLabelEncode:
- RecResizeImg:
image_shape: [3, 48, 320]
- KeepKeys:
keep_keys:
- image
- label_ctc
- label_sar
- length
- valid_ratio
loader:
shuffle: false
drop_last: false
batch_size_per_card: 12
num_workers: 4

**Comment by LDOUBLEV** [comment]
eval_batch_step: [0, 2000]

The above parameters indicate that it is evaluated once after 2000 iterations. If you have very little data and the number of iterations does not reach 2000, no evaluation will be performed and the best_accuracy model will not be saved.

**Comment by TapendraBaduwal** [comment]
@LDOUBLEV Thank you ...issue solved

**Comment by midtlz** [comment]
I have the same problem, and modified eval_ batch_ Step, but there was a problem during the training: 

[2023/02/21 19:40:56] ppocr ERROR: When parsing line train/2202220320_crop_0.jpg 2202220320
, error happened with msg: Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR/ppocr/data/simple_dataset.py", line 128, in __getitem__
    label = substr[1]
IndexError: list index out of range

......

eval model::   0%|          | 0/5 [00:00<?, ?it/s]
LAUNCH INFO 2023-02-21 19:40:59,106 Exit code 1

pls give me some suggestions. 

thk

**Comment by TapendraBaduwal** [comment]
@midtlz Can you share the config file and dataset, dear friend?

**Comment by midtlz** [comment]
@TapendraBaduwal loader:

Thank you, bro.
I solved my problem yesterday.
I modified the batch_ size_ per_ card & num_workers parameter.
What I set up before is batch_size_per_card: 4;
                                       num_workers: 4;
now i modified it to batch_size_per_card: 4;
                                num_workers: 2;

haha, this is really funny problem.  ^.^

configuration information
    shuffle: true
    batch_size_per_card: 4
    drop_last: true
    num_workers: 2
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: PaddleOCR/train_data
    label_file_list:
    - PaddleOCR/train_data/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 4
    num_workers: 2
