### ISSUE TITLE
我可以基于“基于PubLayNet训练的模型”，在我自己的数据上finetune吗？

### ISSUE THREAD

**Issue by shihanmax** [PaddlePaddle/PaddleOCR#9158]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

你好，我正在参照https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppstructure/layout/train_layoutparser_model_ch.md ，在自有数据上训练版面分析模型，页面https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppstructure/layout/README_ch.md#:~:text=%7B0%3A%22Table%22%7D-,PubLayNet,-lp%3A//PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet 上提到，paddled Detection 已经在publayNet上finetune过一个模型，我通过这个链接也将模型参数下载下来进行了测试，推理是正常的。

但是链接提供的模型好像是export之后的推理模型，请问是否有原始checkpoint提供呢？谢谢

**Comment by LDOUBLEV** [comment]
参考这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list_en.md

**Comment by shihanmax** [comment]
谢谢。

**Comment by mllife** [comment]
@shihanmax , can you share experience and some template code on using "[ppyolov2_r50vd_dcn_365e_publaynet](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppstructure/layout/README_ch.md#:~:text=%7B0%3A%22Table%22%7D-,PubLayNet,-lp%3A//PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet)" model pretrained on publaynet.

Your help is really appreciated.
I am unable to get any output from this model; https://github.com/PaddlePaddle/PaddleOCR/issues/10476
