### ISSUE TITLE
Android Demo cannot work with other detect or recognition model

### ISSUE THREAD

**Issue by llf10811020205** [PaddlePaddle/PaddleOCR#916]

**Comment by llf10811020205** [comment]
你好， 可以说明一下安卓默认下载的检测识别模型 对应的模型结构和版本吗？因为在 替换v1.1训练后的模型，demo闪退

**Comment by 772865705** [comment]
> 
> 
> 你好， 可以说明一下安卓默认下载的检测识别模型 对应的模型结构和版本吗？因为在 替换v1.1训练后的模型，demo闪退

我也是替换V1.1训练后的nb模型就会闪退，但是demo里面对替换V1.1的描述是还要换一个什么东西，这个描述有点轻描淡写，看不懂学不会……
