### ISSUE TITLE
ctc loss和center loss组合在一起的具体展开公式应该怎么写呢？

### ISSUE THREAD

**Issue by fishstarr** [PaddlePaddle/PaddleOCR#9160]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
你好，我参考的是这个https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/enhanced_ctc_loss.md
想要知道Lc-ctc具体的展开公式，谢谢噢

**Comment by nissansz** [comment]
导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。

**Comment by fishstarr** [comment]
在配置文件中center_file_path这里添加train_center.pkl路径




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月9日(星期五) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] ctc loss和center loss组合在一起的具体展开公式应该怎么写呢？ (Issue #9160)





 
导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。

**Comment by nissansz** [comment]
导出的center loss文件train_center.pkl怎么使用？加入yml文件报错。




#Loss:

#  name: CTCLoss

Loss:

  name: CombinedLoss

  loss_config_list:

  - CTCLoss:

      use_focal_loss: false

      weight: 1.0

  - CenterLoss:

      weight: 0.05

      num_classes: 63466

      feat_dim: 512

      center_file_path: C:/F/pycharm2020.2/PaddleOCR-release-2.5/train_center.pkl

  # you can also try to add ace loss on your own dataset

  - ACELoss:

      weight: 0.1




 报错如下




 Traceback (most recent call last):

  File "./tools/train.py", line 191, in <module>

    main(config, device, logger, vdl_writer)

  File "./tools/train.py", line 164, in main

    program.train(config, train_dataloader, valid_dataloader, device, model,

  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train

    loss = loss_class(preds, batch)

  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__

    return self._dygraph_call_func(*inputs, **kwargs)

  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func

    outputs = self.forward(*inputs, **kwargs)

  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward

    loss = loss_func(input, batch, **kargs)

  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in __call__

    assert isinstance(predicts, (list, tuple))

AssertionError







如果只用use_focal_loss: True，可以训练，这种就是启用了Focal-CTC Loss？




Loss:

  name: CombinedLoss

  loss_config_list:

  - CTCLoss:

      use_focal_loss: True

      weight: 1.0















--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: fishstarr  ***@***.***>
 

 
 发送时间: 2023-06-10 15:23:39
 

 
 收件人:PaddlePaddle/PaddleOCR ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Comment ***@***.***> 

 
 主题: Re: [PaddlePaddle/PaddleOCR] ctc loss和center loss组合在一起的具体展开公式应该怎么写呢？ (Issue #9160)
 





 在配置文件中center_file_path这里添加train_center.pkl路径 
 
 
 
 
 ------------------&nbsp原始邮件&nbsp------------------ 
 发件人: ***@***.***&gt 
 发送时间: 2023年6月9日(星期五) 晚上6:46 
 收件人: ***@***.***&gt 
 抄送: ***@***.***&gt ***@***.***&gt 
 主题: Re: [PaddlePaddle/PaddleOCR] ctc loss和center loss组合在一起的具体展开公式应该怎么写呢？ (Issue #9160) 
 
 
 
 
 
 
 导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。
