### ISSUE TITLE
ocr识别cpu消耗和用时问题

### ISSUE THREAD

**Issue by cmingxu** [PaddlePaddle/PaddleOCR#9161]
通过paddle-ocr识别火车票样例，模型选择服务器版， 用时6.5s，CPU最高到100%， 这是否正常 ？

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
linux
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
2.4.1

- 运行指令/Command Code：

none
- 完整报错/Complete Error Message：

none

**Comment by andyjpaddle** [comment]
cpu测试推荐开启mkldnn，另外速度测试需要开启warmup和benchmark并且在批量数据下测试会更准确

**Comment by mklp** [comment]
> cpu测试推荐启动mkldnn，另外速度测试需要启动warmup和benchmark并在批量数据下测试会更准确

鲲鹏920好像开启不了mkldnn，识别图片非常慢有解决办法吗？
