### ISSUE TITLE
pdserving不会自己释放显卡内存问题

### ISSUE THREAD

**Issue by HysUnknown** [PaddlePaddle/PaddleOCR#9162]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7 nvidia-docker
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle-serving-app        0.8.3
paddle-serving-client     0.8.3
paddle-serving-server-gpu 0.8.3.post112
paddlepaddle-gpu          2.4.1.post112
- 运行指令/Command Code：
python3.9 web_service.py --config=config.yml &>log.txt &
- 完整报错/Complete Error Message：
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle_infer::Tensor::CopyFromCpu<float>(float const*)
1   float* phi::DeviceContext::Alloc<float>(phi::TensorBase*, unsigned long, bool) const
2   phi::DeviceContext::Impl::Alloc(phi::TensorBase*, phi::Place const&, paddle::experimental::DataType, unsigned long, bool) const
3   phi::DenseTensor::AllocateFrom(phi::Allocator*, paddle::experimental::DataType, unsigned long)
4   paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::Allocator::Allocate(unsigned long)
6   paddle::memory::allocation::Allocator::Allocate(unsigned long)
7   paddle::memory::allocation::Allocator::Allocate(unsigned long)
8   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
9   std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
10  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 10.500000MB memory on GPU 0, 7.926758GB memory has been allocated and available memory is only 2.625000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:95)
. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
For details about error message, see PipelineServingLogs/pipeline.log
==> total number of test imgs:  2
![FB7Q}1`TES _HT$2~_8484](https://user-images.githubusercontent.com/39686680/220227520-2ab2fba6-f1a8-4b1b-9961-aafdf551d0b8.png)

**Comment by andyjpaddle** [comment]
目前paddleserving不继续维护了，后续会迁移到FastDeploy上使用Paddle+Triton的方案，可以试试，参考这个：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3/serving

**Comment by HysUnknown** [comment]
好的，谢谢
