### ISSUE TITLE
多个进程推理的时候 copy_to_cpu() 耗时呈线性增加 

### ISSUE THREAD

**Issue by zhongJY1998** [PaddlePaddle/PaddleOCR#9163]
请问当单进程进行ocr的时候耗时很正常, 但是用多进程推理的时候 copy_to_cpu()函数的耗时呈线性增加, 有什么好办法解决吗?

**Comment by andyjpaddle** [comment]
你好，可以提供下复现代码和耗时数据吗

**Comment by zhongJY1998** [comment]
![9267ff5b659dced70b596339374673c](https://user-images.githubusercontent.com/107853193/220502863-82f8c9f9-7799-4ac6-adb6-7df52cae2b00.png)
![cc0e0d13f8306e6f41812d03960251c](https://user-images.githubusercontent.com/107853193/220502869-f423e9ca-3b34-4b5d-8553-7abc99725330.png)
![e5e0ec42bb699994f5be28a604c5a23](https://user-images.githubusercontent.com/107853193/220502878-aa71e17b-0f1d-470c-b9ea-09c16d43d64a.png)
![11](https://user-images.githubusercontent.com/107853193/220503577-a074ae40-c4cb-4fc9-8abb-b1eb5e947bd3.jpg)
![22](https://user-images.githubusercontent.com/107853193/220503637-9c8af2df-d846-4f2a-aadd-8337b4c2c396.jpg)

服务是用gunicorn启动的, 这是1个进程, 2个进程, 3个进程打印的检测和识别过程中从copy_to_cpu()的耗时

**Comment by zhoutianzi666** [comment]
GPU上推理是异步执行的，直到你调用copy_to_cpu这个函数，才会同步。因此你打印的耗时不仅仅是拷贝时间，还包含部分执行时间。

**Comment by zhongJY1998** [comment]
但是多进程并行执行时间耗时却是在增长, 并且是随着进程数的增加而增加。
