### ISSUE TITLE
使用trt量化推理时，第一次运行能够成功，但再次运行无法成功，但将模型文件夹下生成的det_trt_dynamic_shape.txt删除后又可以了，请问这是怎么回事

### ISSUE THREAD

**Issue by chaoshixie** [PaddlePaddle/PaddleOCR#9165]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04 python3.7
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：python tools/infer/predict_det.py ... --use_tensorrt=True --precision='int8'
- 完整报错/Complete Error Message：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Fatal Python error: Segmentation fault

Current thread 0x00007f0372f1e3c0 (most recent call first):
  File "/PDF-OCR/PaddleOCR-release-2.4/drawing-ocr-master/PaddleOCR/tools/infer/utility.py", line 277 in create_predictor
  File "tools/infer/predict_det.py", line 146 in __init__
  File "tools/infer/predict_det.py", line 292 in <module>

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::DeleteQuantDequantLinearOpPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1676960786 (unix time) try "date -d @1676960786" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x2a179) received by PID 172409 (TID 0x7f0372f1e3c0) from PID 172409 ***]

Segmentation fault (core dumped)

**Comment by andyjpaddle** [comment]
用的哪个模型呢

**Comment by chaoshixie** [comment]
用的PaddleOCR/configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml进行QAT训练的

**Comment by chaoshixie** [comment]
是参考这个进行量化训练的，唯一区别是在quant_config中加入了onnx_format=True（在PaddleSlim团队上看到的处理），训练时无异常且不开启tensorrt推理也无异常，就是使用了use_tensorrt=True后出现了上面的问题

**Comment by andyjpaddle** [comment]
> PaddleOCR-release-2.4

使用的是最新的2.6分支的代码吗？

**Comment by chaoshixie** [comment]
没，量化训练是ocr2.4版本，推理我2.4和2.6都试了

**Comment by chaoshixie** [comment]
好吧，刚重新训了1轮，发现是onnx_format=True的问题，不用这种格式保存就没事，但不这么保存，那体积小的优点不就没了（原来如果是200M，量化训练后还是200M）

**Comment by andyjpaddle** [comment]
导出的量化模型，参数精度仍然是FP32，但是参数的数值范围是int8，所以体积基本不变

**Comment by chaoshixie** [comment]
是的，这我知道，只是设置onnx_format=True可以看到体积的变化（出处：https://github.com/PaddlePaddle/PaddleSlim/issues/1628），但无法跑通，是有bug么；还有我使用 --use_tensorrt=True --precision='int8'运行在  Detected invalid timing cache, setup a local cache instead  打印的日志处卡了很久，这是为什么

**Comment by andyjpaddle** [comment]
可以看下是不是测试图片的问题

**Comment by chaoshixie** [comment]
不是，我不用tensorrt就没问题
