### ISSUE TITLE
如何在做版面分析的同时，能够将det的结果保存下来.

### ISSUE THREAD

**Issue by zalmanchen** [PaddlePaddle/PaddleOCR#9166]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle 2.3.2：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
paddleocr --image_dir=paddle_ocr_results/u0006809.pdf --type=structure --det true --lang=ch --output=paddle_layout_results
- 完整报错/Complete Error Message：
无报错

如何在做版面分析的同时，能够将det的结果保存下来，以方便做接下来的数据处理

**Comment by andyjpaddle** [comment]
输出结果已经包含了det的结果
