### ISSUE TITLE
paddleocr 样本间隙太大导致检测框分开识别

### ISSUE THREAD

**Issue by Currf** [PaddlePaddle/PaddleOCR#9167]
![result13](https://user-images.githubusercontent.com/80883358/220275749-a6b96437-231f-497f-894d-82f988de5819.jpg)
如图 像这种16和48，数据标注的时候我是直接标注一整行的，但检测结果还是分开的，我想让他们识别为同一个检测框变成1648，这种情况应该怎么改善呢？

**Comment by wangxinzhe0617** [comment]
> ![result13](https://user-images.githubusercontent.com/80883358/220275749-a6b96437-231f-497f-894d-82f988de5819.jpg) 如图 像这种16和48，数据标注的时候我是直接标注一整行的，但检测结果还是分开的，我想让他们识别为同一个检测框变成1648，这种情况应该怎么改善呢？

建议自己写一个程序检测中心点的位置，然后按照中心点y坐标进行字符合并，就可以拼在一起了。

**Comment by Currf** [comment]
> > ![result13](https://user-images.githubusercontent.com/80883358/220275749-a6b96437-231f-497f-894d-82f988de5819.jpg) 如图 像这种16和48，数据标注的时候我是直接标注一整行的，但检测结果还是分开的，我想让他们识别为同一个检测框变成1648，这种情况应该怎么改善呢？
> 
> 建议自己写一个程序检测中心点的位置，然后按照中心点y坐标进行字符合并，就可以拼在一起了。

感谢回复，但这个方法在场景里面就不行了，比如场景里面有竖直的 有横着的 不能只识别y坐标。而且不同的物件的文本，他们如果y坐标都一样的话 就会把他们都识别到一起
