### ISSUE TITLE
编译安装npu版成功，且能识别到卡，执行却报不是npu版本

### ISSUE THREAD

**Issue by Wuguangnann** [PaddlePaddle/PaddleOCR#9169]
如下图，编译安装npu版paddle成功，能识别卡信息，但是训练时失败，定位到是校验不通过。
paddle-custom-npu     0.0.0
paddleocr             2.6.1.0
paddlepaddle          0.0.0

![image](https://user-images.githubusercontent.com/110798296/220287169-256c02b4-1851-4df5-a8cb-c238c4a21bc1.png)

![image](https://user-images.githubusercontent.com/110798296/220286868-8266fb47-a3b3-4661-bd3e-9701d04ed671.png)

**Comment by andyjpaddle** [comment]
确认一下是否安装成功了

**Comment by Wuguangnann** [comment]
> 这是安装成功了吧

![image](https://user-images.githubusercontent.com/110798296/220345421-0668a79b-e64c-4f00-9bbc-74dd85114158.png)

**Comment by andyjpaddle** [comment]
这个可以到paddle主repo下提一个issue

**Comment by Randy-1009** [comment]
python -c "import paddle; paddle.utils.run_check()"
跑这个命令会提示你在NPU上works well吗
