### ISSUE TITLE
印章弯曲文本识别问题

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleOCR#9170]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：dygraph
- 运行指令/Command Code：python3 tools/infer/predict_system.py --image_dir=data/1ttt.jpg --det_model_dir=inference/det_db++/ --rec_model_dir=inference/rec_svtr/ --use_angle_cls=false
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/28383188/220293956-87baa05b-3898-4543-883d-3c0490baf874.png)

模型代码：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md#51------------
我是将印章弯曲文字检查和识别代码转换成推理模型，然后tools/infer/predict_system.py脚本串联起来推理，单个模型检测时可以的，然下：
![image](https://user-images.githubusercontent.com/28383188/220294642-78d9f9fe-bd9b-481c-8f01-7c90997a4313.png)

但是我截图看下了下文字检测的图，发现并没有将弯曲文字拉直给文字检测模型，
![image](https://user-images.githubusercontent.com/28383188/220294993-afb6cf88-0138-40c2-8e6d-3aec1a73fc8f.png)
导致识别不了弯曲文字，我想问下这个是哪里问题尼，需要自己写代码进行极坐标转换吗？

请问怎么正确识别这个弯曲文字尼？

**Comment by LeFuGang** [comment]
我知道什么问题了，是
![image](https://user-images.githubusercontent.com/28383188/220499667-6d0f5947-bbfe-469e-b8cf-d83aaaf5b4b2.png)
这个地方的参数没改，但是还有报错
![image](https://user-images.githubusercontent.com/28383188/220499746-10dc3f81-b0f9-40eb-aca6-2715ba476fa2.png)
大佬帮忙看下

**Comment by andyjpaddle** [comment]
降低下opencv版本试试
`
opencv-python<=4.6.0.66
opencv-contrib-python<=4.6.0.66
`

**Comment by LeFuGang** [comment]
> -

因为坐标点需要都是4*2的，我手动改了，就可以了

**Comment by LeFuGang** [comment]
官方不知道有没有注意到这个bug，可以修复下，

**Comment by wangxinzhe0617** [comment]
大佬哪里有将弯曲文字拉直的代码啊。我也在训练弯曲文字，我输出的坐标全是四个点的。没发现哪里可以将弯曲文字拉直。求指教。

**Comment by BaoBaoJianqiang** [comment]
craft，可以拉直

**Comment by xurning** [comment]
> > 
> 
> 因为坐标点需要都是4*2的，我手动改了，就可以了

麻烦问下4*2这个在哪里进行修改？

**Comment by wanggoudanscd** [comment]
getPerspectiveTransform中使用浮点数

**Comment by guangyangL** [comment]
> 
请问大佬找到了吗

**Comment by SiriusWy** [comment]
> 大佬哪里有将弯曲文字拉直的代码啊。我也在训练弯曲文字，我输出的坐标全是四个点的。没发现哪里可以将弯曲文字拉直。求指教。

stn的作用就是将弯曲文字拉直，配置文件的这里
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/9431785/66fb24bb-3021-4196-a375-edd89353e471)
