### ISSUE TITLE
如何同时识别英文和华文, 或者超过一个语言

### ISSUE THREAD

**Issue by similang** [PaddlePaddle/PaddleOCR#9171]
如题，用着PaddleOCR， 发现，华文的模型可以认识英文，可是，不能识别空格； 如果只用英文的模型，确又不能识别华文， 这又什么办法解决？

**Comment by andyjpaddle** [comment]
华文是什么语言？可以使用通用中英文模型

**Comment by similang** [comment]
我是指中文； 

如果用中英文模型，空格全部不能识别

**Comment by andyjpaddle** [comment]
use_space_char设置为true试试，或者提供下测试图片
