### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9172]
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by andyjpaddle** [comment]
make sure your cuda and cudnn is installed rightly， and make sure the version is matched with paddle

**Comment by segu-L** [comment]
export LD_LIBRARY_PATH= libcudart.so.10.2 file' path
such as
export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib            
I use conda enviorment

**Comment by Mrfuhang** [comment]
> 



> 
After configuring the environment according to your configuration, it still reports the same error：
                        Can not import paddle core while this file exists: lib/python3.8/site-packages/paddle/fluid/libpaddle.so

**Comment by guidongnan** [comment]
Is there any update facing that error?

> > 
> 
> > 
> 
> After configuring the environment according to your configuration, it still reports the same error： Can not import paddle core while this file exists: lib/python3.8/site-packages/paddle/fluid/libpaddle.so

**Comment by luoyq6** [comment]
> export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib

![image](https://user-images.githubusercontent.com/110521846/224883988-f6744591-9285-40bc-a3d6-a4a9b725f488.png)

**Comment by luoyq6** [comment]
> export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib

![image](https://user-images.githubusercontent.com/110521846/224883988-f6744591-9285-40bc-a3d6-a4a9b725f488.png)

**Comment by luoyq6** [comment]
> 确保您的 CUDA 和 CUDNN 安装正确，并确保版本与桨匹配

![image](https://user-images.githubusercontent.com/110521846/224884407-f130f74a-970e-4160-bb6b-f7c134708fcd.png)

**Comment by bhumika-cashify** [comment]
hello, I am still facing this issue.
Has anyone solved this yet. Would really appreciate the help.

**Comment by liyuyuan6969** [comment]
first,you can check if your `/usr/local/cuda-11.7/lib64` have `libcudart.so.10.2`,if not,
you lack `libcudart.so.10.2`,maybe this .so included in cuda10.2.you can download this file and move it to `/usr/local/cuda-11.7/lib64`,those path are example,please according to yourself.
```
# 在~/.bashrc中添加路径
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
# 还是未能解决，参考：https://blog.csdn.net/zoey_peak/article/details/129540845
# 将下载好的libcudart.so.10.2放在lib64下
cd /usr/local/cuda-11.7/lib64
mv /root/lyy/PaddleSpeech/demos/style_fs2/libcudart.so.10.2 ./
chmod +x libcudart.so.10.2
```

**Comment by kishore-work-hard** [comment]
> first,you can check if your `/usr/local/cuda-11.7/lib64` have `libcudart.so.10.2`,if not, you lack `libcudart.so.10.2`,maybe this .so included in cuda10.2.you can download this file and move it to `/usr/local/cuda-11.7/lib64`,those path are example,please according to yourself. you can download with google disk https://drive.google.com/file/d/1YUev1Z7zUPj1r_UCFLkRJvuhSMjNKuyu/view?usp=sharing
> 
> ```
> # 在~/.bashrc中添加路径
> export PATH=$PATH:/usr/local/cuda/bin
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
> # 还是未能解决，参考：https://blog.csdn.net/zoey_peak/article/details/129540845
> # 将下载好的libcudart.so.10.2放在lib64下
> cd /usr/local/cuda-11.7/lib64
> mv /root/lyy/PaddleSpeech/demos/style_fs2/libcudart.so.10.2 ./
> # 一定要添加权限
> chmod +x libcudart.so.10.2
> ```

current CUDA version in google colab is 11.8 and I tried downloading the file.. uploading it and still same error.

**Comment by MarielMa** [comment]
修改paddlepaddle-gpu版本，python3.8/3.9 cuda 11.7 对应版本为 pip install paddlepaddle-gpu==2.4.2.post117 然后就不报错了

**Comment by yaobaishen** [comment]
> 修改paddlepaddle-gpu版本，python3.8/3.9 cuda 11.7 对应版本为 pip install paddlepaddle-gpu==2.4.2.post117 然后就不报错了

this one really helps!

**Comment by 1005cyxin** [comment]
也可以在安装paddlepaddle-gpu2.4.2之后，使用conda环境隔离，安装cudatoolkit10.2
