### ISSUE TITLE
手册有一处拼写错误，示例代码英文逗号写成了中文逗号

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleOCR#9175]
问题页面：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md

在这句话`如果输入是PDF文件，那么可以参考下面代码进行可视化`下面的代码，
`ocr = PaddleOCR(use_angle_cls=True, lang="ch"， page_num=2)  # need to run only once to download and load model into memory`

应该为：

`ocr = PaddleOCR(use_angle_cls=True, lang="ch",  page_num=2)  # need to run only once to download and load model into memory`

也就`lang="ch"`后面的逗号，应该是英文逗号，写成了中文逗号。

**Comment by andyjpaddle** [comment]
感谢反馈，我们会尽快修复

**Comment by skywalk163** [comment]
已修复！
