### ISSUE TITLE
styletext使用中的问题

### ISSUE THREAD

**Issue by angel-yi** [PaddlePaddle/PaddleOCR#9178]
使用styletext合成中文含有生僻字的数据，发现：1、生僻字不支持，换了支持的字体，生成后文字辨识不出；2、存在漏字情况

示例：
![0](https://user-images.githubusercontent.com/51775756/220503902-2d5d4992-5ba7-4c4c-a207-9ec4b9ea8cdb.png)
![1](https://user-images.githubusercontent.com/51775756/220503989-ebcc8ef5-de94-4a57-a1c7-a2e7048032ed.png)
![2](https://user-images.githubusercontent.com/51775756/220503999-03f5c0ef-ca5e-4c0d-8acb-fa7e0662466f.png)
![3](https://user-images.githubusercontent.com/51775756/220504007-0ad57c0b-b919-4945-b711-66ddb0fef29c.png)
![image](https://user-images.githubusercontent.com/51775756/220503933-d520a0fd-253c-40f8-942c-ff21b79474b0.png)

**Comment by tink2123** [comment]
styletext 效果还在优化中～ 欢迎持续关注
