### ISSUE TITLE
编译android端侧部署的执行文件出错

### ISSUE THREAD

**Issue by jockeyyan** [PaddlePaddle/PaddleOCR#918]
请帮忙看看怎么回事？

$ pwd
/opt/inference_lite_lib.android.armv8/demo/cxx/ocr

$ make -j
/opt/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ --sysroot=/opt/android-ndk-r17c/sysroot -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK -DLITE_WITH_LINUX -DPADDLE_DISABLE_PROFILER -DPADDLE_NO_PYTHON -DPADDLE_WITH_TESTING -I/opt/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include -I/opt/android-ndk-r17c/sources/cxx-stl/llvm-libc++abi/include -I/opt/android-ndk-r17c/sources/android/support/include -I/opt/android-ndk-r17c/sysroot/usr/include  -I/opt/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include -I../../..//cxx/include -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions -frtti -std=c++11 -fopenmp -O3 -DNDEBUG -fPIE -o ocr_db_crnn.o -c ocr_db_crnn.cc
Fetch clipper 
fetch opencv libs
...
cls_process.h:25:28: fatal error: opencv2/core.hpp: No such file or directory
 #include "opencv2/core.hpp"
                            ^
compilation terminated.

$ tree -N
.
├── clipper.cpp
├── clipper.hpp
├── cls_process.cc
├── cls_process.h
├── config.txt
├── crnn_process.cc
├── crnn_process.h
├── db_post_process.cc
├── db_post_process.h
├── debug
│   ├── 11.jpg
│   ├── ch_ppocr_mobile_v1.1_cls_opt.nb
│   ├── ch_ppocr_mobile_v1.1_det_opt.nb
│   ├── ch_ppocr_mobile_v1.1_rec_opt.nb
│   ├── config.txt
│   ├── libpaddle_light_api_shared.so
│   └── ppocr_keys_v1.txt
├── Makefile
├── ocr_db_crnn.cc
├── prepare.sh
├── readme_en.md
└── readme.md

**Comment by WenmuZhou** [comment]
看看这个路径下/opt/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -I../../../third_party/opencv4.1.0/arm64-v8a/include有没有自动下载opencv的库

**Comment by jockeyyan** [comment]
在这个路径下/opt/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android 没有；
在../../../third_party/opencv4.1.0/arm64-v8a/include下有opencv的头文件：
$ tree -N
.
└── opencv2
    ├── calib3d
    │   ├── calib3d_c.h
    │   └── calib3d.hpp
    ├── calib3d.hpp
......
31 directories, 209 files

另外，在我的/usr/local/include/opencv2下也有include头文件
$ tree -N
.
├── calib3d
│   ├── calib3d_c.h
│   └── calib3d.hpp
├── calib3d.hpp
......
31 directories, 247 files

我不确定编译会找哪个？

**Comment by LDOUBLEV** [comment]
默认找/third_party/ 下的opencv，如果没有这个库，会自动下载；
报错后，重新make -j 试试呢

**Comment by BeeFly616** [comment]
我是删除了third_party,然后重新make -j就成功了

**Comment by zouxiaoshi** [comment]
@WenmuZhou  您好，ndk 中找不到 g++文件, 导致无法编译，后来换了个版本也没有。（版本： 22，21） 

Android Studio 信息：
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64   


sdk/ndk/22.0.7026061/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin 中目录如下：
.
├── aarch64-linux-android-addr2line
├── aarch64-linux-android-ar
├── aarch64-linux-android-as
├── aarch64-linux-android-c++filt
├── aarch64-linux-android-dwp
├── aarch64-linux-android-elfedit
├── aarch64-linux-android-gprof
├── aarch64-linux-android-ld
├── aarch64-linux-android-ld.bfd
├── aarch64-linux-android-ld.gold
├── aarch64-linux-android-nm
├── aarch64-linux-android-objcopy
├── aarch64-linux-android-objdump
├── aarch64-linux-android-ranlib
├── aarch64-linux-android-readelf
├── aarch64-linux-android-size
├── aarch64-linux-android-strings
└── aarch64-linux-android-strip
