### ISSUE TITLE
关于paddleOCR padlehub服务化部署时使用多语言模型会识别成中文的问题

### ISSUE THREAD

**Issue by LangJiHuangSha** [PaddlePaddle/PaddleOCR#9180]
# 关于paddleOCR padlehub服务化部署时使用多语言模型会识别成中文的问题
## 图片预览
![image](https://user-images.githubusercontent.com/100844589/220521545-a2910fa7-2154-41aa-8c7a-ef587786033b.png)
### params.py
![image](https://user-images.githubusercontent.com/100844589/220521891-e4d42533-36ad-432b-b7cf-ab9c8db3532d.png)
### deploy/hubserving/ocr_system/model.json 
![image](https://user-images.githubusercontent.com/100844589/220522086-1ae56ac7-8fe1-41d1-803e-c4323db6b807.png)
### 模型文件位置
![image](https://user-images.githubusercontent.com/100844589/220522144-cba491d4-674d-44c9-be55-3ee95a3e5149.png)

## 识别结果（显示为中文，应该是韩文）
![image](https://user-images.githubusercontent.com/100844589/220521675-90420258-3cf1-4081-b9fc-54c7c799de2a.png)

**Comment by tink2123** [comment]
1. 检查模型是否成功替换成了韩文模型
2. 需要修改字典文件为韩文， 看配置仍然是中文字典
<img width="518" alt="image" src="https://user-images.githubusercontent.com/31891223/220604751-d5a35edf-134c-4437-aca2-6d531a830ab2.png">

**Comment by LangJiHuangSha** [comment]
> 1. 检查模型是否成功替换成了韩文模型
> 2. 需要修改字典文件为韩文， 看配置仍然是中文字典
> 
> <img alt="image" width="518" src="https://user-images.githubusercontent.com/31891223/220604751-d5a35edf-134c-4437-aca2-6d531a830ab2.png">

嗯嗯，确实是字典没改过来，现在已经解决了，非常感谢（本人纯小白）
