### ISSUE TITLE
如何更换quick start 的whl中  调用的默认的轻量级模型，貌似默认是mobile net，我想试一试resnet，但是没有找到接口。

### ISSUE THREAD

**Issue by shenghuangxu** [PaddlePaddle/PaddleOCR#9181]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
直接修改 rec_model_dir / det_model_dir 参数为希望修改的模型路径， 参考:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/whl.md#31-%E4%BB%A3%E7%A0%81%E4%BD%BF%E7%94%A8
