### ISSUE TITLE
nvidia 1080Ti显卡，cuda10.2，使用paddleOCR 推理报错：

### ISSUE THREAD

**Issue by wenxuezhang** [PaddlePaddle/PaddleOCR#9183]
- 系统环境/System Environment：
- centos 7.7 ；nvidia 1080Ti显卡，cuda10.2， cudnn7.6.5.32， 
- 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 版本：paddlepaddle-gpu 2.4.2
paddleOCR 版本：paddleocr 2.6.1.3

模型：
# 方向分类器
cls_model:ch_ppocr_mobile_v2.0_cls_infer
# ocr检测模型:
det_model: ch_PP-OCRv3_det_infer
# ocr识别模型
rec_model: ch_PP-OCRv3_rec_infer
rec_char_dict_path: /ppocr_keys_v1.txt
font_path:sim_fang.ttf
char_type: ch
- 运行指令/Command Code：
ocr = PaddleOCR(cls_model_dir=cls_model,det_model_dir=det_model, 
        rec_model_dir=rec_model,
        rec_char_dict_path = rec_char_path, rec_char_type=rec_char_type,version='PP-OCRv3',
        vis_font_path=font_path, use_angle_cls=False,use_gpu=True)

执行：ocr.ocr(file_name, cls=True)，报错如下：
- 完整报错/Complete Error Message：
- terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (External) CUDA error(3), initialization error. 
  [Hint: Please search for the error code(3) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:172)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle_infer::Tensor::CopyFromCpu<float>(float const*)
1   std::__basic_future<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_get_result() const
2   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_complete_async()
3   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > paddle::platform::CreateDeviceContext<phi::GPUContext>(phi::Place const&, bool)
6   phi::GPUContext::Impl::~Impl()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1677048461 (unix time) try "date -d @1677048461" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x62e1) received by PID 25313 (TID 0x7f87bca50700) from PID 25313 ***]

**Comment by tink2123** [comment]
请检查 paddle 安装是否正确：
```
import paddle
paddle.utils.run_check()
```

**Comment by wenxuezhang** [comment]
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0222 22:25:37.441035 22594 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0222 22:25:37.451232 22594 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
/opt/anaconda3/envs/py37ocr/lib/python3.7/site-packages/paddle/fluid/executor.py:1585: UserWarning: Standalone executor is not used for data parallel
  UserWarning)
W0222 22:25:40.725191 22594 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W0222 22:25:40.725250 22594 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W0222 22:25:43.492534 22594 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
我推理的时候用的是一个卡

**Comment by wenxuezhang** [comment]
为啥关闭这个issue?  问题并没有解决。硬件检测通过说明paddleocr 安装的没问题，然后我加载模型也没问题，但是我推理的时候出错啊，我上面描述的错误是推理的错误

**Comment by wenxuezhang** [comment]
我单独以交互式方式执行是没问题的。但是通过tornado放在进程里就不好使，不知道咋回事，有类似的issue 能推荐下吗？我觉得这个问题应该不是个特别的问题
