### ISSUE TITLE
KIE: re train error

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleOCR#9184]
SER模型训练时，尝试在class_list_xfun.txt中添加了4个label，如下
```
OTHER
QUESTION
ANSWER
HEADER
NAME_KEY
NAME_VAL
SEX_KEY
SEX_VAL
```
SER的模型已训练完毕。想训练RE模型时，沿用SER的class_list_xfun.txt标签，却出现如下报错
```
  File "/home/aistudio/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/__init__.py", line 57, in transform
    data = op(data)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/vqa/token/vqa_token_chunk.py", line 109, in __call__
    item['entities']['label'] = [
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/vqa/token/vqa_token_chunk.py", line 110, in <listcomp>
    self.entities_labels[x] for x in item['entities']['label']
KeyError: 'NAME_KEY'
```
RE配置文件 configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml 中的class_path指定路径无误，配置文件还有其他地方涉及到label的地方吗

**Comment by tink2123** [comment]
看报错是这个位置：https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/ppocr/data/imaug/vqa/token/vqa_token_chunk.py#L56

可以修改配置文件：
```
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
          entities_labels: { 'HEADER': 0, 'QUESTION': 1, 'ANSWER': 2, 'NAME_KEY':3, 'SEX_KEY':4, 'SEX_VAL':5}
```

**Comment by hbo-lambda** [comment]
ok，谢谢

**Comment by harshsummit** [comment]
After this, it will give float point exception error

**Comment by harshsummit** [comment]
Hey @hbo-lambda  if you are able to successfully train this RE model, please let me know, I need help for the same

**Comment by hbo-lambda** [comment]
> Hey @hbo-lambda if you are able to successfully train this RE model, please let me know, I need help for the same
fail.  !!!!!

**Comment by ariefwijaya** [comment]
any update on this?

**Comment by bagaabu** [comment]
same issue, any update? or anyone run the traing can help?

**Comment by c-avan** [comment]
我也出现这个问题了，配置文件添加entities_labels:{}后出现如下错误：
  File "/usr/local/lib/python3.10/dist-packages/paddle/tensor/manipulation.py", line 1842, in stack
    return _C_ops.stack(x, axis)
ValueError: (InvalidArgument) x dim number should greater than 0, but received value is: 0
  [Hint: Expected x_dim > 0, but received x_dim:0 <= 0:0.] (at ../paddle/phi/backends/gpu/gpu_launch_config.h:175)

**Comment by woguwo** [comment]
> 我也出现这个问题了，配置文件添加entities_labels:{}后出现如下错误： File "/usr/local/lib/python3.10/dist-packages/paddle/tensor/manipulation.py", line 1842, in stack return _C_ops.stack(x, axis) ValueError: (InvalidArgument) x dim number should greater than 0, but received value is: 0 [Hint: Expected x_dim > 0, but received x_dim:0 <= 0:0.] (at ../paddle/phi/backends/gpu/gpu_launch_config.h:175)

您好，我在训练kie的时候也出现一样问题了，您解决这个问题了吗？

**Comment by XiYuan68** [comment]
@c-avan @woguwo 看这里
https://github.com/PaddlePaddle/PaddleOCR/issues/9184#issuecomment-1851209700

**Comment by UserWangZz** [comment]
It has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by freezehe** [comment]
@tink2123 这个bug修复了吗？我现在也遇到了这样的问题？是否有解决方案

**Comment by freezehe** [comment]
> @tink2123 这个bug修复了吗？我现在也遇到了这样的问题？是否有解决方案

@XiYuan68 你好，这个bug修复了吗？

**Comment by chairc** [comment]
我测了一下出一个一般的**解决方案**
1、`KeyError`参考  [https://github.com/PaddlePaddle/PaddleOCR/issues/9184#issuecomment-1439859586](https://github.com/PaddlePaddle/PaddleOCR/issues/9184#issuecomment-1439859586) 修改entities_labels为自己的类别
2、可能会报`[Hint: Expected x_dim > 0, but received x_dim:0 <= 0:0.]`错误，参考[https://github.com/PaddlePaddle/PaddleOCR/issues/11261#issuecomment-1955978762](https://github.com/PaddlePaddle/PaddleOCR/issues/11261#issuecomment-1955978762)，这是因为数据集的label的顺序问题导致的，可以修改部分代码跳过报错问题解决
3、潜在版本问题会报`AttributeError: 'bool' object has no attribute 'sum'`错误，这是paddlenlp新版本修改了部分代码导致的，参考[https://github.com/PaddlePaddle/PaddleOCR/discussions/13368#discussioncomment-10030978](https://github.com/PaddlePaddle/PaddleOCR/discussions/13368#discussioncomment-10030978)降低版本paddlepaddle==2.4.1 paddlenlp==2.5.2
