### ISSUE TITLE
ch_PP-OCRv3蒸馏识别模型训练收敛很慢效果很差，但是使用ch_PP-OCRv2收敛特别快，acc能达到96%

### ISSUE THREAD

**Issue by fengchuibeixiang** [PaddlePaddle/PaddleOCR#9185]
显卡GTX1660
paddlepaddle = 2.3.2
python = 3.8.13
数据集大概有13000张左右的图片，都是合成的，评估用的是真实场景下的图片。
问题1：之前用的是中英文通用预训练模型ch_PP-OCRv2来训练识别模型，10个epoch以内就能达到最好效果，差不多96%。后面在识别模型finetune教程中发现官方推荐使用ch_PP-OCRv3搭配蒸馏的配置文件来微调模型，故使用v3来训练了30个epoch，并由官方教程根据我的batch_size修改了学习率，但最后评估正确率只有11%，可能是什么原因呢？
问题2：
![1677054993980](https://user-images.githubusercontent.com/122582019/220566326-4dc9a1d6-e2d7-443f-a84e-7e4fe42ca072.png)
刚出现的错误，增广了样本后，使用ch_PP-OCRv2训练，第四轮时出现以上报错，如果是输入图片大小原因的话，为什么前几轮不报错呢？

**Comment by tink2123** [comment]
训练时尝试关闭复杂的数据增强，注释一下部分代码：

https://github.com/PaddlePaddle/PaddleOCR/blob/a923f35de57b5e378f8dd16e54d0a3e4f51267fd/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml#L161-L165

**Comment by fengchuibeixiang** [comment]
> 

谢谢，在注释了这段代码后训练，识别准确率能有96%左右
