### ISSUE TITLE
docker安装的paddleocr镜像，预测推理时第一张卡住，

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleOCR#9186]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 按照官网sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7 /bin/bash
- pip install "paddleocr>=2.0.1"   为2.6.1.3
- 执行命令:paddleocr --image_dir ./ppocr_img/ppocr_img/imgs/11.jpg --use_angle_cls true --use_gpu true
![image](https://user-images.githubusercontent.com/22360785/220571107-4e802f76-d1fb-4f14-bfb8-bbca130a56c9.png)
无论是python代码 还是这里的cmd命令 都卡住不动。gpu为rtx3090

**Comment by gengyanlei** [comment]
好吧。默认模型是不能使用gpu的

**Comment by kesshei** [comment]
> 好吧。默认模型是不能使用gpu的

为什么呢，我不太懂，大佬可以讲讲么
