### ISSUE TITLE
Missing commonly used characters in chinese_cht_dict.txt

### ISSUE THREAD

**Issue by kenho211** [PaddlePaddle/PaddleOCR#9187]
Hi, may I know what chinese_cht_dict.txt is based on?
Some commonly used traditional Chinese characters like 注 is missing from chinese_cht_dict.txt (this character is used in both simplified Chinese and traditional Chinese without discrepancy)

**Comment by tink2123** [comment]
Thanks for feedback. The dictionary is obtained by traversing the characters that appear after collecting a batch of corpus, so some characters may be missed.

**Comment by kenho211** [comment]
如果使用自定義字典，需要重新設定 FC 層的維度 / CTC Head 的out_channels 嗎？
https://github.com/PaddlePaddle/PaddleOCR/issues/8514

**Comment by kenho211** [comment]
已經找到答案了，謝謝。

https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/ppocr/modeling/heads/rec_multi_head.py#L53-L54

https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/tools/train.py#L88-L92
