### ISSUE TITLE
PPStructure 的一些小细节

### ISSUE THREAD

**Issue by similang** [PaddlePaddle/PaddleOCR#9188]
1. 有没有办法把所有的图片都当成一张表，然后再做行列检测？

2. 不是很明白这些模型用途。。。可以确定我已下的了解对吗？ 然后可以拆开使用吗？

cls_model_dir - For angle classification inference model (but how does it work and what does that mean?)
det_model_dir - For text detection model
e2e_model_dir -??? - Any example?
layout_model_dir - Layout model like LayoutParser
re_model_dir - KIE related model?
rec_model_dir - Text OCR model?
ser_model_dir - Semantic Entity Recognition (Question & Answer)
sr_model_dir - ???
table_model_dir - For table detection? How's different from layout model?

**Comment by tink2123** [comment]
1. 如果你的图片是表格，当然可以这样做，直接调用表格识别模型即可，参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/table/README.md
2. 以下模型均可拆开使用， 模型用途 和 example 可以在各个模型的说明文档中找到：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/doc/doc_en

**Comment by similang** [comment]
想更了解slanet - 

> 1. 如果你的图片是表格，当然可以这样做，直接调用表格识别模型即可，参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/table/README.md


想更了解slanet - 看起来是从 xywh 构建？ 我有了解错吗？
如果我有 xywh 可以直接用这模型来重塑表格吗？还是有其它模型可以利用？ 谢谢。

**Comment by similang** [comment]
@tink2123 对以上的了解有错吗？ 谢谢

**Comment by similang** [comment]
@tink2123 
@sdcb 
@ZeyuChen 
@bingooo 

以上的了解对吗？
