### ISSUE TITLE
文字识别用官方库里的推理模型转的onnx文件和用预训练模型转推理再转的onnx文件速度差很多

### ISSUE THREAD

**Issue by YesterdayisTuesday** [PaddlePaddle/PaddleOCR#9190]
两个推理模型用paddle推理时间一致，但是转出来的onnx速度相差十几倍
是转换推理模型的方式有误吗？还是转onnx的方式有误？

转推理模型按paddleocr的教程转的，指令如下
python3 tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml -o Global.pretrained_model=./pre Global.save_inference_dir=./infer

转onnx用paddle2onnx上的教程转的，指令如下
paddle2onnx --model_dir saved_inference_model \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --save_file model.onnx \
            --enable_dev_version True
拜托大佬解答

**Comment by zhongJY1998** [comment]
是没用上gpu吗,
