### ISSUE TITLE
docker下载完镜像后，paddleocr测试图像 使用gpu卡住不动

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleOCR#9195]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7 /bin/bash

按照官网给的安装教程安装paddleocr镜像，然后采用如下可以执行，但是更改use_gpu=True后 第一张图像就卡住不动！需要kill -9才可以杀死进程，ctrl+c无法终止。另外采用python脚本代码也是如此，不知道为什么？
paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu false

请问，需要在哪里设置什么？还是版本问题呢？
paddle-gpu: 2.1.3
paddleocr: 2.6.1.3

**Comment by WenmuZhou** [comment]
建议使用最新的paddle镜像

**Comment by gengyanlei** [comment]
好吧，谢谢啦。
去docker上找最新的paddle镜像，然后安装最新的ppocr，或者下载此仓库训练测试。
