### ISSUE TITLE
KIE: SER对未标注的区域未识别成other

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleOCR#9197]
训练好了文字检测模型，召回率90%多。检测样本中的文字时，可能会识别出多余的区域，但我觉得不影响使用。
SER模型也是在自定义的数据集上训练的，数据集仅标注了需要关注的几个区域。它跟文字检测模型配合使用时，对文字检测出的多余区域会识别为QUESTION或者ANSWER。训练了好几次，SER的准确率和召回率已经挺高了，预测时却没有将多余的部分识别成other，怎么解决呢

**Comment by WenmuZhou** [comment]
label里面，其他的数据的标记为other的吗

**Comment by sunzhaoyang** [comment]
我也是，其他的数据标记为 other 了。传送门：https://github.com/PaddlePaddle/PaddleOCR/issues/9231
