### ISSUE TITLE
paddle逐字符检测

### ISSUE THREAD

**Issue by H-eaven-1** [PaddlePaddle/PaddleOCR#9198]
![pa](https://user-images.githubusercontent.com/124422627/220830609-8e70f222-efcf-4461-9646-90dba5d1d392.png)
如何达到逐字符检测效果，即检测时每个字符都有一个矩形框和坐标位置；而不是只返回整行文字的位置坐标。

**Comment by WenmuZhou** [comment]
暂时不支持

**Comment by tianchiguaixia** [comment]
> ![pa](https://user-images.githubusercontent.com/124422627/220830609-8e70f222-efcf-4461-9646-90dba5d1d392.png) 如何达到逐字符检测效果，即检测时每个字符都有一个矩形框和坐标位置；而不是只返回整行文字的位置坐标。

虽然完全字位置给不了，你可以自己推大概位置，根据文本框

**Comment by BaoBaoJianqiang** [comment]
数字或者英文的话 自己切割；中文的话，有点难搞

**Comment by fanqie03** [comment]
字符检测：[https://github.com/fanqie03/char-detection/tree/main](https://github.com/fanqie03/char-detection/tree/main)
