### ISSUE TITLE
How to add a language?

### ISSUE THREAD

**Issue by Mejans** [PaddlePaddle/PaddleOCR#920]
Hello,
how can I help you to add my language?
Here I helped to provide files for Occitan, oc iso-code: https://github.com/JaidedAI/EasyOCR/tree/master/easyocr
Would it be enough?

Best regards

**Comment by tink2123** [comment]
**You are very welcome to provide us with dictionaries and fonts in other languages**
If you like, you can submit the dictionary file to [dict](https://github.com/PaddlePaddle/PaddleOCR/tree/develop/ppocr/utils/dict) or corpus file to [corpus](https://github.com/PaddlePaddle/PaddleOCR/tree/develop/ppocr/utils/corpus) and we will thank you in the Repo.

**Comment by Mejans** [comment]
Hello,
done here: https://github.com/PaddlePaddle/PaddleOCR/pull/928
I hope it's okay

**Comment by tink2123** [comment]
Thanks for your contribution
