### ISSUE TITLE
模型训练加载数据json读取异常

### ISSUE THREAD

**Issue by yuhai5237** [PaddlePaddle/PaddleOCR#9200]
数据格式是按照规定的格式来的，最后下载中科院手写数据集来测试还是一样的问题

- 系统环境/System Environment：windows10 cpu训练
- 版本号/Version：2.4.1 Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python .\tools\train.py -c .\configs\det\det_mv3_db.yml
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/24368402/220832749-c811c9f8-d211-4152-b0ae-c25ad779f19b.png)

**Comment by WenmuZhou** [comment]
label贴一下看看

**Comment by yuhai5237** [comment]
> label贴一下看看

哪个label

**Comment by yuhai5237** [comment]
> label贴一下看

解决了，不好意思，指定的配置文件指定错了
