### ISSUE TITLE
OCR识别问题

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#9205]
我想识别一下，红底上面的数字哎，但是paddleocrv3检测效果不是很好
1.请问下修改什么参数可以让画圈的地方可以检测出来？
2.这种情况，如果标注训练，效果会好？
![image](https://user-images.githubusercontent.com/29837553/221069466-8f71ef67-50e6-47e5-a85c-efdfbed3f931.png)
![image](https://user-images.githubusercontent.com/29837553/221069490-4f9d24fb-6c7d-4e0c-a7cc-48f2abfb1582.png)

**Comment by an1018** [comment]
可以先调低框过滤的阈值试试：det_db_box_thresh

**Comment by tianchiguaixia** [comment]
已经设置为0.01了还是不行哎

**Comment by an1018** [comment]
如果中、英文模型尝试都没有检测到，那就需要针对自己场景微调训练了

**Comment by tianchiguaixia** [comment]
好的
