### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lokeycookie** [PaddlePaddle/PaddleOCR#9206]
Please provide the following information to quickly locate the problem

- System Environment：Ubuntu 20.04
- 版本号/Version：paddleocr 2.6.1.2 , paddlepaddle-gpu 2.4.1.post112

- Complete Error Message：
Traceback (most recent call last):
  File "/home/evas/Documents/GitHub (copy)/project/src/test.py", line 20, in <module>
    recognized = model.ocr(img_ocr, det = False, rec = True)
  File "/home/evas/anaconda3/envs/project/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 577, in ocr
    rec_res, elapse = self.text_recognizer(img)
  File "/home/evas/anaconda3/envs/project/lib/python3.9/site-packages/paddleocr/tools/infer/predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/evas/anaconda3/envs/project/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 122, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/evas/anaconda3/envs/project/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 83, in decode
    char_list = [
  File "/home/evas/anaconda3/envs/project/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 85, in <listcomp>
    self.character[text_id]
IndexError: list index out of range

Hi there,

I trained PaddleOCR with two datasets (which is combined into one). One dataset is images of handwritten word, while the other dataset is images of handwritten lines. In my training script, here is s small portion of configs that I changed:
character_dict_path: ppocr/utils/en_dict.txt
  char_type : en
  max_text_length: 250
  infer_mode: True
  use_space_char: True
  
I have trained PaddleOCR succesfully and I have exported it out.
However, when I tried to call the trained PaddleOCR model in code, I got the above error: IndexError: list index out of range

How do I resolve this issue?

**Comment by an1018** [comment]
run with exported model, you also need  to specify the dictionary path used by --rec_char_dict_path

**Comment by Jaccica** [comment]
我也出现了这个问题，请问怎么解决？用推理模型来预测，结果出现了这个错误。检测推理模型可以预测，识别推理模型却出错。

**Comment by Nemophilist8** [comment]
需要设置rec_char_dict_path

**Comment by athewsey** [comment]
I came across the same error when working with a pre-trained model but changing the download dirs - like this:

```python
ocr = PaddleOCR(
    lang="en",
    use_angle_cls=True,
    det_model_dir="/opt/paddleocr/models/det",
    rec_model_dir="/opt/paddleocr/models/rec",
    cls_model_dir="/opt/paddleocr/models/cls",
)
```

Not sure what I should set `rec_char_dict_path` to in this case?

**Comment by asif-ca** [comment]
I am facing the same issue with the custom trained model.

**Comment by jiangbossB** [comment]
> I am facing the same issue with the custom-trained model. My dictionary path is also correct but still facing same error
> 
> ```
> custom_ocr = PaddleOCR(use_angle_cls=True,
>                 rec_model_dir='PaddleOCR/inference/en_PP-OCRv3_rec',
>                 det_model_dir='PaddleOCR/output/det_db_inference',
>                 rec_char_dict_path='ppocr/utils/en_dict.txt',
>                 use_gpu=True,
>                 show_log=False)
> ```
> 
> 
> 我在定制训练模型中也遇到了同样的问题。我的字典路径也是正确的，但仍然面临同样的错误
> 
> ```
> custom_ocr = PaddleOCR（use_angle_cls=True，
>                 rec_model_dir='PaddleOCR/inference/en_PP-OCRv3_rec'，
>                 det_model_dir='PaddleOCR/output/det_db_inference'，
>                 rec_char_dict_path ='ppocr/utils/en_dict.txt '，
>                 use_gpu=True，
>                 show_log=False）
> ```
same,Is it solved？

**Comment by thinhemb** [comment]
you can let path is path to chinese_cht_dict.txt. Example on Windows: rec_char_dict_path=r'..\ppocr\utils\dict\chinese_cht_dict.txt'. I leave it as en_dict.txt. Then I get access outside the list because en_dict.txt has few characters

**Comment by asif-ca** [comment]
@CyanMystery 

I had an issue with my model because I used the wrong dictionary. I added more characters to the dictionary and trained the model, but when I tried to use the model for inference, I mistakenly gave it the old dictionary which had fewer keys than the updated one. This caused problems, but once I used the same dictionary that I used to fine-tune the model, it worked correctly.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by Cairang** [comment]
The problem can be solved by keeping the dictionary of rec_char_dect_path consistent between the training and inference models.
