### ISSUE TITLE
Pgnet训练电子印章不收敛，recall=0，percision=0

### ISSUE THREAD

**Issue by wangxinzhe0617** [PaddlePaddle/PaddleOCR#9207]
训练日志如下，为什么会这样。。。。困扰好几天了，调整了学习率也不行。batchsize设置为4，训练自己标注的小批量数据也是这个效果。只有将tcloss前边参数改为0，recall才正常。但是训练公开的totaltext就一切正常，是不是pgnet不适合中文。求大佬指教。ppocr版本为3.5
[2023/02/24 10:24:17] ppocr INFO: epoch: [6/600], global_step: 12000, lr: 0.001000, loss: 155.738098, score_loss: 0.109713, border_loss: 0.063462, direction_loss: 0.069807, ctc_loss: 31.102074, avg_reader_cost
: 0.00017 s, avg_batch_cost: 1.57068 s, avg_samples: 4.0, ips: 2.54667 samples/s, eta: 21 days, 23:02:59
eval model:: 100%|██████████| 2000/2000 [21:15<00:00,  1.57it/s][2023/02/24 10:45:32] ppocr INFO: cur metric, total_num_gt: 5047, total_num_det: 38, global_accumulative_recall: 0, hit_str_count: 0, r
ecall: 0.0, precision: 0.0, f_score: 0, seqerr: 1, recall_e2e: 0.0, precision_e2e: 0.0, f_score_e2e: 0, fps: 4.060423078555949[2023/02/24 10:45:37] ppocr INFO: save best model is to ./output/seal_public/best_accuracy
[2023/02/24 10:45:37] ppocr INFO: best metric, f_score_e2e: 0, total_num_gt: 5047, total_num_det: 38, global_accumulative_recall: 0, hit_str_count: 0, recall: 0.0, precision: 0.0, f_score: 0, seqerr: 1, recall
_e2e: 0.0, precision_e2e: 0.0, fps: 4.060423078555949, best_epoch: 6

**Comment by wangxinzhe0617** [comment]
> 可以参考一下这个范例，也是训练中文印章：https://aistudio.baidu.com/aistudio/projectdetail/4983788?contributionType=1

谢谢回复，我就是参考的这个，数据集合用的电子印章数据集合

**Comment by an1018** [comment]
那按aistudio中相同的参数配置，recall也是0吗，还有字典有更新吗

**Comment by wangxinzhe0617** [comment]
> 那按aistudio中相同的参数配置，recall也是0吗，还有字典有更新吗

key修改过了为6623个中文数据集合，aistudio运行不了。找不到文件。如图
![6af7d666ab1aa25dcb20a5acb2fdd543](https://user-images.githubusercontent.com/38687226/221164716-c981428b-5917-46f5-ae24-48f0fd399c1d.png)
![ee1977d1a2ad610a11ea1a0822d55085](https://user-images.githubusercontent.com/38687226/221164760-422dc803-090e-47ac-954d-19bce4420d9e.png)

**Comment by an1018** [comment]
整个文档细看一下吧，从开始执行，前面需要先下载项目
![image](https://user-images.githubusercontent.com/19808900/221451568-24672006-e1d7-4722-9e22-26dbd12e3f72.png)

**Comment by wangxinzhe0617** [comment]
> 整个文档细看一下吧，从开始执行，前面需要先下载项目 ![image](https://user-images.githubusercontent.com/19808900/221451568-24672006-e1d7-4722-9e22-26dbd12e3f72.png)

非常感谢回复，我运行了notebook这个环境准备脚本的。我打开work下detection还有ocr项目里边确实是没有这两个文件，是不是版本修改了啊。

**Comment by an1018** [comment]
需要自己下载git clone

**Comment by wangxinzhe0617** [comment]
> 需要自己下载git clone

不知道是不是我没理解。我是运行了git clone的如图
![73bb87080387ec2ec31b0f9b47b95bfe](https://user-images.githubusercontent.com/38687226/221455742-4ebffe23-b96f-44dc-a36f-a534f6c2ab85.png)

**Comment by wangxinzhe0617** [comment]
> 需要自己下载git clone
可能是我表达的不清楚，我是运行了git clone的如图
![73bb87080387ec2ec31b0f9b47b95bfe](https://user-images.githubusercontent.com/38687226/221455979-d0683cf6-4c8b-406b-97a9-9a4d9eb58139.png)
找不到的文件为configs/pgnet_r50_vd_seal/config.yml，config/ppyolo/ppyolo_seal_detection.yml。detection还有ppocr整个工程是有的。

**Comment by an1018** [comment]
明白了，我反馈给负责人看下~

**Comment by an1018** [comment]
下载模型压缩包后包含配置文件，直接使用即可

**Comment by wangxinzhe0617** [comment]
> 下载模型压缩包后包含配置文件，直接使用即可

您好，我从开源大礼包里找到了这两个配置文件，目前训练数据看起来正常了。谢谢啦。

**Comment by dodgaga** [comment]
@wangxinzhe0617  您好，想问一下是什么配置文件，你是只训pgnet吗？我目前的loss也是到100多就不降了。

**Comment by wangxinzhe0617** [comment]
> @wangxinzhe0617 您好，想问一下是什么配置文件，你是只训pgnet吗？我目前的loss也是到100多就不降了。

开源礼包里印章识别，pgnet里有一个配置文件。目前只是recall跟percision不是零了。那个loss训练几轮也是一百多，不知道能不能下去。
 
![e68cba449e9c798124498ac09a7f80ae](https://user-images.githubusercontent.com/38687226/221564327-445b58ad-b984-4097-ba98-8b17517ae090.png)

**Comment by wangxinzhe0617** [comment]
> @wangxinzhe0617 您好，想问一下是什么配置文件，你是只训pgnet吗？我目前的loss也是到100多就不降了。

我是只训练pgnet，目前小批量数据表现不佳

**Comment by dodgaga** [comment]
小批量是指多少？我这边数据集1.8w也不行。今天我尝试只使用两张图训练看看是否收敛，结果也是训练到100多loss，降不下了

**Comment by wangxinzhe0617** [comment]
> 小批量是指多少？我这边数据集1.8w也不行。今天我尝试只使用两张图训练看看是否收敛，结果也是训练到100多loss，降不下了

我用了七十多张，loss下降到loss: 4.626624的样子吧。
![e2c233e440c0291ca48c9ad826f5c6c5](https://user-images.githubusercontent.com/38687226/221568344-38412951-b19d-4b05-8684-8bd932149dd9.png)
测试效果一般般，即使你用train里的数据来测。。。。。。。。。。

**Comment by zhaoqf-cq** [comment]
> 

大佬，云盘过期了，能重新分享一下吗

**Comment by zhaoqf-cq** [comment]
> > > @wangxinzhe0617 您好，想问一下是什么配置文件，你是只训pgnet吗？我目前的loss也是到100多就不降了。
> > 
> > 
> > 开源礼包里印章识别，pgnet里有一个配置文件，我分享百度云盘链接在下边了。目前只是recall跟percision不是零了。那个loss训练几轮也是一百多，不知道能不能下去。
> > ![e68cba449e9c798124498ac09a7f80ae](https://user-images.githubusercontent.com/38687226/221564327-445b58ad-b984-4097-ba98-8b17517ae090.png)
> 
> 链接：https://pan.baidu.com/s/120Xbo7yZ3Bo1Snj-7fTeaw 提取码：mtp8 --来自百度网盘超级会员V5的分享

大佬能不能重新分享一下，过期了

**Comment by zhaoqf-cq** [comment]
> 下载模型压缩包后包含配置文件，直接使用即可

大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到

**Comment by wangxinzhe0617** [comment]
> > 下载模型压缩包后包含配置文件，直接使用即可
> 
> 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到

链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 
提取码：9h1w 
--来自百度网盘超级会员V5的分享

**Comment by wangxinzhe0617** [comment]
> > 下载模型压缩包后包含配置文件，直接使用即可
> 
> 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到

这个网络一般般，学习率到一定程度网络会直接废掉，acc=0，recall=0.

**Comment by zhaoqf-cq** [comment]
> > > 下载模型压缩包后包含配置文件，直接使用即可
> > 
> > 
> > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> 
> 这个网络一般般，学习率到一定程度网络会直接废掉，acc=0，recall=0.

我就试着玩儿... 谢谢大佬

**Comment by zhaoqf-cq** [comment]
> > > 下载模型压缩包后包含配置文件，直接使用即可
> > 
> > 
> > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> 
> 链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 提取码：9h1w --来自百度网盘超级会员V5的分享

大佬啊，我用这个模型， 按照 官网给的文章https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md
这个文档进行尝试训练， 用原始数据都跑不起来，能不能分享一下 你们怎么做的啊？

我数据处理完了， 没有label_list.txt这个文件，然后我印章检测这里 python3  tools/train.py -o use_gpu=false  -c configs/ppyolo/ppyolo_mbv3_large.yml  --eval 我执行这个命令就失败了，我想着这个还只是检测，索性我就直接跳到了 5. 2的两阶段印章文字识别实践，在执行 python tools/train.py -c configs/det/det_r50_db++_icdar15.yml -o Global.epoch_num=100 这个时候，提示i错误 ：
File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/label_ops.py", line 55, in __call__
    box = label[bno]['points']
KeyError: 'points'
这里我用的就是 数据处理 seal_ppocr_gt 里面的 seal_ppocr_img.txt，看着这个文档完全一脸懵...进行不下去

**Comment by wangxinzhe0617** [comment]
> > > > 下载模型压缩包后包含配置文件，直接使用即可
> > > 
> > > 
> > > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> > 
> > 
> > 链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 提取码：9h1w --来自百度网盘超级会员V5的分享
> 
> 大佬啊，我用这个模型， 按照 官网给的文章https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 这个文档进行尝试训练， 用原始数据都跑不起来，能不能分享一下 你们怎么做的啊？
> 
> 我数据处理完了， 没有label_list.txt这个文件，我就手动创建了这个文件，在里面就写了一个 redseal， 再执行 python3 tools/train.py -o use_gpu=false -c configs/ppyolo/ppyolo_mbv3_large.yml --eval 看起来是成功了，我想着这个还只是检测，索性我就直接跳到了 5. 2的两阶段印章文字识别实践，在执行 python tools/train.py -c configs/det/det_r50_db++_icdar15.yml -o Global.epoch_num=100 这个时候，提示i错误 ： File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/label_ops.py", line 55, in **call** box = label[bno]['points'] KeyError: 'points' 这里我用的就是 数据处理 seal_ppocr_gt 里面的 seal_ppocr_img.txt，看着这个文档完全一脸懵...进行不下去
他那个数据估计是没提供，你去大礼包李找找，放到对应位置看看。

**Comment by zhaoqf-cq** [comment]
> > > > > 下载模型压缩包后包含配置文件，直接使用即可
> > > > 
> > > > 
> > > > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> > > 
> > > 
> > > 链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 提取码：9h1w --来自百度网盘超级会员V5的分享
> > 
> > 
> > 大佬啊，我用这个模型， 按照 官网给的文章https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 这个文档进行尝试训练， 用原始数据都跑不起来，能不能分享一下 你们怎么做的啊？
> > 我数据处理完了， 没有label_list.txt这个文件，我就手动创建了这个文件，在里面就写了一个 redseal， 再执行 python3 tools/train.py -o use_gpu=false -c configs/ppyolo/ppyolo_mbv3_large.yml --eval 看起来是成功了，我想着这个还只是检测，索性我就直接跳到了 5. 2的两阶段印章文字识别实践，在执行 python tools/train.py -c configs/det/det_r50_db++_icdar15.yml -o Global.epoch_num=100 这个时候，提示i错误 ： File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/label_ops.py", line 55, in **call** box = label[bno]['points'] KeyError: 'points' 这里我用的就是 数据处理 seal_ppocr_gt 里面的 seal_ppocr_img.txt，看着这个文档完全一脸懵...进行不下去
> > 他那个数据估计是没提供，你去大礼包李找找，放到对应位置看看。

谢谢大佬，我用了10000的那个数据集，里面8000个印章... 惊呆了，训练起来超级慢...

**Comment by wangxinzhe0617** [comment]
> > > > > > 下载模型压缩包后包含配置文件，直接使用即可
> > > > > 
> > > > > 
> > > > > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> > > > 
> > > > 
> > > > 链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 提取码：9h1w --来自百度网盘超级会员V5的分享
> > > 
> > > 
> > > 大佬啊，我用这个模型， 按照 官网给的文章https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 这个文档进行尝试训练， 用原始数据都跑不起来，能不能分享一下 你们怎么做的啊？
> > > 我数据处理完了， 没有label_list.txt这个文件，我就手动创建了这个文件，在里面就写了一个 redseal， 再执行 python3 tools/train.py -o use_gpu=false -c configs/ppyolo/ppyolo_mbv3_large.yml --eval 看起来是成功了，我想着这个还只是检测，索性我就直接跳到了 5. 2的两阶段印章文字识别实践，在执行 python tools/train.py -c configs/det/det_r50_db++_icdar15.yml -o Global.epoch_num=100 这个时候，提示i错误 ： File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/label_ops.py", line 55, in **call** box = label[bno]['points'] KeyError: 'points' 这里我用的就是 数据处理 seal_ppocr_gt 里面的 seal_ppocr_img.txt，看着这个文档完全一脸懵...进行不下去
> > > 他那个数据估计是没提供，你去大礼包李找找，放到对应位置看看。
> 
> 谢谢大佬，我用了10000的那个数据集，里面8000个印章... 惊呆了，训练起来超级慢...

训到一定程度可能还会出现acc=0。。。。。。。反正我是这样

**Comment by kkiskkk** [comment]
> > > > > > 下载模型压缩包后包含配置文件，直接使用即可
> > > > > 
> > > > > 
> > > > > 大佬这个在哪儿下啊... 我最近也在学习印章识别，同一个文章，也是找不到这个文件，QQ群里面没有，微信群加不进去，微信公众号“礼包”回复的也没有找到
> > > > 
> > > > 
> > > > 链接：https://pan.baidu.com/s/1P9vtPpPFK2tZ1-52tYFdFw 提取码：9h1w --来自百度网盘超级会员V5的分享
> > > 
> > > 
> > > 大佬啊，我用这个模型， 按照 官网给的文章https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md 这个文档进行尝试训练， 用原始数据都跑不起来，能不能分享一下 你们怎么做的啊？
> > > 我数据处理完了， 没有label_list.txt这个文件，我就手动创建了这个文件，在里面就写了一个 redseal， 再执行 python3 tools/train.py -o use_gpu=false -c configs/ppyolo/ppyolo_mbv3_large.yml --eval 看起来是成功了，我想着这个还只是检测，索性我就直接跳到了 5. 2的两阶段印章文字识别实践，在执行 python tools/train.py -c configs/det/det_r50_db++_icdar15.yml -o Global.epoch_num=100 这个时候，提示i错误 ： File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/label_ops.py", line 55, in **call** box = label[bno]['points'] KeyError: 'points' 这里我用的就是 数据处理 seal_ppocr_gt 里面的 seal_ppocr_img.txt，看着这个文档完全一脸懵...进行不下去
> > > 他那个数据估计是没提供，你去大礼包李找找，放到对应位置看看。
> 
> 谢谢大佬，我用了10000的那个数据集，里面8000个印章... 惊呆了，训练起来超级慢...

请问最后训练效果如何？
