### ISSUE TITLE
paddlePaddle和paddleOCR中英文 

### ISSUE THREAD

**Issue by sisrfeng** [PaddlePaddle/PaddleOCR#9208]

**Comment by sisrfeng** [comment]
文档有中文版和英文版, githuba的项目, 我习惯看英文版, 但发现有些内容只在中文版

**Comment by an1018** [comment]
发现哪些没有英文呢，可以具体列一下

**Comment by sisrfeng** [comment]
applications
![image](https://user-images.githubusercontent.com/53520949/221148741-6f88d9d6-8006-411e-b10c-b5d3f36dce0c.png)

**Comment by an1018** [comment]
这些是范例，目前也正在出英文版本，后续会公开

**Comment by sisrfeng** [comment]
那还是优先中文咯
