### ISSUE TITLE
这个很简单的图片，为啥OCR结果这么奇怪，需要做什么预处理吗？

### ISSUE THREAD

**Issue by yier2333** [PaddlePaddle/PaddleOCR#9209]
![a](https://user-images.githubusercontent.com/10252024/221083225-77a5e387-774b-4d6e-a4e7-f7831a1b59f9.jpg)
![飞书20230224-111400](https://user-images.githubusercontent.com/10252024/221083252-7b1d6095-431b-42aa-8145-271ac7f93368.jpeg)

**Comment by an1018** [comment]
执行的什么命令

**Comment by yier2333** [comment]
> 执行的什么命令

就是正常的ocr.get_ocr_result（）

**Comment by an1018** [comment]
使用pp-ocrv3模型试试呢https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#211-%E4%B8%AD%E8%8B%B1%E6%96%87%E6%A8%A1%E5%9E%8B

**Comment by SWHL** [comment]
通过在线demo可视化可以看到是检测不太好，在线demo: [PaddleOCR](https://www.paddlepaddle.org.cn/hub/scene/ocr)
![123](https://user-images.githubusercontent.com/28639377/222026860-e5562825-24ff-4844-bde3-598ed32eae76.png)

**Comment by yier2333** [comment]
> 使用pp-ocrv3模型试试呢https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#211-%E4%B8%AD%E8%8B%B1%E6%96%87%E6%A8%A1%E5%9E%8B

就是PP3呀，最新的模型
