### ISSUE TITLE
部署训练模型到自己的服务端

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#921]
我想在服务器端部署识别与检测模型，测试了教程的服务化部署模块，效果很好，于是我想在自己编写的服务器代码中使用模型，请问应该怎样部署以及有什么思路吗？谢谢。

**Comment by MissPenguin** [comment]
为什么要自己写服务器代码呢，是有什么特殊需求吗，可以直接在repo中的服务部署代码中修改的

**Comment by tyy2tyy** [comment]
我想知道服务器是怎样加载并使用模型的
