### ISSUE TITLE
Deploy model on pdserving

### ISSUE THREAD

**Issue by Tanmay98** [PaddlePaddle/PaddleOCR#9210]
Hi,

I have a trained model for layout analysis using layout parser which is saved in .pth format (pytorch format). Is it possible to deploy pytorch models directly on pdserving server?

Or Is it possible to convert pytorch model to paddle format and then deploy it to pdserving?

**Comment by an1018** [comment]
you can create the issue [here](https://github.com/PaddlePaddle/Serving/blob/v0.9.0/README.md)

**Comment by Tanmay98** [comment]
Hi, thanks I will make a new issue there

**Comment by Tanmay98** [comment]
You can convert pytorch models to paddle models using #1433 on pdserving issues #docs/inference_model_convertor/pytorch2paddle.md
