### ISSUE TITLE
请问解析一篇pdf正常需要多久？ 部署的服务耗时太久了，不知道是否正常

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleOCR#9212]
参考项目，我在代码里使用如下方案，解析一篇pdf，需要用到版面分析和文字检测及文字识别等功能，大致代码如下：
       table_engine = PPStructure(recovery=True, table=False, use_mp=True)
        result = table_engine(img)
        h, w, _ = img.shape
        res = sorted_layout_boxes(result, w)
        for i, region in enumerate(res):
            if region['type'].lower() in ["figure", "table"]:
                continue
            if region["type"].lower() == "title":
                if region['res']:
                    all_res.append(region['res'][0]['text'])
            else:
                for i, line in enumerate(region['res']):
                    all_res.append(line['text'] + ' ')

其实大致功能就是将pdf转成图片，然后对每个图片采用默认的版面分析功能，最后提取文字输出，参考的也是项目中的使用方法。但是目前这个代码，测试下来，一张图片整个流程测试下来需要10秒左右，请问这个是正常的吗？

**Comment by an1018** [comment]
可以先分析下每部分的耗时
