### ISSUE TITLE
使用PaddleOCR进行文字检测时，  在Ascend NPU上运行单机单卡为脚本报错

### ISSUE THREAD

**Issue by chenqion** [PaddlePaddle/PaddleOCR#9214]
使用PaddleOCR进行文字检测时，  在Ascend NPU上运行单机单卡为脚本报错，命令如下：
python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained \
     Global.use_amp=True Global.scale_loss=1024.0 Global.use_dynamic_loss_scaling=True

参考的代码链接为：
(https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/amp_cn.html)

**Comment by an1018** [comment]
具体报什么错误？
