### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by JINO-ROHIT** [PaddlePaddle/PaddleOCR#9216]
I keep running into this error while using v2 and v1 ocr models
![image](https://user-images.githubusercontent.com/63234112/221179519-e09d244c-cd1c-4e8a-aa45-36d806f3a4bd.png)

**Comment by an1018** [comment]
排查一下字典

**Comment by Jaccica** [comment]
请问如何解决啊？之前没有出现过这个问题。
