### ISSUE TITLE
PGNet训练时产生tensor类型不匹配

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleOCR#9218]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/61871674/221225888-1e3ac12d-73df-47eb-9751-1610c7fd8457.png)
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4096, 6624], X's size = 27131904, 'shape' is [-1, 64, 37], known capacity of 'shape' is -2368.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-27130176 != -in_size:-27131904.] (at /paddle/paddle/phi/infermeta/unary.cc:1417)

**Comment by an1018** [comment]
检查一下输入shape吧

**Comment by wangxinzhe0617** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> * 运行指令/Command Code：
> * 完整报错/Complete Error Message：
> 
> ![image](https://user-images.githubusercontent.com/61871674/221225888-1e3ac12d-73df-47eb-9751-1610c7fd8457.png) ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4096, 6624], X's size = 27131904, 'shape' is [-1, 64, 37], known capacity of 'shape' is -2368. [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-27130176 != -in_size:-27131904.] (at /paddle/paddle/phi/infermeta/unary.cc:1417)

没猜错的话你那个字典跟模型的类别不匹配，就是中文，英文的类型不匹配。37是英文字母加空格，6624是中文字数加空格。

**Comment by hooyia123** [comment]
> > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > 
> > * 系统环境/System Environment：
> > * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> > * 运行指令/Command Code：
> > * 完整报错/Complete Error Message：
> > 
> > ![image](https://user-images.githubusercontent.com/61871674/221225888-1e3ac12d-73df-47eb-9751-1610c7fd8457.png) ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4096, 6624], X's size = 27131904, 'shape' is [-1, 64, 37], known capacity of 'shape' is -2368. [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-27130176 != -in_size:-27131904.] (at /paddle/paddle/phi/infermeta/unary.cc:1417)
> 
> 没猜错的话你那个字典跟模型的类别不匹配，就是中文，英文的类型不匹配。37是英文字母加空格，6624是中文字数加空格。

这个回答相当正确，我遇到了同样的问题，试了很多次，发现就是字典字符数的问题。
在配置文件e2e_r50_vd_pg.yml中，pad_num的个数是character_dict_path: ppocr/utils/dict/guji_dict_han.txt字典的长度。比如我的这个字典有22780个字，那么pad_num的值应该从默认的36修改为22780：
Loss:
  name: PGLoss
  tcl_bs: 64
  max_text_length: 50 # the same as Global: max_text_length
  max_text_nums: 30 # the same as Global：max_text_nums
  **pad_num:** 22780 # the length of dict for pad 说的是guji_dict_han.txt字典的长度

**Comment by yang-chenyu104** [comment]
谢谢大佬，解决疑惑，可能字符数这方面没注意！！！感谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月22日(周五) 中午1:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] PGNet训练时产生tensor类型不匹配 (Issue #9218)




   
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
  
系统环境/System Environment：
 
版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
 
运行指令/Command Code：
 
完整报错/Complete Error Message：
  
 ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4096, 6624], X's size = 27131904, 'shape' is [-1, 64, 37], known capacity of 'shape' is -2368. [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-27130176 != -in_size:-27131904.] (at /paddle/paddle/phi/infermeta/unary.cc:1417)
  
没猜错的话你那个字典跟模型的类别不匹配，就是中文，英文的类型不匹配。37是英文字母加空格，6624是中文字数加空格。
  
这个回答相当正确，我遇到了同样的问题，试了很多次，发现就是字典字符数的问题。
 在配置文件e2e_r50_vd_pg.yml中，pad_num的个数是character_dict_path: ppocr/utils/dict/guji_dict_han.txt字典的长度。比如我的这个字典有22780个字，那么pad_num的值应该从默认的36修改为22780：
 Loss:
 name: PGLoss
 tcl_bs: 64
 max_text_length: 50 # the same as Global: max_text_length
 max_text_nums: 30 # the same as Global：max_text_nums
 pad_num: 22780 # the length of dict for pad 说的是guji_dict_han.txt字典的长度
