### ISSUE TITLE
PPStructure Slanet

### ISSUE THREAD

**Issue by similang** [PaddlePaddle/PaddleOCR#9220]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PPstructure
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我的图表整个就是表单了。
想更了解slanet - 看起来是从表格 xywh + text 构建？ 我有了解错吗？
如果我有 这表格数据xywh + text 可以直接用这模型来重塑表格吗？还是有其它模型可以利用？ 谢谢。

**Comment by WenmuZhou** [comment]
可以看下我们的介绍 https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/docs/PP-StructureV2_introduction.md
