### ISSUE TITLE
请问可以随意删除字典中的不需要的字符吗

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#9223]
请问我可以随意删除繁体字典`chinese_cht_dict`中不需要的字符吗，比如删除所有字母和符号，能不能再删除一些我知道的任务中用不到的汉字。这样会应影响整体的识别吗？

**Comment by wangxinzhe0617** [comment]
> 请问我可以随意删除繁体字典`chinese_cht_dict`中不需要的字符吗，比如删除所有字母和符号，能不能再删除一些我知道的任务中用不到的汉字。这样会应影响整体的识别吗？

你训练的话是可以删除的。使用开源模型推理不能删。

**Comment by haoxia1** [comment]
好的感谢！也就是说这样子只能从头训练，预训练模型也不能用是吗？

然后再麻烦请教您两个问题：
1. 那请问我需要对繁体字做一个微调：可以直接在简体字典后面加入我需要的繁体字(不改变前面的序列)，然后还能使用预训练模型继续微调吗？（因为繁体字识别模型效果远不如简体模型）
2. 微调的时候，请问数据集的尺寸最好是多大比较合适，36*36可以吗(我就做单字的)，还是推荐多准备一些尺寸，然后请问一个字大概需要多少张数据进行微调？

感谢！
