### ISSUE TITLE
paddleocr中英文识别数据集是开源的吗，有下载地址吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleOCR#9224]
请问ch_PP-OCRv3训练的识别模型数据集是开源的吗，可以提供下载地址吗

**Comment by MissPenguin** [comment]
PP-OCR模型使用的训练数据来自于公开数据集和合成数据。公开数据集的部分，常见的数据集基本都考虑到了，PaddleOCR也整理了一部分数据的下载链接可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/datasets.md ，也可以自己调研搜索更多数据集；合成数据使用的[textrender](https://github.com/Sanster/text_renderer)合成工具。
