### ISSUE TITLE
export_model.py save_inference_dir中文路径出现乱码

### ISSUE THREAD

**Issue by jafer11** [PaddlePaddle/PaddleOCR#9226]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
PaddleOCR：2.6

使用export_model.py导出推理模型是，save_inference_dir路径存在中文名字inference.pdiparams就会保存在乱码的路径当中

**Comment by LDOUBLEV** [comment]
可能是环境问题，在我的机器上是支持导出路径为中文的
<img width="660" alt="image" src="https://user-images.githubusercontent.com/26592129/221549226-f047239b-231c-401a-9efd-7853bf5fd69e.png">

**Comment by jafer11** [comment]
Win10系统不测一下吗？这个问题困扰我很久了
