### ISSUE TITLE
在使用ppocrlabel进行表格识别发现效果不是很好，能替换自己训练的表格识别吗

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleOCR#9233]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
-  PaddleOCR： 2.6

目前搜索了所有Issues和文档找不到替换的方法，本地目录也找不到表格识别的模型在哪替换，求大神指点

**Comment by andyjpaddle** [comment]
在PPStructure类里面指定一下`table_model_dir`,然后重新编译安装 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/PPOCRLabel.py#L104

**Comment by 1061302569** [comment]
> 在PPStructure类里面指定一下`table_model_dir`,然后重新编译安装 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/PPOCRLabel.py#L104
谢谢，大神指点
