### ISSUE TITLE
我已经是最新版本的PPOCRLabel，重新标注，还是没有label，只有key_cls

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9234]
![image](https://user-images.githubusercontent.com/110521846/221733678-453ec064-350f-452e-ad4f-7335debfb59a.png)
![image](https://user-images.githubusercontent.com/110521846/221733787-4a57a20c-e9ba-4a0b-b895-604ce29022e7.png)
![image](https://user-images.githubusercontent.com/110521846/221733902-0fc319fa-58d8-491c-b3ec-c0fd5ef3d907.png)

**Comment by sunzhaoyang** [comment]
要自己写脚本转换....

**Comment by luoyq6** [comment]
> 要自己写脚本转换....
能不能提供脚本给我呢？谢谢！
