### ISSUE TITLE
paddleocr初始化失败，没有任何报错信息，无法定位问题

### ISSUE THREAD

**Issue by TheHonestBob** [PaddlePaddle/PaddleOCR#9235]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
windows 10 cpu环境
pycharm
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle-gpu
- 运行指令/Command Code：
from paddleocr import PaddleOCR
ocr = PaddleOCR(lang="ch", use_gpu=False)
初始化失败
- 完整报错/Complete Error Message：
没有任何报错信息，经过尝试，包括重新创建虚拟环境，仍然无法解决，但是如果我安装paddle cpu版本是可以正常运行的，所以这里是否是paddle-gpu的某一个bug导致，而且没有任何报错信息，只是进程异常退出，而且我发现新建虚拟环境安装paddle-gpu时，会安装tf和torch-cpu，这让人很难受

**Comment by andyjpaddle** [comment]
确保gpu版本的paddle和cuda版本对应
