### ISSUE TITLE
数据增强是否支持 SER 任务？

### ISSUE THREAD

**Issue by sunzhaoyang** [PaddlePaddle/PaddleOCR#9236]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/angle_class.md
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/2182116/221734934-4d99ec03-b9f4-4c31-ba9d-bfe59d46614c.png">

在 Ser 相关的训练配置文件中没有找到 RecAug 相关参数，请问是否支持？

**Comment by andyjpaddle** [comment]
recaug增强主要针对文本识别任务，ser任务目前没有使用数据增强
