### ISSUE TITLE
文本检测 + 文本识别 + 语义实体识别(SER)。这三部可以一次完成吗？还是要先文本检测 + 文本识别的到结果文件。再传给ser预测呢？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9238]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：

```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.json \
Global.infer_mode=False
```
- 完整报错/Complete Error Message：

```
Traceback (most recent call last):
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/tools/infer_kie_token_ser.py", line 147, in <module>
    result, _ = ser_engine(data)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/tools/infer_kie_token_ser.py", line 106, in __call__
    batch = transform(data, self.ops)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppocr/data/imaug/label_ops.py", line 1092, in __call__
    label = info['label']
KeyError: 'label'
python-BaseException
```

system_results.json 中确实没有label字段。这个文件是通过文本检测 + 文本识别  生成的。需要怎么处理呢？？？
如果要  文本检测 + 文本识别 + 语义实体识别(SER)  可以一次性预测吗？？？

**Comment by andyjpaddle** [comment]
可以继续端到端预测 参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/kie/README_ch.md#422-%E5%9F%BA%E4%BA%8E%E5%8A%A8%E6%80%81%E5%9B%BE%E7%9A%84%E9%A2%84%E6%B5%8B

**Comment by rexzhengzhihong** [comment]
这个吗？这个我再2.6分支的文档里没找到，paddleocr需要切换到最新分支吗？
![image](https://user-images.githubusercontent.com/32863094/221773522-cb70c15e-b305-4c67-be00-079d5087347f.png)

**Comment by andyjpaddle** [comment]
2.6分支也有的
```
# 仅预测SER模型
python3 tools/infer_kie_token_ser.py \
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg
```

**Comment by rexzhengzhihong** [comment]
结果有点问题。标注结果差的有点多，怎么查看是在哪里出的问题？文字检测+识别 这步测试没问题
```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
Global.infer_mode=True \
Global.kie_rec_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
Global.kie_det_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student
```

![image](https://user-images.githubusercontent.com/32863094/221776856-044cbf9c-4c23-4a86-91e0-76d81f9b8ce6.png)

**Comment by rexzhengzhihong** [comment]
这是我测试文本检车+识别的。得到的txt文件的准确率还是蛮高的
```
python3 tools/infer/predict_system.py \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgs/zzszyfp.jpg" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student/" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--rec_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
--rec_image_shape="3,48,320" \
--rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/" \
--use_space_char=True \
--use_angle_cls=False
```

**Comment by rexzhengzhihong** [comment]
@andyjpaddle

**Comment by rexzhengzhihong** [comment]
通过文本检测+识别 预测得到的system_results.txt文件。传到到ser模型里预测。得到的效果也没问题的。

```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt \
Global.infer_mode=False
```

**Comment by rexzhengzhihong** [comment]
为什么端到端的会有问题呢

**Comment by andyjpaddle** [comment]
可以debug看下端到端测试中的检测和识别结果和单独检测识别有啥出入

**Comment by rexzhengzhihong** [comment]
端到端 的怎么看每一步的结果？

**Comment by rexzhengzhihong** [comment]
debug看不到 端到端测试中的检测和识别结果。麻烦指导下，感谢
@andyjpaddle

**Comment by rexzhengzhihong** [comment]
![image](https://user-images.githubusercontent.com/32863094/222032865-30952572-5dce-431c-88a1-2ea19dca5263.png)
找到了，怎么看原因呢？

**Comment by rexzhengzhihong** [comment]
txt_detector  中没有可以设置--det_limit_side_len=736  --det_limit_type="min" 值的地方吗？猜测是不是文字检测出了问题
![image](https://user-images.githubusercontent.com/32863094/222037452-c9a9714d-d6b2-4a8c-808c-23cc72b14aca.png)

**Comment by tink2123** [comment]
检测模型是自己训练的吗？ 看命令在推理时需要修改参数：--det_limit_side_len=736  --det_limit_type="min" ， 使用ser端到端推理时，检测参数是默认的 --det_limit_side_len=960 --det_limit_type='max'，肯定会影响检测效果。

目前这个接口没有在命令行暴露出来，可以从源码中修改后处理参数值，https://github.com/PaddlePaddle/PaddleOCR/blob/b2781efacd5587025fb1168ed2b2df1d9d0d6e9d/tools/infer_kie_token_ser.py#L75

**Comment by rexzhengzhihong** [comment]
模型是自己训练的。参数改了是变了。但是检测效果还是一样的，看不出什么原因
![image](https://user-images.githubusercontent.com/32863094/222039329-0c9c6b7e-e61f-4cdc-a06e-156d6f2b585a.png)
![1677642076181](https://user-images.githubusercontent.com/32863094/222039505-4d2d167f-6000-4f5d-9b1e-10ab527797b4.png)

**Comment by rexzhengzhihong** [comment]
text_detector下是不是得有一个det_limit_side_len才有用？现在是在text_detector.args下有改
![image](https://user-images.githubusercontent.com/32863094/222039989-e384e1cf-6c96-481b-91f8-acdc846e09c8.png)

**Comment by rexzhengzhihong** [comment]
@tink2123

**Comment by rexzhengzhihong** [comment]
我把det步骤的参数都贴出来。不一样的有
![image](https://user-images.githubusercontent.com/32863094/222057891-980b5b70-d5de-4b25-b4d4-53be35aff874.png)
![image](https://user-images.githubusercontent.com/32863094/222057990-8e7c0a75-1e6d-4157-930a-f75fac531089.png)
![image](https://user-images.githubusercontent.com/32863094/222058047-8b32c537-8ede-4470-b56b-8682ce34b4f3.png)
![image](https://user-images.githubusercontent.com/32863094/222058098-882d06aa-5084-4873-a650-50f26678b5d4.png)

**Comment by tink2123** [comment]
去掉clas模型试试

**Comment by rexzhengzhihong** [comment]
好像去掉了
![image](https://user-images.githubusercontent.com/32863094/222061235-1b87741c-b1b9-4868-a90b-4460b1ccff9b.png)

**Comment by rexzhengzhihong** [comment]
好像设置关闭没效果？

**Comment by rexzhengzhihong** [comment]
@tink2123

**Comment by rexzhengzhihong** [comment]
dir好像都改不了。
![image](https://user-images.githubusercontent.com/32863094/222086878-d0e57afc-eccc-4c1b-83f5-d672b77d38c9.png)

**Comment by rexzhengzhihong** [comment]
好像自己训练的模型不能用在端对端。我把默认改成ch_PP-OCRv3  默认的。都能识别出一些东西
```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
Global.infer_mode=True \
Global.kie_rec_model_dir=/home/onez/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
Global.kie_det_model_dir=/home/onez/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer
```

**Comment by rexzhengzhihong** [comment]
@tink2123 @andyjpaddle

**Comment by rexzhengzhihong** [comment]
你好。端到端的这种怎么服务部署呢？

**Comment by rexzhengzhihong** [comment]
有文档参考吗

**Comment by cola2023** [comment]
> 好像自己训练的模型不能用在端对端。我把默认改成ch_PP-OCRv3 默认的。都能识别出一些东西
> 
> ```
> python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
> Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
> Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
> Global.infer_mode=True \
> Global.kie_rec_model_dir=/home/onez/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
> Global.kie_det_model_dir=/home/onez/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer
> ```



> KeyError: 'label'

您好，您这个 KeyError: 'label'是怎么解决的，是改的代码吗？

**Comment by cola2023** [comment]
> 

端到端是可以使用自己训练的det模型的，我自己训练的DB算法的是可以正常使用，但是我训练的DB++的就完全使用不了的，就算指定了感觉差不多的参数也不可以使用。您现在是这些问题都解决了吗？可否给些指导。

**Comment by rexzhengzhihong** [comment]
> kie_rec_model_dir

我是用DB

**Comment by cola2023** [comment]
> > kie_rec_model_dir
> 
> 我是用DB

是增加这个参数就可以解决 KeyError: 'label'的问题吗？

**Comment by Johann356** [comment]
> 为什么端到端的会有问题呢

paddleocr.py中484行左右的几个maybedownload注释掉就好了
