### ISSUE TITLE
印章弯曲文字二阶段识别问题。

### ISSUE THREAD

**Issue by wangxinzhe0617** [PaddlePaddle/PaddleOCR#9240]
训练完成dbnet之后得到检测图如下
![2a7db5b26aa93e4d4b19ac70c0da00b5](https://user-images.githubusercontent.com/38687226/221773135-cefa89b8-c3d8-4b9f-9a07-ad57ce1cef91.png)
文档中说使用如下代码将字符从印章中切割出来，但是下图只是针对四点坐标。我想请教一下弯曲文字（云南能投化工有限公司）是怎么处理的呢？是弯曲文字直接也使用四个点坐标切出来训练，还是将弯曲文字变直之后再训练。

import cv2
import numpy as np

def get_rotate_crop_image(img, points):
    '''
    img_height, img_width = img.shape[0:2]
    left = int(np.min(points[:, 0]))
    right = int(np.max(points[:, 0]))
    top = int(np.min(points[:, 1]))
    bottom = int(np.max(points[:, 1]))
    img_crop = img[top:bottom, left:right, :].copy()
    points[:, 0] = points[:, 0] - left
    points[:, 1] = points[:, 1] - top
    '''
    assert len(points) == 4, "shape of points must be 4*2"
    img_crop_width = int(
        max(
            np.linalg.norm(points[0] - points[1]),
            np.linalg.norm(points[2] - points[3])))
    img_crop_height = int(
        max(
            np.linalg.norm(points[0] - points[3]),
            np.linalg.norm(points[1] - points[2])))
    pts_std = np.float32([[0, 0], [img_crop_width, 0],
                          [img_crop_width, img_crop_height],
                          [0, img_crop_height]])
    M = cv2.getPerspectiveTransform(points, pts_std)
    dst_img = cv2.warpPerspective(
        img,
        M, (img_crop_width, img_crop_height),
        borderMode=cv2.BORDER_REPLICATE,
        flags=cv2.INTER_CUBIC)
    dst_img_height, dst_img_width = dst_img.shape[0:2]
    if dst_img_height * 1.0 / dst_img_width >= 1.5:
        dst_img = np.rot90(dst_img)
    return dst_img

def run(data_dir, label_file, save_dir):
    datas = open(label_file, 'r').readlines()
    for idx, line in enumerate(datas):
        img_path, label = line.strip().split('\t')
        img_path = os.path.join(data_dir, img_path)

        label = json.loads(label)
        src_im = cv2.imread(img_path)
        if src_im is None:
            continue

        for anno in label:
            seal_box = anno['seal_box']
            txt_boxes = anno['polys']
            crop_im = get_rotate_crop_image(src_im, text_boxes)

            save_path = os.path.join(save_dir, f'{idx}.png')
            if not os.path.exists(save_dir):
                os.makedirs(save_dir)
            # print(src_im.shape)
            cv2.imwrite(save_path, crop_im

**Comment by LDOUBLEV** [comment]
对于弯曲的文字部分是裁剪最小四边形去训练识别https://github.com/PaddlePaddle/PaddleOCR/blob/d8d76d59c90d922782a4c812f9c720ac77877d5a/tools/infer/utility.py#L633

**Comment by wangxinzhe0617** [comment]
> 对于弯曲的文字部分是裁剪最小四边形去训练识别
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/d8d76d59c90d922782a4c812f9c720ac77877d5a/tools/infer/utility.py#L633

好的谢谢大佬回复。

**Comment by Autismkkk** [comment]
> 训练完成dbnet之后得到检测图如下 ![2a7db5b26aa93e4d4b19ac70c0da00b5](https://user-images.githubusercontent.com/38687226/221773135-cefa89b8-c3d8-4b9f-9a07-ad57ce1cef91.png) 文档中说使用如下代码将字符从印章中切割出来，但是下图只是针对四点坐标。我想请教一下弯曲文字（云南能投化工有限公司）是怎么处理的呢？是弯曲文字直接也使用四个点坐标切出来训练，还是将弯曲文字变直之后再训练。
> 
> import cv2 import numpy as np
> 
> def get_rotate_crop_image(img, points): ''' img_height, img_width = img.shape[0:2] left = int(np.min(points[:, 0])) right = int(np.max(points[:, 0])) top = int(np.min(points[:, 1])) bottom = int(np.max(points[:, 1])) img_crop = img[top:bottom, left:right, :].copy() points[:, 0] = points[:, 0] - left points[:, 1] = points[:, 1] - top ''' assert len(points) == 4, "shape of points must be 4*2" img_crop_width = int( max( np.linalg.norm(points[0] - points[1]), np.linalg.norm(points[2] - points[3]))) img_crop_height = int( max( np.linalg.norm(points[0] - points[3]), np.linalg.norm(points[1] - points[2]))) pts_std = np.float32([[0, 0], [img_crop_width, 0], [img_crop_width, img_crop_height], [0, img_crop_height]]) M = cv2.getPerspectiveTransform(points, pts_std) dst_img = cv2.warpPerspective( img, M, (img_crop_width, img_crop_height), borderMode=cv2.BORDER_REPLICATE, flags=cv2.INTER_CUBIC) dst_img_height, dst_img_width = dst_img.shape[0:2] if dst_img_height * 1.0 / dst_img_width >= 1.5: dst_img = np.rot90(dst_img) return dst_img
> 
> def run(data_dir, label_file, save_dir): datas = open(label_file, 'r').readlines() for idx, line in enumerate(datas): img_path, label = line.strip().split('\t') img_path = os.path.join(data_dir, img_path)
> 
> ```
>     label = json.loads(label)
>     src_im = cv2.imread(img_path)
>     if src_im is None:
>         continue
> 
>     for anno in label:
>         seal_box = anno['seal_box']
>         txt_boxes = anno['polys']
>         crop_im = get_rotate_crop_image(src_im, text_boxes)
> 
>         save_path = os.path.join(save_dir, f'{idx}.png')
>         if not os.path.exists(save_dir):
>             os.makedirs(save_dir)
>         # print(src_im.shape)
>         cv2.imwrite(save_path, crop_im
> ```

您好，我想问下，我用BD++检测的时候，精准率和召回率都特别低只有0.0几，并且在做eval的时候yml中的四个 keepkeys   
        - image
        - shape
        - polys
        - ignore_tags
 向量对齐不了，我做了向量对齐
