### ISSUE TITLE
怎么获得文字检测后的置信度？

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9242]
推理结果只有识别的置信度分数，没有文字检测的置信度分数，我需要这些置信度分数，要怎么获得？谢谢

**Comment by andyjpaddle** [comment]
以DB算法为例，可以在后处理部分输出scores https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/postprocess/db_postprocess.py#L245
同时在预测代码里取出 scores
 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_det.py#L272
