### ISSUE TITLE
请问这种模糊图片怎么提高识别准确率呢？是用大量的清晰图片去训练么？还是用大量已知文字的模糊图片去训练识别模型

### ISSUE THREAD

**Issue by cumthxy** [PaddlePaddle/PaddleOCR#9243]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/22782047/221832664-b821f716-d9cf-48d2-9a04-83a25a0c7c1c.png">

<img width="178" alt="image" src="https://user-images.githubusercontent.com/22782047/221832902-d0641ffd-7fd6-4cbe-bfbd-38decd4dc4b6.png">

请问这种模糊图片怎么提高识别准确率呢？是用大量的清晰图片去训练么？还是用大量已知文字的模糊图片去训练识别模型

**Comment by andyjpaddle** [comment]
这种模糊图片，人肉眼都看不出文字，应该无法训练，或者可以尝试一些超分模型进行预处理

**Comment by SWHL** [comment]
人眼能看清是底线，就算用超分，估计清晰后的文字也不太可信
