### ISSUE TITLE
繁体微调相关问题

### ISSUE THREAD

**Issue by haoxia1** [PaddlePaddle/PaddleOCR#9244]
1. 请问我可以随意删除中文字典中不需要的字符吗，比如删除所有字母、符号以及一些我知道的任务中用不到的汉字。这样还能直接推理吗？
2. 请问我需要对繁体字做一个微调（因为繁体字识别模型效果远不如简体模型）：可以直接在简体字典后面加入我需要的繁体字(不改变前面序列的位置关系)，然后还能使用预训练模型继续微调吗？此时微调数据集是否可以不覆盖所有码表，而只包含我加入的码表？
3. 微调的时候，请问数据集的尺寸最好是多大比较合适，40*40可以吗(我就做单字的)，还是推荐多准备一些尺寸，然后请问一个字大概需要多少张数据进行微调？

感谢您的回答！

**Comment by andyjpaddle** [comment]
1. 如果删除了字符，需要重新finetune模型才能正确推理，可以通过后处理来过滤识别结果，去除识别结果中不需要的字符。
2. 微调不建议修改字典，可以加载繁体模型预训练，在自己的数据上进行微调，微调数据尽量覆盖所有码表
3. 微调不推荐修改训练shape 数据量至少5000张吧，具体可参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83  另外单字也可以试试直接分类模型

**Comment by kenho211** [comment]
如果需要加入chinese_cht_dict.txt 沒有的常見字 (https://github.com/PaddlePaddle/PaddleOCR/issues/9187) ，是否要train from scratch / 不能用預訓練模型 ?

**Comment by haoxia1** [comment]
> 

感谢您的回复！
第三点请问，我是用繁体的长语句图片进行微调，是否可以有效提升我推理的时候单字识别的正确率？(几十万单字确实挺慢的)

然后好像我使用单字的训练集去微调，而配置文件的image_shape为[48, 320, 3]是否相应得改为[48, 48, 3]？

**Comment by haoxia1** [comment]
> 1. 如果删除了字符，需要重新finetune模型才能正确推理，可以通过后处理来过滤识别结果，去除识别结果中不需要的字符。
> 2. 微调不建议修改字典，可以加载繁体模型预训练，在自己的数据上进行微调，微调数据尽量覆盖所有码表
> 3. 微调不推荐修改训练shape 数据量至少5000张吧，具体可参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83  另外单字也可以试试直接分类模型

感谢您的回复！
第三点请问，我是用繁体的长语句图片进行微调，是否可以有效提升我推理的时候单字识别的正确率？(几十万单字确实挺慢的)

然后好像我使用单字的训练集去微调，而配置文件的image_shape为[48, 320, 3]是否相应得改为[48, 48, 3]？

**Comment by andyjpaddle** [comment]
> 如果需要加入chinese_cht_dict.txt 沒有的常見字 (#9187) ，是否要train from scratch / 不能用預訓練模型 ?

改变字典也可以加载预训练，但是最后一层参数shape对不上，需要重新finetune训练

**Comment by andyjpaddle** [comment]
> 繁体的长语句图片进行微调

长句也可以，单字可以试试直接分类模型，改shape可能要适配下模型，不是很推荐改shape

**Comment by kenho211** [comment]
> > 如果需要加入chinese_cht_dict.txt 沒有的常見字 (#9187) ，是否要train from scratch / 不能用預訓練模型 ?
> 
> 改变字典也可以加载预训练，但是最后一层参数shape对不上，需要重新finetune训练

如果使用自定義字典，需要像 https://github.com/PaddlePaddle/PaddleOCR/issues/8514 所說 重新設定 FC 層的維度 / CTC Head 的out_channels 嗎？謝謝

**Comment by kenho211** [comment]
> > > 如果需要加入chinese_cht_dict.txt 沒有的常見字 (#9187) ，是否要train from scratch / 不能用預訓練模型 ?
> > 
> > 
> > 改变字典也可以加载预训练，但是最后一层参数shape对不上，需要重新finetune训练
> 
> 如果使用自定義字典，需要像 #8514 所說 重新設定 FC 層的維度 / CTC Head 的out_channels 嗎？謝謝

已經找到答案了，謝謝。

https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/ppocr/modeling/heads/rec_multi_head.py#L53-L54

https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/tools/train.py#L88-L92
