### ISSUE TITLE
Inference time  issue with Paddle model.

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleOCR#9245]
Hello team in my project i used below models provided by paddlepaddle:
1. Layout analysis model
2. Table recognation model
3. Text detection model
4. Text recognation model

For single page of below image take 15 sec for ocr output in cpu based server.
It is possible to reduce time too 2 to 3 second?

![pu1](https://user-images.githubusercontent.com/87867535/221891857-1ff9b09f-d7e0-4350-b015-3282ce9aa163.jpg)

**Comment by andyjpaddle** [comment]
you can set `enable_mkldnn=True` to speed up in CPU mode

**Comment by TapendraBaduwal** [comment]
@andyjpaddle I already set enable_mkldnn=True but for single page it take 10 to 15 sec....It is possible to reduce time inference to 2/3 sec?

**Comment by andyjpaddle** [comment]
the inference time depends on the performance of your cpu

**Comment by Sayaka91** [comment]
@TapendraBaduwal 
Did you do to reduce the inference time for your process?
Can you share your pipeline?
