### ISSUE TITLE
paddleocr车牌识别中文识别不好

### ISSUE THREAD

**Issue by guiniao** [PaddlePaddle/PaddleOCR#9246]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
我用paddleocr和CCPD2020训练车牌识别的模型，因为样本基本都是皖A的牌照，训练好后模型对其他地方的车牌识别效果不太好，特别是中文，很多都被识别为皖，请问，我需要增加其他地方的车牌标注样本吗

**Comment by tink2123** [comment]
需要的，样本中某个固定词组出现频率过高，会影响识别结果

**Comment by guiniao** [comment]
@tink2123 ，你好，有生成其他地区牌照的方法吗

**Comment by pcb9382** [comment]
车牌车牌识别开源项目可以看看这个：https://github.com/pcb9382/PlateRecognition
