### ISSUE TITLE
多卡/单卡OCR训练错误： no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by quanzhang2020** [PaddlePaddle/PaddleOCR#9247]
环境：
使用dockerhub安装：镜像[2.4.2-gpu-cuda10.2-cudnn7.6-trt7.0]
paddleocr是2.6
报错情况：
使用3090显卡2和3训练PP-OCRv3，报错：
![image](https://user-images.githubusercontent.com/69777965/222024109-cea560b2-aecc-46c5-b49b-9b817ff403b2.png)

**Comment by quanzhang2020** [comment]
验证paddle是否安装正确，进入python解释器，运行：paddle.utils.run_check()
![image](https://user-images.githubusercontent.com/69777965/222031039-f5a56836-8c79-42f1-b7db-32a6366c3b93.png)

**Comment by tink2123** [comment]
0号卡可能无法使用，更换其他卡单独训练试试。另外还是建议解决好paddle安装的问题，参考这个步骤：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html 重新尝试安装paddle

**Comment by quanzhang2020** [comment]
安装是采用dokerhub拉取镜像安装的， 训练之前测试过inference，cpu可以推理，gpu推理结果错误。详见：https://github.com/PaddlePaddle/PaddleOCR/issues/9249。但是我用另外一台T4显卡的机器，cpu和gpu推理都没有问题，难道paddlepaddle用不了3090？？

**Comment by quanzhang2020** [comment]
升级驱动，升级docker 到cuda11.2的版本，inference正常。
