### ISSUE TITLE
OCR识别GPU和CPU结果不一样，GPU结果错误

### ISSUE THREAD

**Issue by quanzhang2020** [PaddlePaddle/PaddleOCR#9249]
环境：
使用dockerhub安装：镜像[2.4.2-gpu-cuda10.2-cudnn7.6-trt7.0]
paddleocr是2.6
GPU:3090
错误情况：
下载ch_PP-OCRv3_det_infer和ch_PP-OCRv3_rec_infer，使用GPU推理，运行命令行：python tools/infer/predict_system.py --image_dir="./doc/imgs/00018069.jpg"  --det_model_dir="./ch_PP-OCRv3_det_infer/"  --rec_model_dir="./ch_PP-OCRv3_rec_infer/"  --use_angle_cls=false --use_mp=True --total_process_num=6 结果错误，如下：
![image](https://user-images.githubusercontent.com/69777965/222060937-86ec59db-b07e-4afc-a61c-efdb094a3966.png)
不适用GPU推理，执行命令行：python tools/infer/predict_system.py --image_dir="./doc/imgs/00018069.jpg"  --det_model_dir="./ch_PP-OCRv3_det_infer/"  --rec_model_dir="./ch_PP-OCRv3_rec_infer/"  --use_angle_cls=false --use_mp=True --total_process_num=6 --use_gpu=False 结果正确，如下：
![image](https://user-images.githubusercontent.com/69777965/222061432-36b89a46-65d6-4cab-84bd-e8edde698164.png)

**Comment by tink2123** [comment]
确认paddle安装cuda版本是否和gpu一致，可以去Paddle repo提一下安装的问题：https://github.com/PaddlePaddle/Paddle/issues

**Comment by quanzhang2020** [comment]
升级驱动，升级cuda到11.2，拉取[2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0]
