### ISSUE TITLE
快速安装  预测时无法启动文字detection模型

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleOCR#925]
大佬，您好，
我想在windows上运行prediction看一下效果。
--------------------------------------------
运行的命令 :   
run tools/infer/predict_system.py --image_dir='./doc/imgs/japan_2.jpg' --det_model_dir = "./inference/ch_ppocr_mobile_v1.1_det_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --rec_model_dir="./inference/japan_ppocr_mobile_v1.1_rec_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False
--------------------------------------------
报错:
predict_system.py: error: unrecognized arguments: ./inference/ch_ppocr_mobile_v1.1_det_infer/
An exception has occurred, use %tb to see the full traceback.
---------------------------------------------
请问是怎么一回事？

**Comment by MissPenguin** [comment]
![image](https://user-images.githubusercontent.com/25809855/95845524-dc6a6c80-0d7c-11eb-8428-8cc4957a6bc8.png)
这个“=”前后的空格去掉

**Comment by terrancraft** [comment]
谢谢大佬，运行之后是这个结果...

RuntimeError: mklml.dll not found.
