### ISSUE TITLE
身份证模型，检测效果还可以，检测+识别就很差了

### ISSUE THREAD

**Issue by yuanqin27** [PaddlePaddle/PaddleOCR#9251]
身份证模型关键信息提取，检测效果还行，运行predict_system.py，检测+识别放一起后，效果很差，识别用的v3，不知道下一步该怎么改进
![det](https://user-images.githubusercontent.com/16290532/222066872-34ce1941-4beb-4e57-a8c1-4e3c69646294.jpg)
![det_rec](https://user-images.githubusercontent.com/16290532/222066903-5350bc72-5625-4c3a-97b9-eea947b5f787.jpg)

**Comment by tink2123** [comment]
检测框不准影响识别模型，可以参考这个范例：https://aistudio.baidu.com/aistudio/projectdetail/4255861?channelType=0&channel=0

**Comment by yuanqin27** [comment]
> 检测框不准影响识别模型，可以参考这个范例：https://aistudio.baidu.com/aistudio/projectdetail/4255861?channelType=0&channel=0

检测框调整了，识别后，发现地址识别不出来，其他的都识别出来了

**Comment by mxzgn** [comment]
请问你的数据量是多少？

**Comment by MeshHun** [comment]
@yuanqin27 
图中的关键信息定位效果是怎么做的呢，麻烦指个路 Tks
