### ISSUE TITLE
如何使用版面分析训练自己的数据集 

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9253]
可以调用版面分析的模型分析自己的数据集嘛 （数据集中的类型不局限于公开数据集中出现的那几种）

**Comment by tink2123** [comment]
可以试用效果，但如果场景和训练数据差异过大，效果可能不会太好

**Comment by AIwang666** [comment]
> 可以尝试使用效果，但如果现场和训练数据差异过大，效果可能不会太好

可以重新标记自己的数据集 然后进行训练吗

**Comment by AIwang666** [comment]
> 可以尝试使用效果，但如果现场和训练数据差异过大，效果可能不会太好

或者请问采用CDLA的训练模型可以训练自己的数据集嘛
![1R%U6X8CXX2$_}X2S1Q I`B](https://user-images.githubusercontent.com/56247915/222098319-7b607f0a-cee4-4da0-ad3a-9b6ce94ed53b.png)

**Comment by KyleWang-Hunter** [comment]
> > 可以尝试使用效果，但如果现场和训练数据差异过大，效果可能不会太好
> 
> 或者请问采用CDLA的训练模型可以训练自己的数据集嘛 ![1R%U6X8CXX2$_}X2S1Q I`B](https://user-images.githubusercontent.com/56247915/222098319-7b607f0a-cee4-4da0-ad3a-9b6ce94ed53b.png)

可以的
