### ISSUE TITLE
为什么两张几乎一样的图片，识别出来的内容会有不同？

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#9254]
rt，本人自己在paddle提供的预训练模型（PPOCR_server_v2.0）上finetune了识别模型，数据是一些合成图片以及一些真实图片，总数据量2.5w，在转为inference模型后进行推理预测，出现了如下图的情况：
![20220322154310origin](https://user-images.githubusercontent.com/74600923/222085366-1ac830a5-c0b5-4a58-a81d-e07173d610b6.jpg)
![20220322154314origin](https://user-images.githubusercontent.com/74600923/222085382-ed784565-4629-4186-9b65-d7a3e77e3bdd.jpg)

在这两张图的“所有人”和“品牌型号”字段，可以发现识别结果不一致，而这两张图片均来自于同一张驾驶证，基本上没有太大的区别，但是出现了这种情况，实在不能理解，求问大佬这是为什么。

**Comment by tink2123** [comment]
可以看下训练样本中 慧 这个字是否出现频率较低，识别模型推理时该字段的置信度应该不高，边缘像素的略微变动都会影响最终结果。

**Comment by Lebron-Harden** [comment]
> 可以看下训练样本中 慧 这个字是否出现频率较低，识别模型推理时该字段的置信度应该不高，边缘像素的略微变动都会影响最终结果。

感谢答复
