### ISSUE TITLE
当我使用文本检测算法DB++进行推理时时，出现了问题

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9255]
![image](https://user-images.githubusercontent.com/110521846/222086025-8769b254-ef58-494a-aef2-5503cc006eb7.png)

**Comment by tink2123** [comment]
ppocr whl包中并不支持DB++ 算法，建议直接使用源码推理

**Comment by luoyq6** [comment]
谢谢您的回复，我想知道什么是ppocr whl？我好像用的就是源码推理



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月01日 17:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] 当我使用文本检测算法DB++进行推理时时，出现了问题 (Issue #9255) |

ppocr whl包中并不支持DB++ 算法，建议直接使用源码推理

**Comment by tink2123** [comment]
参考这个文档进行源码推理：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_det_db.md#4
