### ISSUE TITLE
文本识别训练报错：OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by quanzhang2020** [PaddlePaddle/PaddleOCR#9258]
环境：
显卡3090
paddle：拉取2.4.2的docker
paddleocr：2.6
![image](https://user-images.githubusercontent.com/69777965/222122850-39916053-6bcd-49e8-852f-af1373dd41a6.png)

**Comment by tink2123** [comment]
2.4.2的docker cuda版本和安装的paddle版本是否一致？
