### ISSUE TITLE
KIE Extraction Training on Field Level Classification only

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#9259]
Hi Everyone, 

I want to train a KIE pipeline on my custom dataset where the input is a simple card and I want to output the following:
Field Name and Field Content
for example:
'Name': 'Jordan Michael'
'Birth':'5/11/1990'
etc...

I'm not interested in the relationship between fields, I've read the documentation but it's not clear how to do this simple task because the annotation file has 'linking' parameter

so any idea how can I do this? what modifications can I do on the annotation file?

for example can I just leave the linking parameter empty?

**Comment by botastark** [comment]
On my own dataset I did annotation running the following command:
python PPOCRLabel.py --kie True
created needed fields as assigning it

I don't have any linking parameter in annotation file. Could you please specify where you are receiving whose?

**Comment by ariefwijaya** [comment]
@botastark 
linking is needed for RE model training 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/kie_en.md#12-custom-dataset
<img width="748" alt="image" src="https://user-images.githubusercontent.com/24664153/236997741-0995865a-0e04-410b-a087-15b915676316.png">
