### ISSUE TITLE
版面分析如何开始训练自己的数据

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9262]
RT
![O9(ANS(H$N2G_%C%J7(}J~T](https://user-images.githubusercontent.com/56247915/222153063-067262e3-328e-446a-82a0-a916b1de4fce.png)
（1）请问进行版面分析训练 想要重新训练自己的数据的话是要下载上图中的训练模型嘛，以CDLA为例这个训练模型能不能不局限于CDLA的数据集场景 可以在自己场景的数据进行训练后得到一定的效果吗
（2）还是说CDLA的训练模型只能处理该类型数据集的数据

**Comment by KyleWang-Hunter** [comment]
> RT ![O9(ANS(H$N2G_%C%J7(}J~T](https://user-images.githubusercontent.com/56247915/222153063-067262e3-328e-446a-82a0-a916b1de4fce.png) （1）请问进行版面分析训练 想要重新训练自己的数据的话是要下载上图中的训练模型嘛，以CDLA为例这个训练模型能不能不局限于CDLA的数据集场景 可以在自己场景的数据进行训练后得到一定的效果吗 （2）还是说CDLA的训练模型只能处理该类型数据集的数据

可以在预训练模型的基础上对自己的数据集进行fineturn
