### ISSUE TITLE
怎么使用文本检测算法DB++进行推理？

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9264]
当我使用如图所示的demo代码时，出现错误，ppocr ERROR: det_algorithm must in ['DB']

![image](https://user-images.githubusercontent.com/110521846/222310096-1fff0984-ff37-42fe-bb79-ded893270b29.png)

**Comment by WenmuZhou** [comment]
whl包暂时不支持哈，可以用predict_det.py进行推理
