### ISSUE TITLE
关于 ch_PP-OCRv3 实现精准检测问题

### ISSUE THREAD

**Issue by changyiming** [PaddlePaddle/PaddleOCR#9265]
- 系统环境/System Environment：Centos8,Pyton 3.7
- 版本号/Version：Paddle：  PaddleOCR 2.41
- 训练 ch_PP-OCRv3\ch_PP-OCRv3_det_student.yml
- 训练日志
- [2023/03/01 05:32:47] ppocr INFO: epoch: [33/50], global_step: 750, lr: 0.001000, loss: 0.701992, loss_shrink_maps: 0.369131, loss_threshold_maps: 0.249159, loss_binary_maps: 0.073614, avg_reader_cost: 0.02206 s, avg_batch_cost: 42.53302 s, avg_samples: 8.0, ips: 0.18809 samples/s, eta: 14:44:02
[2023/03/01 05:32:55] ppocr INFO: cur metric, precision: 0.7073170731707317, recall: 0.8923076923076924, hmean: 0.7891156462585034, fps: 0.6708134669493496
[2023/03/01 05:32:55] ppocr INFO: best metric, hmean: 1.0, is_float16: False, precision: 1.0, recall: 1.0, fps: 0.6031369186941493, best_epoch: 10, start_epoch: 23
经过模型训练后，通过推理测试发现不能跟据我样本标注来检测输出检测结果，他把没有标注的内容也检测出来了，请问题是否可以实现跟据我标注的内容来实现精准检测，把不需要的内容排除掉？虽说全部识别出来可以通过后处理来过淲掉一些关键字，但是这样容易出现串内容的情况，有些证件会出现上下两行不同语言，这些内容如果全部识别出来会增加内容取串的概率问题。
![image](https://user-images.githubusercontent.com/15882199/222319240-6e83f813-9e90-4061-af33-bd49e7c7ca6e.png)

下图是我使用一张银行卡测试检测结果，发现他也把文字内容都检测出来，不知道是否有方法可以排除掉我不想要的检测内容？
![image](https://user-images.githubusercontent.com/15882199/222319395-6b559e06-8f48-414f-978f-f7d4d8cf317b.png)

**Comment by WenmuZhou** [comment]
可以只标注你需要的内容试一下

**Comment by changyiming** [comment]
> 可以只标注你需要的内容试一下
@[WenmuZhou](https://github.com/WenmuZhou) 感谢您的解答。

》》我的所有样本都是只标注了我要的内容，且样本都是身份证照片，标注都是很标准。
       现在不知道要怎么做才可以实现精准检测，把没有标注的内容不要检测出来。
![image](https://user-images.githubusercontent.com/15882199/222334488-21f86f80-ac62-44d9-b4cd-0c732ac0a10c.png)

**Comment by WenmuZhou** [comment]
我的意思是，你不想检测的就不标注

**Comment by drenched9** [comment]
感觉你可以试试目标检测，基于目标检测，只标注姓名后面的内容，然后类别就是姓名。这样检测结果会好很多

**Comment by changyiming** [comment]
> 感觉你可以试试目标检测，基于目标检测，只标注姓名后面的内容，然后类别就是姓名。这样检测结果会好很多

@drenched9 感谢建议，这是一个办法，但是这也增加处理过程中复杂度。


> 我的意思是，你不想检测的就不标注

@WenmuZhou 我能明白你的意思，身份证上的内容把不想要的内容不要标注出来再训练模型，我现在就是这样标注的，例身份证反面（中华人民共和国 和 居民身份证 这二行内容就是没有标注的），但是训练出来的模型检测身份证反面这二行内容确都能检测出来，另外，还有很多情况下会把整行内容单做一行内容了，例：我的标注图片中姓名 和 人名字是标的两个框，但是在推理检测时他确检测到一行了，导致识别出来的内容变成一条了。

**Comment by minushuang** [comment]
> > 感觉你可以试试目标检测，基于目标检测，只标注姓名后面的内容，然后类别就是姓名。这样检测结果会好很多
> 
> @drenched9 感谢建议，这是一个办法，但是这也增加处理过程中复杂度。
> 
> > 我的意思是，你不想检测的就不标注
> 
> @WenmuZhou 我能明白你的意思，身份证上的内容把不想要的内容不要标注出来再训练模型，我现在就是这样标注的，例身份证反面（中华人民共和国 和 居民身份证 这二行内容就是没有标注的），但是训练出来的模型检测身份证反面这二行内容确都能检测出来，另外，还有很多情况下会把整行内容单做一行内容了，例：我的标注图片中姓名 和 人名字是标的两个框，但是在推理检测时他确检测到一行了，导致识别出来的内容变成一条了。

最后是怎么解决的呢？个人觉得有几个办法：
第一，添加更多的训练数据。
第二，将一行的内容进行合并标注，并用目标检测的方法进行检测+分类，最后通过正则匹配到对应类别框中提取自己想要的结果。
第三，针对【非自己想要的文字】，可以添加一些样本作为背景。

以上仅为个人观点，未经实验验证。
