### ISSUE TITLE
我在笔记本本地部署的，识别关闭了GPU识别，但是识别一张PDF表格图片耗时太长，几乎30几S

### ISSUE THREAD

**Issue by jiangfan99** [PaddlePaddle/PaddleOCR#9266]
![image](https://user-images.githubusercontent.com/109214143/222324008-2f9eeb70-0288-43cc-9b6e-a464bb468d8c.png)
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz
- 版本号
- paddle-bfloat                   0.1.7
  paddleocr                       2.5.0.3
  paddlepaddle                    2.3.1  

- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
cpu性能会影响推理速度哈

**Comment by jiangfan99** [comment]
> cpu性能会影响推理速度哈

识别时间不大于3秒这样子，请问有推荐的CPU型号吗，或者显卡型号
