### ISSUE TITLE
启动模型训练报错

### ISSUE THREAD

**Issue by yuhai5237** [PaddlePaddle/PaddleOCR#9269]
按照教程准备好数据，修改好配置文件，识别训练和检测训练都是报一样的错

- 系统环境/System Environment：win10  cuda10.2 cudnn7.6 显卡750Ti
- 版本号/Version：Paddle：2.4.1  PaddleOCR： 问题相关组件/Related components：ch_PP-OCRv3_det模型训练和ch_PP-OCRv3_rec模型训练报错
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
-                                               python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml
- 完整报错/Complete Error Message：
- 
![image](https://user-images.githubusercontent.com/24368402/222343742-dec23bff-8896-420e-bb32-fe8ac29eb97b.png)

**Comment by WenmuZhou** [comment]
paddle.utils.run_check()是否正常

**Comment by yuhai5237** [comment]
> paddle.utils.run_check()是否正常

不正常，报一样的错误
![image](https://user-images.githubusercontent.com/24368402/222661671-3d64d2a7-582c-4df8-a672-24dba572c6bd.png)

**Comment by yuhai5237** [comment]
使用2.4.2版本就会报这个错，换成2.3.2版本就没有问题
