### ISSUE TITLE
图片尺寸在 32-64 像素之间时崩溃问题

### ISSUE THREAD

**Issue by shisenxd** [PaddlePaddle/PaddleOCR#927]
preprocess_op.cpp 文件中

  int resize_h = int(float(h) * ratio);
  int resize_w = int(float(w) * ratio);
  if (resize_h % 32 == 0)
    resize_h = resize_h;
  else if (resize_h / 32 < 1 + 1e-5)
    resize_h = 32;
  else
    resize_h = (resize_h / 32 - 1) * 32;

  if (resize_w % 32 == 0)
    resize_w = resize_w;
  else if (resize_w / 32 < 1)
    resize_w = 32;
  else
    resize_w = (resize_w / 32 - 1) * 32;

size 可能为0崩溃

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleOCR/pull/960
