### ISSUE TITLE
自己的训练的模型，ocr检测+识别 预测能得到准确率不错的的结果（.txt文件）。将.txt文件传入自己训练的cer实体识别模型。也能预测出正确的实体信息。

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9270]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

自己的训练的模型，ocr检测+识别 预测能得到准确率不错的的结果（.txt文件）。将.txt文件传入自己训练的cer实体识别模型。也能预测出正确的实体信息。但是如果通过ser预测的时候传入刚刚的检测和识别模型，结果偏差非常大

- ocr检测+识别
```
python3 tools/infer/predict_system.py \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgs/zzszyfp.jpg" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student/" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--rec_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
--rec_image_shape="3,48,320" \
--rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/" \
--use_space_char=True \
--use_angle_cls=False
```
得到/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt文件
[system_results.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10868318/system_results.txt)

- ser预测（不使用ocr,直接使用结果文件进行预测，能得到正确的结果）
```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt \
Global.infer_mode=False
```
得到了想要的结果
![image](https://user-images.githubusercontent.com/32863094/222351631-ec74a743-de67-4163-9af3-cc745c9d1ab5.png)

- 但是，但是。但是。直接使用  ocr检测+识别+ser  端到端预测。结果差太多了。能帮忙看看是为什么吗？？？
```
python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
Global.infer_mode=True \
Global.kie_rec_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
Global.kie_det_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student
```

![image](https://user-images.githubusercontent.com/32863094/222352010-2e6de735-a343-4aa7-a17f-23e1f3279e2c.png)

**Comment by rexzhengzhihong** [comment]
怀疑两种方式的det结果不一致，debug断点看到
方式一：ocr检测+识别中的det步骤，返回19个标注点
![image](https://user-images.githubusercontent.com/32863094/222353113-72906fed-5fc9-4950-9314-ea02e0aca283.png)


方式二：ser 中的det步骤，返回2两个标注点。
![image](https://user-images.githubusercontent.com/32863094/222353609-11793b35-dd41-41b3-958f-86f5f11f6d59.png)


det参数有打印出来。有几处差别，但是看不出什么问题。大佬能帮忙看看吗

**Comment by rexzhengzhihong** [comment]
参数对比如下
![868161afff2cf6e636ce6422842bd38](https://user-images.githubusercontent.com/32863094/222356852-63a07bcf-6cb8-4212-a100-add22fb96fe5.png)
![63e07fe34963a97de3082c2bc733279](https://user-images.githubusercontent.com/32863094/222356889-e3fbfe7a-eda0-4560-acde-55fb732df5eb.png)

![868161afff2cf6e636ce6422842bd38](https://user-images.githubusercontent.com/32863094/222356912-ec5b6b91-2cf3-4fb8-9c6b-24d7ad010ff2.png)

**Comment by rexzhengzhihong** [comment]
感觉是读取图片的时候有问题，一个是cv2.imread(image_file)   一个是with open(data["img_path"], 'rb') as f: img = f.read()

是这个问题吗？需要在哪里改

**Comment by rexzhengzhihong** [comment]
![image](https://user-images.githubusercontent.com/32863094/223007374-cf3865b5-3224-46fa-b230-b1d2ec98a63a.png)
这样改可以吗

**Comment by cola2023** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：
>   ubuntu20.04
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
>   paddle 1.0.2
>   paddle-bfloat 0.1.2
>   paddle2onnx 0.9.7
>   paddlefsl 1.1.0
>   paddlenlp 2.4.1
>   paddleocr 2.6.1.2
>   paddlepaddle-gpu 2.4.1.post116
>   pandas 1.1.5
>   pandocfilters 1.5.0
> * 运行指令/Command Code：
> * 完整报错/Complete Error Message：
> 
> 自己的训练的模型，ocr检测+识别 预测能得到准确率不错的的结果（.txt文件）。将.txt文件传入自己训练的cer实体识别模型。也能预测出正确的实体信息。但是如果通过ser预测的时候传入刚刚的检测和识别模型，结果偏差非常大
> 
> * ocr检测+识别
> 
> ```
> python3 tools/infer/predict_system.py \
> --image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgs/zzszyfp.jpg" \
> --det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student/" \
> --det_limit_side_len=736 \
> --det_limit_type="min" \
> --rec_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
> --rec_image_shape="3,48,320" \
> --rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
> --draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/" \
> --use_space_char=True \
> --use_angle_cls=False
> ```
> 
> 得到/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt文件 [system_results.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10868318/system_results.txt)
> 
> * ser预测（不使用ocr,直接使用结果文件进行预测，能得到正确的结果）
> 
> ```
> python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml -o \
> Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
> Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt \
> Global.infer_mode=False
> ```
> 
> 得到了想要的结果 ![image](https://user-images.githubusercontent.com/32863094/222351631-ec74a743-de67-4163-9af3-cc745c9d1ab5.png)
> 
> * 但是，但是。但是。直接使用  ocr检测+识别+ser  端到端预测。结果差太多了。能帮忙看看是为什么吗？？？
> 
> ```
> python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
> Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
> Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
> Global.infer_mode=True \
> Global.kie_rec_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
> Global.kie_det_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student
> ```
> 
> ![image](https://user-images.githubusercontent.com/32863094/222352010-2e6de735-a343-4aa7-a17f-23e1f3279e2c.png)

你好你这个解决了吗？我也同样的问题，predict_system的时候是正确的但是用infer_kie_token_ser.py串连的时候就不对，得到的boxes数量少了。

**Comment by cola2023** [comment]
> ![image](https://user-images.githubusercontent.com/32863094/223007374-cf3865b5-3224-46fa-b230-b1d2ec98a63a.png) 这样改可以吗

您好，您这个预测时候使用ocr时候差太多的问题是按照您这样改就可以了吗？   我这里也是同样的问题我使用自己训练的DB++用OCR就不太对，但是使用官方的就没有问题，所以不知道问题到底出现在哪里。是自己训练的模型经过你注释掉的这段代码后，我们的模型识别的时候就有问题了吗？那官方的为什么没问题呢

**Comment by rexzhengzhihong** [comment]
> > 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> > 
> > * 系统环境/System Environment：
> >   ubuntu20.04
> > * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
> >   paddle 1.0.2
> >   paddle-bfloat 0.1.2
> >   paddle2onnx 0.9.7
> >   paddlefsl 1.1.0
> >   paddlenlp 2.4.1
> >   paddleocr 2.6.1.2
> >   paddlepaddle-gpu 2.4.1.post116
> >   pandas 1.1.5
> >   pandocfilters 1.5.0
> > * 运行指令/Command Code：
> > * 完整报错/Complete Error Message：
> > 
> > 自己的训练的模型，ocr检测+识别 预测能得到准确率不错的的结果（.txt文件）。将.txt文件传入自己训练的cer实体识别模型。也能预测出正确的实体信息。但是如果通过ser预测的时候传入刚刚的检测和识别模型，结果偏差非常大
> > 
> > * ocr检测+识别
> > 
> > ```
> > python3 tools/infer/predict_system.py \
> > --image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgs/zzszyfp.jpg" \
> > --det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student/" \
> > --det_limit_side_len=736 \
> > --det_limit_type="min" \
> > --rec_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
> > --rec_image_shape="3,48,320" \
> > --rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
> > --draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/" \
> > --use_space_char=True \
> > --use_angle_cls=False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 得到/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt文件 [system_results.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10868318/system_results.txt)
> > 
> > * ser预测（不使用ocr,直接使用结果文件进行预测，能得到正确的结果）
> > 
> > ```
> > python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml -o \
> > Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
> > Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_dec_imgsresult/system_results.txt \
> > Global.infer_mode=False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 得到了想要的结果 ![image](https://user-images.githubusercontent.com/32863094/222351631-ec74a743-de67-4163-9af3-cc745c9d1ab5.png)
> > 
> > * 但是，但是。但是。直接使用  ocr检测+识别+ser  端到端预测。结果差太多了。能帮忙看看是为什么吗？？？
> > 
> > ```
> > python3 tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_zzszyfp_zh.yml  -o \
> > Architecture.Backbone.checkpoints=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm_zzszyfp_zh/best_accuracy \
> > Global.infer_img=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/uie_imgs/zzszyfp.jpg \
> > Global.infer_mode=True \
> > Global.kie_rec_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
> > Global.kie_det_model_dir=/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_inference_dml_dml_1000/Student
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/32863094/222352010-2e6de735-a343-4aa7-a17f-23e1f3279e2c.png)
> 
> 你好你这个解决了吗？我也同样的问题，predict_system的时候是正确的但是用infer_kie_token_ser.py串连的时候就不对，得到的boxes数量少了。

应该不是。因为我到后面也有问题

**Comment by d246810g2000** [comment]
您好，請問解決了嗎？我也有遇到這個問題！

**Comment by Kus66** [comment]
请问问题解决了吗
