### ISSUE TITLE
微调识别模型后，相似的图片，有的识别效果很好，有的比较差

### ISSUE THREAD

**Issue by Lebron-Harden** [PaddlePaddle/PaddleOCR#9273]
rt，最近在做驾驶证识别的工作，为了提高识别的效果，本人使用ppocr_server_v2.0的识别模型作为预训练模型，在自己构建的数据集上进行了训练。数据集2.5w张图片，包括合成图片（人名，地址，字母数字串等）以及真实场景图片（少量驾驶证截取的图片和较多自然场景图片）。

训练之后，效果确实有提升，但是有时候对于相似的图片，有的识别效果很好，有的比较差，如下面两个：
![20220322154327origin](https://user-images.githubusercontent.com/74600923/222381416-b0d693a6-9aa0-4a1e-ae2e-d3d2c88db7de.jpg)
![20220322154417origin](https://user-images.githubusercontent.com/74600923/222381493-f1aa2e46-6440-430e-b0fb-41fb72106aea.jpg)

想请问这种情况应该如何针对性改进训练的策略，感觉这么训练之后鲁棒性不如paddle本身的模型了

**Comment by WenmuZhou** [comment]
识别模型的数据有多少呢

**Comment by Lebron-Harden** [comment]
> 

请问是指测试图片的数量吗？像这样的整张驾驶证图片，现在还只有大几十张，后面应该还会补充的

**Comment by WenmuZhou** [comment]
训练的，可能是因为你的数据集少了

**Comment by Lebron-Harden** [comment]
> 训练的，可能是因为你的数据集少了

我感觉训练数据多了，会把本来应该识别正确的字（一些常见字），识别成训练集中的高频字。因为我的训练集是比较有针对性的，针对PPOCR_v2识别不好的字符去特定合成一些数据，此外就是随机的加了一些自然场景的图片，但也都用字频过滤了（不会有很多高频字）。主要是感觉数据集才是最核心的问题，想要提升效果，还是很难组织一个好的训练集的。
