### ISSUE TITLE
the params loaded from weight file is different between CPU and NPU

### ISSUE THREAD

**Issue by old-steel** [PaddlePaddle/PaddleOCR#9274]
当在npu上进行OCR dbnet的模型训练的时候，loss无法收敛，精度为0。因此排查的时候发现在load预训练模型的时候，neck下的权值在cpu上和npu上是不一样的，在这个位置之后的余弦相似度都不一样了。这里我们在load model之后加了print(model.neck.in5_conv.weight), 显示两边的值不一样。

- 系统环境/System Environment：x86 NPU
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：训练不收敛，精度0
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained.pdparams
- 完整报错/Complete Error Message：
![cpu](https://user-images.githubusercontent.com/37517248/222381831-1bf6649c-5193-4b75-a129-ff1d798017ee.png)
![npu](https://user-images.githubusercontent.com/37517248/222381839-0555a822-b046-4a0f-9ace-3aaf0f4ecbfe.png)

**Comment by LDOUBLEV** [comment]
neck参数不同是正常的，加载的预训练模型只有backbone的参数，neck的参数是随机初始化的
