### ISSUE TITLE
Question about classifier OCR to China and English words

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#9275]
Thanks for great repo

When I use ocr to get text. I want to classifier each word is Chinese or English.
For example my input is:
```
全名/ full name
```
全名: is china word
full name: English word
/ : punctuation

Thank you very much.

**Comment by WenmuZhou** [comment]
Currently not supported

**Comment by phamkhactu** [comment]
@WenmuZhou thank you.
