### ISSUE TITLE
关于文本检测的中文预训练模型问题

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9276]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我想请问，文本检测算法支持很多模型，但是这些模型的的训练模型都只是在ICDAR2015公开数据集上跑的效果，或者别的本质上都是英文数据集。那我想训练中文的数据集的话，可以使用这些预训练模型吗？
![image](https://user-images.githubusercontent.com/94897119/222385218-6352815c-ef50-467e-aa40-ebc985d1e266.png)

**Comment by phb-shiyige-fw** [comment]
希望能得到各位的回复，谢谢 @WenmuZhou

**Comment by LDOUBLEV** [comment]
可以使用

不过你在中文上预训练的话，不如直接使用PP-OCRv3的训练模型做预训练模型，效果会更好
![image](https://user-images.githubusercontent.com/26592129/222658443-bc82d8d3-a5fd-4244-97a3-13be0750ad09.png)

**Comment by phb-shiyige-fw** [comment]
> 可以使用
> 
> 不过你在中文上预训练的话，不如直接使用PP-OCRv3的训练模型做预训练模型，效果会更好 ![image](https://user-images.githubusercontent.com/26592129/222658443-bc82d8d3-a5fd-4244-97a3-13be0750ad09.png)

感谢回复，我还想问清楚一些：
使用PP_OCRv3的训练模型作为预训练模型的话，不会有网络或者模块更换的冲突吗？我的意思是，PPOCRv3的预训练模型是在它本身的网络跑出来的，如果我更换了backbone或者neck，不会出问题吗？

**Comment by LDOUBLEV** [comment]
如果你更换了neck，只加载backbone的参数做为预训练也可以

如果你网络结构都不一样了，那用不上

**Comment by phb-shiyige-fw** [comment]
> 如果你更换了neck，只加载backbone的参数做为预训练也可以
> 
> 如果你网络结构都不一样了，那用不上

非常感谢！
