### ISSUE TITLE
paddleocr c++源码部署，window10编译成功的dll，如何在Windows7 旗舰版 SP1中正常运行，需要的运行库要安装哪些

### ISSUE THREAD

**Issue by zhaocanglong** [PaddlePaddle/PaddleOCR#9277]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows7 旗舰版 SP1
- 版本号/Version： PaddleOCR： 2.6 
- 完整报错/Complete Error Message： window10编译成功的dll报错，找不到指定模块

**Comment by zhaocanglong** [comment]
Windows 10中安装了 
VC_redist.x64.exe
这两个安装后，paddleocr便可以成功执行

**Comment by hiroi-sora** [comment]
> Windows 10中安装了 VC_redist.x64.exe VisualCppBuildTools_Full.exe离线版 这两个安装后，paddleocr便可以成功执行

你好，你是安装完这两个库后就能在Win7下跑ppocr了吗？

**Comment by zhaocanglong** [comment]
这两个安装后不能正常运行，你去padde的issue中去看，我在那边都已经说了

**Comment by zhaocanglong** [comment]
paddle issue 
#51116
