### ISSUE TITLE
Superscript OCR detection in images.

### ISSUE THREAD

**Issue by parthplc** [PaddlePaddle/PaddleOCR#9279]
I cannot extract superscript in text OCR using the PaddleOCR library. Is there Anyway, can I work on this issue?

![Page-1](https://user-images.githubusercontent.com/35425925/222387730-84635adf-bc6f-4ccf-b256-98b89b41ffde.png)

**Comment by callmeabhi07** [comment]
I have been working on this use case for about 6 months now. I tried OCRs like GOCR, tesseract, paddle, nanonets, etc. None of the tools can distinguish a Superscript from the general text characters. Wrt OCR capability Vision OCR does the best job to recognize Superscript Special symbols but still cannot distinguish them.
