### ISSUE TITLE
ocr车牌数据合成

### ISSUE THREAD

**Issue by guiniao** [PaddlePaddle/PaddleOCR#9282]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
用的开源的CCPD和CRPD的车牌样本训练的识别模型，但这些样本基本都是一个地方的，比如都是皖A的，导致模型对其他地市的车牌识别不好，特别是中文，请问有没有其他方法，或者数据合成的方法，生成一些其他地市的车牌样本

**Comment by guiniao** [comment]
@an1018 我用的就是这个，因为基本都是皖A的牌照，导致模型对其他地方的牌照识别不太好，所以想合成一些其他地市的数据

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by pcb9382** [comment]
车牌车牌识别开源项目可以看看这个：https://github.com/pcb9382/PlateRecognition
