### ISSUE TITLE
PPOCRLabel怎样生成可执行文件

### ISSUE THREAD

**Issue by guiniao** [PaddlePaddle/PaddleOCR#9283]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
怎么生成像labelme一样的exe的可执行文件，方便标注人员使用（不然每个标注人员都要本地安装，比较麻烦）

**Comment by zlszhonglongshen** [comment]
是不是考虑搞个web页面呀？

**Comment by guiniao** [comment]
@zlszhonglongshen 那得开发吧，来不及

**Comment by Evezerest** [comment]
你好，目前没有打包的计划，不过可以参考QPT进行打包，与pdf2word的流程比较像 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure/pdf2word
