### ISSUE TITLE
Model Inference with CPU doesn't use all the cores

### ISSUE THREAD

**Issue by ghazalli** [PaddlePaddle/PaddleOCR#9284]
Hi, I'm inferencing some documents with PaddleOCR, how to make the process into Multiprocessing? While inferencing the system only use single core.

![image](https://user-images.githubusercontent.com/52516822/222612347-bf9cccbc-4e9a-41da-9c92-7d0866c7b89b.png)

**Comment by an1018** [comment]
you can refer to [this document](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/inference_ppocr_en.md#text-detection-angle-classification-and-recognition-inference-concatenation), set use_mp and total_process_num

**Comment by ghazalli** [comment]
> you can refer to [this document](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/inference_ppocr_en.md#text-detection-angle-classification-and-recognition-inference-concatenation), set use_mp and total_process_num

solved with your suggetion, thank you
