### ISSUE TITLE
关于表格识别模型 SLANet_ch 数据集

### ISSUE THREAD

**Issue by weirman** [PaddlePaddle/PaddleOCR#9288]
# SLANet_ch 数据准备

根据[配置文件](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/table/SLANet_ch.yml)，数据标签所读取数据标签是**xyxyxyxy**，即四点框。

因此，有以下问题：

1. 四点框所对应的是**单元格**位置还是**单元格中文字**的位置？
2. 如果对应的是**单元格**位置，那么对应于**无线表格**类型，**单元格位置**应该如何标注？
3. 如果我使用**单元格中文字**的位置进行微调需要训练多少epoch，目前训练了14个epoch，发现位置回归仍存在较大偏移，使用真实数据+合成数据共30W左右。
![image](https://user-images.githubusercontent.com/13463086/222661725-358c95dc-1e1f-4d4e-a6f9-ad140113fe2d.png)
4. 在模型训练过程中，发现GPU-Util波动较大，log如下，不知道 avg_reader_cost 是否正常，3090*3，batch_size 48，num_workers=1。

> [2023/03/03 07:45:10] ppocr INFO: epoch: [15/400], global_step: 2680, lr: 0.000750, acc: 0.968750, loss: 0.001055, structure_loss: 0.000150, loc_loss: 0.000891, avg_reader_cost: 0.01281 s, avg_batch_cost: 2.23359 s, avg_samples: 48.0, ips: 21.49004 samples/s, eta: 24 days, 8:30:09
[2023/03/03 07:45:54] ppocr INFO: epoch: [15/400], global_step: 2700, lr: 0.000750, acc: 0.958333, loss: 0.000953, structure_loss: 0.000138, loc_loss: 0.000787, avg_reader_cost: 0.01337 s, avg_batch_cost: 2.16672 s, avg_samples: 48.0, ips: 22.15333 samples/s, eta: 24 days, 8:12:47
[2023/03/03 07:46:38] ppocr INFO: epoch: [15/400], global_step: 2720, lr: 0.000750, acc: 0.979167, loss: 0.000996, structure_loss: 0.000152, loc_loss: 0.000809, avg_reader_cost: 0.01404 s, avg_batch_cost: 2.19950 s, avg_samples: 48.0, ips: 21.82316 samples/s, eta: 24 days, 7:59:18
[2023/03/03 07:47:22] ppocr INFO: epoch: [15/400], global_step: 2740, lr: 0.000750, acc: 0.958333, loss: 0.001013, structure_loss: 0.000204, loc_loss: 0.000789, avg_reader_cost: 0.01343 s, avg_batch_cost: 2.23917 s, avg_samples: 48.0, ips: 21.43652 samples/s, eta: 24 days, 7:50:24
[2023/03/03 07:48:08] ppocr INFO: epoch: [15/400], global_step: 2760, lr: 0.000750, acc: 0.979167, loss: 0.000893, structure_loss: 0.000113, loc_loss: 0.000780, avg_reader_cost: 0.01382 s, avg_batch_cost: 2.26478 s, avg_samples: 48.0, ips: 21.19412 samples/s, eta: 24 days, 7:44:26
[2023/03/03 07:48:54] ppocr INFO: epoch: [15/400], global_step: 2780, lr: 0.000750, acc: 0.958333, loss: 0.001037, structure_loss: 0.000185, loc_loss: 0.000816, avg_reader_cost: 0.01300 s, avg_batch_cost: 2.30789 s, avg_samples: 48.0, ips: 20.79822 samples/s, eta: 24 days, 7:43:14
[2023/03/03 07:49:38] ppocr INFO: epoch: [15/400], global_step: 2800, lr: 0.000750, acc: 0.979167, loss: 0.000924, structure_loss: 0.000157, loc_loss: 0.000773, avg_reader_cost: 0.01334 s, avg_batch_cost: 2.19375 s, avg_samples: 48.0, ips: 21.88034 samples/s, eta: 24 days, 7:29:41
[2023/03/03 07:50:23] ppocr INFO: epoch: [15/400], global_step: 2820, lr: 0.000750, acc: 0.979167, loss: 0.001010, structure_loss: 0.000208, loc_loss: 0.000809, avg_reader_cost: 0.01328 s, avg_batch_cost: 2.25291 s, avg_samples: 48.0, ips: 21.30573 samples/s, eta: 24 days, 7:22:41
[2023/03/03 07:51:06] ppocr INFO: epoch: [15/400], global_step: 2840, lr: 0.000750, acc: 0.979167, loss: 0.001153, structure_loss: 0.000257, loc_loss: 0.000839, avg_reader_cost: 0.01353 s, avg_batch_cost: 2.18054 s, avg_samples: 48.0, ips: 22.01287 samples/s, eta: 24 days, 7:08:03
[2023/03/03 07:51:50] ppocr INFO: epoch: [15/400], global_step: 2860, lr: 0.000750, acc: 0.968750, loss: 0.000891, structure_loss: 0.000187, loc_loss: 0.000703, avg_reader_cost: 0.01288 s, avg_batch_cost: 2.19270 s, avg_samples: 48.0, ips: 21.89078 samples/s, eta: 24 days, 6:54:53
[2023/03/03 07:52:34] ppocr INFO: epoch: [15/400], global_step: 2880, lr: 0.000750, acc: 0.979167, loss: 0.000918, structure_loss: 0.000132, loc_loss: 0.000743, avg_reader_cost: 0.01402 s, avg_batch_cost: 2.19201 s, avg_samples: 48.0, ips: 21.89773 samples/s, eta: 24 days, 6:41:50
[2023/03/03 07:53:18] ppocr INFO: epoch: [15/400], global_step: 2900, lr: 0.000750, acc: 0.979167, loss: 0.000901, structure_loss: 0.000091, loc_loss: 0.000764, avg_reader_cost: 0.01378 s, avg_batch_cost: 2.18783 s, avg_samples: 48.0, ips: 21.93953 samples/s, eta: 24 days, 6:28:31
[2023/03/03 07:54:02] ppocr INFO: epoch: [15/400], global_step: 2920, lr: 0.000750, acc: 0.979167, loss: 0.000898, structure_loss: 0.000150, loc_loss: 0.000759, avg_reader_cost: 0.01407 s, avg_batch_cost: 2.22269 s, avg_samples: 48.0, ips: 21.59545 samples/s, eta: 24 days, 6:18:59

**Comment by rpsipl2021** [comment]
what is the format of dataset, the model you've trained?

**Comment by weirman** [comment]
训练的模型是：表格识别模型 [table_recognition](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/table_recognition.md)，使用配置文件[SLANet_ch.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/table/SLANet_ch.yml)。
数据格式：

> {"filename": "tableGen//28//img//no_border_5032_0B1GJC2BB00PRAZX5G7P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"6\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["务", "，"], "bbox": [819.0, 4.0, 851.0, 4.0, 851.0, 21.0, 819.0, 21.0]}, {"tokens": ["C", "a", "r", "n", "i", "v", "a", "l", "J"], "bbox": [70.0, 35.0, 138.0, 35.0, 138.0, 52.0, 70.0, 52.0]}, {"tokens": ["王", "剑", "的", "传", "统", "形", "象", "，", "以"], "bbox": [169.0, 37.0, 313.0, 37.0, 313.0, 54.0, 169.0, 54.0]}, {"tokens": ["主", "义", "、", "永", "远", "不", "愿", "妥"], "bbox": [343.0, 37.0, 471.0, 37.0, 471.0, 54.0, 343.0, 54.0]}, {"tokens": ["B", "端", "用", "户", "在", "我"], "bbox": [501.0, 37.0, 592.0, 37.0, 592.0, 54.0, 501.0, 54.0]}, {"tokens": ["代", "表", "联", "系", "点", "，"], "bbox": [621.0, 37.0, 717.0, 37.0, 717.0, 54.0, 621.0, 54.0]}, {"tokens": ["》", "的", "声", "音", "。", "”", "李"], "bbox": [747.0, 37.0, 851.0, 37.0, 851.0, 54.0, 747.0, 54.0]}, {"tokens": ["B", "s", "t", "a"], "bbox": [108.0, 67.0, 138.0, 67.0, 138.0, 84.0, 108.0, 84.0]}, {"tokens": ["3", "9", "2", ".", "2", "4"], "bbox": [283.0, 67.0, 327.0, 67.0, 327.0, 84.0, 283.0, 84.0]}, {"tokens": ["8", "2", "1", ".", "1", "8"], "bbox": [441.0, 67.0, 485.0, 67.0, 485.0, 84.0, 441.0, 84.0]}, {"tokens": ["$", "5", "7", "7", "1"], "bbox": [565.0, 67.0, 605.0, 67.0, 605.0, 84.0, 565.0, 84.0]}, {"tokens": ["7", "1", ".", "8", "5"], "bbox": [695.0, 67.0, 731.0, 67.0, 731.0, 84.0, 695.0, 84.0]}, {"tokens": ["2", "2", ".", "7", "7"], "bbox": [829.0, 67.0, 865.0, 67.0, 865.0, 84.0, 829.0, 84.0]}, {"tokens": ["V", "i", "e"], "bbox": [116.0, 97.0, 139.0, 97.0, 139.0, 114.0, 116.0, 114.0]}, {"tokens": ["5"], "bbox": [319.0, 97.0, 327.0, 97.0, 327.0, 114.0, 319.0, 114.0]}, {"tokens": ["7", "9"], "bbox": [469.0, 97.0, 485.0, 97.0, 485.0, 114.0, 469.0, 114.0]}, {"tokens": ["$", "8", "3", "1", "2"], "bbox": [565.0, 97.0, 605.0, 97.0, 605.0, 114.0, 565.0, 114.0]}, {"tokens": ["5", "3", "6", "."], "bbox": [703.0, 97.0, 731.0, 97.0, 731.0, 114.0, 703.0, 114.0]}, {"tokens": ["4", "2", "1", "0"], "bbox": [833.0, 97.0, 865.0, 97.0, 865.0, 114.0, 833.0, 114.0]}, {"tokens": ["应", "，", "迅", "速", "对", "接", "，", "在"], "bbox": [11.0, 130.0, 139.0, 130.0, 139.0, 147.0, 11.0, 147.0]}, {"tokens": ["4", ".", "2", "2"], "bbox": [299.0, 129.0, 327.0, 129.0, 327.0, 146.0, 299.0, 146.0]}, {"tokens": ["9", "6", ".", "0", "5"], "bbox": [449.0, 129.0, 485.0, 129.0, 485.0, 146.0, 449.0, 146.0]}, {"tokens": ["$", "3", "6", "1", "5", ".", "7", "2"], "bbox": [545.0, 129.0, 605.0, 129.0, 605.0, 146.0, 545.0, 146.0]}, {"tokens": []}, {"tokens": ["7", "0", "3", ".", "7", "6"], "bbox": [821.0, 129.0, 865.0, 129.0, 865.0, 146.0, 821.0, 146.0]}, {"tokens": ["一", "步", "降", "低"], "bbox": [75.0, 163.0, 139.0, 163.0, 139.0, 180.0, 75.0, 180.0]}, {"tokens": ["5", "7", "."], "bbox": [307.0, 161.0, 327.0, 161.0, 327.0, 178.0, 307.0, 178.0]}, {"tokens": ["3", "5", "5", "9"], "bbox": [453.0, 161.0, 485.0, 161.0, 485.0, 178.0, 453.0, 178.0]}, {"tokens": ["$", "6", "3", "9", ".", "8", "7"], "bbox": [553.0, 161.0, 605.0, 161.0, 605.0, 178.0, 553.0, 178.0]}, {"tokens": ["9", "."], "bbox": [719.0, 161.0, 731.0, 161.0, 731.0, 178.0, 719.0, 178.0]}, {"tokens": ["9", "4"], "bbox": [849.0, 161.0, 865.0, 161.0, 865.0, 178.0, 849.0, 178.0]}, {"tokens": ["d", "r", "e", "l", "i", "g", "i", "o", "u", "s"], "bbox": [71.0, 193.0, 138.0, 193.0, 138.0, 210.0, 71.0, 210.0]}, {"tokens": ["1", ".", "8", "0"], "bbox": [299.0, 193.0, 327.0, 193.0, 327.0, 210.0, 299.0, 210.0]}, {"tokens": ["2", "5", "0"], "bbox": [461.0, 193.0, 485.0, 193.0, 485.0, 210.0, 461.0, 210.0]}, {"tokens": ["$", "9", "9", "6", "9", ".", "1", "3"], "bbox": [545.0, 193.0, 605.0, 193.0, 605.0, 210.0, 545.0, 210.0]}, {"tokens": ["0", ".", "3"], "bbox": [711.0, 193.0, 731.0, 193.0, 731.0, 210.0, 711.0, 210.0]}, {"tokens": ["2", "6", "6", ".", "9", "6"], "bbox": [821.0, 193.0, 865.0, 193.0, 865.0, 210.0, 821.0, 210.0]}, {"tokens": ["W", "i", "n", "d", "i", "n", "g", "e", "s"], "bbox": [66.0, 223.0, 139.0, 223.0, 139.0, 240.0, 66.0, 240.0]}, {"tokens": ["1", "5", "4", "1"], "bbox": [295.0, 223.0, 327.0, 223.0, 327.0, 240.0, 295.0, 240.0]}, {"tokens": ["6", ".", "8", "2"], "bbox": [457.0, 223.0, 485.0, 223.0, 485.0, 240.0, 457.0, 240.0]}, {"tokens": ["$", "9"], "bbox": [589.0, 223.0, 605.0, 223.0, 605.0, 240.0, 589.0, 240.0]}, {"tokens": ["9", "7", "0", ".", "8", "1"], "bbox": [687.0, 223.0, 731.0, 223.0, 731.0, 240.0, 687.0, 240.0]}, {"tokens": ["5", "8", "2", ".", "3", "2"], "bbox": [821.0, 223.0, 865.0, 223.0, 865.0, 240.0, 821.0, 240.0]}, {"tokens": ["S", "h", "i", "h", "o", "N", "o", "b", "u"], "bbox": [62.0, 253.0, 139.0, 253.0, 139.0, 270.0, 62.0, 270.0]}, {"tokens": ["4", "7", "7", ".", "5", "4"], "bbox": [283.0, 253.0, 327.0, 253.0, 327.0, 270.0, 283.0, 270.0]}, {"tokens": ["2", "1", "2"], "bbox": [461.0, 253.0, 485.0, 253.0, 485.0, 270.0, 461.0, 270.0]}, {"tokens": []}, {"tokens": ["2", "5", ".", "4", "6"], "bbox": [695.0, 253.0, 731.0, 253.0, 731.0, 270.0, 695.0, 270.0]}, {"tokens": ["2", "4", "."], "bbox": [845.0, 253.0, 865.0, 253.0, 865.0, 270.0, 845.0, 270.0]}, {"tokens": ["社", "群", "共", "建", "“", "玩", "”", "出", "圈", "■"], "bbox": [1.0, 286.0, 139.0, 286.0, 139.0, 303.0, 1.0, 303.0]}, {"tokens": ["2", "2", "1", "2"], "bbox": [295.0, 285.0, 327.0, 285.0, 327.0, 302.0, 295.0, 302.0]}, {"tokens": ["5", "3"], "bbox": [469.0, 285.0, 485.0, 285.0, 485.0, 302.0, 469.0, 302.0]}, {"tokens": ["$", "7", ".", "0", "7"], "bbox": [569.0, 285.0, 605.0, 285.0, 605.0, 302.0, 569.0, 302.0]}, {"tokens": ["9", "3", "4"], "bbox": [707.0, 285.0, 731.0, 285.0, 731.0, 302.0, 707.0, 302.0]}, {"tokens": ["9", "2", "4", "1"], "bbox": [833.0, 285.0, 865.0, 285.0, 865.0, 302.0, 833.0, 302.0]}]}}

![no_border_5032_0B1GJC2BB00PRAZX5G7P](https://user-images.githubusercontent.com/13463086/222681171-908c3a07-8b71-4500-b5bc-8484e365e03b.jpg)

**bbox是单元格中文字的位置。**

**Comment by rpsipl2021** [comment]
![Screenshot from 2023-03-03 15-12-09](https://user-images.githubusercontent.com/113658786/222686895-33d02c41-c874-4945-9e19-b5db080e821b.png)
got error!

**Comment by weirman** [comment]
GitHub 的markdown 把它过滤了。。

{"filename": "tableGen//28//img//no_border_5032_0B1GJC2BB00PRAZX5G7P.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " colspan=\"6\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>"]}, "cells": [{"tokens": ["务", "，"], "bbox": [819.0, 4.0, 851.0, 4.0, 851.0, 21.0, 819.0, 21.0]}, {"tokens": ["C", "a", "r", "n", "i", "v", "a", "l", "J"], "bbox": [70.0, 35.0, 138.0, 35.0, 138.0, 52.0, 70.0, 52.0]}, {"tokens": ["王", "剑", "的", "传", "统", "形", "象", "，", "以"], "bbox": [169.0, 37.0, 313.0, 37.0, 313.0, 54.0, 169.0, 54.0]}, {"tokens": ["主", "义", "、", "永", "远", "不", "愿", "妥"], "bbox": [343.0, 37.0, 471.0, 37.0, 471.0, 54.0, 343.0, 54.0]}, {"tokens": ["B", "端", "用", "户", "在", "我"], "bbox": [501.0, 37.0, 592.0, 37.0, 592.0, 54.0, 501.0, 54.0]}, {"tokens": ["代", "表", "联", "系", "点", "，"], "bbox": [621.0, 37.0, 717.0, 37.0, 717.0, 54.0, 621.0, 54.0]}, {"tokens": ["》", "的", "声", "音", "。", "”", "李"], "bbox": [747.0, 37.0, 851.0, 37.0, 851.0, 54.0, 747.0, 54.0]}, {"tokens": ["B", "s", "t", "a"], "bbox": [108.0, 67.0, 138.0, 67.0, 138.0, 84.0, 108.0, 84.0]}, {"tokens": ["3", "9", "2", ".", "2", "4"], "bbox": [283.0, 67.0, 327.0, 67.0, 327.0, 84.0, 283.0, 84.0]}, {"tokens": ["8", "2", "1", ".", "1", "8"], "bbox": [441.0, 67.0, 485.0, 67.0, 485.0, 84.0, 441.0, 84.0]}, {"tokens": ["$", "5", "7", "7", "1"], "bbox": [565.0, 67.0, 605.0, 67.0, 605.0, 84.0, 565.0, 84.0]}, {"tokens": ["7", "1", ".", "8", "5"], "bbox": [695.0, 67.0, 731.0, 67.0, 731.0, 84.0, 695.0, 84.0]}, {"tokens": ["2", "2", ".", "7", "7"], "bbox": [829.0, 67.0, 865.0, 67.0, 865.0, 84.0, 829.0, 84.0]}, {"tokens": ["V", "i", "e"], "bbox": [116.0, 97.0, 139.0, 97.0, 139.0, 114.0, 116.0, 114.0]}, {"tokens": ["5"], "bbox": [319.0, 97.0, 327.0, 97.0, 327.0, 114.0, 319.0, 114.0]}, {"tokens": ["7", "9"], "bbox": [469.0, 97.0, 485.0, 97.0, 485.0, 114.0, 469.0, 114.0]}, {"tokens": ["$", "8", "3", "1", "2"], "bbox": [565.0, 97.0, 605.0, 97.0, 605.0, 114.0, 565.0, 114.0]}, {"tokens": ["5", "3", "6", "."], "bbox": [703.0, 97.0, 731.0, 97.0, 731.0, 114.0, 703.0, 114.0]}, {"tokens": ["4", "2", "1", "0"], "bbox": [833.0, 97.0, 865.0, 97.0, 865.0, 114.0, 833.0, 114.0]}, {"tokens": ["应", "，", "迅", "速", "对", "接", "，", "在"], "bbox": [11.0, 130.0, 139.0, 130.0, 139.0, 147.0, 11.0, 147.0]}, {"tokens": ["4", ".", "2", "2"], "bbox": [299.0, 129.0, 327.0, 129.0, 327.0, 146.0, 299.0, 146.0]}, {"tokens": ["9", "6", ".", "0", "5"], "bbox": [449.0, 129.0, 485.0, 129.0, 485.0, 146.0, 449.0, 146.0]}, {"tokens": ["$", "3", "6", "1", "5", ".", "7", "2"], "bbox": [545.0, 129.0, 605.0, 129.0, 605.0, 146.0, 545.0, 146.0]}, {"tokens": []}, {"tokens": ["7", "0", "3", ".", "7", "6"], "bbox": [821.0, 129.0, 865.0, 129.0, 865.0, 146.0, 821.0, 146.0]}, {"tokens": ["一", "步", "降", "低"], "bbox": [75.0, 163.0, 139.0, 163.0, 139.0, 180.0, 75.0, 180.0]}, {"tokens": ["5", "7", "."], "bbox": [307.0, 161.0, 327.0, 161.0, 327.0, 178.0, 307.0, 178.0]}, {"tokens": ["3", "5", "5", "9"], "bbox": [453.0, 161.0, 485.0, 161.0, 485.0, 178.0, 453.0, 178.0]}, {"tokens": ["$", "6", "3", "9", ".", "8", "7"], "bbox": [553.0, 161.0, 605.0, 161.0, 605.0, 178.0, 553.0, 178.0]}, {"tokens": ["9", "."], "bbox": [719.0, 161.0, 731.0, 161.0, 731.0, 178.0, 719.0, 178.0]}, {"tokens": ["9", "4"], "bbox": [849.0, 161.0, 865.0, 161.0, 865.0, 178.0, 849.0, 178.0]}, {"tokens": ["d", "r", "e", "l", "i", "g", "i", "o", "u", "s"], "bbox": [71.0, 193.0, 138.0, 193.0, 138.0, 210.0, 71.0, 210.0]}, {"tokens": ["1", ".", "8", "0"], "bbox": [299.0, 193.0, 327.0, 193.0, 327.0, 210.0, 299.0, 210.0]}, {"tokens": ["2", "5", "0"], "bbox": [461.0, 193.0, 485.0, 193.0, 485.0, 210.0, 461.0, 210.0]}, {"tokens": ["$", "9", "9", "6", "9", ".", "1", "3"], "bbox": [545.0, 193.0, 605.0, 193.0, 605.0, 210.0, 545.0, 210.0]}, {"tokens": ["0", ".", "3"], "bbox": [711.0, 193.0, 731.0, 193.0, 731.0, 210.0, 711.0, 210.0]}, {"tokens": ["2", "6", "6", ".", "9", "6"], "bbox": [821.0, 193.0, 865.0, 193.0, 865.0, 210.0, 821.0, 210.0]}, {"tokens": ["W", "i", "n", "d", "i", "n", "g", "e", "s"], "bbox": [66.0, 223.0, 139.0, 223.0, 139.0, 240.0, 66.0, 240.0]}, {"tokens": ["1", "5", "4", "1"], "bbox": [295.0, 223.0, 327.0, 223.0, 327.0, 240.0, 295.0, 240.0]}, {"tokens": ["6", ".", "8", "2"], "bbox": [457.0, 223.0, 485.0, 223.0, 485.0, 240.0, 457.0, 240.0]}, {"tokens": ["$", "9"], "bbox": [589.0, 223.0, 605.0, 223.0, 605.0, 240.0, 589.0, 240.0]}, {"tokens": ["9", "7", "0", ".", "8", "1"], "bbox": [687.0, 223.0, 731.0, 223.0, 731.0, 240.0, 687.0, 240.0]}, {"tokens": ["5", "8", "2", ".", "3", "2"], "bbox": [821.0, 223.0, 865.0, 223.0, 865.0, 240.0, 821.0, 240.0]}, {"tokens": ["S", "h", "i", "h", "o", "N", "o", "b", "u"], "bbox": [62.0, 253.0, 139.0, 253.0, 139.0, 270.0, 62.0, 270.0]}, {"tokens": ["4", "7", "7", ".", "5", "4"], "bbox": [283.0, 253.0, 327.0, 253.0, 327.0, 270.0, 283.0, 270.0]}, {"tokens": ["2", "1", "2"], "bbox": [461.0, 253.0, 485.0, 253.0, 485.0, 270.0, 461.0, 270.0]}, {"tokens": []}, {"tokens": ["2", "5", ".", "4", "6"], "bbox": [695.0, 253.0, 731.0, 253.0, 731.0, 270.0, 695.0, 270.0]}, {"tokens": ["2", "4", "."], "bbox": [845.0, 253.0, 865.0, 253.0, 865.0, 270.0, 845.0, 270.0]}, {"tokens": ["社", "群", "共", "建", "“", "玩", "”", "出", "圈", "■"], "bbox": [1.0, 286.0, 139.0, 286.0, 139.0, 303.0, 1.0, 303.0]}, {"tokens": ["2", "2", "1", "2"], "bbox": [295.0, 285.0, 327.0, 285.0, 327.0, 302.0, 295.0, 302.0]}, {"tokens": ["5", "3"], "bbox": [469.0, 285.0, 485.0, 285.0, 485.0, 302.0, 469.0, 302.0]}, {"tokens": ["$", "7", ".", "0", "7"], "bbox": [569.0, 285.0, 605.0, 285.0, 605.0, 302.0, 569.0, 302.0]}, {"tokens": ["9", "3", "4"], "bbox": [707.0, 285.0, 731.0, 285.0, 731.0, 302.0, 707.0, 302.0]}, {"tokens": ["9", "2", "4", "1"], "bbox": [833.0, 285.0, 865.0, 285.0, 865.0, 302.0, 833.0, 302.0]}]}}

**Comment by weirman** [comment]
请检查你的数据，不要在我的 issues 提出你的问题。

**Comment by weirman** [comment]
@WenmuZhou wenmu大佬，能不能抽空看一眼~

**Comment by Jsooooooo** [comment]
老哥问下你的标注数据里bbox是单元格的坐标还是里面文字框的坐标？还有是不是一开始训练acc一直都是0的

**Comment by Jsooooooo** [comment]
我看你这个acc这么高识别出来咋这么差- -

**Comment by weirman** [comment]
1、bbox 在 tablemaster 里面是文字位置，在SLANet里面是单元格位置，具体是那个位置取决于你的数据方式，目前，我还没有测试单元格位置的方案。
2、acc 在开始时候会是 0，要等训练一会。acc 只看单元格序列准确率，不看单元格回归准确率。

**Comment by Jsooooooo** [comment]
请问你无线表格识别的怎么样？
