### ISSUE TITLE
训练中文文档数据集，评估集指标很高，但是实际测试效果差

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleOCR#9289]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：paddlepaddle-gpu 2.4.0.post117  PaddleOCR： 问题相关组件/Related components：文本识别模型
- 运行指令/Command Code：`python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/rec/rec_r34_vd_none_none_ctc.yml`
- 完整报错/Complete Error Message：评估集指标很高，但是实际使用效果差
- 您好，我训练文本识别模型rec_r34_vd_none_none_ctc，训练集是"中文文档文字识别"（364万张文本图像），训练到第4轮时候，评估集指标就很高了(acc=0.97)，我尝试使用该模型测试，(文本检测和分类模型用pp-ocrv3)，最终得到的识别效果不理想，请问怎么解决这个问题呢？测试指令如下：
`python3 tools/infer/predict_system.py --use_gpu=True \
--det_model_dir=./models/ch_PP-OCRv3_det_infer \
--rec_model_dir=./models/ch_PP-OCRv3_rec_infer/ \
--cls_model_dir=./models/ch_ppocr_mobile_v2.0_cls_infer \
--image_dir=./doc/imgs/doc1.JPG \
--rec_image_shape='3,32,100' \
--rec_char_dict_path=ppocr/utils/char_std_5990.txt`

![image](https://user-images.githubusercontent.com/44281534/222666546-75d2c050-0daa-4e27-9a8b-2c6fbe766856.png)

**Comment by LDOUBLEV** [comment]
单独运行检测模型看下，从你的可视化结果来看漏检问题比较严重

可以设置use_dilation=True  设置较小的box_thresh缓解漏检问题

**Comment by gsx1378** [comment]
最终发现是训练数据的问题，训练/测试图像统一是3x32x280，而训练尺寸是3x32x100，导致每一张图像的字符都被压缩，所以能够在测试集却的较好的效果。但是实际测试图像，短字符的文本框被补边至3x32x100，字符未被压缩，所以导致识别效果差。
