### ISSUE TITLE
what is the proper dataset format for training SLANet model(table detection)

### ISSUE THREAD

**Issue by rpsipl2021** [PaddlePaddle/PaddleOCR#9290]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.4.2
- 运行指令/Command Code：python tools/train.py -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：not able to specify the error
- can you please provide the proper dataset format, given format in readme not working for me

**Comment by UserWangZz** [comment]
You can reference this document.
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/table_recognition.md
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
