### ISSUE TITLE
Missing inference script for Layout Detection

### ISSUE THREAD

**Issue by kenho211** [PaddlePaddle/PaddleOCR#9291]
In README, it says use tools/infer.py for running inference for Layout Detection, but this script is absent in tools dir

**Comment by an1018** [comment]
you need to run in PaddleDetection repo，refer to：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/layout/README.md#32-install-paddledetection

**Comment by mllife** [comment]
@kenho211 , try this https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#22-use-by-python-script but this only loads the 9.7mb default model for inference, i am also unable to load pertained models mentioned here https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list_en.md#:~:text=ppyolov2_r50vd_dcn_365e_publaynet,same%20as%20above

if you find anything, also contribute to my issue by helping - https://github.com/PaddlePaddle/PaddleOCR/issues/10476

**Comment by kenho211** [comment]
Please see https://github.com/PaddlePaddle/PaddleOCR/issues/9654
