### ISSUE TITLE
弯曲文本(印章)识别与检测 微信群

### ISSUE THREAD

**Issue by sisrfeng** [PaddlePaddle/PaddleOCR#9293]
请问官方有这样的群吗? 没有的话, 这里有个刚建的群, 欢迎讨论~
![281a176c6c18c3f3f5dc5962ec2f2ba](https://user-images.githubusercontent.com/53520949/222693777-566d4079-079f-4124-9b1f-f620fc65fc5b.jpg)

**Comment by xinxin19950423** [comment]
失效了

**Comment by Tuannnxlf** [comment]
加我一个呗，微信号：xlf159289

**Comment by sisrfeng** [comment]
不好意思哈各位, 群主暂时不做印章识别了. 希望paddle官方能建立类似的细分群, 而非所有问题都在500人大水群里
