### ISSUE TITLE
单机多卡训练出错ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by 1wang11lijian1** [PaddlePaddle/PaddleOCR#9294]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10, python3.7
- 版本号/Version：2.6 Paddle：2.6  PaddleOCR： 问题相关组件/Related components：单机单卡跟单机多卡训练检测模型出现问题，报错 ValueError: invalid literal for int() with base 10: "'1'"
- 运行指令/Command Code：python -m paddle.distributed.launch --gpus '1' tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
- 完整报错/Complete Error Message：
- python -m paddle.distributed.launch --gpus '1' tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
LAUNCH INFO 2023-03-03 17:39:16,741 -----------  Configuration  ----------------------
LAUNCH INFO 2023-03-03 17:39:16,741 devices: None
LAUNCH INFO 2023-03-03 17:39:16,742 elastic_level: -1
LAUNCH INFO 2023-03-03 17:39:16,742 elastic_timeout: 30
LAUNCH INFO 2023-03-03 17:39:16,742 gloo_port: 6767
LAUNCH INFO 2023-03-03 17:39:16,742 host: None
LAUNCH INFO 2023-03-03 17:39:16,742 job_id: default
LAUNCH INFO 2023-03-03 17:39:16,742 legacy: False
LAUNCH INFO 2023-03-03 17:39:16,742 log_dir: log
LAUNCH INFO 2023-03-03 17:39:16,742 log_level: INFO
LAUNCH INFO 2023-03-03 17:39:16,742 master: None
LAUNCH INFO 2023-03-03 17:39:16,743 max_restart: 3
LAUNCH INFO 2023-03-03 17:39:16,743 nnodes: 1
LAUNCH INFO 2023-03-03 17:39:16,743 nproc_per_node: None
LAUNCH INFO 2023-03-03 17:39:16,743 rank: -1
LAUNCH INFO 2023-03-03 17:39:16,743 run_mode: collective
LAUNCH INFO 2023-03-03 17:39:16,743 server_num: None
LAUNCH INFO 2023-03-03 17:39:16,743 servers:
LAUNCH INFO 2023-03-03 17:39:16,743 trainer_num: None
LAUNCH INFO 2023-03-03 17:39:16,743 trainers:
LAUNCH INFO 2023-03-03 17:39:16,743 training_script: '1'
LAUNCH INFO 2023-03-03 17:39:16,743 training_script_args: ['tools/train.py', '-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml']
LAUNCH INFO 2023-03-03 17:39:16,744 with_gloo: 0
LAUNCH INFO 2023-03-03 17:39:16,744 --------------------------------------------------
LAUNCH WARNING 2023-03-03 17:39:16,744 Compatible mode enable with args ['--gpus']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: '1'
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml']
worker_num: None
workers:
------------------------------------------------
WARNING 2023-03-03 17:39:16,747 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2023-03-03 17:39:16,747 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
launch train in GPU mode!
INFO 2023-03-03 17:39:16,750 launch_utils.py:561] Local start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:54188               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:54188               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '1'                     |
    |                 PADDLE_WORLD_DEVICE_IDS                       '1'                     |
    |                     FLAGS_selected_gpus                       '1'                     |
    |             FLAGS_selected_accelerators                       '1'                     |
    +=======================================================================================+

INFO 2023-03-03 17:39:16,750 launch_utils.py:561] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:54188               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:54188               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '1'                     |
    |                 PADDLE_WORLD_DEVICE_IDS                       '1'                     |
    |                     FLAGS_selected_gpus                       '1'                     |
    |             FLAGS_selected_accelerators                       '1'                     |
    +=======================================================================================+

INFO 2023-03-03 17:39:16,752 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2023-03-03 17:39:16,752 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
launch proc_id:3668 idx:0
Traceback (most recent call last):
  File "tools/train.py", line 27, in <module>
    import paddle
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\__init__.py", line 344, in <module>
    from .hapi import Model  # noqa: F401
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\hapi\__init__.py", line 25, in <module>
    logger.setup_logger()
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\hapi\logger.py", line 47, in setup_logger
    local_rank = ParallelEnv().local_rank
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 125, in __init__
    self._device_id = int(selected_gpus[0])
ValueError: invalid literal for int() with base 10: "'1'"
INFO 2023-03-03 17:39:22,892 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 17:39:22,892 launch_utils.py:343] terminate all the procs
ERROR 2023-03-03 17:39:22,892 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2023-03-03 17:39:22,892 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2023-03-03 17:39:25,898 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 17:39:25,898 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 17:39:25,898 launch.py:402] Local processes completed.
INFO 2023-03-03 17:39:25,898 launch.py:402] Local processes completed.

**Comment by an1018** [comment]
多卡GPU只设置了1个，python -m paddle.distributed.launch --gpus '1'，改为--gpus '0,1,2,3'这种

**Comment by 1wang11lijian1** [comment]
你好，我使用多卡训练也是不行的，下面是我刚刚运行的结果
python -m paddle.distributed.launch --gpus '0,1' tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
以下是报错内容
LAUNCH INFO 2023-03-03 20:32:56,571 -----------  Configuration  ----------------------
LAUNCH INFO 2023-03-03 20:32:56,571 devices: None
LAUNCH INFO 2023-03-03 20:32:56,571 elastic_level: -1
LAUNCH INFO 2023-03-03 20:32:56,571 elastic_timeout: 30
LAUNCH INFO 2023-03-03 20:32:56,572 gloo_port: 6767
LAUNCH INFO 2023-03-03 20:32:56,572 host: None
LAUNCH INFO 2023-03-03 20:32:56,572 job_id: default
LAUNCH INFO 2023-03-03 20:32:56,572 legacy: False
LAUNCH INFO 2023-03-03 20:32:56,572 log_dir: log
LAUNCH INFO 2023-03-03 20:32:56,572 log_level: INFO
LAUNCH INFO 2023-03-03 20:32:56,572 master: None
LAUNCH INFO 2023-03-03 20:32:56,572 max_restart: 3
LAUNCH INFO 2023-03-03 20:32:56,572 nnodes: 1
LAUNCH INFO 2023-03-03 20:32:56,572 nproc_per_node: None
LAUNCH INFO 2023-03-03 20:32:56,572 rank: -1
LAUNCH INFO 2023-03-03 20:32:56,573 run_mode: collective
LAUNCH INFO 2023-03-03 20:32:56,573 server_num: None
LAUNCH INFO 2023-03-03 20:32:56,573 servers:
LAUNCH INFO 2023-03-03 20:32:56,573 trainer_num: None
LAUNCH INFO 2023-03-03 20:32:56,573 trainers:
LAUNCH INFO 2023-03-03 20:32:56,573 training_script: '0,1'
LAUNCH INFO 2023-03-03 20:32:56,573 training_script_args: ['tools/train.py', '-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml']
LAUNCH INFO 2023-03-03 20:32:56,573 with_gloo: 0
LAUNCH INFO 2023-03-03 20:32:56,573 --------------------------------------------------
LAUNCH WARNING 2023-03-03 20:32:56,573 Compatible mode enable with args ['--gpus']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: '0,1'
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml']
worker_num: None
workers:
------------------------------------------------
WARNING 2023-03-03 20:32:56,577 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2023-03-03 20:32:56,577 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
launch train in GPU mode!
INFO 2023-03-03 20:32:56,579 launch_utils.py:561] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55643               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:55643,127.0.0.1:55644       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                      '0,1'                    |
    |                     FLAGS_selected_gpus                       '0                      |
    |             FLAGS_selected_accelerators                       '0                      |
    +=======================================================================================+

INFO 2023-03-03 20:32:56,579 launch_utils.py:561] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55643               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:55643,127.0.0.1:55644       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                      '0,1'                    |
    |                     FLAGS_selected_gpus                       '0                      |
    |             FLAGS_selected_accelerators                       '0                      |
    +=======================================================================================+

INFO 2023-03-03 20:32:56,581 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2023-03-03 20:32:56,581 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
launch proc_id:20372 idx:0
launch proc_id:15668 idx:1
Traceback (most recent call last):
  File "tools/train.py", line 27, in <module>
    import paddle
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\__init__.py", line 344, in <module>
    from .hapi import Model  # noqa: F401
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\hapi\__init__.py", line 25, in <module>
    logger.setup_logger()
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\hapi\logger.py", line 47, in setup_logger
    local_rank = ParallelEnv().local_rank
  File "C:\Users\user\.conda\envs\paddle_ocr\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 125, in __init__
    self._device_id = int(selected_gpus[0])
ValueError: invalid literal for int() with base 10: "'0"
INFO 2023-03-03 20:33:02,686 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 20:33:02,686 launch_utils.py:343] terminate all the procs
ERROR 2023-03-03 20:33:02,686 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
ERROR 2023-03-03 20:33:02,686 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2023-03-03 20:33:05,688 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 20:33:05,688 launch_utils.py:343] terminate all the procs
INFO 2023-03-03 20:33:05,688 launch.py:402] Local processes completed.
INFO 2023-03-03 20:33:05,688 launch.py:402] Local processes completed.
