### ISSUE TITLE
训练模型的一些问题

### ISSUE THREAD

**Issue by H-eaven-1** [PaddlePaddle/PaddleOCR#9296]
paddle可以在已经训练好的官方模型的基础上继续训练吗？ 新的样本数量可能不断增加，每回都要重新训练吗

**Comment by an1018** [comment]
如果场景相差不多，预测效果比较好就不需要重新训练

**Comment by an1018** [comment]
可以的，在初始模型上finetune训练

**Comment by zhwshr** [comment]
> 可以的，在初始模型上finetune训练

好，谢谢
