### ISSUE TITLE
PaddleOCR-release-2.5\ppocr\data\simple_dataset.py  怎么传入pillow生成的图像？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9298]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5  问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PaddleOCR-release-2.5\ppocr\data\simple_dataset.py  怎么传入pil生成的图像？

第105行左右，想修改，不知道怎么改成用pillow生成的图像
            if not os.path.exists(img_path):
                continue
            with open(data['img_path'], 'rb') as f:
                img = f.read()
                data['image'] = img
            data = transform(data, load_data_ops)

**Comment by huangjun12** [comment]
图像解码是在transform对应的op里面

**Comment by nissansz** [comment]
找到了DataSet
