### ISSUE TITLE
本地预测时内存一直增长（python cpu环境 关闭mkldnn和zero_copy_run v1.1中英文超轻量OCR模型 paddle2.0）

### ISSUE THREAD

**Issue by qypf** [PaddlePaddle/PaddleOCR#930]
部署的时候发现内存一直增长，一开始以为是自己代码改动和自己使用web框架的原因，排除后发现不是，于是直接使用paddleocr的源码进行测试，使用的参数都是默认配置，环境如题。使用的是predict_system.py文件，对于一个文件夹下的图片进行ocr。
    用memory_profiler工具进行内存检测，发现结果如下：
第一张图片
`Line#     Mem usage    Increment   Line Contents
================================================
    87 281.8516 MiB 281.8516 MiB       @profile(precision=4)
    88                                 def __call__(self, img):
    89 327.5078 MiB  45.6562 MiB           ori_im = img.copy()
    90 915.1875 MiB 587.6797 MiB           dt_boxes, elapse = self.text_detector(img)
    91 915.1875 MiB   0.0000 MiB           print("dt_boxes num : {}, elapse : {}".format(len(dt_boxes), elapse))
    92 915.1875 MiB   0.0000 MiB           if dt_boxes is None:
    93                                         return None, None
    94 915.1875 MiB   0.0000 MiB           img_crop_list = []
    95                             
    96 915.1914 MiB   0.0039 MiB           dt_boxes = sorted_boxes(dt_boxes)
    97                             
    98 924.6250 MiB   0.0000 MiB           for bno in range(len(dt_boxes)):
    99 924.6250 MiB   0.0000 MiB               tmp_box = copy.deepcopy(dt_boxes[bno])
   100 924.6250 MiB   4.1250 MiB               img_crop = self.get_rotate_crop_image(ori_im, tmp_box)
   101 924.6250 MiB   0.0000 MiB               img_crop_list.append(img_crop)
   102 924.6250 MiB   0.0000 MiB           if self.use_angle_cls:
   103                                         img_crop_list, angle_list, elapse = self.text_classifier(
   104                                             img_crop_list)
   105                                         print("cls num  : {}, elapse : {}".format(
   106                                             len(img_crop_list), elapse))
   107 1236.9023 MiB 312.2773 MiB           rec_res, elapse = self.text_recognizer(img_crop_list)
   108 1236.9023 MiB   0.0000 MiB           print("rec_res num  : {}, elapse : {}".format(len(rec_res), elapse))
   109                                     # self.print_draw_crop_rec_res(img_crop_list, rec_res)
   110 1236.9023 MiB   0.0000 MiB           return dt_boxes, rec_res`

**第二张图片**
   
Line #    Mem usage    Increment   Line Contents
================================================
    87 1295.0508 MiB 1295.0508 MiB       @profile(precision=4)
    88                                 def __call__(self, img):
    89 1301.1836 MiB   6.1328 MiB           ori_im = img.copy()
    **90 1348.2695 MiB  47.0859 MiB           dt_boxes, elapse = self.text_detector(img)**
    91 1348.2695 MiB   0.0000 MiB           print("dt_boxes num : {}, elapse : {}".format(len(dt_boxes), elapse))
    92 1348.2695 MiB   0.0000 MiB           if dt_boxes is None:
    93                                         return None, None
    94 1348.2695 MiB   0.0000 MiB           img_crop_list = []
    95                             
    96 1348.2695 MiB   0.0000 MiB           dt_boxes = sorted_boxes(dt_boxes)
    97                             
    98 1348.8125 MiB   0.0000 MiB           for bno in range(len(dt_boxes)):
    99 1348.7930 MiB   0.0000 MiB               tmp_box = copy.deepcopy(dt_boxes[bno])
   100 1348.8125 MiB   0.3281 MiB               img_crop = self.get_rotate_crop_image(ori_im, tmp_box)
   101 1348.8125 MiB   0.0000 MiB               img_crop_list.append(img_crop)
   102 1348.8125 MiB   0.0000 MiB           if self.use_angle_cls:
   103                                         img_crop_list, angle_list, elapse = self.text_classifier(
   104                                             img_crop_list)
   105                                         print("cls num  : {}, elapse : {}".format(
   106                                             len(img_crop_list), elapse))
   **107 1349.1367 MiB   0.3242 MiB           rec_res, elapse = self.text_recognizer(img_crop_list)**
   108 1349.1367 MiB   0.0000 MiB           print("rec_res num  : {}, elapse : {}".format(len(rec_res), elapse))
   109                                     # self.print_draw_crop_rec_res(img_crop_list, rec_res)
   110 1349.1367 MiB   0.0000 MiB           return dt_boxes, rec_res

第三张图片
Line #    Mem usage    Increment   Line Contents
================================================
    87 1225.2852 MiB 1225.2852 MiB       @profile(precision=4)
    88                                 def __call__(self, img):
    89 1250.2188 MiB  24.9336 MiB           ori_im = img.copy()
    **90 1309.7266 MiB  59.5078 MiB           dt_boxes, elapse = self.text_detector(img)**
    91 1309.7266 MiB   0.0000 MiB           print("dt_boxes num : {}, elapse : {}".format(len(dt_boxes), elapse))
    92 1309.7266 MiB   0.0000 MiB           if dt_boxes is None:
    93                                         return None, None
    94 1309.7266 MiB   0.0000 MiB           img_crop_list = []
    95                             
    96 1309.7266 MiB   0.0000 MiB           dt_boxes = sorted_boxes(dt_boxes)
    97                             
    98 1313.5547 MiB   0.0000 MiB           for bno in range(len(dt_boxes)):
    99 1312.7578 MiB   0.0000 MiB               tmp_box = copy.deepcopy(dt_boxes[bno])
   100 1313.5547 MiB   2.9688 MiB               img_crop = self.get_rotate_crop_image(ori_im, tmp_box)
   101 1313.5547 MiB   0.0000 MiB               img_crop_list.append(img_crop)
   102 1313.5547 MiB   0.0000 MiB           if self.use_angle_cls:
   103                                         img_crop_list, angle_list, elapse = self.text_classifier(
   104                                             img_crop_list)
   105                                         print("cls num  : {}, elapse : {}".format(
   106                                             len(img_crop_list), elapse))
   **107 1314.5781 MiB   1.0234 MiB           rec_res, elapse = self.text_recognizer(img_crop_list)**
   108 1314.5781 MiB   0.0000 MiB           print("rec_res num  : {}, elapse : {}".format(len(rec_res), elapse))
   109                                     # self.print_draw_crop_rec_res(img_crop_list, rec_res)
   110 1314.5781 MiB   0.0000 MiB           return dt_boxes, rec_res

    虽然中间也有内存回收，但是在多张图片的压力测试下仍然会内存增长，通过排查发现内存增长主要来自于self.predictor.run
以下是TextDetector的三次结果
第一张图片

Line #    Mem usage    Increment   Line Contents
================================================
   136 327.4922 MiB 327.4922 MiB       @profile(precision=4)
   137                                 def __call__(self, img):
   138 373.1484 MiB  45.6562 MiB           ori_im = img.copy()
   139 380.9648 MiB   7.8164 MiB           im, ratio_list = self.preprocess_op(img)
   140 380.9648 MiB   0.0000 MiB           if im is None:
   141                                         return None, 0
   142 380.9648 MiB   0.0000 MiB           im = im.copy()
   143 380.9648 MiB   0.0000 MiB           starttime = time.time()
   144 380.9648 MiB   0.0000 MiB           if self.use_zero_copy_run:
   145                                         self.input_tensor.copy_from_cpu(im)
   146                                         self.predictor.zero_copy_run()
   147                                     else:
   148 380.9727 MiB   0.0078 MiB               im = fluid.core.PaddleTensor(im)
   **149 964.3672 MiB 583.3945 MiB               self.predictor.run([im])**
   150 964.3672 MiB   0.0000 MiB           outputs = []
   151 966.8359 MiB   0.0000 MiB           for output_tensor in self.output_tensors:
   152 966.8359 MiB   2.4688 MiB               output = output_tensor.copy_to_cpu()
   153 966.8359 MiB   0.0000 MiB               outputs.append(output)
   154 966.8359 MiB   0.0000 MiB           outs_dict = {}
   155 966.8359 MiB   0.0000 MiB           if self.det_algorithm == "EAST":
   156                                         outs_dict['f_geo'] = outputs[0]
   157                                         outs_dict['f_score'] = outputs[1]
   158 966.8359 MiB   0.0000 MiB           elif self.det_algorithm == 'SAST':
   159                                         outs_dict['f_border'] = outputs[0]
   160                                         outs_dict['f_score'] = outputs[1]
   161                                         outs_dict['f_tco'] = outputs[2]
   162                                         outs_dict['f_tvo'] = outputs[3]
   163                                     else:
   164 966.8359 MiB   0.0000 MiB               outs_dict['maps'] = outputs[0]
   165                             
   166 970.6992 MiB   3.8633 MiB           dt_boxes_list = self.postprocess_op(outs_dict, [ratio_list])
   167 970.6992 MiB   0.0000 MiB           dt_boxes = dt_boxes_list[0]
   168 970.6992 MiB   0.0000 MiB           if self.det_algorithm == "SAST" and self.det_sast_polygon:
   169                                         dt_boxes = self.filter_tag_det_res_only_clip(dt_boxes, ori_im.shape)
   170                                     else:
   171 970.7148 MiB   0.0156 MiB               dt_boxes = self.filter_tag_det_res(dt_boxes, ori_im.shape)
   172 970.7148 MiB   0.0000 MiB           elapse = time.time() - starttime
   173 970.7148 MiB   0.0000 MiB           return dt_boxes, elapse

第二张图片

Line #    Mem usage    Increment   Line Contents
================================================
   136 1299.8125 MiB 1299.8125 MiB       @profile(precision=4)
   137                                 def __call__(self, img):
   138 1305.9492 MiB   6.1367 MiB           ori_im = img.copy()
   139 1309.5352 MiB   3.5859 MiB           im, ratio_list = self.preprocess_op(img)
   140 1309.5352 MiB   0.0000 MiB           if im is None:
   141                                         return None, 0
   142 1309.5312 MiB   0.0000 MiB           im = im.copy()
   143 1309.5312 MiB   0.0000 MiB           starttime = time.time()
   144 1309.5312 MiB   0.0000 MiB           if self.use_zero_copy_run:
   145                                         self.input_tensor.copy_from_cpu(im)
   146                                         self.predictor.zero_copy_run()
   147                                     else:
   148 1309.5352 MiB   0.0039 MiB               im = fluid.core.PaddleTensor(im)
   **149 1355.7539 MiB  46.2188 MiB               self.predictor.run([im])**
   150 1355.7539 MiB   0.0000 MiB           outputs = []
   151 1357.0469 MiB   0.0000 MiB           for output_tensor in self.output_tensors:
   152 1357.0469 MiB   1.2930 MiB               output = output_tensor.copy_to_cpu()
   153 1357.0469 MiB   0.0000 MiB               outputs.append(output)
   154 1357.0469 MiB   0.0000 MiB           outs_dict = {}
   155 1357.0469 MiB   0.0000 MiB           if self.det_algorithm == "EAST":
   156                                         outs_dict['f_geo'] = outputs[0]
   157                                         outs_dict['f_score'] = outputs[1]
   158 1357.0469 MiB   0.0000 MiB           elif self.det_algorithm == 'SAST':
   159                                         outs_dict['f_border'] = outputs[0]
   160                                         outs_dict['f_score'] = outputs[1]
   161                                         outs_dict['f_tco'] = outputs[2]
   162                                         outs_dict['f_tvo'] = outputs[3]
   163                                     else:
   164 1357.0469 MiB   0.0000 MiB               outs_dict['maps'] = outputs[0]
   165                             
   166 1358.0156 MiB   0.9688 MiB           dt_boxes_list = self.postprocess_op(outs_dict, [ratio_list])
   167 1358.0156 MiB   0.0000 MiB           dt_boxes = dt_boxes_list[0]
   168 1358.0156 MiB   0.0000 MiB           if self.det_algorithm == "SAST" and self.det_sast_polygon:
   169                                         dt_boxes = self.filter_tag_det_res_only_clip(dt_boxes, ori_im.shape)
   170                                     else:
   171 1358.0156 MiB   0.0000 MiB               dt_boxes = self.filter_tag_det_res(dt_boxes, ori_im.shape)
   172 1358.0156 MiB   0.0000 MiB           elapse = time.time() - starttime
   173 1358.0156 MiB   0.0000 MiB           return dt_boxes, elapse

第三张图片

Line #    Mem usage    Increment   Line Contents
================================================
   136 1250.4883 MiB 1250.4883 MiB       @profile(precision=4)
   137                                 def __call__(self, img):
   138 1275.4297 MiB  24.9414 MiB           ori_im = img.copy()
   139 1282.5547 MiB   7.1250 MiB           im, ratio_list = self.preprocess_op(img)
   140 1282.5547 MiB   0.0000 MiB           if im is None:
   141                                         return None, 0
   142 1282.5547 MiB   0.0000 MiB           im = im.copy()
   143 1282.5547 MiB   0.0000 MiB           starttime = time.time()
   144 1282.5547 MiB   0.0000 MiB           if self.use_zero_copy_run:
   145                                         self.input_tensor.copy_from_cpu(im)
   146                                         self.predictor.zero_copy_run()
   147                                     else:
   148 1282.5547 MiB   0.0000 MiB               im = fluid.core.PaddleTensor(im)
   **149 1339.7109 MiB  57.1562 MiB               self.predictor.run([im])**
   150 1339.7109 MiB   0.0000 MiB           outputs = []
   151 1342.0664 MiB   0.0000 MiB           for output_tensor in self.output_tensors:
   152 1342.0664 MiB   2.3555 MiB               output = output_tensor.copy_to_cpu()
   153 1342.0664 MiB   0.0000 MiB               outputs.append(output)
   154 1342.0664 MiB   0.0000 MiB           outs_dict = {}
   155 1342.0664 MiB   0.0000 MiB           if self.det_algorithm == "EAST":
   156                                         outs_dict['f_geo'] = outputs[0]
   157                                         outs_dict['f_score'] = outputs[1]
   158 1342.0664 MiB   0.0000 MiB           elif self.det_algorithm == 'SAST':
   159                                         outs_dict['f_border'] = outputs[0]
   160                                         outs_dict['f_score'] = outputs[1]
   161                                         outs_dict['f_tco'] = outputs[2]
   162                                         outs_dict['f_tvo'] = outputs[3]
   163                                     else:
   164 1342.0664 MiB   0.0000 MiB               outs_dict['maps'] = outputs[0]
   165                             
   166 1344.4297 MiB   2.3633 MiB           dt_boxes_list = self.postprocess_op(outs_dict, [ratio_list])
   167 1344.4297 MiB   0.0000 MiB           dt_boxes = dt_boxes_list[0]
   168 1344.4297 MiB   0.0000 MiB           if self.det_algorithm == "SAST" and self.det_sast_polygon:
   169                                         dt_boxes = self.filter_tag_det_res_only_clip(dt_boxes, ori_im.shape)
   170                                     else:
   171 1344.4297 MiB   0.0000 MiB               dt_boxes = self.filter_tag_det_res(dt_boxes, ori_im.shape)
   172 1344.4297 MiB   0.0000 MiB           elapse = time.time() - starttime
   173 1344.4297 MiB   0.0000 MiB           return dt_boxes, elapse
    请问这个问题怎么解决，还有有什么方法能够释放predictor的内存吗，每次运行predictor.run都会占用很多内存，而且没法释放，而self.predictor参数本身是不怎么占内存的，所以不太好改。
  github这个排版调了几次也调不好，不好意思，将就着看吧

**Comment by qypf** [comment]
另外，通过去掉 ori_im = img.copy()，或者将tools/infer/utility,py中注释掉的126行去掉注释，也就是使用config.enable_memory_optim()，可以一定程度上缓解内存的问题，但是似乎没有从本质上解决问题。
    我最关心的是怎么释放因为使用predictor.run而占用的内存，因为这个是paddlepaddle框架里封装好的函数，好像也不太好改

**Comment by LDOUBLEV** [comment]
内存增长的问题已经解决了，建议用paddle 2.0.0.b0版本的预测库

**Comment by qypf** [comment]
@LDOUBLEV 关键在于我用的就是paddle 2.0.0b0版本的预测库，所以发现这个问题依旧存在

**Comment by littletomatodonkey** [comment]
看你这个增长的幅度不大，是否是因为不同图像image shape不同造成的呢？是否可以测下500张图像，看下内存涨幅情况呢？

**Comment by chuzhifeng** [comment]
@qypf 哥们，请问你解决了这个内存一直增长的问题么，我也遇到了这种情况，试了几个版本都这样

**Comment by YAwei666** [comment]
请问解决了嘛，内存还是在涨

**Comment by MissPenguin** [comment]
内存泄漏问题已解，可以拉取最新代码试试哈，如果还有问题可以重新提issue，我们再继续跟进～
