### ISSUE TITLE
PP-Structure的表格训练的中文表格预训练模型是用哪些数据集训练的

### ISSUE THREAD

**Issue by hf62580** [PaddlePaddle/PaddleOCR#9300]
我想知道，PP-Structure的表格训练的中文表格预训练模型（即ch_ppstructure_mobile_v2.0_SLANet_train）是用哪些数据集训练的

**Comment by WenmuZhou** [comment]
生成数据+wtw公开数据

**Comment by hf62580** [comment]
收到，谢谢

**Comment by hf62580** [comment]
> 生成数据+wtw公开数据

请问有没有什么脚本可以把wtw数据集的格式转成表格训练的格式

**Comment by nissansz** [comment]
wtw数据集 标注转好了吗？
