### ISSUE TITLE
这个报错怎么解决？ PaddleOCR-release-2.5\ppocr\metrics\rec_metric.py", line 41, in __call__     for (pred, pred_conf), (target, _) in zip(preds, labels): ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9301]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

PaddleOCR-release-2.5\ppocr\metrics\rec_metric.py", line 41, in __call__
    for (pred, pred_conf), (target, _) in zip(preds, labels):
ValueError: too many values to unpack (expected 2)

**Comment by nissansz** [comment]
改成 这样可以运行，但不知道有没有问题
# for (pred, pred_conf), (target, _) in zip(preds, labels):
        for (pred, pred_conf, _), (target, _, _) in zip(preds, labels):

**Comment by huangjun12** [comment]
调试看看preds和labels包含的元素信息吧

**Comment by nissansz** [comment]
之前改了paddle2.5的代码，重新覆盖一遍应该就没错了
