### ISSUE TITLE
OCR文本检测的细节

### ISSUE THREAD

**Issue by 553548793** [PaddlePaddle/PaddleOCR#9303]
OCR检测完的box有按照从上到下的顺序排列吗，还是说是随机的呢。打算检测完后面加个识别，所以想知道一下是否有顺序

**Comment by MissPenguin** [comment]
从上到下、从左到右排序的，具体实现在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/d8d76d59c90d922782a4c812f9c720ac77877d5a/tools/infer/predict_system.py#L79
