### ISSUE TITLE
为什么crnn英中日的混合模型，英文效果反而比中文，日文差？英文图片要怎样准备才能改善？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9305]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
为什么crnn英中日的混合模型，英文效果反而比中文，日文差？英文图片要怎样准备才能改善？

**Comment by MissPenguin** [comment]
如果纯英文场景，可以用PP-OCR英文模型或者在此基础上微调；如果是中英日混合的场景，可以看下是不是训练数据不均衡，按需补充训练数据或调整采样策略

**Comment by nissansz** [comment]
发现普通英文还是可以识别出来，可能是难识别的字符易出错，再加一些易出错字数据训练试试

![image](https://user-images.githubusercontent.com/41010669/223039324-527eb481-92f7-4238-8e43-f936882f5527.png)
[('見つけたぞこのー族。', 0.8956415057182312)]
![image](https://user-images.githubusercontent.com/41010669/223039338-6c620ff9-d786-4e65-b645-7eb01dcc4c8e.png)
[('ほどこしてgulped。孫PUSAT:', 0.9999451637268066)]
