### ISSUE TITLE
关于对空格支持的疑问

### ISSUE THREAD

**Issue by hbulaoma** [PaddlePaddle/PaddleOCR#931]
我看文档上说，要支持空格，需要use_space_char设置成true，那这时ppocr_keys_v1.txt中要包含空格这个字符吗？还是说即使use_space_char=false，但只要字典ppocr_keys_v1.txt中有空格，训练的模型也可以支持空格？训练样本已经包含带空格的数据。

**Comment by tink2123** [comment]
是的，只要字典中本身带空格，就可以支持空格。设置 `use_space_char=True`, 主要针对没有空格的字典，在训练时会在末尾添加一个空格类别。

**Comment by hbulaoma** [comment]
> 是的，只要字典中本身带空格，就可以支持空格。设置 `use_space_char=True`, 主要针对没有空格的字典，在训练时会在末尾添加一个空格类别。

了解了，谢谢啦！

**Comment by tink2123** [comment]
不客气～
