### ISSUE TITLE
使用en_PP-OCRv3_xx优化后的模型在android手机上内存溢出

### ISSUE THREAD

**Issue by DJSHICHAOREN** [PaddlePaddle/PaddleOCR#9310]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10 android 11
- 版本号/Version：
          version of opt:v2.12
          version of current Paddle-Lite:v2.6.1
- 问题相关组件/Related components：
- 使用的模型：
![image](https://user-images.githubusercontent.com/29346132/222976064-1a7a9c88-2aea-4e37-ae7f-151d56cb75f1.png)

通过脚本转换为paddlelite模型
![image](https://user-images.githubusercontent.com/29346132/222976100-6bd34423-7477-47dc-808d-c8e4452e960c.png)

- 运行指令/Command Code：
![image](https://user-images.githubusercontent.com/29346132/222975993-6320c874-9b79-49c4-9426-2796e4ac9ea1.png)

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/29346132/222976014-5098965b-3f9e-4d8d-8721-a2b45e5d11c4.png)

**Comment by DJSHICHAOREN** [comment]
使用的app就是demo app，用demo中的模型跑是正常的
![6bca88f011a7bc9665fbc88a90d1385](https://user-images.githubusercontent.com/29346132/222976282-464d0d51-50cc-41b0-bcb4-6801b56e2382.jpg)

**Comment by LDOUBLEV** [comment]
1. 只运行检测模型看下是否有问题，排查问题出在检测还是识别模型上
2. 更换为英文模型后，识别模型的字典也需要修改，通过Label Path指定
3. 参考这里的步骤将inference model转成nb模型试试，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/lite/readme_ch.md#21-%E6%A8%A1%E5%9E%8B%E4%BC%98%E5%8C%96
