### ISSUE TITLE
ModuleNotFoundError: No module named 'Polygon'

### ISSUE THREAD

**Issue by kainer80** [PaddlePaddle/PaddleOCR#9311]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：xp
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6&2.3
- 运行指令/Command Code：执行训练 python .\tools\train.py -c .\configs\en_PP-OCRv3_rec_fct.yml
- 完整报错/Complete Error Message：
(base) PS E:\PaddleOCR-release-2.6> python .\tools\train.py -c .\configs\en_PP-OCRv3_rec_fct.yml
C:\Users\Lenovo\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
C:\Users\Lenovo\anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
C:\Users\Lenovo\anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Traceback (most recent call last):
  File ".\tools\train.py", line 30, in <module>
    from ppocr.data import build_dataloader
  File "E:\PaddleOCR-release-2.6\ppocr\data\__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "E:\PaddleOCR-release-2.6\ppocr\data\imaug\__init__.py", line 47, in <module>
    from .ct_process import *
  File "E:\PaddleOCR-release-2.6\ppocr\data\imaug\ct_process.py", line 22, in <module>
    import Polygon as plg
ModuleNotFoundError: No module named 'Polygon'

系统已经安装有polygon
ply                                3.11
polygon                            1.1.0
premailer                          3.10.0
prometheus-client                  0.10.1
prompt-toolkit                     3.0.17
protobuf                           3.20.0
psutil                             5.8.0

**Comment by sisrfeng** [comment]
是没用pip install -r requirement.txt吗?
https://github.com/PaddlePaddle/PaddleOCR/pull/9097/files
