### ISSUE TITLE
如何fine-tune自己的版面分析数据集

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9312]
请问在fine-tune自己的中文版面分析数据集时 也要使用picodet_lcnet_x1_0_layout.yml这个配置文件嘛 还是需要调用picodet_lcnet_x1_0_fgd_layout_cdla.pdparams这个预训练模型  能不能给出一个具体的fine-tune实例 有关训练自己中文版面分析数据集的

**Comment by vikhil0609** [comment]
Hii @AIwang666 ,
I want to know have you trained the custom model for fine tuning the english data set?

**Comment by Fissionalist** [comment]
我也有相同的问题，因为版面分析训练默认下载PP-PicoDet预训练模型，我想指定其他模型，就在命令行参数设置weights为另外的预训练模型路径，但是没用。
是不是要把`picodet_lcnet_x1_0_layout.yml`和`configs/picodet/legacy_model/_base_/picodet_esnet.yml`里的`pretrain_weights`值都改成自己希望的预训练模型路径？明天试试。
