### ISSUE TITLE
Adding table recognition model on pdserving

### ISSUE THREAD

**Issue by Tanmay98** [PaddlePaddle/PaddleOCR#9317]
Hi, The quickstart deployment readme shows how to deploy paddleocr detection and recognition models on pdserving. But is it possible to deploy other models for table recognition, SER, layout analysis models too in the same way?

**Comment by LDOUBLEV** [comment]
It is not supported now. 
 And it is possible to deploy table models on pdserving with some code development work.

**Comment by Tanmay98** [comment]
So should I use hub serving to host layout analysis, OCR, Table, and KIE models? My purpose is to evaluate lots of documents via adding concurrency .

**Comment by LDOUBLEV** [comment]
hubserving is OK for you
