### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by nckf** [PaddlePaddle/PaddleOCR#932]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/docker/hubserving/README_cn.md
按照此按理创建的Docker容器
使用的ocr_system模块   服务器端模型  
运行tools/test_hubserving.py 跑/doc/imgs下的图片
容量只增不减
尝试过调大服务器内存无果

**Comment by Steffy-zxf** [comment]
你好！该问题为已知问题，请参考 https://github.com/PaddlePaddle/PaddleHub/issues/682
