### ISSUE TITLE
训练CDLA中文版面数据集遇到以下错误

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9320]
![ODQH`X _4A$Y}V}KH@EO`J](https://user-images.githubusercontent.com/56247915/223050869-16908e29-1f7f-449b-b976-2ee312a1ef12.png)
q请问这个出错的py文件在哪里呀 应该如何修改

**Comment by an1018** [comment]
字典修改了吗

**Comment by AIwang666** [comment]
> 字典修改了吗

请问字典是在配置文件里吗

**Comment by AIwang666** [comment]
> 

numclass已经修改了
