### ISSUE TITLE
训练模型没有反应

### ISSUE THREAD

**Issue by yhj1427102168** [PaddlePaddle/PaddleOCR#9321]
我在window10上面训练paddleocr的模型，使用的是两阶段训练[configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml]，但是执行到[2023/03/06 16:38:35] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations  ，会停留一段时间，然后进程就结束了，也没有报错，请问下这是什么原因呢？

**Comment by LDOUBLEV** [comment]
你的数据量有多少？看下output目录下有没有输出结果

**Comment by yhj1427102168** [comment]
> 

数据量有8000，ouput下面只是生成了config.yml和日志文件

**Comment by LDOUBLEV** [comment]
可能是数据太少
把epoch调大一些，eval_batch_step: [0, 2000] 设置为100(每迭代100次评估一次)试试

**Comment by yhj1427102168** [comment]
现在是将character_dict_path 换成了ppocr/utils/dict/chinese_cht_dict.txt 中文的，不知道是不是因为中文的比较多，然后output_channel就比较大，导致运行到开始训练的时候直接进程就结束了，请问有什么方法解决吗，或者可以改chinese_cht_dict.txt文件吗？

**Comment by lipeng1109** [comment]
我的也是同样的问题，调小batch解决了: 注意batch_size_per_card是每张卡的batch，建议从4开始，逐步调大确定合适的batch_size
