### ISSUE TITLE
kie中vi_layoutxlm做实体抽取时数量的限制

### ISSUE THREAD

**Issue by wangtiehu** [PaddlePaddle/PaddleOCR#9323]
您好！我想使用vi_layoutxlm做实体抽取，发现文字比较多的图片后面预测不到，我修改了配置文件的max_seq_len参数由512到1024，训练时报错，请问怎么处理一张图片实体较多的情况呢

**Comment by azhaoid** [comment]
大佬？这个问题解决了吗？

**Comment by ariefwijaya** [comment]
Any update on this issue?

**Comment by tran601** [comment]
site-packages/paddlenlp/transformers/layoutxlm/modeling.py
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/87564928/b2e770ba-9a9d-40e0-aa52-d2ac02f09814)

**Comment by UserWangZz** [comment]
Thanks for discuss.
