### ISSUE TITLE
关于小角度图片倾斜识别错误问题

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#9324]
当我的图片稍微倾斜一点点，paddleocr识别会存在错行的情况，paddleocrv3中有没有参数调节阈值，来防止错行解析的情况

**Comment by LDOUBLEV** [comment]
错行是指？发一个badcase看下

**Comment by tianchiguaixia** [comment]
![image](https://user-images.githubusercontent.com/29837553/223300852-20528237-0245-4a6e-a37d-045647762be3.png)
举个例子：按道理ocr应该输出Qusetion/repetitions:159/0 30
但是现实是：Qusetion/repetitions:159/0 MS [dB]:17.3
就是因为稍微倾斜导致错开行了

**Comment by LDOUBLEV** [comment]
你这个问题是检测框排序问题，没有参数可以调节
建议针对你这个场景重新对检测框排序

**Comment by xunfeng2zkj** [comment]
> 你这个问题是检测框排序问题，没有参数可以调节 建议针对你这个场景重新对检测框排序

有些表格没有线，就不好对表格进行矫正，不然矫正后效果应该会好点

**Comment by tianchiguaixia** [comment]
https://www.textin.com/experience/text_recognize_3d1
