### ISSUE TITLE
经常看到训练过程中会有多余字符出现，这种是什么现象？继续训练一般都能解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9326]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

- ねぇねぇ ごんちゃん 西中の誰かと会ってないの?
+ ねぇねえぇ ごんちゃん 西中の誰かと会ってないの?
? 　　　＋

**Comment by LDOUBLEV** [comment]
数据量足够的话，继续训练能解决
如果出现多余字符的场景是比较相似，或者固定一些字符出现重复，建议针对这些场景做一些数据增强

**Comment by nissansz** [comment]
中文字体2万个字符，日文16000个字符。2种字体训练。
要准备多少数据？

**Comment by LDOUBLEV** [comment]
> 中文字体2万个字符，日文16000个字符。2种字体训练。
> 要准备多少数据？

越多越好，500W的数据都嫌少

**Comment by nissansz** [comment]
易错字加到5%差不多了
