### ISSUE TITLE
竖行文字识别不出来

### ISSUE THREAD

**Issue by Smarter1214** [PaddlePaddle/PaddleOCR#9327]
![image](https://user-images.githubusercontent.com/78294109/223145432-2a3a74cb-1f64-4b60-9a78-fc1721eded3f.png)
竖行文字识别不出来，相关的文本框也有对应标注，但在excel中不能显示出来竖行文字
配置如下：
数据集选用的是tablegeneration制作的包含竖行的数据集；
![image](https://user-images.githubusercontent.com/78294109/223168798-51af8766-aab5-4bdf-ac57-8b07d61d6c5e.png)
预训练模型：下载中文表格识别模型预训练模型ch_ppstructure_mobile_v2.0_SLANet_train.tar
预测命令：
![image](https://user-images.githubusercontent.com/78294109/223168937-d370ee9c-76d6-46bc-9673-7308d9df8ef4.png)

尝试：
我们现在已经尝试进行大量竖行文字表格的模型训练，但效果方面基本没有变化，在用模型进行竖行文字识别时，依旧是无法进行

**Comment by kerry-weic** [comment]
@Smarter1214  请问这个问题有解决嘛，也碰到相同的问题了呢
