### ISSUE TITLE
数据标注问题 表格识别模型训练自有数据集

### ISSUE THREAD

**Issue by ASLYY** [PaddlePaddle/PaddleOCR#9329]
如何对自有数据集进行标注生成 表格识别模型所需要的数据集格式.jsonl呢？
期待您的回复！不甚感激

**Comment by andyjpaddle** [comment]
可以使用PPOCRLabel https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md

**Comment by ASLYY** [comment]
感谢您对上一个问题的解答！
我已经开始使用PPOCRLabel对表格进行标注，但是总是遇到这样的问题： 点击表格识别之后选择“文件”-“导出表格标注” 程序会自动退出并报错：NameError: name 'null' is not defined
![image](https://user-images.githubusercontent.com/87521581/223900129-8d80b9d9-2d82-4f1d-84b9-795f66600fc7.png)
 请问这是什么原因引起的呢 如何去解决呢？

> 可以使用PPOCRLabel https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md

**Comment by pinkman199810** [comment]
添加2472行
![image](https://user-images.githubusercontent.com/65639657/231042201-9a7df6a3-6c3d-4d26-a9f9-5ac618dba77b.png)
