### ISSUE TITLE
日文文字识别结果是乱码

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleOCR#933]
大佬，您好。
我运行以下的命令，预测结果是乱码。
----------------------------------------------------------------------------------------------------------------------
 run tools/infer/predict_system.py --image_dir="./doc/imgs/" --det_model_dir="./inference/ch_ppocr_mobile_v1.1_det_infer/" --rec_model_dir="./inference/japan_ppocr_mobile_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer" --use_angle_cls=True --use_space_char=False --use_gpu=False
----------------------------------------------------------------------------------------------------------------------
![japan_2](https://user-images.githubusercontent.com/51820927/95968496-76e3b200-0e48-11eb-84a4-39bb6634c77e.jpg)
![123](https://user-images.githubusercontent.com/51820927/95968868-f3769080-0e48-11eb-8976-86ae90a0e368.png)

**Comment by LDOUBLEV** [comment]
默认字典没有替换为 日文字典 吧

**Comment by terrancraft** [comment]
> 默认字典没有替换为 日文字典 吧

是的，请问替换位置在哪儿

**Comment by terrancraft** [comment]
> 默认字典没有替换为 日文字典 吧

我算是找到了 ，谢谢。我先去试一下
