### ISSUE TITLE
进行训练的时候，INFO只提示save model in ./output/ch_PP-OCR_v3_det/latest

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [PaddlePaddle/PaddleOCR#9330]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 
- 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/53245262/223318275-130f6aca-09b8-42b8-9da5-c0109024d80a.png)
如图所示

**Comment by andyjpaddle** [comment]
训练数据太少了，log中显示的每一个epoch只有1个iter，但是每400iter评估一次，需要增加训练数据，或者调小评估间隔

**Comment by HanChinese-LIURUI** [comment]
了解
