### ISSUE TITLE
在线Api 返回结果不全 https://www.paddlepaddle.org.cn/paddlehub-api/image_classification/chinese_ocr_db_crnn_mobile

### ISSUE THREAD

**Issue by xyyipiantian** [PaddlePaddle/PaddleOCR#9331]
### 图片地址 
https://www.oocl.com/eng/ourservices/serviceroutes/PublishingImages/MAF/MAF_BME_MWAX.jpg

返回结果中 缺少
![image](https://user-images.githubusercontent.com/48873295/223328306-4aab0ffb-a7fa-423c-a12a-786b2bdc3139.png)

结果Json
![image](https://user-images.githubusercontent.com/48873295/223328517-df98dc8e-4728-4690-8d4b-1b27964b7f1f.png)

**Comment by xyyipiantian** [comment]
有参数 可以控制 返回全部识别的结果嘛

**Comment by andyjpaddle** [comment]
可以试试python推理 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/inference_ppocr.md#4-%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E6%96%B9%E5%90%91%E5%88%86%E7%B1%BB%E5%92%8C%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E4%B8%B2%E8%81%94%E6%8E%A8%E7%90%86
