### ISSUE TITLE
模型加入STN网络，怎么可视化矫正后的效果图呀

### ISSUE THREAD

**Issue by fishstarr** [PaddlePaddle/PaddleOCR#9332]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
可以在这里取出输出 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/modeling/architectures/base_model.py#L84

**Comment by fishstarr** [comment]
> 可以在这里取出输出 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/modeling/architectures/base_model.py#L84

具体怎么取出呢，我想要得到单张图片的效果，多谢！

**Comment by zhs1316** [comment]
同问，请问您的问题现在解决了吗？
