### ISSUE TITLE
请问修改版面分析配置文件的学习率应该如何修改

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9338]
请问修改配置文件的学习率是在下图optimzer.yml文件修改吗

![@40E){E3W VMXF8ZS_E00)G](https://user-images.githubusercontent.com/56247915/223372462-9fefc3e1-6958-4413-b87e-df4bd29d736d.png)

![LCOR0 B~5 B{MS6313A6UPM](https://user-images.githubusercontent.com/56247915/223372485-fd26f15a-eaaa-4ce9-9822-073f9abe77dc.png)
能不能告知一下具体的学习率修改文件

**Comment by andyjpaddle** [comment]
应该是这个，可以看一下paddledetection里面相关的文档
