### ISSUE TITLE
中英文模型空格问题

### ISSUE THREAD

**Issue by DJSHICHAOREN** [PaddlePaddle/PaddleOCR#9339]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我发现中文模型和英文模型的字典里面都没有空格
请问PaddleOCR中预训练的模型都不支持空格吗？
![image](https://user-images.githubusercontent.com/29346132/223373975-023338cc-d4cd-4311-9b80-7291a332e3ec.png)

**Comment by andyjpaddle** [comment]
支持的，根据配置文件中的use_space_char来指定是否使用空格

**Comment by DJSHICHAOREN** [comment]
> 支持的，根据配置文件中的use_space_char来指定是否使用空格

请问这个是在训练模型的配置文件里吗？
如果我想要一个可以识别空格和英文的模型，有训练好的模型库吗？

**Comment by andyjpaddle** [comment]
参数是在配置文件中，官方给的模型就是支持空格识别的
