### ISSUE TITLE
运行predict_system.py时出现问题

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/PaddleOCR#934]
运行predict_system.py时显示

  File "<frozen importlib._bootstrap_external>", line 978, in _get_parent_path

KeyError: 'ppocr.data'

应该时ppocr文件夹下文件导入失败，但from ppocr.utils.utility import get_image_file_list, check_and_read_gif就没有问题
请问时什么原因

**Comment by upenggod** [comment]
from ppocr.data.det.sast_process import SASTProcessTest出先上面的错误
如果把data文件夹改成datadata，运行from ppocr.datadata.det.sast_process import SASTProcessTest就没问题

**Comment by LDOUBLEV** [comment]
在PaddleOCR目录下运行predict_system.py
```
cd PaddleOCR
python  tools/infer/predict_system.py  
```
