### ISSUE TITLE
Could NOT find PY_numpy (missing: PY_NUMPY) 

### ISSUE THREAD

**Issue by hujimei** [PaddlePaddle/PaddleOCR#9342]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux kylin1 4.19.80 #6 SMP Mon Nov 4 10:05:29 EST 2019 aarch64 aarch64 aarch64 GNU/Linux
- 版本号/Version：Paddle inference v1.8
-   PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- cmake -DPY_VERSION=3 \
        -DWITH_TESTING=OFF \
        -DWITH_MKL=ON \
        -DWITH_GPU=OFF \
        -DON_INFER=ON \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        ..
- 完整报错/Complete Error Message：
-- Could NOT find PY_numpy (missing: PY_NUMPY) 
CMake Error at cmake/python_module.cmake:27 (message):
  python module numpy is not found
Call Stack (most recent call first):
  cmake/external/python.cmake:69 (find_python_module)
  cmake/third_party.cmake:216 (include)
  CMakeLists.txt:156 (include)

-- Configuring incomplete, errors occurred!

**Comment by andyjpaddle** [comment]
could you describe your question in more detail?

**Comment by hujimei** [comment]
> could you describe your question in more detail?

#include <pmmintrin.h>
int main()
{
    __m128d a = _mm_set1_pd(6.28);
    __m128d b = _mm_set1_pd(3.14);
    __m128d result = _mm_addsub_pd(a, b);
    result = _mm_movedup_pd(result);
    return 0;
}
Performing C++ SOURCE FILE Test AVX_FOUND failed with the following compile output:
Change Dir: /root/Paddle/build_cpu/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_9801f/fast && /usr/bin/make  -f CMakeFiles/cmTC_9801f.dir/build.make CMakeFiles/cmTC_9801f.dir/build
make[1]: Entering directory '/root/Paddle/build_cpu/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_9801f.dir/src.cxx.o
/usr/local/bin/c++ -DAVX_FOUND  -Wno-error=deprecated-declarations -Wno-deprecated-declarations -mavx -o CMakeFiles/cmTC_9801f.dir/src.cxx.o -c /root/Paddle/build_cpu/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command-line option ‘-mavx’
CMakeFiles/cmTC_9801f.dir/build.make:77: recipe for target 'CMakeFiles/cmTC_9801f.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_9801f.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/root/Paddle/build_cpu/CMakeFiles/CMakeTmp'
Makefile:127: recipe for target 'cmTC_9801f/fast' failed
make: *** [cmTC_9801f/fast] Error 2


...and run output:

Return value: 1
Source file was:
这是CMakeError.log里面的内容，您看看这个是否有用？

**Comment by andyjpaddle** [comment]
还是不太清楚你的具体问题，你是在运行ocr教程的哪一步报的错？

**Comment by hujimei** [comment]
> 



> 



> 还是不太清楚你的具体问题，你是在运行ocr教程的哪一步报的错？

就是在对Paddle Inference v1.8版本进行源码编译的时候，在创建并进入build目录后，执行cmake指令cmake -DPY_VERSION=3 \
        -DWITH_TESTING=OFF \
        -DWITH_MKL=ON \
        -DWITH_GPU=OFF \
        -DON_INFER=ON \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        ..  的时候报这个错误：-- Could NOT find PY_numpy (missing: PY_NUMPY)
CMake Error at cmake/python_module.cmake:27 (message):
python module numpy is not found
Call Stack (most recent call first):
cmake/external/python.cmake:69 (find_python_module)
cmake/third_party.cmake:216 (include)
CMakeLists.txt:156 (include)
-- Configuring incomplete, errors occurred!

**Comment by andyjpaddle** [comment]
这个到paddleinference下面进行提问吧，这边主要是paddleocr相关的问题

**Comment by hujimei** [comment]
> 这个到paddleinference下面进行提问吧，这边主要是paddleocr相关的问题

好的好的  谢谢了
