### ISSUE TITLE
训练图文字间隔大小对模型没影响？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9343]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练图文字间隔大小对模型没影响？

**Comment by tink2123** [comment]
抱歉 没明白您的意思，标注信息和图片内容一致即可

**Comment by nissansz** [comment]
比如，2个字符之间，相隔1-10随机像素

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
