### ISSUE TITLE
训练时显存问题和pretrained参数问题

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [PaddlePaddle/PaddleOCR#9344]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/53245262/223613549-9294be57-bb8c-4954-8626-c59b8806f5d9.png)

1、训练时，我自己的图像只有40张，但是为什么我的batch_size_per_card参数只能设置到6，就会把显存占满？（我的显卡显存为12GB）
我使用的pretrained_model:ch_PP-OCRv3_det_distill_train\best_accuracy
使用的配置文件为：ch_PP-OCRv2_det_cml.yml
2、配置文件中Architecture:-》pretrained:参数是什么意思，训练时是否需要填写 

3、使用检测模型转inference 模型后出现三个文件夹，我应该使用那个文件夹中的模型
![image](https://user-images.githubusercontent.com/53245262/223616632-8a8f0672-2473-4198-bcc5-6db11f2761d4.png)

**Comment by tink2123** [comment]
1. ch_PP-OCRv2_det_cml.yml 这是检测的蒸馏模型，模型自身参数量就比较大，占用显存较多是正常的。
2. 是预训练权重的意思，如果需要加载预训练的话要填写
3. 都可以使用，Teacher模型精度高但推理速度慢，V3使用的是Student模型

**Comment by HanChinese-LIURUI** [comment]
> 1. ch_PP-OCRv2_det_cml.yml 这是检测的蒸馏模型，模型自身参数量就比较大，占用显存较多是正常的。
> 2. 是预训练权重的意思，如果需要加载预训练的话要填写
> 3. 都可以使用，Teacher模型精度高但推理速度慢，V3使用的是Student模型

你好，关于预训练权重您的意思是，pretrained_model这个参数填写了是需要填写pretrained的吗？
这个权重我应该怎么填写呢

**Comment by HanChinese-LIURUI** [comment]
> 1. ch_PP-OCRv2_det_cml.yml 这是检测的蒸馏模型，模型自身参数量就比较大，占用显存较多是正常的。
> 2. 是预训练权重的意思，如果需要加载预训练的话要填写
> 3. 都可以使用，Teacher模型精度高但推理速度慢，V3使用的是Student模型

你好，关于预训练权重您的意思是，pretrained_model这个参数填写了是需要填写pretrained的吗？
这个权重我应该怎么填写呢
