### ISSUE TITLE
不同平台文字检测推理速度不一致

### ISSUE THREAD

**Issue by boreas-l** [PaddlePaddle/PaddleOCR#9346]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

同样的官方模型权重，同样的代码，同样的测试图像，在笔记本windows下的pycharm中运行的时候，文字检测的推理时长为408ms（显示内容：dt_boxes num: 7, elapse: 0.408906...）。但是到linux服务器进行推理的时候，文字检测的推理时长就变慢了很多，来到了5s多（显示内容：dt_boxes_num: 7, elapse: 5.57601094...）。其中，配置信息里，use_gpu都为true。
请问，造成推理时长差异这么多的可能原因有什么吖？谢谢

**Comment by tink2123** [comment]
服务器上可能有其他程序占用gpu

**Comment by boreas-l** [comment]
> 

没有呢，我确认了gpu占用以及后台的运行进程。没有发现什么异常。然后我又确认了一遍，把同一份代码压缩传进去测试，然后显存完全没有占用的情况下，文字推理的时长还是2s多
