### ISSUE TITLE
paddleocr按照版式解析

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleOCR#9347]
就是paddleocr识别的是一个个文本框和对应的文本。我如何合并这些文本框，可以满足解析的文本布局和图片上布局大致一致呢。

例如，我如何在txt文件里面，使用文本体现右边的结构呢
![image](https://user-images.githubusercontent.com/29837553/223646867-8ebd3d7f-ed66-4a49-9ba3-1b2f239449a7.png)

**Comment by tink2123** [comment]
可以试用一下版面恢复功能：https://github.com/PaddlePaddle/PaddleOCR/blob/6660e3b4955481364b26f00d7c2310e043c5ca64/ppstructure/docs/quickstart.md#216-%E7%89%88%E9%9D%A2%E6%81%A2%E5%A4%8D
