### ISSUE TITLE
SER 预测结果在图片后半常出现识别丢失的情况

### ISSUE THREAD

**Issue by huiyaoren** [PaddlePaddle/PaddleOCR#9348]
- 系统环境/System Environment：
Windows 10 21H2
Python 3.9.2
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
PaddleOCR release-2.6
- 运行指令/Command Code：
*export_model*
```python39 E:\Project\PaddleOCR\tools/export_model.py -c ./ser_vi_layoutxlm_xfund_zh_ext/config.yml -o Architecture.Backbone.checkpoints=./ser_vi_layoutxlm_xfund_zh_ext/best_accuracy Global.save_inference_dir=./ser_vi_layoutxlm_xfund_zh_ext/inference/best_accuracy```
*predict_kie_token_ser*
```python39 E:\Project\PaddleOCR\ppstructure\kie\predict_kie_token_ser.py  --kie_algorithm=LayoutXLM  --ser_model_dir=./   --image_dir="C:\Users\Administrator\Pictures\ocr\eval"   --ser_dict_path=./class_list.txt   --vis_font_path=../doc/fonts/simfang.ttf  --ocr_order_method="tb-yx" --det_model_dir="../ch_db_res18.0.9881778281183633"```

- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/13791901/223659671-63aeb385-5fb7-421a-92d5-b8cdbec258cb.png)

*config.yaml*

```
Global:
  use_gpu: True
  epoch_num: &epoch_num 200
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: F:\deep\Drill hole histogram\9.train_ser_ext\ser_vi_layoutxlm_xfund_zh_ext
  save_epoch_step: 200
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
  # if you want to predict using the groundtruth ocr info,
  # you can use the following config
  # infer_img: train_data/XFUND/zh_val/val.json
  # infer_mode: False

  save_res_path: ./output/ser/xfund_zh/res
  kie_rec_model_dir: 
  kie_det_model_dir:
#  checkpoints: F:\deep\Drill hole histogram\9.train_ser_ext\ser_vi_layoutxlm_xfund_zh_ext\latest

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForSer
    pretrained: True
    checkpoints:
    # one of base or vi
    mode: vi
    num_classes: &num_classes 49

Loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: *num_classes
  key: "backbone_out"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Linear
    learning_rate: 0.000025
    epochs: *epoch_num
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: &class_path F:\deep\Drill hole histogram\9.train_ser_ext\class_list.txt

Metric:
  name: VQASerTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: F:\deep\Drill hole histogram
    label_file_list: 
      - F:\deep\Drill hole histogram\9.train_ser_ext\train_label.txt
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: &use_textline_bbox_info True
          # one of [None, "tb-yx"]
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 12

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: F:\deep\Drill hole histogram
    label_file_list:
    - F:\deep\Drill hole histogram\9.train_ser_ext\test_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4
```yaml

**Comment by huiyaoren** [comment]
*det 预测结果*
![image](https://user-images.githubusercontent.com/13791901/223662681-9af2f8d8-7af1-404d-925f-167e8f375382.png)

翻了一下历史 issue 应该是同一个问题 我们目前有相关的解决办法么
https://github.com/PaddlePaddle/PaddleOCR/issues/8009
https://github.com/PaddlePaddle/PaddleOCR/issues/7359
https://github.com/PaddlePaddle/PaddleOCR/issues/8945
https://github.com/PaddlePaddle/PaddleOCR/issues/8943
https://github.com/PaddlePaddle/PaddleOCR/issues/8955

**Comment by piarosebelledelapaz** [comment]
hello, i am also encountering the same problem. were you able to figure out the issue and how to solve it?

**Comment by eunij-peanut** [comment]
> * 系统环境/System Environment：
>   Windows 10 21H2
>   Python 3.9.2
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
>   PaddleOCR release-2.6
> * 运行指令/Command Code：
>   _export_model_
>   `python39 E:\Project\PaddleOCR\tools/export_model.py -c ./ser_vi_layoutxlm_xfund_zh_ext/config.yml -o Architecture.Backbone.checkpoints=./ser_vi_layoutxlm_xfund_zh_ext/best_accuracy Global.save_inference_dir=./ser_vi_layoutxlm_xfund_zh_ext/inference/best_accuracy`
>   _predict_kie_token_ser_
>   `python39 E:\Project\PaddleOCR\ppstructure\kie\predict_kie_token_ser.py  --kie_algorithm=LayoutXLM  --ser_model_dir=./   --image_dir="C:\Users\Administrator\Pictures\ocr\eval"   --ser_dict_path=./class_list.txt   --vis_font_path=../doc/fonts/simfang.ttf  --ocr_order_method="tb-yx" --det_model_dir="../ch_db_res18.0.9881778281183633"`
> * 完整报错/Complete Error Message：
>   ![image](https://user-images.githubusercontent.com/13791901/223659671-63aeb385-5fb7-421a-92d5-b8cdbec258cb.png)
> 
> _config.yaml_
> 
> ```
> Global:
>   use_gpu: True
>   epoch_num: &epoch_num 200
>   log_smooth_window: 10
>   print_batch_step: 10
>   save_model_dir: F:\deep\Drill hole histogram\9.train_ser_ext\ser_vi_layoutxlm_xfund_zh_ext
>   save_epoch_step: 200
>   # evaluation is run every 10 iterations after the 0th iteration
>   eval_batch_step: [ 0, 19 ]
>   cal_metric_during_train: False
>   save_inference_dir:
>   use_visualdl: False
>   seed: 2022
>   infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
>   # if you want to predict using the groundtruth ocr info,
>   # you can use the following config
>   # infer_img: train_data/XFUND/zh_val/val.json
>   # infer_mode: False
> 
>   save_res_path: ./output/ser/xfund_zh/res
>   kie_rec_model_dir: 
>   kie_det_model_dir:
> #  checkpoints: F:\deep\Drill hole histogram\9.train_ser_ext\ser_vi_layoutxlm_xfund_zh_ext\latest
> 
> Architecture:
>   model_type: kie
>   algorithm: &algorithm "LayoutXLM"
>   Transform:
>   Backbone:
>     name: LayoutXLMForSer
>     pretrained: True
>     checkpoints:
>     # one of base or vi
>     mode: vi
>     num_classes: &num_classes 49
> 
> Loss:
>   name: VQASerTokenLayoutLMLoss
>   num_classes: *num_classes
>   key: "backbone_out"
> 
> Optimizer:
>   name: AdamW
>   beta1: 0.9
>   beta2: 0.999
>   lr:
>     name: Linear
>     learning_rate: 0.000025
>     epochs: *epoch_num
>     warmup_epoch: 2
>   regularizer:
>     name: L2
>     factor: 0.00000
>     
> PostProcess:
>   name: VQASerTokenLayoutLMPostProcess
>   class_path: &class_path F:\deep\Drill hole histogram\9.train_ser_ext\class_list.txt
> 
> Metric:
>   name: VQASerTokenMetric
>   main_indicator: hmean
> 
> Train:
>   dataset:
>     name: SimpleDataSet
>     data_dir: F:\deep\Drill hole histogram
>     label_file_list: 
>       - F:\deep\Drill hole histogram\9.train_ser_ext\train_label.txt
>     ratio_list: [ 1.0 ]
>     transforms:
>       - DecodeImage: # load image
>           img_mode: RGB
>           channel_first: False
>       - VQATokenLabelEncode: # Class handling label
>           contains_re: False
>           algorithm: *algorithm
>           class_path: *class_path
>           use_textline_bbox_info: &use_textline_bbox_info True
>           # one of [None, "tb-yx"]
>           order_method: &order_method "tb-yx"
>       - VQATokenPad:
>           max_seq_len: &max_seq_len 512
>           return_attention_mask: True
>       - VQASerTokenChunk:
>           max_seq_len: *max_seq_len
>       - Resize:
>           size: [224,224]
>       - NormalizeImage:
>           scale: 1
>           mean: [ 123.675, 116.28, 103.53 ]
>           std: [ 58.395, 57.12, 57.375 ]
>           order: 'hwc'
>       - ToCHWImage:
>       - KeepKeys:
>           keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
>   loader:
>     shuffle: True
>     drop_last: False
>     batch_size_per_card: 4
>     num_workers: 12
> 
> Eval:
>   dataset:
>     name: SimpleDataSet
>     data_dir: F:\deep\Drill hole histogram
>     label_file_list:
>     - F:\deep\Drill hole histogram\9.train_ser_ext\test_label.txt
>     transforms:
>       - DecodeImage: # load image
>           img_mode: RGB
>           channel_first: False
>       - VQATokenLabelEncode: # Class handling label
>           contains_re: False
>           algorithm: *algorithm
>           class_path: *class_path
>           use_textline_bbox_info: *use_textline_bbox_info
>           order_method: *order_method
>       - VQATokenPad:
>           max_seq_len: *max_seq_len
>           return_attention_mask: True
>       - VQASerTokenChunk:
>           max_seq_len: *max_seq_len
>       - Resize:
>           size: [224,224]
>       - NormalizeImage:
>           scale: 1
>           mean: [ 123.675, 116.28, 103.53 ]
>           std: [ 58.395, 57.12, 57.375 ]
>           order: 'hwc'
>       - ToCHWImage:
>       - KeepKeys:
>           keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
>   loader:
>     shuffle: False
>     drop_last: False
>     batch_size_per_card: 8
>     num_workers: 4
> ```yaml
> ```

佬请问你解决这个问题了吗？
