### ISSUE TITLE
未转为inference的识别模型识别效果完美。但一转为inference之后用predict_rec识别就出现大量的nan

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PaddleOCR#935]
报错信息如下：
C:\Users\MINHOO>python C:/Users/MINHOO/AppData/Local/Programs/Python/Python37/tools/infer/predict_rec.py --image_dir="C:/Users/MINHOO/Desktop/POKER/rec/train/" --rec_model_dir="C:/Users/MINHOO/Desktop/POKER/inference/rec_crnn/"
C:\Users\MINHOO\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\MINHOO\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1004.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1005.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1014.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1024.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1025.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1042.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1043.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1066.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1067.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1068.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1069.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1070.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1098.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1115.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1135.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1156.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1175.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1199.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1214.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1226.jpg:['0', 0.28344637]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1231.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1237.jpg:['0', 0.56245553]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1247.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1252.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1255.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1265.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1271.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1273.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1297.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1298.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1306.jpg:['8', 0.30163422]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1307.jpg:['0', 0.4960568]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1318.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1319.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1329.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1330.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1338.jpg:['0', 0.2716659]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1339.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1344.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1345.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1351.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_144.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_145.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1458.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1459.jpg:['', nan]
Predicts of C:/Users/MINHOO/Desktop/POKER/rec/train/10_1468.jpg:['', nan]

**Comment by LDOUBLEV** [comment]
1. 提供一下转inference model的命令和输出日志
2. 试一下转换PaddleOCR提供的训练模型预测是否正常

**Comment by minhoooo1** [comment]
模型转换的日志
![image](https://user-images.githubusercontent.com/61350752/96068403-92919b80-0ece-11eb-8aa8-0ed50eb8399e.png)

**Comment by littletomatodonkey** [comment]
导出模型与模型预测时预处理稍微有点diff，这个我们明天修复下，感谢反馈~

**Comment by lim-0** [comment]
> 导出模型与模型预测时预处理稍微有点diff，这个我们明天修复下，感谢反馈~

你好，我也遇到类似的问题，请问有解决办法了吗？
![image](https://user-images.githubusercontent.com/35923416/96695089-d5b2a980-13bb-11eb-8e6c-ee1cf309be7c.png)
我已经指定了自己的字典，但预测时却出现了不在字典里的词

**Comment by lim-0** [comment]
> > 导出模型与模型预测时预处理稍微有点diff，这个我们明天修复下，感谢反馈~
> 
> 你好，我也遇到类似的问题，请问有解决办法了吗？
> ![image](https://user-images.githubusercontent.com/35923416/96695089-d5b2a980-13bb-11eb-8e6c-ee1cf309be7c.png)
> 我已经指定了自己的字典，但预测时却出现了不在字典里的词

如果不转换成inference模型则结果正常
