### ISSUE TITLE
Training Fails with the Table Generated Labels

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleOCR#9350]
Hi Everyone I generated Table Dataset using the table generator provided in the documentation

and after I try to train it gives me an error when parsing any line

ppocr ERROR: When parsing line {"filename": "img/border_top_294_J6M8X3DAZVHMCZN7TAUY.jpg", "html": {"structure": {"tokens": ["<tr>", "<td", " rowspan=\"2\"", ">", etc...}

File "/paddle/paddle-arabic/ppocr/data/pubtab_dataset.py", line 118, in __getitem__
    outs = transform(data, self.ops)
  File "/paddle/paddle-arabic/ppocr/data/imaug/__init__.py", line 53, in transform
    data = op(data)
  File "/paddle/paddle-arabic/ppocr/data/imaug/label_ops.py", line 673, in __call__
    bboxes[i] = bbox
ValueError: could not broadcast input array from shape (8,) into shape (4,)

any idea what's causing this?

**Comment by tink2123** [comment]
Please confirm whether the generated data format matches the configuration file：

https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/configs/table/SLANet.yml#L20

**Comment by bely66** [comment]
thanks it worked, it was generating a different format
