### ISSUE TITLE
训练不能使用共享显存吗？系统自动用内存代替显存是什么原因不能使用呢？

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#9351]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：python tools/train.py -c %config_path%
- 完整报错/Complete Error Message：

> Out of memory error on GPU 0. Cannot allocate 1.531982GB memory on GPU 0, 11.895996GB memory has been allocated and available memory is only 106.000000MB.
> 
> Please check whether there is any other process using GPU 0.
> 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> 2. If no, please decrease the batch size of your model.
> 
>  (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)
> . (at ..\paddle\fluid\imperative\tracer.cc:307)

发现是在eval model的时候有一个gpu内存占用率增长过程，因为专用gpu内存剩余空间不够了，但是程序又不会去占用共享GPU内存，然后就报错无法申请显存。

**Comment by OpenOneV** [comment]
![image](https://user-images.githubusercontent.com/115529885/223670667-1b40ad0f-c803-4965-bf4d-168cefd648ab.png)

**Comment by OpenOneV** [comment]
For search engine：topic of this issue in En: Can I train models using shared video memory? What is the reason why the system can't automatically uses shared video memory when GPU video memory is full?

**Comment by OpenOneV** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/test_tipc/configs/rec_r45_abinet/rec_r45_abinet.yml#L106
> 
> eval时开启共享内存：use_shared_memory: True

还是不行啊。
最后写了这一行还是会在peak的时候，报错没显存了啊

**Comment by OpenOneV** [comment]
@tink2123

**Comment by OpenOneV** [comment]
能请您注意一下，那个峰值的问题吗？开启了以后还是在那个峰值出错了。就好像缺少一个判断那样。

**Comment by OpenOneV** [comment]
![image](https://user-images.githubusercontent.com/115529885/224295231-c4691367-91bf-4b01-8f93-1ff2d879c73c.png)
![image](https://user-images.githubusercontent.com/115529885/224295246-bab26426-fee5-4a1b-85db-e5fae5c3de24.png)

**Comment by tink2123** [comment]
请问是在第一次eval时就会出现显存不足吗？

**Comment by OpenOneV** [comment]
> Collaborator
> ###
> ** [tink2123](/tink2123) ** commented [Mar 13, 2023](#issuecomment-1465657499) •

yes，我把eval设置成  Global.eval_batch_step: [0,10] 了。

您的意思是eval的时候并不会关闭train的前向网络吗？ 这样会导致训练的显存最小占用翻倍吧？怎么会没有一个在eval时候释放train的所有前向网络参数、输入输出显存占用的可选项呢？。。这不是一个很通用的优化问题？还是我理解有误捏
