### ISSUE TITLE
CUDA环境报错

### ISSUE THREAD

**Issue by goalya** [PaddlePaddle/PaddleOCR#9354]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 22.04.1 CUDA-11.7 cudnn-8.7 显卡3090
- 版本号/Version：Paddle 2.4：  PaddleOCR：2.6 问题相关组件/Related components：在gpu环境下报错，cpu可以运行
- 运行指令/Command Code：python tools/train.py --config=configs/rec/rec_r31_sar.yml
- 完整报错/Complete Error Message：
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < linear > error]

**Comment by tink2123** [comment]
paddle版本和本地cuda版本不一致:
python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by goalya** [comment]
> paddle版本和本地cuda版本不一致: python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

我在运行之前就是这么安装的，并且跑
paddle.utils.run_check()
结果是
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by yatoubusha** [comment]
我也是同样的问题，跑check是正常的，cuda和cudnn，nccl版本都对应，调用ocr的api就会报错
