### ISSUE TITLE
enchanced_ctc_loss

### ISSUE THREAD

**Issue by fishstarr** [PaddlePaddle/PaddleOCR#9358]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问具体的C-CTC的具体的展开公式应该是什么呢？
<img width="702" alt="386f4642355e2799c431e25ea12de0f" src="https://user-images.githubusercontent.com/108205156/223726991-c9600aec-27e1-4503-8cf8-0dcec6263a6b.png">
对应的Lctc怎么定义？

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
