### ISSUE TITLE
请问EAST、PSE效果差是为什么，DB模型结果正常

### ISSUE THREAD

**Issue by fishstarr** [PaddlePaddle/PaddleOCR#9359]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

这里是两个模型的结果以及默认配置文件

<img width="131" alt="314677a34d24995d64cdd4e407d4bb8" src="https://user-images.githubusercontent.com/108205156/223741122-acc6c89b-7121-43aa-9ae7-640081693200.png">

<img width="175" alt="97133e2238744f6448e3fd8928aab5a" src="https://user-images.githubusercontent.com/108205156/223740903-f025b312-bd1a-47d5-9c9d-e7d9a09b4ce6.png">

**Comment by LDOUBLEV** [comment]
测试数据是？

**Comment by fishstarr** [comment]
> 测试数据是？

自己的数据集，购物小票，DB模型三个指标都有90

**Comment by LDOUBLEV** [comment]
主要原因是没有在你的数据场景上训练过，跑出来的模型指标差异大很正常

**Comment by fishstarr** [comment]
> 不同模型的能力不一样，而且没有在你的数据场景上训练过，跑出来的模型指标差异大很正常

训练数据也是自己的，已经加载了预训练模型训练了自己的数据
