### ISSUE TITLE
Transformer unit 的 positional embedding 不用训练？

### ISSUE THREAD

**Issue by jjjjohnson** [PaddlePaddle/PaddleOCR#936]
请教一下：函数`prepare_encoder`中的[positional embedding](https://github.com/PaddlePaddle/PaddleOCR/blob/65a472cd7c28673e1122b968ccc56248eb7713ab/ppocr/modeling/heads/self_attention/model.py#L274)为啥`trainable=False`
还有[这里]也一样。(https://github.com/PaddlePaddle/PaddleOCR/blob/65a472cd7c28673e1122b968ccc56248eb7713ab/ppocr/modeling/heads/self_attention/model.py#L309).
是因为已经初始化了一个特定的值吗？还是其他地方会更新这个embedding，这边只是用这个embedding就可以了？

谢谢！

**Comment by tink2123** [comment]
这里是因为用两阶段，训练第二阶段时，固定了前面pvam模块的参数。端到端训练时是需要放开的，感谢反馈我更新下代码。

**Comment by jjjjohnson** [comment]
明白了 谢谢！
