### ISSUE TITLE
Table Recognition

### ISSUE THREAD

**Issue by harshsummit** [PaddlePaddle/PaddleOCR#9363]
Is there any way to map the table cells produced in html output of table recognition to their respective coordinates in the original image??

Can we have a structure of table recognition like:
{
 "cell" : {
   "text": "ocr text here"
   "coordinates":"[1,2,3,4]
    }
}

Currently paddle ocr table recognition gives output as 

`{"type": "table", "bbox": [13, 8, 559, 306], "res": {"cell_bbox": [[13.29407024383545, 15.610450744628906, 158.6073760986328, 37.66778564453125], [194.0216522216797, 17.634674072265625, 374.33203125, 37.230472564697266], [16.997289657592773, 68.49259185791016, 112.43869018554688, 93.95305633544922], [194.50376892089844, 70.65872955322266, 236.43637084960938, 91.50242614746094], [17.13978385925293, 113.75179290771484, 161.94627380371094, 137.48304748535156], [180.34690856933594, 113.11701965332031, 442.02923583984375, 139.59640502929688], [12.125612258911133, 162.91650390625, 167.30349731445312, 184.323974609375], [170.06082153320312, 160.9302215576172, 527.1134033203125, 190.5405731201172], [14.445188522338867, 212.7855987548828, 169.2019500732422, 235.40859985351562], [185.97653198242188, 210.74497985839844, 505.1007080078125, 239.2645263671875], [11.577629089355469, 262.8587646484375, 172.67910766601562, 284.759765625], [201.6256103515625, 259.0702209472656, 529.1819458007812, 289.9233703613281]], "html": "<html><body><table><thead><tr><td>Taxable income</td><td>Tax on this income</td></tr></thead><tbody><tr><td>0 - $18,200</td><td>Nil</td></tr><tr><td>$18,201 - $37.000</td><td>19c for each $1 over $18.200</td></tr><tr><td>$37,001 -- $90,000</td><td>$3,572 plus 32.5c for each $1 over $37.000</td></tr><tr><td>$90,001 - $180,000</td><td>$20,797 plus 37c for each $1 over $90,000</td></tr><tr><td>$180,001 and over</td><td>$54,097 plus 45c for each $1 over $180,000</td></tr></tbody></table></body></html>"}, "img_idx": 0}

`

for an image like 
![test](https://user-images.githubusercontent.com/122161388/223931640-ed603821-e5df-449e-869a-fa8a2c318e43.png)

**Comment by WenmuZhou** [comment]
It is currently not supported, you can sort it according to the coordinate relationship
