### ISSUE TITLE
为什么使用多个 SerPredictor 性能下降了呢？

### ISSUE THREAD

**Issue by sunzhaoyang** [PaddlePaddle/PaddleOCR#9365]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.6
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

使用 FastAPI 部署 Ser 模型。初始化一个 List，启动时放入两个 SerPredictor 实例。每个请求会先尝试从 list 里取一个 SerPredictor ，取不到就等，用完再放回去，以确保线程安全。

使用 locust 压测， user=1 时 预测耗时 0.5 秒，user=2 时预测耗时变成了 1 秒，不明白为什么。并发只有 2 并不存在等待的情况。

加了耗时统计的输出，也能看出其他过程的耗时没有增加，只有 预测的时间增加了。

```
# user=1
write file: 0.00028198095969855785
read img: 0.017052036011591554
queue wait: 2.0537059754133224e-05
predictor img: 0.5648561888374388
gen result: 0.00017279107123613358
total: 0.5823629968799651


# user=2
write file: 0.0005731489509344101
read img: 0.024949982995167375
queue wait: 3.124983049929142e-05
predictor img: 1.0066254558041692
gen result: 0.00017139920964837074
total: 1.0246716290712357

# nvidia-smi
7137MiB /  7981MiB

```

代码太长就不贴了，`predictor img` 的耗时仅包含这几行代码：
```
            ser_res, _, elapse = ser_predictor(img)
            ser_res = ser_res[0]
```

**Comment by cumthxy** [comment]
你解决这个问题了么？我也发现了。现在部署的时候 遇到这个问题很难解决

**Comment by danteblink** [comment]
@sunzhaoyang How did you manage to obtain those times?

I'm using GPU and the SerPredictor creation is taking alt least 4 seconds
