### ISSUE TITLE
文本识别训练完成后进行测试发生out_channels_list错误

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [PaddlePaddle/PaddleOCR#9366]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/53245262/223970321-eb139561-c8d6-42e7-b375-b3b222b423b0.png)
我在测试识别效果时：
执行命令：
python tools/infer_det.py -c C:\Users\admin\Desktop\PaddleOCR\PaddleOCRTran\ch_PP-OCRv3_rec_train\ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=C:\Users\admin\Desktop\PaddleOCR\PaddleOCRTran\ch_PP-OCRv3_rec_train\best_accuracy Global.infer_img=C:\Users\admin\Desktop\workImage\1\ng\crop_img\20230302145308008_crop_1.jpg

发生如上图所示错误，请问是什么原因造成的

**Comment by WenmuZhou** [comment]
infer_det换成infer_rec

**Comment by HanChinese-LIURUI** [comment]
![image](https://user-images.githubusercontent.com/53245262/223973429-6c2e3850-aee9-47b0-8f52-ffbe0b03beb9.png)
又报这个错误
