### ISSUE TITLE
arg ext_data_num in RecConAug

### ISSUE THREAD

**Issue by kenho211** [PaddlePaddle/PaddleOCR#9373]
`ext_data_num` seems is not used in RecConAug.

https://github.com/PaddlePaddle/PaddleOCR/blob/29cdda4eda0b3867d33b2ce018532ff96ac872b2/ppocr/data/imaug/rec_img_aug.py#L130-L170

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
