### ISSUE TITLE
AI studio 项目打包下载失败

### ISSUE THREAD

**Issue by yao-yu1999** [PaddlePaddle/PaddleOCR#9374]
我的项目地址：【未公开】
https://aistudio.baidu.com/bj-cpu-01/user/704965/3414002/

  - 训练之后，预测模型和预测结果都不能打包下载。
  - 显示“打包下载失败：Bad Request”
  - 我已经用了“zip result.zip ./*”等命令，允许弹窗等方法，都不行

**Comment by an1018** [comment]
试试tar命令

**Comment by yao-yu1999** [comment]
已经解决了。希望不要下架旧版本，毕业设计还在这个里面项目里面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] AI studio 项目打包下载失败 (Issue #9374)





 
试试tar命令

**Comment by an1018** [comment]
这个不能保证的，这属于AIStudio产品，不太了解他们之后维护版本，最好自己备份
