### ISSUE TITLE
字典文件可以随时增减，在之前不同字典的预训练模型上也能恢复训练？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9375]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

字典文件可以随时增减，在之前不同字典的预训练模型上也能恢复训练？

Q2.13: 遇到中英文识别模型不支持的字符，该如何对模型做微调？
A：如果希望识别中英文识别模型中不支持的字符，需要更新识别的字典，并完成微调过程。比如说如果希
望模型能够进一步识别罗马数字，可以按照以下步骤完成模型微调过程。
1. 准备中英文识别数据以及罗马数字的识别数据，用于训练，同时保证罗马数字和中英文识别数字的效果；
2. 修改默认的字典文件，在后面添加罗马数字的字符；
3. 下载PaddleOCR提供的预训练模型，配置预训练模型和数据的路径，开始训练。

**Comment by an1018** [comment]
可以的，第2条不是写了修改字典训练

**Comment by nissansz** [comment]
单修改字典文件，模型文件不会报不匹配错误？

**Comment by an1018** [comment]
你在字典后面append，保证数据label没问题就行

**Comment by nissansz** [comment]
pytorch训练，不允许这种操作？只有paddle可以？
