### ISSUE TITLE
PaddleOCR可以在Paddle Inference中使用吗？

### ISSUE THREAD

**Issue by hujimei** [PaddlePaddle/PaddleOCR#9377]
PaddleOCR可以在Paddle Inference中使用吗？具体使用方法是什么？有相关的参考文档吗？

**Comment by an1018** [comment]
你说的是模型导出与预测？https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/detection.md#4-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B

**Comment by hujimei** [comment]
> 你说的是模型导出与预测？[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/detection.md#4-%E6%A8%A1%E5%9E% 8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/detection.md#4-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B)
不是这个，我想要咨询的是，目前我根据paddle inference文档进行了源码编译，我想问这个paddle inference环境支持使用PaddleOCR的相关模型吗？

**Comment by an1018** [comment]
这个吧，https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/cpp_infer/readme_ch.md
