### ISSUE TITLE
识别模型转为推理模型，修改推理输入高，导致推理异常问题

### ISSUE THREAD

**Issue by dtiny** [PaddlePaddle/PaddleOCR#9378]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04
- 版本号/Version：Paddle 2.4.1：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/export_model.py -c configs/rec/starnet_r34_vd_none_none_ctc.yml \
-o Global.pretrained_model=./output/rec/starnet_r34_vd_none_none_ctc/best_accuracy  Global.save_inference_dir=models/starnet_none_48x224/
- 完整报错/Complete Error Message：模型训练输入尺寸hxw：48x224, 训练正常收敛，准确率80%，转换推理模型正常，用onnx显示尺寸也是正常的，name: x type: float32[?,3,48,?]，name: softmax_0.tmp_0 type: float32[?,?,6757]，如果输入尺寸为hxw:48x224推理结果的不正确；如果将输入尺寸为hxw:32x224推理结果正确。
- 仔细看了tools/export_model.py 文件， 
       model = to_static(
            model,
            input_spec=[
                paddle.static.InputSpec(
                    shape=[None] + infer_shape, dtype="float32")
            ])
是在paddle中就把高给限制只能为32吗，还是什么情况，导出模型的推理结果只有在高为32的时候正确，其他就就是不对。
这个是什么原因导致，有办法解决吗？

**Comment by an1018** [comment]
高度和训练保持一致
