### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by zhaoguoqing12** [PaddlePaddle/PaddleOCR#938]
训练角度分类器模型，总是在训练完第一周期，出现OSError: [Errno 12] Cannot allocate memory
![image](https://user-images.githubusercontent.com/47818312/96090023-3a708e80-0efa-11eb-8e73-c882459c2637.png)

**Comment by grasswolfs** [comment]
您好，由于长时间没有收到您的回复，本issue暂时关闭，如果还有更多问题，可以reopen或者新开一个issue继续提问，感谢您对于PaddleOCR的支持。

**Comment by Mrfuhang** [comment]
> 试着把bs改小一点试下吧

bs 是啥啊
