### ISSUE TITLE
what's wrong in this dataset format?

### ISSUE THREAD

**Issue by rpsipl2021** [PaddlePaddle/PaddleOCR#9380]
![Screenshot from 2023-03-10 10-39-21](https://user-images.githubusercontent.com/113658786/224229103-e4e3813f-e61b-4f83-a484-b49029e19042.png)
]
can someone correct if I'm using wrong dataset formate?

**Comment by an1018** [comment]
you can try make your dataset like this format:

> {
   'filename': str,
   'split': str,
   'imgid': int,
   'html': {
     'structure': {'tokens': [str]},
     'cell': [
       {
         'tokens': [str],
         'bbox': [x0, y0, x1, y1]  # only non-empty cells have this attribute
       }
     ]
   }
}

**Comment by rpsipl2021** [comment]
not working, even it's giving new error:
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)
and I'm using .txt file for model training and SLANet_ch.yml file,
in previous error it was giving error and parallel training was also running with some files in training data.

**Comment by WenmuZhou** [comment]
In your data, whether the blank cells have been marked, and all the cell label information has been spatially sorted

**Comment by rpsipl2021** [comment]
I'm uploading train.txt file, can you please go through it and check where exactly problem is?
[train (1).txt](https://github.com/PaddlePaddle/PaddleOCR/files/10964975/train.1.txt)

**Comment by rpsipl2021** [comment]
@WenmuZhou  can you please explain what do you mean by whether the blank cells have been marked, and all the cell label information has been spatially sorted?
