### ISSUE TITLE
请问PaddleOCR.ocr函数可以获得单个字符的置信度吗？

### ISSUE THREAD

**Issue by ThomasjonLi** [PaddlePaddle/PaddleOCR#9381]
请问PaddleOCR.ocr函数可以获得单个字符的置信度吗，目前返回的结果中是整个字符串的一个score，可以返回每个单个字符的score吗？

**Comment by an1018** [comment]
开发中，后续可以关注下~

**Comment by ThomasjonLi** [comment]
找到了，可以修改ppocr/postprocess/rec_postprocess.py中的decode函数，返回conf_list

**Comment by ctgushiwei** [comment]
> 找到了，可以修改ppocr/postprocess/rec_postprocess.py中的decode函数，返回conf_list

具体是哪个函数啊？
