### ISSUE TITLE
Each time you delete an image, the cursor automatically returns to the first line, which is inconvenient to use

### ISSUE THREAD

**Issue by all-for-code** [PaddlePaddle/PaddleOCR#9383]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
which function？

**Comment by all-for-code** [comment]
文件列表中导入图片后，删除其中一张后，会自动将光标移动到第一行，使用起来很不方便，建议删除一张后，光标移动到下一张图片上面，这样使用起来比较方便，不然当图片很多的时候使用起来不方便。具体应该是在“删除图像”button的槽函数里面吧。
