### ISSUE TITLE
det预测的时候。会把一个不需要的地方 标注出来。大概会是什么原因呢

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9385]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
det预测
```
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_dml_inference/Student" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgsresult/" \
--use_gpu=True
```
- 完整报错/Complete Error Message：
- 预测结果
![image](https://user-images.githubusercontent.com/32863094/224256316-234dc114-aa73-47e3-880d-4fef58a057ab.png)
- 样本数据。大概有20张
![image](https://user-images.githubusercontent.com/32863094/224259417-5cd83314-3dc2-43a5-b337-a47a0fe310e8.png)

![image](https://user-images.githubusercontent.com/32863094/224259489-f39119f0-780e-4326-9084-0b53210db972.png)

**Comment by an1018** [comment]
可以把框过滤的阈值box_thresh调大些

**Comment by rexzhengzhihong** [comment]
在哪里调？

**Comment by rexzhengzhihong** [comment]
把box_thresh调大些，想要的框反而出不来了

**Comment by rexzhengzhihong** [comment]
![image](https://user-images.githubusercontent.com/32863094/224594265-d74d1342-28f1-44cb-af0d-8ff3d6689084.png)
这空其实不需要。要标注吗？

**Comment by rexzhengzhihong** [comment]
可以把备注的那个框 设置为“###”吗。这样会忽略吗

**Comment by rexzhengzhihong** [comment]
@an1018

**Comment by rexzhengzhihong** [comment]
> 可以把备注的那个框 设置为“###”吗。这样会忽略吗

这个设置了还是一样的效果

**Comment by rexzhengzhihong** [comment]
@LDOUBLEV 能帮忙看看吗
