### ISSUE TITLE
PaddleOCR和PaddleOCRv2、PaddleOCRv3的模型使用问题不清楚

### ISSUE THREAD

**Issue by hujimei** [PaddlePaddle/PaddleOCR#9386]
PaddleOCR、PaddleOCRv2和PaddleOCRv3的模型使用是不是只要环境配置满足paddlepaddle2.0+的版本要求，就可以使用三个版本中的任何一个模型了？还是说每个模型对应的系统、架构、内核、处理器版本等要求都是不一样的？

**Comment by an1018** [comment]
使用低版本的分支+paddlepaddle高版本不确定会不会报错，不过可以尝试下载模型试试
