### ISSUE TITLE
手写数字识别， 训练自己的数据效果一直很差， 我的数据比较长，公式比较麻烦，请问可以修改哪部分提高准确率啊

### ISSUE THREAD

**Issue by dongjie-shi** [PaddlePaddle/PaddleOCR#9387]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by an1018** [comment]
数据比较长会导致resize之后太模糊，可以增大图片尺寸训练看

**Comment by super-tian** [comment]
宽高比，maxlength
