### ISSUE TITLE
检测模型准确率为0

### ISSUE THREAD

**Issue by guiniao** [PaddlePaddle/PaddleOCR#9394]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
使用PP-OCRv3，检测模型MobileNetV3分别对生成的车牌数据训练，检测模型准确率都为0，输入图片
shape为（72,246,3），是不是模型输入尺寸和图片大小没匹配上，图像太小了，怎么修改yml的参数（哪个参数修改图片大小的），感谢

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/9c22490f958f42b6c7f88f42374a78addb7e75dd/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml#L94 这个参数控制训练时的图像大小
