### ISSUE TITLE
我用PPOCRLabel标注工具时，出现卡死闪退现象，如何解决

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9396]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "C:\Users\PHB\Desktop\ocr_table\PaddleOCR-dygraph\PPOCRLabel\libs\canvas.py", line 164, in mouseMoveEvent
    self.line.close()
  File "C:\Users\PHB\Desktop\ocr_table\PaddleOCR-dygraph\PPOCRLabel\libs\shape.py", line 95, in close
    self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range

标几个地方就卡死了，画不出来框，然后关不掉，然后就闪退了，报错信息如上，希望大佬们能帮我解决一下，是什么问题造成的。谢谢！

**Comment by phb-shiyige-fw** [comment]
@huangjun12 @ZeyuChen @

**Comment by Camphora7** [comment]
用2.6最新版的代码试一下，我这边最新版本的已经没有这个问题了

**Comment by Juruobudong** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/20828404/5bdc9e75-c4c3-4b41-acac-9461b2e55e69)
我也是，他不是一开始报这个错，而是标了一大半出错，很容易气死。。而且我就算中途ctrl+v保存后，也没写入Label.txt。只有退出才会保存。没退出的话，他还是读取的Cache.cach文件

**Comment by ifjgm005** [comment]
将 canvas.py 164 行附近的代码
                 if self.drawSquare:
                     self.line.points = [self.current[0], pos]
                     self.line.close()
               
               修改为如下这样即可
                if self.drawSquare:
                    x1, y1 = self.current[0].x(), self.current[0].y()
                    x2, y2 = pos.x(), pos.y()
                    self.line.points = [QPointF(x1, y1), QPointF(x1, y2), QPointF(x2, y2), QPointF(x2, y1)]
                    self.line.close()
