### ISSUE TITLE
每次训练迭代没起来然后报错就退出程序了：(0xC0000409)

### ISSUE THREAD

**Issue by yygc2002** [PaddlePaddle/PaddleOCR#9397]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows11 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：python3.7 ; cuda 11.2 ; paddlepaddle-gpu 2.4.2 ; paddleocr-release-2.6
- 运行指令/Command Code：python tools/train.py -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：Process finished with exit code -1073740791 (0xC0000409)

**Comment by huangjun12** [comment]
有更完整的报错信息吗

**Comment by yygc2002** [comment]
> 

程序没有其他报错了，windows日志那里到是有一个：
错误应用程序名称: python.exe，版本: 3.7.150.1013，时间戳: 0x5b34dd6a
错误模块名称: ucrtbase.dll，版本: 10.0.22000.1，时间戳: 0x00e78ce9
异常代码: 0xc0000409
错误偏移量: 0x000000000007dd7e
错误进程 ID: 0x41ec
错误应用程序启动时间: 0x01d9529c386524a8
错误应用程序路径: D:\environment\envs\paddleocr26\python.exe
错误模块路径: C:\Windows\System32\ucrtbase.dll
报告 ID: eda2a527-2f47-442d-8bc7-eff5484f059f
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by yygc2002** [comment]
> 有更完整的报错信息吗

@huangjun12 程序没有其他报错了，windows日志那里到是有一个：
错误应用程序名称: python.exe，版本: 3.7.150.1013，时间戳: 0x5b34dd6a
错误模块名称: ucrtbase.dll，版本: 10.0.22000.1，时间戳: 0x00e78ce9
异常代码: 0xc0000409
错误偏移量: 0x000000000007dd7e
错误进程 ID: 0x41ec
错误应用程序启动时间: 0x01d9529c386524a8
错误应用程序路径: D:\environment\envs\paddleocr26\python.exe
错误模块路径: C:\Windows\System32\ucrtbase.dll
报告 ID: eda2a527-2f47-442d-8bc7-eff5484f059f
错误程序包全名:
错误程序包相对应用程序 ID:

**Comment by yygc2002** [comment]
我电脑本身有cuda12.0的驱动，cuda11.2我不是去NVIDIA官网下的，我是用官网的指令：conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 。下载的cudatoolkit=11.2，我看网上说这样就不用下一个完整的cuda，不知道是不是这个的原因

**Comment by yygc2002** [comment]
好的，我装了完整的cuda10.2和cudann7.6.5，paddlepaddle的包也换成对应的了，还得一样的报错

**Comment by huangjun12** [comment]
安装好paddle之后，跑一下paddle.utils.run_check()，看下是否能成功运行。如果运行失败，大概率是环境问题，比如装好cuda后没有设置好环境变量

**Comment by yygc2002** [comment]
> paddle.utils.run_check(
@huangjun12 运行结果是这样的，好像没问题
Running verify PaddlePaddle program ...
W0314 21:36:45.958832 23256 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.2
W0314 21:36:46.247545 23256 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
