### ISSUE TITLE
关键信息提取训练错误 Assertion false failed. The value of label expected >= 0

### ISSUE THREAD

**Issue by ASLYY** [PaddlePaddle/PaddleOCR#9398]
Hi,我标注了kie所需要的数据集 在格式上与文档说明中的格式保持了一致 但是执行训练的时候会报一下错误：
Error: /paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1008 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 16. Please check label value. 
Error: /paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1008 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 9. Please check label value.
Error: /paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1008 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 9. Please check label value.
Error: /paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1008 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 8. Please check label value.
Error: /paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1008 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 8. Please check label value.
请问这是什么原因呢 检查了标签但是实在没有头绪 希望能得到解答！非常感谢！

**Comment by huangjun12** [comment]
算交叉熵损失的时候报错了，期望类别id是0<=x<7，实际输入的类别id是16，看下是否没有改最后fc层的类别数

**Comment by zhuqiang00099** [comment]
我也报这个错误头疼，XFUND数据集就不报错

**Comment by hellokhj** [comment]
> 算交叉熵损失的时候报错了，期望类别id是0<=x<7，实际输入的类别id是16，看下是否没有改最后fc层的类别数
请问在哪里修改fc层
