### ISSUE TITLE
可以可视化热力图？

### ISSUE THREAD

**Issue by fishstarr** [PaddlePaddle/PaddleOCR#9399]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
暂不支持，需要自己实现一下哈
