### ISSUE TITLE
转c++部署推理该怎么使用自己训练的模型？

### ISSUE THREAD

**Issue by chc-stars** [PaddlePaddle/PaddleOCR#9400]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by chc-stars** [comment]
你们的C++部署是只能使用你们提供的推理模型嘛！如果是自己的模型，网络结构需不需要改？

**Comment by chc-stars** [comment]
为啥转为推理模型后很多都检测不出来，效果差的离谱？

**Comment by chc-stars** [comment]
为啥转为推理模型后很多都检测不出来，效果差的离谱？

**Comment by thsno02** [comment]
> 为啥转为推理模型后很多都检测不出来，效果差的离谱？

可以检查一下前处理部分的代码是否和训练时的一致，同时检查自己的配置文件和推理的命令。

**Comment by chc-stars** [comment]
已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 下午2:18
收件人: ***@***.***&gt;; 
抄送: "“ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 转c++部署推理该怎么使用自己训练的模型？ (Issue #9400)





  
为啥转为推理模型后很多都检测不出来，效果差的离谱？
  
可以检查一下前处理部分的代码是否和训练时的一致，同时检查自己的配置文件和推理的命令。
