### ISSUE TITLE
训练检测模型，只检测到整张图片边缘的框，无法检测到文字位置，请问是什么原因

### ISSUE THREAD

**Issue by 1wang11lijian1** [PaddlePaddle/PaddleOCR#9402]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10，python3.7
- 版本号/Version：Paddle：2.6  PaddleOCR：2.6 问题相关组件/Related components：训练检测模型，只检测到整张图片边缘的框，无法检测到文字位置，请问是什么原因
- 运行指令/Command Code：python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/
- 完整报错/Complete Error Message：
以下是训练的ch_PP-OCRv3_det_cml.yml文件
Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/en_PP-OCR_v3_det/
  save_epoch_step: 100
  eval_batch_step:
  - 0
  - 400
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  save_res_path: ./output/det/predicts_ppocrv3_en.txt
  distributed: true

Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      pretrained:
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        name: DBHead
        k: 50
    Student2:
      pretrained: 
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        name: DBHead
        k: 50
    Teacher:
      pretrained: 
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: ResNet_vd
        in_channels: 3
        layers: 50
      Neck:
        name: LKPAN
        out_channels: 256
      Head:
        name: DBHead
        kernel_list: [7,2,2]
        k: 50

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - ["Student", "Teacher"]
      - ["Student2", "Teacher"]
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - ["Student", "Student2"]
      maps_name: "thrink_maps"
      weight: 1.0
      model_name_pairs: ["Student", "Student2"]
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list: ["Student", "Student2"]
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05

PostProcess:
  name: DistillationDBPostProcess
  model_name: ["Student"]
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/icdar_c4_train_imgs/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [1.0]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - CopyPaste:
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 960
        - 960
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 10
    num_workers: 2
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/ch4_test_images/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2

以下是测试训练出来的模型的检测图片
全部都是只检测出图片边缘的蓝色框
请问这是哪个地方出现问题了

![image](https://user-images.githubusercontent.com/101158990/224586214-33087a75-8188-49fe-ad0f-7844dcf0e77e.png)

![image](https://user-images.githubusercontent.com/101158990/224586097-c863b199-23fe-4296-bb51-a8ed2732c409.png)

**Comment by LDOUBLEV** [comment]
没加载预训练模型
> python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/

/pretrain_models/MobileNetV3_large_x0_5_pretrained/ 是Backbone在image net上的预训练参数

用OCR模型需下载主页readme里的模型
<img width="888" alt="image" src="https://user-images.githubusercontent.com/26592129/224620806-a5c06d99-a703-4cbe-b295-267d350fa95a.png">

**Comment by 1wang11lijian1** [comment]
你好，谢谢你的回复，我这边下载了你说的PP-OCRv3权重，并在训练中作为预训练模型，但是还是跟上面一样的结果，没有检测出来任何文字的位置。下面是我训练的代码以及推理的部分过程，其中1280，720是图片大小。麻烦大佬帮忙再看看这是什么导致的？

训练的代码（加载了PP-OCRv3检测模型的权重）
python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.pretrain_weights=./pretrain_models/en_PP-OCRv3_det_distill_train/

推理的几张图片结果
[2023/03/14 08:50:58] ppocr INFO: infer_img: ./train_data/icdar2015/text_localization/ch4_test_images\img_96.jpg
[[[   0    0]
  [1280    0]
  [1280  720]
  [   0  720]]]
[2023/03/14 08:50:58] ppocr INFO: The detected Image saved in ./output/det/det_results_Student/img_96.jpg
[2023/03/14 08:50:58] ppocr INFO: infer_img: ./train_data/icdar2015/text_localization/ch4_test_images\img_97.jpg
[[[   0    0]
  [1280    0]
  [1280  720]
  [   0  720]]]
[2023/03/14 08:50:58] ppocr INFO: The detected Image saved in ./output/det/det_results_Student/img_97.jpg
[2023/03/14 08:50:58] ppocr INFO: infer_img: ./train_data/icdar2015/text_localization/ch4_test_images\img_98.jpg
[[[   0    0]
  [1280    0]
  [1280  720]
  [   0  720]]]
[2023/03/14 08:50:58] ppocr INFO: The detected Image saved in ./output/det/det_results_Student/img_98.jpg
[2023/03/14 08:50:58] ppocr INFO: infer_img: ./train_data/icdar2015/text_localization/ch4_test_images\img_99.jpg
[[[   0    0]
  [1280    0]
  [1280  720]
  [   0  720]]]
[2023/03/14 08:50:58] ppocr INFO: The detected Image saved in ./output/det/det_results_Student/img_99.jpg

**Comment by 1wang11lijian1** [comment]
@LDOUBLEV 请问什么原因呢

**Comment by guiniao** [comment]
把下面的Eval中的DetResizeForTest改成resize_long:960试试看

**Comment by 1wang11lijian1** [comment]
@guiniao 你好，谢谢你的回复，我这边试了您说的这个方法，我修改了这个文件ch_PP-OCRv3_det_cml.yml中的Eval部分如下第一部分，下面第二部分是训练一开始几轮的日志，其中最后一行的指标precision: 0.0, recall: 0.0，我觉得这次尝试可能会失败。请问可以微信详聊吗，这是我的微信号17361712910。

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/ch4_test_images/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          size:
            - 960
            - 960
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']

训练一开始几轮的日志：
[2023/03/16 10:57:25] ppocr INFO: epoch: [4/500], global_step: 310, lr: 0.001000, dila_dbloss_Student_Teacher: 0.148534, dila_dbloss_Student2_Teacher: 0.186120, loss: 14.489466, dml_thrink_maps_0: 0.010857, db_Student_loss_shrink_ma
ps: 4.933090, db_Student_loss_threshold_maps: 1.147401, db_Student_loss_binary_maps: 0.986695, db_Student2_loss_shrink_maps: 4.932360, db_Student2_loss_threshold_maps: 1.147477, db_Student2_loss_binary_maps: 0.986715, avg_reader_cos
t: 0.32777 s, avg_batch_cost: 2.12928 s, avg_samples: 10.0, ips: 4.69643 samples/s, eta: 1 day, 6:07:01
[2023/03/16 10:57:47] ppocr INFO: epoch: [4/500], global_step: 320, lr: 0.001000, dila_dbloss_Student_Teacher: 0.141147, dila_dbloss_Student2_Teacher: 0.173905, loss: 14.463524, dml_thrink_maps_0: 0.010222, db_Student_loss_shrink_ma
ps: 4.926154, db_Student_loss_threshold_maps: 1.145463, db_Student_loss_binary_maps: 0.985328, db_Student2_loss_shrink_maps: 4.925036, db_Student2_loss_threshold_maps: 1.146317, db_Student2_loss_binary_maps: 0.985347, avg_reader_cos
t: 0.37468 s, avg_batch_cost: 2.17309 s, avg_samples: 10.0, ips: 4.60175 samples/s, eta: 1 day, 6:06:26
[2023/03/16 10:58:08] ppocr INFO: epoch: [4/500], global_step: 330, lr: 0.001000, dila_dbloss_Student_Teacher: 0.136445, dila_dbloss_Student2_Teacher: 0.166648, loss: 14.421456, dml_thrink_maps_0: 0.008884, db_Student_loss_shrink_ma
ps: 4.932472, db_Student_loss_threshold_maps: 1.142820, db_Student_loss_binary_maps: 0.986545, db_Student2_loss_shrink_maps: 4.931602, db_Student2_loss_threshold_maps: 1.142885, db_Student2_loss_binary_maps: 0.986556, avg_reader_cos
t: 0.34648 s, avg_batch_cost: 2.14598 s, avg_samples: 10.0, ips: 4.65987 samples/s, eta: 1 day, 6:05:10
[2023/03/16 10:58:30] ppocr INFO: epoch: [4/500], global_step: 340, lr: 0.001000, dila_dbloss_Student_Teacher: 0.130202, dila_dbloss_Student2_Teacher: 0.158107, loss: 14.415939, dml_thrink_maps_0: 0.008336, db_Student_loss_shrink_ma
ps: 4.938410, db_Student_loss_threshold_maps: 1.142064, db_Student_loss_binary_maps: 0.987729, db_Student2_loss_shrink_maps: 4.937699, db_Student2_loss_threshold_maps: 1.142208, db_Student2_loss_binary_maps: 0.987736, avg_reader_cos
t: 0.33718 s, avg_batch_cost: 2.14138 s, avg_samples: 10.0, ips: 4.66988 samples/s, eta: 1 day, 6:03:51
[2023/03/16 10:58:52] ppocr INFO: epoch: [4/500], global_step: 350, lr: 0.001000, dila_dbloss_Student_Teacher: 0.121063, dila_dbloss_Student2_Teacher: 0.149888, loss: 14.418106, dml_thrink_maps_0: 0.007144, db_Student_loss_shrink_ma
ps: 4.932528, db_Student_loss_threshold_maps: 1.141053, db_Student_loss_binary_maps: 0.986614, db_Student2_loss_shrink_maps: 4.931944, db_Student2_loss_threshold_maps: 1.142218, db_Student2_loss_binary_maps: 0.986619, avg_reader_cos
t: 0.34198 s, avg_batch_cost: 2.14578 s, avg_samples: 10.0, ips: 4.66031 samples/s, eta: 1 day, 6:02:41
[2023/03/16 10:59:14] ppocr INFO: epoch: [4/500], global_step: 360, lr: 0.001000, dila_dbloss_Student_Teacher: 0.114768, dila_dbloss_Student2_Teacher: 0.142519, loss: 14.393169, dml_thrink_maps_0: 0.006410, db_Student_loss_shrink_ma
ps: 4.928962, db_Student_loss_threshold_maps: 1.146375, db_Student_loss_binary_maps: 0.985828, db_Student2_loss_shrink_maps: 4.928376, db_Student2_loss_threshold_maps: 1.147378, db_Student2_loss_binary_maps: 0.985837, avg_reader_cos
t: 0.36938 s, avg_batch_cost: 2.18959 s, avg_samples: 10.0, ips: 4.56706 samples/s, eta: 1 day, 6:02:34
[2023/03/16 10:59:35] ppocr INFO: epoch: [4/500], global_step: 370, lr: 0.001000, dila_dbloss_Student_Teacher: 0.110561, dila_dbloss_Student2_Teacher: 0.135702, loss: 14.367229, dml_thrink_maps_0: 0.006696, db_Student_loss_shrink_ma
ps: 4.920202, db_Student_loss_threshold_maps: 1.146687, db_Student_loss_binary_maps: 0.984104, db_Student2_loss_shrink_maps: 4.919592, db_Student2_loss_threshold_maps: 1.149370, db_Student2_loss_binary_maps: 0.984117, avg_reader_cos
t: 0.34338 s, avg_batch_cost: 2.15178 s, avg_samples: 10.0, ips: 4.64731 samples/s, eta: 1 day, 6:01:36
[2023/03/16 10:59:57] ppocr INFO: epoch: [4/500], global_step: 380, lr: 0.001000, dila_dbloss_Student_Teacher: 0.104074, dila_dbloss_Student2_Teacher: 0.130746, loss: 14.357050, dml_thrink_maps_0: 0.005552, db_Student_loss_shrink_ma
ps: 4.931272, db_Student_loss_threshold_maps: 1.140896, db_Student_loss_binary_maps: 0.986277, db_Student2_loss_shrink_maps: 4.930660, db_Student2_loss_threshold_maps: 1.144727, db_Student2_loss_binary_maps: 0.986284, avg_reader_cos
t: 0.32097 s, avg_batch_cost: 2.12888 s, avg_samples: 10.0, ips: 4.69731 samples/s, eta: 1 day, 6:00:10
[2023/03/16 11:00:19] ppocr INFO: epoch: [4/500], global_step: 390, lr: 0.001000, dila_dbloss_Student_Teacher: 0.102839, dila_dbloss_Student2_Teacher: 0.127228, loss: 14.340802, dml_thrink_maps_0: 0.005748, db_Student_loss_shrink_ma
ps: 4.920578, db_Student_loss_threshold_maps: 1.142502, db_Student_loss_binary_maps: 0.984212, db_Student2_loss_shrink_maps: 4.919618, db_Student2_loss_threshold_maps: 1.142910, db_Student2_loss_binary_maps: 0.984216, avg_reader_cos
t: 0.39699 s, avg_batch_cost: 2.20500 s, avg_samples: 10.0, ips: 4.53516 samples/s, eta: 1 day, 6:00:24
[2023/03/16 11:00:33] ppocr INFO: save model in ./output/en_PP-OCR_v3_det/latest
[2023/03/16 11:00:43] ppocr INFO: epoch: [5/500], global_step: 400, lr: 0.001000, dila_dbloss_Student_Teacher: 0.098955, dila_dbloss_Student2_Teacher: 0.119900, loss: 14.291090, dml_thrink_maps_0: 0.006539, db_Student_loss_shrink_ma
ps: 4.901950, db_Student_loss_threshold_maps: 1.135324, db_Student_loss_binary_maps: 0.980396, db_Student2_loss_shrink_maps: 4.901190, db_Student2_loss_threshold_maps: 1.142910, db_Student2_loss_binary_maps: 0.980404, avg_reader_cos
t: 0.54792 s, avg_batch_cost: 2.31522 s, avg_samples: 10.0, ips: 4.31924 samples/s, eta: 1 day, 6:02:51
eval model:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 499/500 [01:04<00:00,  7.68it/s]
[2023/03/16 11:01:48] ppocr INFO: cur metric, precision: 0.0, recall: 0.0, hmean: 0, fps: 8.264265517193737

**Comment by jingmingtao** [comment]
> @guiniao 你好，谢谢你的回复，我这边试了您说的这个方法，我修改了这个文件ch_PP-OCRv3_det_cml.yml中的Eval部分如下第一部分，下面第二部分是训练一开始几轮的日志，其中最后一行的指标precision: 0.0, recall: 0.0，我觉得这次尝试可能会失败。请问可以微信详聊吗，这是我的微信号17361712910。
> 
> Eval: dataset: name: SimpleDataSet data_dir: ./train_data/icdar2015/text_localization/ch4_test_images/ label_file_list: - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt transforms: - DecodeImage: # load image img_mode: BGR channel_first: False - DetLabelEncode: # Class handling label - DetResizeForTest: size: - 960 - 960 - NormalizeImage: scale: 1./255. mean: [0.485, 0.456, 0.406] std: [0.229, 0.224, 0.225] order: 'hwc' - ToCHWImage: - KeepKeys: keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
> 
> 训练一开始几轮的日志： [2023/03/16 10:57:25] ppocr INFO: epoch: [4/500], global_step: 310, lr: 0.001000, dila_dbloss_Student_Teacher: 0.148534, dila_dbloss_Student2_Teacher: 0.186120, loss: 14.489466, dml_thrink_maps_0: 0.010857, db_Student_loss_shrink_ma ps: 4.933090, db_Student_loss_threshold_maps: 1.147401, db_Student_loss_binary_maps: 0.986695, db_Student2_loss_shrink_maps: 4.932360, db_Student2_loss_threshold_maps: 1.147477, db_Student2_loss_binary_maps: 0.986715, avg_reader_cos t: 0.32777 s, avg_batch_cost: 2.12928 s, avg_samples: 10.0, ips: 4.69643 samples/s, eta: 1 day, 6:07:01 [2023/03/16 10:57:47] ppocr INFO: epoch: [4/500], global_step: 320, lr: 0.001000, dila_dbloss_Student_Teacher: 0.141147, dila_dbloss_Student2_Teacher: 0.173905, loss: 14.463524, dml_thrink_maps_0: 0.010222, db_Student_loss_shrink_ma ps: 4.926154, db_Student_loss_threshold_maps: 1.145463, db_Student_loss_binary_maps: 0.985328, db_Student2_loss_shrink_maps: 4.925036, db_Student2_loss_threshold_maps: 1.146317, db_Student2_loss_binary_maps: 0.985347, avg_reader_cos t: 0.37468 s, avg_batch_cost: 2.17309 s, avg_samples: 10.0, ips: 4.60175 samples/s, eta: 1 day, 6:06:26 [2023/03/16 10:58:08] ppocr INFO: epoch: [4/500], global_step: 330, lr: 0.001000, dila_dbloss_Student_Teacher: 0.136445, dila_dbloss_Student2_Teacher: 0.166648, loss: 14.421456, dml_thrink_maps_0: 0.008884, db_Student_loss_shrink_ma ps: 4.932472, db_Student_loss_threshold_maps: 1.142820, db_Student_loss_binary_maps: 0.986545, db_Student2_loss_shrink_maps: 4.931602, db_Student2_loss_threshold_maps: 1.142885, db_Student2_loss_binary_maps: 0.986556, avg_reader_cos t: 0.34648 s, avg_batch_cost: 2.14598 s, avg_samples: 10.0, ips: 4.65987 samples/s, eta: 1 day, 6:05:10 [2023/03/16 10:58:30] ppocr INFO: epoch: [4/500], global_step: 340, lr: 0.001000, dila_dbloss_Student_Teacher: 0.130202, dila_dbloss_Student2_Teacher: 0.158107, loss: 14.415939, dml_thrink_maps_0: 0.008336, db_Student_loss_shrink_ma ps: 4.938410, db_Student_loss_threshold_maps: 1.142064, db_Student_loss_binary_maps: 0.987729, db_Student2_loss_shrink_maps: 4.937699, db_Student2_loss_threshold_maps: 1.142208, db_Student2_loss_binary_maps: 0.987736, avg_reader_cos t: 0.33718 s, avg_batch_cost: 2.14138 s, avg_samples: 10.0, ips: 4.66988 samples/s, eta: 1 day, 6:03:51 [2023/03/16 10:58:52] ppocr INFO: epoch: [4/500], global_step: 350, lr: 0.001000, dila_dbloss_Student_Teacher: 0.121063, dila_dbloss_Student2_Teacher: 0.149888, loss: 14.418106, dml_thrink_maps_0: 0.007144, db_Student_loss_shrink_ma ps: 4.932528, db_Student_loss_threshold_maps: 1.141053, db_Student_loss_binary_maps: 0.986614, db_Student2_loss_shrink_maps: 4.931944, db_Student2_loss_threshold_maps: 1.142218, db_Student2_loss_binary_maps: 0.986619, avg_reader_cos t: 0.34198 s, avg_batch_cost: 2.14578 s, avg_samples: 10.0, ips: 4.66031 samples/s, eta: 1 day, 6:02:41 [2023/03/16 10:59:14] ppocr INFO: epoch: [4/500], global_step: 360, lr: 0.001000, dila_dbloss_Student_Teacher: 0.114768, dila_dbloss_Student2_Teacher: 0.142519, loss: 14.393169, dml_thrink_maps_0: 0.006410, db_Student_loss_shrink_ma ps: 4.928962, db_Student_loss_threshold_maps: 1.146375, db_Student_loss_binary_maps: 0.985828, db_Student2_loss_shrink_maps: 4.928376, db_Student2_loss_threshold_maps: 1.147378, db_Student2_loss_binary_maps: 0.985837, avg_reader_cos t: 0.36938 s, avg_batch_cost: 2.18959 s, avg_samples: 10.0, ips: 4.56706 samples/s, eta: 1 day, 6:02:34 [2023/03/16 10:59:35] ppocr INFO: epoch: [4/500], global_step: 370, lr: 0.001000, dila_dbloss_Student_Teacher: 0.110561, dila_dbloss_Student2_Teacher: 0.135702, loss: 14.367229, dml_thrink_maps_0: 0.006696, db_Student_loss_shrink_ma ps: 4.920202, db_Student_loss_threshold_maps: 1.146687, db_Student_loss_binary_maps: 0.984104, db_Student2_loss_shrink_maps: 4.919592, db_Student2_loss_threshold_maps: 1.149370, db_Student2_loss_binary_maps: 0.984117, avg_reader_cos t: 0.34338 s, avg_batch_cost: 2.15178 s, avg_samples: 10.0, ips: 4.64731 samples/s, eta: 1 day, 6:01:36 [2023/03/16 10:59:57] ppocr INFO: epoch: [4/500], global_step: 380, lr: 0.001000, dila_dbloss_Student_Teacher: 0.104074, dila_dbloss_Student2_Teacher: 0.130746, loss: 14.357050, dml_thrink_maps_0: 0.005552, db_Student_loss_shrink_ma ps: 4.931272, db_Student_loss_threshold_maps: 1.140896, db_Student_loss_binary_maps: 0.986277, db_Student2_loss_shrink_maps: 4.930660, db_Student2_loss_threshold_maps: 1.144727, db_Student2_loss_binary_maps: 0.986284, avg_reader_cos t: 0.32097 s, avg_batch_cost: 2.12888 s, avg_samples: 10.0, ips: 4.69731 samples/s, eta: 1 day, 6:00:10 [2023/03/16 11:00:19] ppocr INFO: epoch: [4/500], global_step: 390, lr: 0.001000, dila_dbloss_Student_Teacher: 0.102839, dila_dbloss_Student2_Teacher: 0.127228, loss: 14.340802, dml_thrink_maps_0: 0.005748, db_Student_loss_shrink_ma ps: 4.920578, db_Student_loss_threshold_maps: 1.142502, db_Student_loss_binary_maps: 0.984212, db_Student2_loss_shrink_maps: 4.919618, db_Student2_loss_threshold_maps: 1.142910, db_Student2_loss_binary_maps: 0.984216, avg_reader_cos t: 0.39699 s, avg_batch_cost: 2.20500 s, avg_samples: 10.0, ips: 4.53516 samples/s, eta: 1 day, 6:00:24 [2023/03/16 11:00:33] ppocr INFO: save model in ./output/en_PP-OCR_v3_det/latest [2023/03/16 11:00:43] ppocr INFO: epoch: [5/500], global_step: 400, lr: 0.001000, dila_dbloss_Student_Teacher: 0.098955, dila_dbloss_Student2_Teacher: 0.119900, loss: 14.291090, dml_thrink_maps_0: 0.006539, db_Student_loss_shrink_ma ps: 4.901950, db_Student_loss_threshold_maps: 1.135324, db_Student_loss_binary_maps: 0.980396, db_Student2_loss_shrink_maps: 4.901190, db_Student2_loss_threshold_maps: 1.142910, db_Student2_loss_binary_maps: 0.980404, avg_reader_cos t: 0.54792 s, avg_batch_cost: 2.31522 s, avg_samples: 10.0, ips: 4.31924 samples/s, eta: 1 day, 6:02:51 eval model:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 499/500 [01:04<00:00, 7.68it/s] [2023/03/16 11:01:48] ppocr INFO: cur metric, precision: 0.0, recall: 0.0, hmean: 0, fps: 8.264265517193737
您好我也遇到了这样的问题，采用了500多张图片，训练检测，也根据您的问题，进行了尝试，无法解决，可以指教一下吗
