### ISSUE TITLE
PaddleOCR提供模型精度测试脚本吗？

### ISSUE THREAD

**Issue by likecv** [PaddlePaddle/PaddleOCR#9403]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
哪个数据集上的精度

测试脚本tools/eval.py ?

**Comment by Lebhoryi** [comment]
@LDOUBLEV L老师你好

我想跑下OCRv3 三个模型串联的精度，en 或者 ch都可以

有以下几个问题：

1、测试的数据集我该选择哪一个，目前我了解到的信息：det-icdar2015, rec-icdar2015,

    串联的模型数据集没有提及，icdar2015 中存在端到端的数据集，没有找到标签生成代码；
 
 2、测试串联模型的脚本是哪一个，目前我在看tools/end2end，但是里面好像是ocrv2版本的，不知道是否适用
