### ISSUE TITLE
使用PPOCRLabel进行标注数据的一些问题

### ISSUE THREAD

**Issue by panliang5020** [PaddlePaddle/PaddleOCR#9406]
在使用PPOCRLabel标注表格数据时,我自己标注的识别框并用重新识别出的结果,怎么导出为表格识别模型的训练数据?
自带的表格识别结果不能满足需求,怎么替换成自己想要的效果

**Comment by UserWangZz** [comment]
参考该链接
https://github.com/PaddlePaddle/PaddleOCR/blob/main/PPOCRLabel/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA
