### ISSUE TITLE
给各位老总一个建议，关于大家用pyinstaller打包exe会出现各种ModuleNotFoundError: No module named 'XXXX'

### ISSUE THREAD

**Issue by Mr-Diaolvyu** [PaddlePaddle/PaddleOCR#9408]
关于这个问题报错的地方，处理了几个，基本上都是在paddle和paddleocr目录下的py文件里。大多数都是在from A import B这个地方，将A补全为程序所在程序的完整路径（绝对路径？）都可以解决。

**Comment by LDOUBLEV** [comment]
感谢反馈，我们会看下这个问题

**Comment by kerneltravel** [comment]
@LDOUBLEV 刚提交的这PR 是根据 @Mr-Diaolvyu 的思路改的代码。看下是否符合你们的意思

**Comment by Mr-Diaolvyu** [comment]
> > 桨叶
> 
> 这个问题依然存在，请问"将A补全为程序所在程序的完整路径（绝对路径？）都可以解决。"这个是什么意思？

例如“from labelColor import label_colormap”补全为“from libs.labelColor import label_colormap”
