### ISSUE TITLE
下载模型解压缩后出现错误

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/PaddleOCR#941]
下载ch_ppocr_mobile_v1.1_rec_infer.tar后解压缩出来的不是文件夹，是不可识别的文件，wget下载也出现同样的问题，请工程师大佬检查一下，是下载文件有问题还是我有问题，谢谢

**Comment by guanfaqian** [comment]
我也遇到了
![Uploading image.png…]()

**Comment by guanfaqian** [comment]
window用7z解压不出来。就那个rec的不管是服务器版本，还是另外那个。

**Comment by TingquanGao** [comment]
@guanfaqian @upenggod 请留一下邮箱，我重新压缩了一份zip格式的文件发你们试一下。

**Comment by upenggod** [comment]
我的邮箱25310896@qq.com，谢谢

**Comment by LoeWHJ** [comment]
你好，我也遇到了相同问题，我的邮箱2642264392@qq.com,谢谢

**Comment by TingquanGao** [comment]
> 你好，我也遇到了相同问题，我的邮箱[2642264392@qq.com](mailto:2642264392@qq.com),谢谢

邮件已发，请查收。

**Comment by TingquanGao** [comment]
重新压缩的zip文件请自行下载：

[ch_ppocr_mobile_v1.1_rec_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5463451/ch_ppocr_mobile_v1.1_rec_infer.zip)
