### ISSUE TITLE
关于表格内容识别问题，PPOCR有没有去表格网格线的工具？

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9410]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

如题，网格线好像会影响检测和识别效果，PPOCR内有没有能将网格线去除的工具呢？一般传统方法的网格线去除好像效果并不是特别好。来问问各位大佬们有没有什么高见！谢谢各位！

**Comment by LDOUBLEV** [comment]
目前没有

**Comment by Mrfuhang** [comment]
兄弟你表格识别的时候有遇到一种问题嘛：识别框出来的图片精准，可是输入到excel的时候却只有部分信息
