### ISSUE TITLE
无法打开ch_PP-OCRv3_det_infer中的inference.pdmodel

### ISSUE THREAD

**Issue by mrwang-19** [PaddlePaddle/PaddleOCR#9413]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
无法打开ch_PP-OCRv3_det_infer中的inference.pdmodel，系统环境paddle2.4，cuda1.7 paddleocr2.6rc,python3.9

**Comment by andyjpaddle** [comment]
需要用visualDL打开进行可视化

**Comment by mrwang-19** [comment]
> 需要用visualDL打开进行可视化

我用python直接调用模型文件不能使用

**Comment by andyjpaddle** [comment]
怎么调用的？

**Comment by mrwang-19** [comment]
> 怎么调用的？

ocr = PaddleOCR(rec_model_dir='./ocr/rec/ch/ch_PP-OCRv3_rec_infer',det_model_dir='./ocr/det/ch/ch_PP-OCRv3_det_infer', cls_model_dir='./ocr/cls/ch_ppocr_mobile_v2.0_cls_infer')

# 读取图片
file_path = './test.png'
img = cv2.imread(file_path)

**Comment by andyjpaddle** [comment]
报的啥错误？

**Comment by mrwang-19** [comment]
就是打不开文件./ocr/det/ch/ch_PP-OCRv3_det_infer/inference.pdmodel

**Comment by mrwang-19** [comment]
> 报的啥错误？

就是打不开文件./ocr/det/ch/ch_PP-OCRv3_det_infer/inference.pdmodel

**Comment by andyjpaddle** [comment]
你截图下报错，是找不到文件，还是文件损坏？

**Comment by mrwang-19** [comment]
> 你截图下报错，是找不到文件，还是文件损坏？

 (NotFound) Cannot open file D:/mode/ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1901)

**Comment by andyjpaddle** [comment]
> D:/mode/ch_PP-OCRv3_det_infer/inference.pdmodel

路径看看是不是写的有问题？

**Comment by mrwang-19** [comment]
> > D:/mode/ch_PP-OCRv3_det_infer/inference.pdmodel
>

> > D:/mode/ch_PP-OCRv3_det_infer/inference.pdmodel
> 
> 路径看看是不是写的有问题？

路径没问题呀

**Comment by andyjpaddle** [comment]
直接使用默认参数 `ocr = PaddleOCR()`

**Comment by andyjpaddle** [comment]
应该是Windows路径问题，改成反斜扛试试 D:\mode\ch_PP-OCRv3_det_infer\inference.pdmodel

**Comment by zhanglinc** [comment]
这个问题解决了么，我也是这个情况

**Comment by zhanglinc** [comment]
> * paddleocr2.6rc重新按照官网下载paddleocr下载一次，问题应该就可以解了，

**Comment by ayiduod** [comment]
问题解决了吗，我也是这个问题

**Comment by qq61786631** [comment]
同样的问题，我是c++版本碰到的

**Comment by qq61786631** [comment]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file =/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1500)
