### ISSUE TITLE
PPOCRv3 rec模型 multihead 模型裁剪无法正常使用，FPGMFilterPruner报错

### ISSUE THREAD

**Issue by HAIMSTZL** [PaddlePaddle/PaddleOCR#9416]
对使用ch_PP-OCRv3_rec.yml训练模型，

按照官方教程运行deploy/slim/prune/sensitivity_anal.py，进行模型裁剪，

遇到无参数'out_channels_list'，和pruner = FPGMFilterPruner(model,input_shape)报错TypeError: 'NoneType' object is not subscriptable问题，这两个问题在以下issue提及，但该issue下并无正确解决方法。

out_channels_list： https://github.com/PaddlePaddle/PaddleOCR/issues/7616
FPGMFilterPruner： https://github.com/PaddlePaddle/PaddleOCR/issues/8519

out_channels_list为代码bug，参考tools/infer_rec.py文件修复
FPGMFilterPruner,经过断点调试，发现为对multihead模型，剪裁代码无法正确运行，paddleslim/core/dygraph.py/_dy2prog报错，缺失multihead相关有效参数target。

使用ch_PP-OCRv3_rec模型进行模型裁剪，该问题必现，请问如何解决

**Comment by andyjpaddle** [comment]
可以试试PACT量化或kL量化，FPGM后续不再支持了
