### ISSUE TITLE
det预测的时候。会把一个不需要的地方预测为文本区域。但实际上我的样本里都没有标注这个位置

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9421]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/det/inference/det_db_dml_inference/Student" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/test/det_imgsresult/" \
--use_gpu=True
```
- 完整报错/Complete Error Message：
det预测的时候。会把一个不需要的地方预测为文本区域（红色方框部分）。但实际上我的样本里都没有标注这个位置。是不是有文字一样的有影响？
1. 我是要把这个位置在样本中标注上吗？
2. 我尝试调了det_db_box_thresh=0.7 没有效果
3. 这种情况该怎么处理？

![image](https://user-images.githubusercontent.com/32863094/224926625-73f4de05-b4fd-4cce-bdfc-e0d339c19cde.png)

**Comment by andyjpaddle** [comment]
文字区域检测到是正常的，可以通过一定的规则进行后处理来去除不需要的结果

**Comment by rexzhengzhihong** [comment]
> 文字区域检测到是正常的，可以通过一定的规则进行后处理来去除不需要的结果

在哪个环节后处理呢？可以怎么处理？我是det+rec+ser 识别提取表单信息。

**Comment by andyjpaddle** [comment]
在OCR的结果里面过滤下不需要的检测框
