### ISSUE TITLE
对手写英文和数字混合图像的识别效果不太好

### ISSUE THREAD

**Issue by 0-Maxwei-0** [PaddlePaddle/PaddleOCR#9423]
![1](https://user-images.githubusercontent.com/72435377/224939793-a29a94ab-4daa-49a4-a1dd-24577e284115.jpg)
请问有什么好的解决方案吗

**Comment by andyjpaddle** [comment]
增加数据进行finetune

**Comment by 0-Maxwei-0** [comment]
> 

这种一般添加多少数据比较合适呢？

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md

**Comment by super-tian** [comment]
这种文字检测模型也要单独训练一个吧
