### ISSUE TITLE
我先做单个文字（汉字）的识别，不需要序列文字识别，应该选用哪个配置文件呢

### ISSUE THREAD

**Issue by ic1031** [PaddlePaddle/PaddleOCR#9425]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
目前没有单独的单字识别模型，可以自己直接训练一个分类模型

**Comment by 01000100GT** [comment]
CRAFT 可以做单字
