### ISSUE TITLE
Add DB++ support in PaddleOCR

### ISSUE THREAD

**Issue by letmerecall** [PaddlePaddle/PaddleOCR#9428]
## What's the suggestion

PaddleOCR class in [paddleocr.py](https://github.com/PaddlePaddle/PaddleOCR/blob/9c22490f958f42b6c7f88f42374a78addb7e75dd/paddleocr.py) support only **DB** detection model as of now. Since now we have support for **DB++** in main detection class, it should be straightforward to add it support here.

https://github.com/PaddlePaddle/PaddleOCR/blob/9c22490f958f42b6c7f88f42374a78addb7e75dd/paddleocr.py#L49

## How to implement it

It might be as simple as updating `SUPPORT_DET_MODEL` list to `["DB", "DB++" ]`.

https://github.com/PaddlePaddle/PaddleOCR/blob/9c22490f958f42b6c7f88f42374a78addb7e75dd/paddleocr.py#L49

**Comment by andyjpaddle** [comment]
In paddleocr.py, we only support pp-series model(PP-OCRv2 PP-OCRv3, etc), if you want use other models, you can add it by yourself and rebuild.
