### ISSUE TITLE
Configuring ocr_det while using hub server

### ISSUE THREAD

**Issue by qlee01** [PaddlePaddle/PaddleOCR#943]
Hi, thanks for the great library. Is there any way to configure the ocr_det module while using hub server? I want to pass parameters like "det_db_thresh", "det_db_box_thresh", ... into the service, but cannot figure out how to add them to a config.json.
Thanks for help!

**Comment by littletomatodonkey** [comment]
Thanks for your attention, actually you can specify the parameters here as you want.

https://github.com/PaddlePaddle/PaddleOCR/blob/0fac210b8535d114c2cfa73df3aca93c882724db/deploy/hubserving/ocr_det/params.py#L20

**Comment by qlee01** [comment]
Thanks, this woks good! However, would be nicer to pass in the config values with the external json config, in order not to change any code from the repo locally. Would this be possible?
