### ISSUE TITLE
Loading english number recognition in python

### ISSUE THREAD

**Issue by R-N** [PaddlePaddle/PaddleOCR#9430]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

There's a [pretrained english number model](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/models_list_en.md#22-english-recognition-model) provided. But I can't seem to use it with the library. How should I do this?

- 系统环境/System Environment：Google Colab
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：PaddleOCR(use_angle_cls=True, lang='en_number') 
- 完整报错/Complete Error Message：param lang must in dict_keys(['ch', 'en', 'korean', 'japan', 'chinese_cht', 'ta', 'te', 'ka', 'latin', 'arabic', 'cyrillic', 'devanagari']), but got en_number

**Comment by andyjpaddle** [comment]
just use `lang='en'`

**Comment by R-N** [comment]
It loads the general english model. It often misrecognizes dot as
inclination mark (!) and 1 as 7 or 2 due to the background. The number is
float
