### ISSUE TITLE
Recommended Input Image Shape

### ISSUE THREAD

**Issue by Taghreed7878** [PaddlePaddle/PaddleOCR#9432]
Hello there,
I'm trying to reduce inference time on CPU by reducing the input image dimensions, and It actually showed a significant difference when I reduced an image dimensions from 1925*1325 to 350*320. The original dimensions cost 63 seconds when I tried it, but the new reduced dimensions took only 3 seconds. 

But of course, it does not necessarily work for any input image. So, I'm wondering if there is a recommended standard size that can work well in general. 
And there is another thing, Does your pipeline resize automatically within a scale?
Thanks in advance

**Comment by andyjpaddle** [comment]
in det model, the input shape usually is 960x960, in rec model, the input shape is 32x480
