### ISSUE TITLE
表格识别评估错误

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#9436]
【求大神指点】表格识别模型TEDS指标复现错误，发现评估过程中，并未把ocr识别结果加入pre_html。（多次重新拉了2.6分支尝试仍然如此）
- 版本号/Version：Paddle：2.2.0  PaddleOCR：release2.6
- 运行指令/Command Code：python ./ppstructure/table/eval_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=inference/en_ppocr_mobile_v2.0_table_structure_infer --image_dir=./doc/table/PMC1963449_004_02.png --rec_char_dict_path=./ppocr/utils/dict/table_dict.txt --table_char_dict_path=./ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --det_limit_type=min --rec_image_shape=3,32,320 --gt_path=../pubtabnet/PMC1963449_004_02.txt
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/83860013/225176273-ea33500d-6a9d-4568-a4c4-c74311a4223a.png)

**Comment by andyjpaddle** [comment]
image_dir应该是文件夹路径
gt 示例 `PMC5755158_010_01.png	<html><body><table><thead><tr><td></td><td><b>Weaning</b></td><td><b>Week 15</b></td><td><b>Off-test</b></td></tr></thead><tbody><tr><td>Weaning</td><td>–</td><td>–</td><td>–</td></tr><tr><td>Week 15</td><td>–</td><td>0.17 ± 0.08</td><td>0.16 ± 0.03</td></tr><tr><td>Off-test</td><td>–</td><td>0.80 ± 0.24</td><td>0.19 ± 0.09</td></tr></tbody></table></body></html>
`
评估参考下面代码：
`python table/eval_table.py --det_model_dir=../inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=../inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=../inference/en_ppstructure_mobile_v2.0_SLANet_infer --image_dir=./ --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --gt_path=test_gt.txt`

**Comment by s957995299** [comment]
> image_dir应该是文件夹路径 gt 示例 `PMC5755158_010_01.png <html><body><table><thead><tr><td></td><td><b>Weaning</b></td><td><b>Week 15</b></td><td><b>Off-test</b></td></tr></thead><tbody><tr><td>Weaning</td><td>–</td><td>–</td><td>–</td></tr><tr><td>Week 15</td><td>–</td><td>0.17 ± 0.08</td><td>0.16 ± 0.03</td></tr><tr><td>Off-test</td><td>–</td><td>0.80 ± 0.24</td><td>0.19 ± 0.09</td></tr></tbody></table></body></html> ` 评估参考下面代码： `python table/eval_table.py --det_model_dir=../inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=../inference/en_ppocr_mobile_v2.0_table_rec_infer --table_model_dir=../inference/en_ppstructure_mobile_v2.0_SLANet_infer --image_dir=./ --rec_char_dict_path=../ppocr/utils/dict/table_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --det_limit_side_len=736 --gt_path=test_gt.txt`

没有，我是以一张为示例，评估一张的TEDS。评估整个验证集的也是同样的错误，未把ocr识别结果加入pre_html，导致TEDS很低
