### ISSUE TITLE
在做会计单据信息的提取。现在测试一张单据一个模型没问题。但是一个模型就要占用一定的gpu显存。能把所有的单据放在一个模型里训练吗？？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9438]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![zzszyfp_5](https://user-images.githubusercontent.com/32863094/225181254-f3ba551c-bb9d-4534-8ecb-50dbb2a5d86c.jpg)
![yzhyhd](https://user-images.githubusercontent.com/32863094/225181273-36654753-fc33-40aa-bfc2-09ade540fe13.jpg)
![yhzyhd2](https://user-images.githubusercontent.com/32863094/225181293-41c8158b-0a9b-4e06-895e-db6cb0ef8aec.jpg)

**Comment by tink2123** [comment]
可以放在一起训练

**Comment by rexzhengzhihong** [comment]
加一张就要重新训练吗？

**Comment by rexzhengzhihong** [comment]
> > 加一张就要重新训练吗？
> 
> 数据集最好覆盖更多一点，兄弟你的发票数量1能识别到吗，我的识别不了1

我也是1或者个，人，这种简单的字会识别不到

**Comment by rexzhengzhihong** [comment]
> 可以放在一起训练

那标签会非常多，这样会有问题吗？

**Comment by rexzhengzhihong** [comment]
> > 加一张就要重新训练吗？
> 
> 数据集最好覆盖更多一点，兄弟你的发票数量1能识别到吗，我的识别不了1

那没张单据的关键信息不一样，那class_list会非常多？怎么处理的？
