### ISSUE TITLE
训练模型acc为0.99，框出来的结果也非常精准，但是识别出来的结果却只有一部分(这一部分也准确)

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9440]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos7
- 版本号/Version：Paddle： 2.4.2 PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 训练出来的模型的acc：0.9999
使用模型进行推理表格图片，看到图片都被正确标注，但是识别出来的xlsx结果却只有一部分，请问这是为什么啊？

**Comment by Mrfuhang** [comment]
![image](https://user-images.githubusercontent.com/29907548/225187539-ecb829b3-30ec-4679-92ef-fd3e8909ec9c.png)

**Comment by rpsipl2021** [comment]
@Mrfuhang can you please show me sample dataset file, is it .txt or .jsonl file?
and how's the format of it?

**Comment by Mrfuhang** [comment]
> @Mrfuhang can you please show me sample dataset file, is it .txt or .jsonl file? and how's the format of it?

I have solved it，There's something wrong with my annotated data。

**Comment by rpsipl2021** [comment]
@Mrfuhang I can't figure out what's wrong in my dataset
![sample](https://user-images.githubusercontent.com/113658786/225267033-17fde4be-c8a2-4e02-9693-524ac74cc7be.png)

**Comment by Mrfuhang** [comment]
> @Mrfuhang I can't figure out what's wrong in my dataset ![sample](https://user-images.githubusercontent.com/113658786/225267033-17fde4be-c8a2-4e02-9693-524ac74cc7be.png)

There is a problem with your data annotation

**Comment by nissansz** [comment]
这个表格部分不需要切割出来再标注，训练吗？
