### ISSUE TITLE
C++调用自己训练的识别模型，具体的参考的文本或者案例可以提供链接吗？

### ISSUE THREAD

**Issue by 5204AIO** [PaddlePaddle/PaddleOCR#9445]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
可以参考C++部署案例：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme_ch.md

**Comment by raoyutian** [comment]
可以参考https://gitee.com/raoyutian/paddle-ocrsharp，C已经封装好的C++的动态库，直接调用即可使用。
