### ISSUE TITLE
文字检测任务中，在哪里修改检测网络的输入图像大小

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9446]
我想知道输入到文字检测网络的默认图像大小是多大？

**Comment by guiniao** [comment]
以MobileNetV3为例，在对应的yml配置文件中，Train下面的EastRandomCropData.size中指定图片大小

**Comment by tink2123** [comment]
训练时默认640

**Comment by luoyq6** [comment]
> 推理呢？是960？

**Comment by luoyq6** [comment]
> > 推理呢？是960？



> 训练时默认640

这个是推理的输入大小吗？
![image](https://user-images.githubusercontent.com/110521846/225574581-46462dab-9cb4-4cab-9762-5625f013192a.png)

**Comment by tink2123** [comment]
是的，推理时会按长边或短边等比例缩放，推理时是变长的
