### ISSUE TITLE
predict_system.py如何修改为日语文字识别(inference)

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleOCR#945]
你好，我想看一下日本语inference的效果(包括文字检测和识别)。
我参照了python inference说明部分，predict_rec.py那个脚本是可以直接运行日本语识别结果的。
但貌似predict_system.py不能直接使用，
求问需要做什么修改吗？

**Comment by tink2123** [comment]
predict_system.py 也是可以的，在predict_rec.py 的基础上，添加检测的模型路径即可。
```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/japan_1.jpg" --det_model_dir="./det inference model dir" --rec_model_dir="./your inference model" --rec_char_type="japan" --rec_char_dict_path="ppocr/utils/dict/japan_dict.txt" --vis_font_path="doc/japan.ttf"
```

**Comment by terrancraft** [comment]
谢谢大佬，已经搞定。
我找了数张日文图片预测了一下，发现竖向和斜向排列的文字预测不太准。
我需要自己重新训练日文的方向分类器吗(这部分理论还不太懂)。

**Comment by tink2123** [comment]
现在的训练样本里没有加入竖向的样本，所以对竖排样本效果较差，我们正在优化中。如果您自己有竖排和倾斜样本的话，可以基于我们的模型finetune，效果会有很大提升。

**Comment by terrancraft** [comment]
了解，谢谢大佬
