### ISSUE TITLE
我训练代码出现了问题：Electron框架中的一个警告信息，意味着在渲染进程中加载非上下文感知的本机模块已经被弃用，并且在将来的某个时候将停止工作。

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9450]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：D:\ocr_table\PaddleOCR-dygraph>D:/ocr_table/PaddleOCR-dygraph/tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml
- 完整报错/Complete Error Message：

(ppocr3) D:\ocr_table\PaddleOCR-dygraph>D:/ocr_table/PaddleOCR-dygraph/tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv
3_det_cml.yml

(ppocr3) D:\ocr_table\PaddleOCR-dygraph>
[main 2023-03-15T10:27:23.662Z] update#setState idle
(node:19400) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:19400) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:19400) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:19400) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:19188) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:19188) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working
 at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

出现以上问题导致模型无法正常训练，应该如何解决呢？

**Comment by phb-shiyige-fw** [comment]
@tink2123 @ZeyuChen @sdcb

**Comment by phb-shiyige-fw** [comment]
@WenmuZhou  希望能帮忙解决一下问题 谢谢 那个18397 实在是没办法看明白

**Comment by LDOUBLEV** [comment]
不太明白你训练OCR任务为什么会出现js报错的问题
