### ISSUE TITLE
Creating lite, small or medium versions of inference models

### ISSUE THREAD

**Issue by danielvfung** [PaddlePaddle/PaddleOCR#9452]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/9281

<div type='discussions-op-text'>

<sup>Originally posted by **danielvfung** March  2, 2023</sup>
I managed to create the inference versions of the SAST, DB++ and even DB det_algorithms as per the instructions on the Paddle Docs.
They all seem to segment words better than the default en_PP-OCRv3 lite weight model.
The inference models i created using the export script are all 100 MB and larger. my question is how can we generate small sized models say medium, or smaller sized to be used for inference but still get the detection levels that these algorithms provide over the default line block level detection.
</div>

**Comment by LDOUBLEV** [comment]
The size of the model is directly related to the number of parameters in the model. 
There is currently no way to reduce its size.
But you can retrain the model with a smaller backbone

Here is a model with a smaller backbone, the model size is small, but the accuracy is slightly lower.
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/algorithm_det_db_en.md
![image](https://user-images.githubusercontent.com/26592129/225799685-b15bc5c7-8501-4250-aa7f-97eda72eaf09.png)
