### ISSUE TITLE
pip install paddleocr 安装的时候 protobuf 版本冲突

### ISSUE THREAD

**Issue by agnarsong** [PaddlePaddle/PaddleOCR#9453]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：

macOS Monterey
Apple M1 Pro

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：

paddlepaddle==2.3.2
参考 https://zhuanlan.zhihu.com/p/609496068 文档安装 PaddleOCR，并未指定版本

- 运行指令/Command Code：

pip install paddleocr

- 完整报错/Complete Error Message：

安装时候的异常：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.3.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.

若无视这个问题直接使用paddleocr，也会报错：

(paddleocr_env)➜  PaddleOCR git:(release/2.6) python
Python 3.9.16 (main, Mar  8 2023, 04:29:44)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddleocr import PaddleOCR

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/tools/infer/predict_system.py", line 33, in <module>
    import tools.infer.predict_det as predict_det
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/tools/infer/predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/ppocr/data/__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/ppocr/data/imaug/__init__.py", line 47, in <module>
    from .ct_process import *
  File "/Users/dl00038ml/PKG/projects/python/PaddleOCR/ppocr/data/imaug/ct_process.py", line 22, in <module>
    import Polygon as plg
ModuleNotFoundError: No module named 'Polygon'

**Comment by guiniao** [comment]
我也有这个冲突，不过我使用PaddleOCR好像没报错，所以直接忽略了

**Comment by agnarsong** [comment]
我使用的时候报错了：

ModuleNotFoundError: No module named 'Polygon'

尝试过卸载 protobuf 3.20.3，并且是新开的env来安装它的。
会报同样的错误，所以protobuf 这个扩展版本冲突，是 执行pip install paddleocr 的时候，它内部依赖所使用的 protobuf 版本冲突导致的。这个需要官方出手帮忙了

**Comment by tink2123** [comment]
可以先手动安装protobuf来避免这个问题， pip install protobuf==3.20.0

> ModuleNotFoundError: No module named 'Polygon'

是因为相关依赖没有安装成功，可以手动安装 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/requirements.txt

**Comment by xiabaoyulo** [comment]
我完美解决了这个问题，给大家分享一下，我是最新paddlepaddle-gpu=2.4.2版本加paddleocr=2.6版本；paddlepaddle要求的protobuf<=3.20.0，但是直接pip install paddleocr会导致protobuf版本变成3.20.3；
原因：是paddleocr依赖于visualdl，而visualdl依赖于onnx；onnx依赖于protobuf，前面两次依赖都没有指定版本，导致onnx安装了最新的1.13.1版本，而安装这个版本的onnx会导致protobuf版本升高到3.20.3
解决办法：安装paddleocr之前先按照顺序安装protobuf==3.20.0，再安装onnx==1.12.0或者1.11.0

**Comment by xiabaoyulo** [comment]
补充一下：我用conda安装protobuf==3.20.0和onnx==1.12.0冲突了，建议用1.11.0吧

**Comment by axuu** [comment]
> 我完美解决了这个问题，给大家分享一下，我是最新paddlepaddle-gpu=2.4.2版本加paddleocr=2.6版本；paddlepaddle要求的protobuf<=3.20.0，但是直接pip install paddleocr会导致protobuf版本变成3.20.3； 原因：是paddleocr依赖于visualdl，而visualdl依赖于onnx；onnx依赖于protobuf，前面两次依赖都没有指定版本，导致onnx安装了最新的1.13.1版本，而安装这个版本的onnx会导致protobuf版本升高到3.20.3 解决办法：安装paddleocr之前先按照顺序安装protobuf==3.20.0，再安装onnx==1.12.0或者1.11.0

感谢，已经解决问题。顺便吐槽一下paddleocr连依赖这种问题都解决不好。

**Comment by haonit** [comment]
> onnx==1.12.0

就这，还天天all in AI呢？

**Comment by liqijie1** [comment]
> 我完美解决了这个问题，给大家分享一下，我是最新paddlepaddle-gpu=2.4.2版本加paddleocr=2.6版本；paddlepaddle要求的protobuf<=3.20.0，但是直接pip install paddleocr会导致protobuf版本变成3.20.3； 原因：是paddleocr依赖于visualdl，而visualdl依赖于onnx；onnx依赖于protobuf，前面两次依赖都没有指定版本，导致onnx安装了最新的1.13.1版本，而安装这个版本的onnx会导致protobuf版本升高到3.20.3 解决办法：安装paddleocr之前先按照顺序安装protobuf==3.20.0，再安装onnx==1.12.0或者1.11.0

感谢，已解决
