### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch.  不是之前的常规问题

### ISSUE THREAD

**Issue by Aurora-Rong** [PaddlePaddle/PaddleOCR#9455]
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [6, 96, 3, 12] and the shape of Y = [6, 96, 4, 12]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_add > error]

按照你们之前的回答：
已经修改过[preprocess_op.cpp]这个文件了，而且测试图片的宽高都改成了32的倍数，
还是不行，求解答

**Comment by WenmuZhou** [comment]
跑的啥命令
