### ISSUE TITLE
能检测到文字框，模型识别不了

### ISSUE THREAD

**Issue by guiniao** [PaddlePaddle/PaddleOCR#9458]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
文字检测，检测模型能检测到框，识别模型识别不了，因为什么

**Comment by Mrfuhang** [comment]
因为你标注的数据有问题

**Comment by MissPenguin** [comment]
可以具体描述下吗？用的什么模型，什么命令，官方模型还是自己训练的，等等

**Comment by MissPenguin** [comment]
以及“识别不了”是什么意思，都识别错了？方便的话可以贴几个示例
