### ISSUE TITLE
关于训练问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleOCR#946]
请教一下：我使用通用中文模型作为预训练模型，更改了字典文件，在训练的时候会出现如下红框报错。请问是什么原因呢？
![image](https://user-images.githubusercontent.com/43515926/96207904-eec3f080-0f9e-11eb-9268-a01a0d33abd7.png)

**Comment by tink2123** [comment]
修改了字典之后，识别模型的最后一层FC纬度发生了改变，没有办法加载参数。这里是一个警告，可以忽略，正常训练即可。

**Comment by zcswdt** [comment]
> 修改了字典之后，识别模型的最后一层FC纬度发生了改变，没有办法加载参数。

谢谢，已经在训练了，不过30万数据需要训练多少个epoch呢？

**Comment by littletomatodonkey** [comment]
想要比较好的效果的话，建议300-500epoch

**Comment by zcswdt** [comment]
> 想要比较好的效果的话，建议300-500epoch

您好，周末的时间在训练，大概训练了43个epoch，程序自己停了，也没报错。还有就是训练的Loss一般降到多少比较合适？
![image](https://user-images.githubusercontent.com/43515926/96393102-cb907f80-11f0-11eb-9fe4-4a932ebb4ab6.png)

**Comment by MissPenguin** [comment]
看log训练是正常的，自动挂掉的问题是否稳定复现呢，建议拉取2.1分支最新代码试试，如果仍有问题，欢迎重新提issue。
