### ISSUE TITLE
改进空格的辨识度

### ISSUE THREAD

**Issue by skwskwskwskw** [PaddlePaddle/PaddleOCR#9462]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleOCR
- 运行指令/Command Code：ocr = PaddleOCR(lang=lang,  use_angle_cls = True, show_log = False, enable_mkldnn=True)
- 完整报错/Complete Error Message：
原图
![image](https://user-images.githubusercontent.com/7208012/225707762-bd57773d-90ee-4c09-aca7-5562a43b0521.png)

辨识后
![image](https://user-images.githubusercontent.com/7208012/225707880-99fb2a7a-83b6-488e-82a7-f3b434f3816a.png)
如何改进空格的辨识度？

**Comment by similang** [comment]
用了use_dilation = True; 还是有不完美处

**Comment by MissPenguin** [comment]
默认使用的中文模型，可以指定为英文数字模型试试，空格上的效果可能会好一点

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
