### ISSUE TITLE
StyleText 不能生成数字

### ISSUE THREAD

**Issue by Tavish77** [PaddlePaddle/PaddleOCR#9463]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：[StyleText]

希望可以生成数字，输入数字生成的都是一些奇怪的字符
![ApplicationFrameHost_6648NuA1L4](https://user-images.githubusercontent.com/126149709/225802467-eaf9cd3f-7f8f-4a67-ba58-b1af6bc82948.png)

**Comment by MissPenguin** [comment]
StyleText目前效果确实有缺陷，还在优化中，欢迎持续关注🌹
