### ISSUE TITLE
怎么做才能做到识别方块勾选的字符

### ISSUE THREAD

**Issue by zlei0251** [PaddlePaddle/PaddleOCR#9466]
怎么做才能识别方块勾选这样的字符，如图中的这样的情况，怎么才能将识别像图中□中打钩的字符
![image](https://user-images.githubusercontent.com/99624878/225874127-1d3276ac-9402-440b-ba52-aad8f1c98f4d.png)

**Comment by MissPenguin** [comment]
楼上的方案可以尝试～

**Comment by xiongchun** [comment]
如果是手工打钩，打钩有点不是很规则，形状多样的呢？请问这种情况有啥处理思路嘛？谢谢。

**Comment by zlei0251** [comment]
@xiongchun 如果对☑字符进行重新训练的话，训练的材料里就需要包含各式各样的手写☑，其中就包括你这里的不规则的这种符号，其他的交给模型自己就行了。

**Comment by JiLisx** [comment]
Hello，请问po主最后怎么解决的这个问题，我有一些复选框是图中这样的，想请教您我现在应该什么思路训练呢

<img width="512" height="115" alt="Image" src="https://github.com/user-attachments/assets/168fb5ae-778f-4fd4-a72f-37412bf1bd9a" />
