### ISSUE TITLE
protobuf version conflict (pip)

### ISSUE THREAD

**Issue by Existance29** [PaddlePaddle/PaddleOCR#9468]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
Installing paddlepaddle and paddleocr:
```
python3 -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

pip3 install "paddleocr>=2.0.1"
```
This leads to a version conflict of protobuf, as different versions of protobuf are required for onnx (a dependency) and paddlepaddle
paddlepaddle requires protobuf <=3.20.0, > 3.1.0, but onnx requires protobuf < 4, >= 3.20.2

For me, downgrading protobuf to 3.20.0 works fine, I havent tested it yet with 3.20.2, but there could be issues that I haven't noticed yet

- 系统环境/System Environment：MacOS (intel)
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：onnx: 1.13.1, visualdl: 2.5.1
- 运行指令/Command Code：Described above
- 完整报错/Complete Error Message：N.A.

**Comment by derek8bai** [comment]
Is there a way to get around this right now? Which paddlepaddle and paddleocr versions are compatible?

**Comment by derek8bai** [comment]
I ended up installing these versions. 

pip install paddlepaddle==2.3.1
pip install paddleocr==2.6.1.2
pip install "numpy<1.24.0"

Works best on amd architecture instead of arm
