### ISSUE TITLE
用C++ openvino部署paddleOCR在debug下会报错，release下不报错

### ISSUE THREAD

**Issue by WeekZero** [PaddlePaddle/PaddleOCR#9474]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 检测模型：ch_PP-OCRv3
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...dows\runtime\bin\intel64\Debug\openvino_intel_cpu_plugind.dll
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\vector
Line: 1501

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Comment by WeekZero** [comment]
安装的是vs2022社区版，报了一个vs2019专业版的错误？

**Comment by LDOUBLEV** [comment]
参考FASTDeploy里的openvino 部署，https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/cpu-gpu

**Comment by yao-xiaofei** [comment]
> 安装的是vs2022社区版，报了一个vs2019专业版的错误？

遇到了同样的问题
