### ISSUE TITLE
训练表格识别过程中会训练OCR吗？

### ISSUE THREAD

**Issue by tianyongliu** [PaddlePaddle/PaddleOCR#9475]
我再训练表格识别模型的过程中，OCR是同步训练的吗，还是直接用的内置的OCR模型？
如果我需要改进OCR，是不是要自己训练OCR模型，然后修改表格识别配置文件中的模型和字典的路径？或者还有什么需要注意的，谢谢！

**Comment by LDOUBLEV** [comment]
使用的内置的OCR模型；

> 是不是要自己训练OCR模型，然后修改表格识别配置文件中的模型和字典的路径

是的，没太多需要注意的事项，你训练遇到问题的时候可以提出来看下

**Comment by tianyongliu** [comment]
好的，感谢回复
