### ISSUE TITLE
 File does not exist 'resources.qrc'

### ISSUE THREAD

**Issue by bihailantian655** [PaddlePaddle/PaddleOCR#9477]
安装完成后 运行提示  

E:\COMPILE\PYTHON\python381064\Scripts\pyrcc5: File does not exist 'resources.qrc'
Traceback (most recent call last):
  File "D:\Desktop\GIT3\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 2837, in <module>
    assert output == 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
AssertionError: operate the cmd have some problems ,please check  whether there is a in the lib directory resources.py

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.

python 3.8  64 位 ，amd 平台  cpu ，无独显。

python D:\Desktop\GIT3\PaddleOCR\PPOCRLabel\PPOCRLabel.py --lang ch

 pip install -r D:\Desktop\GIT3\PaddleOCR\PPOCRLabel\requirements.txt

**Comment by bihailantian655** [comment]
python -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by LDOUBLEV** [comment]
> E:\COMPILE\PYTHON\python381064\Scripts\pyrcc5: File does not exist 'resources.qrc'

重新安装pyqt5试试

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour > is the source of the following dependency conflicts.
> paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.

将protobuf降低到2.32.0试试呢

**Comment by bihailantian655** [comment]
Package               Version
--------------------- -----------
aiofiles              23.1.0
aiohttp               3.8.4
aiosignal             1.3.1
altair                4.2.2
anyio                 3.6.2
astor                 0.8.1
async-timeout         4.0.2
attrdict              2.0.1
attrs                 22.2.0
Babel                 2.12.1
bce-python-sdk        0.8.79
beautifulsoup4        4.11.2
Brotli                1.0.9
cachetools            5.3.0
certifi               2022.12.7
cffi                  1.15.1
charset-normalizer    3.1.0
click                 7.1.2
colorama              0.4.6
contourpy             1.0.7
cssselect             1.2.0
cssutils              2.6.0
cycler                0.11.0
Cython                0.29.33
decorator             5.1.1
entrypoints           0.4
et-xmlfile            1.1.0
fastapi               0.95.0
ffmpy                 0.3.0
filelock              3.10.0
fire                  0.5.0
Flask                 2.2.3
flask-babel           3.0.1
fonttools             4.39.2
frozenlist            1.3.3
fsspec                2023.3.0
future                0.18.3
gevent                22.10.2
geventhttpclient      2.0.2
gradio                3.22.1
greenlet              2.0.2
grpcio                1.51.3
h11                   0.14.0
httpcore              0.16.3
httpx                 0.23.3
huggingface-hub       0.13.2
idna                  3.4
imageio               2.26.0
imgaug                0.4.0
importlib-metadata    6.1.0
importlib-resources   5.12.0
itsdangerous          2.1.2
Jinja2                3.1.2
jsonschema            4.17.3
kiwisolver            1.4.4
lazy_loader           0.1
linkify-it-py         2.0.0
lmdb                  1.4.0
lxml                  4.9.2
markdown-it-py        2.2.0
MarkupSafe            2.1.2
matplotlib            3.7.1
mdit-py-plugins       0.3.3
mdurl                 0.1.2
mpmath                1.3.0
multidict             6.0.4
networkx              3.0
numpy                 1.24.2
onnx                  1.13.1
opencv-contrib-python 4.6.0.66
opencv-python         4.6.0.66
openpyxl              3.1.2
opt-einsum            3.3.0
orjson                3.8.7
packaging             23.0
paddle-bfloat         0.1.7
paddleocr             2.6.1.3
paddlepaddle          2.4.2
pandas                1.5.3
pdf2docx              0.5.6
Pillow                9.4.0
pip                   23.0.1
pkgutil_resolve_name  1.3.10
premailer             3.10.0
                                                                                           protobuf              3.20.0
psutil                5.9.4
pyclipper             1.3.0.post4
pycparser             2.21
pycryptodome          3.17
pydantic              1.10.6
pydub                 0.25.1
PyMuPDF               1.20.2
pyparsing             3.0.9
PyQt5                 5.15.4
pyqt5-plugins         5.15.4.2.2
PyQt5-Qt5             5.15.2
PyQt5-sip             12.11.1
pyqt5-tools           5.15.4.3.2
pyrsistent            0.19.3
python-dateutil       2.8.2
python-docx           0.8.11
python-dotenv         1.0.0
python-multipart      0.0.6
python-rapidjson      1.10
pytz                  2022.7.1
PyWavelets            1.4.1
PyYAML                6.0
qt5-applications      5.15.2.2.2
qt5-tools             5.15.2.1.2
rapidfuzz             2.13.7
rarfile               4.0
requests              2.28.2
rfc3986               1.5.0
scikit-image          0.20.0
scipy                 1.9.1
setuptools            67.3.3
shapely               2.0.1
six                   1.16.0
sniffio               1.3.0
soupsieve             2.4
starlette             0.26.1
sympy                 1.11.1
termcolor             2.2.0
tifffile              2023.3.15
toolz                 0.12.0
tqdm                  4.65.0
tritonclient          2.31.0
typing_extensions     4.5.0
uc-micro-py           1.0.1
urllib3               1.26.15
uvicorn               0.21.1
visualdl              2.5.1
websockets            10.4
Werkzeug              2.2.3
wheel                 0.38.4
x2paddle              1.4.0
xlrd                  1.2.0
yarl                  1.8.2
zipp                  3.15.0
zope.event            4.6
zope.interface        6.0

**Comment by bihailantian655** [comment]
pip 列表    这样还是一样报错

**Comment by panliang5020** [comment]
https://blog.csdn.net/weixin_45654405/article/details/107650754

**Comment by bihailantian655** [comment]
解决了 ，但是 中间过程 有几个库 还是需要手动安装
