### ISSUE TITLE
表格识别模型的SLANet_ch模型微调结果不良的优化途径

### ISSUE THREAD

**Issue by panliang5020** [PaddlePaddle/PaddleOCR#9481]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：表格识别
 

使用根据ppocrlabel表格标注教程标注的70余张图片,尝试对slanet_ch模型进行微调,效果如图,出现了定位框偏移,不准确的问题,后续改如何优化
![infer](https://user-images.githubusercontent.com/51695693/226283418-f5ffdc9a-62b4-4387-b2f5-888836f486b0.jpg)
![infer1](https://user-images.githubusercontent.com/51695693/226283501-4aa87c10-320d-4844-9c1b-fdecab8d23cc.png)

**Comment by Mrfuhang** [comment]
你这种识别出来应该不碍事吧 ，这是它自动给你标了个大概吧 实际上还是可以识别出来的啊
