### ISSUE TITLE
请问PaddleOCR有数学公式的识别吗？如果没有，有办法将物理公式识别为figure吗？

### ISSUE THREAD

**Issue by winnietyz** [PaddlePaddle/PaddleOCR#9483]
![show_0](https://user-images.githubusercontent.com/68419053/226353280-27f0286f-b4cf-4dcb-8ea1-de0b799a38b1.jpg)

**Comment by MissPenguin** [comment]
PaddleOCR中目前只有一种手写公式识别算法：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_can.md

如果想要将公式识别为figure，需要补充一些训练数据微调训练，因为开源的模型基于PubLayNet，其中没有公式这一类，所以无法识别
