### ISSUE TITLE
Word-level bounding boxes

### ISSUE THREAD

**Issue by Taghreed7878** [PaddlePaddle/PaddleOCR#9485]
Is there any way to get bounding boxes of words instead of lines?

**Comment by NaumanHSA** [comment]
Using multi-language model for detection will give you word level boxes. I faced this issue while key value extraction, because the line boxes would enclose keys and values in one box.

**Comment by Taghreed7878** [comment]
> Using multi-language model for detection will give you word level boxes. I faced this issue while key value extraction, because the line boxes would enclose keys and values in one box.

When I set "det_algorithm" to "Multilingual_PP-OCRv3_det_slim_infer" I got an error says: det_algorithm must be in ["DB"]

**Comment by NaumanHSA** [comment]
You just need to do some modifications in paddleocr.py script. Just pass an extra parameter `det_lang='ml'` to the PaddleOCR class. Then in the PaddleOCR __init__ method, add following lines right after parse_lang() method call.

```
 if params.det_lang is not None:
     det_lang = params.det_lang
```

Hopefully, it will then work for you. Good Luck.

**Comment by Taghreed7878** [comment]
> You just need to do some modifications in paddleocr.py script. Just pass an extra parameter `det_lang='ml'` to the PaddleOCR class. Then in the PaddleOCR **init** method, add following lines right after parse_lang() method call.
> 
> ```
>  if params.det_lang is not None:
>      det_lang = params.det_lang
> ```
> 
> Hopefully, it will then work for you. Good Luck.

It worked properly! thank you a lot

**Comment by NaumanHSA** [comment]
@Taghreed7878 Good to hear that.

**Comment by Taghreed7878** [comment]
After I tried more test cases I found that multi-lingual model does not strictly extract words separately from each other.

**Comment by jyotiyadav94** [comment]
is it necessary to change in paddleocr.py script can't we directly call through the parameter 
ocr = paddleocr.PaddleOCR(det_lang='ml')?
could you please share some ideas on how did you make it work ?

**Comment by NaumanHSA** [comment]
@jyotiyadav94 Yes you are right, this may not be the perfect solution, consider this as a workaround to get word level boxes. I found it useful, it is possible that the ml model has been trained on a dataset which contains word level annotations. Sorry, I've not done more research on the dataset.

About the parameters thing, if I remember correctly, there's a function in the PaddleOCR script which return the detection language based on the recognition language. That's why I explicitly forced the script to use 'en' and 'ml' combination. You can div deep into the code to check if it's possible with params, but I don't think so.

**Comment by mobassir94** [comment]
@NaumanHSA whatever you are asking to do i can see it's already there since last 5-6 months https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py#L382

i was using latest version pip install paddleocr==2.6.1.3 and even after setting det_lang='ml' i am getting sentence  level detection,,,however  if i set det_lang='ar' then i get word level but can't recognize english,,,the system recognizes english as arabic,so you are right that "About the parameters thing, if I remember correctly, there's a function in the PaddleOCR script which return the detection language based on the recognition language. That's why I explicitly forced the script to use 'en' and 'ml' combination."

however how do  you install paddleocr and do detection in word level and recognition in preferred language,if you provide full step by step guideline with code,then it will be helpful for others,thanks

**Comment by NaumanHSA** [comment]
@mobassir94 
I've mentioned it earlier already. There's a function called in the PaddleOCR init method, which actually takes params.lang (recognition langugae), and based on that, it returns det_lang (detection language). Check below.

Function Definition:
https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/paddleocr.py#L348

Function Call:
https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/paddleocr.py#L460

So, the easiest solution is comment out that function call, and set the languages manually. For example, right after the function call, do the following:

```
# lang, det_lang = parse_lang(params.lang)
lang, det_lang = 'en', 'ml'
```

**Comment by ariefwijaya** [comment]
> Thanks, @NaumanHSA
> 
> I cannot see much difference after following the above steps. I believe this still doesn't give the word-level bounding boxes similar to the Pytesseract.

I think we can get it by training our model for ocr det and rec

**Comment by NaumanHSA** [comment]
@ariefwijaya 
Of course, you can always train models accordingly. I tried training OCR recognizer for MRZ reading, and it is working pretty good. But I've not yet tried to train the detection model which I assume is much easier to train than a recognizer.

**Comment by KameniAlexNea** [comment]
I did this implementation to avoid modification of the source code : 

```python
import logging
import os
import sys
from pathlib import Path

import cv2
import numpy as np
from paddleocr import paddleocr
from paddleocr.paddleocr import (BASE_DIR, SUPPORT_DET_MODEL,
                                 SUPPORT_OCR_MODEL_VERSION, SUPPORT_REC_MODEL,
                                 alpha_to_color, binarize_img, check_gpu,
                                 check_img, confirm_model_dir_url,
                                 get_model_config, logger, maybe_download,
                                 parse_args, parse_lang, predict_system)


class MultiPaddleOCR(predict_system.TextSystem):
    def __init__(self, **kwargs):
        """
        paddleocr package
        args:
            **kwargs: other params show in paddleocr --help
        """
        params = parse_args(mMain=False)
        params.__dict__.update(**kwargs)
        assert params.ocr_version in SUPPORT_OCR_MODEL_VERSION, "ocr_version must in {}, but get {}".format(
            SUPPORT_OCR_MODEL_VERSION, params.ocr_version)
        params.use_gpu = check_gpu(params.use_gpu)

        if not params.show_log:
            logger.setLevel(logging.INFO)
        self.use_angle_cls = params.use_angle_cls
        lang, det_lang = parse_lang(params.lang)
        if params.det_lang is not None:
            det_lang = params.det_lang

        # init model dir
        det_model_config = get_model_config('OCR', params.ocr_version, 'det',
                                            det_lang)
        params.det_model_dir, det_url = confirm_model_dir_url(
            params.det_model_dir,
            os.path.join(BASE_DIR, 'whl', 'det', det_lang),
            det_model_config['url'])
        rec_model_config = get_model_config('OCR', params.ocr_version, 'rec',
                                            lang)
        params.rec_model_dir, rec_url = confirm_model_dir_url(
            params.rec_model_dir,
            os.path.join(BASE_DIR, 'whl', 'rec', lang), rec_model_config['url'])
        cls_model_config = get_model_config('OCR', params.ocr_version, 'cls',
                                            'ch')
        params.cls_model_dir, cls_url = confirm_model_dir_url(
            params.cls_model_dir,
            os.path.join(BASE_DIR, 'whl', 'cls'), cls_model_config['url'])
        if params.ocr_version in ['PP-OCRv3', 'PP-OCRv4']:
            params.rec_image_shape = "3, 48, 320"
        else:
            params.rec_image_shape = "3, 32, 320"
        # download model if using paddle infer
        if not params.use_onnx:
            maybe_download(params.det_model_dir, det_url)
            maybe_download(params.rec_model_dir, rec_url)
            maybe_download(params.cls_model_dir, cls_url)

        if params.det_algorithm not in SUPPORT_DET_MODEL:
            logger.error('det_algorithm must in {}'.format(SUPPORT_DET_MODEL))
            sys.exit(0)
        if params.rec_algorithm not in SUPPORT_REC_MODEL:
            logger.error('rec_algorithm must in {}'.format(SUPPORT_REC_MODEL))
            sys.exit(0)

        if params.rec_char_dict_path is None:
            params.rec_char_dict_path = str(
                Path(paddleocr.__file__).parent / rec_model_config['dict_path'])

        logger.debug(params)
        # init det_model and rec_model
        super().__init__(params)
        self.page_num = params.page_num

    def ocr(self, img, det=True, rec=True, cls=True, bin=False, inv=False, alpha_color=(255, 255, 255)):
        """
        OCR with PaddleOCR
        args:
            img: img for OCR, support ndarray, img_path and list or ndarray
            det: use text detection or not. If False, only rec will be exec. Default is True
            rec: use text recognition or not. If False, only det will be exec. Default is True
            cls: use angle classifier or not. Default is True. If True, the text with rotation of 180 degrees can be recognized. If no text is rotated by 180 degrees, use cls=False to get better performance. Text with rotation of 90 or 270 degrees can be recognized even if cls=False.
            bin: binarize image to black and white. Default is False.
            inv: invert image colors. Default is False.
            alpha_color: set RGB color Tuple for transparent parts replacement. Default is pure white.
        """
        assert isinstance(img, (np.ndarray, list, str, bytes))
        if isinstance(img, list) and det == True:
            logger.error('When input a list of images, det must be false')
            exit(0)
        if cls == True and self.use_angle_cls == False:
            logger.warning(
                'Since the angle classifier is not initialized, it will not be used during the forward process'
            )

        img = check_img(img)
        # for infer pdf file
        if isinstance(img, list):
            if self.page_num > len(img) or self.page_num == 0:
                self.page_num = len(img)
            imgs = img[:self.page_num]
        else:
            imgs = [img]

        def preprocess_image(_image):
            _image = alpha_to_color(_image, alpha_color)
            if inv:
                _image = cv2.bitwise_not(_image)
            if bin:
                _image = binarize_img(_image)
            return _image

        if det and rec:
            ocr_res = []
            for idx, img in enumerate(imgs):
                img = preprocess_image(img)
                dt_boxes, rec_res, _ = self.__call__(img, cls)
                if not dt_boxes and not rec_res:
                    ocr_res.append(None)
                    continue
                tmp_res = [[box.tolist(), res]
                           for box, res in zip(dt_boxes, rec_res)]
                ocr_res.append(tmp_res)
            return ocr_res
        elif det and not rec:
            ocr_res = []
            for idx, img in enumerate(imgs):
                img = preprocess_image(img)
                dt_boxes, elapse = self.text_detector(img)
                if not dt_boxes:
                    ocr_res.append(None)
                    continue
                tmp_res = [box.tolist() for box in dt_boxes]
                ocr_res.append(tmp_res)
            return ocr_res
        else:
            ocr_res = []
            cls_res = []
            for idx, img in enumerate(imgs):
                if not isinstance(img, list):
                    img = preprocess_image(img)
                    img = [img]
                if self.use_angle_cls and cls:
                    img, cls_res_tmp, elapse = self.text_classifier(img)
                    if not rec:
                        cls_res.append(cls_res_tmp)
                rec_res, elapse = self.text_recognizer(img)
                ocr_res.append(rec_res)
            if not rec:
                return cls_res
            return ocr_res
```

**Comment by rk041kumar** [comment]
Above Code can we resolve the word level extraction and get the coordinate information also
