### ISSUE TITLE
关于模型微调，参数冻结，总结？

### ISSUE THREAD

**Issue by kingkingpang** [PaddlePaddle/PaddleOCR#9486]
- 版本号/Version：Paddle：paddleocrv3   

查阅了有关issue的提问与回答。
目前看到两种回答：
一种回答是 #5543 
[PaddleOCR/ppocr/modeling/architectures/distillation_model.py](https://github.com/PaddlePaddle/PaddleOCR/blob/b43f9ecec2e518a2696642977f0acc67d1e2943b/ppocr/modeling/architectures/distillation_model.py#L50-L52)

Lines 50 to 52 in [b43f9ec](https://github.com/PaddlePaddle/PaddleOCR/commit/b43f9ecec2e518a2696642977f0acc67d1e2943b)

 if freeze_params: 
     for param in model.parameters(): 
         param.trainable = False

我看了之后不清楚放到哪个位置，然后又看到了 #5505
![154396911-e345a82c-3d46-4060-9118-58c3feb1fbf4](https://user-images.githubusercontent.com/53334346/226372460-c8a99a30-4e3a-4056-9833-babfe0262bf5.png)

这样放置就可以了吗？ 还是要继续在config中的yml文件中继续修改以下两个地方？这两个地方的参数有何作用？？
![SharedScreenshot](https://user-images.githubusercontent.com/53334346/226371792-388a7670-164f-4c4a-a53a-73a07671d2ad.jpg)

第二种回答是 #6753

> 在希望冻结的部分，添加 stop_gradient=True, 如果是希望冻结backbone，可在这个位置下一行添加 x.stop_gradient=True：
[PaddleOCR/ppocr/modeling/architectures/base_model.py](https://github.com/PaddlePaddle/PaddleOCR/blob/3293645c1a036026e1dda71d11755b19fda1813e/ppocr/modeling/architectures/base_model.py#L79)

Line 79 in [3293645](https://github.com/PaddlePaddle/PaddleOCR/commit/3293645c1a036026e1dda71d11755b19fda1813e)

 x = self.backbone(x)

这种方式相对让人容易理解一点。

**Comment by pcycccccc** [comment]
请问您验证过这两种冻结方式吗？训练的话是可行的吗？

**Comment by kingkingpang** [comment]
我没有验证过，你可以试一下，两种应该都是可行的。
第一种方法是针对“师生”模型，这里设置冻结是冻结整个“教师”模块或“学生”模块。这种方法只用改yml文件。
第二个是针对模型结构中的某个模块，比如backbone\neck。这种方法只用改py文件。
第二种比第一种控制的部分更加细节一点。

**Comment by pcycccccc** [comment]
第一种方法，忽略第一个截图上的代码吗？只需要修改yml？

**Comment by pcycccccc** [comment]
> 我没有验证过，你可以试一下，两种应该都是可行的。 第一种方法是针对“师生”模型，这里设置冻结是冻结整个“教师”模块或“学生”模块。这种方法只用改yml文件。 第二个是针对模型结构中的某个模块，比如backbone\neck。这种方法只用改py文件。 第二种比第一种控制的部分更加细节一点。

第一种方法是不是不用第一张截图那部分的修改，直接改yml文件就ok了？

**Comment by kingkingpang** [comment]
yeah~
