### ISSUE TITLE
OCR outputting first page only of PDF files 

### ISSUE THREAD

**Issue by creo13** [PaddlePaddle/PaddleOCR#9487]
PaddleOCR is ouputting the first page only of PDF files when inside a For Loop (See code below). PaddleOCR however will output when inputting a single PDF. I've tried to play with the presets but to no  success. Please note there were not any errors.

- 系统环境/System Environment：Python 3.10.6 venv Win10
- 版本号/Version：CUDA 11.7, CuDNN 8.8  Paddle：2.4.2.post117  PaddleOCR：2.6.1.3  
- 问题相关组件/Related components: RTX 3090
- 运行指令/Command Code：

from paddleocr import PaddleOCR
paddle= PaddleOCR(use_angle_cls=True, lang="en", use_gpu=True, use_mp=True, max_batch_size=1000, page_num=0)  
for pdf in directory:
       result = paddle.ocr(directory + pdf, cls=True)

**Comment by andyjpaddle** [comment]
I have tried that and it can output all the page results

**Comment by creo13** [comment]
Thank you @feiyangwei. 
Adding code "ocr = PaddleOCR(use_angle_cls=True, lang="ch")" into the loop does work. However the new problem is that efficiency is reduced 450% now due to the fact that the model now has to be loaded into the loop with each iteration. Is there a better work around?

**Comment by creo13** [comment]
@andyjpaddle Did you install CUDA/CuDNN inside the environment?

**Comment by alouafi** [comment]
Hi, I also have the same issue, is there any workaround other than reinstantiating the PaddleOCR object? Because it significantly increases computational time and reloads the model although it is not necessary

**Comment by lhepto** [comment]
Having the same problem, is there way around this without reinstantiating?

**Comment by Nzteb** [comment]
Is there any update on this? I'm facing the same problem.
