### ISSUE TITLE
paddleocr使用问题

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#9489]
环境 Python3.6
paddlepaddle==2.1.0
paddlehub==2.1.0
paddlenlp==2.0.3

ocr = hub.Module(directory="/usr/src/app/paddlehub_bak/modules/chinese_ocr_db_crnn")
按指定目录初始化  但执行recognize_text时报错
 paddlehub.module.manager.HubModuleNotFoundError: No HubModule named chinese_text_detection_db was found
paddlehub_bak/modules/下目录文件都有，chinese_text_detection_db 要怎么指定 ？
drwxr-xr-x. 6 root root 175 Mar 21 10:12 chinese_ocr_db_crnn
drwxr-xr-x. 5 root root 151 Mar 21 10:12 chinese_ocr_db_crnn_server
drwxr-xr-x. 4 root root 119 Mar 21 10:12 chinese_text_detection_db
drwxr-xr-x. 4 root root 121 Mar 21 10:12 chinese_text_detection_db_server

**Comment by Matiz7** [comment]
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/src/app/app.py", line 84, in invoke_client
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    results = ocr_c.recognize_text(paths=[f1], visualization=False)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    return func(*args, **kwargs)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 63, in _wrapper
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    return func(*args, **kwargs)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/src/app/paddlehub_bak/modules/chinese_ocr_db_crnn/module.py", line 195, in recognize_text
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    detection_results = self.text_detector_module.detect_text(
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 90, in __getattribute__
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    _attr = object.__getattribute__(self, attr)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/src/app/paddlehub_bak/modules/chinese_ocr_db_crnn/module.py", line 95, in text_detector_module
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    name='chinese_text_detection_db')
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 395, in __new__
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    **kwargs)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 493, in init_with_name
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    ignore_env_mismatch=ignore_env_mismatch)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/mana
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19FC Invoke End RequestId: 1-641970af-6c83db9bf1fd61265086cd3b
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19ger.py", line 190, in install
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    return self._install_from_name(name, version, ignore_env_mismatch)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 270, in _install_from_name
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19    raise HubModuleNotFoundError(name=name, version=version)
c-641970af-536c55dff2b945f39ec42023-03-21 16:54:19paddlehub.module.manager.HubModuleNotFoundError: No HubModule named chinese_text_detection_db was found

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/deploy/hubserving 进行部署

**Comment by Matiz7** [comment]
> 参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/deploy/hubserving 进行部署

我用的版本比较老，之前单机部署成功了一直在用，所以现在要镜像部署也继续用这个老版本。你们这文档 两种方式好像都不适合镜像部署用 ？

**Comment by andyjpaddle** [comment]
可以试试fastdeploy

**Comment by Matiz7** [comment]
> 可以试试fastdeploy

ocr = hub.Module(name="chinese_ocr_db_crnn")
之前我单机代码这么写的没有问题，模型自动下载到用户默认路径下 ~/.paddlehub   镜像里只能指定路径，但是报错，帮忙看看这个问题吧

**Comment by andyjpaddle** [comment]
这个可以到paddlehub下面提个issue问下~
