### ISSUE TITLE
自己数据训练的表格识别模型--预测结果完全不准且高度一致

### ISSUE THREAD

**Issue by tianyongliu** [PaddlePaddle/PaddleOCR#9493]
数据集共有5W张图片，模型batch_size设置的48，训练了50轮，在测试集上评估结果： 84.9%
这是模型预测结果：

[2023/03/21 17:38:36] ppocr INFO: <html><body><table><thead></thead> colspan="20" colspan="20" colspan="20" colspan="20" colspan="20"</tbody><tr></tr></thead> colspan="20" colspan="20" colspan="20" colspan="20" colspan="20"</tbody></thead> colspan="20" colspan="20" colspan="20" colspan="20" colspan="20"</tbody><td rowspan="2"</table></body></html>
[2023/03/21 17:38:36] ppocr INFO: excel saved to ../output/table/600859_20210424_5_P_138_T_4.xlsx

我的数据样式，其中bbox是文字区域的坐标(圈住文字的最小外接矩形)：
{"imgid": 1677693594028342, "filename": "7ac1ecb4-3879-4863-bdd9-aeda8cd6053d_P_155_T_1.png", "split": "train", "html": {"cells": [{"tokens": ["<b>", "单", "位", "名", "称", "</b>"], "bbox": [12.611125119508273, 0.45966571721771743, 50.861212869508265, 10.144069217217748]}, {"tokens": ["<b>", "账", "面", "余", "额", "</b>"], "bbox": [248.65111986950828, 0.45966571721771743, 286.9012136195083, 10.144069217217748]}, {"tokens": ["<b>", "占", "预", "付", "款", "项", "余", "额", "的", "比", "例", "(", "%", ")", "</b>"], "bbox": [342.4911161195083, 0.45966571721771743, 448.2329829542979, 10.144069217217748]}, {"tokens": ["<b>", "中", "粮", "肉", "食", "（", "北", "京", "）", "有", "限", "公", "司", "</b>"], "bbox": [2.0511236195082603, 17.85966346721773, 112.30122261950825, 27.54406696721776]}, {"tokens": ["<b>", "5", ",", "7", "0", "3", ",", "2", "5", "7", ".", "3", "9", "</b>"], "bbox": [264.2275526195083, 18.543691967217796, 268.7277401195082, 27.54406696721776]}, {"tokens": ["<b>", "1", "5", ".", "4", "3", "</b>"], "bbox": [311.5311168695083, 18.543691967217796, 313.78121061950833, 27.54406696721776]}, {"tokens": ["<b>", "正", "大", "饲", "料", "（", "义", "乌", "）", "有", "限", "公", "司", "（", "以", "下", "简", "称", "正", "大", "饲", "料", "公", "司", "）", "</b>"], "bbox": [2.0511236195082603, 35.13967021721771, 220.30122261950825, 44.82407371721774]}, {"tokens": ["<b>", "3", ",", "0", "4", "4", ",", "6", "1", "6", ".", "5", "2", "</b>"], "bbox": [264.25113336950824, 35.82369871721778, 268.7513208695083, 44.82407371721774]}, {"tokens": ["<b>", "8", ".", "2", "4", "</b>"], "bbox": [311.5311168695083, 35.82369871721778, 313.78121061950833, 44.82407371721774]}, {"tokens": ["<b>", "阜", "阳", "汉", "世", "伟", "食", "品", "有", "限", "公", "司", "</b>"], "bbox": [2.0511236195082603, 52.539655967217755, 103.30122261950825, 62.224059467217785]}, {"tokens": ["<b>", "2", ",", "8", "9", "0", ",", "4", "6", "0", ".", "3", "9", "</b>"], "bbox": [264.22792761950825, 53.22368446721782, 268.7281151195083, 62.224059467217785]}, {"tokens": ["<b>", "7", ".", "8", "2", "</b>"], "bbox": [311.5311168695083, 53.22368446721782, 313.78121061950833, 62.224059467217785]}, {"tokens": ["<b>", "C", "a", "r", "n", "i", "c", "a", " ", "B", "a", "t", "a", "l", "l", "e", ",", "S", ".", "A", ".", "</b>"], "bbox": [2.0511236195082603, 70.5036912172178, 8.045373369508262, 79.50406621721777]}, {"tokens": ["<b>", "2", ",", "7", "3", "0", ",", "2", "0", "4", ".", "4", "0", "</b>"], "bbox": [264.2849597280981, 70.5036912172178, 268.785147228098, 79.50406621721777]}, {"tokens": ["<b>", "7", ".", "3", "9", "</b>"], "bbox": [311.5311168695083, 70.5036912172178, 313.78121061950833, 79.50406621721777]}, {"tokens": ["<b>", "K", "R", "I", "S", "T", "O", "M", " ", "C", "A", "N", "A", "D", "A", "</b>"], "bbox": [2.0511236195082603, 87.90370021721776, 8.549394369508263, 96.90407521721772]}, {"tokens": ["<b>", "2", ",", "5", "8", "3", ",", "1", "3", "9", ".", "4", "5", "</b>"], "bbox": [264.2483957136609, 87.90370021721776, 268.74858321366094, 96.90407521721772]}, {"tokens": ["<b>", "6", ".", "9", "9", "</b>"], "bbox": [311.5311168695083, 87.90370021721776, 313.78121061950833, 96.90407521721772]}, {"tokens": ["<b>", "小", "计", "</b>"], "bbox": [12.611125119508273, 104.49967846721768, 40.06121736950827, 114.18408196721771]}, {"tokens": ["<b>", "1", "6", ",", "9", "5", "1", ",", "6", "7", "8", ".", "1", "5", "</b>"], "bbox": [259.8503748695083, 105.18370696721774, 264.3505623695082, 114.18408196721771]}, {"tokens": ["<b>", "4", "5", ".", "8", "7", "</b>"], "bbox": [311.5311168695083, 105.18370696721774, 313.78121061950833, 114.18408196721771]}], "structure": {"tokens": ["<thead>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</thead>", "<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}}, "location": [55.188876380491735, 132.24000628278225, 532.9325845264007, 256.5600121892817], "pdfShape": [841.92004, 595.32001]}

**Comment by tianyongliu** [comment]
![image](https://user-images.githubusercontent.com/126230848/226776889-7e543264-ceb5-40ff-81e7-c3193e042708.png)

**Comment by tianyongliu** [comment]
不好意思，上面的结果和原始的标注数据不匹配，我这里给出了一个原始图，以及其对应的标注数据以及预测结果的展示：
这是原图，原图比较小，16kb, 477 * 124  
![image](https://user-images.githubusercontent.com/126230848/226779030-198276c7-3cf2-4f63-903e-035fde54236a.png)

这是对应的标注数据：
{"imgid": 1677693594028342, "filename": "7ac1ecb4-3879-4863-bdd9-aeda8cd6053d_P_155_T_1.png", "split": "train", "html": {"cells": [{"tokens": ["<b>", "单", "位", "名", "称", "</b>"], "bbox": [12.611125119508273, 0.45966571721771743, 50.861212869508265, 10.144069217217748]}, {"tokens": ["<b>", "账", "面", "余", "额", "</b>"], "bbox": [248.65111986950828, 0.45966571721771743, 286.9012136195083, 10.144069217217748]}, {"tokens": ["<b>", "占", "预", "付", "款", "项", "余", "额", "的", "比", "例", "(", "%", ")", "</b>"], "bbox": [342.4911161195083, 0.45966571721771743, 448.2329829542979, 10.144069217217748]}, {"tokens": ["<b>", "中", "粮", "肉", "食", "（", "北", "京", "）", "有", "限", "公", "司", "</b>"], "bbox": [2.0511236195082603, 17.85966346721773, 112.30122261950825, 27.54406696721776]}, {"tokens": ["<b>", "5", ",", "7", "0", "3", ",", "2", "5", "7", ".", "3", "9", "</b>"], "bbox": [264.2275526195083, 18.543691967217796, 268.7277401195082, 27.54406696721776]}, {"tokens": ["<b>", "1", "5", ".", "4", "3", "</b>"], "bbox": [311.5311168695083, 18.543691967217796, 313.78121061950833, 27.54406696721776]}, {"tokens": ["<b>", "正", "大", "饲", "料", "（", "义", "乌", "）", "有", "限", "公", "司", "（", "以", "下", "简", "称", "正", "大", "饲", "料", "公", "司", "）", "</b>"], "bbox": [2.0511236195082603, 35.13967021721771, 220.30122261950825, 44.82407371721774]}, {"tokens": ["<b>", "3", ",", "0", "4", "4", ",", "6", "1", "6", ".", "5", "2", "</b>"], "bbox": [264.25113336950824, 35.82369871721778, 268.7513208695083, 44.82407371721774]}, {"tokens": ["<b>", "8", ".", "2", "4", "</b>"], "bbox": [311.5311168695083, 35.82369871721778, 313.78121061950833, 44.82407371721774]}, {"tokens": ["<b>", "阜", "阳", "汉", "世", "伟", "食", "品", "有", "限", "公", "司", "</b>"], "bbox": [2.0511236195082603, 52.539655967217755, 103.30122261950825, 62.224059467217785]}, {"tokens": ["<b>", "2", ",", "8", "9", "0", ",", "4", "6", "0", ".", "3", "9", "</b>"], "bbox": [264.22792761950825, 53.22368446721782, 268.7281151195083, 62.224059467217785]}, {"tokens": ["<b>", "7", ".", "8", "2", "</b>"], "bbox": [311.5311168695083, 53.22368446721782, 313.78121061950833, 62.224059467217785]}, {"tokens": ["<b>", "C", "a", "r", "n", "i", "c", "a", " ", "B", "a", "t", "a", "l", "l", "e", ",", "S", ".", "A", ".", "</b>"], "bbox": [2.0511236195082603, 70.5036912172178, 8.045373369508262, 79.50406621721777]}, {"tokens": ["<b>", "2", ",", "7", "3", "0", ",", "2", "0", "4", ".", "4", "0", "</b>"], "bbox": [264.2849597280981, 70.5036912172178, 268.785147228098, 79.50406621721777]}, {"tokens": ["<b>", "7", ".", "3", "9", "</b>"], "bbox": [311.5311168695083, 70.5036912172178, 313.78121061950833, 79.50406621721777]}, {"tokens": ["<b>", "K", "R", "I", "S", "T", "O", "M", " ", "C", "A", "N", "A", "D", "A", "</b>"], "bbox": [2.0511236195082603, 87.90370021721776, 8.549394369508263, 96.90407521721772]}, {"tokens": ["<b>", "2", ",", "5", "8", "3", ",", "1", "3", "9", ".", "4", "5", "</b>"], "bbox": [264.2483957136609, 87.90370021721776, 268.74858321366094, 96.90407521721772]}, {"tokens": ["<b>", "6", ".", "9", "9", "</b>"], "bbox": [311.5311168695083, 87.90370021721776, 313.78121061950833, 96.90407521721772]}, {"tokens": ["<b>", "小", "计", "</b>"], "bbox": [12.611125119508273, 104.49967846721768, 40.06121736950827, 114.18408196721771]}, {"tokens": ["<b>", "1", "6", ",", "9", "5", "1", ",", "6", "7", "8", ".", "1", "5", "</b>"], "bbox": [259.8503748695083, 105.18370696721774, 264.3505623695082, 114.18408196721771]}, {"tokens": ["<b>", "4", "5", ".", "8", "7", "</b>"], "bbox": [311.5311168695083, 105.18370696721774, 313.78121061950833, 114.18408196721771]}], "structure": {"tokens": ["<thead>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</thead>", "<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}}, "location": [55.188876380491735, 132.24000628278225, 532.9325845264007, 256.5600121892817], "pdfShape": [841.92004, 595.32001]}

这是可视化结果，可视化结果无法显示原始图片
![image](https://user-images.githubusercontent.com/126230848/226779324-a41afa12-0b3e-46fd-aa70-51bce8467cdb.png)


![image](https://user-images.githubusercontent.com/126230848/226778957-8c3b9b4f-4826-4b36-9632-dd74b280fdd9.png)

**Comment by Mrfuhang** [comment]
> 不好意思，上面的结果和原始的标注数据不匹配，我这里给出了一个原始图，以及其对应的标注数据以及预测结果的展示： 这是原图，原图比较小，16kb, 477 * 124 ![image](https://user-images.githubusercontent.com/126230848/226779030-198276c7-3cf2-4f63-903e-035fde54236a.png)
> 
> 这是对应的标注数据， html/structure/tokens中的元素有带, 之类的，点击Update comment提交后就全部变成空了，如果你那边能编辑的话，应该可以看到： {"imgid": 1677693594028342, "filename": "7ac1ecb4-3879-4863-bdd9-aeda8cd6053d_P_155_T_1.png", "split": "train", "html": {"cells": [{"tokens": ["", "单", "位", "名", "称", ""], "bbox": [12.611125119508273, 0.45966571721771743, 50.861212869508265, 10.144069217217748]}, {"tokens": ["", "账", "面", "余", "额", ""], "bbox": [248.65111986950828, 0.45966571721771743, 286.9012136195083, 10.144069217217748]}, {"tokens": ["", "占", "预", "付", "款", "项", "余", "额", "的", "比", "例", "(", "%", ")", ""], "bbox": [342.4911161195083, 0.45966571721771743, 448.2329829542979, 10.144069217217748]}, {"tokens": ["", "中", "粮", "肉", "食", "（", "北", "京", "）", "有", "限", "公", "司", ""], "bbox": [2.0511236195082603, 17.85966346721773, 112.30122261950825, 27.54406696721776]}, {"tokens": ["", "5", ",", "7", "0", "3", ",", "2", "5", "7", ".", "3", "9", ""], "bbox": [264.2275526195083, 18.543691967217796, 268.7277401195082, 27.54406696721776]}, {"tokens": ["", "1", "5", ".", "4", "3", ""], "bbox": [311.5311168695083, 18.543691967217796, 313.78121061950833, 27.54406696721776]}, {"tokens": ["", "正", "大", "饲", "料", "（", "义", "乌", "）", "有", "限", "公", "司", "（", "以", "下", "简", "称", "正", "大", "饲", "料", "公", "司", "）", ""], "bbox": [2.0511236195082603, 35.13967021721771, 220.30122261950825, 44.82407371721774]}, {"tokens": ["", "3", ",", "0", "4", "4", ",", "6", "1", "6", ".", "5", "2", ""], "bbox": [264.25113336950824, 35.82369871721778, 268.7513208695083, 44.82407371721774]}, {"tokens": ["", "8", ".", "2", "4", ""], "bbox": [311.5311168695083, 35.82369871721778, 313.78121061950833, 44.82407371721774]}, {"tokens": ["", "阜", "阳", "汉", "世", "伟", "食", "品", "有", "限", "公", "司", ""], "bbox": [2.0511236195082603, 52.539655967217755, 103.30122261950825, 62.224059467217785]}, {"tokens": ["", "2", ",", "8", "9", "0", ",", "4", "6", "0", ".", "3", "9", ""], "bbox": [264.22792761950825, 53.22368446721782, 268.7281151195083, 62.224059467217785]}, {"tokens": ["", "7", ".", "8", "2", ""], "bbox": [311.5311168695083, 53.22368446721782, 313.78121061950833, 62.224059467217785]}, {"tokens": ["", "C", "a", "r", "n", "i", "c", "a", " ", "B", "a", "t", "a", "l", "l", "e", ",", "S", ".", "A", ".", ""], "bbox": [2.0511236195082603, 70.5036912172178, 8.045373369508262, 79.50406621721777]}, {"tokens": ["", "2", ",", "7", "3", "0", ",", "2", "0", "4", ".", "4", "0", ""], "bbox": [264.2849597280981, 70.5036912172178, 268.785147228098, 79.50406621721777]}, {"tokens": ["", "7", ".", "3", "9", ""], "bbox": [311.5311168695083, 70.5036912172178, 313.78121061950833, 79.50406621721777]}, {"tokens": ["", "K", "R", "I", "S", "T", "O", "M", " ", "C", "A", "N", "A", "D", "A", ""], "bbox": [2.0511236195082603, 87.90370021721776, 8.549394369508263, 96.90407521721772]}, {"tokens": ["", "2", ",", "5", "8", "3", ",", "1", "3", "9", ".", "4", "5", ""], "bbox": [264.2483957136609, 87.90370021721776, 268.74858321366094, 96.90407521721772]}, {"tokens": ["", "6", ".", "9", "9", ""], "bbox": [311.5311168695083, 87.90370021721776, 313.78121061950833, 96.90407521721772]}, {"tokens": ["", "小", "计", ""], "bbox": [12.611125119508273, 104.49967846721768, 40.06121736950827, 114.18408196721771]}, {"tokens": ["", "1", "6", ",", "9", "5", "1", ",", "6", "7", "8", ".", "1", "5", ""], "bbox": [259.8503748695083, 105.18370696721774, 264.3505623695082, 114.18408196721771]}, {"tokens": ["", "4", "5", ".", "8", "7", ""], "bbox": [311.5311168695083, 105.18370696721774, 313.78121061950833, 114.18408196721771]}], "structure": {"tokens": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]}}, "location": [55.188876380491735, 132.24000628278225, 532.9325845264007, 256.5600121892817], "pdfShape": [841.92004, 595.32001]}
> 
> 这是可视化结果，可视化结果无法显示原始图片 ![image](https://user-images.githubusercontent.com/126230848/226779324-a41afa12-0b3e-46fd-aa70-51bce8467cdb.png)
> 
> ![image](https://user-images.githubusercontent.com/126230848/226778957-8c3b9b4f-4826-4b36-9632-dd74b280fdd9.png)

无法显示原图，有些图片是这样，但是识别出来的结果倒是还可以的呀，是不是标注上有些问题呢
