### ISSUE TITLE
Ubuntu arm64 编译paddle2.4版本源代码失败

### ISSUE THREAD

**Issue by hbliucl** [PaddlePaddle/PaddleOCR#9496]
按照官方的文档: https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html, 在Ubuntu18.04版本, 使用Docker方式编译源代码失败, 信息如下:

root@iZ2ze0gtsdv2iyxtqcwz85Z:~/Paddle# docker run --name paddle-v6 -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:latest-dev /bin/bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/bash: exec format error

没有arm版本的docker镜像

请问, 官方能否提供一个arm64版本的docker镜像, 在项目中直接使用即可
或者官方提供一个编译好的paddle库, 项目直接引入

**Comment by MissPenguin** [comment]
编译问题可以去paddle官网提个issue哈：https://github.com/PaddlePaddle/Paddle/issues
