### ISSUE TITLE
您好，我公式识别训练自己的数据， ACC一直为0，请问是什么原因啊

### ISSUE THREAD

**Issue by dongjie-shi** [PaddlePaddle/PaddleOCR#9498]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
用公开数据集按照教程能正常训练吗

**Comment by dongjie-shi** [comment]
没用公开数据集训练用， 直接用的自己的数据集
