### ISSUE TITLE
predict_system.py: error: unrecognized arguments: --cls_model_dir=./inference/ch_ppocr_mobile_v1.1_cls_infer/ --use_angle_cls=True

### ISSUE THREAD

**Issue by guanfaqian** [PaddlePaddle/PaddleOCR#950]
我刚刚接触贵公司的项目。

发现有个问题在window对于cls模型不能解压，linux可以。

另外根据python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False

发现cls_model_dir参数没用。我在该文件也没看到相关参数。

**Comment by guanfaqian** [comment]
好像我用的是之前。才出现问题

**Comment by littletomatodonkey** [comment]
你好，麻烦拉一下最新的代码吧，这些参数是在最新的代码里
