### ISSUE TITLE
用版面分析模型训练自己的数据集 MAP较低

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9505]
我制作了一个250张训练集30张测试集的版面分析模型，通过200个EPOCH训练，为什么MAP只有0.5啊 很低 
需要扩充数据吗？

**Comment by tink2123** [comment]
训练数据较少，如果场景比较复杂，建议先扩充到1k张左右，同时可以加载预训练模型帮助收敛
