### ISSUE TITLE
docker基础镜像registry.baidubce.com/paddlepaddle/paddle是否有ARM架构镜像

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9507]
在docker环境下部署paddleocr，里面用到一个基础镜像：registry.baidubce.com/paddlepaddle/paddle:2.3.2，请问是否有ARM架构对应的基础镜像？如果没有，那么是否支持在ARM架构服务器下进行源码编译？但看你们官方网站说明，paddle又不支持ARM64:，如下图所示：

![1f6c816994129385e4d36eb51d0406d](https://user-images.githubusercontent.com/18339429/226850055-3fd2999a-91d8-4ce4-b854-3b6b89841acd.png)

**Comment by tink2123** [comment]
可以在更多硬件中查看是否支持：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html

如不支持您的硬件，可以去主repo提交issue，询问能否支持：https://github.com/PaddlePaddle/Paddle/issues
