### ISSUE TITLE
Gpu版本,无法识别pdf中文字

### ISSUE THREAD

**Issue by Lao-Feng** [PaddlePaddle/PaddleOCR#9508]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
-
![image](https://user-images.githubusercontent.com/35493712/226855307-645796c9-3c29-4d34-b12f-a8d7fbcb7cfb.png)
![image](https://user-images.githubusercontent.com/35493712/226855626-4e5a6380-57e5-4ba4-9735-a23ebd4a4487.png)

**Comment by tink2123** [comment]
先检查下Paddle是否正确安装，cpu版本能否正确识别结果呢？ 控制台输出log是否有报错信息
