### ISSUE TITLE
用PPOCRLabel标注完表格后，训练是不是只用了html的结构作为数据进行训练

### ISSUE THREAD

**Issue by yygc2002** [PaddlePaddle/PaddleOCR#9513]
用PPOCRLabel标注完表格后会有对表格内文本检测的cell信息，如果我只是进行表格结构识别的训练的话这些信息是不是没有用上，只用了html的描述作为训练数据

**Comment by Mrfuhang** [comment]
不是，还运用到了他们的坐标等信息

**Comment by yygc2002** [comment]
> 不是，还运用到了他们的坐标等信息

感谢回复，我还有两个困惑：
1、我在原理里看到的是先分成表格结构识别和文本检测，然后再用表格单元格的四点坐标和文本的四点坐标做内聚合并，然后看到别人提问的回答是表格结构识别时调用的是内置ocr，并且再训练表格结构时是不会训练这个ocr的，那这个文本检测的cell信息在表格结构训练时的作用是什么（有点长抱歉，想尽可能描述清楚）
2、如果有用到这个cell信息的话，那我在表格标注时这个cell的大小是包含住文本就行还是要和整个单元格重合，并且当一个单元格内有多行信息时要如何进行标注（感谢看完）

**Comment by yygc2002** [comment]
@WenmuZhou 能帮忙看下吗谢谢

**Comment by yygc2002** [comment]
> 不是，还运用到了他们的坐标等信息

这里cell信息是指单元格的坐标还是单元格内文字的坐标
