### ISSUE TITLE
关于AttributeError: module 'paddle.distributed' has no attribute 'init_parallel_env'错误

### ISSUE THREAD

**Issue by Manman35** [PaddlePaddle/PaddleOCR#9514]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![1679535207644](https://user-images.githubusercontent.com/126783868/227076139-99f1733e-9568-4142-9052-0a912e16f837.png)
![1679535241041](https://user-images.githubusercontent.com/126783868/227076241-563e4231-839c-4c89-84ac-09e04fd61725.png)
AiStudio里面运行的 请问一下这个错误怎么解决

**Comment by WenmuZhou** [comment]
paddle安装成功了吗，试一下paddle.utils.run_check()

**Comment by Manman35** [comment]
好的 謝謝&nbsp;


王晓曼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 关于AttributeError: module &#39;paddle.distributed&#39; has no attribute &#39;init_parallel_env&#39;错误 (Issue #9514)





 
paddle安装成功了吗，试一下paddle.utils.run_check()

**Comment by andyz168** [comment]
升级paddlepaddle试下
