### ISSUE TITLE
检测识别行驶证时无法区分花体字0

### ISSUE THREAD

**Issue by icecream56** [PaddlePaddle/PaddleOCR#9519]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
直接使用预训练模型（ch_PP-OCRv3_det_infer/ch_PP-OCRv3_rec_infer）检测识别行驶证，下面是检测结果：
![ED0E2B3D830F43369420B31FFFBBF478](https://user-images.githubusercontent.com/91267993/227097031-c8d2536e-7c0f-44ed-aba0-9d0802e6cd46.png)

遇到数字的时候识别都不太不准确，特别是花体字0，看来还是得finetune吧？想问问有没有人做过这个让我偷个懒，栓Q

**Comment by livingbody** [comment]
需要finetune，可以参看aistudio上的电【表读数识别】范例项目

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
