### ISSUE TITLE
我有一个问题，在ocr模型转为onnx推理的时候，我需要固定shape。有两个方案，1，使用paddle.jit.to_static 转静态图的时候指定shape[1,3,1536,1536],然后使用paddle2onnx转为onnx模型；或者，2,用paddle.jit.to_static 转静态图的时候不指定shape，即shape=[None, None,None,None],然后使用paddle2onnx转为onnx模型时候指定输入的shape[1,3,1536,1536]；  哪种方式对精度影响最小呢？？

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/PaddleOCR#9522]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by WenmuZhou** [comment]
这个你可以手动尝试一下
