### ISSUE TITLE
SER and RE models deployment on mobile (Android/iOS)

### ISSUE THREAD

**Issue by NaumanHSA** [PaddlePaddle/PaddleOCR#9523]
Hello All,
I've successfully trained SER and RE models on my custom datasets and it's working pretty good. Thanks to the paddleOCR. Now, my next goal is to deploy the whole pipeline on mobile so I can run the OCR on the client side application. 

As per paddleOCR documentations, they have provided tutorial for running the OCR engine (Text Detection and Text Recognition) on mobile using PaddleLite. However, I can't find any help for how to run ppstructure (SER and RE) models on mobile. Have anyone successfully deployed these models on mobile? Please assist me if this is possible. Thanks in advance.

**Comment by WenmuZhou** [comment]
The ser and re models are currently too large, and it is not recommended to run on mobile devices

**Comment by NaumanHSA** [comment]
@WenmuZhou Thank you for the response.
Do you guys have any planning to make it possible on edge devices in near future? 
My ultimate goal is make an offline mobile application, and this could be a blocker for me. I'd have to search for alternatives if this is not possible.
