### ISSUE TITLE
这种图片我应该如何框选这个单元格

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9524]
![image](https://user-images.githubusercontent.com/29907548/227202620-f5a4e22e-93a8-4e15-b426-a950b1756c6a.png)

**Comment by Mrfuhang** [comment]
这种自动换行的单元格应该如何标注

**Comment by Mrfuhang** [comment]
> 标记一个大框

识别不出来

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
