### ISSUE TITLE
PyMuPDF installation getting failed while installing PaddleOCR

### ISSUE THREAD

**Issue by vikas94** [PaddlePaddle/PaddleOCR#9526]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Mac M1 Ventura
- 版本号/Version：13.1 
- Paddle： paddlepaddle==2.4.2 
- PaddleOCR：paddleocr>=2.0.1
- python: 3.8
-  问题相关组件/Related components：
- 运行指令/Command Code：pip install paddleocr
- 完整报错/Complete Error Message： swig -python -o fitz/fitz_wrap.c fitz/fitz.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> PyMuPDF

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by SAhmad75** [comment]
I am also having the same issue

**Comment by SAhmad75** [comment]
I also had the same issue. There were different versions of python interpreters. I changed python version from 3.11.2 to 3.10.2 and recreated the virtual environment. It worked after that.

**Comment by swhamdani** [comment]
It works for me, Thanks to [AlienKevin](https://github.com/AlienKevin)
pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1

**Comment by skymavo** [comment]
> It works for me, Thanks to [AlienKevin](https://github.com/AlienKevin) pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1

problem solved

**Comment by vikas94** [comment]
refer to [this](https://stackoverflow.com/questions/68565341/installing-pymupdf-on-macos-big-sur) and install pumpdf manually, this also worked for me

**Comment by njzheng** [comment]
pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1
