### ISSUE TITLE
error while running ppocrlabel. the user interface opens and i choose the image directory. when i try to draw bbox on the image the program crashes giving the "type error"

### ISSUE THREAD

**Issue by kishore-work-hard** [PaddlePaddle/PaddleOCR#9532]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.10.8 64bit, pip 23.0.1
- 版本号/Version：2.4.2 Paddle：paddlepaddle  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：TypeError: 
- 完整报错/Complete Error Message：TypeError: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'float'
  drawRect(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'float'

![image](https://user-images.githubusercontent.com/93419928/227440321-6c64386e-6b54-4c0c-b3d3-ddcab3f31b95.png)

**Comment by kishore-work-hard** [comment]
> you can try clone the repo，and run in this dir：python PPOCRLabel.py

already tried this. doesn't work.

**Comment by kevinkazzo** [comment]
super simple fix, feel free to make the PR.

on line 596 in canvas.py, change the line to this- > `p.drawRect(int(leftTop.x()), int(leftTop.y()), int(rectWidth), int(rectHeight))`

Then recompile PPOCRLabel, and re install. Should probably make a PR for this.
