### ISSUE TITLE
How to train BIO / IOB format dataset for KIE vi_layoutxlm SER model custom training?

### ISSUE THREAD

**Issue by IrfanSk-AI** [PaddlePaddle/PaddleOCR#9534]
I am currently working on KIE vi_layoutxlm SER model custom training. My dataset annotations are in BIO / IOB format and its corresponding word coordinates in the IMAGE. But the paddle detection and recognition is happening more than 1 word. In my case, i have word level annotations. Can you help how to train with my dataset.

**Comment by an1018** [comment]
you can try modify the format like [this](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/kie_en.md#12-custom-dataset)
