### ISSUE TITLE
量化训练时模型评估时，精度(precision)、召回率(recall)、F1值(hmean)都为0

### ISSUE THREAD

**Issue by ChihoJack** [PaddlePaddle/PaddleOCR#9536]
- 系统环境/System Environment：Winodws10 教育版 64位
- 版本号/Version：Paddle：2.3.2.post112  PaddleOCR：2.6.1.3 问题相关组件/Related components：模型量化
- 运行指令/Command Code：
- python deploy/slim/quantization/quant.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.pretrained_model='./train_data/det_outputmodel/best_accuracy'   Global.save_model_dir=./train_data/quant_model_distill/
- 完整报错/Complete Error Message：
- [2023/03/24 11:24:16] ppocr INFO: cur metric, precision: 0.0, recall: 0.0, hmean: 0, fps: 6.358296325689887
-[2023/03/24 11:24:16] ppocr INFO: save best model is to ./train_data/quant_model_distill/best_accuracy
-[2023/03/24 11:24:16] ppocr INFO: best metric, hmean: 0, is_float16: False, precision: 0.0, recall: 0.0, fps: 6.358296325689887, best_epoch: 45

下面附上train.log
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/11059746/train.log)

**Comment by ChihoJack** [comment]
我是用我自己微调后的预训练模型来量化的，但是用官方提供没有微调的预训练模型就不会出现这种情况

**Comment by ChihoJack** [comment]
正常的，微调过程中回传精度这些都是0.9+

**Comment by JoahHuang** [comment]
我也是，使用PP-OCRv3的学生模型训练了检测和识别模型，然后量化，train.log里指标都正常，但是eval的时候，识别模型acc=0，检测模型是都为0。求解

**Comment by li-ya-zhou** [comment]
使用PP-OCRv3的学生模型训练了检测和识别模型，然后量化，train.log里指标都正常，但是eval的时候，识别模型acc=0，检测模型是都为0。求解

**Comment by JoahHuang** [comment]
邮件已收到~

**Comment by Li-Asia-Edward** [comment]
使用PP-OCRv3的学生模型训练了检测和识别模型，然后量化，train.log里指标都正常，但是eval的时候，识别模型acc=0，检测模型是都为0。求解

**Comment by JoahHuang** [comment]
邮件已收到~

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by JoahHuang** [comment]
邮件已收到~

**Comment by JoahHuang** [comment]
邮件已收到~
