### ISSUE TITLE
使用paddleocr 识别表格图片，为什么识别出来的结构和实际图片会相差那么大呢？

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9537]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：window11
- 版本号/Version：Paddle：2.4.2 PaddleOCR：2.6.1.3 问题相关组件/Related components：

**Comment by an1018** [comment]
可能是因为测试图片和训练差异比较大，可以多测试一下图片，如果整体效果不太好，可以使用自己的图片进行训练

**Comment by Mrfuhang** [comment]
> 可能是因为测试图片和训练差异比较大，可以多测试一下图片，如果整体效果不太好，可以使用自己的图片进行训练

我用的自己的图片训练的呀，然后识别出来的效果不好，比如一列数据，都是单字符，然后它只能识别到一部分
