### ISSUE TITLE
表格结构训练里，json文件中bbox的坐标应该是文本的坐标还是表格单元格的坐标

### ISSUE THREAD

**Issue by yygc2002** [PaddlePaddle/PaddleOCR#9542]
rt

**Comment by livingbody** [comment]
单元格坐标

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
