### ISSUE TITLE
aarch64 deploy with paddlehub, no RNNCell

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleOCR#9554]
system env: aarch64 GNU/Linux
docker image: registry.baidubce.com/device/paddle-cpu:kylinv10-aarch64-gcc73

![2023-03-27 17-39-29屏幕截图](https://user-images.githubusercontent.com/7626261/227904876-86b612c1-9ce7-4e29-8377-89341121750c.png)

**Comment by hazelsilver8740** [comment]
Hello! Has this issue been addressed? I can't seem to find any other sources of help.

**Comment by asmitaw** [comment]
same here

**Comment by Shadow-Alex** [comment]
same here.

**Comment by Shadow-Alex** [comment]
I downgraded the paddle and everything is fine.
Use stable version here, the default `pip install ` will install a `2.5.0` version which cause the trouble.
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/46802674/53364bcf-b0e4-4040-b801-ba7dbccc9464)

**Comment by hazelsilver8740** [comment]
@Shadow-Alex, thank you! Will test this soon.
