### ISSUE TITLE
关于PaddleOcr中的predict_rec.py和infer_rec.py

### ISSUE THREAD

**Issue by BaoBaoJianqiang** [PaddlePaddle/PaddleOCR#9557]
问题1：
请问二者的区别是是什么？按照字面翻译，predict是预测，infer是推理。
但是看很多文档和文章，都说predict_rec.py是用来推理。

问题2：
pip install paddleocr然后使用ocr.ocr()方法进行检测和识别，这个ocr方法对应的是paddleocr项目的哪几个类？

**Comment by JoyshowXia** [comment]
> 问题1： 请问二者的区别是是什么？按照字面翻译，predict是预测，infer是推理。 但是看很多文档和文章，都说predict_rec.py是用来推理。
> 
> 问题2： pip install paddleocr然后使用ocr.ocr()方法进行检测和识别，这个ocr方法对应的是paddleocr项目的哪几个类？

你这么一说还真是！包括官方的文档写的也都是拿infer_xxx.py预测，predict_xxx.py推理，我估计是刚开始名字取反了，后面要改的话要改动的地方太多就索性不改了，将错就错。

**Comment by BaoBaoJianqiang** [comment]
> > 问题1： 请问二者的区别是是什么？按照字面翻译，predict是预测，infer是推理。 但是看很多文档和文章，都说predict_rec.py是用来推理。
> > 问题2： pip install paddleocr然后使用ocr.ocr()方法进行检测和识别，这个ocr方法对应的是paddleocr项目的哪几个类？
> 
> 你这么一说还真是！包括官方的文档写的也都是拿infer_xxx.py预测，predict_xxx.py推理，我估计是刚开始名字取反了，后面要改的话要改动的地方太多就索性不改了，将错就错。

问题2，麻烦看一下

**Comment by BaoBaoJianqiang** [comment]
已解决，就在根目录下的paddleocr类
