### ISSUE TITLE
数据集中中文字符分布不均衡？

### ISSUE THREAD

**Issue by Gavinic** [PaddlePaddle/PaddleOCR#9561]
问题描述:
        使用自己的数据集训练模型时，效果极差，分析数据之后发现字符分布上数量级相差很大。
如下图所示，(左边是字符，右边是数量)。 字符数量差异达到10W级别。有什么好的解决方案吗？PaddleOCR V1，V2，V3 版本中是如何处理这些问题的？感谢
        
![image](https://user-images.githubusercontent.com/20828244/228116846-a1dbaccc-bc4e-429a-8e27-429033eefbcd.png)
![image](https://user-images.githubusercontent.com/20828244/228116884-c1678a5a-1d40-4210-95c4-6890bd843978.png)

**Comment by andyjpaddle** [comment]
可以根据具体的使用场景进行补充数据，生僻字本身就会少一些，如果场景中需要，可以自己加一些对应的数据进行finetune

**Comment by Gavinic** [comment]
paddle v1, v2,v3 版本中对于生僻字有做类似数据增广的特殊处理吗？ 实际使用中发现会把一些繁体字转换成简体中文。请问是在构建词表的时候做了mapping 吗？

**Comment by andyjpaddle** [comment]
没有做映射，训练集中会有一些生僻字
