### ISSUE TITLE
用ch_PP-OCRv3_det模型进行文本图片检测

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleOCR#9562]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
ch_PP-OCRv3_det模型进行文本图片检测，后处理得到的坐标与实际不符合，有的会出现坐标变成2000多
![1679973662809](https://user-images.githubusercontent.com/61871674/228119408-8d4fe4b2-e02d-4285-8a65-52054e4a7c6d.png)
用tools.infer.predict_systeem import TextSystem得到的后处理坐标与实际不符合，有的文本坐标偏移到2000多
- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
检测图片是啥样的？

**Comment by yang-chenyu104** [comment]
![1679986237646](https://user-images.githubusercontent.com/61871674/228152166-e24fb4f8-16a1-45c3-a0b1-af85f6cf708e.png)
检测识别到电子税票号码和后面数字，但前面税票号码坐标会变成2000多，后面数字号码坐标变成200多，其他也有类似坐标漂移问题

**Comment by andyjpaddle** [comment]
完整的可视化发出来看看？

**Comment by yang-chenyu104** [comment]
![1679986629488](https://user-images.githubusercontent.com/61871674/228153575-fdc79884-fe81-4096-9335-eb6c40e261ee.png)

**Comment by yang-chenyu104** [comment]
生成的后处理坐标电子税号横坐标达到2000多其他后面号码坐标只有300多产生坐标漂移问题
![1679990885581](https://user-images.githubusercontent.com/61871674/228171066-f4ed6648-1c66-4c4a-967d-c1392b2483de.png)

**Comment by andyjpaddle** [comment]
可视化是没有问题的呀，你这个坐标有啥问题吗

**Comment by yang-chenyu104** [comment]
看单位名称那个坐标显示是2446，可视化正确，后处理得到的坐标漂移太严重
