### ISSUE TITLE
在做det+rec+提取ser。提取信息结果还可以，但是如果有表格的内容，ser标签就会很多。这种怎么处理？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9565]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![2-1](https://user-images.githubusercontent.com/32863094/228170857-20566a66-8b41-4b00-a9bf-bcf21256a68b.jpg)
像这种一张图片里既有文本又有表格。应该怎么做呢？表格里的每一个空都去标注吗？并命名一个标签吗

**Comment by explorer009** [comment]
同问

**Comment by explorer009** [comment]
可以分享一下，您这个标注数据的方法嘛

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
