### ISSUE TITLE
个人数据det训练完det_hmean: 1.0,det_precision: 1.0。det预测效果也好。但是det+rec之后有会丢那么一两空。

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9566]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
det预测：
```
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference/Student" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_imgsresult/" \
--use_gpu=True
```
预测效果完全正确
![image](https://user-images.githubusercontent.com/32863094/228179625-1bfd3aa4-292c-4034-bb26-684edb4f7668.png)

det+rec预测：
```
python3 tools/infer/predict_system.py \
--image_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_dec_imgs/3-193.jpg" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference/Student/" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--rec_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
--rec_image_shape="3,48,320" \
--rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_dec_imgsresult/" \
--use_space_char=True \
--use_angle_cls=False
```
![image](https://user-images.githubusercontent.com/32863094/228179451-ff094606-12d8-42ea-8f94-3e43d2991619.png)

- 完整报错/Complete Error Message：
这个是为什么呢？det模型是自己训练的，rec模型是直接用的官网的ch_PP-OCRv3_rec_infer模型

**Comment by andyjpaddle** [comment]
可以看下det和det+rec下的预处理和后处理参数是不是一致

**Comment by andyjpaddle** [comment]
可以用pp-structure来解决，版面分析+表格识别

**Comment by rexzhengzhihong** [comment]
> 可以用pp-structure来解决，版面分析+表格识别

可是图片中不止有表格，还有关键信息，怎么处理？

**Comment by andyjpaddle** [comment]
非表格区域也可以检测识别

**Comment by rexzhengzhihong** [comment]
pp-structure 不能使用kie_ser模型吧？

**Comment by rexzhengzhihong** [comment]
文档中哪里有这种例子吗

**Comment by andyjpaddle** [comment]
需要关键信息的话，可以直接用ser模型

**Comment by rexzhengzhihong** [comment]
没太明白，怎么直接用ser模型？

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md

**Comment by rexzhengzhihong** [comment]
这个有做提取的。现在我是不知道怎么在把（版面分析+表格识别）和关键信息提取的怎么一步完成。

**Comment by andyjpaddle** [comment]
如果需要关键信息，那可以不用表格识别了，然后漏掉的，可以调下后处理的阈值

**Comment by rexzhengzhihong** [comment]
如果图片中有文本和表格的，把表格里的空标注为关键信息？

**Comment by rexzhengzhihong** [comment]
我一开始就是这么做的，但是有的图片大部分是表格，标注量非常大，而且det不是很准。有时候表格的文本太靠近。两空会识别成一空

**Comment by rexzhengzhihong** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/9578
这个有提到过，回复没发解决

**Comment by andyjpaddle** [comment]
表格识别更多的是将图片中的表格识别出来转成Excel，你这个问题用kie就行，然后可以在你的数据集上finetune一下

**Comment by rexzhengzhihong** [comment]
然后可以在你的数据集上finetune一下是什么意思？

**Comment by andyjpaddle** [comment]
就是针对你的使用数据做一个finetune训练，优化下模型

**Comment by rexzhengzhihong** [comment]
> finetune

这个有文档吗？不太明白怎么优化

**Comment by andyjpaddle** [comment]
就是在你的数据上进行微调模型，具体看下https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/how_to_do_kie.md

**Comment by rexzhengzhihong** [comment]
ser模型我已经训练完了，但是在det的时候就有的空合并了。

> 就是在你的数据上进行微调模型，具体看下https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/how_to_do_kie.md

**Comment by rexzhengzhihong** [comment]
其实我也知道加表格模型预测很麻烦。但是用关键信息提取ser。对于里面有表格的表单好像确实会出一些问题。比如
1、两空太近合成一空
2、有的空会丢掉
3、标注的时候表格的每个空的要去标注 一个不同的名称，工作量有一些
这些可以解决吗

**Comment by andyjpaddle** [comment]
先调下后处理参数试试吧

**Comment by izhaolinger** [comment]
> 可以看下det和det+rec下的预处理和后处理参数是不是一致

您好，我也遇到了这样的问题，我训练的检测模型很准确，我现在又训练了个识别模型，结合起来用时，原本能检测到的文字区域会丢失一两个。请问我应该怎么做呢

**Comment by boreas-l** [comment]
> 可以看下det和det+rec下的预处理和后处理参数是不是一致

您好，我也有这个问题，就是已经检测到文字了，但是识别的时候漏字了。我看了一下代码，是将文字检测的结果img_crops输入进行文字识别，我也把img_crop的结果保存了，发现确实有检测到文字，而且也比较清晰，但文字识别rec就是漏了一个字。请问一下，预处理和后处理哪里会有问题呢？多谢多谢。

**Comment by D715-ky** [comment]
> > 可以看下det和det+rec下的预处理和后处理参数是不是一致
> 
> 您好，我也有这个问题，就是已经检测到文字了，但是识别的时候漏字了。我看了一下代码，是将文字检测的结果img_crops输入进行文字识别，我也把img_crop的结果保存了，发现确实有检测到文字，而且也比较清晰，但文字识别rec就是漏了一个字。请问一下，预处理和后处理哪里会有问题呢？多谢多谢。

请问您找到预处理和后处理调整的地方了吗？同样的问题，谢谢
