### ISSUE TITLE
字认不到

### ISSUE THREAD

**Issue by similang** [PaddlePaddle/PaddleOCR#9568]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win 11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleOCR
- 运行指令/Command Code：ocr = PaddleOCR(lang='en', use_angle_cls=True, show_log=False, enable_mkldnn=True, use_space_char=True, use_dilation=True)
- 完整报错/Complete Error Message：

![image](https://user-images.githubusercontent.com/7208012/228255362-e0ba98a8-9a55-48c6-b1c4-b005a28c2d47.png)

PaddleOCR 的正确率高，可惜， 有时候会认不到字 - 如图，第一张是原图，第二张是改了原图， 都认不到字-不明白原因。。。

认不到斜字？

**Comment by similang** [comment]
![image](https://user-images.githubusercontent.com/7208012/228710482-17a88bd8-bb98-4e2a-a0a0-b77e5ef760c6.png)

如图 - 差不多一样的图片，一个认得到，一个不能。。。。为啥？

**Comment by andyjpaddle** [comment]
直接调用识别模型识别不到吗，这种图片不需要用检测模型

**Comment by similang** [comment]
其实这图就是因为有些字识得到有写不能所以放大来看看; 
还有不同得padding和resize结果也不同； 
用得是英文识别模型 
顺便看看这： https://github.com/PaddlePaddle/PaddleOCR/issues/9633
