### ISSUE TITLE
PaddleOCR 这个例子只有文字结果怎么没返回每个字的位置？

### ISSUE THREAD

**Issue by alexhmyang** [PaddlePaddle/PaddleOCR#9570]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E6%89%8B%E5%86%99%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md

PaddleOCR 这个例子只有文字结果怎么没返回每个字的位置？
哪里能返回每个字的位置呢，谢谢

**Comment by BaoBaoJianqiang** [comment]
自己训练吧，或者投影
