### ISSUE TITLE
Error: "SSL: WRONG_VERSION_NUMBER"

### ISSUE THREAD

**Issue by Existance29** [PaddlePaddle/PaddleOCR#9571]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
Attempting to run paddleocr throws the following error:

`[SSL:WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)`

Python version: 3.7
Pip version: 10.0.1

- 系统环境/System Environment：MacOS 10.13
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.3 
- 完整报错/Complete Error Message：
![app screenshot](https://media.discordapp.net/attachments/1078089174688727040/1090246548845240440/Screen_Shot_2023-03-28_at_4.10.08_PM.png?width=1910&height=962)

**Comment by HissaanAli** [comment]
I'm getting the same error.

**Comment by HissaanAli** [comment]
I ran it on my mac (m1 pro) and my pc, and I got the same error. However running it on google colab, with the same commands worked fine. 
Not sure what's going on here.

**Comment by multics** [comment]
That's because recent macOS is using LibreSSL, which is not compatible with urllib3.

@tink2123 Could you please help on it? I saw you were assigned on this issue. Thanks
