### ISSUE TITLE
python tools/infer_det.py 报错，请教

### ISSUE THREAD

**Issue by austinleeee** [PaddlePaddle/PaddleOCR#9576]
在 本地CPU跑没问题

上传服务器后 运行却报错

错误说明如下

![image](https://user-images.githubusercontent.com/116559785/228442424-c60fcb2f-8f08-42b1-a700-e7952c1e7184.png)

**Comment by tink2123** [comment]
更新一下服务器上 opencv 的版本

**Comment by austinleeee** [comment]
> 更新一下服务器上 opencv 的版本

谢谢，发现确实是我opencv的版本问题
