### ISSUE TITLE
怎么提高ocr识别精度

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#9577]
通过python脚本，PaddleOCR.ocr进行推理(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#22-python%E8%84%9A%E6%9C%AC%E4%BD%BF%E7%94%A8),
识别合同页文字内容，仅前18行就出现5处文字识别错误的情况不含空格，另外空格识别视乎很少能准确识别(已开启use_space_char)
![image](https://user-images.githubusercontent.com/49382323/228443293-166425b3-1f33-4341-b348-d72885c379ce.png)
尝试锐化文字再进行ocr，但识别精度视乎更差，错误率反而提升了，锐化前后比对效果如下
![image](https://user-images.githubusercontent.com/49382323/228444659-4668a9aa-489f-437a-a332-42d9c2f43945.png)
请问有什么办法能降低识别的错误率，本机paddle相关版本如下图:
![image](https://user-images.githubusercontent.com/49382323/228447106-25be46d2-054a-4bc4-9d03-2dc701eea0b5.png)

**Comment by jingsongliujing** [comment]
建议换一个大点的模型

**Comment by kerry-weic** [comment]
您说的大模型是指ch_ppocr_server_v2.0_det、ch_ppocr_server_v2.0_rec这两个吗？ 我本地尝试过不知为何识别效果没PP-OCRv3模型识别效果好。修改过paddleocr.py源代码让其支持ppocr_server模型，推理代码代码片段如下
用不同模型对比结果差异对比如下:







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 上午9:11
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 怎么提高ocr识别精度 (Issue #9577)





 
建议换一个大点的模型

**Comment by kerry-weic** [comment]
尝试修改后，精度有所提高但是依旧有识别错误的情况，比如第5行的"重"依旧还是被识别成"董"字。
另外想咨询下，fastdeploy(simple_serving)服务化部署后，怎么在请求中添加use_dilation自定义参数。尝试再请求参数parameters&nbsp;中添加无效，代码片段如下:

采用http请求方式访问，参考示例代码：https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/serving/simple_serving#3-%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%B7%E6%B1%82




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 晚上8:09
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 怎么提高ocr识别精度 (Issue #9577)





 
扩大一下检测框边缘，添加参数： --use_dilation=True

**Comment by ghazalli** [comment]
> 扩大一下检测框边缘，添加参数： --use_dilation=True

Hi, how to expand the edge of detection frame? Is there any configuration to this? thank you

**Comment by kerry-weic** [comment]
扩大一下检测框边缘，按我的理解是图片上下左右多留一定的空白区域
