### ISSUE TITLE
det预测的时候。同一行离得近的两空会预测成一个空

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9578]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
调整了参数 det_db_unclip_ratio好像没有效果
![image](https://user-images.githubusercontent.com/32863094/228463184-0a6ff41f-330a-4a57-9d5d-69e23c5ea650.png)

**Comment by rexzhengzhihong** [comment]
![image](https://user-images.githubusercontent.com/32863094/228464687-6b93238c-ff6a-4d14-b108-613eabebbead.png)

**Comment by tink2123** [comment]
确实离的非常近，通过检测暂时无法解决，可以试下表格识别模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/table/README_ch.md

**Comment by rexzhengzhihong** [comment]
那我一个图片里面有的表格 有文本的怎么处理？？
