### ISSUE TITLE
paddleocr 模型加载路径？如何直接使用模型？

### ISSUE THREAD

**Issue by ahong007007** [PaddlePaddle/PaddleOCR#9580]
由于电脑设置了代理，运行命令**paddleocr --image_dir=moxi.pdf --type=structure --table=true --ocr=false**的时候模型下载不了。

已经用其他工具下载了ch_PP-OCRv3_rec_infer.tar ，请问这个文件放在那个位置？加载模型的时候，可以直接使用而不是再次下载模型？
![image](https://user-images.githubusercontent.com/22077027/228527969-1cb8d863-22fe-4796-ae1b-3f3072b67079.png)

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by tink2123** [comment]
修改参数 rec_model_dir 到指定模型路径，参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/whl.md#31-%E4%BB%A3%E7%A0%81%E4%BD%BF%E7%94%A8

**Comment by lanricheng** [comment]
您解决这个问题了吗，我也遇到了同样的问题

**Comment by wangqiang9** [comment]
```
ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}',
                rec_char_dict_path='{your_rec_char_dict_path}', cls_model_dir='{your_cls_model_dir}',
                use_angle_cls=True)
```

> 您解决这个问题了吗，我也遇到了同样的问题

**Comment by Maple0709** [comment]
问题解决了吗？模型已经下载存储到本地，我使用以下代码：
ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}',
                rec_char_dict_path='{your_rec_char_dict_path}', cls_model_dir='{your_cls_model_dir}',
                use_angle_cls=True)
每次初始化仍然会在线上下载模型

**Comment by TWa961600** [comment]
> 问题解决了吗？模型已经下载存储到本地，我使用以下代码：問題解決了嗎？模型已經下載儲存到本地，我使用以下程式碼： ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}',ocr = PaddleOCR(det_model_dir='{your_det_model_dir}', rec_model_dir='{your_rec_model_dir}', rec_char_dict_path='{your_rec_char_dict_path}', cls_model_dir='{your_cls_model_dir}',rec_char_dict_path='{your_rec_char_dict_path}', cls_model_dir='{your_cls_model_dir}', use_angle_cls=True)  use_angle_cls=真） 每次初始化仍然会在线上下载模型  每次初始化仍然會在線上下載模型

請問您解決了嗎?我指定路徑，也是會下載預設模型
