### ISSUE TITLE
模型的Init和Infer可以分开吗？

### ISSUE THREAD

**Issue by zuoyizhongguo** [PaddlePaddle/PaddleOCR#9588]
模型的Init和Infer可以分开吗？
官方很多的案例是初始化和预测在一起的，实际使用时初始化一次就可以，预测需要单独在一个函数里的。

**Comment by WilliamQf-AI** [comment]
可以，我就是这样用的

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
