### ISSUE TITLE
中英文识别模型测试出现shape不匹配问题

### ISSUE THREAD

**Issue by maomaoyuchengzi** [PaddlePaddle/PaddleOCR#959]
报错：
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 8, 56] and the shape of Y = [1, 256, 8, 55]. Received [56] in X is not equal to [55] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]
报错位置：
predict_rec.py 104行：
            self.input_tensor.copy_from_cpu(norm_img_batch)# 设置输入
            self.predictor.zero_copy_run()       # 运行predictor
其中norm_img_batch是单张图，shape=(1,3,32,220)
设置测试参数：
--image_dir="./img/812_whole_passport_1_13.jpg"
--rec_model_dir="./PaddleOCR/inference/ch_ppocr_server_v1.1_det_infer"
--rec_char_type="ch"
--use_space_char=False

**Comment by LDOUBLEV** [comment]
可否发一下你的测试图像，我这边测试下

**Comment by maomaoyuchengzi** [comment]
> 可否发一下你的测试图像，我这边测试下

怎样发送给你？

**Comment by LDOUBLEV** [comment]
贴在评论区，或者发我邮箱，liuweiwei06@baidu.com

**Comment by LDOUBLEV** [comment]
轻量模型的效果，
![image](https://user-images.githubusercontent.com/26592129/96548861-2ef9da80-12e1-11eb-82c1-caf24d4c38c0.png)
你加载错模型了，识别模型的路径指定的是检测模型
![image](https://user-images.githubusercontent.com/26592129/96548890-41741400-12e1-11eb-8b79-bac46dfbc944.png)

**Comment by maomaoyuchengzi** [comment]
> 轻量模型的效果，
> ![image](https://user-images.githubusercontent.com/26592129/96548861-2ef9da80-12e1-11eb-82c1-caf24d4c38c0.png)
> 你加载错模型了，识别模型的路径指定的是检测模型
> ![image](https://user-images.githubusercontent.com/26592129/96548890-41741400-12e1-11eb-8b79-bac46dfbc944.png)

谢谢！

**Comment by Jitesh4389** [comment]
Same issue i am facing

InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 24, 42] and the shape of Y = [1, 256, 23, 41]. Received [24] in X is not equal to [23] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
      [operator < elementwise_add > error]

**Comment by DarkSQL9527** [comment]
Same issue i am facing

InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 24, 42] and the shape of Y = [1, 256, 23, 41]. Received [24] in X is not equal to [23] in Y at i:2.
[Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
[operator < elementwise_add > error]

**Comment by thsno02** [comment]
This is a consequence of the inaccurate detection model since the detection model yields multiple bounding boxes and some of them can't resize correctly in the recognition preprocess.

The original code is shown below<sup>1</sup> :

```
void CrnnResizeImg::Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio,
                        bool use_tensorrt,
                        const std::vector<int> &rec_image_shape) {
  int imgC, imgH, imgW;
  imgC = rec_image_shape[0];
  imgH = rec_image_shape[1];
  imgW = rec_image_shape[2];


  imgW = int(imgH * wh_ratio);


  float ratio = float(img.cols) / float(img.rows);
  int resize_w, resize_h;


  if (ceilf(imgH * ratio) > imgW)
    resize_w = imgW;
  else
    resize_w = int(ceilf(imgH * ratio));


  cv::resize(img, resize_img, cv::Size(resize_w, imgH), 0.f, 0.f,
             cv::INTER_LINEAR);
  cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                     int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                     {127, 127, 127});
}
```

This code doesn't take two scenarios into consideration:

+ The image height is larger than `imgH`, that is `img.rows>imgH`. 
+ The multiplication between `imgH` and `wh_ratio` may produce a larger value than the designed image width, that is ` int(imgH * wh_ratio) > imgW `.

Thus, the code should be

```
void CrnnResizeImg::Run(const cv::Mat &img, cv::Mat &resize_img, float wh_ratio,
                        bool use_tensorrt,
                        const std::vector<int> &rec_image_shape) {
  int imgC, imgH, imgW;
  imgC = rec_image_shape[0];
  imgH = rec_image_shape[1];
  imgW = rec_image_shape[2];

  // @thsno02: handle the dimension mismatch issue
  if (imgW <= int(imgH * wh_ratio))
    imgW = int(imgH * wh_ratio);


  float ratio = float(img.cols) / float(img.rows);
  int resize_w, resize_h;

  // @thsno02: resize the image height
  resize_h = imgH;

  // @thsno02: use resize_h instead of imgH
  if (ceilf(resize_h * ratio) > imgW)
    resize_w = imgW;
  else
    resize_w = int(ceilf(resize_h * ratio));


  cv::resize(img, resize_img, cv::Size(resize_w, resize_h), 0.f, 0.f,
             cv::INTER_LINEAR);
  cv::copyMakeBorder(resize_img, resize_img, 0, 0, 0,
                     int(imgW - resize_img.cols), cv::BORDER_CONSTANT,
                     {127, 127, 127});
}
```

# Footnotes

<a name="ft1">[1]</a>: https://github.com/PaddlePaddle/PaddleOCR/blob/76fefd56f86f2809a6e8f719220746442fbab9f3/deploy/cpp_infer/src/preprocess_op.cpp#L108-L131
