### ISSUE TITLE
请问有onnx_format版本量化算子的ch_PP-OCRv3_rec_slim模型吗？

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleOCR#9590]
你好，我想要使用https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md中
![image](https://user-images.githubusercontent.com/96160062/228751849-f029f07e-ad22-4287-bc28-ef2dfb755ff6.png)

这个模型的onnx_format版本，请问有办法获取到吗？非常感谢。这个版本模型中的量化算子是fake_q_dq版本的，只适合paddle inference，但是我想转到onnxruntime EP运行

**Comment by herbzhao** [comment]
同问，否则需要重新量化又要下载数据？

**Comment by herbzhao** [comment]
> 你好，我想要使用[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md中](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md%E4%B8%AD) ![image](https://user-images.githubusercontent.com/96160062/228751849-f029f07e-ad22-4287-bc28-ef2dfb755ff6.png)
> 
> 这个模型的onnx_format版本，请问有办法获取到吗？非常感谢。这个版本模型中的量化算子是fake_q_dq版本的，只适合paddle inference，但是我想转到onnxruntime EP运行
 
请问最终你如何解决这个问题的？

**Comment by sanbuphy** [comment]
> > 你好，我想要使用[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md中](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md%E4%B8%AD) ![image](https://user-images.githubusercontent.com/96160062/228751849-f029f07e-ad22-4287-bc28-ef2dfb755ff6.png)
> > 这个模型的onnx_format版本，请问有办法获取到吗？非常感谢。这个版本模型中的量化算子是fake_q_dq版本的，只适合paddle inference，但是我想转到onnxruntime EP运行
> 
> 请问最终你如何解决这个问题的？

自己产出，没有官方提供

**Comment by herbzhao** [comment]
> > > 你好，我想要使用[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md中](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md%E4%B8%AD) ![image](https://user-images.githubusercontent.com/96160062/228751849-f029f07e-ad22-4287-bc28-ef2dfb755ff6.png)
> > > 这个模型的onnx_format版本，请问有办法获取到吗？非常感谢。这个版本模型中的量化算子是fake_q_dq版本的，只适合paddle inference，但是我想转到onnxruntime EP运行
> > 
> > 
> > 请问最终你如何解决这个问题的？
> 
> 自己产出，没有官方提供

ok产出的模型是不是还是float32的？之后要onnx quantize 一遍？
