### ISSUE TITLE
angle of text

### ISSUE THREAD

**Issue by changcw83** [PaddlePaddle/PaddleOCR#9592]
what is the easiest way to distinguish angle of text, especially 0 degree versus 180 degree?

**Comment by wangxinzhe0617** [comment]
> what is the easiest way to distinguish angle of text, especially 0 degree versus 180 degree?

可以训练分类器。但是0跟180很容易混。最好是联合投票判断。

**Comment by TuanBC** [comment]
There is a classifier model in the repo for this task. Or if you want to explore another option, there is another model available in PaddleClas repo as well.

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/en/PULC/PULC_textline_orientation_en.md
