### ISSUE TITLE
Custom Dataset adequate annotation for text detection and recognition

### ISSUE THREAD

**Issue by mahachaaben99** [PaddlePaddle/PaddleOCR#9593]
Hello gyus , I have a custom dataset and I woud like to know exactly the annotation format I should follow while labeling my dataset in order to train PaddleOCR models on it

**Comment by sumitclearquote** [comment]
@maziqueen79 Could you tell me what the appropriate annotation format is here?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
