### ISSUE TITLE
请教一下ppstructure只能解析图片内容？文档已经是PDF电子版(内容可以复制)，需要建立key-value对的信息抽取，为什么还要转换成图片格式？识别后的版面分析和OCR能力，一定可以比电子原版效果好？

### ISSUE THREAD

**Issue by ahong007007** [PaddlePaddle/PaddleOCR#9596]
请教一下ppstructure只能解析图片内容？文档已经是PDF电子版(内容可以复制)，需要建立key-value对的信息抽取，**为什么还要转换成图片格式**？图片识别后的版面分析和OCR能力，一定可以比电子原版效果好？

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by ahong007007** [comment]
key-value对比较多，而且一天xxxxxK的数据量，人工复制效率低。
既然是文档解析，转换成jpg后就多余了吧

**Comment by Wall-ee** [comment]
> key-value对比较多，而且一天xxxxxK的数据量，人工复制效率低。
> 
> 既然是文档解析，转换成jpg后就多余了吧

兄弟找到解决方案了吗？示例只有命令行版本……

**Comment by WilliamQf-AI** [comment]
> key-value对比较多，而且一天xxxxxK的数据量，人工复制效率低。 既然是文档解析，转换成jpg后就多余了吧

既然可以复制文字，那说明是标准pdf啊，那就写代码提取pdf文字，然后分析kv辨析就好了，跟ocr没关系啊

**Comment by shiyutang** [comment]
@WilliamQf-AI 有没有相关参考代码链接可以提供呢？

**Comment by WilliamQf-AI** [comment]
> @WilliamQf-AI 有没有相关参考代码链接可以提供呢？
提取文字可以使用google的pdfium调用api：FPDFText_CountChars， FPDFText_GetText即可。链接如下：https://code.google.com/p/pdfium/wiki/Build

**Comment by shiyutang** [comment]
好的，以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
