### ISSUE TITLE
paddleocr对服务器资源最低要求

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#9598]
在不做模型finetune，只部署推理模型的场景下，请问paddleocr对服务器的资源（GPU或CPU、内存）有最低要求是多少？

**Comment by UserWangZz** [comment]
使用轻量模型在边端设备上也可以运行，显存使用也和输入图像大小有关，具体根据实际需求决定

**Comment by skyroot** [comment]
同问
