### ISSUE TITLE
Request Word Level Bounding Box 

### ISSUE THREAD

**Issue by jyotiyadav94** [PaddlePaddle/PaddleOCR#9600]
- System Environment：Google collab

I tried the below piece of codein order to get the word level bounding boxes similar to the pytesseract .
I have taken the referece from here - https://github.com/PaddlePaddle/PaddleOCR/issues/9485
Can anyone suggest something to work on word level bounding boxes
`
import io
import cv2
import paddleocr

ocr = paddleocr.PaddleOCR(det_lang='ml',use_gpu=False, use_angle_cls=True,det_algorithm= "DB")

img = cv2.imread('path of the image')

results = ocr.ocr(img)

print('results',results)

`
@NaumanHSA
@Taghreed7878

**Comment by NaumanHSA** [comment]
@jyotiyadav94 please check my comment in #9485.
