### ISSUE TITLE
进行版面还原时 表格还原出错

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9601]
进行版面还原后能成功识别表格但是无法生成DOC文档

![6ZRLEG8MPU%HO@3FORAFSDQ](https://user-images.githubusercontent.com/56247915/228806998-bab5cc79-3cf4-4f07-bcf5-e920949014c4.png)
请问这是什么问题 显示越界

**Comment by AIwang666** [comment]
> 我也遇到了同样的问题，我出这个错误的地方都是比较复杂的表格，而且看excel表格文件可以发现，pdf内的表格的识别出现错误，可能是还原表格时错误的计算了行列数量。

你用的自己的数据集进行的训练吗

**Comment by crazyyoung** [comment]
> > 我也遇到了同样的问题，我出这个错误的地方都是比较复杂的表格，而且看excel表格文件可以发现，pdf内的表格的识别出现错误，可能是还原表格时错误的计算了行列数量。
> 
> 你用的自己的数据集进行的训练吗

没有，我直接使用了官方提供的模型
