### ISSUE TITLE
关于识别模型的序列问题

### ISSUE THREAD

**Issue by zhang0225** [PaddlePaddle/PaddleOCR#9603]
作者您好，我使用了crnn作为识别模型部署至移动端，我的识别数据集格式固定，其中有涉及年份的一段内容，项目是在去年完成的，所以数据集中与年份有关的都是22，今年在实际应用时，发现23都被识别为了22，猜测大概率是因为数据集的问题。
  在不补充数据集的前提下能解决这个问题么，因为就算采集了今年的数据集明年再使用的时候还是有相同的问题，我尝试了使用TextRender、StyleText、GAN等方法生成文本，其中TextRender生成数据与真实样本风格差距较大，与真实数据混合后训练效果不佳，还是大部分被识别为22，StyleText、GAN不能按照指定内容生成，所以目前这三个方法都无法解决这个问题，我又尝试了官网提供的通用模型（PPOCRV3），发现23能被识别出来，但是因为场景问题通用模型整体识别率不高，所以想请教一下您关于这个问题的理解与解决方法。

**Comment by UserWangZz** [comment]
这个可以找一批日期的数据集混合训练，增强对数字的敏感度，还有就是进行数据合成
