### ISSUE TITLE
How to properly specify the directory for layout_model

### ISSUE THREAD

**Issue by themantalope** [PaddlePaddle/PaddleOCR#9605]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

Hi all,

I have a docker image which tries to download and include a layout model in the image so `PPStructure` does not need to download the model. This works well for models such as the `PP-OCR-V3` models. Here is an example in the Dockerfile:

```dockerfile

# en_PP-OCRv3_rec_infer
RUN wget --progress=bar https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar
RUN tar xf /PaddleOCR/inference/en_PP-OCRv3_rec_infer.tar -C /PaddleOCR/inference/
ENV REC_INFER_MODEL_EN=/PaddleOCR/inference/en_PP-OCRv3_rec_infer

...

RUN wget --progress=bar https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_infer.tar 
RUN tar xf /PaddleOCR/inference/picodet_lcnet_x1_0_fgd_layout_infer.tar -C /PaddleOCR/inference/
ENV LAYOUT_INFER_MODEL=/PaddleOCR/inference/picodet_lcnet_x1_0_fgd_layout_infer
...
```

Then in the python code, I specify the model location:

```python
STRUCT_OPT_DICT = {
    'structure_version':'PP-StructureV2',
    'lang':'en',
    'table_model_dir':os.environ['TABLE_STRUCTURE_INFER_MODEL'],
    'rec_model_dir':os.environ['REC_INFER_MODEL_EN'],
    'cls_model_dir':None,
    'det_model_dir':os.environ['DET_INFER_MODEL_EN'],
    'layout_model_dir':os.environ['LAYOUT_INFER_MODEL'],
}

table_engine = PPStructure(show_log=True, **STRUCT_OPT_DICT)

```

However, the layout model still downloads every time.

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.4.2
-  PaddleOCR：paddleclas==2.5.1, paddleocr==2.6.1 
- 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by pepperav** [comment]
same for me on AWS Lambda which trigger errors about readonly file-system

**Comment by mllife** [comment]
@pepperav you can specific tmp directory in lambda to get over this issue, (tmp storage is good for default models) https://docs.aws.amazon.com/lambda/latest/dg/API_EphemeralStorage.html , but

@themantalope , the issue that "PPStructure" class is unable to load models from the specified directory is real pain, i am also trying to do the inference using pre-trained models on publaynet, but no results - pls take a look here for more details - https://github.com/PaddlePaddle/PaddleOCR/issues/10476

**Comment by jinyichao** [comment]
@themantalope the problem is because the file name from https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_infer.tar are `model.pdiparams` and `model.pdmodel`, while the code inside PPStructure will look for the file named as `inference.pdiparams` and `inference.pdmodel`. 

So I guess a simple solution would be just renaming the files from `mode.*` into `inference.*` after you unzip the downloaded tar file, in your Dockerfile.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
