### ISSUE TITLE
fastDeploy simple_serving服务化部署，如何查看和设置推理模型参数

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#9606]
ocr所支持的模型参数: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/inference_args.md
想咨询两个问题
1、当前所使用了推理模型参数他们对应配置的值.
启动服务后，进行推理操作没看到相关的log输出
![image](https://user-images.githubusercontent.com/49382323/229006686-d7acac3e-30c9-4414-82d5-950e3be0d974.png)

2、客户端请求时怎么设置自定义的推理参数.
尝试在parameters请求参数中增加推理参数，视乎没起作用
![image](https://user-images.githubusercontent.com/49382323/229007263-4b0504f2-db5a-4332-b953-4d1767ae87be.png)
客户端代码参考:https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/serving/simple_serving#3-%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%B7%E6%B1%82

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
