### ISSUE TITLE
模型det_r50_drrg_ctw.yml训练过程中计算损失函数loss报错

### ISSUE THREAD

**Issue by ZHUHF123** [PaddlePaddle/PaddleOCR#9608]
det_drrg_loss.py
line 42, in balance_bce_loss
    assert paddle.all(pred >= 0) and paddle.all(pred <= 1)
AssertionError

**Comment by kognyouze123** [comment]
同问题，感觉是数据标注问题？我是把数字写成特殊字符作为数据了

**Comment by ZHUHF123** [comment]
> 同问题，感觉是数据标注问题？我是把数字写成特殊字符作为数据了

应该不是数据标注的问题，写的脚本统一标注的；分出来一小部分也能训练，整体训练就报错了
