### ISSUE TITLE
PPStructure中KIE任务中RE子任务使用带蒸馏版本的模型预测报“Backbone” KeyError错但yml配置文件中有Backbone字段

### ISSUE THREAD

**Issue by galaxyknight** [PaddlePaddle/PaddleOCR#9609]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS7+Python3.8+PaddleOCR2.6
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python ./tools/infer_kie_token_ser_re.py \
>   -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_sinovatio_zh_udml.yml \
>   -o Architecture.Backbone.checkpoints=/data01/wj/PythonWorkspace/PaddleOCR-release-2.6/output/re_vi_layoutxlm_sinovatio_zh_udml/best_accuracy \
>   Global.infer_img=/data01/wj/public_data/dataset/sinovatio_data/dev/dev_img/ \
>   -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_sinovatio_zh_udml.yml \
>   -o_ser Architecture.Backbone.checkpoints=/data01/wj/PythonWorkspace/PaddleOCR-release-2.6/output/ser_vi_layoutxlm_sinovatio_zh_udml/best_accuracy
- 完整报错/Complete Error Message：
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/profiler/profiler_statistic.py:1402: DeprecationWarning: invalid escape sequence \(
  kernel_name_pattern = re.compile('(.+?)(<.*>)(\(.*\))')
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/tensor/random.py:31: DeprecationWarning: invalid escape sequence \e
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/distributed/parallel.py:87: SyntaxWarning: "is" with a literal. Did you mean "=="?
  ) or backend is 'xccl':
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py:438: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self._algo is 'min_max':
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/incubate/nn/layer/fused_linear.py:20: DeprecationWarning: invalid escape sequence \_
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_optimizer_stage2.py:208: DeprecationWarning: invalid escape sequence \.
  "The param name passed to the optimizer doesn't follow .+_[0-9]+\..+ patter, "
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/dataset/common.py:38: DeprecationWarning: invalid escape sequence \T
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/sparse/unary.py:555: DeprecationWarning: invalid escape sequence \p
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/sparse/unary.py:588: DeprecationWarning: invalid escape sequence \p
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/sparse/nn/functional/transformer.py:29: DeprecationWarning: invalid escape sequence \s
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/sparse/nn/functional/activation.py:64: DeprecationWarning: invalid escape sequence \e
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/paddle/sparse/nn/functional/activation.py:149: DeprecationWarning: invalid escape sequence \_
  """
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/iterative.py:10: DeprecationWarning: Please use `LinearOperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import LinearOperator
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/utils.py:7: DeprecationWarning: Please use `asmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.sputils` namespace is deprecated.
  from scipy.sparse.sputils import asmatrix
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/utils.py:9: DeprecationWarning: Please use `aslinearoperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator, LinearOperator, \
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/utils.py:9: DeprecationWarning: Please use `LinearOperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator, LinearOperator, \
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/utils.py:9: DeprecationWarning: Please use `IdentityOperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator, LinearOperator, \
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/lsqr.py:56: DeprecationWarning: Please use `aslinearoperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/lsmr.py:24: DeprecationWarning: Please use `aslinearoperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:7: DeprecationWarning: Please use `is_pydata_spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.sputils` namespace is deprecated.
  from scipy.sparse.sputils import is_pydata_spmatrix
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:47: DeprecationWarning: Please use `aslinearoperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator, LinearOperator
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:47: DeprecationWarning: Please use `LinearOperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
  from scipy.sparse.linalg.interface import aslinearoperator, LinearOperator
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:50: DeprecationWarning: Please use `isdense` from the `scipy.sparse` namespace, the `scipy.sparse.sputils` namespace is deprecated.
  from scipy.sparse.sputils import isdense, is_pydata_spmatrix
/home/rhino/anaconda3/envs/zkq_py38_paddleocr_cuda11/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:50: DeprecationWarning: Please use `is_pydata_spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.sputils` namespace is deprecated.
  from scipy.sparse.sputils import isdense, is_pydata_spmatrix
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "./tools/infer_kie_token_ser_re.py", line 186, in <module>
    config, ser_config, device, logger = preprocess()
  File "./tools/infer_kie_token_ser_re.py", line 162, in preprocess
    config = merge_config(config, FLAGS.opt)
  File "/data01/wj/PythonWorkspace/PaddleOCR-release-2.6/tools/program.py", line 113, in merge_config
    cur = cur[sub_key]
KeyError: 'Backbone'

**Comment by an1018** [comment]
使用dygraph的代码试试

**Comment by galaxyknight** [comment]
dygraph的代码具体在哪啊，我在PaddleOCR-release-2.6这个版本了没找到

**Comment by mxzgn** [comment]
![image](https://user-images.githubusercontent.com/25200723/234532485-9aa967f0-bce2-442d-af1f-636d7eddb0c0.png)
试一试改为这样子

**Comment by first236108** [comment]
> ```
> -o Architecture.Backbone.checkpoints=/data01/wj/PythonWorkspace/PaddleOCR-release-2.6/output/re_vi_layoutxlm_sinovatio_zh_udml/best_accuracy
> ```
> 
> 把这个替换成
> 
> ```
> -o Architecture.Models.Student.Backbone.checkpoints=/data01/wj/PythonWorkspace/PaddleOCR-release-2.6/output/re_vi_layoutxlm_sinovatio_zh_udml/best_accuracy
> ```
你是对的，这个方法对我有用，确实是配置路径问题，蒸馏配置Backbone不在根节点：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/24523802/ab5af4e2-dd34-44ae-b398-ddbcb50eee73)

**Comment by zhanglong2100** [comment]
你在预测的时候可以不用re_vi_layoutxlm_sinovatio_zh_udml文件，改成re_vi_layoutxlm_sinovatio_zh.yml文件。你用udml文件，即使将命令改成Architecture.Models.Student.Backbone.checkpoints这样解决这个问题，但也会遇到其它问题： 'DistillationModel' object has no attribute 'backbone'、ser_results[0]  KeyError: '0'。
