### ISSUE TITLE
预训练模型和推理模型的问题

### ISSUE THREAD

**Issue by chenhaofen** [PaddlePaddle/PaddleOCR#961]
用推理模型ch_ppocr_server_v1.1_det_infer 直接预测就一点错误都没有,如果用预训练模型（ch_ppocr_server_v1.1_det_train）去对已有的数据进行训练就全部都错，格式是icdar2015的格式。我都好奇怪

**Comment by littletomatodonkey** [comment]
如果需要直接预测的话，建议使用`ch_ppocr_server_v1.1_det_infer`，如果需要finetune的话，建议使用`ch_ppocr_server_v1.1_det_train `进行finetune，这两个不是完全相同的，不过如果全部都错的话，感觉是你导出的过程有问题

**Comment by chenhaofen** [comment]
> 如果需要直接预测的话，建议使用`ch_ppocr_server_v1.1_det_infer`，如果需要finetune的话，建议使用`ch_ppocr_server_v1.1_det_train `进行finetune，这两个不是完全相同的，不过如果全部都错的话，感觉是你导出的过程有问题

我是直接用icdar的格式来凑成数据集来做训练的  训练完损失也就0.1的样子
还没有inference出来  我是直接用这个命令来测试的 python3 tools/infer_det.py -c configs/det/det_mv3_db_v1.1.yml -o TestReader.infer_img="./doc/imgs_en/img_10.jpg" Global.checkpoints="./output/det_db/best_accuracy"   用了这里 就发现了直接预测和finetune完后效果相差就好大了

**Comment by littletomatodonkey** [comment]
> 就发现了直接预测和finetune完后效果相差就好大

是哪个好哪个坏，你贴一下不同模型的得到方式和效果图吧

**Comment by chenhaofen** [comment]
> > 就发现了直接预测和finetune完后效果相差就好大
> 
> 是哪个好哪个坏，你贴一下不同模型的得到方式和效果图吧
![1](https://user-images.githubusercontent.com/30793486/96529315-6bb0dc00-12b7-11eb-9701-bf6f8dac417c.jpg)
这个是直接用推理模型的 

下面是直接用预训练模型做训练的 
![1603157703(1)](https://user-images.githubusercontent.com/30793486/96529369-8c793180-12b7-11eb-8a9f-4e0f47c87251.png)

出来的结果是这样的
./doc/imgs/test.jpg	[]
即为空  什么都没有

**Comment by 013292** [comment]
遇到相同的问题，按照[closed issues # 1015](https://github.com/PaddlePaddle/PaddleOCR/issues/1015)复现问题依旧，回复中提供的修改.yml中PostProcess参数的方法并没有奏效。请问是否有解释 @LDOUBLEV @littletomatodonkey ?谢谢
