### ISSUE TITLE
当使用paddleocr对船舶的水尺读数时，发现只能检测出上面部分的读数，对于下面的部分没有识别

### ISSUE THREAD

**Issue by yuxin-zh** [PaddlePaddle/PaddleOCR#9612]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![图片](https://user-images.githubusercontent.com/81307887/229048395-55fb3d6e-5258-43e9-9b77-f6c8f626544f.png)
![图片](https://user-images.githubusercontent.com/81307887/229048569-3eaaf4f6-74ba-43e2-b1f4-d47239e0a0cb.png)

**Comment by an1018** [comment]
1、调小检测框阈值；2、也可以试试英文模型
