### ISSUE TITLE
 ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

### ISSUE THREAD

**Issue by PC-walter** [PaddlePaddle/PaddleOCR#9617]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/python3.7
- 版本号/Version：Paddle：2.1.0
- 运行指令/Command Code：PPOCRLabel --lang ch

- 完整报错/Complete Error Message：ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

**Comment by ToddBear** [comment]
Did you want to keep the args.ocr to be true when args.layout is false ?

**Comment by Yanic0420** [comment]
How to  keep the args.ocr to be true when args.layout is false ,I haven't found parameters named args.ocr and args.layout

**Comment by Kassy607** [comment]
i have the same problem;  I changed the languag to arabic and added it to the combo box and layout
