### ISSUE TITLE
How to disable the automatic model download

### ISSUE THREAD

**Issue by sejongpyo** [PaddlePaddle/PaddleOCR#9618]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：docker (fastapi)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
By following this instruction (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/whl_en.md),
Parameter description (rec, dec, cls_model_dir) says that "The path of the inference model converted by yourself, the model and params files must be included in the model path".
So, I have called this code:
`ocr_model = PaddleOCR(
    use_angle_cls=True,
    lang='en',
    dec_model_dir='/code/inference/en_PP-OCRv3_det_infer',
    rec_model_dir='/code/inference/en_PP-OCRv3_rec_infer',
    cls_model_dir='/code/inference/ch_ppocr_mobile_v2.0_cls_infer',
    rec_char_dict_path='/code/inference/en_dict.txt')`
But even if I set the custom model and params files, when it deployed in the docker (fastapi), the PaddleOCR still tries to download models.
How to hesitate from downloading models when it has been called even for the first time.

As a result it shows below error.

- 完整报错/Complete Error Message：
ocr_model = PaddleOCR(
File "/usr/local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 506, in __init__
maybe_download(params.det_model_dir, det_url)
File "/usr/local/lib/python3.8/site-packages/paddleocr/ppocr/utils/network.py", line 52, in maybe_download
os.makedirs(model_storage_directory, exist_ok=True)
File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
[Previous line repeated 1 more time]
File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.paddleocr'

**Comment by Iamlaoli** [comment]
I have also encountered this issue. May I ask how to solve this permission issue
