### ISSUE TITLE
How to install paddlepaddle for CUDA 12.1?

### ISSUE THREAD

**Issue by inesriahi** [PaddlePaddle/PaddleOCR#9620]
I have cuda 12.1, how can I install paddlepaddle on it?

**Comment by MissPenguin** [comment]
As you can see from the official website of PaddlePaddle, CUDA 12.1 has not been supported yet. https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/compile/linux-compile_en.html
