### ISSUE TITLE
如何暂时把<td></td>视为两个token

### ISSUE THREAD

**Issue by s957995299** [PaddlePaddle/PaddleOCR#9621]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 完整报错/Complete Error Message：
PP-StructureV2中如何暂时把
![image](https://user-images.githubusercontent.com/83860013/229350184-e6e737d7-0e37-4da3-b051-2f41a3b27f6c.png)
视为两个token

**Comment by MissPenguin** [comment]
PP- StructureV1中的表格识别模型就是将`<td></td>`视为2个token，可以直接使用V1或参考V1进行修改
