### ISSUE TITLE
模型进行文字检测、识别的速度问题

### ISSUE THREAD

**Issue by H-eaven-1** [PaddlePaddle/PaddleOCR#9622]
正常情况下，使用pp_ocrv3英文模型进行文字检测加识别的速度是多少呢，我输入的原始图像大小是1280×433的，每张图片只有1至两行文字，使用python ，cpu版本，目前速度1s左右

**Comment by MissPenguin** [comment]
原始图片输入后会进行resize，到长边960，你的图中文字不多的话，整体耗时应该不到500ms的，猜测原因可能有：
1. 只预测单张图，耗时算上了预热时间，一般统计耗时会跳过前面几张，比如跑100张，统计后90张的平均耗时。
2. CPU配置较低
3. 未开启MKLDNN
4. 机器上有其他任务在占用CPU

**Comment by leoterry-ulrica** [comment]
> 3\. 未开启MKLDNN

如何开启：MKLDNN
