### ISSUE TITLE
paddleocr 搞乱了 sys.path

### ISSUE THREAD

**Issue by miba2020** [PaddlePaddle/PaddleOCR#9624]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 22.04, python virtual environment, python 3.8, 3.9, 3.10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：
  >>> import sys
  >>> print(len(sys.path))
  12
  >>> from paddleocr import PaddleOCR
  >>> print(len(sys.path))
  36
  >>> print(“重复内容条数”, len(sys.path) - len(set(sys.path)))
  15
- 完整报错/Complete Error Message：

从上面看，import paddleocr 以后，sys.path 里面增加了 24 个条目，其中 15 条是重复的。
而且在这些新增的目录下定义了很多常用的 module name，比如 uilts，这就会导致模块名冲突。

如果再有一个 package 也像 paddleocr 一样在代码里操纵 sys.path ，并且也包含一个 utils 模块，那 import utils 到底会用到谁就不确定了。

paddleocr 这个项目很有用，用的人也多。希望开发者重视这个 小小的 问题，让 paddleocr 的使用体验更好。谢谢！

**Comment by quantdata2018** [comment]
我也遇到了相同的情况。在使用multiprocess.Process创建的新进程中无法找到paddleocr，引用时必须去掉paddleocr，比如from ppstructure.predict_system import StructureSystem。
1. 在python环境中直接调用时的环境变量是这样：
` ['C:\\src\\extract\\pdf-ocr\\src\\ocrparser', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\third_party\\thriftpy', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\src\\extract\\pdf-ocr', 'C:\\src\\extract\\pdf-ocr\\src', 'C:\\Users\\wizar\\AppData\\Local\\JetBrains\\PyCharmCE2022.3\\cythonExtensions', 'C:\\src\\extract\\pdf-ocr\\src\\ocrparser', 'C:\\Anaconda202303\\envs\\paddle\\python39.zip', 'C:\\Anaconda202303\\envs\\paddle\\DLLs', 'C:\\Anaconda202303\\envs\\paddle\\lib', 'C:\\Anaconda202303\\envs\\paddle', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages']`
2. 创建的进程中sys.path变成了这样，导致原来写的paddleocr引用都找不到了，importlib.import_module('paddleocr')也会返回空值：
` ['C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\..\\libs', 'C:\\src\\extract\\pdf-ocr\\src\\ocrparser', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\third_party\\thriftpy', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\src\\extract\\pdf-ocr', 'C:\\src\\extract\\pdf-ocr\\src', 'C:\\Users\\wizar\\AppData\\Local\\JetBrains\\PyCharmCE2022.3\\cythonExtensions', 'C:\\src\\extract\\pdf-ocr\\src\\ocrparser', 'C:\\Anaconda202303\\envs\\paddle\\python39.zip', 'C:\\Anaconda202303\\envs\\paddle\\DLLs', 'C:\\Anaconda202303\\envs\\paddle\\lib', 'C:\\Anaconda202303\\envs\\paddle', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\proto', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\e2e_utils', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\e2e_utils\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\layout', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\table', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\table', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\table', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\src\\extract\\pdf-ocr\\src']
from paddleocr.ppstructure.predict_system import StructureSystem
from paddleocr.ppocr.utils.network import download_with_progressbar
sys.path
['C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\..\\libs', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\third_party\\thriftpy', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\src\\extract\\pdf-ocr', 'C:\\Anaconda202303\\envs\\paddle\\python39.zip', 'C:\\Anaconda202303\\envs\\paddle\\DLLs', 'C:\\Anaconda202303\\envs\\paddle\\lib', 'C:\\Anaconda202303\\envs\\paddle', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages', 'C:\\src\\extract\\pdf-ocr', 'C:\\src\\extract\\pdf-ocr\\src', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\proto', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\postprocess\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\e2e_utils', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppocr\\utils\\e2e_utils\\..', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\tools\\infer', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\layout', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\table', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure\\table', 'C:\\Anaconda202303\\envs\\paddle\\lib\\site-packages\\paddleocr\\ppstructure']`
