### ISSUE TITLE
医疗票据文字检测标注问题

### ISSUE THREAD

**Issue by Abraham-2020** [PaddlePaddle/PaddleOCR#9625]
我在做医疗票据文字检测，在标注时遇到一些困惑想请教各位：

1. 像这种文字密集且版式不同的医疗票据，需要所有文字都标注吗？怎样标注训练和评估时效果会比较好呀
2. 对于有印章干扰的文字应该怎么处理呀
3. 图片如下所示。谢谢！
![2imgs_266](https://user-images.githubusercontent.com/61900951/229398202-78e2b777-bf5f-460d-a305-4dcb579a023d.jpg)
![img_720](https://user-images.githubusercontent.com/61900951/229398292-76619bfd-4470-42f5-bdf8-19ae09a91f8a.jpg)

![1imgs_1876](https://user-images.githubusercontent.com/61900951/229398117-9324bf07-72b6-4524-a8ca-62d8078bbd05.jpg)

**Comment by LDOUBLEV** [comment]
> 像这种文字密集且版式不同的医疗票据，需要所有文字都标注吗？怎样标注训练和评估时效果会比较好呀
> 对于有印章干扰的文字应该怎么处理呀
> 图片如下所示。谢谢！

标注要检测的部分即可
如果不需要检测印章中的文字，忽略印章
