### ISSUE TITLE
使用paddleocr进行中文版面还原时报错

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9626]
我进行版面还原使用的是自己的数据集，版面分析模型也是自己的推理模型，运行之后报错如下

![}MNMJZ2L2 H6(A`K3FJTC 7](https://user-images.githubusercontent.com/56247915/229400353-189f41f4-3797-4a43-a289-4b528f062bdb.png)
请问这是什么问题啊
Traceback (most recent call last):
  File "ppstructure/predict_system.py", line 315, in <module>
    main(args)
  File "ppstructure/predict_system.py", line 254, in main
    res, time_dict = structure_sys(img, img_idx=index)
  File "ppstructure/predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "C:\Users\zzz\Desktop\Code\Python\PaddleOCR-release-2.6\ppstructure\layout\predict_layout.py", line 86, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at ..\paddle\fluid\framework\operator.cc:2411)
  [operator < conv2d_fusion > error]

**Comment by AIwang666** [comment]
能不能回复一下这个问题呢

**Comment by AIwang666** [comment]
@LDOUBLEV

**Comment by AIwang666** [comment]
Traceback (most recent call last):
  File "ppstructure/predict_system.py", line 315, in <module>
    main(args)
  File "ppstructure/predict_system.py", line 254, in main
    res, time_dict = structure_sys(img, img_idx=index)
  File "ppstructure/predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "C:\Users\zzz\Desktop\Code\Python\PaddleOCR-release-2.6\ppstructure\layout\predict_layout.py", line 86, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at ..\paddle\fluid\framework\operator.cc:2411)
  [operator < conv2d_fusion > error]
这是上面说的完整的报错信息

**Comment by LDOUBLEV** [comment]
训练的时候没问题吗？训练中评估的时候有没有报错

报错提示输入tensor没有初始化，检查下你执行inference的脚本的预处理和训练评估的预处理是不是一样的

**Comment by AIwang666** [comment]
训练评估的时候没有报错

**Comment by AIwang666** [comment]
@LDOUBLEV

**Comment by LDOUBLEV** [comment]
检查下你训练的模型，执行inference的脚本的预处理 和 训练评估的预处理实现是否相同

**Comment by AIwang666** [comment]
刚刚检查了一下所使用的配置文件picodet_lcnet_x1_0_layout.yml配置是一样的 还是重复报上面的错误 @LDOUBLEV

**Comment by AIwang666** [comment]
请问如果是自己的数据集 在版面分析的字典设置方面有什么需要注意的地方吗
layout_dict_path我更换为自己的字典了

**Comment by an1018** [comment]
这部分的能执行通过吗：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/layout/README_ch.md#7-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B

**Comment by AIwang666** [comment]
> 

可以通过 我直接执行的
python3 tools/export_model.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    -o weights=output/picodet_lcnet_x1_0_layout/best_model \
    --output_dir=output_inference/
这几行指令 生成了三个模型参数文件和一个YML文件

**Comment by AIwang666** [comment]
@an1018

**Comment by AIwang666** [comment]
![3GQ EQ$Y3QCT~5L{CY9V2TT](https://user-images.githubusercontent.com/56247915/229669913-c06105ab-f117-43fc-be4e-5a3fa6bca799.png)
执行7.1后生成了四个文件 然后我直接去执行版面恢复的脚本了 就出现上述输入tensonr没有初始化的报错

**Comment by AIwang666** [comment]
![C`4XN6YWMY9Y87NEEU33 FI](https://user-images.githubusercontent.com/56247915/229670983-5adaf0b4-35c5-485f-967a-53233ef7144a.png)
模型推理也可以正常执行 @LDOUBLEV @an1018

**Comment by AIwang666** [comment]
请问 我在训练开始时自动加载了PP-picodet预训练模型 在执行inference的时候是不是应该执行如下指令：

若使用提供的预训练模型转Inference模型，或使用FGD蒸馏训练的模型，更换weights模型路径，模型转inference模型步骤如下：
python3 tools/export_model.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    --slim_config configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x2_5_layout.yml \
    -o weights=./output/picodet_lcnet_x2_5_layout/best_model \
    --output_dir=output_inference/

**Comment by AIwang666** [comment]
@LDOUBLEV @an1018

**Comment by AIwang666** [comment]
请问这个问题到底出在哪个地方呢 @an1018 @LDOUBLEV @

**Comment by AIwang666** [comment]
> 这部分的能执行通过吗：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/layout/README_ch.md#7-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B

麻烦回复一下ISSUE

**Comment by an1018** [comment]
训练、评估、推理都没问题，可能是detection代码更新和ocr集成的代码不一致了，可以通过ppstructure\layout\predict_layout.py这里debug看下，具体哪里报错

**Comment by AIwang666** [comment]
@an1018

**Comment by AIwang666** [comment]
问题出在 我用官方给出的CDLA推理模型进行版面还原时不会报错，但是用我自己的数据集，模型推理之后进行版面还原就报错了 @an1018

**Comment by an1018** [comment]
你使用OCR代码的时候，更改layout模型路径了吗

**Comment by AIwang666** [comment]
> 你使用OCR代码的时候，更改layout模型路径了吗

更改了 更改为我自己训练完推理后的模型了 字典也改为我的字典了
是不是因为我的字典中包含的元素有些多 比如我看源代码中图片的标签是figure但是我给的标签是seal

**Comment by an1018** [comment]
不是，你用CPU跑一下看看

**Comment by AIwang666** [comment]
> 不是，你用CPU跑一下看看

请问如何设置CPU 应该执行哪个指令

**Comment by AIwang666** [comment]
> 不是，你用CPU跑一下看看

是指用CPU跑版面还原吗 我在进行模型推理的时候设置的就是CPU

**Comment by AIwang666** [comment]
> 你使用OCR代码的时候，更改layout模型路径了吗

我是直接执行的命令行命令
python ppstructure/predict_system.py
 --image_dir=./docs/table/14.jpg 
--det_model_dir=inference/ch_PP-OCRv3_det_infer 
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer 
--rec_char_dict_path=./ppocr/utils/ppocr_keys_v1.txt 
--table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer 
--table_char_dict_path=./ppocr/utils/dict/table_structure_dict.txt 
--layout_model_dir=inference/chbm 
--layout_dict_path=./ppocr/utils/dict/layout_dict/layout.txt 
--vis_font_path=./doc/fonts/simfang.ttf 
--recovery=True --output=./output/
执行完之后就报错说张量没有初始化

**Comment by AIwang666** [comment]
@an1018

**Comment by AIwang666** [comment]
我感觉还是模型推理出问题了 推理出来的模型有问题 但是不知道具体在哪个环节

**Comment by lbeing** [comment]
问题解决了吗？在ppocr项目使用自己训练的版面分析模型推理时遇到同样的问题，这个版本分析模型是PaddleDetection项目中自己数据集训练的；版本都是2.6

**Comment by AIwang666** [comment]
> 问题解决了吗？在ppocr项目使用自己训练的版面分析模型推理时遇到同样的问题，这个版本分析模型是PaddleDetection项目中自己数据集训练的；版本都是2.6

没有解决 你解决了吗

**Comment by AIwang666** [comment]
@an1018

**Comment by lbeing** [comment]
> 你解决了

没有，是预处理不同
PPOCR是这个
class LayoutPredictor(object):
    def __init__(self, args):
        pre_process_list = [{
            'Resize': {
                'size': [800, 608]
            }
        }, {
            'NormalizeImage': {
                'std': [0.229, 0.224, 0.225],
                'mean': [0.485, 0.456, 0.406],
                'scale': '1./255.',
                'order': 'hwc'
            }
        }, {
            'ToCHWImage': None
        }, {
            'KeepKeys': {
                'keep_keys': ['image']
            }
        }]
        postprocess_params = {
            'name': 'PicoDetPostProcess',
            "layout_dict_path": args.layout_dict_path,
            "score_threshold": args.layout_score_threshold,
            "nms_threshold": args.layout_nms_threshold,
        }

**Comment by AIwang666** [comment]
> > 你解决了
> 
> 没有，是预处理不同 PPOCR是这个 class LayoutPredictor(object): def **init**(self, args): pre_process_list = [{ 'Resize': { 'size': [800, 608] } }, { 'NormalizeImage': { 'std': [0.229, 0.224, 0.225], 'mean': [0.485, 0.456, 0.406], 'scale': '1./255.', 'order': 'hwc' } }, { 'ToCHWImage': None }, { 'KeepKeys': { 'keep_keys': ['image'] } }] postprocess_params = { 'name': 'PicoDetPostProcess', "layout_dict_path": args.layout_dict_path, "score_threshold": args.layout_score_threshold, "nms_threshold": args.layout_nms_threshold, }

要修改PPOCR代码里的预处理和detection保持一致

**Comment by AIwang666** [comment]
> > 你解决了
> 
> 没有，是预处理不同 PPOCR是这个 class LayoutPredictor(object): def **init**(self, args): pre_process_list = [{ 'Resize': { 'size': [800, 608] } }, { 'NormalizeImage': { 'std': [0.229, 0.224, 0.225], 'mean': [0.485, 0.456, 0.406], 'scale': '1./255.', 'order': 'hwc' } }, { 'ToCHWImage': None }, { 'KeepKeys': { 'keep_keys': ['image'] } }] postprocess_params = { 'name': 'PicoDetPostProcess', "layout_dict_path": args.layout_dict_path, "score_threshold": args.layout_score_threshold, "nms_threshold": args.layout_nms_threshold, }

你在paddledetection里面的预处理是如何进行的

**Comment by AIwang666** [comment]
@lbeing 请问你的那个问题解决了吗

**Comment by AIwang666** [comment]
@lbeing 请问问题最后是如何解决的呢

**Comment by yuanyatao** [comment]
> 不是，你用CPU跑一下看看

请问您还在吗，能帮忙看看吗 @an1018

**Comment by yuanyatao** [comment]
问题已经解决：
问题出在模型导出时没有加参数 export.benchmark=True
-c
F:\deep_learning\WordDetection\PaddleDetection\configs\picodet\legacy_model\application\layout_analysis\picodet_lcnet_x1_0_layout.yml
-o
weights=output/picodet_lcnet_x1_0_layout/best_model
export.benchmark=True
--output_dir=output_inference/

**Comment by zhzspace** [comment]
我也遇到了同样的问题，目前按照下面的方法已经解决
这个问题需要在导出模型时增加一个参数：如无需导出后处理，请指定：-o export.benchmark=True（如果-o已出现过，此处删掉-o），这是官网中写的。
完整的模型导出脚本：
python3 tools/export_model.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    -o export.benchmark=True weights=output/picodet_lcnet_x1_0_layout/best_model \
    --output_dir=output_inference/
@AIwang666 @yuanyatao

**Comment by zhzspace** [comment]
我也遇到了同样的问题，目前按照下面的方法已经解决
我在导出模型时少增加一个参数解决了这个问题：如无需导出后处理，请指定：-o export.benchmark=True（如果-o已出现过，此处删掉-o），这是官网中写的。
完整的模型导出脚本：
python3 tools/export_model.py
-c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml
-o export.benchmark=True weights=output/picodet_lcnet_x1_0_layout/best_model
--output_dir=output_inference/

**Comment by beetter** [comment]
> 我也遇到了同样的问题，目前按照下面的方法已经解决 我在导出模型时少增加一个参数解决了这个问题：如无需导出后处理，请指定：-o export.benchmark=True（如果-o已出现过，此处删掉-o），这是官方写的。 完整的模型导出脚本： python3 tools/export_model.py -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml -o export.benchmark=True weights=output/picodet_lcnet_x1_0_layout/best_model --output_dir=output_inference/ @AIwang666 @yuanyatao

这样导出后效果还准吗，我导出后是可以使用了，但是效果很差很差。

**Comment by Andy197527** [comment]
请问把模型导出之后，如何在原先的东西里边更换成自己训练的模型呢？

**Comment by Andy197527** [comment]
> > 你使用OCR代码的时候，更改layout模型路径了吗
> 
> 更改了 更改为我自己训练完推理后的模型了 字典也改为我的字典了 是不是因为我的字典中包含的元素有些多 比如我看源代码中图片的标签是figure但是我给的标签是seal

请问你是如何换成自己训练好的模型的呢？就是这个picodet_lcnet_x1_0_layout.yml模型我训练好了，但是我想把他换上去？请问改怎么做呢？
