### ISSUE TITLE
do not support arm64?

### ISSUE THREAD

**Issue by sck-star** [PaddlePaddle/PaddleOCR#9627]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu 18.04.6 LTS (GNU/Linux 4.9.253-tegra aarch64)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
Are you running paddleocr on mac or phone.

please install  paddlepaddle for mac: python -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

If running paddleocr on iphone, you can use paddlelite: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/lite/readme.md

**Comment by sck-star** [comment]
> Are you running paddleocr on mac or phone.
> 
> please install paddlepaddle for mac: python -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> If running paddleocr on iphone, you can use paddlelite: https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/deploy/lite/readme.md

It will run on NVIDIA Jetson Nano Developer Kit.Is it work?How do I do ?
