### ISSUE TITLE
PPOCR-v3模型转化为华为的om模型后输入数据的结构是什么样子的？ 

### ISSUE THREAD

**Issue by qianweizj** [PaddlePaddle/PaddleOCR#9629]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by UserWangZz** [comment]
这个issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
