### ISSUE TITLE
多语言支持目前支持泰语吗

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleOCR#9630]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我看多语言已经支持了越南语， 马来文 没看到泰文

**Comment by habout632** [comment]
还有菲律宾语， 老挝语

**Comment by LDOUBLEV** [comment]
目前不支持

**Comment by ZhangXinNan** [comment]
> 还有菲律宾语， 老挝语

菲律宾的官方语言除了英语还有他加䘵语，书写和英文字母差不多，只多一个字母，类似西班牙语
