### ISSUE TITLE
crnn量化训练或者直接降到fp16，精度很差

### ISSUE THREAD

**Issue by Jverson** [PaddlePaddle/PaddleOCR#9631]
在进行推理速度优化时，尝试过将模型降到fp16，也尝试过量化训练，最后效果都很差，主要问题有两个：
1. 将训练好的PaddleOCR dbnet和crnn模型，直接转为nb模型后，在RK3326的CPU上跑起来是没有问题的，但是转为FP16后，在RK3326的GPU上跑起来准确率直线下降，完全不能用。

PaddleOCR版本：  dbnet: release/2.1, crnn: release/2.3
Paddle版本：     paddlepaddle-gpu 2.1.2.post110
Paddle-Lite版本：RK提供的libpaddle_light_api_shared.so

1.1 转inference模型：
    python3 tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_230327.yml \
       -o Global.pretrained_model=output/det_dbnet_230327/best_accuracy_XXXX \
       Global.load_static_weights=False \
       Global.save_inference_dir=output/det_dbnet_230327/best_accuracy_XXXX
    python3 tools/export_model.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation_finetune.yml \
       -o Global.pretrained_model=/data1/huajie/OCR/limaopeng/output/rec_pp-OCRv2_distillation_32320_cosine_focal_230314/best_accuracy_0.861104941699056_299000 \
       Global.load_static_weights=False \
       Global.save_inference_dir=/data1/huajie/OCR/limaopeng/output/rec_pp-OCRv2_distillation_32320_cosine_focal_230314/best_accuracy_0.861104941699056_299000
1.2 转nb模型（opt文件也是由RK提供的）：
    ./opt --model_file=./dbnet_XXXX/inference.pdmodel  \
          --param_file=./dbnet_XXXX/inference.pdiparams  \
          --optimize_out=./det_models/dbnet_XXXX \
          --valid_targets=opencl  \
          --optimize_out_type=naive_buffer \
          --enable_fp16=true
    ./opt --model_file=./crnn_XXX/Student/inference.pdmodel  \
          --param_file=./crnn_XXX/Student/inference.pdiparams  \
          --optimize_out=./rec_models/crnn_XXXX \
          --valid_targets=opencl  \
          --optimize_out_type=naive_buffer \
          --enable_fp16=true

2. 使用PaddleSlim量化训练PaddleOCR crnn模型，训练时在验证集的准确率跟非量化训练相差不大，但是转为nb模型之后，推理结果直接就是空的。
PaddleOCR版本：  release/2.3
Paddle版本：     paddlepaddle-gpu 2.1.2.post110
PaddleSlim版本： paddleslim 2.1.1
Paddle-Lite版本：v2.9和v2.10都试过

2.1 训练命令：
    python deploy/slim/quantization/quant.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_quant.yml
2.2 转inference模型：
    python deploy/slim/quantization/export_model.py \
       -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_quant.yml \
       -o Global.checkpoints=outputs/rec/quant_20230105/best_accuracy_XXXX \
       Global.load_static_weights=False \
       Global.save_inference_dir=outputs/rec/quant_20230105_2/best_accuracy_XXXX
2.3 转nb模型：
    ./opt --model_file=./crnn_quant/best_accuracy_XXXX/inference.pdmodel \
      --param_file=./crnn_quant/best_accuracy_XXXX/inference.pdiparams \
      --optimize_out=./crnn_quant/best_accuracy_XXXX \
      --valid_targets=arm \
      --optimize_out_type=naive_buffer

[ppocr_models.zip](https://github.com/PaddlePaddle/PaddleOCR/files/11137000/ppocr_models.zip)

**Comment by LDOUBLEV** [comment]
fp32模型转fp16预测，会有比较大的精度损失
量化模型预测结果为空不太符合预期，检查第二个步骤转inference的模型预测结果是不是对的；
如果inference model没问题，在预测的时候没有指定INT8精度

# 仅使用文本检测模型，使用方式如下：
./ocr_db_crnn  det ch_PP-OCRv3_det_slim_opt.nb arm8 INT8 10 1 ./11.jpg  config.txt

**Comment by Jverson** [comment]
我目前只量化训练了crnn，检测暂时没有量化训练好的模型，按照你的思路，我做了以下尝试。

首先，我用以下命令测了一下inference model，结果是对的：
python3 tools/infer/predict_rec.py \
        --image_dir="test_images" \
        --rec_model_dir="output/quant_20230305/XXXXXX" \
        --rec_image_shape="3, 32, 320" \
        --rec_char_dict_path="ppocr/utils/ppocr_keys_v1_XXX.txt"

然后，用以下命令转换成nb模型后，在终端跑起来，推理结果还是空的：
./opt --model_file=./quant_20230305/XXXXXX/inference.pdmodel \
      --param_file=./quant_20230305/XXXXXX/inference.pdiparams \
      --optimize_out=./quant_20230305/XXXXXX \
      --valid_targets=arm \
      --optimize_out_type=naive_buffer

但是，我下载了你们发布的量化推理模型，用完全相同的命令转成nb模型，在终端跑起来，结果是OK的：
./opt --model_file=./ch_PP-OCRv2_rec_slim_quant_infer/inference.pdmodel \
      --param_file=./ch_PP-OCRv2_rec_slim_quant_infer/inference.pdiparams \
      --optimize_out=./ch_PP-OCRv2_rec_slim_quant_infer \
      --valid_targets=arm \
      --optimize_out_type=naive_buffer

搞不清楚问题出在哪里，我一度怀疑是不是训练的时候没有进入量化训练，而是常规训练，但是转化之后的nb模型只有3M多，跟下载的差不多，这似乎说明确实是量化训练。

对比了一下跟源码的差异：
1) 字符集有差异，在原有ppocr_keys_v1.txt基础上增加了部分字符；
2) 训练时图像尺寸固定为：[3, 32, 320]；
3) label的最长限制是100个字符；
4) 没有使用蒸馏

@LDOUBLEV 还有没有其他思路来定位这个问题？

**Comment by Jverson** [comment]
> fp32模型转fp16预测，会有比较大的精度损失 量化模型预测结果为空不太符合预期，检查第二个步骤转inference的模型预测结果是不是对的； 如果inference model没问题，在预测的时候没有指定INT8精度
> 
> ```
> # 仅使用文本检测模型，使用方式如下：
> ./ocr_db_crnn  det ch_PP-OCRv3_det_slim_opt.nb arm8 INT8 10 1 ./11.jpg  config.txt
> ```

我目前只量化训练了crnn，检测暂时没有量化训练好的模型，按照你的思路，我做了以下尝试。

首先，我用以下命令测了一下inference model，结果是对的：
python3 tools/infer/predict_rec.py
--image_dir="test_images"
--rec_model_dir="output/quant_20230305/XXXXXX"
--rec_image_shape="3, 32, 320"
--rec_char_dict_path="ppocr/utils/ppocr_keys_v1_XXX.txt"

然后，用以下命令转换成nb模型后，在终端跑起来，推理结果还是空的：
./opt --model_file=./quant_20230305/XXXXXX/inference.pdmodel
--param_file=./quant_20230305/XXXXXX/inference.pdiparams
--optimize_out=./quant_20230305/XXXXXX
--valid_targets=arm
--optimize_out_type=naive_buffer

但是，我下载了你们发布的量化推理模型，用完全相同的命令转成nb模型，在终端跑起来，结果是OK的：
./opt --model_file=./ch_PP-OCRv2_rec_slim_quant_infer/inference.pdmodel
--param_file=./ch_PP-OCRv2_rec_slim_quant_infer/inference.pdiparams
--optimize_out=./ch_PP-OCRv2_rec_slim_quant_infer
--valid_targets=arm
--optimize_out_type=naive_buffer

搞不清楚问题出在哪里，我一度怀疑是不是训练的时候没有进入量化训练，而是常规训练，但是转化之后的nb模型只有3M多，跟下载的差不多，这似乎说明确实是量化训练。

对比了一下跟源码的差异：
1) 字符集有差异，在原有ppocr_keys_v1.txt基础上增加了部分字符；
2) 训练时图像尺寸固定为：[3, 32, 320]；
3) label的最长限制是100个字符；
4) 没有使用蒸馏。

@LDOUBLEV 还有没有其他思路来定位这个问题？
