### ISSUE TITLE
What's the best preprocessing method for OCR text detection and recognition?

### ISSUE THREAD

**Issue by similang** [PaddlePaddle/PaddleOCR#9633]
I have been trying different padding and resizing for low quality image and each time OCR output is different.

For best accuracies what are the best way to do preprocessing?

**Comment by similang** [comment]
the input size doesn't matter? what I am observing is padding and resizing produced different output...

**Comment by andyjpaddle** [comment]
> just using the corresponding default method of each algorithm.

I mean you used the default padding or input size

**Comment by similang** [comment]
so I need to pad the image and resize or how - according to the default values? @andyjpaddle
