### ISSUE TITLE
如何加入自己的检测算法？

### ISSUE THREAD

**Issue by Elsanna** [PaddlePaddle/PaddleOCR#964]
如题，想将自己的文本检测算法（基于Mask R-CNN的）整合进PPOCR中，是否有文字教程一类的可以教学一下需要改动哪些部分，加入新算法并训练？谢谢！

**Comment by MissPenguin** [comment]
可以简单读一遍检测的代码，应该就比较清楚了，目前已经有三个检测算法了，照着结构再加一个就行。主要代码在ppocr目录下，可以先看下整体目录结构：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/tree.md
