### ISSUE TITLE
Detected Bounding Box but Doesn't Print Text

### ISSUE THREAD

**Issue by sg1806** [PaddlePaddle/PaddleOCR#9643]
Detected Bounding Box but Doesn't Print Text

Hi,

I am having an issue with the text detection in PaddleOCR because the bounding box is able to detect the text I want but it isn't printing out that text (and this is only happening with one of the lines, the model is working for the rest of the document). The confidence scores for all the bounding box results are really high (>0.9) and changing it to a lower threshold isn't helping with the text printing.

Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Google Colab
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：Bounding Box but No Text Printed for One of the Elements
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by andyjpaddle** [comment]
pls provide your test image and your test code.
