### ISSUE TITLE
detected value , confidence value and text region for PPStructure table

### ISSUE THREAD

**Issue by zhcterry** [PaddlePaddle/PaddleOCR#9644]
When using PPStructure, when the type is text, the model returns the detected value , confidence value and text region. When the type is table, it only returns the cell bounding box and the table in html format. Is it possible for the model to return the detected value, confidence level and text region of the detected text in the table as well?

text example:
{'text': 'abcdefg', 'confidence': 0.9148340821266174, 'text_region': [[104.0, 240.0], [614.0, 241.0], [614.0, 261.0], [104.0, 260.0]]}

table example:
{'type': 'table', 'bbox': [57, 55, 1716, 564], 'res': {'cell_bbox': [[62.22278594970703, 21.91761016845703, 187.28712463378906, 62.401065826416016]],  'html': '<html><body><table><thead><tr><td>text</td><td>... ...

**Comment by andyjpaddle** [comment]
you can refer this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#23-result-description

**Comment by zhcterry** [comment]
Got it thanks a bunch!
