### ISSUE TITLE
目前用了20w数据来微调v3识别模型，但是还是存在英文识别错误，数字识别错误的问题，请问如何改善？

### ISSUE THREAD

**Issue by cumthxy** [PaddlePaddle/PaddleOCR#9645]
目前用了20w数据来微调v3识别模型，但是还是存在英文识别错误，数字识别错误的问题，请问如何改善？
20w 数据是1w张证件手工标注的数据。训练轮次300轮。其他配置都是默认的参数。请问如何去提升识别结果？
数据为这样的：
这样的数字有些会错一位。
![20002_crop_22的副本](https://user-images.githubusercontent.com/22782047/229744690-6279f1e8-86ff-416e-a9ef-5dfe30ce744f.jpg)
或者这样的 U有些就被识别成了 LI
![20033_crop_19](https://user-images.githubusercontent.com/22782047/229744978-1584251b-aad6-4ffa-bde4-826a8287e178.jpg)

此外还发现问题就是随着数据集中的字母数据越来越多，数字的识别准确度在下降。目前字母数字的比例是：100:6

**Comment by andyjpaddle** [comment]
你这个数据好像有点模糊，finetune的时候学习率调小了吗，也可以针对bad case合成一些数据加进去试试

**Comment by cumthxy** [comment]
> 

学习率目前采用的是
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

那我需要调整到多少呢？有参考值么？20w 的数据量。
证件号识别错误的问题 是不是可以通过新增一些数字图片，我接着训练我上次训练好的模型呢？设置checkpoints为我上次的 best_acc 模型呢？

**Comment by cumthxy** [comment]
> 你这个数据好像有点模糊，finetune的时候学习率调小了吗，也可以针对bad case合成一些数据加进去试试

学习率目前采用的是
Optimizer:
name: Adam
beta1: 0.9
beta2: 0.999
lr:
name: Cosine
learning_rate: 0.001
warmup_epoch: 5
regularizer:
name: L2
factor: 3.0e-05

那我需要调整到多少呢？有参考值么？20w 的数据量。
证件号识别错误的问题 是不是可以通过新增一些数字图片，我接着训练我上次训练好的模型呢？设置checkpoints为我上次的 best_acc 模型呢？

**Comment by nissansz** [comment]
多语种模型，汉字识别好，英文识别会有错，怎样改善？

**Comment by nissansz** [comment]
> 你这个数据好像有点模糊，finetune的时候学习率调小了吗，也可以针对bad case合成一些数据加进去试试

rec resnet34模型微调hard case时，lr要设置为多少？
默认配置如下
Optimizer:
name: Adam
beta1: 0.9
beta2: 0.999
lr:
learning_rate: 0.0005
regularizer:
name: L2
