### ISSUE TITLE
ppstructureV2 版式恢复 如何携带字体大小信息呢？

### ISSUE THREAD

**Issue by luoshenfu** [PaddlePaddle/PaddleOCR#9646]
![image](https://user-images.githubusercontent.com/5335245/229740490-169dfb3a-a5af-40b9-9883-36863deda2e0.png)

环境信息如上

使用paddleocr 2.6.1  
进行版式识别命令:  paddleocr --image_dir=ppstructure/docs/table/ceshi1.png --type=structure --recovery=true

版式恢复的结果 字体没有了，生成的word文档，字体是自己生成的，

请问怎样做 才能将字体信息也能识别和恢复呢？

**Comment by andyjpaddle** [comment]
如果pdf是可解析的，而不是图片性质的话，可以使用pdf2docx这个库来解析

**Comment by Wall-ee** [comment]
> 如果pdf是可解析的，而不是图片性质的话，可以使用pdf2docx这个库来解析

那如何用脚本进行pdf转word呢？  我貌似没找到脚本的示例代码，仅有命令行的
