### ISSUE TITLE
ppocr模型推理不匹配

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9649]
我用自己的数据集训练之后完成了模型的推理 请问为什么我的pdmodel文件要比官方给出的cdla的推理模型中pdmodel文件小很多啊 这个问题会不会造成后续在版面还原中出现问题。
如图
![X03T}NR~9S5ZN2CF9@QNQXA](https://user-images.githubusercontent.com/56247915/229759194-87e86fda-5f32-4386-8df7-cae1a4c8048b.png)
![0_V5RU$ %H2~4_F9A4~`T 1](https://user-images.githubusercontent.com/56247915/229759212-1ed08b09-521f-442c-9179-cecea2b3dc93.png)

**Comment by AIwang666** [comment]
@andyjpaddle

**Comment by andyjpaddle** [comment]
如果导出正确，可以试下推理结果是否正确，不同paddle版本导出的模型大小可能会有一些diff
