### ISSUE TITLE
请问下，我看到多语言的字典里是混合了不同的语种，这个是有什么讲究吗？统一到一个字典里会对精度造成多大的损失？

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/PaddleOCR#965]

**Comment by tink2123** [comment]
统一到一个字典里，会造成最后一层FC过大，增加模型大小。如果有特殊需求的话，可以把您需要的几种语言合并字典训练模型，在PaddleOCR暂时将语言字典分开。

**Comment by zcswdt** [comment]
> 造成最后一层FC过大，增加模型大小。如果有特殊需求的话，可以把您需要的几种语言合并字典训练模型

合并字典的话，这样会对识别的精度造成损失吗？

**Comment by tink2123** [comment]
> 合并字典的话，这样会对识别的精度造成损失吗？

合并字典之后如果引入过多的形近字，可能会造成精度损失，字符平衡的问题可能也需要考虑一下。

**Comment by terrancraft** [comment]
打扰你们的谈话了，大佬们。
我现在有个业务要识别同时中文 韩文和日文的文字。
3个字典并一起，并增加FC层尺寸来重新训练的方案可行吗？

**Comment by WenmuZhou** [comment]
> 打扰你们的谈话了，大佬们。
> 
> 我现在有个业务要识别同时中文 韩文和日文的文字。
> 
> 3个字典并一起，并增加FC层尺寸来重新训练的方案可行吗？

可以是可以，但是这样你得考虑数据均衡的问题，建议分类器+三个模型

**Comment by terrancraft** [comment]
> > 打扰你们的谈话了，大佬们。
> > 我现在有个业务要识别同时中文 韩文和日文的文字。
> > 3个字典并一起，并增加FC层尺寸来重新训练的方案可行吗？
> 
> 可以是可以，但是这样你得考虑数据均衡的问题，建议分类器+三个模型
-------------------------------------------------------------------------------------------------------------------------------------
我主要是想处理一张图片中包含中文，日文和韩文的情况。 如果我没有理解错的话，您的意思是在detection阶段分别为三种不同的语言做标注，然后再将detection的推测结果放入训练好的三个模型中(比如框起来的中文部分送去中文模型处理)？

**Comment by nissansz** [comment]
> > > 打扰你们的谈话了，大佬们。
> > > 我现在有个业务要识别同时中文 韩文和日文的文字。
> > > 3个字典并一起，并增加FC层尺寸来重新训练的方案可行吗？
> > 
> > 
> > 可以是可以，但是这样你得考虑数据均衡的问题，建议分类器+三个模型
> 
> 我主要是想处理一张图片中包含中文，日文和韩文的情况。 如果我没有理解错的话，您的意思是在detection阶段分别为三种不同的语言做标注，然后再将detection的推测结果放入训练好的三个模型中(比如框起来的中文部分送去中文模型处理)？

效果怎么样？
