### ISSUE TITLE
LayoutLM class imbalancement issue

### ISSUE THREAD

**Issue by inesriahi** [PaddlePaddle/PaddleOCR#9651]
Hi.
I'm working with a key information extraction problem using LayoutLM. I am facing overfitting because of data imbalancement.
The dataset is labeled such that in one document, out of about 200 tokens in some cases, there is one segment labeled as TITLE, another ID, PAGE_NUM, etc, while the rest of the segments have the class OTHER.

Any recommendation for dealing with this problem?
I'm currently using LayoutLM from HuggingFace, but I'm considering moving to paddle, so I'd like to know how can this be tackled.

Thank you

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
