### ISSUE TITLE
Vi-LayoutXLM网络结果理解问题

### ISSUE THREAD

**Issue by simpleman12138** [PaddlePaddle/PaddleOCR#9655]
![image](https://user-images.githubusercontent.com/61568958/230088310-476b766d-9cde-4979-9fb3-8c8256f2146b.png)
  查找该模型得到：VI-LayoutXLM基于LayoutXLM进行改进，在下游任务训练过程中，去除视觉骨干网络模块，最终精度基本无损的情况下，模型推理速度进一步提升。
  这是否意味着上图LayoutXLM输入图片不需要进行特征提取（即左边的分支去除），只输入文本和位置信息？VI-LayoutXLM和LayoutXLM的网络有哪些区别？
  希望得到您的回复 .Hope to receive your reply,Thanks.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
