### ISSUE TITLE
使用源码文档中提供的图片进行表格识别，结果并未与文档中描述的结果一致，是什么原因？

### ISSUE THREAD

**Issue by ywachao** [PaddlePaddle/PaddleOCR#9656]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：BML CoreLab
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6.0
- 运行指令/Command Code：
    python table/predict_table.py \
    --det_model_dir=inference/ch_PP-OCRv3_det_infer \
    --rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
    --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --image_dir=docs/table/table1.png \
    --use_gpu=False \
    --output=../output/table1
- 完整报错/Complete Error Message：<html><body><table><tbody><tr><td>项目名称</td><td>结果</td><td>单位</td><td>参考范围</td><td>项目名称</td></tr><tr><td rowspan="7">总蛋白 白蛋白 谷丙转氨酶 谷草转氨酶 r-谷氨酰转移酶 总胆红素 直接胆红素 碱性磷酸酶 乳酸脱氢酶</td><td>72</td><td>g / L</td><td>62-82</td><td></td></tr><tr><td>42</td><td>g / L</td><td>35-55</td><td></td></tr><tr><td>116</td><td>t U/L</td><td>0-40</td><td></td></tr><tr><td>45</td><td>1 U/L</td><td>0-40</td><td></td></tr><tr><td>78</td><td>t U/L</td><td>8-40</td><td></td></tr><tr><td>18. 0</td><td>t umo1/L 0-17</td><td></td><td></td></tr><tr><td>4. 1 84 134</td><td>umo1/L 0-6 U/L U/L</td><td>42-140 115-220</td><td></td></tr></tbody></table></body></html>

中文那一列全部是在一行了，并不是分开多行

官方文档描述的结果如下的
![table1](https://user-images.githubusercontent.com/3369914/230150177-6b167b7b-7a01-4107-89ed-7604269fbbb4.jpg)

**Comment by WenmuZhou** [comment]
你好这边未能复现你的问题，辛苦提供一下paddle版本，代码库版本，系统环境

**Comment by ywachao** [comment]
> 你好这边未能复现你的问题，辛苦提供一下paddle版本，代码库版本，系统环境

就是用的你们官方示例 https://www.paddlepaddle.org.cn/modelsDetail?modelId=18，在BML CoreLab上测试跑的

**Comment by wzgwy** [comment]
请问一下你找到了原因吗？
