### ISSUE TITLE
det+rec+ser识别提取的时候。det模型和ser模型是自己训练的。det+rec之后有一些空方向不是正的。如下图。导致ser这个空会丢掉

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9657]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
```
python3 tools/infer/predict_system.py \
--image_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_dec_imgs/" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference/Student/" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--rec_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/rec/inference/ch_PP-OCRv3_rec_infer/" \
--rec_image_shape="3,48,320" \
--drop_score=0 \
--rec_char_dict_path="ppocr/utils/ppocr_keys_v1.txt" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_dec_imgsresult/" \
--use_space_char=True \
--use_angle_cls=False
```
- 完整报错/Complete Error Message：
det+rec+ser识别提取的时候。det模型和ser模型是自己训练的。det+rec之后有一些空方向不是正的。如下图。导致ser这个空会丢掉
1.方向不是正的有关系吗？？？？
2.怎么调整？？？
![1680743308367](https://user-images.githubusercontent.com/32863094/230247790-cf0b60e6-7d06-4343-819f-f8305dece688.png)

**Comment by WenmuZhou** [comment]
不会影响，最终使用的是矩形框，你这个可能就是ser模型分错了

**Comment by rexzhengzhihong** [comment]
> ser模型

ser模型分错了吗？我在det+rec 的结果就发现有问题了。这个空给的是错的，单字的甚至不给了。我是用的/ch_PP-OCRv3_rec_infer
