### ISSUE TITLE
请问ppstructurev2的ser任务中，如何解决文本检测中多行的问题

### ISSUE THREAD

**Issue by BaiShiqing** [PaddlePaddle/PaddleOCR#9658]
### 请问ppstructurev2的ser任务中，如何解决文本检测中多行的问题
比如：身份证号码是两行，但它是一个实体Question。
![image](https://user-images.githubusercontent.com/48881406/230262072-73a89692-bf78-4750-99ed-87c0cfaee3ab.png)

**Comment by WenmuZhou** [comment]
你的ser训练数据中有这种吗，有的话应该不影响
