### ISSUE TITLE
det训练后precision: 1.0, recall: 0.95, hmean: 0.97。drop_score=0.0 后    但预测后还是会丢空，会是什么原因？？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9659]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
python3 tools/infer/predict_det.py --det_algorithm="DB" \
--det_model_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference/Student" \
--det_limit_side_len=736 \
--det_limit_type="min" \
--image_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_imgs/" \
--draw_img_save_dir="/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/det_imgsresult/" \
--use_gpu=True
```
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/32863094/230264759-2e47c9f2-7afc-4f7a-bbff-8be801dbed3a.png)

**Comment by rexzhengzhihong** [comment]
det_db_box_thresh 调小后0.6.会出现这种不是方框的，是什么原因？
![image](https://user-images.githubusercontent.com/32863094/230283729-9d3637a1-04a0-4253-be48-2597da2ea077.png)

**Comment by WenmuZhou** [comment]
可以分析一下badcase，然后进行改进，不是方框的结果可以画一下输出map看看

**Comment by rexzhengzhihong** [comment]
> 不是方框的结果可

map是指 方框的位置吗？

**Comment by rexzhengzhihong** [comment]
{'name': 'DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.6, 'max_candidates': 1000, 'unclip_ratio': 1.5, 'use_dilation': False, 'score_mode': 'fast', 'box_type': 'quad'}

**Comment by rexzhengzhihong** [comment]
[[[417.0, 299.0], [489.0, 299.0], [489.0, 331.0], [417.0, 331.0]], [[744.0, 299.0], [795.0, 299.0], [795.0, 328.0], [744.0, 328.0]], [[583.0, 298.0], [655.0, 298.0], [655.0, 329.0], [583.0, 329.0]], [[240.0, 298.0], [308.0, 298.0], [308.0, 323.0], [240.0, 323.0]], [[796.0, 278.0], [863.0, 278.0], [863.0, 299.0], [796.0, 299.0]], [[190.0, 277.0], [322.0, 277.0], [322.0, 300.0], [190.0, 300.0]], [[14.0, 183.0], [81.0, 182.0], [82.0, 201.0], [14.0, 202.0]], [[749.0, 182.0], [805.0, 182.0], [805.0, 202.0], [749.0, 202.0]], [[566.0, 181.0], [615.0, 181.0], [615.0, 202.0], [566.0, 202.0]], [[93.0, 183.0], [131.0, 182.0], [131.0, 201.0], [94.0, 202.0]], [[665.0, 179.0], [653.0, 192.0], [677.0, 191.0], [664.0, 204.0]], [[494.0, 181.0], [528.0, 181.0], [528.0, 203.0], [494.0, 203.0]], [[94.0, 159.0], [131.0, 159.0], [131.0, 178.0], [94.0, 178.0]], [[15.0, 158.0], [76.0, 158.0], [76.0, 178.0], [15.0, 178.0]], [[748.0, 157.0], [805.0, 157.0], [805.0, 179.0], [748.0, 179.0]], [[566.0, 158.0], [615.0, 158.0], [615.0, 178.0], [566.0, 178.0]], [[495.0, 157.0], [529.0, 157.0], [529.0, 179.0], [495.0, 179.0]], [[652.0, 168.0], [665.0, 156.0], [677.0, 167.0], [664.0, 180.0]], [[865.0, 114.0], [939.0, 114.0], [939.0, 129.0], [865.0, 129.0]], [[376.0, 113.0], [654.0, 113.0], [654.0, 130.0], [376.0, 130.0]], [[82.0, 113.0], [219.0, 114.0], [219.0, 130.0], [82.0, 129.0]], [[865.0, 81.0], [918.0, 81.0], [918.0, 98.0], [865.0, 98.0]], [[398.0, 77.0], [692.0, 77.0], [692.0, 94.0], [398.0, 94.0]], [[88.0, 77.0], [236.0, 77.0], [236.0, 95.0], [88.0, 95.0]]]

**Comment by rexzhengzhihong** [comment]
--use_dilation  发现是设置为true就好很多

**Comment by WenmuZhou** [comment]
你这个应该是太小了，导致最后出来的分割图太小了，可以训练的时候对这种小的进行一下放大看看

**Comment by rexzhengzhihong** [comment]
原始图太小了？

**Comment by rexzhengzhihong** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/9667 这个帮我看看吗，搞了好久了

**Comment by rexzhengzhihong** [comment]
> 你这个应该是太小了，导致最后出来的分割图太小了，可以训练的时候对这种小的进行一下放大看看

你好。您是说这个原始图 太小了吗

**Comment by rexzhengzhihong** [comment]
我看有问题的图片确实只有 八十几k 。训练的时候怎么放大呢？  我原来的设置是 det_limit_side_len=736.0,det_limit_type='min',
![image](https://user-images.githubusercontent.com/32863094/231041475-18d9e197-11e9-4901-81d9-55c0e4ab7719.png)
