### ISSUE TITLE
基于海光DCU（Z100）的PaddleOCR安装版本问题

### ISSUE THREAD

**Issue by chenzhijun45** [PaddlePaddle/PaddleOCR#9665]
```java
操作系统：ubuntu20.04
CPU：Hygon C86 7380 32-core Processor
DCU：Hygon Z100、Hygon Z100L
```

**请问我应该安装哪个版本的飞浆呢？**
我在官网只看到`paddlepaddle-rocm==2.4.0.post401`版本，但是我看到“飞桨与海光人工智能加速卡DCU系列完成互证”使用的飞浆版本是2.1.0，官网又没看到2.1.0版本的`paddlepaddle-rocm`。

**Comment by WenmuZhou** [comment]
可以在paddle issue问一下

**Comment by chenzhijun45** [comment]
> 可以在paddle issue问一下

嗯，前几天问过，暂时没人回复。

**Comment by JeffRody** [comment]
参考 这篇文章 https://developer.sourcefind.cn/codes/modelzoo/crnn_paddle/-/blob/main/README.md
