### ISSUE TITLE
文本检测，不使用预训练模型

### ISSUE THREAD

**Issue by Abraham-2020** [PaddlePaddle/PaddleOCR#9666]
请问 我在使用DB算法做文字检测的时候，如果不使用预训练好的模型，从头开始训练，是不是pretrained_model设为空就好啦？
![image](https://user-images.githubusercontent.com/61900951/230387556-203d133f-b568-4dd6-a744-f54df519298d.png)

**Comment by WenmuZhou** [comment]
是的
