### ISSUE TITLE
pip install Polygon3报错

### ISSUE THREAD

**Issue by HappyJiaJun** [PaddlePaddle/PaddleOCR#9668]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：  ERROR: Failed building wheel for Polygon3
- 完整报错/Complete Error Message：Collecting Polygon3
  Using cached Polygon3-3.0.9.1.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Polygon3
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-310\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
Installing collected packages: Polygon3
  Running setup.py install for Polygon3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Polygon3 did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Using NumPy extension!
      running install
      C:\Users\17555\anaconda3\envs\paddle\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-310\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Polygon3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by zirui** [comment]
遇到同样的问题

**Comment by burh2341** [comment]
有人解决吗

**Comment by Lizhen0628** [comment]
同样的问题，解决了吗？

**Comment by biansf2001** [comment]
安装vs2022，把桌面c++那些都装了

**Comment by HappyJiaJun** [comment]
是的，谢谢解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月19日 13:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleOCR] pip install Polygon3报错 (Issue #9668) |

安装vs2022，把桌面c++那些都装了

**Comment by Lizhen0628** [comment]
mac or  linux 系统怎么解决的？
