### ISSUE TITLE
det_db_unclip_ratio参数的作用是什么？

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9670]
如果我想同时文本检测出如图所示的效果，需要重新训练数据，还是说可以修改模型参数就可以？
![image](https://user-images.githubusercontent.com/110521846/230526720-79783b3d-7cec-4dc3-84a6-c4675563aea1.png)

**Comment by luoyq6** [comment]
如果需要重新训练，大概需要多少数据呢？

**Comment by luoyq6** [comment]
@an1018

**Comment by an1018** [comment]
这里有参数说明：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_ch/whl.md#6-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

**Comment by luoyq6** [comment]
谢谢您的回复！已经跑了，不能检测出，只能微调

**Comment by an1018** [comment]
那就针对当前场景训练看看吧
