### ISSUE TITLE
hub serving structure-system模块服务返回异常信息

### ISSUE THREAD

**Issue by LangJiHuangSha** [PaddlePaddle/PaddleOCR#9671]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

请求信息：
url：http://127.0.0.1:30001/predict/structure_system
请求json：{"images": ["${base64}"]}

base64长度太长，无法发送,
[ https://pan.baidu.com/s/1NU4WCLKSSvNt130a4pvLBw?pwd=x98r ](url)

返回信息：
{
    "msg": "pop index out of range",
    "results": "",
    "status": "101"
}

**Comment by an1018** [comment]
图片太大，base64太长报错了，换个图片再试试

**Comment by LangJiHuangSha** [comment]
> 图片太大，base64太长报错了，换个图片再试试

base64太长只是针对于github的issues来说的，将所有的base64发在issues里面无法发出来，下面那个是图片链接。不好意思，可能我上面表达的意思有误，麻烦您再看下
