### ISSUE TITLE
【StyleText工具合成数据效果不理想】

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleOCR#9673]
你好，根据官网指导使用StyleText工具，当选择使用仿宋_GB2312.ttf字体和自己选定的style_images图像后，合成的数据效果不理想，请问这是哪里的问题呢？合成后效果如下：
![1](https://user-images.githubusercontent.com/44281534/230570639-a72bea66-0758-4f0e-aec7-7998dca24a8a.png)
内容是：《中华人民共和国行政强制执行法》

**Comment by an1018** [comment]
--language设置了吗

**Comment by gsx1378** [comment]
> --language设置了吗

设置了，部分参数如下：
`Global:
  output_num: 10            # 批量时，需要合成的数量
  output_dir: output_data  # 保存合成数据的目录
  use_gpu: true
  image_height: 32
  image_width: 320
  standard_font: fonts/仿宋_GB2312.ttf
TextDrawer:
  fonts:
    en: fonts/仿宋_GB2312.ttf
    ch: fonts/仿宋_GB2312.ttf
    ko: fonts/仿宋_GB2312.ttf
StyleSampler:
  method: DatasetSampler
  image_home: examples                  # 风格图片目录；
  label_file: examples/image_list.txt   # 风格图像的列表文件 
  with_label: true                      # true: label_file代表是label文件
CorpusGenerator:
  method: FileCorpus
  language: ch
  corpus_file: examples/corpus/example.txt`

执行命令：`python3 tools/synth_dataset.py -c configs/dataset_config.yml`

我自己测试用的背景：
![033207_476](https://user-images.githubusercontent.com/44281534/230582021-32ff4725-61cb-4602-9bfc-959b92ddc49e.jpg)

我尝试了控制字体、背景变量情况下，合成数据，但是感觉效果都不怎么好。

1. 保持官网字体，保持官网背景，合成效果如下：
![4](https://user-images.githubusercontent.com/44281534/230582357-d324a1e4-76a8-4c45-ae94-6c855b45a6c2.png)

3. 保持官网字体，使用自制背景，合成效果如下：
![9](https://user-images.githubusercontent.com/44281534/230581898-41752f9e-0485-4338-97c1-0805af24b4a9.png)

5. 使用仿宋_GB2312.ttf，保持官网背景，合成效果如下：
![8](https://user-images.githubusercontent.com/44281534/230583314-fc4a5165-df95-484b-83d9-7a985e4701fd.png)

7. 使用仿宋_GB2312.ttf，使用自制背景，合成效果如下：
![1](https://user-images.githubusercontent.com/44281534/230582960-66b25798-c485-41c4-9032-22c3b9cc4fe1.png)
