### ISSUE TITLE
在官方预训练模型上进行fine tune的问题

### ISSUE THREAD

**Issue by opentld** [PaddlePaddle/PaddleOCR#9674]
我使用官方提供的训练好的模型进行文本识别，对于特定的工程场景，有些文本的识别准确率并不高，所以我想在官方预训练模型上进行fine tune，但我的数据集并不大，我不想训练好之后，只能在自己的数据集上使用，还希望保留官方的模型的识别能力，再增加我的数据集的识别能力。
所以，我是不是应该在官方数据集的基础上，增加我的数据集进去，一起进行训练？还是有其它方法？
官方的中文识别的数据集是哪个呢？能不能提供下载？

**Comment by wzl639** [comment]
同问

**Comment by zhaibo623** [comment]
同问

**Comment by brianyuastri** [comment]
Any update?

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by brianyuastri** [comment]
Would you please reopen the issue? Thank you very much!
