### ISSUE TITLE
采用lite 部署到 paddle-lite  提供的模型需要修改么?

### ISSUE THREAD

**Issue by liuyongfusteven** [PaddlePaddle/PaddleOCR#9679]
使用如下方式部署到 rv1126:   https://www.paddlepaddle.org.cn/lite/develop/demo_guides/verisilicon_timvx.html
  模型采用 https://www.paddlepaddle.org.cn/modelsDetail?modelId=17  提供的模型

请问需要自己量化不？ 目前采用cpu  方式运行正常，采用NPU 不是很清楚

**Comment by MissPenguin** [comment]
PP-OCRv3同时提供量化和非量化模型，按需下载即可～
