### ISSUE TITLE
输出数据格式，有没有可能逐字输出坐标，而不是一段话输出坐标？

### ISSUE THREAD

**Issue by aliendaniel** [PaddlePaddle/PaddleOCR#9680]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
目前不支持，可以根据文本行长度和字数粗略估计一下单字坐标
