### ISSUE TITLE
SVTR  无法处理长文本条？

### ISSUE THREAD

**Issue by Gavinic** [PaddlePaddle/PaddleOCR#9684]
使用SVTR进行inference的时候，发现模型对于长文本条(文字长度大于50)无法识别，识别效果差。请问有什么解决方案吗？

**Comment by LDOUBLEV** [comment]
svtr是定长输入，超过25个字符的识别效果会变差，要么你重新训练，加大输入字符长度限制
https://github.com/PaddlePaddle/PaddleOCR/blob/2be9fe763e4ebb55d59cc192eee437b0e09207ce/configs/rec/rec_svtrnet_ch.yml#L18

**Comment by ccx1997** [comment]
欢迎关注iccv2023论文 LISTER，解决文本识别字符串长度问题：
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/tree/main/OCR/LISTER
