### ISSUE TITLE
关于训练中文的检测和识别模型，需要选择合适的预训练模型问题

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9685]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：det_mv3_east.yml
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我想使用det_mv3_east.yml训练一个中文的文本检测模型与其他算法进行对比，官方给的预训练模型是基于ICDAR2015的英文数据集，我之前也问过类似的问题，大佬们建议我使用更好的中文预训练模型，但是受限于网络主干的问题，我不知道应该如何选择用于训练这个配置文件的预训练模型，能给我推荐一下合适的预训练模型吗？
![image](https://user-images.githubusercontent.com/94897119/230850978-43e0e545-53aa-4b94-aad5-996fd6394b89.png)
另外，我在使用官方基于ICDAR2015数据集的预训练模型的时候，预测部分会出现如下情况，eval的时间非常长，这是正常现象还是应该有需要调整的地方？也需要解答一下。
![image](https://user-images.githubusercontent.com/94897119/230851217-0ac69465-b5bf-4d21-a740-9d240bf438e2.png)
以上两个问题，希望能得到各位的帮助和回复，谢谢各位！！！

**Comment by phb-shiyige-fw** [comment]
@LDOUBLEV @WenmuZhou @an1018 @andyjpaddle 抱歉打扰各位，希望能得到回复，谢谢各位了！

**Comment by LDOUBLEV** [comment]
> 我想使用det_mv3_east.yml训练一个中文的文本检测模型与其他算法进行对比，官方给的预训练模型是基于ICDAR2015的英文数据集，我之前也问过类似的问题，大佬们建议我使用更好的中文预训练模型，但是受限于网络主干的问题，我不知道应该如何选择用于训练这个配置文件的预训练模型，能给我推荐一下合适的预训练模型吗？

east的配置只有icdar2015的预训练模型，没有中文的；

> 另外，我在使用官方基于ICDAR2015数据集的预训练模型的时候，预测部分会出现如下情况，eval的时间非常长，这是正常现象还是应该有需要调整的地方？也需要解答一下。

east训练前期模型效果不好，直接评估速度很慢，训练久一些，精度上来后评估速度能快很多

**Comment by phb-shiyige-fw** [comment]
> > 我想使用det_mv3_east.yml训练一个中文的文本检测模型与其他算法进行对比，官方给的预训练模型是基于ICDAR2015的英文数据集，我之前也问过类似的问题，大佬们建议我使用更好的中文预训练模型，但是受限于网络主干的问题，我不知道应该如何选择用于训练这个配置文件的预训练模型，能给我推荐一下合适的预训练模型吗？
> 
> east的配置只有icdar2015的预训练模型，没有中文的；
> 
> > 另外，我在使用官方基于ICDAR2015数据集的预训练模型的时候，预测部分会出现如下情况，eval的时间非常长，这是正常现象还是应该有需要调整的地方？也需要解答一下。
> 
> east训练前期模型效果不好，直接评估速度很慢，训练久一些，精度上来后评估速度能快很多

感谢回复，我还有别的问题想问您，就是我基于mv3训练了DBNet的检测模型，效果非常好，hmean可以达到94.5%左右，后来我换成ResNet50_vd网络训练DBNet的检测模型，效果却非常差，只有不到60%的精确度，请问是什么原因造成的呢？

两次训练都用了500张训练集和100张测试集进行训练，lr和batch_per_card有做适当调整，具体训练日志劳烦您看看，是什么原因导致这样的结果：
db_mv3:
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/11209166/train.log)
db_resnet50:
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/11209176/train.log)
