### ISSUE TITLE
能否不用docker运行代码

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#969]
因为某些原因，远程服务器无法用docker，请问大佬用其他的方法代替docker吗？

**Comment by qypf** [comment]
根本就没必要用docker啊，docker只是便于管理，比较方便，不用完全可以的。安装python，再把requirement.txt的依赖包装上，代码就可以运行了

**Comment by ulanbator** [comment]
好的，万分感谢！
