### ISSUE TITLE
单个字符的漏检问题

### ISSUE THREAD

**Issue by Coder-TieHH** [PaddlePaddle/PaddleOCR#9690]
[请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：  windows10
- 版本号/Version：Paddle：2.6    PaddleOCR： 问题相关组件/Related components： db模型的单个字符识别不出来
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：无

表单的识别，输入图片大小是1100X1000的分辨率，有一个数据比较重要，但是是单个字符的，我们实验后发现，经常在第一步检测的时候就出不来，用的db模型，看到论坛里面有人说这是db模型本身的缺陷，经过实验发现det_db_unclip_ratio该参数调大后，会有一定的改善，但是目前已经改到了2.7，还是有很多时候出不来，请问如何解决？或者如果是db模型本身的问题，应该选择哪种模型？
请帮帮我，十分感谢!]

**Comment by Coder-TieHH** [comment]
![image](https://user-images.githubusercontent.com/130418678/231034972-a87654b5-d29b-434d-8927-e2e856d7a0a2.png)

**Comment by andyjpaddle** [comment]
可以调下其他预处理阈值，bbox_thresh等，或者加些数据finetune一下

**Comment by 1061302569** [comment]
建议自己fintune，这种单字符就算调出来，其他地方也会出问题

**Comment by Coder-TieHH** [comment]
首先感谢各位大佬的帮助，我是想自己加一些数据集进去finetune的，但是之前有看到其他人的帖子说，就是他的数据集里面其实就是存在这样的小字符的样本，训练完之后还是有这种问题，然后后面的有Collaborator说这是db模型本身的缺陷，故我想的就是如果真的是db模型本身的缺陷，我应该选择哪个模型？请赐教。

**Comment by thsno02** [comment]
如果位置固定的话，建议你用 yolo 试试。

**Comment by DenghuiXiao** [comment]
> 首先感谢各位大佬的帮助，我是想自己加一些数据集进去finetune的，但是之前有看到其他人的帖子说，就是他的数据集里面其实就是存在这样的小字符的样本，训练完之后还是有这种问题，然后后面的有Collaborator说这是db模型本身的缺陷，故我想的就是如果真的是db模型本身的缺陷，我应该选择哪个模型？请赐教。

请问解决了吗？ 我也遇到该问题了
