### ISSUE TITLE
en_PP-OCRv3_rec 学习率设置

### ISSUE THREAD

**Issue by cumthxy** [PaddlePaddle/PaddleOCR#9692]
文档https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md 里边说了ch_PP-OCRv3_rec_distillation.yml的学习率的配置。我的现在场景只需要识别英文和数字 用这个en_PP-OCRv3_rec 模型是不是就可以了？那学习率的设置 该怎么设置呢？我看en_PP-OCRv3_rec 的默认配置是
![Snipaste_2023-04-11_11-00-52](https://user-images.githubusercontent.com/22782047/231044999-a3e79d9b-d9d4-4863-9f1b-0e575d01d1c0.jpg)

**Comment by andyjpaddle** [comment]
根据文档进行对应调整就行
