### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by xiaoli26** [PaddlePaddle/PaddleOCR#9694]
!python D:/chatglm/openvino/predict_structure.py D:/chatglm/ocr1/PaddleOCR-2.6.0/ppstructure/predict_system.py \
    --image_dir=D:/chatglm/openvino/predict_structure.py D:/chatglm/ocr1/PaddleOCR-2.6.0/ppstructure/docs/table/1.png \
    --det_model_dir=D:/chatglm/ocr1/models/en_PP-OCRv3_det_infer \
    --rec_model_dir=D:/chatglm/ocr1/models/en_PP-OCRv3_rec_infer \
    --rec_char_dict_path=D:/chatglm/ocr1/PaddleOCR-2.6.0/ppocr/utils/en_dict.txt \
    --table_model_dir=D:/chatglm/ocr1/models/en_ppstructure_mobile_v2.0_SLANet_infer \
    --table_char_dict_path=D:/chatglm/ocr1/PaddleOCR-2.6.0/ppocr/utils/dict/table_structure_dict.txt \
    --layout_model_dir=D:/chatglm/ocr1/models/picodet_lcnet_x1_0_fgd_layout_infer \
    --layout_dict_path=D:/chatglm/ocr1/PaddleOCR-2.6.0/ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt \
    --vis_font_path=D:/chatglm/ocr1/PaddleOCR-2.6.0/doc/fonts/simfang.ttf \
    --recovery=True \
    --use_gpu=False \
    --use_openvino=True \
    --output=./output/

Traceback (most recent call last):
  File "D:\chatglm\openvino\predict_structure.py", line 30, in <module>
    import tools.infer.utility as utility
ModuleNotFoundError: No module named 'tools'

菜鸟求教！

**Comment by hhhaoyi** [comment]
我也遇到同样的问题，未打包时可正常运行，打包为exe后报错：
Traceback (most recent call last):
File"main.py",line 14,in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File"paddleocr\_init_.py",line 14,in<module>
File"paddleocr\paddleocr.py", line 33, in <module>
File”importlib\_init_.py"line 127,in import_module
ModuleNotFoundError: No module named 'tools

**Comment by xiaoli26** [comment]
> 我也遇到同样的问题，未打包时可正常运行，打包为exe后报错： Traceback (most recent call last): File"main.py",line 14,in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File"paddleocr_init_.py",line 14,in File"paddleocr\paddleocr.py", line 33, in File”importlib_init_.py"line 127,in import_module ModuleNotFoundError: No module named 'tools

感觉是openvino的问题，我试着跑了原版的OCR没有问题

**Comment by xuri422** [comment]
> > 我也遇到同样的问题，未打包时可正常运行，打包为exe后报错： Traceback (most recent call last): File"main.py",line 14,in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File"paddleocr_init_.py",line 14,in File"paddleocr\paddleocr.py", line 33, in File”importlib_init_.py"line 127,in import_module ModuleNotFoundError: No module named 'tools
> 
> 感觉是openvino的问题，我试着跑了原版的OCR没有问题

请问原版的OCR是什么意思？从那里获取？
