### ISSUE TITLE
Question - KIE SER/RE dataset format

### ISSUE THREAD

**Issue by kuopching** [PaddlePaddle/PaddleOCR#9699]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 11
- 版本号/Version：2.6 Paddle：2.6  PaddleOCR：2.6  问题相关组件/Related components：
Hi,
I would like to clarify one thing about kie.
The dataset format for SER is the same as the RE dataset format, with the exceptions of id and linking? 
What exactly does the field label mean in the SER dataset? It is a "question-answer" pair or it is, for example, a name_key/name_value pair?

Is these samples valid for SER training dataset?
{"transcription":"foo","id":28,"label":"name_key","points":[[783,71],[1513,71],[1513,171],[783,171]]}
{"transcription":"bar","id":29,"label":"name_value","points":[[1523,71],[1573,71],[1573,171],[1523,171]]}

or it must be 
{"transcription":"foo","id":28,"label":"question","points":[[783,71],[1513,71],[1513,171],[783,171]]}
{"transcription":"bar","id":29,"label":"answer","points":[[1523,71],[1573,71],[1573,171],[1523,171]]}

?
thank you

**Comment by andyjpaddle** [comment]
refer to this doc https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/kie_en.md#12-custom-dataset
