### ISSUE TITLE
这种模拟的图片怎么模拟生成比较好？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9714]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://user-images.githubusercontent.com/41010669/231631703-bf97cf46-318e-4773-8e8f-0001239bd070.png)

**Comment by WenmuZhou** [comment]
加点模糊特效

**Comment by nissansz** [comment]
有示例代码吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
