### ISSUE TITLE
如何批量预测

### ISSUE THREAD

**Issue by tfka** [PaddlePaddle/PaddleOCR#9720]
目前只能一张一张图预测
for img in tqdm(imgs):
        # try:
        #     #print(img_path + img)
        result = ocr.ocr(img_base_path + img, cls=True)
如果我有大量的存量图片，我如何批量调包预测。

**Comment by an1018** [comment]
直接输入path就可以，支持ndarray, img_path and list or ndarray
ocr.ocr(img_base_path, cls=True)

**Comment by tfka** [comment]
> 
ocr = PaddleOCR(lang="ch")
img_base_path = "/raw_data/demo/imgs/"
result = ocr.ocr(img_base_path, cls=True)

报错
File "/anaconda3/envs/paddle/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 436, in check_img
    with open(image_file, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/raw_data/demo/imgs/'

**Comment by Sariel2** [comment]
我也遇到了同样的问题，使用ocr.ocr(img_list)会产生异常
`AttributeError: 'str' object has no attribute 'shape'`
