### ISSUE TITLE
ser关键信息提取，是不是得一张单据一个模型？因为每个单据关键信息不一样。如果是这样。那这么多模型部署hubserving上。一个模型就要占用一定的gpu显存

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9721]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle： PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
运行指令/Command Code
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
ser关键信息提取，是不是得一张单据一个模型？
1.如果是这样。那这么多模型部署hubserving上。一个模型就要占用一定的gpu显存，怎么处理？
2.因为每个单据关键信息不一样。class_list就会非常多。公用吗？

**Comment by azhaoid** [comment]
可以多种类型的单据，用一个class_list,只训练一个模型就可以。比如XFUND数据集就很多种类型图片。

**Comment by rexzhengzhihong** [comment]
> 可以多种类型的单据，用一个class_list,只训练一个模型就可以。比如XFUND数据集就很多种类型图片。

xfund数据集是的class_list只有三个，`QUESTION`, `ANSWER`, `HEADER` 。是通过re把关系绑定起来的。我是用ser，直接标注这个空叫什么

**Comment by rexzhengzhihong** [comment]
@an1018 能帮忙回答一下吗
