### ISSUE TITLE
PaddleOCR() 函数进行通用识别可以设置置信度吗？

### ISSUE THREAD

**Issue by azhaoid** [PaddlePaddle/PaddleOCR#9722]
PaddleOCR() 函数进行通用识别可以设置置信度吗？比如，只提取0.95以上的内容。有请大佬解答下。

ocr = PaddleOCR(use_angle_cls=True, lang="ch")  
img_path = r'G:\NLPdataset\IMG_20180903_145015.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

**Comment by an1018** [comment]
![image](https://user-images.githubusercontent.com/19808900/231960428-88f903c7-7b36-44ac-9471-da216ba2e122.png)
获取结果后可以添加代码：根据置信度进行阈值判断过滤
