### ISSUE TITLE
train.py: error: unrecognized arguments:   zsh: command not found: -o

### ISSUE THREAD

**Issue by luoyuchen0417** [PaddlePaddle/PaddleOCR#973]
在启动训练的实例时遇到这样的情况怎么办

**Comment by littletomatodonkey** [comment]
应该训练脚本写法有问题，麻烦提供下你的训练脚本吧，

**Comment by luoyuchen0417** [comment]
> 应该训练脚本写法有问题，麻烦提供下你的训练脚本吧，
就是根据教程来的。文字检测>启动训练>>python3 tools/train.py -c configs/det/det_mv3_db_v1.1.yml \ 
     -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/ \
     2>&1 | tee train_det.log

**Comment by luoyuchen0417** [comment]
> 应该训练脚本写法有问题，麻烦提供下你的训练脚本吧，

就是根据教程来的。文字检测>启动训练>>python3 tools/train.py -c configs/det/det_mv3_db_v1.1.yml \
-o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/ 
2>&1 | tee train_det.log

**Comment by luoyuchen0417** [comment]
> > 应该训练脚本写法有问题，麻烦提供下你的训练脚本吧，
> 
> 就是根据教程来的。文字检测>启动训练>>python3 tools/train.py -c configs/det/det_mv3_db_v1.1.yml 
> -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/
> 2>&1 | tee train_det.log

https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md 在跟着这个做的练习，不是自己的训练脚本

**Comment by littletomatodonkey** [comment]
你好，可以麻烦你手动在命令行中敲一下这个命令吗？看下是否能够正常运行，看这个报错应该是zsh没有成功解析直接拷贝过去的训练脚本导致的

**Comment by BeyondYourself** [comment]
这种大多数是因为copy导致的，手动输入一般能够解决
