### ISSUE TITLE
PGNet问题

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleOCR#9731]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 出现报错
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4096, 6624], X's size = 27131904, 'shape' is [-1, 64, 37], known capacity of 'shape' is -2368.

**Comment by yl3118436** [comment]
Loss:
  name: PGLoss
  tcl_bs: 64
  max_text_length: 50 # the same as Global: max_text_length
  max_text_nums: 30 # the same as Global：max_text_nums
  # pad_num: 36 # the length of dict for pad
  pad_num: 6623

这里的pad_num改成6623
