### ISSUE TITLE
How many image in the Arabic model dataset ? and were them all synthetic or some were real? 

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#9735]
I could not find any information about the training dataset of the Arabic model

**Comment by MohieEldinMuhammad** [comment]
@an1018

**Comment by ruogedol** [comment]
I was also training a language model for Arabic recently. Since I couldn't find the relevant Arabic training set, I used the code in https://github.com/Sanster/text_renderer to simulate the dataset to train the model. If you have a good training set, can you share the public address?

**Comment by MohieEldinMuhammad** [comment]
I'm also using synthetic data to simulate the real data here is the repo i'm using --> https://github.com/Belval/TextRecognitionDataGenerator

**Comment by MohieEldinMuhammad** [comment]
you can create as many images as you want with different text colors, backgrounds with random words in each image --> just download the repo locally and create venv and install the requirements and follow this tutorial to create your own data https://textrecognitiondatagenerator.readthedocs.io/en/latest/tutorial.html

**Comment by ruogedol** [comment]
thanks @MohieEldinMuhammad
