### ISSUE TITLE
识别文字时，有没有办法，第一步识别出字体名，第二步根据字体名选用对应的模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9736]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
 

识别文字时，有没有办法，第一步识别出字体名，第二步根据字体名选用对应的模型？

**Comment by WilliamQf-AI** [comment]
我之前也有这个想法，但不幸的是并没有，看到google有识别语言的模型，但它本身就是根据你提供的字符来识别，而要提取字符又要先加载模型，这样就成了死结。

**Comment by nissansz** [comment]
有搜集到多少字体文件了？

**Comment by UserWangZz** [comment]
可以尝试标注一批数据训练一个分类器模型对字体进行分类
