### ISSUE TITLE
Cublas error, CUBLAS_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#974]
使用下载的权重，执行命令：CUDA_VISIBLE_DEVICES=2 python tools/infer/predict_system.py --image_dir="/DATA/fangzheng/PLP/Test/images" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True报错，报错信息如下：
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::FCOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::FCOpKernel<paddle::platform::CUDADeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::FCOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::operators::math::FCFunctor<paddle::platform::CUDADeviceContext, float>::operator()(paddle::platform::CUDADeviceContext const&, int, int, int, float const*, float const*, float*, float const*, bool, bool)
8   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
9   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < fc > error]

本机测试环境：ubuntu16.0.4 CUDA10.1 卡2的显存还剩6000M,是显存不够吗？第一次用Paddle框架。

**Comment by littletomatodonkey** [comment]
麻烦使用cuda9.0或者cuda10.0吧，目前cuda10.1兼容性还不是很好

**Comment by grasswolfs** [comment]
由于长期没有收到您的回复，本issue暂时关闭，如果仍然有问题，可以reopen继续咨询。
