### ISSUE TITLE
训练crnn mobilenet v3时，为什么有的时候会停住，不继续训练，怎么查哪里的问题

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9741]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练crnn mobilenet v3时，为什么有的时候会停住，不继续训练，怎么查哪里的问题

**Comment by idontkonwher** [comment]
请问有进展吗，遇到了类似的问题
