### ISSUE TITLE
kie 训练出现以下错误

### ISSUE THREAD

**Issue by yanceking** [PaddlePaddle/PaddleOCR#9744]
Special tokens file saved in /Users/yance/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
Traceback (most recent call last):
  File "/Users/yance/Downloads/PaddleOCR/tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "/Users/yance/Downloads/PaddleOCR/tools/train.py", line 69, in main
    global_config)
  File "/Users/yance/Downloads/PaddleOCR/ppocr/postprocess/__init__.py", line 69, in build_post_process
    'post process only support {}'.format(support_dict))
AssertionError: post process only support ['DBPostProcess', 'EASTPostProcess', 'SASTPostProcess', 'FCEPostProcess', 'CTCLabelDecode', 'AttnLabelDecode', 'ClsPostProcess', 'SRNLabelDecode', 'PGPostProcess', 'DistillationCTCLabelDecode', 'TableLabelDecode', 'DistillationDBPostProcess', 'NRTRLabelDecode', 'SARLabelDecode', 'SEEDLabelDecode', 'VQASerTokenLayoutLMPostProcess', 'VQAReTokenLayoutLMPostProcess', 'PRENLabelDecode', 'DistillationSARLabelDecode', 'ViTSTRLabelDecode', 'ABINetLabelDecode', 'TableMasterLabelDecode', 'SPINLabelDecode', 'DistillationSerPostProcess', 'DistillationRePostProcess', 'VLLabelDecode', 'PicoDetPostProcess', 'CTPostProcess', 'RFLLabelDecode', 'DRRGPostprocess', 'CANLabelDecode']

**Comment by MissPenguin** [comment]
怎么训练的呢，做了什么改动，命令贴一下吧

**Comment by yanceking** [comment]
我知道问题的原因了，因为官方文档描述的（https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md），训练自己的数据集，需要修改配置文件中的数据配置、字典文件以及类别数。以 configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml 为例，`
Architecture:
  # ...
  Backbone:
    name: LayoutXLMForSer
    pretrained: True
    mode: vi
    # 假设字典中包含n个字段（包含other），由于采用BIO标注，则类别数为2n-1
    num_classes: &num_classes 7

PostProcess:
  name: kieSerTokenLayoutLMPostProcess
  # 修改字典文件的路径为你自定义的数据集的字典路径
  class_path: &class_path train_data/XFUND/class_list_xfun.txt

Train:
  dataset:
    name: SimpleDataSet
    # 修改为你自己的训练数据目录
    data_dir: train_data/XFUND/zh_train/image
    # 修改为你自己的训练数据标签文件
    label_file_list:
      - train_data/XFUND/zh_train/train.json
    ...
  loader:
    # 训练时的单卡batch_size
    batch_size_per_card: 8
    ...

Eval:
  dataset:
    name: SimpleDataSet
    # 修改为你自己的验证数据目录
    data_dir: train_data/XFUND/zh_val/image
    # 修改为你自己的验证数据标签文件
    label_file_list:
      - train_data/XFUND/zh_val/val.json
    ...
  loader:
    # 验证时的单卡batch_size
    batch_size_per_card: 8`
但是kieSerTokenLayoutLMPostProcess根本就不存在

**Comment by yanceking** [comment]
还有个问题，自定义训练集，我用PaddleLabel  KIE标注的，为什么训练集不是以下的格式呢？
`" 图像文件名                 图像标注信息 "
zh_train_0.jpg   [{"transcription": "汇丰晋信", "label": "other", "points": [[104, 114], [530, 114], [530, 175], [104, 175]], "id": 1, "linking": []}, {"transcription": "受理时间:", "label": "question", "points": [[126, 267], [266, 267], [266, 305], [126, 305]], "id": 7, "linking": [[7, 13]]}, {"transcription": "2020.6.15", "label": "answer", "points": [[321, 239], [537, 239], [537, 285], [321, 285]], "id": 13, "linking": [[7, 13]]}]
zh_train_1.jpg   [{"transcription": "中国人体器官捐献", "label": "other", "points": [[544, 459], [954, 459], [954, 517], [544, 517]], "id": 1, "linking": []}, {"transcription": ">编号:MC545715483585", "label": "other", "points": [[1462, 470], [2054, 470], [2054, 543], [1462, 543]], "id": 10, "linking": []}, {"transcription": "CHINAORGANDONATION", "label": "other", "points": [[543, 516], [958, 516], [958, 551], [543, 551]], "id": 14, "linking": []}, {"transcription": "中国人体器官捐献志愿登记表", "label": "header", "points": [[635, 793], [1892, 793], [1892, 904], [635, 904]], "id": 18, "linking": []}]
...`
其中图像标注信息字符串经过json解析之后可以得到一个列表信息，列表中每个元素是一个字典，存储了每个文本行的需要信息，各个字段的含义如下。

transcription: 存储了文本行的文字内容
label: 该文本行内容所属的类别
points: 存储文本行的四点位置信息
id: 存储文本行的id信息，用于RE任务的训练
linking: 存储文本行的之间的连接信息，用于RE任务的训练


请问是我标注的方法有问题吗?

**Comment by zhaoqf-cq** [comment]
> anscription": "汇丰晋信", "label": "other", "points": [[104, 114], [530, 114], [530, 175], [104, 175]], "id": 1, "linking"

插个眼... 我训练出来也不是这种格式， 
``` {"transcription": "汇丰晋信", "key_cls": "other", "points": [[104, 114], [530, 114], [530, 175], [104, 175]], "difficult": true}```
 这样的... 然后我就用替换的形式修改的... 是我操作错了吗 有结果麻烦告知一下
