### ISSUE TITLE
请问有没有 ppstructure v2 的pdf可解析版本的脚本使用示例

### ISSUE THREAD

**Issue by Wall-ee** [PaddlePaddle/PaddleOCR#9745]
示例代码是命令行版本的pdf 2 word  以及  img识别方案的脚本示例。

请问有没有  可解析pdf  的Python脚本示例？

**Comment by MissPenguin** [comment]
可以看这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/recovery/README_ch.md

**Comment by MissPenguin** [comment]
> > 可以看这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/recovery/README_ch.md
> 
> 对 这个是命令行版本， 后来我结合那个 paddocr.py. 发现他还是依赖于 pdf2docx 这个项目。 但是这个项目的准确率并不高…………

嗯，确实这个解析功能只是简单集成了一下，没有做这部分的优化。。

**Comment by Wall-ee** [comment]
> > > 可以看这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/recovery/README_ch.md
> > 
> > 
> > 对 这个是命令行版本， 后来我结合那个 paddocr.py. 发现他还是依赖于 pdf2docx 这个项目。 但是这个项目的准确率并不高…………
> 
> 嗯，确实这个解析功能只是简单集成了一下，没有做这部分的优化。。

好的 谢谢，我发现这个的用法了，如果是可以用pdf2docx的项目，可以直接用pymupdf 自己来解析。然后把图片和表格调用ppstructure来处理， 效果很好

**Comment by chopin1998** [comment]
> 

请问您用 pymupdf 怎么扣出 一个pdf里的多个table？
