### ISSUE TITLE
ppocrlabel的KIE标注后全是"difficult": true

### ISSUE THREAD

**Issue by yaoman12345** [PaddlePaddle/PaddleOCR#9748]

**Comment by zhenhuamo** [comment]
我也是这样，请问你解决了吗

**Comment by yaoman12345** [comment]
直接把标签文件中的true替换成false.

**Comment by zhenhuamo** [comment]
3.4 导出部分识别结果
针对部分难以识别的数据，通过在识别结果的复选框中取消勾选相应的标记，其识别结果不会被导出。被取消勾选的识别结果在标记文件 label.txt 中的 difficult 变量保存为 True 。

注意：识别结果中的复选框状态仍需用户手动点击确认后才能保留

我看到文档这样说，但在软件里也没看到有复选框可以选

**Comment by yaoman12345** [comment]
我也没找到选择difficut的复选框，由于我的所有样本中的标注框都是false,所以我在标注完成后直接写个小脚本，将txt文件中的true都改为false。不过在后续的标注中difficut的状态又变为false。我也不知道什么原因造成的
