### ISSUE TITLE
svtr复现：训练后评估精度无法与官网一致

### ISSUE THREAD

**Issue by spencerr221** [PaddlePaddle/PaddleOCR#9752]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：paddle_2.4.1 
- 运行指令/Command Code：
- 训练过程运行指令：python3 tools/train.py -c configs/rec/rec_svtrnet.yml 
- 评估过程运行指令：
- python -m paddle.distributed.launch --gpus '0' tools/eval.py -c configs/rec/rec_svtrnet.yml -o Global.pretrained_model=/workspace/ppocr/paddleocr_0412/PaddleOCR/output/rec/svtr/best_accuracy.pdparams
其中 /workspace/ppocr/paddleocr_0412/PaddleOCR/output/rec/svtr/best_accuracy.pdparams为训练输出参数
配置文件为paddle最新configs/rec/rec_svtrnet.yml
数据集为lmdb格式，下载地址：https://github.com/clovaai/deep-text-recognition-benchmark#download-lmdb-dataset-for-traininig-and-evaluation-from-here
<img width="593" alt="Screenshot" src="https://user-images.githubusercontent.com/83412649/232400001-c7f1dbb5-4938-45d4-b546-fdc179f55778.PNG">

- 完整报错/Complete Error Message：
现评估精度如下：
<img width="799" alt="ppocr_refactor" src="https://user-images.githubusercontent.com/83412649/232400899-297db9ad-dffd-4fba-a501-9296cf5e10e5.PNG">
无法达到官网精度，请问什么原因，怎么调节超参。

**Comment by dlml** [comment]
估计有训练trick，以及数据预训练模型优势
