### ISSUE TITLE
对于重复字段，无法正确检测的问题

### ISSUE THREAD

**Issue by WUFENGSS** [PaddlePaddle/PaddleOCR#9754]
对于这种重复的字段貌似检测效果很差，是不是因为框架里面对重复情况有特殊处理呢，如图所示：

![Uploading result112.jpg…]()
![Uploading result002.jpg…]()

![Uploading result113.jpg…]()

**Comment by ToddBear** [comment]
看不到图片，可以重新上传一下吗？
