### ISSUE TITLE
显卡4090，cpu正常运行，gpu运行结果无法识别

### ISSUE THREAD

**Issue by fudemin1** [PaddlePaddle/PaddleOCR#9755]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
 显卡4090 ，paddleocr 2.6.1 paddlepaddle-gpu2.4.2  cuda10.2 cudnn7.6.5  ，用官方的图片测试，cpu 运行出的结果正常可以正确识别，gpu运行检测框全是乱的，有的就检测不出来

**Comment by andyjpaddle** [comment]
测试命令和结果发出来看看？

**Comment by andyjpaddle** [comment]
我这边测试正常的，这边有做什么修改吗

**Comment by fudemin1** [comment]
没有做任何修改，cpu跑的结果都是正常的，你用的也是4090吗，我看之前也有个人说4090无法正常识别

**Comment by andyjpaddle** [comment]
我这边不是4090，那有可能是兼容性问题？

**Comment by zhuhui1214** [comment]
解决了吗，我用4070Ti也遇到这个问题，CPU模型结果正确，但是GPU结果是错乱的

**Comment by zhuhui1214** [comment]
> 解决了吗，我用4070Ti也遇到这个问题，CPU模型结果正确，但是GPU结果是错乱的

后面解决了，有几个地方要修改，但是不同的环境有不同的方法，因人而异

**Comment by fudemin1** [comment]
> > 解决了吗，我用4070Ti也遇到这个问题，CPU模型结果正确，但是GPU结果是错乱的
> 
> 后面解决了，有几个地方要修改，但是不同的环境有不同的方法，因人而异
没有解决，应该是不兼容

**Comment by fudemin1** [comment]
没有解决，应该是不兼容 @zhuhui1214

**Comment by RRrrickHe** [comment]
@fudemin1 请问解决了吗？我4080卡，cuda cudnn都和你一样，识别不出来，不过我用的C++demo
@zhuhui1214 请问你是怎么解决的呢？

**Comment by RRrrickHe** [comment]
解决了，用了cuda11.6,  10.2cuda不支持8以上算力的cpu@fudemin1

**Comment by GuangtaoLyu** [comment]
> > 解决了吗，我用4070Ti也遇到这个问题，CPU模型结果正确，但是GPU结果是错乱的
> 
> 后面解决了，有几个地方要修改，但是不同的环境有不同的方法，因人而异

哥们能说一下怎么改吗
