### ISSUE TITLE
在训练识别模型时怎么冻结网络

### ISSUE THREAD

**Issue by liuzimo** [PaddlePaddle/PaddleOCR#9758]
文档有提到stop_gradient 但是具体没有说在什么文件里面进行设置

关于冻结backbone 
有提到x = self.backbone(x)

但是最新的代码是
if self.use_backbone:
    x = self.backbone(x)
   
   
  这个self.use_backbone 是在哪 配置文件吗 什么地方配置 或者说训练传入的参数吗

python tools/train.py -c configs/rec/rec_r34_vd_none_bilstm_ctc.yml -o Global.pretrained_model=./rec_r34_vd_none_bilstm_ctc_v2.0_train/best_accuracy

这是我训练的命令使用的配置文件

请问在什么地方更改可以冻结网络层

**Comment by andyjpaddle** [comment]
可以在backbone的最后一层的输出设置stop_gradient=true

> if self.use_backbone:
> x = self.backbone(x)

比如这里，可以设置x.stop_gradient=True

如果需要冻结其他层，可以在组网的时候设置参数冻结：
比如：
```
layers = nn.Linear()
for param in layers.parameters():
     param.trainable = False
```
