### ISSUE TITLE
当文字比较密集时候，除了迁移学习或者重新训练之外，请问还有其他办法可以提高检测效果吗？希望能出准确率更精准的模型，尤其是针对多行密集的文字。

### ISSUE THREAD

**Issue by DominicTerry** [PaddlePaddle/PaddleOCR#976]

**Comment by WenmuZhou** [comment]
不训练，基本就靠规则了吧

**Comment by LDOUBLEV** [comment]
检测效果不好可以发一些badcase看下？不清楚具体问题也很难说有好的方法

**Comment by DominicTerry** [comment]
@LDOUBLEV 自己写了一个web前端展示，文字密集时，文字区域捕捉不是特别准。
![QQ图片20201021142355](https://user-images.githubusercontent.com/34568768/96681132-51572b00-13a9-11eb-8bf4-7b30ea728f5a.png)
如图
![image](https://user-images.githubusercontent.com/34568768/96681014-21a82300-13a9-11eb-9397-a1f81f56d437.png)

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV 自己写了一个web前端展示，文字密集时，文字区域捕捉不是特别准。
> 如图
> ![image](https://user-images.githubusercontent.com/34568768/96681014-21a82300-13a9-11eb-9397-a1f81f56d437.png)

可否发一张原图，我看下可视化后的结果，这个问题不算严重，说不定改一下后处理可以解决

**Comment by DominicTerry** [comment]
@LDOUBLEV 原图如下
![20014](https://user-images.githubusercontent.com/34568768/96683330-a21c5300-13ac-11eb-9fb2-839e014c6cd1.png)

**Comment by DominicTerry** [comment]
我采用的是中英文通用OCR模型，DB算法，det_db_box_thresh=0，det_db_thresh=0.6，use_angle_cls=False，use_space_char=False 没有使用GPU use_gpu=False。其他的参数都是默认。

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/97382070-7f86be80-1905-11eb-8255-91ee0c717e5a.png)
我用det_res50_vb ，最下面出现一个空白的box，这个是什么问题呢

**Comment by DominicTerry** [comment]
> ![image](https://user-images.githubusercontent.com/12640462/97382070-7f86be80-1905-11eb-8255-91ee0c717e5a.png)
> 我用det_res50_vb ，最下面出现一个空白的box，这个是什么问题呢

最下面出现一个空白的box，说明你用的这个模型，把这个box图的背景当成文字检测了。
