### ISSUE TITLE
Problem in installing on MAC M1 PRO

### ISSUE THREAD

**Issue by alexandruvesa** [PaddlePaddle/PaddleOCR#9761]
Hello, I;m trying to install paddleocr on a MAC M1 PRO.

I;m using pipenv to create virtual environment.

I used python 3.10.2 and other versions starting from 3.8 and I get the same error:
/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pipenv-ckt3f0sl-requireme
nts/pipenv-daaaizce-requirement.txt (line 1)) (1.0.1)
Building wheels for collected packages: lanms-neo, PyMuPDF, fire, lxml,
python-docx, Polygon3, future, gevent, greenlet
  Building wheel for lanms-neo (pyproject.toml): started
  Building wheel for lanms-neo (pyproject.toml): finished with status
'done'
  Created wheel for lanms-neo:
filename=lanms_neo-1.0.2-cp310-cp310-macosx_12_0_arm64.whl size=103581
sha256=d7ae98fa461cfbec621ada0ef6408e3a356a846925177796ae55ed985d9c238c
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/39/2d/97/6339a08bcd70b34137a13f6506b29cdfa20fd345d478
1dbefc
  Building wheel for PyMuPDF (setup.py): started
  Building wheel for PyMuPDF (setup.py): finished with status 'error'
  Running setup.py clean for PyMuPDF
  Building wheel for fire (setup.py): started
  Building wheel for fire (setup.py): finished with status 'done'
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl
size=116932
sha256=60e9a53f5824349070b3dbb0ab2ce4c7eeba0ca266793ba698f71e9dd1b31ef7
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/90/d4/f7/9404e5db0116bd4d43e5666eaa3e70ab53723e1e3ea4
0c9a95
  Building wheel for lxml (setup.py): started
  Building wheel for lxml (setup.py): finished with status 'done'
  Created wheel for lxml:
filename=lxml-4.9.2-cp310-cp310-macosx_12_0_arm64.whl size=1676849
sha256=606c497440c10d764bb10544373acb23e682aa9b54b773a5618d36eac85790ef
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/5a/51/0e/95b4a6ddee4a616530c36aeb03dafb5e04183756d997
3a7d5d
  Building wheel for python-docx (setup.py): started
  Building wheel for python-docx (setup.py): finished with status 'done'
  Created wheel for python-docx:
filename=python_docx-0.8.11-py3-none-any.whl size=184491
sha256=010aa1b476c00a927456c831b0d2379123362ce540a3d830840c517efe06fdcc
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/80/27/06/837436d4c3bd989b957a91679966f207bfd71d358d63
a8194d
  Building wheel for Polygon3 (setup.py): started
  Building wheel for Polygon3 (setup.py): finished with status 'done'
  Created wheel for Polygon3:
filename=Polygon3-3.0.9.1-cp310-cp310-macosx_12_0_arm64.whl size=45061
sha256=3ec3e81045a38000557431e0265c80a533b6137fa59fdd9ea79796a66aa9f226
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/d8/b7/f6/b4e24f56a1cc9856dca98cc2fdc3915d7649b39b62f3
dbca9e
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl
size=492022
sha256=d30424e535ba0edcaaf10f364c312e0a93599993d821bfc37ab5a36588464777
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/5e/a9/47/f118e66afd12240e4662752cc22cefae5d97275623aa
8ef57d
  Building wheel for gevent (pyproject.toml): started
  Building wheel for gevent (pyproject.toml): still running...
  Building wheel for gevent (pyproject.toml): finished with status 'done'
  Created wheel for gevent:
filename=gevent-22.10.2-cp310-cp310-macosx_12_0_arm64.whl size=1783023
sha256=129c3f66193c2a69c168589f282f2d6baab867347438687b2392e0f1cad2fba3
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/17/de/c5/51b1e40d3d86a601c822e0cec04bfcdd91e56742b4d5
1e5408
  Building wheel for greenlet (setup.py): started
  Building wheel for greenlet (setup.py): finished with status 'done'
  Created wheel for greenlet:
filename=greenlet-2.0.2-cp310-cp310-macosx_12_0_arm64.whl size=195988
sha256=8ded2e944e27a4ad9fe3566efc46fe133c17d8e9483be458ccd38a23a3655b5f
  Stored in directory:
/private/var/folders/v9/kg9zy4tn6nz9yz830rvfyl7r0000gn/T/pip-ephem-wheel-c
ache-t2l6nge7/wheels/47/bc/8f/f9ec0af994f77b6f12a772b27c503c9658e7d5b10f09
68582a
Successfully built lanms-neo fire lxml python-docx Polygon3 future gevent
greenlet
Failed to build PyMuPDF
Installing collected packages: Polygon3, lanms-neo, tritonclient, PyMuPDF,
pydantic, pycryptodome, protobuf, orjson, opencv-python,
opencv-contrib-python, multidict, mdurl, lxml, linkify-it-py, lazy_loader,
itsdangerous, imageio, h11, grpcio, greenlet, future, fsspec, frozenlist,
fire, et-xmlfile, entrypoints, cython, cssutils, cssselect, click,
cachetools, Babel, attrdict, async-timeout, aiofiles, yarl, x2paddle,
uvicorn, starlette, scikit-image, python-docx, premailer, openpyxl, onnx,
markdown-it-py, httpcore, gevent, flask, bce-python-sdk, aiosignal,
pdf2docx, mdit-py-plugins, imgaug, httpx, geventhttpclient, Flask-Babel,
fastapi, altair, aiohttp, gradio-client, gradio, visualdl, paddleocr
  Running setup.py install for PyMuPDF: started
  Running setup.py install for PyMuPDF: finished with status 'error'

[36m  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-310
      creating build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/__init__.py ->
build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/fitz.py -> build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/utils.py -> build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/__main__.py ->
build/lib.macosx-12-arm64-cpython-310/fitz
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building 'fitz._fitz' extension
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/fitz
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code
-fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
-I/usr/local/include/mupdf -I/usr/local/include
-Imupdf/thirdparty/freetype/include -I/usr/local/include/freetype2
-I/usr/X11R6/include/freetype2 -I/opt/homebrew/include
-I/opt/homebrew/include/mupdf -I/opt/homebrew/include/freetype2
-I/Users/alexandruvesa/.local/share/virtualenvs/donut-bxlfDEPa/include
-I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/
include/python3.10 -c fitz/fitz_wrap.c -o
build/temp.macosx-12-arm64-cpython-310/fitz/fitz_wrap.o
      fitz/fitz_wrap.c:2755:10: fatal error: 'fitz.h' file not found
      #include <fitz.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1

  note: This error originates from a subprocess, and is likely not a
problem with pip.
  ERROR: Failed building wheel for PyMuPDF
  error: subprocess-exited-with-error

  × Running setup.py install for PyMuPDF did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running install
      /Users/alexandruvesa/.local/share/virtualenvs/donut-bxlfDEPa/lib/pyt
hon3.10/site-packages/setuptools/command/install.py:34:
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build
and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-310
      creating build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/__init__.py ->
build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/fitz.py -> build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/utils.py -> build/lib.macosx-12-arm64-cpython-310/fitz
      copying fitz/__main__.py ->
build/lib.macosx-12-arm64-cpython-310/fitz
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building 'fitz._fitz' extension
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/fitz
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code
-fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
-I/usr/local/include/mupdf -I/usr/local/include
-Imupdf/thirdparty/freetype/include -I/usr/local/include/freetype2
-I/usr/X11R6/include/freetype2 -I/opt/homebrew/include
-I/opt/homebrew/include/mupdf -I/opt/homebrew/include/freetype2
-I/Users/alexandruvesa/.local/share/virtualenvs/donut-bxlfDEPa/include
-I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/
include/python3.10 -c fitz/fitz_wrap.c -o
build/temp.macosx-12-arm64-cpython-310/fitz/fitz_wrap.o
      fitz/fitz_wrap.c:2755:10: fatal error: 'fitz.h' file not found
      #include <fitz.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1

  note: This error originates from a subprocess, and is likely not a
problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> PyMuPDF

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Thanks,
Alex

**Comment by vesaalexandru95** [comment]
Hello ! Did anybody solve this? Thanks

**Comment by HawkingRadiation42** [comment]
yeah im facing the same issue myself, created a new env and still getting the same error

**Comment by RaymnLee** [comment]
Same machine and same problem here!

**Comment by mediflux95** [comment]
And what version of paddlepaddle did you install ?

**Comment by ajayghiyad** [comment]
I have paddlepaddle==2.5.0 installed right now
But somehow it is just freezing, trying to create a docker container with ubuntu image
So that I can run the cpu version atleast on mac

**Comment by mediflux95** [comment]
Can you share please your dockerfile? Thanks !

**Comment by ajayghiyad** [comment]
I am trying some experiments with this

> registry.baidubce.com/paddlepaddle/paddle:2.4.2

as the base image

**Comment by ajayghiyad** [comment]
well I actually ended up solving the thing

[dockerFile](https://github.com/PaddlePaddle/Paddle/issues/54531#issuecomment-1619601905)

**Comment by HawkingRadiation42** [comment]
if anyone is stillfacing any error for installing paddleocr then try running this command worked pretty well for me dont know if it will work the same for you but worth the shot ig 

pip install joblib &&
pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1 &&
python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple&&
pip install --upgrade numpy&&
pip install --upgrade paddlepaddle paddleocr

**Comment by tjspross** [comment]
I think issue is still relevant

**Comment by OussamaBATOUCHE** [comment]
> on M2 Pro this seemed working with python 3.6-3.9 `pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1`
> 
> Thank you [AlienKevin](https://github.com/AlienKevin)

This worked for me, MacBook Pro **M1 Max**, macOS **Sonoma 14.3** , **python 3.9**

**Comment by jzhang533** [comment]
PyMuPDF is now optional.

**Comment by pprabakaran** [comment]
> > on M2 Pro this seemed working with python 3.6-3.9 `pip install "paddleocr>=2.0.1" --upgrade PyMuPDF==1.21.1`
> > Thank you [AlienKevin](https://github.com/AlienKevin)
> 
> This worked for me, MacBook Pro **M1 Max**, macOS **Sonoma 14.3** , **python 3.9**

This worked for me too. I installed without 'PyMuPDF' though. I have Mac M1 Pro with Sonoma 14.4.1
