### ISSUE TITLE
车牌识别，ch_PP-OCRv3_rec.yaml修改配置，image_shape从[3, 48, 320]修改成[3,96,256]报错

### ISSUE THREAD

**Issue by ChetWei** [PaddlePaddle/PaddleOCR#9763]
车牌识别，ch_PP-OCRv3_rec.yaml修改配置，image_shape修改成[3,96,256]报错，无法运行
原始的配置文件 image_shape: [3, 48, 320] 考虑到和车牌的长宽比不太匹配，所以想自定义image_shape
难道模型固定了输入尺寸吗？

**Comment by Cute-Yang** [comment]
是不是报了一个asser的错误？他那里识别的backbone要求输出的H的维度是1，因为后面会有一个image2sequence的过程，而他的backbone你观察一下，会将H的长度 缩放16倍，最后再接了一个 2x2 ，stride=2的池化，所以最终输出的H = 1，而你改成96之后， 96 / 16 = 6，然后再接一个 2x2池化，stride=1，padding=0的池化层后，输出的H的大小是 ceil((6 -1 ) / 2 ) = 3，当然就不满足了，看看你得backbone的输出是不是和我描述的一致

**Comment by Cute-Yang** [comment]
最后的池化层是2，打错了，抱歉
