### ISSUE TITLE
请问pdserving方式有没有并发处理，是否可以开启多线程或者多进程

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#977]
请问pdserving方式有没有并发处理，是否可以开启多线程或者多进程？现在是每次只能处理一条

**Comment by wangjiawei04** [comment]
这个正在讨论中，看看OCR本地预测中的多线程如何应用到Serving上

**Comment by coder-sun** [comment]
> 这个正在讨论中，看看OCR本地预测中的多线程如何应用到Serving上

本地预测现在怎么做多线程的呢，请问有没有相关介绍

**Comment by MissPenguin** [comment]
> > 这个正在讨论中，看看OCR本地预测中的多线程如何应用到Serving上
> 
> 本地预测现在怎么做多线程的呢，请问有没有相关介绍

最近增加了多进程预测的支持，可以看下这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q3444-%E5%A6%82%E4%BD%95%E5%A4%9A%E8%BF%9B%E7%A8%8B%E9%A2%84%E6%B5%8B

pdserving部署最近也有更新，可以拉取最新代码试试。

如果有新的问题，欢迎重新提issue。
