### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bulijojodibulido** [PaddlePaddle/PaddleOCR#9770]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
    CPU:  16核
    总显存: 128GB
    总内存: 128 GB
    总硬盘:  100 GB
    环境配置  Python:  3.7.4
    框架版本: PaddlePaddle 2.3.2
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 配置:
 Global:
  use_gpu: True
  epoch_num: 400
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 400
  eval_batch_step: [0, 331]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints: 
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ppstructure/docs/table/table.jpg
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 5096
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer
- 运行指令/Command Code：
  import os
  os.chdir('/home/aistudio/PaddleOCR')
  ! python3 tools/train.py -c configs/table/SLANet_ch.yml -o \
  Global.save_model_dir=./output/SLANet_finetune \
  Global.pretrained_model=./pretrain_models/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy.pdparams \
  Global.eval_batch_step=[0,375] \
  Global.print_batch_step=5 \
  Optimizer.lr.name=Const \
  Optimizer.lr.learning_rate=0.0005 \
  Train.dataset.data_dir=/home/aistudio/data/data165849/table_gen_dataset \
  Train.dataset.label_file_list=[/home/aistudio/train.txt] \
  Eval.dataset.data_dir=/home/aistudio/data/data165849/table_gen_dataset \
  Eval.dataset.label_file_list=[/home/aistudio/val.txt] \
- 完整报错/Complete Error Message：
 ppocr ERROR: When parsing line {"filename": "img/15.jpg", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td", " colspan=\"3\"", ">", "</td>", "<td", " colspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>",
  File "/home/aistudio/PaddleOCR/ppocr/data/pubtab_dataset.py", line 118, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/label_ops.py", line 725, in __call__
    if 'bbox' in cells[bbox_idx] and len(cells[bbox_idx][
IndexError: list index out of range

**Comment by bulijojodibulido** [comment]
{"filename": "img/15.jpg", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td", " colspan=\"3\"", ">", "</td>", "<td", " colspan=\"2\"", ">", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["合", "供", "現", "金", "流", "量", "表", "節", "项", "目"], "bbox": [[19, 9], [166, 9], [166, 25], [19, 25]]}, {"tokens": ["截", "至", "1", "2", "月", "3", "1", "日", "止", "年", "度"], "bbox": [[284, 49], [360, 49], [360, 65], [284, 65]]}, {"tokens": ["截", "至", "3", "月", "3", "1", "日", "止", "三", "個", "月"], "bbox": [[434, 49], [514, 49], [514, 65], [434, 65]]}, {"tokens": ["2", "0", "1", "9", "年", " ", "人", "民", "币", "千", "元"], "bbox": [[239, 68], [286, 68], [286, 104], [239, 104]]}, {"tokens": ["2", "0", "2", "0", "年", " ", "人", "民", "币", "千", "元"], "bbox": [[302, 68], [344, 68], [344, 107], [302, 107]]}, {"tokens": ["2", "0", "2", "1", "年", " ", "人", "民", "币", "千", "元"], "bbox": [[360, 70], [407, 70], [407, 106], [360, 106]]}, {"tokens": ["2", "0", "2", "1", " ", "年", " ", "人", "民", "币", "千", "元"], "bbox": [[422, 68], [468, 68], [468, 106], [422, 106]]}, {"tokens": ["2", "0", "2", "2", "年", " ", "人", "民", "币", "千", "元"], "bbox": [[482, 68], [529, 68], [529, 105], [482, 105]]}, {"tokens": ["管", "建", "资", "金", "变", "动", "前", "的", "经", "营", "性", "现", "金", "流", "量"], "bbox": [[17, 143], [137, 143], [137, 159], [17, 159]]}, {"tokens": ["1", ",", "5", "8", "4", ",", "8", "5", "2"], "bbox": [[250, 143], [288, 143], [288, 160], [250, 160]]}, {"tokens": ["2", ",", "1", "9", "8", ",", "3", "8", "3"], "bbox": [[310, 143], [349, 143], [349, 160], [310, 160]]}, {"tokens": ["2", ".", ",", "5", "4", "5", ",", "7", "3", "7"], "bbox": [[371, 143], [410, 143], [410, 160], [371, 160]]}, {"tokens": ["4", "4", ",", "1", "7", "6"], "bbox": [[439, 143], [472, 143], [472, 160], [439, 160]]}, {"tokens": ["6", "6", "1", ",", "5", "6", "8"], "bbox": [[499, 143], [533, 143], [533, 160], [499, 160]]}, {"tokens": ["管", "建", "资", "金", "变", "动"], "bbox": [[17, 160], [70, 160], [70, 176], [17, 176]]}, {"tokens": ["8", "4", "2", "1", "7", "9"], "bbox": [[254, 160], [288, 160], [288, 176], [254, 176]]}, {"tokens": ["7", "2", "4", ",", "5", "9", "0"], "bbox": [[316, 160], [349, 160], [349, 176], [316, 176]]}, {"tokens": ["7", "8", "4", ",", "1", "8", "0"], "bbox": [[376, 160], [411, 160], [411, 176], [376, 176]]}, {"tokens": ["(", "1", ",", "1", "4", "6", ",", "5", "4", "1", ")"], "bbox": [[430, 162], [473, 162], [473, 175], [430, 175]]}, {"tokens": ["(", "2", ",", "3", "9", "1", ",", "6", "8", "5", ")"], "bbox": [[491, 162], [534, 162], [534, 175], [491, 175]]}, {"tokens": ["已", "付", "税", "项"], "bbox": [[16, 177], [60, 177], [60, 194], [16, 194]]}, {"tokens": ["(", "3", "3", "6", ".", "0", "3", "8", ")"], "bbox": [[252, 177], [290, 177], [290, 194], [252, 194]]}, {"tokens": ["(", "3", "6", "5", ",", "7", "6", "6", ")"], "bbox": [[312, 177], [352, 177], [352, 194], [312, 194]]}, {"tokens": ["(", "4", "9", "6", ",", "3", "0", "6", ")"], "bbox": [[374, 177], [413, 177], [413, 194], [374, 194]]}, {"tokens": ["(", "2", "0", "6", ",", "4", "3", "1", ")"], "bbox": [[435, 177], [474, 177], [474, 194], [435, 194]]}, {"tokens": ["(", "1", "8", "7", ",", "3", "3", ")"], "bbox": [[496, 177], [536, 177], [536, 194], [496, 194]]}, {"tokens": ["经", "管", "活", "动", "所", "得", " ", "/", "(", "所", "用", ")", "现", "金", "流", "量", "净", "额"], "bbox": [[17, 195], [147, 195], [147, 210], [17, 210]]}, {"tokens": ["2", ",", "0", "9", "0", ",", "9", "9", "3"], "bbox": [[249, 194], [288, 194], [288, 210], [249, 210]]}, {"tokens": ["2", ",", "5", "5", "7", ",", "2", "0", "7"], "bbox": [[310, 196], [348, 196], [348, 209], [310, 209]]}, {"tokens": ["2", ",", "8", "3", "3", ",", "6", "1", "1"], "bbox": [[372, 196], [410, 196], [410, 209], [372, 209]]}, {"tokens": ["(", "9", "0", "8", ",", "7", "9", "6", ")"], "bbox": [[436, 196], [473, 196], [473, 209], [436, 209]]}, {"tokens": ["(", "1", ",", "9", "1", "7", ",", "4", "4", "8", ")"], "bbox": [[491, 196], [534, 196], [534, 209], [491, 209]]}, {"tokens": ["投", "资", "活", "动", "(", "所", "用", ")", " ", "/", " ", "所", "得", "现", "金", "流", "量", "净", "额", "."], "bbox": [[17, 211], [146, 211], [146, 227], [17, 227]]}, {"tokens": ["(", "6", "6", "5", ",", "8", "6", "2", ")"], "bbox": [[252, 211], [290, 211], [290, 228], [252, 228]]}, {"tokens": ["(", "1", ",", "9", "5", "0", ",", "3", "1", "2", ")"], "bbox": [[308, 211], [351, 211], [351, 228], [308, 228]]}, {"tokens": ["5", "1", "8", ",", "9", "2", "7"], "bbox": [[377, 211], [410, 211], [410, 228], [377, 228]]}, {"tokens": ["2", "2", ",", "5", "2", "2"], "bbox": [[443, 212], [471, 212], [471, 227], [443, 227]]}, {"tokens": ["(", "1", "7", "8", ",", "3", "8", ")"], "bbox": [[496, 211], [535, 211], [535, 228], [496, 228]]}, {"tokens": ["融", "资", "活", "动", "所", "得", " ", "/", "(", "所", "用", ")", "现", "金", "流", "量", "净", "额", ","], "bbox": [[17, 228], [147, 228], [147, 243], [17, 243]]}, {"tokens": ["(", "3", "2", "7", ",", "9", "1", "2", ")"], "bbox": [[253, 229], [289, 229], [289, 242], [253, 242]]}, {"tokens": ["(", "3", "9", "0", ",", "4", "9", "4", ")"], "bbox": [[314, 229], [350, 229], [350, 242], [314, 242]]}, {"tokens": ["(", "2", ",", "3", "1", "9", ",", "3", "0", "3", ")"], "bbox": [[369, 229], [411, 229], [411, 242], [369, 242]]}, {"tokens": ["(", "1", ",", "8", "5", "3", ")"], "bbox": [[442, 228], [474, 228], [474, 244], [442, 244]]}, {"tokens": ["(", "4", "8", "0", ",", "3", "6", "9", ")"], "bbox": [[497, 228], [536, 228], [536, 244], [497, 244]]}, {"tokens": ["现", "金", "及", "现", "金", "等", "价", "物", "增", "加", "/", "(", "减", "少", ")", "承", "额", "."], "bbox": [[17, 244], [147, 244], [147, 260], [17, 260]]}, {"tokens": ["1", ",", "0", "9", "7", ",", "2", "1", "9"], "bbox": [[249, 244], [288, 244], [288, 261], [249, 261]]}, {"tokens": ["2", "1", "6", ",", "4", "0", "1"], "bbox": [[315, 244], [349, 244], [349, 261], [315, 261]]}, {"tokens": ["1", ",", "3", ",", "2", "3", "5"], "bbox": [[371, 244], [410, 244], [410, 261], [371, 261]]}, {"tokens": ["(", "8", ",", "1", "7", ")"], "bbox": [[435, 244], [474, 244], [474, 261], [435, 261]]}, {"tokens": ["(", "2", ".", "5", "7", "6", "2", "0", "3", ")"], "bbox": [[491, 244], [535, 244], [535, 261], [491, 261]]}, {"tokens": ["年", "初", "／", "期", "初", "现", "金", "及", "现", "金", "等", "价", "物"], "bbox": [[18, 263], [123, 263], [123, 275], [18, 275]]}, {"tokens": ["4", ",", "0", "8", "7", ",", "1", "6", "3"], "bbox": [[250, 263], [287, 263], [287, 276], [250, 276]]}, {"tokens": ["5", ",", "1", "8", "4", ",", "7", "9", "2"], "bbox": [[310, 263], [348, 263], [348, 276], [310, 276]]}, {"tokens": ["5", ",", "3", "9", "7", ",", "6", "4", "6"], "bbox": [[372, 263], [409, 263], [409, 276], [372, 276]]}, {"tokens": ["5", ",", "3", "9", "7", ",", "6", "4", "6"], "bbox": [[434, 263], [471, 263], [471, 276], [434, 276]]}, {"tokens": ["6", ",", "4", "3", "0", "5", "5", "7"], "bbox": [[493, 261], [533, 261], [533, 277], [493, 277]]}, {"tokens": ["医", "率", "爱", "劲", "的", "影", "馨", "净", "额"], "bbox": [[18, 279], [90, 279], [90, 293], [18, 293]]}, {"tokens": ["4", "1", "0"], "bbox": [[269, 279], [288, 279], [288, 295], [269, 295]]}, {"tokens": ["(", "3", ".", "5", "4", "7", ")"], "bbox": [[321, 279], [351, 279], [351, 295], [321, 295]]}, {"tokens": ["(", "3", "2", "4", ")"], "bbox": [[387, 278], [412, 278], [412, 296], [387, 296]]}, {"tokens": ["2", "2", "7"], "bbox": [[453, 278], [471, 278], [471, 295], [453, 295]]}, {"tokens": ["3", "1"], "bbox": [[517, 278], [532, 278], [532, 296], [517, 296]]}, {"tokens": ["年", "来", "/", "期", "末", "现", "金", "及", "现", "金", "等", "价", "物"], "bbox": [[17, 298], [124, 298], [124, 313], [17, 313]]}, {"tokens": ["5", ",", "1", "8", "4", ",", "7", "9", "2"], "bbox": [[249, 298], [287, 298], [287, 315], [249, 315]]}, {"tokens": ["5", ",", "3", "9", "7", ",", "6", "4", "6"], "bbox": [[310, 298], [348, 298], [348, 315], [310, 315]]}, {"tokens": ["6", ",", "4", "3", "0", ",", "5", "7"], "bbox": [[371, 298], [409, 298], [409, 315], [371, 315]]}, {"tokens": ["4", ".", "5", "0", "9", "7", "4", "6"], "bbox": [[433, 298], [471, 298], [471, 315], [433, 315]]}, {"tokens": ["3", ".", "8", "5", "4", "3", "8", "5"], "bbox": [[494, 298], [532, 298], [532, 315], [494, 315]]}]}, "gt": "<html><body><table><tbody><tr><td></td><td colspan=\"3\"></td><td colspan=\"2\"></td></tr><tr><td></td><td></td><td></td><td></td><td>合供現金流量表節项目</td><td>截至12月31日止年度</td></tr><tr><td>截至3月31日止三個月</td><td>2019年 人民币千元</td><td>2020年 人民币千元</td><td>2021年 人民币千元</td><td>2021 年 人民币千元</td><td>2022年 人民币千元</td></tr><tr><td>管建资金变动前的经营性现金流量</td><td>1,584,852</td><td>2,198,383</td><td>2.,545,737</td><td>44,176</td><td>661,568</td></tr><tr><td>管建资金变动</td><td>842179</td><td>724,590</td><td>784,180</td><td>(1,146,541)</td><td>(2,391,685)</td></tr><tr><td>已付税项</td><td>(336.038)</td><td>(365,766)</td><td>(496,306)</td><td>(206,431)</td><td>(187,33)</td></tr><tr><td>经管活动所得 /(所用)现金流量净额</td><td>2,090,993</td><td>2,557,207</td><td>2,833,611</td><td>(908,796)</td><td>(1,917,448)</td></tr><tr><td>投资活动(所用) / 所得现金流量净额.</td><td>(665,862)</td><td>(1,950,312)</td><td>518,927</td><td>22,522</td><td>(178,38)</td></tr><tr><td>融资活动所得 /(所用)现金流量净额,</td><td>(327,912)</td><td>(390,494)</td><td>(2,319,303)</td><td>(1,853)</td><td>(480,369)</td></tr><tr><td>现金及现金等价物增加/(减少)承额.</td><td>1,097,219</td><td>216,401</td><td>1,3,235</td><td>(8,17)</td><td>(2.576203)</td></tr><tr><td>年初／期初现金及现金等价物</td><td>4,087,163</td><td>5,184,792</td><td>5,397,646</td><td>5,397,646</td><td>6,430557</td></tr><tr><td>医率爱劲的影馨净额</td><td>410</td><td>(3.547)</td><td>(324)</td><td>227</td><td>31</td></tr><tr><td>年来/期末现金及现金等价物</td><td>5,184,792</td><td>5,397,646</td><td>6,430,57</td><td>4.509746</td><td>3.854385</td></tr></tbody></table></body></html>"}

**Comment by bulijojodibulido** [comment]
以上数据通过 PPOcrLabel标注导出

**Comment by xunfeng2zkj** [comment]
大哥解决了吗,我也是在这个地方

**Comment by joshivikalp** [comment]
Any solution for this? Even I'm stuck here. thanks!

**Comment by mk25499** [comment]
哥，解决这个问题了吗？

**Comment by heyuqi1970** [comment]
这个问题解决了吗？
