### ISSUE TITLE
身份证+分类训练完成后，用推理模型推理是显示不出来类别？

### ISSUE THREAD

**Issue by litao-zhx** [PaddlePaddle/PaddleOCR#9771]
根据readme.md修改代码后，已完成模型的训练，用训练模型去推理的话显示正常，如下：
![image](https://user-images.githubusercontent.com/76981650/233060504-51a6e910-f0f5-499a-8da7-271322489b81.png)
转换成推理模型后，显示却异常，检测框过大，且显示没有类别，如下：
![image](https://user-images.githubusercontent.com/76981650/233061001-7bca34a2-9c64-4cbe-a8f4-68ba069bb912.png)
检测框的话，可以修改正确，但是类别这块改怎么修改呢？

**Comment by litao-zhx** [comment]
感觉是num_classes这个参数传进去，但是没找到入口

**Comment by mxzgn** [comment]
同样，预测模型效果更加，但是推理模型不准

**Comment by litao-zhx** [comment]
> 同样，预测模型效果更加，但是推理模型不准

已解决，具体可参考我的博客：https://blog.csdn.net/qq_55068938/article/details/130265458
