### ISSUE TITLE
pgnet 推理

### ISSUE THREAD

**Issue by Delay0123456789** [PaddlePaddle/PaddleOCR#9775]
(ppv3) db306@db306:/media/db306/data/zxs/ppv3/PaddleOCR-release-2.6$ python3 tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="/media/db306/data/zxs/ppv3/PaddleOCR-release-2.6/train_data_clear/det/train/0000.png" --e2e_model_dir="/media/db306/data/zxs/e2e_server_pgnetA_infer/" --e2e_pgnet_polygon=True
usage: predict_e2e.py [-h] [--use_gpu USE_GPU] [--use_xpu USE_XPU] [--use_npu USE_NPU] [--ir_optim IR_OPTIM]
                      [--use_tensorrt USE_TENSORRT] [--min_subgraph_size MIN_SUBGRAPH_SIZE] [--precision PRECISION]
                      [--gpu_mem GPU_MEM] [--image_dir IMAGE_DIR] [--page_num PAGE_NUM] [--det_algorithm DET_ALGORITHM]
                      [--det_model_dir DET_MODEL_DIR] [--det_limit_side_len DET_LIMIT_SIDE_LEN]
                      [--det_limit_type DET_LIMIT_TYPE] [--det_box_type DET_BOX_TYPE] [--det_db_thresh DET_DB_THRESH]
                      [--det_db_box_thresh DET_DB_BOX_THRESH] [--det_db_unclip_ratio DET_DB_UNCLIP_RATIO]
                      [--max_batch_size MAX_BATCH_SIZE] [--use_dilation USE_DILATION]
                      [--det_db_score_mode DET_DB_SCORE_MODE] [--det_east_score_thresh DET_EAST_SCORE_THRESH]
                      [--det_east_cover_thresh DET_EAST_COVER_THRESH] [--det_east_nms_thresh DET_EAST_NMS_THRESH]
                      [--det_sast_score_thresh DET_SAST_SCORE_THRESH] [--det_sast_nms_thresh DET_SAST_NMS_THRESH]
                      [--det_pse_thresh DET_PSE_THRESH] [--det_pse_box_thresh DET_PSE_BOX_THRESH]
                      [--det_pse_min_area DET_PSE_MIN_AREA] [--det_pse_scale DET_PSE_SCALE] [--scales SCALES]
                      [--alpha ALPHA] [--beta BETA] [--fourier_degree FOURIER_DEGREE] [--rec_algorithm REC_ALGORITHM]
                      [--rec_model_dir REC_MODEL_DIR] [--rec_image_inverse REC_IMAGE_INVERSE]
                      [--rec_image_shape REC_IMAGE_SHAPE] [--rec_batch_num REC_BATCH_NUM]
                      [--max_text_length MAX_TEXT_LENGTH] [--rec_char_dict_path REC_CHAR_DICT_PATH]
                      [--use_space_char USE_SPACE_CHAR] [--vis_font_path VIS_FONT_PATH] [--drop_score DROP_SCORE]
                      [--e2e_algorithm E2E_ALGORITHM] [--e2e_model_dir E2E_MODEL_DIR]
                      [--e2e_limit_side_len E2E_LIMIT_SIDE_LEN] [--e2e_limit_type E2E_LIMIT_TYPE]
                      [--e2e_pgnet_score_thresh E2E_PGNET_SCORE_THRESH] [--e2e_char_dict_path E2E_CHAR_DICT_PATH]
                      [--e2e_pgnet_valid_set E2E_PGNET_VALID_SET] [--e2e_pgnet_mode E2E_PGNET_MODE]
                      [--use_angle_cls USE_ANGLE_CLS] [--cls_model_dir CLS_MODEL_DIR] [--cls_image_shape CLS_IMAGE_SHAPE]
                      [--label_list LABEL_LIST] [--cls_batch_num CLS_BATCH_NUM] [--cls_thresh CLS_THRESH]
                      [--enable_mkldnn ENABLE_MKLDNN] [--cpu_threads CPU_THREADS] [--use_pdserving USE_PDSERVING]
                      [--warmup WARMUP] [--sr_model_dir SR_MODEL_DIR] [--sr_image_shape SR_IMAGE_SHAPE]
                      [--sr_batch_num SR_BATCH_NUM] [--draw_img_save_dir DRAW_IMG_SAVE_DIR]
                      [--save_crop_res SAVE_CROP_RES] [--crop_res_save_dir CROP_RES_SAVE_DIR] [--use_mp USE_MP]
                      [--total_process_num TOTAL_PROCESS_NUM] [--process_id PROCESS_ID] [--benchmark BENCHMARK]
                      [--save_log_path SAVE_LOG_PATH] [--show_log SHOW_LOG] [--use_onnx USE_ONNX]
predict_e2e.py: error: unrecognized arguments: --e2e_pgnet_polygon=True

**Comment by dengmingD** [comment]
--e2e_pgnet_polygon=True 这个参数是无效的
