### ISSUE TITLE
类似这种图片，怎么漂白成白色的干净图片？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9776]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 
![11](https://user-images.githubusercontent.com/41010669/233268654-486dd171-458f-44e0-bca9-1e2f88018042.jpg)

**Comment by WilliamQf-AI** [comment]
可以参考这个项目，模型我是跑出来了，不过推理时崩溃，你看看：
https://aistudio.baidu.com/bd-cpu-01/user/5480184/6619296/lab

**Comment by nissansz** [comment]
干扰很大的训练图，训练过程acc 0.3, loss 15, 实测准确度0.9以上，这种继续用高难度图片训练有什么影响吗？

**Comment by shiyutang** [comment]
这个项目我打不开呢@WilliamQf-AI

**Comment by WilliamQf-AI** [comment]
> 这个项目我打不开呢@WilliamQf-AI

设置了公开，现在应该可以了，你试试，正好看看为啥推理会有问题啊
