### ISSUE TITLE
paddleOCR识别部分部署多线程

### ISSUE THREAD

**Issue by GUOhm230** [PaddlePaddle/PaddleOCR#9778]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
- 系统环境/System Environment：安卓+armv8a，C++
- 版本号/Version：Paddle：  PaddleOCR： det: 自己训练的检测模型，rec: ch_PP-OCRv3_det_infer
- 问题相关组件/Related components：paddle_Lite: v2.10
- 运行指令/Command Code：多线程部署。大致代码如下:

1. 创建线程
`vector<paddle::lite_api::MobileConfig> configs;
for(int i=0; i<num_thread; i++){
            paddle::lite_api::MobileConfig config;
            config.set_model_from_buffer(model_buffer);
            config.set_threads(_thread_num);
            config.set_power_mode(_mode);
            configs.emplace_back(config);
  }
for(int i=0; i<num_thread;i++){
	LOGE("不复制，但创建多个解释器");
	_predictor.emplace_back(paddle::lite_api::CreatePaddlePredictor(configs[i]));
}
`
2. 模型检测与识别流程（多线程之前就出现问题了）
step1: 模型初始化
`
ppredictor::OCR_PPredictor *ocr_init
        (string det_encodeModel_path, string rec_ch_encodeModel_path,
         string rec_fri_encodeModel_path) {
    //配置信息初始化
    int thread_num = 4; //默认与创建的处理图片识别时的线程数一致
    std::string cpu_mode = "LITE_POWER_HIGH";
    ppredictor::OCR_Config conf;
    conf.use_opencl = 0; //根据不同机型获取数据
    conf.thread_num = thread_num;
    conf.mode = str_to_cpu_mode(cpu_mode);
    ppredictor::OCR_PPredictor *ocr_predictor;
    ocr_predictor = new ppredictor::OCR_PPredictor{conf};
    ocr_predictor->init_from_file(det_encodeModel_path, rec_ch_encodeModel_path,
                                  rec_fri_encodeModel_path);
    LOGE("OCR_INIT即模型初始化完成");
    return ocr_predictor;
}
`
step2: 模型检测
代码为官方提供：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/android_demo/app/src/main/cpp/ocr_ppredictor.cpp
step3: 建立四个子线程，每个子线程分配不同的文字图片进行同步识别
目前也只是用官方代码
- 完整报错/Complete Error Message：以上流程运行后，出现以下问题：

1. 使用飞桨文档提供创建多线程解释器的方法进行解释器克隆：https://www.paddlepaddle.org.cn/lite/v2.10/guides/performance_tuning/multi_thread.html。
结果发现只能多次创建，克隆是无法使用的。而且paddle_infer是啥也不太清楚。创建后这些解释器都能正常使用。
请问paddle_lite创建的解释器，里面和MNN一样，内部的缓存不允许多线程同时访问嘛？那如何通过克隆创建多个解释器，可以共享config和指针。这样可以减少空间吗？
2. 假设一张图片经过检测后，共有13个边框，我设置了4个子线程，每个子线程分别处理4, 3, 3, 3张图片。这样输入，输出是不共享的，但是内部很多中间变量是要共享的。请问这种可以实现嘛？

**Comment by Cute-Yang** [comment]
首先模型的权重的张量一定是可以共享的，你可以观察一下，在创建不同实例的时候，内存/显存的变化情况，是不是直接增加了模型的参数量那么大。paddle的话没看过源码，不怎么了解。但是在tensorRT中，他们的做法是 所有的线程共享模型参数，但是结果的中间变量是每个线程使用了单独的显存，这样就可以保证线程安全！

**Comment by GUOhm230** [comment]
> 首先模型的权重的张量一定是可以共享的，你可以观察一下，在创建不同实例的时候，内存/显存的变化情况，是不是直接增加了模型的参数量那么大。paddle的话没看过源码，不怎么了解。但是在tensorRT中，他们的做法是 所有的线程共享模型参数，但是结果的中间变量是每个线程使用了单独的显存，这样就可以保证线程安全！

我使用了官方的api做多线程克隆结果出错。我后来直接创建了多个解释器。其实不怎么增加内存和时间。但是多线程的效果不明显
