### ISSUE TITLE
cpu版运行正常，gpu版运行出现 Cudnn error, CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by wingloong** [PaddlePaddle/PaddleOCR#978]
cpu版运行正常，gpu版运行出现 Cudnn error， CUDNN_STATUS_EXECUTION_FAILED，请问这个问题如何解决？
paddlepaddle 版本1.8.5.post97
cuda 版本 9.0
cudnn 版本7.5

错误信息：
Cudnn error, CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:299)
   [operator < conv2d_fusion > error]

**Comment by littletomatodonkey** [comment]
你好，需要使用Paddle2.0.0b0的Paddle，同时需要保证cudnn版本为7.6~

**Comment by wingloong** [comment]
> 你好，需要使用Paddle2.0.0b0的Paddle，同时需要保证cudnn版本为7.6~
上面写错了，cuda版本是7.6.5，paddlepaddle 2.0.0b0也试了，同样的错误。用的是官方提供的docker_pdocr_cuda9.tar。
另外在出错信息的Python Call Stacks 出现了/root/anaconda3/envs/deploy/lib/python3.7...，这个就很奇怪，压根就没有安装这个python 环境！

**Comment by littletomatodonkey** [comment]
好的，我们再测试下

**Comment by ulanbator** [comment]
> cpu版运行正常，gpu版运行出现 Cudnn error， CUDNN_STATUS_EXECUTION_FAILED，请问这个问题如何解决？
> paddlepaddle 版本1.8.5.post97
> cuda 版本 9.0
> cudnn 版本7.5
> 
> 错误信息：
> Cudnn error, CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:299)
> [operator < conv2d_fusion > error]
同样是CUDA9 paddlepaddle-gpu 1.8.5.post97 cudnn7.6  
错误信息：
Cudnn error, CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:299)
[operator < conv2d_fusion > error]

之前在cuda10.1使用报错：ExternalError: Cublas error, CUBLAS_STATUS_EXECUTION_FAILED (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
[operator < fc > error]  提了issue说是不paddle2.0不兼容cuda10.1

已经配环境配了两天，希望尽快解决，实在不行只能考虑其他框架了。。。。

**Comment by LDOUBLEV** [comment]
> > cpu版运行正常，gpu版运行出现 Cudnn error， CUDNN_STATUS_EXECUTION_FAILED，请问这个问题如何解决？
> > paddlepaddle 版本1.8.5.post97
> > cuda 版本 9.0
> > cudnn 版本7.5
> > 错误信息：
> > Cudnn error, CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:299)
> > [operator < conv2d_fusion > error]
> > 同样是CUDA9 paddlepaddle-gpu 1.8.5.post97 cudnn7.6
> > 错误信息：
> > Cudnn error, CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:299)
> > [operator < conv2d_fusion > error]
> 
> 之前在cuda10.1使用报错：ExternalError: Cublas error, CUBLAS_STATUS_EXECUTION_FAILED (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
> [operator < fc > error] 提了issue说是不paddle2.0不兼容cuda10.1
> 
> 已经配环境配了两天，希望尽快解决，实在不行只能考虑其他框架了。。。。

试试这个docker，https://paddleocr.bj.bcebos.com/docker%2Fdocker_paddleocr_cuda9.tar.gz

**Comment by littletomatodonkey** [comment]
你好，可以试下这个docker：https://paddleocr.bj.bcebos.com/docker%2Fdocker_paddleocr_cuda9.tar.gz

**Comment by ulanbator** [comment]
> 你好，可以试下这个docker：https://paddleocr.bj.bcebos.com/docker%2Fdocker_paddleocr_cuda9.tar.gz

我是没办法运行PaddleOCR的测试代码，Paddle环境从CUDA10.1 paddle2.0报错你说不兼容  然后我转到cuda9.0 cudnn7.6 paddle1.8和上面报的错误是一样的 错误信息： Cudnn error， CUDNN_STATUS_EXECUTION_FAILED

**Comment by littletomatodonkey** [comment]
你的物理机cuda版本和cudnn版本是多少呢？

**Comment by wingloong** [comment]
> 你的物理机cuda版本和cudnn版本是多少呢？

我的物理机cuda版本10.0 cudnn版本7.6.5

**Comment by ulanbator** [comment]
> 你的物理机cuda版本和cudnn版本是多少呢？

cuda9 cudnn7.3.1  我看安装说明上说指定cuda9的cudnn必须要大于7.6的，但是7.6的cudnn和9.0的cudnn不匹配啊。所有说怎么在cuda9下能够正常使用gpu训练模型呢？

**Comment by littletomatodonkey** [comment]
你好，cudnn建议使用7.6版本的，cuda 选择9.0或者10.0都可以

**Comment by wingloong** [comment]
这个错误可能是cuda版本和GPU驱动版本不兼容导致的。
出错的环境是cuda 9.0 GPU驱动版本11.0
换了一台cuda 10.0 GPU驱动版本10.0就没有出现这个错误！

**Comment by wingloong** [comment]
这个错误可能是环境问题导致的。
出现错误的环境：
CUDA Driver API 11.0 （nvidia-smi命令显示的CUDA Version）
cuda 9.0 （nvcc命令显示的cuda version）
cudnn 7.6.5
换成
CUDA Driver API 10.0
cuda 10.0
cudnn 7.6.5 （注意安装cuda10.0对应的cudnn，我之前安装的是cuda9.0对应的cudnn，然后就出现了CUDNN_STATUS_EXECUTION_FAILED ）
就正常了

**Comment by wienerjier** [comment]
我通过下载"cuDNN v7.6.5 for CUDA 10.2"进行cudnn升级解决的此问题。我出现这个错误是因为第一次升级使用的是"cuDNN v7.6.5 for CUDA 9.0"。
我的本机是安装的cuda10.2，但docker环境中安装的是cuda9.0，我猜测应该是docker使用的还是本机的cuda10.2，所以应该下载"cuDNN v7.6.5 for CUDA 10.2"。

cudnn升级方法参考的这里 https://blog.csdn.net/lhxez6868/article/details/108769662，本机下载后 复制文件到docker环境中。

**Comment by oziasly** [comment]
多个APi同时调用cudnn好像也会出现这个问题，尝试一下多线程吧

**Comment by 1193700079** [comment]
减小batchsize 即可 跟环境无关

**Comment by autismmmmm** [comment]
> 减小batchsize 即可 跟环境无关

你好，为啥batchsize大了之后会报这个错误

**Comment by 1193700079** [comment]
> > 减小batchsize 即可 跟环境无关
> 
> 你好，为啥batchsize大了之后会报这个错误

我是试出来的，具体原因，时间久远我也忘记了

**Comment by LiuQing119** [comment]
> 减小batchsize 即可 跟环境无关

确实减小batch_size参数就有用了，原因未知。我以为真得换cudnn版本，但是在别的模型都能用，说明我的版本配置本身没问题。我把batch_size从4减到2目前可以可以训练成功了。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40288876/fe275fd2-41d4-4bd1-8e87-19f930f40c67)

**Comment by zhangwen54** [comment]
请问batchsize在哪里改啊？
