### ISSUE TITLE
这种图怎么生成比较好？腐蚀？膨胀？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9780]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

![image](https://user-images.githubusercontent.com/41010669/233295834-a06f4975-87f9-4a14-8732-6f9aac4225d8.png)

**Comment by austinleeee** [comment]
图像二值化更好

**Comment by nissansz** [comment]
我是要将pillow生成的清晰图片，转成模糊效果。
试了一些模糊，二值化，都不太相似

**Comment by austinleeee** [comment]
哦，可以使用opencv中的腐蚀操作

**Comment by nissansz** [comment]
也是不像

**Comment by austinleeee** [comment]
呢直方图你尝试过了么

**Comment by nissansz** [comment]
直方图是没有字的吧，是横向，纵向的波形图吧？

有没有识别图中字体名称的模型？
