### ISSUE TITLE
关于模型量化的一些疑问

### ISSUE THREAD

**Issue by justcodew** [PaddlePaddle/PaddleOCR#9786]
看了你们提供的一个车牌识别案例：[轻量级车牌识别.md](https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/applications/%E8%BD%BB%E9%87%8F%E7%BA%A7%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB.md#424-ccpd%E8%BD%A6%E7%89%8C%E6%95%B0%E6%8D%AE%E9%9B%86fine-tune%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83)
![image](https://user-images.githubusercontent.com/107862224/233371273-be6c7871-a468-458a-9445-f63f6237b5f3.png)

并做了一些测试，有一些疑问：

1.量化后的模型大小和速度具体是如何测试的，是否一定要在端侧转换为nb模型文件才能对比出int8的加速效果
2.不在端侧部署，在服务端如何测试验证int8的加速效果
3.在线量化训练acc为0，之前这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/5801)也出现过
4.车牌这个场景轻量化识别模型你们使用的是SVTR，是否对比过CRNN的效果
5.量化训练后的模型如何转换trt的engine文件，有没有相关的资料介绍，我是否可以使用paddle2onnx将量化训练的模型转化为uonnx文件后再转化为trt模型文件

感谢

**Comment by HappyJiaJun** [comment]
> 看了你们提供的一个车牌识别案例：[轻量级车牌识别.md](https://github.com/PaddlePaddle/PaddleOCR/blob/18ddb6d5f9bdc2c1b0aa7f6e399ec0f76119dc87/applications/%E8%BD%BB%E9%87%8F%E7%BA%A7%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB.md#424-ccpd%E8%BD%A6%E7%89%8C%E6%95%B0%E6%8D%AE%E9%9B%86fine-tune%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83) ![image](https://user-images.githubusercontent.com/107862224/233371273-be6c7871-a468-458a-9445-f63f6237b5f3.png)
> 
> 并做了一些测试，有一些疑问：
> 
> 1.量化后的模型大小和速度具体是如何测试的，是否一定要在端侧转换为nb模型文件才能对比出int8的加速效果 2.不在端侧部署，在服务端如何测试验证int8的加速效果 3.在线量化训练acc为0，之前这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/5801)也出现过 4.车牌这个场景轻量化识别模型你们使用的是SVTR，是否对比过CRNN的效果 5.量化训练后的模型如何转换trt的engine文件，有没有相关的资料介绍，我是否可以使用paddle2onnx将量化训练的模型转化为uonnx文件后再转化为trt模型文件
> 
>请问svtr对双行车牌的识别效果怎么样，您尝试过吗？
