### ISSUE TITLE
训练结果与推理结果不一致

### ISSUE THREAD

**Issue by shuihsaiu** [PaddlePaddle/PaddleOCR#9790]
在进行文本检测模型的效果预测时，效果表现出：训练模型>inference推理模型>onnx推理模型。对inference推理模型进行resize,同时对齐了前后处理的参数。但效果还是不一致。

**Comment by thsno02** [comment]
根据我的经验，在**相应的代码**里调整均值方差、resize 方法之后，效果是几乎一致，可以尝试在代码里 print 相关的参数，以确保调整都生效了。也可以把你的推理的命令、修改后的代码、训练时的参数贴出来看一下。

**Comment by shuihsaiu** [comment]
模型训练设置的参数：PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/val.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
          resize_long: 1280
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
inference推理代码：
# params for text detector
    parser.add_argument("--image_dir", type=str)
    parser.add_argument("--page_num", type=int, default=0)
    parser.add_argument("--det_algorithm", type=str, default='DB')
    parser.add_argument("--det_resize_long", type=float, default=1280)
    parser.add_argument("--det_model_dir", type=str)
    parser.add_argument("--det_limit_side_len", type=float, default=960)
    parser.add_argument("--det_limit_type", type=str, default='max')
    parser.add_argument("--det_box_type", type=str, default='quad')

    # DB parmas
    parser.add_argument("--det_db_thresh", type=float, default=0.3)
    parser.add_argument("--det_db_box_thresh", type=float, default=0.6)
    parser.add_argument("--det_db_unclip_ratio", type=float, default=1.5)
    parser.add_argument("--max_batch_size", type=int, default=10)
    parser.add_argument("--use_dilation", type=str2bool, default=True)
    parser.add_argument("--det_db_score_mode", type=str, default="fast")

**Comment by shuihsaiu** [comment]
onnx推理部分代码：
![image](https://user-images.githubusercontent.com/70890342/234154662-03bfdf70-5caa-4b98-8f0e-c05c00f21d15.png)

**Comment by thsno02** [comment]
均值方差看起来是对的。试试对齐 resize 方法，我记得 predict_det、infer_det 中 resize 方法有一些不一致。建议你可以先写定 resize shape，暂时不要使用 resize_long 或者是 min、max 这种会自适应变化图片大小的方法。
