### ISSUE TITLE
python: relocation error: /usr/local/cuda-11.1/lib64/libcublas.so: symbol runGemmShortApi, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleOCR#9793]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
请问这个问题怎么解决呢

python: relocation error: /usr/local/cuda-11.1/lib64/libcublas.so: symbol runGemmShortApi, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

**Comment by bdbaigc** [comment]
没人解答吗

**Comment by zjl123123zjl** [comment]
同样遇到了这个问题，请问你们解决了吗，可以提供一下解决方法吗，谢谢

> largerwxt

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
