### ISSUE TITLE
关于文本检测微调训练算法的选择问题

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9798]
文本检测微调训练可以选择其他算法吗？我看到ch_PP-OCRv3_det_student.yml中默认的是使用DB，但是我想尝试用DB++进行训练，并且想使用其他Backbone，我需要怎么做，还有就是ch_PP-OCRv3_det_cml.yml、ch_PP-OCRv3_det_dml.yml、ch_PP-OCRv3_det_student.yml三个配置文件分别有什么作用。谢谢大佬
![image](https://user-images.githubusercontent.com/110521846/233815582-248d9a80-e871-4f2c-bfea-7ac096c95ff3.png)

**Comment by Abraham-2020** [comment]
可以选择其他算法，更换backbone或其他部分请参考这个文档https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/add_new_algorithm.md
ch_PP-OCRv3_det_cml.yml、ch_PP-OCRv3_det_dml.yml是两个蒸馏配置文件，分别是CML蒸馏和DML蒸馏。

**Comment by MissPenguin** [comment]
DB++直接参考这个文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_det_db.md

关于三个配置文件：
ch_PP-OCRv3_det_cml.yml：cml蒸馏训练，得到蒸馏后的学生模型；
ch_PP-OCRv3_det_dml.yml：dml蒸馏训练，得到高精度teacher，该teacher用于cml蒸馏训练；
ch_PP-OCRv3_det_student.yml：直接训练学生模型，可以加载ppocrv3的模型作为预训练，直接finetune自己的模型，不用再走蒸馏的流程，比较高效。

更多信息可以参考PP-OCRv3的[技术报告](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/PP-OCRv3_introduction.md#2)和蒸馏训练的使用文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/knowledge_distillation.md#215-%E8%92%B8%E9%A6%8F%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83
