### ISSUE TITLE
超SR怎么与识别模型相结合使用？

### ISSUE THREAD

**Issue by ASLYY** [PaddlePaddle/PaddleOCR#9803]
项目中有关于超分辨率算法的实现比如sr_telescope.yml，但是怎么把SR与识别模块结合在一起使用呢？
想实现：用SR处理图像，得到高质量图像再进行识别
期待您的回复与解答，感谢！

**Comment by MissPenguin** [comment]
需要自己在推理代码里面串一下。先分别把两部分的推理调通，然后改下代码，把SR作为一个预处理模块集成进去。
