### ISSUE TITLE
如何获取单个字符的位置坐标信息？

### ISSUE THREAD

**Issue by zhenhuamo** [PaddlePaddle/PaddleOCR#9807]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
使用OCR检测出来的是整行字符串的位置坐标，有没办法可以获取到单个字符的位置信息？

**Comment by jingmingtao** [comment]
> 字符检测：https://github.com/fanqie03/char-detection/tree/main

请问该字符检测可以支持倾斜的图片文字，以及背景复杂的情况吗，该字符检测的输出是字符的位置以及该字符是什么吗

**Comment by jingmingtao** [comment]
> 字符检测：https://github.com/fanqie03/char-detection/tree/main

请问一下该字符检测需要训练吗，是不需要训练就直接用吗

**Comment by UserWangZz** [comment]
如果官方模型在您的场景下表现不理想就需要您微调模型
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
