### ISSUE TITLE
the difference between paddle and onnx

### ISSUE THREAD

**Issue by Cute-Yang** [PaddlePaddle/PaddleOCR#9809]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by Cute-Yang** [comment]
### the hardsigmoid function difference
+ the paddle's F.hardsigmoid function support slope and offset used in transform y = slope * x + offset,but the onnx's hardsigmoid node only have slope param. And I see the slope and offset is constant (1/6 and 0.5) in Pytorch.,so what should i do if the slope != 1/6 and offset !=0.5 in paddle while I want to use other framework to load the paddle weight?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
