### ISSUE TITLE
在做表格预测的时候，用的是系统提供的中文表格预测模型。但是有点问题。是我预测参数有问题，还是我得准备数据进行微调

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9811]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
python table/predict_table.py \
--det_model_dir=inference/ch_PP-OCRv3_det_infer \
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
--table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer \
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
--image_dir=/home/DiskA/zncsPython/picture_ocr/table/test/table_predict/3_table.jpg \
--output=/home/DiskA/zncsPython/picture_ocr/table/test/table_predict_result

```
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/32863094/233935750-e48b09ba-4ccb-490c-8588-3cc689799ae0.png)

![image](https://user-images.githubusercontent.com/32863094/233935600-ba803614-55f2-45fd-87a7-00de692a7903.png)
![image](https://user-images.githubusercontent.com/32863094/233935659-2ebb8613-af50-43d6-bf0d-7707a099aa1e.png)

**Comment by yeying0310** [comment]
您用好未来的那个数据集训练过吗

**Comment by rexzhengzhihong** [comment]
> 您用好未来的那个数据集训练过吗

没有，直接用的ch_ppstructure_mobile_v2.0_SLANet_infer。用好未来数据集可以训练过就行吗

**Comment by yeying0310** [comment]
不知道啊，我是识别嵌套的表格效果很差，想用好未来的重训练一下，但那个数据集读取时有些问题，想问问您用过没

**Comment by rexzhengzhihong** [comment]
> 不知道啊，我是识别嵌套的表格效果很差，想用好未来的重训练一下，但那个数据集读取时有些问题，想问问您用过没
原来您是用ch_ppstructure_mobile_v2.0_SLANet_infer还是自己训练的？

**Comment by yeying0310** [comment]
> > 不知道啊，我是识别嵌套的表格效果很差，想用好未来的重训练一下，但那个数据集读取时有些问题，想问问您用过没
> > 原来您是用ch_ppstructure_mobile_v2.0_SLANet_infer还是自己训练的？

用的SLANet模型，也试了一下tablemaster，效果都不好

**Comment by rexzhengzhihong** [comment]
> tablemaster

是。感觉是不是需要自己打标签微调。可是上面写至少几千张，没那么多数据

**Comment by rexzhengzhihong** [comment]
> > > 不知道啊，我是识别嵌套的表格效果很差，想用好未来的重训练一下，但那个数据集读取时有些问题，想问问您用过没
> > > 原来您是用ch_ppstructure_mobile_v2.0_SLANet_infer还是自己训练的？
> 
> 用的SLANet模型，也试了一下tablemaster，效果都不好

兄弟，后来则呢么处理的?？?

**Comment by rexzhengzhihong** [comment]
@LDOUBLEV

**Comment by wzgwy** [comment]
请问一下这个框回归和检测模型回归的差距很大，这个是参数设置的问题吗？

**Comment by nissansz** [comment]
> 不知道啊，我是识别嵌套的表格效果很差，想用好未来的重训练一下，但那个数据集读取时有些问题，想问问您用过没

 可以百度网盘分享一下好未来数据集吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
