### ISSUE TITLE
文本检测有随机反转颜色的数据增强可用吗？Any random color inversion augumentation configurable for det model training (DB)?

### ISSUE THREAD

**Issue by gongliyu** [PaddlePaddle/PaddleOCR#9815]
训练文本检测模型，想随机一个概率把整张图片的所有像素颜色翻转 RGB2 = 255 - RGB. 有可以直接配置的方法吗？谢谢🙏

**Comment by andyjpaddle** [comment]
可以在 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/data/imaug/operators.py#L67 之前加一个条件控制，例如：
```
if random.random()>0.5:
    img = 255 - img
```
