### ISSUE TITLE
有没有办法限定识别字符的范围？

### ISSUE THREAD

**Issue by 0-Maxwei-0** [PaddlePaddle/PaddleOCR#9817]
例如真实字符只可能是AEIOU这几个字母，识别出的结果也一定只包含这几个字符。

**Comment by andyjpaddle** [comment]
可以加后处理过滤掉不需要的字符

**Comment by 0-Maxwei-0** [comment]
就是我想实现这样的效果：目前我的待识别图片里只有AEIOU这几个字母的不同组合。我希望在进行OCR识别时，模型能够只从这几个字母中选择最匹配的字母。相当于杜绝了错误识别出了其它字母的可能性。

**Comment by 555myhair** [comment]
@0-Maxwei-0  请问你这个限定识别范围实现了吗?
