### ISSUE TITLE
文本检测，在自己的数据场景下微调，训练集的预测结果都不是很好

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9818]
你好，我在自己的数据场景下进行文本检测DB算法微调，为什么对训练集进行定位都效果欠佳

**Comment by luoyq6** [comment]
@andyjpaddle

**Comment by andyjpaddle** [comment]
可能原因：
1. 训练集数量较少
2. 数据太难，检查下标注是否正确
3. 训练不收敛

**Comment by xunfeng2zkj** [comment]
> 可能原因：
> 
> 1. 训练集数量较少
> 2. 数据太难，检查下标注是否正确
> 3. 训练不收敛

怎么样才标注才算正常呢,找了几天了,PPOCRLabel一个标准都没有,只告诉你要这样
