### ISSUE TITLE
依赖安装报错

### ISSUE THREAD

**Issue by jinchunzhao** [PaddlePaddle/PaddleOCR#9820]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： x86_64
CentOS Linux release 7.9.2009 (Core)

- 版本号/Version：Paddle：  PaddleOCR： 2.4.2
- 问题相关组件/Related components：
- 运行指令/Command Code：python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
- 完整报错/Complete Error Message：

Requirement already satisfied: certifi>=2017.4.17 in /usr/local/python3/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle) (2022.12.7)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.

**Comment by zwang98** [comment]
安装PaddleOCR-release-2.6时有同样问题:
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.0 which is incompatible.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
icetk 0.0.7 requires protobuf<3.19, but you have protobuf 3.20.0 which is incompatible.
安装的packages中 onnx 和 tensorboard、icetk需求冲突
