### ISSUE TITLE
crnn训练，怎么合并多种字体的模型比较好？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9821]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.5  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

crnn训练，怎么合并多种字体的模型比较好？

有没有识别字体名的模型？

**Comment by livingbody** [comment]
可以多种字体一起训练，合并数据集。
字体识别模型还么有，我没见到。

**Comment by shiyutang** [comment]
已有多种模型的话，可以参考模型集成。

**Comment by nissansz** [comment]
怎么集成？
印刷扫描体有什么好的模拟生成程序吗

**Comment by shiyutang** [comment]
可以使用styleText进行模拟生成：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/StyleText

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by nissansz** [comment]
目前日文字幕模型，模拟字幕效果还可以。但用这个模型识别扫描文件，反而会有错误，有时是英文，数字错误。
不知道怎么改善

**Comment by shiyutang** [comment]
可以给出运行的指令和效果吗？

**Comment by nissansz** [comment]
就是0O之类错误，或多字，少字，错字

**Comment by livingbody** [comment]
> 就是0O之类错误，或多字，少字，错字

可以针对易错字构造数据集继续进行训练。

**Comment by nissansz** [comment]
你有训练好的模型可以分享吗

**Comment by livingbody** [comment]
我没训。

**Comment by nissansz** [comment]
resnet18, resnet34等都能训练crnn?
哪个好？

**Comment by shiyutang** [comment]
模型越大精度越高，但是需要的数据也越多。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
