### ISSUE TITLE
预训练权重的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleOCR#9826]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
使用的是最新的paddleocr，我发现自己训练完模型得到参数文件后，为什么不能将我训练好的参数作为预训练权重导入，它下面老提示找不到名字对应的模块，请问怎么解决

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
