### ISSUE TITLE
Makefile:4: ../Makefile.def: No such file or directory 树莓派上make -j 

### ISSUE THREAD

**Issue by wowowoll** [PaddlePaddle/PaddleOCR#983]
无法进行编译

**Comment by LDOUBLEV** [comment]
查看你编译的预测库是否有  Makefile.def 这个文件
![image](https://user-images.githubusercontent.com/26592129/96818930-10b4eb80-1455-11eb-9815-9b0996151c8f.png)

**Comment by wowowoll** [comment]
没有Makefile.def  这个文件是通过编译生成的吗

**Comment by LDOUBLEV** [comment]
是编译生成的，检查下预测库是否编译成功

**Comment by siyuzhong94** [comment]
> 是编译生成的，检查下预测库是否编译成功



> 查看你编译的预测库是否有 Makefile.def 这个文件
> ![image](https://user-images.githubusercontent.com/26592129/96818930-10b4eb80-1455-11eb-9815-9b0996151c8f.png)

楼主是做的ppocr移植到树莓派么
