### ISSUE TITLE
训练图和label 里如何让每个字符的出现频率类似，尤其是生僻字

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9830]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练图和label 里如何让每个字符的出现频率类似，尤其是生僻字

**Comment by livingbody** [comment]
我知道，你说的是识别模型，可以数据均衡。

**Comment by nissansz** [comment]
数据均衡怎么实现？

**Comment by nissansz** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/67d3e6ce-d271-4e67-8315-8eb9dee8f851)

怎么模拟这种效果？有没有python代码，方法？

**Comment by shiyutang** [comment]
参考styletext：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/StyleText

**Comment by nissansz** [comment]
styletext不太好，只支持部分语种。而且效果也不接近

**Comment by shiyutang** [comment]
还有TextRender可以尝试，效果会好于StyleText。

**Comment by nissansz** [comment]
resnet34 默认学习率    learning_rate: 0.0005
训练到一定准确度后没法继续改善，能修改lr继续提高准确率吗？修改多少比较好？

**Comment by shiyutang** [comment]
这个可以看你的设置，如果bs增大了，可以采用更大的学习率。另外设置阶梯学习率，例如0.0005、0.0001、0.001、0.002、0.00005等进行尝试，找到适合的学习率在附近微调。

**Comment by nissansz** [comment]
[StyleText](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/StyleText
怎样支持繁体，日文等字体？

resnet34 默认学习率是固定的，    learning_rate: 0.0005 训练过程中是可以改的？

**Comment by nissansz** [comment]
yml怎么改成resnet18或其他backbone，

**Comment by nissansz** [comment]
yml怎么改成resnet18或其他backbone，改成这些backbone, crnn还能训练吗？源代码要不要改？

**Comment by shiyutang** [comment]
修改支持的backbone是可以训练的，可以参考：https://github.com/PaddlePaddle/PaddleOCR/blob/61b3fee29183d38b4ef24347472f4b468e27fc97/configs/rec/rec_r34_vd_tps_bilstm_ctc.yml#L41C1-L41C1

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
