### ISSUE TITLE
文本检测模型训练时自动停止问题

### ISSUE THREAD

**Issue by lipeng1109** [PaddlePaddle/PaddleOCR#9833]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6
- 版本号/Version：Paddle：2.4.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3  -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml \
    -o Global.pretrained_model=./student \
       Global.save_model_dir=./output/
- 完整报错/Complete Error Message：不报错，在打印完这个自动停止：During the training process, after the 0th iteration, an evaluation is run every 400 iterations

奇怪的是使用batch=4可以开始训练，其他的batch就会自动停止，也没有任何提示

**Comment by WenmuZhou** [comment]
你的数据量多大呢

**Comment by lipeng1109** [comment]
> 你的数据量多大呢

你好，我的训练数据19W，验证数据1W左右，我已经定位到了，验证集的bacth必须设置为1，这个是文本检测算法的特点吗？

**Comment by lipeng1109** [comment]
我将验证集的batch设置为1出现了报错：Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1682673486 (unix time) try "date -d @1682673486" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x285a00008687) received by PID 34439 (TID 0x7f874c9db3c0) from PID 34439 ***]
@WenmuZhou
