### ISSUE TITLE
ch_PP-OCRv3_det_dml.yml  文本检测知识蒸馏

### ISSUE THREAD

**Issue by bianliuyang** [PaddlePaddle/PaddleOCR#9834]
我想请问一下，dml不是训练教师模型吗，为什么这里Teacher模型为mbv3，学生模型为resnet50呀，不应该教师是大模型，学生是小模型吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
