### ISSUE TITLE
"output_tensor.copy_to_cpu()" take too long to execute 

### ISSUE THREAD

**Issue by chelzakaria** [PaddlePaddle/PaddleOCR#9836]
系统环境/System Environment：Python 3.10.7 | Win10
版本号/Version：CUDA 11.6, CuDNN 8.8 Paddle：2.4.2.post112 PaddleOCR：2.6.1.3
问题相关组件/Related components: RTX 3080 
运行指令/Command Code：
--------------------------------
Trying to optimize the model performance speed by identifying how long code cells/blocks/functions take to execute, I found that in this line "Copying the output of recognition to the CPU": 
https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_rec.py#L542
that it took approximately 50% of whole recognition process which I found weird, compared to the same process for Detection (https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_det.py#L246) or TextClassifier (https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_cls.py#L112).
Aiming to optimize the OCR process I want to know why exactly it took that long to execute, and if there is any way to improve it?

**Comment by WenmuZhou** [comment]
In this sentence, getting data from gpu to cpu will take a long time due to bandwidth and other reasons.

**Comment by chelzakaria** [comment]
I know it takes time to get data from GPU, but what I don't understand is why the problem occurs only in the recognition part of the model process? : https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_rec.py#L611
This isn't a problem for the Detection and TextClassifier, as shown above.
For the purpose of really proving the issue, I used a simple image from your repository ((https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/013870d9bc963f7508d5a76f81da872b84471a71/doc/imgs_en/img623.jpg)) and I ran the process multiple times (to be specific, I ran it 1000 times) and this is what the result looked like:
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/80723047/03b4acc0-682b-4d07-908c-9ca55b9e722d)
As shown in the chart above, I have taken the distribution of the results and divided them into percentiles. As shown the median is 1.19 ms and the 95th percentile shows a significant change, which indicates that the model is performing inconsistently, which indicates that it may need to be improved. 
It would be helpful if you could provide me with an explanation as to why the model is acting in this manner, as well as exactly where the problem lies.

Also I included a csv file for the results that I got if needed.
[performance_paddleocr.csv](https://github.com/PaddlePaddle/PaddleOCR/files/11463776/performance_paddleocr.csv)

--------
P.S: I'm using Windows 10, python 3.10.7, CUDA 11.6, CuDNN 8.8 Paddle：2.4.2.post112, Driver Version: 531.79

**Comment by chelzakaria** [comment]
@WenmuZhou any updates !?

**Comment by y2k0999** [comment]
Is there a change you're running async code and the timer functions are messing up? I've run into similar issues before when timing the run time of cuda kernels without proper synchronization. It might be the prediction step that's taking so long, not the copying step.
