### ISSUE TITLE
PPOCRv3 不定长文本识别问题

### ISSUE THREAD

**Issue by bianliuyang** [PaddlePaddle/PaddleOCR#9842]
看了相关的issue，说是在PPOCRV3中对svtr做了改进，改了backbone 为lcnet结构，我想请问一下en_PP-OCRv3_rec.yml中的backbone：mobilenetv1enhance就是lcnet结构吗？另外en_PP-OCRv3_rec.yml文件中，还是要设置max_text_length，那加入我不知道图片中的最长的字符有多长，只知道有短文本和长文本，这怎么完成不定长文本识别呢。

**Comment by super-tian** [comment]
max_text_length指的是最大长度，你给你的最大长度就行

**Comment by ccx1997** [comment]
ICCV2023的工作LISTER可以解决这个问题
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/tree/main/OCR/LISTER

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
