### ISSUE TITLE
获取资料添加微信失败，提示被加好友过于频繁

### ISSUE THREAD

**Issue by equationl** [PaddlePaddle/PaddleOCR#9846]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/README.md#2

在这里填写调查问卷后获取到微信二维码，但是无法添加，提示被加好友过于频繁

**Comment by XiaokangLei** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by equationl** [comment]
@an1018 hello，发送了好友申请但是一直没同意啊

**Comment by an1018** [comment]
收到，已反馈
