### ISSUE TITLE
table_master 模型训结果偏差太大

### ISSUE THREAD

**Issue by Leezzzzz** [PaddlePaddle/PaddleOCR#9848]
table_master模型数据标注格式是什么？左上角顶点xy坐标加上宽度和高度吗？
为什么我的模型训练后的表格识别结果往左上角偏移
![image](https://user-images.githubusercontent.com/62826242/235128482-def098fe-c4f3-4054-a34d-911ed83888a6.png)
![image](https://user-images.githubusercontent.com/62826242/235128516-51db8e48-9b86-4372-aa46-d43b3f9c9a08.png)
我的标注数据是没有问题，按照xywh标注的
![image](https://user-images.githubusercontent.com/62826242/235128558-7aa3df78-7d14-4f9c-9dac-e4a54e353cc0.png)
![image](https://user-images.githubusercontent.com/62826242/235128574-42ca76b9-c38c-4b4c-ac0a-c0fc0f2af519.png)

**Comment by liuyifan6613** [comment]
有偏移的，要加上layout出来的这块表格的左上顶点坐标。
