### ISSUE TITLE
backbone support for text orientation detection

### ISSUE THREAD

**Issue by JINO-ROHIT** [PaddlePaddle/PaddleOCR#9850]
Is mobilenet v3 the only backbone i can use for text orientation? is there any other backbone support? is there any documentation for this?

Also after training custom text orientation, theres no pdmodel or pdparams to run complete inference? how to use the custom model files for inference in the scripts tools/infer.py

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
