### ISSUE TITLE
how to detect rolling text from video,avoid repetative text

### ISSUE THREAD

**Issue by akashAD98** [PaddlePaddle/PaddleOCR#9852]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

i have frames & i want only single output which will save result of unique text,insted of same text, how can i build this system logic

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
