### ISSUE TITLE
Paddleocr怎么测速？

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleOCR#9853]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

请问paddleocr怎么对模型进行测速，我看只有评估的时候会出现一个fps，我用ppocrv3_det训练自己的数据集，显卡为3090，并没有其他地方占用，最后fps评估时才9的fps，这显然不合理

**Comment by MissPenguin** [comment]
评估是基于训练引擎的预测，转推理模型后预测速度会变快。
基于推理引擎预测时，可以打开benchmark开关进行测速：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_det.py#L154
