### ISSUE TITLE
其他語言? (端到端預訓練模型、PPOCRLabel)

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#9854]
1.端到端預訓練模型語言現有是否只包含英文與簡中，是否還有其他模型，例如英+繁中`
若需要用端到端從頭訓練其他語言，大概多少資料才足夠?

2.PPOCRLabel也只有簡中+英文嗎?
謝謝

**Comment by livingbody** [comment]
亲，可以使用其他语言模型，以及自定义模型。

参考：[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md)
![360截图20230630180743576](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/cdd11024-38b6-4947-9543-91d73a216c45)

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

**Comment by shiyutang** [comment]
端到端模型目前只支持PGNet，且在ICDAR2015上进行预训练。但是ppocr两阶段算法支持包括繁体在内的多语言模型：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md#%E8%AF%AD%E7%A7%8D%E7%BC%A9%E5%86%99
