### ISSUE TITLE
KIE 实际场景中几个问题

### ISSUE THREAD

**Issue by lbeing** [PaddlePaddle/PaddleOCR#9858]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

1、chunk只使用了前面512个，实际场景都不止512个，所以根本不可用
class VQASerTokenChunk(object):
    def __init__(self, max_seq_len=512, infer_mode=False, **kwargs):
        self.max_seq_len = max_seq_len
        self.infer_mode = infer_mode

    def __call__(self, data):
        ...
        return encoded_inputs_all[0]
2、实际场景中表格中一个单元格经常对文本进行分行，而OCR识别结果是是单行，SER+RE数据任务输入时却是一行，这也导致整体串不起来。是否有OCR检测和识别任务支持多行？如果有请告知

**Comment by XiaokangLei** [comment]
我也有这样的问题，经常碰见key是多行的情况

**Comment by azhaoid** [comment]
请问max_seq_len这个参数不可以加大了吗？我设置成1024报错了。

alueError: (InvalidArgument) The value (514) of the non-singleton dimension does not match the corresponding value (1024) in shape for expand_v2 op.
