### ISSUE TITLE
文本检测不出来是什么原因？

### ISSUE THREAD

**Issue by Ludasheng** [PaddlePaddle/PaddleOCR#9859]
训练：python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.checkpoints=output/ch_PP-OCRV3_det/best_accuracy

参考：模型微调做的，https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md

训练集840张图片，测试集91张图片。歪的的检测效果不好，训练样本里也有歪的图片。

![image](https://user-images.githubusercontent.com/41037283/236097850-d9528c22-3607-42cf-bf48-b558308ff0af.png)

**Comment by WenmuZhou** [comment]
训练的指标是多少呢

**Comment by Ludasheng** [comment]
@WenmuZhou 大佬好。

我的配置  ch_PP-OCRv3_det_student.yml
![image](https://user-images.githubusercontent.com/41037283/236372077-7789c660-0db0-4c39-a2bf-5b059fdef965.png)
![image](https://user-images.githubusercontent.com/41037283/236372092-5b604a00-4576-4aa3-aa7b-da60b2e3500d.png)
![image](https://user-images.githubusercontent.com/41037283/236372109-42653d77-b863-4479-9449-b3d29d1416e8.png)


![image](https://user-images.githubusercontent.com/41037283/236373167-f44747e1-cd51-4f09-ad4e-e0d12f39834f.png)

**Comment by XiaokangLei** [comment]
先预处理把图摆正

**Comment by XiaokangLei** [comment]
<img width="600" alt="微信图片_20230510084614" src="https://github.com/PaddlePaddle/PaddleOCR/assets/19248640/12819453-f720-4939-a45e-c8a520a474ec">
正常训练的图片，感觉还可以吧，DBNet的

**Comment by Ludasheng** [comment]
> @XiaokangLei 感谢大佬提供的思路，我换DBNet试试。
歪斜的图片，我用霍夫矫正了下，检测成功率会提高些。


但是还有个问题是，图片朝向问题，每个方向都有，左右朝向的还不是很理想。如下，是朝向右边的。
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41037283/ff1e6865-43f7-4914-af43-f3fe46f2d748)
经霍夫矫正后
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41037283/4899309f-cb2b-45c7-b656-cd852987206d)
