### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by guanfaqian** [PaddlePaddle/PaddleOCR#986]
python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --use_gpu=False

![image](https://user-images.githubusercontent.com/38851311/96829031-4ebd0a00-146b-11eb-96e8-0e6b93b2b48e.png)

**Comment by guanfaqian** [comment]
按百度的说什么装window需要的运行库也没用

**Comment by WenmuZhou** [comment]
shapely没有装好
