### ISSUE TITLE
c++简单推理demo，预测结果不对

### ISSUE THREAD

**Issue by PlantainZ** [PaddlePaddle/PaddleOCR#9862]
- 系统环境：win11/VS2019
- PaddleOC ver：Release/2.6
- 使用预测库：cpu_avx_mkl （windows）
- cmake ver : 3.26.3
- opencv ver : 4.6.0
- 使用推理模型：en_PP-OCRv3_rec_infer、en_PP-OCRv3_det_infer

- 2.png 图像内容如下：
![2](https://user-images.githubusercontent.com/28504294/236137571-fef5cd19-502d-4338-bbc5-6ae872342509.png)

- 对此图片的cmd预测命令及结果如下：
(base) PS C:\XXXX_CodeRepository\Business_Cache\code\PaddleOCR\deploy\cpp_infer> CHCP 65001
Active code page: 65001

(base) PS C:\XXXX_CodeRepository\Business_Cache\code\PaddleOCR\deploy\cpp_infer> .\build\Release\ppocr.exe system --det_model_dir=.\build\Release\model\en_PP-OCRv3_det_infer --rec_model_dir=.\build\Release\model\en_PP-OCRv3_rec_infer --cls_model_dir=.\build\Release\model\ch_ppocr_mobile_v2.0_cls_infer --image_dir=.\build\Release\imgs\2.png

In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320',if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
total images num: 1
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0504 15:26:15.072537 19832 fuse_pass_base.cc:57] ---  detected 33 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
I0504 15:26:15.127473 19832 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : depthwise_conv2d_14.tmp_0  size: 1920
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : tmp_5  size: 384
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_44.tmp_3  size: 1920
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_44.tmp_1  size: 1920
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_44.tmp_0  size: 1920
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : hardsigmoid_1.tmp_0  size: 384
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : hardsigmoid_3.tmp_0  size: 384
I0504 15:26:15.143617 19832 memory_optimize_pass.cc:216] Cluster name : x  size: 12
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0504 15:26:15.269950 19832 analysis_predictor.cc:1035] ======= optimize end =======
I0504 15:26:15.269950 19832 naive_executor.cc:102] ---  skip [feed], feed -> x
I0504 15:26:15.271008 19832 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
In PP-OCRv3, default rec_img_h is 48,if you use other model, you should set the param rec_img_h=32
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
I0504 15:26:15.364784 19832 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
I0504 15:26:15.364784 19832 fuse_pass_base.cc:57] ---  detected 4 subgraphs
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0504 15:26:15.372898 19832 fuse_pass_base.cc:57] ---  detected 9 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0504 15:26:15.452906 19832 fuse_pass_base.cc:57] ---  detected 19 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : tmp_3  size: 480
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_16.tmp_4  size: 6144
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : conv2d_44.tmp_0  size: 6144
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : transpose_4.tmp_0_slice_1  size: 480
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_14.tmp_4  size: 6144
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : batch_norm_25.tmp_1  size: 2048
I0504 15:26:15.479983 19832 memory_optimize_pass.cc:216] Cluster name : x  size: 576
I0504 15:26:15.489991 19832 memory_optimize_pass.cc:216] Cluster name : transpose_1.tmp_0_slice_1  size: 480
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0504 15:26:15.554940 19832 analysis_predictor.cc:1035] ======= optimize end =======
I0504 15:26:15.554940 19832 naive_executor.cc:102] ---  skip [feed], feed -> x
I0504 15:26:15.561028 19832 naive_executor.cc:102] ---  skip [softmax_2.tmp_0], fetch -> fetch
predict img: .\jlq_build\Release\imgs\2.png
0       det boxes: [[387,60],[574,65],[573,110],[386,105]] rec text: 绚捌伺月 rec score: 0.9995
1       det boxes: [[53,61],[251,71],[249,112],[51,102]] rec text: 疗月要地 rec score: 0.893072
2       det boxes: [[64,126],[293,129],[293,173],[64,170]] rec text: 诚先捌问陂地地 rec score: 0.9495
3       det boxes: [[386,125],[586,128],[585,173],[385,170]] rec text: 娇先瘸月备陂 rec score: 0.954898
4       det boxes: [[63,190],[253,192],[253,241],[63,239]] rec text: 溜瘸忖拳地 rec score: 0.999597
5       det boxes: [[388,192],[553,192],[553,240],[388,240]] rec text: 题鄙忖眼 rec score: 0.999938
6       det boxes: [[62,255],[304,265],[302,312],[60,302]] rec text: 贿先鄙地拳地要 rec score: 0.962237
7       det boxes: [[388,256],[613,260],[612,312],[387,308]] rec text: 者先地忖专问捌 rec score: 0.936085
8       det boxes: [[64,323],[270,326],[269,374],[63,371]] rec text: 廖要忖要地 rec score: 0.999955
9       det boxes: [[364,323],[566,326],[565,374],[363,371]] rec text: 疗'先捌地要 rec score: 0.952818
The detection visualized image saved in ./output//2.png

ppocr/utils/ppocr_keys_v1.tx已经改为ANSI编码格式。
源程序改动了下，加入了自己的检测string，发现这些中文并不是乱码，而是一个确切的预测结果。
（上方再跑demo时，已经将源程序恢复成官方写的样子。）
全程无报错，是否是配置的原因？？可是检查了下配置，似乎也没有什么太大的问题

**Comment by WenmuZhou** [comment]
需要将字典换成这个 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict/en_dict.txt

**Comment by PlantainZ** [comment]
> 需要将字典换成这个 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict/en_dict.txt

谢谢！！！把字典换成了您贴的这个之后，还换了一下模型，可以正常识别了！感谢您！
