### ISSUE TITLE
模型量化问题

### ISSUE THREAD

**Issue by simpleman12138** [PaddlePaddle/PaddleOCR#9869]
- 版本号/Version：PaddlePaddle 2.4.2.post112        PaddleOCR： 问题相关组件/Related components：  2.6
- 运行指令/Command Code： python deploy/slim/quantization/export_model.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml  -o Global.checkpoints=output/my_rec_slim/best_accuracy Global.save_inference_dir=./output/inference/my_rec_slim_infer
- 完整报错/Complete Error Message：  ValueError: The additional config (onnx_format) of `paddle.jit.save` is not supported.
![image](https://user-images.githubusercontent.com/61568958/236387892-85463d65-5703-448a-bc1e-bbaecd011df6.png)

**Comment by an1018** [comment]
paddle版本是什么
