### ISSUE TITLE
版面分析针对一些拍摄表格，无法识别出表格

### ISSUE THREAD

**Issue by wujushan** [PaddlePaddle/PaddleOCR#9870]
![aoliao](https://user-images.githubusercontent.com/12782418/236401070-2b0a5bce-2b87-4fee-9a53-a40baf38db95.jpg)
 
使用以下命令行对上图进行版面分析和表格恢复
> paddleocr --image_dir=aoliao.jpg --type=structure --recovery=true

在版面分析时，上图会被识别成图而非表格： 
 {'type': 'figure', 'bbox': [10, 0, 245, 195], 'img_idx': 0, 'layout': 'single'}

**Comment by xunfeng2zkj** [comment]
我试了扫描件倒是可以，把整个流水全部算在内了

**Comment by an1018** [comment]
之前基于文档类的数据集训练，这种差异较大，可以基于自己的场景训练
