### ISSUE TITLE
PPOCRV3的识别模型进行剪枝出现的问题

### ISSUE THREAD

**Issue by simpleman12138** [PaddlePaddle/PaddleOCR#9878]
对PPOCRV3的识别模型进行剪枝：python deploy/slim/prune/sensitivity_anal.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml -o Global.pretrain_weights=./output/my_rec/best_acc  Global.test_batch_size_per_card=1
报错：
![image](https://user-images.githubusercontent.com/61568958/236655548-31fea4d8-d294-4f21-a09d-835e53b64842.png)
配置文件中本来没有这个参数
期望回复，感谢

**Comment by MissPenguin** [comment]
PP-OCRv3没有适配剪枝策略，推荐直接用量化。

**Comment by simpleman12138** [comment]
文档中说明了量化不能减小模型体积，是否还有别的方法可以减小垂类场景的文本识别模型大小
