### ISSUE TITLE
关于SRN论文所用的TRW15数据集

### ISSUE THREAD

**Issue by GarrettLee** [PaddlePaddle/PaddleOCR#988]
我最近读了SRN的paper，想跑跑代码，论文里面用了TRW15作为中文数据指标，但是在网上搜索不到这个数据，想问一下在哪里可以找到这个数据呢

**Comment by tink2123** [comment]
http://icdar2015.imageplusplus.com/
数据介绍可阅读：https://arxiv.org/pdf/1506.03184.pdf

**Comment by GarrettLee** [comment]
> http://icdar2015.imageplusplus.com/
> 数据介绍可阅读：https://arxiv.org/pdf/1506.03184.pdf

这个数据下载链接好像已经失效了，打不开

**Comment by GarrettLee** [comment]
> 
> 
> http://icdar2015.imageplusplus.com/
> 数据介绍可阅读：https://arxiv.org/pdf/1506.03184.pdf

想问一下有其他有效连接吗？感谢！

**Comment by tink2123** [comment]
目前没有找到其他有效的下载链接，官方链接看起来失效了，等一等看能否修复吧。

**Comment by huihui0000** [comment]
麻烦是否可以上传下这个测试集？下载不了呢
