### ISSUE TITLE
2.6 闪退

### ISSUE THREAD

**Issue by longxinglxl** [PaddlePaddle/PaddleOCR#9880]
C:\Users\Administrator>PPOCRLabel --lang ch
[2023/05/07 18:43:33] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  F:\test\njkbsjjd\xunlian\1_1.png
DirPath in importDirImages is F:/test/njkbsjjd/xunlian
Traceback (most recent call last):
  File "D:\Python\Python310\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'

**Comment by MissPenguin** [comment]
可能是没装好，是严格按照教程安装的吗：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/PPOCRLabel/README_ch.md#12-%E5%AE%89%E8%A3%85%E4%B8%8E%E8%BF%90%E8%A1%8Cppocrlabel

可以把相关依赖全卸载重新安装一遍试试

**Comment by huangye123** [comment]
使用Python3.8 可以解决，Python3.10会有这个问题，希望官方可以改善一下Python版本兼容性

**Comment by rise-worlds** [comment]
是的，也发现这个问题，改一半报错还要重来

**Comment by XiYuan68** [comment]
`bar.setValue(bar.value() + bar.singleStep() * units)`
改成
`bar.setValue(int(bar.value() + bar.singleStep() * units))`
可以解决
