### ISSUE TITLE
请问一下大佬们如何提取识别文本框的倾斜角度

### ISSUE THREAD

**Issue by Yudaoni0** [PaddlePaddle/PaddleOCR#9883]
如题，谢谢

**Comment by WYH150123** [comment]
1. 确认文本框的宽高比，比如宽大于高2倍（可以系数调整）以上可认为是横文字方向
2. 横方向的，文本框左边两点平均，右边两点平均，即取出直线两点，通过数学计算角度即可
3. 竖方向同理

**Comment by mayurou** [comment]
怎么看出左旋还是右旋呢？
