### ISSUE TITLE
FastDeploy Serving部署ocr服务，推断速度过慢，且显存未释放

### ISSUE THREAD

**Issue by citisy** [PaddlePaddle/PaddleOCR#9885]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 9.4.0；NVIDIA GeForce RTX 3090；Driver Version: 470.182.03；CUDA Version: 11.4
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

按照教程 

- https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/README_CN.md ，部署FastDeploy Serving服务
- https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/README.md ，部署ocr服务

使用规格为1200*800的图片测试，使用FastDeploy部署的推断服务，平均一张图片约耗时2.5s；如果直接运行模型预测，平均一张图片约耗时0.5s

另外，观察资源消耗发现，服务刚启动是显存占用约1g，图片测试后，显存占用为5g左右，且服务空闲时也未释放

请问上述这种情况是否是合理的？另外，是否有相关的文档，表明使用FastDeploy部署ocr后的推断速度及资源消耗的实验数据

万分感谢。

**Comment by night-handsomer** [comment]
同问

**Comment by miknyko** [comment]
同问，使用fastdeploy贼慢，在同样的gpu机器上，比直接调用paddleocr python api慢10倍

**Comment by aixuedegege** [comment]
pend
