### ISSUE TITLE
RE Relation Extraction model only predicts a limited portion of text on document. How to enhance the model to make prediction on the whole document? 

### ISSUE THREAD

**Issue by suonbo** [PaddlePaddle/PaddleOCR#9887]
![image](https://user-images.githubusercontent.com/87938340/236771654-26fe147e-d384-4f61-b531-9282bf96b122.png)

My RE model only give predictions with the text on the top part of the document like the image above. Is there any method to make the model predict on the whole text of the document? And how to implement it on Paddle RE model training pipeline?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
