### ISSUE TITLE
Error: Failed to process the request(s) for model 'det_postprocess_0_2', message: TritonModelException: inference request batch-size must be <= 128 for 'cls_pp'

### ISSUE THREAD

**Issue by pangdahua** [PaddlePaddle/PaddleOCR#9888]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
 ubuntu 20.04 docker 1.0.6-gpu-cuda11.4-trt8.5-21.10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
 
- 运行指令/Command Code：
- 使用 grpc 客户端部分图片报错
- 
- 完整报错/Complete Error Message：
-
0508 08:41:54.435022 9471 pb_stub.cc:402] Failed to process the request(s) for model 'det_postprocess_0_1', message: TritonModelException: inference request batch-size must be <= 128 for 'cls_pp'

At:
  /ocr_serving/models/det_postprocess/1/model.py(175): execute

0508 08:41:54.555160 9471 pb_stub.cc:402] Failed to process the request(s) for model 'det_postprocess_0_1', message: TritonModelException: inference request batch-size must be <= 128 for 'cls_pp'

**Comment by gerasim13** [comment]
I have the same problem. i get error when i try to call model inference from bls python model
