### ISSUE TITLE
rec的Combined loss 怎么设置？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9890]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec的Combined loss 怎么设置？可以改善易错字符的干扰吗？
distillation比crnn更准？

**Comment by LDOUBLEV** [comment]
distill后效果会变好

combine loss参考https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml#L98-L135

**Comment by nissansz** [comment]
distill 比 combinedloss好？
