### ISSUE TITLE
哪个配置yml文件的汉字字符准确率最高?

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9894]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

哪个配置yml文件的汉字字符准确率最高?

**Comment by LDOUBLEV** [comment]
PP-OCRv3 rec
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/26592129/237010014-7b6168e7-eeef-4e60-8924-0faf5c758ffb.png">

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml

**Comment by nissansz** [comment]
想把yml中 MobileNetV1Enhance 替换为resnet 34, 要怎么改？
自己改的有错

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
