### ISSUE TITLE
这个yml文件怎么修改成res 34 back bone?

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9896]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
[MobileNetV1Enhance-Distillation.zip](https://github.com/PaddlePaddle/PaddleOCR/files/11421258/MobileNetV1Enhance-Distillation.zip)

- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by LDOUBLEV** [comment]
参考：https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/configs/rec/rec_r34_vd_none_bilstm_ctc.yml#L37-L39

**Comment by nissansz** [comment]
我照着修改了，然后训练，还是报错，可以帮忙修改一份可用的版本吗？

**Comment by nissansz** [comment]
只用改37 到39那样，其余都不用改？

我是尝试了改其余head，neck之类, loss之类要改吗？
Architecture:
  model_type: &model_type "rec"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: rec
      algorithm: CRNN
      Transform:
      Backbone:
        name: ResNet
        layers: 34
      Neck:
        name: SequenceEncoder
        encoder_type: rnn
        hidden_size: 256
      Head:       
        name: CTCHead
        fc_decay: 0
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: SVTR
      Transform:
      Backbone:
        name: MobileNetV1Enhance
        scale: 0.5
        last_conv_stride: [1, 2]
        last_pool_type: avg
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 64
                depth: 2
                hidden_dims: 120
                use_guide: True
              Head:
                fc_decay: 0.00001
          - SARHead:
              enc_dim: 512
              max_text_length: *max_text_length

**Comment by nissansz** [comment]
只改那2行，也是报错

<html><body>


[2023/05/09 14:20:31] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 500 iterations
--
177.5s | 472 | Traceback (most recent call last):
177.5s | 473 | File "../input/paddle251/PaddleOCR-release-2.5/tools/train.py", line 191, in <module>
177.5s | 474 | main(config, device, logger, vdl_writer)
177.5s | 475 | File "../input/paddle251/PaddleOCR-release-2.5/tools/train.py", line 166, in main
177.5s | 476 | eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
177.5s | 477 | File "/kaggle/input/paddle251/PaddleOCR-release-2.5/tools/program.py", line 268, in train
177.5s | 478 | loss = loss_class(preds, batch)
177.5s | 479 | File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
177.5s | 480 | return self._dygraph_call_func(*inputs, **kwargs)
177.5s | 481 | File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
177.5s | 482 | outputs = self.forward(*inputs, **kwargs)
177.5s | 483 | File "/kaggle/input/paddle251/PaddleOCR-release-2.5/ppocr/losses/combined_loss.py", line 55, in forward
177.5s | 484 | loss = loss_func(input, batch, **kargs)
177.5s | 485 | File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
177.5s | 486 | return self._dygraph_call_func(*inputs, **kwargs)
177.5s | 487 | File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
177.5s | 488 | outputs = self.forward(*inputs, **kwargs)
177.5s | 489 | File "/kaggle/input/paddle251/PaddleOCR-release-2.5/ppocr/losses/distillation_loss.py", line 107, in forward
177.5s | 490 | out2[self.dis_head])
177.5s | 491 | File "/kaggle/input/paddle251/PaddleOCR-release-2.5/ppocr/losses/basic_loss.py", line 116, in forward
177.5s | 492 | self._kldiv(log_out1, out2) + self._kldiv(log_out2, out1)) / 2.0
177.5s | 493 | File "/kaggle/input/paddle251/PaddleOCR-release-2.5/ppocr/losses/basic_loss.py", line 102, in _kldiv
177.5s | 494 | loss = target * (paddle.log(target + eps) - x)
177.5s | 495 | File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
177.5s | 496 | return math_op(self, other_var, 'axis', axis)
177.5s | 497 | ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 80, 63466] and the shape of Y = [16, 40, 63466]. Received [80] in X is not equal to [40] in Y at i:1.
177.5s | 498 | [Hint: Expected x_dims_array[i] == y_dims_array[i] \|\| x_dims_array[i] <= 1 \|\| y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] \|\| x_dims_array[i] <= 1 \|\| y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
177.5s | 499 | [operator < elementwise_sub > error]
181.2s | 500 | /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2935: FutureWarning: --Exporter.preprocessors=["remove_papermill_header.RemovePapermillHeader"] for containers is deprecated in traitlets 5.0. You can pass `--Exporter.preprocessors item` ... multiple times to add items to a list.
181.2s | 501 | FutureWarning,


</body>
</html>
