### ISSUE TITLE
版面还原进行时报错，无法应用到其他数据集

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleOCR#9900]
我在自己的数据集完成了版面分析模型的训练和评估以及模型推理，但是在进行版面还原时遇到了下面的报错
![P%VF$21RM%91ASA9)A KII0](https://user-images.githubusercontent.com/56247915/237028523-52338340-d03e-4ea8-88f4-ec816781d0ad.png)
这个错误显示前后输入的张量不一致，但是我仔细检查了好几遍，我采用的步骤都是按照官方文档来的，但是走到这一步就一直报错，同样的问题，我看到也有很多人用自己的数据集不能完成版面还原的测试，还请官方的大神能注意一下这个问题，因为个人感觉是不是开源的框架不支持个人数据集进行训练再实现版面还原呢，请官方大神重视一下这个问题，希望能得到解答，真的是尝试了太多的方法了 ，感谢！

**Comment by AIwang666** [comment]
@andyjpaddle

**Comment by AIwang666** [comment]
@andyjpaddle

**Comment by AIwang666** [comment]
@andyjpaddle

**Comment by AIwang666** [comment]
请回复一下这个问题 @andyjpaddle

**Comment by an1018** [comment]
使用detection进行推理报错吗

**Comment by AIwang666** [comment]
> 使用detection进行推理报错吗

并不报错

**Comment by an1018** [comment]
cpu报错吗

**Comment by an1018** [comment]
参数添加use_gpu=False，还有可以试一下原模型gpu是否报错

**Comment by AIwang666** [comment]
> 参数添加use_gpu=False，还有可以试一下原模型gpu是否报错

我试了一下 用CPU进行还原的话仍然报同样的错误，张量没有初始化 @an1018

**Comment by liuhuan-gl** [comment]
会不会和配置文件里面的resize有关系
