### ISSUE TITLE
训练维语OCR识别模型，acc一直都是1.0000

### ISSUE THREAD

**Issue by kongfnajie** [PaddlePaddle/PaddleOCR#9901]
我用维语数据集训练了很多OCR识别模型，都是从零开始训练的，有的模型可以正常训练出成果，acc是稳步提升的，如SVTR、ABINet、RFL等。但有的模型不行，acc一开始就一直是1.0000，如RobustScanner、SEED等....loss是逐步下降的，就是acc显示不正确，训练集测试集上的acc一直都是1.0000，请问这是什么原因，是计算acc的模块出错了吗，是不是因为是维语才出现这样的问题，那为什么有的模型正常有的模型出错呢

**Comment by kongfnajie** [comment]
作者可以解答一下我的问题吗

**Comment by kongfnajie** [comment]
我的维语数据集也不小，大概有50w张图片，应该不是数据集的问题

**Comment by kongfnajie** [comment]
[train.log](https://github.com/PaddlePaddle/PaddleOCR/files/11429110/train.log)

**Comment by kongfnajie** [comment]
训练了几十轮的模型，单独进行测试，测试结果也是1.0000。尝试了把数据转换成LMDB格式，也没有解决问题。

**Comment by kongfnajie** [comment]
是不是有的模型不兼容维语这种从右往左的顺序？ 类似阿拉伯语

**Comment by andyjpaddle** [comment]
从右往左需要把标签反一下，这样能保留语义信息

**Comment by kongfnajie** [comment]
> 我比较好奇的是，到底识别的对不对 @kongfnajie

虽然acc一直是0，但是训练过程中loss是逐步下降的，我没测试过，但应该是训练出了一定的精度
