### ISSUE TITLE
安装包依赖冲突

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#9906]
CentOS8 / Python3.10.9
paddlepaddle 2.4.2
下载PaddleOCR最新代码
安装依赖时
paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible
protobuf改为3.20.0解决
随后安装PaddleOCR
[PaddleOCR-release-2.6]# python3 setup.py install
error: protobuf 3.20.0 is installed but protobuf>=3.20.2 is required by {'onnx'}
这怎么解决

**Comment by Matiz7** [comment]
OCR似乎可以用，不知是不是影响训练

**Comment by arckalsun** [comment]
请问解决了吗

**Comment by Matiz7** [comment]
> arckalsun
protobuf==3.20.0 现在OCR可以用，但不清楚报错是怎么回事
反正我只是使用现成的模型，不做训练
