### ISSUE TITLE
FCE algorithm can not be used

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9907]
There is a bug in using FCE algorithm as detector
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/48731e89-9eb1-4dc4-967b-a7d4f8f6b8eb)

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
