### ISSUE TITLE
识别效果很差

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9908]
使用pp-ocrv3 对几张简单的文本进行识别，识别错误很多，公开的模型效果这么差吗
![e1](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/a09e2f94-b8da-4e2c-9e61-2b383123796c)

**Comment by XiaokangLei** [comment]
看起来是检测切掉了一部分，调一下检测试试

**Comment by ericosmic** [comment]
@XiaokangLei   用rec模型直接识别手工剪切的数据也会出现同样的错误，说明rec模型本身对一些字识别精度就是不行。

**Comment by XiaokangLei** [comment]
> @XiaokangLei 用rec模型直接识别手工剪切的数据也会出现同样的错误，说明rec模型本身对一些字识别精度就是不行。

发个原图我试试

**Comment by ericosmic** [comment]
@XiaokangLei file:///home/eric/AI/bug1/e14.png
file:///home/eric/AI/bug1/e15.png

**Comment by ericosmic** [comment]
@XiaokangLei  
![e16](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/6a24d03a-287e-4b51-a326-7d4af1f2b292)
![e14](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/b06623e8-c3eb-49cd-ae7f-5160ff776d76)
