### ISSUE TITLE
直接推理中默认的算法可以修改吗？

### ISSUE THREAD

**Issue by luoyq6** [PaddlePaddle/PaddleOCR#9911]
直接推理中默认的模型可以修改吗？想修改成好一点的算法，比如检测将DB换成DB++,这样子做要不要更换模型的best_accuracy.目前我用的推理配置文件如图所示，模型：ch_PP-OCRv3_det_infer
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110521846/14356f08-9840-4e28-9ad2-b827bda21fee)

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/110521846/fafc28d2-9d1a-4493-9adf-f83866755107)

**Comment by UserWangZz** [comment]
模型和推理配置文件需要对应
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
