### ISSUE TITLE
[Question] Page Dewarping

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#9915]
Thanks for excellent repo!!

I have used PaddleOCR  to recognize text in image.
If I have good image, it works extremely great, but skewed image algorithm not works well.
I don't know whether repo has function or option like this.

I am very happy if you can give me more information about this.

Thank you very much.

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
