### ISSUE TITLE
训练检测模型的时候，要是没有目标的图片该如何标注标签

### ISSUE THREAD

**Issue by wqp113** [PaddlePaddle/PaddleOCR#9920]
你好，我有两个问题：
1. 训练检测模型的时候，要是没有目标的图片该如何标注标签标注文件
2. 标签中的point四个点是左上角开始顺时针旋转吗，要是标注成左下角开始，四个点逆时针旋转用于训练会不会有什么问题

**Comment by 6098669** [comment]
应该没有问题，有问题你在下面说一下

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
