### ISSUE TITLE
Centerloss 导出时12722 这个是什么意思？模型的字符数？必须和原模型字符数匹配才能用于combinedloss?

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9923]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

get center:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 12721/12722 [49:14<00:00,  4.31it/s]

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
