### ISSUE TITLE
合成训练集所用的字典和训练中所用字典不同对训练效果有影响吗

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9926]
请问如果合成训练数据所用的字典和训练的字典不同，但生成的训练集中字符都可以在训练字典中找到，会对训练效果有影响吗

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
