### ISSUE TITLE
Finetune Rec模型，为什么一开始的acc=0

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9928]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

训练数据是用text-tender生成的，字典也是用项目默认， 使用了ch_PP-OCRv3_rec_train作为预训练模型，这种条件下的finetune，acc应该一开始很高才对。可是实际训练中acc一开始是0,后面才慢慢升高。 

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=ppocr_models/pretrain/ch_PP-OCRv3_rec_train/best_accuracy
- 完整报错/Complete Error Message： 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/cf3e750b-9a5a-456c-b3e4-8af658bf554b)

**Comment by data-ant** [comment]
为什么呢？
