### ISSUE TITLE
not find model file path ./inference/ch_ppocr_mobile_v1.1_rec_infer/model

### ISSUE THREAD

**Issue by shaoshenchen** [PaddlePaddle/PaddleOCR#993]
从 [inference模型下载](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md#2inference%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD) 下载推理模型并且自行解压到 `inference` 目录下，但得不到解压后的文件结构。我的文件结构是这样的
```
|-inference
    |-ch_ppocr_mobile_v1.1_det_infer
        |- model
        |- params
    |-ch_ppocr_mobile_v1.1_rec_infer    # 这是一个1_rec_infer类型的文件
    |-ch_ppocr_mobile-v1.1_cls_infer
        |- ._model
        |- ._params
        |- model
        |- params
```

然后运行代码就会报错
```
!python tools/infer/predict_system.py \
    --image_dir="./doc/imgs/11.jpg" \
    --det_model_dir="./inference/ch_ppocr_mobile_v1.1_det_infer"  \
    --rec_model_dir="./inference/ch_ppocr_mobile_v1.1_rec_infer" \
    --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer" \
    --use_angle_cls=True \
    --use_space_char=True
```

**Comment by WenmuZhou** [comment]
看起来缺个rec的模型，这个下载了吗

**Comment by shaoshenchen** [comment]
> 看起来缺个rec的模型，这个下载了吗

我从表格中下载来的文件只有这么一个rec文件
```
    |-ch_ppocr_mobile_v1.1_rec_infer    # 这是一个1_rec_infer类型的文件

```

**Comment by WenmuZhou** [comment]
重新下载一下吧，我从表格里的链接下载的是正常的
https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_infer.tar

**Comment by shaoshenchen** [comment]
![image](https://user-images.githubusercontent.com/45918719/97109349-bb573380-170d-11eb-82c1-93a5128e2ab4.png)
这个就是我下载来的文件，里面只有一个文件，请问该如何使用呢？

**Comment by WenmuZhou** [comment]
再解压一次

**Comment by littletomatodonkey** [comment]
想问下可以了吗？不行的话就下载这个zip包解压把
[ch_ppocr_mobile_v1.1_rec_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5440154/ch_ppocr_mobile_v1.1_rec_infer.zip)

**Comment by shaoshenchen** [comment]
> 想问下可以了吗？不行的话就下载这个zip包解压把
> [ch_ppocr_mobile_v1.1_rec_infer.zip](https://github.com/PaddlePaddle/PaddleOCR/files/5440154/ch_ppocr_mobile_v1.1_rec_infer.zip)

非常感谢！这个zip包是有效的！现在可以运行了
