### ISSUE TITLE
印章文字识别模型样本是否要进行处理

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#9933]
印章文字识别模型样本是否要处理（SVTR）成如下图：
![test11](https://github.com/PaddlePaddle/PaddleOCR/assets/72127773/0d1413df-9e73-4ea2-af3e-f727ac66c4e7)
label.txt如下：
img/test11.png	云南省农村信用社
还是直接截取，如下图：
![aaaa](https://github.com/PaddlePaddle/PaddleOCR/assets/72127773/bb943e18-da26-4e05-8c63-dbc4ced69ead)
原图如下：
![24_1](https://github.com/PaddlePaddle/PaddleOCR/assets/72127773/dad9b4c3-50f9-435a-aace-abcf3effdecb)

**Comment by UserWangZz** [comment]
矫正成水平最好
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
