### ISSUE TITLE
这个报错怎么解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9936]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：kaggle
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

ImportError: cannot import name 'QhullError' from 'scipy.spatial' (/opt/conda/lib/python3.10/site-packages/scipy/spatial/__init__.py)

**Comment by OttomanZ** [comment]
Hi, I'm getting the same error on my Kaggle Notebook.
