### ISSUE TITLE
关于表格识别的一些问题想请教

### ISSUE THREAD

**Issue by wu-yz** [PaddlePaddle/PaddleOCR#9937]
1、好未来表格识别数据集下不了，可以重新放一下链接吗？
2、发现表格识别的SLANet模型对于跨行和跨列的表格识别的不是很好，想问问要如何对修改过的模型进行训练呢？
3、WTW中文场景表格数据集要如何转换？
谢谢！

**Comment by nissansz** [comment]
官方自带的tablemaster效果怎么样？

**Comment by wu-yz** [comment]
> 官方自带的tablemaster效果怎么样？

只能识别英文表格

**Comment by nissansz** [comment]
有表格线补齐的代码吗？有的表格线残缺，或者虚线那种变成实线

**Comment by nissansz** [comment]
有表格线补齐的代码吗？有的表格线残缺，或者虚线那种变成实线

**Comment by wu-yz** [comment]
> 有表格线补齐的代码吗？有的表格线残缺，或者虚线那种变成实线

我跑的结果没有表格线

**Comment by nissansz** [comment]
pip install Polygon3 这个在windows安装失败？

**Comment by microdoge** [comment]
> 1、好未来表格识别数据集下不了，可以重新放一下链接吗？ 2、发现表格识别的SLANet模型对于跨行和跨列的表格识别的不是很好，想问问要如何对修改过的模型进行训练呢？ 3、WTW中文场景表格数据集要如何转换？ 谢谢！
你好, 跨行和跨列的表格我也有同样的问题, 请问是怎么解决的
