### ISSUE TITLE
身份证地址检测出多行的怎么识别？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#9940]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by XiaokangLei** [comment]
一行一行处理
