### ISSUE TITLE
训练过程中cuda报错

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9942]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：`python tools/train.py -c configs/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=ppocr_models/pretrain/ch_PP-OCRv3_rec_train/best_accuracy`
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/35327931/d3713251-b3c2-4a42-b4ff-a968ddd772a2)

之后导入paddle就会报错：

**Comment by LDOUBLEV** [comment]
如果是训练中报错，问题比较难排查
如果import paddle就报错，卸载了重新安装试试

**Comment by ericosmic** [comment]
@LDOUBLEV  这个算是paddle的版本bug吗， 目前运行的训练都会在训练中遇到这个问题导致自动中断， 然后重启电脑paddle就就恢复正常。
