### ISSUE TITLE
直接下载使用推理模型OK，下载预训练模型然后重新导出后不可用(没做二次训练直接导出)

### ISSUE THREAD

**Issue by colinlwz** [PaddlePaddle/PaddleOCR#9943]
直接使用推理模型：

1.下载版面CDLA推理模型
wget https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
tar xf picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar

2.通过PaddleOCR使用CDLA推理模型进行pdf版面恢复
cd PaddleOCR/ppstructure/
python3 predict_system.py
--layout_model_dir=inference/picodet_lcnet_x1_0_fgd_layout_cdla_infer
--layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt
--vis_font_path=../doc/fonts/simfang.ttf
--recovery=True
--det_model_dir=inference/ch_PP-OCRv3_det_infer
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer
--table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt
--output=../output/
--image_dir=/home/aistudio/test/zx/testtable.pdf

3.运行结果：OK，成功转出word文档

下载版面CDLA预训练模型并重新导出推理模型：

1.下载CDLA预训练模型
wget https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams

2.通过PaddleDetection直接将预训练模型导出成infer模型
cd PaddleDetection/
python3 tools/export_model.py
-c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml
-o weights=/home/aistudio/PaddleDetection/pretrained_model/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams
--output_dir=/home/aistudio/PaddleDetection/pretrained_model/

3.通过PaddleOCR使用CDLA推理模型进行pdf版面恢复
cd PaddleOCR/ppstructure/
python3 predict_system.py
--layout_model_dir=/home/aistudio/PaddleDetection/pretrained_model/picodet_lcnet_x1_0_layout \ #替换成导出的模型
--layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt
--vis_font_path=../doc/fonts/simfang.ttf
--recovery=True
--det_model_dir=inference/ch_PP-OCRv3_det_infer
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer
--table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt
--output=../output/
--image_dir=/home/aistudio/test/zx/testtable.pdf

4.运行结果：
InvalidArgumentError: The conv2d_fusion Op's Input Variable Input contains uninitialized Tensor.
[Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2094)
[operator < conv2d_fusion > error]

请问有人碰到过类似问题吗，是否是导出模型这个步骤有问题

**Comment by colinlwz** [comment]
另外我分别比对了以下三种模型的推理和版面恢复命令测试情况：
模型一：CDLA原始推理模型
模型二：CDLA原始预训练模型导出
模型三：CDLA预训练模型基础上增加自己的数据集进行训练，然后再模型导出

**1.推理测试：**
测试命令：
python3 deploy/python/infer.py \
    --model_dir=output_inference/picodet_lcnet_x1_0_layout/ \ #这里分别改成三个模型
    --image_file=docs/images/layout.jpg \
测试结果：
模型一：能正常在图片上标识版面位置
模型二：图片上午任何标识
模型三：能正常在图片上标识版面位置，并且比模型一效果好(基本达到我训练的数据效果)

**1.版面恢复测试：**
测试命令：
python3 predict_system.py
--layout_model_dir=/home/aistudio/PaddleDetection/pretrained_model/picodet_lcnet_x1_0_layout \  #这里分别改成三个模型
--layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt
--vis_font_path=../doc/fonts/simfang.ttf
--recovery=True
--det_model_dir=inference/ch_PP-OCRv3_det_infer
--rec_model_dir=inference/ch_PP-OCRv3_rec_infer
--table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer
--rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt
--output=../output/
--image_dir=/home/aistudio/test/zx/testtable.pdf
测试结果：
模型一：能正常导出word
模型二：报错InvalidArgumentError: The conv2d_fusion Op's Input Variable Input contains uninitialized Tensor.
模型三：报错InvalidArgumentError: The conv2d_fusion Op's Input Variable Input contains uninitialized Tensor.

**Comment by AIwang666** [comment]
我也遇到这个问题了 你解决了吗 @ @LDOUBLEV

**Comment by colinlwz** [comment]
我很多方法都试了，都不行。开始怀疑是FGD训练问题，改用FGD训练也不行，又怀疑是label字典问题，改成同样的字典还是不行。

我自己打标测试训练的模型，推理测试没问题，也能看出训练有效果，但一跟paddleocr集成就报错。
然后以为是自己训练过程有问题，就不训练直接将原始预训练模型导出，结果不仅跟paddleocr集成报错，连推理都没效果了，还不如我训练过的模型。

感觉官方应该出个能用的简单训练project demo，自己训练出问题了也好跟官方的demo测试对比方便排查问题

**Comment by isaone** [comment]
我遇到这个问题了，怎么解决了呢  @LDOUBLEV

**Comment by AIwang666** [comment]
@LDOUBLEV 能来看一下这个问题 解决一下嘛

**Comment by wzgwy** [comment]
我也遇到了这个问题，请问一下有解决了的吗？
