### ISSUE TITLE
无法添加助手，助手无响应，无法入群

### ISSUE THREAD

**Issue by znipps** [PaddlePaddle/PaddleOCR#9945]
无法添加助手，助手无响应，无法入群

**Comment by LDOUBLEV** [comment]
小助手可能在忙，等等看
我分享给你一个群二维码，你试试
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26592129/07dc2220-443a-4b74-a4d4-e3f1bcf61a2f)

**Comment by znipps** [comment]
已解决

**Comment by 892745513** [comment]
> 小助手可能在忙，等等看 我分享给你一个群二维码，你试试 ![image](https://user-images.githubusercontent.com/26592129/238252319-07dc2220-443a-4b74-a4d4-e3f1bcf61a2f.png)

兄弟这个二维码过期了，能再发下么，百度的小助手加了一点反应都没有
