### ISSUE TITLE
Custom model in PPOCRLabel

### ISSUE THREAD

**Issue by thanhsang298** [PaddlePaddle/PaddleOCR#9947]
Hi guys,
Could you give me the approach to use my custom model that trained by your framework into tool label.
Thanks and best regard.

**Comment by livingbody** [comment]
## 使用自定义模型

[https://github.com/PaddlePaddle/PaddleOCR/blob/static/doc/doc_ch/whl.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B](https://github.com/PaddlePaddle/PaddleOCR/blob/static/doc/doc_ch/whl.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)

**Comment by livingbody** [comment]
![360截图20230630235724325](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/313a3820-86dd-48a4-8262-8fcc216f15ea)

**Comment by shiyutang** [comment]
Do you mean that you want to use your model in OCRlabel or in the ppocr process?

**Comment by livingbody** [comment]
yes, use your own model in PPOCRLabel !

**Comment by thanhsang298** [comment]
> yes, use your own model in PPOCRLabel !

Did you solve it? Could I close this issue?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.

**Comment by mundekaralgorisys123** [comment]
> Do you mean that you want to use your model in OCRlabel or in the ppocr process?

yes
