### ISSUE TITLE
python调用ocr接口参数不能够将所有识别的地方都打上框

### ISSUE THREAD

**Issue by wulei1997** [PaddlePaddle/PaddleOCR#9948]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos8
- 版本号/Version：Paddle2.4.2：  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：ocr = PaddleOCR(use_angle_cls=True, lang="ch")
- 完整报错/Complete Error Message：
- 
![result](https://github.com/PaddlePaddle/PaddleOCR/assets/53397694/9e457752-a401-4fc1-9a35-a405bc1366f1)

**Comment by XiaokangLei** [comment]
不科学，我的就可以

**Comment by wulei1997** [comment]
> 不科学，我的就可以

ocr版本, 参数配置，用的哪个模型？

**Comment by XiaokangLei** [comment]
> > 不科学，我的就可以
> 
> ocr版本, 参数配置，用的哪个模型？

你放个原图，我给你看结果，这种文档文字是检测任务中最easy的，我们都没漏过，都不用考虑优化这种

**Comment by wulei1997** [comment]
> 
图在这

![41200348](https://github.com/PaddlePaddle/PaddleOCR/assets/53397694/a0fdeadf-19f9-468f-bf9a-895d6495fb22)

**Comment by wulei1997** [comment]
> > > 不科学，我的就可以
> > 
> > 
> > ocr版本, 参数配置，用的哪个模型？
> 
> 你放个原图，我给你看结果，这种文档文字是检测任务中最easy的，我们都没漏过，都不用考虑优化这种

原图在这
![41200348](https://github.com/PaddlePaddle/PaddleOCR/assets/53397694/d3833262-ba0c-4ca9-909c-d027c238de89)

**Comment by XiaokangLei** [comment]
> > 不科学，我的就可以
> 
> ocr版本, 参数配置，用的哪个模型？

V2版本的模型，参数det_db_thresh=0.1, det_db_box_thresh=0.4, det_db_unclip_ratio=2.0,det_db_score_mode='slow', use_dilation='True'
![2023-05-16_14-30-57 894025](https://github.com/PaddlePaddle/PaddleOCR/assets/19248640/d99c252a-a305-407c-8044-6e6cd6fffdb7)

**Comment by 1061302569** [comment]
@XiaokangLei  大神可以帮我把这里面的数字1也调出来吗，数量里面的数字容易漏检

![1677470677 40454362](https://github.com/PaddlePaddle/PaddleOCR/assets/44227598/f0a7b894-e357-4f8d-84bc-26b00b2209f4)

**Comment by XiaokangLei** [comment]
> @XiaokangLei 大神可以帮我把这里面的数字1也调出来吗，数量里面的数字容易漏检
> 
> ![1677470677 40454362](https://user-images.githubusercontent.com/44227598/240174776-f0a7b894-e357-4f8d-84bc-26b00b2209f4.jpg)

![2023-05-24_18-22-36 953350](https://github.com/PaddlePaddle/PaddleOCR/assets/19248640/cb89526e-b1eb-4435-b09b-d0c67c7867ea)
第二个轻量模型稍差一点

**Comment by 1061302569** [comment]
@XiaokangLei  牛啊，我调参数咋就调不出这样的效果，容易把别的检测框调合并
