### ISSUE TITLE
structure_system识别表格丢失数据

### ISSUE THREAD

**Issue by shiyun123456789** [PaddlePaddle/PaddleOCR#9949]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  2.4.2.post112PaddleOCR：2.6.1.0 问题相关组件/Related components：
- 运行指令/Command Code：nohup hub serving start -c config/tableconfig.json >log 2>&1 &
- 完整报错/Complete Error Message：
hubserving 部署 structure_system 读取表格时，当存在空列时，其他数据行丢失数据严重。
![1](https://github.com/PaddlePaddle/PaddleOCR/assets/31406086/bb801ad2-6d73-4b56-9ca3-0682576392da)
![2](https://github.com/PaddlePaddle/PaddleOCR/assets/31406086/852a7f81-890f-4d05-aca8-7c61a3977206)
![result](https://github.com/PaddlePaddle/PaddleOCR/assets/31406086/3e13d841-36e3-4e15-aff2-a9c4e00eb3f2)

structure_system下param配置入下：
def read_params():
    cfg = table_read_params()
    cfg.det_algorithm = "DB"
    cfg.det_model_dir = "./inference/ch_PP-OCRv3_det_infer/"
    cfg.det_limit_side_len = 960
    cfg.det_limit_type = 'max'

    # DB parmas
    cfg.det_db_thresh = 0.3
    cfg.det_db_box_thresh = 0.5
    cfg.det_db_unclip_ratio = 1.6
    cfg.use_dilation = False
    cfg.det_db_score_mode = "fast"
          
    # EAST parmas
    cfg.det_east_score_thresh = 0.8
    cfg.det_east_cover_thresh = 0.1
    cfg.det_east_nms_thresh = 0.2

    # params for text recognizer
    cfg.rec_algorithm = "CRNN"
    cfg.rec_model_dir = "./inference/ch_PP-OCRv3_rec_infer/"

    cfg.rec_image_shape = "3, 48, 320"
    cfg.rec_batch_num = 6
    cfg.max_text_length = 25 
    
    cfg.rec_char_dict_path = "./ppocr/utils/ppocr_keys_v1.txt"
    cfg.use_space_char = True
    
    # params for text classifier
    cfg.use_angle_cls = True
    cfg.cls_model_dir = "./inference/trained/ch_ppocr_server_v1.0_cls_infer/"
    cfg.cls_image_shape = "3, 48, 192"
    cfg.label_list = ['0','90','180','270']
    cfg.cls_batch_num = 30
    cfg.cls_thresh = 0.9

    cfg.use_pdserving = False
    cfg.use_tensorrt = False
    cfg.drop_score = 0.5
    # params for layout parser model
    cfg.layout_model_dir = './inference/picodet_lcnet_x1_0_fgd_layout_table_infer/'
    cfg.layout_dict_path = './ppocr/utils/dict/layout_dict/layout_table_dict.txt'
    cfg.layout_score_threshold = 0.5
    cfg.layout_nms_threshold = 0.5

    cfg.mode = 'structure'
    cfg.output = './output'
    return cfg

**Comment by tink2123** [comment]
检测训练数据中缺少空列的数据，目前这种场景上模型效果确实不够好。建议通过finetune来解决此类问题
