### ISSUE TITLE
pdserving方式部署，多线程会出现线程安全问题，多进程会出现内存泄漏问题

### ISSUE THREAD

**Issue by 784117672** [PaddlePaddle/PaddleOCR#9950]
我通过pdserving方式部署之后，在java中通过http方式调用(调用的接口为http://118.190.xxx.xxx:8888/ocr/prediction)。
当config中的is_thread_op为多线程模式时，多线程调用会出现线程安全问题，会读到其他线程的数据（内存正常）。
当config中的is_thread_op为多进程模式时，多线程调用，会导致内存无法释放。
环境：
contos7
python3.7
部署方式：pdserving
启动命令：python3 web_service.py cpu --config=config.yml --enable_mkldnn=True &>log.txt &

配置文件 config.yml：

![1684142791740](https://github.com/PaddlePaddle/PaddleOCR/assets/14973988/abd95d81-1cf7-477b-aa27-69293ea53382)

![1684142864696](https://github.com/PaddlePaddle/PaddleOCR/assets/14973988/89b5b82a-5e99-4f48-bda1-0d8d9d9c2d57)

**Comment by bxjxxyy** [comment]
我也是当config中的is_thread_op为false时，多线程调用，会随机出现内存占用达到100%导致被kill的情况。根据查的资料和其他issues里面说是因为启用了mkldnn的问题。
但是没有找到除了关闭mkldnn之外的其他解决方案。
