### ISSUE TITLE
tablemaster推理慢

### ISSUE THREAD

**Issue by yedaorman** [PaddlePaddle/PaddleOCR#9952]
TableMaster 在进行Python推理时，速度较慢，使用P40 gpu推理时间达到7-8s，而mmocr实现的tablemaster时间在1s左右，请问这个是什么原因造成的呢。

**Comment by panliang5020** [comment]
> TableMaster 在进行Python推理时，速度较慢，使用P40 gpu推理时间达到7-8s，而mmocr实现的tablemaster时间在1s左右，请问这个是什么原因造成的呢。

可以请教一下tableMaster训练数据怎么构建的吗

**Comment by allen20200111** [comment]
在Tesla T4 时间上也是7-8s，这个时间很夸张

**Comment by allen20200111** [comment]
8使用了TensorRT加速，速度还是一样需要7-8s
