### ISSUE TITLE
ppocrv3 的识别模型支持变长数据训练吗

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleOCR#9954]
使用默认的ch_PP-OCRv3_rec_distillation.yml 和ppocr_models/pretrain/ch_PP-OCRv3_rec_train模型 进行中文训练， 并在配置文件中设置use_space_char=true， 是否支持变长的训练数据呢？ 目前使用自己合成的15k的训练数据进行fine-tune， 生成的模型acc只有0.8左右，实际预测结果非常糟糕，甚至远不如公开模型。
另外一个疑惑是使用预训练模型进行fine-tune训练， 为什么开始的acc=0 呢？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
