### ISSUE TITLE
怎么提取合同尾部署名单位地址信息

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#9958]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49382323/24240770-4c68-48ae-b3d2-2539930ad516)

如上图，合同尾部署名信息在分栏操作后，单位地址信息可能会跨行，怎么将识别内容后将地址信息提取出来后，可以合并为一个整体即能得到结果"湖南省长沙市岳麓区岳麓大道中电软件XX路XX号",尝试过用PP-Structure做文档内容分析，原本想着它可能将其识别成表格作为一个整体但结果也不理想。请问我可以怎么做能达到其目的，谢谢~

**Comment by andyjpaddle** [comment]
参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md

**Comment by kerry-weic** [comment]
@andyjpaddle 我先看看，多谢

**Comment by dizhenx** [comment]
> 参考文档 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md

只有命令行推理预测，没有配套的前后端界面，可以上传文件或者拍照进行OCR识别吗？
