### ISSUE TITLE
同一个图片里有多种文字，字体，除了训练全部文字的合并模型外，如果按不同字体分别训练单独的模型，怎样合并结果？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9965]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

同一个图片里有多种文字，字体，除了训练全部文字的合并模型外，如果按不同字体分别训练单独的模型，怎样合并结果？

**Comment by hbulaoma** [comment]
同一种语言的不同字体，一般混合训练就可以了，像中、日、韩、英这些文字其实也可以混合到一起训练。分开训练只有在通用模型不佳的情况下才会考虑，先分类再调用对应模型识别

**Comment by nissansz** [comment]
混合到一起训练，会有不同字体造成的干扰。怎样解决比较好？

分开训练，先分类再调用对应模型识别。怎样根据图片得到字体分类，然后调用对应模型。字体名识别比较困难。有好办法吗？

**Comment by hbulaoma** [comment]
除了手写体中文和印刷体中文考虑字体分类，如果只是印刷体，根本不需要考虑分开训练。横排和竖排的都可以训练到一起，不同字体算啥

**Comment by nissansz** [comment]
你有训练好的多语种多字体模型分享吗？
多字体一起训练没有单字体准

**Comment by hbulaoma** [comment]
不要考虑多字体分类，除非你是想输出字体类型，用来版面还原。多字体没有单字体准，从样本上去考虑解决方法，如果是中文字符，效果不好的字体整点样本100-200万条文本行，识别率和单字体没啥区别。像中、日、韩这些语言都是可以合到一起训练的，当然相比单语种识别率会有下降，也是在低质量样本情况下才有影响，正常质量的图像识别率也没啥区别。字体分类，参考那个https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_language_classification.md

**Comment by nissansz** [comment]
你有中日韩英混合模型可以分享吗？

例如
日语字体，
ハ，和八
在一个字体下的ハ 可能和另一个字体的八非常接近。

类似例子应该还有很多。

**Comment by nissansz** [comment]
你有中日韩的较全字符集和文本短句文件吗？
