### ISSUE TITLE
ppocr v3的量化模型使用

### ISSUE THREAD

**Issue by lingl-space** [PaddlePaddle/PaddleOCR#9970]
请问，使用OCR v3的量化模型进行predict_system文件的推理时，需要配置那些参数么？

在使用相同参数进行推理时，Slim模型进行的推理过程会比原模型慢上很多很多，无论是中英文模型还是纯英文模型。

按理来说，经过量化的slim模型不是减少了计算量么？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
