### ISSUE TITLE
GPU无法训练，AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by colinchou2020** [PaddlePaddle/PaddleOCR#9973]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/50770300/31204239-0f97-4366-ac8e-a0dc85ce9741)

**Comment by LaysonShen** [comment]
yaml文件里面global那块把use_gpu改成False

**Comment by CrazyD-0804** [comment]
Please install paddlepaddle-gpu

**Comment by LouisVA** [comment]
Add to the above comment, the right version. In my case with cuda 11.8: https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/windows-pip_en.html#gpu
