### ISSUE TITLE
求助表格矫正

### ISSUE THREAD

**Issue by xunfeng2zkj** [PaddlePaddle/PaddleOCR#9977]
![bb__QQ20230517-104735](https://github.com/PaddlePaddle/PaddleOCR/assets/22878414/4fc23ddb-c8b9-4ff6-851f-71201fec001c)

我有一张这样的图片，然后想把每个单元格都定位出来，然后进行矫正，不知道这样是否可行，有没有大佬有过类似经验

**Comment by nissansz** [comment]
有办法了吗？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
