### ISSUE TITLE
转onnx模型的操作符集问题

### ISSUE THREAD

**Issue by Tomhardy13** [PaddlePaddle/PaddleOCR#9982]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu18.04
- 版本号/Version：PaddleOCR v2.5 paddlepaddle=2.3.2 paddle2onnx=1.0.2
- 运行指令/Command Code：paddle2onnx --model_dir ./inference/license_plate/ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./models/onnx/model.onnx --opset_version 12 --input_shape_dict=[1,3,32,120] --enable_onnx_checker True

能成功转onnx，但是onnx部署某些边缘端出现“RuntimeError: onnx model's opset_import.domain must be ai.onnx but is Paddle.”
打印了onnx_model.opset_import[0].domain和onnx_model.opset_import[1].domain
第一个输出是空，表明是ONNX默认的操作符集ai.onnx，第二个输出Paddle。我猜测是这个操作符集导致的错误，请问如何解决这个bug呢？我发现其他框架转onnx只有模型的ai.onnx操作符集

**Comment by Tomhardy13** [comment]
另外我直接用paddle.onnx.export()转的onnx模型同样包含Paddle操作符集

**Comment by cuicheng01** [comment]
可以升级到最新的paddle2onnx来解决哈
