### ISSUE TITLE
如何从现有一般rec resnet34模型蒸馏出student模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9983]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

如何从现有一般rec resnet34模型蒸馏出student模型？

**Comment by cuicheng01** [comment]
可以再说的具体一点吗，比如是识别还是检测，使用哪种蒸馏方式？

**Comment by nissansz** [comment]
识别 rec
