### ISSUE TITLE
Converting ch_PP-OCRv3_rec_slim to onnx or openvino

### ISSUE THREAD

**Issue by yash-khurana** [PaddlePaddle/PaddleOCR#9984]
Is it possible to convert the model ch_PP-OCRv3_rec_slim to onnx? or is it possible to infer using opencv in cpp? or onnxruntime in cpp?
I tried to convert to onnx using paddle2onnx but I get error. Is it not supported?

**Comment by cuicheng01** [comment]
Hi，please update the latest paddle2onnx to try converting

**Comment by yash-khurana** [comment]
@cuicheng01 Thank you for your reply. I will try again. Is it possible to convert the en_number_mobile_slim_v2.0_rec model to onnx?
