### ISSUE TITLE
识别训练中日韩英，有没有较全的字符集和短语集，句子集？在哪里下载

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9987]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

识别训练中日韩英，有没有较全的字符集和短语集，句子集？在哪里下载

**Comment by livingbody** [comment]
https://rrc.cvc.uab.es/?ch=15&com=downloads

![360截图20230709005519797](https://github.com/PaddlePaddle/PaddleOCR/assets/8059137/0c7732db-f27a-41e2-92f4-349dc4f8e797)

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
