### ISSUE TITLE
PaddleOCR识别建议

### ISSUE THREAD

**Issue by Puhouchen** [PaddlePaddle/PaddleOCR#9990]
例如下图中“仅供参考”几个字无法被识别，该模型对于比较浅的字或水印很难识别，大家有没有好的使用建议呀
![3](https://github.com/PaddlePaddle/PaddleOCR/assets/102594073/2b088ba6-f894-42da-bf46-de2236aec3a4)

**Comment by WYH150123** [comment]
可以考虑通过一些CV的方式（比如一些滤波，滤镜的算法）把对应水印浅文字给加强
