### ISSUE TITLE
PGNet on non-English texts?

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/PaddleOCR#9991]
Hello, 
PGNet works fine on English (Latin) languages, but I'm having troubles with other languages, such as Chinese, Japanese, Korean and Russian.  
Looking at the docs, only English images are used.  
Is this a limitation of the algorithm or there's some configuration needed?

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
