### ISSUE TITLE
rec识别模型，已有resnet34模型，如何distillation, 裁剪，简化，centerloss等提高准确率？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#9997]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

rec识别模型，已有resnet34模型，如何distillation, 裁剪，简化，等提高准确率？

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
