### ISSUE TITLE
PPOCRLabel运行问题

### ISSUE THREAD

**Issue by smalllyingspinach** [PaddlePaddle/PaddleOCR#9998]
(paddle_label) D:\Studying\Group Project\paddleocr\paddleocr\PPOCRLabel>python PPOCRLabel.py --lang ch
PPOCRLabel.py:1035: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1794: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:1825: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:2011: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \

Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "D:\environment\Anaconda\envs\paddle_label\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\environment\Anaconda\envs\paddle_label\lib\site-packages\paddleocr\paddleocr.py", line 38, in <module>
    from ppocr.utils.logging import get_logger
ModuleNotFoundError: No module named 'ppocr.utils.logging'

**Comment by smalllyingspinach** [comment]
文件是在的，但在paddleocr.py的里面怎么都导入不进去，
`ppocr = importlib.import_module('.', package='ppocr')`这一步是动态导入

**Comment by livingbody** [comment]
# 请先安装 PaddleOCR
```
from ppocr.utils.logging import get_logger
ModuleNotFoundError: No module named 'ppocr.utils.logging'```

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
